circular_driven_cavity.cc File Reference
Classes
class QuarterCircleDrivenCavityProblem< ELEMENT >
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
Namespaces
namespace Global_Physical_Variables
Namespace for physical parameters.
Functions
Vector< double > Global_Physical_Variables::Gravity (2)
Gravity vector.
void Global_Physical_Variables::body_force (const double &time, const Vector< double > &x, Vector< double > &result)
Functional body force.
void Global_Physical_Variables::zero_body_force (const double &time, const Vector< double > &x, Vector< double > &result)
Zero functional body force.
int main ()
Driver for QuarterCircleDrivenCavityProblem test problem.
Variables
double Global_Physical_Variables::Re =100
Reynolds number.
double Global_Physical_Variables::Re_invFr =100
Reynolds/Froude number.
Function Documentation
main()
int main ()
Driver for QuarterCircleDrivenCavityProblem test problem.
Definition at line 288 of file circular_driven_cavity.cc.
References Global_Physical_Variables::body_force(), QuarterCircleDrivenCavityProblem< ELEMENT >::doc_solution(), Global_Physical_Variables::Gravity(), and Global_Physical_Variables::zero_body_force().