QuarterCircleDrivenCavityProblem2< ELEMENT > Class Template Reference
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
Public Member Functions
QuarterCircleDrivenCavityProblem2 (NavierStokesEquations< 2 >::NavierStokesBodyForceFctPt body_force_fct_pt)
Constructor.
~QuarterCircleDrivenCavityProblem2 ()
Destructor: Empty.
void actions_after_newton_solve ()
Update the after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve. (Re-)set velocity boundary conditions just to be on the safe side...
void actions_after_adapt ()
After adaptation: Unpin pressure and pin redudant pressure dofs.
void doc_solution (DocInfo &doc_info)
Doc the solution.
Private Member Functions
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
Private Attributes
NavierStokesEquations< 2 >::NavierStokesBodyForceFctPt Body_force_fct_pt
Pointer to body force function.
Detailed Description
template<class ELEMENT>
class QuarterCircleDrivenCavityProblem2< ELEMENT >
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
Driven cavity problem in quarter circle domain, templated by element type.
Definition at line 84 of file circular_driven_cavity2.cc.
Constructor & Destructor Documentation
QuarterCircleDrivenCavityProblem2()
template<class ELEMENT >
QuarterCircleDrivenCavityProblem2< ELEMENT >::QuarterCircleDrivenCavityProblem2 (NavierStokesEquations< 2 >::NavierStokesBodyForceFctPt body_force_fct_pt)
Constructor.
Constructor for driven cavity problem in quarter circle domain.
Definition at line 185 of file circular_driven_cavity2.cc.
References QuarterCircleDrivenCavityProblem2< ELEMENT >::Body_force_fct_pt, QuarterCircleDrivenCavityProblem2< ELEMENT >::fix_pressure(), Global_Physical_Variables2::Gravity(), Global_Physical_Variables2::Re, and Global_Physical_Variables2::Re_invFr.
 QuarterCircleDrivenCavityProblem2()
template<class ELEMENT >
QuarterCircleDrivenCavityProblem2< ELEMENT >::~QuarterCircleDrivenCavityProblem2 () [inline]
Destructor: Empty.
Definition at line 94 of file circular_driven_cavity2.cc.
Member Function Documentation
actions_after_adapt()
template<class ELEMENT >
void QuarterCircleDrivenCavityProblem2< ELEMENT >::actions_after_adapt () [inline]
After adaptation: Unpin pressure and pin redudant pressure dofs.
Definition at line 146 of file circular_driven_cavity2.cc.
actions_after_newton_solve()
template<class ELEMENT >
void QuarterCircleDrivenCavityProblem2< ELEMENT >::actions_after_newton_solve () [inline]
Update the after solve (empty)
Definition at line 97 of file circular_driven_cavity2.cc.
actions_before_newton_solve()
template<class ELEMENT >
void QuarterCircleDrivenCavityProblem2< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve. (Re-)set velocity boundary conditions just to be on the safe side...
Definition at line 101 of file circular_driven_cavity2.cc.
doc_solution()
template<class ELEMENT >
void QuarterCircleDrivenCavityProblem2< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 276 of file circular_driven_cavity2.cc.
Referenced by main().
fix_pressure()
template<class ELEMENT >
void QuarterCircleDrivenCavityProblem2< ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) [inline], [private]
Fix pressure in element e at pressure dof pdof and set to pvalue.
Definition at line 169 of file circular_driven_cavity2.cc.
Referenced by QuarterCircleDrivenCavityProblem2< ELEMENT >::QuarterCircleDrivenCavityProblem2().
Member Data Documentation
Body_force_fct_pt
template<class ELEMENT >
NavierStokesEquations<2>::NavierStokesBodyForceFctPt QuarterCircleDrivenCavityProblem2< ELEMENT >::Body_force_fct_pt [private]
Pointer to body force function.
Definition at line 166 of file circular_driven_cavity2.cc.
Referenced by QuarterCircleDrivenCavityProblem2< ELEMENT >::QuarterCircleDrivenCavityProblem2().
The documentation for this class was generated from the following file:
circular_driven_cavity2.cc