QuarterCircleDrivenCavityProblem< ELEMENT > Class Template Reference
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
Public Member Functions
QuarterCircleDrivenCavityProblem (NavierStokesEquations< 2 >::NavierStokesBodyForceFctPt body_force_fct_pt)
Constructor.
~QuarterCircleDrivenCavityProblem ()
Destructor: Empty.
void actions_after_newton_solve ()
Update the after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve. (Re-)set velocity boundary conditions just to be on the safe side...
void actions_after_adapt ()
After adaptation: Unpin pressure and pin redudant pressure dofs.
void doc_solution (DocInfo &doc_info)
Doc the solution.
Private Member Functions
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
Private Attributes
NavierStokesEquations< 2 >::NavierStokesBodyForceFctPt Body_force_fct_pt
Pointer to body force function.
Detailed Description
template<class ELEMENT>
class QuarterCircleDrivenCavityProblem< ELEMENT >
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
Driven cavity problem in quarter circle domain, templated by element type.
Definition at line 84 of file circular_driven_cavity.cc.
Constructor & Destructor Documentation
QuarterCircleDrivenCavityProblem()
template<class ELEMENT >
QuarterCircleDrivenCavityProblem< ELEMENT >::QuarterCircleDrivenCavityProblem (NavierStokesEquations< 2 >::NavierStokesBodyForceFctPt body_force_fct_pt)
Constructor.
Constructor for driven cavity problem in quarter circle domain.
Definition at line 172 of file circular_driven_cavity.cc.
References QuarterCircleDrivenCavityProblem< ELEMENT >::Body_force_fct_pt, QuarterCircleDrivenCavityProblem< ELEMENT >::fix_pressure(), Global_Physical_Variables::Gravity(), Global_Physical_Variables::Re, and Global_Physical_Variables::Re_invFr.
 QuarterCircleDrivenCavityProblem()
template<class ELEMENT >
QuarterCircleDrivenCavityProblem< ELEMENT >::~QuarterCircleDrivenCavityProblem () [inline]
Destructor: Empty.
Definition at line 94 of file circular_driven_cavity.cc.
Member Function Documentation
actions_after_adapt()
template<class ELEMENT >
void QuarterCircleDrivenCavityProblem< ELEMENT >::actions_after_adapt () [inline]
After adaptation: Unpin pressure and pin redudant pressure dofs.
Definition at line 133 of file circular_driven_cavity.cc.
actions_after_newton_solve()
template<class ELEMENT >
void QuarterCircleDrivenCavityProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the after solve (empty)
Definition at line 97 of file circular_driven_cavity.cc.
actions_before_newton_solve()
template<class ELEMENT >
void QuarterCircleDrivenCavityProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve. (Re-)set velocity boundary conditions just to be on the safe side...
Definition at line 101 of file circular_driven_cavity.cc.
doc_solution()
template<class ELEMENT >
void QuarterCircleDrivenCavityProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 263 of file circular_driven_cavity.cc.
Referenced by main().
fix_pressure()
template<class ELEMENT >
void QuarterCircleDrivenCavityProblem< ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) [inline], [private]
Fix pressure in element e at pressure dof pdof and set to pvalue.
Definition at line 156 of file circular_driven_cavity.cc.
Referenced by QuarterCircleDrivenCavityProblem< ELEMENT >::QuarterCircleDrivenCavityProblem().
Member Data Documentation
Body_force_fct_pt
template<class ELEMENT >
NavierStokesEquations<2>::NavierStokesBodyForceFctPt QuarterCircleDrivenCavityProblem< ELEMENT >::Body_force_fct_pt [private]
Pointer to body force function.
Definition at line 153 of file circular_driven_cavity.cc.
Referenced by QuarterCircleDrivenCavityProblem< ELEMENT >::QuarterCircleDrivenCavityProblem().
The documentation for this class was generated from the following file:
circular_driven_cavity.cc