Global_Physical_Variables2 Namespace Reference
Namespace for physical parameters.
Functions
Vector< double > Gravity (2)
Gravity vector.
void body_force (const double &time, const Vector< double > &x, Vector< double > &result)
Functional body force.
void zero_body_force (const double &time, const Vector< double > &x, Vector< double > &result)
Zero functional body force.
Variables
double Re =100
Reynolds number.
double Re_invFr =100
Reynolds/Froude number.
Detailed Description
Namespace for physical parameters.
Function Documentation
body_force()
void Global_Physical_Variables2::body_force (const double & time, const Vector< double > & x, Vector< double > & result)
Functional body force.
Definition at line 58 of file circular_driven_cavity2.cc.
References Re_invFr.
Referenced by main().
Gravity()
Vector< double > Global_Physical_Variables2::Gravity (2)
Gravity vector.
Referenced by main(), and QuarterCircleDrivenCavityProblem2< ELEMENT >::QuarterCircleDrivenCavityProblem2().
zero_body_force()
void Global_Physical_Variables2::zero_body_force (const double & time, const Vector< double > & x, Vector< double > & result)
Zero functional body force.
Definition at line 66 of file circular_driven_cavity2.cc.
Referenced by main().
Variable Documentation
Re
double Global_Physical_Variables2::Re =100
Reynolds number.
Definition at line 49 of file circular_driven_cavity2.cc.
Referenced by QuarterCircleDrivenCavityProblem2< ELEMENT >::QuarterCircleDrivenCavityProblem2().
Re_invFr
double Global_Physical_Variables2::Re_invFr =100
Reynolds/Froude number.
Definition at line 52 of file circular_driven_cavity2.cc.
Referenced by body_force(), and QuarterCircleDrivenCavityProblem2< ELEMENT >::QuarterCircleDrivenCavityProblem2().