FSIChannelWithLeafletProblem< ELEMENT > Class Template Reference
//////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
Public Member Functions
FSIChannelWithLeafletProblem (const double &lleft, const double &lright, const double &hleaflet, const double &htot, const unsigned &nleft, const unsigned &nright, const unsigned &ny1, const unsigned &ny2, const double &x_0)
Constructor: Pass the lenght of the domain at the left of the leaflet lleft,the lenght of the domain at the right of the leaflet lright,the height of the leaflet hleaflet, the total height of the domain htot, the number of macro-elements at the left of the leaflet nleft, the number of macro-elements at the right of the leaflet nright, the number of macro-elements under hleaflet ny1, the number of macro-elements above hleaflet ny2, the abscissa of the origin of the leaflet x_0.
~FSIChannelWithLeafletProblem ()
Destructor empty.
void actions_after_newton_solve ()
Actions after solve (empty)
void actions_before_newton_solve ()
Actions before solve (empty)
void actions_after_adapt ()
Actions after adaptation.
OneDLagrangianMesh< FSIHermiteBeamElement > * wall_mesh_pt ()
Access function to the wall mesh.
RefineableAlgebraicChannelWithLeafletMesh< ELEMENT > * fluid_mesh_pt ()
Access function to fluid mesh.
void doc_solution (DocInfo &doc_info, ofstream &trace)
Doc the solution.
void actions_before_implicit_timestep ()
Update the inflow velocity.
void actions_before_newton_convergence_check ()
Update before checking Newton convergence: Update the nodal positions in the fluid mesh in response to possible changes in the wall shape.
Private Attributes
RefineableAlgebraicChannelWithLeafletMesh< ELEMENT > * Fluid_mesh_pt
Pointer to the fluid mesh.
OneDLagrangianMesh< FSIHermiteBeamElement > * Wall_mesh_pt
Pointer to the `wall` mesh.
GeomObject * Leaflet_pt
Pointer to the GeomObject that represents the wall.
double Htot
Total height of the domain.
Detailed Description
template<class ELEMENT>
class FSIChannelWithLeafletProblem< ELEMENT >
//////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
FSI leaflet in channel
Definition at line 164 of file fsi_channel_with_leaflet.cc.
Constructor & Destructor Documentation
FSIChannelWithLeafletProblem()
template<class ELEMENT >
FSIChannelWithLeafletProblem< ELEMENT >::FSIChannelWithLeafletProblem (const double & lleft, const double & lright, const double & hleaflet, const double & htot, const unsigned & nleft, const unsigned & nright, const unsigned & ny1, const unsigned & ny2, const double & x_0)
Constructor: Pass the lenght of the domain at the left of the leaflet lleft,the lenght of the domain at the right of the leaflet lright,the height of the leaflet hleaflet, the total height of the domain htot, the number of macro-elements at the left of the leaflet nleft, the number of macro-elements at the right of the leaflet nright, the number of macro-elements under hleaflet ny1, the number of macro-elements above hleaflet ny2, the abscissa of the origin of the leaflet x_0.
Constructor.
Definition at line 265 of file fsi_channel_with_leaflet.cc.
References FSIChannelWithLeafletProblem< ELEMENT >::Fluid_mesh_pt, Global_Physical_Variables::H, Global_Physical_Variables::Q, Global_Physical_Variables::Re, Global_Physical_Variables::ReSt, FSIChannelWithLeafletProblem< ELEMENT >::wall_mesh_pt(), and FSIChannelWithLeafletProblem< ELEMENT >::Wall_mesh_pt.
 FSIChannelWithLeafletProblem()
template<class ELEMENT >
FSIChannelWithLeafletProblem< ELEMENT >::~FSIChannelWithLeafletProblem () [inline]
Destructor empty.
Definition at line 185 of file fsi_channel_with_leaflet.cc.
Member Function Documentation
actions_after_adapt()
template<class ELEMENT >
void FSIChannelWithLeafletProblem< ELEMENT >::actions_after_adapt
Actions after adaptation.
Actions_after_adapt()
Definition at line 572 of file fsi_channel_with_leaflet.cc.
actions_after_newton_solve()
template<class ELEMENT >
void FSIChannelWithLeafletProblem< ELEMENT >::actions_after_newton_solve () [inline]
Actions after solve (empty)
Definition at line 188 of file fsi_channel_with_leaflet.cc.
actions_before_implicit_timestep()
template<class ELEMENT >
void FSIChannelWithLeafletProblem< ELEMENT >::actions_before_implicit_timestep () [inline]
Update the inflow velocity.
Definition at line 213 of file fsi_channel_with_leaflet.cc.
References FSIChannelWithLeafletProblem< ELEMENT >::Fluid_mesh_pt, Global_Physical_Variables::flux(), and FSIChannelWithLeafletProblem< ELEMENT >::Htot.
actions_before_newton_convergence_check()
template<class ELEMENT >
void FSIChannelWithLeafletProblem< ELEMENT >::actions_before_newton_convergence_check () [inline]
Update before checking Newton convergence: Update the nodal positions in the fluid mesh in response to possible changes in the wall shape.
Definition at line 236 of file fsi_channel_with_leaflet.cc.
References FSIChannelWithLeafletProblem< ELEMENT >::Fluid_mesh_pt.
actions_before_newton_solve()
template<class ELEMENT >
void FSIChannelWithLeafletProblem< ELEMENT >::actions_before_newton_solve () [inline]
Actions before solve (empty)
Definition at line 191 of file fsi_channel_with_leaflet.cc.
doc_solution()
template<class ELEMENT >
void FSIChannelWithLeafletProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace)
Doc the solution.
Definition at line 633 of file fsi_channel_with_leaflet.cc.
References Global_Physical_Variables::flux().
fluid_mesh_pt()
template<class ELEMENT >
RefineableAlgebraicChannelWithLeafletMesh< ELEMENT > * FSIChannelWithLeafletProblem< ELEMENT >::fluid_mesh_pt () [inline]
Access function to fluid mesh.
Definition at line 203 of file fsi_channel_with_leaflet.cc.
References FSIChannelWithLeafletProblem< ELEMENT >::Fluid_mesh_pt.
wall_mesh_pt()
template<class ELEMENT >
OneDLagrangianMesh< FSIHermiteBeamElement > * FSIChannelWithLeafletProblem< ELEMENT >::wall_mesh_pt () [inline]
Access function to the wall mesh.
Definition at line 197 of file fsi_channel_with_leaflet.cc.
References FSIChannelWithLeafletProblem< ELEMENT >::Wall_mesh_pt.
Referenced by FSIChannelWithLeafletProblem< ELEMENT >::FSIChannelWithLeafletProblem().
Member Data Documentation
Fluid_mesh_pt
template<class ELEMENT >
RefineableAlgebraicChannelWithLeafletMesh<ELEMENT>* FSIChannelWithLeafletProblem< ELEMENT >::Fluid_mesh_pt [private]
Pointer to the fluid mesh.
Definition at line 244 of file fsi_channel_with_leaflet.cc.
Referenced by FSIChannelWithLeafletProblem< ELEMENT >::actions_before_implicit_timestep(), FSIChannelWithLeafletProblem< ELEMENT >::actions_before_newton_convergence_check(), FSIChannelWithLeafletProblem< ELEMENT >::fluid_mesh_pt(), and FSIChannelWithLeafletProblem< ELEMENT >::FSIChannelWithLeafletProblem().
Htot
template<class ELEMENT >
double FSIChannelWithLeafletProblem< ELEMENT >::Htot [private]
Total height of the domain.
Definition at line 253 of file fsi_channel_with_leaflet.cc.
Referenced by FSIChannelWithLeafletProblem< ELEMENT >::actions_before_implicit_timestep().
Leaflet_pt
template<class ELEMENT >
GeomObject* FSIChannelWithLeafletProblem< ELEMENT >::Leaflet_pt [private]
Pointer to the GeomObject that represents the wall.
Definition at line 250 of file fsi_channel_with_leaflet.cc.
Wall_mesh_pt
template<class ELEMENT >
OneDLagrangianMesh<FSIHermiteBeamElement>* FSIChannelWithLeafletProblem< ELEMENT >::Wall_mesh_pt [private]
Pointer to the `wall` mesh.
Definition at line 247 of file fsi_channel_with_leaflet.cc.
Referenced by FSIChannelWithLeafletProblem< ELEMENT >::FSIChannelWithLeafletProblem(), and FSIChannelWithLeafletProblem< ELEMENT >::wall_mesh_pt().
The documentation for this class was generated from the following file:
fsi_channel_with_leaflet.cc