HarmonicEquations Class Reference
A class for all elements that solve the simple one-dimensional eigenvalue problem.
Public Member Functions
HarmonicEquations ()
Empty Constructor.
virtual double u (const unsigned &n) const
Access function: Eigenfunction value at local node n Note that solving the eigenproblem does not assign values to this storage space. It is used for output purposes only.
void output (ostream &outfile)
Output the eigenfunction with default number of plot points.
void output (ostream &outfile, const unsigned &nplot)
Output FE representation of soln: x,y,u or x,y,z,u at Nplot plot points.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Assemble the contributions to the jacobian and mass matrices.
double interpolated_u (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
Protected Member Functions
virtual double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
virtual int u_local_eqn (const unsigned &n)
Access function that returns the local equation number of the unknown in the problem. Default is to assume that it is the first (only) value stored at the node.
Detailed Description
A class for all elements that solve the simple one-dimensional eigenvalue problem.
 \frac{\partial^2 u}{\partial x_i^2}  + \lambda u = 0 
 These elements are very closely related to the Poisson elements and could inherit from them. They are here developed from scratch for pedagogical purposes. This class contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
Definition at line 68 of file harmonic.cc.
Constructor & Destructor Documentation
HarmonicEquations()
HarmonicEquations::HarmonicEquations () [inline]
Empty Constructor.
Definition at line 73 of file harmonic.cc.
Member Function Documentation
dshape_eulerian()
virtual double HarmonicEquations::dshape_eulerian (const Vector< double > & s, Shape & psi, DShape & dpsidx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in QHarmonicElement< NNODE_1D >.
dshape_eulerian_at_knot()
virtual double HarmonicEquations::dshape_eulerian_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsidx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in QHarmonicElement< NNODE_1D >.
Referenced by fill_in_contribution_to_jacobian_and_mass_matrix().
fill_in_contribution_to_jacobian_and_mass_matrix()
void HarmonicEquations::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline]
Assemble the contributions to the jacobian and mass matrices.
Definition at line 113 of file harmonic.cc.
References dshape_eulerian_at_knot(), and u_local_eqn().
interpolated_u()
double HarmonicEquations::interpolated_u (const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s.
Definition at line 168 of file harmonic.cc.
References interpolated_u(), and u().
Referenced by interpolated_u(), and output().
output() [1/2]
void HarmonicEquations::output (ostream & outfile) [inline]
Output the eigenfunction with default number of plot points.
Definition at line 82 of file harmonic.cc.
References output().
Referenced by output(), QHarmonicElement< NNODE_1D >::output(), and QHarmonicElement< NNODE_1D >::output().
output() [2/2]
void HarmonicEquations::output (ostream & outfile, const unsigned & nplot) [inline]
Output FE representation of soln: x,y,u or x,y,z,u at Nplot plot points.
Definition at line 90 of file harmonic.cc.
References interpolated_u().
u()
virtual double HarmonicEquations::u (const unsigned & n) const [inline], [virtual]
Access function: Eigenfunction value at local node n Note that solving the eigenproblem does not assign values to this storage space. It is used for output purposes only.
Definition at line 78 of file harmonic.cc.
Referenced by interpolated_u().
u_local_eqn()
virtual int HarmonicEquations::u_local_eqn (const unsigned & n) [inline], [protected], [virtual]
Access function that returns the local equation number of the unknown in the problem. Default is to assume that it is the first (only) value stored at the node.
Definition at line 205 of file harmonic.cc.
Referenced by fill_in_contribution_to_jacobian_and_mass_matrix().
The documentation for this class was generated from the following file:
harmonic.cc