RefineableCylinderAndInterfaceMesh< ELEMENT > Class Template Reference
Public Member Functions
RefineableCylinderAndInterfaceMesh (const double &length, const double &height, TimeStepper *time_stepper_pt)
virtual ~RefineableCylinderAndInterfaceMesh ()
Destructor: Empty.
Public Member Functions inherited from CylinderAndInterfaceMesh< ELEMENT >
CylinderAndInterfaceDomain * domain_pt ()
CylinderAndInterfaceMesh (const double &length, const double &height, TimeStepper *time_stepper_pt)
Additional Inherited Members
Protected Attributes inherited from CylinderAndInterfaceMesh< ELEMENT >
CylinderAndInterfaceDomain * Domain_pt
Detailed Description
template<class ELEMENT>
class RefineableCylinderAndInterfaceMesh< ELEMENT >
Definition at line 685 of file adaptive_interface.cc.
Constructor & Destructor Documentation
RefineableCylinderAndInterfaceMesh()
template<class ELEMENT >
RefineableCylinderAndInterfaceMesh< ELEMENT >::RefineableCylinderAndInterfaceMesh (const double & length, const double & height, TimeStepper * time_stepper_pt) [inline]
Definition at line 691 of file adaptive_interface.cc.
References CylinderAndInterfaceMesh< ELEMENT >::Domain_pt.
Referenced by RefineableRotatingCylinderProblem< ELEMENT >::finish_problem_setup(), RefineableRotatingCylinderProblem< ELEMENT >::RefineableRotatingCylinderProblem(), and RefineableRotatingCylinderProblem< ELEMENT >::solve().
~RefineableCylinderAndInterfaceMesh()
template<class ELEMENT >
virtual RefineableCylinderAndInterfaceMesh< ELEMENT >::~RefineableCylinderAndInterfaceMesh () [inline], [virtual]
Destructor: Empty.
Definition at line 716 of file adaptive_interface.cc.
The documentation for this class was generated from the following file:
adaptive_interface.cc