ProblemParameters Namespace Reference
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
Functions
Vector< double > Coeff (N_terms, 1.0)
Coefficients in the exact solution.
std::complex< double > I (0.0, 1.0)
Imaginary unit.
void get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector of size 2, containing real and imag parts.
void exact_minus_dudr (const Vector< double > &x, std::complex< double > &flux)
Get -du/dr (spherical r) for exact solution. Equal to prescribed flux on inner boundary.
std::complex< double > Magnitude (100.0, 100.0)
Point source magnitude (Complex)
Variables
string Directory =`RESLT`
Output directory.
double K_squared = 10.0
Frequency.
double PML_thickness =4.0
Default physical PML thickness.
unsigned Nel_pml =15
Default number of elements within PMLs.
double Element_area = 0.1
Target area for initial mesh.
int N_fourier =0
The default Fourier wave number.
unsigned N_terms =6
Number of terms in the exact solution.
double R_source = 2.0
Radial position of point source.
double Z_source = 2.0
Axial position of point source.
Detailed Description
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
Namespace for the Fourier decomposed Helmholtz problem parameters
Function Documentation
Coeff()
Vector< double > ProblemParameters::Coeff (N_terms , 1. 0)
Coefficients in the exact solution.
Referenced by exact_minus_dudr(), and get_exact_u().
exact_minus_dudr()
void ProblemParameters::exact_minus_dudr (const Vector< double > & x, std::complex< double > & flux)
Get -du/dr (spherical r) for exact solution. Equal to prescribed flux on inner boundary.
Definition at line 147 of file oscillating_sphere.cc.
References Coeff(), I(), K_squared, N_fourier, and N_terms.
Referenced by PMLFourierDecomposedHelmholtzProblem< ELEMENT >::create_flux_elements_on_inner_boundary().
get_exact_u()
void ProblemParameters::get_exact_u (const Vector< double > & x, Vector< double > & u)
Exact solution as a Vector of size 2, containing real and imag parts.
Definition at line 86 of file oscillating_sphere.cc.
References Coeff(), I(), K_squared, N_fourier, and N_terms.
Referenced by PMLFourierDecomposedHelmholtzProblem< ELEMENT >::doc_solution().
I()
std::complex< double > ProblemParameters::I (0. 0, 1. 0)
Imaginary unit.
Referenced by exact_minus_dudr(), and get_exact_u().
Magnitude()
std::complex< double > ProblemParameters::Magnitude (100. 0, 100. 0)
Point source magnitude (Complex)
Referenced by PMLFourierDecomposedHelmholtzProblem< ELEMENT >::setup_point_source().
Variable Documentation
Directory
string ProblemParameters::Directory =`RESLT`
Output directory.
Definition at line 59 of file oscillating_sphere.cc.
Referenced by main(), and PMLFourierDecomposedHelmholtzProblem< ELEMENT >::PMLFourierDecomposedHelmholtzProblem().
Element_area
double ProblemParameters::Element_area = 0.1
Target area for initial mesh.
Definition at line 71 of file oscillating_sphere.cc.
Referenced by main(), and PMLFourierDecomposedHelmholtzProblem< ELEMENT >::PMLFourierDecomposedHelmholtzProblem().
K_squared
double ProblemParameters::K_squared = 10.0
Frequency.
Definition at line 62 of file oscillating_sphere.cc.
Referenced by PMLFourierDecomposedHelmholtzProblem< ELEMENT >::complete_problem_setup(), exact_minus_dudr(), get_exact_u(), main(), and PMLFourierDecomposedHelmholtzProblem< ELEMENT >::PMLFourierDecomposedHelmholtzProblem().
N_fourier
int ProblemParameters::N_fourier =0
The default Fourier wave number.
Definition at line 74 of file oscillating_sphere.cc.
Referenced by PMLFourierDecomposedHelmholtzProblem< ELEMENT >::complete_problem_setup(), exact_minus_dudr(), get_exact_u(), main(), and PMLFourierDecomposedHelmholtzProblem< ELEMENT >::setup_point_source().
N_terms
unsigned ProblemParameters::N_terms =6
Number of terms in the exact solution.
Definition at line 77 of file oscillating_sphere.cc.
Referenced by exact_minus_dudr(), and get_exact_u().
Nel_pml
unsigned ProblemParameters::Nel_pml =15
Default number of elements within PMLs.
Definition at line 68 of file oscillating_sphere.cc.
Referenced by PMLFourierDecomposedHelmholtzProblem< ELEMENT >::create_pml_meshes(), and main().
PML_thickness
double ProblemParameters::PML_thickness =4.0
Default physical PML thickness.
Definition at line 65 of file oscillating_sphere.cc.
Referenced by PMLFourierDecomposedHelmholtzProblem< ELEMENT >::create_pml_meshes(), and main().
R_source
double ProblemParameters::R_source = 2.0
Radial position of point source.
Definition at line 206 of file oscillating_sphere.cc.
Referenced by PMLFourierDecomposedHelmholtzProblem< ELEMENT >::setup_point_source().
Z_source
double ProblemParameters::Z_source = 2.0
Axial position of point source.
Definition at line 209 of file oscillating_sphere.cc.
Referenced by PMLFourierDecomposedHelmholtzProblem< ELEMENT >::setup_point_source().