OscEllipseProblem< ELEMENT, TIMESTEPPER > Class Template Reference
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Public Member Functions
OscEllipseProblem ()
Constructor.
~OscEllipseProblem ()
Destructor (empty)
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_newton_solve ()
Update problem specs before solve (empty)
void actions_before_adapt ()
Actions before adapt (empty)
void actions_after_adapt ()
Actions after adaptation, pin relevant pressures.
void actions_before_implicit_timestep ()
Update the problem specs before next timestep.
void actions_after_implicit_timestep ()
Update the problem specs after timestep (empty)
void doc_solution (DocInfo &doc_info)
Doc the solution.
void unsteady_run (DocInfo &doc_info)
Timestepping loop.
void set_initial_condition ()
Set initial condition.
Private Member Functions
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
Private Attributes
GeomObject * Wall_pt
Pointer to GeomObject that specifies the domain bondary.
Detailed Description
template<class ELEMENT, class TIMESTEPPER>
class OscEllipseProblem< ELEMENT, TIMESTEPPER >
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Navier-Stokes problem in an oscillating ellipse domain.
Definition at line 178 of file osc_quarter_ellipse.cc.
Constructor & Destructor Documentation
OscEllipseProblem()
template<class ELEMENT , class TIMESTEPPER >
OscEllipseProblem< ELEMENT, TIMESTEPPER >::OscEllipseProblem
Constructor.
Constructor for Navier-Stokes problem on an oscillating ellipse domain.
Definition at line 269 of file osc_quarter_ellipse.cc.
References Global_Physical_Variables::A, Global_Physical_Variables::A_hat, Global_Physical_Variables::Re, Global_Physical_Variables::ReSt, and Global_Physical_Variables::T.
 OscEllipseProblem()
template<class ELEMENT , class TIMESTEPPER >
OscEllipseProblem< ELEMENT, TIMESTEPPER >::~OscEllipseProblem () [inline]
Destructor (empty)
Definition at line 187 of file osc_quarter_ellipse.cc.
Member Function Documentation
actions_after_adapt()
template<class ELEMENT , class TIMESTEPPER >
void OscEllipseProblem< ELEMENT, TIMESTEPPER >::actions_after_adapt () [inline]
Actions after adaptation, pin relevant pressures.
Definition at line 199 of file osc_quarter_ellipse.cc.
actions_after_implicit_timestep()
template<class ELEMENT , class TIMESTEPPER >
void OscEllipseProblem< ELEMENT, TIMESTEPPER >::actions_after_implicit_timestep () [inline]
Update the problem specs after timestep (empty)
Definition at line 236 of file osc_quarter_ellipse.cc.
actions_after_newton_solve()
template<class ELEMENT , class TIMESTEPPER >
void OscEllipseProblem< ELEMENT, TIMESTEPPER >::actions_after_newton_solve () [inline]
Update the problem specs after solve (empty)
Definition at line 190 of file osc_quarter_ellipse.cc.
actions_before_adapt()
template<class ELEMENT , class TIMESTEPPER >
void OscEllipseProblem< ELEMENT, TIMESTEPPER >::actions_before_adapt () [inline]
Actions before adapt (empty)
Definition at line 196 of file osc_quarter_ellipse.cc.
actions_before_implicit_timestep()
template<class ELEMENT , class TIMESTEPPER >
void OscEllipseProblem< ELEMENT, TIMESTEPPER >::actions_before_implicit_timestep () [inline]
Update the problem specs before next timestep.
Definition at line 216 of file osc_quarter_ellipse.cc.
actions_before_newton_solve()
template<class ELEMENT , class TIMESTEPPER >
void OscEllipseProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_solve () [inline]
Update problem specs before solve (empty)
Definition at line 193 of file osc_quarter_ellipse.cc.
doc_solution()
template<class ELEMENT , class TIMESTEPPER >
void OscEllipseProblem< ELEMENT, TIMESTEPPER >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 466 of file osc_quarter_ellipse.cc.
References Global_Physical_Variables::get_exact_u().
fix_pressure()
template<class ELEMENT , class TIMESTEPPER >
void OscEllipseProblem< ELEMENT, TIMESTEPPER >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) [inline], [private]
Fix pressure in element e at pressure dof pdof and set to pvalue.
Definition at line 250 of file osc_quarter_ellipse.cc.
set_initial_condition()
template<class ELEMENT , class TIMESTEPPER >
void OscEllipseProblem< ELEMENT, TIMESTEPPER >::set_initial_condition
Set initial condition.
Set initial condition: Assign previous and current values from exact solution.
Definition at line 392 of file osc_quarter_ellipse.cc.
References Global_Physical_Variables::get_exact_u().
unsteady_run()
template<class ELEMENT , class TIMESTEPPER >
void OscEllipseProblem< ELEMENT, TIMESTEPPER >::unsteady_run (DocInfo & doc_info)
Timestepping loop.
Unsteady run.
Definition at line 558 of file osc_quarter_ellipse.cc.
Referenced by main().
Member Data Documentation
Wall_pt
template<class ELEMENT , class TIMESTEPPER >
GeomObject* OscEllipseProblem< ELEMENT, TIMESTEPPER >::Wall_pt [private]
Pointer to GeomObject that specifies the domain bondary.
Definition at line 259 of file osc_quarter_ellipse.cc.
The documentation for this class was generated from the following file:
osc_quarter_ellipse.cc