ShellProblem< ELEMENT > Class Template Reference
Public Member Functions
ShellProblem (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly)
Constructor.
ShellMesh< ELEMENT > * mesh_pt ()
Overload Access function for the mesh.
void actions_after_newton_solve ()
Actions after solve empty.
void actions_before_newton_solve ()
Actions before solve empty.
void solve ()
ShellProblem (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly)
Constructor.
~ShellProblem ()
Destructor: delete mesh, geometric object.
ShellMesh< ELEMENT > * mesh_pt ()
Overload Access function for the mesh.
void actions_after_newton_solve ()
Actions after solve empty.
void actions_before_newton_solve ()
Actions before solve empty.
void solve ()
Private Attributes
GeomObject * Undeformed_midplane_pt
Pointer to GeomObject that specifies the undeformed midplane.
Node * Trace_node_pt
First trace node.
Node * Trace_node2_pt
Second trace node.
Detailed Description
template<class ELEMENT>
class ShellProblem< ELEMENT >
Definition at line 214 of file clamped_shell.cc.
Constructor & Destructor Documentation
ShellProblem() [1/2]
template<class ELEMENT >
ShellProblem< ELEMENT >::ShellProblem (const unsigned & nx, const unsigned & ny, const double & lx, const double & ly)
Constructor.
Definition at line 255 of file clamped_shell.cc.
References Global_Physical_Variables::Pext_data_pt, Global_Physical_Variables::Prescribed_y, and Global_Physical_Variables::press_load().
ShellProblem() [2/2]
template<class ELEMENT >
ShellProblem< ELEMENT >::ShellProblem (const unsigned & nx, const unsigned & ny, const double & lx, const double & ly)
Constructor.
 ShellProblem()
template<class ELEMENT >
ShellProblem< ELEMENT >::~ShellProblem () [inline]
Destructor: delete mesh, geometric object.
Definition at line 325 of file clamped_shell_with_arclength_cont.cc.
References ShellProblem< ELEMENT >::Undeformed_midplane_pt.
Member Function Documentation
actions_after_newton_solve() [1/2]
template<class ELEMENT >
void ShellProblem< ELEMENT >::actions_after_newton_solve () [inline]
Actions after solve empty.
Definition at line 228 of file clamped_shell.cc.
actions_after_newton_solve() [2/2]
template<class ELEMENT >
void ShellProblem< ELEMENT >::actions_after_newton_solve () [inline]
Actions after solve empty.
Definition at line 337 of file clamped_shell_with_arclength_cont.cc.
actions_before_newton_solve() [1/2]
template<class ELEMENT >
void ShellProblem< ELEMENT >::actions_before_newton_solve () [inline]
Actions before solve empty.
Definition at line 231 of file clamped_shell.cc.
actions_before_newton_solve() [2/2]
template<class ELEMENT >
void ShellProblem< ELEMENT >::actions_before_newton_solve () [inline]
Actions before solve empty.
Definition at line 340 of file clamped_shell_with_arclength_cont.cc.
mesh_pt() [1/2]
template<class ELEMENT >
ShellMesh< ELEMENT > * ShellProblem< ELEMENT >::mesh_pt () [inline]
Overload Access function for the mesh.
Definition at line 224 of file clamped_shell.cc.
mesh_pt() [2/2]
template<class ELEMENT >
ShellMesh< ELEMENT > * ShellProblem< ELEMENT >::mesh_pt () [inline]
Overload Access function for the mesh.
Definition at line 333 of file clamped_shell_with_arclength_cont.cc.
solve() [1/2]
template<class ELEMENT >
void ShellProblem< ELEMENT >::solve
Definition at line 485 of file clamped_shell.cc.
References Global_Physical_Variables::external_pressure(), Global_Physical_Variables::Pcos, and Global_Physical_Variables::Prescribed_y.
Referenced by main().
solve() [2/2]
template<class ELEMENT >
void ShellProblem< ELEMENT >::solve ()
Member Data Documentation
Trace_node2_pt
template<class ELEMENT >
Node * ShellProblem< ELEMENT >::Trace_node2_pt [private]
Second trace node.
Definition at line 245 of file clamped_shell.cc.
Trace_node_pt
template<class ELEMENT >
Node * ShellProblem< ELEMENT >::Trace_node_pt [private]
First trace node.
Definition at line 242 of file clamped_shell.cc.
Undeformed_midplane_pt
template<class ELEMENT >
GeomObject * ShellProblem< ELEMENT >::Undeformed_midplane_pt [private]
Pointer to GeomObject that specifies the undeformed midplane.
Definition at line 239 of file clamped_shell.cc.
Referenced by ShellProblem< ELEMENT >::~ShellProblem().
The documentation for this class was generated from the following files:
clamped_shell.cc
clamped_shell_with_arclength_cont.cc