#!MC 1100


$!VARSET |STEP|=4
 
$!READDATASET  '"RESLT1/soln|STEP|.dat" ' 
  READDATAOPTION = NEW
  RESETSTYLE = YES
  INCLUDETEXT = NO
  INCLUDEGEOM = NO
  INCLUDECUSTOMLABELS = NO
  VARLOADMODE = BYNAME
  ASSIGNSTRANDIDS = YES
  INITIALPLOTTYPE = CARTESIAN3D
  VARNAMELIST = '"V1" "V2" "V3" "V4"' 
$!VARSET |NELEMENTS|=|NUMZONES|

$!FIELDMAP [1-|NELEMENTS|]  MESH{SHOW = NO}
$!FIELDMAP [1-|NELEMENTS|]  EDGELAYER{COLOR = RED}
$!FIELDMAP [1-|NELEMENTS|]  EDGELAYER{LINETHICKNESS = 0.1}
$!REDRAW 
$!READDATASET  '"RESLT1/no_true_edge|STEP|.dat" ' 
  READDATAOPTION = APPEND
  RESETSTYLE = NO
  INCLUDETEXT = NO
  INCLUDEGEOM = NO
  INCLUDECUSTOMLABELS = NO
  VARLOADMODE = BYPOSITION
  ASSIGNSTRANDIDS = YES
  INITIALPLOTTYPE = CARTESIAN3D

$!VARSET |FIRST_EDGE|=(|NELEMENTS|+1)
$!VARSET |LAST_EDGE|=|NUMZONES|

$!FIELDMAP [|FIRST_EDGE|-|LAST_EDGE|]  GROUP = 2
$!ACTIVEFIELDMAPS += [|FIRST_EDGE|-|LAST_EDGE|]
$!FIELDMAP [|FIRST_EDGE|-|LAST_EDGE|]  MESH{COLOR = GREEN}
$!FIELDMAP [|FIRST_EDGE|-|LAST_EDGE|]  MESH{LINETHICKNESS = 0.4}
$!VIEW FIT

$!THREEDVIEW 
  PSIANGLE = 45.6387
  THETAANGLE = -122.202
  ALPHAANGLE = 112.879
  VIEWERPOSITION
    {
    X = 7.88804711017
    Y = 5.15283456724
    Z = 9.03858667898
    }
$!VIEW PUSH
$!VIEW FIT

$!BLANKING VALUE{INCLUDE = YES}
$!BLANKING VALUE{CONSTRAINT 1 {INCLUDE = YES}}
$!BLANKING VALUE{CONSTRAINT 1 {VALUECUTOFF = 0.001}}
$!REDRAWALL 
$!BLANKING VALUE{VALUEBLANKCELLMODE = PRIMARYVALUE}
$!REDRAWALL 
$!BLANKING VALUE{VALUEBLANKCELLMODE = ANYCORNER}
$!REDRAWALL 
$!BLANKING VALUE{VALUEBLANKCELLMODE = ALLCORNERS}
$!REDRAWALL 
$!BLANKING VALUE{CONSTRAINT 2 {INCLUDE = YES}}
$!BLANKING VALUE{CONSTRAINT 2 {RELOP = GREATERTHANOREQUAL}}
$!BLANKING VALUE{CONSTRAINT 2 {VALUECUTOFF = 0.999}}
$!REDRAWALL 
$!BLANKING VALUE{CONSTRAINT 3 {INCLUDE = YES}}
$!BLANKING VALUE{CONSTRAINT 3 {VARA = 2}}
$!BLANKING VALUE{CONSTRAINT 3 {VALUECUTOFF = 0.001}}
$!BLANKING VALUE{CONSTRAINT 4 {INCLUDE = YES}}
$!BLANKING VALUE{CONSTRAINT 4 {VARA = 2}}
$!BLANKING VALUE{CONSTRAINT 4 {RELOP = GREATERTHANOREQUAL}}
$!BLANKING VALUE{CONSTRAINT 4 {VALUECUTOFF = 0.999}}
$!BLANKING VALUE{CONSTRAINT 5 {INCLUDE = YES}}
$!BLANKING VALUE{CONSTRAINT 5 {VARA = 3}}
$!BLANKING VALUE{CONSTRAINT 5 {VALUECUTOFF = 0.001}}
$!BLANKING VALUE{CONSTRAINT 6 {INCLUDE = YES}}
$!BLANKING VALUE{CONSTRAINT 6 {VARA = 3}}
$!BLANKING VALUE{CONSTRAINT 6 {RELOP = GREATERTHANOREQUAL}}
$!BLANKING VALUE{CONSTRAINT 6 {VALUECUTOFF = 0.99}}
$!BLANKING VALUE{CONSTRAINT 6 {VALUECUTOFF = 0.999}}
