two_d_poisson_flux_bc.txt File Reference
Typedefs
using i = 1}^2 \frac{\partial^2u}{\partial x_i^2}=f(x_1, x_2), \ \ \ \ \ \ \ \ \ \ @E[2DPoisson]@ \f] in the rectangular domain \f$ D=\left\{(x_1, x_2) \in[0, 1] \times[0, 2]\right\} \f$. The domain boundary \f$ \partial D=\partial D_{Neumann} \cup \partial D_{Dirichlet} \f$, where \f$ \partial D_{Neumann}=\left\{(x_1, x_2)|x_1=1, \ x_2\in[0, 2] \right\} \f$. On \f$ \partial D_{Dirichlet} \f$ we apply the Dirichlet boundary conditions \f[\left. u\right|_{\partial D_{Dirichlet}}=u_0, \ \ \ \ \ \ \ \ \ \ @E[2DPoisson_BC]@ \f] where the function \f$ u_0 \f$ is given. On \f$ \partial D_{Neumann} \f$ we apply the Neumann conditions \f[\left. \frac{\partial u}{\partial n}\right|_{\partial D_{Neumann}}=\left. \frac{\partial u}{\partial x_1}\right|_{\partial D_{Neumann}}=g_0, \ \ \ \ \ \ \ \ \ \ @E[2DPoisson_fluxBC]@ \f] where the function \f$ g_0 \f$ is given.</TD ></TR ></TABLE ></CENTER > We provide a detailed discussion of the driver code< A HREF=`../../../../demo_drivers/poisson/two_d_poisson_flux_bc/two_d_poisson_flux_bc.cc`> two_d_poisson_flux_bc.cc</A > which solves the problem for \f[u_0(x_1, x_2)=\tanh(1-\alpha(x_1 \tan\Phi - x_2)), \ \ \ \ \ \ \ \ \ @E[ExactSoln]@ \f] \f[f(x_1, x_2)=\sum_{i=1}^2 \frac{\partial^2 u_0}{\partial x_i^2}, \ \ \ \ \ \ \ \ \ @E[SourceFct]@ \f] and \f[g_0=\left. \frac{\partial u_0}{\partial n} \right|_{x_1=1}=\left. \frac{\partial u_0}{\partial x_1} \right|_{x_1=1}, \ \ \ \ \ \ \ \ \ @E[FluxFct]@ \f] so that \f$ u_0(x_1, x_2) \f$ is the exact solution of the problem. For large values of \f$ \alpha \f$ the solution approaches a step function \f[u_{step}(x_1, x_2)=\left\{ \begin{array}{rl} -1 &\mbox {for $x_2< x_1 \ \tan\Phi$} \\ 1 &\mbox {for $x_2 > x_1 \ \tan\Phi$} \end{array} \right. \f] and presents a serious challenge for any numerical method. The figure below compares the numerical and exact solutions for \f$ \alpha=1 \f$ and \f$ \Phi=45^o \f$. @I w 0.75\textwidth soln `Plot of the solution ` Most of the driver code is identical to the code that solves the< A HREF=`../../../poisson/two_d_poisson/html/index.html`> equivalent problem without Neumann boundary conditions</A >. Therefore we only provide a detailed discussion of those functions that needed to be changed to accommodate the Neumann boundary conditions.< HR >< HR > \section global Global parameters and functions As in the Dirichlet problem, we define the source function(@R[SourceFct]@) and the exact solution(@R[ExactSoln]@), together with the problem parameters \f$ \tan \Phi \f$ and \f$ \alpha \f$, in a namespace \c TanhSolnForPoisson. We add the function \c TanhSolnForPoisson::prescribed_flux_on_fixed_x_boundary(...) which computes the prescribed flux \f$ g_0 \f$ required in the Neumann boundary condition(@R[2DPoisson_fluxBC]@). The function evaluates \f$ \partial u_0/\partial n={\bf N} \cdot \nabla u_0 \f$ for the normal direction specified by the vector \f$ {\bf N}=(1, 0)^T. \f$ \dontinclude two_d_poisson_flux_bc.cc \skipline start_of_namespace \until end of namespace< HR >< HR > \section main The driver code The driver code is very similar to that for the< A HREF=`../../../poisson/two_d_poisson/html/index.html`>pure Dirichlet problem:</A > We set up the problem, check its integrity and define the problem parameters. Following this, we solve the problem for a number of \f$ \alpha \f$ values and document the solution. \dontinclude two_d_poisson_flux_bc.cc \skipline start_of_main \until end of main< HR >< HR > \section problem The problem class The problem class is virtually identical to that used for the< A HREF=`../../../poisson/two_d_poisson/html/index.html`>pure Dirichlet problem</A >:The only difference is that the class now contains an additional private data member, \c FluxPoissonProblem::Npoisson_elements, which stores the number of 2D `bulk` elements in the mesh, and an additional private member function \c FluxPoissonProblem::create_flux_elements(...). pwd \dontinclude two_d_poisson_flux_bc.cc \skipline start_of_problem_class \until end of problem class[See the discussion of the< A HREF=`../../../poisson/one_d_poisson/html/index.html`> 1D Poisson problem</A > for a more detailed discussion of the function type PoissonEquations< 2 >::PoissonSourceFctPt.]< HR >< HR > \section constructor The Problem constructor The first part of the \c Problem constructor is identical to that used for the< A HREF=`../../../poisson/two_d_poisson/html/index.html`>pure Dirichlet problem</A >:We create a 2D Mesh consisting of 4x4 quadrilateral Poisson elements:\skipline start_of_constructor \until mesh_pt Before continuing, we store the number of 2D `bulk` Poisson elements in the variable \c FluxPoissonProblem::Npoisson_element:\skipline Store \until Npoisson Now, we need to apply the prescribed-flux boundary condition along the Neumann boundary \f$ \partial D_{Neumann} \f$. The documentation for the \c SimpleRectangularQuadMesh shows that this boundary is mesh boundary 1. The necessary steps are performed by the function \c create_flux_elements(..), described in the section \ref create_flux below. \skipline Create prescribed \until create_flux The rest of the constructor is very similar to its counterpart in the< A HREF=`../../../poisson/two_d_poisson/html/index.html`>pure Dirichlet problem</A >. First we apply Dirichlet conditions on the remaining boundaries by pinning the nodal values. Next, we finish the problem setup by looping over all `bulk` Poisson elements and set the pointer to the source function. Since we have added the \c PoissonFluxElements to the \c Mesh, only the first \c Npoisson_element elements are `bulk` elements and the loop is restricted to these. We then perform a second loop over the \c PoissonFluxElements which need to be passed the pointer to the prescribed-flux function \c TanhSolnForPoisson::prescribed_flux_on_fixed_x_boundary(...). Finally, we generate the equation numbering scheme. \skipline Set the boundary \until end of constructor< HR >< HR > \section create_flux Creating the flux elements \c oomph-lib provides an element type \c PoissonFluxElement, which allows the application of Neumann(flux) boundary conditions along the `faces` of higher-dimensional `bulk` Poisson elements. \c PoissonFluxElements are templated by the type of the corresponding higher-dimensional `bulk` element, so that a \c PoissonFluxElement< QPoissonElement< 2, 3 > > is a one-dimensional three-node element that applies Neumann boundary conditions along the one-dimensional edge of a nine-node quadrilateral Poisson element. Similarly, a \c PoissonFluxElement< QPoissonElement< 3, 2 > > is a two-dimensional quadrilateral four-node element that applies Neumann boundary conditions along the two-dimensional face of a eight-node brick-shaped Poisson element
Functions
etc The constructor of the c PoissonFluxElement takes two and are located next to mesh boundary and along this boundary the element s coordinate f s_0 f has a constant (maximum) value of+1.0. Hence we need to set \c face_index
etc The constructor of the c PoissonFluxElement takes two and are located next to mesh boundary and along this boundary the element s coordinate f s_0 f has a the determination of the face index can be more difficult (or at least very tedious)
see the section ref exercises for a more detailed discussion of broken virtual functions Error checking would therefore have to be implemented by hand (excluding the \c PoissonFluxElements)
see the section ref exercises for a more detailed discussion of broken virtual functions Error checking would therefore have to be implemented by or a suitable error measure would have to be defined in the c PoissonFluxElements We do not pursue either approach here because the difficulty is a direct consequence of our (questionable) decision to include elements of different types in the same \c Mesh object. While this is perfectly `legal` and often convenient
sprintf (filename,`%s/error%i.dat`, doc_info.directory().c_str(), doc_info.number())
some_file open (filename)
mesh_pt () -> compute_error(some_file, TanhSolnForPoisson::get_exact_u, error, norm)
some_file close ()
Variables
mainpage Demo problem
mainpage Demo we demonstrate how to solve a Poisson problem with Neumann boundary conditions
etc The constructor of the c PoissonFluxElement takes two arguments
see the section ref exercises for a more detailed discussion of broken virtual functions Error checking would therefore have to be implemented by or a suitable error measure would have to be defined in the c PoissonFluxElements We do not pursue either approach here because the difficulty is a direct consequence of the practice introduces additional difficulties in refineable problems and we shall demonstrate< A HREF=`../../../poisson/two_d_poisson_flux_bc2/html/index.html`> an alternative approach in another example</A > skipline start_of_doc until end of doc< HR >< HR > section exercises Exercises and Comments but leave the nodes on the Neumann boundary un pinned Compare the computational result to those obtained when you set the prescribed flux to zero
see the section ref exercises for a more detailed discussion of broken virtual functions Error checking would therefore have to be implemented by or a suitable error measure would have to be defined in the c PoissonFluxElements We do not pursue either approach here because the difficulty is a direct consequence of the practice introduces additional difficulties in refineable problems and we shall demonstrate< A HREF=`../../../poisson/two_d_poisson_flux_bc2/html/index.html`> an alternative approach in another example</A > skipline start_of_doc until end of doc< HR >< HR > section exercises Exercises and Comments but leave the nodes on the Neumann boundary un pinned Compare the computational result to those obtained when you set the prescribed flux to f g_0
see the section ref exercises for a more detailed discussion of broken virtual functions Error checking would therefore have to be implemented by or a suitable error measure would have to be defined in the c PoissonFluxElements We do not pursue either approach here because the difficulty is a direct consequence of the practice introduces additional difficulties in refineable problems and we shall demonstrate< A HREF=`../../../poisson/two_d_poisson_flux_bc2/html/index.html`> an alternative approach in another example</A > skipline start_of_doc until end of doc< HR >< HR > section exercises Exercises and Comments but leave the nodes on the Neumann boundary un pinned Compare the computational result to those obtained when you set the prescribed flux to f norm
endcode in c doc_solution(...). What happens when you run the code? The code 's behaviour illustrates a general convention in \c oomph-lib if the function is not overloaded
endcode in c doc_solution(...). What happens when you run the code? The code 's behaviour illustrates a general convention in \c oomph-lib if the function is not the virtual broken function throws an error
endcode in c doc_solution(...). What happens when you run the code? The code 's behaviour illustrates a general convention in \c oomph-lib if the function is not the virtual broken function throws an allowing a traceback in a debugger to find out where the broken function was called from We note that this practice is not universally approved of in the C community but we believe it to have its place in situations such as the one described here n n Incidentally
Typedef Documentation
i
using i = 1}^2 \frac{\partial^2u}{\partial x_i^2} = f(x_1,x_2), \ \ \ \ \ \ \ \ \ \ @E[2DPoisson]@ \f] in the rectangular domain \f$ D = \left\{ (x_1,x_2) \in [0,1] \times [0,2]\right\} \f$. The domain boundary \f$ \partial D = \partial D_{Neumann} \cup \partial D_{Dirichlet} \f$, where \f$ \partial D_{Neumann} = \left\{ (x_1,x_2) | x_1=1, \ x_2\in [0,2] \right\} \f$. On \f$ \partial D_{Dirichlet} \f$ we apply the Dirichlet boundary conditions \f[ \left. u\right|_{\partial D_{Dirichlet}}=u_0, \ \ \ \ \ \ \ \ \ \ @E[2DPoisson_BC]@ \f] where the function \f$ u_0 \f$ is given. On \f$ \partial D_{Neumann} \f$ we apply the Neumann conditions \f[ \left. \frac{\partial u}{\partial n}\right|_{\partial D_{Neumann}} = \left. \frac{\partial u}{\partial x_1}\right|_{\partial D_{Neumann}} =g_0, \ \ \ \ \ \ \ \ \ \ @E[2DPoisson_fluxBC]@ \f] where the function \f$ g_0 \f$ is given. </TD> </TR> </TABLE> </CENTER> We provide a detailed discussion of the driver code <A HREF=`../../../../demo_drivers/poisson/two_d_poisson_flux_bc/two_d_poisson_flux_bc.cc`> two_d_poisson_flux_bc.cc</A> which solves the problem for \f[ u_0(x_1,x_2) = \tanh(1-\alpha(x_1 \tan\Phi - x_2)), \ \ \ \ \ \ \ \ \ @E[ExactSoln]@ \f] \f[ f(x_1,x_2) = \sum_{i=1}^2 \frac{\partial^2 u_0}{\partial x_i^2}, \ \ \ \ \ \ \ \ \ @E[SourceFct]@ \f] and \f[ g_0 = \left. \frac{\partial u_0}{\partial n} \right|_{x_1=1} = \left. \frac{\partial u_0}{\partial x_1} \right|_{x_1=1}, \ \ \ \ \ \ \ \ \ @E[FluxFct]@ \f] so that \f$ u_0(x_1,x_2) \f$ is the exact solution of the problem. For large values of \f$ \alpha \f$ the solution approaches a step function \f[ u_{step}(x_1,x_2) = \left\{ \begin{array}{rl} -1 & \mbox {for $x_2 < x_1 \ \tan\Phi$} \\ 1 & \mbox {for $x_2 > x_1 \ \tan\Phi$} \end{array} \right. \f] and presents a serious challenge for any numerical method. The figure below compares the numerical and exact solutions for \f$ \alpha = 1 \f$ and \f$ \Phi = 45^o \f$. @I w 0.75\textwidth soln `Plot of the solution ` Most of the driver code is identical to the code that solves the <A HREF=`../../../poisson/two_d_poisson/html/index.html`> equivalent problem without Neumann boundary conditions</A>. Therefore we only provide a detailed discussion of those functions that needed to be changed to accommodate the Neumann boundary conditions. <HR> <HR> \section global Global parameters and functions As in the Dirichlet problem, we define the source function (@R[SourceFct]@) and the exact solution (@R[ExactSoln]@), together with the problem parameters \f$ \tan \Phi \f$ and \f$ \alpha \f$, in a namespace \c TanhSolnForPoisson. We add the function \c TanhSolnForPoisson::prescribed_flux_on_fixed_x_boundary(...) which computes the prescribed flux \f$ g_0 \f$ required in the Neumann boundary condition (@R[2DPoisson_fluxBC]@). The function evaluates \f$ \partial u_0 /\partial n = {\bf N} \cdot \nabla u_0 \f$ for the normal direction specified by the vector \f$ {\bf N} = (1,0)^T. \f$ \dontinclude two_d_poisson_flux_bc.cc \skipline start_of_namespace \until end of namespace <HR> <HR> \section main The driver code The driver code is very similar to that for the <A HREF=`../../../poisson/two_d_poisson/html/index.html`>pure Dirichlet problem:</A> We set up the problem, check its integrity and define the problem parameters. Following this, we solve the problem for a number of \f$ \alpha \f$ values and document the solution. \dontinclude two_d_poisson_flux_bc.cc \skipline start_of_main \until end of main <HR> <HR> \section problem The problem class The problem class is virtually identical to that used for the <A HREF=`../../../poisson/two_d_poisson/html/index.html`>pure Dirichlet problem</A>: The only difference is that the class now contains an additional private data member, \c FluxPoissonProblem::Npoisson_elements, which stores the number of 2D `bulk` elements in the mesh, and an additional private member function \c FluxPoissonProblem::create_flux_elements(...). pwd \dontinclude two_d_poisson_flux_bc.cc \skipline start_of_problem_class \until end of problem class [See the discussion of the <A HREF=`../../../poisson/one_d_poisson/html/index.html`> 1D Poisson problem</A> for a more detailed discussion of the function type PoissonEquations<2>::PoissonSourceFctPt.] <HR> <HR> \section constructor The Problem constructor The first part of the \c Problem constructor is identical to that used for the <A HREF=`../../../poisson/two_d_poisson/html/index.html`>pure Dirichlet problem</A>: We create a 2D Mesh consisting of 4x4 quadrilateral Poisson elements: \skipline start_of_constructor \until mesh_pt Before continuing, we store the number of 2D `bulk` Poisson elements in the variable \c FluxPoissonProblem::Npoisson_element: \skipline Store \until Npoisson Now, we need to apply the prescribed-flux boundary condition along the Neumann boundary \f$ \partial D_{Neumann} \f$. The documentation for the \c SimpleRectangularQuadMesh shows that this boundary is mesh boundary 1. The necessary steps are performed by the function \c create_flux_elements(..), described in the section \ref create_flux below. \skipline Create prescribed \until create_flux The rest of the constructor is very similar to its counterpart in the <A HREF=`../../../poisson/two_d_poisson/html/index.html`>pure Dirichlet problem</A>. First we apply Dirichlet conditions on the remaining boundaries by pinning the nodal values. Next, we finish the problem setup by looping over all `bulk` Poisson elements and set the pointer to the source function. Since we have added the \c PoissonFluxElements to the \c Mesh, only the first \c Npoisson_element elements are `bulk` elements and the loop is restricted to these. We then perform a second loop over the \c PoissonFluxElements which need to be passed the pointer to the prescribed-flux function \c TanhSolnForPoisson::prescribed_flux_on_fixed_x_boundary(...). Finally, we generate the equation numbering scheme. \skipline Set the boundary \until end of constructor <HR> <HR> \section create_flux Creating the flux elements \c oomph-lib provides an element type \c PoissonFluxElement, which allows the application of Neumann (flux) boundary conditions along the `faces` of higher-dimensional `bulk` Poisson elements. \c PoissonFluxElements are templated by the type of the corresponding higher-dimensional `bulk` element, so that a \c PoissonFluxElement<QPoissonElement<2,3> > is a one-dimensional three-node element that applies Neumann boundary conditions along the one-dimensional edge of a nine-node quadrilateral Poisson element. Similarly, a \c PoissonFluxElement<QPoissonElement<3,2> > is a two-dimensional quadrilateral four-node element that applies Neumann boundary conditions along the two-dimensional face of a eight-node brick-shaped Poisson element
Definition at line 210 of file two_d_poisson_flux_bc.txt.
Function Documentation
close()
some_file close ()
constant()
etc The constructor of the c PoissonFluxElement takes two and are located next to mesh boundary and along this boundary the element s coordinate f s_0 f has a constant (maximum)
difficult()
etc The constructor of the c PoissonFluxElement takes two and are located next to mesh boundary and along this boundary the element s coordinate f s_0 f has a the determination of the face index can be more difficult (or at least very tedious)
hand()
see the section ref exercises for a more detailed discussion of broken virtual functions Error checking would therefore have to be implemented by hand (excluding the \c PoissonFluxElements)
mesh_pt()
mesh_pt () -> compute_error(some_file, TanhSolnForPoisson::get_exact_u, error, norm)
Referenced by FluxPoissonProblem< ELEMENT >::actions_before_newton_solve(), FluxPoissonProblem< ELEMENT >::create_flux_elements(), FluxPoissonProblem< ELEMENT >::doc_solution(), and FluxPoissonProblem< ELEMENT >::FluxPoissonProblem().
open()
some_file open (filename)
our()
see the section ref exercises for a more detailed discussion of broken virtual functions Error checking would therefore have to be implemented by or a suitable error measure would have to be defined in the c PoissonFluxElements We do not pursue either approach here because the difficulty is a direct consequence of our (questionable)
sprintf()
sprintf (filename , `%s/error%i.dat` , doc_info. directory).c_str(, doc_info. number())
Referenced by FluxPoissonProblem< ELEMENT >::doc_solution().
Variable Documentation
arguments
etc The constructor of the c PoissonFluxElement takes two arguments
Definition at line 222 of file two_d_poisson_flux_bc.txt.
conditions
mainpage Demo we demonstrate how to solve a Poisson problem with Neumann boundary conditions
Definition at line 4 of file two_d_poisson_flux_bc.txt.
error
endcode in c doc_solution (...). What happens when you run the code? The code's behaviour illustrates a general convention in \c oomph-lib if the function is not the virtual broken function throws an error
Definition at line 338 of file two_d_poisson_flux_bc.txt.
g_0
see the section ref exercises for a more detailed discussion of broken virtual functions Error checking would therefore have to be implemented by or a suitable error measure would have to be defined in the c PoissonFluxElements We do not pursue either approach here because the difficulty is a direct consequence of the practice introduces additional difficulties in refineable problems and we shall demonstrate<A HREF=`../../../poisson/two_d_poisson_flux_bc2/html/index.html`> an alternative approach in another example</A> skipline start_of_doc until end of doc<HR><HR> section exercises Exercises and Comments but leave the nodes on the Neumann boundary un pinned Compare the computational result to those obtained when you set the prescribed flux to f g_0
Initial value:
= 0 \f$. Does this make sense?
   [Hint: Remember the "natural" boundary conditions for
   Poisson's equation].
-# Try to compute the error of the computed solution by
   re-instating the global error checking procedure
   \code
   
   
   double error
Definition at line 298 of file two_d_poisson_flux_bc.txt.
Incidentally
endcode in c doc_solution (...). What happens when you run the code? The code's behaviour illustrates a general convention in \c oomph-lib if the function is not the virtual broken function throws an allowing a traceback in a debugger to find out where the broken function was called from We note that this practice is not universally approved of in the C community but we believe it to have its place in situations such as the one described here n n Incidentally
Definition at line 344 of file two_d_poisson_flux_bc.txt.
norm
see the section ref exercises for a more detailed discussion of broken virtual functions Error checking would therefore have to be implemented by or a suitable error measure would have to be defined in the c PoissonFluxElements We do not pursue either approach here because the difficulty is a direct consequence of the practice introduces additional difficulties in refineable problems and we shall demonstrate<A HREF=`../../../poisson/two_d_poisson_flux_bc2/html/index.html`> an alternative approach in another example</A> skipline start_of_doc until end of doc<HR><HR> section exercises Exercises and Comments but leave the nodes on the Neumann boundary un pinned Compare the computational result to those obtained when you set the prescribed flux to f norm
Definition at line 306 of file two_d_poisson_flux_bc.txt.
overloaded
endcode in c doc_solution (...). What happens when you run the code? The code's behaviour illustrates a general convention in \c oomph-lib if the function is not overloaded
Definition at line 314 of file two_d_poisson_flux_bc.txt.
problem
mainpage Demo problem
Definition at line 3 of file two_d_poisson_flux_bc.txt.
Referenced by main().
zero
see the section ref exercises for a more detailed discussion of broken virtual functions Error checking would therefore have to be implemented by or a suitable error measure would have to be defined in the c PoissonFluxElements We do not pursue either approach here because the difficulty is a direct consequence of the practice introduces additional difficulties in refineable problems and we shall demonstrate<A HREF=`../../../poisson/two_d_poisson_flux_bc2/html/index.html`> an alternative approach in another example</A> skipline start_of_doc until end of doc<HR><HR> section exercises Exercises and Comments but leave the nodes on the Neumann boundary un pinned Compare the computational result to those obtained when you set the prescribed flux to zero
Definition at line 298 of file two_d_poisson_flux_bc.txt.