RayleighProblem< ELEMENT, TIMESTEPPER > Class Template Reference
Rayleigh-type problem: 2D channel whose upper wall oscillates periodically.
Public Member Functions
RayleighProblem (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly)
Constructor: Pass number of elements in x and y directions and lengths.
void actions_before_newton_solve ()
void actions_after_newton_solve ()
Update after solve is empty.
void actions_before_implicit_timestep ()
void unsteady_run (DocInfo &doc_info)
Run an unsteady simulation.
void doc_solution (DocInfo &doc_info)
Doc the solution.
void set_initial_condition ()
Set initial condition (incl previous timesteps) according to specified function.
Private Member Functions
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
Private Attributes
ofstream Trace_file
Trace file.
Detailed Description
template<class ELEMENT, class TIMESTEPPER>
class RayleighProblem< ELEMENT, TIMESTEPPER >
Rayleigh-type problem: 2D channel whose upper wall oscillates periodically.
Definition at line 120 of file rayleigh_channel.cc.
Constructor & Destructor Documentation
RayleighProblem()
template<class ELEMENT , class TIMESTEPPER >
RayleighProblem< ELEMENT, TIMESTEPPER >::RayleighProblem (const unsigned & nx, const unsigned & ny, const double & lx, const double & ly)
Constructor: Pass number of elements in x and y directions and lengths.
Problem constructor.
Definition at line 187 of file rayleigh_channel.cc.
References Global_Parameters::Re, and Global_Parameters::ReSt.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT , class TIMESTEPPER >
void RayleighProblem< ELEMENT, TIMESTEPPER >::actions_after_newton_solve () [inline]
Update after solve is empty.
Definition at line 133 of file rayleigh_channel.cc.
actions_before_implicit_timestep()
template<class ELEMENT , class TIMESTEPPER >
void RayleighProblem< ELEMENT, TIMESTEPPER >::actions_before_implicit_timestep () [inline]
Definition at line 136 of file rayleigh_channel.cc.
References ExactSoln::get_exact_u().
actions_before_newton_solve()
template<class ELEMENT , class TIMESTEPPER >
void RayleighProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_solve () [inline]
Definition at line 130 of file rayleigh_channel.cc.
doc_solution()
template<class ELEMENT , class TIMESTEPPER >
void RayleighProblem< ELEMENT, TIMESTEPPER >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 332 of file rayleigh_channel.cc.
References ExactSoln::get_exact_u().
fix_pressure()
template<class ELEMENT , class TIMESTEPPER >
void RayleighProblem< ELEMENT, TIMESTEPPER >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) [inline], [private]
Fix pressure in element e at pressure dof pdof and set to pvalue.
Definition at line 169 of file rayleigh_channel.cc.
References RayleighProblem< ELEMENT, TIMESTEPPER >::fix_pressure().
Referenced by RayleighProblem< ELEMENT, TIMESTEPPER >::fix_pressure().
set_initial_condition()
template<class ELEMENT , class TIMESTEPPER >
void RayleighProblem< ELEMENT, TIMESTEPPER >::set_initial_condition
Set initial condition (incl previous timesteps) according to specified function.
Set initial condition: Assign previous and current values from exact solution.
Definition at line 253 of file rayleigh_channel.cc.
References ExactSoln::get_exact_u().
unsteady_run()
template<class ELEMENT , class TIMESTEPPER >
void RayleighProblem< ELEMENT, TIMESTEPPER >::unsteady_run (DocInfo & doc_info)
Run an unsteady simulation.
Unsteady run...
Definition at line 417 of file rayleigh_channel.cc.
References Global_Parameters::Impulsive_start_flag, and Global_Parameters::Long_run_flag.
Referenced by main().
Member Data Documentation
Trace_file
template<class ELEMENT , class TIMESTEPPER >
ofstream RayleighProblem< ELEMENT, TIMESTEPPER >::Trace_file [private]
Trace file.
Definition at line 178 of file rayleigh_channel.cc.
The documentation for this class was generated from the following file:
rayleigh_channel.cc