oomph::CollapsibleChannelMesh< ELEMENT > Class Template Reference
Basic collapsible channel mesh. The mesh is derived from the SimpleRectangularQuadMesh so it's node and element numbering scheme is the same as in that mesh. Only the boundaries are numbered differently to allow the easy identification of the `collapsible` segment. Boundary coordinates are set up for all nodes located on boundary 3 (the collapsible segment). The curvilinear (`collapsible`) segment is defined by a GeomObject.
#include <collapsible_channel_mesh.template.h>
Public Member Functions
CollapsibleChannelMesh (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly, GeomObject *wall_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass number of elements in upstream/collapsible/ downstream segment and across the channel; lengths of upstream/ collapsible/downstream segments and width of channel, pointer to GeomObject that defines the collapsible segment and pointer to TimeStepper (defaults to the default timestepper, Steady).
~CollapsibleChannelMesh ()
destructor
GeomObject *& wall_pt ()
Access function to GeomObject representing wall.
CollapsibleChannelDomain * domain_pt ()
Access function to domain.
virtual CollapsibleChannelDomain::BLSquashFctPt & bl_squash_fct_pt ()
Function pointer for function that squashes the mesh near the walls. Default trivial mapping (the identity) leaves vertical nodal positions unchanged. Mapping is used in underlying CollapsibleChannelDomain. Virtual so we can break it in derived classes (e.g. the Algebraic versions of this mesh where it doesn't make any sense to provide the bl_squash_fct after the mesh has been built).
CollapsibleChannelDomain::BLSquashFctPt bl_squash_fct_pt () const
Function pointer for function that squashes the mesh near the walls. Default trivial mapping (the identity) leaves vertical nodal positions unchanged. Mapping is used in underlying CollapsibleChannelDomain. Const version.
virtual CollapsibleChannelDomain::AxialSpacingFctPt & axial_spacing_fct_pt ()
Function pointer for function that redistributes the elements in the axial direction. Virtual so we can break it in derived classes (e.g. the Algebraic versions of this mesh where it doesn't make any sense to provide the bl_squash_fct after the mesh has been built).
virtual CollapsibleChannelDomain::AxialSpacingFctPt & axial_spacing_fct_pt () const
Function pointer for function that redistributes the elements in the axial direction. Const version.
Protected Attributes
CollapsibleChannelDomain * Domain_pt
Pointer to domain.
unsigned Nup
Number of element columns in upstream part.
unsigned Ncollapsible
Number of element columns in collapsible part.
unsigned Ndown
Number of element columns in downstream part.
unsigned Ny
Number of element rows across channel.
GeomObject * Wall_pt
Pointer to geometric object that represents the moving wall.
Detailed Description
template<class ELEMENT>
class oomph::CollapsibleChannelMesh< ELEMENT >
Basic collapsible channel mesh. The mesh is derived from the SimpleRectangularQuadMesh so it's node and element numbering scheme is the same as in that mesh. Only the boundaries are numbered differently to allow the easy identification of the `collapsible` segment. Boundary coordinates are set up for all nodes located on boundary 3 (the collapsible segment). The curvilinear (`collapsible`) segment is defined by a GeomObject.
Definition at line 64 of file collapsible_channel_mesh.template.h.
Constructor & Destructor Documentation
CollapsibleChannelMesh()
template<class ELEMENT >
oomph::CollapsibleChannelMesh< ELEMENT >::CollapsibleChannelMesh (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly, GeomObject * wall_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass number of elements in upstream/collapsible/ downstream segment and across the channel; lengths of upstream/ collapsible/downstream segments and width of channel, pointer to GeomObject that defines the collapsible segment and pointer to TimeStepper (defaults to the default timestepper, Steady).
Constructor: Pass number of elements in upstream/collapsible/downstream segment and across the channel; lengths of upstream/collapsible/downstream segments and width of channel, pointer to GeomObject that defines the collapsible segment and pointer to TimeStepper (defaults to the default timestepper, Steady).
Definition at line 43 of file collapsible_channel_mesh.template.cc.
References oomph::CollapsibleChannelMesh< ELEMENT >::Domain_pt, oomph::SimpleRectangularQuadMesh< ELEMENT >::ny(), and oomph::CollapsibleChannelMesh< ELEMENT >::wall_pt().
 CollapsibleChannelMesh()
template<class ELEMENT >
oomph::CollapsibleChannelMesh< ELEMENT >::~CollapsibleChannelMesh () [inline]
destructor
Definition at line 85 of file collapsible_channel_mesh.template.h.
References oomph::CollapsibleChannelMesh< ELEMENT >::Domain_pt.
Member Function Documentation
axial_spacing_fct_pt() [1/2]
template<class ELEMENT >
virtual CollapsibleChannelDomain::AxialSpacingFctPt & oomph::CollapsibleChannelMesh< ELEMENT >::axial_spacing_fct_pt () [inline], [virtual]
Function pointer for function that redistributes the elements in the axial direction. Virtual so we can break it in derived classes (e.g. the Algebraic versions of this mesh where it doesn't make any sense to provide the bl_squash_fct after the mesh has been built).
Reimplemented in oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >.
Definition at line 130 of file collapsible_channel_mesh.template.h.
References oomph::CollapsibleChannelDomain::axial_spacing_fct_pt(), and oomph::CollapsibleChannelMesh< ELEMENT >::Domain_pt.
axial_spacing_fct_pt() [2/2]
template<class ELEMENT >
virtual CollapsibleChannelDomain::AxialSpacingFctPt & oomph::CollapsibleChannelMesh< ELEMENT >::axial_spacing_fct_pt () const [inline], [virtual]
Function pointer for function that redistributes the elements in the axial direction. Const version.
Definition at line 138 of file collapsible_channel_mesh.template.h.
References oomph::CollapsibleChannelDomain::axial_spacing_fct_pt(), and oomph::CollapsibleChannelMesh< ELEMENT >::Domain_pt.
bl_squash_fct_pt() [1/2]
template<class ELEMENT >
virtual CollapsibleChannelDomain::BLSquashFctPt & oomph::CollapsibleChannelMesh< ELEMENT >::bl_squash_fct_pt () [inline], [virtual]
Function pointer for function that squashes the mesh near the walls. Default trivial mapping (the identity) leaves vertical nodal positions unchanged. Mapping is used in underlying CollapsibleChannelDomain. Virtual so we can break it in derived classes (e.g. the Algebraic versions of this mesh where it doesn't make any sense to provide the bl_squash_fct after the mesh has been built).
Reimplemented in oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >.
Definition at line 109 of file collapsible_channel_mesh.template.h.
References oomph::CollapsibleChannelDomain::bl_squash_fct_pt(), and oomph::CollapsibleChannelMesh< ELEMENT >::Domain_pt.
bl_squash_fct_pt() [2/2]
template<class ELEMENT >
CollapsibleChannelDomain::BLSquashFctPt oomph::CollapsibleChannelMesh< ELEMENT >::bl_squash_fct_pt () const [inline]
Function pointer for function that squashes the mesh near the walls. Default trivial mapping (the identity) leaves vertical nodal positions unchanged. Mapping is used in underlying CollapsibleChannelDomain. Const version.
Definition at line 119 of file collapsible_channel_mesh.template.h.
References oomph::CollapsibleChannelDomain::bl_squash_fct_pt(), and oomph::CollapsibleChannelMesh< ELEMENT >::Domain_pt.
domain_pt()
template<class ELEMENT >
CollapsibleChannelDomain * oomph::CollapsibleChannelMesh< ELEMENT >::domain_pt () [inline]
Access function to domain.
Definition at line 97 of file collapsible_channel_mesh.template.h.
References oomph::CollapsibleChannelMesh< ELEMENT >::Domain_pt.
Referenced by oomph::MacroElementNodeUpdateCollapsibleChannelMesh< ELEMENT >::MacroElementNodeUpdateCollapsibleChannelMesh().
wall_pt()
template<class ELEMENT >
GeomObject *& oomph::CollapsibleChannelMesh< ELEMENT >::wall_pt () [inline]
Access function to GeomObject representing wall.
Definition at line 91 of file collapsible_channel_mesh.template.h.
References oomph::CollapsibleChannelMesh< ELEMENT >::Wall_pt.
Referenced by oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >::AlgebraicCollapsibleChannelMesh(), and oomph::CollapsibleChannelMesh< ELEMENT >::CollapsibleChannelMesh().
Member Data Documentation
Domain_pt
template<class ELEMENT >
CollapsibleChannelDomain* oomph::CollapsibleChannelMesh< ELEMENT >::Domain_pt [protected]
Pointer to domain.
Definition at line 147 of file collapsible_channel_mesh.template.h.
Referenced by oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >::AlgebraicCollapsibleChannelMesh(), oomph::CollapsibleChannelMesh< ELEMENT >::axial_spacing_fct_pt(), oomph::CollapsibleChannelMesh< ELEMENT >::bl_squash_fct_pt(), oomph::CollapsibleChannelMesh< ELEMENT >::CollapsibleChannelMesh(), oomph::CollapsibleChannelMesh< ELEMENT >::domain_pt(), and oomph::CollapsibleChannelMesh< ELEMENT >::~CollapsibleChannelMesh().
Ncollapsible
template<class ELEMENT >
unsigned oomph::CollapsibleChannelMesh< ELEMENT >::Ncollapsible [protected]
Number of element columns in collapsible part.
Definition at line 153 of file collapsible_channel_mesh.template.h.
Ndown
template<class ELEMENT >
unsigned oomph::CollapsibleChannelMesh< ELEMENT >::Ndown [protected]
Number of element columns in downstream part.
Definition at line 156 of file collapsible_channel_mesh.template.h.
Nup
template<class ELEMENT >
unsigned oomph::CollapsibleChannelMesh< ELEMENT >::Nup [protected]
Number of element columns in upstream part.
Definition at line 150 of file collapsible_channel_mesh.template.h.
Ny
template<class ELEMENT >
unsigned oomph::CollapsibleChannelMesh< ELEMENT >::Ny [protected]
Number of element rows across channel.
Definition at line 159 of file collapsible_channel_mesh.template.h.
Wall_pt
template<class ELEMENT >
GeomObject* oomph::CollapsibleChannelMesh< ELEMENT >::Wall_pt [protected]
Pointer to geometric object that represents the moving wall.
Definition at line 162 of file collapsible_channel_mesh.template.h.
Referenced by oomph::MacroElementNodeUpdateCollapsibleChannelMesh< ELEMENT >::MacroElementNodeUpdateCollapsibleChannelMesh(), and oomph::CollapsibleChannelMesh< ELEMENT >::wall_pt().
The documentation for this class was generated from the following files:
collapsible_channel_mesh.template.h
collapsible_channel_mesh.template.cc