oomph::MacroElementNodeUpdateRefineableQuarterTubeMesh< ELEMENT > Class Template Reference
MacroElementNodeUpdate version of RefineableQuarterTubeMesh.
#include <quarter_tube_mesh.h>
Public Member Functions
MacroElementNodeUpdateRefineableQuarterTubeMesh (GeomObject *wall_pt, const Vector< double > &xi_lo, const double &fract_mid, const Vector< double > &xi_hi, const unsigned &nlayer, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass pointer to geometric object, start and end coordinates on the geometric object and the fraction along which the dividing line is to be placed when updating the nodal positions, and timestepper (defaults to (Steady) default timestepper defined in Mesh). Setup the refineable mesh (by calling the constructor for the underlying RefineableQuarterTubeMesh) and the algebraic node update functions for nodes.
virtual ~MacroElementNodeUpdateRefineableQuarterTubeMesh ()
Destructor: empty.
void node_update (const bool &update_all_solid_nodes=false)
Resolve mesh update: Update current nodal positions via sparse MacroElement-based update. [Doesn't make sense to use this mesh with SolidElements anyway, so we buffer the case if update_all_solid_nodes is set to true.].
Public Member Functions inherited from oomph::RefineableQuarterTubeMesh< ELEMENT >
RefineableQuarterTubeMesh (GeomObject *wall_pt, const Vector< double > &xi_lo, const double &fract_mid, const Vector< double > &xi_hi, const unsigned &nlayer, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor for adaptive deformable quarter tube mesh class. The domain is specified by the GeomObject that identifies boundary 3. Pass pointer to geometric object that specifies the wall, start and end coordinates on the geometric object, and the fraction along which the dividing line is to be placed, and the timestepper. Timestepper defaults to Steady dummy timestepper.
virtual ~RefineableQuarterTubeMesh ()
Destructor: empty.
Public Member Functions inherited from oomph::QuarterTubeMesh< ELEMENT >
QuarterTubeMesh (GeomObject *wall_pt, const Vector< double > &xi_lo, const double &fract_mid, const Vector< double > &xi_hi, const unsigned &nlayer, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass pointer to geometric object that specifies the wall, start and end coordinates on the geometric object, and the fraction along which the dividing line is to be placed, and the timestepper. Timestepper defaults to Steady dummy timestepper.
virtual ~QuarterTubeMesh ()
Destructor: empty.
GeomObject *& wall_pt ()
Access function to GeomObject representing wall.
QuarterTubeDomain * domain_pt ()
Access function to domain.
QuarterTubeDomain::BLSquashFctPt & bl_squash_fct_pt ()
Function pointer for function that squashes the outer macro elements towards the wall by mapping the input value of the "radial" macro element coordinate to the return value (defined in the underlying Domain object)
virtual QuarterTubeDomain::AxialSpacingFctPt & axial_spacing_fct_pt ()
Function pointer for function for axial spacing.
QuarterTubeDomain * domain_pt () const
Access function to underlying domain.
Private Member Functions
void setup_macro_element_node_update ()
Setup all the information that's required for MacroElement-based node update: Tell the elements that their geometry depends on the geometric object that parametrises the wall.
Additional Inherited Members
Protected Attributes inherited from oomph::QuarterTubeMesh< ELEMENT >
QuarterTubeDomain * Domain_pt
Pointer to domain.
GeomObject * Wall_pt
Pointer to the geometric object that represents the curved wall.
Vector< double > Xi_lo
Lower limits for the coordinates along the wall.
double Fract_mid
Fraction along wall where outer ring is to be divided.
Vector< double > Xi_hi
Upper limits for the coordinates along the wall.
Detailed Description
template<class ELEMENT>
class oomph::MacroElementNodeUpdateRefineableQuarterTubeMesh< ELEMENT >
MacroElementNodeUpdate version of RefineableQuarterTubeMesh.
Definition at line 234 of file quarter_tube_mesh.h.
Constructor & Destructor Documentation
MacroElementNodeUpdateRefineableQuarterTubeMesh()
template<class ELEMENT >
oomph::MacroElementNodeUpdateRefineableQuarterTubeMesh< ELEMENT >::MacroElementNodeUpdateRefineableQuarterTubeMesh (GeomObject * wall_pt, const Vector< double > & xi_lo, const double & fract_mid, const Vector< double > & xi_hi, const unsigned & nlayer, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass pointer to geometric object, start and end coordinates on the geometric object and the fraction along which the dividing line is to be placed when updating the nodal positions, and timestepper (defaults to (Steady) default timestepper defined in Mesh). Setup the refineable mesh (by calling the constructor for the underlying RefineableQuarterTubeMesh) and the algebraic node update functions for nodes.
Definition at line 246 of file quarter_tube_mesh.h.
References oomph::MacroElementNodeUpdateRefineableQuarterTubeMesh< ELEMENT >::setup_macro_element_node_update().
~MacroElementNodeUpdateRefineableQuarterTubeMesh()
template<class ELEMENT >
virtual oomph::MacroElementNodeUpdateRefineableQuarterTubeMesh< ELEMENT >::~MacroElementNodeUpdateRefineableQuarterTubeMesh () [inline], [virtual]
Destructor: empty.
Definition at line 289 of file quarter_tube_mesh.h.
Member Function Documentation
node_update()
template<class ELEMENT >
void oomph::MacroElementNodeUpdateRefineableQuarterTubeMesh< ELEMENT >::node_update (const bool & update_all_solid_nodes = false) [inline]
Resolve mesh update: Update current nodal positions via sparse MacroElement-based update. [Doesn't make sense to use this mesh with SolidElements anyway, so we buffer the case if update_all_solid_nodes is set to true.].
Definition at line 296 of file quarter_tube_mesh.h.
setup_macro_element_node_update()
template<class ELEMENT >
void oomph::MacroElementNodeUpdateRefineableQuarterTubeMesh< ELEMENT >::setup_macro_element_node_update () [inline], [private]
Setup all the information that's required for MacroElement-based node update: Tell the elements that their geometry depends on the geometric object that parametrises the wall.
Definition at line 322 of file quarter_tube_mesh.h.
References oomph::QuarterTubeMesh< ELEMENT >::domain_pt(), and oomph::QuarterTubeMesh< ELEMENT >::Wall_pt.
Referenced by oomph::MacroElementNodeUpdateRefineableQuarterTubeMesh< ELEMENT >::MacroElementNodeUpdateRefineableQuarterTubeMesh().
The documentation for this class was generated from the following file:
quarter_tube_mesh.h