RectangularDrivenCavityProblem< ELEMENT > Class Template Reference
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Public Member Functions
RectangularDrivenCavityProblem ()
Constructor.
~RectangularDrivenCavityProblem ()
Destructor (empty)
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void actions_after_newton_solve ()
Update the after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve. Re-set velocity boundary conditions just to be on the safe side...
SimpleRectangularQuadMesh< ELEMENT > * mesh_pt ()
void doc_solution (DocInfo &doc_info)
Doc the solution.
Detailed Description
template<class ELEMENT>
class RectangularDrivenCavityProblem< ELEMENT >
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Driven cavity problem in rectangular domain
Definition at line 63 of file driven_cavity.cc.
Constructor & Destructor Documentation
RectangularDrivenCavityProblem()
template<class ELEMENT >
RectangularDrivenCavityProblem< ELEMENT >::RectangularDrivenCavityProblem
Constructor.
Constructor for RectangularDrivenCavity problem.
Definition at line 141 of file driven_cavity.cc.
References Global_Physical_Variables::Re.
 RectangularDrivenCavityProblem()
template<class ELEMENT >
RectangularDrivenCavityProblem< ELEMENT >::~RectangularDrivenCavityProblem () [inline]
Destructor (empty)
Definition at line 73 of file driven_cavity.cc.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT >
void RectangularDrivenCavityProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the after solve (empty)
Definition at line 86 of file driven_cavity.cc.
actions_before_newton_solve()
template<class ELEMENT >
void RectangularDrivenCavityProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve. Re-set velocity boundary conditions just to be on the safe side...
Definition at line 91 of file driven_cavity.cc.
References RectangularDrivenCavityProblem< ELEMENT >::mesh_pt().
doc_solution()
template<class ELEMENT >
void RectangularDrivenCavityProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 207 of file driven_cavity.cc.
Referenced by main().
fix_pressure()
template<class ELEMENT >
void RectangularDrivenCavityProblem< ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) [inline]
Fix pressure in element e at pressure dof pdof and set to pvalue.
Definition at line 76 of file driven_cavity.cc.
References RectangularDrivenCavityProblem< ELEMENT >::fix_pressure(), and RectangularDrivenCavityProblem< ELEMENT >::mesh_pt().
Referenced by RectangularDrivenCavityProblem< ELEMENT >::fix_pressure().
mesh_pt()
template<class ELEMENT >
SimpleRectangularQuadMesh< ELEMENT > * RectangularDrivenCavityProblem< ELEMENT >::mesh_pt () [inline]
Definition at line 122 of file driven_cavity.cc.
Referenced by RectangularDrivenCavityProblem< ELEMENT >::actions_before_newton_solve(), and RectangularDrivenCavityProblem< ELEMENT >::fix_pressure().
The documentation for this class was generated from the following file:
driven_cavity.cc