fish_poisson.txt File Reference
Typedefs
using i = 1}^2 \frac{\partial^2u}{\partial x_i^2}=-1, \ \ \ \ \ \ \ \ \ \ @E[2DPoisson]@ \f] in the fish-shaped domain \f $D_{fish} \f$, with homogeneous Dirichlet boundary conditions \f[\left. u\right|_{\partial D_{fish}}=0. \ \ \ \ \ \ \ \ \ \ @E[2DPoisson_BC]@ \f]</TD ></TR ></TABLE ></CENTER > @I w 0.75\textwidth fish_poisson_soln `Plot of the solution ` The sharp corners in the domain create singularities in the solution(its derivatives are unbounded) and so accurate results can only be obtained if we use a sufficiently fine discretisation. Implementing this by uniform mesh refinement would create a huge number of elements in the interior of the domain where the fine discretisation is not required. To avoid this problem, \c oomph-lib provides mesh adaptation routines that automatically adapt the mesh, based on \e a \e posteriori error estimates. Regions in which an error estimator indicates that the solution is not resolved to the required accuracy are refined
Functions
namespace c ConstSourceForPoisson only contains the constant source function f f (x)
namespace c ConstSourceForPoisson only contains the constant source function f coarse mesh is performed automatically until the solution satisfies the required error bounds (or until the maximum permitted number of adaptation steps has been reached). - In the second approach we start by performing a number of uniform mesh refinement steps
the c RefineableQPoissonElement< 2, 3 > is a nine node (bi-quadratic) quad element. \dontinclude fish_poisson.cc \skipline start_black_box \until RefineableFish After creating the \c DocInfo object
the c RefineableQPoissonElement< 2, 3 > is a nine we document the(default) adaptivity targets see ref comments The fully adaptive solution of the problem is very simple We simply pass the maximum number of adaptations to the Newton solver and document the results Done dontinclude fish_poisson cc skipline with fully automatic adaptation until end black box< HR > subsection incremental Incremental adaptation To allow the user more control over the mesh adaptation c oomph lib provides a number of functions that perform individual adaptation steps without re computing the solution immediately This allows the user to perform uniform mesh refinement and impose a specific refinement monitor document the progress of the automatic adaptation The second driver function illustrates some of these functions We start by setting up the create the c DocInfo object and document the adaptivity exactly as we solve the problem on the very coarse mesh and document the very coarse until doc_info number ()++
and in time dependent problems where the solution at one timestep provides initial conditions for the next one See the discussion of< A HREF=`../../../unsteady_heat/two_d_unsteady_heat_adapt/html/index.html`> the adaptive solution of the unsteady heat equation</A > for more details the source function pointers are automatically passed to an element s four son elements when the element is subdivided This allows the adaptation to proceed completely without any intervention by the user On return from c certain actions may need to be performed before or after the mesh adaptation (e.g. if flux boundary conditions are applied by \c FaceElements;this is explained in< A HREF=`../../../poisson/two_d_poisson_flux_bc_adapt/html/index.html`> another example</A >). To ensure that these steps are performed when the adaptation is controlled by the `black-box` adaptive Newton solver
endcode before code problem mesh_pt () -> doc_adaptivity_targets(cout)
Variables
mainpage Demo problem
namespace c ConstSourceForPoisson only contains the constant source function f coarse mesh is performed automatically until the solution satisfies the required error and then use incremental adaptations
namespace c ConstSourceForPoisson only contains the constant source function f coarse mesh is performed automatically until the solution satisfies the required error and then use incremental allowing us to document how the refinement proceeds dontinclude fish_poisson cc skipline start_of_main until end of main< HR > subsection black_box Black box adaptation We start by creating the Problem object
the c RefineableQPoissonElement< 2, 3 > is a nine we document the(default) adaptivity targets see ref comments The fully adaptive solution of the problem is very simple We simply pass the maximum number of adaptations to the Newton solver and document the results Done dontinclude fish_poisson cc skipline with fully automatic adaptation until end black box< HR > subsection incremental Incremental adaptation To allow the user more control over the mesh adaptation process
the c RefineableQPoissonElement< 2, 3 > is a nine we document the(default) adaptivity targets see ref comments The fully adaptive solution of the problem is very simple We simply pass the maximum number of adaptations to the Newton solver and document the results Done dontinclude fish_poisson cc skipline with fully automatic adaptation until end black box< HR > subsection incremental Incremental adaptation To allow the user more control over the mesh adaptation c oomph lib provides a number of functions that perform individual adaptation steps without re computing the solution immediately This allows the user to perform uniform mesh refinement and unrefinement
the c RefineableQPoissonElement< 2, 3 > is a nine we document the(default) adaptivity targets see ref comments The fully adaptive solution of the problem is very simple We simply pass the maximum number of adaptations to the Newton solver and document the results Done dontinclude fish_poisson cc skipline with fully automatic adaptation until end black box< HR > subsection incremental Incremental adaptation To allow the user more control over the mesh adaptation c oomph lib provides a number of functions that perform individual adaptation steps without re computing the solution immediately This allows the user to perform uniform mesh refinement and impose a specific refinement pattern
the c RefineableQPoissonElement< 2, 3 > is a nine we document the(default) adaptivity targets see ref comments The fully adaptive solution of the problem is very simple We simply pass the maximum number of adaptations to the Newton solver and document the results Done dontinclude fish_poisson cc skipline with fully automatic adaptation until end black box< HR > subsection incremental Incremental adaptation To allow the user more control over the mesh adaptation c oomph lib provides a number of functions that perform individual adaptation steps without re computing the solution immediately This allows the user to perform uniform mesh refinement and impose a specific refinement monitor document the progress of the automatic adaptation The second driver function illustrates some of these functions We start by setting up the create the c DocInfo object and document the adaptivity targets
the c RefineableQPoissonElement< 2, 3 > is a nine we document the(default) adaptivity targets see ref comments The fully adaptive solution of the problem is very simple We simply pass the maximum number of adaptations to the Newton solver and document the results Done dontinclude fish_poisson cc skipline with fully automatic adaptation until end black box< HR > subsection incremental Incremental adaptation To allow the user more control over the mesh adaptation c oomph lib provides a number of functions that perform individual adaptation steps without re computing the solution immediately This allows the user to perform uniform mesh refinement and impose a specific refinement monitor document the progress of the automatic adaptation The second driver function illustrates some of these functions We start by setting up the create the c DocInfo object and document the adaptivity exactly as before
the c RefineableQPoissonElement< 2, 3 > is a nine we document the(default) adaptivity targets see ref comments The fully adaptive solution of the problem is very simple We simply pass the maximum number of adaptations to the Newton solver and document the results Done dontinclude fish_poisson cc skipline with fully automatic adaptation until end black box< HR > subsection incremental Incremental adaptation To allow the user more control over the mesh adaptation c oomph lib provides a number of functions that perform individual adaptation steps without re computing the solution immediately This allows the user to perform uniform mesh refinement and impose a specific refinement monitor document the progress of the automatic adaptation The second driver function illustrates some of these functions We start by setting up the create the c DocInfo object and document the adaptivity exactly as we solve the problem on the original
the c RefineableQPoissonElement< 2, 3 > is a nine we document the(default) adaptivity targets see ref comments The fully adaptive solution of the problem is very simple We simply pass the maximum number of adaptations to the Newton solver and document the results Done dontinclude fish_poisson cc skipline with fully automatic adaptation until end black box< HR > subsection incremental Incremental adaptation To allow the user more control over the mesh adaptation c oomph lib provides a number of functions that perform individual adaptation steps without re computing the solution immediately This allows the user to perform uniform mesh refinement and impose a specific refinement monitor document the progress of the automatic adaptation The second driver function illustrates some of these functions We start by setting up the create the c DocInfo object and document the adaptivity exactly as we solve the problem on the very coarse mesh and document the result
We know that the result is unlikely to be very accurate
We know that the result is unlikely to be very so we apply three levels of uniform refinement
We know that the result is unlikely to be very so we apply three levels of uniform increasing the number of elements from to
We know that the result is unlikely to be very so we apply three levels of uniform increasing the number of elements from and re compute
The solution looks much smoother but we suspect that the corner regions are still under resolved Therefore
The solution looks much smoother but we suspect that the corner regions are still under resolved we call the c we recompute the solution
the next frame shows the solution on the uniformly refined mesh
the final two frames show the progress of the subsequent
the final two frames show the progress of the error estimate driven mesh adaptation< HR >< HR > section problem The problem class The problem class is virtually identical to that used in the< A HREF=`../../../poisson/two_d_poisson/html/index.html`> D Poisson problem without mesh refinement</A > In the present problem we leave the function c Problem::actions_before_newton_solve() empty because the boundary conditions do not change. The function \c RefineableFishPoissonProblem it automatically updates the equation numbering scheme
the final two frames show the progress of the error estimate driven mesh adaptation< HR >< HR > section problem The problem class The problem class is virtually identical to that used in the< A HREF=`../../../poisson/two_d_poisson/html/index.html`> D Poisson problem without mesh refinement</A > In the present problem we leave the function c Problem::actions_before_newton_solve() empty because the boundary conditions do not change. The function \c RefineableFishPoissonProblem it automatically updates the equation numbering and interpolates the solution from the original mesh onto the adapted mesh This is important in nonlinear problems where the provision of a good initial guess for the Newton iteration is vital
and in time dependent problems where the solution at one timestep provides initial conditions for the next one See the discussion of< A HREF=`../../../unsteady_heat/two_d_unsteady_heat_adapt/html/index.html`> the adaptive solution of the unsteady heat equation</A > for more details Furthermore
and in time dependent problems where the solution at one timestep provides initial conditions for the next one See the discussion of< A HREF=`../../../unsteady_heat/two_d_unsteady_heat_adapt/html/index.html`> the adaptive solution of the unsteady heat equation</A > for more details the source function pointers are automatically passed to an element s four son elements when the element is subdivided This allows the adaptation to proceed completely automatically
f to f
Typedef Documentation
i
using i = 1}^2 \frac{\partial^2u}{\partial x_i^2} = -1, \ \ \ \ \ \ \ \ \ \ @E[2DPoisson]@ \f] in the fish-shaped domain \f$D_{fish} \f$, with homogeneous Dirichlet boundary conditions \f[ \left. u\right|_{\partial D_{fish}}=0. \ \ \ \ \ \ \ \ \ \ @E[2DPoisson_BC]@ \f] </TD> </TR> </TABLE> </CENTER> @I w 0.75\textwidth fish_poisson_soln `Plot of the solution ` The sharp corners in the domain create singularities in the solution (its derivatives are unbounded) and so accurate results can only be obtained if we use a sufficiently fine discretisation. Implementing this by uniform mesh refinement would create a huge number of elements in the interior of the domain where the fine discretisation is not required. To avoid this problem, \c oomph-lib provides mesh adaptation routines that automatically adapt the mesh, based on \e a \e posteriori error estimates. Regions in which an error estimator indicates that the solution is not resolved to the required accuracy are refined
Definition at line 43 of file fish_poisson.txt.
Function Documentation
adaptation()
and in time dependent problems where the solution at one timestep provides initial conditions for the next one See the discussion of<A HREF=`../../../unsteady_heat/two_d_unsteady_heat_adapt/html/index.html`> the adaptive solution of the unsteady heat equation</A> for more details the source function pointers are automatically passed to an element s four son elements when the element is subdivided This allows the adaptation to proceed completely without any intervention by the user On return from c certain actions may need to be performed before or after the mesh adaptation (e.g. if flux boundary conditions are applied by \c FaceElements;this is explained in< A HREF=`../../../poisson/two_d_poisson_flux_bc_adapt/html/index.html`> another example</A >)
bounds()
namespace c ConstSourceForPoisson only contains the constant source function f coarse mesh is performed automatically until the solution satisfies the required error bounds (or until the maximum permitted number of adaptation steps has been reached)
f()
namespace c ConstSourceForPoisson only contains the constant source function f f (x)
mesh_pt()
endcode before code problem mesh_pt () -> doc_adaptivity_targets(cout)
Referenced by FishPoissonProblem< ELEMENT >::doc_solution(), RefineableFishPoissonProblem< ELEMENT >::doc_solution(), FishPoissonProblem< ELEMENT >::FishPoissonProblem(), FishPoissonProblem< ELEMENT >::mesh_pt(), RefineableFishPoissonProblem< ELEMENT >::mesh_pt(), and RefineableFishPoissonProblem< ELEMENT >::RefineableFishPoissonProblem().
node()
the c RefineableQPoissonElement<2,3> is a nine node (bi- quadratic)
number()
the c RefineableQPoissonElement<2,3> is a nine we document the (default) adaptivity targets see ref comments The fully adaptive solution of the problem is very simple We simply pass the maximum number of adaptations to the Newton solver and document the results Done dontinclude fish_poisson cc skipline with fully automatic adaptation until end black box<HR> subsection incremental Incremental adaptation To allow the user more control over the mesh adaptation c oomph lib provides a number of functions that perform individual adaptation steps without re computing the solution immediately This allows the user to perform uniform mesh refinement and impose a specific refinement monitor document the progress of the automatic adaptation The second driver function illustrates some of these functions We start by setting up the create the c DocInfo object and document the adaptivity exactly as we solve the problem on the very coarse mesh and document the very coarse until doc_info number ()
Variable Documentation
accurate
We know that the result is unlikely to be very accurate
Definition at line 194 of file fish_poisson.txt.
adaptations
namespace c ConstSourceForPoisson only contains the constant source function f coarse mesh is performed automatically until the solution satisfies the required error and then use incremental adaptations
Definition at line 98 of file fish_poisson.txt.
automatically
and in time dependent problems where the solution at one timestep provides initial conditions for the next one See the discussion of<A HREF=`../../../unsteady_heat/two_d_unsteady_heat_adapt/html/index.html`> the adaptive solution of the unsteady heat equation</A> for more details the source function pointers are automatically passed to an element s four son elements when the element is subdivided This allows the adaptation to proceed completely automatically
Definition at line 335 of file fish_poisson.txt.
before
the c RefineableQPoissonElement<2,3> is a nine we document the (default) adaptivity targets see ref comments The fully adaptive solution of the problem is very simple We simply pass the maximum number of adaptations to the Newton solver and document the results Done dontinclude fish_poisson cc skipline with fully automatic adaptation until end black box<HR> subsection incremental Incremental adaptation To allow the user more control over the mesh adaptation c oomph lib provides a number of functions that perform individual adaptation steps without re computing the solution immediately This allows the user to perform uniform mesh refinement and impose a specific refinement monitor document the progress of the automatic adaptation The second driver function illustrates some of these functions We start by setting up the create the c DocInfo object and document the adaptivity exactly as before
Definition at line 186 of file fish_poisson.txt.
compute
We know that the result is unlikely to be very so we apply three levels of uniform increasing the number of elements from and re compute
Definition at line 200 of file fish_poisson.txt.
f
f to f
Initial value:
{-4} \f$ by adding the statement
   \code
   problem.mesh_pt()->min_permitted_error()=1.0e-4
Definition at line 392 of file fish_poisson.txt.
Furthermore
and in time dependent problems where the solution at one timestep provides initial conditions for the next one See the discussion of<A HREF=`../../../unsteady_heat/two_d_unsteady_heat_adapt/html/index.html`> the adaptive solution of the unsteady heat equation</A> for more details Furthermore
Definition at line 332 of file fish_poisson.txt.
mesh
the next frame shows the solution on the uniformly refined mesh
Definition at line 221 of file fish_poisson.txt.
object
namespace c ConstSourceForPoisson only contains the constant source function f coarse mesh is performed automatically until the solution satisfies the required error and then use incremental allowing us to document how the refinement proceeds dontinclude fish_poisson cc skipline start_of_main until end of main<HR> subsection black_box Black box adaptation We start by creating the Problem object
Definition at line 110 of file fish_poisson.txt.
original
the c RefineableQPoissonElement<2,3> is a nine we document the (default) adaptivity targets see ref comments The fully adaptive solution of the problem is very simple We simply pass the maximum number of adaptations to the Newton solver and document the results Done dontinclude fish_poisson cc skipline with fully automatic adaptation until end black box<HR> subsection incremental Incremental adaptation To allow the user more control over the mesh adaptation c oomph lib provides a number of functions that perform individual adaptation steps without re computing the solution immediately This allows the user to perform uniform mesh refinement and impose a specific refinement monitor document the progress of the automatic adaptation The second driver function illustrates some of these functions We start by setting up the create the c DocInfo object and document the adaptivity exactly as we solve the problem on the original
Definition at line 186 of file fish_poisson.txt.
pattern
the c RefineableQPoissonElement<2,3> is a nine we document the (default) adaptivity targets see ref comments The fully adaptive solution of the problem is very simple We simply pass the maximum number of adaptations to the Newton solver and document the results Done dontinclude fish_poisson cc skipline with fully automatic adaptation until end black box<HR> subsection incremental Incremental adaptation To allow the user more control over the mesh adaptation c oomph lib provides a number of functions that perform individual adaptation steps without re computing the solution immediately This allows the user to perform uniform mesh refinement and impose a specific refinement pattern
Definition at line 174 of file fish_poisson.txt.
problem
the c RefineableQPoissonElement<2,3> is a nine we document the (default) adaptivity targets see ref comments The fully adaptive solution of the problem is very simple We simply pass the maximum number of adaptations to the Newton solver and document the results Done dontinclude fish_poisson cc skipline with fully automatic adaptation until end black box<HR> subsection incremental Incremental adaptation To allow the user more control over the mesh adaptation c oomph lib provides a number of functions that perform individual adaptation steps without re computing the solution immediately This allows the user to perform uniform mesh refinement and impose a specific refinement monitor document the progress of the automatic adaptation The second driver function illustrates some of these functions We start by setting up the problem
Definition at line 3 of file fish_poisson.txt.
Referenced by main(), solve_with_fully_automatic_adaptation(), and solve_with_incremental_adaptation().
process
the c RefineableQPoissonElement<2,3> is a nine we document the (default) adaptivity targets see ref comments The fully adaptive solution of the problem is very simple We simply pass the maximum number of adaptations to the Newton solver and document the results Done dontinclude fish_poisson cc skipline with fully automatic adaptation until end black box<HR> subsection incremental Incremental adaptation To allow the user more control over the mesh adaptation process
Definition at line 122 of file fish_poisson.txt.
refinement
We know that the result is unlikely to be very so we apply three levels of uniform refinement
Definition at line 195 of file fish_poisson.txt.
result
the c RefineableQPoissonElement<2,3> is a nine we document the (default) adaptivity targets see ref comments The fully adaptive solution of the problem is very simple We simply pass the maximum number of adaptations to the Newton solver and document the results Done dontinclude fish_poisson cc skipline with fully automatic adaptation until end black box<HR> subsection incremental Incremental adaptation To allow the user more control over the mesh adaptation c oomph lib provides a number of functions that perform individual adaptation steps without re computing the solution immediately This allows the user to perform uniform mesh refinement and impose a specific refinement monitor document the progress of the automatic adaptation The second driver function illustrates some of these functions We start by setting up the create the c DocInfo object and document the adaptivity exactly as we solve the problem on the very coarse mesh and document the result
Definition at line 190 of file fish_poisson.txt.
scheme
the final two frames show the progress of the error estimate driven mesh adaptation<HR><HR> section problem The problem class The problem class is virtually identical to that used in the<A HREF=`../../../poisson/two_d_poisson/html/index.html`> D Poisson problem without mesh refinement</A> In the present problem we leave the function c Problem::actions_before_newton_solve () empty because the boundary conditions do not change. The function \c RefineableFishPoissonProblem it automatically updates the equation numbering scheme
Definition at line 233 of file fish_poisson.txt.
solution
The solution looks much smoother but we suspect that the corner regions are still under resolved we call the c we recompute the solution
Definition at line 207 of file fish_poisson.txt.
subsequent
the final two frames show the progress of the subsequent
Definition at line 222 of file fish_poisson.txt.
targets
the c RefineableQPoissonElement<2,3> is a nine we document the (default) adaptivity targets see ref comments The fully adaptive solution of the problem is very simple We simply pass the maximum number of adaptations to the Newton solver and document the results Done dontinclude fish_poisson cc skipline with fully automatic adaptation until end black box<HR> subsection incremental Incremental adaptation To allow the user more control over the mesh adaptation c oomph lib provides a number of functions that perform individual adaptation steps without re computing the solution immediately This allows the user to perform uniform mesh refinement and impose a specific refinement monitor document the progress of the automatic adaptation The second driver function illustrates some of these functions We start by setting up the create the c DocInfo object and document the adaptivity targets
Definition at line 180 of file fish_poisson.txt.
Therefore
The solution looks much smoother but we suspect that the corner regions are still under resolved Therefore
Definition at line 203 of file fish_poisson.txt.
to
We know that the result is unlikely to be very so we apply three levels of uniform increasing the number of elements from to
Definition at line 196 of file fish_poisson.txt.
unrefinement
the c RefineableQPoissonElement<2,3> is a nine we document the (default) adaptivity targets see ref comments The fully adaptive solution of the problem is very simple We simply pass the maximum number of adaptations to the Newton solver and document the results Done dontinclude fish_poisson cc skipline with fully automatic adaptation until end black box<HR> subsection incremental Incremental adaptation To allow the user more control over the mesh adaptation c oomph lib provides a number of functions that perform individual adaptation steps without re computing the solution immediately This allows the user to perform uniform mesh refinement and unrefinement
Definition at line 173 of file fish_poisson.txt.
vital
the final two frames show the progress of the error estimate driven mesh adaptation<HR><HR> section problem The problem class The problem class is virtually identical to that used in the<A HREF=`../../../poisson/two_d_poisson/html/index.html`> D Poisson problem without mesh refinement</A> In the present problem we leave the function c Problem::actions_before_newton_solve () empty because the boundary conditions do not change. The function \c RefineableFishPoissonProblem it automatically updates the equation numbering and interpolates the solution from the original mesh onto the adapted mesh This is important in nonlinear problems where the provision of a good initial guess for the Newton iteration is vital
Definition at line 326 of file fish_poisson.txt.