fish_poisson.cc File Reference
Classes
class RefineableFishPoissonProblem< ELEMENT >
Refineable Poisson problem in fish-shaped domain. Template parameter identifies the element type.
Namespaces
namespace ConstSourceForPoisson
Namespace for const source term in Poisson equation.
Functions
void ConstSourceForPoisson::source_function (const Vector< double > &x, double &source)
Const source function.
void solve_with_incremental_adaptation ()
Demonstrate how to solve 2D Poisson problem in fish-shaped domain with mesh adaptation. First we solve on the original coarse mesh. Next we do a few uniform refinement steps and re-solve. Finally, we enter into an automatic adapation loop.
void solve_with_fully_automatic_adaptation ()
Demonstrate how to solve 2D Poisson problem in fish-shaped domain with fully automatic mesh adaptation.
int main ()
Demonstrate how to solve 2D Poisson problem in fish-shaped domain with mesh adaptation.
Variables
double ConstSourceForPoisson::Strength =-1.0
Strength of source function: default value -1.0.
Function Documentation
main()
int main ()
Demonstrate how to solve 2D Poisson problem in fish-shaped domain with mesh adaptation.
Definition at line 325 of file fish_poisson.cc.
References solve_with_fully_automatic_adaptation(), and solve_with_incremental_adaptation().
solve_with_fully_automatic_adaptation()
void solve_with_fully_automatic_adaptation ()
Demonstrate how to solve 2D Poisson problem in fish-shaped domain with fully automatic mesh adaptation.
Definition at line 282 of file fish_poisson.cc.
References RefineableFishPoissonProblem< ELEMENT >::doc_solution(), and RefineableFishPoissonProblem< ELEMENT >::mesh_pt().
Referenced by main().
solve_with_incremental_adaptation()
void solve_with_incremental_adaptation ()
Demonstrate how to solve 2D Poisson problem in fish-shaped domain with mesh adaptation. First we solve on the original coarse mesh. Next we do a few uniform refinement steps and re-solve. Finally, we enter into an automatic adapation loop.
Definition at line 191 of file fish_poisson.cc.
References RefineableFishPoissonProblem< ELEMENT >::doc_solution(), and RefineableFishPoissonProblem< ELEMENT >::mesh_pt().
Referenced by main().