      SUBROUTINE BREAKHSL()
      WRITE(*,*) ' '
      WRITE(*,*) ' '
      WRITE(*,*) '===================================================='
      WRITE(*,*) ' '
      WRITE(*,*) 'Broken dummy code! Please obtain the full'
      WRITE(*,*) 'HSL Fortran sources from '
      WRITE(*,*) ' '
      WRITE(*,*) '    http://www.hsl.rl.ac.uk/ '
      WRITE(*,*) ' '
      WRITE(*,*) 'Place all the hsl routines listed in '
      WRITE(*,*) ' '
      WRITE(*,*) '    external_src/oomph_hsl/dummy_frontal.f'
      WRITE(*,*) ' '
      WRITE(*,*) 'into '
      WRITE(*,*) ' '
      WRITE(*,*) '    external_src/oomph_hsl/frontal.f'
      WRITE(*,*) ' '
      WRITE(*,*) 'and re-run '
      WRITE(*,*) ' '
      WRITE(*,*) '     autogen.sh --rebuild'
      WRITE(*,*) ' '
      WRITE(*,*) 'in the top-level oomph-lib directory.'
      WRITE(*,*) ' '
      WRITE(*,*) '[Terminating code execution] '
      WRITE(*,*) ' '
      WRITE(*,*) '==================================================='
      WRITE(*,*) ' '
      WRITE(*,*) ' '
      STOP
      END

C*******************************************************************

c HERE ARE THE BROKEN STUBS FOR THE SUBROUTINES REQUIRED FROM HSL


C*******************************************************************
      SUBROUTINE MA42ID(ICNTL,CNTL,ISAVE)
      DOUBLE PRECISION CNTL(2)
      INTEGER ICNTL(8),ISAVE(45)
      INTEGER I
      CALL BREAKHSL()
      END
C*******************************************************************
      SUBROUTINE MA42AD(NVAR,IVAR,NDF,LAST,LENLST,ICNTL,ISAVE,INFO)
      INTEGER LENLST,NDF,NVAR
      INTEGER ICNTL(8),INFO(23),ISAVE(45),IVAR(NVAR),LAST(LENLST)
      INTEGER I,JVAR,K,LP
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MA42JD(NVAR,IVAR,NDF,LAST,NMAXE,IFSIZE,ICNTL,ISAVE,
     +                  INFO)
      INTEGER NDF,NMAXE,NVAR
      INTEGER ICNTL(8),IFSIZE(5),INFO(23),ISAVE(45),IVAR(NVAR),LAST(NDF)
      INTEGER IELL,ISTATC,KFRNT,L,LFRNT,LK,LP,MFR,NELL
      INTEGER PIVBLK,KR,J,J1
      CALL BREAKHSL()
      END
C*******************************************************************
      SUBROUTINE MA42PD(ISTRM,LENBUF,LENFLE,ICNTL,ISAVE,INFO)
      INTEGER ICNTL(8),INFO(23),ISAVE(45),ISTRM(3),LENBUF(3),LENFLE(3)
      INTEGER IFILE(3),ISIZE(3),NUMBLK(3)
      INTEGER I,ICON,IOS,LP,MP
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MA42BD(NVAR,IVAR,NDF,LAST,NMAXE,AVAR,NRHS,RHS,LRHS,LX,
     +                  X,NFRONT,LENBUF,LW,W,LIW,IW,ICNTL,CNTL,ISAVE,
     +                  INFO,RINFO)
      DOUBLE PRECISION ZERO
      PARAMETER (ZERO=0.0D0)
      INTEGER LIW,LRHS,LW,LX,NDF,NMAXE,NRHS,NVAR
      DOUBLE PRECISION AVAR(NMAXE,NVAR),CNTL(2),RHS(NMAXE,LRHS),
     +                 RINFO(2),W(LW),X(LX,LRHS)
      INTEGER ICNTL(8),INFO(23),ISAVE(45),IVAR(NVAR),IW(LIW),LAST(NDF),
     +        LENBUF(3),NFRONT(2)
      INTEGER DIMBUF,DIMIBF,FA,FRHS,I,IELL,JBUFL,JBUFR,JBUFU,K,KDEST,
     +        KFRNT,KHED,KPIV,KPVLNK,L,LDEST,LFL,LFRNT,LHED,LLIW,LLW,LP,
     +        MFR,NELL,NFR,PIVBLK,BZERO
      DOUBLE PRECISION Y(1,1)
      INTEGER IFILE(3),IREC(3),ISIZE(3),MKEY(3),NUMBLK(3)
      CALL BREAKHSL()
      END
C*********************************************************************
      SUBROUTINE MA42CD(TRANS,NRHS,LX,B,X,LW,W,LIW,IW,ICNTL,ISAVE,INFO)
      DOUBLE PRECISION ZERO
      PARAMETER (ZERO=0.0D0)
      INTEGER LIW,LW,LX,NRHS
      LOGICAL TRANS
      DOUBLE PRECISION B(LX,NRHS),W(LW),X(LX,NRHS)
      INTEGER ICNTL(8),INFO(23),ISAVE(45),IW(LIW)
      INTEGER IFILE(3),IREC(3),ISIZE(3),MKEY(3)
      INTEGER DIMIBF,I,L,L1,L2,L3,LBUFR,LLW,LP,NFMAX,NRHSB
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MA42DD(IND,NRHS,NDF,X,LYINBF,LY1,LY2,Y,BUFR,DIMBUF,
     +                  IBUFR,DIMIBF,W,LDW,LP,NRHSB,IFILE,IREC,ISIZE,
     +                  MKEY,INFO)
      DOUBLE PRECISION ONE
      PARAMETER (ONE=1.0D0)
      INTEGER DIMBUF,DIMIBF,IND,INFO,LDW,LP,LY1,LY2,NDF,NRHS,NRHSB
      LOGICAL LYINBF
      DOUBLE PRECISION BUFR(DIMBUF),W(LDW,NRHS),X(NDF,NRHS),Y(LY1,LY2)
      INTEGER IBUFR(DIMIBF),IFILE(3),IREC(3),ISIZE(3),MKEY(3)
      EXTERNAL DGEMM,DGEMV,DTPSV,MA42LD
      INTRINSIC ABS,MAX
      INTEGER FIL,I,IFIL,IKEY,ILNGTH,IPNT,IR1,IR2,IREAD,IRECD,J1,J2,
     +        JFLAG,JFRNT1,JR1,JR2,K,K1,K1PK,K2,K2PK,K3,K3PK,KEY,KFRNT,
     +        KFRNT1,KRO,L,LBUFR,LCO,LENGTH,LFRNT,LFRNT1,LIBUFR,NLOOP,
     +        NPIV,NPIV1,NREAD,NREC
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MA42ED(IND,NRHS,NDF,R1,BUFR,DIMBUF,IBUFR,DIMIBF,W,LDW,
     +                  LP,NRHSB,IFILE,ISIZE,MKEY,INFO)
      DOUBLE PRECISION ONE,ZERO
      PARAMETER (ONE=1.0D0,ZERO=0.0D0)
      INTEGER DIMBUF,DIMIBF,IND,INFO,LDW,LP,NDF,NRHS,NRHSB
      DOUBLE PRECISION BUFR(DIMBUF),R1(NDF,NRHS),W(LDW,NRHS)
      INTEGER IBUFR(DIMIBF),IFILE(3),ISIZE(3),MKEY(3)
      INTEGER FIL,I,IFIL,IKEY,ILNGTH,IP1,IR2,IREAD,IRECD,ISPACE,J1,J2,
     +        JFLAG,JFRNT,JFRNT1,JR2,JRECD,JSPACE,K,K1,K1PK,KEY,KFRNT,
     +        KFRNT1,KRO,L,LBUFR,LENGTH,LFRNT,LFRNT1,LIBUFR,NLOOP,NPIV,
     +        NPIV1,NREAD,NREC
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MA42FD(AVAR,RHS,LRHS,NRHS,IVAR,LAST,NDF,NMAXE,NVAR,
     +                  MFRONT,NFRONT,BUFRL,LLB,BUFRU,LUB,IBUFR,LIBUFR,
     +                  FA,FRHS,LHED,KHED,KPIV,KPVLNK,LDEST,KDEST,ICNTL,
     +                  CNTL,IFILE,IREC,ISIZE,MKEY,NUMBLK,IELL,NELL,
     +                  KFRNT,LFRNT,ICOM,PIVBLK,BZERO,INFO,RINFO)
      DOUBLE PRECISION ZERO
      PARAMETER (ZERO=0.0D0)
      INTEGER IELL,KFRNT,LFRNT,LIBUFR,LLB,LRHS,LUB,MFRONT,NDF,NELL,
     +        NFRONT,NMAXE,NRHS,NVAR,PIVBLK,BZERO
      DOUBLE PRECISION AVAR(NMAXE,NVAR),BUFRL(LLB),BUFRU(LUB),CNTL(2),
     +                 FA(MFRONT,NFRONT),FRHS(MFRONT,LRHS),
     +                 RHS(NMAXE,LRHS),RINFO(2)
      INTEGER IBUFR(LIBUFR),ICNTL(8),ICOM(5),IFILE(3),INFO(23),IREC(3),
     +        ISIZE(3),IVAR(NVAR),KDEST(MFRONT),KHED(MFRONT),
     +        KPIV(NFRONT),KPVLNK(NFRONT),LAST(NDF),LDEST(NFRONT),
     +        LHED(NFRONT),MKEY(3),NUMBLK(3)
      DOUBLE PRECISION DET,OPS,PIVOT
      INTEGER I,IFORCE,ISTATC,KPIVRX,KR,KS,L,LFREE,LFRNTT,LK,LP,LPIVCX,
     +        MFR,MP,MVAR,NELIM,OFDIAG
      INTEGER NSIZE,NEW
      LOGICAL LSTAT
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MA42GD(IND,JFL,FA,FRHS,NRHS,KFRNT,LFRNT,NPIV,BUFR,
     +                 LBUFR,MFRONT,LP,IFILE,IREC,ISIZE,MKEY,
     +                 NUMBLK,IELL,NELL,INFO)
      DOUBLE PRECISION ZERO
      PARAMETER (ZERO=0.0D0)
      INTEGER IELL,IFILE,IND,IREC,ISIZE,JFL,KFRNT,LBUFR,LFRNT,LP,
     +        MFRONT,MKEY,NELL,NPIV,NRHS,NUMBLK
      DOUBLE PRECISION BUFR(LBUFR),FA(MFRONT,*),FRHS(MFRONT,*)
      INTEGER INFO(23)
      INTEGER IBUFR(1)
      INTEGER I,I1,IBLOCK,IFRNT1,ISPACE,IUP,J,J1,J2,JBUFR,JFLAG,JFRNT1,
     +        K,K1,KFRNT1,LENGTH,LFRNT1,LIBUFR,NBUFR,NPIV1
      EXTERNAL MA42KD,MA42LD
      INTRINSIC MIN
      INTEGER NZEROL,NZEROU
      SAVE NZEROL,NZEROU
      CALL BREAKHSL()
      END
C*********************************************************************
      SUBROUTINE MA42HD(JFL,KFRNT,LFRNT,NPIV,IBUFR,LIBUFR,KHED,LHED,
     +                 MFRONT,NFRONT,LP,IFILE,IREC,ISIZE,MKEY,NUMBLK,
     +                 IELL,NELL,INFO)
      INTEGER IELL,IFILE,IREC,ISIZE,JFL,KFRNT,LFRNT,LIBUFR,LP,MFRONT,
     +        MKEY,NELL,NFRONT,NPIV,NUMBLK
      INTEGER IBUFR(LIBUFR),INFO(23),KHED(MFRONT),LHED(NFRONT)
      INTEGER I,ISPACE,J,J1,J2,JBUFR,JFLAG,K,K1,LBUFR,LENGTH,NBUFR
      DOUBLE PRECISION BUFR(1)
      INTEGER ITEMP(4)
      CALL BREAKHSL()
      END
C*******************************************************************
      SUBROUTINE MA42KD(JFL,IND,LENGTH,IFILE,ISIZE,MKEY,NUMBLK,IREC,
     +                  IELL,NELL,LP,INFO)
      INTEGER IELL,IFILE,IND,IREC,ISIZE,JFL,LENGTH,LP,MKEY,NELL,NUMBLK
      INTEGER INFO(23)
      INTEGER INFOIN,ISPACE,JFIT,JFIT1,NBUFR,NWRITE
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MA42LD(IOPT,IFILE,MKEY,BUFR,LBUFR,IBUFR,LIBUFR,LP,
     +                  JFLAG)
      INTEGER IFILE,IOPT,JFLAG,LBUFR,LIBUFR,LP,MKEY
      DOUBLE PRECISION BUFR(LBUFR)
      INTEGER IBUFR(LIBUFR)
      INTEGER IOS
      CALL BREAKHSL()
      END
C*********************************************************************
      SUBROUTINE MA42MD(IELL,AVAR,LRHS,NMAXE,RHS,NRHS,IVAR,LAST,NDF,
     +                  NVAR,MFRONT,NFRONT,FA,FRHS,LHED,KHED,KPIV,
     +                  KPVLNK,LDEST,KDEST,ISTATC,LFREE,KR,KFRNT,LFRNT,
     +                  INFO)
      DOUBLE PRECISION ZERO
      PARAMETER (ZERO=0.0D0)
      INTEGER IELL,ISTATC,KFRNT,KR,LFREE,LFRNT,LRHS,MFRONT,NDF,NFRONT,
     +        NMAXE,NRHS,NVAR
      DOUBLE PRECISION AVAR(NMAXE,NVAR),FA(MFRONT,NFRONT),
     +                 FRHS(MFRONT,LRHS),RHS(NMAXE,LRHS)
      INTEGER INFO(23),IVAR(NVAR),KDEST(MFRONT),KHED(MFRONT),
     +        KPIV(NFRONT),KPVLNK(NFRONT),LAST(NDF),LDEST(NFRONT),
     +        LHED(NFRONT)
      INTEGER IPOS,J,JVAR,K,KC1,KDST,KPOS,KR1,L,LDST,LELL,LFR,LPOS,MFR,
     +        NFREE,NUVAR
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MA42ND(IELL,NDF,LAST,MFRONT,NFRONT,FA,LHED,KHED,LRHS,
     +                  NRHS,FRHS,KDEST,LDEST,KPIV,KPVLNK,KPIVRX,LPIVCX,
     +                  PIVOT,KFRNT,LFRNT,KR,KS,NMAXE,NELIM,IFORCE,
     +                  LIBUFR,IBUFR,BUFRL,LLB,BUFRU,LUB,IFILE,IREC,
     +                  ISIZE,MKEY,NUMBLK,DET,OPS,NELL,CNTL,ICNTL,INFO,
     +                  OFDIAG,NSIZE,LSTAT)
      DOUBLE PRECISION ONE,ZERO
      PARAMETER (ONE=1.0D0,ZERO=0.0D0)
      DOUBLE PRECISION DET,OPS,PIVOT
      INTEGER IELL,IFORCE,KFRNT,KPIVRX,KR,KS,LFRNT,LIBUFR,LLB,LPIVCX,
     +        LRHS,LUB,MFRONT,NDF,NELIM,NELL,NFRONT,NMAXE,NRHS,NSIZE,
     +        OFDIAG
      LOGICAL LSTAT
      DOUBLE PRECISION BUFRL(LLB),BUFRU(LUB),CNTL(2),FA(MFRONT,NFRONT),
     +                 FRHS(MFRONT,LRHS)
      INTEGER IBUFR(LIBUFR),ICNTL(8),IFILE(3),INFO(23),IREC(3),ISIZE(3),
     +        KDEST(MFRONT),KHED(MFRONT),KPIV(NFRONT),KPVLNK(NFRONT),
     +        LAST(NDF),LDEST(NFRONT),LHED(NFRONT),MKEY(3),NUMBLK(3)
      DOUBLE PRECISION GMON,GMONX,PIVINV,PIVX,RMAX,SWAP
      INTEGER CHFRNT,I,IAUTO,IELIM,ISRCH,J,JJ,JSRCH,K,KFR,KFRO,KH,KK,
     +        KMAX,KPIVKR,KPIVRO,KPOS,KPRE,KRTEMP,KX,L,LCOL,LFR,LFRO,LK,
     +        LL,LP,LPIVCO,LPOS,LPRE,LTEMP,MFR,MP,L1
      INTEGER IDAMAX
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MA42OD(IELL,AVAR,LRHS,NMAXE,RHS,NRHS,IVAR,NDF,LAST,
     +                  NVAR,MFRONT,NFRONT,LHED,KHED,KR,KPIV,KPVLNK,
     +                  LDEST,KDEST,ISTATC,LFREE,FRHS,BUFRL,LLB,BUFRU,
     +                  LUB,IBUFR,LIBUFR,MVAR,KFRNT,LFRNT,FA,IFILE,IREC,
     +                  ISIZE,MKEY,NUMBLK,DET,OPS,NELL,CNTL,ICNTL,INFO)
      DOUBLE PRECISION ONE,ZERO
      PARAMETER (ONE=1.0D0,ZERO=0.0D0)
      DOUBLE PRECISION DET,OPS
      INTEGER IELL,ISTATC,KFRNT,KR,LFREE,LFRNT,LIBUFR,LLB,LRHS,LUB,
     +        MFRONT,MVAR,NDF,NELL,NFRONT,NMAXE,NRHS,NVAR
      DOUBLE PRECISION AVAR(NMAXE,NVAR),BUFRL(LLB),BUFRU(LUB),CNTL(2),
     +                 FA(MFRONT,NFRONT),FRHS(MFRONT,LRHS),
     +                 RHS(NMAXE,LRHS)
      INTEGER IBUFR(LIBUFR),ICNTL(8),IFILE(3),INFO(23),IREC(3),ISIZE(3),
     +        IVAR(NVAR),KDEST(MFRONT),KHED(MFRONT),KPIV(NFRONT),
     +        KPVLNK(NFRONT),LAST(NDF),LDEST(NFRONT),LHED(NFRONT),
     +        MKEY(3),NUMBLK(3)
      DOUBLE PRECISION PIVINV,PIVOT,RMAX,SMAX,SWAP
      INTEGER I,IMAX,IPIV,IPOS,IRHS,ISWAP,J,J1,JCOL,JJ,JSTATC,JVAR,K,
     +        KDST,KFR,KFRNEW,KFROLD,KPOS,KR1,L,LC1,LDST,LFR,LFRNEW,
     +        LFROLD,LK,LP,MFR,MOVE,MP,NFREE,NUMPIV,NUVAR,NUVRP1
      LOGICAL LDET
      INTEGER IDAMAX
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MC60AD(N,LIRN,IRN,ICPTR,ICNTL,IW,INFO)
      INTEGER N
      INTEGER LIRN
      INTEGER IRN(LIRN)
      INTEGER ICPTR(N+1)
      INTEGER ICNTL(2)
      INTEGER IW(N)
      INTEGER INFO(4)
      INTEGER CKP1,I,I1,I2,II,IOUT,IPOS,IREP,J,KZ,LP,NDIAG,NEWTAU
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MC60BD(N,LIRN,IRN,ICPTR,NSUP,SVAR,VARS,IW)
      INTEGER N
      INTEGER LIRN
      INTEGER IRN(LIRN)
      INTEGER ICPTR(N+1)
      INTEGER NSUP
      INTEGER SVAR(N)
      INTEGER VARS(N)
      INTEGER IW(2*N)
      INTEGER FLAG
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MC60CD(N,NSUP,LIRN,IRN,ICPTR,VARS,JCNTL,
     +                  PERMSV,WEIGHT,PAIR,INFO,IW,W)
      INTEGER N,NSUP,LIRN,IRN(LIRN),ICPTR(NSUP+1),VARS(NSUP),JCNTL(2)
      INTEGER PERMSV(NSUP),PAIR(2,NSUP/2),INFO(4),IW(3*NSUP+1)
      DOUBLE PRECISION WEIGHT(2),W(NSUP)
      INTEGER DEGREE,I,IL,HINFO(6),J,K,LIST,LSTNUM,LWIDTH,LWDTH1,
     *        LZNUM,MAXPSV,MINPSV,NLVL,NLVL1,NODES,NSTOP,NSTRT,NVARS,XLS
      DOUBLE PRECISION NWGHT(2)
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MC60DD(N,NSUP,SVAR,VARS,PERMSV,PERM,POSSV)
      INTEGER N
      INTEGER NSUP
      INTEGER SVAR(N)
      INTEGER VARS(NSUP)
      INTEGER PERMSV(NSUP)
      INTEGER PERM(N)
      INTEGER POSSV(NSUP)
      INTEGER I,IS,L
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MC60ED(N,NSUP,LIRN,IRN,ICPTR,SVAR,VARS,PERMSV,PERM,IW)
      INTEGER N,NSUP,LIRN
      INTEGER IRN(LIRN),ICPTR(NSUP+1),PERM(N),PERMSV(NSUP),IW(NSUP),
     *        SVAR(N),VARS(NSUP)
      INTEGER I,IS,JS,K,L,M
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MC60FD(N,NSUP,LIRN,IRN,ICPTR,VARS,PERMSV,IW,RINFO)
      DOUBLE PRECISION ZERO
      PARAMETER (ZERO=0.0D0)
      INTEGER LIRN,N,NSUP
      INTEGER IRN(LIRN),IW(2*NSUP+1),PERMSV(NSUP),ICPTR(NSUP+1),
     *        VARS(NSUP)
      DOUBLE PRECISION RINFO(4)
      INTEGER I,IMIN,J,JSTOP,JSTRT,K,NACTIV,NBR,NV
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MC60GD(N,NSUP,LIRN,IRN,ICPTR,VARS,PERMSV,IW,RINFO)
      DOUBLE PRECISION ZERO
      PARAMETER (ZERO=0.0D0)
      INTEGER LIRN,N,NSUP
      DOUBLE PRECISION RINFO(4)
      INTEGER ICPTR(NSUP+1),IRN(LIRN),IW(NSUP),PERMSV(NSUP),VARS(NSUP)
      INTEGER I,IEQ,J,JSTOP,JSTRT,K,KFRNT,LFRNT,MFR,NV
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MC60HD(N,NSUP,LIRN,IRN,ICPTR,VARS,MASK,LS,XLS,LIST,
     +                 INFO)
      INTEGER N,NSUP,LIRN
      INTEGER ICPTR(NSUP+1),IRN(LIRN),LIST(NSUP),LS(NSUP),
     +        MASK(NSUP),VARS(NSUP),XLS(NSUP+1),INFO(6)
      INTEGER DEGREE,I,J,LSIZE,LWIDTH,MAIN,MAXDEP,
     +        MINDEG,MINWID,NLSIZE,NLVL,NODE,NODES,NSTOP,NSTRT,NVARS
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MC60JD(NSUP,LIRN,NODES,NSTRT,LSTNUM,IRN,ICPTR,VARS,
     +                  STATUS,WEIGHT,NLIST,QUEUE,DEG,PRIOR)
      INTEGER LIRN,LSTNUM,NSUP,NODES,NSTRT
      INTEGER DEG(NSUP),ICPTR(NSUP+1),IRN(LIRN),NLIST(NSUP),
     +        QUEUE(0:NODES-1),STATUS(NSUP),VARS(NSUP)
      DOUBLE PRECISION WEIGHT(2),PRIOR(NSUP)
      INTEGER ADDRES,DEGREE,FATHER,I,ISTOP,ISTRT,J,JSTOP,JSTRT,J1,J2,
     +        K,L,NABOR,NBR,NEXT,NODE,NQ,QNODE,SON,THRESH
      PARAMETER (THRESH=100)
      DOUBLE PRECISION MAXPRT,PNODE,PRTY
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MC60LD(ROOT,MAXWID,NSUP,LIRN,IRN,ICPTR,VARS,MASK,LS,
     +                 XLS,NLVL,LWIDTH,NVARS)
      INTEGER LWIDTH,MAXWID,NSUP,NLVL,LIRN,ROOT,NVARS
      INTEGER ICPTR(NSUP+1),IRN(LIRN),LS(NSUP),MASK(NSUP),
     *        VARS(NSUP),XLS(NSUP+1)
      INTEGER I,J,LBEGIN,LNBR,LVLEND,LW,NBR,NODE
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MC60OD(N,NC,LIRN,IRN,ICPTR,SVAR,NSUP,NEW,VARS,FLAG)
      INTEGER N
      INTEGER NC
      INTEGER LIRN
      INTEGER IRN(LIRN)
      INTEGER ICPTR(NC+1)
      INTEGER SVAR(N)
      INTEGER NSUP
      INTEGER NEW(N)
      INTEGER VARS(N)
      INTEGER FLAG(N)
      INTEGER I,IS,J,JS,K,K1,K2
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MC60PD(N,NSUP,LIRN,IRN,ICPTR,SVAR,VARS,VAR,FLAG)
      INTEGER N
      INTEGER LIRN
      INTEGER IRN(LIRN)
      INTEGER NSUP
      INTEGER ICPTR(N+1)
      INTEGER SVAR(N)
      INTEGER VARS(NSUP)
      INTEGER VAR(NSUP)
      INTEGER FLAG(NSUP)
      INTEGER I,IS,J,JS,K,K1,L
      CALL BREAKHSL()
      END
C*******************************************************************
      SUBROUTINE MC63ID(ICNTL)
      INTEGER ICNTL(10)
      INTEGER I
      CALL BREAKHSL()
      END
C**********************************************************************
      SUBROUTINE MC63AD(DIRECT,N,NELT,NE,ELTVAR,ELTPTR,ORDER,PERM,NSUP,
     +                 VARS,SVAR,WT,LIW,IW,LW,W,ICNTL,INFO,RINFO)
      DOUBLE PRECISION ONE,TWO,ZERO
      PARAMETER (ONE=1.0D0,TWO=2.0D0,ZERO=0.0D0)
      INTEGER LIW,LW,N,NE,NELT,NSUP
      LOGICAL DIRECT
      DOUBLE PRECISION RINFO(6),W(LW),WT(3)
      INTEGER ELTPTR(NELT+1),ELTVAR(NE),ICNTL(10),INFO(15),IW(LIW),
     +        ORDER(NELT),PERM(*),SVAR(N),VARS(N)
      INTEGER FLAG,I,IERR,IOUT,IPERM,IPTR,IRN,IW1,IWORK,J,JCNTL,K,KEY,
     +        KSUP,LENIP,LENIRN,LP,M,MP,NEED,NEW,NNE,NODES,NZ,PAIR,
     +        SELTPR,SELTVR,USED
      DOUBLE PRECISION WEIGHT(2)
      INTEGER ICNL60(2),INFO60(4),JNFO(4)
      CALL BREAKHSL()
      END
C***********************************************************************
      SUBROUTINE MC63BD(ICNTL,N,NSUP,NELT,NE,ELTVAR,ELTPTR,VARS,ORDER,
     +                 IW,INFO,RINFO)
      DOUBLE PRECISION ZERO
      PARAMETER (ZERO=0.0D0)
      INTEGER ICNTL,N,NE,NELT,NSUP
      DOUBLE PRECISION RINFO(3)
      INTEGER ELTPTR(NELT+1),ELTVAR(NE),INFO(4),IW(NSUP),ORDER(NELT),
     +        VARS(NSUP)
      INTEGER I,ICOUNT,IDUP,IELT,IOUT,J,JJ,JSTOP,JSTRT,JVAR,KFRNT
      CALL BREAKHSL()
      END
C*****************************************************************
      SUBROUTINE MC63CD(DIRECT,N,NELT,NZ,NSUP,ELTVAR,ELTPTR,IRN,LENIRN,
     +                 IP,LENIP,SVAR,SELTVR,SELTPR,IW,M,ICNTL,IERR,NNE)
      INTEGER IERR,LENIP,LENIRN,M,N,NELT,NNE,NSUP,NZ
      LOGICAL DIRECT
      INTEGER ELTPTR(NELT+1),ELTVAR(NZ),ICNTL(10),IP(LENIP),IRN(LENIRN),
     +        IW(M),SELTPR(NSUP+1),SELTVR(NZ),SVAR(N)
      INTEGER I,ICOUNT,IELT,J,J1,J2,JJ,JSUP,JVAR,K,K1,K2,KADJ,KELT,KSUP
      CALL BREAKHSL()
      END
C******************************************************************
      SUBROUTINE MC63DD(NELT,NSUP,NNE,NE,ELTVAR,ELTPTR,VARS,IRN,ICPTR,
     +                 ORDER,IW,IW1,W,ICNTL,WT)
      DOUBLE PRECISION FIVE,ONE,TEN,TWO,ZERO
      PARAMETER (FIVE=5.0D0,ONE=1.0D0,TEN=10.0D0,TWO=2.0D0,ZERO=0.0D0)
      INTEGER NE,NELT,NNE,NSUP
      DOUBLE PRECISION W(NELT),WT(3)
      INTEGER ELTPTR(NELT+1),ELTVAR(NE),ICNTL(10),ICPTR(NELT+1),
     +        IRN(NNE),IW(4*NELT+2),IW1(2*NSUP),ORDER(NELT),VARS(NSUP)
      INTEGER DEGREE,DIST,I,IELIM,IFRNT,IL,IVARS,J,LIST,LS,LSTNUM,
     +        LWIDTH,MAXPSV,MINPSV,NLIST,NLVL,NODES,NSTRT,NVARS,QUEUE,
     +        UNNUM,XLS
      DOUBLE PRECISION WEIGHT(3)
      INTEGER HINFO(6)
      CALL BREAKHSL()
      END
C***********************************************************************
      SUBROUTINE MC63ED(NELT,NNE,NODES,NSUP,NSTRT,LSTNUM,VARS,NE,ELTVAR,
     +                 ELTPTR,IRN,ICPTR,STATUS,NLIST,QUEUE,PRIOR,IFRNT,
     +                 IELIM,DIST,UNNUM,WEIGHT)
      INTEGER THRESH
      PARAMETER (THRESH=100)
      INTEGER LSTNUM,NE,NELT,NNE,NODES,NSTRT,NSUP
      DOUBLE PRECISION PRIOR(NELT),WEIGHT(3)
      INTEGER DIST(NELT),ELTPTR(NELT+1),ELTVAR(NE),ICPTR(NELT+1),
     +        IELIM(NSUP),IFRNT(NSUP),IRN(NNE),NLIST(NELT),
     +        QUEUE(0:NODES-1),STATUS(NELT),UNNUM(NELT),VARS(NSUP)
      DOUBLE PRECISION MAXPRT,PNODE,PRTY,W1,W2,W3
      INTEGER ADDRES,FATHER,I,ISTOP,ISTRT,J,J1,J2,K,L,L1,LFRNT,NBR,NEXT,
     +        NFRNT,NGAIN,NODE,NQ,QNODE,SON
      CALL BREAKHSL()
      END
C***********************************************************
      SUBROUTINE MC63FD(NSUP,NELT,NZ,SELTVR,SELTPR,IPERM,KEY,LIST)
      INTEGER NELT,NSUP,NZ
      INTEGER IPERM(NSUP),KEY(NELT),LIST(NELT),SELTPR(NELT+1),SELTVR(NZ)
      INTEGER I,IELL,J,JSTOP,JSTRT,L
      CALL BREAKHSL()
      END
C********************************************************************
      SUBROUTINE MC63GD(N,LIST,KEY)
      INTEGER N
      INTEGER KEY(N),LIST(N)
      INTEGER GUESS,I,LL,LM,LR,LTEMP,NL,NR,STKTOP
      INTEGER IW(64)
      CALL BREAKHSL()
      END




