RefineablePeriodicLoadProblem< ELEMENT > Class Template Reference
Periodic loading problem.
Public Member Functions
RefineablePeriodicLoadProblem (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly)
Constructor: Pass number of elements in x and y directions and lengths.
void actions_before_newton_solve ()
Update before solve is empty.
void actions_after_newton_solve ()
Update after solve is empty.
void actions_before_adapt ()
Actions before adapt: Wipe the mesh of traction elements.
void actions_after_adapt ()
Actions after adapt: Rebuild the mesh of traction elements.
void doc_solution (DocInfo &doc_info)
Doc the solution.
Private Member Functions
void assign_traction_elements ()
Allocate traction elements on the top surface.
void delete_traction_elements ()
Kill traction elements on the top surface.
Private Attributes
TreeBasedRefineableMeshBase * Bulk_mesh_pt
Pointer to the (refineable!) bulk mesh.
Mesh * Surface_mesh_pt
Pointer to the mesh of traction elements.
Detailed Description
template<class ELEMENT>
class RefineablePeriodicLoadProblem< ELEMENT >
Periodic loading problem.
Definition at line 91 of file refineable_periodic_load.cc.
Constructor & Destructor Documentation
RefineablePeriodicLoadProblem()
template<class ELEMENT >
RefineablePeriodicLoadProblem< ELEMENT >::RefineablePeriodicLoadProblem (const unsigned & nx, const unsigned & ny, const double & lx, const double & ly)
Constructor: Pass number of elements in x and y directions and lengths.
Problem constructor: Pass number of elements in the coordinate directions and the domain sizes.
Definition at line 165 of file refineable_periodic_load.cc.
References Global_Parameters::E(), Global_Parameters::exact_solution(), and Global_Parameters::Finite.
Member Function Documentation
actions_after_adapt()
template<class ELEMENT >
void RefineablePeriodicLoadProblem< ELEMENT >::actions_after_adapt () [inline]
Actions after adapt: Rebuild the mesh of traction elements.
Definition at line 117 of file refineable_periodic_load.cc.
References RefineablePeriodicLoadProblem< ELEMENT >::assign_traction_elements().
actions_after_newton_solve()
template<class ELEMENT >
void RefineablePeriodicLoadProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update after solve is empty.
Definition at line 104 of file refineable_periodic_load.cc.
actions_before_adapt()
template<class ELEMENT >
void RefineablePeriodicLoadProblem< ELEMENT >::actions_before_adapt () [inline]
Actions before adapt: Wipe the mesh of traction elements.
Definition at line 107 of file refineable_periodic_load.cc.
References RefineablePeriodicLoadProblem< ELEMENT >::delete_traction_elements().
actions_before_newton_solve()
template<class ELEMENT >
void RefineablePeriodicLoadProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update before solve is empty.
Definition at line 101 of file refineable_periodic_load.cc.
assign_traction_elements()
template<class ELEMENT >
void RefineablePeriodicLoadProblem< ELEMENT >::assign_traction_elements [private]
Allocate traction elements on the top surface.
Make traction elements along the top boundary of the bulk mesh.
Definition at line 300 of file refineable_periodic_load.cc.
References Global_Parameters::periodic_traction().
Referenced by RefineablePeriodicLoadProblem< ELEMENT >::actions_after_adapt().
delete_traction_elements()
template<class ELEMENT >
void RefineablePeriodicLoadProblem< ELEMENT >::delete_traction_elements () [inline], [private]
Kill traction elements on the top surface.
Definition at line 135 of file refineable_periodic_load.cc.
References RefineablePeriodicLoadProblem< ELEMENT >::Surface_mesh_pt.
Referenced by RefineablePeriodicLoadProblem< ELEMENT >::actions_before_adapt().
doc_solution()
template<class ELEMENT >
void RefineablePeriodicLoadProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 340 of file refineable_periodic_load.cc.
References Global_Parameters::exact_solution().
Referenced by main().
Member Data Documentation
Bulk_mesh_pt
template<class ELEMENT >
TreeBasedRefineableMeshBase* RefineablePeriodicLoadProblem< ELEMENT >::Bulk_mesh_pt [private]
Pointer to the (refineable!) bulk mesh.
Definition at line 152 of file refineable_periodic_load.cc.
Surface_mesh_pt
template<class ELEMENT >
Mesh* RefineablePeriodicLoadProblem< ELEMENT >::Surface_mesh_pt [private]
Pointer to the mesh of traction elements.
Definition at line 155 of file refineable_periodic_load.cc.
Referenced by RefineablePeriodicLoadProblem< ELEMENT >::delete_traction_elements().
The documentation for this class was generated from the following file:
refineable_periodic_load.cc