PeriodicLoadProblem< ELEMENT > Class Template Reference
Periodic loading problem.
Public Member Functions
PeriodicLoadProblem (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly)
Constructor: Pass number of elements in x and y directions and lengths.
void actions_before_newton_solve ()
Update before solve is empty.
void actions_after_newton_solve ()
Update after solve is empty.
void doc_solution (DocInfo &doc_info)
Doc the solution.
Private Member Functions
void assign_traction_elements ()
Allocate traction elements on the top surface.
Private Attributes
Mesh * Bulk_mesh_pt
Pointer to the bulk mesh.
Mesh * Surface_mesh_pt
Pointer to the mesh of traction elements.
Detailed Description
template<class ELEMENT>
class PeriodicLoadProblem< ELEMENT >
Periodic loading problem.
Definition at line 91 of file periodic_load.cc.
Constructor & Destructor Documentation
PeriodicLoadProblem()
template<class ELEMENT >
PeriodicLoadProblem< ELEMENT >::PeriodicLoadProblem (const unsigned & nx, const unsigned & ny, const double & lx, const double & ly)
Constructor: Pass number of elements in x and y directions and lengths.
Problem constructor: Pass number of elements in coordinate directions and size of domain.
Definition at line 128 of file periodic_load.cc.
References Global_Parameters::E(), Global_Parameters::exact_solution(), Global_Parameters::Finite, and Global_Parameters::periodic_traction().
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT >
void PeriodicLoadProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update after solve is empty.
Definition at line 104 of file periodic_load.cc.
actions_before_newton_solve()
template<class ELEMENT >
void PeriodicLoadProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update before solve is empty.
Definition at line 101 of file periodic_load.cc.
assign_traction_elements()
template<class ELEMENT >
void PeriodicLoadProblem< ELEMENT >::assign_traction_elements [private]
Allocate traction elements on the top surface.
Make traction elements along the top boundary of the bulk mesh.
Definition at line 221 of file periodic_load.cc.
doc_solution()
template<class ELEMENT >
void PeriodicLoadProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 247 of file periodic_load.cc.
References Global_Parameters::exact_solution().
Referenced by main().
Member Data Documentation
Bulk_mesh_pt
template<class ELEMENT >
Mesh* PeriodicLoadProblem< ELEMENT >::Bulk_mesh_pt [private]
Pointer to the bulk mesh.
Definition at line 115 of file periodic_load.cc.
Surface_mesh_pt
template<class ELEMENT >
Mesh* PeriodicLoadProblem< ELEMENT >::Surface_mesh_pt [private]
Pointer to the mesh of traction elements.
Definition at line 118 of file periodic_load.cc.
The documentation for this class was generated from the following file:
periodic_load.cc