FlowPastBoxProblem< ELEMENT > Class Template Reference
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Public Member Functions
FlowPastBoxProblem (const string &node_file_name, const string &element_file_name, const string &poly_file_name)
Constructor: Pass filenames for mesh.
~FlowPastBoxProblem ()
Destructor (empty)
void actions_after_newton_solve ()
Update the after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve. Re-set velocity boundary conditions just to be on the safe side...
void actions_after_adapt ()
RefineableTriangleMesh< ELEMENT > * mesh_pt ()
Access function for the specific mesh.
TriangleMesh< ELEMENT > * mesh_pt ()
Access function for the specific mesh.
void doc_solution (DocInfo &doc_info)
Doc the solution.
Private Attributes
RefineableTriangleMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the bulk mesh.
Z2ErrorEstimator * error_estimator_pt
Error estimator.
Detailed Description
template<class ELEMENT>
class FlowPastBoxProblem< ELEMENT >
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Flow past a box in a channel
Definition at line 62 of file mesh_from_triangle_navier_stokes.cc.
Constructor & Destructor Documentation
FlowPastBoxProblem()
template<class ELEMENT >
FlowPastBoxProblem< ELEMENT >::FlowPastBoxProblem (const string & node_file_name, const string & element_file_name, const string & poly_file_name)
Constructor: Pass filenames for mesh.
Constructor for FlowPastBox problem. Pass filenames for mesh.
Definition at line 164 of file mesh_from_triangle_navier_stokes.cc.
References Global_Physical_Variables::Re.
 FlowPastBoxProblem()
template<class ELEMENT >
FlowPastBoxProblem< ELEMENT >::~FlowPastBoxProblem () [inline]
Destructor (empty)
Definition at line 74 of file mesh_from_triangle_navier_stokes.cc.
Member Function Documentation
actions_after_adapt()
template<class ELEMENT >
void FlowPastBoxProblem< ELEMENT >::actions_after_adapt
Definition at line 239 of file mesh_from_triangle_navier_stokes.cc.
References Global_Physical_Variables::Re.
actions_after_newton_solve()
template<class ELEMENT >
void FlowPastBoxProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the after solve (empty)
Definition at line 77 of file mesh_from_triangle_navier_stokes.cc.
actions_before_newton_solve()
template<class ELEMENT >
void FlowPastBoxProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve. Re-set velocity boundary conditions just to be on the safe side...
Definition at line 81 of file mesh_from_triangle_navier_stokes.cc.
References FlowPastBoxProblem< ELEMENT >::mesh_pt().
doc_solution()
template<class ELEMENT >
void FlowPastBoxProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 293 of file mesh_from_triangle_navier_stokes.cc.
Referenced by main().
mesh_pt() [1/2]
template<class ELEMENT >
RefineableTriangleMesh< ELEMENT > * FlowPastBoxProblem< ELEMENT >::mesh_pt () [inline]
Access function for the specific mesh.
Definition at line 132 of file mesh_from_triangle_navier_stokes.cc.
Referenced by FlowPastBoxProblem< ELEMENT >::actions_before_newton_solve(), and main().
mesh_pt() [2/2]
template<class ELEMENT >
TriangleMesh< ELEMENT > * FlowPastBoxProblem< ELEMENT >::mesh_pt () [inline]
Access function for the specific mesh.
Definition at line 138 of file mesh_from_triangle_navier_stokes.cc.
Member Data Documentation
Bulk_mesh_pt
template<class ELEMENT >
RefineableTriangleMesh<ELEMENT>* FlowPastBoxProblem< ELEMENT >::Bulk_mesh_pt [private]
Pointer to the bulk mesh.
Definition at line 150 of file mesh_from_triangle_navier_stokes.cc.
error_estimator_pt
template<class ELEMENT >
Z2ErrorEstimator* FlowPastBoxProblem< ELEMENT >::error_estimator_pt [private]
Error estimator.
Definition at line 153 of file mesh_from_triangle_navier_stokes.cc.
The documentation for this class was generated from the following file:
mesh_from_triangle_navier_stokes.cc