oomph::AxisymmetricVolumeConstraintBoundingElement Class Reference
Axisymmetric (one-dimensional) interface elements that allow the application of a volume constraint on the region bounded by these elements. The volume is computed by integrating x.n around the boundary of the domain and then dividing by three. The sign is chosen so that the volume will be positive when the elements surround a fluid domain.
#include <constrained_volume_elements.h>
Public Member Functions
AxisymmetricVolumeConstraintBoundingElement ()
Empty Contructor.
~AxisymmetricVolumeConstraintBoundingElement ()
Empty Destructor.
double contribution_to_enclosed_volume ()
Return this element's contribution to the total volume enclosed.
double contribution_to_volume_flux ()
Return this element's contribution to the volume flux over the boundary.
Public Member Functions inherited from oomph::VolumeConstraintBoundingElement
VolumeConstraintBoundingElement ()
Constructor initialise the boolean flag We expect the traded pressure data to be stored externally.
~VolumeConstraintBoundingElement ()
Empty Destructor.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in contribution to residuals and Jacobian.
void set_volume_constraint_element (VolumeConstraintElement *const &vol_constraint_el_pt, const bool &check_nodal_data=true)
Set the "master" volume constraint element The setup here is a bit more complicated than one might expect because if an internal pressure on a boundary is hijacked in TaylorHood elements then that the "traded" value may already be stored as nodal data in this element. This causes no problems apart from when running with PARANOID in which case the resulting repeated local equation numbers are spotted and an error is thrown. The check is a finite amount of work and so can be avoided if the boolean flag check_nodal_data is set to false.
Protected Member Functions
void fill_in_generic_residual_contribution_volume_constraint (Vector< double > &residuals)
Helper function to fill in contributions to residuals (remember that part of the residual is added by the the associated VolumeConstraintElement). This is specific for 1D line elements that bound 2D cartesian fluid elements.
Protected Member Functions inherited from oomph::VolumeConstraintBoundingElement
int ptraded_local_eqn ()
The local eqn number for the traded pressure.
Additional Inherited Members
Protected Attributes inherited from oomph::VolumeConstraintBoundingElement
unsigned Data_number_of_traded_pressure
The Data that contains the traded pressure is usually stored as external Data for this element, but may also be nodal Data Which Data item is it?
unsigned Index_of_traded_pressure_value
Index of the value in traded pressure data that corresponds to the traded pressure.
bool Traded_pressure_stored_at_node
Boolean to indicate whether the traded pressure is stored externally or at a node (this can happen in Taylor-Hood elements)
Detailed Description
Axisymmetric (one-dimensional) interface elements that allow the application of a volume constraint on the region bounded by these elements. The volume is computed by integrating x.n around the boundary of the domain and then dividing by three. The sign is chosen so that the volume will be positive when the elements surround a fluid domain.
These elements must be used together with the associated VolumeConstraintElement, which stores the value of the target volume.
Definition at line 481 of file constrained_volume_elements.h.
Constructor & Destructor Documentation
AxisymmetricVolumeConstraintBoundingElement()
oomph::AxisymmetricVolumeConstraintBoundingElement::AxisymmetricVolumeConstraintBoundingElement () [inline]
Empty Contructor.
Definition at line 494 of file constrained_volume_elements.h.
~AxisymmetricVolumeConstraintBoundingElement()
oomph::AxisymmetricVolumeConstraintBoundingElement::~AxisymmetricVolumeConstraintBoundingElement () [inline]
Empty Destructor.
Definition at line 500 of file constrained_volume_elements.h.
Member Function Documentation
contribution_to_enclosed_volume()
double oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_enclosed_volume ()
Return this element's contribution to the total volume enclosed.
Definition at line 266 of file constrained_volume_elements.cc.
contribution_to_volume_flux()
double oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_volume_flux () [inline]
Return this element's contribution to the volume flux over the boundary.
Definition at line 507 of file constrained_volume_elements.h.
fill_in_generic_residual_contribution_volume_constraint()
void oomph::AxisymmetricVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint (Vector< double > & residuals) [protected], [virtual]
Helper function to fill in contributions to residuals (remember that part of the residual is added by the the associated VolumeConstraintElement). This is specific for 1D line elements that bound 2D cartesian fluid elements.
Helper function to fill in contributions to residuals (remember that part of the residual is added by the the associated VolumeConstraintElement). This is specific for axisymmetric line elements that bound 2D axisymmetric fluid elements. The only difference from the 1D case is the addition of the weighting factor in the integrand and division of the dot product by three.
Implements oomph::VolumeConstraintBoundingElement.
Definition at line 351 of file constrained_volume_elements.cc.
References oomph::VolumeConstraintBoundingElement::ptraded_local_eqn().
Referenced by oomph::ElasticAxisymmetricVolumeConstraintBoundingElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::SpineAxisymmetricVolumeConstraintBoundingElement< ELEMENT >::fill_in_contribution_to_jacobian().
The documentation for this class was generated from the following files:
constrained_volume_elements.h
constrained_volume_elements.cc