rayleigh_instability_surfactant.txt File Reference
Functions
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi multi physics problem because there is a coupling between the equations on the surface and those in the bulk The coupling from the bulk to the surface transport arises through the surface velocity in the surface transport equation The coupling from the surface transport to bulk arises in a more subtle manner because the surface concentration affects the surface tension In this we describe how to use the existing framework to create surface transport equations and how to include them in a free surface problem< HR >< HR > section example_problem The example problem The problem to be solved is the evolution of an annular film of fluid on the inside of a solid cylinder in the presence of an insoluble surfactant on the we reproduce some of the results given in A D model of Rayleigh instability in capillary tubes surfactant effects by D J Di Paolo &F A< em > Int J Multiphase</em > vol< b ></b > Our is different from their approach as described in detail in our< a href=`../../../navier_stokes/surface_theory/html/index.html`> free surface theory document</a >< CENTER >< TABLE >< TR >< TD >< CENTER >< B > The unsteady axisymmetric free surface Navier Stokes equations with insoluble surfactant</B ></CENTER > Solve f[Re \left[St \frac{\partial u_r}{\partial t}+u_r \frac{\partial u_r}{\partial r} - \frac{u_\theta^2}{r}+u_z \frac{\partial u_r}{\partial z}\right]=-\frac{\partial p}{\partial r}+\left[\frac{\partial^2 u_r}{\partial r^2}+\frac{1}{r}\frac{\partial u_r}{\partial r} - \frac{u_r}{r^2}+\frac{\partial^2 u_r}{\partial z^2}\right],\f] f[Re \left[St \frac{\partial u_\theta}{\partial t}+u_r \frac{\partial u_\theta}{\partial r}+\frac{u_r u_\theta}{r}+u_z \frac{\partial u_\theta}{\partial z}\right]=+\left[\frac{\partial^2 u_\theta}{\partial r^2}+\frac{1}{r}\frac{\partial u_\theta}{\partial r} - \frac{u_\theta}{r^2}+\frac{\partial^2 u_\theta}{\partial z^2}\right],\f] f[Re \left[St \frac{\partial u_z}{\partial t}+u_r \frac{\partial u_z}{\partial r}+u_z \frac{\partial u_z}{\partial z}\right]=-\frac{\partial p}{\partial z}+\left[\frac{\partial^2 u_z}{\partial r^2}+\frac{1}{r}\frac{\partial u_z}{\partial r}+\frac{\partial^2 u_z}{\partial z^2}\right],\f] and f[\frac{\partial u_r}{\partial r}+\frac{u_r}{r}+\frac{\partial u_z}{\partial z}=0\ \ \ \ \ \ \ \ \ \ @E[eqn:NSlower]@\f] in the bulk fluid The governing equations are subject to the no slip boundary conditions f[u_r=u_\theta=u_z=0 \ \ \ \ \ \ \ \ \ \ @E[eqn:BC1]@\f] on the outer solid boundary (\f$ r=1.0 \f$) and the symmetry boundary conditions \f[u_z
Variables
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi domain
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi multi physics problem because there is a coupling between the equations on the surface and those in the bulk The coupling from the bulk to the surface transport arises through the surface velocity in the surface transport equation The coupling from the surface transport to bulk arises in a more subtle manner because the surface concentration affects the surface tension In this tutorial
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi multi physics problem because there is a coupling between the equations on the surface and those in the bulk The coupling from the bulk to the surface transport arises through the surface velocity in the surface transport equation The coupling from the surface transport to bulk arises in a more subtle manner because the surface concentration affects the surface tension In this we describe how to use the existing framework to create surface transport equations and how to include them in a free surface problem< HR >< HR > section example_problem The example problem The problem to be solved is the evolution of an annular film of fluid on the inside of a solid cylinder in the presence of an insoluble surfactant on the interface
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi multi physics problem because there is a coupling between the equations on the surface and those in the bulk The coupling from the bulk to the surface transport arises through the surface velocity in the surface transport equation The coupling from the surface transport to bulk arises in a more subtle manner because the surface concentration affects the surface tension In this we describe how to use the existing framework to create surface transport equations and how to include them in a free surface problem< HR >< HR > section example_problem The example problem The problem to be solved is the evolution of an annular film of fluid on the inside of a solid cylinder in the presence of an insoluble surfactant on the we reproduce some of the results given in A D model of Rayleigh instability in capillary tubes surfactant effects by D Campana
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi multi physics problem because there is a coupling between the equations on the surface and those in the bulk The coupling from the bulk to the surface transport arises through the surface velocity in the surface transport equation The coupling from the surface transport to bulk arises in a more subtle manner because the surface concentration affects the surface tension In this we describe how to use the existing framework to create surface transport equations and how to include them in a free surface problem< HR >< HR > section example_problem The example problem The problem to be solved is the evolution of an annular film of fluid on the inside of a solid cylinder in the presence of an insoluble surfactant on the we reproduce some of the results given in A D model of Rayleigh instability in capillary tubes surfactant effects by D J Di Paolo &F A Saita
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi multi physics problem because there is a coupling between the equations on the surface and those in the bulk The coupling from the bulk to the surface transport arises through the surface velocity in the surface transport equation The coupling from the surface transport to bulk arises in a more subtle manner because the surface concentration affects the surface tension In this we describe how to use the existing framework to create surface transport equations and how to include them in a free surface problem< HR >< HR > section example_problem The example problem The problem to be solved is the evolution of an annular film of fluid on the inside of a solid cylinder in the presence of an insoluble surfactant on the we reproduce some of the results given in A D model of Rayleigh instability in capillary tubes surfactant effects by D J Di Paolo &F A< em > Int J Multiphase Flow
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi multi physics problem because there is a coupling between the equations on the surface and those in the bulk The coupling from the bulk to the surface transport arises through the surface velocity in the surface transport equation The coupling from the surface transport to bulk arises in a more subtle manner because the surface concentration affects the surface tension In this we describe how to use the existing framework to create surface transport equations and how to include them in a free surface problem< HR >< HR > section example_problem The example problem The problem to be solved is the evolution of an annular film of fluid on the inside of a solid cylinder in the presence of an insoluble surfactant on the we reproduce some of the results given in A D model of Rayleigh instability in capillary tubes surfactant effects by D J Di Paolo &F A< em > Int J Multiphase</em > vol< b ></b > pp
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi multi physics problem because there is a coupling between the equations on the surface and those in the bulk The coupling from the bulk to the surface transport arises through the surface velocity in the surface transport equation The coupling from the surface transport to bulk arises in a more subtle manner because the surface concentration affects the surface tension In this we describe how to use the existing framework to create surface transport equations and how to include them in a free surface problem< HR >< HR > section example_problem The example problem The problem to be solved is the evolution of an annular film of fluid on the inside of a solid cylinder in the presence of an insoluble surfactant on the we reproduce some of the results given in A D model of Rayleigh instability in capillary tubes surfactant effects by D J Di Paolo &F A< em > Int J Multiphase</em > vol< b ></b > Our formulation
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi multi physics problem because there is a coupling between the equations on the surface and those in the bulk The coupling from the bulk to the surface transport arises through the surface velocity in the surface transport equation The coupling from the surface transport to bulk arises in a more subtle manner because the surface concentration affects the surface tension In this we describe how to use the existing framework to create surface transport equations and how to include them in a free surface problem< HR >< HR > section example_problem The example problem The problem to be solved is the evolution of an annular film of fluid on the inside of a solid cylinder in the presence of an insoluble surfactant on the we reproduce some of the results given in A D model of Rayleigh instability in capillary tubes surfactant effects by D J Di Paolo &F A< em > Int J Multiphase</em > vol< b ></b > Our however
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi multi physics problem because there is a coupling between the equations on the surface and those in the bulk The coupling from the bulk to the surface transport arises through the surface velocity in the surface transport equation The coupling from the surface transport to bulk arises in a more subtle manner because the surface concentration affects the surface tension In this we describe how to use the existing framework to create surface transport equations and how to include them in a free surface problem< HR >< HR > section example_problem The example problem The problem to be solved is the evolution of an annular film of fluid on the inside of a solid cylinder in the presence of an insoluble surfactant on the we reproduce some of the results given in A D model of Rayleigh instability in capillary tubes surfactant effects by D J Di Paolo &F A< em > Int J Multiphase</em > vol< b ></b > Our is different from their approach as described in detail in our< a href=`../../../navier_stokes/surface_theory/html/index.html`> free surface theory document</a >< CENTER >< TABLE >< TR >< TD >< CENTER >< B > The unsteady axisymmetric free surface Navier Stokes equations with insoluble surfactant</B ></CENTER > Solve f[Re \left[St \frac{\partial u_r}{\partial t}+u_r \frac{\partial u_r}{\partial r} - \frac{u_\theta^2}{r}+u_z \frac{\partial u_r}{\partial z}\right]=-\frac{\partial p}{\partial r}+\left[\frac{\partial^2 u_r}{\partial r^2}+\frac{1}{r}\frac{\partial u_r}{\partial r} - \frac{u_r}{r^2}+\frac{\partial^2 u_r}{\partial z^2}\right],\f] f[Re \left[St \frac{\partial u_\theta}{\partial t}+u_r \frac{\partial u_\theta}{\partial r}+\frac{u_r u_\theta}{r}+u_z \frac{\partial u_\theta}{\partial z}\right]=+\left[\frac{\partial^2 u_\theta}{\partial r^2}+\frac{1}{r}\frac{\partial u_\theta}{\partial r} - \frac{u_\theta}{r^2}+\frac{\partial^2 u_\theta}{\partial z^2}\right],\f] f[Re \left[St \frac{\partial u_z}{\partial t}+u_r \frac{\partial u_z}{\partial r}+u_z \frac{\partial u_z}{\partial z}\right]=-\frac{\partial p}{\partial z}+\left[\frac{\partial^2 u_z}{\partial r^2}+\frac{1}{r}\frac{\partial u_z}{\partial r}+\frac{\partial^2 u_z}{\partial z^2}\right],\f] and f[\frac{\partial u_r}{\partial r}+\frac{u_r}{r}+\frac{\partial u_z}{\partial z}=0\ \ \ \ \ \ \ \ \ \ @E[eqn:NSlower]@\f] in the bulk fluid The governing equations are subject to the no slip boundary conditions f[u_r=u_\theta=u_z=0 \ \ \ \ \ \ \ \ \ \ @E[eqn:BC1]@\f] on the outer solid E[eqn:kinematicBC] f and the dynamic condition f[\tau_{ij}^{[2]}n_j=\tau_{ij}^{[1]}n_j+\frac{1}{Ca}\left(\sigma \kappa n_i+\frac{\partial \sigma}{\partial s} t_{i} \right).\ \ \ \ \ \ \ \ \ \ @E[eqn:dynamicBC]@\f] where f sigma
Function Documentation
boundary()
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi multi physics problem because there is a coupling between the equations on the surface and those in the bulk The coupling from the bulk to the surface transport arises through the surface velocity in the surface transport equation The coupling from the surface transport to bulk arises in a more subtle manner because the surface concentration affects the surface tension In this we describe how to use the existing framework to create surface transport equations and how to include them in a free surface problem<HR><HR> section example_problem The example problem The problem to be solved is the evolution of an annular film of fluid on the inside of a solid cylinder in the presence of an insoluble surfactant on the we reproduce some of the results given in A D model of Rayleigh instability in capillary tubes surfactant effects by D J Di Paolo& F A<em> Int J Multiphase</em> vol<b></b> Our is different from their approach as described in detail in our<a href=`../../../navier_stokes/surface_theory/html/index.html`> free surface theory document</a><CENTER><TABLE><TR><TD><CENTER><B> The unsteady axisymmetric free surface Navier Stokes equations with insoluble surfactant</B></CENTER> Solve f [Re \left[ St \frac{\partial u_r}{\partial t} + u_r \frac{\partial u_r}{\partial r} - \frac{u_\theta^2}{r} + u_z \frac{\partial u_r}{\partial z}\right] = -\frac{\partial p}{\partial r}+ \left[ \frac{\partial^2 u_r}{\partial r^2} + \frac{1}{r}\frac{\partial u_r}{\partial r} - \frac{u_r}{r^2} + \frac{\partial^2 u_r}{\partial z^2}\right],\f] f [Re \left[ St \frac{\partial u_\theta}{\partial t} + u_r \frac{\partial u_\theta}{\partial r} + \frac{u_r u_\theta}{r} + u_z \frac{\partial u_\theta}{\partial z}\right]= + \left[ \frac{\partial^2 u_\theta}{\partial r^2} + \frac{1}{r}\frac{\partial u_\theta}{\partial r} - \frac{u_\theta}{r^2} + \frac{\partial^2 u_\theta}{\partial z^2}\right],\f] f [Re \left[ St \frac{\partial u_z}{\partial t} + u_r \frac{\partial u_z}{\partial r} + u_z \frac{\partial u_z}{\partial z}\right] = -\frac{\partial p}{\partial z}+ \left[ \frac{\partial^2 u_z}{\partial r^2} + \frac{1}{r}\frac{\partial u_z}{\partial r} + \frac{\partial^2 u_z}{\partial z^2}\right],\f] and f [\frac{\partial u_r}{\partial r}+ \frac{u_r}{r}+ \frac{\partial u_z}{\partial z} = 0\ \ \ \ \ \ \ \ \ \ @E[eqn:NSlower]@\f] in the bulk fluid The governing equations are subject to the no slip boundary conditions f [u_r = u_\theta = u_z = 0 \ \ \ \ \ \ \ \ \ \ @E[eqn:BC1]@\f] on the outer solid boundary (\f$ r = 1.0 \f$)
Variable Documentation
Campana
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi multi physics problem because there is a coupling between the equations on the surface and those in the bulk The coupling from the bulk to the surface transport arises through the surface velocity in the surface transport equation The coupling from the surface transport to bulk arises in a more subtle manner because the surface concentration affects the surface tension In this we describe how to use the existing framework to create surface transport equations and how to include them in a free surface problem<HR><HR> section example_problem The example problem The problem to be solved is the evolution of an annular film of fluid on the inside of a solid cylinder in the presence of an insoluble surfactant on the we reproduce some of the results given in A D model of Rayleigh instability in capillary tubes surfactant effects by D Campana
Definition at line 24 of file rayleigh_instability_surfactant.txt.
domain
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi domain
Definition at line 4 of file rayleigh_instability_surfactant.txt.
Flow
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi multi physics problem because there is a coupling between the equations on the surface and those in the bulk The coupling from the bulk to the surface transport arises through the surface velocity in the surface transport equation The coupling from the surface transport to bulk arises in a more subtle manner because the surface concentration affects the surface tension In this we describe how to use the existing framework to create surface transport equations and how to include them in a free surface problem<HR><HR> section example_problem The example problem The problem to be solved is the evolution of an annular film of fluid on the inside of a solid cylinder in the presence of an insoluble surfactant on the we reproduce some of the results given in A D model of Rayleigh instability in capillary tubes surfactant effects by D J Di Paolo& F A<em> Int J Multiphase Flow
Definition at line 24 of file rayleigh_instability_surfactant.txt.
formulation
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi multi physics problem because there is a coupling between the equations on the surface and those in the bulk The coupling from the bulk to the surface transport arises through the surface velocity in the surface transport equation The coupling from the surface transport to bulk arises in a more subtle manner because the surface concentration affects the surface tension In this we describe how to use the existing framework to create surface transport equations and how to include them in a free surface problem<HR><HR> section example_problem The example problem The problem to be solved is the evolution of an annular film of fluid on the inside of a solid cylinder in the presence of an insoluble surfactant on the we reproduce some of the results given in A D model of Rayleigh instability in capillary tubes surfactant effects by D J Di Paolo& F A<em> Int J Multiphase</em> vol<b></b> Our formulation
Definition at line 25 of file rayleigh_instability_surfactant.txt.
however
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi multi physics problem because there is a coupling between the equations on the surface and those in the bulk The coupling from the bulk to the surface transport arises through the surface velocity in the surface transport equation The coupling from the surface transport to bulk arises in a more subtle manner because the surface concentration affects the surface tension In this we describe how to use the existing framework to create surface transport equations and how to include them in a free surface problem<HR><HR> section example_problem The example problem The problem to be solved is the evolution of an annular film of fluid on the inside of a solid cylinder in the presence of an insoluble surfactant on the we reproduce some of the results given in A D model of Rayleigh instability in capillary tubes surfactant effects by D J Di Paolo& F A<em> Int J Multiphase</em> vol<b></b> Our however
Definition at line 25 of file rayleigh_instability_surfactant.txt.
interface
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi multi physics problem because there is a coupling between the equations on the surface and those in the bulk The coupling from the bulk to the surface transport arises through the surface velocity in the surface transport equation The coupling from the surface transport to bulk arises in a more subtle manner because the surface concentration affects the surface tension In this we describe how to use the existing framework to create surface transport equations and how to include them in a free surface problem<HR><HR> section example_problem The example problem The problem to be solved is the evolution of an annular film of fluid on the inside of a solid cylinder in the presence of an insoluble surfactant on the interface
Definition at line 22 of file rayleigh_instability_surfactant.txt.
pp
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi multi physics problem because there is a coupling between the equations on the surface and those in the bulk The coupling from the bulk to the surface transport arises through the surface velocity in the surface transport equation The coupling from the surface transport to bulk arises in a more subtle manner because the surface concentration affects the surface tension In this we describe how to use the existing framework to create surface transport equations and how to include them in a free surface problem<HR><HR> section example_problem The example problem The problem to be solved is the evolution of an annular film of fluid on the inside of a solid cylinder in the presence of an insoluble surfactant on the we reproduce some of the results given in A D model of Rayleigh instability in capillary tubes surfactant effects by D J Di Paolo& F A<em> Int J Multiphase</em> vol<b></b> pp
Definition at line 25 of file rayleigh_instability_surfactant.txt.
Saita
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi multi physics problem because there is a coupling between the equations on the surface and those in the bulk The coupling from the bulk to the surface transport arises through the surface velocity in the surface transport equation The coupling from the surface transport to bulk arises in a more subtle manner because the surface concentration affects the surface tension In this we describe how to use the existing framework to create surface transport equations and how to include them in a free surface problem<HR><HR> section example_problem The example problem The problem to be solved is the evolution of an annular film of fluid on the inside of a solid cylinder in the presence of an insoluble surfactant on the we reproduce some of the results given in A D model of Rayleigh instability in capillary tubes surfactant effects by D J Di Paolo& F A Saita
Definition at line 24 of file rayleigh_instability_surfactant.txt.
sigma
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi multi physics problem because there is a coupling between the equations on the surface and those in the bulk The coupling from the bulk to the surface transport arises through the surface velocity in the surface transport equation The coupling from the surface transport to bulk arises in a more subtle manner because the surface concentration affects the surface tension In this we describe how to use the existing framework to create surface transport equations and how to include them in a free surface problem<HR><HR> section example_problem The example problem The problem to be solved is the evolution of an annular film of fluid on the inside of a solid cylinder in the presence of an insoluble surfactant on the we reproduce some of the results given in A D model of Rayleigh instability in capillary tubes surfactant effects by D J Di Paolo& F A<em> Int J Multiphase</em> vol<b></b> Our is different from their approach as described in detail in our<a href=`../../../navier_stokes/surface_theory/html/index.html`> free surface theory document</a><CENTER><TABLE><TR><TD><CENTER><B> The unsteady axisymmetric free surface Navier Stokes equations with insoluble surfactant</B></CENTER> Solve f [Re \left[ St \frac{\partial u_r}{\partial t} + u_r \frac{\partial u_r}{\partial r} - \frac{u_\theta^2}{r} + u_z \frac{\partial u_r}{\partial z}\right] = -\frac{\partial p}{\partial r}+ \left[ \frac{\partial^2 u_r}{\partial r^2} + \frac{1}{r}\frac{\partial u_r}{\partial r} - \frac{u_r}{r^2} + \frac{\partial^2 u_r}{\partial z^2}\right],\f] f [Re \left[ St \frac{\partial u_\theta}{\partial t} + u_r \frac{\partial u_\theta}{\partial r} + \frac{u_r u_\theta}{r} + u_z \frac{\partial u_\theta}{\partial z}\right]= + \left[ \frac{\partial^2 u_\theta}{\partial r^2} + \frac{1}{r}\frac{\partial u_\theta}{\partial r} - \frac{u_\theta}{r^2} + \frac{\partial^2 u_\theta}{\partial z^2}\right],\f] f [Re \left[ St \frac{\partial u_z}{\partial t} + u_r \frac{\partial u_z}{\partial r} + u_z \frac{\partial u_z}{\partial z}\right] = -\frac{\partial p}{\partial z}+ \left[ \frac{\partial^2 u_z}{\partial r^2} + \frac{1}{r}\frac{\partial u_z}{\partial r} + \frac{\partial^2 u_z}{\partial z^2}\right],\f] and f [\frac{\partial u_r}{\partial r}+ \frac{u_r}{r}+ \frac{\partial u_z}{\partial z} = 0\ \ \ \ \ \ \ \ \ \ @E[eqn:NSlower]@\f] in the bulk fluid The governing equations are subject to the no slip boundary conditions f [u_r = u_\theta = u_z = 0 \ \ \ \ \ \ \ \ \ \ @E[eqn:BC1]@\f] on the outer solid E [eqn:kinematicBC] f and the dynamic condition f [\tau_{ij}^{[2]}n_j = \tau_{ij}^{[1]}n_j+\frac{1}{Ca}\left (\sigma \kappa n_i+ \frac{\partial \sigma}{\partial s} t_{i} \right).\ \ \ \ \ \ \ \ \ \ @E[eqn:dynamicBC]@\f] where f sigma
Initial value:
= \sigma^{*} / \sigma_{ref} \f$ is the dimensionless
surface tension relative to a reference value.
An insoluble surfactant of surface concentration \f$ \Gamma^{*}\f$ is
 non-dimensionalised with respect to a reference value \f$ \Gamma =
 \Gamma^{*}/\Gamma_{ref} \f$ and obeys the surface transport equation
 \f[ St \left(\frac{\partial \Gamma}{\partial t} -
   \dot{\mbox{\boldmath$R$}} \mbox{\boldmath$\cdot$}
   \mbox{\boldmath$\nabla$}_{\!\!_{S}} \Gamma \right) +
   \mbox{\boldmath$\nabla$}_{\!\!_{S}} \mbox{\boldmath$\cdot$}
   \left(\Gamma \mbox{\boldmath$U$}\right) =
   \frac{1}{Pe_{s}}
 \mbox{\boldmath$\nabla$}_{\!\!_{S}}\mbox{\boldmath$\cdot$}
 \mbox{\boldmath$\nabla$}_{\!\!_{S}}
   \Gamma \f]
on the interface.
The surface tension is a function of the surfactant concentration \f$
\sigma(\Gamma)\f$ and a linear equation of state is chosen
\f[ \sigma = 1 - \beta (\Gamma - 1).
 \f]
The symmetry boundary conditions on the bottom (\f$ z = 0.0 \f$) and
top (\f$ z = \pi / \alpha \f$) boundaries are
 \f[ \frac{\partial \Gamma}{\partial z} = 0. \f]
Initially
Definition at line 114 of file rayleigh_instability_surfactant.txt.
Referenced by oomph::PointFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement< ELEMENT >::output(), and oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::output().
tutorial
mainpage The Rayleigh Plateau instability in the presence of an insoluble surfactant In this tutorial we present an example of surface transport equations in a free surface Navier Stokes problem This is a multi multi physics problem because there is a coupling between the equations on the surface and those in the bulk The coupling from the bulk to the surface transport arises through the surface velocity in the surface transport equation The coupling from the surface transport to bulk arises in a more subtle manner because the surface concentration affects the surface tension In this tutorial
Definition at line 10 of file rayleigh_instability_surfactant.txt.