#!MC 1000
$!EXPORTSETUP IMAGEWIDTH = 798
$!EXPORTSETUP EXPORTFNAME = 'rotate.avi'
$!EXPORTSTART 
  EXPORTREGION = CURRENTFRAME

$!VARSET |nstep|=24
$!VARSET |dtheta|=360
$!VARSET |dtheta|/=|nstep|
$!VARSET |nstep|-=1

$!LOOP |nstep|

$!ROTATE3DVIEW THETA
  ANGLE = |dtheta|
  ROTATEORIGINLOCATION = DEFINEDORIGIN
$!EXPORTNEXTFRAME 

$!ENDLOOP

$!EXPORTFINISH 

