StaticDiskCompressionProblem< ELEMENT > Class Template Reference
Uniform compression of a circular disk in a state of plane strain, subject to uniform growth.
Public Member Functions
StaticDiskCompressionProblem ()
Constructor:
void parameter_study (const unsigned &case_number)
Run simulation: Pass case number to label output files.
void doc_solution (DocInfo &doc_info)
Doc the solution.
void actions_after_newton_solve ()
Update function (empty)
void actions_before_newton_solve ()
Update function (empty)
Private Attributes
ofstream Trace_file
Trace file.
Vector< Node * > Trace_node_pt
Vector of pointers to nodes whose position we're tracing.
ElasticRefineableQuarterCircleSectorMesh< ELEMENT > * Solid_mesh_pt
Pointer to solid mesh.
SolidMesh * Traction_mesh_pt
Pointer to mesh of traction elements.
Detailed Description
template<class ELEMENT>
class StaticDiskCompressionProblem< ELEMENT >
Uniform compression of a circular disk in a state of plane strain, subject to uniform growth.
Definition at line 170 of file disk_compression.cc.
Constructor & Destructor Documentation
StaticDiskCompressionProblem()
template<class ELEMENT >
StaticDiskCompressionProblem< ELEMENT >::StaticDiskCompressionProblem
Constructor:
Definition at line 210 of file disk_compression.cc.
References Global_Physical_Variables::constant_pressure(), Global_Physical_Variables::Constitutive_law_pt, and Global_Physical_Variables::growth_function().
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT >
void StaticDiskCompressionProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update function (empty)
Definition at line 185 of file disk_compression.cc.
actions_before_newton_solve()
template<class ELEMENT >
void StaticDiskCompressionProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update function (empty)
Definition at line 188 of file disk_compression.cc.
doc_solution()
template<class ELEMENT >
void StaticDiskCompressionProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 303 of file disk_compression.cc.
References Global_Physical_Variables::E, Global_Physical_Variables::Nu, Global_Physical_Variables::P, and Global_Physical_Variables::Uniform_gamma.
parameter_study()
template<class ELEMENT >
void StaticDiskCompressionProblem< ELEMENT >::parameter_study (const unsigned & case_number)
Run simulation: Pass case number to label output files.
Run the paramter study.
Definition at line 356 of file disk_compression.cc.
References Global_Physical_Variables::P.
Referenced by main().
Member Data Documentation
Solid_mesh_pt
template<class ELEMENT >
ElasticRefineableQuarterCircleSectorMesh<ELEMENT>* StaticDiskCompressionProblem< ELEMENT >::Solid_mesh_pt [private]
Pointer to solid mesh.
Definition at line 199 of file disk_compression.cc.
Trace_file
template<class ELEMENT >
ofstream StaticDiskCompressionProblem< ELEMENT >::Trace_file [private]
Trace file.
Definition at line 193 of file disk_compression.cc.
Trace_node_pt
template<class ELEMENT >
Vector<Node*> StaticDiskCompressionProblem< ELEMENT >::Trace_node_pt [private]
Vector of pointers to nodes whose position we're tracing.
Definition at line 196 of file disk_compression.cc.
Traction_mesh_pt
template<class ELEMENT >
SolidMesh* StaticDiskCompressionProblem< ELEMENT >::Traction_mesh_pt [private]
Pointer to mesh of traction elements.
Definition at line 202 of file disk_compression.cc.
The documentation for this class was generated from the following file:
disk_compression.cc