ElasticRefineableQuarterCircleSectorMesh< ELEMENT > Class Template Reference
Elastic quarter circle sector mesh with functionality to attach traction elements to the curved surface. We "upgrade" the RefineableQuarterCircleSectorMesh to become an SolidMesh and equate the Eulerian and Lagrangian coordinates, thus making the domain represented by the mesh the stress-free configuration.
The member function make_traction_element_mesh() creates a separate mesh of SolidTractionElements that are attached to the mesh's curved boundary (boundary 1).
Public Member Functions
ElasticRefineableQuarterCircleSectorMesh (GeomObject *wall_pt, const double &xi_lo, const double &fract_mid, const double &xi_hi, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Build mesh and copy Eulerian coords to Lagrangian ones so that the initial configuration is the stress-free one.
void make_traction_element_mesh (SolidMesh *&traction_mesh_pt)
Function to create mesh made of traction elements.
Detailed Description
template<class ELEMENT>
class ElasticRefineableQuarterCircleSectorMesh< ELEMENT >
Elastic quarter circle sector mesh with functionality to attach traction elements to the curved surface. We "upgrade" the RefineableQuarterCircleSectorMesh to become an SolidMesh and equate the Eulerian and Lagrangian coordinates, thus making the domain represented by the mesh the stress-free configuration.
The member function make_traction_element_mesh() creates a separate mesh of SolidTractionElements that are attached to the mesh's curved boundary (boundary 1).
Definition at line 112 of file disk_compression.cc.
Constructor & Destructor Documentation
ElasticRefineableQuarterCircleSectorMesh()
template<class ELEMENT >
ElasticRefineableQuarterCircleSectorMesh< ELEMENT >::ElasticRefineableQuarterCircleSectorMesh (GeomObject * wall_pt, const double & xi_lo, const double & fract_mid, const double & xi_hi, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Build mesh and copy Eulerian coords to Lagrangian ones so that the initial configuration is the stress-free one.
Make the current configuration the undeformed one by setting the nodal Lagrangian coordinates to their current Eulerian ones
Definition at line 85 of file disk_compression.cc.
References Global_Physical_Variables::Uniform_gamma.
Referenced by main(), StaticDiskCompressionProblem< ELEMENT >::parameter_study(), and StaticDiskCompressionProblem< ELEMENT >::StaticDiskCompressionProblem().
Member Function Documentation
make_traction_element_mesh()
template<class ELEMENT >
void ElasticRefineableQuarterCircleSectorMesh< ELEMENT >::make_traction_element_mesh (SolidMesh *& traction_mesh_pt) [inline]
Function to create mesh made of traction elements.
Definition at line 139 of file disk_compression.cc.
Referenced by StaticDiskCompressionProblem< ELEMENT >::StaticDiskCompressionProblem().
The documentation for this class was generated from the following file:
disk_compression.cc