MyBiharmonicBellProblem< ELEMENT, DIM, NNODE_1D > Class Template Reference
2D Biharmonic problem.
Public Member Functions
MyBiharmonicBellProblem (typename MyBiharmonicEquations< DIM, NNODE_1D >::SourceFctPt source_fct_pt)
Constructor: Pass number of elements and pointer to source function.
~MyBiharmonicBellProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve: (Re)set boundary conditions.
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void doc_solution (DocInfo &doc_info)
Doc the solution, pass the number of the case considered, so that output files can be distinguished.
Private Attributes
MyBiharmonicEquations< DIM, NNODE_1D >::SourceFctPt Source_fct_pt
Pointer to source function.
Detailed Description
template<class ELEMENT, unsigned DIM, unsigned NNODE_1D>
class MyBiharmonicBellProblem< ELEMENT, DIM, NNODE_1D >
2D Biharmonic problem.
Definition at line 970 of file structured_2d_biharmonic_bellelement.cc.
Constructor & Destructor Documentation
MyBiharmonicBellProblem()
template<class ELEMENT , unsigned DIM, unsigned NNODE_1D>
MyBiharmonicBellProblem< ELEMENT, DIM, NNODE_1D >::MyBiharmonicBellProblem (typename MyBiharmonicEquations< DIM, NNODE_1D >::SourceFctPt source_fct_pt)
Constructor: Pass number of elements and pointer to source function.
Constructor for 2D Biharmonic problem. Discretise the 2D domain with n_element elements of type ELEMENT. Specify function pointer to source function.
Definition at line 1010 of file structured_2d_biharmonic_bellelement.cc.
References i, Physical_Variables::l_x, Physical_Variables::l_y, Physical_Variables::n_x, and Physical_Variables::n_y.
 MyBiharmonicBellProblem()
template<class ELEMENT , unsigned DIM, unsigned NNODE_1D>
MyBiharmonicBellProblem< ELEMENT, DIM, NNODE_1D >::~MyBiharmonicBellProblem () [inline]
Destructor (empty)
Definition at line 979 of file structured_2d_biharmonic_bellelement.cc.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT , unsigned DIM, unsigned NNODE_1D>
void MyBiharmonicBellProblem< ELEMENT, DIM, NNODE_1D >::actions_after_newton_solve () [inline]
Update the problem specs after solve (empty)
Definition at line 988 of file structured_2d_biharmonic_bellelement.cc.
actions_before_newton_solve()
template<class ELEMENT , unsigned DIM, unsigned NNODE_1D>
void MyBiharmonicBellProblem< ELEMENT, DIM, NNODE_1D >::actions_before_newton_solve
Update the problem specs before solve: (Re)set boundary conditions.
Update the problem specs before solve: (Re)set boundary values from the exact solution.
Definition at line 1065 of file structured_2d_biharmonic_bellelement.cc.
References Physical_Variables::get_exact_u(), i, and u.
doc_solution()
template<class ELEMENT , unsigned DIM, unsigned NNODE_1D>
void MyBiharmonicBellProblem< ELEMENT, DIM, NNODE_1D >::doc_solution (DocInfo & doc_info)
Doc the solution, pass the number of the case considered, so that output files can be distinguished.
Doc the solution in tecplot format. Label files with label.
Definition at line 1105 of file structured_2d_biharmonic_bellelement.cc.
References Physical_Variables::get_exact_u().
Referenced by main().
Member Data Documentation
Source_fct_pt
template<class ELEMENT , unsigned DIM, unsigned NNODE_1D>
MyBiharmonicEquations<DIM,NNODE_1D>::SourceFctPt MyBiharmonicBellProblem< ELEMENT, DIM, NNODE_1D >::Source_fct_pt [private]
Pointer to source function.
Definition at line 997 of file structured_2d_biharmonic_bellelement.cc.
The documentation for this class was generated from the following file:
structured_2d_biharmonic_bellelement.cc