Physical_Variables Namespace Reference
Namespace for the solution of 2D Biharmonic equation.
Functions
void get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void source_function (const Vector< double > &x, double &source)
Source function required to make the solution above an exact solution.
Variables
unsigned n_x = 4
number of elements in the x direction
unsigned n_y = 2
number of elements in the y direction
double l_x = 2.0
length in the x direction
double l_y = 1.0
length in the y direction
Detailed Description
Namespace for the solution of 2D Biharmonic equation.
Function Documentation
get_exact_u()
void Physical_Variables::get_exact_u (const Vector< double > & x, Vector< double > & u)
Exact solution as a Vector.
Definition at line 946 of file structured_2d_biharmonic_bellelement.cc.
References u.
Referenced by MyBiharmonicBellProblem< ELEMENT, DIM, NNODE_1D >::actions_before_newton_solve(), and MyBiharmonicBellProblem< ELEMENT, DIM, NNODE_1D >::doc_solution().
source_function()
void Physical_Variables::source_function (const Vector< double > & x, double & source)
Source function required to make the solution above an exact solution.
Definition at line 957 of file structured_2d_biharmonic_bellelement.cc.
Referenced by main().
Variable Documentation
l_x
double Physical_Variables::l_x = 2.0
length in the x direction
Definition at line 940 of file structured_2d_biharmonic_bellelement.cc.
Referenced by MyBiharmonicBellProblem< ELEMENT, DIM, NNODE_1D >::MyBiharmonicBellProblem().
l_y
double Physical_Variables::l_y = 1.0
length in the y direction
Definition at line 943 of file structured_2d_biharmonic_bellelement.cc.
Referenced by MyBiharmonicBellProblem< ELEMENT, DIM, NNODE_1D >::MyBiharmonicBellProblem().
n_x
unsigned Physical_Variables::n_x = 4
number of elements in the x direction
Definition at line 934 of file structured_2d_biharmonic_bellelement.cc.
Referenced by MyBiharmonicBellProblem< ELEMENT, DIM, NNODE_1D >::MyBiharmonicBellProblem().
n_y
unsigned Physical_Variables::n_y = 2
number of elements in the y direction
Definition at line 937 of file structured_2d_biharmonic_bellelement.cc.
Referenced by MyBiharmonicBellProblem< ELEMENT, DIM, NNODE_1D >::MyBiharmonicBellProblem().