#!MC 1100



#=======================
# LOOP OVER ALL ROTATIONS
#=======================
$!LOOP 24

$!DRAWGRAPHICS FALSE

$!VARSET |STEP|=(|LOOP|-1)
#((|LOOP|-1)+24)

$!READDATASET  '"RESLT1/orientation|STEP|.dat" ' 
  READDATAOPTION = NEW
  RESETSTYLE = YES
  INCLUDETEXT = NO
  INCLUDEGEOM = NO
  INCLUDECUSTOMLABELS = NO
  VARLOADMODE = BYNAME
  ASSIGNSTRANDIDS = YES
  INITIALPLOTTYPE = CARTESIAN3D
  VARNAMELIST = '"V1" "V2" "V3" "V4" "V5" "V6"' 
$!READDATASET  '"RESLT1/root_elements|STEP|.dat" ' 
  READDATAOPTION = APPEND
  RESETSTYLE = NO
  INCLUDETEXT = NO
  INCLUDEGEOM = NO
  INCLUDECUSTOMLABELS = NO
  VARLOADMODE = BYPOSITION
  ASSIGNSTRANDIDS = YES
  INITIALPLOTTYPE = CARTESIAN3D
$!GLOBALTHREEDVECTOR UVAR = 4
$!GLOBALTHREEDVECTOR VVAR = 5
$!GLOBALTHREEDVECTOR WVAR = 6
$!RESETVECTORLENGTH 
$!FIELDLAYERS SHOWVECTOR = YES
$!REDRAWALL 
$!FIELDMAP [55-81]  GROUP = 2
$!ACTIVEFIELDMAPS += [55-81]
$!REDRAWALL 
$!FIELDMAP [55-81]  VECTOR{SHOW = NO}
$!REDRAWALL 
$!THREEDVIEW 
  PSIANGLE = 48.1272
  THETAANGLE = 234.753
  ALPHAANGLE = 0
  VIEWERPOSITION
    {
    X = 5.57639227353
    Y = 4.08728728547
    Z = 6.07195257569
    }
$!VIEW PUSH
$!THREEDAXIS XDETAIL{SHOWAXIS = NO}
$!THREEDAXIS YDETAIL{SHOWAXIS = NO}
$!THREEDAXIS ZDETAIL{SHOWAXIS = NO}
$!REDRAWALL 
$!THREEDVIEW 
  PSIANGLE = 75.265
  THETAANGLE = 237.297
  ALPHAANGLE = 0
  VIEWERPOSITION
    {
    X = 7.29346053586
    Y = 4.86185665272
    Z = 2.62323917114
    }
$!VIEW PUSH
$!VIEW FIT
$!FIELDMAP [1-81]  VECTOR{LINETHICKNESS = 0.4}
$!REDRAWALL 
$!FIELDLAYERS SHOWMESH = NO
$!REDRAWALL 
$!FIELDMAP [1-81]  EDGELAYER{LINETHICKNESS = 0.1}

$!DRAWGRAPHICS TRUE
$!REDRAWALL 



$!IF  |LOOP|>1
  $!EXPORTNEXTFRAME
$!ELSE
  $!EXPORTSETUP EXPORTFORMAT = AVI
  $!EXPORTSETUP BITDUMPREGION = ALLFRAMES
  $!EXPORTSETUP IMAGEWIDTH = 829
  $!EXPORTSETUP EXPORTFNAME = 'orientation.avi'
  $!EXPORTSTART
$!ENDIF

$!DRAWGRAPHICS FALSE

$!ENDLOOP


$!EXPORTFINISH
