BrethertonProblem< ELEMENT > Class Template Reference
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
Public Member Functions
BrethertonProblem ()
Constructor:
void actions_before_newton_convergence_check ()
Spine heights/lengths are unknowns in the problem so their values get corrected during each Newton step. However, changing their value does not automatically change the nodal positions, so we need to update all of them.
void actions_before_newton_solve ()
Update before solve: empty.
void actions_after_newton_solve ()
Update after solve can remain empty, because the update is performed automatically after every Newton step.
void fix_pressure (const unsigned &e, const unsigned &l, const double &pvalue)
Fix pressure value l in element e to value p_value.
void activate_inflow_dependency ()
Activate the dependency of the inflow velocity on the spine heights at the outflow.
void parameter_study (const unsigned &nsteps)
Run a parameter study; perform specified number of steps.
void doc_solution (DocInfo &doc_info)
Doc the solution.
Private Attributes
ELEMENT * Control_element_pt
Pointer to control element.
ofstream Trace_file
Trace file.
BrethertonSpineMesh< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > > * Bulk_mesh_pt
Pointer to bulk mesh.
Detailed Description
template<class ELEMENT>
class BrethertonProblem< ELEMENT >
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
Bretherton problem
Definition at line 464 of file bretherton.cc.
Constructor & Destructor Documentation
BrethertonProblem()
template<class ELEMENT >
BrethertonProblem< ELEMENT >::BrethertonProblem
Constructor:
Problem constructor.
Definition at line 551 of file bretherton.cc.
References Global_Physical_Variables::Ca, Global_Physical_Variables::G(), Global_Physical_Variables::H_lo_pt, Global_Physical_Variables::H_up_pt, Global_Physical_Variables::Re, Global_Physical_Variables::ReInvFr, Global_Physical_Variables::ReSt, Global_Physical_Variables::Y_lo_pt, and Global_Physical_Variables::Y_up_pt.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT >
void BrethertonProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update after solve can remain empty, because the update is performed automatically after every Newton step.
Definition at line 509 of file bretherton.cc.
actions_before_newton_convergence_check()
template<class ELEMENT >
void BrethertonProblem< ELEMENT >::actions_before_newton_convergence_check () [inline]
Spine heights/lengths are unknowns in the problem so their values get corrected during each Newton step. However, changing their value does not automatically change the nodal positions, so we need to update all of them.
Definition at line 477 of file bretherton.cc.
References BrethertonProblem< ELEMENT >::Bulk_mesh_pt, and Global_Physical_Variables::inflow().
actions_before_newton_solve()
template<class ELEMENT >
void BrethertonProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update before solve: empty.
Definition at line 505 of file bretherton.cc.
activate_inflow_dependency()
template<class ELEMENT >
void BrethertonProblem< ELEMENT >::activate_inflow_dependency
Activate the dependency of the inflow velocity on the spine heights at the outflow.
Loop over elements on inflow boundary (1)
Definition at line 726 of file bretherton.cc.
References Global_Physical_Variables::inflow().
doc_solution()
template<class ELEMENT >
void BrethertonProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 762 of file bretherton.cc.
References Global_Physical_Variables::Ca.
fix_pressure()
template<class ELEMENT >
void BrethertonProblem< ELEMENT >::fix_pressure (const unsigned & e, const unsigned & l, const double & pvalue) [inline]
Fix pressure value l in element e to value p_value.
Definition at line 512 of file bretherton.cc.
References BrethertonProblem< ELEMENT >::Bulk_mesh_pt, and BrethertonProblem< ELEMENT >::fix_pressure().
Referenced by BrethertonProblem< ELEMENT >::fix_pressure().
parameter_study()
template<class ELEMENT >
void BrethertonProblem< ELEMENT >::parameter_study (const unsigned & nsteps)
Run a parameter study; perform specified number of steps.
Parameter study.
Definition at line 816 of file bretherton.cc.
References Global_Physical_Variables::Ca.
Referenced by main().
Member Data Documentation
Bulk_mesh_pt
template<class ELEMENT >
BrethertonSpineMesh<ELEMENT,SpineLineFluidInterfaceElement<ELEMENT> >* BrethertonProblem< ELEMENT >::Bulk_mesh_pt [private]
Pointer to bulk mesh.
Definition at line 542 of file bretherton.cc.
Referenced by BrethertonProblem< ELEMENT >::actions_before_newton_convergence_check(), and BrethertonProblem< ELEMENT >::fix_pressure().
Control_element_pt
template<class ELEMENT >
ELEMENT* BrethertonProblem< ELEMENT >::Control_element_pt [private]
Pointer to control element.
Definition at line 535 of file bretherton.cc.
Trace_file
template<class ELEMENT >
ofstream BrethertonProblem< ELEMENT >::Trace_file [private]
Trace file.
Definition at line 538 of file bretherton.cc.
The documentation for this class was generated from the following file:
bretherton.cc