ElasticRingProblem< ELEMENT, TIMESTEPPER > Class Template Reference
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
Public Member Functions
ElasticRingProblem (const unsigned &N, const double &L)
Constructor: Number of elements, length of domain, flag for setting Newmark IC directly or consistently.
OneDLagrangianMesh< ELEMENT > * mesh_pt ()
Access function for the mesh.
void actions_after_newton_solve ()
Update function is empty.
void actions_before_newton_solve ()
Update function is empty.
void doc_solution (DocInfo &doc_info)
Doc solution.
void unsteady_run ()
Do unsteady run.
ElasticRingProblem (const unsigned &n_element)
Constructor: Number of elements.
OneDLagrangianMesh< ELEMENT > * mesh_pt ()
Access function for the specific mesh.
void actions_after_newton_solve ()
Update function is empty.
void actions_before_newton_solve ()
Update function is empty.
void set_initial_conditions ()
Setup initial conditions.
void doc_solution (DocInfo &doc_info)
Doc solution.
void unsteady_run ()
Do unsteady run.
void dump_it (ofstream &dump_file)
Dump problem-specific parameter values, then dump generic problem data.
void restart (ifstream &restart_file)
Read problem-specific parameter values, then recover generic problem data.
Private Attributes
double Length
Length of domain (in terms of the Lagrangian coordinates)
ELEMENT * Displ_control_elem_pt
In which element are we applying displacement control? (here only used for doc of radius)
Vector< double > S_displ_control
At what local coordinate are we applying displacement control?
GeomObject * Undef_geom_pt
Pointer to geometric object that represents the undeformed shape.
SolidInitialCondition * IC_pt
Pointer to object that specifies the initial condition.
ofstream Trace_file
Trace file for recording control data.
unsigned Validation_run_flag
Flag for validation run: Default: 0 = no validation run.
bool Restart_flag
Restart flag specified via command line?
Detailed Description
template<class ELEMENT, class TIMESTEPPER>
class ElasticRingProblem< ELEMENT, TIMESTEPPER >
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
Oscillating ring problem: Compare small-amplitude oscillations against analytical solution of the linearised equations.
Ring problem
Definition at line 71 of file lin_unsteady_ring.cc.
Constructor & Destructor Documentation
ElasticRingProblem() [1/2]
template<class ELEMENT , class TIMESTEPPER >
ElasticRingProblem< ELEMENT, TIMESTEPPER >::ElasticRingProblem (const unsigned & N, const double & L)
Constructor: Number of elements, length of domain, flag for setting Newmark IC directly or consistently.
Constructor for elastic ring problem.
Definition at line 127 of file lin_unsteady_ring.cc.
References ElasticRingProblem< ELEMENT, TIMESTEPPER >::Displ_control_elem_pt, ElasticRingProblem< ELEMENT, TIMESTEPPER >::IC_pt, ElasticRingProblem< ELEMENT, TIMESTEPPER >::mesh_pt(), ElasticRingProblem< ELEMENT, TIMESTEPPER >::S_displ_control, and ElasticRingProblem< ELEMENT, TIMESTEPPER >::Undef_geom_pt.
ElasticRingProblem() [2/2]
template<class ELEMENT , class TIMESTEPPER >
ElasticRingProblem< ELEMENT, TIMESTEPPER >::ElasticRingProblem (const unsigned & n_element)
Constructor: Number of elements.
Constructor for elastic ring problem.
Definition at line 157 of file unsteady_ring.cc.
References Global_Physical_Variables::H, Global_Physical_Variables::Lambda_sq, ElasticRingProblem< ELEMENT, TIMESTEPPER >::mesh_pt(), and Global_Physical_Variables::press_load().
Member Function Documentation
actions_after_newton_solve() [1/2]
template<class ELEMENT , class TIMESTEPPER >
void ElasticRingProblem< ELEMENT, TIMESTEPPER >::actions_after_newton_solve () [inline]
Update function is empty.
Definition at line 87 of file lin_unsteady_ring.cc.
actions_after_newton_solve() [2/2]
template<class ELEMENT , class TIMESTEPPER >
void ElasticRingProblem< ELEMENT, TIMESTEPPER >::actions_after_newton_solve () [inline]
Update function is empty.
Definition at line 113 of file unsteady_ring.cc.
actions_before_newton_solve() [1/2]
template<class ELEMENT , class TIMESTEPPER >
void ElasticRingProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_solve () [inline]
Update function is empty.
Definition at line 90 of file lin_unsteady_ring.cc.
actions_before_newton_solve() [2/2]
template<class ELEMENT , class TIMESTEPPER >
void ElasticRingProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_solve () [inline]
Update function is empty.
Definition at line 116 of file unsteady_ring.cc.
doc_solution() [1/2]
template<class ELEMENT , class TIMESTEPPER >
void ElasticRingProblem< ELEMENT, TIMESTEPPER >::doc_solution (DocInfo & doc_info)
Doc solution.
Document solution.
Definition at line 213 of file lin_unsteady_ring.cc.
doc_solution() [2/2]
template<class ELEMENT , class TIMESTEPPER >
void ElasticRingProblem< ELEMENT, TIMESTEPPER >::doc_solution (DocInfo & doc_info)
Doc solution.
dump_it()
template<class ELEMENT , class TIMESTEPPER >
void ElasticRingProblem< ELEMENT, TIMESTEPPER >::dump_it (ofstream & dump_file)
Dump problem-specific parameter values, then dump generic problem data.
Definition at line 325 of file unsteady_ring.cc.
References Global_Physical_Variables::Pcos.
mesh_pt() [1/2]
template<class ELEMENT , class TIMESTEPPER >
OneDLagrangianMesh< ELEMENT > * ElasticRingProblem< ELEMENT, TIMESTEPPER >::mesh_pt () [inline]
Access function for the mesh.
Definition at line 81 of file lin_unsteady_ring.cc.
Referenced by ElasticRingProblem< ELEMENT, TIMESTEPPER >::ElasticRingProblem().
mesh_pt() [2/2]
template<class ELEMENT , class TIMESTEPPER >
OneDLagrangianMesh< ELEMENT > * ElasticRingProblem< ELEMENT, TIMESTEPPER >::mesh_pt () [inline]
Access function for the specific mesh.
Definition at line 107 of file unsteady_ring.cc.
restart()
template<class ELEMENT , class TIMESTEPPER >
void ElasticRingProblem< ELEMENT, TIMESTEPPER >::restart (ifstream & restart_file)
Read problem-specific parameter values, then recover generic problem data.
Definition at line 347 of file unsteady_ring.cc.
References Global_Physical_Variables::Pcos.
set_initial_conditions()
template<class ELEMENT , class TIMESTEPPER >
void ElasticRingProblem< ELEMENT, TIMESTEPPER >::set_initial_conditions
Setup initial conditions.
Setup initial conditions -- either restart from solution specified via command line or impulsive start.
Definition at line 380 of file unsteady_ring.cc.
unsteady_run() [1/2]
template<class ELEMENT , class TIMESTEPPER >
void ElasticRingProblem< ELEMENT, TIMESTEPPER >::unsteady_run
Do unsteady run.
Solver loop to perform unsteady run. Label for output
Definition at line 320 of file lin_unsteady_ring.cc.
References Global_Physical_Variables::Consistent_newmark_ic, Global_Physical_Variables::Fixed_timestep_flag, and Global_Physical_Variables::Long_run_flag.
Referenced by main().
unsteady_run() [2/2]
template<class ELEMENT , class TIMESTEPPER >
void ElasticRingProblem< ELEMENT, TIMESTEPPER >::unsteady_run ()
Do unsteady run.
Member Data Documentation
Displ_control_elem_pt
template<class ELEMENT , class TIMESTEPPER >
ELEMENT* ElasticRingProblem< ELEMENT, TIMESTEPPER >::Displ_control_elem_pt [private]
In which element are we applying displacement control? (here only used for doc of radius)
Definition at line 105 of file lin_unsteady_ring.cc.
Referenced by ElasticRingProblem< ELEMENT, TIMESTEPPER >::ElasticRingProblem().
IC_pt
template<class ELEMENT , class TIMESTEPPER >
SolidInitialCondition* ElasticRingProblem< ELEMENT, TIMESTEPPER >::IC_pt [private]
Pointer to object that specifies the initial condition.
Definition at line 114 of file lin_unsteady_ring.cc.
Referenced by ElasticRingProblem< ELEMENT, TIMESTEPPER >::ElasticRingProblem().
Length
template<class ELEMENT , class TIMESTEPPER >
double ElasticRingProblem< ELEMENT, TIMESTEPPER >::Length [private]
Length of domain (in terms of the Lagrangian coordinates)
Definition at line 101 of file lin_unsteady_ring.cc.
Restart_flag
template<class ELEMENT , class TIMESTEPPER >
bool ElasticRingProblem< ELEMENT, TIMESTEPPER >::Restart_flag [private]
Restart flag specified via command line?
Definition at line 145 of file unsteady_ring.cc.
S_displ_control
template<class ELEMENT , class TIMESTEPPER >
Vector<double> ElasticRingProblem< ELEMENT, TIMESTEPPER >::S_displ_control [private]
At what local coordinate are we applying displacement control?
Definition at line 108 of file lin_unsteady_ring.cc.
Referenced by ElasticRingProblem< ELEMENT, TIMESTEPPER >::ElasticRingProblem().
Trace_file
template<class ELEMENT , class TIMESTEPPER >
ofstream ElasticRingProblem< ELEMENT, TIMESTEPPER >::Trace_file [private]
Trace file for recording control data.
Definition at line 117 of file lin_unsteady_ring.cc.
Undef_geom_pt
template<class ELEMENT , class TIMESTEPPER >
GeomObject* ElasticRingProblem< ELEMENT, TIMESTEPPER >::Undef_geom_pt [private]
Pointer to geometric object that represents the undeformed shape.
Definition at line 111 of file lin_unsteady_ring.cc.
Referenced by ElasticRingProblem< ELEMENT, TIMESTEPPER >::ElasticRingProblem().
Validation_run_flag
template<class ELEMENT , class TIMESTEPPER >
unsigned ElasticRingProblem< ELEMENT, TIMESTEPPER >::Validation_run_flag [private]
Flag for validation run: Default: 0 = no validation run.
Definition at line 142 of file unsteady_ring.cc.
The documentation for this class was generated from the following files:
lin_unsteady_ring.cc
unsteady_ring.cc