oomph::BackwardStepQuadMesh< ELEMENT > Class Template Reference
Backward step mesh.
#include <backward_step_mesh.h>
Public Member Functions
BackwardStepQuadMesh (const unsigned &nx, const unsigned &ny, const unsigned &nx_cut_out, const unsigned &ny_cut_out, const double &lx, const double &ly, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Pass overall number of elements in the horizontal and vertical directions, nx and ny, and the corresponding dimensions, lx and ly. nx_cut_out and ny_cut_out elements are cut out from the lower right corner to create the (reversed) backward step geometry. Timestepper defaults to Steady.
virtual ~BackwardStepQuadMesh ()
Destructor: Empty.
Public Member Functions inherited from oomph::RectangularQuadMesh< ELEMENT >
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Simple constructor: nx: number of elements in x direction; ny: number of elements in y direction; lx, length of domain in x direction (0,lx); ly, length of domain in y direction (0,ly) Also pass pointer to timestepper (defaults to Steady)
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor that allows the specification of minimum and maximum values of x and y coordinates.
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly, const bool &periodic_in_x, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Simple constructor: nx: number of elements in x direction; ny: number of elements in y direction; lx, length of domain in x direction (0,lx); ly, length of domain in y direction (0,ly) Boolean flag specifies if the mesh is periodic in the x-direction. Also pass pointer to timestepper (defaults to Steady)
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, const bool &periodic_in_x, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor that allows the specification of minimum and maximum values of x and y coordinates. Boolean flag specifies if the mesh is periodic in the x-direction.
const unsigned & nx () const
Return number of elements in x direction.
const unsigned & ny () const
Return number of elements in y direction.
const double x_min () const
Return the minimum value of x coordinate.
const double x_max () const
Return the maximum value of x coordinate.
const double y_min () const
Return the minimum value of y coordinate.
const double y_max () const
Return the maximum value of y coordinate.
virtual void element_reorder ()
Reorder the elements: By default they are ordered in "horizontal" layers (increasing in x, then in y). This function changes this to an ordering in the vertical direction (y first, then x). This is more efficient if a frontal solver is used and the mesh has more elements in the x than the y direction. Can be overloaded in specific derived meshes.
virtual double x_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode)
Return the value of the x-coordinate at the node given by the local node number (xnode, ynode) in the element (xelement,yelement). The description is in a "psudeo" two-dimensional coordinate system, so the range of xelement is [0,Nx-1], yelement is [0,Ny-1], and that of xnode and ynode is [0,Np-1]. The default is to return nodes that are equally spaced in the x coodinate.
virtual double y_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode)
Return the value of the y-coordinate at the node given by the local node number (xnode, ynode) in the element (xelement,yelement). The description is in a "psudeo" two-dimensional coordinate system, so the range of xelement is [0,Nx-1], yelement is [0,Ny-1], and that of xnode and ynode is [0,Np-1]. The default it to return nodes that are equally spaced in the y coordinate.
Private Member Functions
void build_mesh (const unsigned &nx, const unsigned &ny, const unsigned &nx_cut_out, const unsigned &ny_cut_out, const double &lx, const double &ly)
Actual build function.
Additional Inherited Members
Protected Member Functions inherited from oomph::RectangularQuadMesh< ELEMENT >
void build_mesh (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Generic mesh construction function: contains all the hard work.
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, const bool &periodic_in_x, const bool &build, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor that allows the specification of minimum and maximum values of x and y coordinates and does not build the mesh This is intend to be used in derived classes that overload the spacing functions. THis is scheduled to be changed, however. The reason why this MUST be done is because the virtual spacing functions cannot be called in the base constructur, because they will not have been overloaded yet!!
Protected Attributes inherited from oomph::RectangularQuadMesh< ELEMENT >
unsigned Nx
Nx: number of elements in x-direction.
unsigned Ny
Ny: number of elements in y-direction.
unsigned Np
Np: number of (linear) points in the element.
double Xmin
Minimum value of x coordinate.
double Xmax
Maximum value of x coordinate.
double Ymin
Minimum value of y coordinate.
double Ymax
Maximum value of y coordinate.
bool Xperiodic
Boolean variable used to determine whether the mesh is periodic in the x-direction.
Detailed Description
template<class ELEMENT>
class oomph::BackwardStepQuadMesh< ELEMENT >
Backward step mesh.
Definition at line 45 of file backward_step_mesh.h.
Constructor & Destructor Documentation
BackwardStepQuadMesh()
template<class ELEMENT >
oomph::BackwardStepQuadMesh< ELEMENT >::BackwardStepQuadMesh (const unsigned & nx, const unsigned & ny, const unsigned & nx_cut_out, const unsigned & ny_cut_out, const double & lx, const double & ly, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Pass overall number of elements in the horizontal and vertical directions, nx and ny, and the corresponding dimensions, lx and ly. nx_cut_out and ny_cut_out elements are cut out from the lower right corner to create the (reversed) backward step geometry. Timestepper defaults to Steady.
Definition at line 54 of file backward_step_mesh.h.
References oomph::BackwardStepQuadMesh< ELEMENT >::build_mesh(), oomph::RectangularQuadMesh< ELEMENT >::nx(), and oomph::RectangularQuadMesh< ELEMENT >::ny().
~BackwardStepQuadMesh()
template<class ELEMENT >
virtual oomph::BackwardStepQuadMesh< ELEMENT >::~BackwardStepQuadMesh () [inline], [virtual]
Destructor: Empty.
Definition at line 69 of file backward_step_mesh.h.
Member Function Documentation
build_mesh()
template<class ELEMENT >
void oomph::BackwardStepQuadMesh< ELEMENT >::build_mesh (const unsigned & nx, const unsigned & ny, const unsigned & nx_cut_out, const unsigned & ny_cut_out, const double & lx, const double & ly) [private]
Actual build function.
Actual build function. Pass overall number of elements in the horizontal and vertical directions, nx and ny, and the corresponding dimensions, lx and ly. nx_cut_out and ny_cut_out elements are cut out from the lower right corner to create the (reversed) backward step geometry. Timestepper defaults to Steady.
Definition at line 47 of file backward_step_mesh.template.cc.
Referenced by oomph::BackwardStepQuadMesh< ELEMENT >::BackwardStepQuadMesh().
The documentation for this class was generated from the following files:
backward_step_mesh.h
backward_step_mesh.template.cc