two_d_unsteady_heat_restarted.cc File Reference
Classes
class UnsteadyHeatProblem< ELEMENT >
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Namespaces
namespace ExactSolnForUnsteadyHeat
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Functions
void ExactSolnForUnsteadyHeat::get_exact_u (const double &time, const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void ExactSolnForUnsteadyHeat::get_exact_u (const double &time, const Vector< double > &x, double &u)
Exact solution as a scalar.
void ExactSolnForUnsteadyHeat::get_source (const double &time, const Vector< double > &x, double &source)
Source function to make it an exact solution.
int main (int argc, char *argv[])
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Function Documentation
main()
int main (int argc, char * argv[])
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Driver code for unsteady heat equation with option for restart from disk: Only a single command line argument is allowed. If specified it is interpreted as the name of the restart file.
Definition at line 532 of file two_d_unsteady_heat_restarted.cc.
References UnsteadyHeatProblem< ELEMENT >::doc_solution(), ExactSolnForUnsteadyHeat::get_source(), and UnsteadyHeatProblem< ELEMENT >::set_initial_condition().