two_d_unsteady_heat.cc File Reference
Classes
class UnsteadyHeatProblem< ELEMENT >
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Namespaces
 ExactSolnForUnsteadyHeat
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Functions
void ExactSolnForUnsteadyHeat::get_exact_u (const double &time, const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void ExactSolnForUnsteadyHeat::get_exact_u (const double &time, const Vector< double > &x, double &u)
Exact solution as a scalar.
void ExactSolnForUnsteadyHeat::get_source (const double &time, const Vector< double > &x, double &source)
Source function to make it an exact solution.
int main ()
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Variables
double ExactSolnForUnsteadyHeat::K =10
Decay factor.
double ExactSolnForUnsteadyHeat::Phi =1.0
Angle of bump.
Function Documentation
main()
int main ()
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Driver code for unsteady heat equation
Definition at line 414 of file two_d_unsteady_heat.cc.
References UnsteadyHeatProblem< ELEMENT >::doc_solution(), ExactSolnForUnsteadyHeat::get_source(), and UnsteadyHeatProblem< ELEMENT >::set_initial_condition().