two_d_unsteady_heat_2adapt.cc File Reference
Classes
class MyEllipse
Oscillating ellipse.
class RefineableUnsteadyHeatProblem< ELEMENT >
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Namespaces
 TanhSolnForUnsteadyHeat
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Functions
double TanhSolnForUnsteadyHeat::step_position (const double &time)
Position of step (x-axis intercept)
void TanhSolnForUnsteadyHeat::get_exact_u (const double &time, const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForUnsteadyHeat::get_exact_u (const double &time, const Vector< double > &x, double &u)
Exact solution as a scalar.
void TanhSolnForUnsteadyHeat::get_source (const double &time, const Vector< double > &x, double &source)
Source function to make it an exact solution.
void TanhSolnForUnsteadyHeat::prescribed_flux_on_fixed_y_boundary (const double &time, const Vector< double > &x, double &flux)
Flux required by the exact solution on a boundary on which y is fixed.
int main (int argc, char *argv[])
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Variables
double TanhSolnForUnsteadyHeat::Alpha
Parameter for steepness of step.
double TanhSolnForUnsteadyHeat::Beta
Parameter for amplitude of step translation.
double TanhSolnForUnsteadyHeat::Gamma
Parameter for timescale of step translation.
double TanhSolnForUnsteadyHeat::TanPhi
Parameter for angle of step.
Function Documentation
main()
int main (int argc, char * argv[])
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Demonstrate how to solve an unsteady heat problem in deformable domain with mesh adaptation. Command line arguments specify the name of the restart file.
Definition at line 1054 of file two_d_unsteady_heat_2adapt.cc.
References RefineableUnsteadyHeatProblem< ELEMENT >::bulk_mesh_pt(), RefineableUnsteadyHeatProblem< ELEMENT >::doc_solution(), RefineableUnsteadyHeatProblem< ELEMENT >::epsilon_t(), TanhSolnForUnsteadyHeat::get_source(), RefineableUnsteadyHeatProblem< ELEMENT >::next_dt(), RefineableUnsteadyHeatProblem< ELEMENT >::set_initial_condition(), and RefineableUnsteadyHeatProblem< ELEMENT >::write_trace_file_header().