osc_ring_alg.cc File Reference
Classes
class OscRingNStProblem< ELEMENT >
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Namespaces
namespace Global_Physical_Variables
Namespace for physical parameters.
Functions
int main (int argc, char *argv[])
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Function Documentation
main()
int main (int argc, char * argv[])
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Demonstrate how to solve OscRingNSt problem in deformable domain with mesh adaptation
Definition at line 923 of file osc_ring_alg.cc.
References oomph::SarahBL::full_exact_soln(), OscRingNStProblem< ELEMENT >::restart(), OscRingNStProblem< ELEMENT >::set_initial_condition(), and OscRingNStProblem< ELEMENT >::unsteady_run().