oomph::Steady< NSTEPS > Class Template Reference
Faux time-stepper for steady problems. Allows storage for NSTEPS previous values.
#include <timesteppers.h>
Public Types
typedef double(* InitialConditionFctPt) (const double &t)
Typedef for function that returns the (scalar) initial value at a given value of the continuous time t.
Public Member Functions
Steady ()
Constructor: Creates storage for NSTEPS previous timesteps and can evaluate up to 2nd derivatives (though it doesn't actually do anything -- all time-derivatives evaluate to zero)
Steady (const Steady &)=delete
Broken copy constructor.
void operator= (const Steady &)=delete
Broken assignment operator.
unsigned order () const
Return the actual order of the scheme. Returning zero here -- doesn't make much sense, though.
void assign_initial_values_impulsive (Data *const &data_pt)
Initialise the time-history for the Data values, corresponding to an impulsive start.
void assign_initial_positions_impulsive (Node *const &node_pt)
Initialise the time-history for the nodal positions corresponding to an impulsive start.
void assign_initial_data_values (Data *const &data_pt, Vector< InitialConditionFctPt > initial_value_fct)
Initialise the time-history for the Data values, corresponding to given time history, specified by Vector of function pointers.
void shift_time_values (Data *const &data_pt)
This function updates the Data's time history so that we can advance to the next timestep. As for BDF schemes, we simply push the values backwards...
void shift_time_positions (Node *const &node_pt)
This function advances the time history of the positions at a node.
void set_weights ()
Set weights.
unsigned nprev_values () const
Number of previous values available.
unsigned ndt () const
Number of timestep increments that need to be stored by the scheme.
double weight (const unsigned &i, const unsigned &j) const
Dummy: Access function for j-th weight for the i-th derivative.
Public Member Functions inherited from oomph::TimeStepper
TimeStepper (const unsigned &tstorage, const unsigned &max_deriv)
Constructor. Pass the amount of storage required by timestepper (present value + history values) and the order of highest time-derivative.
TimeStepper ()
Broken empty constructor.
TimeStepper (const TimeStepper &)=delete
Broken copy constructor.
void operator= (const TimeStepper &)=delete
Broken assignment operator.
virtual ~TimeStepper ()
virtual destructor
unsigned highest_derivative () const
Highest order derivative that the scheme can compute.
double & time ()
Return current value of continous time.
double time () const
Return current value of continous time.
virtual unsigned nprev_values_for_value_at_evaluation_time () const
Number of previous values needed to calculate the value at the current time. i.e. how many previous values must we loop over to calculate the values at the evaluation time. For most methods this is 1, i.e. just use the value at t_{n+1}. See midpoint method for a counter-example.
void make_steady ()
Function to make the time stepper temporarily steady. This is trivially achieved by setting all the weights to zero.
bool is_steady () const
Flag to indicate if a timestepper has been made steady (possibly temporarily to switch off time-dependence)
bool predict_by_explicit_step () const
Flag: is adaptivity done by taking a separate step using an ExplicitTimeStepper object?
ExplicitTimeStepper * explicit_predictor_pt ()
Get the pointer to the explicit timestepper to use as a predictor in adaptivity if Predict_by_explicit_step is set.
void set_predictor_pt (ExplicitTimeStepper *_pred_pt)
Set the pointer to the explicit timestepper to use as a predictor in adaptivity if Predict_by_explicit_step is set.
void update_predicted_time (const double &new_time)
Set the time that the current predictions apply for, only needed for paranoid checks when doing Predict_by_explicit_step.
void check_predicted_values_up_to_date () const
Check that the predicted values are the ones we want.
unsigned predictor_storage_index () const
Return the time-index in each Data where predicted values are stored if the timestepper is adaptive.
void enable_warning_in_assign_initial_data_values ()
Enable the output of warnings due to possible fct pointer vector size mismatch in assign_initial_data_values (Default)
void disable_warning_in_assign_initial_data_values ()
Disable the output of warnings due to possible fct pointer vector size mismatch in assign_initial_data_values.
const DenseMatrix< double > * weights_pt () const
Get a (const) pointer to the weights.
virtual void undo_make_steady ()
Reset the is_steady status of a specific TimeStepper to its default and re-assign the weights.
std::string type () const
Return string that indicates the type of the timestepper (e.g. "BDF", "Newmark", etc.)
void time_derivative (const unsigned &i, Data *const &data_pt, Vector< double > &deriv)
Evaluate i-th derivative of all values in Data and return in Vector deriv[].
double time_derivative (const unsigned &i, Data *const &data_pt, const unsigned &j)
Evaluate i-th derivative of j-th value in Data.
void time_derivative (const unsigned &i, Node *const &node_pt, Vector< double > &deriv)
Evaluate i-th derivative of all values in Node and return in Vector deriv[] (this can't be simply combined with time_derivative(.., Data, ...) because of differences with haning nodes).
double time_derivative (const unsigned &i, Node *const &node_pt, const unsigned &j)
Evaluate i-th derivative of j-th value in Node. Note the use of the node's value() function so that hanging nodes are taken into account (this is why the functions for Data and Node cannot be combined through simple polymorphism: value is not virtual).
Time *const & time_pt () const
Access function for the pointer to time (const version)
Time *& time_pt ()
Access function for the pointer to time (can't have a paranoid test for null pointers because this is used as a set function).
unsigned ntstorage () const
Return the number of doubles required to represent history (one for steady)
bool adaptive_flag () const
Function to indicate whether the scheme is adaptive (false by default)
virtual void set_predictor_weights ()
Set the weights for the predictor previous timestep (currently empty -- overwrite for specific scheme)
virtual void calculate_predicted_values (Data *const &data_pt)
Do the predictor step for data stored in a Data object (currently empty -- overwrite for specific scheme)
virtual void calculate_predicted_positions (Node *const &node_pt)
Do the predictor step for the positions at a node (currently empty --- overwrite for a specific scheme)
virtual void set_error_weights ()
Set the weights for the error computation, (currently empty -- overwrite for specific scheme)
virtual double temporal_error_in_position (Node *const &node_pt, const unsigned &i)
Compute the error in the position i at a node zero here -- overwrite for specific scheme.
virtual double temporal_error_in_value (Data *const &data_pt, const unsigned &i)
Compute the error in the value i in a Data structure zero here -- overwrite for specific scheme.
virtual void actions_before_timestep (Problem *problem_pt)
Interface for any actions that need to be performed before a time step.
virtual void actions_after_timestep (Problem *problem_pt)
Interface for any actions that need to be performed after a time step.
Static Private Attributes
static double One = 1.0
Static variable to hold the value 1.0.
static double Zero = 0.0
Static variable to hold the value 0.0.
static Time Dummy_time
Additional Inherited Members
Protected Attributes inherited from oomph::TimeStepper
Time * Time_pt
Pointer to discrete time storage scheme.
DenseMatrix< double > Weight
Storage for the weights associated with the timestepper.
std::string Type
String that indicates the type of the timestepper (e.g. "BDF", "Newmark", etc.)
bool Adaptive_Flag
Boolean variable to indicate whether the timestepping scheme can be adaptive.
bool Is_steady
Bool to indicate if the timestepper is steady, i.e. its time-derivatives evaluate to zero. This status may be achieved temporarily by calling make_steady(). It can be reset to the appropriate default by the function undo_make_steady().
bool Shut_up_in_assign_initial_data_values
Boolean to indicate if the timestepper will output warnings when setting possibly an incorrect number of initial data values from function pointers.
bool Predict_by_explicit_step
Flag: is adaptivity done by taking a separate step using an ExplicitTimeStepper object?
ExplicitTimeStepper * Explicit_predictor_pt
Pointer to explicit time stepper to use as predictor if Predict_by_explicit_step is set. ??ds merge the two? predict by explicit if pointer is set?
double Predicted_time
Store the time that the predicted values currently stored are at, to compare for paranoid checks.
int Predictor_storage_index
The time-index in each Data object where predicted values are stored. -1 if not set.
Detailed Description
template<unsigned NSTEPS>
class oomph::Steady< NSTEPS >
Faux time-stepper for steady problems. Allows storage for NSTEPS previous values.
Definition at line 680 of file timesteppers.h.
Member Typedef Documentation
InitialConditionFctPt
template<unsigned NSTEPS>
typedef double(* oomph::Steady< NSTEPS >::InitialConditionFctPt) (const double &t)
Typedef for function that returns the (scalar) initial value at a given value of the continuous time t.
Definition at line 760 of file timesteppers.h.
Constructor & Destructor Documentation
Steady() [1/2]
template<unsigned NSTEPS>
oomph::Steady< NSTEPS >::Steady () [inline]
Constructor: Creates storage for NSTEPS previous timesteps and can evaluate up to 2nd derivatives (though it doesn't actually do anything -- all time-derivatives evaluate to zero)
Definition at line 687 of file timesteppers.h.
References oomph::Steady< NSTEPS >::Dummy_time, oomph::TimeStepper::Is_steady, and oomph::TimeStepper::Time_pt.
Steady() [2/2]
template<unsigned NSTEPS>
oomph::Steady< NSTEPS >::Steady (const Steady< NSTEPS > &) [delete]
Broken copy constructor.
Member Function Documentation
assign_initial_data_values()
template<unsigned NSTEPS>
void oomph::Steady< NSTEPS >::assign_initial_data_values (Data *const & data_pt, Vector< InitialConditionFctPt > initial_value_fct) [inline]
Initialise the time-history for the Data values, corresponding to given time history, specified by Vector of function pointers.
Definition at line 765 of file timesteppers.h.
References oomph::TimeStepper::ntstorage(), t, oomph::Time::time(), and oomph::TimeStepper::Time_pt.
assign_initial_positions_impulsive()
template<unsigned NSTEPS>
void oomph::Steady< NSTEPS >::assign_initial_positions_impulsive (Node *const & node_pt) [inline], [virtual]
Initialise the time-history for the nodal positions corresponding to an impulsive start.
Implements oomph::TimeStepper.
Definition at line 733 of file timesteppers.h.
References i, oomph::Node::ndim(), oomph::Node::nposition_type(), oomph::Node::position_is_a_copy(), t, and oomph::Node::x_gen().
assign_initial_values_impulsive()
template<unsigned NSTEPS>
void oomph::Steady< NSTEPS >::assign_initial_values_impulsive (Data *const & data_pt) [inline], [virtual]
Initialise the time-history for the Data values, corresponding to an impulsive start.
Implements oomph::TimeStepper.
Definition at line 713 of file timesteppers.h.
References t.
ndt()
template<unsigned NSTEPS>
unsigned oomph::Steady< NSTEPS >::ndt () const [inline], [virtual]
Number of timestep increments that need to be stored by the scheme.
Implements oomph::TimeStepper.
Definition at line 862 of file timesteppers.h.
nprev_values()
template<unsigned NSTEPS>
unsigned oomph::Steady< NSTEPS >::nprev_values () const [inline], [virtual]
Number of previous values available.
Implements oomph::TimeStepper.
Definition at line 856 of file timesteppers.h.
operator=()
template<unsigned NSTEPS>
void oomph::Steady< NSTEPS >::operator= (const Steady< NSTEPS > &) [delete]
Broken assignment operator.
order()
template<unsigned NSTEPS>
unsigned oomph::Steady< NSTEPS >::order () const [inline], [virtual]
Return the actual order of the scheme. Returning zero here -- doesn't make much sense, though.
Reimplemented from oomph::TimeStepper.
Definition at line 706 of file timesteppers.h.
set_weights()
template<unsigned NSTEPS>
void oomph::Steady< NSTEPS >::set_weights () [inline], [virtual]
Set weights.
Implements oomph::TimeStepper.
Definition at line 839 of file timesteppers.h.
References oomph::TimeStepper::highest_derivative(), i, and oomph::TimeStepper::Weight.
shift_time_positions()
template<unsigned NSTEPS>
void oomph::Steady< NSTEPS >::shift_time_positions (Node *const & node_pt) [inline], [virtual]
This function advances the time history of the positions at a node.
Implements oomph::TimeStepper.
Definition at line 813 of file timesteppers.h.
References i, oomph::Node::ndim(), oomph::Node::nposition_type(), oomph::Node::position_is_a_copy(), t, and oomph::Node::x_gen().
shift_time_values()
template<unsigned NSTEPS>
void oomph::Steady< NSTEPS >::shift_time_values (Data *const & data_pt) [inline], [virtual]
This function updates the Data's time history so that we can advance to the next timestep. As for BDF schemes, we simply push the values backwards...
Implements oomph::TimeStepper.
Definition at line 791 of file timesteppers.h.
References t.
weight()
template<unsigned NSTEPS>
double oomph::Steady< NSTEPS >::weight (const unsigned & i, const unsigned & j) const [inline], [virtual]
Dummy: Access function for j-th weight for the i-th derivative.
Reimplemented from oomph::TimeStepper.
Definition at line 868 of file timesteppers.h.
References i, oomph::Steady< NSTEPS >::One, and oomph::Steady< NSTEPS >::Zero.
Member Data Documentation
Dummy_time
template<unsigned NSTEPS>
Time oomph::Steady< NSTEPS >::Dummy_time [static], [private]
Definition at line 888 of file timesteppers.h.
Referenced by oomph::Steady< NSTEPS >::Steady().
One
template<unsigned NSTEPS>
double oomph::Steady< NSTEPS >::One = 1.0 [static], [private]
Static variable to hold the value 1.0.
Definition at line 882 of file timesteppers.h.
Referenced by oomph::Steady< NSTEPS >::weight().
Zero
template<unsigned NSTEPS>
double oomph::Steady< NSTEPS >::Zero = 0.0 [static], [private]
Static variable to hold the value 0.0.
Definition at line 885 of file timesteppers.h.
Referenced by oomph::Steady< NSTEPS >::weight().
The documentation for this class was generated from the following files:
timesteppers.h
timesteppers.cc