oomph::RefineableQCrouzeixRaviartElement< DIM > Class Template Reference
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
#include <refineable_navier_stokes_elements.h>
Public Member Functions
RefineableQCrouzeixRaviartElement ()
Constructor.
RefineableQCrouzeixRaviartElement (const RefineableQCrouzeixRaviartElement< DIM > &dummy)=delete
Broken copy constructor.
unsigned ncont_interpolated_values () const
Broken assignment operator.
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: Reconstruct pressure from the (merged) sons This must be specialised for each dimension.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get all function values [u,v..,p] at previous timestep t (t=0: present; t>0: previous timestep).
void further_setup_hanging_nodes ()
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty.
void further_build ()
Further build for Crouzeix_Raviart interpolates the internal pressure dofs from father element: Make sure pressure values and dp/ds agree between fathers and sons at the midpoints of the son elements. This must be specialised for each dimension.
void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs containing.
void rebuild_from_sons (Mesh *&mesh_pt)
2D Rebuild from sons: Reconstruct pressure from the (merged) sons
void rebuild_from_sons (Mesh *&mesh_pt)
3D Rebuild from sons: Reconstruct pressure from the (merged) sons
void further_build ()
2D Further build for Crouzeix_Raviart interpolates the internal pressure dofs from father element: Make sure pressure values and dp/ds agree between fathers and sons at the midpoints of the son elements.
void further_build ()
3D Further build for Crouzeix_Raviart interpolates the internal pressure dofs from father element: Make sure pressure values and dp/ds agree between fathers and sons at the midpoints of the son elements.
Private Member Functions
void unpin_elemental_pressure_dofs ()
Unpin all internal pressure dofs.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::RefineableQCrouzeixRaviartElement< DIM >
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Refineable version of Crouzeix Raviart elements. Generic class definitions
Definition at line 1105 of file refineable_navier_stokes_elements.h.
Constructor & Destructor Documentation
RefineableQCrouzeixRaviartElement() [1/2]
template<unsigned DIM>
oomph::RefineableQCrouzeixRaviartElement< DIM >::RefineableQCrouzeixRaviartElement () [inline]
Constructor.
Definition at line 1124 of file refineable_navier_stokes_elements.h.
RefineableQCrouzeixRaviartElement() [2/2]
template<unsigned DIM>
oomph::RefineableQCrouzeixRaviartElement< DIM >::RefineableQCrouzeixRaviartElement (const RefineableQCrouzeixRaviartElement< DIM > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
build_fp_press_adv_diff_robin_bc_element()
template<unsigned DIM>
void oomph::RefineableQCrouzeixRaviartElement< DIM >::build_fp_press_adv_diff_robin_bc_element (const unsigned & face_index) [inline], [virtual]
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
Definition at line 1246 of file refineable_navier_stokes_elements.h.
References oomph::NavierStokesEquations< DIM >::Pressure_advection_diffusion_robin_element_pt.
further_build() [1/3]
template<unsigned DIM>
void oomph::RefineableQCrouzeixRaviartElement< DIM >::further_build () [inline], [virtual]
Further build for Crouzeix_Raviart interpolates the internal pressure dofs from father element: Make sure pressure values and dp/ds agree between fathers and sons at the midpoints of the son elements. This must be specialised for each dimension.
Reimplemented from oomph::RefineableNavierStokesEquations< DIM >.
Referenced by oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::further_build().
further_build() [2/3]
void oomph::RefineableQCrouzeixRaviartElement< 2 >::further_build () [inline], [virtual]
2D Further build for Crouzeix_Raviart interpolates the internal pressure dofs from father element: Make sure pressure values and dp/ds agree between fathers and sons at the midpoints of the son elements.
Reimplemented from oomph::RefineableNavierStokesEquations< DIM >.
Definition at line 1925 of file refineable_navier_stokes_elements.h.
References oomph::RefineableNavierStokesEquations< DIM >::further_build(), i, oomph::GeneralisedElement::internal_data_pt(), oomph::NavierStokesEquations< DIM >::interpolated_p_nst(), oomph::QuadTreeNames::NE, oomph::QuadTreeNames::NW, oomph::QuadTreeNames::SE, oomph::QuadTreeNames::SW, and oomph::Data::value().
further_build() [3/3]
void oomph::RefineableQCrouzeixRaviartElement< 3 >::further_build () [inline], [virtual]
3D Further build for Crouzeix_Raviart interpolates the internal pressure dofs from father element: Make sure pressure values and dp/ds agree between fathers and sons at the midpoints of the son elements.
Reimplemented from oomph::RefineableNavierStokesEquations< DIM >.
Definition at line 1998 of file refineable_navier_stokes_elements.h.
References oomph::OcTree::Direction_to_vector, oomph::RefineableNavierStokesEquations< DIM >::further_build(), i, oomph::GeneralisedElement::internal_data_pt(), oomph::NavierStokesEquations< DIM >::interpolated_p_nst(), and oomph::Data::value().
further_setup_hanging_nodes()
template<unsigned DIM>
void oomph::RefineableQCrouzeixRaviartElement< DIM >::further_setup_hanging_nodes () [inline], [virtual]
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty.
Reimplemented from oomph::RefineableElement.
Definition at line 1234 of file refineable_navier_stokes_elements.h.
Referenced by oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::further_setup_hanging_nodes().
get_interpolated_values() [1/2]
template<unsigned DIM>
void oomph::RefineableQCrouzeixRaviartElement< DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get all function values [u,v..,p] at previous timestep t (t=0: present; t>0: previous timestep).
Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Note: No pressure history is kept, so pressure is always the current value.
Implements oomph::RefineableElement.
Definition at line 1200 of file refineable_navier_stokes_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::shape(), and oomph::NavierStokesEquations< DIM >::u_index_nst().
get_interpolated_values() [2/2]
template<unsigned DIM>
void oomph::RefineableQCrouzeixRaviartElement< DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 1178 of file refineable_navier_stokes_elements.h.
References i, and oomph::NavierStokesEquations< DIM >::interpolated_u_nst().
Referenced by oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::get_interpolated_values().
identify_load_data()
template<unsigned DIM>
void oomph::RefineableQCrouzeixRaviartElement< DIM >::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data) [inline], [virtual]
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function. (Overloads non-refineable version and takes hanging nodes into account)
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
Definition at line 1263 of file refineable_navier_stokes_elements.h.
References oomph::Node::hanging_pt(), i, oomph::GeneralisedElement::internal_data_pt(), oomph::Node::is_hanging(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::QCrouzeixRaviartElement< DIM >::npres_nst(), oomph::QCrouzeixRaviartElement< DIM >::P_nst_internal_index, and oomph::NavierStokesEquations< DIM >::u_index_nst().
ncont_interpolated_values()
template<unsigned DIM>
unsigned oomph::RefineableQCrouzeixRaviartElement< DIM >::ncont_interpolated_values () const [inline], [virtual]
Broken assignment operator.
Number of continuously interpolated values: DIM (velocities)
Implements oomph::RefineableElement.
Definition at line 1146 of file refineable_navier_stokes_elements.h.
nrecovery_order()
template<unsigned DIM>
unsigned oomph::RefineableQCrouzeixRaviartElement< DIM >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 1157 of file refineable_navier_stokes_elements.h.
Referenced by oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::nrecovery_order().
nvertex_node()
template<unsigned DIM>
unsigned oomph::RefineableQCrouzeixRaviartElement< DIM >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 1163 of file refineable_navier_stokes_elements.h.
References oomph::FiniteElement::nvertex_node().
rebuild_from_sons() [1/3]
template<unsigned DIM>
void oomph::RefineableQCrouzeixRaviartElement< DIM >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
Rebuild from sons: Reconstruct pressure from the (merged) sons This must be specialised for each dimension.
Implements oomph::RefineableElement.
Referenced by oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::rebuild_from_sons().
rebuild_from_sons() [2/3]
void oomph::RefineableQCrouzeixRaviartElement< 2 >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
2D Rebuild from sons: Reconstruct pressure from the (merged) sons
Implements oomph::RefineableElement.
Definition at line 1606 of file refineable_navier_stokes_elements.h.
References oomph::QuadTreeNames::NE, oomph::QuadTreeNames::NW, oomph::QuadTreeNames::SE, and oomph::QuadTreeNames::SW.
rebuild_from_sons() [3/3]
void oomph::RefineableQCrouzeixRaviartElement< 3 >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
3D Rebuild from sons: Reconstruct pressure from the (merged) sons
Implements oomph::RefineableElement.
Definition at line 1714 of file refineable_navier_stokes_elements.h.
References oomph::OcTreeNames::LDB, oomph::OcTreeNames::LDF, oomph::OcTreeNames::LUB, oomph::OcTreeNames::LUF, oomph::OcTreeNames::RDB, oomph::OcTreeNames::RDF, oomph::OcTreeNames::RUB, and oomph::OcTreeNames::RUF.
unpin_elemental_pressure_dofs()
template<unsigned DIM>
void oomph::RefineableQCrouzeixRaviartElement< DIM >::unpin_elemental_pressure_dofs () [inline], [private], [virtual]
Unpin all internal pressure dofs.
Implements oomph::RefineableNavierStokesEquations< DIM >.
Definition at line 1112 of file refineable_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), oomph::QCrouzeixRaviartElement< DIM >::npres_nst(), oomph::QCrouzeixRaviartElement< DIM >::P_nst_internal_index, and oomph::Data::unpin().
vertex_node_pt()
template<unsigned DIM>
Node * oomph::RefineableQCrouzeixRaviartElement< DIM >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 1169 of file refineable_navier_stokes_elements.h.
References oomph::FiniteElement::vertex_node_pt().
The documentation for this class was generated from the following file:
refineable_navier_stokes_elements.h