oomph::RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D > Class Template Reference
Refineable version of QSUPGAdvectionDiffusionElement. Inherit from the standard QSUPGAdvectionDiffusionElement and the appropriate refineable geometric element and the refineable equations.
#include <supg_advection_diffusion_elements.h>
Public Member Functions
RefineableQSUPGAdvectionDiffusionElement ()
Constructor: Pass refinement level to refineable quad element (default 0 = root)
RefineableQSUPGAdvectionDiffusionElement (const RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D > &dummy)
Broken copy constructor.
void operator= (const RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D > &)
Broken assignment operator.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: 1.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: empty.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
void further_setup_hanging_nodes ()
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty.
Additional Inherited Members
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D >
Refineable version of QSUPGAdvectionDiffusionElement. Inherit from the standard QSUPGAdvectionDiffusionElement and the appropriate refineable geometric element and the refineable equations.
Definition at line 265 of file supg_advection_diffusion_elements.h.
Constructor & Destructor Documentation
RefineableQSUPGAdvectionDiffusionElement() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::RefineableQSUPGAdvectionDiffusionElement () [inline]
Constructor: Pass refinement level to refineable quad element (default 0 = root)
Definition at line 273 of file supg_advection_diffusion_elements.h.
RefineableQSUPGAdvectionDiffusionElement() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::RefineableQSUPGAdvectionDiffusionElement (const RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 283 of file supg_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
further_setup_hanging_nodes()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::further_setup_hanging_nodes () [inline], [virtual]
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty.
Reimplemented from oomph::RefineableElement.
Definition at line 326 of file supg_advection_diffusion_elements.h.
ncont_interpolated_values()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values: 1.
Implements oomph::RefineableElement.
Definition at line 297 of file supg_advection_diffusion_elements.h.
nrecovery_order()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 319 of file supg_advection_diffusion_elements.h.
nvertex_node()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 303 of file supg_advection_diffusion_elements.h.
References oomph::FiniteElement::nvertex_node().
operator=()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::operator= (const RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D > &) [inline]
Broken assignment operator.
Definition at line 290 of file supg_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_assign().
rebuild_from_sons()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
Rebuild from sons: empty.
Implements oomph::RefineableElement.
Definition at line 315 of file supg_advection_diffusion_elements.h.
vertex_node_pt()
template<unsigned DIM, unsigned NNODE_1D>
Node* oomph::RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 309 of file supg_advection_diffusion_elements.h.
References oomph::FiniteElement::vertex_node_pt().
The documentation for this class was generated from the following file:
supg_advection_diffusion_elements.h