oomph::RefineableSphericalAdvectionDiffusionEquations Class Reference
A version of the Advection Diffusion in spherical coordinates equations that can be used with non-uniform mesh refinement. In essence, the class overloads the fill_in_generic_residual_contribution_spherical_adv_diff() function so that contributions from hanging nodes (or alternatively in-compatible function values) are taken into account.
#include <refineable_spherical_advection_diffusion_elements.h>
Public Member Functions
RefineableSphericalAdvectionDiffusionEquations ()
Empty Constructor.
RefineableSphericalAdvectionDiffusionEquations (const RefineableSphericalAdvectionDiffusionEquations &dummy)
Broken copy constructor.
void operator= (const RefineableSphericalAdvectionDiffusionEquations &)
Broken assignment operator.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Standard flux.from AdvectionDiffusion equations.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
double geometric_jacobian (const Vector< double > &x)
Fill in the geometric Jacobian, which in this case is r*r*sin(theta)
void further_build ()
Further build: Copy source function pointer from father element.
void dinterpolated_u_adv_diff_ddata (const Vector< double > &s, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information.
Protected Member Functions
void fill_in_generic_residual_contribution_spherical_adv_diff (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Add the element's contribution to the elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Additional Inherited Members
Detailed Description
A version of the Advection Diffusion in spherical coordinates equations that can be used with non-uniform mesh refinement. In essence, the class overloads the fill_in_generic_residual_contribution_spherical_adv_diff() function so that contributions from hanging nodes (or alternatively in-compatible function values) are taken into account.
Definition at line 54 of file refineable_spherical_advection_diffusion_elements.h.
Constructor & Destructor Documentation
RefineableSphericalAdvectionDiffusionEquations() [1/2]
oomph::RefineableSphericalAdvectionDiffusionEquations::RefineableSphericalAdvectionDiffusionEquations () [inline]
Empty Constructor.
Definition at line 61 of file refineable_spherical_advection_diffusion_elements.h.
RefineableSphericalAdvectionDiffusionEquations() [2/2]
oomph::RefineableSphericalAdvectionDiffusionEquations::RefineableSphericalAdvectionDiffusionEquations (const RefineableSphericalAdvectionDiffusionEquations & dummy) [inline]
Broken copy constructor.
Definition at line 70 of file refineable_spherical_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dinterpolated_u_adv_diff_ddata()
void oomph::RefineableSphericalAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata (const Vector< double > & s, Vector< double > & du_ddata, Vector< unsigned > & global_eqn_number) [inline], [virtual]
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information.
Reimplemented from oomph::SphericalAdvectionDiffusionEquations.
Definition at line 210 of file refineable_spherical_advection_diffusion_elements.h.
References oomph::Data::eqn_number(), oomph::Node::hanging_pt(), oomph::Node::is_hanging(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::shape(), and oomph::SphericalAdvectionDiffusionEquations::u_index_spherical_adv_diff().
fill_in_generic_residual_contribution_spherical_adv_diff()
void oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [protected], [virtual]
Add the element's contribution to the elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Add the element's contribution to the elemental residual vector and/or elemental jacobian matrix. This function overloads the standard version so that the possible presence of hanging nodes is taken into account.
Reimplemented from oomph::SphericalAdvectionDiffusionEquations.
Definition at line 37 of file refineable_spherical_advection_diffusion_elements.cc.
References oomph::SphericalAdvectionDiffusionEquations::dshape_and_dtest_eulerian_at_knot_spherical_adv_diff(), oomph::SphericalAdvectionDiffusionEquations::du_dt_spherical_adv_diff(), oomph::SphericalAdvectionDiffusionEquations::get_source_spherical_adv_diff(), oomph::SphericalAdvectionDiffusionEquations::get_wind_spherical_adv_diff(), oomph::Node::hanging_pt(), i, oomph::FiniteElement::integral_pt(), interpolated_u(), oomph::FiniteElement::interpolated_x(), oomph::Node::is_hanging(), oomph::Integral::knot(), oomph::RefineableElement::local_hang_eqn(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), oomph::SphericalAdvectionDiffusionEquations::pe(), oomph::SphericalAdvectionDiffusionEquations::pe_st(), residuals(), s, oomph::Data::time_stepper_pt(), oomph::SphericalAdvectionDiffusionEquations::u_index_spherical_adv_diff(), oomph::QuadTreeNames::W, oomph::Integral::weight(), and oomph::TimeStepper::weight().
further_build()
void oomph::RefineableSphericalAdvectionDiffusionEquations::further_build () [inline], [virtual]
Further build: Copy source function pointer from father element.
Reimplemented from oomph::RefineableElement.
Definition at line 188 of file refineable_spherical_advection_diffusion_elements.h.
References oomph::RefineableElement::father_element_pt(), oomph::SphericalAdvectionDiffusionEquations::pe_pt(), oomph::SphericalAdvectionDiffusionEquations::Pe_pt, oomph::SphericalAdvectionDiffusionEquations::pe_st_pt(), oomph::SphericalAdvectionDiffusionEquations::PeSt_pt, oomph::SphericalAdvectionDiffusionEquations::source_fct_pt(), oomph::SphericalAdvectionDiffusionEquations::Source_fct_pt, oomph::SphericalAdvectionDiffusionEquations::wind_fct_pt(), and oomph::SphericalAdvectionDiffusionEquations::Wind_fct_pt.
geometric_jacobian()
double oomph::RefineableSphericalAdvectionDiffusionEquations::geometric_jacobian (const Vector< double > & x) [inline], [virtual]
Fill in the geometric Jacobian, which in this case is r*r*sin(theta)
Reimplemented from oomph::ElementWithZ2ErrorEstimator.
Definition at line 182 of file refineable_spherical_advection_diffusion_elements.h.
get_interpolated_values() [1/2]
void oomph::RefineableSphericalAdvectionDiffusionEquations::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 133 of file refineable_spherical_advection_diffusion_elements.h.
References get_interpolated_values(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), oomph::Global_string_for_annotation::string(), t, oomph::SphericalAdvectionDiffusionEquations::u_index_spherical_adv_diff(), and values.
get_interpolated_values() [2/2]
void oomph::RefineableSphericalAdvectionDiffusionEquations::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 101 of file refineable_spherical_advection_diffusion_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), oomph::SphericalAdvectionDiffusionEquations::u_index_spherical_adv_diff(), and values.
Referenced by get_interpolated_values().
get_Z2_flux()
void oomph::RefineableSphericalAdvectionDiffusionEquations::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Standard flux.from AdvectionDiffusion equations.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 91 of file refineable_spherical_advection_diffusion_elements.h.
References oomph::SphericalAdvectionDiffusionEquations::get_flux().
num_Z2_flux_terms()
unsigned oomph::RefineableSphericalAdvectionDiffusionEquations::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 84 of file refineable_spherical_advection_diffusion_elements.h.
operator=()
void oomph::RefineableSphericalAdvectionDiffusionEquations::operator= (const RefineableSphericalAdvectionDiffusionEquations &) [inline]
Broken assignment operator.
Definition at line 77 of file refineable_spherical_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_assign().
The documentation for this class was generated from the following files:
refineable_spherical_advection_diffusion_elements.h
refineable_spherical_advection_diffusion_elements.cc