oomph::NavierStokesSurfacePowerElement< ELEMENT > Class Template Reference
A class of elements that allow the determination of the power input and various other fluxes over the domain boundaries. The element operates as a FaceElement and attaches itself to a bulk element of the type specified by the template argument.
#include <navier_stokes_surface_power_elements.h>
Public Member Functions
NavierStokesSurfacePowerElement (FiniteElement *const &element_pt, const int &face_index)
Constructor, which takes a `bulk` element and the value of the index and its limit.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default This final over-ride is required for cases where the FaceElement is a SolidFiniteElement because both SolidFiniteElements and FaceElements overload zeta_nodal.
Vector< double > drag_force ()
Get drag force (traction acting on fluid)
Vector< double > drag_force (std::ofstream &outfile)
Get drag force (traction acting on fluid) Doc in outfile.
double get_rate_of_traction_work ()
Get integral of instantaneous rate of work done by the traction that's exerted onto the fluid.
double get_rate_of_traction_work (std::ofstream &outfile)
Get integral of instantaneous rate of work done by the traction that's exerted onto the fluid. Doc in outfile.
void get_rate_of_traction_work_components (double &rate_of_work_integral_p, double &rate_of_work_integral_n, double &rate_of_work_integral_t)
Get integral of instantaneous rate of work done by the traction that's exerted onto the fluid, decomposed into pressure and normal and tangential viscous components.
void get_rate_of_traction_work_components (std::ofstream &outfile, double &rate_of_work_integral_p, double &rate_of_work_integral_n, double &rate_of_work_integral_t)
Get integral of instantaneous rate of work done by the traction that's exerted onto the fluid, decomposed into pressure and normal and tangential viscous components. Doc in outfile.
double get_kinetic_energy_flux ()
Get integral of kinetic energy flux.
double get_kinetic_energy_flux (std::ofstream &outfile)
Get integral of kinetic energy flux and doc.
double get_volume_flux ()
Get integral of volume flux.
double get_volume_flux (std::ofstream &outfile)
Get integral of volume flux and doc.
Private Attributes
unsigned Dim
The highest dimension of the problem.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::NavierStokesSurfacePowerElement< ELEMENT >
A class of elements that allow the determination of the power input and various other fluxes over the domain boundaries. The element operates as a FaceElement and attaches itself to a bulk element of the type specified by the template argument.
Definition at line 50 of file navier_stokes_surface_power_elements.h.
Constructor & Destructor Documentation
NavierStokesSurfacePowerElement()
template<class ELEMENT >
oomph::NavierStokesSurfacePowerElement< ELEMENT >::NavierStokesSurfacePowerElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit.
Definition at line 56 of file navier_stokes_surface_power_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::Dim, oomph::FaceElement::face_index(), oomph::Node::ndim(), and oomph::FiniteElement::node_pt().
Member Function Documentation
drag_force() [1/2]
template<class ELEMENT >
Vector< double > oomph::NavierStokesSurfacePowerElement< ELEMENT >::drag_force () [inline]
Get drag force (traction acting on fluid)
Definition at line 84 of file navier_stokes_surface_power_elements.h.
References oomph::NavierStokesSurfacePowerElement< ELEMENT >::drag_force().
Referenced by oomph::NavierStokesSurfacePowerElement< ELEMENT >::drag_force().
drag_force() [2/2]
template<class ELEMENT >
Vector< double > oomph::NavierStokesSurfacePowerElement< ELEMENT >::drag_force (std::ofstream & outfile) [inline]
Get drag force (traction acting on fluid) Doc in outfile.
Definition at line 93 of file navier_stokes_surface_power_elements.h.
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), oomph::FaceElement::get_local_coordinate_in_bulk(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::FaceElement::J_eulerian(), oomph::Integral::knot(), oomph::GeomObject::ndim(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
get_kinetic_energy_flux() [1/2]
template<class ELEMENT >
double oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_kinetic_energy_flux () [inline]
Get integral of kinetic energy flux.
Definition at line 563 of file navier_stokes_surface_power_elements.h.
References oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_kinetic_energy_flux().
Referenced by oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_kinetic_energy_flux().
get_kinetic_energy_flux() [2/2]
template<class ELEMENT >
double oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_kinetic_energy_flux (std::ofstream & outfile) [inline]
Get integral of kinetic energy flux and doc.
Definition at line 571 of file navier_stokes_surface_power_elements.h.
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), oomph::FaceElement::get_local_coordinate_in_bulk(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::FaceElement::J_eulerian(), oomph::Integral::knot(), oomph::GeomObject::ndim(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
get_rate_of_traction_work() [1/2]
template<class ELEMENT >
double oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work () [inline]
Get integral of instantaneous rate of work done by the traction that's exerted onto the fluid.
Definition at line 217 of file navier_stokes_surface_power_elements.h.
References oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work().
Referenced by oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work().
get_rate_of_traction_work() [2/2]
template<class ELEMENT >
double oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work (std::ofstream & outfile) [inline]
Get integral of instantaneous rate of work done by the traction that's exerted onto the fluid. Doc in outfile.
Definition at line 226 of file navier_stokes_surface_power_elements.h.
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), oomph::FaceElement::get_local_coordinate_in_bulk(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::FaceElement::J_eulerian(), oomph::Integral::knot(), oomph::GeomObject::ndim(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
get_rate_of_traction_work_components() [1/2]
template<class ELEMENT >
void oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work_components (double & rate_of_work_integral_p, double & rate_of_work_integral_n, double & rate_of_work_integral_t) [inline]
Get integral of instantaneous rate of work done by the traction that's exerted onto the fluid, decomposed into pressure and normal and tangential viscous components.
Definition at line 370 of file navier_stokes_surface_power_elements.h.
References oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work_components().
Referenced by oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work_components().
get_rate_of_traction_work_components() [2/2]
template<class ELEMENT >
void oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work_components (std::ofstream & outfile, double & rate_of_work_integral_p, double & rate_of_work_integral_n, double & rate_of_work_integral_t) [inline]
Get integral of instantaneous rate of work done by the traction that's exerted onto the fluid, decomposed into pressure and normal and tangential viscous components. Doc in outfile.
Definition at line 385 of file navier_stokes_surface_power_elements.h.
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), oomph::FaceElement::get_local_coordinate_in_bulk(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::FaceElement::J_eulerian(), oomph::Integral::knot(), oomph::GeomObject::ndim(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
get_volume_flux() [1/2]
template<class ELEMENT >
double oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux () [inline]
Get integral of volume flux.
Definition at line 704 of file navier_stokes_surface_power_elements.h.
References oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux().
Referenced by oomph::NavierStokesFluxControlElement< ELEMENT >::get_volume_flux(), and oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux().
get_volume_flux() [2/2]
template<class ELEMENT >
double oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux (std::ofstream & outfile) [inline]
Get integral of volume flux and doc.
Definition at line 712 of file navier_stokes_surface_power_elements.h.
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), oomph::FaceElement::get_local_coordinate_in_bulk(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::FaceElement::J_eulerian(), oomph::Integral::knot(), oomph::GeomObject::ndim(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
zeta_nodal()
template<class ELEMENT >
double oomph::NavierStokesSurfacePowerElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default This final over-ride is required for cases where the FaceElement is a SolidFiniteElement because both SolidFiniteElements and FaceElements overload zeta_nodal.
Reimplemented from oomph::FaceElement.
Definition at line 75 of file navier_stokes_surface_power_elements.h.
References i, and oomph::FaceElement::zeta_nodal().
Member Data Documentation
Dim
template<class ELEMENT >
unsigned oomph::NavierStokesSurfacePowerElement< ELEMENT >::Dim [private]
The highest dimension of the problem.
Definition at line 840 of file navier_stokes_surface_power_elements.h.
Referenced by oomph::NavierStokesSurfacePowerElement< ELEMENT >::NavierStokesSurfacePowerElement().
The documentation for this class was generated from the following file:
navier_stokes_surface_power_elements.h