oomph::QElementBase Class Reference
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
#include <Qelements.h>
Public Member Functions
QElementBase ()
Constructor: Initialise pointers to macro element reference coords.
QElementBase (const QElementBase &)=delete
Broken copy constructor.
virtual ~QElementBase ()
Broken assignment operator.
bool local_coord_is_valid (const Vector< double > &s)
Check whether the local coordinate are valid or not.
void move_local_coord_back_into_element (Vector< double > &s) const
Adjust local coordinates so that they're located inside the element.
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
Set pointer to macro element also sets up storage for the reference coordinates and initialises them.
double & s_macro_ll (const unsigned &i)
Access fct to the i-th coordinate of the element's `lower left` vertex in the associated MacroElement.
double & s_macro_ur (const unsigned &i)
Access fct to the i-th coordinate of the element's `upper right` vertex in the associated MacroElement.
double s_macro_ll (const unsigned &i) const
Access fct to the i-th coordinate of the element's `lower left` vertex in the associated MacroElement. (const version)
double s_macro_ur (const unsigned &i) const
Access fct to the i-th coordinate of the element's `upper right` vertex in the associated MacroElement. (const version)
void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
Global coordinates as function of local coordinates. using the macro element representation.
void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
Global coordinates as function of local coordinates at previous time `level` t (t=0: present; t>0: previous) using the macro element representation.
unsigned nnode_on_face () const
Return number of nodes on one face of the element. Always nnode_1d^(el_dim - 1).
ElementGeometry::ElementGeometry element_geometry () const
It's a Q element!
Private Attributes
Vector< double > * S_macro_ll_pt
Pointer to vector of lower left vertex coords. in macro element.
Vector< double > * S_macro_ur_pt
Pointer to vector of upper right vertex coords. in macro element.
Additional Inherited Members
Detailed Description
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
Base class for Qelements
Definition at line 90 of file Qelements.h.
Constructor & Destructor Documentation
QElementBase() [1/2]
oomph::QElementBase::QElementBase () [inline]
Constructor: Initialise pointers to macro element reference coords.
Definition at line 94 of file Qelements.h.
QElementBase() [2/2]
oomph::QElementBase::QElementBase (const QElementBase &) [delete]
Broken copy constructor.
 QElementBase()
virtual oomph::QElementBase::~QElementBase () [inline], [virtual]
Broken assignment operator.
Destructor: Kill storage for macro element reference coords
Definition at line 103 of file Qelements.h.
References S_macro_ll_pt, and S_macro_ur_pt.
Member Function Documentation
element_geometry()
ElementGeometry::ElementGeometry oomph::QElementBase::element_geometry () const [inline], [virtual]
It's a Q element!
Reimplemented from oomph::FiniteElement.
Definition at line 307 of file Qelements.h.
References oomph::ElementGeometry::Q.
get_x_from_macro_element() [1/2]
void oomph::QElementBase::get_x_from_macro_element (const unsigned & t, const Vector< double > & s, Vector< double > & x) [inline], [virtual]
Global coordinates as function of local coordinates at previous time `level` t (t=0: present; t>0: previous) using the macro element representation.
Reimplemented from oomph::FiniteElement.
Definition at line 274 of file Qelements.h.
References oomph::FiniteElement::dim(), i, oomph::FiniteElement::Macro_elem_pt, oomph::MacroElement::macro_map(), s, s_macro_ll(), s_macro_ur(), and t.
get_x_from_macro_element() [2/2]
void oomph::QElementBase::get_x_from_macro_element (const Vector< double > & s, Vector< double > & x) const [inline], [virtual]
Global coordinates as function of local coordinates. using the macro element representation.
Reimplemented from oomph::FiniteElement.
Definition at line 249 of file Qelements.h.
References oomph::FiniteElement::dim(), i, oomph::FiniteElement::Macro_elem_pt, oomph::MacroElement::macro_map(), s, s_macro_ll(), and s_macro_ur().
local_coord_is_valid()
bool oomph::QElementBase::local_coord_is_valid (const Vector< double > & s) [inline], [virtual]
Check whether the local coordinate are valid or not.
Reimplemented from oomph::FiniteElement.
Definition at line 113 of file Qelements.h.
References oomph::FiniteElement::dim(), i, s, oomph::FiniteElement::s_max(), and oomph::FiniteElement::s_min().
move_local_coord_back_into_element()
void oomph::QElementBase::move_local_coord_back_into_element (Vector< double > & s) const [inline], [virtual]
Adjust local coordinates so that they're located inside the element.
Reimplemented from oomph::FiniteElement.
Definition at line 129 of file Qelements.h.
References oomph::FiniteElement::dim(), i, s, oomph::FiniteElement::s_max(), and oomph::FiniteElement::s_min().
nnode_on_face()
unsigned oomph::QElementBase::nnode_on_face () const [inline], [virtual]
Return number of nodes on one face of the element. Always nnode_1d^(el_dim - 1).
Reimplemented from oomph::FiniteElement.
Definition at line 299 of file Qelements.h.
References oomph::FiniteElement::dim(), and oomph::FiniteElement::nnode_1d().
s_macro_ll() [1/2]
double & oomph::QElementBase::s_macro_ll (const unsigned & i) [inline]
Access fct to the i-th coordinate of the element's `lower left` vertex in the associated MacroElement.
Definition at line 186 of file Qelements.h.
References i, and S_macro_ll_pt.
Referenced by oomph::RefineableQElement< 3 >::build(), oomph::RefineableSolidQElement< 3 >::build(), oomph::RefineableQElement< 1 >::build(), oomph::RefineableQElement< 2 >::build(), oomph::RefineableSolidQElement< 2 >::build(), oomph::ExtrudedCubeMeshFromQuadMesh< ELEMENT >::build_mesh(), oomph::Multi_domain_functions::construct_new_external_halo_master_node_helper(), oomph::Missing_masters_functions::construct_new_external_halo_master_node_helper(), oomph::Multi_domain_functions::create_external_halo_elements(), oomph::Missing_masters_functions::get_required_master_nodal_information_helper(), oomph::Multi_domain_functions::get_required_master_nodal_information_helper(), oomph::QSolidElementBase::get_x_and_xi(), get_x_from_macro_element(), oomph::Multi_domain_functions::locate_zeta_for_missing_coordinates(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::pre_build(), and set_macro_elem_pt().
s_macro_ll() [2/2]
double oomph::QElementBase::s_macro_ll (const unsigned & i) const [inline]
Access fct to the i-th coordinate of the element's `lower left` vertex in the associated MacroElement. (const version)
Definition at line 218 of file Qelements.h.
References i, and S_macro_ll_pt.
s_macro_ur() [1/2]
double & oomph::QElementBase::s_macro_ur (const unsigned & i) [inline]
Access fct to the i-th coordinate of the element's `upper right` vertex in the associated MacroElement.
Definition at line 202 of file Qelements.h.
References i, and S_macro_ur_pt.
Referenced by oomph::RefineableQElement< 3 >::build(), oomph::RefineableSolidQElement< 3 >::build(), oomph::RefineableQElement< 1 >::build(), oomph::RefineableQElement< 2 >::build(), oomph::RefineableSolidQElement< 2 >::build(), oomph::ExtrudedCubeMeshFromQuadMesh< ELEMENT >::build_mesh(), oomph::Multi_domain_functions::construct_new_external_halo_master_node_helper(), oomph::Missing_masters_functions::construct_new_external_halo_master_node_helper(), oomph::Multi_domain_functions::create_external_halo_elements(), oomph::Missing_masters_functions::get_required_master_nodal_information_helper(), oomph::Multi_domain_functions::get_required_master_nodal_information_helper(), oomph::QSolidElementBase::get_x_and_xi(), get_x_from_macro_element(), oomph::Multi_domain_functions::locate_zeta_for_missing_coordinates(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::pre_build(), and set_macro_elem_pt().
s_macro_ur() [2/2]
double oomph::QElementBase::s_macro_ur (const unsigned & i) const [inline]
Access fct to the i-th coordinate of the element's `upper right` vertex in the associated MacroElement. (const version)
Definition at line 234 of file Qelements.h.
References i, and S_macro_ur_pt.
set_macro_elem_pt()
virtual void oomph::QElementBase::set_macro_elem_pt (MacroElement * macro_elem_pt) [inline], [virtual]
Set pointer to macro element also sets up storage for the reference coordinates and initialises them.
Call the corresponding function in the FiniteElement base class
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QSolidElementBase, oomph::RefineableSolidQElement< 3 >, oomph::RefineableSolidQElement< 1 >, and oomph::RefineableSolidQElement< 2 >.
Definition at line 143 of file Qelements.h.
References oomph::FiniteElement::dim(), i, oomph::FiniteElement::macro_elem_pt(), s_macro_ll(), S_macro_ll_pt, s_macro_ur(), S_macro_ur_pt, and oomph::FiniteElement::set_macro_elem_pt().
Referenced by oomph::QSolidElementBase::set_macro_elem_pt().
Member Data Documentation
S_macro_ll_pt
Vector<double>* oomph::QElementBase::S_macro_ll_pt [private]
Pointer to vector of lower left vertex coords. in macro element.
Definition at line 314 of file Qelements.h.
Referenced by s_macro_ll(), set_macro_elem_pt(), and ~QElementBase().
S_macro_ur_pt
Vector<double>* oomph::QElementBase::S_macro_ur_pt [private]
Pointer to vector of upper right vertex coords. in macro element.
Definition at line 317 of file Qelements.h.
Referenced by s_macro_ur(), set_macro_elem_pt(), and ~QElementBase().
The documentation for this class was generated from the following file:
Qelements.h