oomph::RefineableMeshBase Class Reference
Base class for refineable meshes. Provides standardised interfaces for the following standard mesh adaptation routines:
#include <refineable_mesh.h>
Public Member Functions
bool adapt_flag ()
RefineableMeshBase ()
Constructor sets default values for refinement targets etc. and initialises pointer to spatial error estimator to NULL.
RefineableMeshBase (const RefineableMeshBase &dummy)=delete
Broken copy constructor.
void operator= (const RefineableMeshBase &)=delete
Broken assignment operator.
virtual ~RefineableMeshBase ()
Empty Destructor:
unsigned nrefined ()
Access fct for number of elements that were refined.
unsigned nunrefined ()
Access fct for number of elements that were unrefined.
unsigned & nrefinement_overruled ()
Number of elements that would have liked to be refined further but can't because they've reached the max. refinement level.
unsigned & max_keep_unrefined ()
Max. number of elements that we allow to remain unrefined if no other mesh adaptation is required (to avoid mesh-adaptations that would only unrefine a few elements and then force a new solve -- this can't be worth our while!)
virtual void doc_adaptivity_targets (std::ostream &outfile)
Doc the targets for mesh adaptation.
ErrorEstimator *& spatial_error_estimator_pt ()
Access to spatial error estimator.
ErrorEstimator * spatial_error_estimator_pt () const
Access to spatial error estimator (const version.
double & min_permitted_error ()
Access fct for min. error (i.e. (try to) merge elements if their error is smaller)
double & max_permitted_error ()
Access fct for max. error (i.e. split elements if their error is larger)
double & min_error ()
Access fct for min. actual error in present solution (i.e. before re-solve on adapted mesh)
double & max_error ()
Access fct for max. actual error in present solution (i.e. before re-solve on adapted mesh)
DocInfo *& doc_info_pt ()
Access fct for pointer to DocInfo.
void enable_adaptation ()
Enable adaptation.
void disable_adaptation ()
Disable adaptation.
void enable_p_adaptation ()
Enable adaptation.
void disable_p_adaptation ()
Disable adaptation.
void enable_additional_synchronisation_of_hanging_nodes ()
Enable additional synchronisation of hanging nodes.
void disable_additional_synchronisation_of_hanging_nodes ()
Disable additional synchronisation of hanging nodes.
bool is_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_p_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_additional_synchronisation_of_hanging_nodes_disabled () const
Return whether additional synchronisation is enabled.
DocInfo doc_info ()
Access fct for DocInfo.
virtual void adapt (const Vector< double > &elemental_error)=0
Adapt mesh: Refine elements whose error is lager than err_max and (try to) unrefine those whose error is smaller than err_min.
virtual void p_adapt (const Vector< double > &elemental_error)
p-adapt mesh: Refine elements whose error is lager than err_max and (try to) unrefine those whose error is smaller than err_min
virtual void refine_uniformly (DocInfo &doc_info)=0
Refine mesh uniformly and doc process.
virtual void refine_uniformly ()
Refine mesh uniformly.
virtual void p_refine_uniformly (DocInfo &doc_info)
p-refine mesh uniformly and doc process
virtual void p_refine_uniformly ()
p-refine mesh uniformly
virtual unsigned unrefine_uniformly ()=0
Unrefine mesh uniformly: Return 0 for success, 1 for failure (if unrefinement has reached the coarsest permitted level)
void p_unrefine_uniformly (DocInfo &doc_info)
p-unrefine mesh uniformly
Public Member Functions inherited from oomph::Mesh
void resize_halo_nodes ()
Helper function that resizes halo nodes to the same size as their non-halo counterparts if required. (A discrepancy can arise if a FaceElement that introduces additional unknowns are attached to a bulk element that shares a node with a haloed element. In that case the joint node between haloed and non-haloed element is resized on that processor but not on the one that holds the halo counterpart (because no FaceElement is attached to the halo element)
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
Constructor builds combined mesh from the meshes specified. Note: This simply merges the meshes' elements and nodes (ignoring duplicates; no boundary information etc. is created).
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
Merge meshes. Note: This simply merges the meshes' elements and nodes (ignoring duplicates; no boundary information etc. is created).
virtual void setup_boundary_element_info ()
Interface for function that is used to setup the boundary information (Empty virtual function -- implement this for specific Mesh classes)
virtual void setup_boundary_element_info (std::ostream &outfile)
Setup lookup schemes which establish whic elements are located next to mesh's boundaries. Doc in outfile (if it's open). (Empty virtual function -- implement this for specific Mesh classes)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned > > &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
Output boundary coordinates on boundary b -- template argument specifies the bulk element type (needed to create FaceElement of appropriate type on mesh boundary).
virtual void scale_mesh (const double &factor)
Scale all nodal coordinates by given factor. Virtual so it can be overloaded in SolidMesh class where it also re-assigns the Lagrangian coordinates.
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
Flush storage for elements and nodes by emptying the vectors that store the pointers to them. This is useful if a particular mesh is only built to generate a small part of a bigger mesh. Once the elements and nodes have been created, they are typically copied into the new mesh and the auxiliary mesh can be deleted. However, if we simply call the destructor of the auxiliary mesh, it will also wipe out the nodes and elements, because it still "thinks" it's in charge of these...
void flush_element_storage ()
Flush storage for elements (only) by emptying the vectors that store the pointers to them. This is useful if a particular mesh is only built to generate a small part of a bigger mesh. Once the elements and nodes have been created, they are typically copied into the new mesh and the auxiliary mesh can be deleted. However, if we simply call the destructor of the auxiliary mesh, it will also wipe out the nodes and elements, because it still "thinks" it's in charge of these...
void flush_node_storage ()
Flush storage for nodes (only) by emptying the vectors that store the pointers to them.
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Upcast (downcast?) to FiniteElement (needed to access FiniteElement member functions).
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
Remove all information about nodes stored on the b-th boundary of the mesh.
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
Replace existing boundary node lookup schemes with new schemes created using the boundary data stored in the nodes.
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
void set_boundary_coordinate_exists (const unsigned &i)
Set boundary coordinate on the i-th boundary to be existing.
void set_boundary_coordinate_does_not_exist (const unsigned &i)
Set boundary coordinate on the i-th boundary to be non-existing.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
Update nodal positions in response to changes in the domain shape. Uses the FiniteElement::get_x(...) function for FiniteElements and doesn't do anything for other element types. If a MacroElement pointer has been set for a FiniteElement, the MacroElement representation is used to update the nodal positions; if not get_x(...) uses the FE interpolation and thus leaves the nodal positions unchanged. Virtual, so it can be overloaded by specific meshes, such as AlgebraicMeshes or SpineMeshes. Generally, this function updates the position of all nodes in response to changes in the boundary position. However, we ignore all SolidNodes since their position is computed as part of the solution -- unless the bool flag is set to true. Such calls are typically made when the initial mesh is created and/or after a mesh has been refined repeatedly before the start of the computation.
virtual void reorder_nodes (const bool &use_old_ordering=true)
Re-order nodes in the order in which they appear in elements -- can be overloaded for more efficient re-ordering.
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
Get a reordering of the nodes in the order in which they appear in elements -- can be overloaded for more efficient re-ordering.
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
Constuct a Mesh of FACE_ELEMENTs along the b-th boundary of the mesh (which contains elements of type BULK_ELEMENT)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
Determine max and min area for all FiniteElements in the mesh (non-FiniteElements are ignored)
double total_size ()
Determine the sum of all "sizes" of the FiniteElements in the mesh (non-FiniteElements are ignored). This gives the length/area/volume occupied by the mesh.
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
Check for inverted elements and report outcome in boolean variable. This visits all elements at their integration points and checks if the Jacobian of the mapping between local and global coordinates is positive -- using the same test that would be carried out (but only in PARANOID mode) during the assembly of the elements' Jacobian matrices. Inverted elements are output in inverted_element_file (if the stream is open).
void check_inverted_elements (bool &mesh_has_inverted_elements)
Check for inverted elements and report outcome in boolean variable. This visits all elements at their integration points and checks if the Jacobian of the mapping between local and global coordinates is positive -- using the same test that would be carried out (but only in PARANOID mode) during the assembly of the elements' Jacobian matrices.
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Check for repeated nodes within a given spatial tolerance. Return (0/1) for (pass/fail).
Vector< Node * > prune_dead_nodes ()
Prune nodes. Nodes that have been marked as obsolete are removed from the mesh (and its boundary-node scheme). Returns vector of pointers to deleted nodes.
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
Find a node not on any boundary in mesh_pt (useful for pinning a single node in a purely Neumann problem so that it is fully determined).
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
For the e-th finite element on boundary b, return int to indicate the face_index of the face adjacent to the boundary. This is consistent with input required during the generation of FaceElements.
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
Output in paraview format into specified file. Breaks up each element into sub-elements for plotting purposes. We assume that all elements are of the same type (fct will break break (in paranoid mode) if paraview output fcts of the elements are inconsistent).
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
Output in paraview format into specified file. Breaks up each element into sub-elements for plotting purposes. We assume that all elements are of the same type (fct will break break (in paranoid mode) if paraview output fcts of the elements are inconsistent).
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
Output in paraview format into specified file. Breaks up each element into sub-elements for plotting purposes. We assume that all elements are of the same type (fct will break break (in paranoid mode) if paraview output fcts of the elements are inconsistent).
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
Output a given time-dep. Vector function at f(n_plot) points in each element.
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
Output the nodes on the boundaries (into separate tecplot zones). Specify filename.
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
Shift time-dependent data along for next timestep: Deal with nodal Data/positions and the element's internal Data.
void calculate_predictions ()
Calculate predictions for all Data and positions associated with the mesh, usually used in adaptive time-stepping.
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with all nodal and elemental data stored in the mesh.
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Function that can be used to set any additional timestepper data stored at the Mesh (as opposed to nodal and elemental) levels. This is virtual so that it can be overloaded in the appropriate Meshes. Examples include the SpineMeshes and adaptive triangle and tet meshes.
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the internal data stored within elements in the meah.
virtual void compute_norm (double &norm)
Compute norm of solution by summing contributions of compute_norm(...) for all constituent elements in the mesh. What that norm means depends on what's defined in the element's function; may need to take the square root afterwards if the elements compute the square of the L2 norm, say.
virtual void compute_norm (Vector< double > &norm)
Compute norm of solution by summing contributions of compute_norm(...) for all constituent elements in the mesh. What that norm means depends on what's defined in the element's function; may need to take the square root afterwards if the elements compute the square of the L2 norm, say.
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Plot error when compared against a given exact solution. Also returns the norm of the error and that of the exact solution.
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Plot error when compared against a given time-depdendent exact solution. Also returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Plot error when compared against a given time-dependent exact solution. Also returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
Plot error when compared against a given time-dependent exact solution. Also returns the norm of the error and that of the exact solution.
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
Plot error when compared against a given time-depdendent exact solution. Also returns the norm of the error and that of the exact solution. Version with vectors of norms and errors so that different variables' norms and errors can be returned individually.
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
Plot error when compared against a given time-depdendent exact solution. Also returns the norm of the error and that of the exact solution. Version with vectors of norms and errors so that different variables' norms and errors can be returned individually.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
Returns the norm of the error and that of the exact solution. Version with vectors of norms and errors so that different variables' norms and errors can be returned individually.
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
Read-only access fct to communicator (Null if mesh is not distributed, i.e. if we don't have mpi).
void set_communicator_pt (OomphCommunicator *comm_pt)
Function to set communicator (mesh is assumed to be distributed if the communicator pointer is non-null). Only defined if mpi is enabled becaus Comm_pt itself is only defined when mpi is enabled.
void set_keep_all_elements_as_halos ()
Call this function to keep all the elements as halo elements.
void unset_keep_all_elements_as_halos ()
Calll this function to unset the flag that keeps all elements in the mesh as halo elements.
virtual void distribute (OomphCommunicator *comm_pt, const Vector< unsigned > &element_domain, Vector< GeneralisedElement * > &deleted_element_pt, DocInfo &doc_info, const bool &report_stats, const bool &overrule_keep_as_halo_element_status)
Distribute the problem and doc; make this virtual to allow overloading for particular meshes where further work is required. Add to vector of pointers to deleted elements.
void distribute (OomphCommunicator *comm_pt, const Vector< unsigned > &element_domain, Vector< GeneralisedElement * > &deleted_element_pt, const bool &report_stats=false)
Distribute the problem Add to vector of pointers to deleted elements.
void prune_halo_elements_and_nodes (Vector< GeneralisedElement * > &deleted_element_pt, const bool &report_stats=false)
(Irreversibly) prune halo(ed) elements and nodes, usually after another round of refinement, to get rid of excessively wide halo layers. Note that the current mesh will be now regarded as the base mesh and no unrefinement relative to it will be possible once this function has been called.
void prune_halo_elements_and_nodes (Vector< GeneralisedElement * > &deleted_element_pt, DocInfo &doc_info, const bool &report_stats)
(Irreversibly) prune halo(ed) elements and nodes, usually after another round of refinement, to get rid of excessively wide halo layers. Note that the current mesh will be now regarded as the base mesh and no unrefinement relative to it will be possible once this function has been called.
void get_efficiency_of_mesh_distribution (double &av_efficiency, double &max_efficiency, double &min_efficiency)
Get efficiency of mesh distribution: In an ideal distribution without halo overhead, each processor would only hold its own elements. Efficieny per processor = (number of non-halo elements)/ (total number of elements).
void doc_mesh_distribution (DocInfo &doc_info)
Doc the mesh distribution, to be processed with tecplot macros.
void check_halo_schemes (DocInfo &doc_info, double &max_permitted_error_for_halo_check)
Check halo and shared schemes on the mesh.
virtual void classify_halo_and_haloed_nodes (DocInfo &doc_info, const bool &report_stats)
Classify the halo and haloed nodes in the mesh. Virtual so it can be overloaded to perform additional functionality (such as synchronising hanging nodes) in refineable meshes, say.
virtual void classify_halo_and_haloed_nodes (const bool &report_stats=false)
Classify the halo and haloed nodes in the mesh. Virtual so it can be overloaded to perform additional functionality (such as synchronising hanging nodes) in refineable meshes, say.
void synchronise_shared_nodes (const bool &report_stats)
Synchronise shared node lookup schemes to cater for the the case where: (1) a certain node on the current processor is halo with proc p (i.e. its non-halo counterpart lives on processor p) (2) that node is also exists (also as a halo) on another processor (q, say) where its non-halo counter part is also known to be on processor p. However, without calling this function the current processor does not necessarily know that it shares a node with processor q. This information can be required, e.g. when synchronising hanging node schemes over all processors.
void get_all_halo_data (std::map< unsigned, double * > &map_of_halo_data)
Get all the halo data stored in the mesh and add pointers to the data to the map, indexed by global equation number.
Vector< GeneralisedElement * > halo_element_pt (const unsigned &p)
Return vector of halo elements in this Mesh whose non-halo counterpart is held on processor p.
Vector< GeneralisedElement * > haloed_element_pt (const unsigned &p)
Return vector of haloed elements in this Mesh whose haloing counterpart is held on processor p.
unsigned nnon_halo_element ()
Total number of non-halo elements in this mesh (Costly call computes result on the fly)
unsigned nroot_halo_element ()
Total number of root halo elements in this Mesh.
unsigned nroot_halo_element (const unsigned &p)
Number of root halo elements in this Mesh whose non-halo counterpart is held on processor p.
Vector< GeneralisedElement * > root_halo_element_pt (const unsigned &p)
Vector of pointers to root halo elements in this Mesh whose non-halo counterpart is held on processor p.
GeneralisedElement *& root_halo_element_pt (const unsigned &p, const unsigned &e)
Access fct to the e-th root halo element in this Mesh whose non-halo counterpart is held on processor p.
void add_root_halo_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
Add root halo element whose non-halo counterpart is held on processor p to this Mesh.
unsigned nhalo_node ()
Total number of halo nodes in this Mesh.
unsigned nhalo_node (const unsigned &p)
Number of halo nodes in this Mesh whose non-halo counterpart is held on processor p.
void add_halo_node_pt (const unsigned &p, Node *&nod_pt)
Add halo node whose non-halo counterpart is held on processor p to the storage scheme for halo nodes.
Node * halo_node_pt (const unsigned &p, const unsigned &j)
Access fct to the j-th halo node in this Mesh whose non-halo counterpart is held on processor p.
unsigned nroot_haloed_element ()
Total number of root haloed elements in this Mesh.
unsigned nroot_haloed_element (const unsigned &p)
Number of root haloed elements in this Mesh whose non-halo counterpart is held on processor p.
Vector< GeneralisedElement * > root_haloed_element_pt (const unsigned &p)
Vector of pointers to root haloed elements in this Mesh whose non-halo counterpart is held on processor p.
GeneralisedElement *& root_haloed_element_pt (const unsigned &p, const unsigned &e)
Access fct to the e-th root haloed element in this Mesh whose non-halo counterpart is held on processor p.
void add_root_haloed_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
Add root haloed element whose non-halo counterpart is held on processor p to the storage scheme for haloed elements. Note: This does not add the element to the storage scheme for elements as it's understood to naturally live on this processor anyway!
unsigned nhaloed_node ()
Total number of haloed nodes in this Mesh.
unsigned nhaloed_node (const unsigned &p)
Number of haloed nodes in this Mesh whose haloed counterpart is held on processor p.
Node * haloed_node_pt (const unsigned &p, const unsigned &j)
Access fct to the j-th haloed node in this Mesh whose halo counterpart is held on processor p.
void add_haloed_node_pt (const unsigned &p, Node *&nod_pt)
Add haloed node whose halo counterpart is held on processor p to the storage scheme for haloed nodes.
void disable_resizing_of_halo_nodes ()
Function to suppress resizing of halo nodes -- optmisation but call it at your own risk!
void enable_resizing_of_halo_nodes ()
Function to (re-)enable resizing of halo nodes -- this returns things to the default behaviour.
void disable_output_of_halo_elements ()
Function to disable halo element output.
void enable_output_of_halo_elements ()
Function to enable halo element output.
unsigned nshared_node ()
Total number of shared nodes in this Mesh.
void doc_shared_nodes ()
Doc shared nodes.
unsigned nshared_node (const unsigned &p)
Number of shared nodes in this Mesh who have a counterpart on processor p.
Node * shared_node_pt (const unsigned &p, const unsigned &j)
Access fct to the j-th shared node in this Mesh who has a counterpart on processor p.
void get_shared_node_pt (const unsigned &p, Vector< Node * > &shared_node_pt)
Get vector of pointers to shared nodes with processor p. Required for faster search in Missing_masters_functions::add_external_haloed_node_helper() and Missing_masters_functions::add_external_haloed_master_node_helper()
void add_shared_node_pt (const unsigned &p, Node *&nod_pt)
Add shared node whose counterpart is held on processor p to the storage scheme for shared nodes. (NB: ensure that this routine is called twice, once for each process)
void get_halo_node_stats (double &av_number, unsigned &max_number, unsigned &min_number)
Get halo node stats for this distributed mesh: Average/max/min number of halo nodes over all processors. Careful: Involves MPI Broadcasts and must therefore be called on all processors!
void get_haloed_node_stats (double &av_number, unsigned &max_number, unsigned &min_number)
Get haloed node stats for this distributed mesh: Average/max/min number of haloed nodes over all processors. Careful: Involves MPI Broadcasts and must therefore be called on all processors!
void output_external_halo_elements (std::ostream &outfile, const unsigned &n_plot=5)
Output all external halo elements.
void output_external_halo_elements (const unsigned &p, std::ostream &outfile, const unsigned &n_plot=5)
Output all external halo elements with processor p.
void output_external_haloed_elements (std::ostream &outfile, const unsigned &n_plot=5)
Output all external haloed elements.
void output_external_haloed_elements (const unsigned &p, std::ostream &outfile, const unsigned &n_plot=5)
Output all external haloed elements with processor p.
unsigned nexternal_halo_element ()
Total number of external halo elements in this Mesh.
unsigned nexternal_halo_element (const unsigned &p)
Number of external halo elements in this Mesh whose non-halo counterpart is held on processor p.
GeneralisedElement *& external_halo_element_pt (const unsigned &p, const unsigned &e)
Access fct to the e-th external halo element in this Mesh whose non-halo counterpart is held on processor p.
void add_external_halo_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
Add external halo element whose non-halo counterpart is held on processor p to this Mesh.
unsigned nexternal_haloed_element ()
Total number of external haloed elements in this Mesh.
unsigned nexternal_haloed_element (const unsigned &p)
Number of external haloed elements in this Mesh whose non-halo counterpart is held on processor p.
GeneralisedElement *& external_haloed_element_pt (const unsigned &p, const unsigned &e)
Access fct to the e-th external haloed element in this Mesh whose non-halo counterpart is held on processor p.
unsigned add_external_haloed_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
Add external haloed element whose non-halo counterpart is held on processor p to the storage scheme for haloed elements.
unsigned nexternal_halo_node ()
Total number of external halo nodes in this Mesh.
void get_external_halo_node_pt (Vector< Node * > &external_halo_node_pt)
Get vector of pointers to all external halo nodes.
unsigned nexternal_halo_node (const unsigned &p)
Number of external halo nodes in this Mesh whose non-halo (external) counterpart is held on processor p.
void add_external_halo_node_pt (const unsigned &p, Node *&nod_pt)
Add external halo node whose non-halo (external) counterpart is held on processor p to the storage scheme for halo nodes.
Node *& external_halo_node_pt (const unsigned &p, const unsigned &j)
Access fct to the j-th external halo node in this Mesh whose non-halo external counterpart is held on processor p.
Vector< Node * > external_halo_node_pt (const unsigned &p)
Access fct to vector of external halo node in this Mesh whose non-halo external counterpart is held on processor p. (read only)
void set_external_halo_node_pt (const unsigned &p, const Vector< Node * > &external_halo_node_pt)
Set vector of external halo node in this Mesh whose non-halo external counterpart is held on processor p.
void null_external_halo_node (const unsigned &p, Node *nod_pt)
Null out specified external halo node (used when deleting duplicates)
void remove_null_pointers_from_external_halo_node_storage ()
Consolidate external halo node storage by removing nulled out pointes in external halo and haloed schemes.
unsigned nexternal_haloed_node ()
Total number of external haloed nodes in this Mesh.
unsigned nexternal_haloed_node (const unsigned &p)
Number of external haloed nodes in this Mesh whose halo (external) counterpart is held on processor p.
Node *& external_haloed_node_pt (const unsigned &p, const unsigned &j)
Access fct to the j-th external haloed node in this Mesh whose halo external counterpart is held on processor p.
unsigned add_external_haloed_node_pt (const unsigned &p, Node *&nod_pt)
Add external haloed node whose halo (external) counterpart is held on processor p to the storage scheme for haloed nodes.
Vector< Node * > external_haloed_node_pt (const unsigned &p)
Access fct to vector of external haloed node in this Mesh whose halo external counterpart is held on processor p. (read only)
void set_external_haloed_node_pt (const unsigned &p, const Vector< Node * > &external_haloed_node_pt)
Set vector of external haloed node in this Mesh whose halo external counterpart is held on processor p.
std::set< int > external_halo_proc ()
Return the set of processors that hold external halo nodes. This is required to avoid having to pass a communicator into the node_update functions for Algebraic-based and MacroElement-based Meshes.
virtual void create_shared_boundaries (OomphCommunicator *comm_pt, const Vector< unsigned > &element_domain, const Vector< GeneralisedElement * > &backed_up_el_pt, const Vector< FiniteElement * > &backed_up_f_el_pt, std::map< Data *, std::set< unsigned > > &processors_associated_with_data, const bool &overrule_keep_as_halo_element_status)
Creates the shared boundaries, only used in unstructured meshes In this case with the "TriangleMesh" class.
virtual unsigned try_to_add_root_haloed_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
virtual unsigned try_to_add_haloed_node_pt (const unsigned &p, Node *&nod_pt)
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Protected Attributes
ErrorEstimator * Spatial_error_estimator_pt
Pointer to spatial error estimator.
double Max_permitted_error
Max. error (i.e. split elements if their error is larger)
double Min_permitted_error
Min. error (i.e. (try to) merge elements if their error is smaller)
double Min_error
Min.actual error.
double Max_error
Max. actual error.
unsigned Nrefined
Stats: Number of elements that were refined.
unsigned Nunrefined
Stats: Number of elements that were unrefined.
bool Adapt_flag
Flag that requests adaptation.
bool P_adapt_flag
Flag that requests p-adaptation.
bool Additional_synchronisation_of_hanging_nodes_not_required
Flag that disables additional synchronisation of hanging nodes.
DocInfo * Doc_info_pt
Pointer to DocInfo.
unsigned Max_keep_unrefined
Max. number of elements that can remain unrefined if no other mesh adaptation is required (to avoid mesh-adaptations that would only unrefine a few elements and then force a new solve -- this can't be worth our while!)
unsigned Nrefinement_overruled
Number of elements that would like to be refined further but can't because they've reached the max. refinement level.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
Vector of Vector of pointers to nodes on the boundaries: Boundary_node_pt(b,n). Note that this is private to force the use of the add_boundary_node() function, which ensures that the reverse look-up schemes for the nodes are set up.
bool Lookup_for_elements_next_boundary_is_setup
Flag to indicate that the lookup schemes for elements that are adjacent to the boundaries has been set up.
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector of Vector of pointers to elements on the boundaries: Boundary_element_pt(b,e)
Vector< Vector< int > > Face_index_at_boundary
For the e-th finite element on boundary b, this is the index of the face that lies along that boundary.
std::map< unsigned, Vector< GeneralisedElement * > > Root_halo_element_pt
Map of vectors holding the pointers to the root halo elements.
std::map< unsigned, Vector< GeneralisedElement * > > Root_haloed_element_pt
Map of vectors holding the pointers to the root haloed elements.
std::map< unsigned, Vector< Node * > > Halo_node_pt
Map of vectors holding the pointers to the halo nodes.
std::map< unsigned, Vector< Node * > > Haloed_node_pt
Map of vectors holding the pointers to the haloed nodes.
std::map< unsigned, Vector< Node * > > Shared_node_pt
Map of vectors holding the pointers to the shared nodes. These are all the nodes that are on two "neighbouring" processes (the halo(ed) lookup scheme depends upon which processor is in charge.
OomphCommunicator * Comm_pt
Pointer to communicator -- set to NULL if mesh is not distributed.
std::map< unsigned, Vector< GeneralisedElement * > > External_halo_element_pt
External halo(ed) elements are created as and when they are needed to act as source elements for the particular process's mesh. The storage is wiped and rebuilt every time the mesh is refined.
std::map< unsigned, Vector< GeneralisedElement * > > External_haloed_element_pt
Map of vectors holding the pointers to the external haloed elements.
std::map< unsigned, Vector< Node * > > External_halo_node_pt
Map of vectors holding the pointers to the external halo nodes.
std::map< unsigned, Vector< Node * > > External_haloed_node_pt
Map of vectors holding the pointers to the external haloed nodes.
bool Keep_all_elements_as_halos
bool to indicate whether to keep all elements in a mesh as halos or not
bool Resize_halo_nodes_not_required
Set this to true to suppress resizing of halo nodes (at your own risk!)
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
Typedef for function pointer to function that computes steady exact solution.
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Typedef for function pointer to function that computes unsteady exact solution.
Public Attributes inherited from oomph::Mesh
bool Output_halo_elements
Bool for output of halo elements.
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
Default Steady Timestepper, to be used in default arguments to Mesh constructors.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Boolean used to control warning about empty mesh level timestepper function.
Protected Member Functions inherited from oomph::Mesh
void setup_shared_node_scheme ()
Setup shared node scheme.
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign the global equation numbers in the Data stored at the nodes and also internal element Data. Also, build (via push_back) the Vector of pointers to the dofs (variables).
void describe_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the dofs of the Mesh. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the local dofs of the elements. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers in all elements If the boolean argument is true then also store pointers to dofs.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
A function that upgrades an ordinary node to a boundary node We shouldn't ever really use this, but it does make life that bit easier for the lazy mesh writer. The pointer to the node is replaced by a pointer to the new boundary node in all element look-up schemes and in the mesh's Node_pt vector. The new node is also addressed by node_pt on return from the function.
void convert_to_boundary_node (Node *&node_pt)
A function that upgrades an ordinary node to a boundary node. All pointers to the node from the mesh's elements are found. and replaced by pointers to the new boundary node. If the node is present in the mesh's list of nodes, that pointer is also replaced. Finally, the pointer argument node_pt addresses the new node on return from the function. We shouldn't ever really use this, but it does make life that bit easier for the lazy mesh writer.
Detailed Description
Base class for refineable meshes. Provides standardised interfaces for the following standard mesh adaptation routines:
Uniform mesh refinement.
Adaptation, based on the elemental error estimates obtained from an error estimator function which is accessed via a function pointer.
Definition at line 47 of file refineable_mesh.h.
Constructor & Destructor Documentation
RefineableMeshBase() [1/2]
oomph::RefineableMeshBase::RefineableMeshBase () [inline]
Constructor sets default values for refinement targets etc. and initialises pointer to spatial error estimator to NULL.
Definition at line 57 of file refineable_mesh.h.
References Adapt_flag, Additional_synchronisation_of_hanging_nodes_not_required, Doc_info_pt, Max_error, Max_keep_unrefined, Max_permitted_error, Min_error, Min_permitted_error, Nrefinement_overruled, P_adapt_flag, and Spatial_error_estimator_pt.
RefineableMeshBase() [2/2]
oomph::RefineableMeshBase::RefineableMeshBase (const RefineableMeshBase & dummy) [delete]
Broken copy constructor.
~RefineableMeshBase()
virtual oomph::RefineableMeshBase::~RefineableMeshBase () [inline], [virtual]
Empty Destructor:
Definition at line 98 of file refineable_mesh.h.
Member Function Documentation
adapt()
virtual void oomph::RefineableMeshBase::adapt (const Vector< double > & elemental_error) [pure virtual]
Adapt mesh: Refine elements whose error is lager than err_max and (try to) unrefine those whose error is smaller than err_min.
Implemented in oomph::RefineableGmshTetMesh< ELEMENT >, oomph::RefineableQuadFromTriangleMesh< ELEMENT >, oomph::RefineableTetgenMesh< ELEMENT >, oomph::RefineableTriangleMesh< ELEMENT >, and oomph::TreeBasedRefineableMeshBase.
adapt_flag()
bool oomph::RefineableMeshBase::adapt_flag () [inline]
Definition at line 50 of file refineable_mesh.h.
References Adapt_flag.
disable_adaptation()
void oomph::RefineableMeshBase::disable_adaptation () [inline]
Disable adaptation.
Definition at line 195 of file refineable_mesh.h.
References Adapt_flag.
disable_additional_synchronisation_of_hanging_nodes()
void oomph::RefineableMeshBase::disable_additional_synchronisation_of_hanging_nodes () [inline]
Disable additional synchronisation of hanging nodes.
Definition at line 219 of file refineable_mesh.h.
References Additional_synchronisation_of_hanging_nodes_not_required.
disable_p_adaptation()
void oomph::RefineableMeshBase::disable_p_adaptation () [inline]
Disable adaptation.
Definition at line 207 of file refineable_mesh.h.
References P_adapt_flag.
doc_adaptivity_targets()
virtual void oomph::RefineableMeshBase::doc_adaptivity_targets (std::ostream & outfile) [inline], [virtual]
Doc the targets for mesh adaptation.
Reimplemented in oomph::TreeBasedRefineableMeshBase, oomph::RefineableTetMeshBase, and oomph::RefineableTriangleMesh< ELEMENT >.
Definition at line 129 of file refineable_mesh.h.
References Max_keep_unrefined, Max_permitted_error, and Min_permitted_error.
doc_info()
DocInfo oomph::RefineableMeshBase::doc_info () [inline]
Access fct for DocInfo.
Definition at line 243 of file refineable_mesh.h.
References Doc_info_pt.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt(), oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::TreeBasedRefineableMeshBase::classify_halo_and_haloed_nodes(), oomph::TreeBasedRefineableMeshBase::classify_halo_and_haloed_nodes(), oomph::TreeBasedRefineableMeshBase::p_adapt(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), p_refine_uniformly(), oomph::TreeBasedRefineableMeshBase::p_refine_uniformly(), oomph::TreeBasedRefineableMeshBase::p_unrefine_uniformly(), refine_uniformly(), and oomph::TreeBasedRefineableMeshBase::refine_uniformly().
doc_info_pt()
DocInfo *& oomph::RefineableMeshBase::doc_info_pt () [inline]
Access fct for pointer to DocInfo.
Definition at line 183 of file refineable_mesh.h.
References Doc_info_pt.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt(), and oomph::TreeBasedRefineableMeshBase::p_adapt().
enable_adaptation()
void oomph::RefineableMeshBase::enable_adaptation () [inline]
Enable adaptation.
Definition at line 189 of file refineable_mesh.h.
References Adapt_flag.
enable_additional_synchronisation_of_hanging_nodes()
void oomph::RefineableMeshBase::enable_additional_synchronisation_of_hanging_nodes () [inline]
Enable additional synchronisation of hanging nodes.
Definition at line 213 of file refineable_mesh.h.
References Additional_synchronisation_of_hanging_nodes_not_required.
enable_p_adaptation()
void oomph::RefineableMeshBase::enable_p_adaptation () [inline]
Enable adaptation.
Definition at line 201 of file refineable_mesh.h.
References P_adapt_flag.
is_adaptation_enabled()
bool oomph::RefineableMeshBase::is_adaptation_enabled () const [inline]
Return whether the mesh is to be adapted.
Definition at line 225 of file refineable_mesh.h.
References Adapt_flag.
is_additional_synchronisation_of_hanging_nodes_disabled()
bool oomph::RefineableMeshBase::is_additional_synchronisation_of_hanging_nodes_disabled () const [inline]
Return whether additional synchronisation is enabled.
Definition at line 237 of file refineable_mesh.h.
References Additional_synchronisation_of_hanging_nodes_not_required.
is_p_adaptation_enabled()
bool oomph::RefineableMeshBase::is_p_adaptation_enabled () const [inline]
Return whether the mesh is to be adapted.
Definition at line 231 of file refineable_mesh.h.
References P_adapt_flag.
max_error()
double & oomph::RefineableMeshBase::max_error () [inline]
Access fct for max. actual error in present solution (i.e. before re-solve on adapted mesh)
Definition at line 177 of file refineable_mesh.h.
References Max_error.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), and oomph::TreeBasedRefineableMeshBase::p_adapt_mesh().
max_keep_unrefined()
unsigned & oomph::RefineableMeshBase::max_keep_unrefined () [inline]
Max. number of elements that we allow to remain unrefined if no other mesh adaptation is required (to avoid mesh-adaptations that would only unrefine a few elements and then force a new solve -- this can't be worth our while!)
Definition at line 123 of file refineable_mesh.h.
References Max_keep_unrefined.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt(), oomph::TreeBasedRefineableMeshBase::p_adapt(), and oomph::TreeBasedRefineableMeshBase::unrefine_uniformly().
max_permitted_error()
double & oomph::RefineableMeshBase::max_permitted_error () [inline]
Access fct for max. error (i.e. split elements if their error is larger)
Definition at line 163 of file refineable_mesh.h.
References Max_permitted_error.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt(), oomph::RefineableTetMeshBase::compute_volume_target(), oomph::TreeBasedRefineableMeshBase::p_adapt(), and oomph::TreeBasedRefineableMeshBase::unrefine_uniformly().
min_error()
double & oomph::RefineableMeshBase::min_error () [inline]
Access fct for min. actual error in present solution (i.e. before re-solve on adapted mesh)
Definition at line 170 of file refineable_mesh.h.
References Min_error.
min_permitted_error()
double & oomph::RefineableMeshBase::min_permitted_error () [inline]
Access fct for min. error (i.e. (try to) merge elements if their error is smaller)
Definition at line 156 of file refineable_mesh.h.
References Min_permitted_error.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt(), oomph::RefineableTetMeshBase::compute_volume_target(), oomph::TreeBasedRefineableMeshBase::p_adapt(), and oomph::TreeBasedRefineableMeshBase::unrefine_uniformly().
nrefined()
unsigned oomph::RefineableMeshBase::nrefined () [inline]
Access fct for number of elements that were refined.
Definition at line 101 of file refineable_mesh.h.
References Nrefined.
nrefinement_overruled()
unsigned & oomph::RefineableMeshBase::nrefinement_overruled () [inline]
Number of elements that would have liked to be refined further but can't because they've reached the max. refinement level.
Definition at line 114 of file refineable_mesh.h.
References Nrefinement_overruled.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt(), and oomph::TreeBasedRefineableMeshBase::p_adapt().
nunrefined()
unsigned oomph::RefineableMeshBase::nunrefined () [inline]
Access fct for number of elements that were unrefined.
Definition at line 107 of file refineable_mesh.h.
References Nunrefined.
operator=()
void oomph::RefineableMeshBase::operator= (const RefineableMeshBase &) [delete]
Broken assignment operator.
p_adapt()
virtual void oomph::RefineableMeshBase::p_adapt (const Vector< double > & elemental_error) [inline], [virtual]
p-adapt mesh: Refine elements whose error is lager than err_max and (try to) unrefine those whose error is smaller than err_min
Reimplemented in oomph::TreeBasedRefineableMeshBase.
Definition at line 254 of file refineable_mesh.h.
p_refine_uniformly() [1/2]
virtual void oomph::RefineableMeshBase::p_refine_uniformly () [inline], [virtual]
p-refine mesh uniformly
Reimplemented in oomph::TreeBasedRefineableMeshBase.
Definition at line 294 of file refineable_mesh.h.
References oomph::DocInfo::directory(), oomph::DocInfo::disable_doc(), doc_info(), and p_refine_uniformly().
Referenced by p_refine_uniformly(), and oomph::TreeBasedRefineableMeshBase::p_refine_uniformly().
p_refine_uniformly() [2/2]
virtual void oomph::RefineableMeshBase::p_refine_uniformly (DocInfo & doc_info) [inline], [virtual]
p-refine mesh uniformly and doc process
Reimplemented in oomph::TreeBasedRefineableMeshBase.
Definition at line 280 of file refineable_mesh.h.
p_unrefine_uniformly()
void oomph::RefineableMeshBase::p_unrefine_uniformly (DocInfo & doc_info) [inline]
p-unrefine mesh uniformly
Definition at line 308 of file refineable_mesh.h.
refine_uniformly() [1/2]
virtual void oomph::RefineableMeshBase::refine_uniformly () [inline], [virtual]
Refine mesh uniformly.
Reimplemented in oomph::TreeBasedRefineableMeshBase, and oomph::RefineableQuadFromTriangleMesh< ELEMENT >.
Definition at line 271 of file refineable_mesh.h.
References oomph::DocInfo::directory(), oomph::DocInfo::disable_doc(), doc_info(), and refine_uniformly().
Referenced by refine_uniformly(), and oomph::TreeBasedRefineableMeshBase::refine_uniformly().
refine_uniformly() [2/2]
virtual void oomph::RefineableMeshBase::refine_uniformly (DocInfo & doc_info) [pure virtual]
Refine mesh uniformly and doc process.
Implemented in oomph::TreeBasedRefineableMeshBase, oomph::RefineableGmshTetMesh< ELEMENT >, oomph::RefineableQuadFromTriangleMesh< ELEMENT >, oomph::RefineableTetgenMesh< ELEMENT >, and oomph::RefineableTriangleMesh< ELEMENT >.
spatial_error_estimator_pt() [1/2]
ErrorEstimator *& oomph::RefineableMeshBase::spatial_error_estimator_pt () [inline]
Access to spatial error estimator.
Definition at line 143 of file refineable_mesh.h.
References Spatial_error_estimator_pt.
spatial_error_estimator_pt() [2/2]
ErrorEstimator * oomph::RefineableMeshBase::spatial_error_estimator_pt () const [inline]
Access to spatial error estimator (const version.
Definition at line 149 of file refineable_mesh.h.
References Spatial_error_estimator_pt.
unrefine_uniformly()
virtual unsigned oomph::RefineableMeshBase::unrefine_uniformly () [pure virtual]
Unrefine mesh uniformly: Return 0 for success, 1 for failure (if unrefinement has reached the coarsest permitted level)
Implemented in oomph::TreeBasedRefineableMeshBase, oomph::RefineableGmshTetMesh< ELEMENT >, oomph::RefineableTetgenMesh< ELEMENT >, and oomph::RefineableTriangleMesh< ELEMENT >.
Member Data Documentation
Adapt_flag
bool oomph::RefineableMeshBase::Adapt_flag [protected]
Flag that requests adaptation.
Definition at line 344 of file refineable_mesh.h.
Referenced by adapt_flag(), disable_adaptation(), enable_adaptation(), is_adaptation_enabled(), and RefineableMeshBase().
Additional_synchronisation_of_hanging_nodes_not_required
bool oomph::RefineableMeshBase::Additional_synchronisation_of_hanging_nodes_not_required [protected]
Flag that disables additional synchronisation of hanging nodes.
Definition at line 350 of file refineable_mesh.h.
Referenced by disable_additional_synchronisation_of_hanging_nodes(), enable_additional_synchronisation_of_hanging_nodes(), is_additional_synchronisation_of_hanging_nodes_disabled(), and RefineableMeshBase().
Doc_info_pt
DocInfo* oomph::RefineableMeshBase::Doc_info_pt [protected]
Pointer to DocInfo.
Definition at line 353 of file refineable_mesh.h.
Referenced by doc_info(), doc_info_pt(), RefineableMeshBase(), and oomph::TreeBasedRefineableMeshBase::TreeBasedRefineableMeshBase().
Max_error
double oomph::RefineableMeshBase::Max_error [protected]
Max. actual error.
Definition at line 335 of file refineable_mesh.h.
Referenced by max_error(), and RefineableMeshBase().
Max_keep_unrefined
unsigned oomph::RefineableMeshBase::Max_keep_unrefined [protected]
Max. number of elements that can remain unrefined if no other mesh adaptation is required (to avoid mesh-adaptations that would only unrefine a few elements and then force a new solve -- this can't be worth our while!)
Definition at line 359 of file refineable_mesh.h.
Referenced by doc_adaptivity_targets(), oomph::TreeBasedRefineableMeshBase::doc_adaptivity_targets(), oomph::RefineableTetMeshBase::doc_adaptivity_targets(), max_keep_unrefined(), and RefineableMeshBase().
Max_permitted_error
double oomph::RefineableMeshBase::Max_permitted_error [protected]
Max. error (i.e. split elements if their error is larger)
Definition at line 326 of file refineable_mesh.h.
Referenced by doc_adaptivity_targets(), oomph::TreeBasedRefineableMeshBase::doc_adaptivity_targets(), oomph::RefineableTetMeshBase::doc_adaptivity_targets(), max_permitted_error(), and RefineableMeshBase().
Min_error
double oomph::RefineableMeshBase::Min_error [protected]
Min.actual error.
Definition at line 332 of file refineable_mesh.h.
Referenced by min_error(), and RefineableMeshBase().
Min_permitted_error
double oomph::RefineableMeshBase::Min_permitted_error [protected]
Min. error (i.e. (try to) merge elements if their error is smaller)
Definition at line 329 of file refineable_mesh.h.
Referenced by doc_adaptivity_targets(), oomph::TreeBasedRefineableMeshBase::doc_adaptivity_targets(), oomph::RefineableTetMeshBase::doc_adaptivity_targets(), min_permitted_error(), and RefineableMeshBase().
Nrefined
unsigned oomph::RefineableMeshBase::Nrefined [protected]
Stats: Number of elements that were refined.
Definition at line 338 of file refineable_mesh.h.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt(), oomph::RefineableTetMeshBase::compute_volume_target(), nrefined(), oomph::TreeBasedRefineableMeshBase::p_adapt(), and oomph::TreeBasedRefineableMeshBase::TreeBasedRefineableMeshBase().
Nrefinement_overruled
unsigned oomph::RefineableMeshBase::Nrefinement_overruled [protected]
Number of elements that would like to be refined further but can't because they've reached the max. refinement level.
Definition at line 363 of file refineable_mesh.h.
Referenced by oomph::RefineableTetMeshBase::compute_volume_target(), nrefinement_overruled(), and RefineableMeshBase().
Nunrefined
unsigned oomph::RefineableMeshBase::Nunrefined [protected]
Stats: Number of elements that were unrefined.
Definition at line 341 of file refineable_mesh.h.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt(), oomph::RefineableTetMeshBase::compute_volume_target(), nunrefined(), oomph::TreeBasedRefineableMeshBase::p_adapt(), and oomph::TreeBasedRefineableMeshBase::TreeBasedRefineableMeshBase().
P_adapt_flag
bool oomph::RefineableMeshBase::P_adapt_flag [protected]
Flag that requests p-adaptation.
Definition at line 347 of file refineable_mesh.h.
Referenced by disable_p_adaptation(), enable_p_adaptation(), is_p_adaptation_enabled(), and RefineableMeshBase().
Spatial_error_estimator_pt
ErrorEstimator* oomph::RefineableMeshBase::Spatial_error_estimator_pt [protected]
Pointer to spatial error estimator.
Definition at line 323 of file refineable_mesh.h.
Referenced by RefineableMeshBase(), spatial_error_estimator_pt(), and spatial_error_estimator_pt().
The documentation for this class was generated from the following file:
refineable_mesh.h