oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations Class Reference
A class for elements that solve the unsteady axisymmetric Navier--Stokes equations in cylindrical polar coordinates, $ x_0^* = r^*$ and $ x_1^* = z^* $ with $ \partial / \partial \theta = 0 $. We're solving for the radial, axial and azimuthal (swirl) velocities, $ u_0^* = u_r^*(r^*,z^*,t^*) = u^*(r^*,z^*,t^*), \ u_1^* = u_z^*(r^*,z^*,t^*) = w^*(r^*,z^*,t^*)$ and $ u_2^* = u_\theta^*(r^*,z^*,t^*) = v^*(r^*,z^*,t^*) $, respectively, and the pressure $ p(r^*,z^*,t^*) $. This class contains the generic maths -- any concrete implementation must be derived from this.
#include <generalised_newtonian_axisym_navier_stokes_elements.h>
Public Member Functions
GeneralisedNewtonianAxisymmetricNavierStokesEquations ()
Constructor: NULL the body force and source function.
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const double & re_invro () const
Global Reynolds number multiplied by inverse Rossby number.
double *& re_invro_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
const double & density_ratio () const
Density ratio for element: Element's density relative to the viscosity used in the definition of the Reynolds number.
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & viscosity_ratio () const
Viscosity ratio for element: Element's viscosity relative to the viscosity used in the definition of the Reynolds number.
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
GeneralisedNewtonianConstitutiveEquation< 3 > *& constitutive_eqn_pt ()
Access function for the constitutive equation pointer.
void use_current_strainrate_to_compute_second_invariant ()
Switch to fully implict evaluation of non-Newtonian const eqn.
void use_extrapolated_strainrate_to_compute_second_invariant ()
Use extrapolation for non-Newtonian const eqn.
virtual unsigned npres_axi_nst () const =0
Function to return number of pressure degrees of freedom.
virtual unsigned u_index_axi_nst (const unsigned &i) const
Return the index at which the i-th unknown velocity component is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
unsigned u_index_nst (const unsigned &i) const
Return the index at which the i-th unknown velocity component is stored with a common interface for use in general FluidInterface and similar elements. To do: Merge all common storage etc to a common base class for Navier--Stokes elements in all coordinate systems.
unsigned n_u_nst () const
Return the number of velocity components for use in general FluidInterface class.
double du_dt_axi_nst (const unsigned &n, const unsigned &i) const
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
void disable_ALE ()
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
void enable_ALE ()
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
virtual double p_axi_nst (const unsigned &n_p) const =0
Pressure at local pressure `node` n_p Uses suitably interpolated value for hanging nodes.
virtual int p_nodal_index_axi_nst () const
Which nodal value represents the pressure?
double pressure_integral () const
Integral of pressure over element.
void max_and_min_invariant_and_viscosity (double &min_invariant, double &max_invariant, double &min_viscosity, double &max_viscosity) const
Get max. and min. strain rate invariant and visocosity over all integration points in element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: $ e_{ij} $ where $ i,j = r,z,\theta $ (in that order)
void strain_rate (const unsigned &t, const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: $ e_{ij} $ where $ i,j = r,z,\theta $ (in that order) at a specific time history value.
virtual void extrapolated_strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Extrapolated strain-rate tensor: $ e_{ij} $ where $ i,j = r,z,\theta $ (in that order) based on the previous time steps evaluated at local coordinate s.
virtual void extrapolated_strain_rate (const unsigned &ipt, DenseMatrix< double > &strain_rate) const
Extrapolated strain-rate tensor: $ e_{ij} $ where $ i,j = r,z,\theta $ (in that order) based on the previous time steps evaluated at ipt-th integration point.
void traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction) const
Compute traction (on the viscous scale) at local coordinate s for outer unit normal N.
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one) NOTE: pressure versions isn't implemented yet because this element has never been tried with Fp preconditoner.
unsigned nscalar_paraview () const
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
std::string scalar_name_paraview (const unsigned &i) const
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
void point_output_data (const Vector< double > &s, Vector< double > &data)
Output solution in data vector at local cordinates s: r,z,u_r,u_z,u_phi,p.
void output (std::ostream &outfile)
Output function: x,y,[z],u,v,[w],p in tecplot format. Default number of plot points.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,[z],u,v,[w],p in tecplot format. nplot points in each coordinate direction.
void output (FILE *file_pt)
Output function: x,y,[z],u,v,[w],p in tecplot format. Default number of plot points.
void output (FILE *file_pt, const unsigned &nplot)
Output function: x,y,[z],u,v,[w],p in tecplot format. nplot points in each coordinate direction.
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
Output function: x,y,[z],u,v,[w] in tecplot format. nplot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given number of plot points. Function prints as many components as are returned in solution Vector.
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given time and at a given number of plot points. Function prints as many components as are returned in solution Vector.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
Compute derivatives of elemental residual vector with respect to nodal coordinates. This function computes these terms analytically and overwrites the default implementation in the FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}.
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Compute the element's residual Vector.
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void interpolated_u_axi_nst (const Vector< double > &s, Vector< double > &veloc) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_axi_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_axi_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
virtual void dinterpolated_u_axi_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. The function is virtual so that it can be overloaded in the refineable version.
double interpolated_p_axi_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_duds_axi_nst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
Return FE interpolated derivatives of velocity component u[i] w.r.t spatial local coordinate direction s[j] at local coordinate s.
double interpolated_dudx_axi_nst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
Return FE interpolated derivatives of velocity component u[i] w.r.t spatial global coordinate direction x[j] at local coordinate s.
double interpolated_dudt_axi_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated derivatives of velocity component u[i] w.r.t time at local coordinate s.
double interpolated_d_dudx_dX_axi_nst (const Vector< double > &s, const unsigned &p, const unsigned &q, const unsigned &i, const unsigned &k) const
Return FE interpolated derivatives w.r.t. nodal coordinates X_{pq} of the spatial derivatives of the velocity components du_i/dx_k at local coordinate s.
double compute_physical_size () const
Compute the volume of the element.
Public Attributes
void(*&)(const double &time, const Vector< double > &x, Vector< double > &f) axi_nst_body_force_fct_pt ()
Access function for the body-force pointer.
double(*&)(const double &time, const Vector< double > &x) source_fct_pt ()
Access function for the source-function pointer.
Static Public Attributes
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Protected Member Functions
virtual int p_local_eqn (const unsigned &n) const =0
Access function for the local equation number information for the pressure. p_local_eqn[n] = local equation number or < 0 if pinned.
virtual double dshape_and_dtest_eulerian_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Compute the shape functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
virtual double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Compute the shape functions and derivatives w.r.t. global coords at ipt-th integration point Return Jacobian of mapping between local and global coordinates.
virtual double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
virtual void pshape_axi_nst (const Vector< double > &s, Shape &psi) const =0
Compute the pressure shape functions at local coordinate s.
virtual void pshape_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const =0
Compute the pressure shape and test functions at local coordinate s.
virtual void get_body_force_axi_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
Calculate the body force fct at a given time and Eulerian position.
virtual void get_body_force_gradient_axi_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
Get gradient of body force term at (Eulerian) position x. Computed via function pointer (if set) or by finite differencing (default)
double get_source_fct (const double &time, const unsigned &ipt, const Vector< double > &x)
Calculate the source fct at given time and Eulerian position.
virtual void get_source_fct_gradient (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
Get gradient of source term at (Eulerian) position x. Computed via function pointer (if set) or by finite differencing (default)
virtual void get_viscosity_ratio_axisym_nst (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, double &visc_ratio)
Calculate the viscosity ratio relative to the viscosity used in the definition of the Reynolds number at given time and Eulerian position This is the equivalent of the Newtonian case and basically allows the flow of two Generalised Newtonian fluids with different reference viscosities.
virtual void fill_in_generic_residual_contribution_axi_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Compute the residuals for the Navier--Stokes equations; flag=2 or 1 or 0: compute the Jacobian and/or mass matrix as well.
virtual void fill_in_generic_dresidual_contribution_axi_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, unsigned flag)
Compute the derivative of residuals for the Navier--Stokes equations; with respect to a parameeter flag=2 or 1 or 0: compute the Jacobian and/or mass matrix as well.
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Compute the hessian tensor vector products required to perform continuation of bifurcations analytically.
Protected Attributes
double * Viscosity_Ratio_pt
Pointer to the viscosity ratio (relative to the viscosity used in the definition of the Reynolds number)
double * Density_Ratio_pt
Pointer to the density ratio (relative to the density used in the definition of the Reynolds number)
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
double * ReInvFr_pt
Pointer to global Reynolds number x inverse Froude number (= Bond number / Capillary number)
double * ReInvRo_pt
Pointer to global Reynolds number x inverse Rossby number (used when in a rotating frame)
Vector< double > * G_pt
Pointer to global gravity Vector.
void(* Body_force_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
Pointer to body force function.
double(* Source_fct_pt)(const double &time, const Vector< double > &x)
Pointer to volumetric source function.
GeneralisedNewtonianConstitutiveEquation< 3 > * Constitutive_eqn_pt
Pointer to the generalised Newtonian constitutive equation.
bool Use_extrapolated_strainrate_to_compute_second_invariant
bool ALE_is_disabled
Boolean flag to indicate if ALE formulation is disabled when the time-derivatives are computed. Only set to true if you're sure that the mesh is stationary.
Static Protected Attributes
static bool Pre_multiply_by_viscosity_ratio
Static boolean telling us whether we pre-multiply the pressure and continuity by the viscosity ratio.
Static Private Attributes
static int Pressure_not_stored_at_node
Static `magic` number that indicates that the pressure is not stored at a node.
static double Default_Physical_Constant_Value
Static default value for the physical constants (all initialised to zero)
static double Default_Physical_Ratio_Value
Static default value for the physical ratios (all are initialised to one)
static Vector< double > Default_Gravity_vector
Static default value for the gravity vector.
Additional Inherited Members
Detailed Description
A class for elements that solve the unsteady axisymmetric Navier--Stokes equations in cylindrical polar coordinates, $ x_0^* = r^*$ and $ x_1^* = z^* $ with $ \partial / \partial \theta = 0 $. We're solving for the radial, axial and azimuthal (swirl) velocities, $ u_0^* = u_r^*(r^*,z^*,t^*) = u^*(r^*,z^*,t^*), \ u_1^* = u_z^*(r^*,z^*,t^*) = w^*(r^*,z^*,t^*)$ and $ u_2^* = u_\theta^*(r^*,z^*,t^*) = v^*(r^*,z^*,t^*) $, respectively, and the pressure $ p(r^*,z^*,t^*) $. This class contains the generic maths -- any concrete implementation must be derived from this.
In dimensional form the axisymmetric Navier-Stokes equations are given by the momentum equations (for the $ r^* $, $ z^* $ and $ \theta $ directions, respectively)
 \rho\left(\frac{\partial u^*}{\partial t^*} + {u^*}\frac{\partial u^*}{\partial r^*} - \frac{{v^*}^2}{r^*} + {w^*}\frac{\partial u^*}{\partial z^*} \right) = B_r^*\left(r^*,z^*,t^*\right)+ \rho G_r^*+ \frac{1}{r^*} \frac{\partial\left({r^*}\sigma_{rr}^*\right)}{\partial r^*} - \frac{\sigma_{\theta\theta}^*}{r^*} + \frac{\partial\sigma_{rz}^*}{\partial z^*}, 
 \rho\left(\frac{\partial w^*}{\partial t^*} + {u^*}\frac{\partial w^*}{\partial r^*} + {w^*}\frac{\partial w^*}{\partial z^*} \right) = B_z^*\left(r^*,z^*,t^*\right)+\rho G_z^*+ \frac{1}{r^*}\frac{\partial\left({r^*}\sigma_{zr}^*\right)}{\partial r^*} + \frac{\partial\sigma_{zz}^*}{\partial z^*}, 
 \rho\left(\frac{\partial v^*}{\partial t^*} + {u^*}\frac{\partial v^*}{\partial r^*} + \frac{u^* v^*}{r^*} +{w^*}\frac{\partial v^*}{\partial z^*} \right)= B_\theta^*\left(r^*,z^*,t^*\right)+ \rho G_\theta^*+ \frac{1}{r^*}\frac{\partial\left({r^*}\sigma_{\theta r}^*\right)}{\partial r^*} + \frac{\sigma_{r\theta}^*}{r^*} + \frac{\partial\sigma_{\theta z}^*}{\partial z^*}, 
 and
 \frac{1}{r^*}\frac{\partial\left(r^*u^*\right)}{\partial r^*} + \frac{\partial w^*}{\partial z^*} = Q^*. 
 The dimensional, symmetric stress tensor is defined as:
 \sigma_{rr}^* = -p^* + 2\mu\frac{\partial u^*}{\partial r^*}, \qquad \sigma_{\theta\theta}^* = -p^* +2\mu\frac{u^*}{r^*}, 
 \sigma_{zz}^* = -p^* + 2\mu\frac{\partial w^*}{\partial z^*}, \qquad \sigma_{rz}^* = \mu\left(\frac{\partial u^*}{\partial z^*} + \frac{\partial w^*}{\partial r^*}\right), 
 \sigma_{\theta r}^* = \mu r^*\frac{\partial}{\partial r^*} \left(\frac{v^*}{r^*}\right), \qquad \sigma_{\theta z}^* = \mu\frac{\partial v^*}{\partial z^*}. 
 Here, the (dimensional) velocity components are denoted by $ u^* $, $ w^* $ and $ v^* $ for the radial, axial and azimuthal velocities, respectively, and we have split the body force into two components: A constant vector $ \rho \ G_i^* $ which typically represents gravitational forces; and a variable body force, $ B_i^*(r^*,z^*,t^*) $. $ Q^*(r^*,z^*,t^*) $ is a volumetric source term for the continuity equation and is typically equal to zero.
We non-dimensionalise the equations, using problem-specific reference quantities for the velocity, $ U $, length, $ L $, and time, $ T $, and scale the constant body force vector on the gravitational acceleration, $ g $, so that
 u^* = U\, u, \qquad w^* = U\, w, \qquad v^* = U\, v, 
 r^* = L\, r, \qquad z^* = L\, z, \qquad t^* = T\, t, 
 G_i^* = g\, G_i, \qquad B_i^* = \frac{U\mu_{ref}}{L^2}\, B_i, \qquad p^* = \frac{\mu_{ref} U}{L}\, p, \qquad Q^* = \frac{U}{L}\, Q. 
 where we note that the pressure and the variable body force have been non-dimensionalised on the viscous scale. $ \mu_{ref} $ and $ \rho_{ref} $ (used below) are reference values for the fluid viscosity and density, respectively. In single-fluid problems, they are identical to the viscosity $ \mu $ and density $ \rho $ of the (one and only) fluid in the problem.
The non-dimensional form of the axisymmetric Navier-Stokes equations is then given by
 R_{\rho} Re\left(St\frac{\partial u}{\partial t} + {u}\frac{\partial u}{\partial r} - \frac{{v}^2}{r} + {w}\frac{\partial u}{\partial z} \right) = B_r\left(r,z,t\right)+ R_\rho \frac{Re}{Fr} G_r + \frac{1}{r} \frac{\partial\left({r}\sigma_{rr}\right)}{\partial r} - \frac{\sigma_{\theta\theta}}{r} + \frac{\partial\sigma_{rz}}{\partial z}, 
 R_{\rho} Re\left(St\frac{\partial w}{\partial t} + {u}\frac{\partial w}{\partial r} + {w}\frac{\partial w}{\partial z} \right) = B_z\left(r,z,t\right)+ R_\rho \frac{Re}{Fr} G_z+ \frac{1}{r}\frac{\partial\left({r}\sigma_{zr}\right)}{\partial r} + \frac{\partial\sigma_{zz}}{\partial z}, 
 R_{\rho} Re\left(St\frac{\partial v}{\partial t} + {u}\frac{\partial v}{\partial r} + \frac{u v}{r} +{w}\frac{\partial v}{\partial z} \right)= B_\theta\left(r,z,t\right)+ R_\rho \frac{Re}{Fr} G_\theta+ \frac{1}{r}\frac{\partial\left({r}\sigma_{\theta r}\right)}{\partial r} + \frac{\sigma_{r\theta}}{r} + \frac{\partial\sigma_{\theta z}}{\partial z}, 
 and
 \frac{1}{r}\frac{\partial\left(ru\right)}{\partial r} + \frac{\partial w}{\partial z} = Q. 
 Here the non-dimensional, symmetric stress tensor is defined as:
 \sigma_{rr} = -p + 2R_\mu \frac{\partial u}{\partial r}, \qquad \sigma_{\theta\theta} = -p +2R_\mu \frac{u}{r}, 
 \sigma_{zz} = -p + 2R_\mu \frac{\partial w}{\partial z}, \qquad \sigma_{rz} = R_\mu \left(\frac{\partial u}{\partial z} + \frac{\partial w}{\partial r}\right), 
 \sigma_{\theta r} = R_\mu r \frac{\partial}{\partial r}\left(\frac{v}{r}\right), \qquad \sigma_{\theta z} = R_\mu \frac{\partial v}{\partial z}. 
 and the dimensionless parameters
 Re = \frac{UL\rho_{ref}}{\mu_{ref}}, \qquad St = \frac{L}{UT}, \qquad Fr = \frac{U^2}{gL}, 
 are the Reynolds number, Strouhal number and Froude number respectively. $ R_\rho=\rho/\rho_{ref} $ and $ R_\mu(T) =\mu(T)/\mu_{ref}$ represent the ratios of the fluid's density and its dynamic viscosity, relative to the density and viscosity values used to form the non-dimensional parameters (By default, $ R_\rho = R_\mu = 1 $; other values tend to be used in problems involving multiple fluids).
Definition at line 116 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Constructor & Destructor Documentation
GeneralisedNewtonianAxisymmetricNavierStokesEquations()
oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::GeneralisedNewtonianAxisymmetricNavierStokesEquations () [inline]
Constructor: NULL the body force and source function.
Definition at line 393 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References Default_Gravity_vector, Default_Physical_Constant_Value, Default_Physical_Ratio_Value, Density_Ratio_pt, G_pt, Re_pt, ReInvFr_pt, ReInvRo_pt, ReSt_pt, and Viscosity_Ratio_pt.
Member Function Documentation
compute_error() [1/2]
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Validate against exact velocity solution Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Reimplemented from oomph::FiniteElement.
Definition at line 241 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References i, oomph::FiniteElement::integral_pt(), interpolated_u_axi_nst(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::Integral::nweight(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
compute_error() [2/2]
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [virtual]
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Validate against exact velocity solution at given time. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Reimplemented from oomph::FiniteElement.
Definition at line 163 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References i, oomph::FiniteElement::integral_pt(), interpolated_u_axi_nst(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::Integral::nweight(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
compute_physical_size()
double oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::compute_physical_size () const [inline], [virtual]
Compute the volume of the element.
Reimplemented from oomph::FiniteElement.
Definition at line 1251 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::FiniteElement::nodal_dimension(), oomph::Integral::nweight(), oomph::MathematicalConstants::Pi, s, and oomph::Integral::weight().
constitutive_eqn_pt()
GeneralisedNewtonianConstitutiveEquation<3>*& oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::constitutive_eqn_pt () [inline]
Access function for the constitutive equation pointer.
Definition at line 520 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References Constitutive_eqn_pt.
density_ratio()
const double& oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::density_ratio () const [inline]
Density ratio for element: Element's density relative to the viscosity used in the definition of the Reynolds number.
Definition at line 481 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References Density_Ratio_pt.
Referenced by fill_in_contribution_to_hessian_vector_products(), fill_in_generic_dresidual_contribution_axi_nst(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
density_ratio_pt()
double*& oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::density_ratio_pt () [inline]
Pointer to Density ratio.
Definition at line 487 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References Density_Ratio_pt.
Referenced by oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::further_build().
dinterpolated_u_axi_nst_ddata()
virtual void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata (const Vector< double > & s, const unsigned & i, Vector< double > & du_ddata, Vector< unsigned > & global_eqn_number) [inline], [virtual]
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. The function is virtual so that it can be overloaded in the refineable version.
Reimplemented in oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations.
Definition at line 1027 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References oomph::Data::eqn_number(), i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), s, oomph::FiniteElement::shape(), and u_index_axi_nst().
disable_ALE()
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::disable_ALE () [inline], [virtual]
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
Reimplemented from oomph::FiniteElement.
Definition at line 599 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References ALE_is_disabled.
dissipation() [1/2]
double oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::dissipation () const
Return integral of dissipation over element.
Definition at line 601 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::Integral::nweight(), s, strain_rate(), and oomph::Integral::weight().
dissipation() [2/2]
double oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::dissipation (const Vector< double > & s) const
Return dissipation at local coordinate s.
Definition at line 720 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References i, s, and strain_rate().
dshape_and_dtest_eulerian_at_knot_axi_nst() [1/2]
virtual double oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implemented in oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement, and oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement.
dshape_and_dtest_eulerian_at_knot_axi_nst() [2/2]
virtual double oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Compute the shape functions and derivatives w.r.t. global coords at ipt-th integration point Return Jacobian of mapping between local and global coordinates.
Implemented in oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement, and oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_contribution_to_hessian_vector_products(), fill_in_generic_dresidual_contribution_axi_nst(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
dshape_and_dtest_eulerian_axi_nst()
virtual double oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::dshape_and_dtest_eulerian_axi_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Compute the shape functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Implemented in oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement, and oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement.
du_dt_axi_nst()
double oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::du_dt_axi_nst (const unsigned & n, const unsigned & i) const [inline]
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
Definition at line 570 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References i, oomph::TimeStepper::is_steady(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), u_index_axi_nst(), and oomph::TimeStepper::weight().
Referenced by fill_in_generic_dresidual_contribution_axi_nst(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), and interpolated_dudt_axi_nst().
enable_ALE()
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::enable_ALE () [inline], [virtual]
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
Reimplemented from oomph::FiniteElement.
Definition at line 608 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References ALE_is_disabled.
extrapolated_strain_rate() [1/2]
virtual void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::extrapolated_strain_rate (const unsigned & ipt, DenseMatrix< double > & strain_rate) const [inline], [virtual]
Extrapolated strain-rate tensor: $ e_{ij} $ where $ i,j = r,z,\theta $ (in that order) based on the previous time steps evaluated at ipt-th integration point.
Definition at line 665 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References extrapolated_strain_rate(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), s, and strain_rate().
extrapolated_strain_rate() [2/2]
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::extrapolated_strain_rate (const Vector< double > & s, DenseMatrix< double > & strain_rate) const [virtual]
Extrapolated strain-rate tensor: $ e_{ij} $ where $ i,j = r,z,\theta $ (in that order) based on the previous time steps evaluated at local coordinate s.
Get strain-rate tensor: $ e_{ij} $ where $ i,j = r,z,\theta $ (in that order). Extrapolated from history values.
Definition at line 976 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References oomph::Time::dt(), i, oomph::DenseMatrix< T >::ncol(), oomph::FiniteElement::node_pt(), oomph::DenseMatrix< T >::nrow(), s, strain_rate(), oomph::TimeStepper::time_pt(), oomph::GeomObject::time_stepper_pt(), and oomph::Data::time_stepper_pt().
Referenced by extrapolated_strain_rate(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), and traction().
fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter()
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam, DenseMatrix< double > & dmass_matrix_dparam) [inline], [virtual]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Reimplemented from oomph::GeneralisedElement.
Definition at line 931 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References fill_in_generic_dresidual_contribution_axi_nst().
fill_in_contribution_to_djacobian_dparameter()
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_djacobian_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam) [inline], [virtual]
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
Reimplemented from oomph::GeneralisedElement.
Definition at line 915 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_dresidual_contribution_axi_nst().
fill_in_contribution_to_dresiduals_dparameter()
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_dresiduals_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam) [inline], [virtual]
Compute the element's residual Vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 900 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_dresidual_contribution_axi_nst().
fill_in_contribution_to_hessian_vector_products()
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products (Vector< double > const & Y, DenseMatrix< double > const & C, DenseMatrix< double > & product) [protected], [virtual]
Compute the hessian tensor vector products required to perform continuation of bifurcations analytically.
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations.
Definition at line 4097 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References ALE_is_disabled, density_ratio(), dshape_and_dtest_eulerian_at_knot_axi_nst(), g(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Integral::knot(), oomph::GeneralisedElement::ndof(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::DenseMatrix< T >::nrow(), oomph::Integral::nweight(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), re(), s, u_index_axi_nst(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
fill_in_contribution_to_jacobian()
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
Reimplemented from oomph::GeneralisedElement.
Definition at line 867 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_axi_nst().
fill_in_contribution_to_jacobian_and_mass_matrix()
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline], [virtual]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Reimplemented from oomph::GeneralisedElement.
Definition at line 882 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References fill_in_generic_residual_contribution_axi_nst().
fill_in_contribution_to_residuals()
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Compute the element's residual Vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 854 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_axi_nst().
fill_in_generic_dresidual_contribution_axi_nst()
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam, DenseMatrix< double > & dmass_matrix_dparam, unsigned flag) [protected], [virtual]
Compute the derivative of residuals for the Navier--Stokes equations; with respect to a parameeter flag=2 or 1 or 0: compute the Jacobian and/or mass matrix as well.
Compute the residuals for the Navier--Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented in oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations.
Definition at line 3368 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References ALE_is_disabled, density_ratio(), dshape_and_dtest_eulerian_at_knot_axi_nst(), du_dt_axi_nst(), g(), get_viscosity_ratio_axisym_nst(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), npres_axi_nst(), oomph::Integral::nweight(), p_axi_nst(), pshape_axi_nst(), oomph::FiniteElement::raw_dnodal_position_dt(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), re_invfr_pt(), re_invro_pt(), Re_pt, re_pt(), re_st_pt(), s, oomph::Data::time_stepper_pt(), u_index_axi_nst(), oomph::QuadTreeNames::W, oomph::Integral::weight(), and oomph::TimeStepper::weight().
Referenced by fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter(), fill_in_contribution_to_djacobian_dparameter(), and fill_in_contribution_to_dresiduals_dparameter().
fill_in_generic_residual_contribution_axi_nst()
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [protected], [virtual]
Compute the residuals for the Navier--Stokes equations; flag=2 or 1 or 0: compute the Jacobian and/or mass matrix as well.
Compute the residuals for the Navier--Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented in oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations.
Definition at line 1166 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References ALE_is_disabled, Constitutive_eqn_pt, density_ratio(), dshape_and_dtest_eulerian_at_knot_axi_nst(), du_dt_axi_nst(), oomph::GeneralisedNewtonianConstitutiveEquation< DIM >::dviscosity_dinvariant(), extrapolated_strain_rate(), g(), Gamma, get_body_force_axi_nst(), get_source_fct(), get_viscosity_ratio_axisym_nst(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Integral::knot(), oomph::GeneralisedElement::ndof(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), npres_axi_nst(), oomph::Integral::nweight(), p_axi_nst(), p_local_eqn(), Pre_multiply_by_viscosity_ratio, pshape_axi_nst(), oomph::FiniteElement::raw_dnodal_position_dt(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), re(), re_invfr(), re_invro(), re_st(), s, oomph::SecondInvariantHelper::second_invariant(), strain_rate(), oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), u_index_axi_nst(), Use_extrapolated_strainrate_to_compute_second_invariant, oomph::GeneralisedNewtonianConstitutiveEquation< DIM >::viscosity(), oomph::QuadTreeNames::W, oomph::Integral::weight(), and oomph::TimeStepper::weight().
Referenced by fill_in_contribution_to_jacobian(), fill_in_contribution_to_jacobian_and_mass_matrix(), and fill_in_contribution_to_residuals().
g()
const Vector<double>& oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::g () const [inline]
Vector of gravitational components.
Definition at line 468 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References G_pt.
Referenced by fill_in_contribution_to_hessian_vector_products(), fill_in_generic_dresidual_contribution_axi_nst(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
g_pt()
Vector<double>*& oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::g_pt () [inline]
Pointer to Vector of gravitational components.
Definition at line 474 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References G_pt.
Referenced by oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::further_build().
get_body_force_axi_nst()
virtual void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_body_force_axi_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & result) [inline], [protected], [virtual]
Calculate the body force fct at a given time and Eulerian position.
Definition at line 237 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References Body_force_fct_pt, and i.
Referenced by fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_body_force_gradient_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
get_body_force_gradient_axi_nst()
virtual void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_body_force_gradient_axi_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, DenseMatrix< double > & d_body_force_dx) [inline], [protected], [virtual]
Get gradient of body force term at (Eulerian) position x. Computed via function pointer (if set) or by finite differencing (default)
Definition at line 262 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References oomph::GeneralisedElement::Default_fd_jacobian_step, get_body_force_axi_nst(), i, and s.
Referenced by get_dresidual_dnodal_coordinates(), and oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
get_dresidual_dnodal_coordinates()
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates (RankThreeTensor< double > & dresidual_dnodal_coordinates) [virtual]
Compute derivatives of elemental residual vector with respect to nodal coordinates. This function computes these terms analytically and overwrites the default implementation in the FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}.
Compute derivatives of elemental residual vector with respect to nodal coordinates. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij} Overloads the FD-based version in the FiniteElement base class.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations.
Definition at line 2420 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References ALE_is_disabled, oomph::GeneralisedElement::Default_fd_jacobian_step, density_ratio(), dshape_and_dtest_eulerian_at_knot_axi_nst(), du_dt_axi_nst(), g(), Gamma, get_body_force_axi_nst(), get_body_force_gradient_axi_nst(), get_source_fct(), get_source_fct_gradient(), oomph::Node::has_auxiliary_node_update_fct_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Integral::knot(), oomph::GeneralisedElement::ndof(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), npres_axi_nst(), oomph::Integral::nweight(), p_axi_nst(), p_local_eqn(), oomph::Node::perform_auxiliary_node_update_fct(), oomph::Node::position_time_stepper_pt(), pshape_axi_nst(), oomph::FiniteElement::raw_dnodal_position_dt(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), re(), re_invfr(), re_invro(), re_st(), s, oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), u_index_axi_nst(), oomph::Data::value_pt(), viscosity_ratio(), oomph::Integral::weight(), oomph::TimeStepper::weight(), and oomph::Node::x().
get_pressure_and_velocity_mass_matrix_diagonal()
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > & press_mass_diag, Vector< double > & veloc_mass_diag, const unsigned & which_one = 0) [virtual]
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one) NOTE: pressure versions isn't implemented yet because this element has never been tried with Fp preconditoner.
Implements oomph::NavierStokesElementWithDiagonalMassMatrices.
Definition at line 70 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::J_eulerian_at_knot(), oomph::GeneralisedElement::ndof(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::Integral::nweight(), oomph::FiniteElement::shape_at_knot(), u_index_axi_nst(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
get_source_fct()
double oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_source_fct (const double & time, const unsigned & ipt, const Vector< double > & x) [inline], [protected]
Calculate the source fct at given time and Eulerian position.
Definition at line 301 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References Source_fct_pt.
Referenced by fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), and get_source_fct_gradient().
get_source_fct_gradient()
virtual void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_source_fct_gradient (const double & time, const unsigned & ipt, const Vector< double > & x, Vector< double > & gradient) [inline], [protected], [virtual]
Get gradient of source term at (Eulerian) position x. Computed via function pointer (if set) or by finite differencing (default)
Definition at line 320 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References oomph::GeneralisedElement::Default_fd_jacobian_step, get_source_fct(), and i.
Referenced by get_dresidual_dnodal_coordinates(), and oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
get_viscosity_ratio_axisym_nst()
virtual void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_viscosity_ratio_axisym_nst (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, double & visc_ratio) [inline], [protected], [virtual]
Calculate the viscosity ratio relative to the viscosity used in the definition of the Reynolds number at given time and Eulerian position This is the equivalent of the Newtonian case and basically allows the flow of two Generalised Newtonian fluids with different reference viscosities.
Definition at line 357 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References Viscosity_Ratio_pt.
Referenced by fill_in_generic_dresidual_contribution_axi_nst(), and fill_in_generic_residual_contribution_axi_nst().
interpolated_d_dudx_dX_axi_nst()
double oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_d_dudx_dX_axi_nst (const Vector< double > & s, const unsigned & p, const unsigned & q, const unsigned & i, const unsigned & k) const [inline]
Return FE interpolated derivatives w.r.t. nodal coordinates X_{pq} of the spatial derivatives of the velocity components du_i/dx_k at local coordinate s.
Definition at line 1193 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References oomph::FiniteElement::d_dshape_eulerian_dnodal_coordinates(), oomph::FiniteElement::dJ_eulerian_dnodal_coordinates(), oomph::FiniteElement::dshape_local(), i, oomph::FiniteElement::local_to_eulerian_mapping(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), and u_index_axi_nst().
interpolated_duds_axi_nst()
double oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_duds_axi_nst (const Vector< double > & s, const unsigned & i, const unsigned & j) const [inline]
Return FE interpolated derivatives of velocity component u[i] w.r.t spatial local coordinate direction s[j] at local coordinate s.
Definition at line 1102 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_local(), i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), and u_index_axi_nst().
interpolated_dudt_axi_nst()
double oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_dudt_axi_nst (const Vector< double > & s, const unsigned & i) const [inline]
Return FE interpolated derivatives of velocity component u[i] w.r.t time at local coordinate s.
Definition at line 1166 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References du_dt_axi_nst(), i, oomph::FiniteElement::nnode(), s, and oomph::FiniteElement::shape().
interpolated_dudx_axi_nst()
double oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_dudx_axi_nst (const Vector< double > & s, const unsigned & i, const unsigned & j) const [inline]
Return FE interpolated derivatives of velocity component u[i] w.r.t spatial global coordinate direction x[j] at local coordinate s.
Definition at line 1134 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian(), i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), and u_index_axi_nst().
interpolated_p_axi_nst()
double oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_p_axi_nst (const Vector< double > & s) const [inline]
Return FE interpolated pressure at local coordinate s.
Definition at line 1080 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References npres_axi_nst(), p_axi_nst(), pshape_axi_nst(), and s.
Referenced by oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::further_build(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::get_interpolated_values(), output(), point_output_data(), pressure_integral(), scalar_value_paraview(), and traction().
interpolated_u_axi_nst() [1/3]
double oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_u_axi_nst (const unsigned & t, const Vector< double > & s, const unsigned & i) const [inline]
Return FE interpolated velocity u[i] at local coordinate s.
Definition at line 996 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), t, and u_index_axi_nst().
interpolated_u_axi_nst() [2/3]
double oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_u_axi_nst (const Vector< double > & s, const unsigned & i) const [inline]
Return FE interpolated velocity u[i] at local coordinate s.
Definition at line 969 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and u_index_axi_nst().
interpolated_u_axi_nst() [3/3]
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_u_axi_nst (const Vector< double > & s, Vector< double > & veloc) const [inline]
Compute vector of FE interpolated velocity u at local coordinate s.
Definition at line 944 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and u_index_axi_nst().
Referenced by compute_error(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), kin_energy(), output(), point_output_data(), and scalar_value_paraview().
kin_energy()
double oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::kin_energy () const
Get integral of kinetic energy over element.
Get integral of kinetic energy over element:
Definition at line 1025 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References i, oomph::FiniteElement::integral_pt(), interpolated_u_axi_nst(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::Integral::nweight(), s, and oomph::Integral::weight().
max_and_min_invariant_and_viscosity()
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::max_and_min_invariant_and_viscosity (double & min_invariant, double & max_invariant, double & min_viscosity, double & max_viscosity) const
Get max. and min. strain rate invariant and visocosity over all integration points in element.
Definition at line 1118 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References Constitutive_eqn_pt, i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), oomph::Integral::nweight(), s, oomph::SecondInvariantHelper::second_invariant(), strain_rate(), and oomph::GeneralisedNewtonianConstitutiveEquation< DIM >::viscosity().
n_u_nst()
unsigned oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::n_u_nst () const [inline]
Return the number of velocity components for use in general FluidInterface class.
Definition at line 563 of file generalised_newtonian_axisym_navier_stokes_elements.h.
npres_axi_nst()
virtual unsigned oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::npres_axi_nst () const [pure virtual]
Function to return number of pressure degrees of freedom.
Implemented in oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement, and oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_dresidual_contribution_axi_nst(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), and interpolated_p_axi_nst().
nscalar_paraview()
unsigned oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::nscalar_paraview () const [inline], [virtual]
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
Reimplemented from oomph::FiniteElement.
Definition at line 693 of file generalised_newtonian_axisym_navier_stokes_elements.h.
output() [1/4]
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output (FILE * file_pt) [inline], [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format. Default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement, and oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement.
Definition at line 802 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References output().
output() [2/4]
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output (FILE * file_pt, const unsigned & nplot) [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format. nplot points in each coordinate direction.
Output function: r,z,u,v,w,p in tecplot format. Specified number of plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement, and oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement.
Definition at line 553 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, interpolated_p_axi_nst(), interpolated_u_axi_nst(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [3/4]
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output (std::ostream & outfile) [inline], [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format. Default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement, and oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement.
Definition at line 789 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by output(), oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::output(), oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement::output(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::output(), and oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::output().
output() [4/4]
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format. nplot points in each coordinate direction.
Output function: r,z,u,v,w,p in tecplot format. Specified number of plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement, and oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement.
Definition at line 507 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, interpolated_p_axi_nst(), interpolated_u_axi_nst(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_fct() [1/2]
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact solution specified via function pointer at a given time and at a given number of plot points. Function prints as many components as are returned in solution Vector.
Output `exact` solution at a given time Solution is provided via function pointer. Plot at a given number of plot points. Function prints as many components as are returned in solution Vector.
Reimplemented from oomph::FiniteElement.
Definition at line 373 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_fct() [2/2]
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact solution specified via function pointer at a given number of plot points. Function prints as many components as are returned in solution Vector.
Output `exact` solution Solution is provided via function pointer. Plot at a given number of plot points. Function prints as many components as are returned in solution Vector.
Reimplemented from oomph::FiniteElement.
Definition at line 318 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_veloc()
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output_veloc (std::ostream & outfile, const unsigned & nplot, const unsigned & t)
Output function: x,y,[z],u,v,[w] in tecplot format. nplot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
Output function: Velocities only x,y,[z],u,v,[w] in tecplot format at specified previous timestep (t=0: present; t>0: previous timestep). Specified number of plot points in each coordinate direction.
Definition at line 430 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::shape(), t, oomph::FiniteElement::tecplot_zone_string(), u_index_axi_nst(), and oomph::FiniteElement::write_tecplot_zone_footer().
p_axi_nst()
virtual double oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::p_axi_nst (const unsigned & n_p) const [pure virtual]
Pressure at local pressure `node` n_p Uses suitably interpolated value for hanging nodes.
Implemented in oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, and oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_dresidual_contribution_axi_nst(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), and interpolated_p_axi_nst().
p_local_eqn()
virtual int oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::p_local_eqn (const unsigned & n) const [protected], [pure virtual]
Access function for the local equation number information for the pressure. p_local_eqn[n] = local equation number or < 0 if pinned.
Implemented in oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement, and oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
p_nodal_index_axi_nst()
virtual int oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::p_nodal_index_axi_nst () const [inline], [virtual]
Which nodal value represents the pressure?
Reimplemented in oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, and oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement.
Definition at line 618 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References Pressure_not_stored_at_node.
Referenced by oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), and oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
point_output_data()
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::point_output_data (const Vector< double > & s, Vector< double > & data) [inline], [virtual]
Output solution in data vector at local cordinates s: r,z,u_r,u_z,u_phi,p.
Reimplemented from oomph::FiniteElement.
Definition at line 768 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References i, interpolated_p_axi_nst(), interpolated_u_axi_nst(), oomph::FiniteElement::interpolated_x(), and s.
pressure_integral()
double oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::pressure_integral () const
Integral of pressure over element.
Return pressure integrated over the element.
Definition at line 1074 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References i, oomph::FiniteElement::integral_pt(), interpolated_p_axi_nst(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::Integral::nweight(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
pshape_axi_nst() [1/2]
virtual void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::pshape_axi_nst (const Vector< double > & s, Shape & psi) const [protected], [pure virtual]
Compute the pressure shape functions at local coordinate s.
Implemented in oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement, and oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_dresidual_contribution_axi_nst(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), and interpolated_p_axi_nst().
pshape_axi_nst() [2/2]
virtual void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::pshape_axi_nst (const Vector< double > & s, Shape & psi, Shape & test) const [protected], [pure virtual]
Compute the pressure shape and test functions at local coordinate s.
Implemented in oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement, and oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement.
re()
const double& oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::re () const [inline]
Reynolds number.
Definition at line 420 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References Re_pt.
Referenced by fill_in_contribution_to_hessian_vector_products(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
re_invfr()
const double& oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::re_invfr () const [inline]
Global inverse Froude number.
Definition at line 444 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References ReInvFr_pt.
Referenced by fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
re_invfr_pt()
double*& oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::re_invfr_pt () [inline]
Pointer to global inverse Froude number.
Definition at line 450 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References ReInvFr_pt.
Referenced by fill_in_generic_dresidual_contribution_axi_nst(), and oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::further_build().
re_invro()
const double& oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::re_invro () const [inline]
Global Reynolds number multiplied by inverse Rossby number.
Definition at line 456 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References ReInvRo_pt.
Referenced by fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
re_invro_pt()
double*& oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::re_invro_pt () [inline]
Pointer to global inverse Froude number.
Definition at line 462 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References ReInvRo_pt.
Referenced by fill_in_generic_dresidual_contribution_axi_nst(), and oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::further_build().
re_pt()
double*& oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::re_pt () [inline]
Pointer to Reynolds number.
Definition at line 432 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References Re_pt.
Referenced by fill_in_generic_dresidual_contribution_axi_nst(), and oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::further_build().
re_st()
const double& oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::re_st () const [inline]
Product of Reynolds and Strouhal number (=Womersley number)
Definition at line 426 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References ReSt_pt.
Referenced by fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
re_st_pt()
double*& oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::re_st_pt () [inline]
Pointer to product of Reynolds and Strouhal number (=Womersley number)
Definition at line 438 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References ReSt_pt.
Referenced by fill_in_generic_dresidual_contribution_axi_nst(), and oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::further_build().
scalar_name_paraview()
std::string oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::scalar_name_paraview (const unsigned & i) const [inline], [virtual]
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
Reimplemented from oomph::FiniteElement.
Definition at line 741 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References i, and oomph::StringConversion::to_string().
scalar_value_paraview()
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const [inline], [virtual]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
Definition at line 700 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References oomph::FiniteElement::get_s_plot(), i, interpolated_p_axi_nst(), interpolated_u_axi_nst(), oomph::FiniteElement::nplot_points_paraview(), and s.
strain_rate() [1/2]
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::strain_rate (const unsigned & t, const Vector< double > & s, DenseMatrix< double > & strain_rate) const
Strain-rate tensor: $ e_{ij} $ where $ i,j = r,z,\theta $ (in that order) at a specific time history value.
Get strain-rate tensor: $ e_{ij} $ where $ i,j = r,z,\theta $ (in that order) at a specific time.
Definition at line 850 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References oomph::FiniteElement::dshape_eulerian(), i, oomph::DenseMatrix< T >::ncol(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::DenseMatrix< T >::nrow(), s, t, u_index_axi_nst(), and oomph::Node::x().
strain_rate() [2/2]
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::strain_rate (const Vector< double > & s, DenseMatrix< double > & strain_rate) const
Strain-rate tensor: $ e_{ij} $ where $ i,j = r,z,\theta $ (in that order)
Get strain-rate tensor: $ e_{ij} $ where $ i,j = r,z,\theta $ (in that order)
Definition at line 749 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References oomph::FiniteElement::dshape_eulerian(), i, oomph::DenseMatrix< T >::ncol(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::DenseMatrix< T >::nrow(), s, and u_index_axi_nst().
Referenced by dissipation(), extrapolated_strain_rate(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_Z2_flux(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::get_Z2_flux(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::get_Z2_flux(), max_and_min_invariant_and_viscosity(), and traction().
traction()
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::traction (const Vector< double > & s, const Vector< double > & N, Vector< double > & traction) const
Compute traction (on the viscous scale) at local coordinate s for outer unit normal N.
Definition at line 657 of file generalised_newtonian_axisym_navier_stokes_elements.cc.
References Constitutive_eqn_pt, extrapolated_strain_rate(), i, interpolated_p_axi_nst(), oomph::QuadTreeNames::N, s, oomph::SecondInvariantHelper::second_invariant(), strain_rate(), Use_extrapolated_strainrate_to_compute_second_invariant, and oomph::GeneralisedNewtonianConstitutiveEquation< DIM >::viscosity().
Referenced by oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::get_traction(), and oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement::get_traction().
u_index_axi_nst()
virtual unsigned oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::u_index_axi_nst (const unsigned & i) const [inline], [virtual]
Return the index at which the i-th unknown velocity component is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
Definition at line 546 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References i.
Referenced by dinterpolated_u_axi_nst_ddata(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), du_dt_axi_nst(), fill_in_contribution_to_hessian_vector_products(), fill_in_generic_dresidual_contribution_axi_nst(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), get_pressure_and_velocity_mass_matrix_diagonal(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::identify_load_data(), interpolated_d_dudx_dX_axi_nst(), interpolated_duds_axi_nst(), interpolated_dudx_axi_nst(), interpolated_u_axi_nst(), output_veloc(), strain_rate(), and u_index_nst().
u_index_nst()
unsigned oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::u_index_nst (const unsigned & i) const [inline]
Return the index at which the i-th unknown velocity component is stored with a common interface for use in general FluidInterface and similar elements. To do: Merge all common storage etc to a common base class for Navier--Stokes elements in all coordinate systems.
Definition at line 556 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References u_index_axi_nst().
use_current_strainrate_to_compute_second_invariant()
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::use_current_strainrate_to_compute_second_invariant () [inline]
Switch to fully implict evaluation of non-Newtonian const eqn.
Definition at line 526 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References Use_extrapolated_strainrate_to_compute_second_invariant.
use_extrapolated_strainrate_to_compute_second_invariant()
void oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::use_extrapolated_strainrate_to_compute_second_invariant () [inline]
Use extrapolation for non-Newtonian const eqn.
Definition at line 532 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References Use_extrapolated_strainrate_to_compute_second_invariant.
viscosity_ratio()
const double& oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::viscosity_ratio () const [inline]
Viscosity ratio for element: Element's viscosity relative to the viscosity used in the definition of the Reynolds number.
Definition at line 494 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References Viscosity_Ratio_pt.
Referenced by oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
viscosity_ratio_pt()
double*& oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::viscosity_ratio_pt () [inline]
Pointer to Viscosity Ratio.
Definition at line 500 of file generalised_newtonian_axisym_navier_stokes_elements.h.
References Viscosity_Ratio_pt.
Referenced by oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::further_build().
Member Data Documentation
ALE_is_disabled
bool oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::ALE_is_disabled [protected]
Boolean flag to indicate if ALE formulation is disabled when the time-derivatives are computed. Only set to true if you're sure that the mesh is stationary.
Definition at line 188 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by disable_ALE(), enable_ALE(), fill_in_contribution_to_hessian_vector_products(), fill_in_generic_dresidual_contribution_axi_nst(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::further_build(), get_dresidual_dnodal_coordinates(), and oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
axi_nst_body_force_fct_pt
void(*&)(const double& time, const Vector<double>& x, Vector<double>& f) oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::axi_nst_body_force_fct_pt() [inline]
Access function for the body-force pointer.
Definition at line 506 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::further_build().
Body_force_fct_pt
void(* oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Body_force_fct_pt) (const double &time, const Vector< double > &x, Vector< double > &result) [protected]
Pointer to body force function.
Definition at line 171 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::further_build(), and get_body_force_axi_nst().
Constitutive_eqn_pt
GeneralisedNewtonianConstitutiveEquation<3>* oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Constitutive_eqn_pt [protected]
Pointer to the generalised Newtonian constitutive equation.
Definition at line 179 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by constitutive_eqn_pt(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), max_and_min_invariant_and_viscosity(), and traction().
Default_Gravity_vector
Vector< double > oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Default_Gravity_vector [static], [private]
Static default value for the gravity vector.
Navier-Stokes equations default gravity vector.
Definition at line 134 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by GeneralisedNewtonianAxisymmetricNavierStokesEquations().
Default_Physical_Constant_Value
double oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Default_Physical_Constant_Value [static], [private]
Static default value for the physical constants (all initialised to zero)
Definition at line 127 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by GeneralisedNewtonianAxisymmetricNavierStokesEquations().
Default_Physical_Ratio_Value
double oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Default_Physical_Ratio_Value [static], [private]
Static default value for the physical ratios (all are initialised to one)
Definition at line 131 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by GeneralisedNewtonianAxisymmetricNavierStokesEquations().
Density_Ratio_pt
double* oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Density_Ratio_pt [protected]
Pointer to the density ratio (relative to the density used in the definition of the Reynolds number)
Definition at line 149 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by density_ratio(), density_ratio_pt(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::further_build(), and GeneralisedNewtonianAxisymmetricNavierStokesEquations().
G_pt
Vector<double>* oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::G_pt [protected]
Pointer to global gravity Vector.
Definition at line 168 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::further_build(), g(), g_pt(), and GeneralisedNewtonianAxisymmetricNavierStokesEquations().
Gamma
Vector< double > oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Gamma [static]
Vector to decide whether the stress-divergence form is used or not.
Navier--Stokes equations static data.
Definition at line 415 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
Pre_multiply_by_viscosity_ratio
bool oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Pre_multiply_by_viscosity_ratio [static], [protected]
Static boolean telling us whether we pre-multiply the pressure and continuity by the viscosity ratio.
Definition at line 139 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by fill_in_generic_residual_contribution_axi_nst().
Pressure_not_stored_at_node
int oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Pressure_not_stored_at_node [static], [private]
Static `magic` number that indicates that the pressure is not stored at a node.
Definition at line 123 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by p_nodal_index_axi_nst().
Re_pt
double* oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Re_pt [protected]
Pointer to global Reynolds number.
Definition at line 154 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by fill_in_generic_dresidual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::further_build(), GeneralisedNewtonianAxisymmetricNavierStokesEquations(), re(), and re_pt().
ReInvFr_pt
double* oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::ReInvFr_pt [protected]
Pointer to global Reynolds number x inverse Froude number (= Bond number / Capillary number)
Definition at line 161 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::further_build(), GeneralisedNewtonianAxisymmetricNavierStokesEquations(), re_invfr(), and re_invfr_pt().
ReInvRo_pt
double* oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::ReInvRo_pt [protected]
Pointer to global Reynolds number x inverse Rossby number (used when in a rotating frame)
Definition at line 165 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::further_build(), GeneralisedNewtonianAxisymmetricNavierStokesEquations(), re_invro(), and re_invro_pt().
ReSt_pt
double* oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::ReSt_pt [protected]
Pointer to global Reynolds number x Strouhal number (=Womersley)
Definition at line 157 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::further_build(), GeneralisedNewtonianAxisymmetricNavierStokesEquations(), re_st(), and re_st_pt().
source_fct_pt
double(*&)(const double& time, const Vector<double>& x) oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::source_fct_pt() [inline]
Access function for the source-function pointer.
Definition at line 514 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::further_build().
Source_fct_pt
double(* oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Source_fct_pt) (const double &time, const Vector< double > &x) [protected]
Pointer to volumetric source function.
Definition at line 176 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::further_build(), and get_source_fct().
Use_extrapolated_strainrate_to_compute_second_invariant
bool oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Use_extrapolated_strainrate_to_compute_second_invariant [protected]
Definition at line 183 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), traction(), use_current_strainrate_to_compute_second_invariant(), and use_extrapolated_strainrate_to_compute_second_invariant().
Viscosity_Ratio_pt
double* oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::Viscosity_Ratio_pt [protected]
Pointer to the viscosity ratio (relative to the viscosity used in the definition of the Reynolds number)
Definition at line 145 of file generalised_newtonian_axisym_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::further_build(), GeneralisedNewtonianAxisymmetricNavierStokesEquations(), get_viscosity_ratio_axisym_nst(), viscosity_ratio(), and viscosity_ratio_pt().
The documentation for this class was generated from the following files:
generalised_newtonian_axisym_navier_stokes_elements.h
generalised_newtonian_axisym_navier_stokes_elements.cc