oomph::QPVDElement< DIM, NNODE_1D > Class Template Reference
An Element that solves the solid mechanics equations, based on the principle of virtual displacements in Cartesian coordinates, using SolidQElements for the interpolation of the variable positions.
#include <solid_elements.h>
Public Member Functions
QPVDElement ()
Constructor, there are no internal data points.
void output (std::ostream &outfile)
Output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
void output (FILE *file_pt)
C-style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function.
Additional Inherited Members
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::QPVDElement< DIM, NNODE_1D >
An Element that solves the solid mechanics equations, based on the principle of virtual displacements in Cartesian coordinates, using SolidQElements for the interpolation of the variable positions.
Definition at line 606 of file solid_elements.h.
Constructor & Destructor Documentation
QPVDElement()
template<unsigned DIM, unsigned NNODE_1D>
oomph::QPVDElement< DIM, NNODE_1D >::QPVDElement () [inline]
Constructor, there are no internal data points.
Definition at line 611 of file solid_elements.h.
Member Function Documentation
output() [1/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPVDElement< DIM, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function.
Reimplemented from oomph::PVDEquations< DIM >.
Definition at line 627 of file solid_elements.h.
References oomph::PVDEquations< DIM >::output().
output() [2/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPVDElement< DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function.
Reimplemented from oomph::PVDEquations< DIM >.
Definition at line 633 of file solid_elements.h.
References oomph::PVDEquations< DIM >::output().
output() [3/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPVDElement< DIM, NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function.
Reimplemented from oomph::PVDEquations< DIM >.
Definition at line 614 of file solid_elements.h.
References oomph::PVDEquations< DIM >::output().
output() [4/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPVDElement< DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function.
Reimplemented from oomph::PVDEquations< DIM >.
Definition at line 620 of file solid_elements.h.
References oomph::PVDEquations< DIM >::output().
The documentation for this class was generated from the following file:
solid_elements.h