oomph::SpectralElement Class Reference
#include <Qspectral_elements.h>
Public Member Functions
SpectralElement ()
virtual ~SpectralElement ()
Data * spectral_data_pt (const unsigned &i) const
Return the i-th data object associated with the polynomials of order p. Note that i <= p.
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the local dofs of the element. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers. If the boolean argument is true then store degrees of freedom at Dof_pt.
unsigned nspectral () const
Protected Attributes
Vector< Data * > * Spectral_data_pt
Additional Storage for shared spectral data.
Vector< unsigned > Spectral_order
Vector that represents the spectral order in each dimension.
Vector< unsigned > Nodal_spectral_order
Vector that represents the nodal spectral order.
DenseMatrix< int > Spectral_local_eqn
Local equation numbers for the spectral degrees of freedom.
Additional Inherited Members
Detailed Description
Definition at line 152 of file Qspectral_elements.h.
Constructor & Destructor Documentation
SpectralElement()
oomph::SpectralElement::SpectralElement () [inline]
Definition at line 168 of file Qspectral_elements.h.
 SpectralElement()
virtual oomph::SpectralElement::~SpectralElement () [inline], [virtual]
Definition at line 170 of file Qspectral_elements.h.
Member Function Documentation
assign_all_generic_local_eqn_numbers()
virtual void oomph::SpectralElement::assign_all_generic_local_eqn_numbers (const bool & store_local_dof_pt) [inline], [virtual]
Assign the local equation numbers. If the boolean argument is true then store degrees of freedom at Dof_pt.
Reimplemented from oomph::FiniteElement.
Definition at line 229 of file Qspectral_elements.h.
References oomph::FiniteElement::assign_all_generic_local_eqn_numbers(), oomph::GeneralisedElement::Dof_pt_deque, oomph::Data::eqn_number(), oomph::Data::Is_pinned, oomph::Data::Is_unclassified, n, oomph::Data::nvalue(), oomph::DenseMatrix< T >::resize(), and oomph::Data::value_pt().
describe_local_dofs()
virtual void oomph::SpectralElement::describe_local_dofs (std::ostream & out, const std::string & current_string) const [inline], [virtual]
Function to describe the local dofs of the element. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
Reimplemented from oomph::FiniteElement.
Definition at line 195 of file Qspectral_elements.h.
References oomph::Data::describe_dofs(), oomph::FiniteElement::describe_local_dofs(), n, and oomph::Global_string_for_annotation::string().
nspectral()
unsigned oomph::SpectralElement::nspectral () const [inline]
Definition at line 342 of file Qspectral_elements.h.
spectral_data_pt()
Data* oomph::SpectralElement::spectral_data_pt (const unsigned & i) const [inline]
Return the i-th data object associated with the polynomials of order p. Note that i <= p.
Definition at line 182 of file Qspectral_elements.h.
References i.
Member Data Documentation
Nodal_spectral_order
Vector<unsigned> oomph::SpectralElement::Nodal_spectral_order [protected]
Vector that represents the nodal spectral order.
Definition at line 162 of file Qspectral_elements.h.
Spectral_data_pt
Vector<Data*>* oomph::SpectralElement::Spectral_data_pt [protected]
Additional Storage for shared spectral data.
Definition at line 156 of file Qspectral_elements.h.
Spectral_local_eqn
DenseMatrix<int> oomph::SpectralElement::Spectral_local_eqn [protected]
Local equation numbers for the spectral degrees of freedom.
Definition at line 165 of file Qspectral_elements.h.
Spectral_order
Vector<unsigned> oomph::SpectralElement::Spectral_order [protected]
Vector that represents the spectral order in each dimension.
Definition at line 159 of file Qspectral_elements.h.
The documentation for this class was generated from the following file:
Qspectral_elements.h