oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM > Class Template Reference
///////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
#include <womersley_elements.h>
Public Member Functions
NavierStokesImpedanceTractionElement (FiniteElement *const &element_pt, const int &face_index)
Constructor, which takes a `bulk` element and the value of the index and its limit.
~NavierStokesImpedanceTractionElement ()
Destructor should not delete anything.
Mesh *& navier_stokes_outflow_mesh_pt ()
Access to mesh containing all NavierStokesImpedanceTractionElements that contribute to the volume flux into the `downstream tube` that provides the impedance.
double get_volume_flux ()
Get integral of volume flux through element.
void set_external_data_from_navier_stokes_outflow_mesh (Mesh *navier_stokes_outflow_mesh_pt)
NavierStokesImpedanceTractionElements that contribute to the volume flux into the downstream `impedance tube` to the element and classify all nodes in that mesh as external Data for this element (unless the nodes are also the element's own nodes, of course).
void set_aux_integral_pt (std::map< unsigned, double > *aux_integral_pt)
Set pointer to the precomputed auxiliary integral that contains the derivative of the total volume flux through the outflow boundary of the (higher-dimensional) Navier-Stokes mesh w.r.t. to the discrete (global) (velocity) degrees of freedom.
double total_volume_flux_into_downstream_tube ()
Compute total volume flux into the `downstream tube` that provides the impedance (computed by adding up the flux through all NavierStokesImpedanceTractionElements in the mesh specified by volume_flux_mesh_pt().
void set_impedance_tube_pt (TemplateFreeWomersleyImpedanceTubeBase *impedance_tube_pt)
Set pointer to `impedance tube` that provides the flow resistance.
void add_element_contribution_to_aux_integral (std::map< unsigned, double > *aux_integral_pt)
Add the element's contribution to the auxiliary integral that contains the derivative of the total volume flux through the outflow boundary of the (higher-dimensional) Navier-Stokes mesh w.r.t. to the discrete (global) (velocity) degrees of freedom.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in the element's contribution to the element's residual vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Fill in the element's contribution to the element's residual vector and Jacobian matrix.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,[z],u,v,[w],p in tecplot format.
Protected Member Functions
virtual int u_local_eqn (const unsigned &n, const unsigned &i)
Access function that returns the local equation numbers for velocity components. u_local_eqn(n,i) = local equation number or < 0 if pinned. The default is to asssume that n is the local node number and the i-th velocity component is the i-th unknown stored at the node.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping.
void fill_in_generic_residual_contribution_fluid_traction (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
Private Attributes
std::map< unsigned, double > * Aux_integral_pt
Pointer to auxiliary integral, containing the derivative of the total volume flux through the outflow boundary of the (higher-dimensional) Navier-Stokes mesh w.r.t. to the discrete (global) (velocity) degrees of freedom.
WomersleyImpedanceTubeBase< WOMERSLEY_ELEMENT, DIM > * Impedance_tube_pt
Pointer to ImpedanceTubeProblem that computes the flow resistance.
Additional Inherited Members
Detailed Description
template<class BULK_NAVIER_STOKES_ELEMENT, class WOMERSLEY_ELEMENT, unsigned DIM>
class oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >
///////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// A class for elements that allow the imposition of an impedance type traction boundary condition to the Navier--Stokes equations The geometrical information can be read from the FaceGeometery<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class. Template arguments specify the type of the bulk Navier Stokes elements that the elements are attached to, and the type of the Womersley element used to compute the flow resistance in the downstream `impedance tube`.
Definition at line 1978 of file womersley_elements.h.
Constructor & Destructor Documentation
NavierStokesImpedanceTractionElement()
template<class BULK_NAVIER_STOKES_ELEMENT , class WOMERSLEY_ELEMENT , unsigned DIM>
oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::NavierStokesImpedanceTractionElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit.
Definition at line 2038 of file womersley_elements.h.
References oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::Aux_integral_pt, oomph::FiniteElement::build_face_element(), oomph::FaceElement::face_index(), oomph::FiniteElement::has_hanging_nodes(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::Impedance_tube_pt, and oomph::NavierStokesImpedanceTractionElementBase::Navier_stokes_outflow_mesh_pt.
 NavierStokesImpedanceTractionElement()
template<class BULK_NAVIER_STOKES_ELEMENT , class WOMERSLEY_ELEMENT , unsigned DIM>
oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::~NavierStokesImpedanceTractionElement () [inline]
Destructor should not delete anything.
Definition at line 2089 of file womersley_elements.h.
Member Function Documentation
add_element_contribution_to_aux_integral()
template<class BULK_NAVIER_STOKES_ELEMENT , class WOMERSLEY_ELEMENT , unsigned DIM>
void oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::add_element_contribution_to_aux_integral (std::map< unsigned, double > * aux_integral_pt) [inline], [virtual]
Add the element's contribution to the auxiliary integral that contains the derivative of the total volume flux through the outflow boundary of the (higher-dimensional) Navier-Stokes mesh w.r.t. to the discrete (global) (velocity) degrees of freedom.
Implements oomph::NavierStokesImpedanceTractionElementBase.
Definition at line 2300 of file womersley_elements.h.
References i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::J_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FaceElement::outer_unit_normal(), s, oomph::FiniteElement::shape(), and oomph::W.
fill_in_contribution_to_jacobian()
template<class BULK_NAVIER_STOKES_ELEMENT , class WOMERSLEY_ELEMENT , unsigned DIM>
void oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Fill in the element's contribution to the element's residual vector and Jacobian matrix.
Reimplemented from oomph::FiniteElement.
Definition at line 2377 of file womersley_elements.h.
References oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::fill_in_generic_residual_contribution_fluid_traction(), and oomph::FiniteElement::jacobian.
fill_in_contribution_to_residuals()
template<class BULK_NAVIER_STOKES_ELEMENT , class WOMERSLEY_ELEMENT , unsigned DIM>
void oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Fill in the element's contribution to the element's residual vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 2366 of file womersley_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::fill_in_generic_residual_contribution_fluid_traction().
fill_in_generic_residual_contribution_fluid_traction()
template<class BULK_NAVIER_STOKES_ELEMENT , class WOMERSLEY_ELEMENT , unsigned DIM>
void oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::fill_in_generic_residual_contribution_fluid_traction (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [protected]
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Function that returns the residuals for the imposed traction Navier_Stokes equations
Definition at line 2427 of file womersley_elements.h.
References oomph::Data::eqn_number(), i, and oomph::W.
Referenced by oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::fill_in_contribution_to_jacobian(), and oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::fill_in_contribution_to_residuals().
get_volume_flux()
template<class BULK_NAVIER_STOKES_ELEMENT , class WOMERSLEY_ELEMENT , unsigned DIM>
double oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::get_volume_flux () [inline], [virtual]
Get integral of volume flux through element.
Implements oomph::NavierStokesImpedanceTractionElementBase.
Definition at line 2100 of file womersley_elements.h.
References oomph::FaceElement::bulk_element_pt(), oomph::FaceElement::get_local_coordinate_in_bulk(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::FaceElement::J_eulerian(), oomph::FaceElement::outer_unit_normal(), s, oomph::W, and oomph::x.
Referenced by oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::total_volume_flux_into_downstream_tube().
navier_stokes_outflow_mesh_pt()
template<class BULK_NAVIER_STOKES_ELEMENT , class WOMERSLEY_ELEMENT , unsigned DIM>
Mesh *& oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::navier_stokes_outflow_mesh_pt () [inline]
Access to mesh containing all NavierStokesImpedanceTractionElements that contribute to the volume flux into the `downstream tube` that provides the impedance.
Definition at line 2094 of file womersley_elements.h.
References oomph::NavierStokesImpedanceTractionElementBase::Navier_stokes_outflow_mesh_pt.
Referenced by oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::set_external_data_from_navier_stokes_outflow_mesh().
output() [1/2]
template<class BULK_NAVIER_STOKES_ELEMENT , class WOMERSLEY_ELEMENT , unsigned DIM>
void oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Definition at line 2400 of file womersley_elements.h.
References oomph::FiniteElement::output().
output() [2/2]
template<class BULK_NAVIER_STOKES_ELEMENT , class WOMERSLEY_ELEMENT , unsigned DIM>
void oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format.
Reimplemented from oomph::FiniteElement.
Definition at line 2406 of file womersley_elements.h.
References oomph::FiniteElement::output().
set_aux_integral_pt()
template<class BULK_NAVIER_STOKES_ELEMENT , class WOMERSLEY_ELEMENT , unsigned DIM>
void oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::set_aux_integral_pt (std::map< unsigned, double > * aux_integral_pt) [inline], [virtual]
Set pointer to the precomputed auxiliary integral that contains the derivative of the total volume flux through the outflow boundary of the (higher-dimensional) Navier-Stokes mesh w.r.t. to the discrete (global) (velocity) degrees of freedom.
Implements oomph::NavierStokesImpedanceTractionElementBase.
Definition at line 2242 of file womersley_elements.h.
References oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::Aux_integral_pt.
set_external_data_from_navier_stokes_outflow_mesh()
template<class BULK_NAVIER_STOKES_ELEMENT , class WOMERSLEY_ELEMENT , unsigned DIM>
void oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::set_external_data_from_navier_stokes_outflow_mesh (Mesh * navier_stokes_outflow_mesh_pt) [inline], [virtual]
NavierStokesImpedanceTractionElements that contribute to the volume flux into the downstream `impedance tube` to the element and classify all nodes in that mesh as external Data for this element (unless the nodes are also the element's own nodes, of course).
Implements oomph::NavierStokesImpedanceTractionElementBase.
Definition at line 2199 of file womersley_elements.h.
References oomph::GeneralisedElement::add_external_data(), e, oomph::Mesh::finite_element_pt(), oomph::NavierStokesImpedanceTractionElementBase::Navier_stokes_outflow_mesh_pt, oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::navier_stokes_outflow_mesh_pt(), oomph::Mesh::nelement(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
set_impedance_tube_pt()
template<class BULK_NAVIER_STOKES_ELEMENT , class WOMERSLEY_ELEMENT , unsigned DIM>
void oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::set_impedance_tube_pt (TemplateFreeWomersleyImpedanceTubeBase * impedance_tube_pt) [inline], [virtual]
Set pointer to `impedance tube` that provides the flow resistance.
Implements oomph::NavierStokesImpedanceTractionElementBase.
Definition at line 2287 of file womersley_elements.h.
References oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::Impedance_tube_pt.
shape_and_test_at_knot()
template<class BULK_NAVIER_STOKES_ELEMENT , class WOMERSLEY_ELEMENT , unsigned DIM>
double oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping.
Definition at line 2007 of file womersley_elements.h.
References i, oomph::FaceElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape_at_knot().
total_volume_flux_into_downstream_tube()
template<class BULK_NAVIER_STOKES_ELEMENT , class WOMERSLEY_ELEMENT , unsigned DIM>
double oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::total_volume_flux_into_downstream_tube () [inline]
Compute total volume flux into the `downstream tube` that provides the impedance (computed by adding up the flux through all NavierStokesImpedanceTractionElements in the mesh specified by volume_flux_mesh_pt().
Definition at line 2252 of file womersley_elements.h.
References e, oomph::Mesh::element_pt(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::get_volume_flux(), oomph::NavierStokesImpedanceTractionElementBase::Navier_stokes_outflow_mesh_pt, and oomph::Mesh::nelement().
u_local_eqn()
template<class BULK_NAVIER_STOKES_ELEMENT , class WOMERSLEY_ELEMENT , unsigned DIM>
virtual int oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::u_local_eqn (const unsigned & n, const unsigned & i) [inline], [protected], [virtual]
Access function that returns the local equation numbers for velocity components. u_local_eqn(n,i) = local equation number or < 0 if pinned. The default is to asssume that n is the local node number and the i-th velocity component is the i-th unknown stored at the node.
Definition at line 2000 of file womersley_elements.h.
References i, and oomph::FiniteElement::nodal_local_eqn().
zeta_nodal()
template<class BULK_NAVIER_STOKES_ELEMENT , class WOMERSLEY_ELEMENT , unsigned DIM>
double oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Reimplemented from oomph::FaceElement.
Definition at line 2391 of file womersley_elements.h.
References i, and oomph::FaceElement::zeta_nodal().
Member Data Documentation
Aux_integral_pt
template<class BULK_NAVIER_STOKES_ELEMENT , class WOMERSLEY_ELEMENT , unsigned DIM>
std::map<unsigned, double>* oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::Aux_integral_pt [private]
Pointer to auxiliary integral, containing the derivative of the total volume flux through the outflow boundary of the (higher-dimensional) Navier-Stokes mesh w.r.t. to the discrete (global) (velocity) degrees of freedom.
Definition at line 1988 of file womersley_elements.h.
Referenced by oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::NavierStokesImpedanceTractionElement(), and oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::set_aux_integral_pt().
Impedance_tube_pt
template<class BULK_NAVIER_STOKES_ELEMENT , class WOMERSLEY_ELEMENT , unsigned DIM>
WomersleyImpedanceTubeBase<WOMERSLEY_ELEMENT, DIM>* oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::Impedance_tube_pt [private]
Pointer to ImpedanceTubeProblem that computes the flow resistance.
Definition at line 1991 of file womersley_elements.h.
Referenced by oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::NavierStokesImpedanceTractionElement(), and oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::set_impedance_tube_pt().
The documentation for this class was generated from the following file:
womersley_elements.h