oomph::GeomObject Class Reference
A geometric object is an object that provides a parametrised description of its shape via the function GeomObject::position(...).
#include <geom_objects.h>
Public Member Functions
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
Constructor: Pass dimension of geometric object (# of Eulerian coords = # of Lagrangian coords; no time history available/needed)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
Constructor: pass # of Eulerian and Lagrangian coordinates. No time history available/needed.
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
Constructor: pass # of Eulerian and Lagrangian coordinates and pointer to time-stepper which is used to handle the position at previous timesteps and allows the evaluation of veloc/acceleration etc. in cases where the GeomData varies with time.
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
Access function for pointer to time stepper: Null if object is not time-dependent.
TimeStepper * time_stepper_pt () const
Access function for pointer to time stepper: Null if object is not time-dependent. Const version.
virtual unsigned ngeom_data () const
How many items of Data does the shape of the object depend on? This is implemented as a broken virtual function. You must overload this for GeomObjects that contain geometric Data, i.e. GeomObjects whose shape depends on Data that may contain unknowns in the overall Problem.
virtual Data * geom_data_pt (const unsigned &j)
Return pointer to the j-th Data item that the object's shape depends on. This is implemented as a broken virtual function. You must overload this for GeomObjects that contain geometric Data, i.e. GeomObjects whose shape depends on Data that may contain unknowns in the overall Problem.
virtual void position (const Vector< double > &zeta, Vector< double > &r) const =0
Parametrised position on object at current time: r(zeta).
virtual void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Works for t=0 but needs to be overloaded if genuine time-dependence is required.
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
Parametrised position on object: r(zeta). Evaluated at the continuous time value, t.
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
j-th time-derivative on object at current time: $ \frac{d^{j} r(\zeta)}{dt^j} $.
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
Derivative of position Vector w.r.t. to coordinates: $ \frac{dR_i}{d \zeta_\alpha}$ = drdzeta(alpha,i). Evaluated at current time.
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
2nd derivative of position Vector w.r.t. to coordinates: $ \frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}$ = ddrdzeta(alpha,beta,i). Evaluated at current time.
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Posn Vector and its 1st & 2nd derivatives w.r.t. to coordinates: $ \frac{dR_i}{d \zeta_\alpha}$ = drdzeta(alpha,i). $ \frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}$ = ddrdzeta(alpha,beta,i). Evaluated at current time.
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
A geometric object may be composed of may sub-objects (e.g. a finite-element representation of a boundary). In order to implement sparse update functions, it is necessary to know the sub-object and local coordinate within that sub-object at a given intrinsic coordinate, zeta. Note that only one sub-object can "cover" any given intrinsic position. If the position is at an "interface" between sub-objects, either one can be returned. The default implementation merely returns, the pointer to the "entire" GeomObject and the coordinate, zeta The optional boolean flag only applies if a Newton method is used to find the value of zeta, and if true the value of the coordinate s is used as the initial guess for the method. If the flag is false (the default) a value of s=0 is used as the initial guess.
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
A geometric object may be composed of many sub-objects each with their own local coordinate. This function returns the "global" intrinsic coordinate zeta (within the compound object), at a given local coordinate s (i.e. the intrinsic coordinate of the sub-GeomObject. In simple (non-compound) GeomObjects, the local intrinsic coordinate is the global intrinsic coordinate and so the function merely returns s. To make it less likely that the default implementation is called in error (because it is not overloaded in a derived GeomObject where the default is not appropriate, we do at least check that s and zeta have the same size if called in PARANOID mode.
Protected Attributes
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Timestepper (used to handle access to geometry at previous timesteps)
Detailed Description
A geometric object is an object that provides a parametrised description of its shape via the function GeomObject::position(...).
The minimum functionality is: The geometric object has a number of Lagrangian (intrinsic) coordinates that parametrise the (Eulerian) position vector, whose dimension might differ from the number of Lagrangian (intrinsic) coordinates (e.g. for shell-like objects).
We might also need the derivatives of the position Vector w.r.t. to the Lagrangian (intrinsic) coordinates and interfaces for this functionality are provided. [Note: For some geometric objects it might be too tedious to work out the derivatives and they might not be needed anyway. In other cases we might always need the position vector and all derivatives at the same time. We provide suitable interfaces for these cases in virtual but broken (rather than pure virtual) form so the user can (but doesn't have to) provide the required versions by overloading.]
The shape of a geometric object is usually determined by a number of parameters whose value might have to be determined as part of the overall solution (e.g. for geometric objects that represent elastic walls). The geometric object therefore has a vector of (pointers to) geometric Data, which can be free/pinned and have a time history, etc. This makes it possible to `upgrade' GeomObjects to GeneralisedElements -- in this case the geometric Data plays the role of internal Data in the GeneralisedElement. Conversely, FiniteElements, in which a geometry (spatial coordinate) has been defined, inherit from GeomObjects, which is particularly useful in FSI computations: Meshing of moving domains is typically performed by representing the domain as an object of type Domain and, by default, Domain boundaries are represented by GeomObjects. In FSI computations, the boundary of the fluid domain is represented by a number of solid mechanics elements. These elements are, in fact, GeomObjects via inheritance so that the we can use the standard interfaces of the GeomObject class for mesh generation. An example is the class FSIHermiteBeamElement which is derived from the class HermiteBeamElement (a `normal' beam element) and the GeomObject class.
The shape of a geometric object can have an explicit time-dependence, for instance in cases where a domain boundary is performing prescribed motions. We provide access to the `global' time by giving the object a pointer to a timestepping scheme. [Note that, within the overall FE code, time is only ever evaluated at discrete instants (which are accessible via the timestepper), never in continuous form]. The timestepper is also needed to evaluate time-derivatives if the geometric Data carries a time history.
Definition at line 100 of file geom_objects.h.
Constructor & Destructor Documentation
GeomObject() [1/5]
oomph::GeomObject::GeomObject () [inline]
Default constructor.
Definition at line 104 of file geom_objects.h.
GeomObject() [2/5]
oomph::GeomObject::GeomObject (const unsigned & ndim) [inline]
Constructor: Pass dimension of geometric object (# of Eulerian coords = # of Lagrangian coords; no time history available/needed)
Definition at line 108 of file geom_objects.h.
GeomObject() [3/5]
oomph::GeomObject::GeomObject (const unsigned & nlagrangian, const unsigned & ndim) [inline]
Constructor: pass # of Eulerian and Lagrangian coordinates. No time history available/needed.
Definition at line 116 of file geom_objects.h.
References ndim(), and nlagrangian().
GeomObject() [4/5]
oomph::GeomObject::GeomObject (const unsigned & nlagrangian, const unsigned & ndim, TimeStepper * time_stepper_pt) [inline]
Constructor: pass # of Eulerian and Lagrangian coordinates and pointer to time-stepper which is used to handle the position at previous timesteps and allows the evaluation of veloc/acceleration etc. in cases where the GeomData varies with time.
Definition at line 139 of file geom_objects.h.
References ndim(), and nlagrangian().
GeomObject() [5/5]
oomph::GeomObject::GeomObject (const GeomObject & dummy) [delete]
Broken copy constructor.
~GeomObject()
virtual oomph::GeomObject::~GeomObject () [inline], [virtual]
(Empty) destructor
Definition at line 168 of file geom_objects.h.
Member Function Documentation
d2position() [1/2]
virtual void oomph::GeomObject::d2position (const Vector< double > & zeta, RankThreeTensor< double > & ddrdzeta) const [inline], [virtual]
2nd derivative of position Vector w.r.t. to coordinates: $ \frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}$ = ddrdzeta(alpha,beta,i). Evaluated at current time.
Reimplemented in oomph::StraightLine, oomph::Ellipse, and oomph::EllipticalTube.
Definition at line 341 of file geom_objects.h.
Referenced by oomph::CircularCylindricalShellMesh< ELEMENT >::assign_undeformed_positions(), oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals_beam(), oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_residuals_shell(), oomph::KirchhoffLoveShellEquations::get_energy(), oomph::KirchhoffLoveBeamEquations::get_energy(), and oomph::KirchhoffLoveShellEquations::get_strain_and_bend().
d2position() [2/2]
virtual void oomph::GeomObject::d2position (const Vector< double > & zeta, Vector< double > & r, DenseMatrix< double > & drdzeta, RankThreeTensor< double > & ddrdzeta) const [inline], [virtual]
Posn Vector and its 1st & 2nd derivatives w.r.t. to coordinates: $ \frac{dR_i}{d \zeta_\alpha}$ = drdzeta(alpha,i). $ \frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}$ = ddrdzeta(alpha,beta,i). Evaluated at current time.
Reimplemented in oomph::StraightLine, oomph::Ellipse, and oomph::EllipticalTube.
Definition at line 357 of file geom_objects.h.
dposition()
virtual void oomph::GeomObject::dposition (const Vector< double > & zeta, DenseMatrix< double > & drdzeta) const [inline], [virtual]
Derivative of position Vector w.r.t. to coordinates: $ \frac{dR_i}{d \zeta_\alpha}$ = drdzeta(alpha,i). Evaluated at current time.
Reimplemented in oomph::MeshAsGeomObject, oomph::StraightLine, and oomph::Ellipse.
Definition at line 327 of file geom_objects.h.
dposition_dt()
virtual void oomph::GeomObject::dposition_dt (const Vector< double > & zeta, const unsigned & j, Vector< double > & drdt) [inline], [virtual]
j-th time-derivative on object at current time: $ \frac{d^{j} r(\zeta)}{dt^j} $.
Reimplemented in oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >, oomph::PseudoBucklingRing, oomph::ImmersedRigidBodyElement, and oomph::FiniteElement.
Definition at line 292 of file geom_objects.h.
References i, position(), and oomph::FiniteElement::size().
Referenced by oomph::SolidFiniteElement::fill_in_generic_jacobian_for_solid_ic().
geom_data_pt()
virtual Data * oomph::GeomObject::geom_data_pt (const unsigned & j) [inline], [virtual]
Return pointer to the j-th Data item that the object's shape depends on. This is implemented as a broken virtual function. You must overload this for GeomObjects that contain geometric Data, i.e. GeomObjects whose shape depends on Data that may contain unknowns in the overall Problem.
Reimplemented in oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >, oomph::FiniteElement, oomph::SolidFiniteElement, oomph::FaceElementAsGeomObject< ELEMENT >, oomph::StraightLine, oomph::Ellipse, oomph::Circle, oomph::MeshAsGeomObject, oomph::PseudoBucklingRing, oomph::RefineableSolidElement, and oomph::ImmersedRigidBodyElement.
Definition at line 233 of file geom_objects.h.
Referenced by oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt().
interpolated_zeta()
virtual void oomph::GeomObject::interpolated_zeta (const Vector< double > & s, Vector< double > & zeta) const [inline], [virtual]
A geometric object may be composed of many sub-objects each with their own local coordinate. This function returns the "global" intrinsic coordinate zeta (within the compound object), at a given local coordinate s (i.e. the intrinsic coordinate of the sub-GeomObject. In simple (non-compound) GeomObjects, the local intrinsic coordinate is the global intrinsic coordinate and so the function merely returns s. To make it less likely that the default implementation is called in error (because it is not overloaded in a derived GeomObject where the default is not appropriate, we do at least check that s and zeta have the same size if called in PARANOID mode.
Reimplemented in oomph::FiniteElement.
Definition at line 404 of file geom_objects.h.
References s, and oomph::FiniteElement::size().
locate_zeta()
virtual void oomph::GeomObject::locate_zeta (const Vector< double > & zeta, GeomObject *& sub_geom_object_pt, Vector< double > & s, const bool & use_coordinate_as_initial_guess = false) [inline], [virtual]
A geometric object may be composed of may sub-objects (e.g. a finite-element representation of a boundary). In order to implement sparse update functions, it is necessary to know the sub-object and local coordinate within that sub-object at a given intrinsic coordinate, zeta. Note that only one sub-object can "cover" any given intrinsic position. If the position is at an "interface" between sub-objects, either one can be returned. The default implementation merely returns, the pointer to the "entire" GeomObject and the coordinate, zeta The optional boolean flag only applies if a Newton method is used to find the value of zeta, and if true the value of the coordinate s is used as the initial guess for the method. If the flag is false (the default) a value of s=0 is used as the initial guess.
Reimplemented in oomph::FSIHermiteBeamElement, oomph::FiniteElement, and oomph::MeshAsGeomObject.
Definition at line 381 of file geom_objects.h.
References s.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt(), oomph::RefineableAlgebraicChannelWithLeafletMesh< ELEMENT >::update_node_update(), oomph::RefineableAlgebraicCollapsibleChannelMesh< ELEMENT >::update_node_update(), oomph::RefineableAlgebraicCylinderWithFlagMesh< ELEMENT >::update_node_update(), oomph::AlgebraicFishMesh< ELEMENT >::update_node_update(), and oomph::RefineableAlgebraicFSIDrivenCavityMesh< ELEMENT >::update_node_update().
ndim()
unsigned oomph::GeomObject::ndim () const [inline]
Access function to # of Eulerian coordinates.
Definition at line 177 of file geom_objects.h.
References Ndim.
Referenced by oomph::NonLinearElasticitySmoothMesh< ELEMENT >::actions_before_newton_solve(), oomph::Problem::adapt(), oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::GeneralisedElement::assign_local_eqn_numbers(), oomph::NonLinearElasticitySmoothMesh< ELEMENT >::backup(), oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::BackupMeshForProjection(), oomph::RefineableQElement< 3 >::build(), oomph::RefineableQElement< 2 >::build(), oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 1, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 2, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 3, NNODE_1D >::build_face_element(), oomph::Mesh::check_for_repeated_nodes(), oomph::Mesh::check_halo_schemes(), oomph::Multi_domain_functions::construct_new_external_halo_master_node_helper(), oomph::Missing_masters_functions::construct_new_external_halo_master_node_helper(), oomph::Multi_domain_functions::construct_new_external_halo_node_helper(), oomph::Missing_masters_functions::construct_new_external_halo_node_helper(), oomph::RefineableTriangleMesh< ELEMENT >::construct_new_halo_node_helper(), oomph::RefineableTriangleMesh< ELEMENT >::construct_new_node_load_balance_helper(), oomph::Node::copy(), oomph::Mesh::delete_all_external_storage(), oomph::Mesh::distribute(), oomph::FSI_functions::doc_fsi(), oomph::Mesh::doc_mesh_distribution(), oomph::Mesh::doc_shared_nodes(), oomph::FSIHermiteBeamElement::dposition_dlagrangian_at_local_coordinate(), oomph::FSIDiagHermiteShellElement::dposition_dlagrangian_at_local_coordinate(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::drag_force(), oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals_beam(), GeomObject(), GeomObject(), oomph::Problem::get_data_to_be_sent_during_load_balancing(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::get_drag_and_torque(), oomph::KirchhoffLoveShellEquations::get_energy(), oomph::KirchhoffLoveBeamEquations::get_energy(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_kinetic_energy_flux(), oomph::KirchhoffLoveBeamEquations::get_non_unit_tangent(), oomph::KirchhoffLoveBeamEquations::get_normal(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work_components(), oomph::Missing_masters_functions::get_required_master_nodal_information_helper(), oomph::Multi_domain_functions::get_required_master_nodal_information_helper(), oomph::Missing_masters_functions::get_required_nodal_information_helper(), oomph::Multi_domain_functions::get_required_nodal_information_helper(), oomph::RefineableTriangleMesh< ELEMENT >::get_required_nodal_information_helper(), oomph::RefineableTriangleMesh< ELEMENT >::get_required_nodal_information_load_balance_helper(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux(), oomph::NodeOrdering::node_global_position_comparison(), oomph::AlgebraicMesh::node_update(), oomph::Mesh::node_update(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update_central_region(), oomph::AlgebraicFishMesh< ELEMENT >::node_update_in_body(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update_in_central_box(), oomph::AlgebraicFishMesh< ELEMENT >::node_update_in_fin(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update_in_lower_right_box(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update_in_upper_left_box(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update_lower_right_region(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update_upper_left_region(), oomph::LinearElasticitySmoothMesh< LINEAR_ELASTICITY_ELEMENT >::operator()(), oomph::PoissonSmoothMesh< POISSON_ELEMENT >::operator()(), oomph::HermiteBeamElement::output(), oomph::DummyFaceElement< ELEMENT >::output(), oomph::HermiteBeamElement::output(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >::output(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >::output(), oomph::TriangleMesh< ELEMENT >::output_boundary_coordinates(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::p_refine(), oomph::Tree::p_refine_if_required(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project(), oomph::Data::read(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::rebuild_from_sons(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::rebuild_from_sons(), oomph::RefineableQSpectralElement< 3 >::rebuild_from_sons(), oomph::RefineableQSpectralElement< 2 >::rebuild_from_sons(), oomph::Problem::remove_duplicate_data(), oomph::NonLinearElasticitySmoothMesh< ELEMENT >::reset(), oomph::Mesh::resize_halo_nodes(), oomph::ContinuationStorageScheme::set_consistent_pinned_positions(), oomph::Problem::set_pinned_values_to_zero(), oomph::Tree::split_if_required(), oomph::WomersleyMesh< WOMERSLEY_ELEMENT >::WomersleyMesh(), and oomph::DiskLikeGeomObjectWithBoundaries::zeta_on_boundary().
ngeom_data()
virtual unsigned oomph::GeomObject::ngeom_data () const [inline], [virtual]
How many items of Data does the shape of the object depend on? This is implemented as a broken virtual function. You must overload this for GeomObjects that contain geometric Data, i.e. GeomObjects whose shape depends on Data that may contain unknowns in the overall Problem.
Reimplemented in oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >, oomph::ElementWithMovingNodes, oomph::FiniteElement, oomph::SolidFiniteElement, oomph::FaceElementAsGeomObject< ELEMENT >, oomph::StraightLine, oomph::Ellipse, oomph::Circle, oomph::EllipticalTube, oomph::MeshAsGeomObject, oomph::PseudoBucklingRing, oomph::RefineableSolidElement, and oomph::ImmersedRigidBodyElement.
Definition at line 209 of file geom_objects.h.
Referenced by oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt().
nlagrangian()
unsigned oomph::GeomObject::nlagrangian () const [inline]
Access function to # of Lagrangian coordinates.
Definition at line 171 of file geom_objects.h.
References NLagrangian.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::Multi_domain_functions::aux_setup_multi_domain_interaction(), oomph::SolidNode::copy(), oomph::Mesh::delete_all_external_storage(), oomph::FSIHermiteBeamElement::dposition_dlagrangian_at_local_coordinate(), oomph::FSIDiagHermiteShellElement::dposition_dlagrangian_at_local_coordinate(), oomph::DummyErrorEstimator::DummyErrorEstimator(), oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals_beam(), GeomObject(), GeomObject(), oomph::KirchhoffLoveShellEquations::get_energy(), oomph::KirchhoffLoveBeamEquations::get_energy(), oomph::KirchhoffLoveBeamEquations::get_non_unit_tangent(), oomph::KirchhoffLoveBeamEquations::get_normal(), oomph::Missing_masters_functions::get_required_master_nodal_information_helper(), oomph::Multi_domain_functions::get_required_master_nodal_information_helper(), oomph::AlgebraicFishMesh< ELEMENT >::node_update_in_body(), oomph::AlgebraicFishMesh< ELEMENT >::node_update_in_fin(), oomph::HermiteBeamElement::output(), oomph::SolidQHermiteElement< DIM >::output(), oomph::SolidQElement< 1, NNODE_1D >::output(), oomph::SolidQElement< 2, NNODE_1D >::output(), oomph::SolidQElement< 3, NNODE_1D >::output(), oomph::SolidQHermiteElement< DIM >::output(), oomph::HermiteBeamElement::output(), oomph::SolidQHermiteElement< DIM >::output(), oomph::SolidQElement< 1, NNODE_1D >::output(), oomph::SolidQElement< 2, NNODE_1D >::output(), oomph::SolidQElement< 3, NNODE_1D >::output(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::MeshAsGeomObject::position(), oomph::StorableShapeSolidElementBase::pre_compute_d2shape_lagrangian_at_knots(), oomph::StorableShapeSolidElementBase::pre_compute_dshape_lagrangian_at_knots(), and oomph::DiskLikeGeomObjectWithBoundaries::zeta_on_boundary().
operator=()
void oomph::GeomObject::operator= (const GeomObject &) [delete]
Broken assignment operator.
position() [1/3]
virtual void oomph::GeomObject::position (const double & t, const Vector< double > & zeta, Vector< double > & r) const [inline], [virtual]
Parametrised position on object: r(zeta). Evaluated at the continuous time value, t.
Definition at line 276 of file geom_objects.h.
position() [2/3]
virtual void oomph::GeomObject::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const [inline], [virtual]
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Works for t=0 but needs to be overloaded if genuine time-dependence is required.
Reimplemented in oomph::ImmersedRigidBodyElement, oomph::ImmersedRigidBodyTriangleMeshPolygon, oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >, oomph::FiniteElement, oomph::WarpedCircularDisk, oomph::StraightLine, oomph::Ellipse, oomph::Circle, oomph::EllipticalTube, oomph::MeshAsGeomObject, and oomph::PseudoBucklingRing.
Definition at line 259 of file geom_objects.h.
References position(), and t.
position() [3/3]
virtual void oomph::GeomObject::position (const Vector< double > & zeta, Vector< double > & r) const [pure virtual]
Parametrised position on object at current time: r(zeta).
Implemented in oomph::YoungLaplaceEquations, oomph::ImmersedRigidBodyElement, oomph::ImmersedRigidBodyTriangleMeshPolygon, oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >, oomph::FiniteElement, oomph::WarpedCircularDisk, oomph::StraightLine, oomph::Ellipse, oomph::Circle, oomph::EllipticalTube, oomph::MeshAsGeomObject, and oomph::PseudoBucklingRing.
Referenced by oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::AlgebraicChannelWithLeafletMesh(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh(), oomph::ChannelWithLeafletDomain::ChannelWithLeafletDomain(), dposition_dt(), oomph::ImmersedRigidBodyElement::dposition_dt(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::TriangleMeshCurviLine::final_vertex_coordinate(), oomph::TriangleMeshCurviLine::initial_vertex_coordinate(), oomph::ChannelWithLeafletDomain::macro_bound_I_E(), oomph::ChannelWithLeafletDomain::macro_bound_I_W(), oomph::ChannelWithLeafletDomain::macro_bound_II_E(), oomph::ChannelWithLeafletDomain::macro_bound_II_W(), oomph::RectangleWithHoleAndAnnularRegionDomain::macro_element_boundary(), oomph::FullCircleDomain::macro_element_boundary(), oomph::TubeDomain::macro_element_boundary(), oomph::CylinderWithFlagDomain::macro_element_boundary(), oomph::RectangleWithHoleDomain::macro_element_boundary(), oomph::RectangleWithHoleAndAnnularRegionDomain::macro_element_boundary(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::node_update_I(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::node_update_II(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::TriangleMeshCurviLine::output(), oomph::ImmersedRigidBodyElement::position(), position(), oomph::ImmersedRigidBodyElement::position(), oomph::DiskLikeGeomObjectWithBoundaries::position_on_boundary(), oomph::RectangleWithHoleAndAnnularRegionDomain::project_point_on_cylinder_to_annular_boundary(), oomph::RectangleWithHoleAndAnnularRegionDomain::project_point_on_cylinder_to_annular_boundary(), oomph::QuarterPipeDomain::r_B(), oomph::QuarterTubeDomain::r_bot_right_B(), oomph::QuarterTubeDomain::r_bot_right_D(), oomph::QuarterCircleSectorDomain::r_bot_right_E(), oomph::QuarterTubeDomain::r_bot_right_F(), oomph::QuarterTubeDomain::r_bot_right_R(), oomph::QuarterCircleSectorDomain::r_bot_right_S(), oomph::QuarterTubeDomain::r_bot_right_U(), oomph::QuarterCircleSectorDomain::r_bot_right_W(), oomph::QuarterTubeDomain::r_centr_B(), oomph::QuarterTubeDomain::r_centr_D(), oomph::QuarterTubeDomain::r_centr_F(), oomph::QuarterTubeDomain::r_centr_L(), oomph::QuarterTubeDomain::r_centr_R(), oomph::QuarterCircleSectorDomain::r_centr_S(), oomph::QuarterTubeDomain::r_centr_U(), oomph::QuarterCircleSectorDomain::r_centr_W(), oomph::QuarterPipeDomain::r_D(), oomph::CollapsibleChannelDomain::r_E_collapsible(), oomph::QuarterPipeDomain::r_F(), oomph::QuarterPipeDomain::r_L(), oomph::CollapsibleChannelDomain::r_N_collapsible(), oomph::QuarterPipeDomain::r_R(), oomph::CollapsibleChannelDomain::r_S_collapsible(), oomph::QuarterTubeDomain::r_top_left_B(), oomph::QuarterCircleSectorDomain::r_top_left_E(), oomph::QuarterTubeDomain::r_top_left_F(), oomph::QuarterTubeDomain::r_top_left_L(), oomph::QuarterCircleSectorDomain::r_top_left_N(), oomph::QuarterCircleSectorDomain::r_top_left_S(), oomph::QuarterTubeDomain::r_top_left_U(), oomph::QuarterCircleSectorDomain::r_top_left_W(), oomph::QuarterPipeDomain::r_U(), oomph::FishDomain::r_upper_body_E(), oomph::FishDomain::r_upper_body_N(), oomph::FishDomain::r_upper_body_S(), oomph::FishDomain::r_upper_body_W(), oomph::FishDomain::r_upper_fin_N(), oomph::FishDomain::r_upper_fin_S(), oomph::FishDomain::r_upper_fin_W(), oomph::CollapsibleChannelDomain::r_W_collapsible(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::UnstructuredTwoDMeshGeometryBase::setup_boundary_coordinates(), oomph::ChannelWithLeafletDomain::slanted_bound_up(), oomph::UnstructuredTwoDMeshGeometryBase::snap_nodes_onto_geometric_objects(), and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error().
set_nlagrangian_and_ndim()
void oomph::GeomObject::set_nlagrangian_and_ndim (const unsigned & n_lagrangian, const unsigned & n_dim) [inline]
Set # of Lagrangian and Eulerian coordinates.
Definition at line 183 of file geom_objects.h.
References Ndim, and NLagrangian.
Referenced by oomph::MeshAsGeomObject::build_it(), oomph::FaceElementAsGeomObject< ELEMENT >::FaceElementAsGeomObject(), and oomph::FSIWallElement::setup_fsi_wall_element().
time_stepper_pt() [1/2]
TimeStepper *& oomph::GeomObject::time_stepper_pt () [inline]
Access function for pointer to time stepper: Null if object is not time-dependent.
Definition at line 192 of file geom_objects.h.
References Geom_object_time_stepper_pt.
Referenced by oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >::adapt_temporal_mesh(), oomph::SurfactantTransportInterfaceElement::add_additional_residual_contributions_interface(), oomph::Mesh::assign_initial_values_impulsive(), oomph::Problem::assign_initial_values_impulsive(), oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::BackupMeshForProjection(), oomph::RefineableQElement< 3 >::build(), oomph::RefineableQElement< 1 >::build(), oomph::RefineableQElement< 2 >::build(), oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::GeompackQuadMesh< ELEMENT >::build_from_scaffold(), oomph::SimpleCubicTetMesh< ELEMENT >::build_from_scaffold(), oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), oomph::TriangleMesh< ELEMENT >::build_from_scaffold(), oomph::QuadFromTriangleMesh< ELEMENT >::build_from_scaffold(), oomph::ExtrudedCubeMeshFromQuadMesh< ELEMENT >::build_mesh(), oomph::BrickFromTetMesh< ELEMENT >::build_mesh(), oomph::FishMesh< ELEMENT >::build_mesh(), oomph::HermiteQuadMesh< ELEMENT >::build_mesh(), oomph::OneDMesh< ELEMENT >::build_mesh(), oomph::RectangularQuadMesh< ELEMENT >::build_mesh(), oomph::SimpleCubicMesh< ELEMENT >::build_mesh(), oomph::BrickFromTetMesh< ELEMENT >::build_mesh(), oomph::SingleLayerSpineMesh< ELEMENT >::build_single_layer_mesh(), oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::Mesh::calculate_predictions(), oomph::Problem::calculate_predictions(), oomph::Circle::Circle(), oomph::Circle::Circle(), oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::construct_boundary_node(), oomph::FiniteElement::construct_boundary_node(), oomph::SolidFiniteElement::construct_boundary_node(), oomph::DGElement::construct_boundary_nodes_and_faces(), oomph::RefineableTriangleMesh< ELEMENT >::construct_new_halo_node_helper(), oomph::RefineableTriangleMesh< ELEMENT >::construct_new_node_load_balance_helper(), oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::construct_node(), oomph::FiniteElement::construct_node(), oomph::SolidFiniteElement::construct_node(), oomph::DGElement::construct_nodes_and_faces(), oomph::CylinderWithFlagMesh< ELEMENT >::CylinderWithFlagMesh(), oomph::AxisymmetricPoroelasticityEquations::d2u_dt2(), oomph::PoroelasticityEquations< DIM >::d2u_dt2(), oomph::AxisymmetricLinearElasticityEquationsBase::d2u_dt2_axisymmetric_linear_elasticity(), oomph::LinearWaveEquations< DIM >::d2u_dt2_lin_wave(), oomph::LinearElasticityEquationsBase< DIM >::d2u_dt2_linear_elasticity(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::dc_dt_adv_diff_react(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::dc_dt_adv_diff_react(), oomph::SurfactantTransportInterfaceElement::dcdt_surface(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::dposition_dt(), oomph::AxisymmetricPoroelasticityEquations::dq_edge_dt(), oomph::PoroelasticityEquations< DIM >::dq_edge_dt(), oomph::AxisymmetricPoroelasticityEquations::dq_internal_dt(), oomph::PoroelasticityEquations< DIM >::dq_internal_dt(), oomph::AxisymmetricPoroelasticityEquations::du_dt(), oomph::PoroelasticityEquations< DIM >::du_dt(), oomph::AdvectionDiffusionEquations< DIM >::du_dt_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::du_dt_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::du_dt_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::du_dt_axi_nst(), oomph::AxisymmetricLinearElasticityEquationsBase::du_dt_axisymmetric_linear_elasticity(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::du_dt_cons_adv_diff(), oomph::GeneralisedAxisymAdvectionDiffusionEquations::du_dt_cons_axisym_adv_diff(), oomph::FluxTransportEquations< DIM >::du_dt_flux_transport(), oomph::LinearWaveEquations< DIM >::du_dt_lin_wave(), oomph::LinearisedAxisymmetricNavierStokesEquations::du_dt_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations::du_dt_linearised_nst(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::du_dt_nst(), oomph::NavierStokesEquations< DIM >::du_dt_nst(), oomph::PolarNavierStokesEquations::du_dt_pnst(), oomph::SphericalAdvectionDiffusionEquations::du_dt_spherical_adv_diff(), oomph::SphericalNavierStokesEquations::du_dt_spherical_nst(), oomph::UnsteadyHeatEquations< DIM >::du_dt_ust_heat(), oomph::WomersleyEquations< DIM >::du_dt_womersley(), oomph::SegregatableFSIProblem::extrapolate_solid_data(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::extrapolated_strain_rate(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::extrapolated_strain_rate(), oomph::ODEElement::fill_in_contribution_to_residuals(), oomph::FishMesh< ELEMENT >::FishMesh(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::Missing_masters_functions::get_required_master_nodal_information_helper(), oomph::Multi_domain_functions::get_required_master_nodal_information_helper(), oomph::Missing_masters_functions::get_required_nodal_information_helper(), oomph::Multi_domain_functions::get_required_nodal_information_helper(), oomph::FiniteElement::get_x(), oomph::ImmersedRigidBodyElement::initialise(), oomph::ImmersedRigidBodyElement::output_centre_of_gravity(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::p_refine(), oomph::StraightLine::position(), oomph::Ellipse::position(), oomph::Circle::position(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::pre_build(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::pre_build(), oomph::PseudoBucklingRing::PseudoBucklingRing(), oomph::PseudoBucklingRing::PseudoBucklingRing(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::rebuild_from_sons(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::rebuild_from_sons(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::rebuild_from_sons(), oomph::RectangleWithHoleAndAnnularRegionMesh< ELEMENT >::RectangleWithHoleAndAnnularRegionMesh(), oomph::RefineableQuadMeshWithMovingCylinder< ELEMENT >::RefineableQuadMeshWithMovingCylinder(), oomph::ContinuationStorageScheme::set_consistent_pinned_values(), oomph::SolidICProblem::set_newmark_initial_condition_consistently(), oomph::SolidICProblem::set_newmark_initial_condition_directly(), oomph::AxisymmetricPoroelasticityEquations::set_q_internal_timestepper(), oomph::PoroelasticityEquations< DIM >::set_q_internal_timestepper(), oomph::SolidICProblem::set_static_initial_condition(), oomph::PeriodicOrbitEquations::set_timestepper_weights(), oomph::Mesh::shift_time_values(), oomph::Problem::shift_time_values(), oomph::WomersleyImpedanceTubeBase< ELEMENT, DIM >::shift_time_values(), oomph::SimpleRectangularQuadMesh< ELEMENT >::SimpleRectangularQuadMesh(), and oomph::XdaTetMesh< ELEMENT >::XdaTetMesh().
time_stepper_pt() [2/2]
TimeStepper * oomph::GeomObject::time_stepper_pt () const [inline]
Access function for pointer to time stepper: Null if object is not time-dependent. Const version.
Definition at line 199 of file geom_objects.h.
References Geom_object_time_stepper_pt.
Member Data Documentation
Geom_object_time_stepper_pt
TimeStepper* oomph::GeomObject::Geom_object_time_stepper_pt [protected]
Timestepper (used to handle access to geometry at previous timesteps)
Definition at line 435 of file geom_objects.h.
Referenced by oomph::PseudoBucklingRing::accel(), oomph::PseudoBucklingRing::position(), oomph::PseudoBucklingRing::position(), time_stepper_pt(), time_stepper_pt(), and oomph::PseudoBucklingRing::veloc().
Ndim
unsigned oomph::GeomObject::Ndim [protected]
Number of Eulerian coordinates.
Definition at line 431 of file geom_objects.h.
Referenced by oomph::PseudoBucklingRing::accel(), ndim(), oomph::PseudoBucklingRing::position(), oomph::PseudoBucklingRing::position(), set_nlagrangian_and_ndim(), and oomph::PseudoBucklingRing::veloc().
NLagrangian
unsigned oomph::GeomObject::NLagrangian [protected]
Number of Lagrangian (intrinsic) coordinates.
Definition at line 428 of file geom_objects.h.
Referenced by nlagrangian(), and set_nlagrangian_and_ndim().
The documentation for this class was generated from the following file:
geom_objects.h