oomph::DGScalarAdvectionFaceElement< ELEMENT > Class Template Reference
FaceElement for Discontinuous Galerkin Problems.
#include <scalar_advection_elements.h>
Public Member Functions
DGScalarAdvectionFaceElement (FiniteElement *const &element_pt, const int &face_index)
Constructor.
unsigned required_nflux ()
Set the number of flux components.
void numerical_flux (const Vector< double > &n_out, const Vector< double > &u_int, const Vector< double > &u_ext, Vector< double > &flux)
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::DGScalarAdvectionFaceElement< ELEMENT >
FaceElement for Discontinuous Galerkin Problems.
Definition at line 398 of file scalar_advection_elements.h.
Constructor & Destructor Documentation
DGScalarAdvectionFaceElement()
template<class ELEMENT >
oomph::DGScalarAdvectionFaceElement< ELEMENT >::DGScalarAdvectionFaceElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor.
Definition at line 403 of file scalar_advection_elements.h.
References oomph::FiniteElement::build_face_element(), and oomph::FaceElement::face_index().
Member Function Documentation
numerical_flux()
template<class ELEMENT >
void oomph::DGScalarAdvectionFaceElement< ELEMENT >::numerical_flux (const Vector< double > & n_out, const Vector< double > & u_int, const Vector< double > & u_ext, Vector< double > & flux) [inline], [virtual]
Calculate the normal flux, so this is the dot product of the numerical flux with n_in
Reimplemented from oomph::DGFaceElement.
Definition at line 422 of file scalar_advection_elements.h.
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), oomph::VectorHelpers::dot(), i, n, oomph::FiniteElement::nodal_dimension(), oomph::DGScalarAdvectionFaceElement< ELEMENT >::required_nflux(), and s.
required_nflux()
template<class ELEMENT >
unsigned oomph::DGScalarAdvectionFaceElement< ELEMENT >::required_nflux () [inline], [virtual]
Set the number of flux components.
Reimplemented from oomph::DGFaceElement.
Definition at line 415 of file scalar_advection_elements.h.
Referenced by oomph::DGScalarAdvectionFaceElement< ELEMENT >::numerical_flux().
The documentation for this class was generated from the following file:
scalar_advection_elements.h