oomph::HelmholtzAbsorbingBCElement< ELEMENT > Class Template Reference
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
#include <helmholtz_bc_elements.h>
Public Member Functions
HelmholtzAbsorbingBCElement (FiniteElement *const &bulk_el_pt, const int &face_index)
Construct element from specification of bulk element and face index.
unsigned *& abc_order_pt ()
Pointer to order of absorbing boundary condition.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and its Jacobian matrix.
double *& outer_radius_pt ()
Get pointer to radius of outer boundary (must be a cirle)
Private Member Functions
void fill_in_generic_residual_contribution_helmholtz_abc (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Compute the element's residual vector and the (Jacobian matrix. Overloaded version, using the abc approximation.
Private Attributes
double * Outer_radius_pt
Pointer to radius of outer boundary (must be a circle!)
unsigned * ABC_order_pt
Pointer to order of absorbing boundary condition.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::HelmholtzAbsorbingBCElement< ELEMENT >
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
Absorbing BC element for approximation imposition of Sommerfeld radiation condition
Definition at line 638 of file helmholtz_bc_elements.h.
Constructor & Destructor Documentation
HelmholtzAbsorbingBCElement()
template<class ELEMENT >
oomph::HelmholtzAbsorbingBCElement< ELEMENT >::HelmholtzAbsorbingBCElement (FiniteElement *const & bulk_el_pt, const int & face_index) [inline]
Construct element from specification of bulk element and face index.
Definition at line 643 of file helmholtz_bc_elements.h.
References oomph::HelmholtzAbsorbingBCElement< ELEMENT >::ABC_order_pt, and oomph::HelmholtzAbsorbingBCElement< ELEMENT >::Outer_radius_pt.
Member Function Documentation
abc_order_pt()
template<class ELEMENT >
unsigned*& oomph::HelmholtzAbsorbingBCElement< ELEMENT >::abc_order_pt () [inline]
Pointer to order of absorbing boundary condition.
Definition at line 655 of file helmholtz_bc_elements.h.
References oomph::HelmholtzAbsorbingBCElement< ELEMENT >::ABC_order_pt.
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and its Jacobian matrix.
Reimplemented from oomph::FiniteElement.
Definition at line 672 of file helmholtz_bc_elements.h.
References oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_abc().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 662 of file helmholtz_bc_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_abc().
fill_in_generic_residual_contribution_helmholtz_abc()
template<class ELEMENT >
void oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_abc (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [inline], [private]
Compute the element's residual vector and the (Jacobian matrix. Overloaded version, using the abc approximation.
Definition at line 691 of file helmholtz_bc_elements.h.
References oomph::HelmholtzAbsorbingBCElement< ELEMENT >::ABC_order_pt, oomph::FaceElement::bulk_element_pt(), oomph::HelmholtzBCElementBase< ELEMENT >::d_shape_and_test_local(), oomph::HelmholtzBCElementBase< ELEMENT >::Dim, i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_value(), oomph::Integral::nweight(), oomph::HelmholtzAbsorbingBCElement< ELEMENT >::Outer_radius_pt, oomph::BinaryTreeNames::R, s, oomph::HelmholtzBCElementBase< ELEMENT >::U_index_helmholtz, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_contribution_to_residuals().
outer_radius_pt()
template<class ELEMENT >
double*& oomph::HelmholtzAbsorbingBCElement< ELEMENT >::outer_radius_pt () [inline]
Get pointer to radius of outer boundary (must be a cirle)
Definition at line 682 of file helmholtz_bc_elements.h.
References oomph::HelmholtzAbsorbingBCElement< ELEMENT >::Outer_radius_pt.
Member Data Documentation
ABC_order_pt
template<class ELEMENT >
unsigned* oomph::HelmholtzAbsorbingBCElement< ELEMENT >::ABC_order_pt [private]
Pointer to order of absorbing boundary condition.
Definition at line 1112 of file helmholtz_bc_elements.h.
Referenced by oomph::HelmholtzAbsorbingBCElement< ELEMENT >::abc_order_pt(), oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_abc(), and oomph::HelmholtzAbsorbingBCElement< ELEMENT >::HelmholtzAbsorbingBCElement().
Outer_radius_pt
template<class ELEMENT >
double* oomph::HelmholtzAbsorbingBCElement< ELEMENT >::Outer_radius_pt [private]
Pointer to radius of outer boundary (must be a circle!)
Definition at line 1109 of file helmholtz_bc_elements.h.
Referenced by oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_abc(), oomph::HelmholtzAbsorbingBCElement< ELEMENT >::HelmholtzAbsorbingBCElement(), and oomph::HelmholtzAbsorbingBCElement< ELEMENT >::outer_radius_pt().
The documentation for this class was generated from the following file:
helmholtz_bc_elements.h