oomph::FluxTransportEquations< DIM > Class Template Reference
Base class for the flux transport equations templated by the dimension DIM. The equations that are solved are.
#include <flux_transport_elements.h>
Public Member Functions
FluxTransportEquations ()
Constructor.
virtual ~FluxTransportEquations ()
Empty destructor.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
Assemble the contributions to the mass matrix and residuals.
virtual void fill_in_generic_residual_contribution_flux_transport (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Compute the residuals for the Navier--Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
double interpolated_u_flux_transport (const Vector< double > &s, const unsigned &i)
Return the i-th unknown at the local coordinate s.
double du_dt_flux_transport (const unsigned &n, const unsigned &i) const
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
void calculate_element_averages (double *&average_values)
Compute the average values of the fluxes.
void output (std::ostream &outfile)
Output the element data --- typically the values at the nodes in a format suitable for post-processing.
void output (std::ostream &outfile, const unsigned &nplot)
Output function, print the values of all unknowns.
Protected Member Functions
virtual unsigned nflux () const
Return the number of fluxes (default zero)
virtual unsigned u_index_flux_transport (const unsigned &i) const
Return the index at which the i-th unknown value is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
virtual void flux (const Vector< double > &u, DenseMatrix< double > &f)
Return the flux as a function of the unknown. This interface could (should) be generalised)
virtual void dflux_du (const Vector< double > &u, RankThreeTensor< double > &df_du)
Return the flux derivatives as a funciton of the unknowns Default finite-different implementation.
virtual double dshape_and_dtest_eulerian_flux_transport (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_flux_transport (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::FluxTransportEquations< DIM >
Base class for the flux transport equations templated by the dimension DIM. The equations that are solved are.
 \frac{\partial u_{i}}{\partial t} + \frac{\partial}{\partial x_{j}} \left(F_{ij}(u_{k})\right), 
 where $ F_{ij} $ is a matrix of flux components.
Definition at line 48 of file flux_transport_elements.h.
Constructor & Destructor Documentation
FluxTransportEquations()
template<unsigned DIM>
oomph::FluxTransportEquations< DIM >::FluxTransportEquations () [inline]
Constructor.
Definition at line 107 of file flux_transport_elements.h.
 FluxTransportEquations()
template<unsigned DIM>
virtual oomph::FluxTransportEquations< DIM >::~FluxTransportEquations () [inline], [virtual]
Empty destructor.
Definition at line 110 of file flux_transport_elements.h.
Member Function Documentation
calculate_element_averages()
template<unsigned DIM>
void oomph::FluxTransportEquations< DIM >::calculate_element_averages (double *& average_values)
Compute the average values of the fluxes.
Calculate the averages of the flux variables.
Definition at line 308 of file flux_transport_elements.cc.
References i, and oomph::QuadTreeNames::W.
Referenced by oomph::DGSpectralEulerElement< 1, NNODE_1D >::calculate_element_averages(), oomph::DGSpectralEulerElement< 2, NNODE_1D >::calculate_element_averages(), oomph::DGSpectralScalarAdvectionElement< 1, NNODE_1D >::calculate_element_averages(), oomph::DGSpectralScalarAdvectionElement< 2, NNODE_1D >::calculate_element_averages(), oomph::DGScalarAdvectionElement< 1, NNODE_1D >::calculate_element_averages(), and oomph::DGScalarAdvectionElement< 2, NNODE_1D >::calculate_element_averages().
dflux_du()
template<unsigned DIM>
void oomph::FluxTransportEquations< DIM >::dflux_du (const Vector< double > & u, RankThreeTensor< double > & df_du) [protected], [virtual]
Return the flux derivatives as a funciton of the unknowns Default finite-different implementation.
Return the derivatives of the flux components as functions of the unknowns. The default implementation is to use second-order finite-differences, but these can be overloaded in specific equations.
Reimplemented in oomph::ScalarAdvectionEquations< DIM >.
Definition at line 40 of file flux_transport_elements.cc.
References oomph::GeneralisedElement::Default_fd_jacobian_step, and oomph::OcTreeNames::F.
dshape_and_dtest_eulerian_at_knot_flux_transport()
template<unsigned DIM>
virtual double oomph::FluxTransportEquations< DIM >::dshape_and_dtest_eulerian_at_knot_flux_transport (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::QSpectralEulerElement< DIM, NNODE_1D >, oomph::QSpectralEulerElement< 1, NNODE_1D >, oomph::QSpectralEulerElement< 2, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< DIM, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< 1, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< 2, NNODE_1D >, oomph::QScalarAdvectionElement< DIM, NNODE_1D >, oomph::QScalarAdvectionElement< 1, NNODE_1D >, and oomph::QScalarAdvectionElement< 2, NNODE_1D >.
dshape_and_dtest_eulerian_flux_transport()
template<unsigned DIM>
virtual double oomph::FluxTransportEquations< DIM >::dshape_and_dtest_eulerian_flux_transport (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in oomph::QSpectralEulerElement< DIM, NNODE_1D >, oomph::QSpectralEulerElement< 1, NNODE_1D >, oomph::QSpectralEulerElement< 2, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< DIM, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< 1, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< 2, NNODE_1D >, oomph::QScalarAdvectionElement< DIM, NNODE_1D >, oomph::QScalarAdvectionElement< 1, NNODE_1D >, and oomph::QScalarAdvectionElement< 2, NNODE_1D >.
du_dt_flux_transport()
template<unsigned DIM>
double oomph::FluxTransportEquations< DIM >::du_dt_flux_transport (const unsigned & n, const unsigned & i) const
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
Definition at line 276 of file flux_transport_elements.cc.
References i, oomph::TimeStepper::is_steady(), oomph::TimeStepper::ntstorage(), t, and oomph::TimeStepper::weight().
fill_in_contribution_to_jacobian()
template<unsigned DIM>
void oomph::FluxTransportEquations< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
Reimplemented from oomph::GeneralisedElement.
Definition at line 126 of file flux_transport_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::FluxTransportEquations< DIM >::fill_in_generic_residual_contribution_flux_transport().
fill_in_contribution_to_jacobian_and_mass_matrix()
template<unsigned DIM>
void oomph::FluxTransportEquations< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline], [virtual]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Reimplemented from oomph::GeneralisedElement.
Definition at line 136 of file flux_transport_elements.h.
References oomph::FluxTransportEquations< DIM >::fill_in_generic_residual_contribution_flux_transport().
fill_in_contribution_to_mass_matrix()
template<unsigned DIM>
void oomph::FluxTransportEquations< DIM >::fill_in_contribution_to_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & mass_matrix) [inline], [virtual]
Assemble the contributions to the mass matrix and residuals.
Reimplemented from oomph::GeneralisedElement.
Definition at line 147 of file flux_transport_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::FluxTransportEquations< DIM >::fill_in_generic_residual_contribution_flux_transport().
fill_in_contribution_to_residuals()
template<unsigned DIM>
void oomph::FluxTransportEquations< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Compute the element's residual Vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 113 of file flux_transport_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::FluxTransportEquations< DIM >::fill_in_generic_residual_contribution_flux_transport().
fill_in_generic_residual_contribution_flux_transport()
template<unsigned DIM>
void oomph::FluxTransportEquations< DIM >::fill_in_generic_residual_contribution_flux_transport (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [virtual]
Compute the residuals for the Navier--Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Compute the residuals for the flux transport equations; flag=1 compute jacobian as well flag=2 compute mass matrix and jacobian as well flag=3 compute mass matrix as well.
Reimplemented in oomph::DGSpectralEulerElement< 1, NNODE_1D >, oomph::DGSpectralEulerElement< 2, NNODE_1D >, oomph::DGSpectralScalarAdvectionElement< 1, NNODE_1D >, oomph::DGSpectralScalarAdvectionElement< 2, NNODE_1D >, oomph::DGScalarAdvectionElement< 1, NNODE_1D >, and oomph::DGScalarAdvectionElement< 2, NNODE_1D >.
Definition at line 89 of file flux_transport_elements.cc.
References oomph::OcTreeNames::F, i, and oomph::QuadTreeNames::W.
Referenced by oomph::FluxTransportEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::FluxTransportEquations< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::FluxTransportEquations< DIM >::fill_in_contribution_to_mass_matrix(), oomph::FluxTransportEquations< DIM >::fill_in_contribution_to_residuals(), oomph::DGSpectralEulerElement< 1, NNODE_1D >::fill_in_generic_residual_contribution_flux_transport(), oomph::DGSpectralEulerElement< 2, NNODE_1D >::fill_in_generic_residual_contribution_flux_transport(), oomph::DGSpectralScalarAdvectionElement< 1, NNODE_1D >::fill_in_generic_residual_contribution_flux_transport(), oomph::DGSpectralScalarAdvectionElement< 2, NNODE_1D >::fill_in_generic_residual_contribution_flux_transport(), oomph::DGScalarAdvectionElement< 1, NNODE_1D >::fill_in_generic_residual_contribution_flux_transport(), and oomph::DGScalarAdvectionElement< 2, NNODE_1D >::fill_in_generic_residual_contribution_flux_transport().
flux()
template<unsigned DIM>
virtual void oomph::FluxTransportEquations< DIM >::flux (const Vector< double > & u, DenseMatrix< double > & f) [inline], [protected], [virtual]
Return the flux as a function of the unknown. This interface could (should) be generalised)
Reimplemented in oomph::EulerEquations< DIM >, and oomph::ScalarAdvectionEquations< DIM >.
Definition at line 70 of file flux_transport_elements.h.
interpolated_u_flux_transport()
template<unsigned DIM>
double oomph::FluxTransportEquations< DIM >::interpolated_u_flux_transport (const Vector< double > & s, const unsigned & i)
Return the i-th unknown at the local coordinate s.
Definition at line 250 of file flux_transport_elements.cc.
References i, and oomph::OneDimLagrange::shape().
nflux()
template<unsigned DIM>
virtual unsigned oomph::FluxTransportEquations< DIM >::nflux () const [inline], [protected], [virtual]
Return the number of fluxes (default zero)
Reimplemented in oomph::EulerEquations< DIM >, and oomph::ScalarAdvectionEquations< DIM >.
Definition at line 52 of file flux_transport_elements.h.
output() [1/2]
template<unsigned DIM>
void oomph::FluxTransportEquations< DIM >::output (std::ostream & outfile) [inline], [virtual]
Output the element data --- typically the values at the nodes in a format suitable for post-processing.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QSpectralEulerElement< 1, NNODE_1D >, oomph::QSpectralEulerElement< 2, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< DIM, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< 1, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< 2, NNODE_1D >, oomph::QScalarAdvectionElement< DIM, NNODE_1D >, oomph::QScalarAdvectionElement< 1, NNODE_1D >, and oomph::QScalarAdvectionElement< 2, NNODE_1D >.
Definition at line 175 of file flux_transport_elements.h.
References oomph::FluxTransportEquations< DIM >::output().
Referenced by oomph::FluxTransportEquations< DIM >::output(), oomph::QSpectralScalarAdvectionElement< DIM, NNODE_1D >::output(), and oomph::QScalarAdvectionElement< DIM, NNODE_1D >::output().
output() [2/2]
template<unsigned DIM>
void oomph::FluxTransportEquations< DIM >::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output function, print the values of all unknowns.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QSpectralEulerElement< 1, NNODE_1D >, oomph::QSpectralEulerElement< 2, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< DIM, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< 1, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< 2, NNODE_1D >, oomph::QScalarAdvectionElement< DIM, NNODE_1D >, oomph::QScalarAdvectionElement< 1, NNODE_1D >, and oomph::QScalarAdvectionElement< 2, NNODE_1D >.
Definition at line 385 of file flux_transport_elements.cc.
References i, and s.
u_index_flux_transport()
template<unsigned DIM>
virtual unsigned oomph::FluxTransportEquations< DIM >::u_index_flux_transport (const unsigned & i) const [inline], [protected], [virtual]
Return the index at which the i-th unknown value is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
Definition at line 63 of file flux_transport_elements.h.
References i.
The documentation for this class was generated from the following files:
flux_transport_elements.h
flux_transport_elements.cc