oomph::RefineableRectangleWithHoleMesh< ELEMENT > Class Template Reference
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
#include <rectangle_with_hole_mesh.template.h>
Public Member Functions
RefineableRectangleWithHoleMesh (GeomObject *cylinder_pt, const double &length, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor. Pass pointer to geometric object that represents the cylinder, the length and height of the domain. The GeomObject must be parametrised such that $\zeta \in [0,2\pi]$ sweeps around the circumference in anticlockwise direction. Timestepper defaults to Steady default timestepper.
virtual ~RefineableRectangleWithHoleMesh ()
Destructor: Empty.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::RefineableRectangleWithHoleMesh< ELEMENT >
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
Refineable version of RectangleWithHoleMesh. For some reason this needs on uniform refinement to work...
Definition at line 255 of file rectangle_with_hole_mesh.template.h.
Constructor & Destructor Documentation
RefineableRectangleWithHoleMesh()
template<class ELEMENT >
oomph::RefineableRectangleWithHoleMesh< ELEMENT >::RefineableRectangleWithHoleMesh (GeomObject * cylinder_pt, const double & length, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor. Pass pointer to geometric object that represents the cylinder, the length and height of the domain. The GeomObject must be parametrised such that $\zeta \in [0,2\pi]$ sweeps around the circumference in anticlockwise direction. Timestepper defaults to Steady default timestepper.
Definition at line 265 of file rectangle_with_hole_mesh.template.h.
References oomph::RectangleWithHoleMesh< ELEMENT >::Domain_pt, e, oomph::Mesh::element_pt(), oomph::Domain::macro_element_pt(), oomph::Mesh::setup_boundary_element_info(), and oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest().
 RefineableRectangleWithHoleMesh()
template<class ELEMENT >
virtual oomph::RefineableRectangleWithHoleMesh< ELEMENT >::~RefineableRectangleWithHoleMesh () [inline], [virtual]
Destructor: Empty.
Definition at line 290 of file rectangle_with_hole_mesh.template.h.
The documentation for this class was generated from the following file:
rectangle_with_hole_mesh.template.h