oomph::DGEulerFaceElement< ELEMENT > Class Template Reference
FaceElement for Discontinuous Galerkin Problems.
#include <euler_elements.h>
Public Member Functions
DGEulerFaceElement (FiniteElement *const &element_pt, const int &face_index)
Constructor.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
unsigned required_nflux ()
Set the number of flux components.
void numerical_flux (const Vector< double > &n_out, const Vector< double > &u_int, const Vector< double > &u_ext, Vector< double > &flux)
Calculate the normal flux, so this is the dot product of the numerical flux with n_out.
Private Attributes
unsigned Nflux
bool Reflecting
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::DGEulerFaceElement< ELEMENT >
FaceElement for Discontinuous Galerkin Problems.
Definition at line 441 of file euler_elements.h.
Constructor & Destructor Documentation
DGEulerFaceElement()
template<class ELEMENT >
oomph::DGEulerFaceElement< ELEMENT >::DGEulerFaceElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor.
Definition at line 450 of file euler_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FiniteElement::dim(), oomph::FaceElement::face_index(), oomph::DGEulerFaceElement< ELEMENT >::Nflux, and oomph::FiniteElement::set_integration_scheme().
Member Function Documentation
numerical_flux()
template<class ELEMENT >
void oomph::DGEulerFaceElement< ELEMENT >::numerical_flux (const Vector< double > & n_out, const Vector< double > & u_int, const Vector< double > & u_ext, Vector< double > & flux) [inline], [virtual]
Calculate the normal flux, so this is the dot product of the numerical flux with n_out.
Reimplemented from oomph::DGFaceElement.
Definition at line 488 of file euler_elements.h.
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), i, oomph::Vector< _Tp >::initialise(), oomph::DGEulerFaceElement< ELEMENT >::Nflux, and oomph::oomph_info.
required_nflux()
template<class ELEMENT >
unsigned oomph::DGEulerFaceElement< ELEMENT >::required_nflux () [inline], [virtual]
Set the number of flux components.
Reimplemented from oomph::DGFaceElement.
Definition at line 481 of file euler_elements.h.
References oomph::DGEulerFaceElement< ELEMENT >::Nflux.
zeta_nodal()
template<class ELEMENT >
double oomph::DGEulerFaceElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Reimplemented from oomph::FiniteElement.
Definition at line 472 of file euler_elements.h.
References i, and oomph::FaceElement::zeta_nodal().
Member Data Documentation
Nflux
template<class ELEMENT >
unsigned oomph::DGEulerFaceElement< ELEMENT >::Nflux [private]
Definition at line 444 of file euler_elements.h.
Referenced by oomph::DGEulerFaceElement< ELEMENT >::DGEulerFaceElement(), oomph::DGEulerFaceElement< ELEMENT >::numerical_flux(), and oomph::DGEulerFaceElement< ELEMENT >::required_nflux().
Reflecting
template<class ELEMENT >
bool oomph::DGEulerFaceElement< ELEMENT >::Reflecting [private]
Definition at line 446 of file euler_elements.h.
The documentation for this class was generated from the following file:
euler_elements.h