oomph::BlockPrecQTaylorHoodSpaceTimeElement Class Reference
Block preconditionable version of the QTaylorHoodSpaceTimeElement element.
#include <spacetime_navier_stokes_block_preconditionable_elements.h>
Public Member Functions
BlockPrecQTaylorHoodSpaceTimeElement ()
Empty constructor.
~BlockPrecQTaylorHoodSpaceTimeElement ()
Empty destructor.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Overload the pure virtual base class implementation. Create a list of pairs for all unknowns in this element, so the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with.
Additional Inherited Members
Detailed Description
Block preconditionable version of the QTaylorHoodSpaceTimeElement element.
Definition at line 50 of file spacetime_navier_stokes_block_preconditionable_elements.h.
Constructor & Destructor Documentation
BlockPrecQTaylorHoodSpaceTimeElement()
oomph::BlockPrecQTaylorHoodSpaceTimeElement::BlockPrecQTaylorHoodSpaceTimeElement () [inline]
Empty constructor.
Definition at line 56 of file spacetime_navier_stokes_block_preconditionable_elements.h.
 BlockPrecQTaylorHoodSpaceTimeElement()
oomph::BlockPrecQTaylorHoodSpaceTimeElement::~BlockPrecQTaylorHoodSpaceTimeElement () [inline]
Empty destructor.
Definition at line 63 of file spacetime_navier_stokes_block_preconditionable_elements.h.
Member Function Documentation
get_dof_numbers_for_unknowns()
void oomph::BlockPrecQTaylorHoodSpaceTimeElement::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> & dof_lookup_list) const [virtual]
Overload the pure virtual base class implementation. Create a list of pairs for all unknowns in this element, so the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with.
The setup function...
Implements oomph::BlockPreconditionableSpaceTimeElementBase.
Definition at line 38 of file spacetime_navier_stokes_block_preconditionable_elements.cc.
References oomph::GeneralisedElement::eqn_number(), i, oomph::GeneralisedElement::local_eqn_number(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), oomph::Data::nvalue(), and oomph::BlockPreconditionableSpaceTimeElementBase::Time_slab_id.
The documentation for this class was generated from the following files:
spacetime_navier_stokes_block_preconditionable_elements.h
spacetime_navier_stokes_block_preconditionable_elements.cc