oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM > Class Template Reference
Refineable version of Unsteady Heat equations.
#include <refineable_space_time_unsteady_heat_elements.h>
Public Member Functions
RefineableSpaceTimeUnsteadyHeatEquations ()
Constructor.
RefineableSpaceTimeUnsteadyHeatEquations (const RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM > &dummy)
Broken copy constructor.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Different to the get_flux function in the base class as we also have to include du/dt as we're doing temporal adaptivity too.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void further_build ()
Further build: Copy source function pointer from father element.
RefineableSpaceTimeUnsteadyHeatEquations ()
Constructor.
RefineableSpaceTimeUnsteadyHeatEquations (const RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM > &dummy)
Broken copy constructor.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Different to the get_flux function in the base class as we also have to include du/dt as we're doing temporal adaptivity too.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void further_build ()
Further build: Copy source function pointer from father element.
Private Member Functions
virtual void fill_in_generic_residual_contribution_ust_heat (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Add element's contribution to elemental residual vector and/or Jacobian matrix flag=0: compute residual vector only flag=1: compute both.
virtual void fill_in_generic_residual_contribution_ust_heat (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Add element's contribution to elemental residual vector and/or Jacobian matrix flag=0: compute residual vector only flag=1: compute both.
Additional Inherited Members
Detailed Description
template<unsigned SPATIAL_DIM>
class oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >
Refineable version of Unsteady Heat equations.
Definition at line 51 of file refineable_space_time_unsteady_heat_elements.h.
Constructor & Destructor Documentation
RefineableSpaceTimeUnsteadyHeatEquations() [1/4]
template<unsigned SPATIAL_DIM>
oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::RefineableSpaceTimeUnsteadyHeatEquations () [inline]
Constructor.
Definition at line 58 of file refineable_space_time_unsteady_heat_elements.h.
RefineableSpaceTimeUnsteadyHeatEquations() [2/4]
template<unsigned SPATIAL_DIM>
oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::RefineableSpaceTimeUnsteadyHeatEquations (const RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM > & dummy) [inline]
Broken copy constructor.
Definition at line 67 of file refineable_space_time_unsteady_heat_elements.h.
References oomph::BrokenCopy::broken_copy().
RefineableSpaceTimeUnsteadyHeatEquations() [3/4]
template<unsigned SPATIAL_DIM>
oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::RefineableSpaceTimeUnsteadyHeatEquations () [inline]
Constructor.
Definition at line 58 of file refineable_discontinuous_galerkin_space_time_unsteady_heat_elements.h.
RefineableSpaceTimeUnsteadyHeatEquations() [4/4]
template<unsigned SPATIAL_DIM>
oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::RefineableSpaceTimeUnsteadyHeatEquations (const RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM > & dummy) [inline]
Broken copy constructor.
Definition at line 67 of file refineable_discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
fill_in_generic_residual_contribution_ust_heat() [1/2]
template<unsigned SPATIAL_DIM>
void oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [private], [virtual]
Add element's contribution to elemental residual vector and/or Jacobian matrix flag=0: compute residual vector only flag=1: compute both.
Add element's contribution to the elemental residual vector and/or Jacobian matrix. flag=0: compute residual vector only flag=1: compute both
Reimplemented from oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.
Definition at line 43 of file refineable_space_time_unsteady_heat_elements.cc.
References oomph::ALE_is_disabled, i, interpolated_u(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), residuals(), s, and oomph::QuadTreeNames::W.
fill_in_generic_residual_contribution_ust_heat() [2/2]
template<unsigned SPATIAL_DIM>
virtual void oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [private], [virtual]
Add element's contribution to elemental residual vector and/or Jacobian matrix flag=0: compute residual vector only flag=1: compute both.
Reimplemented from oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.
further_build() [1/2]
template<unsigned SPATIAL_DIM>
void oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::further_build () [inline], [virtual]
Further build: Copy source function pointer from father element.
Reimplemented from oomph::RefineableElement.
Definition at line 192 of file refineable_discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::ALE_is_disabled, oomph::RefineableElement::father_element_pt(), and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Source_fct_pt.
further_build() [2/2]
template<unsigned SPATIAL_DIM>
void oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::further_build () [inline], [virtual]
Further build: Copy source function pointer from father element.
Reimplemented from oomph::RefineableElement.
Definition at line 192 of file refineable_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::ALE_is_disabled, oomph::RefineableElement::father_element_pt(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::source_fct_pt(), and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Source_fct_pt.
get_interpolated_values() [1/4]
template<unsigned SPATIAL_DIM>
void oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 160 of file refineable_discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::u_index_ust_heat(), and values.
get_interpolated_values() [2/4]
template<unsigned SPATIAL_DIM>
void oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 160 of file refineable_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::u_index_ust_heat(), and values.
get_interpolated_values() [3/4]
template<unsigned SPATIAL_DIM>
void oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 126 of file refineable_discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::u_index_ust_heat(), and values.
get_interpolated_values() [4/4]
template<unsigned SPATIAL_DIM>
void oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 126 of file refineable_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::u_index_ust_heat(), and values.
get_Z2_flux() [1/2]
template<unsigned SPATIAL_DIM>
void oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Different to the get_flux function in the base class as we also have to include du/dt as we're doing temporal adaptivity too.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 85 of file refineable_discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::u_index_ust_heat().
get_Z2_flux() [2/2]
template<unsigned SPATIAL_DIM>
void oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Different to the get_flux function in the base class as we also have to include du/dt as we're doing temporal adaptivity too.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 85 of file refineable_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::u_index_ust_heat().
num_Z2_flux_terms() [1/2]
template<unsigned SPATIAL_DIM>
unsigned oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 75 of file refineable_space_time_unsteady_heat_elements.h.
num_Z2_flux_terms() [2/2]
template<unsigned SPATIAL_DIM>
unsigned oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 75 of file refineable_discontinuous_galerkin_space_time_unsteady_heat_elements.h.
The documentation for this class was generated from the following files:
refineable_space_time_unsteady_heat_elements.h
refineable_discontinuous_galerkin_space_time_unsteady_heat_elements.h
refineable_space_time_unsteady_heat_elements.cc
refineable_discontinuous_galerkin_space_time_unsteady_heat_elements.cc