oomph::LinearElasticityEquationsBase< DIM > Class Template Reference
A base class for elements that solve the equations of linear elasticity in Cartesian coordinates. Combines a few generic functions that are shared by LinearElasticityEquations and LinearElasticityEquationsWithPressure (hierher: The latter don't exist yet but will be written as soon as somebody needs them...)
#include <linear_elasticity_elements.h>
Public Types
typedef void(* BodyForceFctPt) (const double &t, const Vector< double > &x, Vector< double > &b)
Function pointer to function that specifies the body force as a function of the Cartesian coordinates and time FCT(t,x,b) -- x and b are Vectors!
Public Member Functions
virtual unsigned u_index_linear_elasticity (const unsigned i) const
Return the index at which the i-th unknown displacement component is stored. The default value, i, is appropriate for single-physics problems.
double d2u_dt2_linear_elasticity (const unsigned &n, const unsigned &i) const
d^2u/dt^2 at local node n
void interpolated_u_linear_elasticity (const Vector< double > &s, Vector< double > &disp) const
Compute vector of FE interpolated displacement u at local coordinate s.
double interpolated_u_linear_elasticity (const Vector< double > &s, const unsigned &i) const
Return FE interpolated displacement u[i] at local coordinate s.
LinearElasticityEquationsBase ()
Constructor: Set null pointers for constitutive law and for isotropic growth function. Set physical parameter values to default values, switch on inertia and set body force to zero.
ElasticityTensor *& elasticity_tensor_pt ()
Return the pointer to the elasticity_tensor.
double E (const unsigned &i, const unsigned &j, const unsigned &k, const unsigned &l) const
Access function to the entries in the elasticity tensor.
const double & lambda_sq () const
Access function for timescale ratio (nondim density)
double *& lambda_sq_pt ()
Access function for pointer to timescale ratio (nondim density)
BodyForceFctPt & body_force_fct_pt ()
Access function: Pointer to body force function.
BodyForceFctPt body_force_fct_pt () const
Access function: Pointer to body force function (const version)
void enable_inertia ()
Switch on solid inertia.
void disable_inertia ()
Switch off solid inertia.
bool is_inertia_enabled () const
Access function to flag that switches inertia on/off (const version)
virtual void pin_elemental_redundant_nodal_solid_pressures ()
Pin the element's redundant solid pressures (needed for refinement)
virtual void get_stress (const Vector< double > &s, DenseMatrix< double > &sigma) const =0
Return the Cauchy stress tensor, as calculated from the elasticity tensor at specified local coordinate Virtual so separaete versions can (and must!) be provided for displacement and pressure-displacement formulations.
void get_strain (const Vector< double > &s, DenseMatrix< double > &strain) const
Return the strain tensor.
void body_force (const Vector< double > &x, Vector< double > &b) const
Evaluate body force at Eulerian coordinate x at present time (returns zero vector if no body force function pointer has been set)
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into: for now lump them all into one DOF type. Can be adjusted later.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF types` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Static Public Member Functions
static void pin_redundant_nodal_solid_pressures (const Vector< GeneralisedElement * > &element_pt)
Loop over all elements in Vector (which typically contains all the elements in a refineable solid mesh) and pin the nodal solid pressure degrees of freedom that are not being used. Function uses the member function.
Protected Attributes
ElasticityTensor * Elasticity_tensor_pt
Pointer to the elasticity tensor.
double * Lambda_sq_pt
Timescale ratio (non-dim. density)
bool Unsteady
Flag that switches inertia on/off.
BodyForceFctPt Body_force_fct_pt
Pointer to body force function.
Static Protected Attributes
static double Default_lambda_sq_value = 1.0
Static default value for timescale ratio (1.0 -- for natural scaling)
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::LinearElasticityEquationsBase< DIM >
A base class for elements that solve the equations of linear elasticity in Cartesian coordinates. Combines a few generic functions that are shared by LinearElasticityEquations and LinearElasticityEquationsWithPressure (hierher: The latter don't exist yet but will be written as soon as somebody needs them...)
Definition at line 56 of file linear_elasticity_elements.h.
Member Typedef Documentation
BodyForceFctPt
template<unsigned DIM>
typedef void(* oomph::LinearElasticityEquationsBase< DIM >::BodyForceFctPt) (const double &t, const Vector< double > &x, Vector< double > &b)
Function pointer to function that specifies the body force as a function of the Cartesian coordinates and time FCT(t,x,b) -- x and b are Vectors!
Definition at line 158 of file linear_elasticity_elements.h.
Constructor & Destructor Documentation
LinearElasticityEquationsBase()
template<unsigned DIM>
oomph::LinearElasticityEquationsBase< DIM >::LinearElasticityEquationsBase () [inline]
Constructor: Set null pointers for constitutive law and for isotropic growth function. Set physical parameter values to default values, switch on inertia and set body force to zero.
Definition at line 165 of file linear_elasticity_elements.h.
Member Function Documentation
body_force()
template<unsigned DIM>
void oomph::LinearElasticityEquationsBase< DIM >::body_force (const Vector< double > & x, Vector< double > & b) const [inline]
Evaluate body force at Eulerian coordinate x at present time (returns zero vector if no body force function pointer has been set)
Definition at line 270 of file linear_elasticity_elements.h.
References oomph::LinearElasticityEquationsBase< DIM >::Body_force_fct_pt, oomph::FiniteElement::dim(), i, oomph::FiniteElement::node_pt(), oomph::Time::time(), oomph::TimeStepper::time_pt(), and oomph::Data::time_stepper_pt().
body_force_fct_pt() [1/2]
template<unsigned DIM>
BodyForceFctPt & oomph::LinearElasticityEquationsBase< DIM >::body_force_fct_pt () [inline]
Access function: Pointer to body force function.
Definition at line 201 of file linear_elasticity_elements.h.
References oomph::LinearElasticityEquationsBase< DIM >::Body_force_fct_pt.
Referenced by oomph::RefineableLinearElasticityEquations< DIM >::further_build().
body_force_fct_pt() [2/2]
template<unsigned DIM>
BodyForceFctPt oomph::LinearElasticityEquationsBase< DIM >::body_force_fct_pt () const [inline]
Access function: Pointer to body force function (const version)
Definition at line 207 of file linear_elasticity_elements.h.
References oomph::LinearElasticityEquationsBase< DIM >::Body_force_fct_pt.
d2u_dt2_linear_elasticity()
template<unsigned DIM>
double oomph::LinearElasticityEquationsBase< DIM >::d2u_dt2_linear_elasticity (const unsigned & n, const unsigned & i) const [inline]
d^2u/dt^2 at local node n
Definition at line 68 of file linear_elasticity_elements.h.
References i, oomph::TimeStepper::is_steady(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), oomph::LinearElasticityEquationsBase< DIM >::u_index_linear_elasticity(), and oomph::TimeStepper::weight().
disable_inertia()
template<unsigned DIM>
void oomph::LinearElasticityEquationsBase< DIM >::disable_inertia () [inline]
Switch off solid inertia.
Definition at line 220 of file linear_elasticity_elements.h.
References oomph::LinearElasticityEquationsBase< DIM >::Unsteady.
E()
template<unsigned DIM>
double oomph::LinearElasticityEquationsBase< DIM >::E (const unsigned & i, const unsigned & j, const unsigned & k, const unsigned & l) const [inline]
Access function to the entries in the elasticity tensor.
Definition at line 180 of file linear_elasticity_elements.h.
References oomph::LinearElasticityEquationsBase< DIM >::Elasticity_tensor_pt, and i.
elasticity_tensor_pt()
template<unsigned DIM>
ElasticityTensor *& oomph::LinearElasticityEquationsBase< DIM >::elasticity_tensor_pt () [inline]
Return the pointer to the elasticity_tensor.
Definition at line 174 of file linear_elasticity_elements.h.
References oomph::LinearElasticityEquationsBase< DIM >::Elasticity_tensor_pt.
Referenced by oomph::RefineableLinearElasticityEquations< DIM >::further_build().
enable_inertia()
template<unsigned DIM>
void oomph::LinearElasticityEquationsBase< DIM >::enable_inertia () [inline]
Switch on solid inertia.
Definition at line 214 of file linear_elasticity_elements.h.
References oomph::LinearElasticityEquationsBase< DIM >::Unsteady.
get_dof_numbers_for_unknowns()
template<unsigned DIM>
void oomph::LinearElasticityEquationsBase< DIM >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [inline], [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF types` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Reimplemented from oomph::GeneralisedElement.
Definition at line 311 of file linear_elasticity_elements.h.
References oomph::GeneralisedElement::eqn_number(), i, oomph::FiniteElement::nnode(), and oomph::FiniteElement::nodal_local_eqn().
get_strain()
template<unsigned DIM>
void oomph::LinearElasticityEquationsBase< DIM >::get_strain (const Vector< double > & s, DenseMatrix< double > & strain) const
Return the strain tensor.
/////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////
Compute the strain tensor at local coordinate s Now fill in the entries of the strain tensor
Definition at line 47 of file linear_elasticity_elements.cc.
References i, oomph::DenseMatrix< T >::ncol(), oomph::DenseMatrix< T >::nrow(), and s.
Referenced by oomph::RefineableLinearElasticityEquations< DIM >::get_Z2_flux(), and oomph::TLinearElasticityElement< DIM, NNODE_1D >::get_Z2_flux().
get_stress()
template<unsigned DIM>
virtual void oomph::LinearElasticityEquationsBase< DIM >::get_stress (const Vector< double > & s, DenseMatrix< double > & sigma) const [pure virtual]
Return the Cauchy stress tensor, as calculated from the elasticity tensor at specified local coordinate Virtual so separaete versions can (and must!) be provided for displacement and pressure-displacement formulations.
Implemented in oomph::LinearElasticityEquations< DIM >.
interpolated_u_linear_elasticity() [1/2]
template<unsigned DIM>
double oomph::LinearElasticityEquationsBase< DIM >::interpolated_u_linear_elasticity (const Vector< double > & s, const unsigned & i) const [inline]
Return FE interpolated displacement u[i] at local coordinate s.
Definition at line 127 of file linear_elasticity_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and oomph::LinearElasticityEquationsBase< DIM >::u_index_linear_elasticity().
interpolated_u_linear_elasticity() [2/2]
template<unsigned DIM>
void oomph::LinearElasticityEquationsBase< DIM >::interpolated_u_linear_elasticity (const Vector< double > & s, Vector< double > & disp) const [inline]
Compute vector of FE interpolated displacement u at local coordinate s.
Definition at line 98 of file linear_elasticity_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and oomph::LinearElasticityEquationsBase< DIM >::u_index_linear_elasticity().
Referenced by oomph::RefineableLinearElasticityEquations< DIM >::get_interpolated_values().
is_inertia_enabled()
template<unsigned DIM>
bool oomph::LinearElasticityEquationsBase< DIM >::is_inertia_enabled () const [inline]
Access function to flag that switches inertia on/off (const version)
Definition at line 226 of file linear_elasticity_elements.h.
References oomph::LinearElasticityEquationsBase< DIM >::Unsteady.
Referenced by oomph::RefineableLinearElasticityEquations< DIM >::further_build().
lambda_sq()
template<unsigned DIM>
const double & oomph::LinearElasticityEquationsBase< DIM >::lambda_sq () const [inline]
Access function for timescale ratio (nondim density)
Definition at line 189 of file linear_elasticity_elements.h.
References oomph::LinearElasticityEquationsBase< DIM >::Lambda_sq_pt.
lambda_sq_pt()
template<unsigned DIM>
double *& oomph::LinearElasticityEquationsBase< DIM >::lambda_sq_pt () [inline]
Access function for pointer to timescale ratio (nondim density)
Definition at line 195 of file linear_elasticity_elements.h.
References oomph::LinearElasticityEquationsBase< DIM >::Lambda_sq_pt.
Referenced by oomph::RefineableLinearElasticityEquations< DIM >::further_build().
ndof_types()
template<unsigned DIM>
unsigned oomph::LinearElasticityEquationsBase< DIM >::ndof_types () const [inline], [virtual]
The number of `DOF types` that degrees of freedom in this element are sub-divided into: for now lump them all into one DOF type. Can be adjusted later.
Reimplemented from oomph::GeneralisedElement.
Definition at line 299 of file linear_elasticity_elements.h.
pin_elemental_redundant_nodal_solid_pressures()
template<unsigned DIM>
virtual void oomph::LinearElasticityEquationsBase< DIM >::pin_elemental_redundant_nodal_solid_pressures () [inline], [virtual]
Pin the element's redundant solid pressures (needed for refinement)
Definition at line 232 of file linear_elasticity_elements.h.
Referenced by oomph::LinearElasticityEquationsBase< DIM >::pin_redundant_nodal_solid_pressures().
pin_redundant_nodal_solid_pressures()
template<unsigned DIM>
static void oomph::LinearElasticityEquationsBase< DIM >::pin_redundant_nodal_solid_pressures (const Vector< GeneralisedElement * > & element_pt) [inline], [static]
Loop over all elements in Vector (which typically contains all the elements in a refineable solid mesh) and pin the nodal solid pressure degrees of freedom that are not being used. Function uses the member function.
LinearElasticityEquationsBase<DIM>:: pin_elemental_redundant_nodal_pressure_dofs()
which is empty by default and should be implemented for elements with nodal solid pressure degrees of freedom (e.g. linear elasticity elements with continuous pressure interpolation.)
Definition at line 245 of file linear_elasticity_elements.h.
References e, and oomph::LinearElasticityEquationsBase< DIM >::pin_elemental_redundant_nodal_solid_pressures().
u_index_linear_elasticity()
template<unsigned DIM>
virtual unsigned oomph::LinearElasticityEquationsBase< DIM >::u_index_linear_elasticity (const unsigned i) const [inline], [virtual]
Return the index at which the i-th unknown displacement component is stored. The default value, i, is appropriate for single-physics problems.
Definition at line 62 of file linear_elasticity_elements.h.
References i.
Referenced by oomph::LinearElasticityEquationsBase< DIM >::d2u_dt2_linear_elasticity(), oomph::RefineableLinearElasticityEquations< DIM >::get_interpolated_values(), and oomph::LinearElasticityEquationsBase< DIM >::interpolated_u_linear_elasticity().
Member Data Documentation
Body_force_fct_pt
template<unsigned DIM>
BodyForceFctPt oomph::LinearElasticityEquationsBase< DIM >::Body_force_fct_pt [protected]
Pointer to body force function.
Definition at line 361 of file linear_elasticity_elements.h.
Referenced by oomph::LinearElasticityEquationsBase< DIM >::body_force(), oomph::LinearElasticityEquationsBase< DIM >::body_force_fct_pt(), and oomph::RefineableLinearElasticityEquations< DIM >::further_build().
Default_lambda_sq_value
template<unsigned DIM>
double oomph::LinearElasticityEquationsBase< DIM >::Default_lambda_sq_value = 1.0 [static], [protected]
Static default value for timescale ratio (1.0 -- for natural scaling)
Definition at line 364 of file linear_elasticity_elements.h.
Elasticity_tensor_pt
template<unsigned DIM>
ElasticityTensor* oomph::LinearElasticityEquationsBase< DIM >::Elasticity_tensor_pt [protected]
Pointer to the elasticity tensor.
Definition at line 352 of file linear_elasticity_elements.h.
Referenced by oomph::LinearElasticityEquationsBase< DIM >::E(), oomph::LinearElasticityEquationsBase< DIM >::elasticity_tensor_pt(), and oomph::RefineableLinearElasticityEquations< DIM >::further_build().
Lambda_sq_pt
template<unsigned DIM>
double* oomph::LinearElasticityEquationsBase< DIM >::Lambda_sq_pt [protected]
Timescale ratio (non-dim. density)
Definition at line 355 of file linear_elasticity_elements.h.
Referenced by oomph::RefineableLinearElasticityEquations< DIM >::further_build(), oomph::LinearElasticityEquationsBase< DIM >::lambda_sq(), and oomph::LinearElasticityEquationsBase< DIM >::lambda_sq_pt().
Unsteady
template<unsigned DIM>
bool oomph::LinearElasticityEquationsBase< DIM >::Unsteady [protected]
Flag that switches inertia on/off.
Definition at line 358 of file linear_elasticity_elements.h.
Referenced by oomph::LinearElasticityEquationsBase< DIM >::disable_inertia(), oomph::LinearElasticityEquationsBase< DIM >::enable_inertia(), oomph::RefineableLinearElasticityEquations< DIM >::further_build(), and oomph::LinearElasticityEquationsBase< DIM >::is_inertia_enabled().
The documentation for this class was generated from the following files:
linear_elasticity_elements.h
linear_elasticity_elements.cc