oomph::FSIDrivenCavityMesh< ELEMENT > Class Template Reference
Mesh for W. Wall's FSI driven cavity problem. The mesh is derived from the SimpleRectangularQuadMesh so it's node and element numbering scheme is the same as in that mesh. Only the boundaries are numbered differently to allow the easy identification of the `collapsible` segment. Boundary coordinates are set up for all nodes located on boundary 3 (the collapsible segment). The curvilinear (`collapsible`) segment is defined by a GeomObject.
#include <fsi_driven_cavity_mesh.template.h>
Public Member Functions
FSIDrivenCavityMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly, const double &gap_fraction, GeomObject *wall_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass number of elements, number of elements, fractional height of the gap above the moving wall, pointer to GeomObject that defines the collapsible segment and pointer to TimeStepper (defaults to the default timestepper, Steady).
Protected Attributes
unsigned Nx
Number of elements in x direction.
unsigned Ny
Number of elements in y direction.
double Gap_fraction
Fraction of the gap next to moving lid, relative to the height of the domain.
GeomObject * Wall_pt
Pointer to geometric object that represents the moving wall.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::FSIDrivenCavityMesh< ELEMENT >
Mesh for W. Wall's FSI driven cavity problem. The mesh is derived from the SimpleRectangularQuadMesh so it's node and element numbering scheme is the same as in that mesh. Only the boundaries are numbered differently to allow the easy identification of the `collapsible` segment. Boundary coordinates are set up for all nodes located on boundary 3 (the collapsible segment). The curvilinear (`collapsible`) segment is defined by a GeomObject.
Boundary 0 is the moving lid.
Boundary 1 is the gap above the moving lid on the right wall
Boundary 2 is the rigid part of the right wall
Boundary 3 is the moving (elastic) wall
Boundary 4 is the rigid part of the left wall
Boundary 5 is the gap above the moving lid on the left wall
Definition at line 65 of file fsi_driven_cavity_mesh.template.h.
Constructor & Destructor Documentation
FSIDrivenCavityMesh()
template<class ELEMENT >
oomph::FSIDrivenCavityMesh< ELEMENT >::FSIDrivenCavityMesh (const unsigned & nx, const unsigned & ny, const double & lx, const double & ly, const double & gap_fraction, GeomObject * wall_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass number of elements, number of elements, fractional height of the gap above the moving wall, pointer to GeomObject that defines the collapsible segment and pointer to TimeStepper (defaults to the default timestepper, Steady).
Constructor: Pass number of elements, lengths, pointer to GeomObject that defines the collapsible segment and pointer to TimeStepper (defaults to the default timestepper, Steady).
Definition at line 41 of file fsi_driven_cavity_mesh.template.cc.
References oomph::Mesh::add_boundary_node(), oomph::Mesh::Boundary_coordinate_exists, e, oomph::Mesh::finite_element_pt(), oomph::FSIDrivenCavityMesh< ELEMENT >::Gap_fraction, i, oomph::Mesh::nboundary(), oomph::Mesh::nelement(), oomph::Mesh::nnode(), oomph::FiniteElement::nnode_1d(), oomph::Mesh::node_pt(), oomph::FiniteElement::node_pt(), oomph::SimpleRectangularQuadMesh< ELEMENT >::nx(), oomph::SimpleRectangularQuadMesh< ELEMENT >::ny(), oomph::Mesh::remove_boundary_nodes(), oomph::Node::set_coordinates_on_boundary(), oomph::Mesh::set_nboundary(), oomph::QuadMeshBase::setup_boundary_element_info(), and oomph::Node::x().
Member Data Documentation
Gap_fraction
template<class ELEMENT >
double oomph::FSIDrivenCavityMesh< ELEMENT >::Gap_fraction [protected]
Fraction of the gap next to moving lid, relative to the height of the domain.
Definition at line 90 of file fsi_driven_cavity_mesh.template.h.
Referenced by oomph::FSIDrivenCavityMesh< ELEMENT >::FSIDrivenCavityMesh().
Nx
template<class ELEMENT >
unsigned oomph::FSIDrivenCavityMesh< ELEMENT >::Nx [protected]
Number of elements in x direction.
Definition at line 83 of file fsi_driven_cavity_mesh.template.h.
Ny
template<class ELEMENT >
unsigned oomph::FSIDrivenCavityMesh< ELEMENT >::Ny [protected]
Number of elements in y direction.
Definition at line 86 of file fsi_driven_cavity_mesh.template.h.
Wall_pt
template<class ELEMENT >
GeomObject* oomph::FSIDrivenCavityMesh< ELEMENT >::Wall_pt [protected]
Pointer to geometric object that represents the moving wall.
Definition at line 93 of file fsi_driven_cavity_mesh.template.h.
The documentation for this class was generated from the following files:
fsi_driven_cavity_mesh.template.h
fsi_driven_cavity_mesh.template.cc