oomph::RefineableTwoDAnnularMesh< ELEMENT > Class Template Reference
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
#include <annular_mesh.template.h>
Public Member Functions
RefineableTwoDAnnularMesh (const bool &periodic, const double &azimuthal_fraction, const unsigned &ntheta, const unsigned &nr, const double &a, const double &h, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor.
RefineableTwoDAnnularMesh (const bool &periodic, const double &azimuthal_fraction, const unsigned &ntheta, const unsigned &nr, const double &a, const double &h, const double &phi, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor; rotate mesh by angle phi.
Private Attributes
AnnularDomain * Domain_pt
Pointer to domain.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::RefineableTwoDAnnularMesh< ELEMENT >
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
Refineable 2D annular mesh with a unit circle in the middle and a layer of thickness h surrounding it.
Definition at line 106 of file annular_mesh.template.h.
Constructor & Destructor Documentation
RefineableTwoDAnnularMesh() [1/2]
template<class ELEMENT >
oomph::RefineableTwoDAnnularMesh< ELEMENT >::RefineableTwoDAnnularMesh (const bool & periodic, const double & azimuthal_fraction, const unsigned & ntheta, const unsigned & nr, const double & a, const double & h, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor.
Definition at line 111 of file annular_mesh.template.h.
References oomph::RefineableTwoDAnnularMesh< ELEMENT >::Domain_pt, oomph::QuadTreeNames::E, oomph::Mesh::element_pt(), i, oomph::Domain::macro_element_pt(), oomph::Mesh::nelement(), oomph::Mesh::node_update(), oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest(), and oomph::W.
RefineableTwoDAnnularMesh() [2/2]
template<class ELEMENT >
oomph::RefineableTwoDAnnularMesh< ELEMENT >::RefineableTwoDAnnularMesh (const bool & periodic, const double & azimuthal_fraction, const unsigned & ntheta, const unsigned & nr, const double & a, const double & h, const double & phi, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor; rotate mesh by angle phi.
Definition at line 179 of file annular_mesh.template.h.
References oomph::RefineableTwoDAnnularMesh< ELEMENT >::Domain_pt, oomph::QuadTreeNames::E, oomph::Mesh::element_pt(), i, oomph::Domain::macro_element_pt(), oomph::Mesh::nelement(), oomph::Mesh::node_update(), oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest(), and oomph::W.
Member Data Documentation
Domain_pt
template<class ELEMENT >
AnnularDomain* oomph::RefineableTwoDAnnularMesh< ELEMENT >::Domain_pt [private]
Pointer to domain.
Definition at line 247 of file annular_mesh.template.h.
Referenced by oomph::RefineableTwoDAnnularMesh< ELEMENT >::RefineableTwoDAnnularMesh().
The documentation for this class was generated from the following file:
annular_mesh.template.h