RefineableLinearisedQTaylorHoodMultiDomainElement Class Reference
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
#include <multi_domain_linearised_navier_stokes_elements.h>
Public Member Functions
RefineableLinearisedQTaylorHoodMultiDomainElement ()
Constructor: call the underlying constructors.
virtual void get_base_flow_u (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result) const
Overload get_base_flow_u(...) to return the external element's velocity components at the integration point.
virtual void get_base_flow_dudx (const double &time, const unsigned &ipt, const Vector< double > &x, DenseMatrix< double > &result) const
Overload get_base_flow_dudx(...) to return the derivatives of the external element's velocity components w.r.t. global coordinates at the integration point.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual vector and the Jacobian matrix.
Additional Inherited Members
Detailed Description
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
Build a RefineableLinearisedQTaylorHood element that inherits from ElementWithExternalElement so that it can `communicate` with an axisymmetric Navier-Stokes element that provides the base flow velocities and their derivatives w.r.t. global coordinates (r and z)
Definition at line 288 of file multi_domain_linearised_navier_stokes_elements.h.
Constructor & Destructor Documentation
RefineableLinearisedQTaylorHoodMultiDomainElement()
RefineableLinearisedQTaylorHoodMultiDomainElement::RefineableLinearisedQTaylorHoodMultiDomainElement () [inline]
Constructor: call the underlying constructors.
Do not include any external geometric data when computing the element's Jacobian.
Definition at line 294 of file multi_domain_linearised_navier_stokes_elements.h.
References oomph::ElementWithExternalElement::set_ninteraction().
Member Function Documentation
fill_in_contribution_to_jacobian()
void RefineableLinearisedQTaylorHoodMultiDomainElement::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute the element's residual vector and the Jacobian matrix.
Reimplemented from oomph::ElementWithExternalElement.
Definition at line 382 of file multi_domain_linearised_navier_stokes_elements.h.
References oomph::ElementWithExternalElement::fill_in_jacobian_from_external_interaction_by_fd().
get_base_flow_dudx()
virtual void RefineableLinearisedQTaylorHoodMultiDomainElement::get_base_flow_dudx (const double & time, const unsigned & ipt, const Vector< double > & x, DenseMatrix< double > & result) const [inline], [virtual]
Overload get_base_flow_dudx(...) to return the derivatives of the external element's velocity components w.r.t. global coordinates at the integration point.
Reimplemented from oomph::LinearisedNavierStokesEquations.
Definition at line 345 of file multi_domain_linearised_navier_stokes_elements.h.
References oomph::ElementWithExternalElement::external_element_local_coord(), oomph::ElementWithExternalElement::external_element_pt(), i, and oomph::NavierStokesEquations< DIM >::interpolated_dudx_nst().
get_base_flow_u()
virtual void RefineableLinearisedQTaylorHoodMultiDomainElement::get_base_flow_u (const double & time, const unsigned & ipt, const Vector< double > & x, Vector< double > & result) const [inline], [virtual]
Overload get_base_flow_u(...) to return the external element's velocity components at the integration point.
Reimplemented from oomph::LinearisedNavierStokesEquations.
Definition at line 312 of file multi_domain_linearised_navier_stokes_elements.h.
References oomph::ElementWithExternalElement::external_element_local_coord(), oomph::ElementWithExternalElement::external_element_pt(), i, and oomph::NavierStokesEquations< DIM >::interpolated_u_nst().
The documentation for this class was generated from the following file:
multi_domain_linearised_navier_stokes_elements.h