oomph::HelmholtzEquations< DIM > Class Template Reference
A class for all isoparametric elements that solve the Helmholtz equations.
#include <helmholtz_elements.h>
Public Types
typedef void(* HelmholtzSourceFctPt) (const Vector< double > &x, std::complex< double > &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
Public Member Functions
HelmholtzEquations ()
Constructor (must initialise the Source_fct_pt to null)
HelmholtzEquations (const HelmholtzEquations &dummy)=delete
Broken copy constructor.
virtual std::complex< unsigned > u_index_helmholtz () const
Broken assignment operator.
double *& k_squared_pt ()
Get pointer to square of wavenumber.
double k_squared ()
Get the square of wavenumber.
unsigned nscalar_paraview () const
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
std::string scalar_name_paraview (const unsigned &i) const
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &n_plot)
Output FE representation of soln: x,y,u_re,u_im or x,y,z,u_re,u_im at n_plot^DIM plot points.
void output_real (std::ostream &outfile, const double &phi, const unsigned &n_plot)
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output FE representation of soln: x,y,u_re,u_im or x,y,z,u_re,u_im at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_re_exact,u_im_exact or x,y,z,u_re_exact,u_im_exact at n_plot^DIM plot points.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: (dummy time-dependent version to keep intel compiler happy)
void output_real_fct (std::ostream &outfile, const double &phi, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for real part of full time-dependent fct u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
HelmholtzSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
HelmholtzSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
virtual void get_source_helmholtz (const unsigned &ipt, const Vector< double > &x, std::complex< double > &source) const
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
void get_flux (const Vector< double > &s, Vector< std::complex< double > > &flux) const
Get flux: flux[i] = du/dx_i for real and imag part.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and element Jacobian matrix (wrapper)
std::complex< double > interpolated_u_helmholtz (const Vector< double > &s) const
Return FE representation of function value u_helmholtz(s) at local coordinate s.
unsigned self_test ()
Self-test: Return 0 for OK.
Protected Member Functions
virtual double dshape_and_dtest_eulerian_helmholtz (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_helmholtz (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
virtual void fill_in_generic_residual_contribution_helmholtz (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Protected Attributes
HelmholtzSourceFctPt Source_fct_pt
Pointer to source function:
double * K_squared_pt
Pointer to square of wavenumber.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::HelmholtzEquations< DIM >
A class for all isoparametric elements that solve the Helmholtz equations.
 \frac{\partial^2 u}{\partial x_i^2} + k^2 u = f(x_j) 
 This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
Definition at line 55 of file helmholtz_elements.h.
Member Typedef Documentation
HelmholtzSourceFctPt
template<unsigned DIM>
typedef void(* oomph::HelmholtzEquations< DIM >::HelmholtzSourceFctPt) (const Vector< double > &x, std::complex< double > &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
Definition at line 60 of file helmholtz_elements.h.
Constructor & Destructor Documentation
HelmholtzEquations() [1/2]
template<unsigned DIM>
oomph::HelmholtzEquations< DIM >::HelmholtzEquations () [inline]
Constructor (must initialise the Source_fct_pt to null)
Definition at line 65 of file helmholtz_elements.h.
HelmholtzEquations() [2/2]
template<unsigned DIM>
oomph::HelmholtzEquations< DIM >::HelmholtzEquations (const HelmholtzEquations< DIM > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
compute_error() [1/2]
template<unsigned DIM>
void oomph::HelmholtzEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution.
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 482 of file helmholtz_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
compute_error() [2/2]
template<unsigned DIM>
void oomph::HelmholtzEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [inline], [virtual]
Dummy, time dependent error checker.
Reimplemented from oomph::FiniteElement.
Definition at line 263 of file helmholtz_elements.h.
dshape_and_dtest_eulerian_at_knot_helmholtz()
template<unsigned DIM>
virtual double oomph::HelmholtzEquations< DIM >::dshape_and_dtest_eulerian_at_knot_helmholtz (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::QHelmholtzElement< DIM, NNODE_1D >, and oomph::THelmholtzElement< DIM, NNODE_1D >.
dshape_and_dtest_eulerian_helmholtz()
template<unsigned DIM>
virtual double oomph::HelmholtzEquations< DIM >::dshape_and_dtest_eulerian_helmholtz (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in oomph::QHelmholtzElement< DIM, NNODE_1D >, and oomph::THelmholtzElement< DIM, NNODE_1D >.
fill_in_contribution_to_jacobian()
template<unsigned DIM>
void oomph::HelmholtzEquations< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and element Jacobian matrix (wrapper)
Reimplemented from oomph::FiniteElement.
Definition at line 359 of file helmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz().
fill_in_contribution_to_residuals()
template<unsigned DIM>
void oomph::HelmholtzEquations< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 348 of file helmholtz_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::HelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz().
fill_in_generic_residual_contribution_helmholtz()
template<unsigned DIM>
void oomph::HelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected], [virtual]
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Compute element residual Vector and/or element Jacobian matrix.
flag=1: compute both flag=0: compute only residual Vector
Pure version without hanging nodes
Reimplemented in oomph::RefineableHelmholtzEquations< DIM >.
Definition at line 49 of file helmholtz_elements.cc.
References i, and oomph::QuadTreeNames::W.
Referenced by oomph::HelmholtzEquations< DIM >::fill_in_contribution_to_jacobian(), and oomph::HelmholtzEquations< DIM >::fill_in_contribution_to_residuals().
get_flux()
template<unsigned DIM>
void oomph::HelmholtzEquations< DIM >::get_flux (const Vector< double > & s, Vector< std::complex< double > > & flux) const [inline]
Get flux: flux[i] = du/dx_i for real and imag part.
Definition at line 310 of file helmholtz_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, and oomph::HelmholtzEquations< DIM >::u_index_helmholtz().
Referenced by oomph::RefineableHelmholtzEquations< DIM >::get_Z2_flux(), and oomph::THelmholtzElement< DIM, NNODE_1D >::get_Z2_flux().
get_source_helmholtz()
template<unsigned DIM>
virtual void oomph::HelmholtzEquations< DIM >::get_source_helmholtz (const unsigned & ipt, const Vector< double > & x, std::complex< double > & source) const [inline], [virtual]
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
Definition at line 292 of file helmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::Source_fct_pt.
interpolated_u_helmholtz()
template<unsigned DIM>
std::complex< double > oomph::HelmholtzEquations< DIM >::interpolated_u_helmholtz (const Vector< double > & s) const [inline]
Return FE representation of function value u_helmholtz(s) at local coordinate s.
Definition at line 369 of file helmholtz_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and oomph::HelmholtzEquations< DIM >::u_index_helmholtz().
Referenced by oomph::HelmholtzEquations< DIM >::scalar_value_paraview().
k_squared()
template<unsigned DIM>
double oomph::HelmholtzEquations< DIM >::k_squared () [inline]
Get the square of wavenumber.
Definition at line 94 of file helmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::K_squared_pt.
k_squared_pt()
template<unsigned DIM>
double *& oomph::HelmholtzEquations< DIM >::k_squared_pt () [inline]
Get pointer to square of wavenumber.
Definition at line 87 of file helmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::K_squared_pt.
Referenced by oomph::RefineableHelmholtzEquations< DIM >::further_build().
nscalar_paraview()
template<unsigned DIM>
unsigned oomph::HelmholtzEquations< DIM >::nscalar_paraview () const [inline], [virtual]
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
Reimplemented from oomph::FiniteElement.
Definition at line 111 of file helmholtz_elements.h.
output() [1/4]
template<unsigned DIM>
void oomph::HelmholtzEquations< DIM >::output (FILE * file_pt) [inline], [virtual]
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QHelmholtzElement< DIM, NNODE_1D >, and oomph::THelmholtzElement< DIM, NNODE_1D >.
Definition at line 213 of file helmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::output().
output() [2/4]
template<unsigned DIM>
void oomph::HelmholtzEquations< DIM >::output (FILE * file_pt, const unsigned & nplot) [virtual]
C-style output FE representation of soln: x,y,u_re,u_im or x,y,z,u_re,u_im at n_plot^DIM plot points.
C-style output function:
x,y,u or x,y,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QHelmholtzElement< DIM, NNODE_1D >, and oomph::THelmholtzElement< DIM, NNODE_1D >.
Definition at line 331 of file helmholtz_elements.cc.
References i, and s.
output() [3/4]
template<unsigned DIM>
void oomph::HelmholtzEquations< DIM >::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QHelmholtzElement< DIM, NNODE_1D >, and oomph::THelmholtzElement< DIM, NNODE_1D >.
Definition at line 193 of file helmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::output().
Referenced by oomph::HelmholtzEquations< DIM >::output(), oomph::QHelmholtzElement< DIM, NNODE_1D >::output(), and oomph::THelmholtzElement< DIM, NNODE_1D >::output().
output() [4/4]
template<unsigned DIM>
void oomph::HelmholtzEquations< DIM >::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: x,y,u_re,u_im or x,y,z,u_re,u_im at n_plot^DIM plot points.
Output function:
x,y,u_re,u_imag or x,y,z,u_re,u_imag
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QHelmholtzElement< DIM, NNODE_1D >, and oomph::THelmholtzElement< DIM, NNODE_1D >.
Definition at line 254 of file helmholtz_elements.cc.
References i, and s.
output_fct() [1/2]
template<unsigned DIM>
virtual void oomph::HelmholtzEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output exact soln: (dummy time-dependent version to keep intel compiler happy)
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QHelmholtzElement< DIM, NNODE_1D >, and oomph::THelmholtzElement< DIM, NNODE_1D >.
Definition at line 231 of file helmholtz_elements.h.
output_fct() [2/2]
template<unsigned DIM>
void oomph::HelmholtzEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: x,y,u_re_exact,u_im_exact or x,y,z,u_re_exact,u_im_exact at n_plot^DIM plot points.
Output exact solution.
Solution is provided via function pointer. Plot at a given number of plot points.
x,y,u_exact or x,y,z,u_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QHelmholtzElement< DIM, NNODE_1D >, and oomph::THelmholtzElement< DIM, NNODE_1D >.
Definition at line 374 of file helmholtz_elements.cc.
References i, and s.
Referenced by oomph::QHelmholtzElement< DIM, NNODE_1D >::output_fct(), and oomph::THelmholtzElement< DIM, NNODE_1D >::output_fct().
output_real()
template<unsigned DIM>
void oomph::HelmholtzEquations< DIM >::output_real (std::ostream & outfile, const double & phi, const unsigned & nplot)
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
Output function for real part of full time-dependent solution.
u = Re((u_r +i u_i) exp(-i omega t)
at phase angle omega t = phi.
x,y,u or x,y,z,u
Output at nplot points in each coordinate direction
Definition at line 294 of file helmholtz_elements.cc.
References i, and s.
Referenced by oomph::QHelmholtzElement< DIM, NNODE_1D >::output_real().
output_real_fct()
template<unsigned DIM>
void oomph::HelmholtzEquations< DIM >::output_real_fct (std::ostream & outfile, const double & phi, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for real part of full time-dependent fct u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
Output function for real part of full time-dependent fct.
u = Re((u_r +i u_i) exp(-i omega t)
at phase angle omega t = phi.
x,y,u or x,y,z,u
Output at nplot points in each coordinate direction
Definition at line 429 of file helmholtz_elements.cc.
References i, and s.
Referenced by oomph::QHelmholtzElement< DIM, NNODE_1D >::output_real_fct().
scalar_name_paraview()
template<unsigned DIM>
std::string oomph::HelmholtzEquations< DIM >::scalar_name_paraview (const unsigned & i) const [inline], [virtual]
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
Reimplemented from oomph::FiniteElement.
Definition at line 164 of file helmholtz_elements.h.
References i.
scalar_value_paraview()
template<unsigned DIM>
void oomph::HelmholtzEquations< DIM >::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const [inline], [virtual]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
Definition at line 118 of file helmholtz_elements.h.
References oomph::FiniteElement::get_s_plot(), i, oomph::HelmholtzEquations< DIM >::interpolated_u_helmholtz(), oomph::FiniteElement::nplot_points_paraview(), and s.
self_test()
template<unsigned DIM>
unsigned oomph::HelmholtzEquations< DIM >::self_test [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
Definition at line 224 of file helmholtz_elements.cc.
References oomph::FiniteElement::self_test().
source_fct_pt() [1/2]
template<unsigned DIM>
HelmholtzSourceFctPt & oomph::HelmholtzEquations< DIM >::source_fct_pt () [inline]
Access function: Pointer to source function.
Definition at line 276 of file helmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::Source_fct_pt.
Referenced by oomph::RefineableHelmholtzEquations< DIM >::further_build().
source_fct_pt() [2/2]
template<unsigned DIM>
HelmholtzSourceFctPt oomph::HelmholtzEquations< DIM >::source_fct_pt () const [inline]
Access function: Pointer to source function. Const version.
Definition at line 282 of file helmholtz_elements.h.
References oomph::HelmholtzEquations< DIM >::Source_fct_pt.
u_index_helmholtz()
template<unsigned DIM>
virtual std::complex< unsigned > oomph::HelmholtzEquations< DIM >::u_index_helmholtz () const [inline], [virtual]
Broken assignment operator.
Return the index at which the unknown value is stored.
Definition at line 80 of file helmholtz_elements.h.
Referenced by oomph::HelmholtzEquations< DIM >::get_flux(), oomph::RefineableHelmholtzEquations< DIM >::get_interpolated_values(), oomph::HelmholtzBCElementBase< ELEMENT >::HelmholtzBCElementBase(), oomph::HelmholtzFluxElement< ELEMENT >::HelmholtzFluxElement(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::HelmholtzFluxFromNormalDisplacementBCElement(), and oomph::HelmholtzEquations< DIM >::interpolated_u_helmholtz().
Member Data Documentation
K_squared_pt
template<unsigned DIM>
double* oomph::HelmholtzEquations< DIM >::K_squared_pt [protected]
Pointer to square of wavenumber.
Definition at line 437 of file helmholtz_elements.h.
Referenced by oomph::RefineableHelmholtzEquations< DIM >::further_build(), oomph::HelmholtzEquations< DIM >::k_squared(), and oomph::HelmholtzEquations< DIM >::k_squared_pt().
Source_fct_pt
template<unsigned DIM>
HelmholtzSourceFctPt oomph::HelmholtzEquations< DIM >::Source_fct_pt [protected]
Pointer to source function:
Definition at line 434 of file helmholtz_elements.h.
Referenced by oomph::RefineableHelmholtzEquations< DIM >::further_build(), oomph::HelmholtzEquations< DIM >::get_source_helmholtz(), and oomph::HelmholtzEquations< DIM >::source_fct_pt().
The documentation for this class was generated from the following files:
helmholtz_elements.h
helmholtz_elements.cc