oomph::AxisymmetricPVDEquations Class Reference
A class for elements that solve the equations of solid mechanics, based on the principle of virtual displacements in an axisymmetric formulation. In this case x[0] is the component of displacement in the radial direction and x[1] is that in the theta direction.
#include <axisym_solid_elements.h>
Public Member Functions
AxisymmetricPVDEquations ()
Constructor.
ConstitutiveLaw *& constitutive_law_pt ()
Return the constitutive law pointer.
void get_stress (const DenseMatrix< double > &g, const DenseMatrix< double > &G, DenseMatrix< double > &sigma)
Return the stress tensor, as calculated from the constitutive law.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in the residuals by calling the generic function.
void fill_in_contribution_to_residuals_axisym_pvd (Vector< double > &residuals)
Return the residuals for the equations of solid mechanics.
double compute_physical_size () const
Overload/implement the function to calculate the volume of the element.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Assign the contribution to the residual using only finite differences.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
void output (FILE *file_pt)
Overload the output function.
void output (FILE *file_pt, const unsigned &n_plot)
Output function.
Private Attributes
ConstitutiveLaw * Constitutive_law_pt
Pointer to constitutive law.
Additional Inherited Members
Detailed Description
A class for elements that solve the equations of solid mechanics, based on the principle of virtual displacements in an axisymmetric formulation. In this case x[0] is the component of displacement in the radial direction and x[1] is that in the theta direction.
Definition at line 49 of file axisym_solid_elements.h.
Constructor & Destructor Documentation
AxisymmetricPVDEquations()
oomph::AxisymmetricPVDEquations::AxisymmetricPVDEquations () [inline]
Constructor.
Definition at line 57 of file axisym_solid_elements.h.
Member Function Documentation
compute_physical_size()
double oomph::AxisymmetricPVDEquations::compute_physical_size () const [inline], [virtual]
Overload/implement the function to calculate the volume of the element.
Reimplemented from oomph::FiniteElement.
Definition at line 284 of file axisym_solid_elements.h.
References oomph::SolidFiniteElement::dshape_lagrangian_at_knot(), i, oomph::FiniteElement::integral_pt(), oomph::SolidFiniteElement::interpolated_xi(), oomph::SolidFiniteElement::lagrangian_position_gen(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position_gen(), oomph::Integral::nweight(), oomph::MathematicalConstants::Pi, oomph::QuadTreeNames::W, and oomph::Integral::weight().
constitutive_law_pt()
ConstitutiveLaw*& oomph::AxisymmetricPVDEquations::constitutive_law_pt () [inline]
Return the constitutive law pointer.
Definition at line 60 of file axisym_solid_elements.h.
References Constitutive_law_pt.
fill_in_contribution_to_jacobian()
void oomph::AxisymmetricPVDEquations::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Assign the contribution to the residual using only finite differences.
Reimplemented from oomph::GeneralisedElement.
Definition at line 388 of file axisym_solid_elements.h.
References fill_in_contribution_to_residuals_axisym_pvd(), oomph::SolidFiniteElement::fill_in_jacobian_for_newmark_accel(), oomph::SolidFiniteElement::fill_in_jacobian_from_solid_position_by_fd(), and oomph::SolidFiniteElement::Solve_for_consistent_newmark_accel_flag.
fill_in_contribution_to_residuals()
void oomph::AxisymmetricPVDEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Fill in the residuals by calling the generic function.
Reimplemented from oomph::GeneralisedElement.
Definition at line 88 of file axisym_solid_elements.h.
References fill_in_contribution_to_residuals_axisym_pvd().
fill_in_contribution_to_residuals_axisym_pvd()
void oomph::AxisymmetricPVDEquations::fill_in_contribution_to_residuals_axisym_pvd (Vector< double > & residuals) [inline]
Return the residuals for the equations of solid mechanics.
Definition at line 94 of file axisym_solid_elements.h.
References oomph::SolidFiniteElement::dshape_lagrangian_at_knot(), get_stress(), i, oomph::FiniteElement::integral_pt(), oomph::SolidFiniteElement::interpolated_xi(), oomph::SolidFiniteElement::lagrangian_position_gen(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position_gen(), oomph::Integral::nweight(), oomph::SolidFiniteElement::position_local_eqn(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by fill_in_contribution_to_jacobian(), and fill_in_contribution_to_residuals().
get_stress()
void oomph::AxisymmetricPVDEquations::get_stress (const DenseMatrix< double > & g, const DenseMatrix< double > & G, DenseMatrix< double > & sigma) [inline]
Return the stress tensor, as calculated from the constitutive law.
Definition at line 66 of file axisym_solid_elements.h.
References oomph::ConstitutiveLaw::calculate_second_piola_kirchhoff_stress(), Constitutive_law_pt, and oomph::Global_string_for_annotation::string().
Referenced by fill_in_contribution_to_residuals_axisym_pvd().
output() [1/4]
void oomph::AxisymmetricPVDEquations::output (FILE * file_pt) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::AxisymDiagHermitePVDElement, and oomph::AxisymQPVDElement.
Definition at line 448 of file axisym_solid_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
void oomph::AxisymmetricPVDEquations::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::AxisymDiagHermitePVDElement, and oomph::AxisymQPVDElement.
Definition at line 455 of file axisym_solid_elements.h.
References i, oomph::FiniteElement::interpolated_x(), oomph::SolidFiniteElement::interpolated_xi(), and s.
output() [3/4]
void oomph::AxisymmetricPVDEquations::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::AxisymDiagHermitePVDElement, and oomph::AxisymQPVDElement.
Definition at line 407 of file axisym_solid_elements.h.
References oomph::FiniteElement::output().
Referenced by oomph::AxisymQPVDElement::output().
output() [4/4]
void oomph::AxisymmetricPVDEquations::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::AxisymDiagHermitePVDElement, and oomph::AxisymQPVDElement.
Definition at line 413 of file axisym_solid_elements.h.
References i, oomph::FiniteElement::interpolated_x(), oomph::SolidFiniteElement::interpolated_xi(), and s.
Member Data Documentation
Constitutive_law_pt
ConstitutiveLaw* oomph::AxisymmetricPVDEquations::Constitutive_law_pt [private]
Pointer to constitutive law.
Definition at line 53 of file axisym_solid_elements.h.
Referenced by constitutive_law_pt(), and get_stress().
The documentation for this class was generated from the following file:
axisym_solid_elements.h