oomph::PolarTaylorHoodElement Class Reference
/////////////////////////////////////////////////////////////////////////
#include <polar_navier_stokes_elements.h>
Public Member Functions
PolarTaylorHoodElement ()
Constructor, no internal data points.
virtual unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
virtual int p_nodal_index_pnst ()
Which nodal value represents the pressure?
Node * pressure_node_pt (const unsigned &n_p)
Pointer to n_p-th pressure node.
double u_pnst (const unsigned &n, const unsigned &i) const
Return the velocity component u[i] at local node n. Uses suitably interpolated value for hanging nodes.
double u_pnst (const unsigned &t, const unsigned &n, const unsigned &i) const
Return the velocity component u[i] at local node n at timestep t (t=0: present; t>0: previous timestep). Uses suitably interpolated value for hanging nodes.
double p_pnst (const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
unsigned npres_pnst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void get_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs of pointers to data objects and unsigned integers that index the values in the data object that affect the load (traction), as specified in the get_load() function.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &Nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &Nplot)
Redirect output to NavierStokesEquations output.
Protected Member Functions
double dshape_and_dtest_eulerian_pnst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_pnst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
void pshape_pnst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_pnst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
int p_local_eqn (const unsigned &n)
Return the local equation numbers for the pressure values.
Static Protected Attributes
static const unsigned Pconv [] = {0, 2, 6, 8}
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Static Private Attributes
static const unsigned Initial_Nvalue []
Static array of ints to hold number of variables at node.
Additional Inherited Members
Detailed Description
/////////////////////////////////////////////////////////////////////////
Taylor--Hood elements are Navier--Stokes elements with quadratic interpolation for velocities and positions and continous linear pressure interpolation
Definition at line 1012 of file polar_navier_stokes_elements.h.
Constructor & Destructor Documentation
PolarTaylorHoodElement()
oomph::PolarTaylorHoodElement::PolarTaylorHoodElement () [inline]
Constructor, no internal data points.
Definition at line 1058 of file polar_navier_stokes_elements.h.
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_pnst()
double oomph::PolarTaylorHoodElement::dshape_and_dtest_eulerian_at_knot_pnst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
2D : Derivatives of the shape functions and test functions w.r.t to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::PolarNavierStokesEquations.
Definition at line 1184 of file polar_navier_stokes_elements.h.
References i.
dshape_and_dtest_eulerian_pnst()
double oomph::PolarTaylorHoodElement::dshape_and_dtest_eulerian_pnst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
2D : Derivatives of the shape functions and test functions w.r.t to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::PolarNavierStokesEquations.
Definition at line 1156 of file polar_navier_stokes_elements.h.
References i, and s.
fix_pressure()
void oomph::PolarTaylorHoodElement::fix_pressure (const unsigned & p_dof, const double & p_value) [inline], [virtual]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implements oomph::PolarNavierStokesEquations.
Definition at line 1109 of file polar_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt(), and p_nodal_index_pnst().
get_load_data()
void oomph::PolarTaylorHoodElement::get_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data)
Add to the set paired_load_data pairs of pointers to data objects and unsigned integers that index the values in the data object that affect the load (traction), as specified in the get_load() function.
Add pointers to Data and the indices of the values that affect the potential load (traction) applied to the SolidElements to the set paired_load_data.
Definition at line 1622 of file polar_navier_stokes_elements.cc.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), npres_pnst(), and Pconv.
npres_pnst()
unsigned oomph::PolarTaylorHoodElement::npres_pnst () const [inline], [virtual]
Return number of pressure values.
Implements oomph::PolarNavierStokesEquations.
Definition at line 1103 of file polar_navier_stokes_elements.h.
Referenced by get_load_data(), oomph::RefineablePolarTaylorHoodElement::insert_load_data(), and oomph::RefineablePolarTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs().
output() [1/4]
void oomph::PolarTaylorHoodElement::output (FILE * file_pt) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::PolarNavierStokesEquations.
Definition at line 1136 of file polar_navier_stokes_elements.h.
References oomph::PolarNavierStokesEquations::output().
output() [2/4]
void oomph::PolarTaylorHoodElement::output (FILE * file_pt, const unsigned & Nplot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::PolarNavierStokesEquations.
Definition at line 1142 of file polar_navier_stokes_elements.h.
References oomph::PolarNavierStokesEquations::output().
output() [3/4]
void oomph::PolarTaylorHoodElement::output (std::ostream & outfile) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::PolarNavierStokesEquations.
Definition at line 1124 of file polar_navier_stokes_elements.h.
References oomph::PolarNavierStokesEquations::output().
output() [4/4]
void oomph::PolarTaylorHoodElement::output (std::ostream & outfile, const unsigned & Nplot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::PolarNavierStokesEquations.
Definition at line 1130 of file polar_navier_stokes_elements.h.
References oomph::PolarNavierStokesEquations::output().
p_local_eqn()
int oomph::PolarTaylorHoodElement::p_local_eqn (const unsigned & n) [inline], [protected], [virtual]
Return the local equation numbers for the pressure values.
Implements oomph::PolarNavierStokesEquations.
Definition at line 1051 of file polar_navier_stokes_elements.h.
References oomph::FiniteElement::nodal_local_eqn(), and p_nodal_index_pnst().
p_nodal_index_pnst()
virtual int oomph::PolarTaylorHoodElement::p_nodal_index_pnst () [inline], [virtual]
Which nodal value represents the pressure?
Reimplemented from oomph::PolarNavierStokesEquations.
Definition at line 1068 of file polar_navier_stokes_elements.h.
Referenced by fix_pressure(), oomph::RefineablePolarTaylorHoodElement::further_setup_hanging_nodes(), oomph::RefineablePolarTaylorHoodElement::insert_load_data(), p_local_eqn(), oomph::RefineablePolarTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), and oomph::RefineablePolarTaylorHoodElement::unpin_elemental_pressure_dofs().
p_pnst()
double oomph::PolarTaylorHoodElement::p_pnst (const unsigned & n_p) const [inline], [virtual]
Access function for the pressure values at local pressure node n_p (const version)
Implements oomph::PolarNavierStokesEquations.
Definition at line 1096 of file polar_navier_stokes_elements.h.
References oomph::FiniteElement::nodal_value().
pressure_node_pt()
Node * oomph::PolarTaylorHoodElement::pressure_node_pt (const unsigned & n_p) [inline], [virtual]
Pointer to n_p-th pressure node.
Reimplemented from oomph::PolarNavierStokesEquations.
Reimplemented in oomph::RefineablePolarTaylorHoodElement.
Definition at line 1074 of file polar_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt().
pshape_pnst() [1/2]
void oomph::PolarTaylorHoodElement::pshape_pnst (const Vector< double > & s, Shape & psi) const [inline], [protected], [virtual]
Pressure shape functions at local coordinate s.
2D : Pressure shape functions
Implements oomph::PolarNavierStokesEquations.
Definition at line 1210 of file polar_navier_stokes_elements.h.
References i, s, and oomph::OneDimLagrange::shape< 2 >().
Referenced by oomph::RefineablePolarTaylorHoodElement::interpolating_basis(), and pshape_pnst().
pshape_pnst() [2/2]
void oomph::PolarTaylorHoodElement::pshape_pnst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected], [virtual]
Pressure shape and test functions at local coordinte s.
2D : Pressure shape and test functions
Implements oomph::PolarNavierStokesEquations.
Definition at line 1237 of file polar_navier_stokes_elements.h.
References i, pshape_pnst(), and s.
required_nvalue()
virtual unsigned oomph::PolarTaylorHoodElement::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::RefineablePolarTaylorHoodElement.
Definition at line 1062 of file polar_navier_stokes_elements.h.
References Initial_Nvalue.
u_pnst() [1/2]
double oomph::PolarTaylorHoodElement::u_pnst (const unsigned & n, const unsigned & i) const [inline], [virtual]
Return the velocity component u[i] at local node n. Uses suitably interpolated value for hanging nodes.
Implements oomph::PolarNavierStokesEquations.
Definition at line 1081 of file polar_navier_stokes_elements.h.
References i, and oomph::FiniteElement::nodal_value().
u_pnst() [2/2]
double oomph::PolarTaylorHoodElement::u_pnst (const unsigned & t, const unsigned & n, const unsigned & i) const [inline], [virtual]
Return the velocity component u[i] at local node n at timestep t (t=0: present; t>0: previous timestep). Uses suitably interpolated value for hanging nodes.
Implements oomph::PolarNavierStokesEquations.
Definition at line 1089 of file polar_navier_stokes_elements.h.
References i, and oomph::FiniteElement::nodal_value().
Member Data Documentation
Initial_Nvalue
const unsigned oomph::PolarTaylorHoodElement::Initial_Nvalue [static], [private]
Initial value:
= {
    3, 2, 3, 2, 2, 2, 3, 2, 3}
Static array of ints to hold number of variables at node.
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Definition at line 1017 of file polar_navier_stokes_elements.h.
Referenced by required_nvalue().
Pconv
const unsigned oomph::PolarTaylorHoodElement::Pconv = {0, 2, 6, 8} [static], [protected]
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Definition at line 1022 of file polar_navier_stokes_elements.h.
Referenced by get_load_data(), and oomph::RefineablePolarTaylorHoodElement::pressure_node_pt().
The documentation for this class was generated from the following files:
polar_navier_stokes_elements.h
polar_navier_stokes_elements.cc