oomph::ElasticAxisymmetricVolumeConstraintBoundingElement< ELEMENT > Class Template Reference
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
#include <constrained_volume_elements.h>
Public Member Functions
ElasticAxisymmetricVolumeConstraintBoundingElement (FiniteElement *const &element_pt, const int &face_index)
Contructor: Specify bulk element and index of face to which this face element is to be attached.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Fill in contribution to residuals and Jacobian. This is specific to solid-based elements in which derivatives w.r.t. to nodal positions are evaluated by finite differencing.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::ElasticAxisymmetricVolumeConstraintBoundingElement< ELEMENT >
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
The axisymmetric (one-dimensional) interface elements that allow imposition of a volume constraint specialised for the case when the nodal positions of the bulk elements are treated as solid degrees of freedom. To enforce that a fluid volume has a certain volume, attach these elements to all faces of the (2D axisymmetric) bulk fluid elements (of type ELEMENT) that bound that region and then specify the `pressure` value that is traded for the constraint.
Definition at line 602 of file constrained_volume_elements.h.
Constructor & Destructor Documentation
ElasticAxisymmetricVolumeConstraintBoundingElement()
template<class ELEMENT >
oomph::ElasticAxisymmetricVolumeConstraintBoundingElement< ELEMENT >::ElasticAxisymmetricVolumeConstraintBoundingElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Contructor: Specify bulk element and index of face to which this face element is to be attached.
Definition at line 609 of file constrained_volume_elements.h.
References oomph::FiniteElement::build_face_element(), and oomph::FaceElement::face_index().
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::ElasticAxisymmetricVolumeConstraintBoundingElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Fill in contribution to residuals and Jacobian. This is specific to solid-based elements in which derivatives w.r.t. to nodal positions are evaluated by finite differencing.
Reimplemented from oomph::GeneralisedElement.
Definition at line 621 of file constrained_volume_elements.h.
References oomph::AxisymmetricVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint().
zeta_nodal()
template<class ELEMENT >
double oomph::ElasticAxisymmetricVolumeConstraintBoundingElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default.
Reimplemented from oomph::FiniteElement.
Definition at line 635 of file constrained_volume_elements.h.
References i, and oomph::FaceElement::zeta_nodal().
The documentation for this class was generated from the following file:
constrained_volume_elements.h