oomph::CompressedMatrixCoefficient Class Reference
Class for a compressed-matrix coefficent (for either CC or CR matrices). Contains the (row or column) index and value of a coefficient in a compressed row or column. Currently only used in ILU(0) for CCDoubleMatrices to allow the coefficients in each compressed column [row] to be sorted by their row [column] index.
#include <general_purpose_preconditioners.h>
Public Member Functions
CompressedMatrixCoefficient ()
Constructor (no arguments)
CompressedMatrixCoefficient (const unsigned &index, const double &value)
Constructor (takes the index and value as arguments)
~CompressedMatrixCoefficient ()
Destructor (does nothing)
CompressedMatrixCoefficient (const CompressedMatrixCoefficient &a)
Copy Constructor. Not Broken. Required for STL sort function.
void operator= (const CompressedMatrixCoefficient &a)
Assignment Operator. Not Broken. Required for STL sort function.
bool operator< (const CompressedMatrixCoefficient &a) const
Less Than Operator (for the STL sort function)
unsigned & index ()
access function for the coefficient's (row or column) index
double & value ()
access function for the coefficient value
unsigned index () const
Access function for the coefficient's (row or column_ index (const version)
double value () const
access function for the coefficient's value (const version)
Private Attributes
unsigned Index
the row or column index of the compressed-matrix coefficient
double Value
the value of the compressed-matrix coefficient
Detailed Description
Class for a compressed-matrix coefficent (for either CC or CR matrices). Contains the (row or column) index and value of a coefficient in a compressed row or column. Currently only used in ILU(0) for CCDoubleMatrices to allow the coefficients in each compressed column [row] to be sorted by their row [column] index.
Definition at line 184 of file general_purpose_preconditioners.h.
Constructor & Destructor Documentation
CompressedMatrixCoefficient() [1/3]
oomph::CompressedMatrixCoefficient::CompressedMatrixCoefficient () [inline]
Constructor (no arguments)
Definition at line 188 of file general_purpose_preconditioners.h.
CompressedMatrixCoefficient() [2/3]
oomph::CompressedMatrixCoefficient::CompressedMatrixCoefficient (const unsigned & index, const double & value) [inline]
Constructor (takes the index and value as arguments)
Definition at line 191 of file general_purpose_preconditioners.h.
References index(), Index, value(), and Value.
 CompressedMatrixCoefficient()
oomph::CompressedMatrixCoefficient::~CompressedMatrixCoefficient () [inline]
Destructor (does nothing)
Definition at line 199 of file general_purpose_preconditioners.h.
CompressedMatrixCoefficient() [3/3]
oomph::CompressedMatrixCoefficient::CompressedMatrixCoefficient (const CompressedMatrixCoefficient & a) [inline]
Copy Constructor. Not Broken. Required for STL sort function.
Definition at line 202 of file general_purpose_preconditioners.h.
References index(), Index, value(), and Value.
Member Function Documentation
index() [1/2]
unsigned & oomph::CompressedMatrixCoefficient::index () [inline]
access function for the coefficient's (row or column) index
Definition at line 222 of file general_purpose_preconditioners.h.
References Index.
Referenced by CompressedMatrixCoefficient(), operator<(), and operator=().
index() [2/2]
unsigned oomph::CompressedMatrixCoefficient::index () const [inline]
Access function for the coefficient's (row or column_ index (const version)
Definition at line 235 of file general_purpose_preconditioners.h.
References Index.
operator<()
bool oomph::CompressedMatrixCoefficient::operator< (const CompressedMatrixCoefficient & a) const [inline]
Less Than Operator (for the STL sort function)
Definition at line 216 of file general_purpose_preconditioners.h.
References index(), and Index.
operator=()
void oomph::CompressedMatrixCoefficient::operator= (const CompressedMatrixCoefficient & a) [inline]
Assignment Operator. Not Broken. Required for STL sort function.
Definition at line 209 of file general_purpose_preconditioners.h.
References index(), Index, value(), and Value.
value() [1/2]
double & oomph::CompressedMatrixCoefficient::value () [inline]
access function for the coefficient value
Definition at line 228 of file general_purpose_preconditioners.h.
References Value.
Referenced by CompressedMatrixCoefficient(), and operator=().
value() [2/2]
double oomph::CompressedMatrixCoefficient::value () const [inline]
access function for the coefficient's value (const version)
Definition at line 241 of file general_purpose_preconditioners.h.
References Value.
Member Data Documentation
Index
unsigned oomph::CompressedMatrixCoefficient::Index [private]
the row or column index of the compressed-matrix coefficient
Definition at line 248 of file general_purpose_preconditioners.h.
Referenced by CompressedMatrixCoefficient(), index(), operator<(), and operator=().
Value
double oomph::CompressedMatrixCoefficient::Value [private]
the value of the compressed-matrix coefficient
Definition at line 251 of file general_purpose_preconditioners.h.
Referenced by CompressedMatrixCoefficient(), operator=(), and value().
The documentation for this class was generated from the following file:
general_purpose_preconditioners.h