oomph::HermiteBeamElement Class Reference
Hermite Kirchhoff Love beam. Implements KirchhoffLoveBeamEquations using 2-node Hermite elements as the underlying geometrical elements.
#include <beam_elements.h>
Public Member Functions
HermiteBeamElement ()
Constructor (empty)
void output (std::ostream &outfile)
Output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function with specified number of plot points.
void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
Output at previous time (t=0: present; t>0: previous) with specified number of plot points.
void output (FILE *file_pt)
C-style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function with specified number of plot points.
void output (const unsigned &t, FILE *file_pt, const unsigned &n_plot) const
C-style output at previous time (t=0: present; t>0: previous) with specified number of plot points.
Additional Inherited Members
Detailed Description
Hermite Kirchhoff Love beam. Implements KirchhoffLoveBeamEquations using 2-node Hermite elements as the underlying geometrical elements.
Definition at line 311 of file beam_elements.h.
Constructor & Destructor Documentation
HermiteBeamElement()
oomph::HermiteBeamElement::HermiteBeamElement () [inline]
Constructor (empty)
Definition at line 316 of file beam_elements.h.
References oomph::FiniteElement::set_nodal_dimension().
Member Function Documentation
output() [1/6]
void oomph::HermiteBeamElement::output (const unsigned & t, FILE * file_pt, const unsigned & n_plot) const
C-style output at previous time (t=0: present; t>0: previous) with specified number of plot points.
C-style output position at previous time (t=0: present; t>0: previous) with specified number of plot points.
Definition at line 940 of file beam_elements.cc.
References i, oomph::FiniteElement::interpolated_x(), oomph::Node::ndim(), oomph::FiniteElement::node_pt(), s, and t.
output() [2/6]
void oomph::HermiteBeamElement::output (const unsigned & t, std::ostream & outfile, const unsigned & n_plot) const [virtual]
Output at previous time (t=0: present; t>0: previous) with specified number of plot points.
Output position at previous time (t=0: present; t>0: previous) with specified number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 786 of file beam_elements.cc.
References i, oomph::FiniteElement::interpolated_x(), oomph::Node::ndim(), oomph::FiniteElement::node_pt(), s, and t.
output() [3/6]
void oomph::HermiteBeamElement::output (FILE * file_pt) [virtual]
C-style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 1095 of file beam_elements.cc.
References output().
output() [4/6]
void oomph::HermiteBeamElement::output (FILE * file_pt, const unsigned & n_plot) [virtual]
C-style output function with specified number of plot points.
Output function.
Reimplemented from oomph::FiniteElement.
Definition at line 982 of file beam_elements.cc.
References i, oomph::SolidFiniteElement::interpolated_xi(), oomph::GeomObject::ndim(), oomph::GeomObject::nlagrangian(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::raw_dnodal_position_gen_dt(), oomph::SolidFiniteElement::raw_lagrangian_position_gen(), s, oomph::QHermiteElement< DIM >::shape(), and oomph::KirchhoffLoveBeamEquations::Undeformed_beam_pt.
output() [5/6]
void oomph::HermiteBeamElement::output (std::ostream & outfile) [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Definition at line 929 of file beam_elements.cc.
References output().
Referenced by output().
output() [6/6]
void oomph::HermiteBeamElement::output (std::ostream & outfile, const unsigned & n_plot) [virtual]
Output function with specified number of plot points.
Output function.
Reimplemented from oomph::FiniteElement.
Definition at line 825 of file beam_elements.cc.
References i, oomph::SolidFiniteElement::interpolated_xi(), oomph::GeomObject::ndim(), oomph::GeomObject::nlagrangian(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::raw_dnodal_position_gen_dt(), oomph::SolidFiniteElement::raw_lagrangian_position_gen(), s, oomph::QHermiteElement< DIM >::shape(), and oomph::KirchhoffLoveBeamEquations::Undeformed_beam_pt.
The documentation for this class was generated from the following files:
beam_elements.h
beam_elements.cc