oomph::AxisymmetricLinearElasticityEquationsBase Class Reference
A base class for elements that solve the axisymmetric (in cylindrical polars) equations of linear elasticity.
#include <axisym_linear_elasticity_elements.h>
Public Types
typedef void(* BodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &b)
Function pointer to function that specifies the body force as a function of the Cartesian coordinates and time FCT(x,b) -- x and b are Vectors!
Public Member Functions
virtual unsigned u_index_axisymmetric_linear_elasticity (const unsigned &i) const
Return the index at which the i-th (i=0: r, i=1: z; i=2: theta) unknown displacement component is stored at the nodes. The default assignment here (u_r, u_z, u_theta) is appropriate for single-physics problems.
double d2u_dt2_axisymmetric_linear_elasticity (const unsigned &n, const unsigned &i) const
d^2u/dt^2 at local node n
double du_dt_axisymmetric_linear_elasticity (const unsigned &n, const unsigned &i) const
du/dt at local node n
void interpolated_u_axisymmetric_linear_elasticity (const Vector< double > &s, Vector< double > &disp) const
Compute vector of FE interpolated displacement u at local coordinate s.
double interpolated_u_axisymmetric_linear_elasticity (const Vector< double > &s, const unsigned &i) const
Return FE interpolated displacement u[i] (i=0: r, i=1: z; i=2: theta) at local coordinate s.
void interpolated_du_dt_axisymmetric_linear_elasticity (const Vector< double > &s, Vector< double > &du_dt) const
Compute vector of FE interpolated velocity du/dt at local coordinate s.
void interpolated_d2u_dt2_axisymmetric_linear_elasticity (const Vector< double > &s, Vector< double > &d2u_dt2) const
Compute vector of FE interpolated accel d2u/dt2 at local coordinate s.
AxisymmetricLinearElasticityEquationsBase ()
Constructor: Set null pointers for constitutive law. Set physical parameter values to default values, and set body force to zero.
double *& youngs_modulus_pt ()
Return the pointer to Young's modulus.
double youngs_modulus () const
Access function to Young's modulus.
double & nu () const
Access function for Poisson's ratio.
double *& nu_pt ()
Access function for pointer to Poisson's ratio.
double *& lambda_sq_pt ()
Access function for pointer to timescale ratio (nondim density)
const double & lambda_sq () const
Access function for timescale ratio (nondim density)
BodyForceFctPt & body_force_fct_pt ()
Access function: Pointer to body force function.
BodyForceFctPt body_force_fct_pt () const
Access function: Pointer to body force function (const version)
void body_force (const double &time, const Vector< double > &x, Vector< double > &b) const
Evaluate body force at Eulerian coordinate x at present time (returns zero vector if no body force function pointer has been set)
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into: for now lump them all into one DOF type. Can be adjusted later.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Protected Attributes
double * Youngs_modulus_pt
Pointer to the Young's modulus.
double * Nu_pt
Pointer to Poisson's ratio.
double * Lambda_sq_pt
Timescale ratio (non-dim. density)
BodyForceFctPt Body_force_fct_pt
Pointer to body force function.
Static Protected Attributes
static double Default_youngs_modulus_value
Static default value for Young's modulus (1.0 -- for natural scaling, i.e. all stresses have been non-dimensionalised by the same reference Young's modulus. Setting the `non-dimensional` Young's modulus (obtained by de-referencing Youngs_modulus_pt) to a number larger than one means that the material is stiffer than assumed in the non-dimensionalisation.
static double Default_lambda_sq_value
Static default value for timescale ratio (1.0 for natural scaling)
Additional Inherited Members
Detailed Description
A base class for elements that solve the axisymmetric (in cylindrical polars) equations of linear elasticity.
Definition at line 53 of file axisym_linear_elasticity_elements.h.
Member Typedef Documentation
BodyForceFctPt
typedef void(* oomph::AxisymmetricLinearElasticityEquationsBase::BodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &b)
Function pointer to function that specifies the body force as a function of the Cartesian coordinates and time FCT(x,b) -- x and b are Vectors!
Definition at line 250 of file axisym_linear_elasticity_elements.h.
Constructor & Destructor Documentation
AxisymmetricLinearElasticityEquationsBase()
oomph::AxisymmetricLinearElasticityEquationsBase::AxisymmetricLinearElasticityEquationsBase () [inline]
Constructor: Set null pointers for constitutive law. Set physical parameter values to default values, and set body force to zero.
Definition at line 257 of file axisym_linear_elasticity_elements.h.
Member Function Documentation
body_force()
void oomph::AxisymmetricLinearElasticityEquationsBase::body_force (const double & time, const Vector< double > & x, Vector< double > & b) const [inline]
Evaluate body force at Eulerian coordinate x at present time (returns zero vector if no body force function pointer has been set)
Definition at line 325 of file axisym_linear_elasticity_elements.h.
References Body_force_fct_pt, oomph::FiniteElement::dim(), and i.
Referenced by oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity().
body_force_fct_pt() [1/2]
BodyForceFctPt & oomph::AxisymmetricLinearElasticityEquationsBase::body_force_fct_pt () [inline]
Access function: Pointer to body force function.
Definition at line 312 of file axisym_linear_elasticity_elements.h.
References Body_force_fct_pt.
body_force_fct_pt() [2/2]
BodyForceFctPt oomph::AxisymmetricLinearElasticityEquationsBase::body_force_fct_pt () const [inline]
Access function: Pointer to body force function (const version)
Definition at line 318 of file axisym_linear_elasticity_elements.h.
References Body_force_fct_pt.
d2u_dt2_axisymmetric_linear_elasticity()
double oomph::AxisymmetricLinearElasticityEquationsBase::d2u_dt2_axisymmetric_linear_elasticity (const unsigned & n, const unsigned & i) const [inline]
d^2u/dt^2 at local node n
Definition at line 67 of file axisym_linear_elasticity_elements.h.
References i, oomph::TimeStepper::is_steady(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), u_index_axisymmetric_linear_elasticity(), and oomph::TimeStepper::weight().
Referenced by oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), and interpolated_d2u_dt2_axisymmetric_linear_elasticity().
du_dt_axisymmetric_linear_elasticity()
double oomph::AxisymmetricLinearElasticityEquationsBase::du_dt_axisymmetric_linear_elasticity (const unsigned & n, const unsigned & i) const [inline]
du/dt at local node n
Definition at line 100 of file axisym_linear_elasticity_elements.h.
References i, oomph::TimeStepper::is_steady(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), u_index_axisymmetric_linear_elasticity(), and oomph::TimeStepper::weight().
Referenced by interpolated_du_dt_axisymmetric_linear_elasticity().
get_dof_numbers_for_unknowns()
void oomph::AxisymmetricLinearElasticityEquationsBase::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [inline], [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Reimplemented from oomph::GeneralisedElement.
Definition at line 359 of file axisym_linear_elasticity_elements.h.
References oomph::GeneralisedElement::eqn_number(), i, oomph::FiniteElement::nnode(), and oomph::FiniteElement::nodal_local_eqn().
interpolated_d2u_dt2_axisymmetric_linear_elasticity()
void oomph::AxisymmetricLinearElasticityEquationsBase::interpolated_d2u_dt2_axisymmetric_linear_elasticity (const Vector< double > & s, Vector< double > & d2u_dt2) const [inline]
Compute vector of FE interpolated accel d2u/dt2 at local coordinate s.
Definition at line 221 of file axisym_linear_elasticity_elements.h.
References d2u_dt2_axisymmetric_linear_elasticity(), i, oomph::FiniteElement::nnode(), s, and oomph::FiniteElement::shape().
Referenced by oomph::AxisymmetricLinearElasticityEquations::output().
interpolated_du_dt_axisymmetric_linear_elasticity()
void oomph::AxisymmetricLinearElasticityEquationsBase::interpolated_du_dt_axisymmetric_linear_elasticity (const Vector< double > & s, Vector< double > & du_dt) const [inline]
Compute vector of FE interpolated velocity du/dt at local coordinate s.
Definition at line 194 of file axisym_linear_elasticity_elements.h.
References du_dt_axisymmetric_linear_elasticity(), i, oomph::FiniteElement::nnode(), s, and oomph::FiniteElement::shape().
Referenced by oomph::AxisymmetricLinearElasticityEquations::output().
interpolated_u_axisymmetric_linear_elasticity() [1/2]
double oomph::AxisymmetricLinearElasticityEquationsBase::interpolated_u_axisymmetric_linear_elasticity (const Vector< double > & s, const unsigned & i) const [inline]
Return FE interpolated displacement u[i] (i=0: r, i=1: z; i=2: theta) at local coordinate s.
Definition at line 163 of file axisym_linear_elasticity_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and u_index_axisymmetric_linear_elasticity().
interpolated_u_axisymmetric_linear_elasticity() [2/2]
void oomph::AxisymmetricLinearElasticityEquationsBase::interpolated_u_axisymmetric_linear_elasticity (const Vector< double > & s, Vector< double > & disp) const [inline]
Compute vector of FE interpolated displacement u at local coordinate s.
Definition at line 131 of file axisym_linear_elasticity_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and u_index_axisymmetric_linear_elasticity().
Referenced by oomph::AxisymmetricLinearElasticityEquations::compute_error(), and oomph::AxisymmetricLinearElasticityEquations::output().
lambda_sq()
const double & oomph::AxisymmetricLinearElasticityEquationsBase::lambda_sq () const [inline]
Access function for timescale ratio (nondim density)
Definition at line 306 of file axisym_linear_elasticity_elements.h.
References Lambda_sq_pt.
Referenced by oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity().
lambda_sq_pt()
double *& oomph::AxisymmetricLinearElasticityEquationsBase::lambda_sq_pt () [inline]
Access function for pointer to timescale ratio (nondim density)
Definition at line 300 of file axisym_linear_elasticity_elements.h.
References Lambda_sq_pt.
ndof_types()
unsigned oomph::AxisymmetricLinearElasticityEquationsBase::ndof_types () const [inline], [virtual]
The number of `DOF types` that degrees of freedom in this element are sub-divided into: for now lump them all into one DOF type. Can be adjusted later.
Reimplemented from oomph::GeneralisedElement.
Definition at line 348 of file axisym_linear_elasticity_elements.h.
nu()
double & oomph::AxisymmetricLinearElasticityEquationsBase::nu () const [inline]
Access function for Poisson's ratio.
Definition at line 278 of file axisym_linear_elasticity_elements.h.
References Nu_pt.
Referenced by oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity().
nu_pt()
double *& oomph::AxisymmetricLinearElasticityEquationsBase::nu_pt () [inline]
Access function for pointer to Poisson's ratio.
Definition at line 294 of file axisym_linear_elasticity_elements.h.
References Nu_pt.
u_index_axisymmetric_linear_elasticity()
virtual unsigned oomph::AxisymmetricLinearElasticityEquationsBase::u_index_axisymmetric_linear_elasticity (const unsigned & i) const [inline], [virtual]
Return the index at which the i-th (i=0: r, i=1: z; i=2: theta) unknown displacement component is stored at the nodes. The default assignment here (u_r, u_z, u_theta) is appropriate for single-physics problems.
Definition at line 60 of file axisym_linear_elasticity_elements.h.
References i.
Referenced by d2u_dt2_axisymmetric_linear_elasticity(), du_dt_axisymmetric_linear_elasticity(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::AxisymmetricLinearElasticityEquations::get_strain(), and interpolated_u_axisymmetric_linear_elasticity().
youngs_modulus()
double oomph::AxisymmetricLinearElasticityEquationsBase::youngs_modulus () const [inline]
Access function to Young's modulus.
Definition at line 272 of file axisym_linear_elasticity_elements.h.
References Youngs_modulus_pt.
Referenced by oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity().
youngs_modulus_pt()
double *& oomph::AxisymmetricLinearElasticityEquationsBase::youngs_modulus_pt () [inline]
Return the pointer to Young's modulus.
Definition at line 266 of file axisym_linear_elasticity_elements.h.
References Youngs_modulus_pt.
Member Data Documentation
Body_force_fct_pt
BodyForceFctPt oomph::AxisymmetricLinearElasticityEquationsBase::Body_force_fct_pt [protected]
Pointer to body force function.
Definition at line 408 of file axisym_linear_elasticity_elements.h.
Referenced by body_force(), and body_force_fct_pt().
Default_lambda_sq_value
double oomph::AxisymmetricLinearElasticityEquationsBase::Default_lambda_sq_value [static], [protected]
Initial value:
=
    1.0
Static default value for timescale ratio (1.0 for natural scaling)
Static default value for timescale ratio (1.0 -- for natural scaling)
Definition at line 419 of file axisym_linear_elasticity_elements.h.
Default_youngs_modulus_value
double oomph::AxisymmetricLinearElasticityEquationsBase::Default_youngs_modulus_value [static], [protected]
Initial value:
=
      1.0
Static default value for Young's modulus (1.0 -- for natural scaling, i.e. all stresses have been non-dimensionalised by the same reference Young's modulus. Setting the `non-dimensional` Young's modulus (obtained by de-referencing Youngs_modulus_pt) to a number larger than one means that the material is stiffer than assumed in the non-dimensionalisation.
Definition at line 416 of file axisym_linear_elasticity_elements.h.
Lambda_sq_pt
double* oomph::AxisymmetricLinearElasticityEquationsBase::Lambda_sq_pt [protected]
Timescale ratio (non-dim. density)
Definition at line 405 of file axisym_linear_elasticity_elements.h.
Referenced by lambda_sq(), and lambda_sq_pt().
Nu_pt
double* oomph::AxisymmetricLinearElasticityEquationsBase::Nu_pt [protected]
Pointer to Poisson's ratio.
Definition at line 402 of file axisym_linear_elasticity_elements.h.
Referenced by nu(), and nu_pt().
Youngs_modulus_pt
double* oomph::AxisymmetricLinearElasticityEquationsBase::Youngs_modulus_pt [protected]
Pointer to the Young's modulus.
Definition at line 399 of file axisym_linear_elasticity_elements.h.
Referenced by youngs_modulus(), and youngs_modulus_pt().
The documentation for this class was generated from the following files:
axisym_linear_elasticity_elements.h
axisym_linear_elasticity_elements.cc