oomph::StorableShapeElement< ELEMENT > Class Template Reference
#include <stored_shape_function_elements.h>
Public Member Functions
StorableShapeElement ()
Constructor, set most storage pointers to zero.
virtual ~StorableShapeElement ()
Empty virtual destructor.
StorableShapeElement (const StorableShapeElement &)
Broken copy constructor.
void operator= (const StorableShapeElement &)
Broken assignment operator.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::StorableShapeElement< ELEMENT >
Templated wrapper that attaches the ability to store the shape functions and their derivatives w.r.t. to the local and global (Eulerian) coordinates at the integration points to the element specified by the template parameter.
Definition at line 565 of file stored_shape_function_elements.h.
Constructor & Destructor Documentation
StorableShapeElement() [1/2]
template<class ELEMENT >
oomph::StorableShapeElement< ELEMENT >::StorableShapeElement () [inline]
Constructor, set most storage pointers to zero.
Definition at line 571 of file stored_shape_function_elements.h.
References oomph::FiniteElement::integral_pt(), and oomph::StorableShapeElementBase::set_integration_scheme().
 StorableShapeElement()
template<class ELEMENT >
virtual oomph::StorableShapeElement< ELEMENT >::~StorableShapeElement () [inline], [virtual]
Empty virtual destructor.
Definition at line 580 of file stored_shape_function_elements.h.
StorableShapeElement() [2/2]
template<class ELEMENT >
oomph::StorableShapeElement< ELEMENT >::StorableShapeElement (const StorableShapeElement< ELEMENT > &) [inline]
Broken copy constructor.
Definition at line 583 of file stored_shape_function_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
operator=()
template<class ELEMENT >
void oomph::StorableShapeElement< ELEMENT >::operator= (const StorableShapeElement< ELEMENT > &) [inline]
Broken assignment operator.
Definition at line 589 of file stored_shape_function_elements.h.
References oomph::BrokenCopy::broken_assign().
The documentation for this class was generated from the following file:
stored_shape_function_elements.h