oomph::MacroElementNodeUpdateCollapsibleChannelMesh< ELEMENT > Class Template Reference
#include <collapsible_channel_mesh.template.h>
Public Member Functions
MacroElementNodeUpdateCollapsibleChannelMesh (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly, GeomObject *wall_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass numbers of elements and dimensions of the various parts of the collapsible channel, pointer to geometric object that represents the wall and pointer to timestepper (defaults to Steady).
virtual ~MacroElementNodeUpdateCollapsibleChannelMesh ()
Destructor: empty.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::MacroElementNodeUpdateCollapsibleChannelMesh< ELEMENT >
Collapsible channel mesh with MacroElement-based node update. The collapsible segment is represented by the specified geometric object. Some or all of the geometric Data in that geometric object may contain unknowns in the global Problem. The dependency on these unknowns is taken into account when setting up the Jacobian matrix of the elements. For this purpose, the element (whose type is specified by the template parameter) must inherit from MacroElementNodeUpdateElementBase.
Definition at line 238 of file collapsible_channel_mesh.template.h.
Constructor & Destructor Documentation
MacroElementNodeUpdateCollapsibleChannelMesh()
template<class ELEMENT >
oomph::MacroElementNodeUpdateCollapsibleChannelMesh< ELEMENT >::MacroElementNodeUpdateCollapsibleChannelMesh (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly, GeomObject * wall_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass numbers of elements and dimensions of the various parts of the collapsible channel, pointer to geometric object that represents the wall and pointer to timestepper (defaults to Steady).
Definition at line 247 of file collapsible_channel_mesh.template.h.
References oomph::CollapsibleChannelMesh< ELEMENT >::domain_pt(), oomph::Mesh::element_pt(), i, oomph::MacroElementNodeUpdateMesh::macro_domain_pt(), oomph::Mesh::nelement(), oomph::MacroElementNodeUpdateMesh::set_geom_object_vector_pt(), oomph::Global_string_for_annotation::string(), and oomph::CollapsibleChannelMesh< ELEMENT >::Wall_pt.
 MacroElementNodeUpdateCollapsibleChannelMesh()
template<class ELEMENT >
virtual oomph::MacroElementNodeUpdateCollapsibleChannelMesh< ELEMENT >::~MacroElementNodeUpdateCollapsibleChannelMesh () [inline], [virtual]
Destructor: empty.
Definition at line 344 of file collapsible_channel_mesh.template.h.
The documentation for this class was generated from the following file:
collapsible_channel_mesh.template.h