oomph::C1CurvedElementBase< NNODE_1D > Class Template Reference
#include <Subparametric_Telements.h>
Public Member Functions
C1CurvedElementBase ()
Constructor: Call constructors for FiniteElement.
virtual void get_value_transform_matrix (DenseMatrix< double > &D, DenseMatrix< double > &B, DenseMatrix< double > &node_position, unsigned &bd_element, DenseMatrix< double > &bd_node_position, Vector< double > &x) const
virtual void classify_boundary_node (DenseMatrix< double > &node_position, unsigned &bd_element, DenseMatrix< double > &bd_node_position, Vector< double > &x) const
virtual void basis_straight (const Vector< double > &s, Shape &psi) const
virtual void dbasis_local_straight (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void d2basis_local_straight (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void shape_geom (const Vector< double > &s, Shape &psi, Shape &phi) const
virtual void dshape_local_geom (const Vector< double > &s, Shape &psi, DShape &dpsids, Shape &phi, DShape &dphids) const
virtual void d2shape_local_geom (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids, Shape &phi, DShape &dphids, DShape &d2phids) const
virtual void basis_curve (const Vector< double > &s, Shape &psi) const
virtual void dbasis_local_curve (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void d2basis_local_curve (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void basis_c0 (const Vector< double > &s, Shape &psi) const
virtual void dbasis_c0_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void d2basis_c0_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void test (const Vector< double > &s, Shape &phi) const
virtual void dtest_local (const Vector< double > &s, Shape &phi, DShape &dphids) const
virtual void d2test_local (const Vector< double > &s, Shape &phi, DShape &dphids, DShape &d2phids) const
void basis_at_knot_straight (const unsigned &ipt, Shape &psi) const
Return the c1-shape function associated with a straight-sided boundary stored at the ipt-th integration point.
void dbasis_local_at_knot_straight (const unsigned &ipt, Shape &psi, DShape &dpsids) const
Return the c1-shape function associated with a straight-sided boundary and its derivatives w.r.t. the global coordinates at the ipt-th integration point.
void d2basis_local_at_knot_straight (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
void basis_at_knot_curve (const unsigned &ipt, Shape &psi) const
Return the c1-shape function associated with a curvilinear boundary stored at the ipt-th integration point.
void dbasis_local_at_knot_curve (const unsigned &ipt, Shape &psi, DShape &dpsids) const
void d2basis_local_at_knot_curve (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
void basis_c0_at_knot (const unsigned &ipt, Shape &psi) const
Return the c0-shape function stored at the ipt-th integration point.
void dbasis_c0_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
Return the c0-shape function and its derivatives w.r.t. the local coordinates at the ipt-th integration point.
void d2basis_c0_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
void shape_at_knot_geom (const unsigned &ipt, Shape &psi, Shape &phi) const
Return the geometric shape function stored at the ipt-th integration point.
void dshape_local_at_knot_geom (const unsigned &ipt, Shape &psi, DShape &dpsids, Shape &phi, DShape &dphids) const
Return the geometric shape function and its derivatives w.r.t. the local coordinates at the ipt-th integration point.
void d2shape_local_at_knot_geom (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids, Shape &phi, DShape &dphids, DShape &d2phids) const
void test_at_knot (const unsigned &ipt, Shape &phi) const
Return the test function stored at the ipt-th integration point.
void dtest_local_at_knot (const unsigned &ipt, Shape &phi, DShape &dphids) const
Return the test function and its derivatives w.r.t. the local coordinates at the ipt-th integration point.
void d2test_local_at_knot (const unsigned &ipt, Shape &phi, DShape &dphids, DShape &d2phids) const
double dshape_and_dtest_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, Shape &test, DShape &dtest) const
double d2shape_and_d2test_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DShape &d2psi, Shape &test, DShape &dtest, DShape &d2test) const
Compute the c1-shape functions that associated with the straight- boundary element and also first and second derivatives w.r.t. global coordinates at ipt-th integration point Returns Jacobian of mapping from global to local coordinates.
double local_to_eulerian_mapping2 (const DShape &dpsids, DShape &dphids, DenseMatrix< double > &inverse_jacobian) const
Calculate the mapping from local to Eulerian coordinates, given the derivatives of the shape functions w.r.t. local coordinates, Return only the determinant of the jacobian and the inverse of the mapping (ds/dx).
virtual double local_to_eulerian_mapping2 (const DShape &dpsids, DShape &dphids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void myassemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void my_interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
double J_eulerian1 (const Vector< double > &s) const
Calculate the Jacobian of the mapping between local and global coordinates at the position s.
unsigned is_boundary_element () const
double dbasis_c0_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsi) const
Compute the c0-shape functions and also first derivatives w.r.t. global coordinates at local coordinate s; Returns Jacobian of mapping from global to local coordinates. Most general form of the function, but may be over-loaded, if desired.
double d2basis_c0_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsi, DShape &d2psi) const
Compute the c0-shape functions and also the first and the second derivatives w.r.t.global coordinates at local coordinate s; Returns Jacobian of mapping from global to local coordinates. Most general form of the function, but may be over-loaded, if desired.
double dbasis_eulerian_curve (const Vector< double > &s, Shape &psi, DShape &dpsi) const
Compute the curved-element shape functions and also first derivatives w.r.t. global coordinates at local coordinate s; Returns Jacobian of mapping from global to local coordinates. Most general form of the function, but may be over-loaded, if desired.
double d2basis_eulerian_curve (const Vector< double > &s, Shape &psi, DShape &dpsi, DShape &d2psi) const
Compute the cuved-element shape functions and also first and second derivatives w.r.t. global coordinates at ipt-th integration point.
void get_nodal_value_curve1 (Vector< double > &u_value, DenseMatrix< double > &M)
Return raw nodal value for nodes specified on the reference triangle.
void get_nodal_eqn_curve (DenseMatrix< int > &nodal_eqn)
void my_interpolated_u_normal1 (const Vector< double > s, Vector< double > &interpolated_u, DenseMatrix< double > &interpolated_dudxi, DenseMatrix< double > &interpolated_d2udxi, DenseMatrix< double > &M)
void my_interpolated_u_normal (const Vector< double > s, Vector< double > &interpolated_u, DenseMatrix< double > &interpolated_dudxi, DenseMatrix< double > &interpolated_d2udxi) const
void my_interpolated_u_tangential (const Vector< double > s, Vector< double > &interpolated_u, DenseMatrix< double > &interpolated_dudxi) const
Return FE interpolated value u[] at local coordinate s as Vector.
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::C1CurvedElementBase< NNODE_1D >
Empty base class for C1Curvedelements (created so that we can use dynamic_cast<>() to figure out if a an element is a C1Curvedelement). This element is sup-parametric Note that this type of element carries three kinds of shape functions shape_straight : denotes C1-shape functions for straight-edged triangle shape_curve : denotes C1-shape functions for curve-edged triangle shape_geom : denotes C0-shape functions for geometry
Definition at line 5857 of file Subparametric_Telements.h.
Constructor & Destructor Documentation
C1CurvedElementBase()
template<unsigned NNODE_1D>
oomph::C1CurvedElementBase< NNODE_1D >::C1CurvedElementBase () [inline]
Constructor: Call constructors for FiniteElement.
Definition at line 5861 of file Subparametric_Telements.h.
Member Function Documentation
basis_at_knot_curve()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::basis_at_knot_curve (const unsigned & ipt, Shape & psi) const [inline]
Return the c1-shape function associated with a curvilinear boundary stored at the ipt-th integration point.
Definition at line 6039 of file Subparametric_Telements.h.
References oomph::C1CurvedElementBase< NNODE_1D >::basis_curve(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
basis_at_knot_straight()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::basis_at_knot_straight (const unsigned & ipt, Shape & psi) const [inline]
Return the c1-shape function associated with a straight-sided boundary stored at the ipt-th integration point.
Definition at line 5974 of file Subparametric_Telements.h.
References oomph::C1CurvedElementBase< NNODE_1D >::basis_straight(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
basis_c0()
template<unsigned NNODE_1D>
virtual void oomph::C1CurvedElementBase< NNODE_1D >::basis_c0 (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Reimplemented in oomph::C1CurvedElement< 2, NNODE_1D >.
Definition at line 5936 of file Subparametric_Telements.h.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::basis_c0_at_knot().
basis_c0_at_knot()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::basis_c0_at_knot (const unsigned & ipt, Shape & psi) const [inline]
Return the c0-shape function stored at the ipt-th integration point.
Definition at line 6104 of file Subparametric_Telements.h.
References oomph::C1CurvedElementBase< NNODE_1D >::basis_c0(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
basis_curve()
template<unsigned NNODE_1D>
virtual void oomph::C1CurvedElementBase< NNODE_1D >::basis_curve (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Reimplemented in oomph::C1CurvedElement< 2, NNODE_1D >.
Definition at line 5920 of file Subparametric_Telements.h.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::basis_at_knot_curve().
basis_straight()
template<unsigned NNODE_1D>
virtual void oomph::C1CurvedElementBase< NNODE_1D >::basis_straight (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Reimplemented in oomph::C1CurvedElement< 2, NNODE_1D >.
Definition at line 5879 of file Subparametric_Telements.h.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::basis_at_knot_straight().
classify_boundary_node()
template<unsigned NNODE_1D>
virtual void oomph::C1CurvedElementBase< NNODE_1D >::classify_boundary_node (DenseMatrix< double > & node_position, unsigned & bd_element, DenseMatrix< double > & bd_node_position, Vector< double > & x) const [inline], [virtual]
Reimplemented in oomph::C1CurvedElement< 2, NNODE_1D >.
Definition at line 5872 of file Subparametric_Telements.h.
d2basis_c0_eulerian()
template<unsigned NNODE_1D>
double oomph::C1CurvedElementBase< NNODE_1D >::d2basis_c0_eulerian (const Vector< double > & s, Shape & psi, DShape & dpsi, DShape & d2psi) const [inline]
Compute the c0-shape functions and also the first and the second derivatives w.r.t.global coordinates at local coordinate s; Returns Jacobian of mapping from global to local coordinates. Most general form of the function, but may be over-loaded, if desired.
Definition at line 6631 of file Subparametric_Telements.h.
References oomph::C1CurvedElementBase< NNODE_1D >::d2basis_c0_local(), oomph::C1CurvedElementBase< NNODE_1D >::d2shape_local_geom(), oomph::FiniteElement::dim(), oomph::C1CurvedElementBase< NNODE_1D >::local_to_eulerian_mapping2(), oomph::C1CurvedElementBase< NNODE_1D >::myassemble_local_to_eulerian_jacobian2(), oomph::FiniteElement::N2deriv, s, and oomph::FiniteElement::transform_second_derivatives().
d2basis_c0_local()
template<unsigned NNODE_1D>
virtual void oomph::C1CurvedElementBase< NNODE_1D >::d2basis_c0_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline], [virtual]
Reimplemented in oomph::C1CurvedElement< 2, NNODE_1D >.
Definition at line 5945 of file Subparametric_Telements.h.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::d2basis_c0_eulerian(), and oomph::C1CurvedElementBase< NNODE_1D >::d2basis_c0_local_at_knot().
d2basis_c0_local_at_knot()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::d2basis_c0_local_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline]
Calculate the c0-shape function and its first and second derivatives w.r.t. local coordinates at the ipt-th integration point.
 Numbering:
Definition at line 6145 of file Subparametric_Telements.h.
References oomph::C1CurvedElementBase< NNODE_1D >::d2basis_c0_local(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
d2basis_eulerian_curve()
template<unsigned NNODE_1D>
double oomph::C1CurvedElementBase< NNODE_1D >::d2basis_eulerian_curve (const Vector< double > & s, Shape & psi, DShape & dpsi, DShape & d2psi) const [inline]
Compute the cuved-element shape functions and also first and second derivatives w.r.t. global coordinates at ipt-th integration point.
Definition at line 6711 of file Subparametric_Telements.h.
References oomph::C1CurvedElementBase< NNODE_1D >::d2basis_local_curve(), oomph::C1CurvedElementBase< NNODE_1D >::d2shape_local_geom(), oomph::FiniteElement::dim(), oomph::C1CurvedElementBase< NNODE_1D >::local_to_eulerian_mapping2(), oomph::C1CurvedElementBase< NNODE_1D >::myassemble_local_to_eulerian_jacobian2(), oomph::FiniteElement::N2deriv, s, and oomph::FiniteElement::transform_second_derivatives().
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::my_interpolated_u_normal(), and oomph::C1CurvedElementBase< NNODE_1D >::my_interpolated_u_normal1().
d2basis_local_at_knot_curve()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::d2basis_local_at_knot_curve (const unsigned & ipt, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline]
Calculate the c1-shape function associated with a curvilinear boundary and its first and second derivatives w.r.t. local coordinates at the ipt-th integration point.
 Numbering:
Definition at line 6082 of file Subparametric_Telements.h.
References oomph::C1CurvedElementBase< NNODE_1D >::d2basis_local_curve(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
d2basis_local_at_knot_straight()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::d2basis_local_at_knot_straight (const unsigned & ipt, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline]
Calculate the c1-shape function associated with a straight-sided boundary and its first and second derivatives w.r.t. global coordinates at the ipt-th integration point.
 Numbering:
Definition at line 6017 of file Subparametric_Telements.h.
References oomph::C1CurvedElementBase< NNODE_1D >::d2basis_local_straight(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::d2shape_and_d2test_eulerian_at_knot().
d2basis_local_curve()
template<unsigned NNODE_1D>
virtual void oomph::C1CurvedElementBase< NNODE_1D >::d2basis_local_curve (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline], [virtual]
Reimplemented in oomph::C1CurvedElement< 2, NNODE_1D >.
Definition at line 5929 of file Subparametric_Telements.h.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::d2basis_eulerian_curve(), and oomph::C1CurvedElementBase< NNODE_1D >::d2basis_local_at_knot_curve().
d2basis_local_straight()
template<unsigned NNODE_1D>
virtual void oomph::C1CurvedElementBase< NNODE_1D >::d2basis_local_straight (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline], [virtual]
Reimplemented in oomph::C1CurvedElement< 2, NNODE_1D >.
Definition at line 5888 of file Subparametric_Telements.h.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::d2basis_local_at_knot_straight(), oomph::C1CurvedElementBase< NNODE_1D >::my_interpolated_u_normal(), and oomph::C1CurvedElementBase< NNODE_1D >::my_interpolated_u_normal1().
d2shape_and_d2test_eulerian_at_knot()
template<unsigned NNODE_1D>
double oomph::C1CurvedElementBase< NNODE_1D >::d2shape_and_d2test_eulerian_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsi, DShape & d2psi, Shape & test, DShape & dtest, DShape & d2test) const [inline]
Compute the c1-shape functions that associated with the straight- boundary element and also first and second derivatives w.r.t. global coordinates at ipt-th integration point Returns Jacobian of mapping from global to local coordinates.
Definition at line 6346 of file Subparametric_Telements.h.
References oomph::C1CurvedElementBase< NNODE_1D >::d2basis_local_at_knot_straight(), oomph::C1CurvedElementBase< NNODE_1D >::d2shape_local_at_knot_geom(), oomph::C1CurvedElementBase< NNODE_1D >::d2test_local_at_knot(), oomph::FiniteElement::dim(), oomph::C1CurvedElementBase< NNODE_1D >::local_to_eulerian_mapping2(), and oomph::C1CurvedElementBase< NNODE_1D >::test().
d2shape_local_at_knot_geom()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::d2shape_local_at_knot_geom (const unsigned & ipt, Shape & psi, DShape & dpsids, DShape & d2psids, Shape & phi, DShape & dphids, DShape & d2phids) const [inline]
Calculate the geometric shape function and its first and second derivatives w.r.t. local coordinates at the ipt-th integration point.
 Numbering:
Definition at line 6211 of file Subparametric_Telements.h.
References oomph::C1CurvedElementBase< NNODE_1D >::d2shape_local_geom(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::d2shape_and_d2test_eulerian_at_knot().
d2shape_local_geom()
template<unsigned NNODE_1D>
virtual void oomph::C1CurvedElementBase< NNODE_1D >::d2shape_local_geom (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids, Shape & phi, DShape & dphids, DShape & d2phids) const [inline], [virtual]
Reimplemented in oomph::C1CurvedElement< 2, NNODE_1D >.
Definition at line 5910 of file Subparametric_Telements.h.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::d2basis_c0_eulerian(), oomph::C1CurvedElementBase< NNODE_1D >::d2basis_eulerian_curve(), oomph::C1CurvedElementBase< NNODE_1D >::d2shape_local_at_knot_geom(), oomph::C1CurvedElementBase< NNODE_1D >::dbasis_c0_eulerian(), and oomph::C1CurvedElementBase< NNODE_1D >::dbasis_eulerian_curve().
d2test_local()
template<unsigned NNODE_1D>
virtual void oomph::C1CurvedElementBase< NNODE_1D >::d2test_local (const Vector< double > & s, Shape & phi, DShape & dphids, DShape & d2phids) const [inline], [virtual]
Reimplemented in oomph::C1CurvedElement< 2, NNODE_1D >.
Definition at line 5962 of file Subparametric_Telements.h.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::d2test_local_at_knot().
d2test_local_at_knot()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::d2test_local_at_knot (const unsigned & ipt, Shape & phi, DShape & dphids, DShape & d2phids) const [inline]
Calculate the test function and its first and second derivatives w.r.t. local coordinates at the ipt-th integration point.
 Numbering:
Definition at line 6277 of file Subparametric_Telements.h.
References oomph::C1CurvedElementBase< NNODE_1D >::d2test_local(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::d2shape_and_d2test_eulerian_at_knot().
dbasis_c0_eulerian()
template<unsigned NNODE_1D>
double oomph::C1CurvedElementBase< NNODE_1D >::dbasis_c0_eulerian (const Vector< double > & s, Shape & psi, DShape & dpsi) const [inline]
Compute the c0-shape functions and also first derivatives w.r.t. global coordinates at local coordinate s; Returns Jacobian of mapping from global to local coordinates. Most general form of the function, but may be over-loaded, if desired.
Definition at line 6594 of file Subparametric_Telements.h.
References oomph::C1CurvedElementBase< NNODE_1D >::d2shape_local_geom(), oomph::C1CurvedElementBase< NNODE_1D >::dbasis_c0_local(), oomph::FiniteElement::dim(), oomph::C1CurvedElementBase< NNODE_1D >::local_to_eulerian_mapping2(), s, and oomph::FiniteElement::transform_derivatives().
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::my_interpolated_u_tangential().
dbasis_c0_local()
template<unsigned NNODE_1D>
virtual void oomph::C1CurvedElementBase< NNODE_1D >::dbasis_c0_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const [inline], [virtual]
Reimplemented in oomph::C1CurvedElement< 2, NNODE_1D >.
Definition at line 5939 of file Subparametric_Telements.h.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::dbasis_c0_eulerian(), and oomph::C1CurvedElementBase< NNODE_1D >::dbasis_c0_local_at_knot().
dbasis_c0_local_at_knot()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::dbasis_c0_local_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsids) const [inline]
Return the c0-shape function and its derivatives w.r.t. the local coordinates at the ipt-th integration point.
Definition at line 6123 of file Subparametric_Telements.h.
References oomph::C1CurvedElementBase< NNODE_1D >::dbasis_c0_local(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
dbasis_eulerian_curve()
template<unsigned NNODE_1D>
double oomph::C1CurvedElementBase< NNODE_1D >::dbasis_eulerian_curve (const Vector< double > & s, Shape & psi, DShape & dpsi) const [inline]
Compute the curved-element shape functions and also first derivatives w.r.t. global coordinates at local coordinate s; Returns Jacobian of mapping from global to local coordinates. Most general form of the function, but may be over-loaded, if desired.
Definition at line 6675 of file Subparametric_Telements.h.
References oomph::C1CurvedElementBase< NNODE_1D >::d2shape_local_geom(), oomph::C1CurvedElementBase< NNODE_1D >::dbasis_local_curve(), oomph::FiniteElement::dim(), oomph::C1CurvedElementBase< NNODE_1D >::local_to_eulerian_mapping2(), s, and oomph::FiniteElement::transform_derivatives().
dbasis_local_at_knot_curve()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::dbasis_local_at_knot_curve (const unsigned & ipt, Shape & psi, DShape & dpsids) const [inline]
Return the c1-shape function associated with a curvilinear boundary and its derivatives w.r.t. the local coordinates at the ipt-th integration point.
Definition at line 6059 of file Subparametric_Telements.h.
References oomph::C1CurvedElementBase< NNODE_1D >::dbasis_local_curve(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
dbasis_local_at_knot_straight()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::dbasis_local_at_knot_straight (const unsigned & ipt, Shape & psi, DShape & dpsids) const [inline]
Return the c1-shape function associated with a straight-sided boundary and its derivatives w.r.t. the global coordinates at the ipt-th integration point.
Definition at line 5994 of file Subparametric_Telements.h.
References oomph::C1CurvedElementBase< NNODE_1D >::dbasis_local_straight(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
dbasis_local_curve()
template<unsigned NNODE_1D>
virtual void oomph::C1CurvedElementBase< NNODE_1D >::dbasis_local_curve (const Vector< double > & s, Shape & psi, DShape & dpsids) const [inline], [virtual]
Reimplemented in oomph::C1CurvedElement< 2, NNODE_1D >.
Definition at line 5923 of file Subparametric_Telements.h.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::dbasis_eulerian_curve(), and oomph::C1CurvedElementBase< NNODE_1D >::dbasis_local_at_knot_curve().
dbasis_local_straight()
template<unsigned NNODE_1D>
virtual void oomph::C1CurvedElementBase< NNODE_1D >::dbasis_local_straight (const Vector< double > & s, Shape & psi, DShape & dpsids) const [inline], [virtual]
Reimplemented in oomph::C1CurvedElement< 2, NNODE_1D >.
Definition at line 5882 of file Subparametric_Telements.h.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::dbasis_local_at_knot_straight().
dshape_and_dtest_eulerian_at_knot()
template<unsigned NNODE_1D>
double oomph::C1CurvedElementBase< NNODE_1D >::dshape_and_dtest_eulerian_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsi, Shape & test, DShape & dtest) const [inline]
Calculate the shape function and its first and second derivatives w.r.t. local coordinates at the ipt-th integration point.
 Numbering:
Definition at line 6300 of file Subparametric_Telements.h.
References oomph::FiniteElement::dim(), oomph::FiniteElement::dshape_local_at_knot(), oomph::C1CurvedElementBase< NNODE_1D >::dshape_local_at_knot_geom(), oomph::C1CurvedElementBase< NNODE_1D >::dtest_local_at_knot(), oomph::C1CurvedElementBase< NNODE_1D >::local_to_eulerian_mapping2(), oomph::C1CurvedElementBase< NNODE_1D >::test(), and oomph::FiniteElement::transform_derivatives().
dshape_local_at_knot_geom()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::dshape_local_at_knot_geom (const unsigned & ipt, Shape & psi, DShape & dpsids, Shape & phi, DShape & dphids) const [inline]
Return the geometric shape function and its derivatives w.r.t. the local coordinates at the ipt-th integration point.
Definition at line 6186 of file Subparametric_Telements.h.
References oomph::FiniteElement::dim(), oomph::C1CurvedElementBase< NNODE_1D >::dshape_local_geom(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::dshape_and_dtest_eulerian_at_knot().
dshape_local_geom()
template<unsigned NNODE_1D>
virtual void oomph::C1CurvedElementBase< NNODE_1D >::dshape_local_geom (const Vector< double > & s, Shape & psi, DShape & dpsids, Shape & phi, DShape & dphids) const [inline], [virtual]
Reimplemented in oomph::C1CurvedElement< 2, NNODE_1D >.
Definition at line 5902 of file Subparametric_Telements.h.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::dshape_local_at_knot_geom(), and oomph::C1CurvedElementBase< NNODE_1D >::J_eulerian1().
dtest_local()
template<unsigned NNODE_1D>
virtual void oomph::C1CurvedElementBase< NNODE_1D >::dtest_local (const Vector< double > & s, Shape & phi, DShape & dphids) const [inline], [virtual]
Reimplemented in oomph::C1CurvedElement< 2, NNODE_1D >.
Definition at line 5956 of file Subparametric_Telements.h.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::dtest_local_at_knot().
dtest_local_at_knot()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::dtest_local_at_knot (const unsigned & ipt, Shape & phi, DShape & dphids) const [inline]
Return the test function and its derivatives w.r.t. the local coordinates at the ipt-th integration point.
Definition at line 6255 of file Subparametric_Telements.h.
References oomph::FiniteElement::dim(), oomph::C1CurvedElementBase< NNODE_1D >::dtest_local(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::dshape_and_dtest_eulerian_at_knot().
get_nodal_eqn_curve()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::get_nodal_eqn_curve (DenseMatrix< int > & nodal_eqn) [inline]
Return raw nodal equations for nodes specified on the curved triangle This function will be employed for the post-permutation as the nodal values defined on the element doesn't match with the defined shape functions
Definition at line 6826 of file Subparametric_Telements.h.
References oomph::OcTreeNames::B, oomph::OcTreeNames::D, oomph::C1CurvedElementBase< NNODE_1D >::get_value_transform_matrix(), i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), and oomph::FiniteElement::position().
get_nodal_value_curve1()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::get_nodal_value_curve1 (Vector< double > & u_value, DenseMatrix< double > & M) [inline]
Return raw nodal value for nodes specified on the reference triangle.
Definition at line 6752 of file Subparametric_Telements.h.
References oomph::OcTreeNames::B, oomph::OcTreeNames::D, oomph::C1CurvedElementBase< NNODE_1D >::get_value_transform_matrix(), i, oomph::FiniteElement::position(), oomph::FiniteElement::raw_nodal_value(), and value.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::my_interpolated_u_normal1().
get_value_transform_matrix()
template<unsigned NNODE_1D>
virtual void oomph::C1CurvedElementBase< NNODE_1D >::get_value_transform_matrix (DenseMatrix< double > & D, DenseMatrix< double > & B, DenseMatrix< double > & node_position, unsigned & bd_element, DenseMatrix< double > & bd_node_position, Vector< double > & x) const [inline], [virtual]
Reimplemented in oomph::C1CurvedElement< 2, NNODE_1D >.
Definition at line 5862 of file Subparametric_Telements.h.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::get_nodal_eqn_curve(), oomph::C1CurvedElementBase< NNODE_1D >::get_nodal_value_curve1(), and oomph::C1CurvedElementBase< NNODE_1D >::my_interpolated_u_normal().
is_boundary_element()
template<unsigned NNODE_1D>
unsigned oomph::C1CurvedElementBase< NNODE_1D >::is_boundary_element () const [inline]
Definition at line 6562 of file Subparametric_Telements.h.
References i, oomph::Node::is_on_boundary(), and oomph::FiniteElement::node_pt().
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::my_interpolated_u_normal(), and oomph::C1CurvedElementBase< NNODE_1D >::my_interpolated_u_normal1().
J_eulerian1()
template<unsigned NNODE_1D>
double oomph::C1CurvedElementBase< NNODE_1D >::J_eulerian1 (const Vector< double > & s) const [inline]
Calculate the Jacobian of the mapping between local and global coordinates at the position s.
Definition at line 6481 of file Subparametric_Telements.h.
References oomph::FiniteElement::check_jacobian(), oomph::FiniteElement::dim(), oomph::C1CurvedElementBase< NNODE_1D >::dshape_local_geom(), i, oomph::FiniteElement::nodal_dimension(), and oomph::oomph_info.
local_to_eulerian_mapping2() [1/2]
template<unsigned NNODE_1D>
double oomph::C1CurvedElementBase< NNODE_1D >::local_to_eulerian_mapping2 (const DShape & dpsids, DShape & dphids, DenseMatrix< double > & inverse_jacobian) const [inline]
Calculate the mapping from local to Eulerian coordinates, given the derivatives of the shape functions w.r.t. local coordinates, Return only the determinant of the jacobian and the inverse of the mapping (ds/dx).
Definition at line 6391 of file Subparametric_Telements.h.
References oomph::FiniteElement::dim().
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::d2basis_c0_eulerian(), oomph::C1CurvedElementBase< NNODE_1D >::d2basis_eulerian_curve(), oomph::C1CurvedElementBase< NNODE_1D >::d2shape_and_d2test_eulerian_at_knot(), oomph::C1CurvedElementBase< NNODE_1D >::dbasis_c0_eulerian(), oomph::C1CurvedElementBase< NNODE_1D >::dbasis_eulerian_curve(), and oomph::C1CurvedElementBase< NNODE_1D >::dshape_and_dtest_eulerian_at_knot().
local_to_eulerian_mapping2() [2/2]
template<unsigned NNODE_1D>
virtual double oomph::C1CurvedElementBase< NNODE_1D >::local_to_eulerian_mapping2 (const DShape & dpsids, DShape & dphids, DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const [inline], [virtual]
Definition at line 6406 of file Subparametric_Telements.h.
References oomph::FiniteElement::dim(), i, and oomph::FiniteElement::invert_jacobian_mapping().
my_interpolated_u_normal()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::my_interpolated_u_normal (const Vector< double > s, Vector< double > & interpolated_u, DenseMatrix< double > & interpolated_dudxi, DenseMatrix< double > & interpolated_d2udxi) const [inline]
Return FE interpolated value u[] at local coordinate s as Vector using Bell interpolations for the straight-edges triangle using C1-curved interpolations for the curve-edges triangle
Definition at line 6975 of file Subparametric_Telements.h.
References oomph::OcTreeNames::B, oomph::OcTreeNames::D, oomph::C1CurvedElementBase< NNODE_1D >::d2basis_eulerian_curve(), oomph::C1CurvedElementBase< NNODE_1D >::d2basis_local_straight(), oomph::C1CurvedElementBase< NNODE_1D >::get_value_transform_matrix(), i, interpolated_u(), oomph::C1CurvedElementBase< NNODE_1D >::is_boundary_element(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::position(), oomph::FiniteElement::raw_nodal_value(), s, and value.
my_interpolated_u_normal1()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::my_interpolated_u_normal1 (const Vector< double > s, Vector< double > & interpolated_u, DenseMatrix< double > & interpolated_dudxi, DenseMatrix< double > & interpolated_d2udxi, DenseMatrix< double > & M) [inline]
Return FE interpolated value u[] at local coordinate s as Vector using Bell interpolations for the straight-edges triangle using C1-curved interpolations for the curve-edges triangle
Definition at line 6899 of file Subparametric_Telements.h.
References oomph::C1CurvedElementBase< NNODE_1D >::d2basis_eulerian_curve(), oomph::C1CurvedElementBase< NNODE_1D >::d2basis_local_straight(), oomph::C1CurvedElementBase< NNODE_1D >::get_nodal_value_curve1(), i, interpolated_u(), oomph::C1CurvedElementBase< NNODE_1D >::is_boundary_element(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::raw_nodal_value(), and s.
my_interpolated_u_tangential()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::my_interpolated_u_tangential (const Vector< double > s, Vector< double > & interpolated_u, DenseMatrix< double > & interpolated_dudxi) const [inline]
Return FE interpolated value u[] at local coordinate s as Vector.
Definition at line 7168 of file Subparametric_Telements.h.
References oomph::C1CurvedElementBase< NNODE_1D >::dbasis_c0_eulerian(), interpolated_u(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::raw_nodal_value().
my_interpolated_x()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::my_interpolated_x (const Vector< double > & s, Vector< double > & x) const [inline]
Return FE interpolated position x[] at local coordinate s as Vector.
Definition at line 6463 of file Subparametric_Telements.h.
References s, and oomph::C1CurvedElementBase< NNODE_1D >::shape_geom().
myassemble_local_to_eulerian_jacobian2()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::myassemble_local_to_eulerian_jacobian2 (const DShape & d2psids, DenseMatrix< double > & jacobian2) const [inline]
Internal function that is used to assemble the jacobian of second derivatives of the the mapping from local coordinates (s) to the eulerian coordinates (x), given the second derivatives of the shape functions.
Definition at line 6437 of file Subparametric_Telements.h.
References oomph::FiniteElement::dim(), i, and oomph::FiniteElement::N2deriv.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::d2basis_c0_eulerian(), and oomph::C1CurvedElementBase< NNODE_1D >::d2basis_eulerian_curve().
shape_at_knot_geom()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::shape_at_knot_geom (const unsigned & ipt, Shape & psi, Shape & phi) const [inline]
Return the geometric shape function stored at the ipt-th integration point.
Definition at line 6167 of file Subparametric_Telements.h.
References oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), s, and oomph::C1CurvedElementBase< NNODE_1D >::shape_geom().
shape_geom()
template<unsigned NNODE_1D>
virtual void oomph::C1CurvedElementBase< NNODE_1D >::shape_geom (const Vector< double > & s, Shape & psi, Shape & phi) const [inline], [virtual]
Reimplemented in oomph::C1CurvedElement< 2, NNODE_1D >.
Definition at line 5895 of file Subparametric_Telements.h.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::my_interpolated_x(), and oomph::C1CurvedElementBase< NNODE_1D >::shape_at_knot_geom().
test()
template<unsigned NNODE_1D>
virtual void oomph::C1CurvedElementBase< NNODE_1D >::test (const Vector< double > & s, Shape & phi) const [inline], [virtual]
Reimplemented in oomph::C1CurvedElement< 2, NNODE_1D >.
Definition at line 5953 of file Subparametric_Telements.h.
Referenced by oomph::C1CurvedElementBase< NNODE_1D >::d2shape_and_d2test_eulerian_at_knot(), oomph::C1CurvedElementBase< NNODE_1D >::dshape_and_dtest_eulerian_at_knot(), and oomph::C1CurvedElementBase< NNODE_1D >::test_at_knot().
test_at_knot()
template<unsigned NNODE_1D>
void oomph::C1CurvedElementBase< NNODE_1D >::test_at_knot (const unsigned & ipt, Shape & phi) const [inline]
Return the test function stored at the ipt-th integration point.
Definition at line 6236 of file Subparametric_Telements.h.
References oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), s, and oomph::C1CurvedElementBase< NNODE_1D >::test().
The documentation for this class was generated from the following file:
Subparametric_Telements.h