oomph::TPVDElement< DIM, NNODE_1D > Class Template Reference
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
#include <solid_elements.h>
Public Member Functions
TPVDElement ()
Constructor, there are no internal data points.
void output (std::ostream &outfile)
Output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
void output (FILE *file_pt)
C-style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain tensor.
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the local dofs of the element. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::desribe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
Additional Inherited Members
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::TPVDElement< DIM, NNODE_1D >
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
An Element that solves the solid mechanics equations, based on the principle of virtual displacements in Cartesian coordinates, using SolidTElements for the interpolation of the variable positions.
Definition at line 1753 of file solid_elements.h.
Constructor & Destructor Documentation
TPVDElement()
template<unsigned DIM, unsigned NNODE_1D>
oomph::TPVDElement< DIM, NNODE_1D >::TPVDElement () [inline]
Constructor, there are no internal data points.
Definition at line 1759 of file solid_elements.h.
Member Function Documentation
describe_local_dofs()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::SolidFiniteElement::describe_local_dofs (std::ostream & out, const std::string & current_string) const [virtual]
Function to describe the local dofs of the element. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::desribe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
Reimplemented from oomph::FiniteElement.
Definition at line 3894 of file elements.cc.
References i, oomph::FiniteElement::local_coordinate_of_node(), oomph::FiniteElement::node_pt(), and s.
get_Z2_flux()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TPVDElement< DIM, NNODE_1D >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Upper triangular entries in strain tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 1824 of file solid_elements.h.
References oomph::PVDEquationsBase< DIM >::get_strain(), and i.
nrecovery_order()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::TPVDElement< DIM, NNODE_1D >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 1788 of file solid_elements.h.
num_Z2_flux_terms()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::TPVDElement< DIM, NNODE_1D >::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 1816 of file solid_elements.h.
nvertex_node()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::TPVDElement< DIM, NNODE_1D >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 1794 of file solid_elements.h.
output() [1/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TPVDElement< DIM, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function.
Reimplemented from oomph::PVDEquations< DIM >.
Definition at line 1775 of file solid_elements.h.
References oomph::PVDEquations< DIM >::output().
output() [2/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TPVDElement< DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function.
Reimplemented from oomph::PVDEquations< DIM >.
Definition at line 1781 of file solid_elements.h.
References oomph::PVDEquations< DIM >::output().
output() [3/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TPVDElement< DIM, NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function.
Reimplemented from oomph::PVDEquations< DIM >.
Definition at line 1762 of file solid_elements.h.
References oomph::PVDEquations< DIM >::output().
output() [4/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TPVDElement< DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function.
Reimplemented from oomph::PVDEquations< DIM >.
Definition at line 1768 of file solid_elements.h.
References oomph::PVDEquations< DIM >::output().
vertex_node_pt()
template<unsigned DIM, unsigned NNODE_1D>
Node * oomph::TPVDElement< DIM, NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 1800 of file solid_elements.h.
The documentation for this class was generated from the following file:
solid_elements.h