oomph::SolidQHermiteElement< DIM > Class Template Reference
////////////////////////////////////////////////////////////////////
#include <hermite_elements.h>
Public Member Functions
SolidQHermiteElement ()
Constructor.
SolidQHermiteElement (const SolidQHermiteElement &dummy)=delete
Broken copy constructor.
void operator= (const SolidQHermiteElement &)=delete
Broken assignment operator.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at n_plot points.
void output (FILE *file_pt)
C-style output.
void output (FILE *file_pt, const unsigned &n_plot)
C_style output at n_plot points.
void build_face_element (const int &face_index, FaceElement *face_element_pt)
Build the lower-dimensional FaceElement of the type SolidQHermiteElement<DIM-1>. The face index takes a value that correponds to the possible faces:
void output (std::ostream &outfile, const unsigned &n_plot)
The output function for n_plot points in each coordinate direction for the 1D element.
void output (FILE *file_pt, const unsigned &n_plot)
The C-style output function for n_plot points in each coordinate direction for the 1D element.
void output (std::ostream &outfile, const unsigned &n_p)
The output function for any number of points per element.
void output (FILE *file_pt, const unsigned &n_plot)
The C-style output function for any number of points per element.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::SolidQHermiteElement< DIM >
////////////////////////////////////////////////////////////////////
SolidQHermiteElement elements are Hermite elements whose Jacobian matrices include derivatives w.r.t. the Eulerian positions of their nodes. They are the basis for elasticity elements. No assumptions are made about alignment of local and global coordinates.
Definition at line 502 of file hermite_elements.h.
Constructor & Destructor Documentation
SolidQHermiteElement() [1/2]
template<unsigned DIM>
oomph::SolidQHermiteElement< DIM >::SolidQHermiteElement () [inline]
Constructor.
Definition at line 507 of file hermite_elements.h.
References oomph::FiniteElement::nnode(), oomph::SolidFiniteElement::set_lagrangian_dimension(), and oomph::SolidFiniteElement::set_nnodal_lagrangian_type().
SolidQHermiteElement() [2/2]
template<unsigned DIM>
oomph::SolidQHermiteElement< DIM >::SolidQHermiteElement (const SolidQHermiteElement< DIM > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
build_face_element()
template<unsigned DIM>
void oomph::SolidQHermiteElement< DIM >::build_face_element (const int & face_index, FaceElement * face_element_pt) [virtual]
Build the lower-dimensional FaceElement of the type SolidQHermiteElement<DIM-1>. The face index takes a value that correponds to the possible faces:
Function to setup geometrical information for lower-dimensional FaceElements for the solid hermite elements. We need to construct the basic element and then sort out the Lagrangian coordinates.
In 1D: -1 (Left) s[0] = -1.0 +1 (Right) s[0] = 1.0
In 2D: -1 (West) s[0] = -1.0 +1 (East) s[0] = 1.0 -2 (South) s[1] = -1.0 +2 (North) s[1] = 1.0
In 3D: -1 (Left) s[0] = -1.0 +1 (Right) s[0] = 1.0 -2 (Down) s[1] = -1.0 +2 (Up) s[1] = 1.0 -3 (Back) s[2] = -1.0 +3 (Front) s[2] = 1.0
Reimplemented from oomph::QHermiteElement< DIM >.
Definition at line 1270 of file hermite_elements.cc.
References oomph::SolidNode::nlagrangian().
operator=()
template<unsigned DIM>
void oomph::SolidQHermiteElement< DIM >::operator= (const SolidQHermiteElement< DIM > &) [delete]
Broken assignment operator.
output() [1/8]
template<unsigned DIM>
void oomph::SolidQHermiteElement< DIM >::output (FILE * file_pt) [virtual]
C-style output.
Overload the C-style output function.
Reimplemented from oomph::QHermiteElement< DIM >.
Reimplemented in oomph::HermitePVDElement< DIM >.
Definition at line 1123 of file hermite_elements.cc.
References oomph::CommandLineArgs::output().
output() [2/8]
void oomph::SolidQHermiteElement< 1 >::output (FILE * file_pt, const unsigned & n_plot) [virtual]
The C-style output function for n_plot points in each coordinate direction for the 1D element.
Reimplemented from oomph::QHermiteElement< DIM >.
Definition at line 1134 of file hermite_elements.cc.
References i, and s.
output() [3/8]
void oomph::SolidQHermiteElement< 2 >::output (FILE * file_pt, const unsigned & n_plot) [virtual]
The C-style output function for any number of points per element.
Reimplemented from oomph::QHermiteElement< DIM >.
Definition at line 1223 of file hermite_elements.cc.
References i, and s.
output() [4/8]
template<unsigned DIM>
void oomph::SolidQHermiteElement< DIM >::output (FILE * file_pt, const unsigned & n_plot) [virtual]
C_style output at n_plot points.
Reimplemented from oomph::QHermiteElement< DIM >.
Reimplemented in oomph::HermitePVDElement< DIM >.
output() [5/8]
template<unsigned DIM>
void oomph::SolidQHermiteElement< DIM >::output (std::ostream & outfile) [virtual]
Overload the output function.
Reimplemented from oomph::QHermiteElement< DIM >.
Reimplemented in oomph::HermitePVDElement< DIM >.
Definition at line 1072 of file hermite_elements.cc.
References oomph::QHermiteElement< DIM >::output().
Referenced by oomph::HermiteShellElement::output(), and oomph::HermitePVDElement< DIM >::output().
output() [6/8]
void oomph::SolidQHermiteElement< 2 >::output (std::ostream & outfile, const unsigned & n_p) [virtual]
The output function for any number of points per element.
Reimplemented from oomph::QHermiteElement< DIM >.
Definition at line 1178 of file hermite_elements.cc.
References i, and s.
output() [7/8]
void oomph::SolidQHermiteElement< 1 >::output (std::ostream & outfile, const unsigned & n_plot) [virtual]
The output function for n_plot points in each coordinate direction for the 1D element.
Reimplemented from oomph::QHermiteElement< DIM >.
Definition at line 1083 of file hermite_elements.cc.
References i, and s.
output() [8/8]
template<unsigned DIM>
void oomph::SolidQHermiteElement< DIM >::output (std::ostream & outfile, const unsigned & n_plot) [virtual]
Output at n_plot points.
Reimplemented from oomph::QHermiteElement< DIM >.
Reimplemented in oomph::HermitePVDElement< DIM >.
The documentation for this class was generated from the following files:
hermite_elements.h
hermite_elements.cc