oomph::XdaTetMesh< ELEMENT > Class Template Reference
Tet mesh made of quadratic (ten node) tets built from xda input file.
#include <xda_tet_mesh.template.h>
Public Member Functions
XdaTetMesh (const std::string xda_file_name, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass name of xda file. Note that all boundary elements get their own ID -- this is required for FSI problems. In this case; the vector containing the oomph-lib boundary IDs of all oomph-lib boundaries that collectively form a given boundary as specified in the xda input file can be obtained from the access function oomph_lib_boundary_ids(...). Timestepper defaults to steady pseudo-timestepper.
void setup_boundary_coordinates (const unsigned &b, const bool &switch_normal)
Setup boundary coordinate on boundary b while is temporarily flattened to simplex faces. Boundary coordinates are the x-y coordinates in the plane of that boundary with the x-axis along the line from the (lexicographically) `lower left` to the `upper right` node. The y axis is obtained by taking the cross-product of the positive x direction with the outer unit normal computed by the face elements (or its negative if switch_normal is set to true).
void setup_boundary_coordinates (const unsigned &b, const bool &switch_normal, std::ofstream &outfile)
Setup boundary coordinate on boundary b while is temporarily flattened to simplex faces. Boundary coordinates are the x-y coordinates in the plane of that boundary with the x-axis along the line from the (lexicographically) `lower left` to the `upper right` node. The y axis is obtained by taking the cross-product of the positive x direction with the outer unit normal computed by the face elements (or its negative if switch_normal is set to true). Doc faces in output file.
unsigned nxda_boundary ()
Access function to the number of distinct boundaries specified in the original xda enumeration.
Vector< unsigned > oomph_lib_boundary_ids (const unsigned &xda_boundary_id)
Access functions to the Vector of oomph-lib boundary ids that make up boundary b in the original xda enumeration.
Private Attributes
Vector< Vector< unsigned > > Boundary_id
Vector of vectors containing the boundary IDs of the overall boundary specified in the xda file.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::XdaTetMesh< ELEMENT >
Tet mesh made of quadratic (ten node) tets built from xda input file.
Definition at line 53 of file xda_tet_mesh.template.h.
Constructor & Destructor Documentation
XdaTetMesh()
template<class ELEMENT >
oomph::XdaTetMesh< ELEMENT >::XdaTetMesh (const std::string xda_file_name, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass name of xda file. Note that all boundary elements get their own ID -- this is required for FSI problems. In this case; the vector containing the oomph-lib boundary IDs of all oomph-lib boundaries that collectively form a given boundary as specified in the xda input file can be obtained from the access function oomph_lib_boundary_ids(...). Timestepper defaults to steady pseudo-timestepper.
Constructor: Pass name of xda file. Note that all boundary elements get their own ID -- this is required for FSI problems. The vector containing the oomph-lib boundary IDs of all oomph-lib boundaries that collectively form a given boundary as specified in the xda input file can be obtained from the access function oomph_lib_boundary_ids(...). Timestepper defaults to steady pseudo-timestepper.
Definition at line 46 of file xda_tet_mesh.template.cc.
References e, i, and oomph::Global_string_for_annotation::string().
Member Function Documentation
nxda_boundary()
template<class ELEMENT >
unsigned oomph::XdaTetMesh< ELEMENT >::nxda_boundary () [inline]
Access function to the number of distinct boundaries specified in the original xda enumeration.
Definition at line 98 of file xda_tet_mesh.template.h.
References oomph::XdaTetMesh< ELEMENT >::Boundary_id.
oomph_lib_boundary_ids()
template<class ELEMENT >
Vector< unsigned > oomph::XdaTetMesh< ELEMENT >::oomph_lib_boundary_ids (const unsigned & xda_boundary_id) [inline]
Access functions to the Vector of oomph-lib boundary ids that make up boundary b in the original xda enumeration.
Definition at line 105 of file xda_tet_mesh.template.h.
References oomph::XdaTetMesh< ELEMENT >::Boundary_id.
setup_boundary_coordinates() [1/2]
template<class ELEMENT >
void oomph::XdaTetMesh< ELEMENT >::setup_boundary_coordinates (const unsigned & b, const bool & switch_normal) [inline]
Setup boundary coordinate on boundary b while is temporarily flattened to simplex faces. Boundary coordinates are the x-y coordinates in the plane of that boundary with the x-axis along the line from the (lexicographically) `lower left` to the `upper right` node. The y axis is obtained by taking the cross-product of the positive x direction with the outer unit normal computed by the face elements (or its negative if switch_normal is set to true).
Definition at line 75 of file xda_tet_mesh.template.h.
References oomph::XdaTetMesh< ELEMENT >::setup_boundary_coordinates().
Referenced by oomph::XdaTetMesh< ELEMENT >::setup_boundary_coordinates().
setup_boundary_coordinates() [2/2]
template<class ELEMENT >
void oomph::XdaTetMesh< ELEMENT >::setup_boundary_coordinates (const unsigned & b, const bool & switch_normal, std::ofstream & outfile)
Setup boundary coordinate on boundary b while is temporarily flattened to simplex faces. Boundary coordinates are the x-y coordinates in the plane of that boundary with the x-axis along the line from the (lexicographically) `lower left` to the `upper right` node. The y axis is obtained by taking the cross-product of the positive x direction with the outer unit normal computed by the face elements (or its negative if switch_normal is set to true). Doc faces in output file.
Definition at line 345 of file xda_tet_mesh.template.cc.
References e, i, oomph::FiniteElement::node_pt(), oomph::Node::position(), s, oomph::Node::set_coordinates_on_boundary(), and oomph::Node::x().
Member Data Documentation
Boundary_id
template<class ELEMENT >
Vector<Vector<unsigned> > oomph::XdaTetMesh< ELEMENT >::Boundary_id [private]
Vector of vectors containing the boundary IDs of the overall boundary specified in the xda file.
Definition at line 113 of file xda_tet_mesh.template.h.
Referenced by oomph::XdaTetMesh< ELEMENT >::nxda_boundary(), and oomph::XdaTetMesh< ELEMENT >::oomph_lib_boundary_ids().
The documentation for this class was generated from the following files:
xda_tet_mesh.template.h
xda_tet_mesh.template.cc