oomph::QSpectralElement< 3, NNODE_1D > Class Template Reference
General QSpectralElement class specialised to three spatial dimensions.
#include <Qspectral_elements.h>
Public Member Functions
QSpectralElement ()
Constructor.
double s_min () const
Min. value of local coordinate.
double s_max () const
Max. value of local coordinate.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void local_coordinate_of_node (const unsigned &n, Vector< double > &s) const
Get local coordinates of node j in the element; vector sets its own size.
void local_fraction_of_node (const unsigned &n, Vector< double > &s_fraction)
Get the local fractino of node j in the element.
double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
The local one-d fraction is the same.
void shape (const Vector< double > &s, Shape &psi) const
Calculate the geometric shape functions at local coordinate s.
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Compute the geometric shape functions and derivatives w.r.t. local coordinates at local coordinate s.
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
Compute the geometric shape functions, derivatives and second derivatives w.r.t. local coordinates at local coordinate s d2psids(i,0) = $ \partial ^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial ^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial ^2 \psi_j / \partial s_2^2 $ d2psids(i,3) = $ \partial ^2 \psi_j / \partial s_0 \partial s_1 $ d2psids(i,4) = $ \partial ^2 \psi_j / \partial s_0 \partial s_2 $ d2psids(i,5) = $ \partial ^2 \psi_j / \partial s_1 \partial s_2 $.
double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Overload the template-free interface for the calculation of inverse jacobian matrix. This is a one-dimensional element, so use the 3D version.
unsigned nnode_1d () const
Number of nodes along each element edge.
void output (FILE *file_pt)
C-style output.
void output (FILE *file_pt, const unsigned &n_plot)
C_style output at n_plot points.
void output (std::ostream &outfile)
Output.
void output (std::ostream &outfile, const unsigned &nplot)
Output at nplot points.
void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &use_equally_spaced_interior_sample_points=false) const
Get cector of local coordinates of plot point i (when plotting nplot points in each "coordinate direction).
std::string tecplot_zone_string (const unsigned &nplot) const
Return string for tecplot zone header (when plotting nplot points in each "coordinate direction)
unsigned nplot_points (const unsigned &nplot) const
Return total number of plot points (when plotting nplot points in each "coordinate direction)
void build_face_element (const int &face_index, FaceElement *face_element_pt)
Build the lower-dimensional FaceElement (an element of type QSpectralElement<2,NNODE_1D>). The face index takes six values corresponding to the six possible faces: -1 (Left) s[0] = -1.0 +1 (Right) s[0] = 1.0 -2 (Down) s[1] = -1.0 +2 (Up) s[1] = 1.0 -3 (Back) s[2] = -1.0 +3 (Front) s[2] = 1.0.
Static Private Attributes
static GaussLobattoLegendre< 3, NNODE_1D > integral
Default integration rule: Gaussian integration of same 'order' as the element.
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::QSpectralElement< 3, NNODE_1D >
General QSpectralElement class specialised to three spatial dimensions.
Definition at line 964 of file Qspectral_elements.h.
Constructor & Destructor Documentation
QSpectralElement()
template<unsigned NNODE_1D>
oomph::QSpectralElement< 3, NNODE_1D >::QSpectralElement () [inline]
Constructor.
Definition at line 977 of file Qspectral_elements.h.
References oomph::OneDimensionalLegendreShape< NNODE_1D >::calculate_nodal_positions().
Member Function Documentation
build_face_element()
template<unsigned NNODE_1D>
void oomph::QSpectralElement< 3, NNODE_1D >::build_face_element (const int & face_index, FaceElement * face_element_pt) [virtual]
Build the lower-dimensional FaceElement (an element of type QSpectralElement<2,NNODE_1D>). The face index takes six values corresponding to the six possible faces: -1 (Left) s[0] = -1.0 +1 (Right) s[0] = 1.0 -2 (Down) s[1] = -1.0 +2 (Up) s[1] = 1.0 -3 (Back) s[2] = -1.0 +3 (Front) s[2] = 1.0.
Function to setup geometrical information for lower-dimensional FaceElements (which are of type QElement<3,NNODE_1D>).
Reimplemented from oomph::FiniteElement.
Definition at line 538 of file Qspectral_elements.cc.
References oomph::FaceElement::bulk_coordinate_derivatives_fct_pt(), oomph::FaceElement::bulk_element_pt(), oomph::QElement3FaceToBulkCoordinates::face0(), oomph::QElement3FaceToBulkCoordinates::face1(), oomph::QElement3FaceToBulkCoordinates::face2(), oomph::QElement3FaceToBulkCoordinates::face3(), oomph::QElement3FaceToBulkCoordinates::face4(), oomph::QElement3FaceToBulkCoordinates::face5(), oomph::FaceElement::face_index(), oomph::FaceElement::face_to_bulk_coordinate_fct_pt(), oomph::QElement3BulkCoordinateDerivatives::faces0(), oomph::QElement3BulkCoordinateDerivatives::faces1(), oomph::QElement3BulkCoordinateDerivatives::faces2(), i, oomph::FaceElement::nbulk_value_resize(), oomph::FiniteElement::node_pt(), oomph::FaceElement::normal_sign(), oomph::oomph_info, oomph::GeneralisedElement::set_halo(), and oomph::FiniteElement::set_nodal_dimension().
d2shape_local()
template<unsigned NNODE_1D>
void oomph::QSpectralElement< 3, NNODE_1D >::d2shape_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline], [virtual]
Compute the geometric shape functions, derivatives and second derivatives w.r.t. local coordinates at local coordinate s d2psids(i,0) = $ \partial ^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial ^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial ^2 \psi_j / \partial s_2^2 $ d2psids(i,3) = $ \partial ^2 \psi_j / \partial s_0 \partial s_1 $ d2psids(i,4) = $ \partial ^2 \psi_j / \partial s_0 \partial s_2 $ d2psids(i,5) = $ \partial ^2 \psi_j / \partial s_1 \partial s_2 $.
Second derivatives of shape functions for specific QSpectralElement<3,..> d2psids(i,0) = $ \partial ^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial ^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial ^2 \psi_j / \partial s_2^2 $ d2psids(i,3) = $ \partial ^2 \psi_j / \partial s_0 \partial s_1 $ d2psids(i,4) = $ \partial ^2 \psi_j / \partial s_0 \partial s_2 $ d2psids(i,5) = $ \partial ^2 \psi_j / \partial s_1 \partial s_2 $.
Reimplemented from oomph::FiniteElement.
Definition at line 1292 of file Qspectral_elements.h.
dshape_local()
template<unsigned NNODE_1D>
void oomph::QSpectralElement< 3, NNODE_1D >::dshape_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const [inline], [virtual]
Compute the geometric shape functions and derivatives w.r.t. local coordinates at local coordinate s.
Derivatives of shape functions for specific QSpectralElement<3,..>
Reimplemented from oomph::FiniteElement.
Definition at line 1245 of file Qspectral_elements.h.
References i, and s.
get_s_plot()
template<unsigned NNODE_1D>
void oomph::QSpectralElement< 3, NNODE_1D >::get_s_plot (const unsigned & i, const unsigned & nplot, Vector< double > & s, const bool & use_equally_spaced_interior_sample_points = false) const [inline], [virtual]
Get cector of local coordinates of plot point i (when plotting nplot points in each "coordinate direction).
Reimplemented from oomph::FiniteElement.
Definition at line 1142 of file Qspectral_elements.h.
References i, and s.
invert_jacobian_mapping()
template<unsigned NNODE_1D>
double oomph::QSpectralElement< 3, NNODE_1D >::invert_jacobian_mapping (const DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const [inline], [virtual]
Overload the template-free interface for the calculation of inverse jacobian matrix. This is a one-dimensional element, so use the 3D version.
Reimplemented from oomph::FiniteElement.
Definition at line 1110 of file Qspectral_elements.h.
local_coordinate_of_node()
template<unsigned NNODE_1D>
void oomph::QSpectralElement< 3, NNODE_1D >::local_coordinate_of_node (const unsigned & n, Vector< double > & s) const [inline], [virtual]
Get local coordinates of node j in the element; vector sets its own size.
Reimplemented from oomph::FiniteElement.
Definition at line 1056 of file Qspectral_elements.h.
References oomph::OneDimensionalLegendreShape< NNODE_1D >::nodal_position(), and s.
local_fraction_of_node()
template<unsigned NNODE_1D>
void oomph::QSpectralElement< 3, NNODE_1D >::local_fraction_of_node (const unsigned & n, Vector< double > & s_fraction) [inline], [virtual]
Get the local fractino of node j in the element.
Reimplemented from oomph::FiniteElement.
Definition at line 1068 of file Qspectral_elements.h.
local_one_d_fraction_of_node()
template<unsigned NNODE_1D>
double oomph::QSpectralElement< 3, NNODE_1D >::local_one_d_fraction_of_node (const unsigned & n1d, const unsigned & i) [inline], [virtual]
The local one-d fraction is the same.
Reimplemented from oomph::FiniteElement.
Definition at line 1078 of file Qspectral_elements.h.
References oomph::OneDimensionalLegendreShape< NNODE_1D >::nodal_position().
nnode_1d()
template<unsigned NNODE_1D>
unsigned oomph::QSpectralElement< 3, NNODE_1D >::nnode_1d () const [inline], [virtual]
Number of nodes along each element edge.
Reimplemented from oomph::FiniteElement.
Definition at line 1117 of file Qspectral_elements.h.
nplot_points()
template<unsigned NNODE_1D>
unsigned oomph::QSpectralElement< 3, NNODE_1D >::nplot_points (const unsigned & nplot) const [inline], [virtual]
Return total number of plot points (when plotting nplot points in each "coordinate direction)
Reimplemented from oomph::FiniteElement.
Definition at line 1189 of file Qspectral_elements.h.
References i.
nvertex_node()
template<unsigned NNODE_1D>
unsigned oomph::QSpectralElement< 3, NNODE_1D >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::BrickElementBase.
Definition at line 1005 of file Qspectral_elements.h.
output() [1/4]
template<unsigned NNODE_1D>
void oomph::QSpectralElement< 3, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output.
Reimplemented from oomph::FiniteElement.
Definition at line 1123 of file Qspectral_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<unsigned NNODE_1D>
void oomph::QSpectralElement< 3, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C_style output at n_plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 1129 of file Qspectral_elements.h.
References oomph::FiniteElement::output().
output() [3/4]
template<unsigned NNODE_1D>
void oomph::QSpectralElement< 3, NNODE_1D >::output (std::ostream & outfile) [virtual]
Output.
The output function for general 1D QSpectralElements.
Reimplemented from oomph::FiniteElement.
Definition at line 455 of file Qspectral_elements.cc.
References i.
output() [4/4]
template<unsigned NNODE_1D>
void oomph::QSpectralElement< 3, NNODE_1D >::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output at nplot points.
The output function for n_plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Definition at line 496 of file Qspectral_elements.cc.
References i, and s.
s_max()
template<unsigned NNODE_1D>
double oomph::QSpectralElement< 3, NNODE_1D >::s_max () const [inline], [virtual]
Max. value of local coordinate.
Reimplemented from oomph::FiniteElement.
Definition at line 999 of file Qspectral_elements.h.
s_min()
template<unsigned NNODE_1D>
double oomph::QSpectralElement< 3, NNODE_1D >::s_min () const [inline], [virtual]
Min. value of local coordinate.
Reimplemented from oomph::FiniteElement.
Definition at line 993 of file Qspectral_elements.h.
shape()
template<unsigned NNODE_1D>
void oomph::QSpectralElement< 3, NNODE_1D >::shape (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Calculate the geometric shape functions at local coordinate s.
Shape function for specific QSpectralElement<3,..>
Implements oomph::FiniteElement.
Definition at line 1218 of file Qspectral_elements.h.
References i, and s.
tecplot_zone_string()
template<unsigned NNODE_1D>
std::string oomph::QSpectralElement< 3, NNODE_1D >::tecplot_zone_string (const unsigned & nplot) const [inline], [virtual]
Return string for tecplot zone header (when plotting nplot points in each "coordinate direction)
Reimplemented from oomph::FiniteElement.
Definition at line 1179 of file Qspectral_elements.h.
vertex_node_pt()
template<unsigned NNODE_1D>
Node * oomph::QSpectralElement< 3, NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::BrickElementBase.
Definition at line 1011 of file Qspectral_elements.h.
Member Data Documentation
integral
template<unsigned NNODE_1D>
GaussLobattoLegendre< 3, NNODE_1D > oomph::QSpectralElement< 3, NNODE_1D >::integral [static], [private]
Default integration rule: Gaussian integration of same 'order' as the element.
/////////////////////////////////////////////////////////////////////// 3D QLegendreElements
Assign the static integral
Definition at line 973 of file Qspectral_elements.h.
The documentation for this class was generated from the following files:
Qspectral_elements.h
Qspectral_elements.cc