GeneralisedNewtonianNavierStokesEquations< DIM > Class Template Reference
and
#include <generalised_newtonian_navier_stokes_elements.h>
Public Types
typedef void(* NavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
Function pointer to body force function fct(t,x,f(x)) x is a Vector!
typedef double(* NavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
Function pointer to source function fct(t,x) x is a Vector!
typedef double(* NavierStokesPressureAdvDiffSourceFctPt) (const Vector< double > &x)
Function pointer to source function fct(x) for the pressure advection diffusion equation (only used during validation!). x is a Vector!
Public Member Functions
GeneralisedNewtonianNavierStokesEquations ()
Constructor: NULL the body force and source function and make sure the ALE terms are included by default.
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
const double & viscosity_ratio () const
Viscosity ratio for element: Element's viscosity relative to the viscosity used in the definition of the Reynolds number.
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
Density ratio for element: Element's density relative to the viscosity used in the definition of the Reynolds number.
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
NavierStokesBodyForceFctPt & body_force_fct_pt ()
Access function for the body-force pointer.
NavierStokesBodyForceFctPt body_force_fct_pt () const
Access function for the body-force pointer. Const version.
NavierStokesSourceFctPt & source_fct_pt ()
Access function for the source-function pointer.
NavierStokesSourceFctPt source_fct_pt () const
Access function for the source-function pointer. Const version.
GeneralisedNewtonianConstitutiveEquation< DIM > *& constitutive_eqn_pt ()
Access function for the constitutive equation pointer.
void use_current_strainrate_to_compute_second_invariant ()
Switch to fully implict evaluation of non-Newtonian const eqn.
void use_extrapolated_strainrate_to_compute_second_invariant ()
Use extrapolation for non-Newtonian const eqn.
virtual unsigned npres_nst () const =0
Function to return number of pressure degrees of freedom.
virtual void pshape_nst (const Vector< double > &s, Shape &psi) const =0
Compute the pressure shape functions at local coordinate s.
virtual void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const =0
Compute the pressure shape and test functions at local coordinate s.
double u_nst (const unsigned &n, const unsigned &i) const
Velocity i at local node n. Uses suitably interpolated value for hanging nodes. The use of u_index_nst() permits the use of this element as the basis for multi-physics elements. The default is to assume that the i-th velocity component is stored at the i-th location of the node.
double u_nst (const unsigned &t, const unsigned &n, const unsigned &i) const
Velocity i at local node n at timestep t (t=0: present; t>0: previous). Uses suitably interpolated value for hanging nodes.
virtual unsigned u_index_nst (const unsigned &i) const
Return the index at which the i-th unknown velocity component is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
unsigned n_u_nst () const
Return the number of velocity components Used in FluidInterfaceElements.
double du_dt_nst (const unsigned &n, const unsigned &i) const
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
void disable_ALE ()
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
void enable_ALE ()
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
virtual double p_nst (const unsigned &n_p) const =0
Pressure at local pressure `node` n_p Uses suitably interpolated value for hanging nodes.
virtual double p_nst (const unsigned &t, const unsigned &n_p) const =0
Pressure at local pressure `node` n_p at time level t.
virtual void fix_pressure (const unsigned &p_dof, const double &p_value)=0
Pin p_dof-th pressure dof and set it to value specified by p_value.
virtual int p_nodal_index_nst () const
Return the index at which the pressure is stored if it is stored at the nodes. If not stored at the nodes this will return a negative number.
double pressure_integral () const
Integral of pressure over element.
void max_and_min_invariant_and_viscosity (double &min_invariant, double &max_invariant, double &min_viscosity, double &max_viscosity) const
Get max. and min. strain rate invariant and visocosity over all integration points in element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute the vorticity vector at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
double d_kin_energy_dt () const
Get integral of time derivative of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j + du_j/dx_i)
void strain_rate (const unsigned &t, const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j + du_j/dx_i) at a specific time history value.
virtual void extrapolated_strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Extrapolated strain-rate tensor: 1/2 (du_i/dx_j + du_j/dx_i) based on the previous time steps evaluated at local coordinate s.
virtual void extrapolated_strain_rate (const unsigned &ipt, DenseMatrix< double > &strain_rate) const
Extrapolated strain-rate tensor: 1/2 (du_i/dx_j + du_j/dx_i) based on the previous time steps evaluated at ipt-th integration point.
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s. N has to be outer unit normal to the fluid.
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction_p, Vector< double > &traction_visc_n, Vector< double > &traction_visc_t)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s, decomposed into pressure and normal and tangential viscous components. N has to be outer unit normal to the fluid.
void get_load (const Vector< double > &s, const Vector< double > &N, Vector< double > &load)
This implements a pure virtual function defined in the FSIFluidElement class. The function computes the traction (on the viscous scale), at the element's local coordinate s, that the fluid element exerts onto an adjacent solid element. The number of arguments is imposed by the interface defined in the FSIFluidElement -- only the unit normal N (pointing into the fluid!) is actually used in the computation.
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
unsigned nscalar_paraview () const
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
std::string scalar_name_paraview (const unsigned &i) const
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
void output (std::ostream &outfile)
Output function: x,y,[z],u,v,[w],p in tecplot format. Default number of plot points.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,[z],u,v,[w],p in tecplot format. nplot points in each coordinate direction.
void output (FILE *file_pt)
C-style output function: x,y,[z],u,v,[w],p in tecplot format. Default number of plot points.
void output (FILE *file_pt, const unsigned &nplot)
C-style output function: x,y,[z],u,v,[w],p in tecplot format. nplot points in each coordinate direction.
void full_output (std::ostream &outfile)
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. Default number of plot points.
void full_output (std::ostream &outfile, const unsigned &nplot)
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. nplot points in each coordinate direction.
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
Output function: x,y,[z],u,v,[w] in tecplot format. nplot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
void output_vorticity (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,[z], [omega_x,omega_y,[and/or omega_z]] in tecplot format. nplot points in each coordinate direction.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given number of plot points. Function prints as many components as are returned in solution Vector.
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given time and at a given number of plot points. Function prints as many components as are returned in solution Vector.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Compute the element's residual Vector.
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void pin_all_non_pressure_dofs (std::map< Data *, std::vector< int > > &eqn_number_backup)
Pin all non-pressure dofs and backup eqn numbers.
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}.
void interpolated_u_nst (const Vector< double > &s, Vector< double > &veloc) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s at time level t (t=0: present; t>0: history)
virtual void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. The function is virtual so that it can be overloaded in the refineable version.
virtual double interpolated_p_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_p_nst (const unsigned &t, const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s at time level t.
void point_output_data (const Vector< double > &s, Vector< double > &data)
Output solution in data vector at local cordinates s: x,y [,z], u,v,[w], p.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute 3D vorticity vector at local coordinate s.
Static Public Attributes
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Protected Member Functions
virtual double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Compute the shape functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
virtual double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Compute the shape functions and derivatives w.r.t. global coords at ipt-th integration point Return Jacobian of mapping between local and global coordinates.
virtual double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
virtual double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const =0
Compute the pressure shape and test functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
virtual void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
Calculate the body force at a given time and local and/or Eulerian position. This function is virtual so that it can be overloaded in multi-physics elements where the body force might depend on another variable.
virtual void get_body_force_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
Get gradient of body force term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
virtual double get_source_nst (const double &time, const unsigned &ipt, const Vector< double > &x)
Calculate the source fct at given time and Eulerian position.
virtual void get_source_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
Get gradient of source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
virtual void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Compute the residuals for the Navier--Stokes equations. Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
virtual void fill_in_generic_dresidual_contribution_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, unsigned flag)
Compute the derivatives of the residuals for the Navier--Stokes equations with respect to a parameter Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Compute the hessian tensor vector products required to perform continuation of bifurcations analytically.
Protected Attributes
double * Viscosity_Ratio_pt
Pointer to the viscosity ratio (relative to the viscosity used in the definition of the Reynolds number)
double * Density_Ratio_pt
Pointer to the density ratio (relative to the density used in the definition of the Reynolds number)
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
double * ReInvFr_pt
Pointer to global Reynolds number x inverse Froude number (= Bond number / Capillary number)
Vector< double > * G_pt
Pointer to global gravity Vector.
NavierStokesBodyForceFctPt Body_force_fct_pt
Pointer to body force function.
NavierStokesSourceFctPt Source_fct_pt
Pointer to volumetric source function.
GeneralisedNewtonianConstitutiveEquation< DIM > * Constitutive_eqn_pt
Pointer to the generalised Newtonian constitutive equation.
bool Use_extrapolated_strainrate_to_compute_second_invariant
bool ALE_is_disabled
Boolean flag to indicate if ALE formulation is disabled when time-derivatives are computed. Only set to true if you're sure that the mesh is stationary.
Static Protected Attributes
static bool Pre_multiply_by_viscosity_ratio = false
Static boolean telling us whether we pre-multiply the pressure and continuity by the viscosity ratio.
Static Private Attributes
static int Pressure_not_stored_at_node = -100
Static `magic` number that indicates that the pressure is not stored at a node.
static double Default_Physical_Constant_Value = 0.0
Static default value for the physical constants (all initialised to zero)
static double Default_Physical_Ratio_Value = 1.0
Static default value for the physical ratios (all are initialised to one)
static Vector< double > Default_Gravity_vector
Static default value for the gravity vector.
Detailed Description
template<unsigned DIM>
class GeneralisedNewtonianNavierStokesEquations< DIM >
and
$ { \frac{\partial u_i}{\partial x_i} = Q } $
We also provide all functions required to use this element in FSI problems, by deriving it from the FSIFluidElement base class.
Definition at line 123 of file generalised_newtonian_navier_stokes_elements.h.
Member Typedef Documentation
NavierStokesBodyForceFctPt
template<unsigned DIM>
typedef void(* GeneralisedNewtonianNavierStokesEquations< DIM >::NavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
Function pointer to body force function fct(t,x,f(x)) x is a Vector!
Definition at line 130 of file generalised_newtonian_navier_stokes_elements.h.
NavierStokesPressureAdvDiffSourceFctPt
template<unsigned DIM>
typedef double(* GeneralisedNewtonianNavierStokesEquations< DIM >::NavierStokesPressureAdvDiffSourceFctPt) (const Vector< double > &x)
Function pointer to source function fct(x) for the pressure advection diffusion equation (only used during validation!). x is a Vector!
Definition at line 143 of file generalised_newtonian_navier_stokes_elements.h.
NavierStokesSourceFctPt
template<unsigned DIM>
typedef double(* GeneralisedNewtonianNavierStokesEquations< DIM >::NavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
Function pointer to source function fct(t,x) x is a Vector!
Definition at line 136 of file generalised_newtonian_navier_stokes_elements.h.
Constructor & Destructor Documentation
GeneralisedNewtonianNavierStokesEquations()
template<unsigned DIM>
GeneralisedNewtonianNavierStokesEquations< DIM >::GeneralisedNewtonianNavierStokesEquations () [inline]
Constructor: NULL the body force and source function and make sure the ALE terms are included by default.
Definition at line 409 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::MultiDomainBoussinesqHelper::Default_Physical_Constant_Value.
Member Function Documentation
body_force_fct_pt() [1/2]
template<unsigned DIM>
NavierStokesBodyForceFctPt & GeneralisedNewtonianNavierStokesEquations< DIM >::body_force_fct_pt () [inline]
Access function for the body-force pointer.
Definition at line 510 of file generalised_newtonian_navier_stokes_elements.h.
body_force_fct_pt() [2/2]
template<unsigned DIM>
NavierStokesBodyForceFctPt GeneralisedNewtonianNavierStokesEquations< DIM >::body_force_fct_pt () const [inline]
Access function for the body-force pointer. Const version.
Definition at line 516 of file generalised_newtonian_navier_stokes_elements.h.
compute_error() [1/2]
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm)
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Validate against exact velocity solution Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Definition at line 279 of file generalised_newtonian_navier_stokes_elements.cc.
References i, s, oomph::W, and oomph::x.
compute_error() [2/2]
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Validate against exact velocity solution at given time. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Definition at line 200 of file generalised_newtonian_navier_stokes_elements.cc.
References i, s, oomph::W, and oomph::x.
constitutive_eqn_pt()
template<unsigned DIM>
GeneralisedNewtonianConstitutiveEquation< DIM > *& GeneralisedNewtonianNavierStokesEquations< DIM >::constitutive_eqn_pt () [inline]
Access function for the constitutive equation pointer.
Definition at line 534 of file generalised_newtonian_navier_stokes_elements.h.
d_kin_energy_dt()
template<unsigned DIM>
double GeneralisedNewtonianNavierStokesEquations< DIM >::d_kin_energy_dt
Get integral of time derivative of kinetic energy over element.
Get integral of time derivative of kinetic energy over element:
Definition at line 1415 of file generalised_newtonian_navier_stokes_elements.cc.
References i, and s.
density_ratio()
template<unsigned DIM>
const double & GeneralisedNewtonianNavierStokesEquations< DIM >::density_ratio () const [inline]
Density ratio for element: Element's density relative to the viscosity used in the definition of the Reynolds number.
Definition at line 474 of file generalised_newtonian_navier_stokes_elements.h.
density_ratio_pt()
template<unsigned DIM>
double *& GeneralisedNewtonianNavierStokesEquations< DIM >::density_ratio_pt () [inline]
Pointer to Density ratio.
Definition at line 480 of file generalised_newtonian_navier_stokes_elements.h.
dinterpolated_u_nst_ddata()
template<unsigned DIM>
virtual void GeneralisedNewtonianNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata (const Vector< double > & s, const unsigned & i, Vector< double > & du_ddata, Vector< unsigned > & global_eqn_number) [inline], [virtual]
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. The function is virtual so that it can be overloaded in the refineable version.
Definition at line 1181 of file generalised_newtonian_navier_stokes_elements.h.
References i, s, and oomph::OneDimLagrange::shape().
disable_ALE()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::disable_ALE () [inline]
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
Definition at line 629 of file generalised_newtonian_navier_stokes_elements.h.
dissipation() [1/2]
template<unsigned DIM>
double GeneralisedNewtonianNavierStokesEquations< DIM >::dissipation
Return integral of dissipation over element.
Definition at line 830 of file generalised_newtonian_navier_stokes_elements.cc.
References i, and s.
dissipation() [2/2]
template<unsigned DIM>
double GeneralisedNewtonianNavierStokesEquations< DIM >::dissipation (const Vector< double > & s) const
Return dissipation at local coordinate s.
Definition at line 983 of file generalised_newtonian_navier_stokes_elements.cc.
References i, and s.
dpshape_and_dptest_eulerian_nst()
template<unsigned DIM>
virtual double GeneralisedNewtonianNavierStokesEquations< DIM >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [protected], [pure virtual]
Compute the pressure shape and test functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Implemented in GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, GeneralisedNewtonianQTaylorHoodElement< DIM >, GeneralisedNewtonianQTaylorHoodElement< DIM >, and GeneralisedNewtonianQTaylorHoodElement< DIM >.
dshape_and_dtest_eulerian_at_knot_nst() [1/2]
template<unsigned DIM>
virtual double GeneralisedNewtonianNavierStokesEquations< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implemented in GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, GeneralisedNewtonianQTaylorHoodElement< DIM >, GeneralisedNewtonianQTaylorHoodElement< DIM >, and GeneralisedNewtonianQTaylorHoodElement< DIM >.
dshape_and_dtest_eulerian_at_knot_nst() [2/2]
template<unsigned DIM>
virtual double GeneralisedNewtonianNavierStokesEquations< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Compute the shape functions and derivatives w.r.t. global coords at ipt-th integration point Return Jacobian of mapping between local and global coordinates.
Implemented in GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, and GeneralisedNewtonianQTaylorHoodElement< DIM >.
dshape_and_dtest_eulerian_nst()
template<unsigned DIM>
virtual double GeneralisedNewtonianNavierStokesEquations< DIM >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Compute the shape functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Implemented in GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, and GeneralisedNewtonianQTaylorHoodElement< DIM >.
du_dt_nst()
template<unsigned DIM>
double GeneralisedNewtonianNavierStokesEquations< DIM >::du_dt_nst (const unsigned & n, const unsigned & i) const [inline]
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
Definition at line 600 of file generalised_newtonian_navier_stokes_elements.h.
References i, and t.
enable_ALE()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::enable_ALE () [inline]
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
Definition at line 638 of file generalised_newtonian_navier_stokes_elements.h.
extrapolated_strain_rate() [1/2]
template<unsigned DIM>
virtual void GeneralisedNewtonianNavierStokesEquations< DIM >::extrapolated_strain_rate (const unsigned & ipt, DenseMatrix< double > & strain_rate) const [inline], [virtual]
Extrapolated strain-rate tensor: 1/2 (du_i/dx_j + du_j/dx_i) based on the previous time steps evaluated at ipt-th integration point.
Definition at line 706 of file generalised_newtonian_navier_stokes_elements.h.
References i, and s.
extrapolated_strain_rate() [2/2]
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::extrapolated_strain_rate (const Vector< double > & s, DenseMatrix< double > & strain_rate) const [virtual]
Extrapolated strain-rate tensor: 1/2 (du_i/dx_j + du_j/dx_i) based on the previous time steps evaluated at local coordinate s.
Get strain-rate tensor: 1/2 (du_i/dx_j + du_j/dx_i) Extrapolated from history values.
Definition at line 1175 of file generalised_newtonian_navier_stokes_elements.cc.
References i, and s.
fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam, DenseMatrix< double > & dmass_matrix_dparam) [inline]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Definition at line 994 of file generalised_newtonian_navier_stokes_elements.h.
fill_in_contribution_to_djacobian_dparameter()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_contribution_to_djacobian_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam) [inline]
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
Definition at line 978 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_contribution_to_dresiduals_dparameter()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_contribution_to_dresiduals_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam) [inline]
Compute the element's residual Vector.
Definition at line 963 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_contribution_to_hessian_vector_products()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_contribution_to_hessian_vector_products (Vector< double > const & Y, DenseMatrix< double > const & C, DenseMatrix< double > & product) [protected]
Compute the hessian tensor vector products required to perform continuation of bifurcations analytically.
Definition at line 2111 of file generalised_newtonian_navier_stokes_elements.cc.
fill_in_contribution_to_jacobian()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline]
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
Definition at line 940 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_contribution_to_jacobian_and_mass_matrix()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Definition at line 952 of file generalised_newtonian_navier_stokes_elements.h.
fill_in_contribution_to_residuals()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline]
Compute the element's residual Vector.
Definition at line 927 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_generic_dresidual_contribution_nst()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_generic_dresidual_contribution_nst (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam, DenseMatrix< double > & dmass_matrix_dparam, unsigned flag) [protected], [virtual]
Compute the derivatives of the residuals for the Navier--Stokes equations with respect to a parameter Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
Compute the derivatives of the residuals for the Navier--Stokes equations with respect to a parameter; flag=2 or 1 or 0: do (or don't) compute the Jacobian and mass matrix as well.
Definition at line 2093 of file generalised_newtonian_navier_stokes_elements.cc.
fill_in_generic_residual_contribution_nst()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [protected], [virtual]
Compute the residuals for the Navier--Stokes equations. Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
Compute the residuals for the Navier--Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented in oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1607 of file generalised_newtonian_navier_stokes_elements.cc.
References i, s, oomph::SecondInvariantHelper::second_invariant(), and oomph::W.
fix_pressure()
template<unsigned DIM>
virtual void GeneralisedNewtonianNavierStokesEquations< DIM >::fix_pressure (const unsigned & p_dof, const double & p_value) [pure virtual]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implemented in GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, GeneralisedNewtonianQTaylorHoodElement< DIM >, oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >, and oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >.
full_output() [1/2]
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::full_output (std::ostream & outfile) [inline]
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. Default number of plot points.
Definition at line 868 of file generalised_newtonian_navier_stokes_elements.h.
Referenced by GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::full_output(), and oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::full_output().
full_output() [2/2]
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::full_output (std::ostream & outfile, const unsigned & nplot)
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. nplot points in each coordinate direction.
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. Specified number of plot points in each coordinate direction.
Definition at line 631 of file generalised_newtonian_navier_stokes_elements.cc.
References i, and s.
g()
template<unsigned DIM>
const Vector< double > & GeneralisedNewtonianNavierStokesEquations< DIM >::g () const [inline]
Vector of gravitational components.
Definition at line 498 of file generalised_newtonian_navier_stokes_elements.h.
g_pt()
template<unsigned DIM>
Vector< double > *& GeneralisedNewtonianNavierStokesEquations< DIM >::g_pt () [inline]
Pointer to Vector of gravitational components.
Definition at line 504 of file generalised_newtonian_navier_stokes_elements.h.
get_body_force_gradient_nst()
template<unsigned DIM>
virtual void GeneralisedNewtonianNavierStokesEquations< DIM >::get_body_force_gradient_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, DenseMatrix< double > & d_body_force_dx) [inline], [protected], [virtual]
Get gradient of body force term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
Definition at line 283 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedElement::Default_fd_jacobian_step, i, s, and oomph::x.
get_body_force_nst()
template<unsigned DIM>
virtual void GeneralisedNewtonianNavierStokesEquations< DIM >::get_body_force_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & result) [inline], [protected], [virtual]
Calculate the body force at a given time and local and/or Eulerian position. This function is virtual so that it can be overloaded in multi-physics elements where the body force might depend on another variable.
Definition at line 256 of file generalised_newtonian_navier_stokes_elements.h.
References i, and oomph::x.
get_dresidual_dnodal_coordinates()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates (RankThreeTensor< double > & dresidual_dnodal_coordinates) [virtual]
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}.
Compute derivatives of elemental residual vector with respect to nodal coordinates. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij} Overloads the FD-based version in the FE base class.
Definition at line 2131 of file generalised_newtonian_navier_stokes_elements.cc.
References oomph::GeneralisedElement::Default_fd_jacobian_step, i, and s.
get_load()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::get_load (const Vector< double > & s, const Vector< double > & N, Vector< double > & load) [inline]
This implements a pure virtual function defined in the FSIFluidElement class. The function computes the traction (on the viscous scale), at the element's local coordinate s, that the fluid element exerts onto an adjacent solid element. The number of arguments is imposed by the interface defined in the FSIFluidElement -- only the unit normal N (pointing into the fluid!) is actually used in the computation.
Definition at line 740 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::QuadTreeNames::N, and s.
get_pressure_and_velocity_mass_matrix_diagonal()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > & press_mass_diag, Vector< double > & veloc_mass_diag, const unsigned & which_one = 0)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
Definition at line 81 of file generalised_newtonian_navier_stokes_elements.cc.
References i, s, and oomph::W.
get_source_gradient_nst()
template<unsigned DIM>
virtual void GeneralisedNewtonianNavierStokesEquations< DIM >::get_source_gradient_nst (const double & time, const unsigned & ipt, const Vector< double > & x, Vector< double > & gradient) [inline], [protected], [virtual]
Get gradient of source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
Definition at line 346 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::GeneralisedElement::Default_fd_jacobian_step, i, and oomph::x.
get_source_nst()
template<unsigned DIM>
virtual double GeneralisedNewtonianNavierStokesEquations< DIM >::get_source_nst (const double & time, const unsigned & ipt, const Vector< double > & x) [inline], [protected], [virtual]
Calculate the source fct at given time and Eulerian position.
Definition at line 324 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::x.
get_traction() [1/2]
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::get_traction (const Vector< double > & s, const Vector< double > & N, Vector< double > & traction)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s. N has to be outer unit normal to the fluid.
Definition at line 887 of file generalised_newtonian_navier_stokes_elements.cc.
References i, oomph::QuadTreeNames::N, s, and oomph::SecondInvariantHelper::second_invariant().
get_traction() [2/2]
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::get_traction (const Vector< double > & s, const Vector< double > & N, Vector< double > & traction_p, Vector< double > & traction_visc_n, Vector< double > & traction_visc_t)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s, decomposed into pressure and normal and tangential viscous components. N has to be outer unit normal to the fluid.
Definition at line 931 of file generalised_newtonian_navier_stokes_elements.cc.
References i, oomph::QuadTreeNames::N, s, and oomph::SecondInvariantHelper::second_invariant().
get_vorticity() [1/3]
void GeneralisedNewtonianNavierStokesEquations< 2 >::get_vorticity (const Vector< double > & s, Vector< double > & vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector.
Definition at line 1226 of file generalised_newtonian_navier_stokes_elements.cc.
References i, and s.
get_vorticity() [2/3]
void GeneralisedNewtonianNavierStokesEquations< 3 >::get_vorticity (const Vector< double > & s, Vector< double > & vorticity) const
Compute 3D vorticity vector at local coordinate s.
Definition at line 1293 of file generalised_newtonian_navier_stokes_elements.cc.
References i, and s.
get_vorticity() [3/3]
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::get_vorticity (const Vector< double > & s, Vector< double > & vorticity) const
Compute the vorticity vector at local coordinate s.
interpolated_p_nst() [1/2]
template<unsigned DIM>
double GeneralisedNewtonianNavierStokesEquations< DIM >::interpolated_p_nst (const unsigned & t, const Vector< double > & s) const [inline]
Return FE interpolated pressure at local coordinate s at time level t.
Definition at line 1255 of file generalised_newtonian_navier_stokes_elements.h.
References s, and t.
interpolated_p_nst() [2/2]
template<unsigned DIM>
virtual double GeneralisedNewtonianNavierStokesEquations< DIM >::interpolated_p_nst (const Vector< double > & s) const [inline], [virtual]
Return FE interpolated pressure at local coordinate s.
Definition at line 1233 of file generalised_newtonian_navier_stokes_elements.h.
References s.
Referenced by oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::further_build(), oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::further_build(), and oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::get_interpolated_values().
interpolated_u_nst() [1/3]
template<unsigned DIM>
double GeneralisedNewtonianNavierStokesEquations< DIM >::interpolated_u_nst (const unsigned & t, const Vector< double > & s, const unsigned & i) const [inline]
Return FE interpolated velocity u[i] at local coordinate s at time level t (t=0: present; t>0: history)
Definition at line 1149 of file generalised_newtonian_navier_stokes_elements.h.
References i, s, oomph::OneDimLagrange::shape(), and t.
interpolated_u_nst() [2/3]
template<unsigned DIM>
double GeneralisedNewtonianNavierStokesEquations< DIM >::interpolated_u_nst (const Vector< double > & s, const unsigned & i) const [inline]
Return FE interpolated velocity u[i] at local coordinate s.
Definition at line 1124 of file generalised_newtonian_navier_stokes_elements.h.
References i, s, and oomph::OneDimLagrange::shape().
interpolated_u_nst() [3/3]
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::interpolated_u_nst (const Vector< double > & s, Vector< double > & veloc) const [inline]
Compute vector of FE interpolated velocity u at local coordinate s.
Definition at line 1099 of file generalised_newtonian_navier_stokes_elements.h.
References i, s, and oomph::OneDimLagrange::shape().
Referenced by oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::get_interpolated_values(), and oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::get_interpolated_values().
kin_energy()
template<unsigned DIM>
double GeneralisedNewtonianNavierStokesEquations< DIM >::kin_energy
Get integral of kinetic energy over element.
Get integral of kinetic energy over element: Note that this is the `raw` kinetic energy in the sense that the density ratio has not been included. In problems with two or more fluids the user will have to remember to premultiply certain elements by the appropriate density ratio.
Definition at line 1366 of file generalised_newtonian_navier_stokes_elements.cc.
References i, and s.
max_and_min_invariant_and_viscosity()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::max_and_min_invariant_and_viscosity (double & min_invariant, double & max_invariant, double & min_viscosity, double & max_viscosity) const
Get max. and min. strain rate invariant and visocosity over all integration points in element.
Definition at line 1559 of file generalised_newtonian_navier_stokes_elements.cc.
References i, s, and oomph::SecondInvariantHelper::second_invariant().
n_u_nst()
template<unsigned DIM>
unsigned GeneralisedNewtonianNavierStokesEquations< DIM >::n_u_nst () const [inline]
Return the number of velocity components Used in FluidInterfaceElements.
Definition at line 593 of file generalised_newtonian_navier_stokes_elements.h.
npres_nst()
template<unsigned DIM>
virtual unsigned GeneralisedNewtonianNavierStokesEquations< DIM >::npres_nst () const [pure virtual]
Function to return number of pressure degrees of freedom.
Implemented in GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, GeneralisedNewtonianQTaylorHoodElement< DIM >, oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >, and oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >.
nscalar_paraview()
template<unsigned DIM>
unsigned GeneralisedNewtonianNavierStokesEquations< DIM >::nscalar_paraview () const [inline]
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
Definition at line 762 of file generalised_newtonian_navier_stokes_elements.h.
output() [1/4]
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::output (FILE * file_pt) [inline]
C-style output function: x,y,[z],u,v,[w],p in tecplot format. Default number of plot points.
Definition at line 855 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::CommandLineArgs::output().
output() [2/4]
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::output (FILE * file_pt, const unsigned & nplot)
C-style output function: x,y,[z],u,v,[w],p in tecplot format. nplot points in each coordinate direction.
C-style output function: x,y,[z],u,v,[w],p in tecplot format. Specified number of plot points in each coordinate direction.
Definition at line 586 of file generalised_newtonian_navier_stokes_elements.cc.
References i, and s.
output() [3/4]
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::output (std::ostream & outfile) [inline]
Output function: x,y,[z],u,v,[w],p in tecplot format. Default number of plot points.
Definition at line 843 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::CommandLineArgs::output().
Referenced by GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::output(), GeneralisedNewtonianQTaylorHoodElement< DIM >::output(), oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::output(), and oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::output().
output() [4/4]
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::output (std::ostream & outfile, const unsigned & nplot)
Output function: x,y,[z],u,v,[w],p in tecplot format. nplot points in each coordinate direction.
Output function: x,y,[z],u,v,[w],p in tecplot format. Specified number of plot points in each coordinate direction.
Definition at line 539 of file generalised_newtonian_navier_stokes_elements.cc.
References i, and s.
output_fct() [1/2]
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given time and at a given number of plot points. Function prints as many components as are returned in solution Vector.
Output `exact` solution at a given time Solution is provided via function pointer. Plot at a given number of plot points. Function prints as many components as are returned in solution Vector.
Definition at line 413 of file generalised_newtonian_navier_stokes_elements.cc.
References i, s, and oomph::x.
output_fct() [2/2]
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given number of plot points. Function prints as many components as are returned in solution Vector.
Output `exact` solution Solution is provided via function pointer. Plot at a given number of plot points. Function prints as many components as are returned in solution Vector.
Definition at line 357 of file generalised_newtonian_navier_stokes_elements.cc.
References i, s, and oomph::x.
output_veloc()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::output_veloc (std::ostream & outfile, const unsigned & nplot, const unsigned & t)
Output function: x,y,[z],u,v,[w] in tecplot format. nplot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
Output function: Velocities only x,y,[z],u,v,[w] in tecplot format at specified previous timestep (t=0: present; t>0: previous timestep). Specified number of plot points in each coordinate direction.
Definition at line 471 of file generalised_newtonian_navier_stokes_elements.cc.
References i, s, oomph::OneDimLagrange::shape(), and t.
output_vorticity()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::output_vorticity (std::ostream & outfile, const unsigned & nplot)
Output function: x,y,[z], [omega_x,omega_y,[and/or omega_z]] in tecplot format. nplot points in each coordinate direction.
Output function for vorticity. x,y,[z],[omega_x,omega_y,[and/or omega_z]] in tecplot format. Specified number of plot points in each coordinate direction.
Definition at line 762 of file generalised_newtonian_navier_stokes_elements.cc.
References i, s, and oomph::Global_string_for_annotation::string().
p_nodal_index_nst()
template<unsigned DIM>
virtual int GeneralisedNewtonianNavierStokesEquations< DIM >::p_nodal_index_nst () const [inline], [virtual]
Return the index at which the pressure is stored if it is stored at the nodes. If not stored at the nodes this will return a negative number.
Reimplemented in GeneralisedNewtonianQTaylorHoodElement< DIM >, and oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >.
Definition at line 656 of file generalised_newtonian_navier_stokes_elements.h.
p_nst() [1/2]
template<unsigned DIM>
virtual double GeneralisedNewtonianNavierStokesEquations< DIM >::p_nst (const unsigned & n_p) const [pure virtual]
Pressure at local pressure `node` n_p Uses suitably interpolated value for hanging nodes.
Implemented in GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >, GeneralisedNewtonianQTaylorHoodElement< DIM >, and oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >.
p_nst() [2/2]
template<unsigned DIM>
virtual double GeneralisedNewtonianNavierStokesEquations< DIM >::p_nst (const unsigned & t, const unsigned & n_p) const [pure virtual]
Pressure at local pressure `node` n_p at time level t.
Implemented in GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >, GeneralisedNewtonianQTaylorHoodElement< DIM >, and oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >.
pin_all_non_pressure_dofs()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::pin_all_non_pressure_dofs (std::map< Data *, std::vector< int > > & eqn_number_backup) [inline]
Pin all non-pressure dofs and backup eqn numbers.
Definition at line 1007 of file generalised_newtonian_navier_stokes_elements.h.
References i.
point_output_data()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::point_output_data (const Vector< double > & s, Vector< double > & data) [inline]
Output solution in data vector at local cordinates s: x,y [,z], u,v,[w], p.
Definition at line 1278 of file generalised_newtonian_navier_stokes_elements.h.
References i, and s.
pressure_integral()
template<unsigned DIM>
double GeneralisedNewtonianNavierStokesEquations< DIM >::pressure_integral
Integral of pressure over element.
Return pressure integrated over the element.
Definition at line 1513 of file generalised_newtonian_navier_stokes_elements.cc.
References i, s, and oomph::W.
pshape_nst() [1/2]
template<unsigned DIM>
virtual void GeneralisedNewtonianNavierStokesEquations< DIM >::pshape_nst (const Vector< double > & s, Shape & psi) const [pure virtual]
Compute the pressure shape functions at local coordinate s.
Implemented in GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, GeneralisedNewtonianQTaylorHoodElement< DIM >, GeneralisedNewtonianQTaylorHoodElement< DIM >, and GeneralisedNewtonianQTaylorHoodElement< DIM >.
pshape_nst() [2/2]
template<unsigned DIM>
virtual void GeneralisedNewtonianNavierStokesEquations< DIM >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const [pure virtual]
Compute the pressure shape and test functions at local coordinate s.
Implemented in GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, and GeneralisedNewtonianQTaylorHoodElement< DIM >.
re()
template<unsigned DIM>
const double & GeneralisedNewtonianNavierStokesEquations< DIM >::re () const [inline]
Reynolds number.
Definition at line 436 of file generalised_newtonian_navier_stokes_elements.h.
re_invfr()
template<unsigned DIM>
const double & GeneralisedNewtonianNavierStokesEquations< DIM >::re_invfr () const [inline]
Global inverse Froude number.
Definition at line 486 of file generalised_newtonian_navier_stokes_elements.h.
re_invfr_pt()
template<unsigned DIM>
double *& GeneralisedNewtonianNavierStokesEquations< DIM >::re_invfr_pt () [inline]
Pointer to global inverse Froude number.
Definition at line 492 of file generalised_newtonian_navier_stokes_elements.h.
re_pt()
template<unsigned DIM>
double *& GeneralisedNewtonianNavierStokesEquations< DIM >::re_pt () [inline]
Pointer to Reynolds number.
Definition at line 448 of file generalised_newtonian_navier_stokes_elements.h.
re_st()
template<unsigned DIM>
const double & GeneralisedNewtonianNavierStokesEquations< DIM >::re_st () const [inline]
Product of Reynolds and Strouhal number (=Womersley number)
Definition at line 442 of file generalised_newtonian_navier_stokes_elements.h.
re_st_pt()
template<unsigned DIM>
double *& GeneralisedNewtonianNavierStokesEquations< DIM >::re_st_pt () [inline]
Pointer to product of Reynolds and Strouhal number (=Womersley number)
Definition at line 454 of file generalised_newtonian_navier_stokes_elements.h.
scalar_name_paraview()
template<unsigned DIM>
std::string GeneralisedNewtonianNavierStokesEquations< DIM >::scalar_name_paraview (const unsigned & i) const [inline]
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
Definition at line 815 of file generalised_newtonian_navier_stokes_elements.h.
References i, and oomph::StringConversion::to_string().
scalar_value_paraview()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const [inline]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Definition at line 769 of file generalised_newtonian_navier_stokes_elements.h.
References i, and s.
source_fct_pt() [1/2]
template<unsigned DIM>
NavierStokesSourceFctPt & GeneralisedNewtonianNavierStokesEquations< DIM >::source_fct_pt () [inline]
Access function for the source-function pointer.
Definition at line 522 of file generalised_newtonian_navier_stokes_elements.h.
source_fct_pt() [2/2]
template<unsigned DIM>
NavierStokesSourceFctPt GeneralisedNewtonianNavierStokesEquations< DIM >::source_fct_pt () const [inline]
Access function for the source-function pointer. Const version.
Definition at line 528 of file generalised_newtonian_navier_stokes_elements.h.
strain_rate() [1/2]
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::strain_rate (const unsigned & t, const Vector< double > & s, DenseMatrix< double > & strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j + du_j/dx_i) at a specific time history value.
Get strain-rate tensor: 1/2 (du_i/dx_j + du_j/dx_i) at a specific time.
Definition at line 1082 of file generalised_newtonian_navier_stokes_elements.cc.
References i, s, and t.
strain_rate() [2/2]
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::strain_rate (const Vector< double > & s, DenseMatrix< double > & strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j + du_j/dx_i)
Get strain-rate tensor: 1/2 (du_i/dx_j + du_j/dx_i)
Definition at line 1012 of file generalised_newtonian_navier_stokes_elements.cc.
References i, and s.
Referenced by oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::get_Z2_flux(), oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::get_Z2_flux(), and oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::get_Z2_flux().
u_index_nst()
template<unsigned DIM>
virtual unsigned GeneralisedNewtonianNavierStokesEquations< DIM >::u_index_nst (const unsigned & i) const [inline], [virtual]
Return the index at which the i-th unknown velocity component is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
Definition at line 586 of file generalised_newtonian_navier_stokes_elements.h.
References i.
Referenced by oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::get_interpolated_values(), oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::identify_load_data(), and oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::identify_load_data().
u_nst() [1/2]
template<unsigned DIM>
double GeneralisedNewtonianNavierStokesEquations< DIM >::u_nst (const unsigned & n, const unsigned & i) const [inline]
Velocity i at local node n. Uses suitably interpolated value for hanging nodes. The use of u_index_nst() permits the use of this element as the basis for multi-physics elements. The default is to assume that the i-th velocity component is stored at the i-th location of the node.
Definition at line 568 of file generalised_newtonian_navier_stokes_elements.h.
References i.
u_nst() [2/2]
template<unsigned DIM>
double GeneralisedNewtonianNavierStokesEquations< DIM >::u_nst (const unsigned & t, const unsigned & n, const unsigned & i) const [inline]
Velocity i at local node n at timestep t (t=0: present; t>0: previous). Uses suitably interpolated value for hanging nodes.
Definition at line 575 of file generalised_newtonian_navier_stokes_elements.h.
References i, and t.
use_current_strainrate_to_compute_second_invariant()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::use_current_strainrate_to_compute_second_invariant () [inline]
Switch to fully implict evaluation of non-Newtonian const eqn.
Definition at line 540 of file generalised_newtonian_navier_stokes_elements.h.
use_extrapolated_strainrate_to_compute_second_invariant()
template<unsigned DIM>
void GeneralisedNewtonianNavierStokesEquations< DIM >::use_extrapolated_strainrate_to_compute_second_invariant () [inline]
Use extrapolation for non-Newtonian const eqn.
Definition at line 546 of file generalised_newtonian_navier_stokes_elements.h.
viscosity_ratio()
template<unsigned DIM>
const double & GeneralisedNewtonianNavierStokesEquations< DIM >::viscosity_ratio () const [inline]
Viscosity ratio for element: Element's viscosity relative to the viscosity used in the definition of the Reynolds number.
Definition at line 461 of file generalised_newtonian_navier_stokes_elements.h.
viscosity_ratio_pt()
template<unsigned DIM>
double *& GeneralisedNewtonianNavierStokesEquations< DIM >::viscosity_ratio_pt () [inline]
Pointer to Viscosity Ratio.
Definition at line 467 of file generalised_newtonian_navier_stokes_elements.h.
Member Data Documentation
ALE_is_disabled
template<unsigned DIM>
bool GeneralisedNewtonianNavierStokesEquations< DIM >::ALE_is_disabled [protected]
Boolean flag to indicate if ALE formulation is disabled when time-derivatives are computed. Only set to true if you're sure that the mesh is stationary.
Definition at line 208 of file generalised_newtonian_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::further_build().
Body_force_fct_pt
template<unsigned DIM>
NavierStokesBodyForceFctPt GeneralisedNewtonianNavierStokesEquations< DIM >::Body_force_fct_pt [protected]
Pointer to body force function.
Definition at line 193 of file generalised_newtonian_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::further_build().
Constitutive_eqn_pt
template<unsigned DIM>
GeneralisedNewtonianConstitutiveEquation<DIM>* GeneralisedNewtonianNavierStokesEquations< DIM >::Constitutive_eqn_pt [protected]
Pointer to the generalised Newtonian constitutive equation.
Definition at line 199 of file generalised_newtonian_navier_stokes_elements.h.
Default_Gravity_vector
template<unsigned DIM>
Vector< double > GeneralisedNewtonianNavierStokesEquations< DIM >::Default_Gravity_vector [static], [private]
Static default value for the gravity vector.
Navier-Stokes equations default gravity vector.
Definition at line 160 of file generalised_newtonian_navier_stokes_elements.h.
Default_Physical_Constant_Value
template<unsigned DIM>
double GeneralisedNewtonianNavierStokesEquations< DIM >::Default_Physical_Constant_Value = 0.0 [static], [private]
Static default value for the physical constants (all initialised to zero)
Navier--Stokes equations static data.
Definition at line 153 of file generalised_newtonian_navier_stokes_elements.h.
Default_Physical_Ratio_Value
template<unsigned DIM>
double GeneralisedNewtonianNavierStokesEquations< DIM >::Default_Physical_Ratio_Value = 1.0 [static], [private]
Static default value for the physical ratios (all are initialised to one)
Navier--Stokes equations static data.
Definition at line 157 of file generalised_newtonian_navier_stokes_elements.h.
Density_Ratio_pt
template<unsigned DIM>
double* GeneralisedNewtonianNavierStokesEquations< DIM >::Density_Ratio_pt [protected]
Pointer to the density ratio (relative to the density used in the definition of the Reynolds number)
Definition at line 175 of file generalised_newtonian_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::further_build().
G_pt
template<unsigned DIM>
Vector<double>* GeneralisedNewtonianNavierStokesEquations< DIM >::G_pt [protected]
Pointer to global gravity Vector.
Definition at line 190 of file generalised_newtonian_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::further_build().
Gamma
template<unsigned DIM>
Vector< double > GeneralisedNewtonianNavierStokesEquations< DIM >::Gamma [static]
Vector to decide whether the stress-divergence form is used or not.
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
Navier--Stokes equations static data
Definition at line 431 of file generalised_newtonian_navier_stokes_elements.h.
Pre_multiply_by_viscosity_ratio
template<unsigned DIM>
bool GeneralisedNewtonianNavierStokesEquations< DIM >::Pre_multiply_by_viscosity_ratio = false [static], [protected]
Static boolean telling us whether we pre-multiply the pressure and continuity by the viscosity ratio.
By default disable the pre-multiplication of the pressure and continuity equation by the viscosity ratio.
Definition at line 165 of file generalised_newtonian_navier_stokes_elements.h.
Pressure_not_stored_at_node
template<unsigned DIM>
int GeneralisedNewtonianNavierStokesEquations< DIM >::Pressure_not_stored_at_node = -100 [static], [private]
Static `magic` number that indicates that the pressure is not stored at a node.
`Magic` negative number that indicates that the pressure is not stored at a node. This cannot be -1 because that represents the positional hanging scheme in the hanging_pt object of nodes
Definition at line 149 of file generalised_newtonian_navier_stokes_elements.h.
Re_pt
template<unsigned DIM>
double* GeneralisedNewtonianNavierStokesEquations< DIM >::Re_pt [protected]
Pointer to global Reynolds number.
Definition at line 180 of file generalised_newtonian_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::further_build().
ReInvFr_pt
template<unsigned DIM>
double* GeneralisedNewtonianNavierStokesEquations< DIM >::ReInvFr_pt [protected]
Pointer to global Reynolds number x inverse Froude number (= Bond number / Capillary number)
Definition at line 187 of file generalised_newtonian_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::further_build().
ReSt_pt
template<unsigned DIM>
double* GeneralisedNewtonianNavierStokesEquations< DIM >::ReSt_pt [protected]
Pointer to global Reynolds number x Strouhal number (=Womersley)
Definition at line 183 of file generalised_newtonian_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::further_build().
Source_fct_pt
template<unsigned DIM>
NavierStokesSourceFctPt GeneralisedNewtonianNavierStokesEquations< DIM >::Source_fct_pt [protected]
Pointer to volumetric source function.
Definition at line 196 of file generalised_newtonian_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::further_build().
Use_extrapolated_strainrate_to_compute_second_invariant
template<unsigned DIM>
bool GeneralisedNewtonianNavierStokesEquations< DIM >::Use_extrapolated_strainrate_to_compute_second_invariant [protected]
Definition at line 203 of file generalised_newtonian_navier_stokes_elements.h.
Viscosity_Ratio_pt
template<unsigned DIM>
double* GeneralisedNewtonianNavierStokesEquations< DIM >::Viscosity_Ratio_pt [protected]
Pointer to the viscosity ratio (relative to the viscosity used in the definition of the Reynolds number)
Definition at line 171 of file generalised_newtonian_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::further_build().
The documentation for this class was generated from the following files:
generalised_newtonian_navier_stokes_elements.h
generalised_newtonian_navier_stokes_elements.cc