oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT > Class Template Reference
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
#include <pml_fourier_decomposed_helmholtz_flux_elements.h>
Public Member Functions
PMLFourierDecomposedHelmholtzPowerMonitorElement (FiniteElement *const &bulk_el_pt, const int &face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to which the element is attached.
PMLFourierDecomposedHelmholtzPowerMonitorElement ()
Broken empty constructor.
PMLFourierDecomposedHelmholtzPowerMonitorElement (const PMLFourierDecomposedHelmholtzPowerMonitorElement &dummy)=delete
Broken copy constructor.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Broken assignment operator.
void output (std::ostream &outfile)
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
void output (std::ostream &outfile, const unsigned &n_plot)
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
void output (FILE *file_pt)
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
virtual std::complex< unsigned > u_index_pml_fourier_decomposed_helmholtz () const
Return the index at which the real/imag unknown value is stored.
double global_power_contribution ()
Compute the element's contribution to the time-averaged radiated power over the artificial boundary. NOTE: This may give the wrong result if the constitutive parameters genuinely vary!
double global_power_contribution (std::ofstream &outfile)
Compute the element's contribution to the time-averaged radiated power over the artificial boundary. Also output the power density as a fct of the zenith angle in the specified output file if it's open. NOTE: This may give the wrong result if the constitutive parameters genuinely vary!
Protected Member Functions
double shape_and_test (const Vector< double > &s, Shape &psi, Shape &test) const
Function to compute the test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
double d_shape_and_test_local (const Vector< double > &s, Shape &psi, Shape &test, DShape &dpsi_ds, DShape &dtest_ds) const
Function to compute the shape, test functions and derivates and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Protected Attributes
std::complex< unsigned > U_index_pml_fourier_decomposed_helmholtz
The index at which the real and imag part of the unknown is stored at the nodes.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
A class for elements that allow postprocessing of the results -- currently computes radiated power over domain boundaries. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
Definition at line 407 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
Constructor & Destructor Documentation
PMLFourierDecomposedHelmholtzPowerMonitorElement() [1/3]
template<class ELEMENT >
oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::PMLFourierDecomposedHelmholtzPowerMonitorElement (FiniteElement *const & bulk_el_pt, const int & face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to which the element is attached.
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
Constructor, takes the pointer to the `bulk` element and the face index.
Definition at line 697 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FaceElement::face_index(), oomph::Global_string_for_annotation::string(), oomph::PMLFourierDecomposedHelmholtzEquations::u_index_pml_fourier_decomposed_helmholtz(), and oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::U_index_pml_fourier_decomposed_helmholtz.
PMLFourierDecomposedHelmholtzPowerMonitorElement() [2/3]
template<class ELEMENT >
oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::PMLFourierDecomposedHelmholtzPowerMonitorElement () [inline]
Broken empty constructor.
Definition at line 418 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
PMLFourierDecomposedHelmholtzPowerMonitorElement() [3/3]
template<class ELEMENT >
oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::PMLFourierDecomposedHelmholtzPowerMonitorElement (const PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
d_shape_and_test_local()
template<class ELEMENT >
double oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::d_shape_and_test_local (const Vector< double > & s, Shape & psi, Shape & test, DShape & dpsi_ds, DShape & dtest_ds) const [inline], [protected]
Function to compute the shape, test functions and derivates and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 657 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FiniteElement::dshape_local(), i, oomph::FaceElement::J_eulerian(), oomph::FiniteElement::nnode(), and s.
global_power_contribution() [1/2]
template<class ELEMENT >
double oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution () [inline]
Compute the element's contribution to the time-averaged radiated power over the artificial boundary. NOTE: This may give the wrong result if the constitutive parameters genuinely vary!
Definition at line 491 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution().
Referenced by oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution().
global_power_contribution() [2/2]
template<class ELEMENT >
double oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution (std::ofstream & outfile) [inline]
Compute the element's contribution to the time-averaged radiated power over the artificial boundary. Also output the power density as a fct of the zenith angle in the specified output file if it's open. NOTE: This may give the wrong result if the constitutive parameters genuinely vary!
Definition at line 503 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FaceElement::bulk_element_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::FaceElement::J_eulerian(), oomph::Integral::knot(), oomph::FaceElement::local_coordinate_in_bulk(), oomph::Node::ndim(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), oomph::MathematicalConstants::Pi, s, oomph::FiniteElement::shape(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::u_index_pml_fourier_decomposed_helmholtz(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
output() [1/4]
template<class ELEMENT >
void oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 464 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<class ELEMENT >
void oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 472 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FiniteElement::output().
output() [3/4]
template<class ELEMENT >
void oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 450 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<class ELEMENT >
void oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 457 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::FiniteElement::output().
shape_and_test()
template<class ELEMENT >
double oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::shape_and_test (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 636 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References i, oomph::FaceElement::J_eulerian(), oomph::FiniteElement::nnode(), s, and oomph::FiniteElement::shape().
u_index_pml_fourier_decomposed_helmholtz()
template<class ELEMENT >
virtual std::complex< unsigned > oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::u_index_pml_fourier_decomposed_helmholtz () const [inline], [virtual]
Return the index at which the real/imag unknown value is stored.
Definition at line 479 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::U_index_pml_fourier_decomposed_helmholtz.
Referenced by oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution().
zeta_nodal()
template<class ELEMENT >
double oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
Broken assignment operator.
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Reimplemented from oomph::FaceElement.
Definition at line 440 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
References i, and oomph::FaceElement::zeta_nodal().
Member Data Documentation
U_index_pml_fourier_decomposed_helmholtz
template<class ELEMENT >
std::complex<unsigned> oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::U_index_pml_fourier_decomposed_helmholtz [protected]
The index at which the real and imag part of the unknown is stored at the nodes.
Definition at line 684 of file pml_fourier_decomposed_helmholtz_flux_elements.h.
Referenced by oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::PMLFourierDecomposedHelmholtzPowerMonitorElement(), and oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::u_index_pml_fourier_decomposed_helmholtz().
The documentation for this class was generated from the following file:
pml_fourier_decomposed_helmholtz_flux_elements.h