oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM > Class Template Reference
A version of the Advection Diffusion Reaction equations that can be used with non-uniform mesh refinement. In essence, the class overloads the fill_in_generic_residual_contribution_adv_diff_react() function so that contributions from hanging nodes (or alternatively in-compatible function values) are taken into account.
#include <refineable_advection_diffusion_reaction_elements.h>
Public Member Functions
RefineableAdvectionDiffusionReactionEquations ()
Empty Constructor.
RefineableAdvectionDiffusionReactionEquations (const RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM > &dummy)
Broken copy constructor.
void operator= (const RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM > &)
Broken assignment operator.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Standard flux.from AdvectionDiffusionReaction equations.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function values c in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function values c in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void further_build ()
Protected Member Functions
void fill_in_generic_residual_contribution_adv_diff_react (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Add the element's contribution to the elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Additional Inherited Members
Detailed Description
template<unsigned NREAGENT, unsigned DIM>
class oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >
A version of the Advection Diffusion Reaction equations that can be used with non-uniform mesh refinement. In essence, the class overloads the fill_in_generic_residual_contribution_adv_diff_react() function so that contributions from hanging nodes (or alternatively in-compatible function values) are taken into account.
Definition at line 54 of file refineable_advection_diffusion_reaction_elements.h.
Constructor & Destructor Documentation
RefineableAdvectionDiffusionReactionEquations() [1/2]
template<unsigned NREAGENT, unsigned DIM>
oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::RefineableAdvectionDiffusionReactionEquations () [inline]
Empty Constructor.
Definition at line 61 of file refineable_advection_diffusion_reaction_elements.h.
RefineableAdvectionDiffusionReactionEquations() [2/2]
template<unsigned NREAGENT, unsigned DIM>
oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::RefineableAdvectionDiffusionReactionEquations (const RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM > & dummy) [inline]
Broken copy constructor.
Definition at line 70 of file refineable_advection_diffusion_reaction_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
fill_in_generic_residual_contribution_adv_diff_react()
template<unsigned NREAGENT, unsigned DIM>
void oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_generic_residual_contribution_adv_diff_react (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [protected], [virtual]
Add the element's contribution to the elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Add the element's contribution to the elemental residual vector and/or elemental jacobian matrix. This function overloads the standard version so that the possible presence of hanging nodes is taken into account.
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
Definition at line 38 of file refineable_advection_diffusion_reaction_elements.cc.
References oomph::ALE_is_disabled, oomph::OcTreeNames::D, i, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::BinaryTreeNames::R, residuals(), s, oomph::ElementGeometry::T, and oomph::QuadTreeNames::W.
further_build()
template<unsigned NREAGENT, unsigned DIM>
void oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::further_build () [inline], [virtual]
Further build: Copy all pointers from the father element
Reimplemented from oomph::RefineableElement.
Definition at line 171 of file refineable_advection_diffusion_reaction_elements.h.
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::ALE_is_disabled, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::diff_pt(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Diff_pt, oomph::RefineableElement::father_element_pt(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::reaction_deriv_fct_pt(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Reaction_deriv_fct_pt, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::reaction_fct_pt(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Reaction_fct_pt, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::source_fct_pt(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Source_fct_pt, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::tau_pt(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Tau_pt, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::wind_fct_pt(), and oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Wind_fct_pt.
get_interpolated_values() [1/2]
template<unsigned NREAGENT, unsigned DIM>
void oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function values c in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 137 of file refineable_advection_diffusion_reaction_elements.h.
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::c_index_adv_diff_react(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and values.
get_interpolated_values() [2/2]
template<unsigned NREAGENT, unsigned DIM>
void oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function values c in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 102 of file refineable_advection_diffusion_reaction_elements.h.
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::c_index_adv_diff_react(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and values.
get_Z2_flux()
template<unsigned NREAGENT, unsigned DIM>
void oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Standard flux.from AdvectionDiffusionReaction equations.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 92 of file refineable_advection_diffusion_reaction_elements.h.
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_flux().
num_Z2_flux_terms()
template<unsigned NREAGENT, unsigned DIM>
unsigned oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 85 of file refineable_advection_diffusion_reaction_elements.h.
operator=()
template<unsigned NREAGENT, unsigned DIM>
void oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::operator= (const RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM > &) [inline]
Broken assignment operator.
Definition at line 77 of file refineable_advection_diffusion_reaction_elements.h.
References oomph::BrokenCopy::broken_assign().
The documentation for this class was generated from the following files:
refineable_advection_diffusion_reaction_elements.h
refineable_advection_diffusion_reaction_elements.cc