oomph::BellElement< DIM, NNODE_1D > Class Template Reference
#include <Subparametric_Telements.h>
Public Member Functions
BellElement ()
Constructor: Call constructors for BellElement.
BellElement (const BellElement &)
Broken copy constructor.
void operator= (const BellElement &)
Broken assignment operator.
void shape (const Vector< double > &s, Shape &psi) const
Calculate the geometric shape functions at local coordinate s.
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Compute the geometric shape functions and derivatives w.r.t. local coordinates at local coordinate s.
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
Computer the geometric shape functions, derivatives and second derivatives w.r.t local coordinates at local coordinate s
d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $
d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $
d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $
.
void basis (const Vector< double > &s, Shape &psi) const
Calculate the c1-basis functions at local coordinate s.
void dbasis_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Compute the c1-basis functions and derivatives w.r.t. global coordinates at local coordinate s.
void d2basis_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
Compute the c1-basis functions and derivatives w.r.t. global coordinates at local coordinate s.
void basis_c0 (const Vector< double > &s, Shape &psi) const
Calculate the c0-basis functions at local coordinate s.
void dbasis_c0_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Compute the c0-basis functions and derivatives w.r.t. local coordinates at local coordinate s.
void d2basis_c0_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
Computer the c0-basis functions, derivatives and second derivatives w.r.t local coordinates at local coordinate s
d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $
d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $
d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $
.
void test (const Vector< double > &s, Shape &psi) const
Calculate the test functions at local coordinate s.
void dtest_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Compute the test functions and derivatives w.r.t. local coordinates at local coordinate s.
void d2test_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
Computer the test functions, derivatives and second derivatives w.r.t local coordinates at local coordinate s
d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $
d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $
d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $
.
Additional Inherited Members
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::BellElement< DIM, NNODE_1D >
General BellElement class /// Empty, just establishes the template parameters
Definition at line 5661 of file Subparametric_Telements.h.
Constructor & Destructor Documentation
BellElement() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::BellElement< DIM, NNODE_1D >::BellElement () [inline]
Constructor: Call constructors for BellElement.
Definition at line 5668 of file Subparametric_Telements.h.
References oomph::FiniteElement::set_integration_scheme(), and oomph::FiniteElement::set_nnodal_position_type().
BellElement() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::BellElement< DIM, NNODE_1D >::BellElement (const BellElement< DIM, NNODE_1D > &) [inline]
Broken copy constructor.
Definition at line 5681 of file Subparametric_Telements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
basis()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::BellElement< DIM, NNODE_1D >::basis (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Calculate the c1-basis functions at local coordinate s.
Number of nodes along each element edge
Reimplemented from oomph::BellElementBase< NNODE_1D >.
Definition at line 5721 of file Subparametric_Telements.h.
References oomph::FiniteElement::raw_nodal_position_gen(), and s.
basis_c0()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::BellElement< DIM, NNODE_1D >::basis_c0 (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Calculate the c0-basis functions at local coordinate s.
Reimplemented from oomph::BellElementBase< NNODE_1D >.
Definition at line 5790 of file Subparametric_Telements.h.
References s, and oomph::OneDimLagrange::shape().
d2basis_c0_local()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::BellElement< DIM, NNODE_1D >::d2basis_c0_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline], [virtual]
Computer the c0-basis functions, derivatives and second derivatives w.r.t local coordinates at local coordinate s
d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $
d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $
d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $
.
Reimplemented from oomph::BellElementBase< NNODE_1D >.
Definition at line 5809 of file Subparametric_Telements.h.
References s.
d2basis_local()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::BellElement< DIM, NNODE_1D >::d2basis_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline], [virtual]
Compute the c1-basis functions and derivatives w.r.t. global coordinates at local coordinate s.
Number of nodes along each element edge
Reimplemented from oomph::BellElementBase< NNODE_1D >.
Definition at line 5766 of file Subparametric_Telements.h.
References oomph::FiniteElement::raw_nodal_position_gen(), and s.
d2shape_local()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::BellElement< DIM, NNODE_1D >::d2shape_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline], [virtual]
Computer the geometric shape functions, derivatives and second derivatives w.r.t local coordinates at local coordinate s
d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $
d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $
d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $
.
Reimplemented from oomph::FiniteElement.
Definition at line 5712 of file Subparametric_Telements.h.
References s.
d2test_local()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::BellElement< DIM, NNODE_1D >::d2test_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline], [virtual]
Computer the test functions, derivatives and second derivatives w.r.t local coordinates at local coordinate s
d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $
d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $
d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $
.
Reimplemented from oomph::BellElementBase< NNODE_1D >.
Definition at line 5837 of file Subparametric_Telements.h.
References s.
dbasis_c0_local()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::BellElement< DIM, NNODE_1D >::dbasis_c0_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const [inline], [virtual]
Compute the c0-basis functions and derivatives w.r.t. local coordinates at local coordinate s.
Reimplemented from oomph::BellElementBase< NNODE_1D >.
Definition at line 5797 of file Subparametric_Telements.h.
References s.
dbasis_local()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::BellElement< DIM, NNODE_1D >::dbasis_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const [inline], [virtual]
Compute the c1-basis functions and derivatives w.r.t. global coordinates at local coordinate s.
Number of nodes along each element edge
Reimplemented from oomph::BellElementBase< NNODE_1D >.
Definition at line 5742 of file Subparametric_Telements.h.
References oomph::FiniteElement::raw_nodal_position_gen(), and s.
dshape_local()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::BellElement< DIM, NNODE_1D >::dshape_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const [inline], [virtual]
Compute the geometric shape functions and derivatives w.r.t. local coordinates at local coordinate s.
Reimplemented from oomph::FiniteElement.
Definition at line 5700 of file Subparametric_Telements.h.
References s.
dtest_local()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::BellElement< DIM, NNODE_1D >::dtest_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const [inline], [virtual]
Compute the test functions and derivatives w.r.t. local coordinates at local coordinate s.
Reimplemented from oomph::BellElementBase< NNODE_1D >.
Definition at line 5825 of file Subparametric_Telements.h.
References s.
operator=()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::BellElement< DIM, NNODE_1D >::operator= (const BellElement< DIM, NNODE_1D > &) [inline]
Broken assignment operator.
Definition at line 5687 of file Subparametric_Telements.h.
References oomph::BrokenCopy::broken_assign().
shape()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::BellElement< DIM, NNODE_1D >::shape (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Calculate the geometric shape functions at local coordinate s.
Implements oomph::FiniteElement.
Definition at line 5693 of file Subparametric_Telements.h.
References s.
test()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::BellElement< DIM, NNODE_1D >::test (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Calculate the test functions at local coordinate s.
Reimplemented from oomph::BellElementBase< NNODE_1D >.
Definition at line 5818 of file Subparametric_Telements.h.
References s, and oomph::OneDimLagrange::shape().
The documentation for this class was generated from the following file:
Subparametric_Telements.h