oomph::SolidTetgenMesh< ELEMENT > Class Template Reference
/////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////
#include <tetgen_mesh.template.h>
Public Member Functions
SolidTetgenMesh (const std::string &node_file_name, const std::string &element_file_name, const std::string &face_file_name, const bool &split_corner_elements, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false)
Constructor. Boundary coordinates are setup automatically.
SolidTetgenMesh (const std::string &node_file_name, const std::string &element_file_name, const std::string &face_file_name, const bool &split_corner_elements, const bool &switch_normal, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false)
Constructor. Boundary coordinates are re-setup automatically, with the orientation of the outer unit normal determined by switch_normal.
virtual ~SolidTetgenMesh ()
Empty Destructor.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::SolidTetgenMesh< ELEMENT >
/////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////
Tetgen-based mesh upgraded to become a solid mesh. Automatically enumerates all boundaries.
Definition at line 739 of file tetgen_mesh.template.h.
Constructor & Destructor Documentation
SolidTetgenMesh() [1/2]
template<class ELEMENT >
oomph::SolidTetgenMesh< ELEMENT >::SolidTetgenMesh (const std::string & node_file_name, const std::string & element_file_name, const std::string & face_file_name, const bool & split_corner_elements, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false) [inline]
Constructor. Boundary coordinates are setup automatically.
Definition at line 745 of file tetgen_mesh.template.h.
References oomph::SolidMesh::set_lagrangian_nodal_coordinates().
SolidTetgenMesh() [2/2]
template<class ELEMENT >
oomph::SolidTetgenMesh< ELEMENT >::SolidTetgenMesh (const std::string & node_file_name, const std::string & element_file_name, const std::string & face_file_name, const bool & split_corner_elements, const bool & switch_normal, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false) [inline]
Constructor. Boundary coordinates are re-setup automatically, with the orientation of the outer unit normal determined by switch_normal.
Definition at line 765 of file tetgen_mesh.template.h.
References oomph::Mesh::nboundary(), and oomph::SolidMesh::set_lagrangian_nodal_coordinates().
 SolidTetgenMesh()
template<class ELEMENT >
virtual oomph::SolidTetgenMesh< ELEMENT >::~SolidTetgenMesh () [inline], [virtual]
Empty Destructor.
Definition at line 792 of file tetgen_mesh.template.h.
The documentation for this class was generated from the following file:
tetgen_mesh.template.h