SpaceTimeNavierStokesEquations< DIM > Class Template Reference
and
#include <discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h>
Public Types
typedef void(* NavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
Function pointer to body force function fct(t,x,f(x)) x is a Vector!
typedef double(* NavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
Function pointer to source function fct(t,x) (x is a Vector!)
typedef double(* NavierStokesPressureAdvDiffSourceFctPt) (const Vector< double > &x)
Function pointer to source function fct(x) for the pressure advection diffusion equation (only used during validation!). x is a Vector!
typedef void(* NavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
Function pointer to body force function fct(t,x,f(x)) x is a Vector!
typedef double(* NavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
Function pointer to source function fct(t,x) (x is a Vector!)
typedef double(* NavierStokesPressureAdvDiffSourceFctPt) (const Vector< double > &x)
Function pointer to source function fct(x) for the pressure advection diffusion equation (only used during validation!). x is a Vector!
typedef void(* NavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
Function pointer to body force function fct(t,x,f(x)) x is a Vector!
typedef double(* NavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
Function pointer to source function fct(t,x) (x is a Vector!)
typedef double(* NavierStokesPressureAdvDiffSourceFctPt) (const Vector< double > &x)
Function pointer to source function fct(x) for the pressure advection diffusion equation (only used during validation!). x is a Vector!
Public Member Functions
SpaceTimeNavierStokesEquations ()
Constructor: NULL the body force and source function and make sure the ALE terms are included by default.
void store_strouhal_as_external_data (Data *strouhal_data_pt)
Function that tells us whether the period is stored as external data.
const double & re () const
Reynolds number.
double *& re_pt ()
Pointer to Reynolds number.
bool is_strouhal_stored_as_external_data () const
Are we storing the Strouhal number as external data?
const double & st () const
Strouhal parameter (const. version)
double * st_pt () const
Pointer to Strouhal parameter (const. version)
double *& st_pt ()
Pointer to Strouhal number (can only assign to private member data)
double re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
const double & viscosity_ratio () const
Viscosity ratio for element: Element's viscosity relative to the viscosity used in the definition of the Reynolds number.
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
Density ratio for element: Element's density relative to the viscosity used in the definition of the Reynolds number.
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
NavierStokesBodyForceFctPt & body_force_fct_pt ()
Access function for the body-force pointer.
NavierStokesBodyForceFctPt body_force_fct_pt () const
Access function for the body-force pointer. Const version.
NavierStokesSourceFctPt & source_fct_pt ()
Access function for the source-function pointer.
NavierStokesSourceFctPt source_fct_pt () const
Access function for the source-function pointer. Const version.
NavierStokesPressureAdvDiffSourceFctPt & source_fct_for_pressure_adv_diff ()
Access function for the source-function pointer for pressure advection diffusion (used for validation only).
NavierStokesPressureAdvDiffSourceFctPt source_fct_for_pressure_adv_diff () const
Access function for the source-function pointer for pressure advection diffusion (used for validation only). Const version.
int & pinned_fp_pressure_eqn ()
Global eqn number of pressure dof that's pinned in pressure adv diff problem.
virtual unsigned npres_nst () const =0
Function to return number of pressure degrees of freedom.
virtual void pshape_nst (const Vector< double > &s, Shape &psi) const =0
Compute the pressure shape functions at local coordinate s.
virtual void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const =0
Compute the pressure shape and test functions at local coordinate s.
double u_nst (const unsigned &n, const unsigned &i) const
Velocity i at local node n. Uses suitably interpolated value for hanging nodes. The use of u_index_nst() permits the use of this element as the basis for multi-physics elements. The default is to assume that the i-th velocity component is stored at the i-th location of the node.
double u_nst (const unsigned &t, const unsigned &n, const unsigned &i) const
Velocity i at local node n at timestep t (t=0: present; t>0: previous). Uses suitably interpolated value for hanging nodes.
virtual unsigned u_index_nst (const unsigned &i) const
Return the index at which the i-th unknown velocity component is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
unsigned n_u_nst () const
Return the number of velocity components (used in FluidInterfaceElements)
double get_du_dt (const unsigned &n, const unsigned &i) const
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes. NOTE: This is essentially a wrapper for du_dt_nst() so it can be called externally.
double du_dt_nst (const unsigned &n, const unsigned &i) const
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
double interpolated_du_dt_nst (const Vector< double > &s, const unsigned &i) const
Return FE representation of function value du_i/dt(s) at local coordinate s.
void disable_ALE ()
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
void enable_ALE ()
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
virtual double p_nst (const unsigned &n_p) const =0
Pressure at local pressure `node` n_p Uses suitably interpolated value for hanging nodes.
virtual double p_nst (const unsigned &t, const unsigned &n_p) const =0
Pressure at local pressure `node` n_p at time level t.
virtual void fix_pressure (const unsigned &p_dof, const double &p_value)=0
Pin p_dof-th pressure dof and set it to value specified by p_value.
virtual int p_nodal_index_nst () const
Return the index at which the pressure is stored if it is stored at the nodes. If not stored at the nodes this will return a negative number.
double pressure_integral () const
Integral of pressure over element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute the vorticity vector at local coordinate s.
void get_vorticity (const Vector< double > &s, double &vorticity) const
Compute the vorticity vector at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
double d_kin_energy_dt () const
Get integral of time derivative of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j+du_j/dx_i)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s. N has to be outer unit normal to the fluid.
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction_p, Vector< double > &traction_visc_n, Vector< double > &traction_visc_t)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s, decomposed into pressure and normal and tangential viscous components. N has to be outer unit normal to the fluid.
void get_load (const Vector< double > &s, const Vector< double > &N, Vector< double > &load)
This implements a pure virtual function defined in the FSIFluidElement class. The function computes the traction (on the viscous scale), at the element's local coordinate s, that the fluid element exerts onto an adjacent solid element. The number of arguments is imposed by the interface defined in the FSIFluidElement -- only the unit normal N (pointing into the fluid!) is actually used in the computation.
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
unsigned nscalar_paraview () const
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
std::string scalar_name_paraview (const unsigned &i) const
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
void output (std::ostream &outfile)
Output function: x,y,t,u,v,p in tecplot format. The default number of plot points is five.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,[z],u,v,[w],p in tecplot format. Here, we use n_plot plot points in each coordinate direction.
void output (FILE *file_pt)
C-style output function: x,y,[z],u,v,[w],p in tecplot format. The default number of plot points is five.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,[z],u,v,[w],p in tecplot format. Use n_plot points in each coordinate direction.
void full_output (std::ostream &outfile)
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. The default number of plot points is five.
void full_output (std::ostream &outfile, const unsigned &n_plot)
Full output function: x,y,t,u,v,p,du/dt,dv/dt,dissipation in tecplot format. Use n_plot plot points in each coordinate direction.
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
Output function: x,y,t,u,v in tecplot format. Use n_plot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
void output_vorticity (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,t,omega in tecplot format. nplot points in each coordinate direction.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given number of plot points. Function prints as many components as are returned in solution Vector.
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given time and at a given number of plot points. Function prints as many components as are returned in solution Vector.
void compute_norm (Vector< double > &norm)
Compute the vector norm of the FEM solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Compute the element's residual Vector (differentiated w.r.t. a parameter)
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void fill_in_pressure_advection_diffusion_residuals (Vector< double > &residuals)
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
void fill_in_pressure_advection_diffusion_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the residuals and Jacobian for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
void pin_all_non_pressure_dofs (std::map< Data *, std::vector< int > > &eqn_number_backup)
Pin all non-pressure dofs and backup eqn numbers.
virtual void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)=0
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void output_pressure_advection_diffusion_robin_elements (std::ostream &outfile)
Output the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void delete_pressure_advection_diffusion_robin_elements ()
Delete the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j)=d res(l) / dX_{ij}.
void interpolated_u_nst (const Vector< double > &s, Vector< double > &velocity) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s time level, t. Purposely broken for space-time elements.
virtual void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. The function is virtual so that it can be overloaded in the refineable version.
virtual double interpolated_p_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_p_nst (const unsigned &t, const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s at time level t.
void point_output_data (const Vector< double > &s, Vector< double > &data)
Output solution in data vector at local cordinates s: x,y,z,u,v,p.
SpaceTimeNavierStokesEquations ()
Constructor: NULL the body force and source function and make sure the ALE terms are included by default.
void store_strouhal_as_external_data (Data *strouhal_data_pt)
Function that tells us whether the period is stored as external data.
const double & re () const
Reynolds number.
double *& re_pt ()
Pointer to Reynolds number.
bool is_strouhal_stored_as_external_data () const
Are we storing the Strouhal number as external data?
const double & st () const
Strouhal parameter (const. version)
double * st_pt () const
Pointer to Strouhal parameter (const. version)
double *& st_pt ()
Pointer to Strouhal number (can only assign to private member data)
double re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
const double & viscosity_ratio () const
Viscosity ratio for element: Element's viscosity relative to the viscosity used in the definition of the Reynolds number.
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
Density ratio for element: Element's density relative to the viscosity used in the definition of the Reynolds number.
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
NavierStokesBodyForceFctPt & body_force_fct_pt ()
Access function for the body-force pointer.
NavierStokesBodyForceFctPt body_force_fct_pt () const
Access function for the body-force pointer. Const version.
NavierStokesSourceFctPt & source_fct_pt ()
Access function for the source-function pointer.
NavierStokesSourceFctPt source_fct_pt () const
Access function for the source-function pointer. Const version.
NavierStokesPressureAdvDiffSourceFctPt & source_fct_for_pressure_adv_diff ()
Access function for the source-function pointer for pressure advection diffusion (used for validation only).
NavierStokesPressureAdvDiffSourceFctPt source_fct_for_pressure_adv_diff () const
Access function for the source-function pointer for pressure advection diffusion (used for validation only). Const version.
int & pinned_fp_pressure_eqn ()
Global eqn number of pressure dof that's pinned in pressure adv diff problem.
virtual unsigned npres_nst () const =0
Function to return number of pressure degrees of freedom.
virtual void pshape_nst (const Vector< double > &s, Shape &psi) const =0
Compute the pressure shape functions at local coordinate s.
virtual void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const =0
Compute the pressure shape and test functions at local coordinate s.
double u_nst (const unsigned &n, const unsigned &i) const
Velocity i at local node n. Uses suitably interpolated value for hanging nodes. The use of u_index_nst() permits the use of this element as the basis for multi-physics elements. The default is to assume that the i-th velocity component is stored at the i-th location of the node.
double u_nst (const unsigned &t, const unsigned &n, const unsigned &i) const
Velocity i at local node n at timestep t (t=0: present; t>0: previous). Uses suitably interpolated value for hanging nodes.
virtual unsigned u_index_nst (const unsigned &i) const
Return the index at which the i-th unknown velocity component is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
unsigned n_u_nst () const
Return the number of velocity components (used in FluidInterfaceElements)
double get_du_dt (const unsigned &n, const unsigned &i) const
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes. NOTE: This is essentially a wrapper for du_dt_nst() so it can be called externally.
double du_dt_nst (const unsigned &n, const unsigned &i) const
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
double interpolated_du_dt_nst (const Vector< double > &s, const unsigned &i) const
Return FE representation of function value du_i/dt(s) at local coordinate s.
void disable_ALE ()
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
void enable_ALE ()
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
virtual double p_nst (const unsigned &n_p) const =0
Pressure at local pressure `node` n_p Uses suitably interpolated value for hanging nodes.
virtual double p_nst (const unsigned &t, const unsigned &n_p) const =0
Pressure at local pressure `node` n_p at time level t.
virtual void fix_pressure (const unsigned &p_dof, const double &p_value)=0
Pin p_dof-th pressure dof and set it to value specified by p_value.
virtual int p_nodal_index_nst () const
Return the index at which the pressure is stored if it is stored at the nodes. If not stored at the nodes this will return a negative number.
double pressure_integral () const
Integral of pressure over element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute the vorticity vector at local coordinate s.
void get_vorticity (const Vector< double > &s, double &vorticity) const
Compute the vorticity vector at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
double d_kin_energy_dt () const
Get integral of time derivative of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j+du_j/dx_i)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s. N has to be outer unit normal to the fluid.
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction_p, Vector< double > &traction_visc_n, Vector< double > &traction_visc_t)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s, decomposed into pressure and normal and tangential viscous components. N has to be outer unit normal to the fluid.
void get_load (const Vector< double > &s, const Vector< double > &N, Vector< double > &load)
This implements a pure virtual function defined in the FSIFluidElement class. The function computes the traction (on the viscous scale), at the element's local coordinate s, that the fluid element exerts onto an adjacent solid element. The number of arguments is imposed by the interface defined in the FSIFluidElement -- only the unit normal N (pointing into the fluid!) is actually used in the computation.
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
unsigned nscalar_paraview () const
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
std::string scalar_name_paraview (const unsigned &i) const
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
void output (std::ostream &outfile)
Output function: x,y,t,u,v,p in tecplot format. The default number of plot points is five.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,[z],u,v,[w],p in tecplot format. Here, we use n_plot plot points in each coordinate direction.
void output (FILE *file_pt)
C-style output function: x,y,[z],u,v,[w],p in tecplot format. The default number of plot points is five.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,[z],u,v,[w],p in tecplot format. Use n_plot points in each coordinate direction.
void full_output (std::ostream &outfile)
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. The default number of plot points is five.
void full_output (std::ostream &outfile, const unsigned &n_plot)
Full output function: x,y,t,u,v,p,du/dt,dv/dt,dissipation in tecplot format. Use n_plot plot points in each coordinate direction.
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
Output function: x,y,t,u,v in tecplot format. Use n_plot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
void output_vorticity (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,t,omega in tecplot format. nplot points in each coordinate direction.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given number of plot points. Function prints as many components as are returned in solution Vector.
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given time and at a given number of plot points. Function prints as many components as are returned in solution Vector.
void compute_norm (Vector< double > &norm)
Compute the vector norm of the FEM solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Compute the element's residual Vector (differentiated w.r.t. a parameter)
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void fill_in_pressure_advection_diffusion_residuals (Vector< double > &residuals)
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
void fill_in_pressure_advection_diffusion_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the residuals and Jacobian for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
void pin_all_non_pressure_dofs (std::map< Data *, std::vector< int > > &eqn_number_backup)
Pin all non-pressure dofs and backup eqn numbers.
virtual void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)=0
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void output_pressure_advection_diffusion_robin_elements (std::ostream &outfile)
Output the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void delete_pressure_advection_diffusion_robin_elements ()
Delete the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j)=d res(l) / dX_{ij}.
void interpolated_u_nst (const Vector< double > &s, Vector< double > &velocity) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s time level, t. Purposely broken for space-time elements.
virtual void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. The function is virtual so that it can be overloaded in the refineable version.
virtual double interpolated_p_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_p_nst (const unsigned &t, const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s at time level t.
void point_output_data (const Vector< double > &s, Vector< double > &data)
Output solution in data vector at local cordinates s: x,y,z,u,v,p.
SpaceTimeNavierStokesEquations ()
Constructor: NULL the body force and source function and make sure the ALE terms are included by default.
void store_strouhal_as_external_data (Data *strouhal_data_pt)
Function that tells us whether the period is stored as external data.
bool is_reynolds_strouhal_stored_as_external_data () const
Are we storing the Strouhal number as external data?
const double & re () const
Reynolds number.
double *& re_pt ()
Pointer to Reynolds number.
const double & re_st () const
ReSt parameter (const. version)
double * re_st_pt () const
Pointer to Strouhal parameter (const. version)
double *& re_st_pt ()
Pointer to ReSt number (can only assign to private member data)
const double & viscosity_ratio () const
Viscosity ratio for element: Element's viscosity relative to the viscosity used in the definition of the Reynolds number.
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
Density ratio for element: Element's density relative to the viscosity used in the definition of the Reynolds number.
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
NavierStokesBodyForceFctPt & body_force_fct_pt ()
Access function for the body-force pointer.
NavierStokesBodyForceFctPt body_force_fct_pt () const
Access function for the body-force pointer. Const version.
NavierStokesSourceFctPt & source_fct_pt ()
Access function for the source-function pointer.
NavierStokesSourceFctPt source_fct_pt () const
Access function for the source-function pointer. Const version.
NavierStokesPressureAdvDiffSourceFctPt & source_fct_for_pressure_adv_diff ()
Access function for the source-function pointer for pressure advection diffusion (used for validation only).
NavierStokesPressureAdvDiffSourceFctPt source_fct_for_pressure_adv_diff () const
Access function for the source-function pointer for pressure advection diffusion (used for validation only). Const version.
int & pinned_fp_pressure_eqn ()
Global eqn number of pressure dof that's pinned in pressure adv diff problem.
virtual unsigned npres_nst () const =0
Function to return number of pressure degrees of freedom.
virtual void pshape_nst (const Vector< double > &s, Shape &psi) const =0
Compute the pressure shape functions at local coordinate s.
virtual void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const =0
Compute the pressure shape and test functions at local coordinate s.
double u_nst (const unsigned &n, const unsigned &i) const
Velocity i at local node n. Uses suitably interpolated value for hanging nodes. The use of u_index_nst() permits the use of this element as the basis for multi-physics elements. The default is to assume that the i-th velocity component is stored at the i-th location of the node.
double u_nst (const unsigned &t, const unsigned &n, const unsigned &i) const
Velocity i at local node n at timestep t (t=0: present; t>0: previous). Uses suitably interpolated value for hanging nodes.
virtual unsigned u_index_nst (const unsigned &i) const
Return the index at which the i-th unknown velocity component is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
unsigned n_u_nst () const
Return the number of velocity components (used in FluidInterfaceElements)
double get_du_dt (const unsigned &n, const unsigned &i) const
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes. NOTE: This is essentially a wrapper for du_dt_nst() so it can be called externally.
double du_dt_nst (const unsigned &n, const unsigned &i) const
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
double interpolated_du_dt_nst (const Vector< double > &s, const unsigned &i) const
Return FE representation of function value du_i/dt(s) at local coordinate s.
void disable_ALE ()
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
void enable_ALE ()
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
virtual double p_nst (const unsigned &n_p) const =0
Pressure at local pressure `node` n_p Uses suitably interpolated value for hanging nodes.
virtual double p_nst (const unsigned &t, const unsigned &n_p) const =0
Pressure at local pressure `node` n_p at time level t.
virtual void fix_pressure (const unsigned &p_dof, const double &p_value)=0
Pin p_dof-th pressure dof and set it to value specified by p_value.
virtual int p_nodal_index_nst () const
Return the index at which the pressure is stored if it is stored at the nodes. If not stored at the nodes this will return a negative number.
double pressure_integral () const
Integral of pressure over element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute the vorticity vector at local coordinate s.
void get_vorticity (const Vector< double > &s, double &vorticity) const
Compute the vorticity vector at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
double d_kin_energy_dt () const
Get integral of time derivative of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j+du_j/dx_i)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s. N has to be outer unit normal to the fluid.
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction_p, Vector< double > &traction_visc_n, Vector< double > &traction_visc_t)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s, decomposed into pressure and normal and tangential viscous components. N has to be outer unit normal to the fluid.
void get_load (const Vector< double > &s, const Vector< double > &N, Vector< double > &load)
This implements a pure virtual function defined in the FSIFluidElement class. The function computes the traction (on the viscous scale), at the element's local coordinate s, that the fluid element exerts onto an adjacent solid element. The number of arguments is imposed by the interface defined in the FSIFluidElement -- only the unit normal N (pointing into the fluid!) is actually used in the computation.
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
unsigned nscalar_paraview () const
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
std::string scalar_name_paraview (const unsigned &i) const
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
void output (std::ostream &outfile)
Output function: x,y,t,u,v,p in tecplot format. The default number of plot points is five.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,[z],u,v,[w],p in tecplot format. Here, we use n_plot plot points in each coordinate direction.
void output (FILE *file_pt)
C-style output function: x,y,[z],u,v,[w],p in tecplot format. The default number of plot points is five.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,[z],u,v,[w],p in tecplot format. Use n_plot points in each coordinate direction.
void full_output (std::ostream &outfile)
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. The default number of plot points is five.
void full_output (std::ostream &outfile, const unsigned &n_plot)
Full output function: x,y,t,u,v,p,du/dt,dv/dt,dissipation in tecplot format. Use n_plot plot points in each coordinate direction.
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
Output function: x,y,t,u,v in tecplot format. Use n_plot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
void output_vorticity (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,t,omega in tecplot format. nplot points in each coordinate direction.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given number of plot points. Function prints as many components as are returned in solution Vector.
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given time and at a given number of plot points. Function prints as many components as are returned in solution Vector.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void compute_norm (Vector< double > &norm)
Compute the vector norm of the FEM solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Compute the element's residual Vector (differentiated w.r.t. a parameter)
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void fill_in_pressure_advection_diffusion_residuals (Vector< double > &residuals)
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
void fill_in_pressure_advection_diffusion_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the residuals and Jacobian for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
void pin_all_non_pressure_dofs (std::map< Data *, std::vector< int > > &eqn_number_backup)
Pin all non-pressure dofs and backup eqn numbers.
virtual void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)=0
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void output_pressure_advection_diffusion_robin_elements (std::ostream &outfile)
Output the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void delete_pressure_advection_diffusion_robin_elements ()
Delete the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j)=d res(l) / dX_{ij}.
void interpolated_u_nst (const Vector< double > &s, Vector< double > &velocity) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s time level, t. Purposely broken for space-time elements.
virtual void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. The function is virtual so that it can be overloaded in the refineable version.
virtual double interpolated_p_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_p_nst (const unsigned &t, const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s at time level t.
void point_output_data (const Vector< double > &s, Vector< double > &data)
Output solution in data vector at local cordinates s: x,y,z,u,v,p.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector.
void get_vorticity (const Vector< double > &s, double &vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector as a double.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector.
void get_vorticity (const Vector< double > &s, double &vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector as a double.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector.
void get_vorticity (const Vector< double > &s, double &vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector as a double.
Static Public Attributes
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not N.B. This needs to be public so that the intel compiler gets things correct somehow the access function messes things up when going to refineable Navier-Stokes.
Protected Member Functions
virtual double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Compute the shape functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
virtual double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Compute the shape functions and derivatives w.r.t. global coords at ipt-th integration point Return Jacobian of mapping between local and global coordinates.
virtual double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
virtual double dpshape_eulerian (const Vector< double > &s, Shape &ppsi, DShape &dppsidx) const =0
Pressure shape functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
virtual double dptest_eulerian (const Vector< double > &s, Shape &ptest, DShape &dptestdx) const =0
Pressure test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
virtual double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const =0
Compute the pressure shape and test functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
virtual void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
Calculate the body force at a given time and local and/or Eulerian position. This function is virtual so that it can be overloaded in multi-physics elements where the body force might depend on another variable.
virtual void get_body_force_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
Get gradient of body force term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
virtual double get_source_nst (const double &time, const unsigned &ipt, const Vector< double > &x)
Calculate the source fct at a given time and Eulerian position.
virtual void get_source_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
Get gradient of source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
virtual void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, const unsigned &flag)
Compute the residuals for the Navier-Stokes equations. Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
virtual void fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
virtual void fill_in_generic_dresidual_contribution_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, const unsigned &flag)
Compute the derivatives of the residuals for the Navier-Stokes equations with respect to a parameter Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Compute the hessian tensor vector products required to perform continuation of bifurcations analytically.
virtual double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Compute the shape functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
virtual double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Compute the shape functions and derivatives w.r.t. global coords at ipt-th integration point Return Jacobian of mapping between local and global coordinates.
virtual double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
virtual double dpshape_eulerian (const Vector< double > &s, Shape &ppsi, DShape &dppsidx) const =0
Pressure shape functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
virtual double dptest_eulerian (const Vector< double > &s, Shape &ptest, DShape &dptestdx) const =0
Pressure test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
virtual double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const =0
Compute the pressure shape and test functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
virtual void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
Calculate the body force at a given time and local and/or Eulerian position. This function is virtual so that it can be overloaded in multi-physics elements where the body force might depend on another variable.
virtual void get_body_force_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
Get gradient of body force term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
virtual double get_source_nst (const double &time, const unsigned &ipt, const Vector< double > &x)
Calculate the source fct at a given time and Eulerian position.
virtual void get_source_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
Get gradient of source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
virtual void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, const unsigned &flag)
Compute the residuals for the Navier-Stokes equations. Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
virtual void fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
virtual void fill_in_generic_dresidual_contribution_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, const unsigned &flag)
Compute the derivatives of the residuals for the Navier-Stokes equations with respect to a parameter Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Compute the hessian tensor vector products required to perform continuation of bifurcations analytically.
virtual double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Compute the shape functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
virtual double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Compute the shape functions and derivatives w.r.t. global coords at ipt-th integration point Return Jacobian of mapping between local and global coordinates.
virtual double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
virtual double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const =0
Compute the pressure shape and test functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
virtual void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
Calculate the body force at a given time and local and/or Eulerian position. This function is virtual so that it can be overloaded in multi-physics elements where the body force might depend on another variable.
virtual void get_body_force_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
Get gradient of body force term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
virtual double get_source_nst (const double &time, const unsigned &ipt, const Vector< double > &x)
Calculate the source fct at a given time and Eulerian position.
virtual void get_source_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
Get gradient of source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
virtual void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, const unsigned &flag)
Compute the residuals for the Navier-Stokes equations. Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
virtual void fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
virtual void fill_in_generic_dresidual_contribution_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, const unsigned &flag)
Compute the derivatives of the residuals for the Navier-Stokes equations with respect to a parameter Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Compute the hessian tensor vector products required to perform continuation of bifurcations analytically.
Protected Attributes
double * Viscosity_Ratio_pt
Pointer to the viscosity ratio (relative to the viscosity used in the definition of the Reynolds number)
double * Density_Ratio_pt
Pointer to the density ratio (relative to the density used in the definition of the Reynolds number)
double * Re_pt
Pointer to global Reynolds number.
double * St_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
bool Strouhal_is_stored_as_external_data
Boolean to indicate whether or not the Strouhal value is stored as external data (if it's also an unknown of the problem)
double * ReInvFr_pt
Pointer to global Reynolds number x inverse Froude number (= Bond number / Capillary number)
Vector< double > * G_pt
Pointer to global gravity Vector.
NavierStokesBodyForceFctPt Body_force_fct_pt
Pointer to body force function.
NavierStokesSourceFctPt Source_fct_pt
Pointer to volumetric source function.
NavierStokesPressureAdvDiffSourceFctPt Press_adv_diff_source_fct_pt
Pointer to source function pressure advection diffusion equation (only to be used during validation)
bool ALE_is_disabled
Boolean flag to indicate if ALE formulation is disabled when time-derivatives are computed. Only set to true if you're sure that the mesh is stationary.
Vector< FpPressureAdvDiffRobinBCSpaceTimeElementBase * > Pressure_advection_diffusion_robin_element_pt
Storage for FaceElements that apply Robin BC for pressure adv diff equation used in Fp preconditioner.
int Pinned_fp_pressure_eqn
Global eqn number of pressure dof that's pinned in pressure advection diffusion problem (defaults to -1)
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (= Womersley)
bool ReynoldsStrouhal_is_stored_as_external_data
Boolean to indicate whether or not the Strouhal value is stored as external data (if it's also an unknown of the problem)
Static Private Attributes
static int Pressure_not_stored_at_node = -100
Static `magic` number that indicates that the pressure is not stored at a node.
static double Default_Physical_Constant_Value
Static default value for the physical constants (all initialised to zero)
static double Default_Physical_Ratio_Value
Static default value for the physical ratios (all are initialised to one)
static Vector< double > Default_Gravity_vector
Static default value for the gravity vector.
Detailed Description
template<unsigned DIM>
class SpaceTimeNavierStokesEquations< DIM >
and
$ { \frac{\partial u_i}{\partial x_i}=Q } $
We also provide all functions required to use this element in FSI problems, by deriving it from the FSIFluidElement base class.
0
SPACE-TIME ELEMENTS:
The space-time extension is written ONLY for the 2D Navier-Stokes equations. The result is a 3D problem (x,y,t) to be solved on a 3D mesh. The template parameter DIM now corresponds to the dimension of the space-time problem (i.e. DIM=3 for the 2D flow).
$ { \frac{\partial u_i}{\partial x_i}=Q } $
We also provide all functions required to use this element in FSI problems, by deriving it from the FSIFluidElement base class.
0
SPACE-TIME ELEMENTS:
The space-time extension is written ONLY for the 2D Navier-Stokes equations. The result is a 3D problem (x,y,t) to be solved on a 3D mesh. The template parameter DIM now corresponds to the dimension of the space-time problem (i.e. DIM=3 for the 2D flow).
$ { \frac{\partial u_i}{\partial x_i}=Q } $
We also provide all functions required to use this element in FSI problems, by deriving it from the FSIFluidElement base class.
0
SPACE-TIME ELEMENTS:
The space-time extension is written ONLY for the 2D Navier-Stokes equations. The result is a 3D problem (x,y,t) to be solved on a 3D mesh. The template parameter DIM now corresponds to the dimension of the space-time problem (i.e. DIM=3 for the 2D flow).
Definition at line 469 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Member Typedef Documentation
NavierStokesBodyForceFctPt [1/3]
template<unsigned DIM>
typedef void(* SpaceTimeNavierStokesEquations< DIM >::NavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
Function pointer to body force function fct(t,x,f(x)) x is a Vector!
Definition at line 476 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
NavierStokesBodyForceFctPt [2/3]
template<unsigned DIM>
typedef void(* SpaceTimeNavierStokesEquations< DIM >::NavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
Function pointer to body force function fct(t,x,f(x)) x is a Vector!
Definition at line 476 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
NavierStokesBodyForceFctPt [3/3]
template<unsigned DIM>
typedef void(* SpaceTimeNavierStokesEquations< DIM >::NavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
Function pointer to body force function fct(t,x,f(x)) x is a Vector!
Definition at line 476 of file spacetime_navier_stokes_elements.h.
NavierStokesPressureAdvDiffSourceFctPt [1/3]
template<unsigned DIM>
typedef double(* SpaceTimeNavierStokesEquations< DIM >::NavierStokesPressureAdvDiffSourceFctPt) (const Vector< double > &x)
Function pointer to source function fct(x) for the pressure advection diffusion equation (only used during validation!). x is a Vector!
Definition at line 487 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
NavierStokesPressureAdvDiffSourceFctPt [2/3]
template<unsigned DIM>
typedef double(* SpaceTimeNavierStokesEquations< DIM >::NavierStokesPressureAdvDiffSourceFctPt) (const Vector< double > &x)
Function pointer to source function fct(x) for the pressure advection diffusion equation (only used during validation!). x is a Vector!
Definition at line 487 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
NavierStokesPressureAdvDiffSourceFctPt [3/3]
template<unsigned DIM>
typedef double(* SpaceTimeNavierStokesEquations< DIM >::NavierStokesPressureAdvDiffSourceFctPt) (const Vector< double > &x)
Function pointer to source function fct(x) for the pressure advection diffusion equation (only used during validation!). x is a Vector!
Definition at line 487 of file spacetime_navier_stokes_elements.h.
NavierStokesSourceFctPt [1/3]
template<unsigned DIM>
typedef double(* SpaceTimeNavierStokesEquations< DIM >::NavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
Function pointer to source function fct(t,x) (x is a Vector!)
Definition at line 481 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
NavierStokesSourceFctPt [2/3]
template<unsigned DIM>
typedef double(* SpaceTimeNavierStokesEquations< DIM >::NavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
Function pointer to source function fct(t,x) (x is a Vector!)
Definition at line 481 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
NavierStokesSourceFctPt [3/3]
template<unsigned DIM>
typedef double(* SpaceTimeNavierStokesEquations< DIM >::NavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
Function pointer to source function fct(t,x) (x is a Vector!)
Definition at line 481 of file spacetime_navier_stokes_elements.h.
Constructor & Destructor Documentation
SpaceTimeNavierStokesEquations() [1/3]
template<unsigned DIM>
SpaceTimeNavierStokesEquations< DIM >::SpaceTimeNavierStokesEquations () [inline]
Constructor: NULL the body force and source function and make sure the ALE terms are included by default.
Definition at line 801 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::MultiDomainBoussinesqHelper::Default_Physical_Constant_Value.
SpaceTimeNavierStokesEquations() [2/3]
template<unsigned DIM>
SpaceTimeNavierStokesEquations< DIM >::SpaceTimeNavierStokesEquations () [inline]
Constructor: NULL the body force and source function and make sure the ALE terms are included by default.
Definition at line 801 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::MultiDomainBoussinesqHelper::Default_Physical_Constant_Value.
SpaceTimeNavierStokesEquations() [3/3]
template<unsigned DIM>
SpaceTimeNavierStokesEquations< DIM >::SpaceTimeNavierStokesEquations () [inline]
Constructor: NULL the body force and source function and make sure the ALE terms are included by default.
Definition at line 784 of file spacetime_navier_stokes_elements.h.
References oomph::MultiDomainBoussinesqHelper::Default_Physical_Constant_Value.
Member Function Documentation
body_force_fct_pt() [1/6]
template<unsigned DIM>
NavierStokesBodyForceFctPt & SpaceTimeNavierStokesEquations< DIM >::body_force_fct_pt () [inline]
Access function for the body-force pointer.
Definition at line 1015 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build().
body_force_fct_pt() [2/6]
template<unsigned DIM>
NavierStokesBodyForceFctPt & SpaceTimeNavierStokesEquations< DIM >::body_force_fct_pt () [inline]
Access function for the body-force pointer.
Definition at line 1015 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
body_force_fct_pt() [3/6]
template<unsigned DIM>
NavierStokesBodyForceFctPt & SpaceTimeNavierStokesEquations< DIM >::body_force_fct_pt () [inline]
Access function for the body-force pointer.
Definition at line 989 of file spacetime_navier_stokes_elements.h.
body_force_fct_pt() [4/6]
template<unsigned DIM>
NavierStokesBodyForceFctPt SpaceTimeNavierStokesEquations< DIM >::body_force_fct_pt () const [inline]
Access function for the body-force pointer. Const version.
Definition at line 1021 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
body_force_fct_pt() [5/6]
template<unsigned DIM>
NavierStokesBodyForceFctPt SpaceTimeNavierStokesEquations< DIM >::body_force_fct_pt () const [inline]
Access function for the body-force pointer. Const version.
Definition at line 1021 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
body_force_fct_pt() [6/6]
template<unsigned DIM>
NavierStokesBodyForceFctPt SpaceTimeNavierStokesEquations< DIM >::body_force_fct_pt () const [inline]
Access function for the body-force pointer. Const version.
Definition at line 995 of file spacetime_navier_stokes_elements.h.
build_fp_press_adv_diff_robin_bc_element() [1/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::build_fp_press_adv_diff_robin_bc_element (const unsigned & face_index) [pure virtual]
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
build_fp_press_adv_diff_robin_bc_element() [2/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::build_fp_press_adv_diff_robin_bc_element (const unsigned & face_index) [pure virtual]
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
build_fp_press_adv_diff_robin_bc_element() [3/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::build_fp_press_adv_diff_robin_bc_element (const unsigned & face_index) [pure virtual]
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
compute_error() [1/15]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm)
Validate against exact solution. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
Validate against exact velocity solution Solution is provided via a function pointer. Compute L2 error and L2 norm of velocity solution over element.
Definition at line 607 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, s, oomph::W, and oomph::x.
compute_error() [2/15]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm)
Validate against exact solution. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
compute_error() [3/15]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm)
Validate against exact solution. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
compute_error() [4/15]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm)
Validate against exact solution. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
Validate against exact velocity solution at given time. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
Definition at line 531 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, s, oomph::W, and oomph::x.
compute_error() [5/15]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm)
Validate against exact solution. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
compute_error() [6/15]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm)
Validate against exact solution. Solution is provided via function pointer. Compute L2 error and L2 norm of velocity solution over element.
compute_error() [7/15]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm)
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Validate against exact velocity solution Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Definition at line 677 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, s, oomph::W, and oomph::x.
compute_error() [8/15]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm)
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
compute_error() [9/15]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm)
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
compute_error() [10/15]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Validate against exact velocity solution at given time. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Definition at line 243 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, s, oomph::W, and oomph::x.
compute_error() [11/15]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
compute_error() [12/15]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
compute_error() [13/15]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, Vector< double > & error, Vector< double > & norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Validate against exact velocity solution at given time. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Definition at line 387 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, s, oomph::W, and oomph::x.
compute_error() [14/15]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, Vector< double > & error, Vector< double > & norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
compute_error() [15/15]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, Vector< double > & error, Vector< double > & norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
compute_norm() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::compute_norm (Vector< double > & norm)
Compute the vector norm of the FEM solution.
Compute the vector norm of FEM solution.
Definition at line 195 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, s, and oomph::W.
compute_norm() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::compute_norm (Vector< double > & norm)
Compute the vector norm of the FEM solution.
compute_norm() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::compute_norm (Vector< double > & norm)
Compute the vector norm of the FEM solution.
d_kin_energy_dt() [1/3]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::d_kin_energy_dt
Get integral of time derivative of kinetic energy over element.
Get integral of time derivative of kinetic energy over element:
Definition at line 1668 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i.
d_kin_energy_dt() [2/3]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::d_kin_energy_dt () const
Get integral of time derivative of kinetic energy over element.
d_kin_energy_dt() [3/3]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::d_kin_energy_dt () const
Get integral of time derivative of kinetic energy over element.
delete_pressure_advection_diffusion_robin_elements() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::delete_pressure_advection_diffusion_robin_elements () [inline]
Delete the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Definition at line 1878 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References e.
delete_pressure_advection_diffusion_robin_elements() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::delete_pressure_advection_diffusion_robin_elements () [inline]
Delete the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Definition at line 1878 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References e.
delete_pressure_advection_diffusion_robin_elements() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::delete_pressure_advection_diffusion_robin_elements () [inline]
Delete the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Definition at line 1851 of file spacetime_navier_stokes_elements.h.
References e.
density_ratio() [1/3]
template<unsigned DIM>
const double & SpaceTimeNavierStokesEquations< DIM >::density_ratio () const [inline]
Density ratio for element: Element's density relative to the viscosity used in the definition of the Reynolds number.
Definition at line 979 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
density_ratio() [2/3]
template<unsigned DIM>
const double & SpaceTimeNavierStokesEquations< DIM >::density_ratio () const [inline]
Density ratio for element: Element's density relative to the viscosity used in the definition of the Reynolds number.
Definition at line 979 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
density_ratio() [3/3]
template<unsigned DIM>
const double & SpaceTimeNavierStokesEquations< DIM >::density_ratio () const [inline]
Density ratio for element: Element's density relative to the viscosity used in the definition of the Reynolds number.
Definition at line 953 of file spacetime_navier_stokes_elements.h.
density_ratio_pt() [1/3]
template<unsigned DIM>
double *& SpaceTimeNavierStokesEquations< DIM >::density_ratio_pt () [inline]
Pointer to Density ratio.
Definition at line 985 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build().
density_ratio_pt() [2/3]
template<unsigned DIM>
double *& SpaceTimeNavierStokesEquations< DIM >::density_ratio_pt () [inline]
Pointer to Density ratio.
Definition at line 985 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
density_ratio_pt() [3/3]
template<unsigned DIM>
double *& SpaceTimeNavierStokesEquations< DIM >::density_ratio_pt () [inline]
Pointer to Density ratio.
Definition at line 959 of file spacetime_navier_stokes_elements.h.
dinterpolated_u_nst_ddata() [1/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata (const Vector< double > & s, const unsigned & i, Vector< double > & du_ddata, Vector< unsigned > & global_eqn_number) [inline], [virtual]
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. The function is virtual so that it can be overloaded in the refineable version.
Definition at line 1984 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References i, s, and oomph::OneDimLagrange::shape().
dinterpolated_u_nst_ddata() [2/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata (const Vector< double > & s, const unsigned & i, Vector< double > & du_ddata, Vector< unsigned > & global_eqn_number) [inline], [virtual]
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. The function is virtual so that it can be overloaded in the refineable version.
Definition at line 1984 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References i, s, and oomph::OneDimLagrange::shape().
dinterpolated_u_nst_ddata() [3/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata (const Vector< double > & s, const unsigned & i, Vector< double > & du_ddata, Vector< unsigned > & global_eqn_number) [inline], [virtual]
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. The function is virtual so that it can be overloaded in the refineable version.
Definition at line 1957 of file spacetime_navier_stokes_elements.h.
References i, s, and oomph::OneDimLagrange::shape().
disable_ALE() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::disable_ALE () [inline]
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
Definition at line 1206 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
disable_ALE() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::disable_ALE () [inline]
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
Definition at line 1206 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
disable_ALE() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::disable_ALE () [inline]
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
Definition at line 1180 of file spacetime_navier_stokes_elements.h.
dissipation() [1/6]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::dissipation
Return integral of dissipation over element.
Definition at line 1305 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, and s.
dissipation() [2/6]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::dissipation () const
Return integral of dissipation over element.
dissipation() [3/6]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::dissipation () const
Return integral of dissipation over element.
dissipation() [4/6]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::dissipation (const Vector< double > & s) const
Return dissipation at local coordinate s.
Definition at line 1444 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, and s.
dissipation() [5/6]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::dissipation (const Vector< double > & s) const
Return dissipation at local coordinate s.
dissipation() [6/6]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::dissipation (const Vector< double > & s) const
Return dissipation at local coordinate s.
dpshape_and_dptest_eulerian_nst() [1/3]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [protected], [pure virtual]
Compute the pressure shape and test functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
dpshape_and_dptest_eulerian_nst() [2/3]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [protected], [pure virtual]
Compute the pressure shape and test functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
dpshape_and_dptest_eulerian_nst() [3/3]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [protected], [pure virtual]
Compute the pressure shape and test functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
dpshape_eulerian() [1/2]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::dpshape_eulerian (const Vector< double > & s, Shape & ppsi, DShape & dppsidx) const [protected], [pure virtual]
Pressure shape functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
dpshape_eulerian() [2/2]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::dpshape_eulerian (const Vector< double > & s, Shape & ppsi, DShape & dppsidx) const [protected], [pure virtual]
Pressure shape functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
dptest_eulerian() [1/2]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::dptest_eulerian (const Vector< double > & s, Shape & ptest, DShape & dptestdx) const [protected], [pure virtual]
Pressure test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
dptest_eulerian() [2/2]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::dptest_eulerian (const Vector< double > & s, Shape & ptest, DShape & dptestdx) const [protected], [pure virtual]
Pressure test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
dshape_and_dtest_eulerian_at_knot_nst() [1/6]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
dshape_and_dtest_eulerian_at_knot_nst() [2/6]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
dshape_and_dtest_eulerian_at_knot_nst() [3/6]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
dshape_and_dtest_eulerian_at_knot_nst() [4/6]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Compute the shape functions and derivatives w.r.t. global coords at ipt-th integration point Return Jacobian of mapping between local and global coordinates.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
dshape_and_dtest_eulerian_at_knot_nst() [5/6]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Compute the shape functions and derivatives w.r.t. global coords at ipt-th integration point Return Jacobian of mapping between local and global coordinates.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
dshape_and_dtest_eulerian_at_knot_nst() [6/6]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Compute the shape functions and derivatives w.r.t. global coords at ipt-th integration point Return Jacobian of mapping between local and global coordinates.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
dshape_and_dtest_eulerian_nst() [1/3]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Compute the shape functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
dshape_and_dtest_eulerian_nst() [2/3]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Compute the shape functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
dshape_and_dtest_eulerian_nst() [3/3]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Compute the shape functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
du_dt_nst() [1/3]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::du_dt_nst (const unsigned & n, const unsigned & i) const [inline]
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
Definition at line 1155 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References i, and s.
du_dt_nst() [2/3]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::du_dt_nst (const unsigned & n, const unsigned & i) const [inline]
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
Definition at line 1155 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References i, and s.
du_dt_nst() [3/3]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::du_dt_nst (const unsigned & n, const unsigned & i) const [inline]
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
Definition at line 1129 of file spacetime_navier_stokes_elements.h.
References i, and s.
enable_ALE() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::enable_ALE () [inline]
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
Definition at line 1216 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
enable_ALE() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::enable_ALE () [inline]
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
Definition at line 1216 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
enable_ALE() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::enable_ALE () [inline]
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
Definition at line 1190 of file spacetime_navier_stokes_elements.h.
fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam, DenseMatrix< double > & dmass_matrix_dparam) [inline]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Definition at line 1700 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam, DenseMatrix< double > & dmass_matrix_dparam) [inline]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Definition at line 1700 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam, DenseMatrix< double > & dmass_matrix_dparam) [inline]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Definition at line 1673 of file spacetime_navier_stokes_elements.h.
fill_in_contribution_to_djacobian_dparameter() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_djacobian_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam) [inline]
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
Definition at line 1680 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_contribution_to_djacobian_dparameter() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_djacobian_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam) [inline]
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
Definition at line 1680 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_contribution_to_djacobian_dparameter() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_djacobian_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam) [inline]
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
Definition at line 1653 of file spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_contribution_to_dresiduals_dparameter() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_dresiduals_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam) [inline]
Compute the element's residual Vector (differentiated w.r.t. a parameter)
Definition at line 1662 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_contribution_to_dresiduals_dparameter() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_dresiduals_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam) [inline]
Compute the element's residual Vector (differentiated w.r.t. a parameter)
Definition at line 1662 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_contribution_to_dresiduals_dparameter() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_dresiduals_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam) [inline]
Compute the element's residual Vector (differentiated w.r.t. a parameter)
Definition at line 1635 of file spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_contribution_to_hessian_vector_products() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_hessian_vector_products (Vector< double > const & Y, DenseMatrix< double > const & C, DenseMatrix< double > & product) [protected]
Compute the hessian tensor vector products required to perform continuation of bifurcations analytically.
Definition at line 2461 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
fill_in_contribution_to_hessian_vector_products() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_hessian_vector_products (Vector< double > const & Y, DenseMatrix< double > const & C, DenseMatrix< double > & product) [protected]
Compute the hessian tensor vector products required to perform continuation of bifurcations analytically.
fill_in_contribution_to_hessian_vector_products() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_hessian_vector_products (Vector< double > const & Y, DenseMatrix< double > const & C, DenseMatrix< double > & product) [protected]
Compute the hessian tensor vector products required to perform continuation of bifurcations analytically.
fill_in_contribution_to_jacobian() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline]
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
Definition at line 1629 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_contribution_to_jacobian() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline]
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
Definition at line 1629 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_contribution_to_jacobian() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline]
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version.
Definition at line 1602 of file spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_contribution_to_jacobian_and_mass_matrix() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Definition at line 1646 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
fill_in_contribution_to_jacobian_and_mass_matrix() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Definition at line 1646 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
fill_in_contribution_to_jacobian_and_mass_matrix() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Definition at line 1619 of file spacetime_navier_stokes_elements.h.
fill_in_contribution_to_residuals() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline]
Compute the element's residual Vector.
Definition at line 1613 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_contribution_to_residuals() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline]
Compute the element's residual Vector.
Definition at line 1613 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_contribution_to_residuals() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline]
Compute the element's residual Vector.
Definition at line 1586 of file spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_generic_dresidual_contribution_nst() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_generic_dresidual_contribution_nst (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam, DenseMatrix< double > & dmass_matrix_dparam, const unsigned & flag) [protected], [virtual]
Compute the derivatives of the residuals for the Navier-Stokes equations with respect to a parameter Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
Compute the derivatives of the residuals for the Navier-Stokes equations with respect to a parameter; flag=2 or 1 or 0: do (or don't) compute the Jacobian and mass matrix as well.
Definition at line 2442 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
fill_in_generic_dresidual_contribution_nst() [2/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::fill_in_generic_dresidual_contribution_nst (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam, DenseMatrix< double > & dmass_matrix_dparam, const unsigned & flag) [protected], [virtual]
Compute the derivatives of the residuals for the Navier-Stokes equations with respect to a parameter Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
fill_in_generic_dresidual_contribution_nst() [3/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::fill_in_generic_dresidual_contribution_nst (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam, DenseMatrix< double > & dmass_matrix_dparam, const unsigned & flag) [protected], [virtual]
Compute the derivatives of the residuals for the Navier-Stokes equations with respect to a parameter Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
fill_in_generic_pressure_advection_diffusion_contribution_nst() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected], [virtual]
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented in oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, and oomph::RefineableSpaceTimeNavierStokesEquations< DIM >.
Definition at line 1811 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References e, i, s, oomph::W, and oomph::x.
fill_in_generic_pressure_advection_diffusion_contribution_nst() [2/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected], [virtual]
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented in oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, and oomph::RefineableSpaceTimeNavierStokesEquations< DIM >.
fill_in_generic_pressure_advection_diffusion_contribution_nst() [3/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected], [virtual]
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented in oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, and oomph::RefineableSpaceTimeNavierStokesEquations< DIM >.
fill_in_generic_residual_contribution_nst() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, const unsigned & flag) [protected], [virtual]
Compute the residuals for the Navier-Stokes equations. Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
Compute the residuals for the Navier-Stokes equations; flag=1 (or 0): do (or don't) compute the Jacobian as well.
Reimplemented in oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, and oomph::RefineableSpaceTimeNavierStokesEquations< DIM >.
Definition at line 1993 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, s, and oomph::W.
fill_in_generic_residual_contribution_nst() [2/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, const unsigned & flag) [protected], [virtual]
Compute the residuals for the Navier-Stokes equations. Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
Reimplemented in oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, and oomph::RefineableSpaceTimeNavierStokesEquations< DIM >.
fill_in_generic_residual_contribution_nst() [3/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, const unsigned & flag) [protected], [virtual]
Compute the residuals for the Navier-Stokes equations. Flag=1 (or 0): do (or don't) compute the Jacobian as well. Flag=2: Fill in mass matrix too.
Reimplemented in oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, and oomph::RefineableSpaceTimeNavierStokesEquations< DIM >.
fill_in_pressure_advection_diffusion_jacobian() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_pressure_advection_diffusion_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline]
Compute the residuals and Jacobian for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
Definition at line 1734 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
fill_in_pressure_advection_diffusion_jacobian() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_pressure_advection_diffusion_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline]
Compute the residuals and Jacobian for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
Definition at line 1734 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
fill_in_pressure_advection_diffusion_jacobian() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_pressure_advection_diffusion_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline]
Compute the residuals and Jacobian for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
Definition at line 1707 of file spacetime_navier_stokes_elements.h.
fill_in_pressure_advection_diffusion_residuals() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_pressure_advection_diffusion_residuals (Vector< double > & residuals) [inline]
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
Definition at line 1720 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_pressure_advection_diffusion_residuals() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_pressure_advection_diffusion_residuals (Vector< double > & residuals) [inline]
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
Definition at line 1720 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fill_in_pressure_advection_diffusion_residuals() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::fill_in_pressure_advection_diffusion_residuals (Vector< double > & residuals) [inline]
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
Definition at line 1693 of file spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Dummy_matrix.
fix_pressure() [1/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::fix_pressure (const unsigned & p_dof, const double & p_value) [pure virtual]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
fix_pressure() [2/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::fix_pressure (const unsigned & p_dof, const double & p_value) [pure virtual]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
fix_pressure() [3/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::fix_pressure (const unsigned & p_dof, const double & p_value) [pure virtual]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
full_output() [1/6]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::full_output (std::ostream & outfile) [inline]
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. The default number of plot points is five.
Definition at line 1513 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
full_output() [2/6]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::full_output (std::ostream & outfile) [inline]
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. The default number of plot points is five.
Definition at line 1513 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
full_output() [3/6]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::full_output (std::ostream & outfile) [inline]
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. The default number of plot points is five.
Definition at line 1487 of file spacetime_navier_stokes_elements.h.
full_output() [4/6]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::full_output (std::ostream & outfile, const unsigned & n_plot)
Full output function: x,y,t,u,v,p,du/dt,dv/dt,dissipation in tecplot format. Use n_plot plot points in each coordinate direction.
Full output function: x,y,t,u,v,p,du/dt,dv/dt,dissipation in tecplot format. Specified number of plot points in each coordinate direction.
Definition at line 1091 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, and s.
full_output() [5/6]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::full_output (std::ostream & outfile, const unsigned & n_plot)
Full output function: x,y,t,u,v,p,du/dt,dv/dt,dissipation in tecplot format. Use n_plot plot points in each coordinate direction.
full_output() [6/6]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::full_output (std::ostream & outfile, const unsigned & n_plot)
Full output function: x,y,t,u,v,p,du/dt,dv/dt,dissipation in tecplot format. Use n_plot plot points in each coordinate direction.
g() [1/3]
template<unsigned DIM>
const Vector< double > & SpaceTimeNavierStokesEquations< DIM >::g () const [inline]
Vector of gravitational components.
Definition at line 1003 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
g() [2/3]
template<unsigned DIM>
const Vector< double > & SpaceTimeNavierStokesEquations< DIM >::g () const [inline]
Vector of gravitational components.
Definition at line 1003 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
g() [3/3]
template<unsigned DIM>
const Vector< double > & SpaceTimeNavierStokesEquations< DIM >::g () const [inline]
Vector of gravitational components.
Definition at line 977 of file spacetime_navier_stokes_elements.h.
g_pt() [1/3]
template<unsigned DIM>
Vector< double > *& SpaceTimeNavierStokesEquations< DIM >::g_pt () [inline]
Pointer to Vector of gravitational components.
Definition at line 1009 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build().
g_pt() [2/3]
template<unsigned DIM>
Vector< double > *& SpaceTimeNavierStokesEquations< DIM >::g_pt () [inline]
Pointer to Vector of gravitational components.
Definition at line 1009 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
g_pt() [3/3]
template<unsigned DIM>
Vector< double > *& SpaceTimeNavierStokesEquations< DIM >::g_pt () [inline]
Pointer to Vector of gravitational components.
Definition at line 983 of file spacetime_navier_stokes_elements.h.
get_body_force_gradient_nst() [1/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::get_body_force_gradient_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, DenseMatrix< double > & d_body_force_dx) [inline], [protected], [virtual]
Get gradient of body force term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
Definition at line 652 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Default_fd_jacobian_step, i, s, and oomph::x.
get_body_force_gradient_nst() [2/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::get_body_force_gradient_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, DenseMatrix< double > & d_body_force_dx) [inline], [protected], [virtual]
Get gradient of body force term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
Definition at line 652 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Default_fd_jacobian_step, i, s, and oomph::x.
get_body_force_gradient_nst() [3/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::get_body_force_gradient_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, DenseMatrix< double > & d_body_force_dx) [inline], [protected], [virtual]
Get gradient of body force term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
Definition at line 635 of file spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Default_fd_jacobian_step, i, s, and oomph::x.
get_body_force_nst() [1/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::get_body_force_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & result) [inline], [protected], [virtual]
Calculate the body force at a given time and local and/or Eulerian position. This function is virtual so that it can be overloaded in multi-physics elements where the body force might depend on another variable.
Definition at line 626 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::x.
get_body_force_nst() [2/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::get_body_force_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & result) [inline], [protected], [virtual]
Calculate the body force at a given time and local and/or Eulerian position. This function is virtual so that it can be overloaded in multi-physics elements where the body force might depend on another variable.
Definition at line 626 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::x.
get_body_force_nst() [3/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::get_body_force_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & result) [inline], [protected], [virtual]
Calculate the body force at a given time and local and/or Eulerian position. This function is virtual so that it can be overloaded in multi-physics elements where the body force might depend on another variable.
Definition at line 609 of file spacetime_navier_stokes_elements.h.
References oomph::x.
get_dresidual_dnodal_coordinates() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates (RankThreeTensor< double > & dresidual_dnodal_coordinates) [virtual]
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j)=d res(l) / dX_{ij}.
Compute derivatives of elemental residual vector with respect to nodal coordinates. dresidual_dnodal_coordinates(l,i,j)=d res(l) / dX_{ij} Overloads the FD-based version in the FE base class. DRAIG: This needs doing carefully if the ALE nodes aren't fixed!!!
Definition at line 2481 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References oomph::GeneralisedElement::Default_fd_jacobian_step, i, and s.
get_dresidual_dnodal_coordinates() [2/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates (RankThreeTensor< double > & dresidual_dnodal_coordinates) [virtual]
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j)=d res(l) / dX_{ij}.
get_dresidual_dnodal_coordinates() [3/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates (RankThreeTensor< double > & dresidual_dnodal_coordinates) [virtual]
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j)=d res(l) / dX_{ij}.
get_du_dt() [1/3]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::get_du_dt (const unsigned & n, const unsigned & i) const [inline]
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes. NOTE: This is essentially a wrapper for du_dt_nst() so it can be called externally.
Definition at line 1146 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References i.
get_du_dt() [2/3]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::get_du_dt (const unsigned & n, const unsigned & i) const [inline]
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes. NOTE: This is essentially a wrapper for du_dt_nst() so it can be called externally.
Definition at line 1146 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References i.
get_du_dt() [3/3]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::get_du_dt (const unsigned & n, const unsigned & i) const [inline]
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes. NOTE: This is essentially a wrapper for du_dt_nst() so it can be called externally.
Definition at line 1120 of file spacetime_navier_stokes_elements.h.
References i.
get_load() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::get_load (const Vector< double > & s, const Vector< double > & N, Vector< double > & load) [inline]
This implements a pure virtual function defined in the FSIFluidElement class. The function computes the traction (on the viscous scale), at the element's local coordinate s, that the fluid element exerts onto an adjacent solid element. The number of arguments is imposed by the interface defined in the FSIFluidElement -- only the unit normal N (pointing into the fluid!) is actually used in the computation.
Definition at line 1291 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::QuadTreeNames::N, and s.
get_load() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::get_load (const Vector< double > & s, const Vector< double > & N, Vector< double > & load) [inline]
This implements a pure virtual function defined in the FSIFluidElement class. The function computes the traction (on the viscous scale), at the element's local coordinate s, that the fluid element exerts onto an adjacent solid element. The number of arguments is imposed by the interface defined in the FSIFluidElement -- only the unit normal N (pointing into the fluid!) is actually used in the computation.
Definition at line 1291 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::QuadTreeNames::N, and s.
get_load() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::get_load (const Vector< double > & s, const Vector< double > & N, Vector< double > & load) [inline]
This implements a pure virtual function defined in the FSIFluidElement class. The function computes the traction (on the viscous scale), at the element's local coordinate s, that the fluid element exerts onto an adjacent solid element. The number of arguments is imposed by the interface defined in the FSIFluidElement -- only the unit normal N (pointing into the fluid!) is actually used in the computation.
Definition at line 1265 of file spacetime_navier_stokes_elements.h.
References oomph::QuadTreeNames::N, and s.
get_pressure_and_velocity_mass_matrix_diagonal() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > & press_mass_diag, Vector< double > & veloc_mass_diag, const unsigned & which_one = 0)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one).
Definition at line 69 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, s, and oomph::W.
get_pressure_and_velocity_mass_matrix_diagonal() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > & press_mass_diag, Vector< double > & veloc_mass_diag, const unsigned & which_one = 0)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
get_pressure_and_velocity_mass_matrix_diagonal() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > & press_mass_diag, Vector< double > & veloc_mass_diag, const unsigned & which_one = 0)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
get_source_gradient_nst() [1/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::get_source_gradient_nst (const double & time, const unsigned & ipt, const Vector< double > & x, Vector< double > & gradient) [inline], [protected], [virtual]
Get gradient of source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
Definition at line 721 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Default_fd_jacobian_step, i, and oomph::x.
get_source_gradient_nst() [2/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::get_source_gradient_nst (const double & time, const unsigned & ipt, const Vector< double > & x, Vector< double > & gradient) [inline], [protected], [virtual]
Get gradient of source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
Definition at line 721 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Default_fd_jacobian_step, i, and oomph::x.
get_source_gradient_nst() [3/3]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::get_source_gradient_nst (const double & time, const unsigned & ipt, const Vector< double > & x, Vector< double > & gradient) [inline], [protected], [virtual]
Get gradient of source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
Definition at line 704 of file spacetime_navier_stokes_elements.h.
References oomph::GeneralisedElement::Default_fd_jacobian_step, i, and oomph::x.
get_source_nst() [1/3]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::get_source_nst (const double & time, const unsigned & ipt, const Vector< double > & x) [inline], [protected], [virtual]
Calculate the source fct at a given time and Eulerian position.
Definition at line 697 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::x.
get_source_nst() [2/3]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::get_source_nst (const double & time, const unsigned & ipt, const Vector< double > & x) [inline], [protected], [virtual]
Calculate the source fct at a given time and Eulerian position.
Definition at line 697 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::x.
get_source_nst() [3/3]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::get_source_nst (const double & time, const unsigned & ipt, const Vector< double > & x) [inline], [protected], [virtual]
Calculate the source fct at a given time and Eulerian position.
Definition at line 680 of file spacetime_navier_stokes_elements.h.
References oomph::x.
get_traction() [1/6]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::get_traction (const Vector< double > & s, const Vector< double > & N, Vector< double > & traction)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s. N has to be outer unit normal to the fluid.
Definition at line 1366 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, oomph::QuadTreeNames::N, and s.
get_traction() [2/6]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::get_traction (const Vector< double > & s, const Vector< double > & N, Vector< double > & traction)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s. N has to be outer unit normal to the fluid.
get_traction() [3/6]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::get_traction (const Vector< double > & s, const Vector< double > & N, Vector< double > & traction)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s. N has to be outer unit normal to the fluid.
get_traction() [4/6]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::get_traction (const Vector< double > & s, const Vector< double > & N, Vector< double > & traction_p, Vector< double > & traction_visc_n, Vector< double > & traction_visc_t)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s, decomposed into pressure and normal and tangential viscous components. N has to be outer unit normal to the fluid.
Definition at line 1400 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, oomph::QuadTreeNames::N, and s.
get_traction() [5/6]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::get_traction (const Vector< double > & s, const Vector< double > & N, Vector< double > & traction_p, Vector< double > & traction_visc_n, Vector< double > & traction_visc_t)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s, decomposed into pressure and normal and tangential viscous components. N has to be outer unit normal to the fluid.
get_traction() [6/6]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::get_traction (const Vector< double > & s, const Vector< double > & N, Vector< double > & traction_p, Vector< double > & traction_visc_n, Vector< double > & traction_visc_t)
Compute traction (on the viscous scale) exerted onto the fluid at local coordinate s, decomposed into pressure and normal and tangential viscous components. N has to be outer unit normal to the fluid.
get_vorticity() [1/12]
void SpaceTimeNavierStokesEquations< 2 >::get_vorticity (const Vector< double > & s, double & vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector as a double.
Definition at line 1601 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References s.
get_vorticity() [2/12]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::get_vorticity (const Vector< double > & s, double & vorticity) const
Compute the vorticity vector at local coordinate s.
get_vorticity() [3/12]
void SpaceTimeNavierStokesEquations< 2 >::get_vorticity (const Vector< double > & s, double & vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector as a double.
Definition at line 1601 of file discontinuous_galerkin_spacetime_navier_stokes_elements.cc.
References s.
get_vorticity() [4/12]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::get_vorticity (const Vector< double > & s, double & vorticity) const
Compute the vorticity vector at local coordinate s.
get_vorticity() [5/12]
void SpaceTimeNavierStokesEquations< 2 >::get_vorticity (const Vector< double > & s, double & vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector as a double.
Definition at line 1601 of file spacetime_navier_stokes_elements.cc.
References s.
get_vorticity() [6/12]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::get_vorticity (const Vector< double > & s, double & vorticity) const
Compute the vorticity vector at local coordinate s.
get_vorticity() [7/12]
void SpaceTimeNavierStokesEquations< 2 >::get_vorticity (const Vector< double > & s, Vector< double > & vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector.
Definition at line 1536 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, and s.
get_vorticity() [8/12]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::get_vorticity (const Vector< double > & s, Vector< double > & vorticity) const
Compute the vorticity vector at local coordinate s.
get_vorticity() [9/12]
void SpaceTimeNavierStokesEquations< 2 >::get_vorticity (const Vector< double > & s, Vector< double > & vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector.
Definition at line 1536 of file discontinuous_galerkin_spacetime_navier_stokes_elements.cc.
References i, and s.
get_vorticity() [10/12]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::get_vorticity (const Vector< double > & s, Vector< double > & vorticity) const
Compute the vorticity vector at local coordinate s.
get_vorticity() [11/12]
void SpaceTimeNavierStokesEquations< 2 >::get_vorticity (const Vector< double > & s, Vector< double > & vorticity) const
Compute 2D vorticity vector at local coordinate s (return in one and only component of vorticity vector.
Definition at line 1536 of file spacetime_navier_stokes_elements.cc.
References i, and s.
get_vorticity() [12/12]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::get_vorticity (const Vector< double > & s, Vector< double > & vorticity) const
Compute the vorticity vector at local coordinate s.
interpolated_du_dt_nst() [1/3]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::interpolated_du_dt_nst (const Vector< double > & s, const unsigned & i) const [inline]
Return FE representation of function value du_i/dt(s) at local coordinate s.
Definition at line 1170 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References i, and s.
interpolated_du_dt_nst() [2/3]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::interpolated_du_dt_nst (const Vector< double > & s, const unsigned & i) const [inline]
Return FE representation of function value du_i/dt(s) at local coordinate s.
Definition at line 1170 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References i, and s.
interpolated_du_dt_nst() [3/3]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::interpolated_du_dt_nst (const Vector< double > & s, const unsigned & i) const [inline]
Return FE representation of function value du_i/dt(s) at local coordinate s.
Definition at line 1144 of file spacetime_navier_stokes_elements.h.
References i, and s.
interpolated_p_nst() [1/6]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::interpolated_p_nst (const unsigned & t, const Vector< double > & s) const [inline]
Return FE interpolated pressure at local coordinate s at time level t.
Definition at line 2065 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References s, and t.
interpolated_p_nst() [2/6]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::interpolated_p_nst (const unsigned & t, const Vector< double > & s) const [inline]
Return FE interpolated pressure at local coordinate s at time level t.
Definition at line 2065 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References s, and t.
interpolated_p_nst() [3/6]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::interpolated_p_nst (const unsigned & t, const Vector< double > & s) const [inline]
Return FE interpolated pressure at local coordinate s at time level t.
Definition at line 2038 of file spacetime_navier_stokes_elements.h.
References s, and t.
interpolated_p_nst() [4/6]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::interpolated_p_nst (const Vector< double > & s) const [inline], [virtual]
Return FE interpolated pressure at local coordinate s.
Definition at line 2043 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References s.
Referenced by oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolated_values().
interpolated_p_nst() [5/6]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::interpolated_p_nst (const Vector< double > & s) const [inline], [virtual]
Return FE interpolated pressure at local coordinate s.
Definition at line 2043 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References s.
interpolated_p_nst() [6/6]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::interpolated_p_nst (const Vector< double > & s) const [inline], [virtual]
Return FE interpolated pressure at local coordinate s.
Definition at line 2016 of file spacetime_navier_stokes_elements.h.
References s.
interpolated_u_nst() [1/9]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::interpolated_u_nst (const unsigned & t, const Vector< double > & s, const unsigned & i) const [inline]
Return FE interpolated velocity u[i] at local coordinate s time level, t. Purposely broken for space-time elements.
Definition at line 1961 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
interpolated_u_nst() [2/9]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::interpolated_u_nst (const unsigned & t, const Vector< double > & s, const unsigned & i) const [inline]
Return FE interpolated velocity u[i] at local coordinate s time level, t. Purposely broken for space-time elements.
Definition at line 1961 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
interpolated_u_nst() [3/9]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::interpolated_u_nst (const unsigned & t, const Vector< double > & s, const unsigned & i) const [inline]
Return FE interpolated velocity u[i] at local coordinate s time level, t. Purposely broken for space-time elements.
Definition at line 1934 of file spacetime_navier_stokes_elements.h.
interpolated_u_nst() [4/9]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::interpolated_u_nst (const Vector< double > & s, const unsigned & i) const [inline]
Return FE interpolated velocity u[i] at local coordinate s.
Definition at line 1930 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References i, s, and oomph::OneDimLagrange::shape().
interpolated_u_nst() [5/9]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::interpolated_u_nst (const Vector< double > & s, const unsigned & i) const [inline]
Return FE interpolated velocity u[i] at local coordinate s.
Definition at line 1930 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References i, s, and oomph::OneDimLagrange::shape().
interpolated_u_nst() [6/9]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::interpolated_u_nst (const Vector< double > & s, const unsigned & i) const [inline]
Return FE interpolated velocity u[i] at local coordinate s.
Definition at line 1903 of file spacetime_navier_stokes_elements.h.
References i, s, and oomph::OneDimLagrange::shape().
interpolated_u_nst() [7/9]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::interpolated_u_nst (const Vector< double > & s, Vector< double > & velocity) const [inline]
Compute vector of FE interpolated velocity u at local coordinate s.
Definition at line 1898 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References i, s, and oomph::OneDimLagrange::shape().
Referenced by oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolated_values().
interpolated_u_nst() [8/9]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::interpolated_u_nst (const Vector< double > & s, Vector< double > & velocity) const [inline]
Compute vector of FE interpolated velocity u at local coordinate s.
Definition at line 1898 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References i, s, and oomph::OneDimLagrange::shape().
interpolated_u_nst() [9/9]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::interpolated_u_nst (const Vector< double > & s, Vector< double > & velocity) const [inline]
Compute vector of FE interpolated velocity u at local coordinate s.
Definition at line 1871 of file spacetime_navier_stokes_elements.h.
References i, s, and oomph::OneDimLagrange::shape().
is_reynolds_strouhal_stored_as_external_data()
template<unsigned DIM>
bool SpaceTimeNavierStokesEquations< DIM >::is_reynolds_strouhal_stored_as_external_data () const [inline]
Are we storing the Strouhal number as external data?
Definition at line 859 of file spacetime_navier_stokes_elements.h.
is_strouhal_stored_as_external_data() [1/2]
template<unsigned DIM>
bool SpaceTimeNavierStokesEquations< DIM >::is_strouhal_stored_as_external_data () const [inline]
Are we storing the Strouhal number as external data?
Definition at line 892 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build().
is_strouhal_stored_as_external_data() [2/2]
template<unsigned DIM>
bool SpaceTimeNavierStokesEquations< DIM >::is_strouhal_stored_as_external_data () const [inline]
Are we storing the Strouhal number as external data?
Definition at line 892 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
kin_energy() [1/3]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::kin_energy
Get integral of kinetic energy over element.
Get integral of kinetic energy over element: Note that this is the `raw` kinetic energy in the sense that the density ratio has not been included. In problems with two or more fluids the user will have to remember to premultiply certain elements by the appropriate density ratio.
Definition at line 1623 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, and s.
kin_energy() [2/3]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::kin_energy () const
Get integral of kinetic energy over element.
kin_energy() [3/3]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::kin_energy () const
Get integral of kinetic energy over element.
n_u_nst() [1/3]
template<unsigned DIM>
unsigned SpaceTimeNavierStokesEquations< DIM >::n_u_nst () const [inline]
Return the number of velocity components (used in FluidInterfaceElements)
Definition at line 1135 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
n_u_nst() [2/3]
template<unsigned DIM>
unsigned SpaceTimeNavierStokesEquations< DIM >::n_u_nst () const [inline]
Return the number of velocity components (used in FluidInterfaceElements)
Definition at line 1135 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
n_u_nst() [3/3]
template<unsigned DIM>
unsigned SpaceTimeNavierStokesEquations< DIM >::n_u_nst () const [inline]
Return the number of velocity components (used in FluidInterfaceElements)
Definition at line 1109 of file spacetime_navier_stokes_elements.h.
npres_nst() [1/3]
template<unsigned DIM>
virtual unsigned SpaceTimeNavierStokesEquations< DIM >::npres_nst () const [pure virtual]
Function to return number of pressure degrees of freedom.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
npres_nst() [2/3]
template<unsigned DIM>
virtual unsigned SpaceTimeNavierStokesEquations< DIM >::npres_nst () const [pure virtual]
Function to return number of pressure degrees of freedom.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
npres_nst() [3/3]
template<unsigned DIM>
virtual unsigned SpaceTimeNavierStokesEquations< DIM >::npres_nst () const [pure virtual]
Function to return number of pressure degrees of freedom.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
nscalar_paraview() [1/3]
template<unsigned DIM>
unsigned SpaceTimeNavierStokesEquations< DIM >::nscalar_paraview () const [inline]
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
Definition at line 1313 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
nscalar_paraview() [2/3]
template<unsigned DIM>
unsigned SpaceTimeNavierStokesEquations< DIM >::nscalar_paraview () const [inline]
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
Definition at line 1313 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
nscalar_paraview() [3/3]
template<unsigned DIM>
unsigned SpaceTimeNavierStokesEquations< DIM >::nscalar_paraview () const [inline]
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
Definition at line 1287 of file spacetime_navier_stokes_elements.h.
output() [1/12]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output (FILE * file_pt) [inline]
C-style output function: x,y,[z],u,v,[w],p in tecplot format. The default number of plot points is five.
Definition at line 1495 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::CommandLineArgs::output().
output() [2/12]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output (FILE * file_pt) [inline]
C-style output function: x,y,[z],u,v,[w],p in tecplot format. The default number of plot points is five.
Definition at line 1495 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::CommandLineArgs::output().
output() [3/12]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output (FILE * file_pt) [inline]
C-style output function: x,y,[z],u,v,[w],p in tecplot format. The default number of plot points is five.
Definition at line 1469 of file spacetime_navier_stokes_elements.h.
References oomph::CommandLineArgs::output().
output() [4/12]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output (FILE * file_pt, const unsigned & n_plot)
C-style output function: x,y,[z],u,v,[w],p in tecplot format. Use n_plot points in each coordinate direction.
C-style output function: x,y,[z],u,v,[w],p in tecplot format. Specified number of plot points in each coordinate direction.
Definition at line 1041 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, and s.
output() [5/12]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output (FILE * file_pt, const unsigned & n_plot)
C-style output function: x,y,[z],u,v,[w],p in tecplot format. Use n_plot points in each coordinate direction.
output() [6/12]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output (FILE * file_pt, const unsigned & n_plot)
C-style output function: x,y,[z],u,v,[w],p in tecplot format. Use n_plot points in each coordinate direction.
output() [7/12]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output (std::ostream & outfile) [inline]
Output function: x,y,t,u,v,p in tecplot format. The default number of plot points is five.
Definition at line 1478 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::CommandLineArgs::output().
Referenced by QTaylorHoodSpaceTimeElement< DIM >::output().
output() [8/12]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output (std::ostream & outfile) [inline]
Output function: x,y,t,u,v,p in tecplot format. The default number of plot points is five.
Definition at line 1478 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::CommandLineArgs::output().
output() [9/12]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output (std::ostream & outfile) [inline]
Output function: x,y,t,u,v,p in tecplot format. The default number of plot points is five.
Definition at line 1452 of file spacetime_navier_stokes_elements.h.
References oomph::CommandLineArgs::output().
output() [10/12]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output (std::ostream & outfile, const unsigned & n_plot)
Output function: x,y,[z],u,v,[w],p in tecplot format. Here, we use n_plot plot points in each coordinate direction.
Output function: x,y,[z],u,v,[w],p in tecplot format. Specified number of plot points in each coordinate direction.
Definition at line 982 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, and s.
output() [11/12]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output (std::ostream & outfile, const unsigned & n_plot)
Output function: x,y,[z],u,v,[w],p in tecplot format. Here, we use n_plot plot points in each coordinate direction.
output() [12/12]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output (std::ostream & outfile, const unsigned & n_plot)
Output function: x,y,[z],u,v,[w],p in tecplot format. Here, we use n_plot plot points in each coordinate direction.
output_fct() [1/6]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given time and at a given number of plot points. Function prints as many components as are returned in solution Vector.
Output `exact` solution at a given time Solution is provided via function pointer. Plot at a given number of plot points. Function prints as many components as are returned in solution Vector.
Definition at line 851 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, s, and oomph::x.
output_fct() [2/6]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given time and at a given number of plot points. Function prints as many components as are returned in solution Vector.
output_fct() [3/6]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given time and at a given number of plot points. Function prints as many components as are returned in solution Vector.
output_fct() [4/6]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given number of plot points. Function prints as many components as are returned in solution Vector.
Output `exact` solution Solution is provided via function pointer. Plot at a given number of plot points. Function prints as many components as are returned in solution Vector.
Definition at line 777 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, s, and oomph::x.
output_fct() [5/6]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given number of plot points. Function prints as many components as are returned in solution Vector.
output_fct() [6/6]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact solution specified via function pointer at a given number of plot points. Function prints as many components as are returned in solution Vector.
output_pressure_advection_diffusion_robin_elements() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output_pressure_advection_diffusion_robin_elements (std::ostream & outfile) [inline]
Output the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Definition at line 1840 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References e, i, s, and oomph::x.
output_pressure_advection_diffusion_robin_elements() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output_pressure_advection_diffusion_robin_elements (std::ostream & outfile) [inline]
Output the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Definition at line 1840 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References e, i, s, and oomph::x.
output_pressure_advection_diffusion_robin_elements() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output_pressure_advection_diffusion_robin_elements (std::ostream & outfile) [inline]
Output the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Definition at line 1813 of file spacetime_navier_stokes_elements.h.
References e, i, s, and oomph::x.
output_veloc() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output_veloc (std::ostream & outfile, const unsigned & nplot, const unsigned & t)
Output function: x,y,t,u,v in tecplot format. Use n_plot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
Output function: Velocities only x,y,[z],u,v,[w] in tecplot format at specified previous timestep (t=0: present; t>0: previous timestep). Specified number of plot points in each coordinate direction. DRAIG: Should be broken!
Definition at line 928 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, and s.
output_veloc() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output_veloc (std::ostream & outfile, const unsigned & nplot, const unsigned & t)
Output function: x,y,t,u,v in tecplot format. Use n_plot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
output_veloc() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output_veloc (std::ostream & outfile, const unsigned & nplot, const unsigned & t)
Output function: x,y,t,u,v in tecplot format. Use n_plot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
output_vorticity() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output_vorticity (std::ostream & outfile, const unsigned & nplot)
Output function: x,y,t,omega in tecplot format. nplot points in each coordinate direction.
Output function for vorticity. x,y,[z],[omega_x,omega_y,[and/or omega_z]] in tecplot format. Specified number of plot points in each coordinate direction.
Definition at line 1223 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, s, and oomph::Global_string_for_annotation::string().
output_vorticity() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output_vorticity (std::ostream & outfile, const unsigned & nplot)
Output function: x,y,t,omega in tecplot format. nplot points in each coordinate direction.
output_vorticity() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::output_vorticity (std::ostream & outfile, const unsigned & nplot)
Output function: x,y,t,omega in tecplot format. nplot points in each coordinate direction.
p_nodal_index_nst() [1/3]
template<unsigned DIM>
virtual int SpaceTimeNavierStokesEquations< DIM >::p_nodal_index_nst () const [inline], [virtual]
Return the index at which the pressure is stored if it is stored at the nodes. If not stored at the nodes this will return a negative number.
Reimplemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
Definition at line 1235 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
p_nodal_index_nst() [2/3]
template<unsigned DIM>
virtual int SpaceTimeNavierStokesEquations< DIM >::p_nodal_index_nst () const [inline], [virtual]
Return the index at which the pressure is stored if it is stored at the nodes. If not stored at the nodes this will return a negative number.
Reimplemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
Definition at line 1235 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
p_nodal_index_nst() [3/3]
template<unsigned DIM>
virtual int SpaceTimeNavierStokesEquations< DIM >::p_nodal_index_nst () const [inline], [virtual]
Return the index at which the pressure is stored if it is stored at the nodes. If not stored at the nodes this will return a negative number.
Reimplemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
Definition at line 1209 of file spacetime_navier_stokes_elements.h.
p_nst() [1/6]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::p_nst (const unsigned & n_p) const [pure virtual]
Pressure at local pressure `node` n_p Uses suitably interpolated value for hanging nodes.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
p_nst() [2/6]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::p_nst (const unsigned & n_p) const [pure virtual]
Pressure at local pressure `node` n_p Uses suitably interpolated value for hanging nodes.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
p_nst() [3/6]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::p_nst (const unsigned & n_p) const [pure virtual]
Pressure at local pressure `node` n_p Uses suitably interpolated value for hanging nodes.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
p_nst() [4/6]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::p_nst (const unsigned & t, const unsigned & n_p) const [pure virtual]
Pressure at local pressure `node` n_p at time level t.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
p_nst() [5/6]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::p_nst (const unsigned & t, const unsigned & n_p) const [pure virtual]
Pressure at local pressure `node` n_p at time level t.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
p_nst() [6/6]
template<unsigned DIM>
virtual double SpaceTimeNavierStokesEquations< DIM >::p_nst (const unsigned & t, const unsigned & n_p) const [pure virtual]
Pressure at local pressure `node` n_p at time level t.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
pin_all_non_pressure_dofs() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::pin_all_non_pressure_dofs (std::map< Data *, std::vector< int > > & eqn_number_backup) [inline]
Pin all non-pressure dofs and backup eqn numbers.
Definition at line 1747 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References i.
pin_all_non_pressure_dofs() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::pin_all_non_pressure_dofs (std::map< Data *, std::vector< int > > & eqn_number_backup) [inline]
Pin all non-pressure dofs and backup eqn numbers.
Definition at line 1747 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References i.
pin_all_non_pressure_dofs() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::pin_all_non_pressure_dofs (std::map< Data *, std::vector< int > > & eqn_number_backup) [inline]
Pin all non-pressure dofs and backup eqn numbers.
Definition at line 1720 of file spacetime_navier_stokes_elements.h.
References i.
pinned_fp_pressure_eqn() [1/3]
template<unsigned DIM>
int & SpaceTimeNavierStokesEquations< DIM >::pinned_fp_pressure_eqn () [inline]
Global eqn number of pressure dof that's pinned in pressure adv diff problem.
Definition at line 1055 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
pinned_fp_pressure_eqn() [2/3]
template<unsigned DIM>
int & SpaceTimeNavierStokesEquations< DIM >::pinned_fp_pressure_eqn () [inline]
Global eqn number of pressure dof that's pinned in pressure adv diff problem.
Definition at line 1055 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
pinned_fp_pressure_eqn() [3/3]
template<unsigned DIM>
int & SpaceTimeNavierStokesEquations< DIM >::pinned_fp_pressure_eqn () [inline]
Global eqn number of pressure dof that's pinned in pressure adv diff problem.
Definition at line 1029 of file spacetime_navier_stokes_elements.h.
point_output_data() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::point_output_data (const Vector< double > & s, Vector< double > & data) [inline]
Output solution in data vector at local cordinates s: x,y,z,u,v,p.
Definition at line 2088 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References i, and s.
point_output_data() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::point_output_data (const Vector< double > & s, Vector< double > & data) [inline]
Output solution in data vector at local cordinates s: x,y,z,u,v,p.
Definition at line 2088 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References i, and s.
point_output_data() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::point_output_data (const Vector< double > & s, Vector< double > & data) [inline]
Output solution in data vector at local cordinates s: x,y,z,u,v,p.
Definition at line 2061 of file spacetime_navier_stokes_elements.h.
References i, and s.
pressure_integral() [1/3]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::pressure_integral
Integral of pressure over element.
Return pressure integrated over the element.
Definition at line 1765 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, s, and oomph::W.
pressure_integral() [2/3]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::pressure_integral () const
Integral of pressure over element.
pressure_integral() [3/3]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::pressure_integral () const
Integral of pressure over element.
pshape_nst() [1/6]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::pshape_nst (const Vector< double > & s, Shape & psi) const [pure virtual]
Compute the pressure shape functions at local coordinate s.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
pshape_nst() [2/6]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::pshape_nst (const Vector< double > & s, Shape & psi) const [pure virtual]
Compute the pressure shape functions at local coordinate s.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
pshape_nst() [3/6]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::pshape_nst (const Vector< double > & s, Shape & psi) const [pure virtual]
Compute the pressure shape functions at local coordinate s.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
pshape_nst() [4/6]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const [pure virtual]
Compute the pressure shape and test functions at local coordinate s.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
pshape_nst() [5/6]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const [pure virtual]
Compute the pressure shape and test functions at local coordinate s.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
pshape_nst() [6/6]
template<unsigned DIM>
virtual void SpaceTimeNavierStokesEquations< DIM >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const [pure virtual]
Compute the pressure shape and test functions at local coordinate s.
Implemented in QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, QTaylorHoodSpaceTimeElement< 2 >, QTaylorHoodSpaceTimeElement< DIM >, and QTaylorHoodSpaceTimeElement< 2 >.
re() [1/3]
template<unsigned DIM>
const double & SpaceTimeNavierStokesEquations< DIM >::re () const [inline]
Reynolds number.
Definition at line 876 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
re() [2/3]
template<unsigned DIM>
const double & SpaceTimeNavierStokesEquations< DIM >::re () const [inline]
Reynolds number.
Definition at line 876 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
re() [3/3]
template<unsigned DIM>
const double & SpaceTimeNavierStokesEquations< DIM >::re () const [inline]
Reynolds number.
Definition at line 867 of file spacetime_navier_stokes_elements.h.
re_invfr() [1/3]
template<unsigned DIM>
const double & SpaceTimeNavierStokesEquations< DIM >::re_invfr () const [inline]
Global inverse Froude number.
Definition at line 991 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
re_invfr() [2/3]
template<unsigned DIM>
const double & SpaceTimeNavierStokesEquations< DIM >::re_invfr () const [inline]
Global inverse Froude number.
Definition at line 991 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
re_invfr() [3/3]
template<unsigned DIM>
const double & SpaceTimeNavierStokesEquations< DIM >::re_invfr () const [inline]
Global inverse Froude number.
Definition at line 965 of file spacetime_navier_stokes_elements.h.
re_invfr_pt() [1/3]
template<unsigned DIM>
double *& SpaceTimeNavierStokesEquations< DIM >::re_invfr_pt () [inline]
Pointer to global inverse Froude number.
Definition at line 997 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build().
re_invfr_pt() [2/3]
template<unsigned DIM>
double *& SpaceTimeNavierStokesEquations< DIM >::re_invfr_pt () [inline]
Pointer to global inverse Froude number.
Definition at line 997 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
re_invfr_pt() [3/3]
template<unsigned DIM>
double *& SpaceTimeNavierStokesEquations< DIM >::re_invfr_pt () [inline]
Pointer to global inverse Froude number.
Definition at line 971 of file spacetime_navier_stokes_elements.h.
re_pt() [1/3]
template<unsigned DIM>
double *& SpaceTimeNavierStokesEquations< DIM >::re_pt () [inline]
Pointer to Reynolds number.
Definition at line 884 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build().
re_pt() [2/3]
template<unsigned DIM>
double *& SpaceTimeNavierStokesEquations< DIM >::re_pt () [inline]
Pointer to Reynolds number.
Definition at line 884 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
re_pt() [3/3]
template<unsigned DIM>
double *& SpaceTimeNavierStokesEquations< DIM >::re_pt () [inline]
Pointer to Reynolds number.
Definition at line 875 of file spacetime_navier_stokes_elements.h.
re_st() [1/3]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::re_st () const [inline]
Product of Reynolds and Strouhal number (=Womersley number)
Definition at line 957 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
re_st() [2/3]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::re_st () const [inline]
Product of Reynolds and Strouhal number (=Womersley number)
Definition at line 957 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
re_st() [3/3]
template<unsigned DIM>
const double & SpaceTimeNavierStokesEquations< DIM >::re_st () const [inline]
ReSt parameter (const. version)
Definition at line 883 of file spacetime_navier_stokes_elements.h.
re_st_pt() [1/2]
template<unsigned DIM>
double *& SpaceTimeNavierStokesEquations< DIM >::re_st_pt () [inline]
Pointer to ReSt number (can only assign to private member data)
Definition at line 931 of file spacetime_navier_stokes_elements.h.
re_st_pt() [2/2]
template<unsigned DIM>
double * SpaceTimeNavierStokesEquations< DIM >::re_st_pt () const [inline]
Pointer to Strouhal parameter (const. version)
Definition at line 907 of file spacetime_navier_stokes_elements.h.
scalar_name_paraview() [1/3]
template<unsigned DIM>
std::string SpaceTimeNavierStokesEquations< DIM >::scalar_name_paraview (const unsigned & i) const [inline]
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
Definition at line 1442 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References i, and oomph::StringConversion::to_string().
scalar_name_paraview() [2/3]
template<unsigned DIM>
std::string SpaceTimeNavierStokesEquations< DIM >::scalar_name_paraview (const unsigned & i) const [inline]
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
Definition at line 1442 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References i, and oomph::StringConversion::to_string().
scalar_name_paraview() [3/3]
template<unsigned DIM>
std::string SpaceTimeNavierStokesEquations< DIM >::scalar_name_paraview (const unsigned & i) const [inline]
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
Definition at line 1416 of file spacetime_navier_stokes_elements.h.
References i, and oomph::StringConversion::to_string().
scalar_value_fct_paraview() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::scalar_value_fct_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const [inline]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Definition at line 1373 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References i, and s.
scalar_value_fct_paraview() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::scalar_value_fct_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const [inline]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Definition at line 1373 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References i, and s.
scalar_value_fct_paraview() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::scalar_value_fct_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const [inline]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Definition at line 1347 of file spacetime_navier_stokes_elements.h.
References i, and s.
scalar_value_paraview() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const [inline]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Definition at line 1321 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References i, and s.
scalar_value_paraview() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const [inline]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Definition at line 1321 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References i, and s.
scalar_value_paraview() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const [inline]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Definition at line 1295 of file spacetime_navier_stokes_elements.h.
References i, and s.
source_fct_for_pressure_adv_diff() [1/6]
template<unsigned DIM>
NavierStokesPressureAdvDiffSourceFctPt & SpaceTimeNavierStokesEquations< DIM >::source_fct_for_pressure_adv_diff () [inline]
Access function for the source-function pointer for pressure advection diffusion (used for validation only).
Definition at line 1040 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
source_fct_for_pressure_adv_diff() [2/6]
template<unsigned DIM>
NavierStokesPressureAdvDiffSourceFctPt & SpaceTimeNavierStokesEquations< DIM >::source_fct_for_pressure_adv_diff () [inline]
Access function for the source-function pointer for pressure advection diffusion (used for validation only).
Definition at line 1040 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
source_fct_for_pressure_adv_diff() [3/6]
template<unsigned DIM>
NavierStokesPressureAdvDiffSourceFctPt & SpaceTimeNavierStokesEquations< DIM >::source_fct_for_pressure_adv_diff () [inline]
Access function for the source-function pointer for pressure advection diffusion (used for validation only).
Definition at line 1014 of file spacetime_navier_stokes_elements.h.
source_fct_for_pressure_adv_diff() [4/6]
template<unsigned DIM>
NavierStokesPressureAdvDiffSourceFctPt SpaceTimeNavierStokesEquations< DIM >::source_fct_for_pressure_adv_diff () const [inline]
Access function for the source-function pointer for pressure advection diffusion (used for validation only). Const version.
Definition at line 1047 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
source_fct_for_pressure_adv_diff() [5/6]
template<unsigned DIM>
NavierStokesPressureAdvDiffSourceFctPt SpaceTimeNavierStokesEquations< DIM >::source_fct_for_pressure_adv_diff () const [inline]
Access function for the source-function pointer for pressure advection diffusion (used for validation only). Const version.
Definition at line 1047 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
source_fct_for_pressure_adv_diff() [6/6]
template<unsigned DIM>
NavierStokesPressureAdvDiffSourceFctPt SpaceTimeNavierStokesEquations< DIM >::source_fct_for_pressure_adv_diff () const [inline]
Access function for the source-function pointer for pressure advection diffusion (used for validation only). Const version.
Definition at line 1021 of file spacetime_navier_stokes_elements.h.
source_fct_pt() [1/6]
template<unsigned DIM>
NavierStokesSourceFctPt & SpaceTimeNavierStokesEquations< DIM >::source_fct_pt () [inline]
Access function for the source-function pointer.
Definition at line 1027 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build().
source_fct_pt() [2/6]
template<unsigned DIM>
NavierStokesSourceFctPt & SpaceTimeNavierStokesEquations< DIM >::source_fct_pt () [inline]
Access function for the source-function pointer.
Definition at line 1027 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
source_fct_pt() [3/6]
template<unsigned DIM>
NavierStokesSourceFctPt & SpaceTimeNavierStokesEquations< DIM >::source_fct_pt () [inline]
Access function for the source-function pointer.
Definition at line 1001 of file spacetime_navier_stokes_elements.h.
source_fct_pt() [4/6]
template<unsigned DIM>
NavierStokesSourceFctPt SpaceTimeNavierStokesEquations< DIM >::source_fct_pt () const [inline]
Access function for the source-function pointer. Const version.
Definition at line 1033 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
source_fct_pt() [5/6]
template<unsigned DIM>
NavierStokesSourceFctPt SpaceTimeNavierStokesEquations< DIM >::source_fct_pt () const [inline]
Access function for the source-function pointer. Const version.
Definition at line 1033 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
source_fct_pt() [6/6]
template<unsigned DIM>
NavierStokesSourceFctPt SpaceTimeNavierStokesEquations< DIM >::source_fct_pt () const [inline]
Access function for the source-function pointer. Const version.
Definition at line 1007 of file spacetime_navier_stokes_elements.h.
st() [1/2]
template<unsigned DIM>
const double & SpaceTimeNavierStokesEquations< DIM >::st () const [inline]
Strouhal parameter (const. version)
Definition at line 900 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
st() [2/2]
template<unsigned DIM>
const double & SpaceTimeNavierStokesEquations< DIM >::st () const [inline]
Strouhal parameter (const. version)
Definition at line 900 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
st_pt() [1/4]
template<unsigned DIM>
double *& SpaceTimeNavierStokesEquations< DIM >::st_pt () [inline]
Pointer to Strouhal number (can only assign to private member data)
Definition at line 949 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
st_pt() [2/4]
template<unsigned DIM>
double *& SpaceTimeNavierStokesEquations< DIM >::st_pt () [inline]
Pointer to Strouhal number (can only assign to private member data)
Definition at line 949 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
st_pt() [3/4]
template<unsigned DIM>
double * SpaceTimeNavierStokesEquations< DIM >::st_pt () const [inline]
Pointer to Strouhal parameter (const. version)
Definition at line 924 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build().
st_pt() [4/4]
template<unsigned DIM>
double * SpaceTimeNavierStokesEquations< DIM >::st_pt () const [inline]
Pointer to Strouhal parameter (const. version)
Definition at line 924 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
store_strouhal_as_external_data() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::store_strouhal_as_external_data (Data * strouhal_data_pt) [inline]
Function that tells us whether the period is stored as external data.
Definition at line 843 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build().
store_strouhal_as_external_data() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::store_strouhal_as_external_data (Data * strouhal_data_pt) [inline]
Function that tells us whether the period is stored as external data.
Definition at line 843 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
store_strouhal_as_external_data() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::store_strouhal_as_external_data (Data * strouhal_data_pt) [inline]
Function that tells us whether the period is stored as external data.
Definition at line 826 of file spacetime_navier_stokes_elements.h.
strain_rate() [1/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::strain_rate (const Vector< double > & s, DenseMatrix< double > & strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j+du_j/dx_i)
Get strain-rate tensor: (1/2)*(du_i/dx_j+du_j/dx_i)
Definition at line 1468 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, and s.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::get_Z2_flux().
strain_rate() [2/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::strain_rate (const Vector< double > & s, DenseMatrix< double > & strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j+du_j/dx_i)
strain_rate() [3/3]
template<unsigned DIM>
void SpaceTimeNavierStokesEquations< DIM >::strain_rate (const Vector< double > & s, DenseMatrix< double > & strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j+du_j/dx_i)
u_index_nst() [1/3]
template<unsigned DIM>
virtual unsigned SpaceTimeNavierStokesEquations< DIM >::u_index_nst (const unsigned & i) const [inline], [virtual]
Return the index at which the i-th unknown velocity component is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
Definition at line 1108 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References i.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::get_Z2_flux(), and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::identify_load_data().
u_index_nst() [2/3]
template<unsigned DIM>
virtual unsigned SpaceTimeNavierStokesEquations< DIM >::u_index_nst (const unsigned & i) const [inline], [virtual]
Return the index at which the i-th unknown velocity component is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
Definition at line 1108 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References i.
u_index_nst() [3/3]
template<unsigned DIM>
virtual unsigned SpaceTimeNavierStokesEquations< DIM >::u_index_nst (const unsigned & i) const [inline], [virtual]
Return the index at which the i-th unknown velocity component is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
Definition at line 1082 of file spacetime_navier_stokes_elements.h.
References i.
u_nst() [1/6]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::u_nst (const unsigned & n, const unsigned & i) const [inline]
Velocity i at local node n. Uses suitably interpolated value for hanging nodes. The use of u_index_nst() permits the use of this element as the basis for multi-physics elements. The default is to assume that the i-th velocity component is stored at the i-th location of the node.
Definition at line 1078 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References i.
u_nst() [2/6]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::u_nst (const unsigned & n, const unsigned & i) const [inline]
Velocity i at local node n. Uses suitably interpolated value for hanging nodes. The use of u_index_nst() permits the use of this element as the basis for multi-physics elements. The default is to assume that the i-th velocity component is stored at the i-th location of the node.
Definition at line 1078 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References i.
u_nst() [3/6]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::u_nst (const unsigned & n, const unsigned & i) const [inline]
Velocity i at local node n. Uses suitably interpolated value for hanging nodes. The use of u_index_nst() permits the use of this element as the basis for multi-physics elements. The default is to assume that the i-th velocity component is stored at the i-th location of the node.
Definition at line 1052 of file spacetime_navier_stokes_elements.h.
References i.
u_nst() [4/6]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::u_nst (const unsigned & t, const unsigned & n, const unsigned & i) const [inline]
Velocity i at local node n at timestep t (t=0: present; t>0: previous). Uses suitably interpolated value for hanging nodes.
Definition at line 1085 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References i, and t.
u_nst() [5/6]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::u_nst (const unsigned & t, const unsigned & n, const unsigned & i) const [inline]
Velocity i at local node n at timestep t (t=0: present; t>0: previous). Uses suitably interpolated value for hanging nodes.
Definition at line 1085 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References i, and t.
u_nst() [6/6]
template<unsigned DIM>
double SpaceTimeNavierStokesEquations< DIM >::u_nst (const unsigned & t, const unsigned & n, const unsigned & i) const [inline]
Velocity i at local node n at timestep t (t=0: present; t>0: previous). Uses suitably interpolated value for hanging nodes.
Definition at line 1059 of file spacetime_navier_stokes_elements.h.
References i, and t.
viscosity_ratio() [1/3]
template<unsigned DIM>
const double & SpaceTimeNavierStokesEquations< DIM >::viscosity_ratio () const [inline]
Viscosity ratio for element: Element's viscosity relative to the viscosity used in the definition of the Reynolds number.
Definition at line 966 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
viscosity_ratio() [2/3]
template<unsigned DIM>
const double & SpaceTimeNavierStokesEquations< DIM >::viscosity_ratio () const [inline]
Viscosity ratio for element: Element's viscosity relative to the viscosity used in the definition of the Reynolds number.
Definition at line 966 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
viscosity_ratio() [3/3]
template<unsigned DIM>
const double & SpaceTimeNavierStokesEquations< DIM >::viscosity_ratio () const [inline]
Viscosity ratio for element: Element's viscosity relative to the viscosity used in the definition of the Reynolds number.
Definition at line 940 of file spacetime_navier_stokes_elements.h.
viscosity_ratio_pt() [1/3]
template<unsigned DIM>
double *& SpaceTimeNavierStokesEquations< DIM >::viscosity_ratio_pt () [inline]
Pointer to Viscosity Ratio.
Definition at line 972 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build().
viscosity_ratio_pt() [2/3]
template<unsigned DIM>
double *& SpaceTimeNavierStokesEquations< DIM >::viscosity_ratio_pt () [inline]
Pointer to Viscosity Ratio.
Definition at line 972 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
viscosity_ratio_pt() [3/3]
template<unsigned DIM>
double *& SpaceTimeNavierStokesEquations< DIM >::viscosity_ratio_pt () [inline]
Pointer to Viscosity Ratio.
Definition at line 946 of file spacetime_navier_stokes_elements.h.
Member Data Documentation
ALE_is_disabled
template<unsigned DIM>
bool SpaceTimeNavierStokesEquations< DIM >::ALE_is_disabled [protected]
Boolean flag to indicate if ALE formulation is disabled when time-derivatives are computed. Only set to true if you're sure that the mesh is stationary.
Definition at line 549 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build().
Body_force_fct_pt
template<unsigned DIM>
NavierStokesBodyForceFctPt SpaceTimeNavierStokesEquations< DIM >::Body_force_fct_pt [protected]
Pointer to body force function.
Definition at line 537 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build().
Default_Gravity_vector
template<unsigned DIM>
static Vector< double > SpaceTimeNavierStokesEquations< DIM >::Default_Gravity_vector [static], [private]
Static default value for the gravity vector.
Navier-Stokes equations default gravity vector.
Definition at line 504 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Default_Physical_Constant_Value
template<unsigned DIM>
static double SpaceTimeNavierStokesEquations< DIM >::Default_Physical_Constant_Value [static], [private]
Initial value:
=
    0.0
Static default value for the physical constants (all initialised to zero)
Navier-Stokes equations static data.
Definition at line 497 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Default_Physical_Ratio_Value
template<unsigned DIM>
static double SpaceTimeNavierStokesEquations< DIM >::Default_Physical_Ratio_Value [static], [private]
Initial value:
=
    1.0
Static default value for the physical ratios (all are initialised to one)
Navier-Stokes equations static data.
Definition at line 501 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Density_Ratio_pt
template<unsigned DIM>
double * SpaceTimeNavierStokesEquations< DIM >::Density_Ratio_pt [protected]
Pointer to the density ratio (relative to the density used in the definition of the Reynolds number)
Definition at line 515 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build().
G_pt
template<unsigned DIM>
Vector< double > * SpaceTimeNavierStokesEquations< DIM >::G_pt [protected]
Pointer to global gravity Vector.
Definition at line 534 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build().
Gamma
template<unsigned DIM>
static Vector< double > SpaceTimeNavierStokesEquations< DIM >::Gamma [static]
Vector to decide whether the stress-divergence form is used or not N.B. This needs to be public so that the intel compiler gets things correct somehow the access function messes things up when going to refineable Navier-Stokes.
Navier-Stokes equations static data.
Definition at line 839 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Pinned_fp_pressure_eqn
template<unsigned DIM>
int SpaceTimeNavierStokesEquations< DIM >::Pinned_fp_pressure_eqn [protected]
Global eqn number of pressure dof that's pinned in pressure advection diffusion problem (defaults to -1)
Definition at line 558 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Press_adv_diff_source_fct_pt
template<unsigned DIM>
NavierStokesPressureAdvDiffSourceFctPt SpaceTimeNavierStokesEquations< DIM >::Press_adv_diff_source_fct_pt [protected]
Pointer to source function pressure advection diffusion equation (only to be used during validation)
Definition at line 544 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Pressure_advection_diffusion_robin_element_pt
template<unsigned DIM>
Vector< FpPressureAdvDiffRobinBCSpaceTimeElementBase * > SpaceTimeNavierStokesEquations< DIM >::Pressure_advection_diffusion_robin_element_pt [protected]
Storage for FaceElements that apply Robin BC for pressure adv diff equation used in Fp preconditioner.
Definition at line 554 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::build_fp_press_adv_diff_robin_bc_element().
Pressure_not_stored_at_node
template<unsigned DIM>
static int SpaceTimeNavierStokesEquations< DIM >::Pressure_not_stored_at_node = -100 [static], [private]
Static `magic` number that indicates that the pressure is not stored at a node.
`Magic` negative number that indicates that the pressure is not stored at a node. This cannot be -1 because that represents the positional hanging scheme in the hanging_pt object of nodes.
Definition at line 493 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Re_pt
template<unsigned DIM>
double * SpaceTimeNavierStokesEquations< DIM >::Re_pt [protected]
Pointer to global Reynolds number.
Definition at line 520 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build().
ReInvFr_pt
template<unsigned DIM>
double * SpaceTimeNavierStokesEquations< DIM >::ReInvFr_pt [protected]
Pointer to global Reynolds number x inverse Froude number (= Bond number / Capillary number)
Definition at line 531 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build().
ReSt_pt
template<unsigned DIM>
double* SpaceTimeNavierStokesEquations< DIM >::ReSt_pt [protected]
Pointer to global Reynolds number x Strouhal number (= Womersley)
Definition at line 523 of file spacetime_navier_stokes_elements.h.
ReynoldsStrouhal_is_stored_as_external_data
template<unsigned DIM>
bool SpaceTimeNavierStokesEquations< DIM >::ReynoldsStrouhal_is_stored_as_external_data [protected]
Boolean to indicate whether or not the Strouhal value is stored as external data (if it's also an unknown of the problem)
Definition at line 527 of file spacetime_navier_stokes_elements.h.
Source_fct_pt
template<unsigned DIM>
NavierStokesSourceFctPt SpaceTimeNavierStokesEquations< DIM >::Source_fct_pt [protected]
Pointer to volumetric source function.
Definition at line 540 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build().
St_pt
template<unsigned DIM>
double * SpaceTimeNavierStokesEquations< DIM >::St_pt [protected]
Pointer to global Reynolds number x Strouhal number (=Womersley)
Definition at line 523 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build().
Strouhal_is_stored_as_external_data
template<unsigned DIM>
bool SpaceTimeNavierStokesEquations< DIM >::Strouhal_is_stored_as_external_data [protected]
Boolean to indicate whether or not the Strouhal value is stored as external data (if it's also an unknown of the problem)
Definition at line 527 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build().
Viscosity_Ratio_pt
template<unsigned DIM>
double * SpaceTimeNavierStokesEquations< DIM >::Viscosity_Ratio_pt [protected]
Pointer to the viscosity ratio (relative to the viscosity used in the definition of the Reynolds number)
Definition at line 511 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build().
The documentation for this class was generated from the following files:
discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h
discontinuous_galerkin_spacetime_navier_stokes_elements.h
spacetime_navier_stokes_elements.h
discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc
discontinuous_galerkin_spacetime_navier_stokes_elements.cc
spacetime_navier_stokes_elements.cc