oomph::DarcyFaceElement< ELEMENT > Class Template Reference
A class for elements that allow the imposition of an applied pressure in the Darcy equations. The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
#include <darcy_face_elements.h>
Public Member Functions
DarcyFaceElement (FiniteElement *const &element_pt, const int &face_index)
Constructor, which takes a `bulk` element and the value of the index and its limit.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Return the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Fill in contribution from Jacobian.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
void output (std::ostream &outfile)
Output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
void output (FILE *file_pt)
C_style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function.
void pressure (const double &time, const Vector< double > &s, double &pressure)
Compute pressure value at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
Public Attributes
void(*&)(const double &time, const Vector< double > &x, const Vector< double > &n, double &pressure) pressure_fct_pt ()
Reference to the pressure function pointer.
Protected Member Functions
virtual void get_pressure (const double &time, const unsigned &intpt, const Vector< double > &x, const Vector< double > &n, double &pressure)
Get the pressure value: Pass number of integration point (dummy), Eulerlian coordinate and normal vector and return the pressure (not all of the input arguments will be required for all specific load functions but the list should cover all cases). This function is virtual so it can be overloaded for FSI.
void fill_in_contribution_to_residuals_darcy_face (Vector< double > &residuals)
Helper function that actually calculates the residuals.
Protected Attributes
void(* Pressure_fct_pt)(const double &time, const Vector< double > &x, const Vector< double > &n, double &result)
Pointer to an imposed pressure function. Arguments: Eulerian coordinate; outer unit normal; applied pressure. (Not all of the input arguments will be required for all specific load functions but the list should cover all cases)
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::DarcyFaceElement< ELEMENT >
A class for elements that allow the imposition of an applied pressure in the Darcy equations. The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
Definition at line 71 of file darcy_face_elements.h.
Constructor & Destructor Documentation
DarcyFaceElement()
template<class ELEMENT >
oomph::DarcyFaceElement< ELEMENT >::DarcyFaceElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit.
Definition at line 111 of file darcy_face_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FaceElement::face_index(), oomph::FiniteElement::has_hanging_nodes(), oomph::DarcyFaceElement< ELEMENT >::Pressure_fct_pt, and oomph::DarcyFaceElementHelper::Zero_pressure_fct().
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::DarcyFaceElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Fill in contribution from Jacobian.
Reimplemented from oomph::GeneralisedElement.
Definition at line 165 of file darcy_face_elements.h.
References oomph::DarcyFaceElement< ELEMENT >::fill_in_contribution_to_residuals_darcy_face().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::DarcyFaceElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Return the residuals.
Reimplemented from oomph::GeneralisedElement.
Definition at line 158 of file darcy_face_elements.h.
References oomph::DarcyFaceElement< ELEMENT >::fill_in_contribution_to_residuals_darcy_face().
fill_in_contribution_to_residuals_darcy_face()
template<class ELEMENT >
void oomph::DarcyFaceElement< ELEMENT >::fill_in_contribution_to_residuals_darcy_face (Vector< double > & residuals) [protected]
Helper function that actually calculates the residuals.
Return the residuals for the DarcyFaceElement equations.
Definition at line 253 of file darcy_face_elements.h.
References i, and oomph::QuadTreeNames::W.
Referenced by oomph::DarcyFaceElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::DarcyFaceElement< ELEMENT >::fill_in_contribution_to_residuals().
get_pressure()
template<class ELEMENT >
virtual void oomph::DarcyFaceElement< ELEMENT >::get_pressure (const double & time, const unsigned & intpt, const Vector< double > & x, const Vector< double > & n, double & pressure) [inline], [protected], [virtual]
Get the pressure value: Pass number of integration point (dummy), Eulerlian coordinate and normal vector and return the pressure (not all of the input arguments will be required for all specific load functions but the list should cover all cases). This function is virtual so it can be overloaded for FSI.
Definition at line 90 of file darcy_face_elements.h.
References oomph::DarcyFaceElement< ELEMENT >::pressure(), and oomph::DarcyFaceElement< ELEMENT >::Pressure_fct_pt.
output() [1/4]
template<class ELEMENT >
void oomph::DarcyFaceElement< ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C_style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 197 of file darcy_face_elements.h.
References oomph::CommandLineArgs::output().
output() [2/4]
template<class ELEMENT >
void oomph::DarcyFaceElement< ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 203 of file darcy_face_elements.h.
References oomph::CommandLineArgs::output().
output() [3/4]
template<class ELEMENT >
void oomph::DarcyFaceElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Definition at line 185 of file darcy_face_elements.h.
References oomph::CommandLineArgs::output().
output() [4/4]
template<class ELEMENT >
void oomph::DarcyFaceElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Definition at line 191 of file darcy_face_elements.h.
References oomph::CommandLineArgs::output().
pressure()
template<class ELEMENT >
void oomph::DarcyFaceElement< ELEMENT >::pressure (const double & time, const Vector< double > & s, double & pressure)
Compute pressure value at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Compute pressure value at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
Definition at line 227 of file darcy_face_elements.h.
References s.
Referenced by oomph::DarcyFaceElement< ELEMENT >::get_pressure().
zeta_nodal()
template<class ELEMENT >
double oomph::DarcyFaceElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Reimplemented from oomph::FiniteElement.
Definition at line 177 of file darcy_face_elements.h.
References i, and oomph::FaceElement::zeta_nodal().
Member Data Documentation
pressure_fct_pt
template<class ELEMENT >
void(*&)(const double &time, const Vector< double > &x, const Vector< double > &n, double &pressure) oomph::DarcyFaceElement< ELEMENT >::pressure_fct_pt() [inline]
Reference to the pressure function pointer.
Definition at line 148 of file darcy_face_elements.h.
Pressure_fct_pt
template<class ELEMENT >
void(* oomph::DarcyFaceElement< ELEMENT >::Pressure_fct_pt) (const double &time, const Vector< double > &x, const Vector< double > &n, double &result) [protected]
Pointer to an imposed pressure function. Arguments: Eulerian coordinate; outer unit normal; applied pressure. (Not all of the input arguments will be required for all specific load functions but the list should cover all cases)
Definition at line 79 of file darcy_face_elements.h.
Referenced by oomph::DarcyFaceElement< ELEMENT >::DarcyFaceElement(), and oomph::DarcyFaceElement< ELEMENT >::get_pressure().
The documentation for this class was generated from the following file:
darcy_face_elements.h