oomph::TetMeshFacetedClosedSurfaceForRemesh Class Reference
#include <tet_mesh.h>
Public Member Functions
TetMeshFacetedClosedSurfaceForRemesh (Vector< Node * > const &vertex_node_pt, Vector< Vector< unsigned > > const &facet_connectivity, Vector< unsigned > const &facet_boundary_id)
Constructor for a FacetedSurface created from a list of nodes and connectivity information. This is used in remeshing.
virtual ~TetMeshFacetedClosedSurfaceForRemesh ()
Destructor. Delete allocated memory.
Public Member Functions inherited from oomph::TetMeshFacetedClosedSurface
TetMeshFacetedClosedSurface ()
Constructor:
virtual ~TetMeshFacetedClosedSurface ()
Empty destructor.
void enable_faceted_volume_represents_hole_for_gmsh ()
Declare closed surface to represent hole for gmsh.
void disable_faceted_volume_represents_hole_for_gmsh ()
Declare closed surface NOT to represent hole for gmsh.
bool faceted_volume_represents_hole_for_gmsh () const
Does closed surface represent hole for gmsh?
const double & internal_point_for_tetgen (const unsigned &j, const unsigned &i) const
i=th coordinate of the j-th internal point for tetgen
void set_hole_for_tetgen (const Vector< double > &hole_point)
Specify coordinate of hole for tetgen.
void set_region_for_tetgen (const unsigned &region_id, const Vector< double > &region_point)
Specify a region; pass (zero-based) region ID and coordinate of point in region for tetgen.
unsigned ninternal_point_for_tetgen ()
Number of internal points (identifying either regions or holes) for tetgen.
const int & region_id_for_tetgen (const unsigned &j) const
Return the (zero-based) region ID of j-th internal point for tetgen. Negative if it's actually a hole.
bool internal_point_identifies_hole_for_tetgen (const unsigned &j)
Is j-th internal point for tetgen associated with a hole?
bool internal_point_identifies_region_for_tetgen (const unsigned &j)
Is j-th internal point for tetgen associated with a region?
Public Member Functions inherited from oomph::TetMeshFacetedSurface
TetMeshFacetedSurface ()
Constructor:
virtual ~TetMeshFacetedSurface ()
Empty destructor.
unsigned nvertex () const
Number of vertices.
unsigned nfacet () const
Number of facets.
unsigned one_based_facet_boundary_id (const unsigned &j) const
One-based boundary id of j-th facet.
unsigned one_based_vertex_boundary_id (const unsigned &j) const
First (of possibly multiple) one-based boundary id of j-th vertex.
double vertex_coordinate (const unsigned &j, const unsigned &i) const
i-th coordinate of j-th vertex
unsigned nvertex_on_facet (const unsigned &j) const
Number of vertices defining the j-th facet.
bool boundaries_can_be_split_in_tetgen ()
Test whether boundary can be split in tetgen.
void enable_boundaries_can_be_split_in_tetgen ()
Test whether boundaries can be split in tetgen.
void disable_boundaries_can_be_split_in_tetgen ()
Test whether boundaries can be split in tetgen.
TetMeshFacet * facet_pt (const unsigned &j) const
Pointer to j-th facet.
TetMeshVertex * vertex_pt (const unsigned &j) const
Pointer to j-th vertex.
DiskLikeGeomObjectWithBoundaries * geom_object_with_boundaries_pt ()
Access to GeomObject with boundaries associated with this surface (Null if there isn't one!)
void output (std::ostream &outfile) const
Output.
void output (const std::string &filename) const
Output.
void output_paraview (std::ostream &outfile) const
Outputs the faceted surface into a specified file in the Paraview format for viewing in Paraview. Make sure to output the file with a .vtu extension. (Not particularly optimised)
void output_paraview (const std::string &filename) const
Outputs the faceted surface into a file with the specified name in the Paraview format. (Not particularly optimised)
virtual void boundary_zeta01 (const unsigned &facet_id, const double &zeta_boundary, Vector< double > &zeta)
Virtual function that specifies the variation of the zeta coordinates in the GeomObject along the boundary connecting vertices 0 and 1 in facet facet_id. Default implementation: Linear interpolation between edges. zeta_boundary=0.0: we're on vertex 0; zeta_boundary=1.0: we're on vertex 1.
virtual void boundary_zeta12 (const unsigned &facet_id, const double &zeta_boundary, Vector< double > &zeta)
Virtual function that specifies the variation of the zeta coordinates in the GeomObject along the boundary connecting vertices 1 and 2 in facet facet_id. Default implementation: Linear interpolation between edges. zeta_boundary=0.0: we're on vertex 1; zeta_boundary=1.0: we're on vertex 2.
virtual void boundary_zeta20 (const unsigned &facet_id, const double &zeta_boundary, Vector< double > &zeta)
Virtual function that specifies the variation of the zeta coordinates in the GeomObject along the boundary connecting vertices 2 and 0 in facet facet_id. Default implementation: Linear interpolation between edges. zeta_boundary=0.0: we're on vertex 2; zeta_boundary=1.0: we're on vertex 0.
Vector< unsigned > vertex_index_in_tetgen (const unsigned &f)
Facet connectivity: vertex_index[j] is the index of the j-th vertex (in the Vertex_pt vector) in facet f. Bit of an obscure functionality that's only needed for setup tetgen_io.
Additional Inherited Members
Protected Attributes inherited from oomph::TetMeshFacetedSurface
Vector< TetMeshVertex * > Vertex_pt
Vector pointers to vertices.
Vector< TetMeshFacet * > Facet_pt
Vector of pointers to facets.
bool Boundaries_can_be_split_in_tetgen
Boolean to indicate whether extra vertices can be added on the boundary in tetgen.
Vector< Vector< unsigned > > Facet_vertex_index_in_tetgen
Facet connectivity: Facet_vertex_index[f][j] is the index of the j-th vertex (in the Vertex_pt vector) in facet f.
DiskLikeGeomObjectWithBoundaries * Geom_object_with_boundaries_pt
GeomObject with boundaries associated with this surface.
Detailed Description
Definition at line 818 of file tet_mesh.h.
Constructor & Destructor Documentation
TetMeshFacetedClosedSurfaceForRemesh()
oomph::TetMeshFacetedClosedSurfaceForRemesh::TetMeshFacetedClosedSurfaceForRemesh (Vector< Node * > const & vertex_node_pt, Vector< Vector< unsigned > > const & facet_connectivity, Vector< unsigned > const & facet_boundary_id)
Constructor for a FacetedSurface created from a list of nodes and connectivity information. This is used in remeshing.
Definition at line 40 of file tet_mesh.cc.
References oomph::TetMeshFacetedSurface::Facet_pt, i, oomph::FiniteElement::size(), and oomph::TetMeshFacetedSurface::Vertex_pt.
~TetMeshFacetedClosedSurfaceForRemesh()
oomph::TetMeshFacetedClosedSurfaceForRemesh::~TetMeshFacetedClosedSurfaceForRemesh () [virtual]
Destructor. Delete allocated memory.
Definition at line 73 of file tet_mesh.cc.
References oomph::TetMeshFacetedSurface::Facet_pt, oomph::TetMeshFacetedSurface::nfacet(), oomph::TetMeshFacetedSurface::nvertex(), and oomph::TetMeshFacetedSurface::Vertex_pt.
The documentation for this class was generated from the following files:
tet_mesh.h
tet_mesh.cc