oomph::MacroElementNodeUpdateElementBase Class Reference
////////////////////////////////////////////////////////////////////
#include <macro_element_node_update_element.h>
Public Member Functions
MacroElementNodeUpdateElementBase ()
Constructor (empty)
MacroElementNodeUpdateElementBase (const MacroElementNodeUpdateElementBase &)=delete
Broken copy constructor.
void operator= (const MacroElementNodeUpdateElementBase &)=delete
Broken assignment operator.
virtual ~MacroElementNodeUpdateElementBase ()
Virtual destructor (empty)
virtual void set_node_update_info (const Vector< GeomObject * > &geom_object_pt)=0
Set node update information: Pass the vector of (pointers to) the geometric objects that affect the node update. This gets passed on to all nodes in the element.
unsigned ngeom_object ()
Number of geometric objects involved in node update function.
Vector< GeomObject * > & geom_object_pt ()
Vector of (pointers to) geometric objects involved in node update function.
GeomObject * geom_object_pt (const unsigned &i)
Pointer to i-th geometric object involved in node update function.
Protected Attributes
Vector< GeomObject * > Geom_object_pt
Vector of geometric objects that are involved in the node update operation.
Detailed Description
////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////// Base class for elements that allow MacroElement-based node update
Definition at line 196 of file macro_element_node_update_element.h.
Constructor & Destructor Documentation
MacroElementNodeUpdateElementBase() [1/2]
oomph::MacroElementNodeUpdateElementBase::MacroElementNodeUpdateElementBase () [inline]
Constructor (empty)
Definition at line 200 of file macro_element_node_update_element.h.
MacroElementNodeUpdateElementBase() [2/2]
oomph::MacroElementNodeUpdateElementBase::MacroElementNodeUpdateElementBase (const MacroElementNodeUpdateElementBase &) [delete]
Broken copy constructor.
 MacroElementNodeUpdateElementBase()
virtual oomph::MacroElementNodeUpdateElementBase::~MacroElementNodeUpdateElementBase () [inline], [virtual]
Virtual destructor (empty)
Definition at line 210 of file macro_element_node_update_element.h.
Member Function Documentation
geom_object_pt() [1/2]
Vector< GeomObject * > & oomph::MacroElementNodeUpdateElementBase::geom_object_pt () [inline]
Vector of (pointers to) geometric objects involved in node update function.
Definition at line 227 of file macro_element_node_update_element.h.
References Geom_object_pt.
Referenced by oomph::RefineableQElement< 3 >::build(), oomph::RefineableQElement< 1 >::build(), oomph::RefineableQElement< 2 >::build(), oomph::MacroElementNodeUpdateMesh::distribute(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::pre_build(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::rebuild_from_sons(), and oomph::MacroElementNodeUpdateElement< ELEMENT >::set_node_update_info().
geom_object_pt() [2/2]
GeomObject * oomph::MacroElementNodeUpdateElementBase::geom_object_pt (const unsigned & i) [inline]
Pointer to i-th geometric object involved in node update function.
Definition at line 234 of file macro_element_node_update_element.h.
References Geom_object_pt, and i.
ngeom_object()
unsigned oomph::MacroElementNodeUpdateElementBase::ngeom_object () [inline]
Number of geometric objects involved in node update function.
Definition at line 220 of file macro_element_node_update_element.h.
References Geom_object_pt.
Referenced by oomph::MacroElementNodeUpdateElement< ELEMENT >::set_node_update_info().
operator=()
void oomph::MacroElementNodeUpdateElementBase::operator= (const MacroElementNodeUpdateElementBase &) [delete]
Broken assignment operator.
set_node_update_info()
virtual void oomph::MacroElementNodeUpdateElementBase::set_node_update_info (const Vector< GeomObject * > & geom_object_pt) [pure virtual]
Set node update information: Pass the vector of (pointers to) the geometric objects that affect the node update. This gets passed on to all nodes in the element.
Implemented in oomph::MacroElementNodeUpdateElement< ELEMENT >.
Referenced by oomph::RefineableQElement< 3 >::build(), oomph::RefineableQElement< 1 >::build(), oomph::RefineableQElement< 2 >::build(), oomph::MacroElementNodeUpdateMesh::distribute(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::p_refine(), and oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::pre_build().
Member Data Documentation
Geom_object_pt
Vector<GeomObject*> oomph::MacroElementNodeUpdateElementBase::Geom_object_pt [protected]
Vector of geometric objects that are involved in the node update operation.
Definition at line 243 of file macro_element_node_update_element.h.
Referenced by geom_object_pt(), ngeom_object(), oomph::MacroElementNodeUpdateElement< ELEMENT >::rebuild_from_sons(), and oomph::MacroElementNodeUpdateElement< ELEMENT >::set_node_update_info().
The documentation for this class was generated from the following file:
macro_element_node_update_element.h