oomph::RefineablePolarTaylorHoodElement Class Reference
Refineable version of Polar Taylor Hood elements. These classes can be written in total generality.
#include <refineable_polar_navier_stokes_elements.h>
Public Member Functions
RefineablePolarTaylorHoodElement ()
Constructor.
unsigned required_nvalue (const unsigned &n) const
Number of values required at local node n. In order to simplify matters, we allocate storage for pressure variables at all the nodes and then pin those that are not used.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: (DIM velocities + 1 pressure)
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: empty.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void further_setup_hanging_nodes ()
Perform additional hanging node procedures for variables that are not interpolated by all nodes. The pressures are stored at the p_nodal_index_pnst-th location in each node.
Node * interpolating_node_pt (const unsigned &n, const int &value_id)
The velocities are isoparametric and so the `nodes` interpolating the velocities are the geometric nodes. The pressure `nodes` are a subset of the nodes, so when value_id==DIM, the n-th pressure node is returned.
double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
The pressure nodes are the corner nodes, so when n_value==DIM, the fraction is the same as the 1d node number, 0 or 1.
Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
The velocity nodes are the same as the geometric nodes. The pressure nodes must be calculated by using the same methods as the geometric nodes, but by recalling that there are only two pressure nodes per edge.
unsigned ninterpolating_node_1d (const int &value_id)
The number of 1d pressure nodes is 2, the number of 1d velocity nodes is the same as the number of 1d geometric nodes.
unsigned ninterpolating_node (const int &value_id)
The number of pressure nodes is 2^DIM. The number of velocity nodes is the same as the number of geometric nodes.
void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
The basis interpolating the pressure is given by pshape(). / The basis interpolating the velocity is shape().
void insert_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs containing.
Private Member Functions
Node * pressure_node_pt (const unsigned &n_p)
Pointer to n_p-th pressure node.
void unpin_elemental_pressure_dofs ()
Unpin all pressure dofs.
void pin_elemental_redundant_nodal_pressure_dofs ()
Pin all nodal pressure dofs that are not required.
Additional Inherited Members
Detailed Description
Refineable version of Polar Taylor Hood elements. These classes can be written in total generality.
Definition at line 220 of file refineable_polar_navier_stokes_elements.h.
Constructor & Destructor Documentation
RefineablePolarTaylorHoodElement()
oomph::RefineablePolarTaylorHoodElement::RefineablePolarTaylorHoodElement () [inline]
Constructor.
Definition at line 272 of file refineable_polar_navier_stokes_elements.h.
Member Function Documentation
further_setup_hanging_nodes()
void oomph::RefineablePolarTaylorHoodElement::further_setup_hanging_nodes () [inline], [virtual]
Perform additional hanging node procedures for variables that are not interpolated by all nodes. The pressures are stored at the p_nodal_index_pnst-th location in each node.
Implements oomph::RefineableQElement< 2 >.
Definition at line 403 of file refineable_polar_navier_stokes_elements.h.
References oomph::PolarTaylorHoodElement::p_nodal_index_pnst(), and oomph::RefineableQElement< 2 >::setup_hang_for_value().
get_interpolated_values() [1/2]
void oomph::RefineablePolarTaylorHoodElement::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 341 of file refineable_polar_navier_stokes_elements.h.
References i, oomph::PolarNavierStokesEquations::interpolated_p_pnst(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::nprev_values(), oomph::Tree::object_pt(), oomph::Tree::root_pt(), oomph::FiniteElement::shape(), t, oomph::Data::time_stepper_pt(), oomph::RefineableElement::tree_pt(), and oomph::PolarNavierStokesEquations::u_index_pnst().
get_interpolated_values() [2/2]
void oomph::RefineablePolarTaylorHoodElement::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 321 of file refineable_polar_navier_stokes_elements.h.
References i, oomph::PolarNavierStokesEquations::interpolated_p_pnst(), and oomph::PolarNavierStokesEquations::interpolated_u_pnst().
get_interpolating_node_at_local_coordinate()
Node * oomph::RefineablePolarTaylorHoodElement::get_interpolating_node_at_local_coordinate (const Vector< double > & s, const int & value_id) [inline], [virtual]
The velocity nodes are the same as the geometric nodes. The pressure nodes must be calculated by using the same methods as the geometric nodes, but by recalling that there are only two pressure nodes per edge.
Construct the general pressure index from the components.
Reimplemented from oomph::RefineableElement.
Definition at line 449 of file refineable_polar_navier_stokes_elements.h.
References oomph::FiniteElement::get_node_at_local_coordinate(), i, oomph::FiniteElement::Node_location_tolerance, pressure_node_pt(), and s.
insert_load_data()
void oomph::RefineablePolarTaylorHoodElement::insert_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data) [inline]
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function. (Overloads non-refineable version and takes hanging nodes into account)
Definition at line 562 of file refineable_polar_navier_stokes_elements.h.
References oomph::Node::hanging_pt(), i, oomph::Node::is_hanging(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::PolarTaylorHoodElement::npres_pnst(), oomph::PolarTaylorHoodElement::p_nodal_index_pnst(), pressure_node_pt(), and oomph::PolarNavierStokesEquations::u_index_pnst().
interpolating_basis()
void oomph::RefineablePolarTaylorHoodElement::interpolating_basis (const Vector< double > & s, Shape & psi, const int & value_id) const [inline], [virtual]
The basis interpolating the pressure is given by pshape(). / The basis interpolating the velocity is shape().
Reimplemented from oomph::RefineableElement.
Definition at line 538 of file refineable_polar_navier_stokes_elements.h.
References oomph::PolarTaylorHoodElement::pshape_pnst(), and oomph::FiniteElement::shape().
interpolating_node_pt()
Node * oomph::RefineablePolarTaylorHoodElement::interpolating_node_pt (const unsigned & n, const int & value_id) [inline], [virtual]
The velocities are isoparametric and so the `nodes` interpolating the velocities are the geometric nodes. The pressure `nodes` are a subset of the nodes, so when value_id==DIM, the n-th pressure node is returned.
Reimplemented from oomph::RefineableElement.
Definition at line 412 of file refineable_polar_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt(), and pressure_node_pt().
local_one_d_fraction_of_interpolating_node()
double oomph::RefineablePolarTaylorHoodElement::local_one_d_fraction_of_interpolating_node (const unsigned & n1d, const unsigned & i, const int & value_id) [inline], [virtual]
The pressure nodes are the corner nodes, so when n_value==DIM, the fraction is the same as the 1d node number, 0 or 1.
Reimplemented from oomph::RefineableElement.
Definition at line 429 of file refineable_polar_navier_stokes_elements.h.
References i, and oomph::FiniteElement::local_one_d_fraction_of_node().
ncont_interpolated_values()
unsigned oomph::RefineablePolarTaylorHoodElement::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values: (DIM velocities + 1 pressure)
Implements oomph::RefineableElement.
Definition at line 290 of file refineable_polar_navier_stokes_elements.h.
ninterpolating_node()
unsigned oomph::RefineablePolarTaylorHoodElement::ninterpolating_node (const int & value_id) [inline], [virtual]
The number of pressure nodes is 2^DIM. The number of velocity nodes is the same as the number of geometric nodes.
Reimplemented from oomph::RefineableElement.
Definition at line 524 of file refineable_polar_navier_stokes_elements.h.
References oomph::FiniteElement::nnode().
ninterpolating_node_1d()
unsigned oomph::RefineablePolarTaylorHoodElement::ninterpolating_node_1d (const int & value_id) [inline], [virtual]
The number of 1d pressure nodes is 2, the number of 1d velocity nodes is the same as the number of 1d geometric nodes.
Reimplemented from oomph::RefineableElement.
Definition at line 510 of file refineable_polar_navier_stokes_elements.h.
References oomph::FiniteElement::nnode_1d().
nrecovery_order()
unsigned oomph::RefineablePolarTaylorHoodElement::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 300 of file refineable_polar_navier_stokes_elements.h.
nvertex_node()
unsigned oomph::RefineablePolarTaylorHoodElement::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 306 of file refineable_polar_navier_stokes_elements.h.
References oomph::FiniteElement::nvertex_node().
pin_elemental_redundant_nodal_pressure_dofs()
void oomph::RefineablePolarTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs () [inline], [private], [virtual]
Pin all nodal pressure dofs that are not required.
Reimplemented from oomph::RefineablePolarNavierStokesEquations.
Definition at line 246 of file refineable_polar_navier_stokes_elements.h.
References oomph::Node::is_hanging(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::PolarTaylorHoodElement::npres_pnst(), oomph::PolarTaylorHoodElement::p_nodal_index_pnst(), oomph::Data::pin(), pressure_node_pt(), and oomph::Data::unpin().
pressure_node_pt()
Node * oomph::RefineablePolarTaylorHoodElement::pressure_node_pt (const unsigned & n_p) [inline], [private], [virtual]
Pointer to n_p-th pressure node.
Reimplemented from oomph::PolarTaylorHoodElement.
Definition at line 227 of file refineable_polar_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::PolarTaylorHoodElement::Pconv.
Referenced by get_interpolating_node_at_local_coordinate(), insert_load_data(), interpolating_node_pt(), and pin_elemental_redundant_nodal_pressure_dofs().
rebuild_from_sons()
void oomph::RefineablePolarTaylorHoodElement::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
Rebuild from sons: empty.
Implements oomph::RefineableElement.
Definition at line 296 of file refineable_polar_navier_stokes_elements.h.
required_nvalue()
unsigned oomph::RefineablePolarTaylorHoodElement::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values required at local node n. In order to simplify matters, we allocate storage for pressure variables at all the nodes and then pin those that are not used.
Reimplemented from oomph::PolarTaylorHoodElement.
Definition at line 283 of file refineable_polar_navier_stokes_elements.h.
unpin_elemental_pressure_dofs()
void oomph::RefineablePolarTaylorHoodElement::unpin_elemental_pressure_dofs () [inline], [private], [virtual]
Unpin all pressure dofs.
Implements oomph::RefineablePolarNavierStokesEquations.
Definition at line 233 of file refineable_polar_navier_stokes_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::PolarTaylorHoodElement::p_nodal_index_pnst(), and oomph::Data::unpin().
vertex_node_pt()
Node * oomph::RefineablePolarTaylorHoodElement::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 312 of file refineable_polar_navier_stokes_elements.h.
References oomph::FiniteElement::vertex_node_pt().
The documentation for this class was generated from the following file:
refineable_polar_navier_stokes_elements.h