oomph::RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D > Class Template Reference
Refineable version of QAdvectionDiffusionReactionElement. Inherit from the standard QAdvectionDiffusionReactionElement and the appropriate refineable geometric element and the refineable equations.
#include <refineable_advection_diffusion_reaction_elements.h>
Public Member Functions
RefineableQAdvectionDiffusionReactionElement ()
Empty Constructor:
RefineableQAdvectionDiffusionReactionElement (const RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D > &dummy)
Broken copy constructor.
void operator= (const RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D > &)
Broken assignment operator.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: NREAGENT.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: empty.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
void further_setup_hanging_nodes ()
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty.
Additional Inherited Members
Detailed Description
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
class oomph::RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >
Refineable version of QAdvectionDiffusionReactionElement. Inherit from the standard QAdvectionDiffusionReactionElement and the appropriate refineable geometric element and the refineable equations.
Definition at line 211 of file refineable_advection_diffusion_reaction_elements.h.
Constructor & Destructor Documentation
RefineableQAdvectionDiffusionReactionElement() [1/2]
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
oomph::RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::RefineableQAdvectionDiffusionReactionElement () [inline]
Empty Constructor:
Definition at line 219 of file refineable_advection_diffusion_reaction_elements.h.
RefineableQAdvectionDiffusionReactionElement() [2/2]
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
oomph::RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::RefineableQAdvectionDiffusionReactionElement (const RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 229 of file refineable_advection_diffusion_reaction_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
further_setup_hanging_nodes()
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
void oomph::RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::further_setup_hanging_nodes () [inline], [virtual]
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty.
Reimplemented from oomph::RefineableElement.
Definition at line 280 of file refineable_advection_diffusion_reaction_elements.h.
ncont_interpolated_values()
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
unsigned oomph::RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values: NREAGENT.
Implements oomph::RefineableElement.
Definition at line 249 of file refineable_advection_diffusion_reaction_elements.h.
nrecovery_order()
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
unsigned oomph::RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 273 of file refineable_advection_diffusion_reaction_elements.h.
nvertex_node()
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
unsigned oomph::RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 255 of file refineable_advection_diffusion_reaction_elements.h.
References oomph::FiniteElement::nvertex_node().
operator=()
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
void oomph::RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::operator= (const RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D > &) [inline]
Broken assignment operator.
Definition at line 239 of file refineable_advection_diffusion_reaction_elements.h.
References oomph::BrokenCopy::broken_assign().
rebuild_from_sons()
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
void oomph::RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
Rebuild from sons: empty.
Implements oomph::RefineableElement.
Definition at line 269 of file refineable_advection_diffusion_reaction_elements.h.
vertex_node_pt()
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
Node* oomph::RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 262 of file refineable_advection_diffusion_reaction_elements.h.
References oomph::FiniteElement::vertex_node_pt().
The documentation for this class was generated from the following file:
refineable_advection_diffusion_reaction_elements.h