oomph::FullCircleMesh< ELEMENT > Class Template Reference
Full circle mesh class. The domain is specified by the GeomObject that identifies the entire area. Non-refineable base version!
#include <full_circle_mesh.template.h>
Public Member Functions
FullCircleMesh (GeomObject *wall_pt, const Vector< double > &theta_positions, const Vector< double > &radius_box, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass pointer to geometric object that specifies the area; values of theta at which dividing lines are to be placed, fractions of the radius for the central box at the dividing lines and the timestepper. Timestepper defaults to Steady dummy timestepper.
virtual ~FullCircleMesh ()
Destructor: empty.
GeomObject *& area_pt ()
Access function to GeomObject representing wall.
FullCircleDomain * domain_pt ()
Access function to domain.
FullCircleDomain * domain_pt () const
Access function to underlying domain.
Protected Attributes
FullCircleDomain * Domain_pt
Pointer to domain.
GeomObject * Area_pt
Pointer to the geometric object that represents the entire domain.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::FullCircleMesh< ELEMENT >
Full circle mesh class. The domain is specified by the GeomObject that identifies the entire area. Non-refineable base version!
The mesh boundaries are numbered as follows:
Boundary 0: The outer wall, represented by $\xi_1 = 1$.
Definition at line 49 of file full_circle_mesh.template.h.
Constructor & Destructor Documentation
FullCircleMesh()
template<class ELEMENT >
oomph::FullCircleMesh< ELEMENT >::FullCircleMesh (GeomObject * wall_pt, const Vector< double > & theta_positions, const Vector< double > & radius_box, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass pointer to geometric object that specifies the area; values of theta at which dividing lines are to be placed, fractions of the radius for the central box at the dividing lines and the timestepper. Timestepper defaults to Steady dummy timestepper.
Constructor for deformable quarter tube mesh class. The domain is specified by the GeomObject that identifies the entire volume.
Definition at line 40 of file full_circle_mesh.template.cc.
References oomph::Mesh::add_boundary_node(), oomph::FullCircleMesh< ELEMENT >::area_pt(), oomph::Mesh::Boundary_coordinate_exists, oomph::FiniteElement::construct_node(), oomph::Mesh::convert_to_boundary_node(), oomph::FullCircleMesh< ELEMENT >::Domain_pt, oomph::Mesh::Element_pt, oomph::Mesh::finite_element_pt(), i, oomph::Domain::macro_element_pt(), oomph::MacroElement::macro_map(), oomph::FiniteElement::node_pt(), oomph::Mesh::Node_pt, oomph::Mesh::node_pt(), oomph::oomph_info, oomph::MathematicalConstants::Pi, s, oomph::Mesh::set_nboundary(), oomph::QuadMeshBase::setup_boundary_element_info(), oomph::Global_string_for_annotation::string(), and oomph::Node::x().
 FullCircleMesh()
template<class ELEMENT >
virtual oomph::FullCircleMesh< ELEMENT >::~FullCircleMesh () [inline], [virtual]
Destructor: empty.
Definition at line 63 of file full_circle_mesh.template.h.
References oomph::FullCircleMesh< ELEMENT >::Domain_pt.
Member Function Documentation
area_pt()
template<class ELEMENT >
GeomObject*& oomph::FullCircleMesh< ELEMENT >::area_pt () [inline]
Access function to GeomObject representing wall.
Definition at line 69 of file full_circle_mesh.template.h.
References oomph::FullCircleMesh< ELEMENT >::Area_pt.
Referenced by oomph::FullCircleMesh< ELEMENT >::FullCircleMesh().
domain_pt() [1/2]
template<class ELEMENT >
FullCircleDomain* oomph::FullCircleMesh< ELEMENT >::domain_pt () [inline]
Access function to domain.
Definition at line 75 of file full_circle_mesh.template.h.
References oomph::FullCircleMesh< ELEMENT >::Domain_pt.
domain_pt() [2/2]
template<class ELEMENT >
FullCircleDomain* oomph::FullCircleMesh< ELEMENT >::domain_pt () const [inline]
Access function to underlying domain.
Definition at line 81 of file full_circle_mesh.template.h.
References oomph::FullCircleMesh< ELEMENT >::Domain_pt.
Member Data Documentation
Area_pt
template<class ELEMENT >
GeomObject* oomph::FullCircleMesh< ELEMENT >::Area_pt [protected]
Pointer to the geometric object that represents the entire domain.
Definition at line 91 of file full_circle_mesh.template.h.
Referenced by oomph::FullCircleMesh< ELEMENT >::area_pt().
Domain_pt
template<class ELEMENT >
FullCircleDomain* oomph::FullCircleMesh< ELEMENT >::Domain_pt [protected]
Pointer to domain.
Definition at line 88 of file full_circle_mesh.template.h.
Referenced by oomph::FullCircleMesh< ELEMENT >::domain_pt(), oomph::FullCircleMesh< ELEMENT >::FullCircleMesh(), oomph::RefineableFullCircleMesh< ELEMENT >::RefineableFullCircleMesh(), and oomph::FullCircleMesh< ELEMENT >::~FullCircleMesh().
The documentation for this class was generated from the following files:
full_circle_mesh.template.h
full_circle_mesh.template.cc