oomph::LinearisedNavierStokesEigenfunctionNormalisationElement Class Reference
A class that is used to implement the constraint that the eigenfunction has a particular normalisation. This element stores the two components of the eigenvalue.
#include <linearised_navier_stokes_eigenvalue_elements.h>
Public Member Functions
LinearisedNavierStokesEigenfunctionNormalisationElement (std::complex< double > *const &normalisation_pt)
Constructor: Pass pointer to target volume. `Pressure` value that `traded` for the volume contraint is created internally (as a Data item with a single pressure value)
~LinearisedNavierStokesEigenfunctionNormalisationElement ()
Constructor: Pass pointer to target volume, pointer to Data item whose value specified by index_of_traded_pressure represents the `Pressure` value that `traded` for the volume contraint. The Data is stored as external Data for this element.
Data * eigenvalue_data_pt ()
Access to Data that contains the traded pressure.
double eigenvalue (const unsigned &i)
Return the traded pressure value.
unsigned index_of_eigenvalue ()
Return the index of Data object at which the traded pressure is stored.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in the residuals for the volume constraint.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Fill in the residuals and jacobian for the volume constraint.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Fill in the residuals, jacobian and mass matrix for the volume constraint.
Private Member Functions
int eigenvalue_local_eqn (const unsigned &i)
The local eqn number for the traded pressure.
void fill_in_generic_contribution_to_residuals_normalisation (Vector< double > &residuals)
Fill in the residuals for the volume constraint.
Private Attributes
std::complex< double > * Normalisation_pt
Pointer to the desired normalisation.
unsigned External_or_internal_data_index_of_eigenvalue
Storage for the initial index of the eigenvalue.
unsigned Index_of_eigenvalue
Storage for the offset index of the eigenvalue.
Additional Inherited Members
Detailed Description
A class that is used to implement the constraint that the eigenfunction has a particular normalisation. This element stores the two components of the eigenvalue.
Definition at line 50 of file linearised_navier_stokes_eigenvalue_elements.h.
Constructor & Destructor Documentation
LinearisedNavierStokesEigenfunctionNormalisationElement()
oomph::LinearisedNavierStokesEigenfunctionNormalisationElement::LinearisedNavierStokesEigenfunctionNormalisationElement (std::complex< double > *const & normalisation_pt)
Constructor: Pass pointer to target volume. `Pressure` value that `traded` for the volume contraint is created internally (as a Data item with a single pressure value)
Definition at line 72 of file linearised_navier_stokes_eigenvalue_elements.cc.
References oomph::GeneralisedElement::add_internal_data(), External_or_internal_data_index_of_eigenvalue, Index_of_eigenvalue, and Normalisation_pt.
 LinearisedNavierStokesEigenfunctionNormalisationElement()
oomph::LinearisedNavierStokesEigenfunctionNormalisationElement::~LinearisedNavierStokesEigenfunctionNormalisationElement () [inline]
Constructor: Pass pointer to target volume, pointer to Data item whose value specified by index_of_traded_pressure represents the `Pressure` value that `traded` for the volume contraint. The Data is stored as external Data for this element.
Empty destructor
Definition at line 91 of file linearised_navier_stokes_eigenvalue_elements.h.
Member Function Documentation
eigenvalue()
double oomph::LinearisedNavierStokesEigenfunctionNormalisationElement::eigenvalue (const unsigned & i) [inline]
Return the traded pressure value.
Definition at line 100 of file linearised_navier_stokes_eigenvalue_elements.h.
References eigenvalue_data_pt(), i, Index_of_eigenvalue, and oomph::Data::value().
Referenced by fill_in_generic_contribution_to_residuals_normalisation().
eigenvalue_data_pt()
Data* oomph::LinearisedNavierStokesEigenfunctionNormalisationElement::eigenvalue_data_pt () [inline]
Access to Data that contains the traded pressure.
Definition at line 94 of file linearised_navier_stokes_eigenvalue_elements.h.
References External_or_internal_data_index_of_eigenvalue, and oomph::GeneralisedElement::internal_data_pt().
Referenced by eigenvalue(), and oomph::LinearisedNavierStokesEquations::set_eigenfunction_normalisation_element().
eigenvalue_local_eqn()
int oomph::LinearisedNavierStokesEigenfunctionNormalisationElement::eigenvalue_local_eqn (const unsigned & i) [inline], [private]
The local eqn number for the traded pressure.
Definition at line 65 of file linearised_navier_stokes_eigenvalue_elements.h.
References i, Index_of_eigenvalue, and oomph::GeneralisedElement::internal_local_eqn().
Referenced by fill_in_contribution_to_jacobian(), and fill_in_generic_contribution_to_residuals_normalisation().
fill_in_contribution_to_jacobian()
void oomph::LinearisedNavierStokesEigenfunctionNormalisationElement::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Fill in the residuals and jacobian for the volume constraint.
Reimplemented from oomph::GeneralisedElement.
Definition at line 119 of file linearised_navier_stokes_eigenvalue_elements.h.
References eigenvalue_local_eqn(), and fill_in_generic_contribution_to_residuals_normalisation().
fill_in_contribution_to_jacobian_and_mass_matrix()
void oomph::LinearisedNavierStokesEigenfunctionNormalisationElement::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline], [virtual]
Fill in the residuals, jacobian and mass matrix for the volume constraint.
Reimplemented from oomph::GeneralisedElement.
Definition at line 135 of file linearised_navier_stokes_eigenvalue_elements.h.
References fill_in_generic_contribution_to_residuals_normalisation().
fill_in_contribution_to_residuals()
void oomph::LinearisedNavierStokesEigenfunctionNormalisationElement::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Fill in the residuals for the volume constraint.
Reimplemented from oomph::GeneralisedElement.
Definition at line 113 of file linearised_navier_stokes_eigenvalue_elements.h.
References fill_in_generic_contribution_to_residuals_normalisation().
fill_in_generic_contribution_to_residuals_normalisation()
void oomph::LinearisedNavierStokesEigenfunctionNormalisationElement::fill_in_generic_contribution_to_residuals_normalisation (Vector< double > & residuals) [private]
Fill in the residuals for the volume constraint.
Definition at line 37 of file linearised_navier_stokes_eigenvalue_elements.cc.
References eigenvalue(), and eigenvalue_local_eqn().
Referenced by fill_in_contribution_to_jacobian(), fill_in_contribution_to_jacobian_and_mass_matrix(), and fill_in_contribution_to_residuals().
index_of_eigenvalue()
unsigned oomph::LinearisedNavierStokesEigenfunctionNormalisationElement::index_of_eigenvalue () [inline]
Return the index of Data object at which the traded pressure is stored.
Definition at line 106 of file linearised_navier_stokes_eigenvalue_elements.h.
References Index_of_eigenvalue.
Referenced by oomph::LinearisedNavierStokesEquations::set_eigenfunction_normalisation_element().
Member Data Documentation
External_or_internal_data_index_of_eigenvalue
unsigned oomph::LinearisedNavierStokesEigenfunctionNormalisationElement::External_or_internal_data_index_of_eigenvalue [private]
Storage for the initial index of the eigenvalue.
Definition at line 58 of file linearised_navier_stokes_eigenvalue_elements.h.
Referenced by eigenvalue_data_pt(), and LinearisedNavierStokesEigenfunctionNormalisationElement().
Index_of_eigenvalue
unsigned oomph::LinearisedNavierStokesEigenfunctionNormalisationElement::Index_of_eigenvalue [private]
Storage for the offset index of the eigenvalue.
Definition at line 61 of file linearised_navier_stokes_eigenvalue_elements.h.
Referenced by eigenvalue(), eigenvalue_local_eqn(), index_of_eigenvalue(), and LinearisedNavierStokesEigenfunctionNormalisationElement().
Normalisation_pt
std::complex<double>* oomph::LinearisedNavierStokesEigenfunctionNormalisationElement::Normalisation_pt [private]
Pointer to the desired normalisation.
Definition at line 55 of file linearised_navier_stokes_eigenvalue_elements.h.
Referenced by LinearisedNavierStokesEigenfunctionNormalisationElement().
The documentation for this class was generated from the following files:
linearised_navier_stokes_eigenvalue_elements.h
linearised_navier_stokes_eigenvalue_elements.cc