oomph::SimpleRectangularQuadMesh< ELEMENT > Class Template Reference
Simple rectangular 2D Quad mesh class. Nx : number of elements in the x direction.
#include <simple_rectangular_quadmesh.template.h>
Public Member Functions
SimpleRectangularQuadMesh (const unsigned &Nx, const unsigned &Ny, const double &Lx, const double &Ly, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass number of elements in the horizontal and vertical directions, and the corresponding dimensions. Timestepper defaults to Steady.
const unsigned & nx () const
Access function for number of elements in x directions.
const unsigned & ny () const
Access function for number of elements in y directions.
Private Attributes
unsigned NX
Number of elements in x direction.
unsigned NY
Number of elements in y direction.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::SimpleRectangularQuadMesh< ELEMENT >
Simple rectangular 2D Quad mesh class. Nx : number of elements in the x direction.
Ny : number of elements in the y direction
Lx : length in the x direction
Ly : length in the y direction
Ordering of elements: 'Lower left' to 'lower right' then 'upwards'
Timestepper defaults to Steady.
Definition at line 57 of file simple_rectangular_quadmesh.template.h.
Constructor & Destructor Documentation
SimpleRectangularQuadMesh()
template<class ELEMENT >
oomph::SimpleRectangularQuadMesh< ELEMENT >::SimpleRectangularQuadMesh (const unsigned & Nx, const unsigned & Ny, const double & Lx, const double & Ly, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass number of elements in the horizontal and vertical directions, and the corresponding dimensions. Timestepper defaults to Steady.
Constructor for 2D Quad mesh class:
Nx : number of elements in the x direction
Ny : number of elements in the y direction
Lx : length in the x direction
Ly : length in the y direction
Ordering of elements: 'Lower left' to 'lower right' then 'upwards'
Timestepper defaults to Steady.
Definition at line 51 of file simple_rectangular_quadmesh.template.cc.
References i.
Member Function Documentation
nx()
template<class ELEMENT >
const unsigned & oomph::SimpleRectangularQuadMesh< ELEMENT >::nx () const [inline]
Access function for number of elements in x directions.
Definition at line 71 of file simple_rectangular_quadmesh.template.h.
References oomph::SimpleRectangularQuadMesh< ELEMENT >::NX.
Referenced by oomph::FSIDrivenCavityMesh< ELEMENT >::FSIDrivenCavityMesh().
ny()
template<class ELEMENT >
const unsigned & oomph::SimpleRectangularQuadMesh< ELEMENT >::ny () const [inline]
Access function for number of elements in y directions.
Definition at line 77 of file simple_rectangular_quadmesh.template.h.
References oomph::SimpleRectangularQuadMesh< ELEMENT >::NY.
Referenced by oomph::CollapsibleChannelMesh< ELEMENT >::CollapsibleChannelMesh(), and oomph::FSIDrivenCavityMesh< ELEMENT >::FSIDrivenCavityMesh().
Member Data Documentation
NX
template<class ELEMENT >
unsigned oomph::SimpleRectangularQuadMesh< ELEMENT >::NX [private]
Number of elements in x direction.
Definition at line 84 of file simple_rectangular_quadmesh.template.h.
Referenced by oomph::SimpleRectangularQuadMesh< ELEMENT >::nx().
NY
template<class ELEMENT >
unsigned oomph::SimpleRectangularQuadMesh< ELEMENT >::NY [private]
Number of elements in y direction.
Definition at line 87 of file simple_rectangular_quadmesh.template.h.
Referenced by oomph::SimpleRectangularQuadMesh< ELEMENT >::ny().
The documentation for this class was generated from the following files:
simple_rectangular_quadmesh.template.h
simple_rectangular_quadmesh.template.cc