oomph::QLinearElasticityElement< DIM, NNODE_1D > Class Template Reference
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
#include <linear_elasticity_elements.h>
Public Member Functions
QLinearElasticityElement ()
Constructor.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact solution x,y,[z],u,v,[w].
void output (std::ostream &outfile)
Output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
void output (FILE *file_pt)
C-style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function.
Additional Inherited Members
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::QLinearElasticityElement< DIM, NNODE_1D >
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
An Element that solves the equations of linear elasticity in Cartesian coordinates, using QElements for the geometry
Definition at line 485 of file linear_elasticity_elements.h.
Constructor & Destructor Documentation
QLinearElasticityElement()
template<unsigned DIM, unsigned NNODE_1D>
oomph::QLinearElasticityElement< DIM, NNODE_1D >::QLinearElasticityElement () [inline]
Constructor.
Definition at line 490 of file linear_elasticity_elements.h.
Member Function Documentation
output() [1/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QLinearElasticityElement< DIM, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function.
Reimplemented from oomph::LinearElasticityEquations< DIM >.
Definition at line 517 of file linear_elasticity_elements.h.
References oomph::LinearElasticityEquations< DIM >::output().
output() [2/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QLinearElasticityElement< DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function.
Reimplemented from oomph::LinearElasticityEquations< DIM >.
Definition at line 523 of file linear_elasticity_elements.h.
References oomph::LinearElasticityEquations< DIM >::output().
output() [3/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QLinearElasticityElement< DIM, NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function.
Reimplemented from oomph::LinearElasticityEquations< DIM >.
Definition at line 504 of file linear_elasticity_elements.h.
References oomph::LinearElasticityEquations< DIM >::output().
output() [4/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QLinearElasticityElement< DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function.
Reimplemented from oomph::LinearElasticityEquations< DIM >.
Definition at line 510 of file linear_elasticity_elements.h.
References oomph::LinearElasticityEquations< DIM >::output().
output_fct()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QLinearElasticityElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output exact solution x,y,[z],u,v,[w].
Reimplemented from oomph::LinearElasticityEquations< DIM >.
Definition at line 496 of file linear_elasticity_elements.h.
References oomph::LinearElasticityEquations< DIM >::output_fct().
The documentation for this class was generated from the following file:
linear_elasticity_elements.h