oomph::QPVDElementWithPressure< DIM > Class Template Reference
#include <solid_elements.h>
Public Member Functions
bool has_internal_solid_data ()
There is internal solid data so we can't use the automatic assignment of consistent initial conditions for time-dependent problems.
QPVDElementWithPressure ()
Constructor, there are DIM+1 internal data points.
double solid_p (const unsigned &l)
Return the lth pressure value.
void set_solid_p (const unsigned &l, const double &p_value)
Set the l-th pressure value to p_value.
unsigned npres_solid () const
Return number of pressure values.
void fix_solid_pressure (const unsigned &l, const double &pvalue)
Fix the pressure dof l to be the value pvalue.
void output (std::ostream &outfile)
Generic FiniteElement output function.
void output (std::ostream &outfile, const unsigned &n_plot)
PVDEquationsWithPressure output function.
void output (FILE *file_pt)
C-style Generic FiniteElement output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style PVDEquationsWithPressure output function.
Protected Member Functions
int solid_p_local_eqn (const unsigned &i) const
Overload the access function that is used to return local equation corresponding to the i-th solid pressure value.
void solid_pshape (const Vector< double > &s, Shape &psi) const
Return the pressure shape functions.
void solid_pshape (const Vector< double > &s, Shape &psi) const
Pressure shape functions for 2D QPVDElementWithPressure elements.
void solid_pshape (const Vector< double > &s, Shape &psi) const
Pressure shape functions for 3D QPVDElementWithPressure elements.
Protected Attributes
unsigned P_solid_internal_index
Internal index that indicates at which internal data value the solid presure is stored.
Private Member Functions
void unpin_elemental_solid_pressure_dofs ()
Unpin all solid pressure dofs in the element.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::QPVDElementWithPressure< DIM >
An Element that solves the equations of solid mechanics, using the principle of virtual displacements, with quadratic interpolation for the positions and a discontinuous linear solid pressure. This is analogous to the QCrouzeixRaviartElement element for fluids.
Definition at line 1330 of file solid_elements.h.
Constructor & Destructor Documentation
QPVDElementWithPressure()
template<unsigned DIM>
oomph::QPVDElementWithPressure< DIM >::QPVDElementWithPressure () [inline]
Constructor, there are DIM+1 internal data points.
Definition at line 1369 of file solid_elements.h.
References oomph::GeneralisedElement::add_internal_data(), Data, and oomph::QPVDElementWithPressure< DIM >::P_solid_internal_index.
Member Function Documentation
fix_solid_pressure()
template<unsigned DIM>
void oomph::QPVDElementWithPressure< DIM >::fix_solid_pressure (const unsigned & l, const double & pvalue) [inline]
Fix the pressure dof l to be the value pvalue.
Definition at line 1396 of file solid_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), oomph::Data::pin(), and oomph::Data::set_value().
has_internal_solid_data()
template<unsigned DIM>
bool oomph::QPVDElementWithPressure< DIM >::has_internal_solid_data () [inline], [virtual]
There is internal solid data so we can't use the automatic assignment of consistent initial conditions for time-dependent problems.
Reimplemented from oomph::SolidFiniteElement.
Definition at line 1363 of file solid_elements.h.
npres_solid()
template<unsigned DIM>
unsigned oomph::QPVDElementWithPressure< DIM >::npres_solid () const [inline], [virtual]
Return number of pressure values.
Reimplemented from oomph::PVDEquationsBase< DIM >.
Definition at line 1390 of file solid_elements.h.
Referenced by oomph::RefineableQPVDElementWithPressure< DIM >::unpin_elemental_solid_pressure_dofs(), and oomph::QPVDElementWithPressure< DIM >::unpin_elemental_solid_pressure_dofs().
output() [1/4]
template<unsigned DIM>
void oomph::QPVDElementWithPressure< DIM >::output (FILE * file_pt) [inline], [virtual]
C-style Generic FiniteElement output function.
Reimplemented from oomph::PVDEquationsWithPressure< DIM >.
Definition at line 1416 of file solid_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<unsigned DIM>
void oomph::QPVDElementWithPressure< DIM >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style PVDEquationsWithPressure output function.
Reimplemented from oomph::PVDEquationsWithPressure< DIM >.
Definition at line 1422 of file solid_elements.h.
References oomph::PVDEquationsWithPressure< DIM >::output().
output() [3/4]
template<unsigned DIM>
void oomph::QPVDElementWithPressure< DIM >::output (std::ostream & outfile) [inline], [virtual]
Generic FiniteElement output function.
Reimplemented from oomph::PVDEquationsWithPressure< DIM >.
Definition at line 1403 of file solid_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<unsigned DIM>
void oomph::QPVDElementWithPressure< DIM >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
PVDEquationsWithPressure output function.
Reimplemented from oomph::PVDEquationsWithPressure< DIM >.
Definition at line 1409 of file solid_elements.h.
References oomph::PVDEquationsWithPressure< DIM >::output().
set_solid_p()
template<unsigned DIM>
void oomph::QPVDElementWithPressure< DIM >::set_solid_p (const unsigned & l, const double & p_value) [inline], [virtual]
Set the l-th pressure value to p_value.
Implements oomph::PVDEquationsWithPressure< DIM >.
Definition at line 1384 of file solid_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), and oomph::Data::set_value().
solid_p()
template<unsigned DIM>
double oomph::QPVDElementWithPressure< DIM >::solid_p (const unsigned & l) [inline], [virtual]
Return the lth pressure value.
Implements oomph::PVDEquationsWithPressure< DIM >.
Definition at line 1378 of file solid_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), and oomph::Data::value().
Referenced by oomph::RefineableQPVDElementWithPressure< DIM >::further_build().
solid_p_local_eqn()
template<unsigned DIM>
int oomph::QPVDElementWithPressure< DIM >::solid_p_local_eqn (const unsigned & i) const [inline], [protected], [virtual]
Overload the access function that is used to return local equation corresponding to the i-th solid pressure value.
Reimplemented from oomph::PVDEquationsBase< DIM >.
Definition at line 1352 of file solid_elements.h.
References i, and oomph::GeneralisedElement::internal_local_eqn().
solid_pshape() [1/3]
template<unsigned DIM>
void oomph::QPVDElementWithPressure< DIM >::solid_pshape (const Vector< double > & s, Shape & psi) const [inline], [protected], [virtual]
Return the pressure shape functions.
Implements oomph::PVDEquationsWithPressure< DIM >.
solid_pshape() [2/3]
void oomph::QPVDElementWithPressure< 2 >::solid_pshape (const Vector< double > & s, Shape & psi) const [inline], [protected], [virtual]
Pressure shape functions for 2D QPVDElementWithPressure elements.
Implements oomph::PVDEquationsWithPressure< DIM >.
Definition at line 1433 of file solid_elements.h.
References s.
solid_pshape() [3/3]
void oomph::QPVDElementWithPressure< 3 >::solid_pshape (const Vector< double > & s, Shape & psi) const [inline], [protected], [virtual]
Pressure shape functions for 3D QPVDElementWithPressure elements.
Implements oomph::PVDEquationsWithPressure< DIM >.
Definition at line 1446 of file solid_elements.h.
References s.
unpin_elemental_solid_pressure_dofs()
template<unsigned DIM>
void oomph::QPVDElementWithPressure< DIM >::unpin_elemental_solid_pressure_dofs () [inline], [private], [virtual]
Unpin all solid pressure dofs in the element.
Implements oomph::PVDEquationsBase< DIM >.
Definition at line 1334 of file solid_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), oomph::QPVDElementWithPressure< DIM >::npres_solid(), oomph::QPVDElementWithPressure< DIM >::P_solid_internal_index, and oomph::Data::unpin().
Member Data Documentation
P_solid_internal_index
template<unsigned DIM>
unsigned oomph::QPVDElementWithPressure< DIM >::P_solid_internal_index [protected]
Internal index that indicates at which internal data value the solid presure is stored.
Definition at line 1347 of file solid_elements.h.
Referenced by oomph::QPVDElementWithPressure< DIM >::QPVDElementWithPressure(), oomph::RefineableQPVDElementWithPressure< DIM >::unpin_elemental_solid_pressure_dofs(), and oomph::QPVDElementWithPressure< DIM >::unpin_elemental_solid_pressure_dofs().
The documentation for this class was generated from the following file:
solid_elements.h