oomph::DGEulerFaceReflectionElement< ELEMENT > Class Template Reference
FaceElement for Discontinuous Galerkin Problems with reflection boundary conditions.
#include <euler_elements.h>
Public Member Functions
DGEulerFaceReflectionElement (FiniteElement *const &element_pt, const int &face_index)
Constructor.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
unsigned required_nflux ()
Set the number of flux components.
void interpolated_u (const Vector< double > &s, Vector< double > &u)
We overload interpolated_u to reflect.
Private Attributes
unsigned Nflux
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::DGEulerFaceReflectionElement< ELEMENT >
FaceElement for Discontinuous Galerkin Problems with reflection boundary conditions.
Definition at line 696 of file euler_elements.h.
Constructor & Destructor Documentation
DGEulerFaceReflectionElement()
template<class ELEMENT >
oomph::DGEulerFaceReflectionElement< ELEMENT >::DGEulerFaceReflectionElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor.
Definition at line 703 of file euler_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FiniteElement::dim(), oomph::FaceElement::face_index(), and oomph::DGEulerFaceReflectionElement< ELEMENT >::Nflux.
Member Function Documentation
interpolated_u()
template<class ELEMENT >
void oomph::DGEulerFaceReflectionElement< ELEMENT >::interpolated_u (const Vector< double > & s, Vector< double > & u) [inline], [virtual]
We overload interpolated_u to reflect.
Reimplemented from oomph::DGFaceElement.
Definition at line 735 of file euler_elements.h.
required_nflux()
template<class ELEMENT >
unsigned oomph::DGEulerFaceReflectionElement< ELEMENT >::required_nflux () [inline], [virtual]
Set the number of flux components.
Reimplemented from oomph::DGFaceElement.
Definition at line 729 of file euler_elements.h.
References oomph::DGEulerFaceReflectionElement< ELEMENT >::Nflux.
zeta_nodal()
template<class ELEMENT >
double oomph::DGEulerFaceReflectionElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Reimplemented from oomph::FiniteElement.
Definition at line 721 of file euler_elements.h.
References i, and oomph::FaceElement::zeta_nodal().
Member Data Documentation
Nflux
template<class ELEMENT >
unsigned oomph::DGEulerFaceReflectionElement< ELEMENT >::Nflux [private]
Definition at line 699 of file euler_elements.h.
Referenced by oomph::DGEulerFaceReflectionElement< ELEMENT >::DGEulerFaceReflectionElement(), and oomph::DGEulerFaceReflectionElement< ELEMENT >::required_nflux().
The documentation for this class was generated from the following file:
euler_elements.h