oomph::BinaryTreeRoot Class Reference
#include <binary_tree.h>
Public Member Functions
BinaryTreeRoot (RefineableElement *const &object_pt)
BinaryTreeRoot (const BinaryTreeRoot &dummy)
Broken copy constructor.
void operator= (const BinaryTreeRoot &)
Broken assignment operator.
int direction_of_neighbour (BinaryTreeRoot *binary_tree_root_pt)
If binary_tree_root_pt is a neighbour, return the direction (L/R) in which it is found, otherwise return OMEGA.
Additional Inherited Members
Detailed Description
BinaryTreeRoot is a BinaryTree that forms the root of a (recursive) binary tree. The `root node` is special as it holds additional information about its neighbours.
Definition at line 236 of file binary_tree.h.
Constructor & Destructor Documentation
BinaryTreeRoot() [1/2]
oomph::BinaryTreeRoot::BinaryTreeRoot (RefineableElement *const & object_pt) [inline]
Constructor for the (empty) root binary tree: Pass pointer to associated object, a RefineableQElement<1>.
Definition at line 241 of file binary_tree.h.
References oomph::BinaryTree::Static_data_has_been_setup, and oomph::Global_string_for_annotation::string().
BinaryTreeRoot() [2/2]
oomph::BinaryTreeRoot::BinaryTreeRoot (const BinaryTreeRoot & dummy) [inline]
Broken copy constructor.
Definition at line 261 of file binary_tree.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
direction_of_neighbour()
int oomph::BinaryTreeRoot::direction_of_neighbour (BinaryTreeRoot * binary_tree_root_pt) [inline]
If binary_tree_root_pt is a neighbour, return the direction (L/R) in which it is found, otherwise return OMEGA.
Definition at line 274 of file binary_tree.h.
References oomph::BinaryTreeNames::L, oomph::TreeRoot::Neighbour_pt, oomph::Tree::OMEGA, and oomph::BinaryTreeNames::R.
operator=()
void oomph::BinaryTreeRoot::operator= (const BinaryTreeRoot &) [inline]
Broken assignment operator.
Definition at line 267 of file binary_tree.h.
References oomph::BrokenCopy::broken_assign().
The documentation for this class was generated from the following file:
binary_tree.h