oomph::HermiteShellElement Class Reference
An element that solves the Kirchhoff-Love shell theory equations using Hermite interpolation (displacements and slopes are interpolated separately. The local and global (Lagrangian) coordinates are not assumed to be aligned. N.B. It will be DOG SLOW.
#include <shell_elements.h>
Public Member Functions
HermiteShellElement ()
Constructor, there are no internal data points.
void output_with_time_dep_quantities (std::ostream &outfile, const unsigned &n_plot)
Output position veloc and accel.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
void output (FILE *file_pt)
Overload the output function.
void output (FILE *file_pt, const unsigned &n_plot)
Output function.
Additional Inherited Members
Detailed Description
An element that solves the Kirchhoff-Love shell theory equations using Hermite interpolation (displacements and slopes are interpolated separately. The local and global (Lagrangian) coordinates are not assumed to be aligned. N.B. It will be DOG SLOW.
Definition at line 345 of file shell_elements.h.
Constructor & Destructor Documentation
HermiteShellElement()
oomph::HermiteShellElement::HermiteShellElement () [inline]
Constructor, there are no internal data points.
Definition at line 350 of file shell_elements.h.
References oomph::FiniteElement::set_nodal_dimension().
Member Function Documentation
output() [1/4]
void oomph::HermiteShellElement::output (FILE * file_pt) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::KirchhoffLoveShellEquations.
Definition at line 371 of file shell_elements.h.
References oomph::SolidQHermiteElement< DIM >::output().
output() [2/4]
void oomph::HermiteShellElement::output (FILE * file_pt, const unsigned & n_plot) [virtual]
Output function.
The output function.
Reimplemented from oomph::KirchhoffLoveShellEquations.
Definition at line 1298 of file shell_elements.cc.
References oomph::FiniteElement::interpolated_x(), oomph::SolidFiniteElement::interpolated_xi(), and s.
output() [3/4]
void oomph::HermiteShellElement::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::KirchhoffLoveShellEquations.
Definition at line 362 of file shell_elements.h.
References oomph::SolidQHermiteElement< DIM >::output().
output() [4/4]
void oomph::HermiteShellElement::output (std::ostream & outfile, const unsigned & n_plot) [virtual]
Output function.
The output function.
Reimplemented from oomph::KirchhoffLoveShellEquations.
Definition at line 1267 of file shell_elements.cc.
References oomph::FiniteElement::interpolated_x(), oomph::SolidFiniteElement::interpolated_xi(), and s.
output_with_time_dep_quantities()
void oomph::HermiteShellElement::output_with_time_dep_quantities (std::ostream & outfile, const unsigned & n_plot)
Output position veloc and accel.
The output function: position, veloc and accel.
Definition at line 1233 of file shell_elements.cc.
References oomph::FiniteElement::interpolated_dxdt(), oomph::FiniteElement::interpolated_x(), and s.
The documentation for this class was generated from the following files:
shell_elements.h
shell_elements.cc