oomph::ImposeParallelOutflowElement< ELEMENT > Class Template Reference
ImposeParallelOutflowElement are elements that coincide with the faces of higher-dimensional `bulk` elements. They are used on boundaries where we would like to impose parallel outflow and impose the pressure.
#include <impose_parallel_outflow_element.h>
Public Member Functions
ImposeParallelOutflowElement (FiniteElement *const &element_pt, const int &face_index, const unsigned &id=0)
Constructor takes a `bulk` element, the index that identifies which face the ImposeParallelOutflowElement is supposed to be attached to, and the face element ID.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Fill in contribution from Jacobian.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,[z],u,v,[w],p in tecplot format.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default This final over-ride is required because both SolidFiniteElements and FaceElements overload zeta_nodal.
double *& pressure_pt ()
Access function for the pressure.
Protected Member Functions
void fill_in_generic_contribution_to_residuals_parall_lagr_multiplier (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Helper function to compute the residuals and, if flag==1, the Jacobian.
unsigned ndof_types () const
The number of degrees of freedom types that this element is divided into: The ImposeParallelOutflowElement is responsible for 1(2) of it's own degrees of freedom. In addition to this, it also classifies the 2(3) constrained velocity bulk degrees of freedom which this face element is attached to.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the LOCAL number of the `DOF types` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Private Attributes
double * Pressure_pt
pointer to imposed pressure -- if null then no pressure imposed.
unsigned Id
Lagrange Id.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::ImposeParallelOutflowElement< ELEMENT >
ImposeParallelOutflowElement are elements that coincide with the faces of higher-dimensional `bulk` elements. They are used on boundaries where we would like to impose parallel outflow and impose the pressure.
Definition at line 44 of file impose_parallel_outflow_element.h.
Constructor & Destructor Documentation
ImposeParallelOutflowElement()
template<class ELEMENT >
oomph::ImposeParallelOutflowElement< ELEMENT >::ImposeParallelOutflowElement (FiniteElement *const & element_pt, const int & face_index, const unsigned & id = 0) [inline]
Constructor takes a `bulk` element, the index that identifies which face the ImposeParallelOutflowElement is supposed to be attached to, and the face element ID.
Definition at line 60 of file impose_parallel_outflow_element.h.
References oomph::FaceElement::add_additional_values(), oomph::FiniteElement::build_face_element(), oomph::FiniteElement::dim(), oomph::FaceElement::face_index(), oomph::ImposeParallelOutflowElement< ELEMENT >::Id, oomph::FiniteElement::nnode(), and oomph::ImposeParallelOutflowElement< ELEMENT >::Pressure_pt.
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Fill in contribution from Jacobian.
Reimplemented from oomph::FiniteElement.
Definition at line 95 of file impose_parallel_outflow_element.h.
References oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), and residuals().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Fill in the residuals.
Reimplemented from oomph::GeneralisedElement.
Definition at line 87 of file impose_parallel_outflow_element.h.
References oomph::GeneralisedElement::Dummy_matrix, oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), and residuals().
fill_in_generic_contribution_to_residuals_parall_lagr_multiplier()
template<class ELEMENT >
void oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [inline], [protected]
Helper function to compute the residuals and, if flag==1, the Jacobian.
Definition at line 137 of file impose_parallel_outflow_element.h.
References oomph::FaceElement::bulk_element_pt(), oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), oomph::FiniteElement::dim(), i, oomph::ImposeParallelOutflowElement< ELEMENT >::Id, oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), oomph::FiniteElement::integral_pt(), interpolated_u(), oomph::FaceElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), oomph::ImposeParallelOutflowElement< ELEMENT >::Pressure_pt, residuals(), oomph::FiniteElement::shape_at_knot(), oomph::Node::value(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_contribution_to_residuals().
get_dof_numbers_for_unknowns()
template<class ELEMENT >
void oomph::ImposeParallelOutflowElement< ELEMENT >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> & dof_lookup_list) const [inline], [protected], [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the LOCAL number of the `DOF types` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
For the ImposeParallelOutflowElement, we need to classify both the constrained velocity from the bulk element and the dof types from this element. In 3D, let up, vp, wp be the constrained velocity dof types associated with the ImposeParallelOutflowElement. Let Lp1 and Lp2 be the two Lagrange multiplier dof types associated with the ImposeParallelOutflowElement. Then we have:
0 1 2 3 4 up vp wp L1 L2
Reimplemented from oomph::GeneralisedElement.
Definition at line 353 of file impose_parallel_outflow_element.h.
References oomph::FaceElement::Bulk_element_pt, oomph::FaceElement::Bulk_node_number, oomph::FiniteElement::dim(), oomph::GeneralisedElement::eqn_number(), oomph::ImposeParallelOutflowElement< ELEMENT >::Id, oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), and oomph::FiniteElement::node_pt().
ndof_types()
template<class ELEMENT >
unsigned oomph::ImposeParallelOutflowElement< ELEMENT >::ndof_types () const [inline], [protected], [virtual]
The number of degrees of freedom types that this element is divided into: The ImposeParallelOutflowElement is responsible for 1(2) of it's own degrees of freedom. In addition to this, it also classifies the 2(3) constrained velocity bulk degrees of freedom which this face element is attached to.
Reimplemented from oomph::GeneralisedElement.
Definition at line 327 of file impose_parallel_outflow_element.h.
References oomph::FiniteElement::dim().
output() [1/2]
template<class ELEMENT >
void oomph::ImposeParallelOutflowElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Definition at line 104 of file impose_parallel_outflow_element.h.
References oomph::FiniteElement::output().
output() [2/2]
template<class ELEMENT >
void oomph::ImposeParallelOutflowElement< ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format.
Reimplemented from oomph::FiniteElement.
Definition at line 110 of file impose_parallel_outflow_element.h.
References oomph::FiniteElement::output().
pressure_pt()
template<class ELEMENT >
double*& oomph::ImposeParallelOutflowElement< ELEMENT >::pressure_pt () [inline]
Access function for the pressure.
Definition at line 129 of file impose_parallel_outflow_element.h.
References oomph::ImposeParallelOutflowElement< ELEMENT >::Pressure_pt.
zeta_nodal()
template<class ELEMENT >
double oomph::ImposeParallelOutflowElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default This final over-ride is required because both SolidFiniteElements and FaceElements overload zeta_nodal.
Reimplemented from oomph::FaceElement.
Definition at line 120 of file impose_parallel_outflow_element.h.
References i, n, and oomph::FaceElement::zeta_nodal().
Member Data Documentation
Id
template<class ELEMENT >
unsigned oomph::ImposeParallelOutflowElement< ELEMENT >::Id [private]
Lagrange Id.
Definition at line 52 of file impose_parallel_outflow_element.h.
Referenced by oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::ImposeParallelOutflowElement< ELEMENT >::get_dof_numbers_for_unknowns(), and oomph::ImposeParallelOutflowElement< ELEMENT >::ImposeParallelOutflowElement().
Pressure_pt
template<class ELEMENT >
double* oomph::ImposeParallelOutflowElement< ELEMENT >::Pressure_pt [private]
pointer to imposed pressure -- if null then no pressure imposed.
Definition at line 49 of file impose_parallel_outflow_element.h.
Referenced by oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::ImposeParallelOutflowElement< ELEMENT >::ImposeParallelOutflowElement(), and oomph::ImposeParallelOutflowElement< ELEMENT >::pressure_pt().
The documentation for this class was generated from the following file:
impose_parallel_outflow_element.h