oomph::RefineableRectangleWithHoleAndAnnularRegionMesh< ELEMENT > Class Template Reference
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
#include <rectangle_with_moving_cylinder_mesh.template.h>
Public Member Functions
RefineableRectangleWithHoleAndAnnularRegionMesh (GeomObject *cylinder_pt, const double &annular_region_radius, const double &length, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor. Pass pointer to geometric object that represents the cylinder, the length and height of the domain. The GeomObject must be parametrised such that $\zeta \in [0,2\pi]$ sweeps around the circumference in anticlockwise direction. Timestepper defaults to Steady default timestepper.
virtual ~RefineableRectangleWithHoleAndAnnularRegionMesh ()
Destructor: Empty.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::RefineableRectangleWithHoleAndAnnularRegionMesh< ELEMENT >
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Refineable version of RectangleWithHoleAndAnnularRegionMesh. Applies one uniform refinement immediately to avoid problems with the automatic applications of boundary conditions in subsequent refinements
Definition at line 269 of file rectangle_with_moving_cylinder_mesh.template.h.
Constructor & Destructor Documentation
RefineableRectangleWithHoleAndAnnularRegionMesh()
template<class ELEMENT >
oomph::RefineableRectangleWithHoleAndAnnularRegionMesh< ELEMENT >::RefineableRectangleWithHoleAndAnnularRegionMesh (GeomObject * cylinder_pt, const double & annular_region_radius, const double & length, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor. Pass pointer to geometric object that represents the cylinder, the length and height of the domain. The GeomObject must be parametrised such that $\zeta \in [0,2\pi]$ sweeps around the circumference in anticlockwise direction. Timestepper defaults to Steady default timestepper.
Definition at line 280 of file rectangle_with_moving_cylinder_mesh.template.h.
References oomph::RectangleWithHoleAndAnnularRegionMesh< ELEMENT >::Domain_pt, e, oomph::Mesh::element_pt(), oomph::Domain::macro_element_pt(), oomph::Domain::nmacro_element(), oomph::Mesh::setup_boundary_element_info(), and oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest().
 RefineableRectangleWithHoleAndAnnularRegionMesh()
template<class ELEMENT >
virtual oomph::RefineableRectangleWithHoleAndAnnularRegionMesh< ELEMENT >::~RefineableRectangleWithHoleAndAnnularRegionMesh () [inline], [virtual]
Destructor: Empty.
Definition at line 309 of file rectangle_with_moving_cylinder_mesh.template.h.
The documentation for this class was generated from the following file:
rectangle_with_moving_cylinder_mesh.template.h