oomph::NewmarkBDF< NSTEPS > Class Template Reference
Newmark scheme for second time deriv with first derivatives calculated using BDF. . Stored data represents.
#include <timesteppers.h>
Public Member Functions
NewmarkBDF ()
Constructor: Pass pointer to global time. We set up a timestepping scheme with NSTEPS+2 doubles to represent the history and the highest deriv is 2.
NewmarkBDF (const NewmarkBDF &)=delete
Broken copy constructor.
void operator= (const NewmarkBDF &)=delete
Broken assignment operator.
void set_weights ()
Set weights.
void shift_time_values (Data *const &data_pt)
This function updates the Data's time history so that we can advance to the next timestep.
void shift_time_positions (Node *const &node_pt)
This function updates a nodal time history so that we can advance to the next timestep.
void enable_degrade_first_derivatives_to_bdf1 ()
Degrade scheme to first order BDF (for first derivs/veloc); usually for start-up.
void disable_degrade_first_derivatives_to_bdf1 ()
Disable degradation to first order BDF.
void set_weights ()
Set weights.
void set_weights ()
Set weights.
void set_weights ()
Set weights.
Public Member Functions inherited from oomph::Newmark< NSTEPS >
Newmark ()
Constructor: Pass pointer to global time. We set up a timestepping scheme with NSTEPS+2 doubles to represent the history and the highest deriv is 2.
Newmark (const Newmark &)=delete
Broken copy constructor.
void operator= (const Newmark &)=delete
Broken assignment operator.
unsigned order () const
The actual order (accuracy of the scheme)
void assign_initial_values_impulsive (Data *const &data_pt)
Initialise the time-history for the values, corresponding to an impulsive start.
void assign_initial_positions_impulsive (Node *const &node_pt)
Initialise the time-history for the values, corresponding to an impulsive start.
void assign_initial_data_values (Data *const &data_pt, Vector< InitialConditionFctPt > initial_value_fct, Vector< InitialConditionFctPt > initial_veloc_fct, Vector< InitialConditionFctPt > initial_accel_fct)
Initialise the time-history for the Data values, so that the Newmark representations for current veloc and acceleration are exact.
void assign_initial_data_values (Node *const &node_pt, Vector< NodeInitialConditionFctPt > initial_value_fct, Vector< NodeInitialConditionFctPt > initial_veloc_fct, Vector< NodeInitialConditionFctPt > initial_accel_fct)
Initialise the time-history for the nodal values, so that the Newmark representations for current veloc and acceleration are exact.
void assign_initial_data_values_stage1 (const unsigned t_deriv, Data *const &data_pt)
First step in a two-stage procedure to assign the history values for the Newmark scheme so that the veloc and accel that are computed by the scheme are correct at the current time.
void assign_initial_data_values_stage2 (Data *const &data_pt)
Second step in a two-stage procedure to assign the history values for the Newmark scheme so that the veloc and accel that are computed by the scheme are correct at the current time.
unsigned nprev_values () const
Number of previous values available.
unsigned ndt () const
Number of timestep increments that need to be stored by the scheme.
Public Member Functions inherited from oomph::TimeStepper
TimeStepper (const unsigned &tstorage, const unsigned &max_deriv)
Constructor. Pass the amount of storage required by timestepper (present value + history values) and the order of highest time-derivative.
TimeStepper ()
Broken empty constructor.
TimeStepper (const TimeStepper &)=delete
Broken copy constructor.
void operator= (const TimeStepper &)=delete
Broken assignment operator.
virtual ~TimeStepper ()
virtual destructor
unsigned highest_derivative () const
Highest order derivative that the scheme can compute.
double & time ()
Return current value of continous time.
double time () const
Return current value of continous time.
virtual unsigned nprev_values_for_value_at_evaluation_time () const
Number of previous values needed to calculate the value at the current time. i.e. how many previous values must we loop over to calculate the values at the evaluation time. For most methods this is 1, i.e. just use the value at t_{n+1}. See midpoint method for a counter-example.
void make_steady ()
Function to make the time stepper temporarily steady. This is trivially achieved by setting all the weights to zero.
bool is_steady () const
Flag to indicate if a timestepper has been made steady (possibly temporarily to switch off time-dependence)
bool predict_by_explicit_step () const
Flag: is adaptivity done by taking a separate step using an ExplicitTimeStepper object?
ExplicitTimeStepper * explicit_predictor_pt ()
Get the pointer to the explicit timestepper to use as a predictor in adaptivity if Predict_by_explicit_step is set.
void set_predictor_pt (ExplicitTimeStepper *_pred_pt)
Set the pointer to the explicit timestepper to use as a predictor in adaptivity if Predict_by_explicit_step is set.
void update_predicted_time (const double &new_time)
Set the time that the current predictions apply for, only needed for paranoid checks when doing Predict_by_explicit_step.
void check_predicted_values_up_to_date () const
Check that the predicted values are the ones we want.
unsigned predictor_storage_index () const
Return the time-index in each Data where predicted values are stored if the timestepper is adaptive.
void enable_warning_in_assign_initial_data_values ()
Enable the output of warnings due to possible fct pointer vector size mismatch in assign_initial_data_values (Default)
void disable_warning_in_assign_initial_data_values ()
Disable the output of warnings due to possible fct pointer vector size mismatch in assign_initial_data_values.
const DenseMatrix< double > * weights_pt () const
Get a (const) pointer to the weights.
virtual void undo_make_steady ()
Reset the is_steady status of a specific TimeStepper to its default and re-assign the weights.
std::string type () const
Return string that indicates the type of the timestepper (e.g. "BDF", "Newmark", etc.)
void time_derivative (const unsigned &i, Data *const &data_pt, Vector< double > &deriv)
Evaluate i-th derivative of all values in Data and return in Vector deriv[].
double time_derivative (const unsigned &i, Data *const &data_pt, const unsigned &j)
Evaluate i-th derivative of j-th value in Data.
void time_derivative (const unsigned &i, Node *const &node_pt, Vector< double > &deriv)
Evaluate i-th derivative of all values in Node and return in Vector deriv[] (this can't be simply combined with time_derivative(.., Data, ...) because of differences with haning nodes).
double time_derivative (const unsigned &i, Node *const &node_pt, const unsigned &j)
Evaluate i-th derivative of j-th value in Node. Note the use of the node's value() function so that hanging nodes are taken into account (this is why the functions for Data and Node cannot be combined through simple polymorphism: value is not virtual).
Time *const & time_pt () const
Access function for the pointer to time (const version)
Time *& time_pt ()
Access function for the pointer to time (can't have a paranoid test for null pointers because this is used as a set function).
virtual double weight (const unsigned &i, const unsigned &j) const
Access function for j-th weight for the i-th derivative.
unsigned ntstorage () const
Return the number of doubles required to represent history (one for steady)
bool adaptive_flag () const
Function to indicate whether the scheme is adaptive (false by default)
virtual void set_predictor_weights ()
Set the weights for the predictor previous timestep (currently empty -- overwrite for specific scheme)
virtual void calculate_predicted_values (Data *const &data_pt)
Do the predictor step for data stored in a Data object (currently empty -- overwrite for specific scheme)
virtual void calculate_predicted_positions (Node *const &node_pt)
Do the predictor step for the positions at a node (currently empty --- overwrite for a specific scheme)
virtual void set_error_weights ()
Set the weights for the error computation, (currently empty -- overwrite for specific scheme)
virtual double temporal_error_in_position (Node *const &node_pt, const unsigned &i)
Compute the error in the position i at a node zero here -- overwrite for specific scheme.
virtual double temporal_error_in_value (Data *const &data_pt, const unsigned &i)
Compute the error in the value i in a Data structure zero here -- overwrite for specific scheme.
virtual void actions_before_timestep (Problem *problem_pt)
Interface for any actions that need to be performed before a time step.
virtual void actions_after_timestep (Problem *problem_pt)
Interface for any actions that need to be performed after a time step.
Private Member Functions
void set_newmark_veloc_weights (const double &dt)
Set original Newmark weights for velocities (needed when shifting history values -- they're used when updating the previous accelerations and doing this with bdf can make the scheme unstable...
Private Attributes
bool Degrade_to_bdf1_for_first_derivs
Boolean flag to indicate degradation of scheme to first order BDF (for first derivs/veloc); usually for start-up.
Vector< double > Newmark_veloc_weight
Original Newmark weights for velocities (needed when shifting history values -- they're used when updating the previous accelerations and doing this with bdf can make the scheme unstable...
Additional Inherited Members
Public Types inherited from oomph::Newmark< NSTEPS >
typedef double(* InitialConditionFctPt) (const double &t)
Typedef for function that returns the (scalar) initial value at a given value of the continuous time t.
typedef double(* NodeInitialConditionFctPt) (const double &t, const Vector< double > &x)
Typedef for function that returns the (scalar) initial value at a given value of the continuous time t and the spatial coordinate -- appropriate for assignement of initial conditions for nodes.
Protected Attributes inherited from oomph::Newmark< NSTEPS >
double Beta1
First Newmark parameter (usually 0.5)
double Beta2
Second Newmark parameter (usually 0.5)
Protected Attributes inherited from oomph::TimeStepper
Time * Time_pt
Pointer to discrete time storage scheme.
DenseMatrix< double > Weight
Storage for the weights associated with the timestepper.
std::string Type
String that indicates the type of the timestepper (e.g. "BDF", "Newmark", etc.)
bool Adaptive_Flag
Boolean variable to indicate whether the timestepping scheme can be adaptive.
bool Is_steady
Bool to indicate if the timestepper is steady, i.e. its time-derivatives evaluate to zero. This status may be achieved temporarily by calling make_steady(). It can be reset to the appropriate default by the function undo_make_steady().
bool Shut_up_in_assign_initial_data_values
Boolean to indicate if the timestepper will output warnings when setting possibly an incorrect number of initial data values from function pointers.
bool Predict_by_explicit_step
Flag: is adaptivity done by taking a separate step using an ExplicitTimeStepper object?
ExplicitTimeStepper * Explicit_predictor_pt
Pointer to explicit time stepper to use as predictor if Predict_by_explicit_step is set. ??ds merge the two? predict by explicit if pointer is set?
double Predicted_time
Store the time that the predicted values currently stored are at, to compare for paranoid checks.
int Predictor_storage_index
The time-index in each Data object where predicted values are stored. -1 if not set.
Detailed Description
template<unsigned NSTEPS>
class oomph::NewmarkBDF< NSTEPS >
Newmark scheme for second time deriv with first derivatives calculated using BDF. . Stored data represents.
t=0: value at at present time, Time_pt->time()
t=1: value at previous time, Time_pt->time()-dt
...
t=NSTEPS: value at previous time, Time_pt->time()-NSTEPS*dt
t=NSTEPS+1: 1st time deriv (= "velocity") at previous time, Time_pt->time()-dt
t=NSTEPS+2: 2nd time deriv (= "acceleration") at previous time, Time_pt->time()-dt
NSTEPS=1 gives normal Newmark.
Definition at line 1073 of file timesteppers.h.
Constructor & Destructor Documentation
NewmarkBDF() [1/2]
template<unsigned NSTEPS>
oomph::NewmarkBDF< NSTEPS >::NewmarkBDF () [inline]
Constructor: Pass pointer to global time. We set up a timestepping scheme with NSTEPS+2 doubles to represent the history and the highest deriv is 2.
Definition at line 1079 of file timesteppers.h.
References oomph::NewmarkBDF< NSTEPS >::Degrade_to_bdf1_for_first_derivs, and oomph::NewmarkBDF< NSTEPS >::Newmark_veloc_weight.
NewmarkBDF() [2/2]
template<unsigned NSTEPS>
oomph::NewmarkBDF< NSTEPS >::NewmarkBDF (const NewmarkBDF< NSTEPS > &) [delete]
Broken copy constructor.
Member Function Documentation
disable_degrade_first_derivatives_to_bdf1()
template<unsigned NSTEPS>
void oomph::NewmarkBDF< NSTEPS >::disable_degrade_first_derivatives_to_bdf1 () [inline]
Disable degradation to first order BDF.
Definition at line 1112 of file timesteppers.h.
References oomph::NewmarkBDF< NSTEPS >::Degrade_to_bdf1_for_first_derivs.
enable_degrade_first_derivatives_to_bdf1()
template<unsigned NSTEPS>
void oomph::NewmarkBDF< NSTEPS >::enable_degrade_first_derivatives_to_bdf1 () [inline]
Degrade scheme to first order BDF (for first derivs/veloc); usually for start-up.
Definition at line 1105 of file timesteppers.h.
References oomph::NewmarkBDF< NSTEPS >::Degrade_to_bdf1_for_first_derivs.
operator=()
template<unsigned NSTEPS>
void oomph::NewmarkBDF< NSTEPS >::operator= (const NewmarkBDF< NSTEPS > &) [delete]
Broken assignment operator.
set_newmark_veloc_weights()
template<unsigned NSTEPS>
void oomph::NewmarkBDF< NSTEPS >::set_newmark_veloc_weights (const double & dt) [inline], [private]
Set original Newmark weights for velocities (needed when shifting history values -- they're used when updating the previous accelerations and doing this with bdf can make the scheme unstable...
Definition at line 1122 of file timesteppers.h.
References oomph::Newmark< NSTEPS >::Beta1, oomph::NewmarkBDF< NSTEPS >::Newmark_veloc_weight, t, and oomph::TimeStepper::Weight.
set_weights() [1/4]
void oomph::NewmarkBDF< 1 >::set_weights () [virtual]
Set weights.
Reimplemented from oomph::Newmark< NSTEPS >.
Definition at line 1185 of file timesteppers.cc.
set_weights() [2/4]
void oomph::NewmarkBDF< 2 >::set_weights () [virtual]
Set weights.
Reimplemented from oomph::Newmark< NSTEPS >.
Definition at line 1208 of file timesteppers.cc.
References i, and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
set_weights() [3/4]
void oomph::NewmarkBDF< 4 >::set_weights () [virtual]
Set weights.
Reimplemented from oomph::Newmark< NSTEPS >.
Definition at line 1247 of file timesteppers.cc.
References i, and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
set_weights() [4/4]
template<unsigned NSTEPS>
void oomph::NewmarkBDF< NSTEPS >::set_weights () [virtual]
Set weights.
Reimplemented from oomph::Newmark< NSTEPS >.
shift_time_positions()
template<unsigned NSTEPS>
void oomph::NewmarkBDF< NSTEPS >::shift_time_positions (Node *const & node_pt) [virtual]
This function updates a nodal time history so that we can advance to the next timestep.
Reimplemented from oomph::Newmark< NSTEPS >.
Definition at line 1128 of file timesteppers.cc.
References i, oomph::Node::ndim(), oomph::FiniteElement::node_pt(), oomph::Node::nposition_type(), oomph::Node::position_is_a_copy(), t, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::Node::x_gen().
shift_time_values()
template<unsigned NSTEPS>
void oomph::NewmarkBDF< NSTEPS >::shift_time_values (Data *const & data_pt) [virtual]
This function updates the Data's time history so that we can advance to the next timestep.
Reimplemented from oomph::Newmark< NSTEPS >.
Definition at line 1082 of file timesteppers.cc.
References i, t, and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
Member Data Documentation
Degrade_to_bdf1_for_first_derivs
template<unsigned NSTEPS>
bool oomph::NewmarkBDF< NSTEPS >::Degrade_to_bdf1_for_first_derivs [private]
Boolean flag to indicate degradation of scheme to first order BDF (for first derivs/veloc); usually for start-up.
Definition at line 1139 of file timesteppers.h.
Referenced by oomph::NewmarkBDF< NSTEPS >::disable_degrade_first_derivatives_to_bdf1(), oomph::NewmarkBDF< NSTEPS >::enable_degrade_first_derivatives_to_bdf1(), and oomph::NewmarkBDF< NSTEPS >::NewmarkBDF().
Newmark_veloc_weight
template<unsigned NSTEPS>
Vector<double> oomph::NewmarkBDF< NSTEPS >::Newmark_veloc_weight [private]
Original Newmark weights for velocities (needed when shifting history values -- they're used when updating the previous accelerations and doing this with bdf can make the scheme unstable...
Definition at line 1145 of file timesteppers.h.
Referenced by oomph::NewmarkBDF< NSTEPS >::NewmarkBDF(), and oomph::NewmarkBDF< NSTEPS >::set_newmark_veloc_weights().
The documentation for this class was generated from the following files:
timesteppers.h
timesteppers.cc