oomph::SimpleCubicScaffoldTetMesh Class Reference
Scaffold mesh for cubic tet mesh.
#include <simple_cubic_scaffold_tet_mesh.h>
Public Member Functions
SimpleCubicScaffoldTetMesh (const unsigned &n_x, const unsigned &n_y, const unsigned &n_z, const double &l_x, const double &l_y, const double &l_z, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass number of elements and dimensions of cube.
Additional Inherited Members
Detailed Description
Scaffold mesh for cubic tet mesh.
Definition at line 36 of file simple_cubic_scaffold_tet_mesh.h.
Constructor & Destructor Documentation
SimpleCubicScaffoldTetMesh()
oomph::SimpleCubicScaffoldTetMesh::SimpleCubicScaffoldTetMesh (const unsigned & n_x, const unsigned & n_y, const unsigned & n_z, const double & l_x, const double & l_y, const double & l_z, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass number of elements and dimensions of cube.
Scaffold mesh for cubic tet mesh.
Definition at line 35 of file simple_cubic_scaffold_tet_mesh.cc.
References oomph::Mesh::add_boundary_node(), oomph::Mesh::Element_pt, i, Node, oomph::Mesh::Node_pt, oomph::Mesh::node_pt(), oomph::Mesh::set_nboundary(), and oomph::Node::x().
The documentation for this class was generated from the following files:
simple_cubic_scaffold_tet_mesh.h
simple_cubic_scaffold_tet_mesh.cc