oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations Class Reference
A version of the GeneralisedAxisymAdvectionDiffusion equations that can be used with non-uniform mesh refinement. In essence, the class overloads the fill_in_generic_residual_contribution_cons_axisym_adv_diff() function so that contributions from hanging nodes (or alternatively in-compatible function values) are taken into account.
#include <refineable_gen_axisym_advection_diffusion_elements.h>
Public Member Functions
RefineableGeneralisedAxisymAdvectionDiffusionEquations ()
Empty Constructor.
RefineableGeneralisedAxisymAdvectionDiffusionEquations (const RefineableGeneralisedAxisymAdvectionDiffusionEquations &dummy)=delete
Broken copy constructor.
unsigned num_Z2_flux_terms ()
Broken assignment operator.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Standard flux.from GeneralisedAxisymAdvectionDiffusion equations.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
double geometric_jacobian (const Vector< double > &x)
Fill in the geometric Jacobian, which in this case is r.
void further_build ()
Further build: Copy source function pointer from father element.
Protected Member Functions
void fill_in_generic_residual_contribution_cons_axisym_adv_diff (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Add the element's contribution to the elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Additional Inherited Members
Detailed Description
A version of the GeneralisedAxisymAdvectionDiffusion equations that can be used with non-uniform mesh refinement. In essence, the class overloads the fill_in_generic_residual_contribution_cons_axisym_adv_diff() function so that contributions from hanging nodes (or alternatively in-compatible function values) are taken into account.
Definition at line 54 of file refineable_gen_axisym_advection_diffusion_elements.h.
Constructor & Destructor Documentation
RefineableGeneralisedAxisymAdvectionDiffusionEquations() [1/2]
oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::RefineableGeneralisedAxisymAdvectionDiffusionEquations () [inline]
Empty Constructor.
Definition at line 61 of file refineable_gen_axisym_advection_diffusion_elements.h.
RefineableGeneralisedAxisymAdvectionDiffusionEquations() [2/2]
oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::RefineableGeneralisedAxisymAdvectionDiffusionEquations (const RefineableGeneralisedAxisymAdvectionDiffusionEquations & dummy) [delete]
Broken copy constructor.
Member Function Documentation
fill_in_generic_residual_contribution_cons_axisym_adv_diff()
void oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [protected], [virtual]
Add the element's contribution to the elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Add the element's contribution to the elemental residual vector and/or elemental jacobian matrix. This function overloads the standard version so that the possible presence of hanging nodes is taken into account.
Reimplemented from oomph::GeneralisedAxisymAdvectionDiffusionEquations.
Definition at line 36 of file refineable_gen_axisym_advection_diffusion_elements.cc.
References oomph::GeneralisedAxisymAdvectionDiffusionEquations::ALE_is_disabled, oomph::OcTreeNames::D, oomph::FiniteElement::dnodal_position_dt(), oomph::GeneralisedAxisymAdvectionDiffusionEquations::dshape_and_dtest_eulerian_at_knot_cons_axisym_adv_diff(), oomph::GeneralisedAxisymAdvectionDiffusionEquations::du_dt_cons_axisym_adv_diff(), oomph::GeneralisedAxisymAdvectionDiffusionEquations::get_conserved_wind_cons_axisym_adv_diff(), oomph::GeneralisedAxisymAdvectionDiffusionEquations::get_diff_cons_axisym_adv_diff(), oomph::GeneralisedAxisymAdvectionDiffusionEquations::get_source_cons_axisym_adv_diff(), oomph::GeneralisedAxisymAdvectionDiffusionEquations::get_wind_cons_axisym_adv_diff(), oomph::Node::hanging_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Node::is_hanging(), oomph::Integral::knot(), oomph::RefineableElement::local_hang_eqn(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), oomph::GeneralisedAxisymAdvectionDiffusionEquations::pe(), oomph::GeneralisedAxisymAdvectionDiffusionEquations::pe_st(), s, oomph::Data::time_stepper_pt(), oomph::QuadTreeNames::W, oomph::Integral::weight(), oomph::TimeStepper::weight(), and oomph::GeneralisedAxisymAdvectionDiffusionEquations::wind.
further_build()
void oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::further_build () [inline], [virtual]
Further build: Copy source function pointer from father element.
Reimplemented from oomph::RefineableElement.
Definition at line 170 of file refineable_gen_axisym_advection_diffusion_elements.h.
References oomph::GeneralisedAxisymAdvectionDiffusionEquations::ALE_is_disabled, oomph::GeneralisedAxisymAdvectionDiffusionEquations::conserved_wind_fct_pt(), oomph::GeneralisedAxisymAdvectionDiffusionEquations::Conserved_wind_fct_pt, oomph::GeneralisedAxisymAdvectionDiffusionEquations::diff_fct_pt(), oomph::GeneralisedAxisymAdvectionDiffusionEquations::Diff_fct_pt, oomph::RefineableElement::father_element_pt(), oomph::GeneralisedAxisymAdvectionDiffusionEquations::pe_pt(), oomph::GeneralisedAxisymAdvectionDiffusionEquations::Pe_pt, oomph::GeneralisedAxisymAdvectionDiffusionEquations::pe_st_pt(), oomph::GeneralisedAxisymAdvectionDiffusionEquations::PeSt_pt, oomph::GeneralisedAxisymAdvectionDiffusionEquations::source_fct_pt(), oomph::GeneralisedAxisymAdvectionDiffusionEquations::Source_fct_pt, oomph::GeneralisedAxisymAdvectionDiffusionEquations::wind_fct_pt(), and oomph::GeneralisedAxisymAdvectionDiffusionEquations::Wind_fct_pt.
geometric_jacobian()
double oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::geometric_jacobian (const Vector< double > & x) [inline], [virtual]
Fill in the geometric Jacobian, which in this case is r.
Reimplemented from oomph::ElementWithZ2ErrorEstimator.
Definition at line 163 of file refineable_gen_axisym_advection_diffusion_elements.h.
get_interpolated_values() [1/2]
void oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 133 of file refineable_gen_axisym_advection_diffusion_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, and oomph::FiniteElement::shape().
get_interpolated_values() [2/2]
void oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 101 of file refineable_gen_axisym_advection_diffusion_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, and oomph::FiniteElement::shape().
get_Z2_flux()
void oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Standard flux.from GeneralisedAxisymAdvectionDiffusion equations.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 91 of file refineable_gen_axisym_advection_diffusion_elements.h.
References oomph::GeneralisedAxisymAdvectionDiffusionEquations::get_flux().
num_Z2_flux_terms()
unsigned oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::num_Z2_flux_terms () [inline], [virtual]
Broken assignment operator.
Number of 'flux' terms for Z2 error estimation
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 84 of file refineable_gen_axisym_advection_diffusion_elements.h.
The documentation for this class was generated from the following files:
refineable_gen_axisym_advection_diffusion_elements.h
refineable_gen_axisym_advection_diffusion_elements.cc