oomph::FluidInterfaceAdditionalValues< ELEMENT > Class Template Reference
This policy class is used to allow additional values to be added to the nodes from new surface equations, for examples of usage see the SurfactantTransportFluidInterfaceElements. The use of this class avoids issues with calling virtual functions in constructors and avoids having a global look-up able, although it functions in much the same way. Typically, this will only be filled in by `expert users` and is only required if you want to write generic surface-element classes. Specific classes can always be overloaded on a case-by-case basis.
#include <specific_node_update_interface_elements.h>
Public Member Functions
FluidInterfaceAdditionalValues ()
Empty constructor.
unsigned nadditional_values (const unsigned &n)
Specific interface that states how many additional values are required for the n-th node. Default is zero, but issue error_message.
void setup_equation_indices (ELEMENT *const &element_pt, const unsigned &id)
Specify any additional index setup information that is required; i.e. the look-up schemes for the additional values. Default is empty with error message.
Private Member Functions
void error_message ()
Detailed Description
template<class ELEMENT>
class oomph::FluidInterfaceAdditionalValues< ELEMENT >
This policy class is used to allow additional values to be added to the nodes from new surface equations, for examples of usage see the SurfactantTransportFluidInterfaceElements. The use of this class avoids issues with calling virtual functions in constructors and avoids having a global look-up able, although it functions in much the same way. Typically, this will only be filled in by `expert users` and is only required if you want to write generic surface-element classes. Specific classes can always be overloaded on a case-by-case basis.
Definition at line 71 of file specific_node_update_interface_elements.h.
Constructor & Destructor Documentation
FluidInterfaceAdditionalValues()
template<class ELEMENT >
oomph::FluidInterfaceAdditionalValues< ELEMENT >::FluidInterfaceAdditionalValues () [inline]
Empty constructor.
Definition at line 93 of file specific_node_update_interface_elements.h.
Member Function Documentation
error_message()
template<class ELEMENT >
void oomph::FluidInterfaceAdditionalValues< ELEMENT >::error_message () [inline], [private]
Definition at line 75 of file specific_node_update_interface_elements.h.
Referenced by oomph::FluidInterfaceAdditionalValues< ELEMENT >::nadditional_values(), and oomph::FluidInterfaceAdditionalValues< ELEMENT >::setup_equation_indices().
nadditional_values()
template<class ELEMENT >
unsigned oomph::FluidInterfaceAdditionalValues< ELEMENT >::nadditional_values (const unsigned & n) [inline]
Specific interface that states how many additional values are required for the n-th node. Default is zero, but issue error_message.
Definition at line 97 of file specific_node_update_interface_elements.h.
References oomph::FluidInterfaceAdditionalValues< ELEMENT >::error_message().
Referenced by oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >::ElasticUpdateFluidInterfaceElement(), and oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >::SpineUpdateFluidInterfaceElement().
setup_equation_indices()
template<class ELEMENT >
void oomph::FluidInterfaceAdditionalValues< ELEMENT >::setup_equation_indices (ELEMENT *const & element_pt, const unsigned & id) [inline]
Specify any additional index setup information that is required; i.e. the look-up schemes for the additional values. Default is empty with error message.
Definition at line 106 of file specific_node_update_interface_elements.h.
References oomph::FluidInterfaceAdditionalValues< ELEMENT >::error_message().
Referenced by oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >::ElasticUpdateFluidInterfaceElement(), and oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >::SpineUpdateFluidInterfaceElement().
The documentation for this class was generated from the following file:
specific_node_update_interface_elements.h