oomph::RefineableBrickMesh< ELEMENT > Class Template Reference
Intermediate mesh class that implements the mesh adaptation functions specified in the TreeBasedRefineableMesh class for meshes that contain the refineable variant of QElement s [The class ELEMENT provided as the template parameter must be of type RefineableQElement<3>].
#include <refineable_brick_mesh.h>
Public Member Functions
RefineableBrickMesh ()
Constructor: Setup static octree data.
RefineableBrickMesh (const RefineableBrickMesh &dummy)=delete
Broken copy constructor.
void operator= (const RefineableBrickMesh &)=delete
Broken assignment operator.
virtual ~RefineableBrickMesh ()
Destructor:
virtual void setup_tree_forest ()
Set up the tree forest associated with the Mesh. Forwards call to setup_octree_forest()
void setup_octree_forest ()
Do what it says...
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::RefineableBrickMesh< ELEMENT >
Intermediate mesh class that implements the mesh adaptation functions specified in the TreeBasedRefineableMesh class for meshes that contain the refineable variant of QElement s [The class ELEMENT provided as the template parameter must be of type RefineableQElement<3>].
Mesh adaptation/refinement is implemented by OcTree procedures and any concrete implementation of this class needs to provide a OcTreeForest representation of the initial (coarse) mesh.
Definition at line 59 of file refineable_brick_mesh.h.
Constructor & Destructor Documentation
RefineableBrickMesh() [1/2]
template<class ELEMENT >
oomph::RefineableBrickMesh< ELEMENT >::RefineableBrickMesh () [inline]
Constructor: Setup static octree data.
Definition at line 64 of file refineable_brick_mesh.h.
References oomph::OcTree::setup_static_data().
RefineableBrickMesh() [2/2]
template<class ELEMENT >
oomph::RefineableBrickMesh< ELEMENT >::RefineableBrickMesh (const RefineableBrickMesh< ELEMENT > & dummy) [delete]
Broken copy constructor.
 RefineableBrickMesh()
template<class ELEMENT >
virtual oomph::RefineableBrickMesh< ELEMENT >::~RefineableBrickMesh () [inline], [virtual]
Destructor:
Definition at line 78 of file refineable_brick_mesh.h.
Member Function Documentation
operator=()
template<class ELEMENT >
void oomph::RefineableBrickMesh< ELEMENT >::operator= (const RefineableBrickMesh< ELEMENT > &) [delete]
Broken assignment operator.
setup_octree_forest()
template<class ELEMENT >
void oomph::RefineableBrickMesh< ELEMENT >::setup_octree_forest () [inline]
Do what it says...
Definition at line 88 of file refineable_brick_mesh.h.
References oomph::Mesh::Comm_pt, e, oomph::Mesh::element_pt(), oomph::Tree::flush_sons(), oomph::TreeForest::flush_trees(), oomph::TreeBasedRefineableMeshBase::Forest_pt, oomph::TreeBasedRefineableMeshBase::get_refinement_levels(), i, oomph::Mesh::nelement(), oomph::Tree::nsons(), oomph::Tree::object_pt(), oomph::RefineableElement::refinement_level(), oomph::Tree::root_pt(), oomph::Tree::set_father_pt(), oomph::Tree::set_son_pt(), oomph::Tree::son_pt(), oomph::Tree::stick_all_tree_nodes_into_vector(), and oomph::TreeForest::stick_all_tree_nodes_into_vector().
Referenced by oomph::RefineableBrickFromTetMesh< ELEMENT >::RefineableBrickFromTetMesh(), oomph::RefineableExtrudedCubeMeshFromQuadMesh< ELEMENT >::RefineableExtrudedCubeMeshFromQuadMesh(), oomph::RefineableSimpleCubicMesh< ELEMENT >::RefineableSimpleCubicMesh(), oomph::RefineableSolidBrickFromTetMesh< ELEMENT >::RefineableSolidBrickFromTetMesh(), oomph::RefineableSolidThinLayerBrickOnTetMesh< ELEMENT >::RefineableSolidThinLayerBrickOnTetMesh(), oomph::RefineableThinLayerBrickOnTetMesh< ELEMENT >::RefineableThinLayerBrickOnTetMesh(), and oomph::RefineableBrickMesh< ELEMENT >::setup_tree_forest().
setup_tree_forest()
template<class ELEMENT >
virtual void oomph::RefineableBrickMesh< ELEMENT >::setup_tree_forest () [inline], [virtual]
Set up the tree forest associated with the Mesh. Forwards call to setup_octree_forest()
Implements oomph::TreeBasedRefineableMeshBase.
Definition at line 82 of file refineable_brick_mesh.h.
References oomph::RefineableBrickMesh< ELEMENT >::setup_octree_forest().
The documentation for this class was generated from the following file:
refineable_brick_mesh.h