oomph::LinearElasticityTractionElement< ELEMENT > Class Template Reference
A class for elements that allow the imposition of an applied traction in the equations of linear elasticity. The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
#include <linear_elasticity_traction_elements.h>
Public Member Functions
LinearElasticityTractionElement (FiniteElement *const &element_pt, const int &face_index)
Constructor, which takes a `bulk` element and the value of the index and its limit.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Return the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Fill in contribution from Jacobian.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
void output (std::ostream &outfile)
Output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
void output (FILE *file_pt)
C_style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function.
void traction (const double &time, const Vector< double > &s, Vector< double > &traction)
Compute traction vector at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
Public Attributes
void(*&)(const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction) traction_fct_pt ()
Reference to the traction function pointer.
Protected Member Functions
virtual void get_traction (const double &time, const unsigned &intpt, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction)
Get the traction vector: Pass number of integration point (dummy), Eulerlian coordinate and normal vector and return the load vector (not all of the input arguments will be required for all specific load functions but the list should cover all cases). This function is virtual so it can be overloaded for FSI.
void fill_in_contribution_to_residuals_linear_elasticity_traction (Vector< double > &residuals)
Helper function that actually calculates the residuals.
Protected Attributes
Vector< unsigned > U_index_linear_elasticity_traction
Index at which the i-th displacement component is stored.
void(* Traction_fct_pt)(const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
Pointer to an imposed traction function. Arguments: Eulerian coordinate; outer unit normal; applied traction. (Not all of the input arguments will be required for all specific load functions but the list should cover all cases)
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::LinearElasticityTractionElement< ELEMENT >
A class for elements that allow the imposition of an applied traction in the equations of linear elasticity. The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
Definition at line 75 of file linear_elasticity_traction_elements.h.
Constructor & Destructor Documentation
LinearElasticityTractionElement()
template<class ELEMENT >
oomph::LinearElasticityTractionElement< ELEMENT >::LinearElasticityTractionElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit.
Definition at line 119 of file linear_elasticity_traction_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FaceElement::face_index(), oomph::FiniteElement::has_hanging_nodes(), i, oomph::FiniteElement::nodal_dimension(), oomph::LinearElasticityTractionElement< ELEMENT >::Traction_fct_pt, and oomph::LinearElasticityTractionElementHelper::Zero_traction_fct().
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::LinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Fill in contribution from Jacobian.
Reimplemented from oomph::FiniteElement.
Definition at line 187 of file linear_elasticity_traction_elements.h.
References oomph::LinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals_linear_elasticity_traction().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::LinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Return the residuals.
Reimplemented from oomph::GeneralisedElement.
Definition at line 180 of file linear_elasticity_traction_elements.h.
References oomph::LinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals_linear_elasticity_traction().
fill_in_contribution_to_residuals_linear_elasticity_traction()
template<class ELEMENT >
void oomph::LinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals_linear_elasticity_traction (Vector< double > & residuals) [protected]
Helper function that actually calculates the residuals.
Return the residuals for the LinearElasticityTractionElement equations.
Definition at line 274 of file linear_elasticity_traction_elements.h.
References i, and oomph::QuadTreeNames::W.
Referenced by oomph::LinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::LinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals().
get_traction()
template<class ELEMENT >
virtual void oomph::LinearElasticityTractionElement< ELEMENT >::get_traction (const double & time, const unsigned & intpt, const Vector< double > & x, const Vector< double > & n, Vector< double > & traction) [inline], [protected], [virtual]
Get the traction vector: Pass number of integration point (dummy), Eulerlian coordinate and normal vector and return the load vector (not all of the input arguments will be required for all specific load functions but the list should cover all cases). This function is virtual so it can be overloaded for FSI.
Definition at line 98 of file linear_elasticity_traction_elements.h.
References oomph::LinearElasticityTractionElement< ELEMENT >::traction(), and oomph::LinearElasticityTractionElement< ELEMENT >::Traction_fct_pt.
output() [1/4]
template<class ELEMENT >
void oomph::LinearElasticityTractionElement< ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C_style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 219 of file linear_elasticity_traction_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<class ELEMENT >
void oomph::LinearElasticityTractionElement< ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 225 of file linear_elasticity_traction_elements.h.
References oomph::FiniteElement::output().
output() [3/4]
template<class ELEMENT >
void oomph::LinearElasticityTractionElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Definition at line 207 of file linear_elasticity_traction_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<class ELEMENT >
void oomph::LinearElasticityTractionElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Definition at line 213 of file linear_elasticity_traction_elements.h.
References oomph::FiniteElement::output().
traction()
template<class ELEMENT >
void oomph::LinearElasticityTractionElement< ELEMENT >::traction (const double & time, const Vector< double > & s, Vector< double > & traction)
Compute traction vector at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Compute traction vector at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
Definition at line 249 of file linear_elasticity_traction_elements.h.
References s.
Referenced by oomph::LinearElasticityTractionElement< ELEMENT >::get_traction().
zeta_nodal()
template<class ELEMENT >
double oomph::LinearElasticityTractionElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Reimplemented from oomph::FaceElement.
Definition at line 199 of file linear_elasticity_traction_elements.h.
References i, and oomph::FaceElement::zeta_nodal().
Member Data Documentation
traction_fct_pt
template<class ELEMENT >
void(*&)(const double& time, const Vector<double>& x, const Vector<double>& n, Vector<double>& traction) oomph::LinearElasticityTractionElement< ELEMENT >::traction_fct_pt() [inline]
Reference to the traction function pointer.
Definition at line 170 of file linear_elasticity_traction_elements.h.
Traction_fct_pt
template<class ELEMENT >
void(* oomph::LinearElasticityTractionElement< ELEMENT >::Traction_fct_pt) (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result) [protected]
Pointer to an imposed traction function. Arguments: Eulerian coordinate; outer unit normal; applied traction. (Not all of the input arguments will be required for all specific load functions but the list should cover all cases)
Definition at line 87 of file linear_elasticity_traction_elements.h.
Referenced by oomph::LinearElasticityTractionElement< ELEMENT >::get_traction(), and oomph::LinearElasticityTractionElement< ELEMENT >::LinearElasticityTractionElement().
U_index_linear_elasticity_traction
template<class ELEMENT >
Vector<unsigned> oomph::LinearElasticityTractionElement< ELEMENT >::U_index_linear_elasticity_traction [protected]
Index at which the i-th displacement component is stored.
Definition at line 80 of file linear_elasticity_traction_elements.h.
The documentation for this class was generated from the following file:
linear_elasticity_traction_elements.h