oomph::RefineableFSISolidTractionElement< ELEMENT, DIM > Class Template Reference
#include <solid_traction_elements.h>
Public Member Functions
RefineableFSISolidTractionElement (FiniteElement *const &element_pt, const int &face_index)
Constructor: Create element as FSIWallElement (and thus, by inheritance, a GeomObject) with DIM-1 Lagrangian and DIM Eulerian coordinates. By default, we assume that the normal vector computed by the underlying FaceElement points into the fluid. If this is not the case, overwrite this with the access function FSISolidTractionElement::set_normal_pointing_out_of_fluid() Constructor for GeomObject is called explicitly because of virtual inheritance!
~RefineableFSISolidTractionElement ()
Destructor: empty.
virtual void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Final overload. Get contributions from refineable solid traction element and derivatives from external data.
Additional Inherited Members
Detailed Description
template<class ELEMENT, unsigned DIM>
class oomph::RefineableFSISolidTractionElement< ELEMENT, DIM >
RefineableSolidTractionElement `upgraded` to a FSIWallElement (and thus, by inheritance, a GeomObject), so it can be used in FSI. The element is templated by the bulk solid element and the spatial (Eulerian) dimension of the bulk element.
Definition at line 1042 of file solid_traction_elements.h.
Constructor & Destructor Documentation
RefineableFSISolidTractionElement()
template<class ELEMENT , unsigned DIM>
oomph::RefineableFSISolidTractionElement< ELEMENT, DIM >::RefineableFSISolidTractionElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor: Create element as FSIWallElement (and thus, by inheritance, a GeomObject) with DIM-1 Lagrangian and DIM Eulerian coordinates. By default, we assume that the normal vector computed by the underlying FaceElement points into the fluid. If this is not the case, overwrite this with the access function FSISolidTractionElement::set_normal_pointing_out_of_fluid() Constructor for GeomObject is called explicitly because of virtual inheritance!
Definition at line 1057 of file solid_traction_elements.h.
 RefineableFSISolidTractionElement()
template<class ELEMENT , unsigned DIM>
oomph::RefineableFSISolidTractionElement< ELEMENT, DIM >::~RefineableFSISolidTractionElement () [inline]
Destructor: empty.
Definition at line 1066 of file solid_traction_elements.h.
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT , unsigned DIM>
virtual void oomph::RefineableFSISolidTractionElement< ELEMENT, DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Final overload. Get contributions from refineable solid traction element and derivatives from external data.
Reimplemented from oomph::FSIWallElement.
Definition at line 1071 of file solid_traction_elements.h.
References oomph::RefineableSolidTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::ElementWithExternalElement::fill_in_jacobian_from_external_interaction_by_fd(), and residuals().
The documentation for this class was generated from the following file:
solid_traction_elements.h