oomph::PeriodicOrbitTimeDiscretisation Class Reference
Timestepper used to calculate periodic orbits directly. It's not really a "timestepper" per se, but represents the time storage and means of calculating time-derivatives given the underlying discretisation.
#include <periodic_orbit_handler.h>
Public Types
typedef double(* InitialConditionFctPt) (const double &t)
Typedef for function that returns the (scalar) initial value at a given value of the continuous time t.
Public Member Functions
PeriodicOrbitTimeDiscretisation (const unsigned &n_tstorage)
Constructor for the case when we allow adaptive timestepping.
PeriodicOrbitTimeDiscretisation (const PeriodicOrbitTimeDiscretisation &)=delete
Broken copy constructor.
void operator= (const PeriodicOrbitTimeDiscretisation &)=delete
Broken assignment operator.
unsigned order () const
Return the actual order of the scheme.
void assign_initial_values_impulsive (Data *const &data_pt)
Broken initialisation the time-history for the Data values corresponding to an impulsive start.
void assign_initial_positions_impulsive (Node *const &node_pt)
Broken initialisation of the positions for the node corresponding to an impulsive start.
void assign_initial_data_values (Data *const &data_pt, Vector< InitialConditionFctPt > initial_value_fct)
Initialise the time-history for the Data values, corresponding to given time history, specified by Vector of function pointers.
void shift_time_values (Data *const &data_pt)
Broken shifting of time values.
void shift_time_positions (Node *const &node_pt)
Broken shifting of time positions.
void set_weights ()
Set the weights.
unsigned nprev_values () const
Number of previous values available.
unsigned ndt () const
Number of timestep increments that need to be stored by the scheme.
Public Member Functions inherited from oomph::TimeStepper
TimeStepper (const unsigned &tstorage, const unsigned &max_deriv)
Constructor. Pass the amount of storage required by timestepper (present value + history values) and the order of highest time-derivative.
TimeStepper ()
Broken empty constructor.
TimeStepper (const TimeStepper &)=delete
Broken copy constructor.
void operator= (const TimeStepper &)=delete
Broken assignment operator.
virtual ~TimeStepper ()
virtual destructor
unsigned highest_derivative () const
Highest order derivative that the scheme can compute.
double & time ()
Return current value of continous time.
double time () const
Return current value of continous time.
virtual unsigned nprev_values_for_value_at_evaluation_time () const
Number of previous values needed to calculate the value at the current time. i.e. how many previous values must we loop over to calculate the values at the evaluation time. For most methods this is 1, i.e. just use the value at t_{n+1}. See midpoint method for a counter-example.
void make_steady ()
Function to make the time stepper temporarily steady. This is trivially achieved by setting all the weights to zero.
bool is_steady () const
Flag to indicate if a timestepper has been made steady (possibly temporarily to switch off time-dependence)
bool predict_by_explicit_step () const
Flag: is adaptivity done by taking a separate step using an ExplicitTimeStepper object?
ExplicitTimeStepper * explicit_predictor_pt ()
Get the pointer to the explicit timestepper to use as a predictor in adaptivity if Predict_by_explicit_step is set.
void set_predictor_pt (ExplicitTimeStepper *_pred_pt)
Set the pointer to the explicit timestepper to use as a predictor in adaptivity if Predict_by_explicit_step is set.
void update_predicted_time (const double &new_time)
Set the time that the current predictions apply for, only needed for paranoid checks when doing Predict_by_explicit_step.
void check_predicted_values_up_to_date () const
Check that the predicted values are the ones we want.
unsigned predictor_storage_index () const
Return the time-index in each Data where predicted values are stored if the timestepper is adaptive.
void enable_warning_in_assign_initial_data_values ()
Enable the output of warnings due to possible fct pointer vector size mismatch in assign_initial_data_values (Default)
void disable_warning_in_assign_initial_data_values ()
Disable the output of warnings due to possible fct pointer vector size mismatch in assign_initial_data_values.
const DenseMatrix< double > * weights_pt () const
Get a (const) pointer to the weights.
virtual void undo_make_steady ()
Reset the is_steady status of a specific TimeStepper to its default and re-assign the weights.
std::string type () const
Return string that indicates the type of the timestepper (e.g. "BDF", "Newmark", etc.)
void time_derivative (const unsigned &i, Data *const &data_pt, Vector< double > &deriv)
Evaluate i-th derivative of all values in Data and return in Vector deriv[].
double time_derivative (const unsigned &i, Data *const &data_pt, const unsigned &j)
Evaluate i-th derivative of j-th value in Data.
void time_derivative (const unsigned &i, Node *const &node_pt, Vector< double > &deriv)
Evaluate i-th derivative of all values in Node and return in Vector deriv[] (this can't be simply combined with time_derivative(.., Data, ...) because of differences with haning nodes).
double time_derivative (const unsigned &i, Node *const &node_pt, const unsigned &j)
Evaluate i-th derivative of j-th value in Node. Note the use of the node's value() function so that hanging nodes are taken into account (this is why the functions for Data and Node cannot be combined through simple polymorphism: value is not virtual).
Time *const & time_pt () const
Access function for the pointer to time (const version)
Time *& time_pt ()
Access function for the pointer to time (can't have a paranoid test for null pointers because this is used as a set function).
virtual double weight (const unsigned &i, const unsigned &j) const
Access function for j-th weight for the i-th derivative.
unsigned ntstorage () const
Return the number of doubles required to represent history (one for steady)
bool adaptive_flag () const
Function to indicate whether the scheme is adaptive (false by default)
virtual void set_predictor_weights ()
Set the weights for the predictor previous timestep (currently empty -- overwrite for specific scheme)
virtual void calculate_predicted_values (Data *const &data_pt)
Do the predictor step for data stored in a Data object (currently empty -- overwrite for specific scheme)
virtual void calculate_predicted_positions (Node *const &node_pt)
Do the predictor step for the positions at a node (currently empty --- overwrite for a specific scheme)
virtual void set_error_weights ()
Set the weights for the error computation, (currently empty -- overwrite for specific scheme)
virtual double temporal_error_in_position (Node *const &node_pt, const unsigned &i)
Compute the error in the position i at a node zero here -- overwrite for specific scheme.
virtual double temporal_error_in_value (Data *const &data_pt, const unsigned &i)
Compute the error in the value i in a Data structure zero here -- overwrite for specific scheme.
virtual void actions_before_timestep (Problem *problem_pt)
Interface for any actions that need to be performed before a time step.
virtual void actions_after_timestep (Problem *problem_pt)
Interface for any actions that need to be performed after a time step.
Friends
class PeriodicOrbitEquations
Additional Inherited Members
Protected Attributes inherited from oomph::TimeStepper
Time * Time_pt
Pointer to discrete time storage scheme.
DenseMatrix< double > Weight
Storage for the weights associated with the timestepper.
std::string Type
String that indicates the type of the timestepper (e.g. "BDF", "Newmark", etc.)
bool Adaptive_Flag
Boolean variable to indicate whether the timestepping scheme can be adaptive.
bool Is_steady
Bool to indicate if the timestepper is steady, i.e. its time-derivatives evaluate to zero. This status may be achieved temporarily by calling make_steady(). It can be reset to the appropriate default by the function undo_make_steady().
bool Shut_up_in_assign_initial_data_values
Boolean to indicate if the timestepper will output warnings when setting possibly an incorrect number of initial data values from function pointers.
bool Predict_by_explicit_step
Flag: is adaptivity done by taking a separate step using an ExplicitTimeStepper object?
ExplicitTimeStepper * Explicit_predictor_pt
Pointer to explicit time stepper to use as predictor if Predict_by_explicit_step is set. ??ds merge the two? predict by explicit if pointer is set?
double Predicted_time
Store the time that the predicted values currently stored are at, to compare for paranoid checks.
int Predictor_storage_index
The time-index in each Data object where predicted values are stored. -1 if not set.
Detailed Description
Timestepper used to calculate periodic orbits directly. It's not really a "timestepper" per se, but represents the time storage and means of calculating time-derivatives given the underlying discretisation.
Definition at line 55 of file periodic_orbit_handler.h.
Member Typedef Documentation
InitialConditionFctPt
typedef double(* oomph::PeriodicOrbitTimeDiscretisation::InitialConditionFctPt) (const double &t)
Typedef for function that returns the (scalar) initial value at a given value of the continuous time t.
Definition at line 104 of file periodic_orbit_handler.h.
Constructor & Destructor Documentation
PeriodicOrbitTimeDiscretisation() [1/2]
oomph::PeriodicOrbitTimeDiscretisation::PeriodicOrbitTimeDiscretisation (const unsigned & n_tstorage) [inline]
Constructor for the case when we allow adaptive timestepping.
Definition at line 61 of file periodic_orbit_handler.h.
PeriodicOrbitTimeDiscretisation() [2/2]
oomph::PeriodicOrbitTimeDiscretisation::PeriodicOrbitTimeDiscretisation (const PeriodicOrbitTimeDiscretisation &) [delete]
Broken copy constructor.
Member Function Documentation
assign_initial_data_values()
void oomph::PeriodicOrbitTimeDiscretisation::assign_initial_data_values (Data *const & data_pt, Vector< InitialConditionFctPt > initial_value_fct) [inline]
Initialise the time-history for the Data values, corresponding to given time history, specified by Vector of function pointers.
Definition at line 109 of file periodic_orbit_handler.h.
References oomph::TimeStepper::ntstorage(), t, oomph::Time::time(), oomph::TimeStepper::time(), and oomph::TimeStepper::Time_pt.
assign_initial_positions_impulsive()
void oomph::PeriodicOrbitTimeDiscretisation::assign_initial_positions_impulsive (Node *const & node_pt) [inline], [virtual]
Broken initialisation of the positions for the node corresponding to an impulsive start.
Implements oomph::TimeStepper.
Definition at line 93 of file periodic_orbit_handler.h.
assign_initial_values_impulsive()
void oomph::PeriodicOrbitTimeDiscretisation::assign_initial_values_impulsive (Data *const & data_pt) [inline], [virtual]
Broken initialisation the time-history for the Data values corresponding to an impulsive start.
Implements oomph::TimeStepper.
Definition at line 83 of file periodic_orbit_handler.h.
ndt()
unsigned oomph::PeriodicOrbitTimeDiscretisation::ndt () const [inline], [virtual]
Number of timestep increments that need to be stored by the scheme.
Implements oomph::TimeStepper.
Definition at line 160 of file periodic_orbit_handler.h.
References oomph::TimeStepper::ntstorage().
nprev_values()
unsigned oomph::PeriodicOrbitTimeDiscretisation::nprev_values () const [inline], [virtual]
Number of previous values available.
Implements oomph::TimeStepper.
Definition at line 154 of file periodic_orbit_handler.h.
References oomph::TimeStepper::ntstorage().
operator=()
void oomph::PeriodicOrbitTimeDiscretisation::operator= (const PeriodicOrbitTimeDiscretisation &) [delete]
Broken assignment operator.
order()
unsigned oomph::PeriodicOrbitTimeDiscretisation::order () const [inline], [virtual]
Return the actual order of the scheme.
Reimplemented from oomph::TimeStepper.
Definition at line 76 of file periodic_orbit_handler.h.
set_weights()
void oomph::PeriodicOrbitTimeDiscretisation::set_weights () [inline], [virtual]
Set the weights.
Implements oomph::TimeStepper.
Definition at line 151 of file periodic_orbit_handler.h.
shift_time_positions()
void oomph::PeriodicOrbitTimeDiscretisation::shift_time_positions (Node *const & node_pt) [inline], [virtual]
Broken shifting of time positions.
Implements oomph::TimeStepper.
Definition at line 142 of file periodic_orbit_handler.h.
shift_time_values()
void oomph::PeriodicOrbitTimeDiscretisation::shift_time_values (Data *const & data_pt) [inline], [virtual]
Broken shifting of time values.
Implements oomph::TimeStepper.
Definition at line 133 of file periodic_orbit_handler.h.
Friends And Related Symbol Documentation
PeriodicOrbitEquations
friend class PeriodicOrbitEquations [friend]
Definition at line 57 of file periodic_orbit_handler.h.
The documentation for this class was generated from the following file:
periodic_orbit_handler.h