oomph::TElement< 2, NNODE_1D > Class Template Reference
General TElement class specialised to two spatial dimensions Ordering of nodes as in Zienkiwizc sketches: vertex nodes 0 - 1 - 2 anticlockwise. Midside nodes filled in progressing along the consecutive edges. Central node(s) come(s) last.
#include <Telements.h>
Public Member Functions
TElement ()
Constructor.
TElement (const bool &allow_high_order)
Alternative constructor.
TElement (const TElement &)=delete
Broken copy constructor.
~TElement ()
Broken assignment operator.
unsigned nnode_1d () const
Number of nodes along each element edge.
unsigned nvertex_node () const
Number of vertex nodes in the element: One more than spatial dimension.
unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
Public access function for Node_on_face.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void shape (const Vector< double > &s, Shape &psi) const
Calculate the geometric shape functions at local coordinate s.
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Compute the geometric shape functions and derivatives w.r.t. local coordinates at local coordinate s.
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
Compute the geometric shape functions, derivatives and second derivatives w.r.t local coordinates at local coordinate s d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $.
double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Overload the template-free interface for the calculation of inverse jacobian matrix. This is a two dimensional element, so use the 2D version.
double s_min () const
Min. value of local coordinate.
double s_max () const
Max. value of local coordinate.
void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
Return local coordinates of node j.
unsigned nplot_points_paraview (const unsigned &nplot) const
Return the number of actual plot points for paraview plot with parameter nplot.
unsigned nsub_elements_paraview (const unsigned &nplot) const
Return the number of local sub-elements for paraview plot with parameter nplot.
void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
Fill in the offset information for paraview plot. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
Return the paraview element type. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
Return the offsets for the paraview sub-elements. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
void output (std::ostream &output)
Output.
void output (std::ostream &outfile, const unsigned &nplot)
Output at specified number of plot points.
void output (FILE *file_pt)
C-style output.
void output (FILE *file_pt, const unsigned &n_plot)
C_style output at n_plot points.
void get_s_plot (const unsigned &iplot, const unsigned &nplot, Vector< double > &s, const bool &use_equally_spaced_interior_sample_points=false) const
Get vector of local coordinates of plot point i (when plotting nplot points in each `coordinate direction`).
std::string tecplot_zone_string (const unsigned &nplot) const
Return string for tecplot zone header (when plotting nplot points in each "coordinate direction)
void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
Add tecplot zone `footer` to output stream (when plotting nplot points in each "coordinate direction). Empty by default -- can be used, e.g., to add FE connectivity lists to elements that need it.
void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
Add tecplot zone `footer` to C-style output. (when plotting nplot points in each "coordinate direction). Empty by default -- can be used, e.g., to add FE connectivity lists to elements that need it.
unsigned nplot_points (const unsigned &nplot) const
Return total number of plot points (when plotting nplot points in each "coordinate direction)
void build_face_element (const int &face_index, FaceElement *face_element_pt)
Build the lower-dimensional FaceElement (an element of type TElement<1,NNODE_1D>). The face index takes three possible values: 0 (Left) s[0] = 0.0 1 (Bottom) s[1] = 0.0 2 (Sloping face) s[0] = 1.0 - s[1].
Static Private Attributes
static const unsigned Node_on_face [3][NNODE_1D]
Nodal translation scheme for use when generating face elements.
static TGauss< 2, NNODE_1D > Default_integration_scheme
Default integration rule: Gaussian integration of same 'order' as the element.
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::TElement< 2, NNODE_1D >
General TElement class specialised to two spatial dimensions Ordering of nodes as in Zienkiwizc sketches: vertex nodes 0 - 1 - 2 anticlockwise. Midside nodes filled in progressing along the consecutive edges. Central node(s) come(s) last.
Definition at line 1503 of file Telements.h.
Constructor & Destructor Documentation
TElement() [1/3]
template<unsigned NNODE_1D>
oomph::TElement< 2, NNODE_1D >::TElement () [inline]
Constructor.
Definition at line 1520 of file Telements.h.
References oomph::Global_string_for_annotation::string().
TElement() [2/3]
template<unsigned NNODE_1D>
oomph::TElement< 2, NNODE_1D >::TElement (const bool & allow_high_order) [inline]
Alternative constructor.
Definition at line 1551 of file Telements.h.
TElement() [3/3]
template<unsigned NNODE_1D>
oomph::TElement< 2, NNODE_1D >::TElement (const TElement< 2, NNODE_1D > &) [delete]
Broken copy constructor.
 TElement()
template<unsigned NNODE_1D>
oomph::TElement< 2, NNODE_1D >::~TElement () [inline]
Broken assignment operator.
Destructor
Definition at line 1582 of file Telements.h.
Member Function Documentation
build_face_element()
template<unsigned NNODE_1D>
void oomph::TElement< 2, NNODE_1D >::build_face_element (const int & face_index, FaceElement * face_element_pt) [virtual]
Build the lower-dimensional FaceElement (an element of type TElement<1,NNODE_1D>). The face index takes three possible values: 0 (Left) s[0] = 0.0 1 (Bottom) s[1] = 0.0 2 (Sloping face) s[0] = 1.0 - s[1].
Function to setup geometrical information for lower-dimensional FaceElements (which are of type TElement<2,NNODE_1D>).
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidTElement< 2, NNODE_1D >.
Definition at line 370 of file Telements.cc.
References oomph::FaceElement::bulk_coordinate_derivatives_fct_pt(), oomph::FaceElement::bulk_element_pt(), oomph::FaceElement::bulk_node_number(), oomph::FaceElement::bulk_node_number_resize(), oomph::TElement2BulkCoordinateDerivatives::face0(), oomph::TElement2FaceToBulkCoordinates::face0(), oomph::TElement2BulkCoordinateDerivatives::face1(), oomph::TElement2FaceToBulkCoordinates::face1(), oomph::TElement2BulkCoordinateDerivatives::face2(), oomph::TElement2FaceToBulkCoordinates::face2(), oomph::FaceElement::face_index(), oomph::FaceElement::face_to_bulk_coordinate_fct_pt(), i, oomph::FaceElement::nbulk_value(), oomph::FaceElement::nbulk_value_resize(), oomph::TElement< DIM, NNODE_1D >::Node_on_face(), oomph::FiniteElement::node_pt(), oomph::FaceElement::normal_sign(), oomph::GeneralisedElement::set_halo(), and oomph::FiniteElement::set_nodal_dimension().
d2shape_local()
template<unsigned NNODE_1D>
void oomph::TElement< 2, NNODE_1D >::d2shape_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline], [virtual]
Compute the geometric shape functions, derivatives and second derivatives w.r.t local coordinates at local coordinate s d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $.
Reimplemented from oomph::FiniteElement.
Definition at line 1643 of file Telements.h.
References s.
dshape_local()
template<unsigned NNODE_1D>
void oomph::TElement< 2, NNODE_1D >::dshape_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const [inline], [virtual]
Compute the geometric shape functions and derivatives w.r.t. local coordinates at local coordinate s.
Reimplemented from oomph::FiniteElement.
Definition at line 1631 of file Telements.h.
References s.
get_bulk_node_number()
template<unsigned NNODE_1D>
unsigned oomph::TElement< 2, NNODE_1D >::get_bulk_node_number (const int & face_index, const unsigned & i) const [inline], [virtual]
Public access function for Node_on_face.
Reimplemented from oomph::FiniteElement.
Definition at line 1598 of file Telements.h.
References i, and oomph::TElement< DIM, NNODE_1D >::Node_on_face().
get_s_plot()
template<unsigned NNODE_1D>
void oomph::TElement< 2, NNODE_1D >::get_s_plot (const unsigned & iplot, const unsigned & nplot, Vector< double > & s, const bool & use_equally_spaced_interior_sample_points = false) const [inline], [virtual]
Get vector of local coordinates of plot point i (when plotting nplot points in each `coordinate direction`).
Reimplemented from oomph::FiniteElement.
Definition at line 1781 of file Telements.h.
References i, and s.
invert_jacobian_mapping()
template<unsigned NNODE_1D>
double oomph::TElement< 2, NNODE_1D >::invert_jacobian_mapping (const DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const [inline], [virtual]
Overload the template-free interface for the calculation of inverse jacobian matrix. This is a two dimensional element, so use the 2D version.
Reimplemented from oomph::FiniteElement.
Definition at line 1654 of file Telements.h.
local_coordinate_of_node()
template<unsigned NNODE_1D>
void oomph::TElement< 2, NNODE_1D >::local_coordinate_of_node (const unsigned & j, Vector< double > & s) const [inline], [virtual]
Return local coordinates of node j.
Reimplemented from oomph::FiniteElement.
Definition at line 1673 of file Telements.h.
References s.
nnode_1d()
template<unsigned NNODE_1D>
unsigned oomph::TElement< 2, NNODE_1D >::nnode_1d () const [inline], [virtual]
Number of nodes along each element edge.
Reimplemented from oomph::FiniteElement.
Definition at line 1585 of file Telements.h.
nplot_points()
template<unsigned NNODE_1D>
unsigned oomph::TElement< 2, NNODE_1D >::nplot_points (const unsigned & nplot) const [inline], [virtual]
Return total number of plot points (when plotting nplot points in each "coordinate direction)
Reimplemented from oomph::FiniteElement.
Definition at line 1899 of file Telements.h.
References i.
nplot_points_paraview()
template<unsigned NNODE_1D>
unsigned oomph::TElement< 2, NNODE_1D >::nplot_points_paraview (const unsigned & nplot) const [inline], [virtual]
Return the number of actual plot points for paraview plot with parameter nplot.
Reimplemented from oomph::FiniteElement.
Definition at line 1681 of file Telements.h.
References i.
nsub_elements_paraview()
template<unsigned NNODE_1D>
unsigned oomph::TElement< 2, NNODE_1D >::nsub_elements_paraview (const unsigned & nplot) const [inline], [virtual]
Return the number of local sub-elements for paraview plot with parameter nplot.
Reimplemented from oomph::FiniteElement.
Definition at line 1693 of file Telements.h.
References i.
nvertex_node()
template<unsigned NNODE_1D>
unsigned oomph::TElement< 2, NNODE_1D >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element: One more than spatial dimension.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >.
Definition at line 1592 of file Telements.h.
output() [1/4]
template<unsigned NNODE_1D>
void oomph::TElement< 2, NNODE_1D >::output (FILE * file_pt) [virtual]
C-style output.
The C-style output function for TElement<2,NNODE_1D>
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >.
Definition at line 538 of file Telements.cc.
References oomph::CommandLineArgs::output().
output() [2/4]
template<unsigned NNODE_1D>
void oomph::TElement< 2, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [virtual]
C_style output at n_plot points.
The C-style output function for TElement<2,NNODE_1D>
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >.
Definition at line 548 of file Telements.cc.
References i, and s.
output() [3/4]
template<unsigned NNODE_1D>
void oomph::TElement< 2, NNODE_1D >::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output at specified number of plot points.
The output function for TElement<2,NNODE_1D>
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >.
Definition at line 504 of file Telements.cc.
References i, and s.
output() [4/4]
template<unsigned NNODE_1D>
void oomph::TElement< 2, NNODE_1D >::output (std::ostream & output) [virtual]
Output.
The output function for TElement<2,NNODE_1D>
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >.
Definition at line 493 of file Telements.cc.
References oomph::CommandLineArgs::output().
s_max()
template<unsigned NNODE_1D>
double oomph::TElement< 2, NNODE_1D >::s_max () const [inline], [virtual]
Max. value of local coordinate.
Reimplemented from oomph::FiniteElement.
Definition at line 1667 of file Telements.h.
s_min()
template<unsigned NNODE_1D>
double oomph::TElement< 2, NNODE_1D >::s_min () const [inline], [virtual]
Min. value of local coordinate.
Reimplemented from oomph::FiniteElement.
Definition at line 1661 of file Telements.h.
shape()
template<unsigned NNODE_1D>
void oomph::TElement< 2, NNODE_1D >::shape (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Calculate the geometric shape functions at local coordinate s.
Implements oomph::FiniteElement.
Definition at line 1624 of file Telements.h.
References s, and oomph::OneDimLagrange::shape().
tecplot_zone_string()
template<unsigned NNODE_1D>
std::string oomph::TElement< 2, NNODE_1D >::tecplot_zone_string (const unsigned & nplot) const [inline], [virtual]
Return string for tecplot zone header (when plotting nplot points in each "coordinate direction)
Reimplemented from oomph::FiniteElement.
Definition at line 1821 of file Telements.h.
References i.
vertex_node_pt()
template<unsigned NNODE_1D>
Node * oomph::TElement< 2, NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >.
Definition at line 1605 of file Telements.h.
write_paraview_offsets()
template<unsigned NNODE_1D>
void oomph::TElement< 2, NNODE_1D >::write_paraview_offsets (std::ofstream & file_out, const unsigned & nplot, unsigned & offset_sum) const [inline], [virtual]
Return the offsets for the paraview sub-elements. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
Reimplemented from oomph::FiniteElement.
Definition at line 1752 of file Telements.h.
References i.
write_paraview_output_offset_information()
template<unsigned NNODE_1D>
void oomph::TElement< 2, NNODE_1D >::write_paraview_output_offset_information (std::ofstream & file_out, const unsigned & nplot, unsigned & counter) const [inline], [virtual]
Fill in the offset information for paraview plot. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
Reimplemented from oomph::FiniteElement.
Definition at line 1706 of file Telements.h.
References i.
write_paraview_type()
template<unsigned NNODE_1D>
void oomph::TElement< 2, NNODE_1D >::write_paraview_type (std::ofstream & file_out, const unsigned & nplot) const [inline], [virtual]
Return the paraview element type. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
Reimplemented from oomph::FiniteElement.
Definition at line 1737 of file Telements.h.
References i.
write_tecplot_zone_footer() [1/2]
template<unsigned NNODE_1D>
void oomph::TElement< 2, NNODE_1D >::write_tecplot_zone_footer (FILE * file_pt, const unsigned & nplot) const [inline], [virtual]
Add tecplot zone `footer` to C-style output. (when plotting nplot points in each "coordinate direction). Empty by default -- can be used, e.g., to add FE connectivity lists to elements that need it.
Reimplemented from oomph::FiniteElement.
Definition at line 1867 of file Telements.h.
References i.
write_tecplot_zone_footer() [2/2]
template<unsigned NNODE_1D>
void oomph::TElement< 2, NNODE_1D >::write_tecplot_zone_footer (std::ostream & outfile, const unsigned & nplot) const [inline], [virtual]
Add tecplot zone `footer` to output stream (when plotting nplot points in each "coordinate direction). Empty by default -- can be used, e.g., to add FE connectivity lists to elements that need it.
Reimplemented from oomph::FiniteElement.
Definition at line 1838 of file Telements.h.
References i.
Member Data Documentation
Default_integration_scheme
template<unsigned NNODE_1D>
TGauss< 2, NNODE_1D > oomph::TElement< 2, NNODE_1D >::Default_integration_scheme [static], [private]
Default integration rule: Gaussian integration of same 'order' as the element.
Definition at line 1515 of file Telements.h.
Node_on_face
template<unsigned NNODE_1D>
const unsigned oomph::TElement< 2, NNODE_1D >::Node_on_face[3][NNODE_1D] [static], [private]
Nodal translation scheme for use when generating face elements.
Definition at line 1508 of file Telements.h.
The documentation for this class was generated from the following files:
Telements.h
Telements.cc