oomph::SpineLineVolumeConstraintBoundingElement< ELEMENT > Class Template Reference
#include <constrained_volume_elements.h>
Public Member Functions
SpineLineVolumeConstraintBoundingElement (FiniteElement *const &element_pt, const int &face_index)
Contructor: Specify bulk element and index of face to which this face element is to be attached.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::SpineLineVolumeConstraintBoundingElement< ELEMENT >
The one-dimensional interface elements that allow imposition of a volume constraint specialised for the case when the nodal positions of the bulk elements are adjusted using Spines. To enforce that a fluid volume has a certain volume, attach these elements to all faces of the (2D cartesian) bulk fluid elements (of type ELEMENT) that bound that region and then specify the `pressure` value that is traded for the constraint.
Definition at line 421 of file constrained_volume_elements.h.
Constructor & Destructor Documentation
SpineLineVolumeConstraintBoundingElement()
template<class ELEMENT >
oomph::SpineLineVolumeConstraintBoundingElement< ELEMENT >::SpineLineVolumeConstraintBoundingElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Contructor: Specify bulk element and index of face to which this face element is to be attached.
Definition at line 428 of file constrained_volume_elements.h.
References oomph::FiniteElement::build_face_element(), and oomph::FaceElement::face_index().
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::SpineLineVolumeConstraintBoundingElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Fill in contribution to residuals and Jacobian. This is specific to spine based elements in which the shape derivatives are evaluated using geometric data
Reimplemented from oomph::GeneralisedElement.
Definition at line 442 of file constrained_volume_elements.h.
References oomph::LineVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), and oomph::ElementWithMovingNodes::fill_in_jacobian_from_geometric_data().
zeta_nodal()
template<class ELEMENT >
double oomph::SpineLineVolumeConstraintBoundingElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default.
Reimplemented from oomph::FiniteElement.
Definition at line 455 of file constrained_volume_elements.h.
References i, n, and oomph::FaceElement::zeta_nodal().
The documentation for this class was generated from the following file:
constrained_volume_elements.h