oomph::HyprePreconditioner Class Reference
An Preconditioner class using the suite of Hypre preconditioners to allow.
#include <hypre_solver.h>
Public Member Functions
HyprePreconditioner (const std::string &context_string="")
Constructor. Provide optional string that is used in annotation of performance.
~HyprePreconditioner ()
Destructor.
HyprePreconditioner (const HyprePreconditioner &)=delete
Broken copy constructor.
void operator= (const HyprePreconditioner &)=delete
Broken assignment operator.
void enable_report_my_cumulative_preconditioner_solve_time ()
Enable reporting of cumulative solve time in destructor.
void disable_report_my_cumulative_preconditioner_solve_time ()
Disable reporting of cumulative solve time in destructor.
void enable_doc_time ()
Enable documentation of preconditioner timings.
void disable_doc_time ()
Disable documentation of preconditioner timings.
unsigned & hypre_method ()
Access function to Hypre_method flag -- specified via enumeration.
unsigned & internal_preconditioner ()
Access function to Internal_preconditioner flag -- specified via enumeration.
void use_BoomerAMG ()
Function to select BoomerAMG as the preconditioner.
void set_amg_iterations (const unsigned &amg_iterations)
Function to set the number of times to apply BoomerAMG.
unsigned & amg_iterations ()
Return function for Max_iter.
void amg_using_simple_smoothing ()
Function to select use of 'simple' AMG smoothers as controlled by the flag AMG_simple_smoother.
unsigned & amg_simple_smoother ()
Access function to AMG_simple_smoother flag.
void amg_using_complex_smoothing ()
Function to select use of 'complex' AMG smoothers as controlled by the flag AMG_complex_smoother.
unsigned & amg_complex_smoother ()
Access function to AMG_complex_smoother flag.
bool & amg_using_simple_smoothing_flag ()
Return function for the AMG_using_simple_smoothing_flag.
unsigned & amg_print_level ()
Access function to AMG_print_level.
unsigned & amg_smoother_iterations ()
Access function to AMG_smoother_iterations.
unsigned & amg_coarsening ()
Access function to AMG_coarsening flag.
unsigned & amg_max_levels ()
Access function to AMG_max_levels.
double & amg_damping ()
Access function to AMG_damping parameter.
double & amg_strength ()
Access function to AMG_strength.
double & amg_max_row_sum ()
Access function to AMG_max_row_sum.
double & amg_truncation ()
Access function to AMG_truncation.
void use_ParaSails ()
Function to select ParaSails as the preconditioner.
int & parasails_symmetry ()
Access function to ParaSails symmetry flag.
int & parasails_nlevel ()
Access function to ParaSails nlevel parameter.
double & parasails_thresh ()
Access function to ParaSails thresh parameter.
double & parasails_filter ()
Access function to ParaSails filter parameter.
void use_Euclid ()
Function to select use Euclid as the preconditioner.
double & euclid_droptol ()
Access function to Euclid drop tolerance parameter.
int & euclid_level ()
Access function to Euclid level parameter for ILU(k) factorization.
void enable_euclid_rowScale ()
Enable euclid rowScaling.
void disable_euclid_rowScale ()
Disable euclid row scaling.
void enable_euclid_using_BJ ()
Enable use of Block Jacobi as opposed to PILU.
void disable_euclid_using_BJ ()
Disable use of Block Jacobi, so PILU will be used.
void euclid_using_ILUK ()
Function to switch on ILU(k) factorization for Euclid (default is ILU(k) factorization)
void euclid_using_ILUT ()
Function to switch on ILUT factorization for Euclid (default is ILU(k) factorization)
unsigned & euclid_print_level ()
Function to set the level of printing from Euclid when the Euclid destructor is called 0: no printing (default) 1: prints summary of runtime settings and timings 2: as 1 plus prints memory usage.
void enable_delete_matrix ()
Hypre copies matrix data from oomph-lib's CRDoubleMatrix or DistributedCRDoubleMatrix into its own data structures, doubling the memory requirements for the matrix. As far as the Hypre solvers are concerned the oomph-lib matrix is no longer required and could be deleted to save memory. However, this will not be the expected behaviour and therefore needs to be requested explicitly by the user by calling this function which changes the flag from false (its default) to true.
void disable_delete_matrix ()
Hypre copies matrix data from oomph-lib's CRDoubleMatrix or DistributedCRDoubleMatrix into its own data structures, doubling the memory requirements for the matrix. Calling this function ensures that the matrix is not deleted.
void setup ()
Function to set up a preconditioner for the linear system defined by matrix_pt. This function is required when preconditioning and must be called before using the preconditioner_solve(...) function. This interface allows HyprePreconditioner to be used as a Preconditioner object for oomph-lib's own IterativeLinearSolver class. Note: matrix_pt must point to an object of type CRDoubleMatrix or DistributedCRDoubleMatrix. Note: Hypre copies matrix data from oomph-lib's CRDoubleMatrix and DistributedCRDoubleMatrix into its own data structures, doubling the memory requirements for the matrix. As far as the Hypre solvers are concerned, the oomph-lib matrix is no longer required and could be deleted to save memory. However, this will not be the expected behaviour and therefore needs to be requested explicitly by the user by calling the enable_delete_matrix() function.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Function applies solver to vector r for preconditioning. This requires a call to setup(...) first. Note: Hypre copies matrix data from oomph-lib's CRDoubleMatrix or DistributedCRDoubleMatrix into its own data structures, doubling the memory requirements for the matrix. As far as the Hypre solvers are concerned, the oomph-lib matrix is no longer required and could be deleted to save memory. However, this will not be the expected behaviour and therefore needs to be requested explicitly by the user with the delete_matrix() function.
void clean_up_memory ()
Function deletes all solver data.
Public Member Functions inherited from oomph::Preconditioner
Preconditioner ()
Constructor.
Preconditioner (const Preconditioner &)=delete
Broken copy constructor.
void operator= (const Preconditioner &)=delete
Broken assignment operator.
virtual ~Preconditioner ()
Destructor (empty)
virtual void preconditioner_solve_transpose (const DoubleVector &r, DoubleVector &z)
Apply the preconditioner. Pure virtual generic interface function. This method should apply the preconditioner operator to the vector r and return the vector z. (broken virtual)
virtual void setup (DoubleMatrixBase *matrix_pt)
Setup the preconditioner: store the matrix pointer and the communicator pointer then call preconditioner specific setup() function.
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
Compatability layer for old preconditioners where problem pointers were needed. The problem pointer is only used to get a communicator pointer.
void enable_silent_preconditioner_setup ()
Set up the block preconditioner quietly!
void disable_silent_preconditioner_setup ()
Be verbose in the block preconditioner setup.
virtual DoubleMatrixBase * matrix_pt () const
Get function for matrix pointer.
virtual void set_matrix_pt (DoubleMatrixBase *matrix_pt)
Set the matrix pointer.
virtual const OomphCommunicator * comm_pt () const
Get function for comm pointer.
virtual void set_comm_pt (const OomphCommunicator *const comm_pt)
Set the communicator pointer.
double setup_time () const
Returns the time to setup the preconditioner.
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
Virtual interface function for making a preconditioner a subsidiary of a block preconditioner. By default nothing is needed, but if this preconditioner is also a block preconditioner then things need to happen. There's an assumption here that the block preconditioner will be in CR form but since that assumption is hard coded all over BlockPreconditioner we're safe.
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned > > &doftype_coarsen_map_coarse)
Virtual interface function for making a preconditioner a subsidiary of a block preconditioner. By default nothing is needed, but if this preconditioner is also a block preconditioner then things need to happen. Version for coarsening dof-types.
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
if the communicator_pt is null then the distribution is not setup then false is returned, otherwise return true
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
setup the distribution of this distributable linear algebra object
void build_distribution (const LinearAlgebraDistribution &dist)
setup the distribution of this distributable linear algebra object
Public Member Functions inherited from oomph::HypreInterface
HypreInterface ()
Constructor.
~HypreInterface ()
Destructor.
HypreInterface (const HypreInterface &)=delete
Broken copy constructor.
void operator= (const HypreInterface &)=delete
Broken assignment operator.
void enable_hypre_error_messages ()
Turn on the hypre error messages.
void disable_hypre_error_messages ()
Turn off hypre error messages.
unsigned existing_solver ()
Function to return value of which solver (if any) is currently stored.
unsigned existing_preconditioner ()
Function return value of which preconditioner (if any) is stored.
Static Public Member Functions
static void report_cumulative_solve_times ()
Report cumulative solve times of all instantiations of this class.
static void reset_cumulative_solve_times ()
Reset cumulative solve times.
Static Public Attributes
static double Cumulative_preconditioner_solve_time = 0.0
Static double that accumulates the preconditioner solve time of all instantiations of this class. Reset it manually, e.g. after every Newton solve, using reset_cumulative_solve_times().
static std::map< std::string, double > Context_based_cumulative_solve_time
Static double that accumulates the preconditioner solve time of all instantiations of this class, labeled by context string. Reset it manually, e.g. after every Newton solve, using reset_cumulative_solve_times().
static unsigned Cumulative_npreconditioner_solve = 0
Static unsigned that accumulates the number of preconditioner solves of all instantiations of this class. Reset it manually, e.g. after every Newton solve, using reset_cumulative_solve_times().
static std::map< std::string, unsigned > Context_based_cumulative_npreconditioner_solve
Static unsigned that accumulates the number of preconditioner solves of all instantiations of this class, labeled by context string. Reset it manually, e.g. after every Newton solve, using reset_cumulative_solve_times().
static std::map< std::string, unsigned > Context_based_nrow
Static unsigned that stores nrow for the most recent instantiations of this class, labeled by context string. Reset it manually, e.g. after every Newton solve, using reset_cumulative_solve_times().
Private Attributes
bool Delete_matrix
Hypre copies matrix data from oomph-lib's CRDoubleMatrix or DistributedCRDoubleMatrix into its own data structures, doubling the memory requirements for the matrix. As far as the Hypre solvers are concerned the oomph-lib matrix is no longer required and could be deleted to save memory. However, this will not be the expected behaviour and therefore needs to be requested explicitly by the user by changing this flag from false (its default) to true.
bool Doc_time
double My_cumulative_preconditioner_solve_time
Private double that accumulates the preconditioner solve time of thi instantiation of this class. Is reported in destructor if Report_my_cumulative_preconditioner_solve_time is set to true.
bool Report_my_cumulative_preconditioner_solve_time
Bool to request report of My_cumulative_preconditioner_solve_time in destructor.
std::string Context_string
String can be used to provide context for annotation.
Additional Inherited Members
Public Types inherited from oomph::HypreInterface
enum Hypre_method_types {
CG
, GMRES
, BiCGStab
, BoomerAMG
,
Euclid
, ParaSails
, None
 }
Enumerated flag to define which Hypre methods are used CAREFUL: DON'T CHANGE THE ORDER OF THESE!
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
clear the distribution of this distributable linear algebra object
Protected Member Functions inherited from oomph::HypreInterface
void hypre_clean_up_memory ()
Function deletes all solver data.
void hypre_matrix_setup (CRDoubleMatrix *matrix_pt)
Function which sets values of First_global_row, Last_global_row and other partitioning data and creates the distributed Hypre matrix (stored in Matrix_ij/Matrix_par) from the CRDoubleMatrix.
void hypre_solver_setup ()
Sets up the data required for to use as an oomph-lib LinearSolver or Preconditioner. This must be called after the Hypre matrix has been generated using hypre_matrix_setup(...).
void hypre_solve (const DoubleVector &rhs, DoubleVector &solution)
Helper function performs a solve if any solver exists.
void doc_hypre_parameters ()
Doc parameters used in hypre solver.
Protected Attributes inherited from oomph::Preconditioner
bool Silent_preconditioner_setup
Boolean to indicate whether or not the build should be done silently.
std::ostream * Stream_pt
Pointer to the output stream -- defaults to std::cout.
Protected Attributes inherited from oomph::HypreInterface
bool Output_info
Flag is true to output info and results of timings.
unsigned Max_iter
Maximum number of iterations used in solver.
double Tolerance
Tolerance used to terminate solver.
unsigned Hypre_method
Hypre method flag. Valid values are specified in enumeration.
unsigned Internal_preconditioner
Preconditioner method flag used with Hypre's PCG, GMRES and BiCGStab in solve(...) or resolve(...). Valid values are BoomerAMG, Euclid, ParaSails or None (all enumerated above), for any other value no preconditioner is set.
unsigned AMG_print_level
Used to set the Hypre printing level for AMG 0: no printout 1: print setup information 2: print solve information 3: print setup and solve information.
unsigned AMG_max_levels
Maximum number of levels used in AMG.
double AMG_max_row_sum
Parameter to identify diagonally dominant parts of the matrix in AMG.
bool AMG_using_simple_smoothing
Flag to determine whether simple smoothers (determined by the AMG_simple_smoother flag) or complex smoothers (determined by the AMG_complex_smoother flag are used in AMG.
unsigned AMG_simple_smoother
Simple smoothing methods used in BoomerAMG. To use these methods set AMG_using_simple_smoothing to true. Here are the current options (from hypre's HYPRE_parcsr_ls.h):
unsigned AMG_complex_smoother
Complex smoothing methods used in BoomerAMG. To use these methods set AMG_using_simple_smoothing to false Here are the current options (from hypre's HYPRE_parcsr_ls.h):
unsigned AMG_smoother_iterations
The number of smoother iterations to apply.
double AMG_damping
Damping factor for BoomerAMG smoothed Jacobi or hybrid SOR.
double AMG_strength
Connection strength threshold parameter for BoomerAMG.
double AMG_truncation
Interpolation truncation factor for BoomerAMG.
unsigned AMG_coarsening
AMG coarsening strategy. Coarsening types include: 0 = CLJP (parallel coarsening using independent sets) 1 = classical RS with no boundary treatment (not recommended in parallel) 3 = modified RS with 3rd pass to add C points on the boundaries 6 = Falgout (uses 1 then CLJP using interior coarse points as first independent set) 8 = PMIS (parallel coarsening using independent sets - lower complexities than 0, maybe also slower convergence) 10= HMIS (one pass RS on each processor then PMIS on interior coarse points as first independent set) 11= One pass RS on each processor (not recommended)
int ParaSails_symmetry
ParaSails symmetry flag, used to inform ParaSails of Symmetry of definitenss of problem and type of ParaSails preconditioner: 0 = nonsymmetric and/or indefinite problem, nonsymmetric preconditioner 1 = SPD problem, and SPD (factored preconditioner) 2 = nonsymmetric, definite problem and SDP (factored preconditoner)
int ParaSails_nlevel
ParaSails nlevel parameter.
double ParaSails_thresh
ParaSails thresh parameter.
double ParaSails_filter
ParaSails filter parameter.
double Euclid_droptol
Euclid drop tolerance for ILU(k) and ILUT factorization.
bool Euclid_rowScale
Flag to switch on Euclid row scaling.
bool Euclid_using_ILUT
Flag to determine if ILUT (if true) or ILU(k) is used in Euclid.
bool Euclid_using_BJ
Flag to determine if Block Jacobi is used instead of PILU.
int Euclid_level
Euclid level parameter for ILU(k) factorization.
unsigned Euclid_print_level
Flag to set the level of printing from Euclid when the Euclid destructor is called 0: no printing (default) 1: prints summary of runtime settings and timings 2: as 1 plus prints memory usage.
bool AMGEuclidSmoother_use_block_jacobi
bool AMGEuclidSmoother_use_row_scaling
bool AMGEuclidSmoother_use_ilut
unsigned AMGEuclidSmoother_level
double AMGEuclidSmoother_drop_tol
unsigned AMGEuclidSmoother_print_level
unsigned Krylov_print_level
Used to set the Hypre printing level for the Krylov subspace solvers.
bool Hypre_error_messages
Flag to determine if non-zero values of the Hypre error flag plus Hypre error messages are output to screen at various points in the solve function, i.e. after:
bool Delete_input_data
Internal flag which is true when hypre_setup or hypre_solve can delete input matrix.
bool Using_distributed_rhs
Internal flag which tell the solver if the rhs Vector is distributed or not.
bool Returning_distributed_solution
Internal flag which tell the solver if the solution Vector to be returned is distributed or not.
Detailed Description
An Preconditioner class using the suite of Hypre preconditioners to allow.
 BoomerAMG (Algebraic Multi Grid),
 Euclid (ILU) or
 ParaSails (Approximate inverse)
 to be used for Preconditioner::preconditioner_solve(...). By default BoomerAMG is used.
Definition at line 1011 of file hypre_solver.h.
Constructor & Destructor Documentation
HyprePreconditioner() [1/2]
oomph::HyprePreconditioner::HyprePreconditioner (const std::string & context_string = "") [inline]
Constructor. Provide optional string that is used in annotation of performance.
Definition at line 1016 of file hypre_solver.h.
References oomph::HypreInterface::BoomerAMG, Context_string, Delete_matrix, Doc_time, oomph::HypreInterface::Hypre_method, oomph::HypreInterface::Internal_preconditioner, oomph::HypreInterface::Max_iter, My_cumulative_preconditioner_solve_time, oomph::HypreInterface::None, Report_my_cumulative_preconditioner_solve_time, and oomph::HypreInterface::Tolerance.
~HyprePreconditioner()
oomph::HyprePreconditioner::~HyprePreconditioner () [inline]
Destructor.
Definition at line 1048 of file hypre_solver.h.
References Context_string, My_cumulative_preconditioner_solve_time, oomph::oomph_info, and Report_my_cumulative_preconditioner_solve_time.
HyprePreconditioner() [2/2]
oomph::HyprePreconditioner::HyprePreconditioner (const HyprePreconditioner &) [delete]
Broken copy constructor.
Member Function Documentation
amg_coarsening()
unsigned & oomph::HyprePreconditioner::amg_coarsening () [inline]
Access function to AMG_coarsening flag.
Definition at line 1206 of file hypre_solver.h.
References oomph::HypreInterface::AMG_coarsening.
amg_complex_smoother()
unsigned & oomph::HyprePreconditioner::amg_complex_smoother () [inline]
Access function to AMG_complex_smoother flag.
Definition at line 1182 of file hypre_solver.h.
References oomph::HypreInterface::AMG_complex_smoother.
amg_damping()
double & oomph::HyprePreconditioner::amg_damping () [inline]
Access function to AMG_damping parameter.
Definition at line 1218 of file hypre_solver.h.
References oomph::HypreInterface::AMG_damping.
amg_iterations()
unsigned & oomph::HyprePreconditioner::amg_iterations () [inline]
Return function for Max_iter.
Definition at line 1156 of file hypre_solver.h.
References oomph::HypreInterface::Max_iter.
Referenced by set_amg_iterations().
amg_max_levels()
unsigned & oomph::HyprePreconditioner::amg_max_levels () [inline]
Access function to AMG_max_levels.
Definition at line 1212 of file hypre_solver.h.
References oomph::HypreInterface::AMG_max_levels.
amg_max_row_sum()
double & oomph::HyprePreconditioner::amg_max_row_sum () [inline]
Access function to AMG_max_row_sum.
Definition at line 1230 of file hypre_solver.h.
References oomph::HypreInterface::AMG_max_row_sum.
amg_print_level()
unsigned & oomph::HyprePreconditioner::amg_print_level () [inline]
Access function to AMG_print_level.
Definition at line 1194 of file hypre_solver.h.
References oomph::HypreInterface::AMG_print_level.
amg_simple_smoother()
unsigned & oomph::HyprePreconditioner::amg_simple_smoother () [inline]
Access function to AMG_simple_smoother flag.
Definition at line 1169 of file hypre_solver.h.
References oomph::HypreInterface::AMG_simple_smoother.
amg_smoother_iterations()
unsigned & oomph::HyprePreconditioner::amg_smoother_iterations () [inline]
Access function to AMG_smoother_iterations.
Definition at line 1200 of file hypre_solver.h.
References oomph::HypreInterface::AMG_smoother_iterations.
amg_strength()
double & oomph::HyprePreconditioner::amg_strength () [inline]
Access function to AMG_strength.
Definition at line 1224 of file hypre_solver.h.
References oomph::HypreInterface::AMG_strength.
amg_truncation()
double & oomph::HyprePreconditioner::amg_truncation () [inline]
Access function to AMG_truncation.
Definition at line 1236 of file hypre_solver.h.
References oomph::HypreInterface::AMG_truncation.
amg_using_complex_smoothing()
void oomph::HyprePreconditioner::amg_using_complex_smoothing () [inline]
Function to select use of 'complex' AMG smoothers as controlled by the flag AMG_complex_smoother.
Definition at line 1176 of file hypre_solver.h.
References oomph::HypreInterface::AMG_using_simple_smoothing.
amg_using_simple_smoothing()
void oomph::HyprePreconditioner::amg_using_simple_smoothing () [inline]
Function to select use of 'simple' AMG smoothers as controlled by the flag AMG_simple_smoother.
Definition at line 1163 of file hypre_solver.h.
References oomph::HypreInterface::AMG_using_simple_smoothing.
amg_using_simple_smoothing_flag()
bool & oomph::HyprePreconditioner::amg_using_simple_smoothing_flag () [inline]
Return function for the AMG_using_simple_smoothing_flag.
Definition at line 1188 of file hypre_solver.h.
References oomph::HypreInterface::AMG_using_simple_smoothing.
clean_up_memory()
void oomph::HyprePreconditioner::clean_up_memory () [virtual]
Function deletes all solver data.
clean_up_memory() deletes any existing Hypre solver and Hypre matrix
Reimplemented from oomph::Preconditioner.
Definition at line 1905 of file hypre_solver.cc.
References oomph::HypreInterface::hypre_clean_up_memory().
Referenced by setup().
disable_delete_matrix()
void oomph::HyprePreconditioner::disable_delete_matrix () [inline]
Hypre copies matrix data from oomph-lib's CRDoubleMatrix or DistributedCRDoubleMatrix into its own data structures, doubling the memory requirements for the matrix. Calling this function ensures that the matrix is not deleted.
Definition at line 1357 of file hypre_solver.h.
References Delete_matrix.
disable_doc_time()
void oomph::HyprePreconditioner::disable_doc_time () [inline]
Disable documentation of preconditioner timings.
Definition at line 1125 of file hypre_solver.h.
References Doc_time.
disable_euclid_rowScale()
void oomph::HyprePreconditioner::disable_euclid_rowScale () [inline]
Disable euclid row scaling.
Definition at line 1296 of file hypre_solver.h.
References oomph::HypreInterface::Euclid_rowScale.
disable_euclid_using_BJ()
void oomph::HyprePreconditioner::disable_euclid_using_BJ () [inline]
Disable use of Block Jacobi, so PILU will be used.
Definition at line 1310 of file hypre_solver.h.
References oomph::HypreInterface::Euclid_using_BJ.
disable_report_my_cumulative_preconditioner_solve_time()
void oomph::HyprePreconditioner::disable_report_my_cumulative_preconditioner_solve_time () [inline]
Disable reporting of cumulative solve time in destructor.
Definition at line 1113 of file hypre_solver.h.
References Report_my_cumulative_preconditioner_solve_time.
enable_delete_matrix()
void oomph::HyprePreconditioner::enable_delete_matrix () [inline]
Hypre copies matrix data from oomph-lib's CRDoubleMatrix or DistributedCRDoubleMatrix into its own data structures, doubling the memory requirements for the matrix. As far as the Hypre solvers are concerned the oomph-lib matrix is no longer required and could be deleted to save memory. However, this will not be the expected behaviour and therefore needs to be requested explicitly by the user by calling this function which changes the flag from false (its default) to true.
Definition at line 1348 of file hypre_solver.h.
References Delete_matrix.
enable_doc_time()
void oomph::HyprePreconditioner::enable_doc_time () [inline]
Enable documentation of preconditioner timings.
Definition at line 1119 of file hypre_solver.h.
References Doc_time.
enable_euclid_rowScale()
void oomph::HyprePreconditioner::enable_euclid_rowScale () [inline]
Enable euclid rowScaling.
Definition at line 1290 of file hypre_solver.h.
References oomph::HypreInterface::Euclid_rowScale.
enable_euclid_using_BJ()
void oomph::HyprePreconditioner::enable_euclid_using_BJ () [inline]
Enable use of Block Jacobi as opposed to PILU.
Definition at line 1303 of file hypre_solver.h.
References oomph::HypreInterface::Euclid_using_BJ.
enable_report_my_cumulative_preconditioner_solve_time()
void oomph::HyprePreconditioner::enable_report_my_cumulative_preconditioner_solve_time () [inline]
Enable reporting of cumulative solve time in destructor.
Definition at line 1107 of file hypre_solver.h.
References Report_my_cumulative_preconditioner_solve_time.
euclid_droptol()
double & oomph::HyprePreconditioner::euclid_droptol () [inline]
Access function to Euclid drop tolerance parameter.
Definition at line 1278 of file hypre_solver.h.
References oomph::HypreInterface::Euclid_droptol.
euclid_level()
int & oomph::HyprePreconditioner::euclid_level () [inline]
Access function to Euclid level parameter for ILU(k) factorization.
Definition at line 1284 of file hypre_solver.h.
References oomph::HypreInterface::Euclid_level.
euclid_print_level()
unsigned & oomph::HyprePreconditioner::euclid_print_level () [inline]
Function to set the level of printing from Euclid when the Euclid destructor is called 0: no printing (default) 1: prints summary of runtime settings and timings 2: as 1 plus prints memory usage.
Definition at line 1334 of file hypre_solver.h.
References oomph::HypreInterface::Euclid_print_level.
euclid_using_ILUK()
void oomph::HyprePreconditioner::euclid_using_ILUK () [inline]
Function to switch on ILU(k) factorization for Euclid (default is ILU(k) factorization)
Definition at line 1317 of file hypre_solver.h.
References oomph::HypreInterface::Euclid_using_ILUT.
euclid_using_ILUT()
void oomph::HyprePreconditioner::euclid_using_ILUT () [inline]
Function to switch on ILUT factorization for Euclid (default is ILU(k) factorization)
Definition at line 1324 of file hypre_solver.h.
References oomph::HypreInterface::Euclid_using_ILUT.
hypre_method()
unsigned & oomph::HyprePreconditioner::hypre_method () [inline]
Access function to Hypre_method flag -- specified via enumeration.
Definition at line 1131 of file hypre_solver.h.
References oomph::HypreInterface::Hypre_method.
internal_preconditioner()
unsigned & oomph::HyprePreconditioner::internal_preconditioner () [inline]
Access function to Internal_preconditioner flag -- specified via enumeration.
Definition at line 1138 of file hypre_solver.h.
References oomph::HypreInterface::Internal_preconditioner.
operator=()
void oomph::HyprePreconditioner::operator= (const HyprePreconditioner &) [delete]
Broken assignment operator.
parasails_filter()
double & oomph::HyprePreconditioner::parasails_filter () [inline]
Access function to ParaSails filter parameter.
Definition at line 1266 of file hypre_solver.h.
References oomph::HypreInterface::ParaSails_filter.
parasails_nlevel()
int & oomph::HyprePreconditioner::parasails_nlevel () [inline]
Access function to ParaSails nlevel parameter.
Definition at line 1254 of file hypre_solver.h.
References oomph::HypreInterface::ParaSails_nlevel.
parasails_symmetry()
int & oomph::HyprePreconditioner::parasails_symmetry () [inline]
Access function to ParaSails symmetry flag.
Definition at line 1248 of file hypre_solver.h.
References oomph::HypreInterface::ParaSails_symmetry.
parasails_thresh()
double & oomph::HyprePreconditioner::parasails_thresh () [inline]
Access function to ParaSails thresh parameter.
Definition at line 1260 of file hypre_solver.h.
References oomph::HypreInterface::ParaSails_thresh.
preconditioner_solve()
void oomph::HyprePreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) [virtual]
Function applies solver to vector r for preconditioning. This requires a call to setup(...) first. Note: Hypre copies matrix data from oomph-lib's CRDoubleMatrix or DistributedCRDoubleMatrix into its own data structures, doubling the memory requirements for the matrix. As far as the Hypre solvers are concerned, the oomph-lib matrix is no longer required and could be deleted to save memory. However, this will not be the expected behaviour and therefore needs to be requested explicitly by the user with the delete_matrix() function.
Preconditioner_solve uses a hypre solver to precondition vector r.
Implements oomph::Preconditioner.
Definition at line 1838 of file hypre_solver.cc.
References oomph::DoubleVector::built(), Context_based_cumulative_npreconditioner_solve, Context_based_cumulative_solve_time, Context_string, Cumulative_npreconditioner_solve, Cumulative_preconditioner_solve_time, oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::HypreInterface::existing_solver(), oomph::HypreInterface::hypre_solve(), My_cumulative_preconditioner_solve_time, oomph::HypreInterface::None, oomph::HypreInterface::Output_info, and oomph::TimingHelpers::timer().
report_cumulative_solve_times()
void oomph::HyprePreconditioner::report_cumulative_solve_times () [static]
Report cumulative solve times of all instantiations of this class.
Definition at line 1711 of file hypre_solver.cc.
References Context_based_cumulative_npreconditioner_solve, Context_based_cumulative_solve_time, Context_based_nrow, Cumulative_npreconditioner_solve, Cumulative_preconditioner_solve_time, oomph::oomph_info, and oomph::FiniteElement::size().
reset_cumulative_solve_times()
void oomph::HyprePreconditioner::reset_cumulative_solve_times () [static]
Reset cumulative solve times.
Definition at line 1762 of file hypre_solver.cc.
References Context_based_cumulative_npreconditioner_solve, Context_based_cumulative_solve_time, Context_based_nrow, Cumulative_npreconditioner_solve, and Cumulative_preconditioner_solve_time.
set_amg_iterations()
void oomph::HyprePreconditioner::set_amg_iterations (const unsigned & amg_iterations) [inline]
Function to set the number of times to apply BoomerAMG.
Definition at line 1150 of file hypre_solver.h.
References amg_iterations(), and oomph::HypreInterface::Max_iter.
setup()
void oomph::HyprePreconditioner::setup () [virtual]
Function to set up a preconditioner for the linear system defined by matrix_pt. This function is required when preconditioning and must be called before using the preconditioner_solve(...) function. This interface allows HyprePreconditioner to be used as a Preconditioner object for oomph-lib's own IterativeLinearSolver class. Note: matrix_pt must point to an object of type CRDoubleMatrix or DistributedCRDoubleMatrix. Note: Hypre copies matrix data from oomph-lib's CRDoubleMatrix and DistributedCRDoubleMatrix into its own data structures, doubling the memory requirements for the matrix. As far as the Hypre solvers are concerned, the oomph-lib matrix is no longer required and could be deleted to save memory. However, this will not be the expected behaviour and therefore needs to be requested explicitly by the user by calling the enable_delete_matrix() function.
An interface to allow HypreSolver to be used as a Preconditioner for the oomph-lib IterativeLinearSolver class. Matrix has to be of type CRDoubleMatrix or DistributedCRDoubleMatrix.
Implements oomph::Preconditioner.
Definition at line 1777 of file hypre_solver.cc.
References oomph::DistributableLinearAlgebraObject::build_distribution(), clean_up_memory(), Context_based_nrow, Context_string, oomph::HypreInterface::Delete_input_data, Delete_matrix, oomph::DistributableLinearAlgebraObject::distribution_pt(), Doc_time, oomph::HypreInterface::hypre_matrix_setup(), oomph::HypreInterface::hypre_solver_setup(), oomph::Preconditioner::matrix_pt(), oomph::DistributableLinearAlgebraObject::nrow(), oomph::oomph_info, and oomph::HypreInterface::Output_info.
use_BoomerAMG()
void oomph::HyprePreconditioner::use_BoomerAMG () [inline]
Function to select BoomerAMG as the preconditioner.
Definition at line 1144 of file hypre_solver.h.
References oomph::HypreInterface::BoomerAMG, and oomph::HypreInterface::Hypre_method.
use_Euclid()
void oomph::HyprePreconditioner::use_Euclid () [inline]
Function to select use Euclid as the preconditioner.
Definition at line 1272 of file hypre_solver.h.
References oomph::HypreInterface::Euclid, and oomph::HypreInterface::Hypre_method.
use_ParaSails()
void oomph::HyprePreconditioner::use_ParaSails () [inline]
Function to select ParaSails as the preconditioner.
Definition at line 1242 of file hypre_solver.h.
References oomph::HypreInterface::Hypre_method, and oomph::HypreInterface::ParaSails.
Member Data Documentation
Context_based_cumulative_npreconditioner_solve
std::map< std::string, unsigned > oomph::HyprePreconditioner::Context_based_cumulative_npreconditioner_solve [static]
Static unsigned that accumulates the number of preconditioner solves of all instantiations of this class, labeled by context string. Reset it manually, e.g. after every Newton solve, using reset_cumulative_solve_times().
Definition at line 1090 of file hypre_solver.h.
Referenced by preconditioner_solve(), report_cumulative_solve_times(), and reset_cumulative_solve_times().
Context_based_cumulative_solve_time
std::map< std::string, double > oomph::HyprePreconditioner::Context_based_cumulative_solve_time [static]
Static double that accumulates the preconditioner solve time of all instantiations of this class, labeled by context string. Reset it manually, e.g. after every Newton solve, using reset_cumulative_solve_times().
map of static doubles that accumulates the preconditioner solve time of all instantiations of this class, labeled by context string. Reset it manually, e.g. after every Newton solve, using reset_cumulative_solve_times().
Definition at line 1075 of file hypre_solver.h.
Referenced by preconditioner_solve(), report_cumulative_solve_times(), and reset_cumulative_solve_times().
Context_based_nrow
std::map< std::string, unsigned > oomph::HyprePreconditioner::Context_based_nrow [static]
Static unsigned that stores nrow for the most recent instantiations of this class, labeled by context string. Reset it manually, e.g. after every Newton solve, using reset_cumulative_solve_times().
Definition at line 1097 of file hypre_solver.h.
Referenced by report_cumulative_solve_times(), reset_cumulative_solve_times(), and setup().
Context_string
std::string oomph::HyprePreconditioner::Context_string [private]
String can be used to provide context for annotation.
Definition at line 1420 of file hypre_solver.h.
Referenced by HyprePreconditioner(), preconditioner_solve(), setup(), and ~HyprePreconditioner().
Cumulative_npreconditioner_solve
unsigned oomph::HyprePreconditioner::Cumulative_npreconditioner_solve = 0 [static]
Static unsigned that accumulates the number of preconditioner solves of all instantiations of this class. Reset it manually, e.g. after every Newton solve, using reset_cumulative_solve_times().
Definition at line 1082 of file hypre_solver.h.
Referenced by preconditioner_solve(), report_cumulative_solve_times(), and reset_cumulative_solve_times().
Cumulative_preconditioner_solve_time
double oomph::HyprePreconditioner::Cumulative_preconditioner_solve_time = 0.0 [static]
Static double that accumulates the preconditioner solve time of all instantiations of this class. Reset it manually, e.g. after every Newton solve, using reset_cumulative_solve_times().
Definition at line 1068 of file hypre_solver.h.
Referenced by preconditioner_solve(), report_cumulative_solve_times(), and reset_cumulative_solve_times().
Delete_matrix
bool oomph::HyprePreconditioner::Delete_matrix [private]
Hypre copies matrix data from oomph-lib's CRDoubleMatrix or DistributedCRDoubleMatrix into its own data structures, doubling the memory requirements for the matrix. As far as the Hypre solvers are concerned the oomph-lib matrix is no longer required and could be deleted to save memory. However, this will not be the expected behaviour and therefore needs to be requested explicitly by the user by changing this flag from false (its default) to true.
Definition at line 1404 of file hypre_solver.h.
Referenced by disable_delete_matrix(), enable_delete_matrix(), HyprePreconditioner(), and setup().
Doc_time
bool oomph::HyprePreconditioner::Doc_time [private]
Definition at line 1407 of file hypre_solver.h.
Referenced by disable_doc_time(), enable_doc_time(), HyprePreconditioner(), and setup().
My_cumulative_preconditioner_solve_time
double oomph::HyprePreconditioner::My_cumulative_preconditioner_solve_time [private]
Private double that accumulates the preconditioner solve time of thi instantiation of this class. Is reported in destructor if Report_my_cumulative_preconditioner_solve_time is set to true.
Definition at line 1413 of file hypre_solver.h.
Referenced by HyprePreconditioner(), preconditioner_solve(), and ~HyprePreconditioner().
Report_my_cumulative_preconditioner_solve_time
bool oomph::HyprePreconditioner::Report_my_cumulative_preconditioner_solve_time [private]
Bool to request report of My_cumulative_preconditioner_solve_time in destructor.
Definition at line 1417 of file hypre_solver.h.
Referenced by disable_report_my_cumulative_preconditioner_solve_time(), enable_report_my_cumulative_preconditioner_solve_time(), HyprePreconditioner(), and ~HyprePreconditioner().
The documentation for this class was generated from the following files:
hypre_solver.h
hypre_solver.cc