oomph::Circle Class Reference
Circle in 2D space.
#include <geom_objects.h>
Public Member Functions
Circle (const double &x_c, const double &y_c, const double &r)
Constructor: Pass x and y-coords of centre and radius (all pinned)
Circle (const double &x_c, const double &y_c, const double &r, TimeStepper *time_stepper_pt)
Constructor: Pass x and y-coords of centre and radius (all pinned) Circle is static but can be used in time-dependent runs with specified timestepper.
Circle (const Vector< Data * > &geom_data_pt)
Constructor: Pass x and y-coords of centre and radius (all as Data)
Circle (const Circle &dummy)=delete
Broken copy constructor.
void operator= (const Circle &)=delete
Broken assignment operator.
virtual ~Circle ()
Destructor: Clean up if necessary.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position Vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep.
double & x_c ()
Access function to x-coordinate of centre of circle.
double & y_c ()
Access function to y-coordinate of centre of circle.
double & R ()
Access function to radius of circle.
unsigned ngeom_data () const
How many items of Data does the shape of the object depend on?
Data * geom_data_pt (const unsigned &j)
Return pointer to the j-th Data item that the object's shape depends on.
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
Constructor: Pass dimension of geometric object (# of Eulerian coords = # of Lagrangian coords; no time history available/needed)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
Constructor: pass # of Eulerian and Lagrangian coordinates. No time history available/needed.
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
Constructor: pass # of Eulerian and Lagrangian coordinates and pointer to time-stepper which is used to handle the position at previous timesteps and allows the evaluation of veloc/acceleration etc. in cases where the GeomData varies with time.
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
Access function for pointer to time stepper: Null if object is not time-dependent.
TimeStepper * time_stepper_pt () const
Access function for pointer to time stepper: Null if object is not time-dependent. Const version.
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
Parametrised position on object: r(zeta). Evaluated at the continuous time value, t.
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
j-th time-derivative on object at current time: $ \frac{d^{j} r(\zeta)}{dt^j} $.
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
Derivative of position Vector w.r.t. to coordinates: $ \frac{dR_i}{d \zeta_\alpha}$ = drdzeta(alpha,i). Evaluated at current time.
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
2nd derivative of position Vector w.r.t. to coordinates: $ \frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}$ = ddrdzeta(alpha,beta,i). Evaluated at current time.
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Posn Vector and its 1st & 2nd derivatives w.r.t. to coordinates: $ \frac{dR_i}{d \zeta_\alpha}$ = drdzeta(alpha,i). $ \frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}$ = ddrdzeta(alpha,beta,i). Evaluated at current time.
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
A geometric object may be composed of may sub-objects (e.g. a finite-element representation of a boundary). In order to implement sparse update functions, it is necessary to know the sub-object and local coordinate within that sub-object at a given intrinsic coordinate, zeta. Note that only one sub-object can "cover" any given intrinsic position. If the position is at an "interface" between sub-objects, either one can be returned. The default implementation merely returns, the pointer to the "entire" GeomObject and the coordinate, zeta The optional boolean flag only applies if a Newton method is used to find the value of zeta, and if true the value of the coordinate s is used as the initial guess for the method. If the flag is false (the default) a value of s=0 is used as the initial guess.
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
A geometric object may be composed of many sub-objects each with their own local coordinate. This function returns the "global" intrinsic coordinate zeta (within the compound object), at a given local coordinate s (i.e. the intrinsic coordinate of the sub-GeomObject. In simple (non-compound) GeomObjects, the local intrinsic coordinate is the global intrinsic coordinate and so the function merely returns s. To make it less likely that the default implementation is called in error (because it is not overloaded in a derived GeomObject where the default is not appropriate, we do at least check that s and zeta have the same size if called in PARANOID mode.
Protected Attributes
Vector< Data * > Geom_data_pt
Vector of pointers to Data items that affects the object's shape.
bool Must_clean_up
Do I need to clean up?
bool Is_time_dependent
Genuine time-dependence?
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Timestepper (used to handle access to geometry at previous timesteps)
Detailed Description
Circle in 2D space.
 x = X_c + R \cos(\zeta)  
 y = Y_c + R \sin(\zeta)  
Definition at line 872 of file geom_objects.h.
Constructor & Destructor Documentation
Circle() [1/4]
oomph::Circle::Circle (const double & x_c, const double & y_c, const double & r) [inline]
Constructor: Pass x and y-coords of centre and radius (all pinned)
Definition at line 876 of file geom_objects.h.
References Geom_data_pt, Is_time_dependent, Must_clean_up, x_c(), and y_c().
Circle() [2/4]
oomph::Circle::Circle (const double & x_c, const double & y_c, const double & r, TimeStepper * time_stepper_pt) [inline]
Constructor: Pass x and y-coords of centre and radius (all pinned) Circle is static but can be used in time-dependent runs with specified timestepper.
Definition at line 915 of file geom_objects.h.
References oomph::TimeStepper::assign_initial_values_impulsive(), Geom_data_pt, Is_time_dependent, Must_clean_up, oomph::GeomObject::time_stepper_pt(), x_c(), and y_c().
Circle() [3/4]
oomph::Circle::Circle (const Vector< Data * > & geom_data_pt) [inline]
Constructor: Pass x and y-coords of centre and radius (all as Data)
Geom_data_pt[0]->value(0) = X_c;
Geom_data_pt[0]->value(1) = Y_c;
Geom_data_pt[0]->value(2) = R;
Definition at line 964 of file geom_objects.h.
References geom_data_pt(), Geom_data_pt, Is_time_dependent, Must_clean_up, oomph::Data::nvalue(), and oomph::GeomObject::time_stepper_pt().
Circle() [4/4]
oomph::Circle::Circle (const Circle & dummy) [delete]
Broken copy constructor.
~Circle()
virtual oomph::Circle::~Circle () [inline], [virtual]
Destructor: Clean up if necessary.
Definition at line 1009 of file geom_objects.h.
References Geom_data_pt, i, Must_clean_up, ngeom_data(), and oomph::FiniteElement::size().
Member Function Documentation
geom_data_pt()
Data * oomph::Circle::geom_data_pt (const unsigned & j) [inline], [virtual]
Return pointer to the j-th Data item that the object's shape depends on.
Reimplemented from oomph::GeomObject.
Definition at line 1102 of file geom_objects.h.
References Geom_data_pt.
Referenced by Circle().
ngeom_data()
unsigned oomph::Circle::ngeom_data () const [inline], [virtual]
How many items of Data does the shape of the object depend on?
Reimplemented from oomph::GeomObject.
Definition at line 1095 of file geom_objects.h.
References Geom_data_pt, and oomph::FiniteElement::size().
Referenced by ~Circle().
operator=()
void oomph::Circle::operator= (const Circle &) [delete]
Broken assignment operator.
position() [1/2]
void oomph::Circle::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const [inline], [virtual]
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep.
Reimplemented from oomph::GeomObject.
Definition at line 1040 of file geom_objects.h.
References Geom_data_pt, Is_time_dependent, oomph::TimeStepper::nprev_values(), position(), R(), t, and oomph::GeomObject::time_stepper_pt().
position() [2/2]
void oomph::Circle::position (const Vector< double > & zeta, Vector< double > & r) const [inline], [virtual]
Position Vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
Definition at line 1024 of file geom_objects.h.
References Geom_data_pt, and R().
Referenced by oomph::CylinderWithFlagDomain::macro_element_boundary(), and position().
R()
double & oomph::Circle::R () [inline]
Access function to radius of circle.
Definition at line 1089 of file geom_objects.h.
References Geom_data_pt.
Referenced by position(), and position().
x_c()
double & oomph::Circle::x_c () [inline]
Access function to x-coordinate of centre of circle.
Definition at line 1077 of file geom_objects.h.
References Geom_data_pt.
Referenced by Circle(), and Circle().
y_c()
double & oomph::Circle::y_c () [inline]
Access function to y-coordinate of centre of circle.
Definition at line 1083 of file geom_objects.h.
References Geom_data_pt.
Referenced by Circle(), and Circle().
Member Data Documentation
Geom_data_pt
Vector<Data*> oomph::Circle::Geom_data_pt [protected]
Vector of pointers to Data items that affects the object's shape.
Definition at line 1109 of file geom_objects.h.
Referenced by Circle(), Circle(), Circle(), geom_data_pt(), ngeom_data(), position(), position(), R(), x_c(), y_c(), and ~Circle().
Is_time_dependent
bool oomph::Circle::Is_time_dependent [protected]
Genuine time-dependence?
Definition at line 1115 of file geom_objects.h.
Referenced by Circle(), Circle(), Circle(), and position().
Must_clean_up
bool oomph::Circle::Must_clean_up [protected]
Do I need to clean up?
Definition at line 1112 of file geom_objects.h.
Referenced by Circle(), Circle(), Circle(), and ~Circle().
The documentation for this class was generated from the following file:
geom_objects.h