oomph::PeriodicOrbitBaseElement Class Reference
#include <periodic_orbit_handler.h>
Public Member Functions
PeriodicOrbitBaseElement ()
virtual void get_non_external_dofs (Vector< double > &u)
Interface to get the current value of all (internal and shared) unknowns.
virtual void get_non_external_ddofs_dt (Vector< double > &du_dt)
Interface to get the current value of the time derivative of all (internal and shared) unknowns.
virtual void get_inner_product_matrix (DenseMatrix< double > &inner_product)
Get the inner product matrix.
virtual void spacetime_output (std::ostream &outilfe, const unsigned &Nplot, const double &time=0.0)
Additional Inherited Members
Detailed Description
Definition at line 1457 of file periodic_orbit_handler.h.
Constructor & Destructor Documentation
PeriodicOrbitBaseElement()
oomph::PeriodicOrbitBaseElement::PeriodicOrbitBaseElement () [inline]
Definition at line 1460 of file periodic_orbit_handler.h.
Member Function Documentation
get_inner_product_matrix()
virtual void oomph::PeriodicOrbitBaseElement::get_inner_product_matrix (DenseMatrix< double > & inner_product) [inline], [virtual]
Get the inner product matrix.
Definition at line 1472 of file periodic_orbit_handler.h.
References i, oomph::DenseMatrix< T >::initialise(), and oomph::GeneralisedElement::ndof().
Referenced by oomph::PeriodicOrbitEquations::fill_in_generic_residual_contribution_orbit().
get_non_external_ddofs_dt()
virtual void oomph::PeriodicOrbitBaseElement::get_non_external_ddofs_dt (Vector< double > & du_dt) [inline], [virtual]
Interface to get the current value of the time derivative of all (internal and shared) unknowns.
Definition at line 1468 of file periodic_orbit_handler.h.
Referenced by oomph::PeriodicOrbitEquations::fill_in_generic_residual_contribution_orbit().
get_non_external_dofs()
virtual void oomph::PeriodicOrbitBaseElement::get_non_external_dofs (Vector< double > & u) [inline], [virtual]
Interface to get the current value of all (internal and shared) unknowns.
Definition at line 1464 of file periodic_orbit_handler.h.
Referenced by oomph::PeriodicOrbitEquations::fill_in_generic_residual_contribution_orbit().
spacetime_output()
virtual void oomph::PeriodicOrbitBaseElement::spacetime_output (std::ostream & outilfe, const unsigned & Nplot, const double & time = 0.0) [inline], [virtual]
Definition at line 1482 of file periodic_orbit_handler.h.
Referenced by oomph::PeriodicOrbitEquations::orbit_output().
The documentation for this class was generated from the following file:
periodic_orbit_handler.h