oomph::SolidTractionElement< ELEMENT > Class Template Reference
A class for elements that allow the imposition of an applied traction in the principle of virtual displacements. The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
#include <solid_traction_elements.h>
Public Member Functions
SolidTractionElement (FiniteElement *const &element_pt, const int &face_index, const bool &called_from_refineable_constructor=false)
Constructor, which takes a `bulk` element and the value of the index and its limit.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Return the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Fill in contribution from Jacobian.
void output (std::ostream &outfile)
Output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
void output (FILE *file_pt)
C_style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function.
void traction (const Vector< double > &s, Vector< double > &traction)
Compute traction vector at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
Public Attributes
void(*&)(const Vector< double > &xi, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction) traction_fct_pt ()
Reference to the traction function pointer.
Protected Member Functions
virtual void get_traction (const unsigned &intpt, const Vector< double > &xi, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction)
Get the traction vector: Pass number of integration point (dummy), Lagr. coordinate and normal vector and return the load vector (not all of the input arguments will be required for all specific load functions but the list should cover all cases). This function is virtual so it can be overloaded for FSI.
void fill_in_contribution_to_residuals_solid_traction (Vector< double > &residuals)
Helper function that actually calculates the residuals.
Protected Attributes
void(* Traction_fct_pt)(const Vector< double > &xi, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
Pointer to an imposed traction function. Arguments: Lagrangian coordinate; Eulerian coordinate; outer unit normal; applied traction. (Not all of the input arguments will be required for all specific load functions but the list should cover all cases)
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::SolidTractionElement< ELEMENT >
A class for elements that allow the imposition of an applied traction in the principle of virtual displacements. The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
Definition at line 76 of file solid_traction_elements.h.
Constructor & Destructor Documentation
SolidTractionElement()
template<class ELEMENT >
oomph::SolidTractionElement< ELEMENT >::SolidTractionElement (FiniteElement *const & element_pt, const int & face_index, const bool & called_from_refineable_constructor = false) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit.
Definition at line 118 of file solid_traction_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FiniteElement::dim(), oomph::FaceElement::face_index(), oomph::FiniteElement::has_hanging_nodes(), oomph::SolidTractionElement< ELEMENT >::Traction_fct_pt, and oomph::SolidTractionElementHelper::Zero_traction_fct().
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::SolidTractionElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Fill in contribution from Jacobian.
Reimplemented from oomph::SolidFiniteElement.
Reimplemented in oomph::RefineableSolidTractionElement< ELEMENT >, oomph::FSISolidTractionElement< ELEMENT, DIM >, and oomph::RefineableFSISolidTractionElement< ELEMENT, DIM >.
Definition at line 176 of file solid_traction_elements.h.
References oomph::SolidTractionElement< ELEMENT >::fill_in_contribution_to_residuals_solid_traction(), and oomph::GeneralisedElement::fill_in_jacobian_from_external_by_fd().
Referenced by oomph::FSISolidTractionElement< ELEMENT, DIM >::fill_in_contribution_to_jacobian().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::SolidTractionElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Return the residuals.
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::RefineableSolidTractionElement< ELEMENT >.
Definition at line 169 of file solid_traction_elements.h.
References oomph::SolidTractionElement< ELEMENT >::fill_in_contribution_to_residuals_solid_traction().
fill_in_contribution_to_residuals_solid_traction()
template<class ELEMENT >
void oomph::SolidTractionElement< ELEMENT >::fill_in_contribution_to_residuals_solid_traction (Vector< double > & residuals) [protected]
Helper function that actually calculates the residuals.
Return the residuals for the SolidTractionElement equations.
Definition at line 316 of file solid_traction_elements.h.
References i, and oomph::QuadTreeNames::W.
Referenced by oomph::SolidTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::SolidTractionElement< ELEMENT >::fill_in_contribution_to_residuals().
get_traction()
template<class ELEMENT >
virtual void oomph::SolidTractionElement< ELEMENT >::get_traction (const unsigned & intpt, const Vector< double > & xi, const Vector< double > & x, const Vector< double > & n, Vector< double > & traction) [inline], [protected], [virtual]
Get the traction vector: Pass number of integration point (dummy), Lagr. coordinate and normal vector and return the load vector (not all of the input arguments will be required for all specific load functions but the list should cover all cases). This function is virtual so it can be overloaded for FSI.
Reimplemented in oomph::FSISolidTractionElement< ELEMENT, DIM >.
Definition at line 97 of file solid_traction_elements.h.
References oomph::SolidTractionElement< ELEMENT >::traction(), and oomph::SolidTractionElement< ELEMENT >::Traction_fct_pt.
Referenced by oomph::SolidTractionElement< ELEMENT >::output().
output() [1/4]
template<class ELEMENT >
void oomph::SolidTractionElement< ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C_style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 258 of file solid_traction_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<class ELEMENT >
void oomph::SolidTractionElement< ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 264 of file solid_traction_elements.h.
References oomph::FiniteElement::output().
output() [3/4]
template<class ELEMENT >
void oomph::SolidTractionElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Definition at line 191 of file solid_traction_elements.h.
References oomph::SolidTractionElement< ELEMENT >::output().
Referenced by oomph::SolidTractionElement< ELEMENT >::output().
output() [4/4]
template<class ELEMENT >
void oomph::SolidTractionElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::FSISolidTractionElement< ELEMENT, DIM >.
Definition at line 199 of file solid_traction_elements.h.
References oomph::FiniteElement::get_s_plot(), oomph::SolidTractionElement< ELEMENT >::get_traction(), i, oomph::FaceElement::interpolated_x(), oomph::SolidFaceElement::interpolated_xi(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::nplot_points(), oomph::FaceElement::outer_unit_normal(), s, oomph::FiniteElement::tecplot_zone_string(), oomph::SolidTractionElement< ELEMENT >::traction(), and oomph::FiniteElement::write_tecplot_zone_footer().
traction()
template<class ELEMENT >
void oomph::SolidTractionElement< ELEMENT >::traction (const Vector< double > & s, Vector< double > & traction)
Compute traction vector at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Compute traction vector at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
Definition at line 286 of file solid_traction_elements.h.
References s.
Referenced by oomph::SolidTractionElement< ELEMENT >::get_traction(), oomph::FSISolidTractionElement< ELEMENT, DIM >::get_traction(), oomph::SolidTractionElement< ELEMENT >::output(), and oomph::FSISolidTractionElement< ELEMENT, DIM >::output().
Member Data Documentation
traction_fct_pt
template<class ELEMENT >
void(*&)(const Vector< double > &xi, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction) oomph::SolidTractionElement< ELEMENT >::traction_fct_pt() [inline]
Reference to the traction function pointer.
Definition at line 159 of file solid_traction_elements.h.
Traction_fct_pt
template<class ELEMENT >
void(* oomph::SolidTractionElement< ELEMENT >::Traction_fct_pt) (const Vector< double > &xi, const Vector< double > &x, const Vector< double > &n, Vector< double > &result) [protected]
Pointer to an imposed traction function. Arguments: Lagrangian coordinate; Eulerian coordinate; outer unit normal; applied traction. (Not all of the input arguments will be required for all specific load functions but the list should cover all cases)
Definition at line 85 of file solid_traction_elements.h.
Referenced by oomph::SolidTractionElement< ELEMENT >::get_traction(), and oomph::SolidTractionElement< ELEMENT >::SolidTractionElement().
The documentation for this class was generated from the following file:
solid_traction_elements.h