oomph::GMRESBlockPreconditioner Class Reference
The block preconditioner form of GMRES. This version extracts the blocks from the global systems and assembles the system by concatenating all the matrices together.
#include <general_purpose_space_time_subsidiary_block_preconditioner.h>
Public Member Functions
GMRESBlockPreconditioner ()
Constructor (empty)
virtual ~GMRESBlockPreconditioner ()
Destructor.
virtual void clean_up_memory ()
Clean up the memory (empty for now...)
GMRESBlockPreconditioner (const GMRESBlockPreconditioner &)
Broken copy constructor.
void operator= (const GMRESBlockPreconditioner &)
Broken assignment operator.
void setup ()
Setup the preconditioner.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply preconditioner to r.
void solve (Problem *const &problem_pt, DoubleVector &result)
Solver: Takes pointer to problem and returns the results vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual vector.
unsigned iterations () const
Handle to the number of iterations taken.
void set_preconditioner_LHS ()
Set left preconditioning (the default)
void set_preconditioner_RHS ()
Enable right preconditioning.
void enable_doc_memory_usage ()
Document the memory usage.
void disable_doc_memory_usage ()
Don't document the memory usage!
double get_memory_usage_in_bytes ()
Get the memory statistics.
SpaceTimeNavierStokesSubsidiaryPreconditioner * navier_stokes_subsidiary_preconditioner_pt () const
GMRESBlockPreconditioner ()
Constructor (empty)
virtual ~GMRESBlockPreconditioner ()
Destructor.
virtual void clean_up_memory ()
Clean up the memory (empty for now...)
GMRESBlockPreconditioner (const GMRESBlockPreconditioner &)
Broken copy constructor.
void operator= (const GMRESBlockPreconditioner &)
Broken assignment operator.
void setup ()
Setup the preconditioner.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply preconditioner to r.
void solve (Problem *const &problem_pt, DoubleVector &result)
Solver: Takes pointer to problem and returns the results vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual vector.
unsigned iterations () const
Handle to the number of iterations taken.
void set_preconditioner_LHS ()
Set left preconditioning (the default)
void set_preconditioner_RHS ()
Enable right preconditioning.
void enable_doc_memory_statistics ()
Document the memory usage.
void disable_doc_memory_statistics ()
Don't document the memory usage!
double get_memory_usage_in_bytes ()
Get the memory statistics.
SpaceTimeNavierStokesSubsidiaryPreconditioner * navier_stokes_subsidiary_preconditioner_pt () const
void setup (DoubleMatrixBase *matrix_pt)
For some reason we need to remind the compiler that there is also a function named setup in the base class.
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
For some reason we need to remind the compiler that there is also a function named setup in the base class.
virtual void setup ()=0
For some reason we need to remind the compiler that there is also a function named setup in the base class.
void setup (DoubleMatrixBase *matrix_pt)
For some reason we need to remind the compiler that there is also a function named setup in the base class.
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
For some reason we need to remind the compiler that there is also a function named setup in the base class.
virtual void setup ()=0
For some reason we need to remind the compiler that there is also a function named setup in the base class.
Private Member Functions
void update (const unsigned &k, const Vector< Vector< double >> &H, const Vector< double > &s, const Vector< DoubleVector > &v, const DoubleVector &block_x_with_size_of_full_x, DoubleVector &x)
void generate_plane_rotation (double &dx, double &dy, double &cs, double &sn)
Helper function: Generate a plane rotation. This is done by finding the values of $ \cos(\theta) $ (i.e. cs) and \sin(\theta) (i.e. sn) such that:
void apply_plane_rotation (double &dx, double &dy, double &cs, double &sn)
Helper function: Apply plane rotation. This is done using the update:
void update (const unsigned &k, const Vector< Vector< double >> &H, const Vector< double > &s, const Vector< DoubleVector > &v, const DoubleVector &block_x_with_size_of_full_x, DoubleVector &x)
void generate_plane_rotation (double &dx, double &dy, double &cs, double &sn)
Helper function: Generate a plane rotation. This is done by finding the values of $ \cos(\theta) $ (i.e. cs) and \sin(\theta) (i.e. sn) such that:
void apply_plane_rotation (double &dx, double &dy, double &cs, double &sn)
Helper function: Apply plane rotation. This is done using the update:
Private Attributes
CRDoubleMatrix * Matrix_pt
Pointer to matrix.
SpaceTimeNavierStokesSubsidiaryPreconditioner * Navier_stokes_subsidiary_preconditioner_pt
Pointer to the preconditioner for the block matrix.
unsigned Iterations
Number of iterations taken.
bool Compute_memory_statistics
Flag to indicate whether or not to record the memory statistics this preconditioner.
double Memory_usage_in_bytes
Storage for the memory usage of the solver if the flag above is set to true (in bytes)
bool Preconditioner_has_been_setup
Control flag is true if the preconditioner has been setup (used so we can wipe the data when the preconditioner is called again)
bool Preconditioner_LHS
boolean indicating use of left hand preconditioning (if true) or right hand preconditioning (if false)
Additional Inherited Members
Detailed Description
The block preconditioner form of GMRES. This version extracts the blocks from the global systems and assembles the system by concatenating all the matrices together.
Definition at line 250 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
Constructor & Destructor Documentation
GMRESBlockPreconditioner() [1/4]
oomph::GMRESBlockPreconditioner::GMRESBlockPreconditioner () [inline]
Constructor (empty)
Definition at line 256 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
References Compute_memory_statistics, and Memory_usage_in_bytes.
 GMRESBlockPreconditioner() [1/2]
virtual oomph::GMRESBlockPreconditioner::~GMRESBlockPreconditioner () [inline], [virtual]
Destructor.
Definition at line 272 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
References clean_up_memory().
GMRESBlockPreconditioner() [2/4]
oomph::GMRESBlockPreconditioner::GMRESBlockPreconditioner (const GMRESBlockPreconditioner &) [inline]
Broken copy constructor.
Definition at line 299 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
References oomph::BrokenCopy::broken_copy().
GMRESBlockPreconditioner() [3/4]
oomph::GMRESBlockPreconditioner::GMRESBlockPreconditioner () [inline]
Constructor (empty)
Definition at line 263 of file spacetime_navier_stokes_block_preconditioner.h.
References Compute_memory_statistics, and Memory_usage_in_bytes.
 GMRESBlockPreconditioner() [2/2]
virtual oomph::GMRESBlockPreconditioner::~GMRESBlockPreconditioner () [inline], [virtual]
Destructor.
Definition at line 279 of file spacetime_navier_stokes_block_preconditioner.h.
References clean_up_memory().
GMRESBlockPreconditioner() [4/4]
oomph::GMRESBlockPreconditioner::GMRESBlockPreconditioner (const GMRESBlockPreconditioner &) [inline]
Broken copy constructor.
Definition at line 306 of file spacetime_navier_stokes_block_preconditioner.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
apply_plane_rotation() [1/2]
void oomph::GMRESBlockPreconditioner::apply_plane_rotation (double & dx, double & dy, double & cs, double & sn) [inline], [private]
Helper function: Apply plane rotation. This is done using the update:
 \begin{bmatrix} dx \newline dy \end{bmatrix} \leftarrow \begin{bmatrix} \cos\theta & \sin\theta \newline -\sin\theta & \cos\theta \end{bmatrix} \begin{bmatrix} dx \newline dy \end{bmatrix}. 
Definition at line 606 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
Referenced by preconditioner_solve().
apply_plane_rotation() [2/2]
void oomph::GMRESBlockPreconditioner::apply_plane_rotation (double & dx, double & dy, double & cs, double & sn) [inline], [private]
Helper function: Apply plane rotation. This is done using the update:
 \begin{bmatrix} dx \newline dy \end{bmatrix} \leftarrow \begin{bmatrix} \cos\theta & \sin\theta \newline -\sin\theta & \cos\theta \end{bmatrix} \begin{bmatrix} dx \newline dy \end{bmatrix}. 
Definition at line 613 of file spacetime_navier_stokes_block_preconditioner.h.
clean_up_memory() [1/2]
virtual void oomph::GMRESBlockPreconditioner::clean_up_memory () [inline], [virtual]
Clean up the memory (empty for now...)
Reimplemented from oomph::LinearSolver.
Definition at line 279 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
References Matrix_pt, Navier_stokes_subsidiary_preconditioner_pt, and Preconditioner_has_been_setup.
Referenced by setup(), and ~GMRESBlockPreconditioner().
clean_up_memory() [2/2]
virtual void oomph::GMRESBlockPreconditioner::clean_up_memory () [inline], [virtual]
Clean up the memory (empty for now...)
Reimplemented from oomph::LinearSolver.
Definition at line 286 of file spacetime_navier_stokes_block_preconditioner.h.
References Matrix_pt, Navier_stokes_subsidiary_preconditioner_pt, and Preconditioner_has_been_setup.
disable_doc_memory_statistics()
void oomph::GMRESBlockPreconditioner::disable_doc_memory_statistics () [inline]
Don't document the memory usage!
Set the appropriate flag to false
Definition at line 367 of file spacetime_navier_stokes_block_preconditioner.h.
References Compute_memory_statistics.
disable_doc_memory_usage()
void oomph::GMRESBlockPreconditioner::disable_doc_memory_usage () [inline]
Don't document the memory usage!
Set the appropriate flag to false
Definition at line 360 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
References Compute_memory_statistics.
enable_doc_memory_statistics()
void oomph::GMRESBlockPreconditioner::enable_doc_memory_statistics () [inline]
Document the memory usage.
Set the appropriate flag to true
Definition at line 359 of file spacetime_navier_stokes_block_preconditioner.h.
References Compute_memory_statistics.
enable_doc_memory_usage()
void oomph::GMRESBlockPreconditioner::enable_doc_memory_usage () [inline]
Document the memory usage.
Set the appropriate flag to true
Definition at line 352 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
References Compute_memory_statistics.
generate_plane_rotation() [1/2]
void oomph::GMRESBlockPreconditioner::generate_plane_rotation (double & dx, double & dy, double & cs, double & sn) [inline], [private]
Helper function: Generate a plane rotation. This is done by finding the values of $ \cos(\theta) $ (i.e. cs) and \sin(\theta) (i.e. sn) such that:
 \begin{bmatrix} \cos\theta & \sin\theta \newline -\sin\theta & \cos\theta \end{bmatrix} \begin{bmatrix} dx \newline dy \end{bmatrix} = \begin{bmatrix} r \newline 0 \end{bmatrix}, 
 where $ r=\sqrt{pow(dx,2)+pow(dy,2)} $. The values of a and b are given by:
 \cos\theta&=\dfrac{dx}{\sqrt{pow(dx,2)+pow(dy,2)}}, 
 and
 \sin\theta&=\dfrac{dy}{\sqrt{pow(dx,2)+pow(dy,2)}}. 
 Taken from: Saad Y.`Iterative methods for sparse linear systems`, p.192
Definition at line 547 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
Referenced by preconditioner_solve().
generate_plane_rotation() [2/2]
void oomph::GMRESBlockPreconditioner::generate_plane_rotation (double & dx, double & dy, double & cs, double & sn) [inline], [private]
Helper function: Generate a plane rotation. This is done by finding the values of $ \cos(\theta) $ (i.e. cs) and \sin(\theta) (i.e. sn) such that:
 \begin{bmatrix} \cos\theta & \sin\theta \newline -\sin\theta & \cos\theta \end{bmatrix} \begin{bmatrix} dx \newline dy \end{bmatrix} = \begin{bmatrix} r \newline 0 \end{bmatrix}, 
 where $ r=\sqrt{pow(dx,2)+pow(dy,2)} $. The values of a and b are given by:
 \cos\theta&=\dfrac{dx}{\sqrt{pow(dx,2)+pow(dy,2)}}, 
 and
 \sin\theta&=\dfrac{dy}{\sqrt{pow(dx,2)+pow(dy,2)}}. 
 Taken from: Saad Y.`Iterative methods for sparse linear systems`, p.192
Definition at line 554 of file spacetime_navier_stokes_block_preconditioner.h.
get_memory_usage_in_bytes() [1/2]
double oomph::GMRESBlockPreconditioner::get_memory_usage_in_bytes () [inline]
Get the memory statistics.
Definition at line 368 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
References Compute_memory_statistics, Memory_usage_in_bytes, and Preconditioner_has_been_setup.
Referenced by oomph::BandedBlockTriangularPreconditioner< MATRIX >::setup().
get_memory_usage_in_bytes() [2/2]
double oomph::GMRESBlockPreconditioner::get_memory_usage_in_bytes () [inline]
Get the memory statistics.
Definition at line 375 of file spacetime_navier_stokes_block_preconditioner.h.
References Compute_memory_statistics, Memory_usage_in_bytes, and Preconditioner_has_been_setup.
iterations() [1/2]
unsigned oomph::GMRESBlockPreconditioner::iterations () const [inline], [virtual]
Handle to the number of iterations taken.
Implements oomph::IterativeLinearSolver.
Definition at line 332 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
References Iterations.
iterations() [2/2]
unsigned oomph::GMRESBlockPreconditioner::iterations () const [inline], [virtual]
Handle to the number of iterations taken.
Implements oomph::IterativeLinearSolver.
Definition at line 339 of file spacetime_navier_stokes_block_preconditioner.h.
References Iterations.
navier_stokes_subsidiary_preconditioner_pt() [1/2]
SpaceTimeNavierStokesSubsidiaryPreconditioner* oomph::GMRESBlockPreconditioner::navier_stokes_subsidiary_preconditioner_pt () const [inline]
Handle to the Navier-Stokes subsidiary block preconditioner DRAIG: Make sure the desired const-ness is correct later...
Definition at line 422 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
References Navier_stokes_subsidiary_preconditioner_pt.
Referenced by oomph::BandedBlockTriangularPreconditioner< MATRIX >::setup().
navier_stokes_subsidiary_preconditioner_pt() [2/2]
SpaceTimeNavierStokesSubsidiaryPreconditioner* oomph::GMRESBlockPreconditioner::navier_stokes_subsidiary_preconditioner_pt () const [inline]
Handle to the Navier-Stokes subsidiary block preconditioner DRAIG: Make sure the desired const-ness is correct later...
Definition at line 429 of file spacetime_navier_stokes_block_preconditioner.h.
References Navier_stokes_subsidiary_preconditioner_pt.
operator=() [1/2]
void oomph::GMRESBlockPreconditioner::operator= (const GMRESBlockPreconditioner &) [inline]
Broken assignment operator.
Definition at line 305 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
References oomph::BrokenCopy::broken_assign().
operator=() [2/2]
void oomph::GMRESBlockPreconditioner::operator= (const GMRESBlockPreconditioner &) [inline]
Broken assignment operator.
Definition at line 312 of file spacetime_navier_stokes_block_preconditioner.h.
References oomph::BrokenCopy::broken_assign().
preconditioner_solve() [1/2]
void oomph::GMRESBlockPreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) [virtual]
Apply preconditioner to r.
Preconditioner solve for the GMRES block preconditioner.
Implements oomph::Preconditioner.
Definition at line 729 of file general_purpose_space_time_subsidiary_block_preconditioner.cc.
References apply_plane_rotation(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::IterativeLinearSolver::Doc_convergence_history, oomph::LinearSolver::Doc_time, oomph::DoubleVector::dot(), generate_plane_rotation(), oomph::BlockPreconditioner< CRDoubleMatrix >::get_block_vector(), oomph::BlockPreconditioner< CRDoubleMatrix >::get_block_vectors(), i, oomph::Vector< _Tp >::initialise(), Iterations, Matrix_pt, oomph::IterativeLinearSolver::Max_iter, oomph::CRDoubleMatrix::multiply(), Navier_stokes_subsidiary_preconditioner_pt, oomph::BlockPreconditioner< CRDoubleMatrix >::nblock_types(), oomph::DoubleVector::norm(), oomph::oomph_info, oomph::IterativeLinearSolver::Output_file_stream, Preconditioner_LHS, oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::preconditioner_solve(), oomph::DoubleMatrixBase::residual(), oomph::BlockPreconditioner< CRDoubleMatrix >::return_block_vector(), s, oomph::IterativeLinearSolver::Solution_time, oomph::IterativeLinearSolver::Throw_error_after_max_iter, oomph::TimingHelpers::timer(), oomph::IterativeLinearSolver::Tolerance, update(), and oomph::DoubleVector::values_pt().
preconditioner_solve() [2/2]
void oomph::GMRESBlockPreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) [virtual]
Apply preconditioner to r.
Implements oomph::Preconditioner.
set_preconditioner_LHS() [1/2]
void oomph::GMRESBlockPreconditioner::set_preconditioner_LHS () [inline]
Set left preconditioning (the default)
Definition at line 339 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
References Preconditioner_LHS.
set_preconditioner_LHS() [2/2]
void oomph::GMRESBlockPreconditioner::set_preconditioner_LHS () [inline]
Set left preconditioning (the default)
Definition at line 346 of file spacetime_navier_stokes_block_preconditioner.h.
References Preconditioner_LHS.
set_preconditioner_RHS() [1/2]
void oomph::GMRESBlockPreconditioner::set_preconditioner_RHS () [inline]
Enable right preconditioning.
Definition at line 345 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
References Preconditioner_LHS.
set_preconditioner_RHS() [2/2]
void oomph::GMRESBlockPreconditioner::set_preconditioner_RHS () [inline]
Enable right preconditioning.
Definition at line 352 of file spacetime_navier_stokes_block_preconditioner.h.
References Preconditioner_LHS.
setup() [1/8]
void oomph::GMRESBlockPreconditioner::setup () [virtual]
Setup the preconditioner.
Setup for the GMRES block preconditioner.
Implements oomph::Preconditioner.
Definition at line 575 of file general_purpose_space_time_subsidiary_block_preconditioner.cc.
References oomph::BlockPreconditioner< CRDoubleMatrix >::block_setup(), clean_up_memory(), Compute_memory_statistics, oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::enable_doc_memory_usage(), oomph::BlockPreconditioner< CRDoubleMatrix >::get_block(), i, oomph::BlockPreconditioner< CRDoubleMatrix >::is_subsidiary_block_preconditioner(), oomph::BlockPreconditioner< CRDoubleMatrix >::matrix_pt(), Matrix_pt, Memory_usage_in_bytes, Navier_stokes_subsidiary_preconditioner_pt, oomph::BlockPreconditioner< CRDoubleMatrix >::nblock_types(), oomph::BlockPreconditioner< CRDoubleMatrix >::ndof_types(), oomph::CRDoubleMatrix::nnz(), oomph::CRDoubleMatrix::nrow(), oomph::oomph_info, oomph::oomph_nullstream, Preconditioner_has_been_setup, oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::setup(), oomph::Preconditioner::Silent_preconditioner_setup, oomph::Preconditioner::Stream_pt, oomph::OomphInfo::stream_pt(), oomph::TimingHelpers::timer(), and oomph::BlockPreconditioner< MATRIX >::turn_into_subsidiary_block_preconditioner().
setup() [2/8]
void oomph::GMRESBlockPreconditioner::setup () [virtual]
Setup the preconditioner.
Implements oomph::Preconditioner.
setup() [3/8]
virtual void oomph::Preconditioner::setup
For some reason we need to remind the compiler that there is also a function named setup in the base class.
setup() [4/8]
virtual void oomph::Preconditioner::setup
For some reason we need to remind the compiler that there is also a function named setup in the base class.
setup() [5/8]
void oomph::Preconditioner::setup [inline]
For some reason we need to remind the compiler that there is also a function named setup in the base class.
Definition at line 126 of file preconditioner.h.
setup() [6/8]
void oomph::Preconditioner::setup [inline]
For some reason we need to remind the compiler that there is also a function named setup in the base class.
Definition at line 126 of file preconditioner.h.
setup() [7/8]
void oomph::Preconditioner::setup [inline]
For some reason we need to remind the compiler that there is also a function named setup in the base class.
Definition at line 100 of file preconditioner.h.
setup() [8/8]
void oomph::Preconditioner::setup [inline]
For some reason we need to remind the compiler that there is also a function named setup in the base class.
Definition at line 100 of file preconditioner.h.
solve() [1/2]
void oomph::GMRESBlockPreconditioner::solve (Problem *const & problem_pt, DoubleVector & result) [inline], [virtual]
Solver: Takes pointer to problem and returns the results vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual vector.
Implements oomph::LinearSolver.
Definition at line 323 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
solve() [2/2]
void oomph::GMRESBlockPreconditioner::solve (Problem *const & problem_pt, DoubleVector & result) [inline], [virtual]
Solver: Takes pointer to problem and returns the results vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual vector.
Implements oomph::LinearSolver.
Definition at line 330 of file spacetime_navier_stokes_block_preconditioner.h.
update() [1/2]
void oomph::GMRESBlockPreconditioner::update (const unsigned & k, const Vector< Vector< double >> & H, const Vector< double > & s, const Vector< DoubleVector > & v, const DoubleVector & block_x_with_size_of_full_x, DoubleVector & x) [inline], [private]
Helper function to update the result vector using the result, x=x_0+V_m*y
Definition at line 432 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
References oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::BlockPreconditioner< CRDoubleMatrix >::get_block_vector(), i, Navier_stokes_subsidiary_preconditioner_pt, oomph::DistributableLinearAlgebraObject::nrow(), Preconditioner_LHS, oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::preconditioner_solve(), oomph::BlockPreconditioner< CRDoubleMatrix >::return_block_vector(), s, and oomph::DoubleVector::values_pt().
Referenced by preconditioner_solve().
update() [2/2]
void oomph::GMRESBlockPreconditioner::update (const unsigned & k, const Vector< Vector< double >> & H, const Vector< double > & s, const Vector< DoubleVector > & v, const DoubleVector & block_x_with_size_of_full_x, DoubleVector & x) [inline], [private]
Helper function to update the result vector using the result, x=x_0+V_m*y
Definition at line 439 of file spacetime_navier_stokes_block_preconditioner.h.
References oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::BlockPreconditioner< CRDoubleMatrix >::get_block_vector(), i, Navier_stokes_subsidiary_preconditioner_pt, oomph::DistributableLinearAlgebraObject::nrow(), Preconditioner_LHS, oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::preconditioner_solve(), oomph::BlockPreconditioner< CRDoubleMatrix >::return_block_vector(), s, and oomph::DoubleVector::values_pt().
Member Data Documentation
Compute_memory_statistics
bool oomph::GMRESBlockPreconditioner::Compute_memory_statistics [private]
Flag to indicate whether or not to record the memory statistics this preconditioner.
Definition at line 630 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
Referenced by disable_doc_memory_statistics(), disable_doc_memory_usage(), enable_doc_memory_statistics(), enable_doc_memory_usage(), get_memory_usage_in_bytes(), GMRESBlockPreconditioner(), and setup().
Iterations
unsigned oomph::GMRESBlockPreconditioner::Iterations [private]
Number of iterations taken.
Definition at line 626 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
Referenced by iterations(), and preconditioner_solve().
Matrix_pt
CRDoubleMatrix * oomph::GMRESBlockPreconditioner::Matrix_pt [private]
Pointer to matrix.
Definition at line 619 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
Referenced by clean_up_memory(), preconditioner_solve(), and setup().
Memory_usage_in_bytes
double oomph::GMRESBlockPreconditioner::Memory_usage_in_bytes [private]
Storage for the memory usage of the solver if the flag above is set to true (in bytes)
Definition at line 634 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
Referenced by get_memory_usage_in_bytes(), GMRESBlockPreconditioner(), and setup().
Navier_stokes_subsidiary_preconditioner_pt
SpaceTimeNavierStokesSubsidiaryPreconditioner * oomph::GMRESBlockPreconditioner::Navier_stokes_subsidiary_preconditioner_pt [private]
Pointer to the preconditioner for the block matrix.
Definition at line 623 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
Referenced by clean_up_memory(), navier_stokes_subsidiary_preconditioner_pt(), preconditioner_solve(), setup(), and update().
Preconditioner_has_been_setup
bool oomph::GMRESBlockPreconditioner::Preconditioner_has_been_setup [private]
Control flag is true if the preconditioner has been setup (used so we can wipe the data when the preconditioner is called again)
Definition at line 638 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
Referenced by clean_up_memory(), get_memory_usage_in_bytes(), and setup().
Preconditioner_LHS
bool oomph::GMRESBlockPreconditioner::Preconditioner_LHS [private]
boolean indicating use of left hand preconditioning (if true) or right hand preconditioning (if false)
Definition at line 642 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
Referenced by preconditioner_solve(), set_preconditioner_LHS(), set_preconditioner_RHS(), and update().
The documentation for this class was generated from the following files:
general_purpose_space_time_subsidiary_block_preconditioner.h
spacetime_navier_stokes_block_preconditioner.h
general_purpose_space_time_subsidiary_block_preconditioner.cc
spacetime_navier_stokes_block_preconditioner.cc