oomph::BiharmonicPreconditioner Class Reference
Biharmonic Preconditioner - for two dimensional problems.
#include <biharmonic_preconditioner.h>
Public Member Functions
BiharmonicPreconditioner ()
Constructor - by default inexact preconditioning is used.
~BiharmonicPreconditioner ()
destructor - cleans up preconditioners and delete matrices
void clean_up_memory ()
Clean up memory (empty). Generic interface function.
BiharmonicPreconditioner (const BiharmonicPreconditioner &)
Broken copy constructor.
void operator= (const BiharmonicPreconditioner &)
Broken assignment operator.
void setup ()
Setup the preconditioner.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply preconditioner to r.
unsigned & preconditioner_type ()
Access function to the preconditioner type
.
Mesh *& bulk_element_mesh_pt ()
Access function to the mesh pt for the bulk elements. The mesh should only contain BiharmonicElement<2> and Hijacked<BiharmonicElement<2> > elements.
Private Attributes
unsigned Preconditioner_type
Preconditioner * Sub_preconditioner_1_pt
Exact Preconditioner Pointer.
Preconditioner * Sub_preconditioner_2_pt
Inexact Preconditioner Pointer.
Preconditioner * Hijacked_sub_block_preconditioner_pt
Preconditioner the diagonal block associated with hijacked elements.
Mesh * Bulk_element_mesh_pt
the bulk element mesh pt
Additional Inherited Members
Detailed Description
Biharmonic Preconditioner - for two dimensional problems.
Definition at line 87 of file biharmonic_preconditioner.h.
Constructor & Destructor Documentation
BiharmonicPreconditioner() [1/2]
oomph::BiharmonicPreconditioner::BiharmonicPreconditioner () [inline]
Constructor - by default inexact preconditioning is used.
Definition at line 91 of file biharmonic_preconditioner.h.
References Bulk_element_mesh_pt, Hijacked_sub_block_preconditioner_pt, Preconditioner_type, oomph::BlockPreconditioner< CRDoubleMatrix >::set_nmesh(), Sub_preconditioner_1_pt, and Sub_preconditioner_2_pt.
 BiharmonicPreconditioner()
oomph::BiharmonicPreconditioner::~BiharmonicPreconditioner () [inline]
destructor - cleans up preconditioners and delete matrices
Definition at line 112 of file biharmonic_preconditioner.h.
References clean_up_memory().
BiharmonicPreconditioner() [2/2]
oomph::BiharmonicPreconditioner::BiharmonicPreconditioner (const BiharmonicPreconditioner &) [inline]
Broken copy constructor.
Definition at line 127 of file biharmonic_preconditioner.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
bulk_element_mesh_pt()
Mesh*& oomph::BiharmonicPreconditioner::bulk_element_mesh_pt () [inline]
Access function to the mesh pt for the bulk elements. The mesh should only contain BiharmonicElement<2> and Hijacked<BiharmonicElement<2> > elements.
Definition at line 157 of file biharmonic_preconditioner.h.
References Bulk_element_mesh_pt.
clean_up_memory()
void oomph::BiharmonicPreconditioner::clean_up_memory () [inline], [virtual]
Clean up memory (empty). Generic interface function.
Reimplemented from oomph::Preconditioner.
Definition at line 118 of file biharmonic_preconditioner.h.
References Hijacked_sub_block_preconditioner_pt, Sub_preconditioner_1_pt, and Sub_preconditioner_2_pt.
Referenced by setup(), and ~BiharmonicPreconditioner().
operator=()
void oomph::BiharmonicPreconditioner::operator= (const BiharmonicPreconditioner &) [inline]
Broken assignment operator.
Definition at line 133 of file biharmonic_preconditioner.h.
References oomph::BrokenCopy::broken_assign().
preconditioner_solve()
void oomph::BiharmonicPreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) [virtual]
Apply preconditioner to r.
preconditioner solve for the biharmonic preconditioner
Implements oomph::Preconditioner.
Definition at line 243 of file biharmonic_preconditioner.cc.
References oomph::DoubleVector::clear(), oomph::BlockPreconditioner< CRDoubleMatrix >::get_block_vector(), Hijacked_sub_block_preconditioner_pt, oomph::DoubleVector::initialise(), oomph::BlockPreconditioner< CRDoubleMatrix >::nblock_types(), oomph::Preconditioner::preconditioner_solve(), oomph::BlockPreconditioner< CRDoubleMatrix >::return_block_vector(), Sub_preconditioner_1_pt, and Sub_preconditioner_2_pt.
preconditioner_type()
unsigned& oomph::BiharmonicPreconditioner::preconditioner_type () [inline]
Access function to the preconditioner type
.
0 : exact BBD
1 : inexact BBD w/ SuperLU
2 : inexact BBD w/ AMG (Hypre Boomer AMG)
3 : block diagonal (3x3)+(1x1)
Definition at line 149 of file biharmonic_preconditioner.h.
References Preconditioner_type.
setup()
void oomph::BiharmonicPreconditioner::setup () [virtual]
Setup the preconditioner.
setup for the biharmonic preconditioner Exact BD
Implements oomph::Preconditioner.
Definition at line 107 of file biharmonic_preconditioner.cc.
References oomph::BlockPreconditioner< CRDoubleMatrix >::block_setup(), Bulk_element_mesh_pt, clean_up_memory(), oomph::BlockPreconditioner< CRDoubleMatrix >::get_block(), Hijacked_sub_block_preconditioner_pt, oomph::BlockPreconditioner< CRDoubleMatrix >::matrix_pt(), oomph::BlockPreconditioner< CRDoubleMatrix >::nblock_types(), oomph::oomph_info, Preconditioner_type, oomph::BlockPreconditioner< CRDoubleMatrix >::set_mesh(), oomph::Preconditioner::setup(), Sub_preconditioner_1_pt, and Sub_preconditioner_2_pt.
Member Data Documentation
Bulk_element_mesh_pt
Mesh* oomph::BiharmonicPreconditioner::Bulk_element_mesh_pt [private]
the bulk element mesh pt
Definition at line 180 of file biharmonic_preconditioner.h.
Referenced by BiharmonicPreconditioner(), bulk_element_mesh_pt(), and setup().
Hijacked_sub_block_preconditioner_pt
Preconditioner* oomph::BiharmonicPreconditioner::Hijacked_sub_block_preconditioner_pt [private]
Preconditioner the diagonal block associated with hijacked elements.
Definition at line 177 of file biharmonic_preconditioner.h.
Referenced by BiharmonicPreconditioner(), clean_up_memory(), preconditioner_solve(), and setup().
Preconditioner_type
unsigned oomph::BiharmonicPreconditioner::Preconditioner_type [private]
preconditioner type
0 : exact BBD
1 : inexact BBD w/ SuperLU
2 : inexact BBD w/ AMG
3 : block diagonal (3x3)+(1x1)
Definition at line 168 of file biharmonic_preconditioner.h.
Referenced by BiharmonicPreconditioner(), preconditioner_type(), and setup().
Sub_preconditioner_1_pt
Preconditioner* oomph::BiharmonicPreconditioner::Sub_preconditioner_1_pt [private]
Exact Preconditioner Pointer.
Definition at line 171 of file biharmonic_preconditioner.h.
Referenced by BiharmonicPreconditioner(), clean_up_memory(), preconditioner_solve(), and setup().
Sub_preconditioner_2_pt
Preconditioner* oomph::BiharmonicPreconditioner::Sub_preconditioner_2_pt [private]
Inexact Preconditioner Pointer.
Definition at line 174 of file biharmonic_preconditioner.h.
Referenced by BiharmonicPreconditioner(), clean_up_memory(), preconditioner_solve(), and setup().
The documentation for this class was generated from the following files:
biharmonic_preconditioner.h
biharmonic_preconditioner.cc