oomph::NetFluxControlElement Class Reference
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
#include <navier_stokes_flux_control_elements.h>
Public Member Functions
NetFluxControlElement (Mesh *flux_control_mesh_pt, double *prescribed_flux_value_pt)
Constructor takes a mesh of TemplateFreeNavierStokesFluxControlElementBase elements that impose the pressure to control the flux, plus a pointer to the double which contains the desired flux value.
~NetFluxControlElement ()
Empty Destructor - Data gets deleted automatically.
NetFluxControlElement (const NetFluxControlElement &dummy)=delete
Broken copy constructor.
unsigned dim () const
Broken assignment operator.
Data * pressure_data_pt () const
Function to return a pointer to the Data object whose single value is the pressure applied by the NavierStokesFluxControlElement elements.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector: i.e. the flux constraint.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals, but adds nothing to the Jacobian as this element's Jacobian contributions are calculated by the NavierStokesFluxControlElements which impose the traction used to control the flux.
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into - it's set to Dof_number_for_unknown+1 because it's expected this element is added to a fluid mesh containing navier stokes elements.
unsigned & dof_number_for_unknown ()
Function to set / get the nodal value of the `DOF type` to which the degree of freedom in this element (the pressure that enforces the required volume flux!) is added to. This should be set to the Navier-Stokes pressure DOF type (usually the dimension of the problem, for example, in 3D, the DOF types for single-physics Navier-Stokes elements are usually labelled 0, 1, 2, 3 for u, v and w velocities and pressure respectively. It is important to note that this is dimension dependent, so should not be hard coded in!! In particularly, this should not simply be set to the dimension of the problem if there is further splitting of the velocity DOF types) if this element is added to a fluid mesh containing Navier-Stokes elements.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) The single degree of freedom is given the DOF type number of Dof_number_for_unknown since it's expected this unknown is added to the Navier-Stokes pressure DOF block (it is also assumed that the user has set the Dof_number_for_unknown variable to the velocity DOF type using the function dof_number_for_unknown()).
Protected Member Functions
void fill_in_generic_residual_contribution_flux_control (Vector< double > &residuals)
This function returns the residuals for the flux control master element.
Private Attributes
Data * Pressure_data_pt
Data object whose single value is the pressure applied by the elements in the Flux_control_mesh_pt.
Mesh * Flux_control_mesh_pt
Mesh of elements which impose the pressure which controls the net flux.
double * Prescribed_flux_value_pt
Pointer to the value that stores the prescribed flux.
unsigned Dof_number_for_unknown
The id number of the `DOF type` to which the degree of freedom in this element is added to. This should be set to the number id of the Navier-Stokes pressure DOF block (which is dimension dependent!) if this element is added to a fluid mesh containing navier stokes elements.
unsigned Dim
spatial dim of NS system
Additional Inherited Members
Detailed Description
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
A class for an element that controls the net fluid flux across a boundary by the imposition of an unknown applied pressure to the Navier-Stokes equations. This element is used with a mesh of NavierStokesFluxControlElement elements which are attached to the boundary. Note: fill_in_contribution_to_jacobian() does not calculate Jacobian contributions for this element as they are calculated by NavierStokesFluxControlElement::fill_in_contribution_to_jacobian(...)
Definition at line 103 of file navier_stokes_flux_control_elements.h.
Constructor & Destructor Documentation
NetFluxControlElement() [1/2]
oomph::NetFluxControlElement::NetFluxControlElement (Mesh * flux_control_mesh_pt, double * prescribed_flux_value_pt) [inline]
Constructor takes a mesh of TemplateFreeNavierStokesFluxControlElementBase elements that impose the pressure to control the flux, plus a pointer to the double which contains the desired flux value.
Definition at line 110 of file navier_stokes_flux_control_elements.h.
References oomph::GeneralisedElement::add_internal_data(), oomph::TemplateFreeNavierStokesFluxControlElementBase::add_pressure_data(), Dof_number_for_unknown, e, oomph::Mesh::element_pt(), Flux_control_mesh_pt, oomph::Mesh::nelement(), and Pressure_data_pt.
 NetFluxControlElement()
oomph::NetFluxControlElement::~NetFluxControlElement () [inline]
Empty Destructor - Data gets deleted automatically.
Definition at line 148 of file navier_stokes_flux_control_elements.h.
NetFluxControlElement() [2/2]
oomph::NetFluxControlElement::NetFluxControlElement (const NetFluxControlElement & dummy) [delete]
Broken copy constructor.
Member Function Documentation
dim()
unsigned oomph::NetFluxControlElement::dim () const [inline]
Broken assignment operator.
Spatial dimension of the problem
Definition at line 162 of file navier_stokes_flux_control_elements.h.
References Dim.
dof_number_for_unknown()
unsigned& oomph::NetFluxControlElement::dof_number_for_unknown () [inline]
Function to set / get the nodal value of the `DOF type` to which the degree of freedom in this element (the pressure that enforces the required volume flux!) is added to. This should be set to the Navier-Stokes pressure DOF type (usually the dimension of the problem, for example, in 3D, the DOF types for single-physics Navier-Stokes elements are usually labelled 0, 1, 2, 3 for u, v and w velocities and pressure respectively. It is important to note that this is dimension dependent, so should not be hard coded in!! In particularly, this should not simply be set to the dimension of the problem if there is further splitting of the velocity DOF types) if this element is added to a fluid mesh containing Navier-Stokes elements.
Definition at line 229 of file navier_stokes_flux_control_elements.h.
References Dof_number_for_unknown.
fill_in_contribution_to_jacobian()
void oomph::NetFluxControlElement::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
This function returns the residuals, but adds nothing to the Jacobian as this element's Jacobian contributions are calculated by the NavierStokesFluxControlElements which impose the traction used to control the flux.
Reimplemented from oomph::GeneralisedElement.
Definition at line 188 of file navier_stokes_flux_control_elements.h.
References fill_in_generic_residual_contribution_flux_control().
fill_in_contribution_to_residuals()
void oomph::NetFluxControlElement::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector: i.e. the flux constraint.
Reimplemented from oomph::GeneralisedElement.
Definition at line 178 of file navier_stokes_flux_control_elements.h.
References fill_in_generic_residual_contribution_flux_control().
fill_in_generic_residual_contribution_flux_control()
void oomph::NetFluxControlElement::fill_in_generic_residual_contribution_flux_control (Vector< double > & residuals) [inline], [protected]
This function returns the residuals for the flux control master element.
Definition at line 273 of file navier_stokes_flux_control_elements.h.
References e, oomph::Mesh::element_pt(), Flux_control_mesh_pt, oomph::TemplateFreeNavierStokesFluxControlElementBase::get_volume_flux(), oomph::Mesh::nelement(), and Prescribed_flux_value_pt.
Referenced by fill_in_contribution_to_jacobian(), and fill_in_contribution_to_residuals().
get_dof_numbers_for_unknowns()
void oomph::NetFluxControlElement::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> & dof_lookup_list) const [inline], [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) The single degree of freedom is given the DOF type number of Dof_number_for_unknown since it's expected this unknown is added to the Navier-Stokes pressure DOF block (it is also assumed that the user has set the Dof_number_for_unknown variable to the velocity DOF type using the function dof_number_for_unknown()).
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::NetFluxControlElementForWomersleyPressureControl.
Definition at line 244 of file navier_stokes_flux_control_elements.h.
References Dof_number_for_unknown, and oomph::GeneralisedElement::eqn_number().
ndof_types()
unsigned oomph::NetFluxControlElement::ndof_types () const [inline], [virtual]
The number of `DOF types` that degrees of freedom in this element are sub-divided into - it's set to Dof_number_for_unknown+1 because it's expected this element is added to a fluid mesh containing navier stokes elements.
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::NetFluxControlElementForWomersleyPressureControl.
Definition at line 200 of file navier_stokes_flux_control_elements.h.
References Dof_number_for_unknown.
pressure_data_pt()
Data* oomph::NetFluxControlElement::pressure_data_pt () const [inline]
Function to return a pointer to the Data object whose single value is the pressure applied by the NavierStokesFluxControlElement elements.
Definition at line 170 of file navier_stokes_flux_control_elements.h.
References Pressure_data_pt.
Referenced by oomph::NetFluxControlElementForWomersleyPressureControl::NetFluxControlElementForWomersleyPressureControl().
Member Data Documentation
Dim
unsigned oomph::NetFluxControlElement::Dim [private]
spatial dim of NS system
Definition at line 329 of file navier_stokes_flux_control_elements.h.
Referenced by dim().
Dof_number_for_unknown
unsigned oomph::NetFluxControlElement::Dof_number_for_unknown [private]
The id number of the `DOF type` to which the degree of freedom in this element is added to. This should be set to the number id of the Navier-Stokes pressure DOF block (which is dimension dependent!) if this element is added to a fluid mesh containing navier stokes elements.
Definition at line 326 of file navier_stokes_flux_control_elements.h.
Referenced by dof_number_for_unknown(), get_dof_numbers_for_unknowns(), ndof_types(), and NetFluxControlElement().
Flux_control_mesh_pt
Mesh* oomph::NetFluxControlElement::Flux_control_mesh_pt [private]
Mesh of elements which impose the pressure which controls the net flux.
Definition at line 316 of file navier_stokes_flux_control_elements.h.
Referenced by fill_in_generic_residual_contribution_flux_control(), and NetFluxControlElement().
Prescribed_flux_value_pt
double* oomph::NetFluxControlElement::Prescribed_flux_value_pt [private]
Pointer to the value that stores the prescribed flux.
Definition at line 319 of file navier_stokes_flux_control_elements.h.
Referenced by fill_in_generic_residual_contribution_flux_control().
Pressure_data_pt
Data* oomph::NetFluxControlElement::Pressure_data_pt [private]
Data object whose single value is the pressure applied by the elements in the Flux_control_mesh_pt.
Definition at line 312 of file navier_stokes_flux_control_elements.h.
Referenced by NetFluxControlElement(), and pressure_data_pt().
The documentation for this class was generated from the following file:
navier_stokes_flux_control_elements.h