Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector > Class Reference
Specialize the Anasazi traits class for the oomph-lib DoubleMultiVector. This provides the interfaces required by the Anasazi eigensolvers.
#include <trilinos_eigen_solver.h>
Static Public Member Functions
static Teuchos::RCP< oomph::DoubleMultiVector > Clone (const oomph::DoubleMultiVector &mv, const int numvecs)
Creates a new empty DoubleMultiVector containing numvecs columns. Return a reference-counted pointer to the new multivector.
static Teuchos::RCP< oomph::DoubleMultiVector > CloneCopy (const oomph::DoubleMultiVector &mv)
Creates a deep copy of the DoubleMultiVector mv return Reference-counted pointer to the new DoubleMultiVector.
static Teuchos::RCP< oomph::DoubleMultiVector > CloneCopy (const oomph::DoubleMultiVector &mv, const std::vector< int > &index)
Creates a new oomph::DoubleMultiVector and (deep) copies the contents of the vectors in index into the new vector return Reference-counted pointer to the new oomph::DoubleMultiVector.
static Teuchos::RCP< oomph::DoubleMultiVector > CloneCopy (const oomph::DoubleMultiVector &mv, const Teuchos::Range1D &index)
Deep copy of specified columns of oomph::DoubleMultiVector return Reference-counted pointer to the new oomph::DoubleMultiVector.
static Teuchos::RCP< oomph::DoubleMultiVector > CloneViewNonConst (oomph::DoubleMultiVector &mv, const std::vector< int > &index)
Creates a new oomph::DoubleMultiVector that contains shallow copies of selected entries of the oomph::DoubleMultiVector mv return Reference-counted pointer to the new oomph::DoubleMultiVector.
static Teuchos::RCP< oomph::DoubleMultiVector > CloneViewNonConst (oomph::DoubleMultiVector &mv, const Teuchos::Range1D &index)
Creates a new oomph::DoubleMultiVector that contains shallow copies of selected entries of the oomph::DoubleMultiVector mv return Reference-counted pointer to the new oomph::DoubleMultiVector.
static Teuchos::RCP< const oomph::DoubleMultiVector > CloneView (const oomph::DoubleMultiVector &mv, const std::vector< int > &index)
Creates a new oomph::DoubleMultiVector that contains shallow copies of selected entries of the oomph::DoubleMultiVector mv return Reference-counted pointer to the new oomph::DoubleMultiVector (const version)
static Teuchos::RCP< oomph::DoubleMultiVector > CloneView (oomph::DoubleMultiVector &mv, const std::vector< int > &index)
Creates a new oomph::DoubleMultiVector that contains shallow copies of selected entries of the oomph::DoubleMultiVector mv return Reference-counted pointer to the new oomph::DoubleMultiVector (Non-const version for Trilinos 9 interface)
static Teuchos::RCP< oomph::DoubleMultiVector > CloneView (oomph::DoubleMultiVector &mv, const Teuchos::Range1D &index)
Creates a new oomph::DoubleMultiVector that contains shallow copies of selected entries of the oomph::DoubleMultiVector mv return Reference-counted pointer to the new oomph::DoubleMultiVector (const version)
static int GetVecLength (const oomph::DoubleMultiVector &mv)
Obtain the global length of the vector.
static int GetNumberVecs (const oomph::DoubleMultiVector &mv)
Obtain the number of vectors in the multivector.
static void MvTimesMatAddMv (const double alpha, const oomph::DoubleMultiVector &A, const Teuchos::SerialDenseMatrix< int, double > &B, const double beta, oomph::DoubleMultiVector &mv)
Update mv with $ \alpha AB + \beta mv $.
static void MvAddMv (const double alpha, const oomph::DoubleMultiVector &A, const double beta, const oomph::DoubleMultiVector &B, oomph::DoubleMultiVector &mv)
Replace mv with $\alpha A + \beta B$.
static void MvScale (oomph::DoubleMultiVector &mv, const double alpha)
Scale each element of the vectors in mv with alpha.
static void MvScale (oomph::DoubleMultiVector &mv, const std::vector< double > &alpha)
Scale each element of the i-th vector in mv with alpha[i].
static void MvTransMv (const double alpha, const oomph::DoubleMultiVector &A, const oomph::DoubleMultiVector &mv, Teuchos::SerialDenseMatrix< int, double > &B)
Compute a dense matrix B through the matrix-matrix multiply $ \alpha A^Hmv $.
static void MvDot (const oomph::DoubleMultiVector &mv, const oomph::DoubleMultiVector &A, std::vector< double > &b)
Compute a vector b where the components are the individual dot-products of the i-th columns of A and mv, i.e. $b[i] = A[i]^Hmv[i]$.
static void MvNorm (const oomph::DoubleMultiVector &mv, std::vector< double > &normvec)
Compute the 2-norm of each individual vector of mv. Upon return, normvec[i] holds the value of $||mv_i||_2$, the i-th column of mv.
 Initialization methods
static void SetBlock (const oomph::DoubleMultiVector &A, const std::vector< int > &index, oomph::DoubleMultiVector &mv)
Copy the vectors in A to a set of vectors in mv indicated by the indices given in index.
static void SetBlock (const oomph::DoubleMultiVector &A, const Teuchos::Range1D &index, oomph::DoubleMultiVector &mv)
Deep copy of A into specified columns of mv.
static void Assign (const oomph::DoubleMultiVector &A, oomph::DoubleMultiVector &mv)
mv := A
static void MvRandom (oomph::DoubleMultiVector &mv)
Replace the vectors in mv with random vectors.
static void MvInit (oomph::DoubleMultiVector &mv, const double alpha=Teuchos::ScalarTraits< double >::zero())
Replace each element of the vectors in mv with alpha.
 Print method
static void MvPrint (const oomph::DoubleMultiVector &mv, std::ostream &os)
Print the mv multi-vector to the os output stream.
Detailed Description
Specialize the Anasazi traits class for the oomph-lib DoubleMultiVector. This provides the interfaces required by the Anasazi eigensolvers.
Definition at line 51 of file trilinos_eigen_solver.h.
Member Function Documentation
Assign()
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::Assign (const oomph::DoubleMultiVector & A, oomph::DoubleMultiVector & mv) [inline], [static]
mv := A
Assign (deep copy) A into mv.
Definition at line 388 of file trilinos_eigen_solver.h.
Clone()
static Teuchos::RCP< oomph::DoubleMultiVector > Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::Clone (const oomph::DoubleMultiVector & mv, const int numvecs) [inline], [static]
Creates a new empty DoubleMultiVector containing numvecs columns. Return a reference-counted pointer to the new multivector.
Definition at line 56 of file trilinos_eigen_solver.h.
CloneCopy() [1/3]
static Teuchos::RCP< oomph::DoubleMultiVector > Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::CloneCopy (const oomph::DoubleMultiVector & mv) [inline], [static]
Creates a deep copy of the DoubleMultiVector mv return Reference-counted pointer to the new DoubleMultiVector.
Definition at line 64 of file trilinos_eigen_solver.h.
CloneCopy() [2/3]
static Teuchos::RCP< oomph::DoubleMultiVector > Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::CloneCopy (const oomph::DoubleMultiVector & mv, const std::vector< int > & index) [inline], [static]
Creates a new oomph::DoubleMultiVector and (deep) copies the contents of the vectors in index into the new vector return Reference-counted pointer to the new oomph::DoubleMultiVector.
Definition at line 74 of file trilinos_eigen_solver.h.
CloneCopy() [3/3]
static Teuchos::RCP< oomph::DoubleMultiVector > Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::CloneCopy (const oomph::DoubleMultiVector & mv, const Teuchos::Range1D & index) [inline], [static]
Deep copy of specified columns of oomph::DoubleMultiVector return Reference-counted pointer to the new oomph::DoubleMultiVector.
Definition at line 82 of file trilinos_eigen_solver.h.
CloneView() [1/3]
static Teuchos::RCP< const oomph::DoubleMultiVector > Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::CloneView (const oomph::DoubleMultiVector & mv, const std::vector< int > & index) [inline], [static]
Creates a new oomph::DoubleMultiVector that contains shallow copies of selected entries of the oomph::DoubleMultiVector mv return Reference-counted pointer to the new oomph::DoubleMultiVector (const version)
Definition at line 113 of file trilinos_eigen_solver.h.
CloneView() [2/3]
static Teuchos::RCP< oomph::DoubleMultiVector > Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::CloneView (oomph::DoubleMultiVector & mv, const std::vector< int > & index) [inline], [static]
Creates a new oomph::DoubleMultiVector that contains shallow copies of selected entries of the oomph::DoubleMultiVector mv return Reference-counted pointer to the new oomph::DoubleMultiVector (Non-const version for Trilinos 9 interface)
Definition at line 124 of file trilinos_eigen_solver.h.
CloneView() [3/3]
static Teuchos::RCP< oomph::DoubleMultiVector > Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::CloneView (oomph::DoubleMultiVector & mv, const Teuchos::Range1D & index) [inline], [static]
Creates a new oomph::DoubleMultiVector that contains shallow copies of selected entries of the oomph::DoubleMultiVector mv return Reference-counted pointer to the new oomph::DoubleMultiVector (const version)
Definition at line 135 of file trilinos_eigen_solver.h.
CloneViewNonConst() [1/2]
static Teuchos::RCP< oomph::DoubleMultiVector > Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::CloneViewNonConst (oomph::DoubleMultiVector & mv, const std::vector< int > & index) [inline], [static]
Creates a new oomph::DoubleMultiVector that contains shallow copies of selected entries of the oomph::DoubleMultiVector mv return Reference-counted pointer to the new oomph::DoubleMultiVector.
Definition at line 92 of file trilinos_eigen_solver.h.
CloneViewNonConst() [2/2]
static Teuchos::RCP< oomph::DoubleMultiVector > Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::CloneViewNonConst (oomph::DoubleMultiVector & mv, const Teuchos::Range1D & index) [inline], [static]
Creates a new oomph::DoubleMultiVector that contains shallow copies of selected entries of the oomph::DoubleMultiVector mv return Reference-counted pointer to the new oomph::DoubleMultiVector.
Definition at line 102 of file trilinos_eigen_solver.h.
GetNumberVecs()
static int Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::GetNumberVecs (const oomph::DoubleMultiVector & mv) [inline], [static]
Obtain the number of vectors in the multivector.
Definition at line 148 of file trilinos_eigen_solver.h.
References oomph::DoubleMultiVector::nvector().
GetVecLength()
static int Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::GetVecLength (const oomph::DoubleMultiVector & mv) [inline], [static]
Obtain the global length of the vector.
Definition at line 142 of file trilinos_eigen_solver.h.
References oomph::DistributableLinearAlgebraObject::nrow().
MvAddMv()
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvAddMv (const double alpha, const oomph::DoubleMultiVector & A, const double beta, const oomph::DoubleMultiVector & B, oomph::DoubleMultiVector & mv) [inline], [static]
Replace mv with $\alpha A + \beta B$.
Definition at line 189 of file trilinos_eigen_solver.h.
References oomph::OcTreeNames::B, i, oomph::DistributableLinearAlgebraObject::nrow_local(), and oomph::DoubleMultiVector::nvector().
MvDot()
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvDot (const oomph::DoubleMultiVector & mv, const oomph::DoubleMultiVector & A, std::vector< double > & b) [inline], [static]
Compute a vector b where the components are the individual dot-products of the i-th columns of A and mv, i.e. $b[i] = A[i]^Hmv[i]$.
Definition at line 302 of file trilinos_eigen_solver.h.
References oomph::DoubleMultiVector::dot().
MvInit()
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvInit (oomph::DoubleMultiVector & mv, const double alpha = Teuchos::ScalarTraits<double>::zero()) [inline], [static]
Replace each element of the vectors in mv with alpha.
Definition at line 411 of file trilinos_eigen_solver.h.
References oomph::DoubleMultiVector::initialise().
MvNorm()
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvNorm (const oomph::DoubleMultiVector & mv, std::vector< double > & normvec) [inline], [static]
Compute the 2-norm of each individual vector of mv. Upon return, normvec[i] holds the value of $||mv_i||_2$, the i-th column of mv.
Definition at line 314 of file trilinos_eigen_solver.h.
References oomph::DoubleMultiVector::norm().
MvPrint()
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvPrint (const oomph::DoubleMultiVector & mv, std::ostream & os) [inline], [static]
Print the mv multi-vector to the os output stream.
Definition at line 425 of file trilinos_eigen_solver.h.
References oomph::DoubleMultiVector::output().
MvRandom()
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvRandom (oomph::DoubleMultiVector & mv) [inline], [static]
Replace the vectors in mv with random vectors.
Definition at line 396 of file trilinos_eigen_solver.h.
References i, oomph::DistributableLinearAlgebraObject::nrow_local(), and oomph::DoubleMultiVector::nvector().
MvScale() [1/2]
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvScale (oomph::DoubleMultiVector & mv, const double alpha) [inline], [static]
Scale each element of the vectors in mv with alpha.
Definition at line 208 of file trilinos_eigen_solver.h.
MvScale() [2/2]
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvScale (oomph::DoubleMultiVector & mv, const std::vector< double > & alpha) [inline], [static]
Scale each element of the i-th vector in mv with alpha[i].
Definition at line 216 of file trilinos_eigen_solver.h.
References i, oomph::DistributableLinearAlgebraObject::nrow_local(), and oomph::DoubleMultiVector::nvector().
MvTimesMatAddMv()
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvTimesMatAddMv (const double alpha, const oomph::DoubleMultiVector & A, const Teuchos::SerialDenseMatrix< int, double > & B, const double beta, oomph::DoubleMultiVector & mv) [inline], [static]
Update mv with $ \alpha AB + \beta mv $.
Definition at line 154 of file trilinos_eigen_solver.h.
References oomph::OcTreeNames::B, i, oomph::DistributableLinearAlgebraObject::nrow_local(), and oomph::DoubleMultiVector::nvector().
MvTransMv()
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvTransMv (const double alpha, const oomph::DoubleMultiVector & A, const oomph::DoubleMultiVector & mv, Teuchos::SerialDenseMatrix< int, double > & B) [inline], [static]
Compute a dense matrix B through the matrix-matrix multiply $ \alpha A^Hmv $.
Definition at line 233 of file trilinos_eigen_solver.h.
References oomph::OcTreeNames::B, oomph::LinearAlgebraDistribution::communicator_pt(), oomph::DistributableLinearAlgebraObject::distributed(), oomph::DistributableLinearAlgebraObject::distribution_pt(), i, oomph::DistributableLinearAlgebraObject::nrow_local(), and oomph::DoubleMultiVector::nvector().
SetBlock() [1/2]
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::SetBlock (const oomph::DoubleMultiVector & A, const std::vector< int > & index, oomph::DoubleMultiVector & mv) [inline], [static]
Copy the vectors in A to a set of vectors in mv indicated by the indices given in index.
The numvecs vectors in A are copied to a subset of vectors in mv indicated by the indices given in index, i.e.mv[index[i]] = A[i].
Definition at line 331 of file trilinos_eigen_solver.h.
References i, and oomph::DistributableLinearAlgebraObject::nrow_local().
SetBlock() [2/2]
static void Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::SetBlock (const oomph::DoubleMultiVector & A, const Teuchos::Range1D & index, oomph::DoubleMultiVector & mv) [inline], [static]
Deep copy of A into specified columns of mv.
(Deeply) copy the first index.size() columns of A into the columns of mv specified by the given index range.
Postcondition: mv[i] = A[i - index.lbound()] for all i in [index.lbound(), index.ubound()]
Parameters
A [in] Source multivector
index [in] Inclusive index range of columns of mv; index set of the target
mv [out] Target multivector
Definition at line 363 of file trilinos_eigen_solver.h.
References i, and oomph::DistributableLinearAlgebraObject::nrow_local().
The documentation for this class was generated from the following file:
trilinos_eigen_solver.h