oomph::ExactDGPBlockPreconditioner< MATRIX > Class Template Reference
General purpose block tridiagonal preconditioner. By default SuperLUPreconditioner (or SuperLUDistPreconditioner) is used to solve the subsidiary systems, but other preconditioners can be used by setting them using passing a pointer to a function of type SubsidiaryPreconditionerFctPt to the method subsidiary_preconditioner_function_pt().
#include <general_purpose_space_time_block_preconditioner.h>
Public Member Functions
ExactDGPBlockPreconditioner ()
Constructor. (By default this preconditioner is upper triangular).
virtual ~ExactDGPBlockPreconditioner ()
Destructor - delete the preconditioner matrices.
virtual void clean_up_memory ()
Clean up the memory.
ExactDGPBlockPreconditioner (const ExactDGPBlockPreconditioner &)
Broken copy constructor.
void operator= (const ExactDGPBlockPreconditioner &)
Broken assignment operator.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply preconditioner to r.
void setup ()
Setup the preconditioner.
void enable_doc_memory_usage ()
Document the memory usage.
void disable_doc_memory_usage ()
Don't document the memory usage!
double get_memory_usage_in_bytes ()
Get the memory statistics.
Private Attributes
bool Preconditioner_has_been_setup
Control flag is true if the preconditioner has been setup (used so we can wipe the data when the preconditioner is called again)
bool Compute_memory_statistics
Flag to indicate whether or not to record the memory statistics this preconditioner.
double Memory_usage_in_bytes
Storage for the memory usage of the solver if the flag above is set to true (in bytes)
Additional Inherited Members
Detailed Description
template<typename MATRIX>
class oomph::ExactDGPBlockPreconditioner< MATRIX >
General purpose block tridiagonal preconditioner. By default SuperLUPreconditioner (or SuperLUDistPreconditioner) is used to solve the subsidiary systems, but other preconditioners can be used by setting them using passing a pointer to a function of type SubsidiaryPreconditionerFctPt to the method subsidiary_preconditioner_function_pt().
Definition at line 57 of file general_purpose_space_time_block_preconditioner.h.
Constructor & Destructor Documentation
ExactDGPBlockPreconditioner() [1/2]
template<typename MATRIX >
oomph::ExactDGPBlockPreconditioner< MATRIX >::ExactDGPBlockPreconditioner () [inline]
Constructor. (By default this preconditioner is upper triangular).
Definition at line 62 of file general_purpose_space_time_block_preconditioner.h.
References oomph::ExactDGPBlockPreconditioner< MATRIX >::Compute_memory_statistics, oomph::ExactDGPBlockPreconditioner< MATRIX >::Memory_usage_in_bytes, and oomph::ExactDGPBlockPreconditioner< MATRIX >::Preconditioner_has_been_setup.
 ExactDGPBlockPreconditioner()
template<typename MATRIX >
virtual oomph::ExactDGPBlockPreconditioner< MATRIX >::~ExactDGPBlockPreconditioner () [inline], [virtual]
Destructor - delete the preconditioner matrices.
Definition at line 76 of file general_purpose_space_time_block_preconditioner.h.
References oomph::ExactDGPBlockPreconditioner< MATRIX >::clean_up_memory().
ExactDGPBlockPreconditioner() [2/2]
template<typename MATRIX >
oomph::ExactDGPBlockPreconditioner< MATRIX >::ExactDGPBlockPreconditioner (const ExactDGPBlockPreconditioner< MATRIX > &) [inline]
Broken copy constructor.
Definition at line 92 of file general_purpose_space_time_block_preconditioner.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
clean_up_memory()
template<typename MATRIX >
virtual void oomph::ExactDGPBlockPreconditioner< MATRIX >::clean_up_memory () [inline], [virtual]
Clean up the memory.
Reimplemented from oomph::GeneralPurposeBlockPreconditioner< MATRIX >.
Definition at line 84 of file general_purpose_space_time_block_preconditioner.h.
References oomph::GeneralPurposeBlockPreconditioner< MATRIX >::clean_up_memory().
Referenced by oomph::ExactDGPBlockPreconditioner< MATRIX >::~ExactDGPBlockPreconditioner().
disable_doc_memory_usage()
template<typename MATRIX >
void oomph::ExactDGPBlockPreconditioner< MATRIX >::disable_doc_memory_usage () [inline]
Don't document the memory usage!
Set the appropriate flag to false
Definition at line 122 of file general_purpose_space_time_block_preconditioner.h.
References oomph::ExactDGPBlockPreconditioner< MATRIX >::Compute_memory_statistics.
enable_doc_memory_usage()
template<typename MATRIX >
void oomph::ExactDGPBlockPreconditioner< MATRIX >::enable_doc_memory_usage () [inline]
Document the memory usage.
Set the appropriate flag to true
Definition at line 114 of file general_purpose_space_time_block_preconditioner.h.
References oomph::ExactDGPBlockPreconditioner< MATRIX >::Compute_memory_statistics.
get_memory_usage_in_bytes()
template<typename MATRIX >
double oomph::ExactDGPBlockPreconditioner< MATRIX >::get_memory_usage_in_bytes () [inline]
Get the memory statistics.
Definition at line 130 of file general_purpose_space_time_block_preconditioner.h.
References oomph::ExactDGPBlockPreconditioner< MATRIX >::Compute_memory_statistics, oomph::ExactDGPBlockPreconditioner< MATRIX >::Memory_usage_in_bytes, and oomph::ExactDGPBlockPreconditioner< MATRIX >::Preconditioner_has_been_setup.
operator=()
template<typename MATRIX >
void oomph::ExactDGPBlockPreconditioner< MATRIX >::operator= (const ExactDGPBlockPreconditioner< MATRIX > &) [inline]
Broken assignment operator.
Definition at line 99 of file general_purpose_space_time_block_preconditioner.h.
References oomph::BrokenCopy::broken_assign().
preconditioner_solve()
template<typename MATRIX >
void oomph::ExactDGPBlockPreconditioner< MATRIX >::preconditioner_solve (const DoubleVector & r, DoubleVector & z) [virtual]
Apply preconditioner to r.
Preconditioner solve for the exact preconditioner.
Implements oomph::Preconditioner.
Definition at line 181 of file general_purpose_space_time_block_preconditioner.cc.
References oomph::DoubleVectorHelpers::concatenate(), and oomph::DoubleVectorHelpers::split().
setup()
template<typename MATRIX >
void oomph::ExactDGPBlockPreconditioner< MATRIX >::setup [virtual]
Setup the preconditioner.
Set up the exact preconditioner.
Implements oomph::Preconditioner.
Definition at line 42 of file general_purpose_space_time_block_preconditioner.cc.
References oomph::TerminateHelper::clean_up_memory(), i, oomph::oomph_info, oomph::oomph_nullstream, oomph::OomphInfo::stream_pt(), and oomph::TimingHelpers::timer().
Member Data Documentation
Compute_memory_statistics
template<typename MATRIX >
bool oomph::ExactDGPBlockPreconditioner< MATRIX >::Compute_memory_statistics [private]
Flag to indicate whether or not to record the memory statistics this preconditioner.
Definition at line 188 of file general_purpose_space_time_block_preconditioner.h.
Referenced by oomph::ExactDGPBlockPreconditioner< MATRIX >::disable_doc_memory_usage(), oomph::ExactDGPBlockPreconditioner< MATRIX >::enable_doc_memory_usage(), oomph::ExactDGPBlockPreconditioner< MATRIX >::ExactDGPBlockPreconditioner(), and oomph::ExactDGPBlockPreconditioner< MATRIX >::get_memory_usage_in_bytes().
Memory_usage_in_bytes
template<typename MATRIX >
double oomph::ExactDGPBlockPreconditioner< MATRIX >::Memory_usage_in_bytes [private]
Storage for the memory usage of the solver if the flag above is set to true (in bytes)
Definition at line 192 of file general_purpose_space_time_block_preconditioner.h.
Referenced by oomph::ExactDGPBlockPreconditioner< MATRIX >::ExactDGPBlockPreconditioner(), and oomph::ExactDGPBlockPreconditioner< MATRIX >::get_memory_usage_in_bytes().
Preconditioner_has_been_setup
template<typename MATRIX >
bool oomph::ExactDGPBlockPreconditioner< MATRIX >::Preconditioner_has_been_setup [private]
Control flag is true if the preconditioner has been setup (used so we can wipe the data when the preconditioner is called again)
Definition at line 184 of file general_purpose_space_time_block_preconditioner.h.
Referenced by oomph::ExactDGPBlockPreconditioner< MATRIX >::ExactDGPBlockPreconditioner(), and oomph::ExactDGPBlockPreconditioner< MATRIX >::get_memory_usage_in_bytes().
The documentation for this class was generated from the following files:
general_purpose_space_time_block_preconditioner.h
general_purpose_space_time_block_preconditioner.cc