oomph::RefineableQElement< 1 > Class Reference
Refineable version of QElement<1,NNODE_1D>.
#include <refineable_line_element.h>
Public Types
typedef void(RefineableQElement< 1 >::* VoidMemberFctPt) ()
Shorthand for pointer to an argument-free void member function of the refineable element.
Public Member Functions
RefineableQElement ()
Constructor: Pass refinement level (default 0 = root)
RefineableQElement (const RefineableQElement< 1 > &dummy)=delete
Broken copy constructor.
virtual ~RefineableQElement ()
Broken assignment operator.
unsigned required_nsons () const
A refineable line element has two sons.
Node * node_created_by_neighbour (const Vector< double > &s_fraction, bool &is_periodic)
If a neighbouring element has already created a node at a position corresponding to the local fractional position within the present element, s_fraction, return a pointer to that node. If not, return NULL (0). If the node is on a periodic boundary the flag is_periodic is true, otherwise it will be false.
Node * node_created_by_son_of_neighbour (const Vector< double > &s_fraction, bool &is_periodic)
If a neighbouring element has already created a node at a position corresponding to the local fractional position within the present element, s_fraction, return a pointer to that node. If not, return NULL (0). If the node is on a periodic boundary the flag is_periodic is true, otherwise it will be false.
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)
Build the element, i.e. give it nodal positions, apply BCs, etc. Pointers to any new nodes will be returned in new_node_pt. If it is open, the positions of the new nodes will be written to the file stream new_nodes_file.
void check_integrity (double &max_error)
Check the integrity of the element: ensure that the position and values are continuous across the element edges.
void output_corners (std::ostream &outfile, const std::string &colour) const
Print corner nodes, using colour.
BinaryTree * binary_tree_pt ()
Pointer to binary tree representation of this element.
BinaryTree * binary_tree_pt () const
Pointer to binary tree representation of this element (const version)
void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
Line elements have no hanging nodes so this is deliberately left empty.
Protected Member Functions
void setup_father_bounds ()
Setup static matrix for coincidence between son nodal points and father boundaries.
void setup_hang_for_value (const int &value_id)
Line elements have no hanging nodes so this is deliberately left empty.
void binary_hang_helper (const int &value_id, const int &my_edge, std::ofstream &output_hangfile)
Line elements have no hanging nodes so this is deliberately left empty.
Static Protected Attributes
static std::map< unsigned, DenseMatrix< int > > Father_bound
Coincidence between son nodal points and father boundaries: Father_bound[node_1d](jnod_son,son_type) = {L/R/OMEGA}.
Additional Inherited Members
Detailed Description
Refineable version of QElement<1,NNODE_1D>.
Refinement is performed by binary tree procedures. When the element is subdivided, the geometry of its sons is established by calls to their father's get_x(...) function which refers to:
the father element's geometric FE mapping (this is the default) or
a MacroElement's MacroElement::macro_map (if the pointer to the macro element is non-NULL)
The class provides a generic RefineableQElement<1>::build() function which deals with generic isoparametric QElements in which all values are associated with nodes. The RefineableQElement<1>::further_build() function provides an interface for any element-specific non-generic build operations.
Definition at line 64 of file refineable_line_element.h.
Member Typedef Documentation
VoidMemberFctPt
typedef void(RefineableQElement< 1 >::* oomph::RefineableQElement< 1 >::VoidMemberFctPt) ()
Shorthand for pointer to an argument-free void member function of the refineable element.
Definition at line 70 of file refineable_line_element.h.
Constructor & Destructor Documentation
RefineableQElement() [1/2]
oomph::RefineableQElement< 1 >::RefineableQElement () [inline]
Constructor: Pass refinement level (default 0 = root)
Definition at line 73 of file refineable_line_element.h.
References oomph::LeakCheckNames::_build.
RefineableQElement() [2/2]
oomph::RefineableQElement< 1 >::RefineableQElement (const RefineableQElement< 1 > & dummy) [delete]
Broken copy constructor.
 RefineableQElement()
virtual oomph::RefineableQElement< 1 >::~RefineableQElement () [inline], [virtual]
Broken assignment operator.
Destructor
Definition at line 92 of file refineable_line_element.h.
References oomph::LeakCheckNames::_build.
Member Function Documentation
binary_hang_helper()
void oomph::RefineableQElement< 1 >::binary_hang_helper (const int & value_id, const int & my_edge, std::ofstream & output_hangfile) [inline], [protected]
Line elements have no hanging nodes so this is deliberately left empty.
Definition at line 171 of file refineable_line_element.h.
binary_tree_pt() [1/2]
BinaryTree * oomph::RefineableQElement< 1 >::binary_tree_pt () [inline]
Pointer to binary tree representation of this element.
Definition at line 144 of file refineable_line_element.h.
binary_tree_pt() [2/2]
BinaryTree * oomph::RefineableQElement< 1 >::binary_tree_pt () const [inline]
Pointer to binary tree representation of this element (const version)
Definition at line 150 of file refineable_line_element.h.
build()
void oomph::RefineableQElement< 1 >::build (Mesh *& mesh_pt, Vector< Node * > & new_node_pt, bool & was_already_built, std::ofstream & new_nodes_file) [virtual]
Build the element, i.e. give it nodal positions, apply BCs, etc. Pointers to any new nodes will be returned in new_node_pt. If it is open, the positions of the new nodes will be written to the file stream new_nodes_file.
Build the element by doing the following:
Give it nodal positions (by establishing the pointers to its nodes). In the process create new nodes where required (i.e. if they don't already exist in the father element and have not already been created whilst building new neighbouring elements). Node building involves the following steps:
Get the nodal position from the father element.
Establish the time-history of the newly created nodal point (its coordinates and previous values) consistent with the father's history.
Add the new node to the mesh itself.
Doc newly created nodes in `new_nodes.dat` stored in the directory of the DocInfo object (only if it's open!).
NOTE: Unlike in higher-dimensional elements, in 1D it is impossible for newly-created nodes to be on a mesh boundary, since any boundary nodes must exist in the initial (coarse) mesh. Therefore it is not necessary to add any nodes to the mesh's boundary node storage schemes, and we always create normal `bulk` nodes.
Once the element has a full complement of nodes, excute the element- specific further_build() (empty by default -- must be overloaded for specific elements). This deals with any build operations that are not included in the generic process outlined above. For instance, in Crouzeix Raviart elements we need to initialise the internal pressure pressure values in a manner consistent with the pressure distribution in the father element.
Implements oomph::RefineableElement.
Reimplemented in oomph::RefineableSolidQElement< 1 >.
Definition at line 212 of file refineable_line_element.cc.
References oomph::Mesh::add_node_pt(), oomph::ElementWithMovingNodes::enable_always_evaluate_dresidual_dnodal_coordinates_by_fd(), oomph::ElementWithMovingNodes::enable_bypass_fill_in_jacobian_from_geometric_data(), oomph::MacroElementNodeUpdateElementBase::geom_object_pt(), oomph::RefineableElement::get_interpolated_values(), oomph::FiniteElement::get_node_at_local_coordinate(), oomph::FiniteElement::get_x(), oomph::BinaryTreeNames::L, oomph::FiniteElement::Macro_elem_pt, oomph::ElementWithMovingNodes::method_for_shape_derivs(), oomph::FiniteElement::node_pt(), oomph::Node::nposition_type(), oomph::Data::nvalue(), oomph::Tree::object_pt(), oomph::BinaryTreeNames::R, oomph::QElementBase::s_macro_ll(), oomph::QElementBase::s_macro_ur(), oomph::MacroElementNodeUpdateElementBase::set_node_update_info(), oomph::Data::set_value(), oomph::AlgebraicElementBase::setup_algebraic_node_update(), oomph::Tree::son_type(), oomph::Global_string_for_annotation::string(), t, oomph::Data::time_stepper_pt(), and oomph::Node::x().
check_integrity()
void oomph::RefineableQElement< 1 >::check_integrity (double & max_error) [virtual]
Check the integrity of the element: ensure that the position and values are continuous across the element edges.
Check inter-element continuity of.
nodal positions
(nodally) interpolated function values
Implements oomph::RefineableElement.
Definition at line 686 of file refineable_line_element.cc.
References e, oomph::RefineableElement::get_interpolated_values(), oomph::BinaryTree::gteq_edge_neighbour(), oomph::FiniteElement::interpolated_x(), oomph::TreeRoot::is_neighbour_periodic(), oomph::BinaryTreeNames::L, oomph::RefineableElement::ncont_interpolated_values(), oomph::RefineableElement::nodes_built(), oomph::Tree::object_pt(), oomph::oomph_info, oomph::BinaryTreeNames::R, oomph::Tree::root_pt(), t, and oomph::Node::x().
node_created_by_neighbour()
Node * oomph::RefineableQElement< 1 >::node_created_by_neighbour (const Vector< double > & s_fraction, bool & is_periodic)
If a neighbouring element has already created a node at a position corresponding to the local fractional position within the present element, s_fraction, return a pointer to that node. If not, return NULL (0). If the node is on a periodic boundary the flag is_periodic is true, otherwise it will be false.
If a neighbouring element has already created a node at a position corresponding to the local fractional position within the present element, s_fraction, return a pointer to that node. If not, return NULL (0). If the node is periodic the flag is_periodic will be true.
Definition at line 91 of file refineable_line_element.cc.
References oomph::FiniteElement::get_node_at_local_coordinate(), oomph::BinaryTree::gteq_edge_neighbour(), oomph::BinaryTreeNames::L, oomph::RefineableElement::nodes_built(), oomph::Tree::object_pt(), oomph::BinaryTreeNames::OMEGA, oomph::BinaryTreeNames::R, and oomph::Global_string_for_annotation::string().
node_created_by_son_of_neighbour()
Node * oomph::RefineableQElement< 1 >::node_created_by_son_of_neighbour (const Vector< double > & s_fraction, bool & is_periodic) [inline]
If a neighbouring element has already created a node at a position corresponding to the local fractional position within the present element, s_fraction, return a pointer to that node. If not, return NULL (0). If the node is on a periodic boundary the flag is_periodic is true, otherwise it will be false.
Definition at line 118 of file refineable_line_element.h.
output_corners()
void oomph::RefineableQElement< 1 >::output_corners (std::ostream & outfile, const std::string & colour) const
Print corner nodes, using colour.
Print corner nodes, use colour (default `BLACK`)
Definition at line 655 of file refineable_line_element.cc.
References oomph::TecplotNames::colour, oomph::Global_unsigned::Number, and s.
required_nsons()
unsigned oomph::RefineableQElement< 1 >::required_nsons () const [inline], [virtual]
A refineable line element has two sons.
Reimplemented from oomph::RefineableElement.
Definition at line 100 of file refineable_line_element.h.
setup_father_bounds()
void oomph::RefineableQElement< 1 >::setup_father_bounds () [protected]
Setup static matrix for coincidence between son nodal points and father boundaries.
Setup static matrix for coincidence between son nodal points and father boundaries:
Father_bound[nnode_1d](nnode_son,son_type) = {L/R/OMEGA}
so that node nnode_son in element of type son_type lies on boundary/ vertex Father_bound[nnode_1d](nnode_son,son_type) in its father element. If the node doesn't lie on a boundary the value is OMEGA.
Definition at line 48 of file refineable_line_element.cc.
References oomph::BinaryTreeNames::L, oomph::Tree::OMEGA, and oomph::BinaryTreeNames::R.
setup_hang_for_value()
void oomph::RefineableQElement< 1 >::setup_hang_for_value (const int & value_id) [inline], [protected]
Line elements have no hanging nodes so this is deliberately left empty.
Definition at line 168 of file refineable_line_element.h.
setup_hanging_nodes()
void oomph::RefineableQElement< 1 >::setup_hanging_nodes (Vector< std::ofstream * > & output_stream) [inline], [virtual]
Line elements have no hanging nodes so this is deliberately left empty.
Reimplemented from oomph::RefineableElement.
Definition at line 156 of file refineable_line_element.h.
Member Data Documentation
Father_bound
std::map< unsigned, DenseMatrix< int > > oomph::RefineableQElement< 1 >::Father_bound [static], [protected]
Coincidence between son nodal points and father boundaries: Father_bound[node_1d](jnod_son,son_type) = {L/R/OMEGA}.
Static matrix for coincidence between son nodal points and father boundaries.
Definition at line 161 of file refineable_line_element.h.
The documentation for this class was generated from the following files:
refineable_line_element.h
refineable_line_element.cc