oomph::GeneralisedNewtonianConstitutiveEquation< DIM > Class Template Reference
A Base class defining the generalise Newtonian constitutive relation.
#include <generalised_newtonian_constitutive_models.h>
Public Member Functions
GeneralisedNewtonianConstitutiveEquation ()
Empty constructor.
virtual ~GeneralisedNewtonianConstitutiveEquation ()
Empty virtual destructor.
virtual double viscosity (const double &second_invariant_of_rate_of_strain_tensor)=0
Function implementing the constitutive model Input: second invariant of the rate of strain Output: the viscosity For Newtonian behaviour this returns 1.
virtual double dviscosity_dinvariant (const double &second_invariant_of_rate_of_strain_tensor)=0
Function returning the derivative of the viscosity w.r.t. the second invariant of the rate of strain tensor For Newtonian behaviour this returns 0.0.
Detailed Description
template<unsigned DIM>
class oomph::GeneralisedNewtonianConstitutiveEquation< DIM >
A Base class defining the generalise Newtonian constitutive relation.
Definition at line 41 of file generalised_newtonian_constitutive_models.h.
Constructor & Destructor Documentation
GeneralisedNewtonianConstitutiveEquation()
template<unsigned DIM>
oomph::GeneralisedNewtonianConstitutiveEquation< DIM >::GeneralisedNewtonianConstitutiveEquation () [inline]
Empty constructor.
Definition at line 45 of file generalised_newtonian_constitutive_models.h.
 GeneralisedNewtonianConstitutiveEquation()
template<unsigned DIM>
virtual oomph::GeneralisedNewtonianConstitutiveEquation< DIM >::~GeneralisedNewtonianConstitutiveEquation () [inline], [virtual]
Empty virtual destructor.
Definition at line 49 of file generalised_newtonian_constitutive_models.h.
Member Function Documentation
dviscosity_dinvariant()
template<unsigned DIM>
virtual double oomph::GeneralisedNewtonianConstitutiveEquation< DIM >::dviscosity_dinvariant (const double & second_invariant_of_rate_of_strain_tensor) [pure virtual]
Function returning the derivative of the viscosity w.r.t. the second invariant of the rate of strain tensor For Newtonian behaviour this returns 0.0.
Implemented in oomph::TanhProfileConstitutiveEquation< DIM >, oomph::NicosConstitutiveEquation< DIM >, oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >, oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >, oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >, oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >, oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >, oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >, and oomph::NewtonianConstitutiveEquation< DIM >.
Referenced by oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), and oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst().
viscosity()
template<unsigned DIM>
virtual double oomph::GeneralisedNewtonianConstitutiveEquation< DIM >::viscosity (const double & second_invariant_of_rate_of_strain_tensor) [pure virtual]
Function implementing the constitutive model Input: second invariant of the rate of strain Output: the viscosity For Newtonian behaviour this returns 1.
Implemented in oomph::TanhProfileConstitutiveEquation< DIM >, oomph::NicosConstitutiveEquation< DIM >, oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >, oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >, oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >, oomph::HerschelBulkleyPapRegConstitutiveEquation< DIM >, oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >, oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >, oomph::HerschelBulkleyBerEngRegConstitutiveEquation< DIM >, oomph::PowerLawBerEngRegConstitutiveEquation< DIM >, and oomph::NewtonianConstitutiveEquation< DIM >.
Referenced by oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::max_and_min_invariant_and_viscosity(), and oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::traction().
The documentation for this class was generated from the following file:
generalised_newtonian_constitutive_models.h