oomph::BiharmonicElement< DIM > Class Template Reference
biharmonic element class
#include <biharmonic_elements.h>
Public Member Functions
double u (const unsigned &n, const unsigned &k) const
access function for value, kth dof of node n
BiharmonicElement ()
Constructor: Call constructors for QElement and Poisson equations.
~BiharmonicElement ()
unsigned required_nvalue (const unsigned &n) const
Required # of `values' (pinned or dofs) at node n.
void output (std::ostream &outfile)
Output.
void output (std::ostream &outfile, const unsigned &n_plot)
output wrapper
void output (FILE *file_pt)
C-style output.
void output (FILE *file_pt, const unsigned &n_plot)
C_style output at n_plot points.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
analytic solution wrapper
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Final override.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
computes error
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Call the equations-class overloaded unsteady error calculation.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::BiharmonicElement< DIM >
biharmonic element class
Definition at line 526 of file biharmonic_elements.h.
Constructor & Destructor Documentation
BiharmonicElement()
template<unsigned DIM>
oomph::BiharmonicElement< DIM >::BiharmonicElement () [inline]
Constructor: Call constructors for QElement and Poisson equations.
Definition at line 539 of file biharmonic_elements.h.
 BiharmonicElement()
template<unsigned DIM>
oomph::BiharmonicElement< DIM >::~BiharmonicElement () [inline]
Definition at line 542 of file biharmonic_elements.h.
Member Function Documentation
compute_error() [1/2]
template<unsigned DIM>
void oomph::BiharmonicElement< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [inline], [virtual]
computes error
Reimplemented from oomph::BiharmonicEquations< DIM >.
Definition at line 598 of file biharmonic_elements.h.
References oomph::BiharmonicEquations< DIM >::compute_error().
compute_error() [2/2]
template<unsigned DIM>
void oomph::BiharmonicElement< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [inline], [virtual]
Call the equations-class overloaded unsteady error calculation.
Reimplemented from oomph::BiharmonicEquations< DIM >.
Definition at line 608 of file biharmonic_elements.h.
References oomph::BiharmonicEquations< DIM >::compute_error().
output() [1/4]
template<unsigned DIM>
void oomph::BiharmonicElement< DIM >::output (FILE * file_pt) [inline], [virtual]
C-style output.
Reimplemented from oomph::BiharmonicEquations< DIM >.
Definition at line 566 of file biharmonic_elements.h.
References oomph::BiharmonicEquations< DIM >::output().
output() [2/4]
template<unsigned DIM>
void oomph::BiharmonicElement< DIM >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C_style output at n_plot points.
Reimplemented from oomph::BiharmonicEquations< DIM >.
Definition at line 572 of file biharmonic_elements.h.
References oomph::BiharmonicEquations< DIM >::output().
output() [3/4]
template<unsigned DIM>
void oomph::BiharmonicElement< DIM >::output (std::ostream & outfile) [inline], [virtual]
Output.
Reimplemented from oomph::BiharmonicEquations< DIM >.
Definition at line 554 of file biharmonic_elements.h.
References oomph::BiharmonicEquations< DIM >::output().
output() [4/4]
template<unsigned DIM>
void oomph::BiharmonicElement< DIM >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
output wrapper
Reimplemented from oomph::BiharmonicEquations< DIM >.
Definition at line 560 of file biharmonic_elements.h.
References oomph::BiharmonicEquations< DIM >::output().
output_fct() [1/2]
template<unsigned DIM>
void oomph::BiharmonicElement< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Final override.
Reimplemented from oomph::BiharmonicEquations< DIM >.
Definition at line 588 of file biharmonic_elements.h.
References oomph::BiharmonicEquations< DIM >::output_fct().
output_fct() [2/2]
template<unsigned DIM>
void oomph::BiharmonicElement< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
analytic solution wrapper
Reimplemented from oomph::BiharmonicEquations< DIM >.
Definition at line 579 of file biharmonic_elements.h.
References oomph::BiharmonicEquations< DIM >::output_fct().
required_nvalue()
template<unsigned DIM>
unsigned oomph::BiharmonicElement< DIM >::required_nvalue (const unsigned & n) const [inline], [virtual]
Required # of `values' (pinned or dofs) at node n.
Reimplemented from oomph::FiniteElement.
Definition at line 547 of file biharmonic_elements.h.
u()
template<unsigned DIM>
double oomph::BiharmonicElement< DIM >::u (const unsigned & n, const unsigned & k) const [inline], [virtual]
access function for value, kth dof of node n
Implements oomph::BiharmonicEquations< DIM >.
Definition at line 531 of file biharmonic_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::Node::value().
The documentation for this class was generated from the following file:
biharmonic_elements.h