oomph::SolidQElement< 3, NNODE_1D > Class Template Reference
SolidQElement elements, specialised to three spatial dimensions.
#include <Qelements.h>
Public Member Functions
SolidQElement ()
Constructor.
SolidQElement (const SolidQElement &)=delete
Broken copy constructor.
void output (std::ostream &outfile)
Broken assignment operator.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at n_plot^2 points.
void output (FILE *file_pt)
C-style output.
void output (FILE *file_pt, const unsigned &n_plot)
C_style output at n_plot points.
void build_face_element (const int &face_index, FaceElement *face_element_pt)
Build the lower-dimensional FaceElement (an element of type SolidQElement<2,NNODE_1D>). The face index takes of one six values corresponding to the six possible faces: -1 (Left) s[0] = -1.0 +1 (Right) s[0] = 1.0 -2 (Down) s[1] = -1.0 +2 (Up) s[1] = 1.0 -3 (Back) s[2] = -1.0 +3 (Front) s[2] = 1.0.
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::SolidQElement< 3, NNODE_1D >
SolidQElement elements, specialised to three spatial dimensions.
Definition at line 2077 of file Qelements.h.
Constructor & Destructor Documentation
SolidQElement() [1/2]
template<unsigned NNODE_1D>
oomph::SolidQElement< 3, NNODE_1D >::SolidQElement () [inline]
Constructor.
Definition at line 2082 of file Qelements.h.
SolidQElement() [2/2]
template<unsigned NNODE_1D>
oomph::SolidQElement< 3, NNODE_1D >::SolidQElement (const SolidQElement< 3, NNODE_1D > &) [delete]
Broken copy constructor.
Member Function Documentation
build_face_element()
template<unsigned NNODE_1D>
void oomph::SolidQElement< 3, NNODE_1D >::build_face_element (const int & face_index, FaceElement * face_element_pt) [inline], [virtual]
Build the lower-dimensional FaceElement (an element of type SolidQElement<2,NNODE_1D>). The face index takes of one six values corresponding to the six possible faces: -1 (Left) s[0] = -1.0 +1 (Right) s[0] = 1.0 -2 (Down) s[1] = -1.0 +2 (Up) s[1] = 1.0 -3 (Back) s[2] = -1.0 +3 (Front) s[2] = 1.0.
Function to setup geometrical information for lower-dimensional FaceElements (which are of type SolidQElement<1,NNODE_1D>).
Reimplemented from oomph::FiniteElement.
Definition at line 2240 of file Qelements.h.
References oomph::SolidNode::nlagrangian().
output() [1/4]
template<unsigned NNODE_1D>
void oomph::SolidQElement< 3, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output.
Reimplemented from oomph::QElement< 3, NNODE_1D >.
Definition at line 2108 of file Qelements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<unsigned NNODE_1D>
void oomph::SolidQElement< 3, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C_style output at n_plot points.
C-style output function for any number of points per element.
Reimplemented from oomph::QElement< 3, NNODE_1D >.
Definition at line 2189 of file Qelements.h.
References i, and s.
output() [3/4]
template<unsigned NNODE_1D>
void oomph::SolidQElement< 3, NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Broken assignment operator.
Overload the output function
Reimplemented from oomph::QElement< 3, NNODE_1D >.
Definition at line 2099 of file Qelements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<unsigned NNODE_1D>
void oomph::SolidQElement< 3, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output at n_plot^2 points.
The output function for any number of points per element.
Reimplemented from oomph::QElement< 3, NNODE_1D >.
Definition at line 2140 of file Qelements.h.
References i, and s.
The documentation for this class was generated from the following file:
Qelements.h