QTaylorHoodSpaceTimeElement< DIM > Class Template Reference
/////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////
#include <discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h>
Public Member Functions
QTaylorHoodSpaceTimeElement ()
Constructor, no internal data points.
virtual unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void ptest_nst (const Vector< double > &s, Shape &psi) const
Pressure test functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
virtual int p_nodal_index_nst () const
Set the value at which the pressure is stored in the nodes.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
double p_nst (const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
double p_nst (const unsigned &t, const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
unsigned npres_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs containing.
void identify_pressure_data (std::set< std::pair< Data *, unsigned > > &paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
unsigned ndof_types () const
Returns the number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity and pressure.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1.
QTaylorHoodSpaceTimeElement ()
Constructor, no internal data points.
~QTaylorHoodSpaceTimeElement ()
virtual unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void ptest_nst (const Vector< double > &s, Shape &psi) const
Pressure test functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
virtual int p_nodal_index_nst () const
Set the value at which the pressure is stored in the nodes.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
double p_nst (const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
double p_nst (const unsigned &t, const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
unsigned npres_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs containing.
void identify_pressure_data (std::set< std::pair< Data *, unsigned > > &paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
QTaylorHoodSpaceTimeElement ()
Constructor, no internal data points.
virtual unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
virtual int p_nodal_index_nst () const
Set the value at which the pressure is stored in the nodes.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
double p_nst (const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
double p_nst (const unsigned &t, const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
unsigned npres_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs containing.
void identify_pressure_data (std::set< std::pair< Data *, unsigned > > &paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
Protected Member Functions
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
double dpshape_eulerian (const Vector< double > &s, Shape &ppsi, DShape &dppsidx) const
Pressure shape functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
double dptest_eulerian (const Vector< double > &s, Shape &ptest, DShape &dptestdx) const
Pressure test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
double dpshape_eulerian (const Vector< double > &s, Shape &ppsi, DShape &dppsidx) const
Pressure shape functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
double dptest_eulerian (const Vector< double > &s, Shape &ptest, DShape &dptestdx) const
Pressure test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
const unsigned Pconv [12]
const unsigned Pconv [8]
const unsigned Pconv [8]
Static Protected Attributes
static const unsigned Pconv []
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Private Member Functions
const unsigned Initial_Nvalue [27]
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
const unsigned Initial_Nvalue [27]
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
const unsigned Initial_Nvalue [27]
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Static Private Attributes
static const unsigned Initial_Nvalue []
Static array of ints to hold number of variables at node.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class QTaylorHoodSpaceTimeElement< DIM >
/////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////
Taylor-Hood elements are Navier-Stokes elements with quadratic interpolation for velocities and positions and continuous linear pressure interpolation. They can be used within oomph-lib's block-preconditioning framework.
Definition at line 2123 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Constructor & Destructor Documentation
QTaylorHoodSpaceTimeElement() [1/3]
template<unsigned DIM>
QTaylorHoodSpaceTimeElement< DIM >::QTaylorHoodSpaceTimeElement () [inline]
Constructor, no internal data points.
Definition at line 2198 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
QTaylorHoodSpaceTimeElement() [2/3]
template<unsigned DIM>
QTaylorHoodSpaceTimeElement< DIM >::QTaylorHoodSpaceTimeElement () [inline]
Constructor, no internal data points.
Definition at line 2198 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
 QTaylorHoodSpaceTimeElement()
template<unsigned DIM>
QTaylorHoodSpaceTimeElement< DIM >::~QTaylorHoodSpaceTimeElement () [inline]
Definition at line 2204 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
QTaylorHoodSpaceTimeElement() [3/3]
template<unsigned DIM>
QTaylorHoodSpaceTimeElement< DIM >::QTaylorHoodSpaceTimeElement () [inline]
Constructor, no internal data points.
Definition at line 2154 of file spacetime_navier_stokes_elements.h.
Member Function Documentation
build_fp_press_adv_diff_robin_bc_element() [1/3]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::build_fp_press_adv_diff_robin_bc_element (const unsigned & face_index) [inline], [virtual]
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Implements SpaceTimeNavierStokesEquations< DIM >.
Reimplemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
Definition at line 2284 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
build_fp_press_adv_diff_robin_bc_element() [2/3]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::build_fp_press_adv_diff_robin_bc_element (const unsigned & face_index) [inline], [virtual]
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Implements SpaceTimeNavierStokesEquations< DIM >.
Reimplemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
Definition at line 2291 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
build_fp_press_adv_diff_robin_bc_element() [3/3]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::build_fp_press_adv_diff_robin_bc_element (const unsigned & face_index) [inline], [virtual]
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Implements SpaceTimeNavierStokesEquations< DIM >.
Definition at line 2236 of file spacetime_navier_stokes_elements.h.
dpshape_and_dptest_eulerian_nst() [1/3]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implements SpaceTimeNavierStokesEquations< DIM >.
dpshape_and_dptest_eulerian_nst() [2/3]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implements SpaceTimeNavierStokesEquations< DIM >.
dpshape_and_dptest_eulerian_nst() [3/3]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implements SpaceTimeNavierStokesEquations< DIM >.
dpshape_eulerian() [1/2]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::dpshape_eulerian (const Vector< double > & s, Shape & ppsi, DShape & dppsidx) const [inline], [protected], [virtual]
Pressure shape functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implements SpaceTimeNavierStokesEquations< DIM >.
dpshape_eulerian() [2/2]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::dpshape_eulerian (const Vector< double > & s, Shape & ppsi, DShape & dppsidx) const [inline], [protected], [virtual]
Pressure shape functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implements SpaceTimeNavierStokesEquations< DIM >.
dptest_eulerian() [1/2]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::dptest_eulerian (const Vector< double > & s, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
Pressure test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implements SpaceTimeNavierStokesEquations< DIM >.
dptest_eulerian() [2/2]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::dptest_eulerian (const Vector< double > & s, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
Pressure test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implements SpaceTimeNavierStokesEquations< DIM >.
dshape_and_dtest_eulerian_at_knot_nst() [1/6]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implements SpaceTimeNavierStokesEquations< DIM >.
dshape_and_dtest_eulerian_at_knot_nst() [2/6]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implements SpaceTimeNavierStokesEquations< DIM >.
dshape_and_dtest_eulerian_at_knot_nst() [3/6]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implements SpaceTimeNavierStokesEquations< DIM >.
dshape_and_dtest_eulerian_at_knot_nst() [4/6]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements SpaceTimeNavierStokesEquations< DIM >.
Definition at line 2485 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References i, and s.
dshape_and_dtest_eulerian_at_knot_nst() [5/6]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Implements SpaceTimeNavierStokesEquations< DIM >.
dshape_and_dtest_eulerian_at_knot_nst() [6/6]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Implements SpaceTimeNavierStokesEquations< DIM >.
dshape_and_dtest_eulerian_nst() [1/3]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements SpaceTimeNavierStokesEquations< DIM >.
Definition at line 2375 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::OneDimLagrange::dshape< 3 >(), oomph::OneDimDiscontinuousGalerkin::dshape< 3 >(), i, s, oomph::OneDimLagrange::shape< 3 >(), and oomph::OneDimDiscontinuousGalerkin::shape< 3 >().
dshape_and_dtest_eulerian_nst() [2/3]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Implements SpaceTimeNavierStokesEquations< DIM >.
dshape_and_dtest_eulerian_nst() [3/3]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Implements SpaceTimeNavierStokesEquations< DIM >.
fix_pressure() [1/3]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::fix_pressure (const unsigned & p_dof, const double & p_value) [inline], [virtual]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implements SpaceTimeNavierStokesEquations< DIM >.
Definition at line 2270 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
fix_pressure() [2/3]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::fix_pressure (const unsigned & p_dof, const double & p_value) [inline], [virtual]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implements SpaceTimeNavierStokesEquations< DIM >.
Definition at line 2277 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
fix_pressure() [3/3]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::fix_pressure (const unsigned & p_dof, const double & p_value) [inline], [virtual]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implements SpaceTimeNavierStokesEquations< DIM >.
Definition at line 2222 of file spacetime_navier_stokes_elements.h.
get_dof_numbers_for_unknowns()
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1.
Create a list of pairs for all unknowns in this element, so the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Definition at line 3068 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
identify_load_data() [1/3]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data)
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Definition at line 2998 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i.
identify_load_data() [2/3]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data)
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
identify_load_data() [3/3]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data)
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
identify_pressure_data() [1/3]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::identify_pressure_data (std::set< std::pair< Data *, unsigned > > & paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all pressure values that affect the load computed in the get_load(...) function.
the pointer to a Data object and
the index of the value in that Data object
for pressure values that affect the load computed in the get_load(...) function.,
Definition at line 3040 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
identify_pressure_data() [2/3]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::identify_pressure_data (std::set< std::pair< Data *, unsigned > > & paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all pressure values that affect the load computed in the get_load(...) function.
identify_pressure_data() [3/3]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::identify_pressure_data (std::set< std::pair< Data *, unsigned > > & paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all pressure values that affect the load computed in the get_load(...) function.
Initial_Nvalue() [1/3]
const unsigned QTaylorHoodSpaceTimeElement< 2 >::Initial_Nvalue [private]
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Definition at line 2979 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
Initial_Nvalue() [2/3]
const unsigned QTaylorHoodSpaceTimeElement< 2 >::Initial_Nvalue [private]
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Definition at line 2972 of file discontinuous_galerkin_spacetime_navier_stokes_elements.cc.
Initial_Nvalue() [3/3]
const unsigned QTaylorHoodSpaceTimeElement< 2 >::Initial_Nvalue [private]
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Definition at line 2976 of file spacetime_navier_stokes_elements.cc.
ndof_types()
template<unsigned DIM>
unsigned QTaylorHoodSpaceTimeElement< DIM >::ndof_types () const [inline]
Returns the number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity and pressure.
Definition at line 2350 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
npres_nst() [1/3]
template<unsigned DIM>
unsigned QTaylorHoodSpaceTimeElement< DIM >::npres_nst () const [inline], [virtual]
Return number of pressure values.
Implements SpaceTimeNavierStokesEquations< DIM >.
Definition at line 2261 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::identify_load_data(), and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs().
npres_nst() [2/3]
template<unsigned DIM>
unsigned QTaylorHoodSpaceTimeElement< DIM >::npres_nst () const [inline], [virtual]
Return number of pressure values.
Implements SpaceTimeNavierStokesEquations< DIM >.
Definition at line 2268 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
npres_nst() [3/3]
template<unsigned DIM>
unsigned QTaylorHoodSpaceTimeElement< DIM >::npres_nst () const [inline], [virtual]
Return number of pressure values.
Implements SpaceTimeNavierStokesEquations< DIM >.
Definition at line 2213 of file spacetime_navier_stokes_elements.h.
output() [1/12]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::output (FILE * file_pt) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 2333 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References SpaceTimeNavierStokesEquations< DIM >::output().
output() [2/12]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::output (FILE * file_pt) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 2340 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References SpaceTimeNavierStokesEquations< DIM >::output().
output() [3/12]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::output (FILE * file_pt) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 2285 of file spacetime_navier_stokes_elements.h.
References SpaceTimeNavierStokesEquations< DIM >::output().
output() [4/12]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::output (FILE * file_pt, const unsigned & nplot) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 2341 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References SpaceTimeNavierStokesEquations< DIM >::output().
output() [5/12]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::output (FILE * file_pt, const unsigned & nplot) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 2348 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References SpaceTimeNavierStokesEquations< DIM >::output().
output() [6/12]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::output (FILE * file_pt, const unsigned & nplot) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 2293 of file spacetime_navier_stokes_elements.h.
References SpaceTimeNavierStokesEquations< DIM >::output().
output() [7/12]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::output (std::ostream & outfile) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 2317 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References SpaceTimeNavierStokesEquations< DIM >::output().
output() [8/12]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::output (std::ostream & outfile) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 2324 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References SpaceTimeNavierStokesEquations< DIM >::output().
output() [9/12]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::output (std::ostream & outfile) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 2269 of file spacetime_navier_stokes_elements.h.
References SpaceTimeNavierStokesEquations< DIM >::output().
output() [10/12]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 2325 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References SpaceTimeNavierStokesEquations< DIM >::output().
output() [11/12]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 2332 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References SpaceTimeNavierStokesEquations< DIM >::output().
output() [12/12]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 2277 of file spacetime_navier_stokes_elements.h.
References SpaceTimeNavierStokesEquations< DIM >::output().
p_local_eqn() [1/3]
template<unsigned DIM>
int QTaylorHoodSpaceTimeElement< DIM >::p_local_eqn (const unsigned & n) const [inline]
Return the local equation numbers for the pressure values.
Definition at line 2235 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
p_local_eqn() [2/3]
template<unsigned DIM>
int QTaylorHoodSpaceTimeElement< DIM >::p_local_eqn (const unsigned & n) const [inline]
Return the local equation numbers for the pressure values.
Definition at line 2242 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
p_local_eqn() [3/3]
template<unsigned DIM>
int QTaylorHoodSpaceTimeElement< DIM >::p_local_eqn (const unsigned & n) const [inline]
Return the local equation numbers for the pressure values.
Definition at line 2187 of file spacetime_navier_stokes_elements.h.
p_nodal_index_nst() [1/3]
template<unsigned DIM>
virtual int QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst () const [inline], [virtual]
Set the value at which the pressure is stored in the nodes.
Reimplemented from SpaceTimeNavierStokesEquations< DIM >.
Definition at line 2227 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::further_setup_hanging_nodes(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::identify_load_data(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs(), and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::unpin_elemental_pressure_dofs().
p_nodal_index_nst() [2/3]
template<unsigned DIM>
virtual int QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst () const [inline], [virtual]
Set the value at which the pressure is stored in the nodes.
Reimplemented from SpaceTimeNavierStokesEquations< DIM >.
Definition at line 2234 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
p_nodal_index_nst() [3/3]
template<unsigned DIM>
virtual int QTaylorHoodSpaceTimeElement< DIM >::p_nodal_index_nst () const [inline], [virtual]
Set the value at which the pressure is stored in the nodes.
Reimplemented from SpaceTimeNavierStokesEquations< DIM >.
Definition at line 2179 of file spacetime_navier_stokes_elements.h.
p_nst() [1/6]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::p_nst (const unsigned & n_p) const [inline], [virtual]
Access function for the pressure values at local pressure node n_p (const version)
Implements SpaceTimeNavierStokesEquations< DIM >.
Definition at line 2244 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
p_nst() [2/6]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::p_nst (const unsigned & n_p) const [inline], [virtual]
Access function for the pressure values at local pressure node n_p (const version)
Implements SpaceTimeNavierStokesEquations< DIM >.
Definition at line 2251 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
p_nst() [3/6]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::p_nst (const unsigned & n_p) const [inline], [virtual]
Access function for the pressure values at local pressure node n_p (const version)
Implements SpaceTimeNavierStokesEquations< DIM >.
Definition at line 2196 of file spacetime_navier_stokes_elements.h.
p_nst() [4/6]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::p_nst (const unsigned & t, const unsigned & n_p) const [inline], [virtual]
Access function for the pressure values at local pressure node n_p (const version)
Implements SpaceTimeNavierStokesEquations< DIM >.
Definition at line 2253 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References t.
p_nst() [5/6]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::p_nst (const unsigned & t, const unsigned & n_p) const [inline], [virtual]
Access function for the pressure values at local pressure node n_p (const version)
Implements SpaceTimeNavierStokesEquations< DIM >.
Definition at line 2260 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References t.
p_nst() [6/6]
template<unsigned DIM>
double QTaylorHoodSpaceTimeElement< DIM >::p_nst (const unsigned & t, const unsigned & n_p) const [inline], [virtual]
Access function for the pressure values at local pressure node n_p (const version)
Implements SpaceTimeNavierStokesEquations< DIM >.
Definition at line 2205 of file spacetime_navier_stokes_elements.h.
References t.
Pconv() [1/3]
const unsigned QTaylorHoodSpaceTimeElement< 2 >::Pconv [protected]
Definition at line 2985 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
Pconv() [2/3]
const unsigned QTaylorHoodSpaceTimeElement< 2 >::Pconv [protected]
Definition at line 2978 of file discontinuous_galerkin_spacetime_navier_stokes_elements.cc.
Pconv() [3/3]
const unsigned QTaylorHoodSpaceTimeElement< 2 >::Pconv [protected]
Definition at line 2982 of file spacetime_navier_stokes_elements.cc.
pshape_nst() [1/6]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Pressure shape functions at local coordinate s.
Implements SpaceTimeNavierStokesEquations< DIM >.
Referenced by oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::interpolating_basis().
pshape_nst() [2/6]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Pressure shape functions at local coordinate s.
Implements SpaceTimeNavierStokesEquations< DIM >.
pshape_nst() [3/6]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Pressure shape functions at local coordinate s.
Implements SpaceTimeNavierStokesEquations< DIM >.
pshape_nst() [4/6]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [virtual]
Pressure shape and test functions at local coordinte s.
Pressure shape and test functions.
Implements SpaceTimeNavierStokesEquations< DIM >.
Definition at line 2891 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References s.
pshape_nst() [5/6]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [virtual]
Pressure shape and test functions at local coordinte s.
Implements SpaceTimeNavierStokesEquations< DIM >.
pshape_nst() [6/6]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [virtual]
Pressure shape and test functions at local coordinte s.
Implements SpaceTimeNavierStokesEquations< DIM >.
ptest_nst() [1/2]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::ptest_nst (const Vector< double > & s, Shape & psi) const [inline]
Pressure test functions at local coordinate s.
ptest_nst() [2/2]
template<unsigned DIM>
void QTaylorHoodSpaceTimeElement< DIM >::ptest_nst (const Vector< double > & s, Shape & psi) const [inline]
Pressure test functions at local coordinate s.
required_nvalue() [1/3]
template<unsigned DIM>
virtual unsigned QTaylorHoodSpaceTimeElement< DIM >::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
Reimplemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
Definition at line 2205 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
required_nvalue() [2/3]
template<unsigned DIM>
virtual unsigned QTaylorHoodSpaceTimeElement< DIM >::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
Reimplemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
Definition at line 2212 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
required_nvalue() [3/3]
template<unsigned DIM>
virtual unsigned QTaylorHoodSpaceTimeElement< DIM >::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
Reimplemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
Definition at line 2161 of file spacetime_navier_stokes_elements.h.
Member Data Documentation
Initial_Nvalue
template<unsigned DIM>
static const unsigned QTaylorHoodSpaceTimeElement< DIM >::Initial_Nvalue [static], [private]
Static array of ints to hold number of variables at node.
Definition at line 2129 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Pconv
template<unsigned DIM>
static const unsigned QTaylorHoodSpaceTimeElement< DIM >::Pconv [static], [protected]
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Definition at line 2134 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pressure_node_pt().
The documentation for this class was generated from the following files:
discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h
discontinuous_galerkin_spacetime_navier_stokes_elements.h
spacetime_navier_stokes_elements.h
discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc
discontinuous_galerkin_spacetime_navier_stokes_elements.cc
spacetime_navier_stokes_elements.cc