oomph::BiharmonicFluidBoundaryElement Class Reference
Point equation element used to impose the traction free edge (i.e. du/dn = 0) on the boundary when dt/ds_n != 0. The following equation is implemented : du/ds_n = dt/ds_n * ds_t/dt * du/dt. The bulk biharmonic elements on the boundary must be hijackable and the du/ds_n and d2u/ds_nds_t boundary DOFs hijacked when these elements are applied. At any node where dt/ds_n = 0 we can impose du/ds_n = 0 and d2u/ds_nds_t = 0 using pinning - see BiharmonicFluidProblem::impose_traction_free_edge()
#include <biharmonic_problem.h>
Public Member Functions
BiharmonicFluidBoundaryElement (Node *node_pt, const unsigned s_fixed_index)
void output (std::ostream &outfile)
Output function -- does nothing.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function -- does nothing.
void output_fluid_velocity (std::ostream &outfile, const unsigned &n_plot)
Output function -- does nothing.
void output (FILE *file_pt)
C-style output function -- does nothing.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function -- does nothing.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
compute_error -- does nothing
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the elemental residual vector - wrapper function called by get_residuals in GeneralisedElement.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the elemental residual vector and jacobian matrix - wrapper function called by get_jacobian in GeneralisedElement.
virtual void fill_in_generic_residual_contribution_biharmonic_boundary (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned JFLAG)
Computes the elemental residual vector and the elemental jacobian matrix if JFLAG = 0 Imposes the equations : du/ds_n = dt/ds_n * ds_t/dt * du/dt.
Private Attributes
unsigned S_fixed_index
Additional Inherited Members
Detailed Description
Point equation element used to impose the traction free edge (i.e. du/dn = 0) on the boundary when dt/ds_n != 0. The following equation is implemented : du/ds_n = dt/ds_n * ds_t/dt * du/dt. The bulk biharmonic elements on the boundary must be hijackable and the du/ds_n and d2u/ds_nds_t boundary DOFs hijacked when these elements are applied. At any node where dt/ds_n = 0 we can impose du/ds_n = 0 and d2u/ds_nds_t = 0 using pinning - see BiharmonicFluidProblem::impose_traction_free_edge()
Definition at line 311 of file biharmonic_problem.h.
Constructor & Destructor Documentation
BiharmonicFluidBoundaryElement()
oomph::BiharmonicFluidBoundaryElement::BiharmonicFluidBoundaryElement (Node * node_pt, const unsigned s_fixed_index) [inline]
Definition at line 315 of file biharmonic_problem.h.
References oomph::FiniteElement::node_pt(), and S_fixed_index.
Member Function Documentation
compute_error()
void oomph::BiharmonicFluidBoundaryElement::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [inline], [virtual]
compute_error -- does nothing
Reimplemented from oomph::FiniteElement.
Definition at line 345 of file biharmonic_problem.h.
fill_in_contribution_to_jacobian()
void oomph::BiharmonicFluidBoundaryElement::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute the elemental residual vector and jacobian matrix - wrapper function called by get_jacobian in GeneralisedElement.
Reimplemented from oomph::GeneralisedElement.
Definition at line 368 of file biharmonic_problem.h.
References fill_in_generic_residual_contribution_biharmonic_boundary().
fill_in_contribution_to_residuals()
void oomph::BiharmonicFluidBoundaryElement::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Compute the elemental residual vector - wrapper function called by get_residuals in GeneralisedElement.
Reimplemented from oomph::GeneralisedElement.
Definition at line 355 of file biharmonic_problem.h.
References fill_in_generic_residual_contribution_biharmonic_boundary().
fill_in_generic_residual_contribution_biharmonic_boundary()
void oomph::BiharmonicFluidBoundaryElement::fill_in_generic_residual_contribution_biharmonic_boundary (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned JFLAG) [virtual]
Computes the elemental residual vector and the elemental jacobian matrix if JFLAG = 0 Imposes the equations : du/ds_n = dt/ds_n * ds_t/dt * du/dt.
Definition at line 390 of file biharmonic_problem.cc.
References oomph::GeneralisedElement::local_eqn_number(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), S_fixed_index, oomph::Node::value(), and oomph::Node::x_gen().
Referenced by fill_in_contribution_to_jacobian(), and fill_in_contribution_to_residuals().
output() [1/4]
void oomph::BiharmonicFluidBoundaryElement::output (FILE * file_pt) [inline], [virtual]
C-style output function -- does nothing.
Reimplemented from oomph::FiniteElement.
Definition at line 337 of file biharmonic_problem.h.
output() [2/4]
void oomph::BiharmonicFluidBoundaryElement::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function -- does nothing.
Reimplemented from oomph::FiniteElement.
Definition at line 341 of file biharmonic_problem.h.
output() [3/4]
void oomph::BiharmonicFluidBoundaryElement::output (std::ostream & outfile) [inline], [virtual]
Output function -- does nothing.
Reimplemented from oomph::FiniteElement.
Definition at line 325 of file biharmonic_problem.h.
output() [4/4]
void oomph::BiharmonicFluidBoundaryElement::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function -- does nothing.
Reimplemented from oomph::FiniteElement.
Definition at line 329 of file biharmonic_problem.h.
output_fluid_velocity()
void oomph::BiharmonicFluidBoundaryElement::output_fluid_velocity (std::ostream & outfile, const unsigned & n_plot) [inline]
Output function -- does nothing.
Definition at line 333 of file biharmonic_problem.h.
Member Data Documentation
S_fixed_index
unsigned oomph::BiharmonicFluidBoundaryElement::S_fixed_index [private]
Definition at line 385 of file biharmonic_problem.h.
Referenced by BiharmonicFluidBoundaryElement(), and fill_in_generic_residual_contribution_biharmonic_boundary().
The documentation for this class was generated from the following files:
biharmonic_problem.h
biharmonic_problem.cc