oomph::MacroElementNodeUpdateChannelWithLeafletMesh< ELEMENT > Class Template Reference
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
#include <channel_with_leaflet_mesh.template.h>
Public Member Functions
MacroElementNodeUpdateChannelWithLeafletMesh (GeomObject *leaflet_pt, const double &lleft, const double &lright, const double &hleaflet, const double &htot, const unsigned &nleft, const unsigned &nright, const unsigned &ny1, const unsigned &ny2, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass pointer to GeomObject that represents the leaflet, the length of the domain to left and right of the leaflet, the height of the leaflet and the overall height of the channel, the number of element columns to the left and right of the leaflet, the number of rows of elements from the bottom of the channel to the end of the leaflet, the number of rows of elements above the end of the leaflet. Timestepper defaults to Steady default Timestepper defined in the Mesh base class.
virtual ~MacroElementNodeUpdateChannelWithLeafletMesh ()
Destructor: empty.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::MacroElementNodeUpdateChannelWithLeafletMesh< ELEMENT >
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
Channel with leaflet mesh with MacroElement-based node update. The leaflet is represented by the specified geometric object. Some or all of the geometric Data in that geometric object may contain unknowns in the global Problem. The dependency on these unknowns is taken into account when setting up the Jacobian matrix of the elements. For this purpose, the element (whose type is specified by the template parameter) must inherit from MacroElementNodeUpdateElementBase.
Definition at line 166 of file channel_with_leaflet_mesh.template.h.
Constructor & Destructor Documentation
MacroElementNodeUpdateChannelWithLeafletMesh()
template<class ELEMENT >
oomph::MacroElementNodeUpdateChannelWithLeafletMesh< ELEMENT >::MacroElementNodeUpdateChannelWithLeafletMesh (GeomObject * leaflet_pt, const double & lleft, const double & lright, const double & hleaflet, const double & htot, const unsigned & nleft, const unsigned & nright, const unsigned & ny1, const unsigned & ny2, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass pointer to GeomObject that represents the leaflet, the length of the domain to left and right of the leaflet, the height of the leaflet and the overall height of the channel, the number of element columns to the left and right of the leaflet, the number of rows of elements from the bottom of the channel to the end of the leaflet, the number of rows of elements above the end of the leaflet. Timestepper defaults to Steady default Timestepper defined in the Mesh base class.
Definition at line 180 of file channel_with_leaflet_mesh.template.h.
References oomph::ChannelWithLeafletMesh< ELEMENT >::domain_pt(), oomph::Mesh::element_pt(), i, oomph::ChannelWithLeafletMesh< ELEMENT >::Leaflet_pt, oomph::MacroElementNodeUpdateMesh::macro_domain_pt(), oomph::Mesh::nelement(), oomph::MacroElementNodeUpdateMesh::set_geom_object_vector_pt(), and oomph::Global_string_for_annotation::string().
 MacroElementNodeUpdateChannelWithLeafletMesh()
template<class ELEMENT >
virtual oomph::MacroElementNodeUpdateChannelWithLeafletMesh< ELEMENT >::~MacroElementNodeUpdateChannelWithLeafletMesh () [inline], [virtual]
Destructor: empty.
Definition at line 277 of file channel_with_leaflet_mesh.template.h.
The documentation for this class was generated from the following file:
channel_with_leaflet_mesh.template.h