oomph::ExplicitTimeStepper Class Reference
A Base class for explicit timesteppers.
#include <explicit_timesteppers.h>
Public Member Functions
ExplicitTimeStepper ()
Empty Constructor.
ExplicitTimeStepper (const ExplicitTimeStepper &)
Broken copy constructor.
void operator= (const ExplicitTimeStepper &)
Broken assignment operator.
virtual ~ExplicitTimeStepper ()
Empty virtual destructor --- no memory is allocated in this class.
virtual void timestep (ExplicitTimeSteppableObject *const &object_pt, const double &dt)=0
Pure virtual function that is used to advance time in the object.
Protected Attributes
std::string Type
String that indicates the type of the timestepper (e.g. `RungeKutta`, etc.)
Detailed Description
A Base class for explicit timesteppers.
Definition at line 137 of file explicit_timesteppers.h.
Constructor & Destructor Documentation
ExplicitTimeStepper() [1/2]
oomph::ExplicitTimeStepper::ExplicitTimeStepper () [inline]
Empty Constructor.
Definition at line 146 of file explicit_timesteppers.h.
ExplicitTimeStepper() [2/2]
oomph::ExplicitTimeStepper::ExplicitTimeStepper (const ExplicitTimeStepper &) [inline]
Broken copy constructor.
Definition at line 149 of file explicit_timesteppers.h.
References oomph::BrokenCopy::broken_copy().
 ExplicitTimeStepper()
virtual oomph::ExplicitTimeStepper::~ExplicitTimeStepper () [inline], [virtual]
Empty virtual destructor --- no memory is allocated in this class.
Definition at line 161 of file explicit_timesteppers.h.
Member Function Documentation
operator=()
void oomph::ExplicitTimeStepper::operator= (const ExplicitTimeStepper &) [inline]
Broken assignment operator.
Definition at line 155 of file explicit_timesteppers.h.
References oomph::BrokenCopy::broken_assign().
timestep()
virtual void oomph::ExplicitTimeStepper::timestep (ExplicitTimeSteppableObject *const & object_pt, const double & dt) [pure virtual]
Pure virtual function that is used to advance time in the object.
Implemented in oomph::LowStorageRungeKutta< ORDER >, oomph::EBDF3, oomph::RungeKutta< ORDER >, oomph::LowStorageRungeKutta< ORDER >, oomph::RungeKutta< ORDER >, oomph::RungeKutta< ORDER >, and oomph::Euler.
Referenced by oomph::Problem::explicit_timestep().
Member Data Documentation
Type
std::string oomph::ExplicitTimeStepper::Type [protected]
String that indicates the type of the timestepper (e.g. `RungeKutta`, etc.)
Definition at line 142 of file explicit_timesteppers.h.
Referenced by oomph::Euler::Euler(), and oomph::RungeKutta< ORDER >::RungeKutta().
The documentation for this class was generated from the following file:
explicit_timesteppers.h