oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT > Class Template Reference
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
#include <axisym_poroelasticity_elements.h>
Public Member Functions
ProjectableAxisymmetricPoroelasticityElement ()
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Vector< std::pair< Data *, unsigned > > data_values_of_field (const unsigned &fld)
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld.
unsigned nfields_for_projection ()
Number of fields to be projected: 4 (two displacement components, pressure, Darcy flux)
unsigned nhistory_values_for_projection (const unsigned &fld)
Number of history values to be stored for fld-th field. (Note: count includes current value!)
unsigned nhistory_values_for_coordinate_projection ()
Number of positional history values (Note: count includes current value!)
double jacobian_and_shape_of_field (const unsigned &fld, const Vector< double > &s, Shape &psi)
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
double get_field (const unsigned &t, const unsigned &fld, const Vector< double > &s)
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
unsigned nvalue_of_field (const unsigned &fld)
Return number of values in field fld.
int local_equation (const unsigned &fld, const unsigned &j)
Return local equation number of value j in field fld.
void output (std::ostream &outfile, const unsigned &nplot)
Output FE representation of soln as in underlying element.
void residual_for_projection (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Residual for the projection step. Flag indicates if we want the Jacobian (1) or not (0). Virtual so it can be overloaded if necessary.
Additional Inherited Members
Detailed Description
template<class AXISYMMETRIC_POROELASTICITY_ELEMENT>
class oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Axisymmetric poro elasticity upgraded to become projectable
Definition at line 1396 of file axisym_poroelasticity_elements.h.
Constructor & Destructor Documentation
ProjectableAxisymmetricPoroelasticityElement()
template<class AXISYMMETRIC_POROELASTICITY_ELEMENT >
oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::ProjectableAxisymmetricPoroelasticityElement () [inline]
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Definition at line 1403 of file axisym_poroelasticity_elements.h.
Member Function Documentation
data_values_of_field()
template<class AXISYMMETRIC_POROELASTICITY_ELEMENT >
Vector<std::pair<Data*, unsigned> > oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::data_values_of_field (const unsigned & fld) [inline], [virtual]
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld.
Implements oomph::ProjectableElementBase.
Definition at line 1408 of file axisym_poroelasticity_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::Data::nvalue().
get_field()
template<class AXISYMMETRIC_POROELASTICITY_ELEMENT >
double oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::get_field (const unsigned & t, const unsigned & fld, const Vector< double > & s) [inline], [virtual]
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
Implements oomph::ProjectableElementBase.
Definition at line 1610 of file axisym_poroelasticity_elements.h.
References s, and t.
Referenced by oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::residual_for_projection().
jacobian_and_shape_of_field()
template<class AXISYMMETRIC_POROELASTICITY_ELEMENT >
double oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::jacobian_and_shape_of_field (const unsigned & fld, const Vector< double > & s, Shape & psi) [inline], [virtual]
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
Implements oomph::ProjectableElementBase.
Definition at line 1526 of file axisym_poroelasticity_elements.h.
References oomph::FiniteElement::dim(), i, oomph::Shape::nindex1(), oomph::FiniteElement::nnode(), and s.
Referenced by oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::residual_for_projection().
local_equation()
template<class AXISYMMETRIC_POROELASTICITY_ELEMENT >
int oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::local_equation (const unsigned & fld, const unsigned & j) [inline], [virtual]
Return local equation number of value j in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 1697 of file axisym_poroelasticity_elements.h.
References oomph::FiniteElement::nodal_local_eqn().
Referenced by oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::residual_for_projection().
nfields_for_projection()
template<class AXISYMMETRIC_POROELASTICITY_ELEMENT >
unsigned oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::nfields_for_projection () [inline], [virtual]
Number of fields to be projected: 4 (two displacement components, pressure, Darcy flux)
Implements oomph::ProjectableElementBase.
Definition at line 1482 of file axisym_poroelasticity_elements.h.
nhistory_values_for_coordinate_projection()
template<class AXISYMMETRIC_POROELASTICITY_ELEMENT >
unsigned oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::nhistory_values_for_coordinate_projection () [inline], [virtual]
Number of positional history values (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 1519 of file axisym_poroelasticity_elements.h.
References oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), and oomph::Node::position_time_stepper_pt().
nhistory_values_for_projection()
template<class AXISYMMETRIC_POROELASTICITY_ELEMENT >
unsigned oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::nhistory_values_for_projection (const unsigned & fld) [inline], [virtual]
Number of history values to be stored for fld-th field. (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 1489 of file axisym_poroelasticity_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::Data::ntstorage().
nvalue_of_field()
template<class AXISYMMETRIC_POROELASTICITY_ELEMENT >
unsigned oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::nvalue_of_field (const unsigned & fld) [inline], [virtual]
Return number of values in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 1661 of file axisym_poroelasticity_elements.h.
References oomph::FiniteElement::nnode().
Referenced by oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::residual_for_projection().
output()
template<class AXISYMMETRIC_POROELASTICITY_ELEMENT >
void oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output FE representation of soln as in underlying element.
Reimplemented from oomph::FiniteElement.
Definition at line 1743 of file axisym_poroelasticity_elements.h.
References oomph::CommandLineArgs::output().
residual_for_projection()
template<class AXISYMMETRIC_POROELASTICITY_ELEMENT >
void oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::residual_for_projection (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [inline], [virtual]
Residual for the projection step. Flag indicates if we want the Jacobian (1) or not (0). Virtual so it can be overloaded if necessary.
Reimplemented from oomph::ProjectableElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >.
Definition at line 1752 of file axisym_poroelasticity_elements.h.
References oomph::ProjectableElementBase::Coordinate, oomph::FiniteElement::dim(), oomph::ElementWithExternalElement::external_element_local_coord(), oomph::ElementWithExternalElement::external_element_pt(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::get_field(), oomph::ProjectableElementBase::get_field(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::J_eulerian(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::jacobian_and_shape_of_field(), oomph::Integral::knot(), oomph::ProjectableElementBase::Lagrangian, oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::local_equation(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::nvalue_of_field(), oomph::Integral::nweight(), oomph::SolidFiniteElement::position_local_eqn(), oomph::ProjectableElementBase::Projected_coordinate, oomph::ProjectableElementBase::Projected_field, oomph::ProjectableElementBase::Projected_lagrangian, oomph::ProjectableElementBase::Projection_type, s, oomph::FiniteElement::shape(), oomph::ProjectableElementBase::Time_level_for_projection, oomph::ProjectableElementBase::Value, oomph::QuadTreeNames::W, and oomph::Integral::weight().
The documentation for this class was generated from the following file:
axisym_poroelasticity_elements.h