oomph::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT > Class Template Reference
A class for elements that allow the imposition of Robin boundary conditions for the pressure advection diffusion problem in the Fp preconditioner. The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
#include <refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h>
Public Member Functions
RefineableFpPressureAdvDiffRobinBCSpaceTimeElement (FiniteElement *const &element_pt, const int &face_index)
Constructor, which takes a `bulk` element and the value of the index and its limit.
virtual void fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &construct_jacobian_flag)
This function returns the residuals for the traction function. If construct_jacobian_flag=1 (or 0): do (or don't) compute the Jacobian as well.
RefineableFpPressureAdvDiffRobinBCSpaceTimeElement (FiniteElement *const &element_pt, const int &face_index)
Constructor, which takes a `bulk` element and the value of the index and its limit.
virtual void fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &construct_jacobian_flag)
This function returns the residuals for the traction function. If construct_jacobian_flag=1 (or 0): do (or don't) compute the Jacobian as well.
RefineableFpPressureAdvDiffRobinBCSpaceTimeElement (FiniteElement *const &element_pt, const int &face_index)
Constructor, which takes a `bulk` element and the value of the index and its limit.
virtual void fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &construct_jacobian_flag)
This function returns the residuals for the traction function. If construct_jacobian_flag=1 (or 0): do (or don't) compute the Jacobian as well.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >
A class for elements that allow the imposition of Robin boundary conditions for the pressure advection diffusion problem in the Fp preconditioner. The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
Definition at line 53 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Constructor & Destructor Documentation
RefineableFpPressureAdvDiffRobinBCSpaceTimeElement() [1/3]
template<class ELEMENT >
oomph::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit.
Definition at line 59 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
RefineableFpPressureAdvDiffRobinBCSpaceTimeElement() [2/3]
template<class ELEMENT >
oomph::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit.
Definition at line 59 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
RefineableFpPressureAdvDiffRobinBCSpaceTimeElement() [3/3]
template<class ELEMENT >
oomph::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit.
Definition at line 59 of file refineable_spacetime_navier_stokes_elements.h.
Member Function Documentation
fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc() [1/3]
template<class ELEMENT >
void oomph::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & construct_jacobian_flag) [virtual]
This function returns the residuals for the traction function. If construct_jacobian_flag=1 (or 0): do (or don't) compute the Jacobian as well.
Get residuals and Jacobian of Robin boundary conditions in pressure advection diffusion problem in Fp preconditoner. Refineable version. Get outer unit normal
Get outer unit normal
Get outer unit normal
Reimplemented from oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >.
Definition at line 83 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References i, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), s, and oomph::QuadTreeNames::W.
fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc() [2/3]
template<class ELEMENT >
virtual void oomph::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & construct_jacobian_flag) [virtual]
This function returns the residuals for the traction function. If construct_jacobian_flag=1 (or 0): do (or don't) compute the Jacobian as well.
Reimplemented from oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >.
fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc() [3/3]
template<class ELEMENT >
virtual void oomph::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & construct_jacobian_flag) [virtual]
This function returns the residuals for the traction function. If construct_jacobian_flag=1 (or 0): do (or don't) compute the Jacobian as well.
Reimplemented from oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >.
The documentation for this class was generated from the following files:
refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h
refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h
refineable_spacetime_navier_stokes_elements.h