oomph::RefineableQuadMesh< ELEMENT > Class Template Reference
Intermediate mesh class that implements the mesh adaptation functions specified in the TreeBasedRefineableMesh class for meshes that contain the refineable variant of QElement s [The class ELEMENT provided as the template parameter must be of type RefineableQElement<2>].
#include <refineable_quad_mesh.h>
Public Member Functions
RefineableQuadMesh ()
Constructor: Setup static quadtree data.
RefineableQuadMesh (const RefineableQuadMesh &dummy)=delete
Broken copy constructor.
virtual ~RefineableQuadMesh ()
Broken assignment operator.
virtual void setup_tree_forest ()
Set up the tree forest associated with the Mesh. Forwards call to setup_quadtree_forest()
void setup_quadtree_forest ()
Set up QuadTreeForest. Wipes any existing tree structure below the minimum refinement level and regards the elements at that level as the root trees in the forest.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::RefineableQuadMesh< ELEMENT >
Intermediate mesh class that implements the mesh adaptation functions specified in the TreeBasedRefineableMesh class for meshes that contain the refineable variant of QElement s [The class ELEMENT provided as the template parameter must be of type RefineableQElement<2>].
Mesh adaptation/refinement is implemented by QuadTree procedures and any concrete implementation of this class needs to provide a QuadTreeForest representation of the initial (coarse) mesh.
Definition at line 51 of file refineable_quad_mesh.h.
Constructor & Destructor Documentation
RefineableQuadMesh() [1/2]
template<class ELEMENT >
oomph::RefineableQuadMesh< ELEMENT >::RefineableQuadMesh () [inline]
Constructor: Setup static quadtree data.
Definition at line 56 of file refineable_quad_mesh.h.
References oomph::QuadTree::setup_static_data().
RefineableQuadMesh() [2/2]
template<class ELEMENT >
oomph::RefineableQuadMesh< ELEMENT >::RefineableQuadMesh (const RefineableQuadMesh< ELEMENT > & dummy) [delete]
Broken copy constructor.
 RefineableQuadMesh()
template<class ELEMENT >
virtual oomph::RefineableQuadMesh< ELEMENT >::~RefineableQuadMesh () [inline], [virtual]
Broken assignment operator.
Destructor:
Definition at line 75 of file refineable_quad_mesh.h.
Member Function Documentation
setup_quadtree_forest()
template<class ELEMENT >
void oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest () [inline]
Set up QuadTreeForest. Wipes any existing tree structure below the minimum refinement level and regards the elements at that level as the root trees in the forest.
Definition at line 88 of file refineable_quad_mesh.h.
References oomph::Mesh::Comm_pt, e, oomph::Mesh::element_pt(), oomph::Tree::flush_sons(), oomph::TreeForest::flush_trees(), oomph::TreeBasedRefineableMeshBase::Forest_pt, oomph::TreeBasedRefineableMeshBase::get_refinement_levels(), i, oomph::Mesh::nelement(), oomph::Tree::nsons(), oomph::Tree::object_pt(), oomph::RefineableElement::refinement_level(), oomph::Tree::root_pt(), oomph::Tree::set_father_pt(), oomph::Tree::set_son_pt(), oomph::Tree::son_pt(), oomph::Tree::stick_all_tree_nodes_into_vector(), and oomph::TreeForest::stick_all_tree_nodes_into_vector().
Referenced by oomph::ElasticRectangularQuadMesh< ELEMENT >::ElasticRectangularQuadMesh(), oomph::MacroElementNodeUpdateRefineableChannelWithLeafletMesh< ELEMENT >::MacroElementNodeUpdateRefineableChannelWithLeafletMesh(), oomph::MacroElementNodeUpdateRefineableCollapsibleChannelMesh< ELEMENT >::MacroElementNodeUpdateRefineableCollapsibleChannelMesh(), oomph::RefineableAlgebraicChannelWithLeafletMesh< ELEMENT >::RefineableAlgebraicChannelWithLeafletMesh(), oomph::RefineableAlgebraicCollapsibleChannelMesh< ELEMENT >::RefineableAlgebraicCollapsibleChannelMesh(), oomph::RefineableAlgebraicCylinderWithFlagMesh< ELEMENT >::RefineableAlgebraicCylinderWithFlagMesh(), oomph::RefineableAlgebraicFSIDrivenCavityMesh< ELEMENT >::RefineableAlgebraicFSIDrivenCavityMesh(), oomph::RefineableBackwardStepQuadMesh< ELEMENT >::RefineableBackwardStepQuadMesh(), oomph::RefineableChannelWithLeafletMesh< ELEMENT >::RefineableChannelWithLeafletMesh(), oomph::RefineableCollapsibleChannelMesh< ELEMENT >::RefineableCollapsibleChannelMesh(), oomph::RefineableCylinderWithFlagMesh< ELEMENT >::RefineableCylinderWithFlagMesh(), oomph::RefineableFSIDrivenCavityMesh< ELEMENT >::RefineableFSIDrivenCavityMesh(), oomph::RefineableQuarterCircleSectorMesh< ELEMENT >::RefineableQuarterCircleSectorMesh(), oomph::RefineableRectangleWithHoleAndAnnularRegionMesh< ELEMENT >::RefineableRectangleWithHoleAndAnnularRegionMesh(), oomph::RefineableRectangleWithHoleMesh< ELEMENT >::RefineableRectangleWithHoleMesh(), oomph::RefineableRectangularQuadMesh< ELEMENT >::RefineableRectangularQuadMesh(), oomph::RefineableTwoDAnnularMesh< ELEMENT >::RefineableTwoDAnnularMesh(), and oomph::RefineableQuadMesh< ELEMENT >::setup_tree_forest().
setup_tree_forest()
template<class ELEMENT >
virtual void oomph::RefineableQuadMesh< ELEMENT >::setup_tree_forest () [inline], [virtual]
Set up the tree forest associated with the Mesh. Forwards call to setup_quadtree_forest()
Implements oomph::TreeBasedRefineableMeshBase.
Definition at line 80 of file refineable_quad_mesh.h.
References oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest().
The documentation for this class was generated from the following file:
refineable_quad_mesh.h