oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT > Class Template Reference
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
#include <space_time_unsteady_heat_elements.h>
Public Member Functions
ProjectableUnsteadyHeatSpaceTimeElement ()
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Vector< std::pair< Data *, unsigned > > data_values_of_field (const unsigned &fld)
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld.
unsigned nfields_for_projection ()
Number of fields to be projected: Just one.
unsigned nhistory_values_for_projection (const unsigned &fld)
Number of history values to be stored for fld-th field. (Note: count includes current value!)
unsigned nhistory_values_for_coordinate_projection ()
Number of positional history values (Note: count includes current value!)
double jacobian_and_shape_of_field (const unsigned &fld, const Vector< double > &s, Shape &psi)
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
double get_field (const unsigned &t, const unsigned &fld, const Vector< double > &s)
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
unsigned nvalue_of_field (const unsigned &fld)
Return number of values in field fld: One per node.
int local_equation (const unsigned &fld, const unsigned &j)
Return local equation number of value j in field fld.
void output (std::ostream &outfile, const unsigned &nplot)
Output FE representation of soln: x,t,u or x,y,t,u at n_plot^(SPATIAL_DIM+1) plot points.
ProjectableUnsteadyHeatSpaceTimeElement ()
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Vector< std::pair< Data *, unsigned > > data_values_of_field (const unsigned &fld)
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld.
unsigned nfields_for_projection ()
Number of fields to be projected: Just one.
unsigned nhistory_values_for_projection (const unsigned &fld)
Number of history values to be stored for fld-th field. (Note: count includes current value!)
unsigned nhistory_values_for_coordinate_projection ()
Number of positional history values (Note: count includes current value!)
double jacobian_and_shape_of_field (const unsigned &fld, const Vector< double > &s, Shape &psi)
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
double get_field (const unsigned &t, const unsigned &fld, const Vector< double > &s)
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
unsigned nvalue_of_field (const unsigned &fld)
Return number of values in field fld: One per node.
int local_equation (const unsigned &fld, const unsigned &j)
Return local equation number of value j in field fld.
void output (std::ostream &outfile, const unsigned &nplot)
Output FE representation of soln: x,t,u or x,y,t,u at n_plot^(SPATIAL_DIM+1) plot points.
Additional Inherited Members
Detailed Description
template<class UNSTEADY_HEAT_ELEMENT>
class oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
SpaceTimeUnsteadyHeat upgraded to become projectable
Definition at line 925 of file space_time_unsteady_heat_elements.h.
Constructor & Destructor Documentation
ProjectableUnsteadyHeatSpaceTimeElement() [1/2]
template<class UNSTEADY_HEAT_ELEMENT >
oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::ProjectableUnsteadyHeatSpaceTimeElement () [inline]
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Definition at line 931 of file space_time_unsteady_heat_elements.h.
ProjectableUnsteadyHeatSpaceTimeElement() [2/2]
template<class UNSTEADY_HEAT_ELEMENT >
oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::ProjectableUnsteadyHeatSpaceTimeElement () [inline]
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Definition at line 1013 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
Member Function Documentation
data_values_of_field() [1/2]
template<class UNSTEADY_HEAT_ELEMENT >
Vector< std::pair< Data *, unsigned > > oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::data_values_of_field (const unsigned & fld) [inline], [virtual]
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld.
Implements oomph::ProjectableElementBase.
Definition at line 937 of file space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
data_values_of_field() [2/2]
template<class UNSTEADY_HEAT_ELEMENT >
Vector< std::pair< Data *, unsigned > > oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::data_values_of_field (const unsigned & fld) [inline], [virtual]
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld.
Implements oomph::ProjectableElementBase.
Definition at line 1019 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
get_field() [1/2]
template<class UNSTEADY_HEAT_ELEMENT >
double oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::get_field (const unsigned & t, const unsigned & fld, const Vector< double > & s) [inline], [virtual]
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
Implements oomph::ProjectableElementBase.
Definition at line 1071 of file space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), and oomph::FiniteElement::shape().
get_field() [2/2]
template<class UNSTEADY_HEAT_ELEMENT >
double oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::get_field (const unsigned & t, const unsigned & fld, const Vector< double > & s) [inline], [virtual]
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
Implements oomph::ProjectableElementBase.
Definition at line 1153 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), and oomph::FiniteElement::shape().
jacobian_and_shape_of_field() [1/2]
template<class UNSTEADY_HEAT_ELEMENT >
double oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::jacobian_and_shape_of_field (const unsigned & fld, const Vector< double > & s, Shape & psi) [inline], [virtual]
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
Implements oomph::ProjectableElementBase.
Definition at line 1021 of file space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::dim(), oomph::FiniteElement::nnode(), and s.
jacobian_and_shape_of_field() [2/2]
template<class UNSTEADY_HEAT_ELEMENT >
double oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::jacobian_and_shape_of_field (const unsigned & fld, const Vector< double > & s, Shape & psi) [inline], [virtual]
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
Implements oomph::ProjectableElementBase.
Definition at line 1103 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::dim(), oomph::FiniteElement::nnode(), and s.
local_equation() [1/2]
template<class UNSTEADY_HEAT_ELEMENT >
int oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::local_equation (const unsigned & fld, const unsigned & j) [inline], [virtual]
Return local equation number of value j in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 1147 of file space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::nodal_local_eqn().
local_equation() [2/2]
template<class UNSTEADY_HEAT_ELEMENT >
int oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::local_equation (const unsigned & fld, const unsigned & j) [inline], [virtual]
Return local equation number of value j in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 1229 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::nodal_local_eqn().
nfields_for_projection() [1/2]
template<class UNSTEADY_HEAT_ELEMENT >
unsigned oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::nfields_for_projection () [inline], [virtual]
Number of fields to be projected: Just one.
Implements oomph::ProjectableElementBase.
Definition at line 976 of file space_time_unsteady_heat_elements.h.
nfields_for_projection() [2/2]
template<class UNSTEADY_HEAT_ELEMENT >
unsigned oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::nfields_for_projection () [inline], [virtual]
Number of fields to be projected: Just one.
Implements oomph::ProjectableElementBase.
Definition at line 1058 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
nhistory_values_for_coordinate_projection() [1/2]
template<class UNSTEADY_HEAT_ELEMENT >
unsigned oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::nhistory_values_for_coordinate_projection () [inline], [virtual]
Number of positional history values (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 1012 of file space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), and oomph::Node::position_time_stepper_pt().
nhistory_values_for_coordinate_projection() [2/2]
template<class UNSTEADY_HEAT_ELEMENT >
unsigned oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::nhistory_values_for_coordinate_projection () [inline], [virtual]
Number of positional history values (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 1094 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), and oomph::Node::position_time_stepper_pt().
nhistory_values_for_projection() [1/2]
template<class UNSTEADY_HEAT_ELEMENT >
unsigned oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::nhistory_values_for_projection (const unsigned & fld) [inline], [virtual]
Number of history values to be stored for fld-th field. (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 985 of file space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::Data::ntstorage().
nhistory_values_for_projection() [2/2]
template<class UNSTEADY_HEAT_ELEMENT >
unsigned oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::nhistory_values_for_projection (const unsigned & fld) [inline], [virtual]
Number of history values to be stored for fld-th field. (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 1067 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::Data::ntstorage().
nvalue_of_field() [1/2]
template<class UNSTEADY_HEAT_ELEMENT >
unsigned oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::nvalue_of_field (const unsigned & fld) [inline], [virtual]
Return number of values in field fld: One per node.
Implements oomph::ProjectableElementBase.
Definition at line 1121 of file space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::nnode().
nvalue_of_field() [2/2]
template<class UNSTEADY_HEAT_ELEMENT >
unsigned oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::nvalue_of_field (const unsigned & fld) [inline], [virtual]
Return number of values in field fld: One per node.
Implements oomph::ProjectableElementBase.
Definition at line 1203 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::nnode().
output() [1/2]
template<class UNSTEADY_HEAT_ELEMENT >
void oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output FE representation of soln: x,t,u or x,y,t,u at n_plot^(SPATIAL_DIM+1) plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 1177 of file space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::dim(), oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::nplot_points(), oomph::TimeStepper::ntstorage(), oomph::Node::position_time_stepper_pt(), s, t, oomph::FiniteElement::tecplot_zone_string(), oomph::Data::time_stepper_pt(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [2/2]
template<class UNSTEADY_HEAT_ELEMENT >
void oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output FE representation of soln: x,t,u or x,y,t,u at n_plot^(SPATIAL_DIM+1) plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 1259 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::dim(), oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::nplot_points(), oomph::TimeStepper::ntstorage(), oomph::Node::position_time_stepper_pt(), s, t, oomph::FiniteElement::tecplot_zone_string(), oomph::Data::time_stepper_pt(), and oomph::FiniteElement::write_tecplot_zone_footer().
The documentation for this class was generated from the following files:
space_time_unsteady_heat_elements.h
discontinuous_galerkin_space_time_unsteady_heat_elements.h