oomph::LinearElasticityEquations< DIM > Class Template Reference
#include <linear_elasticity_elements.h>
Public Member Functions
LinearElasticityEquations ()
Constructor.
unsigned required_nvalue (const unsigned &n) const
Number of values required at node n.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Return the residuals for the solid equations (the discretised principle of virtual displacements)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void get_stress (const Vector< double > &s, DenseMatrix< double > &sigma) const
Return the Cauchy stress tensor, as calculated from the elasticity tensor at specified local coordinate.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact solution x,y,[z],u,v,[w].
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact solution x,y,[z],u,v,[w] (unsteady version)
void output (std::ostream &outfile)
Output: x,y,[z],u,v,[w].
void output (std::ostream &outfile, const unsigned &n_plot)
Output: x,y,[z],u,v,[w].
void output (FILE *file_pt)
C-style output: x,y,[z],u,v,[w].
void output (FILE *file_pt, const unsigned &n_plot)
Output: x,y,[z],u,v,[w].
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of displacement solution over element.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of displacement solution over element (unsteady version)
Private Member Functions
virtual void fill_in_generic_contribution_to_residuals_linear_elasticity (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Private helper function to compute residuals and (if requested via flag) also the Jacobian matrix.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::LinearElasticityEquations< DIM >
A class for elements that solve the equations of linear elasticity in cartesian coordinates.
Definition at line 378 of file linear_elasticity_elements.h.
Constructor & Destructor Documentation
LinearElasticityEquations()
template<unsigned DIM>
oomph::LinearElasticityEquations< DIM >::LinearElasticityEquations () [inline]
Constructor.
Definition at line 383 of file linear_elasticity_elements.h.
Member Function Documentation
compute_error() [1/2]
template<unsigned DIM>
void oomph::LinearElasticityEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of displacement solution over element.
Validate against exact velocity solution Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Reimplemented from oomph::FiniteElement.
Definition at line 568 of file linear_elasticity_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
compute_error() [2/2]
template<unsigned DIM>
void oomph::LinearElasticityEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [virtual]
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of displacement solution over element (unsteady version)
Validate against exact velocity solution Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element. Unsteady version
Reimplemented from oomph::FiniteElement.
Definition at line 647 of file linear_elasticity_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
fill_in_contribution_to_jacobian()
template<unsigned DIM>
void oomph::LinearElasticityEquations< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
The jacobian is calculated by finite differences by default, We need only to take finite differences w.r.t. positional variables For this element
Reimplemented from oomph::FiniteElement.
Definition at line 402 of file linear_elasticity_elements.h.
References oomph::LinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity().
fill_in_contribution_to_residuals()
template<unsigned DIM>
void oomph::LinearElasticityEquations< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Return the residuals for the solid equations (the discretised principle of virtual displacements)
Reimplemented from oomph::GeneralisedElement.
Definition at line 393 of file linear_elasticity_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, oomph::LinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity(), and residuals().
fill_in_generic_contribution_to_residuals_linear_elasticity()
template<unsigned DIM>
void oomph::LinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [private], [virtual]
Private helper function to compute residuals and (if requested via flag) also the Jacobian matrix.
Compute the residuals for the linear elasticity equations in cartesian coordinates. Flag indicates if we want Jacobian too.
Reimplemented in oomph::RefineableLinearElasticityEquations< DIM >.
Definition at line 190 of file linear_elasticity_elements.cc.
References a(), oomph::QuadTreeNames::E, i, residuals(), s, and oomph::QuadTreeNames::W.
Referenced by oomph::LinearElasticityEquations< DIM >::fill_in_contribution_to_jacobian(), and oomph::LinearElasticityEquations< DIM >::fill_in_contribution_to_residuals().
get_stress()
template<unsigned DIM>
void oomph::LinearElasticityEquations< DIM >::get_stress (const Vector< double > & s, DenseMatrix< double > & stress) const [virtual]
Return the Cauchy stress tensor, as calculated from the elasticity tensor at specified local coordinate.
Compute the Cauchy stress tensor at local coordinate s for displacement formulation.
Implements oomph::LinearElasticityEquationsBase< DIM >.
Definition at line 145 of file linear_elasticity_elements.cc.
References oomph::QuadTreeNames::E, i, oomph::DenseMatrix< T >::ncol(), oomph::DenseMatrix< T >::nrow(), and s.
output() [1/4]
template<unsigned DIM>
void oomph::LinearElasticityEquations< DIM >::output (FILE * file_pt) [inline], [virtual]
C-style output: x,y,[z],u,v,[w].
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QLinearElasticityElement< DIM, NNODE_1D >, oomph::QLinearElasticityElement< DIM, 2 >, and oomph::TLinearElasticityElement< DIM, NNODE_1D >.
Definition at line 438 of file linear_elasticity_elements.h.
References oomph::LinearElasticityEquations< DIM >::output().
output() [2/4]
template<unsigned DIM>
void oomph::LinearElasticityEquations< DIM >::output (FILE * file_pt, const unsigned & n_plot) [virtual]
Output: x,y,[z],u,v,[w].
C-style output: x,y,[z],u,v,[w].
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QLinearElasticityElement< DIM, NNODE_1D >, oomph::QLinearElasticityElement< DIM, 2 >, and oomph::TLinearElasticityElement< DIM, NNODE_1D >.
Definition at line 526 of file linear_elasticity_elements.cc.
References i, and s.
output() [3/4]
template<unsigned DIM>
void oomph::LinearElasticityEquations< DIM >::output (std::ostream & outfile) [inline], [virtual]
Output: x,y,[z],u,v,[w].
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QLinearElasticityElement< DIM, NNODE_1D >, oomph::QLinearElasticityElement< DIM, 2 >, and oomph::TLinearElasticityElement< DIM, NNODE_1D >.
Definition at line 427 of file linear_elasticity_elements.h.
Referenced by oomph::TLinearElasticityElement< DIM, NNODE_1D >::output(), oomph::LinearElasticityEquations< DIM >::output(), and oomph::QLinearElasticityElement< DIM, 2 >::output().
output() [4/4]
template<unsigned DIM>
void oomph::LinearElasticityEquations< DIM >::output (std::ostream & outfile, const unsigned & n_plot) [virtual]
Output: x,y,[z],u,v,[w].
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TLinearElasticityElement< DIM, NNODE_1D >, oomph::QLinearElasticityElement< DIM, NNODE_1D >, and oomph::QLinearElasticityElement< DIM, 2 >.
Definition at line 480 of file linear_elasticity_elements.cc.
References i, s, and u().
output_fct() [1/2]
template<unsigned DIM>
void oomph::LinearElasticityEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact solution x,y,[z],u,v,[w] (unsteady version)
Reimplemented from oomph::FiniteElement.
Definition at line 428 of file linear_elasticity_elements.cc.
References i, and s.
output_fct() [2/2]
template<unsigned DIM>
void oomph::LinearElasticityEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact solution x,y,[z],u,v,[w].
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QLinearElasticityElement< DIM, NNODE_1D >, and oomph::QLinearElasticityElement< DIM, 2 >.
Definition at line 377 of file linear_elasticity_elements.cc.
References i, and s.
Referenced by oomph::QLinearElasticityElement< DIM, 2 >::output_fct().
required_nvalue()
template<unsigned DIM>
unsigned oomph::LinearElasticityEquations< DIM >::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values required at node n.
Reimplemented from oomph::FiniteElement.
Definition at line 386 of file linear_elasticity_elements.h.
The documentation for this class was generated from the following files:
linear_elasticity_elements.h
linear_elasticity_elements.cc