oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT > Class Template Reference
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
#include <fourier_decomposed_helmholtz_bc_elements.h>
Public Member Functions
FourierDecomposedHelmholtzDtNMesh (const double &outer_radius, const unsigned &n_terms)
Constructor: Specify radius of outer boundary and number of terms used in the computation of the gamma integral.
void setup_gamma ()
Compute and store the gamma integral at all integration points of the constituent elements.
Vector< std::complex< double > > & gamma_at_gauss_point (FiniteElement *el_pt)
Gamma integral evaluated at Gauss points for specified element.
Vector< std::map< unsigned, std::complex< double > > > & d_gamma_at_gauss_point (FiniteElement *el_pt)
Derivative of Gamma integral w.r.t global unknown, evaluated at Gauss points for specified element.
double & outer_radius ()
The outer radius.
unsigned & n_terms ()
Number of terms used in the computation of the gamma integral.
Private Attributes
double Outer_radius
Outer radius.
unsigned N_terms
Number of terms used in the Gamma computation.
std::map< FiniteElement *, Vector< std::complex< double > > > Gamma_at_gauss_point
Container to store the gamma integral for given Gauss point and element.
std::map< FiniteElement *, Vector< std::map< unsigned, std::complex< double > > > > D_Gamma_at_gauss_point
Container to store the derivate of Gamma integral w.r.t global unknown evaluated at Gauss points for specified element.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
================================================================= Mesh for DtN boundary condition elements -- provides functionality to apply Sommerfeld radiation condtion
via DtN BC.
Definition at line 350 of file fourier_decomposed_helmholtz_bc_elements.h.
Constructor & Destructor Documentation
FourierDecomposedHelmholtzDtNMesh()
template<class ELEMENT >
oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::FourierDecomposedHelmholtzDtNMesh (const double & outer_radius, const unsigned & n_terms) [inline]
Constructor: Specify radius of outer boundary and number of terms used in the computation of the gamma integral.
Definition at line 355 of file fourier_decomposed_helmholtz_bc_elements.h.
Member Function Documentation
d_gamma_at_gauss_point()
template<class ELEMENT >
Vector< std::map< unsigned, std::complex< double > > > & oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::d_gamma_at_gauss_point (FiniteElement * el_pt) [inline]
Derivative of Gamma integral w.r.t global unknown, evaluated at Gauss points for specified element.
Definition at line 374 of file fourier_decomposed_helmholtz_bc_elements.h.
References oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::D_Gamma_at_gauss_point.
gamma_at_gauss_point()
template<class ELEMENT >
Vector< std::complex< double > > & oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::gamma_at_gauss_point (FiniteElement * el_pt) [inline]
Gamma integral evaluated at Gauss points for specified element.
Definition at line 367 of file fourier_decomposed_helmholtz_bc_elements.h.
References oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::Gamma_at_gauss_point.
n_terms()
template<class ELEMENT >
unsigned & oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::n_terms () [inline]
Number of terms used in the computation of the gamma integral.
Definition at line 388 of file fourier_decomposed_helmholtz_bc_elements.h.
References oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::N_terms.
outer_radius()
template<class ELEMENT >
double & oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::outer_radius () [inline]
The outer radius.
Definition at line 381 of file fourier_decomposed_helmholtz_bc_elements.h.
References oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::Outer_radius.
setup_gamma()
template<class ELEMENT >
void oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::setup_gamma
Compute and store the gamma integral at all integration points of the constituent elements.
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
================================================================ Compute and store the gamma integral and derivates of the mesh's constituent elements Imaginary unit
Definition at line 936 of file fourier_decomposed_helmholtz_bc_elements.h.
References oomph::FaceElement::bulk_element_pt(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::compute_gamma_contribution(), oomph::FiniteElement::dim(), e, oomph::GeneralisedElement::eqn_number(), oomph::Legendre_functions_helper::factorial(), i, oomph::MathematicalConstants::I(), oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), oomph::MathematicalConstants::Pi, s, oomph::ToleranceForFourierDecomposedHelmholtzOuterBoundary::Tol, oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::u_index_fourier_decomposed_helmholtz(), and oomph::Node::x().
Member Data Documentation
D_Gamma_at_gauss_point
template<class ELEMENT >
std::map<FiniteElement*, Vector<std::map<unsigned, std::complex<double> > > > oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::D_Gamma_at_gauss_point [private]
Container to store the derivate of Gamma integral w.r.t global unknown evaluated at Gauss points for specified element.
Definition at line 409 of file fourier_decomposed_helmholtz_bc_elements.h.
Referenced by oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::d_gamma_at_gauss_point().
Gamma_at_gauss_point
template<class ELEMENT >
std::map<FiniteElement*, Vector<std::complex<double> > > oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::Gamma_at_gauss_point [private]
Container to store the gamma integral for given Gauss point and element.
Definition at line 403 of file fourier_decomposed_helmholtz_bc_elements.h.
Referenced by oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::gamma_at_gauss_point().
N_terms
template<class ELEMENT >
unsigned oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::N_terms [private]
Number of terms used in the Gamma computation.
Definition at line 398 of file fourier_decomposed_helmholtz_bc_elements.h.
Referenced by oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::n_terms().
Outer_radius
template<class ELEMENT >
double oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::Outer_radius [private]
Outer radius.
Definition at line 395 of file fourier_decomposed_helmholtz_bc_elements.h.
Referenced by oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::outer_radius().
The documentation for this class was generated from the following file:
fourier_decomposed_helmholtz_bc_elements.h