oomph::RefineableQSphericalTaylorHoodElement Class Reference
Refineable version of Spherical Quad Taylor Hood elements. (note that unlike the cartesian version this is not scale-able to higher dimensions!)
#include <refineable_spherical_navier_stokes_elements.h>
Public Member Functions
RefineableQSphericalTaylorHoodElement ()
Constructor:
unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at node n.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: 4 (3 velocities + 1 pressure)
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: empty.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void further_setup_hanging_nodes ()
Perform additional hanging node procedures for variables that are not interpolated by all nodes. The pressures are stored at the 3rd location in each node.
Node * interpolating_node_pt (const unsigned &n, const int &n_value)
The velocities are isoparametric and so the `nodes` interpolating the velocities are the geometric nodes. The pressure `nodes` are a subset of the nodes, so when n_value==3, the n-th pressure node is returned.
double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &n_value)
The pressure nodes are the corner nodes, so when n_value==DIM, the fraction is the same as the 1d node number, 0 or 1.
Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &n_value)
The velocity nodes are the same as the geometric nodes. The pressure nodes must be calculated by using the same methods as the geometric nodes, but by recalling that there are only two pressure nodes per edge.
unsigned ninterpolating_node_1d (const int &n_value)
The number of 1d pressure nodes is 2, the number of 1d velocity nodes is the same as the number of 1d geometric nodes.
unsigned ninterpolating_node (const int &n_value)
The number of pressure nodes is 4. The number of velocity nodes is the same as the number of geometric nodes.
void interpolating_basis (const Vector< double > &s, Shape &psi, const int &n_value) const
The basis interpolating the pressure is given by pshape(). / The basis interpolating the velocity is shape().
Private Member Functions
Node * pressure_node_pt (const unsigned &n_p)
Pointer to n_p-th pressure node.
void unpin_elemental_pressure_dofs ()
Unpin all pressure dofs.
void pin_elemental_redundant_nodal_pressure_dofs ()
Unpin the proper nodal pressure dofs.
Additional Inherited Members
Detailed Description
Refineable version of Spherical Quad Taylor Hood elements. (note that unlike the cartesian version this is not scale-able to higher dimensions!)
Definition at line 219 of file refineable_spherical_navier_stokes_elements.h.
Constructor & Destructor Documentation
RefineableQSphericalTaylorHoodElement()
oomph::RefineableQSphericalTaylorHoodElement::RefineableQSphericalTaylorHoodElement () [inline]
Constructor:
Definition at line 269 of file refineable_spherical_navier_stokes_elements.h.
Member Function Documentation
further_setup_hanging_nodes()
void oomph::RefineableQSphericalTaylorHoodElement::further_setup_hanging_nodes () [inline], [virtual]
Perform additional hanging node procedures for variables that are not interpolated by all nodes. The pressures are stored at the 3rd location in each node.
Implements oomph::RefineableQElement< 2 >.
Definition at line 377 of file refineable_spherical_navier_stokes_elements.h.
References oomph::RefineableQElement< 2 >::setup_hang_for_value().
get_interpolated_values() [1/2]
void oomph::RefineableQSphericalTaylorHoodElement::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 338 of file refineable_spherical_navier_stokes_elements.h.
References i, oomph::SphericalNavierStokesEquations::interpolated_p_spherical_nst(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), t, and oomph::SphericalNavierStokesEquations::u_index_spherical_nst().
get_interpolated_values() [2/2]
void oomph::RefineableQSphericalTaylorHoodElement::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 318 of file refineable_spherical_navier_stokes_elements.h.
References i, oomph::SphericalNavierStokesEquations::interpolated_p_spherical_nst(), oomph::SphericalNavierStokesEquations::interpolated_u_spherical_nst(), and s.
get_interpolating_node_at_local_coordinate()
Node * oomph::RefineableQSphericalTaylorHoodElement::get_interpolating_node_at_local_coordinate (const Vector< double > & s, const int & n_value) [inline], [virtual]
The velocity nodes are the same as the geometric nodes. The pressure nodes must be calculated by using the same methods as the geometric nodes, but by recalling that there are only two pressure nodes per edge.
Construct the general pressure index from the components.
Reimplemented from oomph::RefineableElement.
Definition at line 423 of file refineable_spherical_navier_stokes_elements.h.
References oomph::FiniteElement::get_node_at_local_coordinate(), i, oomph::FiniteElement::Node_location_tolerance, oomph::FiniteElement::node_pt(), oomph::QSphericalTaylorHoodElement::Pconv, and s.
interpolating_basis()
void oomph::RefineableQSphericalTaylorHoodElement::interpolating_basis (const Vector< double > & s, Shape & psi, const int & n_value) const [inline], [virtual]
The basis interpolating the pressure is given by pshape(). / The basis interpolating the velocity is shape().
Reimplemented from oomph::RefineableElement.
Definition at line 513 of file refineable_spherical_navier_stokes_elements.h.
References oomph::QSphericalTaylorHoodElement::pshape_spherical_nst(), and oomph::FiniteElement::shape().
interpolating_node_pt()
Node * oomph::RefineableQSphericalTaylorHoodElement::interpolating_node_pt (const unsigned & n, const int & n_value) [inline], [virtual]
The velocities are isoparametric and so the `nodes` interpolating the velocities are the geometric nodes. The pressure `nodes` are a subset of the nodes, so when n_value==3, the n-th pressure node is returned.
Reimplemented from oomph::RefineableElement.
Definition at line 386 of file refineable_spherical_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::QSphericalTaylorHoodElement::Pconv.
local_one_d_fraction_of_interpolating_node()
double oomph::RefineableQSphericalTaylorHoodElement::local_one_d_fraction_of_interpolating_node (const unsigned & n1d, const unsigned & i, const int & n_value) [inline], [virtual]
The pressure nodes are the corner nodes, so when n_value==DIM, the fraction is the same as the 1d node number, 0 or 1.
Reimplemented from oomph::RefineableElement.
Definition at line 403 of file refineable_spherical_navier_stokes_elements.h.
References i, and oomph::FiniteElement::local_one_d_fraction_of_node().
ncont_interpolated_values()
unsigned oomph::RefineableQSphericalTaylorHoodElement::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values: 4 (3 velocities + 1 pressure)
Implements oomph::RefineableElement.
Definition at line 287 of file refineable_spherical_navier_stokes_elements.h.
ninterpolating_node()
unsigned oomph::RefineableQSphericalTaylorHoodElement::ninterpolating_node (const int & n_value) [inline], [virtual]
The number of pressure nodes is 4. The number of velocity nodes is the same as the number of geometric nodes.
Reimplemented from oomph::RefineableElement.
Definition at line 499 of file refineable_spherical_navier_stokes_elements.h.
References oomph::FiniteElement::nnode().
ninterpolating_node_1d()
unsigned oomph::RefineableQSphericalTaylorHoodElement::ninterpolating_node_1d (const int & n_value) [inline], [virtual]
The number of 1d pressure nodes is 2, the number of 1d velocity nodes is the same as the number of 1d geometric nodes.
Reimplemented from oomph::RefineableElement.
Definition at line 485 of file refineable_spherical_navier_stokes_elements.h.
References oomph::FiniteElement::nnode_1d().
nrecovery_order()
unsigned oomph::RefineableQSphericalTaylorHoodElement::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 297 of file refineable_spherical_navier_stokes_elements.h.
nvertex_node()
unsigned oomph::RefineableQSphericalTaylorHoodElement::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 303 of file refineable_spherical_navier_stokes_elements.h.
References oomph::FiniteElement::nvertex_node().
pin_elemental_redundant_nodal_pressure_dofs()
void oomph::RefineableQSphericalTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs () [inline], [private], [virtual]
Unpin the proper nodal pressure dofs.
Reimplemented from oomph::RefineableSphericalNavierStokesEquations.
Definition at line 244 of file refineable_spherical_navier_stokes_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::QSphericalTaylorHoodElement::npres_spherical_nst(), oomph::QSphericalTaylorHoodElement::p_nodal_index_spherical_nst(), and oomph::QSphericalTaylorHoodElement::Pconv.
pressure_node_pt()
Node * oomph::RefineableQSphericalTaylorHoodElement::pressure_node_pt (const unsigned & n_p) [inline], [private], [virtual]
Pointer to n_p-th pressure node.
Reimplemented from oomph::RefineableSphericalNavierStokesEquations.
Definition at line 226 of file refineable_spherical_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::QSphericalTaylorHoodElement::Pconv.
rebuild_from_sons()
void oomph::RefineableQSphericalTaylorHoodElement::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
Rebuild from sons: empty.
Implements oomph::RefineableElement.
Definition at line 293 of file refineable_spherical_navier_stokes_elements.h.
required_nvalue()
unsigned oomph::RefineableQSphericalTaylorHoodElement::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values (pinned or dofs) required at node n.
Reimplemented from oomph::QSphericalTaylorHoodElement.
Definition at line 280 of file refineable_spherical_navier_stokes_elements.h.
unpin_elemental_pressure_dofs()
void oomph::RefineableQSphericalTaylorHoodElement::unpin_elemental_pressure_dofs () [inline], [private], [virtual]
Unpin all pressure dofs.
Implements oomph::RefineableSphericalNavierStokesEquations.
Definition at line 232 of file refineable_spherical_navier_stokes_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::QSphericalTaylorHoodElement::p_nodal_index_spherical_nst().
vertex_node_pt()
Node * oomph::RefineableQSphericalTaylorHoodElement::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 309 of file refineable_spherical_navier_stokes_elements.h.
References oomph::FiniteElement::vertex_node_pt().
The documentation for this class was generated from the following file:
refineable_spherical_navier_stokes_elements.h