oomph::DummyFaceElement< ELEMENT > Class Template Reference
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
#include <elements.h>
Public Member Functions
DummyFaceElement (FiniteElement *const &element_pt, const int &face_index)
Constructor, which takes a `bulk` element and the face index.
DummyFaceElement ()
Constructor.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default.
void output (std::ostream &outfile)
Output nodal coordinates.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at n_plot points.
void output (FILE *file_pt)
C-style output.
void output (FILE *file_pt, const unsigned &n_plot)
C_style output at n_plot points.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::DummyFaceElement< ELEMENT >
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Dummy FaceElement for use with purely geometric operations such as mesh generation.
Definition at line 5012 of file elements.h.
Constructor & Destructor Documentation
DummyFaceElement() [1/2]
template<class ELEMENT >
oomph::DummyFaceElement< ELEMENT >::DummyFaceElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the face index.
Definition at line 5018 of file elements.h.
References oomph::FiniteElement::build_face_element(), and oomph::FaceElement::face_index().
DummyFaceElement() [2/2]
template<class ELEMENT >
oomph::DummyFaceElement< ELEMENT >::DummyFaceElement () [inline]
Constructor.
Definition at line 5028 of file elements.h.
Member Function Documentation
output() [1/4]
template<class ELEMENT >
void oomph::DummyFaceElement< ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C-style output.
Reimplemented from oomph::FiniteElement.
Definition at line 5065 of file elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<class ELEMENT >
void oomph::DummyFaceElement< ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C_style output at n_plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 5071 of file elements.h.
References oomph::FiniteElement::output().
output() [3/4]
template<class ELEMENT >
void oomph::DummyFaceElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output nodal coordinates.
Reimplemented from oomph::FiniteElement.
Definition at line 5042 of file elements.h.
References oomph::FiniteElement::dim(), i, oomph::Node::ndim(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::Node::x().
output() [4/4]
template<class ELEMENT >
void oomph::DummyFaceElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output at n_plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 5059 of file elements.h.
References oomph::FiniteElement::output().
zeta_nodal()
template<class ELEMENT >
double oomph::DummyFaceElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default.
Reimplemented from oomph::FaceElement.
Definition at line 5034 of file elements.h.
References i, and oomph::FaceElement::zeta_nodal().
The documentation for this class was generated from the following file:
elements.h