GeneralisedNewtonianQTaylorHoodElement< DIM > Class Template Reference
/////////////////////////////////////////////////////////////////////////
#include <generalised_newtonian_navier_stokes_elements.h>
Public Member Functions
GeneralisedNewtonianQTaylorHoodElement ()
Constructor, no internal data points.
virtual unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
virtual int p_nodal_index_nst () const
Set the value at which the pressure is stored in the nodes.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
double p_nst (const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
double p_nst (const unsigned &t, const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
unsigned npres_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs containing.
void identify_pressure_data (std::set< std::pair< Data *, unsigned > > &paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
unsigned ndof_types () const
Returns the number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity and pressure.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1.
void pshape_nst (const Vector< double > &s, Shape &psi) const
2D : Pressure shape functions
void pshape_nst (const Vector< double > &s, Shape &psi) const
3D : Pressure shape functions
Protected Member Functions
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
const unsigned Pconv [4]
const unsigned Pconv [8]
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
2D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
2D : Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
3D : Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
3D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
Static Protected Attributes
static const unsigned Pconv []
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Private Member Functions
const unsigned Initial_Nvalue [9]
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
const unsigned Initial_Nvalue [27]
Static Private Attributes
static const unsigned Initial_Nvalue []
Static array of ints to hold number of variables at node.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class GeneralisedNewtonianQTaylorHoodElement< DIM >
/////////////////////////////////////////////////////////////////////////
Taylor--Hood elements are Navier--Stokes elements with quadratic interpolation for velocities and positions and continuous linear pressure interpolation. They can be used within oomph-lib's block-preconditioning framework.
Definition at line 1863 of file generalised_newtonian_navier_stokes_elements.h.
Constructor & Destructor Documentation
GeneralisedNewtonianQTaylorHoodElement()
template<unsigned DIM>
GeneralisedNewtonianQTaylorHoodElement< DIM >::GeneralisedNewtonianQTaylorHoodElement () [inline]
Constructor, no internal data points.
Definition at line 1919 of file generalised_newtonian_navier_stokes_elements.h.
Member Function Documentation
dpshape_and_dptest_eulerian_nst() [1/3]
template<unsigned DIM>
double GeneralisedNewtonianQTaylorHoodElement< DIM >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
dpshape_and_dptest_eulerian_nst() [2/3]
double GeneralisedNewtonianQTaylorHoodElement< 2 >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
2D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 2105 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::OneDimLagrange::dshape< 2 >(), i, s, and oomph::OneDimLagrange::shape< 2 >().
dpshape_and_dptest_eulerian_nst() [3/3]
double GeneralisedNewtonianQTaylorHoodElement< 3 >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
3D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 2293 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::OneDimLagrange::dshape< 2 >(), i, s, and oomph::OneDimLagrange::shape< 2 >().
dshape_and_dtest_eulerian_at_knot_nst() [1/4]
template<unsigned DIM>
double GeneralisedNewtonianQTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
dshape_and_dtest_eulerian_at_knot_nst() [2/4]
double GeneralisedNewtonianQTaylorHoodElement< 2 >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
2D : Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 2169 of file generalised_newtonian_navier_stokes_elements.h.
References i.
dshape_and_dtest_eulerian_at_knot_nst() [3/4]
double GeneralisedNewtonianQTaylorHoodElement< 3 >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
3D : Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 2219 of file generalised_newtonian_navier_stokes_elements.h.
References i.
dshape_and_dtest_eulerian_at_knot_nst() [4/4]
template<unsigned DIM>
double GeneralisedNewtonianQTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 2080 of file generalised_newtonian_navier_stokes_elements.h.
dshape_and_dtest_eulerian_nst()
template<unsigned DIM>
double GeneralisedNewtonianQTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 2055 of file generalised_newtonian_navier_stokes_elements.h.
References s.
fix_pressure()
template<unsigned DIM>
void GeneralisedNewtonianQTaylorHoodElement< DIM >::fix_pressure (const unsigned & p_dof, const double & p_value) [inline], [virtual]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1973 of file generalised_newtonian_navier_stokes_elements.h.
get_dof_numbers_for_unknowns()
template<unsigned DIM>
void GeneralisedNewtonianQTaylorHoodElement< DIM >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1.
Create a list of pairs for all unknowns in this element, so the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Definition at line 2838 of file generalised_newtonian_navier_stokes_elements.cc.
identify_load_data()
template<unsigned DIM>
void GeneralisedNewtonianQTaylorHoodElement< DIM >::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data)
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Definition at line 2775 of file generalised_newtonian_navier_stokes_elements.cc.
References i.
identify_pressure_data()
template<unsigned DIM>
void GeneralisedNewtonianQTaylorHoodElement< DIM >::identify_pressure_data (std::set< std::pair< Data *, unsigned > > & paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all pressure values that affect the load computed in the get_load(...) function.
the pointer to a Data object and
the index of the value in that Data object
for pressure values that affect the load computed in the get_load(...) function.,
Definition at line 2811 of file generalised_newtonian_navier_stokes_elements.cc.
Initial_Nvalue() [1/2]
const unsigned GeneralisedNewtonianQTaylorHoodElement< 3 >::Initial_Nvalue [private]
Definition at line 2756 of file generalised_newtonian_navier_stokes_elements.cc.
Initial_Nvalue() [2/2]
const unsigned GeneralisedNewtonianQTaylorHoodElement< 2 >::Initial_Nvalue [private]
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Definition at line 2745 of file generalised_newtonian_navier_stokes_elements.cc.
ndof_types()
template<unsigned DIM>
unsigned GeneralisedNewtonianQTaylorHoodElement< DIM >::ndof_types () const [inline]
Returns the number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity and pressure.
Definition at line 2031 of file generalised_newtonian_navier_stokes_elements.h.
npres_nst()
template<unsigned DIM>
unsigned GeneralisedNewtonianQTaylorHoodElement< DIM >::npres_nst () const [inline], [virtual]
Return number of pressure values.
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1967 of file generalised_newtonian_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::identify_load_data(), and oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs().
output() [1/4]
template<unsigned DIM>
void GeneralisedNewtonianQTaylorHoodElement< DIM >::output (FILE * file_pt) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 2017 of file generalised_newtonian_navier_stokes_elements.h.
References GeneralisedNewtonianNavierStokesEquations< DIM >::output().
output() [2/4]
template<unsigned DIM>
void GeneralisedNewtonianQTaylorHoodElement< DIM >::output (FILE * file_pt, const unsigned & nplot) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 2023 of file generalised_newtonian_navier_stokes_elements.h.
References GeneralisedNewtonianNavierStokesEquations< DIM >::output().
output() [3/4]
template<unsigned DIM>
void GeneralisedNewtonianQTaylorHoodElement< DIM >::output (std::ostream & outfile) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 2005 of file generalised_newtonian_navier_stokes_elements.h.
References GeneralisedNewtonianNavierStokesEquations< DIM >::output().
output() [4/4]
template<unsigned DIM>
void GeneralisedNewtonianQTaylorHoodElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 2011 of file generalised_newtonian_navier_stokes_elements.h.
References GeneralisedNewtonianNavierStokesEquations< DIM >::output().
p_local_eqn()
template<unsigned DIM>
int GeneralisedNewtonianQTaylorHoodElement< DIM >::p_local_eqn (const unsigned & n) const [inline]
Return the local equation numbers for the pressure values.
Definition at line 1947 of file generalised_newtonian_navier_stokes_elements.h.
p_nodal_index_nst()
template<unsigned DIM>
virtual int GeneralisedNewtonianQTaylorHoodElement< DIM >::p_nodal_index_nst () const [inline], [virtual]
Set the value at which the pressure is stored in the nodes.
Reimplemented from GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1941 of file generalised_newtonian_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::further_setup_hanging_nodes(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::identify_load_data(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs(), and oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::unpin_elemental_pressure_dofs().
p_nst() [1/2]
template<unsigned DIM>
double GeneralisedNewtonianQTaylorHoodElement< DIM >::p_nst (const unsigned & n_p) const [inline], [virtual]
Access function for the pressure values at local pressure node n_p (const version)
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1954 of file generalised_newtonian_navier_stokes_elements.h.
p_nst() [2/2]
template<unsigned DIM>
double GeneralisedNewtonianQTaylorHoodElement< DIM >::p_nst (const unsigned & t, const unsigned & n_p) const [inline], [virtual]
Access function for the pressure values at local pressure node n_p (const version)
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1961 of file generalised_newtonian_navier_stokes_elements.h.
References t.
Pconv() [1/2]
const unsigned GeneralisedNewtonianQTaylorHoodElement< 2 >::Pconv [protected]
Definition at line 2750 of file generalised_newtonian_navier_stokes_elements.cc.
Pconv() [2/2]
const unsigned GeneralisedNewtonianQTaylorHoodElement< 3 >::Pconv [protected]
Definition at line 2762 of file generalised_newtonian_navier_stokes_elements.cc.
pshape_nst() [1/4]
template<unsigned DIM>
void GeneralisedNewtonianQTaylorHoodElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Pressure shape functions at local coordinate s.
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Referenced by oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::interpolating_basis().
pshape_nst() [2/4]
void GeneralisedNewtonianQTaylorHoodElement< 2 >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
2D : Pressure shape functions
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 2264 of file generalised_newtonian_navier_stokes_elements.h.
References i, s, and oomph::OneDimLagrange::shape< 2 >().
pshape_nst() [3/4]
void GeneralisedNewtonianQTaylorHoodElement< 3 >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
3D : Pressure shape functions
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 2357 of file generalised_newtonian_navier_stokes_elements.h.
References i, s, and oomph::OneDimLagrange::shape< 2 >().
pshape_nst() [4/4]
template<unsigned DIM>
void GeneralisedNewtonianQTaylorHoodElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [virtual]
Pressure shape and test functions at local coordinte s.
Pressure shape and test functions.
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 2388 of file generalised_newtonian_navier_stokes_elements.h.
References s.
required_nvalue()
template<unsigned DIM>
virtual unsigned GeneralisedNewtonianQTaylorHoodElement< DIM >::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
Reimplemented in oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >.
Definition at line 1926 of file generalised_newtonian_navier_stokes_elements.h.
Member Data Documentation
Initial_Nvalue
template<unsigned DIM>
const unsigned GeneralisedNewtonianQTaylorHoodElement< DIM >::Initial_Nvalue[] [static], [private]
Static array of ints to hold number of variables at node.
Definition at line 1869 of file generalised_newtonian_navier_stokes_elements.h.
Pconv
template<unsigned DIM>
const unsigned GeneralisedNewtonianQTaylorHoodElement< DIM >::Pconv[] [static], [protected]
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Definition at line 1874 of file generalised_newtonian_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::pressure_node_pt().
The documentation for this class was generated from the following files:
generalised_newtonian_navier_stokes_elements.h
generalised_newtonian_navier_stokes_elements.cc