oomph::FishMesh< ELEMENT > Class Template Reference
Fish shaped mesh. The geometry is defined by the Domain object FishDomain.
#include <fish_mesh.template.h>
Public Member Functions
FishMesh (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass pointer to timestepper (defaults to the (Steady) default timestepper defined in Mesh)
FishMesh (GeomObject *back_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass pointer GeomObject that defines the fish's back and pointer to timestepper (defaults to the (Steady) default timestepper defined in Mesh)
virtual ~FishMesh ()
Destructor: Kill the geom object that represents the fish's back (if necessary)
GeomObject *& fish_back_pt ()
Access function to geom object that represents the fish's back.
FishDomain *& domain_pt ()
Access function to FishDomain.
Protected Types
enum { Lower_body
, Upper_body
, Lower_fin
, Upper_fin
 }
Remesh function ids.
Protected Member Functions
void build_mesh (TimeStepper *time_stepper_pt)
Build the mesh, using the geometric object identified by Back_pt.
Protected Attributes
GeomObject * Back_pt
Pointer to fish back.
FishDomain * Domain_pt
Pointer to domain.
bool Must_kill_fish_back
Do I need to kill the fish back geom object?
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::FishMesh< ELEMENT >
Fish shaped mesh. The geometry is defined by the Domain object FishDomain.
Definition at line 54 of file fish_mesh.template.h.
Member Enumeration Documentation
anonymous enum
template<class ELEMENT >
anonymous enum [protected]
Remesh function ids.
Enumerator
Lower_body
Upper_body
Lower_fin
Upper_fin
Definition at line 93 of file fish_mesh.template.h.
Constructor & Destructor Documentation
FishMesh() [1/2]
template<class ELEMENT >
oomph::FishMesh< ELEMENT >::FishMesh (TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass pointer to timestepper (defaults to the (Steady) default timestepper defined in Mesh)
Constructor: Pass pointer to timestepper. (defaults to (Steady) default timestepper defined in Mesh)
Definition at line 39 of file fish_mesh.template.cc.
FishMesh() [2/2]
template<class ELEMENT >
oomph::FishMesh< ELEMENT >::FishMesh (GeomObject * back_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass pointer GeomObject that defines the fish's back and pointer to timestepper (defaults to the (Steady) default timestepper defined in Mesh)
Constructor: Pass pointer GeomObject that defines the fish's back and pointer to timestepper. (defaults to (Steady) default timestepper defined in Mesh)
Definition at line 64 of file fish_mesh.template.cc.
References oomph::FishMesh< ELEMENT >::build_mesh(), and oomph::FishMesh< ELEMENT >::Must_kill_fish_back.
 FishMesh()
template<class ELEMENT >
virtual oomph::FishMesh< ELEMENT >::~FishMesh () [inline], [virtual]
Destructor: Kill the geom object that represents the fish's back (if necessary)
Definition at line 69 of file fish_mesh.template.h.
References oomph::FishMesh< ELEMENT >::Back_pt, and oomph::FishMesh< ELEMENT >::Must_kill_fish_back.
Member Function Documentation
build_mesh()
template<class ELEMENT >
void oomph::FishMesh< ELEMENT >::build_mesh (TimeStepper * time_stepper_pt) [protected]
Build the mesh, using the geometric object identified by Back_pt.
Build the mesh, using the geometric object that defines the fish's back.
Definition at line 83 of file fish_mesh.template.cc.
References e, i, oomph::oomph_info, s, oomph::FiniteElement::set_macro_elem_pt(), and oomph::Node::x().
Referenced by oomph::FishMesh< ELEMENT >::FishMesh().
domain_pt()
template<class ELEMENT >
FishDomain*& oomph::FishMesh< ELEMENT >::domain_pt () [inline]
Access function to FishDomain.
Definition at line 86 of file fish_mesh.template.h.
References oomph::FishMesh< ELEMENT >::Domain_pt.
Referenced by oomph::MacroElementNodeUpdateRefineableFishMesh< ELEMENT >::MacroElementNodeUpdateRefineableFishMesh().
fish_back_pt()
template<class ELEMENT >
GeomObject*& oomph::FishMesh< ELEMENT >::fish_back_pt () [inline]
Access function to geom object that represents the fish's back.
Definition at line 79 of file fish_mesh.template.h.
References oomph::FishMesh< ELEMENT >::Back_pt.
Member Data Documentation
Back_pt
template<class ELEMENT >
GeomObject* oomph::FishMesh< ELEMENT >::Back_pt [protected]
Pointer to fish back.
Definition at line 105 of file fish_mesh.template.h.
Referenced by oomph::FishMesh< ELEMENT >::fish_back_pt(), oomph::MacroElementNodeUpdateRefineableFishMesh< ELEMENT >::MacroElementNodeUpdateRefineableFishMesh(), oomph::AlgebraicFishMesh< ELEMENT >::update_node_update(), and oomph::FishMesh< ELEMENT >::~FishMesh().
Domain_pt
template<class ELEMENT >
FishDomain* oomph::FishMesh< ELEMENT >::Domain_pt [protected]
Pointer to domain.
Definition at line 108 of file fish_mesh.template.h.
Referenced by oomph::FishMesh< ELEMENT >::domain_pt(), and oomph::AlgebraicFishMesh< ELEMENT >::update_node_update().
Must_kill_fish_back
template<class ELEMENT >
bool oomph::FishMesh< ELEMENT >::Must_kill_fish_back [protected]
Do I need to kill the fish back geom object?
Definition at line 111 of file fish_mesh.template.h.
Referenced by oomph::FishMesh< ELEMENT >::FishMesh(), and oomph::FishMesh< ELEMENT >::~FishMesh().
The documentation for this class was generated from the following files:
fish_mesh.template.h
fish_mesh.template.cc