oomph::GZipReader Class Reference
#include <gzip_reader.h>
Public Member Functions
GZipReader ()
GZipReader (const std::string &filename, const unsigned &chunk_size=256)
~GZipReader ()
void open (const std::string &filename)
void close ()
bool is_open () const
Packet getline ()
std::vector< std::string > read_all ()
Private Attributes
gzFile Gzip_file
unsigned Chunk_size
Detailed Description
Definition at line 54 of file gzip_reader.h.
Constructor & Destructor Documentation
GZipReader() [1/2]
oomph::GZipReader::GZipReader ()
Definition at line 41 of file gzip_reader.cc.
GZipReader() [2/2]
oomph::GZipReader::GZipReader (const std::string & filename, const unsigned & chunk_size = 256)
Definition at line 48 of file gzip_reader.cc.
References is_open(), and open().
~GZipReader()
oomph::GZipReader::~GZipReader ()
Definition at line 65 of file gzip_reader.cc.
References close(), and is_open().
Member Function Documentation
close()
void oomph::GZipReader::close ()
Definition at line 87 of file gzip_reader.cc.
References Gzip_file, and is_open().
Referenced by getline(), and ~GZipReader().
getline()
Packet oomph::GZipReader::getline ()
Definition at line 119 of file gzip_reader.cc.
References Chunk_size, close(), Gzip_file, and is_open().
Referenced by read_all().
is_open()
bool oomph::GZipReader::is_open () const
Definition at line 103 of file gzip_reader.cc.
References Gzip_file.
Referenced by close(), getline(), GZipReader(), read_all(), and ~GZipReader().
open()
void oomph::GZipReader::open (const std::string & filename)
Definition at line 78 of file gzip_reader.cc.
References Gzip_file.
Referenced by GZipReader().
read_all()
std::vector< std::string > oomph::GZipReader::read_all ()
Definition at line 180 of file gzip_reader.cc.
References oomph::Packet::found, getline(), and is_open().
Referenced by oomph::gzip_load().
Member Data Documentation
Chunk_size
unsigned oomph::GZipReader::Chunk_size [private]
Definition at line 68 of file gzip_reader.h.
Referenced by getline().
Gzip_file
gzFile oomph::GZipReader::Gzip_file [private]
Definition at line 67 of file gzip_reader.h.
Referenced by close(), getline(), is_open(), and open().
The documentation for this class was generated from the following files:
gzip_reader.h
gzip_reader.cc