oomph::NavierStokesSpaceTimeTractionElement< ELEMENT > Class Template Reference
A class for elements that allow the imposition of an applied traction to the Navier--Stokes equations The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
#include <discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h>
Public Member Functions
NavierStokesSpaceTimeTractionElement (FiniteElement *const &element_pt, const int &face_index, const bool &called_from_refineable_constructor=false)
Constructor, which takes a `bulk` element and the value of the index and its limit.
~NavierStokesSpaceTimeTractionElement ()
Destructor should not delete anything.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
This function returns just the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the jacobian.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,[z],u,v,[w],p in tecplot format.
NavierStokesSpaceTimeTractionElement (FiniteElement *const &element_pt, const int &face_index, const bool &called_from_refineable_constructor=false)
Constructor, which takes a `bulk` element and the value of the index and its limit.
~NavierStokesSpaceTimeTractionElement ()
Destructor should not delete anything.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
This function returns just the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the jacobian.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,[z],u,v,[w],p in tecplot format.
NavierStokesSpaceTimeTractionElement (FiniteElement *const &element_pt, const int &face_index, const bool &called_from_refineable_constructor=false)
Constructor, which takes a `bulk` element and the value of the index and its limit.
~NavierStokesSpaceTimeTractionElement ()
Destructor should not delete anything.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
This function returns just the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the jacobian.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,[z],u,v,[w],p in tecplot format.
Public Attributes
void(*&)(const double &t, const Vector< double > &x, const Vector< double > &n, Vector< double > &result) traction_fct_pt ()
Access function for the imposed traction pointer.
Protected Member Functions
void fill_in_generic_residual_contribution_fluid_traction (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceSpaceTimeElement representation, by default.
virtual int u_local_eqn (const unsigned &n, const unsigned &i)
Access function that returns the local equation numbers for velocity components. u_local_eqn(n,i)=local equation number or < 0 if pinned. The default is to asssume that n is the local node number and the i-th velocity component is the i-th unknown stored at the node.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping.
void get_traction (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
Function to calculate the traction applied to the fluid.
void fill_in_generic_residual_contribution_fluid_traction (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceSpaceTimeElement representation, by default.
virtual int u_local_eqn (const unsigned &n, const unsigned &i)
Access function that returns the local equation numbers for velocity components. u_local_eqn(n,i)=local equation number or < 0 if pinned. The default is to asssume that n is the local node number and the i-th velocity component is the i-th unknown stored at the node.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping.
void get_traction (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
Function to calculate the traction applied to the fluid.
void fill_in_generic_residual_contribution_fluid_traction (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceSpaceTimeElement representation, by default.
virtual int u_local_eqn (const unsigned &n, const unsigned &i)
Access function that returns the local equation numbers for velocity components. u_local_eqn(n,i)=local equation number or < 0 if pinned. The default is to asssume that n is the local node number and the i-th velocity component is the i-th unknown stored at the node.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping.
void get_traction (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
Function to calculate the traction applied to the fluid.
Protected Attributes
unsigned Dim
The highest dimension of the problem.
Private Attributes
void(* Traction_fct_pt)(const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
Pointer to an imposed traction function.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >
A class for elements that allow the imposition of an applied traction to the Navier--Stokes equations The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
Definition at line 51 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
Constructor & Destructor Documentation
NavierStokesSpaceTimeTractionElement() [1/3]
template<class ELEMENT >
oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::NavierStokesSpaceTimeTractionElement (FiniteElement *const & element_pt, const int & face_index, const bool & called_from_refineable_constructor = false) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit.
Definition at line 65 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FiniteElement::dim(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::Dim, oomph::FaceElement::face_index(), oomph::FiniteElement::has_hanging_nodes(), oomph::Node::ndim(), oomph::FiniteElement::node_pt(), and oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::Traction_fct_pt.
 NavierStokesSpaceTimeTractionElement() [1/3]
template<class ELEMENT >
oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::~NavierStokesSpaceTimeTractionElement () [inline]
Destructor should not delete anything.
Definition at line 121 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
NavierStokesSpaceTimeTractionElement() [2/3]
template<class ELEMENT >
oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::NavierStokesSpaceTimeTractionElement (FiniteElement *const & element_pt, const int & face_index, const bool & called_from_refineable_constructor = false) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit.
Definition at line 65 of file discontinuous_galerkin_spacetime_fluid_traction_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FiniteElement::dim(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::Dim, oomph::FaceElement::face_index(), oomph::FiniteElement::has_hanging_nodes(), oomph::Node::ndim(), oomph::FiniteElement::node_pt(), and oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::Traction_fct_pt.
 NavierStokesSpaceTimeTractionElement() [2/3]
template<class ELEMENT >
oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::~NavierStokesSpaceTimeTractionElement () [inline]
Destructor should not delete anything.
Definition at line 121 of file discontinuous_galerkin_spacetime_fluid_traction_elements.h.
NavierStokesSpaceTimeTractionElement() [3/3]
template<class ELEMENT >
oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::NavierStokesSpaceTimeTractionElement (FiniteElement *const & element_pt, const int & face_index, const bool & called_from_refineable_constructor = false) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit.
Definition at line 66 of file spacetime_fluid_traction_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FiniteElement::dim(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::Dim, oomph::FaceElement::face_index(), oomph::FiniteElement::has_hanging_nodes(), oomph::Node::ndim(), oomph::FiniteElement::node_pt(), and oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::Traction_fct_pt.
 NavierStokesSpaceTimeTractionElement() [3/3]
template<class ELEMENT >
oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::~NavierStokesSpaceTimeTractionElement () [inline]
Destructor should not delete anything.
Definition at line 122 of file spacetime_fluid_traction_elements.h.
Member Function Documentation
fill_in_contribution_to_jacobian() [1/3]
template<class ELEMENT >
void oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
This function returns the residuals and the jacobian.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >, oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >, and oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >.
Definition at line 146 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
References oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction().
fill_in_contribution_to_jacobian() [2/3]
template<class ELEMENT >
void oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
This function returns the residuals and the jacobian.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >, and oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >.
Definition at line 146 of file discontinuous_galerkin_spacetime_fluid_traction_elements.h.
References oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction().
fill_in_contribution_to_jacobian() [3/3]
template<class ELEMENT >
void oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
This function returns the residuals and the jacobian.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >.
Definition at line 147 of file spacetime_fluid_traction_elements.h.
References oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction().
fill_in_contribution_to_residuals() [1/3]
template<class ELEMENT >
void oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
This function returns just the residuals.
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >, oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >, and oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >.
Definition at line 136 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction().
fill_in_contribution_to_residuals() [2/3]
template<class ELEMENT >
void oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
This function returns just the residuals.
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >, and oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >.
Definition at line 136 of file discontinuous_galerkin_spacetime_fluid_traction_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction().
fill_in_contribution_to_residuals() [3/3]
template<class ELEMENT >
void oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
This function returns just the residuals.
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >.
Definition at line 137 of file spacetime_fluid_traction_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction().
fill_in_generic_residual_contribution_fluid_traction() [1/3]
template<class ELEMENT >
void oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected]
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Function that returns the residuals for the imposed traction Navier-Stokes equations
Definition at line 312 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
References oomph::Multi_domain_functions::Dim, i, and oomph::QuadTreeNames::W.
Referenced by oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_residuals().
fill_in_generic_residual_contribution_fluid_traction() [2/3]
template<class ELEMENT >
void oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected]
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
fill_in_generic_residual_contribution_fluid_traction() [3/3]
template<class ELEMENT >
void oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected]
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
get_traction() [1/3]
template<class ELEMENT >
void oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::get_traction (const double & time, const Vector< double > & x, const Vector< double > & n, Vector< double > & result) [inline], [protected]
Function to calculate the traction applied to the fluid.
Definition at line 275 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
References oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::Dim, i, and oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::Traction_fct_pt.
get_traction() [2/3]
template<class ELEMENT >
void oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::get_traction (const double & time, const Vector< double > & x, const Vector< double > & n, Vector< double > & result) [inline], [protected]
Function to calculate the traction applied to the fluid.
Definition at line 275 of file discontinuous_galerkin_spacetime_fluid_traction_elements.h.
References oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::Dim, i, and oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::Traction_fct_pt.
get_traction() [3/3]
template<class ELEMENT >
void oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::get_traction (const double & time, const Vector< double > & x, const Vector< double > & n, Vector< double > & result) [inline], [protected]
Function to calculate the traction applied to the fluid.
Definition at line 217 of file spacetime_fluid_traction_elements.h.
References oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::Dim, i, and oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::Traction_fct_pt.
output() [1/6]
template<class ELEMENT >
void oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Definition at line 156 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
References oomph::FiniteElement::output().
output() [2/6]
template<class ELEMENT >
void oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Definition at line 156 of file discontinuous_galerkin_spacetime_fluid_traction_elements.h.
References oomph::FiniteElement::output().
output() [3/6]
template<class ELEMENT >
void oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Definition at line 157 of file spacetime_fluid_traction_elements.h.
References oomph::FiniteElement::output().
output() [4/6]
template<class ELEMENT >
void oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format.
Reimplemented from oomph::FiniteElement.
Definition at line 163 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
References oomph::FiniteElement::output().
output() [5/6]
template<class ELEMENT >
void oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format.
Reimplemented from oomph::FiniteElement.
Definition at line 163 of file discontinuous_galerkin_spacetime_fluid_traction_elements.h.
References oomph::FiniteElement::output().
output() [6/6]
template<class ELEMENT >
void oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format.
Reimplemented from oomph::FiniteElement.
Definition at line 164 of file spacetime_fluid_traction_elements.h.
References oomph::FiniteElement::output().
shape_and_test_at_knot() [1/3]
template<class ELEMENT >
double oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping.
Definition at line 200 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
References oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::J_eulerian_at_knot(), oomph::Integral::knot(), oomph::FiniteElement::nnode_1d(), s, oomph::OneDimLagrange::shape< 3 >(), oomph::OneDimDiscontinuousGalerkin::shape< 3 >(), and oomph::FiniteElement::shape_at_knot().
shape_and_test_at_knot() [2/3]
template<class ELEMENT >
double oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping.
Definition at line 200 of file discontinuous_galerkin_spacetime_fluid_traction_elements.h.
References oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::J_eulerian_at_knot(), oomph::Integral::knot(), oomph::FiniteElement::nnode_1d(), s, oomph::OneDimLagrange::shape< 3 >(), oomph::OneDimDiscontinuousGalerkin::shape< 3 >(), and oomph::FiniteElement::shape_at_knot().
shape_and_test_at_knot() [3/3]
template<class ELEMENT >
double oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping.
Definition at line 201 of file spacetime_fluid_traction_elements.h.
References oomph::FaceElement::J_eulerian_at_knot(), and oomph::FiniteElement::shape_at_knot().
u_local_eqn() [1/3]
template<class ELEMENT >
virtual int oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::u_local_eqn (const unsigned & n, const unsigned & i) [inline], [protected], [virtual]
Access function that returns the local equation numbers for velocity components. u_local_eqn(n,i)=local equation number or < 0 if pinned. The default is to asssume that n is the local node number and the i-th velocity component is the i-th unknown stored at the node.
Definition at line 193 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
References i, and oomph::FiniteElement::nodal_local_eqn().
u_local_eqn() [2/3]
template<class ELEMENT >
virtual int oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::u_local_eqn (const unsigned & n, const unsigned & i) [inline], [protected], [virtual]
Access function that returns the local equation numbers for velocity components. u_local_eqn(n,i)=local equation number or < 0 if pinned. The default is to asssume that n is the local node number and the i-th velocity component is the i-th unknown stored at the node.
Definition at line 193 of file discontinuous_galerkin_spacetime_fluid_traction_elements.h.
References i, and oomph::FiniteElement::nodal_local_eqn().
u_local_eqn() [3/3]
template<class ELEMENT >
virtual int oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::u_local_eqn (const unsigned & n, const unsigned & i) [inline], [protected], [virtual]
Access function that returns the local equation numbers for velocity components. u_local_eqn(n,i)=local equation number or < 0 if pinned. The default is to asssume that n is the local node number and the i-th velocity component is the i-th unknown stored at the node.
Definition at line 194 of file spacetime_fluid_traction_elements.h.
References i, and oomph::FiniteElement::nodal_local_eqn().
zeta_nodal() [1/3]
template<class ELEMENT >
double oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [protected], [virtual]
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceSpaceTimeElement representation, by default.
Reimplemented from oomph::FaceElement.
Definition at line 180 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
References i, and oomph::FaceElement::zeta_nodal().
zeta_nodal() [2/3]
template<class ELEMENT >
double oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [protected], [virtual]
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceSpaceTimeElement representation, by default.
Reimplemented from oomph::FaceElement.
Definition at line 180 of file discontinuous_galerkin_spacetime_fluid_traction_elements.h.
References i, and oomph::FaceElement::zeta_nodal().
zeta_nodal() [3/3]
template<class ELEMENT >
double oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [protected], [virtual]
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceSpaceTimeElement representation, by default.
Reimplemented from oomph::FaceElement.
Definition at line 181 of file spacetime_fluid_traction_elements.h.
References i, and oomph::FaceElement::zeta_nodal().
Member Data Documentation
Dim
template<class ELEMENT >
unsigned oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::Dim [protected]
The highest dimension of the problem.
Definition at line 300 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
Referenced by oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::get_traction(), and oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::NavierStokesSpaceTimeTractionElement().
traction_fct_pt
template<class ELEMENT >
void(*&)(const double &t, const Vector< double > &x, const Vector< double > &n, Vector< double > &result) oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::traction_fct_pt() [inline]
Access function for the imposed traction pointer.
Definition at line 125 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
Traction_fct_pt
template<class ELEMENT >
void(* oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::Traction_fct_pt)(const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result) [private]
Pointer to an imposed traction function.
Definition at line 57 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
Referenced by oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::get_traction(), and oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::NavierStokesSpaceTimeTractionElement().
The documentation for this class was generated from the following files:
discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h
discontinuous_galerkin_spacetime_fluid_traction_elements.h
spacetime_fluid_traction_elements.h