oomph::DummyBlockPreconditioner< MATRIX > Class Template Reference
#include <general_purpose_block_preconditioners.h>
Public Member Functions
DummyBlockPreconditioner ()
Constructor.
~DummyBlockPreconditioner ()
Destructor.
DummyBlockPreconditioner (const DummyBlockPreconditioner &)
Broken copy constructor.
void operator= (const DummyBlockPreconditioner &)
Broken assignment operator.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply preconditioner to r (just copy r to z).
void setup ()
Setup the preconditioner.
Additional Inherited Members
Detailed Description
template<typename MATRIX>
class oomph::DummyBlockPreconditioner< MATRIX >
Preconditioner that doesn't actually do any preconditioning, it just allows access to the Jacobian blocks. This is pretty hacky but oh well..
Definition at line 620 of file general_purpose_block_preconditioners.h.
Constructor & Destructor Documentation
DummyBlockPreconditioner() [1/2]
template<typename MATRIX >
oomph::DummyBlockPreconditioner< MATRIX >::DummyBlockPreconditioner () [inline]
Constructor.
Definition at line 625 of file general_purpose_block_preconditioners.h.
 DummyBlockPreconditioner()
template<typename MATRIX >
oomph::DummyBlockPreconditioner< MATRIX >::~DummyBlockPreconditioner () [inline]
Destructor.
Definition at line 628 of file general_purpose_block_preconditioners.h.
DummyBlockPreconditioner() [2/2]
template<typename MATRIX >
oomph::DummyBlockPreconditioner< MATRIX >::DummyBlockPreconditioner (const DummyBlockPreconditioner< MATRIX > &) [inline]
Broken copy constructor.
Definition at line 631 of file general_purpose_block_preconditioners.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
operator=()
template<typename MATRIX >
void oomph::DummyBlockPreconditioner< MATRIX >::operator= (const DummyBlockPreconditioner< MATRIX > &) [inline]
Broken assignment operator.
Definition at line 637 of file general_purpose_block_preconditioners.h.
References oomph::BrokenCopy::broken_assign().
preconditioner_solve()
template<typename MATRIX >
void oomph::DummyBlockPreconditioner< MATRIX >::preconditioner_solve (const DoubleVector & r, DoubleVector & z) [inline], [virtual]
Apply preconditioner to r (just copy r to z).
Implements oomph::Preconditioner.
Definition at line 643 of file general_purpose_block_preconditioners.h.
References oomph::DoubleVector::build().
setup()
template<typename MATRIX >
void oomph::DummyBlockPreconditioner< MATRIX >::setup () [inline], [virtual]
Setup the preconditioner.
Implements oomph::Preconditioner.
Definition at line 649 of file general_purpose_block_preconditioners.h.
References oomph::BlockPreconditioner< MATRIX >::block_setup().
The documentation for this class was generated from the following file:
general_purpose_block_preconditioners.h