oomph::RefineableTubeMesh< ELEMENT > Class Template Reference
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
#include <tube_mesh.template.h>
Public Member Functions
RefineableTubeMesh (GeomObject *wall_pt, const Vector< double > &centreline_limits, const Vector< double > &theta_positions, const Vector< double > &radius_box, const unsigned &nlayer, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor for adaptive deformable quarter tube mesh class. Pass pointer to geometric object that specifies the volume, start and end coordinates for the centreline on the geometric object. Values of theta at which dividing lines are to be placed, fractions of the radius for the central box at the dividing lines, the number of layers and the timestepper. Timestepper defaults to Steady dummy timestepper.
virtual ~RefineableTubeMesh ()
Destructor: empty.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::RefineableTubeMesh< ELEMENT >
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
Adaptative version of the TubeMesh base mesh. The domain is specified by the GeomObject that identifies the entire volume
The mesh boundaries are numbered as follows:
Boundary 0: `Inflow` cross section; located along the line parametrised by $ \xi_0 = \xi_0^{lo} $.
Boundary 1: The outer wall, represetned by $\xi_2 = 1$.
Boundary 2: The out flow, represented by $\xi_0 = \xi_0^{hi}$.
Definition at line 124 of file tube_mesh.template.h.
Constructor & Destructor Documentation
RefineableTubeMesh()
template<class ELEMENT >
oomph::RefineableTubeMesh< ELEMENT >::RefineableTubeMesh (GeomObject * wall_pt, const Vector< double > & centreline_limits, const Vector< double > & theta_positions, const Vector< double > & radius_box, const unsigned & nlayer, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor for adaptive deformable quarter tube mesh class. Pass pointer to geometric object that specifies the volume, start and end coordinates for the centreline on the geometric object. Values of theta at which dividing lines are to be placed, fractions of the radius for the central box at the dividing lines, the number of layers and the timestepper. Timestepper defaults to Steady dummy timestepper.
Definition at line 137 of file tube_mesh.template.h.
References oomph::TubeMesh< ELEMENT >::Domain_pt, oomph::Mesh::element_pt(), oomph::Mesh::finite_element_pt(), oomph::TreeBasedRefineableMeshBase::Forest_pt, oomph::Domain::macro_element_pt(), oomph::oomph_info, and oomph::Mesh::self_test().
 RefineableTubeMesh()
template<class ELEMENT >
virtual oomph::RefineableTubeMesh< ELEMENT >::~RefineableTubeMesh () [inline], [virtual]
Destructor: empty.
Definition at line 190 of file tube_mesh.template.h.
The documentation for this class was generated from the following file:
tube_mesh.template.h