oomph::SamplePointContainerParameters Class Reference
Helper object for dealing with the parameters used for the SamplePointContainer objects.
#include <sample_point_parameters.h>
Public Member Functions
SamplePointContainerParameters (const SamplePointContainerParameters &data)
Broken copy constructor.
void operator= (const SamplePointContainerParameters &)
Broken assignment operator.
virtual ~SamplePointContainerParameters ()
Empty destructor.
Mesh * mesh_pt () const
Pointer to mesh from whose FiniteElements sample points are created.
Vector< std::pair< double, double > > & min_and_max_coordinates ()
Vector of pairs of doubles for min and maximum coordinates. Call: Min_and_max_coordinates[j] gives me the pair of min (first) and max. (second) coordinates in the j-th coordinate direction.
Vector< std::pair< double, double > > min_and_max_coordinates () const
Vector of pairs of doubles for min and maximum coordinates. Call: Min_and_max_coordinates[j] gives me the pair of min (first) and max. (second) coordinates in the j-th coordinate direction. Const version.
unsigned nsample_points_generated_per_element () const
`Measure of` number of sample points generated in each element const version
unsigned & nsample_points_generated_per_element ()
`Measure of` number of sample points generated in each element
bool use_eulerian_coordinates_during_setup () const
Use eulerian coordinates (via interpolated_x) during setup (otherwise use interpolated_zeta())?
void enable_use_eulerian_coordinates_during_setup ()
void disable_use_eulerian_coordinates_during_setup ()
bool ignore_halo_elements_during_locate_zeta_search () const
Ignore halo elements? (MPI only)
void enable_ignore_halo_elements_during_locate_zeta_search ()
Enable Ignore halo elements? (MPI only)
void disable_ignore_halo_elements_during_locate_zeta_search ()
Disable Ignore halo elements? (MPI only)
Static Public Attributes
static unsigned Default_nsample_points_generated_per_element
Default for `measure of` number of sample points per element.
Protected Attributes
Mesh * Mesh_pt
Pointer to mesh from whose FiniteElements sample points are created.
Vector< std::pair< double, double > > Min_and_max_coordinates
unsigned Nsample_points_generated_per_element
`Measure of` number of sample points generated in each element
bool Use_eulerian_coordinates_during_setup
Use Eulerian coordinates to setup bin (i.e. use interpolated_x() rather than interpolated_zeta() when setting up and searching sample point container)
bool Ignore_halo_elements_during_locate_zeta_search
Ignore halo elements? Accepting halo elements can drastically reduce the number of external halo elements in multidomain problems -- currently not aware of any problems with doing this therefore set to false by default but retention of this flag allows easy return to previous implementation.
Private Member Functions
SamplePointContainerParameters (Mesh *mesh_pt)
Constructor: Pass mesh. Constructor is private and can only be called by the derived friends.
SamplePointContainerParameters ()
Broken default constructor; needed for broken copy constructors. Don't call. It will die.
Friends
class BinArrayParameters
Constructor is private and only accessible by friends to ensure that parameters are set correctly.
class RefineableBinArrayParameters
class NonRefineableBinArrayParameters
class CGALSamplePointContainerParameters
Detailed Description
Helper object for dealing with the parameters used for the SamplePointContainer objects.
Definition at line 69 of file sample_point_parameters.h.
Constructor & Destructor Documentation
SamplePointContainerParameters() [1/3]
oomph::SamplePointContainerParameters::SamplePointContainerParameters (const SamplePointContainerParameters & data) [inline]
Broken copy constructor.
Definition at line 82 of file sample_point_parameters.h.
References oomph::BrokenCopy::broken_copy().
 SamplePointContainerParameters()
virtual oomph::SamplePointContainerParameters::~SamplePointContainerParameters () [inline], [virtual]
Empty destructor.
Definition at line 95 of file sample_point_parameters.h.
SamplePointContainerParameters() [2/3]
oomph::SamplePointContainerParameters::SamplePointContainerParameters (Mesh * mesh_pt) [inline], [private]
Constructor: Pass mesh. Constructor is private and can only be called by the derived friends.
Definition at line 206 of file sample_point_parameters.h.
SamplePointContainerParameters() [3/3]
oomph::SamplePointContainerParameters::SamplePointContainerParameters () [inline], [private]
Broken default constructor; needed for broken copy constructors. Don't call. It will die.
Definition at line 217 of file sample_point_parameters.h.
Member Function Documentation
disable_ignore_halo_elements_during_locate_zeta_search()
void oomph::SamplePointContainerParameters::disable_ignore_halo_elements_during_locate_zeta_search () [inline]
Disable Ignore halo elements? (MPI only)
Definition at line 168 of file sample_point_parameters.h.
References Ignore_halo_elements_during_locate_zeta_search.
disable_use_eulerian_coordinates_during_setup()
void oomph::SamplePointContainerParameters::disable_use_eulerian_coordinates_during_setup () [inline]
Disable use of eulerian coordinates (via interpolated_x) during setup (otherwise use interpolated_zeta())
Definition at line 150 of file sample_point_parameters.h.
References Use_eulerian_coordinates_during_setup.
enable_ignore_halo_elements_during_locate_zeta_search()
void oomph::SamplePointContainerParameters::enable_ignore_halo_elements_during_locate_zeta_search () [inline]
Enable Ignore halo elements? (MPI only)
Definition at line 162 of file sample_point_parameters.h.
References Ignore_halo_elements_during_locate_zeta_search.
enable_use_eulerian_coordinates_during_setup()
void oomph::SamplePointContainerParameters::enable_use_eulerian_coordinates_during_setup () [inline]
Enable use of eulerian coordinates (via interpolated_x) during setup (otherwise use interpolated_zeta())
Definition at line 143 of file sample_point_parameters.h.
References Use_eulerian_coordinates_during_setup.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::adapt(), oomph::RefineableGmshTetMesh< ELEMENT >::adapt(), and oomph::RefineableTriangleMesh< ELEMENT >::adapt().
ignore_halo_elements_during_locate_zeta_search()
bool oomph::SamplePointContainerParameters::ignore_halo_elements_during_locate_zeta_search () const [inline]
Ignore halo elements? (MPI only)
Definition at line 156 of file sample_point_parameters.h.
References Ignore_halo_elements_during_locate_zeta_search.
mesh_pt()
Mesh* oomph::SamplePointContainerParameters::mesh_pt () const [inline]
Pointer to mesh from whose FiniteElements sample points are created.
Definition at line 98 of file sample_point_parameters.h.
References Mesh_pt.
Referenced by oomph::MeshAsGeomObject::build_it().
min_and_max_coordinates() [1/2]
Vector<std::pair<double, double> >& oomph::SamplePointContainerParameters::min_and_max_coordinates () [inline]
Vector of pairs of doubles for min and maximum coordinates. Call: Min_and_max_coordinates[j] gives me the pair of min (first) and max. (second) coordinates in the j-th coordinate direction.
Definition at line 107 of file sample_point_parameters.h.
References Min_and_max_coordinates.
min_and_max_coordinates() [2/2]
Vector<std::pair<double, double> > oomph::SamplePointContainerParameters::min_and_max_coordinates () const [inline]
Vector of pairs of doubles for min and maximum coordinates. Call: Min_and_max_coordinates[j] gives me the pair of min (first) and max. (second) coordinates in the j-th coordinate direction. Const version.
Definition at line 116 of file sample_point_parameters.h.
References Min_and_max_coordinates.
nsample_points_generated_per_element() [1/2]
unsigned& oomph::SamplePointContainerParameters::nsample_points_generated_per_element () [inline]
`Measure of` number of sample points generated in each element
Definition at line 129 of file sample_point_parameters.h.
References Nsample_points_generated_per_element.
nsample_points_generated_per_element() [2/2]
unsigned oomph::SamplePointContainerParameters::nsample_points_generated_per_element () const [inline]
`Measure of` number of sample points generated in each element const version
Definition at line 123 of file sample_point_parameters.h.
References Nsample_points_generated_per_element.
operator=()
void oomph::SamplePointContainerParameters::operator= (const SamplePointContainerParameters &) [inline]
Broken assignment operator.
Definition at line 88 of file sample_point_parameters.h.
References oomph::BrokenCopy::broken_assign().
use_eulerian_coordinates_during_setup()
bool oomph::SamplePointContainerParameters::use_eulerian_coordinates_during_setup () const [inline]
Use eulerian coordinates (via interpolated_x) during setup (otherwise use interpolated_zeta())?
Definition at line 136 of file sample_point_parameters.h.
References Use_eulerian_coordinates_during_setup.
Friends And Related Function Documentation
BinArrayParameters
friend class BinArrayParameters [friend]
Constructor is private and only accessible by friends to ensure that parameters are set correctly.
Definition at line 74 of file sample_point_parameters.h.
CGALSamplePointContainerParameters
friend class CGALSamplePointContainerParameters [friend]
Definition at line 78 of file sample_point_parameters.h.
NonRefineableBinArrayParameters
friend class NonRefineableBinArrayParameters [friend]
Definition at line 76 of file sample_point_parameters.h.
RefineableBinArrayParameters
friend class RefineableBinArrayParameters [friend]
Definition at line 75 of file sample_point_parameters.h.
Member Data Documentation
Default_nsample_points_generated_per_element
unsigned oomph::SamplePointContainerParameters::Default_nsample_points_generated_per_element [static]
Default for `measure of` number of sample points per element.
Definition at line 174 of file sample_point_parameters.h.
Ignore_halo_elements_during_locate_zeta_search
bool oomph::SamplePointContainerParameters::Ignore_halo_elements_during_locate_zeta_search [protected]
Ignore halo elements? Accepting halo elements can drastically reduce the number of external halo elements in multidomain problems -- currently not aware of any problems with doing this therefore set to false by default but retention of this flag allows easy return to previous implementation.
Definition at line 199 of file sample_point_parameters.h.
Referenced by disable_ignore_halo_elements_during_locate_zeta_search(), enable_ignore_halo_elements_during_locate_zeta_search(), and ignore_halo_elements_during_locate_zeta_search().
Mesh_pt
Mesh* oomph::SamplePointContainerParameters::Mesh_pt [protected]
Pointer to mesh from whose FiniteElements sample points are created.
Definition at line 178 of file sample_point_parameters.h.
Referenced by mesh_pt().
Min_and_max_coordinates
Vector<std::pair<double, double> > oomph::SamplePointContainerParameters::Min_and_max_coordinates [protected]
Vector of pairs of doubles for min and maximum coordinates. Call: Min_and_max_coordinates[j] gives me the pair of min (first) and max. (second) coordinates in the j-th coordinate direction.
Definition at line 184 of file sample_point_parameters.h.
Referenced by min_and_max_coordinates().
Nsample_points_generated_per_element
unsigned oomph::SamplePointContainerParameters::Nsample_points_generated_per_element [protected]
`Measure of` number of sample points generated in each element
Definition at line 187 of file sample_point_parameters.h.
Referenced by nsample_points_generated_per_element().
Use_eulerian_coordinates_during_setup
bool oomph::SamplePointContainerParameters::Use_eulerian_coordinates_during_setup [protected]
Use Eulerian coordinates to setup bin (i.e. use interpolated_x() rather than interpolated_zeta() when setting up and searching sample point container)
Definition at line 192 of file sample_point_parameters.h.
Referenced by disable_use_eulerian_coordinates_during_setup(), enable_use_eulerian_coordinates_during_setup(), and use_eulerian_coordinates_during_setup().
The documentation for this class was generated from the following file:
sample_point_parameters.h