oomph::TLinearElasticityElement< DIM, NNODE_1D > Class Template Reference
//////////////////////////////////////////////////////////////////////
#include <Tlinear_elasticity_elements.h>
Public Member Functions
TLinearElasticityElement ()
Constructor: Call constructors for TElement and LinearElasticity equations.
TLinearElasticityElement (const TLinearElasticityElement< DIM, NNODE_1D > &dummy)=delete
Broken copy constructor.
void output (std::ostream &outfile)
Broken assignment operator.
void output (std::ostream &outfile, const unsigned &nplot)
Output function:
void output (FILE *file_pt)
C-style output function:
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function:
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain tensor.
Additional Inherited Members
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::TLinearElasticityElement< DIM, NNODE_1D >
//////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////// TLinearElasticityElement<DIM,NNODE_1D> elements are isoparametric triangular DIM-dimensional LinearElasticity elements with NNODE_1D nodal points along each element edge. Inherits from TElement and LinearElasticityEquations
Definition at line 62 of file Tlinear_elasticity_elements.h.
Constructor & Destructor Documentation
TLinearElasticityElement() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::TLinearElasticityElement< DIM, NNODE_1D >::TLinearElasticityElement () [inline]
Constructor: Call constructors for TElement and LinearElasticity equations.
Definition at line 70 of file Tlinear_elasticity_elements.h.
TLinearElasticityElement() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::TLinearElasticityElement< DIM, NNODE_1D >::TLinearElasticityElement (const TLinearElasticityElement< DIM, NNODE_1D > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
get_Z2_flux()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TLinearElasticityElement< DIM, NNODE_1D >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Upper triangular entries in strain tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 141 of file Tlinear_elasticity_elements.h.
References oomph::LinearElasticityEquationsBase< DIM >::get_strain(), and i.
nrecovery_order()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::TLinearElasticityElement< DIM, NNODE_1D >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 127 of file Tlinear_elasticity_elements.h.
num_Z2_flux_terms()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::TLinearElasticityElement< DIM, NNODE_1D >::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 133 of file Tlinear_elasticity_elements.h.
nvertex_node()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::TLinearElasticityElement< DIM, NNODE_1D >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 114 of file Tlinear_elasticity_elements.h.
output() [1/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TLinearElasticityElement< DIM, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function:
Reimplemented from oomph::LinearElasticityEquations< DIM >.
Definition at line 102 of file Tlinear_elasticity_elements.h.
References oomph::LinearElasticityEquations< DIM >::output().
output() [2/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TLinearElasticityElement< DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function:
Reimplemented from oomph::LinearElasticityEquations< DIM >.
Definition at line 108 of file Tlinear_elasticity_elements.h.
References oomph::LinearElasticityEquations< DIM >::output().
output() [3/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TLinearElasticityElement< DIM, NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Broken assignment operator.
Output function:
Reimplemented from oomph::LinearElasticityEquations< DIM >.
Definition at line 89 of file Tlinear_elasticity_elements.h.
References oomph::LinearElasticityEquations< DIM >::output().
output() [4/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TLinearElasticityElement< DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function:
Reimplemented from oomph::LinearElasticityEquations< DIM >.
Definition at line 95 of file Tlinear_elasticity_elements.h.
References oomph::LinearElasticityEquations< DIM >::output().
vertex_node_pt()
template<unsigned DIM, unsigned NNODE_1D>
Node * oomph::TLinearElasticityElement< DIM, NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 120 of file Tlinear_elasticity_elements.h.
The documentation for this class was generated from the following file:
Tlinear_elasticity_elements.h