oomph::DGFaceElement Class Reference
Base class for Discontinuous Galerkin Faces. These are responsible for calculating the normal fluxes that provide the communication between the discontinuous elements.
#include <dg_elements.h>
Public Member Functions
DGFaceElement ()
Empty Constructor.
virtual ~DGFaceElement ()
Empty Destructor.
FaceElement * neighbour_face_pt (const unsigned &i)
Access function for neighbouring face information.
void setup_neighbour_info (const bool &add_neighbour_data_to_bulk)
Setup information from the neighbouring face, return a set of nodes (as data) in the neighour. The boolean flag is used to determine whether the data in the neighbour are added as external data to the bulk element --- required when computing the jacobian of the system.
void report_info ()
Output information about the present element and its neighbour.
virtual void interpolated_u (const Vector< double > &s, Vector< double > &f)
Return the interpolated values of the unknown fluxes.
virtual void get_interpolation_data (Vector< Data * > &interpolation_data)
Get the data that are used to interpolate the unkowns in the element. These must be returned in order.
virtual void numerical_flux_at_knot (const unsigned &ipt, const Shape &psi, Vector< double > &flux, DenseMatrix< double > &dflux_du_int, DenseMatrix< double > &dflux_du_ext, unsigned flag)
Calculate the normal numerical flux at the integration point. This is the most general interface that can be overloaded if desired.
virtual void numerical_flux (const Vector< double > &n_out, const Vector< double > &u_int, const Vector< double > &u_ext, Vector< double > &flux)
Calculate the normal flux, which is the dot product of our approximation to the flux with the outer unit normal.
virtual void dnumerical_flux_du (const Vector< double > &n_out, const Vector< double > &u_int, const Vector< double > &u_ext, DenseMatrix< double > &dflux_du_int, DenseMatrix< double > &dflux_du_ext)
Calculate the derivative of the normal flux, which is the dot product of our approximation to the flux with the outer unit normal, with respect to the interior and exterior variables Default is to use finite differences.
void add_flux_contributions (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Add the contribution from integrating the numerical flux.
Protected Member Functions
virtual unsigned flux_index (const unsigned &i) const
Return the index at which the i-th unknown flux is stored.
virtual unsigned required_nflux ()
Set the number of flux components.
Private Attributes
Vector< FaceElement * > Neighbour_face_pt
Vector of neighbouring face elements at the integration points.
Vector< Vector< double > > Neighbour_local_coordinate
Vector of neighbouring local coordinates at the integration points.
Vector< Vector< unsigned > > Neighbour_external_data
Vector of the vectors that will store the number of the bulk external data that correspond to the dofs in the neighbouring face This is only used if we are using implict timestepping and wish to assemble the jacobian matrix. In order that the data be correctly set up DGMesh::setup_face_neighbour_info() must be called with the boolean flag set to true.
Additional Inherited Members
Detailed Description
Base class for Discontinuous Galerkin Faces. These are responsible for calculating the normal fluxes that provide the communication between the discontinuous elements.
Definition at line 49 of file dg_elements.h.
Constructor & Destructor Documentation
DGFaceElement()
oomph::DGFaceElement::DGFaceElement () [inline]
Empty Constructor.
Definition at line 81 of file dg_elements.h.
 DGFaceElement()
virtual oomph::DGFaceElement::~DGFaceElement () [inline], [virtual]
Empty Destructor.
Definition at line 84 of file dg_elements.h.
Member Function Documentation
add_flux_contributions()
void oomph::DGFaceElement::add_flux_contributions (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag)
Add the contribution from integrating the numerical flux.
Calculate the integrated (numerical) flux out of the face and add it to the residuals vector.
Definition at line 416 of file dg_elements.cc.
References oomph::FaceElement::bulk_element_pt(), oomph::FaceElement::bulk_node_number(), oomph::FiniteElement::dim(), oomph::GeneralisedElement::external_local_eqn(), oomph::OcTreeNames::F, flux_index(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::J_eulerian_at_knot(), Neighbour_external_data, Neighbour_face_pt, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), numerical_flux_at_knot(), oomph::Integral::nweight(), required_nflux(), oomph::FiniteElement::shape_at_knot(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::DGElement::add_flux_contributions_to_residuals().
dnumerical_flux_du()
void oomph::DGFaceElement::dnumerical_flux_du (const Vector< double > & n_out, const Vector< double > & u_int, const Vector< double > & u_ext, DenseMatrix< double > & dflux_du_int, DenseMatrix< double > & dflux_du_ext) [virtual]
Calculate the derivative of the normal flux, which is the dot product of our approximation to the flux with the outer unit normal, with respect to the interior and exterior variables Default is to use finite differences.
Definition at line 338 of file dg_elements.cc.
References oomph::GeneralisedElement::Default_fd_jacobian_step, numerical_flux(), and required_nflux().
Referenced by numerical_flux_at_knot().
flux_index()
virtual unsigned oomph::DGFaceElement::flux_index (const unsigned & i) const [inline], [protected], [virtual]
Return the index at which the i-th unknown flux is stored.
Definition at line 68 of file dg_elements.h.
References i.
Referenced by add_flux_contributions(), interpolated_u(), and numerical_flux_at_knot().
get_interpolation_data()
void oomph::DGFaceElement::get_interpolation_data (Vector< Data * > & interpolation_data) [virtual]
Get the data that are used to interpolate the unkowns in the element. These must be returned in order.
Add all the data that are used to interpolate the unknowns. This must be consistent with the interpolated_u function above and the default implementation assumes pure nodal interpolaton.
Definition at line 241 of file dg_elements.cc.
References oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
Referenced by setup_neighbour_info().
interpolated_u()
void oomph::DGFaceElement::interpolated_u (const Vector< double > & s, Vector< double > & f) [virtual]
Return the interpolated values of the unknown fluxes.
Reimplemented in oomph::DGEulerFaceReflectionElement< ELEMENT >.
Definition at line 196 of file dg_elements.cc.
References flux_index(), i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), required_nflux(), oomph::FiniteElement::shape(), and oomph::Node::value().
Referenced by numerical_flux_at_knot().
neighbour_face_pt()
FaceElement* oomph::DGFaceElement::neighbour_face_pt (const unsigned & i) [inline]
Access function for neighbouring face information.
Definition at line 87 of file dg_elements.h.
References i, and Neighbour_face_pt.
numerical_flux()
virtual void oomph::DGFaceElement::numerical_flux (const Vector< double > & n_out, const Vector< double > & u_int, const Vector< double > & u_ext, Vector< double > & flux) [inline], [virtual]
Calculate the normal flux, which is the dot product of our approximation to the flux with the outer unit normal.
Reimplemented in oomph::DGScalarAdvectionFaceElement< ELEMENT >, and oomph::DGEulerFaceElement< ELEMENT >.
Definition at line 121 of file dg_elements.h.
Referenced by dnumerical_flux_du(), and numerical_flux_at_knot().
numerical_flux_at_knot()
void oomph::DGFaceElement::numerical_flux_at_knot (const unsigned & ipt, const Shape & psi, Vector< double > & flux, DenseMatrix< double > & dflux_du_int, DenseMatrix< double > & dflux_du_ext, unsigned flag) [virtual]
Calculate the normal numerical flux at the integration point. This is the most general interface that can be overloaded if desired.
Calculate the numerical flux at the knot point ipt. This is the most general interface than can be overloaded if desired. The shape functions at the knot point will be passed into this function.
Definition at line 266 of file dg_elements.cc.
References dnumerical_flux_du(), flux_index(), i, interpolated_u(), Neighbour_face_pt, Neighbour_local_coordinate, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::nodal_value(), numerical_flux(), oomph::FaceElement::outer_unit_normal(), and required_nflux().
Referenced by add_flux_contributions().
report_info()
void oomph::DGFaceElement::report_info ()
Output information about the present element and its neighbour.
Definition at line 123 of file dg_elements.cc.
References oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::Integral::knot(), Neighbour_face_pt, Neighbour_local_coordinate, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), oomph::Integral::nweight(), oomph::oomph_info, and s.
Referenced by oomph::DGElement::setup_face_neighbour_info().
required_nflux()
virtual unsigned oomph::DGFaceElement::required_nflux () [inline], [protected], [virtual]
Set the number of flux components.
Reimplemented in oomph::DGScalarAdvectionFaceElement< ELEMENT >, oomph::DGEulerFaceReflectionElement< ELEMENT >, and oomph::DGEulerFaceElement< ELEMENT >.
Definition at line 74 of file dg_elements.h.
Referenced by add_flux_contributions(), dnumerical_flux_du(), interpolated_u(), and numerical_flux_at_knot().
setup_neighbour_info()
void oomph::DGFaceElement::setup_neighbour_info (const bool & add_neighbour_data_to_bulk)
Setup information from the neighbouring face, return a set of nodes (as data) in the neighour. The boolean flag is used to determine whether the data in the neighbour are added as external data to the bulk element --- required when computing the jacobian of the system.
Find pointers to neighbouring faces and the local coordinates in those faces that correspond to the integration points in the present face. This is achieved by moving up to the bulk element and thence the mesh which MUST have implemented a neighbour finding scheme.
Definition at line 42 of file dg_elements.cc.
References oomph::GeneralisedElement::add_external_data(), oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), oomph::FaceElement::face_index(), get_interpolation_data(), oomph::FaceElement::get_local_coordinate_in_bulk(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), Neighbour_external_data, Neighbour_face_pt, Neighbour_local_coordinate, oomph::Integral::nweight(), and s.
Referenced by oomph::DGElement::setup_face_neighbour_info().
Member Data Documentation
Neighbour_external_data
Vector<Vector<unsigned> > oomph::DGFaceElement::Neighbour_external_data [private]
Vector of the vectors that will store the number of the bulk external data that correspond to the dofs in the neighbouring face This is only used if we are using implict timestepping and wish to assemble the jacobian matrix. In order that the data be correctly set up DGMesh::setup_face_neighbour_info() must be called with the boolean flag set to true.
Definition at line 63 of file dg_elements.h.
Referenced by add_flux_contributions(), and setup_neighbour_info().
Neighbour_face_pt
Vector<FaceElement*> oomph::DGFaceElement::Neighbour_face_pt [private]
Vector of neighbouring face elements at the integration points.
Definition at line 52 of file dg_elements.h.
Referenced by add_flux_contributions(), neighbour_face_pt(), numerical_flux_at_knot(), report_info(), and setup_neighbour_info().
Neighbour_local_coordinate
Vector<Vector<double> > oomph::DGFaceElement::Neighbour_local_coordinate [private]
Vector of neighbouring local coordinates at the integration points.
Definition at line 55 of file dg_elements.h.
Referenced by numerical_flux_at_knot(), report_info(), and setup_neighbour_info().
The documentation for this class was generated from the following files:
dg_elements.h
dg_elements.cc