oomph::OomphInfo Class Reference
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
#include <oomph_definitions.h>
Public Member Functions
OomphInfo ()
Set default values for the output stream (cout) and modifier (no modification)
template<class _Tp >
std::ostream & operator<< (_Tp argument)
Overload the << operator, writing output to the stream addressed by Stream_pt and calling the function defined by the object addressed by Output_modifier_pt.
std::ostream *& stream_pt ()
Access function for the stream pointer.
std::ostream & operator<< (std::ostream &(*f)(std::ostream &))
Overload insertor to handle stream modifiers.
OutputModifier *& output_modifier_pt ()
Access function for the output modifier pointer.
Private Attributes
std::ostream * Stream_pt
Pointer to the output stream -- defaults to std::cout.
OutputModifier * Output_modifier_pt
Pointer to the output modifier object -- defaults to no modification.
Detailed Description
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
This class is a wrapper to a stream and an output modifier that is used to control the `info` output from OomphLib. Its instationiation can be used like std::cout.
Definition at line 429 of file oomph_definitions.h.
Constructor & Destructor Documentation
OomphInfo()
oomph::OomphInfo::OomphInfo () [inline]
Set default values for the output stream (cout) and modifier (no modification)
Definition at line 441 of file oomph_definitions.h.
Member Function Documentation
operator<<() [1/2]
template<class _Tp >
std::ostream & oomph::OomphInfo::operator<< (_Tp argument) [inline]
Overload the << operator, writing output to the stream addressed by Stream_pt and calling the function defined by the object addressed by Output_modifier_pt.
Definition at line 450 of file oomph_definitions.h.
References oomph::oomph_nullstream.
operator<<() [2/2]
std::ostream & oomph::OomphInfo::operator<< (std::ostream &(*)(std::ostream &) f) [inline]
Overload insertor to handle stream modifiers.
Definition at line 470 of file oomph_definitions.h.
References oomph::f().
output_modifier_pt()
OutputModifier *& oomph::OomphInfo::output_modifier_pt () [inline]
Access function for the output modifier pointer.
Definition at line 476 of file oomph_definitions.h.
Referenced by oomph::MPI_Helpers::init().
stream_pt()
std::ostream *& oomph::OomphInfo::stream_pt () [inline]
Access function for the stream pointer.
Definition at line 464 of file oomph_definitions.h.
Referenced by oomph::BlackBoxFDNewtonSolver::black_box_fd_newton_solve(), oomph::Mesh::classify_halo_and_haloed_nodes(), oomph::MGSolver< DIM >::disable_output(), oomph::HelmholtzMGPreconditioner< DIM >::disable_output(), oomph::HelmholtzMGPreconditioner< DIM >::preconditioner_solve(), oomph::MGPreconditioner< DIM >::preconditioner_solve(), oomph::Problem::remove_duplicate_data(), oomph::BlockDiagonalPreconditioner< MATRIX >::setup(), oomph::BlockTriangularPreconditioner< MATRIX >::setup(), oomph::MGPreconditioner< DIM >::setup(), oomph::HelmholtzMGPreconditioner< DIM >::setup(), oomph::ExactDGPBlockPreconditioner< MATRIX >::setup(), oomph::BandedBlockTriangularPreconditioner< MATRIX >::setup(), oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::setup(), oomph::GMRESBlockPreconditioner::setup(), oomph::Mesh::setup_shared_node_scheme(), and oomph::MGSolver< DIM >::solve().
Member Data Documentation
Output_modifier_pt
OutputModifier* oomph::OomphInfo::Output_modifier_pt [private]
Pointer to the output modifier object -- defaults to no modification.
Definition at line 436 of file oomph_definitions.h.
Stream_pt
std::ostream* oomph::OomphInfo::Stream_pt [private]
Pointer to the output stream -- defaults to std::cout.
Definition at line 433 of file oomph_definitions.h.
The documentation for this class was generated from the following file:
oomph_definitions.h