oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT > Class Template Reference
#include <discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h>
Public Member Functions
FpPressureAdvDiffRobinBCSpaceTimeElement (FiniteElement *const &element_pt, const int &face_index, const bool &called_from_refineable_constructor=false)
Constructor, which takes a `bulk` element and the value of the index and its limit. Optional boolean flag indicates if it's called refineable constructor.
~FpPressureAdvDiffRobinBCSpaceTimeElement ()
Empty destructor.
virtual void fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
This function returns the residuals for the traction function. flag=1 (or 0): do (or don't) compute the Jacobian as well.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
This function returns just the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the jacobian.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,[z],u,v,[w],p in tecplot format.
FpPressureAdvDiffRobinBCSpaceTimeElement (FiniteElement *const &element_pt, const int &face_index, const bool &called_from_refineable_constructor=false)
Constructor, which takes a `bulk` element and the value of the index and its limit. Optional boolean flag indicates if it's called refineable constructor.
~FpPressureAdvDiffRobinBCSpaceTimeElement ()
Empty destructor.
virtual void fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
This function returns the residuals for the traction function. flag=1 (or 0): do (or don't) compute the Jacobian as well.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
This function returns just the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the jacobian.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,[z],u,v,[w],p in tecplot format.
FpPressureAdvDiffRobinBCSpaceTimeElement (FiniteElement *const &element_pt, const int &face_index, const bool &called_from_refineable_constructor=false)
Constructor, which takes a `bulk` element and the value of the index and its limit. Optional boolean flag indicates if it's called refineable constructor.
~FpPressureAdvDiffRobinBCSpaceTimeElement ()
Empty destructor.
virtual void fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
This function returns the residuals for the traction function. flag=1 (or 0): do (or don't) compute the Jacobian as well.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
This function returns just the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the jacobian.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,[z],u,v,[w],p in tecplot format.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >
A class for elements that allow the imposition of Robin boundary conditions for the pressure advection diffusion problem in the Fp preconditioner. The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class
Definition at line 77 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Constructor & Destructor Documentation
FpPressureAdvDiffRobinBCSpaceTimeElement() [1/3]
template<class ELEMENT >
oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::FpPressureAdvDiffRobinBCSpaceTimeElement (FiniteElement *const & element_pt, const int & face_index, const bool & called_from_refineable_constructor = false) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit. Optional boolean flag indicates if it's called refineable constructor.
Definition at line 86 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FiniteElement::dim(), oomph::FaceElement::face_index(), and oomph::FiniteElement::has_hanging_nodes().
 FpPressureAdvDiffRobinBCSpaceTimeElement() [1/3]
template<class ELEMENT >
oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::~FpPressureAdvDiffRobinBCSpaceTimeElement () [inline]
Empty destructor.
Definition at line 134 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
FpPressureAdvDiffRobinBCSpaceTimeElement() [2/3]
template<class ELEMENT >
oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::FpPressureAdvDiffRobinBCSpaceTimeElement (FiniteElement *const & element_pt, const int & face_index, const bool & called_from_refineable_constructor = false) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit. Optional boolean flag indicates if it's called refineable constructor.
Definition at line 86 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FiniteElement::dim(), oomph::FaceElement::face_index(), and oomph::FiniteElement::has_hanging_nodes().
 FpPressureAdvDiffRobinBCSpaceTimeElement() [2/3]
template<class ELEMENT >
oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::~FpPressureAdvDiffRobinBCSpaceTimeElement () [inline]
Empty destructor.
Definition at line 134 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
FpPressureAdvDiffRobinBCSpaceTimeElement() [3/3]
template<class ELEMENT >
oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::FpPressureAdvDiffRobinBCSpaceTimeElement (FiniteElement *const & element_pt, const int & face_index, const bool & called_from_refineable_constructor = false) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit. Optional boolean flag indicates if it's called refineable constructor.
Definition at line 86 of file spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FiniteElement::dim(), oomph::FaceElement::face_index(), and oomph::FiniteElement::has_hanging_nodes().
 FpPressureAdvDiffRobinBCSpaceTimeElement() [3/3]
template<class ELEMENT >
oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::~FpPressureAdvDiffRobinBCSpaceTimeElement () [inline]
Empty destructor.
Definition at line 134 of file spacetime_navier_stokes_elements.h.
Member Function Documentation
fill_in_contribution_to_jacobian() [1/3]
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
This function returns the residuals and the jacobian.
Reimplemented from oomph::FiniteElement.
Definition at line 165 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
fill_in_contribution_to_jacobian() [2/3]
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
This function returns the residuals and the jacobian.
Reimplemented from oomph::FiniteElement.
Definition at line 165 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
fill_in_contribution_to_jacobian() [3/3]
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
This function returns the residuals and the jacobian.
Reimplemented from oomph::FiniteElement.
Definition at line 165 of file spacetime_navier_stokes_elements.h.
fill_in_contribution_to_residuals() [1/3]
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
This function returns just the residuals.
Reimplemented from oomph::GeneralisedElement.
Definition at line 147 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
fill_in_contribution_to_residuals() [2/3]
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
This function returns just the residuals.
Reimplemented from oomph::GeneralisedElement.
Definition at line 147 of file spacetime_navier_stokes_elements.h.
fill_in_contribution_to_residuals() [3/3]
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
This function returns just the residuals.
Reimplemented from oomph::GeneralisedElement.
Definition at line 147 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc() [1/3]
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [virtual]
This function returns the residuals for the traction function. flag=1 (or 0): do (or don't) compute the Jacobian as well.
Get residuals and Jacobian of Robin boundary conditions in pressure advection diffusion problem in Fp preconditoner NOTE: Care has to be taken here as fluxes are spatially dependent and not temporally dependent but the template elements are space-time elements!
Implements oomph::FpPressureAdvDiffRobinBCSpaceTimeElementBase.
Reimplemented in oomph::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >, oomph::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >, and oomph::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >.
Definition at line 212 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References i, residuals(), s, and oomph::QuadTreeNames::W.
fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc() [2/3]
template<class ELEMENT >
virtual void oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [virtual]
This function returns the residuals for the traction function. flag=1 (or 0): do (or don't) compute the Jacobian as well.
Implements oomph::FpPressureAdvDiffRobinBCSpaceTimeElementBase.
Reimplemented in oomph::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >, oomph::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >, and oomph::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >.
fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc() [3/3]
template<class ELEMENT >
virtual void oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [virtual]
This function returns the residuals for the traction function. flag=1 (or 0): do (or don't) compute the Jacobian as well.
Implements oomph::FpPressureAdvDiffRobinBCSpaceTimeElementBase.
Reimplemented in oomph::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >, oomph::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >, and oomph::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >.
output() [1/6]
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Definition at line 184 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::output().
output() [2/6]
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Definition at line 184 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::output().
output() [3/6]
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Definition at line 184 of file spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::output().
output() [4/6]
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format.
Reimplemented from oomph::FiniteElement.
Definition at line 192 of file spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::output().
output() [5/6]
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format.
Reimplemented from oomph::FiniteElement.
Definition at line 192 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::output().
output() [6/6]
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format.
Reimplemented from oomph::FiniteElement.
Definition at line 192 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::output().
The documentation for this class was generated from the following files:
discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h
discontinuous_galerkin_spacetime_navier_stokes_elements.h
spacetime_navier_stokes_elements.h