oomph::PoissonSmoothMesh< POISSON_ELEMENT > Class Template Reference
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
#include <mesh_smooth.h>
Public Member Functions
void operator() (SolidMesh *orig_mesh_pt, std::set< Node * > pinned_nodes)
Functor: Specify SolidMesh whose nodal positions are to be adjusted, and set of nodes in that mesh whose position are to remain fixed.
Additional Inherited Members
Detailed Description
template<class POISSON_ELEMENT>
class oomph::PoissonSmoothMesh< POISSON_ELEMENT >
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Functor to smooth a SolidMesh by adjusting the internal nodal positions by solving a Poisson problem for the nodal displacements in the interior. The displacements of the specified pinned nodes (usually located on boundaries) remain fixed (their displacements are computed from the difference between their Lagrangian and Eulerian coordinates). The assumptions is that the Lagrangian coordinates in the SolidMesh still reflect the original nodal positions before the boundary nodes were moved.
The template parameter specifies the Poisson element that must have the same shape (geometric element type) as the elements contained in the mesh that's to be smoothed. So, e.g. for the ten-noded three-dimensional tetrahedral TTaylorHoodElement<3>, it would be a TPoissonElement<3,3>, etc.
Definition at line 658 of file mesh_smooth.h.
Member Function Documentation
operator()()
template<class POISSON_ELEMENT >
void oomph::PoissonSmoothMesh< POISSON_ELEMENT >::operator() (SolidMesh * orig_mesh_pt, std::set< Node * > pinned_nodes) [inline]
Functor: Specify SolidMesh whose nodal positions are to be adjusted, and set of nodes in that mesh whose position are to remain fixed.
Definition at line 664 of file mesh_smooth.h.
References oomph::Mesh::add_element_pt(), oomph::Mesh::add_node_pt(), oomph::Problem::assign_eqn_numbers(), oomph::FiniteElement::construct_node(), e, oomph::Mesh::finite_element_pt(), i, oomph::Problem::mesh_pt(), oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::Problem::newton_solve(), oomph::FiniteElement::nnode(), oomph::Mesh::nnode(), oomph::FiniteElement::node_pt(), oomph::SolidMesh::node_pt(), oomph::oomph_info, oomph::Data::pin(), oomph::SolidMesh::set_lagrangian_nodal_coordinates(), oomph::Data::set_value(), oomph::Node::value(), oomph::Node::x(), and oomph::SolidNode::xi().
The documentation for this class was generated from the following file:
mesh_smooth.h