oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT > Class Template Reference
A class for elements that allow the imposition of the linearised FSI no slip condition from an adjacent linearly elastic axisymmetric solid. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
#include <axisym_fluid_traction_elements.h>
Public Member Functions
LinearisedFSIAxisymmetricNStNoSlipBCElementElement (FiniteElement *const &bulk_el_pt, const int &face_index, const unsigned &id=0)
Constructor, takes the pointer to the `bulk` element and the face index identifying the face to which the element is attached. The optional identifier can be used to distinguish the additional nodal values created by this element from thos created by other FaceElements.
LinearisedFSIAxisymmetricNStNoSlipBCElementElement (const LinearisedFSIAxisymmetricNStNoSlipBCElementElement &dummy)=delete
Broken copy constructor.
double *& st_pt ()
Broken assignment operator.
double st () const
Access function for the fluid Strouhal number.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and its Jacobian matrix.
void output (std::ostream &outfile)
Output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: Output at Gauss points; n_plot is ignored.
void output (FILE *file_pt)
C-style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function.
Protected Member Functions
double shape_and_test (const Vector< double > &s, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Private Member Functions
void fill_in_generic_residual_contribution_fsi_no_slip_axisym (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the contribution to the Jacobian as well.
Private Attributes
unsigned Dim
The spatial dimension of the problem.
Vector< unsigned > U_index_fsi_no_slip_axisym
The index at which the unknowns are stored at the nodes.
unsigned Id
Lagrange Id.
double * St_pt
Pointer to fluid Strouhal number.
Additional Inherited Members
Detailed Description
template<class FLUID_BULK_ELEMENT, class SOLID_BULK_ELEMENT>
class oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >
A class for elements that allow the imposition of the linearised FSI no slip condition from an adjacent linearly elastic axisymmetric solid. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
Definition at line 615 of file axisym_fluid_traction_elements.h.
Constructor & Destructor Documentation
LinearisedFSIAxisymmetricNStNoSlipBCElementElement() [1/2]
template<class FLUID_BULK_ELEMENT , class SOLID_BULK_ELEMENT >
oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::LinearisedFSIAxisymmetricNStNoSlipBCElementElement (FiniteElement *const & bulk_el_pt, const int & face_index, const unsigned & id = 0)
Constructor, takes the pointer to the `bulk` element and the face index identifying the face to which the element is attached. The optional identifier can be used to distinguish the additional nodal values created by this element from thos created by other FaceElements.
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
Constructor, takes the pointer to the `bulk` element, and the face index that identifies the face of the bulk element to which this face element is to be attached. The optional identifier can be used to distinguish the additional nodal values created by this element from thos created by other FaceElements.
Definition at line 828 of file axisym_fluid_traction_elements.h.
References oomph::FaceElement::add_additional_values(), oomph::FiniteElement::build_face_element(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCHelper::Default_strouhal_number, oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::Dim, oomph::FaceElement::face_index(), i, oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::Id, oomph::Node::ndim(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::ElementWithExternalElement::set_ninteraction(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::St_pt, and oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::U_index_fsi_no_slip_axisym.
LinearisedFSIAxisymmetricNStNoSlipBCElementElement() [2/2]
template<class FLUID_BULK_ELEMENT , class SOLID_BULK_ELEMENT >
oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::LinearisedFSIAxisymmetricNStNoSlipBCElementElement (const LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class FLUID_BULK_ELEMENT , class SOLID_BULK_ELEMENT >
void oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and its Jacobian matrix.
Reimplemented from oomph::GeneralisedElement.
Definition at line 670 of file axisym_fluid_traction_elements.h.
References oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::fill_in_generic_residual_contribution_fsi_no_slip_axisym(), and oomph::ElementWithExternalElement::fill_in_jacobian_from_external_interaction_by_fd().
fill_in_contribution_to_residuals()
template<class FLUID_BULK_ELEMENT , class SOLID_BULK_ELEMENT >
void oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 659 of file axisym_fluid_traction_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::fill_in_generic_residual_contribution_fsi_no_slip_axisym().
fill_in_generic_residual_contribution_fsi_no_slip_axisym()
template<class FLUID_BULK_ELEMENT , class SOLID_BULK_ELEMENT >
void oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::fill_in_generic_residual_contribution_fsi_no_slip_axisym (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [private]
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the contribution to the Jacobian as well.
Helper function to compute the element's residual vector and the Jacobian matrix.
Definition at line 882 of file axisym_fluid_traction_elements.h.
References oomph::Multi_domain_functions::Dim, i, oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), s, oomph::Node::value(), and oomph::QuadTreeNames::W.
Referenced by oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::fill_in_contribution_to_residuals().
output() [1/4]
template<class FLUID_BULK_ELEMENT , class SOLID_BULK_ELEMENT >
void oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C-style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 730 of file axisym_fluid_traction_elements.h.
References oomph::CommandLineArgs::output().
output() [2/4]
template<class FLUID_BULK_ELEMENT , class SOLID_BULK_ELEMENT >
void oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 736 of file axisym_fluid_traction_elements.h.
References oomph::CommandLineArgs::output().
output() [3/4]
template<class FLUID_BULK_ELEMENT , class SOLID_BULK_ELEMENT >
void oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Definition at line 682 of file axisym_fluid_traction_elements.h.
References oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::output().
Referenced by oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::output().
output() [4/4]
template<class FLUID_BULK_ELEMENT , class SOLID_BULK_ELEMENT >
void oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: Output at Gauss points; n_plot is ignored.
Reimplemented from oomph::FiniteElement.
Definition at line 690 of file axisym_fluid_traction_elements.h.
References oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::Dim, oomph::ElementWithExternalElement::external_element_local_coord(), oomph::ElementWithExternalElement::external_element_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_zeta(), oomph::Integral::knot(), and oomph::Integral::nweight().
shape_and_test()
template<class FLUID_BULK_ELEMENT , class SOLID_BULK_ELEMENT >
double oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::shape_and_test (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 746 of file axisym_fluid_traction_elements.h.
References i, oomph::FaceElement::J_eulerian(), oomph::FiniteElement::nnode(), s, and oomph::FiniteElement::shape().
shape_and_test_at_knot()
template<class FLUID_BULK_ELEMENT , class SOLID_BULK_ELEMENT >
double oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 770 of file axisym_fluid_traction_elements.h.
References i, oomph::FaceElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape_at_knot().
st()
template<class FLUID_BULK_ELEMENT , class SOLID_BULK_ELEMENT >
double oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::st () const [inline]
Access function for the fluid Strouhal number.
Definition at line 653 of file axisym_fluid_traction_elements.h.
References oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::St_pt.
st_pt()
template<class FLUID_BULK_ELEMENT , class SOLID_BULK_ELEMENT >
double *& oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::st_pt () [inline]
Broken assignment operator.
Access function for the pointer to the fluid Strouhal number (if not set, St defaults to 1)
Definition at line 647 of file axisym_fluid_traction_elements.h.
References oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::St_pt.
Member Data Documentation
Dim
template<class FLUID_BULK_ELEMENT , class SOLID_BULK_ELEMENT >
unsigned oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::Dim [private]
The spatial dimension of the problem.
Definition at line 801 of file axisym_fluid_traction_elements.h.
Referenced by oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::LinearisedFSIAxisymmetricNStNoSlipBCElementElement(), and oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::output().
Id
template<class FLUID_BULK_ELEMENT , class SOLID_BULK_ELEMENT >
unsigned oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::Id [private]
Lagrange Id.
Definition at line 807 of file axisym_fluid_traction_elements.h.
Referenced by oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::LinearisedFSIAxisymmetricNStNoSlipBCElementElement().
St_pt
template<class FLUID_BULK_ELEMENT , class SOLID_BULK_ELEMENT >
double* oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::St_pt [private]
Pointer to fluid Strouhal number.
Definition at line 810 of file axisym_fluid_traction_elements.h.
Referenced by oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::LinearisedFSIAxisymmetricNStNoSlipBCElementElement(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::st(), and oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::st_pt().
U_index_fsi_no_slip_axisym
template<class FLUID_BULK_ELEMENT , class SOLID_BULK_ELEMENT >
Vector<unsigned> oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::U_index_fsi_no_slip_axisym [private]
The index at which the unknowns are stored at the nodes.
Definition at line 804 of file axisym_fluid_traction_elements.h.
Referenced by oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::LinearisedFSIAxisymmetricNStNoSlipBCElementElement().
The documentation for this class was generated from the following file:
axisym_fluid_traction_elements.h