oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D > Class Template Reference
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
#include <gen_axisym_advection_diffusion_elements.h>
Public Member Functions
QGeneralisedAxisymAdvectionDiffusionElement ()
Constructor: Call constructors for QElement and Advection Diffusion equations.
QGeneralisedAxisymAdvectionDiffusionElement (const QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D > &dummy)=delete
Broken copy constructor.
unsigned required_nvalue (const unsigned &n) const
Broken assignment operator.
void output (std::ostream &outfile)
Output function: r,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: r,z,u at n_plot^2 plot points.
void output (FILE *file_pt)
C-style output function: r,z,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: r,z,u at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: r,z,u_exact at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. r,z,u_exact at n_plot^2 plot points (Calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_cons_axisym_adv_diff (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_cons_axisym_adv_diff (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Static Private Attributes
static const unsigned Initial_Nvalue = 1
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
QGeneralisedAxisymAdvectionDiffusionElement elements are linear/quadrilateral/brick-shaped Advection Diffusion elements with isoparametric interpolation for the function.
Definition at line 657 of file gen_axisym_advection_diffusion_elements.h.
Constructor & Destructor Documentation
QGeneralisedAxisymAdvectionDiffusionElement() [1/2]
template<unsigned NNODE_1D>
oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::QGeneralisedAxisymAdvectionDiffusionElement () [inline]
Constructor: Call constructors for QElement and Advection Diffusion equations.
Definition at line 669 of file gen_axisym_advection_diffusion_elements.h.
QGeneralisedAxisymAdvectionDiffusionElement() [2/2]
template<unsigned NNODE_1D>
oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::QGeneralisedAxisymAdvectionDiffusionElement (const QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_cons_axisym_adv_diff()
template<unsigned NNODE_1D>
double oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::dshape_and_dtest_eulerian_at_knot_cons_axisym_adv_diff (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::GeneralisedAxisymAdvectionDiffusionEquations.
Definition at line 806 of file gen_axisym_advection_diffusion_elements.h.
dshape_and_dtest_eulerian_cons_axisym_adv_diff()
template<unsigned NNODE_1D>
double oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::dshape_and_dtest_eulerian_cons_axisym_adv_diff (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::GeneralisedAxisymAdvectionDiffusionEquations.
Definition at line 773 of file gen_axisym_advection_diffusion_elements.h.
References i, and s.
output() [1/4]
template<unsigned NNODE_1D>
void oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function: r,z,u.
Reimplemented from oomph::GeneralisedAxisymAdvectionDiffusionEquations.
Definition at line 707 of file gen_axisym_advection_diffusion_elements.h.
References oomph::GeneralisedAxisymAdvectionDiffusionEquations::output().
output() [2/4]
template<unsigned NNODE_1D>
void oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: r,z,u at n_plot^2 plot points.
Reimplemented from oomph::GeneralisedAxisymAdvectionDiffusionEquations.
Definition at line 714 of file gen_axisym_advection_diffusion_elements.h.
References oomph::GeneralisedAxisymAdvectionDiffusionEquations::output().
output() [3/4]
template<unsigned NNODE_1D>
void oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: r,z,u.
Reimplemented from oomph::GeneralisedAxisymAdvectionDiffusionEquations.
Definition at line 692 of file gen_axisym_advection_diffusion_elements.h.
References oomph::GeneralisedAxisymAdvectionDiffusionEquations::output().
output() [4/4]
template<unsigned NNODE_1D>
void oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: r,z,u at n_plot^2 plot points.
Reimplemented from oomph::GeneralisedAxisymAdvectionDiffusionEquations.
Definition at line 699 of file gen_axisym_advection_diffusion_elements.h.
References oomph::GeneralisedAxisymAdvectionDiffusionEquations::output().
output_fct() [1/2]
template<unsigned NNODE_1D>
void oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. r,z,u_exact at n_plot^2 plot points (Calls the steady version)
Reimplemented from oomph::GeneralisedAxisymAdvectionDiffusionEquations.
Definition at line 733 of file gen_axisym_advection_diffusion_elements.h.
References oomph::GeneralisedAxisymAdvectionDiffusionEquations::output_fct().
output_fct() [2/2]
template<unsigned NNODE_1D>
void oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: r,z,u_exact at n_plot^2 plot points.
Reimplemented from oomph::GeneralisedAxisymAdvectionDiffusionEquations.
Definition at line 721 of file gen_axisym_advection_diffusion_elements.h.
References oomph::GeneralisedAxisymAdvectionDiffusionEquations::output_fct().
required_nvalue()
template<unsigned NNODE_1D>
unsigned oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Broken assignment operator.
Required # of `values' (pinned or dofs) at node n
Reimplemented from oomph::FiniteElement.
Definition at line 685 of file gen_axisym_advection_diffusion_elements.h.
References oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::Initial_Nvalue.
Member Data Documentation
Initial_Nvalue
template<unsigned NNODE_1D>
const unsigned oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::Initial_Nvalue = 1 [static], [private]
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Definition at line 664 of file gen_axisym_advection_diffusion_elements.h.
Referenced by oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::required_nvalue().
The documentation for this class was generated from the following files:
gen_axisym_advection_diffusion_elements.h
gen_axisym_advection_diffusion_elements.cc