oomph::QFoepplvonKarmanElement< NNODE_1D > Class Template Reference
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
#include <foeppl_von_karman_elements.h>
Public Member Functions
QFoepplvonKarmanElement ()
Constructor: Call constructors for QElement and FoepplvonKarmanEquations.
QFoepplvonKarmanElement (const QFoepplvonKarmanElement< NNODE_1D > &dummy)=delete
Broken copy constructor.
void operator= (const QFoepplvonKarmanElement< NNODE_1D > &)=delete
Broken assignment operator.
unsigned required_nvalue (const unsigned &n) const
Required # of `values' (pinned or dofs) at node n.
void output (std::ostream &outfile)
Output function: x,y,w.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,w at n_plot^DIM plot points.
void output (FILE *file_pt)
C-style output function: x,y,w.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,w at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: x,y,w_exact at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. x,y,w_exact at n_plot^DIM plot points (Calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_fvk (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_fvk (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Static Private Attributes
static const unsigned Initial_Nvalue = 8
Static int that holds the number of variables at nodes: always the same.
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::QFoepplvonKarmanElement< NNODE_1D >
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
QFoepplvonKarmanElement elements are linear/quadrilateral/brick-shaped Foeppl von Karman elements with isoparametric interpolation for the function.
Definition at line 490 of file foeppl_von_karman_elements.h.
Constructor & Destructor Documentation
QFoepplvonKarmanElement() [1/2]
template<unsigned NNODE_1D>
oomph::QFoepplvonKarmanElement< NNODE_1D >::QFoepplvonKarmanElement () [inline]
Constructor: Call constructors for QElement and FoepplvonKarmanEquations.
Definition at line 501 of file foeppl_von_karman_elements.h.
QFoepplvonKarmanElement() [2/2]
template<unsigned NNODE_1D>
oomph::QFoepplvonKarmanElement< NNODE_1D >::QFoepplvonKarmanElement (const QFoepplvonKarmanElement< NNODE_1D > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_fvk()
template<unsigned NNODE_1D>
double oomph::QFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_at_knot_fvk (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::FoepplvonKarmanEquations.
Definition at line 632 of file foeppl_von_karman_elements.h.
dshape_and_dtest_eulerian_fvk()
template<unsigned NNODE_1D>
double oomph::QFoepplvonKarmanElement< NNODE_1D >::dshape_and_dtest_eulerian_fvk (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::FoepplvonKarmanEquations.
Definition at line 605 of file foeppl_von_karman_elements.h.
References s.
operator=()
template<unsigned NNODE_1D>
void oomph::QFoepplvonKarmanElement< NNODE_1D >::operator= (const QFoepplvonKarmanElement< NNODE_1D > &) [delete]
Broken assignment operator.
output() [1/4]
template<unsigned NNODE_1D>
void oomph::QFoepplvonKarmanElement< NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function: x,y,w.
Reimplemented from oomph::FoepplvonKarmanEquations.
Definition at line 538 of file foeppl_von_karman_elements.h.
References oomph::FoepplvonKarmanEquations::output().
output() [2/4]
template<unsigned NNODE_1D>
void oomph::QFoepplvonKarmanElement< NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: x,y,w at n_plot^DIM plot points.
Reimplemented from oomph::FoepplvonKarmanEquations.
Definition at line 546 of file foeppl_von_karman_elements.h.
References oomph::FoepplvonKarmanEquations::output().
output() [3/4]
template<unsigned NNODE_1D>
void oomph::QFoepplvonKarmanElement< NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: x,y,w.
Reimplemented from oomph::FoepplvonKarmanEquations.
Definition at line 522 of file foeppl_von_karman_elements.h.
References oomph::FoepplvonKarmanEquations::output().
output() [4/4]
template<unsigned NNODE_1D>
void oomph::QFoepplvonKarmanElement< NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: x,y,w at n_plot^DIM plot points.
Reimplemented from oomph::FoepplvonKarmanEquations.
Definition at line 530 of file foeppl_von_karman_elements.h.
References oomph::FoepplvonKarmanEquations::output().
output_fct() [1/2]
template<unsigned NNODE_1D>
void oomph::QFoepplvonKarmanElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. x,y,w_exact at n_plot^DIM plot points (Calls the steady version)
Reimplemented from oomph::FoepplvonKarmanEquations.
Definition at line 565 of file foeppl_von_karman_elements.h.
References oomph::FoepplvonKarmanEquations::output_fct().
output_fct() [2/2]
template<unsigned NNODE_1D>
void oomph::QFoepplvonKarmanElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: x,y,w_exact at n_plot^DIM plot points.
Reimplemented from oomph::FoepplvonKarmanEquations.
Definition at line 554 of file foeppl_von_karman_elements.h.
References oomph::FoepplvonKarmanEquations::output_fct().
required_nvalue()
template<unsigned NNODE_1D>
unsigned oomph::QFoepplvonKarmanElement< NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Required # of `values' (pinned or dofs) at node n.
Reimplemented from oomph::FiniteElement.
Definition at line 515 of file foeppl_von_karman_elements.h.
References oomph::QFoepplvonKarmanElement< NNODE_1D >::Initial_Nvalue.
Member Data Documentation
Initial_Nvalue
template<unsigned NNODE_1D>
const unsigned oomph::QFoepplvonKarmanElement< NNODE_1D >::Initial_Nvalue = 8 [static], [private]
Static int that holds the number of variables at nodes: always the same.
Set the data for the number of Variables at each node - 8.
Definition at line 496 of file foeppl_von_karman_elements.h.
Referenced by oomph::QFoepplvonKarmanElement< NNODE_1D >::required_nvalue().
The documentation for this class was generated from the following files:
foeppl_von_karman_elements.h
foeppl_von_karman_elements.cc