oomph::PMLTimeHarmonicLinearElasticityEquations< DIM > Class Template Reference
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
#include <pml_time_harmonic_linear_elasticity_elements.h>
Public Member Functions
PMLTimeHarmonicLinearElasticityEquations ()
Constructor.
unsigned required_nvalue (const unsigned &n) const
Number of values required at node n.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Return the residuals for the solid equations (the discretised principle of virtual displacements)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
The jacobian is calculated by finite differences by default, We need only to take finite differences w.r.t. positional variables For this element.
void get_stress (const Vector< double > &s, DenseMatrix< std::complex< double > > &sigma) const
Return the Cauchy stress tensor, as calculated from the elasticity tensor at specified local coordinate.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact solution x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
void output (std::ostream &outfile)
Output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
void output (std::ostream &outfile, const unsigned &n_plot)
Output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
void output (FILE *file_pt)
C-style output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
void output (FILE *file_pt, const unsigned &n_plot)
Output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
void output_total_real (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt incoming_wave_fct_pt, const double &phi, const unsigned &nplot)
Output function for real part of full time-dependent solution constructed by adding the scattered field u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi computed here, to the corresponding incoming wave specified via the function pointer.
void output_real (std::ostream &outfile, const double &phi, const unsigned &n_plot)
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
void output_imag (std::ostream &outfile, const double &phi, const unsigned &n_plot)
Output function for imaginary part of full time-dependent solution u = Im((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
void compute_norm (double &norm)
Compute norm of solution: square of the L2 norm.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
Private Member Functions
virtual void fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Private helper function to compute residuals and (if requested via flag) also the Jacobian matrix.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
A class for elements that solve the equations of linear elasticity in cartesian coordinates.
Definition at line 446 of file pml_time_harmonic_linear_elasticity_elements.h.
Constructor & Destructor Documentation
PMLTimeHarmonicLinearElasticityEquations()
template<unsigned DIM>
oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::PMLTimeHarmonicLinearElasticityEquations () [inline]
Constructor.
Definition at line 451 of file pml_time_harmonic_linear_elasticity_elements.h.
Member Function Documentation
compute_error() [1/2]
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution.
Solution is provided via function pointer.
Reimplemented from oomph::FiniteElement.
Definition at line 923 of file pml_time_harmonic_linear_elasticity_elements.cc.
References i, s, oomph::W, and oomph::x.
compute_error() [2/2]
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [inline], [virtual]
Dummy, time dependent error checker.
Reimplemented from oomph::FiniteElement.
Definition at line 551 of file pml_time_harmonic_linear_elasticity_elements.h.
compute_norm()
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::compute_norm (double & norm) [virtual]
Compute norm of solution: square of the L2 norm.
Compute norm of the solution.
Reimplemented from oomph::GeneralisedElement.
Definition at line 863 of file pml_time_harmonic_linear_elasticity_elements.cc.
References i, s, oomph::W, and oomph::x.
fill_in_contribution_to_jacobian()
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
The jacobian is calculated by finite differences by default, We need only to take finite differences w.r.t. positional variables For this element.
Reimplemented from oomph::FiniteElement.
Definition at line 470 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::FiniteElement::jacobian.
fill_in_contribution_to_residuals()
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Return the residuals for the solid equations (the discretised principle of virtual displacements)
Reimplemented from oomph::GeneralisedElement.
Definition at line 461 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity().
fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity()
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [private], [virtual]
Private helper function to compute residuals and (if requested via flag) also the Jacobian matrix.
Compute the residuals for the linear elasticity equations in cartesian coordinates. Flag indicates if we want Jacobian too. All the PML weights that participate in the assemby process are computed here. pml_inverse_jacobian_diagonals are are used to transform derivatives in real x to derivatives in transformed space $\tilde x $. pml_jacobian_det allows us to transform volume integrals in transformed space to real space. If the PML is not enabled via enable_pml, both default to 1.0.
Definition at line 196 of file pml_time_harmonic_linear_elasticity_elements.cc.
References oomph::QuadTreeNames::E, i, s, and oomph::W.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::fill_in_contribution_to_residuals().
get_stress()
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::get_stress (const Vector< double > & s, DenseMatrix< std::complex< double > > & sigma) const [virtual]
Return the Cauchy stress tensor, as calculated from the elasticity tensor at specified local coordinate.
Compute the Cauchy stress tensor at local coordinate s for displacement formulation.
Implements oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >.
Definition at line 152 of file pml_time_harmonic_linear_elasticity_elements.cc.
References oomph::QuadTreeNames::E, i, and s.
output() [1/4]
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output (FILE * file_pt) [inline], [virtual]
C-style output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::QPMLTimeHarmonicLinearElasticityElement< 2, NNODE_1D >, and oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >.
Definition at line 501 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output().
output() [2/4]
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output (FILE * file_pt, const unsigned & n_plot) [virtual]
Output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
C-style output: x,y,[z],u,v,[w].
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::QPMLTimeHarmonicLinearElasticityElement< 2, NNODE_1D >, and oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >.
Definition at line 814 of file pml_time_harmonic_linear_elasticity_elements.cc.
References i, and s.
output() [3/4]
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output (std::ostream & outfile) [inline], [virtual]
Output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::QPMLTimeHarmonicLinearElasticityElement< 2, NNODE_1D >, and oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >.
Definition at line 490 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output().
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output(), oomph::QPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >::output(), and oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >::output().
output() [4/4]
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output (std::ostream & outfile, const unsigned & n_plot) [virtual]
Output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
Output: x,y,[z],u,v,[w].
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::QPMLTimeHarmonicLinearElasticityElement< 2, NNODE_1D >, and oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >.
Definition at line 589 of file pml_time_harmonic_linear_elasticity_elements.cc.
References i, s, oomph::u, and oomph::x.
output_fct()
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact solution x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
Reimplemented from oomph::FiniteElement.
Definition at line 538 of file pml_time_harmonic_linear_elasticity_elements.cc.
References i, s, and oomph::x.
output_imag()
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output_imag (std::ostream & outfile, const double & phi, const unsigned & nplot)
Output function for imaginary part of full time-dependent solution u = Im((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
Output function for imaginary part of full time-dependent solution.
u = Im((u_r +i u_i) exp(-i omega t))
at phase angle omega t = phi.
x,y,u or x,y,z,u
Output at nplot points in each coordinate direction
Definition at line 768 of file pml_time_harmonic_linear_elasticity_elements.cc.
References i, s, oomph::u, and oomph::x.
output_real()
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output_real (std::ostream & outfile, const double & phi, const unsigned & nplot)
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
Output function for imaginary part of full time-dependent solution.
u = Im((u_r +i u_i) exp(-i omega t))
at phase angle omega t = phi.
x,y,u or x,y,z,u
Output at nplot points in each coordinate direction
Definition at line 715 of file pml_time_harmonic_linear_elasticity_elements.cc.
References i, s, oomph::u, and oomph::x.
output_total_real()
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output_total_real (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt incoming_wave_fct_pt, const double & phi, const unsigned & nplot)
Output function for real part of full time-dependent solution constructed by adding the scattered field u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi computed here, to the corresponding incoming wave specified via the function pointer.
Output function for real part of full time-dependent solution constructed by adding the scattered field.
u = Re((u_r +i u_i) exp(-i omega t)
at phase angle omega t = phi computed here, to the corresponding incoming wave specified via the function pointer.
x,y,u or x,y,z,u
Output at nplot points in each coordinate direction
Definition at line 651 of file pml_time_harmonic_linear_elasticity_elements.cc.
References i, s, oomph::u, and oomph::x.
required_nvalue()
template<unsigned DIM>
unsigned oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values required at node n.
Reimplemented from oomph::FiniteElement.
Definition at line 454 of file pml_time_harmonic_linear_elasticity_elements.h.
The documentation for this class was generated from the following files:
pml_time_harmonic_linear_elasticity_elements.h
pml_time_harmonic_linear_elasticity_elements.cc