oomph::DistributableLinearAlgebraObject Class Reference
Base class for any linear algebra object that is distributable. Just contains storage for the LinearAlgebraDistribution object and access functions.
#include <linear_algebra_distribution.h>
Public Member Functions
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
setup the distribution of this distributable linear algebra object
void build_distribution (const LinearAlgebraDistribution &dist)
setup the distribution of this distributable linear algebra object
Protected Member Functions
void clear_distribution ()
clear the distribution of this distributable linear algebra object
Private Attributes
LinearAlgebraDistribution * Distribution_pt
the LinearAlgebraDistribution object
Detailed Description
Base class for any linear algebra object that is distributable. Just contains storage for the LinearAlgebraDistribution object and access functions.
Definition at line 434 of file linear_algebra_distribution.h.
Constructor & Destructor Documentation
DistributableLinearAlgebraObject() [1/2]
oomph::DistributableLinearAlgebraObject::DistributableLinearAlgebraObject () [inline]
Default constructor - create a distribution.
Definition at line 438 of file linear_algebra_distribution.h.
References Distribution_pt.
DistributableLinearAlgebraObject() [2/2]
oomph::DistributableLinearAlgebraObject::DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject & matrix) [inline]
Broken copy constructor.
Definition at line 444 of file linear_algebra_distribution.h.
References oomph::BrokenCopy::broken_copy().
 DistributableLinearAlgebraObject()
virtual oomph::DistributableLinearAlgebraObject::~DistributableLinearAlgebraObject () [inline], [virtual]
Destructor.
Definition at line 457 of file linear_algebra_distribution.h.
References Distribution_pt.
Member Function Documentation
build_distribution() [1/2]
void oomph::DistributableLinearAlgebraObject::build_distribution (const LinearAlgebraDistribution & dist) [inline]
setup the distribution of this distributable linear algebra object
Definition at line 520 of file linear_algebra_distribution.h.
References oomph::LinearAlgebraDistribution::build(), and Distribution_pt.
build_distribution() [2/2]
void oomph::DistributableLinearAlgebraObject::build_distribution (const LinearAlgebraDistribution *const dist_pt) [inline]
setup the distribution of this distributable linear algebra object
Definition at line 513 of file linear_algebra_distribution.h.
References oomph::LinearAlgebraDistribution::build(), and Distribution_pt.
Referenced by oomph::DoubleVector::build(), oomph::DoubleMultiVector::build(), oomph::CRDoubleMatrix::build(), oomph::CRDoubleMatrix::CRDoubleMatrix(), oomph::MumpsSolver::factorise(), oomph::SuperLUSolver::factorise_distributed(), oomph::DoubleVector::redistribute(), oomph::DoubleMultiVector::redistribute(), oomph::AugmentedBlockPitchForkLinearSolver::resolve(), oomph::DoubleVector::set_external_values(), oomph::SuperLUPreconditioner::setup(), oomph::MatrixBasedDiagPreconditioner::setup(), oomph::MatrixVectorProduct::setup(), oomph::TrilinosPreconditionerBase::setup(), oomph::IdentityPreconditioner::setup(), oomph::NewMumpsPreconditioner::setup(), oomph::ILUZeroPreconditioner< CCDoubleMatrix >::setup(), oomph::ILUZeroPreconditioner< CRDoubleMatrix >::setup(), oomph::InnerIterationPreconditioner< SOLVER, PRECONDITIONER >::setup(), oomph::HyprePreconditioner::setup(), oomph::DoubleMultiVector::shallow_build(), oomph::MumpsSolver::solve(), oomph::HSL_MA42::solve(), oomph::CG< MATRIX >::solve(), oomph::DenseLU::solve(), oomph::TrilinosAztecOOSolver::solve(), oomph::AugmentedBlockFoldLinearSolver::solve(), oomph::BiCGStab< MATRIX >::solve(), oomph::SuperLUSolver::solve(), oomph::BlockPitchForkLinearSolver::solve(), oomph::GS< MATRIX >::solve(), oomph::AugmentedBlockPitchForkLinearSolver::solve(), oomph::HypreSolver::solve(), oomph::GS< CRDoubleMatrix >::solve(), oomph::BlockHopfLinearSolver::solve(), oomph::DampedJacobi< MATRIX >::solve(), oomph::GMRES< MATRIX >::solve(), oomph::AugmentedProblemGMRES::solve(), oomph::HelmholtzGMRESMG< MATRIX >::solve(), oomph::HelmholtzFGMRESMG< MATRIX >::solve(), oomph::ARPACK::solve_eigenproblem(), oomph::LAPACK_QZ::solve_eigenproblem(), oomph::BlockHopfLinearSolver::solve_for_two_rhs(), oomph::SuperLUSolver::solve_transpose(), and oomph::TrilinosAztecOOSolver::solver_setup().
clear_distribution()
void oomph::DistributableLinearAlgebraObject::clear_distribution () [inline], [protected]
clear the distribution of this distributable linear algebra object
Definition at line 528 of file linear_algebra_distribution.h.
References oomph::LinearAlgebraDistribution::clear(), and Distribution_pt.
Referenced by oomph::DenseLU::clean_up_memory(), oomph::SuperLUSolver::clean_up_memory(), oomph::DoubleVector::clear(), oomph::DoubleMultiVector::clear(), oomph::CRDoubleMatrix::clear(), and oomph::BlockPreconditioner< CRDoubleMatrix >::clear_block_preconditioner_base().
distributed()
bool oomph::DistributableLinearAlgebraObject::distributed () const [inline]
distribution is serial or distributed
Definition at line 499 of file linear_algebra_distribution.h.
References oomph::LinearAlgebraDistribution::distributed(), and Distribution_pt.
Referenced by oomph::NavierStokesSchurComplementPreconditioner::assemble_inv_press_and_veloc_mass_matrix_diagonal(), oomph::PressureBasedSolidLSCPreconditioner::assemble_mass_matrix_diagonal(), oomph::HelmholtzSmoother::check_validity_of_solve_helper_inputs(), oomph::Smoother::check_validity_of_solve_helper_inputs(), oomph::DoubleVectorHelpers::concatenate(), oomph::CRDoubleMatrixHelpers::concatenate(), oomph::DoubleVectorHelpers::concatenate_without_communication(), oomph::CRDoubleMatrixHelpers::concatenate_without_communication(), oomph::TrilinosEpetraHelpers::copy_to_oomphlib_vector(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_matrix(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_matrix_for_aztecoo(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_vector(), oomph::HypreHelpers::create_HYPRE_Matrix(), oomph::HypreHelpers::create_HYPRE_Vector(), oomph::DoubleVector::dot(), oomph::DoubleMultiVector::dot(), oomph::CRDoubleMatrix::entries_are_sorted(), oomph::MumpsSolver::factorise(), oomph::SuperLUSolver::factorise_distributed(), oomph::SuperLUSolver::factorise_serial(), oomph::CRDoubleMatrix::get_matrix_transpose(), oomph::CRDoubleMatrix::global_matrix(), oomph::DoubleVectorWithHaloEntries::global_value(), oomph::CRDoubleMatrix::inf_norm(), oomph::DoubleVector::max(), oomph::CRDoubleMatrix::multiply(), oomph::DenseDoubleMatrix::multiply(), oomph::CCDoubleMatrix::multiply(), oomph::CRDoubleMatrix::multiply_transpose(), oomph::DenseDoubleMatrix::multiply_transpose(), oomph::CCDoubleMatrix::multiply_transpose(), Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvTransMv(), oomph::DoubleVector::norm(), oomph::DoubleMultiVector::norm(), oomph::DoubleVector::output(), oomph::DoubleMultiVector::output(), oomph::ILUZeroPreconditioner< CCDoubleMatrix >::preconditioner_solve(), oomph::ILUZeroPreconditioner< CRDoubleMatrix >::preconditioner_solve(), oomph::DoubleVector::redistribute(), oomph::DoubleMultiVector::redistribute(), oomph::CRDoubleMatrix::redistribute(), oomph::AugmentedBlockFoldLinearSolver::resolve(), oomph::ILUZeroPreconditioner< CRDoubleMatrix >::setup(), oomph::AugmentedBlockFoldLinearSolver::solve(), oomph::FD_LU::solve(), oomph::AugmentedBlockPitchForkLinearSolver::solve(), oomph::BlockHopfLinearSolver::solve(), oomph::BlockHopfLinearSolver::solve_for_two_rhs(), oomph::AugmentedProblemGMRES::solve_helper(), oomph::CRDoubleMatrix::sort_entries(), oomph::DoubleVectorHelpers::split(), oomph::DoubleVectorHelpers::split_without_communication(), oomph::DoubleVectorWithHaloEntries::sum_all_halo_and_haloed_values(), and oomph::DoubleVectorWithHaloEntries::synchronise().
distribution_built()
bool oomph::DistributableLinearAlgebraObject::distribution_built () const [inline]
if the communicator_pt is null then the distribution is not setup then false is returned, otherwise return true
Definition at line 506 of file linear_algebra_distribution.h.
References oomph::LinearAlgebraDistribution::built(), and Distribution_pt.
Referenced by oomph::MumpsSolver::backsub(), oomph::SuperLUSolver::backsub_distributed(), oomph::DoubleVector::build(), oomph::DoubleMultiVector::build(), oomph::Problem::get_eigenproblem_matrices(), oomph::Problem::get_jacobian(), oomph::CRDoubleMatrix::inf_norm(), oomph::CRDoubleMatrix::multiply(), oomph::DoubleVector::operator*=(), oomph::DoubleMultiVector::operator*=(), oomph::DoubleVector::operator-=(), oomph::DoubleMultiVector::operator-=(), oomph::TrilinosAztecOOSolver::resolve(), oomph::DoubleVector::set_external_values(), oomph::DoubleMultiVector::shallow_build(), and oomph::DenseLU::solve().
distribution_pt()
LinearAlgebraDistribution* oomph::DistributableLinearAlgebraObject::distribution_pt () const [inline]
access to the LinearAlgebraDistribution
Definition at line 463 of file linear_algebra_distribution.h.
References Distribution_pt.
Referenced by oomph::CRDoubleMatrix::add(), oomph::ProblemBasedShiftInvertOperator::apply(), oomph::AugmentedProblemGMRES::apply_schur_complement_preconditioner(), oomph::OomphLibPreconditionerEpetraOperator::ApplyInverse(), oomph::AugmentedProblemGMRES::augmented_matrix_multiply(), oomph::MumpsSolver::backsub(), oomph::SuperLUSolver::backsub_distributed(), oomph::SuperLUSolver::backsub_serial(), oomph::SuperLUSolver::backsub_transpose_serial(), oomph::DoubleVector::build(), oomph::DoubleMultiVector::build(), oomph::HelmholtzSmoother::check_validity_of_solve_helper_inputs(), oomph::Smoother::check_validity_of_solve_helper_inputs(), oomph::SuperLUSolver::clean_up_memory(), oomph::HelmholtzSmoother::complex_matrix_multiplication(), oomph::HelmholtzGMRESMG< MATRIX >::complex_matrix_multiplication(), oomph::DoubleVectorHelpers::concatenate(), oomph::CRDoubleMatrixHelpers::concatenate(), oomph::DoubleVectorHelpers::concatenate_without_communication(), oomph::CRDoubleMatrixHelpers::concatenate_without_communication(), oomph::TrilinosEpetraHelpers::copy_to_oomphlib_vector(), oomph::CRDoubleMatrix::CRDoubleMatrix(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_matrix(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_matrix_for_aztecoo(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_vector(), oomph::TrilinosEpetraHelpers::create_epetra_vector_view_data(), oomph::HypreHelpers::create_HYPRE_Matrix(), oomph::HypreHelpers::create_HYPRE_Vector(), oomph::CRDoubleMatrixHelpers::deep_copy(), oomph::DoubleVector::dot(), oomph::DoubleMultiVector::dot(), oomph::DoubleMultiVector::DoubleMultiVector(), oomph::MumpsSolver::factorise(), oomph::SuperLUSolver::factorise(), oomph::SuperLUSolver::factorise_distributed(), oomph::BlockPreconditioner< CRDoubleMatrix >::get_block_ordered_preconditioner_vector(), oomph::BlockPreconditioner< CRDoubleMatrix >::get_block_vector(), oomph::BlockPreconditioner< CRDoubleMatrix >::get_block_vectors(), oomph::BlockPreconditioner< CRDoubleMatrix >::get_concatenated_block(), oomph::BlockPreconditioner< CRDoubleMatrix >::get_concatenated_block_vector(), oomph::Problem::get_eigenproblem_matrices(), oomph::Problem::get_hessian_vector_products(), oomph::Problem::get_jacobian(), oomph::CRDoubleMatrix::get_matrix_transpose(), oomph::CRDoubleMatrix::global_matrix(), oomph::HypreInterface::hypre_matrix_setup(), oomph::HypreInterface::hypre_solve(), oomph::CRDoubleMatrix::inf_norm(), oomph::BlockPreconditioner< CRDoubleMatrix >::internal_dof_number(), oomph::BlockPreconditioner< CRDoubleMatrix >::internal_get_block(), oomph::BlockPreconditioner< CRDoubleMatrix >::internal_get_block_ordered_preconditioner_vector(), oomph::BlockPreconditioner< CRDoubleMatrix >::internal_get_block_vector(), oomph::BlockPreconditioner< CRDoubleMatrix >::internal_get_block_vectors(), oomph::BlockPreconditioner< CRDoubleMatrix >::internal_index_in_dof(), oomph::BlockPreconditioner< CRDoubleMatrix >::internal_preconditioner_matrix_distribution_pt(), oomph::BlockPreconditioner< CRDoubleMatrix >::internal_return_block_ordered_preconditioner_vector(), oomph::BlockPreconditioner< CRDoubleMatrix >::internal_return_block_vector(), oomph::BlockPreconditioner< CRDoubleMatrix >::internal_return_block_vectors(), oomph::CRDoubleMatrix::lubksub(), oomph::BlockPreconditioner< CRDoubleMatrix >::master_distribution_pt(), oomph::DoubleVector::max(), oomph::MatrixVectorProduct::multiply(), oomph::TrilinosEpetraHelpers::multiply(), oomph::CRDoubleMatrix::multiply(), oomph::DenseDoubleMatrix::multiply(), oomph::CCDoubleMatrix::multiply(), oomph::MatrixVectorProduct::multiply_transpose(), oomph::CRDoubleMatrix::multiply_transpose(), oomph::DenseDoubleMatrix::multiply_transpose(), oomph::CCDoubleMatrix::multiply_transpose(), Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvTransMv(), oomph::DoubleVector::norm(), oomph::DoubleMultiVector::norm(), oomph::OomphLibPreconditionerEpetraOperator::OomphLibPreconditionerEpetraOperator(), oomph::DoubleVector::operator+=(), oomph::DoubleMultiVector::operator+=(), oomph::DoubleVector::operator-=(), oomph::DoubleMultiVector::operator-=(), oomph::DoubleVector::output(), oomph::DoubleMultiVector::output(), oomph::PitchForkHandler::PitchForkHandler(), oomph::MatrixBasedDiagPreconditioner::preconditioner_solve(), oomph::MatrixBasedLumpedPreconditioner< oomph::CRDoubleMatrix >::preconditioner_solve(), oomph::TrilinosPreconditionerBase::preconditioner_solve(), oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::preconditioner_solve(), oomph::FSIPreconditioner::preconditioner_solve(), oomph::PressureBasedSolidLSCPreconditioner::preconditioner_solve(), oomph::LagrangeEnforcedFlowPreconditioner::preconditioner_solve(), oomph::BandedBlockTriangularPreconditioner< MATRIX >::preconditioner_solve(), oomph::ILUZeroPreconditioner< CCDoubleMatrix >::preconditioner_solve(), oomph::IdentityPreconditioner::preconditioner_solve(), oomph::GMRESBlockPreconditioner::preconditioner_solve(), oomph::ILUZeroPreconditioner< CRDoubleMatrix >::preconditioner_solve(), oomph::BlockDiagonalPreconditioner< MATRIX >::preconditioner_solve(), oomph::BlockTriangularPreconditioner< MATRIX >::preconditioner_solve(), oomph::NavierStokesSchurComplementPreconditioner::preconditioner_solve(), oomph::HyprePreconditioner::preconditioner_solve(), oomph::DoubleVector::redistribute(), oomph::DoubleMultiVector::redistribute(), oomph::CRDoubleMatrix::redistribute(), oomph::MumpsSolver::resolve(), oomph::HSL_MA42::resolve(), oomph::TrilinosAztecOOSolver::resolve(), oomph::AugmentedBlockFoldLinearSolver::resolve(), oomph::BlockPitchForkLinearSolver::resolve(), oomph::AugmentedBlockPitchForkLinearSolver::resolve(), oomph::HypreSolver::resolve(), oomph::BlockPreconditioner< CRDoubleMatrix >::return_block_ordered_preconditioner_vector(), oomph::BlockPreconditioner< CRDoubleMatrix >::return_block_vector(), oomph::BlockPreconditioner< CRDoubleMatrix >::return_block_vectors(), oomph::BlockPreconditioner< CRDoubleMatrix >::return_concatenated_block_vector(), oomph::SuperLUPreconditioner::setup(), oomph::MatrixBasedDiagPreconditioner::setup(), oomph::MatrixVectorProduct::setup(), oomph::TrilinosPreconditionerBase::setup(), oomph::MatrixBasedLumpedPreconditioner< oomph::CRDoubleMatrix >::setup(), oomph::LagrangeEnforcedFlowPreconditioner::setup(), oomph::IdentityPreconditioner::setup(), oomph::NewMumpsPreconditioner::setup(), oomph::ILUZeroPreconditioner< CRDoubleMatrix >::setup(), oomph::InnerIterationPreconditioner< SOLVER, PRECONDITIONER >::setup(), oomph::HyprePreconditioner::setup(), oomph::DoubleMultiVector::setup_doublevector_representation(), oomph::DoubleMultiVector::shallow_build(), oomph::MumpsSolver::solve(), oomph::CG< MATRIX >::solve(), oomph::DenseLU::solve(), oomph::TrilinosAztecOOSolver::solve(), oomph::AugmentedBlockFoldLinearSolver::solve(), oomph::BiCGStab< MATRIX >::solve(), oomph::SuperLUSolver::solve(), oomph::BlockPitchForkLinearSolver::solve(), oomph::GS< MATRIX >::solve(), oomph::AugmentedBlockPitchForkLinearSolver::solve(), oomph::HypreSolver::solve(), oomph::GS< CRDoubleMatrix >::solve(), oomph::BlockHopfLinearSolver::solve(), oomph::DampedJacobi< MATRIX >::solve(), oomph::GMRES< MATRIX >::solve(), oomph::AugmentedProblemGMRES::solve(), oomph::HelmholtzGMRESMG< MATRIX >::solve(), oomph::HelmholtzFGMRESMG< MATRIX >::solve(), oomph::ARPACK::solve_eigenproblem(), oomph::LAPACK_QZ::solve_eigenproblem(), oomph::BlockHopfLinearSolver::solve_for_two_rhs(), oomph::CG< MATRIX >::solve_helper(), oomph::BiCGStab< MATRIX >::solve_helper(), oomph::GS< MATRIX >::solve_helper(), oomph::GS< CRDoubleMatrix >::solve_helper(), oomph::DampedJacobi< MATRIX >::solve_helper(), oomph::GMRES< MATRIX >::solve_helper(), oomph::AugmentedProblemGMRES::solve_helper(), oomph::HelmholtzGMRESMG< MATRIX >::solve_helper(), oomph::HelmholtzFGMRESMG< MATRIX >::solve_helper(), oomph::SuperLUSolver::solve_transpose(), oomph::TrilinosAztecOOSolver::solver_setup(), oomph::CRDoubleMatrix::sparse_indexed_output_with_offset(), oomph::DoubleVectorHelpers::split(), oomph::DoubleVectorHelpers::split_without_communication(), oomph::LowStorageRungeKutta< ORDER >::timestep(), oomph::GMRESBlockPreconditioner::update(), oomph::GMRES< MATRIX >::update(), oomph::AugmentedProblemGMRES::update(), oomph::HelmholtzGMRESMG< MATRIX >::update(), and oomph::HelmholtzFGMRESMG< MATRIX >::update().
first_row() [1/2]
unsigned oomph::DistributableLinearAlgebraObject::first_row () const [inline]
access function for the first row on this processor
Definition at line 487 of file linear_algebra_distribution.h.
References Distribution_pt, and oomph::LinearAlgebraDistribution::first_row().
Referenced by oomph::PressureBasedSolidLSCPreconditioner::assemble_mass_matrix_diagonal(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_matrix_for_aztecoo(), oomph::CRDoubleMatrix::diagonal_entries(), oomph::MumpsSolver::factorise(), oomph::SuperLUSolver::factorise_distributed(), oomph::CRDoubleMatrix::global_matrix(), oomph::DoubleVectorWithHaloEntries::global_value(), oomph::DoubleVector::initialise(), oomph::BlockPreconditioner< CRDoubleMatrix >::internal_dof_number(), oomph::BlockPreconditioner< CRDoubleMatrix >::internal_index_in_dof(), oomph::TrilinosEpetraHelpers::multiply(), oomph::DoubleVector::output(), oomph::DoubleMultiVector::output(), oomph::DoubleVector::output_local_values_with_offset(), oomph::DoubleVector::redistribute(), oomph::DoubleMultiVector::redistribute(), oomph::CRDoubleMatrix::redistribute(), oomph::MatrixBasedDiagPreconditioner::setup(), oomph::PseudoElasticPreconditionerSubsidiaryPreconditionerOld::setup(), oomph::CRDoubleMatrix::sparse_indexed_output_with_offset(), and oomph::DoubleVectorHelpers::split().
first_row() [2/2]
unsigned oomph::DistributableLinearAlgebraObject::first_row (const unsigned & p) const [inline]
access function for the first row on this processor
Definition at line 493 of file linear_algebra_distribution.h.
References Distribution_pt, and oomph::LinearAlgebraDistribution::first_row().
nrow()
unsigned oomph::DistributableLinearAlgebraObject::nrow () const [inline]
access function to the number of global rows.
Definition at line 469 of file linear_algebra_distribution.h.
References Distribution_pt, and oomph::LinearAlgebraDistribution::nrow().
Referenced by oomph::IMRByBDF::actions_after_timestep(), oomph::Problem::add_eigenvector_to_dofs(), oomph::PressureBasedSolidLSCPreconditioner::assemble_mass_matrix_diagonal(), oomph::Problem::assign_eigenvector_to_dofs(), oomph::DenseLU::backsub(), oomph::SuperLUSolver::backsub_serial(), oomph::SuperLUSolver::backsub_transpose_serial(), oomph::BlockPreconditioner< CRDoubleMatrix >::block_matrix_test(), oomph::HelmholtzSmoother::check_validity_of_solve_helper_inputs(), oomph::Smoother::check_validity_of_solve_helper_inputs(), oomph::ComplexGMRES< MATRIX >::complex_smoother_setup(), oomph::DoubleVectorHelpers::concatenate(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_vector(), oomph::SuperLUSolver::factorise_distributed(), Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::GetVecLength(), oomph::BlockPreconditioner< CRDoubleMatrix >::internal_get_block_vector(), oomph::HelmholtzMGPreconditioner< DIM >::interpolation_matrix_set(), oomph::MGSolver< DIM >::interpolation_matrix_set(), oomph::DoubleVector::max(), oomph::DenseDoubleMatrix::multiply(), oomph::CCDoubleMatrix::multiply(), oomph::DenseDoubleMatrix::multiply_transpose(), oomph::CCDoubleMatrix::multiply_transpose(), oomph::CRDoubleMatrix::nrow(), oomph::DoubleVector::output(), oomph::DoubleMultiVector::output(), oomph::LagrangeEnforcedFlowPreconditioner::preconditioner_solve(), oomph::PressureBasedSolidLSCPreconditioner::preconditioner_solve(), oomph::ILUZeroPreconditioner< CCDoubleMatrix >::preconditioner_solve(), oomph::ILUZeroPreconditioner< CRDoubleMatrix >::preconditioner_solve(), oomph::NavierStokesSchurComplementPreconditioner::preconditioner_solve(), oomph::MGPreconditioner< DIM >::preconditioner_solve(), oomph::DoubleVector::redistribute(), oomph::DoubleMultiVector::redistribute(), oomph::HSL_MA42::resolve(), oomph::TrilinosAztecOOSolver::resolve(), oomph::SuperLUSolver::resolve(), oomph::SuperLUSolver::resolve_transpose(), oomph::Problem::set_dofs(), oomph::TrilinosPreconditionerBase::setup(), oomph::InnerIterationPreconditioner< SOLVER, PRECONDITIONER >::setup(), oomph::HyprePreconditioner::setup(), oomph::MumpsSolver::solve(), oomph::DenseLU::solve(), oomph::TrilinosAztecOOSolver::solve(), oomph::SuperLUSolver::solve(), oomph::CG< MATRIX >::solve_helper(), oomph::BiCGStab< MATRIX >::solve_helper(), oomph::GS< MATRIX >::solve_helper(), oomph::GS< CRDoubleMatrix >::solve_helper(), oomph::DampedJacobi< MATRIX >::solve_helper(), oomph::GMRES< MATRIX >::solve_helper(), oomph::AugmentedProblemGMRES::solve_helper(), oomph::HelmholtzGMRESMG< MATRIX >::solve_helper(), oomph::HelmholtzFGMRESMG< MATRIX >::solve_helper(), oomph::SuperLUSolver::solve_transpose(), oomph::DoubleVectorHelpers::split(), oomph::LowStorageRungeKutta< ORDER >::timestep(), oomph::GMRESBlockPreconditioner::update(), oomph::GMRES< MATRIX >::update(), and oomph::AugmentedProblemGMRES::update().
nrow_local() [1/2]
unsigned oomph::DistributableLinearAlgebraObject::nrow_local () const [inline]
access function for the num of local rows on this processor.
Definition at line 475 of file linear_algebra_distribution.h.
References Distribution_pt, and oomph::LinearAlgebraDistribution::nrow_local().
Referenced by oomph::CRDoubleMatrix::add(), oomph::Problem::add_eigenvector_to_dofs(), oomph::ProblemBasedShiftInvertOperator::apply(), oomph::PressureBasedSolidLSCPreconditioner::assemble_mass_matrix_diagonal(), oomph::Problem::assign_eigenvector_to_dofs(), oomph::DoubleVector::build(), oomph::DoubleMultiVector::build(), oomph::CRDoubleMatrix::build(), oomph::CRDoubleMatrix::build_without_copy(), oomph::TrilinosEpetraHelpers::copy_to_oomphlib_vector(), oomph::CRDoubleMatrix::CRDoubleMatrix(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_matrix_for_aztecoo(), oomph::CRDoubleMatrixHelpers::deep_copy(), oomph::CRDoubleMatrix::diagonal_entries(), oomph::DoubleVector::dot(), oomph::DoubleMultiVector::dot(), oomph::DoubleMultiVector::DoubleMultiVector(), oomph::SuperLUSolver::factorise_distributed(), oomph::Problem::get_derivative_wrt_global_parameter(), oomph::CRDoubleMatrix::global_matrix(), oomph::DoubleVectorWithHaloEntries::global_value(), oomph::CRDoubleMatrix::inf_norm(), oomph::DoubleVector::initialise(), oomph::DoubleMultiVector::initialise(), oomph::BlockPreconditioner< CRDoubleMatrix >::internal_dof_number(), oomph::BlockPreconditioner< CRDoubleMatrix >::internal_index_in_dof(), oomph::PseudoElasticPreconditioner::lagrange_multiplier_preconditioner_solve(), oomph::PseudoElasticPreconditionerOld::lagrange_multiplier_preconditioner_solve(), oomph::CRDoubleMatrix::matrix_reduction(), oomph::DoubleVector::max(), oomph::TrilinosEpetraHelpers::multiply(), Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvAddMv(), Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvRandom(), Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvScale(), Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvTimesMatAddMv(), Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvTransMv(), oomph::DoubleVector::norm(), oomph::DoubleMultiVector::norm(), oomph::DoubleMultiVector::operator()(), oomph::DoubleVector::operator*=(), oomph::DoubleMultiVector::operator*=(), oomph::DoubleVector::operator+=(), oomph::DoubleMultiVector::operator+=(), oomph::DoubleVector::operator-=(), oomph::DoubleMultiVector::operator-=(), oomph::DoubleVector::operator==(), oomph::DoubleMultiVector::operator==(), oomph::DoubleVector::operator[](), oomph::DoubleVector::output(), oomph::DoubleMultiVector::output(), oomph::DoubleVector::output_local_values(), oomph::DoubleVector::output_local_values_with_offset(), oomph::MatrixBasedDiagPreconditioner::preconditioner_solve(), oomph::LagrangeEnforcedFlowPreconditioner::preconditioner_solve(), oomph::DoubleVector::redistribute(), oomph::DoubleMultiVector::redistribute(), oomph::CRDoubleMatrix::redistribute(), oomph::DoubleMatrixBase::residual(), oomph::BlockPitchForkLinearSolver::resolve(), Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::SetBlock(), oomph::MatrixBasedDiagPreconditioner::setup(), oomph::MatrixBasedLumpedPreconditioner< oomph::CRDoubleMatrix >::setup(), oomph::PseudoElasticPreconditionerSubsidiaryPreconditionerOld::setup(), oomph::HyprePreconditioner::setup(), oomph::ANASAZI::solve_eigenproblem(), oomph::CRDoubleMatrix::sparse_indexed_output_with_offset(), and oomph::DoubleVectorHelpers::split().
nrow_local() [2/2]
unsigned oomph::DistributableLinearAlgebraObject::nrow_local (const unsigned & p) const [inline]
access function for the num of local rows on this processor.
Definition at line 481 of file linear_algebra_distribution.h.
References Distribution_pt, and oomph::LinearAlgebraDistribution::nrow_local().
operator=()
void oomph::DistributableLinearAlgebraObject::operator= (const DistributableLinearAlgebraObject &) [inline]
Broken assignment operator.
Definition at line 451 of file linear_algebra_distribution.h.
References oomph::BrokenCopy::broken_assign().
Member Data Documentation
Distribution_pt
LinearAlgebraDistribution* oomph::DistributableLinearAlgebraObject::Distribution_pt [private]
the LinearAlgebraDistribution object
Definition at line 535 of file linear_algebra_distribution.h.
Referenced by build_distribution(), clear_distribution(), DistributableLinearAlgebraObject(), distributed(), distribution_built(), distribution_pt(), first_row(), nrow(), nrow_local(), and ~DistributableLinearAlgebraObject().
The documentation for this class was generated from the following file:
linear_algebra_distribution.h