oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT > Class Template Reference
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
#include <multi_domain_boussinesq_elements.h>
Public Member Functions
NavierStokesBoussinesqElement ()
Constructor: call the underlying constructors and initialise the pointer to the Rayleigh number to point to the default value of 0.0.
const double & ra () const
Access function for the Rayleigh number (const version)
double *& ra_pt ()
Access function for the pointer to the Rayleigh number.
void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
Overload get_body_force_nst to get the temperature `body force` from the `source` AdvectionDiffusion element via current integration point.
void get_dbody_force_nst_dexternal_element_data (const unsigned &ipt, DenseMatrix< double > &result, Vector< unsigned > &global_eqn_number)
Fill in the derivatives of the body force with respect to the external unknowns.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual vector and the Jacobian matrix. Jacobian is computed by finite-differencing or analytically.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void fill_in_off_diagonal_block_analytic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the contribution of the external degrees of freedom (temperatures) on the Navier-Stokes equations.
Private Attributes
double * Ra_pt
Pointer to a private data member, the Rayleigh number.
Additional Inherited Members
Detailed Description
template<class NST_ELEMENT, class AD_ELEMENT>
class oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
Build NavierStokesBoussinesqElement that inherits from ElementWithExternalElement so that it can `communicate` with AdvectionDiffusionElementWithExternalElement
Definition at line 815 of file multi_domain_boussinesq_elements.h.
Constructor & Destructor Documentation
NavierStokesBoussinesqElement()
template<class NST_ELEMENT , class AD_ELEMENT >
oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::NavierStokesBoussinesqElement () [inline]
Constructor: call the underlying constructors and initialise the pointer to the Rayleigh number to point to the default value of 0.0.
Definition at line 827 of file multi_domain_boussinesq_elements.h.
References oomph::MultiDomainBoussinesqHelper::Default_Physical_Constant_Value, oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::Ra_pt, and oomph::ElementWithExternalElement::set_ninteraction().
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class NST_ELEMENT , class AD_ELEMENT >
void oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute the element's residual vector and the Jacobian matrix. Jacobian is computed by finite-differencing or analytically.
Reimplemented from oomph::ElementWithExternalElement.
Definition at line 867 of file multi_domain_boussinesq_elements.h.
References oomph::ElementWithExternalElement::fill_in_contribution_to_jacobian(), oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic(), and oomph::FiniteElement::jacobian.
fill_in_contribution_to_jacobian_and_mass_matrix()
template<class NST_ELEMENT , class AD_ELEMENT >
void oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline], [virtual]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Reimplemented from oomph::GeneralisedElement.
Definition at line 889 of file multi_domain_boussinesq_elements.h.
References oomph::GeneralisedElement::fill_in_contribution_to_jacobian_and_mass_matrix(), and oomph::FiniteElement::jacobian.
fill_in_off_diagonal_block_analytic()
template<class NST_ELEMENT , class AD_ELEMENT >
void oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline]
Compute the contribution of the external degrees of freedom (temperatures) on the Navier-Stokes equations.
Definition at line 903 of file multi_domain_boussinesq_elements.h.
References oomph::FiniteElement::dim(), oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::get_dbody_force_nst_dexternal_element_data(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::jacobian, oomph::GeneralisedElement::local_eqn_number(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), and oomph::W.
Referenced by oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_contribution_to_jacobian().
get_body_force_nst()
template<class NST_ELEMENT , class AD_ELEMENT >
void oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::get_body_force_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & result)
Overload get_body_force_nst to get the temperature `body force` from the `source` AdvectionDiffusion element via current integration point.
Definition at line 1002 of file multi_domain_boussinesq_elements.h.
References i.
get_dbody_force_nst_dexternal_element_data()
template<class NST_ELEMENT , class AD_ELEMENT >
void oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::get_dbody_force_nst_dexternal_element_data (const unsigned & ipt, DenseMatrix< double > & result, Vector< unsigned > & global_eqn_number)
Fill in the derivatives of the body force with respect to the external unknowns.
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
Fill in the derivatives of the body force with respect to the external unknowns in the Navier--Stokes equations
Definition at line 1376 of file multi_domain_boussinesq_elements.h.
References i, and oomph::DenseMatrix< T >::resize().
Referenced by oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic().
ra()
template<class NST_ELEMENT , class AD_ELEMENT >
const double & oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::ra () const [inline]
Access function for the Rayleigh number (const version)
Definition at line 837 of file multi_domain_boussinesq_elements.h.
References oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::Ra_pt.
ra_pt()
template<class NST_ELEMENT , class AD_ELEMENT >
double *& oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::ra_pt () [inline]
Access function for the pointer to the Rayleigh number.
Definition at line 843 of file multi_domain_boussinesq_elements.h.
References oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::Ra_pt.
Member Data Documentation
Ra_pt
template<class NST_ELEMENT , class AD_ELEMENT >
double* oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::Ra_pt [private]
Pointer to a private data member, the Rayleigh number.
Definition at line 821 of file multi_domain_boussinesq_elements.h.
Referenced by oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::NavierStokesBoussinesqElement(), oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::ra(), and oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::ra_pt().
The documentation for this class was generated from the following file:
multi_domain_boussinesq_elements.h