oomph::WomersleyEquations< DIM > Class Template Reference
#include <womersley_elements.h>
Public Member Functions
WomersleyEquations ()
Constructor: Initialises the Pressure_gradient_data_pt to null.
WomersleyEquations (const WomersleyEquations &dummy)
Broken copy constructor.
void operator= (const WomersleyEquations &)
Broken assignment operator.
void set_pressure_gradient_pt (Data *&pressure_gradient_data_pt)
Set pointer to pressure gradient (single-valued Data)
Data * set_pressure_gradient_pt () const
Read-only access to pointer to pressure gradient.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
virtual unsigned u_index_womersley () const
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the Womersley equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
double du_dt_womersley (const unsigned &n) const
du/dt at local node n. Uses suitably interpolated value for hanging nodes.
void output (std::ostream &outfile)
Output with default number of plot points.
void output_3d (std::ostream &outfile, const unsigned &n_plot, const double &z_out)
Output function: x,y,z_out,0,0,u,0 to allow comparison against full Navier Stokes at n_nplot x n_plot points (2D)
void output (std::ostream &outfile, const unsigned &nplot)
Output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points.
virtual void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points (time-dependent version)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Get error against and norm of exact solution.
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: flux[i] = du/dx_i.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute element residual Vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute element residual Vector and element Jacobian matrix (wrapper)
double interpolated_u_womersley (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
unsigned self_test ()
Self-test: Return 0 for OK.
double get_volume_flux ()
Compute total volume flux through element.
Protected Member Functions
virtual double dshape_and_dtest_eulerian_womersley (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_womersley (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
virtual void fill_in_generic_residual_contribution_womersley (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Protected Attributes
Data * Pressure_gradient_data_pt
Pointer to pressure gradient Data (single value Data item)
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
Static Protected Attributes
static double Default_ReSt_value = 0.0
Static default value for the Womersley number.
Private Member Functions
void set_pressure_gradient_and_add_as_external_data (Data *pressure_gradient_data_pt)
Set pointer to pressure gradient (single-valued Data) and treat it as external data -- this can only be called by the friend class ImposeFluxForWomersleyElement which imposes a volume flux constraint and trades it for the now unknown pressure gradient Data that is treated as external Data for this element. This slightly convoluted (private/friend) construction is necessary because, counter to practice, the current element adds contributions to the equation that determines the external data. This obviously requires that the ImposeFluxForWomersleyElement doesn't do the same. We know that it doesn't and therefore we make it a friend that's allowed to collaborate with this element...
Friends
template<unsigned DIMM>
class ImposeFluxForWomersleyElement
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::WomersleyEquations< DIM >
A class for all isoparametric elements that solve the Womersley (parallel flow) equations.
 Re St \frac{\partial u}{\partial t} = - g + \frac{\partial^2 u}{\partial x_i^2} 
 which may be derived from the full Navier-Stokes equations (with a viscous scaling of the pressure) under the assumption of parallel flow in the z direction. u then represents the axial velocity and g is the (spatially constant) axial component of the pressure gradient.
This class contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class. Note that this class assumes an isoparametric formulation, i.e. that the scalar unknown is interpolated using the same shape functions as the position.
Generally, the instantaneous value of the pressure gradient, g, is prescribed (and specified via a pointer to a single-valued Data object whose current (pinned) value contains the pressure.
It is also possible to prescribe the flow rate through a mesh of Womersley elements and to determine the pressure gradient required to achieve this flow rate as an unknown. In that case the external pressure is treated as an external Data object that an associated ImposeFluxForWomersleyElement is in charge of. Note that only the ImposeFluxForWomersleyElement can set the pressure gradient Data object as external Data. This is because (counter to general practice) the WomersleyEquations make contributions to the residuals of the ImposeFluxForWomersleyElements in order to keep the elemental Jacobians as small as possible.
Definition at line 188 of file womersley_elements.h.
Constructor & Destructor Documentation
WomersleyEquations() [1/2]
template<unsigned DIM>
oomph::WomersleyEquations< DIM >::WomersleyEquations () [inline]
Constructor: Initialises the Pressure_gradient_data_pt to null.
Definition at line 192 of file womersley_elements.h.
References oomph::WomersleyEquations< DIM >::Default_ReSt_value, and oomph::WomersleyEquations< DIM >::ReSt_pt.
WomersleyEquations() [2/2]
template<unsigned DIM>
oomph::WomersleyEquations< DIM >::WomersleyEquations (const WomersleyEquations< DIM > & dummy) [inline]
Broken copy constructor.
Definition at line 199 of file womersley_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
compute_error() [1/2]
template<unsigned DIM>
void oomph::WomersleyEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 524 of file womersley_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
compute_error() [2/2]
template<unsigned DIM>
void oomph::WomersleyEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution at time t.
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 603 of file womersley_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
dshape_and_dtest_eulerian_at_knot_womersley()
template<unsigned DIM>
virtual double oomph::WomersleyEquations< DIM >::dshape_and_dtest_eulerian_at_knot_womersley (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::QWomersleyElement< DIM, NNODE_1D >, and oomph::TWomersleyElement< DIM, NNODE_1D >.
dshape_and_dtest_eulerian_womersley()
template<unsigned DIM>
virtual double oomph::WomersleyEquations< DIM >::dshape_and_dtest_eulerian_womersley (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in oomph::QWomersleyElement< DIM, NNODE_1D >, and oomph::TWomersleyElement< DIM, NNODE_1D >.
du_dt_womersley()
template<unsigned DIM>
double oomph::WomersleyEquations< DIM >::du_dt_womersley (const unsigned & n) const [inline]
du/dt at local node n. Uses suitably interpolated value for hanging nodes.
Definition at line 264 of file womersley_elements.h.
References oomph::TimeStepper::is_steady(), n, oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), oomph::WomersleyEquations< DIM >::u_index_womersley(), and oomph::TimeStepper::weight().
fill_in_contribution_to_jacobian()
template<unsigned DIM>
void oomph::WomersleyEquations< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute element residual Vector and element Jacobian matrix (wrapper)
Reimplemented from oomph::FiniteElement.
Definition at line 397 of file womersley_elements.h.
References oomph::WomersleyEquations< DIM >::fill_in_generic_residual_contribution_womersley(), and residuals().
fill_in_contribution_to_residuals()
template<unsigned DIM>
void oomph::WomersleyEquations< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Compute element residual Vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 387 of file womersley_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, oomph::WomersleyEquations< DIM >::fill_in_generic_residual_contribution_womersley(), and residuals().
fill_in_generic_residual_contribution_womersley()
template<unsigned DIM>
void oomph::WomersleyEquations< DIM >::fill_in_generic_residual_contribution_womersley (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [protected], [virtual]
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Compute element residual Vector and/or element Jacobian matrix
flag=1: compute both flag=0: compute only residual Vector
Pure version without hanging nodes
Definition at line 67 of file womersley_elements.cc.
References i, interpolated_u(), residuals(), s, and oomph::QuadTreeNames::W.
Referenced by oomph::WomersleyEquations< DIM >::fill_in_contribution_to_jacobian(), and oomph::WomersleyEquations< DIM >::fill_in_contribution_to_residuals().
get_flux()
template<unsigned DIM>
void oomph::WomersleyEquations< DIM >::get_flux (const Vector< double > & s, Vector< double > & flux) const [inline]
Get flux: flux[i] = du/dx_i.
Definition at line 353 of file womersley_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, and oomph::WomersleyEquations< DIM >::u_index_womersley().
get_volume_flux()
template<unsigned DIM>
double oomph::WomersleyEquations< DIM >::get_volume_flux
Compute total volume flux through element.
Compute volume flux through element.
Definition at line 219 of file womersley_elements.cc.
References i, interpolated_u(), s, and oomph::QuadTreeNames::W.
Referenced by oomph::ImposeFluxForWomersleyElement< DIM >::total_volume_flux().
interpolated_u_womersley()
template<unsigned DIM>
double oomph::WomersleyEquations< DIM >::interpolated_u_womersley (const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s.
Definition at line 406 of file womersley_elements.h.
References interpolated_u(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and oomph::WomersleyEquations< DIM >::u_index_womersley().
operator=()
template<unsigned DIM>
void oomph::WomersleyEquations< DIM >::operator= (const WomersleyEquations< DIM > &) [inline]
Broken assignment operator.
Definition at line 206 of file womersley_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
template<unsigned DIM>
void oomph::WomersleyEquations< DIM >::output (FILE * file_pt) [inline], [virtual]
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QWomersleyElement< DIM, NNODE_1D >.
Definition at line 311 of file womersley_elements.h.
References oomph::WomersleyEquations< DIM >::output().
output() [2/4]
template<unsigned DIM>
void oomph::WomersleyEquations< DIM >::output (FILE * file_pt, const unsigned & nplot) [virtual]
C-style output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points.
C-style output function:
x,y,u or x,y,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QWomersleyElement< DIM, NNODE_1D >.
Definition at line 382 of file womersley_elements.cc.
References i, and s.
output() [3/4]
template<unsigned DIM>
void oomph::WomersleyEquations< DIM >::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QWomersleyElement< DIM, NNODE_1D >.
Definition at line 293 of file womersley_elements.h.
Referenced by oomph::TWomersleyElement< DIM, NNODE_1D >::output(), oomph::WomersleyEquations< DIM >::output(), and oomph::QWomersleyElement< DIM, NNODE_1D >::output().
output() [4/4]
template<unsigned DIM>
void oomph::WomersleyEquations< DIM >::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points.
Output function:
x,y,u or x,y,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QWomersleyElement< DIM, NNODE_1D >.
Definition at line 346 of file womersley_elements.cc.
References i, and s.
output_3d()
template<unsigned DIM>
void oomph::WomersleyEquations< DIM >::output_3d (std::ostream & outfile, const unsigned & nplot, const double & z_out)
Output function: x,y,z_out,0,0,u,0 to allow comparison against full Navier Stokes at n_nplot x n_plot points (2D)
Output function: x,y,z_out,0,0,u,0 to allow comparison against full Navier Stokes at n_nplot x n_plot points (2D)
Definition at line 308 of file womersley_elements.cc.
References i, and s.
output_fct() [1/2]
template<unsigned DIM>
void oomph::WomersleyEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points (time-dependent version)
Output exact solution at time t
Solution is provided via function pointer. Plot at a given number of plot points.
x,y,u_exact or x,y,z,u_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QWomersleyElement< DIM, NNODE_1D >, and oomph::TWomersleyElement< DIM, NNODE_1D >.
Definition at line 470 of file womersley_elements.cc.
References i, and s.
output_fct() [2/2]
template<unsigned DIM>
void oomph::WomersleyEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points.
Output exact solution
Solution is provided via function pointer. Plot at a given number of plot points.
x,y,u_exact or x,y,z,u_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QWomersleyElement< DIM, NNODE_1D >.
Definition at line 418 of file womersley_elements.cc.
References i, and s.
Referenced by oomph::TWomersleyElement< DIM, NNODE_1D >::output_fct(), and oomph::QWomersleyElement< DIM, NNODE_1D >::output_fct().
re_st()
template<unsigned DIM>
const double& oomph::WomersleyEquations< DIM >::re_st () const [inline]
Product of Reynolds and Strouhal number (=Womersley number)
Definition at line 236 of file womersley_elements.h.
References oomph::WomersleyEquations< DIM >::ReSt_pt.
re_st_pt()
template<unsigned DIM>
double*& oomph::WomersleyEquations< DIM >::re_st_pt () [inline]
Pointer to product of Reynolds and Strouhal number (=Womersley number)
Definition at line 243 of file womersley_elements.h.
References oomph::WomersleyEquations< DIM >::ReSt_pt.
self_test()
template<unsigned DIM>
unsigned oomph::WomersleyEquations< DIM >::self_test [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
Definition at line 281 of file womersley_elements.cc.
References oomph::FiniteElement::self_test().
set_pressure_gradient_and_add_as_external_data()
template<unsigned DIM>
void oomph::WomersleyEquations< DIM >::set_pressure_gradient_and_add_as_external_data (Data * pressure_gradient_data_pt) [inline], [private]
Set pointer to pressure gradient (single-valued Data) and treat it as external data -- this can only be called by the friend class ImposeFluxForWomersleyElement which imposes a volume flux constraint and trades it for the now unknown pressure gradient Data that is treated as external Data for this element. This slightly convoluted (private/friend) construction is necessary because, counter to practice, the current element adds contributions to the equation that determines the external data. This obviously requires that the ImposeFluxForWomersleyElement doesn't do the same. We know that it doesn't and therefore we make it a friend that's allowed to collaborate with this element...
Definition at line 489 of file womersley_elements.h.
References oomph::GeneralisedElement::add_external_data(), and oomph::WomersleyEquations< DIM >::Pressure_gradient_data_pt.
Referenced by oomph::ImposeFluxForWomersleyElement< DIM >::ImposeFluxForWomersleyElement().
set_pressure_gradient_pt() [1/2]
template<unsigned DIM>
Data* oomph::WomersleyEquations< DIM >::set_pressure_gradient_pt () const [inline]
Read-only access to pointer to pressure gradient.
Definition at line 229 of file womersley_elements.h.
References oomph::WomersleyEquations< DIM >::Pressure_gradient_data_pt.
set_pressure_gradient_pt() [2/2]
template<unsigned DIM>
void oomph::WomersleyEquations< DIM >::set_pressure_gradient_pt (Data *& pressure_gradient_data_pt) [inline]
Set pointer to pressure gradient (single-valued Data)
Definition at line 213 of file womersley_elements.h.
References oomph::Data::nvalue(), and oomph::WomersleyEquations< DIM >::Pressure_gradient_data_pt.
u_index_womersley()
template<unsigned DIM>
virtual unsigned oomph::WomersleyEquations< DIM >::u_index_womersley () const [inline], [virtual]
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the Womersley equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
Definition at line 256 of file womersley_elements.h.
Referenced by oomph::WomersleyEquations< DIM >::du_dt_womersley(), oomph::WomersleyEquations< DIM >::get_flux(), and oomph::WomersleyEquations< DIM >::interpolated_u_womersley().
Friends And Related Function Documentation
ImposeFluxForWomersleyElement
template<unsigned DIM>
template<unsigned DIMM>
friend class ImposeFluxForWomersleyElement [friend]
Definition at line 474 of file womersley_elements.h.
Member Data Documentation
Default_ReSt_value
template<unsigned DIM>
double oomph::WomersleyEquations< DIM >::Default_ReSt_value = 0.0 [static], [protected]
Static default value for the Womersley number.
Default Womersley number.
Definition at line 470 of file womersley_elements.h.
Referenced by oomph::WomersleyEquations< DIM >::WomersleyEquations().
Pressure_gradient_data_pt
template<unsigned DIM>
Data* oomph::WomersleyEquations< DIM >::Pressure_gradient_data_pt [protected]
Pointer to pressure gradient Data (single value Data item)
Definition at line 464 of file womersley_elements.h.
Referenced by oomph::WomersleyEquations< DIM >::set_pressure_gradient_and_add_as_external_data(), and oomph::WomersleyEquations< DIM >::set_pressure_gradient_pt().
ReSt_pt
template<unsigned DIM>
double* oomph::WomersleyEquations< DIM >::ReSt_pt [protected]
Pointer to global Reynolds number x Strouhal number (=Womersley)
Definition at line 467 of file womersley_elements.h.
Referenced by oomph::WomersleyEquations< DIM >::re_st(), oomph::WomersleyEquations< DIM >::re_st_pt(), and oomph::WomersleyEquations< DIM >::WomersleyEquations().
The documentation for this class was generated from the following files:
womersley_elements.h
womersley_elements.cc