oomph::RefineableAxisymmetricNavierStokesEquations Class Reference
Refineable version of the Axisymmetric Navier--Stokes equations.
#include <refineable_axisym_navier_stokes_elements.h>
Public Member Functions
RefineableAxisymmetricNavierStokesEquations ()
Empty Constructor.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
double geometric_jacobian (const Vector< double > &x)
Fill in the geometric Jacobian, which in this case is r.
void further_build ()
Further build: pass the pointers down to the sons.
void dinterpolated_u_axi_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information.
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
Compute derivatives of elemental residual vector with respect to nodal coordinates. This function computes these terms analytically and overwrites the default implementation in the FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}.
Static Public Member Functions
static void pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > &element_pt)
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function.
static void unpin_all_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in vector.
Protected Member Functions
virtual Node * pressure_node_pt (const unsigned &n_p)
Pointer to n_p-th pressure node (Default: NULL, indicating that pressure is not based on nodal interpolation).
virtual void unpin_elemental_pressure_dofs ()=0
Unpin all pressure dofs in the element.
virtual void pin_elemental_redundant_nodal_pressure_dofs ()
Pin unused nodal pressure dofs (empty by default, because by default pressure dofs are not associated with nodes)
Private Member Functions
void fill_in_generic_residual_contribution_axi_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Add element's contribution to the elemental residual vector and/or Jacobian matrix and mass matrix flag=2: compute all flag=1: compute both residual and Jacobian flag=0: compute only residual vector.
void fill_in_generic_dresidual_contribution_axi_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, unsigned flag)
Add element's contribution to the derivative of the elemental residual vector and/or Jacobian matrix and/or mass matrix flag=2: compute all flag=1: compute both residual and Jacobian flag=0: compute only residual vector.
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Compute the hessian tensor vector products required to perform continuation of bifurcations analytically.
Additional Inherited Members
Detailed Description
Refineable version of the Axisymmetric Navier--Stokes equations.
Definition at line 45 of file refineable_axisym_navier_stokes_elements.h.
Constructor & Destructor Documentation
RefineableAxisymmetricNavierStokesEquations()
oomph::RefineableAxisymmetricNavierStokesEquations::RefineableAxisymmetricNavierStokesEquations () [inline]
Empty Constructor.
Definition at line 67 of file refineable_axisym_navier_stokes_elements.h.
Member Function Documentation
dinterpolated_u_axi_nst_ddata()
void oomph::RefineableAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata (const Vector< double > & s, const unsigned & i, Vector< double > & du_ddata, Vector< unsigned > & global_eqn_number) [inline], [virtual]
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information.
Reimplemented from oomph::AxisymmetricNavierStokesEquations.
Definition at line 175 of file refineable_axisym_navier_stokes_elements.h.
References oomph::Data::eqn_number(), oomph::Node::hanging_pt(), oomph::Node::is_hanging(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::shape(), and oomph::AxisymmetricNavierStokesEquations::u_index_axi_nst().
fill_in_contribution_to_hessian_vector_products()
void oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products (Vector< double > const & Y, DenseMatrix< double > const & C, DenseMatrix< double > & product) [inline], [private], [virtual]
Compute the hessian tensor vector products required to perform continuation of bifurcations analytically.
Reimplemented from oomph::AxisymmetricNavierStokesEquations.
Definition at line 387 of file refineable_axisym_navier_stokes_elements.h.
fill_in_generic_dresidual_contribution_axi_nst()
void oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam, DenseMatrix< double > & dmass_matrix_dparam, unsigned flag) [inline], [private], [virtual]
Add element's contribution to the derivative of the elemental residual vector and/or Jacobian matrix and/or mass matrix flag=2: compute all flag=1: compute both residual and Jacobian flag=0: compute only residual vector.
Reimplemented from oomph::AxisymmetricNavierStokesEquations.
Definition at line 373 of file refineable_axisym_navier_stokes_elements.h.
fill_in_generic_residual_contribution_axi_nst()
void oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [private], [virtual]
Add element's contribution to the elemental residual vector and/or Jacobian matrix and mass matrix flag=2: compute all flag=1: compute both residual and Jacobian flag=0: compute only residual vector.
Add element's contribution to the elemental residual vector and/or Jacobian matrix. flag=1: compute both flag=0: compute only residual vector.
Reimplemented from oomph::AxisymmetricNavierStokesEquations.
Definition at line 37 of file refineable_axisym_navier_stokes_elements.cc.
References oomph::AxisymmetricNavierStokesEquations::ALE_is_disabled, oomph::AxisymmetricNavierStokesEquations::density_ratio(), oomph::FiniteElement::dnodal_position_dt(), oomph::AxisymmetricNavierStokesEquations::dshape_and_dtest_eulerian_at_knot_axi_nst(), oomph::AxisymmetricNavierStokesEquations::du_dt_axi_nst(), oomph::AxisymmetricNavierStokesEquations::g(), oomph::AxisymmetricNavierStokesEquations::Gamma, oomph::AxisymmetricNavierStokesEquations::get_body_force_axi_nst(), oomph::AxisymmetricNavierStokesEquations::get_source_fct(), oomph::Node::hanging_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Node::is_hanging(), oomph::Integral::knot(), oomph::RefineableElement::local_hang_eqn(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::AxisymmetricNavierStokesEquations::npres_axi_nst(), oomph::Integral::nweight(), oomph::AxisymmetricNavierStokesEquations::p_axi_nst(), oomph::AxisymmetricNavierStokesEquations::p_local_eqn(), oomph::AxisymmetricNavierStokesEquations::p_nodal_index_axi_nst(), pressure_node_pt(), oomph::AxisymmetricNavierStokesEquations::pshape_axi_nst(), oomph::AxisymmetricNavierStokesEquations::re(), oomph::AxisymmetricNavierStokesEquations::re_invfr(), oomph::AxisymmetricNavierStokesEquations::re_invro(), oomph::AxisymmetricNavierStokesEquations::re_st(), s, oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), oomph::AxisymmetricNavierStokesEquations::u_index_axi_nst(), oomph::AxisymmetricNavierStokesEquations::viscosity_ratio(), oomph::QuadTreeNames::W, oomph::Integral::weight(), and oomph::TimeStepper::weight().
further_build()
void oomph::RefineableAxisymmetricNavierStokesEquations::further_build () [inline], [virtual]
Further build: pass the pointers down to the sons.
Reimplemented from oomph::RefineableElement.
Reimplemented in oomph::RefineableAxisymmetricQCrouzeixRaviartElement.
Definition at line 136 of file refineable_axisym_navier_stokes_elements.h.
References oomph::AxisymmetricNavierStokesEquations::ALE_is_disabled, oomph::AxisymmetricNavierStokesEquations::axi_nst_body_force_fct_pt, oomph::AxisymmetricNavierStokesEquations::Body_force_fct_pt, oomph::AxisymmetricNavierStokesEquations::Density_Ratio_pt, oomph::AxisymmetricNavierStokesEquations::density_ratio_pt(), oomph::RefineableElement::father_element_pt(), oomph::AxisymmetricNavierStokesEquations::G_pt, oomph::AxisymmetricNavierStokesEquations::g_pt(), oomph::AxisymmetricNavierStokesEquations::re_invfr_pt(), oomph::AxisymmetricNavierStokesEquations::re_invro_pt(), oomph::AxisymmetricNavierStokesEquations::Re_pt, oomph::AxisymmetricNavierStokesEquations::re_pt(), oomph::AxisymmetricNavierStokesEquations::re_st_pt(), oomph::AxisymmetricNavierStokesEquations::ReInvFr_pt, oomph::AxisymmetricNavierStokesEquations::ReInvRo_pt, oomph::AxisymmetricNavierStokesEquations::ReSt_pt, oomph::AxisymmetricNavierStokesEquations::source_fct_pt, oomph::AxisymmetricNavierStokesEquations::Source_fct_pt, oomph::AxisymmetricNavierStokesEquations::Viscosity_Ratio_pt, and oomph::AxisymmetricNavierStokesEquations::viscosity_ratio_pt().
Referenced by oomph::RefineableAxisymmetricQCrouzeixRaviartElement::further_build().
geometric_jacobian()
double oomph::RefineableAxisymmetricNavierStokesEquations::geometric_jacobian (const Vector< double > & x) [inline], [virtual]
Fill in the geometric Jacobian, which in this case is r.
Reimplemented from oomph::ElementWithZ2ErrorEstimator.
Definition at line 129 of file refineable_axisym_navier_stokes_elements.h.
get_dresidual_dnodal_coordinates()
void oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates (RankThreeTensor< double > & dresidual_dnodal_coordinates) [virtual]
Compute derivatives of elemental residual vector with respect to nodal coordinates. This function computes these terms analytically and overwrites the default implementation in the FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}.
Compute derivatives of elemental residual vector with respect to nodal coordinates. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij} Overloads the FD-based version in the FiniteElement base class.
Reimplemented from oomph::AxisymmetricNavierStokesEquations.
Definition at line 981 of file refineable_axisym_navier_stokes_elements.cc.
References oomph::AxisymmetricNavierStokesEquations::ALE_is_disabled, oomph::GeneralisedElement::Default_fd_jacobian_step, oomph::AxisymmetricNavierStokesEquations::density_ratio(), oomph::FiniteElement::dnodal_position_dt(), oomph::AxisymmetricNavierStokesEquations::dshape_and_dtest_eulerian_at_knot_axi_nst(), oomph::AxisymmetricNavierStokesEquations::du_dt_axi_nst(), oomph::AxisymmetricNavierStokesEquations::g(), oomph::AxisymmetricNavierStokesEquations::Gamma, oomph::AxisymmetricNavierStokesEquations::get_body_force_axi_nst(), oomph::AxisymmetricNavierStokesEquations::get_body_force_gradient_axi_nst(), oomph::AxisymmetricNavierStokesEquations::get_source_fct(), oomph::AxisymmetricNavierStokesEquations::get_source_fct_gradient(), oomph::Node::hanging_pt(), oomph::Node::has_auxiliary_node_update_fct_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Node::is_hanging(), oomph::Integral::knot(), oomph::RefineableElement::local_hang_eqn(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::GeneralisedElement::ndof(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::AxisymmetricNavierStokesEquations::npres_axi_nst(), oomph::RefineableElement::nshape_controlling_nodes(), oomph::Integral::nweight(), oomph::AxisymmetricNavierStokesEquations::p_axi_nst(), oomph::AxisymmetricNavierStokesEquations::p_local_eqn(), oomph::AxisymmetricNavierStokesEquations::p_nodal_index_axi_nst(), oomph::Node::perform_auxiliary_node_update_fct(), oomph::Node::position_time_stepper_pt(), pressure_node_pt(), oomph::AxisymmetricNavierStokesEquations::pshape_axi_nst(), oomph::AxisymmetricNavierStokesEquations::re(), oomph::AxisymmetricNavierStokesEquations::re_invfr(), oomph::AxisymmetricNavierStokesEquations::re_invro(), oomph::AxisymmetricNavierStokesEquations::re_st(), s, oomph::RefineableElement::shape_controlling_node_lookup(), oomph::Global_string_for_annotation::string(), oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), oomph::AxisymmetricNavierStokesEquations::u_index_axi_nst(), oomph::Data::value_pt(), oomph::AxisymmetricNavierStokesEquations::viscosity_ratio(), oomph::Integral::weight(), oomph::TimeStepper::weight(), and oomph::Node::x().
get_Z2_flux()
void oomph::RefineableAxisymmetricNavierStokesEquations::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 83 of file refineable_axisym_navier_stokes_elements.h.
References i, and oomph::AxisymmetricNavierStokesEquations::strain_rate().
num_Z2_flux_terms()
unsigned oomph::RefineableAxisymmetricNavierStokesEquations::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 75 of file refineable_axisym_navier_stokes_elements.h.
pin_elemental_redundant_nodal_pressure_dofs()
virtual void oomph::RefineableAxisymmetricNavierStokesEquations::pin_elemental_redundant_nodal_pressure_dofs () [inline], [protected], [virtual]
Pin unused nodal pressure dofs (empty by default, because by default pressure dofs are not associated with nodes)
Reimplemented in oomph::RefineableAxisymmetricQTaylorHoodElement.
Definition at line 63 of file refineable_axisym_navier_stokes_elements.h.
Referenced by pin_redundant_nodal_pressures().
pin_redundant_nodal_pressures()
static void oomph::RefineableAxisymmetricNavierStokesEquations::pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > & element_pt) [inline], [static]
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function.
RefineableAxisymmetricNavierStokesEquations:: pin_all_nodal_pressure_dofs()
which is empty by default and should be implemented for elements with nodal pressure degrees of freedom (e.g. for refineable Taylor-Hood.)
Definition at line 319 of file refineable_axisym_navier_stokes_elements.h.
References e, and pin_elemental_redundant_nodal_pressure_dofs().
pressure_node_pt()
virtual Node * oomph::RefineableAxisymmetricNavierStokesEquations::pressure_node_pt (const unsigned & n_p) [inline], [protected], [virtual]
Pointer to n_p-th pressure node (Default: NULL, indicating that pressure is not based on nodal interpolation).
Reimplemented in oomph::RefineableAxisymmetricQTaylorHoodElement.
Definition at line 53 of file refineable_axisym_navier_stokes_elements.h.
Referenced by fill_in_generic_residual_contribution_axi_nst(), and get_dresidual_dnodal_coordinates().
unpin_all_pressure_dofs()
static void oomph::RefineableAxisymmetricNavierStokesEquations::unpin_all_pressure_dofs (const Vector< GeneralisedElement * > & element_pt) [inline], [static]
Unpin all pressure dofs in elements listed in vector.
Definition at line 334 of file refineable_axisym_navier_stokes_elements.h.
References e, and unpin_elemental_pressure_dofs().
unpin_elemental_pressure_dofs()
virtual void oomph::RefineableAxisymmetricNavierStokesEquations::unpin_elemental_pressure_dofs () [protected], [pure virtual]
Unpin all pressure dofs in the element.
Implemented in oomph::RefineableAxisymmetricQTaylorHoodElement, and oomph::RefineableAxisymmetricQCrouzeixRaviartElement.
Referenced by unpin_all_pressure_dofs().
The documentation for this class was generated from the following files:
refineable_axisym_navier_stokes_elements.h
refineable_axisym_navier_stokes_elements.cc