oomph::WomersleyProblem< ELEMENT, DIM > Class Template Reference
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
#include <womersley_elements.h>
Public Types
typedef double(* PrescribedPressureGradientFctPt) (const double &time)
Function pointer to fct that prescribes pressure gradient g=fct(t)
Public Member Functions
WomersleyProblem (double *re_st_pt, double *prescribed_volume_flux_pt, TimeStepper *time_stepper_pt, Mesh *womersley_mesh_pt)
Constructor: Pass pointer to Womersley number, pointer to the double that stores the currently imposed flow rate, the pointer to the mesh of WomersleyElements (of the type specified by the template argument) and the TimeStepper used in these elements. (Note that the mesh must be created, and boundary conditions applied BEFORE creating the Womersley problem. This is to facilitate the re-use of this class for different geometries.
WomersleyProblem (double *re_st_pt, PrescribedPressureGradientFctPt pressure_gradient_fct_pt, TimeStepper *time_stepper_pt, Mesh *womersley_mesh_pt)
Constructor: Pass pointer to Womersley number, pointer to the function that returns the imposed pressure gradient, the pointer to the mesh of WomersleyElements and the TimeStepper used in these elements. (Note that the mesh must be created, and boundary conditions applied BEFORE creating the Womersley problem. This is to allow the facilitate the re-use of this class for different geometries.)
~WomersleyProblem ()
Destructor to clean up memory.
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_before_implicit_timestep ()
Update the problem specs before next timestep: Update time-varying pressure gradient (if prescribed)
void doc_solution (DocInfo &doc_info, std::ofstream &trace_file, const double &z_out=0.0)
Doc the solution incl. trace file for various quantities of interest (to some...)
void doc_solution (DocInfo &doc_info, const double &z_out=0.0)
Doc the solution.
Data * pressure_gradient_data_pt ()
Access function to the single-valued Data object that contains the unknown pressure gradient (used if flux is prescribed)
Private Attributes
double * Prescribed_volume_flux_pt
Pointer to currently prescribed volume flux.
ImposeFluxForWomersleyElement< DIM > * Flux_el_pt
Pointer to element that imposes the flux through the collection of Womersley elements.
PrescribedPressureGradientFctPt Prescribed_pressure_gradient_fct_pt
Fct pointer to fct that prescribes pressure gradient.
Data * Pressure_gradient_data_pt
Pointer to single-valued Data item that stores pressure gradient.
Additional Inherited Members
Detailed Description
template<class ELEMENT, unsigned DIM>
class oomph::WomersleyProblem< ELEMENT, DIM >
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Womersley problem
Definition at line 745 of file womersley_elements.h.
Member Typedef Documentation
PrescribedPressureGradientFctPt
template<class ELEMENT , unsigned DIM>
typedef double(* oomph::WomersleyProblem< ELEMENT, DIM >::PrescribedPressureGradientFctPt) (const double &time)
Function pointer to fct that prescribes pressure gradient g=fct(t)
Definition at line 750 of file womersley_elements.h.
Constructor & Destructor Documentation
WomersleyProblem() [1/2]
template<class ELEMENT , unsigned DIM>
oomph::WomersleyProblem< ELEMENT, DIM >::WomersleyProblem (double * re_st_pt, double * prescribed_volume_flux_pt, TimeStepper * time_stepper_pt, Mesh * womersley_mesh_pt)
Constructor: Pass pointer to Womersley number, pointer to the double that stores the currently imposed flow rate, the pointer to the mesh of WomersleyElements (of the type specified by the template argument) and the TimeStepper used in these elements. (Note that the mesh must be created, and boundary conditions applied BEFORE creating the Womersley problem. This is to facilitate the re-use of this class for different geometries.
Constructor: Pass pointer to Womersley number, pointer to the double that stores the currently imposed flow rate, the pointer to the mesh of WomersleyElements and the TimeStepper used in these elements. (Note that the mesh must be created, and boundary conditions applied BEFORE creating the Womersley problem. This is to facilitate the re-use of this class for different geometries.)
Definition at line 918 of file womersley_elements.h.
References oomph::Mesh::add_element_pt(), oomph::Problem::add_time_stepper_pt(), oomph::Problem::assign_eqn_numbers(), oomph::Mesh::element_pt(), oomph::WomersleyProblem< ELEMENT, DIM >::Flux_el_pt, i, oomph::Problem::mesh_pt(), oomph::Mesh::nelement(), oomph::oomph_info, oomph::WomersleyProblem< ELEMENT, DIM >::Prescribed_volume_flux_pt, oomph::WomersleyProblem< ELEMENT, DIM >::Pressure_gradient_data_pt, oomph::Problem::Problem_is_nonlinear, and oomph::Problem::time_stepper_pt().
WomersleyProblem() [2/2]
template<class ELEMENT , unsigned DIM>
oomph::WomersleyProblem< ELEMENT, DIM >::WomersleyProblem (double * re_st_pt, PrescribedPressureGradientFctPt pressure_gradient_fct_pt, TimeStepper * time_stepper_pt, Mesh * womersley_mesh_pt)
Constructor: Pass pointer to Womersley number, pointer to the function that returns the imposed pressure gradient, the pointer to the mesh of WomersleyElements and the TimeStepper used in these elements. (Note that the mesh must be created, and boundary conditions applied BEFORE creating the Womersley problem. This is to allow the facilitate the re-use of this class for different geometries.)
Constructor: Pass pointer to Womersley number, fct pointer to the function that returns the prescribed pressure gradient, the pointer to the mesh of WomersleyElements (of the type specified by the template argument), and the TimeStepper used in these elements. (Note that the mesh must be created, and boundary conditions applied BEFORE creating the Womersley problem. This is to facilitate the re-use of this class for different geometries.)
Definition at line 850 of file womersley_elements.h.
References oomph::Problem::add_time_stepper_pt(), oomph::Problem::assign_eqn_numbers(), e, oomph::Mesh::element_pt(), i, oomph::Problem::mesh_pt(), oomph::Mesh::nelement(), oomph::oomph_info, oomph::Data::pin(), oomph::WomersleyProblem< ELEMENT, DIM >::Pressure_gradient_data_pt, oomph::Problem::Problem_is_nonlinear, and oomph::Problem::time_stepper_pt().
 WomersleyProblem()
template<class ELEMENT , unsigned DIM>
oomph::WomersleyProblem< ELEMENT, DIM >::~WomersleyProblem
Destructor to clean up memory.
Destructor for Womersley problem.
Definition at line 980 of file womersley_elements.h.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT , unsigned DIM>
void oomph::WomersleyProblem< ELEMENT, DIM >::actions_after_newton_solve () [inline], [virtual]
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
Definition at line 783 of file womersley_elements.h.
actions_before_implicit_timestep()
template<class ELEMENT , unsigned DIM>
void oomph::WomersleyProblem< ELEMENT, DIM >::actions_before_implicit_timestep () [inline], [virtual]
Update the problem specs before next timestep: Update time-varying pressure gradient (if prescribed)
Assign current prescribed pressure gradient to Data
Reimplemented from oomph::Problem.
Definition at line 791 of file womersley_elements.h.
References oomph::WomersleyProblem< ELEMENT, DIM >::Prescribed_pressure_gradient_fct_pt, oomph::WomersleyProblem< ELEMENT, DIM >::Pressure_gradient_data_pt, oomph::Data::set_value(), oomph::Problem::time(), and oomph::Problem::time_pt().
actions_before_newton_solve()
template<class ELEMENT , unsigned DIM>
void oomph::WomersleyProblem< ELEMENT, DIM >::actions_before_newton_solve () [inline], [virtual]
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
Definition at line 786 of file womersley_elements.h.
doc_solution() [1/2]
template<class ELEMENT , unsigned DIM>
void oomph::WomersleyProblem< ELEMENT, DIM >::doc_solution (DocInfo & doc_info, const double & z_out = 0.0) [inline]
Doc the solution.
Definition at line 808 of file womersley_elements.h.
References oomph::WomersleyProblem< ELEMENT, DIM >::doc_solution().
doc_solution() [2/2]
template<class ELEMENT , unsigned DIM>
void oomph::WomersleyProblem< ELEMENT, DIM >::doc_solution (DocInfo & doc_info, std::ofstream & trace_file, const double & z_out = 0.0)
Doc the solution incl. trace file for various quantities of interest (to some...)
Doc the solution.
Definition at line 993 of file womersley_elements.h.
References oomph::DocInfo::directory(), e, and oomph::DocInfo::number().
Referenced by oomph::WomersleyProblem< ELEMENT, DIM >::doc_solution().
pressure_gradient_data_pt()
template<class ELEMENT , unsigned DIM>
Data * oomph::WomersleyProblem< ELEMENT, DIM >::pressure_gradient_data_pt () [inline]
Access function to the single-valued Data object that contains the unknown pressure gradient (used if flux is prescribed)
Definition at line 816 of file womersley_elements.h.
References oomph::WomersleyProblem< ELEMENT, DIM >::Pressure_gradient_data_pt.
Member Data Documentation
Flux_el_pt
template<class ELEMENT , unsigned DIM>
ImposeFluxForWomersleyElement<DIM>* oomph::WomersleyProblem< ELEMENT, DIM >::Flux_el_pt [private]
Pointer to element that imposes the flux through the collection of Womersley elements.
Definition at line 828 of file womersley_elements.h.
Referenced by oomph::WomersleyProblem< ELEMENT, DIM >::WomersleyProblem().
Prescribed_pressure_gradient_fct_pt
template<class ELEMENT , unsigned DIM>
PrescribedPressureGradientFctPt oomph::WomersleyProblem< ELEMENT, DIM >::Prescribed_pressure_gradient_fct_pt [private]
Fct pointer to fct that prescribes pressure gradient.
Definition at line 831 of file womersley_elements.h.
Referenced by oomph::WomersleyProblem< ELEMENT, DIM >::actions_before_implicit_timestep().
Prescribed_volume_flux_pt
template<class ELEMENT , unsigned DIM>
double* oomph::WomersleyProblem< ELEMENT, DIM >::Prescribed_volume_flux_pt [private]
Pointer to currently prescribed volume flux.
Definition at line 824 of file womersley_elements.h.
Referenced by oomph::WomersleyProblem< ELEMENT, DIM >::WomersleyProblem().
Pressure_gradient_data_pt
template<class ELEMENT , unsigned DIM>
Data* oomph::WomersleyProblem< ELEMENT, DIM >::Pressure_gradient_data_pt [private]
Pointer to single-valued Data item that stores pressure gradient.
Definition at line 834 of file womersley_elements.h.
Referenced by oomph::WomersleyProblem< ELEMENT, DIM >::actions_before_implicit_timestep(), oomph::WomersleyProblem< ELEMENT, DIM >::pressure_gradient_data_pt(), and oomph::WomersleyProblem< ELEMENT, DIM >::WomersleyProblem().
The documentation for this class was generated from the following file:
womersley_elements.h