oomph::FaceElement Class Reference
FaceElements are elements that coincide with the faces of higher-dimensional "bulk" elements. They are used on boundaries where additional non-trivial boundary conditions need to be applied. Examples include free surfaces, and applied traction conditions. In many cases, FaceElements need to evaluate to quantities in the associated bulk elements. For instance, the evaluation of a shear stresses on 2D FaceElement requires the evaluation of velocity derivatives in the associated 3D volume element etc. Therefore we store a pointer to the associated bulk element, and information about the relation between the local coordinates in the face and bulk elements.
#include <elements.h>
Public Member Functions
FaceElement ()
Constructor: Initialise all appropriate member data.
virtual ~FaceElement ()
Empty virtual destructor.
FaceElement (const FaceElement &)=delete
Broken copy constructor.
const unsigned & boundary_number_in_bulk_mesh () const
Broken assignment operator.
void set_boundary_number_in_bulk_mesh (const unsigned &b)
Set function for the boundary number in bulk mesh.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
In a FaceElement, the "global" intrinsic coordinate of the element along the boundary, when viewed as part of a compound geometric object is specified using the boundary coordinate defined by the mesh. Note: Boundary coordinates will have been set up when creating the underlying mesh, and their values will have been stored at the nodes.
double J_eulerian (const Vector< double > &s) const
Return the Jacobian of mapping from local to global coordinates at local position s. Overloaded from FiniteElement.
double J_eulerian_at_knot (const unsigned &ipt) const
Return the Jacobian of the mapping from local to global coordinates at the ipt-th integration point Overloaded from FiniteElement.
void check_J_eulerian_at_knots (bool &passed) const
Check that Jacobian of mapping between local and Eulerian coordinates at all integration points is positive.
double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s. Overloaded to get information from bulk.
double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s at previous timestep t (t=0: present; t>0: previous timestep). Overloaded to get information from bulk.
void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector Overloaded to get information from bulk.
void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s at previous timestep t as Vector (t=0: present; t>0: previous timestep). Overloaded to get information from bulk.
double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
Return t-th time-derivative of the i-th FE-interpolated Eulerian coordinate at local coordinate s. Overloaded to get information from bulk.
void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
Compte t-th time-derivative of the FE-interpolated Eulerian coordinate vector at local coordinate s. Overloaded to get information from bulk.
int & normal_sign ()
Sign of outer unit normal (relative to cross-products of tangent vectors in the corresponding "bulk" element.
int normal_sign () const
Return sign of outer unit normal (relative to cross-products of tangent vectors in the corresponding "bulk" element. (const version)
int & face_index ()
Index of the face (a number that uniquely identifies the face in the element)
int face_index () const
Index of the face (a number that uniquely identifies the face in the element) (const version)
const Vector< double > * tangent_direction_pt () const
Public access function for the tangent direction pointer.
void set_tangent_direction (Vector< double > *tangent_direction_pt)
Set the tangent direction vector.
void turn_on_warning_for_discontinuous_tangent ()
Turn on warning for when there may be discontinuous tangent vectors from continuous_tangent_and_outer_unit_normal(...)
void turn_off_warning_for_discontinuous_tangent ()
Turn off warning for when there may be discontinuous tangent vectors from continuous_tangent_and_outer_unit_normal(...)
void continuous_tangent_and_outer_unit_normal (const Vector< double > &s, Vector< Vector< double > > &tang_vec, Vector< double > &unit_normal) const
Compute the tangent vector(s) and the outer unit normal vector at the specified local coordinate. In two spatial dimensions, a "tangent direction" is not required. In three spatial dimensions, a tangent direction is required (set via set_tangent_direction(...)), and we project the tanent direction on to the surface. The second tangent vector is taken to be the cross product of the projection and the unit normal.
void continuous_tangent_and_outer_unit_normal (const unsigned &ipt, Vector< Vector< double > > &tang_vec, Vector< double > &unit_normal) const
Compute the tangent vector(s) and the outer unit normal vector at the ipt-th integration point. This is a wrapper around continuous_tangent_and_outer_unit_normal(...) with the integration points converted into local coordinates.
void outer_unit_normal (const Vector< double > &s, Vector< double > &unit_normal) const
Compute outer unit normal at the specified local coordinate.
void outer_unit_normal (const unsigned &ipt, Vector< double > &unit_normal) const
Compute outer unit normal at ipt-th integration point.
FiniteElement *& bulk_element_pt ()
Pointer to higher-dimensional "bulk" element.
FiniteElement * bulk_element_pt () const
Pointer to higher-dimensional "bulk" element (const version)
CoordinateMappingFctPt & face_to_bulk_coordinate_fct_pt ()
Return the pointer to the function that maps the face coordinate to the bulk coordinate.
CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt () const
Return the pointer to the function that maps the face coordinate to the bulk coordinate (const version)
BulkCoordinateDerivativesFctPt & bulk_coordinate_derivatives_fct_pt ()
Return the pointer to the function that returns the derivatives of the bulk coordinates wrt the face coordinates.
BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt () const
Return the pointer to the function that returns the derivatives of the bulk coordinates wrt the face coordinates (const version)
Vector< double > local_coordinate_in_bulk (const Vector< double > &s) const
Return vector of local coordinates in bulk element, given the local coordinates in this FaceElement.
void get_local_coordinate_in_bulk (const Vector< double > &s, Vector< double > &s_bulk) const
Calculate the vector of local coordinate in the bulk element given the local coordinates in this FaceElement.
void get_ds_bulk_ds_face (const Vector< double > &s, DenseMatrix< double > &dsbulk_dsface, unsigned &interior_direction) const
Calculate the derivatives of the local coordinates in the bulk element with respect to the local coordinates in this FaceElement. In addition return the index of a bulk local coordinate that varies away from the face.
unsigned & bulk_position_type (const unsigned &i)
Return the position type in the "bulk" element that corresponds to position type i on the FaceElement.
const unsigned & bulk_position_type (const unsigned &i) const
Return the position type in the "bulk" element that corresponds to the position type i on the FaceElement. Const version.
void bulk_node_number_resize (const unsigned &i)
Resize the storage for the bulk node numbers.
unsigned & bulk_node_number (const unsigned &n)
Return the bulk node number that corresponds to the n-th local node number.
const unsigned & bulk_node_number (const unsigned &n) const
Return the bulk node number that corresponds to the n-th local node number (const version)
void bulk_position_type_resize (const unsigned &i)
Resize the storage for bulk_position_type to i entries.
unsigned & nbulk_value (const unsigned &n)
Return the number of values originally stored at local node n (before the FaceElement added additional values to it (if it did))
unsigned nbulk_value (const unsigned &n) const
Return the number of values originally stored at local node n (before the FaceElement added additional values to it (if it did)) (const version)
void nbulk_value_resize (const unsigned &i)
Resize the storage for the number of values originally stored at the local nodes to i entries.
void resize_nodes (Vector< unsigned > &nadditional_data_values)
Provide additional storage for a specified number of values at the nodes of the FaceElement. (This is needed, for instance, in free-surface elements, if the non-penetration condition is imposed by Lagrange multipliers whose values are only stored at the surface nodes but not in the interior of the bulk element). nadditional_data_values[n] specifies the number of additional values required at node n of the FaceElement. Note: Since this function is executed separately for each FaceElement, nodes that are common to multiple elements might be resized repeatedly. To avoid this, we only allow a single resize operation by comparing the number of values stored at each node to the number of values the node had when it was simply a member of the associated "bulk" element. There are cases where this will break! -- e.g. if a node is common to two FaceElements which require additional storage for distinct quantities. Such cases need to be handled by "hand-crafted" face elements.
void output_zeta (std::ostream &outfile, const unsigned &nplot)
Output boundary coordinate zeta.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
Set the dimension of the element and initially set the dimension of the nodes to be the same as the dimension of the element.
void set_nodal_dimension (const unsigned &nodal_dim)
Set the dimension of the nodes in the element. This will typically only be required when constructing FaceElements or in beam and shell type elements where a lower dimensional surface is embedded in a higher dimensional space.
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
Set the number of nodes in the element to n, by resizing the storage for pointers to the Node objects.
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
Return the local equation number corresponding to the i-th value at the n-th local node.
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
Compute the geometric shape functions (psi) at integration point ipt. Return the determinant of the jacobian of the mapping (detJ). Additionally calculate the derivatives of "detJ" w.r.t. the nodal coordinates.
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
The destructor cleans up the static memory allocated for shape function storage. Internal and external data get wiped by the GeneralisedElement destructor; nodes get killed in mesh destructor.
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
Adjust local coordinates so that they're located inside the element.
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
Compute centre of gravity of all nodes and radius of node that is furthest from it. Used to assess approximately if a point is likely to be contained with an element in locate_zeta-like operations.
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
Get local coordinates of node j in the element; vector sets its own size (broken virtual)
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
Get the local fraction of the node j in the element A dumb, but correct default implementation is provided.
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
Get the local fraction of any node in the n-th position in a one dimensional expansion along the i-th local coordinate.
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
Set pointer to macro element -- can be overloaded in derived elements to perform additional tasks.
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
Global coordinates as function of local coordinates. Either via FE representation or via macro-element (if Macro_elem_pt!=0)
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
Global coordinates as function of local coordinates at previous time "level" t (t=0: present; t>0: previous). Either via FE representation of QElement or via macro-element (if Macro_elem_pt!=0).
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
Global coordinates as function of local coordinates using macro element representation. (Broken virtual --- this must be overloaded in specific geometric element classes)
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
Global coordinates as function of local coordinates at previous time "level" t (t=0: present; t>0: previous). using macro element representation (Broken virtual -- overload in specific geometric element class if you want to use this functionality.)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
Calculate the geometric shape functions at local coordinate s. This function must be overloaded for each specific geometric element.
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
Return the geometric shape function at the ipt-th integration point.
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Function to compute the geometric shape functions and derivatives w.r.t. local coordinates at local coordinate s. This function must be overloaded for each specific geometric element. (Broken virtual function --- specifies the interface)
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
Return the geometric shape function and its derivative w.r.t. the local coordinates at the ipt-th integration point.
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
Function to compute the geometric shape functions and also first and second derivatives w.r.t. local coordinates at local coordinate s. This function must be overloaded for each specific geometric element (if required). (Broken virtual function --- specifies the interface). Numbering: 1D: d2psids(i,0) = $ d^2 \psi_j / ds^2 $ 2D: d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $ 3D: d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial^2 \psi_j / \partial s_2^2 $ d2psids(i,3) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $ d2psids(i,4) = $ \partial^2 \psi_j / \partial s_0 \partial s_2 $ d2psids(i,5) = $ \partial^2 \psi_j / \partial s_1 \partial s_2 $.
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
Return the geometric shape function and its first and second derivatives w.r.t. the local coordinates at the ipt-th integration point. Numbering: 1D: d2psids(i,0) = $ d^2 \psi_j / ds^2 $ 2D: d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $ 3D: d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial^2 \psi_j / \partial s_2^2 $ d2psids(i,3) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $ d2psids(i,4) = $ \partial^2 \psi_j / \partial s_0 \partial s_2 $ d2psids(i,5) = $ \partial^2 \psi_j / \partial s_1 \partial s_2 $.
void check_J_eulerian_at_knots (bool &passed) const
Check that Jacobian of mapping between local and Eulerian coordinates at all integration points is positive.
void check_jacobian (const double &jacobian) const
Helper function used to check for singular or negative Jacobians in the transform from local to global or Lagrangian coordinates.
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
Compute the geometric shape functions and also first derivatives w.r.t. global coordinates at local coordinate s; Returns Jacobian of mapping from global to local coordinates.
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
Return the geometric shape functions and also first derivatives w.r.t. global coordinates at the ipt-th integration point.
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
Compute the geometric shape functions (psi) and first derivatives w.r.t. global coordinates (dpsidx) at the ipt-th integration point. Return the determinant of the jacobian of the mapping (detJ). Additionally calculate the derivatives of both "detJ" and "dpsidx" w.r.t. the nodal coordinates.
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
Compute the geometric shape functions and also first and second derivatives w.r.t. global coordinates at local coordinate s; Returns Jacobian of mapping from global to local coordinates. Numbering: 1D: d2psidx(i,0) = $ d^2 \psi_j / d x^2 $ 2D: d2psidx(i,0) = $ \partial^2 \psi_j / \partial x_0^2 $ d2psidx(i,1) = $ \partial^2 \psi_j / \partial x_1^2 $ d2psidx(i,2) = $ \partial^2 \psi_j / \partial x_0 \partial x_1 $ 3D: d2psidx(i,0) = $ \partial^2 \psi_j / \partial x_0^2 $ d2psidx(i,1) = $ \partial^2 \psi_j / \partial x_1^2 $ d2psidx(i,2) = $ \partial^2 \psi_j / \partial x_2^2 $ d2psidx(i,3) = $ \partial^2 \psi_j / \partial x_0 \partial x_1 $ d2psidx(i,4) = $ \partial^2 \psi_j / \partial x_0 \partial x_2 $ d2psidx(i,5) = $ \partial^2 \psi_j / \partial x_1 \partial x_2 $.
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
Return the geometric shape functions and also first and second derivatives w.r.t. global coordinates at ipt-th integration point. Numbering: 1D: d2psidx(i,0) = $ d^2 \psi_j / d s^2 $ 2D: d2psidx(i,0) = $ \partial^2 \psi_j / \partial x_0^2 $ d2psidx(i,1) = $ \partial^2 \psi_j / \partial x_1^2 $ d2psidx(i,2) = $ \partial^2 \psi_j / \partial x_0 \partial x_1 $ 3D: d2psidx(i,0) = $ \partial^2 \psi_j / \partial x_0^2 $ d2psidx(i,1) = $ \partial^2 \psi_j / \partial x_1^2 $ d2psidx(i,2) = $ \partial^2 \psi_j / \partial x_2^2 $ d2psidx(i,3) = $ \partial^2 \psi_j / \partial x_0 \partial x_1 $ d2psidx(i,4) = $ \partial^2 \psi_j / \partial x_0 \partial x_2 $ d2psidx(i,5) = $ \partial^2 \psi_j / \partial x_1 \partial x_2 $.
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for Data stored at the nodes Virtual so that it can be overloaded by RefineableFiniteElements. If the boolean is true then the pointers to the degrees of freedom associated with each equation number are stored in Dof_pt.
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the local dofs of the element[s]. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the local dofs of the element[s]. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Overloaded version of the calculation of the local equation numbers. If the boolean argument is true then pointers to the degrees of freedom associated with each equation number are stored locally in the array Dof_pt.
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
Return the number of nodes along one edge of the element Default is to return zero --- must be overloaded by geometric elements.
double raw_nodal_position (const unsigned &n, const unsigned &i) const
Return the i-th coordinate at local node n. Do not use the hanging node representation. NOTE: Moved to cc file because of a possible compiler bug in gcc (yes, really!). The move to the cc file avoids inlining which appears to cause problems (only) when compiled with gcc and -O3; offensive "illegal read" is in optimised-out section of code and data that is allegedly illegal is readily readable (by other means) just before this function is called so I can't really see how we could possibly be responsible for this...
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
Return the i-th coordinate at local node n, at time level t (t=0: present; t>0: previous time level). Do not use the hanging node representation.
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n. Do not use the hanging node representation.
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
Return the i-th component of j-th derivative of nodal position: d^jx/dt^j at node n. Do not use the hanging node representation.
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
Return the value of the k-th type of the i-th positional variable at the local node n. Do not use the hanging node representation.
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
Return the generalised nodal position (type k, i-th variable) at previous timesteps at local node n. Do not use the hanging node representation.
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
i-th component of time derivative (velocity) of the generalised position, dx(k,i)/dt at local node n. `Type': k; Coordinate direction: i. Do not use the hanging node representation.
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
i-th component of j-th time derivative of the generalised position, dx(k,i)/dt at local node n. `Type': k; Coordinate direction: i. Do not use the hanging node representation.
double nodal_position (const unsigned &n, const unsigned &i) const
Return the i-th coordinate at local node n. If the node is hanging, the appropriate interpolation is handled by the position function in the Node class.
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
Return the i-th coordinate at local node n, at time level t (t=0: present; t>0: previous time level) Returns suitably interpolated version for hanging nodes.
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
Return the i-th component of j-th derivative of nodal position: d^jx/dt^j at node n.
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
Return the value of the k-th type of the i-th positional variable at the local node n.
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
Return the generalised nodal position (type k, i-th variable) at previous timesteps at local node n.
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
i-th component of time derivative (velocity) of the generalised position, dx(k,i)/dt at local node n. `Type': k; Coordinate direction: i.
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
i-th component of j-th time derivative of the generalised position, dx(k,i)/dt at local node n. `Type': k; Coordinate direction: i.
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
Compute derivatives of elemental residual vector with respect to nodal coordinates. Default implementation by FD can be overwritten for specific elements. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}.
virtual void disable_ALE ()
This is an empty function that establishes a uniform interface for all (derived) elements that involve time-derivatives. Such elements are/should be implemented in ALE form to allow mesh motions. The additional expense associated with the computation of the mesh velocities is, of course, superfluous if the elements are used in problems in which the mesh is stationary. This function should therefore be overloaded in all derived elements that are formulated in ALE form to suppress the computation of the mesh velocities. The user disables the ALE functionality at his/her own risk! If the mesh does move after all, then the results will be wrong. Here we simply issue a warning message stating that the empty function has been called.
virtual void enable_ALE ()
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. This function is empty and simply establishes a common interface for all derived elements that are formulated in ALE form.
virtual unsigned required_nvalue (const unsigned &n) const
Number of values that must be stored at local node n by the element. The default is 0, until over-ridden by a particular element. For example, a Poisson equation requires only one value to be stored at each node; 2D Navier--Stokes equations require two values (velocity components) to be stored at each Node (provided that the pressure interpolation is discontinuous).
unsigned nnodal_position_type () const
Return the number of coordinate types that the element requires to interpolate the geometry between the nodes. For Lagrange elements it is 1.
bool has_hanging_nodes () const
Return boolean to indicate if any of the element's nodes are geometrically hanging.
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
Return the number of vertex nodes in this element. Broken virtual function in "pure" finite elements.
virtual Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element. Broken virtual function in "pure" finite elements.
virtual Node * construct_node (const unsigned &n)
Construct the local node n and return a pointer to the newly created node object.
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Construct the local node n, including storage for history values required by timestepper, and return a pointer to the newly created node object.
virtual Node * construct_boundary_node (const unsigned &n)
Construct the local node n as a boundary node; that is a node that MAY be placed on a mesh boundary and return a pointer to the newly created node object.
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Construct the local node n, including storage for history values required by timestepper, as a boundary node; that is a node that MAY be placed on a mesh boundary and return a pointer to the newly created node object.
int get_node_number (Node *const &node_pt) const
Return the number of the node *node_pt if this node is in the element, else return -1;.
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
If there is a node at this local coordinate, return the pointer to the node.
double raw_nodal_value (const unsigned &n, const unsigned &i) const
Return the i-th value stored at local node n but do NOT take hanging nodes into account.
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
Return the i-th value stored at local node n, at time level t (t=0: present; t>0 previous timesteps), but do NOT take hanging nodes into account.
double nodal_value (const unsigned &n, const unsigned &i) const
Return the i-th value stored at local node n. Produces suitably interpolated values for hanging nodes.
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
Return the i-th value stored at local node n, at time level t (t=0: present; t>0 previous timesteps). Produces suitably interpolated values for hanging nodes.
unsigned dim () const
Return the spatial dimension of the element, i.e. the number of local coordinates required to parametrise its geometry.
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
unsigned ngeom_data () const
A standard FiniteElement is fixed, so there are no geometric data when viewed in its GeomObject incarnation.
Data * geom_data_pt (const unsigned &j)
A standard FiniteElement is fixed, so there are no geometric data when viewed in its GeomObject incarnation.
void position (const Vector< double > &zeta, Vector< double > &r) const
Return the parametrised position of the FiniteElement in its incarnation as a GeomObject, r(zeta). The position is given by the Eulerian coordinate and the intrinsic coordinate (zeta) is the local coordinate of the element (s).
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
Return the parametrised position of the FiniteElement in its GeomObject incarnation: r(zeta). The position is given by the Eulerian coordinate and the intrinsic coordinate (zeta) is the local coordinate of the element (s) This version of the function returns the position as a function of time t=0: current time; t>0: previous timestep. Works for t=0 but needs to be overloaded if genuine time-dependence is required.
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
Return the t-th time derivative of the parametrised position of the FiniteElement in its GeomObject incarnation: $ \frac{d^{t} dr(zeta)}{d t^{t}} $. Call the t-th time derivative of the FE-interpolated Eulerian coordinate.
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Calculate the interpolated value of zeta, the intrinsic coordinate of the element when viewed as a compound geometric object within a Mesh as a function of the local coordinate of the element, s. The default assumption is the zeta is interpolated using the shape functions of the element with the values given by zeta_nodal(). A MacroElement representation of the intrinsic coordinate parametrised by the local coordinate s is used if available. Choosing the MacroElement representation of zeta (Eulerian x by default) allows a correspondence to be established between elements on different Meshes covering the same curvilinear domain in cases where one element is much coarser than the other.
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
For a given value of zeta, the "global" intrinsic coordinate of a mesh of FiniteElements represented as a compound geometric object, find the local coordinate in this element that corresponds to the requested value of zeta. If zeta cannot be located in this element, geom_object_pt is set to NULL. If zeta is located in this element, we return its "this" pointer. By default don't use any value passed in to the local coordinate s as the initial guess in the Newton method.
virtual void node_update ()
Update the positions of all nodes in the element using each node update function. The default implementation may be overloaded so that more efficient versions can be written.
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned > > &paired_field_data)
The purpose of this function is to identify all possible Data that can affect the fields interpolated by the FiniteElement. The information will typically be used in interaction problems in which the FiniteElement provides a forcing term for an ElementWithExternalElement. The Data must be provided as paired_load data containing.
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
The purpose of this function is to identify all Data objects that affect the elements' geometry. This function is implemented as an empty virtual function since it can only be implemented in conjunction with a node-update strategy. A specific implementation is provided in the ElementWithMovingNodes class.
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
Calculate the size of the element (length, area, volume,...) in Eulerian computational coordinates. Use suitably overloaded compute_physical_size() function to compute the actual size (taking into account factors such as 2pi or radii the integrand) -- such function can only be implemented on an equation-by-equation basis.
virtual double compute_physical_size () const
Broken virtual function to compute the actual size (taking into account factors such as 2pi or radii the integrand) -- such function can only be implemented on an equation-by-equation basis.
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
Virtual function to write the double precision numbers that appear in a single line of output into the data vector. Empty virtual, can be overloaded for specific elements; used e.g. by LineVisualiser.
void point_output (std::ostream &outfile, const Vector< double > &s)
Output solution (as defined by point_output_data()) at local cordinates s.
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
Return the number of actual plot points for paraview plot with parameter nplot. Broken virtual; can be overloaded in specific elements.
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
Return the number of local sub-elements for paraview plot with parameter nplot. Broken virtual; can be overloaded in specific elements.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
Paraview output -- this outputs the coordinates at the plot points (for parameter nplot) to specified output file.
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
Fill in the offset information for paraview plot. Broken virtual. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
Return the paraview element type. Broken virtual. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
Return the offsets for the paraview sub-elements. Broken virtual. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
virtual unsigned nscalar_paraview () const
Number of scalars/fields output by this element. Broken virtual. Needs to be implemented for each new specific element type.
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
Write values of the i-th scalar field at the plot points. Broken virtual. Needs to be implemented for each new specific element type.
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
Write values of the i-th scalar field at the plot points. Broken virtual. Needs to be implemented for each new specific element type.
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
Write values of the i-th scalar field at the plot points. Broken virtual. Needs to be implemented for each new specific element type.
virtual std::string scalar_name_paraview (const unsigned &i) const
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
virtual void output (std::ostream &outfile)
Output the element data --- typically the values at the nodes in a format suitable for post-processing.
virtual void output (std::ostream &outfile, const unsigned &n_plot)
Output the element data --- pass (some measure of) the number of plot points per element.
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
Output the element data at time step t. This is const because it is newly added and so can be done easily. Really all the output(...) functions should be const!
virtual void output (FILE *file_pt)
Output the element data --- typically the values at the nodes in a format suitable for post-processing. (C style output)
virtual void output (FILE *file_pt, const unsigned &n_plot)
Output the element data --- pass (some measure of) the number of plot points per element (C style output)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
Get cector of local coordinates of plot point i (when plotting nplot points in each "coordinate direction"). Generally these plot points will be uniformly spaced across the element. The optional final boolean flag (default: false) allows them to be shifted inwards to avoid duplication of plot point points between elements -- useful when they are used in locate_zeta, say.
virtual std::string tecplot_zone_string (const unsigned &nplot) const
Return string for tecplot zone header (when plotting nplot points in each "coordinate direction")
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
Add tecplot zone "footer" to output stream (when plotting nplot points in each "coordinate direction"). Empty by default -- can be used, e.g., to add FE connectivity lists to elements that need it.
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
Add tecplot zone "footer" to C-style output. (when plotting nplot points in each "coordinate direction"). Empty by default -- can be used, e.g., to add FE connectivity lists to elements that need it.
virtual unsigned nplot_points (const unsigned &nplot) const
Return total number of plot points (when plotting nplot points in each "coordinate direction")
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
Given the exact solution $ {\bf f}({\bf x}) $ this function calculates the norm of the error and that of the exact solution. Version with vectors of norms and errors so that different variables' norms and errors can be returned individually.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
Given the exact solution $ {\bf f}({\bf x}) $ this function calculates the norm of the error and that of the exact solution. Version with vectors of norms and errors so that different variables' norms and errors can be returned individually.
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Plot the error when compared against a given exact solution $ {\bf f}({\bf x}) $. Also calculates the norm of the error and that of the exact solution.
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Plot the error when compared against a given time-dependent exact solution $ {\bf f}(t,{\bf x}) $. Also calculates the norm of the error and that of the exact solution.
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
Plot the error when compared against a given exact solution $ {\bf f}({\bf x}) $. Also calculates the norm of the error and that of the exact solution. The version with vectors of norms and errors so that different variables' norms and errors can be returned individually.
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
Plot the error when compared against a given time-dependent exact solution $ {\bf f}(t,{\bf x}) $. Also calculates the norm of the error and that of the exact solution. The version with vectors of norms and errors so that different variables' norms and errors can be returned individually.
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
Plot the error when compared against a given exact solution $ {\bf f}({\bf x}) $. Also calculates the maximum absolute error.
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Evaluate integral of a Vector-valued function $ {\bf f}({\bf x}) $ over the element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Evaluate integral of a Vector-valued, time-dependent function $ {\bf f}(t,{\bf x}) $ over the element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
Function for building a lower dimensional FaceElement on the specified face of the FiniteElement. The arguments are the index of the face, an integer whose value depends on the particular element type, and a pointer to the FaceElement.
virtual unsigned self_test ()
Self-test: Check inversion of element & do self-test for GeneralisedElement. Return 0 if OK.
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
Get the number of the ith node on face face_index (in the bulk node vector).
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
Get a pointer to the function mapping face coordinates to bulk coordinates.
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Get a pointer to the derivative of the mapping from face to bulk coordinates.
Public Member Functions inherited from oomph::GeneralisedElement
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
Return the global equation number corresponding to the ieqn_local-th local equation number.
int local_eqn_number (const unsigned long &ieqn_global) const
Return the local equation number corresponding to the ieqn_global-th global equation number. Returns minus one (-1) if there is no local degree of freedom corresponding to the chosen global equation number.
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
Add a (pointer to an) external data object to the element and return its index (i.e. the index required to obtain it from the access function external_data_pt(...). The optional boolean flag indicates whether the data should be included in the general finite-difference loop when calculating the jacobian. The default value is true, i.e. the data will be included in the finite-differencing.
bool external_data_fd (const unsigned &i) const
Return the status of the boolean flag indicating whether the external data is included in the finite difference loop.
void exclude_external_data_fd (const unsigned &i)
Set the boolean flag to exclude the external datum from the the finite difference loop when computing the jacobian matrix.
void include_external_data_fd (const unsigned &i)
Set the boolean flag to include the external datum in the the finite difference loop when computing the jacobian matrix.
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the i-th internal data object.
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
Assign the global equation numbers to the internal Data. The arguments are the current highest global equation number (which will be incremented) and a Vector of pointers to the global variables (to which any unpinned values in the internal Data are added).
void describe_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the dofs of the element. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
Add pointers to the internal data values to map indexed by the global equation number.
void add_internal_data_values_to_vector (Vector< double > &vector_of_values)
Add all internal data and time history values to the vector in the internal storage order.
void read_internal_data_values_from_vector (const Vector< double > &vector_of_values, unsigned &index)
Read all internal data and time history values from the vector starting from index. On return the index will be set to the value at the end of the data that has been read in.
void add_internal_eqn_numbers_to_vector (Vector< long > &vector_of_eqn_numbers)
Add all equation numbers associated with internal data to the vector in the internal storage order.
void read_internal_eqn_numbers_from_vector (const Vector< long > &vector_of_eqn_numbers, unsigned &index)
Read all equation numbers associated with internal data from the vector starting from index. On return the index will be set to the value at the end of the data that has been read in.
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Setup the arrays of local equation numbers for the element. If the optional boolean argument is true, then pointers to the associated degrees of freedom are stored locally in the array Dof_pt.
virtual void complete_setup_of_dependencies ()
Complete the setup of any additional dependencies that the element may have. Empty virtual function that may be overloaded for specific derived elements. Used, e.g., for elements with algebraic node update functions to determine the "geometric Data", i.e. the Data that affects the element's shape. This function is called (for all elements) at the very beginning of the equation numbering procedure to ensure that all dependencies are accounted for.
virtual void get_residuals (Vector< double > &residuals)
Calculate the vector of residuals of the equations in the element. By default initialise the vector to zero and then call the fill_in_contribution_to_residuals() function. Note that this entire function can be overloaded if desired.
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Calculate the elemental Jacobian matrix "d equation / d variable".
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
Calculate the residuals and the elemental "mass" matrix, the matrix that multiplies the time derivative terms in a problem.
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Calculate the residuals and jacobian and elemental "mass" matrix, the matrix that multiplies the time derivative terms.
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Calculate the derivatives of the residuals with respect to a parameter.
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
Calculate the derivatives of the elemental Jacobian matrix and residuals with respect to a parameter.
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
Calculate the derivatives of the elemental Jacobian matrix mass matrix and residuals with respect to a parameter.
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Calculate the product of the Hessian (derivative of Jacobian with respect to all variables) an eigenvector, Y, and other specified vectors, C (d(J_{ij})/d u_{k}) Y_{j} C_{k}.
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned > > const &history_index, Vector< double > &inner_product)
Return the vector of inner product of the given pairs of history values.
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double > > &inner_product_vector)
Compute the vectors that when taken as a dot product with other history values give the inner product over the element.
virtual void compute_norm (Vector< double > &norm)
Compute norm of solution -- broken virtual can be overloaded by element writer to implement whatever norm is desired for the specific element.
virtual void compute_norm (double &norm)
Compute norm of solution -- broken virtual can be overloaded by element writer to implement whatever norm is desired for the specific element.
void set_halo (const unsigned &non_halo_proc_ID)
Label the element as halo and specify processor that holds non-halo counterpart.
void set_nonhalo ()
Label the element as not being a halo.
bool is_halo () const
Is this element a halo?
int non_halo_proc_ID ()
ID of processor ID that holds non-halo counterpart of halo element; negative if not a halo.
void set_must_be_kept_as_halo ()
Insist that this element be kept as a halo element during a distribute?
void unset_must_be_kept_as_halo ()
Do not insist that this element be kept as a halo element during distribution.
bool must_be_kept_as_halo () const
Test whether the element must be kept as a halo element.
virtual unsigned ndof_types () const
The number of types of degrees of freedom in this element are sub-divided into.
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for the unknowns that this element is "in charge of" -- ignore any unknowns associated with external Data. The first entry in each pair must contain the global equation number of the unknown, while the second one contains the number of the DOF type that this unknown is associated with. (The function can obviously only be called if the equation numbering scheme has been set up.)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
Constructor: Pass dimension of geometric object (# of Eulerian coords = # of Lagrangian coords; no time history available/needed)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
Constructor: pass # of Eulerian and Lagrangian coordinates. No time history available/needed.
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
Constructor: pass # of Eulerian and Lagrangian coordinates and pointer to time-stepper which is used to handle the position at previous timesteps and allows the evaluation of veloc/acceleration etc. in cases where the GeomData varies with time.
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
Access function for pointer to time stepper: Null if object is not time-dependent.
TimeStepper * time_stepper_pt () const
Access function for pointer to time stepper: Null if object is not time-dependent. Const version.
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
Parametrised position on object: r(zeta). Evaluated at the continuous time value, t.
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
Derivative of position Vector w.r.t. to coordinates: $ \frac{dR_i}{d \zeta_\alpha}$ = drdzeta(alpha,i). Evaluated at current time.
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
2nd derivative of position Vector w.r.t. to coordinates: $ \frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}$ = ddrdzeta(alpha,beta,i). Evaluated at current time.
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Posn Vector and its 1st & 2nd derivatives w.r.t. to coordinates: $ \frac{dR_i}{d \zeta_\alpha}$ = drdzeta(alpha,i). $ \frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}$ = ddrdzeta(alpha,beta,i). Evaluated at current time.
Protected Member Functions
void add_additional_values (const Vector< unsigned > &nadditional_values, const unsigned &id)
Helper function adding additional values for the unknowns associated with the FaceElement. This function also sets the map containing the position of the first entry of this face element's additional values.The inputs are the number of additional values and the face element's ID. Note the same number of additonal values are allocated at ALL nodes.
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
Assemble the jacobian matrix for the mapping from local to Eulerian coordinates, given the derivatives of the shape function w.r.t the local coordinates.
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
Assemble the the "jacobian" matrix of second derivatives of the mapping from local to Eulerian coordinates, given the second derivatives of the shape functions w.r.t. local coordinates.
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
Assemble the covariant Eulerian base vectors, assuming that the derivatives of the shape functions with respect to the local coordinates have already been constructed.
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Take the matrix passed as jacobian and return its inverse in inverse_jacobian. This function is templated by the dimension of the element because matrix inversion cannot be written efficiently in a generic manner.
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
A template-free interface that takes the matrix passed as jacobian and return its inverse in inverse_jacobian. By default the function will use the dimension of the element to call the correct invert_jacobian(..) function. This should be overloaded for efficiency (removal of a switch statement) in specific elements.
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Calculate the mapping from local to Eulerian coordinates, given the derivatives of the shape functions w.r.t. local coordinates. Returns the determinant of the jacobian, the jacobian and inverse jacobian.
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
Calculate the mapping from local to Eulerian coordinates, given the derivatives of the shape functions w.r.t. local coordinates, Return only the determinant of the jacobian and the inverse of the mapping (ds/dx).
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Calculate the mapping from local to Eulerian coordinates given the derivatives of the shape functions w.r.t the local coordinates. assuming that the coordinates are aligned in the direction of the local coordinates, i.e. there are no cross terms and the jacobian is diagonal. This function returns the determinant of the jacobian, the jacobian and the inverse jacobian.
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
A template-free interface that calculates the derivative of the jacobian of a mapping with respect to the nodal coordinates X_ij. To do this it requires the jacobian matrix and the derivatives of the shape functions w.r.t. the local coordinates. By default the function will use the dimension of the element to call the correct dJ_eulerian_dnodal_coordinates_templated_helper(..) function. This should be overloaded for efficiency (removal of a switch statement) in specific elements.
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
Calculate the derivative of the jacobian of a mapping with respect to the nodal coordinates X_ij using the jacobian matrix and the derivatives of the shape functions w.r.t. the local coordinates. This function is templated by the dimension of the element.
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
A template-free interface that calculates the derivative w.r.t. the nodal coordinates $ X_{pq} $ of the derivative of the shape functions $ \psi_j $ w.r.t. the global eulerian coordinates $ x_i $. I.e. this function calculates.
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
Calculate the derivative w.r.t. the nodal coordinates $ X_{pq} $ of the derivative of the shape functions w.r.t. the global eulerian coordinates $ x_i $, using the determinant of the jacobian mapping, its derivative w.r.t. the nodal coordinates $ X_{pq} $, the inverse jacobian and the derivatives of the shape functions w.r.t. the local coordinates. The result is returned as a tensor of rank four. Numbering: d_dpsidx_dX(p,q,j,i) = $ \frac{\partial}{\partial X_{pq}} \left( \frac{\partial \psi_j}{\partial x_i} \right) $ This function is templated by the dimension of the element.
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
Convert derivative w.r.t.local coordinates to derivatives w.r.t the coordinates used to assemble the inverse_jacobian passed in the mapping. On entry, dbasis must contain the basis function derivatives w.r.t. the local coordinates; it will contain the derivatives w.r.t. the new coordinates on exit. This is virtual so that it may be overloaded if desired for efficiency reasons.
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
Convert derivative w.r.t local coordinates to derivatives w.r.t the coordinates used to assemble the inverse jacobian passed in the mapping, assuming that the coordinates are aligned in the direction of the local coordinates. On entry dbasis must contain the derivatives of the basis functions w.r.t. the local coordinates; it will contain the derivatives w.r.t. the new coordinates. are converted into the new using the mapping inverse_jacobian.
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Convert derivatives and second derivatives w.r.t. local coordiantes to derivatives and second derivatives w.r.t. the coordinates used to assemble the jacobian, inverse jacobian and jacobian2 passed to the function. By default this function will call transform_second_derivatives_template<>(...) using the dimension of the element as the template parameter. It is virtual so that it can be overloaded by a specific element to save using a switch statement. Optionally, the element writer may wish to use the transform_second_derivatives_diagonal<>(...) function On entry dbasis and d2basis must contain the derivatives w.r.t. the local coordinates; on exit they will be the derivatives w.r.t. the transformed coordinates.
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Convert derivatives and second derivatives w.r.t. local coordinates to derivatives and second derivatives w.r.t. the coordinates used to asssmble the jacobian, inverse jacobian and jacobian2 passed in the mapping. This is templated by dimension because the method of calculation varies significantly with the dimension. On entry dbasis and d2basis must contain the derivatives w.r.t. the local coordinates; on exit they will be the derivatives w.r.t. the transformed coordinates.
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Convert derivatives and second derivatives w.r.t. local coordinates to derivatives and second derivatives w.r.t. the coordinates used to asssmble the jacobian, inverse jacobian and jacobian2 passed in the mapping. This version of the function assumes that the local coordinates are aligned with the global coordinates, i.e. the jacobians are diagonal On entry dbasis and d2basis must contain the derivatives w.r.t. the local coordinates; on exit they will be the derivatives w.r.t. the transformed coordinates.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Calculate the contributions to the jacobian from the nodal degrees of freedom using finite differences. This version of the function assumes that the residuals vector has already been calculated.
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
Calculate the contributions to the jacobian from the nodal degrees of freedom using finite differences. This version computes the residuals vector before calculating the jacobian terms.
virtual void update_before_nodal_fd ()
Function that is called before the finite differencing of any nodal data. This may be overloaded to update any dependent data before finite differencing takes place.
virtual void reset_after_nodal_fd ()
Function that is call after the finite differencing of the nodal data. This may be overloaded to reset any dependent variables that may have changed during the finite differencing.
virtual void update_in_nodal_fd (const unsigned &i)
Function called within the finite difference loop for nodal data after a change in the i-th nodal value.
virtual void reset_in_nodal_fd (const unsigned &i)
Function called within the finite difference loop for nodal data after the i-th nodal values is reset. The default behaviour is to call the update function.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the elemental contribution to the jacobian matrix. and the residuals vector. Note that this function will NOT initialise the residuals vector or the jacobian matrix. It must be called after the residuals vector and jacobian matrix have been initialised to zero. The default is to use finite differences to calculate the jacobian.
template<> double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<> double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<> double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<> double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Three-d specialisation of function to calculate inverse of jacobian mapping.
template<> void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
Zero-d specialisation of function to calculate the derivative of the jacobian of a mapping with respect to the nodal coordinates X_ij.
template<> void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
One-d specialisation of function to calculate the derivative of the jacobian of a mapping with respect to the nodal coordinates X_ij.
template<> void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
Two-d specialisation of function to calculate the derivative of the jacobian of a mapping with respect to the nodal coordinates X_ij.
template<> void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
Three-d specialisation of function to calculate the derivative of the jacobian of a mapping with respect to the nodal coordinates X_ij.
template<> void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
Zero-d specialisation of function to calculate the derivative w.r.t. the nodal coordinates $ X_{pq} $ of the derivative of the shape functions w.r.t. the global eulerian coordinates $ x_i $.
template<> void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
One-d specialisation of function to calculate the derivative w.r.t. the nodal coordinates $ X_{pq} $ of the derivative of the shape functions w.r.t. the global eulerian coordinates $ x_i $.
template<> void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
Two-d specialisation of function to calculate the derivative w.r.t. the nodal coordinates $ X_{pq} $ of the derivative of the shape functions w.r.t. the global eulerian coordinates $ x_i $.
template<> void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
Three-d specialisation of function to calculate the derivative w.r.t. the nodal coordinates $ X_{pq} $ of the derivative of the shape functions w.r.t. the global eulerian coordinates $ x_i $.
template<> void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Convert derivatives and second derivatives w.r.t local coordinates to derivatives w.r.t. the coordinates used to assemble the jacobian, inverse_jacobian and jacobian 2 passed. This must be specialised for each dimension, otherwise it gets very ugly Specialisation to one dimension.
template<> void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Convert derivatives and second derivatives w.r.t local coordinates to derivatives w.r.t. the coordinates used to assemble the jacobian, inverse_jacobian and jacobian 2 passed. This must be specialised for each dimension, otherwise it gets very ugly. Specialisation to two spatial dimensions.
template<> void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Convert derivatives and second derivatives w.r.t local coordinates to derivatives w.r.t. the coordinates used to assemble the jacobian, inverse_jacobian and jacobian 2 passed. This must be specialised for each dimension, otherwise it gets very ugly Specialisation to one dimension.
template<> void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Convert second derivatives w.r.t. local coordinates to second derivatives w.r.t. the coordinates passed in the tensor coordinate. Specialised to two spatial dimension.
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
Add a (pointer to an) internal data object to the element and return the index required to obtain it from the access function internal_data_pt(). The boolean indicates whether the datum should be included in the general finite-difference loop when calculating the jacobian. The default value is true, i.e. the data will be included in the finite differencing.
bool internal_data_fd (const unsigned &i) const
Return the status of the boolean flag indicating whether the internal data is included in the finite difference loop.
void exclude_internal_data_fd (const unsigned &i)
Set the boolean flag to exclude the internal datum from the finite difference loop when computing the jacobian matrix.
void include_internal_data_fd (const unsigned &i)
Set the boolean flag to include the internal datum in the finite difference loop when computing the jacobian matrix.
void clear_global_eqn_numbers ()
Clear the storage for the global equation numbers and pointers to dofs (if stored)
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
Add the contents of the queue global_eqn_numbers to the local storage for the local-to-global translation scheme. It is essential that the entries in the queue are added IN ORDER i.e. from the front.
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for the internal and external Data This must be called after the global equation numbers have all been assigned. It is virtual so that it can be overloaded by ElementWithExternalElements so that any external data from the external elements in included in the numbering scheme. If the boolean argument is true then pointers to the dofs will be stored in Dof_pt.
virtual void assign_additional_local_eqn_numbers ()
Setup any additional look-up schemes for local equation numbers. Examples of use include using local storage to refer to explicit degrees of freedom. The additional memory cost of such storage may or may not be offset by fast local access.
int internal_local_eqn (const unsigned &i, const unsigned &j) const
Return the local equation number corresponding to the j-th value stored at the i-th internal data.
int external_local_eqn (const unsigned &i, const unsigned &j)
Return the local equation number corresponding to the j-th value stored at the i-th external data.
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the elemental contribution to the residuals vector. Note that this function will NOT initialise the residuals vector. It must be called after the residuals vector has been initialised to zero.
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
Calculate the contributions to the jacobian from the internal degrees of freedom using finite differences. This version of the function assumes that the residuals vector has already been calculated. If the boolean argument is true, the finite differencing will be performed for all internal data, irrespective of the information in Data_fd. The default value (false) uses the information in Data_fd to selectively difference only certain data.
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
Calculate the contributions to the jacobian from the internal degrees of freedom using finite differences. This version computes the residuals vector before calculating the jacobian terms. If the boolean argument is true, the finite differencing will be performed for all internal data, irrespective of the information in Data_fd. The default value (false) uses the information in Data_fd to selectively difference only certain data.
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
Calculate the contributions to the jacobian from the external degrees of freedom using finite differences. This version of the function assumes that the residuals vector has already been calculated. If the boolean argument is true, the finite differencing will be performed for all external data, irrespective of the information in Data_fd. The default value (false) uses the information in Data_fd to selectively difference only certain data.
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
Calculate the contributions to the jacobian from the external degrees of freedom using finite differences. This version computes the residuals vector before calculating the jacobian terms. If the boolean argument is true, the finite differencing will be performed for all internal data, irrespective of the information in Data_fd. The default value (false) uses the information in Data_fd to selectively difference only certain data.
virtual void update_before_internal_fd ()
Function that is called before the finite differencing of any internal data. This may be overloaded to update any dependent data before finite differencing takes place.
virtual void reset_after_internal_fd ()
Function that is call after the finite differencing of the internal data. This may be overloaded to reset any dependent variables that may have changed during the finite differencing.
virtual void update_in_internal_fd (const unsigned &i)
Function called within the finite difference loop for internal data after a change in any values in the i-th internal data object.
virtual void reset_in_internal_fd (const unsigned &i)
Function called within the finite difference loop for internal data after the values in the i-th external data object are reset. The default behaviour is to call the update function.
virtual void update_before_external_fd ()
Function that is called before the finite differencing of any external data. This may be overloaded to update any dependent data before finite differencing takes place.
virtual void reset_after_external_fd ()
Function that is call after the finite differencing of the external data. This may be overloaded to reset any dependent variables that may have changed during the finite differencing.
virtual void update_in_external_fd (const unsigned &i)
Function called within the finite difference loop for external data after a change in any values in the i-th external data object.
virtual void reset_in_external_fd (const unsigned &i)
Function called within the finite difference loop for external data after the values in the i-th external data object are reset. The default behaviour is to call the update function.
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
Add the elemental contribution to the mass matrix matrix. and the residuals vector. Note that this function should NOT initialise the residuals vector or the mass matrix. It must be called after the residuals vector and jacobian matrix have been initialised to zero. The default is deliberately broken.
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Add the elemental contribution to the jacobian matrix, mass matrix and the residuals vector. Note that this function should NOT initialise any entries. It must be called after the residuals vector and matrices have been initialised to zero.
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Add the elemental contribution to the derivatives of the residuals with respect to a parameter. This function should NOT initialise any entries and must be called after the entries have been initialised to zero The default implementation is to use finite differences to calculate the derivatives.
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
Add the elemental contribution to the derivatives of the elemental Jacobian matrix and residuals with respect to a parameter. This function should NOT initialise any entries and must be called after the entries have been initialised to zero The default implementation is to use finite differences to calculate the derivatives.
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
Add the elemental contribution to the derivative of the jacobian matrix, mass matrix and the residuals vector with respect to the passed parameter. Note that this function should NOT initialise any entries. It must be called after the residuals vector and matrices have been initialised to zero.
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Fill in contribution to the product of the Hessian (derivative of Jacobian with respect to all variables) an eigenvector, Y, and other specified vectors, C (d(J_{ij})/d u_{k}) Y_{j} C_{k}.
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned > > const &history_index, Vector< double > &inner_product)
Fill in the contribution to the inner products between given pairs of history values.
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double > > &inner_product_vector)
Fill in the contributions to the vectors that when taken as dot product with other history values give the inner product over the element.
Protected Attributes
unsigned Boundary_number_in_bulk_mesh
The boundary number in the bulk mesh to which this element is attached.
bool Boundary_number_in_bulk_mesh_has_been_set
Has the Boundary_number_in_bulk_mesh been set? Only included if compiled with PARANOID switched on.
FiniteElement * Bulk_element_pt
Pointer to the associated higher-dimensional "bulk" element.
Vector< unsigned > Bulk_node_number
List of indices of the local node numbers in the "bulk" element that correspond to the local node numbers in the FaceElement.
Vector< unsigned > Nbulk_value
A vector that will hold the number of data values at the nodes that are associated with the "bulk" element. i.e. not including any additional degrees of freedom that might be required for extra equations that are being solved by the FaceElement.
Vector< double > * Tangent_direction_pt
A general direction pointer for the tangent vectors. This is used in the function continuous_tangent_and_outer_unit_normal() for creating continuous tangent vectors in spatial dimensions. The general direction is projected on to the surface. This technique is not required in two spatial dimensions.
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeneralisedElement
int Non_halo_proc_ID
Non-halo processor ID for Data; -1 if it's not a halo.
bool Must_be_kept_as_halo
Does this element need to be kept as a halo element during a distribute?
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Timestepper (used to handle access to geometry at previous timesteps)
Private Types
typedef void(* CoordinateMappingFctPt) (const Vector< double > &s, Vector< double > &s_bulk)
Typedef for the function that translates the face coordinate to the coordinate in the bulk element.
typedef void(* BulkCoordinateDerivativesFctPt) (const Vector< double > &s, DenseMatrix< double > &ds_bulk_dsface, unsigned &interior_direction)
Typedef for the function that returns the partial derivative of the local coordinates in the bulk element with respect to the coordinates along the face. In addition this function returns an index of one of the bulk local coordinates that varies away from the edge.
Private Attributes
CoordinateMappingFctPt Face_to_bulk_coordinate_fct_pt
Pointer to a function that translates the face coordinate to the coordinate in the bulk element.
BulkCoordinateDerivativesFctPt Bulk_coordinate_derivatives_fct_pt
Pointer to a function that returns the derivatives of the local "bulk" coordinates with respect to the local face coordinates.
Vector< unsigned > Bulk_position_type
Vector holding integers to translate additional position types to those of the "bulk" element; e.g. Bulk_position_type(1) is the position type of the "bulk" element that corresponds to face position type 1. This is required in QHermiteElements, where the slope in the direction of the 1D element is face position type 1, but may be position type 1 or 2 in the "bulk" element, depending upon which face, we are located.
int Normal_sign
Sign of outer unit normal (relative to cross-products of tangent vectors in the corresponding "bulk" element.
int Face_index
Index of the face.
Static Private Attributes
static bool Ignore_discontinuous_tangent_warning = false
Ignores the warning when the tangent vectors from continuous_tangent_and_outer_unit_normal may not be continuous as a result of the unit normal being aligned with the z axis. This can be avoided by supplying a general direction vector for the tangent vector via set_tangent_direction(...).
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
Function pointer for function that computes vector-valued steady "exact solution" $ {\bf f}({\bf x}) $ as $ \mbox{\tt fct}({\bf x}, {\bf f}) $.
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Function pointer for function that computes Vector-valued time-dependent function $ {\bf f}(t,{\bf x}) $ as $ \mbox{\tt fct}(t, {\bf x}, {\bf f}) $.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
Boolean that if set to true allows a negative jacobian in the transform between global and local coordinates (negative surface area = left-handed coordinate system).
static bool Suppress_output_while_checking_for_inverted_elements
Static boolean to suppress output while checking for inverted elements.
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_any_repeated_data = false
Static boolean to suppress warnings about repeated data. Defaults to false.
static bool Suppress_warning_about_repeated_internal_data
Static boolean to suppress warnings about repeated internal data. Defaults to false.
static bool Suppress_warning_about_repeated_external_data = true
Static boolean to suppress warnings about repeated external data. Defaults to true.
static double Default_fd_jacobian_step = 1.0e-8
Double used for the default finite difference step in elemental jacobian calculations.
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default return value for required_nvalue(n) which gives the number of "data" values required by the element at node n; for example, solving a Poisson equation would required only one "data" value at each node. The defaults is set to zero, because a general element is problem-less.
static const double Node_location_tolerance = 1.0e-14
Default value for the tolerance to be used when locating nodes via local coordinates.
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static array that holds the number of second derivatives as a function of the dimension of the element.
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
Empty dense matrix used as a dummy argument to combined residual and jacobian functions in the case when only the residuals are being assembled.
static std::deque< double * > Dof_pt_deque
Static storage for deque used to add_global_equation_numbers when pointers to the dofs in each element are not required.
Detailed Description
FaceElements are elements that coincide with the faces of higher-dimensional "bulk" elements. They are used on boundaries where additional non-trivial boundary conditions need to be applied. Examples include free surfaces, and applied traction conditions. In many cases, FaceElements need to evaluate to quantities in the associated bulk elements. For instance, the evaluation of a shear stresses on 2D FaceElement requires the evaluation of velocity derivatives in the associated 3D volume element etc. Therefore we store a pointer to the associated bulk element, and information about the relation between the local coordinates in the face and bulk elements.
Definition at line 4341 of file elements.h.
Member Typedef Documentation
BulkCoordinateDerivativesFctPt
typedef void(* oomph::FaceElement::BulkCoordinateDerivativesFctPt) (const Vector< double > &s, DenseMatrix< double > &ds_bulk_dsface, unsigned &interior_direction) [private]
Typedef for the function that returns the partial derivative of the local coordinates in the bulk element with respect to the coordinates along the face. In addition this function returns an index of one of the bulk local coordinates that varies away from the edge.
Definition at line 4353 of file elements.h.
CoordinateMappingFctPt
typedef void(* oomph::FaceElement::CoordinateMappingFctPt) (const Vector< double > &s, Vector< double > &s_bulk) [private]
Typedef for the function that translates the face coordinate to the coordinate in the bulk element.
Definition at line 4345 of file elements.h.
Constructor & Destructor Documentation
FaceElement() [1/2]
oomph::FaceElement::FaceElement () [inline]
Constructor: Initialise all appropriate member data.
Definition at line 4450 of file elements.h.
References Boundary_number_in_bulk_mesh_has_been_set, and Bulk_position_type.
~FaceElement()
virtual oomph::FaceElement::~FaceElement () [inline], [virtual]
Empty virtual destructor.
Definition at line 4469 of file elements.h.
FaceElement() [2/2]
oomph::FaceElement::FaceElement (const FaceElement &) [delete]
Broken copy constructor.
Member Function Documentation
add_additional_values()
void oomph::FaceElement::add_additional_values (const Vector< unsigned > & nadditional_values, const unsigned & id) [inline], [protected]
Helper function adding additional values for the unknowns associated with the FaceElement. This function also sets the map containing the position of the first entry of this face element's additional values.The inputs are the number of additional values and the face element's ID. Note the same number of additonal values are allocated at ALL nodes.
Definition at line 4432 of file elements.h.
References oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
Referenced by oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::FSIImposeDisplacementByLagrangeMultiplierElement(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::ImposeDisplacementByLagrangeMultiplierElement(), oomph::ImposeImpenetrabilityElement< ELEMENT >::ImposeImpenetrabilityElement(), oomph::ImposeParallelOutflowElement< ELEMENT >::ImposeParallelOutflowElement(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::LinearisedAxisymPoroelasticBJS_FSIElement(), and oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::LinearisedFSIAxisymmetricNStNoSlipBCElementElement().
boundary_number_in_bulk_mesh()
const unsigned & oomph::FaceElement::boundary_number_in_bulk_mesh () const [inline]
Broken assignment operator.
Access function for the boundary number in bulk mesh
Definition at line 4479 of file elements.h.
References Boundary_number_in_bulk_mesh.
Referenced by oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt().
bulk_coordinate_derivatives_fct_pt() [1/2]
BulkCoordinateDerivativesFctPt & oomph::FaceElement::bulk_coordinate_derivatives_fct_pt () [inline]
Return the pointer to the function that returns the derivatives of the bulk coordinates wrt the face coordinates.
Definition at line 4774 of file elements.h.
References Bulk_coordinate_derivatives_fct_pt.
Referenced by oomph::FiniteElement::build_face_element(), oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 1, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 2, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 3, NNODE_1D >::build_face_element(), oomph::TElement< 1, NNODE_1D >::build_face_element(), and oomph::TElement< 2, NNODE_1D >::build_face_element().
bulk_coordinate_derivatives_fct_pt() [2/2]
BulkCoordinateDerivativesFctPt oomph::FaceElement::bulk_coordinate_derivatives_fct_pt () const [inline]
Return the pointer to the function that returns the derivatives of the bulk coordinates wrt the face coordinates (const version)
Definition at line 4781 of file elements.h.
References Bulk_coordinate_derivatives_fct_pt.
bulk_element_pt() [1/2]
FiniteElement *& oomph::FaceElement::bulk_element_pt () [inline]
Pointer to higher-dimensional "bulk" element.
Definition at line 4739 of file elements.h.
References Bulk_element_pt.
Referenced by oomph::DGFaceElement::add_flux_contributions(), oomph::FiniteElement::build_face_element(), oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 1, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 2, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 3, NNODE_1D >::build_face_element(), oomph::TElement< 1, NNODE_1D >::build_face_element(), oomph::TElement< 2, NNODE_1D >::build_face_element(), oomph::TElement< 3, NNODE_1D >::build_face_element(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::contribution_to_total_porous_flux(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_total_porous_flux(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_volume_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::drag_force(), oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::ClampedHermiteShellBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_abc(), oomph::PointFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::get_drag_and_torque(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_kinetic_energy_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work_components(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::get_volume_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_flux_contribution(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_solid(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::HelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_power_contribution(), interpolated_dxdt(), interpolated_dxdt(), interpolated_x(), interpolated_x(), interpolated_x(), interpolated_x(), oomph::SolidFaceElement::interpolated_xi(), oomph::SolidFaceElement::interpolated_xi(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::lagrangian_eulerian_translation_factor(), oomph::RefineableNavierStokesTractionElement< ELEMENT >::ncont_interpolated_values(), oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::ncont_interpolated_values(), oomph::RefineableSolidTractionElement< ELEMENT >::ncont_interpolated_values(), oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::ncont_interpolated_values(), oomph::DGEulerFaceElement< ELEMENT >::numerical_flux(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::output(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::output(), oomph::ClampedHermiteShellBoundaryConditionElement::output(), oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::FluidInterfaceBoundingElement::reset_after_external_fd(), oomph::FluidInterfaceBoundingElement::set_contact_angle(), oomph::DGFaceElement::setup_neighbour_info(), oomph::DGElement::slope_limit(), and oomph::FluidInterfaceBoundingElement::update_in_external_fd().
bulk_element_pt() [2/2]
FiniteElement * oomph::FaceElement::bulk_element_pt () const [inline]
Pointer to higher-dimensional "bulk" element (const version)
Definition at line 4746 of file elements.h.
References Bulk_element_pt.
bulk_node_number() [1/2]
unsigned & oomph::FaceElement::bulk_node_number (const unsigned & n) [inline]
Return the bulk node number that corresponds to the n-th local node number.
Definition at line 4829 of file elements.h.
References Bulk_node_number.
Referenced by oomph::DGFaceElement::add_flux_contributions(), oomph::FiniteElement::build_face_element(), oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 1, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 2, NNODE_1D >::build_face_element(), oomph::TBubbleEnrichedElement< DIM, NNODE_1D >::build_face_element(), oomph::TElement< 1, NNODE_1D >::build_face_element(), oomph::TElement< 2, NNODE_1D >::build_face_element(), and oomph::TElement< 3, NNODE_1D >::build_face_element().
bulk_node_number() [2/2]
const unsigned & oomph::FaceElement::bulk_node_number (const unsigned & n) const [inline]
Return the bulk node number that corresponds to the n-th local node number (const version)
Definition at line 4836 of file elements.h.
References Bulk_node_number.
bulk_node_number_resize()
void oomph::FaceElement::bulk_node_number_resize (const unsigned & i) [inline]
Resize the storage for the bulk node numbers.
Definition at line 4822 of file elements.h.
References Bulk_node_number, and i.
Referenced by oomph::FiniteElement::build_face_element(), oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 1, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 2, NNODE_1D >::build_face_element(), oomph::TBubbleEnrichedElement< DIM, NNODE_1D >::build_face_element(), oomph::TElement< 1, NNODE_1D >::build_face_element(), oomph::TElement< 2, NNODE_1D >::build_face_element(), and oomph::TElement< 3, NNODE_1D >::build_face_element().
bulk_position_type() [1/2]
unsigned & oomph::FaceElement::bulk_position_type (const unsigned & i) [inline]
Return the position type in the "bulk" element that corresponds to position type i on the FaceElement.
Definition at line 4809 of file elements.h.
References Bulk_position_type, and i.
Referenced by oomph::QHermiteElement< DIM >::build_face_element(), check_J_eulerian_at_knots(), oomph::ClampedHermiteShellBoundaryConditionElement::ClampedHermiteShellBoundaryConditionElement(), continuous_tangent_and_outer_unit_normal(), J_eulerian(), J_eulerian_at_knot(), and outer_unit_normal().
bulk_position_type() [2/2]
const unsigned & oomph::FaceElement::bulk_position_type (const unsigned & i) const [inline]
Return the position type in the "bulk" element that corresponds to the position type i on the FaceElement. Const version.
Definition at line 4816 of file elements.h.
References Bulk_position_type, and i.
bulk_position_type_resize()
void oomph::FaceElement::bulk_position_type_resize (const unsigned & i) [inline]
Resize the storage for bulk_position_type to i entries.
Definition at line 4842 of file elements.h.
References Bulk_position_type, and i.
Referenced by oomph::QHermiteElement< DIM >::build_face_element(), and oomph::ClampedHermiteShellBoundaryConditionElement::ClampedHermiteShellBoundaryConditionElement().
check_J_eulerian_at_knots()
void oomph::FaceElement::check_J_eulerian_at_knots (bool & passed) const
Check that Jacobian of mapping between local and Eulerian coordinates at all integration points is positive.
Definition at line 5441 of file elements.cc.
References bulk_position_type(), oomph::FiniteElement::dim(), oomph::FiniteElement::dshape_local_at_knot(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::nodal_position_gen(), and oomph::Integral::nweight().
continuous_tangent_and_outer_unit_normal() [1/2]
void oomph::FaceElement::continuous_tangent_and_outer_unit_normal (const unsigned & ipt, Vector< Vector< double > > & tang_vec, Vector< double > & unit_normal) const
Compute the tangent vector(s) and the outer unit normal vector at the ipt-th integration point. This is a wrapper around continuous_tangent_and_outer_unit_normal(...) with the integration points converted into local coordinates.
Definition at line 6017 of file elements.cc.
References continuous_tangent_and_outer_unit_normal(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
continuous_tangent_and_outer_unit_normal() [2/2]
void oomph::FaceElement::continuous_tangent_and_outer_unit_normal (const Vector< double > & s, Vector< Vector< double > > & tang_vec, Vector< double > & unit_normal) const
Compute the tangent vector(s) and the outer unit normal vector at the specified local coordinate. In two spatial dimensions, a "tangent direction" is not required. In three spatial dimensions, a tangent direction is required (set via set_tangent_direction(...)), and we project the tanent direction on to the surface. The second tangent vector is taken to be the cross product of the projection and the unit normal.
Definition at line 5543 of file elements.cc.
References oomph::VectorHelpers::angle(), Bulk_element_pt, bulk_position_type(), oomph::VectorHelpers::cross(), oomph::FiniteElement::dim(), oomph::VectorHelpers::dot(), oomph::FiniteElement::dshape_local(), get_ds_bulk_ds_face(), get_local_coordinate_in_bulk(), i, Ignore_discontinuous_tangent_warning, oomph::VectorHelpers::magnitude(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::nodal_position_gen(), Normal_sign, oomph::MathematicalConstants::Pi, s, oomph::FiniteElement::size(), and Tangent_direction_pt.
Referenced by continuous_tangent_and_outer_unit_normal(), and oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier().
face_index() [1/2]
int & oomph::FaceElement::face_index () [inline]
Index of the face (a number that uniquely identifies the face in the element)
Definition at line 4630 of file elements.h.
References Face_index.
Referenced by oomph::AdvectionDiffusionFluxElement< ELEMENT >::AdvectionDiffusionFluxElement(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::AxisymmetricLinearElasticityTractionElement(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::AxisymmetricNavierStokesTractionElement(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::AxisymmetricPoroelasticityTractionElement(), oomph::AxisymmetricSolidTractionElement< ELEMENT >::AxisymmetricSolidTractionElement(), oomph::BiharmonicFluxElement< DIM >::BiharmonicFluxElement(), oomph::FiniteElement::build_face_element(), oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 1, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 2, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 3, NNODE_1D >::build_face_element(), oomph::TElement< 1, NNODE_1D >::build_face_element(), oomph::TElement< 2, NNODE_1D >::build_face_element(), oomph::TElement< 3, NNODE_1D >::build_face_element(), oomph::ClampedHermiteShellBoundaryConditionElement::ClampedHermiteShellBoundaryConditionElement(), oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::ClampedSlidingHermiteBeamBoundaryConditionElement(), oomph::DarcyFaceElement< ELEMENT >::DarcyFaceElement(), oomph::DGEulerFaceElement< ELEMENT >::DGEulerFaceElement(), oomph::DGEulerFaceReflectionElement< ELEMENT >::DGEulerFaceReflectionElement(), oomph::DGScalarAdvectionFaceElement< ELEMENT >::DGScalarAdvectionFaceElement(), oomph::DummyFaceElement< ELEMENT >::DummyFaceElement(), oomph::ElasticAxisymmetricVolumeConstraintBoundingElement< ELEMENT >::ElasticAxisymmetricVolumeConstraintBoundingElement(), oomph::ElasticLineVolumeConstraintBoundingElement< ELEMENT >::ElasticLineVolumeConstraintBoundingElement(), oomph::ElasticSurfaceVolumeConstraintBoundingElement< ELEMENT >::ElasticSurfaceVolumeConstraintBoundingElement(), oomph::FaceElementAsGeomObject< ELEMENT >::FaceElementAsGeomObject(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::FourierDecomposedHelmholtzBCElementBase(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::FourierDecomposedHelmholtzFluxElement(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement(), oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement(), oomph::FpPressureAdvDiffRobinBCElement< ELEMENT >::FpPressureAdvDiffRobinBCElement(), oomph::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement(), oomph::FSIAxisymmetricLinearElasticityTractionElement< ELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::FSIAxisymmetricLinearElasticityTractionElement(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::FSIImposeDisplacementByLagrangeMultiplierElement(), oomph::HelmholtzBCElementBase< ELEMENT >::HelmholtzBCElementBase(), oomph::HelmholtzFluxElement< ELEMENT >::HelmholtzFluxElement(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::HelmholtzFluxFromNormalDisplacementBCElement(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::ImposeDisplacementByLagrangeMultiplierElement(), oomph::ImposeImpenetrabilityElement< ELEMENT >::ImposeImpenetrabilityElement(), oomph::ImposeParallelOutflowElement< ELEMENT >::ImposeParallelOutflowElement(), oomph::LinearElasticityTractionElement< ELEMENT >::LinearElasticityTractionElement(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::LinearisedAxisymPoroelasticBJS_FSIElement(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::LinearisedFSIAxisymmetricNStNoSlipBCElementElement(), oomph::LinearWaveFluxElement< ELEMENT >::LinearWaveFluxElement(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::NavierStokesImpedanceTractionElement(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::NavierStokesMixedOrderSpaceTimeTractionElement(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::NavierStokesSurfaceDragTorqueElement(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::NavierStokesSurfacePowerElement(), oomph::NavierStokesTractionElement< ELEMENT >::NavierStokesTractionElement(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::PMLFourierDecomposedHelmholtzFluxElement(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::PMLFourierDecomposedHelmholtzPowerMonitorElement(), oomph::PMLHelmholtzFluxElement< ELEMENT >::PMLHelmholtzFluxElement(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::PMLHelmholtzFluxFromNormalDisplacementBCElement(), oomph::PMLHelmholtzPowerElement< ELEMENT >::PMLHelmholtzPowerElement(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >::PMLTimeHarmonicLinearElasticityTractionElement(), oomph::PoissonFluxElement< ELEMENT >::PoissonFluxElement(), oomph::PolarNavierStokesTractionElement< ELEMENT >::PolarNavierStokesTractionElement(), oomph::PolarStressIntegralElement< ELEMENT >::PolarStressIntegralElement(), oomph::PoroelasticityFaceElement< ELEMENT >::PoroelasticityFaceElement(), oomph::DGFaceElement::setup_neighbour_info(), oomph::SolidTractionElement< ELEMENT >::SolidTractionElement(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::SphericalAdvectionDiffusionFluxElement(), oomph::SpineAxisymmetricVolumeConstraintBoundingElement< ELEMENT >::SpineAxisymmetricVolumeConstraintBoundingElement(), oomph::SpineLineVolumeConstraintBoundingElement< ELEMENT >::SpineLineVolumeConstraintBoundingElement(), oomph::SpineSurfaceVolumeConstraintBoundingElement< ELEMENT >::SpineSurfaceVolumeConstraintBoundingElement(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::SteadyAxisymAdvectionDiffusionFluxElement(), oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >::TimeHarmonicFourierDecomposedLinearElasticityTractionElement(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >::TimeHarmonicLinearElasticityTractionElement(), oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement(), oomph::UnsteadyHeatFluxElement< ELEMENT >::UnsteadyHeatFluxElement(), and oomph::YoungLaplaceContactAngleElement< ELEMENT >::YoungLaplaceContactAngleElement().
face_index() [2/2]
int oomph::FaceElement::face_index () const [inline]
Index of the face (a number that uniquely identifies the face in the element) (const version)
Definition at line 4637 of file elements.h.
References Face_index.
face_to_bulk_coordinate_fct_pt() [1/2]
CoordinateMappingFctPt & oomph::FaceElement::face_to_bulk_coordinate_fct_pt () [inline]
Return the pointer to the function that maps the face coordinate to the bulk coordinate.
Definition at line 4759 of file elements.h.
References Face_to_bulk_coordinate_fct_pt.
Referenced by oomph::FiniteElement::build_face_element(), oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 1, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 2, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 3, NNODE_1D >::build_face_element(), oomph::TElement< 1, NNODE_1D >::build_face_element(), oomph::TElement< 2, NNODE_1D >::build_face_element(), and oomph::TElement< 3, NNODE_1D >::build_face_element().
face_to_bulk_coordinate_fct_pt() [2/2]
CoordinateMappingFctPt oomph::FaceElement::face_to_bulk_coordinate_fct_pt () const [inline]
Return the pointer to the function that maps the face coordinate to the bulk coordinate (const version)
Definition at line 4766 of file elements.h.
References Face_to_bulk_coordinate_fct_pt.
get_ds_bulk_ds_face()
void oomph::FaceElement::get_ds_bulk_ds_face (const Vector< double > & s, DenseMatrix< double > & dsbulk_dsface, unsigned & interior_direction) const
Calculate the derivatives of the local coordinates in the bulk element with respect to the local coordinates in this FaceElement. In addition return the index of a bulk local coordinate that varies away from the face.
Definition at line 6440 of file elements.cc.
References Bulk_coordinate_derivatives_fct_pt, and s.
Referenced by continuous_tangent_and_outer_unit_normal(), and outer_unit_normal().
get_local_coordinate_in_bulk()
void oomph::FaceElement::get_local_coordinate_in_bulk (const Vector< double > & s, Vector< double > & s_bulk) const
Calculate the vector of local coordinate in the bulk element given the local coordinates in this FaceElement.
Calculate the vector of local coordinates in bulk element, given the local coordinates in this FaceElement.
Definition at line 6415 of file elements.cc.
References Face_to_bulk_coordinate_fct_pt, and s.
Referenced by continuous_tangent_and_outer_unit_normal(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::drag_force(), oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::PointFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::get_drag_and_torque(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_kinetic_energy_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work_components(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::get_volume_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux(), outer_unit_normal(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::output(), and oomph::DGFaceElement::setup_neighbour_info().
interpolated_dxdt() [1/2]
double oomph::FaceElement::interpolated_dxdt (const Vector< double > & s, const unsigned & i, const unsigned & t) [inline], [virtual]
Return t-th time-derivative of the i-th FE-interpolated Eulerian coordinate at local coordinate s. Overloaded to get information from bulk.
Reimplemented from oomph::FiniteElement.
Definition at line 4587 of file elements.h.
References bulk_element_pt(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::interpolated_dxdt(), local_coordinate_in_bulk(), s, and t.
interpolated_dxdt() [2/2]
void oomph::FaceElement::interpolated_dxdt (const Vector< double > & s, const unsigned & t, Vector< double > & dxdt) [inline], [virtual]
Compte t-th time-derivative of the FE-interpolated Eulerian coordinate vector at local coordinate s. Overloaded to get information from bulk.
Reimplemented from oomph::FiniteElement.
Definition at line 4602 of file elements.h.
References bulk_element_pt(), oomph::FiniteElement::dim(), oomph::FiniteElement::interpolated_dxdt(), local_coordinate_in_bulk(), s, and t.
interpolated_x() [1/4]
double oomph::FaceElement::interpolated_x (const unsigned & t, const Vector< double > & s, const unsigned & i) const [inline], [virtual]
Return FE interpolated coordinate x[i] at local coordinate s at previous timestep t (t=0: present; t>0: previous timestep). Overloaded to get information from bulk.
Reimplemented from oomph::FiniteElement.
Definition at line 4545 of file elements.h.
References bulk_element_pt(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::interpolated_x(), local_coordinate_in_bulk(), s, and t.
interpolated_x() [2/4]
void oomph::FaceElement::interpolated_x (const unsigned & t, const Vector< double > & s, Vector< double > & x) const [inline], [virtual]
Return FE interpolated position x[] at local coordinate s at previous timestep t as Vector (t=0: present; t>0: previous timestep). Overloaded to get information from bulk.
Reimplemented from oomph::FiniteElement.
Definition at line 4572 of file elements.h.
References bulk_element_pt(), oomph::FiniteElement::dim(), oomph::FiniteElement::interpolated_x(), local_coordinate_in_bulk(), s, and t.
interpolated_x() [3/4]
double oomph::FaceElement::interpolated_x (const Vector< double > & s, const unsigned & i) const [inline], [virtual]
Return FE interpolated coordinate x[i] at local coordinate s. Overloaded to get information from bulk.
Reimplemented from oomph::FiniteElement.
Definition at line 4532 of file elements.h.
References bulk_element_pt(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::interpolated_x(), local_coordinate_in_bulk(), and s.
Referenced by oomph::HelmholtzBCElementBase< ELEMENT >::compute_contribution_to_fourier_components(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_enclosed_volume(), oomph::LineVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::contribution_to_total_porous_flux(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_total_porous_flux(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_volume_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::drag_force(), oomph::FluidInterfaceElement::fill_in_generic_residual_contribution_interface(), oomph::PointFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LineVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::AxisymmetricVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::SurfaceVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::get_drag_and_torque(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_kinetic_energy_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work_components(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::get_volume_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_flux_contribution(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_helmholtz(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_solid(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::HelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_power_contribution(), oomph::SurfactantTransportInterfaceElement::integrate_c(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::lagrangian_eulerian_translation_factor(), oomph::FluidInterfaceElement::output(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::output(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::output(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output(), oomph::FluidInterfaceElement::output(), oomph::SurfactantTransportInterfaceElement::output(), oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), oomph::ClampedHermiteShellBoundaryConditionElement::output(), oomph::SolidTractionElement< ELEMENT >::output(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >::output(), oomph::PoissonFluxElement< ELEMENT >::output(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >::output(), output_zeta(), oomph::DGFaceElement::report_info(), and oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::scalar_value_paraview().
interpolated_x() [4/4]
void oomph::FaceElement::interpolated_x (const Vector< double > & s, Vector< double > & x) const [inline], [virtual]
Return FE interpolated position x[] at local coordinate s as Vector Overloaded to get information from bulk.
Reimplemented from oomph::FiniteElement.
Definition at line 4559 of file elements.h.
References bulk_element_pt(), oomph::FiniteElement::dim(), oomph::FiniteElement::interpolated_x(), local_coordinate_in_bulk(), and s.
J_eulerian()
double oomph::FaceElement::J_eulerian (const Vector< double > & s) const [virtual]
Return the Jacobian of mapping from local to global coordinates at local position s. Overloaded from FiniteElement.
Calculate the determinant of the Jacobian of the mapping between local and global coordinates at the position s. Overloaded from FiniteElement.
Reimplemented from oomph::FiniteElement.
Definition at line 5273 of file elements.cc.
References bulk_position_type(), oomph::FiniteElement::dim(), oomph::FiniteElement::dshape_local(), i, oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::nodal_position_gen(), and s.
Referenced by oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::add_element_contribution_to_aux_integral(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::d_shape_and_test_local(), oomph::HelmholtzBCElementBase< ELEMENT >::d_shape_and_test_local(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::d_shape_and_test_local(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::drag_force(), oomph::ClampedHermiteShellBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::get_drag_and_torque(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_kinetic_energy_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work_components(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::get_volume_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_flux_contribution(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_helmholtz(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_solid(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::HelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_power_contribution(), oomph::ClampedHermiteShellBoundaryConditionElement::output(), oomph::AdvectionDiffusionFluxElement< ELEMENT >::shape_and_test(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::shape_and_test(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::shape_and_test(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::shape_and_test(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::shape_and_test(), oomph::HelmholtzFluxElement< ELEMENT >::shape_and_test(), oomph::LinearWaveFluxElement< ELEMENT >::shape_and_test(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::shape_and_test(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::shape_and_test(), oomph::PMLHelmholtzFluxElement< ELEMENT >::shape_and_test(), oomph::PoissonFluxElement< ELEMENT >::shape_and_test(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test(), oomph::UnsteadyHeatFluxElement< ELEMENT >::shape_and_test(), and oomph::HelmholtzBCElementBase< ELEMENT >::test_only().
J_eulerian_at_knot()
double oomph::FaceElement::J_eulerian_at_knot (const unsigned & ipt) const [virtual]
Return the Jacobian of the mapping from local to global coordinates at the ipt-th integration point Overloaded from FiniteElement.
Compute the Jacobian of the mapping between the local and global coordinates at the ipt-th integration point. Overloaded from FiniteElement.
Reimplemented from oomph::FiniteElement.
Definition at line 5359 of file elements.cc.
References bulk_position_type(), oomph::FiniteElement::dim(), oomph::FiniteElement::dshape_local_at_knot(), i, oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), and oomph::FiniteElement::nodal_position_gen().
Referenced by oomph::DGFaceElement::add_flux_contributions(), oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::ClampedHermiteShellBoundaryConditionElement::output(), oomph::AdvectionDiffusionFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::shape_and_test_at_knot(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::shape_and_test_at_knot(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::HelmholtzFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test_at_knot(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test_at_knot(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test_at_knot(), oomph::NavierStokesTractionElement< ELEMENT >::shape_and_test_at_knot(), oomph::NavierStokesFluxControlElement< ELEMENT >::shape_and_test_at_knot(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::PMLHelmholtzFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::PoissonFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::PolarNavierStokesTractionElement< ELEMENT >::shape_and_test_at_knot(), oomph::PolarStressIntegralElement< ELEMENT >::shape_and_test_at_knot(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::shape_and_test_at_knot(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test_at_knot(), and oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::shape_and_test_at_knot().
local_coordinate_in_bulk()
Vector< double > oomph::FaceElement::local_coordinate_in_bulk (const Vector< double > & s) const
Return vector of local coordinates in bulk element, given the local coordinates in this FaceElement.
Definition at line 6384 of file elements.cc.
References Bulk_element_pt, oomph::FiniteElement::dim(), Face_to_bulk_coordinate_fct_pt, and s.
Referenced by oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::contribution_to_total_porous_flux(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_total_porous_flux(), oomph::ClampedHermiteShellBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_flux_contribution(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_helmholtz(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_solid(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::HelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_power_contribution(), interpolated_dxdt(), interpolated_dxdt(), interpolated_x(), interpolated_x(), interpolated_x(), interpolated_x(), oomph::SolidFaceElement::interpolated_xi(), oomph::SolidFaceElement::interpolated_xi(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::lagrangian_eulerian_translation_factor(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::output(), and oomph::ClampedHermiteShellBoundaryConditionElement::output().
nbulk_value() [1/2]
unsigned & oomph::FaceElement::nbulk_value (const unsigned & n) [inline]
Return the number of values originally stored at local node n (before the FaceElement added additional values to it (if it did))
Definition at line 4849 of file elements.h.
References Nbulk_value.
Referenced by oomph::FiniteElement::build_face_element(), oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 1, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 2, NNODE_1D >::build_face_element(), oomph::TBubbleEnrichedElement< DIM, NNODE_1D >::build_face_element(), oomph::TElement< 1, NNODE_1D >::build_face_element(), oomph::TElement< 2, NNODE_1D >::build_face_element(), and oomph::TElement< 3, NNODE_1D >::build_face_element().
nbulk_value() [2/2]
unsigned oomph::FaceElement::nbulk_value (const unsigned & n) const [inline]
Return the number of values originally stored at local node n (before the FaceElement added additional values to it (if it did)) (const version)
Definition at line 4857 of file elements.h.
References Nbulk_value.
nbulk_value_resize()
void oomph::FaceElement::nbulk_value_resize (const unsigned & i) [inline]
Resize the storage for the number of values originally stored at the local nodes to i entries.
Definition at line 4864 of file elements.h.
References i, and Nbulk_value.
Referenced by oomph::FiniteElement::build_face_element(), oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 1, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 2, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 3, NNODE_1D >::build_face_element(), oomph::TBubbleEnrichedElement< DIM, NNODE_1D >::build_face_element(), oomph::TElement< 1, NNODE_1D >::build_face_element(), oomph::TElement< 2, NNODE_1D >::build_face_element(), and oomph::TElement< 3, NNODE_1D >::build_face_element().
normal_sign() [1/2]
int & oomph::FaceElement::normal_sign () [inline]
Sign of outer unit normal (relative to cross-products of tangent vectors in the corresponding "bulk" element.
Definition at line 4616 of file elements.h.
References Normal_sign.
Referenced by oomph::FiniteElement::build_face_element(), oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 1, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 2, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 3, NNODE_1D >::build_face_element(), oomph::TElement< 1, NNODE_1D >::build_face_element(), oomph::TElement< 2, NNODE_1D >::build_face_element(), oomph::TElement< 3, NNODE_1D >::build_face_element(), and oomph::SurfaceVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint().
normal_sign() [2/2]
int oomph::FaceElement::normal_sign () const [inline]
Return sign of outer unit normal (relative to cross-products of tangent vectors in the corresponding "bulk" element. (const version)
Definition at line 4623 of file elements.h.
References Normal_sign.
outer_unit_normal() [1/2]
void oomph::FaceElement::outer_unit_normal (const unsigned & ipt, Vector< double > & unit_normal) const
Compute outer unit normal at ipt-th integration point.
Compute the outer unit normal at the ipt-th integration point.
Definition at line 6364 of file elements.cc.
References oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), outer_unit_normal(), and s.
outer_unit_normal() [2/2]
void oomph::FaceElement::outer_unit_normal (const Vector< double > & s, Vector< double > & unit_normal) const
Compute outer unit normal at the specified local coordinate.
Compute the outer unit normal at the specified local coordinate.
Definition at line 6037 of file elements.cc.
References Bulk_element_pt, bulk_position_type(), oomph::VectorHelpers::cross(), oomph::FiniteElement::dim(), oomph::FiniteElement::dshape_local(), get_ds_bulk_ds_face(), get_local_coordinate_in_bulk(), i, oomph::VectorHelpers::magnitude(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::nodal_position_gen(), Normal_sign, s, and oomph::FiniteElement::size().
Referenced by oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::add_element_contribution_to_aux_integral(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_enclosed_volume(), oomph::LineVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::contribution_to_total_porous_flux(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_total_porous_flux(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_volume_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::drag_force(), oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::NavierStokesFluxControlElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction(), oomph::FluidInterfaceElement::fill_in_generic_residual_contribution_interface(), oomph::PointFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LineVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::AxisymmetricVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::get_drag_and_torque(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_kinetic_energy_flux(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::get_pressure(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work_components(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::get_traction(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::get_volume_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_flux_contribution(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_helmholtz(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_solid(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::HelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_power_contribution(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::lagrangian_eulerian_translation_factor(), oomph::DGFaceElement::numerical_flux_at_knot(), outer_unit_normal(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::output(), oomph::FSIAxisymmetricLinearElasticityTractionElement< ELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::output(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::output(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::output(), oomph::SurfactantTransportInterfaceElement::output(), oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::output(), oomph::SolidTractionElement< ELEMENT >::output(), oomph::FSISolidTractionElement< ELEMENT, DIM >::output(), oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), and oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::scalar_value_paraview().
output_zeta()
void oomph::FaceElement::output_zeta (std::ostream & outfile, const unsigned & nplot)
Output boundary coordinate zeta.
Definition at line 5231 of file elements.cc.
References oomph::FiniteElement::dim(), oomph::FiniteElement::get_s_plot(), i, interpolated_x(), oomph::FiniteElement::interpolated_zeta(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
resize_nodes()
void oomph::FaceElement::resize_nodes (Vector< unsigned > & nadditional_data_values) [inline]
Provide additional storage for a specified number of values at the nodes of the FaceElement. (This is needed, for instance, in free-surface elements, if the non-penetration condition is imposed by Lagrange multipliers whose values are only stored at the surface nodes but not in the interior of the bulk element). nadditional_data_values[n] specifies the number of additional values required at node n of the FaceElement. Note: Since this function is executed separately for each FaceElement, nodes that are common to multiple elements might be resized repeatedly. To avoid this, we only allow a single resize operation by comparing the number of values stored at each node to the number of values the node had when it was simply a member of the associated "bulk" element. There are cases where this will break! -- e.g. if a node is common to two FaceElements which require additional storage for distinct quantities. Such cases need to be handled by "hand-crafted" face elements.
Definition at line 4886 of file elements.h.
References Nbulk_value, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Data::nvalue(), and oomph::Node::resize().
Referenced by oomph::ClampedHermiteShellBoundaryConditionElement::ClampedHermiteShellBoundaryConditionElement(), and oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::ClampedSlidingHermiteBeamBoundaryConditionElement().
set_boundary_number_in_bulk_mesh()
void oomph::FaceElement::set_boundary_number_in_bulk_mesh (const unsigned & b) [inline]
Set function for the boundary number in bulk mesh.
Definition at line 4486 of file elements.h.
References Boundary_number_in_bulk_mesh, and Boundary_number_in_bulk_mesh_has_been_set.
set_tangent_direction()
void oomph::FaceElement::set_tangent_direction (Vector< double > * tangent_direction_pt) [inline]
Set the tangent direction vector.
Definition at line 4649 of file elements.h.
References oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::size(), Tangent_direction_pt, and tangent_direction_pt().
tangent_direction_pt()
const Vector< double > * oomph::FaceElement::tangent_direction_pt () const [inline]
Public access function for the tangent direction pointer.
Definition at line 4643 of file elements.h.
References Tangent_direction_pt.
Referenced by set_tangent_direction().
turn_off_warning_for_discontinuous_tangent()
void oomph::FaceElement::turn_off_warning_for_discontinuous_tangent () [inline]
Turn off warning for when there may be discontinuous tangent vectors from continuous_tangent_and_outer_unit_normal(...)
Definition at line 4704 of file elements.h.
References Ignore_discontinuous_tangent_warning.
turn_on_warning_for_discontinuous_tangent()
void oomph::FaceElement::turn_on_warning_for_discontinuous_tangent () [inline]
Turn on warning for when there may be discontinuous tangent vectors from continuous_tangent_and_outer_unit_normal(...)
Definition at line 4697 of file elements.h.
References Ignore_discontinuous_tangent_warning.
zeta_nodal()
double oomph::FaceElement::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
In a FaceElement, the "global" intrinsic coordinate of the element along the boundary, when viewed as part of a compound geometric object is specified using the boundary coordinate defined by the mesh. Note: Boundary coordinates will have been set up when creating the underlying mesh, and their values will have been stored at the nodes.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SpineLineVolumeConstraintBoundingElement< ELEMENT >, oomph::SpineAxisymmetricVolumeConstraintBoundingElement< ELEMENT >, oomph::SpineSurfaceVolumeConstraintBoundingElement< ELEMENT >, oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >, oomph::SolidFaceElement, oomph::FaceElementAsGeomObject< ELEMENT >, oomph::HelmholtzBCElementBase< ELEMENT >, oomph::HelmholtzFluxElement< ELEMENT >, oomph::LinearElasticityTractionElement< ELEMENT >, oomph::LinearWaveFluxElement< ELEMENT >, oomph::NavierStokesTractionElement< ELEMENT >, oomph::ImposeImpenetrabilityElement< ELEMENT >, oomph::ImposeParallelOutflowElement< ELEMENT >, oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >, oomph::NavierStokesSurfacePowerElement< ELEMENT >, oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >, oomph::PMLHelmholtzPowerElement< ELEMENT >, oomph::PMLHelmholtzFluxElement< ELEMENT >, oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >, oomph::PoissonFluxElement< ELEMENT >, oomph::PoroelasticityFaceElement< ELEMENT >, oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >, oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >, oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >, oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >, oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >, oomph::UnsteadyHeatFluxElement< ELEMENT >, oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >, and oomph::YoungLaplaceContactAngleElement< ELEMENT >.
Definition at line 4501 of file elements.h.
References Boundary_number_in_bulk_mesh, oomph::FiniteElement::dim(), oomph::Node::get_coordinates_on_boundary(), i, and oomph::FiniteElement::node_pt().
Referenced by oomph::AdvectionDiffusionFluxElement< ELEMENT >::zeta_nodal(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::zeta_nodal(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::zeta_nodal(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::zeta_nodal(), oomph::BiharmonicFluxElement< DIM >::zeta_nodal(), oomph::DarcyFaceElement< ELEMENT >::zeta_nodal(), oomph::ElasticLineVolumeConstraintBoundingElement< ELEMENT >::zeta_nodal(), oomph::SpineLineVolumeConstraintBoundingElement< ELEMENT >::zeta_nodal(), oomph::ElasticAxisymmetricVolumeConstraintBoundingElement< ELEMENT >::zeta_nodal(), oomph::SpineAxisymmetricVolumeConstraintBoundingElement< ELEMENT >::zeta_nodal(), oomph::ElasticSurfaceVolumeConstraintBoundingElement< ELEMENT >::zeta_nodal(), oomph::SpineSurfaceVolumeConstraintBoundingElement< ELEMENT >::zeta_nodal(), oomph::ElasticUpdateFluidInterfaceElement< EQUATION_CLASS, DERIVATIVE_CLASS, ELEMENT >::zeta_nodal(), oomph::ElasticPointFluidInterfaceBoundingElement< ELEMENT >::zeta_nodal(), oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >::zeta_nodal(), oomph::DGEulerFaceElement< ELEMENT >::zeta_nodal(), oomph::DGEulerFaceReflectionElement< ELEMENT >::zeta_nodal(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::zeta_nodal(), oomph::SolidFaceElement::zeta_nodal(), oomph::DummyFaceElement< ELEMENT >::zeta_nodal(), oomph::FaceElementAsGeomObject< ELEMENT >::zeta_nodal(), oomph::HelmholtzBCElementBase< ELEMENT >::zeta_nodal(), oomph::HelmholtzFluxElement< ELEMENT >::zeta_nodal(), oomph::LinearElasticityTractionElement< ELEMENT >::zeta_nodal(), oomph::LinearWaveFluxElement< ELEMENT >::zeta_nodal(), oomph::NavierStokesTractionElement< ELEMENT >::zeta_nodal(), oomph::ImposeImpenetrabilityElement< ELEMENT >::zeta_nodal(), oomph::ImposeParallelOutflowElement< ELEMENT >::zeta_nodal(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::zeta_nodal(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::zeta_nodal(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::zeta_nodal(), oomph::PMLHelmholtzPowerElement< ELEMENT >::zeta_nodal(), oomph::PMLHelmholtzFluxElement< ELEMENT >::zeta_nodal(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >::zeta_nodal(), oomph::PoissonFluxElement< ELEMENT >::zeta_nodal(), oomph::PoroelasticityFaceElement< ELEMENT >::zeta_nodal(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::zeta_nodal(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::zeta_nodal(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::zeta_nodal(), oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >::zeta_nodal(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >::zeta_nodal(), oomph::UnsteadyHeatFluxElement< ELEMENT >::zeta_nodal(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::zeta_nodal(), and oomph::YoungLaplaceContactAngleElement< ELEMENT >::zeta_nodal().
Member Data Documentation
Boundary_number_in_bulk_mesh
unsigned oomph::FaceElement::Boundary_number_in_bulk_mesh [protected]
The boundary number in the bulk mesh to which this element is attached.
Definition at line 4392 of file elements.h.
Referenced by boundary_number_in_bulk_mesh(), set_boundary_number_in_bulk_mesh(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt(), and zeta_nodal().
Boundary_number_in_bulk_mesh_has_been_set
bool oomph::FaceElement::Boundary_number_in_bulk_mesh_has_been_set [protected]
Has the Boundary_number_in_bulk_mesh been set? Only included if compiled with PARANOID switched on.
Definition at line 4398 of file elements.h.
Referenced by FaceElement(), set_boundary_number_in_bulk_mesh(), and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt().
Bulk_coordinate_derivatives_fct_pt
BulkCoordinateDerivativesFctPt oomph::FaceElement::Bulk_coordinate_derivatives_fct_pt [private]
Pointer to a function that returns the derivatives of the local "bulk" coordinates with respect to the local face coordinates.
Definition at line 4365 of file elements.h.
Referenced by bulk_coordinate_derivatives_fct_pt(), bulk_coordinate_derivatives_fct_pt(), and get_ds_bulk_ds_face().
Bulk_element_pt
FiniteElement* oomph::FaceElement::Bulk_element_pt [protected]
Pointer to the associated higher-dimensional "bulk" element.
Definition at line 4403 of file elements.h.
Referenced by bulk_element_pt(), bulk_element_pt(), continuous_tangent_and_outer_unit_normal(), oomph::ImposeImpenetrabilityElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::ImposeParallelOutflowElement< ELEMENT >::get_dof_numbers_for_unknowns(), local_coordinate_in_bulk(), and outer_unit_normal().
Bulk_node_number
Vector<unsigned> oomph::FaceElement::Bulk_node_number [protected]
List of indices of the local node numbers in the "bulk" element that correspond to the local node numbers in the FaceElement.
Definition at line 4407 of file elements.h.
Referenced by bulk_node_number(), bulk_node_number(), bulk_node_number_resize(), oomph::ImposeImpenetrabilityElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::ImposeParallelOutflowElement< ELEMENT >::get_dof_numbers_for_unknowns(), and oomph::FluidInterfaceBoundingElement::set_contact_angle().
Bulk_position_type
Vector<unsigned> oomph::FaceElement::Bulk_position_type [private]
Vector holding integers to translate additional position types to those of the "bulk" element; e.g. Bulk_position_type(1) is the position type of the "bulk" element that corresponds to face position type 1. This is required in QHermiteElements, where the slope in the direction of the 1D element is face position type 1, but may be position type 1 or 2 in the "bulk" element, depending upon which face, we are located.
Definition at line 4374 of file elements.h.
Referenced by bulk_position_type(), bulk_position_type(), bulk_position_type_resize(), and FaceElement().
Face_index
int oomph::FaceElement::Face_index [private]
Index of the face.
Definition at line 4381 of file elements.h.
Referenced by face_index(), and face_index().
Face_to_bulk_coordinate_fct_pt
CoordinateMappingFctPt oomph::FaceElement::Face_to_bulk_coordinate_fct_pt [private]
Pointer to a function that translates the face coordinate to the coordinate in the bulk element.
Definition at line 4361 of file elements.h.
Referenced by face_to_bulk_coordinate_fct_pt(), face_to_bulk_coordinate_fct_pt(), get_local_coordinate_in_bulk(), and local_coordinate_in_bulk().
Ignore_discontinuous_tangent_warning
bool oomph::FaceElement::Ignore_discontinuous_tangent_warning = false [static], [private]
Ignores the warning when the tangent vectors from continuous_tangent_and_outer_unit_normal may not be continuous as a result of the unit normal being aligned with the z axis. This can be avoided by supplying a general direction vector for the tangent vector via set_tangent_direction(...).
Definition at line 4388 of file elements.h.
Referenced by continuous_tangent_and_outer_unit_normal(), turn_off_warning_for_discontinuous_tangent(), and turn_on_warning_for_discontinuous_tangent().
Nbulk_value
Vector<unsigned> oomph::FaceElement::Nbulk_value [protected]
A vector that will hold the number of data values at the nodes that are associated with the "bulk" element. i.e. not including any additional degrees of freedom that might be required for extra equations that are being solved by the FaceElement.
Definition at line 4417 of file elements.h.
Referenced by oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::ClampedHermiteShellBoundaryConditionElement::fill_in_contribution_to_residuals(), nbulk_value(), nbulk_value(), nbulk_value_resize(), oomph::ClampedHermiteShellBoundaryConditionElement::output(), and resize_nodes().
Normal_sign
int oomph::FaceElement::Normal_sign [private]
Sign of outer unit normal (relative to cross-products of tangent vectors in the corresponding "bulk" element.
Definition at line 4378 of file elements.h.
Referenced by continuous_tangent_and_outer_unit_normal(), normal_sign(), normal_sign(), and outer_unit_normal().
Tangent_direction_pt
Vector<double>* oomph::FaceElement::Tangent_direction_pt [protected]
A general direction pointer for the tangent vectors. This is used in the function continuous_tangent_and_outer_unit_normal() for creating continuous tangent vectors in spatial dimensions. The general direction is projected on to the surface. This technique is not required in two spatial dimensions.
Definition at line 4424 of file elements.h.
Referenced by continuous_tangent_and_outer_unit_normal(), set_tangent_direction(), and tangent_direction_pt().
The documentation for this class was generated from the following files:
elements.h
elements.cc