oomph::NavierStokesImpedanceTractionElementBase Class Reference
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
#include <womersley_elements.h>
Public Member Functions
NavierStokesImpedanceTractionElementBase ()
virtual ~NavierStokesImpedanceTractionElementBase ()
Empty vitual destructor.
virtual double get_volume_flux ()=0
Pure virtual function that must be implemented to compute the volume flux that passes through this element.
virtual void add_element_contribution_to_aux_integral (std::map< unsigned, double > *aux_integral_pt)=0
Add the element's contribution to the auxiliary integral used in the element's Jacobian. The aux_integral contains the derivative of the total volume flux through the outflow boundary of the (higher-dimensional) Navier-Stokes mesh w.r.t. to the discrete (global) (velocity) degrees of freedom.
virtual void set_aux_integral_pt (std::map< unsigned, double > *aux_integral_pt)=0
Pass the pointer to the pre-computed auxiliary integral to the element so it can be accessed when computing the elemental Jacobian.
virtual void set_impedance_tube_pt (TemplateFreeWomersleyImpedanceTubeBase *impedance_tube_pt)=0
Pass the pointer to the `impedance tube` that computes the flow resistance via the solution of Womersley's equations to the element.
virtual void set_external_data_from_navier_stokes_outflow_mesh (Mesh *navier_stokes_outflow_mesh_pt_mesh_pt)=0
Pass the pointer to the mesh containing all NavierStokesImpedanceTractionElements that contribute to the volume flux into the downstream `impedance tube` to the element and classify all nodes in that mesh as external Data for this element (unless the nodes are also the element's own nodes, of course).
Protected Attributes
Mesh * Navier_stokes_outflow_mesh_pt
Pointer to mesh containing the NavierStokesImpedanceTractionElements that contribute to the volume flux into the `downstream tube` that provides the flow resistance.
Detailed Description
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
A base class for elements that allow the imposition of an impedance type boundary condition to the Navier--Stokes equations. Establishes the template-free common functionality, that they must have to be able to compute the volume flux that passes through them, etc.
Definition at line 95 of file womersley_elements.h.
Constructor & Destructor Documentation
NavierStokesImpedanceTractionElementBase()
oomph::NavierStokesImpedanceTractionElementBase::NavierStokesImpedanceTractionElementBase () [inline]
Definition at line 99 of file womersley_elements.h.
 NavierStokesImpedanceTractionElementBase()
virtual oomph::NavierStokesImpedanceTractionElementBase::~NavierStokesImpedanceTractionElementBase () [inline], [virtual]
Empty vitual destructor.
Definition at line 102 of file womersley_elements.h.
Member Function Documentation
add_element_contribution_to_aux_integral()
virtual void oomph::NavierStokesImpedanceTractionElementBase::add_element_contribution_to_aux_integral (std::map< unsigned, double > * aux_integral_pt) [pure virtual]
Add the element's contribution to the auxiliary integral used in the element's Jacobian. The aux_integral contains the derivative of the total volume flux through the outflow boundary of the (higher-dimensional) Navier-Stokes mesh w.r.t. to the discrete (global) (velocity) degrees of freedom.
Implemented in oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >.
Referenced by oomph::WomersleyImpedanceTubeBase< ELEMENT, DIM >::precompute_aux_integrals().
get_volume_flux()
virtual double oomph::NavierStokesImpedanceTractionElementBase::get_volume_flux () [pure virtual]
Pure virtual function that must be implemented to compute the volume flux that passes through this element.
Implemented in oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >.
set_aux_integral_pt()
virtual void oomph::NavierStokesImpedanceTractionElementBase::set_aux_integral_pt (std::map< unsigned, double > * aux_integral_pt) [pure virtual]
Pass the pointer to the pre-computed auxiliary integral to the element so it can be accessed when computing the elemental Jacobian.
Implemented in oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >.
Referenced by oomph::WomersleyImpedanceTubeBase< ELEMENT, DIM >::precompute_aux_integrals().
set_external_data_from_navier_stokes_outflow_mesh()
virtual void oomph::NavierStokesImpedanceTractionElementBase::set_external_data_from_navier_stokes_outflow_mesh (Mesh * navier_stokes_outflow_mesh_pt_mesh_pt) [pure virtual]
Pass the pointer to the mesh containing all NavierStokesImpedanceTractionElements that contribute to the volume flux into the downstream `impedance tube` to the element and classify all nodes in that mesh as external Data for this element (unless the nodes are also the element's own nodes, of course).
Implemented in oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >.
Referenced by oomph::WomersleyImpedanceTubeBase< ELEMENT, DIM >::WomersleyImpedanceTubeBase().
set_impedance_tube_pt()
virtual void oomph::NavierStokesImpedanceTractionElementBase::set_impedance_tube_pt (TemplateFreeWomersleyImpedanceTubeBase * impedance_tube_pt) [pure virtual]
Pass the pointer to the `impedance tube` that computes the flow resistance via the solution of Womersley's equations to the element.
Implemented in oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >.
Referenced by oomph::WomersleyImpedanceTubeBase< ELEMENT, DIM >::precompute_aux_integrals().
Member Data Documentation
Navier_stokes_outflow_mesh_pt
Mesh* oomph::NavierStokesImpedanceTractionElementBase::Navier_stokes_outflow_mesh_pt [protected]
Pointer to mesh containing the NavierStokesImpedanceTractionElements that contribute to the volume flux into the `downstream tube` that provides the flow resistance.
Definition at line 143 of file womersley_elements.h.
Referenced by oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::navier_stokes_outflow_mesh_pt(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::NavierStokesImpedanceTractionElement(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::set_external_data_from_navier_stokes_outflow_mesh(), and oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::total_volume_flux_into_downstream_tube().
The documentation for this class was generated from the following file:
womersley_elements.h