oomph::RefineableLinearisedQTaylorHoodElement Class Reference
/////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////
#include <refineable_linearised_navier_stokes_elements.h>
Public Member Functions
RefineableLinearisedQTaylorHoodElement ()
Constructor:
unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at node n. Bumped up to 8 so we don't have to worry if a hanging mid-side node gets shared by a corner node (which has extra degrees of freedom)
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: 8 (6 velocities + 2 pressures)
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: empty.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void further_setup_hanging_nodes ()
Perform additional hanging node procedures for variables that are not interpolated by all nodes. The two pressure components are stored at the 6th and 7th location in each node.
Node * interpolating_node_pt (const unsigned &n, const int &n_value)
The velocities are isoparametric and so the `nodes` interpolating the velocities are the geometric nodes. The pressure `nodes` are a subset of the nodes, so when n_value==6 or 7, the n-th pressure node is returned.
double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &n_value)
The pressure nodes are the corner nodes, so when n_value==6 or 7, the fraction is the same as the 1d node number, 0 or 1.
Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &n_value)
The velocity nodes are the same as the geometric nodes. The pressure nodes must be calculated by using the same methods as the geometric nodes, but by recalling that there are only two pressure nodes per edge.
unsigned ninterpolating_node_1d (const int &n_value)
The number of 1d pressure nodes is 2, the number of 1d velocity nodes is the same as the number of 1d geometric nodes.
unsigned ninterpolating_node (const int &n_value)
The number of pressure nodes is 4. The number of velocity nodes is the same as the number of geometric nodes.
void interpolating_basis (const Vector< double > &s, Shape &psi, const int &n_value) const
The basis interpolating the pressure is given by pshape(). / The basis interpolating the velocity is shape().
Private Member Functions
Node * pressure_node_pt (const unsigned &n_p)
Pointer to n_p-th pressure node.
void unpin_elemental_pressure_dofs ()
Unpin all pressure dofs.
void pin_elemental_redundant_nodal_pressure_dofs ()
Unpin the proper nodal pressure dofs.
Additional Inherited Members
Detailed Description
/////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////
Refineable version of linearised axisymmetric quadratic Taylor-Hood elements
Definition at line 605 of file refineable_linearised_navier_stokes_elements.h.
Constructor & Destructor Documentation
RefineableLinearisedQTaylorHoodElement()
oomph::RefineableLinearisedQTaylorHoodElement::RefineableLinearisedQTaylorHoodElement () [inline]
Constructor:
Definition at line 679 of file refineable_linearised_navier_stokes_elements.h.
Member Function Documentation
further_setup_hanging_nodes()
void oomph::RefineableLinearisedQTaylorHoodElement::further_setup_hanging_nodes () [inline], [virtual]
Perform additional hanging node procedures for variables that are not interpolated by all nodes. The two pressure components are stored at the 6th and 7th location in each node.
Implements oomph::RefineableQElement< 2 >.
Definition at line 797 of file refineable_linearised_navier_stokes_elements.h.
References i, and oomph::RefineableQElement< 2 >::setup_hang_for_value().
get_interpolated_values() [1/2]
void oomph::RefineableLinearisedQTaylorHoodElement::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 755 of file refineable_linearised_navier_stokes_elements.h.
References i, oomph::LinearisedNavierStokesEquations::interpolated_p_linearised_nst(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), t, and oomph::LinearisedNavierStokesEquations::u_index_linearised_nst().
get_interpolated_values() [2/2]
void oomph::RefineableLinearisedQTaylorHoodElement::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 728 of file refineable_linearised_navier_stokes_elements.h.
References i, oomph::LinearisedNavierStokesEquations::interpolated_p_linearised_nst(), oomph::LinearisedNavierStokesEquations::interpolated_u_linearised_nst(), and s.
get_interpolating_node_at_local_coordinate()
Node * oomph::RefineableLinearisedQTaylorHoodElement::get_interpolating_node_at_local_coordinate (const Vector< double > & s, const int & n_value) [inline], [virtual]
The velocity nodes are the same as the geometric nodes. The pressure nodes must be calculated by using the same methods as the geometric nodes, but by recalling that there are only two pressure nodes per edge.
Construct the general pressure index from the components.
Reimplemented from oomph::RefineableElement.
Definition at line 847 of file refineable_linearised_navier_stokes_elements.h.
References oomph::FiniteElement::get_node_at_local_coordinate(), i, oomph::FiniteElement::Node_location_tolerance, oomph::FiniteElement::node_pt(), oomph::LinearisedQTaylorHoodElement::Pconv, and s.
interpolating_basis()
void oomph::RefineableLinearisedQTaylorHoodElement::interpolating_basis (const Vector< double > & s, Shape & psi, const int & n_value) const [inline], [virtual]
The basis interpolating the pressure is given by pshape(). / The basis interpolating the velocity is shape().
Reimplemented from oomph::RefineableElement.
Definition at line 940 of file refineable_linearised_navier_stokes_elements.h.
References oomph::LinearisedQTaylorHoodElement::pshape_linearised_nst(), and oomph::FiniteElement::shape().
interpolating_node_pt()
Node * oomph::RefineableLinearisedQTaylorHoodElement::interpolating_node_pt (const unsigned & n, const int & n_value) [inline], [virtual]
The velocities are isoparametric and so the `nodes` interpolating the velocities are the geometric nodes. The pressure `nodes` are a subset of the nodes, so when n_value==6 or 7, the n-th pressure node is returned.
Reimplemented from oomph::RefineableElement.
Definition at line 809 of file refineable_linearised_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::LinearisedQTaylorHoodElement::Pconv.
local_one_d_fraction_of_interpolating_node()
double oomph::RefineableLinearisedQTaylorHoodElement::local_one_d_fraction_of_interpolating_node (const unsigned & n1d, const unsigned & i, const int & n_value) [inline], [virtual]
The pressure nodes are the corner nodes, so when n_value==6 or 7, the fraction is the same as the 1d node number, 0 or 1.
Reimplemented from oomph::RefineableElement.
Definition at line 827 of file refineable_linearised_navier_stokes_elements.h.
References i, and oomph::FiniteElement::local_one_d_fraction_of_node().
ncont_interpolated_values()
unsigned oomph::RefineableLinearisedQTaylorHoodElement::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values: 8 (6 velocities + 2 pressures)
Implements oomph::RefineableElement.
Definition at line 697 of file refineable_linearised_navier_stokes_elements.h.
ninterpolating_node()
unsigned oomph::RefineableLinearisedQTaylorHoodElement::ninterpolating_node (const int & n_value) [inline], [virtual]
The number of pressure nodes is 4. The number of velocity nodes is the same as the number of geometric nodes.
Reimplemented from oomph::RefineableElement.
Definition at line 926 of file refineable_linearised_navier_stokes_elements.h.
References oomph::FiniteElement::nnode().
ninterpolating_node_1d()
unsigned oomph::RefineableLinearisedQTaylorHoodElement::ninterpolating_node_1d (const int & n_value) [inline], [virtual]
The number of 1d pressure nodes is 2, the number of 1d velocity nodes is the same as the number of 1d geometric nodes.
Reimplemented from oomph::RefineableElement.
Definition at line 912 of file refineable_linearised_navier_stokes_elements.h.
References oomph::FiniteElement::nnode_1d().
nrecovery_order()
unsigned oomph::RefineableLinearisedQTaylorHoodElement::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 707 of file refineable_linearised_navier_stokes_elements.h.
nvertex_node()
unsigned oomph::RefineableLinearisedQTaylorHoodElement::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 713 of file refineable_linearised_navier_stokes_elements.h.
References oomph::FiniteElement::nvertex_node().
pin_elemental_redundant_nodal_pressure_dofs()
void oomph::RefineableLinearisedQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs () [inline], [private], [virtual]
Unpin the proper nodal pressure dofs.
Reimplemented from oomph::RefineableLinearisedNavierStokesEquations.
Definition at line 641 of file refineable_linearised_navier_stokes_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::LinearisedQTaylorHoodElement::npres_linearised_nst(), oomph::LinearisedQTaylorHoodElement::p_index_linearised_nst(), and oomph::LinearisedQTaylorHoodElement::Pconv.
pressure_node_pt()
Node * oomph::RefineableLinearisedQTaylorHoodElement::pressure_node_pt (const unsigned & n_p) [inline], [private], [virtual]
Pointer to n_p-th pressure node.
Reimplemented from oomph::RefineableLinearisedNavierStokesEquations.
Definition at line 612 of file refineable_linearised_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::LinearisedQTaylorHoodElement::Pconv.
rebuild_from_sons()
void oomph::RefineableLinearisedQTaylorHoodElement::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
Rebuild from sons: empty.
Implements oomph::RefineableElement.
Definition at line 703 of file refineable_linearised_navier_stokes_elements.h.
required_nvalue()
unsigned oomph::RefineableLinearisedQTaylorHoodElement::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values (pinned or dofs) required at node n. Bumped up to 8 so we don't have to worry if a hanging mid-side node gets shared by a corner node (which has extra degrees of freedom)
Reimplemented from oomph::LinearisedQTaylorHoodElement.
Definition at line 690 of file refineable_linearised_navier_stokes_elements.h.
unpin_elemental_pressure_dofs()
void oomph::RefineableLinearisedQTaylorHoodElement::unpin_elemental_pressure_dofs () [inline], [private], [virtual]
Unpin all pressure dofs.
Implements oomph::RefineableLinearisedNavierStokesEquations.
Definition at line 618 of file refineable_linearised_navier_stokes_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::LinearisedQTaylorHoodElement::p_index_linearised_nst().
vertex_node_pt()
Node * oomph::RefineableLinearisedQTaylorHoodElement::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 719 of file refineable_linearised_navier_stokes_elements.h.
References oomph::FiniteElement::vertex_node_pt().
The documentation for this class was generated from the following file:
refineable_linearised_navier_stokes_elements.h