oomph::MacroElementNodeUpdateNode Class Reference
MacroElementNodeUpdate nodes are nodes with a positional update function, based on their element's MacroElement representation.
#include <macro_element_node_update_element.h>
Public Member Functions
MacroElementNodeUpdateNode (const unsigned &n_dim, const unsigned &n_position_type, const unsigned &initial_nvalue)
Constructor for steady node of spatial dimension n_dim, with n_position_type generalised coordinates and with initial_nvalue dofs.
MacroElementNodeUpdateNode (TimeStepper *time_stepper_pt, const unsigned &n_dim, const unsigned &n_position_type, const unsigned &initial_nvalue)
Constructor for bog-standard node of spatial dimension n_dim, with n_position_type generalised coordinates, with initial_nvalue dofs and with time dependence.
MacroElementNodeUpdateNode (const MacroElementNodeUpdateNode &)=delete
Broken copy constructor.
virtual ~MacroElementNodeUpdateNode ()
Broken assignment operator.
void node_update (const bool &update_all_time_levels_for_new_node=false)
Update the current nodal position. If required, perform the auxiliary update of nodal values. If update_all_time_levels_for_new_node==true, previous positions are also updated -- as indicated by the name of this flag, this should only be done for newly created nodes, when this function is called from MacroElementNodeUpdateElementBase::build_macro_element_node_update_node(...)
FiniteElement *& node_update_element_pt ()
Pointer to finite element that performs the update by referring to its macro-element representation (Access required...)
Vector< double > & s_in_node_update_element ()
Vector of local coordinates of node with the finite element that performs the MacroElement-based node update operation.
unsigned ngeom_object () const
Number of geometric objects involved in node update function.
Vector< GeomObject * > & geom_object_pt ()
Vector of (pointers to) geometric objects involved in node update function.
GeomObject * geom_object_pt (const unsigned &i)
Pointer to i-th geometric object involved in node update function.
Vector< GeomObject * > & vector_geom_object_pt ()
Return vector of geometric objects involved in node update function.
GeomObject ** all_geom_object_pt ()
Return all geometric objects that affect the node update.
void set_node_update_info (FiniteElement *node_update_element_pt, const Vector< double > &s_in_node_update_element, const Vector< GeomObject * > &geom_object_pt)
Set node update information for node: Pass the pointer to the element that performs the update operation, the vector containing the node's local coordinates in that element and the vector of (pointers to) the geometric objects that affect the node update.
Public Member Functions inherited from oomph::Node
Node ()
Default constructor.
Node (const unsigned &n_dim, const unsigned &n_position_type, const unsigned &initial_n_value, const bool &allocate_x_position=true)
Steady constructor, for a Node of spatial dimension n_dim. Allocates storage for initial_n_value values. NPosition_type is the number of coordinate types needed in the mapping between local and global coordinates (e.g. 1 for Lagrange-type elements; 2 for 1D Hermite elements; 4 for 2D Hermite elements, etc).
Node (TimeStepper *const &time_stepper_pt, const unsigned &n_dim, const unsigned &n_position_type, const unsigned &initial_n_value, const bool &allocate_x_position=true)
Unsteady constructor for a node of spatial dimension n_dim. Allocates storage for initial_n_value values with history values as required by the timestepper. n_position_type: # of coordinate types needed in the mapping between local and global coordinates (e.g. 1 for Lagrange-type elements; 2 for 1D Hermite elements; 4 for 2D Hermite elements).
virtual ~Node ()
Destructor: Clean up the memory allocated for nodal position.
Node (const Node &node)=delete
Broken copy constructor.
void operator= (const Node &)=delete
Broken assignment operator.
unsigned nposition_type () const
Number of coordinate types needed in the mapping between local and global coordinates.
TimeStepper *& position_time_stepper_pt ()
Return a pointer to the position timestepper.
TimeStepper *const & position_time_stepper_pt () const
Return a pointer to the position timestepper (const version).
virtual void set_position_time_stepper (TimeStepper *const &position_time_stepper_pt, const bool &preserve_existing_data)
Set a new position timestepper be resizing the appropriate storage.
virtual bool does_pointer_correspond_to_position_data (double *const &parameter_pt)
Check whether the pointer parameter_pt addresses position data values. It never does for a standard node, because the positions are not data.
virtual void assign_eqn_numbers (unsigned long &global_ndof, Vector< double * > &dof_pt)
Assign global equation numbers; increment global number of unknowns, global_ndof; and add any new dofs to the dof_pt.
unsigned ndim () const
Return (Eulerian) spatial dimension of the node.
double & x (const unsigned &i)
Return the i-th nodal coordinate.
const double & x (const unsigned &i) const
Return the i-th nodal coordinate (const version).
double & x (const unsigned &t, const unsigned &i)
Return the position x(i) at previous timestep t (t=0: present; t>0 previous timestep).
const double & x (const unsigned &t, const unsigned &i) const
Return the position x(i) at previous timestep t (t=0: present; t>0 previous timestep) (const version)
double dx_dt (const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt.
double dx_dt (const unsigned &j, const unsigned &i) const
Return the i-th component of j-th derivative of nodal position: d^jx/dt^j.
virtual Node * copied_node_pt () const
Return pointer to copied node (null if the current node is not a copy -- always the case here; it's overloaded for boundary nodes)
virtual bool position_is_a_copy () const
Return whether any position coordinate has been copied (always false)
virtual bool position_is_a_copy (const unsigned &i) const
Return whether the position coordinate i has been copied (always false)
double & x_gen (const unsigned &k, const unsigned &i)
Reference to the generalised position x(k,i). `Type': k; Coordinate direction: i.
const double & x_gen (const unsigned &k, const unsigned &i) const
Reference to the generalised position x(k,i). `Type': k; Coordinate direction: i (const version).
double & x_gen (const unsigned &t, const unsigned &k, const unsigned &i)
Reference to the generalised position x(k,i) at the previous timestep [t=0: present]. `Type': k; Coordinate direction: i.
const double & x_gen (const unsigned &t, const unsigned &k, const unsigned &i) const
Reference to the generalised position x(k,i) at the previous timestep [t=0: present]. `Type': k; Coordinate direction: i. (const version)
double dx_gen_dt (const unsigned &k, const unsigned &i) const
i-th component of time derivative (velocity) of the generalised position, dx(k,i)/dt. `Type': k; Coordinate direction: i.
double dx_gen_dt (const unsigned &j, const unsigned &k, const unsigned &i) const
i-th component of j-th time derivative (velocity) of the generalised position, d^jx(k,i)/dt^j. `Type': k; Coordinate direction: i.
double * x_pt (const unsigned &t, const unsigned &i)
Direct access to the i-th coordinate at time level t (t=0: present; t>0: previous)
void copy (Node *orig_node_pt)
Copy all nodal data from specified Node object.
virtual void dump (std::ostream &dump_file) const
Dump nodal position and associated data to file for restart.
void read (std::ifstream &restart_file)
Read nodal position and associated data from file for restart.
virtual void pin_all ()
The pin_all() function must be overloaded by SolidNodes, so we put the virtual interface here to avoid virtual functions in Data.
virtual void unpin_all ()
The unpin_all() function must be overloaded by SolidNode, so we put the virtual interface here to avoid virtual functions in Data.
unsigned hang_code ()
Code that encapsulates the hanging status of the node (incl. the geometric hanging status) as $  \sum_{i=-1}{nval-1} Node::is_hanging(i) 2^{i+1} $.
HangInfo *const & hanging_pt () const
Return pointer to hanging node data (this refers to the geometric hanging node status) (const version).
HangInfo *const & hanging_pt (const int &i) const
Return pointer to hanging node data for value i (const version)
bool is_hanging () const
Test whether the node is geometrically hanging.
bool is_hanging (const int &i) const
Test whether the i-th value is hanging.
void set_hanging_pt (HangInfo *const &hang_pt, const int &i)
Set the hanging data for the i-th value. (hang_pt=0 to make non-hanging)
void set_nonhanging ()
Label node as non-hanging node by removing all hanging node data.
void resize (const unsigned &n_value)
Resize the number of equations.
virtual void constrain_positions ()
Constrain the positions when the node is made hanging Empty virtual function that is overloaded in SolidNodes.
virtual void unconstrain_positions ()
Unconstrain the positions when the node is made non-hanging Empty virtual function that is overloaded in SolidNodes.
virtual void make_periodic (Node *const &node_pt)
Make the node periodic by copying the values from node_pt. Note that the coordinates will always remain independent, even though this may lead to (a little) unrequired information being stored. Broken virtual (only implemented in BoundaryNodes)
virtual void make_periodic_nodes (const Vector< Node * > &periodic_nodes_pt)
Make the nodes passed in the vector periodic_nodes share the same data as this node.
virtual void get_boundaries_pt (std::set< unsigned > *&boundaries_pt)
Return a pointer to set of mesh boundaries that this node occupies; this will be overloaded by BoundaryNodes. The default behaviour is that the Node does not lie on any boundaries so the pointer to the set of boundaries is NULL.
virtual bool is_on_boundary () const
Test whether the Node lies on a boundary. The "bulk" Node cannot lie on a boundary, so return false. This will be overloaded by BoundaryNodes.
virtual bool is_on_boundary (const unsigned &b) const
Test whether the node lies on mesh boundary b. The "bulk" Node cannot lie on a boundary, so return false. This will be overloaded by BoundaryNodes.
virtual void add_to_boundary (const unsigned &b)
Broken interface for adding the node to the mesh boundary b Essentially here for error reporting.
virtual void remove_from_boundary (const unsigned &b)
Broken interface for removing the node from the mesh boundary b Here to provide error reporting.
virtual unsigned ncoordinates_on_boundary (const unsigned &b)
Get the number of boundary coordinates on mesh boundary b. Broken virtual interface provides run-time error checking.
virtual bool boundary_coordinates_have_been_set_up ()
Have boundary coordinates been set up? Broken virtual interface provides run-time error checking.
virtual void get_coordinates_on_boundary (const unsigned &b, const unsigned &k, Vector< double > &boundary_zeta)
Return the vector of the k-th generalised boundary coordinates on mesh boundary b. Broken virtual interface provides run-time error checking.
virtual void set_coordinates_on_boundary (const unsigned &b, const unsigned &k, const Vector< double > &boundary_zeta)
Set the vector of the k-th generalised boundary coordinates on mesh boundary b. Broken virtual interface provides run-time error checking.
virtual void get_coordinates_on_boundary (const unsigned &b, Vector< double > &boundary_zeta)
Return the vector of coordinates on mesh boundary b Broken virtual interface provides run-time error checking.
virtual void set_coordinates_on_boundary (const unsigned &b, const Vector< double > &boundary_zeta)
Set the vector of coordinates on mesh boundary b Broken virtual interface provides run-time error checking.
void set_obsolete ()
Mark node as obsolete.
void set_non_obsolete ()
Mark node as non-obsolete.
bool is_obsolete ()
Test whether node is obsolete.
double raw_value (const unsigned &i) const
Return the i-th value stored at the Node. This interface does NOT take the hanging status of the Node into account.
double raw_value (const unsigned &t, const unsigned &i) const
Return the i-th value at time level t (t=0: present, t>0: previous). This interface does NOT take the hanging status of the Node into account.
double value (const unsigned &i) const
Return i-th value (dofs or pinned) at this node either directly or via hanging node representation. Note that this REDFINES the interface in Data Thus, the present function will be called provided that it is accessed through a pointer to a node i.e. Node* node_pt->value() will take hanging information into account. If a pointer to a Node has been explicitly down-cast to a pointer to Data then the "wrong" (Data) version of the function will be called.
double value (const unsigned &t, const unsigned &i) const
Return i-th value at time level t (t=0: present, t>0: previous) either directly or via hanging node representation. Note that this REDEFINES the interface in Data Thus, the present function will be called provided that it is accessed through a pointer to a node i.e. Node* node_pt->value() will take hanging information into account. If a pointer to a Node has been explicitly down-cast to a pointer to Data then the "wrong" (Data) version of the function will be called.
void value (Vector< double > &values) const
Compute Vector of values for the Data value taking the hanging node status into account. Note that this REDEFINES the interface in Data Thus, the present function will be called provided that it is accessed through a pointer to a node i.e. Node* node_pt->value() will take hanging information into account. If a pointer to a Node has been explicitly down-cast to a pointer to Data then the "wrong" (Data) version of the function will be called.
Vector< double > value () const
Return vector of values calculated using value(vector).
void value (const unsigned &t, Vector< double > &values) const
Compute Vector of values (dofs or pinned) in this data at time level t (t=0: present; t>0: previous). This interface explicitly takes the hanging status into account. Thus, the present function will be called provided that it is accessed through a pointer to a node i.e. Node* node_pt->value() will take hanging information into account. If a pointer to a Node has been explicitly down-cast to a pointer to Data then the "wrong" (Data) version of the function will be called.
void position (Vector< double > &pos) const
Compute Vector of nodal positions either directly or via hanging node representation.
Vector< double > position () const
Return vector of position of node at current time.
void position (const unsigned &t, Vector< double > &pos) const
Compute Vector of nodal position at time level t (t=0: current; t>0: previous timestep), either directly or via hanging node representation.
double position (const unsigned &i) const
Return i-th nodal coordinate either directly or via hanging node representation.
double position (const unsigned &t, const unsigned &i) const
Return i-th nodal coordinate at time level t (t=0: current; t>0: previous time level), either directly or via hanging node representation.
double position_gen (const unsigned &k, const unsigned &i) const
Return generalised nodal coordinate either directly or via hanging node representation.
double position_gen (const unsigned &t, const unsigned &k, const unsigned &i) const
Return generalised nodal coordinate at time level t (t=0: current; t>0: previous time level), either directly or via hanging node representation.
double dposition_dt (const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt, either directly or via hanging node representation.
double dposition_dt (const unsigned &j, const unsigned &i) const
Return the i-th component of j-th derivative of nodal position: d^jx/dt^j either directly or via hanging node representation.
double dposition_gen_dt (const unsigned &k, const unsigned &i) const
i-th component of time derivative (velocity) of the generalised position, dx(k,i)/dt. `Type': k; Coordinate direction: i. This function uses the hanging node representation if necessary.
double dposition_gen_dt (const unsigned &j, const unsigned &k, const unsigned &i) const
i-th component of j-th time derivative (velocity) of the generalised position, d^jx(k,i)/dt^j. `Type': k; Coordinate direction: i. This function uses the hanging node representation if necessary
void set_auxiliary_node_update_fct_pt (AuxNodeUpdateFctPt aux_node_update_fct_pt)
Set pointer to auxiliary update function -- this can be used to update any nodal values following the update of the nodal position. This is needed e.g. to update the no-slip condition on moving boundaries.
bool has_auxiliary_node_update_fct_pt ()
Boolean to indicate if node has a pointer to and auxiliary update function.
void perform_auxiliary_node_update_fct ()
Execute auxiliary update function (if any) -- this can be used to update any nodal values following the update of the nodal position. This is needed e.g. to update the no-slip condition on moving boundaries.
virtual unsigned ngeom_data () const
Return the number of geometric data that affect the nodal position. The default value is zero (node is stationary)
virtual Data ** all_geom_data_pt ()
Return a pointer to an array of all (geometric) data that affect the nodal position. The default value is zero (node is stationary)
void output (std::ostream &outfile)
Output nodal position.
void add_values_to_vector (Vector< double > &vector_of_values)
Add all data and time history values to the vector. Overloaded to add the position information as well.
void read_values_from_vector (const Vector< double > &vector_of_values, unsigned &index)
Read all data and time history values from the vector starting from index. On return the index will be set the value at the end of the data that has been read in Overload to also read the position information.
Public Member Functions inherited from oomph::Data
virtual void clear_copied_pointers ()
Helper function that should be overloaded derived classes that contain copies of data. The function must unset (NULL out) the internal pointers to the copied data. This is used when destructing data to ensure that all pointers remain valid. The default implementation throws an error because Data cannot be a copy.
Data ()
Default: Just set pointer to (steady) timestepper. No storage for values is allocated.
Data (const unsigned &initial_n_value)
Default constructor for steady problems: assign memory for initial_n_value values.
Data (TimeStepper *const &time_stepper_pt, const unsigned &initial_n_value, const bool &allocate_storage=true)
Constructor for unsteady problems: assign memory for initial_n_value values and any memory required by the Timestepper for the storage of history values.
Data (const Data &data)=delete
Broken copy constructor.
void operator= (const Data &)=delete
Broken assignment operator.
virtual ~Data ()
Destructor, deallocates memory assigned for data.
void set_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set a new timestepper by resizing the appropriate storage. If already assigned the equation numbering will not be altered.
TimeStepper *& time_stepper_pt ()
Return the pointer to the timestepper.
TimeStepper *const & time_stepper_pt () const
Return the pointer to the timestepper (const version).
virtual bool is_a_copy () const
Return a boolean to indicate whether the Data objact contains any copied values. A base Data object can never be a copy so the default implementation always returns false.
virtual bool is_a_copy (const unsigned &i) const
Return flag to indicate whether the i-th value is a copy. A base Data object can never be a copy so the default implementation always returns false.
void set_value (const unsigned &i, const double &value_)
Set the i-th stored data value to specified value. The only reason that we require an explicit set function is because we redefine value() in the Node class to interpolate the values for nodes that are hanging and so we cannot return a reference to the value in this case.
void set_value (const unsigned &t, const unsigned &i, const double &value_)
Set the t-th history value of the i-th stored data value to specified value.
double value (const unsigned &i) const
Return i-th stored value. This function is not virtual so that it can be inlined. This means that if we have an explicit pointer to a Data object Data* data_pt->value() always returns the "raw" stored value.
double value (const unsigned &t, const unsigned &i) const
Return i-th value at time level t (t=0: present, t>0: previous) This function is not virtual so that it can be inlined. This means that if we have an explicit pointer to a Data object Data* data_pt->value() always returns to the "raw" stored value.
void value (Vector< double > &values) const
Compute Vector of values for the Data value.
void value (const unsigned &t, Vector< double > &values) const
Compute Vector of values (dofs or pinned) in this data at time level t (t=0: present; t>0: previous).
double * value_pt (const unsigned &i) const
Return the pointer to the i-the stored value. Typically this is required when direct access to the stored value is required, e.g. when writing functions that return a reference to a variable that is stored in a Data object.
double * value_pt (const unsigned &t, const unsigned &i) const
Return the pointer to the i-th stored value, or any of its history values (const version). Typically this is required when direct access to the stored value is required, e.g. when writing functions that return a reference to a variable that is stored in a Data object.
bool does_pointer_correspond_to_value (double *const &parameter_pt)
Check whether the pointer parameter_pt addresses internal data values.
void copy (Data *orig_data_pt)
Copy Data values from specified Data object.
void dump (std::ostream &dump_file) const
Dump the data object to a file.
void read (std::ifstream &restart_file)
Read data object from a file.
long * eqn_number_pt (const unsigned &i)
Return the pointer to the equation number of the i-th stored variable.
long & eqn_number (const unsigned &i)
Return the equation number of the i-th stored variable.
long eqn_number (const unsigned &i) const
Return the equation number of the i-th stored variable.
void pin (const unsigned &i)
Pin the i-th stored variable.
void unpin (const unsigned &i)
Unpin the i-th stored variable.
void pin_all ()
Pin all the stored variables.
void unpin_all ()
Unpin all the stored variables.
bool is_pinned (const unsigned &i) const
Test whether the i-th variable is pinned (1: true; 0: false).
bool is_segregated_solve_pinned (const unsigned &i)
Test whether the i-th variable is temporaily pinned for a segregated solve.
void constrain (const unsigned &i)
Constrain the i-th stored variable when making hanging data If the data is already pinned leave it along, otherwise mark as constrained (hanging)
void unconstrain (const unsigned &i)
Unconstrain the i-th stored variable when make the data nonhanging. Only unconstrain if it was actually constrained (hanging)
void constrain_all ()
Constrain all the stored variables when the data is made hanging.
void unconstrain_all ()
Unconstrain all the stored variables when the data is made nonhanging.
bool is_constrained (const unsigned &i)
Test whether the i-th variable is constrained (1: true; 0: false).
unsigned self_test ()
Self-test: Have all values been classified as pinned/unpinned? Return 0 if OK.
unsigned nvalue () const
Return number of values stored in data object (incl pinned ones).
unsigned ntstorage () const
Return total number of doubles stored per value to record time history of each value (one for steady problems).
virtual void describe_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the dofs of the Node. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
virtual void add_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
Add pointers to all unpinned and unconstrained data to a map indexed by (global) equation number.
void set_halo (const unsigned &non_halo_proc_ID)
Label the node as halo and specify processor that holds non-halo counterpart.
void set_nonhalo ()
Label the node as not being a halo.
bool is_halo () const
Is this Data a halo?
int non_halo_proc_ID ()
ID of processor ID that holds non-halo counterpart of halo node; negative if not a halo.
virtual void add_eqn_numbers_to_vector (Vector< long > &vector_of_eqn_numbers)
Add all equation numbers to the vector in the internal storage order.
virtual void read_eqn_numbers_from_vector (const Vector< long > &vector_of_eqn_numbers, unsigned &index)
Read all equation numbers from the vector starting from index. On return the index will be set to the value at the end of the data that has been read in.
Private Attributes
FiniteElement * Node_update_element_pt
Pointer to finite element that performs the node update by referring to its macro-element representation.
Vector< double > S_in_node_update_element
Vector containing the node's local coordinates in node update element.
Vector< GeomObject * > Geom_object_pt
Vector of geometric objects that are involved in the node update operation.
Additional Inherited Members
Public Types inherited from oomph::Node
typedef void(* AuxNodeUpdateFctPt) (Node *)
Function pointer to auxiliary node update function.
Static Public Attributes inherited from oomph::Node
static unsigned No_independent_position = 10
Static "Magic number" used to indicate that there is no independent position in a periodic node.
Static Public Attributes inherited from oomph::Data
static long Is_pinned = -1
Static "Magic number" used in place of the equation number to indicate that the value is pinned.
static long Is_segregated_solve_pinned = -3
Static "Magic number" used in place of the equation number to indicate that the value is pinned, but only for the duration of a segregated solve.
static long Is_unclassified = -10
Static "Magic number" used in place of the equation number to denote a value that hasn't been classified as pinned or free.
static long Is_constrained = -2
Static "Magic number" used in place of the equation number to indicate that the value is constrained because it is associated with non-conforming element boundaries --- a hanging node --- (and is therefore pinned)
Protected Member Functions inherited from oomph::Node
void x_gen_range_check (const unsigned &t, const unsigned &k, const unsigned &i) const
Private function to check that the arguemnts to the position functions are in range.
double * x_position_pt (const unsigned &i)
Direct access to the pointer to the i-th stored coordinate data.
Protected Member Functions inherited from oomph::Data
virtual void reset_copied_pointers ()
Helper function that should be overloaded in derived classes that can contain copies of Data. The function must reset the internal pointers to the copied data. This is used when resizing data to ensure that all the pointers remain valid. The default implementation throws an error beacause Data cannot be a copy.
Protected Attributes inherited from oomph::Node
double ** X_position
Array of pointers to the data holding the Eulerian positions. The storage format must be the same as the internal data storage so that we can implement the functions x() in generality here without the need for virtual functions. The first index will be a flat array of position types and coordinates and the second will be the number of time history values at each position type.
TimeStepper * Position_time_stepper_pt
Pointer to the timestepper associated with the position data.
HangInfo ** Hanging_pt
C-style array of pointers to hanging node info. It's set to NULL if the node isn't hanging. The first entry (0) is the geometric hanging node data. The remaining entries correspond to the hanging data for the other values stored at the node. Usually, these entries will be the same as the geometric hanging node data represented by Hanging_pt[0], but this is not necessarily the case; e.g. the pressure in Taylor Hood has different hanging node data from the velocities.
unsigned Ndim
Eulerian dimension of the node.
unsigned Nposition_type
Number of coordinate types used in the mapping between local and global coordinates (e.g. 1 for Lagrange-type elements; 2 for 1D Hermite elements; 4 for 2D Hermite elements, etc).
bool Obsolete
Flag to indicate that the Node has become obsolete --- usually during mesh refinement process.
AuxNodeUpdateFctPt Aux_node_update_fct_pt
Pointer to auxiliary update function -- this can be used to update any nodal values following the update of the nodal position. This is needed e.g. to update the no-slip condition on moving boundaries.
Protected Attributes inherited from oomph::Data
Data ** Copy_of_data_pt
C-style array of any Data objects that contain copies of the current Data object's data values.
unsigned Ncopies
Number of Data that contain copies of this Data object's values.
Static Protected Attributes inherited from oomph::Data
static TimeStepper * Default_static_time_stepper_pt = new Steady<0>()
Default (static) timestepper used in steady problems.
Detailed Description
MacroElementNodeUpdate nodes are nodes with a positional update function, based on their element's MacroElement representation.
Definition at line 48 of file macro_element_node_update_element.h.
Constructor & Destructor Documentation
MacroElementNodeUpdateNode() [1/3]
oomph::MacroElementNodeUpdateNode::MacroElementNodeUpdateNode (const unsigned & n_dim, const unsigned & n_position_type, const unsigned & initial_nvalue) [inline]
Constructor for steady node of spatial dimension n_dim, with n_position_type generalised coordinates and with initial_nvalue dofs.
Definition at line 54 of file macro_element_node_update_element.h.
MacroElementNodeUpdateNode() [2/3]
oomph::MacroElementNodeUpdateNode::MacroElementNodeUpdateNode (TimeStepper * time_stepper_pt, const unsigned & n_dim, const unsigned & n_position_type, const unsigned & initial_nvalue) [inline]
Constructor for bog-standard node of spatial dimension n_dim, with n_position_type generalised coordinates, with initial_nvalue dofs and with time dependence.
Definition at line 66 of file macro_element_node_update_element.h.
MacroElementNodeUpdateNode() [3/3]
oomph::MacroElementNodeUpdateNode::MacroElementNodeUpdateNode (const MacroElementNodeUpdateNode &) [delete]
Broken copy constructor.
~MacroElementNodeUpdateNode()
virtual oomph::MacroElementNodeUpdateNode::~MacroElementNodeUpdateNode () [inline], [virtual]
Broken assignment operator.
Destructor (empty)
Definition at line 88 of file macro_element_node_update_element.h.
Member Function Documentation
all_geom_object_pt()
GeomObject ** oomph::MacroElementNodeUpdateNode::all_geom_object_pt () [inline], [virtual]
Return all geometric objects that affect the node update.
Reimplemented from oomph::Node.
Definition at line 144 of file macro_element_node_update_element.h.
References Geom_object_pt, and oomph::FiniteElement::size().
geom_object_pt() [1/2]
Vector< GeomObject * > & oomph::MacroElementNodeUpdateNode::geom_object_pt () [inline]
Vector of (pointers to) geometric objects involved in node update function.
Definition at line 122 of file macro_element_node_update_element.h.
References Geom_object_pt.
Referenced by set_node_update_info().
geom_object_pt() [2/2]
GeomObject * oomph::MacroElementNodeUpdateNode::geom_object_pt (const unsigned & i) [inline]
Pointer to i-th geometric object involved in node update function.
Definition at line 130 of file macro_element_node_update_element.h.
References Geom_object_pt, and i.
ngeom_object()
unsigned oomph::MacroElementNodeUpdateNode::ngeom_object () const [inline], [virtual]
Number of geometric objects involved in node update function.
Reimplemented from oomph::Node.
Definition at line 115 of file macro_element_node_update_element.h.
References Geom_object_pt, and oomph::FiniteElement::size().
node_update()
void oomph::MacroElementNodeUpdateNode::node_update (const bool & update_all_time_levels_for_new_node = false) [virtual]
Update the current nodal position. If required, perform the auxiliary update of nodal values. If update_all_time_levels_for_new_node==true, previous positions are also updated -- as indicated by the name of this flag, this should only be done for newly created nodes, when this function is called from MacroElementNodeUpdateElementBase::build_macro_element_node_update_node(...)
Excute the update function: Update the current (and if update_all_time_levels_for_new_node==true also the previous) nodal position. Also update the current nodal values if an auxiliary update function is defined. Note: Updating of previous positions is only required (and should only be performed for) newly created MacroElementNodeUpdateNodes i.e. when this function is called from... If a node is hanging, its position is determined via its hanging node constraints after updating the position of its master nodes.
Reimplemented from oomph::Node.
Definition at line 48 of file macro_element_node_update_element.cc.
References oomph::Node::Aux_node_update_fct_pt, oomph::FiniteElement::get_x(), oomph::Node::hanging_pt(), i, oomph::Node::is_hanging(), oomph::HangInfo::master_node_pt(), oomph::Node::ndim(), oomph::HangInfo::nmaster(), node_update(), Node_update_element_pt, oomph::TimeStepper::nprev_values(), oomph::Node::Position_time_stepper_pt, S_in_node_update_element, t, and oomph::Node::x().
Referenced by node_update().
node_update_element_pt()
FiniteElement *& oomph::MacroElementNodeUpdateNode::node_update_element_pt () [inline]
Pointer to finite element that performs the update by referring to its macro-element representation (Access required...)
Definition at line 101 of file macro_element_node_update_element.h.
References Node_update_element_pt.
Referenced by set_node_update_info().
s_in_node_update_element()
Vector< double > & oomph::MacroElementNodeUpdateNode::s_in_node_update_element () [inline]
Vector of local coordinates of node with the finite element that performs the MacroElement-based node update operation.
Definition at line 109 of file macro_element_node_update_element.h.
References S_in_node_update_element.
Referenced by set_node_update_info().
set_node_update_info()
void oomph::MacroElementNodeUpdateNode::set_node_update_info (FiniteElement * node_update_element_pt, const Vector< double > & s_in_node_update_element, const Vector< GeomObject * > & geom_object_pt) [inline]
Set node update information for node: Pass the pointer to the element that performs the update operation, the vector containing the node's local coordinates in that element and the vector of (pointers to) the geometric objects that affect the node update.
Definition at line 161 of file macro_element_node_update_element.h.
References geom_object_pt(), Geom_object_pt, node_update_element_pt(), Node_update_element_pt, s_in_node_update_element(), and S_in_node_update_element.
vector_geom_object_pt()
Vector< GeomObject * > & oomph::MacroElementNodeUpdateNode::vector_geom_object_pt () [inline]
Return vector of geometric objects involved in node update function.
Definition at line 138 of file macro_element_node_update_element.h.
References Geom_object_pt.
Member Data Documentation
Geom_object_pt
Vector<GeomObject*> oomph::MacroElementNodeUpdateNode::Geom_object_pt [private]
Vector of geometric objects that are involved in the node update operation.
Definition at line 182 of file macro_element_node_update_element.h.
Referenced by all_geom_object_pt(), geom_object_pt(), geom_object_pt(), ngeom_object(), set_node_update_info(), and vector_geom_object_pt().
Node_update_element_pt
FiniteElement* oomph::MacroElementNodeUpdateNode::Node_update_element_pt [private]
Pointer to finite element that performs the node update by referring to its macro-element representation.
Definition at line 174 of file macro_element_node_update_element.h.
Referenced by node_update(), node_update_element_pt(), and set_node_update_info().
S_in_node_update_element
Vector<double> oomph::MacroElementNodeUpdateNode::S_in_node_update_element [private]
Vector containing the node's local coordinates in node update element.
Definition at line 178 of file macro_element_node_update_element.h.
Referenced by node_update(), s_in_node_update_element(), and set_node_update_info().
The documentation for this class was generated from the following files:
macro_element_node_update_element.h
macro_element_node_update_element.cc