oomph::RefineableUnsteadyHeatEquations< DIM > Class Template Reference
////////////////////////////////////////////////////////////////////////
#include <refineable_unsteady_heat_elements.h>
Public Member Functions
RefineableUnsteadyHeatEquations ()
Constructor.
RefineableUnsteadyHeatEquations (const RefineableUnsteadyHeatEquations< DIM > &dummy)=delete
Broken copy constructor.
unsigned num_Z2_flux_terms ()
Broken assignment operator.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Standard flux.from UnsteadyHeat equations.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void further_build ()
Further build: Copy source function pointer from father element.
Private Member Functions
void fill_in_generic_residual_contribution_ust_heat (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Add element's contribution to elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::RefineableUnsteadyHeatEquations< DIM >
////////////////////////////////////////////////////////////////////////
Refineable version of Unsteady HEat equations
Definition at line 56 of file refineable_unsteady_heat_elements.h.
Constructor & Destructor Documentation
RefineableUnsteadyHeatEquations() [1/2]
template<unsigned DIM>
oomph::RefineableUnsteadyHeatEquations< DIM >::RefineableUnsteadyHeatEquations () [inline]
Constructor.
Definition at line 63 of file refineable_unsteady_heat_elements.h.
RefineableUnsteadyHeatEquations() [2/2]
template<unsigned DIM>
oomph::RefineableUnsteadyHeatEquations< DIM >::RefineableUnsteadyHeatEquations (const RefineableUnsteadyHeatEquations< DIM > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
fill_in_generic_residual_contribution_ust_heat()
template<unsigned DIM>
void oomph::RefineableUnsteadyHeatEquations< DIM >::fill_in_generic_residual_contribution_ust_heat (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [private]
Add element's contribution to elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Add element's contribution to the elemental residual vector and/or Jacobian matrix. flag=1: compute both flag=0: compute only residual vector.
Definition at line 38 of file refineable_unsteady_heat_elements.cc.
References i, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), s, and oomph::W.
further_build()
template<unsigned DIM>
void oomph::RefineableUnsteadyHeatEquations< DIM >::further_build () [inline], [virtual]
Further build: Copy source function pointer from father element.
Reimplemented from oomph::RefineableElement.
Definition at line 162 of file refineable_unsteady_heat_elements.h.
References oomph::RefineableElement::father_element_pt().
get_interpolated_values() [1/2]
template<unsigned DIM>
void oomph::RefineableUnsteadyHeatEquations< DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 133 of file refineable_unsteady_heat_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, and oomph::FiniteElement::shape().
get_interpolated_values() [2/2]
template<unsigned DIM>
void oomph::RefineableUnsteadyHeatEquations< DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 100 of file refineable_unsteady_heat_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, and oomph::FiniteElement::shape().
get_Z2_flux()
template<unsigned DIM>
void oomph::RefineableUnsteadyHeatEquations< DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Standard flux.from UnsteadyHeat equations.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 91 of file refineable_unsteady_heat_elements.h.
References s.
num_Z2_flux_terms()
template<unsigned DIM>
unsigned oomph::RefineableUnsteadyHeatEquations< DIM >::num_Z2_flux_terms () [inline], [virtual]
Broken assignment operator.
Number of 'flux' terms for Z2 error estimation
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 84 of file refineable_unsteady_heat_elements.h.
The documentation for this class was generated from the following files:
refineable_unsteady_heat_elements.h
refineable_unsteady_heat_elements.cc