oomph::ClampedSlidingHermiteBeamBoundaryConditionElement Class Reference
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
#include <beam_elements.h>
Public Member Functions
ClampedSlidingHermiteBeamBoundaryConditionElement (FiniteElement *const &bulk_el_pt, const int &face_index)
Constructor, takes the pointer to the `bulk` element, the index of the fixed local coordinate and its value represented by an integer (+/- 1), indicating that the face is located at the max. or min. value of the `fixed` local coordinate in the bulk element.
ClampedSlidingHermiteBeamBoundaryConditionElement ()
Broken empty constructor.
ClampedSlidingHermiteBeamBoundaryConditionElement (const ClampedSlidingHermiteBeamBoundaryConditionElement &dummy)=delete
Broken copy constructor.
void set_symmetry_line (const Vector< double > &vector_to_symmetry_line, const Vector< double > &normal_to_symmetry_line)
Broken assignment operator.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in the element's contribution to its residual vector.
void output (std::ostream &outfile)
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
void output (std::ostream &outfile, const unsigned &n_plot)
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
void output (FILE *file_pt)
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Private Attributes
Vector< double > Vector_to_symmetry_line
Vector to some point on the symmetry line along which the end of the beam is sliding.
Vector< double > Normal_to_symmetry_line
Normal vector to the symmetry line along which the end of the beam is sliding.
Additional Inherited Members
Detailed Description
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Element that allows the imposition of boundary conditions for a beam that is clamped but can slide along a line which is specified by a position vector to that line and the normal vector to it. The endpoint of the beam is forced to stay on that line and meet it at a right angle. This is achieved with Lagrange multipliers.
Definition at line 509 of file beam_elements.h.
Constructor & Destructor Documentation
ClampedSlidingHermiteBeamBoundaryConditionElement() [1/3]
oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::ClampedSlidingHermiteBeamBoundaryConditionElement (FiniteElement *const & bulk_el_pt, const int & face_index)
Constructor, takes the pointer to the `bulk` element, the index of the fixed local coordinate and its value represented by an integer (+/- 1), indicating that the face is located at the max. or min. value of the `fixed` local coordinate in the bulk element.
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
Constructor, takes the pointer to the `bulk` element, the index of the fixed local coordinate and its value represented by an integer (+/- 1), indicating that the face is located at the max. or min. value of the `fixed` local coordinate in the bulk element.
Definition at line 1318 of file beam_elements.cc.
References oomph::FiniteElement::build_face_element(), oomph::FaceElement::face_index(), Normal_to_symmetry_line, oomph::FaceElement::resize_nodes(), oomph::FiniteElement::set_nnodal_position_type(), and Vector_to_symmetry_line.
ClampedSlidingHermiteBeamBoundaryConditionElement() [2/3]
oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::ClampedSlidingHermiteBeamBoundaryConditionElement () [inline]
Broken empty constructor.
Definition at line 523 of file beam_elements.h.
ClampedSlidingHermiteBeamBoundaryConditionElement() [3/3]
oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::ClampedSlidingHermiteBeamBoundaryConditionElement (const ClampedSlidingHermiteBeamBoundaryConditionElement & dummy) [delete]
Broken copy constructor.
Member Function Documentation
fill_in_contribution_to_residuals()
void oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::fill_in_contribution_to_residuals (Vector< double > & residuals) [virtual]
Fill in the element's contribution to its residual vector.
Add the element's contribution to its residual vector. Loop over directions
Reimplemented from oomph::GeneralisedElement.
Definition at line 1356 of file beam_elements.cc.
References oomph::FaceElement::bulk_element_pt(), oomph::FaceElement::get_local_coordinate_in_bulk(), oomph::KirchhoffLoveBeamEquations::get_non_unit_tangent(), oomph::KirchhoffLoveBeamEquations::get_normal(), i, oomph::FaceElement::Nbulk_value, oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), Normal_to_symmetry_line, oomph::SolidFiniteElement::position_local_eqn(), s, oomph::Node::value(), and Vector_to_symmetry_line.
output() [1/4]
void oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::output (FILE * file_pt) [inline], [virtual]
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 578 of file beam_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
void oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 586 of file beam_elements.h.
References oomph::FiniteElement::output().
output() [3/4]
void oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::output (std::ostream & outfile) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 564 of file beam_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
void oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 571 of file beam_elements.h.
References oomph::FiniteElement::output().
set_symmetry_line()
void oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::set_symmetry_line (const Vector< double > & vector_to_symmetry_line, const Vector< double > & normal_to_symmetry_line) [inline]
Broken assignment operator.
Set vectors to some point on the symmetry line, and normal to that line along which the end of the beam is sliding.
Definition at line 548 of file beam_elements.h.
References Normal_to_symmetry_line, and Vector_to_symmetry_line.
Member Data Documentation
Normal_to_symmetry_line
Vector<double> oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::Normal_to_symmetry_line [private]
Normal vector to the symmetry line along which the end of the beam is sliding.
Definition at line 598 of file beam_elements.h.
Referenced by ClampedSlidingHermiteBeamBoundaryConditionElement(), fill_in_contribution_to_residuals(), and set_symmetry_line().
Vector_to_symmetry_line
Vector<double> oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::Vector_to_symmetry_line [private]
Vector to some point on the symmetry line along which the end of the beam is sliding.
Definition at line 594 of file beam_elements.h.
Referenced by ClampedSlidingHermiteBeamBoundaryConditionElement(), fill_in_contribution_to_residuals(), and set_symmetry_line().
The documentation for this class was generated from the following files:
beam_elements.h
beam_elements.cc