oomph::UnsteadyHeatEquations< DIM > Class Template Reference
#include <unsteady_heat_elements.h>
Public Types
typedef void(* UnsteadyHeatSourceFctPt) (const double &time, const Vector< double > &x, double &u)
Function pointer to source function fct(t,x,f(x,t)) -- x is a Vector!
Public Member Functions
UnsteadyHeatEquations ()
Constructor: Initialises the Source_fct_pt to null and sets flag to use ALE formulation of the equations. Also set Alpha (thermal inertia) and Beta (thermal conductivity) parameters to defaults (both one for natural scaling)
UnsteadyHeatEquations (const UnsteadyHeatEquations &dummy)
Broken copy constructor.
virtual unsigned u_index_ust_heat () const
Broken assignment operator.
double du_dt_ust_heat (const unsigned &n) const
du/dt at local node n. Uses suitably interpolated value for hanging nodes.
void disable_ALE ()
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
void enable_ALE ()
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
void compute_norm (double &norm)
Compute norm of fe solution.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &nplot)
Output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points.
virtual void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points (time-dependent version)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Get error against and norm of exact solution.
UnsteadyHeatSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
UnsteadyHeatSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
virtual void get_source_ust_heat (const double &t, const unsigned &ipt, const Vector< double > &x, double &source) const
Get source term at continous time t and (Eulerian) position x. Virtual so it can be overloaded in derived multiphysics elements.
const double & alpha () const
Alpha parameter (thermal inertia)
double *& alpha_pt ()
Pointer to Alpha parameter (thermal inertia)
const double & beta () const
Beta parameter (thermal conductivity)
double *& beta_pt ()
Pointer to Beta parameter (thermal conductivity)
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: flux[i] = du/dx_i.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute element residual Vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute element residual Vector and element Jacobian matrix (wrapper)
double interpolated_u_ust_heat (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
double interpolated_u_ust_heat (const unsigned &t, const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s at previous time t (t=0: present)
double interpolated_du_dt_ust_heat (const Vector< double > &s) const
unsigned self_test ()
Self-test: Return 0 for OK.
Protected Member Functions
virtual double dshape_and_dtest_eulerian_ust_heat (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_ust_heat (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
virtual void fill_in_generic_residual_contribution_ust_heat (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Protected Attributes
UnsteadyHeatSourceFctPt Source_fct_pt
Pointer to source function:
bool ALE_is_disabled
Boolean flag to indicate if ALE formulation is disabled when time-derivatives are computed. Only set to true if you're sure that the mesh is stationary.
double * Alpha_pt
Pointer to Alpha parameter (thermal inertia)
double * Beta_pt
Pointer to Beta parameter (thermal conductivity)
Static Private Attributes
static double Default_alpha_parameter = 1.0
Static default value for the Alpha parameter: (thermal inertia): One for natural scaling.
static double Default_beta_parameter = 1.0
Static default value for the Beta parameter (thermal conductivity): One for natural scaling.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::UnsteadyHeatEquations< DIM >
A class for all isoparametric elements that solve the UnsteadyHeat equations.
 \frac{\partial^2 u}{\partial x_i^2}=\frac{\partial u}{\partial t}+f(t,x_j) 
 This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class. Note that this class assumes an isoparametric formulation, i.e. that the scalar unknown is interpolated using the same shape funcitons as the position.
Definition at line 73 of file unsteady_heat_elements.h.
Member Typedef Documentation
UnsteadyHeatSourceFctPt
template<unsigned DIM>
typedef void(* oomph::UnsteadyHeatEquations< DIM >::UnsteadyHeatSourceFctPt) (const double &time, const Vector< double > &x, double &u)
Function pointer to source function fct(t,x,f(x,t)) -- x is a Vector!
Definition at line 78 of file unsteady_heat_elements.h.
Constructor & Destructor Documentation
UnsteadyHeatEquations() [1/2]
template<unsigned DIM>
oomph::UnsteadyHeatEquations< DIM >::UnsteadyHeatEquations () [inline]
Constructor: Initialises the Source_fct_pt to null and sets flag to use ALE formulation of the equations. Also set Alpha (thermal inertia) and Beta (thermal conductivity) parameters to defaults (both one for natural scaling)
Definition at line 87 of file unsteady_heat_elements.h.
References oomph::UnsteadyHeatEquations< DIM >::Alpha_pt, oomph::UnsteadyHeatEquations< DIM >::Beta_pt, oomph::UnsteadyHeatEquations< DIM >::Default_alpha_parameter, and oomph::UnsteadyHeatEquations< DIM >::Default_beta_parameter.
UnsteadyHeatEquations() [2/2]
template<unsigned DIM>
oomph::UnsteadyHeatEquations< DIM >::UnsteadyHeatEquations (const UnsteadyHeatEquations< DIM > & dummy) [inline]
Broken copy constructor.
Definition at line 97 of file unsteady_heat_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
alpha()
template<unsigned DIM>
const double& oomph::UnsteadyHeatEquations< DIM >::alpha () const [inline]
Alpha parameter (thermal inertia)
Definition at line 263 of file unsteady_heat_elements.h.
References oomph::UnsteadyHeatEquations< DIM >::Alpha_pt.
alpha_pt()
template<unsigned DIM>
double*& oomph::UnsteadyHeatEquations< DIM >::alpha_pt () [inline]
Pointer to Alpha parameter (thermal inertia)
Definition at line 269 of file unsteady_heat_elements.h.
References oomph::UnsteadyHeatEquations< DIM >::Alpha_pt.
beta()
template<unsigned DIM>
const double& oomph::UnsteadyHeatEquations< DIM >::beta () const [inline]
Beta parameter (thermal conductivity)
Definition at line 276 of file unsteady_heat_elements.h.
References oomph::UnsteadyHeatEquations< DIM >::Beta_pt.
beta_pt()
template<unsigned DIM>
double*& oomph::UnsteadyHeatEquations< DIM >::beta_pt () [inline]
Pointer to Beta parameter (thermal conductivity)
Definition at line 282 of file unsteady_heat_elements.h.
References oomph::UnsteadyHeatEquations< DIM >::Beta_pt.
compute_error() [1/2]
template<unsigned DIM>
void oomph::UnsteadyHeatEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 472 of file unsteady_heat_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
compute_error() [2/2]
template<unsigned DIM>
void oomph::UnsteadyHeatEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution at time t.
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 551 of file unsteady_heat_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
compute_norm()
template<unsigned DIM>
void oomph::UnsteadyHeatEquations< DIM >::compute_norm (double & norm) [virtual]
Compute norm of fe solution.
Reimplemented from oomph::GeneralisedElement.
Definition at line 215 of file unsteady_heat_elements.cc.
References i, s, u(), and oomph::QuadTreeNames::W.
disable_ALE()
template<unsigned DIM>
void oomph::UnsteadyHeatEquations< DIM >::disable_ALE () [inline], [virtual]
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
Reimplemented from oomph::FiniteElement.
Definition at line 156 of file unsteady_heat_elements.h.
References oomph::UnsteadyHeatEquations< DIM >::ALE_is_disabled.
dshape_and_dtest_eulerian_at_knot_ust_heat()
template<unsigned DIM>
virtual double oomph::UnsteadyHeatEquations< DIM >::dshape_and_dtest_eulerian_at_knot_ust_heat (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::QUnsteadyHeatElement< DIM, NNODE_1D >, and oomph::TUnsteadyHeatElement< DIM, NNODE_1D >.
dshape_and_dtest_eulerian_ust_heat()
template<unsigned DIM>
virtual double oomph::UnsteadyHeatEquations< DIM >::dshape_and_dtest_eulerian_ust_heat (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in oomph::QUnsteadyHeatElement< DIM, NNODE_1D >, and oomph::TUnsteadyHeatElement< DIM, NNODE_1D >.
du_dt_ust_heat()
template<unsigned DIM>
double oomph::UnsteadyHeatEquations< DIM >::du_dt_ust_heat (const unsigned & n) const [inline]
du/dt at local node n. Uses suitably interpolated value for hanging nodes.
Definition at line 127 of file unsteady_heat_elements.h.
References oomph::TimeStepper::is_steady(), n, oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), oomph::UnsteadyHeatEquations< DIM >::u_index_ust_heat(), and oomph::TimeStepper::weight().
Referenced by oomph::UnsteadyHeatEquations< DIM >::interpolated_du_dt_ust_heat().
enable_ALE()
template<unsigned DIM>
void oomph::UnsteadyHeatEquations< DIM >::enable_ALE () [inline], [virtual]
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
Reimplemented from oomph::FiniteElement.
Definition at line 166 of file unsteady_heat_elements.h.
References oomph::UnsteadyHeatEquations< DIM >::ALE_is_disabled.
fill_in_contribution_to_jacobian()
template<unsigned DIM>
void oomph::UnsteadyHeatEquations< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute element residual Vector and element Jacobian matrix (wrapper)
Reimplemented from oomph::FiniteElement.
Definition at line 332 of file unsteady_heat_elements.h.
References oomph::UnsteadyHeatEquations< DIM >::fill_in_generic_residual_contribution_ust_heat(), and residuals().
fill_in_contribution_to_residuals()
template<unsigned DIM>
void oomph::UnsteadyHeatEquations< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Compute element residual Vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 322 of file unsteady_heat_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, oomph::UnsteadyHeatEquations< DIM >::fill_in_generic_residual_contribution_ust_heat(), and residuals().
fill_in_generic_residual_contribution_ust_heat()
template<unsigned DIM>
void oomph::UnsteadyHeatEquations< DIM >::fill_in_generic_residual_contribution_ust_heat (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [protected], [virtual]
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Compute element residual Vector and/or element Jacobian matrix
flag=1: compute both flag=0: compute only residual Vector
Pure version without hanging nodes
Reimplemented in oomph::RefineableUnsteadyHeatEquations< DIM >.
Definition at line 60 of file unsteady_heat_elements.cc.
References oomph::ALE_is_disabled, i, interpolated_u(), residuals(), s, and oomph::QuadTreeNames::W.
Referenced by oomph::UnsteadyHeatEquations< DIM >::fill_in_contribution_to_jacobian(), and oomph::UnsteadyHeatEquations< DIM >::fill_in_contribution_to_residuals().
get_flux()
template<unsigned DIM>
void oomph::UnsteadyHeatEquations< DIM >::get_flux (const Vector< double > & s, Vector< double > & flux) const [inline]
Get flux: flux[i] = du/dx_i.
Definition at line 288 of file unsteady_heat_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, and oomph::UnsteadyHeatEquations< DIM >::u_index_ust_heat().
Referenced by oomph::RefineableUnsteadyHeatEquations< DIM >::get_Z2_flux(), and oomph::TUnsteadyHeatElement< DIM, NNODE_1D >::get_Z2_flux().
get_source_ust_heat()
template<unsigned DIM>
virtual void oomph::UnsteadyHeatEquations< DIM >::get_source_ust_heat (const double & t, const unsigned & ipt, const Vector< double > & x, double & source) const [inline], [virtual]
Get source term at continous time t and (Eulerian) position x. Virtual so it can be overloaded in derived multiphysics elements.
Definition at line 245 of file unsteady_heat_elements.h.
References oomph::UnsteadyHeatEquations< DIM >::Source_fct_pt, and t.
interpolated_du_dt_ust_heat()
template<unsigned DIM>
double oomph::UnsteadyHeatEquations< DIM >::interpolated_du_dt_ust_heat (const Vector< double > & s) const [inline]
Return FE representation of function value du/dt(s) at local coordinate s
Definition at line 400 of file unsteady_heat_elements.h.
References oomph::UnsteadyHeatEquations< DIM >::du_dt_ust_heat(), oomph::FiniteElement::nnode(), s, and oomph::FiniteElement::shape().
interpolated_u_ust_heat() [1/2]
template<unsigned DIM>
double oomph::UnsteadyHeatEquations< DIM >::interpolated_u_ust_heat (const unsigned & t, const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s at previous time t (t=0: present)
Definition at line 370 of file unsteady_heat_elements.h.
References interpolated_u(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), t, and oomph::UnsteadyHeatEquations< DIM >::u_index_ust_heat().
interpolated_u_ust_heat() [2/2]
template<unsigned DIM>
double oomph::UnsteadyHeatEquations< DIM >::interpolated_u_ust_heat (const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s.
Definition at line 341 of file unsteady_heat_elements.h.
References interpolated_u(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and oomph::UnsteadyHeatEquations< DIM >::u_index_ust_heat().
output() [1/4]
template<unsigned DIM>
void oomph::UnsteadyHeatEquations< DIM >::output (FILE * file_pt) [inline], [virtual]
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatElement< DIM, NNODE_1D >.
Definition at line 187 of file unsteady_heat_elements.h.
References oomph::UnsteadyHeatEquations< DIM >::output().
output() [2/4]
template<unsigned DIM>
void oomph::UnsteadyHeatEquations< DIM >::output (FILE * file_pt, const unsigned & nplot) [virtual]
C-style output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points.
C-style output function:
x,y,u or x,y,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatElement< DIM, NNODE_1D >.
Definition at line 330 of file unsteady_heat_elements.cc.
References i, and s.
output() [3/4]
template<unsigned DIM>
void oomph::UnsteadyHeatEquations< DIM >::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatElement< DIM, NNODE_1D >.
Definition at line 175 of file unsteady_heat_elements.h.
Referenced by oomph::TUnsteadyHeatElement< DIM, NNODE_1D >::output(), oomph::UnsteadyHeatEquations< DIM >::output(), and oomph::QUnsteadyHeatElement< DIM, NNODE_1D >::output().
output() [4/4]
template<unsigned DIM>
void oomph::UnsteadyHeatEquations< DIM >::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points.
Output function:
x,y,u or x,y,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatElement< DIM, NNODE_1D >.
Definition at line 294 of file unsteady_heat_elements.cc.
References i, and s.
output_fct() [1/2]
template<unsigned DIM>
void oomph::UnsteadyHeatEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points (time-dependent version)
Output exact solution at time t
Solution is provided via function pointer. Plot at a given number of plot points.
x,y,u_exact or x,y,z,u_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatElement< DIM, NNODE_1D >, and oomph::TUnsteadyHeatElement< DIM, NNODE_1D >.
Definition at line 418 of file unsteady_heat_elements.cc.
References i, and s.
output_fct() [2/2]
template<unsigned DIM>
void oomph::UnsteadyHeatEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points.
Output exact solution
Solution is provided via function pointer. Plot at a given number of plot points.
x,y,u_exact or x,y,z,u_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatElement< DIM, NNODE_1D >.
Definition at line 366 of file unsteady_heat_elements.cc.
References i, and s.
Referenced by oomph::TUnsteadyHeatElement< DIM, NNODE_1D >::output_fct(), and oomph::QUnsteadyHeatElement< DIM, NNODE_1D >::output_fct().
self_test()
template<unsigned DIM>
unsigned oomph::UnsteadyHeatEquations< DIM >::self_test [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
Definition at line 264 of file unsteady_heat_elements.cc.
References oomph::FiniteElement::self_test().
source_fct_pt() [1/2]
template<unsigned DIM>
UnsteadyHeatSourceFctPt& oomph::UnsteadyHeatEquations< DIM >::source_fct_pt () [inline], [virtual]
Access function: Pointer to source function.
Implements oomph::UnsteadyHeatEquationsBase.
Definition at line 230 of file unsteady_heat_elements.h.
References oomph::UnsteadyHeatEquations< DIM >::Source_fct_pt.
Referenced by oomph::RefineableUnsteadyHeatEquations< DIM >::further_build().
source_fct_pt() [2/2]
template<unsigned DIM>
UnsteadyHeatSourceFctPt oomph::UnsteadyHeatEquations< DIM >::source_fct_pt () const [inline]
Access function: Pointer to source function. Const version.
Definition at line 237 of file unsteady_heat_elements.h.
References oomph::UnsteadyHeatEquations< DIM >::Source_fct_pt.
u_index_ust_heat()
template<unsigned DIM>
virtual unsigned oomph::UnsteadyHeatEquations< DIM >::u_index_ust_heat () const [inline], [virtual]
Broken assignment operator.
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the unsteady heat equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
Definition at line 120 of file unsteady_heat_elements.h.
Referenced by oomph::UnsteadyHeatEquations< DIM >::du_dt_ust_heat(), oomph::UnsteadyHeatEquations< DIM >::get_flux(), oomph::RefineableUnsteadyHeatEquations< DIM >::get_interpolated_values(), oomph::UnsteadyHeatEquations< DIM >::interpolated_u_ust_heat(), and oomph::UnsteadyHeatFluxElement< ELEMENT >::UnsteadyHeatFluxElement().
Member Data Documentation
ALE_is_disabled
template<unsigned DIM>
bool oomph::UnsteadyHeatEquations< DIM >::ALE_is_disabled [protected]
Boolean flag to indicate if ALE formulation is disabled when time-derivatives are computed. Only set to true if you're sure that the mesh is stationary.
Definition at line 459 of file unsteady_heat_elements.h.
Referenced by oomph::UnsteadyHeatEquations< DIM >::disable_ALE(), oomph::UnsteadyHeatEquations< DIM >::enable_ALE(), and oomph::RefineableUnsteadyHeatEquations< DIM >::further_build().
Alpha_pt
template<unsigned DIM>
double* oomph::UnsteadyHeatEquations< DIM >::Alpha_pt [protected]
Pointer to Alpha parameter (thermal inertia)
Definition at line 462 of file unsteady_heat_elements.h.
Referenced by oomph::UnsteadyHeatEquations< DIM >::alpha(), oomph::UnsteadyHeatEquations< DIM >::alpha_pt(), and oomph::UnsteadyHeatEquations< DIM >::UnsteadyHeatEquations().
Beta_pt
template<unsigned DIM>
double* oomph::UnsteadyHeatEquations< DIM >::Beta_pt [protected]
Pointer to Beta parameter (thermal conductivity)
Definition at line 465 of file unsteady_heat_elements.h.
Referenced by oomph::UnsteadyHeatEquations< DIM >::beta(), oomph::UnsteadyHeatEquations< DIM >::beta_pt(), and oomph::UnsteadyHeatEquations< DIM >::UnsteadyHeatEquations().
Default_alpha_parameter
template<unsigned DIM>
double oomph::UnsteadyHeatEquations< DIM >::Default_alpha_parameter = 1.0 [static], [private]
Static default value for the Alpha parameter: (thermal inertia): One for natural scaling.
2D UnsteadyHeat elements
Default value for Alpha parameter (thermal inertia)
Definition at line 470 of file unsteady_heat_elements.h.
Referenced by oomph::UnsteadyHeatEquations< DIM >::UnsteadyHeatEquations().
Default_beta_parameter
template<unsigned DIM>
double oomph::UnsteadyHeatEquations< DIM >::Default_beta_parameter = 1.0 [static], [private]
Static default value for the Beta parameter (thermal conductivity): One for natural scaling.
Default value for Beta parameter (thermal conductivity)
Definition at line 474 of file unsteady_heat_elements.h.
Referenced by oomph::UnsteadyHeatEquations< DIM >::UnsteadyHeatEquations().
Source_fct_pt
template<unsigned DIM>
UnsteadyHeatSourceFctPt oomph::UnsteadyHeatEquations< DIM >::Source_fct_pt [protected]
Pointer to source function:
Definition at line 454 of file unsteady_heat_elements.h.
Referenced by oomph::RefineableUnsteadyHeatEquations< DIM >::further_build(), oomph::UnsteadyHeatEquations< DIM >::get_source_ust_heat(), and oomph::UnsteadyHeatEquations< DIM >::source_fct_pt().
The documentation for this class was generated from the following files:
unsteady_heat_elements.h
unsteady_heat_elements.cc