oomph::GeneralisedAxisymAdvectionDiffusionEquations Class Reference
#include <gen_axisym_advection_diffusion_elements.h>
Public Member Functions
Function pointer to source function fct (x, f(x)) -- x is a Vector! typedef void(*GeneralisedAxisymAdvectionDiffusionSourceFctPt)(const Vector< double > &x
Function pointer to wind function fct (x, w(x)) -- x is a Vector! typedef void(*GeneralisedAxisymAdvectionDiffusionWindFctPt)(const Vector< double > &x
Constructor Wind_fct_pt (0)
Constructor Conserved_wind_fct_pt (0)
Constructor Diff_fct_pt (0)
Constructor ALE_is_disabled (false)
Broken copy constructor GeneralisedAxisymAdvectionDiffusionEquations (const GeneralisedAxisymAdvectionDiffusionEquations &dummy)=delete
Broken assignment operator virtual inline unsigned u_index_cons_axisym_adv_diff () const
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the advection-diffusion equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
double du_dt_cons_axisym_adv_diff (const unsigned &n) const
du/dt at local node n. Uses suitably interpolated value for hanging nodes.
void disable_ALE ()
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
void enable_ALE ()
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &nplot)
Output FE representation of soln: r,z,u at nplot^2 plot points.
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output FE representation of soln: r,z,u at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: r,z,u_exact at nplot^2 plot points.
virtual void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: r,z,,u_exact at nplot^2 plot points (dummy time-dependent version to keep intel compiler happy)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
double integrate_u ()
Integrate the concentration over the element.
GeneralisedAxisymAdvectionDiffusionSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
GeneralisedAxisymAdvectionDiffusionSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
GeneralisedAxisymAdvectionDiffusionWindFctPt & wind_fct_pt ()
Access function: Pointer to wind function.
GeneralisedAxisymAdvectionDiffusionWindFctPt wind_fct_pt () const
Access function: Pointer to wind function. Const version.
GeneralisedAxisymAdvectionDiffusionWindFctPt & conserved_wind_fct_pt ()
Access function: Pointer to additional (conservative) wind function.
GeneralisedAxisymAdvectionDiffusionWindFctPt conserved_wind_fct_pt () const
Access function: Pointer to additional (conservative) wind function. Const version.
GeneralisedAxisymAdvectionDiffusionDiffFctPt & diff_fct_pt ()
Access function: Pointer to diffusion function.
GeneralisedAxisymAdvectionDiffusionDiffFctPt diff_fct_pt () const
Access function: Pointer to diffusion function. Const version.
const double & pe () const
Peclet number.
double *& pe_pt ()
Pointer to Peclet number.
const double & pe_st () const
Peclet number multiplied by Strouhal number.
double *& pe_st_pt ()
Pointer to Peclet number multipled by Strouha number.
virtual void get_source_cons_axisym_adv_diff (const unsigned &ipt, const Vector< double > &x, double &source) const
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
virtual void get_wind_cons_axisym_adv_diff (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
Get wind at (Eulerian) position x and/or local coordinate s. This function is virtual to allow overloading in multi-physics problems where the wind function might be determined by another system of equations.
virtual void get_conserved_wind_cons_axisym_adv_diff (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
Get additional (conservative) wind at (Eulerian) position x and/or local coordinate s. This function is virtual to allow overloading in multi-physics problems where the wind function might be determined by another system of equations.
virtual void get_diff_cons_axisym_adv_diff (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &D) const
Get diffusivity tensor at (Eulerian) position x and/or local coordinate s. This function is virtual to allow overloading in multi-physics problems where the wind function might be determined by another system of equations.
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: $\mbox{flux}[i] = \mbox{d}u / \mbox{d}x_i $.
void get_total_flux (const Vector< double > &s, Vector< double > &total_flux) const
Get flux: $\mbox{flux}[i] = \mbox{d}u / \mbox{d}x_i $.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and the element Jacobian matrix (wrapper)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
double interpolated_u_cons_axisym_adv_diff (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
unsigned self_test ()
Self-test: Return 0 for OK.
Public Attributes
Function pointer to a diffusivity function typedef void(* GeneralisedAxisymAdvectionDiffusionDiffFctPt)(const Vector< double > &x, DenseMatrix< double > &D)
Function pointer to source function double & f
Function pointer to wind function Vector< double > & wind
Constructor __pad0__: Initialise the Source_fct_pt and Wind_fct_pt to null and set (pointer to) Peclet number to default GeneralisedAxisymAdvectionDiffusionEquations() : Source_fct_pt(0)
Protected Member Functions
virtual double dshape_and_dtest_eulerian_cons_axisym_adv_diff (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_cons_axisym_adv_diff (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
virtual void fill_in_generic_residual_contribution_cons_axisym_adv_diff (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Add the element's contribution to its residual vector only (if flag=and/or element Jacobian matrix.
Protected Attributes
double * Pe_pt
Pointer to global Peclet number.
double * PeSt_pt
Pointer to global Peclet number multiplied by Strouhal number.
GeneralisedAxisymAdvectionDiffusionSourceFctPt Source_fct_pt
Pointer to source function:
GeneralisedAxisymAdvectionDiffusionWindFctPt Wind_fct_pt
Pointer to wind function:
GeneralisedAxisymAdvectionDiffusionWindFctPt Conserved_wind_fct_pt
Pointer to additional (conservative) wind function:
GeneralisedAxisymAdvectionDiffusionDiffFctPt Diff_fct_pt
Pointer to diffusivity funciton.
bool ALE_is_disabled
Boolean flag to indicate if ALE formulation is disabled when time-derivatives are computed. Only set to false if you're sure that the mesh is stationary.
Static Private Attributes
static double Default_peclet_number
Static default value for the Peclet number.
Additional Inherited Members
Detailed Description
Definition at line 56 of file gen_axisym_advection_diffusion_elements.h.
Constructor & Destructor Documentation
GeneralisedAxisymAdvectionDiffusionEquations()
Broken copy constructor oomph::GeneralisedAxisymAdvectionDiffusionEquations::GeneralisedAxisymAdvectionDiffusionEquations (const GeneralisedAxisymAdvectionDiffusionEquations & dummy) [delete]
Member Function Documentation
ALE_is_disabled()
Constructor oomph::GeneralisedAxisymAdvectionDiffusionEquations::ALE_is_disabled (false) [inline]
Definition at line 82 of file gen_axisym_advection_diffusion_elements.h.
References Default_peclet_number, Pe_pt, and PeSt_pt.
compute_error() [1/2]
void oomph::GeneralisedAxisymAdvectionDiffusionEquations::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution.
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 447 of file gen_axisym_advection_diffusion_elements.cc.
References i, oomph::FiniteElement::integral_pt(), interpolated_u_cons_axisym_adv_diff(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
compute_error() [2/2]
void oomph::GeneralisedAxisymAdvectionDiffusionEquations::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [inline], [virtual]
Dummy, time dependent error checker.
Reimplemented from oomph::FiniteElement.
Definition at line 212 of file gen_axisym_advection_diffusion_elements.h.
conserved_wind_fct_pt() [1/2]
GeneralisedAxisymAdvectionDiffusionWindFctPt& oomph::GeneralisedAxisymAdvectionDiffusionEquations::conserved_wind_fct_pt () [inline]
Access function: Pointer to additional (conservative) wind function.
Definition at line 257 of file gen_axisym_advection_diffusion_elements.h.
References Conserved_wind_fct_pt.
Referenced by oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::further_build().
conserved_wind_fct_pt() [2/2]
GeneralisedAxisymAdvectionDiffusionWindFctPt oomph::GeneralisedAxisymAdvectionDiffusionEquations::conserved_wind_fct_pt () const [inline]
Access function: Pointer to additional (conservative) wind function. Const version.
Definition at line 266 of file gen_axisym_advection_diffusion_elements.h.
References Conserved_wind_fct_pt.
Conserved_wind_fct_pt()
Constructor oomph::GeneralisedAxisymAdvectionDiffusionEquations::Conserved_wind_fct_pt (0)
diff_fct_pt() [1/2]
GeneralisedAxisymAdvectionDiffusionDiffFctPt& oomph::GeneralisedAxisymAdvectionDiffusionEquations::diff_fct_pt () [inline]
Access function: Pointer to diffusion function.
Definition at line 272 of file gen_axisym_advection_diffusion_elements.h.
References Diff_fct_pt.
Referenced by oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::further_build().
diff_fct_pt() [2/2]
GeneralisedAxisymAdvectionDiffusionDiffFctPt oomph::GeneralisedAxisymAdvectionDiffusionEquations::diff_fct_pt () const [inline]
Access function: Pointer to diffusion function. Const version.
Definition at line 278 of file gen_axisym_advection_diffusion_elements.h.
References Diff_fct_pt.
Diff_fct_pt()
Constructor oomph::GeneralisedAxisymAdvectionDiffusionEquations::Diff_fct_pt (0)
disable_ALE()
void oomph::GeneralisedAxisymAdvectionDiffusionEquations::disable_ALE () [inline], [virtual]
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
Reimplemented from oomph::FiniteElement.
Definition at line 144 of file gen_axisym_advection_diffusion_elements.h.
References ALE_is_disabled.
dshape_and_dtest_eulerian_at_knot_cons_axisym_adv_diff()
virtual double oomph::GeneralisedAxisymAdvectionDiffusionEquations::dshape_and_dtest_eulerian_at_knot_cons_axisym_adv_diff (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >.
Referenced by fill_in_generic_residual_contribution_cons_axisym_adv_diff(), and oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff().
dshape_and_dtest_eulerian_cons_axisym_adv_diff()
virtual double oomph::GeneralisedAxisymAdvectionDiffusionEquations::dshape_and_dtest_eulerian_cons_axisym_adv_diff (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >.
du_dt_cons_axisym_adv_diff()
double oomph::GeneralisedAxisymAdvectionDiffusionEquations::du_dt_cons_axisym_adv_diff (const unsigned & n) const [inline]
du/dt at local node n. Uses suitably interpolated value for hanging nodes.
Definition at line 117 of file gen_axisym_advection_diffusion_elements.h.
References oomph::TimeStepper::is_steady(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), and oomph::TimeStepper::weight().
Referenced by fill_in_generic_residual_contribution_cons_axisym_adv_diff(), and oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff().
enable_ALE()
void oomph::GeneralisedAxisymAdvectionDiffusionEquations::enable_ALE () [inline], [virtual]
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
Reimplemented from oomph::FiniteElement.
Definition at line 154 of file gen_axisym_advection_diffusion_elements.h.
References ALE_is_disabled.
fct() [1/2]
Function pointer to source function oomph::GeneralisedAxisymAdvectionDiffusionEquations::fct (x , f(x)) const &
fct() [2/2]
Function pointer to wind function oomph::GeneralisedAxisymAdvectionDiffusionEquations::fct (x , w(x)) const &
fill_in_contribution_to_jacobian()
void oomph::GeneralisedAxisymAdvectionDiffusionEquations::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and the element Jacobian matrix (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 536 of file gen_axisym_advection_diffusion_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_cons_axisym_adv_diff().
fill_in_contribution_to_jacobian_and_mass_matrix()
void oomph::GeneralisedAxisymAdvectionDiffusionEquations::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline], [virtual]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Reimplemented from oomph::GeneralisedElement.
Definition at line 547 of file gen_axisym_advection_diffusion_elements.h.
References fill_in_generic_residual_contribution_cons_axisym_adv_diff().
fill_in_contribution_to_residuals()
void oomph::GeneralisedAxisymAdvectionDiffusionEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 522 of file gen_axisym_advection_diffusion_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_cons_axisym_adv_diff().
fill_in_generic_residual_contribution_cons_axisym_adv_diff()
void oomph::GeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [protected], [virtual]
Add the element's contribution to its residual vector only (if flag=and/or element Jacobian matrix.
Compute element residual Vector and/or element Jacobian matrix.
flag=1: compute both flag=0: compute only residual Vector
Pure version without hanging nodes
Reimplemented in oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations.
Definition at line 46 of file gen_axisym_advection_diffusion_elements.cc.
References ALE_is_disabled, oomph::OcTreeNames::D, dshape_and_dtest_eulerian_at_knot_cons_axisym_adv_diff(), du_dt_cons_axisym_adv_diff(), get_conserved_wind_cons_axisym_adv_diff(), get_diff_cons_axisym_adv_diff(), get_source_cons_axisym_adv_diff(), get_wind_cons_axisym_adv_diff(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), pe(), pe_st(), oomph::FiniteElement::raw_dnodal_position_dt(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), s, oomph::Data::time_stepper_pt(), oomph::QuadTreeNames::W, oomph::Integral::weight(), oomph::TimeStepper::weight(), and wind.
Referenced by fill_in_contribution_to_jacobian(), fill_in_contribution_to_jacobian_and_mass_matrix(), and fill_in_contribution_to_residuals().
get_conserved_wind_cons_axisym_adv_diff()
virtual void oomph::GeneralisedAxisymAdvectionDiffusionEquations::get_conserved_wind_cons_axisym_adv_diff (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const [inline], [virtual]
Get additional (conservative) wind at (Eulerian) position x and/or local coordinate s. This function is virtual to allow overloading in multi-physics problems where the wind function might be determined by another system of equations.
Definition at line 361 of file gen_axisym_advection_diffusion_elements.h.
References Conserved_wind_fct_pt, i, and wind.
Referenced by fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), and get_total_flux().
get_diff_cons_axisym_adv_diff()
virtual void oomph::GeneralisedAxisymAdvectionDiffusionEquations::get_diff_cons_axisym_adv_diff (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, DenseMatrix< double > & D) const [inline], [virtual]
Get diffusivity tensor at (Eulerian) position x and/or local coordinate s. This function is virtual to allow overloading in multi-physics problems where the wind function might be determined by another system of equations.
Definition at line 389 of file gen_axisym_advection_diffusion_elements.h.
References oomph::OcTreeNames::D, Diff_fct_pt, and i.
Referenced by fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), and get_total_flux().
get_flux()
void oomph::GeneralisedAxisymAdvectionDiffusionEquations::get_flux (const Vector< double > & s, Vector< double > & flux) const [inline]
Get flux: $\mbox{flux}[i] = \mbox{d}u / \mbox{d}x_i $.
Definition at line 424 of file gen_axisym_advection_diffusion_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), and s.
Referenced by oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::get_Z2_flux().
get_source_cons_axisym_adv_diff()
virtual void oomph::GeneralisedAxisymAdvectionDiffusionEquations::get_source_cons_axisym_adv_diff (const unsigned & ipt, const Vector< double > & x, double & source) const [inline], [virtual]
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
Definition at line 311 of file gen_axisym_advection_diffusion_elements.h.
References Source_fct_pt.
Referenced by fill_in_generic_residual_contribution_cons_axisym_adv_diff(), and oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff().
get_total_flux()
void oomph::GeneralisedAxisymAdvectionDiffusionEquations::get_total_flux (const Vector< double > & s, Vector< double > & total_flux) const [inline]
Get flux: $\mbox{flux}[i] = \mbox{d}u / \mbox{d}x_i $.
Definition at line 456 of file gen_axisym_advection_diffusion_elements.h.
References oomph::OcTreeNames::D, oomph::FiniteElement::dshape_eulerian(), get_conserved_wind_cons_axisym_adv_diff(), get_diff_cons_axisym_adv_diff(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), and s.
get_wind_cons_axisym_adv_diff()
virtual void oomph::GeneralisedAxisymAdvectionDiffusionEquations::get_wind_cons_axisym_adv_diff (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const [inline], [virtual]
Get wind at (Eulerian) position x and/or local coordinate s. This function is virtual to allow overloading in multi-physics problems where the wind function might be determined by another system of equations.
Definition at line 332 of file gen_axisym_advection_diffusion_elements.h.
References i, wind, and Wind_fct_pt.
Referenced by fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), and output().
integrate_u()
double oomph::GeneralisedAxisymAdvectionDiffusionEquations::integrate_u ()
Integrate the concentration over the element.
Calculate the integrated value of the unknown over the element.
Definition at line 521 of file gen_axisym_advection_diffusion_elements.cc.
References oomph::FiniteElement::integral_pt(), oomph::FiniteElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::Integral::nweight(), oomph::FiniteElement::shape_at_knot(), and oomph::Integral::weight().
interpolated_u_cons_axisym_adv_diff()
double oomph::GeneralisedAxisymAdvectionDiffusionEquations::interpolated_u_cons_axisym_adv_diff (const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s.
Definition at line 559 of file gen_axisym_advection_diffusion_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, and oomph::FiniteElement::shape().
Referenced by compute_error(), and output().
operator virtual inline unsigned u_index_cons_axisym_adv_diff()
Broken assignment oomph::GeneralisedAxisymAdvectionDiffusionEquations::operator virtual inline unsigned u_index_cons_axisym_adv_diff () const [inline]
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the advection-diffusion equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
Definition at line 94 of file gen_axisym_advection_diffusion_elements.h.
output() [1/4]
void oomph::GeneralisedAxisymAdvectionDiffusionEquations::output (FILE * file_pt) [inline], [virtual]
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >.
Definition at line 172 of file gen_axisym_advection_diffusion_elements.h.
References output().
output() [2/4]
void oomph::GeneralisedAxisymAdvectionDiffusionEquations::output (FILE * file_pt, const unsigned & nplot) [virtual]
C-style output FE representation of soln: r,z,u at n_plot^2 plot points.
C-style output function:
r,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >.
Definition at line 361 of file gen_axisym_advection_diffusion_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, interpolated_u_cons_axisym_adv_diff(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [3/4]
void oomph::GeneralisedAxisymAdvectionDiffusionEquations::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >.
Definition at line 161 of file gen_axisym_advection_diffusion_elements.h.
Referenced by output(), and oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output().
output() [4/4]
void oomph::GeneralisedAxisymAdvectionDiffusionEquations::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: r,z,u at nplot^2 plot points.
Output function:
r,z,u,w_r,w_z
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >.
Definition at line 290 of file gen_axisym_advection_diffusion_elements.cc.
References oomph::FiniteElement::get_s_plot(), get_wind_cons_axisym_adv_diff(), i, interpolated_u_cons_axisym_adv_diff(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), wind, and oomph::FiniteElement::write_tecplot_zone_footer().
output_fct() [1/2]
virtual void oomph::GeneralisedAxisymAdvectionDiffusionEquations::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output exact soln: r,z,,u_exact at nplot^2 plot points (dummy time-dependent version to keep intel compiler happy)
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >.
Definition at line 191 of file gen_axisym_advection_diffusion_elements.h.
output_fct() [2/2]
void oomph::GeneralisedAxisymAdvectionDiffusionEquations::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: r,z,u_exact at nplot^2 plot points.
Output exact solution.
Solution is provided via function pointer. Plot at a given number of plot points.
r,z,,u_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >.
Definition at line 397 of file gen_axisym_advection_diffusion_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
Referenced by oomph::QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output_fct().
pe()
const double& oomph::GeneralisedAxisymAdvectionDiffusionEquations::pe () const [inline]
Peclet number.
Definition at line 284 of file gen_axisym_advection_diffusion_elements.h.
References Pe_pt.
Referenced by fill_in_generic_residual_contribution_cons_axisym_adv_diff(), and oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff().
pe_pt()
double*& oomph::GeneralisedAxisymAdvectionDiffusionEquations::pe_pt () [inline]
Pointer to Peclet number.
Definition at line 290 of file gen_axisym_advection_diffusion_elements.h.
References Pe_pt.
Referenced by oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::further_build().
pe_st()
const double& oomph::GeneralisedAxisymAdvectionDiffusionEquations::pe_st () const [inline]
Peclet number multiplied by Strouhal number.
Definition at line 296 of file gen_axisym_advection_diffusion_elements.h.
References PeSt_pt.
Referenced by fill_in_generic_residual_contribution_cons_axisym_adv_diff(), and oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff().
pe_st_pt()
double*& oomph::GeneralisedAxisymAdvectionDiffusionEquations::pe_st_pt () [inline]
Pointer to Peclet number multipled by Strouha number.
Definition at line 302 of file gen_axisym_advection_diffusion_elements.h.
References PeSt_pt.
Referenced by oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::further_build().
self_test()
unsigned oomph::GeneralisedAxisymAdvectionDiffusionEquations::self_test () [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
Definition at line 261 of file gen_axisym_advection_diffusion_elements.cc.
References oomph::FiniteElement::self_test().
source_fct_pt() [1/2]
GeneralisedAxisymAdvectionDiffusionSourceFctPt& oomph::GeneralisedAxisymAdvectionDiffusionEquations::source_fct_pt () [inline]
Access function: Pointer to source function.
Definition at line 229 of file gen_axisym_advection_diffusion_elements.h.
References Source_fct_pt.
Referenced by oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::further_build().
source_fct_pt() [2/2]
GeneralisedAxisymAdvectionDiffusionSourceFctPt oomph::GeneralisedAxisymAdvectionDiffusionEquations::source_fct_pt () const [inline]
Access function: Pointer to source function. Const version.
Definition at line 236 of file gen_axisym_advection_diffusion_elements.h.
References Source_fct_pt.
wind_fct_pt() [1/2]
GeneralisedAxisymAdvectionDiffusionWindFctPt& oomph::GeneralisedAxisymAdvectionDiffusionEquations::wind_fct_pt () [inline]
Access function: Pointer to wind function.
Definition at line 243 of file gen_axisym_advection_diffusion_elements.h.
References Wind_fct_pt.
Referenced by oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::further_build().
wind_fct_pt() [2/2]
GeneralisedAxisymAdvectionDiffusionWindFctPt oomph::GeneralisedAxisymAdvectionDiffusionEquations::wind_fct_pt () const [inline]
Access function: Pointer to wind function. Const version.
Definition at line 250 of file gen_axisym_advection_diffusion_elements.h.
References Wind_fct_pt.
Wind_fct_pt()
Constructor oomph::GeneralisedAxisymAdvectionDiffusionEquations::Wind_fct_pt (0)
Member Data Documentation
__pad0__
Constructor oomph::GeneralisedAxisymAdvectionDiffusionEquations::__pad0__
Definition at line 75 of file gen_axisym_advection_diffusion_elements.h.
ALE_is_disabled
bool oomph::GeneralisedAxisymAdvectionDiffusionEquations::ALE_is_disabled [protected]
Boolean flag to indicate if ALE formulation is disabled when time-derivatives are computed. Only set to false if you're sure that the mesh is stationary.
Definition at line 638 of file gen_axisym_advection_diffusion_elements.h.
Referenced by disable_ALE(), enable_ALE(), fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), and oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::further_build().
Conserved_wind_fct_pt
GeneralisedAxisymAdvectionDiffusionWindFctPt oomph::GeneralisedAxisymAdvectionDiffusionEquations::Conserved_wind_fct_pt [protected]
Pointer to additional (conservative) wind function:
Definition at line 630 of file gen_axisym_advection_diffusion_elements.h.
Referenced by conserved_wind_fct_pt(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::further_build(), and get_conserved_wind_cons_axisym_adv_diff().
Default_peclet_number
double oomph::GeneralisedAxisymAdvectionDiffusionEquations::Default_peclet_number [static], [private]
Initial value:
=
    0.0
Static default value for the Peclet number.
2D GeneralisedAdvection Diffusion elements
Default value for Peclet number
Definition at line 642 of file gen_axisym_advection_diffusion_elements.h.
Referenced by ALE_is_disabled().
Diff_fct_pt
GeneralisedAxisymAdvectionDiffusionDiffFctPt oomph::GeneralisedAxisymAdvectionDiffusionEquations::Diff_fct_pt [protected]
Pointer to diffusivity funciton.
Definition at line 633 of file gen_axisym_advection_diffusion_elements.h.
Referenced by diff_fct_pt(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::further_build(), and get_diff_cons_axisym_adv_diff().
f
Function pointer to source function double& oomph::GeneralisedAxisymAdvectionDiffusionEquations::f
Definition at line 63 of file gen_axisym_advection_diffusion_elements.h.
GeneralisedAxisymAdvectionDiffusionDiffFctPt
Function pointer to a diffusivity function typedef void(* oomph::GeneralisedAxisymAdvectionDiffusionEquations::GeneralisedAxisymAdvectionDiffusionDiffFctPt) (const Vector< double > &x, DenseMatrix< double > &D)
Definition at line 72 of file gen_axisym_advection_diffusion_elements.h.
Pe_pt
double* oomph::GeneralisedAxisymAdvectionDiffusionEquations::Pe_pt [protected]
Pointer to global Peclet number.
Definition at line 618 of file gen_axisym_advection_diffusion_elements.h.
Referenced by ALE_is_disabled(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::further_build(), pe(), and pe_pt().
PeSt_pt
double* oomph::GeneralisedAxisymAdvectionDiffusionEquations::PeSt_pt [protected]
Pointer to global Peclet number multiplied by Strouhal number.
Definition at line 621 of file gen_axisym_advection_diffusion_elements.h.
Referenced by ALE_is_disabled(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::further_build(), pe_st(), and pe_st_pt().
Source_fct_pt
GeneralisedAxisymAdvectionDiffusionSourceFctPt oomph::GeneralisedAxisymAdvectionDiffusionEquations::Source_fct_pt [protected]
Pointer to source function:
Definition at line 624 of file gen_axisym_advection_diffusion_elements.h.
Referenced by oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::further_build(), get_source_cons_axisym_adv_diff(), and source_fct_pt().
wind
Function pointer to wind function Vector<double>& oomph::GeneralisedAxisymAdvectionDiffusionEquations::wind
Definition at line 68 of file gen_axisym_advection_diffusion_elements.h.
Referenced by fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), get_conserved_wind_cons_axisym_adv_diff(), get_wind_cons_axisym_adv_diff(), and output().
Wind_fct_pt
GeneralisedAxisymAdvectionDiffusionWindFctPt oomph::GeneralisedAxisymAdvectionDiffusionEquations::Wind_fct_pt [protected]
Pointer to wind function:
Definition at line 627 of file gen_axisym_advection_diffusion_elements.h.
Referenced by oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::further_build(), get_wind_cons_axisym_adv_diff(), and wind_fct_pt().
The documentation for this class was generated from the following files:
gen_axisym_advection_diffusion_elements.h
gen_axisym_advection_diffusion_elements.cc