oomph::QYoungLaplaceElement< NNODE_1D > Class Template Reference
#include <young_laplace_elements.h>
Public Member Functions
QYoungLaplaceElement ()
Constructor: Call constructors for QElement and YoungLaplace equations.
QYoungLaplaceElement (const QYoungLaplaceElement< NNODE_1D > &dummy)
Broken copy constructor.
void operator= (const QYoungLaplaceElement< NNODE_1D > &)
Broken assignment operator.
unsigned required_nvalue (const unsigned &n) const
Required # of `values' (pinned or dofs) at node n.
void output (std::ostream &outfile)
Output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solutio at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution at n_plot^2 plot points (calls the steady version)
Private Member Functions
const unsigned Initial_Nvalue [16]
const unsigned Initial_Nvalue [9]
const unsigned Initial_Nvalue [4]
Static Private Attributes
static const unsigned Initial_Nvalue []
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::QYoungLaplaceElement< NNODE_1D >
QYoungLaplaceElement elements are linear/quadrilateral/brick-shaped YoungLaplace elements with isoparametric interpolation for the function.
Definition at line 470 of file young_laplace_elements.h.
Constructor & Destructor Documentation
QYoungLaplaceElement() [1/2]
template<unsigned NNODE_1D>
oomph::QYoungLaplaceElement< NNODE_1D >::QYoungLaplaceElement () [inline]
Constructor: Call constructors for QElement and YoungLaplace equations.
Definition at line 481 of file young_laplace_elements.h.
QYoungLaplaceElement() [2/2]
template<unsigned NNODE_1D>
oomph::QYoungLaplaceElement< NNODE_1D >::QYoungLaplaceElement (const QYoungLaplaceElement< NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 484 of file young_laplace_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
Initial_Nvalue() [1/3]
const unsigned oomph::QYoungLaplaceElement< 4 >::Initial_Nvalue [private]
Definition at line 36 of file young_laplace_elements.cc.
Initial_Nvalue() [2/3]
const unsigned oomph::QYoungLaplaceElement< 2 >::Initial_Nvalue [private]
Definition at line 42 of file young_laplace_elements.cc.
Initial_Nvalue() [3/3]
const unsigned oomph::QYoungLaplaceElement< 3 >::Initial_Nvalue [private]
Definition at line 39 of file young_laplace_elements.cc.
operator=()
template<unsigned NNODE_1D>
void oomph::QYoungLaplaceElement< NNODE_1D >::operator= (const QYoungLaplaceElement< NNODE_1D > &) [inline]
Broken assignment operator.
Definition at line 490 of file young_laplace_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/2]
template<unsigned NNODE_1D>
void oomph::QYoungLaplaceElement< NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function.
Reimplemented from oomph::QElement< 2, NNODE_1D >.
Definition at line 504 of file young_laplace_elements.h.
References oomph::YoungLaplaceEquations::output().
output() [2/2]
template<unsigned NNODE_1D>
void oomph::QYoungLaplaceElement< NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function at n_plot^2 plot points.
Reimplemented from oomph::QElement< 2, NNODE_1D >.
Definition at line 511 of file young_laplace_elements.h.
References oomph::YoungLaplaceEquations::output().
output_fct() [1/2]
template<unsigned NNODE_1D>
void oomph::QYoungLaplaceElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution at n_plot^2 plot points (calls the steady version)
Reimplemented from oomph::YoungLaplaceEquations.
Definition at line 528 of file young_laplace_elements.h.
References oomph::YoungLaplaceEquations::output_fct().
output_fct() [2/2]
template<unsigned NNODE_1D>
void oomph::QYoungLaplaceElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solutio at n_plot^2 plot points.
Reimplemented from oomph::YoungLaplaceEquations.
Definition at line 518 of file young_laplace_elements.h.
References oomph::YoungLaplaceEquations::output_fct().
required_nvalue()
template<unsigned NNODE_1D>
unsigned oomph::QYoungLaplaceElement< NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Required # of `values' (pinned or dofs) at node n.
Reimplemented from oomph::FiniteElement.
Definition at line 498 of file young_laplace_elements.h.
References oomph::QYoungLaplaceElement< NNODE_1D >::Initial_Nvalue, and n.
Member Data Documentation
Initial_Nvalue
template<unsigned NNODE_1D>
const unsigned oomph::QYoungLaplaceElement< NNODE_1D >::Initial_Nvalue[] [static], [private]
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Definition at line 476 of file young_laplace_elements.h.
Referenced by oomph::QYoungLaplaceElement< NNODE_1D >::required_nvalue().
The documentation for this class was generated from the following file:
young_laplace_elements.h