oomph::RankFourTensor< T > Class Template Reference
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
#include <matrices.h>
Public Member Functions
RankFourTensor ()
Empty constructor.
RankFourTensor (const RankFourTensor &source_tensor)
Copy constructor: Deep copy.
RankFourTensor & operator= (const RankFourTensor &source_tensor)
Copy assignement.
RankFourTensor (const unsigned long &n)
One parameter constructor produces a nxnxnxn tensor.
RankFourTensor (const unsigned long &n_index1, const unsigned long &n_index2, const unsigned long &n_index3, const unsigned long &n_index4)
Four parameter constructor, general non-square tensor.
RankFourTensor (const unsigned long &n_index1, const unsigned long &n_index2, const unsigned long &n_index3, const unsigned long &n_index4, const T &initial_val)
Four parameter constructor, general non-square tensor.
virtual ~RankFourTensor ()
Destructor: delete the pointers.
void resize (const unsigned long &n)
Resize to a square nxnxnxn tensor.
void resize (const unsigned long &n_index1, const unsigned long &n_index2, const unsigned long &n_index3, const unsigned long &n_index4)
Resize to a general tensor.
void resize (const unsigned long &n_index1, const unsigned long &n_index2, const unsigned long &n_index3, const unsigned long &n_index4, const T &initial_value)
Resize to a general tensor.
void initialise (const T &val)
Initialise all values in the tensor to val.
unsigned long nindex1 () const
Return the range of index 1 of the tensor.
unsigned long nindex2 () const
Return the range of index 2 of the tensor.
unsigned long nindex3 () const
Return the range of index 3 of the tensor.
unsigned long nindex4 () const
Return the range of index 4 of the tensor.
T & operator() (const unsigned long &i, const unsigned long &j, const unsigned long &k, const unsigned long &l)
Overload the round brackets to give access as a(i,j,k,l)
T operator() (const unsigned long &i, const unsigned long &j, const unsigned long &k, const unsigned long &l) const
Overload a const version for read-only access as a(i,j,k,l)
T & raw_direct_access (const unsigned long &i)
Direct access to internal storage of data in flat-packed C-style column-major format. WARNING: Only for experienced users. Only use this if raw speed is of the essence, as in the solid mechanics problems.
const T & raw_direct_access (const unsigned long &i) const
Direct access to internal storage of data in flat-packed C-style column-major format. WARNING: Only for experienced users. Only use this if raw speed is of the essence, as in the solid mechanics problems.
unsigned offset (const unsigned long &i, const unsigned long &j) const
Caculate the offset in flat-packed C-style, column-major format, required for a given i,j. WARNING: Only for experienced users. Only use this if raw speed is of the essence, as in the solid mechanics problems.
Private Member Functions
void range_check (const unsigned long &i, const unsigned long &j, const unsigned long &k, const unsigned long &l) const
Range check to catch when an index is out of bounds, if so, it issues a warning message and dies by throwing an OomphLibError.
Private Attributes
T * Tensordata
Private internal representation as pointer to data.
unsigned N
1st Tensor dimension
unsigned M
2nd Tensor dimension
unsigned P
3rd Tensor dimension
unsigned Q
4th Tensor dimension
Detailed Description
template<class T>
class oomph::RankFourTensor< T >
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
A Rank 4 Tensor class
Definition at line 1700 of file matrices.h.
Constructor & Destructor Documentation
RankFourTensor() [1/5]
template<class T >
oomph::RankFourTensor< T >::RankFourTensor () [inline]
Empty constructor.
Definition at line 1769 of file matrices.h.
RankFourTensor() [2/5]
template<class T >
oomph::RankFourTensor< T >::RankFourTensor (const RankFourTensor< T > & source_tensor) [inline]
Copy constructor: Deep copy.
Definition at line 1772 of file matrices.h.
References i, oomph::RankFourTensor< T >::M, oomph::RankFourTensor< T >::N, oomph::RankFourTensor< T >::nindex1(), oomph::RankFourTensor< T >::nindex2(), oomph::RankFourTensor< T >::nindex3(), oomph::RankFourTensor< T >::nindex4(), oomph::RankFourTensor< T >::P, oomph::RankFourTensor< T >::Q, oomph::ElementGeometry::T, and oomph::RankFourTensor< T >::Tensordata.
RankFourTensor() [3/5]
template<class T >
oomph::RankFourTensor< T >::RankFourTensor (const unsigned long & n) [inline]
One parameter constructor produces a nxnxnxn tensor.
Definition at line 1838 of file matrices.h.
References oomph::RankFourTensor< T >::initialise(), oomph::RankFourTensor< T >::M, oomph::RankFourTensor< T >::N, oomph::RankFourTensor< T >::P, oomph::RankFourTensor< T >::Q, oomph::ElementGeometry::T, and oomph::RankFourTensor< T >::Tensordata.
RankFourTensor() [4/5]
template<class T >
oomph::RankFourTensor< T >::RankFourTensor (const unsigned long & n_index1, const unsigned long & n_index2, const unsigned long & n_index3, const unsigned long & n_index4) [inline]
Four parameter constructor, general non-square tensor.
Definition at line 1854 of file matrices.h.
References oomph::RankFourTensor< T >::initialise(), oomph::RankFourTensor< T >::M, oomph::RankFourTensor< T >::N, oomph::RankFourTensor< T >::P, oomph::RankFourTensor< T >::Q, oomph::ElementGeometry::T, and oomph::RankFourTensor< T >::Tensordata.
RankFourTensor() [5/5]
template<class T >
oomph::RankFourTensor< T >::RankFourTensor (const unsigned long & n_index1, const unsigned long & n_index2, const unsigned long & n_index3, const unsigned long & n_index4, const T & initial_val) [inline]
Four parameter constructor, general non-square tensor.
Definition at line 1874 of file matrices.h.
References oomph::RankFourTensor< T >::initialise(), oomph::RankFourTensor< T >::M, oomph::RankFourTensor< T >::N, oomph::RankFourTensor< T >::P, oomph::RankFourTensor< T >::Q, oomph::ElementGeometry::T, and oomph::RankFourTensor< T >::Tensordata.
 RankFourTensor()
template<class T >
virtual oomph::RankFourTensor< T >::~RankFourTensor () [inline], [virtual]
Destructor: delete the pointers.
Definition at line 1892 of file matrices.h.
References oomph::RankFourTensor< T >::Tensordata.
Member Function Documentation
initialise()
template<class T >
void oomph::RankFourTensor< T >::initialise (const T & val) [inline]
Initialise all values in the tensor to val.
Definition at line 2018 of file matrices.h.
References i, oomph::RankFourTensor< T >::M, oomph::RankFourTensor< T >::N, oomph::RankFourTensor< T >::P, oomph::RankFourTensor< T >::Q, and oomph::RankFourTensor< T >::Tensordata.
Referenced by oomph::RankFourTensor< T >::RankFourTensor(), and oomph::RankFourTensor< T >::resize().
nindex1()
template<class T >
unsigned long oomph::RankFourTensor< T >::nindex1 () const [inline]
Return the range of index 1 of the tensor.
Definition at line 2027 of file matrices.h.
References oomph::RankFourTensor< T >::N.
Referenced by oomph::RankFourTensor< T >::operator=(), and oomph::RankFourTensor< T >::RankFourTensor().
nindex2()
template<class T >
unsigned long oomph::RankFourTensor< T >::nindex2 () const [inline]
Return the range of index 2 of the tensor.
Definition at line 2033 of file matrices.h.
References oomph::RankFourTensor< T >::M.
Referenced by oomph::RankFourTensor< T >::operator=(), and oomph::RankFourTensor< T >::RankFourTensor().
nindex3()
template<class T >
unsigned long oomph::RankFourTensor< T >::nindex3 () const [inline]
Return the range of index 3 of the tensor.
Definition at line 2039 of file matrices.h.
References oomph::RankFourTensor< T >::P.
Referenced by oomph::RankFourTensor< T >::operator=(), and oomph::RankFourTensor< T >::RankFourTensor().
nindex4()
template<class T >
unsigned long oomph::RankFourTensor< T >::nindex4 () const [inline]
Return the range of index 4 of the tensor.
Definition at line 2045 of file matrices.h.
References oomph::RankFourTensor< T >::Q.
Referenced by oomph::RankFourTensor< T >::operator=(), and oomph::RankFourTensor< T >::RankFourTensor().
offset()
template<class T >
unsigned oomph::RankFourTensor< T >::offset (const unsigned long & i, const unsigned long & j) const [inline]
Caculate the offset in flat-packed C-style, column-major format, required for a given i,j. WARNING: Only for experienced users. Only use this if raw speed is of the essence, as in the solid mechanics problems.
Definition at line 2096 of file matrices.h.
References i, oomph::RankFourTensor< T >::M, oomph::RankFourTensor< T >::P, and oomph::RankFourTensor< T >::Q.
Referenced by oomph::RefineablePVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::PVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), and oomph::PVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure().
operator()() [1/2]
template<class T >
T & oomph::RankFourTensor< T >::operator() (const unsigned long & i, const unsigned long & j, const unsigned long & k, const unsigned long & l) [inline]
Overload the round brackets to give access as a(i,j,k,l)
Definition at line 2051 of file matrices.h.
References i, oomph::RankFourTensor< T >::M, oomph::RankFourTensor< T >::P, oomph::RankFourTensor< T >::Q, oomph::RankFourTensor< T >::range_check(), and oomph::RankFourTensor< T >::Tensordata.
operator()() [2/2]
template<class T >
T oomph::RankFourTensor< T >::operator() (const unsigned long & i, const unsigned long & j, const unsigned long & k, const unsigned long & l) const [inline]
Overload a const version for read-only access as a(i,j,k,l)
Definition at line 2063 of file matrices.h.
References i, oomph::RankFourTensor< T >::M, oomph::RankFourTensor< T >::P, oomph::RankFourTensor< T >::Q, oomph::RankFourTensor< T >::range_check(), and oomph::RankFourTensor< T >::Tensordata.
operator=()
template<class T >
RankFourTensor & oomph::RankFourTensor< T >::operator= (const RankFourTensor< T > & source_tensor) [inline]
Copy assignement.
Definition at line 1801 of file matrices.h.
References i, oomph::RankFourTensor< T >::M, oomph::RankFourTensor< T >::N, oomph::RankFourTensor< T >::nindex1(), oomph::RankFourTensor< T >::nindex2(), oomph::RankFourTensor< T >::nindex3(), oomph::RankFourTensor< T >::nindex4(), oomph::RankFourTensor< T >::P, oomph::RankFourTensor< T >::Q, and oomph::RankFourTensor< T >::resize().
range_check()
template<class T >
void oomph::RankFourTensor< T >::range_check (const unsigned long & i, const unsigned long & j, const unsigned long & k, const unsigned long & l) const [inline], [private]
Range check to catch when an index is out of bounds, if so, it issues a warning message and dies by throwing an OomphLibError.
Definition at line 1720 of file matrices.h.
References i, oomph::RankFourTensor< T >::M, oomph::RankFourTensor< T >::N, oomph::RankFourTensor< T >::P, and oomph::RankFourTensor< T >::Q.
Referenced by oomph::RankFourTensor< T >::operator()().
raw_direct_access() [1/2]
template<class T >
T & oomph::RankFourTensor< T >::raw_direct_access (const unsigned long & i) [inline]
Direct access to internal storage of data in flat-packed C-style column-major format. WARNING: Only for experienced users. Only use this if raw speed is of the essence, as in the solid mechanics problems.
Definition at line 2078 of file matrices.h.
References i, and oomph::RankFourTensor< T >::Tensordata.
Referenced by oomph::RefineablePVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::PVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), and oomph::PVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure().
raw_direct_access() [2/2]
template<class T >
const T & oomph::RankFourTensor< T >::raw_direct_access (const unsigned long & i) const [inline]
Direct access to internal storage of data in flat-packed C-style column-major format. WARNING: Only for experienced users. Only use this if raw speed is of the essence, as in the solid mechanics problems.
Definition at line 2087 of file matrices.h.
References i, and oomph::RankFourTensor< T >::Tensordata.
resize() [1/3]
template<class T >
void oomph::RankFourTensor< T >::resize (const unsigned long & n) [inline]
Resize to a square nxnxnxn tensor.
Definition at line 1899 of file matrices.h.
References oomph::RankFourTensor< T >::resize().
Referenced by oomph::RankFourTensor< T >::operator=(), and oomph::RankFourTensor< T >::resize().
resize() [2/3]
template<class T >
void oomph::RankFourTensor< T >::resize (const unsigned long & n_index1, const unsigned long & n_index2, const unsigned long & n_index3, const unsigned long & n_index4) [inline]
Resize to a general tensor.
Definition at line 1905 of file matrices.h.
References i, oomph::RankFourTensor< T >::initialise(), oomph::RankFourTensor< T >::M, oomph::RankFourTensor< T >::N, oomph::RankFourTensor< T >::P, oomph::RankFourTensor< T >::Q, oomph::ElementGeometry::T, and oomph::RankFourTensor< T >::Tensordata.
resize() [3/3]
template<class T >
void oomph::RankFourTensor< T >::resize (const unsigned long & n_index1, const unsigned long & n_index2, const unsigned long & n_index3, const unsigned long & n_index4, const T & initial_value) [inline]
Resize to a general tensor.
Definition at line 1961 of file matrices.h.
References i, oomph::RankFourTensor< T >::initialise(), oomph::RankFourTensor< T >::M, oomph::RankFourTensor< T >::N, oomph::RankFourTensor< T >::P, oomph::RankFourTensor< T >::Q, oomph::ElementGeometry::T, and oomph::RankFourTensor< T >::Tensordata.
Member Data Documentation
M
template<class T >
unsigned oomph::RankFourTensor< T >::M [private]
2nd Tensor dimension
Definition at line 1710 of file matrices.h.
Referenced by oomph::RankFourTensor< T >::initialise(), oomph::RankFourTensor< T >::nindex2(), oomph::RankFourTensor< T >::offset(), oomph::RankFourTensor< T >::operator()(), oomph::RankFourTensor< T >::operator=(), oomph::RankFourTensor< T >::range_check(), oomph::RankFourTensor< T >::RankFourTensor(), and oomph::RankFourTensor< T >::resize().
N
template<class T >
unsigned oomph::RankFourTensor< T >::N [private]
1st Tensor dimension
Definition at line 1707 of file matrices.h.
Referenced by oomph::RankFourTensor< T >::initialise(), oomph::RankFourTensor< T >::nindex1(), oomph::RankFourTensor< T >::operator=(), oomph::RankFourTensor< T >::range_check(), oomph::RankFourTensor< T >::RankFourTensor(), and oomph::RankFourTensor< T >::resize().
P
template<class T >
unsigned oomph::RankFourTensor< T >::P [private]
3rd Tensor dimension
Definition at line 1713 of file matrices.h.
Referenced by oomph::RankFourTensor< T >::initialise(), oomph::RankFourTensor< T >::nindex3(), oomph::RankFourTensor< T >::offset(), oomph::RankFourTensor< T >::operator()(), oomph::RankFourTensor< T >::operator=(), oomph::RankFourTensor< T >::range_check(), oomph::RankFourTensor< T >::RankFourTensor(), and oomph::RankFourTensor< T >::resize().
Q
template<class T >
unsigned oomph::RankFourTensor< T >::Q [private]
4th Tensor dimension
Definition at line 1716 of file matrices.h.
Referenced by oomph::RankFourTensor< T >::initialise(), oomph::RankFourTensor< T >::nindex4(), oomph::RankFourTensor< T >::offset(), oomph::RankFourTensor< T >::operator()(), oomph::RankFourTensor< T >::operator=(), oomph::RankFourTensor< T >::range_check(), oomph::RankFourTensor< T >::RankFourTensor(), and oomph::RankFourTensor< T >::resize().
Tensordata
template<class T >
T* oomph::RankFourTensor< T >::Tensordata [private]
Private internal representation as pointer to data.
Definition at line 1704 of file matrices.h.
Referenced by oomph::RankFourTensor< T >::initialise(), oomph::RankFourTensor< T >::operator()(), oomph::RankFourTensor< T >::RankFourTensor(), oomph::RankFourTensor< T >::raw_direct_access(), oomph::RankFourTensor< T >::resize(), and oomph::RankFourTensor< T >::~RankFourTensor().
The documentation for this class was generated from the following file:
matrices.h