oomph::PRefineableElement Class Reference
p-refineable version of RefineableElement
#include <refineable_elements.h>
Public Member Functions
PRefineableElement ()
Constructor, calls the RefineableElement constructor.
virtual ~PRefineableElement ()
Destructor, empty.
PRefineableElement (const PRefineableElement &)
Broken copy constructor.
void operator= (const PRefineableElement &)
Broken assignment operator.
bool p_refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_p_refinement ()
Suppress of any refinement for this element.
void enable_p_refinement ()
Emnable refinement for this element.
unsigned & p_order ()
Access function to P_order.
unsigned p_order () const
Access function to P_order (const version)
virtual unsigned initial_p_order () const =0
void select_for_p_refinement ()
Select the element for p-refinement.
void deselect_for_p_refinement ()
Deselect the element for p-refinement.
void select_for_p_unrefinement ()
Select the element for p-unrefinement.
void deselect_for_p_unrefinement ()
Deselect the element for p-unrefinement.
bool to_be_p_refined ()
Has the element been selected for refinement?
bool to_be_p_unrefined ()
Has the element been selected for p-unrefinement?
virtual void p_refine (const int &inc, Mesh *const &mesh_pt, GeneralisedElement *const &clone_pt)=0
p-refine the element
bool nodes_built ()
Return true if all the nodes have been built, false if not.
Protected Attributes
unsigned P_order
The polynomial expansion order of the elemental basis functions.
bool To_be_p_refined
Flag for p-refinement.
bool P_refinement_is_enabled
Flag to indicate suppression of any refinement.
bool To_be_p_unrefined
Flag for unrefinement.
Additional Inherited Members
Detailed Description
p-refineable version of RefineableElement
Definition at line 657 of file refineable_elements.h.
Constructor & Destructor Documentation
PRefineableElement() [1/2]
oomph::PRefineableElement::PRefineableElement () [inline]
Constructor, calls the RefineableElement constructor.
Definition at line 674 of file refineable_elements.h.
 PRefineableElement()
virtual oomph::PRefineableElement::~PRefineableElement () [inline], [virtual]
Destructor, empty.
Definition at line 684 of file refineable_elements.h.
PRefineableElement() [2/2]
oomph::PRefineableElement::PRefineableElement (const PRefineableElement &) [inline]
Broken copy constructor.
Definition at line 687 of file refineable_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
deselect_for_p_refinement()
void oomph::PRefineableElement::deselect_for_p_refinement () [inline]
Deselect the element for p-refinement.
Definition at line 744 of file refineable_elements.h.
References To_be_p_refined.
Referenced by oomph::TreeBasedRefineableMeshBase::p_adapt(), and oomph::TreeBasedRefineableMeshBase::p_adapt_mesh().
deselect_for_p_unrefinement()
void oomph::PRefineableElement::deselect_for_p_unrefinement () [inline]
Deselect the element for p-unrefinement.
Definition at line 756 of file refineable_elements.h.
References To_be_p_unrefined.
Referenced by oomph::TreeBasedRefineableMeshBase::p_adapt(), and oomph::TreeBasedRefineableMeshBase::p_adapt_mesh().
disable_p_refinement()
void oomph::PRefineableElement::disable_p_refinement () [inline]
Suppress of any refinement for this element.
Definition at line 706 of file refineable_elements.h.
References P_refinement_is_enabled.
enable_p_refinement()
void oomph::PRefineableElement::enable_p_refinement () [inline]
Emnable refinement for this element.
Definition at line 712 of file refineable_elements.h.
References P_refinement_is_enabled.
initial_p_order()
virtual unsigned oomph::PRefineableElement::initial_p_order () const [pure virtual]
Get the initial P_order This is required so that elements which are constructed with a higher p-order initially are not un-refined past this level (e.g. in fluid problems where elements initially use quadratic velocity and linear pressure) Virtual because this needs to be set in templated derived classes
Implemented in oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >, oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >, and oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >.
Referenced by oomph::TreeBasedRefineableMeshBase::p_adapt().
nodes_built()
bool oomph::PRefineableElement::nodes_built () [inline], [virtual]
Return true if all the nodes have been built, false if not.
Reimplemented from oomph::RefineableElement.
Definition at line 779 of file refineable_elements.h.
References n, oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
operator=()
void oomph::PRefineableElement::operator= (const PRefineableElement &) [inline]
Broken assignment operator.
Definition at line 693 of file refineable_elements.h.
References oomph::BrokenCopy::broken_assign().
p_order() [1/2]
unsigned& oomph::PRefineableElement::p_order () [inline]
Access function to P_order.
Definition at line 718 of file refineable_elements.h.
References P_order.
Referenced by oomph::Missing_masters_functions::get_required_master_nodal_information_helper(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::initial_setup(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::initial_setup(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::initial_setup(), oomph::TreeBasedRefineableMeshBase::p_adapt(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::rebuild_from_sons(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::rebuild_from_sons(), and oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::rebuild_from_sons().
p_order() [2/2]
unsigned oomph::PRefineableElement::p_order () const [inline]
Access function to P_order (const version)
Definition at line 724 of file refineable_elements.h.
References P_order.
p_refine()
virtual void oomph::PRefineableElement::p_refine (const int & inc, Mesh *const & mesh_pt, GeneralisedElement *const & clone_pt) [pure virtual]
p-refine the element
Implemented in oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >, oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >, and oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >.
Referenced by oomph::Tree::p_refine_if_required().
p_refinement_is_enabled()
bool oomph::PRefineableElement::p_refinement_is_enabled () [inline]
Flag to indicate suppression of any refinement.
Definition at line 700 of file refineable_elements.h.
References P_refinement_is_enabled.
Referenced by oomph::TreeBasedRefineableMeshBase::p_adapt().
select_for_p_refinement()
void oomph::PRefineableElement::select_for_p_refinement () [inline]
Select the element for p-refinement.
Definition at line 738 of file refineable_elements.h.
References To_be_p_refined.
Referenced by oomph::TreeBasedRefineableMeshBase::p_adapt(), oomph::TreeBasedRefineableMeshBase::p_refine_selected_elements(), and oomph::TreeBasedRefineableMeshBase::p_refine_uniformly().
select_for_p_unrefinement()
void oomph::PRefineableElement::select_for_p_unrefinement () [inline]
Select the element for p-unrefinement.
Definition at line 750 of file refineable_elements.h.
References To_be_p_unrefined.
Referenced by oomph::TreeBasedRefineableMeshBase::p_adapt(), and oomph::TreeBasedRefineableMeshBase::p_unrefine_uniformly().
to_be_p_refined()
bool oomph::PRefineableElement::to_be_p_refined () [inline]
Has the element been selected for refinement?
Definition at line 762 of file refineable_elements.h.
References To_be_p_refined.
Referenced by oomph::Tree::p_refine_if_required().
to_be_p_unrefined()
bool oomph::PRefineableElement::to_be_p_unrefined () [inline]
Has the element been selected for p-unrefinement?
Definition at line 768 of file refineable_elements.h.
References To_be_p_unrefined.
Referenced by oomph::Tree::p_refine_if_required().
Member Data Documentation
P_order
unsigned oomph::PRefineableElement::P_order [protected]
The polynomial expansion order of the elemental basis functions.
Definition at line 661 of file refineable_elements.h.
Referenced by p_order().
P_refinement_is_enabled
bool oomph::PRefineableElement::P_refinement_is_enabled [protected]
Flag to indicate suppression of any refinement.
Definition at line 667 of file refineable_elements.h.
Referenced by disable_p_refinement(), enable_p_refinement(), and p_refinement_is_enabled().
To_be_p_refined
bool oomph::PRefineableElement::To_be_p_refined [protected]
Flag for p-refinement.
Definition at line 664 of file refineable_elements.h.
Referenced by deselect_for_p_refinement(), select_for_p_refinement(), and to_be_p_refined().
To_be_p_unrefined
bool oomph::PRefineableElement::To_be_p_unrefined [protected]
Flag for unrefinement.
Definition at line 670 of file refineable_elements.h.
Referenced by deselect_for_p_unrefinement(), select_for_p_unrefinement(), and to_be_p_unrefined().
The documentation for this class was generated from the following file:
refineable_elements.h