oomph::QFourierDecomposedHelmholtzElement< NNODE_1D > Class Template Reference
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
#include <fourier_decomposed_helmholtz_elements.h>
Public Member Functions
QFourierDecomposedHelmholtzElement ()
Constructor: Call constructors for QElement and FourierDecomposedHelmholtz equations.
QFourierDecomposedHelmholtzElement (const QFourierDecomposedHelmholtzElement< NNODE_1D > &dummy)=delete
Broken copy constructor.
unsigned required_nvalue (const unsigned &n) const
Broken assignment operator.
void output (std::ostream &outfile)
Output function: r,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: r,z,u at n_plot^2 plot points.
void output_real (std::ostream &outfile, const double &phi, const unsigned &n_plot)
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. r,z,u at n_plot plot points in each coordinate direction.
void output (FILE *file_pt)
C-style output function: r,z,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: r,z,u at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: r,z,u_exact at n_plot^2 plot points.
void output_real_fct (std::ostream &outfile, const double &phi, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for real part of full time-dependent fct u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. r,z,u at n_plot plot points in each coordinate direction.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. r,z,u_exact at n_plot^2 plot points (Calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_fourier_decomposed_helmholtz (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_fourier_decomposed_helmholtz (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Static Private Attributes
static const unsigned Initial_Nvalue
Static int that holds the number of variables at nodes: always the same.
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
QFourierDecomposedHelmholtzElement elements are linear/quadrilateral/brick-shaped FourierDecomposedHelmholtz elements with isoparametric interpolation for the function.
Definition at line 428 of file fourier_decomposed_helmholtz_elements.h.
Constructor & Destructor Documentation
QFourierDecomposedHelmholtzElement() [1/2]
template<unsigned NNODE_1D>
oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::QFourierDecomposedHelmholtzElement () [inline]
Constructor: Call constructors for QElement and FourierDecomposedHelmholtz equations.
Definition at line 440 of file fourier_decomposed_helmholtz_elements.h.
QFourierDecomposedHelmholtzElement() [2/2]
template<unsigned NNODE_1D>
oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::QFourierDecomposedHelmholtzElement (const QFourierDecomposedHelmholtzElement< NNODE_1D > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_fourier_decomposed_helmholtz()
template<unsigned NNODE_1D>
double oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::dshape_and_dtest_eulerian_at_knot_fourier_decomposed_helmholtz (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::FourierDecomposedHelmholtzEquations.
Definition at line 595 of file fourier_decomposed_helmholtz_elements.h.
dshape_and_dtest_eulerian_fourier_decomposed_helmholtz()
template<unsigned NNODE_1D>
double oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::dshape_and_dtest_eulerian_fourier_decomposed_helmholtz (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::FourierDecomposedHelmholtzEquations.
Definition at line 568 of file fourier_decomposed_helmholtz_elements.h.
References s.
output() [1/4]
template<unsigned NNODE_1D>
void oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function: r,z,u.
Reimplemented from oomph::FourierDecomposedHelmholtzEquations.
Definition at line 487 of file fourier_decomposed_helmholtz_elements.h.
References oomph::FourierDecomposedHelmholtzEquations::output().
output() [2/4]
template<unsigned NNODE_1D>
void oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: r,z,u at n_plot^2 plot points.
Reimplemented from oomph::FourierDecomposedHelmholtzEquations.
Definition at line 494 of file fourier_decomposed_helmholtz_elements.h.
References oomph::FourierDecomposedHelmholtzEquations::output().
output() [3/4]
template<unsigned NNODE_1D>
void oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: r,z,u.
Reimplemented from oomph::FourierDecomposedHelmholtzEquations.
Definition at line 462 of file fourier_decomposed_helmholtz_elements.h.
References oomph::FourierDecomposedHelmholtzEquations::output().
output() [4/4]
template<unsigned NNODE_1D>
void oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: r,z,u at n_plot^2 plot points.
Reimplemented from oomph::FourierDecomposedHelmholtzEquations.
Definition at line 469 of file fourier_decomposed_helmholtz_elements.h.
References oomph::FourierDecomposedHelmholtzEquations::output().
output_fct() [1/2]
template<unsigned NNODE_1D>
void oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. r,z,u_exact at n_plot^2 plot points (Calls the steady version)
Reimplemented from oomph::FourierDecomposedHelmholtzEquations.
Definition at line 527 of file fourier_decomposed_helmholtz_elements.h.
References oomph::FourierDecomposedHelmholtzEquations::output_fct().
output_fct() [2/2]
template<unsigned NNODE_1D>
void oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: r,z,u_exact at n_plot^2 plot points.
Reimplemented from oomph::FourierDecomposedHelmholtzEquations.
Definition at line 501 of file fourier_decomposed_helmholtz_elements.h.
References oomph::FourierDecomposedHelmholtzEquations::output_fct().
output_real()
template<unsigned NNODE_1D>
void oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::output_real (std::ostream & outfile, const double & phi, const unsigned & n_plot) [inline]
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. r,z,u at n_plot plot points in each coordinate direction.
Definition at line 479 of file fourier_decomposed_helmholtz_elements.h.
References oomph::FourierDecomposedHelmholtzEquations::output_real().
output_real_fct()
template<unsigned NNODE_1D>
void oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::output_real_fct (std::ostream & outfile, const double & phi, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline]
Output function for real part of full time-dependent fct u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. r,z,u at n_plot plot points in each coordinate direction.
Definition at line 514 of file fourier_decomposed_helmholtz_elements.h.
References oomph::FourierDecomposedHelmholtzEquations::output_real_fct().
required_nvalue()
template<unsigned NNODE_1D>
unsigned oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Broken assignment operator.
Required # of `values' (pinned or dofs) at node n
Reimplemented from oomph::FiniteElement.
Definition at line 456 of file fourier_decomposed_helmholtz_elements.h.
References oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::Initial_Nvalue.
Member Data Documentation
Initial_Nvalue
template<unsigned NNODE_1D>
const unsigned oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::Initial_Nvalue [static], [private]
Initial value:
=
    2
Static int that holds the number of variables at nodes: always the same.
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Set the data for the number of Variables at each node, always two (real and imag part) in every case
Definition at line 435 of file fourier_decomposed_helmholtz_elements.h.
Referenced by oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::required_nvalue().
The documentation for this class was generated from the following files:
fourier_decomposed_helmholtz_elements.h
fourier_decomposed_helmholtz_elements.cc