oomph::RefineableLineMesh< ELEMENT > Class Template Reference
Intermediate mesh class that implements the mesh adaptation functions specified in the RefineableMesh class for meshes that contain the refineable variant of QElement s [The class ELEMENT provided as the template parameter must be of type RefineableQElement<1>].
#include <refineable_line_mesh.h>
Public Member Functions
RefineableLineMesh ()
Constructor: Set up static binary tree data.
RefineableLineMesh (const RefineableLineMesh &dummy)=delete
Broken copy constructor.
void operator= (const RefineableLineMesh &)=delete
Broken assignment operator.
virtual ~RefineableLineMesh ()
Destructor:
virtual void setup_tree_forest ()
Set up the tree forest associated with the Mesh. Forwards call to setup_binary_tree_forest().
void setup_binary_tree_forest ()
Set up BinaryTreeForest. Wipes any existing tree structure and regards the currently active elements as the root trees in the forest.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::RefineableLineMesh< ELEMENT >
Intermediate mesh class that implements the mesh adaptation functions specified in the RefineableMesh class for meshes that contain the refineable variant of QElement s [The class ELEMENT provided as the template parameter must be of type RefineableQElement<1>].
Mesh adaptation/refinement is implemented by BinaryTree procedures and any concrete implementation of this class needs to provide a BinaryTreeForest representation of the initial (coarse) mesh.
Definition at line 48 of file refineable_line_mesh.h.
Constructor & Destructor Documentation
RefineableLineMesh() [1/2]
template<class ELEMENT >
oomph::RefineableLineMesh< ELEMENT >::RefineableLineMesh () [inline]
Constructor: Set up static binary tree data.
Definition at line 53 of file refineable_line_mesh.h.
References oomph::BinaryTree::setup_static_data().
RefineableLineMesh() [2/2]
template<class ELEMENT >
oomph::RefineableLineMesh< ELEMENT >::RefineableLineMesh (const RefineableLineMesh< ELEMENT > & dummy) [delete]
Broken copy constructor.
 RefineableLineMesh()
template<class ELEMENT >
virtual oomph::RefineableLineMesh< ELEMENT >::~RefineableLineMesh () [inline], [virtual]
Destructor:
Definition at line 67 of file refineable_line_mesh.h.
Member Function Documentation
operator=()
template<class ELEMENT >
void oomph::RefineableLineMesh< ELEMENT >::operator= (const RefineableLineMesh< ELEMENT > &) [delete]
Broken assignment operator.
setup_binary_tree_forest()
template<class ELEMENT >
void oomph::RefineableLineMesh< ELEMENT >::setup_binary_tree_forest () [inline]
Set up BinaryTreeForest. Wipes any existing tree structure and regards the currently active elements as the root trees in the forest.
Definition at line 78 of file refineable_line_mesh.h.
References e, oomph::Mesh::element_pt(), oomph::TreeBasedRefineableMeshBase::Forest_pt, and oomph::Mesh::nelement().
Referenced by oomph::RefineableOneDMesh< ELEMENT >::RefineableOneDMesh(), and oomph::RefineableLineMesh< ELEMENT >::setup_tree_forest().
setup_tree_forest()
template<class ELEMENT >
virtual void oomph::RefineableLineMesh< ELEMENT >::setup_tree_forest () [inline], [virtual]
Set up the tree forest associated with the Mesh. Forwards call to setup_binary_tree_forest().
Implements oomph::TreeBasedRefineableMeshBase.
Definition at line 71 of file refineable_line_mesh.h.
References oomph::RefineableLineMesh< ELEMENT >::setup_binary_tree_forest().
The documentation for this class was generated from the following file:
refineable_line_mesh.h