oomph::LinearisedAxisymmetricQTaylorHoodElement Class Reference
/////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////
#include <linearised_axisym_navier_stokes_elements.h>
Public Member Functions
LinearisedAxisymmetricQTaylorHoodElement ()
Constructor, no internal data points.
virtual unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
virtual int p_index_linearised_axi_nst (const unsigned &i) const
Which nodal value represents the pressure? Overload version in base class which returns static int `Pressure_not_stored_at_node`.
double p_linearised_axi_nst (const unsigned &n_p, const unsigned &i) const
Access function for the i-th component of pressure at local pressure node n_p (const version).
unsigned npres_linearised_axi_nst () const
Return number of pressure values corresponding to a single pressure component.
void fix_pressure (const unsigned &n_p, const double &pvalue)
Fix both components of the pressure at local pressure node n_p to pvalue.
int p_local_eqn (const unsigned &n, const unsigned &i)
Overload the access function for the i-th component of the pressure's local equation numbers.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
unsigned ndof_types () const
Returns the number of `dof-blocks` that degrees of freedom in this element are sub-divided into: Velocity and pressure.
Protected Member Functions
double dshape_and_dtest_eulerian_linearised_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivatives w.r.t. global coordinates at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_linearised_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivatives w.r.t. global coordinates the ipt-th integation point (taken from geometry). Return Jacobian of mapping between local and global coordinates.
void pshape_linearised_axi_nst (const Vector< double > &s, Shape &psi) const
Compute the pressure shape functions at local coordinate s.
void pshape_linearised_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Compute the pressure shape and test functions at local coordinte s.
Static Protected Attributes
static const unsigned Pconv []
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Static Private Attributes
static const unsigned Initial_Nvalue []
Static array of ints to hold number of variables at node.
Additional Inherited Members
Detailed Description
/////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////
Taylor--Hood elements are Navier--Stokes elements with quadratic interpolation for velocities and positions and continuous linear pressure interpolation
Definition at line 779 of file linearised_axisym_navier_stokes_elements.h.
Constructor & Destructor Documentation
LinearisedAxisymmetricQTaylorHoodElement()
oomph::LinearisedAxisymmetricQTaylorHoodElement::LinearisedAxisymmetricQTaylorHoodElement () [inline]
Constructor, no internal data points.
Definition at line 824 of file linearised_axisym_navier_stokes_elements.h.
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_linearised_axi_nst()
double oomph::LinearisedAxisymmetricQTaylorHoodElement::dshape_and_dtest_eulerian_at_knot_linearised_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivatives w.r.t. global coordinates the ipt-th integation point (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t global (Eulerian) coordinates at the ipt-th integration point. Return Jacobian of mapping between local and global coordinates.
Implements oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 947 of file linearised_axisym_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot(), and i.
dshape_and_dtest_eulerian_linearised_axi_nst()
double oomph::LinearisedAxisymmetricQTaylorHoodElement::dshape_and_dtest_eulerian_linearised_axi_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivatives w.r.t. global coordinates at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t global (Eulerian) coordinates at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Implements oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 919 of file linearised_axisym_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian(), and i.
fix_pressure()
void oomph::LinearisedAxisymmetricQTaylorHoodElement::fix_pressure (const unsigned & n_p, const double & pvalue) [inline]
Fix both components of the pressure at local pressure node n_p to pvalue.
Definition at line 859 of file linearised_axisym_navier_stokes_elements.h.
References i, oomph::FiniteElement::node_pt(), p_index_linearised_axi_nst(), oomph::Data::pin(), and oomph::Data::set_value().
ndof_types()
unsigned oomph::LinearisedAxisymmetricQTaylorHoodElement::ndof_types () const [inline], [virtual]
Returns the number of `dof-blocks` that degrees of freedom in this element are sub-divided into: Velocity and pressure.
Reimplemented from oomph::GeneralisedElement.
Definition at line 903 of file linearised_axisym_navier_stokes_elements.h.
npres_linearised_axi_nst()
unsigned oomph::LinearisedAxisymmetricQTaylorHoodElement::npres_linearised_axi_nst () const [inline], [virtual]
Return number of pressure values corresponding to a single pressure component.
Implements oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 852 of file linearised_axisym_navier_stokes_elements.h.
Referenced by oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs().
output() [1/4]
void oomph::LinearisedAxisymmetricQTaylorHoodElement::output (FILE * file_pt) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 890 of file linearised_axisym_navier_stokes_elements.h.
References oomph::LinearisedAxisymmetricNavierStokesEquations::output().
output() [2/4]
void oomph::LinearisedAxisymmetricQTaylorHoodElement::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 896 of file linearised_axisym_navier_stokes_elements.h.
References oomph::LinearisedAxisymmetricNavierStokesEquations::output().
output() [3/4]
void oomph::LinearisedAxisymmetricQTaylorHoodElement::output (std::ostream & outfile) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 878 of file linearised_axisym_navier_stokes_elements.h.
References oomph::LinearisedAxisymmetricNavierStokesEquations::output().
output() [4/4]
void oomph::LinearisedAxisymmetricQTaylorHoodElement::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 884 of file linearised_axisym_navier_stokes_elements.h.
References oomph::LinearisedAxisymmetricNavierStokesEquations::output().
p_index_linearised_axi_nst()
virtual int oomph::LinearisedAxisymmetricQTaylorHoodElement::p_index_linearised_axi_nst (const unsigned & i) const [inline], [virtual]
Which nodal value represents the pressure? Overload version in base class which returns static int `Pressure_not_stored_at_node`.
Reimplemented from oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 838 of file linearised_axisym_navier_stokes_elements.h.
References i.
Referenced by fix_pressure(), p_linearised_axi_nst(), p_local_eqn(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), and oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::unpin_elemental_pressure_dofs().
p_linearised_axi_nst()
double oomph::LinearisedAxisymmetricQTaylorHoodElement::p_linearised_axi_nst (const unsigned & n_p, const unsigned & i) const [inline], [virtual]
Access function for the i-th component of pressure at local pressure node n_p (const version).
Implements oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 845 of file linearised_axisym_navier_stokes_elements.h.
References i, oomph::FiniteElement::nodal_value(), p_index_linearised_axi_nst(), and Pconv.
p_local_eqn()
int oomph::LinearisedAxisymmetricQTaylorHoodElement::p_local_eqn (const unsigned & n, const unsigned & i) [inline], [virtual]
Overload the access function for the i-th component of the pressure's local equation numbers.
Implements oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 872 of file linearised_axisym_navier_stokes_elements.h.
References i, oomph::FiniteElement::nodal_local_eqn(), p_index_linearised_axi_nst(), and Pconv.
pshape_linearised_axi_nst() [1/2]
void oomph::LinearisedAxisymmetricQTaylorHoodElement::pshape_linearised_axi_nst (const Vector< double > & s, Shape & psi) const [inline], [protected], [virtual]
Compute the pressure shape functions at local coordinate s.
Pressure shape functions.
Implements oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 973 of file linearised_axisym_navier_stokes_elements.h.
References i, s, and oomph::OneDimLagrange::shape< 2 >().
Referenced by oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::interpolating_basis(), and pshape_linearised_axi_nst().
pshape_linearised_axi_nst() [2/2]
void oomph::LinearisedAxisymmetricQTaylorHoodElement::pshape_linearised_axi_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected], [virtual]
Compute the pressure shape and test functions at local coordinte s.
Pressure shape and test functions.
Implements oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 998 of file linearised_axisym_navier_stokes_elements.h.
References i, pshape_linearised_axi_nst(), and s.
required_nvalue()
virtual unsigned oomph::LinearisedAxisymmetricQTaylorHoodElement::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement.
Definition at line 831 of file linearised_axisym_navier_stokes_elements.h.
References Initial_Nvalue.
Member Data Documentation
Initial_Nvalue
const unsigned oomph::LinearisedAxisymmetricQTaylorHoodElement::Initial_Nvalue [static], [private]
Initial value:
= {
    8, 6, 8, 6, 6, 6, 8, 6, 8}
Static array of ints to hold number of variables at node.
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Linearised axisymmetric Taylor-Hood elements
Set the data for the number of variables at each node
Definition at line 785 of file linearised_axisym_navier_stokes_elements.h.
Referenced by required_nvalue().
Pconv
const unsigned oomph::LinearisedAxisymmetricQTaylorHoodElement::Pconv [static], [protected]
Initial value:
= {
    0, 2, 6, 8}
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Set the data for the pressure conversion array.
Definition at line 790 of file linearised_axisym_navier_stokes_elements.h.
Referenced by oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::interpolating_node_pt(), p_linearised_axi_nst(), p_local_eqn(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), and oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::pressure_node_pt().
The documentation for this class was generated from the following files:
linearised_axisym_navier_stokes_elements.h
linearised_axisym_navier_stokes_elements.cc