oomph::RefineableSolidBrickFromTetMesh< ELEMENT > Class Template Reference
#include <brick_from_tet_mesh.template.h>
Public Member Functions
RefineableSolidBrickFromTetMesh (const std::string xda_file_name, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass xda file name.
RefineableSolidBrickFromTetMesh (const std::string xda_file_name, XdaTetMesh< TElement< 3, 3 >> *&xda_tet_mesh_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass xda file name. This returns a pointer to the internally built XdaTetMesh for external use. Note that YOU are responsible for deleting this mesh.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::RefineableSolidBrickFromTetMesh< ELEMENT >
Refineable solid brick mesh built by brickifying an existing tet mesh -- each tet gets split into four bricks. Can only be built with quadratic (27 node) elements.
Definition at line 256 of file brick_from_tet_mesh.template.h.
Constructor & Destructor Documentation
RefineableSolidBrickFromTetMesh() [1/2]
template<class ELEMENT >
oomph::RefineableSolidBrickFromTetMesh< ELEMENT >::RefineableSolidBrickFromTetMesh (const std::string xda_file_name, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass xda file name.
Definition at line 264 of file brick_from_tet_mesh.template.h.
References oomph::SolidMesh::set_lagrangian_nodal_coordinates(), and oomph::RefineableBrickMesh< ELEMENT >::setup_octree_forest().
RefineableSolidBrickFromTetMesh() [2/2]
template<class ELEMENT >
oomph::RefineableSolidBrickFromTetMesh< ELEMENT >::RefineableSolidBrickFromTetMesh (const std::string xda_file_name, XdaTetMesh< TElement< 3, 3 >> *& xda_tet_mesh_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass xda file name. This returns a pointer to the internally built XdaTetMesh for external use. Note that YOU are responsible for deleting this mesh.
Definition at line 283 of file brick_from_tet_mesh.template.h.
References oomph::SolidMesh::set_lagrangian_nodal_coordinates(), and oomph::RefineableBrickMesh< ELEMENT >::setup_octree_forest().
The documentation for this class was generated from the following file:
brick_from_tet_mesh.template.h