GeneralisedNewtonianQCrouzeixRaviartElement< DIM > Class Template Reference
/////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////
#include <generalised_newtonian_navier_stokes_elements.h>
Public Member Functions
GeneralisedNewtonianQCrouzeixRaviartElement ()
Constructor, there are DIM+1 internal values (for the pressure)
virtual unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at local node n.
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
double p_nst (const unsigned &i) const
Return the i-th pressure value (Discontinous pressure interpolation -- no need to cater for hanging nodes).
double p_nst (const unsigned &t, const unsigned &i) const
Return the i-th pressure value (Discontinous pressure interpolation -- no need to cater for hanging nodes).
unsigned npres_nst () const
Return number of pressure values.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs containing.
void identify_pressure_data (std::set< std::pair< Data *, unsigned > > &paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void full_output (std::ostream &outfile)
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. Default number of plot points.
void full_output (std::ostream &outfile, const unsigned &nplot)
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. nplot points in each coordinate direction.
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity and pressure.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1.
void pshape_nst (const Vector< double > &s, Shape &psi) const
2D : Pressure shape functions
void pshape_nst (const Vector< double > &s, Shape &psi) const
3D : Pressure shape functions
Protected Member Functions
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at ipt-th integation point (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
2D Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
3D Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
2D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
3D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
Protected Attributes
unsigned P_nst_internal_index
Internal index that indicates at which internal data the pressure is stored.
Private Member Functions
const unsigned Initial_Nvalue [9]
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
const unsigned Initial_Nvalue [27]
3D Crouzeix-Raviart elements
Static Private Attributes
static const unsigned Initial_Nvalue []
Static array of ints to hold required number of variables at nodes.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class GeneralisedNewtonianQCrouzeixRaviartElement< DIM >
/////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////
Crouzeix_Raviart elements are Navier--Stokes elements with quadratic interpolation for velocities and positions, but a discontinuous linear pressure interpolation. They can be used within oomph-lib's block preconditioning framework.
Definition at line 1308 of file generalised_newtonian_navier_stokes_elements.h.
Constructor & Destructor Documentation
GeneralisedNewtonianQCrouzeixRaviartElement()
template<unsigned DIM>
GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::GeneralisedNewtonianQCrouzeixRaviartElement () [inline]
Constructor, there are DIM+1 internal values (for the pressure)
Definition at line 1364 of file generalised_newtonian_navier_stokes_elements.h.
Member Function Documentation
dpshape_and_dptest_eulerian_nst() [1/3]
template<unsigned DIM>
double GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
dpshape_and_dptest_eulerian_nst() [2/3]
double GeneralisedNewtonianQCrouzeixRaviartElement< 2 >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
2D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1672 of file generalised_newtonian_navier_stokes_elements.h.
References s.
dpshape_and_dptest_eulerian_nst() [3/3]
double GeneralisedNewtonianQCrouzeixRaviartElement< 3 >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
3D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1752 of file generalised_newtonian_navier_stokes_elements.h.
References s.
dshape_and_dtest_eulerian_at_knot_nst() [1/4]
template<unsigned DIM>
double GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
dshape_and_dtest_eulerian_at_knot_nst() [2/4]
double GeneralisedNewtonianQCrouzeixRaviartElement< 2 >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
2D Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1561 of file generalised_newtonian_navier_stokes_elements.h.
References i.
dshape_and_dtest_eulerian_at_knot_nst() [3/4]
double GeneralisedNewtonianQCrouzeixRaviartElement< 3 >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
3D Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1611 of file generalised_newtonian_navier_stokes_elements.h.
References i.
dshape_and_dtest_eulerian_at_knot_nst() [4/4]
template<unsigned DIM>
double GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at ipt-th integation point (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t. to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1535 of file generalised_newtonian_navier_stokes_elements.h.
dshape_and_dtest_eulerian_nst()
template<unsigned DIM>
double GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t. to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1513 of file generalised_newtonian_navier_stokes_elements.h.
References s.
fix_pressure()
template<unsigned DIM>
void GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::fix_pressure (const unsigned & p_dof, const double & p_value) [inline], [virtual]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Reimplemented in oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >.
Definition at line 1414 of file generalised_newtonian_navier_stokes_elements.h.
full_output() [1/2]
template<unsigned DIM>
void GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::full_output (std::ostream & outfile) [inline]
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. Default number of plot points.
Definition at line 1472 of file generalised_newtonian_navier_stokes_elements.h.
References GeneralisedNewtonianNavierStokesEquations< DIM >::full_output().
full_output() [2/2]
template<unsigned DIM>
void GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::full_output (std::ostream & outfile, const unsigned & nplot) [inline]
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. nplot points in each coordinate direction.
Definition at line 1480 of file generalised_newtonian_navier_stokes_elements.h.
References GeneralisedNewtonianNavierStokesEquations< DIM >::full_output().
get_dof_numbers_for_unknowns()
template<unsigned DIM>
void GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1.
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the DOF that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Definition at line 2672 of file generalised_newtonian_navier_stokes_elements.cc.
identify_load_data()
template<unsigned DIM>
void GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data)
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Definition at line 2608 of file generalised_newtonian_navier_stokes_elements.cc.
References i.
identify_pressure_data()
template<unsigned DIM>
void GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::identify_pressure_data (std::set< std::pair< Data *, unsigned > > & paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
Add to the set paired_pressue_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all pressure values that affect the load computed in the get_load(...) function.
the pointer to a Data object and
the index of the value in that Data object
for all pressures values that affect the load computed in the get_load(...) function.
Definition at line 2645 of file generalised_newtonian_navier_stokes_elements.cc.
Initial_Nvalue() [1/2]
const unsigned GeneralisedNewtonianQCrouzeixRaviartElement< 3 >::Initial_Nvalue [private]
3D Crouzeix-Raviart elements
Definition at line 2582 of file generalised_newtonian_navier_stokes_elements.cc.
Initial_Nvalue() [2/2]
const unsigned GeneralisedNewtonianQCrouzeixRaviartElement< 2 >::Initial_Nvalue [private]
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
2D Crouzeix-Raviart elements
Definition at line 2575 of file generalised_newtonian_navier_stokes_elements.cc.
ndof_types()
template<unsigned DIM>
unsigned GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::ndof_types () const [inline]
The number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity and pressure.
Definition at line 1489 of file generalised_newtonian_navier_stokes_elements.h.
npres_nst()
template<unsigned DIM>
unsigned GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::npres_nst () const [inline], [virtual]
Return number of pressure values.
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Reimplemented in oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >.
Definition at line 1401 of file generalised_newtonian_navier_stokes_elements.h.
Referenced by oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::identify_load_data(), and oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::unpin_elemental_pressure_dofs().
output() [1/4]
template<unsigned DIM>
void GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::output (FILE * file_pt) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 1457 of file generalised_newtonian_navier_stokes_elements.h.
References GeneralisedNewtonianNavierStokesEquations< DIM >::output().
output() [2/4]
template<unsigned DIM>
void GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::output (FILE * file_pt, const unsigned & nplot) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 1463 of file generalised_newtonian_navier_stokes_elements.h.
References GeneralisedNewtonianNavierStokesEquations< DIM >::output().
output() [3/4]
template<unsigned DIM>
void GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::output (std::ostream & outfile) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 1444 of file generalised_newtonian_navier_stokes_elements.h.
References GeneralisedNewtonianNavierStokesEquations< DIM >::output().
output() [4/4]
template<unsigned DIM>
void GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 1450 of file generalised_newtonian_navier_stokes_elements.h.
References GeneralisedNewtonianNavierStokesEquations< DIM >::output().
p_local_eqn()
template<unsigned DIM>
int GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::p_local_eqn (const unsigned & n) const [inline]
Return the local equation numbers for the pressure values.
Definition at line 1408 of file generalised_newtonian_navier_stokes_elements.h.
p_nst() [1/2]
template<unsigned DIM>
double GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::p_nst (const unsigned & i) const [inline], [virtual]
Return the i-th pressure value (Discontinous pressure interpolation -- no need to cater for hanging nodes).
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Reimplemented in oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >.
Definition at line 1387 of file generalised_newtonian_navier_stokes_elements.h.
References i.
p_nst() [2/2]
template<unsigned DIM>
double GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::p_nst (const unsigned & t, const unsigned & i) const [inline], [virtual]
Return the i-th pressure value (Discontinous pressure interpolation -- no need to cater for hanging nodes).
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Reimplemented in oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >.
Definition at line 1395 of file generalised_newtonian_navier_stokes_elements.h.
References i, and t.
pshape_nst() [1/4]
template<unsigned DIM>
void GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Pressure shape functions at local coordinate s.
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
pshape_nst() [2/4]
void GeneralisedNewtonianQCrouzeixRaviartElement< 2 >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
2D : Pressure shape functions
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1656 of file generalised_newtonian_navier_stokes_elements.h.
References s.
pshape_nst() [3/4]
void GeneralisedNewtonianQCrouzeixRaviartElement< 3 >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
3D : Pressure shape functions
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1735 of file generalised_newtonian_navier_stokes_elements.h.
References s.
pshape_nst() [4/4]
template<unsigned DIM>
void GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [virtual]
Pressure shape and test functions at local coordinte s.
Ppressure shape and test functions.
Implements GeneralisedNewtonianNavierStokesEquations< DIM >.
Definition at line 1720 of file generalised_newtonian_navier_stokes_elements.h.
References s.
required_nvalue()
template<unsigned DIM>
unsigned GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::required_nvalue (const unsigned & n) const [virtual]
Number of values (pinned or dofs) required at local node n.
Number of values (pinned or dofs) required at node n.
Reimplemented in oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >.
Definition at line 2591 of file generalised_newtonian_navier_stokes_elements.cc.
Member Data Documentation
Initial_Nvalue
template<unsigned DIM>
const unsigned GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::Initial_Nvalue[] [static], [private]
Static array of ints to hold required number of variables at nodes.
Definition at line 1314 of file generalised_newtonian_navier_stokes_elements.h.
P_nst_internal_index
template<unsigned DIM>
unsigned GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::P_nst_internal_index [protected]
Internal index that indicates at which internal data the pressure is stored.
Definition at line 1319 of file generalised_newtonian_navier_stokes_elements.h.
Referenced by oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::fix_pressure(), oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::identify_load_data(), oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::p_nst(), oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement(), oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::rebuild_from_sons(), oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::unpin_elemental_pressure_dofs(), and oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::unpin_elemental_pressure_dofs().
The documentation for this class was generated from the following files:
generalised_newtonian_navier_stokes_elements.h
generalised_newtonian_navier_stokes_elements.cc