oomph::BuoyantQCrouzeixRaviartElement< DIM > Class Template Reference
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
#include <boussinesq_elements.h>
Public Member Functions
BuoyantQCrouzeixRaviartElement ()
Constructor: call the underlying constructors and initialise the pointer to the Rayleigh number to point to the default value of 0.0.
void unfix_pressure (const unsigned &p_dof)
Unpin p_dof-th pressure dof.
unsigned required_nvalue (const unsigned &n) const
The required number of values stored at the nodes is the sum of the required values of the two single-physics elements. Note that this step is generic for any multi-physics element of this type.
const double & ra () const
Access function for the Rayleigh number (const version)
double *& ra_pt ()
Access function for the pointer to the Rayleigh number.
void disable_ALE ()
Final override for disable ALE.
void enable_ALE ()
Final override for enable ALE.
unsigned nscalar_paraview () const
Number of scalars/fields output by this element. Broken virtual. Needs to be implemented for each new specific element type. Temporary dummy.
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
Write values of the i-th scalar field at the plot points. Broken virtual. Needs to be implemented for each new specific element type. Temporary dummy.
std::string scalar_name_paraview (const unsigned &i) const
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names.
void output (std::ostream &outfile)
Overload the standard output function with the broken default.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: Output x, y, u, v, p, theta at Nplot^DIM plot points.
void output (FILE *file_pt)
C-style output function: Broken default.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: Broken default.
void output_fct (std::ostream &outfile, const unsigned &Nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: Broken default.
void output_fct (std::ostream &outfile, const unsigned &Nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution: Broken default.
unsigned u_index_adv_diff () const
Overload the index at which the temperature variable is stored. We choose to store it after the fluid velocities.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element Call the broken default.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element Call the broken default.
void get_wind_adv_diff (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
Overload the wind function in the advection-diffusion equations. This provides the coupling from the Navier--Stokes equations to the advection-diffusion equations because the wind is the fluid velocity.
void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
Overload the body force in the Navier-Stokes equations This provides the coupling from the advection-diffusion equations to the Navier--Stokes equations, the body force is the temperature multiplied by the Rayleigh number acting in the direction opposite to gravity.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Calculate the element's contribution to the residual vector. Recall that fill_in_* functions MUST NOT initialise the entries in the vector to zero. This allows us to call the fill_in_* functions of the constituent single-physics elements sequentially, without wiping out any previously computed entries.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual vector and the Jacobian matrix. Jacobian is computed by finite-differencing.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void fill_in_off_diagonal_jacobian_blocks_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Helper function to get the off-diagonal blocks of the Jacobian matrix by finite differences.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual Vector and the Jacobian matrix. Use finite-differencing only for the off-diagonal blocks.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void fill_in_off_diagonal_jacobian_blocks_analytic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Helper function to get the off-diagonal blocks of the Jacobian matrix analytically.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual Vector and the Jacobian matrix. Use analytic expressions for the off-diagonal blocks.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Private Member Functions
double Default_Physical_Constant_Value
Set the default physical value to be zero.
double Default_Physical_Constant_Value
Private Attributes
double * Ra_pt
Pointer to a private data member, the Rayleigh number.
Static Private Attributes
static double Default_Physical_Constant_Value
The static default value of the Rayleigh number.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::BuoyantQCrouzeixRaviartElement< DIM >
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
A class that solves the Boussinesq approximation of the Navier--Stokes and energy equations by coupling two pre-existing classes. The QAdvectionDiffusionElement with bi-quadratic interpolation for the scalar variable (temperature) and QCrouzeixRaviartElement which solves the Navier--Stokes equations using bi-quadratic interpolation for the velocities and a discontinuous bi-linear interpolation for the pressure. Note that we are free to choose the order in which we store the variables at the nodes. In this case we choose to store the variables in the order fluid velocities followed by temperature. We must, therefore, overload the function AdvectionDiffusionEquations<DIM>::u_index_adv_diff() to indicate that the temperature is stored at the DIM-th position not the 0-th. We do not need to overload the corresponding function in the NavierStokesEquations<DIM> class because the velocities are stored first.
Definition at line 65 of file boussinesq_elements.h.
Constructor & Destructor Documentation
BuoyantQCrouzeixRaviartElement()
template<unsigned DIM>
oomph::BuoyantQCrouzeixRaviartElement< DIM >::BuoyantQCrouzeixRaviartElement () [inline]
Constructor: call the underlying constructors and initialise the pointer to the Rayleigh number to point to the default value of 0.0.
Definition at line 80 of file boussinesq_elements.h.
References oomph::BuoyantQCrouzeixRaviartElement< DIM >::Default_Physical_Constant_Value, and oomph::BuoyantQCrouzeixRaviartElement< DIM >::Ra_pt.
Member Function Documentation
compute_error() [1/2]
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [inline], [virtual]
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element Call the broken default.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 272 of file boussinesq_elements.h.
References oomph::FiniteElement::compute_error().
compute_error() [2/2]
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [inline], [virtual]
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element Call the broken default.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 258 of file boussinesq_elements.h.
References oomph::FiniteElement::compute_error().
Default_Physical_Constant_Value() [1/2]
double oomph::BuoyantQCrouzeixRaviartElement< 2 >::Default_Physical_Constant_Value [private]
Set the default physical value to be zero.
Definition at line 744 of file boussinesq_elements.h.
Default_Physical_Constant_Value() [2/2]
double oomph::BuoyantQCrouzeixRaviartElement< 3 >::Default_Physical_Constant_Value [private]
Definition at line 747 of file boussinesq_elements.h.
disable_ALE()
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::disable_ALE () [inline], [virtual]
Final override for disable ALE.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 114 of file boussinesq_elements.h.
References oomph::AdvectionDiffusionEquations< DIM >::disable_ALE(), and oomph::NavierStokesEquations< DIM >::disable_ALE().
enable_ALE()
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::enable_ALE () [inline], [virtual]
Final override for enable ALE.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 122 of file boussinesq_elements.h.
References oomph::AdvectionDiffusionEquations< DIM >::enable_ALE(), and oomph::NavierStokesEquations< DIM >::enable_ALE().
fill_in_contribution_to_jacobian() [1/3]
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute the element's residual vector and the Jacobian matrix. Jacobian is computed by finite-differencing.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 341 of file boussinesq_elements.h.
References oomph::FiniteElement::fill_in_contribution_to_jacobian().
fill_in_contribution_to_jacobian() [2/3]
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute the element's residual Vector and the Jacobian matrix. Use finite-differencing only for the off-diagonal blocks.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 516 of file boussinesq_elements.h.
References oomph::AdvectionDiffusionEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::NavierStokesEquations< DIM >::fill_in_contribution_to_jacobian(), and oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd().
fill_in_contribution_to_jacobian() [3/3]
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute the element's residual Vector and the Jacobian matrix. Use analytic expressions for the off-diagonal blocks.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 696 of file boussinesq_elements.h.
References oomph::AdvectionDiffusionEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::NavierStokesEquations< DIM >::fill_in_contribution_to_jacobian(), and oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic().
fill_in_contribution_to_jacobian_and_mass_matrix() [1/3]
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline], [virtual]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 350 of file boussinesq_elements.h.
References oomph::GeneralisedElement::fill_in_contribution_to_jacobian_and_mass_matrix().
Referenced by oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix().
fill_in_contribution_to_jacobian_and_mass_matrix() [2/3]
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline], [virtual]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 537 of file boussinesq_elements.h.
References oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), and oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd().
fill_in_contribution_to_jacobian_and_mass_matrix() [3/3]
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline], [virtual]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 716 of file boussinesq_elements.h.
References oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), and oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic().
fill_in_contribution_to_residuals()
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Calculate the element's contribution to the residual vector. Recall that fill_in_* functions MUST NOT initialise the entries in the vector to zero. This allows us to call the fill_in_* functions of the constituent single-physics elements sequentially, without wiping out any previously computed entries.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 323 of file boussinesq_elements.h.
References oomph::AdvectionDiffusionEquations< DIM >::fill_in_contribution_to_residuals(), and oomph::NavierStokesEquations< DIM >::fill_in_contribution_to_residuals().
fill_in_off_diagonal_jacobian_blocks_analytic()
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline]
Helper function to get the off-diagonal blocks of the Jacobian matrix analytically.
Definition at line 564 of file boussinesq_elements.h.
References oomph::QCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst(), oomph::NavierStokesEquations< DIM >::g(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::Integral::nweight(), oomph::AdvectionDiffusionEquations< DIM >::pe(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::ra(), oomph::FiniteElement::raw_nodal_value(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::u_index_adv_diff(), oomph::NavierStokesEquations< DIM >::u_index_nst(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian(), and oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix().
fill_in_off_diagonal_jacobian_blocks_by_fd()
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline]
Helper function to get the off-diagonal blocks of the Jacobian matrix by finite differences.
Definition at line 369 of file boussinesq_elements.h.
References oomph::GeneralisedElement::Default_fd_jacobian_step, oomph::AdvectionDiffusionEquations< DIM >::fill_in_contribution_to_residuals(), oomph::NavierStokesEquations< DIM >::fill_in_contribution_to_residuals(), i, oomph::GeneralisedElement::ndof(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::u_index_adv_diff(), oomph::NavierStokesEquations< DIM >::u_index_nst(), and oomph::Data::value_pt().
Referenced by oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian(), and oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix().
get_body_force_nst()
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::get_body_force_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & result) [inline], [virtual]
Overload the body force in the Navier-Stokes equations This provides the coupling from the advection-diffusion equations to the Navier--Stokes equations, the body force is the temperature multiplied by the Rayleigh number acting in the direction opposite to gravity.
Reimplemented from oomph::NavierStokesEquations< DIM >.
Definition at line 298 of file boussinesq_elements.h.
References i, oomph::AdvectionDiffusionEquations< DIM >::interpolated_u_adv_diff(), and oomph::BuoyantQCrouzeixRaviartElement< DIM >::ra().
get_wind_adv_diff()
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::get_wind_adv_diff (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const [inline], [virtual]
Overload the wind function in the advection-diffusion equations. This provides the coupling from the Navier--Stokes equations to the advection-diffusion equations because the wind is the fluid velocity.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 283 of file boussinesq_elements.h.
References oomph::NavierStokesEquations< DIM >::interpolated_u_nst().
nscalar_paraview()
template<unsigned DIM>
unsigned oomph::BuoyantQCrouzeixRaviartElement< DIM >::nscalar_paraview () const [inline], [virtual]
Number of scalars/fields output by this element. Broken virtual. Needs to be implemented for each new specific element type. Temporary dummy.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 132 of file boussinesq_elements.h.
output() [1/4]
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::output (FILE * file_pt) [inline], [virtual]
C-style output function: Broken default.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 216 of file boussinesq_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: Broken default.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 222 of file boussinesq_elements.h.
References oomph::FiniteElement::output().
output() [3/4]
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::output (std::ostream & outfile) [inline], [virtual]
Overload the standard output function with the broken default.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 167 of file boussinesq_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function: Output x, y, u, v, p, theta at Nplot^DIM plot points.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 175 of file boussinesq_elements.h.
References oomph::FiniteElement::get_s_plot(), i, oomph::NavierStokesEquations< DIM >::interpolated_p_nst(), oomph::AdvectionDiffusionEquations< DIM >::interpolated_u_adv_diff(), oomph::NavierStokesEquations< DIM >::interpolated_u_nst(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_fct() [1/2]
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::output_fct (std::ostream & outfile, const unsigned & Nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution: Broken default.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 238 of file boussinesq_elements.h.
References oomph::FiniteElement::output_fct().
output_fct() [2/2]
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::output_fct (std::ostream & outfile, const unsigned & Nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: Broken default.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 228 of file boussinesq_elements.h.
References oomph::FiniteElement::output_fct().
ra()
template<unsigned DIM>
const double& oomph::BuoyantQCrouzeixRaviartElement< DIM >::ra () const [inline]
Access function for the Rayleigh number (const version)
Definition at line 102 of file boussinesq_elements.h.
References oomph::BuoyantQCrouzeixRaviartElement< DIM >::Ra_pt.
Referenced by oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), and oomph::BuoyantQCrouzeixRaviartElement< DIM >::get_body_force_nst().
ra_pt()
template<unsigned DIM>
double*& oomph::BuoyantQCrouzeixRaviartElement< DIM >::ra_pt () [inline]
Access function for the pointer to the Rayleigh number.
Definition at line 108 of file boussinesq_elements.h.
References oomph::BuoyantQCrouzeixRaviartElement< DIM >::Ra_pt.
required_nvalue()
template<unsigned DIM>
unsigned oomph::BuoyantQCrouzeixRaviartElement< DIM >::required_nvalue (const unsigned & n) const [inline], [virtual]
The required number of values stored at the nodes is the sum of the required values of the two single-physics elements. Note that this step is generic for any multi-physics element of this type.
Reimplemented from oomph::QCrouzeixRaviartElement< DIM >.
Definition at line 95 of file boussinesq_elements.h.
scalar_name_paraview()
template<unsigned DIM>
std::string oomph::BuoyantQCrouzeixRaviartElement< DIM >::scalar_name_paraview (const unsigned & i) const [inline], [virtual]
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 160 of file boussinesq_elements.h.
References i, and oomph::StringConversion::to_string().
scalar_value_paraview()
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const [inline], [virtual]
Write values of the i-th scalar field at the plot points. Broken virtual. Needs to be implemented for each new specific element type. Temporary dummy.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 146 of file boussinesq_elements.h.
u_index_adv_diff()
template<unsigned DIM>
unsigned oomph::BuoyantQCrouzeixRaviartElement< DIM >::u_index_adv_diff () const [inline], [virtual]
Overload the index at which the temperature variable is stored. We choose to store it after the fluid velocities.
Reimplemented from oomph::AdvectionDiffusionEquations< DIM >.
Definition at line 248 of file boussinesq_elements.h.
Referenced by oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), and oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd().
unfix_pressure()
template<unsigned DIM>
void oomph::BuoyantQCrouzeixRaviartElement< DIM >::unfix_pressure (const unsigned & p_dof) [inline]
Unpin p_dof-th pressure dof.
Definition at line 87 of file boussinesq_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), oomph::QCrouzeixRaviartElement< DIM >::P_nst_internal_index, and oomph::Data::unpin().
Member Data Documentation
Default_Physical_Constant_Value
template<unsigned DIM>
double oomph::BuoyantQCrouzeixRaviartElement< DIM >::Default_Physical_Constant_Value [static], [private]
The static default value of the Rayleigh number.
Definition at line 74 of file boussinesq_elements.h.
Referenced by oomph::BuoyantQCrouzeixRaviartElement< DIM >::BuoyantQCrouzeixRaviartElement().
Ra_pt
template<unsigned DIM>
double* oomph::BuoyantQCrouzeixRaviartElement< DIM >::Ra_pt [private]
Pointer to a private data member, the Rayleigh number.
Definition at line 71 of file boussinesq_elements.h.
Referenced by oomph::BuoyantQCrouzeixRaviartElement< DIM >::BuoyantQCrouzeixRaviartElement(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::ra(), and oomph::BuoyantQCrouzeixRaviartElement< DIM >::ra_pt().
The documentation for this class was generated from the following file:
boussinesq_elements.h