oomph::DiagQHermiteElement< DIM > Class Template Reference
#include <hermite_elements.h>
Public Member Functions
DiagQHermiteElement ()
Constructor.
DiagQHermiteElement (const DiagQHermiteElement &dummy)
Broken copy constructor.
void operator= (const DiagQHermiteElement &)
Broken assignment operator.
Protected Member Functions
double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Overload the template-free interface for the calculation of the inverse jacobian. Pass the dimension of the element to the invert_jacobian function.
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Overload the local to eulerian mapping so that it uses diagonal terms only.
void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
Overload the template-free interface for the transformation of derivatives, so that the diagonal version is used.
void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Overload the template-free interface for the calculation of transformation of second derivatives.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::DiagQHermiteElement< DIM >
These elements are exactly the same as QHermiteElements, but they employ the simplifying assumption that the local and global coordinates are aligned. This makes the evaluation of the derivatives of the shape functions much cheaper.
Definition at line 447 of file hermite_elements.h.
Constructor & Destructor Documentation
DiagQHermiteElement() [1/2]
template<unsigned DIM>
oomph::DiagQHermiteElement< DIM >::DiagQHermiteElement () [inline]
Constructor.
Definition at line 494 of file hermite_elements.h.
DiagQHermiteElement() [2/2]
template<unsigned DIM>
oomph::DiagQHermiteElement< DIM >::DiagQHermiteElement (const DiagQHermiteElement< DIM > & dummy) [inline]
Broken copy constructor.
Definition at line 497 of file hermite_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
invert_jacobian_mapping()
template<unsigned DIM>
double oomph::DiagQHermiteElement< DIM >::invert_jacobian_mapping (const DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const [inline], [protected], [virtual]
Overload the template-free interface for the calculation of the inverse jacobian. Pass the dimension of the element to the invert_jacobian function.
Reimplemented from oomph::QHermiteElement< DIM >.
Definition at line 453 of file hermite_elements.h.
local_to_eulerian_mapping()
template<unsigned DIM>
double oomph::DiagQHermiteElement< DIM >::local_to_eulerian_mapping (const DShape & dpsids, DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const [inline], [protected], [virtual]
Overload the local to eulerian mapping so that it uses diagonal terms only.
Reimplemented from oomph::FiniteElement.
Definition at line 461 of file hermite_elements.h.
References oomph::FiniteElement::local_to_eulerian_mapping_diagonal().
operator=()
template<unsigned DIM>
void oomph::DiagQHermiteElement< DIM >::operator= (const DiagQHermiteElement< DIM > &) [inline]
Broken assignment operator.
Definition at line 503 of file hermite_elements.h.
References oomph::BrokenCopy::broken_assign().
transform_derivatives()
template<unsigned DIM>
void oomph::DiagQHermiteElement< DIM >::transform_derivatives (const DenseMatrix< double > & inverse_jacobian, DShape & dbasis) const [inline], [protected], [virtual]
Overload the template-free interface for the transformation of derivatives, so that the diagonal version is used.
Reimplemented from oomph::FiniteElement.
Definition at line 472 of file hermite_elements.h.
References oomph::FiniteElement::transform_derivatives_diagonal().
transform_second_derivatives()
template<unsigned DIM>
void oomph::DiagQHermiteElement< DIM >::transform_second_derivatives (const DenseMatrix< double > & jacobian, const DenseMatrix< double > & inverse_jacobian, const DenseMatrix< double > & jacobian2, DShape & dbasis, DShape & d2basis) const [inline], [protected], [virtual]
Overload the template-free interface for the calculation of transformation of second derivatives.
Reimplemented from oomph::QHermiteElement< DIM >.
Definition at line 480 of file hermite_elements.h.
The documentation for this class was generated from the following file:
hermite_elements.h