oomph::PMLHelmholtzPowerElement< ELEMENT > Class Template Reference
A class for elements that allow the post-processing of radiated power and flux on the boundaries of PMLHelmholtz elements. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
#include <pml_helmholtz_flux_elements.h>
Public Member Functions
PMLHelmholtzPowerElement (FiniteElement *const &bulk_el_pt, const int &face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to which the element is attached.
PMLHelmholtzPowerElement ()
Broken empty constructor.
PMLHelmholtzPowerElement (const PMLHelmholtzPowerElement &dummy)=delete
Broken copy constructor.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Broken assignment operator.
virtual std::complex< unsigned > u_index_helmholtz () const
Return the index at which the unknown value is stored.
double global_power_contribution ()
Compute the element's contribution to the time-averaged radiated power over the artificial boundary.
double global_power_contribution (std::ofstream &outfile)
Compute the element's contribution to the time-averaged radiated power over the artificial boundary. Also output the power density in the specified output file if it's open.
std::complex< double > global_flux_contribution ()
Compute the element's contribution to the time-averaged flux.
std::complex< double > global_flux_contribution (std::ofstream &outfile)
Compute the element's contribution to the integral of the flux over the artificial boundary. Also output the flux in the specified output file if it's open.
Protected Attributes
std::complex< unsigned > U_index_helmholtz
The index at which the real and imag part of the unknown is stored at the nodes.
unsigned Dim
The spatial dimension of the problem.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::PMLHelmholtzPowerElement< ELEMENT >
A class for elements that allow the post-processing of radiated power and flux on the boundaries of PMLHelmholtz elements. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
Definition at line 51 of file pml_helmholtz_flux_elements.h.
Constructor & Destructor Documentation
PMLHelmholtzPowerElement() [1/3]
template<class ELEMENT >
oomph::PMLHelmholtzPowerElement< ELEMENT >::PMLHelmholtzPowerElement (FiniteElement *const & bulk_el_pt, const int & face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to which the element is attached.
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
Constructor, takes the pointer to the `bulk` element, the index of the fixed local coordinate and its value represented by an integer (+/- 1), indicating that the face is located at the max. or min. value of the `fixed` local coordinate in the bulk element.
Definition at line 394 of file pml_helmholtz_flux_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::PMLHelmholtzPowerElement< ELEMENT >::Dim, oomph::FaceElement::face_index(), oomph::FiniteElement::has_hanging_nodes(), oomph::Node::ndim(), oomph::FiniteElement::node_pt(), oomph::Global_string_for_annotation::string(), oomph::PMLHelmholtzEquations< DIM >::u_index_helmholtz(), and oomph::PMLHelmholtzPowerElement< ELEMENT >::U_index_helmholtz.
PMLHelmholtzPowerElement() [2/3]
template<class ELEMENT >
oomph::PMLHelmholtzPowerElement< ELEMENT >::PMLHelmholtzPowerElement () [inline]
Broken empty constructor.
Definition at line 61 of file pml_helmholtz_flux_elements.h.
PMLHelmholtzPowerElement() [3/3]
template<class ELEMENT >
oomph::PMLHelmholtzPowerElement< ELEMENT >::PMLHelmholtzPowerElement (const PMLHelmholtzPowerElement< ELEMENT > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
global_flux_contribution() [1/2]
template<class ELEMENT >
std::complex< double > oomph::PMLHelmholtzPowerElement< ELEMENT >::global_flux_contribution () [inline]
Compute the element's contribution to the time-averaged flux.
Definition at line 247 of file pml_helmholtz_flux_elements.h.
References oomph::PMLHelmholtzPowerElement< ELEMENT >::global_flux_contribution().
Referenced by oomph::PMLHelmholtzPowerElement< ELEMENT >::global_flux_contribution().
global_flux_contribution() [2/2]
template<class ELEMENT >
std::complex< double > oomph::PMLHelmholtzPowerElement< ELEMENT >::global_flux_contribution (std::ofstream & outfile) [inline]
Compute the element's contribution to the integral of the flux over the artificial boundary. Also output the flux in the specified output file if it's open.
Definition at line 258 of file pml_helmholtz_flux_elements.h.
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::FaceElement::J_eulerian(), oomph::Integral::knot(), oomph::FaceElement::local_coordinate_in_bulk(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), s, oomph::FiniteElement::shape(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
global_power_contribution() [1/2]
template<class ELEMENT >
double oomph::PMLHelmholtzPowerElement< ELEMENT >::global_power_contribution () [inline]
Compute the element's contribution to the time-averaged radiated power over the artificial boundary.
Definition at line 105 of file pml_helmholtz_flux_elements.h.
References oomph::PMLHelmholtzPowerElement< ELEMENT >::global_power_contribution().
Referenced by oomph::PMLHelmholtzPowerElement< ELEMENT >::global_power_contribution().
global_power_contribution() [2/2]
template<class ELEMENT >
double oomph::PMLHelmholtzPowerElement< ELEMENT >::global_power_contribution (std::ofstream & outfile) [inline]
Compute the element's contribution to the time-averaged radiated power over the artificial boundary. Also output the power density in the specified output file if it's open.
Definition at line 116 of file pml_helmholtz_flux_elements.h.
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::FaceElement::J_eulerian(), oomph::Integral::knot(), oomph::FaceElement::local_coordinate_in_bulk(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), s, oomph::FiniteElement::shape(), oomph::PMLHelmholtzPowerElement< ELEMENT >::u_index_helmholtz(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
u_index_helmholtz()
template<class ELEMENT >
virtual std::complex< unsigned > oomph::PMLHelmholtzPowerElement< ELEMENT >::u_index_helmholtz () const [inline], [virtual]
Return the index at which the unknown value is stored.
Definition at line 96 of file pml_helmholtz_flux_elements.h.
References oomph::PMLHelmholtzPowerElement< ELEMENT >::U_index_helmholtz.
Referenced by oomph::PMLHelmholtzPowerElement< ELEMENT >::global_power_contribution().
zeta_nodal()
template<class ELEMENT >
double oomph::PMLHelmholtzPowerElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
Broken assignment operator.
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Reimplemented from oomph::FaceElement.
Definition at line 86 of file pml_helmholtz_flux_elements.h.
References i, and oomph::FaceElement::zeta_nodal().
Member Data Documentation
Dim
template<class ELEMENT >
unsigned oomph::PMLHelmholtzPowerElement< ELEMENT >::Dim [protected]
The spatial dimension of the problem.
Definition at line 378 of file pml_helmholtz_flux_elements.h.
Referenced by oomph::PMLHelmholtzPowerElement< ELEMENT >::PMLHelmholtzPowerElement().
U_index_helmholtz
template<class ELEMENT >
std::complex<unsigned> oomph::PMLHelmholtzPowerElement< ELEMENT >::U_index_helmholtz [protected]
The index at which the real and imag part of the unknown is stored at the nodes.
Definition at line 375 of file pml_helmholtz_flux_elements.h.
Referenced by oomph::PMLHelmholtzPowerElement< ELEMENT >::PMLHelmholtzPowerElement(), and oomph::PMLHelmholtzPowerElement< ELEMENT >::u_index_helmholtz().
The documentation for this class was generated from the following file:
pml_helmholtz_flux_elements.h