oomph::FpPressureAdvectionDiffusionProblem< ELEMENT > Class Template Reference
//////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////
#include <navier_stokes_preconditioners.h>
Public Member Functions
FpPressureAdvectionDiffusionProblem (Mesh *navier_stokes_mesh_pt, Problem *orig_problem_pt)
Constructor: Pass Navier-Stokes mesh and pointer to orig problem.
void get_pressure_advection_diffusion_jacobian (CRDoubleMatrix &jacobian)
Get the pressure advection diffusion Jacobian.
void reset_pin_status ()
Reset pin status of all values.
void pin_all_non_pressure_dofs (const bool &set_pressure_bc_for_validation=false)
Pin all non-pressure dofs and (if boolean flag is set to true also all pressure dofs along domain boundaries -- only used for validation)
void validate (DocInfo &doc_info)
Validate pressure advection diffusion problem and doc exact and computed solution in directory specified in DocInfo object.
void doc_solution (DocInfo &doc_info)
Doc solution (only needed during development -- kept alive in case validation is required during code maintenance)
Private Attributes
unsigned Ndim
The spatial dimension.
Problem * Orig_problem_pt
Pointer to orig problem (required so we can re-assign eqn numbers)
std::map< Data *, std::vector< int > > Eqn_number_backup
Map to store original equation numbers.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >
//////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////
Auxiliary Problem that can be used to assemble the pressure advection diffusion matrix needed by the FpPreconditoner
Definition at line 154 of file navier_stokes_preconditioners.h.
Constructor & Destructor Documentation
FpPressureAdvectionDiffusionProblem()
template<class ELEMENT >
oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::FpPressureAdvectionDiffusionProblem (Mesh * navier_stokes_mesh_pt, Problem * orig_problem_pt) [inline]
Constructor: Pass Navier-Stokes mesh and pointer to orig problem.
Definition at line 158 of file navier_stokes_preconditioners.h.
References oomph::Problem::assembly_handler_pt(), oomph::FiniteElement::dim(), oomph::Mesh::finite_element_pt(), oomph::Problem::mesh_pt(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::Ndim, and oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::Orig_problem_pt.
Member Function Documentation
doc_solution()
template<class ELEMENT >
void oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::doc_solution (DocInfo & doc_info) [inline]
Doc solution (only needed during development -- kept alive in case validation is required during code maintenance)
Definition at line 478 of file navier_stokes_preconditioners.h.
References oomph::DocInfo::directory(), oomph::Mesh::finite_element_pt(), oomph::PressureAdvectionDiffusionValidation::get_exact_u(), oomph::Problem::mesh_pt(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::Ndim, oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::DocInfo::number(), oomph::Mesh::output(), oomph::Mesh::output_fct(), s, and oomph::Data::value_pt().
Referenced by oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::validate().
get_pressure_advection_diffusion_jacobian()
template<class ELEMENT >
void oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::get_pressure_advection_diffusion_jacobian (CRDoubleMatrix & jacobian) [inline]
Get the pressure advection diffusion Jacobian.
Definition at line 178 of file navier_stokes_preconditioners.h.
References oomph::Problem::assign_eqn_numbers(), oomph::Problem::get_jacobian(), oomph::oomph_info, oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::Orig_problem_pt, oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::pin_all_non_pressure_dofs(), and oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::reset_pin_status().
pin_all_non_pressure_dofs()
template<class ELEMENT >
void oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::pin_all_non_pressure_dofs (const bool & set_pressure_bc_for_validation = false) [inline]
Pin all non-pressure dofs and (if boolean flag is set to true also all pressure dofs along domain boundaries -- only used for validation)
Definition at line 257 of file navier_stokes_preconditioners.h.
References e, oomph::Data::eqn_number(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::Eqn_number_backup, oomph::Mesh::finite_element_pt(), i, oomph::Problem::mesh_pt(), oomph::Mesh::nelement(), oomph::Data::nvalue(), oomph::Data::pin(), oomph::Data::set_value(), oomph::PressureAdvectionDiffusionValidation::wind_function(), and oomph::Node::x().
Referenced by oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::get_pressure_advection_diffusion_jacobian(), and oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::validate().
reset_pin_status()
template<class ELEMENT >
void oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::reset_pin_status () [inline]
Reset pin status of all values.
Definition at line 202 of file navier_stokes_preconditioners.h.
References e, oomph::Data::eqn_number(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::Eqn_number_backup, oomph::Mesh::finite_element_pt(), i, oomph::Problem::mesh_pt(), oomph::Mesh::nelement(), oomph::Mesh::nnode(), oomph::Mesh::node_pt(), and oomph::Data::nvalue().
Referenced by oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::get_pressure_advection_diffusion_jacobian(), and oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::validate().
validate()
template<class ELEMENT >
void oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::validate (DocInfo & doc_info) [inline]
Validate pressure advection diffusion problem and doc exact and computed solution in directory specified in DocInfo object.
Definition at line 365 of file navier_stokes_preconditioners.h.
References oomph::Problem::assign_eqn_numbers(), oomph::Mesh::boundary_element_pt(), oomph::TemplateFreeNavierStokesEquationsBase::build_fp_press_adv_diff_robin_bc_element(), oomph::TemplateFreeNavierStokesEquationsBase::delete_pressure_advection_diffusion_robin_elements(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::doc_solution(), e, oomph::Mesh::element_pt(), oomph::Mesh::face_index_at_boundary(), oomph::PressureAdvectionDiffusionValidation::Flag, oomph::Problem::mesh_pt(), oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::Mesh::nelement(), oomph::Problem::newton_solve(), oomph::oomph_info, oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::Orig_problem_pt, oomph::PressureAdvectionDiffusionValidation::Peclet, oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::pin_all_non_pressure_dofs(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::reset_pin_status(), and oomph::PressureAdvectionDiffusionValidation::source_function().
Referenced by oomph::NavierStokesSchurComplementPreconditioner::validate().
Member Data Documentation
Eqn_number_backup
template<class ELEMENT >
std::map<Data*, std::vector<int> > oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::Eqn_number_backup [private]
Map to store original equation numbers.
Definition at line 536 of file navier_stokes_preconditioners.h.
Referenced by oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::pin_all_non_pressure_dofs(), and oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::reset_pin_status().
Ndim
template<class ELEMENT >
unsigned oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::Ndim [private]
The spatial dimension.
Definition at line 529 of file navier_stokes_preconditioners.h.
Referenced by oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::doc_solution(), and oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::FpPressureAdvectionDiffusionProblem().
Orig_problem_pt
template<class ELEMENT >
Problem* oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::Orig_problem_pt [private]
Pointer to orig problem (required so we can re-assign eqn numbers)
Definition at line 533 of file navier_stokes_preconditioners.h.
Referenced by oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::FpPressureAdvectionDiffusionProblem(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::get_pressure_advection_diffusion_jacobian(), and oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::validate().
The documentation for this class was generated from the following file:
navier_stokes_preconditioners.h