oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D > Class Template Reference
Refineable version of 2D QUnsteadyHeatSpaceTimeElement elements.
#include <refineable_space_time_unsteady_heat_elements.h>
Public Member Functions
RefineableQUnsteadyHeatSpaceTimeElement ()
Constructor.
RefineableQUnsteadyHeatSpaceTimeElement (const RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D > &dummy)=delete
Broken copy constructor.
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons (empty)
void further_setup_hanging_nodes ()
Perform additional hanging node procedures for variables that are not interpolated by all nodes (empty).
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: 1.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
RefineableQUnsteadyHeatSpaceTimeElement ()
Constructor.
RefineableQUnsteadyHeatSpaceTimeElement (const RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D > &dummy)=delete
Broken copy constructor.
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons (empty)
void further_setup_hanging_nodes ()
Perform additional hanging node procedures for variables that are not interpolated by all nodes (empty).
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: 1.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Additional Inherited Members
Detailed Description
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
class oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >
Refineable version of 2D QUnsteadyHeatSpaceTimeElement elements.
Definition at line 220 of file refineable_space_time_unsteady_heat_elements.h.
Constructor & Destructor Documentation
RefineableQUnsteadyHeatSpaceTimeElement() [1/4]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::RefineableQUnsteadyHeatSpaceTimeElement () [inline]
Constructor.
Definition at line 227 of file refineable_space_time_unsteady_heat_elements.h.
RefineableQUnsteadyHeatSpaceTimeElement() [2/4]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::RefineableQUnsteadyHeatSpaceTimeElement (const RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D > & dummy) [delete]
Broken copy constructor.
RefineableQUnsteadyHeatSpaceTimeElement() [3/4]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::RefineableQUnsteadyHeatSpaceTimeElement () [inline]
Constructor.
Definition at line 227 of file refineable_discontinuous_galerkin_space_time_unsteady_heat_elements.h.
RefineableQUnsteadyHeatSpaceTimeElement() [4/4]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::RefineableQUnsteadyHeatSpaceTimeElement (const RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
further_setup_hanging_nodes() [1/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
void oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::further_setup_hanging_nodes () [inline], [virtual]
Perform additional hanging node procedures for variables that are not interpolated by all nodes (empty).
Reimplemented from oomph::RefineableElement.
Definition at line 247 of file refineable_space_time_unsteady_heat_elements.h.
further_setup_hanging_nodes() [2/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
void oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::further_setup_hanging_nodes () [inline], [virtual]
Perform additional hanging node procedures for variables that are not interpolated by all nodes (empty).
Reimplemented from oomph::RefineableElement.
Definition at line 247 of file refineable_discontinuous_galerkin_space_time_unsteady_heat_elements.h.
ncont_interpolated_values() [1/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
unsigned oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values: 1.
Implements oomph::RefineableElement.
Definition at line 251 of file refineable_space_time_unsteady_heat_elements.h.
ncont_interpolated_values() [2/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
unsigned oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values: 1.
Implements oomph::RefineableElement.
Definition at line 251 of file refineable_discontinuous_galerkin_space_time_unsteady_heat_elements.h.
nrecovery_order() [1/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
unsigned oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 278 of file refineable_space_time_unsteady_heat_elements.h.
nrecovery_order() [2/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
unsigned oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 278 of file refineable_discontinuous_galerkin_space_time_unsteady_heat_elements.h.
nvertex_node() [1/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
unsigned oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 259 of file refineable_space_time_unsteady_heat_elements.h.
References oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::nvertex_node().
Referenced by oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::nvertex_node().
nvertex_node() [2/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
unsigned oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 259 of file refineable_discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::nvertex_node().
rebuild_from_sons() [1/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
void oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
Rebuild from sons (empty)
Implements oomph::RefineableElement.
Definition at line 242 of file refineable_space_time_unsteady_heat_elements.h.
rebuild_from_sons() [2/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
void oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
Rebuild from sons (empty)
Implements oomph::RefineableElement.
Definition at line 242 of file refineable_discontinuous_galerkin_space_time_unsteady_heat_elements.h.
vertex_node_pt() [1/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
Node * oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 268 of file refineable_space_time_unsteady_heat_elements.h.
References oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::vertex_node_pt().
Referenced by oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::vertex_node_pt().
vertex_node_pt() [2/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
Node * oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 268 of file refineable_discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::vertex_node_pt().
The documentation for this class was generated from the following files:
refineable_space_time_unsteady_heat_elements.h
refineable_discontinuous_galerkin_space_time_unsteady_heat_elements.h