oomph::AxisymmetricPVDEquationsWithPressure Class Reference
A class for elements that solve the equations of solid mechanics, based on the principle of virtual displacements in axisymmetric coordinates in a formulation that allows for incompressibility or near incompressibility.
#include <axisym_solid_elements.h>
Public Member Functions
AxisymmetricPVDEquationsWithPressure ()
Constructor, by default the element is not incompressible.
ConstitutiveLaw *& constitutive_law_pt ()
Return the constitutive law pointer.
void get_stress (const DenseMatrix< double > &g, const DenseMatrix< double > &G, DenseMatrix< double > &sigma, DenseMatrix< double > &Gup, double &pressure_stress, double &kappa)
Return the stress tensor, as calculated from the constitutive law in the Near-incompresible formulation.
void get_stress (const DenseMatrix< double > &g, const DenseMatrix< double > &G, DenseMatrix< double > &sigma, DenseMatrix< double > &Gup, double &detG)
Return the stress tensor, as calculated from the constitutive law in the `true` incompresible formulation.
bool is_incompressible () const
Return whether the material is incompressible.
void set_incompressible ()
Set the material to be incompressible.
void set_compressible ()
Set the material to be compressible.
virtual unsigned nsolid_pres () const =0
Return the number of solid pressure degrees of freedom.
virtual double solid_p (const unsigned &l)=0
Return the lth solid pressures.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Return the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Return the residuals and the jacobian.
void fill_in_generic_residual_contribution_axisym_pvd_with_pressure (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Return the residuals for the equations of solid mechanics formulated in the incompressible case!
double compute_physical_size () const
Overload/implement the size function.
double interpolated_solid_p (const Vector< double > &s)
Return the interpolated_solid_pressure.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
void output (FILE *file_pt)
Overload the output function.
void output (FILE *file_pt, const unsigned &n_plot)
Output function.
Protected Member Functions
virtual int solid_p_local_eqn (const unsigned &i)=0
Access function that returns the local equation number for the n-th solid pressure value.
virtual void solid_pshape (const Vector< double > &s, Shape &psi) const =0
Return the solid pressure shape functions.
void solid_pshape_at_knot (const unsigned &ipt, Shape &psi) const
Return the stored solid shape functions at the knots.
Private Attributes
ConstitutiveLaw * Constitutive_law_pt
Pointer to constitutive law.
bool Incompressible
Boolean to determine whether the solid is incompressible or not.
Additional Inherited Members
Detailed Description
A class for elements that solve the equations of solid mechanics, based on the principle of virtual displacements in axisymmetric coordinates in a formulation that allows for incompressibility or near incompressibility.
Definition at line 660 of file axisym_solid_elements.h.
Constructor & Destructor Documentation
AxisymmetricPVDEquationsWithPressure()
oomph::AxisymmetricPVDEquationsWithPressure::AxisymmetricPVDEquationsWithPressure () [inline]
Constructor, by default the element is not incompressible.
Definition at line 682 of file axisym_solid_elements.h.
Member Function Documentation
compute_physical_size()
double oomph::AxisymmetricPVDEquationsWithPressure::compute_physical_size () const [inline], [virtual]
Overload/implement the size function.
Reimplemented from oomph::FiniteElement.
Definition at line 1132 of file axisym_solid_elements.h.
References oomph::SolidFiniteElement::dshape_lagrangian_at_knot(), i, oomph::FiniteElement::integral_pt(), oomph::SolidFiniteElement::interpolated_xi(), oomph::SolidFiniteElement::lagrangian_position_gen(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position_gen(), oomph::Integral::nweight(), oomph::MathematicalConstants::Pi, oomph::QuadTreeNames::W, and oomph::Integral::weight().
constitutive_law_pt()
ConstitutiveLaw *& oomph::AxisymmetricPVDEquationsWithPressure::constitutive_law_pt () [inline]
Return the constitutive law pointer.
Definition at line 688 of file axisym_solid_elements.h.
References Constitutive_law_pt.
fill_in_contribution_to_jacobian()
void oomph::AxisymmetricPVDEquationsWithPressure::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Return the residuals and the jacobian.
Reimplemented from oomph::GeneralisedElement.
Definition at line 780 of file axisym_solid_elements.h.
References fill_in_generic_residual_contribution_axisym_pvd_with_pressure(), and oomph::SolidFiniteElement::fill_in_jacobian_from_solid_position_by_fd().
fill_in_contribution_to_residuals()
void oomph::AxisymmetricPVDEquationsWithPressure::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Return the residuals.
Reimplemented from oomph::GeneralisedElement.
Definition at line 771 of file axisym_solid_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_axisym_pvd_with_pressure().
fill_in_generic_residual_contribution_axisym_pvd_with_pressure()
void oomph::AxisymmetricPVDEquationsWithPressure::fill_in_generic_residual_contribution_axisym_pvd_with_pressure (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [inline]
Return the residuals for the equations of solid mechanics formulated in the incompressible case!
Definition at line 792 of file axisym_solid_elements.h.
References oomph::SolidFiniteElement::dshape_lagrangian_at_knot(), get_stress(), i, Incompressible, oomph::FiniteElement::integral_pt(), interpolated_solid_p(), oomph::SolidFiniteElement::interpolated_xi(), oomph::SolidFiniteElement::lagrangian_position_gen(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position_gen(), nsolid_pres(), oomph::Integral::nweight(), oomph::SolidFiniteElement::position_local_eqn(), solid_p(), solid_p_local_eqn(), solid_pshape_at_knot(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by fill_in_contribution_to_jacobian(), and fill_in_contribution_to_residuals().
get_stress() [1/2]
void oomph::AxisymmetricPVDEquationsWithPressure::get_stress (const DenseMatrix< double > & g, const DenseMatrix< double > & G, DenseMatrix< double > & sigma, DenseMatrix< double > & Gup, double & detG) [inline]
Return the stress tensor, as calculated from the constitutive law in the `true` incompresible formulation.
Definition at line 722 of file axisym_solid_elements.h.
References oomph::ConstitutiveLaw::calculate_second_piola_kirchhoff_stress(), Constitutive_law_pt, and oomph::Global_string_for_annotation::string().
get_stress() [2/2]
void oomph::AxisymmetricPVDEquationsWithPressure::get_stress (const DenseMatrix< double > & g, const DenseMatrix< double > & G, DenseMatrix< double > & sigma, DenseMatrix< double > & Gup, double & pressure_stress, double & kappa) [inline]
Return the stress tensor, as calculated from the constitutive law in the Near-incompresible formulation.
Definition at line 695 of file axisym_solid_elements.h.
References oomph::ConstitutiveLaw::calculate_second_piola_kirchhoff_stress(), Constitutive_law_pt, and oomph::Global_string_for_annotation::string().
Referenced by fill_in_generic_residual_contribution_axisym_pvd_with_pressure().
interpolated_solid_p()
double oomph::AxisymmetricPVDEquationsWithPressure::interpolated_solid_p (const Vector< double > & s) [inline]
Return the interpolated_solid_pressure.
Definition at line 1236 of file axisym_solid_elements.h.
References interpolated_solid_p(), nsolid_pres(), s, solid_p(), and solid_pshape().
Referenced by fill_in_generic_residual_contribution_axisym_pvd_with_pressure(), interpolated_solid_p(), and output().
is_incompressible()
bool oomph::AxisymmetricPVDEquationsWithPressure::is_incompressible () const [inline]
Return whether the material is incompressible.
Definition at line 747 of file axisym_solid_elements.h.
References Incompressible.
nsolid_pres()
virtual unsigned oomph::AxisymmetricPVDEquationsWithPressure::nsolid_pres () const [pure virtual]
Return the number of solid pressure degrees of freedom.
Implemented in oomph::AxisymQPVDElementWithPressure.
Referenced by fill_in_generic_residual_contribution_axisym_pvd_with_pressure(), and interpolated_solid_p().
output() [1/4]
void oomph::AxisymmetricPVDEquationsWithPressure::output (FILE * file_pt) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::AxisymQPVDElementWithPressure.
Definition at line 1298 of file axisym_solid_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
void oomph::AxisymmetricPVDEquationsWithPressure::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::AxisymQPVDElementWithPressure.
Definition at line 1305 of file axisym_solid_elements.h.
References i, oomph::FiniteElement::interpolated_x(), oomph::SolidFiniteElement::interpolated_xi(), and s.
output() [3/4]
void oomph::AxisymmetricPVDEquationsWithPressure::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::AxisymQPVDElementWithPressure.
Definition at line 1257 of file axisym_solid_elements.h.
References oomph::FiniteElement::output().
Referenced by oomph::AxisymQPVDElementWithPressure::output().
output() [4/4]
void oomph::AxisymmetricPVDEquationsWithPressure::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::AxisymQPVDElementWithPressure.
Definition at line 1263 of file axisym_solid_elements.h.
References i, interpolated_solid_p(), oomph::FiniteElement::interpolated_x(), oomph::SolidFiniteElement::interpolated_xi(), and s.
set_compressible()
void oomph::AxisymmetricPVDEquationsWithPressure::set_compressible () [inline]
Set the material to be compressible.
Definition at line 759 of file axisym_solid_elements.h.
References Incompressible.
set_incompressible()
void oomph::AxisymmetricPVDEquationsWithPressure::set_incompressible () [inline]
Set the material to be incompressible.
Definition at line 753 of file axisym_solid_elements.h.
References Incompressible.
solid_p()
virtual double oomph::AxisymmetricPVDEquationsWithPressure::solid_p (const unsigned & l) [pure virtual]
Return the lth solid pressures.
Implemented in oomph::AxisymQPVDElementWithPressure.
Referenced by fill_in_generic_residual_contribution_axisym_pvd_with_pressure(), and interpolated_solid_p().
solid_p_local_eqn()
virtual int oomph::AxisymmetricPVDEquationsWithPressure::solid_p_local_eqn (const unsigned & i) [protected], [pure virtual]
Access function that returns the local equation number for the n-th solid pressure value.
Implemented in oomph::AxisymQPVDElementWithPressure.
Referenced by fill_in_generic_residual_contribution_axisym_pvd_with_pressure().
solid_pshape()
virtual void oomph::AxisymmetricPVDEquationsWithPressure::solid_pshape (const Vector< double > & s, Shape & psi) const [protected], [pure virtual]
Return the solid pressure shape functions.
Implemented in oomph::AxisymQPVDElementWithPressure.
Referenced by interpolated_solid_p(), and solid_pshape_at_knot().
solid_pshape_at_knot()
void oomph::AxisymmetricPVDEquationsWithPressure::solid_pshape_at_knot (const unsigned & ipt, Shape & psi) const [protected]
Return the stored solid shape functions at the knots.
Solid pressure shape function evaluated at integration point.
Definition at line 35 of file axisym_solid_elements.cc.
References i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), s, and solid_pshape().
Referenced by fill_in_generic_residual_contribution_axisym_pvd_with_pressure().
Member Data Documentation
Constitutive_law_pt
ConstitutiveLaw* oomph::AxisymmetricPVDEquationsWithPressure::Constitutive_law_pt [private]
Pointer to constitutive law.
Definition at line 664 of file axisym_solid_elements.h.
Referenced by constitutive_law_pt(), and get_stress().
Incompressible
bool oomph::AxisymmetricPVDEquationsWithPressure::Incompressible [private]
Boolean to determine whether the solid is incompressible or not.
Definition at line 667 of file axisym_solid_elements.h.
Referenced by fill_in_generic_residual_contribution_axisym_pvd_with_pressure(), is_incompressible(), set_compressible(), and set_incompressible().
The documentation for this class was generated from the following files:
axisym_solid_elements.h
axisym_solid_elements.cc