oomph::FaceElementAsGeomObject< ELEMENT > Class Template Reference
Class that is used to create FaceElement from bulk elements and to provide these FaceElement with a geometric object representation. The local coordinates of the FaceElements are used as the intrinisic coordinates for its GeomObject representation.
#include <face_element_as_geometric_object.h>
Public Member Functions
FaceElementAsGeomObject (FiniteElement *const &element_pt, const int &face_index)
Constructor which takes a pointer to a `bulk` element, to which this element is attached. The face index, indicates the face (of the bulk element) that is to be constructed. Note that this element tends to be constructed by the doubly templated Mesh::build_face_mesh() and therefore has to have the same interface as the the generic FaceElement constructor. Hence the boundary number (within the mesh) on which this element is located must be setup afterwards!
FaceElementAsGeomObject (const FaceElementAsGeomObject &)=delete
Broken copy constructor.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Broken assignment operator.
unsigned ngeom_data () const
How many items of Data does the shape of the object depend on? None! We're dealing with a pure geometric FiniteElement!
Data * geom_data_pt (const unsigned &j)
Return pointer to the j-th Data item that the object's shape depends on. Object doesn't depend on any geom Data so we die if this gets called.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Override fill in contribution to jacobian, nothing should be done.
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the local dofs of the element. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Unique final overrider needed for assign_all_generic_local_eqn_numbers.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::FaceElementAsGeomObject< ELEMENT >
Class that is used to create FaceElement from bulk elements and to provide these FaceElement with a geometric object representation. The local coordinates of the FaceElements are used as the intrinisic coordinates for its GeomObject representation.
These elements are used primarily to set up the interaction terms in FSI problems and are expected to be created from meshes so that they lie on a particular boundary of the mesh.
Definition at line 59 of file face_element_as_geometric_object.h.
Constructor & Destructor Documentation
FaceElementAsGeomObject() [1/2]
template<class ELEMENT >
oomph::FaceElementAsGeomObject< ELEMENT >::FaceElementAsGeomObject (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor which takes a pointer to a `bulk` element, to which this element is attached. The face index, indicates the face (of the bulk element) that is to be constructed. Note that this element tends to be constructed by the doubly templated Mesh::build_face_mesh() and therefore has to have the same interface as the the generic FaceElement constructor. Hence the boundary number (within the mesh) on which this element is located must be setup afterwards!
Definition at line 72 of file face_element_as_geometric_object.h.
References oomph::FiniteElement::build_face_element(), oomph::FiniteElement::dim(), oomph::FaceElement::face_index(), oomph::FiniteElement::nodal_dimension(), and oomph::GeomObject::set_nlagrangian_and_ndim().
FaceElementAsGeomObject() [2/2]
template<class ELEMENT >
oomph::FaceElementAsGeomObject< ELEMENT >::FaceElementAsGeomObject (const FaceElementAsGeomObject< ELEMENT > &) [delete]
Broken copy constructor.
Member Function Documentation
assign_all_generic_local_eqn_numbers()
template<class ELEMENT >
void oomph::FaceElementAsGeomObject< ELEMENT >::assign_all_generic_local_eqn_numbers (const bool & store_local_dof_pt) [inline], [virtual]
Unique final overrider needed for assign_all_generic_local_eqn_numbers.
Reimplemented from oomph::FiniteElement.
Definition at line 168 of file face_element_as_geometric_object.h.
References oomph::FiniteElement::assign_all_generic_local_eqn_numbers().
describe_local_dofs()
template<class ELEMENT >
void oomph::FaceElementAsGeomObject< ELEMENT >::describe_local_dofs (std::ostream & out, const std::string & current_string) const [inline], [virtual]
Function to describe the local dofs of the element. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
Reimplemented from oomph::ElementWithExternalElement.
Definition at line 160 of file face_element_as_geometric_object.h.
References oomph::ElementWithExternalElement::describe_local_dofs().
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::FaceElementAsGeomObject< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Override fill in contribution to jacobian, nothing should be done.
Reimplemented from oomph::ElementWithExternalElement.
Definition at line 135 of file face_element_as_geometric_object.h.
geom_data_pt()
template<class ELEMENT >
Data * oomph::FaceElementAsGeomObject< ELEMENT >::geom_data_pt (const unsigned & j) [inline], [virtual]
Return pointer to the j-th Data item that the object's shape depends on. Object doesn't depend on any geom Data so we die if this gets called.
Reimplemented from oomph::FiniteElement.
Definition at line 122 of file face_element_as_geometric_object.h.
ngeom_data()
template<class ELEMENT >
unsigned oomph::FaceElementAsGeomObject< ELEMENT >::ngeom_data () const [inline], [virtual]
How many items of Data does the shape of the object depend on? None! We're dealing with a pure geometric FiniteElement!
Reimplemented from oomph::FiniteElement.
Definition at line 114 of file face_element_as_geometric_object.h.
zeta_nodal()
template<class ELEMENT >
double oomph::FaceElementAsGeomObject< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
Broken assignment operator.
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default
Reimplemented from oomph::FaceElement.
Definition at line 104 of file face_element_as_geometric_object.h.
References i, and oomph::FaceElement::zeta_nodal().
Referenced by oomph::CompareBoundaryCoordinate< ELEMENT >::operator()().
The documentation for this class was generated from the following file:
face_element_as_geometric_object.h