oomph::PMLFourierDecomposedHelmholtzEquations Class Reference
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
#include <pml_fourier_decomposed_helmholtz_elements.h>
Public Types
typedef void(* PMLFourierDecomposedHelmholtzSourceFctPt) (const Vector< double > &x, std::complex< double > &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
Public Member Functions
PMLFourierDecomposedHelmholtzEquations ()
Constructor.
PMLFourierDecomposedHelmholtzEquations (const PMLFourierDecomposedHelmholtzEquations &dummy)=delete
Broken copy constructor.
virtual std::complex< unsigned > u_index_pml_fourier_decomposed_helmholtz () const
Broken assignment operator.
double *& k_squared_pt ()
Get pointer to frequency.
double k_squared ()
Get k squared.
double *& alpha_pt ()
Get pointer to complex shift.
double alpha ()
Get complex shift.
int *& pml_fourier_wavenumber_pt ()
Get pointer to Fourier wavenumber.
int pml_fourier_wavenumber ()
Get the Fourier wavenumber.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &n_plot)
Output FE representation of soln: x,y,u_re,u_im or x,y,z,u_re,u_im at n_plot^2 plot points.
void output_real (std::ostream &outfile, const double &phi, const unsigned &n_plot)
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. r,z,u at n_plot plot points in each coordinate direction.
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output FE representation of soln: r,z,u_re,u_im or at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: r,z,u_re_exact,u_im_exact at n_plot^2 plot points.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: (dummy time-dependent version to keep intel compiler happy)
void output_real_fct (std::ostream &outfile, const double &phi, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for real part of full time-dependent fct u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. r,z,u at n_plot plot points in each coordinate direction.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
void compute_norm (double &norm)
Compute norm of fe solution.
PMLFourierDecomposedHelmholtzSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
PMLFourierDecomposedHelmholtzSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
virtual void get_source_pml_fourier_decomposed_helmholtz (const unsigned &ipt, const Vector< double > &x, std::complex< double > &source) const
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
void values_to_be_pinned_on_outer_pml_boundary (Vector< unsigned > &values_to_pin)
Pure virtual function in which we specify the values to be pinned (and set to zero) on the outer edge of the pml layer. All of them! Vector is resized internally.
void get_flux (const Vector< double > &s, Vector< std::complex< double > > &flux) const
Get flux: flux[i] = du/dx_i for real and imag part.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and element Jacobian matrix (wrapper)
std::complex< double > interpolated_u_pml_fourier_decomposed_helmholtz (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
unsigned self_test ()
Self-test: Return 0 for OK.
Protected Member Functions
void compute_pml_coefficients (const unsigned &ipt, const Vector< double > &x, Vector< std::complex< double > > &pml_laplace_factor, std::complex< double > &pml_k_squared_factor)
Compute pml coefficients at position x and integration point ipt. pml_laplace_factor is used in the residual contribution from the laplace operator, similarly pml_k_squared_factor is used in the contribution from the k^2 of the Helmholtz operator.
void compute_complex_r (const unsigned &ipt, const Vector< double > &x, std::complex< double > &complex_r)
Compute complex variable r at position x[0] and integration point ipt.
PMLMappingAndTransformedCoordinate *& pml_mapping_and_transformed_coordinate_pt ()
Return a pointer to the PML Mapping object.
PMLMappingAndTransformedCoordinate *const & pml_mapping_and_transformed_coordinate_pt () const
Return a pointer to the PML Mapping object (const version)
virtual double dshape_and_dtest_eulerian_pml_fourier_decomposed_helmholtz (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_pml_fourier_decomposed_helmholtz (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
virtual void fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Protected Attributes
PMLFourierDecomposedHelmholtzSourceFctPt Source_fct_pt
Pointer to source function:
double * K_squared_pt
Pointer to k^2 (wavenumber squared)
PMLMappingAndTransformedCoordinate * Pml_mapping_and_transformed_coordinate_pt
Pointer to class which holds the pml mapping function (also known as gamma) and the associated transformed coordinate.
double * Alpha_pt
Pointer to wavenumber complex shift.
int * N_pml_fourier_pt
Pointer to Fourier wave number.
Static Protected Attributes
static BermudezPMLMappingAndTransformedCoordinate Default_pml_mapping_and_transformed_coordinate
Static so that the class doesn't need to instantiate a new default everytime it uses it.
static double Default_Physical_Constant_Value
Static default value for the physical constants (initialised to zero)
Additional Inherited Members
Detailed Description
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
A class for all isoparametric elements that solve the Helmholtz equations with pml capabilities. in Fourier decomposed form (cylindrical polars):
 U(r,\varphi,z) = \Re( u^{(n)}(r,z) \exp(-i n \varphi)) 
 We are solving for $ u^{(n)}(r,z)$ for given parameters $ k^2 $ and $ n $ . This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
Definition at line 159 of file pml_fourier_decomposed_helmholtz_elements.h.
Member Typedef Documentation
PMLFourierDecomposedHelmholtzSourceFctPt
typedef void(* oomph::PMLFourierDecomposedHelmholtzEquations::PMLFourierDecomposedHelmholtzSourceFctPt) (const Vector< double > &x, std::complex< double > &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
Definition at line 166 of file pml_fourier_decomposed_helmholtz_elements.h.
Constructor & Destructor Documentation
PMLFourierDecomposedHelmholtzEquations() [1/2]
oomph::PMLFourierDecomposedHelmholtzEquations::PMLFourierDecomposedHelmholtzEquations () [inline]
Constructor.
Definition at line 170 of file pml_fourier_decomposed_helmholtz_elements.h.
References Alpha_pt, Default_Physical_Constant_Value, Default_pml_mapping_and_transformed_coordinate, and Pml_mapping_and_transformed_coordinate_pt.
PMLFourierDecomposedHelmholtzEquations() [2/2]
oomph::PMLFourierDecomposedHelmholtzEquations::PMLFourierDecomposedHelmholtzEquations (const PMLFourierDecomposedHelmholtzEquations & dummy) [delete]
Broken copy constructor.
Member Function Documentation
alpha()
double oomph::PMLFourierDecomposedHelmholtzEquations::alpha () [inline]
Get complex shift.
Definition at line 234 of file pml_fourier_decomposed_helmholtz_elements.h.
References Alpha_pt.
alpha_pt()
double *& oomph::PMLFourierDecomposedHelmholtzEquations::alpha_pt () [inline]
Get pointer to complex shift.
Definition at line 227 of file pml_fourier_decomposed_helmholtz_elements.h.
References Alpha_pt.
compute_complex_r()
void oomph::PMLFourierDecomposedHelmholtzEquations::compute_complex_r (const unsigned & ipt, const Vector< double > & x, std::complex< double > & complex_r) [inline], [protected]
Compute complex variable r at position x[0] and integration point ipt.
The complex r variable is only imaginary on two conditions: First, the decaying nature of the pml layers is active. Secondly, the integration point is contained in the right pml layer or the two corner pml layers.
Definition at line 570 of file pml_fourier_decomposed_helmholtz_elements.h.
References k_squared(), oomph::PMLElementBase< 2 >::Pml_direction_active, oomph::PMLElementBase< 2 >::Pml_inner_boundary, oomph::PMLElementBase< 2 >::Pml_is_enabled, Pml_mapping_and_transformed_coordinate_pt, oomph::PMLElementBase< 2 >::Pml_outer_boundary, and oomph::PMLMappingAndTransformedCoordinate::transformed_coordinate().
Referenced by fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz().
compute_error() [1/2]
void oomph::PMLFourierDecomposedHelmholtzEquations::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution.
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 715 of file pml_fourier_decomposed_helmholtz_elements.cc.
References i, oomph::FiniteElement::integral_pt(), interpolated_u_pml_fourier_decomposed_helmholtz(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
compute_error() [2/2]
void oomph::PMLFourierDecomposedHelmholtzEquations::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [inline], [virtual]
Dummy, time dependent error checker.
Reimplemented from oomph::FiniteElement.
Definition at line 330 of file pml_fourier_decomposed_helmholtz_elements.h.
compute_norm()
void oomph::PMLFourierDecomposedHelmholtzEquations::compute_norm (double & norm) [virtual]
Compute norm of fe solution.
Reimplemented from oomph::GeneralisedElement.
Definition at line 795 of file pml_fourier_decomposed_helmholtz_elements.cc.
References i, oomph::FiniteElement::integral_pt(), interpolated_u_pml_fourier_decomposed_helmholtz(), oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
compute_pml_coefficients()
void oomph::PMLFourierDecomposedHelmholtzEquations::compute_pml_coefficients (const unsigned & ipt, const Vector< double > & x, Vector< std::complex< double > > & pml_laplace_factor, std::complex< double > & pml_k_squared_factor) [inline], [protected]
Compute pml coefficients at position x and integration point ipt. pml_laplace_factor is used in the residual contribution from the laplace operator, similarly pml_k_squared_factor is used in the contribution from the k^2 of the Helmholtz operator.
Vector which points from the inner boundary to x
Vector which points from the inner boundary to the edge of the boundary
for 2D, in order: g_y/g_x, g_x/g_y for Laplace bit and g_x*g_y for Helmholtz bit for 3D, in order: g_y*g_x/g_x, g*x*g_z/g_y, g_x*g_y/g_z for Laplace bit and g_x*g_y*g_z for Helmholtz factor
The weights all default to 1.0 as if the propagation medium is the physical domain
Definition at line 502 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::PMLMappingAndTransformedCoordinate::gamma(), k_squared(), oomph::PMLElementBase< 2 >::Pml_direction_active, oomph::PMLElementBase< 2 >::Pml_inner_boundary, oomph::PMLElementBase< 2 >::Pml_is_enabled, Pml_mapping_and_transformed_coordinate_pt, and oomph::PMLElementBase< 2 >::Pml_outer_boundary.
Referenced by fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz().
dshape_and_dtest_eulerian_at_knot_pml_fourier_decomposed_helmholtz()
virtual double oomph::PMLFourierDecomposedHelmholtzEquations::dshape_and_dtest_eulerian_at_knot_pml_fourier_decomposed_helmholtz (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >.
Referenced by fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz().
dshape_and_dtest_eulerian_pml_fourier_decomposed_helmholtz()
virtual double oomph::PMLFourierDecomposedHelmholtzEquations::dshape_and_dtest_eulerian_pml_fourier_decomposed_helmholtz (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >.
fill_in_contribution_to_jacobian()
void oomph::PMLFourierDecomposedHelmholtzEquations::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and element Jacobian matrix (wrapper)
Reimplemented from oomph::FiniteElement.
Definition at line 447 of file pml_fourier_decomposed_helmholtz_elements.h.
References fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz().
fill_in_contribution_to_residuals()
void oomph::PMLFourierDecomposedHelmholtzEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 436 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz().
fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz()
void oomph::PMLFourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected], [virtual]
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Compute element residual Vector and/or element Jacobian matrix.
flag=1: compute both flag=0: compute only residual Vector
Pure version without hanging nodes
Definition at line 191 of file pml_fourier_decomposed_helmholtz_elements.cc.
References compute_complex_r(), compute_pml_coefficients(), dshape_and_dtest_eulerian_at_knot_pml_fourier_decomposed_helmholtz(), get_source_pml_fourier_decomposed_helmholtz(), oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), k_squared(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::Integral::nweight(), pml_fourier_wavenumber(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), u_index_pml_fourier_decomposed_helmholtz(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by fill_in_contribution_to_jacobian(), and fill_in_contribution_to_residuals().
get_flux()
void oomph::PMLFourierDecomposedHelmholtzEquations::get_flux (const Vector< double > & s, Vector< std::complex< double > > & flux) const [inline]
Get flux: flux[i] = du/dx_i for real and imag part.
Definition at line 396 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, and u_index_pml_fourier_decomposed_helmholtz().
Referenced by oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >::get_Z2_flux().
get_source_pml_fourier_decomposed_helmholtz()
virtual void oomph::PMLFourierDecomposedHelmholtzEquations::get_source_pml_fourier_decomposed_helmholtz (const unsigned & ipt, const Vector< double > & x, std::complex< double > & source) const [inline], [virtual]
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
Definition at line 364 of file pml_fourier_decomposed_helmholtz_elements.h.
References Source_fct_pt.
Referenced by fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz().
interpolated_u_pml_fourier_decomposed_helmholtz()
std::complex< double > oomph::PMLFourierDecomposedHelmholtzEquations::interpolated_u_pml_fourier_decomposed_helmholtz (const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s.
Definition at line 458 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and u_index_pml_fourier_decomposed_helmholtz().
Referenced by compute_error(), compute_norm(), output(), and output_real().
k_squared()
double oomph::PMLFourierDecomposedHelmholtzEquations::k_squared () [inline]
Get k squared.
Definition at line 212 of file pml_fourier_decomposed_helmholtz_elements.h.
References K_squared_pt.
Referenced by compute_complex_r(), compute_pml_coefficients(), and fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz().
k_squared_pt()
double *& oomph::PMLFourierDecomposedHelmholtzEquations::k_squared_pt () [inline]
Get pointer to frequency.
Definition at line 205 of file pml_fourier_decomposed_helmholtz_elements.h.
References K_squared_pt.
output() [1/4]
void oomph::PMLFourierDecomposedHelmholtzEquations::output (FILE * file_pt) [inline], [virtual]
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >.
Definition at line 280 of file pml_fourier_decomposed_helmholtz_elements.h.
References output().
output() [2/4]
void oomph::PMLFourierDecomposedHelmholtzEquations::output (FILE * file_pt, const unsigned & nplot) [virtual]
C-style output FE representation of soln: r,z,u_re,u_im or at n_plot^2 plot points.
C-style output function:
r,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >.
Definition at line 565 of file pml_fourier_decomposed_helmholtz_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, interpolated_u_pml_fourier_decomposed_helmholtz(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [3/4]
void oomph::PMLFourierDecomposedHelmholtzEquations::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >.
Definition at line 260 of file pml_fourier_decomposed_helmholtz_elements.h.
References output().
Referenced by output(), oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >::output(), and oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >::output().
output() [4/4]
void oomph::PMLFourierDecomposedHelmholtzEquations::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: x,y,u_re,u_im or x,y,z,u_re,u_im at n_plot^2 plot points.
Output function:
r,z,u_re,u_imag
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >.
Definition at line 489 of file pml_fourier_decomposed_helmholtz_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, interpolated_u_pml_fourier_decomposed_helmholtz(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_fct() [1/2]
virtual void oomph::PMLFourierDecomposedHelmholtzEquations::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output exact soln: (dummy time-dependent version to keep intel compiler happy)
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >.
Definition at line 298 of file pml_fourier_decomposed_helmholtz_elements.h.
output_fct() [2/2]
void oomph::PMLFourierDecomposedHelmholtzEquations::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: r,z,u_re_exact,u_im_exact at n_plot^2 plot points.
Output exact solution.
Solution is provided via function pointer. Plot at a given number of plot points.
r,z,u_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >.
Definition at line 609 of file pml_fourier_decomposed_helmholtz_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
Referenced by oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >::output_fct(), and oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >::output_fct().
output_real()
void oomph::PMLFourierDecomposedHelmholtzEquations::output_real (std::ostream & outfile, const double & phi, const unsigned & nplot)
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. r,z,u at n_plot plot points in each coordinate direction.
Output function for real part of full time-dependent solution.
u = Re((u_r +i u_i) exp(-i omega t)
at phase angle omega t = phi.
r,z,u
Output at nplot points in each coordinate direction
Definition at line 529 of file pml_fourier_decomposed_helmholtz_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, interpolated_u_pml_fourier_decomposed_helmholtz(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
Referenced by oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >::output_real().
output_real_fct()
void oomph::PMLFourierDecomposedHelmholtzEquations::output_real_fct (std::ostream & outfile, const double & phi, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for real part of full time-dependent fct u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. r,z,u at n_plot plot points in each coordinate direction.
Output function for real part of full time-dependent fct.
u = Re((u_r +i u_i) exp(-i omega t)
at phase angle omega t = phi.
r,z,u
Output at nplot points in each coordinate direction
Definition at line 663 of file pml_fourier_decomposed_helmholtz_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
Referenced by oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >::output_real_fct().
pml_fourier_wavenumber()
int oomph::PMLFourierDecomposedHelmholtzEquations::pml_fourier_wavenumber () [inline]
Get the Fourier wavenumber.
Definition at line 246 of file pml_fourier_decomposed_helmholtz_elements.h.
References N_pml_fourier_pt.
Referenced by fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz().
pml_fourier_wavenumber_pt()
int *& oomph::PMLFourierDecomposedHelmholtzEquations::pml_fourier_wavenumber_pt () [inline]
Get pointer to Fourier wavenumber.
Definition at line 240 of file pml_fourier_decomposed_helmholtz_elements.h.
References N_pml_fourier_pt.
pml_mapping_and_transformed_coordinate_pt() [1/2]
PMLMappingAndTransformedCoordinate *& oomph::PMLFourierDecomposedHelmholtzEquations::pml_mapping_and_transformed_coordinate_pt () [inline], [protected]
Return a pointer to the PML Mapping object.
Definition at line 605 of file pml_fourier_decomposed_helmholtz_elements.h.
References Pml_mapping_and_transformed_coordinate_pt.
pml_mapping_and_transformed_coordinate_pt() [2/2]
PMLMappingAndTransformedCoordinate *const & oomph::PMLFourierDecomposedHelmholtzEquations::pml_mapping_and_transformed_coordinate_pt () const [inline], [protected]
Return a pointer to the PML Mapping object (const version)
Definition at line 611 of file pml_fourier_decomposed_helmholtz_elements.h.
References Pml_mapping_and_transformed_coordinate_pt.
self_test()
unsigned oomph::PMLFourierDecomposedHelmholtzEquations::self_test () [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
Definition at line 460 of file pml_fourier_decomposed_helmholtz_elements.cc.
References oomph::FiniteElement::self_test().
source_fct_pt() [1/2]
PMLFourierDecomposedHelmholtzSourceFctPt & oomph::PMLFourierDecomposedHelmholtzEquations::source_fct_pt () [inline]
Access function: Pointer to source function.
Definition at line 347 of file pml_fourier_decomposed_helmholtz_elements.h.
References Source_fct_pt.
source_fct_pt() [2/2]
PMLFourierDecomposedHelmholtzSourceFctPt oomph::PMLFourierDecomposedHelmholtzEquations::source_fct_pt () const [inline]
Access function: Pointer to source function. Const version.
Definition at line 354 of file pml_fourier_decomposed_helmholtz_elements.h.
References Source_fct_pt.
u_index_pml_fourier_decomposed_helmholtz()
virtual std::complex< unsigned > oomph::PMLFourierDecomposedHelmholtzEquations::u_index_pml_fourier_decomposed_helmholtz () const [inline], [virtual]
Broken assignment operator.
Return the index at which the unknown value is stored: Real/imag part of index contains (real) index of real/imag part.
Definition at line 197 of file pml_fourier_decomposed_helmholtz_elements.h.
Referenced by fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz(), get_flux(), interpolated_u_pml_fourier_decomposed_helmholtz(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::PMLFourierDecomposedHelmholtzFluxElement(), and oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::PMLFourierDecomposedHelmholtzPowerMonitorElement().
values_to_be_pinned_on_outer_pml_boundary()
void oomph::PMLFourierDecomposedHelmholtzEquations::values_to_be_pinned_on_outer_pml_boundary (Vector< unsigned > & values_to_pin) [inline], [virtual]
Pure virtual function in which we specify the values to be pinned (and set to zero) on the outer edge of the pml layer. All of them! Vector is resized internally.
Implements oomph::PMLElementBase< 2 >.
Definition at line 384 of file pml_fourier_decomposed_helmholtz_elements.h.
Member Data Documentation
Alpha_pt
double* oomph::PMLFourierDecomposedHelmholtzEquations::Alpha_pt [protected]
Pointer to wavenumber complex shift.
Definition at line 661 of file pml_fourier_decomposed_helmholtz_elements.h.
Referenced by alpha(), alpha_pt(), and PMLFourierDecomposedHelmholtzEquations().
Default_Physical_Constant_Value
double oomph::PMLFourierDecomposedHelmholtzEquations::Default_Physical_Constant_Value [static], [protected]
Initial value:
=
      0.0
Static default value for the physical constants (initialised to zero)
PML Helmholtz equations static data, so that by default we can point to a 0.
Definition at line 664 of file pml_fourier_decomposed_helmholtz_elements.h.
Referenced by PMLFourierDecomposedHelmholtzEquations().
Default_pml_mapping_and_transformed_coordinate
BermudezPMLMappingAndTransformedCoordinate oomph::PMLFourierDecomposedHelmholtzEquations::Default_pml_mapping_and_transformed_coordinate [static], [protected]
Static so that the class doesn't need to instantiate a new default everytime it uses it.
Definition at line 620 of file pml_fourier_decomposed_helmholtz_elements.h.
Referenced by PMLFourierDecomposedHelmholtzEquations().
K_squared_pt
double* oomph::PMLFourierDecomposedHelmholtzEquations::K_squared_pt [protected]
Pointer to k^2 (wavenumber squared)
Definition at line 653 of file pml_fourier_decomposed_helmholtz_elements.h.
Referenced by k_squared(), and k_squared_pt().
N_pml_fourier_pt
int* oomph::PMLFourierDecomposedHelmholtzEquations::N_pml_fourier_pt [protected]
Pointer to Fourier wave number.
Definition at line 667 of file pml_fourier_decomposed_helmholtz_elements.h.
Referenced by pml_fourier_wavenumber(), and pml_fourier_wavenumber_pt().
Pml_mapping_and_transformed_coordinate_pt
PMLMappingAndTransformedCoordinate* oomph::PMLFourierDecomposedHelmholtzEquations::Pml_mapping_and_transformed_coordinate_pt [protected]
Pointer to class which holds the pml mapping function (also known as gamma) and the associated transformed coordinate.
Definition at line 658 of file pml_fourier_decomposed_helmholtz_elements.h.
Referenced by compute_complex_r(), compute_pml_coefficients(), pml_mapping_and_transformed_coordinate_pt(), and PMLFourierDecomposedHelmholtzEquations().
Source_fct_pt
PMLFourierDecomposedHelmholtzSourceFctPt oomph::PMLFourierDecomposedHelmholtzEquations::Source_fct_pt [protected]
Pointer to source function:
Definition at line 650 of file pml_fourier_decomposed_helmholtz_elements.h.
Referenced by get_source_pml_fourier_decomposed_helmholtz(), and source_fct_pt().
The documentation for this class was generated from the following files:
pml_fourier_decomposed_helmholtz_elements.h
pml_fourier_decomposed_helmholtz_elements.cc