oomph::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT > Class Template Reference
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
#include <mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h>
Public Member Functions
FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement (FiniteElement *const &element_pt, const int &face_index, const bool &called_from_refineable_constructor=false)
Constructor, which takes a `bulk` element and the value of the index and its limit. Optional boolean flag indicates if it's called refineable constructor.
~FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement ()
Empty destructor.
virtual void fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
This function returns the residuals for the traction function. flag=1 (or 0): do (or don't) compute the Jacobian as well.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
This function returns just the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the jacobian.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,[z],u,v,[w],p in tecplot format.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
A class for elements that allow the imposition of Robin boundary conditions for the pressure advection diffusion problem in the Fp preconditioner. The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class
Definition at line 81 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
Constructor & Destructor Documentation
FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement()
template<class ELEMENT >
oomph::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement (FiniteElement *const & element_pt, const int & face_index, const bool & called_from_refineable_constructor = false) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit. Optional boolean flag indicates if it's called refineable constructor.
Definition at line 90 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FiniteElement::dim(), oomph::FaceElement::face_index(), and oomph::FiniteElement::has_hanging_nodes().
 FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement()
template<class ELEMENT >
oomph::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >::~FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement () [inline]
Empty destructor.
Definition at line 138 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
This function returns the residuals and the jacobian.
Reimplemented from oomph::FiniteElement.
Definition at line 169 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
This function returns just the residuals.
Reimplemented from oomph::GeneralisedElement.
Definition at line 151 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc()
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [virtual]
This function returns the residuals for the traction function. flag=1 (or 0): do (or don't) compute the Jacobian as well.
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Get residuals and Jacobian of Robin boundary conditions in pressure advection diffusion problem in Fp preconditoner NOTE: Care has to be taken here as fluxes are spatially dependent and not temporally dependent but the template elements are space-time elements!
Implements oomph::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElementBase.
Reimplemented in oomph::RefineableFpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >.
Definition at line 215 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
References i, s, and oomph::W.
output() [1/2]
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Definition at line 188 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
References oomph::FiniteElement::output().
output() [2/2]
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format.
Reimplemented from oomph::FiniteElement.
Definition at line 196 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
References oomph::FiniteElement::output().
The documentation for this class was generated from the following file:
mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h