oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT > Class Template Reference
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
#include <discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h>
Public Member Functions
RefineableNavierStokesSpaceTimeTractionElement (FiniteElement *const &element_pt, const int &face_index)
Constructor, which takes a `bulk` element and the face index.
~RefineableNavierStokesSpaceTimeTractionElement ()
Destructor should not delete anything.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values are the same as those in the bulk element.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
This function returns just the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the Jacobian.
RefineableNavierStokesSpaceTimeTractionElement (FiniteElement *const &element_pt, const int &face_index)
Constructor, which takes a `bulk` element and the face index.
~RefineableNavierStokesSpaceTimeTractionElement ()
Destructor should not delete anything.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values are the same as those in the bulk element.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
This function returns just the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the Jacobian.
RefineableNavierStokesSpaceTimeTractionElement (FiniteElement *const &element_pt, const int &face_index)
Constructor, which takes a `bulk` element and the face index.
~RefineableNavierStokesSpaceTimeTractionElement ()
Destructor should not delete anything.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values are the same as those in the bulk element.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
This function returns just the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the Jacobian.
Protected Member Functions
void refineable_fill_in_generic_residual_contribution_fluid_traction (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
void refineable_fill_in_generic_residual_contribution_fluid_traction (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
void refineable_fill_in_generic_residual_contribution_fluid_traction (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
A class for elements that allow the imposition of an applied traction to the Navier--Stokes equations The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
THIS IS THE REFINEABLE VERSION.
Definition at line 449 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
Constructor & Destructor Documentation
RefineableNavierStokesSpaceTimeTractionElement() [1/3]
template<class ELEMENT >
oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::RefineableNavierStokesSpaceTimeTractionElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the face index.
Definition at line 455 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
 RefineableNavierStokesSpaceTimeTractionElement() [1/3]
template<class ELEMENT >
oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::~RefineableNavierStokesSpaceTimeTractionElement () [inline]
Destructor should not delete anything.
Definition at line 465 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
RefineableNavierStokesSpaceTimeTractionElement() [2/3]
template<class ELEMENT >
oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::RefineableNavierStokesSpaceTimeTractionElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the face index.
Definition at line 455 of file discontinuous_galerkin_spacetime_fluid_traction_elements.h.
 RefineableNavierStokesSpaceTimeTractionElement() [2/3]
template<class ELEMENT >
oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::~RefineableNavierStokesSpaceTimeTractionElement () [inline]
Destructor should not delete anything.
Definition at line 465 of file discontinuous_galerkin_spacetime_fluid_traction_elements.h.
RefineableNavierStokesSpaceTimeTractionElement() [3/3]
template<class ELEMENT >
oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::RefineableNavierStokesSpaceTimeTractionElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the face index.
Definition at line 397 of file spacetime_fluid_traction_elements.h.
 RefineableNavierStokesSpaceTimeTractionElement() [3/3]
template<class ELEMENT >
oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::~RefineableNavierStokesSpaceTimeTractionElement () [inline]
Destructor should not delete anything.
Definition at line 407 of file spacetime_fluid_traction_elements.h.
Member Function Documentation
fill_in_contribution_to_jacobian() [1/3]
template<class ELEMENT >
void oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
This function returns the residuals and the Jacobian.
Reimplemented from oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >.
Definition at line 485 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
References oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction().
fill_in_contribution_to_jacobian() [2/3]
template<class ELEMENT >
void oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
This function returns the residuals and the Jacobian.
Reimplemented from oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >.
Definition at line 485 of file discontinuous_galerkin_spacetime_fluid_traction_elements.h.
References oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction().
fill_in_contribution_to_jacobian() [3/3]
template<class ELEMENT >
void oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
This function returns the residuals and the Jacobian.
Reimplemented from oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >.
Definition at line 427 of file spacetime_fluid_traction_elements.h.
References oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction().
fill_in_contribution_to_residuals() [1/3]
template<class ELEMENT >
void oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
This function returns just the residuals.
Reimplemented from oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >.
Definition at line 477 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction().
fill_in_contribution_to_residuals() [2/3]
template<class ELEMENT >
void oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
This function returns just the residuals.
Reimplemented from oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >.
Definition at line 477 of file discontinuous_galerkin_spacetime_fluid_traction_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction().
fill_in_contribution_to_residuals() [3/3]
template<class ELEMENT >
void oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
This function returns just the residuals.
Reimplemented from oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >.
Definition at line 419 of file spacetime_fluid_traction_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction().
ncont_interpolated_values() [1/3]
template<class ELEMENT >
unsigned oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values are the same as those in the bulk element.
Implements oomph::RefineableElement.
Definition at line 470 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
References oomph::FaceElement::bulk_element_pt().
Referenced by oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::ncont_interpolated_values().
ncont_interpolated_values() [2/3]
template<class ELEMENT >
unsigned oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values are the same as those in the bulk element.
Implements oomph::RefineableElement.
Definition at line 470 of file discontinuous_galerkin_spacetime_fluid_traction_elements.h.
References oomph::FaceElement::bulk_element_pt(), and oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::ncont_interpolated_values().
ncont_interpolated_values() [3/3]
template<class ELEMENT >
unsigned oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values are the same as those in the bulk element.
Implements oomph::RefineableElement.
Definition at line 412 of file spacetime_fluid_traction_elements.h.
References oomph::FaceElement::bulk_element_pt(), and oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::ncont_interpolated_values().
refineable_fill_in_generic_residual_contribution_fluid_traction() [1/3]
template<class ELEMENT >
void oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected]
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Function that returns the residuals for the imposed traction Navier_Stokes equations
Definition at line 512 of file discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h.
References oomph::Multi_domain_functions::Dim, i, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), and oomph::QuadTreeNames::W.
Referenced by oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_residuals().
refineable_fill_in_generic_residual_contribution_fluid_traction() [2/3]
template<class ELEMENT >
void oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected]
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
refineable_fill_in_generic_residual_contribution_fluid_traction() [3/3]
template<class ELEMENT >
void oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected]
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
The documentation for this class was generated from the following files:
discontinuous_galerkin_equal_order_pressure_spacetime_fluid_traction_elements.h
discontinuous_galerkin_spacetime_fluid_traction_elements.h
spacetime_fluid_traction_elements.h