oomph::TemplateFreeNavierStokesEquationsBase Class Reference
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
#include <navier_stokes_elements.h>
Public Member Functions
TemplateFreeNavierStokesEquationsBase ()
Constructor (empty)
virtual ~TemplateFreeNavierStokesEquationsBase ()
Virtual destructor (empty)
virtual void fill_in_pressure_advection_diffusion_residuals (Vector< double > &residuals)=0
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
virtual void fill_in_pressure_advection_diffusion_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)=0
Compute the residuals and Jacobian for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
virtual int p_nodal_index_nst () const =0
Return the index at which the pressure is stored if it is stored at the nodes. If not stored at the nodes this will return a negative number.
virtual int p_local_eqn (const unsigned &n) const =0
Access function for the local equation number information for the pressure. p_local_eqn[n] = local equation number or < 0 if pinned.
virtual int & pinned_fp_pressure_eqn ()=0
Global eqn number of pressure dof that's pinned in pressure adv diff problem.
virtual void pin_all_non_pressure_dofs (std::map< Data *, std::vector< int > > &eqn_number_backup)=0
Pin all non-pressure dofs and backup eqn numbers of all Data.
virtual void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)=0
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
virtual void delete_pressure_advection_diffusion_robin_elements ()=0
Delete the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
virtual void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)=0
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
Additional Inherited Members
Detailed Description
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Template-free base class for Navier-Stokes equations to avoid casting problems
Definition at line 305 of file navier_stokes_elements.h.
Constructor & Destructor Documentation
TemplateFreeNavierStokesEquationsBase()
oomph::TemplateFreeNavierStokesEquationsBase::TemplateFreeNavierStokesEquationsBase () [inline]
Constructor (empty)
Definition at line 311 of file navier_stokes_elements.h.
 TemplateFreeNavierStokesEquationsBase()
virtual oomph::TemplateFreeNavierStokesEquationsBase::~TemplateFreeNavierStokesEquationsBase () [inline], [virtual]
Virtual destructor (empty)
Definition at line 314 of file navier_stokes_elements.h.
Member Function Documentation
build_fp_press_adv_diff_robin_bc_element()
virtual void oomph::TemplateFreeNavierStokesEquationsBase::build_fp_press_adv_diff_robin_bc_element (const unsigned & face_index) [pure virtual]
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Implemented in oomph::QCrouzeixRaviartElement< DIM >, oomph::QTaylorHoodElement< DIM >, oomph::RefineableQTaylorHoodElement< DIM >, oomph::RefineableQCrouzeixRaviartElement< DIM >, oomph::TCrouzeixRaviartElement< DIM >, oomph::TTaylorHoodElement< DIM >, and oomph::NavierStokesEquations< DIM >.
Referenced by oomph::NavierStokesSchurComplementPreconditioner::get_pressure_advection_diffusion_matrix(), and oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::validate().
delete_pressure_advection_diffusion_robin_elements()
virtual void oomph::TemplateFreeNavierStokesEquationsBase::delete_pressure_advection_diffusion_robin_elements () [pure virtual]
Delete the FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Implemented in oomph::NavierStokesEquations< DIM >.
Referenced by oomph::NavierStokesSchurComplementPreconditioner::get_pressure_advection_diffusion_matrix(), and oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::validate().
fill_in_pressure_advection_diffusion_jacobian()
virtual void oomph::TemplateFreeNavierStokesEquationsBase::fill_in_pressure_advection_diffusion_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [pure virtual]
Compute the residuals and Jacobian for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
Implemented in oomph::NavierStokesEquations< DIM >.
fill_in_pressure_advection_diffusion_residuals()
virtual void oomph::TemplateFreeNavierStokesEquationsBase::fill_in_pressure_advection_diffusion_residuals (Vector< double > & residuals) [pure virtual]
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner.
Implemented in oomph::NavierStokesEquations< DIM >.
get_pressure_and_velocity_mass_matrix_diagonal()
virtual void oomph::TemplateFreeNavierStokesEquationsBase::get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > & press_mass_diag, Vector< double > & veloc_mass_diag, const unsigned & which_one = 0) [pure virtual]
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
Implements oomph::NavierStokesElementWithDiagonalMassMatrices.
Implemented in oomph::NavierStokesEquations< DIM >, and oomph::RefineableNavierStokesEquations< DIM >.
p_local_eqn()
virtual int oomph::TemplateFreeNavierStokesEquationsBase::p_local_eqn (const unsigned & n) const [pure virtual]
Access function for the local equation number information for the pressure. p_local_eqn[n] = local equation number or < 0 if pinned.
Implemented in oomph::QCrouzeixRaviartElement< DIM >, oomph::QTaylorHoodElement< DIM >, oomph::TCrouzeixRaviartElement< DIM >, and oomph::TTaylorHoodElement< DIM >.
Referenced by oomph::NavierStokesSchurComplementPreconditioner::get_pressure_advection_diffusion_matrix().
p_nodal_index_nst()
virtual int oomph::TemplateFreeNavierStokesEquationsBase::p_nodal_index_nst () const [pure virtual]
Return the index at which the pressure is stored if it is stored at the nodes. If not stored at the nodes this will return a negative number.
Implemented in oomph::NavierStokesEquations< DIM >, oomph::QTaylorHoodElement< DIM >, and oomph::TTaylorHoodElement< DIM >.
pin_all_non_pressure_dofs()
virtual void oomph::TemplateFreeNavierStokesEquationsBase::pin_all_non_pressure_dofs (std::map< Data *, std::vector< int > > & eqn_number_backup) [pure virtual]
Pin all non-pressure dofs and backup eqn numbers of all Data.
Implemented in oomph::NavierStokesEquations< DIM >.
Referenced by oomph::NavierStokesSchurComplementPreconditioner::pin_all_non_pressure_dofs().
pinned_fp_pressure_eqn()
virtual int & oomph::TemplateFreeNavierStokesEquationsBase::pinned_fp_pressure_eqn () [pure virtual]
Global eqn number of pressure dof that's pinned in pressure adv diff problem.
Implemented in oomph::NavierStokesEquations< DIM >.
Referenced by oomph::NavierStokesSchurComplementPreconditioner::get_pressure_advection_diffusion_matrix().
The documentation for this class was generated from the following file:
navier_stokes_elements.h