oomph::CopiedData Class Reference
Custom Data class that is used when making a shallow copy of a data object. The class contains a copy of an entire other Data object.
#include <nodes.h>
Public Member Functions
void clear_copied_pointers ()
Clear the pointers to the copied data.
CopiedData (Data *const &data_pt)
Constructor.
CopiedData (const Data &data)=delete
(Shallow) copy constructor
void operator= (const CopiedData &)=delete
Broken assignment operator.
~CopiedData ()
Destructor informs original object that the copy is being deleted and clears its pointers to the stored values.
bool is_a_copy () const
Return a boolean to indicate whether the data contains any copied values. Copied data is always a copy.
bool is_a_copy (const unsigned &i) const
Return a boolean to indicate whether the i-th value is a copied value. All copied data is always a copy.
void assign_eqn_numbers (unsigned long &global_ndof, Vector< double * > &dof_pt)
CopiedData is always a copy, so no equation numbers should be allocated. This function just returns.
void resize (const unsigned &n_value)
We cannot resize CopiedData, so the resize function throws a warning.
Private Member Functions
void reset_copied_pointers ()
Reset the pointers to the copied data.
Private Attributes
Data * Copied_data_pt
Pointer to the Data object from which the values are copied.
Additional Inherited Members
Detailed Description
Custom Data class that is used when making a shallow copy of a data object. The class contains a copy of an entire other Data object.
Definition at line 651 of file nodes.h.
Constructor & Destructor Documentation
CopiedData() [1/2]
oomph::CopiedData::CopiedData (Data *const & data_pt)
Constructor.
Constructor, creates a CopiedData object with all values copied from another Data object.
Definition at line 1409 of file nodes.cc.
References oomph::Data::add_copy(), oomph::Data::Eqn_number, oomph::Data::is_a_copy(), and oomph::Data::Value.
CopiedData() [2/2]
oomph::CopiedData::CopiedData (const Data & data) [delete]
(Shallow) copy constructor
 CopiedData()
oomph::CopiedData::~CopiedData () [inline]
Destructor informs original object that the copy is being deleted and clears its pointers to the stored values.
Definition at line 675 of file nodes.h.
References Copied_data_pt, oomph::Data::Eqn_number, oomph::Data::remove_copy(), and oomph::Data::Value.
Member Function Documentation
assign_eqn_numbers()
void oomph::CopiedData::assign_eqn_numbers (unsigned long & global_ndof, Vector< double * > & dof_pt) [inline], [virtual]
CopiedData is always a copy, so no equation numbers should be allocated. This function just returns.
Reimplemented from oomph::Data.
Definition at line 708 of file nodes.h.
clear_copied_pointers()
void oomph::CopiedData::clear_copied_pointers () [virtual]
Clear the pointers to the copied data.
Clear ther pointers to the copied data.
Reimplemented from oomph::Data.
Definition at line 1398 of file nodes.cc.
References Copied_data_pt, oomph::Data::Eqn_number, and oomph::Data::Value.
is_a_copy() [1/2]
bool oomph::CopiedData::is_a_copy () const [inline], [virtual]
Return a boolean to indicate whether the data contains any copied values. Copied data is always a copy.
Reimplemented from oomph::Data.
Definition at line 693 of file nodes.h.
is_a_copy() [2/2]
bool oomph::CopiedData::is_a_copy (const unsigned & i) const [inline], [virtual]
Return a boolean to indicate whether the i-th value is a copied value. All copied data is always a copy.
Reimplemented from oomph::Data.
Definition at line 701 of file nodes.h.
operator=()
void oomph::CopiedData::operator= (const CopiedData &) [delete]
Broken assignment operator.
reset_copied_pointers()
void oomph::CopiedData::reset_copied_pointers () [private], [virtual]
Reset the pointers to the copied data.
///////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////// Reset the pointers to the copied data
Reimplemented from oomph::Data.
Definition at line 1381 of file nodes.cc.
References Copied_data_pt, oomph::Data::Eqn_number, oomph::Data::Nvalue, oomph::Data::nvalue(), and oomph::Data::Value.
resize()
void oomph::CopiedData::resize (const unsigned & n_value) [virtual]
We cannot resize CopiedData, so the resize function throws a warning.
We do not allow Copied Data to be resized.
Reimplemented from oomph::Data.
Definition at line 1438 of file nodes.cc.
Member Data Documentation
Copied_data_pt
Data* oomph::CopiedData::Copied_data_pt [private]
Pointer to the Data object from which the values are copied.
Definition at line 655 of file nodes.h.
Referenced by clear_copied_pointers(), reset_copied_pointers(), and ~CopiedData().
The documentation for this class was generated from the following files:
nodes.h
nodes.cc