oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT > Class Template Reference
//////////////////////////////////////////////////////////////////
#include <fourier_decomposed_helmholtz_bc_elements.h>
Public Member Functions
FourierDecomposedHelmholtzDtNBoundaryElement (FiniteElement *const &bulk_el_pt, const int &face_index)
Construct element from specification of bulk element and face index.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and its Jacobian matrix.
void compute_gamma_contribution (const double &theta, const unsigned &n, std::complex< double > &gamma_con, std::map< unsigned, std::complex< double > > &d_gamma_con)
Compute the contribution of the element to the Gamma integral and its derivates w.r.t to global unknows; the function takes the wavenumber (for gamma integral, not the one from the Fourier decomposition of the Helmholtz equations!) and the polar angle theta as input.
FourierDecomposedHelmholtzDtNMesh< ELEMENT > * outer_boundary_mesh_pt () const
Access function to mesh of all DtN boundary condition elements (needed to get access to gamma values)
void set_outer_boundary_mesh_pt (FourierDecomposedHelmholtzDtNMesh< ELEMENT > *mesh_pt)
Set mesh of all DtN boundary condition elements.
void complete_setup_of_dependencies ()
Complete the setup of additional dependencies arising through the far-away interaction with other nodes in Outer_boundary_mesh_pt.
Private Member Functions
void fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_DtN_bc (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Compute the element's residual vector Jacobian matrix. Overloaded version, using the gamma computed in the mesh.
Private Attributes
FourierDecomposedHelmholtzDtNMesh< ELEMENT > * Outer_boundary_mesh_pt
Pointer to mesh of all DtN boundary condition elements (needed to get access to gamma values)
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >
//////////////////////////////////////////////////////////////////
FaceElement used to apply Sommerfeld radiation conditon via Dirichlet to Neumann map.
Definition at line 420 of file fourier_decomposed_helmholtz_bc_elements.h.
Constructor & Destructor Documentation
FourierDecomposedHelmholtzDtNBoundaryElement()
template<class ELEMENT >
oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::FourierDecomposedHelmholtzDtNBoundaryElement (FiniteElement *const & bulk_el_pt, const int & face_index) [inline]
Construct element from specification of bulk element and face index.
Definition at line 426 of file fourier_decomposed_helmholtz_bc_elements.h.
Member Function Documentation
complete_setup_of_dependencies()
template<class ELEMENT >
void oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::complete_setup_of_dependencies () [inline], [virtual]
Complete the setup of additional dependencies arising through the far-away interaction with other nodes in Outer_boundary_mesh_pt.
Reimplemented from oomph::GeneralisedElement.
Definition at line 482 of file fourier_decomposed_helmholtz_bc_elements.h.
References oomph::GeneralisedElement::add_external_data(), oomph::Node::copied_node_pt(), e, oomph::Data::is_a_copy(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::Outer_boundary_mesh_pt.
compute_gamma_contribution()
template<class ELEMENT >
void oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::compute_gamma_contribution (const double & theta, const unsigned & n, std::complex< double > & gamma_con, std::map< unsigned, std::complex< double > > & d_gamma_con)
Compute the contribution of the element to the Gamma integral and its derivates w.r.t to global unknows; the function takes the wavenumber (for gamma integral, not the one from the Fourier decomposition of the Helmholtz equations!) and the polar angle theta as input.
///////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////
compute the contribution of the element to the Gamma integral and its derivates w.r.t to global unknows; the function takes wavenumber n (from the computation of the gamma integral, not the one from the Fourier decomposition of the Helmholtz equations!) and polar angle theta as input.
Definition at line 771 of file fourier_decomposed_helmholtz_bc_elements.h.
References i, oomph::MathematicalConstants::I(), oomph::Legendre_functions_helper::plgndr2(), and s.
Referenced by oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::setup_gamma().
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and its Jacobian matrix.
Reimplemented from oomph::GeneralisedElement.
Definition at line 444 of file fourier_decomposed_helmholtz_bc_elements.h.
References oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_DtN_bc().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 433 of file fourier_decomposed_helmholtz_bc_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_DtN_bc().
fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_DtN_bc()
template<class ELEMENT >
void oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_DtN_bc (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [inline], [private]
Compute the element's residual vector Jacobian matrix. Overloaded version, using the gamma computed in the mesh.
Definition at line 532 of file fourier_decomposed_helmholtz_bc_elements.h.
References oomph::GeneralisedElement::eqn_number(), oomph::GeneralisedElement::external_local_eqn(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), oomph::GeneralisedElement::nexternal_data(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::Outer_boundary_mesh_pt, s, oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::shape_and_test(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::U_index_fourier_decomposed_helmholtz, oomph::QuadTreeNames::W, oomph::Integral::weight(), and oomph::Node::x().
Referenced by oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::fill_in_contribution_to_residuals().
outer_boundary_mesh_pt()
template<class ELEMENT >
FourierDecomposedHelmholtzDtNMesh< ELEMENT > * oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::outer_boundary_mesh_pt () const [inline]
Access function to mesh of all DtN boundary condition elements (needed to get access to gamma values)
Definition at line 466 of file fourier_decomposed_helmholtz_bc_elements.h.
References oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::Outer_boundary_mesh_pt.
set_outer_boundary_mesh_pt()
template<class ELEMENT >
void oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::set_outer_boundary_mesh_pt (FourierDecomposedHelmholtzDtNMesh< ELEMENT > * mesh_pt) [inline]
Set mesh of all DtN boundary condition elements.
Definition at line 472 of file fourier_decomposed_helmholtz_bc_elements.h.
References oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::Outer_boundary_mesh_pt.
Member Data Documentation
Outer_boundary_mesh_pt
template<class ELEMENT >
FourierDecomposedHelmholtzDtNMesh<ELEMENT>* oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::Outer_boundary_mesh_pt [private]
Pointer to mesh of all DtN boundary condition elements (needed to get access to gamma values)
Definition at line 753 of file fourier_decomposed_helmholtz_bc_elements.h.
Referenced by oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::complete_setup_of_dependencies(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_DtN_bc(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::outer_boundary_mesh_pt(), and oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::set_outer_boundary_mesh_pt().
The documentation for this class was generated from the following file:
fourier_decomposed_helmholtz_bc_elements.h