oomph::HermitePVDElement< DIM > Class Template Reference
An Element that solves the principle of virtual diplacements using Hermite interpolation for the variable positions.
#include <solid_elements.h>
Public Member Functions
HermitePVDElement ()
Constructor, there are no internal data points.
void output (std::ostream &outfile)
SolidQHermiteElement output function.
void output (std::ostream &outfile, const unsigned &n_plot)
SolidQHermiteElement output function.
void output (FILE *file_pt)
C-style SolidQHermiteElement output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style SolidQHermiteElement output function.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::HermitePVDElement< DIM >
An Element that solves the principle of virtual diplacements using Hermite interpolation for the variable positions.
Definition at line 696 of file solid_elements.h.
Constructor & Destructor Documentation
HermitePVDElement()
template<unsigned DIM>
oomph::HermitePVDElement< DIM >::HermitePVDElement () [inline]
Constructor, there are no internal data points.
Definition at line 701 of file solid_elements.h.
Member Function Documentation
output() [1/4]
template<unsigned DIM>
void oomph::HermitePVDElement< DIM >::output (FILE * file_pt) [inline], [virtual]
C-style SolidQHermiteElement output function.
Reimplemented from oomph::SolidQHermiteElement< DIM >.
Definition at line 716 of file solid_elements.h.
References oomph::SolidQHermiteElement< DIM >::output().
output() [2/4]
template<unsigned DIM>
void oomph::HermitePVDElement< DIM >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style SolidQHermiteElement output function.
Reimplemented from oomph::SolidQHermiteElement< DIM >.
Definition at line 722 of file solid_elements.h.
References oomph::SolidQHermiteElement< DIM >::output().
output() [3/4]
template<unsigned DIM>
void oomph::HermitePVDElement< DIM >::output (std::ostream & outfile) [inline], [virtual]
SolidQHermiteElement output function.
Reimplemented from oomph::SolidQHermiteElement< DIM >.
Definition at line 704 of file solid_elements.h.
References oomph::SolidQHermiteElement< DIM >::output().
output() [4/4]
template<unsigned DIM>
void oomph::HermitePVDElement< DIM >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
SolidQHermiteElement output function.
Reimplemented from oomph::SolidQHermiteElement< DIM >.
Definition at line 710 of file solid_elements.h.
References oomph::SolidQHermiteElement< DIM >::output().
The documentation for this class was generated from the following file:
solid_elements.h