oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT > Class Template Reference
A class for elements that allow the imposition of an applied traction to the Navier--Stokes equations The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
#include <mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h>
Public Member Functions
NavierStokesMixedOrderSpaceTimeTractionElement (FiniteElement *const &element_pt, const int &face_index, const bool &called_from_refineable_constructor=false)
Constructor, which takes a `bulk` element and the value of the index and its limit.
~NavierStokesMixedOrderSpaceTimeTractionElement ()
Destructor should not delete anything.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
This function returns just the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the jacobian.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,[z],u,v,[w],p in tecplot format.
Public Attributes
void(*&)(const double &t, const Vector< double > &x, const Vector< double > &n, Vector< double > &result) traction_fct_pt ()
Access function for the imposed traction pointer.
Protected Member Functions
void fill_in_generic_residual_contribution_fluid_traction (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceSpaceTimeElement representation, by default.
virtual int u_local_eqn (const unsigned &n, const unsigned &i)
Access function that returns the local equation numbers for velocity components. u_local_eqn(n,i)=local equation number or < 0 if pinned. The default is to asssume that n is the local node number and the i-th velocity component is the i-th unknown stored at the node.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping.
void get_traction (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
Function to calculate the traction applied to the fluid.
Protected Attributes
unsigned Dim
The highest dimension of the problem.
Private Attributes
void(* Traction_fct_pt)(const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
Pointer to an imposed traction function.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >
A class for elements that allow the imposition of an applied traction to the Navier--Stokes equations The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
Definition at line 51 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
Constructor & Destructor Documentation
NavierStokesMixedOrderSpaceTimeTractionElement()
template<class ELEMENT >
oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::NavierStokesMixedOrderSpaceTimeTractionElement (FiniteElement *const & element_pt, const int & face_index, const bool & called_from_refineable_constructor = false) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit.
Definition at line 65 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FiniteElement::dim(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::Dim, oomph::FaceElement::face_index(), oomph::FiniteElement::has_hanging_nodes(), oomph::Node::ndim(), oomph::FiniteElement::node_pt(), and oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::Traction_fct_pt.
 NavierStokesMixedOrderSpaceTimeTractionElement()
template<class ELEMENT >
oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::~NavierStokesMixedOrderSpaceTimeTractionElement () [inline]
Destructor should not delete anything.
Definition at line 121 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
This function returns the residuals and the jacobian.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >.
Definition at line 146 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
References oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
This function returns just the residuals.
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >.
Definition at line 136 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction().
fill_in_generic_residual_contribution_fluid_traction()
template<class ELEMENT >
void oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected]
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Function that returns the residuals for the imposed traction Navier-Stokes equations
Definition at line 339 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
References oomph::Multi_domain_functions::Dim, i, and oomph::QuadTreeNames::W.
Referenced by oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_residuals().
get_traction()
template<class ELEMENT >
void oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::get_traction (const double & time, const Vector< double > & x, const Vector< double > & n, Vector< double > & result) [inline], [protected]
Function to calculate the traction applied to the fluid.
Definition at line 302 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
References oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::Dim, i, and oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::Traction_fct_pt.
output() [1/2]
template<class ELEMENT >
void oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Definition at line 156 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
References oomph::FiniteElement::output().
output() [2/2]
template<class ELEMENT >
void oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format.
Reimplemented from oomph::FiniteElement.
Definition at line 163 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
References oomph::FiniteElement::output().
shape_and_test_at_knot()
template<class ELEMENT >
double oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping.
Definition at line 200 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
References oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::J_eulerian_at_knot(), oomph::Integral::knot(), oomph::FiniteElement::nnode_1d(), s, oomph::OneDimLagrange::shape< 3 >(), oomph::OneDimDiscontinuousGalerkinMixedOrderBasis::shape< 3 >(), and oomph::OneDimDiscontinuousGalerkinMixedOrderTest::shape< 3 >().
u_local_eqn()
template<class ELEMENT >
virtual int oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::u_local_eqn (const unsigned & n, const unsigned & i) [inline], [protected], [virtual]
Access function that returns the local equation numbers for velocity components. u_local_eqn(n,i)=local equation number or < 0 if pinned. The default is to asssume that n is the local node number and the i-th velocity component is the i-th unknown stored at the node.
Definition at line 193 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
References i, and oomph::FiniteElement::nodal_local_eqn().
zeta_nodal()
template<class ELEMENT >
double oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [protected], [virtual]
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceSpaceTimeElement representation, by default.
Reimplemented from oomph::FaceElement.
Definition at line 180 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
References i, and oomph::FaceElement::zeta_nodal().
Member Data Documentation
Dim
template<class ELEMENT >
unsigned oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::Dim [protected]
The highest dimension of the problem.
Definition at line 327 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
Referenced by oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::get_traction(), and oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::NavierStokesMixedOrderSpaceTimeTractionElement().
traction_fct_pt
template<class ELEMENT >
void(*&)(const double &t, const Vector< double > &x, const Vector< double > &n, Vector< double > &result) oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::traction_fct_pt() [inline]
Access function for the imposed traction pointer.
Definition at line 125 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
Traction_fct_pt
template<class ELEMENT >
void(* oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::Traction_fct_pt) (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result) [private]
Pointer to an imposed traction function.
Definition at line 57 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
Referenced by oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::get_traction(), and oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::NavierStokesMixedOrderSpaceTimeTractionElement().
The documentation for this class was generated from the following file:
mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h