oomph::SolidFaceElement Class Reference
SolidFaceElements combine FaceElements and SolidFiniteElements and overload various functions so they work properly in the FaceElement context.
#include <elements.h>
Public Member Functions
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default This final over-ride is required because both SolidFiniteElements and FaceElements overload zeta_nodal.
double interpolated_xi (const Vector< double > &s, const unsigned &i) const
Return i-th FE-interpolated Lagrangian coordinate xi[i] at local coordinate s. Overloaded from SolidFiniteElement. Note that the Lagrangian coordinates are those defined in the bulk! For instance, in a 1D FaceElement that is aligned with the Lagrangian coordinate line xi_0=const, only xi_1 will vary in the FaceElement. This may confuse you if you (wrongly!) believe that in a 1D SolidElement there should only a single Lagrangian coordinate, namely xi_0!
void interpolated_xi (const Vector< double > &s, Vector< double > &xi) const
Compute FE interpolated Lagrangian coordinate vector xi[] at local coordinate s as Vector. Overloaded from SolidFiniteElement. Note that the Lagrangian coordinates are those defined in the bulk! For instance, in a 1D FaceElement that is aligned with the Lagrangian coordinate line xi_0=const, only xi_1 will vary in the FaceElement. This may confuse you if you (wrongly!) believe that in a 1D SolidElement there should only a single Lagrangian coordinate, namely xi_0!
Additional Inherited Members
Detailed Description
SolidFaceElements combine FaceElements and SolidFiniteElements and overload various functions so they work properly in the FaceElement context.
Definition at line 4940 of file elements.h.
Member Function Documentation
interpolated_xi() [1/2]
double oomph::SolidFaceElement::interpolated_xi (const Vector< double > & s, const unsigned & i) const [inline], [virtual]
Return i-th FE-interpolated Lagrangian coordinate xi[i] at local coordinate s. Overloaded from SolidFiniteElement. Note that the Lagrangian coordinates are those defined in the bulk! For instance, in a 1D FaceElement that is aligned with the Lagrangian coordinate line xi_0=const, only xi_1 will vary in the FaceElement. This may confuse you if you (wrongly!) believe that in a 1D SolidElement there should only a single Lagrangian coordinate, namely xi_0!
Reimplemented from oomph::SolidFiniteElement.
Definition at line 4965 of file elements.h.
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), i, interpolated_xi(), oomph::FaceElement::local_coordinate_in_bulk(), and s.
Referenced by interpolated_xi(), oomph::ClampedHermiteShellBoundaryConditionElement::output(), and oomph::SolidTractionElement< ELEMENT >::output().
interpolated_xi() [2/2]
void oomph::SolidFaceElement::interpolated_xi (const Vector< double > & s, Vector< double > & xi) const [inline], [virtual]
Compute FE interpolated Lagrangian coordinate vector xi[] at local coordinate s as Vector. Overloaded from SolidFiniteElement. Note that the Lagrangian coordinates are those defined in the bulk! For instance, in a 1D FaceElement that is aligned with the Lagrangian coordinate line xi_0=const, only xi_1 will vary in the FaceElement. This may confuse you if you (wrongly!) believe that in a 1D SolidElement there should only a single Lagrangian coordinate, namely xi_0!
Reimplemented from oomph::SolidFiniteElement.
Definition at line 4985 of file elements.h.
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), interpolated_xi(), oomph::FaceElement::local_coordinate_in_bulk(), and s.
zeta_nodal()
double oomph::SolidFaceElement::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default This final over-ride is required because both SolidFiniteElements and FaceElements overload zeta_nodal.
Reimplemented from oomph::SolidFiniteElement.
Definition at line 4949 of file elements.h.
References i, and oomph::FaceElement::zeta_nodal().
Referenced by oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt(), and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error().
The documentation for this class was generated from the following file:
elements.h