oomph::AxisymmetricLinearElasticityEquations Class Reference
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
#include <axisym_linear_elasticity_elements.h>
Public Member Functions
AxisymmetricLinearElasticityEquations ()
Constructor.
unsigned required_nvalue (const unsigned &n) const
Number of values required at node n.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Return the residuals for the equations (the discretised principle of virtual displacements)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
The jacobian is calculated by finite differences by default, We need only to take finite differences w.r.t. positional variables For this element.
void get_strain (const Vector< double > &s, DenseMatrix< double > &strain)
Get strain (3x3 entries; r, z, phi)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact solution: r,z, u_r, u_z, u_theta.
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact solution: r,z, u_r, u_z, u_theta Time dependent version.
void output (std::ostream &outfile)
Output: r,z, u_r, u_z, u_theta.
void output (std::ostream &outfile, const unsigned &n_plot)
Output: r,z, u_r, u_z, u_theta.
void output (FILE *file_pt)
C-style output: r,z, u_r, u_z, u_theta.
void output (FILE *file_pt, const unsigned &n_plot)
Output: r,z, u_r, u_z, u_theta.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of displacement solution over element.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Validate against exact solution. Time-dependent version.
Protected Member Functions
virtual void fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Private helper function to compute residuals and (if requested via flag) also the Jacobian matrix.
Additional Inherited Members
Detailed Description
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
A class for elements that solve the axisymmetric (in cylindrical polars) equations of linear elasticity
Definition at line 432 of file axisym_linear_elasticity_elements.h.
Constructor & Destructor Documentation
AxisymmetricLinearElasticityEquations()
oomph::AxisymmetricLinearElasticityEquations::AxisymmetricLinearElasticityEquations () [inline]
Constructor.
Definition at line 437 of file axisym_linear_elasticity_elements.h.
Member Function Documentation
compute_error() [1/2]
void oomph::AxisymmetricLinearElasticityEquations::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of displacement solution over element.
Validate against exact solution Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Reimplemented from oomph::FiniteElement.
Definition at line 662 of file axisym_linear_elasticity_elements.cc.
References i, oomph::FiniteElement::integral_pt(), oomph::AxisymmetricLinearElasticityEquationsBase::interpolated_u_axisymmetric_linear_elasticity(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::J_eulerian(), s, oomph::W, and oomph::x.
compute_error() [2/2]
void oomph::AxisymmetricLinearElasticityEquations::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [virtual]
Validate against exact solution. Time-dependent version.
Validate against exact solution Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Reimplemented from oomph::FiniteElement.
Definition at line 744 of file axisym_linear_elasticity_elements.cc.
References i, oomph::FiniteElement::integral_pt(), oomph::AxisymmetricLinearElasticityEquationsBase::interpolated_u_axisymmetric_linear_elasticity(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::J_eulerian(), s, oomph::W, and oomph::x.
fill_in_contribution_to_jacobian()
void oomph::AxisymmetricLinearElasticityEquations::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
The jacobian is calculated by finite differences by default, We need only to take finite differences w.r.t. positional variables For this element.
Reimplemented from oomph::GeneralisedElement.
Definition at line 457 of file axisym_linear_elasticity_elements.h.
References oomph::FiniteElement::jacobian.
fill_in_contribution_to_residuals()
void oomph::AxisymmetricLinearElasticityEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Return the residuals for the equations (the discretised principle of virtual displacements)
Reimplemented from oomph::GeneralisedElement.
Definition at line 447 of file axisym_linear_elasticity_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity().
fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity()
void oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [protected], [virtual]
Private helper function to compute residuals and (if requested via flag) also the Jacobian matrix.
Compute the residuals for the axisymmetric (in cyl. polars) linear elasticity equations in. Flag indicates if we want Jacobian too.
Definition at line 162 of file axisym_linear_elasticity_elements.cc.
References oomph::AxisymmetricLinearElasticityEquationsBase::body_force(), oomph::AxisymmetricLinearElasticityEquationsBase::d2u_dt2_axisymmetric_linear_elasticity(), oomph::FiniteElement::dshape_eulerian_at_knot(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::jacobian, oomph::AxisymmetricLinearElasticityEquationsBase::lambda_sq(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), oomph::AxisymmetricLinearElasticityEquationsBase::nu(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), s, oomph::AxisymmetricLinearElasticityEquationsBase::u_index_axisymmetric_linear_elasticity(), oomph::W, and oomph::AxisymmetricLinearElasticityEquationsBase::youngs_modulus().
Referenced by fill_in_contribution_to_residuals().
get_strain()
void oomph::AxisymmetricLinearElasticityEquations::get_strain (const Vector< double > & s, DenseMatrix< double > & strain)
Get strain (3x3 entries; r, z, phi)
/////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////
Get strain (3x3 entries; r, z, phi)
Definition at line 55 of file axisym_linear_elasticity_elements.cc.
References i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), and oomph::AxisymmetricLinearElasticityEquationsBase::u_index_axisymmetric_linear_elasticity().
Referenced by oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >::get_Z2_flux().
output() [1/4]
void oomph::AxisymmetricLinearElasticityEquations::output (FILE * file_pt) [inline], [virtual]
C-style output: r,z, u_r, u_z, u_theta.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QAxisymmetricLinearElasticityElement< NNODE_1D >, and oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >.
Definition at line 493 of file axisym_linear_elasticity_elements.h.
References output().
output() [2/4]
void oomph::AxisymmetricLinearElasticityEquations::output (FILE * file_pt, const unsigned & n_plot) [virtual]
Output: r,z, u_r, u_z, u_theta.
C-style output:r,z, u_r, u_z, u_theta.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QAxisymmetricLinearElasticityElement< NNODE_1D >, and oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >.
Definition at line 620 of file axisym_linear_elasticity_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, oomph::AxisymmetricLinearElasticityEquationsBase::interpolated_u_axisymmetric_linear_elasticity(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [3/4]
void oomph::AxisymmetricLinearElasticityEquations::output (std::ostream & outfile) [inline], [virtual]
Output: r,z, u_r, u_z, u_theta.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QAxisymmetricLinearElasticityElement< NNODE_1D >, and oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >.
Definition at line 483 of file axisym_linear_elasticity_elements.h.
References output().
Referenced by output(), oomph::QAxisymmetricLinearElasticityElement< NNODE_1D >::output(), and oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >::output().
output() [4/4]
void oomph::AxisymmetricLinearElasticityEquations::output (std::ostream & outfile, const unsigned & n_plot) [virtual]
Output: r,z, u_r, u_z, u_theta.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QAxisymmetricLinearElasticityElement< NNODE_1D >, and oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >.
Definition at line 558 of file axisym_linear_elasticity_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, oomph::AxisymmetricLinearElasticityEquationsBase::interpolated_d2u_dt2_axisymmetric_linear_elasticity(), oomph::AxisymmetricLinearElasticityEquationsBase::interpolated_du_dt_axisymmetric_linear_elasticity(), oomph::AxisymmetricLinearElasticityEquationsBase::interpolated_u_axisymmetric_linear_elasticity(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), oomph::u, oomph::FiniteElement::write_tecplot_zone_footer(), and oomph::x.
output_fct() [1/2]
void oomph::AxisymmetricLinearElasticityEquations::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact solution: r,z, u_r, u_z, u_theta Time dependent version.
Output exact solution r,z, u_r, u_z, u_theta Time dependent version.
Reimplemented from oomph::FiniteElement.
Definition at line 507 of file axisym_linear_elasticity_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), oomph::FiniteElement::write_tecplot_zone_footer(), and oomph::x.
output_fct() [2/2]
void oomph::AxisymmetricLinearElasticityEquations::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact solution: r,z, u_r, u_z, u_theta.
Output exact solution r,z, u_r, u_z, u_theta.
Reimplemented from oomph::FiniteElement.
Definition at line 456 of file axisym_linear_elasticity_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), oomph::FiniteElement::write_tecplot_zone_footer(), and oomph::x.
required_nvalue()
unsigned oomph::AxisymmetricLinearElasticityEquations::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values required at node n.
Reimplemented from oomph::FiniteElement.
Definition at line 440 of file axisym_linear_elasticity_elements.h.
The documentation for this class was generated from the following files:
axisym_linear_elasticity_elements.h
axisym_linear_elasticity_elements.cc