oomph::QTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D > Class Template Reference
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
#include <time_harmonic_fourier_decomposed_linear_elasticity_elements.h>
Public Member Functions
QTimeHarmonicFourierDecomposedLinearElasticityElement ()
Constructor.
void output (std::ostream &outfile)
Output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
void output (FILE *file_pt)
C-style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function.
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::QTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
An Element that solves the equations of Fourier decomposed (in cylindrical polars) time-harmonic linear elasticity, using QElements for the geometry.
Definition at line 445 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
Constructor & Destructor Documentation
QTimeHarmonicFourierDecomposedLinearElasticityElement()
template<unsigned NNODE_1D>
oomph::QTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >::QTimeHarmonicFourierDecomposedLinearElasticityElement () [inline]
Constructor.
Definition at line 451 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
Member Function Documentation
output() [1/4]
template<unsigned NNODE_1D>
void oomph::QTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function.
Reimplemented from oomph::QElement< 2, NNODE_1D >.
Definition at line 472 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output().
output() [2/4]
template<unsigned NNODE_1D>
void oomph::QTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function.
Reimplemented from oomph::QElement< 2, NNODE_1D >.
Definition at line 478 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output().
output() [3/4]
template<unsigned NNODE_1D>
void oomph::QTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function.
Reimplemented from oomph::QElement< 2, NNODE_1D >.
Definition at line 458 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output().
output() [4/4]
template<unsigned NNODE_1D>
void oomph::QTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function.
Reimplemented from oomph::QElement< 2, NNODE_1D >.
Definition at line 464 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output().
The documentation for this class was generated from the following file:
time_harmonic_fourier_decomposed_linear_elasticity_elements.h