oomph::C1CurvedElement< 2, NNODE_1D > Class Template Reference
C1CurvedElement elements, specialised to two spatial dimensions.
#include <Subparametric_Telements.h>
Public Member Functions
C1CurvedElement ()
Constructor: Call constructors for C1CurvedElement.
C1CurvedElement (const C1CurvedElement &)
Broken copy constructor.
void operator= (const C1CurvedElement &)
Broken assignment operator.
~C1CurvedElement ()
Destructor.
unsigned nnode_1d () const
Number of nodes along each element edge.
unsigned nvertex_node () const
Number of vertex nodes in the element: One more than spatial dimension.
unsigned ninternal_node () const
Number of internal nodes.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void classify_boundary_node (DenseMatrix< double > &node_position, unsigned &bd_element, DenseMatrix< double > &bd_node_position, Vector< double > &x) const
void get_value_transform_matrix (DenseMatrix< double > &D, DenseMatrix< double > &B, DenseMatrix< double > &node_position, unsigned &bd_element, DenseMatrix< double > &bd_node_position, Vector< double > &x) const
void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
Return local coordinates of node j.
void basis_straight (const Vector< double > &s, Shape &psi) const
void dbasis_local_straight (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Compute the c1-shape functions associated with a straight-sided boundary and derivatives w.r.t. global coordinates at local coordinate s.
void d2basis_local_straight (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
Compute the c1-shape functions associated with a straight-sided boundary and derivatives w.r.t. global coordinates at local coordinate s.
void basis_curve (const Vector< double > &s, Shape &psi) const
void dbasis_local_curve (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Compute the c1-shape functions associated with a curved-sided boundary and derivatives w.r.t. local coordinates at local coordinate s.
void d2basis_local_curve (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
Compute the c1-shape functions associated with a curved-sided boundary and derivatives w.r.t. local coordinates at local coordinate s.
void shape_geom (const Vector< double > &s, Shape &psi, Shape &phi) const
Calculate the linear shape functions at local coordinate s.
void dshape_local_geom (const Vector< double > &s, Shape &psi, DShape &dpsids, Shape &phi, DShape &dphids) const
Compute the linear functions and derivatives w.r.t. local coordinates at local coordinate s.
void d2shape_local_geom (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids, Shape &phi, DShape &dphids, DShape &d2phids) const
Compute the linear functions and derivatives w.r.t. local coordinates at local coordinate s.
void basis_c0 (const Vector< double > &s, Shape &psi) const
Calculate the c0-shape functions at local coordinate s.
void dbasis_c0_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Compute the c0-shape functions and derivatives w.r.t. local coordinates at local coordinate s.
void d2basis_c0_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
Computer the c0-shape functions, derivatives and second derivatives w.r.t local coordinates at local coordinate s
d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $
d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $
d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $
.
void test (const Vector< double > &s, Shape &psi) const
Calculate the test functions at local coordinate s.
void dtest_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Compute the test functions and derivatives w.r.t. local coordinates at local coordinate s.
void d2test_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
Computer the geometric shape functions, derivatives and second derivatives w.r.t local coordinates at local coordinate s
d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $
d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $
d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $
.
void build_face_element (const int &face_index, FaceElement *face_element_pt)
Build the lower-dimensional FaceElement (an element of type SolidTElement<1,NNODE_1D>). The face index takes three possible values: 0 (Left) s[0] = 0.0 1 (Bottom) s[1] = 0.0 2 (Sloping face) s[0] = 1.0 - s[1].
Static Private Attributes
static const unsigned NodeOnFace [3][NNODE_1D]
Nodal translation scheme for use when generating face elements.
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::C1CurvedElement< 2, NNODE_1D >
C1CurvedElement elements, specialised to two spatial dimensions.
Definition at line 7208 of file Subparametric_Telements.h.
Constructor & Destructor Documentation
C1CurvedElement() [1/2]
template<unsigned NNODE_1D>
oomph::C1CurvedElement< 2, NNODE_1D >::C1CurvedElement () [inline]
Constructor: Call constructors for C1CurvedElement.
Definition at line 7221 of file Subparametric_Telements.h.
References oomph::Global_string_for_annotation::string().
C1CurvedElement() [2/2]
template<unsigned NNODE_1D>
oomph::C1CurvedElement< 2, NNODE_1D >::C1CurvedElement (const C1CurvedElement< 2, NNODE_1D > &) [inline]
Broken copy constructor.
Definition at line 7258 of file Subparametric_Telements.h.
References oomph::BrokenCopy::broken_copy().
 C1CurvedElement()
template<unsigned NNODE_1D>
oomph::C1CurvedElement< 2, NNODE_1D >::~C1CurvedElement () [inline]
Destructor.
Definition at line 7269 of file Subparametric_Telements.h.
Member Function Documentation
basis_c0()
template<unsigned NNODE_1D>
void oomph::C1CurvedElement< 2, NNODE_1D >::basis_c0 (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Calculate the c0-shape functions at local coordinate s.
Reimplemented from oomph::C1CurvedElementBase< NNODE_1D >.
Definition at line 7536 of file Subparametric_Telements.h.
References s, and oomph::OneDimLagrange::shape().
basis_curve()
template<unsigned NNODE_1D>
void oomph::C1CurvedElement< 2, NNODE_1D >::basis_curve (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Calculate the c1-shape functions associated with a curved-sided boundary at local coordinate s
Reimplemented from oomph::C1CurvedElementBase< NNODE_1D >.
Definition at line 7440 of file Subparametric_Telements.h.
References s.
basis_straight()
template<unsigned NNODE_1D>
void oomph::C1CurvedElement< 2, NNODE_1D >::basis_straight (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Calculate the c1-shape functions associated with a straight-sided boundary at local coordinate s classify nodes in the element
Reimplemented from oomph::C1CurvedElementBase< NNODE_1D >.
Definition at line 7395 of file Subparametric_Telements.h.
References s.
build_face_element()
template<unsigned NNODE_1D>
void oomph::C1CurvedElement< 2, NNODE_1D >::build_face_element (const int & face_index, FaceElement * face_element_pt) [virtual]
Build the lower-dimensional FaceElement (an element of type SolidTElement<1,NNODE_1D>). The face index takes three possible values: 0 (Left) s[0] = 0.0 1 (Bottom) s[1] = 0.0 2 (Sloping face) s[0] = 1.0 - s[1].
Function to setup geometrical information for lower-dimensional FaceElements (which are of type TElement<1,NNODE_1D>).
Reimplemented from oomph::FiniteElement.
Definition at line 7605 of file Subparametric_Telements.h.
classify_boundary_node()
template<unsigned NNODE_1D>
void oomph::C1CurvedElement< 2, NNODE_1D >::classify_boundary_node (DenseMatrix< double > & node_position, unsigned & bd_element, DenseMatrix< double > & bd_node_position, Vector< double > & x) const [inline], [virtual]
Number of nodes along each element edge: Just for the three vertices not the internal points
Loop over vertices
Reimplemented from oomph::C1CurvedElementBase< NNODE_1D >.
Definition at line 7310 of file Subparametric_Telements.h.
References i.
d2basis_c0_local()
template<unsigned NNODE_1D>
void oomph::C1CurvedElement< 2, NNODE_1D >::d2basis_c0_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline], [virtual]
Computer the c0-shape functions, derivatives and second derivatives w.r.t local coordinates at local coordinate s
d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $
d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $
d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $
.
Reimplemented from oomph::C1CurvedElementBase< NNODE_1D >.
Definition at line 7555 of file Subparametric_Telements.h.
References s.
d2basis_local_curve()
template<unsigned NNODE_1D>
void oomph::C1CurvedElement< 2, NNODE_1D >::d2basis_local_curve (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline], [virtual]
Compute the c1-shape functions associated with a curved-sided boundary and derivatives w.r.t. local coordinates at local coordinate s.
Reimplemented from oomph::C1CurvedElementBase< NNODE_1D >.
Definition at line 7456 of file Subparametric_Telements.h.
References s.
d2basis_local_straight()
template<unsigned NNODE_1D>
void oomph::C1CurvedElement< 2, NNODE_1D >::d2basis_local_straight (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline], [virtual]
Compute the c1-shape functions associated with a straight-sided boundary and derivatives w.r.t. global coordinates at local coordinate s.
classify nodes in the element
Reimplemented from oomph::C1CurvedElementBase< NNODE_1D >.
Definition at line 7423 of file Subparametric_Telements.h.
References s.
d2shape_local_geom()
template<unsigned NNODE_1D>
void oomph::C1CurvedElement< 2, NNODE_1D >::d2shape_local_geom (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids, Shape & phi, DShape & dphids, DShape & d2phids) const [inline], [virtual]
Compute the linear functions and derivatives w.r.t. local coordinates at local coordinate s.
classify nodes in the element
Reimplemented from oomph::C1CurvedElementBase< NNODE_1D >.
Definition at line 7508 of file Subparametric_Telements.h.
References s.
d2test_local()
template<unsigned NNODE_1D>
void oomph::C1CurvedElement< 2, NNODE_1D >::d2test_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline], [virtual]
Computer the geometric shape functions, derivatives and second derivatives w.r.t local coordinates at local coordinate s
d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $
d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $
d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $
.
Reimplemented from oomph::C1CurvedElementBase< NNODE_1D >.
Definition at line 7583 of file Subparametric_Telements.h.
References s.
dbasis_c0_local()
template<unsigned NNODE_1D>
void oomph::C1CurvedElement< 2, NNODE_1D >::dbasis_c0_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const [inline], [virtual]
Compute the c0-shape functions and derivatives w.r.t. local coordinates at local coordinate s.
Reimplemented from oomph::C1CurvedElementBase< NNODE_1D >.
Definition at line 7543 of file Subparametric_Telements.h.
References s.
dbasis_local_curve()
template<unsigned NNODE_1D>
void oomph::C1CurvedElement< 2, NNODE_1D >::dbasis_local_curve (const Vector< double > & s, Shape & psi, DShape & dpsids) const [inline], [virtual]
Compute the c1-shape functions associated with a curved-sided boundary and derivatives w.r.t. local coordinates at local coordinate s.
Reimplemented from oomph::C1CurvedElementBase< NNODE_1D >.
Definition at line 7447 of file Subparametric_Telements.h.
References s.
dbasis_local_straight()
template<unsigned NNODE_1D>
void oomph::C1CurvedElement< 2, NNODE_1D >::dbasis_local_straight (const Vector< double > & s, Shape & psi, DShape & dpsids) const [inline], [virtual]
Compute the c1-shape functions associated with a straight-sided boundary and derivatives w.r.t. global coordinates at local coordinate s.
classify nodes in the element
Reimplemented from oomph::C1CurvedElementBase< NNODE_1D >.
Definition at line 7408 of file Subparametric_Telements.h.
References s.
dshape_local_geom()
template<unsigned NNODE_1D>
void oomph::C1CurvedElement< 2, NNODE_1D >::dshape_local_geom (const Vector< double > & s, Shape & psi, DShape & dpsids, Shape & phi, DShape & dphids) const [inline], [virtual]
Compute the linear functions and derivatives w.r.t. local coordinates at local coordinate s.
classify nodes in the element
Reimplemented from oomph::C1CurvedElementBase< NNODE_1D >.
Definition at line 7483 of file Subparametric_Telements.h.
References s.
dtest_local()
template<unsigned NNODE_1D>
void oomph::C1CurvedElement< 2, NNODE_1D >::dtest_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const [inline], [virtual]
Compute the test functions and derivatives w.r.t. local coordinates at local coordinate s.
Reimplemented from oomph::C1CurvedElementBase< NNODE_1D >.
Definition at line 7571 of file Subparametric_Telements.h.
References s.
get_value_transform_matrix()
template<unsigned NNODE_1D>
void oomph::C1CurvedElement< 2, NNODE_1D >::get_value_transform_matrix (DenseMatrix< double > & D, DenseMatrix< double > & B, DenseMatrix< double > & node_position, unsigned & bd_element, DenseMatrix< double > & bd_node_position, Vector< double > & x) const [inline], [virtual]
classify nodes in the element
compute the set of value of degree of freedom
Reimplemented from oomph::C1CurvedElementBase< NNODE_1D >.
Definition at line 7371 of file Subparametric_Telements.h.
References oomph::OcTreeNames::B, and oomph::OcTreeNames::D.
local_coordinate_of_node()
template<unsigned NNODE_1D>
void oomph::C1CurvedElement< 2, NNODE_1D >::local_coordinate_of_node (const unsigned & j, Vector< double > & s) const [inline], [virtual]
Return local coordinates of node j.
Reimplemented from oomph::FiniteElement.
Definition at line 7387 of file Subparametric_Telements.h.
References s.
ninternal_node()
template<unsigned NNODE_1D>
unsigned oomph::C1CurvedElement< 2, NNODE_1D >::ninternal_node () const [inline]
Number of internal nodes.
Definition at line 7285 of file Subparametric_Telements.h.
nnode_1d()
template<unsigned NNODE_1D>
unsigned oomph::C1CurvedElement< 2, NNODE_1D >::nnode_1d () const [inline], [virtual]
Number of nodes along each element edge.
Reimplemented from oomph::FiniteElement.
Definition at line 7272 of file Subparametric_Telements.h.
nvertex_node()
template<unsigned NNODE_1D>
unsigned oomph::C1CurvedElement< 2, NNODE_1D >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element: One more than spatial dimension.
Reimplemented from oomph::FiniteElement.
Definition at line 7279 of file Subparametric_Telements.h.
operator=()
template<unsigned NNODE_1D>
void oomph::C1CurvedElement< 2, NNODE_1D >::operator= (const C1CurvedElement< 2, NNODE_1D > &) [inline]
Broken assignment operator.
Definition at line 7264 of file Subparametric_Telements.h.
References oomph::BrokenCopy::broken_assign().
shape_geom()
template<unsigned NNODE_1D>
void oomph::C1CurvedElement< 2, NNODE_1D >::shape_geom (const Vector< double > & s, Shape & psi, Shape & phi) const [inline], [virtual]
Calculate the linear shape functions at local coordinate s.
classify nodes in the element
Reimplemented from oomph::C1CurvedElementBase< NNODE_1D >.
Definition at line 7466 of file Subparametric_Telements.h.
References s.
test()
template<unsigned NNODE_1D>
void oomph::C1CurvedElement< 2, NNODE_1D >::test (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Calculate the test functions at local coordinate s.
Reimplemented from oomph::C1CurvedElementBase< NNODE_1D >.
Definition at line 7564 of file Subparametric_Telements.h.
References s, and oomph::OneDimLagrange::shape().
vertex_node_pt()
template<unsigned NNODE_1D>
Node* oomph::C1CurvedElement< 2, NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Reimplemented from oomph::FiniteElement.
Definition at line 7291 of file Subparametric_Telements.h.
Member Data Documentation
NodeOnFace
template<unsigned NNODE_1D>
const unsigned oomph::C1CurvedElement< 2, NNODE_1D >::NodeOnFace[3][NNODE_1D] [static], [private]
Nodal translation scheme for use when generating face elements.
Definition at line 7217 of file Subparametric_Telements.h.
The documentation for this class was generated from the following file:
Subparametric_Telements.h