LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement Class Reference
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
#include <multi_domain_linearised_axisym_navier_stokes_elements.h>
Public Member Functions
LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement ()
Constructor: call the underlying constructors.
virtual void get_base_flow_u (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result) const
Overload get_base_flow_u(...) to return the external element's velocity components at the integration point.
virtual void get_base_flow_dudx (const double &time, const unsigned &ipt, const Vector< double > &x, DenseMatrix< double > &result) const
Overload get_base_flow_dudx(...) to return the derivatives of the external element's velocity components w.r.t. global coordinates at the integration point.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual vector and the Jacobian matrix.
Additional Inherited Members
Detailed Description
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
Build a LinearisedAxisymmetricQCrouzeixRaviart element that inherits from ElementWithExternalElement so that it can `communicate` with an axisymmetric Navier-Stokes element that provides the base flow velocities and their derivatives w.r.t. global coordinates (r and z)
Definition at line 170 of file multi_domain_linearised_axisym_navier_stokes_elements.h.
Constructor & Destructor Documentation
LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement()
LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement::LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement () [inline]
Constructor: call the underlying constructors.
Do not include any external geometric data when computing the element's Jacobian.
Definition at line 176 of file multi_domain_linearised_axisym_navier_stokes_elements.h.
References oomph::ElementWithExternalElement::ignore_external_geometric_data(), and oomph::ElementWithExternalElement::ignore_external_interaction_data().
Member Function Documentation
fill_in_contribution_to_jacobian()
void LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute the element's residual vector and the Jacobian matrix.
Reimplemented from oomph::ElementWithExternalElement.
Definition at line 266 of file multi_domain_linearised_axisym_navier_stokes_elements.h.
References oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian().
get_base_flow_dudx()
virtual void LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement::get_base_flow_dudx (const double & time, const unsigned & ipt, const Vector< double > & x, DenseMatrix< double > & result) const [inline], [virtual]
Overload get_base_flow_dudx(...) to return the derivatives of the external element's velocity components w.r.t. global coordinates at the integration point.
Reimplemented from oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 228 of file multi_domain_linearised_axisym_navier_stokes_elements.h.
References i, and oomph::AxisymmetricNavierStokesEquations::interpolated_dudx_axi_nst().
get_base_flow_u()
virtual void LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement::get_base_flow_u (const double & time, const unsigned & ipt, const Vector< double > & x, Vector< double > & result) const [inline], [virtual]
Overload get_base_flow_u(...) to return the external element's velocity components at the integration point.
Reimplemented from oomph::LinearisedAxisymmetricNavierStokesEquations.
Definition at line 195 of file multi_domain_linearised_axisym_navier_stokes_elements.h.
References i, and oomph::AxisymmetricNavierStokesEquations::interpolated_u_axi_nst().
The documentation for this class was generated from the following file:
multi_domain_linearised_axisym_navier_stokes_elements.h