oomph::SparseMatrix< T, MATRIX_TYPE > Class Template Reference
//////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////
#include <matrices.h>
Public Member Functions
SparseMatrix ()
Default constructor.
SparseMatrix (const SparseMatrix &source_matrix)
Copy constructor.
void operator= (const SparseMatrix &)=delete
Broken assignment operator.
virtual ~SparseMatrix ()
Destructor, delete the memory associated with the values.
T * value ()
Access to C-style value array.
const T * value () const
Access to C-style value array (const version)
unsigned long nrow () const
Return the number of rows of the matrix.
unsigned long ncol () const
Return the number of columns of the matrix.
unsigned long nnz () const
Return the number of nonzero entries.
virtual void output_bottom_right_zero_helper (std::ostream &outfile) const
Output the `bottom right` entry regardless of it being zero or not (this allows automatic detection of matrix size in e.g. matlab, python).
virtual void sparse_indexed_output_helper (std::ostream &outfile) const
Indexed output function to print a matrix to the stream outfile as i,j,a(i,j) for a(i,j)!=0 only.
Protected Attributes
T * Value
Internal representation of the matrix values, a pointer.
unsigned long N
Number of rows.
unsigned long M
Number of columns.
unsigned long Nnz
Number of non-zero values (i.e. size of Value array)
Static Protected Attributes
static T Zero = T(0)
Dummy zero.
Additional Inherited Members
Detailed Description
template<class T, class MATRIX_TYPE>
class oomph::SparseMatrix< T, MATRIX_TYPE >
//////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////
Class for sparse matrices, that store only the non-zero values in a linear array in memory. The details of the array indexing vary depending on the storage scheme used. The MATRIX_TYPE template parameter for use in the curious recursive template pattern is included and passed directly to the base Matrix class.
Definition at line 561 of file matrices.h.
Constructor & Destructor Documentation
SparseMatrix() [1/2]
template<class T , class MATRIX_TYPE >
oomph::SparseMatrix< T, MATRIX_TYPE >::SparseMatrix () [inline]
Default constructor.
Definition at line 581 of file matrices.h.
SparseMatrix() [2/2]
template<class T , class MATRIX_TYPE >
oomph::SparseMatrix< T, MATRIX_TYPE >::SparseMatrix (const SparseMatrix< T, MATRIX_TYPE > & source_matrix) [inline]
Copy constructor.
Definition at line 584 of file matrices.h.
References i, oomph::SparseMatrix< T, MATRIX_TYPE >::M, oomph::SparseMatrix< T, MATRIX_TYPE >::N, oomph::SparseMatrix< T, MATRIX_TYPE >::ncol(), oomph::SparseMatrix< T, MATRIX_TYPE >::Nnz, oomph::SparseMatrix< T, MATRIX_TYPE >::nnz(), oomph::SparseMatrix< T, MATRIX_TYPE >::nrow(), oomph::ElementGeometry::T, oomph::SparseMatrix< T, MATRIX_TYPE >::Value, and oomph::SparseMatrix< T, MATRIX_TYPE >::value().
 SparseMatrix()
template<class T , class MATRIX_TYPE >
virtual oomph::SparseMatrix< T, MATRIX_TYPE >::~SparseMatrix () [inline], [virtual]
Destructor, delete the memory associated with the values.
Definition at line 609 of file matrices.h.
References oomph::SparseMatrix< T, MATRIX_TYPE >::Value.
Member Function Documentation
ncol()
template<class T , class MATRIX_TYPE >
unsigned long oomph::SparseMatrix< T, MATRIX_TYPE >::ncol () const [inline], [virtual]
Return the number of columns of the matrix.
Implements oomph::Matrix< T, MATRIX_TYPE >.
Reimplemented in oomph::CCDoubleMatrix.
Definition at line 634 of file matrices.h.
References oomph::SparseMatrix< T, MATRIX_TYPE >::M.
Referenced by oomph::CRDoubleMatrix::ncol(), and oomph::SparseMatrix< T, MATRIX_TYPE >::SparseMatrix().
nnz()
template<class T , class MATRIX_TYPE >
unsigned long oomph::SparseMatrix< T, MATRIX_TYPE >::nnz () const [inline]
Return the number of nonzero entries.
Definition at line 640 of file matrices.h.
References oomph::SparseMatrix< T, MATRIX_TYPE >::Nnz.
Referenced by oomph::SuperLUSolver::factorise_distributed(), oomph::SuperLUSolver::factorise_serial(), oomph::CRComplexMatrix::multiply(), oomph::CRDoubleMatrix::nnz(), oomph::MatrixBasedLumpedPreconditioner< MATRIX >::setup(), and oomph::SparseMatrix< T, MATRIX_TYPE >::SparseMatrix().
nrow()
template<class T , class MATRIX_TYPE >
unsigned long oomph::SparseMatrix< T, MATRIX_TYPE >::nrow () const [inline], [virtual]
Return the number of rows of the matrix.
Implements oomph::Matrix< T, MATRIX_TYPE >.
Reimplemented in oomph::CCDoubleMatrix.
Definition at line 628 of file matrices.h.
References oomph::SparseMatrix< T, MATRIX_TYPE >::N.
Referenced by oomph::SparseMatrix< T, MATRIX_TYPE >::SparseMatrix().
operator=()
template<class T , class MATRIX_TYPE >
void oomph::SparseMatrix< T, MATRIX_TYPE >::operator= (const SparseMatrix< T, MATRIX_TYPE > &) [delete]
Broken assignment operator.
output_bottom_right_zero_helper()
template<class T , class MATRIX_TYPE >
virtual void oomph::SparseMatrix< T, MATRIX_TYPE >::output_bottom_right_zero_helper (std::ostream & outfile) const [inline], [virtual]
Output the `bottom right` entry regardless of it being zero or not (this allows automatic detection of matrix size in e.g. matlab, python).
Implements oomph::Matrix< T, MATRIX_TYPE >.
Reimplemented in oomph::CCMatrix< T >, oomph::CCMatrix< double >, oomph::CCMatrix< std::complex< double > >, oomph::CRMatrix< T >, oomph::CRMatrix< double >, and oomph::CRMatrix< std::complex< double > >.
Definition at line 648 of file matrices.h.
References oomph::Global_string_for_annotation::string().
sparse_indexed_output_helper()
template<class T , class MATRIX_TYPE >
virtual void oomph::SparseMatrix< T, MATRIX_TYPE >::sparse_indexed_output_helper (std::ostream & outfile) const [inline], [virtual]
Indexed output function to print a matrix to the stream outfile as i,j,a(i,j) for a(i,j)!=0 only.
Implements oomph::Matrix< T, MATRIX_TYPE >.
Reimplemented in oomph::CCMatrix< T >, oomph::CCMatrix< double >, oomph::CCMatrix< std::complex< double > >, oomph::CRMatrix< T >, oomph::CRMatrix< double >, and oomph::CRMatrix< std::complex< double > >.
Definition at line 661 of file matrices.h.
References oomph::Global_string_for_annotation::string().
value() [1/2]
template<class T , class MATRIX_TYPE >
T* oomph::SparseMatrix< T, MATRIX_TYPE >::value () [inline]
Access to C-style value array.
Definition at line 616 of file matrices.h.
References oomph::SparseMatrix< T, MATRIX_TYPE >::Value.
Referenced by oomph::CRComplexMatrix::add(), oomph::SuperLUSolver::factorise_distributed(), oomph::SuperLUSolver::factorise_serial(), oomph::CRDoubleMatrix::inf_norm(), oomph::CRDoubleMatrix::matrix_reduction(), oomph::CCDoubleMatrix::multiply(), oomph::CRComplexMatrix::multiply(), oomph::CRDoubleMatrix::multiply(), oomph::CRDoubleMatrix::multiply_transpose(), oomph::MatrixBasedLumpedPreconditioner< MATRIX >::setup(), oomph::ILUZeroPreconditioner< CCDoubleMatrix >::setup(), oomph::SparseMatrix< T, MATRIX_TYPE >::SparseMatrix(), and oomph::CRDoubleMatrix::value().
value() [2/2]
template<class T , class MATRIX_TYPE >
const T* oomph::SparseMatrix< T, MATRIX_TYPE >::value () const [inline]
Access to C-style value array (const version)
Definition at line 622 of file matrices.h.
References oomph::SparseMatrix< T, MATRIX_TYPE >::Value.
Member Data Documentation
M
template<class T , class MATRIX_TYPE >
unsigned long oomph::SparseMatrix< T, MATRIX_TYPE >::M [protected]
Number of columns.
Definition at line 571 of file matrices.h.
Referenced by oomph::CRComplexMatrix::lubksub(), oomph::CCComplexMatrix::lubksub(), oomph::CRComplexMatrix::ludecompose(), oomph::CCComplexMatrix::ludecompose(), oomph::CCDoubleMatrix::multiply(), oomph::CRComplexMatrix::multiply(), oomph::CCComplexMatrix::multiply(), oomph::CRComplexMatrix::multiply_transpose(), oomph::CCComplexMatrix::multiply_transpose(), oomph::SparseMatrix< T, MATRIX_TYPE >::ncol(), oomph::CRComplexMatrix::residual(), oomph::CCComplexMatrix::residual(), and oomph::SparseMatrix< T, MATRIX_TYPE >::SparseMatrix().
N
template<class T , class MATRIX_TYPE >
unsigned long oomph::SparseMatrix< T, MATRIX_TYPE >::N [protected]
Number of rows.
Definition at line 568 of file matrices.h.
Referenced by oomph::CRComplexMatrix::clean_up_memory(), oomph::CCComplexMatrix::clean_up_memory(), oomph::CRComplexMatrix::lubksub(), oomph::CCComplexMatrix::lubksub(), oomph::CRComplexMatrix::ludecompose(), oomph::CCComplexMatrix::ludecompose(), oomph::CCDoubleMatrix::multiply(), oomph::CRComplexMatrix::multiply(), oomph::CCComplexMatrix::multiply(), oomph::CCDoubleMatrix::multiply_transpose(), oomph::CRComplexMatrix::multiply_transpose(), oomph::CCComplexMatrix::multiply_transpose(), oomph::SparseMatrix< T, MATRIX_TYPE >::nrow(), oomph::CRComplexMatrix::residual(), oomph::CCComplexMatrix::residual(), and oomph::SparseMatrix< T, MATRIX_TYPE >::SparseMatrix().
Nnz
template<class T , class MATRIX_TYPE >
unsigned long oomph::SparseMatrix< T, MATRIX_TYPE >::Nnz [protected]
Number of non-zero values (i.e. size of Value array)
Definition at line 574 of file matrices.h.
Referenced by oomph::CRComplexMatrix::clean_up_memory(), oomph::CCComplexMatrix::clean_up_memory(), oomph::CRComplexMatrix::lubksub(), oomph::CCComplexMatrix::lubksub(), oomph::CRComplexMatrix::ludecompose(), oomph::CCComplexMatrix::ludecompose(), oomph::CCDoubleMatrix::multiply(), oomph::SparseMatrix< T, MATRIX_TYPE >::nnz(), and oomph::SparseMatrix< T, MATRIX_TYPE >::SparseMatrix().
Value
template<class T , class MATRIX_TYPE >
T* oomph::SparseMatrix< T, MATRIX_TYPE >::Value [protected]
Internal representation of the matrix values, a pointer.
Definition at line 565 of file matrices.h.
Referenced by oomph::CRComplexMatrix::clean_up_memory(), oomph::CCComplexMatrix::clean_up_memory(), oomph::CRComplexMatrix::lubksub(), oomph::CCComplexMatrix::lubksub(), oomph::CRComplexMatrix::ludecompose(), oomph::CCComplexMatrix::ludecompose(), oomph::CCDoubleMatrix::matrix_reduction(), oomph::CCDoubleMatrix::multiply(), oomph::CRComplexMatrix::multiply(), oomph::CCComplexMatrix::multiply(), oomph::CCDoubleMatrix::multiply_transpose(), oomph::CRComplexMatrix::multiply_transpose(), oomph::CCComplexMatrix::multiply_transpose(), oomph::CRComplexMatrix::residual(), oomph::CCComplexMatrix::residual(), oomph::SparseMatrix< T, MATRIX_TYPE >::SparseMatrix(), oomph::SparseMatrix< T, MATRIX_TYPE >::value(), and oomph::SparseMatrix< T, MATRIX_TYPE >::~SparseMatrix().
Zero
template<class T , class MATRIX_TYPE >
T oomph::SparseMatrix< T, MATRIX_TYPE >::Zero = T(0) [static], [protected]
Dummy zero.
Definition at line 577 of file matrices.h.
The documentation for this class was generated from the following file:
matrices.h