oomph::TemplateFreeNavierStokesFluxControlElementBase Class Reference
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
#include <navier_stokes_flux_control_elements.h>
Public Member Functions
TemplateFreeNavierStokesFluxControlElementBase ()
Empty constructor.
virtual ~TemplateFreeNavierStokesFluxControlElementBase ()
Empty virtual destructor.
virtual double get_volume_flux ()=0
Pure virtual function to calculate integral of the volume flux.
void add_pressure_data (Data *pressure_data_pt)
Function adds to the external data the Data object whose single value is the pressure applied by the element.
Protected Member Functions
unsigned & pressure_data_id ()
Access function gives id of external Data object whose single value is the pressure applied by the element.
Private Attributes
unsigned Pressure_data_id
Id of external Data object whose single value is the pressure applied by the elements.
Additional Inherited Members
Detailed Description
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
A template free base class for an element to imposes an applied boundary pressure to the Navier-Stokes equations in order to control a volume flux when used in conjunction with a NetFluxControlElement or NetFluxControlElementForWomersleyPressureControl).
Definition at line 53 of file navier_stokes_flux_control_elements.h.
Constructor & Destructor Documentation
TemplateFreeNavierStokesFluxControlElementBase()
oomph::TemplateFreeNavierStokesFluxControlElementBase::TemplateFreeNavierStokesFluxControlElementBase () [inline]
Empty constructor.
Definition at line 58 of file navier_stokes_flux_control_elements.h.
 TemplateFreeNavierStokesFluxControlElementBase()
virtual oomph::TemplateFreeNavierStokesFluxControlElementBase::~TemplateFreeNavierStokesFluxControlElementBase () [inline], [virtual]
Empty virtual destructor.
Definition at line 61 of file navier_stokes_flux_control_elements.h.
Member Function Documentation
add_pressure_data()
void oomph::TemplateFreeNavierStokesFluxControlElementBase::add_pressure_data (Data * pressure_data_pt) [inline]
Function adds to the external data the Data object whose single value is the pressure applied by the element.
Definition at line 68 of file navier_stokes_flux_control_elements.h.
References oomph::GeneralisedElement::add_external_data(), and Pressure_data_id.
Referenced by oomph::NetFluxControlElement::NetFluxControlElement().
get_volume_flux()
virtual double oomph::TemplateFreeNavierStokesFluxControlElementBase::get_volume_flux () [pure virtual]
Pure virtual function to calculate integral of the volume flux.
Implemented in oomph::NavierStokesFluxControlElement< ELEMENT >.
Referenced by oomph::NetFluxControlElement::fill_in_generic_residual_contribution_flux_control().
pressure_data_id()
unsigned & oomph::TemplateFreeNavierStokesFluxControlElementBase::pressure_data_id () [inline], [protected]
Access function gives id of external Data object whose single value is the pressure applied by the element.
Definition at line 76 of file navier_stokes_flux_control_elements.h.
References Pressure_data_id.
Referenced by oomph::NavierStokesFluxControlElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction(), and oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction().
Member Data Documentation
Pressure_data_id
unsigned oomph::TemplateFreeNavierStokesFluxControlElementBase::Pressure_data_id [private]
Id of external Data object whose single value is the pressure applied by the elements.
Definition at line 84 of file navier_stokes_flux_control_elements.h.
Referenced by add_pressure_data(), and pressure_data_id().
The documentation for this class was generated from the following file:
navier_stokes_flux_control_elements.h