oomph::SpineElement< ELEMENT > Class Template Reference
The SpineElement<ELEMENT> class takes an existing element as a template parameter and adds the necessary additional functionality to allow the element to be update using the Method of Spines. A vector of pointers to spines and storage for the local equation numbers associated with the spines are added to the element.
#include <spines.h>
Public Member Functions
SpineElement ()
Constructor, call the constructor of the base element.
SpineElement (FiniteElement *const &element_pt, const int &face_index)
Constructor used for spine face elements.
~SpineElement ()
Destructor, clean up the storage allocated to the local equation numbers.
int spine_local_eqn (const unsigned &n)
Return the local equation number corresponding to the height of the spine at the n-th node.
Private Member Functions
void complete_setup_of_dependencies ()
Complete the setup of additional dependencies. Overloads empty virtual function in GeneralisedElement to determine the `geometric Data`, i.e. the Data that affects the element's shape. This function is called (for all elements) at the very beginning of the equation numbering procedure to ensure that all dependencies are accounted for.
Private Attributes
unsigned * Spine_geometric_index
Array to hold the index of the geometric data associated with the spine height of the spine that affects the n-th node.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::SpineElement< ELEMENT >
The SpineElement<ELEMENT> class takes an existing element as a template parameter and adds the necessary additional functionality to allow the element to be update using the Method of Spines. A vector of pointers to spines and storage for the local equation numbers associated with the spines are added to the element.
Definition at line 474 of file spines.h.
Constructor & Destructor Documentation
SpineElement() [1/2]
template<class ELEMENT >
oomph::SpineElement< ELEMENT >::SpineElement () [inline]
Constructor, call the constructor of the base element.
Definition at line 494 of file spines.h.
SpineElement() [2/2]
template<class ELEMENT >
oomph::SpineElement< ELEMENT >::SpineElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor used for spine face elements.
Definition at line 502 of file spines.h.
 SpineElement()
template<class ELEMENT >
oomph::SpineElement< ELEMENT >::~SpineElement () [inline]
Destructor, clean up the storage allocated to the local equation numbers.
Definition at line 511 of file spines.h.
References oomph::SpineElement< ELEMENT >::Spine_geometric_index.
Member Function Documentation
complete_setup_of_dependencies()
template<class ELEMENT >
void oomph::SpineElement< ELEMENT >::complete_setup_of_dependencies [private], [virtual]
Complete the setup of additional dependencies. Overloads empty virtual function in GeneralisedElement to determine the `geometric Data`, i.e. the Data that affects the element's shape. This function is called (for all elements) at the very beginning of the equation numbering procedure to ensure that all dependencies are accounted for.
////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////// Construct and fill the node_update_data vector
Reimplemented from oomph::ElementWithMovingNodes.
Definition at line 781 of file spines.h.
References i, and oomph::Spine::spine_height_pt().
spine_local_eqn()
template<class ELEMENT >
int oomph::SpineElement< ELEMENT >::spine_local_eqn (const unsigned & n) [inline]
Return the local equation number corresponding to the height of the spine at the n-th node.
Definition at line 521 of file spines.h.
References oomph::ElementWithMovingNodes::geometric_data_local_eqn(), oomph::ElementWithMovingNodes::ngeom_data(), oomph::FiniteElement::nnode(), and oomph::SpineElement< ELEMENT >::Spine_geometric_index.
Referenced by oomph::SpinePointFluidInterfaceBoundingElement< ELEMENT >::kinematic_local_eqn(), and oomph::SpineLineFluidInterfaceBoundingElement< ELEMENT >::kinematic_local_eqn().
Member Data Documentation
Spine_geometric_index
template<class ELEMENT >
unsigned* oomph::SpineElement< ELEMENT >::Spine_geometric_index [private]
Array to hold the index of the geometric data associated with the spine height of the spine that affects the n-th node.
Definition at line 481 of file spines.h.
Referenced by oomph::SpineElement< ELEMENT >::spine_local_eqn(), and oomph::SpineElement< ELEMENT >::~SpineElement().
The documentation for this class was generated from the following file:
spines.h