oomph::AxisymmetricNavierStokesTractionElement< ELEMENT > Class Template Reference
A class for elements that allow the imposition of an applied traction in the axisym Navier Stokes eqns. The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
#include <axisym_fluid_traction_elements.h>
Public Member Functions
AxisymmetricNavierStokesTractionElement (FiniteElement *const &element_pt, const int &face_index)
Constructor, which takes a `bulk` element and the value of the index and its limit.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Return the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Fill in contribution from Jacobian.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
void output (std::ostream &outfile)
Output function.
unsigned nscalar_paraview () const
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
void scalar_value_paraview (std::ofstream &file_out, const unsigned &k, const unsigned &nplot) const
Write values of the k-th scalar field at the plot points. Needs to be implemented for each new specific element type.
std::string scalar_name_paraview (const unsigned &i) const
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
void output (FILE *file_pt)
C_style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function.
void traction (const double &time, const Vector< double > &s, Vector< double > &traction)
Compute traction vector at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
Public Attributes
void(*&)(const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction) traction_fct_pt ()
Reference to the traction function pointer.
Protected Member Functions
virtual void get_traction (const double &time, const unsigned &intpt, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction) const
Get the traction vector: Pass number of integration point (dummy), Eulerian coordinate and normal vector and return the load vector (not all of the input arguments will be required for all specific load functions but the list should cover all cases). This function is virtual so it can be overloaded for FSI.
void fill_in_contribution_to_residuals_axisymmetric_nst_traction (Vector< double > &residuals)
Helper function that actually calculates the residuals.
Protected Attributes
Vector< unsigned > U_index_axisymmetric_nst_traction
Index at which the i-th velocity component is stored.
void(* Traction_fct_pt)(const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
Pointer to an imposed traction function. Arguments: Eulerian coordinate; outer unit normal; applied traction. (Not all of the input arguments will be required for all specific load functions but the list should cover all cases)
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >
A class for elements that allow the imposition of an applied traction in the axisym Navier Stokes eqns. The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
Definition at line 71 of file axisym_fluid_traction_elements.h.
Constructor & Destructor Documentation
AxisymmetricNavierStokesTractionElement()
template<class ELEMENT >
oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::AxisymmetricNavierStokesTractionElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit.
Definition at line 116 of file axisym_fluid_traction_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FaceElement::face_index(), i, oomph::FiniteElement::nodal_dimension(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::Traction_fct_pt, and oomph::AxisymmetricNavierStokesTractionElementHelper::Zero_traction_fct().
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Fill in contribution from Jacobian.
Reimplemented from oomph::GeneralisedElement.
Definition at line 160 of file axisym_fluid_traction_elements.h.
References oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_residuals_axisymmetric_nst_traction().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Return the residuals.
Reimplemented from oomph::GeneralisedElement.
Definition at line 153 of file axisym_fluid_traction_elements.h.
References oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_residuals_axisymmetric_nst_traction().
fill_in_contribution_to_residuals_axisymmetric_nst_traction()
template<class ELEMENT >
void oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_residuals_axisymmetric_nst_traction (Vector< double > & residuals) [protected]
Helper function that actually calculates the residuals.
Return the residuals for the AxisymmetricNavierStokesTractionElement equations.
Definition at line 446 of file axisym_fluid_traction_elements.h.
References i, and oomph::QuadTreeNames::W.
Referenced by oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_residuals().
get_traction()
template<class ELEMENT >
virtual void oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::get_traction (const double & time, const unsigned & intpt, const Vector< double > & x, const Vector< double > & n, Vector< double > & traction) const [inline], [protected], [virtual]
Get the traction vector: Pass number of integration point (dummy), Eulerian coordinate and normal vector and return the load vector (not all of the input arguments will be required for all specific load functions but the list should cover all cases). This function is virtual so it can be overloaded for FSI.
Definition at line 95 of file axisym_fluid_traction_elements.h.
References oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::traction(), and oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::Traction_fct_pt.
Referenced by oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::output(), and oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::scalar_value_paraview().
nscalar_paraview()
template<class ELEMENT >
unsigned oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::nscalar_paraview () const [inline], [virtual]
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
Reimplemented from oomph::FiniteElement.
Definition at line 188 of file axisym_fluid_traction_elements.h.
References oomph::FiniteElement::nodal_dimension().
output() [1/4]
template<class ELEMENT >
void oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C_style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 390 of file axisym_fluid_traction_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<class ELEMENT >
void oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 396 of file axisym_fluid_traction_elements.h.
References oomph::FiniteElement::output().
output() [3/4]
template<class ELEMENT >
void oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Definition at line 180 of file axisym_fluid_traction_elements.h.
References oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::output().
Referenced by oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::output().
output() [4/4]
template<class ELEMENT >
void oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Definition at line 310 of file axisym_fluid_traction_elements.h.
References oomph::FiniteElement::get_s_plot(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::get_traction(), i, oomph::FaceElement::interpolated_x(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::nplot_points(), oomph::FaceElement::outer_unit_normal(), s, oomph::FiniteElement::shape(), oomph::FiniteElement::tecplot_zone_string(), oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), and oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::traction().
scalar_name_paraview()
template<class ELEMENT >
std::string oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::scalar_name_paraview (const unsigned & i) const [inline], [virtual]
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
Reimplemented from oomph::FiniteElement.
Definition at line 282 of file axisym_fluid_traction_elements.h.
References i, oomph::FiniteElement::nodal_dimension(), and oomph::StringConversion::to_string().
scalar_value_paraview()
template<class ELEMENT >
void oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::scalar_value_paraview (std::ofstream & file_out, const unsigned & k, const unsigned & nplot) const [inline], [virtual]
Write values of the k-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
Definition at line 198 of file axisym_fluid_traction_elements.h.
References oomph::FiniteElement::get_s_plot(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::get_traction(), i, oomph::FaceElement::interpolated_x(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::nplot_points_paraview(), oomph::FaceElement::outer_unit_normal(), s, oomph::FiniteElement::shape(), oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), and oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::traction().
traction()
template<class ELEMENT >
void oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::traction (const double & time, const Vector< double > & s, Vector< double > & traction)
Compute traction vector at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Compute traction vector at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
Definition at line 420 of file axisym_fluid_traction_elements.h.
References s.
Referenced by oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::get_traction(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::output(), and oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::scalar_value_paraview().
zeta_nodal()
template<class ELEMENT >
double oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Reimplemented from oomph::FiniteElement.
Definition at line 172 of file axisym_fluid_traction_elements.h.
References i, and oomph::FaceElement::zeta_nodal().
Member Data Documentation
traction_fct_pt
template<class ELEMENT >
void(*&)(const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction) oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::traction_fct_pt() [inline]
Reference to the traction function pointer.
Definition at line 143 of file axisym_fluid_traction_elements.h.
Traction_fct_pt
template<class ELEMENT >
void(* oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::Traction_fct_pt) (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result) [protected]
Pointer to an imposed traction function. Arguments: Eulerian coordinate; outer unit normal; applied traction. (Not all of the input arguments will be required for all specific load functions but the list should cover all cases)
Definition at line 84 of file axisym_fluid_traction_elements.h.
Referenced by oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::AxisymmetricNavierStokesTractionElement(), and oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::get_traction().
U_index_axisymmetric_nst_traction
template<class ELEMENT >
Vector<unsigned> oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::U_index_axisymmetric_nst_traction [protected]
Index at which the i-th velocity component is stored.
Definition at line 77 of file axisym_fluid_traction_elements.h.
The documentation for this class was generated from the following file:
axisym_fluid_traction_elements.h