oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner Class Reference
General purpose block triangular preconditioner. By default this is Upper triangular. Also, by default SuperLUPreconditioner (or SuperLUDistPreconditioner) is used to solve the subsidiary systems, but other preconditioners can be used by setting them using passing a pointer to a function of type SubsidiaryPreconditionerFctPt to the method subsidiary_preconditioner_function_pt().
#include <general_purpose_space_time_subsidiary_block_preconditioner.h>
Public Member Functions
SpaceTimeNavierStokesSubsidiaryPreconditioner ()
Constructor. (By default this preconditioner is upper triangular).
virtual ~SpaceTimeNavierStokesSubsidiaryPreconditioner ()
Destructor - delete the preconditioner matrices.
virtual void clean_up_memory ()
Clean up the memory.
SpaceTimeNavierStokesSubsidiaryPreconditioner (const SpaceTimeNavierStokesSubsidiaryPreconditioner &)=delete
Broken copy constructor.
void operator= (const SpaceTimeNavierStokesSubsidiaryPreconditioner &)=delete
Broken assignment operator.
void setup ()
Setup the preconditioner.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply preconditioner to r.
void enable_doc_memory_usage ()
Document the memory usage.
void disable_doc_memory_usage ()
Don't document the memory usage!
double get_memory_usage_in_bytes ()
Get the memory statistics.
SpaceTimeNavierStokesSubsidiaryPreconditioner ()
Constructor. (By default this preconditioner is upper triangular).
virtual ~SpaceTimeNavierStokesSubsidiaryPreconditioner ()
Destructor - delete the preconditioner matrices.
virtual void clean_up_memory ()
Clean up the memory.
SpaceTimeNavierStokesSubsidiaryPreconditioner (const SpaceTimeNavierStokesSubsidiaryPreconditioner &)=delete
Broken copy constructor.
void operator= (const SpaceTimeNavierStokesSubsidiaryPreconditioner &)=delete
Broken assignment operator.
void setup ()
Setup the preconditioner.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply preconditioner to r.
void enable_doc_memory_usage ()
Document the memory usage.
void disable_doc_memory_usage ()
Don't document the memory usage!
double get_memory_usage_in_bytes ()
Get the memory statistics.
void setup (DoubleMatrixBase *matrix_pt)
For some reason we need to remind the compiler that there is also a function named setup in the base class.
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
For some reason we need to remind the compiler that there is also a function named setup in the base class.
virtual void setup ()=0
For some reason we need to remind the compiler that there is also a function named setup in the base class.
void setup (DoubleMatrixBase *matrix_pt)
For some reason we need to remind the compiler that there is also a function named setup in the base class.
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
For some reason we need to remind the compiler that there is also a function named setup in the base class.
virtual void setup ()=0
For some reason we need to remind the compiler that there is also a function named setup in the base class.
Private Attributes
Preconditioner * F_preconditioner_pt
Pointer to the 'preconditioner' for the F matrix.
Preconditioner * P_preconditioner_pt
Pointer to the 'preconditioner' for the pressure matrix.
bool Using_default_f_preconditioner
Flag indicating whether the default F preconditioner is used.
bool Using_default_p_preconditioner
Flag indicating whether the default P preconditioner is used.
bool Preconditioner_has_been_setup
Control flag is true if the preconditioner has been setup (used so we can wipe the data when the preconditioner is called again)
bool Compute_memory_statistics
Flag to indicate whether or not to record the memory statistics this preconditioner.
double Memory_usage_in_bytes
Storage for the memory usage of the solver if the flag above is set to true (in bytes)
MatrixVectorProduct * F_mat_vec_pt
MatrixVectorProduct operator for F.
MatrixVectorProduct * G_mat_vec_pt
MatrixVectorProduct operator for G.
Additional Inherited Members
Detailed Description
General purpose block triangular preconditioner. By default this is Upper triangular. Also, by default SuperLUPreconditioner (or SuperLUDistPreconditioner) is used to solve the subsidiary systems, but other preconditioners can be used by setting them using passing a pointer to a function of type SubsidiaryPreconditionerFctPt to the method subsidiary_preconditioner_function_pt().
Definition at line 54 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
Constructor & Destructor Documentation
SpaceTimeNavierStokesSubsidiaryPreconditioner() [1/4]
oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::SpaceTimeNavierStokesSubsidiaryPreconditioner () [inline]
Constructor. (By default this preconditioner is upper triangular).
Definition at line 59 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
References Compute_memory_statistics, F_mat_vec_pt, F_preconditioner_pt, G_mat_vec_pt, Memory_usage_in_bytes, P_preconditioner_pt, Preconditioner_has_been_setup, Using_default_f_preconditioner, and Using_default_p_preconditioner.
 SpaceTimeNavierStokesSubsidiaryPreconditioner() [1/2]
virtual oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::~SpaceTimeNavierStokesSubsidiaryPreconditioner () [inline], [virtual]
Destructor - delete the preconditioner matrices.
Definition at line 90 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
References clean_up_memory().
SpaceTimeNavierStokesSubsidiaryPreconditioner() [2/4]
oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::SpaceTimeNavierStokesSubsidiaryPreconditioner (const SpaceTimeNavierStokesSubsidiaryPreconditioner &) [delete]
Broken copy constructor.
SpaceTimeNavierStokesSubsidiaryPreconditioner() [3/4]
oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::SpaceTimeNavierStokesSubsidiaryPreconditioner () [inline]
Constructor. (By default this preconditioner is upper triangular).
Definition at line 60 of file spacetime_navier_stokes_block_preconditioner.h.
References Compute_memory_statistics, F_mat_vec_pt, F_preconditioner_pt, G_mat_vec_pt, Memory_usage_in_bytes, P_preconditioner_pt, Preconditioner_has_been_setup, Using_default_f_preconditioner, and Using_default_p_preconditioner.
 SpaceTimeNavierStokesSubsidiaryPreconditioner() [2/2]
virtual oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::~SpaceTimeNavierStokesSubsidiaryPreconditioner () [inline], [virtual]
Destructor - delete the preconditioner matrices.
Definition at line 91 of file spacetime_navier_stokes_block_preconditioner.h.
References clean_up_memory().
SpaceTimeNavierStokesSubsidiaryPreconditioner() [4/4]
oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::SpaceTimeNavierStokesSubsidiaryPreconditioner (const SpaceTimeNavierStokesSubsidiaryPreconditioner &) [delete]
Broken copy constructor.
Member Function Documentation
clean_up_memory() [1/2]
virtual void oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::clean_up_memory () [inline], [virtual]
Clean up the memory.
Reimplemented from oomph::Preconditioner.
Definition at line 97 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
References F_mat_vec_pt, F_preconditioner_pt, G_mat_vec_pt, P_preconditioner_pt, and Preconditioner_has_been_setup.
Referenced by setup(), and ~SpaceTimeNavierStokesSubsidiaryPreconditioner().
clean_up_memory() [2/2]
virtual void oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::clean_up_memory () [inline], [virtual]
Clean up the memory.
Reimplemented from oomph::Preconditioner.
Definition at line 98 of file spacetime_navier_stokes_block_preconditioner.h.
References F_mat_vec_pt, F_preconditioner_pt, G_mat_vec_pt, P_preconditioner_pt, Preconditioner_has_been_setup, Using_default_f_preconditioner, and Using_default_p_preconditioner.
disable_doc_memory_usage() [1/2]
void oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::disable_doc_memory_usage () [inline]
Don't document the memory usage!
Set the appropriate flag to false
Definition at line 147 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
References Compute_memory_statistics.
disable_doc_memory_usage() [2/2]
void oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::disable_doc_memory_usage () [inline]
Don't document the memory usage!
Set the appropriate flag to false
Definition at line 154 of file spacetime_navier_stokes_block_preconditioner.h.
References Compute_memory_statistics.
enable_doc_memory_usage() [1/2]
void oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::enable_doc_memory_usage () [inline]
Document the memory usage.
Set the appropriate flag to true
Definition at line 139 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
References Compute_memory_statistics.
Referenced by oomph::GMRESBlockPreconditioner::setup().
enable_doc_memory_usage() [2/2]
void oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::enable_doc_memory_usage () [inline]
Document the memory usage.
Set the appropriate flag to true
Definition at line 146 of file spacetime_navier_stokes_block_preconditioner.h.
References Compute_memory_statistics.
get_memory_usage_in_bytes() [1/2]
double oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::get_memory_usage_in_bytes () [inline]
Get the memory statistics.
Definition at line 155 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
References Compute_memory_statistics, Memory_usage_in_bytes, and Preconditioner_has_been_setup.
Referenced by oomph::BandedBlockTriangularPreconditioner< MATRIX >::setup().
get_memory_usage_in_bytes() [2/2]
double oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::get_memory_usage_in_bytes () [inline]
Get the memory statistics.
Definition at line 162 of file spacetime_navier_stokes_block_preconditioner.h.
References Compute_memory_statistics, Memory_usage_in_bytes, and Preconditioner_has_been_setup.
operator=() [1/2]
void oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::operator= (const SpaceTimeNavierStokesSubsidiaryPreconditioner &) [delete]
Broken assignment operator.
operator=() [2/2]
void oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::operator= (const SpaceTimeNavierStokesSubsidiaryPreconditioner &) [delete]
Broken assignment operator.
preconditioner_solve() [1/2]
void oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) [virtual]
Apply preconditioner to r.
Preconditioner solve for the block triangular preconditioner.
Implements oomph::Preconditioner.
Definition at line 482 of file general_purpose_space_time_subsidiary_block_preconditioner.cc.
References oomph::DoubleVector::build(), oomph::LinearAlgebraDistribution::built(), oomph::DoubleVector::clear(), oomph::DistributableLinearAlgebraObject::distribution_pt(), F_mat_vec_pt, F_preconditioner_pt, G_mat_vec_pt, oomph::BlockPreconditioner< CRDoubleMatrix >::get_block_vector(), oomph::MatrixVectorProduct::multiply(), oomph::MatrixVectorProduct::multiply_transpose(), P_preconditioner_pt, oomph::Preconditioner::preconditioner_solve(), and oomph::BlockPreconditioner< CRDoubleMatrix >::return_block_vector().
Referenced by oomph::GMRESBlockPreconditioner::preconditioner_solve(), and oomph::GMRESBlockPreconditioner::update().
preconditioner_solve() [2/2]
void oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) [virtual]
Apply preconditioner to r.
Implements oomph::Preconditioner.
setup() [1/8]
void oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::setup () [virtual]
Setup the preconditioner.
Setup for the block triangular preconditioner.
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Setup for the block triangular preconditioner
Implements oomph::Preconditioner.
Definition at line 61 of file general_purpose_space_time_subsidiary_block_preconditioner.cc.
References oomph::BlockPreconditioner< CRDoubleMatrix >::block_setup(), clean_up_memory(), Compute_memory_statistics, oomph::DoubleVectorHelpers::concatenate(), F_mat_vec_pt, F_preconditioner_pt, G_mat_vec_pt, oomph::BlockPreconditioner< CRDoubleMatrix >::get_block(), i, oomph::BlockPreconditioner< CRDoubleMatrix >::is_subsidiary_block_preconditioner(), oomph::BlockPreconditioner< CRDoubleMatrix >::matrix_pt(), Memory_usage_in_bytes, oomph::CRDoubleMatrix::multiply(), oomph::BlockPreconditioner< CRDoubleMatrix >::nblock_types(), oomph::BlockPreconditioner< CRDoubleMatrix >::ndof_types(), oomph::CRDoubleMatrix::nnz(), oomph::CRDoubleMatrix::nrow(), oomph::oomph_info, oomph::oomph_nullstream, P_preconditioner_pt, Preconditioner_has_been_setup, oomph::Hypre_default_settings::set_defaults_for_2D_poisson_problem(), oomph::Preconditioner::setup(), oomph::BlockPreconditioner< CRDoubleMatrix >::setup_matrix_vector_product(), oomph::Preconditioner::Silent_preconditioner_setup, oomph::CRDoubleMatrix::sparse_indexed_output_with_offset(), oomph::OomphInfo::stream_pt(), oomph::Preconditioner::Stream_pt, oomph::Global_string_for_annotation::string(), oomph::TimingHelpers::timer(), Using_default_f_preconditioner, and Using_default_p_preconditioner.
Referenced by oomph::GMRESBlockPreconditioner::setup().
setup() [2/8]
void oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::setup () [virtual]
Setup the preconditioner.
Implements oomph::Preconditioner.
setup() [3/8]
virtual void oomph::Preconditioner::setup () [virtual]
For some reason we need to remind the compiler that there is also a function named setup in the base class.
Implements oomph::Preconditioner.
setup() [4/8]
virtual void oomph::Preconditioner::setup () [virtual]
For some reason we need to remind the compiler that there is also a function named setup in the base class.
Implements oomph::Preconditioner.
setup() [5/8]
void oomph::Preconditioner::setup (const Problem * problem_pt, DoubleMatrixBase * matrix_pt) [inline]
For some reason we need to remind the compiler that there is also a function named setup in the base class.
Definition at line 120 of file preconditioner.h.
setup() [6/8]
void oomph::Preconditioner::setup (const Problem * problem_pt, DoubleMatrixBase * matrix_pt) [inline]
For some reason we need to remind the compiler that there is also a function named setup in the base class.
Definition at line 120 of file preconditioner.h.
setup() [7/8]
void oomph::Preconditioner::setup (DoubleMatrixBase * matrix_pt) [inline]
For some reason we need to remind the compiler that there is also a function named setup in the base class.
Definition at line 94 of file preconditioner.h.
setup() [8/8]
void oomph::Preconditioner::setup (DoubleMatrixBase * matrix_pt) [inline]
For some reason we need to remind the compiler that there is also a function named setup in the base class.
Definition at line 94 of file preconditioner.h.
Member Data Documentation
Compute_memory_statistics
bool oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::Compute_memory_statistics [private]
Flag to indicate whether or not to record the memory statistics this preconditioner.
Definition at line 225 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
Referenced by disable_doc_memory_usage(), enable_doc_memory_usage(), get_memory_usage_in_bytes(), setup(), and SpaceTimeNavierStokesSubsidiaryPreconditioner().
F_mat_vec_pt
MatrixVectorProduct * oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::F_mat_vec_pt [private]
MatrixVectorProduct operator for F.
Definition at line 232 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
Referenced by clean_up_memory(), preconditioner_solve(), setup(), and SpaceTimeNavierStokesSubsidiaryPreconditioner().
F_preconditioner_pt
Preconditioner * oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::F_preconditioner_pt [private]
Pointer to the 'preconditioner' for the F matrix.
Definition at line 208 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
Referenced by clean_up_memory(), preconditioner_solve(), setup(), and SpaceTimeNavierStokesSubsidiaryPreconditioner().
G_mat_vec_pt
MatrixVectorProduct * oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::G_mat_vec_pt [private]
MatrixVectorProduct operator for G.
Definition at line 235 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
Referenced by clean_up_memory(), preconditioner_solve(), setup(), and SpaceTimeNavierStokesSubsidiaryPreconditioner().
Memory_usage_in_bytes
double oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::Memory_usage_in_bytes [private]
Storage for the memory usage of the solver if the flag above is set to true (in bytes)
Definition at line 229 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
Referenced by get_memory_usage_in_bytes(), setup(), and SpaceTimeNavierStokesSubsidiaryPreconditioner().
P_preconditioner_pt
Preconditioner * oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::P_preconditioner_pt [private]
Pointer to the 'preconditioner' for the pressure matrix.
Definition at line 211 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
Referenced by clean_up_memory(), preconditioner_solve(), setup(), and SpaceTimeNavierStokesSubsidiaryPreconditioner().
Preconditioner_has_been_setup
bool oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::Preconditioner_has_been_setup [private]
Control flag is true if the preconditioner has been setup (used so we can wipe the data when the preconditioner is called again)
Definition at line 221 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
Referenced by clean_up_memory(), get_memory_usage_in_bytes(), setup(), and SpaceTimeNavierStokesSubsidiaryPreconditioner().
Using_default_f_preconditioner
bool oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::Using_default_f_preconditioner [private]
Flag indicating whether the default F preconditioner is used.
Definition at line 214 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
Referenced by clean_up_memory(), setup(), and SpaceTimeNavierStokesSubsidiaryPreconditioner().
Using_default_p_preconditioner
bool oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::Using_default_p_preconditioner [private]
Flag indicating whether the default P preconditioner is used.
Definition at line 217 of file general_purpose_space_time_subsidiary_block_preconditioner.h.
Referenced by clean_up_memory(), setup(), and SpaceTimeNavierStokesSubsidiaryPreconditioner().
The documentation for this class was generated from the following files:
general_purpose_space_time_subsidiary_block_preconditioner.h
spacetime_navier_stokes_block_preconditioner.h
general_purpose_space_time_subsidiary_block_preconditioner.cc
spacetime_navier_stokes_block_preconditioner.cc