oomph::ImposeImpenetrabilityElement< ELEMENT > Class Template Reference
ImposeImpenetrabilityElement are elements that coincide with the faces of higher-dimensional `bulk` elements. They are used on boundaries where we would like to impose impenetrability.
#include <impose_impenetrability_element.h>
Public Member Functions
ImposeImpenetrabilityElement (FiniteElement *const &element_pt, const int &face_index, const unsigned &id=0)
Constructor takes a `bulk` element, the index that identifies which face the ImposeImpenetrabilityElement is supposed to be attached to, and the face element ID.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Fill in contribution from Jacobian.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,[z],u,v,[w],p in tecplot format.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default This final over-ride is required because both SolidFiniteElements and FaceElements overload zeta_nodal.
Protected Member Functions
void fill_in_generic_contribution_to_residuals_parall_lagr_multiplier (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Helper function to compute the residuals and, if flag==1, the Jacobian.
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into: Just the solid degrees of freedom themselves.
unsigned additional_ndof_types () const
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Private Attributes
unsigned Id
Lagrange Id.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::ImposeImpenetrabilityElement< ELEMENT >
ImposeImpenetrabilityElement are elements that coincide with the faces of higher-dimensional `bulk` elements. They are used on boundaries where we would like to impose impenetrability.
Definition at line 43 of file impose_impenetrability_element.h.
Constructor & Destructor Documentation
ImposeImpenetrabilityElement()
template<class ELEMENT >
oomph::ImposeImpenetrabilityElement< ELEMENT >::ImposeImpenetrabilityElement (FiniteElement *const & element_pt, const int & face_index, const unsigned & id = 0) [inline]
Constructor takes a `bulk` element, the index that identifies which face the ImposeImpenetrabilityElement is supposed to be attached to, and the face element ID.
Definition at line 55 of file impose_impenetrability_element.h.
References oomph::FaceElement::add_additional_values(), oomph::FiniteElement::build_face_element(), oomph::FaceElement::face_index(), oomph::ImposeImpenetrabilityElement< ELEMENT >::Id, and oomph::FiniteElement::nnode().
Member Function Documentation
additional_ndof_types()
template<class ELEMENT >
unsigned oomph::ImposeImpenetrabilityElement< ELEMENT >::additional_ndof_types () const [inline], [protected]
Definition at line 299 of file impose_impenetrability_element.h.
References oomph::FiniteElement::dim().
Referenced by oomph::ImposeImpenetrabilityElement< ELEMENT >::get_dof_numbers_for_unknowns(), and oomph::ImposeImpenetrabilityElement< ELEMENT >::ndof_types().
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Fill in contribution from Jacobian.
Reimplemented from oomph::FiniteElement.
Definition at line 85 of file impose_impenetrability_element.h.
References oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), and residuals().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Fill in the residuals.
Reimplemented from oomph::GeneralisedElement.
Definition at line 77 of file impose_impenetrability_element.h.
References oomph::GeneralisedElement::Dummy_matrix, oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), and residuals().
fill_in_generic_contribution_to_residuals_parall_lagr_multiplier()
template<class ELEMENT >
void oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [inline], [protected]
Helper function to compute the residuals and, if flag==1, the Jacobian.
Definition at line 120 of file impose_impenetrability_element.h.
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), i, oomph::ImposeImpenetrabilityElement< ELEMENT >::Id, oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), oomph::FiniteElement::integral_pt(), interpolated_u(), oomph::FaceElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), residuals(), oomph::FiniteElement::shape_at_knot(), oomph::Node::value(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_contribution_to_residuals().
get_dof_numbers_for_unknowns()
template<class ELEMENT >
void oomph::ImposeImpenetrabilityElement< ELEMENT >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> & dof_lookup_list) const [inline], [protected], [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Reimplemented from oomph::GeneralisedElement.
Definition at line 312 of file impose_impenetrability_element.h.
References oomph::ImposeImpenetrabilityElement< ELEMENT >::additional_ndof_types(), oomph::FaceElement::Bulk_element_pt, oomph::FaceElement::Bulk_node_number, oomph::FiniteElement::dim(), oomph::GeneralisedElement::eqn_number(), i, oomph::ImposeImpenetrabilityElement< ELEMENT >::Id, oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), and oomph::FiniteElement::node_pt().
ndof_types()
template<class ELEMENT >
unsigned oomph::ImposeImpenetrabilityElement< ELEMENT >::ndof_types () const [inline], [protected], [virtual]
The number of `DOF types` that degrees of freedom in this element are sub-divided into: Just the solid degrees of freedom themselves.
Reimplemented from oomph::GeneralisedElement.
Definition at line 289 of file impose_impenetrability_element.h.
References oomph::ImposeImpenetrabilityElement< ELEMENT >::additional_ndof_types().
output() [1/2]
template<class ELEMENT >
void oomph::ImposeImpenetrabilityElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Definition at line 94 of file impose_impenetrability_element.h.
References oomph::FiniteElement::output().
output() [2/2]
template<class ELEMENT >
void oomph::ImposeImpenetrabilityElement< ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format.
Reimplemented from oomph::FiniteElement.
Definition at line 100 of file impose_impenetrability_element.h.
References oomph::FiniteElement::output().
zeta_nodal()
template<class ELEMENT >
double oomph::ImposeImpenetrabilityElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default This final over-ride is required because both SolidFiniteElements and FaceElements overload zeta_nodal.
Reimplemented from oomph::FaceElement.
Definition at line 110 of file impose_impenetrability_element.h.
References i, n, and oomph::FaceElement::zeta_nodal().
Member Data Documentation
Id
template<class ELEMENT >
unsigned oomph::ImposeImpenetrabilityElement< ELEMENT >::Id [private]
Lagrange Id.
Definition at line 48 of file impose_impenetrability_element.h.
Referenced by oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::ImposeImpenetrabilityElement< ELEMENT >::get_dof_numbers_for_unknowns(), and oomph::ImposeImpenetrabilityElement< ELEMENT >::ImposeImpenetrabilityElement().
The documentation for this class was generated from the following file:
impose_impenetrability_element.h