oomph::SolidICProblem Class Reference
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
#include <elastic_problems.h>
Public Member Functions
SolidICProblem ()
Constructor. Initialise pointer to IC object to NULL. Create a dummy mesh that can be deleted when static problem finally goes out of scope at end of program execution.
SolidICProblem (const SolidICProblem &)=delete
Broken copy constructor.
void operator= (const SolidICProblem &)=delete
Broken assignment operator.
void actions_after_newton_solve ()
Update after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve. (empty)
void set_static_initial_condition (Problem *problem_pt, Mesh *mesh_pt, SolidInitialCondition *ic_pt, const double &time)
Force the elastic structure that is discretised on the specified mesh to deform in the shape of the initial condition object (evaluated at the time specified)
void set_static_initial_condition (Problem *problem_pt, Mesh *mesh_pt, SolidInitialCondition *ic_pt)
Force the elastic structure that is discretised on the specified mesh to deform in the shape of the initial condition object (wrapper)
template<class TIMESTEPPER >
void set_newmark_initial_condition_directly (Problem *problem_pt, Mesh *mesh_pt, TIMESTEPPER *timestepper_pt, SolidInitialCondition *ic_pt, const double &dt)
Setup initial condition for time-integration with Newmark's method. History values are assigned to that the velocity and accelerations determined by the Newmark scheme are exact at the initial time.
template<class TIMESTEPPER >
void set_newmark_initial_condition_consistently (Problem *problem_pt, Mesh *mesh_pt, TIMESTEPPER *timestepper_pt, SolidInitialCondition *ic_pt, const double &dt, SolidFiniteElement::MultiplierFctPt multiplier_fct_pt=0)
Setup initial condition for time-integration with Newmark's method. Past displacements and velocities are assigned directly (consistent with the idea that a second order ODE can take ICs up to 1st order, while the history value for the previous acceleration is determined by the condition that the weak equation is satisfied at the initial time.) The multiplier function needs to specify the factor that multiplies the inertia terms -- typically this is a constant, given by the ratio $ \Lambda^2 $ of the problem's intrinsic timescale to the time used to non-dimensionalise the equations. If the function (pointer) is not specified the multiplier is assumed to be equal to 1.0 -- appropriate for a non-dimensionalisation based on the problem's intrinsic timescale.
double & max_residual_after_consistent_newton_ic ()
Max. tolerated residual after application of consistent Newmark IC. Used to check if we have specified the correct timescale ratio (non-dim density).
Private Member Functions
void backup_original_state ()
Backup original state of all data associated with mesh.
void reset_original_state ()
Reset original state of all data associated with mesh.
void setup_problem ()
Change pinned status of all data associated with mesh so that the IC problem can be solved.
Private Attributes
SolidInitialCondition * IC_pt
Pointer to initial condition object.
Vector< int > Backup_pinned
Vector to store pinned status of all data.
Vector< Vector< Data * > > Backup_ext_data
Vector of Vectors to store pointers to exernal data in the elements.
double Max_residual_after_consistent_newton_ic
Max. tolerated residual after application of consistent Newmark IC. Used to check if we have specified the correct timescale ratio (non-dim density).
Additional Inherited Members
Detailed Description
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
IC problem for an elastic body discretised on a given (sub)-mesh. We switch the elements' residuals and Jacobians to the system of equations that forces the wall shape to become that of a specified `initial condition object`.
Boundary conditions for all data items associated with the mesh's elements' are temporarily overwritten so that all positional dofs (and only those!) become free while all other data (nodal data and the element's internal and external data) are either pinned (for nodal and internal data) or completely removed (for pointers to external data). The complete removal of the (pointers to the) external data is necessary because in FSI problems, positional data of certain elements can feature as external data of others. Hence pinning them in their incarnation as external data would also pin them in their incarnation as positional data.
All data and its pinned-status are restored at the end of the call to setup_ic().
Definition at line 87 of file elastic_problems.h.
Constructor & Destructor Documentation
SolidICProblem() [1/2]
oomph::SolidICProblem::SolidICProblem () [inline]
Constructor. Initialise pointer to IC object to NULL. Create a dummy mesh that can be deleted when static problem finally goes out of scope at end of program execution.
Create dummy mesh
Definition at line 94 of file elastic_problems.h.
References Max_residual_after_consistent_newton_ic, and oomph::Problem::mesh_pt().
SolidICProblem() [2/2]
oomph::SolidICProblem::SolidICProblem (const SolidICProblem &) [delete]
Broken copy constructor.
Member Function Documentation
actions_after_newton_solve()
void oomph::SolidICProblem::actions_after_newton_solve () [inline], [virtual]
Update after solve (empty)
Reimplemented from oomph::Problem.
Definition at line 111 of file elastic_problems.h.
actions_before_newton_solve()
void oomph::SolidICProblem::actions_before_newton_solve () [inline], [virtual]
Update the problem specs before solve. (empty)
Reimplemented from oomph::Problem.
Definition at line 114 of file elastic_problems.h.
backup_original_state()
void oomph::SolidICProblem::backup_original_state () [private]
Backup original state of all data associated with mesh.
Backup pinned status of all data associated with the mesh. Also backup the (pointers to the) elements' external data.
Definition at line 191 of file elastic_problems.cc.
References Backup_ext_data, Backup_pinned, oomph::Mesh::element_pt(), oomph::GeneralisedElement::external_data_pt(), oomph::SolidFiniteElement::has_internal_solid_data(), i, oomph::GeneralisedElement::internal_data_pt(), oomph::Data::is_pinned(), oomph::Problem::mesh_pt(), oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::GeneralisedElement::nexternal_data(), oomph::GeneralisedElement::ninternal_data(), oomph::FiniteElement::nnodal_position_type(), oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::Data::nvalue(), oomph::SolidNode::position_is_pinned(), and oomph::Global_string_for_annotation::string().
Referenced by set_newmark_initial_condition_consistently(), set_newmark_initial_condition_directly(), and set_static_initial_condition().
max_residual_after_consistent_newton_ic()
double & oomph::SolidICProblem::max_residual_after_consistent_newton_ic () [inline]
Max. tolerated residual after application of consistent Newmark IC. Used to check if we have specified the correct timescale ratio (non-dim density).
Definition at line 172 of file elastic_problems.h.
References Max_residual_after_consistent_newton_ic.
operator=()
void oomph::SolidICProblem::operator= (const SolidICProblem &) [delete]
Broken assignment operator.
reset_original_state()
void oomph::SolidICProblem::reset_original_state () [private]
Reset original state of all data associated with mesh.
Reset pinned status of all data and re-instate the pointers to the elements' external data.
Definition at line 343 of file elastic_problems.cc.
References oomph::GeneralisedElement::add_external_data(), Backup_ext_data, Backup_pinned, oomph::Mesh::element_pt(), oomph::SolidFiniteElement::has_internal_solid_data(), i, oomph::GeneralisedElement::internal_data_pt(), oomph::Problem::mesh_pt(), oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::GeneralisedElement::ninternal_data(), oomph::FiniteElement::nnodal_position_type(), oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::Data::nvalue(), oomph::SolidNode::pin_position(), oomph::Global_string_for_annotation::string(), and oomph::Data::unpin().
Referenced by set_newmark_initial_condition_consistently(), set_newmark_initial_condition_directly(), and set_static_initial_condition().
set_newmark_initial_condition_consistently()
template<class TIMESTEPPER >
void oomph::SolidICProblem::set_newmark_initial_condition_consistently (Problem * problem_pt, Mesh * mesh_pt, TIMESTEPPER * timestepper_pt, SolidInitialCondition * ic_pt, const double & dt, SolidFiniteElement::MultiplierFctPt multiplier_fct_pt = 0)
Setup initial condition for time-integration with Newmark's method. Past displacements and velocities are assigned directly (consistent with the idea that a second order ODE can take ICs up to 1st order, while the history value for the previous acceleration is determined by the condition that the weak equation is satisfied at the initial time.) The multiplier function needs to specify the factor that multiplies the inertia terms -- typically this is a constant, given by the ratio $ \Lambda^2 $ of the problem's intrinsic timescale to the time used to non-dimensionalise the equations. If the function (pointer) is not specified the multiplier is assumed to be equal to 1.0 -- appropriate for a non-dimensionalisation based on the problem's intrinsic timescale.
Setup initial condition for time-integration with Newmark's method. Past displacements and velocities are assigned directly (consistent with the idea that a second order ODE can take ICs up to 1st order, while the history value for the previous acceleration is determined by the condition that that the weak equation is satisfied at the initial time. The multiplier function needs to specify the factor that multiplies the inertia terms -- typically this is a constant, given by the ratio $ \Lambda^2 $ of the problem's intrinsic timescale to the time used to non-dimensionalise the equations. If the function (pointer) is not specified, the multiplier is assumed to be equal to 1.0 -- appropriate for a non-dimensionalisation based on the problem's intrinsic timescale. Pointer to member type solver
Definition at line 356 of file elastic_problems.h.
References oomph::Problem::assign_eqn_numbers(), backup_original_state(), oomph::Mesh::element_pt(), oomph::SolidFiniteElement::enable_solve_for_consistent_newmark_accel(), oomph::Data::eqn_number(), oomph::SolidInitialCondition::geom_object_pt(), oomph::Problem::get_residuals(), i, IC_pt, oomph::SolidInitialCondition::ic_time_deriv(), oomph::Problem::linear_solver_pt(), oomph::DoubleVector::max(), Max_residual_after_consistent_newton_ic, oomph::Problem::mesh_pt(), oomph::SolidFiniteElement::multiplier_fct_pt(), oomph::Mesh::nelement(), oomph::Problem::newton_solve(), oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::TimeStepper::nprev_values(), oomph::TimeStepper::ntstorage(), oomph::Data::nvalue(), oomph::oomph_info, reset_original_state(), oomph::Data::set_value(), setup_problem(), oomph::SolidFiniteElement::solid_ic_pt(), oomph::LinearSolver::solve(), oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::GeomObject::time_stepper_pt(), oomph::Data::value(), and oomph::Data::value_pt().
set_newmark_initial_condition_directly()
template<class TIMESTEPPER >
void oomph::SolidICProblem::set_newmark_initial_condition_directly (Problem * problem_pt, Mesh * mesh_pt, TIMESTEPPER * timestepper_pt, SolidInitialCondition * ic_pt, const double & dt)
Setup initial condition for time-integration with Newmark's method. History values are assigned to that the velocity and accelerations determined by the Newmark scheme are exact at the initial time.
Definition at line 212 of file elastic_problems.h.
References oomph::Problem::assign_eqn_numbers(), backup_original_state(), oomph::SolidInitialCondition::geom_object_pt(), IC_pt, oomph::SolidInitialCondition::ic_time_deriv(), oomph::Problem::mesh_pt(), oomph::Problem::newton_solve(), oomph::Mesh::nnode(), oomph::oomph_info, reset_original_state(), setup_problem(), oomph::Time::time(), oomph::TimeStepper::time_pt(), and oomph::GeomObject::time_stepper_pt().
set_static_initial_condition() [1/2]
void oomph::SolidICProblem::set_static_initial_condition (Problem * problem_pt, Mesh * mesh_pt, SolidInitialCondition * ic_pt) [inline]
Force the elastic structure that is discretised on the specified mesh to deform in the shape of the initial condition object (wrapper)
Definition at line 126 of file elastic_problems.h.
References oomph::Problem::mesh_pt(), set_static_initial_condition(), and oomph::Problem::time().
set_static_initial_condition() [2/2]
void oomph::SolidICProblem::set_static_initial_condition (Problem * problem_pt, Mesh * mesh_pt, SolidInitialCondition * ic_pt, const double & time)
Force the elastic structure that is discretised on the specified mesh to deform in the shape of the initial condition object (evaluated at the time specified)
IC problem for wall: Deform wall into the static initial shape described by the IC object at given time.
Definition at line 522 of file elastic_problems.cc.
References oomph::Problem::assign_eqn_numbers(), oomph::Problem::assign_initial_values_impulsive(), backup_original_state(), oomph::Problem::Communicator_pt, oomph::Problem::communicator_pt(), oomph::SolidInitialCondition::geom_object_pt(), IC_pt, oomph::SolidInitialCondition::ic_time_deriv(), oomph::Problem::mesh_pt(), oomph::Problem::newton_solve(), oomph::oomph_info, oomph::Problem::Problem_has_been_distributed, oomph::Problem::problem_has_been_distributed(), reset_original_state(), setup_problem(), oomph::Problem::time(), oomph::Time::time(), oomph::TimeStepper::time_pt(), and oomph::GeomObject::time_stepper_pt().
Referenced by set_static_initial_condition().
setup_problem()
void oomph::SolidICProblem::setup_problem () [private]
Change pinned status of all data associated with mesh so that the IC problem can be solved.
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
Setup IC problem by:
Pinning all nodal values in the mesh
Pinning the internal data of all elements.
Freeing/unpinnning all positional data.
Flushing the pointers to the elements' external data.
Setting the pointer to the IC object for all elements to ensure that the correct residuals/Jacobians are computed.
Definition at line 48 of file elastic_problems.cc.
References oomph::Problem::assign_eqn_numbers(), oomph::Mesh::element_pt(), oomph::GeneralisedElement::flush_external_data(), oomph::SolidFiniteElement::has_internal_solid_data(), i, IC_pt, oomph::GeneralisedElement::internal_data_pt(), oomph::Problem::mesh_pt(), oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::GeneralisedElement::ninternal_data(), oomph::FiniteElement::nnodal_position_type(), oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::Data::nvalue(), oomph::oomph_info, oomph::Data::pin(), oomph::SolidFiniteElement::solid_ic_pt(), oomph::Global_string_for_annotation::string(), and oomph::SolidNode::unpin_position().
Referenced by set_newmark_initial_condition_consistently(), set_newmark_initial_condition_directly(), and set_static_initial_condition().
Member Data Documentation
Backup_ext_data
Vector<Vector<Data*> > oomph::SolidICProblem::Backup_ext_data [private]
Vector of Vectors to store pointers to exernal data in the elements.
Definition at line 196 of file elastic_problems.h.
Referenced by backup_original_state(), and reset_original_state().
Backup_pinned
Vector<int> oomph::SolidICProblem::Backup_pinned [private]
Vector to store pinned status of all data.
Definition at line 193 of file elastic_problems.h.
Referenced by backup_original_state(), and reset_original_state().
IC_pt
SolidInitialCondition* oomph::SolidICProblem::IC_pt [private]
Pointer to initial condition object.
Definition at line 190 of file elastic_problems.h.
Referenced by set_newmark_initial_condition_consistently(), set_newmark_initial_condition_directly(), set_static_initial_condition(), and setup_problem().
Max_residual_after_consistent_newton_ic
double oomph::SolidICProblem::Max_residual_after_consistent_newton_ic [private]
Max. tolerated residual after application of consistent Newmark IC. Used to check if we have specified the correct timescale ratio (non-dim density).
Definition at line 201 of file elastic_problems.h.
Referenced by max_residual_after_consistent_newton_ic(), set_newmark_initial_condition_consistently(), and SolidICProblem().
The documentation for this class was generated from the following files:
elastic_problems.h
elastic_problems.cc