oomph::CylinderWithFlagMesh< ELEMENT > Class Template Reference
Domain-based mesh for cylinder with flag as in Turek benchmark.
#include <cylinder_with_flag_mesh.template.h>
Public Member Functions
CylinderWithFlagMesh (Circle *cylinder_pt, GeomObject *top_flag_pt, GeomObject *bottom_flag_pt, GeomObject *tip_flag_pt, const double &length, const double &height, const double &flag_length, const double &flag_height, const double &centre_x, const double &centre_y, const double &a, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor. Pass the pointers to the GeomObjects that parametrise the cylinder, the three edges of the flag, the length and height of the domain, the length and height of the flag, the coordinates of the centre of the cylinder and its radius. Timestepper defaults to Steady default timestepper.
virtual ~CylinderWithFlagMesh ()
Destructor: Kill the domain.
CylinderWithFlagDomain * domain_pt ()
Access function to the domain.
Protected Attributes
CylinderWithFlagDomain * Domain_pt
Pointer to the domain.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::CylinderWithFlagMesh< ELEMENT >
Domain-based mesh for cylinder with flag as in Turek benchmark.
Definition at line 48 of file cylinder_with_flag_mesh.template.h.
Constructor & Destructor Documentation
CylinderWithFlagMesh()
template<class ELEMENT >
oomph::CylinderWithFlagMesh< ELEMENT >::CylinderWithFlagMesh (Circle * cylinder_pt, GeomObject * top_flag_pt, GeomObject * bottom_flag_pt, GeomObject * tip_flag_pt, const double & length, const double & height, const double & flag_length, const double & flag_height, const double & centre_x, const double & centre_y, const double & a, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor. Pass the pointers to the GeomObjects that parametrise the cylinder, the three edges of the flag, the length and height of the domain, the length and height of the flag, the coordinates of the centre of the cylinder and its radius. Timestepper defaults to Steady default timestepper.
Definition at line 43 of file cylinder_with_flag_mesh.template.cc.
References e, and s.
 CylinderWithFlagMesh()
template<class ELEMENT >
virtual oomph::CylinderWithFlagMesh< ELEMENT >::~CylinderWithFlagMesh () [inline], [virtual]
Destructor: Kill the domain.
Definition at line 71 of file cylinder_with_flag_mesh.template.h.
References oomph::CylinderWithFlagMesh< ELEMENT >::Domain_pt.
Member Function Documentation
domain_pt()
template<class ELEMENT >
CylinderWithFlagDomain * oomph::CylinderWithFlagMesh< ELEMENT >::domain_pt () [inline]
Access function to the domain.
Definition at line 77 of file cylinder_with_flag_mesh.template.h.
References oomph::CylinderWithFlagMesh< ELEMENT >::Domain_pt.
Referenced by oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::set_bottom_flag_pt(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::set_tip_flag_pt(), and oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::set_top_flag_pt().
Member Data Documentation
Domain_pt
template<class ELEMENT >
CylinderWithFlagDomain* oomph::CylinderWithFlagMesh< ELEMENT >::Domain_pt [protected]
Pointer to the domain.
Definition at line 84 of file cylinder_with_flag_mesh.template.h.
Referenced by oomph::CylinderWithFlagMesh< ELEMENT >::domain_pt(), and oomph::CylinderWithFlagMesh< ELEMENT >::~CylinderWithFlagMesh().
The documentation for this class was generated from the following files:
cylinder_with_flag_mesh.template.h
cylinder_with_flag_mesh.template.cc