oomph::TElement< 1, NNODE_1D > Class Template Reference
General TElement class specialised to one spatial dimensions Ordering of nodes is 0 at local coordinate s[0] = 0, 1 at local coordinate s[0] = 1 and then filling in the intermediate values from s[0]=0 to 1.
#include <Telements.h>
Public Member Functions
TElement ()
Constructor.
TElement (const TElement &)=delete
Broken copy constructor.
~TElement ()
Broken assignment operator.
unsigned nnode_1d () const
Number of nodes along each element edge.
unsigned nvertex_node () const
Number of vertex nodes in the element: One more than spatial dimension.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void shape (const Vector< double > &s, Shape &psi) const
Calculate the geometric shape functions at local coordinate s.
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Compute the geometric shape functions and derivatives w.r.t. local coordinates at local coordinate s.
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
Compute the geometric shape functions, derivatives and second derivatives w.r.t local coordinates at local coordinate s d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $.
double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Overload the template-free interface for the calculation of inverse jacobian matrix. This is a one dimensional element, so use the 1D version.
double s_min () const
Min. value of local coordinate.
double s_max () const
Max. value of local coordinate.
void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
Return local coordinates of node j.
unsigned nplot_points_paraview (const unsigned &nplot) const
Return the number of actual plot points for paraview plot with parameter nplot.
unsigned nsub_elements_paraview (const unsigned &nplot) const
Return the number of local sub-elements for paraview plot with parameter nplot.
void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
Fill in the offset information for paraview plot. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
Return the paraview element type. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
Return the offsets for the paraview sub-elements. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
void output (std::ostream &output)
Output.
void output (std::ostream &outfile, const unsigned &nplot)
Output at specified number of plot points.
void output (FILE *file_pt)
C-style output.
void output (FILE *file_pt, const unsigned &n_plot)
C_style output at n_plot points.
void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &use_equally_spaced_interior_sample_points=false) const
Get vector of local coordinates of plot point i (when plotting nplot points in each `coordinate direction`).
std::string tecplot_zone_string (const unsigned &nplot) const
Return string for tecplot zone header (when plotting nplot points in each "coordinate direction)
unsigned nplot_points (const unsigned &nplot) const
Return total number of plot points (when plotting nplot points in each "coordinate direction)
void build_face_element (const int &face_index, FaceElement *face_element_pt)
Build the lower-dimensional FaceElement (an element of type PointElement). The face index takes two values corresponding to the two possible faces: -1 (Left) s[0] = -1.0 +1 (Right) s[0] = 1.0.
Static Private Attributes
static TGauss< 1, NNODE_1D > Default_integration_scheme
Default integration rule: Gaussian integration of same 'order' as the element.
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::TElement< 1, NNODE_1D >
General TElement class specialised to one spatial dimensions Ordering of nodes is 0 at local coordinate s[0] = 0, 1 at local coordinate s[0] = 1 and then filling in the intermediate values from s[0]=0 to 1.
Definition at line 1219 of file Telements.h.
Constructor & Destructor Documentation
TElement() [1/2]
template<unsigned NNODE_1D>
oomph::TElement< 1, NNODE_1D >::TElement () [inline]
Constructor.
Definition at line 1232 of file Telements.h.
References oomph::Global_string_for_annotation::string().
TElement() [2/2]
template<unsigned NNODE_1D>
oomph::TElement< 1, NNODE_1D >::TElement (const TElement< 1, NNODE_1D > &) [delete]
Broken copy constructor.
 TElement()
template<unsigned NNODE_1D>
oomph::TElement< 1, NNODE_1D >::~TElement () [inline]
Broken assignment operator.
Destructor
Definition at line 1271 of file Telements.h.
Member Function Documentation
build_face_element()
template<unsigned NNODE_1D>
void oomph::TElement< 1, NNODE_1D >::build_face_element (const int & face_index, FaceElement * face_element_pt) [virtual]
Build the lower-dimensional FaceElement (an element of type PointElement). The face index takes two values corresponding to the two possible faces: -1 (Left) s[0] = -1.0 +1 (Right) s[0] = 1.0.
Function to setup geometrical information for lower-dimensional FaceElements (which are Point Elements).
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidTElement< 1, NNODE_1D >.
Definition at line 177 of file Telements.cc.
References oomph::FaceElement::bulk_coordinate_derivatives_fct_pt(), oomph::FaceElement::bulk_element_pt(), oomph::FaceElement::bulk_node_number(), oomph::FaceElement::bulk_node_number_resize(), oomph::TElement1FaceToBulkCoordinates::face0(), oomph::TElement1FaceToBulkCoordinates::face1(), oomph::FaceElement::face_index(), oomph::FaceElement::face_to_bulk_coordinate_fct_pt(), oomph::TElement1BulkCoordinateDerivatives::faces0(), oomph::FaceElement::nbulk_value(), oomph::FaceElement::nbulk_value_resize(), oomph::FiniteElement::node_pt(), oomph::FaceElement::normal_sign(), oomph::GeneralisedElement::set_halo(), and oomph::FiniteElement::set_nodal_dimension().
d2shape_local()
template<unsigned NNODE_1D>
void oomph::TElement< 1, NNODE_1D >::d2shape_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline], [virtual]
Compute the geometric shape functions, derivatives and second derivatives w.r.t local coordinates at local coordinate s d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $.
Reimplemented from oomph::FiniteElement.
Definition at line 1334 of file Telements.h.
References s.
dshape_local()
template<unsigned NNODE_1D>
void oomph::TElement< 1, NNODE_1D >::dshape_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const [inline], [virtual]
Compute the geometric shape functions and derivatives w.r.t. local coordinates at local coordinate s.
Reimplemented from oomph::FiniteElement.
Definition at line 1322 of file Telements.h.
References s.
get_s_plot()
template<unsigned NNODE_1D>
void oomph::TElement< 1, NNODE_1D >::get_s_plot (const unsigned & i, const unsigned & nplot, Vector< double > & s, const bool & use_equally_spaced_interior_sample_points = false) const [inline], [virtual]
Get vector of local coordinates of plot point i (when plotting nplot points in each `coordinate direction`).
Reimplemented from oomph::FiniteElement.
Definition at line 1446 of file Telements.h.
References i, and s.
invert_jacobian_mapping()
template<unsigned NNODE_1D>
double oomph::TElement< 1, NNODE_1D >::invert_jacobian_mapping (const DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const [inline], [virtual]
Overload the template-free interface for the calculation of inverse jacobian matrix. This is a one dimensional element, so use the 1D version.
Reimplemented from oomph::FiniteElement.
Definition at line 1345 of file Telements.h.
local_coordinate_of_node()
template<unsigned NNODE_1D>
void oomph::TElement< 1, NNODE_1D >::local_coordinate_of_node (const unsigned & j, Vector< double > & s) const [inline], [virtual]
Return local coordinates of node j.
Reimplemented from oomph::FiniteElement.
Definition at line 1364 of file Telements.h.
References s.
nnode_1d()
template<unsigned NNODE_1D>
unsigned oomph::TElement< 1, NNODE_1D >::nnode_1d () const [inline], [virtual]
Number of nodes along each element edge.
Reimplemented from oomph::FiniteElement.
Definition at line 1274 of file Telements.h.
nplot_points()
template<unsigned NNODE_1D>
unsigned oomph::TElement< 1, NNODE_1D >::nplot_points (const unsigned & nplot) const [inline], [virtual]
Return total number of plot points (when plotting nplot points in each "coordinate direction)
Reimplemented from oomph::FiniteElement.
Definition at line 1481 of file Telements.h.
nplot_points_paraview()
template<unsigned NNODE_1D>
unsigned oomph::TElement< 1, NNODE_1D >::nplot_points_paraview (const unsigned & nplot) const [inline], [virtual]
Return the number of actual plot points for paraview plot with parameter nplot.
Reimplemented from oomph::FiniteElement.
Definition at line 1372 of file Telements.h.
nsub_elements_paraview()
template<unsigned NNODE_1D>
unsigned oomph::TElement< 1, NNODE_1D >::nsub_elements_paraview (const unsigned & nplot) const [inline], [virtual]
Return the number of local sub-elements for paraview plot with parameter nplot.
Reimplemented from oomph::FiniteElement.
Definition at line 1379 of file Telements.h.
nvertex_node()
template<unsigned NNODE_1D>
unsigned oomph::TElement< 1, NNODE_1D >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element: One more than spatial dimension.
Reimplemented from oomph::FiniteElement.
Definition at line 1282 of file Telements.h.
output() [1/4]
template<unsigned NNODE_1D>
void oomph::TElement< 1, NNODE_1D >::output (FILE * file_pt) [virtual]
C-style output.
C style output function for general 1D TElements.
Reimplemented from oomph::FiniteElement.
Definition at line 93 of file Telements.cc.
References oomph::CommandLineArgs::output().
output() [2/4]
template<unsigned NNODE_1D>
void oomph::TElement< 1, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [virtual]
C_style output at n_plot points.
C style output function for n_plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Definition at line 102 of file Telements.cc.
References i, and s.
output() [3/4]
template<unsigned NNODE_1D>
void oomph::TElement< 1, NNODE_1D >::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output at specified number of plot points.
The output function for n_plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Definition at line 62 of file Telements.cc.
References i, and s.
output() [4/4]
template<unsigned NNODE_1D>
void oomph::TElement< 1, NNODE_1D >::output (std::ostream & output) [virtual]
Output.
The output function for general 1D TElements.
Reimplemented from oomph::FiniteElement.
Definition at line 53 of file Telements.cc.
References oomph::CommandLineArgs::output().
s_max()
template<unsigned NNODE_1D>
double oomph::TElement< 1, NNODE_1D >::s_max () const [inline], [virtual]
Max. value of local coordinate.
Reimplemented from oomph::FiniteElement.
Definition at line 1358 of file Telements.h.
s_min()
template<unsigned NNODE_1D>
double oomph::TElement< 1, NNODE_1D >::s_min () const [inline], [virtual]
Min. value of local coordinate.
Reimplemented from oomph::FiniteElement.
Definition at line 1352 of file Telements.h.
shape()
template<unsigned NNODE_1D>
void oomph::TElement< 1, NNODE_1D >::shape (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Calculate the geometric shape functions at local coordinate s.
Implements oomph::FiniteElement.
Definition at line 1315 of file Telements.h.
References s, and oomph::OneDimLagrange::shape().
tecplot_zone_string()
template<unsigned NNODE_1D>
std::string oomph::TElement< 1, NNODE_1D >::tecplot_zone_string (const unsigned & nplot) const [inline], [virtual]
Return string for tecplot zone header (when plotting nplot points in each "coordinate direction)
Reimplemented from oomph::FiniteElement.
Definition at line 1472 of file Telements.h.
vertex_node_pt()
template<unsigned NNODE_1D>
Node* oomph::TElement< 1, NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Reimplemented from oomph::FiniteElement.
Definition at line 1288 of file Telements.h.
write_paraview_offsets()
template<unsigned NNODE_1D>
void oomph::TElement< 1, NNODE_1D >::write_paraview_offsets (std::ofstream & file_out, const unsigned & nplot, unsigned & offset_sum) const [inline], [virtual]
Return the offsets for the paraview sub-elements. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
Reimplemented from oomph::FiniteElement.
Definition at line 1418 of file Telements.h.
References i.
write_paraview_output_offset_information()
template<unsigned NNODE_1D>
void oomph::TElement< 1, NNODE_1D >::write_paraview_output_offset_information (std::ofstream & file_out, const unsigned & nplot, unsigned & counter) const [inline], [virtual]
Fill in the offset information for paraview plot. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
Reimplemented from oomph::FiniteElement.
Definition at line 1387 of file Telements.h.
References i.
write_paraview_type()
template<unsigned NNODE_1D>
void oomph::TElement< 1, NNODE_1D >::write_paraview_type (std::ofstream & file_out, const unsigned & nplot) const [inline], [virtual]
Return the paraview element type. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf.
Reimplemented from oomph::FiniteElement.
Definition at line 1405 of file Telements.h.
References i.
Member Data Documentation
Default_integration_scheme
template<unsigned NNODE_1D>
TGauss< 1, NNODE_1D > oomph::TElement< 1, NNODE_1D >::Default_integration_scheme [static], [private]
Default integration rule: Gaussian integration of same 'order' as the element.
Assign the static integral.
Definition at line 1228 of file Telements.h.
The documentation for this class was generated from the following files:
Telements.h
Telements.cc