oomph::QPMLHelmholtzElement< DIM, NNODE_1D > Class Template Reference
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
#include <pml_helmholtz_elements.h>
Public Member Functions
QPMLHelmholtzElement ()
Constructor: Call constructors for QElement and PMLHelmholtz equations.
QPMLHelmholtzElement (const QPMLHelmholtzElement< DIM, NNODE_1D > &dummy)=delete
Broken copy constructor.
unsigned required_nvalue (const unsigned &n) const
Broken assignment operator.
void output (std::ostream &outfile)
Output function: x,y,u or x,y,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output_real (std::ostream &outfile, const double &phi, const unsigned &n_plot)
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
void output_imag (std::ostream &outfile, const double &phi, const unsigned &n_plot)
Output function for imaginary part of full time-dependent solution u = Im((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
void output (FILE *file_pt)
C-style output function: x,y,u or x,y,z,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
void output_real_fct (std::ostream &outfile, const double &phi, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for real part of full time-dependent fct u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
void output_imag_fct (std::ostream &outfile, const double &phi, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for imaginary part of full time-dependent fct u = Im((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (Calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_helmholtz (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_helmholtz (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Static Private Attributes
static const unsigned Initial_Nvalue = 2
Static int that holds the number of variables at nodes: always the same.
Additional Inherited Members
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::QPMLHelmholtzElement< DIM, NNODE_1D >
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
QPMLHelmholtzElement elements are linear/quadrilateral/ brick-shaped PMLHelmholtz elements with isoparametric interpolation for the function.
Definition at line 752 of file pml_helmholtz_elements.h.
Constructor & Destructor Documentation
QPMLHelmholtzElement() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::QPMLHelmholtzElement () [inline]
Constructor: Call constructors for QElement and PMLHelmholtz equations.
Definition at line 763 of file pml_helmholtz_elements.h.
QPMLHelmholtzElement() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::QPMLHelmholtzElement (const QPMLHelmholtzElement< DIM, NNODE_1D > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_helmholtz()
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_helmholtz (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::PMLHelmholtzEquations< DIM >.
Definition at line 945 of file pml_helmholtz_elements.h.
dshape_and_dtest_eulerian_helmholtz()
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_helmholtz (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::PMLHelmholtzEquations< DIM >.
Definition at line 919 of file pml_helmholtz_elements.h.
References s.
output() [1/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function: x,y,u or x,y,z,u.
Reimplemented from oomph::PMLHelmholtzEquations< DIM >.
Definition at line 823 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::output().
output() [2/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::PMLHelmholtzEquations< DIM >.
Definition at line 831 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::output().
output() [3/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: x,y,u or x,y,z,u.
Reimplemented from oomph::PMLHelmholtzEquations< DIM >.
Definition at line 784 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::output().
output() [4/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::PMLHelmholtzEquations< DIM >.
Definition at line 792 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::output().
output_fct() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (Calls the steady version)
Reimplemented from oomph::PMLHelmholtzEquations< DIM >.
Definition at line 879 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::output_fct().
output_fct() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
Reimplemented from oomph::PMLHelmholtzEquations< DIM >.
Definition at line 839 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::output_fct().
output_imag()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::output_imag (std::ostream & outfile, const double & phi, const unsigned & n_plot) [inline]
Output function for imaginary part of full time-dependent solution u = Im((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
Definition at line 813 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::output_imag().
output_imag_fct()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::output_imag_fct (std::ostream & outfile, const double & phi, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline]
Output function for imaginary part of full time-dependent fct u = Im((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
Definition at line 866 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::output_imag_fct().
output_real()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::output_real (std::ostream & outfile, const double & phi, const unsigned & n_plot) [inline]
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
Definition at line 802 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::output_real().
output_real_fct()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::output_real_fct (std::ostream & outfile, const double & phi, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline]
Output function for real part of full time-dependent fct u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
Definition at line 852 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::output_real_fct().
required_nvalue()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Broken assignment operator.
Required # of `values' (pinned or dofs) at node n
Reimplemented from oomph::FiniteElement.
Definition at line 777 of file pml_helmholtz_elements.h.
References oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::Initial_Nvalue.
Member Data Documentation
Initial_Nvalue
template<unsigned DIM, unsigned NNODE_1D>
const unsigned oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::Initial_Nvalue = 2 [static], [private]
Static int that holds the number of variables at nodes: always the same.
Set the data for the number of Variables at each node, always two (real and imag part) in every case.
Definition at line 758 of file pml_helmholtz_elements.h.
Referenced by oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::required_nvalue().
The documentation for this class was generated from the following files:
pml_helmholtz_elements.h
pml_helmholtz_elements.cc