oomph::SuperLUPreconditioner Class Reference
An interface to allow SuperLU to be used as an (exact) Preconditioner.
#include <SuperLU_preconditioner.h>
Public Member Functions
SuperLUPreconditioner ()
Constructor.
~SuperLUPreconditioner ()
Destructor.
SuperLUPreconditioner (const SuperLUPreconditioner &)=delete
Broken copy constructor.
void operator= (const SuperLUPreconditioner &)=delete
Broken assignment operator.
void setup ()
Function to set up a preconditioner for the linear system defined by matrix_pt. This function must be called before using preconditioner_solve. Note: matrix_pt must point to an object of class CRDoubleMatrix or CCDoubleMatrix.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Function applies SuperLU to vector r for (exact) preconditioning, this requires a call to setup(...) first.
void preconditioner_solve_transpose (const DoubleVector &r, DoubleVector &z)
Function applies SuperLU to vector r for (exact) preconditioning (of the transposed matrix system) this requires a call to setup(...) first.
virtual void clean_up_memory ()
Clean up memory -- forward the call to the version in SuperLU in its LinearSolver incarnation.
double get_memory_usage_for_lu_factors ()
Get the amount of memory used to store the LU factors inside SuperLU.
double get_total_memory_needed_for_superlu ()
Get the total memory needed by SuperLU to store AND calculate the LU factors.
Vector< double > get_memory_usage_for_superlu ()
Get the amount of memory taken up by SuperLU. The first entry of the returned result contains the memory used to store the LU factors and the second entry contains the total memory used to store AND calculate the LU factors.
void enable_doc_stats ()
Enable documentation of solver statistics.
void disable_doc_stats ()
Enable documentation of solver statistics.
void enable_doc_time ()
Enable documentation of solver statistics.
void disable_doc_time ()
Enable documentation of solver statistics.
Public Member Functions inherited from oomph::Preconditioner
Preconditioner ()
Constructor.
Preconditioner (const Preconditioner &)=delete
Broken copy constructor.
void operator= (const Preconditioner &)=delete
Broken assignment operator.
virtual ~Preconditioner ()
Destructor (empty)
virtual void setup (DoubleMatrixBase *matrix_pt)
Setup the preconditioner: store the matrix pointer and the communicator pointer then call preconditioner specific setup() function.
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
Compatability layer for old preconditioners where problem pointers were needed. The problem pointer is only used to get a communicator pointer.
void enable_silent_preconditioner_setup ()
Set up the block preconditioner quietly!
void disable_silent_preconditioner_setup ()
Be verbose in the block preconditioner setup.
virtual DoubleMatrixBase * matrix_pt () const
Get function for matrix pointer.
virtual void set_matrix_pt (DoubleMatrixBase *matrix_pt)
Set the matrix pointer.
virtual const OomphCommunicator * comm_pt () const
Get function for comm pointer.
virtual void set_comm_pt (const OomphCommunicator *const comm_pt)
Set the communicator pointer.
double setup_time () const
Returns the time to setup the preconditioner.
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
Virtual interface function for making a preconditioner a subsidiary of a block preconditioner. By default nothing is needed, but if this preconditioner is also a block preconditioner then things need to happen. There's an assumption here that the block preconditioner will be in CR form but since that assumption is hard coded all over BlockPreconditioner we're safe.
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned > > &doftype_coarsen_map_coarse)
Virtual interface function for making a preconditioner a subsidiary of a block preconditioner. By default nothing is needed, but if this preconditioner is also a block preconditioner then things need to happen. Version for coarsening dof-types.
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
if the communicator_pt is null then the distribution is not setup then false is returned, otherwise return true
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
setup the distribution of this distributable linear algebra object
void build_distribution (const LinearAlgebraDistribution &dist)
setup the distribution of this distributable linear algebra object
Private Attributes
SuperLUSolver Solver
the SuperLU solver emplyed by this preconditioner
Additional Inherited Members
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
clear the distribution of this distributable linear algebra object
Protected Attributes inherited from oomph::Preconditioner
bool Silent_preconditioner_setup
Boolean to indicate whether or not the build should be done silently.
std::ostream * Stream_pt
Pointer to the output stream -- defaults to std::cout.
Detailed Description
An interface to allow SuperLU to be used as an (exact) Preconditioner.
Definition at line 42 of file SuperLU_preconditioner.h.
Constructor & Destructor Documentation
SuperLUPreconditioner() [1/2]
oomph::SuperLUPreconditioner::SuperLUPreconditioner () [inline]
Constructor.
Definition at line 46 of file SuperLU_preconditioner.h.
References oomph::SuperLUSolver::disable_doc_stats(), oomph::LinearSolver::disable_doc_time(), and Solver.
~SuperLUPreconditioner()
oomph::SuperLUPreconditioner::~SuperLUPreconditioner () [inline]
Destructor.
Definition at line 53 of file SuperLU_preconditioner.h.
SuperLUPreconditioner() [2/2]
oomph::SuperLUPreconditioner::SuperLUPreconditioner (const SuperLUPreconditioner &) [delete]
Broken copy constructor.
Member Function Documentation
clean_up_memory()
virtual void oomph::SuperLUPreconditioner::clean_up_memory () [inline], [virtual]
Clean up memory -- forward the call to the version in SuperLU in its LinearSolver incarnation.
Reimplemented from oomph::Preconditioner.
Definition at line 109 of file SuperLU_preconditioner.h.
References oomph::SuperLUSolver::clean_up_memory(), and Solver.
disable_doc_stats()
void oomph::SuperLUPreconditioner::disable_doc_stats () [inline]
Enable documentation of solver statistics.
Definition at line 159 of file SuperLU_preconditioner.h.
References oomph::SuperLUSolver::disable_doc_stats(), and Solver.
disable_doc_time()
void oomph::SuperLUPreconditioner::disable_doc_time () [inline]
Enable documentation of solver statistics.
Definition at line 173 of file SuperLU_preconditioner.h.
References oomph::LinearSolver::disable_doc_time(), and Solver.
enable_doc_stats()
void oomph::SuperLUPreconditioner::enable_doc_stats () [inline]
Enable documentation of solver statistics.
Definition at line 152 of file SuperLU_preconditioner.h.
References oomph::SuperLUSolver::enable_doc_stats(), and Solver.
enable_doc_time()
void oomph::SuperLUPreconditioner::enable_doc_time () [inline]
Enable documentation of solver statistics.
Definition at line 166 of file SuperLU_preconditioner.h.
References oomph::LinearSolver::enable_doc_time(), and Solver.
get_memory_usage_for_lu_factors()
double oomph::SuperLUPreconditioner::get_memory_usage_for_lu_factors () [inline]
Get the amount of memory used to store the LU factors inside SuperLU.
Definition at line 115 of file SuperLU_preconditioner.h.
References oomph::SuperLUSolver::get_memory_usage_for_lu_factors(), and Solver.
get_memory_usage_for_superlu()
Vector< double > oomph::SuperLUPreconditioner::get_memory_usage_for_superlu () [inline]
Get the amount of memory taken up by SuperLU. The first entry of the returned result contains the memory used to store the LU factors and the second entry contains the total memory used to store AND calculate the LU factors.
Definition at line 135 of file SuperLU_preconditioner.h.
References oomph::SuperLUSolver::get_memory_usage_for_lu_factors(), oomph::SuperLUSolver::get_total_needed_memory(), and Solver.
get_total_memory_needed_for_superlu()
double oomph::SuperLUPreconditioner::get_total_memory_needed_for_superlu () [inline]
Get the total memory needed by SuperLU to store AND calculate the LU factors.
Definition at line 124 of file SuperLU_preconditioner.h.
References oomph::SuperLUSolver::get_total_needed_memory(), and Solver.
operator=()
void oomph::SuperLUPreconditioner::operator= (const SuperLUPreconditioner &) [delete]
Broken assignment operator.
preconditioner_solve()
void oomph::SuperLUPreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) [inline], [virtual]
Function applies SuperLU to vector r for (exact) preconditioning, this requires a call to setup(...) first.
Implements oomph::Preconditioner.
Definition at line 93 of file SuperLU_preconditioner.h.
References oomph::SuperLUSolver::resolve(), and Solver.
preconditioner_solve_transpose()
void oomph::SuperLUPreconditioner::preconditioner_solve_transpose (const DoubleVector & r, DoubleVector & z) [inline], [virtual]
Function applies SuperLU to vector r for (exact) preconditioning (of the transposed matrix system) this requires a call to setup(...) first.
Reimplemented from oomph::Preconditioner.
Definition at line 101 of file SuperLU_preconditioner.h.
References oomph::SuperLUSolver::resolve_transpose(), and Solver.
setup()
void oomph::SuperLUPreconditioner::setup () [inline], [virtual]
Function to set up a preconditioner for the linear system defined by matrix_pt. This function must be called before using preconditioner_solve. Note: matrix_pt must point to an object of class CRDoubleMatrix or CCDoubleMatrix.
Implements oomph::Preconditioner.
Definition at line 66 of file SuperLU_preconditioner.h.
References oomph::DistributableLinearAlgebraObject::build_distribution(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::SuperLUSolver::factorise(), oomph::Preconditioner::matrix_pt(), oomph::oomph_info, and Solver.
Member Data Documentation
Solver
SuperLUSolver oomph::SuperLUPreconditioner::Solver [private]
the SuperLU solver emplyed by this preconditioner
Definition at line 181 of file SuperLU_preconditioner.h.
Referenced by clean_up_memory(), disable_doc_stats(), disable_doc_time(), enable_doc_stats(), enable_doc_time(), get_memory_usage_for_lu_factors(), get_memory_usage_for_superlu(), get_total_memory_needed_for_superlu(), preconditioner_solve(), preconditioner_solve_transpose(), setup(), and SuperLUPreconditioner().
The documentation for this class was generated from the following file:
SuperLU_preconditioner.h