oomph::BellElementBase< NNODE_1D > Class Template Reference
#include <Subparametric_Telements.h>
Public Member Functions
BellElementBase ()
Constructor: Call constructors for FiniteElement.
virtual void basis (const Vector< double > &s, Shape &psi) const
virtual void dbasis_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void d2basis_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void basis_c0 (const Vector< double > &s, Shape &psi) const
virtual void dbasis_c0_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void d2basis_c0_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void test (const Vector< double > &s, Shape &phi) const
virtual void dtest_local (const Vector< double > &s, Shape &phi, DShape &dphids) const
virtual void d2test_local (const Vector< double > &s, Shape &phi, DShape &dphids, DShape &d2phids) const
void basis_at_knot (const unsigned &ipt, Shape &psi) const
Return the C1-basis function stored at the ipt-th integration point.
void dbasis_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
Return the C1-basis function and its derivatives w.r.t. the global coordinates at the ipt-th integration point.
void d2basis_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
void basis_c0_at_knot (const unsigned &ipt, Shape &psi) const
Return the C0-basis function stored at the ipt-th integration point.
void dbasis_c0_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
Return the C0-basis function and its derivatives w.r.t. the local coordinates at the ipt-th integration point.
void d2basis_c0_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
void test_at_knot (const unsigned &ipt, Shape &phi) const
Return the test function stored at the ipt-th integration point.
void dtest_local_at_knot (const unsigned &ipt, Shape &phi, DShape &dphids) const
Return the test function and its derivatives w.r.t. the local coordinates at the ipt-th integration point.
void d2test_local_at_knot (const unsigned &ipt, Shape &phi, DShape &dphids, DShape &d2phids) const
double dbasis_c0_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsi) const
Compute the curved-element shape functions and also first derivatives w.r.t. local coordinates at local coordinate s; Returns Jacobian of mapping from global to local coordinates. Most general form of the function, but may be over-loaded, if desired.
double d2basis_c0_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsi, DShape &d2psi) const
Compute the c0-basis functions and also first and second derivatives w.r.t. local coordinates at ipt-th integration point.
double dbasis_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsi) const
Compute the c1-basis functions and also first derivatives w.r.t. global coordinates at local coordinate s; Returns Jacobian of mapping from global to local coordinates. Most general form of the function, but may be over-loaded, if desired.
double d2basis_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsi, DShape &d2psi) const
Compute the c1-basis functions and also first and second derivatives w.r.t. global coordinates at ipt-th integration point.
double dshape_and_dtest_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, Shape &test, DShape &dtest) const
double d2shape_and_d2test_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DShape &d2psi, Shape &test, DShape &dtest, DShape &d2test) const
Compute the c1-shape functions and also first and second derivatives w.r.t. global coordinates at ipt-th integration points Returns Jacobian of mapping from global to local coordinates.
double local_to_eulerian_mapping2 (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
Calculate the mapping from local to Eulerian coordinates, given the derivatives of the shape functions w.r.t. local coordinates, Return only the determinant of the jacobian and the inverse of the mapping (ds/dx).
virtual double local_to_eulerian_mapping2 (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double J_eulerian1 (const Vector< double > &s) const
Calculate the Jacobian of the mapping between local and global coordinates at the position s.
void myassemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void my_interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::BellElementBase< NNODE_1D >
Empty base class for the subparametric Bellelements (created so that we can use dynamic_cast<>() to figure out if a an element is a C1Curvedelement). This element is sub-parametric which means the geometry will be parametrised by the linear Lagrange functions, while unknowns will be parametrised by two kinds of shape functions basis : denotes C1-interpolations for c1-variables basis_c0 : denotes C0-interpolations for c0-variables
Definition at line 4938 of file Subparametric_Telements.h.
Constructor & Destructor Documentation
BellElementBase()
template<unsigned NNODE_1D>
oomph::BellElementBase< NNODE_1D >::BellElementBase () [inline]
Constructor: Call constructors for FiniteElement.
Definition at line 4942 of file Subparametric_Telements.h.
Member Function Documentation
basis()
template<unsigned NNODE_1D>
virtual void oomph::BellElementBase< NNODE_1D >::basis (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Reimplemented in oomph::BellElement< DIM, NNODE_1D >.
Definition at line 4945 of file Subparametric_Telements.h.
Referenced by oomph::BellElementBase< NNODE_1D >::basis_at_knot().
basis_at_knot()
template<unsigned NNODE_1D>
void oomph::BellElementBase< NNODE_1D >::basis_at_knot (const unsigned & ipt, Shape & psi) const [inline]
Return the C1-basis function stored at the ipt-th integration point.
Definition at line 4998 of file Subparametric_Telements.h.
References oomph::BellElementBase< NNODE_1D >::basis(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
basis_c0()
template<unsigned NNODE_1D>
virtual void oomph::BellElementBase< NNODE_1D >::basis_c0 (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Reimplemented in oomph::BellElement< DIM, NNODE_1D >.
Definition at line 4961 of file Subparametric_Telements.h.
Referenced by oomph::BellElementBase< NNODE_1D >::basis_c0_at_knot().
basis_c0_at_knot()
template<unsigned NNODE_1D>
void oomph::BellElementBase< NNODE_1D >::basis_c0_at_knot (const unsigned & ipt, Shape & psi) const [inline]
Return the C0-basis function stored at the ipt-th integration point.
Definition at line 5063 of file Subparametric_Telements.h.
References oomph::BellElementBase< NNODE_1D >::basis_c0(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
d2basis_c0_eulerian()
template<unsigned NNODE_1D>
double oomph::BellElementBase< NNODE_1D >::d2basis_c0_eulerian (const Vector< double > & s, Shape & psi, DShape & dpsi, DShape & d2psi) const [inline]
Compute the c0-basis functions and also first and second derivatives w.r.t. local coordinates at ipt-th integration point.
Definition at line 5229 of file Subparametric_Telements.h.
References oomph::BellElementBase< NNODE_1D >::d2basis_c0_local(), oomph::FiniteElement::d2shape_local(), oomph::FiniteElement::dim(), oomph::BellElementBase< NNODE_1D >::local_to_eulerian_mapping2(), oomph::BellElementBase< NNODE_1D >::myassemble_local_to_eulerian_jacobian2(), oomph::FiniteElement::N2deriv, s, and oomph::FiniteElement::transform_second_derivatives().
d2basis_c0_local()
template<unsigned NNODE_1D>
virtual void oomph::BellElementBase< NNODE_1D >::d2basis_c0_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline], [virtual]
Reimplemented in oomph::BellElement< DIM, NNODE_1D >.
Definition at line 4970 of file Subparametric_Telements.h.
Referenced by oomph::BellElementBase< NNODE_1D >::d2basis_c0_eulerian(), and oomph::BellElementBase< NNODE_1D >::d2basis_c0_local_at_knot().
d2basis_c0_local_at_knot()
template<unsigned NNODE_1D>
void oomph::BellElementBase< NNODE_1D >::d2basis_c0_local_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline]
Calculate the C0-basis function and its first and second derivatives w.r.t. local coordinates at the ipt-th integration point.
 Numbering:
Definition at line 5105 of file Subparametric_Telements.h.
References oomph::BellElementBase< NNODE_1D >::d2basis_c0_local(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
d2basis_eulerian()
template<unsigned NNODE_1D>
double oomph::BellElementBase< NNODE_1D >::d2basis_eulerian (const Vector< double > & s, Shape & psi, DShape & dpsi, DShape & d2psi) const [inline]
Compute the c1-basis functions and also first and second derivatives w.r.t. global coordinates at ipt-th integration point.
Definition at line 5310 of file Subparametric_Telements.h.
References oomph::BellElementBase< NNODE_1D >::d2basis_local(), oomph::FiniteElement::d2shape_local(), oomph::FiniteElement::dim(), oomph::BellElementBase< NNODE_1D >::local_to_eulerian_mapping2(), and s.
d2basis_local()
template<unsigned NNODE_1D>
virtual void oomph::BellElementBase< NNODE_1D >::d2basis_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline], [virtual]
Reimplemented in oomph::BellElement< DIM, NNODE_1D >.
Definition at line 4954 of file Subparametric_Telements.h.
Referenced by oomph::BellElementBase< NNODE_1D >::d2basis_eulerian(), and oomph::BellElementBase< NNODE_1D >::d2basis_local_at_knot().
d2basis_local_at_knot()
template<unsigned NNODE_1D>
void oomph::BellElementBase< NNODE_1D >::d2basis_local_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsids, DShape & d2psids) const [inline]
Calculate the C1-basis function and its first and second derivatives w.r.t. global coordinates at the ipt-th integration point.
 Numbering:
Definition at line 5040 of file Subparametric_Telements.h.
References oomph::BellElementBase< NNODE_1D >::d2basis_local(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
Referenced by oomph::BellElementBase< NNODE_1D >::d2shape_and_d2test_eulerian_at_knot().
d2shape_and_d2test_eulerian_at_knot()
template<unsigned NNODE_1D>
double oomph::BellElementBase< NNODE_1D >::d2shape_and_d2test_eulerian_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsi, DShape & d2psi, Shape & test, DShape & dtest, DShape & d2test) const [inline]
Compute the c1-shape functions and also first and second derivatives w.r.t. global coordinates at ipt-th integration points Returns Jacobian of mapping from global to local coordinates.
Definition at line 5387 of file Subparametric_Telements.h.
References oomph::BellElementBase< NNODE_1D >::d2basis_local_at_knot(), oomph::BellElementBase< NNODE_1D >::d2test_local_at_knot(), oomph::FiniteElement::dim(), oomph::FiniteElement::dshape_local_at_knot(), oomph::BellElementBase< NNODE_1D >::local_to_eulerian_mapping2(), oomph::FiniteElement::nnode(), and oomph::BellElementBase< NNODE_1D >::test().
d2test_local()
template<unsigned NNODE_1D>
virtual void oomph::BellElementBase< NNODE_1D >::d2test_local (const Vector< double > & s, Shape & phi, DShape & dphids, DShape & d2phids) const [inline], [virtual]
Reimplemented in oomph::BellElement< DIM, NNODE_1D >.
Definition at line 4986 of file Subparametric_Telements.h.
Referenced by oomph::BellElementBase< NNODE_1D >::d2test_local_at_knot().
d2test_local_at_knot()
template<unsigned NNODE_1D>
void oomph::BellElementBase< NNODE_1D >::d2test_local_at_knot (const unsigned & ipt, Shape & phi, DShape & dphids, DShape & d2phids) const [inline]
Calculate the test function and its first and second derivatives w.r.t. local coordinates at the ipt-th integration point.
 Numbering:
Definition at line 5168 of file Subparametric_Telements.h.
References oomph::BellElementBase< NNODE_1D >::d2test_local(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
Referenced by oomph::BellElementBase< NNODE_1D >::d2shape_and_d2test_eulerian_at_knot().
dbasis_c0_eulerian()
template<unsigned NNODE_1D>
double oomph::BellElementBase< NNODE_1D >::dbasis_c0_eulerian (const Vector< double > & s, Shape & psi, DShape & dpsi) const [inline]
Compute the curved-element shape functions and also first derivatives w.r.t. local coordinates at local coordinate s; Returns Jacobian of mapping from global to local coordinates. Most general form of the function, but may be over-loaded, if desired.
Definition at line 5192 of file Subparametric_Telements.h.
References oomph::FiniteElement::d2shape_local(), oomph::BellElementBase< NNODE_1D >::dbasis_c0_local(), oomph::FiniteElement::dim(), oomph::BellElementBase< NNODE_1D >::local_to_eulerian_mapping2(), s, and oomph::FiniteElement::transform_derivatives().
dbasis_c0_local()
template<unsigned NNODE_1D>
virtual void oomph::BellElementBase< NNODE_1D >::dbasis_c0_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const [inline], [virtual]
Reimplemented in oomph::BellElement< DIM, NNODE_1D >.
Definition at line 4964 of file Subparametric_Telements.h.
Referenced by oomph::BellElementBase< NNODE_1D >::dbasis_c0_eulerian(), and oomph::BellElementBase< NNODE_1D >::dbasis_c0_local_at_knot().
dbasis_c0_local_at_knot()
template<unsigned NNODE_1D>
void oomph::BellElementBase< NNODE_1D >::dbasis_c0_local_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsids) const [inline]
Return the C0-basis function and its derivatives w.r.t. the local coordinates at the ipt-th integration point.
Definition at line 5082 of file Subparametric_Telements.h.
References oomph::BellElementBase< NNODE_1D >::dbasis_c0_local(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
Referenced by oomph::BellElementBase< NNODE_1D >::dshape_and_dtest_eulerian_at_knot().
dbasis_eulerian()
template<unsigned NNODE_1D>
double oomph::BellElementBase< NNODE_1D >::dbasis_eulerian (const Vector< double > & s, Shape & psi, DShape & dpsi) const [inline]
Compute the c1-basis functions and also first derivatives w.r.t. global coordinates at local coordinate s; Returns Jacobian of mapping from global to local coordinates. Most general form of the function, but may be over-loaded, if desired.
Definition at line 5276 of file Subparametric_Telements.h.
References oomph::FiniteElement::d2shape_local(), oomph::BellElementBase< NNODE_1D >::dbasis_local(), oomph::FiniteElement::dim(), oomph::BellElementBase< NNODE_1D >::local_to_eulerian_mapping2(), and s.
dbasis_local()
template<unsigned NNODE_1D>
virtual void oomph::BellElementBase< NNODE_1D >::dbasis_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const [inline], [virtual]
Reimplemented in oomph::BellElement< DIM, NNODE_1D >.
Definition at line 4948 of file Subparametric_Telements.h.
Referenced by oomph::BellElementBase< NNODE_1D >::dbasis_eulerian(), and oomph::BellElementBase< NNODE_1D >::dbasis_local_at_knot().
dbasis_local_at_knot()
template<unsigned NNODE_1D>
void oomph::BellElementBase< NNODE_1D >::dbasis_local_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsids) const [inline]
Return the C1-basis function and its derivatives w.r.t. the global coordinates at the ipt-th integration point.
Definition at line 5017 of file Subparametric_Telements.h.
References oomph::BellElementBase< NNODE_1D >::dbasis_local(), oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
dshape_and_dtest_eulerian_at_knot()
template<unsigned NNODE_1D>
double oomph::BellElementBase< NNODE_1D >::dshape_and_dtest_eulerian_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsi, Shape & test, DShape & dtest) const [inline]
Calculate the c0-shape function and its first-order derivatives w.r.t. local coordinates at the ipt-th integration point.
 Numbering:
Definition at line 5347 of file Subparametric_Telements.h.
References oomph::BellElementBase< NNODE_1D >::dbasis_c0_local_at_knot(), oomph::FiniteElement::dim(), oomph::FiniteElement::dshape_local_at_knot(), oomph::BellElementBase< NNODE_1D >::dtest_local_at_knot(), oomph::BellElementBase< NNODE_1D >::local_to_eulerian_mapping2(), oomph::BellElementBase< NNODE_1D >::test(), and oomph::FiniteElement::transform_derivatives().
dtest_local()
template<unsigned NNODE_1D>
virtual void oomph::BellElementBase< NNODE_1D >::dtest_local (const Vector< double > & s, Shape & phi, DShape & dphids) const [inline], [virtual]
Reimplemented in oomph::BellElement< DIM, NNODE_1D >.
Definition at line 4980 of file Subparametric_Telements.h.
Referenced by oomph::BellElementBase< NNODE_1D >::dtest_local_at_knot().
dtest_local_at_knot()
template<unsigned NNODE_1D>
void oomph::BellElementBase< NNODE_1D >::dtest_local_at_knot (const unsigned & ipt, Shape & phi, DShape & dphids) const [inline]
Return the test function and its derivatives w.r.t. the local coordinates at the ipt-th integration point.
Definition at line 5146 of file Subparametric_Telements.h.
References oomph::FiniteElement::dim(), oomph::BellElementBase< NNODE_1D >::dtest_local(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), and s.
Referenced by oomph::BellElementBase< NNODE_1D >::dshape_and_dtest_eulerian_at_knot().
J_eulerian1()
template<unsigned NNODE_1D>
double oomph::BellElementBase< NNODE_1D >::J_eulerian1 (const Vector< double > & s) const [inline]
Calculate the Jacobian of the mapping between local and global coordinates at the position s.
Definition at line 5487 of file Subparametric_Telements.h.
References oomph::FiniteElement::check_jacobian(), oomph::FiniteElement::dim(), oomph::FiniteElement::dshape_local(), i, oomph::FiniteElement::nodal_dimension(), oomph::oomph_info, and oomph::FiniteElement::raw_nodal_position_gen().
local_to_eulerian_mapping2() [1/2]
template<unsigned NNODE_1D>
double oomph::BellElementBase< NNODE_1D >::local_to_eulerian_mapping2 (const DShape & dpsids, DenseMatrix< double > & inverse_jacobian) const [inline]
Calculate the mapping from local to Eulerian coordinates, given the derivatives of the shape functions w.r.t. local coordinates, Return only the determinant of the jacobian and the inverse of the mapping (ds/dx).
Definition at line 5428 of file Subparametric_Telements.h.
References oomph::FiniteElement::dim().
Referenced by oomph::BellElementBase< NNODE_1D >::d2basis_c0_eulerian(), oomph::BellElementBase< NNODE_1D >::d2basis_eulerian(), oomph::BellElementBase< NNODE_1D >::d2shape_and_d2test_eulerian_at_knot(), oomph::BellElementBase< NNODE_1D >::dbasis_c0_eulerian(), oomph::BellElementBase< NNODE_1D >::dbasis_eulerian(), and oomph::BellElementBase< NNODE_1D >::dshape_and_dtest_eulerian_at_knot().
local_to_eulerian_mapping2() [2/2]
template<unsigned NNODE_1D>
virtual double oomph::BellElementBase< NNODE_1D >::local_to_eulerian_mapping2 (const DShape & dpsids, DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const [inline], [virtual]
Definition at line 5440 of file Subparametric_Telements.h.
References oomph::FiniteElement::dim(), i, oomph::FiniteElement::invert_jacobian_mapping(), and oomph::FiniteElement::raw_nodal_position_gen().
my_interpolated_x()
template<unsigned NNODE_1D>
void oomph::BellElementBase< NNODE_1D >::my_interpolated_x (const Vector< double > & s, Vector< double > & x) const [inline]
Return FE interpolated position x[] at local coordinate s as Vector.
Definition at line 5624 of file Subparametric_Telements.h.
References i, oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::nodal_position_gen(), s, and oomph::FiniteElement::shape().
myassemble_local_to_eulerian_jacobian2()
template<unsigned NNODE_1D>
void oomph::BellElementBase< NNODE_1D >::myassemble_local_to_eulerian_jacobian2 (const DShape & d2psids, DenseMatrix< double > & jacobian2) const [inline]
Internal function that is used to assemble the jacobian of second derivatives of the the mapping from local coordinates (s) to the eulerian coordinates (x), given the second derivatives of the shape functions.
Definition at line 5581 of file Subparametric_Telements.h.
References oomph::FiniteElement::dim(), i, oomph::FiniteElement::N2deriv, and oomph::FiniteElement::raw_nodal_position_gen().
Referenced by oomph::BellElementBase< NNODE_1D >::d2basis_c0_eulerian().
test()
template<unsigned NNODE_1D>
virtual void oomph::BellElementBase< NNODE_1D >::test (const Vector< double > & s, Shape & phi) const [inline], [virtual]
Reimplemented in oomph::BellElement< DIM, NNODE_1D >.
Definition at line 4977 of file Subparametric_Telements.h.
Referenced by oomph::BellElementBase< NNODE_1D >::d2shape_and_d2test_eulerian_at_knot(), oomph::BellElementBase< NNODE_1D >::dshape_and_dtest_eulerian_at_knot(), and oomph::BellElementBase< NNODE_1D >::test_at_knot().
test_at_knot()
template<unsigned NNODE_1D>
void oomph::BellElementBase< NNODE_1D >::test_at_knot (const unsigned & ipt, Shape & phi) const [inline]
Return the test function stored at the ipt-th integration point.
Definition at line 5127 of file Subparametric_Telements.h.
References oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), s, and oomph::BellElementBase< NNODE_1D >::test().
The documentation for this class was generated from the following file:
Subparametric_Telements.h