oomph::RefineableAlgebraicCollapsibleChannelMesh< ELEMENT > Class Template Reference
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
#include <collapsible_channel_mesh.template.h>
Public Member Functions
RefineableAlgebraicCollapsibleChannelMesh (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly, GeomObject *wall_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass number of elements in upstream/collapsible/ downstream segment and across the channel; lengths of upstream/ collapsible/downstream segments and width of channel, pointer to GeomObject that defines the collapsible segment and pointer to TimeStepper (defaults to the default timestepper, Steady).
RefineableAlgebraicCollapsibleChannelMesh (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly, GeomObject *wall_pt, CollapsibleChannelDomain::BLSquashFctPt bl_squash_function_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass number of elements in upstream/collapsible/ downstream segment and across the channel; lengths of upstream/ collapsible/downstream segments and width of channel, pointer to GeomObject that defines the collapsible segment and pointer to TimeStepper (defaults to the default timestepper, Steady).
void update_node_update (AlgebraicNode *&node_pt)
Update the node update data for specified node following any mesh adapation.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::RefineableAlgebraicCollapsibleChannelMesh< ELEMENT >
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Refineable version of the CollapsibleChannel mesh with algebraic node update.
Definition at line 588 of file collapsible_channel_mesh.template.h.
Constructor & Destructor Documentation
RefineableAlgebraicCollapsibleChannelMesh() [1/2]
template<class ELEMENT >
oomph::RefineableAlgebraicCollapsibleChannelMesh< ELEMENT >::RefineableAlgebraicCollapsibleChannelMesh (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly, GeomObject * wall_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass number of elements in upstream/collapsible/ downstream segment and across the channel; lengths of upstream/ collapsible/downstream segments and width of channel, pointer to GeomObject that defines the collapsible segment and pointer to TimeStepper (defaults to the default timestepper, Steady).
Definition at line 598 of file collapsible_channel_mesh.template.h.
References oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest().
RefineableAlgebraicCollapsibleChannelMesh() [2/2]
template<class ELEMENT >
oomph::RefineableAlgebraicCollapsibleChannelMesh< ELEMENT >::RefineableAlgebraicCollapsibleChannelMesh (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly, GeomObject * wall_pt, CollapsibleChannelDomain::BLSquashFctPt bl_squash_function_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass number of elements in upstream/collapsible/ downstream segment and across the channel; lengths of upstream/ collapsible/downstream segments and width of channel, pointer to GeomObject that defines the collapsible segment and pointer to TimeStepper (defaults to the default timestepper, Steady).
Definition at line 640 of file collapsible_channel_mesh.template.h.
References oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest().
Member Function Documentation
update_node_update()
template<class ELEMENT >
void oomph::RefineableAlgebraicCollapsibleChannelMesh< ELEMENT >::update_node_update (AlgebraicNode *& node_pt) [virtual]
Update the node update data for specified node following any mesh adapation.
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
Update the geometric references that are used to update node after mesh adaptation.
Reimplemented from oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >.
Definition at line 437 of file collapsible_channel_mesh.template.cc.
References oomph::AlgebraicNode::add_node_update_info(), oomph::AlgebraicNode::kill_node_update_info(), oomph::GeomObject::locate_zeta(), s, oomph::AlgebraicNode::vector_geom_object_pt(), and oomph::AlgebraicNode::vector_ref_value().
The documentation for this class was generated from the following files:
collapsible_channel_mesh.template.h
collapsible_channel_mesh.template.cc