oomph::RefineableSpaceTimeNavierStokesEquations< DIM > Class Template Reference
Refineable version of the Navier-Stokes equations.
#include <refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h>
Public Member Functions
RefineableSpaceTimeNavierStokesEquations ()
Constructor.
virtual Node * pressure_node_pt (const unsigned &n_p)
Pointer to n_p-th pressure node (Default: NULL, indicating that pressure is not based on nodal interpolation).
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
void further_build ()
Further build, pass the pointers down to the sons.
void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information.
RefineableSpaceTimeNavierStokesEquations ()
Constructor.
virtual Node * pressure_node_pt (const unsigned &n_p)
Pointer to n_p-th pressure node (Default: NULL, indicating that pressure is not based on nodal interpolation).
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
void further_build ()
Further build, pass the pointers down to the sons.
void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information.
RefineableSpaceTimeNavierStokesEquations ()
Constructor.
virtual Node * pressure_node_pt (const unsigned &n_p)
Pointer to n_p-th pressure node (Default: NULL, indicating that pressure is not based on nodal interpolation).
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
void further_build ()
Further build, pass the pointers down to the sons.
void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information.
Static Public Member Functions
static void pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > &element_pt)
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function.
static void unpin_all_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in vector.
static void pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > &element_pt)
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function.
static void unpin_all_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in vector.
static void pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > &element_pt)
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function.
static void unpin_all_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in vector.
Protected Member Functions
virtual void unpin_elemental_pressure_dofs ()=0
Unpin all pressure dofs in the element.
virtual void pin_elemental_redundant_nodal_pressure_dofs ()
Pin unused nodal pressure dofs (empty by default, because by default pressure dofs are not associated with nodes)
void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, const unsigned &compute_jacobian_flag)
Add the elements contribution to elemental residual vector and/or Jacobian matrix. compute_jacobian_flag=0: compute residual vector only compute_jacobian_flag=1: compute both.
void fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &compute_jacobian_flag)
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}.
virtual void unpin_elemental_pressure_dofs ()=0
Unpin all pressure dofs in the element.
virtual void pin_elemental_redundant_nodal_pressure_dofs ()
Pin unused nodal pressure dofs (empty by default, because by default pressure dofs are not associated with nodes)
void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, const unsigned &compute_jacobian_flag)
Add the elements contribution to elemental residual vector and/or Jacobian matrix. compute_jacobian_flag=0: compute residual vector only compute_jacobian_flag=1: compute both.
void fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &compute_jacobian_flag)
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}.
virtual void unpin_elemental_pressure_dofs ()=0
Unpin all pressure dofs in the element.
virtual void pin_elemental_redundant_nodal_pressure_dofs ()
Pin unused nodal pressure dofs (empty by default, because by default pressure dofs are not associated with nodes)
void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, const unsigned &compute_jacobian_flag)
Add the elements contribution to elemental residual vector and/or Jacobian matrix. compute_jacobian_flag=0: compute residual vector only compute_jacobian_flag=1: compute both.
void fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &compute_jacobian_flag)
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::RefineableSpaceTimeNavierStokesEquations< DIM >
Refineable version of the Navier-Stokes equations.
Definition at line 339 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Constructor & Destructor Documentation
RefineableSpaceTimeNavierStokesEquations() [1/3]
template<unsigned DIM>
oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::RefineableSpaceTimeNavierStokesEquations () [inline]
Constructor.
Definition at line 354 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
RefineableSpaceTimeNavierStokesEquations() [2/3]
template<unsigned DIM>
oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::RefineableSpaceTimeNavierStokesEquations () [inline]
Constructor.
Definition at line 354 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
RefineableSpaceTimeNavierStokesEquations() [3/3]
template<unsigned DIM>
oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::RefineableSpaceTimeNavierStokesEquations () [inline]
Constructor.
Definition at line 354 of file refineable_spacetime_navier_stokes_elements.h.
Member Function Documentation
dinterpolated_u_nst_ddata() [1/3]
template<unsigned DIM>
void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata (const Vector< double > & s, const unsigned & i, Vector< double > & du_ddata, Vector< unsigned > & global_eqn_number) [inline], [virtual]
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
Definition at line 579 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::Data::eqn_number(), oomph::Node::hanging_pt(), oomph::Node::is_hanging(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::shape(), and oomph::SpaceTimeNavierStokesEquations< DIM >::u_index_nst().
dinterpolated_u_nst_ddata() [2/3]
template<unsigned DIM>
void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata (const Vector< double > & s, const unsigned & i, Vector< double > & du_ddata, Vector< unsigned > & global_eqn_number) [inline], [virtual]
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
Definition at line 579 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::Data::eqn_number(), oomph::Node::hanging_pt(), oomph::Node::is_hanging(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::shape(), and oomph::SpaceTimeNavierStokesEquations< DIM >::u_index_nst().
dinterpolated_u_nst_ddata() [3/3]
template<unsigned DIM>
void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata (const Vector< double > & s, const unsigned & i, Vector< double > & du_ddata, Vector< unsigned > & global_eqn_number) [inline], [virtual]
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
Definition at line 579 of file refineable_spacetime_navier_stokes_elements.h.
References oomph::Data::eqn_number(), oomph::Node::hanging_pt(), oomph::Node::is_hanging(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::shape(), and oomph::SpaceTimeNavierStokesEquations< DIM >::u_index_nst().
fill_in_generic_pressure_advection_diffusion_contribution_nst() [1/3]
template<unsigned DIM>
void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & compute_jacobian_flag) [protected], [virtual]
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
fill_in_generic_pressure_advection_diffusion_contribution_nst() [2/3]
template<unsigned DIM>
void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected], [virtual]
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
Definition at line 286 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References e, i, interpolated_u(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), residuals(), s, and oomph::QuadTreeNames::W.
fill_in_generic_pressure_advection_diffusion_contribution_nst() [3/3]
template<unsigned DIM>
void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & compute_jacobian_flag) [protected], [virtual]
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
fill_in_generic_residual_contribution_nst() [1/3]
template<unsigned DIM>
void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, const unsigned & compute_jacobian_flag) [protected], [virtual]
Add the elements contribution to elemental residual vector and/or Jacobian matrix. compute_jacobian_flag=0: compute residual vector only compute_jacobian_flag=1: compute both.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
fill_in_generic_residual_contribution_nst() [2/3]
template<unsigned DIM>
void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, const unsigned & flag) [protected], [virtual]
Add the elements contribution to elemental residual vector and/or Jacobian matrix. compute_jacobian_flag=0: compute residual vector only compute_jacobian_flag=1: compute both.
Add element's contribution to the elemental residual vector and/or Jacobian matrix. flag=1: compute both flag=0: compute only residual vector
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
Definition at line 580 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References oomph::ALE_is_disabled, i, interpolated_u(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), residuals(), s, and oomph::QuadTreeNames::W.
fill_in_generic_residual_contribution_nst() [3/3]
template<unsigned DIM>
void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, const unsigned & compute_jacobian_flag) [protected], [virtual]
Add the elements contribution to elemental residual vector and/or Jacobian matrix. compute_jacobian_flag=0: compute residual vector only compute_jacobian_flag=1: compute both.
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
further_build() [1/3]
template<unsigned DIM>
void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build () [inline], [virtual]
Further build, pass the pointers down to the sons.
Reimplemented from oomph::RefineableElement.
Definition at line 521 of file refineable_spacetime_navier_stokes_elements.h.
References oomph::SpaceTimeNavierStokesEquations< DIM >::ALE_is_disabled, oomph::SpaceTimeNavierStokesEquations< DIM >::Body_force_fct_pt, oomph::SpaceTimeNavierStokesEquations< DIM >::Density_Ratio_pt, oomph::RefineableElement::father_element_pt(), oomph::SpaceTimeNavierStokesEquations< DIM >::G_pt, oomph::SpaceTimeNavierStokesEquations< DIM >::Re_pt, oomph::SpaceTimeNavierStokesEquations< DIM >::ReInvFr_pt, oomph::SpaceTimeNavierStokesEquations< DIM >::Source_fct_pt, oomph::SpaceTimeNavierStokesEquations< DIM >::St_pt, oomph::SpaceTimeNavierStokesEquations< DIM >::store_strouhal_as_external_data(), oomph::SpaceTimeNavierStokesEquations< DIM >::Strouhal_is_stored_as_external_data, and oomph::SpaceTimeNavierStokesEquations< DIM >::Viscosity_Ratio_pt.
further_build() [2/3]
template<unsigned DIM>
void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build () [inline], [virtual]
Further build, pass the pointers down to the sons.
Reimplemented from oomph::RefineableElement.
Definition at line 521 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::SpaceTimeNavierStokesEquations< DIM >::ALE_is_disabled, oomph::SpaceTimeNavierStokesEquations< DIM >::Body_force_fct_pt, oomph::SpaceTimeNavierStokesEquations< DIM >::body_force_fct_pt(), oomph::SpaceTimeNavierStokesEquations< DIM >::Density_Ratio_pt, oomph::SpaceTimeNavierStokesEquations< DIM >::density_ratio_pt(), oomph::GeneralisedElement::external_data_pt(), oomph::RefineableElement::father_element_pt(), oomph::SpaceTimeNavierStokesEquations< DIM >::G_pt, oomph::SpaceTimeNavierStokesEquations< DIM >::g_pt(), oomph::SpaceTimeNavierStokesEquations< DIM >::is_strouhal_stored_as_external_data(), oomph::SpaceTimeNavierStokesEquations< DIM >::re_invfr_pt(), oomph::SpaceTimeNavierStokesEquations< DIM >::Re_pt, oomph::SpaceTimeNavierStokesEquations< DIM >::re_pt(), oomph::SpaceTimeNavierStokesEquations< DIM >::ReInvFr_pt, oomph::SpaceTimeNavierStokesEquations< DIM >::Source_fct_pt, oomph::SpaceTimeNavierStokesEquations< DIM >::source_fct_pt(), oomph::SpaceTimeNavierStokesEquations< DIM >::St_pt, oomph::SpaceTimeNavierStokesEquations< DIM >::st_pt(), oomph::SpaceTimeNavierStokesEquations< DIM >::store_strouhal_as_external_data(), oomph::SpaceTimeNavierStokesEquations< DIM >::Strouhal_is_stored_as_external_data, oomph::SpaceTimeNavierStokesEquations< DIM >::Viscosity_Ratio_pt, and oomph::SpaceTimeNavierStokesEquations< DIM >::viscosity_ratio_pt().
further_build() [3/3]
template<unsigned DIM>
void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::further_build () [inline], [virtual]
Further build, pass the pointers down to the sons.
Reimplemented from oomph::RefineableElement.
Definition at line 521 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::SpaceTimeNavierStokesEquations< DIM >::ALE_is_disabled, oomph::SpaceTimeNavierStokesEquations< DIM >::Body_force_fct_pt, oomph::SpaceTimeNavierStokesEquations< DIM >::Density_Ratio_pt, oomph::RefineableElement::father_element_pt(), oomph::SpaceTimeNavierStokesEquations< DIM >::G_pt, oomph::SpaceTimeNavierStokesEquations< DIM >::Re_pt, oomph::SpaceTimeNavierStokesEquations< DIM >::ReInvFr_pt, oomph::SpaceTimeNavierStokesEquations< DIM >::Source_fct_pt, oomph::SpaceTimeNavierStokesEquations< DIM >::St_pt, oomph::SpaceTimeNavierStokesEquations< DIM >::store_strouhal_as_external_data(), oomph::SpaceTimeNavierStokesEquations< DIM >::Strouhal_is_stored_as_external_data, and oomph::SpaceTimeNavierStokesEquations< DIM >::Viscosity_Ratio_pt.
get_dresidual_dnodal_coordinates() [1/3]
template<unsigned DIM>
virtual void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates (RankThreeTensor< double > & dresidual_dnodal_coordinates) [protected], [virtual]
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}.
Reimplemented from oomph::RefineableElement.
get_dresidual_dnodal_coordinates() [2/3]
template<unsigned DIM>
void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates (RankThreeTensor< double > & dresidual_dnodal_coordinates) [protected], [virtual]
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}.
Compute derivatives of elemental residual vector with respect to nodal coordinates. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij} Overloads the FD-based version in the FE base class.
Reimplemented from oomph::RefineableElement.
Definition at line 1292 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References oomph::ALE_is_disabled, oomph::GeneralisedElement::Default_fd_jacobian_step, oomph::Node::has_auxiliary_node_update_fct_pt(), i, interpolated_u(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::Node::perform_auxiliary_node_update_fct(), s, oomph::Data::value_pt(), and oomph::Node::x().
get_dresidual_dnodal_coordinates() [3/3]
template<unsigned DIM>
virtual void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates (RankThreeTensor< double > & dresidual_dnodal_coordinates) [protected], [virtual]
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}.
Reimplemented from oomph::RefineableElement.
get_pressure_and_velocity_mass_matrix_diagonal() [1/3]
template<unsigned DIM>
void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > & press_mass_diag, Vector< double > & veloc_mass_diag, const unsigned & which_one = 0) [virtual]
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
get_pressure_and_velocity_mass_matrix_diagonal() [2/3]
template<unsigned DIM>
void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > & press_mass_diag, Vector< double > & veloc_mass_diag, const unsigned & which_one = 0) [virtual]
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
get_pressure_and_velocity_mass_matrix_diagonal() [3/3]
template<unsigned DIM>
void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > & press_mass_diag, Vector< double > & veloc_mass_diag, const unsigned & which_one = 0) [virtual]
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 -- the LSC version of the preconditioner only needs that one)
Reimplemented from oomph::SpaceTimeNavierStokesEquations< DIM >.
Definition at line 43 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc.
References i, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), s, and oomph::QuadTreeNames::W.
get_Z2_flux() [1/3]
template<unsigned DIM>
void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 437 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian(), i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::SpaceTimeNavierStokesEquations< DIM >::strain_rate(), and oomph::SpaceTimeNavierStokesEquations< DIM >::u_index_nst().
get_Z2_flux() [2/3]
template<unsigned DIM>
void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 437 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian(), i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::SpaceTimeNavierStokesEquations< DIM >::strain_rate(), and oomph::SpaceTimeNavierStokesEquations< DIM >::u_index_nst().
get_Z2_flux() [3/3]
template<unsigned DIM>
void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 437 of file refineable_spacetime_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian(), i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::SpaceTimeNavierStokesEquations< DIM >::strain_rate(), and oomph::SpaceTimeNavierStokesEquations< DIM >::u_index_nst().
num_Z2_flux_terms() [1/3]
template<unsigned DIM>
unsigned oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 427 of file refineable_spacetime_navier_stokes_elements.h.
num_Z2_flux_terms() [2/3]
template<unsigned DIM>
unsigned oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 427 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
num_Z2_flux_terms() [3/3]
template<unsigned DIM>
unsigned oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 427 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
pin_elemental_redundant_nodal_pressure_dofs() [1/3]
template<unsigned DIM>
virtual void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::pin_elemental_redundant_nodal_pressure_dofs () [inline], [protected], [virtual]
Pin unused nodal pressure dofs (empty by default, because by default pressure dofs are not associated with nodes)
Reimplemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
Definition at line 350 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::pin_redundant_nodal_pressures().
pin_elemental_redundant_nodal_pressure_dofs() [2/3]
template<unsigned DIM>
virtual void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::pin_elemental_redundant_nodal_pressure_dofs () [inline], [protected], [virtual]
Pin unused nodal pressure dofs (empty by default, because by default pressure dofs are not associated with nodes)
Reimplemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
Definition at line 350 of file refineable_spacetime_navier_stokes_elements.h.
pin_elemental_redundant_nodal_pressure_dofs() [3/3]
template<unsigned DIM>
virtual void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::pin_elemental_redundant_nodal_pressure_dofs () [inline], [protected], [virtual]
Pin unused nodal pressure dofs (empty by default, because by default pressure dofs are not associated with nodes)
Reimplemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
Definition at line 350 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
pin_redundant_nodal_pressures() [1/3]
template<unsigned DIM>
static void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > & element_pt) [inline], [static]
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function.
RefineableSpaceTimeNavierStokesEquations:: pin_elemental_redundant_nodal_pressure_dofs()
which is empty by default and should be implemented for elements with nodal pressure degrees of freedom (e.g. for refineable Taylor-Hood.)
Definition at line 372 of file refineable_spacetime_navier_stokes_elements.h.
References e, and oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::pin_elemental_redundant_nodal_pressure_dofs().
pin_redundant_nodal_pressures() [2/3]
template<unsigned DIM>
static void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > & element_pt) [inline], [static]
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function.
RefineableSpaceTimeNavierStokesEquations:: pin_elemental_redundant_nodal_pressure_dofs()
which is empty by default and should be implemented for elements with nodal pressure degrees of freedom (e.g. for refineable Taylor-Hood.)
Definition at line 372 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References e, and oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::pin_elemental_redundant_nodal_pressure_dofs().
pin_redundant_nodal_pressures() [3/3]
template<unsigned DIM>
static void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > & element_pt) [inline], [static]
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function.
RefineableSpaceTimeNavierStokesEquations:: pin_elemental_redundant_nodal_pressure_dofs()
which is empty by default and should be implemented for elements with nodal pressure degrees of freedom (e.g. for refineable Taylor-Hood.)
Definition at line 372 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References e, and oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::pin_elemental_redundant_nodal_pressure_dofs().
pressure_node_pt() [1/3]
template<unsigned DIM>
virtual Node* oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::pressure_node_pt (const unsigned & n_p) [inline], [virtual]
Pointer to n_p-th pressure node (Default: NULL, indicating that pressure is not based on nodal interpolation).
Reimplemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
Definition at line 409 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
pressure_node_pt() [2/3]
template<unsigned DIM>
virtual Node* oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::pressure_node_pt (const unsigned & n_p) [inline], [virtual]
Pointer to n_p-th pressure node (Default: NULL, indicating that pressure is not based on nodal interpolation).
Reimplemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
Definition at line 409 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
pressure_node_pt() [3/3]
template<unsigned DIM>
virtual Node* oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::pressure_node_pt (const unsigned & n_p) [inline], [virtual]
Pointer to n_p-th pressure node (Default: NULL, indicating that pressure is not based on nodal interpolation).
Reimplemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
Definition at line 409 of file refineable_spacetime_navier_stokes_elements.h.
unpin_all_pressure_dofs() [1/3]
template<unsigned DIM>
static void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::unpin_all_pressure_dofs (const Vector< GeneralisedElement * > & element_pt) [inline], [static]
Unpin all pressure dofs in elements listed in vector.
Definition at line 390 of file refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References e, and oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::unpin_elemental_pressure_dofs().
unpin_all_pressure_dofs() [2/3]
template<unsigned DIM>
static void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::unpin_all_pressure_dofs (const Vector< GeneralisedElement * > & element_pt) [inline], [static]
Unpin all pressure dofs in elements listed in vector.
Definition at line 390 of file refineable_spacetime_navier_stokes_elements.h.
References e, and oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::unpin_elemental_pressure_dofs().
unpin_all_pressure_dofs() [3/3]
template<unsigned DIM>
static void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::unpin_all_pressure_dofs (const Vector< GeneralisedElement * > & element_pt) [inline], [static]
Unpin all pressure dofs in elements listed in vector.
Definition at line 390 of file refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References e, and oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::unpin_elemental_pressure_dofs().
unpin_elemental_pressure_dofs() [1/3]
template<unsigned DIM>
virtual void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::unpin_elemental_pressure_dofs () [protected], [pure virtual]
Unpin all pressure dofs in the element.
Implemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
Referenced by oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::unpin_all_pressure_dofs().
unpin_elemental_pressure_dofs() [2/3]
template<unsigned DIM>
virtual void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::unpin_elemental_pressure_dofs () [protected], [pure virtual]
Unpin all pressure dofs in the element.
Implemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
unpin_elemental_pressure_dofs() [3/3]
template<unsigned DIM>
virtual void oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::unpin_elemental_pressure_dofs () [protected], [pure virtual]
Unpin all pressure dofs in the element.
Implemented in oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, and oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.
The documentation for this class was generated from the following files:
refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h
refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.h
refineable_spacetime_navier_stokes_elements.h
refineable_discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.cc
refineable_discontinuous_galerkin_spacetime_navier_stokes_elements.cc
refineable_spacetime_navier_stokes_elements.cc