oomph::RefineableNavierStokesFluxControlElement< ELEMENT > Class Template Reference
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
#include <navier_stokes_flux_control_elements.h>
Public Member Functions
RefineableNavierStokesFluxControlElement (FiniteElement *const &element_pt, const int &face_index)
Constructor, which takes a `bulk` element and the face index.
~RefineableNavierStokesFluxControlElement ()
Destructor should not delete anything.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values are the same as those in the bulk element.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
This function returns just the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the Jacobian including the Jacobian contribution from the flux control master element with respect to dof in this element.
Protected Member Functions
void refineable_fill_in_generic_residual_contribution_fluid_traction (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
This function returns the residuals for the traction function flag=1(or 0): do (or don't) compute the Jacobian as well. This function also calculates the Jacobian contribution for the NetFluxControlElement.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::RefineableNavierStokesFluxControlElement< ELEMENT >
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
A class of element to impose an applied boundary pressure to Navier-Stokes elements to control to control a volume flux. A mesh of these elements are used in conjunction with a NetFluxControlElement. The template arguement ELEMENT is a Navier-Stokes `bulk` element.
Note: This element calculates Jacobian contributions for both itself and also for the NetFluxControlElement with respect to its unknowns.
THIS IS THE REFINEABLE VERSION.
Definition at line 563 of file navier_stokes_flux_control_elements.h.
Constructor & Destructor Documentation
RefineableNavierStokesFluxControlElement()
template<class ELEMENT >
oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::RefineableNavierStokesFluxControlElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the face index.
Definition at line 569 of file navier_stokes_flux_control_elements.h.
 RefineableNavierStokesFluxControlElement()
template<class ELEMENT >
oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::~RefineableNavierStokesFluxControlElement () [inline]
Destructor should not delete anything.
Definition at line 578 of file navier_stokes_flux_control_elements.h.
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
This function returns the residuals and the Jacobian including the Jacobian contribution from the flux control master element with respect to dof in this element.
Reimplemented from oomph::NavierStokesFluxControlElement< ELEMENT >.
Definition at line 601 of file navier_stokes_flux_control_elements.h.
References oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
This function returns just the residuals.
Reimplemented from oomph::NavierStokesFluxControlElement< ELEMENT >.
Definition at line 590 of file navier_stokes_flux_control_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction().
ncont_interpolated_values()
template<class ELEMENT >
unsigned oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values are the same as those in the bulk element.
Implements oomph::RefineableElement.
Definition at line 583 of file navier_stokes_flux_control_elements.h.
References oomph::FaceElement::bulk_element_pt(), and oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::ncont_interpolated_values().
Referenced by oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::ncont_interpolated_values().
refineable_fill_in_generic_residual_contribution_fluid_traction()
template<class ELEMENT >
void oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [inline], [protected]
This function returns the residuals for the traction function flag=1(or 0): do (or don't) compute the Jacobian as well. This function also calculates the Jacobian contribution for the NetFluxControlElement.
Definition at line 614 of file navier_stokes_flux_control_elements.h.
References oomph::FaceElement::bulk_element_pt(), oomph::NavierStokesFluxControlElement< ELEMENT >::Dim, oomph::GeneralisedElement::external_data_pt(), oomph::GeneralisedElement::external_local_eqn(), oomph::Node::hanging_pt(), i, oomph::FiniteElement::integral_pt(), oomph::Node::is_hanging(), oomph::RefineableElement::local_hang_eqn(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), oomph::TemplateFreeNavierStokesFluxControlElementBase::pressure_data_id(), oomph::NavierStokesFluxControlElement< ELEMENT >::shape_and_test_at_knot(), oomph::Data::value(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::fill_in_contribution_to_residuals().
The documentation for this class was generated from the following file:
navier_stokes_flux_control_elements.h