oomph::AxisymmetricQCrouzeixRaviartElement Class Reference
/////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////
#include <axisym_navier_stokes_elements.h>
Public Member Functions
AxisymmetricQCrouzeixRaviartElement ()
Constructor, there are three internal values (for the pressure)
virtual unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at local node n.
double p_axi_nst (const unsigned &i) const
Return the pressure values at internal dof i_internal (Discontinous pressure interpolation -- no need to cater for hanging nodes).
unsigned npres_axi_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &pvalue)
Function to fix the internal pressure dof idof_internal.
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction) const
Compute traction at local coordinate s for outer unit normal N.
int p_local_eqn (const unsigned &n) const
Overload the access function for the pressure's local equation numbers.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity (3 components) and pressure.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Protected Member Functions
double dshape_and_dtest_eulerian_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at ipt-th integation point (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
void pshape_axi_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
Protected Attributes
unsigned P_axi_nst_internal_index
Internal index that indicates at which internal data the pressure is stored.
Static Private Attributes
static const unsigned Initial_Nvalue []
Static array of ints to hold required number of variables at nodes.
Additional Inherited Members
Detailed Description
/////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////
Crouzeix_Raviart elements are Navier--Stokes elements with quadratic interpolation for velocities and positions, but a discontinuous linear pressure interpolation
Definition at line 1231 of file axisym_navier_stokes_elements.h.
Constructor & Destructor Documentation
AxisymmetricQCrouzeixRaviartElement()
oomph::AxisymmetricQCrouzeixRaviartElement::AxisymmetricQCrouzeixRaviartElement () [inline]
Constructor, there are three internal values (for the pressure)
Definition at line 1288 of file axisym_navier_stokes_elements.h.
References oomph::GeneralisedElement::add_internal_data(), and P_axi_nst_internal_index.
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_axi_nst() [1/2]
double oomph::AxisymmetricQCrouzeixRaviartElement::dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 1436 of file axisym_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot(), and i.
dshape_and_dtest_eulerian_at_knot_axi_nst() [2/2]
double oomph::AxisymmetricQCrouzeixRaviartElement::dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at ipt-th integation point (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t. to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 1407 of file axisym_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot(), and i.
dshape_and_dtest_eulerian_axi_nst()
double oomph::AxisymmetricQCrouzeixRaviartElement::dshape_and_dtest_eulerian_axi_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t. to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 1381 of file axisym_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian(), and i.
fix_pressure()
void oomph::AxisymmetricQCrouzeixRaviartElement::fix_pressure (const unsigned & p_dof, const double & pvalue) [inline]
Function to fix the internal pressure dof idof_internal.
Definition at line 1314 of file axisym_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), P_axi_nst_internal_index, oomph::Data::pin(), and oomph::Data::set_value().
get_dof_numbers_for_unknowns()
void oomph::AxisymmetricQCrouzeixRaviartElement::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> & dof_lookup_list) const [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Reimplemented from oomph::GeneralisedElement.
Definition at line 3639 of file axisym_navier_stokes_elements.cc.
References oomph::GeneralisedElement::eqn_number(), oomph::GeneralisedElement::local_eqn_number(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), npres_axi_nst(), oomph::Data::nvalue(), and p_local_eqn().
get_traction()
void oomph::AxisymmetricQCrouzeixRaviartElement::get_traction (const Vector< double > & s, const Vector< double > & N, Vector< double > & traction) const
Compute traction at local coordinate s for outer unit normal N.
Definition at line 3720 of file axisym_navier_stokes_elements.cc.
References oomph::QuadTreeNames::N, s, and oomph::AxisymmetricNavierStokesEquations::traction().
ndof_types()
unsigned oomph::AxisymmetricQCrouzeixRaviartElement::ndof_types () const [inline], [virtual]
The number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity (3 components) and pressure.
Reimplemented from oomph::GeneralisedElement.
Definition at line 1359 of file axisym_navier_stokes_elements.h.
npres_axi_nst()
unsigned oomph::AxisymmetricQCrouzeixRaviartElement::npres_axi_nst () const [inline], [virtual]
Return number of pressure values.
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 1308 of file axisym_navier_stokes_elements.h.
Referenced by get_dof_numbers_for_unknowns(), and oomph::RefineableAxisymmetricQCrouzeixRaviartElement::unpin_elemental_pressure_dofs().
output() [1/4]
void oomph::AxisymmetricQCrouzeixRaviartElement::output (FILE * file_pt) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::AxisymmetricNavierStokesEquations.
Definition at line 1346 of file axisym_navier_stokes_elements.h.
References oomph::AxisymmetricNavierStokesEquations::output().
output() [2/4]
void oomph::AxisymmetricQCrouzeixRaviartElement::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::AxisymmetricNavierStokesEquations.
Definition at line 1352 of file axisym_navier_stokes_elements.h.
References oomph::AxisymmetricNavierStokesEquations::output().
output() [3/4]
void oomph::AxisymmetricQCrouzeixRaviartElement::output (std::ostream & outfile) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::AxisymmetricNavierStokesEquations.
Definition at line 1333 of file axisym_navier_stokes_elements.h.
References oomph::AxisymmetricNavierStokesEquations::output().
output() [4/4]
void oomph::AxisymmetricQCrouzeixRaviartElement::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::AxisymmetricNavierStokesEquations.
Definition at line 1339 of file axisym_navier_stokes_elements.h.
References oomph::AxisymmetricNavierStokesEquations::output().
p_axi_nst()
double oomph::AxisymmetricQCrouzeixRaviartElement::p_axi_nst (const unsigned & i) const [inline], [virtual]
Return the pressure values at internal dof i_internal (Discontinous pressure interpolation -- no need to cater for hanging nodes).
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 1302 of file axisym_navier_stokes_elements.h.
References i, oomph::GeneralisedElement::internal_data_pt(), P_axi_nst_internal_index, and oomph::Data::value().
p_local_eqn()
int oomph::AxisymmetricQCrouzeixRaviartElement::p_local_eqn (const unsigned & n) const [inline], [virtual]
Overload the access function for the pressure's local equation numbers.
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 1327 of file axisym_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_local_eqn(), and P_axi_nst_internal_index.
Referenced by get_dof_numbers_for_unknowns().
pshape_axi_nst() [1/2]
void oomph::AxisymmetricQCrouzeixRaviartElement::pshape_axi_nst (const Vector< double > & s, Shape & psi) const [inline], [protected], [virtual]
Pressure shape functions at local coordinate s.
Pressure shape functions.
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 1478 of file axisym_navier_stokes_elements.h.
References s.
Referenced by pshape_axi_nst().
pshape_axi_nst() [2/2]
void oomph::AxisymmetricQCrouzeixRaviartElement::pshape_axi_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected], [virtual]
Pressure shape and test functions at local coordinte s.
Define the pressure shape and test functions.
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 1487 of file axisym_navier_stokes_elements.h.
References i, pshape_axi_nst(), and s.
required_nvalue()
unsigned oomph::AxisymmetricQCrouzeixRaviartElement::required_nvalue (const unsigned & n) const [virtual]
Number of values (pinned or dofs) required at local node n.
Number of values (pinned or dofs) required at node n.
Reimplemented from oomph::FiniteElement.
Definition at line 3711 of file axisym_navier_stokes_elements.cc.
References Initial_Nvalue.
Member Data Documentation
Initial_Nvalue
const unsigned oomph::AxisymmetricQCrouzeixRaviartElement::Initial_Nvalue [static], [private]
Initial value:
= {
    3, 3, 3, 3, 3, 3, 3, 3, 3}
Static array of ints to hold required number of variables at nodes.
Axisymmetric Crouzeix-Raviart elements.
Definition at line 1237 of file axisym_navier_stokes_elements.h.
Referenced by required_nvalue().
P_axi_nst_internal_index
unsigned oomph::AxisymmetricQCrouzeixRaviartElement::P_axi_nst_internal_index [protected]
Internal index that indicates at which internal data the pressure is stored.
Definition at line 1242 of file axisym_navier_stokes_elements.h.
Referenced by AxisymmetricQCrouzeixRaviartElement(), fix_pressure(), oomph::RefineableAxisymmetricQCrouzeixRaviartElement::further_build(), p_axi_nst(), p_local_eqn(), oomph::RefineableAxisymmetricQCrouzeixRaviartElement::rebuild_from_sons(), and oomph::RefineableAxisymmetricQCrouzeixRaviartElement::unpin_elemental_pressure_dofs().
The documentation for this class was generated from the following files:
axisym_navier_stokes_elements.h
axisym_navier_stokes_elements.cc