oomph::BandedBlockTriangularPreconditioner< MATRIX > Class Template Reference
General purpose block triangular preconditioner. By default this operates as an upper triangular preconditioner. Also, by default SuperLUPreconditioner (or SuperLUDistPreconditioner) is used to solve the subsidiary systems, but other preconditioners can be used by setting them using passing a pointer to a function of type SubsidiaryPreconditionerFctPt to the method subsidiary_preconditioner_function_pt().
#include <general_purpose_space_time_block_preconditioner.h>
Public Member Functions
BandedBlockTriangularPreconditioner ()
Constructor. (By default this preconditioner is upper triangular).
virtual ~BandedBlockTriangularPreconditioner ()
Destructor - delete the preconditioner matrices.
virtual void clean_up_memory ()
Clean up the memory.
BandedBlockTriangularPreconditioner (const BandedBlockTriangularPreconditioner &)
Broken copy constructor.
void operator= (const BandedBlockTriangularPreconditioner &)
Broken assignment operator.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply preconditioner to r.
void setup ()
Setup the preconditioner.
void set_block_bandwidth (const int &block_bandwidth)
Set the block bandwidth of the preconditioner.
int block_bandwidth ()
Get the block bandwidth of the preconditioner.
void upper_triangular ()
Use as an upper triangular preconditioner.
void lower_triangular ()
Use as a lower triangular preconditioner.
bool is_upper_triangular ()
Is this being used as an upper triangular preconditioner?
void enable_doc_memory_usage ()
Document the memory usage.
void disable_doc_memory_usage ()
Don't document the memory usage!
double get_memory_usage_in_bytes ()
Get the memory statistics.
Protected Attributes
DenseMatrix< MatrixVectorProduct * > Off_diagonal_matrix_vector_products
Matrix of matrix-vector product operators for the off diagonals.
Private Attributes
int Block_bandwidth
Storage for the block bandwidth of the matrix. Defaults to -1 indicating that we assume every off-diagonal block is non-empty. If the matrix is block diagonal then the value is zero.
bool Upper_triangular
Boolean indicating upper or lower triangular.
bool Preconditioner_has_been_setup
Control flag is true if the preconditioner has been setup (used so we can wipe the data when the preconditioner is called again)
bool Compute_memory_statistics
Flag to indicate whether or not to record the memory statistics this preconditioner.
double Memory_usage_in_bytes
Storage for the memory usage of the solver if the flag above is set to true (in bytes)
Additional Inherited Members
Detailed Description
template<typename MATRIX>
class oomph::BandedBlockTriangularPreconditioner< MATRIX >
General purpose block triangular preconditioner. By default this operates as an upper triangular preconditioner. Also, by default SuperLUPreconditioner (or SuperLUDistPreconditioner) is used to solve the subsidiary systems, but other preconditioners can be used by setting them using passing a pointer to a function of type SubsidiaryPreconditionerFctPt to the method subsidiary_preconditioner_function_pt().
Definition at line 205 of file general_purpose_space_time_block_preconditioner.h.
Constructor & Destructor Documentation
BandedBlockTriangularPreconditioner() [1/2]
template<typename MATRIX >
oomph::BandedBlockTriangularPreconditioner< MATRIX >::BandedBlockTriangularPreconditioner () [inline]
Constructor. (By default this preconditioner is upper triangular).
Definition at line 210 of file general_purpose_space_time_block_preconditioner.h.
References oomph::BandedBlockTriangularPreconditioner< MATRIX >::Block_bandwidth, oomph::BandedBlockTriangularPreconditioner< MATRIX >::Compute_memory_statistics, oomph::BandedBlockTriangularPreconditioner< MATRIX >::Memory_usage_in_bytes, oomph::BandedBlockTriangularPreconditioner< MATRIX >::Preconditioner_has_been_setup, and oomph::BandedBlockTriangularPreconditioner< MATRIX >::Upper_triangular.
 BandedBlockTriangularPreconditioner()
template<typename MATRIX >
virtual oomph::BandedBlockTriangularPreconditioner< MATRIX >::~BandedBlockTriangularPreconditioner () [inline], [virtual]
Destructor - delete the preconditioner matrices.
Definition at line 231 of file general_purpose_space_time_block_preconditioner.h.
References oomph::BandedBlockTriangularPreconditioner< MATRIX >::clean_up_memory().
BandedBlockTriangularPreconditioner() [2/2]
template<typename MATRIX >
oomph::BandedBlockTriangularPreconditioner< MATRIX >::BandedBlockTriangularPreconditioner (const BandedBlockTriangularPreconditioner< MATRIX > &) [inline]
Broken copy constructor.
Definition at line 264 of file general_purpose_space_time_block_preconditioner.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
block_bandwidth()
template<typename MATRIX >
int oomph::BandedBlockTriangularPreconditioner< MATRIX >::block_bandwidth () [inline]
Get the block bandwidth of the preconditioner.
Definition at line 295 of file general_purpose_space_time_block_preconditioner.h.
References oomph::BandedBlockTriangularPreconditioner< MATRIX >::Block_bandwidth.
Referenced by oomph::BandedBlockTriangularPreconditioner< MATRIX >::set_block_bandwidth().
clean_up_memory()
template<typename MATRIX >
virtual void oomph::BandedBlockTriangularPreconditioner< MATRIX >::clean_up_memory () [inline], [virtual]
Clean up the memory.
Reimplemented from oomph::GeneralPurposeBlockPreconditioner< MATRIX >.
Definition at line 239 of file general_purpose_space_time_block_preconditioner.h.
References oomph::GeneralPurposeBlockPreconditioner< MATRIX >::clean_up_memory(), i, and oomph::BandedBlockTriangularPreconditioner< MATRIX >::Off_diagonal_matrix_vector_products.
Referenced by oomph::BandedBlockTriangularPreconditioner< MATRIX >::~BandedBlockTriangularPreconditioner().
disable_doc_memory_usage()
template<typename MATRIX >
void oomph::BandedBlockTriangularPreconditioner< MATRIX >::disable_doc_memory_usage () [inline]
Don't document the memory usage!
Set the appropriate flag to false
Definition at line 335 of file general_purpose_space_time_block_preconditioner.h.
References oomph::BandedBlockTriangularPreconditioner< MATRIX >::Compute_memory_statistics.
enable_doc_memory_usage()
template<typename MATRIX >
void oomph::BandedBlockTriangularPreconditioner< MATRIX >::enable_doc_memory_usage () [inline]
Document the memory usage.
Set the appropriate flag to true
Definition at line 327 of file general_purpose_space_time_block_preconditioner.h.
References oomph::BandedBlockTriangularPreconditioner< MATRIX >::Compute_memory_statistics.
get_memory_usage_in_bytes()
template<typename MATRIX >
double oomph::BandedBlockTriangularPreconditioner< MATRIX >::get_memory_usage_in_bytes () [inline]
Get the memory statistics.
Definition at line 343 of file general_purpose_space_time_block_preconditioner.h.
References oomph::BandedBlockTriangularPreconditioner< MATRIX >::Compute_memory_statistics, oomph::BandedBlockTriangularPreconditioner< MATRIX >::Memory_usage_in_bytes, and oomph::BandedBlockTriangularPreconditioner< MATRIX >::Preconditioner_has_been_setup.
is_upper_triangular()
template<typename MATRIX >
bool oomph::BandedBlockTriangularPreconditioner< MATRIX >::is_upper_triangular () [inline]
Is this being used as an upper triangular preconditioner?
Definition at line 319 of file general_purpose_space_time_block_preconditioner.h.
References oomph::BandedBlockTriangularPreconditioner< MATRIX >::Upper_triangular.
lower_triangular()
template<typename MATRIX >
void oomph::BandedBlockTriangularPreconditioner< MATRIX >::lower_triangular () [inline]
Use as a lower triangular preconditioner.
Definition at line 311 of file general_purpose_space_time_block_preconditioner.h.
References oomph::BandedBlockTriangularPreconditioner< MATRIX >::Upper_triangular.
operator=()
template<typename MATRIX >
void oomph::BandedBlockTriangularPreconditioner< MATRIX >::operator= (const BandedBlockTriangularPreconditioner< MATRIX > &) [inline]
Broken assignment operator.
Definition at line 272 of file general_purpose_space_time_block_preconditioner.h.
References oomph::BrokenCopy::broken_assign().
preconditioner_solve()
template<typename MATRIX >
void oomph::BandedBlockTriangularPreconditioner< MATRIX >::preconditioner_solve (const DoubleVector & r, DoubleVector & z) [virtual]
Apply preconditioner to r.
Preconditioner solve for the block triangular preconditioner.
Implements oomph::Preconditioner.
Definition at line 600 of file general_purpose_space_time_block_preconditioner.cc.
References oomph::DistributableLinearAlgebraObject::distribution_pt(), i, oomph::oomph_info, and oomph::CumulativeTimings::start().
set_block_bandwidth()
template<typename MATRIX >
void oomph::BandedBlockTriangularPreconditioner< MATRIX >::set_block_bandwidth (const int & block_bandwidth) [inline]
Set the block bandwidth of the preconditioner.
Definition at line 287 of file general_purpose_space_time_block_preconditioner.h.
References oomph::BandedBlockTriangularPreconditioner< MATRIX >::block_bandwidth(), and oomph::BandedBlockTriangularPreconditioner< MATRIX >::Block_bandwidth.
setup()
template<typename MATRIX >
void oomph::BandedBlockTriangularPreconditioner< MATRIX >::setup [virtual]
Setup the preconditioner.
Set up the block triangular preconditioner.
Implements oomph::Preconditioner.
Definition at line 218 of file general_purpose_space_time_block_preconditioner.cc.
References oomph::TerminateHelper::clean_up_memory(), get_memory_usage_in_bytes(), oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::get_memory_usage_in_bytes(), oomph::GMRESBlockPreconditioner::get_memory_usage_in_bytes(), i, oomph::GMRESBlockPreconditioner::navier_stokes_subsidiary_preconditioner_pt(), oomph::CRDoubleMatrix::nnz(), oomph::CRDoubleMatrix::nrow(), oomph::oomph_info, oomph::oomph_nullstream, oomph::OomphInfo::stream_pt(), oomph::TimingHelpers::timer(), and u().
upper_triangular()
template<typename MATRIX >
void oomph::BandedBlockTriangularPreconditioner< MATRIX >::upper_triangular () [inline]
Use as an upper triangular preconditioner.
Definition at line 303 of file general_purpose_space_time_block_preconditioner.h.
References oomph::BandedBlockTriangularPreconditioner< MATRIX >::Upper_triangular.
Member Data Documentation
Block_bandwidth
template<typename MATRIX >
int oomph::BandedBlockTriangularPreconditioner< MATRIX >::Block_bandwidth [private]
Storage for the block bandwidth of the matrix. Defaults to -1 indicating that we assume every off-diagonal block is non-empty. If the matrix is block diagonal then the value is zero.
Definition at line 402 of file general_purpose_space_time_block_preconditioner.h.
Referenced by oomph::BandedBlockTriangularPreconditioner< MATRIX >::BandedBlockTriangularPreconditioner(), oomph::BandedBlockTriangularPreconditioner< MATRIX >::block_bandwidth(), and oomph::BandedBlockTriangularPreconditioner< MATRIX >::set_block_bandwidth().
Compute_memory_statistics
template<typename MATRIX >
bool oomph::BandedBlockTriangularPreconditioner< MATRIX >::Compute_memory_statistics [private]
Flag to indicate whether or not to record the memory statistics this preconditioner.
Definition at line 413 of file general_purpose_space_time_block_preconditioner.h.
Referenced by oomph::BandedBlockTriangularPreconditioner< MATRIX >::BandedBlockTriangularPreconditioner(), oomph::BandedBlockTriangularPreconditioner< MATRIX >::disable_doc_memory_usage(), oomph::BandedBlockTriangularPreconditioner< MATRIX >::enable_doc_memory_usage(), and oomph::BandedBlockTriangularPreconditioner< MATRIX >::get_memory_usage_in_bytes().
Memory_usage_in_bytes
template<typename MATRIX >
double oomph::BandedBlockTriangularPreconditioner< MATRIX >::Memory_usage_in_bytes [private]
Storage for the memory usage of the solver if the flag above is set to true (in bytes)
Definition at line 417 of file general_purpose_space_time_block_preconditioner.h.
Referenced by oomph::BandedBlockTriangularPreconditioner< MATRIX >::BandedBlockTriangularPreconditioner(), and oomph::BandedBlockTriangularPreconditioner< MATRIX >::get_memory_usage_in_bytes().
Off_diagonal_matrix_vector_products
template<typename MATRIX >
DenseMatrix<MatrixVectorProduct*> oomph::BandedBlockTriangularPreconditioner< MATRIX >::Off_diagonal_matrix_vector_products [protected]
Matrix of matrix-vector product operators for the off diagonals.
Definition at line 396 of file general_purpose_space_time_block_preconditioner.h.
Referenced by oomph::BandedBlockTriangularPreconditioner< MATRIX >::clean_up_memory().
Preconditioner_has_been_setup
template<typename MATRIX >
bool oomph::BandedBlockTriangularPreconditioner< MATRIX >::Preconditioner_has_been_setup [private]
Control flag is true if the preconditioner has been setup (used so we can wipe the data when the preconditioner is called again)
Definition at line 409 of file general_purpose_space_time_block_preconditioner.h.
Referenced by oomph::BandedBlockTriangularPreconditioner< MATRIX >::BandedBlockTriangularPreconditioner(), and oomph::BandedBlockTriangularPreconditioner< MATRIX >::get_memory_usage_in_bytes().
Upper_triangular
template<typename MATRIX >
bool oomph::BandedBlockTriangularPreconditioner< MATRIX >::Upper_triangular [private]
Boolean indicating upper or lower triangular.
Definition at line 405 of file general_purpose_space_time_block_preconditioner.h.
Referenced by oomph::BandedBlockTriangularPreconditioner< MATRIX >::BandedBlockTriangularPreconditioner(), oomph::BandedBlockTriangularPreconditioner< MATRIX >::is_upper_triangular(), oomph::BandedBlockTriangularPreconditioner< MATRIX >::lower_triangular(), and oomph::BandedBlockTriangularPreconditioner< MATRIX >::upper_triangular().
The documentation for this class was generated from the following files:
general_purpose_space_time_block_preconditioner.h
general_purpose_space_time_block_preconditioner.cc