oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT > Class Template Reference
AdvectionDiffusionReaction upgraded to become projectable.
#include <advection_diffusion_reaction_elements.h>
Public Member Functions
Vector< std::pair< Data *, unsigned > > data_values_of_field (const unsigned &fld)
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld.
unsigned nfields_for_projection ()
Number of fields to be projected: Just one.
unsigned nhistory_values_for_projection (const unsigned &fld)
Number of history values to be stored for fld-th field (includes current value!)
unsigned nhistory_values_for_coordinate_projection ()
Number of positional history values (Note: count includes current value!)
double jacobian_and_shape_of_field (const unsigned &fld, const Vector< double > &s, Shape &psi)
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
double get_field (const unsigned &t, const unsigned &fld, const Vector< double > &s)
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
unsigned nvalue_of_field (const unsigned &fld)
Return number of values in field fld: One per node.
int local_equation (const unsigned &fld, const unsigned &j)
Return local equation number of value j in field fld.
Additional Inherited Members
Detailed Description
template<class ADR_ELEMENT>
class oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT >
AdvectionDiffusionReaction upgraded to become projectable.
Definition at line 890 of file advection_diffusion_reaction_elements.h.
Member Function Documentation
data_values_of_field()
template<class ADR_ELEMENT >
Vector<std::pair<Data*, unsigned> > oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT >::data_values_of_field (const unsigned & fld) [inline], [virtual]
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld.
Implements oomph::ProjectableElementBase.
Definition at line 897 of file advection_diffusion_reaction_elements.h.
References oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
get_field()
template<class ADR_ELEMENT >
double oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT >::get_field (const unsigned & t, const unsigned & fld, const Vector< double > & s) [inline], [virtual]
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
Implements oomph::ProjectableElementBase.
Definition at line 952 of file advection_diffusion_reaction_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), and oomph::FiniteElement::shape().
jacobian_and_shape_of_field()
template<class ADR_ELEMENT >
double oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT >::jacobian_and_shape_of_field (const unsigned & fld, const Vector< double > & s, Shape & psi) [inline], [virtual]
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
Implements oomph::ProjectableElementBase.
Definition at line 936 of file advection_diffusion_reaction_elements.h.
References oomph::FiniteElement::dim(), oomph::FiniteElement::nnode(), and s.
local_equation()
template<class ADR_ELEMENT >
int oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT >::local_equation (const unsigned & fld, const unsigned & j) [inline], [virtual]
Return local equation number of value j in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 986 of file advection_diffusion_reaction_elements.h.
References oomph::FiniteElement::nodal_local_eqn().
nfields_for_projection()
template<class ADR_ELEMENT >
unsigned oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT >::nfields_for_projection () [inline], [virtual]
Number of fields to be projected: Just one.
Implements oomph::ProjectableElementBase.
Definition at line 915 of file advection_diffusion_reaction_elements.h.
nhistory_values_for_coordinate_projection()
template<class ADR_ELEMENT >
unsigned oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT >::nhistory_values_for_coordinate_projection () [inline], [virtual]
Number of positional history values (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 929 of file advection_diffusion_reaction_elements.h.
References oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), and oomph::Node::position_time_stepper_pt().
nhistory_values_for_projection()
template<class ADR_ELEMENT >
unsigned oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT >::nhistory_values_for_projection (const unsigned & fld) [inline], [virtual]
Number of history values to be stored for fld-th field (includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 922 of file advection_diffusion_reaction_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::Data::ntstorage().
nvalue_of_field()
template<class ADR_ELEMENT >
unsigned oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT >::nvalue_of_field (const unsigned & fld) [inline], [virtual]
Return number of values in field fld: One per node.
Implements oomph::ProjectableElementBase.
Definition at line 979 of file advection_diffusion_reaction_elements.h.
References oomph::FiniteElement::nnode().
The documentation for this class was generated from the following file:
advection_diffusion_reaction_elements.h