oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D > Class Template Reference
QAdvectionDiffusionReactionElement elements are linear/quadrilateral/brick-shaped Advection Diffusion elements with isoparametric interpolation for the function.
#include <advection_diffusion_reaction_elements.h>
Public Member Functions
QAdvectionDiffusionReactionElement ()
Constructor: Call constructors for QElement and Advection Diffusion equations.
QAdvectionDiffusionReactionElement (const QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D > &dummy)
Broken copy constructor.
void operator= (const QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D > &)
Broken assignment operator.
unsigned required_nvalue (const unsigned &n) const
Required # of `values' (pinned or dofs) at node n.
void output (std::ostream &outfile)
Output function: x,y,u or x,y,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output (FILE *file_pt)
C-style output function: x,y,u or x,y,z,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (Calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_adv_diff_react (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
double dshape_and_dtest_eulerian_at_knot_adv_diff_react (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Additional Inherited Members
Detailed Description
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
class oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >
QAdvectionDiffusionReactionElement elements are linear/quadrilateral/brick-shaped Advection Diffusion elements with isoparametric interpolation for the function.
Definition at line 672 of file advection_diffusion_reaction_elements.h.
Constructor & Destructor Documentation
QAdvectionDiffusionReactionElement() [1/2]
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::QAdvectionDiffusionReactionElement () [inline]
Constructor: Call constructors for QElement and Advection Diffusion equations.
Definition at line 679 of file advection_diffusion_reaction_elements.h.
QAdvectionDiffusionReactionElement() [2/2]
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::QAdvectionDiffusionReactionElement (const QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 686 of file advection_diffusion_reaction_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dshape_and_dtest_eulerian_adv_diff_react()
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
double oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::dshape_and_dtest_eulerian_adv_diff_react (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Galerkin: Test functions = shape functions
Implements oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
Definition at line 792 of file advection_diffusion_reaction_elements.h.
References i, and s.
dshape_and_dtest_eulerian_at_knot_adv_diff_react()
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
double oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_adv_diff_react (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
Definition at line 825 of file advection_diffusion_reaction_elements.h.
operator=()
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
void oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::operator= (const QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D > &) [inline]
Broken assignment operator.
Definition at line 693 of file advection_diffusion_reaction_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
void oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function: x,y,u or x,y,z,u.
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
Definition at line 724 of file advection_diffusion_reaction_elements.h.
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::output().
output() [2/4]
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
void oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
Definition at line 731 of file advection_diffusion_reaction_elements.h.
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::output().
output() [3/4]
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
void oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: x,y,u or x,y,z,u.
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
Definition at line 708 of file advection_diffusion_reaction_elements.h.
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::output().
output() [4/4]
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
void oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
Definition at line 715 of file advection_diffusion_reaction_elements.h.
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::output().
output_fct() [1/2]
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
void oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (Calls the steady version)
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
Definition at line 751 of file advection_diffusion_reaction_elements.h.
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::output_fct().
output_fct() [2/2]
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
void oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
Definition at line 739 of file advection_diffusion_reaction_elements.h.
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::output_fct().
required_nvalue()
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
unsigned oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Required # of `values' (pinned or dofs) at node n.
Reimplemented from oomph::FiniteElement.
Definition at line 701 of file advection_diffusion_reaction_elements.h.
The documentation for this class was generated from the following file:
advection_diffusion_reaction_elements.h