oomph::PeriodicOrbitTemporalMesh< ELEMENT > Class Template Reference
A special temporal mesh class.
#include <periodic_orbit_handler.h>
Public Member Functions
PeriodicOrbitTemporalMesh (const unsigned &n_element)
Constructor, create a 1D mesh from 0 to 1 that is periodic.
void orbit_output (GeneralisedElement *const &elem_pt, std::ostream &outfile, const unsigned &n_plot)
void assemble_residuals (PeriodicOrbitAssemblyHandlerBase *const &assembly_handler_pt, GeneralisedElement *const &elem_pt, Vector< double > &residuals)
void assemble_residuals_and_jacobian (PeriodicOrbitAssemblyHandlerBase *const &assembly_handler_pt, GeneralisedElement *const &elem_pt, Vector< double > &residuals, DenseMatrix< double > &jacobian)
Friends
template<unsigned NNODE_1D>
class PeriodicOrbitAssemblyHandler
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::PeriodicOrbitTemporalMesh< ELEMENT >
A special temporal mesh class.
Definition at line 589 of file periodic_orbit_handler.h.
Constructor & Destructor Documentation
PeriodicOrbitTemporalMesh()
template<class ELEMENT >
oomph::PeriodicOrbitTemporalMesh< ELEMENT >::PeriodicOrbitTemporalMesh (const unsigned & n_element) [inline]
Constructor, create a 1D mesh from 0 to 1 that is periodic.
Definition at line 597 of file periodic_orbit_handler.h.
References oomph::Mesh::boundary_node_pt().
Member Function Documentation
assemble_residuals()
template<class ELEMENT >
void oomph::PeriodicOrbitTemporalMesh< ELEMENT >::assemble_residuals (PeriodicOrbitAssemblyHandlerBase *const & assembly_handler_pt, GeneralisedElement *const & elem_pt, Vector< double > & residuals) [inline]
Definition at line 623 of file periodic_orbit_handler.h.
References e, oomph::Mesh::element_pt(), oomph::Vector< _Tp >::initialise(), and oomph::Mesh::nelement().
assemble_residuals_and_jacobian()
template<class ELEMENT >
void oomph::PeriodicOrbitTemporalMesh< ELEMENT >::assemble_residuals_and_jacobian (PeriodicOrbitAssemblyHandlerBase *const & assembly_handler_pt, GeneralisedElement *const & elem_pt, Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline]
Definition at line 643 of file periodic_orbit_handler.h.
References e, oomph::Mesh::element_pt(), oomph::Vector< _Tp >::initialise(), oomph::DenseMatrix< T >::initialise(), and oomph::Mesh::nelement().
orbit_output()
template<class ELEMENT >
void oomph::PeriodicOrbitTemporalMesh< ELEMENT >::orbit_output (GeneralisedElement *const & elem_pt, std::ostream & outfile, const unsigned & n_plot) [inline]
Definition at line 609 of file periodic_orbit_handler.h.
References e, oomph::Mesh::element_pt(), oomph::Mesh::nelement(), and oomph::PeriodicOrbitTemporalMesh< ELEMENT >::orbit_output().
Referenced by oomph::PeriodicOrbitTemporalMesh< ELEMENT >::orbit_output().
Friends And Related Function Documentation
PeriodicOrbitAssemblyHandler
template<class ELEMENT >
template<unsigned NNODE_1D>
friend class PeriodicOrbitAssemblyHandler [friend]
Definition at line 593 of file periodic_orbit_handler.h.
The documentation for this class was generated from the following file:
periodic_orbit_handler.h