oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH > Class Template Reference
#include <foeppl_von_karman_volume_constraint_element.h>
Public Member Functions
FoepplvonKarmanVolumeConstraintElement (MESH< ELEMENT > *bounding_mesh_pt, const Vector< unsigned > &contributing_region, const double &pressure=0.0)
Constructor. Takes pointer to mesh of Foeppl von Karman elements and a vector of unsigneds which identifies the regions within it that contribute to the controlled volume defined as int w dA (i.e. the `volume under the membrane`). The optional final argument specifies the initial value for the pressure that is `traded` in exchange for the volume constraint.
~FoepplvonKarmanVolumeConstraintElement ()
FoepplvonKarmanVolumeConstraintElement (const FoepplvonKarmanVolumeConstraintElement &)
Broken copy constructor.
void operator= (const FoepplvonKarmanVolumeConstraintElement &)
Broken assignment operator.
double get_bounded_volume ()
Returns the volume `under the elements` in the constrained regions.
void assign_additional_local_eqn_numbers ()
Assign the equation number for the new equation.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in residual: Difference between actual and prescribed bounded volume.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Fill in contribution to elemental residual and Jacobian.
void set_prescribed_volume (double *volume_pt)
Set pointer to target volume.
Data * pressure_data_pt () const
Access to Data object whose single value contains the pressure that has been `traded` for the volume constraint.
Protected Attributes
Data * Volume_control_pressure_pt
Data object whose single value contains the pressure that has been `traded` for the volume constraint.
unsigned Pressure_data_index
Unsigned indicating which internal Data object stores the pressure.
int Volume_control_local_eqn
Local equation number of volume constraint.
MESH< ELEMENT > * Bounding_mesh_pt
Pointer to mesh of Foeppl von Karman elements that bound the prescribed volume; NULL if the FvK elements that contribute to the bounding volume are in charge of adding their own contribution to the volume constraint equation (and the associated Jacobian)
Vector< unsigned > Contributing_region
Region IDs in the bounding mesh that contribute to the prescribed/controlled volume.
double * Prescribed_volume_pt
Pointer to target volume.
Additional Inherited Members
Detailed Description
template<class ELEMENT, template< class > class MESH>
class oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >
A class which allows the user to specify a prescribed volume (as opposed to a prescribed pressure) for in the region bounded by the membrane. Effectively adds an equation to the system for pressure. There would usually only be a single instance of this element in a problem.
Definition at line 51 of file foeppl_von_karman_volume_constraint_element.h.
Constructor & Destructor Documentation
FoepplvonKarmanVolumeConstraintElement() [1/2]
template<class ELEMENT , template< class > class MESH>
oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::FoepplvonKarmanVolumeConstraintElement (MESH< ELEMENT > * bounding_mesh_pt, const Vector< unsigned > & contributing_region, const double & pressure = 0.0) [inline]
Constructor. Takes pointer to mesh of Foeppl von Karman elements and a vector of unsigneds which identifies the regions within it that contribute to the controlled volume defined as int w dA (i.e. the `volume under the membrane`). The optional final argument specifies the initial value for the pressure that is `traded` in exchange for the volume constraint.
Definition at line 62 of file foeppl_von_karman_volume_constraint_element.h.
References oomph::GeneralisedElement::add_internal_data(), Data, oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::Pressure_data_index, oomph::Data::set_value(), and oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::Volume_control_pressure_pt.
 FoepplvonKarmanVolumeConstraintElement()
template<class ELEMENT , template< class > class MESH>
oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::~FoepplvonKarmanVolumeConstraintElement () [inline]
Definition at line 79 of file foeppl_von_karman_volume_constraint_element.h.
FoepplvonKarmanVolumeConstraintElement() [2/2]
template<class ELEMENT , template< class > class MESH>
oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::FoepplvonKarmanVolumeConstraintElement (const FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH > &) [inline]
Broken copy constructor.
Definition at line 82 of file foeppl_von_karman_volume_constraint_element.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
assign_additional_local_eqn_numbers()
template<class ELEMENT , template< class > class MESH>
void oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::assign_additional_local_eqn_numbers () [inline], [virtual]
Assign the equation number for the new equation.
Reimplemented from oomph::GeneralisedElement.
Definition at line 119 of file foeppl_von_karman_volume_constraint_element.h.
References oomph::GeneralisedElement::internal_local_eqn(), oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::Pressure_data_index, and oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::Volume_control_local_eqn.
fill_in_contribution_to_jacobian()
template<class ELEMENT , template< class > class MESH>
void oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Fill in contribution to elemental residual and Jacobian.
Reimplemented from oomph::GeneralisedElement.
Definition at line 136 of file foeppl_von_karman_volume_constraint_element.h.
References residuals(), and oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::Volume_control_local_eqn.
fill_in_contribution_to_residuals()
template<class ELEMENT , template< class > class MESH>
void oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Fill in residual: Difference between actual and prescribed bounded volume.
Reimplemented from oomph::GeneralisedElement.
Definition at line 126 of file foeppl_von_karman_volume_constraint_element.h.
References residuals(), and oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::Volume_control_local_eqn.
get_bounded_volume()
template<class ELEMENT , template< class > class MESH>
double oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::get_bounded_volume () [inline]
Returns the volume `under the elements` in the constrained regions.
Definition at line 96 of file foeppl_von_karman_volume_constraint_element.h.
References oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::Bounding_mesh_pt, oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::Contributing_region, and e.
operator=()
template<class ELEMENT , template< class > class MESH>
void oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::operator= (const FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH > &) [inline]
Broken assignment operator.
Definition at line 89 of file foeppl_von_karman_volume_constraint_element.h.
References oomph::BrokenCopy::broken_assign().
pressure_data_pt()
template<class ELEMENT , template< class > class MESH>
Data* oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::pressure_data_pt () const [inline]
Access to Data object whose single value contains the pressure that has been `traded` for the volume constraint.
Definition at line 246 of file foeppl_von_karman_volume_constraint_element.h.
References oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::Volume_control_pressure_pt.
set_prescribed_volume()
template<class ELEMENT , template< class > class MESH>
void oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::set_prescribed_volume (double * volume_pt) [inline]
Set pointer to target volume.
Definition at line 239 of file foeppl_von_karman_volume_constraint_element.h.
References oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::Prescribed_volume_pt.
Member Data Documentation
Bounding_mesh_pt
template<class ELEMENT , template< class > class MESH>
MESH<ELEMENT>* oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::Bounding_mesh_pt [protected]
Pointer to mesh of Foeppl von Karman elements that bound the prescribed volume; NULL if the FvK elements that contribute to the bounding volume are in charge of adding their own contribution to the volume constraint equation (and the associated Jacobian)
Definition at line 268 of file foeppl_von_karman_volume_constraint_element.h.
Referenced by oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::get_bounded_volume().
Contributing_region
template<class ELEMENT , template< class > class MESH>
Vector<unsigned> oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::Contributing_region [protected]
Region IDs in the bounding mesh that contribute to the prescribed/controlled volume.
Definition at line 272 of file foeppl_von_karman_volume_constraint_element.h.
Referenced by oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::get_bounded_volume().
Prescribed_volume_pt
template<class ELEMENT , template< class > class MESH>
double* oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::Prescribed_volume_pt [protected]
Pointer to target volume.
Definition at line 275 of file foeppl_von_karman_volume_constraint_element.h.
Referenced by oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::set_prescribed_volume().
Pressure_data_index
template<class ELEMENT , template< class > class MESH>
unsigned oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::Pressure_data_index [protected]
Unsigned indicating which internal Data object stores the pressure.
Definition at line 258 of file foeppl_von_karman_volume_constraint_element.h.
Referenced by oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::assign_additional_local_eqn_numbers(), and oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::FoepplvonKarmanVolumeConstraintElement().
Volume_control_local_eqn
template<class ELEMENT , template< class > class MESH>
int oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::Volume_control_local_eqn [protected]
Local equation number of volume constraint.
Definition at line 261 of file foeppl_von_karman_volume_constraint_element.h.
Referenced by oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::assign_additional_local_eqn_numbers(), oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::fill_in_contribution_to_jacobian(), and oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::fill_in_contribution_to_residuals().
Volume_control_pressure_pt
template<class ELEMENT , template< class > class MESH>
Data* oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::Volume_control_pressure_pt [protected]
Data object whose single value contains the pressure that has been `traded` for the volume constraint.
Definition at line 254 of file foeppl_von_karman_volume_constraint_element.h.
Referenced by oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::FoepplvonKarmanVolumeConstraintElement(), and oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::pressure_data_pt().
The documentation for this class was generated from the following file:
foeppl_von_karman_volume_constraint_element.h