oomph::SolidMesh Class Reference
General SolidMesh class.
#include <mesh.h>
Public Member Functions
SolidMesh ()
Default constructor.
SolidMesh (const SolidMesh &dummy)
Broken copy constructor.
void operator= (const SolidMesh &)
Broken assignment operator.
SolidMesh (const Vector< SolidMesh * > &sub_mesh_pt)
Constructor builds combined mesh from the meshes specified. Note: This simply merges the meshes' elements and nodes (ignoring duplicates; no boundary information etc. is created).
SolidNode * node_pt (const unsigned long &n)
Return a pointer to the n-th global SolidNode.
SolidNode * boundary_node_pt (const unsigned &b, const unsigned &n)
Return n-th SolidNodes on b-th boundary.
SolidNode * element_node_pt (const unsigned long &e, const unsigned &n)
Return the n-th local SolidNode in elemnet e. This is required to cast the nodes in a solid mesh to be SolidNodes and therefore allow access to the extra SolidNode data.
void set_lagrangian_nodal_coordinates ()
Make the current configuration the undeformed one by setting the nodal Lagrangian coordinates to their current Eulerian ones.
void scale_mesh (const double &factor)
Scale all nodal coordinates by given factor and re-assign the Lagrangian coordinates.
Static Public Attributes
static SolidICProblem Solid_IC_problem
Static problem that can be used to assign initial conditions on a given solid mesh (need to define this as a static problem somewhere because deleting the problem would wipe out the mesh too!)
Additional Inherited Members
Detailed Description
General SolidMesh class.
Solid meshes contain SolidFiniteElements which contain SolidNodes. This class simply overloads the appropriate access functions from the underlying Mesh class.
Definition at line 2568 of file mesh.h.
Constructor & Destructor Documentation
SolidMesh() [1/3]
oomph::SolidMesh::SolidMesh () [inline]
Default constructor.
Definition at line 2572 of file mesh.h.
SolidMesh() [2/3]
oomph::SolidMesh::SolidMesh (const SolidMesh & dummy) [inline]
Broken copy constructor.
Definition at line 2575 of file mesh.h.
References oomph::BrokenCopy::broken_copy().
SolidMesh() [3/3]
oomph::SolidMesh::SolidMesh (const Vector< SolidMesh * > & sub_mesh_pt) [inline]
Constructor builds combined mesh from the meshes specified. Note: This simply merges the meshes' elements and nodes (ignoring duplicates; no boundary information etc. is created).
Definition at line 2590 of file mesh.h.
References oomph::Mesh::Comm_pt, i, oomph::Mesh::merge_meshes(), and n.
Member Function Documentation
boundary_node_pt()
SolidNode* oomph::SolidMesh::boundary_node_pt (const unsigned & b, const unsigned & n) [inline]
Return n-th SolidNodes on b-th boundary.
Definition at line 2626 of file mesh.h.
References oomph::Mesh::boundary_node_pt(), and n.
Referenced by oomph::ElasticRectangularQuadMesh< ELEMENT >::set_boundary_coordinates().
element_node_pt()
SolidNode* oomph::SolidMesh::element_node_pt (const unsigned long & e, const unsigned & n) [inline]
Return the n-th local SolidNode in elemnet e. This is required to cast the nodes in a solid mesh to be SolidNodes and therefore allow access to the extra SolidNode data.
Definition at line 2645 of file mesh.h.
References e, oomph::Mesh::Element_pt, n, oomph::FiniteElement::node_pt(), and node_pt().
node_pt()
SolidNode* oomph::SolidMesh::node_pt (const unsigned long & n) [inline]
Return a pointer to the n-th global SolidNode.
Definition at line 2608 of file mesh.h.
References n, and oomph::Mesh::Node_pt.
Referenced by oomph::NonLinearElasticitySmoothMesh< ELEMENT >::actions_before_newton_solve(), oomph::NonLinearElasticitySmoothMesh< ELEMENT >::backup(), oomph::FSI_functions::doc_fsi(), oomph::ElasticRectangularQuadMesh< ELEMENT >::ElasticRectangularQuadMesh(), element_node_pt(), oomph::NonLinearElasticitySmoothMesh< ELEMENT >::operator()(), oomph::LinearElasticitySmoothMesh< LINEAR_ELASTICITY_ELEMENT >::operator()(), oomph::PoissonSmoothMesh< POISSON_ELEMENT >::operator()(), oomph::NonLinearElasticitySmoothMesh< ELEMENT >::reset(), and set_lagrangian_nodal_coordinates().
operator=()
void oomph::SolidMesh::operator= (const SolidMesh &) [inline]
Broken assignment operator.
Definition at line 2581 of file mesh.h.
References oomph::BrokenCopy::broken_assign().
scale_mesh()
void oomph::SolidMesh::scale_mesh (const double & factor) [inline], [virtual]
Scale all nodal coordinates by given factor and re-assign the Lagrangian coordinates.
Reimplemented from oomph::Mesh.
Definition at line 2683 of file mesh.h.
References oomph::Mesh::scale_mesh(), and set_lagrangian_nodal_coordinates().
set_lagrangian_nodal_coordinates()
void oomph::SolidMesh::set_lagrangian_nodal_coordinates ()
Make the current configuration the undeformed one by setting the nodal Lagrangian coordinates to their current Eulerian ones.
Make the current configuration the undeformed one by setting the nodal Lagrangian coordinates to their current Eulerian ones
Definition at line 9564 of file mesh.cc.
References n, oomph::SolidNode::nlagrangian(), oomph::SolidNode::nlagrangian_type(), oomph::Mesh::nnode(), oomph::Mesh::Node_pt, node_pt(), oomph::Node::x_gen(), and oomph::SolidNode::xi_gen().
Referenced by oomph::ElasticQuarterPipeMesh< ELEMENT >::ElasticQuarterPipeMesh(), oomph::ElasticRectangularQuadMesh< ELEMENT >::ElasticRectangularQuadMesh(), oomph::OneDLagrangianMesh< ELEMENT >::OneDLagrangianMesh(), oomph::NonLinearElasticitySmoothMesh< ELEMENT >::operator()(), oomph::LinearElasticitySmoothMesh< LINEAR_ELASTICITY_ELEMENT >::operator()(), oomph::PoissonSmoothMesh< POISSON_ELEMENT >::operator()(), oomph::PseudoElasticChannelWithLeafletMesh< ELEMENT >::PseudoElasticChannelWithLeafletMesh(), oomph::RefineableSolidBrickFromTetMesh< ELEMENT >::RefineableSolidBrickFromTetMesh(), oomph::RefineableSolidThinLayerBrickOnTetMesh< ELEMENT >::RefineableSolidThinLayerBrickOnTetMesh(), oomph::RefineableSolidTriangleMesh< ELEMENT >::RefineableSolidTriangleMesh(), scale_mesh(), oomph::SolidBrickFromTetMesh< ELEMENT >::SolidBrickFromTetMesh(), oomph::SolidTetgenMesh< ELEMENT >::SolidTetgenMesh(), oomph::SolidThinLayerBrickOnTetMesh< ELEMENT >::SolidThinLayerBrickOnTetMesh(), oomph::SolidTriangleMesh< ELEMENT >::SolidTriangleMesh(), and oomph::SolidXdaTetMesh< ELEMENT >::SolidXdaTetMesh().
Member Data Documentation
Solid_IC_problem
SolidICProblem oomph::SolidMesh::Solid_IC_problem [static]
Static problem that can be used to assign initial conditions on a given solid mesh (need to define this as a static problem somewhere because deleting the problem would wipe out the mesh too!)
Static problem that can be used to assign initial conditions on a given mesh.
Definition at line 2693 of file mesh.h.
The documentation for this class was generated from the following files:
mesh.h
mesh.cc