oomph::QSolidElementBase Class Reference
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
#include <Qelements.h>
Public Member Functions
QSolidElementBase ()
Constructor: Empty.
QSolidElementBase (const QSolidElementBase &)=delete
Broken copy constructor.
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
Broken assignment operator.
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt, MacroElement *undeformed_macro_elem_pt)
Set pointers to `current` and `undeformed` MacroElements.
void get_x_and_xi (const Vector< double > &s, Vector< double > &x_fe, Vector< double > &x, Vector< double > &xi_fe, Vector< double > &xi) const
Eulerian and Lagrangian coordinates as function of the local coordinates: The Eulerian position is returned in FE-interpolated form (x_fe) and then in the form obtained from the `current` MacroElement representation (if it exists -- if not, x is the same as x_fe). This allows the Domain/MacroElement- based representation to be used to apply displacement boundary conditions exactly. Ditto for the Lagrangian coordinates returned in xi_fe and xi.
Additional Inherited Members
Detailed Description
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
Base class for Solid Qelements
Definition at line 329 of file Qelements.h.
Constructor & Destructor Documentation
QSolidElementBase() [1/2]
oomph::QSolidElementBase::QSolidElementBase () [inline]
Constructor: Empty.
Definition at line 334 of file Qelements.h.
QSolidElementBase() [2/2]
oomph::QSolidElementBase::QSolidElementBase (const QSolidElementBase &) [delete]
Broken copy constructor.
Member Function Documentation
get_x_and_xi()
void oomph::QSolidElementBase::get_x_and_xi (const Vector< double > & s, Vector< double > & x_fe, Vector< double > & x, Vector< double > & xi_fe, Vector< double > & xi) const [inline], [virtual]
Eulerian and Lagrangian coordinates as function of the local coordinates: The Eulerian position is returned in FE-interpolated form (x_fe) and then in the form obtained from the `current` MacroElement representation (if it exists -- if not, x is the same as x_fe). This allows the Domain/MacroElement- based representation to be used to apply displacement boundary conditions exactly. Ditto for the Lagrangian coordinates returned in xi_fe and xi.
Reimplemented from oomph::SolidFiniteElement.
Definition at line 379 of file Qelements.h.
References oomph::FiniteElement::dim(), i, oomph::FiniteElement::interpolated_x(), oomph::SolidFiniteElement::interpolated_xi(), oomph::FiniteElement::Macro_elem_pt, oomph::MacroElement::macro_map(), s, oomph::QElementBase::s_macro_ll(), oomph::QElementBase::s_macro_ur(), oomph::SolidFiniteElement::Undeformed_macro_elem_pt, and oomph::x.
Referenced by oomph::RefineableSolidQElement< 3 >::build(), and oomph::RefineableSolidQElement< 2 >::build().
set_macro_elem_pt() [1/2]
virtual void oomph::QSolidElementBase::set_macro_elem_pt (MacroElement * macro_elem_pt) [inline], [virtual]
Broken assignment operator.
Set pointer to MacroElement -- overloads generic version in RefineableQElement<2> and uses the MacroElement also as the default for the `undeformed` configuration. This assignment can/must be overwritten with set_undeformed_macro_elem_pt(...) if the deformation of the solid body is driven by a deformation of the `current` Domain/MacroElement representation of it's boundary.
Reimplemented from oomph::SolidFiniteElement.
Reimplemented in oomph::RefineableSolidQElement< 3 >, oomph::RefineableSolidQElement< 1 >, and oomph::RefineableSolidQElement< 2 >.
Definition at line 349 of file Qelements.h.
References oomph::FiniteElement::macro_elem_pt(), oomph::QElementBase::set_macro_elem_pt(), and oomph::SolidFiniteElement::set_undeformed_macro_elem_pt().
Referenced by oomph::RefineableSolidQElement< 3 >::set_macro_elem_pt(), oomph::RefineableSolidQElement< 1 >::set_macro_elem_pt(), and oomph::RefineableSolidQElement< 2 >::set_macro_elem_pt().
set_macro_elem_pt() [2/2]
virtual void oomph::QSolidElementBase::set_macro_elem_pt (MacroElement * macro_elem_pt, MacroElement * undeformed_macro_elem_pt) [inline], [virtual]
Set pointers to `current` and `undeformed` MacroElements.
Reimplemented from oomph::SolidFiniteElement.
Reimplemented in oomph::RefineableSolidQElement< 3 >, oomph::RefineableSolidQElement< 1 >, and oomph::RefineableSolidQElement< 2 >.
Definition at line 360 of file Qelements.h.
References oomph::FiniteElement::macro_elem_pt(), oomph::QElementBase::set_macro_elem_pt(), oomph::SolidFiniteElement::set_undeformed_macro_elem_pt(), and oomph::SolidFiniteElement::undeformed_macro_elem_pt().
The documentation for this class was generated from the following file:
Qelements.h