QTaylorHoodElement< DIM > Class Template Reference
/////////////////////////////////////////////////////////////////////////
#include <navier_stokes_elements.h>
Public Member Functions
QTaylorHoodElement ()
Constructor, no internal data points.
virtual unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
virtual int p_nodal_index_nst () const
Set the value at which the pressure is stored in the nodes.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
double p_nst (const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
double p_nst (const unsigned &t, const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
unsigned npres_nst () const
Return number of pressure values.
bool is_pressure_node (const unsigned &n) const
Deduce whether or not the provided node is a pressure node.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs containing.
void identify_pressure_data (std::set< std::pair< Data *, unsigned > > &paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
unsigned ndof_types () const
Returns the number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity and pressure.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1.
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
2D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
void pshape_nst (const Vector< double > &s, Shape &psi) const
2D : Pressure shape functions
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
3D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
void pshape_nst (const Vector< double > &s, Shape &psi) const
3D : Pressure shape functions
Protected Member Functions
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
const unsigned Pconv [4]
const unsigned Pconv [8]
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
2D : Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
3D : Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Static Protected Attributes
static const unsigned Pconv []
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Private Member Functions
const unsigned Initial_Nvalue [9]
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
const unsigned Initial_Nvalue [27]
Static Private Attributes
static const unsigned Initial_Nvalue []
Static array of ints to hold number of variables at node.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class QTaylorHoodElement< DIM >
/////////////////////////////////////////////////////////////////////////
Taylor--Hood elements are Navier--Stokes elements with quadratic interpolation for velocities and positions and continuous linear pressure interpolation. They can be used within oomph-lib's block-preconditioning framework.
Definition at line 2312 of file navier_stokes_elements.h.
Constructor & Destructor Documentation
QTaylorHoodElement()
template<unsigned DIM>
QTaylorHoodElement< DIM >::QTaylorHoodElement () [inline]
Constructor, no internal data points.
Definition at line 2357 of file navier_stokes_elements.h.
Member Function Documentation
build_fp_press_adv_diff_robin_bc_element()
template<unsigned DIM>
void QTaylorHoodElement< DIM >::build_fp_press_adv_diff_robin_bc_element (const unsigned & face_index) [inline], [virtual]
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Implements NavierStokesEquations< DIM >.
Reimplemented in oomph::RefineableQTaylorHoodElement< DIM >.
Definition at line 2440 of file navier_stokes_elements.h.
dpshape_and_dptest_eulerian_nst() [1/3]
template<unsigned DIM>
double QTaylorHoodElement< DIM >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [virtual]
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implements NavierStokesEquations< DIM >.
dpshape_and_dptest_eulerian_nst() [2/3]
double QTaylorHoodElement< 2 >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [virtual]
2D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
Implements NavierStokesEquations< DIM >.
Definition at line 2571 of file navier_stokes_elements.h.
References oomph::OneDimLagrange::dshape< 2 >(), i, s, and oomph::OneDimLagrange::shape< 2 >().
dpshape_and_dptest_eulerian_nst() [3/3]
double QTaylorHoodElement< 3 >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [virtual]
3D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
Implements NavierStokesEquations< DIM >.
Definition at line 2757 of file navier_stokes_elements.h.
References oomph::OneDimLagrange::dshape< 2 >(), i, s, and oomph::OneDimLagrange::shape< 2 >().
dshape_and_dtest_eulerian_at_knot_nst() [1/4]
template<unsigned DIM>
double QTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implements NavierStokesEquations< DIM >.
dshape_and_dtest_eulerian_at_knot_nst() [2/4]
double QTaylorHoodElement< 2 >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
2D : Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements NavierStokesEquations< DIM >.
Definition at line 2636 of file navier_stokes_elements.h.
References i.
dshape_and_dtest_eulerian_at_knot_nst() [3/4]
double QTaylorHoodElement< 3 >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
3D : Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements NavierStokesEquations< DIM >.
Definition at line 2685 of file navier_stokes_elements.h.
References i.
dshape_and_dtest_eulerian_at_knot_nst() [4/4]
template<unsigned DIM>
double QTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements NavierStokesEquations< DIM >.
Definition at line 2546 of file navier_stokes_elements.h.
dshape_and_dtest_eulerian_nst()
template<unsigned DIM>
double QTaylorHoodElement< DIM >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements NavierStokesEquations< DIM >.
Definition at line 2521 of file navier_stokes_elements.h.
References s.
fix_pressure()
template<unsigned DIM>
void QTaylorHoodElement< DIM >::fix_pressure (const unsigned & p_dof, const double & p_value) [inline], [virtual]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implements NavierStokesEquations< DIM >.
Definition at line 2429 of file navier_stokes_elements.h.
get_dof_numbers_for_unknowns()
template<unsigned DIM>
void QTaylorHoodElement< DIM >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1.
Create a list of pairs for all unknowns in this element, so the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Definition at line 2825 of file navier_stokes_elements.cc.
identify_load_data()
template<unsigned DIM>
void QTaylorHoodElement< DIM >::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data)
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Definition at line 2762 of file navier_stokes_elements.cc.
References i.
identify_pressure_data()
template<unsigned DIM>
void QTaylorHoodElement< DIM >::identify_pressure_data (std::set< std::pair< Data *, unsigned > > & paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all pressure values that affect the load computed in the get_load(...) function.
the pointer to a Data object and
the index of the value in that Data object
for pressure values that affect the load computed in the get_load(...) function.,
Definition at line 2798 of file navier_stokes_elements.cc.
Initial_Nvalue() [1/2]
const unsigned QTaylorHoodElement< 3 >::Initial_Nvalue [private]
Definition at line 2744 of file navier_stokes_elements.cc.
Initial_Nvalue() [2/2]
const unsigned QTaylorHoodElement< 2 >::Initial_Nvalue [private]
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Definition at line 2734 of file navier_stokes_elements.cc.
is_pressure_node()
template<unsigned DIM>
bool QTaylorHoodElement< DIM >::is_pressure_node (const unsigned & n) const [inline]
Deduce whether or not the provided node is a pressure node.
Definition at line 2418 of file navier_stokes_elements.h.
ndof_types()
template<unsigned DIM>
unsigned QTaylorHoodElement< DIM >::ndof_types () const [inline]
Returns the number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity and pressure.
Definition at line 2498 of file navier_stokes_elements.h.
npres_nst()
template<unsigned DIM>
unsigned QTaylorHoodElement< DIM >::npres_nst () const [inline], [virtual]
Return number of pressure values.
Implements NavierStokesEquations< DIM >.
Definition at line 2411 of file navier_stokes_elements.h.
Referenced by oomph::RefineableQTaylorHoodElement< DIM >::identify_load_data(), and oomph::RefineableQTaylorHoodElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs().
output() [1/4]
template<unsigned DIM>
void QTaylorHoodElement< DIM >::output (FILE * file_pt) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 2484 of file navier_stokes_elements.h.
References NavierStokesEquations< DIM >::output().
output() [2/4]
template<unsigned DIM>
void QTaylorHoodElement< DIM >::output (FILE * file_pt, const unsigned & nplot) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 2490 of file navier_stokes_elements.h.
References NavierStokesEquations< DIM >::output().
output() [3/4]
template<unsigned DIM>
void QTaylorHoodElement< DIM >::output (std::ostream & outfile) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 2472 of file navier_stokes_elements.h.
References NavierStokesEquations< DIM >::output().
output() [4/4]
template<unsigned DIM>
void QTaylorHoodElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 2478 of file navier_stokes_elements.h.
References NavierStokesEquations< DIM >::output().
p_local_eqn()
template<unsigned DIM>
int QTaylorHoodElement< DIM >::p_local_eqn (const unsigned & n) const [inline]
Return the local equation numbers for the pressure values.
Definition at line 2382 of file navier_stokes_elements.h.
p_nodal_index_nst()
template<unsigned DIM>
virtual int QTaylorHoodElement< DIM >::p_nodal_index_nst () const [inline], [virtual]
Set the value at which the pressure is stored in the nodes.
Reimplemented from NavierStokesEquations< DIM >.
Definition at line 2376 of file navier_stokes_elements.h.
Referenced by oomph::RefineableQTaylorHoodElement< DIM >::further_setup_hanging_nodes(), oomph::RefineableQTaylorHoodElement< DIM >::identify_load_data(), oomph::RefineableQTaylorHoodElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs(), and oomph::RefineableQTaylorHoodElement< DIM >::unpin_elemental_pressure_dofs().
p_nst() [1/2]
template<unsigned DIM>
double QTaylorHoodElement< DIM >::p_nst (const unsigned & n_p) const [inline], [virtual]
Access function for the pressure values at local pressure node n_p (const version)
Implements NavierStokesEquations< DIM >.
Definition at line 2389 of file navier_stokes_elements.h.
p_nst() [2/2]
template<unsigned DIM>
double QTaylorHoodElement< DIM >::p_nst (const unsigned & t, const unsigned & n_p) const [inline], [virtual]
Access function for the pressure values at local pressure node n_p (const version)
Implements NavierStokesEquations< DIM >.
Definition at line 2396 of file navier_stokes_elements.h.
References t.
Pconv() [1/2]
const unsigned QTaylorHoodElement< 2 >::Pconv [protected]
Definition at line 2739 of file navier_stokes_elements.cc.
Pconv() [2/2]
const unsigned QTaylorHoodElement< 3 >::Pconv [protected]
Definition at line 2750 of file navier_stokes_elements.cc.
pshape_nst() [1/4]
template<unsigned DIM>
void QTaylorHoodElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Pressure shape functions at local coordinate s.
Implements NavierStokesEquations< DIM >.
Referenced by oomph::RefineableQTaylorHoodElement< DIM >::interpolating_basis().
pshape_nst() [2/4]
void QTaylorHoodElement< 2 >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
2D : Pressure shape functions
Implements NavierStokesEquations< DIM >.
Definition at line 2729 of file navier_stokes_elements.h.
References i, s, and oomph::OneDimLagrange::shape< 2 >().
pshape_nst() [3/4]
void QTaylorHoodElement< 3 >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
3D : Pressure shape functions
Implements NavierStokesEquations< DIM >.
Definition at line 2822 of file navier_stokes_elements.h.
References i, s, and oomph::OneDimLagrange::shape< 2 >().
pshape_nst() [4/4]
template<unsigned DIM>
void QTaylorHoodElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [virtual]
Pressure shape and test functions at local coordinte s.
Pressure shape and test functions.
Implements NavierStokesEquations< DIM >.
Definition at line 2853 of file navier_stokes_elements.h.
References s.
required_nvalue()
template<unsigned DIM>
virtual unsigned QTaylorHoodElement< DIM >::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
Reimplemented in oomph::RefineableQTaylorHoodElement< DIM >.
Definition at line 2361 of file navier_stokes_elements.h.
Member Data Documentation
Initial_Nvalue
template<unsigned DIM>
const unsigned QTaylorHoodElement< DIM >::Initial_Nvalue[] [static], [private]
Static array of ints to hold number of variables at node.
Definition at line 2317 of file navier_stokes_elements.h.
Pconv
template<unsigned DIM>
const unsigned QTaylorHoodElement< DIM >::Pconv[] [static], [protected]
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Definition at line 2322 of file navier_stokes_elements.h.
Referenced by oomph::RefineableQTaylorHoodElement< DIM >::pressure_node_pt().
The documentation for this class was generated from the following files:
navier_stokes_elements.h
navier_stokes_elements.cc