oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT > Class Template Reference
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
#include <generalised_newtonian_navier_stokes_elements.h>
Public Member Functions
ProjectableGeneralisedNewtonianTaylorHoodElement ()
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Vector< std::pair< Data *, unsigned > > data_values_of_field (const unsigned &fld)
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld. In the underlying Taylor Hood elements the fld-th velocities are stored at the fld-th value of the nodes; the pressures (the dim-th field) are the dim-th values at the vertex nodes etc.
unsigned nfields_for_projection ()
Number of fields to be projected: dim+1, corresponding to velocity components and pressure.
unsigned nhistory_values_for_projection (const unsigned &fld)
Number of history values to be stored for fld-th field. Whatever the timestepper has set up for the velocity components and none for the pressure field. (Note: count includes current value!)
unsigned nhistory_values_for_coordinate_projection ()
Number of positional history values (Note: count includes current value!)
double jacobian_and_shape_of_field (const unsigned &fld, const Vector< double > &s, Shape &psi)
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
double get_field (const unsigned &t, const unsigned &fld, const Vector< double > &s)
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
unsigned nvalue_of_field (const unsigned &fld)
Return number of values in field fld.
int local_equation (const unsigned &fld, const unsigned &j)
Return local equation number of value j in field fld.
Additional Inherited Members
Detailed Description
template<class TAYLOR_HOOD_ELEMENT>
class oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
Taylor Hood upgraded to become projectable
Definition at line 2448 of file generalised_newtonian_navier_stokes_elements.h.
Constructor & Destructor Documentation
ProjectableGeneralisedNewtonianTaylorHoodElement()
template<class TAYLOR_HOOD_ELEMENT >
oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::ProjectableGeneralisedNewtonianTaylorHoodElement () [inline]
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Definition at line 2454 of file generalised_newtonian_navier_stokes_elements.h.
Member Function Documentation
data_values_of_field()
template<class TAYLOR_HOOD_ELEMENT >
Vector< std::pair< Data *, unsigned > > oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::data_values_of_field (const unsigned & fld) [inline], [virtual]
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld. In the underlying Taylor Hood elements the fld-th velocities are stored at the fld-th value of the nodes; the pressures (the dim-th field) are the dim-th values at the vertex nodes etc.
Implements oomph::ProjectableElementBase.
Definition at line 2463 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::dim(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
get_field()
template<class TAYLOR_HOOD_ELEMENT >
double oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::get_field (const unsigned & t, const unsigned & fld, const Vector< double > & s) [inline], [virtual]
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
Implements oomph::ProjectableElementBase.
Definition at line 2565 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::dim(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and t.
jacobian_and_shape_of_field()
template<class TAYLOR_HOOD_ELEMENT >
double oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::jacobian_and_shape_of_field (const unsigned & fld, const Vector< double > & s, Shape & psi) [inline], [virtual]
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
Implements oomph::ProjectableElementBase.
Definition at line 2530 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::dim(), oomph::FiniteElement::nnode(), and s.
local_equation()
template<class TAYLOR_HOOD_ELEMENT >
int oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::local_equation (const unsigned & fld, const unsigned & j) [inline], [virtual]
Return local equation number of value j in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 2617 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::dim(), and oomph::FiniteElement::nodal_local_eqn().
nfields_for_projection()
template<class TAYLOR_HOOD_ELEMENT >
unsigned oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::nfields_for_projection () [inline], [virtual]
Number of fields to be projected: dim+1, corresponding to velocity components and pressure.
Implements oomph::ProjectableElementBase.
Definition at line 2499 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::dim().
nhistory_values_for_coordinate_projection()
template<class TAYLOR_HOOD_ELEMENT >
unsigned oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::nhistory_values_for_coordinate_projection () [inline], [virtual]
Number of positional history values (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 2523 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), and oomph::Node::position_time_stepper_pt().
nhistory_values_for_projection()
template<class TAYLOR_HOOD_ELEMENT >
unsigned oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::nhistory_values_for_projection (const unsigned & fld) [inline], [virtual]
Number of history values to be stored for fld-th field. Whatever the timestepper has set up for the velocity components and none for the pressure field. (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 2508 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::dim(), oomph::FiniteElement::node_pt(), and oomph::Data::ntstorage().
nvalue_of_field()
template<class TAYLOR_HOOD_ELEMENT >
unsigned oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::nvalue_of_field (const unsigned & fld) [inline], [virtual]
Return number of values in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 2603 of file generalised_newtonian_navier_stokes_elements.h.
References oomph::FiniteElement::dim(), and oomph::FiniteElement::nnode().
The documentation for this class was generated from the following file:
generalised_newtonian_navier_stokes_elements.h