oomph::DGScalarAdvectionElement< 2, NNODE_1D > Class Template Reference
Specialisation for 2D DG Elements.
#include <scalar_advection_elements.h>
Public Member Functions
unsigned required_nflux ()
Set the number of flux components.
void calculate_element_averages (double *&average_value)
Calculate the averages in the element.
DGScalarAdvectionElement ()
~DGScalarAdvectionElement ()
void build_all_faces ()
void fill_in_generic_residual_contribution_flux_transport (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Compute the residuals for the Navier--Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Friends
class DGScalarAdvectionFaceElement< DGScalarAdvectionElement< 2, NNODE_1D > >
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::DGScalarAdvectionElement< 2, NNODE_1D >
Specialisation for 2D DG Elements.
Definition at line 964 of file scalar_advection_elements.h.
Constructor & Destructor Documentation
DGScalarAdvectionElement()
template<unsigned NNODE_1D>
oomph::DGScalarAdvectionElement< 2, NNODE_1D >::DGScalarAdvectionElement () [inline]
Definition at line 984 of file scalar_advection_elements.h.
 DGScalarAdvectionElement()
template<unsigned NNODE_1D>
oomph::DGScalarAdvectionElement< 2, NNODE_1D >::~DGScalarAdvectionElement () [inline]
Definition at line 989 of file scalar_advection_elements.h.
Member Function Documentation
build_all_faces()
template<unsigned NNODE_1D>
void oomph::DGScalarAdvectionElement< 2, NNODE_1D >::build_all_faces () [inline], [virtual]
Implements oomph::DGElement.
Definition at line 991 of file scalar_advection_elements.h.
calculate_element_averages()
template<unsigned NNODE_1D>
void oomph::DGScalarAdvectionElement< 2, NNODE_1D >::calculate_element_averages (double *& average_values) [inline], [virtual]
Calculate the averages in the element.
Reimplemented from oomph::DGElement.
Definition at line 978 of file scalar_advection_elements.h.
References oomph::FluxTransportEquations< DIM >::calculate_element_averages().
fill_in_generic_residual_contribution_flux_transport()
template<unsigned NNODE_1D>
void oomph::DGScalarAdvectionElement< 2, NNODE_1D >::fill_in_generic_residual_contribution_flux_transport (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) [inline], [virtual]
Compute the residuals for the Navier--Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented from oomph::FluxTransportEquations< DIM >.
Definition at line 1011 of file scalar_advection_elements.h.
References oomph::FluxTransportEquations< DIM >::fill_in_generic_residual_contribution_flux_transport(), and residuals().
required_nflux()
template<unsigned NNODE_1D>
unsigned oomph::DGScalarAdvectionElement< 2, NNODE_1D >::required_nflux () [inline], [virtual]
Set the number of flux components.
Reimplemented from oomph::DGElement.
Definition at line 972 of file scalar_advection_elements.h.
Friends And Related Function Documentation
DGScalarAdvectionFaceElement< DGScalarAdvectionElement< 2, NNODE_1D > >
template<unsigned NNODE_1D>
friend class DGScalarAdvectionFaceElement< DGScalarAdvectionElement< 2, NNODE_1D > > [friend]
Definition at line 968 of file scalar_advection_elements.h.
The documentation for this class was generated from the following file:
scalar_advection_elements.h