oomph::PeriodicOrbitAssemblyHandlerBase Class Reference
=============================================================== Base class to avoid template complications
#include <periodic_orbit_handler.h>
Public Member Functions
PeriodicOrbitAssemblyHandlerBase ()
virtual void get_dofs_for_element (GeneralisedElement *const elem_pt, Vector< double > &dofs)=0
virtual void get_previous_dofs_for_element (GeneralisedElement *const elem_pt, Vector< double > &dofs)=0
virtual void set_dofs_for_element (GeneralisedElement *const elem_pt, Vector< double > const &dofs)=0
Public Member Functions inherited from oomph::AssemblyHandler
AssemblyHandler ()
Empty constructor.
virtual unsigned ndof (GeneralisedElement *const &elem_pt)
Return the number of degrees of freedom in the element elem_pt.
virtual void dof_vector (GeneralisedElement *const &elem_pt, const unsigned &t, Vector< double > &dof)
Return vector of dofs at time level t in the element elem_pt.
virtual void dof_pt_vector (GeneralisedElement *const &elem_pt, Vector< double * > &dof_pt)
Return vector of pointers to dofs in the element elem_pt.
virtual double & local_problem_dof (Problem *const &problem_pt, const unsigned &t, const unsigned &i)
Return the t-th level of storage associated with the i-th (local) dof stored in the problem.
virtual unsigned long eqn_number (GeneralisedElement *const &elem_pt, const unsigned &ieqn_local)
Return the global equation number of the local unknown ieqn_local in elem_pt.
virtual void get_residuals (GeneralisedElement *const &elem_pt, Vector< double > &residuals)
Return the contribution to the residuals of the element elem_pt.
virtual void get_jacobian (GeneralisedElement *const &elem_pt, Vector< double > &residuals, DenseMatrix< double > &jacobian)
Calculate the elemental Jacobian matrix "d equation / d variable" for elem_pt.
virtual void get_all_vectors_and_matrices (GeneralisedElement *const &elem_pt, Vector< Vector< double > > &vec, Vector< DenseMatrix< double > > &matrix)
Calculate all desired vectors and matrices provided by the element elem_pt.
virtual void get_dresiduals_dparameter (GeneralisedElement *const &elem_pt, double *const &parameter_pt, Vector< double > &dres_dparam)
Calculate the derivative of the residuals with respect to a parameter.
virtual void get_djacobian_dparameter (GeneralisedElement *const &elem_pt, double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
Calculate the derivative of the residuals and jacobian with respect to a parameter.
virtual void get_hessian_vector_products (GeneralisedElement *const &elem_pt, Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Calculate the product of the Hessian (derivative of Jacobian with respect to all variables) an eigenvector, Y, and other specified vectors, C (d(J_{ij})/d u_{k}) Y_{j} C_{k}.
virtual int bifurcation_type () const
Return an unsigned integer to indicate whether the handler is a bifurcation tracking handler. The default is zero (not)
virtual double * bifurcation_parameter_pt () const
Return a pointer to the bifurcation parameter in bifurcation tracking problems.
virtual void get_eigenfunction (Vector< DoubleVector > &eigenfunction)
Return the eigenfunction(s) associated with the bifurcation that has been detected in bifurcation tracking problems.
virtual void get_inner_products (GeneralisedElement *const &elem_pt, Vector< std::pair< unsigned, unsigned > > const &history_index, Vector< double > &inner_product)
Compute the inner products of the given vector of pairs of history values over the element.
virtual void get_inner_product_vectors (GeneralisedElement *const &elem_pt, Vector< unsigned > const &history_index, Vector< Vector< double > > &inner_product_vector)
Compute the vectors that when taken as a dot product with other history values give the inner product over the element.
virtual void synchronise ()
Function that is used to perform any synchronisation required during the solution.
virtual ~AssemblyHandler ()
Empty virtual destructor.
Detailed Description
=============================================================== Base class to avoid template complications
Definition at line 665 of file periodic_orbit_handler.h.
Constructor & Destructor Documentation
PeriodicOrbitAssemblyHandlerBase()
oomph::PeriodicOrbitAssemblyHandlerBase::PeriodicOrbitAssemblyHandlerBase () [inline]
Definition at line 669 of file periodic_orbit_handler.h.
Member Function Documentation
get_dofs_for_element()
virtual void oomph::PeriodicOrbitAssemblyHandlerBase::get_dofs_for_element (GeneralisedElement *const elem_pt, Vector< double > & dofs) [pure virtual]
Implemented in oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >.
Referenced by oomph::PeriodicOrbitEquations::fill_in_generic_residual_contribution_orbit().
get_previous_dofs_for_element()
virtual void oomph::PeriodicOrbitAssemblyHandlerBase::get_previous_dofs_for_element (GeneralisedElement *const elem_pt, Vector< double > & dofs) [pure virtual]
Implemented in oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >.
Referenced by oomph::PeriodicOrbitEquations::fill_in_generic_residual_contribution_orbit().
set_dofs_for_element()
virtual void oomph::PeriodicOrbitAssemblyHandlerBase::set_dofs_for_element (GeneralisedElement *const elem_pt, Vector< double > const & dofs) [pure virtual]
Implemented in oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >.
Referenced by oomph::PeriodicOrbitEquations::fill_in_generic_residual_contribution_orbit().
The documentation for this class was generated from the following file:
periodic_orbit_handler.h