oomph::QHermiteElement< DIM > Class Template Reference
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
#include <hermite_elements.h>
Public Member Functions
QHermiteElement ()
Constructor.
QHermiteElement (const QHermiteElement &dummy)=delete
Broken copy constructor.
void operator= (const QHermiteElement &)=delete
Broken assignment operator.
bool local_coord_is_valid (const Vector< double > &s)
Check whether the local coordinate are valid or not.
void move_local_coord_back_into_element (Vector< double > &s) const
Adjust local coordinates so that they're located inside the element.
void shape (const Vector< double > &s, Shape &psi) const
Function to calculate the geometric shape functions at local coordinate s.
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Function to compute the geometric shape functions and derivatives w.r.t. local coordinates at local coordinate s.
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
Function to compute the geometric shape functions and also first and second derivatives wrt local coordinates at local coordinate s. Numbering: 1D: d2psids(i,0) = $ d^2 \psi_j / d s^2 $ 2D: d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $ 3D: d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial^2 \psi_j / \partial s_2^2 $ d2psids(i,3) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $ d2psids(i,4) = $ \partial^2 \psi_j / \partial s_0 \partial s_2 $ d2psids(i,5) = $ \partial^2 \psi_j / \partial s_1 \partial s_2 $.
double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Overload the template-free interface for the calculation of the inverse jacobian. The element dimension must be passed to the function.
void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Overload the template-free interface for the calculation of transformation of second derivatives. The element dimension should be passed as a template paremeter, for `optimum` efficiency.
double s_min () const
Min. value of local coordinate.
double s_max () const
Max. value of local coordinate.
void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
Get local coordinates of node j in the element; vector sets its own size.
void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
Get local fraction of node j in the element; vector sets its own size.
double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
Get the local fraction of any node in the n-th position in a one dimensional expansion along the i-th local coordinate.
unsigned nnode_1d () const
Return number of nodes along each element edge.
void output (std::ostream &outfile)
Output.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at n_plot points.
void output (FILE *file_pt)
C-style output.
void output (FILE *file_pt, const unsigned &n_plot)
C_style output at n_plot points.
void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &use_equally_spaced_interior_sample_points=false) const
Get cector of local coordinates of plot point i (when plotting nplot points in each "coordinate direction).
std::string tecplot_zone_string (const unsigned &nplot) const
Return string for tecplot zone header (when plotting nplot points in each "coordinate direction)
unsigned nplot_points (const unsigned &nplot) const
Return total number of plot points (when plotting nplot points in each "coordinate direction)
void build_face_element (const int &face_index, FaceElement *face_element_pt)
Build the lower-dimensional FaceElement of the type QHermiteElement<DIM-1>. The face index takes a value that correponds to the possible faces:
void shape (const Vector< double > &s, Shape &psi) const
Shape function for specific QHermiteElement<1>
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Derivatives of shape functions for specific QHermiteElement<1>
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
Derivatives and second derivatives of shape functions for specific QHermiteElement<1> d2psids(i,0) = $ d^2 \psi_j / d s^2 $.
void output (std::ostream &outfile)
The output function for general 1D QHermiteElements.
void output (std::ostream &outfile, const unsigned &n_plot)
The output function for n_plot points in each coordinate direction.
void output (FILE *file_pt)
The C-style output function for general 1D QHermiteElements.
void output (FILE *file_pt, const unsigned &n_plot)
The C-style output function for n_plot points in each coordinate direction.
void build_face_element (const int &face_index, FaceElement *face_element_pt)
Function to setup geometrical information for lower-dimensional FaceElements (single node elements)
void shape (const Vector< double > &s, Shape &psi) const
Shape function for specific QHermiteElement<2>
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Derivatives of shape functions for specific QHermiteElement<2>
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
Second derivatives of the shape functions wrt local coordinates. d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $.
void output (std::ostream &outfile)
The output function for QHermiteElement<2,ORDER>
void output (std::ostream &outfile, const unsigned &n_plot)
The output function for n_plot points in each coordinate direction.
void output (FILE *file_pt)
The C-style output function for QHermiteElement<2,ORDER>
void output (FILE *file_pt, const unsigned &n_plot)
The C-style output function for n_plot points in each coordinate direction.
void build_face_element (const int &face_index, FaceElement *face_element_pt)
Function to setup geometrical information for lower-dimensional FaceElements (of type QHermiteElement<1>).
void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &use_equally_spaced_interior_sample_points) const
Get cector of local coordinates of plot point i (when plotting nplot points in each coordinate direction).
std::string tecplot_zone_string (const unsigned &nplot) const
Return string for tecplot zone header (when plotting nplot points in each coordinate direction)
unsigned nplot_points (const unsigned &nplot) const
Return total number of plot points (when plotting nplot points in each coordinate direction)
void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &use_equally_spaced_interior_sample_points) const
Get cector of local coordinates of plot point i (when plotting nplot points in each "coordinate direction).
std::string tecplot_zone_string (const unsigned &nplot) const
Return string for tecplot zone header (when plotting nplot points in each coordinate direction)
unsigned nplot_points (const unsigned &nplot) const
Return total number of plot points (when plotting nplot points in each coordinate direction)
Static Private Attributes
static Gauss< DIM, 3 > Default_integration_scheme
Default integration rule: Gaussian integration of same 'order' as the element.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::QHermiteElement< DIM >
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
General QHermiteElement class. Local coordinates are not assumed to be aligned with the global coordinates so the Jacobian of the mapping between local and global coordinates is a full matrix. For cases where the coordinates are aligned, you should use the derived class, DiagQHermiteElement, which uses a simplified mapping that makes the evaluation of derivatives of the shape functions much cheaper.
Definition at line 85 of file hermite_elements.h.
Constructor & Destructor Documentation
QHermiteElement() [1/2]
template<unsigned DIM>
oomph::QHermiteElement< DIM >::QHermiteElement () [inline]
Constructor.
Definition at line 98 of file hermite_elements.h.
References oomph::FiniteElement::set_dimension(), oomph::FiniteElement::set_integration_scheme(), oomph::FiniteElement::set_n_node(), and oomph::FiniteElement::set_nnodal_position_type().
QHermiteElement() [2/2]
template<unsigned DIM>
oomph::QHermiteElement< DIM >::QHermiteElement (const QHermiteElement< DIM > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
build_face_element() [1/3]
void oomph::QHermiteElement< 1 >::build_face_element (const int & face_index, FaceElement * face_element_pt) [virtual]
Function to setup geometrical information for lower-dimensional FaceElements (single node elements)
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidQHermiteElement< 1 >, and oomph::SolidQHermiteElement< 2 >.
Definition at line 278 of file hermite_elements.cc.
References oomph::FaceElement::bulk_coordinate_derivatives_fct_pt(), oomph::FaceElement::bulk_element_pt(), oomph::FaceElement::bulk_node_number(), oomph::FaceElement::bulk_node_number_resize(), oomph::QElement1FaceToBulkCoordinates::face0(), oomph::QElement1FaceToBulkCoordinates::face1(), oomph::FaceElement::face_index(), oomph::FaceElement::face_to_bulk_coordinate_fct_pt(), oomph::QElement1BulkCoordinateDerivatives::faces0(), oomph::FaceElement::nbulk_value(), oomph::FaceElement::nbulk_value_resize(), oomph::FiniteElement::node_pt(), oomph::FaceElement::normal_sign(), oomph::GeneralisedElement::set_halo(), and oomph::FiniteElement::set_nodal_dimension().
build_face_element() [2/3]
void oomph::QHermiteElement< 2 >::build_face_element (const int & face_index, FaceElement * face_element_pt) [virtual]
Function to setup geometrical information for lower-dimensional FaceElements (of type QHermiteElement<1>).
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidQHermiteElement< 1 >, and oomph::SolidQHermiteElement< 2 >.
Definition at line 913 of file hermite_elements.cc.
References oomph::FaceElement::bulk_coordinate_derivatives_fct_pt(), oomph::FaceElement::bulk_element_pt(), oomph::FaceElement::bulk_node_number(), oomph::FaceElement::bulk_node_number_resize(), oomph::FaceElement::bulk_position_type(), oomph::FaceElement::bulk_position_type_resize(), oomph::QElement2FaceToBulkCoordinates::face0(), oomph::QElement2FaceToBulkCoordinates::face1(), oomph::QElement2FaceToBulkCoordinates::face2(), oomph::QElement2FaceToBulkCoordinates::face3(), oomph::FaceElement::face_index(), oomph::FaceElement::face_to_bulk_coordinate_fct_pt(), oomph::QElement2BulkCoordinateDerivatives::faces0(), oomph::QElement2BulkCoordinateDerivatives::faces1(), i, oomph::FaceElement::nbulk_value(), oomph::FaceElement::nbulk_value_resize(), oomph::FiniteElement::node_pt(), oomph::FaceElement::normal_sign(), oomph::GeneralisedElement::set_halo(), and oomph::FiniteElement::set_nodal_dimension().
build_face_element() [3/3]
template<unsigned DIM>
void oomph::QHermiteElement< DIM >::build_face_element (const int & face_index, FaceElement * face_element_pt) [virtual]
Build the lower-dimensional FaceElement of the type QHermiteElement<DIM-1>. The face index takes a value that correponds to the possible faces:
In 1D: -1 (Left) s[0] = -1.0 +1 (Right) s[0] = 1.0
In 2D: -1 (West) s[0] = -1.0 +1 (East) s[0] = 1.0 -2 (South) s[1] = -1.0 +2 (North) s[1] = 1.0
In 3D: -1 (Left) s[0] = -1.0 +1 (Right) s[0] = 1.0 -2 (Down) s[1] = -1.0 +2 (Up) s[1] = 1.0 -3 (Back) s[2] = -1.0 +3 (Front) s[2] = 1.0
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, and oomph::SolidQHermiteElement< 2 >.
d2shape_local() [1/3]
void oomph::QHermiteElement< 1 >::d2shape_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [virtual]
Derivatives and second derivatives of shape functions for specific QHermiteElement<1> d2psids(i,0) = $ d^2 \psi_j / d s^2 $.
Reimplemented from oomph::FiniteElement.
Definition at line 98 of file hermite_elements.cc.
References oomph::OneDimHermite::d2shape(), oomph::OneDimHermite::dshape(), s, and oomph::OneDimHermite::shape().
d2shape_local() [2/3]
void oomph::QHermiteElement< 2 >::d2shape_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [virtual]
Second derivatives of the shape functions wrt local coordinates. d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $.
Reimplemented from oomph::FiniteElement.
Definition at line 543 of file hermite_elements.cc.
References s, and oomph::OneDimHermite::shape().
d2shape_local() [3/3]
template<unsigned DIM>
void oomph::QHermiteElement< DIM >::d2shape_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const [virtual]
Function to compute the geometric shape functions and also first and second derivatives wrt local coordinates at local coordinate s. Numbering: 1D: d2psids(i,0) = $ d^2 \psi_j / d s^2 $ 2D: d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $ 3D: d2psids(i,0) = $ \partial^2 \psi_j / \partial s_0^2 $ d2psids(i,1) = $ \partial^2 \psi_j / \partial s_1^2 $ d2psids(i,2) = $ \partial^2 \psi_j / \partial s_2^2 $ d2psids(i,3) = $ \partial^2 \psi_j / \partial s_0 \partial s_1 $ d2psids(i,4) = $ \partial^2 \psi_j / \partial s_0 \partial s_2 $ d2psids(i,5) = $ \partial^2 \psi_j / \partial s_1 \partial s_2 $.
Reimplemented from oomph::FiniteElement.
dshape_local() [1/3]
void oomph::QHermiteElement< 1 >::dshape_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const [virtual]
Derivatives of shape functions for specific QHermiteElement<1>
Reimplemented from oomph::FiniteElement.
Definition at line 70 of file hermite_elements.cc.
References oomph::OneDimHermite::dshape(), s, and oomph::OneDimHermite::shape().
dshape_local() [2/3]
void oomph::QHermiteElement< 2 >::dshape_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const [virtual]
Derivatives of shape functions for specific QHermiteElement<2>
Reimplemented from oomph::FiniteElement.
Definition at line 426 of file hermite_elements.cc.
References oomph::OneDimHermite::dshape(), s, and oomph::OneDimHermite::shape().
dshape_local() [3/3]
template<unsigned DIM>
void oomph::QHermiteElement< DIM >::dshape_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const [virtual]
Function to compute the geometric shape functions and derivatives w.r.t. local coordinates at local coordinate s.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::ClampedHermiteShellBoundaryConditionElement.
get_s_plot() [1/3]
void oomph::QHermiteElement< 1 >::get_s_plot (const unsigned & i, const unsigned & nplot, Vector< double > & s, const bool & use_equally_spaced_interior_sample_points) const [inline], [virtual]
Get cector of local coordinates of plot point i (when plotting nplot points in each coordinate direction).
Reimplemented from oomph::FiniteElement.
Definition at line 322 of file hermite_elements.h.
References i, and s.
get_s_plot() [2/3]
void oomph::QHermiteElement< 2 >::get_s_plot (const unsigned & i, const unsigned & nplot, Vector< double > & s, const bool & use_equally_spaced_interior_sample_points) const [inline], [virtual]
Get cector of local coordinates of plot point i (when plotting nplot points in each "coordinate direction).
Reimplemented from oomph::FiniteElement.
Definition at line 374 of file hermite_elements.h.
References i, and s.
get_s_plot() [3/3]
template<unsigned DIM>
void oomph::QHermiteElement< DIM >::get_s_plot (const unsigned & i, const unsigned & nplot, Vector< double > & s, const bool & use_equally_spaced_interior_sample_points = false) const [virtual]
Get cector of local coordinates of plot point i (when plotting nplot points in each "coordinate direction).
Reimplemented from oomph::FiniteElement.
invert_jacobian_mapping()
template<unsigned DIM>
double oomph::QHermiteElement< DIM >::invert_jacobian_mapping (const DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const [inline], [virtual]
Overload the template-free interface for the calculation of the inverse jacobian. The element dimension must be passed to the function.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::DiagQHermiteElement< DIM >.
Definition at line 183 of file hermite_elements.h.
local_coord_is_valid()
template<unsigned DIM>
bool oomph::QHermiteElement< DIM >::local_coord_is_valid (const Vector< double > & s) [inline], [virtual]
Check whether the local coordinate are valid or not.
Reimplemented from oomph::FiniteElement.
Definition at line 120 of file hermite_elements.h.
References oomph::FiniteElement::dim(), i, s, oomph::QHermiteElement< DIM >::s_max(), and oomph::QHermiteElement< DIM >::s_min().
local_coordinate_of_node()
template<unsigned DIM>
void oomph::QHermiteElement< DIM >::local_coordinate_of_node (const unsigned & j, Vector< double > & s) const [inline], [virtual]
Get local coordinates of node j in the element; vector sets its own size.
Reimplemented from oomph::FiniteElement.
Definition at line 217 of file hermite_elements.h.
References i, s, oomph::QHermiteElement< DIM >::s_max(), and oomph::QHermiteElement< DIM >::s_min().
local_fraction_of_node()
template<unsigned DIM>
void oomph::QHermiteElement< DIM >::local_fraction_of_node (const unsigned & j, Vector< double > & s_fraction) [inline], [virtual]
Get local fraction of node j in the element; vector sets its own size.
Reimplemented from oomph::FiniteElement.
Definition at line 234 of file hermite_elements.h.
References i.
local_one_d_fraction_of_node()
template<unsigned DIM>
double oomph::QHermiteElement< DIM >::local_one_d_fraction_of_node (const unsigned & n1d, const unsigned & i) [inline], [virtual]
Get the local fraction of any node in the n-th position in a one dimensional expansion along the i-th local coordinate.
Reimplemented from oomph::FiniteElement.
Definition at line 250 of file hermite_elements.h.
move_local_coord_back_into_element()
template<unsigned DIM>
void oomph::QHermiteElement< DIM >::move_local_coord_back_into_element (Vector< double > & s) const [inline], [virtual]
Adjust local coordinates so that they're located inside the element.
Reimplemented from oomph::FiniteElement.
Definition at line 136 of file hermite_elements.h.
References oomph::FiniteElement::dim(), i, s, oomph::QHermiteElement< DIM >::s_max(), and oomph::QHermiteElement< DIM >::s_min().
nnode_1d()
template<unsigned DIM>
unsigned oomph::QHermiteElement< DIM >::nnode_1d () const [inline], [virtual]
Return number of nodes along each element edge.
Reimplemented from oomph::FiniteElement.
Definition at line 258 of file hermite_elements.h.
nplot_points() [1/3]
template<unsigned DIM>
unsigned oomph::QHermiteElement< DIM >::nplot_points (const unsigned & nplot) const [virtual]
Return total number of plot points (when plotting nplot points in each "coordinate direction)
Reimplemented from oomph::FiniteElement.
nplot_points() [2/3]
unsigned oomph::QHermiteElement< 1 >::nplot_points (const unsigned & nplot) const [inline], [virtual]
Return total number of plot points (when plotting nplot points in each coordinate direction)
Reimplemented from oomph::FiniteElement.
Definition at line 363 of file hermite_elements.h.
nplot_points() [3/3]
unsigned oomph::QHermiteElement< 2 >::nplot_points (const unsigned & nplot) const [inline], [virtual]
Return total number of plot points (when plotting nplot points in each coordinate direction)
Reimplemented from oomph::FiniteElement.
Definition at line 422 of file hermite_elements.h.
operator=()
template<unsigned DIM>
void oomph::QHermiteElement< DIM >::operator= (const QHermiteElement< DIM > &) [delete]
Broken assignment operator.
output() [1/12]
void oomph::QHermiteElement< 1 >::output (FILE * file_pt) [virtual]
The C-style output function for general 1D QHermiteElements.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidQHermiteElement< 1 >, and oomph::SolidQHermiteElement< 2 >.
Definition at line 203 of file hermite_elements.cc.
References i.
output() [2/12]
void oomph::QHermiteElement< 2 >::output (FILE * file_pt) [virtual]
The C-style output function for QHermiteElement<2,ORDER>
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidQHermiteElement< 1 >, and oomph::SolidQHermiteElement< 2 >.
Definition at line 829 of file hermite_elements.cc.
References i.
output() [3/12]
template<unsigned DIM>
void oomph::QHermiteElement< DIM >::output (FILE * file_pt) [virtual]
C-style output.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::HermiteShellElement, oomph::ClampedHermiteShellBoundaryConditionElement, and oomph::HermitePVDElement< DIM >.
output() [4/12]
void oomph::QHermiteElement< 1 >::output (FILE * file_pt, const unsigned & n_plot) [virtual]
The C-style output function for n_plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::SolidQHermiteElement< 1 >, and oomph::SolidQHermiteElement< 2 >.
Definition at line 248 of file hermite_elements.cc.
References i, and s.
output() [5/12]
void oomph::QHermiteElement< 2 >::output (FILE * file_pt, const unsigned & n_plot) [virtual]
The C-style output function for n_plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::SolidQHermiteElement< 1 >, and oomph::SolidQHermiteElement< 2 >.
Definition at line 878 of file hermite_elements.cc.
References i, and s.
output() [6/12]
template<unsigned DIM>
void oomph::QHermiteElement< DIM >::output (FILE * file_pt, const unsigned & n_plot) [virtual]
C_style output at n_plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::HermiteShellElement, oomph::ClampedHermiteShellBoundaryConditionElement, and oomph::HermitePVDElement< DIM >.
output() [7/12]
void oomph::QHermiteElement< 1 >::output (std::ostream & outfile) [virtual]
The output function for general 1D QHermiteElements.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidQHermiteElement< 1 >, and oomph::SolidQHermiteElement< 2 >.
Definition at line 128 of file hermite_elements.cc.
References i.
output() [8/12]
void oomph::QHermiteElement< 2 >::output (std::ostream & outfile) [virtual]
The output function for QHermiteElement<2,ORDER>
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidQHermiteElement< 1 >, and oomph::SolidQHermiteElement< 2 >.
Definition at line 745 of file hermite_elements.cc.
References i.
output() [9/12]
template<unsigned DIM>
void oomph::QHermiteElement< DIM >::output (std::ostream & outfile) [virtual]
Output.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::HermiteShellElement, oomph::ClampedHermiteShellBoundaryConditionElement, and oomph::HermitePVDElement< DIM >.
Referenced by oomph::SolidQHermiteElement< DIM >::output().
output() [10/12]
void oomph::QHermiteElement< 1 >::output (std::ostream & outfile, const unsigned & n_plot) [virtual]
The output function for n_plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::SolidQHermiteElement< 1 >, and oomph::SolidQHermiteElement< 2 >.
Definition at line 172 of file hermite_elements.cc.
References i, and s.
output() [11/12]
void oomph::QHermiteElement< 2 >::output (std::ostream & outfile, const unsigned & n_plot) [virtual]
The output function for n_plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::SolidQHermiteElement< 1 >, and oomph::SolidQHermiteElement< 2 >.
Definition at line 794 of file hermite_elements.cc.
References i, and s.
output() [12/12]
template<unsigned DIM>
void oomph::QHermiteElement< DIM >::output (std::ostream & outfile, const unsigned & n_plot) [virtual]
Output at n_plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::HermiteShellElement, oomph::ClampedHermiteShellBoundaryConditionElement, and oomph::HermitePVDElement< DIM >.
s_max()
template<unsigned DIM>
double oomph::QHermiteElement< DIM >::s_max () const [inline], [virtual]
Max. value of local coordinate.
Reimplemented from oomph::FiniteElement.
Definition at line 210 of file hermite_elements.h.
Referenced by oomph::QHermiteElement< DIM >::local_coord_is_valid(), oomph::QHermiteElement< DIM >::local_coordinate_of_node(), and oomph::QHermiteElement< DIM >::move_local_coord_back_into_element().
s_min()
template<unsigned DIM>
double oomph::QHermiteElement< DIM >::s_min () const [inline], [virtual]
Min. value of local coordinate.
Reimplemented from oomph::FiniteElement.
Definition at line 204 of file hermite_elements.h.
Referenced by oomph::QHermiteElement< DIM >::local_coord_is_valid(), oomph::QHermiteElement< DIM >::local_coordinate_of_node(), and oomph::QHermiteElement< DIM >::move_local_coord_back_into_element().
shape() [1/3]
void oomph::QHermiteElement< 1 >::shape (const Vector< double > & s, Shape & psi) const [virtual]
Shape function for specific QHermiteElement<1>
Implements oomph::FiniteElement.
Definition at line 48 of file hermite_elements.cc.
References s, and oomph::OneDimHermite::shape().
shape() [2/3]
void oomph::QHermiteElement< 2 >::shape (const Vector< double > & s, Shape & psi) const [virtual]
Shape function for specific QHermiteElement<2>
Implements oomph::FiniteElement.
Definition at line 371 of file hermite_elements.cc.
References s, and oomph::OneDimHermite::shape().
shape() [3/3]
template<unsigned DIM>
void oomph::QHermiteElement< DIM >::shape (const Vector< double > & s, Shape & psi) const [virtual]
Function to calculate the geometric shape functions at local coordinate s.
Implements oomph::FiniteElement.
Reimplemented in oomph::ClampedHermiteShellBoundaryConditionElement.
Referenced by oomph::HermiteBeamElement::output().
tecplot_zone_string() [1/3]
template<unsigned DIM>
std::string oomph::QHermiteElement< DIM >::tecplot_zone_string (const unsigned & nplot) const [virtual]
Return string for tecplot zone header (when plotting nplot points in each "coordinate direction)
Reimplemented from oomph::FiniteElement.
tecplot_zone_string() [2/3]
std::string oomph::QHermiteElement< 1 >::tecplot_zone_string (const unsigned & nplot) const [inline], [virtual]
Return string for tecplot zone header (when plotting nplot points in each coordinate direction)
Reimplemented from oomph::FiniteElement.
Definition at line 350 of file hermite_elements.h.
tecplot_zone_string() [3/3]
std::string oomph::QHermiteElement< 2 >::tecplot_zone_string (const unsigned & nplot) const [inline], [virtual]
Return string for tecplot zone header (when plotting nplot points in each coordinate direction)
Reimplemented from oomph::FiniteElement.
Definition at line 409 of file hermite_elements.h.
transform_second_derivatives()
template<unsigned DIM>
void oomph::QHermiteElement< DIM >::transform_second_derivatives (const DenseMatrix< double > & jacobian, const DenseMatrix< double > & inverse_jacobian, const DenseMatrix< double > & jacobian2, DShape & dbasis, DShape & d2basis) const [inline], [virtual]
Overload the template-free interface for the calculation of transformation of second derivatives. The element dimension should be passed as a template paremeter, for `optimum` efficiency.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::DiagQHermiteElement< DIM >.
Definition at line 192 of file hermite_elements.h.
Member Data Documentation
Default_integration_scheme
template<unsigned DIM>
Gauss< DIM, 3 > oomph::QHermiteElement< DIM >::Default_integration_scheme [static], [private]
Default integration rule: Gaussian integration of same 'order' as the element.
Assign the static Default_integration_scheme.
Definition at line 94 of file hermite_elements.h.
The documentation for this class was generated from the following files:
hermite_elements.h
hermite_elements.cc