oomph::RefineableAxisymmetricQCrouzeixRaviartElement Class Reference
Refineable version of Axisymmetric Quad Crouzeix Raviart elements (note that unlike the cartesian version this is not scale-able to higher dimensions!)
#include <refineable_axisym_navier_stokes_elements.h>
Public Member Functions
RefineableAxisymmetricQCrouzeixRaviartElement ()
Constructor:
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: 3 (velocities)
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: Reconstruct pressure from the (merged) sons.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get all function values [u,v..,p] at previous timestep t (t=0: present; t>0: previous timestep).
Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Note: No pressure history is kept, so pressure is always the current value.
void further_setup_hanging_nodes ()
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty.
void further_build ()
Further build for Crouzeix_Raviart interpolates the internal pressure dofs from father element: Make sure pressure values and dp/ds agree between fathers and sons at the midpoints of the son elements.
Private Member Functions
void unpin_elemental_pressure_dofs ()
Unpin all the internal pressure freedoms.
Additional Inherited Members
Detailed Description
Refineable version of Axisymmetric Quad Crouzeix Raviart elements (note that unlike the cartesian version this is not scale-able to higher dimensions!)
Definition at line 761 of file refineable_axisym_navier_stokes_elements.h.
Constructor & Destructor Documentation
RefineableAxisymmetricQCrouzeixRaviartElement()
oomph::RefineableAxisymmetricQCrouzeixRaviartElement::RefineableAxisymmetricQCrouzeixRaviartElement () [inline]
Constructor:
Definition at line 780 of file refineable_axisym_navier_stokes_elements.h.
Member Function Documentation
further_build()
void oomph::RefineableAxisymmetricQCrouzeixRaviartElement::further_build () [inline], [virtual]
Further build for Crouzeix_Raviart interpolates the internal pressure dofs from father element: Make sure pressure values and dp/ds agree between fathers and sons at the midpoints of the son elements.
Reimplemented from oomph::RefineableAxisymmetricNavierStokesEquations.
Definition at line 984 of file refineable_axisym_navier_stokes_elements.h.
References oomph::Tree::father_pt(), oomph::RefineableAxisymmetricNavierStokesEquations::further_build(), oomph::GeneralisedElement::internal_data_pt(), oomph::AxisymmetricNavierStokesEquations::interpolated_p_axi_nst(), oomph::QuadTreeNames::NE, oomph::QuadTreeNames::NW, oomph::Tree::object_pt(), oomph::AxisymmetricQCrouzeixRaviartElement::P_axi_nst_internal_index, oomph::RefineableQElement< 2 >::quadtree_pt(), oomph::QuadTreeNames::SE, oomph::Data::set_value(), oomph::Tree::son_type(), oomph::QuadTreeNames::SW, and oomph::Data::value().
further_setup_hanging_nodes()
void oomph::RefineableAxisymmetricQCrouzeixRaviartElement::further_setup_hanging_nodes () [inline], [virtual]
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty.
Implements oomph::RefineableQElement< 2 >.
Definition at line 978 of file refineable_axisym_navier_stokes_elements.h.
get_interpolated_values() [1/2]
void oomph::RefineableAxisymmetricQCrouzeixRaviartElement::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get all function values [u,v..,p] at previous timestep t (t=0: present; t>0: previous timestep).
Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Note: No pressure history is kept, so pressure is always the current value.
Implements oomph::RefineableElement.
Definition at line 942 of file refineable_axisym_navier_stokes_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), t, and oomph::AxisymmetricNavierStokesEquations::u_index_axi_nst().
get_interpolated_values() [2/2]
void oomph::RefineableAxisymmetricQCrouzeixRaviartElement::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 918 of file refineable_axisym_navier_stokes_elements.h.
References i, oomph::AxisymmetricNavierStokesEquations::interpolated_u_axi_nst(), and s.
ncont_interpolated_values()
unsigned oomph::RefineableAxisymmetricQCrouzeixRaviartElement::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values: 3 (velocities)
Implements oomph::RefineableElement.
Definition at line 789 of file refineable_axisym_navier_stokes_elements.h.
nrecovery_order()
unsigned oomph::RefineableAxisymmetricQCrouzeixRaviartElement::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 897 of file refineable_axisym_navier_stokes_elements.h.
nvertex_node()
unsigned oomph::RefineableAxisymmetricQCrouzeixRaviartElement::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 903 of file refineable_axisym_navier_stokes_elements.h.
References oomph::FiniteElement::nvertex_node().
rebuild_from_sons()
void oomph::RefineableAxisymmetricQCrouzeixRaviartElement::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
Rebuild from sons: Reconstruct pressure from the (merged) sons.
Implements oomph::RefineableElement.
Definition at line 795 of file refineable_axisym_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), oomph::QuadTreeNames::NE, oomph::QuadTreeNames::NW, oomph::Tree::object_pt(), oomph::AxisymmetricQCrouzeixRaviartElement::P_axi_nst_internal_index, oomph::RefineableQElement< 2 >::quadtree_pt(), oomph::QuadTreeNames::SE, oomph::Data::set_value(), oomph::Tree::son_pt(), oomph::QuadTreeNames::SW, and oomph::Data::value().
unpin_elemental_pressure_dofs()
void oomph::RefineableAxisymmetricQCrouzeixRaviartElement::unpin_elemental_pressure_dofs () [inline], [private], [virtual]
Unpin all the internal pressure freedoms.
Implements oomph::RefineableAxisymmetricNavierStokesEquations.
Definition at line 768 of file refineable_axisym_navier_stokes_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), oomph::AxisymmetricQCrouzeixRaviartElement::npres_axi_nst(), oomph::AxisymmetricQCrouzeixRaviartElement::P_axi_nst_internal_index, and oomph::Data::unpin().
vertex_node_pt()
Node * oomph::RefineableAxisymmetricQCrouzeixRaviartElement::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 909 of file refineable_axisym_navier_stokes_elements.h.
References oomph::FiniteElement::vertex_node_pt().
The documentation for this class was generated from the following file:
refineable_axisym_navier_stokes_elements.h