oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT > Class Template Reference
A class for elements that allow the imposition of an applied combined traction and pore fluid pressure in the axisym poroelasticity equations. The geometrical information can be read from the FaceGeometry<ELEMENT> class and thus, we can be generic enough without the need to have a separate equations class.
#include <axisym_poroelasticity_face_elements.h>
Public Member Functions
AxisymmetricPoroelasticityTractionElement (FiniteElement *const &element_pt, const int &face_index)
Constructor, which takes a `bulk` element and the value of the index and its limit.
AxisymmetricPoroelasticityTractionElement ()
Default constructor.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Return the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Fill in contribution from Jacobian.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
void output (std::ostream &outfile)
Output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
void output (FILE *file_pt)
C_style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function.
double lagrangian_eulerian_translation_factor (const Vector< double > &s)
Ratio of lengths of line elements (or annular surface areas) in the undeformed and deformed configuration (needed to translate normal flux correctly between small displacement formulation used here and the possibly large displacement NSt formulation used in FSI problems. Maths is as follows: Surface area: A = 2 \pi \int r \sqrt((dr/ds)^2+(dz/ds)^2) ds = 2 \pi \int J ds This function returns the ratio of J in the undeformed configuration (used here) to that in the deformed configuration where (r,z) = (r,z)_undef + (u_r,u_z).
void traction (const double &time, const Vector< double > &s, Vector< double > &traction)
Compute traction vector at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
void pressure (const double &time, const Vector< double > &s, double &pressure)
Compute pressure value at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
void contribution_to_total_porous_flux (double &skeleton_flux_contrib, double &seepage_flux_contrib)
Compute contributions to integrated porous flux over boundary: q_skeleton = \int \partial u_displ / \partial t \cdot n ds q_seepage = \int k q \cdot n ds.
Public Attributes
void(*&)(const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction) traction_fct_pt ()
Reference to the traction function pointer.
void(*&)(const double &time, const Vector< double > &x, const Vector< double > &n, double &pressure) pressure_fct_pt ()
Reference to the pressure function pointer.
Protected Member Functions
virtual void get_traction (const double &time, const unsigned &intpt, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction)
Get the traction vector: Pass number of integration point (dummy), Eulerrian coordinate and normal vector and return the pressure (not all of the input arguments will be required for all specific load functions but the list should cover all cases). This function is virtual so it can be overloaded for FSI.
virtual void get_pressure (const double &time, const unsigned &intpt, const Vector< double > &x, const Vector< double > &n, double &pressure)
Get the pressure value: Pass number of integration point (dummy), Eulerrian coordinate and normal vector and return the pressure (not all of the input arguments will be required for all specific load functions but the list should cover all cases). This function is virtual so it can be overloaded for FSI.
void fill_in_contribution_to_residuals_axisym_poroelasticity_face (Vector< double > &residuals)
Helper function that actually calculates the residuals.
Protected Attributes
void(* Traction_fct_pt)(const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
Pointer to an imposed traction function. Arguments: Eulerian coordinate; outer unit normal; applied traction. (Not all of the input arguments will be required for all specific load functions but the list should cover all cases)
void(* Pressure_fct_pt)(const double &time, const Vector< double > &x, const Vector< double > &n, double &result)
Pointer to an imposed pressure function. Arguments: Eulerian coordinate; outer unit normal; applied pressure. (Not all of the input arguments will be required for all specific load functions but the list should cover all cases)
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >
A class for elements that allow the imposition of an applied combined traction and pore fluid pressure in the axisym poroelasticity equations. The geometrical information can be read from the FaceGeometry<ELEMENT> class and thus, we can be generic enough without the need to have a separate equations class.
Definition at line 92 of file axisym_poroelasticity_face_elements.h.
Constructor & Destructor Documentation
AxisymmetricPoroelasticityTractionElement() [1/2]
template<class ELEMENT >
oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::AxisymmetricPoroelasticityTractionElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit.
Definition at line 156 of file axisym_poroelasticity_face_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FaceElement::face_index(), oomph::FiniteElement::has_hanging_nodes(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::Pressure_fct_pt, oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::Traction_fct_pt, oomph::AxisymmetricPoroelasticityTractionElementHelper::Zero_pressure_fct(), and oomph::AxisymmetricPoroelasticityTractionElementHelper::Zero_traction_fct().
AxisymmetricPoroelasticityTractionElement() [2/2]
template<class ELEMENT >
oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::AxisymmetricPoroelasticityTractionElement () [inline]
Default constructor.
Definition at line 199 of file axisym_poroelasticity_face_elements.h.
Member Function Documentation
contribution_to_total_porous_flux()
template<class ELEMENT >
void oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::contribution_to_total_porous_flux (double & skeleton_flux_contrib, double & seepage_flux_contrib) [inline]
Compute contributions to integrated porous flux over boundary: q_skeleton = \int \partial u_displ / \partial t \cdot n ds q_seepage = \int k q \cdot n ds.
Calculate the FE representation of q
Definition at line 530 of file axisym_poroelasticity_face_elements.h.
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dshape_local_at_knot(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::Integral::knot(), oomph::FaceElement::local_coordinate_in_bulk(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), oomph::MathematicalConstants::Pi, s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Fill in contribution from Jacobian.
Reimplemented from oomph::GeneralisedElement.
Definition at line 229 of file axisym_poroelasticity_face_elements.h.
References oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals_axisym_poroelasticity_face().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Return the residuals.
Reimplemented from oomph::GeneralisedElement.
Definition at line 222 of file axisym_poroelasticity_face_elements.h.
References oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals_axisym_poroelasticity_face().
fill_in_contribution_to_residuals_axisym_poroelasticity_face()
template<class ELEMENT >
void oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals_axisym_poroelasticity_face (Vector< double > & residuals) [protected]
Helper function that actually calculates the residuals.
Return the residuals for the AxisymmetricPoroelasticityTractionElement equations.
Definition at line 703 of file axisym_poroelasticity_face_elements.h.
References i, and oomph::QuadTreeNames::W.
Referenced by oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals().
get_pressure()
template<class ELEMENT >
virtual void oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::get_pressure (const double & time, const unsigned & intpt, const Vector< double > & x, const Vector< double > & n, double & pressure) [inline], [protected], [virtual]
Get the pressure value: Pass number of integration point (dummy), Eulerrian coordinate and normal vector and return the pressure (not all of the input arguments will be required for all specific load functions but the list should cover all cases). This function is virtual so it can be overloaded for FSI.
Reimplemented in oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >.
Definition at line 135 of file axisym_poroelasticity_face_elements.h.
References oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::pressure(), and oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::Pressure_fct_pt.
Referenced by oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output().
get_traction()
template<class ELEMENT >
virtual void oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::get_traction (const double & time, const unsigned & intpt, const Vector< double > & x, const Vector< double > & n, Vector< double > & traction) [inline], [protected], [virtual]
Get the traction vector: Pass number of integration point (dummy), Eulerrian coordinate and normal vector and return the pressure (not all of the input arguments will be required for all specific load functions but the list should cover all cases). This function is virtual so it can be overloaded for FSI.
Reimplemented in oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >.
Definition at line 121 of file axisym_poroelasticity_face_elements.h.
References oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::traction(), and oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::Traction_fct_pt.
Referenced by oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output().
lagrangian_eulerian_translation_factor()
template<class ELEMENT >
double oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::lagrangian_eulerian_translation_factor (const Vector< double > & s) [inline]
Ratio of lengths of line elements (or annular surface areas) in the undeformed and deformed configuration (needed to translate normal flux correctly between small displacement formulation used here and the possibly large displacement NSt formulation used in FSI problems. Maths is as follows: Surface area: A = 2 \pi \int r \sqrt((dr/ds)^2+(dz/ds)^2) ds = 2 \pi \int J ds This function returns the ratio of J in the undeformed configuration (used here) to that in the deformed configuration where (r,z) = (r,z)_undef + (u_r,u_z).
Calculate the FE representation of u -- the skeleton displacement
Definition at line 447 of file axisym_poroelasticity_face_elements.h.
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dshape_local(), i, oomph::FaceElement::interpolated_x(), oomph::FaceElement::local_coordinate_in_bulk(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FaceElement::outer_unit_normal(), and s.
Referenced by oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output().
output() [1/4]
template<class ELEMENT >
void oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C_style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 425 of file axisym_poroelasticity_face_elements.h.
References oomph::CommandLineArgs::output().
output() [2/4]
template<class ELEMENT >
void oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 431 of file axisym_poroelasticity_face_elements.h.
References oomph::CommandLineArgs::output().
output() [3/4]
template<class ELEMENT >
void oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Definition at line 249 of file axisym_poroelasticity_face_elements.h.
References oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output().
Referenced by oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output().
output() [4/4]
template<class ELEMENT >
void oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function.
Calculate the FE representation of u -- the skeleton displacement
Skeleton velocity
Reimplemented from oomph::FiniteElement.
Definition at line 257 of file axisym_poroelasticity_face_elements.h.
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dshape_local(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::get_pressure(), oomph::FiniteElement::get_s_plot(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::get_traction(), i, oomph::FaceElement::interpolated_x(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::lagrangian_eulerian_translation_factor(), oomph::FaceElement::local_coordinate_in_bulk(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::nplot_points(), oomph::FaceElement::outer_unit_normal(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::pressure(), s, oomph::FiniteElement::tecplot_zone_string(), oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::traction(), and oomph::FiniteElement::write_tecplot_zone_footer().
pressure()
template<class ELEMENT >
void oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::pressure (const double & time, const Vector< double > & s, double & pressure)
Compute pressure value at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
Definition at line 677 of file axisym_poroelasticity_face_elements.h.
References s.
Referenced by oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::get_pressure(), and oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output().
traction()
template<class ELEMENT >
void oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::traction (const double & time, const Vector< double > & s, Vector< double > & traction)
Compute traction vector at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Compute traction vector at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
Definition at line 651 of file axisym_poroelasticity_face_elements.h.
References s.
Referenced by oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::get_traction(), and oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output().
zeta_nodal()
template<class ELEMENT >
double oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Reimplemented from oomph::FiniteElement.
Definition at line 241 of file axisym_poroelasticity_face_elements.h.
References i, and oomph::FaceElement::zeta_nodal().
Member Data Documentation
pressure_fct_pt
template<class ELEMENT >
void(*&)(const double &time, const Vector< double > &x, const Vector< double > &n, double &pressure) oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::pressure_fct_pt() [inline]
Reference to the pressure function pointer.
Definition at line 212 of file axisym_poroelasticity_face_elements.h.
Pressure_fct_pt
template<class ELEMENT >
void(* oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::Pressure_fct_pt) (const double &time, const Vector< double > &x, const Vector< double > &n, double &result) [protected]
Pointer to an imposed pressure function. Arguments: Eulerian coordinate; outer unit normal; applied pressure. (Not all of the input arguments will be required for all specific load functions but the list should cover all cases)
Definition at line 110 of file axisym_poroelasticity_face_elements.h.
Referenced by oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::AxisymmetricPoroelasticityTractionElement(), and oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::get_pressure().
traction_fct_pt
template<class ELEMENT >
void(*&)(const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction) oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::traction_fct_pt() [inline]
Reference to the traction function pointer.
Definition at line 202 of file axisym_poroelasticity_face_elements.h.
Traction_fct_pt
template<class ELEMENT >
void(* oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::Traction_fct_pt) (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result) [protected]
Pointer to an imposed traction function. Arguments: Eulerian coordinate; outer unit normal; applied traction. (Not all of the input arguments will be required for all specific load functions but the list should cover all cases)
Definition at line 101 of file axisym_poroelasticity_face_elements.h.
Referenced by oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::AxisymmetricPoroelasticityTractionElement(), and oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::get_traction().
The documentation for this class was generated from the following file:
axisym_poroelasticity_face_elements.h