oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT > Class Template Reference
Mesh for 2D Bretherton problem -- based on single layer mesh. Templated by spine-ified Navier-Stokes element type (e.g. SpineElement<QCrouzeixRaviartElement<2> > and the corresponding interface element (e.g. SpineLineFluidInterfaceElement<SpineElement<QCrouzeixRaviartElement<2> > >
#include <bretherton_spine_mesh.h>
Public Member Functions
BrethertonSpineMesh (const unsigned &nx1, const unsigned &nx2, const unsigned &nx3, const unsigned &nh, const unsigned &nhalf, const double &h, GeomObject *lower_wall_pt, GeomObject *upper_wall_pt, const double &zeta_start, const double &zeta_transition_start, const double &zeta_transition_end, const double &zeta_end, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor. Arguments:
FiniteElement *& interface_element_pt (const unsigned long &i)
Access functions for pointers to interface elements.
unsigned long ninterface_element () const
Number of elements on interface.
FiniteElement *& bulk_element_pt (const unsigned long &i)
Access functions for pointers to elements in bulk.
unsigned long nbulk () const
Number of elements in bulk.
unsigned nfree_surface_spines ()
Number of free-surface spines (i.e. excluding the dummy spines in the channel region)
double find_distance_to_free_surface (GeomObject *const &fs_geom_object_pt, Vector< double > &initial_zeta, const Vector< double > &spine_base, const Vector< double > &spine_end)
Recalculate the spine lengths after repositioning.
void reposition_spines (const double &zeta_lo_transition_start, const double &zeta_lo_transition_end, const double &zeta_up_transition_start, const double &zeta_up_transition_end)
Reposition the spines in response to changes in geometry.
void pin_all_spines ()
Pin all spines so the mesh can be used for computation without free surfaces.
void spine_node_update (SpineNode *spine_node_pt)
General node update function implements pure virtual function defined in SpineMesh base class and performs specific update actions, depending on the node update fct id stored for each node.
ELEMENT * control_element_pt ()
Pointer to control element (just under the symmetry line near the bubble tip, so the bubble tip is located at s=[1.0,1.0] in this element.
double spine_centre_fraction () const
Read the value of the spine centre's vertical fraction.
void set_spine_centre_fraction_pt (double *const &fraction_pt)
Set the pointer to the spine centre's vertial fraction.
Public Member Functions inherited from oomph::SingleLayerSpineMesh< ELEMENT >
SingleLayerSpineMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &h, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass number of elements in x-direction, number of elements in y-direction, axial length, height of layer, and pointer to timestepper (defaults to Steady timestepper)
SingleLayerSpineMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &h, const bool &periodic_in_x, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass number of elements in x-direction, number of elements in y-direction, axial length, height of layer, a boolean flag to make the mesh periodic in the x-direction, and a pointer to timestepper (defaults to Steady timestepper)
Public Member Functions inherited from oomph::RectangularQuadMesh< ELEMENT >
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Simple constructor: nx: number of elements in x direction; ny: number of elements in y direction; lx, length of domain in x direction (0,lx); ly, length of domain in y direction (0,ly) Also pass pointer to timestepper (defaults to Steady)
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor that allows the specification of minimum and maximum values of x and y coordinates.
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly, const bool &periodic_in_x, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Simple constructor: nx: number of elements in x direction; ny: number of elements in y direction; lx, length of domain in x direction (0,lx); ly, length of domain in y direction (0,ly) Boolean flag specifies if the mesh is periodic in the x-direction. Also pass pointer to timestepper (defaults to Steady)
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, const bool &periodic_in_x, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor that allows the specification of minimum and maximum values of x and y coordinates. Boolean flag specifies if the mesh is periodic in the x-direction.
const unsigned & nx () const
Return number of elements in x direction.
const unsigned & ny () const
Return number of elements in y direction.
const double x_min () const
Return the minimum value of x coordinate.
const double x_max () const
Return the maximum value of x coordinate.
const double y_min () const
Return the minimum value of y coordinate.
const double y_max () const
Return the maximum value of y coordinate.
virtual void element_reorder ()
Reorder the elements: By default they are ordered in "horizontal" layers (increasing in x, then in y). This function changes this to an ordering in the vertical direction (y first, then x). This is more efficient if a frontal solver is used and the mesh has more elements in the x than the y direction. Can be overloaded in specific derived meshes.
virtual double x_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode)
Return the value of the x-coordinate at the node given by the local node number (xnode, ynode) in the element (xelement,yelement). The description is in a "psudeo" two-dimensional coordinate system, so the range of xelement is [0,Nx-1], yelement is [0,Ny-1], and that of xnode and ynode is [0,Np-1]. The default is to return nodes that are equally spaced in the x coodinate.
virtual double y_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode)
Return the value of the y-coordinate at the node given by the local node number (xnode, ynode) in the element (xelement,yelement). The description is in a "psudeo" two-dimensional coordinate system, so the range of xelement is [0,Nx-1], yelement is [0,Ny-1], and that of xnode and ynode is [0,Np-1]. The default it to return nodes that are equally spaced in the y coordinate.
Public Member Functions inherited from oomph::QuadMeshBase
QuadMeshBase ()
Constructor (empty)
QuadMeshBase (const QuadMeshBase &node)=delete
Broken copy constructor.
void operator= (const QuadMeshBase &)=delete
Broken assignment operator.
virtual ~QuadMeshBase ()
Destructor (empty)
void setup_boundary_element_info ()
Setup lookup schemes which establish whic elements are located next to mesh's boundaries (wrapper to suppress doc).
void setup_boundary_element_info (std::ostream &outfile)
Setup lookup schemes which establish whic elements are located next to mesh's boundaries. Doc in outfile (if it's open).
Public Member Functions inherited from oomph::Mesh
void resize_halo_nodes ()
Helper function that resizes halo nodes to the same size as their non-halo counterparts if required. (A discrepancy can arise if a FaceElement that introduces additional unknowns are attached to a bulk element that shares a node with a haloed element. In that case the joint node between haloed and non-haloed element is resized on that processor but not on the one that holds the halo counterpart (because no FaceElement is attached to the halo element)
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
Constructor builds combined mesh from the meshes specified. Note: This simply merges the meshes' elements and nodes (ignoring duplicates; no boundary information etc. is created).
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
Merge meshes. Note: This simply merges the meshes' elements and nodes (ignoring duplicates; no boundary information etc. is created).
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned > > &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
Output boundary coordinates on boundary b -- template argument specifies the bulk element type (needed to create FaceElement of appropriate type on mesh boundary).
virtual void scale_mesh (const double &factor)
Scale all nodal coordinates by given factor. Virtual so it can be overloaded in SolidMesh class where it also re-assigns the Lagrangian coordinates.
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
Flush storage for elements and nodes by emptying the vectors that store the pointers to them. This is useful if a particular mesh is only built to generate a small part of a bigger mesh. Once the elements and nodes have been created, they are typically copied into the new mesh and the auxiliary mesh can be deleted. However, if we simply call the destructor of the auxiliary mesh, it will also wipe out the nodes and elements, because it still "thinks" it's in charge of these...
void flush_element_storage ()
Flush storage for elements (only) by emptying the vectors that store the pointers to them. This is useful if a particular mesh is only built to generate a small part of a bigger mesh. Once the elements and nodes have been created, they are typically copied into the new mesh and the auxiliary mesh can be deleted. However, if we simply call the destructor of the auxiliary mesh, it will also wipe out the nodes and elements, because it still "thinks" it's in charge of these...
void flush_node_storage ()
Flush storage for nodes (only) by emptying the vectors that store the pointers to them.
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Upcast (downcast?) to FiniteElement (needed to access FiniteElement member functions).
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
Remove all information about nodes stored on the b-th boundary of the mesh.
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
Replace existing boundary node lookup schemes with new schemes created using the boundary data stored in the nodes.
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
void set_boundary_coordinate_exists (const unsigned &i)
Set boundary coordinate on the i-th boundary to be existing.
void set_boundary_coordinate_does_not_exist (const unsigned &i)
Set boundary coordinate on the i-th boundary to be non-existing.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void reorder_nodes (const bool &use_old_ordering=true)
Re-order nodes in the order in which they appear in elements -- can be overloaded for more efficient re-ordering.
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
Get a reordering of the nodes in the order in which they appear in elements -- can be overloaded for more efficient re-ordering.
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
Constuct a Mesh of FACE_ELEMENTs along the b-th boundary of the mesh (which contains elements of type BULK_ELEMENT)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
Determine max and min area for all FiniteElements in the mesh (non-FiniteElements are ignored)
double total_size ()
Determine the sum of all "sizes" of the FiniteElements in the mesh (non-FiniteElements are ignored). This gives the length/area/volume occupied by the mesh.
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
Check for inverted elements and report outcome in boolean variable. This visits all elements at their integration points and checks if the Jacobian of the mapping between local and global coordinates is positive -- using the same test that would be carried out (but only in PARANOID mode) during the assembly of the elements' Jacobian matrices. Inverted elements are output in inverted_element_file (if the stream is open).
void check_inverted_elements (bool &mesh_has_inverted_elements)
Check for inverted elements and report outcome in boolean variable. This visits all elements at their integration points and checks if the Jacobian of the mapping between local and global coordinates is positive -- using the same test that would be carried out (but only in PARANOID mode) during the assembly of the elements' Jacobian matrices.
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Check for repeated nodes within a given spatial tolerance. Return (0/1) for (pass/fail).
Vector< Node * > prune_dead_nodes ()
Prune nodes. Nodes that have been marked as obsolete are removed from the mesh (and its boundary-node scheme). Returns vector of pointers to deleted nodes.
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
Find a node not on any boundary in mesh_pt (useful for pinning a single node in a purely Neumann problem so that it is fully determined).
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
For the e-th finite element on boundary b, return int to indicate the face_index of the face adjacent to the boundary. This is consistent with input required during the generation of FaceElements.
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
Output in paraview format into specified file. Breaks up each element into sub-elements for plotting purposes. We assume that all elements are of the same type (fct will break break (in paranoid mode) if paraview output fcts of the elements are inconsistent).
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
Output in paraview format into specified file. Breaks up each element into sub-elements for plotting purposes. We assume that all elements are of the same type (fct will break break (in paranoid mode) if paraview output fcts of the elements are inconsistent).
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
Output in paraview format into specified file. Breaks up each element into sub-elements for plotting purposes. We assume that all elements are of the same type (fct will break break (in paranoid mode) if paraview output fcts of the elements are inconsistent).
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
Output a given time-dep. Vector function at f(n_plot) points in each element.
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
Output the nodes on the boundaries (into separate tecplot zones). Specify filename.
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
Shift time-dependent data along for next timestep: Deal with nodal Data/positions and the element's internal Data.
void calculate_predictions ()
Calculate predictions for all Data and positions associated with the mesh, usually used in adaptive time-stepping.
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with all nodal and elemental data stored in the mesh.
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the internal data stored within elements in the meah.
virtual void compute_norm (double &norm)
Compute norm of solution by summing contributions of compute_norm(...) for all constituent elements in the mesh. What that norm means depends on what's defined in the element's function; may need to take the square root afterwards if the elements compute the square of the L2 norm, say.
virtual void compute_norm (Vector< double > &norm)
Compute norm of solution by summing contributions of compute_norm(...) for all constituent elements in the mesh. What that norm means depends on what's defined in the element's function; may need to take the square root afterwards if the elements compute the square of the L2 norm, say.
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Plot error when compared against a given exact solution. Also returns the norm of the error and that of the exact solution.
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Plot error when compared against a given time-depdendent exact solution. Also returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Plot error when compared against a given time-dependent exact solution. Also returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
Plot error when compared against a given time-dependent exact solution. Also returns the norm of the error and that of the exact solution.
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
Plot error when compared against a given time-depdendent exact solution. Also returns the norm of the error and that of the exact solution. Version with vectors of norms and errors so that different variables' norms and errors can be returned individually.
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
Plot error when compared against a given time-depdendent exact solution. Also returns the norm of the error and that of the exact solution. Version with vectors of norms and errors so that different variables' norms and errors can be returned individually.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
Returns the norm of the error and that of the exact solution. Version with vectors of norms and errors so that different variables' norms and errors can be returned individually.
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
Read-only access fct to communicator (Null if mesh is not distributed, i.e. if we don't have mpi).
void set_communicator_pt (OomphCommunicator *comm_pt)
Function to set communicator (mesh is assumed to be distributed if the communicator pointer is non-null). Only defined if mpi is enabled becaus Comm_pt itself is only defined when mpi is enabled.
void set_keep_all_elements_as_halos ()
Call this function to keep all the elements as halo elements.
void unset_keep_all_elements_as_halos ()
Calll this function to unset the flag that keeps all elements in the mesh as halo elements.
virtual void distribute (OomphCommunicator *comm_pt, const Vector< unsigned > &element_domain, Vector< GeneralisedElement * > &deleted_element_pt, DocInfo &doc_info, const bool &report_stats, const bool &overrule_keep_as_halo_element_status)
Distribute the problem and doc; make this virtual to allow overloading for particular meshes where further work is required. Add to vector of pointers to deleted elements.
void distribute (OomphCommunicator *comm_pt, const Vector< unsigned > &element_domain, Vector< GeneralisedElement * > &deleted_element_pt, const bool &report_stats=false)
Distribute the problem Add to vector of pointers to deleted elements.
void prune_halo_elements_and_nodes (Vector< GeneralisedElement * > &deleted_element_pt, const bool &report_stats=false)
(Irreversibly) prune halo(ed) elements and nodes, usually after another round of refinement, to get rid of excessively wide halo layers. Note that the current mesh will be now regarded as the base mesh and no unrefinement relative to it will be possible once this function has been called.
void prune_halo_elements_and_nodes (Vector< GeneralisedElement * > &deleted_element_pt, DocInfo &doc_info, const bool &report_stats)
(Irreversibly) prune halo(ed) elements and nodes, usually after another round of refinement, to get rid of excessively wide halo layers. Note that the current mesh will be now regarded as the base mesh and no unrefinement relative to it will be possible once this function has been called.
void get_efficiency_of_mesh_distribution (double &av_efficiency, double &max_efficiency, double &min_efficiency)
Get efficiency of mesh distribution: In an ideal distribution without halo overhead, each processor would only hold its own elements. Efficieny per processor = (number of non-halo elements)/ (total number of elements).
void doc_mesh_distribution (DocInfo &doc_info)
Doc the mesh distribution, to be processed with tecplot macros.
void check_halo_schemes (DocInfo &doc_info, double &max_permitted_error_for_halo_check)
Check halo and shared schemes on the mesh.
virtual void classify_halo_and_haloed_nodes (DocInfo &doc_info, const bool &report_stats)
Classify the halo and haloed nodes in the mesh. Virtual so it can be overloaded to perform additional functionality (such as synchronising hanging nodes) in refineable meshes, say.
virtual void classify_halo_and_haloed_nodes (const bool &report_stats=false)
Classify the halo and haloed nodes in the mesh. Virtual so it can be overloaded to perform additional functionality (such as synchronising hanging nodes) in refineable meshes, say.
void synchronise_shared_nodes (const bool &report_stats)
Synchronise shared node lookup schemes to cater for the the case where: (1) a certain node on the current processor is halo with proc p (i.e. its non-halo counterpart lives on processor p) (2) that node is also exists (also as a halo) on another processor (q, say) where its non-halo counter part is also known to be on processor p. However, without calling this function the current processor does not necessarily know that it shares a node with processor q. This information can be required, e.g. when synchronising hanging node schemes over all processors.
void get_all_halo_data (std::map< unsigned, double * > &map_of_halo_data)
Get all the halo data stored in the mesh and add pointers to the data to the map, indexed by global equation number.
Vector< GeneralisedElement * > halo_element_pt (const unsigned &p)
Return vector of halo elements in this Mesh whose non-halo counterpart is held on processor p.
Vector< GeneralisedElement * > haloed_element_pt (const unsigned &p)
Return vector of haloed elements in this Mesh whose haloing counterpart is held on processor p.
unsigned nnon_halo_element ()
Total number of non-halo elements in this mesh (Costly call computes result on the fly)
unsigned nroot_halo_element ()
Total number of root halo elements in this Mesh.
unsigned nroot_halo_element (const unsigned &p)
Number of root halo elements in this Mesh whose non-halo counterpart is held on processor p.
Vector< GeneralisedElement * > root_halo_element_pt (const unsigned &p)
Vector of pointers to root halo elements in this Mesh whose non-halo counterpart is held on processor p.
GeneralisedElement *& root_halo_element_pt (const unsigned &p, const unsigned &e)
Access fct to the e-th root halo element in this Mesh whose non-halo counterpart is held on processor p.
void add_root_halo_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
Add root halo element whose non-halo counterpart is held on processor p to this Mesh.
unsigned nhalo_node ()
Total number of halo nodes in this Mesh.
unsigned nhalo_node (const unsigned &p)
Number of halo nodes in this Mesh whose non-halo counterpart is held on processor p.
void add_halo_node_pt (const unsigned &p, Node *&nod_pt)
Add halo node whose non-halo counterpart is held on processor p to the storage scheme for halo nodes.
Node * halo_node_pt (const unsigned &p, const unsigned &j)
Access fct to the j-th halo node in this Mesh whose non-halo counterpart is held on processor p.
unsigned nroot_haloed_element ()
Total number of root haloed elements in this Mesh.
unsigned nroot_haloed_element (const unsigned &p)
Number of root haloed elements in this Mesh whose non-halo counterpart is held on processor p.
Vector< GeneralisedElement * > root_haloed_element_pt (const unsigned &p)
Vector of pointers to root haloed elements in this Mesh whose non-halo counterpart is held on processor p.
GeneralisedElement *& root_haloed_element_pt (const unsigned &p, const unsigned &e)
Access fct to the e-th root haloed element in this Mesh whose non-halo counterpart is held on processor p.
void add_root_haloed_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
Add root haloed element whose non-halo counterpart is held on processor p to the storage scheme for haloed elements. Note: This does not add the element to the storage scheme for elements as it's understood to naturally live on this processor anyway!
unsigned nhaloed_node ()
Total number of haloed nodes in this Mesh.
unsigned nhaloed_node (const unsigned &p)
Number of haloed nodes in this Mesh whose haloed counterpart is held on processor p.
Node * haloed_node_pt (const unsigned &p, const unsigned &j)
Access fct to the j-th haloed node in this Mesh whose halo counterpart is held on processor p.
void add_haloed_node_pt (const unsigned &p, Node *&nod_pt)
Add haloed node whose halo counterpart is held on processor p to the storage scheme for haloed nodes.
void disable_resizing_of_halo_nodes ()
Function to suppress resizing of halo nodes -- optmisation but call it at your own risk!
void enable_resizing_of_halo_nodes ()
Function to (re-)enable resizing of halo nodes -- this returns things to the default behaviour.
void disable_output_of_halo_elements ()
Function to disable halo element output.
void enable_output_of_halo_elements ()
Function to enable halo element output.
unsigned nshared_node ()
Total number of shared nodes in this Mesh.
void doc_shared_nodes ()
Doc shared nodes.
unsigned nshared_node (const unsigned &p)
Number of shared nodes in this Mesh who have a counterpart on processor p.
Node * shared_node_pt (const unsigned &p, const unsigned &j)
Access fct to the j-th shared node in this Mesh who has a counterpart on processor p.
void get_shared_node_pt (const unsigned &p, Vector< Node * > &shared_node_pt)
Get vector of pointers to shared nodes with processor p. Required for faster search in Missing_masters_functions::add_external_haloed_node_helper() and Missing_masters_functions::add_external_haloed_master_node_helper()
void add_shared_node_pt (const unsigned &p, Node *&nod_pt)
Add shared node whose counterpart is held on processor p to the storage scheme for shared nodes. (NB: ensure that this routine is called twice, once for each process)
void get_halo_node_stats (double &av_number, unsigned &max_number, unsigned &min_number)
Get halo node stats for this distributed mesh: Average/max/min number of halo nodes over all processors. Careful: Involves MPI Broadcasts and must therefore be called on all processors!
void get_haloed_node_stats (double &av_number, unsigned &max_number, unsigned &min_number)
Get haloed node stats for this distributed mesh: Average/max/min number of haloed nodes over all processors. Careful: Involves MPI Broadcasts and must therefore be called on all processors!
void output_external_halo_elements (std::ostream &outfile, const unsigned &n_plot=5)
Output all external halo elements.
void output_external_halo_elements (const unsigned &p, std::ostream &outfile, const unsigned &n_plot=5)
Output all external halo elements with processor p.
void output_external_haloed_elements (std::ostream &outfile, const unsigned &n_plot=5)
Output all external haloed elements.
void output_external_haloed_elements (const unsigned &p, std::ostream &outfile, const unsigned &n_plot=5)
Output all external haloed elements with processor p.
unsigned nexternal_halo_element ()
Total number of external halo elements in this Mesh.
unsigned nexternal_halo_element (const unsigned &p)
Number of external halo elements in this Mesh whose non-halo counterpart is held on processor p.
GeneralisedElement *& external_halo_element_pt (const unsigned &p, const unsigned &e)
Access fct to the e-th external halo element in this Mesh whose non-halo counterpart is held on processor p.
void add_external_halo_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
Add external halo element whose non-halo counterpart is held on processor p to this Mesh.
unsigned nexternal_haloed_element ()
Total number of external haloed elements in this Mesh.
unsigned nexternal_haloed_element (const unsigned &p)
Number of external haloed elements in this Mesh whose non-halo counterpart is held on processor p.
GeneralisedElement *& external_haloed_element_pt (const unsigned &p, const unsigned &e)
Access fct to the e-th external haloed element in this Mesh whose non-halo counterpart is held on processor p.
unsigned add_external_haloed_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
Add external haloed element whose non-halo counterpart is held on processor p to the storage scheme for haloed elements.
unsigned nexternal_halo_node ()
Total number of external halo nodes in this Mesh.
void get_external_halo_node_pt (Vector< Node * > &external_halo_node_pt)
Get vector of pointers to all external halo nodes.
unsigned nexternal_halo_node (const unsigned &p)
Number of external halo nodes in this Mesh whose non-halo (external) counterpart is held on processor p.
void add_external_halo_node_pt (const unsigned &p, Node *&nod_pt)
Add external halo node whose non-halo (external) counterpart is held on processor p to the storage scheme for halo nodes.
Node *& external_halo_node_pt (const unsigned &p, const unsigned &j)
Access fct to the j-th external halo node in this Mesh whose non-halo external counterpart is held on processor p.
Vector< Node * > external_halo_node_pt (const unsigned &p)
Access fct to vector of external halo node in this Mesh whose non-halo external counterpart is held on processor p. (read only)
void set_external_halo_node_pt (const unsigned &p, const Vector< Node * > &external_halo_node_pt)
Set vector of external halo node in this Mesh whose non-halo external counterpart is held on processor p.
void null_external_halo_node (const unsigned &p, Node *nod_pt)
Null out specified external halo node (used when deleting duplicates)
void remove_null_pointers_from_external_halo_node_storage ()
Consolidate external halo node storage by removing nulled out pointes in external halo and haloed schemes.
unsigned nexternal_haloed_node ()
Total number of external haloed nodes in this Mesh.
unsigned nexternal_haloed_node (const unsigned &p)
Number of external haloed nodes in this Mesh whose halo (external) counterpart is held on processor p.
Node *& external_haloed_node_pt (const unsigned &p, const unsigned &j)
Access fct to the j-th external haloed node in this Mesh whose halo external counterpart is held on processor p.
unsigned add_external_haloed_node_pt (const unsigned &p, Node *&nod_pt)
Add external haloed node whose halo (external) counterpart is held on processor p to the storage scheme for haloed nodes.
Vector< Node * > external_haloed_node_pt (const unsigned &p)
Access fct to vector of external haloed node in this Mesh whose halo external counterpart is held on processor p. (read only)
void set_external_haloed_node_pt (const unsigned &p, const Vector< Node * > &external_haloed_node_pt)
Set vector of external haloed node in this Mesh whose halo external counterpart is held on processor p.
std::set< int > external_halo_proc ()
Return the set of processors that hold external halo nodes. This is required to avoid having to pass a communicator into the node_update functions for Algebraic-based and MacroElement-based Meshes.
virtual void create_shared_boundaries (OomphCommunicator *comm_pt, const Vector< unsigned > &element_domain, const Vector< GeneralisedElement * > &backed_up_el_pt, const Vector< FiniteElement * > &backed_up_f_el_pt, std::map< Data *, std::set< unsigned > > &processors_associated_with_data, const bool &overrule_keep_as_halo_element_status)
Creates the shared boundaries, only used in unstructured meshes In this case with the "TriangleMesh" class.
virtual unsigned try_to_add_root_haloed_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
virtual unsigned try_to_add_haloed_node_pt (const unsigned &p, Node *&nod_pt)
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Public Member Functions inherited from oomph::SpineMesh
virtual ~SpineMesh ()
Destructor to clean up the memory allocated to the spines.
Spine *& spine_pt (const unsigned long &i)
Return the i-th spine in the mesh.
const Spine * spine_pt (const unsigned long &i) const
Return the i-th spine in the mesh (const version)
unsigned long nspine () const
Return the number of spines in the mesh.
void add_spine_pt (Spine *const &spine_pt)
Add a spine to the mesh.
SpineNode * node_pt (const unsigned long &n)
Return a pointer to the n-th global SpineNode.
SpineNode * element_node_pt (const unsigned long &e, const unsigned &n)
Return the n-th local SpineNode in element e. This is required to cast the nodes in a spine mesh to be SpineNodes and therefore allow access to the extra SpineNode data.
virtual unsigned long assign_global_spine_eqn_numbers (Vector< double * > &Dof_pt)
Assign spines to Spine_pt vector of element.
void describe_spine_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the dofs of the Spine. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Overload the mesh_level timestepper function to set the timestepper data for the spines.
void set_spine_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the time stepper forthe spine data that is stored in the mesh.
void set_consistent_pinned_spine_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set any pinned spine "history" values to be consistent for continuation problems.
bool does_pointer_correspond_to_spine_data (double *const &parameter_pt)
Check whether the pointer parameter_pt addresses data stored in the spines.
void node_update (const bool &update_all_solid_nodes=false)
Update function to update all nodes of mesh [Doesn't make sense to use this mesh with SolidElements anyway, so we buffer the case if update_all_solid_nodes is set to true.].
void dump (std::ofstream &dump_file) const
Overload the dump function so that the spine data is dumped.
void read (std::ifstream &restart_file)
Overload the read function so that the spine data is read from the restart file.
Protected Member Functions
void spine_node_update_film_lower (SpineNode *spine_node_pt)
Update function for the deposited film region in the lower part of the domain: Vertical spines.
void spine_node_update_horizontal_transition_lower (SpineNode *spine_node_pt)
Update function for the horizontal transitition region in the lower part of the domain: Spine points from wall to origin.
void spine_node_update_vertical_transition_lower (SpineNode *spine_node_pt)
Update function for the vertical transitition region in the lower part of the domain: Spine points to origin.
void spine_node_update_vertical_transition_upper (SpineNode *spine_node_pt)
Update function for the vertical transitition region in the upper part of the domain: Spine points to origin.
void spine_node_update_horizontal_transition_upper (SpineNode *spine_node_pt)
Update function for the horizontal transitition region in the upper part of the domain: Spine points towards origin.
void spine_node_update_film_upper (SpineNode *spine_node_pt)
Update function for the deposited film region in the upper part of the domain: Vertical spines.
void spine_node_update_channel (SpineNode *spine_node_pt)
Update function for the nodes in the channel region ahead of the finger tip: Nodes are evenly distributed along vertical lines between the top and bottom walls.
void initial_element_reorder ()
Initial reordering elements of the elements -- before the channel mesh is added. Vertical stacks of elements, each topped by their interface element -- this is (currently) identical to the version in the SingleLayerSpineMesh but it's important that the element reordering is maintained in exactly this form for the rest of the mesh generation process to work properly. Therefore we keep a copy of the function in here.
Protected Member Functions inherited from oomph::SingleLayerSpineMesh< ELEMENT >
virtual void build_single_layer_mesh (TimeStepper *time_stepper_pt)
Helper function to actually build the single-layer spine mesh (called from various constructors)
Protected Member Functions inherited from oomph::RectangularQuadMesh< ELEMENT >
void build_mesh (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Generic mesh construction function: contains all the hard work.
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, const bool &periodic_in_x, const bool &build, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor that allows the specification of minimum and maximum values of x and y coordinates and does not build the mesh This is intend to be used in derived classes that overload the spacing functions. THis is scheduled to be changed, however. The reason why this MUST be done is because the virtual spacing functions cannot be called in the base constructur, because they will not have been overloaded yet!!
Protected Member Functions inherited from oomph::Mesh
void setup_shared_node_scheme ()
Setup shared node scheme.
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign the global equation numbers in the Data stored at the nodes and also internal element Data. Also, build (via push_back) the Vector of pointers to the dofs (variables).
void describe_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the dofs of the Mesh. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the local dofs of the elements. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers in all elements If the boolean argument is true then also store pointers to dofs.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
A function that upgrades an ordinary node to a boundary node We shouldn't ever really use this, but it does make life that bit easier for the lazy mesh writer. The pointer to the node is replaced by a pointer to the new boundary node in all element look-up schemes and in the mesh's Node_pt vector. The new node is also addressed by node_pt on return from the function.
void convert_to_boundary_node (Node *&node_pt)
A function that upgrades an ordinary node to a boundary node. All pointers to the node from the mesh's elements are found. and replaced by pointers to the new boundary node. If the node is present in the mesh's list of nodes, that pointer is also replaced. Finally, the pointer argument node_pt addresses the new node on return from the function. We shouldn't ever really use this, but it does make life that bit easier for the lazy mesh writer.
Protected Attributes
unsigned Nx1
Number of elements along wall in deposited film region.
unsigned Nx2
Number of elements along wall in horizontal transition region.
unsigned Nx3
Number of elements along wall in channel region.
unsigned Nhalf
Number of elements in vertical transition region (there are twice as many elements across the channel)
unsigned Nh
Number of elements across the deposited film.
double H
Thickness of deposited film.
GeomObject * Upper_wall_pt
Pointer to geometric object that represents the upper wall.
GeomObject * Lower_wall_pt
Pointer to geometric object that represents the lower wall.
double Zeta_start
Start coordinate on wall.
double Zeta_end
Wall coordinate of end of liquid filled region (inflow)
double Zeta_transition_start
Wall coordinate of start of the transition region.
double Zeta_transition_end
Wall coordinate of end of transition region.
double * Spine_centre_fraction_pt
Pointer to vertical fraction of the spine centre.
double Default_spine_centre_fraction
Default spine fraction.
ELEMENT * Control_element_pt
Pointer to control element (just under the symmetry line near the bubble tip; the bubble tip is located at s=[1.0,1.0] in this element.
Vector< FiniteElement * > Bulk_element_pt
Vector of pointers to element in the fluid layer.
Vector< FiniteElement * > Interface_element_pt
Vector of pointers to interface elements.
Protected Attributes inherited from oomph::RectangularQuadMesh< ELEMENT >
unsigned Nx
Nx: number of elements in x-direction.
unsigned Ny
Ny: number of elements in y-direction.
unsigned Np
Np: number of (linear) points in the element.
double Xmin
Minimum value of x coordinate.
double Xmax
Maximum value of x coordinate.
double Ymin
Minimum value of y coordinate.
double Ymax
Maximum value of y coordinate.
bool Xperiodic
Boolean variable used to determine whether the mesh is periodic in the x-direction.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
Vector of Vector of pointers to nodes on the boundaries: Boundary_node_pt(b,n). Note that this is private to force the use of the add_boundary_node() function, which ensures that the reverse look-up schemes for the nodes are set up.
bool Lookup_for_elements_next_boundary_is_setup
Flag to indicate that the lookup schemes for elements that are adjacent to the boundaries has been set up.
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector of Vector of pointers to elements on the boundaries: Boundary_element_pt(b,e)
Vector< Vector< int > > Face_index_at_boundary
For the e-th finite element on boundary b, this is the index of the face that lies along that boundary.
std::map< unsigned, Vector< GeneralisedElement * > > Root_halo_element_pt
Map of vectors holding the pointers to the root halo elements.
std::map< unsigned, Vector< GeneralisedElement * > > Root_haloed_element_pt
Map of vectors holding the pointers to the root haloed elements.
std::map< unsigned, Vector< Node * > > Halo_node_pt
Map of vectors holding the pointers to the halo nodes.
std::map< unsigned, Vector< Node * > > Haloed_node_pt
Map of vectors holding the pointers to the haloed nodes.
std::map< unsigned, Vector< Node * > > Shared_node_pt
Map of vectors holding the pointers to the shared nodes. These are all the nodes that are on two "neighbouring" processes (the halo(ed) lookup scheme depends upon which processor is in charge.
OomphCommunicator * Comm_pt
Pointer to communicator -- set to NULL if mesh is not distributed.
std::map< unsigned, Vector< GeneralisedElement * > > External_halo_element_pt
External halo(ed) elements are created as and when they are needed to act as source elements for the particular process's mesh. The storage is wiped and rebuilt every time the mesh is refined.
std::map< unsigned, Vector< GeneralisedElement * > > External_haloed_element_pt
Map of vectors holding the pointers to the external haloed elements.
std::map< unsigned, Vector< Node * > > External_halo_node_pt
Map of vectors holding the pointers to the external halo nodes.
std::map< unsigned, Vector< Node * > > External_haloed_node_pt
Map of vectors holding the pointers to the external haloed nodes.
bool Keep_all_elements_as_halos
bool to indicate whether to keep all elements in a mesh as halos or not
bool Resize_halo_nodes_not_required
Set this to true to suppress resizing of halo nodes (at your own risk!)
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
Protected Attributes inherited from oomph::SpineMesh
Vector< Spine * > Spine_pt
A Spine mesh contains a Vector of pointers to spines.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
Typedef for function pointer to function that computes steady exact solution.
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Typedef for function pointer to function that computes unsteady exact solution.
Public Attributes inherited from oomph::Mesh
bool Output_halo_elements
Bool for output of halo elements.
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
Default Steady Timestepper, to be used in default arguments to Mesh constructors.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Boolean used to control warning about empty mesh level timestepper function.
Detailed Description
template<class ELEMENT, class INTERFACE_ELEMENT>
class oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >
Mesh for 2D Bretherton problem -- based on single layer mesh. Templated by spine-ified Navier-Stokes element type (e.g. SpineElement<QCrouzeixRaviartElement<2> > and the corresponding interface element (e.g. SpineLineFluidInterfaceElement<SpineElement<QCrouzeixRaviartElement<2> > >
Definition at line 44 of file bretherton_spine_mesh.h.
Constructor & Destructor Documentation
BrethertonSpineMesh()
template<class ELEMENT , class INTERFACE_ELEMENT >
oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh (const unsigned & nx1, const unsigned & nx2, const unsigned & nx3, const unsigned & nh, const unsigned & nhalf, const double & h, GeomObject * lower_wall_pt, GeomObject * upper_wall_pt, const double & zeta_start, const double & zeta_transition_start, const double & zeta_transition_end, const double & zeta_end, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor. Arguments:
nx1: Number of elements along wall in deposited film region
nx2: Number of elements along wall in horizontal transition region
nx3: Number of elements along wall in channel region
nhalf: Number of elements in vertical transition region (there are twice as many elements across the channel)
nh: Number of elements across the deposited film
h: Thickness of deposited film
zeta0: Start coordinate on wall
zeta1: Wall coordinate of start of transition region
zeta2: Wall coordinate of end of liquid filled region (inflow)
lower_wall_pt: Pointer to geometric object that represents the lower wall
upper_wall_pt: Pointer to geometric object that represents the upper wall
time_stepper_pt: Pointer to timestepper; defaults to Steady
nx1: Number of elements along wall in deposited film region
nx2: Number of elements along wall in horizontal transition region
nx3: Number of elements along wall in channel region
nhalf: Number of elements in vertical transition region (there are twice as many elements across the channel)
nh: Number of elements across the deposited film
h: Thickness of deposited film
zeta0: Start coordinate on wall
zeta1: Wall coordinate of start of transition region
zeta2: Wall coordinate of end of liquid filled region (inflow)
lower_wall_pt: Pointer to geometric object that represents the lower wall
upper_wall_pt: Pointer to geometric object that represents the upper wall
time_stepper_pt: Pointer to timestepper; defaults to Static
Definition at line 60 of file bretherton_spine_mesh.template.cc.
References oomph::Mesh::add_boundary_node(), oomph::Mesh::boundary_node_pt(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Bulk_element_pt, oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Control_element_pt, e, oomph::SpineMesh::element_node_pt(), oomph::Mesh::Element_pt, oomph::Mesh::element_pt(), oomph::Mesh::finite_element_pt(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::H, i, oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::initial_element_reorder(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Interface_element_pt, oomph::GeomObject::locate_zeta(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Lower_wall_pt, oomph::Mesh::nboundary_node(), oomph::Mesh::nelement(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::node_pt(), oomph::Mesh::Node_pt, oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nx3, oomph::oomph_info, oomph::FiniteElement::position(), oomph::GeomObject::position(), oomph::Mesh::remove_boundary_nodes(), oomph::Node::set_coordinates_on_boundary(), oomph::Mesh::set_nboundary(), oomph::Mesh::setup_boundary_element_info(), oomph::FiniteElement::size(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_centre_fraction(), oomph::SpineMesh::Spine_pt, oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Upper_wall_pt, oomph::Node::x(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Zeta_end, oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Zeta_start, oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Zeta_transition_end, and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Zeta_transition_start.
Member Function Documentation
bulk_element_pt()
template<class ELEMENT , class INTERFACE_ELEMENT >
FiniteElement *& oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::bulk_element_pt (const unsigned long & i) [inline]
Access functions for pointers to elements in bulk.
Definition at line 91 of file bretherton_spine_mesh.h.
References oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Bulk_element_pt, and i.
control_element_pt()
template<class ELEMENT , class INTERFACE_ELEMENT >
ELEMENT * oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::control_element_pt () [inline]
Pointer to control element (just under the symmetry line near the bubble tip, so the bubble tip is located at s=[1.0,1.0] in this element.
Definition at line 183 of file bretherton_spine_mesh.h.
References oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Control_element_pt.
find_distance_to_free_surface()
template<class ELEMENT , class INTERFACE_ELEMENT >
double oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::find_distance_to_free_surface (GeomObject *const & fs_geom_object_pt, Vector< double > & initial_zeta, const Vector< double > & spine_base, const Vector< double > & spine_end)
Recalculate the spine lengths after repositioning.
Calculate the distance from the spine base to the free surface, i.e. the spine height.
Definition at line 1056 of file bretherton_spine_mesh.template.cc.
References i, oomph::oomph_info, oomph::FiniteElement::position(), oomph::DoubleMatrixBase::solve(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
initial_element_reorder()
template<class ELEMENT , class INTERFACE_ELEMENT >
void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::initial_element_reorder () [protected]
Initial reordering elements of the elements -- before the channel mesh is added. Vertical stacks of elements, each topped by their interface element -- this is (currently) identical to the version in the SingleLayerSpineMesh but it's important that the element reordering is maintained in exactly this form for the rest of the mesh generation process to work properly. Therefore we keep a copy of the function in here.
Reorder elements: Vertical stacks of elements, each topped by their interface element -- this is (currently) identical to the version in the SingleLayerSpineMesh but it's important that element reordering is maintained in exactly this form so to be on the safe side, we move the function in here.
Definition at line 1019 of file bretherton_spine_mesh.template.cc.
References e, and i.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh().
interface_element_pt()
template<class ELEMENT , class INTERFACE_ELEMENT >
FiniteElement *& oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::interface_element_pt (const unsigned long & i) [inline]
Access functions for pointers to interface elements.
Definition at line 79 of file bretherton_spine_mesh.h.
References i, and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Interface_element_pt.
nbulk()
template<class ELEMENT , class INTERFACE_ELEMENT >
unsigned long oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::nbulk () const [inline]
Number of elements in bulk.
Definition at line 97 of file bretherton_spine_mesh.h.
References oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Bulk_element_pt, and oomph::FiniteElement::size().
nfree_surface_spines()
template<class ELEMENT , class INTERFACE_ELEMENT >
unsigned oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::nfree_surface_spines () [inline]
Number of free-surface spines (i.e. excluding the dummy spines in the channel region)
Definition at line 104 of file bretherton_spine_mesh.h.
References oomph::Mesh::finite_element_pt(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nhalf, oomph::FiniteElement::nnode_1d(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nx1, and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nx2.
ninterface_element()
template<class ELEMENT , class INTERFACE_ELEMENT >
unsigned long oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::ninterface_element () const [inline]
Number of elements on interface.
Definition at line 85 of file bretherton_spine_mesh.h.
References oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Interface_element_pt, and oomph::FiniteElement::size().
pin_all_spines()
template<class ELEMENT , class INTERFACE_ELEMENT >
void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::pin_all_spines () [inline]
Pin all spines so the mesh can be used for computation without free surfaces.
Definition at line 124 of file bretherton_spine_mesh.h.
References i, oomph::SpineMesh::nspine(), oomph::Data::pin(), oomph::Spine::spine_height_pt(), and oomph::SpineMesh::spine_pt().
reposition_spines()
template<class ELEMENT , class INTERFACE_ELEMENT >
void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::reposition_spines (const double & zeta_lo_transition_start, const double & zeta_lo_transition_end, const double & zeta_up_transition_start, const double & zeta_up_transition_end)
Reposition the spines in response to changes in geometry.
Reposition the spines that emenate from the lower wall.
Definition at line 1148 of file bretherton_spine_mesh.template.cc.
References e, i, oomph::FiniteElement::locate_zeta(), oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::node_pt(), oomph::oomph_info, oomph::FiniteElement::position(), oomph::Node::set_coordinates_on_boundary(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
set_spine_centre_fraction_pt()
template<class ELEMENT , class INTERFACE_ELEMENT >
void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::set_spine_centre_fraction_pt (double *const & fraction_pt) [inline]
Set the pointer to the spine centre's vertial fraction.
Definition at line 196 of file bretherton_spine_mesh.h.
References oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Spine_centre_fraction_pt.
spine_centre_fraction()
template<class ELEMENT , class INTERFACE_ELEMENT >
double oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_centre_fraction () const [inline]
Read the value of the spine centre's vertical fraction.
Definition at line 190 of file bretherton_spine_mesh.h.
References oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Spine_centre_fraction_pt.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_lower(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_upper().
spine_node_update()
template<class ELEMENT , class INTERFACE_ELEMENT >
void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update (SpineNode * spine_node_pt) [inline], [virtual]
General node update function implements pure virtual function defined in SpineMesh base class and performs specific update actions, depending on the node update fct id stored for each node.
Reimplemented from oomph::SingleLayerSpineMesh< ELEMENT >.
Definition at line 136 of file bretherton_spine_mesh.h.
References oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_channel(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_lower(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_upper().
spine_node_update_channel()
template<class ELEMENT , class INTERFACE_ELEMENT >
void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_channel (SpineNode * spine_node_pt) [inline], [protected]
Update function for the nodes in the channel region ahead of the finger tip: Nodes are evenly distributed along vertical lines between the top and bottom walls.
Definition at line 458 of file bretherton_spine_mesh.h.
References oomph::FiniteElement::position().
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update().
spine_node_update_film_lower()
template<class ELEMENT , class INTERFACE_ELEMENT >
void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_lower (SpineNode * spine_node_pt) [inline], [protected]
Update function for the deposited film region in the lower part of the domain: Vertical spines.
Definition at line 204 of file bretherton_spine_mesh.h.
References oomph::FiniteElement::position().
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update().
spine_node_update_film_upper()
template<class ELEMENT , class INTERFACE_ELEMENT >
void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_upper (SpineNode * spine_node_pt) [inline], [protected]
Update function for the deposited film region in the upper part of the domain: Vertical spines.
Definition at line 434 of file bretherton_spine_mesh.h.
References oomph::FiniteElement::position().
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update().
spine_node_update_horizontal_transition_lower()
template<class ELEMENT , class INTERFACE_ELEMENT >
void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_lower (SpineNode * spine_node_pt) [inline], [protected]
Update function for the horizontal transitition region in the lower part of the domain: Spine points from wall to origin.
Definition at line 227 of file bretherton_spine_mesh.h.
References oomph::FiniteElement::position(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_centre_fraction().
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update().
spine_node_update_horizontal_transition_upper()
template<class ELEMENT , class INTERFACE_ELEMENT >
void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_upper (SpineNode * spine_node_pt) [inline], [protected]
Update function for the horizontal transitition region in the upper part of the domain: Spine points towards origin.
Definition at line 387 of file bretherton_spine_mesh.h.
References oomph::FiniteElement::position(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_centre_fraction().
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update().
spine_node_update_vertical_transition_lower()
template<class ELEMENT , class INTERFACE_ELEMENT >
void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_lower (SpineNode * spine_node_pt) [inline], [protected]
Update function for the vertical transitition region in the lower part of the domain: Spine points to origin.
Definition at line 273 of file bretherton_spine_mesh.h.
References oomph::FiniteElement::position(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_centre_fraction().
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update().
spine_node_update_vertical_transition_upper()
template<class ELEMENT , class INTERFACE_ELEMENT >
void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_upper (SpineNode * spine_node_pt) [inline], [protected]
Update function for the vertical transitition region in the upper part of the domain: Spine points to origin.
Definition at line 330 of file bretherton_spine_mesh.h.
References oomph::FiniteElement::position(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_centre_fraction().
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update().
Member Data Documentation
Bulk_element_pt
template<class ELEMENT , class INTERFACE_ELEMENT >
Vector<FiniteElement*> oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Bulk_element_pt [protected]
Vector of pointers to element in the fluid layer.
Definition at line 537 of file bretherton_spine_mesh.h.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::bulk_element_pt(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::nbulk().
Control_element_pt
template<class ELEMENT , class INTERFACE_ELEMENT >
ELEMENT* oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Control_element_pt [protected]
Pointer to control element (just under the symmetry line near the bubble tip; the bubble tip is located at s=[1.0,1.0] in this element.
Definition at line 534 of file bretherton_spine_mesh.h.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::control_element_pt().
Default_spine_centre_fraction
template<class ELEMENT , class INTERFACE_ELEMENT >
double oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Default_spine_centre_fraction [protected]
Default spine fraction.
Definition at line 529 of file bretherton_spine_mesh.h.
H
template<class ELEMENT , class INTERFACE_ELEMENT >
double oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::H [protected]
Thickness of deposited film.
Definition at line 505 of file bretherton_spine_mesh.h.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh().
Interface_element_pt
template<class ELEMENT , class INTERFACE_ELEMENT >
Vector<FiniteElement*> oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Interface_element_pt [protected]
Vector of pointers to interface elements.
Definition at line 540 of file bretherton_spine_mesh.h.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::interface_element_pt(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::ninterface_element().
Lower_wall_pt
template<class ELEMENT , class INTERFACE_ELEMENT >
GeomObject* oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Lower_wall_pt [protected]
Pointer to geometric object that represents the lower wall.
Definition at line 511 of file bretherton_spine_mesh.h.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh().
Nh
template<class ELEMENT , class INTERFACE_ELEMENT >
unsigned oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nh [protected]
Number of elements across the deposited film.
Definition at line 502 of file bretherton_spine_mesh.h.
Nhalf
template<class ELEMENT , class INTERFACE_ELEMENT >
unsigned oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nhalf [protected]
Number of elements in vertical transition region (there are twice as many elements across the channel)
Definition at line 499 of file bretherton_spine_mesh.h.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::nfree_surface_spines().
Nx1
template<class ELEMENT , class INTERFACE_ELEMENT >
unsigned oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nx1 [protected]
Number of elements along wall in deposited film region.
Definition at line 489 of file bretherton_spine_mesh.h.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::nfree_surface_spines().
Nx2
template<class ELEMENT , class INTERFACE_ELEMENT >
unsigned oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nx2 [protected]
Number of elements along wall in horizontal transition region.
Definition at line 492 of file bretherton_spine_mesh.h.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::nfree_surface_spines().
Nx3
template<class ELEMENT , class INTERFACE_ELEMENT >
unsigned oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nx3 [protected]
Number of elements along wall in channel region.
Definition at line 495 of file bretherton_spine_mesh.h.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh().
Spine_centre_fraction_pt
template<class ELEMENT , class INTERFACE_ELEMENT >
double* oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Spine_centre_fraction_pt [protected]
Pointer to vertical fraction of the spine centre.
Definition at line 526 of file bretherton_spine_mesh.h.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::set_spine_centre_fraction_pt(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_centre_fraction().
Upper_wall_pt
template<class ELEMENT , class INTERFACE_ELEMENT >
GeomObject* oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Upper_wall_pt [protected]
Pointer to geometric object that represents the upper wall.
Definition at line 508 of file bretherton_spine_mesh.h.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh().
Zeta_end
template<class ELEMENT , class INTERFACE_ELEMENT >
double oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Zeta_end [protected]
Wall coordinate of end of liquid filled region (inflow)
Definition at line 517 of file bretherton_spine_mesh.h.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh().
Zeta_start
template<class ELEMENT , class INTERFACE_ELEMENT >
double oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Zeta_start [protected]
Start coordinate on wall.
Definition at line 514 of file bretherton_spine_mesh.h.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh().
Zeta_transition_end
template<class ELEMENT , class INTERFACE_ELEMENT >
double oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Zeta_transition_end [protected]
Wall coordinate of end of transition region.
Definition at line 523 of file bretherton_spine_mesh.h.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh().
Zeta_transition_start
template<class ELEMENT , class INTERFACE_ELEMENT >
double oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Zeta_transition_start [protected]
Wall coordinate of start of the transition region.
Definition at line 520 of file bretherton_spine_mesh.h.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh().
The documentation for this class was generated from the following files:
bretherton_spine_mesh.h
bretherton_spine_mesh.template.cc