oomph::QSphericalAdvectionDiffusionElement< NNODE_1D > Class Template Reference
QSphericalAdvectionDiffusionElement elements are linear/quadrilateral/brick-shaped Axisymmetric Advection Diffusion elements with isoparametric interpolation for the function.
#include <spherical_advection_diffusion_elements.h>
Public Member Functions
QSphericalAdvectionDiffusionElement ()
Constructor: Call constructors for QElement and Advection Diffusion equations.
QSphericalAdvectionDiffusionElement (const QSphericalAdvectionDiffusionElement< NNODE_1D > &dummy)
Broken copy constructor.
void operator= (const QSphericalAdvectionDiffusionElement< NNODE_1D > &)
Broken assignment operator.
unsigned required_nvalue (const unsigned &n) const
Required # of `values' (pinned or dofs) at node n.
void output (std::ostream &outfile)
Output function: r,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: r,z,u at n_plot^2 plot points.
void output (FILE *file_pt)
C-style output function: r,z,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: r,z,u at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: r,z,u_exact at n_plot^2 plot points.
Protected Member Functions
double dshape_and_dtest_eulerian_spherical_adv_diff (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
double dshape_and_dtest_eulerian_at_knot_spherical_adv_diff (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Static Private Attributes
static const unsigned Initial_Nvalue
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >
QSphericalAdvectionDiffusionElement elements are linear/quadrilateral/brick-shaped Axisymmetric Advection Diffusion elements with isoparametric interpolation for the function.
Definition at line 495 of file spherical_advection_diffusion_elements.h.
Constructor & Destructor Documentation
QSphericalAdvectionDiffusionElement() [1/2]
template<unsigned NNODE_1D>
oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >::QSphericalAdvectionDiffusionElement () [inline]
Constructor: Call constructors for QElement and Advection Diffusion equations.
Definition at line 507 of file spherical_advection_diffusion_elements.h.
QSphericalAdvectionDiffusionElement() [2/2]
template<unsigned NNODE_1D>
oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >::QSphericalAdvectionDiffusionElement (const QSphericalAdvectionDiffusionElement< NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 513 of file spherical_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_spherical_adv_diff()
template<unsigned NNODE_1D>
double oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >::dshape_and_dtest_eulerian_at_knot_spherical_adv_diff (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::SphericalAdvectionDiffusionEquations.
Definition at line 638 of file spherical_advection_diffusion_elements.h.
dshape_and_dtest_eulerian_spherical_adv_diff()
template<unsigned NNODE_1D>
double oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >::dshape_and_dtest_eulerian_spherical_adv_diff (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Galerkin: Test functions = shape functions
Implements oomph::SphericalAdvectionDiffusionEquations.
Definition at line 604 of file spherical_advection_diffusion_elements.h.
References i, and s.
operator=()
template<unsigned NNODE_1D>
void oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >::operator= (const QSphericalAdvectionDiffusionElement< NNODE_1D > &) [inline]
Broken assignment operator.
Definition at line 520 of file spherical_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
template<unsigned NNODE_1D>
void oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function: r,z,u.
Reimplemented from oomph::QElement< 2, NNODE_1D >.
Definition at line 549 of file spherical_advection_diffusion_elements.h.
References oomph::SphericalAdvectionDiffusionEquations::output().
output() [2/4]
template<unsigned NNODE_1D>
void oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: r,z,u at n_plot^2 plot points.
Reimplemented from oomph::QElement< 2, NNODE_1D >.
Definition at line 556 of file spherical_advection_diffusion_elements.h.
References oomph::SphericalAdvectionDiffusionEquations::output().
output() [3/4]
template<unsigned NNODE_1D>
void oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: r,z,u.
Reimplemented from oomph::QElement< 2, NNODE_1D >.
Definition at line 534 of file spherical_advection_diffusion_elements.h.
References oomph::SphericalAdvectionDiffusionEquations::output().
output() [4/4]
template<unsigned NNODE_1D>
void oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: r,z,u at n_plot^2 plot points.
Reimplemented from oomph::QElement< 2, NNODE_1D >.
Definition at line 541 of file spherical_advection_diffusion_elements.h.
References oomph::SphericalAdvectionDiffusionEquations::output().
output_fct()
template<unsigned NNODE_1D>
void oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: r,z,u_exact at n_plot^2 plot points.
Reimplemented from oomph::SphericalAdvectionDiffusionEquations.
Definition at line 563 of file spherical_advection_diffusion_elements.h.
References oomph::SphericalAdvectionDiffusionEquations::output_fct().
required_nvalue()
template<unsigned NNODE_1D>
unsigned oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Required # of `values' (pinned or dofs) at node n.
Reimplemented from oomph::FiniteElement.
Definition at line 527 of file spherical_advection_diffusion_elements.h.
References oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >::Initial_Nvalue.
Member Data Documentation
Initial_Nvalue
template<unsigned NNODE_1D>
const unsigned oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >::Initial_Nvalue [static], [private]
Initial value:
=
    1
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Definition at line 502 of file spherical_advection_diffusion_elements.h.
Referenced by oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >::required_nvalue().
The documentation for this class was generated from the following files:
spherical_advection_diffusion_elements.h
spherical_advection_diffusion_elements.cc