oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT > Class Template Reference
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
#include <mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h>
Public Member Functions
RefineableNavierStokesMixedOrderSpaceTimeTractionElement (FiniteElement *const &element_pt, const int &face_index)
Constructor, which takes a `bulk` element and the face index.
~RefineableNavierStokesMixedOrderSpaceTimeTractionElement ()
Destructor should not delete anything.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values are the same as those in the bulk element.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
This function returns just the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the Jacobian.
Protected Member Functions
void refineable_fill_in_generic_residual_contribution_fluid_traction (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
A class for elements that allow the imposition of an applied traction to the Navier--Stokes equations The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
THIS IS THE REFINEABLE VERSION.
Definition at line 476 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
Constructor & Destructor Documentation
RefineableNavierStokesMixedOrderSpaceTimeTractionElement()
template<class ELEMENT >
oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::RefineableNavierStokesMixedOrderSpaceTimeTractionElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the face index.
Definition at line 482 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
 RefineableNavierStokesMixedOrderSpaceTimeTractionElement()
template<class ELEMENT >
oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::~RefineableNavierStokesMixedOrderSpaceTimeTractionElement () [inline]
Destructor should not delete anything.
Definition at line 492 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
This function returns the residuals and the Jacobian.
Reimplemented from oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >.
Definition at line 512 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
References oomph::FiniteElement::jacobian, and oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
This function returns just the residuals.
Reimplemented from oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >.
Definition at line 504 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction().
ncont_interpolated_values()
template<class ELEMENT >
unsigned oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values are the same as those in the bulk element.
Implements oomph::RefineableElement.
Definition at line 497 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
References oomph::FaceElement::bulk_element_pt(), and oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::ncont_interpolated_values().
Referenced by oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::ncont_interpolated_values().
refineable_fill_in_generic_residual_contribution_fluid_traction()
template<class ELEMENT >
void oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected]
This function returns the residuals for the traction function. flag=1(or 0): do (or don't) compute the Jacobian as well.
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Function that returns the residuals for the imposed traction Navier_Stokes equations
Definition at line 539 of file mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h.
References oomph::Multi_domain_functions::Dim, i, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), and oomph::W.
Referenced by oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_residuals().
The documentation for this class was generated from the following file:
mixed_order_petrov_galerkin_space_time_fluid_traction_elements.h