oomph::LinearisedQTaylorHoodElement Class Reference
/////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////
#include <linearised_navier_stokes_elements.h>
Public Member Functions
LinearisedQTaylorHoodElement ()
Constructor, no internal data points.
virtual unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
virtual int p_index_linearised_nst (const unsigned &i) const
Which nodal value represents the pressure? Overload version in base class which returns static int `Pressure_not_stored_at_node`.
double p_linearised_nst (const unsigned &n_p, const unsigned &i) const
Access function for the i-th component of pressure at local pressure node n_p (const version).
void pin_pressure_normalisation_dofs ()
Pin the normalisation dofs.
virtual void pin_real_or_imag (const unsigned &real)
Pin the real or imaginary part of the problem Input integer 0 for real 1 for imaginary.
virtual void unpin_real_or_imag (const unsigned &real)
unsigned npres_linearised_nst () const
Return number of pressure values corresponding to a single pressure component.
void fix_pressure (const unsigned &n_p, const double &pvalue)
Fix both components of the pressure at local pressure node n_p to pvalue.
int p_local_eqn (const unsigned &n, const unsigned &i)
Overload the access function for the i-th component of the pressure's local equation numbers.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
unsigned ndof_types () const
Returns the number of `dof-blocks` that degrees of freedom in this element are sub-divided into: Velocity and pressure.
Protected Member Functions
double dshape_and_dtest_eulerian_linearised_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivatives w.r.t. global coordinates at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_linearised_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivatives w.r.t. global coordinates the ipt-th integation point (taken from geometry). Return Jacobian of mapping between local and global coordinates.
void pshape_linearised_nst (const Vector< double > &s, Shape &psi) const
Compute the pressure shape functions at local coordinate s.
void pshape_linearised_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Compute the pressure shape and test functions at local coordinte s.
Static Protected Attributes
static const unsigned Pconv [] = {0, 2, 6, 8}
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Static Private Attributes
static const unsigned Initial_Nvalue []
Static array of ints to hold number of variables at node.
Additional Inherited Members
Detailed Description
/////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////
Taylor--Hood elements are Navier--Stokes elements with quadratic interpolation for velocities and positions and continuous linear pressure interpolation
Definition at line 924 of file linearised_navier_stokes_elements.h.
Constructor & Destructor Documentation
LinearisedQTaylorHoodElement()
oomph::LinearisedQTaylorHoodElement::LinearisedQTaylorHoodElement () [inline]
Constructor, no internal data points.
Definition at line 969 of file linearised_navier_stokes_elements.h.
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_linearised_nst()
double oomph::LinearisedQTaylorHoodElement::dshape_and_dtest_eulerian_at_knot_linearised_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivatives w.r.t. global coordinates the ipt-th integation point (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t global (Eulerian) coordinates at the ipt-th integration point. Return Jacobian of mapping between local and global coordinates.
Implements oomph::LinearisedNavierStokesEquations.
Definition at line 1109 of file linearised_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot().
dshape_and_dtest_eulerian_linearised_nst()
double oomph::LinearisedQTaylorHoodElement::dshape_and_dtest_eulerian_linearised_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivatives w.r.t. global coordinates at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t global (Eulerian) coordinates at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Implements oomph::LinearisedNavierStokesEquations.
Definition at line 1087 of file linearised_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian().
fix_pressure()
void oomph::LinearisedQTaylorHoodElement::fix_pressure (const unsigned & n_p, const double & pvalue) [inline]
Fix both components of the pressure at local pressure node n_p to pvalue.
Definition at line 1028 of file linearised_navier_stokes_elements.h.
References i, oomph::FiniteElement::node_pt(), p_index_linearised_nst(), oomph::Data::pin(), and oomph::Data::set_value().
ndof_types()
unsigned oomph::LinearisedQTaylorHoodElement::ndof_types () const [inline], [virtual]
Returns the number of `dof-blocks` that degrees of freedom in this element are sub-divided into: Velocity and pressure.
Reimplemented from oomph::GeneralisedElement.
Definition at line 1071 of file linearised_navier_stokes_elements.h.
npres_linearised_nst()
unsigned oomph::LinearisedQTaylorHoodElement::npres_linearised_nst () const [inline], [virtual]
Return number of pressure values corresponding to a single pressure component.
Implements oomph::LinearisedNavierStokesEquations.
Definition at line 1021 of file linearised_navier_stokes_elements.h.
output() [1/4]
void oomph::LinearisedQTaylorHoodElement::output (FILE * file_pt) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::LinearisedNavierStokesEquations.
Definition at line 1058 of file linearised_navier_stokes_elements.h.
References oomph::LinearisedNavierStokesEquations::output().
output() [2/4]
void oomph::LinearisedQTaylorHoodElement::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::LinearisedNavierStokesEquations.
Definition at line 1064 of file linearised_navier_stokes_elements.h.
References oomph::LinearisedNavierStokesEquations::output().
output() [3/4]
void oomph::LinearisedQTaylorHoodElement::output (std::ostream & outfile) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::LinearisedNavierStokesEquations.
Definition at line 1046 of file linearised_navier_stokes_elements.h.
References oomph::LinearisedNavierStokesEquations::output().
output() [4/4]
void oomph::LinearisedQTaylorHoodElement::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::LinearisedNavierStokesEquations.
Definition at line 1052 of file linearised_navier_stokes_elements.h.
References oomph::LinearisedNavierStokesEquations::output().
p_index_linearised_nst()
virtual int oomph::LinearisedQTaylorHoodElement::p_index_linearised_nst (const unsigned & i) const [inline], [virtual]
Which nodal value represents the pressure? Overload version in base class which returns static int `Pressure_not_stored_at_node`.
Reimplemented from oomph::LinearisedNavierStokesEquations.
Definition at line 983 of file linearised_navier_stokes_elements.h.
References i.
Referenced by fix_pressure(), p_linearised_nst(), and p_local_eqn().
p_linearised_nst()
double oomph::LinearisedQTaylorHoodElement::p_linearised_nst (const unsigned & n_p, const unsigned & i) const [inline], [virtual]
Access function for the i-th component of pressure at local pressure node n_p (const version).
Implements oomph::LinearisedNavierStokesEquations.
Definition at line 990 of file linearised_navier_stokes_elements.h.
References i, oomph::FiniteElement::nodal_value(), p_index_linearised_nst(), and Pconv.
p_local_eqn()
int oomph::LinearisedQTaylorHoodElement::p_local_eqn (const unsigned & n, const unsigned & i) [inline], [virtual]
Overload the access function for the i-th component of the pressure's local equation numbers.
Implements oomph::LinearisedNavierStokesEquations.
Definition at line 1040 of file linearised_navier_stokes_elements.h.
References i, oomph::FiniteElement::nodal_local_eqn(), p_index_linearised_nst(), and Pconv.
pin_pressure_normalisation_dofs()
void oomph::LinearisedQTaylorHoodElement::pin_pressure_normalisation_dofs () [inline], [virtual]
Pin the normalisation dofs.
Implements oomph::LinearisedNavierStokesEquations.
Definition at line 996 of file linearised_navier_stokes_elements.h.
pin_real_or_imag()
virtual void oomph::LinearisedQTaylorHoodElement::pin_real_or_imag (const unsigned & real) [inline], [virtual]
Pin the real or imaginary part of the problem Input integer 0 for real 1 for imaginary.
Implements oomph::LinearisedNavierStokesEquations.
Definition at line 1004 of file linearised_navier_stokes_elements.h.
pshape_linearised_nst() [1/2]
void oomph::LinearisedQTaylorHoodElement::pshape_linearised_nst (const Vector< double > & s, Shape & psi) const [inline], [protected], [virtual]
Compute the pressure shape functions at local coordinate s.
Pressure shape functions.
Implements oomph::LinearisedNavierStokesEquations.
Definition at line 1129 of file linearised_navier_stokes_elements.h.
References i, s, and oomph::OneDimLagrange::shape< 2 >().
Referenced by pshape_linearised_nst().
pshape_linearised_nst() [2/2]
void oomph::LinearisedQTaylorHoodElement::pshape_linearised_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected], [virtual]
Compute the pressure shape and test functions at local coordinte s.
Pressure shape and test functions.
Implements oomph::LinearisedNavierStokesEquations.
Definition at line 1154 of file linearised_navier_stokes_elements.h.
References i, pshape_linearised_nst(), and s.
required_nvalue()
virtual unsigned oomph::LinearisedQTaylorHoodElement::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::RefineableLinearisedQTaylorHoodElement.
Definition at line 976 of file linearised_navier_stokes_elements.h.
References Initial_Nvalue.
unpin_real_or_imag()
virtual void oomph::LinearisedQTaylorHoodElement::unpin_real_or_imag (const unsigned & real) [inline], [virtual]
Implements oomph::LinearisedNavierStokesEquations.
Definition at line 1011 of file linearised_navier_stokes_elements.h.
Member Data Documentation
Initial_Nvalue
const unsigned oomph::LinearisedQTaylorHoodElement::Initial_Nvalue [static], [private]
Initial value:
= {
    12, 8, 12, 8, 8, 8, 12, 8, 12}
Static array of ints to hold number of variables at node.
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Linearised axisymmetric Taylor-Hood elements
Set the data for the number of variables at each node
Definition at line 930 of file linearised_navier_stokes_elements.h.
Referenced by required_nvalue().
Pconv
const unsigned oomph::LinearisedQTaylorHoodElement::Pconv = {0, 2, 6, 8} [static], [protected]
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Set the data for the pressure conversion array.
Definition at line 935 of file linearised_navier_stokes_elements.h.
Referenced by p_linearised_nst(), and p_local_eqn().
The documentation for this class was generated from the following files:
linearised_navier_stokes_elements.h
linearised_navier_stokes_elements.cc