oomph::NonLinearElasticitySmoothMesh< ELEMENT > Class Template Reference
/////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////
#include <mesh_smooth.h>
Public Member Functions
void operator() (SolidMesh *orig_mesh_pt, SolidMesh *copy_of_mesh_pt, const Vector< unsigned > &controlled_boundary_id, const unsigned &max_steps=100000000)
Functor to update the nodal positions in SolidMesh pointed to by orig_mesh_pt in response to the displacement of some of its nodes relative to their original position which must still be indicated by the nodes' Lagrangian position. copy_of_mesh_pt must be a deep copy of orig_mesh_pt, with the same boundary coordinates etc. This mesh is used as workspace and can be deleted afterwards. The vector controlled_boundary_id contains the ids of the mesh boundaries in orig_mesh_pt whose position is supposed to remain fixed (while the other nodes are re-positioned to avoid the inversion of elements). The final optional argument specifies the max. number of increments in which the mesh boundary is deformed.
void operator() (SolidMesh *orig_mesh_pt, SolidMesh *copy_of_mesh_pt, const Vector< unsigned > &controlled_boundary_id, DocInfo doc_info, const unsigned &max_steps=100000000)
Functor to update the nodal positions in SolidMesh pointed to by orig_mesh_pt in response to the displacement of some of its nodes relative to their original position which must still be indicated by the nodes' Lagrangian position. copy_of_mesh_pt must be a deep copy of orig_mesh_pt, with the same boundary coordinates etc. This mesh is used as workspace and can be deleted afterwards. The vector controlled_boundary_id contains the ids of the mesh boundaries in orig_mesh_pt whose position is supposed to remain fixed (while the other nodes are re-positioned to avoid the inversion of elements). The DocInfo allows allows the output of the intermediate meshes. The final optional argument specifies the max. number of increments in which the mesh boundary is deformed.
~NonLinearElasticitySmoothMesh ()
Destructor (empty)
void actions_before_newton_solve ()
Update nodal positions in main mesh -- also moves the nodes of the FaceElements that impose the new position.
void backup ()
Backup nodal positions in dummy mesh to allow for reset after non-convergence of Newton method.
void reset ()
Reset nodal positions in dummy mesh to allow for restart of Newton method with reduced increment in Scale.
void doc_solution (DocInfo &doc_info)
Doc the solution.
Private Attributes
Vector< Vector< double > > Orig_node_pos
Original nodal positions.
Vector< Vector< double > > Backup_node_pos
Backup nodal positions.
SolidMesh * Orig_mesh_pt
Bulk original mesh.
SolidMesh * Dummy_mesh_pt
Copy of mesh to work on.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::NonLinearElasticitySmoothMesh< ELEMENT >
/////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////
Auxiliary Problem to smooth a SolidMesh by adjusting the internal nodal positions via the solution of a nonlinear solid mechanics problem. The mesh will typically have been created with an unstructured mesh generator that uses a low-order (simplex) representation of the element geometry; some of the nodes, typically non-vertex nodes on the domain's curvilinear boundaries, were then moved to their new position to provide a more accurate representation of the geometry. This class should be used to deal with elements that may have become inverted during the node motion.
Important assumption:
It is important that the Lagrangian coordinates of all nodes still indicate their original position, i.e. their position before (some of) them were moved to their new position. This is because we apply the boundary displacements in small increments.
Template argument specifies type of element. It must be a pure solid mechanics element! This shouldn't cause any problems since mesh smoothing operations tend to be performed off-line so the mesh may as well be built with pure solid elements even if it is ultimately to be used with other element types. (This restriction could easily be avoided but would require double templating and would generally be messy...)
Definition at line 97 of file mesh_smooth.h.
Constructor & Destructor Documentation
 NonLinearElasticitySmoothMesh()
template<class ELEMENT >
oomph::NonLinearElasticitySmoothMesh< ELEMENT >::~NonLinearElasticitySmoothMesh () [inline]
Destructor (empty)
Definition at line 390 of file mesh_smooth.h.
Member Function Documentation
actions_before_newton_solve()
template<class ELEMENT >
void oomph::NonLinearElasticitySmoothMesh< ELEMENT >::actions_before_newton_solve () [inline], [virtual]
Update nodal positions in main mesh -- also moves the nodes of the FaceElements that impose the new position.
Reimplemented from oomph::Problem.
Definition at line 395 of file mesh_smooth.h.
References i, oomph::Mesh::nnode(), oomph::SolidMesh::node_pt(), oomph::oomph_info, oomph::NonLinearElasticitySmoothMesh< ELEMENT >::Orig_mesh_pt, oomph::NonLinearElasticitySmoothMesh< ELEMENT >::Orig_node_pos, oomph::Helper_namespace_for_mesh_smoothing::Scale, and oomph::SolidNode::xi().
backup()
template<class ELEMENT >
void oomph::NonLinearElasticitySmoothMesh< ELEMENT >::backup () [inline]
Backup nodal positions in dummy mesh to allow for reset after non-convergence of Newton method.
Definition at line 416 of file mesh_smooth.h.
References oomph::NonLinearElasticitySmoothMesh< ELEMENT >::Backup_node_pos, oomph::NonLinearElasticitySmoothMesh< ELEMENT >::Dummy_mesh_pt, i, oomph::Mesh::nnode(), and oomph::SolidMesh::node_pt().
Referenced by oomph::NonLinearElasticitySmoothMesh< ELEMENT >::operator()().
doc_solution()
template<class ELEMENT >
void oomph::NonLinearElasticitySmoothMesh< ELEMENT >::doc_solution (DocInfo & doc_info) [inline]
Doc the solution.
Definition at line 450 of file mesh_smooth.h.
References oomph::Mesh::check_inverted_elements(), oomph::DocInfo::directory(), oomph::NonLinearElasticitySmoothMesh< ELEMENT >::Dummy_mesh_pt, oomph::DocInfo::is_doc_enabled(), oomph::DocInfo::number(), oomph::oomph_info, and oomph::Mesh::output().
Referenced by oomph::NonLinearElasticitySmoothMesh< ELEMENT >::operator()().
operator()() [1/2]
template<class ELEMENT >
void oomph::NonLinearElasticitySmoothMesh< ELEMENT >::operator() (SolidMesh * orig_mesh_pt, SolidMesh * copy_of_mesh_pt, const Vector< unsigned > & controlled_boundary_id, const unsigned & max_steps = 100000000) [inline]
Functor to update the nodal positions in SolidMesh pointed to by orig_mesh_pt in response to the displacement of some of its nodes relative to their original position which must still be indicated by the nodes' Lagrangian position. copy_of_mesh_pt must be a deep copy of orig_mesh_pt, with the same boundary coordinates etc. This mesh is used as workspace and can be deleted afterwards. The vector controlled_boundary_id contains the ids of the mesh boundaries in orig_mesh_pt whose position is supposed to remain fixed (while the other nodes are re-positioned to avoid the inversion of elements). The final optional argument specifies the max. number of increments in which the mesh boundary is deformed.
Definition at line 112 of file mesh_smooth.h.
References oomph::DocInfo::disable_doc().
operator()() [2/2]
template<class ELEMENT >
void oomph::NonLinearElasticitySmoothMesh< ELEMENT >::operator() (SolidMesh * orig_mesh_pt, SolidMesh * copy_of_mesh_pt, const Vector< unsigned > & controlled_boundary_id, DocInfo doc_info, const unsigned & max_steps = 100000000) [inline]
Functor to update the nodal positions in SolidMesh pointed to by orig_mesh_pt in response to the displacement of some of its nodes relative to their original position which must still be indicated by the nodes' Lagrangian position. copy_of_mesh_pt must be a deep copy of orig_mesh_pt, with the same boundary coordinates etc. This mesh is used as workspace and can be deleted afterwards. The vector controlled_boundary_id contains the ids of the mesh boundaries in orig_mesh_pt whose position is supposed to remain fixed (while the other nodes are re-positioned to avoid the inversion of elements). The DocInfo allows allows the output of the intermediate meshes. The final optional argument specifies the max. number of increments in which the mesh boundary is deformed.
Definition at line 141 of file mesh_smooth.h.
References oomph::Problem::add_sub_mesh(), oomph::Problem::assign_eqn_numbers(), oomph::NonLinearElasticitySmoothMesh< ELEMENT >::backup(), oomph::Mesh::boundary_element_pt(), oomph::Problem::build_global_mesh(), oomph::Helper_namespace_for_mesh_smoothing::Constitutive_law_pt, oomph::NonLinearElasticitySmoothMesh< ELEMENT >::doc_solution(), oomph::NonLinearElasticitySmoothMesh< ELEMENT >::Dummy_mesh_pt, e, oomph::Mesh::element_pt(), oomph::Mesh::face_index_at_boundary(), i, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::Mesh::nelement(), oomph::Problem::newton_solve(), oomph::Mesh::nnode(), oomph::SolidMesh::node_pt(), oomph::DocInfo::number(), oomph::oomph_info, oomph::NonLinearElasticitySmoothMesh< ELEMENT >::Orig_mesh_pt, oomph::NonLinearElasticitySmoothMesh< ELEMENT >::Orig_node_pos, oomph::NonLinearElasticitySmoothMesh< ELEMENT >::reset(), oomph::Helper_namespace_for_mesh_smoothing::Scale, oomph::Helper_namespace_for_mesh_smoothing::Scale_increment, oomph::FaceElement::set_boundary_number_in_bulk_mesh(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt(), and oomph::SolidMesh::set_lagrangian_nodal_coordinates().
reset()
template<class ELEMENT >
void oomph::NonLinearElasticitySmoothMesh< ELEMENT >::reset () [inline]
Reset nodal positions in dummy mesh to allow for restart of Newton method with reduced increment in Scale.
Definition at line 435 of file mesh_smooth.h.
References oomph::NonLinearElasticitySmoothMesh< ELEMENT >::Backup_node_pos, oomph::NonLinearElasticitySmoothMesh< ELEMENT >::Dummy_mesh_pt, i, oomph::Mesh::nnode(), and oomph::SolidMesh::node_pt().
Referenced by oomph::NonLinearElasticitySmoothMesh< ELEMENT >::operator()().
Member Data Documentation
Backup_node_pos
template<class ELEMENT >
Vector<Vector<double> > oomph::NonLinearElasticitySmoothMesh< ELEMENT >::Backup_node_pos [private]
Backup nodal positions.
Definition at line 489 of file mesh_smooth.h.
Referenced by oomph::NonLinearElasticitySmoothMesh< ELEMENT >::backup(), and oomph::NonLinearElasticitySmoothMesh< ELEMENT >::reset().
Dummy_mesh_pt
template<class ELEMENT >
SolidMesh* oomph::NonLinearElasticitySmoothMesh< ELEMENT >::Dummy_mesh_pt [private]
Copy of mesh to work on.
Definition at line 495 of file mesh_smooth.h.
Referenced by oomph::NonLinearElasticitySmoothMesh< ELEMENT >::backup(), oomph::NonLinearElasticitySmoothMesh< ELEMENT >::doc_solution(), oomph::NonLinearElasticitySmoothMesh< ELEMENT >::operator()(), and oomph::NonLinearElasticitySmoothMesh< ELEMENT >::reset().
Orig_mesh_pt
template<class ELEMENT >
SolidMesh* oomph::NonLinearElasticitySmoothMesh< ELEMENT >::Orig_mesh_pt [private]
Bulk original mesh.
Definition at line 492 of file mesh_smooth.h.
Referenced by oomph::NonLinearElasticitySmoothMesh< ELEMENT >::actions_before_newton_solve(), and oomph::NonLinearElasticitySmoothMesh< ELEMENT >::operator()().
Orig_node_pos
template<class ELEMENT >
Vector<Vector<double> > oomph::NonLinearElasticitySmoothMesh< ELEMENT >::Orig_node_pos [private]
Original nodal positions.
Definition at line 486 of file mesh_smooth.h.
Referenced by oomph::NonLinearElasticitySmoothMesh< ELEMENT >::actions_before_newton_solve(), and oomph::NonLinearElasticitySmoothMesh< ELEMENT >::operator()().
The documentation for this class was generated from the following file:
mesh_smooth.h