oomph::FSIAxisymmetricQTaylorHoodElement Class Reference
Axisymmetric FSI Element.
#include <axisym_navier_stokes_elements.h>
Public Member Functions
FSIAxisymmetricQTaylorHoodElement ()
Constructor.
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs containing.
void identify_pressure_data (std::set< std::pair< Data *, unsigned > > &paired_pressure_data)
Add to the set paired_load_data pairs containing.
void get_load (const Vector< double > &s, const Vector< double > &N, Vector< double > &load)
Compute the load vector that is applied by current element (at its local coordinate s) onto the adjacent SolidElement. N is the outer unit normal on the FSIFluidElement.
Additional Inherited Members
Detailed Description
Axisymmetric FSI Element.
Definition at line 2209 of file axisym_navier_stokes_elements.h.
Constructor & Destructor Documentation
FSIAxisymmetricQTaylorHoodElement()
oomph::FSIAxisymmetricQTaylorHoodElement::FSIAxisymmetricQTaylorHoodElement () [inline]
Constructor.
Definition at line 2215 of file axisym_navier_stokes_elements.h.
Member Function Documentation
get_load()
void oomph::FSIAxisymmetricQTaylorHoodElement::get_load (const Vector< double > & s, const Vector< double > & N, Vector< double > & load) [inline], [virtual]
Compute the load vector that is applied by current element (at its local coordinate s) onto the adjacent SolidElement. N is the outer unit normal on the FSIFluidElement.
Implements oomph::FSIFluidElement.
Definition at line 2282 of file axisym_navier_stokes_elements.h.
References oomph::AxisymmetricQTaylorHoodElement::get_traction(), oomph::QuadTreeNames::N, and s.
identify_load_data()
void oomph::FSIAxisymmetricQTaylorHoodElement::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data) [inline], [virtual]
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Implements oomph::FSIFluidElement.
Definition at line 2224 of file axisym_navier_stokes_elements.h.
References i, identify_pressure_data(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::AxisymmetricNavierStokesEquations::u_index_nst().
identify_pressure_data()
void oomph::FSIAxisymmetricQTaylorHoodElement::identify_pressure_data (std::set< std::pair< Data *, unsigned > > & paired_pressure_data) [inline], [virtual]
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Implements oomph::FSIFluidElement.
Definition at line 2261 of file axisym_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt(), oomph::AxisymmetricQTaylorHoodElement::npres_axi_nst(), oomph::AxisymmetricQTaylorHoodElement::p_nodal_index_axi_nst(), and oomph::AxisymmetricQTaylorHoodElement::Pconv.
Referenced by identify_load_data().
The documentation for this class was generated from the following file:
axisym_navier_stokes_elements.h