oomph::SolidInitialCondition Class Reference
A class to specify the initial conditions for a solid body. Solid bodies are often discretised with Hermite-type elements, for which the assignment of the generalised nodal values is nontrivial since they represent derivatives w.r.t. to the local coordinates. A SolidInitialCondition object specifies initial position (i.e. shape), velocity and acceleration of the structure with a geometric object. An integer specifies which time-derivative derivative is currently assigned. See example codes for a demonstration of its use.
#include <elements.h>
Public Member Functions
SolidInitialCondition (GeomObject *geom_object_pt)
Constructor: Pass geometric object; initialise time deriv to 0.
SolidInitialCondition (const SolidInitialCondition &)
Broken copy constructor.
void operator= (const SolidInitialCondition &)
Broken assignment operator.
GeomObject *& geom_object_pt ()
unsigned & ic_time_deriv ()
Which time derivative are we currently assigning?
Private Attributes
GeomObject * Geom_object_pt
Pointer to the GeomObject that specifies the initial condition (shape, veloc and accel)
unsigned IC_time_deriv
Which time derivative (0,1,2) are we currently assigning.
Detailed Description
A class to specify the initial conditions for a solid body. Solid bodies are often discretised with Hermite-type elements, for which the assignment of the generalised nodal values is nontrivial since they represent derivatives w.r.t. to the local coordinates. A SolidInitialCondition object specifies initial position (i.e. shape), velocity and acceleration of the structure with a geometric object. An integer specifies which time-derivative derivative is currently assigned. See example codes for a demonstration of its use.
Definition at line 3520 of file elements.h.
Constructor & Destructor Documentation
SolidInitialCondition() [1/2]
oomph::SolidInitialCondition::SolidInitialCondition (GeomObject * geom_object_pt) [inline]
Constructor: Pass geometric object; initialise time deriv to 0.
Definition at line 3524 of file elements.h.
SolidInitialCondition() [2/2]
oomph::SolidInitialCondition::SolidInitialCondition (const SolidInitialCondition &) [inline]
Broken copy constructor.
Definition at line 3529 of file elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
geom_object_pt()
GeomObject*& oomph::SolidInitialCondition::geom_object_pt () [inline]
(Reference to) pointer to geom object that specifies the initial condition
Definition at line 3543 of file elements.h.
References Geom_object_pt.
Referenced by oomph::SolidFiniteElement::fill_in_generic_jacobian_for_solid_ic(), oomph::SolidICProblem::set_newmark_initial_condition_consistently(), oomph::SolidICProblem::set_newmark_initial_condition_directly(), and oomph::SolidICProblem::set_static_initial_condition().
ic_time_deriv()
unsigned& oomph::SolidInitialCondition::ic_time_deriv () [inline]
Which time derivative are we currently assigning?
Definition at line 3549 of file elements.h.
References IC_time_deriv.
Referenced by oomph::SolidFiniteElement::fill_in_generic_jacobian_for_solid_ic(), oomph::SolidICProblem::set_newmark_initial_condition_consistently(), oomph::SolidICProblem::set_newmark_initial_condition_directly(), and oomph::SolidICProblem::set_static_initial_condition().
operator=()
void oomph::SolidInitialCondition::operator= (const SolidInitialCondition &) [inline]
Broken assignment operator.
Definition at line 3535 of file elements.h.
References oomph::BrokenCopy::broken_assign().
Member Data Documentation
Geom_object_pt
GeomObject* oomph::SolidInitialCondition::Geom_object_pt [private]
Pointer to the GeomObject that specifies the initial condition (shape, veloc and accel)
Definition at line 3558 of file elements.h.
Referenced by geom_object_pt().
IC_time_deriv
unsigned oomph::SolidInitialCondition::IC_time_deriv [private]
Which time derivative (0,1,2) are we currently assigning.
Definition at line 3561 of file elements.h.
Referenced by ic_time_deriv().
The documentation for this class was generated from the following file:
elements.h