oomph::FpPressureAdvDiffRobinBCElement< ELEMENT > Class Template Reference
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
#include <navier_stokes_elements.h>
Public Member Functions
FpPressureAdvDiffRobinBCElement (FiniteElement *const &element_pt, const int &face_index, const bool &called_from_refineable_constructor=false)
Constructor, which takes a `bulk` element and the value of the index and its limit. Optional boolean flag indicates if it's called.
~FpPressureAdvDiffRobinBCElement ()
Empty destructor.
virtual void fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
This function returns the residuals for the traction function. flag=1 (or 0): do (or don't) compute the Jacobian as well.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
This function returns just the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the jacobian.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: x,y,[z],u,v,[w],p in tecplot format.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::FpPressureAdvDiffRobinBCElement< ELEMENT >
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
A class for elements that allow the imposition of Robin boundary conditions for the pressure advection diffusion problem in the Fp preconditioner. The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class
Definition at line 85 of file navier_stokes_elements.h.
Constructor & Destructor Documentation
FpPressureAdvDiffRobinBCElement()
template<class ELEMENT >
oomph::FpPressureAdvDiffRobinBCElement< ELEMENT >::FpPressureAdvDiffRobinBCElement (FiniteElement *const & element_pt, const int & face_index, const bool & called_from_refineable_constructor = false) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit. Optional boolean flag indicates if it's called.
Definition at line 94 of file navier_stokes_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::FiniteElement::dim(), oomph::FaceElement::face_index(), and oomph::FiniteElement::has_hanging_nodes().
 FpPressureAdvDiffRobinBCElement()
template<class ELEMENT >
oomph::FpPressureAdvDiffRobinBCElement< ELEMENT >::~FpPressureAdvDiffRobinBCElement () [inline]
Empty destructor.
Definition at line 132 of file navier_stokes_elements.h.
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
This function returns the residuals and the jacobian.
Reimplemented from oomph::FiniteElement.
Definition at line 154 of file navier_stokes_elements.h.
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
This function returns just the residuals.
Reimplemented from oomph::GeneralisedElement.
Definition at line 142 of file navier_stokes_elements.h.
fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc()
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [virtual]
This function returns the residuals for the traction function. flag=1 (or 0): do (or don't) compute the Jacobian as well.
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Get residuals and Jacobian of Robin boundary conditions in pressure advection diffusion problem in Fp preconditoner Get outer unit normal
Implements oomph::FpPressureAdvDiffRobinBCElementBase.
Reimplemented in oomph::RefineableFpPressureAdvDiffRobinBCElement< ELEMENT >.
Definition at line 189 of file navier_stokes_elements.h.
References i, s, and oomph::QuadTreeNames::W.
output() [1/2]
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::FiniteElement.
Definition at line 167 of file navier_stokes_elements.h.
References oomph::FiniteElement::output().
output() [2/2]
template<class ELEMENT >
void oomph::FpPressureAdvDiffRobinBCElement< ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function: x,y,[z],u,v,[w],p in tecplot format.
Reimplemented from oomph::FiniteElement.
Definition at line 173 of file navier_stokes_elements.h.
References oomph::FiniteElement::output().
The documentation for this class was generated from the following file:
navier_stokes_elements.h