oomph::MGPreconditioner< DIM > Class Template Reference
An interface to allow scalar MG to be used as a Preconditioner.
#include <geometric_multigrid.h>
Public Member Functions
MGPreconditioner (MGProblem *mg_problem_pt)
Constructor.
~MGPreconditioner ()
Destructor (empty)
MGPreconditioner (const MGPreconditioner &)=delete
Broken copy constructor.
void operator= (const MGPreconditioner &)=delete
Broken assignment operator.
void setup ()
Function to set up a preconditioner for the linear system.
virtual void preconditioner_solve (const DoubleVector &rhs, DoubleVector &z)
Function applies MG to the vector r for a full solve.
void clean_up_memory ()
Clean up memory.
Public Member Functions inherited from oomph::MGSolver< DIM >
void set_pre_smoother_factory_function (PreSmootherFactoryFctPt pre_smoother_fn)
Access function to set the pre-smoother creation function.
void set_post_smoother_factory_function (PostSmootherFactoryFctPt post_smoother_fn)
Access function to set the post-smoother creation function.
MGSolver (MGProblem *mg_problem_pt)
Constructor: Set up default values for number of V-cycles and pre- and post-smoothing steps.
~MGSolver ()
Delete any dynamically allocated data.
void clean_up_memory ()
Clean up anything that needs to be cleaned up.
void set_self_test_vector ()
Makes a vector which will be used in the self-test. Is currently set to make the entries of the vector represent a plane wave propagating at an angle of 45 degrees.
void self_test ()
Makes a vector, restricts it down the levels of the hierarchy and documents it at each level. After this is done the vector is interpolated up the levels of the hierarchy with the output being documented at each level.
void restriction_self_test ()
Make a self-test to make sure that the interpolation matrices are doing the same thing to restrict the vectors down through the heirachy.
void interpolation_self_test ()
Make a self-test to make sure that the interpolation matrices are doing the same thing to interpolate the vectors up.
void plot (const unsigned &hierarchy_level, const DoubleVector &input_vector, const std::string &filename)
Given a level in the hierarchy, an input vector and a filename this function will document the given vector according to the structure of the mesh on the given level.
void disable_v_cycle_output ()
Disable all output from mg_solve apart from the number of V-cycles used to solve the problem.
void disable_output ()
Suppress anything that can be suppressed, i.e. any timings. Things like mesh adaptation can not however be silenced using this.
void enable_v_cycle_output ()
Enable the output of the V-cycle timings and other output.
void enable_doc_everything ()
Enable the output from anything that could have been suppressed.
void enable_output ()
Enable the output from anything that could have been suppressed.
void disable_smoother_and_superlu_doc_time ()
Suppress the output of both smoothers and SuperLU.
unsigned & npost_smooth ()
Return the number of post-smoothing iterations (lvalue)
unsigned & npre_smooth ()
Return the number of pre-smoothing iterations (lvalue)
void pre_smooth (const unsigned &level)
Pre-smoother: Perform 'max_iter' smoothing steps on the linear system Ax=b with current RHS vector, b, starting with current solution vector, x. Return the residual vector r=b-Ax. Uses the default smoother (set in the MGProblem constructor) which can be overloaded for a specific problem.
void post_smooth (const unsigned &level)
Post-smoother: Perform max_iter smoothing steps on the linear system Ax=b with current RHS vector, b, starting with current solution vector, x. Uses the default smoother (set in the MGProblem constructor) which can be overloaded for specific problem.
double residual_norm (const unsigned &level)
Return norm of residual r=b-Ax and the residual vector itself on the level-th level.
void direct_solve ()
Call the direct solver (SuperLU) to solve the problem exactly.
void interpolation_matrix_set (const unsigned &level, double *value, int *col_index, int *row_st, unsigned &ncol, unsigned &nnz)
Builds a CRDoubleMatrix that is used to interpolate the residual between levels. The transpose can be used as the full weighting restriction.
void interpolation_matrix_set (const unsigned &level, Vector< double > &value, Vector< int > &col_index, Vector< int > &row_st, unsigned &ncol, unsigned &nrow)
Builds a CRDoubleMatrix that is used to interpolate the residual between levels. The transpose can be used as the full weighting restriction.
void set_restriction_matrices_as_interpolation_transposes ()
Builds a CRDoubleMatrix on each level that is used to restrict the residual between levels. The transpose can be used as the interpolation matrix.
void restrict_residual (const unsigned &level)
Restrict residual (computed on level-th MG level) to the next coarser mesh and stick it into the coarse mesh RHS vector.
void interpolate_and_correct (const unsigned &level)
Interpolate solution at current level onto next finer mesh and correct the solution x at that level.
void level_up_local_coord_of_node (const int &son_type, Vector< double > &s)
Given the son_type of an element and a local node number j in that element with nnode_1d nodes per coordinate direction, return the local coordinate s in its father element. Needed in the setup of the interpolation matrices.
void setup_interpolation_matrices ()
Setup the interpolation matrix on each level.
void setup_interpolation_matrices_unstructured ()
Setup the interpolation matrix on each level (used for unstructured meshes)
void setup_transfer_matrices ()
Setup the transfer matrices on each level.
void full_setup ()
Do a full setup (assumes everything will be setup around the MGProblem pointer given in the constructor)
void solve (Problem *const &problem_pt, DoubleVector &result)
Virtual function in the base class that needs to be implemented later but for now just leave it empty.
unsigned iterations () const
Number of iterations.
unsigned & max_iter ()
Number of iterations.
void level_up_local_coord_of_node (const int &son_type, Vector< double > &s)
Given the son type of the element and the local coordinate s of a given node in the son element, return the local coordinate s in its father element. 2D case.
void level_up_local_coord_of_node (const int &son_type, Vector< double > &s)
Given the son type of the element and the local coordinate s of a given node in the son element, return the local coordinate s in its father element. 3D case.
Public Member Functions inherited from oomph::IterativeLinearSolver
IterativeLinearSolver ()
Constructor: Set (default) trivial preconditioner and set defaults for tolerance and max. number of iterations.
IterativeLinearSolver (const IterativeLinearSolver &)=delete
Broken copy constructor.
void operator= (const IterativeLinearSolver &)=delete
Broken assignment operator.
virtual ~IterativeLinearSolver ()
Destructor (empty)
Preconditioner *& preconditioner_pt ()
Access function to preconditioner.
Preconditioner *const & preconditioner_pt () const
Access function to preconditioner (const version)
double & tolerance ()
Access to convergence tolerance.
unsigned & max_iter ()
Access to max. number of iterations.
void enable_doc_convergence_history ()
Enable documentation of the convergence history.
void disable_doc_convergence_history ()
Disable documentation of the convergence history.
void open_convergence_history_file_stream (const std::string &file_name, const std::string &zone_title="")
Write convergence history into file with specified filename (automatically switches on doc). Optional second argument is a string that can be used (as a zone title) to identify what case we're running (e.g. what combination of linear solver and preconditioner or parameter values are used).
void close_convergence_history_file_stream ()
Close convergence history output stream.
double jacobian_setup_time () const
returns the time taken to assemble the jacobian matrix and residual vector
double linear_solver_solution_time () const
return the time taken to solve the linear system
virtual double preconditioner_setup_time () const
returns the the time taken to setup the preconditioner
void enable_setup_preconditioner_before_solve ()
Setup the preconditioner before the solve.
void disable_setup_preconditioner_before_solve ()
Don't set up the preconditioner before the solve.
void enable_error_after_max_iter ()
Throw an error if we don't converge within max_iter.
void disable_error_after_max_iter ()
Don't throw an error if we don't converge within max_iter (default).
void enable_iterative_solver_as_preconditioner ()
Enables the iterative solver be used as preconditioner (when calling the solve method it bypass the setup solver method -- currently only used by Trilinos solver ---)
void disable_iterative_solver_as_preconditioner ()
Disables the iterative solver be used as preconditioner (when calling the solve method it bypass the setup solver method -- currently only used by Trilinos solver ---)
Public Member Functions inherited from oomph::LinearSolver
LinearSolver ()
Empty constructor, initialise the member data.
LinearSolver (const LinearSolver &dummy)=delete
Broken copy constructor.
void operator= (const LinearSolver &)=delete
Broken assignment operator.
virtual ~LinearSolver ()
Empty virtual destructor.
void enable_doc_time ()
Enable documentation of solve times.
void disable_doc_time ()
Disable documentation of solve times.
bool is_doc_time_enabled () const
Is documentation of solve times enabled?
bool is_resolve_enabled () const
Boolean flag indicating if resolves are enabled.
virtual void enable_resolve ()
Enable resolve (i.e. store matrix and/or LU decomposition, say) Virtual so it can be overloaded to perform additional tasks.
virtual void disable_resolve ()
Disable resolve (i.e. store matrix and/or LU decomposition, say) This function simply resets an internal flag. It's virtual so it can be overloaded to perform additional tasks such as cleaning up memory that is only required for the resolve.
virtual void solve (DoubleMatrixBase *const &matrix_pt, const DoubleVector &rhs, DoubleVector &result)
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
virtual void solve (DoubleMatrixBase *const &matrix_pt, const Vector< double > &rhs, Vector< double > &result)
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
virtual void solve_transpose (Problem *const &problem_pt, DoubleVector &result)
Solver: Takes pointer to problem and returns the results vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual vector (broken virtual).
virtual void solve_transpose (DoubleMatrixBase *const &matrix_pt, const DoubleVector &rhs, DoubleVector &result)
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
virtual void solve_transpose (DoubleMatrixBase *const &matrix_pt, const Vector< double > &rhs, Vector< double > &result)
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
virtual void resolve (const DoubleVector &rhs, DoubleVector &result)
Resolve the system defined by the last assembled jacobian and the rhs vector. Solution is returned in the vector result. (broken virtual)
virtual void resolve_transpose (const DoubleVector &rhs, DoubleVector &result)
Solver: Resolve the system defined by the last assembled jacobian and the rhs vector. Solution is returned in the vector result. (broken virtual)
virtual void enable_computation_of_gradient ()
function to enable the computation of the gradient required for the globally convergent Newton method
void disable_computation_of_gradient ()
function to disable the computation of the gradient required for the globally convergent Newton method
void reset_gradient ()
function to reset the size of the gradient before each Newton solve
void get_gradient (DoubleVector &gradient)
function to access the gradient, provided it has been computed
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
if the communicator_pt is null then the distribution is not setup then false is returned, otherwise return true
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
setup the distribution of this distributable linear algebra object
void build_distribution (const LinearAlgebraDistribution &dist)
setup the distribution of this distributable linear algebra object
Public Member Functions inherited from oomph::Preconditioner
Preconditioner ()
Constructor.
Preconditioner (const Preconditioner &)=delete
Broken copy constructor.
void operator= (const Preconditioner &)=delete
Broken assignment operator.
virtual ~Preconditioner ()
Destructor (empty)
virtual void preconditioner_solve_transpose (const DoubleVector &r, DoubleVector &z)
Apply the preconditioner. Pure virtual generic interface function. This method should apply the preconditioner operator to the vector r and return the vector z. (broken virtual)
virtual void setup (DoubleMatrixBase *matrix_pt)
Setup the preconditioner: store the matrix pointer and the communicator pointer then call preconditioner specific setup() function.
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
Compatability layer for old preconditioners where problem pointers were needed. The problem pointer is only used to get a communicator pointer.
void enable_silent_preconditioner_setup ()
Set up the block preconditioner quietly!
void disable_silent_preconditioner_setup ()
Be verbose in the block preconditioner setup.
virtual DoubleMatrixBase * matrix_pt () const
Get function for matrix pointer.
virtual void set_matrix_pt (DoubleMatrixBase *matrix_pt)
Set the matrix pointer.
virtual const OomphCommunicator * comm_pt () const
Get function for comm pointer.
virtual void set_comm_pt (const OomphCommunicator *const comm_pt)
Set the communicator pointer.
double setup_time () const
Returns the time to setup the preconditioner.
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
Virtual interface function for making a preconditioner a subsidiary of a block preconditioner. By default nothing is needed, but if this preconditioner is also a block preconditioner then things need to happen. There's an assumption here that the block preconditioner will be in CR form but since that assumption is hard coded all over BlockPreconditioner we're safe.
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned > > &doftype_coarsen_map_coarse)
Virtual interface function for making a preconditioner a subsidiary of a block preconditioner. By default nothing is needed, but if this preconditioner is also a block preconditioner then things need to happen. Version for coarsening dof-types.
Additional Inherited Members
Public Types inherited from oomph::MGSolver< DIM >
typedef Smoother *(* PreSmootherFactoryFctPt) ()
typedef for a function that returns a pointer to an object of the class Smoother to be used as the pre-smoother
typedef Smoother *(* PostSmootherFactoryFctPt) ()
typedef for a function that returns a pointer to an object of the class Smoother to be used as the post-smoother
Protected Member Functions inherited from oomph::MGSolver< DIM >
void mg_solve (DoubleVector &result)
Do the actual solve -- this is called through the pure virtual solve function in the LinearSolver base class. The function is stored as protected to allow the MGPreconditioner derived class to use the solver.
void modify_restriction_matrices ()
Normalise the rows of the restriction matrices to avoid amplifications when projecting to the coarser level.
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
clear the distribution of this distributable linear algebra object
Protected Attributes inherited from oomph::MGSolver< DIM >
unsigned Nvcycle
Maximum number of V-cycles (this is set as a protected variable so.
MGProblem * Mg_problem_pt
Pointer to the MG problem (deep copy). This is protected to provide access to the MG preconditioner.
Vector< DoubleVector > Rhs_mg_vectors_storage
Vector to store the RHS vectors (Rhs_mg). This is protected to allow the multigrid preconditioner to assign the RHS vector during preconditioner_solve()
bool Suppress_v_cycle_output
Indicates whether or not the V-cycle output should be suppressed. Needs to be protected member data for the multigrid preconditioner to know whether or not to output information with each preconditioning step.
bool Suppress_all_output
If this is set to true then all output from the solver is suppressed. This is protected member data so that the multigrid preconditioner knows whether or not to restore the stream pointer.
std::ostream * Stream_pt
Pointer to the output stream -- defaults to std::cout. This is protected member data to allow the preconditioner to restore normal output if everything was chosen to be suppressed by the user.
Protected Attributes inherited from oomph::IterativeLinearSolver
bool Doc_convergence_history
Flag indicating if the convergence history is to be documented.
std::ofstream Output_file_stream
Output file stream for convergence history.
double Tolerance
Convergence tolerance.
unsigned Max_iter
Maximum number of iterations.
Preconditioner * Preconditioner_pt
Pointer to the preconditioner.
double Jacobian_setup_time
Jacobian setup time.
double Solution_time
linear solver solution time
double Preconditioner_setup_time
Preconditioner setup time.
bool Setup_preconditioner_before_solve
indicates whether the preconditioner should be setup before solve. Default = true;
bool Throw_error_after_max_iter
Should we throw an error instead of just returning when we hit the max iterations?
bool Use_iterative_solver_as_preconditioner
Use the iterative solver as preconditioner.
bool First_time_solve_when_used_as_preconditioner
When the iterative solver is used a preconditioner then we call the setup of solver method only once (the first time the solve method is called)
Protected Attributes inherited from oomph::LinearSolver
bool Enable_resolve
Boolean that indicates whether the matrix (or its factors, in the case of direct solver) should be stored so that the resolve function can be used.
bool Doc_time
Boolean flag that indicates whether the time taken.
bool Compute_gradient
flag that indicates whether the gradient required for the globally convergent Newton method should be computed or not
bool Gradient_has_been_computed
flag that indicates whether the gradient was computed or not
DoubleVector Gradient_for_glob_conv_newton_solve
DoubleVector storing the gradient for the globally convergent Newton method.
Protected Attributes inherited from oomph::Preconditioner
bool Silent_preconditioner_setup
Boolean to indicate whether or not the build should be done silently.
std::ostream * Stream_pt
Pointer to the output stream -- defaults to std::cout.
Static Protected Attributes inherited from oomph::IterativeLinearSolver
static IdentityPreconditioner Default_preconditioner
Default preconditioner: The base class for preconditioners is a fully functional (if trivial!) preconditioner.
Detailed Description
template<unsigned DIM>
class oomph::MGPreconditioner< DIM >
An interface to allow scalar MG to be used as a Preconditioner.
Definition at line 732 of file geometric_multigrid.h.
Constructor & Destructor Documentation
MGPreconditioner() [1/2]
template<unsigned DIM>
oomph::MGPreconditioner< DIM >::MGPreconditioner (MGProblem * mg_problem_pt) [inline]
Constructor.
Definition at line 736 of file geometric_multigrid.h.
References oomph::MGSolver< DIM >::Nvcycle.
~MGPreconditioner()
template<unsigned DIM>
oomph::MGPreconditioner< DIM >::~MGPreconditioner () [inline]
Destructor (empty)
Definition at line 743 of file geometric_multigrid.h.
MGPreconditioner() [2/2]
template<unsigned DIM>
oomph::MGPreconditioner< DIM >::MGPreconditioner (const MGPreconditioner< DIM > &) [delete]
Broken copy constructor.
Member Function Documentation
clean_up_memory()
template<unsigned DIM>
void oomph::MGPreconditioner< DIM >::clean_up_memory () [inline], [virtual]
Clean up memory.
Reimplemented from oomph::LinearSolver.
Definition at line 816 of file geometric_multigrid.h.
operator=()
template<unsigned DIM>
void oomph::MGPreconditioner< DIM >::operator= (const MGPreconditioner< DIM > &) [delete]
Broken assignment operator.
preconditioner_solve()
template<unsigned DIM>
virtual void oomph::MGPreconditioner< DIM >::preconditioner_solve (const DoubleVector & rhs, DoubleVector & z) [inline], [virtual]
Function applies MG to the vector r for a full solve.
Implements oomph::Preconditioner.
Definition at line 779 of file geometric_multigrid.h.
References oomph::MGSolver< DIM >::Mg_problem_pt, oomph::MGSolver< DIM >::mg_solve(), oomph::Problem::ndof(), oomph::DistributableLinearAlgebraObject::nrow(), oomph::oomph_info, oomph::MGSolver< DIM >::Rhs_mg_vectors_storage, oomph::MGSolver< DIM >::Stream_pt, oomph::OomphInfo::stream_pt(), oomph::MGSolver< DIM >::Suppress_all_output, and oomph::MGSolver< DIM >::Suppress_v_cycle_output.
setup()
template<unsigned DIM>
void oomph::MGPreconditioner< DIM >::setup () [inline], [virtual]
Function to set up a preconditioner for the linear system.
Implements oomph::Preconditioner.
Definition at line 752 of file geometric_multigrid.h.
References oomph::MPI_Helpers::communicator_pt(), oomph::MGSolver< DIM >::full_setup(), oomph::oomph_info, oomph::MGSolver< DIM >::Stream_pt, oomph::OomphInfo::stream_pt(), and oomph::MGSolver< DIM >::Suppress_all_output.
The documentation for this class was generated from the following file:
geometric_multigrid.h