oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D > Class Template Reference
#include <Tadvection_diffusion_reaction_elements.h>
Public Member Functions
TAdvectionDiffusionReactionElement ()
Constructor: Call constructors for TElement and AdvectionDiffusionReaction equations.
TAdvectionDiffusionReactionElement (const TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D > &dummy)
Broken copy constructor.
void operator= (const TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D > &)
Broken assignment operator.
unsigned required_nvalue (const unsigned &n) const
Access function for Nvalue: # of `values' (pinned or dofs) at node n (always returns the same value at every node, 1)
void output (std::ostream &outfile)
Output function: x,y,u or x,y,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output (FILE *file_pt)
C-style output function: x,y,u or x,y,z,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: x,y,u_exact.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. x,y,u_exact (calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_adv_diff_react (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_adv_diff_react (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_adv_diff_react (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
Additional Inherited Members
Detailed Description
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
class oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >
TAdvectionDiffusionReactionElement<NREAGENT,DIM,NNODE_1D> elements are isoparametric triangular DIM-dimensional AdvectionDiffusionReaction elements with NNODE_1D nodal points along each element edge. Inherits from TElement and AdvectionDiffusionReactionEquations
Definition at line 62 of file Tadvection_diffusion_reaction_elements.h.
Constructor & Destructor Documentation
TAdvectionDiffusionReactionElement() [1/2]
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement () [inline]
Constructor: Call constructors for TElement and AdvectionDiffusionReaction equations.
Definition at line 70 of file Tadvection_diffusion_reaction_elements.h.
TAdvectionDiffusionReactionElement() [2/2]
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement (const TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 78 of file Tadvection_diffusion_reaction_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dshape_and_dtest_eulerian_adv_diff_react()
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
double oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::dshape_and_dtest_eulerian_adv_diff_react (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
Definition at line 231 of file Tadvection_diffusion_reaction_elements.h.
References i, and s.
dshape_and_dtest_eulerian_at_knot_adv_diff_react() [1/2]
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
double oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_adv_diff_react (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Definition at line 292 of file Tadvection_diffusion_reaction_elements.h.
dshape_and_dtest_eulerian_at_knot_adv_diff_react() [2/2]
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
double oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_adv_diff_react (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Implements oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
Definition at line 264 of file Tadvection_diffusion_reaction_elements.h.
get_Z2_flux()
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
void oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [protected], [virtual]
Get 'flux' for Z2 error recovery: Standard flux.from AdvectionDiffusionReaction equations
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 201 of file Tadvection_diffusion_reaction_elements.h.
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_flux().
nrecovery_order()
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
unsigned oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::nrecovery_order () [inline], [protected], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 188 of file Tadvection_diffusion_reaction_elements.h.
num_Z2_flux_terms()
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
unsigned oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::num_Z2_flux_terms () [inline], [protected], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 194 of file Tadvection_diffusion_reaction_elements.h.
nvertex_node()
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
unsigned oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::nvertex_node () const [inline], [protected], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 207 of file Tadvection_diffusion_reaction_elements.h.
operator=()
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
void oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::operator= (const TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D > &) [inline]
Broken assignment operator.
Definition at line 85 of file Tadvection_diffusion_reaction_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
void oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function: x,y,u or x,y,z,u.
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
Definition at line 116 of file Tadvection_diffusion_reaction_elements.h.
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::output().
output() [2/4]
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
void oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
Definition at line 124 of file Tadvection_diffusion_reaction_elements.h.
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::output().
output() [3/4]
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
void oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: x,y,u or x,y,z,u.
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
Definition at line 100 of file Tadvection_diffusion_reaction_elements.h.
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::output().
output() [4/4]
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
void oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
Definition at line 107 of file Tadvection_diffusion_reaction_elements.h.
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::output().
output_fct() [1/2]
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
void oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. x,y,u_exact (calls the steady version)
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
Definition at line 144 of file Tadvection_diffusion_reaction_elements.h.
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::output_fct().
output_fct() [2/2]
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
void oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: x,y,u_exact.
Reimplemented from oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.
Definition at line 133 of file Tadvection_diffusion_reaction_elements.h.
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::output_fct().
required_nvalue()
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
unsigned oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Access function for Nvalue: # of `values' (pinned or dofs) at node n (always returns the same value at every node, 1)
Reimplemented from oomph::FiniteElement.
Definition at line 93 of file Tadvection_diffusion_reaction_elements.h.
vertex_node_pt()
template<unsigned NREAGENT, unsigned DIM, unsigned NNODE_1D>
Node* oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [protected], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 213 of file Tadvection_diffusion_reaction_elements.h.
The documentation for this class was generated from the following file:
Tadvection_diffusion_reaction_elements.h