oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D > Class Template Reference
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
#include <space_time_unsteady_heat_elements.h>
Public Member Functions
QUnsteadyHeatSpaceTimeElement ()
Constructor: Call constructors for QElement and SpaceTimeUnsteadyHeat equations.
QUnsteadyHeatSpaceTimeElement (const QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D > &dummy)=delete
Broken copy constructor.
unsigned required_nvalue (const unsigned &n) const
Required number of 'values' (pinned or dofs) at node n.
void output (std::ostream &outfile)
Output function: x,t,u or x,y,t,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,t,u or x,y,t,u at n_plot^(SPATIAL_DIM+1) plot points.
void output (FILE *file_pt)
C-style output function: x,t,u or x,y,t,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,t,u or x,y,t,u at n_plot^(SPATIAL_DIM+1) plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: x,t,u_exact or x,y,t,u_exact at n_plot^(SPATIAL_DIM+1) plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. x,t,u_exact or x,y,t,u_exact at n_plot^(SPATIAL_DIM+1) plot points (Calls the unsteady version)
QUnsteadyHeatSpaceTimeElement ()
Constructor: Call constructors for QElement and SpaceTimeUnsteadyHeat equations.
QUnsteadyHeatSpaceTimeElement (const QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D > &dummy)=delete
Broken copy constructor.
unsigned required_nvalue (const unsigned &n) const
Required number of 'values' (pinned or dofs) at node n.
void output (std::ostream &outfile)
Output function: x,t,u or x,y,t,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,t,u or x,y,t,u at n_plot^(SPATIAL_DIM+1) plot points.
void output (FILE *file_pt)
C-style output function: x,t,u or x,y,t,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,t,u or x,y,t,u at n_plot^(SPATIAL_DIM+1) plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: x,t,u_exact or x,y,t,u_exact at n_plot^(SPATIAL_DIM+1) plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. x,t,u_exact or x,y,t,u_exact at n_plot^(SPATIAL_DIM+1) plot points (Calls the unsteady version)
double dshape_and_dtest_eulerian_ust_heat (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape/test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_ust_heat (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Protected Member Functions
double dshape_and_dtest_eulerian_ust_heat (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape/test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_ust_heat (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Static Private Attributes
static const unsigned Initial_Nvalue = 1
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Additional Inherited Members
Detailed Description
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
class oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
QUnsteadyHeatSpaceTimeElement elements are quadrilateral/brick- shaped UnsteadyHeat elements with isoparametric interpolation for the function.
Definition at line 702 of file space_time_unsteady_heat_elements.h.
Constructor & Destructor Documentation
QUnsteadyHeatSpaceTimeElement() [1/4]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::QUnsteadyHeatSpaceTimeElement () [inline]
Constructor: Call constructors for QElement and SpaceTimeUnsteadyHeat equations.
Definition at line 709 of file space_time_unsteady_heat_elements.h.
QUnsteadyHeatSpaceTimeElement() [2/4]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::QUnsteadyHeatSpaceTimeElement (const QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D > & dummy) [delete]
Broken copy constructor.
QUnsteadyHeatSpaceTimeElement() [3/4]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::QUnsteadyHeatSpaceTimeElement () [inline]
Constructor: Call constructors for QElement and SpaceTimeUnsteadyHeat equations.
Definition at line 708 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
QUnsteadyHeatSpaceTimeElement() [4/4]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::QUnsteadyHeatSpaceTimeElement (const QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_ust_heat() [1/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
double oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_ust_heat (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions=shape functions
Implements oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.
Definition at line 849 of file space_time_unsteady_heat_elements.h.
References i, and s.
dshape_and_dtest_eulerian_at_knot_ust_heat() [2/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
double oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_ust_heat (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implements oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.
dshape_and_dtest_eulerian_ust_heat() [1/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
double oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::dshape_and_dtest_eulerian_ust_heat (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Shape/test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions=shape functions
Implements oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.
Definition at line 821 of file space_time_unsteady_heat_elements.h.
References s.
dshape_and_dtest_eulerian_ust_heat() [2/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
double oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::dshape_and_dtest_eulerian_ust_heat (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [virtual]
Shape/test functions & derivs. w.r.t. to global coords. Return Jacobian.
Implements oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.
output() [1/8]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
void oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function: x,t,u or x,y,t,u.
Reimplemented from oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.
Definition at line 748 of file space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output().
output() [2/8]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
void oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function: x,t,u or x,y,t,u.
Reimplemented from oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.
Definition at line 747 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output().
output() [3/8]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
void oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: x,t,u or x,y,t,u at n_plot^(SPATIAL_DIM+1) plot points.
Reimplemented from oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.
Definition at line 757 of file space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output().
output() [4/8]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
void oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: x,t,u or x,y,t,u at n_plot^(SPATIAL_DIM+1) plot points.
Reimplemented from oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.
Definition at line 756 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output().
output() [5/8]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
void oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: x,t,u or x,y,t,u.
Reimplemented from oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.
Definition at line 730 of file space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output().
output() [6/8]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
void oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Output function: x,t,u or x,y,t,u.
Reimplemented from oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.
Definition at line 729 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output().
output() [7/8]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
void oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: x,t,u or x,y,t,u at n_plot^(SPATIAL_DIM+1) plot points.
Reimplemented from oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.
Definition at line 739 of file space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output().
output() [8/8]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
void oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: x,t,u or x,y,t,u at n_plot^(SPATIAL_DIM+1) plot points.
Reimplemented from oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.
Definition at line 738 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output().
output_fct() [1/4]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
void oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. x,t,u_exact or x,y,t,u_exact at n_plot^(SPATIAL_DIM+1) plot points (Calls the unsteady version)
Reimplemented from oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.
Definition at line 779 of file space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output_fct().
output_fct() [2/4]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
void oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for a time-dependent exact solution. x,t,u_exact or x,y,t,u_exact at n_plot^(SPATIAL_DIM+1) plot points (Calls the unsteady version)
Reimplemented from oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.
Definition at line 778 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output_fct().
output_fct() [3/4]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
void oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: x,t,u_exact or x,y,t,u_exact at n_plot^(SPATIAL_DIM+1) plot points.
Reimplemented from oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.
Definition at line 766 of file space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output_fct().
output_fct() [4/4]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
void oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output function for an exact solution: x,t,u_exact or x,y,t,u_exact at n_plot^(SPATIAL_DIM+1) plot points.
Reimplemented from oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.
Definition at line 765 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output_fct().
required_nvalue() [1/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
unsigned oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Required number of 'values' (pinned or dofs) at node n.
Reimplemented from oomph::FiniteElement.
Definition at line 721 of file space_time_unsteady_heat_elements.h.
References oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::Initial_Nvalue.
required_nvalue() [2/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
unsigned oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::required_nvalue (const unsigned & n) const [inline], [virtual]
Required number of 'values' (pinned or dofs) at node n.
Reimplemented from oomph::FiniteElement.
Definition at line 720 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::Initial_Nvalue.
Member Data Documentation
Initial_Nvalue
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
static const unsigned oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::Initial_Nvalue = 1 [static], [private]
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Definition at line 810 of file space_time_unsteady_heat_elements.h.
Referenced by oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::required_nvalue().
The documentation for this class was generated from the following files:
space_time_unsteady_heat_elements.h
discontinuous_galerkin_space_time_unsteady_heat_elements.h
space_time_unsteady_heat_elements.cc
discontinuous_galerkin_space_time_unsteady_heat_elements.cc