oomph::PeriodicOrbitEquations Class Reference
#include <periodic_orbit_handler.h>
Public Member Functions
PeriodicOrbitEquations ()
PeriodicOrbitEquations (const PeriodicOrbitEquations &dummy)
Broken copy constructor.
double *& omega_pt ()
Broken assignment operator.
double omega ()
Return the frequency.
void set_ntstorage (const unsigned &n_tstorage)
Set the total number of time storage values.
Time *& time_pt ()
Retun the pointer to the global time.
Time *const & time_pt () const
Return the pointer to the global time (const version)
double time () const
Return the global time, accessed via the time pointer.
void fill_in_contribution_to_integrated_residuals (PeriodicOrbitAssemblyHandlerBase *const &assembly_handler_pt, GeneralisedElement *const &elem_pt, Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_integrated_jacobian (PeriodicOrbitAssemblyHandlerBase *const &assembly_handler_pt, GeneralisedElement *const &elem_pt, Vector< double > &residuals, DenseMatrix< double > &jacobian)
void orbit_output (GeneralisedElement *const &elem_pt, std::ostream &outfile, const unsigned &n_plot)
Protected Member Functions
void fill_in_generic_residual_contribution_orbit (PeriodicOrbitAssemblyHandlerBase *const &assembly_handler_pt, GeneralisedElement *const &elem_pt, Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
The routine that actually does all the work!
void set_timestepper_weights (const Shape &psi, const DShape &dpsidt)
Set the timestepper weights.
virtual double dshape_and_dtest_eulerian_orbit (const Vector< double > &s, Shape &psi, DShape &dpsidt, Shape &test, DShape &dtestdt) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_orbit (const unsigned &ipt, Shape &psi, DShape &dpsidt, Shape &test, DShape &dtestdt) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Private Attributes
unsigned Ntstorage
double * Omega_pt
Time * Time_pt
Pointer to global time.
Additional Inherited Members
Detailed Description
Definition at line 174 of file periodic_orbit_handler.h.
Constructor & Destructor Documentation
PeriodicOrbitEquations() [1/2]
oomph::PeriodicOrbitEquations::PeriodicOrbitEquations () [inline]
Definition at line 187 of file periodic_orbit_handler.h.
PeriodicOrbitEquations() [2/2]
oomph::PeriodicOrbitEquations::PeriodicOrbitEquations (const PeriodicOrbitEquations & dummy) [inline]
Broken copy constructor.
Definition at line 190 of file periodic_orbit_handler.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_orbit()
virtual double oomph::PeriodicOrbitEquations::dshape_and_dtest_eulerian_at_knot_orbit (const unsigned & ipt, Shape & psi, DShape & dpsidt, Shape & test, DShape & dtestdt) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::SpectralPeriodicOrbitElement< NNODE_1D >.
Referenced by fill_in_generic_residual_contribution_orbit().
dshape_and_dtest_eulerian_orbit()
virtual double oomph::PeriodicOrbitEquations::dshape_and_dtest_eulerian_orbit (const Vector< double > & s, Shape & psi, DShape & dpsidt, Shape & test, DShape & dtestdt) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in oomph::SpectralPeriodicOrbitElement< NNODE_1D >.
fill_in_contribution_to_integrated_jacobian()
void oomph::PeriodicOrbitEquations::fill_in_contribution_to_integrated_jacobian (PeriodicOrbitAssemblyHandlerBase *const & assembly_handler_pt, GeneralisedElement *const & elem_pt, Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline]
Add the element's contribution to its residual vector and element Jacobian matrix (wrapper)
Definition at line 268 of file periodic_orbit_handler.h.
References fill_in_generic_residual_contribution_orbit(), and residuals().
fill_in_contribution_to_integrated_residuals()
void oomph::PeriodicOrbitEquations::fill_in_contribution_to_integrated_residuals (PeriodicOrbitAssemblyHandlerBase *const & assembly_handler_pt, GeneralisedElement *const & elem_pt, Vector< double > & residuals) [inline]
Add the element's contribution to its residual vector (wrapper)
Definition at line 251 of file periodic_orbit_handler.h.
References oomph::GeneralisedElement::Dummy_matrix, fill_in_generic_residual_contribution_orbit(), and residuals().
fill_in_generic_residual_contribution_orbit()
void oomph::PeriodicOrbitEquations::fill_in_generic_residual_contribution_orbit (PeriodicOrbitAssemblyHandlerBase *const & assembly_handler_pt, GeneralisedElement *const & elem_pt, Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected]
The routine that actually does all the work!
Definition at line 77 of file periodic_orbit_handler.cc.
References dshape_and_dtest_eulerian_at_knot_orbit(), oomph::GeneralisedElement::eqn_number(), oomph::PeriodicOrbitAssemblyHandlerBase::get_dofs_for_element(), oomph::PeriodicOrbitBaseElement::get_inner_product_matrix(), oomph::GeneralisedElement::get_jacobian_and_mass_matrix(), oomph::PeriodicOrbitBaseElement::get_non_external_ddofs_dt(), oomph::PeriodicOrbitBaseElement::get_non_external_dofs(), oomph::PeriodicOrbitAssemblyHandlerBase::get_previous_dofs_for_element(), oomph::GeneralisedElement::get_residuals(), i, oomph::FiniteElement::integral_pt(), oomph::GeneralisedElement::ndof(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), Ntstorage, oomph::Integral::nweight(), omega(), oomph::FiniteElement::raw_nodal_position(), residuals(), oomph::DenseMatrix< T >::resize(), oomph::PeriodicOrbitAssemblyHandlerBase::set_dofs_for_element(), set_timestepper_weights(), oomph::Time::time(), time_pt(), u(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by fill_in_contribution_to_integrated_jacobian(), and fill_in_contribution_to_integrated_residuals().
omega()
double oomph::PeriodicOrbitEquations::omega () [inline]
Return the frequency.
Definition at line 213 of file periodic_orbit_handler.h.
References Omega_pt.
Referenced by fill_in_generic_residual_contribution_orbit(), orbit_output(), and set_timestepper_weights().
omega_pt()
double*& oomph::PeriodicOrbitEquations::omega_pt () [inline]
Broken assignment operator.
Set the pointer to the frequency
Definition at line 207 of file periodic_orbit_handler.h.
References Omega_pt.
Referenced by oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >::adapt_temporal_mesh(), and oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >::PeriodicOrbitAssemblyHandler().
orbit_output()
void oomph::PeriodicOrbitEquations::orbit_output (GeneralisedElement *const & elem_pt, std::ostream & outfile, const unsigned & n_plot)
Definition at line 30 of file periodic_orbit_handler.cc.
References oomph::FiniteElement::dshape_eulerian(), i, oomph::FiniteElement::nnode(), omega(), oomph::FiniteElement::raw_nodal_position(), s, set_timestepper_weights(), oomph::PeriodicOrbitBaseElement::spacetime_output(), oomph::Time::time(), and time_pt().
set_ntstorage()
void oomph::PeriodicOrbitEquations::set_ntstorage (const unsigned & n_tstorage) [inline]
Set the total number of time storage values.
Definition at line 219 of file periodic_orbit_handler.h.
References Ntstorage.
Referenced by oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >::adapt_temporal_mesh(), and oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >::PeriodicOrbitAssemblyHandler().
set_timestepper_weights()
void oomph::PeriodicOrbitEquations::set_timestepper_weights (const Shape & psi, const DShape & dpsidt) [inline], [protected]
Set the timestepper weights.
Definition at line 295 of file periodic_orbit_handler.h.
References oomph::GeneralisedElement::eqn_number(), i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::TimeStepper::ntstorage(), omega(), oomph::GeomObject::time_stepper_pt(), and oomph::TimeStepper::Weight.
Referenced by fill_in_generic_residual_contribution_orbit(), and orbit_output().
time()
double oomph::PeriodicOrbitEquations::time () const [inline]
Return the global time, accessed via the time pointer.
Definition at line 237 of file periodic_orbit_handler.h.
References oomph::Time::time(), and Time_pt.
time_pt() [1/2]
Time*& oomph::PeriodicOrbitEquations::time_pt () [inline]
Retun the pointer to the global time.
Definition at line 225 of file periodic_orbit_handler.h.
References Time_pt.
Referenced by oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >::adapt_temporal_mesh(), fill_in_generic_residual_contribution_orbit(), orbit_output(), and oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >::PeriodicOrbitAssemblyHandler().
time_pt() [2/2]
Time* const& oomph::PeriodicOrbitEquations::time_pt () const [inline]
Return the pointer to the global time (const version)
Definition at line 231 of file periodic_orbit_handler.h.
References Time_pt.
Member Data Documentation
Ntstorage
unsigned oomph::PeriodicOrbitEquations::Ntstorage [private]
Definition at line 177 of file periodic_orbit_handler.h.
Referenced by fill_in_generic_residual_contribution_orbit(), and set_ntstorage().
Omega_pt
double* oomph::PeriodicOrbitEquations::Omega_pt [private]
Definition at line 180 of file periodic_orbit_handler.h.
Referenced by omega(), and omega_pt().
Time_pt
Time* oomph::PeriodicOrbitEquations::Time_pt [private]
Pointer to global time.
Definition at line 183 of file periodic_orbit_handler.h.
Referenced by time(), and time_pt().
The documentation for this class was generated from the following files:
periodic_orbit_handler.h
periodic_orbit_handler.cc