oomph::AdvectionDiffusionFluxElement< ELEMENT > Class Template Reference
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
#include <advection_diffusion_flux_elements.h>
Public Types
typedef void(* AdvectionDiffusionPrescribedFluxFctPt) (const Vector< double > &x, double &flux)
Function pointer to the prescribed-flux function fct(x,f(x)) -- x is a Vector!
Public Member Functions
AdvectionDiffusionFluxElement (FiniteElement *const &bulk_el_pt, const int &face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to be created.
AdvectionDiffusionFluxElement ()
Broken empty constructor.
AdvectionDiffusionFluxElement (const AdvectionDiffusionFluxElement &dummy)=delete
Broken copy constructor.
void operator= (const AdvectionDiffusionFluxElement &)=delete
Broken assignment operator.
AdvectionDiffusionPrescribedFluxFctPt & flux_fct_pt ()
Access function for the prescribed-flux function pointer.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and its Jacobian matrix.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
void output (std::ostream &outfile)
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
void output (std::ostream &outfile, const unsigned &nplot)
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Protected Member Functions
double shape_and_test (const Vector< double > &s, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
void get_flux (const Vector< double > &x, double &flux)
Function to calculate the prescribed flux at a given spatial position.
Private Member Functions
void fill_in_generic_residual_contribution_adv_diff_flux (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the Jacobian as well.
Private Attributes
AdvectionDiffusionPrescribedFluxFctPt Flux_fct_pt
Function pointer to the (global) prescribed-flux function.
unsigned Dim
The spatial dimension of the problem.
unsigned U_index_adv_diff
The index at which the unknown is stored at the nodes.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::AdvectionDiffusionFluxElement< ELEMENT >
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
A class for elements that allow the imposition of an applied flux on the boundaries of Advection Diffusion elements. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
Definition at line 53 of file advection_diffusion_flux_elements.h.
Member Typedef Documentation
AdvectionDiffusionPrescribedFluxFctPt
template<class ELEMENT >
typedef void(* oomph::AdvectionDiffusionFluxElement< ELEMENT >::AdvectionDiffusionPrescribedFluxFctPt) (const Vector< double > &x, double &flux)
Function pointer to the prescribed-flux function fct(x,f(x)) -- x is a Vector!
Definition at line 59 of file advection_diffusion_flux_elements.h.
Constructor & Destructor Documentation
AdvectionDiffusionFluxElement() [1/3]
template<class ELEMENT >
oomph::AdvectionDiffusionFluxElement< ELEMENT >::AdvectionDiffusionFluxElement (FiniteElement *const & bulk_el_pt, const int & face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to be created.
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Constructor, takes the pointer to the `bulk` element and the index of the face to be created
Definition at line 232 of file advection_diffusion_flux_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::AdvectionDiffusionFluxElement< ELEMENT >::Dim, oomph::FaceElement::face_index(), oomph::AdvectionDiffusionFluxElement< ELEMENT >::Flux_fct_pt, oomph::FiniteElement::has_hanging_nodes(), oomph::FiniteElement::node_pt(), oomph::Global_string_for_annotation::string(), and oomph::AdvectionDiffusionFluxElement< ELEMENT >::U_index_adv_diff.
AdvectionDiffusionFluxElement() [2/3]
template<class ELEMENT >
oomph::AdvectionDiffusionFluxElement< ELEMENT >::AdvectionDiffusionFluxElement () [inline]
Broken empty constructor.
Definition at line 70 of file advection_diffusion_flux_elements.h.
AdvectionDiffusionFluxElement() [3/3]
template<class ELEMENT >
oomph::AdvectionDiffusionFluxElement< ELEMENT >::AdvectionDiffusionFluxElement (const AdvectionDiffusionFluxElement< ELEMENT > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::AdvectionDiffusionFluxElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and its Jacobian matrix.
Reimplemented from oomph::GeneralisedElement.
Definition at line 104 of file advection_diffusion_flux_elements.h.
References oomph::AdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_adv_diff_flux(), and oomph::FiniteElement::jacobian.
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::AdvectionDiffusionFluxElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 93 of file advection_diffusion_flux_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::AdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_adv_diff_flux().
fill_in_generic_residual_contribution_adv_diff_flux()
template<class ELEMENT >
void oomph::AdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_adv_diff_flux (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [private]
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the Jacobian as well.
Compute the element's residual vector and the (zero) Jacobian matrix.
Definition at line 383 of file advection_diffusion_flux_elements.h.
References oomph::Multi_domain_functions::Dim, i, s, and oomph::W.
Referenced by oomph::AdvectionDiffusionFluxElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::AdvectionDiffusionFluxElement< ELEMENT >::fill_in_contribution_to_residuals().
flux_fct_pt()
template<class ELEMENT >
AdvectionDiffusionPrescribedFluxFctPt & oomph::AdvectionDiffusionFluxElement< ELEMENT >::flux_fct_pt () [inline]
Access function for the prescribed-flux function pointer.
Definition at line 86 of file advection_diffusion_flux_elements.h.
References oomph::AdvectionDiffusionFluxElement< ELEMENT >::Flux_fct_pt.
get_flux()
template<class ELEMENT >
void oomph::AdvectionDiffusionFluxElement< ELEMENT >::get_flux (const Vector< double > & x, double & flux) [inline], [protected]
Function to calculate the prescribed flux at a given spatial position.
Definition at line 190 of file advection_diffusion_flux_elements.h.
References oomph::AdvectionDiffusionFluxElement< ELEMENT >::Flux_fct_pt, and oomph::x.
operator=()
template<class ELEMENT >
void oomph::AdvectionDiffusionFluxElement< ELEMENT >::operator= (const AdvectionDiffusionFluxElement< ELEMENT > &) [delete]
Broken assignment operator.
output() [1/2]
template<class ELEMENT >
void oomph::AdvectionDiffusionFluxElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 126 of file advection_diffusion_flux_elements.h.
References oomph::FiniteElement::output().
output() [2/2]
template<class ELEMENT >
void oomph::AdvectionDiffusionFluxElement< ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 133 of file advection_diffusion_flux_elements.h.
References oomph::FiniteElement::output().
shape_and_test()
template<class ELEMENT >
double oomph::AdvectionDiffusionFluxElement< ELEMENT >::shape_and_test (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 143 of file advection_diffusion_flux_elements.h.
References i, oomph::FaceElement::J_eulerian(), oomph::FiniteElement::nnode(), s, and oomph::FiniteElement::shape().
shape_and_test_at_knot()
template<class ELEMENT >
double oomph::AdvectionDiffusionFluxElement< ELEMENT >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 167 of file advection_diffusion_flux_elements.h.
References i, oomph::FaceElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape_at_knot().
zeta_nodal()
template<class ELEMENT >
double oomph::AdvectionDiffusionFluxElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Reimplemented from oomph::FiniteElement.
Definition at line 117 of file advection_diffusion_flux_elements.h.
References i, and oomph::FaceElement::zeta_nodal().
Member Data Documentation
Dim
template<class ELEMENT >
unsigned oomph::AdvectionDiffusionFluxElement< ELEMENT >::Dim [private]
The spatial dimension of the problem.
Definition at line 215 of file advection_diffusion_flux_elements.h.
Referenced by oomph::AdvectionDiffusionFluxElement< ELEMENT >::AdvectionDiffusionFluxElement().
Flux_fct_pt
template<class ELEMENT >
AdvectionDiffusionPrescribedFluxFctPt oomph::AdvectionDiffusionFluxElement< ELEMENT >::Flux_fct_pt [private]
Function pointer to the (global) prescribed-flux function.
Definition at line 212 of file advection_diffusion_flux_elements.h.
Referenced by oomph::AdvectionDiffusionFluxElement< ELEMENT >::AdvectionDiffusionFluxElement(), oomph::AdvectionDiffusionFluxElement< ELEMENT >::flux_fct_pt(), and oomph::AdvectionDiffusionFluxElement< ELEMENT >::get_flux().
U_index_adv_diff
template<class ELEMENT >
unsigned oomph::AdvectionDiffusionFluxElement< ELEMENT >::U_index_adv_diff [private]
The index at which the unknown is stored at the nodes.
Definition at line 218 of file advection_diffusion_flux_elements.h.
Referenced by oomph::AdvectionDiffusionFluxElement< ELEMENT >::AdvectionDiffusionFluxElement().
The documentation for this class was generated from the following file:
advection_diffusion_flux_elements.h