oomph::SolidElementWithDiagonalMassMatrix Class Reference
#include <elements.h>
Public Member Functions
SolidElementWithDiagonalMassMatrix ()
Empty constructor.
virtual ~SolidElementWithDiagonalMassMatrix ()
Virtual destructor.
SolidElementWithDiagonalMassMatrix (const SolidElementWithDiagonalMassMatrix &)
Broken copy constructor.
void operator= (const SolidElementWithDiagonalMassMatrix &)
Broken assignment operator.
virtual void get_mass_matrix_diagonal (Vector< double > &mass_diag)=0
Get the diagonal of whatever represents the mass matrix in the specific preconditionable element. For Navier-Stokes elements this is the velocity mass matrix; for incompressible solids it's the mass matrix; ...
Detailed Description
Pure virtual base class for elements that can be used with PressureBasedSolidLSCPreconditioner.
Definition at line 5258 of file elements.h.
Constructor & Destructor Documentation
SolidElementWithDiagonalMassMatrix() [1/2]
oomph::SolidElementWithDiagonalMassMatrix::SolidElementWithDiagonalMassMatrix () [inline]
Empty constructor.
Definition at line 5262 of file elements.h.
 SolidElementWithDiagonalMassMatrix()
virtual oomph::SolidElementWithDiagonalMassMatrix::~SolidElementWithDiagonalMassMatrix () [inline], [virtual]
Virtual destructor.
Definition at line 5265 of file elements.h.
SolidElementWithDiagonalMassMatrix() [2/2]
oomph::SolidElementWithDiagonalMassMatrix::SolidElementWithDiagonalMassMatrix (const SolidElementWithDiagonalMassMatrix &) [inline]
Broken copy constructor.
Definition at line 5268 of file elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
get_mass_matrix_diagonal()
virtual void oomph::SolidElementWithDiagonalMassMatrix::get_mass_matrix_diagonal (Vector< double > & mass_diag) [pure virtual]
Get the diagonal of whatever represents the mass matrix in the specific preconditionable element. For Navier-Stokes elements this is the velocity mass matrix; for incompressible solids it's the mass matrix; ...
Implemented in oomph::PVDEquationsWithPressure< DIM >, and oomph::RefineablePVDEquationsWithPressure< DIM >.
Referenced by oomph::PressureBasedSolidLSCPreconditioner::assemble_mass_matrix_diagonal().
operator=()
void oomph::SolidElementWithDiagonalMassMatrix::operator= (const SolidElementWithDiagonalMassMatrix &) [inline]
Broken assignment operator.
Definition at line 5275 of file elements.h.
References oomph::BrokenCopy::broken_assign().
The documentation for this class was generated from the following file:
elements.h