oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT > Class Template Reference
A class for elements that allow the imposition of the linearised poroelastic FSI slip condition (according to the Beavers-Joseph-Saffman condition) from an adjacent poroelastic axisymmetric medium. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
#include <axisym_poroelastic_fsi_face_elements.h>
Public Member Functions
LinearisedAxisymPoroelasticBJS_FSIElement (FiniteElement *const &bulk_el_pt, const int &face_index, const unsigned &id=0)
Constructor, takes the pointer to the `bulk` element and the face index identifying the face to which the element is attached. The optional identifier can be used to distinguish the additional nodal values created by this element from thos created by other FaceElements.
LinearisedAxisymPoroelasticBJS_FSIElement ()
Default constructor.
LinearisedAxisymPoroelasticBJS_FSIElement (const LinearisedAxisymPoroelasticBJS_FSIElement &dummy)
Broken copy constructor.
void operator= (const LinearisedAxisymPoroelasticBJS_FSIElement &)
Broken assignment operator.
double *& st_pt ()
Access function for the pointer to the fluid Strouhal number (if not set, St defaults to 1)
double st () const
Access function for the fluid Strouhal number.
double inverse_slip_rate_coefficient () const
Inverse slip rate coefficient.
double *& inverse_slip_rate_coefficient_pt ()
Pointer to inverse slip rate coefficient.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector.
double contribution_to_enclosed_volume ()
Return this element's contribution to the total volume enclosed by collection of these elements.
void output (std::ostream &outfile)
Output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: Output at Gauss points; n_plot is ignored.
void contribution_to_total_porous_flux (double &skeleton_flux_contrib, double &seepage_flux_contrib, double &nst_flux_contrib)
Compute contributions to integrated porous flux over boundary: q_skeleton = \int \partial u_displ / \partial t \cdot n ds q_seepage = \int k q \cdot n ds q_nst = \int u \cdot n ds.
void output (FILE *file_pt)
C-style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function.
Protected Member Functions
double shape_and_test (const Vector< double > &s, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Private Member Functions
void fill_in_generic_residual_contribution_axisym_poroelastic_fsi (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the contribution to the Jacobian as well.
Private Attributes
unsigned Dim
The spatial dimension of the problem.
Vector< unsigned > U_index_axisym_poroelastic_fsi
The index at which the velocity unknowns are stored at the nodes.
unsigned Id
Lagrange Id.
double * St_pt
Pointer to fluid Strouhal number.
double * Inverse_slip_rate_coeff_pt
Pointer to inverse slip rate coefficient.
Additional Inherited Members
Detailed Description
template<class FLUID_BULK_ELEMENT, class POROELASTICITY_BULK_ELEMENT>
class oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >
A class for elements that allow the imposition of the linearised poroelastic FSI slip condition (according to the Beavers-Joseph-Saffman condition) from an adjacent poroelastic axisymmetric medium. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
Definition at line 68 of file axisym_poroelastic_fsi_face_elements.h.
Constructor & Destructor Documentation
LinearisedAxisymPoroelasticBJS_FSIElement() [1/3]
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::LinearisedAxisymPoroelasticBJS_FSIElement (FiniteElement *const & bulk_el_pt, const int & face_index, const unsigned & id = 0)
Constructor, takes the pointer to the `bulk` element and the face index identifying the face to which the element is attached. The optional identifier can be used to distinguish the additional nodal values created by this element from thos created by other FaceElements.
Constructor, takes the pointer to the `bulk` element, and the face index that identifies the face of the bulk element to which this face element is to be attached. The optional identifier can be used to distinguish the additional nodal values created by this element from thos created by other FaceElements.
Definition at line 740 of file axisym_poroelastic_fsi_face_elements.h.
References oomph::FaceElement::add_additional_values(), oomph::GeneralisedElement::add_external_data(), oomph::FiniteElement::build_face_element(), oomph::LinearisedAxisymPoroelasticBJS_FSIHelper::Default_inverse_slip_rate_coefficient, oomph::LinearisedAxisymPoroelasticBJS_FSIHelper::Default_strouhal_number, oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::Dim, oomph::FaceElement::face_index(), i, oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::Id, oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::Inverse_slip_rate_coeff_pt, n, oomph::Node::ndim(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::ElementWithExternalElement::set_ninteraction(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::St_pt, and oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::U_index_axisym_poroelastic_fsi.
LinearisedAxisymPoroelasticBJS_FSIElement() [2/3]
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::LinearisedAxisymPoroelasticBJS_FSIElement () [inline]
Default constructor.
Definition at line 84 of file axisym_poroelastic_fsi_face_elements.h.
LinearisedAxisymPoroelasticBJS_FSIElement() [3/3]
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::LinearisedAxisymPoroelasticBJS_FSIElement (const LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT > & dummy) [inline]
Broken copy constructor.
Definition at line 87 of file axisym_poroelastic_fsi_face_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
contribution_to_enclosed_volume()
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
double oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_enclosed_volume () [inline]
Return this element's contribution to the total volume enclosed by collection of these elements.
Definition at line 157 of file axisym_poroelastic_fsi_face_elements.h.
References oomph::VectorHelpers::dot(), oomph::FiniteElement::dshape_local_at_knot(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), oomph::MathematicalConstants::Pi, s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
contribution_to_total_porous_flux()
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
void oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_total_porous_flux (double & skeleton_flux_contrib, double & seepage_flux_contrib, double & nst_flux_contrib) [inline]
Compute contributions to integrated porous flux over boundary: q_skeleton = \int \partial u_displ / \partial t \cdot n ds q_seepage = \int k q \cdot n ds q_nst = \int u \cdot n ds.
Definition at line 453 of file axisym_poroelastic_fsi_face_elements.h.
References oomph::AxisymmetricPoroelasticityTractionElementHelper::Allow_gap_in_FSI, oomph::FaceElement::bulk_element_pt(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::Dim, oomph::FiniteElement::dshape_local_at_knot(), oomph::ElementWithExternalElement::external_element_local_coord(), oomph::ElementWithExternalElement::external_element_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::Integral::knot(), oomph::FaceElement::local_coordinate_in_bulk(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), oomph::MathematicalConstants::Pi, s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
fill_in_contribution_to_residuals()
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
void oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 127 of file axisym_poroelastic_fsi_face_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::fill_in_generic_residual_contribution_axisym_poroelastic_fsi(), and residuals().
fill_in_generic_residual_contribution_axisym_poroelastic_fsi()
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
void oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::fill_in_generic_residual_contribution_axisym_poroelastic_fsi (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [private]
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the contribution to the Jacobian as well.
Helper function to compute the element's residual vector and the Jacobian matrix.
Definition at line 818 of file axisym_poroelastic_fsi_face_elements.h.
References oomph::Multi_domain_functions::Dim, i, oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), residuals(), s, oomph::Node::value(), and oomph::QuadTreeNames::W.
Referenced by oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::fill_in_contribution_to_residuals().
inverse_slip_rate_coefficient()
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
double oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::inverse_slip_rate_coefficient () const [inline]
Inverse slip rate coefficient.
Definition at line 113 of file axisym_poroelastic_fsi_face_elements.h.
References oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::Inverse_slip_rate_coeff_pt.
Referenced by oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output().
inverse_slip_rate_coefficient_pt()
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
double*& oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::inverse_slip_rate_coefficient_pt () [inline]
Pointer to inverse slip rate coefficient.
Definition at line 120 of file axisym_poroelastic_fsi_face_elements.h.
References oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::Inverse_slip_rate_coeff_pt.
operator=()
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
void oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::operator= (const LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT > &) [inline]
Broken assignment operator.
Definition at line 94 of file axisym_poroelastic_fsi_face_elements.h.
References oomph::BrokenCopy::broken_assign().
output() [1/4]
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
void oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C-style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 639 of file axisym_poroelastic_fsi_face_elements.h.
References oomph::output().
output() [2/4]
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
void oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 645 of file axisym_poroelastic_fsi_face_elements.h.
References oomph::output().
output() [3/4]
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
void oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Definition at line 229 of file axisym_poroelastic_fsi_face_elements.h.
output() [4/4]
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
void oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: Output at Gauss points; n_plot is ignored.
Reimplemented from oomph::FiniteElement.
Definition at line 237 of file axisym_poroelastic_fsi_face_elements.h.
References oomph::AxisymmetricPoroelasticityTractionElementHelper::Allow_gap_in_FSI, oomph::FaceElement::bulk_element_pt(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::Dim, oomph::FiniteElement::dshape_local_at_knot(), oomph::ElementWithExternalElement::external_element_local_coord(), oomph::ElementWithExternalElement::external_element_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::inverse_slip_rate_coefficient(), oomph::Integral::knot(), oomph::FaceElement::local_coordinate_in_bulk(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), p_fluid(), s, oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::st(), and oomph::FiniteElement::tecplot_zone_string().
shape_and_test()
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
double oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::shape_and_test (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 655 of file axisym_poroelastic_fsi_face_elements.h.
References i, oomph::FaceElement::J_eulerian(), oomph::FiniteElement::nnode(), s, and oomph::FiniteElement::shape().
shape_and_test_at_knot()
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
double oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 679 of file axisym_poroelastic_fsi_face_elements.h.
References i, oomph::FaceElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape_at_knot().
st()
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
double oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::st () const [inline]
Access function for the fluid Strouhal number.
Definition at line 107 of file axisym_poroelastic_fsi_face_elements.h.
References oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::St_pt.
Referenced by oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output().
st_pt()
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
double*& oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::st_pt () [inline]
Access function for the pointer to the fluid Strouhal number (if not set, St defaults to 1)
Definition at line 101 of file axisym_poroelastic_fsi_face_elements.h.
References oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::St_pt.
Member Data Documentation
Dim
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
unsigned oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::Dim [private]
The spatial dimension of the problem.
Definition at line 709 of file axisym_poroelastic_fsi_face_elements.h.
Referenced by oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_total_porous_flux(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::LinearisedAxisymPoroelasticBJS_FSIElement(), and oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output().
Id
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
unsigned oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::Id [private]
Lagrange Id.
Definition at line 715 of file axisym_poroelastic_fsi_face_elements.h.
Referenced by oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::LinearisedAxisymPoroelasticBJS_FSIElement().
Inverse_slip_rate_coeff_pt
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
double* oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::Inverse_slip_rate_coeff_pt [private]
Pointer to inverse slip rate coefficient.
Definition at line 721 of file axisym_poroelastic_fsi_face_elements.h.
Referenced by oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::inverse_slip_rate_coefficient(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::inverse_slip_rate_coefficient_pt(), and oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::LinearisedAxisymPoroelasticBJS_FSIElement().
St_pt
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
double* oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::St_pt [private]
Pointer to fluid Strouhal number.
Definition at line 718 of file axisym_poroelastic_fsi_face_elements.h.
Referenced by oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::LinearisedAxisymPoroelasticBJS_FSIElement(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::st(), and oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::st_pt().
U_index_axisym_poroelastic_fsi
template<class FLUID_BULK_ELEMENT , class POROELASTICITY_BULK_ELEMENT >
Vector<unsigned> oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::U_index_axisym_poroelastic_fsi [private]
The index at which the velocity unknowns are stored at the nodes.
Definition at line 712 of file axisym_poroelastic_fsi_face_elements.h.
Referenced by oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::LinearisedAxisymPoroelasticBJS_FSIElement().
The documentation for this class was generated from the following file:
axisym_poroelastic_fsi_face_elements.h