oomph::HelmholtzDtNMesh< ELEMENT > Class Template Reference
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
#include <helmholtz_bc_elements.h>
Public Member Functions
HelmholtzDtNMesh (const double &outer_radius, const unsigned &nfourier_terms)
Constructor: Specify radius of outer boundary and number of Fourier terms used in the computation of the gamma integral.
void setup_gamma ()
Compute and store the gamma integral at all integration points of the constituent elements.
void compute_fourier_components (Vector< std::complex< double > > &a_coeff_pos, Vector< std::complex< double > > &a_coeff_neg)
Compute Fourier components of the solution -- length of vector indicates number of terms to be computed.
Vector< std::complex< double > > & gamma_at_gauss_point (FiniteElement *el_pt)
Gamma integral evaluated at Gauss points for specified element.
Vector< std::map< unsigned, std::complex< double > > > & d_gamma_at_gauss_point (FiniteElement *el_pt)
Derivative of Gamma integral w.r.t global unknown, evaluated at Gauss points for specified element.
double & outer_radius ()
The outer radius.
unsigned & nfourier_terms ()
Number of Fourier terms used in the computation of the gamma integral.
Private Attributes
double Outer_radius
Outer radius.
unsigned Nfourier_terms
Nbr of Fourier terms used in the Gamma computation.
std::map< FiniteElement *, Vector< std::complex< double > > > Gamma_at_gauss_point
Container to store the gamma integral for given Gauss point and element.
std::map< FiniteElement *, Vector< std::map< unsigned, std::complex< double > > > > D_Gamma_at_gauss_point
Container to store the derivate of Gamma integral w.r.t global unknown evaluated at Gauss points for specified element.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::HelmholtzDtNMesh< ELEMENT >
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
================================================================= Mesh for DtN boundary condition elements -- provides functionality to apply Sommerfeld radiation condtion
via DtN BC
Definition at line 561 of file helmholtz_bc_elements.h.
Constructor & Destructor Documentation
HelmholtzDtNMesh()
template<class ELEMENT >
oomph::HelmholtzDtNMesh< ELEMENT >::HelmholtzDtNMesh (const double & outer_radius, const unsigned & nfourier_terms) [inline]
Constructor: Specify radius of outer boundary and number of Fourier terms used in the computation of the gamma integral.
Definition at line 566 of file helmholtz_bc_elements.h.
Member Function Documentation
compute_fourier_components()
template<class ELEMENT >
void oomph::HelmholtzDtNMesh< ELEMENT >::compute_fourier_components (Vector< std::complex< double > > & a_coeff_pos, Vector< std::complex< double > > & a_coeff_neg)
Compute Fourier components of the solution -- length of vector indicates number of terms to be computed.
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
================================================================ Compute Fourier components of the solution -- length of
vector indicates number of terms to be computed.
Definition at line 1621 of file helmholtz_bc_elements.h.
References oomph::HelmholtzBCElementBase< ELEMENT >::compute_contribution_to_fourier_components(), e, and i.
d_gamma_at_gauss_point()
template<class ELEMENT >
Vector< std::map< unsigned, std::complex< double > > > & oomph::HelmholtzDtNMesh< ELEMENT >::d_gamma_at_gauss_point (FiniteElement * el_pt) [inline]
Derivative of Gamma integral w.r.t global unknown, evaluated at Gauss points for specified element.
Definition at line 589 of file helmholtz_bc_elements.h.
References oomph::HelmholtzDtNMesh< ELEMENT >::D_Gamma_at_gauss_point.
gamma_at_gauss_point()
template<class ELEMENT >
Vector< std::complex< double > > & oomph::HelmholtzDtNMesh< ELEMENT >::gamma_at_gauss_point (FiniteElement * el_pt) [inline]
Gamma integral evaluated at Gauss points for specified element.
Definition at line 582 of file helmholtz_bc_elements.h.
References oomph::HelmholtzDtNMesh< ELEMENT >::Gamma_at_gauss_point.
nfourier_terms()
template<class ELEMENT >
unsigned & oomph::HelmholtzDtNMesh< ELEMENT >::nfourier_terms () [inline]
Number of Fourier terms used in the computation of the gamma integral.
Definition at line 603 of file helmholtz_bc_elements.h.
References oomph::HelmholtzDtNMesh< ELEMENT >::Nfourier_terms.
outer_radius()
template<class ELEMENT >
double & oomph::HelmholtzDtNMesh< ELEMENT >::outer_radius () [inline]
The outer radius.
Definition at line 596 of file helmholtz_bc_elements.h.
References oomph::HelmholtzDtNMesh< ELEMENT >::Outer_radius.
setup_gamma()
template<class ELEMENT >
void oomph::HelmholtzDtNMesh< ELEMENT >::setup_gamma
Compute and store the gamma integral at all integration points of the constituent elements.
================================================================ Compute and store the gamma integral and derivates
of the mesh's constituent elements
Definition at line 1674 of file helmholtz_bc_elements.h.
References oomph::FaceElement::bulk_element_pt(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::compute_gamma_contribution(), oomph::FiniteElement::dim(), e, oomph::GeneralisedElement::eqn_number(), oomph::Hankel_functions_for_helmholtz_problem::Hankel_first(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), oomph::MathematicalConstants::Pi, s, oomph::ToleranceForHelmholtzOuterBoundary::Tol, oomph::HelmholtzBCElementBase< ELEMENT >::u_index_helmholtz(), and oomph::x.
Member Data Documentation
D_Gamma_at_gauss_point
template<class ELEMENT >
std::map<FiniteElement*, Vector<std::map<unsigned, std::complex<double> > > > oomph::HelmholtzDtNMesh< ELEMENT >::D_Gamma_at_gauss_point [private]
Container to store the derivate of Gamma integral w.r.t global unknown evaluated at Gauss points for specified element.
Definition at line 624 of file helmholtz_bc_elements.h.
Referenced by oomph::HelmholtzDtNMesh< ELEMENT >::d_gamma_at_gauss_point().
Gamma_at_gauss_point
template<class ELEMENT >
std::map<FiniteElement*, Vector<std::complex<double> > > oomph::HelmholtzDtNMesh< ELEMENT >::Gamma_at_gauss_point [private]
Container to store the gamma integral for given Gauss point and element.
Definition at line 618 of file helmholtz_bc_elements.h.
Referenced by oomph::HelmholtzDtNMesh< ELEMENT >::gamma_at_gauss_point().
Nfourier_terms
template<class ELEMENT >
unsigned oomph::HelmholtzDtNMesh< ELEMENT >::Nfourier_terms [private]
Nbr of Fourier terms used in the Gamma computation.
Definition at line 613 of file helmholtz_bc_elements.h.
Referenced by oomph::HelmholtzDtNMesh< ELEMENT >::nfourier_terms().
Outer_radius
template<class ELEMENT >
double oomph::HelmholtzDtNMesh< ELEMENT >::Outer_radius [private]
Outer radius.
Definition at line 610 of file helmholtz_bc_elements.h.
Referenced by oomph::HelmholtzDtNMesh< ELEMENT >::outer_radius().
The documentation for this class was generated from the following file:
helmholtz_bc_elements.h