oomph::PoroelasticityFaceElement< ELEMENT > Class Template Reference
A class for elements that allow the imposition of an applied pressure in the Darcy equations. The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
#include <poroelasticity_face_elements.h>
Public Member Functions
PoroelasticityFaceElement (FiniteElement *const &element_pt, const int &face_index)
Constructor, which takes a `bulk` element and the value of the index and its limit.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Return the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Fill in contribution from Jacobian.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
void output (std::ostream &outfile)
Output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
void output (FILE *file_pt)
C_style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function.
void traction (const double &time, const Vector< double > &s, Vector< double > &traction)
Compute traction vector at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
void pressure (const double &time, const Vector< double > &s, double &pressure)
Compute pressure value at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
Public Attributes
void(*&)(const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction) traction_fct_pt ()
Reference to the traction function pointer.
void(*&)(const double &time, const Vector< double > &x, const Vector< double > &n, double &pressure) pressure_fct_pt ()
Reference to the pressure function pointer.
Protected Member Functions
virtual void get_traction (const double &time, const unsigned &intpt, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction)
Get the traction vector: Pass number of integration point (dummy), Eulerlian coordinate and normal vector and return the pressure (not all of the input arguments will be required for all specific load functions but the list should cover all cases). This function is virtual so it can be overloaded for FSI.
virtual void get_pressure (const double &time, const unsigned &intpt, const Vector< double > &x, const Vector< double > &n, double &pressure)
Get the pressure value: Pass number of integration point (dummy), Eulerlian coordinate and normal vector and return the pressure (not all of the input arguments will be required for all specific load functions but the list should cover all cases). This function is virtual so it can be overloaded for FSI.
void fill_in_contribution_to_residuals_darcy_face (Vector< double > &residuals)
Helper function that actually calculates the residuals.
Protected Attributes
ELEMENT * Element_pt
pointer to the bulk element this face element is attached to
void(* Traction_fct_pt)(const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
Pointer to an imposed traction function. Arguments: Eulerian coordinate; outer unit normal; applied traction. (Not all of the input arguments will be required for all specific load functions but the list should cover all cases)
void(* Pressure_fct_pt)(const double &time, const Vector< double > &x, const Vector< double > &n, double &result)
Pointer to an imposed pressure function. Arguments: Eulerian coordinate; outer unit normal; applied pressure. (Not all of the input arguments will be required for all specific load functions but the list should cover all cases)
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::PoroelasticityFaceElement< ELEMENT >
A class for elements that allow the imposition of an applied pressure in the Darcy equations. The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class.
Definition at line 86 of file poroelasticity_face_elements.h.
Constructor & Destructor Documentation
PoroelasticityFaceElement()
template<class ELEMENT >
oomph::PoroelasticityFaceElement< ELEMENT >::PoroelasticityFaceElement (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor, which takes a `bulk` element and the value of the index and its limit.
Definition at line 152 of file poroelasticity_face_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::PoroelasticityFaceElement< ELEMENT >::Element_pt, oomph::FaceElement::face_index(), oomph::PoroelasticityFaceElement< ELEMENT >::Pressure_fct_pt, oomph::PoroelasticityFaceElement< ELEMENT >::Traction_fct_pt, oomph::PoroelasticityFaceElementHelper::Zero_pressure_fct(), and oomph::PoroelasticityFaceElementHelper::Zero_traction_fct().
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::PoroelasticityFaceElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Fill in contribution from Jacobian.
Reimplemented from oomph::FiniteElement.
Definition at line 218 of file poroelasticity_face_elements.h.
References oomph::PoroelasticityFaceElement< ELEMENT >::fill_in_contribution_to_residuals_darcy_face().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::PoroelasticityFaceElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Return the residuals.
Reimplemented from oomph::GeneralisedElement.
Definition at line 211 of file poroelasticity_face_elements.h.
References oomph::PoroelasticityFaceElement< ELEMENT >::fill_in_contribution_to_residuals_darcy_face().
fill_in_contribution_to_residuals_darcy_face()
template<class ELEMENT >
void oomph::PoroelasticityFaceElement< ELEMENT >::fill_in_contribution_to_residuals_darcy_face (Vector< double > & residuals) [protected]
Helper function that actually calculates the residuals.
Return the residuals for the PoroelasticityFaceElement equations.
Definition at line 339 of file poroelasticity_face_elements.h.
References i, and oomph::QuadTreeNames::W.
Referenced by oomph::PoroelasticityFaceElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::PoroelasticityFaceElement< ELEMENT >::fill_in_contribution_to_residuals().
get_pressure()
template<class ELEMENT >
virtual void oomph::PoroelasticityFaceElement< ELEMENT >::get_pressure (const double & time, const unsigned & intpt, const Vector< double > & x, const Vector< double > & n, double & pressure) [inline], [protected], [virtual]
Get the pressure value: Pass number of integration point (dummy), Eulerlian coordinate and normal vector and return the pressure (not all of the input arguments will be required for all specific load functions but the list should cover all cases). This function is virtual so it can be overloaded for FSI.
Definition at line 131 of file poroelasticity_face_elements.h.
References oomph::PoroelasticityFaceElement< ELEMENT >::pressure(), and oomph::PoroelasticityFaceElement< ELEMENT >::Pressure_fct_pt.
get_traction()
template<class ELEMENT >
virtual void oomph::PoroelasticityFaceElement< ELEMENT >::get_traction (const double & time, const unsigned & intpt, const Vector< double > & x, const Vector< double > & n, Vector< double > & traction) [inline], [protected], [virtual]
Get the traction vector: Pass number of integration point (dummy), Eulerlian coordinate and normal vector and return the pressure (not all of the input arguments will be required for all specific load functions but the list should cover all cases). This function is virtual so it can be overloaded for FSI.
Definition at line 117 of file poroelasticity_face_elements.h.
References oomph::PoroelasticityFaceElement< ELEMENT >::traction(), and oomph::PoroelasticityFaceElement< ELEMENT >::Traction_fct_pt.
output() [1/4]
template<class ELEMENT >
void oomph::PoroelasticityFaceElement< ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C_style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 250 of file poroelasticity_face_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<class ELEMENT >
void oomph::PoroelasticityFaceElement< ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 256 of file poroelasticity_face_elements.h.
References oomph::FiniteElement::output().
output() [3/4]
template<class ELEMENT >
void oomph::PoroelasticityFaceElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Definition at line 238 of file poroelasticity_face_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<class ELEMENT >
void oomph::PoroelasticityFaceElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Definition at line 244 of file poroelasticity_face_elements.h.
References oomph::FiniteElement::output().
pressure()
template<class ELEMENT >
void oomph::PoroelasticityFaceElement< ELEMENT >::pressure (const double & time, const Vector< double > & s, double & pressure)
Compute pressure value at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
Definition at line 313 of file poroelasticity_face_elements.h.
References s.
Referenced by oomph::PoroelasticityFaceElement< ELEMENT >::get_pressure().
traction()
template<class ELEMENT >
void oomph::PoroelasticityFaceElement< ELEMENT >::traction (const double & time, const Vector< double > & s, Vector< double > & traction)
Compute traction vector at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Compute traction vector at specified local coordinate Should only be used for post-processing; ignores dependence on integration point!
Definition at line 287 of file poroelasticity_face_elements.h.
References s.
Referenced by oomph::PoroelasticityFaceElement< ELEMENT >::get_traction().
zeta_nodal()
template<class ELEMENT >
double oomph::PoroelasticityFaceElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Reimplemented from oomph::FaceElement.
Definition at line 230 of file poroelasticity_face_elements.h.
References i, and oomph::FaceElement::zeta_nodal().
Member Data Documentation
Element_pt
template<class ELEMENT >
ELEMENT* oomph::PoroelasticityFaceElement< ELEMENT >::Element_pt [protected]
pointer to the bulk element this face element is attached to
Definition at line 91 of file poroelasticity_face_elements.h.
Referenced by oomph::PoroelasticityFaceElement< ELEMENT >::PoroelasticityFaceElement().
pressure_fct_pt
template<class ELEMENT >
void(*&)(const double &time, const Vector< double > &x, const Vector< double > &n, double &pressure) oomph::PoroelasticityFaceElement< ELEMENT >::pressure_fct_pt() [inline]
Reference to the pressure function pointer.
Definition at line 201 of file poroelasticity_face_elements.h.
Pressure_fct_pt
template<class ELEMENT >
void(* oomph::PoroelasticityFaceElement< ELEMENT >::Pressure_fct_pt) (const double &time, const Vector< double > &x, const Vector< double > &n, double &result) [protected]
Pointer to an imposed pressure function. Arguments: Eulerian coordinate; outer unit normal; applied pressure. (Not all of the input arguments will be required for all specific load functions but the list should cover all cases)
Definition at line 106 of file poroelasticity_face_elements.h.
Referenced by oomph::PoroelasticityFaceElement< ELEMENT >::get_pressure(), and oomph::PoroelasticityFaceElement< ELEMENT >::PoroelasticityFaceElement().
traction_fct_pt
template<class ELEMENT >
void(*&)(const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction) oomph::PoroelasticityFaceElement< ELEMENT >::traction_fct_pt() [inline]
Reference to the traction function pointer.
Definition at line 192 of file poroelasticity_face_elements.h.
Traction_fct_pt
template<class ELEMENT >
void(* oomph::PoroelasticityFaceElement< ELEMENT >::Traction_fct_pt) (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result) [protected]
Pointer to an imposed traction function. Arguments: Eulerian coordinate; outer unit normal; applied traction. (Not all of the input arguments will be required for all specific load functions but the list should cover all cases)
Definition at line 97 of file poroelasticity_face_elements.h.
Referenced by oomph::PoroelasticityFaceElement< ELEMENT >::get_traction(), and oomph::PoroelasticityFaceElement< ELEMENT >::PoroelasticityFaceElement().
The documentation for this class was generated from the following file:
poroelasticity_face_elements.h