oomph::FSIFluidElement Class Reference
/////////////////////////////////////////////////////////////////////////
#include <fsi.h>
Public Member Functions
FSIFluidElement ()
Constructor.
FSIFluidElement (const FSIFluidElement &)=delete
Broken copy constructor.
void operator= (const FSIFluidElement &)=delete
Broken assignment operator.
virtual void get_load (const Vector< double > &s, const Vector< double > &N, Vector< double > &load)=0
Compute the load vector that is applied by current element (at its local coordinate s) onto the adjacent SolidElement. N is the outer unit normal on the FSIFluidElement.
virtual void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)=0
Add to the set paired_load_data pairs containing.
virtual void identify_pressure_data (std::set< std::pair< Data *, unsigned > > &paired_pressure_data)=0
Add to the set paired_pressure_data pairs containing.
Additional Inherited Members
Detailed Description
/////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////// The FSIFluidElement class is a base class for all fluid finite elements that apply a load (traction) onto an adjacent SolidFiniteElement.
Definition at line 62 of file fsi.h.
Constructor & Destructor Documentation
FSIFluidElement() [1/2]
oomph::FSIFluidElement::FSIFluidElement () [inline]
Constructor.
Definition at line 66 of file fsi.h.
FSIFluidElement() [2/2]
oomph::FSIFluidElement::FSIFluidElement (const FSIFluidElement &) [delete]
Broken copy constructor.
Member Function Documentation
get_load()
virtual void oomph::FSIFluidElement::get_load (const Vector< double > & s, const Vector< double > & N, Vector< double > & load) [pure virtual]
Compute the load vector that is applied by current element (at its local coordinate s) onto the adjacent SolidElement. N is the outer unit normal on the FSIFluidElement.
Implemented in oomph::FSIAxisymmetricQTaylorHoodElement, oomph::GeneralisedNewtonianNavierStokesEquations< DIM >, oomph::NavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, and oomph::SphericalNavierStokesEquations.
Referenced by oomph::FSIWallElement::fluid_load_vector().
identify_load_data()
virtual void oomph::FSIFluidElement::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data) [pure virtual]
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Implemented in oomph::FSIAxisymmetricQTaylorHoodElement, oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >, oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >, oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >, oomph::QCrouzeixRaviartElement< DIM >, oomph::QTaylorHoodElement< DIM >, oomph::RefineableQTaylorHoodElement< DIM >, oomph::RefineableQCrouzeixRaviartElement< DIM >, oomph::TCrouzeixRaviartElement< DIM >, oomph::TTaylorHoodElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >, oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::QSphericalCrouzeixRaviartElement, and oomph::QSphericalTaylorHoodElement.
Referenced by oomph::FSIWallElement::identify_all_field_data_for_external_interaction(), and oomph::ImmersedRigidBodyElement::set_drag_mesh().
identify_pressure_data()
virtual void oomph::FSIFluidElement::identify_pressure_data (std::set< std::pair< Data *, unsigned > > & paired_pressure_data) [pure virtual]
Add to the set paired_pressure_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all pressure values that affect the load computed in the get_load(...) function.
Implemented in oomph::FSIAxisymmetricQTaylorHoodElement, oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >, oomph::QCrouzeixRaviartElement< DIM >, oomph::QTaylorHoodElement< DIM >, oomph::TCrouzeixRaviartElement< DIM >, oomph::TTaylorHoodElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >, oomph::QSphericalCrouzeixRaviartElement, and oomph::QSphericalTaylorHoodElement.
Referenced by oomph::FSIWallElement::identify_all_field_data_for_external_interaction().
operator=()
void oomph::FSIFluidElement::operator= (const FSIFluidElement &) [delete]
Broken assignment operator.
The documentation for this class was generated from the following file:
fsi.h