oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM > Class Template Reference
A class for all isoparametric elements that solve the SpaceTimeUnsteadyHeat equations.
#include <space_time_unsteady_heat_elements.h>
Public Types
typedef void(* SpaceTimeUnsteadyHeatSourceFctPt) (const double &time, const Vector< double > &x, double &u)
Function pointer to source function fct(t,x,f(x,t)) -- x is a Vector! DRAIG: Why is this here? There is already one in the base class!
typedef void(* SpaceTimeUnsteadyHeatSourceFctPt) (const double &time, const Vector< double > &x, double &u)
Function pointer to source function fct(t,x,f(x,t)) -- x is a Vector! DRAIG: Why is this here? There is already one in the base class!
Public Member Functions
SpaceTimeUnsteadyHeatEquations ()
Constructor: Initialises the Source_fct_pt to null and sets flag to use ALE formulation of the equations. Also, set Alpha (thermal inertia) and Beta (thermal conductivity) parameters to defaults (both one for natural scaling).
SpaceTimeUnsteadyHeatEquations (const SpaceTimeUnsteadyHeatEquations &dummy)=delete
Broken copy constructor.
void disable_ALE ()
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
void enable_ALE ()
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
void compute_norm (double &norm)
Compute norm of FE solution.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &nplot)
Output FE representation of soln: x,y,u or x,y,z,u at nplot^SPATIAL_DIM plot points.
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &nplot)
C-style output FE representation of soln: x,y,u or x,y,z,u at nplot^SPATIAL_DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^SPATIAL_DIM plot points.
virtual void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^SPATIAL_DIM plot points (time-dependent version)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error and norm against exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Get error and norm against exact solution.
void output_element_paraview (std::ofstream &outfile, const unsigned &nplot)
C-style output FE representation of soln: x,y,u or x,y,z,u at nplot^SPATIAL_DIM plot points.
unsigned nscalar_paraview () const
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
std::string scalar_name_paraview (const unsigned &i) const
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc.
SpaceTimeUnsteadyHeatSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
SpaceTimeUnsteadyHeatSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
virtual void get_source_ust_heat (const double &t, const unsigned &ipt, const Vector< double > &x, double &source) const
Get source term at continous time t and (Eulerian) position x. Virtual so it can be overloaded in derived multi-physics elements.
const double & alpha () const
Alpha parameter (thermal inertia)
double *& alpha_pt ()
Pointer to Alpha parameter (thermal inertia)
const double & beta () const
Beta parameter (thermal conductivity)
double *& beta_pt ()
Pointer to Beta parameter (thermal conductivity)
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: flux[i]=du/dx_i.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute element residual Vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute element residual Vector and element Jacobian matrix (wrapper)
double interpolated_u_ust_heat (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
virtual unsigned u_index_ust_heat () const
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the unsteady heat equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
double interpolated_u_ust_heat (const unsigned &t, const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s at previous time t (t=0: present) DRAIG: This needs to be broken; doesn't make sense in space-time elements!
double du_dt_ust_heat (const unsigned &n) const
Calculate du/dt at the n-th local node. Uses suitably interpolated value for hanging nodes.
double interpolated_du_dt_ust_heat (const Vector< double > &s) const
Return FE representation of function value du/dt(s) at local coordinate s.
unsigned self_test ()
Self-test: Return 0 for OK.
SpaceTimeUnsteadyHeatEquations ()
Constructor: Initialises the Source_fct_pt to null and sets flag to use ALE formulation of the equations. Also, set Alpha (thermal inertia) and Beta (thermal conductivity) parameters to defaults (both one for natural scaling).
SpaceTimeUnsteadyHeatEquations (const SpaceTimeUnsteadyHeatEquations &dummy)=delete
Broken copy constructor.
void disable_ALE ()
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
void enable_ALE ()
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
void compute_norm (double &norm)
Compute norm of FE solution.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &nplot)
Output FE representation of soln: x,y,u or x,y,z,u at nplot^SPATIAL_DIM plot points.
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &nplot)
C-style output FE representation of soln: x,y,u or x,y,z,u at nplot^SPATIAL_DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^SPATIAL_DIM plot points.
virtual void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^SPATIAL_DIM plot points (time-dependent version)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error and norm against exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Get error and norm against exact solution.
void output_element_paraview (std::ofstream &outfile, const unsigned &nplot)
C-style output FE representation of soln: x,y,u or x,y,z,u at nplot^SPATIAL_DIM plot points.
unsigned nscalar_paraview () const
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
std::string scalar_name_paraview (const unsigned &i) const
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc.
SpaceTimeUnsteadyHeatSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
SpaceTimeUnsteadyHeatSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
virtual void get_source_ust_heat (const double &t, const unsigned &ipt, const Vector< double > &x, double &source) const
Get source term at continous time t and (Eulerian) position x. Virtual so it can be overloaded in derived multi-physics elements.
const double & alpha () const
Alpha parameter (thermal inertia)
double *& alpha_pt ()
Pointer to Alpha parameter (thermal inertia)
const double & beta () const
Beta parameter (thermal conductivity)
double *& beta_pt ()
Pointer to Beta parameter (thermal conductivity)
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: flux[i]=du/dx_i.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute element residual Vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute element residual Vector and element Jacobian matrix (wrapper)
double interpolated_u_ust_heat (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
virtual unsigned u_index_ust_heat () const
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the unsteady heat equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
double interpolated_u_ust_heat (const unsigned &t, const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s at previous time t (t=0: present) DRAIG: This needs to be broken; doesn't make sense in space-time elements!
double du_dt_ust_heat (const unsigned &n) const
Calculate du/dt at the n-th local node. Uses suitably interpolated value for hanging nodes.
double interpolated_du_dt_ust_heat (const Vector< double > &s) const
Return FE representation of function value du/dt(s) at local coordinate s.
unsigned self_test ()
Self-test: Return 0 for OK.
virtual double dshape_and_dtest_eulerian_ust_heat (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coordinate s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_ust_heat (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Protected Member Functions
virtual double dshape_and_dtest_eulerian_ust_heat (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coordinate s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_ust_heat (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
virtual void fill_in_generic_residual_contribution_ust_heat (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
virtual void fill_in_generic_residual_contribution_ust_heat (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Protected Attributes
SpaceTimeUnsteadyHeatSourceFctPt Source_fct_pt
Pointer to source function:
bool ALE_is_disabled
Boolean flag to indicate if ALE formulation is disabled when time-derivatives are computed. Only set to true if you're sure that the mesh is stationary.
double * Alpha_pt
Pointer to Alpha parameter (thermal inertia)
double * Beta_pt
Pointer to Beta parameter (thermal conductivity)
Static Private Attributes
static double Default_alpha_parameter
Static default value for the Alpha parameter (thermal inertia): One for natural scaling.
static double Default_beta_parameter
Static default value for the Beta parameter (thermal conductivity): One for natural scaling.
Additional Inherited Members
Detailed Description
template<unsigned SPATIAL_DIM>
class oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >
A class for all isoparametric elements that solve the SpaceTimeUnsteadyHeat equations.
 \frac{\partial^2 u}{\partial x_i^2}=\frac{\partial u}{\partial t}+f(t,x_j) 
 This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class. Note that this class assumes an isoparametric formulation, i.e. that the scalar unknown is interpolated using the same shape funcitons as the position.
Definition at line 75 of file space_time_unsteady_heat_elements.h.
Member Typedef Documentation
SpaceTimeUnsteadyHeatSourceFctPt [1/2]
template<unsigned SPATIAL_DIM>
typedef void(* oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::SpaceTimeUnsteadyHeatSourceFctPt) (const double &time, const Vector< double > &x, double &u)
Function pointer to source function fct(t,x,f(x,t)) -- x is a Vector! DRAIG: Why is this here? There is already one in the base class!
Definition at line 82 of file space_time_unsteady_heat_elements.h.
SpaceTimeUnsteadyHeatSourceFctPt [2/2]
template<unsigned SPATIAL_DIM>
typedef void(* oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::SpaceTimeUnsteadyHeatSourceFctPt) (const double &time, const Vector< double > &x, double &u)
Function pointer to source function fct(t,x,f(x,t)) -- x is a Vector! DRAIG: Why is this here? There is already one in the base class!
Definition at line 81 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
Constructor & Destructor Documentation
SpaceTimeUnsteadyHeatEquations() [1/4]
template<unsigned SPATIAL_DIM>
oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::SpaceTimeUnsteadyHeatEquations () [inline]
Constructor: Initialises the Source_fct_pt to null and sets flag to use ALE formulation of the equations. Also, set Alpha (thermal inertia) and Beta (thermal conductivity) parameters to defaults (both one for natural scaling).
Definition at line 91 of file space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Alpha_pt, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Beta_pt, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Default_alpha_parameter, and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Default_beta_parameter.
SpaceTimeUnsteadyHeatEquations() [2/4]
template<unsigned SPATIAL_DIM>
oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::SpaceTimeUnsteadyHeatEquations (const SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM > & dummy) [delete]
Broken copy constructor.
SpaceTimeUnsteadyHeatEquations() [3/4]
template<unsigned SPATIAL_DIM>
oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::SpaceTimeUnsteadyHeatEquations () [inline]
Constructor: Initialises the Source_fct_pt to null and sets flag to use ALE formulation of the equations. Also, set Alpha (thermal inertia) and Beta (thermal conductivity) parameters to defaults (both one for natural scaling).
Definition at line 90 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Alpha_pt, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Beta_pt, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Default_alpha_parameter, and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Default_beta_parameter.
SpaceTimeUnsteadyHeatEquations() [4/4]
template<unsigned SPATIAL_DIM>
oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::SpaceTimeUnsteadyHeatEquations (const SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
alpha() [1/2]
template<unsigned SPATIAL_DIM>
const double & oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::alpha () const [inline]
Alpha parameter (thermal inertia)
Definition at line 418 of file space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Alpha_pt.
alpha() [2/2]
template<unsigned SPATIAL_DIM>
const double & oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::alpha () const [inline]
Alpha parameter (thermal inertia)
Definition at line 417 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Alpha_pt.
alpha_pt() [1/2]
template<unsigned SPATIAL_DIM>
double *& oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::alpha_pt () [inline]
Pointer to Alpha parameter (thermal inertia)
Definition at line 426 of file space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Alpha_pt.
alpha_pt() [2/2]
template<unsigned SPATIAL_DIM>
double *& oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::alpha_pt () [inline]
Pointer to Alpha parameter (thermal inertia)
Definition at line 425 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Alpha_pt.
beta() [1/2]
template<unsigned SPATIAL_DIM>
const double & oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::beta () const [inline]
Beta parameter (thermal conductivity)
Definition at line 434 of file space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Beta_pt.
beta() [2/2]
template<unsigned SPATIAL_DIM>
const double & oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::beta () const [inline]
Beta parameter (thermal conductivity)
Definition at line 433 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Beta_pt.
beta_pt() [1/2]
template<unsigned SPATIAL_DIM>
double *& oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::beta_pt () [inline]
Pointer to Beta parameter (thermal conductivity)
Definition at line 442 of file space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Beta_pt.
beta_pt() [2/2]
template<unsigned SPATIAL_DIM>
double *& oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::beta_pt () [inline]
Pointer to Beta parameter (thermal conductivity)
Definition at line 441 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Beta_pt.
compute_error() [1/4]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error and norm against exact solution.
Validate against exact solution.
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 529 of file space_time_unsteady_heat_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
compute_error() [2/4]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error and norm against exact solution.
Reimplemented from oomph::FiniteElement.
compute_error() [3/4]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [virtual]
Get error and norm against exact solution.
Validate against exact solution at time t.
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 619 of file space_time_unsteady_heat_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
compute_error() [4/4]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [virtual]
Get error and norm against exact solution.
Reimplemented from oomph::FiniteElement.
compute_norm() [1/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::compute_norm (double & norm) [virtual]
Compute norm of FE solution.
Reimplemented from oomph::GeneralisedElement.
Definition at line 242 of file space_time_unsteady_heat_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
compute_norm() [2/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::compute_norm (double & norm) [virtual]
Compute norm of FE solution.
Reimplemented from oomph::GeneralisedElement.
disable_ALE() [1/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::disable_ALE () [inline], [virtual]
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
Reimplemented from oomph::FiniteElement.
Definition at line 107 of file space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::ALE_is_disabled.
disable_ALE() [2/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::disable_ALE () [inline], [virtual]
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
Reimplemented from oomph::FiniteElement.
Definition at line 106 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::ALE_is_disabled.
dshape_and_dtest_eulerian_at_knot_ust_heat() [1/2]
template<unsigned SPATIAL_DIM>
virtual double oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::dshape_and_dtest_eulerian_at_knot_ust_heat (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, and oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
dshape_and_dtest_eulerian_at_knot_ust_heat() [2/2]
template<unsigned SPATIAL_DIM>
virtual double oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::dshape_and_dtest_eulerian_at_knot_ust_heat (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, and oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
dshape_and_dtest_eulerian_ust_heat() [1/2]
template<unsigned SPATIAL_DIM>
virtual double oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::dshape_and_dtest_eulerian_ust_heat (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coordinate s; return Jacobian of mapping.
Implemented in oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, and oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
dshape_and_dtest_eulerian_ust_heat() [2/2]
template<unsigned SPATIAL_DIM>
virtual double oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::dshape_and_dtest_eulerian_ust_heat (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coordinate s; return Jacobian of mapping.
Implemented in oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, and oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
du_dt_ust_heat() [1/2]
template<unsigned SPATIAL_DIM>
double oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::du_dt_ust_heat (const unsigned & n) const [inline]
Calculate du/dt at the n-th local node. Uses suitably interpolated value for hanging nodes.
Definition at line 586 of file space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::interpolated_du_dt_ust_heat(), oomph::FiniteElement::local_coordinate_of_node(), and s.
du_dt_ust_heat() [2/2]
template<unsigned SPATIAL_DIM>
double oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::du_dt_ust_heat (const unsigned & n) const [inline]
Calculate du/dt at the n-th local node. Uses suitably interpolated value for hanging nodes.
Definition at line 585 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::interpolated_du_dt_ust_heat(), oomph::FiniteElement::local_coordinate_of_node(), and s.
enable_ALE() [1/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::enable_ALE () [inline], [virtual]
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
Reimplemented from oomph::FiniteElement.
Definition at line 118 of file space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::ALE_is_disabled.
enable_ALE() [2/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::enable_ALE () [inline], [virtual]
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
Reimplemented from oomph::FiniteElement.
Definition at line 117 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::ALE_is_disabled.
fill_in_contribution_to_jacobian() [1/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute element residual Vector and element Jacobian matrix (wrapper)
Reimplemented from oomph::FiniteElement.
Definition at line 498 of file space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat().
fill_in_contribution_to_jacobian() [2/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute element residual Vector and element Jacobian matrix (wrapper)
Reimplemented from oomph::FiniteElement.
Definition at line 497 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat().
fill_in_contribution_to_residuals() [1/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Compute element residual Vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 488 of file space_time_unsteady_heat_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat().
fill_in_contribution_to_residuals() [2/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Compute element residual Vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 487 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat().
fill_in_generic_residual_contribution_ust_heat() [1/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected], [virtual]
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Compute element residual vector and/or element Jacobian matrix.
flag=0: compute only residual vector flag=1: compute both
Pure version without hanging nodes
Reimplemented in oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, and oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.
Definition at line 64 of file space_time_unsteady_heat_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
Referenced by oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_contribution_to_jacobian(), and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_contribution_to_residuals().
fill_in_generic_residual_contribution_ust_heat() [2/2]
template<unsigned SPATIAL_DIM>
virtual void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected], [virtual]
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Reimplemented in oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, and oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.
get_flux() [1/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_flux (const Vector< double > & s, Vector< double > & flux) const [inline]
Get flux: flux[i]=du/dx_i.
Definition at line 450 of file space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::u_index_ust_heat().
get_flux() [2/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_flux (const Vector< double > & s, Vector< double > & flux) const [inline]
Get flux: flux[i]=du/dx_i.
Definition at line 449 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::u_index_ust_heat().
get_source_ust_heat() [1/2]
template<unsigned SPATIAL_DIM>
virtual void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_source_ust_heat (const double & t, const unsigned & ipt, const Vector< double > & x, double & source) const [inline], [virtual]
Get source term at continous time t and (Eulerian) position x. Virtual so it can be overloaded in derived multi-physics elements.
Definition at line 397 of file space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Source_fct_pt, and t.
get_source_ust_heat() [2/2]
template<unsigned SPATIAL_DIM>
virtual void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_source_ust_heat (const double & t, const unsigned & ipt, const Vector< double > & x, double & source) const [inline], [virtual]
Get source term at continous time t and (Eulerian) position x. Virtual so it can be overloaded in derived multi-physics elements.
Definition at line 396 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Source_fct_pt, and t.
interpolated_du_dt_ust_heat() [1/2]
template<unsigned SPATIAL_DIM>
double oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::interpolated_du_dt_ust_heat (const Vector< double > & s) const [inline]
Return FE representation of function value du/dt(s) at local coordinate s.
Definition at line 601 of file space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::u_index_ust_heat().
Referenced by oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::du_dt_ust_heat().
interpolated_du_dt_ust_heat() [2/2]
template<unsigned SPATIAL_DIM>
double oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::interpolated_du_dt_ust_heat (const Vector< double > & s) const [inline]
Return FE representation of function value du/dt(s) at local coordinate s.
Definition at line 600 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::u_index_ust_heat().
interpolated_u_ust_heat() [1/4]
template<unsigned SPATIAL_DIM>
double oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::interpolated_u_ust_heat (const unsigned & t, const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s at previous time t (t=0: present) DRAIG: This needs to be broken; doesn't make sense in space-time elements!
Definition at line 554 of file space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), t, and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::u_index_ust_heat().
interpolated_u_ust_heat() [2/4]
template<unsigned SPATIAL_DIM>
double oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::interpolated_u_ust_heat (const unsigned & t, const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s at previous time t (t=0: present) DRAIG: This needs to be broken; doesn't make sense in space-time elements!
Definition at line 553 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), t, and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::u_index_ust_heat().
interpolated_u_ust_heat() [3/4]
template<unsigned SPATIAL_DIM>
double oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::interpolated_u_ust_heat (const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s.
Definition at line 507 of file space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::u_index_ust_heat().
Referenced by oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::scalar_value_paraview().
interpolated_u_ust_heat() [4/4]
template<unsigned SPATIAL_DIM>
double oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::interpolated_u_ust_heat (const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s.
Definition at line 506 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::u_index_ust_heat().
nscalar_paraview() [1/2]
template<unsigned SPATIAL_DIM>
unsigned oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::nscalar_paraview () const [inline], [virtual]
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
Reimplemented from oomph::FiniteElement.
Definition at line 199 of file space_time_unsteady_heat_elements.h.
nscalar_paraview() [2/2]
template<unsigned SPATIAL_DIM>
unsigned oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::nscalar_paraview () const [inline], [virtual]
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
Reimplemented from oomph::FiniteElement.
Definition at line 198 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
output() [1/8]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output (FILE * file_pt) [inline], [virtual]
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, and oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
Definition at line 146 of file space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output().
output() [2/8]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output (FILE * file_pt) [inline], [virtual]
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
Definition at line 145 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output().
output() [3/8]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output (FILE * file_pt, const unsigned & nplot) [virtual]
C-style output FE representation of soln: x,y,u or x,y,z,u at nplot^SPATIAL_DIM plot points.
C-style output function: x,t,u or x,y,t,u at nplot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, and oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
Definition at line 367 of file space_time_unsteady_heat_elements.cc.
References i, and s.
output() [4/8]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output (FILE * file_pt, const unsigned & nplot) [virtual]
C-style output FE representation of soln: x,y,u or x,y,z,u at nplot^SPATIAL_DIM plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
output() [5/8]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, and oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
Definition at line 130 of file space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output().
Referenced by oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output(), and oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output().
output() [6/8]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
Definition at line 129 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output().
output() [7/8]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: x,y,u or x,y,z,u at nplot^SPATIAL_DIM plot points.
Output function: x,t,u or x,y,t,u at nplot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, and oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
Definition at line 327 of file space_time_unsteady_heat_elements.cc.
References i, and s.
output() [8/8]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: x,y,u or x,y,z,u at nplot^SPATIAL_DIM plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
output_element_paraview() [1/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output_element_paraview (std::ofstream & outfile, const unsigned & nplot)
C-style output FE representation of soln: x,y,u or x,y,z,u at nplot^SPATIAL_DIM plot points.
Output function: x,t,u or x,y,t,u at nplot points in each coordinate direction.
Definition at line 714 of file space_time_unsteady_heat_elements.cc.
References i.
output_element_paraview() [2/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output_element_paraview (std::ofstream & outfile, const unsigned & nplot)
C-style output FE representation of soln: x,y,u or x,y,z,u at nplot^SPATIAL_DIM plot points.
output_fct() [1/4]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^SPATIAL_DIM plot points (time-dependent version)
Output exact solution at a given number of plot points: x,t,u_exact or x,y,t,u_exact Solution is provided via function pointer.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, and oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
Definition at line 464 of file space_time_unsteady_heat_elements.cc.
References i, and s.
output_fct() [2/4]
template<unsigned SPATIAL_DIM>
virtual void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^SPATIAL_DIM plot points (time-dependent version)
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, and oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
output_fct() [3/4]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^SPATIAL_DIM plot points.
Output exact solution at a given number of plot points: x,t,u_exact or x,y,t,u_exact Solution is provided via function pointer.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, and oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
Definition at line 407 of file space_time_unsteady_heat_elements.cc.
References i, and s.
Referenced by oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output_fct().
output_fct() [4/4]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^SPATIAL_DIM plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
scalar_name_paraview() [1/2]
template<unsigned SPATIAL_DIM>
std::string oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::scalar_name_paraview (const unsigned & i) const [inline], [virtual]
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc.
Reimplemented from oomph::FiniteElement.
Definition at line 356 of file space_time_unsteady_heat_elements.h.
References i.
scalar_name_paraview() [2/2]
template<unsigned SPATIAL_DIM>
std::string oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::scalar_name_paraview (const unsigned & i) const [inline], [virtual]
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc.
Reimplemented from oomph::FiniteElement.
Definition at line 355 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References i.
scalar_value_fct_paraview() [1/4]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::scalar_value_fct_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const [inline], [virtual]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
Definition at line 296 of file space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points_paraview(), and s.
scalar_value_fct_paraview() [2/4]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::scalar_value_fct_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const [inline], [virtual]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
Definition at line 295 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points_paraview(), and s.
scalar_value_fct_paraview() [3/4]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::scalar_value_fct_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const [inline], [virtual]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
Definition at line 243 of file space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points_paraview(), and s.
scalar_value_fct_paraview() [4/4]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::scalar_value_fct_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const [inline], [virtual]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
Definition at line 242 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points_paraview(), and s.
scalar_value_paraview() [1/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const [inline], [virtual]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
Definition at line 208 of file space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::get_s_plot(), i, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::interpolated_u_ust_heat(), oomph::FiniteElement::nplot_points_paraview(), and s.
scalar_value_paraview() [2/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const [inline], [virtual]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
Definition at line 207 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::FiniteElement::get_s_plot(), i, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::interpolated_u_ust_heat(), oomph::FiniteElement::nplot_points_paraview(), and s.
self_test() [1/2]
template<unsigned SPATIAL_DIM>
unsigned oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::self_test [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
Definition at line 294 of file space_time_unsteady_heat_elements.cc.
References oomph::FiniteElement::self_test().
self_test() [2/2]
template<unsigned SPATIAL_DIM>
unsigned oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::self_test () [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
source_fct_pt() [1/4]
template<unsigned SPATIAL_DIM>
SpaceTimeUnsteadyHeatSourceFctPt & oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::source_fct_pt () [inline], [virtual]
Access function: Pointer to source function.
Implements oomph::SpaceTimeUnsteadyHeatEquationsBase.
Definition at line 380 of file space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Source_fct_pt.
Referenced by oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::further_build().
source_fct_pt() [2/4]
template<unsigned SPATIAL_DIM>
SpaceTimeUnsteadyHeatSourceFctPt & oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::source_fct_pt () [inline], [virtual]
Access function: Pointer to source function.
Implements oomph::SpaceTimeUnsteadyHeatEquationsBase.
Definition at line 379 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Source_fct_pt.
source_fct_pt() [3/4]
template<unsigned SPATIAL_DIM>
SpaceTimeUnsteadyHeatSourceFctPt oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::source_fct_pt () const [inline]
Access function: Pointer to source function. Const version.
Definition at line 388 of file space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Source_fct_pt.
source_fct_pt() [4/4]
template<unsigned SPATIAL_DIM>
SpaceTimeUnsteadyHeatSourceFctPt oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::source_fct_pt () const [inline]
Access function: Pointer to source function. Const version.
Definition at line 387 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
References oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Source_fct_pt.
u_index_ust_heat() [1/2]
template<unsigned SPATIAL_DIM>
virtual unsigned oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::u_index_ust_heat () const [inline], [virtual]
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the unsteady heat equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
Definition at line 543 of file space_time_unsteady_heat_elements.h.
Referenced by oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_flux(), oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_interpolated_values(), oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_Z2_flux(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::interpolated_du_dt_ust_heat(), and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::interpolated_u_ust_heat().
u_index_ust_heat() [2/2]
template<unsigned SPATIAL_DIM>
virtual unsigned oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::u_index_ust_heat () const [inline], [virtual]
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the unsteady heat equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
Definition at line 542 of file discontinuous_galerkin_space_time_unsteady_heat_elements.h.
Member Data Documentation
ALE_is_disabled
template<unsigned SPATIAL_DIM>
bool oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::ALE_is_disabled [protected]
Boolean flag to indicate if ALE formulation is disabled when time-derivatives are computed. Only set to true if you're sure that the mesh is stationary.
Definition at line 672 of file space_time_unsteady_heat_elements.h.
Referenced by oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::disable_ALE(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::enable_ALE(), and oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::further_build().
Alpha_pt
template<unsigned SPATIAL_DIM>
double * oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Alpha_pt [protected]
Pointer to Alpha parameter (thermal inertia)
Definition at line 675 of file space_time_unsteady_heat_elements.h.
Referenced by oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::alpha(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::alpha_pt(), and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::SpaceTimeUnsteadyHeatEquations().
Beta_pt
template<unsigned SPATIAL_DIM>
double * oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Beta_pt [protected]
Pointer to Beta parameter (thermal conductivity)
Definition at line 678 of file space_time_unsteady_heat_elements.h.
Referenced by oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::beta(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::beta_pt(), and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::SpaceTimeUnsteadyHeatEquations().
Default_alpha_parameter
template<unsigned SPATIAL_DIM>
static double oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Default_alpha_parameter [static], [private]
Initial value:
=
    1.0
Static default value for the Alpha parameter (thermal inertia): One for natural scaling.
Default value for Alpha parameter (thermal inertia)
Definition at line 683 of file space_time_unsteady_heat_elements.h.
Referenced by oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::SpaceTimeUnsteadyHeatEquations().
Default_beta_parameter
template<unsigned SPATIAL_DIM>
static double oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Default_beta_parameter [static], [private]
Initial value:
=
    1.0
Static default value for the Beta parameter (thermal conductivity): One for natural scaling.
Default value for Beta parameter (thermal conductivity)
Definition at line 687 of file space_time_unsteady_heat_elements.h.
Referenced by oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::SpaceTimeUnsteadyHeatEquations().
Source_fct_pt
template<unsigned SPATIAL_DIM>
SpaceTimeUnsteadyHeatSourceFctPt oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::Source_fct_pt [protected]
Pointer to source function:
Definition at line 667 of file space_time_unsteady_heat_elements.h.
Referenced by oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::further_build(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_source_ust_heat(), and oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::source_fct_pt().
The documentation for this class was generated from the following files:
space_time_unsteady_heat_elements.h
discontinuous_galerkin_space_time_unsteady_heat_elements.h
space_time_unsteady_heat_elements.cc
discontinuous_galerkin_space_time_unsteady_heat_elements.cc