oomph::RefineableLinearWaveEquations< DIM > Class Template Reference
Refineable version of LinearWave equations.
#include <refineable_linear_wave_elements.h>
Public Member Functions
RefineableLinearWaveEquations ()
Constructor.
RefineableLinearWaveEquations (const RefineableLinearWaveEquations< DIM > &dummy)
Broken copy constructor.
void operator= (const RefineableLinearWaveEquations< DIM > &)
Broken assignment operator.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void further_build ()
Further build: Copy source function pointer from father element.
Private Member Functions
void fill_in_generic_residual_contribution_lin_wave (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Add element's contribution to elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::RefineableLinearWaveEquations< DIM >
Refineable version of LinearWave equations.
Definition at line 47 of file refineable_linear_wave_elements.h.
Constructor & Destructor Documentation
RefineableLinearWaveEquations() [1/2]
template<unsigned DIM>
oomph::RefineableLinearWaveEquations< DIM >::RefineableLinearWaveEquations () [inline]
Constructor.
Definition at line 54 of file refineable_linear_wave_elements.h.
RefineableLinearWaveEquations() [2/2]
template<unsigned DIM>
oomph::RefineableLinearWaveEquations< DIM >::RefineableLinearWaveEquations (const RefineableLinearWaveEquations< DIM > & dummy) [inline]
Broken copy constructor.
Definition at line 63 of file refineable_linear_wave_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
fill_in_generic_residual_contribution_lin_wave()
template<unsigned DIM>
void oomph::RefineableLinearWaveEquations< DIM >::fill_in_generic_residual_contribution_lin_wave (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [private], [virtual]
Add element's contribution to elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector.
Add element's contribution to the elemental residual vector and/or Jacobian matrix. flag=1: compute both flag=0: compute only residual vector
Reimplemented from oomph::LinearWaveEquations< DIM >.
Definition at line 39 of file refineable_linear_wave_elements.cc.
References i, interpolated_u(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), residuals(), s, and oomph::QuadTreeNames::W.
further_build()
template<unsigned DIM>
void oomph::RefineableLinearWaveEquations< DIM >::further_build () [inline], [virtual]
Further build: Copy source function pointer from father element.
Reimplemented from oomph::RefineableElement.
Definition at line 155 of file refineable_linear_wave_elements.h.
References oomph::RefineableElement::father_element_pt(), oomph::LinearWaveEquations< DIM >::source_fct_pt(), and oomph::LinearWaveEquations< DIM >::Source_fct_pt.
get_interpolated_values() [1/2]
template<unsigned DIM>
void oomph::RefineableLinearWaveEquations< DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
Definition at line 126 of file refineable_linear_wave_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), oomph::LinearWaveEquations< DIM >::u_index_lin_wave(), and values.
get_interpolated_values() [2/2]
template<unsigned DIM>
void oomph::RefineableLinearWaveEquations< DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 93 of file refineable_linear_wave_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), oomph::LinearWaveEquations< DIM >::u_index_lin_wave(), and values.
get_Z2_flux()
template<unsigned DIM>
void oomph::RefineableLinearWaveEquations< DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Standard flux.from LinearWave equations
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 83 of file refineable_linear_wave_elements.h.
References oomph::LinearWaveEquations< DIM >::get_flux().
num_Z2_flux_terms()
template<unsigned DIM>
unsigned oomph::RefineableLinearWaveEquations< DIM >::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 76 of file refineable_linear_wave_elements.h.
operator=()
template<unsigned DIM>
void oomph::RefineableLinearWaveEquations< DIM >::operator= (const RefineableLinearWaveEquations< DIM > &) [inline]
Broken assignment operator.
Definition at line 70 of file refineable_linear_wave_elements.h.
References oomph::BrokenCopy::broken_assign().
The documentation for this class was generated from the following files:
refineable_linear_wave_elements.h
refineable_linear_wave_elements.cc