oomph::UnstructuredTwoDMeshGeometryBase Class Reference
Contains functions which define the geometry of the mesh, i.e. regions, boundaries, etc.
#include <unstructured_two_d_mesh_geometry_base.h>
Classes
struct base_vertex_info
Data structure to store the base vertex info, initial or final vertex in the polylines have an associated base vertex.
struct vertex_connection_info
Data structure filled when the connection matrix is created, for each polyline, there are two vertex_connection_info structures, one for each end.
Public Member Functions
UnstructuredTwoDMeshGeometryBase ()
Empty constructor.
UnstructuredTwoDMeshGeometryBase (const UnstructuredTwoDMeshGeometryBase &dummy)=delete
Broken copy constructor.
void operator= (const UnstructuredTwoDMeshGeometryBase &)=delete
Broken assignment operator.
~UnstructuredTwoDMeshGeometryBase ()
Empty destructor.
unsigned nregion ()
Return the number of regions specified by attributes.
unsigned nregion_element (const unsigned &i)
Return the number of elements in the i-th region.
FiniteElement * region_element_pt (const unsigned &i, const unsigned &e)
Return the e-th element in the i-th region.
unsigned nregion_attribute ()
Return the number of attributes used in the mesh.
double region_attribute (const unsigned &i)
Return the attribute associated with region i.
GeomObject * boundary_geom_object_pt (const unsigned &b)
Return the geometric object associated with the b-th boundary or null if the boundary has associated geometric object.
std::map< unsigned, GeomObject * > & boundary_geom_object_pt ()
Return direct access to the geometric object storage.
std::map< unsigned, Vector< double > > & boundary_coordinate_limits ()
Return access to the vector of boundary coordinates associated with each geometric object.
Vector< double > & boundary_coordinate_limits (const unsigned &b)
Return access to the coordinate limits associated with the geometric object associated with boundary b.
unsigned nboundary_element_in_region (const unsigned &b, const unsigned &r) const
Return the number of elements adjacent to boundary b in region r.
FiniteElement * boundary_element_in_region_pt (const unsigned &b, const unsigned &r, const unsigned &e) const
Return pointer to the e-th element adjacent to boundary b in region r.
int face_index_at_boundary_in_region (const unsigned &b, const unsigned &r, const unsigned &e) const
Return face index of the e-th element adjacent to boundary b in region r.
TriangleMeshPolyLine * boundary_polyline_pt (const unsigned &b)
Return pointer to the current polyline that describes the b-th mesh boundary.
std::map< unsigned, std::set< Node * > > & nodes_on_boundary_pt ()
Gets a pointer to a set with all the nodes related with a boundary.
const bool get_connected_vertex_number_on_destination_polyline (TriangleMeshPolyLine *dst_polyline_pt, Vector< double > &vertex_coordinates, unsigned &vertex_number)
Gets the vertex number on the destination polyline (used to create the connections among shared boundaries)
void check_contiguousness_on_polylines_helper (Vector< TriangleMeshPolyLine * > &polylines_pt, unsigned &index)
Sort the polylines coming from joining them. Check whether it is necessary to reverse them or not. Used when joining two curve polylines in order to create a polygon.
void check_contiguousness_on_polylines_helper (Vector< TriangleMeshPolyLine * > &polylines_pt, unsigned &index_halo_start, unsigned &index_halo_end)
Sort the polylines coming from joining them. Check whether it is necessary to reverse them or not. Used when joining polylines and they still do not create a polygon.
bool is_point_inside_polygon_helper (Vector< Vector< double > > polygon_vertices, Vector< double > point)
Helper function that checks if a given point is inside a polygon (a set of sorted vertices that connected create a polygon)
void enable_automatic_creation_of_vertices_on_boundaries ()
Enables the creation of points (by Triangle) on the outer and internal boundaries.
void disable_automatic_creation_of_vertices_on_boundaries ()
Disables the creation of points (by Triangle) on the outer and internal boundaries.
bool is_automatic_creation_of_vertices_on_boundaries_allowed ()
Returns the status of the variable Allow_automatic_creation_of_vertices_on_boundaries.
void flush_boundary_segment_node (const unsigned &b)
Flush the boundary segment node storage.
void set_nboundary_segment_node (const unsigned &b, const unsigned &s)
Set the number of segments associated with a boundary.
unsigned nboundary_segment (const unsigned &b)
Return the number of segments associated with a boundary.
unsigned long nboundary_segment_node (const unsigned &b)
Return the number of segments associated with a boundary.
unsigned long nboundary_segment_node (const unsigned &b, const unsigned &s)
Return the number of nodes associated with a given segment of a boundary.
void add_boundary_segment_node (const unsigned &b, const unsigned &s, Node *const &node_pt)
Add the node node_pt to the b-th boundary and the s-th segment of the mesh.
std::map< unsigned, Vector< double > > & boundary_initial_coordinate ()
Return direct access to the initial coordinates of a boundary.
std::map< unsigned, Vector< double > > & boundary_final_coordinate ()
Return direct access to the final coordinates of a boundary.
std::map< unsigned, Vector< double > > & boundary_initial_zeta_coordinate ()
Return direct access to the initial zeta coordinate of a boundary.
std::map< unsigned, Vector< double > > & boundary_final_zeta_coordinate ()
Return direct access to the final zeta coordinates of a boundary.
std::map< unsigned, Vector< unsigned > > & boundary_segment_inverted ()
Return the info. to know if it is necessary to reverse the segment based on a previous mesh.
std::map< unsigned, Vector< Vector< double > > > & boundary_segment_initial_coordinate ()
Return direct access to the initial coordinates for the segments that are part of a boundary.
std::map< unsigned, Vector< Vector< double > > > & boundary_segment_final_coordinate ()
Return direct access to the final coordinates for the segments that are part of a boundary.
std::map< unsigned, Vector< double > > & boundary_segment_initial_arclength ()
Return direct access to the initial arclength for the segments that are part of a boundary.
std::map< unsigned, Vector< double > > & boundary_segment_final_arclength ()
Return direct access to the final arclength for the segments that are part of a boundary.
std::map< unsigned, Vector< double > > & boundary_segment_initial_zeta ()
Return direct access to the initial zeta for the segments that are part of a boundary.
std::map< unsigned, Vector< double > > & boundary_segment_final_zeta ()
Return direct access to the final zeta for the segments that are part of a boundary.
Vector< double > & boundary_segment_initial_zeta (const unsigned &b)
Return the initial zeta for the segments that are part of a boundary.
Vector< double > & boundary_segment_final_zeta (const unsigned &b)
Return the final zeta for the segments that are part of a boundary.
Vector< double > & boundary_initial_coordinate (const unsigned &b)
Return the initial coordinates for the boundary.
Vector< double > & boundary_final_coordinate (const unsigned &b)
Return the final coordinates for the boundary.
const Vector< unsigned > boundary_segment_inverted (const unsigned &b) const
Return the info. to know if it is necessary to reverse the segment based on a previous mesh.
Vector< unsigned > & boundary_segment_inverted (const unsigned &b)
Return the info. to know if it is necessary to reverse the segment based on a previous mesh.
Vector< double > & boundary_initial_zeta_coordinate (const unsigned &b)
Return the initial zeta coordinate for the boundary.
Vector< double > & boundary_final_zeta_coordinate (const unsigned &b)
Return the final zeta coordinate for the boundary.
Vector< double > & boundary_segment_initial_arclength (const unsigned &b)
Return the initial arclength for the segments that are part of a boundary.
Vector< double > & boundary_segment_final_arclength (const unsigned &b)
Return the final arclength for the segments that are part of a boundary.
Vector< Vector< double > > & boundary_segment_initial_coordinate (const unsigned &b)
Return the initial coordinates for the segments that are part of a boundary.
Vector< Vector< double > > & boundary_segment_final_coordinate (const unsigned &b)
Return the final coordinates for the segments that are part of a boundary.
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b)
Setup boundary coordinate on boundary b. Boundary coordinate increases continously along polygonal boundary. It's zero at the lowest left node on the boundary.
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, std::ofstream &outfile)
Setup boundary coordinate on boundary b. Doc Faces in outfile. Boundary coordinate increases continously along polygonal boundary. It's zero at the lowest left node on the boundary.
Public Attributes
std::map< unsigned, bool > Assigned_segments_initial_zeta_values
Flag used at the setup_boundary_coordinate function to know if initial zeta values for segments have been assigned.
Static Public Attributes
static bool Suppress_warning_about_regions_and_boundaries = true
Public static flag to suppress warning; defaults to false.
Protected Member Functions
void build_triangulateio (Vector< TriangleMeshPolygon * > &outer_polygons_pt, Vector< TriangleMeshPolygon * > &internal_polygons_pt, Vector< TriangleMeshOpenCurve * > &open_curves_pt, Vector< Vector< double > > &extra_holes_coordinates, std::map< unsigned, Vector< double > > &regions_coordinates, std::map< unsigned, double > &regions_areas, TriangulateIO &triangulate_io)
Create TriangulateIO object from outer boundaries, internal boundaries, and open curves. Add the holes and regions information as well.
void add_connection_matrix_info_helper (TriangleMeshPolyLine *polyline_pt, std::map< unsigned, std::map< unsigned, Vector< vertex_connection_info > > > &connection_matrix, TriangleMeshPolyLine *next_polyline_pt=0)
Helps to add information to the connection matrix of the given polyline.
void initialise_base_vertex (TriangleMeshPolyLine *polyline_pt, std::map< unsigned, std::map< unsigned, Vector< base_vertex_info > > > &base_vertices)
Initialise the base vertex structure, set every vertex to no visited and not being a base vertex.
void add_base_vertex_info_helper (TriangleMeshPolyLine *polyline_pt, std::map< unsigned, std::map< unsigned, Vector< base_vertex_info > > > &base_vertices, std::map< unsigned, std::map< unsigned, Vector< vertex_connection_info > > > &connection_matrix, std::map< unsigned, std::map< unsigned, unsigned > > &boundary_chunk_nvertices)
Helps to identify the base vertex of the given polyline.
void snap_nodes_onto_geometric_objects ()
Snap the boundary nodes onto any curvilinear boundaries defined by geometric objects.
void copy_connection_information (TriangleMeshCurveSection *input_curve_pt, TriangleMeshCurveSection *output_curve_pt)
Helper function to copy the connection information from the input curve(polyline or curviline) to the output polyline.
void copy_connection_information_to_sub_polylines (TriangleMeshCurveSection *input_curve_pt, TriangleMeshCurveSection *output_curve_pt)
Helper function to copy the connection information from the input curve(polyline or curviline) to the output sub-polyline.
void create_vertex_coordinates_for_polyline_no_connections (TriangleMeshCurviLine *boundary_pt, Vector< Vector< double > > &vertex_coord, Vector< std::pair< double, double > > &polygonal_vertex_arclength_info)
Helper function to create polyline vertex coordinates for curvilinear boundary specified by boundary_pt, using either equal increments in zeta or in (approximate) arclength along the curviline. vertex_coord[i_vertex][i_dim] stores i_dim-th coordinate of i_vertex-th vertex. polygonal_vertex_arclength_info[i_vertex] contains the pair of doubles made of the arclength of the i_vertex-th vertex along the polygonal representation (.first), and the corresponding coordinate on the GeomObject (.second)
void create_vertex_coordinates_for_polyline_connections (TriangleMeshCurviLine *boundary_pt, Vector< Vector< double > > &vertex_coord, Vector< std::pair< double, double > > &polygonal_vertex_arclength_info)
Helper function to create polyline vertex coordinates for curvilinear boundary specified by boundary_pt, using either equal increments in zeta or in (approximate) arclength along the curviline. vertex_coord[i_vertex][i_dim] stores i_dim-th coordinate of i_vertex-th vertex. polygonal_vertex_arclength_info[i_vertex] contains the pair of doubles made of the arclength of the i_vertex-th vertex along the polygonal representation (.first), and the corresponding coordinate on the GeomObject (.second)
TriangleMeshPolygon * closed_curve_to_polygon_helper (TriangleMeshClosedCurve *closed_curve_pt, unsigned &max_bnd_id_local)
Helper function that returns a polygon representation for the given closed curve, it also computes the maximum boundary id of the constituent curves. If the TriangleMeshClosedCurve is already a TriangleMeshPolygon we simply return a pointer to it. Otherwise a new TrilangleMeshPolygon is created -- this is deleted automatically when the TriangleMesh destructor is called, so no external book-keeping is required.
TriangleMeshOpenCurve * create_open_curve_with_polyline_helper (TriangleMeshOpenCurve *open_curve_pt, unsigned &max_bnd_id_local)
Helper function that creates and returns an open curve with the polyline representation of its constituent curve sections. The new created open curve is deleted when the TriangleMesh destructor is called.
void set_geom_objects_and_coordinate_limits_for_close_curve (TriangleMeshClosedCurve *input_closed_curve_pt)
Stores the geometric objects associated to the curve sections that compound the closed curve. It also stores the limits defined by these geometric objects.
void set_geom_objects_and_coordinate_limits_for_open_curve (TriangleMeshOpenCurve *input_open_curve_pt)
Stores the geometric objects associated to the curve sections that compound the open curve. It also stores the limits defined by these geometric objects.
Protected Attributes
std::map< unsigned, Vector< Vector< Node * > > > Boundary_segment_node_pt
Used to store the nodes associated to a boundary and to an specific segment (this only applies in distributed meshes where the boundary is splitted in segments)
std::map< unsigned, Vector< double > > Boundary_segment_initial_zeta
Stores the initial zeta coordinate for the segments that appear when a boundary is splited among processors.
std::map< unsigned, Vector< double > > Boundary_segment_final_zeta
Stores the final zeta coordinate for the segments that appear when a boundary is splited among processors.
std::map< unsigned, Vector< double > > Boundary_initial_coordinate
Stores the initial coordinates for the boundary.
std::map< unsigned, Vector< double > > Boundary_final_coordinate
Stores the final coordinates for the boundary.
std::map< unsigned, Vector< unsigned > > Boundary_segment_inverted
Stores the info. to know if it is necessary to reverse the segment based on a previous mesh.
std::map< unsigned, Vector< double > > Boundary_initial_zeta_coordinate
Stores the initial zeta coordinate for the boundary.
std::map< unsigned, Vector< double > > Boundary_final_zeta_coordinate
Stores the final zeta coordinate for the boundary.
std::map< unsigned, Vector< double > > Boundary_segment_initial_arclength
Stores the initial arclength for the segments that appear when a boundary is splited among processors.
std::map< unsigned, Vector< double > > Boundary_segment_final_arclength
Stores the final arclength for the segments that appear when a boundary is splited among processors.
std::map< unsigned, Vector< Vector< double > > > Boundary_segment_initial_coordinate
Stores the initial coordinates for the segments that appear when a boundary is splited among processors.
std::map< unsigned, Vector< Vector< double > > > Boundary_segment_final_coordinate
Stores the final coordinates for the segments that appear when a boundary is splited among processors.
bool Allow_automatic_creation_of_vertices_on_boundaries
Flag to indicate whether the automatic creation of vertices along the boundaries by Triangle is allowed.
std::map< unsigned, Vector< FiniteElement * > > Region_element_pt
Vector of elements in each region differentiated by attribute (the key of the map is the attribute)
Vector< double > Region_attribute
Vector of attributes associated with the elements in each region.
std::map< unsigned, GeomObject * > Boundary_geom_object_pt
Storage for the geometric objects associated with any boundaries.
std::map< unsigned, Vector< double > > Boundary_coordinate_limits
Storage for the limits of the boundary coordinates defined by the use of geometric objects. Only used for curvilinear boundaries.
Vector< TriangleMeshPolygon * > Outer_boundary_pt
Polygon that defines outer boundaries.
Vector< TriangleMeshPolygon * > Internal_polygon_pt
Vector of polygons that define internal polygons.
Vector< TriangleMeshOpenCurve * > Internal_open_curve_pt
Vector of open polylines that define internal curves.
Vector< Vector< double > > Extra_holes_coordinates
Storage for extra coordinates for holes.
std::map< unsigned, Vector< double > > Regions_coordinates
Storage for extra coordinates for regions. The key on the map is the region id.
std::map< unsigned, TriangleMeshCurveSection * > Boundary_curve_section_pt
A map that stores the associated curve section of the specified boundary id.
Vector< std::map< unsigned, Vector< FiniteElement * > > > Boundary_region_element_pt
Storage for elements adjacent to a boundary in a particular region.
Vector< std::map< unsigned, Vector< int > > > Face_index_region_at_boundary
Storage for the face index adjacent to a boundary in a particular region.
std::map< unsigned, Vector< std::pair< double, double > > > Polygonal_vertex_arclength_info
Storage for pairs of doubles representing: .first: the arclength along the polygonal representation of the curviline .second: the corresponding intrinsic coordinate on the associated geometric object at which the vertices on the specified boundary are located. Only used for boundaries represented by geom objects.
std::map< unsigned, std::set< Node * > > Nodes_on_boundary_pt
Stores a pointer to a set with all the nodes related with a boundary.
std::set< TriangleMeshCurveSection * > Free_curve_section_pt
A set that contains the curve sections created by this object therefore it is necessary to free their associated memory.
std::set< TriangleMeshPolygon * > Free_polygon_pt
A set that contains the polygons created by this object therefore it is necessary to free their associated memory.
std::set< TriangleMeshOpenCurve * > Free_open_curve_pt
A set that contains the open curves created by this object therefore it is necessary to free their associated memory.
bool Immersed_rigid_body_triangle_mesh_polygon_used
Private Member Functions
TriangleMeshCurveSection * curviline_to_polyline (TriangleMeshCurviLine *&curviline_pt, unsigned &bnd_id)
Helper function that creates the associated polyline representation for curvilines.
unsigned get_associated_vertex_to_svalue (double &target_s_value, unsigned &bnd_id)
Get the associated vertex to the given s value by looking to the list of s values created when changing from curviline to polyline.
unsigned get_associated_vertex_to_svalue (double &target_s_value, unsigned &bnd_id, double &s_tolerance)
Get the associated vertex to the given s value by looking to the list of s values created when changing from curviline to polyline.
Additional Inherited Members
Detailed Description
Contains functions which define the geometry of the mesh, i.e. regions, boundaries, etc.
Definition at line 1737 of file unstructured_two_d_mesh_geometry_base.h.
Constructor & Destructor Documentation
UnstructuredTwoDMeshGeometryBase() [1/2]
oomph::UnstructuredTwoDMeshGeometryBase::UnstructuredTwoDMeshGeometryBase () [inline]
Empty constructor.
Definition at line 1744 of file unstructured_two_d_mesh_geometry_base.h.
UnstructuredTwoDMeshGeometryBase() [2/2]
oomph::UnstructuredTwoDMeshGeometryBase::UnstructuredTwoDMeshGeometryBase (const UnstructuredTwoDMeshGeometryBase & dummy) [delete]
Broken copy constructor.
 UnstructuredTwoDMeshGeometryBase()
oomph::UnstructuredTwoDMeshGeometryBase::~UnstructuredTwoDMeshGeometryBase () [inline]
Empty destructor.
Definition at line 1754 of file unstructured_two_d_mesh_geometry_base.h.
Member Function Documentation
add_base_vertex_info_helper()
void oomph::UnstructuredTwoDMeshGeometryBase::add_base_vertex_info_helper (TriangleMeshPolyLine * polyline_pt, std::map< unsigned, std::map< unsigned, Vector< base_vertex_info > > > & base_vertices, std::map< unsigned, std::map< unsigned, Vector< vertex_connection_info > > > & connection_matrix, std::map< unsigned, std::map< unsigned, unsigned > > & boundary_chunk_nvertices) [protected]
Helps to identify the base vertex of the given polyline.
Definition at line 3578 of file unstructured_two_d_mesh_geometry_base.cc.
References oomph::TriangleMeshPolyLine::boundary_chunk(), oomph::UnstructuredTwoDMeshGeometryBase::base_vertex_info::boundary_chunk, oomph::UnstructuredTwoDMeshGeometryBase::vertex_connection_info::boundary_chunk_to_connect, oomph::TriangleMeshPolyLine::boundary_id(), oomph::UnstructuredTwoDMeshGeometryBase::base_vertex_info::boundary_id, oomph::UnstructuredTwoDMeshGeometryBase::vertex_connection_info::boundary_id_to_connect, oomph::UnstructuredTwoDMeshGeometryBase::base_vertex_info::has_base_vertex_assigned, oomph::UnstructuredTwoDMeshGeometryBase::base_vertex_info::is_base_vertex, oomph::UnstructuredTwoDMeshGeometryBase::vertex_connection_info::is_connected, oomph::TriangleMeshPolyLine::nvertex(), oomph::UnstructuredTwoDMeshGeometryBase::base_vertex_info::vertex_number, and oomph::UnstructuredTwoDMeshGeometryBase::vertex_connection_info::vertex_number_to_connect.
Referenced by build_triangulateio().
add_boundary_segment_node()
void oomph::UnstructuredTwoDMeshGeometryBase::add_boundary_segment_node (const unsigned & b, const unsigned & s, Node *const & node_pt) [inline]
Add the node node_pt to the b-th boundary and the s-th segment of the mesh.
Definition at line 2046 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_node_pt, nboundary_segment_node(), oomph::Mesh::node_pt(), and s.
Referenced by setup_boundary_coordinates().
add_connection_matrix_info_helper()
void oomph::UnstructuredTwoDMeshGeometryBase::add_connection_matrix_info_helper (TriangleMeshPolyLine * polyline_pt, std::map< unsigned, std::map< unsigned, Vector< vertex_connection_info > > > & connection_matrix, TriangleMeshPolyLine * next_polyline_pt = 0) [protected]
Helps to add information to the connection matrix of the given polyline.
Definition at line 3415 of file unstructured_two_d_mesh_geometry_base.cc.
References oomph::TriangleMeshPolyLine::boundary_chunk(), oomph::UnstructuredTwoDMeshGeometryBase::vertex_connection_info::boundary_chunk_to_connect, oomph::TriangleMeshPolyLine::boundary_id(), oomph::UnstructuredTwoDMeshGeometryBase::vertex_connection_info::boundary_id_to_connect, oomph::TriangleMeshCurveSection::final_vertex_connected_bnd_id(), oomph::TriangleMeshCurveSection::final_vertex_connected_n_chunk(), oomph::TriangleMeshCurveSection::final_vertex_connected_n_vertex(), oomph::TriangleMeshCurveSection::initial_vertex_connected_bnd_id(), oomph::TriangleMeshCurveSection::initial_vertex_connected_n_chunk(), oomph::TriangleMeshCurveSection::initial_vertex_connected_n_vertex(), oomph::UnstructuredTwoDMeshGeometryBase::vertex_connection_info::is_connected, oomph::TriangleMeshCurveSection::is_final_vertex_connected(), oomph::TriangleMeshCurveSection::is_initial_vertex_connected(), and oomph::UnstructuredTwoDMeshGeometryBase::vertex_connection_info::vertex_number_to_connect.
Referenced by build_triangulateio().
boundary_coordinate_limits() [1/2]
std::map< unsigned, Vector< double > > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_coordinate_limits () [inline]
Return access to the vector of boundary coordinates associated with each geometric object.
Definition at line 1849 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_coordinate_limits.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::adapt(), and setup_boundary_coordinates().
boundary_coordinate_limits() [2/2]
Vector< double > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_coordinate_limits (const unsigned & b) [inline]
Return access to the coordinate limits associated with the geometric object associated with boundary b.
Definition at line 1856 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_coordinate_limits.
boundary_element_in_region_pt()
FiniteElement * oomph::UnstructuredTwoDMeshGeometryBase::boundary_element_in_region_pt (const unsigned & b, const unsigned & r, const unsigned & e) const [inline]
Return pointer to the e-th element adjacent to boundary b in region r.
Definition at line 1893 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_region_element_pt, and e.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::adapt(), and setup_boundary_coordinates().
boundary_final_coordinate() [1/2]
std::map< unsigned, Vector< double > > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_final_coordinate () [inline]
Return direct access to the final coordinates of a boundary.
Definition at line 2082 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_final_coordinate.
Referenced by oomph::TriangleMesh< ELEMENT >::identify_boundary_segments_and_assign_initial_zeta_values(), and setup_boundary_coordinates().
boundary_final_coordinate() [2/2]
Vector< double > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_final_coordinate (const unsigned & b) [inline]
Return the final coordinates for the boundary.
Definition at line 2221 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_final_coordinate.
boundary_final_zeta_coordinate() [1/2]
std::map< unsigned, Vector< double > > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_final_zeta_coordinate () [inline]
Return direct access to the final zeta coordinates of a boundary.
Definition at line 2096 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_final_zeta_coordinate.
Referenced by oomph::TriangleMesh< ELEMENT >::identify_boundary_segments_and_assign_initial_zeta_values(), and setup_boundary_coordinates().
boundary_final_zeta_coordinate() [2/2]
Vector< double > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_final_zeta_coordinate (const unsigned & b) [inline]
Return the final zeta coordinate for the boundary.
Definition at line 2316 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_final_zeta_coordinate.
boundary_geom_object_pt() [1/2]
std::map< unsigned, GeomObject * > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_geom_object_pt () [inline]
Return direct access to the geometric object storage.
Definition at line 1842 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_geom_object_pt.
Referenced by setup_boundary_coordinates(), and snap_nodes_onto_geometric_objects().
boundary_geom_object_pt() [2/2]
GeomObject * oomph::UnstructuredTwoDMeshGeometryBase::boundary_geom_object_pt (const unsigned & b) [inline]
Return the geometric object associated with the b-th boundary or null if the boundary has associated geometric object.
Definition at line 1827 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_geom_object_pt.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::adapt().
boundary_initial_coordinate() [1/2]
std::map< unsigned, Vector< double > > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_initial_coordinate () [inline]
Return direct access to the initial coordinates of a boundary.
Definition at line 2076 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_initial_coordinate.
Referenced by oomph::TriangleMesh< ELEMENT >::identify_boundary_segments_and_assign_initial_zeta_values(), and setup_boundary_coordinates().
boundary_initial_coordinate() [2/2]
Vector< double > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_initial_coordinate (const unsigned & b) [inline]
Return the initial coordinates for the boundary.
Definition at line 2199 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_initial_coordinate.
boundary_initial_zeta_coordinate() [1/2]
std::map< unsigned, Vector< double > > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_initial_zeta_coordinate () [inline]
Return direct access to the initial zeta coordinate of a boundary.
Definition at line 2089 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_initial_zeta_coordinate.
Referenced by oomph::TriangleMesh< ELEMENT >::identify_boundary_segments_and_assign_initial_zeta_values(), and setup_boundary_coordinates().
boundary_initial_zeta_coordinate() [2/2]
Vector< double > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_initial_zeta_coordinate (const unsigned & b) [inline]
Return the initial zeta coordinate for the boundary.
Definition at line 2292 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_initial_zeta_coordinate.
boundary_polyline_pt()
TriangleMeshPolyLine * oomph::UnstructuredTwoDMeshGeometryBase::boundary_polyline_pt (const unsigned & b) [inline]
Return pointer to the current polyline that describes the b-th mesh boundary.
Definition at line 1937 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_curve_section_pt.
boundary_segment_final_arclength() [1/2]
std::map< unsigned, Vector< double > > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_segment_final_arclength () [inline]
Return direct access to the final arclength for the segments that are part of a boundary.
Definition at line 2131 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_final_arclength.
Referenced by oomph::TriangleMesh< ELEMENT >::identify_boundary_segments_and_assign_initial_zeta_values(), and setup_boundary_coordinates().
boundary_segment_final_arclength() [2/2]
Vector< double > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_segment_final_arclength (const unsigned & b) [inline]
Return the final arclength for the segments that are part of a boundary.
Definition at line 2364 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_final_arclength.
boundary_segment_final_coordinate() [1/2]
std::map< unsigned, Vector< Vector< double > > > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_segment_final_coordinate () [inline]
Return direct access to the final coordinates for the segments that are part of a boundary.
Definition at line 2117 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_final_coordinate.
Referenced by oomph::TriangleMesh< ELEMENT >::identify_boundary_segments_and_assign_initial_zeta_values(), and setup_boundary_coordinates().
boundary_segment_final_coordinate() [2/2]
Vector< Vector< double > > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_segment_final_coordinate (const unsigned & b) [inline]
Return the final coordinates for the segments that are part of a boundary.
Definition at line 2413 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_final_coordinate.
boundary_segment_final_zeta() [1/2]
std::map< unsigned, Vector< double > > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_segment_final_zeta () [inline]
Return direct access to the final zeta for the segments that are part of a boundary.
Definition at line 2145 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_final_zeta.
Referenced by oomph::TriangleMesh< ELEMENT >::identify_boundary_segments_and_assign_initial_zeta_values(), and setup_boundary_coordinates().
boundary_segment_final_zeta() [2/2]
Vector< double > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_segment_final_zeta (const unsigned & b) [inline]
Return the final zeta for the segments that are part of a boundary.
Definition at line 2176 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_final_zeta.
boundary_segment_initial_arclength() [1/2]
std::map< unsigned, Vector< double > > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_segment_initial_arclength () [inline]
Return direct access to the initial arclength for the segments that are part of a boundary.
Definition at line 2124 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_initial_arclength.
Referenced by oomph::TriangleMesh< ELEMENT >::identify_boundary_segments_and_assign_initial_zeta_values(), and setup_boundary_coordinates().
boundary_segment_initial_arclength() [2/2]
Vector< double > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_segment_initial_arclength (const unsigned & b) [inline]
Return the initial arclength for the segments that are part of a boundary.
Definition at line 2340 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_initial_arclength.
boundary_segment_initial_coordinate() [1/2]
std::map< unsigned, Vector< Vector< double > > > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_segment_initial_coordinate () [inline]
Return direct access to the initial coordinates for the segments that are part of a boundary.
Definition at line 2110 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_initial_coordinate.
Referenced by oomph::TriangleMesh< ELEMENT >::identify_boundary_segments_and_assign_initial_zeta_values(), and setup_boundary_coordinates().
boundary_segment_initial_coordinate() [2/2]
Vector< Vector< double > > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_segment_initial_coordinate (const unsigned & b) [inline]
Return the initial coordinates for the segments that are part of a boundary.
Definition at line 2388 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_initial_coordinate.
boundary_segment_initial_zeta() [1/2]
std::map< unsigned, Vector< double > > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_segment_initial_zeta () [inline]
Return direct access to the initial zeta for the segments that are part of a boundary.
Definition at line 2138 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_initial_zeta.
Referenced by oomph::TriangleMesh< ELEMENT >::identify_boundary_segments_and_assign_initial_zeta_values(), and setup_boundary_coordinates().
boundary_segment_initial_zeta() [2/2]
Vector< double > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_segment_initial_zeta (const unsigned & b) [inline]
Return the initial zeta for the segments that are part of a boundary.
Definition at line 2152 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_initial_zeta.
boundary_segment_inverted() [1/3]
std::map< unsigned, Vector< unsigned > > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_segment_inverted () [inline]
Return the info. to know if it is necessary to reverse the segment based on a previous mesh.
Definition at line 2103 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_inverted.
Referenced by setup_boundary_coordinates().
boundary_segment_inverted() [2/3]
Vector< unsigned > & oomph::UnstructuredTwoDMeshGeometryBase::boundary_segment_inverted (const unsigned & b) [inline]
Return the info. to know if it is necessary to reverse the segment based on a previous mesh.
Definition at line 2269 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_inverted.
boundary_segment_inverted() [3/3]
const Vector< unsigned > oomph::UnstructuredTwoDMeshGeometryBase::boundary_segment_inverted (const unsigned & b) const [inline]
Return the info. to know if it is necessary to reverse the segment based on a previous mesh.
Definition at line 2245 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_inverted.
build_triangulateio()
void oomph::UnstructuredTwoDMeshGeometryBase::build_triangulateio (Vector< TriangleMeshPolygon * > & outer_polygons_pt, Vector< TriangleMeshPolygon * > & internal_polygons_pt, Vector< TriangleMeshOpenCurve * > & open_curves_pt, Vector< Vector< double > > & extra_holes_coordinates, std::map< unsigned, Vector< double > > & regions_coordinates, std::map< unsigned, double > & regions_areas, TriangulateIO & triangulate_io) [protected]
Create TriangulateIO object from outer boundaries, internal boundaries, and open curves. Add the holes and regions information as well.
Definition at line 1905 of file unstructured_two_d_mesh_geometry_base.cc.
References add_base_vertex_info_helper(), add_connection_matrix_info_helper(), oomph::TriangleMeshPolyLine::boundary_chunk(), oomph::UnstructuredTwoDMeshGeometryBase::base_vertex_info::boundary_chunk, oomph::TriangleMeshPolyLine::boundary_id(), oomph::UnstructuredTwoDMeshGeometryBase::base_vertex_info::boundary_id, oomph::UnstructuredTwoDMeshGeometryBase::base_vertex_info::has_base_vertex_assigned, oomph::TriangulateIO::holelist, i, initialise_base_vertex(), oomph::TriangleHelper::initialise_triangulateio(), oomph::UnstructuredTwoDMeshGeometryBase::base_vertex_info::is_base_vertex, oomph::TriangulateIO::numberofholes, oomph::TriangulateIO::numberofpoints, oomph::TriangulateIO::numberofregions, oomph::TriangulateIO::numberofsegments, oomph::TriangleMeshPolyLine::nvertex(), oomph::TriangulateIO::pointlist, oomph::TriangulateIO::regionlist, oomph::TriangulateIO::segmentlist, oomph::TriangulateIO::segmentmarkerlist, oomph::Global_string_for_annotation::string(), oomph::TriangleMeshPolyLine::vertex_coordinate(), and oomph::UnstructuredTwoDMeshGeometryBase::base_vertex_info::vertex_number.
Referenced by oomph::QuadFromTriangleMesh< ELEMENT >::generic_constructor(), and oomph::TriangleMesh< ELEMENT >::generic_constructor().
check_contiguousness_on_polylines_helper() [1/2]
void oomph::UnstructuredTwoDMeshGeometryBase::check_contiguousness_on_polylines_helper (Vector< TriangleMeshPolyLine * > & polylines_pt, unsigned & index)
Sort the polylines coming from joining them. Check whether it is necessary to reverse them or not. Used when joining two curve polylines in order to create a polygon.
check_contiguousness_on_polylines_helper() [2/2]
void oomph::UnstructuredTwoDMeshGeometryBase::check_contiguousness_on_polylines_helper (Vector< TriangleMeshPolyLine * > & polylines_pt, unsigned & index_halo_start, unsigned & index_halo_end)
Sort the polylines coming from joining them. Check whether it is necessary to reverse them or not. Used when joining polylines and they still do not create a polygon.
closed_curve_to_polygon_helper()
TriangleMeshPolygon * oomph::UnstructuredTwoDMeshGeometryBase::closed_curve_to_polygon_helper (TriangleMeshClosedCurve * closed_curve_pt, unsigned & max_bnd_id_local) [inline], [protected]
Helper function that returns a polygon representation for the given closed curve, it also computes the maximum boundary id of the constituent curves. If the TriangleMeshClosedCurve is already a TriangleMeshPolygon we simply return a pointer to it. Otherwise a new TrilangleMeshPolygon is created -- this is deleted automatically when the TriangleMesh destructor is called, so no external book-keeping is required.
Definition at line 3345 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_curve_section_pt, oomph::TriangleMeshCurviLine::boundary_id(), oomph::TriangleMeshPolyLine::boundary_id(), oomph::TriangleMeshCurve::curve_section_pt(), curviline_to_polyline(), Free_curve_section_pt, Free_polygon_pt, oomph::TriangleMeshClosedCurve::internal_point(), oomph::TriangleMeshClosedCurve::is_internal_point_fixed(), oomph::TriangleMeshCurveSection::maximum_length(), oomph::TriangleMeshCurve::ncurve_section(), oomph::TriangleMeshCurve::polyline_refinement_tolerance(), oomph::TriangleMeshCurve::polyline_unrefinement_tolerance(), oomph::TriangleMeshCurveSection::refinement_tolerance(), oomph::TriangleMeshCurve::set_polyline_refinement_tolerance(), oomph::TriangleMeshCurve::set_polyline_unrefinement_tolerance(), and oomph::TriangleMeshCurveSection::unrefinement_tolerance().
Referenced by oomph::QuadFromTriangleMesh< ELEMENT >::QuadFromTriangleMesh(), and oomph::TriangleMesh< ELEMENT >::TriangleMesh().
copy_connection_information()
void oomph::UnstructuredTwoDMeshGeometryBase::copy_connection_information (TriangleMeshCurveSection * input_curve_pt, TriangleMeshCurveSection * output_curve_pt) [protected]
Helper function to copy the connection information from the input curve(polyline or curviline) to the output polyline.
Definition at line 4172 of file unstructured_two_d_mesh_geometry_base.cc.
References oomph::TriangleMeshCurveSection::final_s_connection_value(), oomph::TriangleMeshCurveSection::final_vertex_connected_bnd_id(), oomph::TriangleMeshCurveSection::final_vertex_connected_n_chunk(), oomph::TriangleMeshCurveSection::final_vertex_connected_n_vertex(), oomph::TriangleMeshCurveSection::final_vertex_coordinate(), get_associated_vertex_to_svalue(), oomph::TriangleMeshCurveSection::initial_s_connection_value(), oomph::TriangleMeshCurveSection::initial_vertex_connected_bnd_id(), oomph::TriangleMeshCurveSection::initial_vertex_connected_n_chunk(), oomph::TriangleMeshCurveSection::initial_vertex_connected_n_vertex(), oomph::TriangleMeshCurveSection::initial_vertex_coordinate(), oomph::TriangleMeshCurveSection::is_final_vertex_connected(), oomph::TriangleMeshCurveSection::is_final_vertex_connected_to_curviline(), oomph::TriangleMeshCurveSection::is_initial_vertex_connected(), oomph::TriangleMeshCurveSection::is_initial_vertex_connected_to_curviline(), oomph::TriangleMeshCurveSection::set_final_vertex_connected(), oomph::TriangleMeshCurveSection::set_initial_vertex_connected(), oomph::TriangleMeshCurveSection::tolerance_for_s_connection(), oomph::TriangleMeshCurveSection::unset_final_vertex_connected_to_curviline(), and oomph::TriangleMeshCurveSection::unset_initial_vertex_connected_to_curviline().
Referenced by create_open_curve_with_polyline_helper().
copy_connection_information_to_sub_polylines()
void oomph::UnstructuredTwoDMeshGeometryBase::copy_connection_information_to_sub_polylines (TriangleMeshCurveSection * input_curve_pt, TriangleMeshCurveSection * output_curve_pt) [protected]
Helper function to copy the connection information from the input curve(polyline or curviline) to the output sub-polyline.
Definition at line 4433 of file unstructured_two_d_mesh_geometry_base.cc.
References oomph::TriangleMeshCurveSection::final_s_connection_value(), oomph::TriangleMeshCurveSection::final_vertex_connected_bnd_id(), oomph::TriangleMeshCurveSection::final_vertex_connected_n_chunk(), oomph::TriangleMeshCurveSection::final_vertex_connected_n_vertex(), oomph::TriangleMeshCurveSection::final_vertex_coordinate(), get_associated_vertex_to_svalue(), oomph::TriangleMeshCurveSection::initial_s_connection_value(), oomph::TriangleMeshCurveSection::initial_vertex_connected_bnd_id(), oomph::TriangleMeshCurveSection::initial_vertex_connected_n_chunk(), oomph::TriangleMeshCurveSection::initial_vertex_connected_n_vertex(), oomph::TriangleMeshCurveSection::initial_vertex_coordinate(), oomph::TriangleMeshCurveSection::is_final_vertex_connected(), oomph::TriangleMeshCurveSection::is_final_vertex_connected_to_curviline(), oomph::TriangleMeshCurveSection::is_initial_vertex_connected(), oomph::TriangleMeshCurveSection::is_initial_vertex_connected_to_curviline(), oomph::TriangleMeshCurveSection::set_final_vertex_connected(), oomph::TriangleMeshCurveSection::set_initial_vertex_connected(), oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error, oomph::TriangleMeshCurveSection::tolerance_for_s_connection(), oomph::TriangleMeshCurveSection::unset_final_vertex_connected_to_curviline(), and oomph::TriangleMeshCurveSection::unset_initial_vertex_connected_to_curviline().
create_open_curve_with_polyline_helper()
TriangleMeshOpenCurve * oomph::UnstructuredTwoDMeshGeometryBase::create_open_curve_with_polyline_helper (TriangleMeshOpenCurve * open_curve_pt, unsigned & max_bnd_id_local) [inline], [protected]
Helper function that creates and returns an open curve with the polyline representation of its constituent curve sections. The new created open curve is deleted when the TriangleMesh destructor is called.
Definition at line 3495 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_curve_section_pt, oomph::TriangleMeshCurviLine::boundary_id(), oomph::TriangleMeshPolyLine::boundary_id(), copy_connection_information(), oomph::TriangleMeshCurve::curve_section_pt(), curviline_to_polyline(), Free_curve_section_pt, Free_open_curve_pt, i, oomph::TriangleMeshCurveSection::maximum_length(), oomph::TriangleMeshCurve::ncurve_section(), oomph::TriangleMeshCurve::polyline_refinement_tolerance(), oomph::TriangleMeshCurve::polyline_unrefinement_tolerance(), oomph::TriangleMeshCurveSection::refinement_tolerance(), oomph::TriangleMeshCurve::set_polyline_refinement_tolerance(), oomph::TriangleMeshCurve::set_polyline_unrefinement_tolerance(), and oomph::TriangleMeshCurveSection::unrefinement_tolerance().
Referenced by oomph::QuadFromTriangleMesh< ELEMENT >::QuadFromTriangleMesh(), and oomph::TriangleMesh< ELEMENT >::TriangleMesh().
create_vertex_coordinates_for_polyline_connections()
void oomph::UnstructuredTwoDMeshGeometryBase::create_vertex_coordinates_for_polyline_connections (TriangleMeshCurviLine * boundary_pt, Vector< Vector< double > > & vertex_coord, Vector< std::pair< double, double > > & polygonal_vertex_arclength_info) [inline], [protected]
Helper function to create polyline vertex coordinates for curvilinear boundary specified by boundary_pt, using either equal increments in zeta or in (approximate) arclength along the curviline. vertex_coord[i_vertex][i_dim] stores i_dim-th coordinate of i_vertex-th vertex. polygonal_vertex_arclength_info[i_vertex] contains the pair of doubles made of the arclength of the i_vertex-th vertex along the polygonal representation (.first), and the corresponding coordinate on the GeomObject (.second)
Definition at line 2851 of file unstructured_two_d_mesh_geometry_base.h.
References oomph::TriangleMeshCurviLine::boundary_id(), oomph::TriangleMeshCurviLine::connection_points_pt(), oomph::TriangleMeshCurviLine::geom_object_pt(), i, oomph::TriangleMeshCurviLine::nsegment(), oomph::GeomObject::position(), s, oomph::TriangleMeshCurviLine::space_vertices_evenly_in_arclength(), oomph::Global_string_for_annotation::string(), oomph::TriangleMeshCurviLine::zeta_end(), and oomph::TriangleMeshCurviLine::zeta_start().
Referenced by curviline_to_polyline().
create_vertex_coordinates_for_polyline_no_connections()
void oomph::UnstructuredTwoDMeshGeometryBase::create_vertex_coordinates_for_polyline_no_connections (TriangleMeshCurviLine * boundary_pt, Vector< Vector< double > > & vertex_coord, Vector< std::pair< double, double > > & polygonal_vertex_arclength_info) [inline], [protected]
Helper function to create polyline vertex coordinates for curvilinear boundary specified by boundary_pt, using either equal increments in zeta or in (approximate) arclength along the curviline. vertex_coord[i_vertex][i_dim] stores i_dim-th coordinate of i_vertex-th vertex. polygonal_vertex_arclength_info[i_vertex] contains the pair of doubles made of the arclength of the i_vertex-th vertex along the polygonal representation (.first), and the corresponding coordinate on the GeomObject (.second)
Definition at line 2681 of file unstructured_two_d_mesh_geometry_base.h.
References oomph::TriangleMeshCurviLine::geom_object_pt(), i, oomph::TriangleMeshCurviLine::nsegment(), oomph::GeomObject::position(), s, oomph::TriangleMeshCurviLine::space_vertices_evenly_in_arclength(), oomph::TriangleMeshCurviLine::zeta_end(), and oomph::TriangleMeshCurviLine::zeta_start().
Referenced by curviline_to_polyline().
curviline_to_polyline()
TriangleMeshCurveSection * oomph::UnstructuredTwoDMeshGeometryBase::curviline_to_polyline (TriangleMeshCurviLine *& curviline_pt, unsigned & bnd_id) [inline], [private]
Helper function that creates the associated polyline representation for curvilines.
Definition at line 3754 of file unstructured_two_d_mesh_geometry_base.h.
References oomph::TriangleMeshCurviLine::are_there_connection_points(), create_vertex_coordinates_for_polyline_connections(), create_vertex_coordinates_for_polyline_no_connections(), and Polygonal_vertex_arclength_info.
Referenced by closed_curve_to_polygon_helper(), and create_open_curve_with_polyline_helper().
disable_automatic_creation_of_vertices_on_boundaries()
void oomph::UnstructuredTwoDMeshGeometryBase::disable_automatic_creation_of_vertices_on_boundaries () [inline]
Disables the creation of points (by Triangle) on the outer and internal boundaries.
Definition at line 1993 of file unstructured_two_d_mesh_geometry_base.h.
References Allow_automatic_creation_of_vertices_on_boundaries.
enable_automatic_creation_of_vertices_on_boundaries()
void oomph::UnstructuredTwoDMeshGeometryBase::enable_automatic_creation_of_vertices_on_boundaries () [inline]
Enables the creation of points (by Triangle) on the outer and internal boundaries.
Definition at line 1986 of file unstructured_two_d_mesh_geometry_base.h.
References Allow_automatic_creation_of_vertices_on_boundaries.
face_index_at_boundary_in_region()
int oomph::UnstructuredTwoDMeshGeometryBase::face_index_at_boundary_in_region (const unsigned & b, const unsigned & r, const unsigned & e) const [inline]
Return face index of the e-th element adjacent to boundary b in region r.
Definition at line 1911 of file unstructured_two_d_mesh_geometry_base.h.
References e, and Face_index_region_at_boundary.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::adapt(), and setup_boundary_coordinates().
flush_boundary_segment_node()
void oomph::UnstructuredTwoDMeshGeometryBase::flush_boundary_segment_node (const unsigned & b) [inline]
Flush the boundary segment node storage.
Definition at line 2008 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_node_pt.
Referenced by setup_boundary_coordinates().
get_associated_vertex_to_svalue() [1/2]
unsigned oomph::UnstructuredTwoDMeshGeometryBase::get_associated_vertex_to_svalue (double & target_s_value, unsigned & bnd_id) [inline], [private]
Get the associated vertex to the given s value by looking to the list of s values created when changing from curviline to polyline.
Definition at line 3781 of file unstructured_two_d_mesh_geometry_base.h.
References get_associated_vertex_to_svalue().
Referenced by copy_connection_information(), copy_connection_information_to_sub_polylines(), and get_associated_vertex_to_svalue().
get_associated_vertex_to_svalue() [2/2]
unsigned oomph::UnstructuredTwoDMeshGeometryBase::get_associated_vertex_to_svalue (double & target_s_value, unsigned & bnd_id, double & s_tolerance) [inline], [private]
Get the associated vertex to the given s value by looking to the list of s values created when changing from curviline to polyline.
Definition at line 3791 of file unstructured_two_d_mesh_geometry_base.h.
References Polygonal_vertex_arclength_info, and s.
get_connected_vertex_number_on_destination_polyline()
const bool oomph::UnstructuredTwoDMeshGeometryBase::get_connected_vertex_number_on_destination_polyline (TriangleMeshPolyLine * dst_polyline_pt, Vector< double > & vertex_coordinates, unsigned & vertex_number)
Gets the vertex number on the destination polyline (used to create the connections among shared boundaries)
Gets the vertex number on the destination polyline (used / to create the connections among shared boundaries)
Definition at line 4120 of file unstructured_two_d_mesh_geometry_base.cc.
References i, oomph::TriangleMeshPolyLine::nvertex(), oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error, and oomph::TriangleMeshPolyLine::vertex_coordinate().
initialise_base_vertex()
void oomph::UnstructuredTwoDMeshGeometryBase::initialise_base_vertex (TriangleMeshPolyLine * polyline_pt, std::map< unsigned, std::map< unsigned, Vector< base_vertex_info > > > & base_vertices) [protected]
Initialise the base vertex structure, set every vertex to no visited and not being a base vertex.
Definition at line 3542 of file unstructured_two_d_mesh_geometry_base.cc.
References oomph::TriangleMeshPolyLine::boundary_chunk(), oomph::UnstructuredTwoDMeshGeometryBase::base_vertex_info::boundary_chunk, oomph::TriangleMeshPolyLine::boundary_id(), oomph::UnstructuredTwoDMeshGeometryBase::base_vertex_info::boundary_id, oomph::UnstructuredTwoDMeshGeometryBase::base_vertex_info::has_base_vertex_assigned, oomph::UnstructuredTwoDMeshGeometryBase::base_vertex_info::is_base_vertex, and oomph::UnstructuredTwoDMeshGeometryBase::base_vertex_info::vertex_number.
Referenced by build_triangulateio().
is_automatic_creation_of_vertices_on_boundaries_allowed()
bool oomph::UnstructuredTwoDMeshGeometryBase::is_automatic_creation_of_vertices_on_boundaries_allowed () [inline]
Returns the status of the variable Allow_automatic_creation_of_vertices_on_boundaries.
Definition at line 2000 of file unstructured_two_d_mesh_geometry_base.h.
References Allow_automatic_creation_of_vertices_on_boundaries.
Referenced by oomph::QuadFromTriangleMesh< ELEMENT >::generic_constructor(), and oomph::TriangleMesh< ELEMENT >::generic_constructor().
is_point_inside_polygon_helper()
bool oomph::UnstructuredTwoDMeshGeometryBase::is_point_inside_polygon_helper (Vector< Vector< double > > polygon_vertices, Vector< double > point)
Helper function that checks if a given point is inside a polygon (a set of sorted vertices that connected create a polygon)
Helper function that checks if a given point is inside a polygon.
Definition at line 4065 of file unstructured_two_d_mesh_geometry_base.cc.
References i.
nboundary_element_in_region()
unsigned oomph::UnstructuredTwoDMeshGeometryBase::nboundary_element_in_region (const unsigned & b, const unsigned & r) const [inline]
Return the number of elements adjacent to boundary b in region r.
Definition at line 1874 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_region_element_pt.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::adapt(), oomph::Mesh::distribute(), and setup_boundary_coordinates().
nboundary_segment()
unsigned oomph::UnstructuredTwoDMeshGeometryBase::nboundary_segment (const unsigned & b) [inline]
Return the number of segments associated with a boundary.
Definition at line 2020 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_node_pt.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::adapt(), and oomph::RefineableTriangleMesh< ELEMENT >::snap_nodes_onto_boundary().
nboundary_segment_node() [1/2]
unsigned long oomph::UnstructuredTwoDMeshGeometryBase::nboundary_segment_node (const unsigned & b) [inline]
Return the number of segments associated with a boundary.
Definition at line 2026 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_node_pt, and nboundary_segment_node().
Referenced by add_boundary_segment_node(), nboundary_segment_node(), and oomph::RefineableTriangleMesh< ELEMENT >::snap_nodes_onto_boundary().
nboundary_segment_node() [2/2]
unsigned long oomph::UnstructuredTwoDMeshGeometryBase::nboundary_segment_node (const unsigned & b, const unsigned & s) [inline]
Return the number of nodes associated with a given segment of a boundary.
Definition at line 2039 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_node_pt, and s.
nodes_on_boundary_pt()
std::map< unsigned, std::set< Node * > > & oomph::UnstructuredTwoDMeshGeometryBase::nodes_on_boundary_pt () [inline]
Gets a pointer to a set with all the nodes related with a boundary.
Definition at line 1953 of file unstructured_two_d_mesh_geometry_base.h.
References Nodes_on_boundary_pt.
nregion()
unsigned oomph::UnstructuredTwoDMeshGeometryBase::nregion () [inline]
Return the number of regions specified by attributes.
Definition at line 1757 of file unstructured_two_d_mesh_geometry_base.h.
References Region_element_pt.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::adapt(), oomph::Mesh::distribute(), and setup_boundary_coordinates().
nregion_attribute()
unsigned oomph::UnstructuredTwoDMeshGeometryBase::nregion_attribute () [inline]
Return the number of attributes used in the mesh.
Definition at line 1814 of file unstructured_two_d_mesh_geometry_base.h.
References Region_attribute.
nregion_element()
unsigned oomph::UnstructuredTwoDMeshGeometryBase::nregion_element (const unsigned & i) [inline]
Return the number of elements in the i-th region.
Definition at line 1763 of file unstructured_two_d_mesh_geometry_base.h.
References i, and Region_element_pt.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::adapt().
operator=()
void oomph::UnstructuredTwoDMeshGeometryBase::operator= (const UnstructuredTwoDMeshGeometryBase &) [delete]
Broken assignment operator.
region_attribute()
double oomph::UnstructuredTwoDMeshGeometryBase::region_attribute (const unsigned & i) [inline]
Return the attribute associated with region i.
Definition at line 1820 of file unstructured_two_d_mesh_geometry_base.h.
References i, and Region_attribute.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::adapt(), and oomph::Mesh::distribute().
region_element_pt()
FiniteElement * oomph::UnstructuredTwoDMeshGeometryBase::region_element_pt (const unsigned & i, const unsigned & e) [inline]
Return the e-th element in the i-th region.
Definition at line 1783 of file unstructured_two_d_mesh_geometry_base.h.
References e, i, and Region_element_pt.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::adapt().
set_geom_objects_and_coordinate_limits_for_close_curve()
void oomph::UnstructuredTwoDMeshGeometryBase::set_geom_objects_and_coordinate_limits_for_close_curve (TriangleMeshClosedCurve * input_closed_curve_pt) [inline], [protected]
Stores the geometric objects associated to the curve sections that compound the closed curve. It also stores the limits defined by these geometric objects.
Definition at line 3631 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_coordinate_limits, Boundary_geom_object_pt, oomph::TriangleMeshCurviLine::boundary_id(), oomph::TriangleMeshCurveSection::boundary_id(), oomph::TriangleMeshCurve::curve_section_pt(), oomph::TriangleMeshCurviLine::geom_object_pt(), Immersed_rigid_body_triangle_mesh_polygon_used, oomph::TriangleMeshCurve::ncurve_section(), oomph::TriangleMeshCurviLine::zeta_end(), and oomph::TriangleMeshCurviLine::zeta_start().
Referenced by oomph::QuadFromTriangleMesh< ELEMENT >::QuadFromTriangleMesh(), and oomph::TriangleMesh< ELEMENT >::TriangleMesh().
set_geom_objects_and_coordinate_limits_for_open_curve()
void oomph::UnstructuredTwoDMeshGeometryBase::set_geom_objects_and_coordinate_limits_for_open_curve (TriangleMeshOpenCurve * input_open_curve_pt) [inline], [protected]
Stores the geometric objects associated to the curve sections that compound the open curve. It also stores the limits defined by these geometric objects.
Definition at line 3718 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_coordinate_limits, Boundary_geom_object_pt, oomph::TriangleMeshCurviLine::boundary_id(), oomph::TriangleMeshCurve::curve_section_pt(), oomph::TriangleMeshCurviLine::geom_object_pt(), oomph::TriangleMeshCurve::ncurve_section(), oomph::TriangleMeshCurviLine::zeta_end(), and oomph::TriangleMeshCurviLine::zeta_start().
Referenced by oomph::QuadFromTriangleMesh< ELEMENT >::QuadFromTriangleMesh(), and oomph::TriangleMesh< ELEMENT >::TriangleMesh().
set_nboundary_segment_node()
void oomph::UnstructuredTwoDMeshGeometryBase::set_nboundary_segment_node (const unsigned & b, const unsigned & s) [inline]
Set the number of segments associated with a boundary.
Definition at line 2014 of file unstructured_two_d_mesh_geometry_base.h.
References Boundary_segment_node_pt, and s.
Referenced by setup_boundary_coordinates().
setup_boundary_coordinates() [1/2]
template<class ELEMENT >
void oomph::UnstructuredTwoDMeshGeometryBase::setup_boundary_coordinates (const unsigned & b) [inline]
Setup boundary coordinate on boundary b. Boundary coordinate increases continously along polygonal boundary. It's zero at the lowest left node on the boundary.
Definition at line 2442 of file unstructured_two_d_mesh_geometry_base.h.
setup_boundary_coordinates() [2/2]
template<class ELEMENT >
void oomph::UnstructuredTwoDMeshGeometryBase::setup_boundary_coordinates (const unsigned & b, std::ofstream & outfile)
Setup boundary coordinate on boundary b. Doc Faces in outfile. Boundary coordinate increases continously along polygonal boundary. It's zero at the lowest left node on the boundary.
Setup boundary coordinate on boundary b. Doc Faces in outfile. Boundary coordinate increases continously along polygonal boundary. It's zero at the lexicographically smallest node on the boundary.
Definition at line 3851 of file unstructured_two_d_mesh_geometry_base.h.
References add_boundary_segment_node(), Assigned_segments_initial_zeta_values, oomph::Mesh::Boundary_coordinate_exists, boundary_coordinate_limits(), boundary_element_in_region_pt(), oomph::Mesh::boundary_element_pt(), boundary_final_coordinate(), boundary_final_zeta_coordinate(), boundary_geom_object_pt(), boundary_initial_coordinate(), boundary_initial_zeta_coordinate(), boundary_segment_final_arclength(), boundary_segment_final_coordinate(), boundary_segment_final_zeta(), boundary_segment_initial_arclength(), boundary_segment_initial_coordinate(), boundary_segment_initial_zeta(), boundary_segment_inverted(), e, oomph::Mesh::face_index_at_boundary(), face_index_at_boundary_in_region(), flush_boundary_segment_node(), i, oomph::GeneralisedElement::is_halo(), oomph::Mesh::is_mesh_distributed(), oomph::Mesh::nboundary_element(), nboundary_element_in_region(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), nregion(), Polygonal_vertex_arclength_info, oomph::GeomObject::position(), Region_attribute, set_nboundary_segment_node(), oomph::Global_string_for_annotation::string(), Suppress_warning_about_regions_and_boundaries, and oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error.
snap_nodes_onto_geometric_objects()
void oomph::UnstructuredTwoDMeshGeometryBase::snap_nodes_onto_geometric_objects () [protected]
Snap the boundary nodes onto any curvilinear boundaries defined by geometric objects.
Move the nodes on boundaries with associated Geometric Objects so that they exactly coincide with the geometric object. This requires that the boundary coordinates are set up consistently.
Definition at line 4020 of file unstructured_two_d_mesh_geometry_base.cc.
References boundary_geom_object_pt(), oomph::Mesh::boundary_node_pt(), i, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_node(), oomph::GeomObject::position(), and t.
Referenced by oomph::QuadFromTriangleMesh< ELEMENT >::QuadFromTriangleMesh(), oomph::TriangleMesh< ELEMENT >::remesh_from_internal_triangulateio(), and oomph::TriangleMesh< ELEMENT >::TriangleMesh().
Member Data Documentation
Allow_automatic_creation_of_vertices_on_boundaries
bool oomph::UnstructuredTwoDMeshGeometryBase::Allow_automatic_creation_of_vertices_on_boundaries [protected]
Flag to indicate whether the automatic creation of vertices along the boundaries by Triangle is allowed.
Definition at line 2575 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by disable_automatic_creation_of_vertices_on_boundaries(), enable_automatic_creation_of_vertices_on_boundaries(), is_automatic_creation_of_vertices_on_boundaries_allowed(), oomph::QuadFromTriangleMesh< ELEMENT >::QuadFromTriangleMesh(), and oomph::TriangleMesh< ELEMENT >::TriangleMesh().
Assigned_segments_initial_zeta_values
std::map<unsigned, bool> oomph::UnstructuredTwoDMeshGeometryBase::Assigned_segments_initial_zeta_values
Flag used at the setup_boundary_coordinate function to know if initial zeta values for segments have been assigned.
Definition at line 2073 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by setup_boundary_coordinates().
Boundary_coordinate_limits
std::map<unsigned, Vector<double> > oomph::UnstructuredTwoDMeshGeometryBase::Boundary_coordinate_limits [protected]
Storage for the limits of the boundary coordinates defined by the use of geometric objects. Only used for curvilinear boundaries.
Definition at line 2593 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by boundary_coordinate_limits(), set_geom_objects_and_coordinate_limits_for_close_curve(), and set_geom_objects_and_coordinate_limits_for_open_curve().
Boundary_curve_section_pt
std::map<unsigned, TriangleMeshCurveSection*> oomph::UnstructuredTwoDMeshGeometryBase::Boundary_curve_section_pt [protected]
A map that stores the associated curve section of the specified boundary id.
Definition at line 2613 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by boundary_polyline_pt(), closed_curve_to_polygon_helper(), create_open_curve_with_polyline_helper(), and oomph::TriangleMesh< ELEMENT >::remesh_from_internal_triangulateio().
Boundary_final_coordinate
std::map<unsigned, Vector<double> > oomph::UnstructuredTwoDMeshGeometryBase::Boundary_final_coordinate [protected]
Stores the final coordinates for the boundary.
Definition at line 2541 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by boundary_final_coordinate().
Boundary_final_zeta_coordinate
std::map<unsigned, Vector<double> > oomph::UnstructuredTwoDMeshGeometryBase::Boundary_final_zeta_coordinate [protected]
Stores the final zeta coordinate for the boundary.
Definition at line 2551 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by boundary_final_zeta_coordinate().
Boundary_geom_object_pt
std::map<unsigned, GeomObject*> oomph::UnstructuredTwoDMeshGeometryBase::Boundary_geom_object_pt [protected]
Storage for the geometric objects associated with any boundaries.
Definition at line 2589 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by boundary_geom_object_pt(), set_geom_objects_and_coordinate_limits_for_close_curve(), and set_geom_objects_and_coordinate_limits_for_open_curve().
Boundary_initial_coordinate
std::map<unsigned, Vector<double> > oomph::UnstructuredTwoDMeshGeometryBase::Boundary_initial_coordinate [protected]
Stores the initial coordinates for the boundary.
Definition at line 2538 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by boundary_initial_coordinate().
Boundary_initial_zeta_coordinate
std::map<unsigned, Vector<double> > oomph::UnstructuredTwoDMeshGeometryBase::Boundary_initial_zeta_coordinate [protected]
Stores the initial zeta coordinate for the boundary.
Definition at line 2548 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by boundary_initial_zeta_coordinate().
Boundary_region_element_pt
Vector<std::map<unsigned, Vector<FiniteElement*> > > oomph::UnstructuredTwoDMeshGeometryBase::Boundary_region_element_pt [protected]
Storage for elements adjacent to a boundary in a particular region.
Definition at line 2617 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by boundary_element_in_region_pt(), nboundary_element_in_region(), and oomph::TriangleMesh< ELEMENT >::remesh_from_internal_triangulateio().
Boundary_segment_final_arclength
std::map<unsigned, Vector<double> > oomph::UnstructuredTwoDMeshGeometryBase::Boundary_segment_final_arclength [protected]
Stores the final arclength for the segments that appear when a boundary is splited among processors.
Definition at line 2559 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by boundary_segment_final_arclength().
Boundary_segment_final_coordinate
std::map<unsigned, Vector<Vector<double> > > oomph::UnstructuredTwoDMeshGeometryBase::Boundary_segment_final_coordinate [protected]
Stores the final coordinates for the segments that appear when a boundary is splited among processors.
Definition at line 2569 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by boundary_segment_final_coordinate().
Boundary_segment_final_zeta
std::map<unsigned, Vector<double> > oomph::UnstructuredTwoDMeshGeometryBase::Boundary_segment_final_zeta [protected]
Stores the final zeta coordinate for the segments that appear when a boundary is splited among processors.
Definition at line 2535 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by boundary_segment_final_zeta().
Boundary_segment_initial_arclength
std::map<unsigned, Vector<double> > oomph::UnstructuredTwoDMeshGeometryBase::Boundary_segment_initial_arclength [protected]
Stores the initial arclength for the segments that appear when a boundary is splited among processors.
Definition at line 2555 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by boundary_segment_initial_arclength().
Boundary_segment_initial_coordinate
std::map<unsigned, Vector<Vector<double> > > oomph::UnstructuredTwoDMeshGeometryBase::Boundary_segment_initial_coordinate [protected]
Stores the initial coordinates for the segments that appear when a boundary is splited among processors.
Definition at line 2564 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by boundary_segment_initial_coordinate().
Boundary_segment_initial_zeta
std::map<unsigned, Vector<double> > oomph::UnstructuredTwoDMeshGeometryBase::Boundary_segment_initial_zeta [protected]
Stores the initial zeta coordinate for the segments that appear when a boundary is splited among processors.
Definition at line 2531 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by boundary_segment_initial_zeta().
Boundary_segment_inverted
std::map<unsigned, Vector<unsigned> > oomph::UnstructuredTwoDMeshGeometryBase::Boundary_segment_inverted [protected]
Stores the info. to know if it is necessary to reverse the segment based on a previous mesh.
Definition at line 2545 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by boundary_segment_inverted().
Boundary_segment_node_pt
std::map<unsigned, Vector<Vector<Node*> > > oomph::UnstructuredTwoDMeshGeometryBase::Boundary_segment_node_pt [protected]
Used to store the nodes associated to a boundary and to an specific segment (this only applies in distributed meshes where the boundary is splitted in segments)
Definition at line 2527 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by add_boundary_segment_node(), oomph::TriangleMesh< ELEMENT >::boundary_segment_node_pt(), flush_boundary_segment_node(), nboundary_segment(), nboundary_segment_node(), and set_nboundary_segment_node().
Extra_holes_coordinates
Vector<Vector<double> > oomph::UnstructuredTwoDMeshGeometryBase::Extra_holes_coordinates [protected]
Storage for extra coordinates for holes.
Definition at line 2605 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by oomph::QuadFromTriangleMesh< ELEMENT >::generic_constructor(), and oomph::TriangleMesh< ELEMENT >::generic_constructor().
Face_index_region_at_boundary
Vector<std::map<unsigned, Vector<int> > > oomph::UnstructuredTwoDMeshGeometryBase::Face_index_region_at_boundary [protected]
Storage for the face index adjacent to a boundary in a particular region.
Definition at line 2620 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by face_index_at_boundary_in_region(), and oomph::TriangleMesh< ELEMENT >::remesh_from_internal_triangulateio().
Free_curve_section_pt
std::set<TriangleMeshCurveSection*> oomph::UnstructuredTwoDMeshGeometryBase::Free_curve_section_pt [protected]
A set that contains the curve sections created by this object therefore it is necessary to free their associated memory.
Definition at line 2638 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by closed_curve_to_polygon_helper(), create_open_curve_with_polyline_helper(), oomph::QuadFromTriangleMesh< ELEMENT >::~QuadFromTriangleMesh(), and oomph::TriangleMesh< ELEMENT >::~TriangleMesh().
Free_open_curve_pt
std::set<TriangleMeshOpenCurve*> oomph::UnstructuredTwoDMeshGeometryBase::Free_open_curve_pt [protected]
A set that contains the open curves created by this object therefore it is necessary to free their associated memory.
Definition at line 2646 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by create_open_curve_with_polyline_helper(), oomph::QuadFromTriangleMesh< ELEMENT >::~QuadFromTriangleMesh(), and oomph::TriangleMesh< ELEMENT >::~TriangleMesh().
Free_polygon_pt
std::set<TriangleMeshPolygon*> oomph::UnstructuredTwoDMeshGeometryBase::Free_polygon_pt [protected]
A set that contains the polygons created by this object therefore it is necessary to free their associated memory.
Definition at line 2642 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by closed_curve_to_polygon_helper(), oomph::QuadFromTriangleMesh< ELEMENT >::~QuadFromTriangleMesh(), and oomph::TriangleMesh< ELEMENT >::~TriangleMesh().
Immersed_rigid_body_triangle_mesh_polygon_used
bool oomph::UnstructuredTwoDMeshGeometryBase::Immersed_rigid_body_triangle_mesh_polygon_used [protected]
Definition at line 2666 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by set_geom_objects_and_coordinate_limits_for_close_curve().
Internal_open_curve_pt
Vector<TriangleMeshOpenCurve*> oomph::UnstructuredTwoDMeshGeometryBase::Internal_open_curve_pt [protected]
Vector of open polylines that define internal curves.
Definition at line 2602 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by oomph::QuadFromTriangleMesh< ELEMENT >::generic_constructor(), and oomph::TriangleMesh< ELEMENT >::generic_constructor().
Internal_polygon_pt
Vector<TriangleMeshPolygon*> oomph::UnstructuredTwoDMeshGeometryBase::Internal_polygon_pt [protected]
Vector of polygons that define internal polygons.
Definition at line 2599 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by oomph::QuadFromTriangleMesh< ELEMENT >::generic_constructor(), and oomph::TriangleMesh< ELEMENT >::generic_constructor().
Nodes_on_boundary_pt
std::map<unsigned, std::set<Node*> > oomph::UnstructuredTwoDMeshGeometryBase::Nodes_on_boundary_pt [protected]
Stores a pointer to a set with all the nodes related with a boundary.
Definition at line 2634 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by nodes_on_boundary_pt().
Outer_boundary_pt
Vector<TriangleMeshPolygon*> oomph::UnstructuredTwoDMeshGeometryBase::Outer_boundary_pt [protected]
Polygon that defines outer boundaries.
Definition at line 2596 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by oomph::QuadFromTriangleMesh< ELEMENT >::generic_constructor(), and oomph::TriangleMesh< ELEMENT >::generic_constructor().
Polygonal_vertex_arclength_info
std::map<unsigned, Vector<std::pair<double, double> > > oomph::UnstructuredTwoDMeshGeometryBase::Polygonal_vertex_arclength_info [protected]
Storage for pairs of doubles representing: .first: the arclength along the polygonal representation of the curviline .second: the corresponding intrinsic coordinate on the associated geometric object at which the vertices on the specified boundary are located. Only used for boundaries represented by geom objects.
Definition at line 2630 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by curviline_to_polyline(), get_associated_vertex_to_svalue(), oomph::TriangleMesh< ELEMENT >::remesh_from_internal_triangulateio(), and setup_boundary_coordinates().
Region_attribute
Vector<double> oomph::UnstructuredTwoDMeshGeometryBase::Region_attribute [protected]
Vector of attributes associated with the elements in each region.
Definition at line 2586 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by nregion_attribute(), region_attribute(), oomph::TriangleMesh< ELEMENT >::remesh_from_internal_triangulateio(), and setup_boundary_coordinates().
Region_element_pt
std::map<unsigned, Vector<FiniteElement*> > oomph::UnstructuredTwoDMeshGeometryBase::Region_element_pt [protected]
Vector of elements in each region differentiated by attribute (the key of the map is the attribute)
Definition at line 2583 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by nregion(), nregion_element(), region_element_pt(), and oomph::TriangleMesh< ELEMENT >::remesh_from_internal_triangulateio().
Regions_coordinates
std::map<unsigned, Vector<double> > oomph::UnstructuredTwoDMeshGeometryBase::Regions_coordinates [protected]
Storage for extra coordinates for regions. The key on the map is the region id.
Definition at line 2609 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by oomph::QuadFromTriangleMesh< ELEMENT >::generic_constructor(), and oomph::TriangleMesh< ELEMENT >::generic_constructor().
Suppress_warning_about_regions_and_boundaries
bool oomph::UnstructuredTwoDMeshGeometryBase::Suppress_warning_about_regions_and_boundaries = true [static]
Public static flag to suppress warning; defaults to false.
Public static flag to suppress warning; defaults to true because it really clutters up the output. It's unlikely to ever be a genuine error...
Definition at line 1741 of file unstructured_two_d_mesh_geometry_base.h.
Referenced by setup_boundary_coordinates().
The documentation for this class was generated from the following files:
unstructured_two_d_mesh_geometry_base.h
unstructured_two_d_mesh_geometry_base.cc