oomph::HelmholtzDtNBoundaryElement< ELEMENT > Class Template Reference
FaceElement used to apply Sommerfeld radiation conditon via Dirichlet to Neumann map.
#include <helmholtz_bc_elements.h>
Public Member Functions
HelmholtzDtNBoundaryElement (FiniteElement *const &bulk_el_pt, const int &face_index)
Construct element from specification of bulk element and face index.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and its Jacobian matrix.
void compute_gamma_contribution (const double &phi, const int &n, std::complex< double > &gamma_con, std::map< unsigned, std::complex< double > > &d_gamma_con)
Compute the contribution of the element to the Gamma integral and its derivates w.r.t to global unknows; the function takes the wavenumber and the polar angle phi as input.
HelmholtzDtNMesh< ELEMENT > * outer_boundary_mesh_pt () const
Access function to mesh of all DtN boundary condition elements (needed to get access to gamma values)
void set_outer_boundary_mesh_pt (HelmholtzDtNMesh< ELEMENT > *mesh_pt)
Set mesh of all DtN boundary condition elements.
void complete_setup_of_dependencies ()
Complete the setup of additional dependencies arising through the far-away interaction with other nodes in Outer_boundary_mesh_pt.
Private Member Functions
void fill_in_generic_residual_contribution_helmholtz_DtN_bc (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Compute the element's residual vector Jacobian matrix. Overloaded version, using the gamma computed in the mesh.
Private Attributes
HelmholtzDtNMesh< ELEMENT > * Outer_boundary_mesh_pt
Pointer to mesh of all DtN boundary condition elements (needed to get access to gamma values)
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::HelmholtzDtNBoundaryElement< ELEMENT >
FaceElement used to apply Sommerfeld radiation conditon via Dirichlet to Neumann map.
Definition at line 1120 of file helmholtz_bc_elements.h.
Constructor & Destructor Documentation
HelmholtzDtNBoundaryElement()
template<class ELEMENT >
oomph::HelmholtzDtNBoundaryElement< ELEMENT >::HelmholtzDtNBoundaryElement (FiniteElement *const & bulk_el_pt, const int & face_index) [inline]
Construct element from specification of bulk element and face index.
Definition at line 1125 of file helmholtz_bc_elements.h.
Member Function Documentation
complete_setup_of_dependencies()
template<class ELEMENT >
void oomph::HelmholtzDtNBoundaryElement< ELEMENT >::complete_setup_of_dependencies () [inline], [virtual]
Complete the setup of additional dependencies arising through the far-away interaction with other nodes in Outer_boundary_mesh_pt.
Reimplemented from oomph::GeneralisedElement.
Definition at line 1178 of file helmholtz_bc_elements.h.
References oomph::GeneralisedElement::add_external_data(), oomph::Node::copied_node_pt(), e, oomph::Data::is_a_copy(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::HelmholtzDtNBoundaryElement< ELEMENT >::Outer_boundary_mesh_pt.
compute_gamma_contribution()
template<class ELEMENT >
void oomph::HelmholtzDtNBoundaryElement< ELEMENT >::compute_gamma_contribution (const double & phi, const int & n, std::complex< double > & gamma_con, std::map< unsigned, std::complex< double > > & d_gamma_con)
Compute the contribution of the element to the Gamma integral and its derivates w.r.t to global unknows; the function takes the wavenumber and the polar angle phi as input.
///////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////
compute the contribution of the element to the Gamma integral and its derivates w.r.t to global unknows; the function takes wavenumber n and polar angle phi as input.
Definition at line 1459 of file helmholtz_bc_elements.h.
References oomph::Multi_domain_functions::Dim, i, oomph::MathematicalConstants::I(), and s.
Referenced by oomph::HelmholtzDtNMesh< ELEMENT >::setup_gamma().
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::HelmholtzDtNBoundaryElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and its Jacobian matrix.
Reimplemented from oomph::FiniteElement.
Definition at line 1142 of file helmholtz_bc_elements.h.
References oomph::HelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_DtN_bc().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::HelmholtzDtNBoundaryElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 1132 of file helmholtz_bc_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::HelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_DtN_bc().
fill_in_generic_residual_contribution_helmholtz_DtN_bc()
template<class ELEMENT >
void oomph::HelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_DtN_bc (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [inline], [private]
Compute the element's residual vector Jacobian matrix. Overloaded version, using the gamma computed in the mesh.
Definition at line 1228 of file helmholtz_bc_elements.h.
References oomph::HelmholtzBCElementBase< ELEMENT >::Dim, oomph::GeneralisedElement::eqn_number(), oomph::GeneralisedElement::external_local_eqn(), i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), oomph::GeneralisedElement::nexternal_data(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::Integral::nweight(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::Outer_boundary_mesh_pt, s, oomph::HelmholtzBCElementBase< ELEMENT >::test_only(), oomph::HelmholtzBCElementBase< ELEMENT >::U_index_helmholtz, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::HelmholtzDtNBoundaryElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::HelmholtzDtNBoundaryElement< ELEMENT >::fill_in_contribution_to_residuals().
outer_boundary_mesh_pt()
template<class ELEMENT >
HelmholtzDtNMesh< ELEMENT > * oomph::HelmholtzDtNBoundaryElement< ELEMENT >::outer_boundary_mesh_pt () const [inline]
Access function to mesh of all DtN boundary condition elements (needed to get access to gamma values)
Definition at line 1163 of file helmholtz_bc_elements.h.
References oomph::HelmholtzDtNBoundaryElement< ELEMENT >::Outer_boundary_mesh_pt.
set_outer_boundary_mesh_pt()
template<class ELEMENT >
void oomph::HelmholtzDtNBoundaryElement< ELEMENT >::set_outer_boundary_mesh_pt (HelmholtzDtNMesh< ELEMENT > * mesh_pt) [inline]
Set mesh of all DtN boundary condition elements.
Definition at line 1169 of file helmholtz_bc_elements.h.
References oomph::HelmholtzDtNBoundaryElement< ELEMENT >::Outer_boundary_mesh_pt.
Member Data Documentation
Outer_boundary_mesh_pt
template<class ELEMENT >
HelmholtzDtNMesh<ELEMENT>* oomph::HelmholtzDtNBoundaryElement< ELEMENT >::Outer_boundary_mesh_pt [private]
Pointer to mesh of all DtN boundary condition elements (needed to get access to gamma values)
Definition at line 1443 of file helmholtz_bc_elements.h.
Referenced by oomph::HelmholtzDtNBoundaryElement< ELEMENT >::complete_setup_of_dependencies(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_DtN_bc(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::outer_boundary_mesh_pt(), and oomph::HelmholtzDtNBoundaryElement< ELEMENT >::set_outer_boundary_mesh_pt().
The documentation for this class was generated from the following file:
helmholtz_bc_elements.h