oomph::ThinLayerBrickOnTetMesh< ELEMENT > Class Template Reference
Brick mesh layer built on top of a given tet mesh. Typically used in FSI problems where the tet mesh is the fluid mesh and this mesh acts as the solid mesh that surrounds the FSI interface.
#include <thin_layer_brick_on_tet_mesh.template.h>
Public Types
typedef void(* ThicknessFctPt) (const Vector< double > &x, double &h_thick)
Function pointer to function that specifies the wall thickness as a fct of the coordinates of the inner surface.
Public Member Functions
ThinLayerBrickOnTetMesh (Mesh *tet_mesh_pt, const Vector< unsigned > &boundary_ids, ThicknessFctPt thickness_fct_pt, const unsigned &nlayer, const Vector< Vector< unsigned > > &in_out_boundary_id, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Specify (quadratic) tet mesh, boundary IDs of boundary on which the current mesh is to be erected (in an FSI context this boundary tends to be the FSI boundary of the fluid mesh. Also specify the uniform thickness of layer, and the number of element layers. The vectors stored in in_out_boundary_ids contain the boundary IDs of the other boundaries in the tet mesh. In an FSI context these typically identify the in/outflow boundaries in the fluid mesh. The boundary enumeration of the current mesh follows the one of the underlying fluid mesh: The enumeration of the FSI boundary matches (to enable the setup of the FSI matching); the `in/outflow` faces in this mesh inherit the same enumeration as the in/outflow faces in the underlying fluid mesh. Finally, the `outer` boundary gets its own boundary ID. Timestepper defaults to steady pseudo-timestepper.
Vector< unsigned > fsi_boundary_id ()
Access functions to the Vector of oomph-lib boundary ids that make up boundary on which the mesh was erected (typically the FSI interface in an FSI problem)
unsigned outer_boundary_id ()
Boundary ID of the `outer` surface -- in an FSI context this is the non-wetted tube surface at a distance h_thick from the FSI surface.
Vector< unsigned > in_out_boundary_id (const unsigned &boundary_id)
Access function to the vector containing the ids of the oomph-lib mesh boundaries that make up the specified in/outflow boundaries as specified in constructor.
Private Attributes
Vector< unsigned > FSI_boundary_id
Vector of oomph-lib boundary ids that make up boundary on which the mesh was erected (typically the FSI interface in an FSI problem)
unsigned Outer_boundary_id
Boundary ID of the `outer` surface -- the non-wetted tube surface at a distance h_thick from the FSI surface.
Vector< Vector< unsigned > > In_out_boundary_id
Vector of vectors containing the ids of the oomph-lib mesh boundaries that make up the specified in/outflow boundaries.
ThicknessFctPt Thickness_fct_pt
Function pointer to function that specifies the wall thickness as a fct of the coordinates of the inner surface.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::ThinLayerBrickOnTetMesh< ELEMENT >
Brick mesh layer built on top of a given tet mesh. Typically used in FSI problems where the tet mesh is the fluid mesh and this mesh acts as the solid mesh that surrounds the FSI interface.
Definition at line 41 of file thin_layer_brick_on_tet_mesh.template.h.
Member Typedef Documentation
ThicknessFctPt
template<class ELEMENT >
typedef void(* oomph::ThinLayerBrickOnTetMesh< ELEMENT >::ThicknessFctPt) (const Vector< double > &x, double &h_thick)
Function pointer to function that specifies the wall thickness as a fct of the coordinates of the inner surface.
Definition at line 46 of file thin_layer_brick_on_tet_mesh.template.h.
Constructor & Destructor Documentation
ThinLayerBrickOnTetMesh()
template<class ELEMENT >
oomph::ThinLayerBrickOnTetMesh< ELEMENT >::ThinLayerBrickOnTetMesh (Mesh * tet_mesh_pt, const Vector< unsigned > & boundary_ids, ThicknessFctPt thickness_fct_pt, const unsigned & nlayer, const Vector< Vector< unsigned > > & in_out_boundary_id, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Specify (quadratic) tet mesh, boundary IDs of boundary on which the current mesh is to be erected (in an FSI context this boundary tends to be the FSI boundary of the fluid mesh. Also specify the uniform thickness of layer, and the number of element layers. The vectors stored in in_out_boundary_ids contain the boundary IDs of the other boundaries in the tet mesh. In an FSI context these typically identify the in/outflow boundaries in the fluid mesh. The boundary enumeration of the current mesh follows the one of the underlying fluid mesh: The enumeration of the FSI boundary matches (to enable the setup of the FSI matching); the `in/outflow` faces in this mesh inherit the same enumeration as the in/outflow faces in the underlying fluid mesh. Finally, the `outer` boundary gets its own boundary ID. Timestepper defaults to steady pseudo-timestepper.
Definition at line 53 of file thin_layer_brick_on_tet_mesh.template.cc.
References oomph::Mesh::add_boundary_node(), oomph::Mesh::Boundary_coordinate_exists, oomph::Mesh::Boundary_element_pt, oomph::Mesh::boundary_element_pt(), oomph::Mesh::boundary_node_pt(), e, oomph::Mesh::Element_pt, oomph::Mesh::element_pt(), oomph::Mesh::Face_index_at_boundary, oomph::Mesh::face_index_at_boundary(), oomph::Mesh::finite_element_pt(), oomph::ThinLayerBrickOnTetMesh< ELEMENT >::FSI_boundary_id, oomph::Node::get_boundaries_pt(), i, oomph::ThinLayerBrickOnTetMesh< ELEMENT >::in_out_boundary_id(), oomph::ThinLayerBrickOnTetMesh< ELEMENT >::In_out_boundary_id, oomph::FaceElement::interpolated_x(), oomph::FiniteElement::interpolated_zeta(), oomph::Mesh::Lookup_for_elements_next_boundary_is_setup, oomph::Mesh::nboundary_element(), oomph::Mesh::nboundary_node(), oomph::Edge::node1_pt(), oomph::Edge::node2_pt(), oomph::FiniteElement::node_pt(), oomph::Mesh::Node_pt, oomph::FaceElement::normal_sign(), oomph::ThinLayerBrickOnTetMesh< ELEMENT >::Outer_boundary_id, oomph::FaceElement::outer_unit_normal(), oomph::Node::position(), s, oomph::FaceElement::set_boundary_number_in_bulk_mesh(), oomph::Node::set_coordinates_on_boundary(), oomph::Mesh::set_nboundary(), oomph::ThinLayerBrickOnTetMesh< ELEMENT >::Thickness_fct_pt, and oomph::Node::x().
Member Function Documentation
fsi_boundary_id()
template<class ELEMENT >
Vector< unsigned > oomph::ThinLayerBrickOnTetMesh< ELEMENT >::fsi_boundary_id () [inline]
Access functions to the Vector of oomph-lib boundary ids that make up boundary on which the mesh was erected (typically the FSI interface in an FSI problem)
Definition at line 74 of file thin_layer_brick_on_tet_mesh.template.h.
References oomph::ThinLayerBrickOnTetMesh< ELEMENT >::FSI_boundary_id.
in_out_boundary_id()
template<class ELEMENT >
Vector< unsigned > oomph::ThinLayerBrickOnTetMesh< ELEMENT >::in_out_boundary_id (const unsigned & boundary_id) [inline]
Access function to the vector containing the ids of the oomph-lib mesh boundaries that make up the specified in/outflow boundaries as specified in constructor.
Definition at line 90 of file thin_layer_brick_on_tet_mesh.template.h.
References oomph::ThinLayerBrickOnTetMesh< ELEMENT >::In_out_boundary_id.
Referenced by oomph::ThinLayerBrickOnTetMesh< ELEMENT >::ThinLayerBrickOnTetMesh().
outer_boundary_id()
template<class ELEMENT >
unsigned oomph::ThinLayerBrickOnTetMesh< ELEMENT >::outer_boundary_id () [inline]
Boundary ID of the `outer` surface -- in an FSI context this is the non-wetted tube surface at a distance h_thick from the FSI surface.
Definition at line 82 of file thin_layer_brick_on_tet_mesh.template.h.
References oomph::ThinLayerBrickOnTetMesh< ELEMENT >::Outer_boundary_id.
Member Data Documentation
FSI_boundary_id
template<class ELEMENT >
Vector<unsigned> oomph::ThinLayerBrickOnTetMesh< ELEMENT >::FSI_boundary_id [private]
Vector of oomph-lib boundary ids that make up boundary on which the mesh was erected (typically the FSI interface in an FSI problem)
Definition at line 100 of file thin_layer_brick_on_tet_mesh.template.h.
Referenced by oomph::ThinLayerBrickOnTetMesh< ELEMENT >::fsi_boundary_id(), and oomph::ThinLayerBrickOnTetMesh< ELEMENT >::ThinLayerBrickOnTetMesh().
In_out_boundary_id
template<class ELEMENT >
Vector<Vector<unsigned> > oomph::ThinLayerBrickOnTetMesh< ELEMENT >::In_out_boundary_id [private]
Vector of vectors containing the ids of the oomph-lib mesh boundaries that make up the specified in/outflow boundaries.
Definition at line 108 of file thin_layer_brick_on_tet_mesh.template.h.
Referenced by oomph::ThinLayerBrickOnTetMesh< ELEMENT >::in_out_boundary_id(), and oomph::ThinLayerBrickOnTetMesh< ELEMENT >::ThinLayerBrickOnTetMesh().
Outer_boundary_id
template<class ELEMENT >
unsigned oomph::ThinLayerBrickOnTetMesh< ELEMENT >::Outer_boundary_id [private]
Boundary ID of the `outer` surface -- the non-wetted tube surface at a distance h_thick from the FSI surface.
Definition at line 104 of file thin_layer_brick_on_tet_mesh.template.h.
Referenced by oomph::ThinLayerBrickOnTetMesh< ELEMENT >::outer_boundary_id(), and oomph::ThinLayerBrickOnTetMesh< ELEMENT >::ThinLayerBrickOnTetMesh().
Thickness_fct_pt
template<class ELEMENT >
ThicknessFctPt oomph::ThinLayerBrickOnTetMesh< ELEMENT >::Thickness_fct_pt [private]
Function pointer to function that specifies the wall thickness as a fct of the coordinates of the inner surface.
Definition at line 112 of file thin_layer_brick_on_tet_mesh.template.h.
Referenced by oomph::ThinLayerBrickOnTetMesh< ELEMENT >::ThinLayerBrickOnTetMesh().
The documentation for this class was generated from the following files:
thin_layer_brick_on_tet_mesh.template.h
thin_layer_brick_on_tet_mesh.template.cc