oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM > Class Template Reference
A class for all isoparametric elements that solve the SpaceTimeUnsteadyHeatMixedOrder equations.
#include <discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h>
Public Member Functions
SpaceTimeUnsteadyHeatMixedOrderEquations ()
Constructor: Initialises the Source_fct_pt to null and sets flag to use ALE formulation of the equations. Also, set Alpha (thermal inertia) and Beta (thermal conductivity) parameters to defaults (both one for natural scaling).
SpaceTimeUnsteadyHeatMixedOrderEquations (const SpaceTimeUnsteadyHeatMixedOrderEquations &dummy)=delete
Broken copy constructor.
void disable_ALE ()
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
void enable_ALE ()
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
void compute_norm (double &norm)
Compute norm of FE solution.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &nplot)
Output FE representation of soln: x,y,u or x,y,z,u at nplot^SPATIAL_DIM plot points.
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &nplot)
C-style output FE representation of soln: x,y,u or x,y,z,u at nplot^SPATIAL_DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^SPATIAL_DIM plot points.
virtual void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^SPATIAL_DIM plot points (time-dependent version)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error and norm against exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Get error and norm against exact solution.
void output_element_paraview (std::ofstream &outfile, const unsigned &nplot)
C-style output FE representation of soln: x,y,u or x,y,z,u at nplot^SPATIAL_DIM plot points.
unsigned nscalar_paraview () const
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
std::string scalar_name_paraview (const unsigned &i) const
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc.
SpaceTimeUnsteadyHeatSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
SpaceTimeUnsteadyHeatSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
virtual void get_source_ust_heat (const double &t, const unsigned &ipt, const Vector< double > &x, double &source) const
Get source term at continous time t and (Eulerian) position x. Virtual so it can be overloaded in derived multi-physics elements.
const double & alpha () const
Alpha parameter (thermal inertia)
double *& alpha_pt ()
Pointer to Alpha parameter (thermal inertia)
const double & beta () const
Beta parameter (thermal conductivity)
double *& beta_pt ()
Pointer to Beta parameter (thermal conductivity)
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: flux[i]=du/dx_i.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute element residual Vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute element residual Vector and element Jacobian matrix (wrapper)
double interpolated_u_ust_heat (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
virtual unsigned u_index_ust_heat () const
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the unsteady heat equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
double interpolated_u_ust_heat (const unsigned &t, const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s at previous time t (t=0: present) DRAIG: This needs to be broken; doesn't make sense in space-time elements!
double du_dt_ust_heat (const unsigned &n) const
Calculate du/dt at the n-th local node. Uses suitably interpolated value for hanging nodes.
double interpolated_du_dt_ust_heat (const Vector< double > &s) const
Return FE representation of function value du/dt(s) at local coordinate s.
unsigned self_test ()
Self-test: Return 0 for OK.
virtual double dshape_and_dtest_eulerian_ust_heat (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coordinate s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_ust_heat (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Protected Member Functions
virtual void shape_ust_heat (const Vector< double > &s, Shape &psi) const =0
Shape functions w.r.t. to local coords.
virtual void dshape_local_ust_heat (const Vector< double > &s, Shape &psi, DShape &dpsidx) const =0
Shape functions & derivs. w.r.t. to local coords.
virtual void dtest_local_ust_heat (const Vector< double > &s, Shape &test, DShape &dtestdx) const =0
Test functions & derivs. w.r.t. to local coords.
virtual void fill_in_generic_residual_contribution_ust_heat (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Protected Attributes
SpaceTimeUnsteadyHeatSourceFctPt Source_fct_pt
Pointer to source function:
bool ALE_is_disabled
Boolean flag to indicate if ALE formulation is disabled when time-derivatives are computed. Only set to true if you're sure that the mesh is stationary.
double * Alpha_pt
Pointer to Alpha parameter (thermal inertia)
double * Beta_pt
Pointer to Beta parameter (thermal conductivity)
Static Private Attributes
static double Default_alpha_parameter = 1.0
Static default value for the Alpha parameter (thermal inertia): One for natural scaling.
static double Default_beta_parameter = 1.0
Static default value for the Beta parameter (thermal conductivity): One for natural scaling.
Additional Inherited Members
Detailed Description
template<unsigned SPATIAL_DIM>
class oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >
A class for all isoparametric elements that solve the SpaceTimeUnsteadyHeatMixedOrder equations.
 \frac{\partial^2 u}{\partial x_i^2}=\frac{\partial u}{\partial t}+f(t,x_j) 
 This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class. Note that this class assumes an isoparametric formulation, i.e. that the scalar unknown is interpolated using the same shape funcitons as the position.
Definition at line 74 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
Constructor & Destructor Documentation
SpaceTimeUnsteadyHeatMixedOrderEquations() [1/2]
template<unsigned SPATIAL_DIM>
oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::SpaceTimeUnsteadyHeatMixedOrderEquations () [inline]
Constructor: Initialises the Source_fct_pt to null and sets flag to use ALE formulation of the equations. Also, set Alpha (thermal inertia) and Beta (thermal conductivity) parameters to defaults (both one for natural scaling).
Definition at line 82 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::Alpha_pt, oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::Beta_pt, oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::Default_alpha_parameter, and oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::Default_beta_parameter.
SpaceTimeUnsteadyHeatMixedOrderEquations() [2/2]
template<unsigned SPATIAL_DIM>
oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::SpaceTimeUnsteadyHeatMixedOrderEquations (const SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
alpha()
template<unsigned SPATIAL_DIM>
const double & oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::alpha () const [inline]
Alpha parameter (thermal inertia)
Definition at line 410 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::Alpha_pt.
alpha_pt()
template<unsigned SPATIAL_DIM>
double *& oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::alpha_pt () [inline]
Pointer to Alpha parameter (thermal inertia)
Definition at line 418 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::Alpha_pt.
beta()
template<unsigned SPATIAL_DIM>
const double & oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::beta () const [inline]
Beta parameter (thermal conductivity)
Definition at line 426 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::Beta_pt.
beta_pt()
template<unsigned SPATIAL_DIM>
double *& oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::beta_pt () [inline]
Pointer to Beta parameter (thermal conductivity)
Definition at line 434 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::Beta_pt.
compute_error() [1/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error and norm against exact solution.
Validate against exact solution.
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 525 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
compute_error() [2/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [virtual]
Get error and norm against exact solution.
Validate against exact solution at time t.
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 609 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
compute_norm()
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::compute_norm (double & norm) [virtual]
Compute norm of FE solution.
Reimplemented from oomph::GeneralisedElement.
Definition at line 243 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
disable_ALE()
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::disable_ALE () [inline], [virtual]
Disable ALE, i.e. assert the mesh is not moving -- you do this at your own risk!
Reimplemented from oomph::FiniteElement.
Definition at line 99 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::ALE_is_disabled.
dshape_and_dtest_eulerian_at_knot_ust_heat()
template<unsigned SPATIAL_DIM>
virtual double oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::dshape_and_dtest_eulerian_at_knot_ust_heat (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
dshape_and_dtest_eulerian_ust_heat()
template<unsigned SPATIAL_DIM>
virtual double oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::dshape_and_dtest_eulerian_ust_heat (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coordinate s; return Jacobian of mapping.
Implemented in oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
dshape_local_ust_heat()
template<unsigned SPATIAL_DIM>
virtual void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::dshape_local_ust_heat (const Vector< double > & s, Shape & psi, DShape & dpsidx) const [protected], [pure virtual]
Shape functions & derivs. w.r.t. to local coords.
Implemented in oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
Referenced by oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_flux(), and oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::interpolated_du_dt_ust_heat().
dtest_local_ust_heat()
template<unsigned SPATIAL_DIM>
virtual void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::dtest_local_ust_heat (const Vector< double > & s, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Test functions & derivs. w.r.t. to local coords.
Implemented in oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
du_dt_ust_heat()
template<unsigned SPATIAL_DIM>
double oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::du_dt_ust_heat (const unsigned & n) const [inline]
Calculate du/dt at the n-th local node. Uses suitably interpolated value for hanging nodes.
Definition at line 593 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::interpolated_du_dt_ust_heat(), oomph::FiniteElement::local_coordinate_of_node(), and s.
enable_ALE()
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::enable_ALE () [inline], [virtual]
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
Reimplemented from oomph::FiniteElement.
Definition at line 110 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::ALE_is_disabled.
fill_in_contribution_to_jacobian()
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute element residual Vector and element Jacobian matrix (wrapper)
Reimplemented from oomph::FiniteElement.
Definition at line 505 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat().
fill_in_contribution_to_residuals()
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Compute element residual Vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 495 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat().
fill_in_generic_residual_contribution_ust_heat()
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected], [virtual]
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Compute element residual vector and/or element Jacobian matrix.
flag=0: compute only residual vector flag=1: compute both
Pure version without hanging nodes
Reimplemented in oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >.
Definition at line 65 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
Referenced by oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::fill_in_contribution_to_jacobian(), and oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::fill_in_contribution_to_residuals().
get_flux()
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_flux (const Vector< double > & s, Vector< double > & flux) const [inline]
Get flux: flux[i]=du/dx_i.
Definition at line 442 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::FiniteElement::dim(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::dshape_local_ust_heat(), oomph::FiniteElement::local_to_eulerian_mapping(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::transform_derivatives(), and oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::u_index_ust_heat().
get_source_ust_heat()
template<unsigned SPATIAL_DIM>
virtual void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_source_ust_heat (const double & t, const unsigned & ipt, const Vector< double > & x, double & source) const [inline], [virtual]
Get source term at continous time t and (Eulerian) position x. Virtual so it can be overloaded in derived multi-physics elements.
Definition at line 389 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::Source_fct_pt, and t.
interpolated_du_dt_ust_heat()
template<unsigned SPATIAL_DIM>
double oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::interpolated_du_dt_ust_heat (const Vector< double > & s) const [inline]
Return FE representation of function value du/dt(s) at local coordinate s.
Definition at line 608 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::FiniteElement::dim(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::dshape_local_ust_heat(), oomph::FiniteElement::local_to_eulerian_mapping(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::transform_derivatives(), and oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::u_index_ust_heat().
Referenced by oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::du_dt_ust_heat().
interpolated_u_ust_heat() [1/2]
template<unsigned SPATIAL_DIM>
double oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::interpolated_u_ust_heat (const unsigned & t, const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s at previous time t (t=0: present) DRAIG: This needs to be broken; doesn't make sense in space-time elements!
Definition at line 561 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::shape_ust_heat(), t, and oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::u_index_ust_heat().
interpolated_u_ust_heat() [2/2]
template<unsigned SPATIAL_DIM>
double oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::interpolated_u_ust_heat (const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s.
Definition at line 514 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::shape_ust_heat(), and oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::u_index_ust_heat().
Referenced by oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::scalar_value_paraview().
nscalar_paraview()
template<unsigned SPATIAL_DIM>
unsigned oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::nscalar_paraview () const [inline], [virtual]
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
Reimplemented from oomph::FiniteElement.
Definition at line 191 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
output() [1/4]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::output (FILE * file_pt) [inline], [virtual]
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
Definition at line 138 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::output().
output() [2/4]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::output (FILE * file_pt, const unsigned & nplot) [virtual]
C-style output FE representation of soln: x,y,u or x,y,z,u at nplot^SPATIAL_DIM plot points.
C-style output function: x,t,u or x,y,t,u at nplot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
Definition at line 363 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.cc.
References i, and s.
output() [3/4]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
Definition at line 122 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::output().
Referenced by oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::output(), and oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output().
output() [4/4]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: x,y,u or x,y,z,u at nplot^SPATIAL_DIM plot points.
Output function: x,t,u or x,y,t,u at nplot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
Definition at line 323 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.cc.
References i, and s.
output_element_paraview()
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::output_element_paraview (std::ofstream & outfile, const unsigned & nplot)
C-style output FE representation of soln: x,y,u or x,y,z,u at nplot^SPATIAL_DIM plot points.
Output function: x,t,u or x,y,t,u at nplot points in each coordinate direction.
Definition at line 731 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.cc.
References i.
output_fct() [1/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^SPATIAL_DIM plot points (time-dependent version)
Output exact solution at a given number of plot points: x,t,u_exact or x,y,t,u_exact Solution is provided via function pointer.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
Definition at line 460 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.cc.
References i, and s.
output_fct() [2/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^SPATIAL_DIM plot points.
Output exact solution at a given number of plot points: x,t,u_exact or x,y,t,u_exact Solution is provided via function pointer.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
Definition at line 403 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.cc.
References i, and s.
Referenced by oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output_fct().
scalar_name_paraview()
template<unsigned SPATIAL_DIM>
std::string oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::scalar_name_paraview (const unsigned & i) const [inline], [virtual]
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc.
Reimplemented from oomph::FiniteElement.
Definition at line 348 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References i.
scalar_value_fct_paraview() [1/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::scalar_value_fct_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const [inline], [virtual]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
Definition at line 288 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points_paraview(), and s.
scalar_value_fct_paraview() [2/2]
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::scalar_value_fct_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const [inline], [virtual]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
Definition at line 235 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points_paraview(), and s.
scalar_value_paraview()
template<unsigned SPATIAL_DIM>
void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const [inline], [virtual]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
Definition at line 200 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::FiniteElement::get_s_plot(), i, oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::interpolated_u_ust_heat(), oomph::FiniteElement::nplot_points_paraview(), and s.
self_test()
template<unsigned SPATIAL_DIM>
unsigned oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::self_test [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
Definition at line 290 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.cc.
References oomph::FiniteElement::self_test().
shape_ust_heat()
template<unsigned SPATIAL_DIM>
virtual void oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::shape_ust_heat (const Vector< double > & s, Shape & psi) const [protected], [pure virtual]
Shape functions w.r.t. to local coords.
Implemented in oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >.
Referenced by oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::interpolated_u_ust_heat().
source_fct_pt() [1/2]
template<unsigned SPATIAL_DIM>
SpaceTimeUnsteadyHeatSourceFctPt & oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::source_fct_pt () [inline], [virtual]
Access function: Pointer to source function.
Implements oomph::SpaceTimeUnsteadyHeatEquationsBase.
Definition at line 372 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::Source_fct_pt.
Referenced by oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::further_build().
source_fct_pt() [2/2]
template<unsigned SPATIAL_DIM>
SpaceTimeUnsteadyHeatSourceFctPt oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::source_fct_pt () const [inline]
Access function: Pointer to source function. Const version.
Definition at line 380 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::Source_fct_pt.
u_index_ust_heat()
template<unsigned SPATIAL_DIM>
virtual unsigned oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::u_index_ust_heat () const [inline], [virtual]
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the unsteady heat equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
Definition at line 550 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
Referenced by oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_flux(), oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_interpolated_values(), oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_Z2_flux(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::interpolated_du_dt_ust_heat(), and oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::interpolated_u_ust_heat().
Member Data Documentation
ALE_is_disabled
template<unsigned SPATIAL_DIM>
bool oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::ALE_is_disabled [protected]
Boolean flag to indicate if ALE formulation is disabled when time-derivatives are computed. Only set to true if you're sure that the mesh is stationary.
Definition at line 708 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
Referenced by oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::disable_ALE(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::enable_ALE(), and oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::further_build().
Alpha_pt
template<unsigned SPATIAL_DIM>
double* oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::Alpha_pt [protected]
Pointer to Alpha parameter (thermal inertia)
Definition at line 711 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
Referenced by oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::alpha(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::alpha_pt(), and oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::SpaceTimeUnsteadyHeatMixedOrderEquations().
Beta_pt
template<unsigned SPATIAL_DIM>
double* oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::Beta_pt [protected]
Pointer to Beta parameter (thermal conductivity)
Definition at line 714 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
Referenced by oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::beta(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::beta_pt(), and oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::SpaceTimeUnsteadyHeatMixedOrderEquations().
Default_alpha_parameter
template<unsigned SPATIAL_DIM>
double oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::Default_alpha_parameter = 1.0 [static], [private]
Static default value for the Alpha parameter (thermal inertia): One for natural scaling.
Default value for Alpha parameter (thermal inertia)
Definition at line 719 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
Referenced by oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::SpaceTimeUnsteadyHeatMixedOrderEquations().
Default_beta_parameter
template<unsigned SPATIAL_DIM>
double oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::Default_beta_parameter = 1.0 [static], [private]
Static default value for the Beta parameter (thermal conductivity): One for natural scaling.
Default value for Beta parameter (thermal conductivity)
Definition at line 723 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
Referenced by oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::SpaceTimeUnsteadyHeatMixedOrderEquations().
Source_fct_pt
template<unsigned SPATIAL_DIM>
SpaceTimeUnsteadyHeatSourceFctPt oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::Source_fct_pt [protected]
Pointer to source function:
Definition at line 703 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
Referenced by oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::further_build(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_source_ust_heat(), and oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::source_fct_pt().
The documentation for this class was generated from the following files:
discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h
discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.cc