oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT > Class Template Reference
//////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////
#include <multi_domain_boussinesq_elements.h>
Public Member Functions
RefineableAdvectionDiffusionBoussinesqElement ()
Constructor: call the underlying constructors.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: Output x, y, theta at Nplot^DIM plot points.
void output (std::ostream &outfile)
Overload the standard output function with the broken default.
void output (FILE *file_pt)
C-style output function: Broken default.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: Broken default.
void get_wind_adv_diff (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
Overload the wind function in the advection-diffusion equations. This provides the coupling from the Navier--Stokes equations to the advection-diffusion equations because the wind is the fluid velocity, obtained from the `external` element.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual vector and the Jacobian matrix.
void identify_all_field_data_for_external_interaction (Vector< std::set< FiniteElement * > > const &external_elements_pt, std::set< std::pair< Data *, unsigned > > &paired_interaction_data)
Overload the function that must return all field data involved in the interaction with the external (Navier Stokes) element. Only the velocity dofs in the Navier Stokes element affect the interaction with the current element.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void get_dwind_adv_diff_dexternal_element_data (const unsigned &ipt, const unsigned &i, Vector< double > &result, Vector< unsigned > &global_eqn_number)
Fill in the derivatives of the wind with respect to the external unknowns.
void fill_in_off_diagonal_block_analytic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the contribution of the external degrees of freedom (velocities) on the advection-diffusion equations.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Classify dofs for use in block preconditioner.
unsigned ndof_types () const
Specify number of dof types for use in block preconditioner.
Additional Inherited Members
Detailed Description
template<class AD_ELEMENT, class NST_ELEMENT>
class oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >
//////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////
Build an AdvectionDiffusionElement that inherits from ElementWithExternalElement so that it can `communicate` with the a NavierStokesElement that provides its wind.
Definition at line 375 of file multi_domain_boussinesq_elements.h.
Constructor & Destructor Documentation
RefineableAdvectionDiffusionBoussinesqElement()
template<class AD_ELEMENT , class NST_ELEMENT >
oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::RefineableAdvectionDiffusionBoussinesqElement () [inline]
Constructor: call the underlying constructors.
Definition at line 381 of file multi_domain_boussinesq_elements.h.
References oomph::ElementWithExternalElement::set_ninteraction().
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class AD_ELEMENT , class NST_ELEMENT >
void oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute the element's residual vector and the Jacobian matrix.
Reimplemented from oomph::ElementWithExternalElement.
Definition at line 476 of file multi_domain_boussinesq_elements.h.
References oomph::ElementWithExternalElement::fill_in_jacobian_from_external_interaction_by_fd(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic(), and oomph::FiniteElement::jacobian.
fill_in_contribution_to_jacobian_and_mass_matrix()
template<class AD_ELEMENT , class NST_ELEMENT >
void oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline], [virtual]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Reimplemented from oomph::GeneralisedElement.
Definition at line 507 of file multi_domain_boussinesq_elements.h.
References oomph::GeneralisedElement::fill_in_contribution_to_jacobian_and_mass_matrix(), and oomph::FiniteElement::jacobian.
fill_in_off_diagonal_block_analytic()
template<class AD_ELEMENT , class NST_ELEMENT >
void oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline]
Compute the contribution of the external degrees of freedom (velocities) on the advection-diffusion equations.
Definition at line 548 of file multi_domain_boussinesq_elements.h.
References oomph::FiniteElement::dim(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::get_dwind_adv_diff_dexternal_element_data(), oomph::FiniteElement::integral_pt(), oomph::FiniteElement::jacobian, oomph::GeneralisedElement::local_eqn_number(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), and oomph::W.
Referenced by oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_contribution_to_jacobian().
get_dof_numbers_for_unknowns()
template<class AD_ELEMENT , class NST_ELEMENT >
void oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [inline], [virtual]
Classify dofs for use in block preconditioner.
Reimplemented from oomph::GeneralisedElement.
Definition at line 702 of file multi_domain_boussinesq_elements.h.
References oomph::GeneralisedElement::eqn_number(), oomph::GeneralisedElement::local_eqn_number(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), and oomph::FiniteElement::node_pt().
get_dwind_adv_diff_dexternal_element_data()
template<class AD_ELEMENT , class NST_ELEMENT >
void oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::get_dwind_adv_diff_dexternal_element_data (const unsigned & ipt, const unsigned & i, Vector< double > & result, Vector< unsigned > & global_eqn_number) [inline]
Fill in the derivatives of the wind with respect to the external unknowns.
Definition at line 522 of file multi_domain_boussinesq_elements.h.
References oomph::ElementWithExternalElement::external_element_local_coord(), oomph::ElementWithExternalElement::external_element_pt(), and i.
Referenced by oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic().
get_wind_adv_diff()
template<class AD_ELEMENT , class NST_ELEMENT >
void oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::get_wind_adv_diff (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const [inline]
Overload the wind function in the advection-diffusion equations. This provides the coupling from the Navier--Stokes equations to the advection-diffusion equations because the wind is the fluid velocity, obtained from the `external` element.
Definition at line 456 of file multi_domain_boussinesq_elements.h.
References oomph::ElementWithExternalElement::external_element_local_coord(), and oomph::ElementWithExternalElement::external_element_pt().
identify_all_field_data_for_external_interaction()
template<class AD_ELEMENT , class NST_ELEMENT >
void oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::identify_all_field_data_for_external_interaction (Vector< std::set< FiniteElement * > > const & external_elements_pt, std::set< std::pair< Data *, unsigned > > & paired_interaction_data) [virtual]
Overload the function that must return all field data involved in the interaction with the external (Navier Stokes) element. Only the velocity dofs in the Navier Stokes element affect the interaction with the current element.
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Overload the function that must return all field data involved in the interaction with the external (Navier Stokes) element. Only the velocity dofs in the Navier Stokes element affect the interaction with the current element.
Reimplemented from oomph::ElementWithExternalElement.
Definition at line 763 of file multi_domain_boussinesq_elements.h.
References i.
ndof_types()
template<class AD_ELEMENT , class NST_ELEMENT >
unsigned oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::ndof_types () const [inline], [virtual]
Specify number of dof types for use in block preconditioner.
Reimplemented from oomph::GeneralisedElement.
Definition at line 744 of file multi_domain_boussinesq_elements.h.
output() [1/4]
template<class AD_ELEMENT , class NST_ELEMENT >
void oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C-style output function: Broken default.
Reimplemented from oomph::FiniteElement.
Definition at line 440 of file multi_domain_boussinesq_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<class AD_ELEMENT , class NST_ELEMENT >
void oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: Broken default.
Reimplemented from oomph::FiniteElement.
Definition at line 446 of file multi_domain_boussinesq_elements.h.
References oomph::FiniteElement::output().
output() [3/4]
template<class AD_ELEMENT , class NST_ELEMENT >
void oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Overload the standard output function with the broken default.
Reimplemented from oomph::FiniteElement.
Definition at line 434 of file multi_domain_boussinesq_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<class AD_ELEMENT , class NST_ELEMENT >
void oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function: Output x, y, theta at Nplot^DIM plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 400 of file multi_domain_boussinesq_elements.h.
References oomph::FiniteElement::dim(), oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
The documentation for this class was generated from the following file:
multi_domain_boussinesq_elements.h