oomph::BiharmonicFluidProblem< DIM > Class Template Reference
Biharmonic Fluid Problem Class - describes stokes flow in 2D. Developed for the topologically rectangular Hermite Element Mesh. Contains functions allowing the following boundary conditions to be applied (on a given edge):
#include <biharmonic_problem.h>
Public Types
typedef void(* FluidBCFctPt) (const double &s, Vector< double > &u)
Definition of a dirichlet boundary condition function pointer. Takes the position along a boundary (s) in the macro element coordinate scheme and returns the fluid velocity normal (dpsi/dt) to the boundary (u[0]) and the fluid velocity tangential (dpsidn) to the boundary (u[1]).
Public Member Functions
BiharmonicFluidProblem ()
constructor
void actions_before_newton_solve ()
actions before solve, performs self test
void actions_after_newton_solve ()
action after solve
void doc_solution (DocInfo &doc_info, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt=0)
documents the solution, and if an exact solution is provided, then the error between the numerical and exact solution is presented
Protected Member Functions
void impose_solid_boundary_on_edge (const unsigned &b, const double &psi=0)
Imposes a solid boundary on boundary b - no flow into boundary or along boundary v_n = 0 and v_t = 0. User must presribe the streamfunction psi to ensure dpsi/dt = 0 is imposed at all points on the boundary and not just at the nodes.
void impose_traction_free_edge (const unsigned &b)
Impose a traction free edge - i.e. v_t = 0 or dpsi/dn = 0. In general dpsi/dn = 0 can only be imposed using equation elements to set the DOFs dpsi/ds_n, however in the special case of dt/ds_n = 0, then dpsi/ds_n = 0 and can be imposed using pinning - this is handled automatically in this function. For a more detailed description of the equations see the description of the class BiharmonicFluidBoundaryElement.
void impose_fluid_flow_on_edge (const unsigned &b, FluidBCFctPt u_imposed_fn)
Impose a prescribed fluid flow comprising the velocity normal to the boundary (u_imposed_fn[0]) and the velocity tangential to the boundary (u_imposed_fn[1])
Private Attributes
unsigned Npoint_element
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::BiharmonicFluidProblem< DIM >
Biharmonic Fluid Problem Class - describes stokes flow in 2D. Developed for the topologically rectangular Hermite Element Mesh. Contains functions allowing the following boundary conditions to be applied (on a given edge):
wall : v_n = 0 and v_t = 0 (psi must also be prescribed)
traction free : v_t = 0
flow : v_n and v_t are prescribed NOTE 1 : psi is the stream function
fluid velocity normal to boundary v_n = +/- dpsi/dt
fluid velocity tangential to boundary v_t = -/+ dpsi/dn NOTE 2 : when a solid wall boundary condition is applied to ensure that v_n = 0 the the streamfunction psi must also be prescribed (and constant)
Definition at line 224 of file biharmonic_problem.h.
Member Typedef Documentation
FluidBCFctPt
template<unsigned DIM>
typedef void(* oomph::BiharmonicFluidProblem< DIM >::FluidBCFctPt) (const double &s, Vector< double > &u)
Definition of a dirichlet boundary condition function pointer. Takes the position along a boundary (s) in the macro element coordinate scheme and returns the fluid velocity normal (dpsi/dt) to the boundary (u[0]) and the fluid velocity tangential (dpsidn) to the boundary (u[1]).
Definition at line 232 of file biharmonic_problem.h.
Constructor & Destructor Documentation
BiharmonicFluidProblem()
template<unsigned DIM>
oomph::BiharmonicFluidProblem< DIM >::BiharmonicFluidProblem () [inline]
constructor
Definition at line 236 of file biharmonic_problem.h.
References oomph::BiharmonicFluidProblem< DIM >::Npoint_element.
Member Function Documentation
actions_after_newton_solve()
template<unsigned DIM>
void oomph::BiharmonicFluidProblem< DIM >::actions_after_newton_solve () [inline], [virtual]
action after solve
Reimplemented from oomph::Problem.
Definition at line 260 of file biharmonic_problem.h.
actions_before_newton_solve()
template<unsigned DIM>
void oomph::BiharmonicFluidProblem< DIM >::actions_before_newton_solve () [inline], [virtual]
actions before solve, performs self test
Reimplemented from oomph::Problem.
Definition at line 244 of file biharmonic_problem.h.
References oomph::oomph_info, and oomph::Problem::self_test().
doc_solution()
template<unsigned DIM>
void oomph::BiharmonicFluidProblem< DIM >::doc_solution (DocInfo & doc_info, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt = 0)
documents the solution, and if an exact solution is provided, then the error between the numerical and exact solution is presented
Definition at line 810 of file biharmonic_problem.cc.
References oomph::DocInfo::directory(), i, oomph::DocInfo::label(), oomph::oomph_info, and oomph::BiharmonicEquations< DIM >::output_fluid_velocity().
impose_fluid_flow_on_edge()
template<unsigned DIM>
void oomph::BiharmonicFluidProblem< DIM >::impose_fluid_flow_on_edge (const unsigned & b, FluidBCFctPt u_imposed_fn) [protected]
Impose a prescribed fluid flow comprising the velocity normal to the boundary (u_imposed_fn[0]) and the velocity tangential to the boundary (u_imposed_fn[1])
Definition at line 658 of file biharmonic_problem.cc.
References e, n, s, and u().
impose_solid_boundary_on_edge()
template<unsigned DIM>
void oomph::BiharmonicFluidProblem< DIM >::impose_solid_boundary_on_edge (const unsigned & b, const double & psi = 0) [protected]
Imposes a solid boundary on boundary b - no flow into boundary or along boundary v_n = 0 and v_t = 0. User must presribe the streamfunction psi to ensure dpsi/dt = 0 is imposed at all points on the boundary and not just at the nodes.
Imposes a solid boundary - no flow into boundary or along boundary v_n = 0 and v_t = 0. User must presribe the streamfunction psi to ensure dpsi/dt = 0 is imposed at all points on the boundary and not just at the nodes.
Definition at line 457 of file biharmonic_problem.cc.
References n.
impose_traction_free_edge()
template<unsigned DIM>
void oomph::BiharmonicFluidProblem< DIM >::impose_traction_free_edge (const unsigned & b) [protected]
Impose a traction free edge - i.e. v_t = 0 or dpsi/dn = 0. In general dpsi/dn = 0 can only be imposed using equation elements to set the DOFs dpsi/ds_n, however in the special case of dt/ds_n = 0, then dpsi/ds_n = 0 and can be imposed using pinning - this is handled automatically in this function. For a more detailed description of the equations see the description of the class BiharmonicFluidBoundaryElement.
Impose a traction free edge - i.e. v_t = 0 or dpsi/dn = 0. In general dpsi/dn = 0 can only be imposed using equation elements to set the DOFs dpsi/ds_n, however in the special case of dt/ds_n = 0, then dpsi/ds_n = 0 and can be imposed using pinning - this is handled automatically in this function. For a more detailed description of the equations see the description of the class : BiharmonicFluidBoundaryElement.
Definition at line 489 of file biharmonic_problem.cc.
References oomph::Hijacked< ELEMENT >::hijack_nodal_value(), and n.
Member Data Documentation
Npoint_element
template<unsigned DIM>
unsigned oomph::BiharmonicFluidProblem< DIM >::Npoint_element [private]
Definition at line 297 of file biharmonic_problem.h.
Referenced by oomph::BiharmonicFluidProblem< DIM >::BiharmonicFluidProblem().
The documentation for this class was generated from the following files:
biharmonic_problem.h
biharmonic_problem.cc