oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT > Class Template Reference
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
#include <multi_domain_boussinesq_elements.h>
Public Member Functions
AdvectionDiffusionBoussinesqElement ()
Constructor: call the underlying constructors.
void get_wind_adv_diff (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
Overload the wind function in the advection-diffusion equations. This provides the coupling from the Navier--Stokes equations to the advection-diffusion equations because the wind is the fluid velocity, obtained from the source element in the other mesh.
void output (std::ostream &outfile, const unsigned &nplot)
Output function: Output x, y, theta at Nplot^DIM plot points.
void output (std::ostream &outfile)
Overload the standard output function with the broken default.
void output (FILE *file_pt)
C-style output function: Broken default.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: Broken default.
void get_dwind_adv_diff_dexternal_element_data (const unsigned &ipt, const unsigned &i, Vector< double > &result, Vector< unsigned > &global_eqn_number)
Fill in the derivatives of the wind with respect to the external unknowns.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residual vector and the Jacobian matrix. Jacobian is computed by finite-differencing.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
void fill_in_off_diagonal_block_analytic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the contribution of the external degrees of freedom (velocities) on the AdvectionDiffusion equations.
Additional Inherited Members
Detailed Description
template<class AD_ELEMENT, class NST_ELEMENT>
class oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
Build AdvectionDiffusionBoussinesqElement that inherits from ElementWithExternalElement so that it can `communicate` with the Navier Stokes element
Definition at line 1070 of file multi_domain_boussinesq_elements.h.
Constructor & Destructor Documentation
AdvectionDiffusionBoussinesqElement()
template<class AD_ELEMENT , class NST_ELEMENT >
oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::AdvectionDiffusionBoussinesqElement () [inline]
Constructor: call the underlying constructors.
Definition at line 1076 of file multi_domain_boussinesq_elements.h.
References oomph::ElementWithExternalElement::set_ninteraction().
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class AD_ELEMENT , class NST_ELEMENT >
void oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute the element's residual vector and the Jacobian matrix. Jacobian is computed by finite-differencing.
Reimplemented from oomph::ElementWithExternalElement.
Definition at line 1169 of file multi_domain_boussinesq_elements.h.
References oomph::ElementWithExternalElement::fill_in_contribution_to_jacobian(), and oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic().
fill_in_contribution_to_jacobian_and_mass_matrix()
template<class AD_ELEMENT , class NST_ELEMENT >
void oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline], [virtual]
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix.
Reimplemented from oomph::GeneralisedElement.
Definition at line 1191 of file multi_domain_boussinesq_elements.h.
References oomph::GeneralisedElement::fill_in_contribution_to_jacobian_and_mass_matrix().
fill_in_off_diagonal_block_analytic()
template<class AD_ELEMENT , class NST_ELEMENT >
void oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline]
Compute the contribution of the external degrees of freedom (velocities) on the AdvectionDiffusion equations.
Definition at line 1206 of file multi_domain_boussinesq_elements.h.
References oomph::FiniteElement::dim(), oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::get_dwind_adv_diff_dexternal_element_data(), oomph::FiniteElement::integral_pt(), oomph::GeneralisedElement::local_eqn_number(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::Integral::nweight(), oomph::FiniteElement::raw_nodal_value(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_contribution_to_jacobian().
get_dwind_adv_diff_dexternal_element_data()
template<class AD_ELEMENT , class NST_ELEMENT >
void oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::get_dwind_adv_diff_dexternal_element_data (const unsigned & ipt, const unsigned & i, Vector< double > & result, Vector< unsigned > & global_eqn_number)
Fill in the derivatives of the wind with respect to the external unknowns.
Fill in the derivatives of the wind with respect to the external unknowns in the advection-diffusion equations.
Definition at line 1343 of file multi_domain_boussinesq_elements.h.
References i.
Referenced by oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic().
get_wind_adv_diff()
template<class AD_ELEMENT , class NST_ELEMENT >
void oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::get_wind_adv_diff (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const
Overload the wind function in the advection-diffusion equations. This provides the coupling from the Navier--Stokes equations to the advection-diffusion equations because the wind is the fluid velocity, obtained from the source element in the other mesh.
Overload the wind function in the advection-diffusion equations. This provides the coupling from the Navier--Stokes equations to the advection-diffusion equations because the wind is the fluid velocity, obtained from the source elements in the other mesh.
Definition at line 1320 of file multi_domain_boussinesq_elements.h.
output() [1/4]
template<class AD_ELEMENT , class NST_ELEMENT >
void oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C-style output function: Broken default.
Reimplemented from oomph::FiniteElement.
Definition at line 1146 of file multi_domain_boussinesq_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<class AD_ELEMENT , class NST_ELEMENT >
void oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function: Broken default.
Reimplemented from oomph::FiniteElement.
Definition at line 1152 of file multi_domain_boussinesq_elements.h.
References oomph::FiniteElement::output().
output() [3/4]
template<class AD_ELEMENT , class NST_ELEMENT >
void oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Overload the standard output function with the broken default.
Reimplemented from oomph::FiniteElement.
Definition at line 1140 of file multi_domain_boussinesq_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<class AD_ELEMENT , class NST_ELEMENT >
void oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function: Output x, y, theta at Nplot^DIM plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 1104 of file multi_domain_boussinesq_elements.h.
References oomph::FiniteElement::dim(), oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
The documentation for this class was generated from the following file:
multi_domain_boussinesq_elements.h