oomph::TimeHarmonicIsotropicElasticityTensor Class Reference
An isotropic elasticity tensor defined in terms of Young's modulus and Poisson's ratio. The elasticity tensor is assumed to be non-dimensionalised on some reference value for Young's modulus so the value provided to the constructor (if any) is to be interpreted as the ratio of the actual Young's modulus to the Young's modulus used to non-dimensionalise the stresses/tractions in the governing equations.
#include <time_harmonic_elasticity_tensor.h>
Public Member Functions
TimeHarmonicIsotropicElasticityTensor (const double &nu, const double &E)
Constructor. Passing in the values of the Poisson's ratio and Young's modulus (interpreted as the ratio of the actual Young's modulus to the Young's modulus (or other reference stiffness) used to non-dimensionalise stresses and tractions in the governing equations).
TimeHarmonicIsotropicElasticityTensor (const double &nu)
Constructor. Passing in the value of the Poisson's ratio. Stresses and tractions in the governing equations are assumed to have been non-dimensionalised on Young's modulus.
void update_constitutive_parameters (const double &nu, const double &E=1.0)
Update parameters: Specify values of the Poisson's ratio and (optionally) Young's modulus (interpreted as the ratio of the actual Young's modulus to the Young's modulus (or other reference stiffness) used to non-dimensionalise stresses and tractions in the governing equations).
double independent_component (const unsigned &i) const
Overload the independent coefficient function.
Private Member Functions
void set_lame_coefficients (const double &lambda, const double &mu)
Private Attributes
double C [4]
Static Private Attributes
static const unsigned StaticIndex [21]
Translation scheme for the isotropic elasticity tensor.
Additional Inherited Members
Detailed Description
An isotropic elasticity tensor defined in terms of Young's modulus and Poisson's ratio. The elasticity tensor is assumed to be non-dimensionalised on some reference value for Young's modulus so the value provided to the constructor (if any) is to be interpreted as the ratio of the actual Young's modulus to the Young's modulus used to non-dimensionalise the stresses/tractions in the governing equations.
Definition at line 145 of file time_harmonic_elasticity_tensor.h.
Constructor & Destructor Documentation
TimeHarmonicIsotropicElasticityTensor() [1/2]
oomph::TimeHarmonicIsotropicElasticityTensor::TimeHarmonicIsotropicElasticityTensor (const double & nu, const double & E) [inline]
Constructor. Passing in the values of the Poisson's ratio and Young's modulus (interpreted as the ratio of the actual Young's modulus to the Young's modulus (or other reference stiffness) used to non-dimensionalise stresses and tractions in the governing equations).
Definition at line 161 of file time_harmonic_elasticity_tensor.h.
References C, oomph::QuadTreeNames::E, and set_lame_coefficients().
TimeHarmonicIsotropicElasticityTensor() [2/2]
oomph::TimeHarmonicIsotropicElasticityTensor::TimeHarmonicIsotropicElasticityTensor (const double & nu) [inline]
Constructor. Passing in the value of the Poisson's ratio. Stresses and tractions in the governing equations are assumed to have been non-dimensionalised on Young's modulus.
Definition at line 174 of file time_harmonic_elasticity_tensor.h.
References C, oomph::QuadTreeNames::E, and set_lame_coefficients().
Member Function Documentation
independent_component()
double oomph::TimeHarmonicIsotropicElasticityTensor::independent_component (const unsigned & i) const [inline], [virtual]
Overload the independent coefficient function.
Reimplemented from oomph::TimeHarmonicElasticityTensor.
Definition at line 203 of file time_harmonic_elasticity_tensor.h.
References C, i, and StaticIndex.
set_lame_coefficients()
void oomph::TimeHarmonicIsotropicElasticityTensor::set_lame_coefficients (const double & lambda, const double & mu) [inline], [private]
Definition at line 211 of file time_harmonic_elasticity_tensor.h.
References C.
Referenced by TimeHarmonicIsotropicElasticityTensor(), and update_constitutive_parameters().
update_constitutive_parameters()
void oomph::TimeHarmonicIsotropicElasticityTensor::update_constitutive_parameters (const double & nu, const double & E = 1.0) [inline]
Update parameters: Specify values of the Poisson's ratio and (optionally) Young's modulus (interpreted as the ratio of the actual Young's modulus to the Young's modulus (or other reference stiffness) used to non-dimensionalise stresses and tractions in the governing equations).
Definition at line 192 of file time_harmonic_elasticity_tensor.h.
References C, oomph::QuadTreeNames::E, and set_lame_coefficients().
Member Data Documentation
C
double oomph::TimeHarmonicIsotropicElasticityTensor::C[4] [private]
Definition at line 149 of file time_harmonic_elasticity_tensor.h.
Referenced by independent_component(), set_lame_coefficients(), TimeHarmonicIsotropicElasticityTensor(), and update_constitutive_parameters().
StaticIndex
const unsigned oomph::TimeHarmonicIsotropicElasticityTensor::StaticIndex [static], [private]
Initial value:
= {
    1, 0, 2, 3, 0, 1, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 0, 2, 3, 0, 1}
Translation scheme for the isotropic elasticity tensor.
Definition at line 153 of file time_harmonic_elasticity_tensor.h.
Referenced by independent_component().
The documentation for this class was generated from the following files:
time_harmonic_elasticity_tensor.h
time_harmonic_elasticity_tensor.cc