oomph::QAdvectionDiffusionElement< DIM, NNODE_1D > Class Template Reference
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
#include <advection_diffusion_elements.h>
Public Member Functions
QAdvectionDiffusionElement ()
Constructor: Call constructors for QElement and Advection Diffusion equations.
QAdvectionDiffusionElement (const QAdvectionDiffusionElement< DIM, NNODE_1D > &dummy)=delete
Broken copy constructor.
void operator= (const QAdvectionDiffusionElement< DIM, NNODE_1D > &)=delete
Broken assignment operator.
unsigned required_nvalue (const unsigned &n) const
Required # of `values' (pinned or dofs) at node n.
void output (std::ostream &outfile)
Output function: x,y,u or x,y,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output (FILE *file_pt)
C-style output function: x,y,u or x,y,z,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (Calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_adv_diff (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_adv_diff (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Static Private Attributes
static const unsigned Initial_Nvalue = 1
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
QAdvectionDiffusionElement elements are linear/quadrilateral/brick-shaped Advection Diffusion elements with isoparametric interpolation for the function.
Definition at line 610 of file advection_diffusion_elements.h.
Constructor & Destructor Documentation
QAdvectionDiffusionElement() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >::QAdvectionDiffusionElement () [inline]
Constructor: Call constructors for QElement and Advection Diffusion equations.
Definition at line 622 of file advection_diffusion_elements.h.
QAdvectionDiffusionElement() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >::QAdvectionDiffusionElement (const QAdvectionDiffusionElement< DIM, NNODE_1D > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
dshape_and_dtest_eulerian_adv_diff()
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_adv_diff (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Definition at line 723 of file advection_diffusion_elements.h.
References i, and s.
dshape_and_dtest_eulerian_at_knot_adv_diff()
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_adv_diff (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected]
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Definition at line 756 of file advection_diffusion_elements.h.
operator=()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >::operator= (const QAdvectionDiffusionElement< DIM, NNODE_1D > &) [delete]
Broken assignment operator.
output() [1/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >::output (FILE * file_pt) [inline]
C-style output function: x,y,u or x,y,z,u.
Definition at line 658 of file advection_diffusion_elements.h.
References oomph::CommandLineArgs::output().
output() [2/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline]
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Definition at line 665 of file advection_diffusion_elements.h.
References oomph::CommandLineArgs::output().
output() [3/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >::output (std::ostream & outfile) [inline]
Output function: x,y,u or x,y,z,u.
Definition at line 643 of file advection_diffusion_elements.h.
References oomph::CommandLineArgs::output().
output() [4/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline]
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Definition at line 650 of file advection_diffusion_elements.h.
References oomph::CommandLineArgs::output().
output_fct() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline]
Output function for a time-dependent exact solution. x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (Calls the steady version)
Definition at line 684 of file advection_diffusion_elements.h.
output_fct() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline]
Output function for an exact solution: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
Definition at line 672 of file advection_diffusion_elements.h.
required_nvalue()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >::required_nvalue (const unsigned & n) const [inline]
Required # of `values' (pinned or dofs) at node n.
Definition at line 636 of file advection_diffusion_elements.h.
References oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >::Initial_Nvalue.
Member Data Documentation
Initial_Nvalue
template<unsigned DIM, unsigned NNODE_1D>
const unsigned oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >::Initial_Nvalue = 1 [static], [private]
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n].
Definition at line 617 of file advection_diffusion_elements.h.
Referenced by oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >::required_nvalue().
The documentation for this class was generated from the following files:
advection_diffusion_elements.h
advection_diffusion_elements.cc