oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM > Class Template Reference
A base class for elements that solve the equations of time-harmonic linear elasticity in Cartesian coordinates. Combines a few generic functions that are shared by PMLTimeHarmonicLinearElasticityEquations and PMLTimeHarmonicLinearElasticityEquationsWithPressure (Note: The latter don't exist yet but will be written as soon as somebody needs them...)
#include <pml_time_harmonic_linear_elasticity_elements.h>
Public Types
typedef void(* BodyForceFctPt) (const Vector< double > &x, Vector< std::complex< double > > &b)
Function pointer to function that specifies the body force as a function of the Cartesian coordinates FCT(x,b) -- x and b are Vectors!
Public Member Functions
PMLTimeHarmonicLinearElasticityEquationsBase ()
Constructor: Set null pointers for constitutive law and for isotropic growth function. Set physical parameter values to default values, and set body force to zero.
virtual std::complex< unsigned > u_index_time_harmonic_linear_elasticity (const unsigned i) const
Return the index at which the i-th real or imag unknown displacement component is stored. The default value is appropriate for single-physics problems:
void interpolated_u_time_harmonic_linear_elasticity (const Vector< double > &s, Vector< std::complex< double > > &disp) const
Compute vector of FE interpolated displacement u at local coordinate s.
std::complex< double > interpolated_u_time_harmonic_linear_elasticity (const Vector< double > &s, const unsigned &i) const
Return FE interpolated displacement u[i] at local coordinate s.
PMLTimeHarmonicIsotropicElasticityTensor *& elasticity_tensor_pt ()
Return the pointer to the elasticity_tensor.
std::complex< double > E (const unsigned &i, const unsigned &j, const unsigned &k, const unsigned &l) const
Access function to the entries in the elasticity tensor.
double nu () const
Access function to nu in the elasticity tensor.
const double & omega_sq () const
Access function for square of non-dim frequency.
double *& omega_sq_pt ()
Access function for square of non-dim frequency.
BodyForceFctPt & body_force_fct_pt ()
Access function: Pointer to body force function.
BodyForceFctPt body_force_fct_pt () const
Access function: Pointer to body force function (const version)
virtual void get_stress (const Vector< double > &s, DenseMatrix< std::complex< double > > &sigma) const =0
Return the Cauchy stress tensor, as calculated from the elasticity tensor at specified local coordinate Virtual so separaete versions can (and must!) be provided for displacement and pressure-displacement formulations.
void get_strain (const Vector< double > &s, DenseMatrix< std::complex< double > > &strain) const
Return the strain tensor.
void body_force (const Vector< double > &x, Vector< std::complex< double > > &b) const
Evaluate body force at Eulerian coordinate x (returns zero vector if no body force function pointer has been set)
void values_to_be_pinned_on_outer_pml_boundary (Vector< unsigned > &values_to_pin)
Pure virtual function in which we specify the values to be pinned (and set to zero) on the outer edge of the pml layer. All of them! Vector is resized internally.
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into: for now lump them all into one DOF type. Can be adjusted later.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF types` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
void compute_pml_coefficients (const unsigned &ipt, const Vector< double > &x, Vector< std::complex< double > > &pml_inverse_jacobian_diagonal, std::complex< double > &pml_jacobian_det)
Compute pml coefficients at position x and integration point ipt. pml_inverse_jacobian_diagonal contains the diagonal terms from the inverse of the Jacobian of the PML transformation. These are used to transform derivatives in real x to derivatives in transformed space $\tilde x $. This can be interpreted as an anisotropic stiffness. pml_jacobian_det is the determinant of the Jacobian of the PML transformation, this allows us to transform volume integrals in transformed space to real space. This can be interpreted as a mass factor If the PML is not enabled via enable_pml, both default to 1.0.
PMLMapping *& pml_mapping_pt ()
Return a pointer to the PML Mapping object.
PMLMapping *const & pml_mapping_pt () const
Return a pointer to the PML Mapping object (const version)
Static Public Attributes
static ContinuousBermudezPMLMapping Default_pml_mapping
Static so that the class doesn't need to instantiate a new default everytime it uses it.
Protected Attributes
PMLTimeHarmonicIsotropicElasticityTensor * Elasticity_tensor_pt
Pointer to the elasticity tensor.
double * Omega_sq_pt
Square of nondim frequency.
BodyForceFctPt Body_force_fct_pt
Pointer to body force function.
PMLMapping * Pml_mapping_pt
Pointer to class which holds the pml mapping function, also known as gamma.
Static Protected Attributes
static double Default_omega_sq_value
Static default value for square of frequency.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >
A base class for elements that solve the equations of time-harmonic linear elasticity in Cartesian coordinates. Combines a few generic functions that are shared by PMLTimeHarmonicLinearElasticityEquations and PMLTimeHarmonicLinearElasticityEquationsWithPressure (Note: The latter don't exist yet but will be written as soon as somebody needs them...)
Definition at line 78 of file pml_time_harmonic_linear_elasticity_elements.h.
Member Typedef Documentation
BodyForceFctPt
template<unsigned DIM>
typedef void(* oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::BodyForceFctPt) (const Vector< double > &x, Vector< std::complex< double > > &b)
Function pointer to function that specifies the body force as a function of the Cartesian coordinates FCT(x,b) -- x and b are Vectors!
Definition at line 175 of file pml_time_harmonic_linear_elasticity_elements.h.
Constructor & Destructor Documentation
PMLTimeHarmonicLinearElasticityEquationsBase()
template<unsigned DIM>
oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::PMLTimeHarmonicLinearElasticityEquationsBase () [inline]
Constructor: Set null pointers for constitutive law and for isotropic growth function. Set physical parameter values to default values, and set body force to zero.
Definition at line 86 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::Default_pml_mapping, and oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::Pml_mapping_pt.
Member Function Documentation
body_force()
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::body_force (const Vector< double > & x, Vector< std::complex< double > > & b) const [inline]
Evaluate body force at Eulerian coordinate x (returns zero vector if no body force function pointer has been set)
Definition at line 236 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::Body_force_fct_pt, oomph::FiniteElement::dim(), i, and oomph::x.
body_force_fct_pt() [1/2]
template<unsigned DIM>
BodyForceFctPt & oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::body_force_fct_pt () [inline]
Access function: Pointer to body force function.
Definition at line 212 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::Body_force_fct_pt.
body_force_fct_pt() [2/2]
template<unsigned DIM>
BodyForceFctPt oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::body_force_fct_pt () const [inline]
Access function: Pointer to body force function (const version)
Definition at line 218 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::Body_force_fct_pt.
compute_pml_coefficients()
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::compute_pml_coefficients (const unsigned & ipt, const Vector< double > & x, Vector< std::complex< double > > & pml_inverse_jacobian_diagonal, std::complex< double > & pml_jacobian_det) [inline]
Compute pml coefficients at position x and integration point ipt. pml_inverse_jacobian_diagonal contains the diagonal terms from the inverse of the Jacobian of the PML transformation. These are used to transform derivatives in real x to derivatives in transformed space $\tilde x $. This can be interpreted as an anisotropic stiffness. pml_jacobian_det is the determinant of the Jacobian of the PML transformation, this allows us to transform volume integrals in transformed space to real space. This can be interpreted as a mass factor If the PML is not enabled via enable_pml, both default to 1.0.
The factors all default to 1.0 if the propagation medium is the physical domain (no PML transformation)
Vector which points from the inner boundary to x
Vector which points from the inner boundary to the edge of the boundary
Calculate the square of the non-dimensional wavenumber
Definition at line 331 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLMapping::gamma(), oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::nu(), oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::omega_sq(), oomph::PMLElementBase< DIM >::Pml_direction_active, oomph::PMLElementBase< DIM >::Pml_inner_boundary, oomph::PMLElementBase< DIM >::Pml_is_enabled, oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::Pml_mapping_pt, oomph::PMLElementBase< DIM >::Pml_outer_boundary, and oomph::x.
E()
template<unsigned DIM>
std::complex< double > oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::E (const unsigned & i, const unsigned & j, const unsigned & k, const unsigned & l) const [inline]
Access function to the entries in the elasticity tensor.
Definition at line 185 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::Elasticity_tensor_pt, and i.
elasticity_tensor_pt()
template<unsigned DIM>
PMLTimeHarmonicIsotropicElasticityTensor *& oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::elasticity_tensor_pt () [inline]
Return the pointer to the elasticity_tensor.
Definition at line 179 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::Elasticity_tensor_pt.
get_dof_numbers_for_unknowns()
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [inline], [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF types` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Reimplemented from oomph::GeneralisedElement.
Definition at line 284 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::GeneralisedElement::eqn_number(), i, oomph::FiniteElement::nnode(), and oomph::FiniteElement::nodal_local_eqn().
get_strain()
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::get_strain (const Vector< double > & s, DenseMatrix< std::complex< double > > & strain) const
Return the strain tensor.
/////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////
Compute the strain tensor at local coordinate s Now fill in the entries of the strain tensor
Definition at line 49 of file pml_time_harmonic_linear_elasticity_elements.cc.
References i, and s.
Referenced by oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >::get_Z2_flux().
get_stress()
template<unsigned DIM>
virtual void oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::get_stress (const Vector< double > & s, DenseMatrix< std::complex< double > > & sigma) const [pure virtual]
Return the Cauchy stress tensor, as calculated from the elasticity tensor at specified local coordinate Virtual so separaete versions can (and must!) be provided for displacement and pressure-displacement formulations.
Implemented in oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >.
interpolated_u_time_harmonic_linear_elasticity() [1/2]
template<unsigned DIM>
std::complex< double > oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::interpolated_u_time_harmonic_linear_elasticity (const Vector< double > & s, const unsigned & i) const [inline]
Return FE interpolated displacement u[i] at local coordinate s.
Definition at line 139 of file pml_time_harmonic_linear_elasticity_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::u_index_time_harmonic_linear_elasticity().
interpolated_u_time_harmonic_linear_elasticity() [2/2]
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::interpolated_u_time_harmonic_linear_elasticity (const Vector< double > & s, Vector< std::complex< double > > & disp) const [inline]
Compute vector of FE interpolated displacement u at local coordinate s.
Definition at line 105 of file pml_time_harmonic_linear_elasticity_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::u_index_time_harmonic_linear_elasticity().
ndof_types()
template<unsigned DIM>
unsigned oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::ndof_types () const [inline], [virtual]
The number of `DOF types` that degrees of freedom in this element are sub-divided into: for now lump them all into one DOF type. Can be adjusted later.
Reimplemented from oomph::GeneralisedElement.
Definition at line 273 of file pml_time_harmonic_linear_elasticity_elements.h.
nu()
template<unsigned DIM>
double oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::nu () const [inline]
Access function to nu in the elasticity tensor.
Definition at line 194 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::Elasticity_tensor_pt, and oomph::PMLTimeHarmonicIsotropicElasticityTensor::nu().
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::compute_pml_coefficients().
omega_sq()
template<unsigned DIM>
const double & oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::omega_sq () const [inline]
Access function for square of non-dim frequency.
Definition at line 200 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::Omega_sq_pt.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::compute_pml_coefficients().
omega_sq_pt()
template<unsigned DIM>
double *& oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::omega_sq_pt () [inline]
Access function for square of non-dim frequency.
Definition at line 206 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::Omega_sq_pt.
pml_mapping_pt() [1/2]
template<unsigned DIM>
PMLMapping *& oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::pml_mapping_pt () [inline]
Return a pointer to the PML Mapping object.
Definition at line 402 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::Pml_mapping_pt.
pml_mapping_pt() [2/2]
template<unsigned DIM>
PMLMapping *const & oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::pml_mapping_pt () const [inline]
Return a pointer to the PML Mapping object (const version)
Definition at line 408 of file pml_time_harmonic_linear_elasticity_elements.h.
References oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::Pml_mapping_pt.
u_index_time_harmonic_linear_elasticity()
template<unsigned DIM>
virtual std::complex< unsigned > oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::u_index_time_harmonic_linear_elasticity (const unsigned i) const [inline], [virtual]
Return the index at which the i-th real or imag unknown displacement component is stored. The default value is appropriate for single-physics problems:
Definition at line 98 of file pml_time_harmonic_linear_elasticity_elements.h.
References i.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::interpolated_u_time_harmonic_linear_elasticity().
values_to_be_pinned_on_outer_pml_boundary()
template<unsigned DIM>
void oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::values_to_be_pinned_on_outer_pml_boundary (Vector< unsigned > & values_to_pin) [inline], [virtual]
Pure virtual function in which we specify the values to be pinned (and set to zero) on the outer edge of the pml layer. All of them! Vector is resized internally.
Implements oomph::PMLElementBase< DIM >.
Definition at line 260 of file pml_time_harmonic_linear_elasticity_elements.h.
Member Data Documentation
Body_force_fct_pt
template<unsigned DIM>
BodyForceFctPt oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::Body_force_fct_pt [protected]
Pointer to body force function.
Definition at line 425 of file pml_time_harmonic_linear_elasticity_elements.h.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::body_force(), and oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::body_force_fct_pt().
Default_omega_sq_value
template<unsigned DIM>
double oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::Default_omega_sq_value [static], [protected]
Initial value:
=
      1.0
Static default value for square of frequency.
Definition at line 428 of file pml_time_harmonic_linear_elasticity_elements.h.
Default_pml_mapping
template<unsigned DIM>
ContinuousBermudezPMLMapping oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::Default_pml_mapping [static]
Static so that the class doesn't need to instantiate a new default everytime it uses it.
Definition at line 415 of file pml_time_harmonic_linear_elasticity_elements.h.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::PMLTimeHarmonicLinearElasticityEquationsBase().
Elasticity_tensor_pt
template<unsigned DIM>
PMLTimeHarmonicIsotropicElasticityTensor* oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::Elasticity_tensor_pt [protected]
Pointer to the elasticity tensor.
Definition at line 419 of file pml_time_harmonic_linear_elasticity_elements.h.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::E(), oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::elasticity_tensor_pt(), and oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::nu().
Omega_sq_pt
template<unsigned DIM>
double* oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::Omega_sq_pt [protected]
Square of nondim frequency.
Definition at line 422 of file pml_time_harmonic_linear_elasticity_elements.h.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::omega_sq(), and oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::omega_sq_pt().
Pml_mapping_pt
template<unsigned DIM>
PMLMapping* oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::Pml_mapping_pt [protected]
Pointer to class which holds the pml mapping function, also known as gamma.
Definition at line 432 of file pml_time_harmonic_linear_elasticity_elements.h.
Referenced by oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::compute_pml_coefficients(), oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::pml_mapping_pt(), and oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::PMLTimeHarmonicLinearElasticityEquationsBase().
The documentation for this class was generated from the following files:
pml_time_harmonic_linear_elasticity_elements.h
pml_time_harmonic_linear_elasticity_elements.cc