oomph::MGSolver< DIM > Class Template Reference
#include <geometric_multigrid.h>
Public Types
typedef Smoother *(* PreSmootherFactoryFctPt) ()
typedef for a function that returns a pointer to an object of the class Smoother to be used as the pre-smoother
typedef Smoother *(* PostSmootherFactoryFctPt) ()
typedef for a function that returns a pointer to an object of the class Smoother to be used as the post-smoother
Public Member Functions
void set_pre_smoother_factory_function (PreSmootherFactoryFctPt pre_smoother_fn)
Access function to set the pre-smoother creation function.
void set_post_smoother_factory_function (PostSmootherFactoryFctPt post_smoother_fn)
Access function to set the post-smoother creation function.
MGSolver (MGProblem *mg_problem_pt)
Constructor: Set up default values for number of V-cycles and pre- and post-smoothing steps.
~MGSolver ()
Delete any dynamically allocated data.
void clean_up_memory ()
Clean up anything that needs to be cleaned up.
void set_self_test_vector ()
Makes a vector which will be used in the self-test. Is currently set to make the entries of the vector represent a plane wave propagating at an angle of 45 degrees.
void self_test ()
Makes a vector, restricts it down the levels of the hierarchy and documents it at each level. After this is done the vector is interpolated up the levels of the hierarchy with the output being documented at each level.
void restriction_self_test ()
Make a self-test to make sure that the interpolation matrices are doing the same thing to restrict the vectors down through the heirachy.
void interpolation_self_test ()
Make a self-test to make sure that the interpolation matrices are doing the same thing to interpolate the vectors up.
void plot (const unsigned &hierarchy_level, const DoubleVector &input_vector, const std::string &filename)
Given a level in the hierarchy, an input vector and a filename this function will document the given vector according to the structure of the mesh on the given level.
void disable_v_cycle_output ()
Disable all output from mg_solve apart from the number of V-cycles used to solve the problem.
void disable_output ()
Suppress anything that can be suppressed, i.e. any timings. Things like mesh adaptation can not however be silenced using this.
void enable_v_cycle_output ()
Enable the output of the V-cycle timings and other output.
void enable_doc_everything ()
Enable the output from anything that could have been suppressed.
void enable_output ()
Enable the output from anything that could have been suppressed.
void disable_smoother_and_superlu_doc_time ()
Suppress the output of both smoothers and SuperLU.
unsigned & npost_smooth ()
Return the number of post-smoothing iterations (lvalue)
unsigned & npre_smooth ()
Return the number of pre-smoothing iterations (lvalue)
void pre_smooth (const unsigned &level)
Pre-smoother: Perform 'max_iter' smoothing steps on the linear system Ax=b with current RHS vector, b, starting with current solution vector, x. Return the residual vector r=b-Ax. Uses the default smoother (set in the MGProblem constructor) which can be overloaded for a specific problem.
void post_smooth (const unsigned &level)
Post-smoother: Perform max_iter smoothing steps on the linear system Ax=b with current RHS vector, b, starting with current solution vector, x. Uses the default smoother (set in the MGProblem constructor) which can be overloaded for specific problem.
double residual_norm (const unsigned &level)
Return norm of residual r=b-Ax and the residual vector itself on the level-th level.
void direct_solve ()
Call the direct solver (SuperLU) to solve the problem exactly.
void interpolation_matrix_set (const unsigned &level, double *value, int *col_index, int *row_st, unsigned &ncol, unsigned &nnz)
Builds a CRDoubleMatrix that is used to interpolate the residual between levels. The transpose can be used as the full weighting restriction.
void interpolation_matrix_set (const unsigned &level, Vector< double > &value, Vector< int > &col_index, Vector< int > &row_st, unsigned &ncol, unsigned &nrow)
Builds a CRDoubleMatrix that is used to interpolate the residual between levels. The transpose can be used as the full weighting restriction.
void set_restriction_matrices_as_interpolation_transposes ()
Builds a CRDoubleMatrix on each level that is used to restrict the residual between levels. The transpose can be used as the interpolation matrix.
void restrict_residual (const unsigned &level)
Restrict residual (computed on level-th MG level) to the next coarser mesh and stick it into the coarse mesh RHS vector.
void interpolate_and_correct (const unsigned &level)
Interpolate solution at current level onto next finer mesh and correct the solution x at that level.
void level_up_local_coord_of_node (const int &son_type, Vector< double > &s)
Given the son_type of an element and a local node number j in that element with nnode_1d nodes per coordinate direction, return the local coordinate s in its father element. Needed in the setup of the interpolation matrices.
void setup_interpolation_matrices ()
Setup the interpolation matrix on each level.
void setup_interpolation_matrices_unstructured ()
Setup the interpolation matrix on each level (used for unstructured meshes)
void setup_transfer_matrices ()
Setup the transfer matrices on each level.
void full_setup ()
Do a full setup (assumes everything will be setup around the MGProblem pointer given in the constructor)
void solve (Problem *const &problem_pt, DoubleVector &result)
Virtual function in the base class that needs to be implemented later but for now just leave it empty.
unsigned iterations () const
Number of iterations.
unsigned & max_iter ()
Number of iterations.
void level_up_local_coord_of_node (const int &son_type, Vector< double > &s)
Given the son type of the element and the local coordinate s of a given node in the son element, return the local coordinate s in its father element. 2D case.
void level_up_local_coord_of_node (const int &son_type, Vector< double > &s)
Given the son type of the element and the local coordinate s of a given node in the son element, return the local coordinate s in its father element. 3D case.
Public Member Functions inherited from oomph::IterativeLinearSolver
IterativeLinearSolver ()
Constructor: Set (default) trivial preconditioner and set defaults for tolerance and max. number of iterations.
IterativeLinearSolver (const IterativeLinearSolver &)=delete
Broken copy constructor.
void operator= (const IterativeLinearSolver &)=delete
Broken assignment operator.
virtual ~IterativeLinearSolver ()
Destructor (empty)
Preconditioner *& preconditioner_pt ()
Access function to preconditioner.
Preconditioner *const & preconditioner_pt () const
Access function to preconditioner (const version)
double & tolerance ()
Access to convergence tolerance.
unsigned & max_iter ()
Access to max. number of iterations.
void enable_doc_convergence_history ()
Enable documentation of the convergence history.
void disable_doc_convergence_history ()
Disable documentation of the convergence history.
void open_convergence_history_file_stream (const std::string &file_name, const std::string &zone_title="")
Write convergence history into file with specified filename (automatically switches on doc). Optional second argument is a string that can be used (as a zone title) to identify what case we're running (e.g. what combination of linear solver and preconditioner or parameter values are used).
void close_convergence_history_file_stream ()
Close convergence history output stream.
double jacobian_setup_time () const
returns the time taken to assemble the jacobian matrix and residual vector
double linear_solver_solution_time () const
return the time taken to solve the linear system
virtual double preconditioner_setup_time () const
returns the the time taken to setup the preconditioner
void enable_setup_preconditioner_before_solve ()
Setup the preconditioner before the solve.
void disable_setup_preconditioner_before_solve ()
Don't set up the preconditioner before the solve.
void enable_error_after_max_iter ()
Throw an error if we don't converge within max_iter.
void disable_error_after_max_iter ()
Don't throw an error if we don't converge within max_iter (default).
void enable_iterative_solver_as_preconditioner ()
Enables the iterative solver be used as preconditioner (when calling the solve method it bypass the setup solver method -- currently only used by Trilinos solver ---)
void disable_iterative_solver_as_preconditioner ()
Disables the iterative solver be used as preconditioner (when calling the solve method it bypass the setup solver method -- currently only used by Trilinos solver ---)
Public Member Functions inherited from oomph::LinearSolver
LinearSolver ()
Empty constructor, initialise the member data.
LinearSolver (const LinearSolver &dummy)=delete
Broken copy constructor.
void operator= (const LinearSolver &)=delete
Broken assignment operator.
virtual ~LinearSolver ()
Empty virtual destructor.
void enable_doc_time ()
Enable documentation of solve times.
void disable_doc_time ()
Disable documentation of solve times.
bool is_doc_time_enabled () const
Is documentation of solve times enabled?
bool is_resolve_enabled () const
Boolean flag indicating if resolves are enabled.
virtual void enable_resolve ()
Enable resolve (i.e. store matrix and/or LU decomposition, say) Virtual so it can be overloaded to perform additional tasks.
virtual void disable_resolve ()
Disable resolve (i.e. store matrix and/or LU decomposition, say) This function simply resets an internal flag. It's virtual so it can be overloaded to perform additional tasks such as cleaning up memory that is only required for the resolve.
virtual void solve (DoubleMatrixBase *const &matrix_pt, const DoubleVector &rhs, DoubleVector &result)
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
virtual void solve (DoubleMatrixBase *const &matrix_pt, const Vector< double > &rhs, Vector< double > &result)
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
virtual void solve_transpose (Problem *const &problem_pt, DoubleVector &result)
Solver: Takes pointer to problem and returns the results vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual vector (broken virtual).
virtual void solve_transpose (DoubleMatrixBase *const &matrix_pt, const DoubleVector &rhs, DoubleVector &result)
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
virtual void solve_transpose (DoubleMatrixBase *const &matrix_pt, const Vector< double > &rhs, Vector< double > &result)
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
virtual void resolve (const DoubleVector &rhs, DoubleVector &result)
Resolve the system defined by the last assembled jacobian and the rhs vector. Solution is returned in the vector result. (broken virtual)
virtual void resolve_transpose (const DoubleVector &rhs, DoubleVector &result)
Solver: Resolve the system defined by the last assembled jacobian and the rhs vector. Solution is returned in the vector result. (broken virtual)
virtual void enable_computation_of_gradient ()
function to enable the computation of the gradient required for the globally convergent Newton method
void disable_computation_of_gradient ()
function to disable the computation of the gradient required for the globally convergent Newton method
void reset_gradient ()
function to reset the size of the gradient before each Newton solve
void get_gradient (DoubleVector &gradient)
function to access the gradient, provided it has been computed
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
if the communicator_pt is null then the distribution is not setup then false is returned, otherwise return true
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
setup the distribution of this distributable linear algebra object
void build_distribution (const LinearAlgebraDistribution &dist)
setup the distribution of this distributable linear algebra object
Protected Member Functions
void mg_solve (DoubleVector &result)
Do the actual solve -- this is called through the pure virtual solve function in the LinearSolver base class. The function is stored as protected to allow the MGPreconditioner derived class to use the solver.
void modify_restriction_matrices ()
Normalise the rows of the restriction matrices to avoid amplifications when projecting to the coarser level.
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
clear the distribution of this distributable linear algebra object
Protected Attributes
unsigned Nvcycle
Maximum number of V-cycles (this is set as a protected variable so.
MGProblem * Mg_problem_pt
Pointer to the MG problem (deep copy). This is protected to provide access to the MG preconditioner.
Vector< DoubleVector > Rhs_mg_vectors_storage
Vector to store the RHS vectors (Rhs_mg). This is protected to allow the multigrid preconditioner to assign the RHS vector during preconditioner_solve()
bool Suppress_v_cycle_output
Indicates whether or not the V-cycle output should be suppressed. Needs to be protected member data for the multigrid preconditioner to know whether or not to output information with each preconditioning step.
bool Suppress_all_output
If this is set to true then all output from the solver is suppressed. This is protected member data so that the multigrid preconditioner knows whether or not to restore the stream pointer.
std::ostream * Stream_pt
Pointer to the output stream -- defaults to std::cout. This is protected member data to allow the preconditioner to restore normal output if everything was chosen to be suppressed by the user.
Protected Attributes inherited from oomph::IterativeLinearSolver
bool Doc_convergence_history
Flag indicating if the convergence history is to be documented.
std::ofstream Output_file_stream
Output file stream for convergence history.
double Tolerance
Convergence tolerance.
unsigned Max_iter
Maximum number of iterations.
Preconditioner * Preconditioner_pt
Pointer to the preconditioner.
double Jacobian_setup_time
Jacobian setup time.
double Solution_time
linear solver solution time
double Preconditioner_setup_time
Preconditioner setup time.
bool Setup_preconditioner_before_solve
indicates whether the preconditioner should be setup before solve. Default = true;
bool Throw_error_after_max_iter
Should we throw an error instead of just returning when we hit the max iterations?
bool Use_iterative_solver_as_preconditioner
Use the iterative solver as preconditioner.
bool First_time_solve_when_used_as_preconditioner
When the iterative solver is used a preconditioner then we call the setup of solver method only once (the first time the solve method is called)
Protected Attributes inherited from oomph::LinearSolver
bool Enable_resolve
Boolean that indicates whether the matrix (or its factors, in the case of direct solver) should be stored so that the resolve function can be used.
bool Doc_time
Boolean flag that indicates whether the time taken.
bool Compute_gradient
flag that indicates whether the gradient required for the globally convergent Newton method should be computed or not
bool Gradient_has_been_computed
flag that indicates whether the gradient was computed or not
DoubleVector Gradient_for_glob_conv_newton_solve
DoubleVector storing the gradient for the globally convergent Newton method.
Private Member Functions
void setup_mg_hierarchy ()
Function to set up the hierachy of levels. Creates a vector of pointers to each MG level.
void setup_mg_structures ()
Function to set up the hierachy of levels. Creates a vector of pointers to each MG level.
void setup_smoothers ()
Function to set up all of the smoothers once the system matrices have been set up.
Private Attributes
PreSmootherFactoryFctPt Pre_smoother_factory_function_pt
Function to create pre-smoothers.
PostSmootherFactoryFctPt Post_smoother_factory_function_pt
Function to create post-smoothers.
unsigned Nlevel
The number of levels in the multigrid heirachy.
Vector< MGProblem * > Mg_hierarchy
Vector containing pointers to problems in hierarchy.
Vector< CRDoubleMatrix * > Mg_matrices_storage_pt
Vector to store the system matrices.
Vector< CRDoubleMatrix * > Interpolation_matrices_storage_pt
Vector to store the interpolation matrices.
Vector< CRDoubleMatrix * > Restriction_matrices_storage_pt
Vector to store the restriction matrices.
Vector< DoubleVector > X_mg_vectors_storage
Vector to store the solution vectors (X_mg)
Vector< DoubleVector > Residual_mg_vectors_storage
Vector to store the residual vectors.
Vector< DoubleVector > Interpolation_self_test_vectors_storage
Vector to store the result of interpolation on each level (only required if the user wishes to document the output of interpolation and restriction on each level)
Vector< DoubleVector > Restriction_self_test_vectors_storage
Vector to store the result of restriction on each level (only required if the user wishes to document the output of interpolation and restriction on each level)
Vector< Smoother * > Pre_smoothers_storage_pt
Vector to store the pre-smoothers.
Vector< Smoother * > Post_smoothers_storage_pt
Vector to store the post-smoothers.
unsigned Npre_smooth
Number of pre-smoothing steps.
unsigned Npost_smooth
Number of post-smoothing steps.
bool Doc_everything
If this is set to true we document everything. In addition to outputting the information of the setup timings and V-cycle data we document the refinement and unrefinement patterns given by the transfer operators which is done by keeping the coarser MG problem pointers alive.
bool Has_been_setup
Boolean variable to indicate whether or not the solver has been setup.
bool Has_been_solved
Boolean variable to indicate whether or not the problem was successfully solved.
unsigned V_cycle_counter
Pointer to counter for V-cycles.
Additional Inherited Members
Static Protected Attributes inherited from oomph::IterativeLinearSolver
static IdentityPreconditioner Default_preconditioner
Default preconditioner: The base class for preconditioners is a fully functional (if trivial!) preconditioner.
Detailed Description
template<unsigned DIM>
class oomph::MGSolver< DIM >
Definition at line 87 of file geometric_multigrid.h.
Member Typedef Documentation
PostSmootherFactoryFctPt
template<unsigned DIM>
typedef Smoother *(* oomph::MGSolver< DIM >::PostSmootherFactoryFctPt) ()
typedef for a function that returns a pointer to an object of the class Smoother to be used as the post-smoother
Definition at line 96 of file geometric_multigrid.h.
PreSmootherFactoryFctPt
template<unsigned DIM>
typedef Smoother *(* oomph::MGSolver< DIM >::PreSmootherFactoryFctPt) ()
typedef for a function that returns a pointer to an object of the class Smoother to be used as the pre-smoother
Definition at line 92 of file geometric_multigrid.h.
Constructor & Destructor Documentation
MGSolver()
template<unsigned DIM>
oomph::MGSolver< DIM >::MGSolver (MGProblem * mg_problem_pt) [inline]
Constructor: Set up default values for number of V-cycles and pre- and post-smoothing steps.
Definition at line 116 of file geometric_multigrid.h.
References oomph::MGSolver< DIM >::Mg_hierarchy, oomph::MGSolver< DIM >::Mg_problem_pt, and oomph::IterativeLinearSolver::Tolerance.
~MGSolver()
template<unsigned DIM>
oomph::MGSolver< DIM >::~MGSolver () [inline]
Delete any dynamically allocated data.
Definition at line 139 of file geometric_multigrid.h.
References oomph::MGSolver< DIM >::clean_up_memory().
Member Function Documentation
clean_up_memory()
template<unsigned DIM>
void oomph::MGSolver< DIM >::clean_up_memory () [inline], [virtual]
Clean up anything that needs to be cleaned up.
Reimplemented from oomph::LinearSolver.
Definition at line 146 of file geometric_multigrid.h.
References oomph::MGSolver< DIM >::Doc_everything, oomph::MGSolver< DIM >::Has_been_setup, i, oomph::MGSolver< DIM >::Interpolation_matrices_storage_pt, oomph::MGSolver< DIM >::Mg_hierarchy, oomph::MGSolver< DIM >::Mg_matrices_storage_pt, oomph::MGSolver< DIM >::Nlevel, oomph::MGSolver< DIM >::Post_smoothers_storage_pt, oomph::MGSolver< DIM >::Pre_smoothers_storage_pt, and oomph::MGSolver< DIM >::Restriction_matrices_storage_pt.
Referenced by oomph::MGSolver< DIM >::~MGSolver().
direct_solve()
template<unsigned DIM>
void oomph::MGSolver< DIM >::direct_solve () [inline]
Call the direct solver (SuperLU) to solve the problem exactly.
Definition at line 390 of file geometric_multigrid.h.
References oomph::MGSolver< DIM >::Mg_matrices_storage_pt, oomph::MGSolver< DIM >::Nlevel, oomph::MGSolver< DIM >::Rhs_mg_vectors_storage, and oomph::MGSolver< DIM >::X_mg_vectors_storage.
disable_output()
template<unsigned DIM>
void oomph::MGSolver< DIM >::disable_output () [inline]
Suppress anything that can be suppressed, i.e. any timings. Things like mesh adaptation can not however be silenced using this.
Definition at line 254 of file geometric_multigrid.h.
References oomph::LinearSolver::Doc_time, oomph::oomph_info, oomph::oomph_nullstream, oomph::MGSolver< DIM >::Stream_pt, oomph::OomphInfo::stream_pt(), oomph::MGSolver< DIM >::Suppress_all_output, and oomph::MGSolver< DIM >::Suppress_v_cycle_output.
disable_smoother_and_superlu_doc_time()
template<unsigned DIM>
void oomph::MGSolver< DIM >::disable_smoother_and_superlu_doc_time () [inline]
Suppress the output of both smoothers and SuperLU.
Definition at line 306 of file geometric_multigrid.h.
References i, oomph::MGSolver< DIM >::Mg_matrices_storage_pt, oomph::MGSolver< DIM >::Nlevel, oomph::MGSolver< DIM >::Post_smoothers_storage_pt, and oomph::MGSolver< DIM >::Pre_smoothers_storage_pt.
disable_v_cycle_output()
template<unsigned DIM>
void oomph::MGSolver< DIM >::disable_v_cycle_output () [inline]
Disable all output from mg_solve apart from the number of V-cycles used to solve the problem.
Definition at line 243 of file geometric_multigrid.h.
References oomph::LinearSolver::Doc_time, and oomph::MGSolver< DIM >::Suppress_v_cycle_output.
enable_doc_everything()
template<unsigned DIM>
void oomph::MGSolver< DIM >::enable_doc_everything () [inline]
Enable the output from anything that could have been suppressed.
Definition at line 284 of file geometric_multigrid.h.
References oomph::MGSolver< DIM >::Doc_everything.
enable_output()
template<unsigned DIM>
void oomph::MGSolver< DIM >::enable_output () [inline]
Enable the output from anything that could have been suppressed.
Definition at line 293 of file geometric_multigrid.h.
References oomph::LinearSolver::Doc_time, oomph::MGSolver< DIM >::Suppress_all_output, and oomph::MGSolver< DIM >::Suppress_v_cycle_output.
enable_v_cycle_output()
template<unsigned DIM>
void oomph::MGSolver< DIM >::enable_v_cycle_output () [inline]
Enable the output of the V-cycle timings and other output.
Definition at line 274 of file geometric_multigrid.h.
References oomph::LinearSolver::Doc_time, and oomph::MGSolver< DIM >::Suppress_v_cycle_output.
full_setup()
template<unsigned DIM>
void oomph::MGSolver< DIM >::full_setup ()
Do a full setup (assumes everything will be setup around the MGProblem pointer given in the constructor)
Runs a full setup of the MG solver.
Definition at line 823 of file geometric_multigrid.h.
References oomph::FiniteElement::dim(), i, oomph::oomph_info, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::self_test(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::TimingHelpers::timer().
Referenced by oomph::MGPreconditioner< DIM >::setup(), and oomph::MGSolver< DIM >::solve().
interpolate_and_correct()
template<unsigned DIM>
void oomph::MGSolver< DIM >::interpolate_and_correct (const unsigned & level)
Interpolate solution at current level onto next finer mesh and correct the solution x at that level.
Definition at line 2038 of file geometric_multigrid.h.
References oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
interpolation_matrix_set() [1/2]
template<unsigned DIM>
void oomph::MGSolver< DIM >::interpolation_matrix_set (const unsigned & level, double * value, int * col_index, int * row_st, unsigned & ncol, unsigned & nnz) [inline]
Builds a CRDoubleMatrix that is used to interpolate the residual between levels. The transpose can be used as the full weighting restriction.
Definition at line 400 of file geometric_multigrid.h.
References oomph::MGSolver< DIM >::Interpolation_matrices_storage_pt.
interpolation_matrix_set() [2/2]
template<unsigned DIM>
void oomph::MGSolver< DIM >::interpolation_matrix_set (const unsigned & level, Vector< double > & value, Vector< int > & col_index, Vector< int > & row_st, unsigned & ncol, unsigned & nrow) [inline]
Builds a CRDoubleMatrix that is used to interpolate the residual between levels. The transpose can be used as the full weighting restriction.
Definition at line 418 of file geometric_multigrid.h.
References oomph::MGSolver< DIM >::Interpolation_matrices_storage_pt, oomph::MGSolver< DIM >::Mg_hierarchy, and oomph::DistributableLinearAlgebraObject::nrow().
interpolation_self_test()
template<unsigned DIM>
void oomph::MGSolver< DIM >::interpolation_self_test ()
Make a self-test to make sure that the interpolation matrices are doing the same thing to interpolate the vectors up.
Function which implements a self-test to interpolate a vector up all of levels of the MG hierarchy and outputs the restricted vectors to file.
Definition at line 2339 of file geometric_multigrid.h.
References oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
iterations()
template<unsigned DIM>
unsigned oomph::MGSolver< DIM >::iterations () const [inline], [virtual]
Number of iterations.
Implements oomph::IterativeLinearSolver.
Definition at line 593 of file geometric_multigrid.h.
References oomph::MGSolver< DIM >::V_cycle_counter.
level_up_local_coord_of_node() [1/3]
void oomph::MGSolver< 2 >::level_up_local_coord_of_node (const int & son_type, Vector< double > & s)
Given the son type of the element and the local coordinate s of a given node in the son element, return the local coordinate s in its father element. 2D case.
Definition at line 37 of file geometric_multigrid.cc.
References oomph::QuadTreeNames::NE, oomph::QuadTreeNames::NW, oomph::Tree::OMEGA, s, oomph::QuadTreeNames::SE, and oomph::QuadTreeNames::SW.
level_up_local_coord_of_node() [2/3]
void oomph::MGSolver< 3 >::level_up_local_coord_of_node (const int & son_type, Vector< double > & s)
Given the son type of the element and the local coordinate s of a given node in the son element, return the local coordinate s in its father element. 3D case.
Definition at line 91 of file geometric_multigrid.cc.
References oomph::OcTreeNames::LDB, oomph::OcTreeNames::LDF, oomph::OcTreeNames::LUB, oomph::OcTreeNames::LUF, oomph::Tree::OMEGA, oomph::OcTreeNames::RDB, oomph::OcTreeNames::RDF, oomph::OcTreeNames::RUB, oomph::OcTreeNames::RUF, and s.
level_up_local_coord_of_node() [3/3]
template<unsigned DIM>
void oomph::MGSolver< DIM >::level_up_local_coord_of_node (const int & son_type, Vector< double > & s)
Given the son_type of an element and a local node number j in that element with nnode_1d nodes per coordinate direction, return the local coordinate s in its father element. Needed in the setup of the interpolation matrices.
max_iter()
template<unsigned DIM>
unsigned & oomph::MGSolver< DIM >::max_iter () [inline]
Number of iterations.
Definition at line 600 of file geometric_multigrid.h.
References oomph::MGSolver< DIM >::Nvcycle.
mg_solve()
template<unsigned DIM>
void oomph::MGSolver< DIM >::mg_solve (DoubleVector & result) [protected]
Do the actual solve -- this is called through the pure virtual solve function in the LinearSolver base class. The function is stored as protected to allow the MGPreconditioner derived class to use the solver.
Linear solver.
Definition at line 2520 of file geometric_multigrid.h.
References i, oomph::oomph_info, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::TimingHelpers::timer().
Referenced by oomph::MGPreconditioner< DIM >::preconditioner_solve(), and oomph::MGSolver< DIM >::solve().
modify_restriction_matrices()
template<unsigned DIM>
void oomph::MGSolver< DIM >::modify_restriction_matrices () [protected]
Normalise the rows of the restriction matrices to avoid amplifications when projecting to the coarser level.
Modify the restriction matrices.
Definition at line 2065 of file geometric_multigrid.h.
References i, and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
npost_smooth()
template<unsigned DIM>
unsigned & oomph::MGSolver< DIM >::npost_smooth () [inline]
Return the number of post-smoothing iterations (lvalue)
Definition at line 326 of file geometric_multigrid.h.
References oomph::MGSolver< DIM >::Npost_smooth.
npre_smooth()
template<unsigned DIM>
unsigned & oomph::MGSolver< DIM >::npre_smooth () [inline]
Return the number of pre-smoothing iterations (lvalue)
Definition at line 334 of file geometric_multigrid.h.
References oomph::MGSolver< DIM >::Npre_smooth.
plot()
template<unsigned DIM>
void oomph::MGSolver< DIM >::plot (const unsigned & hierarchy_level, const DoubleVector & input_vector, const std::string & filename)
Given a level in the hierarchy, an input vector and a filename this function will document the given vector according to the structure of the mesh on the given level.
Plots the input vector (assuming we're dealing with scalar nodal data, otherwise I don't know how to implement this...)
Definition at line 2374 of file geometric_multigrid.h.
References e, oomph::Data::eqn_number(), oomph::GeneralisedElement::eqn_number(), i, oomph::Node::ndim(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::node_pt(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::FiniteElement::tecplot_zone_string().
post_smooth()
template<unsigned DIM>
void oomph::MGSolver< DIM >::post_smooth (const unsigned & level) [inline]
Post-smoother: Perform max_iter smoothing steps on the linear system Ax=b with current RHS vector, b, starting with current solution vector, x. Uses the default smoother (set in the MGProblem constructor) which can be overloaded for specific problem.
Definition at line 364 of file geometric_multigrid.h.
References oomph::MGSolver< DIM >::Post_smoothers_storage_pt, oomph::MGSolver< DIM >::Rhs_mg_vectors_storage, and oomph::MGSolver< DIM >::X_mg_vectors_storage.
pre_smooth()
template<unsigned DIM>
void oomph::MGSolver< DIM >::pre_smooth (const unsigned & level) [inline]
Pre-smoother: Perform 'max_iter' smoothing steps on the linear system Ax=b with current RHS vector, b, starting with current solution vector, x. Return the residual vector r=b-Ax. Uses the default smoother (set in the MGProblem constructor) which can be overloaded for a specific problem.
Definition at line 346 of file geometric_multigrid.h.
References oomph::MGSolver< DIM >::Mg_matrices_storage_pt, oomph::MGSolver< DIM >::Pre_smoothers_storage_pt, oomph::MGSolver< DIM >::Residual_mg_vectors_storage, oomph::MGSolver< DIM >::Rhs_mg_vectors_storage, and oomph::MGSolver< DIM >::X_mg_vectors_storage.
residual_norm()
template<unsigned DIM>
double oomph::MGSolver< DIM >::residual_norm (const unsigned & level) [inline]
Return norm of residual r=b-Ax and the residual vector itself on the level-th level.
Definition at line 373 of file geometric_multigrid.h.
References oomph::MGSolver< DIM >::Mg_matrices_storage_pt, oomph::MGSolver< DIM >::Residual_mg_vectors_storage, oomph::MGSolver< DIM >::Rhs_mg_vectors_storage, and oomph::MGSolver< DIM >::X_mg_vectors_storage.
restrict_residual()
template<unsigned DIM>
void oomph::MGSolver< DIM >::restrict_residual (const unsigned & level)
Restrict residual (computed on level-th MG level) to the next coarser mesh and stick it into the coarse mesh RHS vector.
Restrict residual (computed on current MG level) to next coarser mesh and stick it into the coarse mesh RHS vector using the restriction matrix (if restrict_flag=1) or the transpose of the interpolation matrix (if restrict_flag=2)
Definition at line 2015 of file geometric_multigrid.h.
restriction_self_test()
template<unsigned DIM>
void oomph::MGSolver< DIM >::restriction_self_test ()
Make a self-test to make sure that the interpolation matrices are doing the same thing to restrict the vectors down through the heirachy.
Function which implements a self-test to restrict the residual vector down all of the coarser grids and output the restricted vectors to file.
Definition at line 2302 of file geometric_multigrid.h.
References oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
self_test()
template<unsigned DIM>
void oomph::MGSolver< DIM >::self_test ()
Makes a vector, restricts it down the levels of the hierarchy and documents it at each level. After this is done the vector is interpolated up the levels of the hierarchy with the output being documented at each level.
Definition at line 2130 of file geometric_multigrid.h.
References oomph::oomph_info, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::TimingHelpers::timer().
set_post_smoother_factory_function()
template<unsigned DIM>
void oomph::MGSolver< DIM >::set_post_smoother_factory_function (PostSmootherFactoryFctPt post_smoother_fn) [inline]
Access function to set the post-smoother creation function.
Definition at line 107 of file geometric_multigrid.h.
References oomph::MGSolver< DIM >::Post_smoother_factory_function_pt.
set_pre_smoother_factory_function()
template<unsigned DIM>
void oomph::MGSolver< DIM >::set_pre_smoother_factory_function (PreSmootherFactoryFctPt pre_smoother_fn) [inline]
Access function to set the pre-smoother creation function.
Definition at line 99 of file geometric_multigrid.h.
References oomph::MGSolver< DIM >::Pre_smoother_factory_function_pt.
set_restriction_matrices_as_interpolation_transposes()
template<unsigned DIM>
void oomph::MGSolver< DIM >::set_restriction_matrices_as_interpolation_transposes () [inline]
Builds a CRDoubleMatrix on each level that is used to restrict the residual between levels. The transpose can be used as the interpolation matrix.
Definition at line 463 of file geometric_multigrid.h.
References i, oomph::MGSolver< DIM >::Interpolation_matrices_storage_pt, oomph::MGSolver< DIM >::Nlevel, and oomph::MGSolver< DIM >::Restriction_matrices_storage_pt.
set_self_test_vector()
template<unsigned DIM>
void oomph::MGSolver< DIM >::set_self_test_vector ()
Makes a vector which will be used in the self-test. Is currently set to make the entries of the vector represent a plane wave propagating at an angle of 45 degrees.
Sets the initial vector to be used in the restriction and interpolation self-tests.
Definition at line 2214 of file geometric_multigrid.h.
References e, oomph::GeneralisedElement::eqn_number(), i, oomph::Node::ndim(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::MathematicalConstants::Pi, and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
setup_interpolation_matrices()
template<unsigned DIM>
void oomph::MGSolver< DIM >::setup_interpolation_matrices ()
Setup the interpolation matrix on each level.
Setup the interpolation matrices.
Definition at line 1505 of file geometric_multigrid.h.
References oomph::Data::eqn_number(), oomph::Node::hanging_pt(), i, oomph::Node::is_hanging(), oomph::FiniteElement::local_coordinate_of_node(), oomph::GeneralisedElement::ndof(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Tree::OMEGA, s, oomph::FiniteElement::shape(), oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
setup_interpolation_matrices_unstructured()
template<unsigned DIM>
void oomph::MGSolver< DIM >::setup_interpolation_matrices_unstructured ()
Setup the interpolation matrix on each level (used for unstructured meshes)
Setup the interpolation matrices.
Definition at line 1827 of file geometric_multigrid.h.
References oomph::Data::eqn_number(), oomph::GeneralisedElement::eqn_number(), oomph::Node::is_hanging(), oomph::FiniteElement::locate_zeta(), oomph::GeneralisedElement::ndof(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::position(), s, oomph::FiniteElement::shape(), oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
setup_mg_hierarchy()
template<unsigned DIM>
void oomph::MGSolver< DIM >::setup_mg_hierarchy () [private]
Function to set up the hierachy of levels. Creates a vector of pointers to each MG level.
Set up the MG hierarchy.
Definition at line 965 of file geometric_multigrid.h.
References oomph::oomph_info, oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::TimingHelpers::timer().
setup_mg_structures()
template<unsigned DIM>
void oomph::MGSolver< DIM >::setup_mg_structures () [private]
Function to set up the hierachy of levels. Creates a vector of pointers to each MG level.
Set up the MG hierarchy structures.
Definition at line 1177 of file geometric_multigrid.h.
References i, oomph::GeneralisedElement::ndof(), oomph::oomph_info, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::TimingHelpers::timer().
setup_smoothers()
template<unsigned DIM>
void oomph::MGSolver< DIM >::setup_smoothers () [private]
Function to set up all of the smoothers once the system matrices have been set up.
Set up the smoothers on all levels.
Definition at line 1356 of file geometric_multigrid.h.
References i, oomph::oomph_info, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::TimingHelpers::timer().
setup_transfer_matrices()
template<unsigned DIM>
void oomph::MGSolver< DIM >::setup_transfer_matrices ()
Setup the transfer matrices on each level.
Set up the transfer matrices. Both the pure injection and full weighting method have been implemented here but it is highly recommended that full weighting is used in general. In both methods the transpose of the transfer matrix is used to transfer a vector back.
Definition at line 1114 of file geometric_multigrid.h.
References oomph::oomph_info, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::TimingHelpers::timer().
solve()
template<unsigned DIM>
void oomph::MGSolver< DIM >::solve (Problem *const & problem_pt, DoubleVector & result) [inline], [virtual]
Virtual function in the base class that needs to be implemented later but for now just leave it empty.
Implements oomph::LinearSolver.
Definition at line 507 of file geometric_multigrid.h.
References oomph::MGSolver< DIM >::full_setup(), oomph::MGSolver< DIM >::Has_been_solved, oomph::Problem::mesh_pt(), oomph::MGSolver< DIM >::Mg_problem_pt, oomph::MGSolver< DIM >::mg_solve(), oomph::Mesh::node_pt(), oomph::Data::nvalue(), oomph::oomph_info, oomph::MGSolver< DIM >::Stream_pt, oomph::OomphInfo::stream_pt(), oomph::MGSolver< DIM >::Suppress_all_output, oomph::MGSolver< DIM >::Suppress_v_cycle_output, and oomph::MGSolver< DIM >::V_cycle_counter.
Member Data Documentation
Doc_everything
template<unsigned DIM>
bool oomph::MGSolver< DIM >::Doc_everything [private]
If this is set to true we document everything. In addition to outputting the information of the setup timings and V-cycle data we document the refinement and unrefinement patterns given by the transfer operators which is done by keeping the coarser MG problem pointers alive.
Definition at line 715 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::clean_up_memory(), and oomph::MGSolver< DIM >::enable_doc_everything().
Has_been_setup
template<unsigned DIM>
bool oomph::MGSolver< DIM >::Has_been_setup [private]
Boolean variable to indicate whether or not the solver has been setup.
Definition at line 718 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::clean_up_memory().
Has_been_solved
template<unsigned DIM>
bool oomph::MGSolver< DIM >::Has_been_solved [private]
Boolean variable to indicate whether or not the problem was successfully solved.
Definition at line 722 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::solve().
Interpolation_matrices_storage_pt
template<unsigned DIM>
Vector<CRDoubleMatrix*> oomph::MGSolver< DIM >::Interpolation_matrices_storage_pt [private]
Vector to store the interpolation matrices.
Definition at line 677 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::clean_up_memory(), oomph::MGSolver< DIM >::interpolation_matrix_set(), oomph::MGSolver< DIM >::interpolation_matrix_set(), and oomph::MGSolver< DIM >::set_restriction_matrices_as_interpolation_transposes().
Interpolation_self_test_vectors_storage
template<unsigned DIM>
Vector<DoubleVector> oomph::MGSolver< DIM >::Interpolation_self_test_vectors_storage [private]
Vector to store the result of interpolation on each level (only required if the user wishes to document the output of interpolation and restriction on each level)
Definition at line 691 of file geometric_multigrid.h.
Mg_hierarchy
template<unsigned DIM>
Vector<MGProblem*> oomph::MGSolver< DIM >::Mg_hierarchy [private]
Vector containing pointers to problems in hierarchy.
Definition at line 671 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::clean_up_memory(), oomph::MGSolver< DIM >::interpolation_matrix_set(), and oomph::MGSolver< DIM >::MGSolver().
Mg_matrices_storage_pt
template<unsigned DIM>
Vector<CRDoubleMatrix*> oomph::MGSolver< DIM >::Mg_matrices_storage_pt [private]
Vector to store the system matrices.
Definition at line 674 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::clean_up_memory(), oomph::MGSolver< DIM >::direct_solve(), oomph::MGSolver< DIM >::disable_smoother_and_superlu_doc_time(), oomph::MGSolver< DIM >::pre_smooth(), and oomph::MGSolver< DIM >::residual_norm().
Mg_problem_pt
template<unsigned DIM>
MGProblem* oomph::MGSolver< DIM >::Mg_problem_pt [protected]
Pointer to the MG problem (deep copy). This is protected to provide access to the MG preconditioner.
Definition at line 624 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::MGSolver(), oomph::MGPreconditioner< DIM >::preconditioner_solve(), and oomph::MGSolver< DIM >::solve().
Nlevel
template<unsigned DIM>
unsigned oomph::MGSolver< DIM >::Nlevel [private]
The number of levels in the multigrid heirachy.
Definition at line 668 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::clean_up_memory(), oomph::MGSolver< DIM >::direct_solve(), oomph::MGSolver< DIM >::disable_smoother_and_superlu_doc_time(), and oomph::MGSolver< DIM >::set_restriction_matrices_as_interpolation_transposes().
Npost_smooth
template<unsigned DIM>
unsigned oomph::MGSolver< DIM >::Npost_smooth [private]
Number of post-smoothing steps.
Definition at line 708 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::npost_smooth().
Npre_smooth
template<unsigned DIM>
unsigned oomph::MGSolver< DIM >::Npre_smooth [private]
Number of pre-smoothing steps.
Definition at line 705 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::npre_smooth().
Nvcycle
template<unsigned DIM>
unsigned oomph::MGSolver< DIM >::Nvcycle [protected]
Maximum number of V-cycles (this is set as a protected variable so.
Definition at line 620 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::max_iter(), and oomph::MGPreconditioner< DIM >::MGPreconditioner().
Post_smoother_factory_function_pt
template<unsigned DIM>
PostSmootherFactoryFctPt oomph::MGSolver< DIM >::Post_smoother_factory_function_pt [private]
Function to create post-smoothers.
Definition at line 653 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::set_post_smoother_factory_function().
Post_smoothers_storage_pt
template<unsigned DIM>
Vector<Smoother*> oomph::MGSolver< DIM >::Post_smoothers_storage_pt [private]
Vector to store the post-smoothers.
Definition at line 702 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::clean_up_memory(), oomph::MGSolver< DIM >::disable_smoother_and_superlu_doc_time(), and oomph::MGSolver< DIM >::post_smooth().
Pre_smoother_factory_function_pt
template<unsigned DIM>
PreSmootherFactoryFctPt oomph::MGSolver< DIM >::Pre_smoother_factory_function_pt [private]
Function to create pre-smoothers.
Definition at line 650 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::set_pre_smoother_factory_function().
Pre_smoothers_storage_pt
template<unsigned DIM>
Vector<Smoother*> oomph::MGSolver< DIM >::Pre_smoothers_storage_pt [private]
Vector to store the pre-smoothers.
Definition at line 699 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::clean_up_memory(), oomph::MGSolver< DIM >::disable_smoother_and_superlu_doc_time(), and oomph::MGSolver< DIM >::pre_smooth().
Residual_mg_vectors_storage
template<unsigned DIM>
Vector<DoubleVector> oomph::MGSolver< DIM >::Residual_mg_vectors_storage [private]
Vector to store the residual vectors.
Definition at line 686 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::pre_smooth(), and oomph::MGSolver< DIM >::residual_norm().
Restriction_matrices_storage_pt
template<unsigned DIM>
Vector<CRDoubleMatrix*> oomph::MGSolver< DIM >::Restriction_matrices_storage_pt [private]
Vector to store the restriction matrices.
Definition at line 680 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::clean_up_memory(), and oomph::MGSolver< DIM >::set_restriction_matrices_as_interpolation_transposes().
Restriction_self_test_vectors_storage
template<unsigned DIM>
Vector<DoubleVector> oomph::MGSolver< DIM >::Restriction_self_test_vectors_storage [private]
Vector to store the result of restriction on each level (only required if the user wishes to document the output of interpolation and restriction on each level)
Definition at line 696 of file geometric_multigrid.h.
Rhs_mg_vectors_storage
template<unsigned DIM>
Vector<DoubleVector> oomph::MGSolver< DIM >::Rhs_mg_vectors_storage [protected]
Vector to store the RHS vectors (Rhs_mg). This is protected to allow the multigrid preconditioner to assign the RHS vector during preconditioner_solve()
Definition at line 629 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::direct_solve(), oomph::MGSolver< DIM >::post_smooth(), oomph::MGSolver< DIM >::pre_smooth(), oomph::MGPreconditioner< DIM >::preconditioner_solve(), and oomph::MGSolver< DIM >::residual_norm().
Stream_pt
template<unsigned DIM>
std::ostream* oomph::MGSolver< DIM >::Stream_pt [protected]
Pointer to the output stream -- defaults to std::cout. This is protected member data to allow the preconditioner to restore normal output if everything was chosen to be suppressed by the user.
Definition at line 646 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::disable_output(), oomph::MGPreconditioner< DIM >::preconditioner_solve(), oomph::MGPreconditioner< DIM >::setup(), and oomph::MGSolver< DIM >::solve().
Suppress_all_output
template<unsigned DIM>
bool oomph::MGSolver< DIM >::Suppress_all_output [protected]
If this is set to true then all output from the solver is suppressed. This is protected member data so that the multigrid preconditioner knows whether or not to restore the stream pointer.
Definition at line 640 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::disable_output(), oomph::MGSolver< DIM >::enable_output(), oomph::MGPreconditioner< DIM >::preconditioner_solve(), oomph::MGPreconditioner< DIM >::setup(), and oomph::MGSolver< DIM >::solve().
Suppress_v_cycle_output
template<unsigned DIM>
bool oomph::MGSolver< DIM >::Suppress_v_cycle_output [protected]
Indicates whether or not the V-cycle output should be suppressed. Needs to be protected member data for the multigrid preconditioner to know whether or not to output information with each preconditioning step.
Definition at line 635 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::disable_output(), oomph::MGSolver< DIM >::disable_v_cycle_output(), oomph::MGSolver< DIM >::enable_output(), oomph::MGSolver< DIM >::enable_v_cycle_output(), oomph::MGPreconditioner< DIM >::preconditioner_solve(), and oomph::MGSolver< DIM >::solve().
V_cycle_counter
template<unsigned DIM>
unsigned oomph::MGSolver< DIM >::V_cycle_counter [private]
Pointer to counter for V-cycles.
Definition at line 725 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::iterations(), and oomph::MGSolver< DIM >::solve().
X_mg_vectors_storage
template<unsigned DIM>
Vector<DoubleVector> oomph::MGSolver< DIM >::X_mg_vectors_storage [private]
Vector to store the solution vectors (X_mg)
Definition at line 683 of file geometric_multigrid.h.
Referenced by oomph::MGSolver< DIM >::direct_solve(), oomph::MGSolver< DIM >::post_smooth(), oomph::MGSolver< DIM >::pre_smooth(), and oomph::MGSolver< DIM >::residual_norm().
The documentation for this class was generated from the following file:
geometric_multigrid.h