oomph::MacroElementNodeUpdateRefineableFishMesh< ELEMENT > Class Template Reference
Refineable fish shaped mesh with MacroElement-based node update. The fish's back is represented by a specified geometric object. Some or all of the geometric Data in that geometric object may contain unknowns in the global Problem. The dependency on these unknowns is taken into account when setting up the Jacobian matrix of the elements. For this purpose, the element (whose type is specified by the template parameter) must inherit from MacroElementNodeUpdateElementBase.
#include <fish_mesh.template.h>
Public Member Functions
MacroElementNodeUpdateRefineableFishMesh (GeomObject *back_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass pointer GeomObject that defines the fish's back and pointer to timestepper (defaults to (Steady) default timestepper defined in Mesh).
virtual ~MacroElementNodeUpdateRefineableFishMesh ()
Destructor: empty.
void node_update (const bool &update_all_solid_nodes=false)
Resolve mesh update: NodeUpdate current nodal positions via sparse MacroElement-based update. [Doesn't make sense to use this mesh with SolidElements anyway, so we buffer the case if update_all_solid_nodes is set to true.].
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::MacroElementNodeUpdateRefineableFishMesh< ELEMENT >
Refineable fish shaped mesh with MacroElement-based node update. The fish's back is represented by a specified geometric object. Some or all of the geometric Data in that geometric object may contain unknowns in the global Problem. The dependency on these unknowns is taken into account when setting up the Jacobian matrix of the elements. For this purpose, the element (whose type is specified by the template parameter) must inherit from MacroElementNodeUpdateElementBase.
Definition at line 197 of file fish_mesh.template.h.
Constructor & Destructor Documentation
MacroElementNodeUpdateRefineableFishMesh()
template<class ELEMENT >
oomph::MacroElementNodeUpdateRefineableFishMesh< ELEMENT >::MacroElementNodeUpdateRefineableFishMesh (GeomObject * back_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass pointer GeomObject that defines the fish's back and pointer to timestepper (defaults to (Steady) default timestepper defined in Mesh).
Definition at line 205 of file fish_mesh.template.h.
References oomph::FishMesh< ELEMENT >::Back_pt, oomph::FishMesh< ELEMENT >::domain_pt(), oomph::Mesh::element_pt(), i, oomph::MacroElementNodeUpdateMesh::macro_domain_pt(), oomph::Mesh::nelement(), oomph::MacroElementNodeUpdateMesh::set_geom_object_vector_pt(), and oomph::Global_string_for_annotation::string().
 MacroElementNodeUpdateRefineableFishMesh()
template<class ELEMENT >
virtual oomph::MacroElementNodeUpdateRefineableFishMesh< ELEMENT >::~MacroElementNodeUpdateRefineableFishMesh () [inline], [virtual]
Destructor: empty.
Definition at line 284 of file fish_mesh.template.h.
Member Function Documentation
node_update()
template<class ELEMENT >
void oomph::MacroElementNodeUpdateRefineableFishMesh< ELEMENT >::node_update (const bool & update_all_solid_nodes = false) [inline], [virtual]
Resolve mesh update: NodeUpdate current nodal positions via sparse MacroElement-based update. [Doesn't make sense to use this mesh with SolidElements anyway, so we buffer the case if update_all_solid_nodes is set to true.].
Reimplemented from oomph::MacroElementNodeUpdateMesh.
Definition at line 291 of file fish_mesh.template.h.
References oomph::MacroElementNodeUpdateMesh::node_update(), and oomph::Global_string_for_annotation::string().
The documentation for this class was generated from the following file:
fish_mesh.template.h