oomph::RefineableAlgebraicChannelWithLeafletMesh< ELEMENT > Class Template Reference
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
#include <channel_with_leaflet_mesh.template.h>
Public Member Functions
RefineableAlgebraicChannelWithLeafletMesh (GeomObject *leaflet_pt, const double &lleft, const double &lright, const double &hleaflet, const double &htot, const unsigned &nleft, const unsigned &nright, const unsigned &ny1, const unsigned &ny2, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass pointer to GeomObject that represents the leaflet, the length of the domain to left and right of the leaflet, the height of the leaflet and the overall height of the channel, the number of element columns to the left and right of the leaflet, the number of rows of elements from the bottom of the channel to the end of the leaflet, the number of rows of elements above the end of the leaflet. Timestepper defaults to Steady default Timestepper defined in the Mesh base class.
void update_node_update (AlgebraicNode *&node_pt)
Update the node update data for specified node following any mesh adapation.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::RefineableAlgebraicChannelWithLeafletMesh< ELEMENT >
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Refineable version of algebraic ChannelWithLeafletMesh
Definition at line 469 of file channel_with_leaflet_mesh.template.h.
Constructor & Destructor Documentation
RefineableAlgebraicChannelWithLeafletMesh()
template<class ELEMENT >
oomph::RefineableAlgebraicChannelWithLeafletMesh< ELEMENT >::RefineableAlgebraicChannelWithLeafletMesh (GeomObject * leaflet_pt, const double & lleft, const double & lright, const double & hleaflet, const double & htot, const unsigned & nleft, const unsigned & nright, const unsigned & ny1, const unsigned & ny2, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass pointer to GeomObject that represents the leaflet, the length of the domain to left and right of the leaflet, the height of the leaflet and the overall height of the channel, the number of element columns to the left and right of the leaflet, the number of rows of elements from the bottom of the channel to the end of the leaflet, the number of rows of elements above the end of the leaflet. Timestepper defaults to Steady default Timestepper defined in the Mesh base class.
Definition at line 483 of file channel_with_leaflet_mesh.template.h.
References oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest().
Member Function Documentation
update_node_update()
template<class ELEMENT >
void oomph::RefineableAlgebraicChannelWithLeafletMesh< ELEMENT >::update_node_update (AlgebraicNode *& node_pt) [virtual]
Update the node update data for specified node following any mesh adapation.
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Update the node update functions
Reimplemented from oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >.
Definition at line 639 of file channel_with_leaflet_mesh.template.cc.
References oomph::AlgebraicNode::add_node_update_info(), oomph::AlgebraicNode::kill_node_update_info(), oomph::GeomObject::locate_zeta(), oomph::AlgebraicNode::node_update_fct_id(), s, oomph::AlgebraicNode::vector_geom_object_pt(), and oomph::AlgebraicNode::vector_ref_value().
The documentation for this class was generated from the following files:
channel_with_leaflet_mesh.template.h
channel_with_leaflet_mesh.template.cc