oomph::PoissonEquations< DIM > Class Template Reference
A class for all isoparametric elements that solve the Poisson equations.
#include <poisson_elements.h>
Public Types
typedef void(* PoissonSourceFctPt) (const Vector< double > &x, double &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
typedef void(* PoissonSourceFctGradientPt) (const Vector< double > &x, Vector< double > &gradient)
Function pointer to gradient of source function fct(x,g(x)) -- x is a Vector!
Public Member Functions
PoissonEquations ()
Constructor (must initialise the Source_fct_pt to null)
PoissonEquations (const PoissonEquations &dummy)=delete
Broken copy constructor.
void operator= (const PoissonEquations &)=delete
Broken assignment operator.
virtual unsigned u_index_poisson () const
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the poisson equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
void point_output_data (const Vector< double > &s, Vector< double > &data)
Output solution in data vector at local cordinates s: x,y [,z], u.
unsigned nscalar_paraview () const
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
std::string scalar_name_paraview (const unsigned &i) const
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &n_plot)
Output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (dummy time-dependent version to keep intel compiler happy)
void compute_norm (double &norm)
Compute norm of solution: square of the L2 norm.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
PoissonSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
PoissonSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
PoissonSourceFctGradientPt & source_fct_gradient_pt ()
Access function: Pointer to gradient of source function.
PoissonSourceFctGradientPt source_fct_gradient_pt () const
Access function: Pointer to gradient source function. Const version.
virtual void get_source_poisson (const unsigned &ipt, const Vector< double > &x, double &source) const
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
virtual void get_source_gradient_poisson (const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient) const
Get gradient of source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: flux[i] = du/dx_i.
void get_dflux_dnodal_u (const Vector< double > &s, Vector< Vector< double > > &dflux_dnodal_u) const
Get derivative of flux w.r.t. to nodal values: dflux_dnodal_u[i][j] = d (du/dx_i) / dU_j.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and element Jacobian matrix (wrapper)
virtual double interpolated_u_poisson (const Vector< double > &s) const
Return FE representation of function value u_poisson(s) at local coordinate s.
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}.
unsigned self_test ()
Self-test: Return 0 for OK.
Protected Member Functions
virtual double dshape_and_dtest_eulerian_poisson (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_poisson (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_poisson (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
virtual void fill_in_generic_residual_contribution_poisson (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Protected Attributes
PoissonSourceFctPt Source_fct_pt
Pointer to source function:
PoissonSourceFctGradientPt Source_fct_gradient_pt
Pointer to gradient of source function.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::PoissonEquations< DIM >
A class for all isoparametric elements that solve the Poisson equations.
 \frac{\partial^2 u}{\partial x_i^2} = f(x_j) 
 This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
Definition at line 55 of file poisson_elements.h.
Member Typedef Documentation
PoissonSourceFctGradientPt
template<unsigned DIM>
typedef void(* oomph::PoissonEquations< DIM >::PoissonSourceFctGradientPt) (const Vector< double > &x, Vector< double > &gradient)
Function pointer to gradient of source function fct(x,g(x)) -- x is a Vector!
Definition at line 65 of file poisson_elements.h.
PoissonSourceFctPt
template<unsigned DIM>
typedef void(* oomph::PoissonEquations< DIM >::PoissonSourceFctPt) (const Vector< double > &x, double &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
Definition at line 60 of file poisson_elements.h.
Constructor & Destructor Documentation
PoissonEquations() [1/2]
template<unsigned DIM>
oomph::PoissonEquations< DIM >::PoissonEquations () [inline]
Constructor (must initialise the Source_fct_pt to null)
Definition at line 70 of file poisson_elements.h.
PoissonEquations() [2/2]
template<unsigned DIM>
oomph::PoissonEquations< DIM >::PoissonEquations (const PoissonEquations< DIM > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
compute_error() [1/2]
template<unsigned DIM>
void oomph::PoissonEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution.
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 500 of file poisson_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
compute_error() [2/2]
template<unsigned DIM>
void oomph::PoissonEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [inline], [virtual]
Dummy, time dependent error checker.
Reimplemented from oomph::FiniteElement.
Definition at line 268 of file poisson_elements.h.
compute_norm()
template<unsigned DIM>
void oomph::PoissonEquations< DIM >::compute_norm (double & norm) [virtual]
Compute norm of solution: square of the L2 norm.
Compute norm of the solution.
Reimplemented from oomph::GeneralisedElement.
Definition at line 447 of file poisson_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
dshape_and_dtest_eulerian_at_knot_poisson() [1/2]
template<unsigned DIM>
virtual double oomph::PoissonEquations< DIM >::dshape_and_dtest_eulerian_at_knot_poisson (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implemented in oomph::QPoissonElement< DIM, NNODE_1D >, oomph::QPoissonElement< DIM, 2 >, oomph::QSpectralPoissonElement< DIM, NNODE_1D >, and oomph::TPoissonElement< DIM, NNODE_1D >.
dshape_and_dtest_eulerian_at_knot_poisson() [2/2]
template<unsigned DIM>
virtual double oomph::PoissonEquations< DIM >::dshape_and_dtest_eulerian_at_knot_poisson (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::QPoissonElement< DIM, NNODE_1D >, oomph::QPoissonElement< DIM, 2 >, oomph::QSpectralPoissonElement< DIM, NNODE_1D >, and oomph::TPoissonElement< DIM, NNODE_1D >.
dshape_and_dtest_eulerian_poisson()
template<unsigned DIM>
virtual double oomph::PoissonEquations< DIM >::dshape_and_dtest_eulerian_poisson (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in oomph::QPoissonElement< DIM, NNODE_1D >, oomph::QPoissonElement< DIM, 2 >, oomph::QSpectralPoissonElement< DIM, NNODE_1D >, and oomph::TPoissonElement< DIM, NNODE_1D >.
fill_in_contribution_to_jacobian()
template<unsigned DIM>
void oomph::PoissonEquations< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and element Jacobian matrix (wrapper)
Reimplemented from oomph::FiniteElement.
Definition at line 435 of file poisson_elements.h.
References oomph::PoissonEquations< DIM >::fill_in_generic_residual_contribution_poisson().
fill_in_contribution_to_residuals()
template<unsigned DIM>
void oomph::PoissonEquations< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 424 of file poisson_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::PoissonEquations< DIM >::fill_in_generic_residual_contribution_poisson().
fill_in_generic_residual_contribution_poisson()
template<unsigned DIM>
void oomph::PoissonEquations< DIM >::fill_in_generic_residual_contribution_poisson (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected], [virtual]
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Compute element residual Vector and/or element Jacobian matrix.
flag=1: compute both flag=0: compute only residual Vector
Pure version without hanging nodes
Reimplemented in oomph::RefineablePoissonEquations< DIM >.
Definition at line 49 of file poisson_elements.cc.
References i, and oomph::QuadTreeNames::W.
Referenced by oomph::PoissonEquations< DIM >::fill_in_contribution_to_jacobian(), and oomph::PoissonEquations< DIM >::fill_in_contribution_to_residuals().
get_dflux_dnodal_u()
template<unsigned DIM>
void oomph::PoissonEquations< DIM >::get_dflux_dnodal_u (const Vector< double > & s, Vector< Vector< double > > & dflux_dnodal_u) const [inline]
Get derivative of flux w.r.t. to nodal values: dflux_dnodal_u[i][j] = d (du/dx_i) / dU_j.
Definition at line 399 of file poisson_elements.h.
References oomph::FiniteElement::dshape_eulerian(), i, oomph::FiniteElement::nnode(), and s.
get_dresidual_dnodal_coordinates()
template<unsigned DIM>
void oomph::PoissonEquations< DIM >::get_dresidual_dnodal_coordinates (RankThreeTensor< double > & dresidual_dnodal_coordinates) [virtual]
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}.
Compute derivatives of elemental residual vector with respect to nodal coordinates (fully analytical). dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij} Overloads the FD-based version in the FE base class.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::RefineablePoissonEquations< DIM >.
Definition at line 165 of file poisson_elements.cc.
References i.
get_flux()
template<unsigned DIM>
void oomph::PoissonEquations< DIM >::get_flux (const Vector< double > & s, Vector< double > & flux) const [inline]
Get flux: flux[i] = du/dx_i.
Definition at line 364 of file poisson_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, and oomph::PoissonEquations< DIM >::u_index_poisson().
Referenced by oomph::PRefineableQPoissonElement< DIM >::compute_energy_error(), oomph::RefineablePoissonEquations< DIM >::get_Z2_flux(), and oomph::TPoissonElement< DIM, NNODE_1D >::get_Z2_flux().
get_source_gradient_poisson()
template<unsigned DIM>
virtual void oomph::PoissonEquations< DIM >::get_source_gradient_poisson (const unsigned & ipt, const Vector< double > & x, Vector< double > & gradient) const [inline], [virtual]
Get gradient of source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations. Computed via function pointer (if set) or by finite differencing (default)
Definition at line 331 of file poisson_elements.h.
References oomph::GeneralisedElement::Default_fd_jacobian_step, oomph::PoissonEquations< DIM >::get_source_poisson(), i, and oomph::PoissonEquations< DIM >::Source_fct_gradient_pt.
get_source_poisson()
template<unsigned DIM>
virtual void oomph::PoissonEquations< DIM >::get_source_poisson (const unsigned & ipt, const Vector< double > & x, double & source) const [inline], [virtual]
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
Definition at line 309 of file poisson_elements.h.
References oomph::PoissonEquations< DIM >::Source_fct_pt.
Referenced by oomph::PoissonEquations< DIM >::get_source_gradient_poisson().
interpolated_u_poisson()
template<unsigned DIM>
virtual double oomph::PoissonEquations< DIM >::interpolated_u_poisson (const Vector< double > & s) const [inline], [virtual]
Return FE representation of function value u_poisson(s) at local coordinate s.
Definition at line 445 of file poisson_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and oomph::PoissonEquations< DIM >::u_index_poisson().
Referenced by oomph::PoissonEquations< DIM >::point_output_data(), and oomph::PoissonEquations< DIM >::scalar_value_paraview().
nscalar_paraview()
template<unsigned DIM>
unsigned oomph::PoissonEquations< DIM >::nscalar_paraview () const [inline], [virtual]
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
Reimplemented from oomph::FiniteElement.
Definition at line 112 of file poisson_elements.h.
operator=()
template<unsigned DIM>
void oomph::PoissonEquations< DIM >::operator= (const PoissonEquations< DIM > &) [delete]
Broken assignment operator.
output() [1/4]
template<unsigned DIM>
void oomph::PoissonEquations< DIM >::output (FILE * file_pt) [inline], [virtual]
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPoissonElement< DIM, NNODE_1D >, oomph::QPoissonElement< DIM, 2 >, oomph::QSpectralPoissonElement< DIM, NNODE_1D >, and oomph::TPoissonElement< DIM, NNODE_1D >.
Definition at line 225 of file poisson_elements.h.
References oomph::PoissonEquations< DIM >::output().
output() [2/4]
template<unsigned DIM>
void oomph::PoissonEquations< DIM >::output (FILE * file_pt, const unsigned & nplot) [virtual]
C-style output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points.
C-style output function:
x,y,u or x,y,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPoissonElement< DIM, NNODE_1D >, oomph::QPoissonElement< DIM, 2 >, oomph::QSpectralPoissonElement< DIM, NNODE_1D >, and oomph::TPoissonElement< DIM, NNODE_1D >.
Definition at line 364 of file poisson_elements.cc.
References i, and s.
output() [3/4]
template<unsigned DIM>
void oomph::PoissonEquations< DIM >::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPoissonElement< DIM, NNODE_1D >, oomph::QPoissonElement< DIM, 2 >, oomph::QSpectralPoissonElement< DIM, NNODE_1D >, and oomph::TPoissonElement< DIM, NNODE_1D >.
Definition at line 214 of file poisson_elements.h.
References oomph::PoissonEquations< DIM >::output().
Referenced by oomph::PoissonEquations< DIM >::output(), oomph::QPoissonElement< DIM, NNODE_1D >::output(), oomph::QSpectralPoissonElement< DIM, NNODE_1D >::output(), and oomph::TPoissonElement< DIM, NNODE_1D >::output().
output() [4/4]
template<unsigned DIM>
void oomph::PoissonEquations< DIM >::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points.
Output function:
x,y,u or x,y,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPoissonElement< DIM, NNODE_1D >, oomph::QPoissonElement< DIM, 2 >, oomph::QSpectralPoissonElement< DIM, NNODE_1D >, and oomph::TPoissonElement< DIM, NNODE_1D >.
Definition at line 328 of file poisson_elements.cc.
References i, and s.
output_fct() [1/2]
template<unsigned DIM>
virtual void oomph::PoissonEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output exact soln: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (dummy time-dependent version to keep intel compiler happy)
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPoissonElement< DIM, NNODE_1D >, oomph::QPoissonElement< DIM, 2 >, oomph::QSpectralPoissonElement< DIM, NNODE_1D >, and oomph::TPoissonElement< DIM, NNODE_1D >.
Definition at line 244 of file poisson_elements.h.
output_fct() [2/2]
template<unsigned DIM>
void oomph::PoissonEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
Output exact solution.
Solution is provided via function pointer. Plot at a given number of plot points.
x,y,u_exact or x,y,z,u_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPoissonElement< DIM, NNODE_1D >, oomph::QPoissonElement< DIM, 2 >, oomph::QSpectralPoissonElement< DIM, NNODE_1D >, and oomph::TPoissonElement< DIM, NNODE_1D >.
Definition at line 400 of file poisson_elements.cc.
References i, and s.
Referenced by oomph::QPoissonElement< DIM, NNODE_1D >::output_fct(), oomph::QSpectralPoissonElement< DIM, NNODE_1D >::output_fct(), and oomph::TPoissonElement< DIM, NNODE_1D >::output_fct().
point_output_data()
template<unsigned DIM>
void oomph::PoissonEquations< DIM >::point_output_data (const Vector< double > & s, Vector< double > & data) [inline], [virtual]
Output solution in data vector at local cordinates s: x,y [,z], u.
Reimplemented from oomph::FiniteElement.
Definition at line 93 of file poisson_elements.h.
References oomph::FiniteElement::dim(), i, oomph::PoissonEquations< DIM >::interpolated_u_poisson(), oomph::FiniteElement::interpolated_x(), and s.
scalar_name_paraview()
template<unsigned DIM>
std::string oomph::PoissonEquations< DIM >::scalar_name_paraview (const unsigned & i) const [inline], [virtual]
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
Reimplemented from oomph::FiniteElement.
Definition at line 149 of file poisson_elements.h.
References i.
scalar_value_fct_paraview()
template<unsigned DIM>
void oomph::PoissonEquations< DIM >::scalar_value_fct_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const [inline], [virtual]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
Definition at line 169 of file poisson_elements.h.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points_paraview(), and s.
scalar_value_paraview()
template<unsigned DIM>
void oomph::PoissonEquations< DIM >::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const [inline], [virtual]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
Definition at line 119 of file poisson_elements.h.
References oomph::FiniteElement::get_s_plot(), i, oomph::PoissonEquations< DIM >::interpolated_u_poisson(), oomph::FiniteElement::nplot_points_paraview(), and s.
self_test()
template<unsigned DIM>
unsigned oomph::PoissonEquations< DIM >::self_test [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
Definition at line 298 of file poisson_elements.cc.
References oomph::FiniteElement::self_test().
source_fct_gradient_pt() [1/2]
template<unsigned DIM>
PoissonSourceFctGradientPt & oomph::PoissonEquations< DIM >::source_fct_gradient_pt () [inline]
Access function: Pointer to gradient of source function.
Definition at line 293 of file poisson_elements.h.
References oomph::PoissonEquations< DIM >::Source_fct_gradient_pt.
source_fct_gradient_pt() [2/2]
template<unsigned DIM>
PoissonSourceFctGradientPt oomph::PoissonEquations< DIM >::source_fct_gradient_pt () const [inline]
Access function: Pointer to gradient source function. Const version.
Definition at line 299 of file poisson_elements.h.
References oomph::PoissonEquations< DIM >::Source_fct_gradient_pt.
source_fct_pt() [1/2]
template<unsigned DIM>
PoissonSourceFctPt & oomph::PoissonEquations< DIM >::source_fct_pt () [inline]
Access function: Pointer to source function.
Definition at line 281 of file poisson_elements.h.
References oomph::PoissonEquations< DIM >::Source_fct_pt.
Referenced by oomph::RefineablePoissonEquations< DIM >::further_build().
source_fct_pt() [2/2]
template<unsigned DIM>
PoissonSourceFctPt oomph::PoissonEquations< DIM >::source_fct_pt () const [inline]
Access function: Pointer to source function. Const version.
Definition at line 287 of file poisson_elements.h.
References oomph::PoissonEquations< DIM >::Source_fct_pt.
u_index_poisson()
template<unsigned DIM>
virtual unsigned oomph::PoissonEquations< DIM >::u_index_poisson () const [inline], [virtual]
Return the index at which the unknown value is stored. The default value, 0, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the poisson equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
Definition at line 85 of file poisson_elements.h.
Referenced by oomph::PoissonEquations< DIM >::get_flux(), oomph::RefineablePoissonEquations< DIM >::get_interpolated_values(), oomph::PoissonEquations< DIM >::interpolated_u_poisson(), and oomph::PoissonFluxElement< ELEMENT >::PoissonFluxElement().
Member Data Documentation
Source_fct_gradient_pt
template<unsigned DIM>
PoissonSourceFctGradientPt oomph::PoissonEquations< DIM >::Source_fct_gradient_pt [protected]
Pointer to gradient of source function.
Definition at line 526 of file poisson_elements.h.
Referenced by oomph::PoissonEquations< DIM >::get_source_gradient_poisson(), and oomph::PoissonEquations< DIM >::source_fct_gradient_pt().
Source_fct_pt
template<unsigned DIM>
PoissonSourceFctPt oomph::PoissonEquations< DIM >::Source_fct_pt [protected]
Pointer to source function:
Definition at line 523 of file poisson_elements.h.
Referenced by oomph::RefineablePoissonEquations< DIM >::further_build(), oomph::PoissonEquations< DIM >::get_source_poisson(), and oomph::PoissonEquations< DIM >::source_fct_pt().
The documentation for this class was generated from the following files:
poisson_elements.h
poisson_elements.cc