oomph::ElementWithZ2ErrorEstimator Class Reference
Base class for finite elements that can compute the quantities that are required for the Z2 error estimator.
#include <error_estimator.h>
Public Member Functions
ElementWithZ2ErrorEstimator ()
Default empty constructor.
ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &)
Broken copy constructor.
void operator= (const ElementWithZ2ErrorEstimator &)
Broken assignment operator.
virtual unsigned num_Z2_flux_terms ()=0
Number of 'flux' terms for Z2 error estimation.
virtual unsigned ncompound_fluxes ()
A stuitable error estimator for a multi-physics elements may require one Z2 error estimate for each field (e.g. velocity and temperature in a fluid convection problem). It is assumed that these error estimates will each use selected flux terms. The number of compound fluxes returns the number of such combinations of the flux terms. Default value is one and all flux terms are combined with equal weight.
virtual void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)=0
Z2 'flux' terms for Z2 error estimation.
virtual void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
Plot the error when compared against a given exact flux. Also calculates the norm of the error and that of the exact flux.
virtual void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
Return the compound flux index of each flux component The default (do nothing behaviour) will mean that all indices remain at the default value zero.
virtual unsigned nvertex_node () const =0
Number of vertex nodes in the element.
virtual Node * vertex_node_pt (const unsigned &j) const =0
Pointer to the j-th vertex node in the element. Needed for efficient patch assmbly.
virtual unsigned nrecovery_order ()=0
Order of recovery shape functions.
virtual double geometric_jacobian (const Vector< double > &x)
Return the geometric jacobian (should be overloaded in cylindrical and spherical geometries). Default value one is suitable for Cartesian coordinates.
Additional Inherited Members
Detailed Description
Base class for finite elements that can compute the quantities that are required for the Z2 error estimator.
Definition at line 84 of file error_estimator.h.
Constructor & Destructor Documentation
ElementWithZ2ErrorEstimator() [1/2]
oomph::ElementWithZ2ErrorEstimator::ElementWithZ2ErrorEstimator () [inline]
Default empty constructor.
Definition at line 88 of file error_estimator.h.
ElementWithZ2ErrorEstimator() [2/2]
oomph::ElementWithZ2ErrorEstimator::ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &) [inline]
Broken copy constructor.
Definition at line 91 of file error_estimator.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
compute_exact_Z2_error()
virtual void oomph::ElementWithZ2ErrorEstimator::compute_exact_Z2_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double & error, double & norm) [inline], [virtual]
Plot the error when compared against a given exact flux. Also calculates the norm of the error and that of the exact flux.
Reimplemented in oomph::RefineablePoissonEquations< DIM >.
Definition at line 122 of file error_estimator.h.
References oomph::Global_string_for_annotation::string().
geometric_jacobian()
virtual double oomph::ElementWithZ2ErrorEstimator::geometric_jacobian (const Vector< double > & x) [inline], [virtual]
Return the geometric jacobian (should be overloaded in cylindrical and spherical geometries). Default value one is suitable for Cartesian coordinates.
Reimplemented in oomph::RefineableAxisymAdvectionDiffusionEquations, oomph::RefineableSphericalAdvectionDiffusionEquations, oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations, oomph::RefineableLinearisedAxisymmetricNavierStokesEquations, oomph::RefineableAxisymmetricNavierStokesEquations, oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations, and oomph::RefineableSphericalNavierStokesEquations.
Definition at line 154 of file error_estimator.h.
Referenced by oomph::Z2ErrorEstimator::get_element_errors(), and oomph::Z2ErrorEstimator::get_recovered_flux_in_patch().
get_Z2_compound_flux_indices()
virtual void oomph::ElementWithZ2ErrorEstimator::get_Z2_compound_flux_indices (Vector< unsigned > & flux_index) [inline], [virtual]
Return the compound flux index of each flux component The default (do nothing behaviour) will mean that all indices remain at the default value zero.
Reimplemented in oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >.
Definition at line 139 of file error_estimator.h.
Referenced by oomph::Z2ErrorEstimator::get_element_errors().
get_Z2_flux()
virtual void oomph::ElementWithZ2ErrorEstimator::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [pure virtual]
Z2 'flux' terms for Z2 error estimation.
Implemented in oomph::TPVDElementWithContinuousPressure< DIM >, oomph::TPVDBubbleEnrichedElement< DIM, NNODE_1D >, oomph::TPVDElement< DIM, NNODE_1D >, oomph::AxisymmetricPoroelasticityEquations, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::TTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >, oomph::AxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, oomph::DarcyEquations< DIM >, oomph::DarcyEquations< 2 >, oomph::SpectralPeriodicOrbitElement< NNODE_1D >, oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::RefineableNavierStokesEquations< DIM >, oomph::RefineablePVDEquationsWithPressure< DIM >, oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >, oomph::TCrouzeixRaviartElement< DIM >, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::TUnsteadyHeatElement< DIM, NNODE_1D >, oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::TPoissonElement< DIM, NNODE_1D >, oomph::TPMLHelmholtzElement< DIM, NNODE_1D >, oomph::THelmholtzElement< DIM, NNODE_1D >, oomph::TFoepplvonKarmanElement< NNODE_1D >, oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::TLinearElasticityElement< DIM, NNODE_1D >, oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >, oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >, oomph::RefineablePolarNavierStokesEquations, oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >, oomph::RefineableLinearElasticityEquations< DIM >, oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations, oomph::RefineableUnsteadyHeatEquations< DIM >, oomph::RefineableHelmholtzEquations< DIM >, oomph::RefineablePMLHelmholtzEquations< DIM >, oomph::RefineableAxisymAdvectionDiffusionEquations, oomph::RefineableYoungLaplaceEquations, oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >, oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >, oomph::RefineableSphericalAdvectionDiffusionEquations, oomph::RefineableAdvectionDiffusionEquations< DIM >, oomph::RefineablePoissonEquations< DIM >, oomph::RefineablePVDEquations< DIM >, oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >, oomph::RefineableLinearisedAxisymmetricNavierStokesEquations, oomph::RefineableLinearisedNavierStokesEquations, oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::RefineableAxisymmetricNavierStokesEquations, oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations, oomph::RefineableLinearWaveEquations< DIM >, and oomph::RefineableSphericalNavierStokesEquations.
Referenced by oomph::Z2ErrorEstimator::doc_flux(), oomph::Z2ErrorEstimator::get_element_errors(), and oomph::Z2ErrorEstimator::get_recovered_flux_in_patch().
ncompound_fluxes()
virtual unsigned oomph::ElementWithZ2ErrorEstimator::ncompound_fluxes () [inline], [virtual]
A stuitable error estimator for a multi-physics elements may require one Z2 error estimate for each field (e.g. velocity and temperature in a fluid convection problem). It is assumed that these error estimates will each use selected flux terms. The number of compound fluxes returns the number of such combinations of the flux terms. Default value is one and all flux terms are combined with equal weight.
Reimplemented in oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >.
Definition at line 112 of file error_estimator.h.
Referenced by oomph::Z2ErrorEstimator::get_element_errors().
nrecovery_order()
virtual unsigned oomph::ElementWithZ2ErrorEstimator::nrecovery_order () [pure virtual]
Order of recovery shape functions.
Implemented in oomph::TPVDElementWithContinuousPressure< DIM >, oomph::TPVDBubbleEnrichedElement< DIM, NNODE_1D >, oomph::TPVDElement< DIM, NNODE_1D >, oomph::PRefineableQCrouzeixRaviartElement< DIM >, oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::RefineableQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::TTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >, oomph::RefineableQPVDElementWithContinuousPressure< DIM >, oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement, oomph::RefineableAxisymmetricQCrouzeixRaviartElement, oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::AxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::RefineableQTaylorHoodElement< DIM >, oomph::RefineablePolarCrouzeixRaviartElement, oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement, oomph::RefineableLinearisedQTaylorHoodElement, oomph::RefineableQSphericalCrouzeixRaviartElement, oomph::TAxisymmetricPoroelasticityElement< ORDER >, oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement, oomph::RefineableAxisymmetricQTaylorHoodElement, oomph::RefineableQPVDElementWithPressure< DIM >, oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >, oomph::SpectralPeriodicOrbitElement< NNODE_1D >, oomph::RefineableQAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >, oomph::RefineableQAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::RefineableQAdvectionDiffusionElement< DIM, 3 >, oomph::TRaviartThomasDarcyElement< ORDER >, oomph::TRaviartThomasDarcyElement< ORDER >, oomph::RefineableLinearisedQCrouzeixRaviartElement, oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement, oomph::PRefineableQPoissonElement< DIM >, oomph::RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >, oomph::PRefineableQLinearElasticityElement< DIM >, oomph::RefineablePolarTaylorHoodElement, oomph::RefineableQSphericalTaylorHoodElement, oomph::RefineableQUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::RefineableQPMLHelmholtzElement< DIM, NNODE_1D >, oomph::RefineableQPMLHelmholtzElement< 2, NNODE_1D >, oomph::RefineableQUnsteadyHeatElement< DIM, NNODE_1D >, oomph::RefineableQHelmholtzElement< DIM, NNODE_1D >, oomph::TCrouzeixRaviartElement< DIM >, oomph::RefineableQPoissonElement< DIM, NNODE_1D >, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::RefineableQLinearWaveElement< DIM, NNODE_1D >, oomph::RefineableQTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::RefineableQYoungLaplaceElement< NNODE_1D >, oomph::RefineableQLinearElasticityElement< DIM, NNODE_1D >, oomph::RefineableQPVDElement< DIM, NNODE_1D >, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::TUnsteadyHeatElement< DIM, NNODE_1D >, oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::TPoissonElement< DIM, NNODE_1D >, oomph::TPMLHelmholtzElement< DIM, NNODE_1D >, oomph::THelmholtzElement< DIM, NNODE_1D >, oomph::TFoepplvonKarmanElement< NNODE_1D >, oomph::TRaviartThomasDarcyElement< ORDER >, oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::TLinearElasticityElement< DIM, NNODE_1D >, oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >, and oomph::RefineableQSpectralPoissonElement< DIM, NNODE_1D >.
Referenced by oomph::Z2ErrorEstimator::get_element_errors(), and oomph::Z2ErrorEstimator::setup_patches().
num_Z2_flux_terms()
virtual unsigned oomph::ElementWithZ2ErrorEstimator::num_Z2_flux_terms () [pure virtual]
Number of 'flux' terms for Z2 error estimation.
Implemented in oomph::TPVDElementWithContinuousPressure< DIM >, oomph::TPVDBubbleEnrichedElement< DIM, NNODE_1D >, oomph::TPVDElement< DIM, NNODE_1D >, oomph::AxisymmetricPoroelasticityEquations, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::TTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >, oomph::AxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, oomph::DarcyEquations< DIM >, oomph::DarcyEquations< 2 >, oomph::SpectralPeriodicOrbitElement< NNODE_1D >, oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::RefineableNavierStokesEquations< DIM >, oomph::RefineablePVDEquationsWithPressure< DIM >, oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >, oomph::TCrouzeixRaviartElement< DIM >, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::TUnsteadyHeatElement< DIM, NNODE_1D >, oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::TPoissonElement< DIM, NNODE_1D >, oomph::TPMLHelmholtzElement< DIM, NNODE_1D >, oomph::THelmholtzElement< DIM, NNODE_1D >, oomph::TFoepplvonKarmanElement< NNODE_1D >, oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::TLinearElasticityElement< DIM, NNODE_1D >, oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >, oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >, oomph::RefineablePolarNavierStokesEquations, oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >, oomph::RefineableLinearElasticityEquations< DIM >, oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations, oomph::RefineableUnsteadyHeatEquations< DIM >, oomph::RefineableHelmholtzEquations< DIM >, oomph::RefineablePMLHelmholtzEquations< DIM >, oomph::RefineableAxisymAdvectionDiffusionEquations, oomph::RefineableYoungLaplaceEquations, oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >, oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >, oomph::RefineableSphericalAdvectionDiffusionEquations, oomph::RefineableAdvectionDiffusionEquations< DIM >, oomph::RefineablePoissonEquations< DIM >, oomph::RefineablePVDEquations< DIM >, oomph::RefineableLinearisedAxisymmetricNavierStokesEquations, oomph::RefineableLinearisedNavierStokesEquations, oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >, oomph::RefineableLinearWaveEquations< DIM >, oomph::RefineableAxisymmetricNavierStokesEquations, oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations, oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, and oomph::RefineableSphericalNavierStokesEquations.
Referenced by oomph::Z2ErrorEstimator::get_element_errors().
nvertex_node()
virtual unsigned oomph::ElementWithZ2ErrorEstimator::nvertex_node () const [pure virtual]
Number of vertex nodes in the element.
Reimplemented from oomph::FiniteElement.
Implemented in oomph::TPVDElementWithContinuousPressure< DIM >, oomph::TPVDBubbleEnrichedElement< DIM, NNODE_1D >, oomph::TPVDElement< DIM, NNODE_1D >, oomph::PRefineableQCrouzeixRaviartElement< DIM >, oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::RefineableQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::TTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >, oomph::RefineableQPVDElementWithContinuousPressure< DIM >, oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement, oomph::RefineableAxisymmetricQCrouzeixRaviartElement, oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::AxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::RefineableQTaylorHoodElement< DIM >, oomph::RefineablePolarCrouzeixRaviartElement, oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement, oomph::RefineableLinearisedQTaylorHoodElement, oomph::RefineableQSphericalCrouzeixRaviartElement, oomph::TAxisymmetricPoroelasticityElement< ORDER >, oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement, oomph::RefineableAxisymmetricQTaylorHoodElement, oomph::SpectralPeriodicOrbitElement< NNODE_1D >, oomph::RefineableQPVDElementWithPressure< DIM >, oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >, oomph::RefineableQAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >, oomph::RefineableLinearisedQCrouzeixRaviartElement, oomph::RefineableQAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::TRaviartThomasDarcyElement< ORDER >, oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement, oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >, oomph::PRefineableQPoissonElement< DIM >, oomph::RefineablePolarTaylorHoodElement, oomph::RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::RefineableQSphericalTaylorHoodElement, oomph::PRefineableQLinearElasticityElement< DIM >, oomph::RefineableQUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::TCrouzeixRaviartElement< DIM >, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >, oomph::RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::RefineableQPMLHelmholtzElement< DIM, NNODE_1D >, oomph::RefineableQUnsteadyHeatElement< DIM, NNODE_1D >, oomph::RefineableQHelmholtzElement< DIM, NNODE_1D >, oomph::RefineableQPoissonElement< DIM, NNODE_1D >, oomph::RefineableQTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::RefineableQLinearWaveElement< DIM, NNODE_1D >, oomph::RefineableQYoungLaplaceElement< NNODE_1D >, oomph::RefineableQLinearElasticityElement< DIM, NNODE_1D >, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::TUnsteadyHeatElement< DIM, NNODE_1D >, oomph::TPMLHelmholtzElement< DIM, NNODE_1D >, oomph::RefineableQPVDElement< DIM, NNODE_1D >, oomph::THelmholtzElement< DIM, NNODE_1D >, oomph::TPoissonElement< DIM, NNODE_1D >, oomph::TFoepplvonKarmanElement< NNODE_1D >, oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::TLinearElasticityElement< DIM, NNODE_1D >, oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >, and oomph::RefineableQSpectralPoissonElement< DIM, NNODE_1D >.
Referenced by oomph::Z2ErrorEstimator::setup_patches().
operator=()
void oomph::ElementWithZ2ErrorEstimator::operator= (const ElementWithZ2ErrorEstimator &) [inline]
Broken assignment operator.
Definition at line 97 of file error_estimator.h.
References oomph::BrokenCopy::broken_assign().
vertex_node_pt()
virtual Node* oomph::ElementWithZ2ErrorEstimator::vertex_node_pt (const unsigned & j) const [pure virtual]
Pointer to the j-th vertex node in the element. Needed for efficient patch assmbly.
Reimplemented from oomph::FiniteElement.
Implemented in oomph::TPVDElementWithContinuousPressure< DIM >, oomph::TPVDBubbleEnrichedElement< DIM, NNODE_1D >, oomph::TPVDElement< DIM, NNODE_1D >, oomph::PRefineableQCrouzeixRaviartElement< DIM >, oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::RefineableQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::TTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >, oomph::RefineableQPVDElementWithContinuousPressure< DIM >, oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement, oomph::RefineableAxisymmetricQCrouzeixRaviartElement, oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::AxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::RefineableQTaylorHoodElement< DIM >, oomph::RefineablePolarCrouzeixRaviartElement, oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement, oomph::RefineableLinearisedQTaylorHoodElement, oomph::RefineableQSphericalCrouzeixRaviartElement, oomph::TAxisymmetricPoroelasticityElement< ORDER >, oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement, oomph::RefineableAxisymmetricQTaylorHoodElement, oomph::SpectralPeriodicOrbitElement< NNODE_1D >, oomph::RefineableQPVDElementWithPressure< DIM >, oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >, oomph::RefineableQAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >, oomph::RefineableLinearisedQCrouzeixRaviartElement, oomph::RefineableQAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::RefineableQAdvectionDiffusionElement< DIM, 3 >, oomph::TRaviartThomasDarcyElement< ORDER >, oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement, oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >, oomph::PRefineableQPoissonElement< DIM >, oomph::RefineablePolarTaylorHoodElement, oomph::RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::RefineableQSphericalTaylorHoodElement, oomph::PRefineableQLinearElasticityElement< DIM >, oomph::RefineableQUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::TCrouzeixRaviartElement< DIM >, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >, oomph::RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::RefineableQPMLHelmholtzElement< DIM, NNODE_1D >, oomph::RefineableQPMLHelmholtzElement< 2, NNODE_1D >, oomph::RefineableQUnsteadyHeatElement< DIM, NNODE_1D >, oomph::RefineableQHelmholtzElement< DIM, NNODE_1D >, oomph::RefineableQPoissonElement< DIM, NNODE_1D >, oomph::RefineableQTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::RefineableQLinearWaveElement< DIM, NNODE_1D >, oomph::RefineableQYoungLaplaceElement< NNODE_1D >, oomph::RefineableQLinearElasticityElement< DIM, NNODE_1D >, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::TUnsteadyHeatElement< DIM, NNODE_1D >, oomph::TPMLHelmholtzElement< DIM, NNODE_1D >, oomph::RefineableQPVDElement< DIM, NNODE_1D >, oomph::THelmholtzElement< DIM, NNODE_1D >, oomph::TPoissonElement< DIM, NNODE_1D >, oomph::TFoepplvonKarmanElement< NNODE_1D >, oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::TLinearElasticityElement< DIM, NNODE_1D >, oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >, and oomph::RefineableQSpectralPoissonElement< DIM, NNODE_1D >.
Referenced by oomph::Z2ErrorEstimator::setup_patches().
The documentation for this class was generated from the following file:
error_estimator.h