oomph::TriangleMesh< ELEMENT > Class Template Reference
Triangle mesh build with the help of the scaffold mesh coming from the triangle mesh generator Triangle. http://www.cs.cmu.edu/~quake/triangle.html.
#include <triangle_mesh.h>
Classes
struct Point
Public Member Functions
TriangleMesh ()
Empty constructor.
TriangleMesh (const std::string &node_file_name, const std::string &element_file_name, const std::string &poly_file_name, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &allow_automatic_creation_of_vertices_on_boundaries=true)
Constructor with the input files.
TriangleMesh (TriangleMeshParameters &triangle_mesh_parameters, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Build mesh, based on the specifications on TriangleMeshParameters.
TriangleMesh (const std::string &poly_file_name, const double &element_area, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &allow_automatic_creation_of_vertices_on_boundaries=true)
Build mesh from poly file, with specified target area for all elements.
TriangleMesh (const TriangleMesh &dummy)=delete
Broken copy constructor.
void operator= (const TriangleMesh &)=delete
Broken assignment operator.
virtual ~TriangleMesh ()
Destructor.
void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Overload set_mesh_level_time_stepper so that the stored time stepper now corresponds to the new timestepper.
void compute_boundary_segments_connectivity_and_initial_zeta_values (const unsigned &b)
Compute the boundary segments connectivity for those boundaries that were splited during the distribution process.
void re_assign_initial_zeta_values_for_internal_boundary (const unsigned &b, Vector< std::list< FiniteElement * > > &old_segment_sorted_ele_pt, std::map< FiniteElement *, bool > &old_is_inverted)
Re-assign the boundary segments initial zeta (arclength) value for those internal boundaries that were splited during the distribution process. Those boundaries that have one face element at each side of the boundary.
void re_scale_re_assigned_initial_zeta_values_for_internal_boundary (const unsigned &b)
Re-scale the re-assigned zeta values for the boundary nodes, apply only for internal boundaries.
void identify_boundary_segments_and_assign_initial_zeta_values (const unsigned &b, Vector< FiniteElement * > &input_face_ele_pt, const bool &is_internal_boundary, std::map< FiniteElement *, FiniteElement * > &face_to_bulk_element_pt)
Identify the segments from the old mesh (original mesh) in the new mesh (this) and assign initial and final boundary coordinates for the segments that create the boundary. (This is the version called from the original mesh to identify its own segments)
void identify_boundary_segments_and_assign_initial_zeta_values (const unsigned &b, TriangleMesh< ELEMENT > *original_mesh_pt)
Identify the segments from the old mesh (original mesh) in the new mesh (this) and assign initial and final boundary coordinates for the segments that create the boundary.
void synchronize_boundary_coordinates (const unsigned &b)
In charge of sinchronize the boundary coordinates for internal boundaries that were split as part of the distribution process. Called after setup_boundary_coordinates() for the original mesh only.
void select_boundary_face_elements (Vector< FiniteElement * > &face_el_pt, const unsigned &b, bool &is_internal_boundary, std::map< FiniteElement *, FiniteElement * > &face_to_bulk_element_pt)
Select face element from boundary using the criteria to decide which of the two face elements should be used on internal boundaries.
Vector< Vector< Node * > > & boundary_segment_node_pt (const unsigned &b)
Return direct access to nodes associated with a boundary but sorted in segments.
Vector< Node * > & boundary_segment_node_pt (const unsigned &b, const unsigned &s)
Return direct access to nodes associated with a segment of a given boundary.
Node *& boundary_segment_node_pt (const unsigned &b, const unsigned &s, const unsigned &n)
Return pointer to node n on boundary b.
void update_triangulateio (Vector< Vector< double > > &internal_point)
Update the TriangulateIO object to the current nodal position and the centre hole coordinates.
void update_triangulateio ()
Update the triangulateio object to the current nodal positions.
void dump_distributed_info_for_restart (std::ostream &dump_file)
Used to dump info. related with distributed triangle meshes.
const unsigned read_unsigned_line_helper (std::istream &read_file)
void read_distributed_info_for_restart (std::istream &restart_file)
Used to read info. related with distributed triangle meshes.
virtual void reestablish_distribution_info_for_restart (OomphCommunicator *comm_pt, std::istream &restart_file)
Virtual function used to re-establish any additional info. related with the distribution after a re-starting for triangle meshes.
void remesh_from_internal_triangulateio ()
Completely regenerate the mesh from the trianglateio structure.
bool triangulateio_exists ()
Boolean defining if Triangulateio object has been built or not.
Vector< unsigned > oomph_vertex_nodes_id ()
Return the vector that contains the oomph-lib node number for all vertex nodes in the TriangulateIO representation of the mesh.
const unsigned initial_shared_boundary_id ()
The initial boundary id for shared boundaries.
const unsigned final_shared_boundary_id ()
The final boundary id for shared boundaries.
virtual void load_balance (const Vector< unsigned > &target_domain_for_local_non_halo_element)
Virtual function to perform the load balance routines.
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned > > &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info routines. Generally used after load balance.
void output_boundary_coordinates (const unsigned &b, std::ostream &outfile)
Output the nodes on the boundary and their respective boundary coordinates(into separate tecplot zones)
Public Member Functions inherited from oomph::TriangleMeshBase
TriangleMeshBase ()
Constructor.
TriangleMeshBase (const TriangleMeshBase &node)=delete
Broken copy constructor.
virtual ~TriangleMeshBase ()
Broken assignment operator.
void setup_boundary_element_info ()
Setup lookup schemes which establish whic elements are located next to mesh's boundaries (wrapper to suppress doc).
void setup_boundary_element_info (std::ostream &outfile)
Setup lookup schemes which establish which elements are located next to mesh's boundaries. Doc in outfile (if it's open).
bool use_triangulateio_restart () const
const access for Use_triangulateio_restart.
void enable_triangulateio_restart ()
write access for Use_triangulateio_restart.
void disable_triangulateio_restart ()
write access for Use_triangulateio_restart.
TriangulateIO & triangulateio_representation ()
Access to the triangulateio representation of the mesh.
void write_triangulateio (TriangulateIO &triangulate_io, std::string &s)
Helper function. Write a TriangulateIO object file with all the triangulateio fields. String s is add to assign a different value for the input and/or output structure.
void clear_triangulateio ()
Helper function. Clean up the memory associated with the TriangulateIO object. This should really only be used to save memory in extremely tight situations.
void dump_triangulateio (std::ostream &dump_file)
Dump the triangulateio structure to a dump file and record boundary coordinates of boundary nodes.
virtual void dump_info_to_reset_halo_haloed_scheme (std::ostream &dump_file)
Virtual function that is used to dump info. related with distributed triangle meshes.
virtual void update_polyline_representation_from_restart ()
Virtual function used to update the polylines representation after restart.
void remesh_from_triangulateio (std::istream &restart_file)
Regenerate the mesh from a dumped triangulateio file and dumped boundary coordinates of boundary nodes.
Public Member Functions inherited from oomph::UnstructuredTwoDMeshGeometryBase
UnstructuredTwoDMeshGeometryBase ()
Empty constructor.
UnstructuredTwoDMeshGeometryBase (const UnstructuredTwoDMeshGeometryBase &dummy)=delete
Broken copy constructor.
void operator= (const UnstructuredTwoDMeshGeometryBase &)=delete
Broken assignment operator.
~UnstructuredTwoDMeshGeometryBase ()
Empty destructor.
unsigned nregion ()
Return the number of regions specified by attributes.
unsigned nregion_element (const unsigned &i)
Return the number of elements in the i-th region.
FiniteElement * region_element_pt (const unsigned &i, const unsigned &e)
Return the e-th element in the i-th region.
unsigned nregion_attribute ()
Return the number of attributes used in the mesh.
double region_attribute (const unsigned &i)
Return the attribute associated with region i.
GeomObject * boundary_geom_object_pt (const unsigned &b)
Return the geometric object associated with the b-th boundary or null if the boundary has associated geometric object.
std::map< unsigned, GeomObject * > & boundary_geom_object_pt ()
Return direct access to the geometric object storage.
std::map< unsigned, Vector< double > > & boundary_coordinate_limits ()
Return access to the vector of boundary coordinates associated with each geometric object.
Vector< double > & boundary_coordinate_limits (const unsigned &b)
Return access to the coordinate limits associated with the geometric object associated with boundary b.
unsigned nboundary_element_in_region (const unsigned &b, const unsigned &r) const
Return the number of elements adjacent to boundary b in region r.
FiniteElement * boundary_element_in_region_pt (const unsigned &b, const unsigned &r, const unsigned &e) const
Return pointer to the e-th element adjacent to boundary b in region r.
int face_index_at_boundary_in_region (const unsigned &b, const unsigned &r, const unsigned &e) const
Return face index of the e-th element adjacent to boundary b in region r.
TriangleMeshPolyLine * boundary_polyline_pt (const unsigned &b)
Return pointer to the current polyline that describes the b-th mesh boundary.
std::map< unsigned, std::set< Node * > > & nodes_on_boundary_pt ()
Gets a pointer to a set with all the nodes related with a boundary.
const bool get_connected_vertex_number_on_destination_polyline (TriangleMeshPolyLine *dst_polyline_pt, Vector< double > &vertex_coordinates, unsigned &vertex_number)
Gets the vertex number on the destination polyline (used to create the connections among shared boundaries)
void check_contiguousness_on_polylines_helper (Vector< TriangleMeshPolyLine * > &polylines_pt, unsigned &index)
Sort the polylines coming from joining them. Check whether it is necessary to reverse them or not. Used when joining two curve polylines in order to create a polygon.
void check_contiguousness_on_polylines_helper (Vector< TriangleMeshPolyLine * > &polylines_pt, unsigned &index_halo_start, unsigned &index_halo_end)
Sort the polylines coming from joining them. Check whether it is necessary to reverse them or not. Used when joining polylines and they still do not create a polygon.
bool is_point_inside_polygon_helper (Vector< Vector< double > > polygon_vertices, Vector< double > point)
Helper function that checks if a given point is inside a polygon (a set of sorted vertices that connected create a polygon)
void enable_automatic_creation_of_vertices_on_boundaries ()
Enables the creation of points (by Triangle) on the outer and internal boundaries.
void disable_automatic_creation_of_vertices_on_boundaries ()
Disables the creation of points (by Triangle) on the outer and internal boundaries.
bool is_automatic_creation_of_vertices_on_boundaries_allowed ()
Returns the status of the variable Allow_automatic_creation_of_vertices_on_boundaries.
void flush_boundary_segment_node (const unsigned &b)
Flush the boundary segment node storage.
void set_nboundary_segment_node (const unsigned &b, const unsigned &s)
Set the number of segments associated with a boundary.
unsigned nboundary_segment (const unsigned &b)
Return the number of segments associated with a boundary.
unsigned long nboundary_segment_node (const unsigned &b)
Return the number of segments associated with a boundary.
unsigned long nboundary_segment_node (const unsigned &b, const unsigned &s)
Return the number of nodes associated with a given segment of a boundary.
void add_boundary_segment_node (const unsigned &b, const unsigned &s, Node *const &node_pt)
Add the node node_pt to the b-th boundary and the s-th segment of the mesh.
std::map< unsigned, Vector< double > > & boundary_initial_coordinate ()
Return direct access to the initial coordinates of a boundary.
std::map< unsigned, Vector< double > > & boundary_final_coordinate ()
Return direct access to the final coordinates of a boundary.
std::map< unsigned, Vector< double > > & boundary_initial_zeta_coordinate ()
Return direct access to the initial zeta coordinate of a boundary.
std::map< unsigned, Vector< double > > & boundary_final_zeta_coordinate ()
Return direct access to the final zeta coordinates of a boundary.
std::map< unsigned, Vector< unsigned > > & boundary_segment_inverted ()
Return the info. to know if it is necessary to reverse the segment based on a previous mesh.
std::map< unsigned, Vector< Vector< double > > > & boundary_segment_initial_coordinate ()
Return direct access to the initial coordinates for the segments that are part of a boundary.
std::map< unsigned, Vector< Vector< double > > > & boundary_segment_final_coordinate ()
Return direct access to the final coordinates for the segments that are part of a boundary.
std::map< unsigned, Vector< double > > & boundary_segment_initial_arclength ()
Return direct access to the initial arclength for the segments that are part of a boundary.
std::map< unsigned, Vector< double > > & boundary_segment_final_arclength ()
Return direct access to the final arclength for the segments that are part of a boundary.
std::map< unsigned, Vector< double > > & boundary_segment_initial_zeta ()
Return direct access to the initial zeta for the segments that are part of a boundary.
std::map< unsigned, Vector< double > > & boundary_segment_final_zeta ()
Return direct access to the final zeta for the segments that are part of a boundary.
Vector< double > & boundary_segment_initial_zeta (const unsigned &b)
Return the initial zeta for the segments that are part of a boundary.
Vector< double > & boundary_segment_final_zeta (const unsigned &b)
Return the final zeta for the segments that are part of a boundary.
Vector< double > & boundary_initial_coordinate (const unsigned &b)
Return the initial coordinates for the boundary.
Vector< double > & boundary_final_coordinate (const unsigned &b)
Return the final coordinates for the boundary.
const Vector< unsigned > boundary_segment_inverted (const unsigned &b) const
Return the info. to know if it is necessary to reverse the segment based on a previous mesh.
Vector< unsigned > & boundary_segment_inverted (const unsigned &b)
Return the info. to know if it is necessary to reverse the segment based on a previous mesh.
Vector< double > & boundary_initial_zeta_coordinate (const unsigned &b)
Return the initial zeta coordinate for the boundary.
Vector< double > & boundary_final_zeta_coordinate (const unsigned &b)
Return the final zeta coordinate for the boundary.
Vector< double > & boundary_segment_initial_arclength (const unsigned &b)
Return the initial arclength for the segments that are part of a boundary.
Vector< double > & boundary_segment_final_arclength (const unsigned &b)
Return the final arclength for the segments that are part of a boundary.
Vector< Vector< double > > & boundary_segment_initial_coordinate (const unsigned &b)
Return the initial coordinates for the segments that are part of a boundary.
Vector< Vector< double > > & boundary_segment_final_coordinate (const unsigned &b)
Return the final coordinates for the segments that are part of a boundary.
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b)
Setup boundary coordinate on boundary b. Boundary coordinate increases continously along polygonal boundary. It's zero at the lowest left node on the boundary.
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, std::ofstream &outfile)
Setup boundary coordinate on boundary b. Doc Faces in outfile. Boundary coordinate increases continously along polygonal boundary. It's zero at the lowest left node on the boundary.
Public Member Functions inherited from oomph::Mesh
void resize_halo_nodes ()
Helper function that resizes halo nodes to the same size as their non-halo counterparts if required. (A discrepancy can arise if a FaceElement that introduces additional unknowns are attached to a bulk element that shares a node with a haloed element. In that case the joint node between haloed and non-haloed element is resized on that processor but not on the one that holds the halo counterpart (because no FaceElement is attached to the halo element)
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
Constructor builds combined mesh from the meshes specified. Note: This simply merges the meshes' elements and nodes (ignoring duplicates; no boundary information etc. is created).
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
Merge meshes. Note: This simply merges the meshes' elements and nodes (ignoring duplicates; no boundary information etc. is created).
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
Output boundary coordinates on boundary b -- template argument specifies the bulk element type (needed to create FaceElement of appropriate type on mesh boundary).
virtual void scale_mesh (const double &factor)
Scale all nodal coordinates by given factor. Virtual so it can be overloaded in SolidMesh class where it also re-assigns the Lagrangian coordinates.
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
Flush storage for elements and nodes by emptying the vectors that store the pointers to them. This is useful if a particular mesh is only built to generate a small part of a bigger mesh. Once the elements and nodes have been created, they are typically copied into the new mesh and the auxiliary mesh can be deleted. However, if we simply call the destructor of the auxiliary mesh, it will also wipe out the nodes and elements, because it still "thinks" it's in charge of these...
void flush_element_storage ()
Flush storage for elements (only) by emptying the vectors that store the pointers to them. This is useful if a particular mesh is only built to generate a small part of a bigger mesh. Once the elements and nodes have been created, they are typically copied into the new mesh and the auxiliary mesh can be deleted. However, if we simply call the destructor of the auxiliary mesh, it will also wipe out the nodes and elements, because it still "thinks" it's in charge of these...
void flush_node_storage ()
Flush storage for nodes (only) by emptying the vectors that store the pointers to them.
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Upcast (downcast?) to FiniteElement (needed to access FiniteElement member functions).
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
Remove all information about nodes stored on the b-th boundary of the mesh.
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
Replace existing boundary node lookup schemes with new schemes created using the boundary data stored in the nodes.
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
void set_boundary_coordinate_exists (const unsigned &i)
Set boundary coordinate on the i-th boundary to be existing.
void set_boundary_coordinate_does_not_exist (const unsigned &i)
Set boundary coordinate on the i-th boundary to be non-existing.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
Update nodal positions in response to changes in the domain shape. Uses the FiniteElement::get_x(...) function for FiniteElements and doesn't do anything for other element types. If a MacroElement pointer has been set for a FiniteElement, the MacroElement representation is used to update the nodal positions; if not get_x(...) uses the FE interpolation and thus leaves the nodal positions unchanged. Virtual, so it can be overloaded by specific meshes, such as AlgebraicMeshes or SpineMeshes. Generally, this function updates the position of all nodes in response to changes in the boundary position. However, we ignore all SolidNodes since their position is computed as part of the solution -- unless the bool flag is set to true. Such calls are typically made when the initial mesh is created and/or after a mesh has been refined repeatedly before the start of the computation.
virtual void reorder_nodes (const bool &use_old_ordering=true)
Re-order nodes in the order in which they appear in elements -- can be overloaded for more efficient re-ordering.
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
Get a reordering of the nodes in the order in which they appear in elements -- can be overloaded for more efficient re-ordering.
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
Constuct a Mesh of FACE_ELEMENTs along the b-th boundary of the mesh (which contains elements of type BULK_ELEMENT)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
Determine max and min area for all FiniteElements in the mesh (non-FiniteElements are ignored)
double total_size ()
Determine the sum of all "sizes" of the FiniteElements in the mesh (non-FiniteElements are ignored). This gives the length/area/volume occupied by the mesh.
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
Check for inverted elements and report outcome in boolean variable. This visits all elements at their integration points and checks if the Jacobian of the mapping between local and global coordinates is positive -- using the same test that would be carried out (but only in PARANOID mode) during the assembly of the elements' Jacobian matrices. Inverted elements are output in inverted_element_file (if the stream is open).
void check_inverted_elements (bool &mesh_has_inverted_elements)
Check for inverted elements and report outcome in boolean variable. This visits all elements at their integration points and checks if the Jacobian of the mapping between local and global coordinates is positive -- using the same test that would be carried out (but only in PARANOID mode) during the assembly of the elements' Jacobian matrices.
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Check for repeated nodes within a given spatial tolerance. Return (0/1) for (pass/fail).
Vector< Node * > prune_dead_nodes ()
Prune nodes. Nodes that have been marked as obsolete are removed from the mesh (and its boundary-node scheme). Returns vector of pointers to deleted nodes.
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
Find a node not on any boundary in mesh_pt (useful for pinning a single node in a purely Neumann problem so that it is fully determined).
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
For the e-th finite element on boundary b, return int to indicate the face_index of the face adjacent to the boundary. This is consistent with input required during the generation of FaceElements.
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
Output in paraview format into specified file. Breaks up each element into sub-elements for plotting purposes. We assume that all elements are of the same type (fct will break break (in paranoid mode) if paraview output fcts of the elements are inconsistent).
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
Output in paraview format into specified file. Breaks up each element into sub-elements for plotting purposes. We assume that all elements are of the same type (fct will break break (in paranoid mode) if paraview output fcts of the elements are inconsistent).
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
Output in paraview format into specified file. Breaks up each element into sub-elements for plotting purposes. We assume that all elements are of the same type (fct will break break (in paranoid mode) if paraview output fcts of the elements are inconsistent).
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
Output a given time-dep. Vector function at f(n_plot) points in each element.
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
Output the nodes on the boundaries (into separate tecplot zones). Specify filename.
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
Shift time-dependent data along for next timestep: Deal with nodal Data/positions and the element's internal Data.
void calculate_predictions ()
Calculate predictions for all Data and positions associated with the mesh, usually used in adaptive time-stepping.
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with all nodal and elemental data stored in the mesh.
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the internal data stored within elements in the meah.
virtual void compute_norm (double &norm)
Compute norm of solution by summing contributions of compute_norm(...) for all constituent elements in the mesh. What that norm means depends on what's defined in the element's function; may need to take the square root afterwards if the elements compute the square of the L2 norm, say.
virtual void compute_norm (Vector< double > &norm)
Compute norm of solution by summing contributions of compute_norm(...) for all constituent elements in the mesh. What that norm means depends on what's defined in the element's function; may need to take the square root afterwards if the elements compute the square of the L2 norm, say.
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Plot error when compared against a given exact solution. Also returns the norm of the error and that of the exact solution.
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Plot error when compared against a given time-depdendent exact solution. Also returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Plot error when compared against a given time-dependent exact solution. Also returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
Plot error when compared against a given time-dependent exact solution. Also returns the norm of the error and that of the exact solution.
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
Plot error when compared against a given time-depdendent exact solution. Also returns the norm of the error and that of the exact solution. Version with vectors of norms and errors so that different variables' norms and errors can be returned individually.
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
Plot error when compared against a given time-depdendent exact solution. Also returns the norm of the error and that of the exact solution. Version with vectors of norms and errors so that different variables' norms and errors can be returned individually.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
Returns the norm of the error and that of the exact solution. Version with vectors of norms and errors so that different variables' norms and errors can be returned individually.
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
Read-only access fct to communicator (Null if mesh is not distributed, i.e. if we don't have mpi).
void set_communicator_pt (OomphCommunicator *comm_pt)
Function to set communicator (mesh is assumed to be distributed if the communicator pointer is non-null). Only defined if mpi is enabled becaus Comm_pt itself is only defined when mpi is enabled.
void set_keep_all_elements_as_halos ()
Call this function to keep all the elements as halo elements.
void unset_keep_all_elements_as_halos ()
Calll this function to unset the flag that keeps all elements in the mesh as halo elements.
virtual void distribute (OomphCommunicator *comm_pt, const Vector< unsigned > &element_domain, Vector< GeneralisedElement * > &deleted_element_pt, DocInfo &doc_info, const bool &report_stats, const bool &overrule_keep_as_halo_element_status)
Distribute the problem and doc; make this virtual to allow overloading for particular meshes where further work is required. Add to vector of pointers to deleted elements.
void distribute (OomphCommunicator *comm_pt, const Vector< unsigned > &element_domain, Vector< GeneralisedElement * > &deleted_element_pt, const bool &report_stats=false)
Distribute the problem Add to vector of pointers to deleted elements.
void prune_halo_elements_and_nodes (Vector< GeneralisedElement * > &deleted_element_pt, const bool &report_stats=false)
(Irreversibly) prune halo(ed) elements and nodes, usually after another round of refinement, to get rid of excessively wide halo layers. Note that the current mesh will be now regarded as the base mesh and no unrefinement relative to it will be possible once this function has been called.
void prune_halo_elements_and_nodes (Vector< GeneralisedElement * > &deleted_element_pt, DocInfo &doc_info, const bool &report_stats)
(Irreversibly) prune halo(ed) elements and nodes, usually after another round of refinement, to get rid of excessively wide halo layers. Note that the current mesh will be now regarded as the base mesh and no unrefinement relative to it will be possible once this function has been called.
void get_efficiency_of_mesh_distribution (double &av_efficiency, double &max_efficiency, double &min_efficiency)
Get efficiency of mesh distribution: In an ideal distribution without halo overhead, each processor would only hold its own elements. Efficieny per processor = (number of non-halo elements)/ (total number of elements).
void doc_mesh_distribution (DocInfo &doc_info)
Doc the mesh distribution, to be processed with tecplot macros.
void check_halo_schemes (DocInfo &doc_info, double &max_permitted_error_for_halo_check)
Check halo and shared schemes on the mesh.
virtual void classify_halo_and_haloed_nodes (DocInfo &doc_info, const bool &report_stats)
Classify the halo and haloed nodes in the mesh. Virtual so it can be overloaded to perform additional functionality (such as synchronising hanging nodes) in refineable meshes, say.
virtual void classify_halo_and_haloed_nodes (const bool &report_stats=false)
Classify the halo and haloed nodes in the mesh. Virtual so it can be overloaded to perform additional functionality (such as synchronising hanging nodes) in refineable meshes, say.
void synchronise_shared_nodes (const bool &report_stats)
Synchronise shared node lookup schemes to cater for the the case where: (1) a certain node on the current processor is halo with proc p (i.e. its non-halo counterpart lives on processor p) (2) that node is also exists (also as a halo) on another processor (q, say) where its non-halo counter part is also known to be on processor p. However, without calling this function the current processor does not necessarily know that it shares a node with processor q. This information can be required, e.g. when synchronising hanging node schemes over all processors.
void get_all_halo_data (std::map< unsigned, double * > &map_of_halo_data)
Get all the halo data stored in the mesh and add pointers to the data to the map, indexed by global equation number.
Vector< GeneralisedElement * > halo_element_pt (const unsigned &p)
Return vector of halo elements in this Mesh whose non-halo counterpart is held on processor p.
Vector< GeneralisedElement * > haloed_element_pt (const unsigned &p)
Return vector of haloed elements in this Mesh whose haloing counterpart is held on processor p.
unsigned nnon_halo_element ()
Total number of non-halo elements in this mesh (Costly call computes result on the fly)
unsigned nroot_halo_element ()
Total number of root halo elements in this Mesh.
unsigned nroot_halo_element (const unsigned &p)
Number of root halo elements in this Mesh whose non-halo counterpart is held on processor p.
Vector< GeneralisedElement * > root_halo_element_pt (const unsigned &p)
Vector of pointers to root halo elements in this Mesh whose non-halo counterpart is held on processor p.
GeneralisedElement *& root_halo_element_pt (const unsigned &p, const unsigned &e)
Access fct to the e-th root halo element in this Mesh whose non-halo counterpart is held on processor p.
void add_root_halo_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
Add root halo element whose non-halo counterpart is held on processor p to this Mesh.
unsigned nhalo_node ()
Total number of halo nodes in this Mesh.
unsigned nhalo_node (const unsigned &p)
Number of halo nodes in this Mesh whose non-halo counterpart is held on processor p.
void add_halo_node_pt (const unsigned &p, Node *&nod_pt)
Add halo node whose non-halo counterpart is held on processor p to the storage scheme for halo nodes.
Node * halo_node_pt (const unsigned &p, const unsigned &j)
Access fct to the j-th halo node in this Mesh whose non-halo counterpart is held on processor p.
unsigned nroot_haloed_element ()
Total number of root haloed elements in this Mesh.
unsigned nroot_haloed_element (const unsigned &p)
Number of root haloed elements in this Mesh whose non-halo counterpart is held on processor p.
Vector< GeneralisedElement * > root_haloed_element_pt (const unsigned &p)
Vector of pointers to root haloed elements in this Mesh whose non-halo counterpart is held on processor p.
GeneralisedElement *& root_haloed_element_pt (const unsigned &p, const unsigned &e)
Access fct to the e-th root haloed element in this Mesh whose non-halo counterpart is held on processor p.
void add_root_haloed_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
Add root haloed element whose non-halo counterpart is held on processor p to the storage scheme for haloed elements. Note: This does not add the element to the storage scheme for elements as it's understood to naturally live on this processor anyway!
unsigned nhaloed_node ()
Total number of haloed nodes in this Mesh.
unsigned nhaloed_node (const unsigned &p)
Number of haloed nodes in this Mesh whose haloed counterpart is held on processor p.
Node * haloed_node_pt (const unsigned &p, const unsigned &j)
Access fct to the j-th haloed node in this Mesh whose halo counterpart is held on processor p.
void add_haloed_node_pt (const unsigned &p, Node *&nod_pt)
Add haloed node whose halo counterpart is held on processor p to the storage scheme for haloed nodes.
void disable_resizing_of_halo_nodes ()
Function to suppress resizing of halo nodes -- optmisation but call it at your own risk!
void enable_resizing_of_halo_nodes ()
Function to (re-)enable resizing of halo nodes -- this returns things to the default behaviour.
void disable_output_of_halo_elements ()
Function to disable halo element output.
void enable_output_of_halo_elements ()
Function to enable halo element output.
unsigned nshared_node ()
Total number of shared nodes in this Mesh.
void doc_shared_nodes ()
Doc shared nodes.
unsigned nshared_node (const unsigned &p)
Number of shared nodes in this Mesh who have a counterpart on processor p.
Node * shared_node_pt (const unsigned &p, const unsigned &j)
Access fct to the j-th shared node in this Mesh who has a counterpart on processor p.
void get_shared_node_pt (const unsigned &p, Vector< Node * > &shared_node_pt)
Get vector of pointers to shared nodes with processor p. Required for faster search in Missing_masters_functions::add_external_haloed_node_helper() and Missing_masters_functions::add_external_haloed_master_node_helper()
void add_shared_node_pt (const unsigned &p, Node *&nod_pt)
Add shared node whose counterpart is held on processor p to the storage scheme for shared nodes. (NB: ensure that this routine is called twice, once for each process)
void get_halo_node_stats (double &av_number, unsigned &max_number, unsigned &min_number)
Get halo node stats for this distributed mesh: Average/max/min number of halo nodes over all processors. Careful: Involves MPI Broadcasts and must therefore be called on all processors!
void get_haloed_node_stats (double &av_number, unsigned &max_number, unsigned &min_number)
Get haloed node stats for this distributed mesh: Average/max/min number of haloed nodes over all processors. Careful: Involves MPI Broadcasts and must therefore be called on all processors!
void output_external_halo_elements (std::ostream &outfile, const unsigned &n_plot=5)
Output all external halo elements.
void output_external_halo_elements (const unsigned &p, std::ostream &outfile, const unsigned &n_plot=5)
Output all external halo elements with processor p.
void output_external_haloed_elements (std::ostream &outfile, const unsigned &n_plot=5)
Output all external haloed elements.
void output_external_haloed_elements (const unsigned &p, std::ostream &outfile, const unsigned &n_plot=5)
Output all external haloed elements with processor p.
unsigned nexternal_halo_element ()
Total number of external halo elements in this Mesh.
unsigned nexternal_halo_element (const unsigned &p)
Number of external halo elements in this Mesh whose non-halo counterpart is held on processor p.
GeneralisedElement *& external_halo_element_pt (const unsigned &p, const unsigned &e)
Access fct to the e-th external halo element in this Mesh whose non-halo counterpart is held on processor p.
void add_external_halo_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
Add external halo element whose non-halo counterpart is held on processor p to this Mesh.
unsigned nexternal_haloed_element ()
Total number of external haloed elements in this Mesh.
unsigned nexternal_haloed_element (const unsigned &p)
Number of external haloed elements in this Mesh whose non-halo counterpart is held on processor p.
GeneralisedElement *& external_haloed_element_pt (const unsigned &p, const unsigned &e)
Access fct to the e-th external haloed element in this Mesh whose non-halo counterpart is held on processor p.
unsigned add_external_haloed_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
Add external haloed element whose non-halo counterpart is held on processor p to the storage scheme for haloed elements.
unsigned nexternal_halo_node ()
Total number of external halo nodes in this Mesh.
void get_external_halo_node_pt (Vector< Node * > &external_halo_node_pt)
Get vector of pointers to all external halo nodes.
unsigned nexternal_halo_node (const unsigned &p)
Number of external halo nodes in this Mesh whose non-halo (external) counterpart is held on processor p.
void add_external_halo_node_pt (const unsigned &p, Node *&nod_pt)
Add external halo node whose non-halo (external) counterpart is held on processor p to the storage scheme for halo nodes.
Node *& external_halo_node_pt (const unsigned &p, const unsigned &j)
Access fct to the j-th external halo node in this Mesh whose non-halo external counterpart is held on processor p.
Vector< Node * > external_halo_node_pt (const unsigned &p)
Access fct to vector of external halo node in this Mesh whose non-halo external counterpart is held on processor p. (read only)
void set_external_halo_node_pt (const unsigned &p, const Vector< Node * > &external_halo_node_pt)
Set vector of external halo node in this Mesh whose non-halo external counterpart is held on processor p.
void null_external_halo_node (const unsigned &p, Node *nod_pt)
Null out specified external halo node (used when deleting duplicates)
void remove_null_pointers_from_external_halo_node_storage ()
Consolidate external halo node storage by removing nulled out pointes in external halo and haloed schemes.
unsigned nexternal_haloed_node ()
Total number of external haloed nodes in this Mesh.
unsigned nexternal_haloed_node (const unsigned &p)
Number of external haloed nodes in this Mesh whose halo (external) counterpart is held on processor p.
Node *& external_haloed_node_pt (const unsigned &p, const unsigned &j)
Access fct to the j-th external haloed node in this Mesh whose halo external counterpart is held on processor p.
unsigned add_external_haloed_node_pt (const unsigned &p, Node *&nod_pt)
Add external haloed node whose halo (external) counterpart is held on processor p to the storage scheme for haloed nodes.
Vector< Node * > external_haloed_node_pt (const unsigned &p)
Access fct to vector of external haloed node in this Mesh whose halo external counterpart is held on processor p. (read only)
void set_external_haloed_node_pt (const unsigned &p, const Vector< Node * > &external_haloed_node_pt)
Set vector of external haloed node in this Mesh whose halo external counterpart is held on processor p.
std::set< int > external_halo_proc ()
Return the set of processors that hold external halo nodes. This is required to avoid having to pass a communicator into the node_update functions for Algebraic-based and MacroElement-based Meshes.
virtual unsigned try_to_add_root_haloed_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
virtual unsigned try_to_add_haloed_node_pt (const unsigned &p, Node *&nod_pt)
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Public Attributes
TimeStepper * Time_stepper_pt
Timestepper used to build elements.
bool Use_attributes
Boolean flag to indicate whether to use attributes or not (required for multidomain meshes)
Public Attributes inherited from oomph::UnstructuredTwoDMeshGeometryBase
std::map< unsigned, bool > Assigned_segments_initial_zeta_values
Flag used at the setup_boundary_coordinate function to know if initial zeta values for segments have been assigned.
Public Attributes inherited from oomph::Mesh
bool Output_halo_elements
Bool for output of halo elements.
Protected Member Functions
void build_from_scaffold (TimeStepper *time_stepper_pt, const bool &use_attributes)
Build mesh from scaffold.
void build_triangulateio (const std::string &poly_file_name, TriangulateIO &triangulate_io, bool &use_attributes)
Helper function to create TriangulateIO object (return in triangulate_io) from the .poly file.
void generic_constructor (Vector< TriangleMeshPolygon * > &outer_boundary_pt, Vector< TriangleMeshPolygon * > &internal_polygon_pt, Vector< TriangleMeshOpenCurve * > &open_polylines_pt, const double &element_area, Vector< Vector< double > > &extra_holes_coordinates, std::map< unsigned, Vector< double > > &regions_coordinates, std::map< unsigned, double > &regions_areas, TimeStepper *time_stepper_pt, const bool &use_attributes, const bool &refine_boundary, const bool &refine_internal_boundary)
A general-purpose construction function that builds the mesh once the different specific constructors have assembled the appropriate information.
void shared_boundaries_in_this_processor (Vector< unsigned > &shared_boundaries_in_this_processor)
Get the shared boundaries ids living in the current processor.
const unsigned nshared_boundaries (const unsigned &p, const unsigned &q) const
Access functions to boundaries shared with processors.
Vector< Vector< Vector< unsigned > > > shared_boundaries_ids () const
Vector< Vector< Vector< unsigned > > > & shared_boundaries_ids ()
Vector< Vector< unsigned > > shared_boundaries_ids (const unsigned &p) const
Vector< Vector< unsigned > > & shared_boundaries_ids (const unsigned &p)
Vector< unsigned > shared_boundaries_ids (const unsigned &p, const unsigned &q) const
Vector< unsigned > & shared_boundaries_ids (const unsigned &p, const unsigned &q)
const unsigned shared_boundaries_ids (const unsigned &p, const unsigned &q, const unsigned &i) const
const unsigned nshared_boundary_curves (const unsigned &p) const
const unsigned nshared_boundary_polyline (const unsigned &p, const unsigned &c) const
Vector< TriangleMeshPolyLine * > & shared_boundary_polyline_pt (const unsigned &p, const unsigned &c)
TriangleMeshPolyLine * shared_boundary_polyline_pt (const unsigned &p, const unsigned &c, const unsigned &i) const
const unsigned nshared_boundaries () const
const unsigned nshared_boundary_element (const unsigned &b)
void flush_shared_boundary_element ()
void flush_shared_boundary_element (const unsigned &b)
void add_shared_boundary_element (const unsigned &b, FiniteElement *ele_pt)
FiniteElement * shared_boundary_element_pt (const unsigned &b, const unsigned &e)
void flush_face_index_at_shared_boundary ()
void add_face_index_at_shared_boundary (const unsigned &b, const unsigned &i)
int face_index_at_shared_boundary (const unsigned &b, const unsigned &e)
const unsigned nshared_boundary_node (const unsigned &b)
void flush_shared_boundary_node ()
Flush ALL the shared boundary nodes.
void flush_shared_boundary_node (const unsigned &b)
Flush the boundary nodes associated to the shared boundary b.
void add_shared_boundary_node (const unsigned &b, Node *node_pt)
Add the node the shared boundary.
Node * shared_boundary_node_pt (const unsigned &b, const unsigned &n)
bool is_node_on_shared_boundary (const unsigned &b, Node *const &node_pt)
Is the node on the shared boundary.
std::map< unsigned, Vector< unsigned > > & shared_boundary_from_processors ()
Return the association of the shared boundaries with the processors.
Vector< unsigned > & shared_boundary_from_processors (const unsigned &b)
const unsigned nshared_boundary_overlaps_internal_boundary ()
Get the number of shared boundaries overlaping internal boundaries.
const bool shared_boundary_overlaps_internal_boundary (const unsigned &shd_bnd_id)
Checks if the shared boundary overlaps an internal boundary.
const unsigned shared_boundary_overlapping_internal_boundary (const unsigned &shd_bnd_id)
Gets the boundary id of the internal boundary that the shared boundary lies on.
void get_shared_boundaries_overlapping_internal_boundary (const unsigned &internal_bnd_id, Vector< unsigned > &shd_bnd_ids)
Gets the shared boundaries ids that overlap the given internal boundary.
std::map< unsigned, unsigned > & shared_boundary_overlaps_internal_boundary ()
Gets the storage that indicates if a shared boundary is part of an internal boundary.
const bool boundary_was_splitted (const unsigned &b)
Helper function to verify if a given boundary was splitted in the distribution process.
const unsigned nboundary_subpolylines (const unsigned &b)
Gets the number of subpolylines that create the boundarya (useful only when the boundary is marked as split)
Vector< TriangleMeshPolyLine * > & boundary_subpolylines (const unsigned &b)
Gets the vector of auxiliar polylines that will represent the given boundary (useful only when the boundaries were split)
const bool boundary_marked_as_shared_boundary (const unsigned &b, const unsigned &isub)
Returns the value that indicates if a subpolyline of a given boundary continues been used as internal boundary or should be changed as shared boundary.
void flush_shared_boundary_polyline_pt ()
void create_distributed_domain_representation (Vector< TriangleMeshPolygon * > &polygons_pt, Vector< TriangleMeshOpenCurve * > &open_curves_pt)
Creates the distributed domain representation. Joins the original boundaires, shared boundaries and creates connections among them to create the new polygons that represent the distributed domain.
void sort_polylines_helper (Vector< TriangleMeshPolyLine * > &unsorted_polylines_pt, Vector< Vector< TriangleMeshPolyLine * > > &sorted_polylines_pt)
Sorts the polylines so they be continuous and then we can create a closed or open curve from them.
void create_tmp_polygons_helper (Vector< Vector< TriangleMeshPolyLine * > > &polylines_pt, Vector< TriangleMeshPolygon * > &polygons_pt)
Take the polylines from the shared boundaries and create temporary polygon representations of the domain.
void create_tmp_open_curves_helper (Vector< Vector< TriangleMeshPolyLine * > > &sorted_open_curves_pt, Vector< TriangleMeshPolyLine * > &unsorted_shared_to_internal_poly_pt, Vector< TriangleMeshOpenCurve * > &open_curves_pt)
Take the polylines from the original open curves and created new temporaly representations of open curves with the bits of original curves not overlapped by shared boundaries.
void compute_holes_left_by_halo_elements_helper (Vector< Vector< double > > &output_holes_coordinates)
Compute the holes left by the halo elements, those adjacent to the shared boundaries.
void update_holes_information_helper (Vector< TriangleMeshPolygon * > &polygons_pt, Vector< Vector< double > > &output_holes_coordinates)
Keeps those vertices that define a hole, those that are inside closed internal boundaries in the new polygons that define the domain. Delete those outside/inside the outer polygons (this is required since Triangle can not deal with vertices that define holes outside the new outer polygons of the domain)
const int check_connections_of_polyline_nodes (std::set< FiniteElement * > &element_in_processor_pt, const int &root_edge_bnd_id, std::map< std::pair< Node *, Node * >, bool > &overlapped_face, std::map< unsigned, std::map< Node *, bool > > &node_on_bnd_not_overlapped_by_shd_bnd, std::list< Node * > &current_polyline_nodes, std::map< unsigned, std::list< Node * > > &shared_bnd_id_to_sorted_list_node_pt, const unsigned &node_degree, Node *&new_node_pt, const bool called_from_load_balance=false)
Check for any possible connections that the array of sorted nodes have with any previous boundaries or with itself. Return -1 if no connection was found, return -2 if the connection is with the same polyline, return the boundary id of the boundary to which the connection is performed.
void create_shared_polylines_connections ()
Establish the connections of the polylines previously marked as having connections. This connections were marked in the function TriangleMesh::create_polylines_from_halo_elements_helper().
void create_shared_boundaries (OomphCommunicator *comm_pt, const Vector< unsigned > &element_domain, const Vector< GeneralisedElement * > &backed_up_el_pt, const Vector< FiniteElement * > &backed_up_f_el_pt, std::map< Data *, std::set< unsigned > > &processors_associated_with_data, const bool &overrule_keep_as_halo_element_status)
Creates the shared boundaries.
void get_halo_elements_on_all_procs (const unsigned &nproc, const Vector< unsigned > &element_domain, const Vector< GeneralisedElement * > &backed_up_el_pt, std::map< Data *, std::set< unsigned > > &processors_associated_with_data, const bool &overrule_keep_as_halo_element_status, std::map< GeneralisedElement *, unsigned > &element_to_global_index, Vector< Vector< Vector< GeneralisedElement * > > > &output_halo_elements_pt)
Creates the halo elements on all processors Gets the halo elements on all processors, these elements are then used on the function that computes the shared boundaries among the processors.
void get_element_edges_on_boundary (std::map< std::pair< Node *, Node * >, unsigned > &element_edges_on_boundary)
Get the element edges (pair of nodes, edges) that lie on a boundary (used to mark shared boundaries that lie on internal boundaries)
void create_polylines_from_halo_elements_helper (const Vector< unsigned > &element_domain, std::map< GeneralisedElement *, unsigned > &element_to_global_index, std::set< FiniteElement * > &element_in_processor_pt, Vector< Vector< Vector< GeneralisedElement * > > > &input_halo_elements, std::map< std::pair< Node *, Node * >, unsigned > &elements_edges_on_boundary, Vector< Vector< Vector< TriangleMeshPolyLine * > > > &output_polylines_pt)
Creates polylines from the intersection of halo elements on all processors. The new polylines define the shared boundaries in the domain This get the polylines on ALL processors, that is why the three dimensions output_polylines_pt[iproc][ncurve][npolyline].
void break_loops_on_shared_polyline_helper (const unsigned &initial_shd_bnd_id, std::list< Node * > &input_nodes, Vector< FiniteElement * > &input_boundary_element_pt, Vector< int > &input_face_index_element, const int &input_connect_to_the_left, const int &input_connect_to_the_right, Vector< std::list< Node * > > &output_sorted_nodes_pt, Vector< Vector< FiniteElement * > > &output_boundary_element_pt, Vector< Vector< int > > &output_face_index_element, Vector< int > &output_connect_to_the_left, Vector< int > &output_connect_to_the_right)
Break any possible loop created by the sorted list of nodes that is used to create a new shared polyline.
void break_loops_on_shared_polyline_load_balance_helper (const unsigned &initial_shd_bnd_id, std::list< Node * > &input_nodes, Vector< FiniteElement * > &input_boundary_element_pt, Vector< FiniteElement * > &input_boundary_face_element_pt, Vector< int > &input_face_index_element, const int &input_connect_to_the_left, const int &input_connect_to_the_right, Vector< std::list< Node * > > &output_sorted_nodes_pt, Vector< Vector< FiniteElement * > > &output_boundary_element_pt, Vector< Vector< FiniteElement * > > &output_boundary_face_element_pt, Vector< Vector< int > > &output_face_index_element, Vector< int > &output_connect_to_the_left, Vector< int > &output_connect_to_the_right)
Break any possible loop created by the sorted list of nodes that is used to create a new shared polyline (modified version for load balance)
void create_shared_polyline (const unsigned &my_rank, const unsigned &shd_bnd_id, const unsigned &iproc, const unsigned &jproc, std::list< Node * > &sorted_nodes, const int &root_edge_bnd_id, Vector< FiniteElement * > &bulk_bnd_ele_pt, Vector< int > &face_index_ele, Vector< Vector< TriangleMeshPolyLine * > > &unsorted_polylines_pt, const int &connect_to_the_left_flag, const int &connect_to_the_right_flag)
Create the shared polyline and fill the data structured that keep all the information associated with the creationg of the shared boundary.
Protected Member Functions inherited from oomph::UnstructuredTwoDMeshGeometryBase
void build_triangulateio (Vector< TriangleMeshPolygon * > &outer_polygons_pt, Vector< TriangleMeshPolygon * > &internal_polygons_pt, Vector< TriangleMeshOpenCurve * > &open_curves_pt, Vector< Vector< double > > &extra_holes_coordinates, std::map< unsigned, Vector< double > > &regions_coordinates, std::map< unsigned, double > &regions_areas, TriangulateIO &triangulate_io)
Create TriangulateIO object from outer boundaries, internal boundaries, and open curves. Add the holes and regions information as well.
void add_connection_matrix_info_helper (TriangleMeshPolyLine *polyline_pt, std::map< unsigned, std::map< unsigned, Vector< vertex_connection_info > > > &connection_matrix, TriangleMeshPolyLine *next_polyline_pt=0)
Helps to add information to the connection matrix of the given polyline.
void initialise_base_vertex (TriangleMeshPolyLine *polyline_pt, std::map< unsigned, std::map< unsigned, Vector< base_vertex_info > > > &base_vertices)
Initialise the base vertex structure, set every vertex to no visited and not being a base vertex.
void add_base_vertex_info_helper (TriangleMeshPolyLine *polyline_pt, std::map< unsigned, std::map< unsigned, Vector< base_vertex_info > > > &base_vertices, std::map< unsigned, std::map< unsigned, Vector< vertex_connection_info > > > &connection_matrix, std::map< unsigned, std::map< unsigned, unsigned > > &boundary_chunk_nvertices)
Helps to identify the base vertex of the given polyline.
void snap_nodes_onto_geometric_objects ()
Snap the boundary nodes onto any curvilinear boundaries defined by geometric objects.
void copy_connection_information (TriangleMeshCurveSection *input_curve_pt, TriangleMeshCurveSection *output_curve_pt)
Helper function to copy the connection information from the input curve(polyline or curviline) to the output polyline.
void copy_connection_information_to_sub_polylines (TriangleMeshCurveSection *input_curve_pt, TriangleMeshCurveSection *output_curve_pt)
Helper function to copy the connection information from the input curve(polyline or curviline) to the output sub-polyline.
void create_vertex_coordinates_for_polyline_no_connections (TriangleMeshCurviLine *boundary_pt, Vector< Vector< double > > &vertex_coord, Vector< std::pair< double, double > > &polygonal_vertex_arclength_info)
Helper function to create polyline vertex coordinates for curvilinear boundary specified by boundary_pt, using either equal increments in zeta or in (approximate) arclength along the curviline. vertex_coord[i_vertex][i_dim] stores i_dim-th coordinate of i_vertex-th vertex. polygonal_vertex_arclength_info[i_vertex] contains the pair of doubles made of the arclength of the i_vertex-th vertex along the polygonal representation (.first), and the corresponding coordinate on the GeomObject (.second)
void create_vertex_coordinates_for_polyline_connections (TriangleMeshCurviLine *boundary_pt, Vector< Vector< double > > &vertex_coord, Vector< std::pair< double, double > > &polygonal_vertex_arclength_info)
Helper function to create polyline vertex coordinates for curvilinear boundary specified by boundary_pt, using either equal increments in zeta or in (approximate) arclength along the curviline. vertex_coord[i_vertex][i_dim] stores i_dim-th coordinate of i_vertex-th vertex. polygonal_vertex_arclength_info[i_vertex] contains the pair of doubles made of the arclength of the i_vertex-th vertex along the polygonal representation (.first), and the corresponding coordinate on the GeomObject (.second)
TriangleMeshPolygon * closed_curve_to_polygon_helper (TriangleMeshClosedCurve *closed_curve_pt, unsigned &max_bnd_id_local)
Helper function that returns a polygon representation for the given closed curve, it also computes the maximum boundary id of the constituent curves. If the TriangleMeshClosedCurve is already a TriangleMeshPolygon we simply return a pointer to it. Otherwise a new TrilangleMeshPolygon is created -- this is deleted automatically when the TriangleMesh destructor is called, so no external book-keeping is required.
TriangleMeshOpenCurve * create_open_curve_with_polyline_helper (TriangleMeshOpenCurve *open_curve_pt, unsigned &max_bnd_id_local)
Helper function that creates and returns an open curve with the polyline representation of its constituent curve sections. The new created open curve is deleted when the TriangleMesh destructor is called.
void set_geom_objects_and_coordinate_limits_for_close_curve (TriangleMeshClosedCurve *input_closed_curve_pt)
Stores the geometric objects associated to the curve sections that compound the closed curve. It also stores the limits defined by these geometric objects.
void set_geom_objects_and_coordinate_limits_for_open_curve (TriangleMeshOpenCurve *input_open_curve_pt)
Stores the geometric objects associated to the curve sections that compound the open curve. It also stores the limits defined by these geometric objects.
Protected Member Functions inherited from oomph::Mesh
void setup_shared_node_scheme ()
Setup shared node scheme.
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign the global equation numbers in the Data stored at the nodes and also internal element Data. Also, build (via push_back) the Vector of pointers to the dofs (variables).
void describe_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the dofs of the Mesh. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the local dofs of the elements. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers in all elements If the boolean argument is true then also store pointers to dofs.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
A function that upgrades an ordinary node to a boundary node We shouldn't ever really use this, but it does make life that bit easier for the lazy mesh writer. The pointer to the node is replaced by a pointer to the new boundary node in all element look-up schemes and in the mesh's Node_pt vector. The new node is also addressed by node_pt on return from the function.
void convert_to_boundary_node (Node *&node_pt)
A function that upgrades an ordinary node to a boundary node. All pointers to the node from the mesh's elements are found. and replaced by pointers to the new boundary node. If the node is present in the mesh's list of nodes, that pointer is also replaced. Finally, the pointer argument node_pt addresses the new node on return from the function. We shouldn't ever really use this, but it does make life that bit easier for the lazy mesh writer.
Protected Attributes
std::map< unsigned, double > Regions_areas
Target areas for regions; defaults to 0.0 which (luckily) implies "no specific target area" for triangle!
bool Triangulateio_exists
Boolean defining if Triangulateio object has been built or not.
TriangleScaffoldMesh * Tmp_mesh_pt
Temporary scaffold mesh.
Vector< unsigned > Oomph_vertex_nodes_id
Vector storing oomph-lib node number for all vertex nodes in the TriangulateIO representation of the mesh.
unsigned Initial_shared_boundary_id
The initial boundary id for shared boundaries.
unsigned Final_shared_boundary_id
The final boundary id for shared boundaries.
Vector< Vector< Vector< unsigned > > > Shared_boundaries_ids
Stores the boundaries ids created by the interaction of two processors Shared_boundaries_ids[iproc][jproc] = Vector of shared boundaries ids "iproc" processor shares boundaries with "jproc" processor.
std::map< unsigned, Vector< unsigned > > Shared_boundary_from_processors
Stores the processors involved in the generation of a shared boundary, in 2D two processors give rise to the creation of a shared boundary.
std::map< unsigned, unsigned > Shared_boundary_overlaps_internal_boundary
Stores information about those shared boundaries that lie over or over a segment of an internal boundary (only used when using internal boundaries in the domain)
Vector< Vector< Vector< TriangleMeshPolyLine * > > > Shared_boundary_polyline_pt
Stores the polyline representation of the shared boundaries Shared_boundary_polyline_pt[iproc][ncurve][npolyline] = polyline_pt.
std::map< unsigned, Vector< FiniteElement * > > Shared_boundary_element_pt
Stores the boundary elements adjacent to the shared boundaries, these elements are a subset of the halo and haloed elements.
std::map< unsigned, Vector< int > > Face_index_at_shared_boundary
For the e-th finite element on shared boundary b, this is the index of the face that lies along that boundary.
std::map< unsigned, Vector< Node * > > Shared_boundary_node_pt
Stores the boundary nodes adjacent to the shared boundaries, these nodes are a subset of the halo and haloed nodes.
std::map< unsigned, bool > Boundary_was_splitted
Flag to indicate if a polyline has been splitted during the distribution process, the boundary id of the polyline is used to indicate if spplited.
std::map< unsigned, Vector< TriangleMeshPolyLine * > > Boundary_subpolylines
The polylines that will temporary represent the boundary that was splitted in the distribution process. Used to ease the sending of info. to Triangle during the adaptation process.
std::map< unsigned, std::vector< bool > > Boundary_marked_as_shared_boundary
Flag to indicate if an internal boundary will be used as shared boundary because there is overlapping of the internal boundary with the shared boundary.
bool First_time_compute_holes_left_by_halo_elements
Flag to know if it is the first time we are going to compute the holes left by the halo elements.
Vector< Vector< double > > Original_extra_holes_coordinates
Backup the original extra holes coordinates.
Protected Attributes inherited from oomph::TriangleMeshBase
TriangulateIO Triangulateio
TriangulateIO representation of the mesh.
bool Use_triangulateio_restart
Should we use triangulateio specific parts for dump/restart? (Doesn't work with some elements and isn't needed if not using adaptivity).
Protected Attributes inherited from oomph::UnstructuredTwoDMeshGeometryBase
std::map< unsigned, Vector< Vector< Node * > > > Boundary_segment_node_pt
Used to store the nodes associated to a boundary and to an specific segment (this only applies in distributed meshes where the boundary is splitted in segments)
std::map< unsigned, Vector< double > > Boundary_segment_initial_zeta
Stores the initial zeta coordinate for the segments that appear when a boundary is splited among processors.
std::map< unsigned, Vector< double > > Boundary_segment_final_zeta
Stores the final zeta coordinate for the segments that appear when a boundary is splited among processors.
std::map< unsigned, Vector< double > > Boundary_initial_coordinate
Stores the initial coordinates for the boundary.
std::map< unsigned, Vector< double > > Boundary_final_coordinate
Stores the final coordinates for the boundary.
std::map< unsigned, Vector< unsigned > > Boundary_segment_inverted
Stores the info. to know if it is necessary to reverse the segment based on a previous mesh.
std::map< unsigned, Vector< double > > Boundary_initial_zeta_coordinate
Stores the initial zeta coordinate for the boundary.
std::map< unsigned, Vector< double > > Boundary_final_zeta_coordinate
Stores the final zeta coordinate for the boundary.
std::map< unsigned, Vector< double > > Boundary_segment_initial_arclength
Stores the initial arclength for the segments that appear when a boundary is splited among processors.
std::map< unsigned, Vector< double > > Boundary_segment_final_arclength
Stores the final arclength for the segments that appear when a boundary is splited among processors.
std::map< unsigned, Vector< Vector< double > > > Boundary_segment_initial_coordinate
Stores the initial coordinates for the segments that appear when a boundary is splited among processors.
std::map< unsigned, Vector< Vector< double > > > Boundary_segment_final_coordinate
Stores the final coordinates for the segments that appear when a boundary is splited among processors.
bool Allow_automatic_creation_of_vertices_on_boundaries
Flag to indicate whether the automatic creation of vertices along the boundaries by Triangle is allowed.
std::map< unsigned, Vector< FiniteElement * > > Region_element_pt
Vector of elements in each region differentiated by attribute (the key of the map is the attribute)
Vector< double > Region_attribute
Vector of attributes associated with the elements in each region.
std::map< unsigned, GeomObject * > Boundary_geom_object_pt
Storage for the geometric objects associated with any boundaries.
std::map< unsigned, Vector< double > > Boundary_coordinate_limits
Storage for the limits of the boundary coordinates defined by the use of geometric objects. Only used for curvilinear boundaries.
Vector< TriangleMeshPolygon * > Outer_boundary_pt
Polygon that defines outer boundaries.
Vector< TriangleMeshPolygon * > Internal_polygon_pt
Vector of polygons that define internal polygons.
Vector< TriangleMeshOpenCurve * > Internal_open_curve_pt
Vector of open polylines that define internal curves.
Vector< Vector< double > > Extra_holes_coordinates
Storage for extra coordinates for holes.
std::map< unsigned, Vector< double > > Regions_coordinates
Storage for extra coordinates for regions. The key on the map is the region id.
std::map< unsigned, TriangleMeshCurveSection * > Boundary_curve_section_pt
A map that stores the associated curve section of the specified boundary id.
Vector< std::map< unsigned, Vector< FiniteElement * > > > Boundary_region_element_pt
Storage for elements adjacent to a boundary in a particular region.
Vector< std::map< unsigned, Vector< int > > > Face_index_region_at_boundary
Storage for the face index adjacent to a boundary in a particular region.
std::map< unsigned, Vector< std::pair< double, double > > > Polygonal_vertex_arclength_info
Storage for pairs of doubles representing: .first: the arclength along the polygonal representation of the curviline .second: the corresponding intrinsic coordinate on the associated geometric object at which the vertices on the specified boundary are located. Only used for boundaries represented by geom objects.
std::map< unsigned, std::set< Node * > > Nodes_on_boundary_pt
Stores a pointer to a set with all the nodes related with a boundary.
std::set< TriangleMeshCurveSection * > Free_curve_section_pt
A set that contains the curve sections created by this object therefore it is necessary to free their associated memory.
std::set< TriangleMeshPolygon * > Free_polygon_pt
A set that contains the polygons created by this object therefore it is necessary to free their associated memory.
std::set< TriangleMeshOpenCurve * > Free_open_curve_pt
A set that contains the open curves created by this object therefore it is necessary to free their associated memory.
bool Immersed_rigid_body_triangle_mesh_polygon_used
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
Vector of Vector of pointers to nodes on the boundaries: Boundary_node_pt(b,n). Note that this is private to force the use of the add_boundary_node() function, which ensures that the reverse look-up schemes for the nodes are set up.
bool Lookup_for_elements_next_boundary_is_setup
Flag to indicate that the lookup schemes for elements that are adjacent to the boundaries has been set up.
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector of Vector of pointers to elements on the boundaries: Boundary_element_pt(b,e)
Vector< Vector< int > > Face_index_at_boundary
For the e-th finite element on boundary b, this is the index of the face that lies along that boundary.
std::map< unsigned, Vector< GeneralisedElement * > > Root_halo_element_pt
Map of vectors holding the pointers to the root halo elements.
std::map< unsigned, Vector< GeneralisedElement * > > Root_haloed_element_pt
Map of vectors holding the pointers to the root haloed elements.
std::map< unsigned, Vector< Node * > > Halo_node_pt
Map of vectors holding the pointers to the halo nodes.
std::map< unsigned, Vector< Node * > > Haloed_node_pt
Map of vectors holding the pointers to the haloed nodes.
std::map< unsigned, Vector< Node * > > Shared_node_pt
Map of vectors holding the pointers to the shared nodes. These are all the nodes that are on two "neighbouring" processes (the halo(ed) lookup scheme depends upon which processor is in charge.
OomphCommunicator * Comm_pt
Pointer to communicator -- set to NULL if mesh is not distributed.
std::map< unsigned, Vector< GeneralisedElement * > > External_halo_element_pt
External halo(ed) elements are created as and when they are needed to act as source elements for the particular process's mesh. The storage is wiped and rebuilt every time the mesh is refined.
std::map< unsigned, Vector< GeneralisedElement * > > External_haloed_element_pt
Map of vectors holding the pointers to the external haloed elements.
std::map< unsigned, Vector< Node * > > External_halo_node_pt
Map of vectors holding the pointers to the external halo nodes.
std::map< unsigned, Vector< Node * > > External_haloed_node_pt
Map of vectors holding the pointers to the external haloed nodes.
bool Keep_all_elements_as_halos
bool to indicate whether to keep all elements in a mesh as halos or not
bool Resize_halo_nodes_not_required
Set this to true to suppress resizing of halo nodes (at your own risk!)
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
Private Types
typedef double coord_t
typedef double coord2_t
Private Member Functions
coord2_t cross (const Point &O, const Point &A, const Point &B)
2D cross product of OA and OB vectors, i.e. z-component of their 3D cross product. Returns a positive value, if OAB makes a counter-clockwise turn, negative for clockwise turn, and zero if the points are collinear.
std::vector< Point > convex_hull (std::vector< Point > P)
Returns a list of points on the convex hull in counter-clockwise order. Note: the last point in the returned list is the same as the first one.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
Typedef for function pointer to function that computes steady exact solution.
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Typedef for function pointer to function that computes unsteady exact solution.
Static Public Attributes inherited from oomph::UnstructuredTwoDMeshGeometryBase
static bool Suppress_warning_about_regions_and_boundaries = true
Public static flag to suppress warning; defaults to false.
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
Default Steady Timestepper, to be used in default arguments to Mesh constructors.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Boolean used to control warning about empty mesh level timestepper function.
Detailed Description
template<class ELEMENT>
class oomph::TriangleMesh< ELEMENT >
Triangle mesh build with the help of the scaffold mesh coming from the triangle mesh generator Triangle. http://www.cs.cmu.edu/~quake/triangle.html.
Definition at line 407 of file meshes/triangle_mesh.h.
Member Typedef Documentation
coord2_t
template<class ELEMENT >
typedef double oomph::TriangleMesh< ELEMENT >::coord2_t [private]
Definition at line 2160 of file meshes/triangle_mesh.h.
coord_t
template<class ELEMENT >
typedef double oomph::TriangleMesh< ELEMENT >::coord_t [private]
Definition at line 2159 of file meshes/triangle_mesh.h.
Constructor & Destructor Documentation
TriangleMesh() [1/5]
template<class ELEMENT >
oomph::TriangleMesh< ELEMENT >::TriangleMesh () [inline]
Empty constructor.
Definition at line 411 of file meshes/triangle_mesh.h.
References oomph::UnstructuredTwoDMeshGeometryBase::Allow_automatic_creation_of_vertices_on_boundaries, oomph::TriangleMesh< ELEMENT >::First_time_compute_holes_left_by_halo_elements, and oomph::TriangleMesh< ELEMENT >::Triangulateio_exists.
TriangleMesh() [2/5]
template<class ELEMENT >
oomph::TriangleMesh< ELEMENT >::TriangleMesh (const std::string & node_file_name, const std::string & element_file_name, const std::string & poly_file_name, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & allow_automatic_creation_of_vertices_on_boundaries = true) [inline]
Constructor with the input files.
Definition at line 432 of file meshes/triangle_mesh.h.
References oomph::UnstructuredTwoDMeshGeometryBase::Allow_automatic_creation_of_vertices_on_boundaries, oomph::TriangleMesh< ELEMENT >::build_from_scaffold(), oomph::TriangleHelper::create_triangulateio_from_polyfiles(), oomph::TriangleMesh< ELEMENT >::First_time_compute_holes_left_by_halo_elements, oomph::Mesh::nboundary(), oomph::TriangleMesh< ELEMENT >::Time_stepper_pt, oomph::TriangleMesh< ELEMENT >::Tmp_mesh_pt, oomph::TriangleMeshBase::Triangulateio, oomph::TriangleMesh< ELEMENT >::Triangulateio_exists, and oomph::TriangleMesh< ELEMENT >::Use_attributes.
TriangleMesh() [3/5]
template<class ELEMENT >
oomph::TriangleMesh< ELEMENT >::TriangleMesh (TriangleMeshParameters & triangle_mesh_parameters, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Build mesh, based on the specifications on TriangleMeshParameters.
Definition at line 500 of file meshes/triangle_mesh.h.
References oomph::UnstructuredTwoDMeshGeometryBase::Allow_automatic_creation_of_vertices_on_boundaries, oomph::UnstructuredTwoDMeshGeometryBase::closed_curve_to_polygon_helper(), oomph::TriangleMeshParameters::communicator_pt(), oomph::UnstructuredTwoDMeshGeometryBase::create_open_curve_with_polyline_helper(), oomph::TriangleMesh< ELEMENT >::First_time_compute_holes_left_by_halo_elements, oomph::TriangleMesh< ELEMENT >::generic_constructor(), i, oomph::TriangleMeshParameters::is_automatic_creation_of_vertices_on_boundaries_allowed(), oomph::Mesh::nboundary(), oomph::TriangleMesh< ELEMENT >::Regions_areas, oomph::Mesh::set_communicator_pt(), oomph::UnstructuredTwoDMeshGeometryBase::set_geom_objects_and_coordinate_limits_for_close_curve(), oomph::UnstructuredTwoDMeshGeometryBase::set_geom_objects_and_coordinate_limits_for_open_curve(), oomph::FiniteElement::size(), oomph::UnstructuredTwoDMeshGeometryBase::snap_nodes_onto_geometric_objects(), and oomph::TriangleMesh< ELEMENT >::Time_stepper_pt.
TriangleMesh() [4/5]
template<class ELEMENT >
oomph::TriangleMesh< ELEMENT >::TriangleMesh (const std::string & poly_file_name, const double & element_area, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & allow_automatic_creation_of_vertices_on_boundaries = true) [inline]
Build mesh from poly file, with specified target area for all elements.
Definition at line 739 of file meshes/triangle_mesh.h.
References oomph::UnstructuredTwoDMeshGeometryBase::Allow_automatic_creation_of_vertices_on_boundaries, oomph::TriangleMesh< ELEMENT >::build_from_scaffold(), oomph::TriangleMesh< ELEMENT >::build_triangulateio(), oomph::TriangleHelper::clear_triangulateio(), oomph::TriangleMesh< ELEMENT >::First_time_compute_holes_left_by_halo_elements, oomph::UnstructuredTwoDMeshGeometryBase::is_automatic_creation_of_vertices_on_boundaries_allowed(), oomph::Mesh::nboundary(), oomph::TriangleMesh< ELEMENT >::Time_stepper_pt, oomph::TriangleMesh< ELEMENT >::Tmp_mesh_pt, oomph::triangulate(), oomph::TriangleMeshBase::Triangulateio, and oomph::TriangleMesh< ELEMENT >::Use_attributes.
TriangleMesh() [5/5]
template<class ELEMENT >
oomph::TriangleMesh< ELEMENT >::TriangleMesh (const TriangleMesh< ELEMENT > & dummy) [delete]
Broken copy constructor.
~TriangleMesh()
template<class ELEMENT >
virtual oomph::TriangleMesh< ELEMENT >::~TriangleMesh () [inline], [virtual]
Destructor.
Definition at line 835 of file meshes/triangle_mesh.h.
References oomph::TriangleHelper::clear_triangulateio(), oomph::UnstructuredTwoDMeshGeometryBase::Free_curve_section_pt, oomph::UnstructuredTwoDMeshGeometryBase::Free_open_curve_pt, oomph::UnstructuredTwoDMeshGeometryBase::Free_polygon_pt, oomph::TriangleMeshBase::Triangulateio, and oomph::TriangleMesh< ELEMENT >::Triangulateio_exists.
Member Function Documentation
add_face_index_at_shared_boundary()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::add_face_index_at_shared_boundary (const unsigned & b, const unsigned & i) [inline], [protected]
Definition at line 1569 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Face_index_at_shared_boundary, and i.
add_shared_boundary_element()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::add_shared_boundary_element (const unsigned & b, FiniteElement * ele_pt) [inline], [protected]
Definition at line 1539 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundary_element_pt.
add_shared_boundary_node()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::add_shared_boundary_node (const unsigned & b, Node * node_pt) [inline], [protected]
Add the node the shared boundary.
Definition at line 1625 of file meshes/triangle_mesh.h.
References oomph::Mesh::node_pt(), oomph::TriangleMesh< ELEMENT >::Shared_boundary_node_pt, and oomph::FiniteElement::size().
boundary_marked_as_shared_boundary()
template<class ELEMENT >
const bool oomph::TriangleMesh< ELEMENT >::boundary_marked_as_shared_boundary (const unsigned & b, const unsigned & isub) [inline], [protected]
Returns the value that indicates if a subpolyline of a given boundary continues been used as internal boundary or should be changed as shared boundary.
Definition at line 1889 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Boundary_marked_as_shared_boundary.
boundary_segment_node_pt() [1/3]
template<class ELEMENT >
Vector< Vector< Node * > > & oomph::TriangleMesh< ELEMENT >::boundary_segment_node_pt (const unsigned & b) [inline]
Return direct access to nodes associated with a boundary but sorted in segments.
Definition at line 933 of file meshes/triangle_mesh.h.
References oomph::UnstructuredTwoDMeshGeometryBase::Boundary_segment_node_pt.
boundary_segment_node_pt() [2/3]
template<class ELEMENT >
Vector< Node * > & oomph::TriangleMesh< ELEMENT >::boundary_segment_node_pt (const unsigned & b, const unsigned & s) [inline]
Return direct access to nodes associated with a segment of a given boundary.
Definition at line 940 of file meshes/triangle_mesh.h.
References oomph::UnstructuredTwoDMeshGeometryBase::Boundary_segment_node_pt, and s.
boundary_segment_node_pt() [3/3]
template<class ELEMENT >
Node *& oomph::TriangleMesh< ELEMENT >::boundary_segment_node_pt (const unsigned & b, const unsigned & s, const unsigned & n) [inline]
Return pointer to node n on boundary b.
Definition at line 947 of file meshes/triangle_mesh.h.
References oomph::UnstructuredTwoDMeshGeometryBase::Boundary_segment_node_pt, and s.
boundary_subpolylines()
template<class ELEMENT >
Vector< TriangleMeshPolyLine * > & oomph::TriangleMesh< ELEMENT >::boundary_subpolylines (const unsigned & b) [inline], [protected]
Gets the vector of auxiliar polylines that will represent the given boundary (useful only when the boundaries were split)
Definition at line 1863 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Boundary_subpolylines.
boundary_was_splitted()
template<class ELEMENT >
const bool oomph::TriangleMesh< ELEMENT >::boundary_was_splitted (const unsigned & b) [inline], [protected]
Helper function to verify if a given boundary was splitted in the distribution process.
Definition at line 1819 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Boundary_was_splitted.
break_loops_on_shared_polyline_helper()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::break_loops_on_shared_polyline_helper (const unsigned & initial_shd_bnd_id, std::list< Node * > & input_nodes, Vector< FiniteElement * > & input_boundary_element_pt, Vector< int > & input_face_index_element, const int & input_connect_to_the_left, const int & input_connect_to_the_right, Vector< std::list< Node * > > & output_sorted_nodes_pt, Vector< Vector< FiniteElement * > > & output_boundary_element_pt, Vector< Vector< int > > & output_face_index_element, Vector< int > & output_connect_to_the_left, Vector< int > & output_connect_to_the_right) [protected]
Break any possible loop created by the sorted list of nodes that is used to create a new shared polyline.
Definition at line 13271 of file triangle_mesh.template.cc.
References oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
break_loops_on_shared_polyline_load_balance_helper()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::break_loops_on_shared_polyline_load_balance_helper (const unsigned & initial_shd_bnd_id, std::list< Node * > & input_nodes, Vector< FiniteElement * > & input_boundary_element_pt, Vector< FiniteElement * > & input_boundary_face_element_pt, Vector< int > & input_face_index_element, const int & input_connect_to_the_left, const int & input_connect_to_the_right, Vector< std::list< Node * > > & output_sorted_nodes_pt, Vector< Vector< FiniteElement * > > & output_boundary_element_pt, Vector< Vector< FiniteElement * > > & output_boundary_face_element_pt, Vector< Vector< int > > & output_face_index_element, Vector< int > & output_connect_to_the_left, Vector< int > & output_connect_to_the_right) [protected]
Break any possible loop created by the sorted list of nodes that is used to create a new shared polyline (modified version for load balance)
Definition at line 14195 of file triangle_mesh.template.cc.
References oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
build_from_scaffold()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::build_from_scaffold (TimeStepper * time_stepper_pt, const bool & use_attributes) [protected]
Build mesh from scaffold.
Build with the help of the scaffold mesh coming from the triangle mesh generator Triangle.
Definition at line 47 of file triangle_mesh.template.cc.
References oomph::FiniteElement::construct_boundary_node(), oomph::FiniteElement::construct_node(), oomph::FiniteElement::dim(), e, i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::local_coordinate_of_node(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::Node_pt, oomph::FiniteElement::node_pt(), oomph::Node::resize(), s, oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::GeomObject::time_stepper_pt().
Referenced by oomph::TriangleMesh< ELEMENT >::generic_constructor(), oomph::TriangleMesh< ELEMENT >::remesh_from_internal_triangulateio(), oomph::TriangleMesh< ELEMENT >::TriangleMesh(), and oomph::TriangleMesh< ELEMENT >::TriangleMesh().
build_triangulateio()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::build_triangulateio (const std::string & poly_file_name, TriangulateIO & triangulate_io, bool & use_attributes) [protected]
Helper function to create TriangulateIO object (return in triangulate_io) from the .poly file.
Create TriangulateIO object via the .poly file.
Definition at line 7204 of file triangle_mesh.template.cc.
References i, oomph::TriangleHelper::initialise_triangulateio(), oomph::oomph_info, and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
Referenced by oomph::TriangleMesh< ELEMENT >::TriangleMesh().
check_connections_of_polyline_nodes()
template<class ELEMENT >
const int oomph::TriangleMesh< ELEMENT >::check_connections_of_polyline_nodes (std::set< FiniteElement * > & element_in_processor_pt, const int & root_edge_bnd_id, std::map< std::pair< Node *, Node * >, bool > & overlapped_face, std::map< unsigned, std::map< Node *, bool > > & node_on_bnd_not_overlapped_by_shd_bnd, std::list< Node * > & current_polyline_nodes, std::map< unsigned, std::list< Node * > > & shared_bnd_id_to_sorted_list_node_pt, const unsigned & node_degree, Node *& new_node_pt, const bool called_from_load_balance = false) [protected]
Check for any possible connections that the array of sorted nodes have with any previous boundaries or with itself. Return -1 if no connection was found, return -2 if the connection is with the same polyline, return the boundary id of the boundary to which the connection is performed.
Definition at line 9077 of file triangle_mesh.template.cc.
References e, i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
compute_boundary_segments_connectivity_and_initial_zeta_values()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::compute_boundary_segments_connectivity_and_initial_zeta_values (const unsigned & b)
Compute the boundary segments connectivity for those boundaries that were splited during the distribution process.
Compute the boundary segments connectivity for those boundaries that were splited during the distribution process and also the initial zeta values for each segment (the initial and final boundary nodes coordinates)
Definition at line 1839 of file triangle_mesh.template.cc.
References i, oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::GeneralisedElement::non_halo_proc_ID(), oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
compute_holes_left_by_halo_elements_helper()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::compute_holes_left_by_halo_elements_helper (Vector< Vector< double > > & output_holes_coordinates) [protected]
Compute the holes left by the halo elements, those adjacent to the shared boundaries.
Definition at line 10825 of file triangle_mesh.template.cc.
References e, i, oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
convex_hull()
template<class ELEMENT >
std::vector< Point > oomph::TriangleMesh< ELEMENT >::convex_hull (std::vector< Point > P) [inline], [private]
Returns a list of points on the convex hull in counter-clockwise order. Note: the last point in the returned list is the same as the first one.
Definition at line 2184 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::cross(), i, oomph::FiniteElement::size(), and t.
create_distributed_domain_representation()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::create_distributed_domain_representation (Vector< TriangleMeshPolygon * > & polygons_pt, Vector< TriangleMeshOpenCurve * > & open_curves_pt) [protected]
Creates the distributed domain representation. Joins the original boundaires, shared boundaries and creates connections among them to create the new polygons that represent the distributed domain.
Definition at line 8137 of file triangle_mesh.template.cc.
References i, oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
create_polylines_from_halo_elements_helper()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::create_polylines_from_halo_elements_helper (const Vector< unsigned > & element_domain, std::map< GeneralisedElement *, unsigned > & element_to_global_index, std::set< FiniteElement * > & element_in_processor_pt, Vector< Vector< Vector< GeneralisedElement * > > > & input_halo_elements, std::map< std::pair< Node *, Node * >, unsigned > & elements_edges_on_boundary, Vector< Vector< Vector< TriangleMeshPolyLine * > > > & output_polylines_pt) [protected]
Creates polylines from the intersection of halo elements on all processors. The new polylines define the shared boundaries in the domain This get the polylines on ALL processors, that is why the three dimensions output_polylines_pt[iproc][ncurve][npolyline].
Definition at line 11776 of file triangle_mesh.template.cc.
References e, i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
create_shared_boundaries()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::create_shared_boundaries (OomphCommunicator * comm_pt, const Vector< unsigned > & element_domain, const Vector< GeneralisedElement * > & backed_up_el_pt, const Vector< FiniteElement * > & backed_up_f_el_pt, std::map< Data *, std::set< unsigned > > & processors_associated_with_data, const bool & overrule_keep_as_halo_element_status) [protected], [virtual]
Creates the shared boundaries.
Reimplemented from oomph::Mesh.
Definition at line 11544 of file triangle_mesh.template.cc.
References e, oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
create_shared_polyline()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::create_shared_polyline (const unsigned & my_rank, const unsigned & shd_bnd_id, const unsigned & iproc, const unsigned & jproc, std::list< Node * > & sorted_nodes, const int & root_edge_bnd_id, Vector< FiniteElement * > & bulk_bnd_ele_pt, Vector< int > & face_index_ele, Vector< Vector< TriangleMeshPolyLine * > > & unsorted_polylines_pt, const int & connect_to_the_left_flag, const int & connect_to_the_right_flag) [protected]
Create the shared polyline and fill the data structured that keep all the information associated with the creationg of the shared boundary.
Definition at line 14623 of file triangle_mesh.template.cc.
References oomph::TriangleMeshCurveSection::final_vertex_connected_bnd_id(), oomph::TriangleMeshCurveSection::final_vertex_connected_n_chunk(), i, oomph::TriangleMeshCurveSection::initial_vertex_connected_bnd_id(), oomph::TriangleMeshCurveSection::initial_vertex_connected_n_chunk(), oomph::TriangleMeshCurveSection::set_final_vertex_connected(), oomph::TriangleMeshCurveSection::set_initial_vertex_connected(), oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
create_shared_polylines_connections()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::create_shared_polylines_connections () [protected]
Establish the connections of the polylines previously marked as having connections. This connections were marked in the function TriangleMesh::create_polylines_from_halo_elements_helper().
Definition at line 9517 of file triangle_mesh.template.cc.
References i, oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
create_tmp_open_curves_helper()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::create_tmp_open_curves_helper (Vector< Vector< TriangleMeshPolyLine * > > & sorted_open_curves_pt, Vector< TriangleMeshPolyLine * > & unsorted_shared_to_internal_poly_pt, Vector< TriangleMeshOpenCurve * > & open_curves_pt) [protected]
Take the polylines from the original open curves and created new temporaly representations of open curves with the bits of original curves not overlapped by shared boundaries.
Definition at line 9037 of file triangle_mesh.template.cc.
References i, oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
create_tmp_polygons_helper()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::create_tmp_polygons_helper (Vector< Vector< TriangleMeshPolyLine * > > & polylines_pt, Vector< TriangleMeshPolygon * > & polygons_pt) [protected]
Take the polylines from the shared boundaries and create temporary polygon representations of the domain.
Definition at line 8637 of file triangle_mesh.template.cc.
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::diff(), i, oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error.
cross()
template<class ELEMENT >
coord2_t oomph::TriangleMesh< ELEMENT >::cross (const Point & O, const Point & A, const Point & B) [inline], [private]
2D cross product of OA and OB vectors, i.e. z-component of their 3D cross product. Returns a positive value, if OAB makes a counter-clockwise turn, negative for clockwise turn, and zero if the points are collinear.
Definition at line 2176 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Point::x, and oomph::TriangleMesh< ELEMENT >::Point::y.
Referenced by oomph::TriangleMesh< ELEMENT >::convex_hull().
dump_distributed_info_for_restart()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::dump_distributed_info_for_restart (std::ostream & dump_file) [virtual]
Used to dump info. related with distributed triangle meshes.
Reimplemented from oomph::TriangleMeshBase.
Definition at line 7443 of file triangle_mesh.template.cc.
References oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
face_index_at_shared_boundary()
template<class ELEMENT >
int oomph::TriangleMesh< ELEMENT >::face_index_at_shared_boundary (const unsigned & b, const unsigned & e) [inline], [protected]
Definition at line 1574 of file meshes/triangle_mesh.h.
References e, and oomph::TriangleMesh< ELEMENT >::Face_index_at_shared_boundary.
final_shared_boundary_id()
template<class ELEMENT >
const unsigned oomph::TriangleMesh< ELEMENT >::final_shared_boundary_id () [inline]
The final boundary id for shared boundaries.
Definition at line 1350 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Final_shared_boundary_id.
flush_face_index_at_shared_boundary()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::flush_face_index_at_shared_boundary () [inline], [protected]
Definition at line 1564 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Face_index_at_shared_boundary.
flush_shared_boundary_element() [1/2]
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::flush_shared_boundary_element () [inline], [protected]
Definition at line 1515 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundary_element_pt.
flush_shared_boundary_element() [2/2]
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::flush_shared_boundary_element (const unsigned & b) [inline], [protected]
Definition at line 1520 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundary_element_pt.
flush_shared_boundary_node() [1/2]
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::flush_shared_boundary_node () [inline], [protected]
Flush ALL the shared boundary nodes.
Definition at line 1613 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundary_node_pt.
flush_shared_boundary_node() [2/2]
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::flush_shared_boundary_node (const unsigned & b) [inline], [protected]
Flush the boundary nodes associated to the shared boundary b.
Definition at line 1619 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundary_node_pt.
flush_shared_boundary_polyline_pt()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::flush_shared_boundary_polyline_pt () [inline], [protected]
Definition at line 1930 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundary_polyline_pt.
generic_constructor()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::generic_constructor (Vector< TriangleMeshPolygon * > & outer_boundary_pt, Vector< TriangleMeshPolygon * > & internal_polygon_pt, Vector< TriangleMeshOpenCurve * > & open_polylines_pt, const double & element_area, Vector< Vector< double > > & extra_holes_coordinates, std::map< unsigned, Vector< double > > & regions_coordinates, std::map< unsigned, double > & regions_areas, TimeStepper * time_stepper_pt, const bool & use_attributes, const bool & refine_boundary, const bool & refine_internal_boundary) [inline], [protected]
A general-purpose construction function that builds the mesh once the different specific constructors have assembled the appropriate information.
Definition at line 1188 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::build_from_scaffold(), oomph::UnstructuredTwoDMeshGeometryBase::build_triangulateio(), oomph::TriangleHelper::clear_triangulateio(), e, oomph::UnstructuredTwoDMeshGeometryBase::Extra_holes_coordinates, oomph::TriangleHelper::initialise_triangulateio(), oomph::UnstructuredTwoDMeshGeometryBase::Internal_open_curve_pt, oomph::UnstructuredTwoDMeshGeometryBase::Internal_polygon_pt, oomph::UnstructuredTwoDMeshGeometryBase::is_automatic_creation_of_vertices_on_boundaries_allowed(), oomph::UnstructuredTwoDMeshGeometryBase::Outer_boundary_pt, oomph::UnstructuredTwoDMeshGeometryBase::Regions_coordinates, oomph::TriangleMesh< ELEMENT >::Time_stepper_pt, oomph::TriangleMesh< ELEMENT >::Tmp_mesh_pt, oomph::triangulate(), oomph::TriangleMeshBase::Triangulateio, oomph::TriangleMesh< ELEMENT >::Triangulateio_exists, and oomph::TriangleMesh< ELEMENT >::Use_attributes.
Referenced by oomph::TriangleMesh< ELEMENT >::TriangleMesh().
get_element_edges_on_boundary()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::get_element_edges_on_boundary (std::map< std::pair< Node *, Node * >, unsigned > & element_edges_on_boundary) [protected]
Get the element edges (pair of nodes, edges) that lie on a boundary (used to mark shared boundaries that lie on internal boundaries)
Definition at line 11711 of file triangle_mesh.template.cc.
References e, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
get_halo_elements_on_all_procs()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::get_halo_elements_on_all_procs (const unsigned & nproc, const Vector< unsigned > & element_domain, const Vector< GeneralisedElement * > & backed_up_el_pt, std::map< Data *, std::set< unsigned > > & processors_associated_with_data, const bool & overrule_keep_as_halo_element_status, std::map< GeneralisedElement *, unsigned > & element_to_global_index, Vector< Vector< Vector< GeneralisedElement * > > > & output_halo_elements_pt) [protected]
Creates the halo elements on all processors Gets the halo elements on all processors, these elements are then used on the function that computes the shared boundaries among the processors.
Definition at line 11622 of file triangle_mesh.template.cc.
References e, oomph::GeneralisedElement::must_be_kept_as_halo(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
get_shared_boundaries_overlapping_internal_boundary()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::get_shared_boundaries_overlapping_internal_boundary (const unsigned & internal_bnd_id, Vector< unsigned > & shd_bnd_ids) [inline], [protected]
Gets the shared boundaries ids that overlap the given internal boundary.
Definition at line 1774 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundary_overlaps_internal_boundary, and oomph::FiniteElement::size().
identify_boundary_segments_and_assign_initial_zeta_values() [1/2]
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::identify_boundary_segments_and_assign_initial_zeta_values (const unsigned & b, TriangleMesh< ELEMENT > * original_mesh_pt)
Identify the segments from the old mesh (original mesh) in the new mesh (this) and assign initial and final boundary coordinates for the segments that create the boundary.
Definition at line 389 of file triangle_mesh.template.cc.
References e, i, oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error.
identify_boundary_segments_and_assign_initial_zeta_values() [2/2]
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::identify_boundary_segments_and_assign_initial_zeta_values (const unsigned & b, Vector< FiniteElement * > & input_face_ele_pt, const bool & is_internal_boundary, std::map< FiniteElement *, FiniteElement * > & face_to_bulk_element_pt)
Identify the segments from the old mesh (original mesh) in the new mesh (this) and assign initial and final boundary coordinates for the segments that create the boundary. (This is the version called from the original mesh to identify its own segments)
initial_shared_boundary_id()
template<class ELEMENT >
const unsigned oomph::TriangleMesh< ELEMENT >::initial_shared_boundary_id () [inline]
The initial boundary id for shared boundaries.
Definition at line 1344 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Initial_shared_boundary_id.
Referenced by oomph::TriangleMesh< ELEMENT >::remesh_from_internal_triangulateio().
is_node_on_shared_boundary()
template<class ELEMENT >
bool oomph::TriangleMesh< ELEMENT >::is_node_on_shared_boundary (const unsigned & b, Node *const & node_pt) [inline], [protected]
Is the node on the shared boundary.
Definition at line 1667 of file meshes/triangle_mesh.h.
References oomph::Mesh::node_pt(), and oomph::TriangleMesh< ELEMENT >::Shared_boundary_node_pt.
load_balance()
template<class ELEMENT >
virtual void oomph::TriangleMesh< ELEMENT >::load_balance (const Vector< unsigned > & target_domain_for_local_non_halo_element) [inline], [virtual]
Virtual function to perform the load balance routines.
Reimplemented from oomph::TriangleMeshBase.
Reimplemented in oomph::RefineableTriangleMesh< ELEMENT >.
Definition at line 2127 of file meshes/triangle_mesh.h.
nboundary_subpolylines()
template<class ELEMENT >
const unsigned oomph::TriangleMesh< ELEMENT >::nboundary_subpolylines (const unsigned & b) [inline], [protected]
Gets the number of subpolylines that create the boundarya (useful only when the boundary is marked as split)
Definition at line 1835 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Boundary_subpolylines.
nshared_boundaries() [1/2]
template<class ELEMENT >
const unsigned oomph::TriangleMesh< ELEMENT >::nshared_boundaries () const [inline], [protected]
Definition at line 1491 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundary_element_pt, and oomph::FiniteElement::size().
Referenced by oomph::TriangleMesh< ELEMENT >::shared_boundaries_in_this_processor().
nshared_boundaries() [2/2]
template<class ELEMENT >
const unsigned oomph::TriangleMesh< ELEMENT >::nshared_boundaries (const unsigned & p, const unsigned & q) const [inline], [protected]
Access functions to boundaries shared with processors.
Definition at line 1422 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundaries_ids, and oomph::FiniteElement::size().
nshared_boundary_curves()
template<class ELEMENT >
const unsigned oomph::TriangleMesh< ELEMENT >::nshared_boundary_curves (const unsigned & p) const [inline], [protected]
Definition at line 1467 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundary_polyline_pt, and oomph::FiniteElement::size().
nshared_boundary_element()
template<class ELEMENT >
const unsigned oomph::TriangleMesh< ELEMENT >::nshared_boundary_element (const unsigned & b) [inline], [protected]
Definition at line 1496 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundary_element_pt, and oomph::FiniteElement::size().
nshared_boundary_node()
template<class ELEMENT >
const unsigned oomph::TriangleMesh< ELEMENT >::nshared_boundary_node (const unsigned & b) [inline], [protected]
Definition at line 1593 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundary_node_pt, and oomph::FiniteElement::size().
nshared_boundary_overlaps_internal_boundary()
template<class ELEMENT >
const unsigned oomph::TriangleMesh< ELEMENT >::nshared_boundary_overlaps_internal_boundary () [inline], [protected]
Get the number of shared boundaries overlaping internal boundaries.
Definition at line 1729 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundary_overlaps_internal_boundary, and oomph::FiniteElement::size().
nshared_boundary_polyline()
template<class ELEMENT >
const unsigned oomph::TriangleMesh< ELEMENT >::nshared_boundary_polyline (const unsigned & p, const unsigned & c) const [inline], [protected]
Definition at line 1472 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundary_polyline_pt, and oomph::FiniteElement::size().
oomph_vertex_nodes_id()
template<class ELEMENT >
Vector< unsigned > oomph::TriangleMesh< ELEMENT >::oomph_vertex_nodes_id () [inline]
Return the vector that contains the oomph-lib node number for all vertex nodes in the TriangulateIO representation of the mesh.
Definition at line 1156 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Oomph_vertex_nodes_id.
operator=()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::operator= (const TriangleMesh< ELEMENT > &) [delete]
Broken assignment operator.
output_boundary_coordinates()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::output_boundary_coordinates (const unsigned & b, std::ostream & outfile)
Output the nodes on the boundary and their respective boundary coordinates(into separate tecplot zones)
Definition at line 8020 of file triangle_mesh.template.cc.
References e, i, oomph::GeneralisedElement::is_halo(), oomph::GeomObject::ndim(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
re_assign_initial_zeta_values_for_internal_boundary()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::re_assign_initial_zeta_values_for_internal_boundary (const unsigned & b, Vector< std::list< FiniteElement * > > & old_segment_sorted_ele_pt, std::map< FiniteElement *, bool > & old_is_inverted)
Re-assign the boundary segments initial zeta (arclength) value for those internal boundaries that were splited during the distribution process. Those boundaries that have one face element at each side of the boundary.
Re-assign the boundary segments initial zeta (arclength) for those internal boundaries that were splited during the distribution process. Those boundaries that have one face element at each side of the boundary. Here we create the segments only with the nonhalo elements, therefore the boundary coordinates need to be re-assigned to be passed to the new meshes.
Definition at line 4090 of file triangle_mesh.template.cc.
References e, i, oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
re_scale_re_assigned_initial_zeta_values_for_internal_boundary()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::re_scale_re_assigned_initial_zeta_values_for_internal_boundary (const unsigned & b)
Re-scale the re-assigned zeta values for the boundary nodes, apply only for internal boundaries.
Re-assign the boundary segments initial zeta (arclength) for those internal boundaries that were splited during the distribution process (only apply for internal boundaries that have one face element at each side of the boundary)
Definition at line 6571 of file triangle_mesh.template.cc.
References e, i, oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
read_distributed_info_for_restart()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::read_distributed_info_for_restart (std::istream & restart_file) [virtual]
Used to read info. related with distributed triangle meshes.
Reimplemented from oomph::TriangleMeshBase.
Definition at line 7686 of file triangle_mesh.template.cc.
References oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
read_unsigned_line_helper()
template<class ELEMENT >
const unsigned oomph::TriangleMesh< ELEMENT >::read_unsigned_line_helper (std::istream & read_file) [inline]
Definition at line 1007 of file meshes/triangle_mesh.h.
reestablish_distribution_info_for_restart()
template<class ELEMENT >
virtual void oomph::TriangleMesh< ELEMENT >::reestablish_distribution_info_for_restart (OomphCommunicator * comm_pt, std::istream & restart_file) [inline], [virtual]
Virtual function used to re-establish any additional info. related with the distribution after a re-starting for triangle meshes.
Reimplemented from oomph::TriangleMeshBase.
Reimplemented in oomph::RefineableTriangleMesh< ELEMENT >.
Definition at line 1026 of file meshes/triangle_mesh.h.
remesh_from_internal_triangulateio()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::remesh_from_internal_triangulateio () [inline], [virtual]
Completely regenerate the mesh from the trianglateio structure.
Reimplemented from oomph::TriangleMeshBase.
Definition at line 1041 of file meshes/triangle_mesh.h.
References oomph::UnstructuredTwoDMeshGeometryBase::Boundary_curve_section_pt, oomph::Mesh::Boundary_element_pt, oomph::UnstructuredTwoDMeshGeometryBase::Boundary_region_element_pt, oomph::TriangleMesh< ELEMENT >::build_from_scaffold(), e, oomph::Mesh::Element_pt, oomph::Mesh::External_halo_element_pt, oomph::Mesh::External_halo_node_pt, oomph::Mesh::External_haloed_element_pt, oomph::Mesh::External_haloed_node_pt, oomph::Mesh::Face_index_at_boundary, oomph::UnstructuredTwoDMeshGeometryBase::Face_index_region_at_boundary, oomph::Mesh::flush_element_and_node_storage(), oomph::Mesh::Halo_node_pt, oomph::Mesh::Haloed_node_pt, oomph::TriangleMesh< ELEMENT >::initial_shared_boundary_id(), oomph::Mesh::is_mesh_distributed(), oomph::Mesh::nboundary(), oomph::Mesh::nelement(), oomph::Mesh::nnode(), oomph::Mesh::Node_pt, oomph::UnstructuredTwoDMeshGeometryBase::Polygonal_vertex_arclength_info, oomph::UnstructuredTwoDMeshGeometryBase::Region_attribute, oomph::UnstructuredTwoDMeshGeometryBase::Region_element_pt, oomph::Mesh::remove_boundary_nodes(), oomph::Mesh::Root_halo_element_pt, oomph::Mesh::Root_haloed_element_pt, oomph::Mesh::set_nboundary(), oomph::UnstructuredTwoDMeshGeometryBase::snap_nodes_onto_geometric_objects(), oomph::TriangleMesh< ELEMENT >::Time_stepper_pt, oomph::TriangleMesh< ELEMENT >::Tmp_mesh_pt, oomph::TriangleMeshBase::Triangulateio, oomph::TriangleMesh< ELEMENT >::Triangulateio_exists, and oomph::TriangleMesh< ELEMENT >::Use_attributes.
reset_boundary_element_info()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::reset_boundary_element_info (Vector< unsigned > & ntmp_boundary_elements, Vector< Vector< unsigned > > & ntmp_boundary_elements_in_region, Vector< FiniteElement * > & deleted_elements) [virtual]
Virtual function to perform the reset boundary elements info routines. Generally used after load balance.
Reset the boundary elements info. after load balance have taken place.
Reimplemented from oomph::TriangleMeshBase.
Definition at line 14866 of file triangle_mesh.template.cc.
References e, and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
select_boundary_face_elements()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::select_boundary_face_elements (Vector< FiniteElement * > & face_ele_pt, const unsigned & b, bool & is_internal_boundary, std::map< FiniteElement *, FiniteElement * > & face_to_bulk_element_pt)
Select face element from boundary using the criteria to decide which of the two face elements should be used on internal boundaries.
===================================================================== Select face elements from a given boundary. In case the we are dealing with an internal boundary we use a set of criterias to decide which of the two face elements should be used on represent the internal boundary. We return the face elements, halo or haloed on this processor that form the boundary. The caller method should be in charge of selecting nonhalo elements and deleting the face
elements created by this method
Definition at line 5283 of file triangle_mesh.template.cc.
References e, i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::GeneralisedElement::non_halo_proc_ID(), oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::Node::x().
set_mesh_level_time_stepper()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::set_mesh_level_time_stepper (TimeStepper *const & time_stepper_pt, const bool & preserve_existing_data) [inline], [virtual]
Overload set_mesh_level_time_stepper so that the stored time stepper now corresponds to the new timestepper.
Reimplemented from oomph::Mesh.
Definition at line 872 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Time_stepper_pt.
shared_boundaries_ids() [1/7]
template<class ELEMENT >
Vector< Vector< Vector< unsigned > > > & oomph::TriangleMesh< ELEMENT >::shared_boundaries_ids () [inline], [protected]
Definition at line 1433 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundaries_ids.
shared_boundaries_ids() [2/7]
template<class ELEMENT >
Vector< Vector< Vector< unsigned > > > oomph::TriangleMesh< ELEMENT >::shared_boundaries_ids () const [inline], [protected]
Definition at line 1428 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundaries_ids.
Referenced by oomph::TriangleMesh< ELEMENT >::shared_boundaries_in_this_processor().
shared_boundaries_ids() [3/7]
template<class ELEMENT >
Vector< Vector< unsigned > > & oomph::TriangleMesh< ELEMENT >::shared_boundaries_ids (const unsigned & p) [inline], [protected]
Definition at line 1443 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundaries_ids.
shared_boundaries_ids() [4/7]
template<class ELEMENT >
Vector< Vector< unsigned > > oomph::TriangleMesh< ELEMENT >::shared_boundaries_ids (const unsigned & p) const [inline], [protected]
Definition at line 1438 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundaries_ids.
shared_boundaries_ids() [5/7]
template<class ELEMENT >
Vector< unsigned > & oomph::TriangleMesh< ELEMENT >::shared_boundaries_ids (const unsigned & p, const unsigned & q) [inline], [protected]
Definition at line 1454 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundaries_ids.
shared_boundaries_ids() [6/7]
template<class ELEMENT >
Vector< unsigned > oomph::TriangleMesh< ELEMENT >::shared_boundaries_ids (const unsigned & p, const unsigned & q) const [inline], [protected]
Definition at line 1448 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundaries_ids.
shared_boundaries_ids() [7/7]
template<class ELEMENT >
const unsigned oomph::TriangleMesh< ELEMENT >::shared_boundaries_ids (const unsigned & p, const unsigned & q, const unsigned & i) const [inline], [protected]
Definition at line 1460 of file meshes/triangle_mesh.h.
References i, and oomph::TriangleMesh< ELEMENT >::Shared_boundaries_ids.
shared_boundaries_in_this_processor()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::shared_boundaries_in_this_processor (Vector< unsigned > & shared_boundaries_in_this_processor) [inline], [protected]
Get the shared boundaries ids living in the current processor.
Definition at line 1357 of file meshes/triangle_mesh.h.
References oomph::Mesh::communicator_pt(), oomph::TriangleMesh< ELEMENT >::nshared_boundaries(), oomph::TriangleMesh< ELEMENT >::shared_boundaries_ids(), and oomph::TriangleMesh< ELEMENT >::shared_boundaries_in_this_processor().
Referenced by oomph::TriangleMesh< ELEMENT >::shared_boundaries_in_this_processor().
shared_boundary_element_pt()
template<class ELEMENT >
FiniteElement * oomph::TriangleMesh< ELEMENT >::shared_boundary_element_pt (const unsigned & b, const unsigned & e) [inline], [protected]
Definition at line 1544 of file meshes/triangle_mesh.h.
References e, and oomph::TriangleMesh< ELEMENT >::Shared_boundary_element_pt.
shared_boundary_from_processors() [1/2]
template<class ELEMENT >
std::map< unsigned, Vector< unsigned > > & oomph::TriangleMesh< ELEMENT >::shared_boundary_from_processors () [inline], [protected]
Return the association of the shared boundaries with the processors.
Definition at line 1700 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundary_from_processors.
shared_boundary_from_processors() [2/2]
template<class ELEMENT >
Vector< unsigned > & oomph::TriangleMesh< ELEMENT >::shared_boundary_from_processors (const unsigned & b) [inline], [protected]
Definition at line 1705 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundary_from_processors.
shared_boundary_node_pt()
template<class ELEMENT >
Node * oomph::TriangleMesh< ELEMENT >::shared_boundary_node_pt (const unsigned & b, const unsigned & n) [inline], [protected]
Definition at line 1647 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundary_node_pt.
shared_boundary_overlapping_internal_boundary()
template<class ELEMENT >
const unsigned oomph::TriangleMesh< ELEMENT >::shared_boundary_overlapping_internal_boundary (const unsigned & shd_bnd_id) [inline], [protected]
Gets the boundary id of the internal boundary that the shared boundary lies on.
Definition at line 1749 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundary_overlaps_internal_boundary.
shared_boundary_overlaps_internal_boundary() [1/2]
template<class ELEMENT >
std::map< unsigned, unsigned > & oomph::TriangleMesh< ELEMENT >::shared_boundary_overlaps_internal_boundary () [inline], [protected]
Gets the storage that indicates if a shared boundary is part of an internal boundary.
Definition at line 1812 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundary_overlaps_internal_boundary.
shared_boundary_overlaps_internal_boundary() [2/2]
template<class ELEMENT >
const bool oomph::TriangleMesh< ELEMENT >::shared_boundary_overlaps_internal_boundary (const unsigned & shd_bnd_id) [inline], [protected]
Checks if the shared boundary overlaps an internal boundary.
Definition at line 1735 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundary_overlaps_internal_boundary.
shared_boundary_polyline_pt() [1/2]
template<class ELEMENT >
Vector< TriangleMeshPolyLine * > & oomph::TriangleMesh< ELEMENT >::shared_boundary_polyline_pt (const unsigned & p, const unsigned & c) [inline], [protected]
Definition at line 1478 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Shared_boundary_polyline_pt.
shared_boundary_polyline_pt() [2/2]
template<class ELEMENT >
TriangleMeshPolyLine * oomph::TriangleMesh< ELEMENT >::shared_boundary_polyline_pt (const unsigned & p, const unsigned & c, const unsigned & i) const [inline], [protected]
Definition at line 1484 of file meshes/triangle_mesh.h.
References i, and oomph::TriangleMesh< ELEMENT >::Shared_boundary_polyline_pt.
sort_polylines_helper()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::sort_polylines_helper (Vector< TriangleMeshPolyLine * > & unsorted_polylines_pt, Vector< Vector< TriangleMeshPolyLine * > > & sorted_polylines_pt) [protected]
Sorts the polylines so they be continuous and then we can create a closed or open curve from them.
Definition at line 11344 of file triangle_mesh.template.cc.
References i, oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
synchronize_boundary_coordinates()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::synchronize_boundary_coordinates (const unsigned & b)
In charge of sinchronize the boundary coordinates for internal boundaries that were split as part of the distribution process. Called after setup_boundary_coordinates() for the original mesh only.
======================================================================== In charge of sinchronize the boundary coordinates for internal boundaries that were split as part of the distribution process. Called after setup_boundary_coordinates() for the
original mesh only
Definition at line 5612 of file triangle_mesh.template.cc.
References e, oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::GeneralisedElement::non_halo_proc_ID(), oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::Node::x().
triangulateio_exists()
template<class ELEMENT >
bool oomph::TriangleMesh< ELEMENT >::triangulateio_exists () [inline]
Boolean defining if Triangulateio object has been built or not.
Definition at line 1147 of file meshes/triangle_mesh.h.
References oomph::TriangleMesh< ELEMENT >::Triangulateio_exists.
update_holes_information_helper()
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::update_holes_information_helper (Vector< TriangleMeshPolygon * > & polygons_pt, Vector< Vector< double > > & output_holes_coordinates) [protected]
Keeps those vertices that define a hole, those that are inside closed internal boundaries in the new polygons that define the domain. Delete those outside/inside the outer polygons (this is required since Triangle can not deal with vertices that define holes outside the new outer polygons of the domain)
Definition at line 10934 of file triangle_mesh.template.cc.
References oomph::FiniteElement::dim(), e, i, oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
update_triangulateio() [1/2]
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::update_triangulateio () [inline]
Update the triangulateio object to the current nodal positions.
Definition at line 980 of file meshes/triangle_mesh.h.
References oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::TriangulateIO::numberofpoints, oomph::TriangleMesh< ELEMENT >::Oomph_vertex_nodes_id, oomph::TriangulateIO::pointlist, and oomph::TriangleMeshBase::Triangulateio.
Referenced by oomph::TriangleMesh< ELEMENT >::update_triangulateio().
update_triangulateio() [2/2]
template<class ELEMENT >
void oomph::TriangleMesh< ELEMENT >::update_triangulateio (Vector< Vector< double > > & internal_point) [inline]
Update the TriangulateIO object to the current nodal position and the centre hole coordinates.
Definition at line 960 of file meshes/triangle_mesh.h.
References oomph::TriangulateIO::holelist, oomph::TriangulateIO::numberofholes, oomph::TriangleMeshBase::Triangulateio, and oomph::TriangleMesh< ELEMENT >::update_triangulateio().
Member Data Documentation
Boundary_marked_as_shared_boundary
template<class ELEMENT >
std::map<unsigned, std::vector<bool> > oomph::TriangleMesh< ELEMENT >::Boundary_marked_as_shared_boundary [protected]
Flag to indicate if an internal boundary will be used as shared boundary because there is overlapping of the internal boundary with the shared boundary.
Definition at line 1962 of file meshes/triangle_mesh.h.
Referenced by oomph::TriangleMesh< ELEMENT >::boundary_marked_as_shared_boundary().
Boundary_subpolylines
template<class ELEMENT >
std::map<unsigned, Vector<TriangleMeshPolyLine*> > oomph::TriangleMesh< ELEMENT >::Boundary_subpolylines [protected]
The polylines that will temporary represent the boundary that was splitted in the distribution process. Used to ease the sending of info. to Triangle during the adaptation process.
Definition at line 1956 of file meshes/triangle_mesh.h.
Referenced by oomph::TriangleMesh< ELEMENT >::boundary_subpolylines(), and oomph::TriangleMesh< ELEMENT >::nboundary_subpolylines().
Boundary_was_splitted
template<class ELEMENT >
std::map<unsigned, bool> oomph::TriangleMesh< ELEMENT >::Boundary_was_splitted [protected]
Flag to indicate if a polyline has been splitted during the distribution process, the boundary id of the polyline is used to indicate if spplited.
Definition at line 1951 of file meshes/triangle_mesh.h.
Referenced by oomph::TriangleMesh< ELEMENT >::boundary_was_splitted().
Face_index_at_shared_boundary
template<class ELEMENT >
std::map<unsigned, Vector<int> > oomph::TriangleMesh< ELEMENT >::Face_index_at_shared_boundary [protected]
For the e-th finite element on shared boundary b, this is the index of the face that lies along that boundary.
Definition at line 1942 of file meshes/triangle_mesh.h.
Referenced by oomph::TriangleMesh< ELEMENT >::add_face_index_at_shared_boundary(), oomph::TriangleMesh< ELEMENT >::face_index_at_shared_boundary(), and oomph::TriangleMesh< ELEMENT >::flush_face_index_at_shared_boundary().
Final_shared_boundary_id
template<class ELEMENT >
unsigned oomph::TriangleMesh< ELEMENT >::Final_shared_boundary_id [protected]
The final boundary id for shared boundaries.
Definition at line 1908 of file meshes/triangle_mesh.h.
Referenced by oomph::TriangleMesh< ELEMENT >::final_shared_boundary_id().
First_time_compute_holes_left_by_halo_elements
template<class ELEMENT >
bool oomph::TriangleMesh< ELEMENT >::First_time_compute_holes_left_by_halo_elements [protected]
Flag to know if it is the first time we are going to compute the holes left by the halo elements.
Definition at line 1994 of file meshes/triangle_mesh.h.
Referenced by oomph::TriangleMesh< ELEMENT >::TriangleMesh(), oomph::TriangleMesh< ELEMENT >::TriangleMesh(), oomph::TriangleMesh< ELEMENT >::TriangleMesh(), and oomph::TriangleMesh< ELEMENT >::TriangleMesh().
Initial_shared_boundary_id
template<class ELEMENT >
unsigned oomph::TriangleMesh< ELEMENT >::Initial_shared_boundary_id [protected]
The initial boundary id for shared boundaries.
Definition at line 1905 of file meshes/triangle_mesh.h.
Referenced by oomph::TriangleMesh< ELEMENT >::initial_shared_boundary_id().
Oomph_vertex_nodes_id
template<class ELEMENT >
Vector<unsigned> oomph::TriangleMesh< ELEMENT >::Oomph_vertex_nodes_id [protected]
Vector storing oomph-lib node number for all vertex nodes in the TriangulateIO representation of the mesh.
Definition at line 1338 of file meshes/triangle_mesh.h.
Referenced by oomph::TriangleMesh< ELEMENT >::oomph_vertex_nodes_id(), and oomph::TriangleMesh< ELEMENT >::update_triangulateio().
Original_extra_holes_coordinates
template<class ELEMENT >
Vector<Vector<double> > oomph::TriangleMesh< ELEMENT >::Original_extra_holes_coordinates [protected]
Backup the original extra holes coordinates.
Definition at line 1997 of file meshes/triangle_mesh.h.
Regions_areas
template<class ELEMENT >
std::map<unsigned, double> oomph::TriangleMesh< ELEMENT >::Regions_areas [protected]
Target areas for regions; defaults to 0.0 which (luckily) implies "no specific target area" for triangle!
Definition at line 1171 of file meshes/triangle_mesh.h.
Referenced by oomph::TriangleMesh< ELEMENT >::TriangleMesh().
Shared_boundaries_ids
template<class ELEMENT >
Vector<Vector<Vector<unsigned> > > oomph::TriangleMesh< ELEMENT >::Shared_boundaries_ids [protected]
Stores the boundaries ids created by the interaction of two processors Shared_boundaries_ids[iproc][jproc] = Vector of shared boundaries ids "iproc" processor shares boundaries with "jproc" processor.
Definition at line 1914 of file meshes/triangle_mesh.h.
Referenced by oomph::TriangleMesh< ELEMENT >::nshared_boundaries(), oomph::TriangleMesh< ELEMENT >::shared_boundaries_ids(), oomph::TriangleMesh< ELEMENT >::shared_boundaries_ids(), oomph::TriangleMesh< ELEMENT >::shared_boundaries_ids(), oomph::TriangleMesh< ELEMENT >::shared_boundaries_ids(), oomph::TriangleMesh< ELEMENT >::shared_boundaries_ids(), oomph::TriangleMesh< ELEMENT >::shared_boundaries_ids(), and oomph::TriangleMesh< ELEMENT >::shared_boundaries_ids().
Shared_boundary_element_pt
template<class ELEMENT >
std::map<unsigned, Vector<FiniteElement*> > oomph::TriangleMesh< ELEMENT >::Shared_boundary_element_pt [protected]
Stores the boundary elements adjacent to the shared boundaries, these elements are a subset of the halo and haloed elements.
Definition at line 1938 of file meshes/triangle_mesh.h.
Referenced by oomph::TriangleMesh< ELEMENT >::add_shared_boundary_element(), oomph::TriangleMesh< ELEMENT >::flush_shared_boundary_element(), oomph::TriangleMesh< ELEMENT >::flush_shared_boundary_element(), oomph::TriangleMesh< ELEMENT >::nshared_boundaries(), oomph::TriangleMesh< ELEMENT >::nshared_boundary_element(), and oomph::TriangleMesh< ELEMENT >::shared_boundary_element_pt().
Shared_boundary_from_processors
template<class ELEMENT >
std::map<unsigned, Vector<unsigned> > oomph::TriangleMesh< ELEMENT >::Shared_boundary_from_processors [protected]
Stores the processors involved in the generation of a shared boundary, in 2D two processors give rise to the creation of a shared boundary.
Definition at line 1919 of file meshes/triangle_mesh.h.
Referenced by oomph::TriangleMesh< ELEMENT >::shared_boundary_from_processors(), and oomph::TriangleMesh< ELEMENT >::shared_boundary_from_processors().
Shared_boundary_node_pt
template<class ELEMENT >
std::map<unsigned, Vector<Node*> > oomph::TriangleMesh< ELEMENT >::Shared_boundary_node_pt [protected]
Stores the boundary nodes adjacent to the shared boundaries, these nodes are a subset of the halo and haloed nodes.
Definition at line 1946 of file meshes/triangle_mesh.h.
Referenced by oomph::TriangleMesh< ELEMENT >::add_shared_boundary_node(), oomph::TriangleMesh< ELEMENT >::flush_shared_boundary_node(), oomph::TriangleMesh< ELEMENT >::flush_shared_boundary_node(), oomph::TriangleMesh< ELEMENT >::is_node_on_shared_boundary(), oomph::TriangleMesh< ELEMENT >::nshared_boundary_node(), and oomph::TriangleMesh< ELEMENT >::shared_boundary_node_pt().
Shared_boundary_overlaps_internal_boundary
template<class ELEMENT >
std::map<unsigned, unsigned> oomph::TriangleMesh< ELEMENT >::Shared_boundary_overlaps_internal_boundary [protected]
Stores information about those shared boundaries that lie over or over a segment of an internal boundary (only used when using internal boundaries in the domain)
Definition at line 1924 of file meshes/triangle_mesh.h.
Referenced by oomph::TriangleMesh< ELEMENT >::get_shared_boundaries_overlapping_internal_boundary(), oomph::TriangleMesh< ELEMENT >::nshared_boundary_overlaps_internal_boundary(), oomph::TriangleMesh< ELEMENT >::shared_boundary_overlapping_internal_boundary(), oomph::TriangleMesh< ELEMENT >::shared_boundary_overlaps_internal_boundary(), and oomph::TriangleMesh< ELEMENT >::shared_boundary_overlaps_internal_boundary().
Shared_boundary_polyline_pt
template<class ELEMENT >
Vector<Vector<Vector<TriangleMeshPolyLine*> > > oomph::TriangleMesh< ELEMENT >::Shared_boundary_polyline_pt [protected]
Stores the polyline representation of the shared boundaries Shared_boundary_polyline_pt[iproc][ncurve][npolyline] = polyline_pt.
Definition at line 1928 of file meshes/triangle_mesh.h.
Referenced by oomph::TriangleMesh< ELEMENT >::flush_shared_boundary_polyline_pt(), oomph::TriangleMesh< ELEMENT >::nshared_boundary_curves(), oomph::TriangleMesh< ELEMENT >::nshared_boundary_polyline(), oomph::TriangleMesh< ELEMENT >::shared_boundary_polyline_pt(), and oomph::TriangleMesh< ELEMENT >::shared_boundary_polyline_pt().
Time_stepper_pt
template<class ELEMENT >
TimeStepper* oomph::TriangleMesh< ELEMENT >::Time_stepper_pt
Timestepper used to build elements.
Definition at line 1162 of file meshes/triangle_mesh.h.
Referenced by oomph::TriangleMesh< ELEMENT >::generic_constructor(), oomph::TriangleMesh< ELEMENT >::remesh_from_internal_triangulateio(), oomph::TriangleMesh< ELEMENT >::set_mesh_level_time_stepper(), oomph::TriangleMesh< ELEMENT >::TriangleMesh(), oomph::TriangleMesh< ELEMENT >::TriangleMesh(), and oomph::TriangleMesh< ELEMENT >::TriangleMesh().
Tmp_mesh_pt
template<class ELEMENT >
TriangleScaffoldMesh* oomph::TriangleMesh< ELEMENT >::Tmp_mesh_pt [protected]
Temporary scaffold mesh.
Definition at line 1334 of file meshes/triangle_mesh.h.
Referenced by oomph::TriangleMesh< ELEMENT >::generic_constructor(), oomph::TriangleMesh< ELEMENT >::remesh_from_internal_triangulateio(), oomph::TriangleMesh< ELEMENT >::TriangleMesh(), and oomph::TriangleMesh< ELEMENT >::TriangleMesh().
Triangulateio_exists
template<class ELEMENT >
bool oomph::TriangleMesh< ELEMENT >::Triangulateio_exists [protected]
Boolean defining if Triangulateio object has been built or not.
Definition at line 1329 of file meshes/triangle_mesh.h.
Referenced by oomph::TriangleMesh< ELEMENT >::generic_constructor(), oomph::TriangleMesh< ELEMENT >::remesh_from_internal_triangulateio(), oomph::TriangleMesh< ELEMENT >::TriangleMesh(), oomph::TriangleMesh< ELEMENT >::TriangleMesh(), oomph::TriangleMesh< ELEMENT >::triangulateio_exists(), and oomph::TriangleMesh< ELEMENT >::~TriangleMesh().
Use_attributes
template<class ELEMENT >
bool oomph::TriangleMesh< ELEMENT >::Use_attributes
Boolean flag to indicate whether to use attributes or not (required for multidomain meshes)
Definition at line 1166 of file meshes/triangle_mesh.h.
Referenced by oomph::TriangleMesh< ELEMENT >::generic_constructor(), oomph::TriangleMesh< ELEMENT >::remesh_from_internal_triangulateio(), oomph::TriangleMesh< ELEMENT >::TriangleMesh(), and oomph::TriangleMesh< ELEMENT >::TriangleMesh().
The documentation for this class was generated from the following files:
meshes/triangle_mesh.h
triangle_mesh.template.cc