oomph::PRefineableQLinearElasticityElement< DIM > Class Template Reference
p-refineable version of 2D QLinearElasticityElement elements
#include <refineable_linear_elasticity_elements.h>
Public Member Functions
PRefineableQLinearElasticityElement ()
Constructor, simply call the other constructors.
~PRefineableQLinearElasticityElement ()
Destructor (to avoid memory leaks)
PRefineableQLinearElasticityElement (const PRefineableQLinearElasticityElement< DIM > &dummy)=delete
Broken copy constructor.
void further_build ()
Broken assignment operator.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: 1.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation:
void compute_energy_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_grad_pt, double &error, double &norm)
Get error against and norm of exact solution.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::PRefineableQLinearElasticityElement< DIM >
p-refineable version of 2D QLinearElasticityElement elements
Definition at line 239 of file refineable_linear_elasticity_elements.h.
Constructor & Destructor Documentation
PRefineableQLinearElasticityElement() [1/2]
template<unsigned DIM>
oomph::PRefineableQLinearElasticityElement< DIM >::PRefineableQLinearElasticityElement () [inline]
Constructor, simply call the other constructors.
Definition at line 246 of file refineable_linear_elasticity_elements.h.
References oomph::FiniteElement::set_integration_scheme().
 PRefineableQLinearElasticityElement()
template<unsigned DIM>
oomph::PRefineableQLinearElasticityElement< DIM >::~PRefineableQLinearElasticityElement () [inline]
Destructor (to avoid memory leaks)
Definition at line 259 of file refineable_linear_elasticity_elements.h.
References oomph::FiniteElement::integral_pt().
PRefineableQLinearElasticityElement() [2/2]
template<unsigned DIM>
oomph::PRefineableQLinearElasticityElement< DIM >::PRefineableQLinearElasticityElement (const PRefineableQLinearElasticityElement< DIM > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
compute_energy_error()
template<unsigned DIM>
void oomph::PRefineableQLinearElasticityElement< DIM >::compute_energy_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_grad_pt, double & error, double & norm)
Get error against and norm of exact solution.
Definition at line 297 of file refineable_linear_elasticity_elements.cc.
References i, s, oomph::W, and oomph::x.
further_build()
template<unsigned DIM>
void oomph::PRefineableQLinearElasticityElement< DIM >::further_build [virtual]
Broken assignment operator.
Reimplemented from oomph::RefineableLinearElasticityEquations< DIM >.
Definition at line 383 of file refineable_linear_elasticity_elements.cc.
References oomph::RefineableLinearElasticityEquations< DIM >::further_build().
ncont_interpolated_values()
template<unsigned DIM>
unsigned oomph::PRefineableQLinearElasticityElement< DIM >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values: 1.
Reimplemented from oomph::RefineableLinearElasticityEquations< DIM >.
Definition at line 276 of file refineable_linear_elasticity_elements.h.
nrecovery_order()
template<unsigned DIM>
unsigned oomph::PRefineableQLinearElasticityElement< DIM >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation:
Same order as shape functions.
Constant recovery order, since recovery order of the first element is used for the whole mesh.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 302 of file refineable_linear_elasticity_elements.h.
nvertex_node()
template<unsigned DIM>
unsigned oomph::PRefineableQLinearElasticityElement< DIM >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 282 of file refineable_linear_elasticity_elements.h.
References oomph::FiniteElement::nvertex_node().
vertex_node_pt()
template<unsigned DIM>
Node * oomph::PRefineableQLinearElasticityElement< DIM >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 288 of file refineable_linear_elasticity_elements.h.
References oomph::FiniteElement::vertex_node_pt().
The documentation for this class was generated from the following files:
refineable_linear_elasticity_elements.h
refineable_linear_elasticity_elements.cc