oomph::TimeHarmonicLinearElasticityEquationsBase< DIM > Class Template Reference
A base class for elements that solve the equations of time-harmonic linear elasticity in Cartesian coordinates. Combines a few generic functions that are shared by TimeHarmonicLinearElasticityEquations and TimeHarmonicLinearElasticityEquationsWithPressure (Note: The latter don't exist yet but will be written as soon as somebody needs them...)
#include <time_harmonic_linear_elasticity_elements.h>
Public Types
typedef void(* BodyForceFctPt) (const double &t, const Vector< double > &x, Vector< std::complex< double >> &b)
Function pointer to function that specifies the body force as a function of the Cartesian coordinates and time FCT(t,x,b) -- x and b are Vectors!
Public Member Functions
virtual std::complex< unsigned > u_index_time_harmonic_linear_elasticity (const unsigned i) const
Return the index at which the i-th real or imag unknown displacement component is stored. The default value is appropriate for single-physics problems:
void interpolated_u_time_harmonic_linear_elasticity (const Vector< double > &s, Vector< std::complex< double >> &disp) const
Compute vector of FE interpolated displacement u at local coordinate s.
std::complex< double > interpolated_u_time_harmonic_linear_elasticity (const Vector< double > &s, const unsigned &i) const
Return FE interpolated displacement u[i] at local coordinate s.
TimeHarmonicLinearElasticityEquationsBase ()
Constructor: Set null pointers for constitutive law and for isotropic growth function. Set physical parameter values to default values, and set body force to zero.
TimeHarmonicElasticityTensor *& elasticity_tensor_pt ()
Return the pointer to the elasticity_tensor.
double E (const unsigned &i, const unsigned &j, const unsigned &k, const unsigned &l) const
Access function to the entries in the elasticity tensor.
const double & omega_sq () const
Access function for square of non-dim frequency.
double *& omega_sq_pt ()
Access function for square of non-dim frequency.
BodyForceFctPt & body_force_fct_pt ()
Access function: Pointer to body force function.
BodyForceFctPt body_force_fct_pt () const
Access function: Pointer to body force function (const version)
virtual void get_stress (const Vector< double > &s, DenseMatrix< std::complex< double >> &sigma) const =0
Return the Cauchy stress tensor, as calculated from the elasticity tensor at specified local coordinate Virtual so separaete versions can (and must!) be provided for displacement and pressure-displacement formulations.
void get_strain (const Vector< double > &s, DenseMatrix< std::complex< double >> &strain) const
Return the strain tensor.
void body_force (const Vector< double > &x, Vector< std::complex< double >> &b) const
Evaluate body force at Eulerian coordinate x at present time (returns zero vector if no body force function pointer has been set)
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into: for now lump them all into one DOF. Can be adjusted later.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Protected Attributes
TimeHarmonicElasticityTensor * Elasticity_tensor_pt
Pointer to the elasticity tensor.
double * Omega_sq_pt
Square of nondim frequency.
BodyForceFctPt Body_force_fct_pt
Pointer to body force function.
Static Protected Attributes
static double Default_omega_sq_value
Static default value for square of frequency.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >
A base class for elements that solve the equations of time-harmonic linear elasticity in Cartesian coordinates. Combines a few generic functions that are shared by TimeHarmonicLinearElasticityEquations and TimeHarmonicLinearElasticityEquationsWithPressure (Note: The latter don't exist yet but will be written as soon as somebody needs them...)
Definition at line 63 of file time_harmonic_linear_elasticity_elements.h.
Member Typedef Documentation
BodyForceFctPt
template<unsigned DIM>
typedef void(* oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::BodyForceFctPt) (const double &t, const Vector< double > &x, Vector< std::complex< double >> &b)
Function pointer to function that specifies the body force as a function of the Cartesian coordinates and time FCT(t,x,b) -- x and b are Vectors!
Definition at line 146 of file time_harmonic_linear_elasticity_elements.h.
Constructor & Destructor Documentation
TimeHarmonicLinearElasticityEquationsBase()
template<unsigned DIM>
oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::TimeHarmonicLinearElasticityEquationsBase () [inline]
Constructor: Set null pointers for constitutive law and for isotropic growth function. Set physical parameter values to default values, and set body force to zero.
Definition at line 153 of file time_harmonic_linear_elasticity_elements.h.
Member Function Documentation
body_force()
template<unsigned DIM>
void oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::body_force (const Vector< double > & x, Vector< std::complex< double >> & b) const [inline]
Evaluate body force at Eulerian coordinate x at present time (returns zero vector if no body force function pointer has been set)
Definition at line 212 of file time_harmonic_linear_elasticity_elements.h.
References oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::Body_force_fct_pt, oomph::FiniteElement::dim(), i, oomph::FiniteElement::node_pt(), oomph::Time::time(), oomph::TimeStepper::time_pt(), and oomph::Data::time_stepper_pt().
body_force_fct_pt() [1/2]
template<unsigned DIM>
BodyForceFctPt& oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::body_force_fct_pt () [inline]
Access function: Pointer to body force function.
Definition at line 188 of file time_harmonic_linear_elasticity_elements.h.
References oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::Body_force_fct_pt.
Referenced by oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::further_build().
body_force_fct_pt() [2/2]
template<unsigned DIM>
BodyForceFctPt oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::body_force_fct_pt () const [inline]
Access function: Pointer to body force function (const version)
Definition at line 194 of file time_harmonic_linear_elasticity_elements.h.
References oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::Body_force_fct_pt.
E()
template<unsigned DIM>
double oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::E (const unsigned & i, const unsigned & j, const unsigned & k, const unsigned & l) const [inline]
Access function to the entries in the elasticity tensor.
Definition at line 167 of file time_harmonic_linear_elasticity_elements.h.
References oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::Elasticity_tensor_pt, and i.
elasticity_tensor_pt()
template<unsigned DIM>
TimeHarmonicElasticityTensor*& oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::elasticity_tensor_pt () [inline]
Return the pointer to the elasticity_tensor.
Definition at line 161 of file time_harmonic_linear_elasticity_elements.h.
References oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::Elasticity_tensor_pt.
Referenced by oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::further_build().
get_dof_numbers_for_unknowns()
template<unsigned DIM>
void oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> & dof_lookup_list) const [inline], [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Reimplemented from oomph::GeneralisedElement.
Definition at line 251 of file time_harmonic_linear_elasticity_elements.h.
References oomph::GeneralisedElement::eqn_number(), i, oomph::FiniteElement::nnode(), and oomph::FiniteElement::nodal_local_eqn().
get_strain()
template<unsigned DIM>
void oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::get_strain (const Vector< double > & s, DenseMatrix< std::complex< double >> & strain) const
Return the strain tensor.
/////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////
Compute the strain tensor at local coordinate s Now fill in the entries of the strain tensor
Definition at line 49 of file time_harmonic_linear_elasticity_elements.cc.
References i, and s.
Referenced by oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::get_Z2_flux(), and oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >::get_Z2_flux().
get_stress()
template<unsigned DIM>
virtual void oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::get_stress (const Vector< double > & s, DenseMatrix< std::complex< double >> & sigma) const [pure virtual]
Return the Cauchy stress tensor, as calculated from the elasticity tensor at specified local coordinate Virtual so separaete versions can (and must!) be provided for displacement and pressure-displacement formulations.
Implemented in oomph::TimeHarmonicLinearElasticityEquations< DIM >.
interpolated_u_time_harmonic_linear_elasticity() [1/2]
template<unsigned DIM>
std::complex<double> oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::interpolated_u_time_harmonic_linear_elasticity (const Vector< double > & s, const unsigned & i) const [inline]
Return FE interpolated displacement u[i] at local coordinate s.
Definition at line 110 of file time_harmonic_linear_elasticity_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::u_index_time_harmonic_linear_elasticity().
interpolated_u_time_harmonic_linear_elasticity() [2/2]
template<unsigned DIM>
void oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::interpolated_u_time_harmonic_linear_elasticity (const Vector< double > & s, Vector< std::complex< double >> & disp) const [inline]
Compute vector of FE interpolated displacement u at local coordinate s.
Definition at line 76 of file time_harmonic_linear_elasticity_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::u_index_time_harmonic_linear_elasticity().
ndof_types()
template<unsigned DIM>
unsigned oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::ndof_types () const [inline], [virtual]
The number of `DOF types` that degrees of freedom in this element are sub-divided into: for now lump them all into one DOF. Can be adjusted later.
Reimplemented from oomph::GeneralisedElement.
Definition at line 240 of file time_harmonic_linear_elasticity_elements.h.
omega_sq()
template<unsigned DIM>
const double& oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::omega_sq () const [inline]
Access function for square of non-dim frequency.
Definition at line 176 of file time_harmonic_linear_elasticity_elements.h.
References oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::Omega_sq_pt.
omega_sq_pt()
template<unsigned DIM>
double*& oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::omega_sq_pt () [inline]
Access function for square of non-dim frequency.
Definition at line 182 of file time_harmonic_linear_elasticity_elements.h.
References oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::Omega_sq_pt.
Referenced by oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::further_build().
u_index_time_harmonic_linear_elasticity()
template<unsigned DIM>
virtual std::complex<unsigned> oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::u_index_time_harmonic_linear_elasticity (const unsigned i) const [inline], [virtual]
Return the index at which the i-th real or imag unknown displacement component is stored. The default value is appropriate for single-physics problems:
Definition at line 69 of file time_harmonic_linear_elasticity_elements.h.
References i.
Referenced by oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::get_interpolated_values(), and oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::interpolated_u_time_harmonic_linear_elasticity().
Member Data Documentation
Body_force_fct_pt
template<unsigned DIM>
BodyForceFctPt oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::Body_force_fct_pt [protected]
Pointer to body force function.
Definition at line 297 of file time_harmonic_linear_elasticity_elements.h.
Referenced by oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::body_force(), oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::body_force_fct_pt(), and oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::further_build().
Default_omega_sq_value
template<unsigned DIM>
double oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::Default_omega_sq_value [static], [protected]
Initial value:
=
      1.0
Static default value for square of frequency.
Definition at line 300 of file time_harmonic_linear_elasticity_elements.h.
Elasticity_tensor_pt
template<unsigned DIM>
TimeHarmonicElasticityTensor* oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::Elasticity_tensor_pt [protected]
Pointer to the elasticity tensor.
Definition at line 291 of file time_harmonic_linear_elasticity_elements.h.
Referenced by oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::E(), oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::elasticity_tensor_pt(), and oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::further_build().
Omega_sq_pt
template<unsigned DIM>
double* oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::Omega_sq_pt [protected]
Square of nondim frequency.
Definition at line 294 of file time_harmonic_linear_elasticity_elements.h.
Referenced by oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::further_build(), oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::omega_sq(), and oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::omega_sq_pt().
The documentation for this class was generated from the following files:
time_harmonic_linear_elasticity_elements.h
time_harmonic_linear_elasticity_elements.cc