oomph::PMLHelmholtzFluxElement< ELEMENT > Class Template Reference
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
#include <pml_helmholtz_flux_elements.h>
Public Types
typedef void(* PMLHelmholtzPrescribedFluxFctPt) (const Vector< double > &x, std::complex< double > &flux)
Function pointer to the prescribed-flux function fct(x,f(x)) -- x is a Vector and the flux is a complex. NOTE THAT f(x) represents c^2 du/dn!
Public Member Functions
PMLHelmholtzFluxElement (FiniteElement *const &bulk_el_pt, const int &face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to which the element is attached.
PMLHelmholtzFluxElement ()
Broken empty constructor.
PMLHelmholtzFluxElement (const PMLHelmholtzFluxElement &dummy)=delete
Broken copy constructor.
PMLHelmholtzPrescribedFluxFctPt & flux_fct_pt ()
Broken assignment operator.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and its Jacobian matrix.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
void output (std::ostream &outfile)
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
void output (std::ostream &outfile, const unsigned &n_plot)
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
void output (FILE *file_pt)
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
virtual std::complex< unsigned > u_index_helmholtz () const
Return the index at which the unknown value is stored.
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into: real and imaginary part.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Real=0; Imag=1.
Protected Member Functions
double shape_and_test (const Vector< double > &s, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
void get_flux (const Vector< double > &x, std::complex< double > &flux)
Function to calculate the prescribed flux at a given spatial position.
virtual void fill_in_generic_residual_contribution_helmholtz_flux (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the contribution to the Jacobian as well.
Protected Attributes
std::complex< unsigned > U_index_helmholtz
The index at which the real and imag part of the unknown is stored at the nodes.
PMLHelmholtzPrescribedFluxFctPt Flux_fct_pt
Function pointer to the (global) prescribed-flux function.
unsigned Dim
The spatial dimension of the problem.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::PMLHelmholtzFluxElement< ELEMENT >
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
A class for elements that allow the imposition of an applied flux on the boundaries of PMLHelmholtz elements. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
Definition at line 550 of file pml_helmholtz_flux_elements.h.
Member Typedef Documentation
PMLHelmholtzPrescribedFluxFctPt
template<class ELEMENT >
typedef void(* oomph::PMLHelmholtzFluxElement< ELEMENT >::PMLHelmholtzPrescribedFluxFctPt) (const Vector< double > &x, std::complex< double > &flux)
Function pointer to the prescribed-flux function fct(x,f(x)) -- x is a Vector and the flux is a complex. NOTE THAT f(x) represents c^2 du/dn!
Definition at line 557 of file pml_helmholtz_flux_elements.h.
Constructor & Destructor Documentation
PMLHelmholtzFluxElement() [1/3]
template<class ELEMENT >
oomph::PMLHelmholtzFluxElement< ELEMENT >::PMLHelmholtzFluxElement (FiniteElement *const & bulk_el_pt, const int & face_index)
Constructor, takes the pointer to the `bulk` element and the index of the face to which the element is attached.
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
Constructor, takes the pointer to the `bulk` element, the index of the fixed local coordinate and its value represented by an integer (+/- 1), indicating that the face is located at the max. or min. value of the `fixed` local coordinate in the bulk element.
Definition at line 821 of file pml_helmholtz_flux_elements.h.
References oomph::FiniteElement::build_face_element(), oomph::PMLHelmholtzFluxElement< ELEMENT >::Dim, oomph::FaceElement::face_index(), oomph::PMLHelmholtzFluxElement< ELEMENT >::Flux_fct_pt, oomph::FiniteElement::has_hanging_nodes(), oomph::FiniteElement::node_pt(), oomph::Global_string_for_annotation::string(), oomph::PMLHelmholtzEquations< DIM >::u_index_helmholtz(), and oomph::PMLHelmholtzFluxElement< ELEMENT >::U_index_helmholtz.
PMLHelmholtzFluxElement() [2/3]
template<class ELEMENT >
oomph::PMLHelmholtzFluxElement< ELEMENT >::PMLHelmholtzFluxElement () [inline]
Broken empty constructor.
Definition at line 566 of file pml_helmholtz_flux_elements.h.
PMLHelmholtzFluxElement() [3/3]
template<class ELEMENT >
oomph::PMLHelmholtzFluxElement< ELEMENT >::PMLHelmholtzFluxElement (const PMLHelmholtzFluxElement< ELEMENT > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::PMLHelmholtzFluxElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and its Jacobian matrix.
Reimplemented from oomph::FiniteElement.
Definition at line 600 of file pml_helmholtz_flux_elements.h.
References oomph::PMLHelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_flux(), and oomph::FiniteElement::jacobian.
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::PMLHelmholtzFluxElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector.
Reimplemented from oomph::GeneralisedElement.
Definition at line 589 of file pml_helmholtz_flux_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::PMLHelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_flux().
fill_in_generic_residual_contribution_helmholtz_flux()
template<class ELEMENT >
void oomph::PMLHelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_flux (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected], [virtual]
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the contribution to the Jacobian as well.
Compute the element's residual vector and the (zero) Jacobian matrix.
Definition at line 972 of file pml_helmholtz_flux_elements.h.
References oomph::Multi_domain_functions::Dim, i, s, and oomph::W.
Referenced by oomph::PMLHelmholtzFluxElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::PMLHelmholtzFluxElement< ELEMENT >::fill_in_contribution_to_residuals().
flux_fct_pt()
template<class ELEMENT >
PMLHelmholtzPrescribedFluxFctPt & oomph::PMLHelmholtzFluxElement< ELEMENT >::flux_fct_pt () [inline]
Broken assignment operator.
Access function for the prescribed-flux function pointer
Definition at line 582 of file pml_helmholtz_flux_elements.h.
References oomph::PMLHelmholtzFluxElement< ELEMENT >::Flux_fct_pt.
get_dof_numbers_for_unknowns()
template<class ELEMENT >
void oomph::PMLHelmholtzFluxElement< ELEMENT >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [inline], [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Real=0; Imag=1.
Reimplemented from oomph::GeneralisedElement.
Definition at line 675 of file pml_helmholtz_flux_elements.h.
References oomph::GeneralisedElement::eqn_number(), oomph::GeneralisedElement::local_eqn_number(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), and oomph::PMLHelmholtzFluxElement< ELEMENT >::U_index_helmholtz.
get_flux()
template<class ELEMENT >
void oomph::PMLHelmholtzFluxElement< ELEMENT >::get_flux (const Vector< double > & x, std::complex< double > & flux) [inline], [protected]
Function to calculate the prescribed flux at a given spatial position.
Definition at line 772 of file pml_helmholtz_flux_elements.h.
References oomph::PMLHelmholtzFluxElement< ELEMENT >::Flux_fct_pt, and oomph::x.
ndof_types()
template<class ELEMENT >
unsigned oomph::PMLHelmholtzFluxElement< ELEMENT >::ndof_types () const [inline], [virtual]
The number of `DOF types` that degrees of freedom in this element are sub-divided into: real and imaginary part.
Reimplemented from oomph::GeneralisedElement.
Definition at line 664 of file pml_helmholtz_flux_elements.h.
output() [1/4]
template<class ELEMENT >
void oomph::PMLHelmholtzFluxElement< ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 639 of file pml_helmholtz_flux_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<class ELEMENT >
void oomph::PMLHelmholtzFluxElement< ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 647 of file pml_helmholtz_flux_elements.h.
References oomph::FiniteElement::output().
output() [3/4]
template<class ELEMENT >
void oomph::PMLHelmholtzFluxElement< ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 624 of file pml_helmholtz_flux_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<class ELEMENT >
void oomph::PMLHelmholtzFluxElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function -- forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
Definition at line 631 of file pml_helmholtz_flux_elements.h.
References oomph::FiniteElement::output().
shape_and_test()
template<class ELEMENT >
double oomph::PMLHelmholtzFluxElement< ELEMENT >::shape_and_test (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 725 of file pml_helmholtz_flux_elements.h.
References i, oomph::FaceElement::J_eulerian(), oomph::FiniteElement::nnode(), s, and oomph::FiniteElement::shape().
shape_and_test_at_knot()
template<class ELEMENT >
double oomph::PMLHelmholtzFluxElement< ELEMENT >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 749 of file pml_helmholtz_flux_elements.h.
References i, oomph::FaceElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape_at_knot().
u_index_helmholtz()
template<class ELEMENT >
virtual std::complex< unsigned > oomph::PMLHelmholtzFluxElement< ELEMENT >::u_index_helmholtz () const [inline], [virtual]
Return the index at which the unknown value is stored.
Definition at line 655 of file pml_helmholtz_flux_elements.h.
References oomph::PMLHelmholtzFluxElement< ELEMENT >::U_index_helmholtz.
zeta_nodal()
template<class ELEMENT >
double oomph::PMLHelmholtzFluxElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const [inline], [virtual]
Specify the value of nodal zeta from the face geometry The `global` intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Reimplemented from oomph::FaceElement.
Definition at line 614 of file pml_helmholtz_flux_elements.h.
References i, and oomph::FaceElement::zeta_nodal().
Member Data Documentation
Dim
template<class ELEMENT >
unsigned oomph::PMLHelmholtzFluxElement< ELEMENT >::Dim [protected]
The spatial dimension of the problem.
Definition at line 805 of file pml_helmholtz_flux_elements.h.
Referenced by oomph::PMLHelmholtzFluxElement< ELEMENT >::PMLHelmholtzFluxElement().
Flux_fct_pt
template<class ELEMENT >
PMLHelmholtzPrescribedFluxFctPt oomph::PMLHelmholtzFluxElement< ELEMENT >::Flux_fct_pt [protected]
Function pointer to the (global) prescribed-flux function.
Definition at line 802 of file pml_helmholtz_flux_elements.h.
Referenced by oomph::PMLHelmholtzFluxElement< ELEMENT >::flux_fct_pt(), oomph::PMLHelmholtzFluxElement< ELEMENT >::get_flux(), and oomph::PMLHelmholtzFluxElement< ELEMENT >::PMLHelmholtzFluxElement().
U_index_helmholtz
template<class ELEMENT >
std::complex<unsigned> oomph::PMLHelmholtzFluxElement< ELEMENT >::U_index_helmholtz [protected]
The index at which the real and imag part of the unknown is stored at the nodes.
Definition at line 789 of file pml_helmholtz_flux_elements.h.
Referenced by oomph::PMLHelmholtzFluxElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::PMLHelmholtzFluxElement< ELEMENT >::PMLHelmholtzFluxElement(), and oomph::PMLHelmholtzFluxElement< ELEMENT >::u_index_helmholtz().
The documentation for this class was generated from the following file:
pml_helmholtz_flux_elements.h