oomph::StorableShapeSolidElement< ELEMENT > Class Template Reference
#include <stored_shape_function_elements.h>
Public Member Functions
StorableShapeSolidElement ()
Constructor: Set defaults.
virtual ~StorableShapeSolidElement ()
Destructor to clean up any allocated memory.
StorableShapeSolidElement (const StorableShapeSolidElement &)
Broken copy constructor.
void operator= (const StorableShapeSolidElement &)
Broken assignment operator.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::StorableShapeSolidElement< ELEMENT >
Templated wrapper that attaches the ability to store the shape functions and their derivatives w.r.t. to the local and global (Eulerian) coordinates at the integration points to the SolidFiniteElement specified by the template parameter.
Definition at line 608 of file stored_shape_function_elements.h.
Constructor & Destructor Documentation
StorableShapeSolidElement() [1/2]
template<class ELEMENT >
oomph::StorableShapeSolidElement< ELEMENT >::StorableShapeSolidElement () [inline]
Constructor: Set defaults.
Definition at line 614 of file stored_shape_function_elements.h.
References oomph::FiniteElement::integral_pt(), and oomph::StorableShapeSolidElementBase::set_integration_scheme().
 StorableShapeSolidElement()
template<class ELEMENT >
virtual oomph::StorableShapeSolidElement< ELEMENT >::~StorableShapeSolidElement () [inline], [virtual]
Destructor to clean up any allocated memory.
Definition at line 623 of file stored_shape_function_elements.h.
StorableShapeSolidElement() [2/2]
template<class ELEMENT >
oomph::StorableShapeSolidElement< ELEMENT >::StorableShapeSolidElement (const StorableShapeSolidElement< ELEMENT > &) [inline]
Broken copy constructor.
Definition at line 627 of file stored_shape_function_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
operator=()
template<class ELEMENT >
void oomph::StorableShapeSolidElement< ELEMENT >::operator= (const StorableShapeSolidElement< ELEMENT > &) [inline]
Broken assignment operator.
Definition at line 633 of file stored_shape_function_elements.h.
References oomph::BrokenCopy::broken_assign().
The documentation for this class was generated from the following file:
stored_shape_function_elements.h