oomph::NavierStokesFluxControlElement< ELEMENT > Class Template Reference
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
#include <navier_stokes_flux_control_elements.h>
Public Member Functions
NavierStokesFluxControlElement (FiniteElement *const &element_pt, const int &face_index, const bool &called_from_refineable_constructor=false)
Constructor, which takes a `bulk` element and face index.
~NavierStokesFluxControlElement ()
Destructor should not delete anything.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
This function returns just the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the Jacobian including the Jacobian contribution from the flux control master element with respect to dof in this element.
double get_volume_flux ()
Function to get the integral of the volume flux.
Protected Member Functions
virtual int u_local_eqn (const unsigned &n, const unsigned &i)
Access function that returns the local equation numbers for velocity components. u_local_eqn(n,i) = local equation number or < 0 if pinned. The default is to asssume that n is the local node number and the i-th velocity component is the i-th unknown stored at the node.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping.
void fill_in_generic_residual_contribution_fluid_traction (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
This function returns the residuals for the traction function flag=1(or 0): do (or don't) compute the Jacobian as well. This function also calculates the Jacobian contribution for the NetFluxControlElement.
Protected Attributes
unsigned Dim
The highest dimension of the problem.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::NavierStokesFluxControlElement< ELEMENT >
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
A class of element to impose an applied boundary pressure to Navier-Stokes elements to control to control a volume flux. A mesh of these elements are used in conjunction with a NetFluxControlElement. The template arguement ELEMENT is a Navier-Stokes `bulk` element.
Note: This element calculates Jacobian contributions for both itself and also for the NetFluxControlElement with respect to its unknowns.
Definition at line 348 of file navier_stokes_flux_control_elements.h.
Constructor & Destructor Documentation
NavierStokesFluxControlElement()
template<class ELEMENT >
oomph::NavierStokesFluxControlElement< ELEMENT >::NavierStokesFluxControlElement (FiniteElement *const & element_pt, const int & face_index, const bool & called_from_refineable_constructor = false) [inline]
Constructor, which takes a `bulk` element and face index.
Definition at line 354 of file navier_stokes_flux_control_elements.h.
References oomph::NavierStokesFluxControlElement< ELEMENT >::Dim, oomph::Node::ndim(), and oomph::FiniteElement::node_pt().
 NavierStokesFluxControlElement()
template<class ELEMENT >
oomph::NavierStokesFluxControlElement< ELEMENT >::~NavierStokesFluxControlElement () [inline]
Destructor should not delete anything.
Definition at line 393 of file navier_stokes_flux_control_elements.h.
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELEMENT >
void oomph::NavierStokesFluxControlElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
This function returns the residuals and the Jacobian including the Jacobian contribution from the flux control master element with respect to dof in this element.
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::RefineableNavierStokesFluxControlElement< ELEMENT >.
Definition at line 407 of file navier_stokes_flux_control_elements.h.
References oomph::NavierStokesFluxControlElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction().
fill_in_contribution_to_residuals()
template<class ELEMENT >
void oomph::NavierStokesFluxControlElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
This function returns just the residuals.
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::RefineableNavierStokesFluxControlElement< ELEMENT >.
Definition at line 396 of file navier_stokes_flux_control_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::NavierStokesFluxControlElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction().
fill_in_generic_residual_contribution_fluid_traction()
template<class ELEMENT >
void oomph::NavierStokesFluxControlElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [inline], [protected]
This function returns the residuals for the traction function flag=1(or 0): do (or don't) compute the Jacobian as well. This function also calculates the Jacobian contribution for the NetFluxControlElement.
Definition at line 456 of file navier_stokes_flux_control_elements.h.
References oomph::NavierStokesFluxControlElement< ELEMENT >::Dim, oomph::GeneralisedElement::external_data_pt(), oomph::GeneralisedElement::external_local_eqn(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), oomph::TemplateFreeNavierStokesFluxControlElementBase::pressure_data_id(), oomph::NavierStokesFluxControlElement< ELEMENT >::shape_and_test_at_knot(), oomph::NavierStokesFluxControlElement< ELEMENT >::u_local_eqn(), oomph::Data::value(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by oomph::NavierStokesFluxControlElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::NavierStokesFluxControlElement< ELEMENT >::fill_in_contribution_to_residuals().
get_volume_flux()
template<class ELEMENT >
double oomph::NavierStokesFluxControlElement< ELEMENT >::get_volume_flux () [inline], [virtual]
Function to get the integral of the volume flux.
Implements oomph::TemplateFreeNavierStokesFluxControlElementBase.
Definition at line 416 of file navier_stokes_flux_control_elements.h.
References oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux().
shape_and_test_at_knot()
template<class ELEMENT >
double oomph::NavierStokesFluxControlElement< ELEMENT >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping.
Definition at line 434 of file navier_stokes_flux_control_elements.h.
References i, oomph::FaceElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape_at_knot().
Referenced by oomph::NavierStokesFluxControlElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction(), and oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction().
u_local_eqn()
template<class ELEMENT >
virtual int oomph::NavierStokesFluxControlElement< ELEMENT >::u_local_eqn (const unsigned & n, const unsigned & i) [inline], [protected], [virtual]
Access function that returns the local equation numbers for velocity components. u_local_eqn(n,i) = local equation number or < 0 if pinned. The default is to asssume that n is the local node number and the i-th velocity component is the i-th unknown stored at the node.
Definition at line 427 of file navier_stokes_flux_control_elements.h.
References i, and oomph::FiniteElement::nodal_local_eqn().
Referenced by oomph::NavierStokesFluxControlElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction().
Member Data Documentation
Dim
template<class ELEMENT >
unsigned oomph::NavierStokesFluxControlElement< ELEMENT >::Dim [protected]
The highest dimension of the problem.
Definition at line 542 of file navier_stokes_flux_control_elements.h.
Referenced by oomph::NavierStokesFluxControlElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction(), oomph::NavierStokesFluxControlElement< ELEMENT >::NavierStokesFluxControlElement(), and oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction().
The documentation for this class was generated from the following file:
navier_stokes_flux_control_elements.h