oomph::OneDMesh< ELEMENT > Class Template Reference
1D mesh consisting of N one-dimensional elements from the QElement family.
#include <one_d_mesh.template.h>
Public Member Functions
OneDMesh (const unsigned &n_element, const double &length, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass number of elements, n_element, length of domain, length, and pointer to timestepper (defaults to a Steady timestepper so we don't need to specify one in problems without time-dependence).
OneDMesh (const unsigned &n_element, const double &xmin, const double &xmax, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass number of elements, n_element, minimum coordinate, xmin, maximum coordinate, xmax, and a pointer to a timestepper.
Protected Member Functions
void check_1d () const
Mesh can only be built with 1D elements (but can be either T or Q so can't use the normal assert_geometric_element function.
void build_mesh (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Generic mesh constuction routine, called by all constructors.
Protected Attributes
double Xmin
Minimum coordinate.
double Xmax
Maximum coordinate.
double Length
Length of the domain.
unsigned N
Number of elements.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::OneDMesh< ELEMENT >
1D mesh consisting of N one-dimensional elements from the QElement family.
 x \in [Xmin,Xmax] 
 The mesh has two boundaries:
Boundary 0 is at $x=Xmin$.
Boundary 1 is at $x=Xmax$.
There is one node on each of these boundaries.
Definition at line 51 of file one_d_mesh.template.h.
Constructor & Destructor Documentation
OneDMesh() [1/2]
template<class ELEMENT >
oomph::OneDMesh< ELEMENT >::OneDMesh (const unsigned & n_element, const double & length, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass number of elements, n_element, length of domain, length, and pointer to timestepper (defaults to a Steady timestepper so we don't need to specify one in problems without time-dependence).
Definition at line 58 of file one_d_mesh.template.h.
References oomph::OneDMesh< ELEMENT >::build_mesh(), and oomph::OneDMesh< ELEMENT >::check_1d().
OneDMesh() [2/2]
template<class ELEMENT >
oomph::OneDMesh< ELEMENT >::OneDMesh (const unsigned & n_element, const double & xmin, const double & xmax, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass number of elements, n_element, minimum coordinate, xmin, maximum coordinate, xmax, and a pointer to a timestepper.
Definition at line 71 of file one_d_mesh.template.h.
References oomph::OneDMesh< ELEMENT >::build_mesh(), and oomph::OneDMesh< ELEMENT >::check_1d().
Member Function Documentation
build_mesh()
template<class ELEMENT >
void oomph::OneDMesh< ELEMENT >::build_mesh (TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [protected]
Generic mesh constuction routine, called by all constructors.
The generic mesh construction routine --- this contains all the hard work and is called by all constructors.
Definition at line 39 of file one_d_mesh.template.cc.
References e, and oomph::QuadTreeNames::N.
Referenced by oomph::OneDMesh< ELEMENT >::OneDMesh().
check_1d()
template<class ELEMENT >
void oomph::OneDMesh< ELEMENT >::check_1d () const [inline], [protected]
Mesh can only be built with 1D elements (but can be either T or Q so can't use the normal assert_geometric_element function.
Definition at line 85 of file one_d_mesh.template.h.
References oomph::FiniteElement::dim(), and oomph::Global_string_for_annotation::string().
Referenced by oomph::OneDMesh< ELEMENT >::OneDMesh().
Member Data Documentation
Length
template<class ELEMENT >
double oomph::OneDMesh< ELEMENT >::Length [protected]
Length of the domain.
Definition at line 107 of file one_d_mesh.template.h.
N
template<class ELEMENT >
unsigned oomph::OneDMesh< ELEMENT >::N [protected]
Number of elements.
Definition at line 110 of file one_d_mesh.template.h.
Xmax
template<class ELEMENT >
double oomph::OneDMesh< ELEMENT >::Xmax [protected]
Maximum coordinate.
Definition at line 104 of file one_d_mesh.template.h.
Xmin
template<class ELEMENT >
double oomph::OneDMesh< ELEMENT >::Xmin [protected]
Minimum coordinate.
Definition at line 101 of file one_d_mesh.template.h.
The documentation for this class was generated from the following files:
one_d_mesh.template.h
one_d_mesh.template.cc