oomph::QPoissonElement< DIM, NNODE_1D > Class Template Reference
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
#include <poisson_elements.h>
Public Member Functions
QPoissonElement ()
Constructor: Call constructors for QElement and Poisson equations.
QPoissonElement (const QPoissonElement< DIM, NNODE_1D > &dummy)=delete
Broken copy constructor.
void operator= (const QPoissonElement< DIM, NNODE_1D > &)=delete
Broken assignment operator.
unsigned required_nvalue (const unsigned &n) const
Required # of `values' (pinned or dofs) at node n.
void output (std::ostream &outfile)
Output function: x,y,u or x,y,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output (FILE *file_pt)
C-style output function: x,y,u or x,y,z,u.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output function for a time-dependent exact solution. x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (Calls the steady version)
Protected Member Functions
double dshape_and_dtest_eulerian_poisson (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_poisson (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_poisson (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Static Private Attributes
static const unsigned Initial_Nvalue = 1
Static int that holds the number of variables at nodes: always the same.
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::QPoissonElement< DIM, NNODE_1D >
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
QPoissonElement elements are linear/quadrilateral/brick-shaped Poisson elements with isoparametric interpolation for the function.
Definition at line 542 of file poisson_elements.h.
Constructor & Destructor Documentation
QPoissonElement() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::QPoissonElement< DIM, NNODE_1D >::QPoissonElement () [inline]
Constructor: Call constructors for QElement and Poisson equations.
Definition at line 553 of file poisson_elements.h.
QPoissonElement() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::QPoissonElement< DIM, NNODE_1D >::QPoissonElement (const QPoissonElement< DIM, NNODE_1D > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_poisson() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QPoissonElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_poisson (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Definition at line 720 of file poisson_elements.h.
dshape_and_dtest_eulerian_at_knot_poisson() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QPoissonElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_poisson (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected]
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Definition at line 692 of file poisson_elements.h.
dshape_and_dtest_eulerian_poisson()
template<unsigned DIM, unsigned NNODE_1D>
double oomph::QPoissonElement< DIM, NNODE_1D >::dshape_and_dtest_eulerian_poisson (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected]
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
Definition at line 666 of file poisson_elements.h.
References s.
operator=()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPoissonElement< DIM, NNODE_1D >::operator= (const QPoissonElement< DIM, NNODE_1D > &) [delete]
Broken assignment operator.
output() [1/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPoissonElement< DIM, NNODE_1D >::output (FILE * file_pt) [inline]
C-style output function: x,y,u or x,y,z,u.
Definition at line 586 of file poisson_elements.h.
References oomph::CommandLineArgs::output().
output() [2/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPoissonElement< DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline]
C-style output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Definition at line 594 of file poisson_elements.h.
References oomph::CommandLineArgs::output().
output() [3/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPoissonElement< DIM, NNODE_1D >::output (std::ostream & outfile) [inline]
Output function: x,y,u or x,y,z,u.
Definition at line 570 of file poisson_elements.h.
References oomph::CommandLineArgs::output().
output() [4/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPoissonElement< DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline]
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Definition at line 578 of file poisson_elements.h.
References oomph::CommandLineArgs::output().
output_fct() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPoissonElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline]
Output function for a time-dependent exact solution. x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (Calls the steady version)
Definition at line 613 of file poisson_elements.h.
output_fct() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::QPoissonElement< DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [inline]
Output function for an exact solution: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
Definition at line 602 of file poisson_elements.h.
required_nvalue()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::QPoissonElement< DIM, NNODE_1D >::required_nvalue (const unsigned & n) const [inline]
Required # of `values' (pinned or dofs) at node n.
Definition at line 563 of file poisson_elements.h.
References oomph::QPoissonElement< DIM, NNODE_1D >::Initial_Nvalue.
Member Data Documentation
Initial_Nvalue
template<unsigned DIM, unsigned NNODE_1D>
const unsigned oomph::QPoissonElement< DIM, NNODE_1D >::Initial_Nvalue = 1 [static], [private]
Static int that holds the number of variables at nodes: always the same.
Set the data for the number of Variables at each node, always one in every case.
Definition at line 548 of file poisson_elements.h.
Referenced by oomph::QPoissonElement< DIM, NNODE_1D >::required_nvalue().
The documentation for this class was generated from the following files:
poisson_elements.h
poisson_elements.cc