oomph::FourierDecomposedHelmholtzEquations Class Reference
#include <fourier_decomposed_helmholtz_elements.h>
Public Types
typedef void(* FourierDecomposedHelmholtzSourceFctPt) (const Vector< double > &x, std::complex< double > &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
Public Member Functions
FourierDecomposedHelmholtzEquations ()
Constructor.
FourierDecomposedHelmholtzEquations (const FourierDecomposedHelmholtzEquations &dummy)
Broken copy constructor.
virtual std::complex< unsigned > u_index_fourier_decomposed_helmholtz () const
Broken assignment operator.
double *& k_squared_pt ()
Get pointer to square of wavenumber.
double k_squared ()
Get the square of wavenumber.
int *& fourier_wavenumber_pt ()
Get pointer to Fourier wavenumber.
int fourier_wavenumber ()
Get the Fourier wavenumber.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &n_plot)
Output FE representation of soln: x,y,u_re,u_im or x,y,z,u_re,u_im at n_plot^2 plot points.
void output_real (std::ostream &outfile, const double &phi, const unsigned &n_plot)
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. r,z,u at n_plot plot points in each coordinate direction.
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output FE representation of soln: r,z,u_re,u_im or at n_plot^2 plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: (dummy time-dependent version to keep intel compiler happy)
void output_real_fct (std::ostream &outfile, const double &phi, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for real part of full time-dependent fct u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. r,z,u at n_plot plot points in each coordinate direction.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
void compute_norm (double &norm)
Compute norm of fe solution.
FourierDecomposedHelmholtzSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
FourierDecomposedHelmholtzSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
virtual void get_source_fourier_decomposed_helmholtz (const unsigned &ipt, const Vector< double > &x, std::complex< double > &source) const
void get_flux (const Vector< double > &s, Vector< std::complex< double >> &flux) const
Get flux: flux[i] = du/dx_i for real and imag part.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and element Jacobian matrix (wrapper)
std::complex< double > interpolated_u_fourier_decomposed_helmholtz (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
unsigned self_test ()
Self-test: Return 0 for OK.
Protected Member Functions
virtual double dshape_and_dtest_eulerian_fourier_decomposed_helmholtz (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_fourier_decomposed_helmholtz (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
virtual void fill_in_generic_residual_contribution_fourier_decomposed_helmholtz (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Protected Attributes
FourierDecomposedHelmholtzSourceFctPt Source_fct_pt
Pointer to source function:
double * K_squared_pt
Pointer to square of wavenumber.
int * N_fourier_pt
Pointer to Fourier wave number.
Additional Inherited Members
Detailed Description
A class for all isoparametric elements that solve the Helmholtz equations.
 \nabla^2 U + k^2 U = f 
 in Fourier decomposed form (cylindrical polars):
 U(r,\varphi,z) = \Re( u^{(n)}(r,z) \exp(-i n \varphi)) 
 We are solving for $ u^{(n)}(r,z)$ for given parameters $ k^2 $ and $ n $ . This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
Definition at line 87 of file fourier_decomposed_helmholtz_elements.h.
Member Typedef Documentation
FourierDecomposedHelmholtzSourceFctPt
typedef void(* oomph::FourierDecomposedHelmholtzEquations::FourierDecomposedHelmholtzSourceFctPt) (const Vector< double > &x, std::complex< double > &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
Definition at line 92 of file fourier_decomposed_helmholtz_elements.h.
Constructor & Destructor Documentation
FourierDecomposedHelmholtzEquations() [1/2]
oomph::FourierDecomposedHelmholtzEquations::FourierDecomposedHelmholtzEquations () [inline]
Constructor.
Definition at line 97 of file fourier_decomposed_helmholtz_elements.h.
FourierDecomposedHelmholtzEquations() [2/2]
oomph::FourierDecomposedHelmholtzEquations::FourierDecomposedHelmholtzEquations (const FourierDecomposedHelmholtzEquations & dummy) [inline]
Broken copy constructor.
Definition at line 103 of file fourier_decomposed_helmholtz_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
compute_error() [1/2]
void oomph::FourierDecomposedHelmholtzEquations::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 626 of file fourier_decomposed_helmholtz_elements.cc.
References i, oomph::FiniteElement::integral_pt(), interpolated_u_fourier_decomposed_helmholtz(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
compute_error() [2/2]
void oomph::FourierDecomposedHelmholtzEquations::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [inline], [virtual]
Dummy, time dependent error checker.
Reimplemented from oomph::FiniteElement.
Definition at line 240 of file fourier_decomposed_helmholtz_elements.h.
compute_norm()
void oomph::FourierDecomposedHelmholtzEquations::compute_norm (double & norm) [virtual]
Compute norm of fe solution.
Reimplemented from oomph::GeneralisedElement.
Definition at line 706 of file fourier_decomposed_helmholtz_elements.cc.
References i, oomph::FiniteElement::integral_pt(), interpolated_u_fourier_decomposed_helmholtz(), oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), s, oomph::QuadTreeNames::W, and oomph::Integral::weight().
dshape_and_dtest_eulerian_at_knot_fourier_decomposed_helmholtz()
virtual double oomph::FourierDecomposedHelmholtzEquations::dshape_and_dtest_eulerian_at_knot_fourier_decomposed_helmholtz (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >.
Referenced by fill_in_generic_residual_contribution_fourier_decomposed_helmholtz().
dshape_and_dtest_eulerian_fourier_decomposed_helmholtz()
virtual double oomph::FourierDecomposedHelmholtzEquations::dshape_and_dtest_eulerian_fourier_decomposed_helmholtz (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >.
fill_in_contribution_to_jacobian()
void oomph::FourierDecomposedHelmholtzEquations::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and element Jacobian matrix (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 339 of file fourier_decomposed_helmholtz_elements.h.
References fill_in_generic_residual_contribution_fourier_decomposed_helmholtz(), and residuals().
fill_in_contribution_to_residuals()
void oomph::FourierDecomposedHelmholtzEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 328 of file fourier_decomposed_helmholtz_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, fill_in_generic_residual_contribution_fourier_decomposed_helmholtz(), and residuals().
fill_in_generic_residual_contribution_fourier_decomposed_helmholtz()
void oomph::FourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected], [virtual]
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Compute element residual Vector and/or element Jacobian matrix
flag=1: compute both flag=0: compute only residual Vector
Pure version without hanging nodes
Definition at line 183 of file fourier_decomposed_helmholtz_elements.cc.
References dshape_and_dtest_eulerian_at_knot_fourier_decomposed_helmholtz(), fourier_wavenumber(), get_source_fourier_decomposed_helmholtz(), i, oomph::FiniteElement::integral_pt(), interpolated_u(), oomph::FiniteElement::interpolated_x(), k_squared(), n, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::Integral::nweight(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), residuals(), u_index_fourier_decomposed_helmholtz(), oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by fill_in_contribution_to_jacobian(), and fill_in_contribution_to_residuals().
fourier_wavenumber()
int oomph::FourierDecomposedHelmholtzEquations::fourier_wavenumber () [inline]
Get the Fourier wavenumber.
Definition at line 157 of file fourier_decomposed_helmholtz_elements.h.
References N_fourier_pt.
Referenced by fill_in_generic_residual_contribution_fourier_decomposed_helmholtz().
fourier_wavenumber_pt()
int*& oomph::FourierDecomposedHelmholtzEquations::fourier_wavenumber_pt () [inline]
Get pointer to Fourier wavenumber.
Definition at line 151 of file fourier_decomposed_helmholtz_elements.h.
References N_fourier_pt.
get_flux()
void oomph::FourierDecomposedHelmholtzEquations::get_flux (const Vector< double > & s, Vector< std::complex< double >> & flux) const [inline]
Get flux: flux[i] = du/dx_i for real and imag part.
Definition at line 290 of file fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, and u_index_fourier_decomposed_helmholtz().
Referenced by oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >::get_Z2_flux().
get_source_fourier_decomposed_helmholtz()
virtual void oomph::FourierDecomposedHelmholtzEquations::get_source_fourier_decomposed_helmholtz (const unsigned & ipt, const Vector< double > & x, std::complex< double > & source) const [inline], [virtual]
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
Definition at line 271 of file fourier_decomposed_helmholtz_elements.h.
References Source_fct_pt.
Referenced by fill_in_generic_residual_contribution_fourier_decomposed_helmholtz().
interpolated_u_fourier_decomposed_helmholtz()
std::complex<double> oomph::FourierDecomposedHelmholtzEquations::interpolated_u_fourier_decomposed_helmholtz (const Vector< double > & s) const [inline]
Return FE representation of function value u(s) at local coordinate s.
Definition at line 350 of file fourier_decomposed_helmholtz_elements.h.
References interpolated_u(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and u_index_fourier_decomposed_helmholtz().
Referenced by compute_error(), compute_norm(), output(), and output_real().
k_squared()
double oomph::FourierDecomposedHelmholtzEquations::k_squared () [inline]
Get the square of wavenumber.
Definition at line 138 of file fourier_decomposed_helmholtz_elements.h.
References K_squared_pt.
Referenced by fill_in_generic_residual_contribution_fourier_decomposed_helmholtz().
k_squared_pt()
double*& oomph::FourierDecomposedHelmholtzEquations::k_squared_pt () [inline]
Get pointer to square of wavenumber.
Definition at line 132 of file fourier_decomposed_helmholtz_elements.h.
References K_squared_pt.
output() [1/4]
void oomph::FourierDecomposedHelmholtzEquations::output (FILE * file_pt) [inline], [virtual]
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >.
Definition at line 190 of file fourier_decomposed_helmholtz_elements.h.
References output().
output() [2/4]
void oomph::FourierDecomposedHelmholtzEquations::output (FILE * file_pt, const unsigned & nplot) [virtual]
C-style output FE representation of soln: r,z,u_re,u_im or at n_plot^2 plot points.
C-style output function:
r,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >.
Definition at line 477 of file fourier_decomposed_helmholtz_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, interpolated_u_fourier_decomposed_helmholtz(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), u(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [3/4]
void oomph::FourierDecomposedHelmholtzEquations::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >.
Definition at line 170 of file fourier_decomposed_helmholtz_elements.h.
Referenced by oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >::output(), output(), and oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::output().
output() [4/4]
void oomph::FourierDecomposedHelmholtzEquations::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: x,y,u_re,u_im or x,y,z,u_re,u_im at n_plot^2 plot points.
Output function:
r,z,u_re,u_imag
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >.
Definition at line 402 of file fourier_decomposed_helmholtz_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, interpolated_u_fourier_decomposed_helmholtz(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), u(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_fct() [1/2]
virtual void oomph::FourierDecomposedHelmholtzEquations::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output exact soln: (dummy time-dependent version to keep intel compiler happy)
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >.
Definition at line 208 of file fourier_decomposed_helmholtz_elements.h.
output_fct() [2/2]
void oomph::FourierDecomposedHelmholtzEquations::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: r,z,u_re_exact,u_im_exact at n_plot^2 plot points
Output exact solution
Solution is provided via function pointer. Plot at a given number of plot points.
r,z,u_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >, and oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >.
Definition at line 520 of file fourier_decomposed_helmholtz_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
Referenced by oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >::output_fct(), and oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::output_fct().
output_real()
void oomph::FourierDecomposedHelmholtzEquations::output_real (std::ostream & outfile, const double & phi, const unsigned & nplot)
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. r,z,u at n_plot plot points in each coordinate direction.
Output function for real part of full time-dependent solution
u = Re((u_r +i u_i) exp(-i omega t)
at phase angle omega t = phi.
r,z,u
Output at nplot points in each coordinate direction
Definition at line 441 of file fourier_decomposed_helmholtz_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, interpolated_u_fourier_decomposed_helmholtz(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), u(), and oomph::FiniteElement::write_tecplot_zone_footer().
Referenced by oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::output_real().
output_real_fct()
void oomph::FourierDecomposedHelmholtzEquations::output_real_fct (std::ostream & outfile, const double & phi, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for real part of full time-dependent fct u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. r,z,u at n_plot plot points in each coordinate direction.
Output function for real part of full time-dependent fct
u = Re((u_r +i u_i) exp(-i omega t)
at phase angle omega t = phi.
r,z,u
Output at nplot points in each coordinate direction
Definition at line 574 of file fourier_decomposed_helmholtz_elements.cc.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
Referenced by oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::output_real_fct().
self_test()
unsigned oomph::FourierDecomposedHelmholtzEquations::self_test () [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
Definition at line 373 of file fourier_decomposed_helmholtz_elements.cc.
References oomph::FiniteElement::self_test().
source_fct_pt() [1/2]
FourierDecomposedHelmholtzSourceFctPt& oomph::FourierDecomposedHelmholtzEquations::source_fct_pt () [inline]
Access function: Pointer to source function.
Definition at line 256 of file fourier_decomposed_helmholtz_elements.h.
References Source_fct_pt.
source_fct_pt() [2/2]
FourierDecomposedHelmholtzSourceFctPt oomph::FourierDecomposedHelmholtzEquations::source_fct_pt () const [inline]
Access function: Pointer to source function. Const version.
Definition at line 262 of file fourier_decomposed_helmholtz_elements.h.
References Source_fct_pt.
u_index_fourier_decomposed_helmholtz()
virtual std::complex<unsigned> oomph::FourierDecomposedHelmholtzEquations::u_index_fourier_decomposed_helmholtz () const [inline], [virtual]
Broken assignment operator.
Return the index at which the unknown value is stored: Real/imag part of index contains (real) index of real/imag part.
Definition at line 124 of file fourier_decomposed_helmholtz_elements.h.
Referenced by fill_in_generic_residual_contribution_fourier_decomposed_helmholtz(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::FourierDecomposedHelmholtzBCElementBase(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::FourierDecomposedHelmholtzFluxElement(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement(), get_flux(), and interpolated_u_fourier_decomposed_helmholtz().
Member Data Documentation
K_squared_pt
double* oomph::FourierDecomposedHelmholtzEquations::K_squared_pt [protected]
Pointer to square of wavenumber.
Definition at line 420 of file fourier_decomposed_helmholtz_elements.h.
Referenced by k_squared(), and k_squared_pt().
N_fourier_pt
int* oomph::FourierDecomposedHelmholtzEquations::N_fourier_pt [protected]
Pointer to Fourier wave number.
Definition at line 423 of file fourier_decomposed_helmholtz_elements.h.
Referenced by fourier_wavenumber(), and fourier_wavenumber_pt().
Source_fct_pt
FourierDecomposedHelmholtzSourceFctPt oomph::FourierDecomposedHelmholtzEquations::Source_fct_pt [protected]
Pointer to source function:
Definition at line 417 of file fourier_decomposed_helmholtz_elements.h.
Referenced by get_source_fourier_decomposed_helmholtz(), and source_fct_pt().
The documentation for this class was generated from the following files:
fourier_decomposed_helmholtz_elements.h
fourier_decomposed_helmholtz_elements.cc