oomph::AxisymmetricQTaylorHoodElement Class Reference
/////////////////////////////////////////////////////////////////////////
#include <axisym_navier_stokes_elements.h>
Public Member Functions
AxisymmetricQTaylorHoodElement ()
Constructor, no internal data points.
virtual unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
virtual int p_nodal_index_axi_nst () const
Which nodal value represents the pressure?
double p_axi_nst (const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
unsigned npres_axi_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &n_p, const double &pvalue)
Fix the pressure at local pressure node n_p.
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction) const
Compute traction at local coordinate s for outer unit normal N.
int p_local_eqn (const unsigned &n) const
Overload the access function for the pressure's local equation numbers.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
unsigned ndof_types () const
Returns the number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity (3 components) and pressure.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Protected Member Functions
double dshape_and_dtest_eulerian_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
void pshape_axi_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
Static Protected Attributes
static const unsigned Pconv [] = {0, 2, 6, 8}
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Static Private Attributes
static const unsigned Initial_Nvalue []
Static array of ints to hold number of variables at node.
Additional Inherited Members
Detailed Description
/////////////////////////////////////////////////////////////////////////
Taylor--Hood elements are Navier--Stokes elements with quadratic interpolation for velocities and positions and continous linear pressure interpolation
Definition at line 1529 of file axisym_navier_stokes_elements.h.
Constructor & Destructor Documentation
AxisymmetricQTaylorHoodElement()
oomph::AxisymmetricQTaylorHoodElement::AxisymmetricQTaylorHoodElement () [inline]
Constructor, no internal data points.
Definition at line 1584 of file axisym_navier_stokes_elements.h.
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_axi_nst() [1/2]
double oomph::AxisymmetricQTaylorHoodElement::dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 1738 of file axisym_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot(), and i.
dshape_and_dtest_eulerian_at_knot_axi_nst() [2/2]
double oomph::AxisymmetricQTaylorHoodElement::dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 1709 of file axisym_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot(), and i.
dshape_and_dtest_eulerian_axi_nst()
double oomph::AxisymmetricQTaylorHoodElement::dshape_and_dtest_eulerian_axi_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 1683 of file axisym_navier_stokes_elements.h.
References oomph::FiniteElement::dshape_eulerian(), and i.
fix_pressure()
void oomph::AxisymmetricQTaylorHoodElement::fix_pressure (const unsigned & n_p, const double & pvalue) [inline]
Fix the pressure at local pressure node n_p.
Definition at line 1616 of file axisym_navier_stokes_elements.h.
References oomph::FiniteElement::node_pt(), p_nodal_index_axi_nst(), oomph::Data::pin(), and oomph::Data::set_value().
get_dof_numbers_for_unknowns()
void oomph::AxisymmetricQTaylorHoodElement::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Create a list of pairs for all unknowns in this element, so the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Reimplemented from oomph::GeneralisedElement.
Definition at line 3741 of file axisym_navier_stokes_elements.cc.
References oomph::GeneralisedElement::eqn_number(), oomph::GeneralisedElement::local_eqn_number(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), and oomph::Data::nvalue().
get_traction()
void oomph::AxisymmetricQTaylorHoodElement::get_traction (const Vector< double > & s, const Vector< double > & N, Vector< double > & traction) const
Compute traction at local coordinate s for outer unit normal N.
Definition at line 3794 of file axisym_navier_stokes_elements.cc.
References oomph::QuadTreeNames::N, s, and oomph::AxisymmetricNavierStokesEquations::traction().
Referenced by oomph::FSIAxisymmetricQTaylorHoodElement::get_load().
ndof_types()
unsigned oomph::AxisymmetricQTaylorHoodElement::ndof_types () const [inline], [virtual]
Returns the number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity (3 components) and pressure.
Reimplemented from oomph::GeneralisedElement.
Definition at line 1661 of file axisym_navier_stokes_elements.h.
npres_axi_nst()
unsigned oomph::AxisymmetricQTaylorHoodElement::npres_axi_nst () const [inline], [virtual]
Return number of pressure values.
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 1610 of file axisym_navier_stokes_elements.h.
Referenced by oomph::FSIAxisymmetricQTaylorHoodElement::identify_pressure_data(), and oomph::RefineableAxisymmetricQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs().
output() [1/4]
void oomph::AxisymmetricQTaylorHoodElement::output (FILE * file_pt) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::AxisymmetricNavierStokesEquations.
Definition at line 1647 of file axisym_navier_stokes_elements.h.
References oomph::AxisymmetricNavierStokesEquations::output().
output() [2/4]
void oomph::AxisymmetricQTaylorHoodElement::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::AxisymmetricNavierStokesEquations.
Definition at line 1653 of file axisym_navier_stokes_elements.h.
References oomph::AxisymmetricNavierStokesEquations::output().
output() [3/4]
void oomph::AxisymmetricQTaylorHoodElement::output (std::ostream & outfile) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::AxisymmetricNavierStokesEquations.
Definition at line 1635 of file axisym_navier_stokes_elements.h.
References oomph::AxisymmetricNavierStokesEquations::output().
output() [4/4]
void oomph::AxisymmetricQTaylorHoodElement::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Redirect output to NavierStokesEquations output.
Reimplemented from oomph::AxisymmetricNavierStokesEquations.
Definition at line 1641 of file axisym_navier_stokes_elements.h.
References oomph::AxisymmetricNavierStokesEquations::output().
p_axi_nst()
double oomph::AxisymmetricQTaylorHoodElement::p_axi_nst (const unsigned & n_p) const [inline], [virtual]
Access function for the pressure values at local pressure node n_p (const version)
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 1604 of file axisym_navier_stokes_elements.h.
References oomph::FiniteElement::nodal_value(), p_nodal_index_axi_nst(), and Pconv.
p_local_eqn()
int oomph::AxisymmetricQTaylorHoodElement::p_local_eqn (const unsigned & n) const [inline], [virtual]
Overload the access function for the pressure's local equation numbers.
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 1629 of file axisym_navier_stokes_elements.h.
References oomph::FiniteElement::nodal_local_eqn(), p_nodal_index_axi_nst(), and Pconv.
p_nodal_index_axi_nst()
virtual int oomph::AxisymmetricQTaylorHoodElement::p_nodal_index_axi_nst () const [inline], [virtual]
Which nodal value represents the pressure?
Reimplemented from oomph::AxisymmetricNavierStokesEquations.
Definition at line 1597 of file axisym_navier_stokes_elements.h.
Referenced by fix_pressure(), oomph::FSIAxisymmetricQTaylorHoodElement::identify_pressure_data(), p_axi_nst(), p_local_eqn(), oomph::RefineableAxisymmetricQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), and oomph::RefineableAxisymmetricQTaylorHoodElement::unpin_elemental_pressure_dofs().
pshape_axi_nst() [1/2]
void oomph::AxisymmetricQTaylorHoodElement::pshape_axi_nst (const Vector< double > & s, Shape & psi) const [inline], [protected], [virtual]
Pressure shape functions at local coordinate s.
Pressure shape functions.
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 1780 of file axisym_navier_stokes_elements.h.
References i, s, and oomph::OneDimLagrange::shape< 2 >().
Referenced by oomph::RefineableAxisymmetricQTaylorHoodElement::interpolating_basis(), and pshape_axi_nst().
pshape_axi_nst() [2/2]
void oomph::AxisymmetricQTaylorHoodElement::pshape_axi_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected], [virtual]
Pressure shape and test functions at local coordinte s.
Pressure shape and test functions.
Implements oomph::AxisymmetricNavierStokesEquations.
Definition at line 1804 of file axisym_navier_stokes_elements.h.
References i, pshape_axi_nst(), and s.
required_nvalue()
virtual unsigned oomph::AxisymmetricQTaylorHoodElement::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::RefineableAxisymmetricQTaylorHoodElement.
Definition at line 1591 of file axisym_navier_stokes_elements.h.
References Initial_Nvalue.
Member Data Documentation
Initial_Nvalue
const unsigned oomph::AxisymmetricQTaylorHoodElement::Initial_Nvalue [static], [private]
Initial value:
= {
    4, 3, 4, 3, 3, 3, 4, 3, 4}
Static array of ints to hold number of variables at node.
Definition at line 1535 of file axisym_navier_stokes_elements.h.
Referenced by required_nvalue().
Pconv
const unsigned oomph::AxisymmetricQTaylorHoodElement::Pconv = {0, 2, 6, 8} [static], [protected]
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Definition at line 1540 of file axisym_navier_stokes_elements.h.
Referenced by oomph::RefineableAxisymmetricQTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::FSIAxisymmetricQTaylorHoodElement::identify_pressure_data(), oomph::RefineableAxisymmetricQTaylorHoodElement::interpolating_node_pt(), p_axi_nst(), p_local_eqn(), oomph::RefineableAxisymmetricQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), and oomph::RefineableAxisymmetricQTaylorHoodElement::pressure_node_pt().
The documentation for this class was generated from the following files:
axisym_navier_stokes_elements.h
axisym_navier_stokes_elements.cc