oomph::TElement< DIM, NNODE_1D > Class Template Reference
General TElement class.
#include <Telements.h>
Public Member Functions
const unsigned Node_on_face [3][2]
Assign the nodal translation schemes.
const unsigned Node_on_face [3][3]
const unsigned Node_on_face [3][4]
const unsigned Node_on_face [4][3]
Assign the nodal translation scheme for linear elements.
const unsigned Node_on_face [4][6]
Assign the nodal translation scheme for quadratic elements.
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::TElement< DIM, NNODE_1D >
General TElement class.
Empty, just establishes the template parameters
Definition at line 1207 of file Telements.h.
Member Function Documentation
Node_on_face() [1/5]
const unsigned oomph::TElement< 2, 2 >::Node_on_face
Assign the nodal translation schemes.
Definition at line 272 of file Telements.cc.
Referenced by oomph::TElement< 2, NNODE_1D >::build_face_element(), oomph::TElement< 3, NNODE_1D >::build_face_element(), oomph::TElement< 2, NNODE_1D >::get_bulk_node_number(), and oomph::TElement< 3, NNODE_1D >::get_bulk_node_number().
Node_on_face() [2/5]
const unsigned oomph::TElement< 2, 3 >::Node_on_face
Definition at line 275 of file Telements.cc.
Node_on_face() [3/5]
const unsigned oomph::TElement< 2, 4 >::Node_on_face
Definition at line 279 of file Telements.cc.
Node_on_face() [4/5]
const unsigned oomph::TElement< 3, 2 >::Node_on_face
Assign the nodal translation scheme for linear elements.
Definition at line 717 of file Telements.cc.
Node_on_face() [5/5]
const unsigned oomph::TElement< 3, 3 >::Node_on_face
Assign the nodal translation scheme for quadratic elements.
Definition at line 722 of file Telements.cc.
The documentation for this class was generated from the following file:
Telements.h