oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D > Class Template Reference
Refineable version of QSphericalAdvectionDiffusionElement. Inherit from the standard QSphericalAdvectionDiffusionElement and the appropriate refineable geometric element and the refineable equations.
#include <refineable_spherical_advection_diffusion_elements.h>
Public Member Functions
RefineableQSphericalAdvectionDiffusionElement ()
Empty Constructor:
RefineableQSphericalAdvectionDiffusionElement (const RefineableQSphericalAdvectionDiffusionElement< NNODE_1D > &dummy)
Broken copy constructor.
void operator= (const RefineableQSphericalAdvectionDiffusionElement< NNODE_1D > &)
Broken assignment operator.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: 1.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: empty.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
void further_setup_hanging_nodes ()
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty.
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >
Refineable version of QSphericalAdvectionDiffusionElement. Inherit from the standard QSphericalAdvectionDiffusionElement and the appropriate refineable geometric element and the refineable equations.
Definition at line 362 of file refineable_spherical_advection_diffusion_elements.h.
Constructor & Destructor Documentation
RefineableQSphericalAdvectionDiffusionElement() [1/2]
template<unsigned NNODE_1D>
oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >::RefineableQSphericalAdvectionDiffusionElement () [inline]
Empty Constructor:
Definition at line 369 of file refineable_spherical_advection_diffusion_elements.h.
RefineableQSphericalAdvectionDiffusionElement() [2/2]
template<unsigned NNODE_1D>
oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >::RefineableQSphericalAdvectionDiffusionElement (const RefineableQSphericalAdvectionDiffusionElement< NNODE_1D > & dummy) [inline]
Broken copy constructor.
Definition at line 379 of file refineable_spherical_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
further_setup_hanging_nodes()
template<unsigned NNODE_1D>
void oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >::further_setup_hanging_nodes () [inline], [virtual]
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty.
Implements oomph::RefineableQElement< 2 >.
Definition at line 423 of file refineable_spherical_advection_diffusion_elements.h.
ncont_interpolated_values()
template<unsigned NNODE_1D>
unsigned oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values: 1.
Implements oomph::RefineableElement.
Definition at line 394 of file refineable_spherical_advection_diffusion_elements.h.
nrecovery_order()
template<unsigned NNODE_1D>
unsigned oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 416 of file refineable_spherical_advection_diffusion_elements.h.
nvertex_node()
template<unsigned NNODE_1D>
unsigned oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 400 of file refineable_spherical_advection_diffusion_elements.h.
References oomph::QElement< 2, NNODE_1D >::nvertex_node().
operator=()
template<unsigned NNODE_1D>
void oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >::operator= (const RefineableQSphericalAdvectionDiffusionElement< NNODE_1D > &) [inline]
Broken assignment operator.
Definition at line 386 of file refineable_spherical_advection_diffusion_elements.h.
References oomph::BrokenCopy::broken_assign().
rebuild_from_sons()
template<unsigned NNODE_1D>
void oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
Rebuild from sons: empty.
Implements oomph::RefineableElement.
Definition at line 412 of file refineable_spherical_advection_diffusion_elements.h.
vertex_node_pt()
template<unsigned NNODE_1D>
Node* oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 406 of file refineable_spherical_advection_diffusion_elements.h.
References oomph::QElement< 2, NNODE_1D >::vertex_node_pt().
The documentation for this class was generated from the following file:
refineable_spherical_advection_diffusion_elements.h