QCrouzeixRaviartElement< DIM > Class Template Reference
/////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////
#include <navier_stokes_elements.h>
Public Member Functions
QCrouzeixRaviartElement ()
Constructor, there are DIM+1 internal values (for the pressure)
virtual unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at local node n.
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
double p_nst (const unsigned &i) const
Return the i-th pressure value (Discontinous pressure interpolation -- no need to cater for hanging nodes).
double p_nst (const unsigned &t, const unsigned &i) const
Return the i-th pressure value (Discontinous pressure interpolation -- no need to cater for hanging nodes).
unsigned npres_nst () const
Return number of pressure values.
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs containing.
void identify_pressure_data (std::set< std::pair< Data *, unsigned > > &paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void full_output (std::ostream &outfile)
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. Default number of plot points.
void full_output (std::ostream &outfile, const unsigned &nplot)
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. nplot points in each coordinate direction.
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity and pressure.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1.
void pshape_nst (const Vector< double > &s, Shape &psi) const
2D : Pressure shape functions
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
2D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
void pshape_nst (const Vector< double > &s, Shape &psi) const
3D : Pressure shape functions
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
3D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
Protected Member Functions
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at ipt-th integation point (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
2D Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
3D Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Protected Attributes
unsigned P_nst_internal_index
Internal index that indicates at which internal data the pressure is stored.
Private Member Functions
const unsigned Initial_Nvalue [9]
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
const unsigned Initial_Nvalue [27]
3D Crouzeix-Raviart elements
Static Private Attributes
static const unsigned Initial_Nvalue []
Static array of ints to hold required number of variables at nodes.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class QCrouzeixRaviartElement< DIM >
/////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////
Crouzeix_Raviart elements are Navier--Stokes elements with quadratic interpolation for velocities and positions, but a discontinuous linear pressure interpolation. They can be used within oomph-lib's block preconditioning framework.
Definition at line 1753 of file navier_stokes_elements.h.
Constructor & Destructor Documentation
QCrouzeixRaviartElement()
template<unsigned DIM>
QCrouzeixRaviartElement< DIM >::QCrouzeixRaviartElement () [inline]
Constructor, there are DIM+1 internal values (for the pressure)
Definition at line 1800 of file navier_stokes_elements.h.
Member Function Documentation
build_fp_press_adv_diff_robin_bc_element()
template<unsigned DIM>
void QCrouzeixRaviartElement< DIM >::build_fp_press_adv_diff_robin_bc_element (const unsigned & face_index) [inline], [virtual]
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Implements NavierStokesEquations< DIM >.
Reimplemented in oomph::RefineableQCrouzeixRaviartElement< DIM >.
Definition at line 1867 of file navier_stokes_elements.h.
dpshape_and_dptest_eulerian_nst() [1/3]
template<unsigned DIM>
double QCrouzeixRaviartElement< DIM >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [virtual]
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Implements NavierStokesEquations< DIM >.
dpshape_and_dptest_eulerian_nst() [2/3]
double QCrouzeixRaviartElement< 2 >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [virtual]
2D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
Implements NavierStokesEquations< DIM >.
Definition at line 2123 of file navier_stokes_elements.h.
References s.
dpshape_and_dptest_eulerian_nst() [3/3]
double QCrouzeixRaviartElement< 3 >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [virtual]
3D : Pressure shape and test functions and derivs w.r.t. to Eulerian coords. Return Jacobian of mapping between local and global coordinates.
Implements NavierStokesEquations< DIM >.
Definition at line 2204 of file navier_stokes_elements.h.
References s.
dshape_and_dtest_eulerian_at_knot_nst() [1/4]
template<unsigned DIM>
double QCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implements NavierStokesEquations< DIM >.
dshape_and_dtest_eulerian_at_knot_nst() [2/4]
double QCrouzeixRaviartElement< 2 >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
2D Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements NavierStokesEquations< DIM >.
Definition at line 2013 of file navier_stokes_elements.h.
References i.
dshape_and_dtest_eulerian_at_knot_nst() [3/4]
double QCrouzeixRaviartElement< 3 >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
3D Define the shape functions (psi) and test functions (test) and their derivatives w.r.t. global coordinates (dpsidx and dtestdx) and return Jacobian of mapping (J). Additionally compute the derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Galerkin: Test functions = shape functions
Implements NavierStokesEquations< DIM >.
Definition at line 2063 of file navier_stokes_elements.h.
References i.
dshape_and_dtest_eulerian_at_knot_nst() [4/4]
template<unsigned DIM>
double QCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at ipt-th integation point (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t. to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements NavierStokesEquations< DIM >.
Definition at line 1987 of file navier_stokes_elements.h.
Referenced by oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), and oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic().
dshape_and_dtest_eulerian_nst()
template<unsigned DIM>
double QCrouzeixRaviartElement< DIM >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t. to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements NavierStokesEquations< DIM >.
Definition at line 1964 of file navier_stokes_elements.h.
References s.
fix_pressure()
template<unsigned DIM>
void QCrouzeixRaviartElement< DIM >::fix_pressure (const unsigned & p_dof, const double & p_value) [inline], [virtual]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implements NavierStokesEquations< DIM >.
Reimplemented in oomph::PRefineableQCrouzeixRaviartElement< DIM >.
Definition at line 1857 of file navier_stokes_elements.h.
full_output() [1/2]
template<unsigned DIM>
void QCrouzeixRaviartElement< DIM >::full_output (std::ostream & outfile) [inline]
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. Default number of plot points.
Definition at line 1925 of file navier_stokes_elements.h.
References NavierStokesEquations< DIM >::full_output().
full_output() [2/2]
template<unsigned DIM>
void QCrouzeixRaviartElement< DIM >::full_output (std::ostream & outfile, const unsigned & nplot) [inline]
Full output function: x,y,[z],u,v,[w],p,du/dt,dv/dt,[dw/dt],dissipation in tecplot format. nplot points in each coordinate direction.
Definition at line 1933 of file navier_stokes_elements.h.
References NavierStokesEquations< DIM >::full_output().
get_dof_numbers_for_unknowns()
template<unsigned DIM>
void QCrouzeixRaviartElement< DIM >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Velocity=0; Pressure=1.
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the DOF that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Definition at line 2662 of file navier_stokes_elements.cc.
identify_load_data()
template<unsigned DIM>
void QCrouzeixRaviartElement< DIM >::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data)
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Definition at line 2598 of file navier_stokes_elements.cc.
References i.
identify_pressure_data()
template<unsigned DIM>
void QCrouzeixRaviartElement< DIM >::identify_pressure_data (std::set< std::pair< Data *, unsigned > > & paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
Add to the set paired_pressue_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all pressure values that affect the load computed in the get_load(...) function.
the pointer to a Data object and
the index of the value in that Data object
for all pressures values that affect the load computed in the get_load(...) function.
Definition at line 2635 of file navier_stokes_elements.cc.
Initial_Nvalue() [1/2]
const unsigned QCrouzeixRaviartElement< 3 >::Initial_Nvalue [private]
3D Crouzeix-Raviart elements
Definition at line 2572 of file navier_stokes_elements.cc.
Initial_Nvalue() [2/2]
const unsigned QCrouzeixRaviartElement< 2 >::Initial_Nvalue [private]
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
2D Crouzeix-Raviart elements
Definition at line 2566 of file navier_stokes_elements.cc.
ndof_types()
template<unsigned DIM>
unsigned QCrouzeixRaviartElement< DIM >::ndof_types () const [inline]
The number of `DOF types` that degrees of freedom in this element are sub-divided into: Velocity and pressure.
Definition at line 1941 of file navier_stokes_elements.h.
npres_nst()
template<unsigned DIM>
unsigned QCrouzeixRaviartElement< DIM >::npres_nst () const [inline], [virtual]
Return number of pressure values.
Implements NavierStokesEquations< DIM >.
Reimplemented in oomph::PRefineableQCrouzeixRaviartElement< DIM >.
Definition at line 1836 of file navier_stokes_elements.h.
Referenced by oomph::RefineableQCrouzeixRaviartElement< DIM >::identify_load_data(), and oomph::RefineableQCrouzeixRaviartElement< DIM >::unpin_elemental_pressure_dofs().
output() [1/4]
template<unsigned DIM>
void QCrouzeixRaviartElement< DIM >::output (FILE * file_pt) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 1910 of file navier_stokes_elements.h.
References NavierStokesEquations< DIM >::output().
output() [2/4]
template<unsigned DIM>
void QCrouzeixRaviartElement< DIM >::output (FILE * file_pt, const unsigned & nplot) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 1916 of file navier_stokes_elements.h.
References NavierStokesEquations< DIM >::output().
output() [3/4]
template<unsigned DIM>
void QCrouzeixRaviartElement< DIM >::output (std::ostream & outfile) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 1897 of file navier_stokes_elements.h.
References NavierStokesEquations< DIM >::output().
output() [4/4]
template<unsigned DIM>
void QCrouzeixRaviartElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) [inline]
Redirect output to NavierStokesEquations output.
Definition at line 1903 of file navier_stokes_elements.h.
References NavierStokesEquations< DIM >::output().
p_local_eqn()
template<unsigned DIM>
int QCrouzeixRaviartElement< DIM >::p_local_eqn (const unsigned & n) const [inline]
Return the local equation numbers for the pressure values.
Definition at line 1851 of file navier_stokes_elements.h.
p_nst() [1/2]
template<unsigned DIM>
double QCrouzeixRaviartElement< DIM >::p_nst (const unsigned & i) const [inline], [virtual]
Return the i-th pressure value (Discontinous pressure interpolation -- no need to cater for hanging nodes).
Implements NavierStokesEquations< DIM >.
Reimplemented in oomph::PRefineableQCrouzeixRaviartElement< DIM >.
Definition at line 1822 of file navier_stokes_elements.h.
References i.
p_nst() [2/2]
template<unsigned DIM>
double QCrouzeixRaviartElement< DIM >::p_nst (const unsigned & t, const unsigned & i) const [inline], [virtual]
Return the i-th pressure value (Discontinous pressure interpolation -- no need to cater for hanging nodes).
Implements NavierStokesEquations< DIM >.
Reimplemented in oomph::PRefineableQCrouzeixRaviartElement< DIM >.
Definition at line 1830 of file navier_stokes_elements.h.
References i, and t.
pshape_nst() [1/4]
template<unsigned DIM>
void QCrouzeixRaviartElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Pressure shape functions at local coordinate s.
Implements NavierStokesEquations< DIM >.
pshape_nst() [2/4]
void QCrouzeixRaviartElement< 2 >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
2D : Pressure shape functions
Implements NavierStokesEquations< DIM >.
Definition at line 2108 of file navier_stokes_elements.h.
References s.
pshape_nst() [3/4]
void QCrouzeixRaviartElement< 3 >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
3D : Pressure shape functions
Implements NavierStokesEquations< DIM >.
Definition at line 2188 of file navier_stokes_elements.h.
References s.
pshape_nst() [4/4]
template<unsigned DIM>
void QCrouzeixRaviartElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [virtual]
Pressure shape and test functions at local coordinte s.
Ppressure shape and test functions.
Implements NavierStokesEquations< DIM >.
Definition at line 2172 of file navier_stokes_elements.h.
References s.
required_nvalue()
template<unsigned DIM>
unsigned QCrouzeixRaviartElement< DIM >::required_nvalue (const unsigned & n) const [virtual]
Number of values (pinned or dofs) required at local node n.
Number of values (pinned or dofs) required at node n.
Reimplemented in oomph::BuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, and oomph::PRefineableQCrouzeixRaviartElement< DIM >.
Definition at line 2581 of file navier_stokes_elements.cc.
Member Data Documentation
Initial_Nvalue
template<unsigned DIM>
const unsigned QCrouzeixRaviartElement< DIM >::Initial_Nvalue[] [static], [private]
Static array of ints to hold required number of variables at nodes.
Definition at line 1758 of file navier_stokes_elements.h.
P_nst_internal_index
template<unsigned DIM>
unsigned QCrouzeixRaviartElement< DIM >::P_nst_internal_index [protected]
Internal index that indicates at which internal data the pressure is stored.
Definition at line 1763 of file navier_stokes_elements.h.
Referenced by oomph::PRefineableQCrouzeixRaviartElement< DIM >::fix_pressure(), oomph::RefineableQCrouzeixRaviartElement< DIM >::identify_load_data(), oomph::PRefineableQCrouzeixRaviartElement< DIM >::p_nst(), oomph::PRefineableQCrouzeixRaviartElement< DIM >::PRefineableQCrouzeixRaviartElement(), oomph::PRefineableQCrouzeixRaviartElement< DIM >::rebuild_from_sons(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::unfix_pressure(), oomph::RefineableQCrouzeixRaviartElement< DIM >::unpin_elemental_pressure_dofs(), and oomph::PRefineableQCrouzeixRaviartElement< DIM >::unpin_elemental_pressure_dofs().
The documentation for this class was generated from the following files:
navier_stokes_elements.h
navier_stokes_elements.cc