oomph::BellElementShape< 2 > Class Reference
#include <Subparametric_Telements.h>
Public Member Functions
void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
Return local coordinates of node j.
void Bshape (const Vector< double > &s, Shape &psi, DenseMatrix< double > &position) const
void dBshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DenseMatrix< double > &position) const
void d2Bshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids, DenseMatrix< double > &position) const
Detailed Description
Definition at line 65 of file Subparametric_Telements.h.
Member Function Documentation
Bshape()
void oomph::BellElementShape< 2 >::Bshape (const Vector< double > & s, Shape & psi, DenseMatrix< double > & position) const [inline]
Definition at line 102 of file Subparametric_Telements.h.
References a(), position, and s.
d2Bshape_local()
void oomph::BellElementShape< 2 >::d2Bshape_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids, DenseMatrix< double > & position) const [inline]
Definition at line 1048 of file Subparametric_Telements.h.
References a(), position, and s.
dBshape_local()
void oomph::BellElementShape< 2 >::dBshape_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DenseMatrix< double > & position) const [inline]
Definition at line 364 of file Subparametric_Telements.h.
References a(), position, and s.
local_coordinate_of_node()
void oomph::BellElementShape< 2 >::local_coordinate_of_node (const unsigned & j, Vector< double > & s) const [inline]
Return local coordinates of node j.
Definition at line 71 of file Subparametric_Telements.h.
References s.
The documentation for this class was generated from the following file:
Subparametric_Telements.h