oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE > Class Template Reference
Specific implementation of the class for specified element and node type.
#include <element_with_moving_nodes.h>
Public Member Functions
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the local dofs of the element. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
ElementWithSpecificMovingNodes ()
Constructor, call the constructor of the base element.
ElementWithSpecificMovingNodes (FiniteElement *const &element_pt, const int &face_index)
Constructor used for face elements.
~ElementWithSpecificMovingNodes ()
Empty Destructor,.
void describe_local_dofs (std::ostream &out, std::string &curr_str)
Unique final overrider for describe_dofs.
Node * construct_node (const unsigned &n)
Overload the node assignment routine to assign nodes of the appropriate type.
Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Overloaded node allocation for unsteady problems.
Node * construct_boundary_node (const unsigned &n)
Overload the node assignment routine to assign boundary nodes.
Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Overloaded boundary node allocation for unsteady problems.
void complete_setup_of_dependencies ()
Complete the setup of additional dependencies. Overloads empty virtual function in GeneralisedElement to determine the `geometric Data`, i.e. the Data that affects the element's shape. This function is called (for all elements) at the very beginning of the equation numbering procedure to ensure that all dependencies are accounted for.
void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers for the underlying element, then deal with the additional geometric dofs.
void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residuals vector and jacobian matrix.
void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Compute the element's residuals vector and jacobian matrix.
Additional Inherited Members
Detailed Description
template<class ELEMENT, class NODE_TYPE>
class oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >
Specific implementation of the class for specified element and node type.
Definition at line 380 of file element_with_moving_nodes.h.
Constructor & Destructor Documentation
ElementWithSpecificMovingNodes() [1/2]
template<class ELEMENT , class NODE_TYPE >
oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::ElementWithSpecificMovingNodes () [inline]
Constructor, call the constructor of the base element.
Definition at line 400 of file element_with_moving_nodes.h.
ElementWithSpecificMovingNodes() [2/2]
template<class ELEMENT , class NODE_TYPE >
oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::ElementWithSpecificMovingNodes (FiniteElement *const & element_pt, const int & face_index) [inline]
Constructor used for face elements.
Definition at line 403 of file element_with_moving_nodes.h.
 ElementWithSpecificMovingNodes()
template<class ELEMENT , class NODE_TYPE >
oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::~ElementWithSpecificMovingNodes () [inline]
Empty Destructor,.
Definition at line 410 of file element_with_moving_nodes.h.
Member Function Documentation
assign_all_generic_local_eqn_numbers()
template<class ELEMENT , class NODE_TYPE >
void oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::assign_all_generic_local_eqn_numbers (const bool & store_local_dof_pt) [inline], [virtual]
Assign local equation numbers for the underlying element, then deal with the additional geometric dofs.
Reimplemented from oomph::ElementWithMovingNodes.
Definition at line 497 of file element_with_moving_nodes.h.
References oomph::ElementWithMovingNodes::assign_all_generic_local_eqn_numbers().
complete_setup_of_dependencies()
template<class ELEMENT , class NODE_TYPE >
void oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::complete_setup_of_dependencies () [inline], [virtual]
Complete the setup of additional dependencies. Overloads empty virtual function in GeneralisedElement to determine the `geometric Data`, i.e. the Data that affects the element's shape. This function is called (for all elements) at the very beginning of the equation numbering procedure to ensure that all dependencies are accounted for.
Reimplemented from oomph::ElementWithMovingNodes.
Reimplemented in oomph::SpineElement< FaceGeometry< ELEMENT > >.
Definition at line 485 of file element_with_moving_nodes.h.
References oomph::ElementWithMovingNodes::complete_setup_of_dependencies().
construct_boundary_node() [1/2]
template<class ELEMENT , class NODE_TYPE >
Node * oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::construct_boundary_node (const unsigned & n) [inline], [virtual]
Overload the node assignment routine to assign boundary nodes.
Reimplemented from oomph::FiniteElement.
Definition at line 449 of file element_with_moving_nodes.h.
References oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::node_pt(), and oomph::FiniteElement::required_nvalue().
construct_boundary_node() [2/2]
template<class ELEMENT , class NODE_TYPE >
Node * oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::construct_boundary_node (const unsigned & n, TimeStepper *const & time_stepper_pt) [inline], [virtual]
Overloaded boundary node allocation for unsteady problems.
Reimplemented from oomph::FiniteElement.
Definition at line 463 of file element_with_moving_nodes.h.
References oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::required_nvalue(), and oomph::GeomObject::time_stepper_pt().
construct_node() [1/2]
template<class ELEMENT , class NODE_TYPE >
Node * oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::construct_node (const unsigned & n) [inline], [virtual]
Overload the node assignment routine to assign nodes of the appropriate type.
Reimplemented from oomph::FiniteElement.
Definition at line 422 of file element_with_moving_nodes.h.
References oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::node_pt(), and oomph::FiniteElement::required_nvalue().
construct_node() [2/2]
template<class ELEMENT , class NODE_TYPE >
Node * oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::construct_node (const unsigned & n, TimeStepper *const & time_stepper_pt) [inline], [virtual]
Overloaded node allocation for unsteady problems.
Reimplemented from oomph::FiniteElement.
Definition at line 435 of file element_with_moving_nodes.h.
References oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::required_nvalue(), and oomph::GeomObject::time_stepper_pt().
describe_local_dofs() [1/2]
template<class ELEMENT , class NODE_TYPE >
void oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::describe_local_dofs (std::ostream & out, const std::string & current_string) const [inline], [virtual]
Function to describe the local dofs of the element. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
Reimplemented from oomph::ElementWithMovingNodes.
Definition at line 392 of file element_with_moving_nodes.h.
References oomph::ElementWithMovingNodes::describe_local_dofs().
describe_local_dofs() [2/2]
template<class ELEMENT , class NODE_TYPE >
void oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::describe_local_dofs (std::ostream & out, std::string & curr_str) [inline]
Unique final overrider for describe_dofs.
Definition at line 413 of file element_with_moving_nodes.h.
References oomph::ElementWithMovingNodes::describe_local_dofs().
get_jacobian()
template<class ELEMENT , class NODE_TYPE >
void oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::get_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Compute the element's residuals vector and jacobian matrix.
Call the element's get jacobian function
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::Hijacked< SpineElement< FaceGeometry< FaceGeometry< ELEMENT > > > >, and oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >.
Definition at line 506 of file element_with_moving_nodes.h.
References oomph::ElementWithMovingNodes::fill_in_jacobian_from_geometric_data().
get_jacobian_and_mass_matrix()
template<class ELEMENT , class NODE_TYPE >
void oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::get_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) [inline], [virtual]
Compute the element's residuals vector and jacobian matrix.
Call the element's get jacobian function
Reimplemented from oomph::GeneralisedElement.
Definition at line 516 of file element_with_moving_nodes.h.
References oomph::ElementWithMovingNodes::fill_in_jacobian_from_geometric_data().
The documentation for this class was generated from the following file:
element_with_moving_nodes.h