oomph::SolidQElement< 1, NNODE_1D > Class Template Reference
SolidQElement elements, specialised to one spatial dimension.
#include <Qelements.h>
Public Member Functions
SolidQElement ()
Constructor.
SolidQElement (const SolidQElement &)=delete
Broken copy constructor.
void output (std::ostream &outfile)
Broken assignment operator.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at n_plot points.
void output (FILE *file_pt)
C-style output.
void output (FILE *file_pt, const unsigned &n_plot)
C_style output at n_plot points.
void build_face_element (const int &face_index, FaceElement *face_element_pt)
Build the lower-dimensional FaceElement (an element of type SolidQElement<0,NNODE_1D>). The face index takes one of two values corresponding to the two possible faces: -1 (Left) s[0] = -1.0 +1 (Right) s[0] = 1.0.
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::SolidQElement< 1, NNODE_1D >
SolidQElement elements, specialised to one spatial dimension.
Definition at line 1750 of file Qelements.h.
Constructor & Destructor Documentation
SolidQElement() [1/2]
template<unsigned NNODE_1D>
oomph::SolidQElement< 1, NNODE_1D >::SolidQElement () [inline]
Constructor.
Definition at line 1755 of file Qelements.h.
SolidQElement() [2/2]
template<unsigned NNODE_1D>
oomph::SolidQElement< 1, NNODE_1D >::SolidQElement (const SolidQElement< 1, NNODE_1D > &) [delete]
Broken copy constructor.
Member Function Documentation
build_face_element()
template<unsigned NNODE_1D>
void oomph::SolidQElement< 1, NNODE_1D >::build_face_element (const int & face_index, FaceElement * face_element_pt) [inline], [virtual]
Build the lower-dimensional FaceElement (an element of type SolidQElement<0,NNODE_1D>). The face index takes one of two values corresponding to the two possible faces: -1 (Left) s[0] = -1.0 +1 (Right) s[0] = 1.0.
Function to setup geometrical information for lower-dimensional FaceElements (which are of type SolidQElement<0,1>).
Reimplemented from oomph::FiniteElement.
Definition at line 1894 of file Qelements.h.
References oomph::SolidNode::nlagrangian().
output() [1/4]
template<unsigned NNODE_1D>
void oomph::SolidQElement< 1, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output.
Reimplemented from oomph::QElement< 1, NNODE_1D >.
Definition at line 1777 of file Qelements.h.
References oomph::FiniteElement::output().
output() [2/4]
template<unsigned NNODE_1D>
void oomph::SolidQElement< 1, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C_style output at n_plot points.
C-style output function for n_plot points in each coordinate direction for the 1D element.
Reimplemented from oomph::QElement< 1, NNODE_1D >.
Definition at line 1853 of file Qelements.h.
References i, and s.
output() [3/4]
template<unsigned NNODE_1D>
void oomph::SolidQElement< 1, NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Broken assignment operator.
Overload the output function
Reimplemented from oomph::QElement< 1, NNODE_1D >.
Definition at line 1768 of file Qelements.h.
References oomph::FiniteElement::output().
output() [4/4]
template<unsigned NNODE_1D>
void oomph::SolidQElement< 1, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output at n_plot points.
////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////// The output function for n_plot points in each coordinate direction for the 1D element
Reimplemented from oomph::QElement< 1, NNODE_1D >.
Definition at line 1813 of file Qelements.h.
References i, and s.
The documentation for this class was generated from the following file:
Qelements.h