oomph::ElasticRefineableQuarterPipeMesh< ELEMENT > Class Template Reference
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
#include <quarter_pipe_mesh.template.h>
Public Member Functions
ElasticRefineableQuarterPipeMesh (const unsigned &ntheta, const unsigned &nr, const unsigned &nz, const double &rmin, const double &rmax, const double &length, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass number of elements in various directions, the inner and outer radius and the length of the tube. Builds mesh and copies Eulerian coords to Lagrangian ones so that the initial configuration is the stress-free one.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::ElasticRefineableQuarterPipeMesh< ELEMENT >
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
Refineable elastic quarter pipe mesh class
Definition at line 209 of file quarter_pipe_mesh.template.h.
Constructor & Destructor Documentation
ElasticRefineableQuarterPipeMesh()
template<class ELEMENT >
oomph::ElasticRefineableQuarterPipeMesh< ELEMENT >::ElasticRefineableQuarterPipeMesh (const unsigned & ntheta, const unsigned & nr, const unsigned & nz, const double & rmin, const double & rmax, const double & length, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass number of elements in various directions, the inner and outer radius and the length of the tube. Builds mesh and copies Eulerian coords to Lagrangian ones so that the initial configuration is the stress-free one.
Definition at line 218 of file quarter_pipe_mesh.template.h.
References oomph::QuarterPipeMesh< ELEMENT >::Domain_pt, e, oomph::Mesh::element_pt(), oomph::Mesh::finite_element_pt(), oomph::TreeBasedRefineableMeshBase::Forest_pt, oomph::Domain::macro_element_pt(), oomph::Mesh::nelement(), and oomph::SimpleCubicMesh< ELEMENT >::nz().
The documentation for this class was generated from the following file:
quarter_pipe_mesh.template.h