QTaylorHoodMixedOrderSpaceTimeElement< DIM > Class Template Reference
/////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////
#include <mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h>
Public Member Functions
QTaylorHoodMixedOrderSpaceTimeElement ()
Constructor, no internal data points.
~QTaylorHoodMixedOrderSpaceTimeElement ()
virtual unsigned required_nvalue (const unsigned &n) const
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
Node * pressure_node_pt (const unsigned &n_p)
Pointer to n_p-th pressure node.
int element_node_index_to_pressure_node_index (const unsigned &n)
Helper function which deduce the pressure node index associated with elemental node n (we're assuming there's a pressure dof stored at this node!)
bool is_pressure_node (const unsigned &n) const
Helper function which indicates whether or not the provided node is a pressure node.
void shape_u_nst (const Vector< double > &s, Shape &psi) const
DRAIG: Fill in later...
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void ptest_nst (const Vector< double > &s, Shape &psi) const
Pressure test functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
virtual int p_nodal_index_nst () const
Set the value at which the pressure is stored in the nodes.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
double p_nst (const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
double p_nst (const unsigned &t, const unsigned &n_p) const
Access function for the pressure values at local pressure node n_p (const version)
unsigned npres_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
void identify_load_data (std::set< std::pair< Data *, unsigned > > &paired_load_data)
Add to the set paired_load_data pairs containing.
void identify_pressure_data (std::set< std::pair< Data *, unsigned > > &paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
void output (std::ostream &outfile)
Redirect output to NavierStokesMixedOrderEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesMixedOrderEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesMixedOrderEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to NavierStokesMixedOrderEquations output.
Protected Member Functions
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
void dshape_local_u_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
DRAIG: Fill in later...
void dtest_local_u_nst (const Vector< double > &s, Shape &test, DShape &dtestdx) const
DRAIG: Fill in later...
double dpshape_eulerian (const Vector< double > &s, Shape &ppsi, DShape &dppsidx) const
Pressure shape functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
double dptest_eulerian (const Vector< double > &s, Shape &ptest, DShape &dptestdx) const
Pressure test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
const unsigned Pconv [8]
Static Protected Attributes
static const unsigned Pconv []
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Private Member Functions
const unsigned Initial_Nvalue [27]
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Static Private Attributes
static const unsigned Initial_Nvalue []
Static array of ints to hold number of variables at node.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class QTaylorHoodMixedOrderSpaceTimeElement< DIM >
/////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////
Taylor-Hood elements are Navier-Stokes elements with quadratic interpolation for velocities and positions and continuous linear pressure interpolation. They can be used within oomph-lib's block-preconditioning framework.
Definition at line 2156 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
Constructor & Destructor Documentation
QTaylorHoodMixedOrderSpaceTimeElement()
template<unsigned DIM>
QTaylorHoodMixedOrderSpaceTimeElement< DIM >::QTaylorHoodMixedOrderSpaceTimeElement () [inline]
Constructor, no internal data points.
Definition at line 2243 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
 QTaylorHoodMixedOrderSpaceTimeElement()
template<unsigned DIM>
QTaylorHoodMixedOrderSpaceTimeElement< DIM >::~QTaylorHoodMixedOrderSpaceTimeElement () [inline]
Definition at line 2249 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
Member Function Documentation
build_fp_press_adv_diff_robin_bc_element()
template<unsigned DIM>
void QTaylorHoodMixedOrderSpaceTimeElement< DIM >::build_fp_press_adv_diff_robin_bc_element (const unsigned & face_index) [inline], [virtual]
Build FaceElements that apply the Robin boundary condition to the pressure advection diffusion problem required by Fp preconditioner.
Implements SpaceTimeNavierStokesMixedOrderEquations< DIM >.
Reimplemented in oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >.
Definition at line 2375 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
dpshape_and_dptest_eulerian_nst()
template<unsigned DIM>
double QTaylorHoodMixedOrderSpaceTimeElement< DIM >::dpshape_and_dptest_eulerian_nst (const Vector< double > & s, Shape & ppsi, DShape & dppsidx, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
Pressure shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implements SpaceTimeNavierStokesMixedOrderEquations< DIM >.
dpshape_eulerian()
template<unsigned DIM>
double QTaylorHoodMixedOrderSpaceTimeElement< DIM >::dpshape_eulerian (const Vector< double > & s, Shape & ppsi, DShape & dppsidx) const [inline], [protected], [virtual]
Pressure shape functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implements SpaceTimeNavierStokesMixedOrderEquations< DIM >.
dptest_eulerian()
template<unsigned DIM>
double QTaylorHoodMixedOrderSpaceTimeElement< DIM >::dptest_eulerian (const Vector< double > & s, Shape & ptest, DShape & dptestdx) const [inline], [protected], [virtual]
Pressure test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry). Return Jacobian of mapping between local and global coordinates.
Implements SpaceTimeNavierStokesMixedOrderEquations< DIM >.
dshape_and_dtest_eulerian_at_knot_nst() [1/2]
template<unsigned DIM>
double QTaylorHoodMixedOrderSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const [inline], [protected], [virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implements SpaceTimeNavierStokesMixedOrderEquations< DIM >.
dshape_and_dtest_eulerian_at_knot_nst() [2/2]
template<unsigned DIM>
double QTaylorHoodMixedOrderSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_at_knot_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements SpaceTimeNavierStokesMixedOrderEquations< DIM >.
Definition at line 2709 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
References i, and s.
dshape_and_dtest_eulerian_nst()
template<unsigned DIM>
double QTaylorHoodMixedOrderSpaceTimeElement< DIM >::dshape_and_dtest_eulerian_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
Velocity shape and test functions and their derivs w.r.t. to global coords at local coordinate s (taken from geometry) Return Jacobian of mapping between local and global coordinates.
Derivatives of the shape functions and test functions w.r.t to global (Eulerian) coordinates. Return Jacobian of mapping between local and global coordinates.
Implements SpaceTimeNavierStokesMixedOrderEquations< DIM >.
Definition at line 2646 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
References s.
dshape_local_u_nst()
template<unsigned DIM>
void QTaylorHoodMixedOrderSpaceTimeElement< DIM >::dshape_local_u_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx) const [inline], [protected], [virtual]
DRAIG: Fill in later...
Implements SpaceTimeNavierStokesMixedOrderEquations< DIM >.
dtest_local_u_nst()
template<unsigned DIM>
void QTaylorHoodMixedOrderSpaceTimeElement< DIM >::dtest_local_u_nst (const Vector< double > & s, Shape & test, DShape & dtestdx) const [inline], [protected], [virtual]
DRAIG: Fill in later...
Implements SpaceTimeNavierStokesMixedOrderEquations< DIM >.
element_node_index_to_pressure_node_index()
template<unsigned DIM>
int QTaylorHoodMixedOrderSpaceTimeElement< DIM >::element_node_index_to_pressure_node_index (const unsigned & n) [inline]
Helper function which deduce the pressure node index associated with elemental node n (we're assuming there's a pressure dof stored at this node!)
Definition at line 2269 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
fix_pressure()
template<unsigned DIM>
void QTaylorHoodMixedOrderSpaceTimeElement< DIM >::fix_pressure (const unsigned & p_dof, const double & p_value) [inline], [virtual]
Pin p_dof-th pressure dof and set it to value specified by p_value.
Implements SpaceTimeNavierStokesMixedOrderEquations< DIM >.
Definition at line 2361 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
identify_load_data()
template<unsigned DIM>
void QTaylorHoodMixedOrderSpaceTimeElement< DIM >::identify_load_data (std::set< std::pair< Data *, unsigned > > & paired_load_data)
Add to the set paired_load_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all values (pressures, velocities) that affect the load computed in the get_load(...) function.
Definition at line 2369 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.cc.
References i.
identify_pressure_data()
template<unsigned DIM>
void QTaylorHoodMixedOrderSpaceTimeElement< DIM >::identify_pressure_data (std::set< std::pair< Data *, unsigned > > & paired_pressure_data)
Add to the set paired_pressure_data pairs containing.
the pointer to a Data object and
the index of the value in that Data object
for all pressure values that affect the load computed in the get_load(...) function.
the pointer to a Data object and
the index of the value in that Data object
for pressure values that affect the load computed in the get_load(...) function.,
Definition at line 2411 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.cc.
Initial_Nvalue()
const unsigned QTaylorHoodMixedOrderSpaceTimeElement< 2 >::Initial_Nvalue [private]
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Definition at line 2350 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.cc.
is_pressure_node()
template<unsigned DIM>
bool QTaylorHoodMixedOrderSpaceTimeElement< DIM >::is_pressure_node (const unsigned & n) const [inline]
Helper function which indicates whether or not the provided node is a pressure node.
Definition at line 2292 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
npres_nst()
template<unsigned DIM>
unsigned QTaylorHoodMixedOrderSpaceTimeElement< DIM >::npres_nst () const [inline], [virtual]
Return number of pressure values.
Implements SpaceTimeNavierStokesMixedOrderEquations< DIM >.
Definition at line 2352 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
Referenced by oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::identify_load_data(), and oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs().
output() [1/4]
template<unsigned DIM>
void QTaylorHoodMixedOrderSpaceTimeElement< DIM >::output (FILE * file_pt) [inline]
Redirect output to NavierStokesMixedOrderEquations output.
Definition at line 2424 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
References SpaceTimeNavierStokesMixedOrderEquations< DIM >::output().
output() [2/4]
template<unsigned DIM>
void QTaylorHoodMixedOrderSpaceTimeElement< DIM >::output (FILE * file_pt, const unsigned & nplot) [inline]
Redirect output to NavierStokesMixedOrderEquations output.
Definition at line 2432 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
References SpaceTimeNavierStokesMixedOrderEquations< DIM >::output().
output() [3/4]
template<unsigned DIM>
void QTaylorHoodMixedOrderSpaceTimeElement< DIM >::output (std::ostream & outfile) [inline]
Redirect output to NavierStokesMixedOrderEquations output.
Definition at line 2408 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
References SpaceTimeNavierStokesMixedOrderEquations< DIM >::output().
output() [4/4]
template<unsigned DIM>
void QTaylorHoodMixedOrderSpaceTimeElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) [inline]
Redirect output to NavierStokesMixedOrderEquations output.
Definition at line 2416 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
References SpaceTimeNavierStokesMixedOrderEquations< DIM >::output().
p_local_eqn()
template<unsigned DIM>
int QTaylorHoodMixedOrderSpaceTimeElement< DIM >::p_local_eqn (const unsigned & n) const [inline]
Return the local equation numbers for the pressure values.
Definition at line 2326 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
p_nodal_index_nst()
template<unsigned DIM>
virtual int QTaylorHoodMixedOrderSpaceTimeElement< DIM >::p_nodal_index_nst () const [inline], [virtual]
Set the value at which the pressure is stored in the nodes.
Reimplemented from SpaceTimeNavierStokesMixedOrderEquations< DIM >.
Definition at line 2318 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
Referenced by oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::further_setup_hanging_nodes(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::identify_load_data(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs(), and oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::unpin_elemental_pressure_dofs().
p_nst() [1/2]
template<unsigned DIM>
double QTaylorHoodMixedOrderSpaceTimeElement< DIM >::p_nst (const unsigned & n_p) const [inline], [virtual]
Access function for the pressure values at local pressure node n_p (const version)
Implements SpaceTimeNavierStokesMixedOrderEquations< DIM >.
Definition at line 2335 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
p_nst() [2/2]
template<unsigned DIM>
double QTaylorHoodMixedOrderSpaceTimeElement< DIM >::p_nst (const unsigned & t, const unsigned & n_p) const [inline], [virtual]
Access function for the pressure values at local pressure node n_p (const version)
Implements SpaceTimeNavierStokesMixedOrderEquations< DIM >.
Definition at line 2344 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
References t.
Pconv()
const unsigned QTaylorHoodMixedOrderSpaceTimeElement< 2 >::Pconv [protected]
Definition at line 2356 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.cc.
pressure_node_pt()
template<unsigned DIM>
Node * QTaylorHoodMixedOrderSpaceTimeElement< DIM >::pressure_node_pt (const unsigned & n_p) [inline]
Pointer to n_p-th pressure node.
Definition at line 2260 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
pshape_nst() [1/2]
template<unsigned DIM>
void QTaylorHoodMixedOrderSpaceTimeElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
Pressure shape functions at local coordinate s.
Implements SpaceTimeNavierStokesMixedOrderEquations< DIM >.
Referenced by oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::interpolating_basis().
pshape_nst() [2/2]
template<unsigned DIM>
void QTaylorHoodMixedOrderSpaceTimeElement< DIM >::pshape_nst (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [virtual]
Pressure shape and test functions at local coordinte s.
Pressure shape and test functions.
Implements SpaceTimeNavierStokesMixedOrderEquations< DIM >.
Definition at line 3078 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
References s.
ptest_nst()
template<unsigned DIM>
void QTaylorHoodMixedOrderSpaceTimeElement< DIM >::ptest_nst (const Vector< double > & s, Shape & psi) const [inline]
Pressure test functions at local coordinate s.
required_nvalue()
template<unsigned DIM>
virtual unsigned QTaylorHoodMixedOrderSpaceTimeElement< DIM >::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values (pinned or dofs) required at node n. Can be overwritten for hanging node version.
Reimplemented in oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >.
Definition at line 2253 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
shape_u_nst()
template<unsigned DIM>
void QTaylorHoodMixedOrderSpaceTimeElement< DIM >::shape_u_nst (const Vector< double > & s, Shape & psi) const [inline], [virtual]
DRAIG: Fill in later...
Implements SpaceTimeNavierStokesMixedOrderEquations< DIM >.
Member Data Documentation
Initial_Nvalue
template<unsigned DIM>
const unsigned QTaylorHoodMixedOrderSpaceTimeElement< DIM >::Initial_Nvalue[] [static], [private]
Static array of ints to hold number of variables at node.
Definition at line 2162 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
Pconv
template<unsigned DIM>
const unsigned QTaylorHoodMixedOrderSpaceTimeElement< DIM >::Pconv[] [static], [protected]
Static array of ints to hold conversion from pressure node numbers to actual node numbers.
Definition at line 2167 of file mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h.
Referenced by oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::pressure_node_pt().
The documentation for this class was generated from the following files:
mixed_order_petrov_galerkin_space_time_navier_stokes_elements.h
mixed_order_petrov_galerkin_space_time_navier_stokes_elements.cc