oomph::AxisymQPVDElementWithPressure Class Reference
An Element that solves the Axisymmetric principle of virtual displacements with separately interpolated pressure, discontinuous interpolation.
#include <axisym_solid_elements.h>
Public Member Functions
bool has_internal_solid_data ()
There is internal solid data so we can't use the automatic assignment of consistent initial conditions for time-dependent problems.
AxisymQPVDElementWithPressure ()
Constructor, there are 3 internal data items.
double solid_p (const unsigned &l)
Return the l-th pressure value.
unsigned nsolid_pres () const
Return number of pressure values.
void fix_solid_pressure (const unsigned &l, const double &pvalue)
Fix the pressure dof l to the value pvalue.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
void output (FILE *file_pt)
Overload the output function.
void output (FILE *file_pt, const unsigned &n_plot)
Output function.
Private Member Functions
int solid_p_local_eqn (const unsigned &i)
Overload the access function for the solid pressure equation numbers.
void solid_pshape (const Vector< double > &s, Shape &psi) const
Return the pressure shape functions.
Private Attributes
unsigned P_solid_internal_index
Internal index that indicates at which internal data value the solid pressure is stored.
Additional Inherited Members
Detailed Description
An Element that solves the Axisymmetric principle of virtual displacements with separately interpolated pressure, discontinuous interpolation.
Definition at line 1348 of file axisym_solid_elements.h.
Constructor & Destructor Documentation
AxisymQPVDElementWithPressure()
oomph::AxisymQPVDElementWithPressure::AxisymQPVDElementWithPressure () [inline]
Constructor, there are 3 internal data items.
Definition at line 1374 of file axisym_solid_elements.h.
References oomph::GeneralisedElement::add_internal_data(), and P_solid_internal_index.
Member Function Documentation
fix_solid_pressure()
void oomph::AxisymQPVDElementWithPressure::fix_solid_pressure (const unsigned & l, const double & pvalue) [inline]
Fix the pressure dof l to the value pvalue.
Definition at line 1395 of file axisym_solid_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), oomph::Data::pin(), and oomph::Data::set_value().
has_internal_solid_data()
bool oomph::AxisymQPVDElementWithPressure::has_internal_solid_data () [inline], [virtual]
There is internal solid data so we can't use the automatic assignment of consistent initial conditions for time-dependent problems.
Reimplemented from oomph::SolidFiniteElement.
Definition at line 1368 of file axisym_solid_elements.h.
nsolid_pres()
unsigned oomph::AxisymQPVDElementWithPressure::nsolid_pres () const [inline], [virtual]
Return number of pressure values.
Implements oomph::AxisymmetricPVDEquationsWithPressure.
Definition at line 1389 of file axisym_solid_elements.h.
output() [1/4]
void oomph::AxisymQPVDElementWithPressure::output (FILE * file_pt) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::AxisymmetricPVDEquationsWithPressure.
Definition at line 1415 of file axisym_solid_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
void oomph::AxisymQPVDElementWithPressure::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
Output function.
Reimplemented from oomph::AxisymmetricPVDEquationsWithPressure.
Definition at line 1421 of file axisym_solid_elements.h.
References oomph::AxisymmetricPVDEquationsWithPressure::output().
output() [3/4]
void oomph::AxisymQPVDElementWithPressure::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::AxisymmetricPVDEquationsWithPressure.
Definition at line 1402 of file axisym_solid_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
void oomph::AxisymQPVDElementWithPressure::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function.
Reimplemented from oomph::AxisymmetricPVDEquationsWithPressure.
Definition at line 1408 of file axisym_solid_elements.h.
References oomph::AxisymmetricPVDEquationsWithPressure::output().
solid_p()
double oomph::AxisymQPVDElementWithPressure::solid_p (const unsigned & l) [inline], [virtual]
Return the l-th pressure value.
Implements oomph::AxisymmetricPVDEquationsWithPressure.
Definition at line 1383 of file axisym_solid_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), and oomph::Data::value().
solid_p_local_eqn()
int oomph::AxisymQPVDElementWithPressure::solid_p_local_eqn (const unsigned & i) [inline], [private], [virtual]
Overload the access function for the solid pressure equation numbers.
Implements oomph::AxisymmetricPVDEquationsWithPressure.
Definition at line 1357 of file axisym_solid_elements.h.
References i, oomph::GeneralisedElement::internal_local_eqn(), and P_solid_internal_index.
solid_pshape()
void oomph::AxisymQPVDElementWithPressure::solid_pshape (const Vector< double > & s, Shape & psi) const [inline], [private], [virtual]
Return the pressure shape functions.
Define the pressure shape functions.
Implements oomph::AxisymmetricPVDEquationsWithPressure.
Definition at line 1428 of file axisym_solid_elements.h.
References s.
Member Data Documentation
P_solid_internal_index
unsigned oomph::AxisymQPVDElementWithPressure::P_solid_internal_index [private]
Internal index that indicates at which internal data value the solid pressure is stored.
Definition at line 1354 of file axisym_solid_elements.h.
Referenced by AxisymQPVDElementWithPressure(), and solid_p_local_eqn().
The documentation for this class was generated from the following file:
axisym_solid_elements.h