oomph::RefineableLinearisedQCrouzeixRaviartElement Class Reference
/////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////
#include <refineable_linearised_navier_stokes_elements.h>
Public Member Functions
RefineableLinearisedQCrouzeixRaviartElement ()
Constructor.
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: 4*DIM (velocities)
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: Reconstruct pressure from the (merged) sons.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
Get all function values [U^C,U^S,...,P^S] at previous timestep t (t=0: present; t>0: previous timestep).
Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Note: No pressure history is kept, so pressure is always the current value.
void further_setup_hanging_nodes ()
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty.
void further_build ()
Further build for Crouzeix_Raviart interpolates the internal pressure dofs from father element: Make sure pressure values and dp/ds agree between fathers and sons at the midpoints of the son elements.
Private Member Functions
void unpin_elemental_pressure_dofs ()
Unpin all the internal pressure freedoms.
Additional Inherited Members
Detailed Description
/////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////
Refineable version of linearised axisymmetric quadratic Crouzeix-Raviart elements
Definition at line 239 of file refineable_linearised_navier_stokes_elements.h.
Constructor & Destructor Documentation
RefineableLinearisedQCrouzeixRaviartElement()
oomph::RefineableLinearisedQCrouzeixRaviartElement::RefineableLinearisedQCrouzeixRaviartElement () [inline]
Constructor.
Definition at line 262 of file refineable_linearised_navier_stokes_elements.h.
Member Function Documentation
further_build()
void oomph::RefineableLinearisedQCrouzeixRaviartElement::further_build () [inline], [virtual]
Further build for Crouzeix_Raviart interpolates the internal pressure dofs from father element: Make sure pressure values and dp/ds agree between fathers and sons at the midpoints of the son elements.
Reimplemented from oomph::RefineableLinearisedNavierStokesEquations.
Definition at line 476 of file refineable_linearised_navier_stokes_elements.h.
References oomph::Tree::father_pt(), oomph::RefineableLinearisedNavierStokesEquations::further_build(), i, oomph::GeneralisedElement::internal_data_pt(), oomph::LinearisedNavierStokesEquations::interpolated_p_linearised_nst(), oomph::QuadTreeNames::NE, oomph::QuadTreeNames::NW, oomph::Tree::object_pt(), oomph::LinearisedQCrouzeixRaviartElement::P_linearised_nst_internal_index, oomph::RefineableQElement< 2 >::quadtree_pt(), oomph::QuadTreeNames::SE, oomph::Data::set_value(), oomph::Tree::son_type(), and oomph::QuadTreeNames::SW.
further_setup_hanging_nodes()
void oomph::RefineableLinearisedQCrouzeixRaviartElement::further_setup_hanging_nodes () [inline], [virtual]
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty.
Implements oomph::RefineableQElement< 2 >.
Definition at line 470 of file refineable_linearised_navier_stokes_elements.h.
get_interpolated_values() [1/2]
void oomph::RefineableLinearisedQCrouzeixRaviartElement::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get all function values [U^C,U^S,...,P^S] at previous timestep t (t=0: present; t>0: previous timestep).
Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Note: No pressure history is kept, so pressure is always the current value.
Implements oomph::RefineableElement.
Definition at line 436 of file refineable_linearised_navier_stokes_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), t, and oomph::LinearisedNavierStokesEquations::u_index_linearised_nst().
get_interpolated_values() [2/2]
void oomph::RefineableLinearisedQCrouzeixRaviartElement::get_interpolated_values (const Vector< double > & s, Vector< double > & values) [inline], [virtual]
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
Definition at line 411 of file refineable_linearised_navier_stokes_elements.h.
References i, oomph::LinearisedNavierStokesEquations::interpolated_u_linearised_nst(), and s.
ncont_interpolated_values()
unsigned oomph::RefineableLinearisedQCrouzeixRaviartElement::ncont_interpolated_values () const [inline], [virtual]
Number of continuously interpolated values: 4*DIM (velocities)
Implements oomph::RefineableElement.
Definition at line 271 of file refineable_linearised_navier_stokes_elements.h.
nrecovery_order()
unsigned oomph::RefineableLinearisedQCrouzeixRaviartElement::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 390 of file refineable_linearised_navier_stokes_elements.h.
nvertex_node()
unsigned oomph::RefineableLinearisedQCrouzeixRaviartElement::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 396 of file refineable_linearised_navier_stokes_elements.h.
References oomph::FiniteElement::nvertex_node().
rebuild_from_sons()
void oomph::RefineableLinearisedQCrouzeixRaviartElement::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
Rebuild from sons: Reconstruct pressure from the (merged) sons.
Implements oomph::RefineableElement.
Definition at line 277 of file refineable_linearised_navier_stokes_elements.h.
References i, oomph::GeneralisedElement::internal_data_pt(), oomph::QuadTreeNames::NE, oomph::QuadTreeNames::NW, oomph::Tree::object_pt(), oomph::LinearisedQCrouzeixRaviartElement::P_linearised_nst_internal_index, oomph::RefineableQElement< 2 >::quadtree_pt(), oomph::QuadTreeNames::SE, oomph::Data::set_value(), oomph::Tree::son_pt(), oomph::QuadTreeNames::SW, and oomph::Data::value().
unpin_elemental_pressure_dofs()
void oomph::RefineableLinearisedQCrouzeixRaviartElement::unpin_elemental_pressure_dofs () [inline], [private], [virtual]
Unpin all the internal pressure freedoms.
Implements oomph::RefineableLinearisedNavierStokesEquations.
Definition at line 246 of file refineable_linearised_navier_stokes_elements.h.
References i, oomph::GeneralisedElement::internal_data_pt(), oomph::LinearisedQCrouzeixRaviartElement::npres_linearised_nst(), oomph::LinearisedQCrouzeixRaviartElement::P_linearised_nst_internal_index, and oomph::Data::unpin().
vertex_node_pt()
Node * oomph::RefineableLinearisedQCrouzeixRaviartElement::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 402 of file refineable_linearised_navier_stokes_elements.h.
References oomph::FiniteElement::vertex_node_pt().
The documentation for this class was generated from the following file:
refineable_linearised_navier_stokes_elements.h