oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D > Class Template Reference
Refineable version of QGeneralisedAxisymAdvectionDiffusionElement. Inherit from the standard QGeneralisedAxisymAdvectionDiffusionElement and the appropriate refineable geometric element and the refineable equations.
#include <refineable_gen_axisym_advection_diffusion_elements.h>
Public Member Functions
RefineableQGeneralisedAxisymAdvectionDiffusionElement ()
Empty Constructor:
RefineableQGeneralisedAxisymAdvectionDiffusionElement (const RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D > &dummy)=delete
Broken copy constructor.
unsigned ncont_interpolated_values () const
Broken assignment operator.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: empty.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
void further_setup_hanging_nodes ()
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty.
Additional Inherited Members
Detailed Description
template<unsigned NNODE_1D>
class oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >
Refineable version of QGeneralisedAxisymAdvectionDiffusionElement. Inherit from the standard QGeneralisedAxisymAdvectionDiffusionElement and the appropriate refineable geometric element and the refineable equations.
Definition at line 210 of file refineable_gen_axisym_advection_diffusion_elements.h.
Constructor & Destructor Documentation
RefineableQGeneralisedAxisymAdvectionDiffusionElement() [1/2]
template<unsigned NNODE_1D>
oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::RefineableQGeneralisedAxisymAdvectionDiffusionElement () [inline]
Empty Constructor:
Definition at line 217 of file refineable_gen_axisym_advection_diffusion_elements.h.
RefineableQGeneralisedAxisymAdvectionDiffusionElement() [2/2]
template<unsigned NNODE_1D>
oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::RefineableQGeneralisedAxisymAdvectionDiffusionElement (const RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
further_setup_hanging_nodes()
template<unsigned NNODE_1D>
void oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::further_setup_hanging_nodes () [inline], [virtual]
Perform additional hanging node procedures for variables that are not interpolated by all nodes. Empty.
Implements oomph::RefineableQElement< 2 >.
Definition at line 268 of file refineable_gen_axisym_advection_diffusion_elements.h.
ncont_interpolated_values()
template<unsigned NNODE_1D>
unsigned oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::ncont_interpolated_values () const [inline], [virtual]
Broken assignment operator.
Number of continuously interpolated values: 1
Implements oomph::RefineableElement.
Definition at line 237 of file refineable_gen_axisym_advection_diffusion_elements.h.
nrecovery_order()
template<unsigned NNODE_1D>
unsigned oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 261 of file refineable_gen_axisym_advection_diffusion_elements.h.
nvertex_node()
template<unsigned NNODE_1D>
unsigned oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 243 of file refineable_gen_axisym_advection_diffusion_elements.h.
References oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::nvertex_node().
Referenced by oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::nvertex_node().
rebuild_from_sons()
template<unsigned NNODE_1D>
void oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::rebuild_from_sons (Mesh *& mesh_pt) [inline], [virtual]
Rebuild from sons: empty.
Implements oomph::RefineableElement.
Definition at line 257 of file refineable_gen_axisym_advection_diffusion_elements.h.
vertex_node_pt()
template<unsigned NNODE_1D>
Node * oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 250 of file refineable_gen_axisym_advection_diffusion_elements.h.
References oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::vertex_node_pt().
Referenced by oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::vertex_node_pt().
The documentation for this class was generated from the following file:
refineable_gen_axisym_advection_diffusion_elements.h