oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT > Class Template Reference
#include <time_harmonic_fourier_decomposed_linear_elasticity_elements.h>
Public Member Functions
ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement ()
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Vector< std::pair< Data *, unsigned > > data_values_of_field (const unsigned &fld)
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld. In the underlying time-harmonic linear elasticity elemements the real and complex parts of the displacements are stored at the nodal values.
unsigned nfields_for_projection ()
Number of fields to be projected: 3*dim, corresponding to real and imag parts of the displacement components.
unsigned nhistory_values_for_projection (const unsigned &fld)
Number of history values to be stored for fld-th field. (includes present value!)
unsigned nhistory_values_for_coordinate_projection ()
Number of positional history values: Read out from positional timestepper (Note: count includes current value!)
double jacobian_and_shape_of_field (const unsigned &fld, const Vector< double > &s, Shape &psi)
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
double get_field (const unsigned &t, const unsigned &fld, const Vector< double > &s)
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
unsigned nvalue_of_field (const unsigned &fld)
Return number of values in field fld.
int local_equation (const unsigned &fld, const unsigned &j)
Return local equation number of value j in field fld.
Additional Inherited Members
Detailed Description
template<class TIME_HARMONIC_LINEAR_ELAST_ELEMENT>
class oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >
Fourier-decomposed time-harmonic linear elasticity upgraded to become projectable
Definition at line 651 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
Constructor & Destructor Documentation
ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement()
template<class TIME_HARMONIC_LINEAR_ELAST_ELEMENT >
oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement () [inline]
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Definition at line 657 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
Member Function Documentation
data_values_of_field()
template<class TIME_HARMONIC_LINEAR_ELAST_ELEMENT >
Vector<std::pair<Data*, unsigned> > oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::data_values_of_field (const unsigned & fld) [inline], [virtual]
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld. In the underlying time-harmonic linear elasticity elemements the real and complex parts of the displacements are stored at the nodal values.
Implements oomph::ProjectableElementBase.
Definition at line 665 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
get_field()
template<class TIME_HARMONIC_LINEAR_ELAST_ELEMENT >
double oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::get_field (const unsigned & t, const unsigned & fld, const Vector< double > & s) [inline], [virtual]
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
Implements oomph::ProjectableElementBase.
Definition at line 732 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References interpolated_u(), oomph::Node::ndim(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::Data::nvalue(), and oomph::FiniteElement::shape().
jacobian_and_shape_of_field()
template<class TIME_HARMONIC_LINEAR_ELAST_ELEMENT >
double oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::jacobian_and_shape_of_field (const unsigned & fld, const Vector< double > & s, Shape & psi) [inline], [virtual]
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
Implements oomph::ProjectableElementBase.
Definition at line 716 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References oomph::FiniteElement::dim(), oomph::FiniteElement::dshape_eulerian(), and oomph::FiniteElement::nnode().
local_equation()
template<class TIME_HARMONIC_LINEAR_ELAST_ELEMENT >
int oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::local_equation (const unsigned & fld, const unsigned & j) [inline], [virtual]
Return local equation number of value j in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 782 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References oomph::Node::ndim(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), and oomph::Data::nvalue().
nfields_for_projection()
template<class TIME_HARMONIC_LINEAR_ELAST_ELEMENT >
unsigned oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::nfields_for_projection () [inline], [virtual]
Number of fields to be projected: 3*dim, corresponding to real and imag parts of the displacement components.
Implements oomph::ProjectableElementBase.
Definition at line 684 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References oomph::FiniteElement::dim().
nhistory_values_for_coordinate_projection()
template<class TIME_HARMONIC_LINEAR_ELAST_ELEMENT >
unsigned oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::nhistory_values_for_coordinate_projection () [inline], [virtual]
Number of positional history values: Read out from positional timestepper (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 709 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), and oomph::Node::position_time_stepper_pt().
nhistory_values_for_projection()
template<class TIME_HARMONIC_LINEAR_ELAST_ELEMENT >
unsigned oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::nhistory_values_for_projection (const unsigned & fld) [inline], [virtual]
Number of history values to be stored for fld-th field. (includes present value!)
Implements oomph::ProjectableElementBase.
Definition at line 691 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::Data::ntstorage().
nvalue_of_field()
template<class TIME_HARMONIC_LINEAR_ELAST_ELEMENT >
unsigned oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::nvalue_of_field (const unsigned & fld) [inline], [virtual]
Return number of values in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 775 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References oomph::FiniteElement::nnode().
The documentation for this class was generated from the following file:
time_harmonic_fourier_decomposed_linear_elasticity_elements.h