oomph::TreeBasedRefineableMeshBase Class Reference
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
#include <refineable_mesh.h>
Classes
struct HangHelperStruct
Helper struct to collate data required during TreeBasedRefineableMeshBase::synchronise_hanging_nodes.
Public Member Functions
TreeBasedRefineableMeshBase ()
Constructor.
TreeBasedRefineableMeshBase (const TreeBasedRefineableMeshBase &dummy)=delete
Broken copy constructor.
void operator= (const TreeBasedRefineableMeshBase &)=delete
Broken assignment operator.
virtual ~TreeBasedRefineableMeshBase ()
Empty Destructor:
void adapt (const Vector< double > &elemental_error)
Adapt mesh: Refine elements whose error is lager than err_max and (try to) unrefine those whose error is smaller than err_min.
void p_adapt (const Vector< double > &elemental_error)
p-adapt mesh: Refine elements whose error is lager than err_max and (try to) unrefine those whose error is smaller than err_min
void refine_uniformly (DocInfo &doc_info)
Refine mesh uniformly and doc process.
void refine_uniformly ()
Refine mesh uniformly.
void p_refine_uniformly (DocInfo &doc_info)
p-refine mesh uniformly and doc process
void p_refine_uniformly ()
p-refine mesh uniformly
unsigned unrefine_uniformly ()
Unrefine mesh uniformly: Return 0 for success, 1 for failure (if unrefinement has reached the coarsest permitted level)
void p_unrefine_uniformly (DocInfo &doc_info)
p-unrefine mesh uniformly
virtual void setup_tree_forest ()=0
Set up the tree forest associated with the Mesh (if any)
TreeForest * forest_pt ()
Return pointer to the Forest represenation of the mesh.
void doc_adaptivity_targets (std::ostream &outfile)
Doc the targets for mesh adaptation.
unsigned & max_refinement_level ()
Access fct for max. permissible refinement level (relative to base mesh)
unsigned & min_refinement_level ()
Access fct for min. permissible refinement level (relative to base mesh)
unsigned & max_p_refinement_level ()
Access fct for max. permissible p-refinement level (relative to base mesh)
unsigned & min_p_refinement_level ()
Access fct for min. permissible p-refinement level (relative to base mesh)
virtual void adapt_mesh (DocInfo &doc_info)
Perform the actual tree-based mesh adaptation, documenting the progress in the directory specified in DocInfo object.
virtual void adapt_mesh ()
Perform the actual tree-based mesh adaptation. A simple wrapper to call the function without documentation.
void p_adapt_mesh (DocInfo &doc_info)
Perform the actual tree-based mesh p-adaptation, documenting the progress in the directory specified in DocInfo object.
void p_adapt_mesh ()
Perform the actual tree-based mesh p-adaptation. A simple wrapper to call the function without documentation.
virtual void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
Refine mesh by splitting the elements identified by their numbers.
virtual void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined)
Refine mesh by splitting the elements identified by their pointers.
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
p-refine mesh by refining the elements identified by their numbers.
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
p-refine mesh by refining the elements identified by their pointers.
virtual void refine_base_mesh_as_in_reference_mesh (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
Refine base mesh to same degree as reference mesh (relative to original unrefined mesh).
virtual bool refine_base_mesh_as_in_reference_mesh_minus_one (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
Refine base mesh to same degree as reference mesh minus one level of refinement (relative to original unrefined mesh). Useful function for multigrid solvers; allows the easy copy of a mesh to the level of refinement just below the current one.
virtual void refine_as_in_reference_mesh (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
Refine mesh once so that its topology etc becomes that of the (finer!) reference mesh -- if possible! Useful for meshes in multigrid hierarchies. If the meshes are too different and the conversion cannot be performed, the code dies (provided PARANOID is enabled).
virtual void get_refinement_levels (unsigned &min_refinement_level, unsigned &max_refinement_level)
Get max/min refinement levels in mesh.
virtual void get_elements_at_refinement_level (unsigned &refinement_level, Vector< RefineableElement * > &level_elements)
Extract the elements at a particular refinement level in the refinement pattern - used in Mesh::redistribute or whatever it's going to be called (RefineableMeshBase::reduce_halo_layers or something)
virtual void get_refinement_pattern (Vector< Vector< unsigned > > &to_be_refined)
Extract refinement pattern: Consider the hypothetical mesh obtained by truncating the refinement of the current mesh to a given level (where level=0 is the un-refined base mesh). To advance to the next refinement level, we need to refine (split) the to_be_refined[level].size() elements identified by the element numbers contained in vector to_be_refined[level][...].
void refine_base_mesh (Vector< Vector< unsigned > > &to_be_refined)
Refine base mesh according to specified refinement pattern.
virtual void refine (std::ifstream &restart_file)
Refine mesh according to refinement pattern in restart file.
virtual void dump_refinement (std::ostream &outfile)
Dump refinement pattern to allow for rebuild.
virtual void read_refinement (std::ifstream &restart_file, Vector< Vector< unsigned > > &to_be_refined)
Read refinement pattern to allow for rebuild.
unsigned uniform_refinement_level_when_pruned () const
Level to which the mesh was uniformly refined when it was pruned (const version)
unsigned & uniform_refinement_level_when_pruned ()
Level to which the mesh was uniformly refined when it was pruned.
void classify_halo_and_haloed_nodes (DocInfo &doc_info, const bool &report_stats)
Classify all halo and haloed information in the mesh (overloaded version from Mesh base class. Calls that one first, then synchronises hanging nodes)
void classify_halo_and_haloed_nodes (const bool &report_stats=false)
Classify the halo and haloed nodes in the mesh.
Protected Member Functions
void synchronise_hanging_nodes (const unsigned &ncont_interpolated_values)
Synchronise the hanging nodes if the mesh is distributed.
virtual void additional_synchronise_hanging_nodes (const unsigned &ncont_interpolated_values)=0
Additional synchronisation of hanging nodes Required for reconcilliation of hanging nodes on the outer edge of the halo layer when using elements with nonuniformly spaced nodes Must be implemented in templated derived class because ELEMENT template parameter is required for the node-creation functions in the Missing_masters_functions namespace.
void synchronise_nonhanging_nodes ()
Synchronise the positions of non-hanging nodes that depend on non-existent neighbours (e.g. h-refinement of neighbouring elements with different p-orders where the shared edge is on the outer edge of the halo layer)
virtual void split_elements_if_required ()=0
Split all the elements in the mesh if required. This template free interface will be overloaded in RefineableMesh<ELEMENT> so that any new elements that are created will be of the correct type.
virtual void p_refine_elements_if_required ()=0
p-refine all the elements in the mesh if required. This template free interface will be overloaded in RefineableMesh<ELEMENT> so that any temporary copies of the element that are created will be of the correct type.
void complete_hanging_nodes (const int &ncont_interpolated_values)
Complete the hanging node scheme recursively.
void complete_hanging_nodes_recursively (Node *&nod_pt, Vector< Node * > &master_nodes, Vector< double > &hang_weights, const int &ival)
Auxiliary routine for recursive hanging node completion.
Protected Attributes
unsigned Uniform_refinement_level_when_pruned
Level to which the mesh was uniformly refined when it was pruned.
unsigned Max_refinement_level
Max. permissible refinement level (relative to base mesh)
unsigned Min_refinement_level
Min. permissible refinement level (relative to base mesh)
unsigned Max_p_refinement_level
Max. permissible p-refinement level (relative to base mesh)
unsigned Min_p_refinement_level
Min. permissible p-refinement level (relative to base mesh)
TreeForest * Forest_pt
Forest representation of the mesh.
Additional Inherited Members
Detailed Description
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
Base class for tree-based refineable meshes.
Definition at line 375 of file refineable_mesh.h.
Constructor & Destructor Documentation
TreeBasedRefineableMeshBase() [1/2]
oomph::TreeBasedRefineableMeshBase::TreeBasedRefineableMeshBase () [inline]
Constructor.
Definition at line 379 of file refineable_mesh.h.
References oomph::RefineableMeshBase::Doc_info_pt, Forest_pt, Max_p_refinement_level, Max_refinement_level, Min_p_refinement_level, Min_refinement_level, oomph::RefineableMeshBase::Nrefined, oomph::RefineableMeshBase::Nunrefined, and Uniform_refinement_level_when_pruned.
TreeBasedRefineableMeshBase() [2/2]
oomph::TreeBasedRefineableMeshBase::TreeBasedRefineableMeshBase (const TreeBasedRefineableMeshBase & dummy) [delete]
Broken copy constructor.
 TreeBasedRefineableMeshBase()
virtual oomph::TreeBasedRefineableMeshBase::~TreeBasedRefineableMeshBase () [inline], [virtual]
Empty Destructor:
Definition at line 412 of file refineable_mesh.h.
References Forest_pt.
Member Function Documentation
adapt()
void oomph::TreeBasedRefineableMeshBase::adapt (const Vector< double > & elemental_error) [virtual]
Adapt mesh: Refine elements whose error is lager than err_max and (try to) unrefine those whose error is smaller than err_min.
Do adaptive refinement for mesh.
Pass Vector of error estimates for all elements.
Refine those whose errors exceeds the threshold
(Try to) unrefine those whose errors is less than threshold (only possible if the three brothers also want to be unrefined, of course.)
Update the nodal positions in the whole lot
Store # of refined/unrefined elements.
Doc refinement process (if required)
Implements oomph::RefineableMeshBase.
Reimplemented in oomph::RefineableQuadFromTriangleMesh< ELEMENT >.
Definition at line 307 of file refineable_mesh.cc.
References adapt_mesh(), classify_halo_and_haloed_nodes(), oomph::Mesh::Comm_pt, oomph::Mesh::delete_all_external_storage(), oomph::RefineableElement::deselect_for_refinement(), oomph::RefineableElement::deselect_sons_for_unrefinement(), oomph::DocInfo::disable_doc(), oomph::RefineableMeshBase::doc_info(), oomph::RefineableMeshBase::doc_info_pt(), e, oomph::Mesh::element_pt(), oomph::Tree::father_pt(), oomph::Mesh::halo_element_pt(), oomph::Mesh::haloed_element_pt(), oomph::DocInfo::is_doc_enabled(), oomph::Tree::is_leaf(), oomph::Mesh::is_mesh_distributed(), oomph::OcTreeNames::LDB, oomph::RefineableMeshBase::max_keep_unrefined(), oomph::RefineableMeshBase::max_permitted_error(), max_refinement_level(), oomph::RefineableMeshBase::min_permitted_error(), min_refinement_level(), oomph::Mesh::nelement(), oomph::RefineableMeshBase::Nrefined, oomph::RefineableMeshBase::nrefinement_overruled(), oomph::Tree::nsons(), oomph::RefineableMeshBase::Nunrefined, oomph::Tree::object_pt(), oomph::oomph_info, oomph::RefineableElement::refinement_is_enabled(), oomph::RefineableElement::refinement_level(), oomph::Mesh::reorder_nodes(), oomph::RefineableElement::select_for_refinement(), oomph::RefineableElement::select_sons_for_unrefinement(), oomph::Tree::son_pt(), oomph::Tree::son_type(), and oomph::RefineableElement::tree_pt().
Referenced by oomph::RefineableQuadFromTriangleMesh< ELEMENT >::adapt(), and unrefine_uniformly().
adapt_mesh() [1/2]
virtual void oomph::TreeBasedRefineableMeshBase::adapt_mesh () [inline], [virtual]
Perform the actual tree-based mesh adaptation. A simple wrapper to call the function without documentation.
Definition at line 517 of file refineable_mesh.h.
References adapt_mesh(), oomph::DocInfo::directory(), oomph::DocInfo::disable_doc(), and oomph::RefineableMeshBase::doc_info().
Referenced by adapt(), adapt_mesh(), refine_base_mesh(), refine_selected_elements(), and refine_uniformly().
adapt_mesh() [2/2]
void oomph::TreeBasedRefineableMeshBase::adapt_mesh (DocInfo & doc_info) [virtual]
Perform the actual tree-based mesh adaptation, documenting the progress in the directory specified in DocInfo object.
Adapt mesh, which exists in two representations, namely as:
a FE mesh
a forest of Oc or QuadTrees
Refinement/derefinement process is documented (in tecplot-able form) if requested.
Procedure:
Loop over all elements and do the refinement for those who want to be refined. Note: Refinement/splitting only allocates elements but doesn't build them.
Build the new elements (i.e. give them nodes (create new ones where necessary), assign boundary conditions, and add nodes to mesh and mesh boundaries.
For all nodes that were hanging on the previous mesh (and are still marked as such), fill in their nodal values (consistent with the current hanging node scheme) to make sure they are fully functional, should they have become non-hanging during the mesh-adaptation. Then mark the nodes as non-hanging.
Unrefine selected elements (which may cause nodes to be re-built).
Add the new elements to the mesh (by completely overwriting the old Vector of elements).
Delete any nodes that have become obsolete.
Mark up hanging nodes and setup hanging node scheme (incl. recursive cleanup for hanging nodes that depend on other hanging nodes).
Adjust position of hanging nodes to make sure their position is consistent with the FE-based represenetation of their larger neighbours.
run a quick self-test on the neighbour finding scheme and check the integrity of the elements (if PARANOID)
doc hanging node status, boundary conditions, neighbour scheme if requested.
After adaptation, all nodes (whether new or old) have up-to-date current and previous values.
If refinement process is being documented, the following information is documented:
The files
`neighbours.dat`
`all_nodes.dat`
`new_nodes.dat`
`hang_nodes_*.dat` where the * denotes a direction (n,s,e,w) in 2D or (r,l,u,d,f,b) in 3D
can be viewed with
QHangingNodes.mcr
The file
`hangnodes_withmasters.dat`
can be viewed with
QHangingNodesWithMasters.mcr
to check the hanging node status.
The neighbour status of the elements is documented in
`neighbours.dat`
and can be viewed with
QuadTreeNeighbours.mcr
Update the boundary element info -- this can be a costly procedure and for this reason the mesh writer might have decided not to set up this scheme. If so, we won't change this and suppress its creation...
Definition at line 926 of file refineable_mesh.cc.
References oomph::Mesh::boundary_element_pt(), oomph::TreeForest::check_all_neighbours(), classify_halo_and_haloed_nodes(), oomph::TreeForest::close_hanging_node_files(), complete_hanging_nodes(), oomph::Tree::deactivate_object(), oomph::Mesh::delete_all_external_storage(), oomph::FiniteElement::dim(), oomph::DocInfo::directory(), oomph::Global_timings::Doc_comprehensive_timings, oomph::RefineableMeshBase::doc_info(), e, oomph::Mesh::Element_pt, oomph::Mesh::finite_element_pt(), Forest_pt, oomph::Node::get_boundaries_pt(), oomph::FiniteElement::get_x(), oomph::SolidFiniteElement::get_x_and_xi(), oomph::Node::hanging_pt(), i, oomph::DocInfo::is_doc_enabled(), oomph::Node::is_hanging(), oomph::Mesh::is_mesh_distributed(), oomph::Node::is_on_boundary(), oomph::Data::is_pinned(), oomph::SolidNode::lagrangian_position(), oomph::FiniteElement::local_coordinate_of_node(), oomph::Mesh::Lookup_for_elements_next_boundary_is_setup, oomph::FiniteElement::macro_elem_pt(), oomph::HangInfo::master_node_pt(), oomph::RefineableMeshBase::max_error(), oomph::RefineableElement::max_integrity_tolerance(), oomph::Tree::merge_sons_if_required(), oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::SolidNode::nlagrangian(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::Mesh::nnode(), oomph::FiniteElement::node_pt(), oomph::Mesh::node_pt(), oomph::AlgebraicNode::node_update(), oomph::TreeForest::ntree(), oomph::Data::ntstorage(), oomph::DocInfo::number(), oomph::Data::nvalue(), oomph::oomph_info, oomph::TreeForest::open_hanging_node_files(), oomph::Node::position(), oomph::Mesh::prune_dead_nodes(), oomph::Node::raw_value(), oomph::Mesh::reorder_nodes(), s, oomph::Node::set_non_obsolete(), oomph::Node::set_nonhanging(), oomph::Node::set_obsolete(), oomph::Data::set_value(), oomph::Mesh::setup_boundary_element_info(), split_elements_if_required(), oomph::TreeForest::stick_all_tree_nodes_into_vector(), oomph::TreeForest::stick_leaves_into_vector(), t, oomph::TimingHelpers::timer(), oomph::Tree::traverse_all(), oomph::Tree::traverse_all_but_leaves(), oomph::TreeForest::tree_pt(), oomph::SolidFiniteElement::undeformed_macro_elem_pt(), oomph::Node::value(), oomph::Node::x(), and oomph::SolidNode::xi().
additional_synchronise_hanging_nodes()
virtual void oomph::TreeBasedRefineableMeshBase::additional_synchronise_hanging_nodes (const unsigned & ncont_interpolated_values) [protected], [pure virtual]
Additional synchronisation of hanging nodes Required for reconcilliation of hanging nodes on the outer edge of the halo layer when using elements with nonuniformly spaced nodes Must be implemented in templated derived class because ELEMENT template parameter is required for the node-creation functions in the Missing_masters_functions namespace.
Implemented in oomph::TreeBasedRefineableMesh< ELEMENT >.
Referenced by synchronise_hanging_nodes().
classify_halo_and_haloed_nodes() [1/2]
void oomph::TreeBasedRefineableMeshBase::classify_halo_and_haloed_nodes (const bool & report_stats = false) [inline], [virtual]
Classify the halo and haloed nodes in the mesh.
Reimplemented from oomph::Mesh.
Definition at line 699 of file refineable_mesh.h.
References classify_halo_and_haloed_nodes(), oomph::DocInfo::disable_doc(), and oomph::RefineableMeshBase::doc_info().
classify_halo_and_haloed_nodes() [2/2]
void oomph::TreeBasedRefineableMeshBase::classify_halo_and_haloed_nodes (DocInfo & doc_info, const bool & report_stats) [inline], [virtual]
Classify all halo and haloed information in the mesh (overloaded version from Mesh base class. Calls that one first, then synchronises hanging nodes)
Reimplemented from oomph::Mesh.
Definition at line 635 of file refineable_mesh.h.
References oomph::Mesh::classify_halo_and_haloed_nodes(), oomph::Mesh::Comm_pt, oomph::Global_timings::Doc_comprehensive_timings, oomph::RefineableMeshBase::doc_info(), oomph::Mesh::element_pt(), oomph::Mesh::nelement(), oomph::oomph_info, oomph::Mesh::resize_halo_nodes(), oomph::Mesh::Resize_halo_nodes_not_required, synchronise_hanging_nodes(), synchronise_nonhanging_nodes(), and oomph::TimingHelpers::timer().
Referenced by adapt(), adapt_mesh(), classify_halo_and_haloed_nodes(), p_adapt(), and p_adapt_mesh().
complete_hanging_nodes()
void oomph::TreeBasedRefineableMeshBase::complete_hanging_nodes (const int & ncont_interpolated_values) [protected]
Complete the hanging node scheme recursively.
Complete the hanging node scheme recursively. After the initial markup scheme, hanging nodes can depend on other hanging nodes ---> AAAAAAAAARGH! Need to translate this into a scheme where all hanging nodes only depend on non-hanging nodes...
Definition at line 2271 of file refineable_mesh.cc.
References complete_hanging_nodes_recursively(), oomph::Node::hanging_pt(), i, oomph::Node::is_hanging(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::oomph_info, oomph::Node::set_hanging_pt(), and oomph::HangInfo::set_master_node_pt().
Referenced by adapt_mesh(), and p_adapt_mesh().
complete_hanging_nodes_recursively()
void oomph::TreeBasedRefineableMeshBase::complete_hanging_nodes_recursively (Node *& nod_pt, Vector< Node * > & master_nodes, Vector< double > & hang_weights, const int & ival) [protected]
Auxiliary routine for recursive hanging node completion.
Given a node, return a vector of pointers to master nodes and a vector of the associated weights. This is done recursively, so if a node is not hanging, the node is regarded as its own master node which has weight 1.0.
Definition at line 2214 of file refineable_mesh.cc.
References complete_hanging_nodes_recursively(), oomph::Node::hanging_pt(), i, oomph::Node::is_hanging(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), and oomph::HangInfo::nmaster().
Referenced by complete_hanging_nodes(), and complete_hanging_nodes_recursively().
doc_adaptivity_targets()
void oomph::TreeBasedRefineableMeshBase::doc_adaptivity_targets (std::ostream & outfile) [inline], [virtual]
Doc the targets for mesh adaptation.
Reimplemented from oomph::RefineableMeshBase.
Definition at line 467 of file refineable_mesh.h.
References oomph::RefineableMeshBase::Max_keep_unrefined, Max_p_refinement_level, oomph::RefineableMeshBase::Max_permitted_error, Max_refinement_level, Min_p_refinement_level, oomph::RefineableMeshBase::Min_permitted_error, and Min_refinement_level.
dump_refinement()
void oomph::TreeBasedRefineableMeshBase::dump_refinement (std::ostream & outfile) [virtual]
Dump refinement pattern to allow for rebuild.
Definition at line 218 of file refineable_mesh.cc.
References get_refinement_pattern(), and i.
forest_pt()
TreeForest * oomph::TreeBasedRefineableMeshBase::forest_pt () [inline]
Return pointer to the Forest represenation of the mesh.
Definition at line 460 of file refineable_mesh.h.
References Forest_pt.
Referenced by get_elements_at_refinement_level(), get_refinement_pattern(), p_adapt_mesh(), and refine_as_in_reference_mesh().
get_elements_at_refinement_level()
void oomph::TreeBasedRefineableMeshBase::get_elements_at_refinement_level (unsigned & refinement_level, Vector< RefineableElement * > & level_elements) [virtual]
Extract the elements at a particular refinement level in the refinement pattern - used in Mesh::redistribute or whatever it's going to be called (RefineableMeshBase::reduce_halo_layers or something)
Extract the elements at a particular refinement level in the refinement pattern (used in Mesh::redistribute or whatever it's going to be called (RefineableMeshBase::reduce_halo_layers or something)
Definition at line 113 of file refineable_mesh.cc.
References e, forest_pt(), and oomph::TreeForest::stick_all_tree_nodes_into_vector().
Referenced by oomph::Mesh::prune_halo_elements_and_nodes().
get_refinement_levels()
void oomph::TreeBasedRefineableMeshBase::get_refinement_levels (unsigned & min_refinement_level, unsigned & max_refinement_level) [virtual]
Get max/min refinement levels in mesh.
Get max/min refinement level.
Definition at line 830 of file refineable_mesh.cc.
References e, oomph::Mesh::element_pt(), max_refinement_level(), min_refinement_level(), and oomph::Mesh::nelement().
Referenced by oomph::Problem::load_balance(), oomph::Mesh::prune_halo_elements_and_nodes(), oomph::Problem::read(), refine_as_in_reference_mesh(), refine_base_mesh(), oomph::RefineableBrickMesh< ELEMENT >::setup_octree_forest(), and oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest().
get_refinement_pattern()
void oomph::TreeBasedRefineableMeshBase::get_refinement_pattern (Vector< Vector< unsigned > > & to_be_refined) [virtual]
Extract refinement pattern: Consider the hypothetical mesh obtained by truncating the refinement of the current mesh to a given level (where level=0 is the un-refined base mesh). To advance to the next refinement level, we need to refine (split) the to_be_refined[level].size() elements identified by the element numbers contained in vector to_be_refined[level][...].
Get refinement pattern of mesh: Consider the hypothetical mesh obtained by truncating the refinement of the current mesh to a given level (where level=0 is the un-refined base mesh). To advance to the next refinement level, we need to refine (split) the to_be_refined[level].size() elements identified by the element numbers contained in vector to_be_refined[level][...].
Definition at line 50 of file refineable_mesh.cc.
References e, forest_pt(), and oomph::TreeForest::stick_all_tree_nodes_into_vector().
Referenced by dump_refinement(), oomph::Mesh::prune_halo_elements_and_nodes(), refine_base_mesh_as_in_reference_mesh(), and refine_base_mesh_as_in_reference_mesh_minus_one().
max_p_refinement_level()
unsigned & oomph::TreeBasedRefineableMeshBase::max_p_refinement_level () [inline]
Access fct for max. permissible p-refinement level (relative to base mesh)
Definition at line 499 of file refineable_mesh.h.
References Max_p_refinement_level.
Referenced by p_adapt().
max_refinement_level()
unsigned & oomph::TreeBasedRefineableMeshBase::max_refinement_level () [inline]
Access fct for max. permissible refinement level (relative to base mesh)
Definition at line 486 of file refineable_mesh.h.
References Max_refinement_level.
Referenced by adapt(), and get_refinement_levels().
min_p_refinement_level()
unsigned & oomph::TreeBasedRefineableMeshBase::min_p_refinement_level () [inline]
Access fct for min. permissible p-refinement level (relative to base mesh)
Definition at line 506 of file refineable_mesh.h.
References Min_p_refinement_level.
min_refinement_level()
unsigned & oomph::TreeBasedRefineableMeshBase::min_refinement_level () [inline]
Access fct for min. permissible refinement level (relative to base mesh)
Definition at line 492 of file refineable_mesh.h.
References Min_refinement_level.
Referenced by adapt(), and get_refinement_levels().
operator=()
void oomph::TreeBasedRefineableMeshBase::operator= (const TreeBasedRefineableMeshBase &) [delete]
Broken assignment operator.
p_adapt()
void oomph::TreeBasedRefineableMeshBase::p_adapt (const Vector< double > & elemental_error) [virtual]
p-adapt mesh: Refine elements whose error is lager than err_max and (try to) unrefine those whose error is smaller than err_min
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
Do adaptive p-refinement for mesh.
Pass Vector of error estimates for all elements.
p-refine those whose errors exceeds the threshold
p-unrefine those whose errors is less than threshold.
/ ... otherwise mark it as having been over-ruled
Reimplemented from oomph::RefineableMeshBase.
Definition at line 3951 of file refineable_mesh.cc.
References classify_halo_and_haloed_nodes(), oomph::Mesh::Comm_pt, oomph::Mesh::delete_all_external_storage(), oomph::PRefineableElement::deselect_for_p_refinement(), oomph::PRefineableElement::deselect_for_p_unrefinement(), oomph::DocInfo::disable_doc(), oomph::RefineableMeshBase::doc_info(), oomph::RefineableMeshBase::doc_info_pt(), e, oomph::Mesh::element_pt(), oomph::Mesh::halo_element_pt(), oomph::Mesh::haloed_element_pt(), oomph::PRefineableElement::initial_p_order(), oomph::DocInfo::is_doc_enabled(), oomph::Mesh::is_mesh_distributed(), oomph::RefineableMeshBase::max_keep_unrefined(), max_p_refinement_level(), oomph::RefineableMeshBase::max_permitted_error(), oomph::RefineableMeshBase::min_permitted_error(), oomph::Mesh::nelement(), oomph::RefineableMeshBase::Nrefined, oomph::RefineableMeshBase::nrefinement_overruled(), oomph::RefineableMeshBase::Nunrefined, oomph::oomph_info, p_adapt_mesh(), oomph::PRefineableElement::p_order(), oomph::PRefineableElement::p_refinement_is_enabled(), oomph::Mesh::reorder_nodes(), oomph::PRefineableElement::select_for_p_refinement(), and oomph::PRefineableElement::select_for_p_unrefinement().
p_adapt_mesh() [1/2]
void oomph::TreeBasedRefineableMeshBase::p_adapt_mesh () [inline]
Perform the actual tree-based mesh p-adaptation. A simple wrapper to call the function without documentation.
Definition at line 533 of file refineable_mesh.h.
References oomph::DocInfo::directory(), oomph::DocInfo::disable_doc(), oomph::RefineableMeshBase::doc_info(), and p_adapt_mesh().
Referenced by p_adapt(), p_adapt_mesh(), p_refine_selected_elements(), p_refine_uniformly(), and p_unrefine_uniformly().
p_adapt_mesh() [2/2]
void oomph::TreeBasedRefineableMeshBase::p_adapt_mesh (DocInfo & doc_info)
Perform the actual tree-based mesh p-adaptation, documenting the progress in the directory specified in DocInfo object.
p-adapt mesh, which exists in two representations, namely as:
a FE mesh
a forest of Oc or QuadTrees
p-refinement/derefinement process is documented (in tecplot-able form) if requested.
Procedure:
Loop over all elements and do the p-refinement/unrefinement for those who want to be refined. Note: p-refinement builds fully- functional elements.
For all nodes that were hanging on the previous mesh (and are still marked as such), fill in their nodal values (consistent with the current hanging node scheme) to make sure they are fully functional, should they have become non-hanging during the mesh-adaptation. Then mark the nodes as non-hanging.
Delete any nodes that have become obsolete.
Mark up hanging nodes and setup hanging node scheme (incl. recursive cleanup for hanging nodes that depend on other hanging nodes).
run a quick self-test on the neighbour finding scheme and check the integrity of the elements (if PARANOID)
doc hanging node status, boundary conditions, neighbour scheme if requested.
After adaptation, all nodes (whether new or old) have up-to-date current and previous values.
If refinement process is being documented, the following information is documented:
The files
`neighbours.dat`
`all_nodes.dat`
`new_nodes.dat`
`hang_nodes_*.dat` where the * denotes a direction (n,s,e,w) in 2D or (r,l,u,d,f,b) in 3D
can be viewed with
QHangingNodes.mcr
The file
`hangnodes_withmasters.dat`
can be viewed with
QHangingNodesWithMasters.mcr
to check the hanging node status.
The neighbour status of the elements is documented in
`neighbours.dat`
and can be viewed with
QuadTreeNeighbours.mcr
Update the boundary element info -- this can be a costly procedure and for this reason the mesh writer might have decided not to set up this scheme. If so, we won't change this and suppress its creation...
/BENFLAG: Check that all the nodes belong to their update elements
Definition at line 4433 of file refineable_mesh.cc.
References oomph::Mesh::boundary_element_pt(), oomph::TreeForest::check_all_neighbours(), classify_halo_and_haloed_nodes(), oomph::TreeForest::close_hanging_node_files(), complete_hanging_nodes(), oomph::Tree::deactivate_object(), oomph::Mesh::delete_all_external_storage(), oomph::PRefineableElement::deselect_for_p_refinement(), oomph::PRefineableElement::deselect_for_p_unrefinement(), oomph::FiniteElement::dim(), oomph::DocInfo::directory(), oomph::Global_timings::Doc_comprehensive_timings, oomph::RefineableMeshBase::doc_info(), e, oomph::Mesh::element_pt(), oomph::Mesh::finite_element_pt(), forest_pt(), oomph::MacroElementNodeUpdateElementBase::geom_object_pt(), oomph::Node::get_boundaries_pt(), oomph::FiniteElement::get_x(), oomph::SolidFiniteElement::get_x_and_xi(), oomph::Node::hanging_pt(), i, oomph::DocInfo::is_doc_enabled(), oomph::Node::is_hanging(), oomph::Mesh::is_mesh_distributed(), oomph::Node::is_on_boundary(), oomph::Data::is_pinned(), oomph::SolidNode::lagrangian_position(), oomph::FiniteElement::local_coordinate_of_node(), oomph::Mesh::Lookup_for_elements_next_boundary_is_setup, oomph::FiniteElement::macro_elem_pt(), oomph::HangInfo::master_node_pt(), oomph::RefineableMeshBase::max_error(), oomph::RefineableElement::max_integrity_tolerance(), oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::SolidNode::nlagrangian(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::Mesh::nnode(), oomph::FiniteElement::node_pt(), oomph::Mesh::node_pt(), oomph::AlgebraicNode::node_update(), oomph::TreeForest::ntree(), oomph::Data::ntstorage(), oomph::DocInfo::number(), oomph::Data::nvalue(), oomph::oomph_info, oomph::TreeForest::open_hanging_node_files(), p_refine_elements_if_required(), oomph::Node::position(), oomph::Mesh::prune_dead_nodes(), oomph::Node::raw_value(), oomph::Mesh::reorder_nodes(), s, oomph::MacroElementNodeUpdateElementBase::set_node_update_info(), oomph::Node::set_non_obsolete(), oomph::Node::set_nonhanging(), oomph::Node::set_obsolete(), oomph::Data::set_value(), oomph::Mesh::setup_boundary_element_info(), oomph::TreeForest::stick_all_tree_nodes_into_vector(), oomph::TreeForest::stick_leaves_into_vector(), t, oomph::TimingHelpers::timer(), oomph::Tree::traverse_all(), oomph::TreeForest::tree_pt(), oomph::SolidFiniteElement::undeformed_macro_elem_pt(), oomph::Node::value(), oomph::Node::x(), and oomph::SolidNode::xi().
p_refine_elements_if_required()
virtual void oomph::TreeBasedRefineableMeshBase::p_refine_elements_if_required () [protected], [pure virtual]
p-refine all the elements in the mesh if required. This template free interface will be overloaded in RefineableMesh<ELEMENT> so that any temporary copies of the element that are created will be of the correct type.
Implemented in oomph::TreeBasedRefineableMesh< ELEMENT >.
Referenced by p_adapt_mesh().
p_refine_selected_elements() [1/2]
void oomph::TreeBasedRefineableMeshBase::p_refine_selected_elements (const Vector< PRefineableElement * > & elements_to_be_refined_pt)
p-refine mesh by refining the elements identified by their pointers.
Definition at line 5304 of file refineable_mesh.cc.
References e, oomph::Mesh::is_mesh_distributed(), and p_adapt_mesh().
p_refine_selected_elements() [2/2]
void oomph::TreeBasedRefineableMeshBase::p_refine_selected_elements (const Vector< unsigned > & elements_to_be_refined)
p-refine mesh by refining the elements identified by their numbers.
Definition at line 5264 of file refineable_mesh.cc.
References e, oomph::Mesh::element_pt(), oomph::Mesh::is_mesh_distributed(), p_adapt_mesh(), and oomph::PRefineableElement::select_for_p_refinement().
p_refine_uniformly() [1/2]
void oomph::TreeBasedRefineableMeshBase::p_refine_uniformly () [inline], [virtual]
p-refine mesh uniformly
Reimplemented from oomph::RefineableMeshBase.
Definition at line 443 of file refineable_mesh.h.
References oomph::RefineableMeshBase::p_refine_uniformly().
p_refine_uniformly() [2/2]
void oomph::TreeBasedRefineableMeshBase::p_refine_uniformly (DocInfo & doc_info) [virtual]
p-refine mesh uniformly and doc process
p-refine mesh uniformly
Reimplemented from oomph::RefineableMeshBase.
Definition at line 1790 of file refineable_mesh.cc.
References oomph::RefineableMeshBase::doc_info(), e, oomph::Mesh::element_pt(), oomph::Mesh::nelement(), p_adapt_mesh(), and oomph::PRefineableElement::select_for_p_refinement().
p_unrefine_uniformly()
void oomph::TreeBasedRefineableMeshBase::p_unrefine_uniformly (DocInfo & doc_info)
p-unrefine mesh uniformly
p-unrefine mesh uniformly Unlike in h-refinement, we can simply p-unrefine each element in the mesh
Definition at line 5240 of file refineable_mesh.cc.
References oomph::RefineableMeshBase::doc_info(), e, oomph::Mesh::element_pt(), oomph::Mesh::nelement(), p_adapt_mesh(), and oomph::PRefineableElement::select_for_p_unrefinement().
read_refinement()
void oomph::TreeBasedRefineableMeshBase::read_refinement (std::ifstream & restart_file, Vector< Vector< unsigned > > & to_be_refined) [virtual]
Read refinement pattern to allow for rebuild.
Definition at line 251 of file refineable_mesh.cc.
References i, and oomph::Global_string_for_annotation::string().
Referenced by refine().
refine()
void oomph::TreeBasedRefineableMeshBase::refine (std::ifstream & restart_file) [virtual]
Refine mesh according to refinement pattern in restart file.
Refine base mesh according to refinement pattern in restart file.
Definition at line 201 of file refineable_mesh.cc.
References read_refinement(), and refine_base_mesh().
refine_as_in_reference_mesh()
void oomph::TreeBasedRefineableMeshBase::refine_as_in_reference_mesh (TreeBasedRefineableMeshBase *const & ref_mesh_pt) [virtual]
Refine mesh once so that its topology etc becomes that of the (finer!) reference mesh -- if possible! Useful for meshes in multigrid hierarchies. If the meshes are too different and the conversion cannot be performed, the code dies (provided PARANOID is enabled).
Definition at line 1947 of file refineable_mesh.cc.
References e, oomph::Tree::father_pt(), oomph::Mesh::finite_element_pt(), forest_pt(), get_refinement_levels(), i, oomph::Tree::is_leaf(), oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Mesh::node_pt(), oomph::Tree::nsons(), oomph::oomph_info, oomph::Mesh::output(), oomph::pause(), refine_selected_elements(), oomph::Tree::son_pt(), oomph::TreeForest::stick_leaves_into_vector(), and oomph::Node::x().
refine_base_mesh()
void oomph::TreeBasedRefineableMeshBase::refine_base_mesh (Vector< Vector< unsigned > > & to_be_refined)
Refine base mesh according to specified refinement pattern.
Refine original, unrefined mesh according to specified refinement pattern (relative to original, unrefined mesh).
Definition at line 137 of file refineable_mesh.cc.
References adapt_mesh(), oomph::Mesh::Comm_pt, oomph::Mesh::element_pt(), get_refinement_levels(), i, oomph::Mesh::is_mesh_distributed(), and unrefine_uniformly().
Referenced by refine(), refine_base_mesh_as_in_reference_mesh(), refine_base_mesh_as_in_reference_mesh_minus_one(), and oomph::Problem::refine_distributed_base_mesh().
refine_base_mesh_as_in_reference_mesh()
void oomph::TreeBasedRefineableMeshBase::refine_base_mesh_as_in_reference_mesh (TreeBasedRefineableMeshBase *const & ref_mesh_pt) [virtual]
Refine base mesh to same degree as reference mesh (relative to original unrefined mesh).
Refine to same degree as the reference mesh.
Definition at line 1885 of file refineable_mesh.cc.
References get_refinement_pattern(), and refine_base_mesh().
refine_base_mesh_as_in_reference_mesh_minus_one()
bool oomph::TreeBasedRefineableMeshBase::refine_base_mesh_as_in_reference_mesh_minus_one (TreeBasedRefineableMeshBase *const & ref_mesh_pt) [virtual]
Refine base mesh to same degree as reference mesh minus one level of refinement (relative to original unrefined mesh). Useful function for multigrid solvers; allows the easy copy of a mesh to the level of refinement just below the current one.
Refine to same degree as the reference mesh minus one. Useful function for multigrid solvers; allows the easy copy of a mesh to the level of refinement just below the current one. Returns a boolean variable which indicates if the reference mesh has not been refined at all.
Definition at line 1906 of file refineable_mesh.cc.
References get_refinement_pattern(), and refine_base_mesh().
Referenced by oomph::MGSolver< DIM >::setup_mg_hierarchy(), and oomph::HelmholtzMGPreconditioner< DIM >::setup_mg_hierarchy().
refine_selected_elements() [1/2]
void oomph::TreeBasedRefineableMeshBase::refine_selected_elements (const Vector< RefineableElement * > & elements_to_be_refined) [virtual]
Refine mesh by splitting the elements identified by their pointers.
Definition at line 1852 of file refineable_mesh.cc.
References adapt_mesh(), e, and oomph::Mesh::is_mesh_distributed().
refine_selected_elements() [2/2]
void oomph::TreeBasedRefineableMeshBase::refine_selected_elements (const Vector< unsigned > & elements_to_be_refined) [virtual]
Refine mesh by splitting the elements identified by their numbers.
Definition at line 1816 of file refineable_mesh.cc.
References adapt_mesh(), e, oomph::Mesh::element_pt(), and oomph::Mesh::is_mesh_distributed().
Referenced by refine_as_in_reference_mesh().
refine_uniformly() [1/2]
void oomph::TreeBasedRefineableMeshBase::refine_uniformly () [inline], [virtual]
Refine mesh uniformly.
Reimplemented from oomph::RefineableMeshBase.
Reimplemented in oomph::RefineableQuadFromTriangleMesh< ELEMENT >.
Definition at line 434 of file refineable_mesh.h.
References oomph::RefineableMeshBase::refine_uniformly().
refine_uniformly() [2/2]
void oomph::TreeBasedRefineableMeshBase::refine_uniformly (DocInfo & doc_info) [virtual]
Refine mesh uniformly and doc process.
Refine mesh uniformly.
Implements oomph::RefineableMeshBase.
Reimplemented in oomph::RefineableQuadFromTriangleMesh< ELEMENT >.
Definition at line 1772 of file refineable_mesh.cc.
References adapt_mesh(), oomph::RefineableMeshBase::doc_info(), e, oomph::Mesh::element_pt(), and oomph::Mesh::nelement().
Referenced by oomph::Problem::load_balance().
setup_tree_forest()
virtual void oomph::TreeBasedRefineableMeshBase::setup_tree_forest () [pure virtual]
Set up the tree forest associated with the Mesh (if any)
Implemented in oomph::RefineableBrickMesh< ELEMENT >, oomph::RefineableLineMesh< ELEMENT >, and oomph::RefineableQuadMesh< ELEMENT >.
Referenced by oomph::Mesh::distribute(), and oomph::Mesh::prune_halo_elements_and_nodes().
split_elements_if_required()
virtual void oomph::TreeBasedRefineableMeshBase::split_elements_if_required () [protected], [pure virtual]
Split all the elements in the mesh if required. This template free interface will be overloaded in RefineableMesh<ELEMENT> so that any new elements that are created will be of the correct type.
Implemented in oomph::TreeBasedRefineableMesh< ELEMENT >.
Referenced by adapt_mesh().
synchronise_hanging_nodes()
void oomph::TreeBasedRefineableMeshBase::synchronise_hanging_nodes (const unsigned & ncont_interpolated_values) [protected]
Synchronise the hanging nodes if the mesh is distributed.
Deal with nodes that are hanging on one process but not another (i.e. the hanging status of the haloed and halo layers disagrees)
Definition at line 2375 of file refineable_mesh.cc.
References additional_synchronise_hanging_nodes(), oomph::Mesh::Comm_pt, oomph::Global_timings::Doc_comprehensive_timings, oomph::Mesh::halo_node_pt(), oomph::Mesh::haloed_node_pt(), oomph::TreeBasedRefineableMeshBase::HangHelperStruct::Hang_pt, oomph::Node::hanging_pt(), i, oomph::TreeBasedRefineableMeshBase::HangHelperStruct::icont, oomph::Node::is_hanging(), oomph::TreeBasedRefineableMeshBase::HangHelperStruct::Master_node_index, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::Mesh::nhalo_node(), oomph::Mesh::nhaloed_node(), oomph::HangInfo::nmaster(), oomph::TreeBasedRefineableMeshBase::HangHelperStruct::Node_pt, oomph::Data::non_halo_proc_ID(), oomph::oomph_info, oomph::TreeBasedRefineableMeshBase::HangHelperStruct::Sending_processor, oomph::Node::set_hanging_pt(), oomph::HangInfo::set_master_node_pt(), oomph::TreeBasedRefineableMeshBase::HangHelperStruct::Shared_node_id_on_sending_processor, oomph::TreeBasedRefineableMeshBase::HangHelperStruct::Shared_node_proc, oomph::Mesh::Shared_node_pt, oomph::Mesh::shared_node_pt(), oomph::TimingHelpers::timer(), and oomph::TreeBasedRefineableMeshBase::HangHelperStruct::Weight.
Referenced by classify_halo_and_haloed_nodes().
synchronise_nonhanging_nodes()
void oomph::TreeBasedRefineableMeshBase::synchronise_nonhanging_nodes () [protected]
Synchronise the positions of non-hanging nodes that depend on non-existent neighbours (e.g. h-refinement of neighbouring elements with different p-orders where the shared edge is on the outer edge of the halo layer)
Definition at line 3650 of file refineable_mesh.cc.
References oomph::Mesh::Comm_pt, oomph::FiniteElement::dim(), oomph::Global_timings::Doc_comprehensive_timings, e, oomph::FiniteElement::get_x(), oomph::Mesh::halo_element_pt(), oomph::Mesh::haloed_element_pt(), oomph::Node::is_hanging(), oomph::FiniteElement::local_coordinate_of_node(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Data::ntstorage(), oomph::oomph_info, s, t, oomph::TimingHelpers::timer(), and oomph::Node::x().
Referenced by classify_halo_and_haloed_nodes().
uniform_refinement_level_when_pruned() [1/2]
unsigned & oomph::TreeBasedRefineableMeshBase::uniform_refinement_level_when_pruned () [inline]
Level to which the mesh was uniformly refined when it was pruned.
Definition at line 625 of file refineable_mesh.h.
References Uniform_refinement_level_when_pruned.
uniform_refinement_level_when_pruned() [2/2]
unsigned oomph::TreeBasedRefineableMeshBase::uniform_refinement_level_when_pruned () const [inline]
Level to which the mesh was uniformly refined when it was pruned (const version)
Definition at line 618 of file refineable_mesh.h.
References Uniform_refinement_level_when_pruned.
Referenced by oomph::Problem::load_balance(), and oomph::Mesh::prune_halo_elements_and_nodes().
unrefine_uniformly()
unsigned oomph::TreeBasedRefineableMeshBase::unrefine_uniformly () [virtual]
Unrefine mesh uniformly: Return 0 for success, 1 for failure (if unrefinement has reached the coarsest permitted level)
Unrefine mesh uniformly. Return 0 for success, 1 for failure (if unrefinement has reached the coarsest permitted level)
Implements oomph::RefineableMeshBase.
Definition at line 2150 of file refineable_mesh.cc.
References adapt(), e, oomph::RefineableMeshBase::max_keep_unrefined(), oomph::RefineableMeshBase::max_permitted_error(), oomph::RefineableMeshBase::min_permitted_error(), and oomph::Mesh::nelement().
Referenced by refine_base_mesh().
Member Data Documentation
Forest_pt
TreeForest* oomph::TreeBasedRefineableMeshBase::Forest_pt [protected]
Forest representation of the mesh.
Definition at line 768 of file refineable_mesh.h.
Referenced by adapt_mesh(), oomph::ElasticRefineableQuarterPipeMesh< ELEMENT >::ElasticRefineableQuarterPipeMesh(), forest_pt(), oomph::TreeBasedRefineableMesh< ELEMENT >::p_refine_elements_if_required(), oomph::RefineableEighthSphereMesh< ELEMENT >::RefineableEighthSphereMesh(), oomph::RefineableFullCircleMesh< ELEMENT >::RefineableFullCircleMesh(), oomph::RefineableQuarterPipeMesh< ELEMENT >::RefineableQuarterPipeMesh(), oomph::RefineableQuarterTubeMesh< ELEMENT >::RefineableQuarterTubeMesh(), oomph::RefineableTubeMesh< ELEMENT >::RefineableTubeMesh(), oomph::RefineableLineMesh< ELEMENT >::setup_binary_tree_forest(), oomph::RefineableBrickMesh< ELEMENT >::setup_octree_forest(), oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest(), oomph::TreeBasedRefineableMesh< ELEMENT >::split_elements_if_required(), TreeBasedRefineableMeshBase(), oomph::RefineableQuarterPipeMesh< ELEMENT >::~RefineableQuarterPipeMesh(), and ~TreeBasedRefineableMeshBase().
Max_p_refinement_level
unsigned oomph::TreeBasedRefineableMeshBase::Max_p_refinement_level [protected]
Max. permissible p-refinement level (relative to base mesh)
Definition at line 762 of file refineable_mesh.h.
Referenced by doc_adaptivity_targets(), max_p_refinement_level(), and TreeBasedRefineableMeshBase().
Max_refinement_level
unsigned oomph::TreeBasedRefineableMeshBase::Max_refinement_level [protected]
Max. permissible refinement level (relative to base mesh)
Definition at line 756 of file refineable_mesh.h.
Referenced by doc_adaptivity_targets(), max_refinement_level(), and TreeBasedRefineableMeshBase().
Min_p_refinement_level
unsigned oomph::TreeBasedRefineableMeshBase::Min_p_refinement_level [protected]
Min. permissible p-refinement level (relative to base mesh)
Definition at line 765 of file refineable_mesh.h.
Referenced by doc_adaptivity_targets(), min_p_refinement_level(), and TreeBasedRefineableMeshBase().
Min_refinement_level
unsigned oomph::TreeBasedRefineableMeshBase::Min_refinement_level [protected]
Min. permissible refinement level (relative to base mesh)
Definition at line 759 of file refineable_mesh.h.
Referenced by doc_adaptivity_targets(), min_refinement_level(), and TreeBasedRefineableMeshBase().
Uniform_refinement_level_when_pruned
unsigned oomph::TreeBasedRefineableMeshBase::Uniform_refinement_level_when_pruned [protected]
Level to which the mesh was uniformly refined when it was pruned.
Definition at line 753 of file refineable_mesh.h.
Referenced by TreeBasedRefineableMeshBase(), and uniform_refinement_level_when_pruned().
The documentation for this class was generated from the following files:
refineable_mesh.h
refineable_mesh.cc