oomph::TimeHarmonicLinearElasticityEquations< DIM > Class Template Reference
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
#include <time_harmonic_linear_elasticity_elements.h>
Public Member Functions
TimeHarmonicLinearElasticityEquations ()
Constructor.
unsigned required_nvalue (const unsigned &n) const
Number of values required at node n.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Return the residuals for the solid equations (the discretised principle of virtual displacements)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
The jacobian is calculated by finite differences by default, We need only to take finite differences w.r.t. positional variables For this element.
void get_stress (const Vector< double > &s, DenseMatrix< std::complex< double > > &sigma) const
Return the Cauchy stress tensor, as calculated from the elasticity tensor at specified local coordinate.
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact solution x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
void output (std::ostream &outfile)
Output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
void output (std::ostream &outfile, const unsigned &n_plot)
Output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
void output (FILE *file_pt)
C-style output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
void output (FILE *file_pt, const unsigned &n_plot)
Output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
void compute_norm (double &norm)
Compute norm of solution: square of the L2 norm.
Private Member Functions
virtual void fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Private helper function to compute residuals and (if requested via flag) also the Jacobian matrix.
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::TimeHarmonicLinearElasticityEquations< DIM >
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
A class for elements that solve the equations of linear elasticity in cartesian coordinates.
Definition at line 314 of file time_harmonic_linear_elasticity_elements.h.
Constructor & Destructor Documentation
TimeHarmonicLinearElasticityEquations()
template<unsigned DIM>
oomph::TimeHarmonicLinearElasticityEquations< DIM >::TimeHarmonicLinearElasticityEquations () [inline]
Constructor.
Definition at line 319 of file time_harmonic_linear_elasticity_elements.h.
Member Function Documentation
compute_norm()
template<unsigned DIM>
void oomph::TimeHarmonicLinearElasticityEquations< DIM >::compute_norm (double & norm) [virtual]
Compute norm of solution: square of the L2 norm.
Compute norm of the solution.
Reimplemented from oomph::GeneralisedElement.
Definition at line 605 of file time_harmonic_linear_elasticity_elements.cc.
References i, s, and oomph::QuadTreeNames::W.
fill_in_contribution_to_jacobian()
template<unsigned DIM>
void oomph::TimeHarmonicLinearElasticityEquations< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
The jacobian is calculated by finite differences by default, We need only to take finite differences w.r.t. positional variables For this element.
Reimplemented from oomph::FiniteElement.
Definition at line 339 of file time_harmonic_linear_elasticity_elements.h.
fill_in_contribution_to_residuals()
template<unsigned DIM>
void oomph::TimeHarmonicLinearElasticityEquations< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Return the residuals for the solid equations (the discretised principle of virtual displacements)
Reimplemented from oomph::GeneralisedElement.
Definition at line 329 of file time_harmonic_linear_elasticity_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::TimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity().
fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity()
template<unsigned DIM>
void oomph::TimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) [private], [virtual]
Private helper function to compute residuals and (if requested via flag) also the Jacobian matrix.
Compute the residuals for the linear elasticity equations in cartesian coordinates. Flag indicates if we want Jacobian too.
Reimplemented in oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >.
Definition at line 194 of file time_harmonic_linear_elasticity_elements.cc.
References oomph::QuadTreeNames::E, i, s, and oomph::QuadTreeNames::W.
Referenced by oomph::TimeHarmonicLinearElasticityEquations< DIM >::fill_in_contribution_to_residuals().
get_stress()
template<unsigned DIM>
void oomph::TimeHarmonicLinearElasticityEquations< DIM >::get_stress (const Vector< double > & s, DenseMatrix< std::complex< double > > & sigma) const [virtual]
Return the Cauchy stress tensor, as calculated from the elasticity tensor at specified local coordinate.
Compute the Cauchy stress tensor at local coordinate s for displacement formulation.
Implements oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >.
Definition at line 150 of file time_harmonic_linear_elasticity_elements.cc.
References oomph::QuadTreeNames::E, i, and s.
output() [1/4]
template<unsigned DIM>
void oomph::TimeHarmonicLinearElasticityEquations< DIM >::output (FILE * file_pt) [inline], [virtual]
C-style output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, and oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >.
Definition at line 370 of file time_harmonic_linear_elasticity_elements.h.
References oomph::TimeHarmonicLinearElasticityEquations< DIM >::output().
output() [2/4]
template<unsigned DIM>
void oomph::TimeHarmonicLinearElasticityEquations< DIM >::output (FILE * file_pt, const unsigned & n_plot) [virtual]
Output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
C-style output: x,y,[z],u,v,[w].
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, and oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >.
Definition at line 556 of file time_harmonic_linear_elasticity_elements.cc.
References i, and s.
output() [3/4]
template<unsigned DIM>
void oomph::TimeHarmonicLinearElasticityEquations< DIM >::output (std::ostream & outfile) [inline], [virtual]
Output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, and oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >.
Definition at line 359 of file time_harmonic_linear_elasticity_elements.h.
References oomph::TimeHarmonicLinearElasticityEquations< DIM >::output().
Referenced by oomph::TimeHarmonicLinearElasticityEquations< DIM >::output(), oomph::QTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >::output(), and oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >::output().
output() [4/4]
template<unsigned DIM>
void oomph::TimeHarmonicLinearElasticityEquations< DIM >::output (std::ostream & outfile, const unsigned & n_plot) [virtual]
Output: x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
Output: x,y,[z],u,v,[w].
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, and oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >.
Definition at line 504 of file time_harmonic_linear_elasticity_elements.cc.
References i, and s.
output_fct()
template<unsigned DIM>
void oomph::TimeHarmonicLinearElasticityEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact solution x,y,[z],u_r,v_r,[w_r],u_i,v_i,[w_i].
Reimplemented from oomph::FiniteElement.
Definition at line 453 of file time_harmonic_linear_elasticity_elements.cc.
References i, and s.
required_nvalue()
template<unsigned DIM>
unsigned oomph::TimeHarmonicLinearElasticityEquations< DIM >::required_nvalue (const unsigned & n) const [inline], [virtual]
Number of values required at node n.
Reimplemented from oomph::FiniteElement.
Definition at line 322 of file time_harmonic_linear_elasticity_elements.h.
The documentation for this class was generated from the following files:
time_harmonic_linear_elasticity_elements.h
time_harmonic_linear_elasticity_elements.cc