oomph::MacroElementNodeUpdateMesh Class Reference
MacroElementNodeUpdateMeshes contain MacroElementNodeUpdateNodes which have their own node update functions. When the node's node_update() function is called, they also perform any auxiliary update functions, e.g. to update no-slip boundary conditions on moving domain boundaries.
#include <macro_element_node_update_element.h>
Public Member Functions
MacroElementNodeUpdateMesh ()
Constructor (empty)
virtual ~MacroElementNodeUpdateMesh ()
Virtual destructor (empty)
MacroElementNodeUpdateMesh (const MacroElementNodeUpdateMesh &)=delete
Broken copy constructor.
Domain *& macro_domain_pt ()
Broken assignment operator.
void node_update (const bool &update_all_solid_nodes=false)
Update all nodal positions via sparse MacroElement-based update functions. If a Node is hanging its position is updated after updating the position of its masters first. [Doesn't make sense to use this mesh with SolidElements anyway, so we buffer the case if update_all_solid_nodes is set to true.].
void distribute (OomphCommunicator *comm_pt, const Vector< unsigned > &element_domain, Vector< GeneralisedElement * > &deleted_element_pt, DocInfo &doc_info, const bool &report_stats, const bool &overrule_keep_as_halo_element_status)
Overload the base class distribute function to deal with halo nodes on halo elements that may have pointers to macro elements that no longer exist.
void set_geom_object_vector_pt (Vector< GeomObject * > geom_object_vector_pt)
Set geometric objects associated with MacroElementNodeUpdateMesh; this must also be called from the constructor of each derived mesh.
Vector< GeomObject * > geom_object_vector_pt ()
Access function to the vector of GeomObject.
Private Attributes
Vector< GeomObject * > Geom_object_vector_pt
Vector of GeomObject associated with MacroElementNodeUpdateNodeMesh.
Domain * Macro_domain_pt
Domain associated with MacroElementNodeUpdateNodeMesh.
Additional Inherited Members
Detailed Description
MacroElementNodeUpdateMeshes contain MacroElementNodeUpdateNodes which have their own node update functions. When the node's node_update() function is called, they also perform any auxiliary update functions, e.g. to update no-slip boundary conditions on moving domain boundaries.
Definition at line 359 of file macro_element_node_update_element.h.
Constructor & Destructor Documentation
MacroElementNodeUpdateMesh() [1/2]
oomph::MacroElementNodeUpdateMesh::MacroElementNodeUpdateMesh () [inline]
Constructor (empty)
Definition at line 363 of file macro_element_node_update_element.h.
 MacroElementNodeUpdateMesh()
virtual oomph::MacroElementNodeUpdateMesh::~MacroElementNodeUpdateMesh () [inline], [virtual]
Virtual destructor (empty)
Definition at line 366 of file macro_element_node_update_element.h.
MacroElementNodeUpdateMesh() [2/2]
oomph::MacroElementNodeUpdateMesh::MacroElementNodeUpdateMesh (const MacroElementNodeUpdateMesh &) [delete]
Broken copy constructor.
Member Function Documentation
distribute()
void oomph::MacroElementNodeUpdateMesh::distribute (OomphCommunicator * comm_pt, const Vector< unsigned > & element_domain, Vector< GeneralisedElement * > & deleted_element_pt, DocInfo & doc_info, const bool & report_stats, const bool & overrule_keep_as_halo_element_status) [inline], [virtual]
Overload the base class distribute function to deal with halo nodes on halo elements that may have pointers to macro elements that no longer exist.
Reimplemented from oomph::Mesh.
Definition at line 465 of file macro_element_node_update_element.h.
References oomph::Mesh::distribute(), e, oomph::MacroElementNodeUpdateElementBase::geom_object_pt(), oomph::Mesh::halo_element_pt(), and oomph::MacroElementNodeUpdateElementBase::set_node_update_info().
geom_object_vector_pt()
Vector< GeomObject * > oomph::MacroElementNodeUpdateMesh::geom_object_vector_pt () [inline]
Access function to the vector of GeomObject.
Definition at line 516 of file macro_element_node_update_element.h.
References Geom_object_vector_pt.
Referenced by oomph::Multi_domain_functions::construct_new_external_halo_master_node_helper(), oomph::Missing_masters_functions::construct_new_external_halo_master_node_helper(), oomph::Multi_domain_functions::construct_new_external_halo_node_helper(), oomph::Missing_masters_functions::construct_new_external_halo_node_helper(), oomph::RefineableTriangleMesh< ELEMENT >::construct_new_halo_node_helper(), oomph::RefineableTriangleMesh< ELEMENT >::construct_new_node_load_balance_helper(), and set_geom_object_vector_pt().
macro_domain_pt()
Domain *& oomph::MacroElementNodeUpdateMesh::macro_domain_pt () [inline]
Broken assignment operator.
Access to Macro_domain_pt for MacroElementNodeUpdateMesh; this must be filled in by any mesh which inherits from here
Definition at line 376 of file macro_element_node_update_element.h.
References Macro_domain_pt.
Referenced by oomph::Multi_domain_functions::construct_new_external_halo_master_node_helper(), oomph::Missing_masters_functions::construct_new_external_halo_master_node_helper(), oomph::Multi_domain_functions::create_external_halo_elements(), oomph::MacroElementNodeUpdateChannelWithLeafletMesh< ELEMENT >::MacroElementNodeUpdateChannelWithLeafletMesh(), oomph::MacroElementNodeUpdateCollapsibleChannelMesh< ELEMENT >::MacroElementNodeUpdateCollapsibleChannelMesh(), oomph::MacroElementNodeUpdateRefineableFishMesh< ELEMENT >::MacroElementNodeUpdateRefineableFishMesh(), oomph::MacroElementNodeUpdateRefineableQuarterCircleSectorMesh< ELEMENT >::setup_macro_element_node_update(), and oomph::MacroElementNodeUpdateRefineableQuarterTubeMesh< ELEMENT >::setup_macro_element_node_update().
node_update()
void oomph::MacroElementNodeUpdateMesh::node_update (const bool & update_all_solid_nodes = false) [inline], [virtual]
Update all nodal positions via sparse MacroElement-based update functions. If a Node is hanging its position is updated after updating the position of its masters first. [Doesn't make sense to use this mesh with SolidElements anyway, so we buffer the case if update_all_solid_nodes is set to true.].
Reimplemented from oomph::Mesh.
Reimplemented in oomph::MacroElementNodeUpdateRefineableFishMesh< ELEMENT >, oomph::MacroElementNodeUpdateRefineableQuarterCircleSectorMesh< ELEMENT >, and oomph::MacroElementNodeUpdateRefineableQuarterTubeMesh< ELEMENT >.
Definition at line 387 of file macro_element_node_update_element.h.
References oomph::Mesh::External_halo_node_pt, oomph::Mesh::external_halo_node_pt(), oomph::Mesh::nexternal_halo_node(), oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::MacroElementNodeUpdateNode::node_update(), and oomph::Global_string_for_annotation::string().
Referenced by oomph::MacroElementNodeUpdateRefineableFishMesh< ELEMENT >::node_update(), oomph::MacroElementNodeUpdateRefineableQuarterCircleSectorMesh< ELEMENT >::node_update(), and oomph::MacroElementNodeUpdateRefineableQuarterTubeMesh< ELEMENT >::node_update().
set_geom_object_vector_pt()
void oomph::MacroElementNodeUpdateMesh::set_geom_object_vector_pt (Vector< GeomObject * > geom_object_vector_pt) [inline]
Set geometric objects associated with MacroElementNodeUpdateMesh; this must also be called from the constructor of each derived mesh.
Definition at line 510 of file macro_element_node_update_element.h.
References geom_object_vector_pt(), and Geom_object_vector_pt.
Referenced by oomph::MacroElementNodeUpdateChannelWithLeafletMesh< ELEMENT >::MacroElementNodeUpdateChannelWithLeafletMesh(), oomph::MacroElementNodeUpdateCollapsibleChannelMesh< ELEMENT >::MacroElementNodeUpdateCollapsibleChannelMesh(), oomph::MacroElementNodeUpdateRefineableFishMesh< ELEMENT >::MacroElementNodeUpdateRefineableFishMesh(), oomph::MacroElementNodeUpdateRefineableQuarterCircleSectorMesh< ELEMENT >::setup_macro_element_node_update(), and oomph::MacroElementNodeUpdateRefineableQuarterTubeMesh< ELEMENT >::setup_macro_element_node_update().
Member Data Documentation
Geom_object_vector_pt
Vector<GeomObject*> oomph::MacroElementNodeUpdateMesh::Geom_object_vector_pt [private]
Vector of GeomObject associated with MacroElementNodeUpdateNodeMesh.
Definition at line 524 of file macro_element_node_update_element.h.
Referenced by geom_object_vector_pt(), and set_geom_object_vector_pt().
Macro_domain_pt
Domain* oomph::MacroElementNodeUpdateMesh::Macro_domain_pt [private]
Domain associated with MacroElementNodeUpdateNodeMesh.
Definition at line 527 of file macro_element_node_update_element.h.
Referenced by macro_domain_pt().
The documentation for this class was generated from the following file:
macro_element_node_update_element.h