oomph::NavierStokesWomersleyPressureControlElement Class Reference
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
#include <womersley_elements.h>
Public Member Functions
NavierStokesWomersleyPressureControlElement (TemplateFreeWomersleyImpedanceTubeBase *womersley_tube_pt)
Constructor takes a pointer to a suitable Womersley impedance tube which defines the pressure via get_response(...)
~NavierStokesWomersleyPressureControlElement ()
Destructor should not delete anything.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
This function returns the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the Jacobian, plus the Jacobian contribution for the NetFluxControlElementForWomersleyPressureControl with respect to unknowns in this element.
Data * volume_flux_data_pt () const
Function to return a pointer to the Data object whose single value is the flux degree of freedom.
void add_pressure_data (Data *pressure_data_pt)
Function to add to external data the Data object whose single value is the pressure applied at the boundary.
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into - set to 1.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Protected Member Functions
void fill_in_generic_residual_contribution_pressure_control (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
This function returns the residuals. flag=1(or 0): do (or don't) compute the Jacobian as well. Note that this function also calculates the Jacobian contribution for the NetFluxControlElementForWomersleyPressureControl.
Private Attributes
Data * Volume_flux_data_pt
Data object whose single value is the volume flux applied by the elements in the Flux_control_mesh_pt.
TemplateFreeWomersleyImpedanceTubeBase * Womersley_tube_pt
Pointer to the Womersley impedance tube.
unsigned Pressure_data_id
Id of external Data object whose single value is the pressure.
unsigned Volume_flux_data_id
Id of internal Data object whose single value is the volume flux.
Additional Inherited Members
Detailed Description
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
An element to impose a fluid pressure obtained from a Womersley impedance tube at a boundary. This element is used in conjunction with a NetFluxControlElementForWomersleyPressureControl element, and is passed to the NetFluxControlElementForWomersleyPressureControl element's constructor. The volume flux across the boundary is then an unknown of the problem. The constructor argument for this element is a suitable Womersley impedance tube to give the pressure via its get_response(...) function.
Note: the NavierStokesWomersleyPressureControlElement element calculates Jacobian entries BOTH for itself AND for the NetFluxControlElementForWomersleyPressureControl with respect to the unknowns in this (NavierStokesWomersleyPressureControlElement) element.
Definition at line 2579 of file womersley_elements.h.
Constructor & Destructor Documentation
NavierStokesWomersleyPressureControlElement()
oomph::NavierStokesWomersleyPressureControlElement::NavierStokesWomersleyPressureControlElement (TemplateFreeWomersleyImpedanceTubeBase * womersley_tube_pt) [inline]
Constructor takes a pointer to a suitable Womersley impedance tube which defines the pressure via get_response(...)
Definition at line 2585 of file womersley_elements.h.
References oomph::GeneralisedElement::add_internal_data(), Volume_flux_data_id, and Volume_flux_data_pt.
 NavierStokesWomersleyPressureControlElement()
oomph::NavierStokesWomersleyPressureControlElement::~NavierStokesWomersleyPressureControlElement () [inline]
Destructor should not delete anything.
Definition at line 2597 of file womersley_elements.h.
Member Function Documentation
add_pressure_data()
void oomph::NavierStokesWomersleyPressureControlElement::add_pressure_data (Data * pressure_data_pt) [inline]
Function to add to external data the Data object whose single value is the pressure applied at the boundary.
Definition at line 2628 of file womersley_elements.h.
References oomph::GeneralisedElement::add_external_data(), and Pressure_data_id.
Referenced by oomph::NetFluxControlElementForWomersleyPressureControl::NetFluxControlElementForWomersleyPressureControl().
fill_in_contribution_to_jacobian()
void oomph::NavierStokesWomersleyPressureControlElement::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
This function returns the residuals and the Jacobian, plus the Jacobian contribution for the NetFluxControlElementForWomersleyPressureControl with respect to unknowns in this element.
Reimplemented from oomph::GeneralisedElement.
Definition at line 2611 of file womersley_elements.h.
References fill_in_generic_residual_contribution_pressure_control().
fill_in_contribution_to_residuals()
void oomph::NavierStokesWomersleyPressureControlElement::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
This function returns the residuals.
Reimplemented from oomph::GeneralisedElement.
Definition at line 2600 of file womersley_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_pressure_control().
fill_in_generic_residual_contribution_pressure_control()
void oomph::NavierStokesWomersleyPressureControlElement::fill_in_generic_residual_contribution_pressure_control (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [inline], [protected]
This function returns the residuals. flag=1(or 0): do (or don't) compute the Jacobian as well. Note that this function also calculates the Jacobian contribution for the NetFluxControlElementForWomersleyPressureControl.
Definition at line 2664 of file womersley_elements.h.
References oomph::GeneralisedElement::external_data_pt(), oomph::GeneralisedElement::external_local_eqn(), oomph::TemplateFreeWomersleyImpedanceTubeBase::get_response(), oomph::GeneralisedElement::internal_local_eqn(), Pressure_data_id, oomph::Data::value(), Volume_flux_data_id, and Womersley_tube_pt.
Referenced by fill_in_contribution_to_jacobian(), and fill_in_contribution_to_residuals().
get_dof_numbers_for_unknowns()
void oomph::NavierStokesWomersleyPressureControlElement::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [inline], [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Reimplemented from oomph::GeneralisedElement.
Definition at line 2646 of file womersley_elements.h.
References oomph::GeneralisedElement::eqn_number().
ndof_types()
unsigned oomph::NavierStokesWomersleyPressureControlElement::ndof_types () const [inline], [virtual]
The number of `DOF types` that degrees of freedom in this element are sub-divided into - set to 1.
Reimplemented from oomph::GeneralisedElement.
Definition at line 2635 of file womersley_elements.h.
volume_flux_data_pt()
Data * oomph::NavierStokesWomersleyPressureControlElement::volume_flux_data_pt () const [inline]
Function to return a pointer to the Data object whose single value is the flux degree of freedom.
Definition at line 2621 of file womersley_elements.h.
References Volume_flux_data_pt.
Member Data Documentation
Pressure_data_id
unsigned oomph::NavierStokesWomersleyPressureControlElement::Pressure_data_id [private]
Id of external Data object whose single value is the pressure.
Definition at line 2708 of file womersley_elements.h.
Referenced by add_pressure_data(), and fill_in_generic_residual_contribution_pressure_control().
Volume_flux_data_id
unsigned oomph::NavierStokesWomersleyPressureControlElement::Volume_flux_data_id [private]
Id of internal Data object whose single value is the volume flux.
Definition at line 2712 of file womersley_elements.h.
Referenced by fill_in_generic_residual_contribution_pressure_control(), and NavierStokesWomersleyPressureControlElement().
Volume_flux_data_pt
Data* oomph::NavierStokesWomersleyPressureControlElement::Volume_flux_data_pt [private]
Data object whose single value is the volume flux applied by the elements in the Flux_control_mesh_pt.
Definition at line 2702 of file womersley_elements.h.
Referenced by NavierStokesWomersleyPressureControlElement(), and volume_flux_data_pt().
Womersley_tube_pt
TemplateFreeWomersleyImpedanceTubeBase* oomph::NavierStokesWomersleyPressureControlElement::Womersley_tube_pt [private]
Pointer to the Womersley impedance tube.
Definition at line 2705 of file womersley_elements.h.
Referenced by fill_in_generic_residual_contribution_pressure_control().
The documentation for this class was generated from the following file:
womersley_elements.h