oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT > Class Template Reference
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
#include <pml_fourier_decomposed_helmholtz_elements.h>
Public Member Functions
ProjectablePMLFourierDecomposedHelmholtzElement ()
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Vector< std::pair< Data *, unsigned > > data_values_of_field (const unsigned &fld)
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld.
unsigned nfields_for_projection ()
Number of fields to be projected: 2 (real and imag part)
unsigned nhistory_values_for_projection (const unsigned &fld)
Number of history values to be stored for fld-th field. (Note: count includes current value!)
unsigned nhistory_values_for_coordinate_projection ()
Number of positional history values (Note: count includes current value!)
double jacobian_and_shape_of_field (const unsigned &fld, const Vector< double > &s, Shape &psi)
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
double get_field (const unsigned &t, const unsigned &fld, const Vector< double > &s)
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
unsigned nvalue_of_field (const unsigned &fld)
Return number of values in field fld: One per node.
int local_equation (const unsigned &fld, const unsigned &j)
Return local equation number of value j in field fld.
void output (std::ostream &outfile, const unsigned &nplot)
Output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points.
Additional Inherited Members
Detailed Description
template<class FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT>
class oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Fourier decomposed Helmholtz upgraded to become projectable
Definition at line 900 of file pml_fourier_decomposed_helmholtz_elements.h.
Constructor & Destructor Documentation
ProjectablePMLFourierDecomposedHelmholtzElement()
template<class FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >
oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::ProjectablePMLFourierDecomposedHelmholtzElement () [inline]
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Definition at line 906 of file pml_fourier_decomposed_helmholtz_elements.h.
Member Function Documentation
data_values_of_field()
template<class FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >
Vector< std::pair< Data *, unsigned > > oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::data_values_of_field (const unsigned & fld) [inline], [virtual]
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld.
Implements oomph::ProjectableElementBase.
Definition at line 911 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
get_field()
template<class FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >
double oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::get_field (const unsigned & t, const unsigned & fld, const Vector< double > & s) [inline], [virtual]
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
Implements oomph::ProjectableElementBase.
Definition at line 999 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), and oomph::FiniteElement::shape().
jacobian_and_shape_of_field()
template<class FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >
double oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::jacobian_and_shape_of_field (const unsigned & fld, const Vector< double > & s, Shape & psi) [inline], [virtual]
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
Implements oomph::ProjectableElementBase.
Definition at line 972 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::dim(), oomph::FiniteElement::nnode(), and s.
local_equation()
template<class FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >
int oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::local_equation (const unsigned & fld, const unsigned & j) [inline], [virtual]
Return local equation number of value j in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 1064 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::nodal_local_eqn().
nfields_for_projection()
template<class FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >
unsigned oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::nfields_for_projection () [inline], [virtual]
Number of fields to be projected: 2 (real and imag part)
Implements oomph::ProjectableElementBase.
Definition at line 941 of file pml_fourier_decomposed_helmholtz_elements.h.
nhistory_values_for_coordinate_projection()
template<class FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >
unsigned oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::nhistory_values_for_coordinate_projection () [inline], [virtual]
Number of positional history values (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 965 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), and oomph::Node::position_time_stepper_pt().
nhistory_values_for_projection()
template<class FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >
unsigned oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::nhistory_values_for_projection (const unsigned & fld) [inline], [virtual]
Number of history values to be stored for fld-th field. (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 948 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::Data::ntstorage().
nvalue_of_field()
template<class FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >
unsigned oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::nvalue_of_field (const unsigned & fld) [inline], [virtual]
Return number of values in field fld: One per node.
Implements oomph::ProjectableElementBase.
Definition at line 1047 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::FiniteElement::nnode().
output()
template<class FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >
void oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 1093 of file pml_fourier_decomposed_helmholtz_elements.h.
References oomph::CommandLineArgs::output().
The documentation for this class was generated from the following file:
pml_fourier_decomposed_helmholtz_elements.h