oomph::RefineableTriangleMesh< ELEMENT > Class Template Reference
Unstructured refineable Triangle Mesh.
#include <triangle_mesh.h>
Public Types
typedef void(* MeshUpdateFctPt) (Mesh *mesh_pt)
Function pointer to function that updates the mesh following the snapping of boundary nodes to the boundaries (e.g. to move boundary nodes very slightly to satisfy volume constraints)
typedef void(* InternalHolePointUpdateFctPt) (const unsigned &ihole, TriangleMeshPolygon *poly_pt)
Function pointer to a function that can generate a point within the ihole-th hole, so that this can be overloaded by the user if they have a better way of doing it than our clunky default. The function should update the components of the Vector poly_pt->internal_point()
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
Typedef for function pointer to function that computes steady exact solution.
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Typedef for function pointer to function that computes unsteady exact solution.
Public Member Functions
RefineableTriangleMesh (TriangleMeshParameters &triangle_mesh_parameters, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Build mesh, based on the specifications on TriangleMeshParameters.
RefineableTriangleMesh (const std::string &node_file_name, const std::string &element_file_name, const std::string &poly_file_name, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &allow_automatic_creation_of_vertices_on_boundaries=true)
Build mesh, based on the polyfiles.
virtual ~RefineableTriangleMesh ()
Empty Destructor.
void enable_timings_tranfering_target_areas ()
Enables info. and timings for tranferring of target areas.
void disable_timings_tranfering_target_areas ()
Disables info. and timings for tranferring of target areas.
void enable_projection ()
Enables the solution projection step during adaptation.
void disable_projection ()
Disables the solution projection step during adaptation.
void enable_timings_projection ()
Enables info. and timings for projection.
void disable_timings_projection ()
Disables info. and timings for projection.
unsigned & nbin_x_for_area_transfer ()
Read/write access to number of bins in the x-direction when transferring target areas by bin method. Only used if we don't have CGAL!
unsigned & nbin_y_for_area_transfer ()
Read/write access to number of bins in the y-direction when transferring target areas by bin method. Only used if we don't have CGAL!
unsigned max_sample_points_for_limited_locate_zeta_during_target_area_transfer ()
Read/write access to number of sample points from which we try to locate zeta by Newton method when transferring target areas using cgal-based sample point container. If Newton method doesn't converge from any of these we use the nearest sample point.
double & max_element_size ()
Max element size allowed during adaptation.
double & min_element_size ()
Min element size allowed during adaptation.
double & min_permitted_angle ()
Min angle before remesh gets triggered.
bool use_iterative_solver_for_projection ()
void enable_iterative_solver_for_projection ()
Enables the use of an iterative solver for the projection problem.
void disable_iterative_solver_for_projection ()
Enables the use of an iterative solver for the projection problem.
void enable_print_timings_adaptation (const unsigned &print_level=1)
Enables printing of timings for adaptation.
void disable_print_timings_adaptation ()
Disables printing of timings for adaptation.
void set_print_level_timings_adaptation (const unsigned &print_level)
Sets the printing level of timings for adaptation.
void enable_print_timings_load_balance (const unsigned &print_level=1)
Enables printing of timings for load balance.
void disable_print_timings_load_balance ()
Disables printing of timings for load balance.
void set_print_level_timings_load_balance (const unsigned &print_level)
Sets the printing level of timings for load balance.
void doc_adaptivity_targets (std::ostream &outfile)
Doc the targets for mesh adaptation.
void refine_uniformly (DocInfo &doc_info)
Refine mesh uniformly and doc process.
unsigned unrefine_uniformly ()
Unrefine mesh uniformly: Return 0 for success, 1 for failure (if unrefinement has reached the coarsest permitted level)
void adapt (const Vector< double > &elem_error)
Adapt mesh, based on elemental error provided.
MeshUpdateFctPt & mesh_update_fct_pt ()
Access to function pointer to function that updates the mesh following the snapping of boundary nodes to the boundaries (e.g. to move boundary nodes very slightly to satisfy volume constraints)
InternalHolePointUpdateFctPt & internal_hole_point_update_fct_pt ()
Access to function pointer to can be used to generate the internal point for the ihole-th hole.
unsigned nsorted_shared_boundary_node (unsigned &b)
void flush_sorted_shared_boundary_node ()
Node * sorted_shared_boundary_node_pt (unsigned &b, unsigned &i)
Vector< Node * > sorted_shared_boundary_node_pt (unsigned &b)
void create_polylines_from_polyfiles (const std::string &node_file_name, const std::string &poly_file_name)
Helper function to create polylines and fill associate data.
void fill_boundary_elements_and_nodes_for_internal_boundaries ()
void fill_boundary_elements_and_nodes_for_internal_boundaries (std::ofstream &outfile)
void reestablish_distribution_info_for_restart (OomphCommunicator *comm_pt, std::istream &restart_file)
Used to re-establish any additional info. related with the distribution after a re-starting for triangle meshes.
void update_polyline_representation_from_restart ()
Method used to update the polylines representation after restart.
void load_balance (const Vector< unsigned > &input_target_domain_for_local_non_halo_element)
Performs the load balancing for unstructured meshes, the load balancing strategy is based on mesh migration.
void get_shared_boundary_elements_and_face_indexes (const Vector< FiniteElement * > &first_element_pt, const Vector< FiniteElement * > &second_element_pt, Vector< FiniteElement * > &first_shared_boundary_element_pt, Vector< unsigned > &first_shared_boundary_element_face_index, Vector< FiniteElement * > &second_shared_boundary_element_pt, Vector< unsigned > &second_shared_boundary_element_face_index)
Use the first and second group of elements to find the intersection between them to get the shared boundary elements from the first and second group.
void create_new_shared_boundaries (std::set< FiniteElement * > &element_in_processor_pt, Vector< Vector< FiniteElement * > > &new_shared_boundary_element_pt, Vector< Vector< unsigned > > &new_shared_boundary_element_face_index)
Creates the new shared boundaries, this method is also in charge of computing the shared boundaries ids of each processor and send that info. to all the processors.
void compute_shared_node_degree_helper (Vector< Vector< FiniteElement * > > &unsorted_face_ele_pt, std::map< Node *, unsigned > &global_node_degree)
Computes the degree of the nodes on the shared boundaries, the degree of the node is computed from the global graph created by the shared boundaries of all processors.
void create_adjacency_matrix_new_shared_edges_helper (Vector< Vector< FiniteElement * > > &unsorted_face_ele_pt, Vector< Vector< Node * > > &tmp_sorted_shared_node_pt, std::map< Node *, Vector< Vector< unsigned > > > &node_alias, Vector< Vector< Vector< unsigned > > > &adjacency_matrix)
Sort the nodes on the new shared boundaries (after load balancing), computes the alias of the nodes and creates the adjacency matrix that represent the graph created by the shared edges between each pair of processors.
void get_shared_boundary_segment_nodes_helper (const unsigned &shd_bnd_id, Vector< Vector< Node * > > &tmp_segment_nodes)
Get the nodes on the shared boundary (b), these are stored in the segment they belong.
void get_boundary_segment_nodes_helper (const unsigned &b, Vector< Vector< Node * > > &tmp_segment_nodes)
Get the nodes on the boundary (b), these are stored in the segment they belong (also used by the load balance method to re-set the number of segments per boundary after load balance has taken place)
void enable_boundary_unrefinement_constrained_by_target_areas ()
Enable/disable unrefinement/refinement methods for original boundaries.
void disable_boundary_unrefinement_constrained_by_target_areas ()
void enable_boundary_refinement_constrained_by_target_areas ()
void disable_boundary_refinement_constrained_by_target_areas ()
void enable_shared_boundary_unrefinement_constrained_by_target_areas ()
Enable/disable unrefinement/refinement methods for shared boundaries.
void disable_shared_boundary_unrefinement_constrained_by_target_areas ()
void enable_shared_boundary_refinement_constrained_by_target_areas ()
void disable_shared_boundary_refinement_constrained_by_target_areas ()
Public Member Functions inherited from oomph::TriangleMesh< ELEMENT >
TriangleMesh ()
Empty constructor.
TriangleMesh (const std::string &node_file_name, const std::string &element_file_name, const std::string &poly_file_name, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &allow_automatic_creation_of_vertices_on_boundaries=true)
Constructor with the input files.
TriangleMesh (TriangleMeshParameters &triangle_mesh_parameters, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Build mesh, based on the specifications on TriangleMeshParameters.
TriangleMesh (const std::string &poly_file_name, const double &element_area, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &allow_automatic_creation_of_vertices_on_boundaries=true)
Build mesh from poly file, with specified target area for all elements.
TriangleMesh (const TriangleMesh &dummy)=delete
Broken copy constructor.
void operator= (const TriangleMesh &)=delete
Broken assignment operator.
virtual ~TriangleMesh ()
Destructor.
void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Overload set_mesh_level_time_stepper so that the stored time stepper now corresponds to the new timestepper.
void compute_boundary_segments_connectivity_and_initial_zeta_values (const unsigned &b)
Compute the boundary segments connectivity for those boundaries that were splited during the distribution process.
void re_assign_initial_zeta_values_for_internal_boundary (const unsigned &b, Vector< std::list< FiniteElement * > > &old_segment_sorted_ele_pt, std::map< FiniteElement *, bool > &old_is_inverted)
Re-assign the boundary segments initial zeta (arclength) value for those internal boundaries that were splited during the distribution process. Those boundaries that have one face element at each side of the boundary.
void re_scale_re_assigned_initial_zeta_values_for_internal_boundary (const unsigned &b)
Re-scale the re-assigned zeta values for the boundary nodes, apply only for internal boundaries.
void identify_boundary_segments_and_assign_initial_zeta_values (const unsigned &b, Vector< FiniteElement * > &input_face_ele_pt, const bool &is_internal_boundary, std::map< FiniteElement *, FiniteElement * > &face_to_bulk_element_pt)
Identify the segments from the old mesh (original mesh) in the new mesh (this) and assign initial and final boundary coordinates for the segments that create the boundary. (This is the version called from the original mesh to identify its own segments)
void identify_boundary_segments_and_assign_initial_zeta_values (const unsigned &b, TriangleMesh< ELEMENT > *original_mesh_pt)
Identify the segments from the old mesh (original mesh) in the new mesh (this) and assign initial and final boundary coordinates for the segments that create the boundary.
void synchronize_boundary_coordinates (const unsigned &b)
In charge of sinchronize the boundary coordinates for internal boundaries that were split as part of the distribution process. Called after setup_boundary_coordinates() for the original mesh only.
void select_boundary_face_elements (Vector< FiniteElement * > &face_el_pt, const unsigned &b, bool &is_internal_boundary, std::map< FiniteElement *, FiniteElement * > &face_to_bulk_element_pt)
Select face element from boundary using the criteria to decide which of the two face elements should be used on internal boundaries.
Vector< Vector< Node * > > & boundary_segment_node_pt (const unsigned &b)
Return direct access to nodes associated with a boundary but sorted in segments.
Vector< Node * > & boundary_segment_node_pt (const unsigned &b, const unsigned &s)
Return direct access to nodes associated with a segment of a given boundary.
Node *& boundary_segment_node_pt (const unsigned &b, const unsigned &s, const unsigned &n)
Return pointer to node n on boundary b.
void update_triangulateio (Vector< Vector< double > > &internal_point)
Update the TriangulateIO object to the current nodal position and the centre hole coordinates.
void update_triangulateio ()
Update the triangulateio object to the current nodal positions.
void dump_distributed_info_for_restart (std::ostream &dump_file)
Used to dump info. related with distributed triangle meshes.
const unsigned read_unsigned_line_helper (std::istream &read_file)
void read_distributed_info_for_restart (std::istream &restart_file)
Used to read info. related with distributed triangle meshes.
void remesh_from_internal_triangulateio ()
Completely regenerate the mesh from the trianglateio structure.
bool triangulateio_exists ()
Boolean defining if Triangulateio object has been built or not.
Vector< unsigned > oomph_vertex_nodes_id ()
Return the vector that contains the oomph-lib node number for all vertex nodes in the TriangulateIO representation of the mesh.
const unsigned initial_shared_boundary_id ()
The initial boundary id for shared boundaries.
const unsigned final_shared_boundary_id ()
The final boundary id for shared boundaries.
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned > > &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info routines. Generally used after load balance.
void output_boundary_coordinates (const unsigned &b, std::ostream &outfile)
Output the nodes on the boundary and their respective boundary coordinates(into separate tecplot zones)
Public Member Functions inherited from oomph::TriangleMeshBase
TriangleMeshBase ()
Constructor.
TriangleMeshBase (const TriangleMeshBase &node)=delete
Broken copy constructor.
virtual ~TriangleMeshBase ()
Broken assignment operator.
void setup_boundary_element_info ()
Setup lookup schemes which establish whic elements are located next to mesh's boundaries (wrapper to suppress doc).
void setup_boundary_element_info (std::ostream &outfile)
Setup lookup schemes which establish which elements are located next to mesh's boundaries. Doc in outfile (if it's open).
bool use_triangulateio_restart () const
const access for Use_triangulateio_restart.
void enable_triangulateio_restart ()
write access for Use_triangulateio_restart.
void disable_triangulateio_restart ()
write access for Use_triangulateio_restart.
TriangulateIO & triangulateio_representation ()
Access to the triangulateio representation of the mesh.
void write_triangulateio (TriangulateIO &triangulate_io, std::string &s)
Helper function. Write a TriangulateIO object file with all the triangulateio fields. String s is add to assign a different value for the input and/or output structure.
void clear_triangulateio ()
Helper function. Clean up the memory associated with the TriangulateIO object. This should really only be used to save memory in extremely tight situations.
void dump_triangulateio (std::ostream &dump_file)
Dump the triangulateio structure to a dump file and record boundary coordinates of boundary nodes.
virtual void dump_info_to_reset_halo_haloed_scheme (std::ostream &dump_file)
Virtual function that is used to dump info. related with distributed triangle meshes.
void remesh_from_triangulateio (std::istream &restart_file)
Regenerate the mesh from a dumped triangulateio file and dumped boundary coordinates of boundary nodes.
Public Member Functions inherited from oomph::UnstructuredTwoDMeshGeometryBase
UnstructuredTwoDMeshGeometryBase ()
Empty constructor.
UnstructuredTwoDMeshGeometryBase (const UnstructuredTwoDMeshGeometryBase &dummy)=delete
Broken copy constructor.
void operator= (const UnstructuredTwoDMeshGeometryBase &)=delete
Broken assignment operator.
~UnstructuredTwoDMeshGeometryBase ()
Empty destructor.
unsigned nregion ()
Return the number of regions specified by attributes.
unsigned nregion_element (const unsigned &i)
Return the number of elements in the i-th region.
FiniteElement * region_element_pt (const unsigned &i, const unsigned &e)
Return the e-th element in the i-th region.
unsigned nregion_attribute ()
Return the number of attributes used in the mesh.
double region_attribute (const unsigned &i)
Return the attribute associated with region i.
GeomObject * boundary_geom_object_pt (const unsigned &b)
Return the geometric object associated with the b-th boundary or null if the boundary has associated geometric object.
std::map< unsigned, GeomObject * > & boundary_geom_object_pt ()
Return direct access to the geometric object storage.
std::map< unsigned, Vector< double > > & boundary_coordinate_limits ()
Return access to the vector of boundary coordinates associated with each geometric object.
Vector< double > & boundary_coordinate_limits (const unsigned &b)
Return access to the coordinate limits associated with the geometric object associated with boundary b.
unsigned nboundary_element_in_region (const unsigned &b, const unsigned &r) const
Return the number of elements adjacent to boundary b in region r.
FiniteElement * boundary_element_in_region_pt (const unsigned &b, const unsigned &r, const unsigned &e) const
Return pointer to the e-th element adjacent to boundary b in region r.
int face_index_at_boundary_in_region (const unsigned &b, const unsigned &r, const unsigned &e) const
Return face index of the e-th element adjacent to boundary b in region r.
TriangleMeshPolyLine * boundary_polyline_pt (const unsigned &b)
Return pointer to the current polyline that describes the b-th mesh boundary.
std::map< unsigned, std::set< Node * > > & nodes_on_boundary_pt ()
Gets a pointer to a set with all the nodes related with a boundary.
const bool get_connected_vertex_number_on_destination_polyline (TriangleMeshPolyLine *dst_polyline_pt, Vector< double > &vertex_coordinates, unsigned &vertex_number)
Gets the vertex number on the destination polyline (used to create the connections among shared boundaries)
void check_contiguousness_on_polylines_helper (Vector< TriangleMeshPolyLine * > &polylines_pt, unsigned &index)
Sort the polylines coming from joining them. Check whether it is necessary to reverse them or not. Used when joining two curve polylines in order to create a polygon.
void check_contiguousness_on_polylines_helper (Vector< TriangleMeshPolyLine * > &polylines_pt, unsigned &index_halo_start, unsigned &index_halo_end)
Sort the polylines coming from joining them. Check whether it is necessary to reverse them or not. Used when joining polylines and they still do not create a polygon.
bool is_point_inside_polygon_helper (Vector< Vector< double > > polygon_vertices, Vector< double > point)
Helper function that checks if a given point is inside a polygon (a set of sorted vertices that connected create a polygon)
void enable_automatic_creation_of_vertices_on_boundaries ()
Enables the creation of points (by Triangle) on the outer and internal boundaries.
void disable_automatic_creation_of_vertices_on_boundaries ()
Disables the creation of points (by Triangle) on the outer and internal boundaries.
bool is_automatic_creation_of_vertices_on_boundaries_allowed ()
Returns the status of the variable Allow_automatic_creation_of_vertices_on_boundaries.
void flush_boundary_segment_node (const unsigned &b)
Flush the boundary segment node storage.
void set_nboundary_segment_node (const unsigned &b, const unsigned &s)
Set the number of segments associated with a boundary.
unsigned nboundary_segment (const unsigned &b)
Return the number of segments associated with a boundary.
unsigned long nboundary_segment_node (const unsigned &b)
Return the number of segments associated with a boundary.
unsigned long nboundary_segment_node (const unsigned &b, const unsigned &s)
Return the number of nodes associated with a given segment of a boundary.
void add_boundary_segment_node (const unsigned &b, const unsigned &s, Node *const &node_pt)
Add the node node_pt to the b-th boundary and the s-th segment of the mesh.
std::map< unsigned, Vector< double > > & boundary_initial_coordinate ()
Return direct access to the initial coordinates of a boundary.
std::map< unsigned, Vector< double > > & boundary_final_coordinate ()
Return direct access to the final coordinates of a boundary.
std::map< unsigned, Vector< double > > & boundary_initial_zeta_coordinate ()
Return direct access to the initial zeta coordinate of a boundary.
std::map< unsigned, Vector< double > > & boundary_final_zeta_coordinate ()
Return direct access to the final zeta coordinates of a boundary.
std::map< unsigned, Vector< unsigned > > & boundary_segment_inverted ()
Return the info. to know if it is necessary to reverse the segment based on a previous mesh.
std::map< unsigned, Vector< Vector< double > > > & boundary_segment_initial_coordinate ()
Return direct access to the initial coordinates for the segments that are part of a boundary.
std::map< unsigned, Vector< Vector< double > > > & boundary_segment_final_coordinate ()
Return direct access to the final coordinates for the segments that are part of a boundary.
std::map< unsigned, Vector< double > > & boundary_segment_initial_arclength ()
Return direct access to the initial arclength for the segments that are part of a boundary.
std::map< unsigned, Vector< double > > & boundary_segment_final_arclength ()
Return direct access to the final arclength for the segments that are part of a boundary.
std::map< unsigned, Vector< double > > & boundary_segment_initial_zeta ()
Return direct access to the initial zeta for the segments that are part of a boundary.
std::map< unsigned, Vector< double > > & boundary_segment_final_zeta ()
Return direct access to the final zeta for the segments that are part of a boundary.
Vector< double > & boundary_segment_initial_zeta (const unsigned &b)
Return the initial zeta for the segments that are part of a boundary.
Vector< double > & boundary_segment_final_zeta (const unsigned &b)
Return the final zeta for the segments that are part of a boundary.
Vector< double > & boundary_initial_coordinate (const unsigned &b)
Return the initial coordinates for the boundary.
Vector< double > & boundary_final_coordinate (const unsigned &b)
Return the final coordinates for the boundary.
const Vector< unsigned > boundary_segment_inverted (const unsigned &b) const
Return the info. to know if it is necessary to reverse the segment based on a previous mesh.
Vector< unsigned > & boundary_segment_inverted (const unsigned &b)
Return the info. to know if it is necessary to reverse the segment based on a previous mesh.
Vector< double > & boundary_initial_zeta_coordinate (const unsigned &b)
Return the initial zeta coordinate for the boundary.
Vector< double > & boundary_final_zeta_coordinate (const unsigned &b)
Return the final zeta coordinate for the boundary.
Vector< double > & boundary_segment_initial_arclength (const unsigned &b)
Return the initial arclength for the segments that are part of a boundary.
Vector< double > & boundary_segment_final_arclength (const unsigned &b)
Return the final arclength for the segments that are part of a boundary.
Vector< Vector< double > > & boundary_segment_initial_coordinate (const unsigned &b)
Return the initial coordinates for the segments that are part of a boundary.
Vector< Vector< double > > & boundary_segment_final_coordinate (const unsigned &b)
Return the final coordinates for the segments that are part of a boundary.
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b)
Setup boundary coordinate on boundary b. Boundary coordinate increases continously along polygonal boundary. It's zero at the lowest left node on the boundary.
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, std::ofstream &outfile)
Setup boundary coordinate on boundary b. Doc Faces in outfile. Boundary coordinate increases continously along polygonal boundary. It's zero at the lowest left node on the boundary.
Public Member Functions inherited from oomph::Mesh
void resize_halo_nodes ()
Helper function that resizes halo nodes to the same size as their non-halo counterparts if required. (A discrepancy can arise if a FaceElement that introduces additional unknowns are attached to a bulk element that shares a node with a haloed element. In that case the joint node between haloed and non-haloed element is resized on that processor but not on the one that holds the halo counterpart (because no FaceElement is attached to the halo element)
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
Constructor builds combined mesh from the meshes specified. Note: This simply merges the meshes' elements and nodes (ignoring duplicates; no boundary information etc. is created).
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
Merge meshes. Note: This simply merges the meshes' elements and nodes (ignoring duplicates; no boundary information etc. is created).
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
Output boundary coordinates on boundary b -- template argument specifies the bulk element type (needed to create FaceElement of appropriate type on mesh boundary).
virtual void scale_mesh (const double &factor)
Scale all nodal coordinates by given factor. Virtual so it can be overloaded in SolidMesh class where it also re-assigns the Lagrangian coordinates.
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
Flush storage for elements and nodes by emptying the vectors that store the pointers to them. This is useful if a particular mesh is only built to generate a small part of a bigger mesh. Once the elements and nodes have been created, they are typically copied into the new mesh and the auxiliary mesh can be deleted. However, if we simply call the destructor of the auxiliary mesh, it will also wipe out the nodes and elements, because it still "thinks" it's in charge of these...
void flush_element_storage ()
Flush storage for elements (only) by emptying the vectors that store the pointers to them. This is useful if a particular mesh is only built to generate a small part of a bigger mesh. Once the elements and nodes have been created, they are typically copied into the new mesh and the auxiliary mesh can be deleted. However, if we simply call the destructor of the auxiliary mesh, it will also wipe out the nodes and elements, because it still "thinks" it's in charge of these...
void flush_node_storage ()
Flush storage for nodes (only) by emptying the vectors that store the pointers to them.
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Upcast (downcast?) to FiniteElement (needed to access FiniteElement member functions).
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
Remove all information about nodes stored on the b-th boundary of the mesh.
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
Replace existing boundary node lookup schemes with new schemes created using the boundary data stored in the nodes.
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
void set_boundary_coordinate_exists (const unsigned &i)
Set boundary coordinate on the i-th boundary to be existing.
void set_boundary_coordinate_does_not_exist (const unsigned &i)
Set boundary coordinate on the i-th boundary to be non-existing.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
Update nodal positions in response to changes in the domain shape. Uses the FiniteElement::get_x(...) function for FiniteElements and doesn't do anything for other element types. If a MacroElement pointer has been set for a FiniteElement, the MacroElement representation is used to update the nodal positions; if not get_x(...) uses the FE interpolation and thus leaves the nodal positions unchanged. Virtual, so it can be overloaded by specific meshes, such as AlgebraicMeshes or SpineMeshes. Generally, this function updates the position of all nodes in response to changes in the boundary position. However, we ignore all SolidNodes since their position is computed as part of the solution -- unless the bool flag is set to true. Such calls are typically made when the initial mesh is created and/or after a mesh has been refined repeatedly before the start of the computation.
virtual void reorder_nodes (const bool &use_old_ordering=true)
Re-order nodes in the order in which they appear in elements -- can be overloaded for more efficient re-ordering.
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
Get a reordering of the nodes in the order in which they appear in elements -- can be overloaded for more efficient re-ordering.
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
Constuct a Mesh of FACE_ELEMENTs along the b-th boundary of the mesh (which contains elements of type BULK_ELEMENT)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
Determine max and min area for all FiniteElements in the mesh (non-FiniteElements are ignored)
double total_size ()
Determine the sum of all "sizes" of the FiniteElements in the mesh (non-FiniteElements are ignored). This gives the length/area/volume occupied by the mesh.
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
Check for inverted elements and report outcome in boolean variable. This visits all elements at their integration points and checks if the Jacobian of the mapping between local and global coordinates is positive -- using the same test that would be carried out (but only in PARANOID mode) during the assembly of the elements' Jacobian matrices. Inverted elements are output in inverted_element_file (if the stream is open).
void check_inverted_elements (bool &mesh_has_inverted_elements)
Check for inverted elements and report outcome in boolean variable. This visits all elements at their integration points and checks if the Jacobian of the mapping between local and global coordinates is positive -- using the same test that would be carried out (but only in PARANOID mode) during the assembly of the elements' Jacobian matrices.
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Check for repeated nodes within a given spatial tolerance. Return (0/1) for (pass/fail).
Vector< Node * > prune_dead_nodes ()
Prune nodes. Nodes that have been marked as obsolete are removed from the mesh (and its boundary-node scheme). Returns vector of pointers to deleted nodes.
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
Find a node not on any boundary in mesh_pt (useful for pinning a single node in a purely Neumann problem so that it is fully determined).
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
For the e-th finite element on boundary b, return int to indicate the face_index of the face adjacent to the boundary. This is consistent with input required during the generation of FaceElements.
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
Output in paraview format into specified file. Breaks up each element into sub-elements for plotting purposes. We assume that all elements are of the same type (fct will break break (in paranoid mode) if paraview output fcts of the elements are inconsistent).
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
Output in paraview format into specified file. Breaks up each element into sub-elements for plotting purposes. We assume that all elements are of the same type (fct will break break (in paranoid mode) if paraview output fcts of the elements are inconsistent).
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
Output in paraview format into specified file. Breaks up each element into sub-elements for plotting purposes. We assume that all elements are of the same type (fct will break break (in paranoid mode) if paraview output fcts of the elements are inconsistent).
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
Output a given time-dep. Vector function at f(n_plot) points in each element.
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
Output the nodes on the boundaries (into separate tecplot zones). Specify filename.
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
Shift time-dependent data along for next timestep: Deal with nodal Data/positions and the element's internal Data.
void calculate_predictions ()
Calculate predictions for all Data and positions associated with the mesh, usually used in adaptive time-stepping.
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with all nodal and elemental data stored in the mesh.
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the internal data stored within elements in the meah.
virtual void compute_norm (double &norm)
Compute norm of solution by summing contributions of compute_norm(...) for all constituent elements in the mesh. What that norm means depends on what's defined in the element's function; may need to take the square root afterwards if the elements compute the square of the L2 norm, say.
virtual void compute_norm (Vector< double > &norm)
Compute norm of solution by summing contributions of compute_norm(...) for all constituent elements in the mesh. What that norm means depends on what's defined in the element's function; may need to take the square root afterwards if the elements compute the square of the L2 norm, say.
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Plot error when compared against a given exact solution. Also returns the norm of the error and that of the exact solution.
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Plot error when compared against a given time-depdendent exact solution. Also returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Plot error when compared against a given time-dependent exact solution. Also returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
Plot error when compared against a given time-dependent exact solution. Also returns the norm of the error and that of the exact solution.
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
Plot error when compared against a given time-depdendent exact solution. Also returns the norm of the error and that of the exact solution. Version with vectors of norms and errors so that different variables' norms and errors can be returned individually.
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
Plot error when compared against a given time-depdendent exact solution. Also returns the norm of the error and that of the exact solution. Version with vectors of norms and errors so that different variables' norms and errors can be returned individually.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
Returns the norm of the error and that of the exact solution. Version with vectors of norms and errors so that different variables' norms and errors can be returned individually.
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
Read-only access fct to communicator (Null if mesh is not distributed, i.e. if we don't have mpi).
void set_communicator_pt (OomphCommunicator *comm_pt)
Function to set communicator (mesh is assumed to be distributed if the communicator pointer is non-null). Only defined if mpi is enabled becaus Comm_pt itself is only defined when mpi is enabled.
void set_keep_all_elements_as_halos ()
Call this function to keep all the elements as halo elements.
void unset_keep_all_elements_as_halos ()
Calll this function to unset the flag that keeps all elements in the mesh as halo elements.
virtual void distribute (OomphCommunicator *comm_pt, const Vector< unsigned > &element_domain, Vector< GeneralisedElement * > &deleted_element_pt, DocInfo &doc_info, const bool &report_stats, const bool &overrule_keep_as_halo_element_status)
Distribute the problem and doc; make this virtual to allow overloading for particular meshes where further work is required. Add to vector of pointers to deleted elements.
void distribute (OomphCommunicator *comm_pt, const Vector< unsigned > &element_domain, Vector< GeneralisedElement * > &deleted_element_pt, const bool &report_stats=false)
Distribute the problem Add to vector of pointers to deleted elements.
void prune_halo_elements_and_nodes (Vector< GeneralisedElement * > &deleted_element_pt, const bool &report_stats=false)
(Irreversibly) prune halo(ed) elements and nodes, usually after another round of refinement, to get rid of excessively wide halo layers. Note that the current mesh will be now regarded as the base mesh and no unrefinement relative to it will be possible once this function has been called.
void prune_halo_elements_and_nodes (Vector< GeneralisedElement * > &deleted_element_pt, DocInfo &doc_info, const bool &report_stats)
(Irreversibly) prune halo(ed) elements and nodes, usually after another round of refinement, to get rid of excessively wide halo layers. Note that the current mesh will be now regarded as the base mesh and no unrefinement relative to it will be possible once this function has been called.
void get_efficiency_of_mesh_distribution (double &av_efficiency, double &max_efficiency, double &min_efficiency)
Get efficiency of mesh distribution: In an ideal distribution without halo overhead, each processor would only hold its own elements. Efficieny per processor = (number of non-halo elements)/ (total number of elements).
void doc_mesh_distribution (DocInfo &doc_info)
Doc the mesh distribution, to be processed with tecplot macros.
void check_halo_schemes (DocInfo &doc_info, double &max_permitted_error_for_halo_check)
Check halo and shared schemes on the mesh.
virtual void classify_halo_and_haloed_nodes (DocInfo &doc_info, const bool &report_stats)
Classify the halo and haloed nodes in the mesh. Virtual so it can be overloaded to perform additional functionality (such as synchronising hanging nodes) in refineable meshes, say.
virtual void classify_halo_and_haloed_nodes (const bool &report_stats=false)
Classify the halo and haloed nodes in the mesh. Virtual so it can be overloaded to perform additional functionality (such as synchronising hanging nodes) in refineable meshes, say.
void synchronise_shared_nodes (const bool &report_stats)
Synchronise shared node lookup schemes to cater for the the case where: (1) a certain node on the current processor is halo with proc p (i.e. its non-halo counterpart lives on processor p) (2) that node is also exists (also as a halo) on another processor (q, say) where its non-halo counter part is also known to be on processor p. However, without calling this function the current processor does not necessarily know that it shares a node with processor q. This information can be required, e.g. when synchronising hanging node schemes over all processors.
void get_all_halo_data (std::map< unsigned, double * > &map_of_halo_data)
Get all the halo data stored in the mesh and add pointers to the data to the map, indexed by global equation number.
Vector< GeneralisedElement * > halo_element_pt (const unsigned &p)
Return vector of halo elements in this Mesh whose non-halo counterpart is held on processor p.
Vector< GeneralisedElement * > haloed_element_pt (const unsigned &p)
Return vector of haloed elements in this Mesh whose haloing counterpart is held on processor p.
unsigned nnon_halo_element ()
Total number of non-halo elements in this mesh (Costly call computes result on the fly)
unsigned nroot_halo_element ()
Total number of root halo elements in this Mesh.
unsigned nroot_halo_element (const unsigned &p)
Number of root halo elements in this Mesh whose non-halo counterpart is held on processor p.
Vector< GeneralisedElement * > root_halo_element_pt (const unsigned &p)
Vector of pointers to root halo elements in this Mesh whose non-halo counterpart is held on processor p.
GeneralisedElement *& root_halo_element_pt (const unsigned &p, const unsigned &e)
Access fct to the e-th root halo element in this Mesh whose non-halo counterpart is held on processor p.
void add_root_halo_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
Add root halo element whose non-halo counterpart is held on processor p to this Mesh.
unsigned nhalo_node ()
Total number of halo nodes in this Mesh.
unsigned nhalo_node (const unsigned &p)
Number of halo nodes in this Mesh whose non-halo counterpart is held on processor p.
void add_halo_node_pt (const unsigned &p, Node *&nod_pt)
Add halo node whose non-halo counterpart is held on processor p to the storage scheme for halo nodes.
Node * halo_node_pt (const unsigned &p, const unsigned &j)
Access fct to the j-th halo node in this Mesh whose non-halo counterpart is held on processor p.
unsigned nroot_haloed_element ()
Total number of root haloed elements in this Mesh.
unsigned nroot_haloed_element (const unsigned &p)
Number of root haloed elements in this Mesh whose non-halo counterpart is held on processor p.
Vector< GeneralisedElement * > root_haloed_element_pt (const unsigned &p)
Vector of pointers to root haloed elements in this Mesh whose non-halo counterpart is held on processor p.
GeneralisedElement *& root_haloed_element_pt (const unsigned &p, const unsigned &e)
Access fct to the e-th root haloed element in this Mesh whose non-halo counterpart is held on processor p.
void add_root_haloed_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
Add root haloed element whose non-halo counterpart is held on processor p to the storage scheme for haloed elements. Note: This does not add the element to the storage scheme for elements as it's understood to naturally live on this processor anyway!
unsigned nhaloed_node ()
Total number of haloed nodes in this Mesh.
unsigned nhaloed_node (const unsigned &p)
Number of haloed nodes in this Mesh whose haloed counterpart is held on processor p.
Node * haloed_node_pt (const unsigned &p, const unsigned &j)
Access fct to the j-th haloed node in this Mesh whose halo counterpart is held on processor p.
void add_haloed_node_pt (const unsigned &p, Node *&nod_pt)
Add haloed node whose halo counterpart is held on processor p to the storage scheme for haloed nodes.
void disable_resizing_of_halo_nodes ()
Function to suppress resizing of halo nodes -- optmisation but call it at your own risk!
void enable_resizing_of_halo_nodes ()
Function to (re-)enable resizing of halo nodes -- this returns things to the default behaviour.
void disable_output_of_halo_elements ()
Function to disable halo element output.
void enable_output_of_halo_elements ()
Function to enable halo element output.
unsigned nshared_node ()
Total number of shared nodes in this Mesh.
void doc_shared_nodes ()
Doc shared nodes.
unsigned nshared_node (const unsigned &p)
Number of shared nodes in this Mesh who have a counterpart on processor p.
Node * shared_node_pt (const unsigned &p, const unsigned &j)
Access fct to the j-th shared node in this Mesh who has a counterpart on processor p.
void get_shared_node_pt (const unsigned &p, Vector< Node * > &shared_node_pt)
Get vector of pointers to shared nodes with processor p. Required for faster search in Missing_masters_functions::add_external_haloed_node_helper() and Missing_masters_functions::add_external_haloed_master_node_helper()
void add_shared_node_pt (const unsigned &p, Node *&nod_pt)
Add shared node whose counterpart is held on processor p to the storage scheme for shared nodes. (NB: ensure that this routine is called twice, once for each process)
void get_halo_node_stats (double &av_number, unsigned &max_number, unsigned &min_number)
Get halo node stats for this distributed mesh: Average/max/min number of halo nodes over all processors. Careful: Involves MPI Broadcasts and must therefore be called on all processors!
void get_haloed_node_stats (double &av_number, unsigned &max_number, unsigned &min_number)
Get haloed node stats for this distributed mesh: Average/max/min number of haloed nodes over all processors. Careful: Involves MPI Broadcasts and must therefore be called on all processors!
void output_external_halo_elements (std::ostream &outfile, const unsigned &n_plot=5)
Output all external halo elements.
void output_external_halo_elements (const unsigned &p, std::ostream &outfile, const unsigned &n_plot=5)
Output all external halo elements with processor p.
void output_external_haloed_elements (std::ostream &outfile, const unsigned &n_plot=5)
Output all external haloed elements.
void output_external_haloed_elements (const unsigned &p, std::ostream &outfile, const unsigned &n_plot=5)
Output all external haloed elements with processor p.
unsigned nexternal_halo_element ()
Total number of external halo elements in this Mesh.
unsigned nexternal_halo_element (const unsigned &p)
Number of external halo elements in this Mesh whose non-halo counterpart is held on processor p.
GeneralisedElement *& external_halo_element_pt (const unsigned &p, const unsigned &e)
Access fct to the e-th external halo element in this Mesh whose non-halo counterpart is held on processor p.
void add_external_halo_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
Add external halo element whose non-halo counterpart is held on processor p to this Mesh.
unsigned nexternal_haloed_element ()
Total number of external haloed elements in this Mesh.
unsigned nexternal_haloed_element (const unsigned &p)
Number of external haloed elements in this Mesh whose non-halo counterpart is held on processor p.
GeneralisedElement *& external_haloed_element_pt (const unsigned &p, const unsigned &e)
Access fct to the e-th external haloed element in this Mesh whose non-halo counterpart is held on processor p.
unsigned add_external_haloed_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
Add external haloed element whose non-halo counterpart is held on processor p to the storage scheme for haloed elements.
unsigned nexternal_halo_node ()
Total number of external halo nodes in this Mesh.
void get_external_halo_node_pt (Vector< Node * > &external_halo_node_pt)
Get vector of pointers to all external halo nodes.
unsigned nexternal_halo_node (const unsigned &p)
Number of external halo nodes in this Mesh whose non-halo (external) counterpart is held on processor p.
void add_external_halo_node_pt (const unsigned &p, Node *&nod_pt)
Add external halo node whose non-halo (external) counterpart is held on processor p to the storage scheme for halo nodes.
Node *& external_halo_node_pt (const unsigned &p, const unsigned &j)
Access fct to the j-th external halo node in this Mesh whose non-halo external counterpart is held on processor p.
Vector< Node * > external_halo_node_pt (const unsigned &p)
Access fct to vector of external halo node in this Mesh whose non-halo external counterpart is held on processor p. (read only)
void set_external_halo_node_pt (const unsigned &p, const Vector< Node * > &external_halo_node_pt)
Set vector of external halo node in this Mesh whose non-halo external counterpart is held on processor p.
void null_external_halo_node (const unsigned &p, Node *nod_pt)
Null out specified external halo node (used when deleting duplicates)
void remove_null_pointers_from_external_halo_node_storage ()
Consolidate external halo node storage by removing nulled out pointes in external halo and haloed schemes.
unsigned nexternal_haloed_node ()
Total number of external haloed nodes in this Mesh.
unsigned nexternal_haloed_node (const unsigned &p)
Number of external haloed nodes in this Mesh whose halo (external) counterpart is held on processor p.
Node *& external_haloed_node_pt (const unsigned &p, const unsigned &j)
Access fct to the j-th external haloed node in this Mesh whose halo external counterpart is held on processor p.
unsigned add_external_haloed_node_pt (const unsigned &p, Node *&nod_pt)
Add external haloed node whose halo (external) counterpart is held on processor p to the storage scheme for haloed nodes.
Vector< Node * > external_haloed_node_pt (const unsigned &p)
Access fct to vector of external haloed node in this Mesh whose halo external counterpart is held on processor p. (read only)
void set_external_haloed_node_pt (const unsigned &p, const Vector< Node * > &external_haloed_node_pt)
Set vector of external haloed node in this Mesh whose halo external counterpart is held on processor p.
std::set< int > external_halo_proc ()
Return the set of processors that hold external halo nodes. This is required to avoid having to pass a communicator into the node_update functions for Algebraic-based and MacroElement-based Meshes.
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Public Member Functions inherited from oomph::RefineableMeshBase
bool adapt_flag ()
RefineableMeshBase ()
Constructor sets default values for refinement targets etc. and initialises pointer to spatial error estimator to NULL.
RefineableMeshBase (const RefineableMeshBase &dummy)=delete
Broken copy constructor.
void operator= (const RefineableMeshBase &)=delete
Broken assignment operator.
virtual ~RefineableMeshBase ()
Empty Destructor:
unsigned nrefined ()
Access fct for number of elements that were refined.
unsigned nunrefined ()
Access fct for number of elements that were unrefined.
unsigned & nrefinement_overruled ()
Number of elements that would have liked to be refined further but can't because they've reached the max. refinement level.
unsigned & max_keep_unrefined ()
Max. number of elements that we allow to remain unrefined if no other mesh adaptation is required (to avoid mesh-adaptations that would only unrefine a few elements and then force a new solve -- this can't be worth our while!)
ErrorEstimator *& spatial_error_estimator_pt ()
Access to spatial error estimator.
ErrorEstimator * spatial_error_estimator_pt () const
Access to spatial error estimator (const version.
double & min_permitted_error ()
Access fct for min. error (i.e. (try to) merge elements if their error is smaller)
double & max_permitted_error ()
Access fct for max. error (i.e. split elements if their error is larger)
double & min_error ()
Access fct for min. actual error in present solution (i.e. before re-solve on adapted mesh)
double & max_error ()
Access fct for max. actual error in present solution (i.e. before re-solve on adapted mesh)
DocInfo *& doc_info_pt ()
Access fct for pointer to DocInfo.
void enable_adaptation ()
Enable adaptation.
void disable_adaptation ()
Disable adaptation.
void enable_p_adaptation ()
Enable adaptation.
void disable_p_adaptation ()
Disable adaptation.
void enable_additional_synchronisation_of_hanging_nodes ()
Enable additional synchronisation of hanging nodes.
void disable_additional_synchronisation_of_hanging_nodes ()
Disable additional synchronisation of hanging nodes.
bool is_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_p_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_additional_synchronisation_of_hanging_nodes_disabled () const
Return whether additional synchronisation is enabled.
DocInfo doc_info ()
Access fct for DocInfo.
virtual void p_adapt (const Vector< double > &elemental_error)
p-adapt mesh: Refine elements whose error is lager than err_max and (try to) unrefine those whose error is smaller than err_min
virtual void refine_uniformly ()
Refine mesh uniformly.
virtual void p_refine_uniformly (DocInfo &doc_info)
p-refine mesh uniformly and doc process
virtual void p_refine_uniformly ()
p-refine mesh uniformly
void p_unrefine_uniformly (DocInfo &doc_info)
p-unrefine mesh uniformly
Protected Member Functions
RefineableTriangleMesh (const Vector< double > &target_area, TriangulateIO &triangulate_io, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false, const bool &allow_automatic_creation_of_vertices_on_boundaries=true, OomphCommunicator *comm_pt=0)
Build mesh from specified triangulation and associated target areas for elements in it NOTE: This is used ONLY during adaptation and should not be used as a method of constructing a TriangleMesh object in demo drivers!
const bool boundary_connections (const unsigned &b, const unsigned &c, std::set< Vector< double > > &vertices)
Verifies if the given boundary receives a connection, and if that is the case then returns the list of vertices that receive the connections.
const void synchronize_shared_boundary_connections ()
Synchronise the vertices that are marked for non deletion.
void add_vertices_for_non_deletion ()
Mark the vertices that are not allowed for deletion by the unrefienment/refinement polyline methods. In charge of filling the Boundary_chunk_connections_pt structure.
void add_non_delete_vertices_from_boundary_helper (Vector< Vector< Node * > > src_bound_segment_node_pt, Vector< Vector< Node * > > dst_bound_segment_node_pt, const unsigned &dst_bnd_id, const unsigned &dst_bnd_chunk)
Adds the vertices from the sources boundary that are repeated in the destination boundary to the list of non delete-able vertices in the destination boundary.
void create_temporary_boundary_connections (Vector< TriangleMeshPolygon * > &tmp_outer_polygons_pt, Vector< TriangleMeshOpenCurve * > &tmp_open_curves_pt)
After unrefinement and refinement has taken place compute the new vertices numbers of the temporary representation of the.
void restore_boundary_connections (Vector< TriangleMeshPolyLine * > &resume_initial_connection_polyline_pt, Vector< TriangleMeshPolyLine * > &resume_final_connection_polyline_pt)
After unrefinement and refinement has taken place compute the new vertices numbers of the boundaries to connect (in a distributed scheme it may be possible that the destination boundary does no longer exist, therefore the connection is suspended and resumed after the adaptation processor.
void restore_polyline_connections_helper (TriangleMeshPolyLine *polyline_pt, Vector< TriangleMeshPolyLine * > &resume_initial_connection_polyline_pt, Vector< TriangleMeshPolyLine * > &resume_final_connection_polyline_pt)
Restore the connections of the specific polyline The vertices numbering on the destination boundaries may have change because of (un)refinement in the destination boundaries. Also deals with connection that do not longer exist because the destination boundary does no longer exist because of the distribution process.
void resume_boundary_connections (Vector< TriangleMeshPolyLine * > &resume_initial_connection_polyline_pt, Vector< TriangleMeshPolyLine * > &resume_final_connection_polyline_pt)
Resume the boundary connections that may have been suspended because the destination boundary is no part of the domain. The connections are no permanently suspended because if load balance takes place the destination boundary may be part of the new domain representation therefore the connection would exist.
bool get_connected_vertex_number_on_dst_boundary (Vector< double > &vertex_coordinates, const unsigned &dst_b_id, unsigned &vertex_number)
Computes the associated vertex number on the destination boundary.
bool unrefine_boundary (const unsigned &b, const unsigned &c, Vector< Vector< double > > &vector_bnd_vertices, double &unrefinement_tolerance, const bool &check_only=false)
Helper function that performs the unrefinement process.
bool refine_boundary (Mesh *face_mesh_pt, Vector< Vector< double > > &vector_bnd_vertices, double &refinement_tolerance, const bool &check_only=false)
Helper function that performs the refinement process on the specified boundary by using the provided vertices representation. Optional boolean is used to run it as test only (if true is specified as input) in which case vertex coordinates aren't actually modified. Returned boolean indicates if polyline was (or would have been -- if called with check_only=false) changed.
bool apply_max_length_constraint (Mesh *face_mesh_pt, Vector< Vector< double > > &vector_bnd_vertices, double &max_length_constraint)
bool unrefine_boundary_constrained_by_target_area (const unsigned &b, const unsigned &c, Vector< Vector< double > > &vector_bnd_vertices, double &unrefinement_tolerance, Vector< double > &area_constraint)
Helper function that performs the unrefinement process on the specified boundary by using the provided vertices representation and the associated target area. Used only when the 'allow_automatic_creation_of_vertices_on_boundaries' flag is set to true.
bool refine_boundary_constrained_by_target_area (MeshAsGeomObject *mesh_geom_obj_pt, Vector< Vector< double > > &vector_bnd_vertices, double &refinement_tolerance, Vector< double > &area_constraint)
Helper function that performs the refinement process on the specified boundary by using the provided vertices representation and the associated elements target area. Used only when the 'allow_automatic_creation_of_vertices_on_boundaries' flag is set to true.
bool unrefine_shared_boundary_constrained_by_target_area (const unsigned &b, const unsigned &c, Vector< Vector< double > > &vector_bnd_vertices, Vector< double > &area_constraint)
Helper function that performs the unrefinement process on the specified boundary by using the provided vertices representation and the associated target area. NOTE: This is the version that applies unrefinement to shared boundaries.
bool refine_shared_boundary_constrained_by_target_area (Vector< Vector< double > > &vector_bnd_vertices, Vector< double > &area_constraint)
Helper function that performs the refinement process on the specified boundary by using the provided vertices representation and the associated elements target area. NOTE: This is the version that applies refinement to shared boundaries.
void initialise_boundary_refinement_data ()
Set all the flags to true (the default values)
void sort_nodes_on_shared_boundaries ()
Sort the nodes on shared boundaries so that the processors that share a boundary agree with the order of the nodes on the boundary.
void reset_shared_boundary_elements_and_nodes (const bool flush_elements=true, const bool update_elements=true, const bool flush_nodes=true, const bool update_nodes=true)
Re-establish the shared boundary elements after the adaptation process (the updating of shared nodes is optional and performed by default)
void reset_halo_haloed_scheme ()
In charge of. re-establish the halo(ed) scheme on all processors. Sends info. to create halo elements and nodes on the processors that need it. It uses and all to all communication strategy therefore must be called on all processors.
void compute_global_node_names_and_shared_nodes (Vector< Vector< Vector< std::map< unsigned, Node * > > > > &other_proc_shd_bnd_node_pt, Vector< Vector< Vector< unsigned > > > &global_node_names, std::map< Vector< unsigned >, unsigned > &node_name_to_global_index, Vector< Node * > &global_shared_node_pt)
Compute the names of the nodes on shared boundaries in this (my_rank) processor with other processors. Also compute the names of nodes on shared boundaries of other processors with other processors (useful when there is an element that requires to be sent to this (my_rank) processor because there is a shared node between this (my_rank) and other processors BUT there is not a shared boundary between this and the other processor.
void send_boundary_node_info_of_shared_nodes (Vector< Vector< Vector< unsigned > > > &global_node_names, std::map< Vector< unsigned >, unsigned > &node_name_to_global_index, Vector< Node * > &global_shared_node_pt)
Get the original boundaries to which is associated each shared node, and send the info. to the related processors. We need to do this so that at the reset of halo(ed) info. stage, the info. be already updated.
void reset_halo_haloed_scheme_helper (Vector< Vector< Vector< std::map< unsigned, Node * > > > > &other_proc_shd_bnd_node_pt, Vector< Vector< Node * > > &iproc_currently_created_nodes_pt, Vector< Vector< Vector< unsigned > > > &global_node_names, std::map< Vector< unsigned >, unsigned > &node_name_to_global_index, Vector< Node * > &global_shared_node_pt)
In charge of creating additional halo(ed) elements on those processors that have no shared boundaries in common but have shared nodes.
unsigned try_to_add_element_pt_load_balance (Vector< FiniteElement * > &new_elements_on_domain, FiniteElement *&ele_pt)
Check if necessary to add the element to the new domain or if it has been previously added.
void get_required_elemental_information_load_balance_helper (unsigned &iproc, Vector< Vector< FiniteElement * > > &f_haloed_ele_pt, FiniteElement *ele_pt)
Helper function to get the required elemental information from the element to be sent. This info. involves the association of the element to a boundary or region, and if its part of the halo(ed) elements within a processor.
unsigned try_to_add_node_pt_load_balance (Vector< Node * > &new_nodes_on_domain, Node *&node_pt)
Check if necessary to add the node to the new domain or if it has been already added.
void add_node_load_balance_helper (unsigned &iproc, Vector< Vector< FiniteElement * > > &f_halo_ele_pt, Vector< Node * > &new_nodes_on_domain, Node *nod_pt)
Helper function to add haloed node.
void get_required_nodal_information_load_balance_helper (Vector< Vector< FiniteElement * > > &f_halo_ele_pt, unsigned &iproc, Node *nod_pt)
Helper function to get the required nodal information from an haloed node so that a fully-functional node (and therefore element) can be created on the receiving process (this is the specific version for the load balance strategy, the difference with the original method is that it checks if the node is on a shared boundary no associated with the current processor --my_rank--, or in a haloed element from other processors.
void create_element_load_balance_helper (unsigned &iproc, Vector< Vector< FiniteElement * > > &f_haloed_ele_pt, Vector< Vector< std::map< unsigned, FiniteElement * > > > &received_old_haloed_element_pt, Vector< FiniteElement * > &new_elements_on_domain, Vector< Node * > &new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node * > > > > &other_proc_shd_bnd_node_pt, Vector< Vector< Vector< unsigned > > > &global_node_names, std::map< Vector< unsigned >, unsigned > &node_name_to_global_index, Vector< Node * > &global_shared_node_pt)
Helper function to create elements on the loop process based on the info received in send_and_received_elements_nodes_info.
void add_element_load_balance_helper (const unsigned &iproc, Vector< Vector< std::map< unsigned, FiniteElement * > > > &received_old_haloed_element_pt, FiniteElement *ele_pt)
Helper function to create elements on the loop process based on the info received in send_and_received_elements_nodes_info This function is in charge of verify if the element is associated to a boundary and associate to it if that is the case.
void add_received_node_load_balance_helper (Node *&new_nod_pt, Vector< Vector< FiniteElement * > > &f_haloed_ele_pt, Vector< Vector< std::map< unsigned, FiniteElement * > > > &received_old_haloed_element_pt, Vector< Node * > &new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node * > > > > &other_proc_shd_bnd_node_pt, unsigned &iproc, unsigned &node_index, FiniteElement *const &new_el_pt, Vector< Vector< Vector< unsigned > > > &global_node_names, std::map< Vector< unsigned >, unsigned > &node_name_to_global_index, Vector< Node * > &global_shared_node_pt)
Helper function to add a new node from load balance.
void construct_new_node_load_balance_helper (Node *&new_nod_pt, Vector< Vector< FiniteElement * > > &f_haloed_ele_pt, Vector< Vector< std::map< unsigned, FiniteElement * > > > &received_old_haloed_element_pt, Vector< Node * > &new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node * > > > > &other_proc_shd_bnd_node_pt, unsigned &iproc, unsigned &node_index, FiniteElement *const &new_el_pt, Vector< Vector< Vector< unsigned > > > &global_node_names, std::map< Vector< unsigned >, unsigned > &node_name_to_global_index, Vector< Node * > &global_shared_node_pt)
Helper function which constructs a new node (on an element) with the information sent from the load balance process.
unsigned try_to_add_root_haloed_element_pt (const unsigned &p, GeneralisedElement *&el_pt)
Check if necessary to add the element as haloed or if it has been previously added to the haloed scheme.
unsigned try_to_add_haloed_node_pt (const unsigned &p, Node *&nod_pt)
Check if necessary to add the node as haloed or if it has been previously added to the haloed scheme.
void get_required_elemental_information_helper (unsigned &iproc, FiniteElement *ele_pt)
Helper function to get the required elemental information from an haloed element. This info. involves the association of the element to a boundary or region.
void get_required_nodal_information_helper (unsigned &iproc, Node *nod_pt)
Helper function to get the required nodal information from a haloed node so that a fully-functional halo node (and therefore element) can be created on the receiving process.
void add_haloed_node_helper (unsigned &iproc, Node *nod_pt)
Helper function to add haloed node.
void send_and_receive_elements_nodes_info (int &send_proc, int &recv_proc)
Helper function to send back halo and haloed information.
void create_halo_element (unsigned &iproc, Vector< Node * > &new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node * > > > > &other_proc_shd_bnd_node_pt, Vector< Vector< Vector< unsigned > > > &global_node_names, std::map< Vector< unsigned >, unsigned > &node_name_to_global_index, Vector< Node * > &global_shared_node_pt)
Helper function to create (halo) elements on the loop process based on the info received in send_and_received_located_info.
void add_halo_element_helper (unsigned &iproc, FiniteElement *ele_pt)
Helper function to create (halo) elements on the loop process based on the info received in send_and_received_located_info This function is in charge of verify if the element is associated to a boundary.
void add_halo_node_helper (Node *&new_nod_pt, Vector< Node * > &new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node * > > > > &other_proc_shd_bnd_node_pt, unsigned &iproc, unsigned &node_index, FiniteElement *const &new_el_pt, Vector< Vector< Vector< unsigned > > > &global_node_names, std::map< Vector< unsigned >, unsigned > &node_name_to_global_index, Vector< Node * > &global_shared_node_pt)
Helper function to add halo node.
void construct_new_halo_node_helper (Node *&new_nod_pt, Vector< Node * > &new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node * > > > > &other_proc_shd_bnd_node_pt, unsigned &iproc, unsigned &node_index, FiniteElement *const &new_el_pt, Vector< Vector< Vector< unsigned > > > &global_node_names, std::map< Vector< unsigned >, unsigned > &node_name_to_global_index, Vector< Node * > &global_shared_node_pt)
Helper function which constructs a new halo node (on an element) with the information sent from the haloed process.
void update_other_proc_shd_bnd_node_helper (Node *&new_nod_pt, Vector< Vector< Vector< std::map< unsigned, Node * > > > > &other_proc_shd_bnd_node_pt, Vector< unsigned > &other_processor_1, Vector< unsigned > &other_processor_2, Vector< unsigned > &other_shared_boundaries, Vector< unsigned > &other_indexes, Vector< Vector< Vector< unsigned > > > &global_node_names, std::map< Vector< unsigned >, unsigned > &node_name_to_global_index, Vector< Node * > &global_shared_node_pt)
Helper function that assigns/updates the references to the node so that it can be found with any other reference. The return value indicates whether or not a node was found on the same reference.
bool update_polygon_using_face_mesh (TriangleMeshPolygon *polygon_pt, const bool &check_only=false)
Helper function that updates the input polygon's PSLG by using the end-points of elements from FaceMesh(es) that are constructed for the boundaries associated with the segments of the polygon. Optional boolean is used to run it as test only (if true is specified as input) in which case polygon isn't actually modified. Returned boolean indicates if polygon was (or would have been -- if called with check_only=false) changed.
bool update_open_curve_using_face_mesh (TriangleMeshOpenCurve *open_polyline_pt, const bool &check_only=false)
Helper function that updates the input open curve by using end-points of elements from FaceMesh(es) that are constructed for the boundaries associated with the polylines. Optional boolean is used to run it as test only (if true is specified as input) in which case the polylines are not actually modified. Returned boolean indicates if polylines were (or would have been -- if called with check_only=false) changed.
virtual bool surface_remesh_for_inner_hole_boundaries (Vector< Vector< double > > &internal_point_coord, const bool &check_only=false)
Generate a new PSLG representation of the inner hole boundaries. Optional boolean is used to run it as test only (if true is specified as input) in which case PSLG isn't actually modified. Returned boolean indicates if PSLG was (or would have been -- if called with check_only=false) changed.
void snap_nodes_onto_boundary (RefineableTriangleMesh< ELEMENT > *&new_mesh_pt, const unsigned &b)
Snap the boundary nodes onto any curvilinear boundaries.
void create_unsorted_face_mesh_representation (const unsigned &boundary_id, Mesh *face_mesh_pt)
Helper function Creates an unsorted face mesh representation from the specified boundary id. It means that the elements are not sorted along the boundary.
void create_sorted_face_mesh_representation (const unsigned &boundary_id, Mesh *face_mesh_pt, std::map< FiniteElement *, bool > &is_inverted, bool &inverted_face_mesh)
Helper function Creates a sorted face mesh representation of the specified PolyLine It means that the elements are sorted along the boundary It also returns a map that indicated the inverted elements.
void get_face_mesh_representation (TriangleMeshPolygon *polygon_pt, Vector< Mesh * > &face_mesh_pt)
Helper function to construct face mesh representation of all polylines, possibly with segments re-distributed between polylines to maintain an appxroximately even sub-division of the polygon.
void get_face_mesh_representation (TriangleMeshOpenCurve *open_polyline_pt, Vector< Mesh * > &face_mesh_pt)
Helper function to construct face mesh representation of open curves.
void update_polygon_after_restart (TriangleMeshPolygon *&polygon_pt)
Updates the polylines representation after restart.
void update_open_curve_after_restart (TriangleMeshOpenCurve *&open_curve_pt)
Updates the open curve representation after restart.
bool update_polygon_using_elements_area (TriangleMeshPolygon *&polygon_pt, const Vector< double > &target_area)
Updates the polylines using the elements area as constraint for the number of points along the boundaries.
bool update_open_curve_using_elements_area (TriangleMeshOpenCurve *&open_curve_pt, const Vector< double > &target_area)
Updates the open curve but using the elements area instead of the default refinement and unrefinement methods.
bool update_shared_curve_using_elements_area (Vector< TriangleMeshPolyLine * > &vector_polyline_pt, const Vector< double > &target_areas)
Updates the polylines using the elements area as constraint for the number of points along the boundaries.
void update_shared_curve_after_restart (Vector< TriangleMeshPolyLine * > &vector_polyline_pt)
Updates the shared polylines representation after restart.
void initialise_adaptation_data ()
Helper function to initialise data associated with adaptation.
void refine_triangulateio (TriangulateIO &triangulate_io, const Vector< double > &target_area, TriangulateIO &triangle_refine)
Build a new TriangulateIO object from previous TriangulateIO based on target area for each element.
double compute_area_target (const Vector< double > &elem_error, Vector< double > &target_area)
Compute target area based on the element's error and the error target; return minimum angle (in degrees)
Protected Member Functions inherited from oomph::TriangleMesh< ELEMENT >
void build_from_scaffold (TimeStepper *time_stepper_pt, const bool &use_attributes)
Build mesh from scaffold.
void build_triangulateio (const std::string &poly_file_name, TriangulateIO &triangulate_io, bool &use_attributes)
Helper function to create TriangulateIO object (return in triangulate_io) from the .poly file.
void generic_constructor (Vector< TriangleMeshPolygon * > &outer_boundary_pt, Vector< TriangleMeshPolygon * > &internal_polygon_pt, Vector< TriangleMeshOpenCurve * > &open_polylines_pt, const double &element_area, Vector< Vector< double > > &extra_holes_coordinates, std::map< unsigned, Vector< double > > &regions_coordinates, std::map< unsigned, double > &regions_areas, TimeStepper *time_stepper_pt, const bool &use_attributes, const bool &refine_boundary, const bool &refine_internal_boundary)
A general-purpose construction function that builds the mesh once the different specific constructors have assembled the appropriate information.
void shared_boundaries_in_this_processor (Vector< unsigned > &shared_boundaries_in_this_processor)
Get the shared boundaries ids living in the current processor.
const unsigned nshared_boundaries (const unsigned &p, const unsigned &q) const
Access functions to boundaries shared with processors.
Vector< Vector< Vector< unsigned > > > shared_boundaries_ids () const
Vector< Vector< Vector< unsigned > > > & shared_boundaries_ids ()
Vector< Vector< unsigned > > shared_boundaries_ids (const unsigned &p) const
Vector< Vector< unsigned > > & shared_boundaries_ids (const unsigned &p)
Vector< unsigned > shared_boundaries_ids (const unsigned &p, const unsigned &q) const
Vector< unsigned > & shared_boundaries_ids (const unsigned &p, const unsigned &q)
const unsigned shared_boundaries_ids (const unsigned &p, const unsigned &q, const unsigned &i) const
const unsigned nshared_boundary_curves (const unsigned &p) const
const unsigned nshared_boundary_polyline (const unsigned &p, const unsigned &c) const
Vector< TriangleMeshPolyLine * > & shared_boundary_polyline_pt (const unsigned &p, const unsigned &c)
TriangleMeshPolyLine * shared_boundary_polyline_pt (const unsigned &p, const unsigned &c, const unsigned &i) const
const unsigned nshared_boundaries () const
const unsigned nshared_boundary_element (const unsigned &b)
void flush_shared_boundary_element ()
void flush_shared_boundary_element (const unsigned &b)
void add_shared_boundary_element (const unsigned &b, FiniteElement *ele_pt)
FiniteElement * shared_boundary_element_pt (const unsigned &b, const unsigned &e)
void flush_face_index_at_shared_boundary ()
void add_face_index_at_shared_boundary (const unsigned &b, const unsigned &i)
int face_index_at_shared_boundary (const unsigned &b, const unsigned &e)
const unsigned nshared_boundary_node (const unsigned &b)
void flush_shared_boundary_node ()
Flush ALL the shared boundary nodes.
void flush_shared_boundary_node (const unsigned &b)
Flush the boundary nodes associated to the shared boundary b.
void add_shared_boundary_node (const unsigned &b, Node *node_pt)
Add the node the shared boundary.
Node * shared_boundary_node_pt (const unsigned &b, const unsigned &n)
bool is_node_on_shared_boundary (const unsigned &b, Node *const &node_pt)
Is the node on the shared boundary.
std::map< unsigned, Vector< unsigned > > & shared_boundary_from_processors ()
Return the association of the shared boundaries with the processors.
Vector< unsigned > & shared_boundary_from_processors (const unsigned &b)
const unsigned nshared_boundary_overlaps_internal_boundary ()
Get the number of shared boundaries overlaping internal boundaries.
const bool shared_boundary_overlaps_internal_boundary (const unsigned &shd_bnd_id)
Checks if the shared boundary overlaps an internal boundary.
const unsigned shared_boundary_overlapping_internal_boundary (const unsigned &shd_bnd_id)
Gets the boundary id of the internal boundary that the shared boundary lies on.
void get_shared_boundaries_overlapping_internal_boundary (const unsigned &internal_bnd_id, Vector< unsigned > &shd_bnd_ids)
Gets the shared boundaries ids that overlap the given internal boundary.
std::map< unsigned, unsigned > & shared_boundary_overlaps_internal_boundary ()
Gets the storage that indicates if a shared boundary is part of an internal boundary.
const bool boundary_was_splitted (const unsigned &b)
Helper function to verify if a given boundary was splitted in the distribution process.
const unsigned nboundary_subpolylines (const unsigned &b)
Gets the number of subpolylines that create the boundarya (useful only when the boundary is marked as split)
Vector< TriangleMeshPolyLine * > & boundary_subpolylines (const unsigned &b)
Gets the vector of auxiliar polylines that will represent the given boundary (useful only when the boundaries were split)
const bool boundary_marked_as_shared_boundary (const unsigned &b, const unsigned &isub)
Returns the value that indicates if a subpolyline of a given boundary continues been used as internal boundary or should be changed as shared boundary.
void flush_shared_boundary_polyline_pt ()
void create_distributed_domain_representation (Vector< TriangleMeshPolygon * > &polygons_pt, Vector< TriangleMeshOpenCurve * > &open_curves_pt)
Creates the distributed domain representation. Joins the original boundaires, shared boundaries and creates connections among them to create the new polygons that represent the distributed domain.
void sort_polylines_helper (Vector< TriangleMeshPolyLine * > &unsorted_polylines_pt, Vector< Vector< TriangleMeshPolyLine * > > &sorted_polylines_pt)
Sorts the polylines so they be continuous and then we can create a closed or open curve from them.
void create_tmp_polygons_helper (Vector< Vector< TriangleMeshPolyLine * > > &polylines_pt, Vector< TriangleMeshPolygon * > &polygons_pt)
Take the polylines from the shared boundaries and create temporary polygon representations of the domain.
void create_tmp_open_curves_helper (Vector< Vector< TriangleMeshPolyLine * > > &sorted_open_curves_pt, Vector< TriangleMeshPolyLine * > &unsorted_shared_to_internal_poly_pt, Vector< TriangleMeshOpenCurve * > &open_curves_pt)
Take the polylines from the original open curves and created new temporaly representations of open curves with the bits of original curves not overlapped by shared boundaries.
void compute_holes_left_by_halo_elements_helper (Vector< Vector< double > > &output_holes_coordinates)
Compute the holes left by the halo elements, those adjacent to the shared boundaries.
void update_holes_information_helper (Vector< TriangleMeshPolygon * > &polygons_pt, Vector< Vector< double > > &output_holes_coordinates)
Keeps those vertices that define a hole, those that are inside closed internal boundaries in the new polygons that define the domain. Delete those outside/inside the outer polygons (this is required since Triangle can not deal with vertices that define holes outside the new outer polygons of the domain)
const int check_connections_of_polyline_nodes (std::set< FiniteElement * > &element_in_processor_pt, const int &root_edge_bnd_id, std::map< std::pair< Node *, Node * >, bool > &overlapped_face, std::map< unsigned, std::map< Node *, bool > > &node_on_bnd_not_overlapped_by_shd_bnd, std::list< Node * > &current_polyline_nodes, std::map< unsigned, std::list< Node * > > &shared_bnd_id_to_sorted_list_node_pt, const unsigned &node_degree, Node *&new_node_pt, const bool called_from_load_balance=false)
Check for any possible connections that the array of sorted nodes have with any previous boundaries or with itself. Return -1 if no connection was found, return -2 if the connection is with the same polyline, return the boundary id of the boundary to which the connection is performed.
void create_shared_polylines_connections ()
Establish the connections of the polylines previously marked as having connections. This connections were marked in the function TriangleMesh::create_polylines_from_halo_elements_helper().
void create_shared_boundaries (OomphCommunicator *comm_pt, const Vector< unsigned > &element_domain, const Vector< GeneralisedElement * > &backed_up_el_pt, const Vector< FiniteElement * > &backed_up_f_el_pt, std::map< Data *, std::set< unsigned > > &processors_associated_with_data, const bool &overrule_keep_as_halo_element_status)
Creates the shared boundaries.
void get_halo_elements_on_all_procs (const unsigned &nproc, const Vector< unsigned > &element_domain, const Vector< GeneralisedElement * > &backed_up_el_pt, std::map< Data *, std::set< unsigned > > &processors_associated_with_data, const bool &overrule_keep_as_halo_element_status, std::map< GeneralisedElement *, unsigned > &element_to_global_index, Vector< Vector< Vector< GeneralisedElement * > > > &output_halo_elements_pt)
Creates the halo elements on all processors Gets the halo elements on all processors, these elements are then used on the function that computes the shared boundaries among the processors.
void get_element_edges_on_boundary (std::map< std::pair< Node *, Node * >, unsigned > &element_edges_on_boundary)
Get the element edges (pair of nodes, edges) that lie on a boundary (used to mark shared boundaries that lie on internal boundaries)
void create_polylines_from_halo_elements_helper (const Vector< unsigned > &element_domain, std::map< GeneralisedElement *, unsigned > &element_to_global_index, std::set< FiniteElement * > &element_in_processor_pt, Vector< Vector< Vector< GeneralisedElement * > > > &input_halo_elements, std::map< std::pair< Node *, Node * >, unsigned > &elements_edges_on_boundary, Vector< Vector< Vector< TriangleMeshPolyLine * > > > &output_polylines_pt)
Creates polylines from the intersection of halo elements on all processors. The new polylines define the shared boundaries in the domain This get the polylines on ALL processors, that is why the three dimensions output_polylines_pt[iproc][ncurve][npolyline].
void break_loops_on_shared_polyline_helper (const unsigned &initial_shd_bnd_id, std::list< Node * > &input_nodes, Vector< FiniteElement * > &input_boundary_element_pt, Vector< int > &input_face_index_element, const int &input_connect_to_the_left, const int &input_connect_to_the_right, Vector< std::list< Node * > > &output_sorted_nodes_pt, Vector< Vector< FiniteElement * > > &output_boundary_element_pt, Vector< Vector< int > > &output_face_index_element, Vector< int > &output_connect_to_the_left, Vector< int > &output_connect_to_the_right)
Break any possible loop created by the sorted list of nodes that is used to create a new shared polyline.
void break_loops_on_shared_polyline_load_balance_helper (const unsigned &initial_shd_bnd_id, std::list< Node * > &input_nodes, Vector< FiniteElement * > &input_boundary_element_pt, Vector< FiniteElement * > &input_boundary_face_element_pt, Vector< int > &input_face_index_element, const int &input_connect_to_the_left, const int &input_connect_to_the_right, Vector< std::list< Node * > > &output_sorted_nodes_pt, Vector< Vector< FiniteElement * > > &output_boundary_element_pt, Vector< Vector< FiniteElement * > > &output_boundary_face_element_pt, Vector< Vector< int > > &output_face_index_element, Vector< int > &output_connect_to_the_left, Vector< int > &output_connect_to_the_right)
Break any possible loop created by the sorted list of nodes that is used to create a new shared polyline (modified version for load balance)
void create_shared_polyline (const unsigned &my_rank, const unsigned &shd_bnd_id, const unsigned &iproc, const unsigned &jproc, std::list< Node * > &sorted_nodes, const int &root_edge_bnd_id, Vector< FiniteElement * > &bulk_bnd_ele_pt, Vector< int > &face_index_ele, Vector< Vector< TriangleMeshPolyLine * > > &unsorted_polylines_pt, const int &connect_to_the_left_flag, const int &connect_to_the_right_flag)
Create the shared polyline and fill the data structured that keep all the information associated with the creationg of the shared boundary.
Protected Member Functions inherited from oomph::UnstructuredTwoDMeshGeometryBase
void build_triangulateio (Vector< TriangleMeshPolygon * > &outer_polygons_pt, Vector< TriangleMeshPolygon * > &internal_polygons_pt, Vector< TriangleMeshOpenCurve * > &open_curves_pt, Vector< Vector< double > > &extra_holes_coordinates, std::map< unsigned, Vector< double > > &regions_coordinates, std::map< unsigned, double > &regions_areas, TriangulateIO &triangulate_io)
Create TriangulateIO object from outer boundaries, internal boundaries, and open curves. Add the holes and regions information as well.
void add_connection_matrix_info_helper (TriangleMeshPolyLine *polyline_pt, std::map< unsigned, std::map< unsigned, Vector< vertex_connection_info > > > &connection_matrix, TriangleMeshPolyLine *next_polyline_pt=0)
Helps to add information to the connection matrix of the given polyline.
void initialise_base_vertex (TriangleMeshPolyLine *polyline_pt, std::map< unsigned, std::map< unsigned, Vector< base_vertex_info > > > &base_vertices)
Initialise the base vertex structure, set every vertex to no visited and not being a base vertex.
void add_base_vertex_info_helper (TriangleMeshPolyLine *polyline_pt, std::map< unsigned, std::map< unsigned, Vector< base_vertex_info > > > &base_vertices, std::map< unsigned, std::map< unsigned, Vector< vertex_connection_info > > > &connection_matrix, std::map< unsigned, std::map< unsigned, unsigned > > &boundary_chunk_nvertices)
Helps to identify the base vertex of the given polyline.
void snap_nodes_onto_geometric_objects ()
Snap the boundary nodes onto any curvilinear boundaries defined by geometric objects.
void copy_connection_information (TriangleMeshCurveSection *input_curve_pt, TriangleMeshCurveSection *output_curve_pt)
Helper function to copy the connection information from the input curve(polyline or curviline) to the output polyline.
void copy_connection_information_to_sub_polylines (TriangleMeshCurveSection *input_curve_pt, TriangleMeshCurveSection *output_curve_pt)
Helper function to copy the connection information from the input curve(polyline or curviline) to the output sub-polyline.
void create_vertex_coordinates_for_polyline_no_connections (TriangleMeshCurviLine *boundary_pt, Vector< Vector< double > > &vertex_coord, Vector< std::pair< double, double > > &polygonal_vertex_arclength_info)
Helper function to create polyline vertex coordinates for curvilinear boundary specified by boundary_pt, using either equal increments in zeta or in (approximate) arclength along the curviline. vertex_coord[i_vertex][i_dim] stores i_dim-th coordinate of i_vertex-th vertex. polygonal_vertex_arclength_info[i_vertex] contains the pair of doubles made of the arclength of the i_vertex-th vertex along the polygonal representation (.first), and the corresponding coordinate on the GeomObject (.second)
void create_vertex_coordinates_for_polyline_connections (TriangleMeshCurviLine *boundary_pt, Vector< Vector< double > > &vertex_coord, Vector< std::pair< double, double > > &polygonal_vertex_arclength_info)
Helper function to create polyline vertex coordinates for curvilinear boundary specified by boundary_pt, using either equal increments in zeta or in (approximate) arclength along the curviline. vertex_coord[i_vertex][i_dim] stores i_dim-th coordinate of i_vertex-th vertex. polygonal_vertex_arclength_info[i_vertex] contains the pair of doubles made of the arclength of the i_vertex-th vertex along the polygonal representation (.first), and the corresponding coordinate on the GeomObject (.second)
TriangleMeshPolygon * closed_curve_to_polygon_helper (TriangleMeshClosedCurve *closed_curve_pt, unsigned &max_bnd_id_local)
Helper function that returns a polygon representation for the given closed curve, it also computes the maximum boundary id of the constituent curves. If the TriangleMeshClosedCurve is already a TriangleMeshPolygon we simply return a pointer to it. Otherwise a new TrilangleMeshPolygon is created -- this is deleted automatically when the TriangleMesh destructor is called, so no external book-keeping is required.
TriangleMeshOpenCurve * create_open_curve_with_polyline_helper (TriangleMeshOpenCurve *open_curve_pt, unsigned &max_bnd_id_local)
Helper function that creates and returns an open curve with the polyline representation of its constituent curve sections. The new created open curve is deleted when the TriangleMesh destructor is called.
void set_geom_objects_and_coordinate_limits_for_close_curve (TriangleMeshClosedCurve *input_closed_curve_pt)
Stores the geometric objects associated to the curve sections that compound the closed curve. It also stores the limits defined by these geometric objects.
void set_geom_objects_and_coordinate_limits_for_open_curve (TriangleMeshOpenCurve *input_open_curve_pt)
Stores the geometric objects associated to the curve sections that compound the open curve. It also stores the limits defined by these geometric objects.
Protected Member Functions inherited from oomph::Mesh
void setup_shared_node_scheme ()
Setup shared node scheme.
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign the global equation numbers in the Data stored at the nodes and also internal element Data. Also, build (via push_back) the Vector of pointers to the dofs (variables).
void describe_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the dofs of the Mesh. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the local dofs of the elements. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers in all elements If the boolean argument is true then also store pointers to dofs.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
A function that upgrades an ordinary node to a boundary node We shouldn't ever really use this, but it does make life that bit easier for the lazy mesh writer. The pointer to the node is replaced by a pointer to the new boundary node in all element look-up schemes and in the mesh's Node_pt vector. The new node is also addressed by node_pt on return from the function.
void convert_to_boundary_node (Node *&node_pt)
A function that upgrades an ordinary node to a boundary node. All pointers to the node from the mesh's elements are found. and replaced by pointers to the new boundary node. If the node is present in the mesh's list of nodes, that pointer is also replaced. Finally, the pointer argument node_pt addresses the new node on return from the function. We shouldn't ever really use this, but it does make life that bit easier for the lazy mesh writer.
Protected Attributes
std::map< unsigned, std::set< Vector< double > > > Boundary_connections_pt
A map that stores the vertices that receive connections, they are identified by the boundary number that receive the connection This is necessary for not erasing them on the adaptation process, specifically for the un-refinement process.
bool Do_boundary_unrefinement_constrained_by_target_areas
Flag that enables or disables boundary unrefinement (true by default)
bool Do_boundary_refinement_constrained_by_target_areas
Flag that enables or disables boundary refinement (true by default)
bool Do_shared_boundary_unrefinement_constrained_by_target_areas
Flag that enables or disables boundary unrefinement (true by default)
bool Do_shared_boundary_refinement_constrained_by_target_areas
Flag that enables or disables boundary unrefinement (true by default)
std::map< unsigned, Vector< Node * > > Sorted_shared_boundary_node_pt
Stores the nodes in the boundaries in the same order in all the processors Sorted_shared_boundary_node_pt[bnd_id][i-th node] = Node* It is a map since the boundary id may not start at zero.
Vector< double > Flat_packed_doubles
Vector of flat-packed doubles to be communicated with other processors.
unsigned Counter_for_flat_packed_doubles
Counter used when processing vector of flat-packed doubles.
Vector< unsigned > Flat_packed_unsigneds
Vector of flat-packed unsigneds to be communicated with other processors.
unsigned Counter_for_flat_packed_unsigneds
Counter used when processing vector of flat-packed unsigneds.
Vector< std::string > Flat_packed_unsigneds_string
Temporary vector of strings to enable full annotation of RefineableTriangleMesh comms.
unsigned Nbin_x_for_area_transfer
Number of bins in the x-direction when transferring target areas by bin method. Only used if we don't have CGAL!
unsigned Nbin_y_for_area_transfer
Number of bins in the y-direction when transferring target areas by bin method. Only used if we don't have CGAL!
unsigned Max_sample_points_for_limited_locate_zeta_during_target_area_transfer
Default value for max. number of sample points used for locate_zeta when transferring target areas using cgal-based sample point container.
double Max_element_size
Max permitted element size.
double Min_element_size
Min permitted element size.
double Min_permitted_angle
Min angle before remesh gets triggered.
bool Disable_projection
Enable/disable solution projection during adaptation.
bool Use_iterative_solver_for_projection
Flag to indicate whether to use or not an iterative solver (CG with diagonal preconditioned) for the projection problem.
bool Print_timings_transfering_target_areas
Enable/disable printing timings for transfering target areas.
bool Print_timings_projection
Enable/disable printing timings for projection.
unsigned Print_timings_level_adaptation
The printing level for adaptation.
unsigned Print_timings_level_load_balance
The printing level for load balance.
MeshUpdateFctPt Mesh_update_fct_pt
Function pointer to function that updates the mesh following the snapping of boundary nodes to the boundaries (e.g. to move boundary nodes very slightly to satisfy volume constraints)
InternalHolePointUpdateFctPt Internal_hole_point_update_fct_pt
Function pointer to function that can be set to update the position of the central point in internal holes.
Protected Attributes inherited from oomph::TriangleMesh< ELEMENT >
std::map< unsigned, double > Regions_areas
Target areas for regions; defaults to 0.0 which (luckily) implies "no specific target area" for triangle!
bool Triangulateio_exists
Boolean defining if Triangulateio object has been built or not.
TriangleScaffoldMesh * Tmp_mesh_pt
Temporary scaffold mesh.
Vector< unsigned > Oomph_vertex_nodes_id
Vector storing oomph-lib node number for all vertex nodes in the TriangulateIO representation of the mesh.
unsigned Initial_shared_boundary_id
The initial boundary id for shared boundaries.
unsigned Final_shared_boundary_id
The final boundary id for shared boundaries.
Vector< Vector< Vector< unsigned > > > Shared_boundaries_ids
Stores the boundaries ids created by the interaction of two processors Shared_boundaries_ids[iproc][jproc] = Vector of shared boundaries ids "iproc" processor shares boundaries with "jproc" processor.
std::map< unsigned, Vector< unsigned > > Shared_boundary_from_processors
Stores the processors involved in the generation of a shared boundary, in 2D two processors give rise to the creation of a shared boundary.
std::map< unsigned, unsigned > Shared_boundary_overlaps_internal_boundary
Stores information about those shared boundaries that lie over or over a segment of an internal boundary (only used when using internal boundaries in the domain)
Vector< Vector< Vector< TriangleMeshPolyLine * > > > Shared_boundary_polyline_pt
Stores the polyline representation of the shared boundaries Shared_boundary_polyline_pt[iproc][ncurve][npolyline] = polyline_pt.
std::map< unsigned, Vector< FiniteElement * > > Shared_boundary_element_pt
Stores the boundary elements adjacent to the shared boundaries, these elements are a subset of the halo and haloed elements.
std::map< unsigned, Vector< int > > Face_index_at_shared_boundary
For the e-th finite element on shared boundary b, this is the index of the face that lies along that boundary.
std::map< unsigned, Vector< Node * > > Shared_boundary_node_pt
Stores the boundary nodes adjacent to the shared boundaries, these nodes are a subset of the halo and haloed nodes.
std::map< unsigned, bool > Boundary_was_splitted
Flag to indicate if a polyline has been splitted during the distribution process, the boundary id of the polyline is used to indicate if spplited.
std::map< unsigned, Vector< TriangleMeshPolyLine * > > Boundary_subpolylines
The polylines that will temporary represent the boundary that was splitted in the distribution process. Used to ease the sending of info. to Triangle during the adaptation process.
std::map< unsigned, std::vector< bool > > Boundary_marked_as_shared_boundary
Flag to indicate if an internal boundary will be used as shared boundary because there is overlapping of the internal boundary with the shared boundary.
bool First_time_compute_holes_left_by_halo_elements
Flag to know if it is the first time we are going to compute the holes left by the halo elements.
Vector< Vector< double > > Original_extra_holes_coordinates
Backup the original extra holes coordinates.
Protected Attributes inherited from oomph::TriangleMeshBase
TriangulateIO Triangulateio
TriangulateIO representation of the mesh.
bool Use_triangulateio_restart
Should we use triangulateio specific parts for dump/restart? (Doesn't work with some elements and isn't needed if not using adaptivity).
Protected Attributes inherited from oomph::UnstructuredTwoDMeshGeometryBase
std::map< unsigned, Vector< Vector< Node * > > > Boundary_segment_node_pt
Used to store the nodes associated to a boundary and to an specific segment (this only applies in distributed meshes where the boundary is splitted in segments)
std::map< unsigned, Vector< double > > Boundary_segment_initial_zeta
Stores the initial zeta coordinate for the segments that appear when a boundary is splited among processors.
std::map< unsigned, Vector< double > > Boundary_segment_final_zeta
Stores the final zeta coordinate for the segments that appear when a boundary is splited among processors.
std::map< unsigned, Vector< double > > Boundary_initial_coordinate
Stores the initial coordinates for the boundary.
std::map< unsigned, Vector< double > > Boundary_final_coordinate
Stores the final coordinates for the boundary.
std::map< unsigned, Vector< unsigned > > Boundary_segment_inverted
Stores the info. to know if it is necessary to reverse the segment based on a previous mesh.
std::map< unsigned, Vector< double > > Boundary_initial_zeta_coordinate
Stores the initial zeta coordinate for the boundary.
std::map< unsigned, Vector< double > > Boundary_final_zeta_coordinate
Stores the final zeta coordinate for the boundary.
std::map< unsigned, Vector< double > > Boundary_segment_initial_arclength
Stores the initial arclength for the segments that appear when a boundary is splited among processors.
std::map< unsigned, Vector< double > > Boundary_segment_final_arclength
Stores the final arclength for the segments that appear when a boundary is splited among processors.
std::map< unsigned, Vector< Vector< double > > > Boundary_segment_initial_coordinate
Stores the initial coordinates for the segments that appear when a boundary is splited among processors.
std::map< unsigned, Vector< Vector< double > > > Boundary_segment_final_coordinate
Stores the final coordinates for the segments that appear when a boundary is splited among processors.
bool Allow_automatic_creation_of_vertices_on_boundaries
Flag to indicate whether the automatic creation of vertices along the boundaries by Triangle is allowed.
std::map< unsigned, Vector< FiniteElement * > > Region_element_pt
Vector of elements in each region differentiated by attribute (the key of the map is the attribute)
Vector< double > Region_attribute
Vector of attributes associated with the elements in each region.
std::map< unsigned, GeomObject * > Boundary_geom_object_pt
Storage for the geometric objects associated with any boundaries.
std::map< unsigned, Vector< double > > Boundary_coordinate_limits
Storage for the limits of the boundary coordinates defined by the use of geometric objects. Only used for curvilinear boundaries.
Vector< TriangleMeshPolygon * > Outer_boundary_pt
Polygon that defines outer boundaries.
Vector< TriangleMeshPolygon * > Internal_polygon_pt
Vector of polygons that define internal polygons.
Vector< TriangleMeshOpenCurve * > Internal_open_curve_pt
Vector of open polylines that define internal curves.
Vector< Vector< double > > Extra_holes_coordinates
Storage for extra coordinates for holes.
std::map< unsigned, Vector< double > > Regions_coordinates
Storage for extra coordinates for regions. The key on the map is the region id.
std::map< unsigned, TriangleMeshCurveSection * > Boundary_curve_section_pt
A map that stores the associated curve section of the specified boundary id.
Vector< std::map< unsigned, Vector< FiniteElement * > > > Boundary_region_element_pt
Storage for elements adjacent to a boundary in a particular region.
Vector< std::map< unsigned, Vector< int > > > Face_index_region_at_boundary
Storage for the face index adjacent to a boundary in a particular region.
std::map< unsigned, Vector< std::pair< double, double > > > Polygonal_vertex_arclength_info
Storage for pairs of doubles representing: .first: the arclength along the polygonal representation of the curviline .second: the corresponding intrinsic coordinate on the associated geometric object at which the vertices on the specified boundary are located. Only used for boundaries represented by geom objects.
std::map< unsigned, std::set< Node * > > Nodes_on_boundary_pt
Stores a pointer to a set with all the nodes related with a boundary.
std::set< TriangleMeshCurveSection * > Free_curve_section_pt
A set that contains the curve sections created by this object therefore it is necessary to free their associated memory.
std::set< TriangleMeshPolygon * > Free_polygon_pt
A set that contains the polygons created by this object therefore it is necessary to free their associated memory.
std::set< TriangleMeshOpenCurve * > Free_open_curve_pt
A set that contains the open curves created by this object therefore it is necessary to free their associated memory.
bool Immersed_rigid_body_triangle_mesh_polygon_used
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
Vector of Vector of pointers to nodes on the boundaries: Boundary_node_pt(b,n). Note that this is private to force the use of the add_boundary_node() function, which ensures that the reverse look-up schemes for the nodes are set up.
bool Lookup_for_elements_next_boundary_is_setup
Flag to indicate that the lookup schemes for elements that are adjacent to the boundaries has been set up.
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector of Vector of pointers to elements on the boundaries: Boundary_element_pt(b,e)
Vector< Vector< int > > Face_index_at_boundary
For the e-th finite element on boundary b, this is the index of the face that lies along that boundary.
std::map< unsigned, Vector< GeneralisedElement * > > Root_halo_element_pt
Map of vectors holding the pointers to the root halo elements.
std::map< unsigned, Vector< GeneralisedElement * > > Root_haloed_element_pt
Map of vectors holding the pointers to the root haloed elements.
std::map< unsigned, Vector< Node * > > Halo_node_pt
Map of vectors holding the pointers to the halo nodes.
std::map< unsigned, Vector< Node * > > Haloed_node_pt
Map of vectors holding the pointers to the haloed nodes.
std::map< unsigned, Vector< Node * > > Shared_node_pt
Map of vectors holding the pointers to the shared nodes. These are all the nodes that are on two "neighbouring" processes (the halo(ed) lookup scheme depends upon which processor is in charge.
OomphCommunicator * Comm_pt
Pointer to communicator -- set to NULL if mesh is not distributed.
std::map< unsigned, Vector< GeneralisedElement * > > External_halo_element_pt
External halo(ed) elements are created as and when they are needed to act as source elements for the particular process's mesh. The storage is wiped and rebuilt every time the mesh is refined.
std::map< unsigned, Vector< GeneralisedElement * > > External_haloed_element_pt
Map of vectors holding the pointers to the external haloed elements.
std::map< unsigned, Vector< Node * > > External_halo_node_pt
Map of vectors holding the pointers to the external halo nodes.
std::map< unsigned, Vector< Node * > > External_haloed_node_pt
Map of vectors holding the pointers to the external haloed nodes.
bool Keep_all_elements_as_halos
bool to indicate whether to keep all elements in a mesh as halos or not
bool Resize_halo_nodes_not_required
Set this to true to suppress resizing of halo nodes (at your own risk!)
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
Protected Attributes inherited from oomph::RefineableMeshBase
ErrorEstimator * Spatial_error_estimator_pt
Pointer to spatial error estimator.
double Max_permitted_error
Max. error (i.e. split elements if their error is larger)
double Min_permitted_error
Min. error (i.e. (try to) merge elements if their error is smaller)
double Min_error
Min.actual error.
double Max_error
Max. actual error.
unsigned Nrefined
Stats: Number of elements that were refined.
unsigned Nunrefined
Stats: Number of elements that were unrefined.
bool Adapt_flag
Flag that requests adaptation.
bool P_adapt_flag
Flag that requests p-adaptation.
bool Additional_synchronisation_of_hanging_nodes_not_required
Flag that disables additional synchronisation of hanging nodes.
DocInfo * Doc_info_pt
Pointer to DocInfo.
unsigned Max_keep_unrefined
Max. number of elements that can remain unrefined if no other mesh adaptation is required (to avoid mesh-adaptations that would only unrefine a few elements and then force a new solve -- this can't be worth our while!)
unsigned Nrefinement_overruled
Number of elements that would like to be refined further but can't because they've reached the max. refinement level.
Additional Inherited Members
Public Attributes inherited from oomph::TriangleMesh< ELEMENT >
TimeStepper * Time_stepper_pt
Timestepper used to build elements.
bool Use_attributes
Boolean flag to indicate whether to use attributes or not (required for multidomain meshes)
Public Attributes inherited from oomph::UnstructuredTwoDMeshGeometryBase
std::map< unsigned, bool > Assigned_segments_initial_zeta_values
Flag used at the setup_boundary_coordinate function to know if initial zeta values for segments have been assigned.
Public Attributes inherited from oomph::Mesh
bool Output_halo_elements
Bool for output of halo elements.
Static Public Attributes inherited from oomph::UnstructuredTwoDMeshGeometryBase
static bool Suppress_warning_about_regions_and_boundaries = true
Public static flag to suppress warning; defaults to false.
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
Default Steady Timestepper, to be used in default arguments to Mesh constructors.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Boolean used to control warning about empty mesh level timestepper function.
Detailed Description
template<class ELEMENT>
class oomph::RefineableTriangleMesh< ELEMENT >
Unstructured refineable Triangle Mesh.
Definition at line 2223 of file meshes/triangle_mesh.h.
Member Typedef Documentation
InternalHolePointUpdateFctPt
template<class ELEMENT >
typedef void(* oomph::RefineableTriangleMesh< ELEMENT >::InternalHolePointUpdateFctPt) (const unsigned &ihole, TriangleMeshPolygon *poly_pt)
Function pointer to a function that can generate a point within the ihole-th hole, so that this can be overloaded by the user if they have a better way of doing it than our clunky default. The function should update the components of the Vector poly_pt->internal_point()
Definition at line 2239 of file meshes/triangle_mesh.h.
MeshUpdateFctPt
template<class ELEMENT >
typedef void(* oomph::RefineableTriangleMesh< ELEMENT >::MeshUpdateFctPt) (Mesh *mesh_pt)
Function pointer to function that updates the mesh following the snapping of boundary nodes to the boundaries (e.g. to move boundary nodes very slightly to satisfy volume constraints)
Definition at line 2231 of file meshes/triangle_mesh.h.
Constructor & Destructor Documentation
RefineableTriangleMesh() [1/3]
template<class ELEMENT >
oomph::RefineableTriangleMesh< ELEMENT >::RefineableTriangleMesh (TriangleMeshParameters & triangle_mesh_parameters, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Build mesh, based on the specifications on TriangleMeshParameters.
Definition at line 2246 of file meshes/triangle_mesh.h.
RefineableTriangleMesh() [2/3]
template<class ELEMENT >
oomph::RefineableTriangleMesh< ELEMENT >::RefineableTriangleMesh (const std::string & node_file_name, const std::string & element_file_name, const std::string & poly_file_name, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & allow_automatic_creation_of_vertices_on_boundaries = true) [inline]
Build mesh, based on the polyfiles.
Definition at line 2261 of file meshes/triangle_mesh.h.
RefineableTriangleMesh() [3/3]
template<class ELEMENT >
oomph::RefineableTriangleMesh< ELEMENT >::RefineableTriangleMesh (const Vector< double > & target_area, TriangulateIO & triangulate_io, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false, const bool & allow_automatic_creation_of_vertices_on_boundaries = true, OomphCommunicator * comm_pt = 0) [inline], [protected]
Build mesh from specified triangulation and associated target areas for elements in it NOTE: This is used ONLY during adaptation and should not be used as a method of constructing a TriangleMesh object in demo drivers!
Definition at line 2292 of file meshes/triangle_mesh.h.
References oomph::TriangleHelper::clear_triangulateio(), oomph::TriangleHelper::initialise_triangulateio(), and oomph::triangulate().
~RefineableTriangleMesh()
template<class ELEMENT >
virtual oomph::RefineableTriangleMesh< ELEMENT >::~RefineableTriangleMesh () [inline], [virtual]
Empty Destructor.
Definition at line 2384 of file meshes/triangle_mesh.h.
Member Function Documentation
adapt()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::adapt (const Vector< double > & elem_error) [virtual]
Adapt mesh, based on elemental error provided.
Adapt problem based on specified elemental error estimates This function implement serial and parallel mesh adaptation, the sections for parallel mesh adaptation are clearly identified by checking whether the mesh is distributed or not.
Implements oomph::RefineableMeshBase.
Definition at line 29597 of file triangle_mesh.template.cc.
References oomph::TriangleHelper::clear_triangulateio(), oomph::TriangleHelper::deep_copy_of_triangulateio_representation(), oomph::Multi_domain_functions::Doc_full_stats, oomph::Multi_domain_functions::Doc_stats, oomph::Multi_domain_functions::Doc_timings, e, i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::GeneralisedElement::is_halo(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::Node_pt, oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), oomph::oomph_info, oomph::Node::resize(), s, oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), oomph::TimingHelpers::timer(), and oomph::Node::x().
add_element_load_balance_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::add_element_load_balance_helper (const unsigned & iproc, Vector< Vector< std::map< unsigned, FiniteElement * > > > & received_old_haloed_element_pt, FiniteElement * ele_pt) [protected]
Helper function to create elements on the loop process based on the info received in send_and_received_elements_nodes_info This function is in charge of verify if the element is associated to a boundary and associate to it if that is the case.
Definition at line 27585 of file triangle_mesh.template.cc.
References oomph::oomph_info, and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
add_halo_element_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::add_halo_element_helper (unsigned & iproc, FiniteElement * ele_pt) [protected]
Helper function to create (halo) elements on the loop process based on the info received in send_and_received_located_info This function is in charge of verify if the element is associated to a boundary.
Definition at line 19199 of file triangle_mesh.template.cc.
References oomph::oomph_info, and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
add_halo_node_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::add_halo_node_helper (Node *& new_nod_pt, Vector< Node * > & new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node * > > > > & other_proc_shd_bnd_node_pt, unsigned & iproc, unsigned & node_index, FiniteElement *const & new_el_pt, Vector< Vector< Vector< unsigned > > > & global_node_names, std::map< Vector< unsigned >, unsigned > & node_name_to_global_index, Vector< Node * > & global_shared_node_pt) [protected]
Helper function to add halo node.
Definition at line 19360 of file triangle_mesh.template.cc.
References oomph::FiniteElement::node_pt(), oomph::oomph_info, and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
add_haloed_node_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::add_haloed_node_helper (unsigned & iproc, Node * nod_pt) [protected]
Helper function to add haloed node.
Helper to add external haloed node that is not a master.
Definition at line 18903 of file triangle_mesh.template.cc.
References oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
add_node_load_balance_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::add_node_load_balance_helper (unsigned & iproc, Vector< Vector< FiniteElement * > > & f_halo_ele_pt, Vector< Node * > & new_nodes_on_domain, Node * nod_pt) [protected]
Helper function to add haloed node.
Helper function to add nodes on a new domain as a result of load balance.
Definition at line 26753 of file triangle_mesh.template.cc.
References oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
add_non_delete_vertices_from_boundary_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::add_non_delete_vertices_from_boundary_helper (Vector< Vector< Node * > > src_bound_segment_node_pt, Vector< Vector< Node * > > dst_bound_segment_node_pt, const unsigned & dst_bnd_id, const unsigned & dst_bnd_chunk) [protected]
Adds the vertices from the sources boundary that are repeated in the destination boundary to the list of non delete-able vertices in the destination boundary.
Definition at line 32579 of file triangle_mesh.template.cc.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
add_received_node_load_balance_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::add_received_node_load_balance_helper (Node *& new_nod_pt, Vector< Vector< FiniteElement * > > & f_haloed_ele_pt, Vector< Vector< std::map< unsigned, FiniteElement * > > > & received_old_haloed_element_pt, Vector< Node * > & new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node * > > > > & other_proc_shd_bnd_node_pt, unsigned & iproc, unsigned & node_index, FiniteElement *const & new_el_pt, Vector< Vector< Vector< unsigned > > > & global_node_names, std::map< Vector< unsigned >, unsigned > & node_name_to_global_index, Vector< Node * > & global_shared_node_pt) [protected]
Helper function to add a new node from load balance.
Definition at line 27842 of file triangle_mesh.template.cc.
References oomph::FiniteElement::node_pt(), oomph::oomph_info, and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
add_vertices_for_non_deletion()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::add_vertices_for_non_deletion () [protected]
Mark the vertices that are not allowed for deletion by the unrefienment/refinement polyline methods. In charge of filling the Boundary_chunk_connections_pt structure.
Mark the vertices that are not allowed for deletion by the unrefienment/refinement polyline methods. In charge of filling the Boundary_connections_pt structure.
Definition at line 31869 of file triangle_mesh.template.cc.
References i, oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
apply_max_length_constraint()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::apply_max_length_constraint (Mesh * face_mesh_pt, Vector< Vector< double > > & vector_bnd_vertices, double & max_length_constraint) [protected]
Get the size of the vector that now includes all added nodes
Definition at line 35539 of file triangle_mesh.template.cc.
References i, oomph::FiniteElement::position(), s, oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
boundary_connections()
template<class ELEMENT >
const bool oomph::RefineableTriangleMesh< ELEMENT >::boundary_connections (const unsigned & b, const unsigned & c, std::set< Vector< double > > & vertices) [inline], [protected]
Verifies if the given boundary receives a connection, and if that is the case then returns the list of vertices that receive the connections.
Definition at line 2902 of file meshes/triangle_mesh.h.
compute_area_target()
template<class ELEMENT >
double oomph::RefineableTriangleMesh< ELEMENT >::compute_area_target (const Vector< double > & elem_error, Vector< double > & target_area) [inline], [protected]
Compute target area based on the element's error and the error target; return minimum angle (in degrees)
Definition at line 3669 of file meshes/triangle_mesh.h.
References e, oomph::FiniteElement::node_pt(), oomph::oomph_info, oomph::MathematicalConstants::Pi, oomph::FiniteElement::size(), and oomph::Node::x().
compute_global_node_names_and_shared_nodes()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::compute_global_node_names_and_shared_nodes (Vector< Vector< Vector< std::map< unsigned, Node * > > > > & other_proc_shd_bnd_node_pt, Vector< Vector< Vector< unsigned > > > & global_node_names, std::map< Vector< unsigned >, unsigned > & node_name_to_global_index, Vector< Node * > & global_shared_node_pt) [protected]
Compute the names of the nodes on shared boundaries in this (my_rank) processor with other processors. Also compute the names of nodes on shared boundaries of other processors with other processors (useful when there is an element that requires to be sent to this (my_rank) processor because there is a shared node between this (my_rank) and other processors BUT there is not a shared boundary between this and the other processor.
Definition at line 16060 of file triangle_mesh.template.cc.
References e, i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::Node::x().
compute_shared_node_degree_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::compute_shared_node_degree_helper (Vector< Vector< FiniteElement * > > & unsorted_face_ele_pt, std::map< Node *, unsigned > & global_node_degree)
Computes the degree of the nodes on the shared boundaries, the degree of the node is computed from the global graph created by the shared boundaries of all processors.
Definition at line 24846 of file triangle_mesh.template.cc.
References i, oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
construct_new_halo_node_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::construct_new_halo_node_helper (Node *& new_nod_pt, Vector< Node * > & new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node * > > > > & other_proc_shd_bnd_node_pt, unsigned & iproc, unsigned & node_index, FiniteElement *const & new_el_pt, Vector< Vector< Vector< unsigned > > > & global_node_names, std::map< Vector< unsigned >, unsigned > & node_name_to_global_index, Vector< Node * > & global_shared_node_pt) [protected]
Helper function which constructs a new halo node (on an element) with the information sent from the haloed process.
The first entry of All_alg_nodal_info contains the default node update id e.g. for the quarter circle there are "Upper_left_box", "Lower right box" etc...
again we need the size of this vector as it varies between meshes; we also need some indication as to which geometric object should be used...
For the received update_id, ref_value, geom_object call add_node_update_info
Now call update_node_update
Definition at line 19416 of file triangle_mesh.template.cc.
References oomph::FiniteElement::construct_boundary_node(), oomph::FiniteElement::construct_node(), i, oomph::FiniteElement::local_coordinate_of_node(), oomph::GeomObject::ndim(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), oomph::oomph_info, oomph::FiniteElement::size(), t, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::GeomObject::time_stepper_pt().
construct_new_node_load_balance_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::construct_new_node_load_balance_helper (Node *& new_nod_pt, Vector< Vector< FiniteElement * > > & f_haloed_ele_pt, Vector< Vector< std::map< unsigned, FiniteElement * > > > & received_old_haloed_element_pt, Vector< Node * > & new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node * > > > > & other_proc_shd_bnd_node_pt, unsigned & iproc, unsigned & node_index, FiniteElement *const & new_el_pt, Vector< Vector< Vector< unsigned > > > & global_node_names, std::map< Vector< unsigned >, unsigned > & node_name_to_global_index, Vector< Node * > & global_shared_node_pt) [protected]
Helper function which constructs a new node (on an element) with the information sent from the load balance process.
The first entry of All_alg_nodal_info contains the default node update id e.g. for the quarter circle there are "Upper_left_box", "Lower right box" etc...
again we need the size of this vector as it varies between meshes; we also need some indication as to which geometric object should be used...
For the received update_id, ref_value, geom_object call add_node_update_info
Now call update_node_update
Definition at line 27906 of file triangle_mesh.template.cc.
References oomph::FiniteElement::construct_boundary_node(), oomph::FiniteElement::construct_node(), i, oomph::FiniteElement::local_coordinate_of_node(), oomph::GeomObject::ndim(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), oomph::oomph_info, oomph::FiniteElement::size(), t, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::GeomObject::time_stepper_pt().
create_adjacency_matrix_new_shared_edges_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::create_adjacency_matrix_new_shared_edges_helper (Vector< Vector< FiniteElement * > > & unsorted_face_ele_pt, Vector< Vector< Node * > > & tmp_sorted_shared_node_pt, std::map< Node *, Vector< Vector< unsigned > > > & node_alias, Vector< Vector< Vector< unsigned > > > & adjacency_matrix)
Sort the nodes on the new shared boundaries (after load balancing), computes the alias of the nodes and creates the adjacency matrix that represent the graph created by the shared edges between each pair of processors.
Definition at line 25845 of file triangle_mesh.template.cc.
References e, i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
create_element_load_balance_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::create_element_load_balance_helper (unsigned & iproc, Vector< Vector< FiniteElement * > > & f_haloed_ele_pt, Vector< Vector< std::map< unsigned, FiniteElement * > > > & received_old_haloed_element_pt, Vector< FiniteElement * > & new_elements_on_domain, Vector< Node * > & new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node * > > > > & other_proc_shd_bnd_node_pt, Vector< Vector< Vector< unsigned > > > & global_node_names, std::map< Vector< unsigned >, unsigned > & node_name_to_global_index, Vector< Node * > & global_shared_node_pt) [protected]
Helper function to create elements on the loop process based on the info received in send_and_received_elements_nodes_info.
Definition at line 27502 of file triangle_mesh.template.cc.
References oomph::FiniteElement::nnode(), oomph::oomph_info, and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
create_halo_element()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::create_halo_element (unsigned & iproc, Vector< Node * > & new_nodes_on_domain, Vector< Vector< Vector< std::map< unsigned, Node * > > > > & other_proc_shd_bnd_node_pt, Vector< Vector< Vector< unsigned > > > & global_node_names, std::map< Vector< unsigned >, unsigned > & node_name_to_global_index, Vector< Node * > & global_shared_node_pt) [protected]
Helper function to create (halo) elements on the loop process based on the info received in send_and_received_located_info.
Creates (halo) element on the loop process based on the information received from each processor.
Definition at line 19111 of file triangle_mesh.template.cc.
References oomph::FiniteElement::nnode(), oomph::oomph_info, and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
create_new_shared_boundaries()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::create_new_shared_boundaries (std::set< FiniteElement * > & element_in_processor_pt, Vector< Vector< FiniteElement * > > & new_shared_boundary_element_pt, Vector< Vector< unsigned > > & new_shared_boundary_element_face_index)
Creates the new shared boundaries, this method is also in charge of computing the shared boundaries ids of each processor and send that info. to all the processors.
Definition at line 22703 of file triangle_mesh.template.cc.
References e, oomph::TriangleMeshCurveSection::final_vertex_connected_bnd_id(), oomph::TriangleMeshCurveSection::final_vertex_connected_n_chunk(), i, oomph::TriangleMeshCurveSection::initial_vertex_connected_bnd_id(), oomph::TriangleMeshCurveSection::initial_vertex_connected_n_chunk(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::oomph_info, oomph::TriangleMeshCurveSection::set_final_vertex_connected(), oomph::TriangleMeshCurveSection::set_initial_vertex_connected(), oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), oomph::TimingHelpers::timer(), and oomph::Node::x().
create_polylines_from_polyfiles()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::create_polylines_from_polyfiles (const std::string & node_file_name, const std::string & poly_file_name)
Helper function to create polylines and fill associate data.
Create the polylines and fill associate data structures, used when creating from a mesh from polyfiles.
Definition at line 36625 of file triangle_mesh.template.cc.
References i, oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
create_sorted_face_mesh_representation()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::create_sorted_face_mesh_representation (const unsigned & boundary_id, Mesh * face_mesh_pt, std::map< FiniteElement *, bool > & is_inverted, bool & inverted_face_mesh) [protected]
Helper function Creates a sorted face mesh representation of the specified PolyLine It means that the elements are sorted along the boundary It also returns a map that indicated the inverted elements.
Helper function Creates a sorted face mesh representation of the specified PolyLine It means that the elements are sorted along the boundary.
Definition at line 35690 of file triangle_mesh.template.cc.
References e, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error.
create_temporary_boundary_connections()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::create_temporary_boundary_connections (Vector< TriangleMeshPolygon * > & tmp_outer_polygons_pt, Vector< TriangleMeshOpenCurve * > & tmp_open_curves_pt) [protected]
After unrefinement and refinement has taken place compute the new vertices numbers of the temporary representation of the.
Definition at line 33042 of file triangle_mesh.template.cc.
References i, oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
create_unsorted_face_mesh_representation()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::create_unsorted_face_mesh_representation (const unsigned & boundary_id, Mesh * face_mesh_pt) [protected]
Helper function Creates an unsorted face mesh representation from the specified boundary id. It means that the elements are not sorted along the boundary.
Definition at line 35657 of file triangle_mesh.template.cc.
References e, and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
disable_boundary_refinement_constrained_by_target_areas()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::disable_boundary_refinement_constrained_by_target_areas () [inline]
Definition at line 2865 of file meshes/triangle_mesh.h.
disable_boundary_unrefinement_constrained_by_target_areas()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::disable_boundary_unrefinement_constrained_by_target_areas () [inline]
Definition at line 2855 of file meshes/triangle_mesh.h.
disable_iterative_solver_for_projection()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::disable_iterative_solver_for_projection () [inline]
Enables the use of an iterative solver for the projection problem.
Definition at line 2483 of file meshes/triangle_mesh.h.
disable_print_timings_adaptation()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::disable_print_timings_adaptation () [inline]
Disables printing of timings for adaptation.
Definition at line 2495 of file meshes/triangle_mesh.h.
disable_print_timings_load_balance()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::disable_print_timings_load_balance () [inline]
Disables printing of timings for load balance.
Definition at line 2522 of file meshes/triangle_mesh.h.
disable_projection()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::disable_projection () [inline]
Disables the solution projection step during adaptation.
Definition at line 2407 of file meshes/triangle_mesh.h.
disable_shared_boundary_refinement_constrained_by_target_areas()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::disable_shared_boundary_refinement_constrained_by_target_areas () [inline]
Definition at line 2887 of file meshes/triangle_mesh.h.
disable_shared_boundary_unrefinement_constrained_by_target_areas()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::disable_shared_boundary_unrefinement_constrained_by_target_areas () [inline]
Definition at line 2877 of file meshes/triangle_mesh.h.
disable_timings_projection()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::disable_timings_projection () [inline]
Disables info. and timings for projection.
Definition at line 2419 of file meshes/triangle_mesh.h.
disable_timings_tranfering_target_areas()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::disable_timings_tranfering_target_areas () [inline]
Disables info. and timings for tranferring of target areas.
Definition at line 2395 of file meshes/triangle_mesh.h.
doc_adaptivity_targets()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::doc_adaptivity_targets (std::ostream & outfile) [inline], [virtual]
Doc the targets for mesh adaptation.
Reimplemented from oomph::RefineableMeshBase.
Definition at line 2543 of file meshes/triangle_mesh.h.
enable_boundary_refinement_constrained_by_target_areas()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::enable_boundary_refinement_constrained_by_target_areas () [inline]
Definition at line 2860 of file meshes/triangle_mesh.h.
enable_boundary_unrefinement_constrained_by_target_areas()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::enable_boundary_unrefinement_constrained_by_target_areas () [inline]
Enable/disable unrefinement/refinement methods for original boundaries.
Definition at line 2850 of file meshes/triangle_mesh.h.
enable_iterative_solver_for_projection()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::enable_iterative_solver_for_projection () [inline]
Enables the use of an iterative solver for the projection problem.
Definition at line 2476 of file meshes/triangle_mesh.h.
enable_print_timings_adaptation()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::enable_print_timings_adaptation (const unsigned & print_level = 1) [inline]
Enables printing of timings for adaptation.
Definition at line 2489 of file meshes/triangle_mesh.h.
enable_print_timings_load_balance()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::enable_print_timings_load_balance (const unsigned & print_level = 1) [inline]
Enables printing of timings for load balance.
Definition at line 2516 of file meshes/triangle_mesh.h.
enable_projection()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::enable_projection () [inline]
Enables the solution projection step during adaptation.
Definition at line 2401 of file meshes/triangle_mesh.h.
enable_shared_boundary_refinement_constrained_by_target_areas()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::enable_shared_boundary_refinement_constrained_by_target_areas () [inline]
Definition at line 2882 of file meshes/triangle_mesh.h.
enable_shared_boundary_unrefinement_constrained_by_target_areas()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::enable_shared_boundary_unrefinement_constrained_by_target_areas () [inline]
Enable/disable unrefinement/refinement methods for shared boundaries.
Definition at line 2872 of file meshes/triangle_mesh.h.
enable_timings_projection()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::enable_timings_projection () [inline]
Enables info. and timings for projection.
Definition at line 2413 of file meshes/triangle_mesh.h.
enable_timings_tranfering_target_areas()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::enable_timings_tranfering_target_areas () [inline]
Enables info. and timings for tranferring of target areas.
Definition at line 2388 of file meshes/triangle_mesh.h.
fill_boundary_elements_and_nodes_for_internal_boundaries() [1/2]
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::fill_boundary_elements_and_nodes_for_internal_boundaries ()
Definition at line 43424 of file triangle_mesh.template.cc.
fill_boundary_elements_and_nodes_for_internal_boundaries() [2/2]
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::fill_boundary_elements_and_nodes_for_internal_boundaries (std::ofstream & outfile)
Definition at line 43436 of file triangle_mesh.template.cc.
References i, and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
flush_sorted_shared_boundary_node()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::flush_sorted_shared_boundary_node () [inline]
Definition at line 2630 of file meshes/triangle_mesh.h.
get_boundary_segment_nodes_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::get_boundary_segment_nodes_helper (const unsigned & b, Vector< Vector< Node * > > & tmp_segment_nodes)
Get the nodes on the boundary (b), these are stored in the segment they belong (also used by the load balance method to re-set the number of segments per boundary after load balance has taken place)
Definition at line 29074 of file triangle_mesh.template.cc.
References e, oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
get_connected_vertex_number_on_dst_boundary()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::get_connected_vertex_number_on_dst_boundary (Vector< double > & vertex_coordinates, const unsigned & dst_b_id, unsigned & vertex_number) [protected]
Computes the associated vertex number on the destination boundary.
Gets the associated vertex number according to the vertex coordinates on the destination boundary.
Definition at line 34082 of file triangle_mesh.template.cc.
References i, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error.
get_face_mesh_representation() [1/2]
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::get_face_mesh_representation (TriangleMeshOpenCurve * open_polyline_pt, Vector< Mesh * > & face_mesh_pt) [protected]
Helper function to construct face mesh representation of open curves.
Helper function to construct face mesh representation of all polylines.
Definition at line 36410 of file triangle_mesh.template.cc.
References oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
get_face_mesh_representation() [2/2]
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::get_face_mesh_representation (TriangleMeshPolygon * polygon_pt, Vector< Mesh * > & face_mesh_pt) [protected]
Helper function to construct face mesh representation of all polylines, possibly with segments re-distributed between polylines to maintain an appxroximately even sub-division of the polygon.
Helper function to construct face mesh representation of all polylines, possibly with segments re-distributed between polylines to maintain an approximately even sub-division of the polygon.
Definition at line 35881 of file triangle_mesh.template.cc.
References e, i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), s, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::Node::x().
get_required_elemental_information_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::get_required_elemental_information_helper (unsigned & iproc, FiniteElement * ele_pt) [protected]
Helper function to get the required elemental information from an haloed element. This info. involves the association of the element to a boundary or region.
Definition at line 17993 of file triangle_mesh.template.cc.
References e, i, and oomph::FiniteElement::size().
get_required_elemental_information_load_balance_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::get_required_elemental_information_load_balance_helper (unsigned & iproc, Vector< Vector< FiniteElement * > > & f_haloed_ele_pt, FiniteElement * ele_pt) [protected]
Helper function to get the required elemental information from the element to be sent. This info. involves the association of the element to a boundary or region, and if its part of the halo(ed) elements within a processor.
Helper function to get the required elemental information from the element that will be sent to iproc processor. This info. involves the association of the element to a boundary or region.
Definition at line 26361 of file triangle_mesh.template.cc.
References e, i, oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
get_required_nodal_information_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::get_required_nodal_information_helper (unsigned & iproc, Node * nod_pt) [protected]
Helper function to get the required nodal information from a haloed node so that a fully-functional halo node (and therefore element) can be created on the receiving process.
Helper function to get the required nodal information from an haloed node so that a fully-functional halo node (and therefore element) can be created on the receiving process.
Definition at line 18330 of file triangle_mesh.template.cc.
References i, oomph::GeomObject::ndim(), oomph::FiniteElement::size(), t, and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
get_required_nodal_information_load_balance_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::get_required_nodal_information_load_balance_helper (Vector< Vector< FiniteElement * > > & f_halo_ele_pt, unsigned & iproc, Node * nod_pt) [protected]
Helper function to get the required nodal information from an haloed node so that a fully-functional node (and therefore element) can be created on the receiving process (this is the specific version for the load balance strategy, the difference with the original method is that it checks if the node is on a shared boundary no associated with the current processor --my_rank--, or in a haloed element from other processors.
Helper function to get the required nodal information from an haloed node so that a fully-functional halo node (and therefore element) can be created on the receiving process.
Definition at line 26810 of file triangle_mesh.template.cc.
References i, oomph::GeomObject::ndim(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), t, and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
get_shared_boundary_elements_and_face_indexes()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::get_shared_boundary_elements_and_face_indexes (const Vector< FiniteElement * > & first_element_pt, const Vector< FiniteElement * > & second_element_pt, Vector< FiniteElement * > & first_shared_boundary_element_pt, Vector< unsigned > & first_shared_boundary_element_face_index, Vector< FiniteElement * > & second_shared_boundary_element_pt, Vector< unsigned > & second_shared_boundary_element_face_index)
Use the first and second group of elements to find the intersection between them to get the shared boundary elements from the first and second group.
Definition at line 22550 of file triangle_mesh.template.cc.
References oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
get_shared_boundary_segment_nodes_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::get_shared_boundary_segment_nodes_helper (const unsigned & shd_bnd_id, Vector< Vector< Node * > > & tmp_segment_nodes)
Get the nodes on the shared boundary (b), these are stored in the segment they belong.
Definition at line 26031 of file triangle_mesh.template.cc.
References e, oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
initialise_adaptation_data()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::initialise_adaptation_data () [inline], [protected]
Helper function to initialise data associated with adaptation.
Definition at line 3606 of file meshes/triangle_mesh.h.
initialise_boundary_refinement_data()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::initialise_boundary_refinement_data () [inline], [protected]
Set all the flags to true (the default values)
Definition at line 3073 of file meshes/triangle_mesh.h.
internal_hole_point_update_fct_pt()
template<class ELEMENT >
InternalHolePointUpdateFctPt & oomph::RefineableTriangleMesh< ELEMENT >::internal_hole_point_update_fct_pt () [inline]
Access to function pointer to can be used to generate the internal point for the ihole-th hole.
Definition at line 2609 of file meshes/triangle_mesh.h.
load_balance()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::load_balance (const Vector< unsigned > & input_target_domain_for_local_non_halo_element) [virtual]
Performs the load balancing for unstructured meshes, the load balancing strategy is based on mesh migration.
Reimplemented from oomph::TriangleMesh< ELEMENT >.
Definition at line 20452 of file triangle_mesh.template.cc.
References e, i, oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::oomph_info, oomph::Node::set_non_obsolete(), oomph::Node::set_obsolete(), oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::TimingHelpers::timer().
max_element_size()
template<class ELEMENT >
double & oomph::RefineableTriangleMesh< ELEMENT >::max_element_size () [inline]
Max element size allowed during adaptation.
Definition at line 2450 of file meshes/triangle_mesh.h.
max_sample_points_for_limited_locate_zeta_during_target_area_transfer()
template<class ELEMENT >
unsigned oomph::RefineableTriangleMesh< ELEMENT >::max_sample_points_for_limited_locate_zeta_during_target_area_transfer () [inline]
Read/write access to number of sample points from which we try to locate zeta by Newton method when transferring target areas using cgal-based sample point container. If Newton method doesn't converge from any of these we use the nearest sample point.
Definition at line 2444 of file meshes/triangle_mesh.h.
mesh_update_fct_pt()
template<class ELEMENT >
MeshUpdateFctPt & oomph::RefineableTriangleMesh< ELEMENT >::mesh_update_fct_pt () [inline]
Access to function pointer to function that updates the mesh following the snapping of boundary nodes to the boundaries (e.g. to move boundary nodes very slightly to satisfy volume constraints)
Definition at line 2601 of file meshes/triangle_mesh.h.
min_element_size()
template<class ELEMENT >
double & oomph::RefineableTriangleMesh< ELEMENT >::min_element_size () [inline]
Min element size allowed during adaptation.
Definition at line 2456 of file meshes/triangle_mesh.h.
min_permitted_angle()
template<class ELEMENT >
double & oomph::RefineableTriangleMesh< ELEMENT >::min_permitted_angle () [inline]
Min angle before remesh gets triggered.
Definition at line 2462 of file meshes/triangle_mesh.h.
nbin_x_for_area_transfer()
template<class ELEMENT >
unsigned & oomph::RefineableTriangleMesh< ELEMENT >::nbin_x_for_area_transfer () [inline]
Read/write access to number of bins in the x-direction when transferring target areas by bin method. Only used if we don't have CGAL!
Definition at line 2427 of file meshes/triangle_mesh.h.
nbin_y_for_area_transfer()
template<class ELEMENT >
unsigned & oomph::RefineableTriangleMesh< ELEMENT >::nbin_y_for_area_transfer () [inline]
Read/write access to number of bins in the y-direction when transferring target areas by bin method. Only used if we don't have CGAL!
Definition at line 2435 of file meshes/triangle_mesh.h.
nsorted_shared_boundary_node()
template<class ELEMENT >
unsigned oomph::RefineableTriangleMesh< ELEMENT >::nsorted_shared_boundary_node (unsigned & b) [inline]
Definition at line 2615 of file meshes/triangle_mesh.h.
reestablish_distribution_info_for_restart()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::reestablish_distribution_info_for_restart (OomphCommunicator * comm_pt, std::istream & restart_file) [inline], [virtual]
Used to re-establish any additional info. related with the distribution after a re-starting for triangle meshes.
Reimplemented from oomph::TriangleMesh< ELEMENT >.
Definition at line 2686 of file meshes/triangle_mesh.h.
refine_boundary()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::refine_boundary (Mesh * face_mesh_pt, Vector< Vector< double > > & vector_bnd_vertices, double & refinement_tolerance, const bool & check_only = false) [protected]
Helper function that performs the refinement process on the specified boundary by using the provided vertices representation. Optional boolean is used to run it as test only (if true is specified as input) in which case vertex coordinates aren't actually modified. Returned boolean indicates if polyline was (or would have been -- if called with check_only=false) changed.
Get the size of the vector that now includes all added nodes
Definition at line 35393 of file triangle_mesh.template.cc.
References i, oomph::FiniteElement::position(), oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
refine_boundary_constrained_by_target_area()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::refine_boundary_constrained_by_target_area (MeshAsGeomObject * mesh_geom_obj_pt, Vector< Vector< double > > & vector_bnd_vertices, double & refinement_tolerance, Vector< double > & area_constraint) [protected]
Helper function that performs the refinement process on the specified boundary by using the provided vertices representation and the associated elements target area. Used only when the 'allow_automatic_creation_of_vertices_on_boundaries' flag is set to true.
Helper function that performs the refinement process on the specified boundary by using the provided vertices representation and the associated elements target area.
Definition at line 40803 of file triangle_mesh.template.cc.
References i, oomph::FiniteElement::position(), s, oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
refine_shared_boundary_constrained_by_target_area()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::refine_shared_boundary_constrained_by_target_area (Vector< Vector< double > > & vector_bnd_vertices, Vector< double > & area_constraint) [protected]
Helper function that performs the refinement process on the specified boundary by using the provided vertices representation and the associated elements target area. NOTE: This is the version that applies refinement to shared boundaries.
Definition at line 41154 of file triangle_mesh.template.cc.
References i, s, oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
refine_triangulateio()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::refine_triangulateio (TriangulateIO & triangulate_io, const Vector< double > & target_area, TriangulateIO & triangle_refine) [protected]
Build a new TriangulateIO object from previous TriangulateIO based on target area for each element.
Build a new TriangulateIO object based on target areas specified.
Definition at line 15060 of file triangle_mesh.template.cc.
References oomph::TriangleHelper::initialise_triangulateio(), oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
refine_uniformly()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::refine_uniformly (DocInfo & doc_info) [inline], [virtual]
Refine mesh uniformly and doc process.
Implements oomph::RefineableMeshBase.
Definition at line 2559 of file meshes/triangle_mesh.h.
reset_halo_haloed_scheme()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::reset_halo_haloed_scheme () [protected]
In charge of. re-establish the halo(ed) scheme on all processors. Sends info. to create halo elements and nodes on the processors that need it. It uses and all to all communication strategy therefore must be called on all processors.
Definition at line 15486 of file triangle_mesh.template.cc.
References oomph::Global_timings::Doc_comprehensive_timings, e, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::oomph_info, oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::TimingHelpers::timer().
reset_halo_haloed_scheme_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::reset_halo_haloed_scheme_helper (Vector< Vector< Vector< std::map< unsigned, Node * > > > > & other_proc_shd_bnd_node_pt, Vector< Vector< Node * > > & iproc_currently_created_nodes_pt, Vector< Vector< Vector< unsigned > > > & global_node_names, std::map< Vector< unsigned >, unsigned > & node_name_to_global_index, Vector< Node * > & global_shared_node_pt) [protected]
In charge of creating additional halo(ed) elements on those processors that have no shared boundaries in common but have shared nodes.
Definition at line 17655 of file triangle_mesh.template.cc.
References e, i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::oomph_info, oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
reset_shared_boundary_elements_and_nodes()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::reset_shared_boundary_elements_and_nodes (const bool flush_elements = true, const bool update_elements = true, const bool flush_nodes = true, const bool update_nodes = true) [protected]
Re-establish the shared boundary elements after the adaptation process (the updating of shared nodes is optional and performed by default)
Definition at line 15402 of file triangle_mesh.template.cc.
References e, oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
restore_boundary_connections()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::restore_boundary_connections (Vector< TriangleMeshPolyLine * > & resume_initial_connection_polyline_pt, Vector< TriangleMeshPolyLine * > & resume_final_connection_polyline_pt) [protected]
After unrefinement and refinement has taken place compute the new vertices numbers of the boundaries to connect (in a distributed scheme it may be possible that the destination boundary does no longer exist, therefore the connection is suspended and resumed after the adaptation processor.
After unrefinement and refinement has taken place compute the new vertices numbers of the boundaries to connect (in a distributed scheme it may be possible that the destination boundary does no longer exist, therefore the connection is suspended. It is not permanently deleted because if load balance takes place it may be possible that the boundary to connect be part of the new domain representation, so the connection would exist)
Definition at line 33167 of file triangle_mesh.template.cc.
References i, oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
restore_polyline_connections_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::restore_polyline_connections_helper (TriangleMeshPolyLine * polyline_pt, Vector< TriangleMeshPolyLine * > & resume_initial_connection_polyline_pt, Vector< TriangleMeshPolyLine * > & resume_final_connection_polyline_pt) [protected]
Restore the connections of the specific polyline The vertices numbering on the destination boundaries may have change because of (un)refinement in the destination boundaries. Also deals with connection that do not longer exist because the destination boundary does no longer exist because of the distribution process.
Definition at line 33287 of file triangle_mesh.template.cc.
References oomph::TriangleMeshPolyLine::boundary_id(), oomph::TriangleMeshCurveSection::final_vertex_connected_bnd_id(), oomph::TriangleMeshCurveSection::final_vertex_connected_n_chunk(), oomph::TriangleMeshCurveSection::final_vertex_connected_n_vertex(), i, oomph::TriangleMeshCurveSection::initial_vertex_connected_bnd_id(), oomph::TriangleMeshCurveSection::initial_vertex_connected_n_chunk(), oomph::TriangleMeshCurveSection::initial_vertex_connected_n_vertex(), oomph::TriangleMeshCurveSection::is_final_vertex_connected(), oomph::TriangleMeshCurveSection::is_initial_vertex_connected(), oomph::TriangleMeshPolyLine::nvertex(), oomph::FiniteElement::size(), oomph::TriangleMeshCurveSection::suspend_final_vertex_connected(), oomph::TriangleMeshCurveSection::suspend_initial_vertex_connected(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::TriangleMeshPolyLine::vertex_coordinate().
resume_boundary_connections()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::resume_boundary_connections (Vector< TriangleMeshPolyLine * > & resume_initial_connection_polyline_pt, Vector< TriangleMeshPolyLine * > & resume_final_connection_polyline_pt) [protected]
Resume the boundary connections that may have been suspended because the destination boundary is no part of the domain. The connections are no permanently suspended because if load balance takes place the destination boundary may be part of the new domain representation therefore the connection would exist.
Definition at line 34039 of file triangle_mesh.template.cc.
References oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
send_and_receive_elements_nodes_info()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::send_and_receive_elements_nodes_info (int & send_proc, int & recv_proc) [protected]
Helper function to send back halo and haloed information.
Send the information of the elements that will be created on the other processor.
Definition at line 18955 of file triangle_mesh.template.cc.
References i, oomph::oomph_info, and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
send_boundary_node_info_of_shared_nodes()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::send_boundary_node_info_of_shared_nodes (Vector< Vector< Vector< unsigned > > > & global_node_names, std::map< Vector< unsigned >, unsigned > & node_name_to_global_index, Vector< Node * > & global_shared_node_pt) [protected]
Get the original boundaries to which is associated each shared node, and send the info. to the related processors. We need to do this so that at the reset of halo(ed) info. stage, the info. be already updated.
Definition at line 17056 of file triangle_mesh.template.cc.
References oomph::Node::get_coordinates_on_boundary(), i, oomph::Node::is_on_boundary(), oomph::FiniteElement::node_pt(), oomph::Node::set_coordinates_on_boundary(), oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::Node::x().
set_print_level_timings_adaptation()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::set_print_level_timings_adaptation (const unsigned & print_level) [inline]
Sets the printing level of timings for adaptation.
Definition at line 2501 of file meshes/triangle_mesh.h.
set_print_level_timings_load_balance()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::set_print_level_timings_load_balance (const unsigned & print_level) [inline]
Sets the printing level of timings for load balance.
Definition at line 2528 of file meshes/triangle_mesh.h.
snap_nodes_onto_boundary()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::snap_nodes_onto_boundary (RefineableTriangleMesh< ELEMENT > *& new_mesh_pt, const unsigned & b) [protected]
Snap the boundary nodes onto any curvilinear boundaries.
Move the boundary nodes onto the boundary defined by the old mesh. Correct!? Because assigned again below
0
Repositioning of mid-side nodes
Definition at line 43652 of file triangle_mesh.template.cc.
References oomph::FiniteElement::construct_node(), e, i, oomph::FiniteElement::interpolated_x(), oomph::GeneralisedElement::is_halo(), oomph::Node::is_on_boundary(), oomph::FiniteElement::local_coordinate_of_node(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::position(), s, oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::Node::x().
sort_nodes_on_shared_boundaries()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::sort_nodes_on_shared_boundaries () [protected]
Sort the nodes on shared boundaries so that the processors that share a boundary agree with the order of the nodes on the boundary.
Definition at line 15294 of file triangle_mesh.template.cc.
References oomph::Bottom_left_sorter, i, oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::Node::x().
sorted_shared_boundary_node_pt() [1/2]
template<class ELEMENT >
Vector< Node * > oomph::RefineableTriangleMesh< ELEMENT >::sorted_shared_boundary_node_pt (unsigned & b) [inline]
Definition at line 2650 of file meshes/triangle_mesh.h.
sorted_shared_boundary_node_pt() [2/2]
template<class ELEMENT >
Node * oomph::RefineableTriangleMesh< ELEMENT >::sorted_shared_boundary_node_pt (unsigned & b, unsigned & i) [inline]
Definition at line 2635 of file meshes/triangle_mesh.h.
References i.
surface_remesh_for_inner_hole_boundaries()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::surface_remesh_for_inner_hole_boundaries (Vector< Vector< double > > & internal_point_coord, const bool & check_only = false) [protected], [virtual]
Generate a new PSLG representation of the inner hole boundaries. Optional boolean is used to run it as test only (if true is specified as input) in which case PSLG isn't actually modified. Returned boolean indicates if PSLG was (or would have been -- if called with check_only=false) changed.
Update the PSLG that define the inner boundaries of the mesh. Optional boolean is used to run it as test only (if true is specified as input) in which case PSLG isn't actually modified. Returned boolean indicates if PSLG was (or would have been -- if called with check_only=false) changed.
Definition at line 36437 of file triangle_mesh.template.cc.
References i, and oomph::FiniteElement::size().
synchronize_shared_boundary_connections()
template<class ELEMENT >
const void oomph::RefineableTriangleMesh< ELEMENT >::synchronize_shared_boundary_connections () [protected]
Synchronise the vertices that are marked for non deletion.
Definition at line 32667 of file triangle_mesh.template.cc.
References i, and oomph::FiniteElement::size().
try_to_add_element_pt_load_balance()
template<class ELEMENT >
unsigned oomph::RefineableTriangleMesh< ELEMENT >::try_to_add_element_pt_load_balance (Vector< FiniteElement * > & new_elements_on_domain, FiniteElement *& ele_pt) [inline], [protected]
Check if necessary to add the element to the new domain or if it has been previously added.
Definition at line 3156 of file meshes/triangle_mesh.h.
References e, and oomph::FiniteElement::size().
try_to_add_haloed_node_pt()
template<class ELEMENT >
unsigned oomph::RefineableTriangleMesh< ELEMENT >::try_to_add_haloed_node_pt (const unsigned & p, Node *& nod_pt) [inline], [protected], [virtual]
Check if necessary to add the node as haloed or if it has been previously added to the haloed scheme.
Reimplemented from oomph::Mesh.
Definition at line 3399 of file meshes/triangle_mesh.h.
try_to_add_node_pt_load_balance()
template<class ELEMENT >
unsigned oomph::RefineableTriangleMesh< ELEMENT >::try_to_add_node_pt_load_balance (Vector< Node * > & new_nodes_on_domain, Node *& node_pt) [inline], [protected]
Check if necessary to add the node to the new domain or if it has been already added.
Definition at line 3204 of file meshes/triangle_mesh.h.
References oomph::FiniteElement::size().
try_to_add_root_haloed_element_pt()
template<class ELEMENT >
unsigned oomph::RefineableTriangleMesh< ELEMENT >::try_to_add_root_haloed_element_pt (const unsigned & p, GeneralisedElement *& el_pt) [inline], [protected], [virtual]
Check if necessary to add the element as haloed or if it has been previously added to the haloed scheme.
Reimplemented from oomph::Mesh.
Definition at line 3361 of file meshes/triangle_mesh.h.
unrefine_boundary()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::unrefine_boundary (const unsigned & b, const unsigned & c, Vector< Vector< double > > & vector_bnd_vertices, double & unrefinement_tolerance, const bool & check_only = false) [protected]
Helper function that performs the unrefinement process.
Helper function that performs the unrefinement process on the specified boundary by using the provided vertices representation. Optional boolean is used to run it as test only (if true is specified as input) in which case vertex coordinates aren't actually modified. Returned boolean indicates if polyline was (or would have been -- if called with check_only=false) changed.
representation. Optional boolean is used to run it as test only (if true is specified as input) in which case vertex coordinates aren't actually modified. Returned boolean indicates if polyline was (or would have been -- if called with check_only=false) changed. Get the size of the vector that now includes all remaining nodes
Copy back
Definition at line 35098 of file triangle_mesh.template.cc.
References e, i, oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error.
unrefine_boundary_constrained_by_target_area()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::unrefine_boundary_constrained_by_target_area (const unsigned & b, const unsigned & c, Vector< Vector< double > > & vector_bnd_vertices, double & unrefinement_tolerance, Vector< double > & area_constraint) [protected]
Helper function that performs the unrefinement process on the specified boundary by using the provided vertices representation and the associated target area. Used only when the 'allow_automatic_creation_of_vertices_on_boundaries' flag is set to true.
Helper function that performs the unrefinement process on the specified boundary by using the provided vertices representation and the associated target area.
Definition at line 40547 of file triangle_mesh.template.cc.
References e, i, oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error.
unrefine_shared_boundary_constrained_by_target_area()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::unrefine_shared_boundary_constrained_by_target_area (const unsigned & b, const unsigned & c, Vector< Vector< double > > & vector_bnd_vertices, Vector< double > & area_constraint) [protected]
Helper function that performs the unrefinement process on the specified boundary by using the provided vertices representation and the associated target area. NOTE: This is the version that applies unrefinement to shared boundaries.
Definition at line 40945 of file triangle_mesh.template.cc.
References i, oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), and oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error.
unrefine_uniformly()
template<class ELEMENT >
unsigned oomph::RefineableTriangleMesh< ELEMENT >::unrefine_uniformly () [inline], [virtual]
Unrefine mesh uniformly: Return 0 for success, 1 for failure (if unrefinement has reached the coarsest permitted level)
Implements oomph::RefineableMeshBase.
Definition at line 2585 of file meshes/triangle_mesh.h.
update_open_curve_after_restart()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::update_open_curve_after_restart (TriangleMeshOpenCurve *& open_curve_pt) [protected]
Updates the open curve representation after restart.
Use a vector of vector for vertices and target areas to deal with the cases when the boundaries are split bn the distribution process. Internal boundaries may be completely or partially overlapped by shared boundaries
Definition at line 42029 of file triangle_mesh.template.cc.
References oomph::Node::get_coordinates_on_boundary(), i, oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error, and oomph::Node::x().
update_open_curve_using_elements_area()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::update_open_curve_using_elements_area (TriangleMeshOpenCurve *& open_curve_pt, const Vector< double > & target_area) [protected]
Updates the open curve but using the elements area instead of the default refinement and unrefinement methods.
Use a vector of vector for vertices and target areas to deal with the cases when the boundaries are split by the distribution process. Internal boundaries may be completely or partially overlapped by shared boundaries
Definition at line 38607 of file triangle_mesh.template.cc.
References oomph::Node::get_coordinates_on_boundary(), i, oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error, and oomph::Node::x().
update_open_curve_using_face_mesh()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::update_open_curve_using_face_mesh (TriangleMeshOpenCurve * open_polyline_pt, const bool & check_only = false) [protected]
Helper function that updates the input open curve by using end-points of elements from FaceMesh(es) that are constructed for the boundaries associated with the polylines. Optional boolean is used to run it as test only (if true is specified as input) in which case the polylines are not actually modified. Returned boolean indicates if polylines were (or would have been -- if called with check_only=false) changed.
Refinement
Definition at line 34614 of file triangle_mesh.template.cc.
References e, oomph::Node::get_coordinates_on_boundary(), i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error, and oomph::Node::x().
update_other_proc_shd_bnd_node_helper()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::update_other_proc_shd_bnd_node_helper (Node *& new_nod_pt, Vector< Vector< Vector< std::map< unsigned, Node * > > > > & other_proc_shd_bnd_node_pt, Vector< unsigned > & other_processor_1, Vector< unsigned > & other_processor_2, Vector< unsigned > & other_shared_boundaries, Vector< unsigned > & other_indexes, Vector< Vector< Vector< unsigned > > > & global_node_names, std::map< Vector< unsigned >, unsigned > & node_name_to_global_index, Vector< Node * > & global_shared_node_pt) [protected]
Helper function that assigns/updates the references to the node so that it can be found with any other reference. The return value indicates whether or not a node was found on the same reference.
Definition at line 20303 of file triangle_mesh.template.cc.
References oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
update_polygon_after_restart()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::update_polygon_after_restart (TriangleMeshPolygon *& polygon_pt) [protected]
Updates the polylines representation after restart.
Use a vector of vector for vertices and target areas to deal with the cases when the boundaries are split by the distribution process
Definition at line 41257 of file triangle_mesh.template.cc.
References oomph::Node::get_coordinates_on_boundary(), i, oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error, and oomph::Node::x().
update_polygon_using_elements_area()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::update_polygon_using_elements_area (TriangleMeshPolygon *& polygon_pt, const Vector< double > & target_area) [protected]
Updates the polylines using the elements area as constraint for the number of points along the boundaries.
Updates the polygon but using the elements area instead of the default refinement and unrefinement methods. Use a vector of vector for vertices and target areas to deal with the cases when the boundaries are split by the distribution process
Definition at line 37645 of file triangle_mesh.template.cc.
References oomph::Node::get_coordinates_on_boundary(), i, oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error, and oomph::Node::x().
update_polygon_using_face_mesh()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::update_polygon_using_face_mesh (TriangleMeshPolygon * polygon_pt, const bool & check_only = false) [protected]
Helper function that updates the input polygon's PSLG by using the end-points of elements from FaceMesh(es) that are constructed for the boundaries associated with the segments of the polygon. Optional boolean is used to run it as test only (if true is specified as input) in which case polygon isn't actually modified. Returned boolean indicates if polygon was (or would have been -- if called with check_only=false) changed.
Definition at line 34129 of file triangle_mesh.template.cc.
References e, oomph::Node::get_coordinates_on_boundary(), i, oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error, and oomph::Node::x().
update_polyline_representation_from_restart()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::update_polyline_representation_from_restart () [inline], [virtual]
Method used to update the polylines representation after restart.
Reimplemented from oomph::TriangleMeshBase.
Definition at line 2738 of file meshes/triangle_mesh.h.
References i, and oomph::FiniteElement::size().
update_shared_curve_after_restart()
template<class ELEMENT >
void oomph::RefineableTriangleMesh< ELEMENT >::update_shared_curve_after_restart (Vector< TriangleMeshPolyLine * > & vector_polyline_pt) [protected]
Updates the shared polylines representation after restart.
Definition at line 43008 of file triangle_mesh.template.cc.
References e, i, oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
update_shared_curve_using_elements_area()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::update_shared_curve_using_elements_area (Vector< TriangleMeshPolyLine * > & vector_polyline_pt, const Vector< double > & target_areas) [protected]
Updates the polylines using the elements area as constraint for the number of points along the boundaries.
Definition at line 39883 of file triangle_mesh.template.cc.
References e, oomph::GeneralisedElement::is_halo(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), s, oomph::FiniteElement::size(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement().
use_iterative_solver_for_projection()
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::use_iterative_solver_for_projection () [inline]
Definition at line 2469 of file meshes/triangle_mesh.h.
Member Data Documentation
Boundary_connections_pt
template<class ELEMENT >
std::map<unsigned, std::set<Vector<double> > > oomph::RefineableTriangleMesh< ELEMENT >::Boundary_connections_pt [protected]
A map that stores the vertices that receive connections, they are identified by the boundary number that receive the connection This is necessary for not erasing them on the adaptation process, specifically for the un-refinement process.
Definition at line 2897 of file meshes/triangle_mesh.h.
Counter_for_flat_packed_doubles
template<class ELEMENT >
unsigned oomph::RefineableTriangleMesh< ELEMENT >::Counter_for_flat_packed_doubles [protected]
Counter used when processing vector of flat-packed doubles.
Definition at line 3335 of file meshes/triangle_mesh.h.
Counter_for_flat_packed_unsigneds
template<class ELEMENT >
unsigned oomph::RefineableTriangleMesh< ELEMENT >::Counter_for_flat_packed_unsigneds [protected]
Counter used when processing vector of flat-packed unsigneds.
Definition at line 3343 of file meshes/triangle_mesh.h.
Disable_projection
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::Disable_projection [protected]
Enable/disable solution projection during adaptation.
Definition at line 3823 of file meshes/triangle_mesh.h.
Do_boundary_refinement_constrained_by_target_areas
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::Do_boundary_refinement_constrained_by_target_areas [protected]
Flag that enables or disables boundary refinement (true by default)
Definition at line 3064 of file meshes/triangle_mesh.h.
Do_boundary_unrefinement_constrained_by_target_areas
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::Do_boundary_unrefinement_constrained_by_target_areas [protected]
Flag that enables or disables boundary unrefinement (true by default)
Definition at line 3061 of file meshes/triangle_mesh.h.
Do_shared_boundary_refinement_constrained_by_target_areas
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::Do_shared_boundary_refinement_constrained_by_target_areas [protected]
Flag that enables or disables boundary unrefinement (true by default)
Definition at line 3070 of file meshes/triangle_mesh.h.
Do_shared_boundary_unrefinement_constrained_by_target_areas
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::Do_shared_boundary_unrefinement_constrained_by_target_areas [protected]
Flag that enables or disables boundary unrefinement (true by default)
Definition at line 3067 of file meshes/triangle_mesh.h.
Flat_packed_doubles
template<class ELEMENT >
Vector<double> oomph::RefineableTriangleMesh< ELEMENT >::Flat_packed_doubles [protected]
Vector of flat-packed doubles to be communicated with other processors.
Definition at line 3331 of file meshes/triangle_mesh.h.
Flat_packed_unsigneds
template<class ELEMENT >
Vector<unsigned> oomph::RefineableTriangleMesh< ELEMENT >::Flat_packed_unsigneds [protected]
Vector of flat-packed unsigneds to be communicated with other processors.
Definition at line 3339 of file meshes/triangle_mesh.h.
Flat_packed_unsigneds_string
template<class ELEMENT >
Vector<std::string> oomph::RefineableTriangleMesh< ELEMENT >::Flat_packed_unsigneds_string [protected]
Temporary vector of strings to enable full annotation of RefineableTriangleMesh comms.
Definition at line 3348 of file meshes/triangle_mesh.h.
Internal_hole_point_update_fct_pt
template<class ELEMENT >
InternalHolePointUpdateFctPt oomph::RefineableTriangleMesh< ELEMENT >::Internal_hole_point_update_fct_pt [protected]
Function pointer to function that can be set to update the position of the central point in internal holes.
Definition at line 3850 of file meshes/triangle_mesh.h.
Max_element_size
template<class ELEMENT >
double oomph::RefineableTriangleMesh< ELEMENT >::Max_element_size [protected]
Max permitted element size.
Definition at line 3814 of file meshes/triangle_mesh.h.
Max_sample_points_for_limited_locate_zeta_during_target_area_transfer
template<class ELEMENT >
unsigned oomph::RefineableTriangleMesh< ELEMENT >::Max_sample_points_for_limited_locate_zeta_during_target_area_transfer [protected]
Default value for max. number of sample points used for locate_zeta when transferring target areas using cgal-based sample point container.
Definition at line 3811 of file meshes/triangle_mesh.h.
Mesh_update_fct_pt
template<class ELEMENT >
MeshUpdateFctPt oomph::RefineableTriangleMesh< ELEMENT >::Mesh_update_fct_pt [protected]
Function pointer to function that updates the mesh following the snapping of boundary nodes to the boundaries (e.g. to move boundary nodes very slightly to satisfy volume constraints)
Definition at line 3845 of file meshes/triangle_mesh.h.
Min_element_size
template<class ELEMENT >
double oomph::RefineableTriangleMesh< ELEMENT >::Min_element_size [protected]
Min permitted element size.
Definition at line 3817 of file meshes/triangle_mesh.h.
Min_permitted_angle
template<class ELEMENT >
double oomph::RefineableTriangleMesh< ELEMENT >::Min_permitted_angle [protected]
Min angle before remesh gets triggered.
Definition at line 3820 of file meshes/triangle_mesh.h.
Nbin_x_for_area_transfer
template<class ELEMENT >
unsigned oomph::RefineableTriangleMesh< ELEMENT >::Nbin_x_for_area_transfer [protected]
Number of bins in the x-direction when transferring target areas by bin method. Only used if we don't have CGAL!
Definition at line 3800 of file meshes/triangle_mesh.h.
Nbin_y_for_area_transfer
template<class ELEMENT >
unsigned oomph::RefineableTriangleMesh< ELEMENT >::Nbin_y_for_area_transfer [protected]
Number of bins in the y-direction when transferring target areas by bin method. Only used if we don't have CGAL!
Definition at line 3805 of file meshes/triangle_mesh.h.
Print_timings_level_adaptation
template<class ELEMENT >
unsigned oomph::RefineableTriangleMesh< ELEMENT >::Print_timings_level_adaptation [protected]
The printing level for adaptation.
Definition at line 3836 of file meshes/triangle_mesh.h.
Print_timings_level_load_balance
template<class ELEMENT >
unsigned oomph::RefineableTriangleMesh< ELEMENT >::Print_timings_level_load_balance [protected]
The printing level for load balance.
Definition at line 3839 of file meshes/triangle_mesh.h.
Print_timings_projection
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::Print_timings_projection [protected]
Enable/disable printing timings for projection.
Definition at line 3833 of file meshes/triangle_mesh.h.
Print_timings_transfering_target_areas
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::Print_timings_transfering_target_areas [protected]
Enable/disable printing timings for transfering target areas.
Definition at line 3830 of file meshes/triangle_mesh.h.
Sorted_shared_boundary_node_pt
template<class ELEMENT >
std::map<unsigned, Vector<Node*> > oomph::RefineableTriangleMesh< ELEMENT >::Sorted_shared_boundary_node_pt [protected]
Stores the nodes in the boundaries in the same order in all the processors Sorted_shared_boundary_node_pt[bnd_id][i-th node] = Node* It is a map since the boundary id may not start at zero.
Definition at line 3088 of file meshes/triangle_mesh.h.
Use_iterative_solver_for_projection
template<class ELEMENT >
bool oomph::RefineableTriangleMesh< ELEMENT >::Use_iterative_solver_for_projection [protected]
Flag to indicate whether to use or not an iterative solver (CG with diagonal preconditioned) for the projection problem.
Definition at line 3827 of file meshes/triangle_mesh.h.
The documentation for this class was generated from the following files:
meshes/triangle_mesh.h
triangle_mesh.template.cc