oomph::QuadMeshBase Class Reference
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
#include <quad_mesh.h>
Public Member Functions
QuadMeshBase ()
Constructor (empty)
QuadMeshBase (const QuadMeshBase &node)=delete
Broken copy constructor.
void operator= (const QuadMeshBase &)=delete
Broken assignment operator.
virtual ~QuadMeshBase ()
Destructor (empty)
void setup_boundary_element_info ()
Setup lookup schemes which establish whic elements are located next to mesh's boundaries (wrapper to suppress doc).
void setup_boundary_element_info (std::ostream &outfile)
Setup lookup schemes which establish whic elements are located next to mesh's boundaries. Doc in outfile (if it's open).
Additional Inherited Members
Detailed Description
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Base class for quad meshes (meshes made of 2D quad elements).
Definition at line 56 of file quad_mesh.h.
Constructor & Destructor Documentation
QuadMeshBase() [1/2]
oomph::QuadMeshBase::QuadMeshBase () [inline]
Constructor (empty)
Definition at line 60 of file quad_mesh.h.
QuadMeshBase() [2/2]
oomph::QuadMeshBase::QuadMeshBase (const QuadMeshBase & node) [delete]
Broken copy constructor.
 QuadMeshBase()
virtual oomph::QuadMeshBase::~QuadMeshBase () [inline], [virtual]
Destructor (empty)
Definition at line 69 of file quad_mesh.h.
Member Function Documentation
operator=()
void oomph::QuadMeshBase::operator= (const QuadMeshBase &) [delete]
Broken assignment operator.
setup_boundary_element_info() [1/2]
void oomph::QuadMeshBase::setup_boundary_element_info () [inline], [virtual]
Setup lookup schemes which establish whic elements are located next to mesh's boundaries (wrapper to suppress doc).
Reimplemented from oomph::Mesh.
Definition at line 73 of file quad_mesh.h.
Referenced by oomph::ChannelWithLeafletMesh< ELEMENT >::ChannelWithLeafletMesh(), oomph::CollapsibleChannelMesh< ELEMENT >::CollapsibleChannelMesh(), oomph::FSIDrivenCavityMesh< ELEMENT >::FSIDrivenCavityMesh(), oomph::FullCircleMesh< ELEMENT >::FullCircleMesh(), and oomph::QuarterCircleSectorMesh< ELEMENT >::QuarterCircleSectorMesh().
setup_boundary_element_info() [2/2]
void oomph::QuadMeshBase::setup_boundary_element_info (std::ostream & outfile) [virtual]
Setup lookup schemes which establish whic elements are located next to mesh's boundaries. Doc in outfile (if it's open).
Setup lookup schemes which establish which elements are located next to which boundaries (Doc to outfile if it's open).
Reimplemented from oomph::Mesh.
Definition at line 37 of file quad_mesh.cc.
References oomph::Mesh::Boundary_element_pt, oomph::FiniteElement::dim(), oomph::LeakCheckNames::doc(), e, oomph::Mesh::Face_index_at_boundary, oomph::Mesh::finite_element_pt(), oomph::Node::get_boundaries_pt(), i, oomph::Mesh::Lookup_for_elements_next_boundary_is_setup, oomph::Mesh::nboundary(), oomph::Mesh::nelement(), oomph::FiniteElement::nnode_1d(), and oomph::FiniteElement::node_pt().
The documentation for this class was generated from the following files:
quad_mesh.h
quad_mesh.cc