oomph::EulerEquations< DIM > Class Template Reference
Base class for Euler equations.
#include <euler_elements.h>
Public Member Functions
EulerEquations ()
Return the flux derivatives as a function of the unknowns.
virtual ~EulerEquations ()
Destructor.
double pressure (const Vector< double > &u) const
Calculate the pressure from the unknowns.
double gamma () const
Return the value of gamma.
double *& gamma_pt ()
Access function for the pointer to gamma.
double *const & gamma_pt () const
Access function for the pointer to gamma (const version)
unsigned required_nvalue (const unsigned &n) const
The number of unknowns at each node is the number of flux components.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_solution_pt, const double &t, Vector< double > &error, Vector< double > &norm)
Compute the error and norm of solution integrated over the element Does not plot the error in the outfile.
void output (std::ostream &outfile)
Output function: x,y,u or x,y,z,u.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
void allocate_memory_for_averages ()
double & average_gradient (const unsigned &i, const unsigned &j)
Return access to the average gradient.
double & average_prim_value (const unsigned &i)
Return the average values.
Protected Member Functions
unsigned nflux () const
DIM momentum-components, a density and an energy are transported.
void flux (const Vector< double > &u, DenseMatrix< double > &f)
Return the flux as a function of the unknown.
Private Member Functions
double Default_Gamma_Value
Set the default value of Gamma to be 1.4 in all three dimension specialisations. This form seems to be required for gcc 4.4.4, rather than a more general templated version.
double Default_Gamma_Value
double Default_Gamma_Value
Private Attributes
double * Gamma_pt
double * Average_prim_value
Storage for the average primitive values.
double * Average_gradient
Storage for the approximated gradients.
Static Private Attributes
static double Default_Gamma_Value
Additional Inherited Members
Detailed Description
template<unsigned DIM>
class oomph::EulerEquations< DIM >
Base class for Euler equations.
Definition at line 46 of file euler_elements.h.
Constructor & Destructor Documentation
EulerEquations()
template<unsigned DIM>
oomph::EulerEquations< DIM >::EulerEquations () [inline]
Return the flux derivatives as a function of the unknowns.
Constructor
Definition at line 75 of file euler_elements.h.
References oomph::EulerEquations< DIM >::Default_Gamma_Value, and oomph::EulerEquations< DIM >::Gamma_pt.
 EulerEquations()
template<unsigned DIM>
virtual oomph::EulerEquations< DIM >::~EulerEquations () [inline], [virtual]
Destructor.
Definition at line 85 of file euler_elements.h.
References oomph::EulerEquations< DIM >::Average_gradient, and oomph::EulerEquations< DIM >::Average_prim_value.
Member Function Documentation
allocate_memory_for_averages()
template<unsigned DIM>
void oomph::EulerEquations< DIM >::allocate_memory_for_averages () [inline]
Definition at line 213 of file euler_elements.h.
References oomph::EulerEquations< DIM >::nflux().
average_gradient()
template<unsigned DIM>
double & oomph::EulerEquations< DIM >::average_gradient (const unsigned & i, const unsigned & j) [inline]
Return access to the average gradient.
Definition at line 230 of file euler_elements.h.
References oomph::EulerEquations< DIM >::Average_gradient, and i.
average_prim_value()
template<unsigned DIM>
double & oomph::EulerEquations< DIM >::average_prim_value (const unsigned & i) [inline]
Return the average values.
Definition at line 242 of file euler_elements.h.
References oomph::EulerEquations< DIM >::Average_prim_value, and i.
compute_error()
template<unsigned DIM>
void oomph::EulerEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_solution_pt, const double & t, Vector< double > & error, Vector< double > & norm) [inline], [virtual]
Compute the error and norm of solution integrated over the element Does not plot the error in the outfile.
Reimplemented from oomph::FiniteElement.
Definition at line 129 of file euler_elements.h.
References oomph::FiniteElement::dshape_eulerian_at_knot(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::EulerEquations< DIM >::nflux(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::Integral::nweight(), s, t, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Default_Gamma_Value() [1/3]
double oomph::EulerEquations< 1 >::Default_Gamma_Value [private]
Set the default value of Gamma to be 1.4 in all three dimension specialisations. This form seems to be required for gcc 4.4.4, rather than a more general templated version.
Definition at line 38 of file euler_elements.cc.
Default_Gamma_Value() [2/3]
double oomph::EulerEquations< 2 >::Default_Gamma_Value [private]
Definition at line 40 of file euler_elements.cc.
Default_Gamma_Value() [3/3]
double oomph::EulerEquations< 3 >::Default_Gamma_Value [private]
Definition at line 42 of file euler_elements.cc.
flux()
template<unsigned DIM>
void oomph::EulerEquations< DIM >::flux (const Vector< double > & u, DenseMatrix< double > & f) [protected], [virtual]
Return the flux as a function of the unknown.
Return the flux as a function of the unknowns The unknowns are stored as density, energy and then the velocity components.
Reimplemented from oomph::FluxTransportEquations< DIM >.
Definition at line 76 of file euler_elements.cc.
References i.
gamma()
template<unsigned DIM>
double oomph::EulerEquations< DIM >::gamma () const [inline]
Return the value of gamma.
Definition at line 103 of file euler_elements.h.
References oomph::EulerEquations< DIM >::Gamma_pt.
gamma_pt() [1/2]
template<unsigned DIM>
double *& oomph::EulerEquations< DIM >::gamma_pt () [inline]
Access function for the pointer to gamma.
Definition at line 109 of file euler_elements.h.
References oomph::EulerEquations< DIM >::Gamma_pt.
gamma_pt() [2/2]
template<unsigned DIM>
double *const & oomph::EulerEquations< DIM >::gamma_pt () const [inline]
Access function for the pointer to gamma (const version)
Definition at line 115 of file euler_elements.h.
References oomph::EulerEquations< DIM >::Gamma_pt.
nflux()
template<unsigned DIM>
unsigned oomph::EulerEquations< DIM >::nflux () const [inline], [protected], [virtual]
DIM momentum-components, a density and an energy are transported.
Reimplemented from oomph::FluxTransportEquations< DIM >.
Definition at line 62 of file euler_elements.h.
Referenced by oomph::EulerEquations< DIM >::allocate_memory_for_averages(), and oomph::EulerEquations< DIM >::compute_error().
output() [1/2]
template<unsigned DIM>
void oomph::EulerEquations< DIM >::output (std::ostream & outfile) [inline], [virtual]
Output function: x,y,u or x,y,z,u.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QSpectralEulerElement< DIM, NNODE_1D >, oomph::QSpectralEulerElement< 1, NNODE_1D >, and oomph::QSpectralEulerElement< 2, NNODE_1D >.
Definition at line 203 of file euler_elements.h.
References oomph::EulerEquations< DIM >::output().
Referenced by oomph::EulerEquations< DIM >::output(), and oomph::QSpectralEulerElement< DIM, NNODE_1D >::output().
output() [2/2]
template<unsigned DIM>
void oomph::EulerEquations< DIM >::output (std::ostream & outfile, const unsigned & n_plot) [virtual]
Output function: x,y,u or x,y,z,u at n_plot^DIM plot points.
Output function, print the values of all unknowns.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QSpectralEulerElement< DIM, NNODE_1D >, oomph::QSpectralEulerElement< 1, NNODE_1D >, and oomph::QSpectralEulerElement< 2, NNODE_1D >.
Definition at line 112 of file euler_elements.cc.
References i, and s.
pressure()
template<unsigned DIM>
double oomph::EulerEquations< DIM >::pressure (const Vector< double > & u) const
Calculate the pressure from the unknowns.
Calculate the pressure value from the unknowns.
Definition at line 49 of file euler_elements.cc.
required_nvalue()
template<unsigned DIM>
unsigned oomph::EulerEquations< DIM >::required_nvalue (const unsigned & n) const [inline], [virtual]
The number of unknowns at each node is the number of flux components.
Reimplemented from oomph::FiniteElement.
Definition at line 122 of file euler_elements.h.
Member Data Documentation
Average_gradient
template<unsigned DIM>
double* oomph::EulerEquations< DIM >::Average_gradient [private]
Storage for the approximated gradients.
Definition at line 58 of file euler_elements.h.
Referenced by oomph::EulerEquations< DIM >::average_gradient(), and oomph::EulerEquations< DIM >::~EulerEquations().
Average_prim_value
template<unsigned DIM>
double* oomph::EulerEquations< DIM >::Average_prim_value [private]
Storage for the average primitive values.
Definition at line 55 of file euler_elements.h.
Referenced by oomph::EulerEquations< DIM >::average_prim_value(), and oomph::EulerEquations< DIM >::~EulerEquations().
Default_Gamma_Value
template<unsigned DIM>
double oomph::EulerEquations< DIM >::Default_Gamma_Value [static], [private]
Definition at line 49 of file euler_elements.h.
Referenced by oomph::EulerEquations< DIM >::EulerEquations().
Gamma_pt
template<unsigned DIM>
double* oomph::EulerEquations< DIM >::Gamma_pt [private]
Definition at line 52 of file euler_elements.h.
Referenced by oomph::EulerEquations< DIM >::EulerEquations(), oomph::EulerEquations< DIM >::gamma(), and oomph::EulerEquations< DIM >::gamma_pt().
The documentation for this class was generated from the following files:
euler_elements.h
euler_elements.cc