oomph::QuadTreeRoot Class Reference
QuadTreeRoot is a QuadTree that forms the root of a (recursive) quadtree. The `root node` is special as it holds additional information about its neighbours and their relative rotation (inside a QuadTreeForest).
#include <quadtree.h>
Public Member Functions
QuadTreeRoot (RefineableElement *const &object_pt)
Constructor for the (empty) root quadtree: Pass pointer to associated object, a RefineableQElement<2>.
QuadTreeRoot (const QuadTreeRoot &dummy)=delete
Broken copy constructor.
void operator= (const QuadTreeRoot &)=delete
Broken assignment operator.
int & north_equivalent (const int &neighbour)
Return north equivalent of the neighbours in specified direction: When viewed from the current quadtree's neighbour neighbour, our northern direction is the neighbour's north_equivalent(neighbour) direction. If there's no rotation, this map contains the identify so that, e.g. north_equivalent(W)=N (read as: `in my Western neighbour, my North is its North`). If the western neighbour is rotated by 180 degrees relative to the current quadtree, say, we have north_equivalent(W)=S (read as: `in my Western neighbour, my North is its South`); etc.
int direction_of_neighbour (QuadTreeRoot *quadtree_root_pt)
If quadtree_root_pt is a neighbour, return the direction [N/S/E/W] in which it is found, otherwise return OMEGA.
Private Attributes
Vector< int > North_equivalent
Vector giving the north equivalent of the neighbours: When viewed from the current quadtree's neighbour neighbour, our northern direction is the neighbour's North_equivalent[neighbour] direction. If there's no rotation, this map contains the identify so that, e.g. North_equivalent[W]=N (read as: `in my Western neighbour, my North is its North`). If the western neighbour is rotated by 180 degrees relative to the current quadtree, say, we have North_equivalent[W]=S (read as: `in my Western neighbour, my North is its South`); etc.
Additional Inherited Members
Detailed Description
QuadTreeRoot is a QuadTree that forms the root of a (recursive) quadtree. The `root node` is special as it holds additional information about its neighbours and their relative rotation (inside a QuadTreeForest).
Definition at line 292 of file quadtree.h.
Constructor & Destructor Documentation
QuadTreeRoot() [1/2]
oomph::QuadTreeRoot::QuadTreeRoot (RefineableElement *const & object_pt) [inline]
Constructor for the (empty) root quadtree: Pass pointer to associated object, a RefineableQElement<2>.
Definition at line 309 of file quadtree.h.
References oomph::QuadTreeNames::E, oomph::QuadTreeNames::N, North_equivalent, oomph::QuadTreeNames::S, oomph::QuadTree::Static_data_has_been_setup, oomph::Global_string_for_annotation::string(), and oomph::QuadTreeNames::W.
QuadTreeRoot() [2/2]
oomph::QuadTreeRoot::QuadTreeRoot (const QuadTreeRoot & dummy) [delete]
Broken copy constructor.
Member Function Documentation
direction_of_neighbour()
int oomph::QuadTreeRoot::direction_of_neighbour (QuadTreeRoot * quadtree_root_pt) [inline]
If quadtree_root_pt is a neighbour, return the direction [N/S/E/W] in which it is found, otherwise return OMEGA.
Definition at line 377 of file quadtree.h.
References oomph::QuadTreeNames::E, oomph::QuadTreeNames::N, oomph::TreeRoot::Neighbour_pt, oomph::Tree::OMEGA, oomph::QuadTreeNames::S, and oomph::QuadTreeNames::W.
Referenced by oomph::QuadTreeForest::construct_north_equivalents().
north_equivalent()
int & oomph::QuadTreeRoot::north_equivalent (const int & neighbour) [inline]
Return north equivalent of the neighbours in specified direction: When viewed from the current quadtree's neighbour neighbour, our northern direction is the neighbour's north_equivalent(neighbour) direction. If there's no rotation, this map contains the identify so that, e.g. north_equivalent(W)=N (read as: `in my Western neighbour, my North is its North`). If the western neighbour is rotated by 180 degrees relative to the current quadtree, say, we have north_equivalent(W)=S (read as: `in my Western neighbour, my North is its South`); etc.
Definition at line 354 of file quadtree.h.
References oomph::QuadTree::Direct_string, oomph::QuadTreeNames::E, oomph::QuadTreeNames::N, North_equivalent, oomph::QuadTreeNames::S, and oomph::QuadTreeNames::W.
Referenced by oomph::QuadTreeForest::construct_north_equivalents(), and oomph::QuadTree::gteq_edge_neighbour().
operator=()
void oomph::QuadTreeRoot::operator= (const QuadTreeRoot &) [delete]
Broken assignment operator.
Member Data Documentation
North_equivalent
Vector<int> oomph::QuadTreeRoot::North_equivalent [private]
Vector giving the north equivalent of the neighbours: When viewed from the current quadtree's neighbour neighbour, our northern direction is the neighbour's North_equivalent[neighbour] direction. If there's no rotation, this map contains the identify so that, e.g. North_equivalent[W]=N (read as: `in my Western neighbour, my North is its North`). If the western neighbour is rotated by 180 degrees relative to the current quadtree, say, we have North_equivalent[W]=S (read as: `in my Western neighbour, my North is its South`); etc.
Definition at line 304 of file quadtree.h.
Referenced by north_equivalent(), and QuadTreeRoot().
The documentation for this class was generated from the following file:
quadtree.h