oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D > Class Template Reference
//////////////////////////////////////////////////////////////////////
#include <Ttime_harmonic_linear_elasticity_elements.h>
Public Member Functions
TTimeHarmonicLinearElasticityElement ()
Constructor: Call constructors for TElement and TimeHarmonicLinearElasticity equations.
TTimeHarmonicLinearElasticityElement (const TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D > &dummy)=delete
Broken copy constructor.
void output (std::ostream &outfile)
Broken assignment operator.
void output (std::ostream &outfile, const unsigned &nplot)
Output function:
void output (FILE *file_pt)
C-style output function:
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function:
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned nrecovery_order ()
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Upper triangular entries in strain tensor.
Additional Inherited Members
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >
//////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////// TTimeHarmonicLinearElasticityElement<DIM,NNODE_1D> elements are isoparametric triangular DIM-dimensional TimeHarmonicLinearElasticity elements with NNODE_1D nodal points along each element edge. Inherits from TElement and TimeHarmonicLinearElasticityEquations
Definition at line 62 of file Ttime_harmonic_linear_elasticity_elements.h.
Constructor & Destructor Documentation
TTimeHarmonicLinearElasticityElement() [1/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >::TTimeHarmonicLinearElasticityElement () [inline]
Constructor: Call constructors for TElement and TimeHarmonicLinearElasticity equations.
Definition at line 70 of file Ttime_harmonic_linear_elasticity_elements.h.
TTimeHarmonicLinearElasticityElement() [2/2]
template<unsigned DIM, unsigned NNODE_1D>
oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >::TTimeHarmonicLinearElasticityElement (const TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
get_Z2_flux()
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) [inline], [virtual]
Get 'flux' for Z2 error recovery: Upper triangular entries in strain tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 144 of file Ttime_harmonic_linear_elasticity_elements.h.
References oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::get_strain(), and i.
nrecovery_order()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >::nrecovery_order () [inline], [virtual]
Order of recovery shape functions for Z2 error estimation: Same order as shape functions.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 130 of file Ttime_harmonic_linear_elasticity_elements.h.
num_Z2_flux_terms()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >::num_Z2_flux_terms () [inline], [virtual]
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 136 of file Ttime_harmonic_linear_elasticity_elements.h.
nvertex_node()
template<unsigned DIM, unsigned NNODE_1D>
unsigned oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >::nvertex_node () const [inline], [virtual]
Number of vertex nodes in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 117 of file Ttime_harmonic_linear_elasticity_elements.h.
output() [1/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >::output (FILE * file_pt) [inline], [virtual]
C-style output function:
Reimplemented from oomph::TimeHarmonicLinearElasticityEquations< DIM >.
Definition at line 104 of file Ttime_harmonic_linear_elasticity_elements.h.
References oomph::TimeHarmonicLinearElasticityEquations< DIM >::output().
output() [2/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function:
Reimplemented from oomph::TimeHarmonicLinearElasticityEquations< DIM >.
Definition at line 110 of file Ttime_harmonic_linear_elasticity_elements.h.
References oomph::TimeHarmonicLinearElasticityEquations< DIM >::output().
output() [3/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >::output (std::ostream & outfile) [inline], [virtual]
Broken assignment operator.
Output function:
Reimplemented from oomph::TimeHarmonicLinearElasticityEquations< DIM >.
Definition at line 91 of file Ttime_harmonic_linear_elasticity_elements.h.
References oomph::TimeHarmonicLinearElasticityEquations< DIM >::output().
output() [4/4]
template<unsigned DIM, unsigned NNODE_1D>
void oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output function:
Reimplemented from oomph::TimeHarmonicLinearElasticityEquations< DIM >.
Definition at line 97 of file Ttime_harmonic_linear_elasticity_elements.h.
References oomph::TimeHarmonicLinearElasticityEquations< DIM >::output().
vertex_node_pt()
template<unsigned DIM, unsigned NNODE_1D>
Node * oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >::vertex_node_pt (const unsigned & j) const [inline], [virtual]
Pointer to the j-th vertex node in the element.
Implements oomph::ElementWithZ2ErrorEstimator.
Definition at line 123 of file Ttime_harmonic_linear_elasticity_elements.h.
The documentation for this class was generated from the following file:
Ttime_harmonic_linear_elasticity_elements.h