oomph::NewtonSolverError Class Reference
A class to handle errors in the Newton solver.
#include <problem.h>
Public Member Functions
NewtonSolverError ()
Default constructor, does nothing.
NewtonSolverError (const bool &Passed_linear_failure)
Constructor that passes a failure of the linear solver.
NewtonSolverError (unsigned Passed_iterations, double Passed_maxres)
Constructor that passes number of iterations and residuals.
bool linear_solver_error ()
Access function to the error in the linear solver.
unsigned iterations ()
Access function to Max. # of iterations performed when the Newton solver died.
double maxres ()
Access function to Max. residual when Newton solver died.
Private Attributes
bool Linear_solver_error
Error in the linear solver.
unsigned Iterations
Max. # of iterations performed when the Newton solver died.
double Maxres
Max. residual when Newton solver died.
Additional Inherited Members
Detailed Description
A class to handle errors in the Newton solver.
Definition at line 3056 of file problem.h.
Constructor & Destructor Documentation
NewtonSolverError() [1/3]
oomph::NewtonSolverError::NewtonSolverError () [inline]
Default constructor, does nothing.
Definition at line 3070 of file problem.h.
NewtonSolverError() [2/3]
oomph::NewtonSolverError::NewtonSolverError (const bool & Passed_linear_failure) [inline]
Constructor that passes a failure of the linear solver.
Definition at line 3081 of file problem.h.
NewtonSolverError() [3/3]
oomph::NewtonSolverError::NewtonSolverError (unsigned Passed_iterations, double Passed_maxres) [inline]
Constructor that passes number of iterations and residuals.
Definition at line 3092 of file problem.h.
Member Function Documentation
iterations()
unsigned oomph::NewtonSolverError::iterations () [inline]
Access function to Max. # of iterations performed when the Newton solver died.
Definition at line 3110 of file problem.h.
References Iterations.
Referenced by oomph::Problem::newton_solve(), oomph::Problem::steady_newton_solve(), and oomph::Problem::unsteady_newton_solve().
linear_solver_error()
bool oomph::NewtonSolverError::linear_solver_error () [inline]
Access function to the error in the linear solver.
Definition at line 3103 of file problem.h.
References Linear_solver_error.
Referenced by oomph::Problem::adaptive_unsteady_newton_solve(), oomph::Problem::arc_length_step_solve_helper(), oomph::Problem::steady_newton_solve(), and oomph::Problem::unsteady_newton_solve().
maxres()
double oomph::NewtonSolverError::maxres () [inline]
Access function to Max. residual when Newton solver died.
Definition at line 3116 of file problem.h.
References Maxres.
Referenced by oomph::Problem::newton_solve(), oomph::Problem::steady_newton_solve(), and oomph::Problem::unsteady_newton_solve().
Member Data Documentation
Iterations
unsigned oomph::NewtonSolverError::Iterations [private]
Max. # of iterations performed when the Newton solver died.
Definition at line 3063 of file problem.h.
Referenced by iterations().
Linear_solver_error
bool oomph::NewtonSolverError::Linear_solver_error [private]
Error in the linear solver.
Definition at line 3060 of file problem.h.
Referenced by linear_solver_error().
Maxres
double oomph::NewtonSolverError::Maxres [private]
Max. residual when Newton solver died.
Definition at line 3066 of file problem.h.
Referenced by maxres().
The documentation for this class was generated from the following file:
problem.h