oomph::AlgebraicNode Class Reference
Algebraic nodes are nodes with an algebraic positional update function.
#include <algebraic_elements.h>
Public Member Functions
AlgebraicNode ()
Default Constructor.
AlgebraicNode (const unsigned &n_dim, const unsigned &n_position_type, const unsigned &initial_nvalue)
Constructor for steady algebraic node of spatial dimension n_dim, with n_position_type generalised coordinates and with initial_nvalue dofs.
AlgebraicNode (TimeStepper *time_stepper_pt, const unsigned &n_dim, const unsigned &n_position_type, const unsigned &initial_nvalue)
Constructor for bog-standard algebraic node of spatial dimension n_dim, with n_position_type generalised coordinates, with initial_nvalue dofs and with time dependence.
virtual ~AlgebraicNode ()
Destructor (empty)
AlgebraicNode (const AlgebraicNode &)=delete
Broken copy constructor.
void node_update (const bool &update_all_time_levels_for_new_node=false)
Broken assignment operator.
unsigned nnode_update_fcts ()
Number of node update fcts.
int node_update_fct_id ()
Default (usually first if there are multiple ones) node update fct id.
void node_update_fct_id (Vector< int > &id)
Return vector of node update fct ids (vector is resized to contain the correct number of entries). Somewhat costly to call as map needs to be copied into vector.
AlgebraicMesh * mesh_pt ()
Default (usually first) mesh that implements update function.
AlgebraicMesh * mesh_pt (const int &id)
Mesh that implements the id-th node update function.
unsigned ngeom_object (const int &id)
Number of geometric objects involved in id-th update function.
unsigned ngeom_object () const
Number of geometric objects involved in default (usually first) update function.
Vector< GeomObject * > & vector_geom_object_pt (const int &id)
Return vector of geometric objects involved in id-th update function.
Vector< GeomObject * > & vector_geom_object_pt ()
Return vector of geometric objects involved in default (usually first) update function.
GeomObject ** all_geom_object_pt ()
Return the vector of all geometric objects.
GeomObject * geom_object_pt (const unsigned &i)
Return pointer to i-th geometric object involved in default (usually first) update function.
unsigned nref_value (const int &id)
Number of reference values involved in id-th update function.
unsigned nref_value ()
Number of reference values involved in default (usually first) update function.
Vector< double > & vector_ref_value ()
Return vector of reference values involved in default (usually first) update function.
Vector< double > & vector_ref_value (const int &id)
Return vector of reference values involved in id-th update function.
double ref_value (const unsigned &i)
Return i-th reference value involved in default (usually first) update function.
void add_node_update_info (const int &id, AlgebraicMesh *mesh_pt, const Vector< GeomObject * > &geom_object_pt, const Vector< double > &ref_value, const bool &called_from_constructor=false)
Add algebraic update information for node: What's the ID of the mesh update function (typically used within the mesh) Which Mesh implements the update operation? Also, pass the vector of geometric objects and the vectors of reference values that are needed for the update operation. Negative values for ID are only allowed when called from node constructor, as indicated by the final argument which defaults to false.
void add_node_update_info (AlgebraicMesh *mesh_pt, const Vector< GeomObject * > &geom_object_pt, const Vector< double > &ref_value)
Add algebraic update information for node: Which Mesh implements the update operation? Also, pass the vector of geometric objects and the vectors of reference values that are needed for the update operation. We're assigning a default node update fct id of 0.
void kill_node_update_info (const int &id=0)
Erase algebraic node update information for id-th node update function. Id defaults to 0.
unsigned self_test ()
Perform self test: If the node has multiple node update functions, check that they all give the same result. Return 1/0 for failure/success. (Failure if max. difference between the nodal positions for different update functions exceeds AlgebraicNode::Max_allowed_difference_between_node_update_fcts.
Public Member Functions inherited from oomph::Node
Node ()
Default constructor.
Node (const unsigned &n_dim, const unsigned &n_position_type, const unsigned &initial_n_value, const bool &allocate_x_position=true)
Steady constructor, for a Node of spatial dimension n_dim. Allocates storage for initial_n_value values. NPosition_type is the number of coordinate types needed in the mapping between local and global coordinates (e.g. 1 for Lagrange-type elements; 2 for 1D Hermite elements; 4 for 2D Hermite elements, etc).
Node (TimeStepper *const &time_stepper_pt, const unsigned &n_dim, const unsigned &n_position_type, const unsigned &initial_n_value, const bool &allocate_x_position=true)
Unsteady constructor for a node of spatial dimension n_dim. Allocates storage for initial_n_value values with history values as required by the timestepper. n_position_type: # of coordinate types needed in the mapping between local and global coordinates (e.g. 1 for Lagrange-type elements; 2 for 1D Hermite elements; 4 for 2D Hermite elements).
virtual ~Node ()
Destructor: Clean up the memory allocated for nodal position.
Node (const Node &node)=delete
Broken copy constructor.
void operator= (const Node &)=delete
Broken assignment operator.
unsigned nposition_type () const
Number of coordinate types needed in the mapping between local and global coordinates.
TimeStepper *& position_time_stepper_pt ()
Return a pointer to the position timestepper.
TimeStepper *const & position_time_stepper_pt () const
Return a pointer to the position timestepper (const version).
virtual void set_position_time_stepper (TimeStepper *const &position_time_stepper_pt, const bool &preserve_existing_data)
Set a new position timestepper be resizing the appropriate storage.
virtual bool does_pointer_correspond_to_position_data (double *const &parameter_pt)
Check whether the pointer parameter_pt addresses position data values. It never does for a standard node, because the positions are not data.
virtual void assign_eqn_numbers (unsigned long &global_ndof, Vector< double * > &dof_pt)
Assign global equation numbers; increment global number of unknowns, global_ndof; and add any new dofs to the dof_pt.
unsigned ndim () const
Return (Eulerian) spatial dimension of the node.
double & x (const unsigned &i)
Return the i-th nodal coordinate.
const double & x (const unsigned &i) const
Return the i-th nodal coordinate (const version).
double & x (const unsigned &t, const unsigned &i)
Return the position x(i) at previous timestep t (t=0: present; t>0 previous timestep).
const double & x (const unsigned &t, const unsigned &i) const
Return the position x(i) at previous timestep t (t=0: present; t>0 previous timestep) (const version)
double dx_dt (const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt.
double dx_dt (const unsigned &j, const unsigned &i) const
Return the i-th component of j-th derivative of nodal position: d^jx/dt^j.
virtual Node * copied_node_pt () const
Return pointer to copied node (null if the current node is not a copy -- always the case here; it's overloaded for boundary nodes)
virtual bool position_is_a_copy () const
Return whether any position coordinate has been copied (always false)
virtual bool position_is_a_copy (const unsigned &i) const
Return whether the position coordinate i has been copied (always false)
double & x_gen (const unsigned &k, const unsigned &i)
Reference to the generalised position x(k,i). `Type': k; Coordinate direction: i.
const double & x_gen (const unsigned &k, const unsigned &i) const
Reference to the generalised position x(k,i). `Type': k; Coordinate direction: i (const version).
double & x_gen (const unsigned &t, const unsigned &k, const unsigned &i)
Reference to the generalised position x(k,i) at the previous timestep [t=0: present]. `Type': k; Coordinate direction: i.
const double & x_gen (const unsigned &t, const unsigned &k, const unsigned &i) const
Reference to the generalised position x(k,i) at the previous timestep [t=0: present]. `Type': k; Coordinate direction: i. (const version)
double dx_gen_dt (const unsigned &k, const unsigned &i) const
i-th component of time derivative (velocity) of the generalised position, dx(k,i)/dt. `Type': k; Coordinate direction: i.
double dx_gen_dt (const unsigned &j, const unsigned &k, const unsigned &i) const
i-th component of j-th time derivative (velocity) of the generalised position, d^jx(k,i)/dt^j. `Type': k; Coordinate direction: i.
double * x_pt (const unsigned &t, const unsigned &i)
Direct access to the i-th coordinate at time level t (t=0: present; t>0: previous)
void copy (Node *orig_node_pt)
Copy all nodal data from specified Node object.
virtual void dump (std::ostream &dump_file) const
Dump nodal position and associated data to file for restart.
void read (std::ifstream &restart_file)
Read nodal position and associated data from file for restart.
virtual void pin_all ()
The pin_all() function must be overloaded by SolidNodes, so we put the virtual interface here to avoid virtual functions in Data.
virtual void unpin_all ()
The unpin_all() function must be overloaded by SolidNode, so we put the virtual interface here to avoid virtual functions in Data.
unsigned hang_code ()
Code that encapsulates the hanging status of the node (incl. the geometric hanging status) as $  \sum_{i=-1}{nval-1} Node::is_hanging(i) 2^{i+1} $.
HangInfo *const & hanging_pt () const
Return pointer to hanging node data (this refers to the geometric hanging node status) (const version).
HangInfo *const & hanging_pt (const int &i) const
Return pointer to hanging node data for value i (const version)
bool is_hanging () const
Test whether the node is geometrically hanging.
bool is_hanging (const int &i) const
Test whether the i-th value is hanging.
void set_hanging_pt (HangInfo *const &hang_pt, const int &i)
Set the hanging data for the i-th value. (hang_pt=0 to make non-hanging)
void set_nonhanging ()
Label node as non-hanging node by removing all hanging node data.
void resize (const unsigned &n_value)
Resize the number of equations.
virtual void constrain_positions ()
Constrain the positions when the node is made hanging Empty virtual function that is overloaded in SolidNodes.
virtual void unconstrain_positions ()
Unconstrain the positions when the node is made non-hanging Empty virtual function that is overloaded in SolidNodes.
virtual void make_periodic (Node *const &node_pt)
Make the node periodic by copying the values from node_pt. Note that the coordinates will always remain independent, even though this may lead to (a little) unrequired information being stored. Broken virtual (only implemented in BoundaryNodes)
virtual void make_periodic_nodes (const Vector< Node * > &periodic_nodes_pt)
Make the nodes passed in the vector periodic_nodes share the same data as this node.
virtual void get_boundaries_pt (std::set< unsigned > *&boundaries_pt)
Return a pointer to set of mesh boundaries that this node occupies; this will be overloaded by BoundaryNodes. The default behaviour is that the Node does not lie on any boundaries so the pointer to the set of boundaries is NULL.
virtual bool is_on_boundary () const
Test whether the Node lies on a boundary. The "bulk" Node cannot lie on a boundary, so return false. This will be overloaded by BoundaryNodes.
virtual bool is_on_boundary (const unsigned &b) const
Test whether the node lies on mesh boundary b. The "bulk" Node cannot lie on a boundary, so return false. This will be overloaded by BoundaryNodes.
virtual void add_to_boundary (const unsigned &b)
Broken interface for adding the node to the mesh boundary b Essentially here for error reporting.
virtual void remove_from_boundary (const unsigned &b)
Broken interface for removing the node from the mesh boundary b Here to provide error reporting.
virtual unsigned ncoordinates_on_boundary (const unsigned &b)
Get the number of boundary coordinates on mesh boundary b. Broken virtual interface provides run-time error checking.
virtual bool boundary_coordinates_have_been_set_up ()
Have boundary coordinates been set up? Broken virtual interface provides run-time error checking.
virtual void get_coordinates_on_boundary (const unsigned &b, const unsigned &k, Vector< double > &boundary_zeta)
Return the vector of the k-th generalised boundary coordinates on mesh boundary b. Broken virtual interface provides run-time error checking.
virtual void set_coordinates_on_boundary (const unsigned &b, const unsigned &k, const Vector< double > &boundary_zeta)
Set the vector of the k-th generalised boundary coordinates on mesh boundary b. Broken virtual interface provides run-time error checking.
virtual void get_coordinates_on_boundary (const unsigned &b, Vector< double > &boundary_zeta)
Return the vector of coordinates on mesh boundary b Broken virtual interface provides run-time error checking.
virtual void set_coordinates_on_boundary (const unsigned &b, const Vector< double > &boundary_zeta)
Set the vector of coordinates on mesh boundary b Broken virtual interface provides run-time error checking.
void set_obsolete ()
Mark node as obsolete.
void set_non_obsolete ()
Mark node as non-obsolete.
bool is_obsolete ()
Test whether node is obsolete.
double raw_value (const unsigned &i) const
Return the i-th value stored at the Node. This interface does NOT take the hanging status of the Node into account.
double raw_value (const unsigned &t, const unsigned &i) const
Return the i-th value at time level t (t=0: present, t>0: previous). This interface does NOT take the hanging status of the Node into account.
double value (const unsigned &i) const
Return i-th value (dofs or pinned) at this node either directly or via hanging node representation. Note that this REDFINES the interface in Data Thus, the present function will be called provided that it is accessed through a pointer to a node i.e. Node* node_pt->value() will take hanging information into account. If a pointer to a Node has been explicitly down-cast to a pointer to Data then the "wrong" (Data) version of the function will be called.
double value (const unsigned &t, const unsigned &i) const
Return i-th value at time level t (t=0: present, t>0: previous) either directly or via hanging node representation. Note that this REDEFINES the interface in Data Thus, the present function will be called provided that it is accessed through a pointer to a node i.e. Node* node_pt->value() will take hanging information into account. If a pointer to a Node has been explicitly down-cast to a pointer to Data then the "wrong" (Data) version of the function will be called.
void value (Vector< double > &values) const
Compute Vector of values for the Data value taking the hanging node status into account. Note that this REDEFINES the interface in Data Thus, the present function will be called provided that it is accessed through a pointer to a node i.e. Node* node_pt->value() will take hanging information into account. If a pointer to a Node has been explicitly down-cast to a pointer to Data then the "wrong" (Data) version of the function will be called.
Vector< double > value () const
Return vector of values calculated using value(vector).
void value (const unsigned &t, Vector< double > &values) const
Compute Vector of values (dofs or pinned) in this data at time level t (t=0: present; t>0: previous). This interface explicitly takes the hanging status into account. Thus, the present function will be called provided that it is accessed through a pointer to a node i.e. Node* node_pt->value() will take hanging information into account. If a pointer to a Node has been explicitly down-cast to a pointer to Data then the "wrong" (Data) version of the function will be called.
void position (Vector< double > &pos) const
Compute Vector of nodal positions either directly or via hanging node representation.
Vector< double > position () const
Return vector of position of node at current time.
void position (const unsigned &t, Vector< double > &pos) const
Compute Vector of nodal position at time level t (t=0: current; t>0: previous timestep), either directly or via hanging node representation.
double position (const unsigned &i) const
Return i-th nodal coordinate either directly or via hanging node representation.
double position (const unsigned &t, const unsigned &i) const
Return i-th nodal coordinate at time level t (t=0: current; t>0: previous time level), either directly or via hanging node representation.
double position_gen (const unsigned &k, const unsigned &i) const
Return generalised nodal coordinate either directly or via hanging node representation.
double position_gen (const unsigned &t, const unsigned &k, const unsigned &i) const
Return generalised nodal coordinate at time level t (t=0: current; t>0: previous time level), either directly or via hanging node representation.
double dposition_dt (const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt, either directly or via hanging node representation.
double dposition_dt (const unsigned &j, const unsigned &i) const
Return the i-th component of j-th derivative of nodal position: d^jx/dt^j either directly or via hanging node representation.
double dposition_gen_dt (const unsigned &k, const unsigned &i) const
i-th component of time derivative (velocity) of the generalised position, dx(k,i)/dt. `Type': k; Coordinate direction: i. This function uses the hanging node representation if necessary.
double dposition_gen_dt (const unsigned &j, const unsigned &k, const unsigned &i) const
i-th component of j-th time derivative (velocity) of the generalised position, d^jx(k,i)/dt^j. `Type': k; Coordinate direction: i. This function uses the hanging node representation if necessary
void set_auxiliary_node_update_fct_pt (AuxNodeUpdateFctPt aux_node_update_fct_pt)
Set pointer to auxiliary update function -- this can be used to update any nodal values following the update of the nodal position. This is needed e.g. to update the no-slip condition on moving boundaries.
bool has_auxiliary_node_update_fct_pt ()
Boolean to indicate if node has a pointer to and auxiliary update function.
void perform_auxiliary_node_update_fct ()
Execute auxiliary update function (if any) -- this can be used to update any nodal values following the update of the nodal position. This is needed e.g. to update the no-slip condition on moving boundaries.
virtual unsigned ngeom_data () const
Return the number of geometric data that affect the nodal position. The default value is zero (node is stationary)
virtual Data ** all_geom_data_pt ()
Return a pointer to an array of all (geometric) data that affect the nodal position. The default value is zero (node is stationary)
void output (std::ostream &outfile)
Output nodal position.
void add_values_to_vector (Vector< double > &vector_of_values)
Add all data and time history values to the vector. Overloaded to add the position information as well.
void read_values_from_vector (const Vector< double > &vector_of_values, unsigned &index)
Read all data and time history values from the vector starting from index. On return the index will be set the value at the end of the data that has been read in Overload to also read the position information.
Public Member Functions inherited from oomph::Data
virtual void clear_copied_pointers ()
Helper function that should be overloaded derived classes that contain copies of data. The function must unset (NULL out) the internal pointers to the copied data. This is used when destructing data to ensure that all pointers remain valid. The default implementation throws an error because Data cannot be a copy.
Data ()
Default: Just set pointer to (steady) timestepper. No storage for values is allocated.
Data (const unsigned &initial_n_value)
Default constructor for steady problems: assign memory for initial_n_value values.
Data (TimeStepper *const &time_stepper_pt, const unsigned &initial_n_value, const bool &allocate_storage=true)
Constructor for unsteady problems: assign memory for initial_n_value values and any memory required by the Timestepper for the storage of history values.
Data (const Data &data)=delete
Broken copy constructor.
void operator= (const Data &)=delete
Broken assignment operator.
virtual ~Data ()
Destructor, deallocates memory assigned for data.
void set_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set a new timestepper by resizing the appropriate storage. If already assigned the equation numbering will not be altered.
TimeStepper *& time_stepper_pt ()
Return the pointer to the timestepper.
TimeStepper *const & time_stepper_pt () const
Return the pointer to the timestepper (const version).
virtual bool is_a_copy () const
Return a boolean to indicate whether the Data objact contains any copied values. A base Data object can never be a copy so the default implementation always returns false.
virtual bool is_a_copy (const unsigned &i) const
Return flag to indicate whether the i-th value is a copy. A base Data object can never be a copy so the default implementation always returns false.
void set_value (const unsigned &i, const double &value_)
Set the i-th stored data value to specified value. The only reason that we require an explicit set function is because we redefine value() in the Node class to interpolate the values for nodes that are hanging and so we cannot return a reference to the value in this case.
void set_value (const unsigned &t, const unsigned &i, const double &value_)
Set the t-th history value of the i-th stored data value to specified value.
double value (const unsigned &i) const
Return i-th stored value. This function is not virtual so that it can be inlined. This means that if we have an explicit pointer to a Data object Data* data_pt->value() always returns the "raw" stored value.
double value (const unsigned &t, const unsigned &i) const
Return i-th value at time level t (t=0: present, t>0: previous) This function is not virtual so that it can be inlined. This means that if we have an explicit pointer to a Data object Data* data_pt->value() always returns to the "raw" stored value.
void value (Vector< double > &values) const
Compute Vector of values for the Data value.
void value (const unsigned &t, Vector< double > &values) const
Compute Vector of values (dofs or pinned) in this data at time level t (t=0: present; t>0: previous).
double * value_pt (const unsigned &i) const
Return the pointer to the i-the stored value. Typically this is required when direct access to the stored value is required, e.g. when writing functions that return a reference to a variable that is stored in a Data object.
double * value_pt (const unsigned &t, const unsigned &i) const
Return the pointer to the i-th stored value, or any of its history values (const version). Typically this is required when direct access to the stored value is required, e.g. when writing functions that return a reference to a variable that is stored in a Data object.
bool does_pointer_correspond_to_value (double *const &parameter_pt)
Check whether the pointer parameter_pt addresses internal data values.
void copy (Data *orig_data_pt)
Copy Data values from specified Data object.
void dump (std::ostream &dump_file) const
Dump the data object to a file.
void read (std::ifstream &restart_file)
Read data object from a file.
long * eqn_number_pt (const unsigned &i)
Return the pointer to the equation number of the i-th stored variable.
long & eqn_number (const unsigned &i)
Return the equation number of the i-th stored variable.
long eqn_number (const unsigned &i) const
Return the equation number of the i-th stored variable.
void pin (const unsigned &i)
Pin the i-th stored variable.
void unpin (const unsigned &i)
Unpin the i-th stored variable.
void pin_all ()
Pin all the stored variables.
void unpin_all ()
Unpin all the stored variables.
bool is_pinned (const unsigned &i) const
Test whether the i-th variable is pinned (1: true; 0: false).
bool is_segregated_solve_pinned (const unsigned &i)
Test whether the i-th variable is temporaily pinned for a segregated solve.
void constrain (const unsigned &i)
Constrain the i-th stored variable when making hanging data If the data is already pinned leave it along, otherwise mark as constrained (hanging)
void unconstrain (const unsigned &i)
Unconstrain the i-th stored variable when make the data nonhanging. Only unconstrain if it was actually constrained (hanging)
void constrain_all ()
Constrain all the stored variables when the data is made hanging.
void unconstrain_all ()
Unconstrain all the stored variables when the data is made nonhanging.
bool is_constrained (const unsigned &i)
Test whether the i-th variable is constrained (1: true; 0: false).
unsigned self_test ()
Self-test: Have all values been classified as pinned/unpinned? Return 0 if OK.
unsigned nvalue () const
Return number of values stored in data object (incl pinned ones).
unsigned ntstorage () const
Return total number of doubles stored per value to record time history of each value (one for steady problems).
virtual void describe_dofs (std::ostream &out, const std::string &current_string) const
Function to describe the dofs of the Node. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
virtual void add_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
Add pointers to all unpinned and unconstrained data to a map indexed by (global) equation number.
void set_halo (const unsigned &non_halo_proc_ID)
Label the node as halo and specify processor that holds non-halo counterpart.
void set_nonhalo ()
Label the node as not being a halo.
bool is_halo () const
Is this Data a halo?
int non_halo_proc_ID ()
ID of processor ID that holds non-halo counterpart of halo node; negative if not a halo.
virtual void add_eqn_numbers_to_vector (Vector< long > &vector_of_eqn_numbers)
Add all equation numbers to the vector in the internal storage order.
virtual void read_eqn_numbers_from_vector (const Vector< long > &vector_of_eqn_numbers, unsigned &index)
Read all equation numbers from the vector starting from index. On return the index will be set to the value at the end of the data that has been read in.
Private Member Functions
void set_default_node_update (const int &id)
Make id-th node update function the default.
Private Attributes
std::map< int, AlgebraicMesh * > Mesh_pt
Pointer to mesh that performs the specified node update operation (Map because this node may only use the Mesh's 116th node update fct. There's no point in wasting an entire vector for the non-existing entries)
std::map< int, Vector< GeomObject * > > Geom_object_pt
Vector of geometric objects that are involved in the specified node update operation. (Map because this node may only use the Mesh's 116th node update fct. There's no point in wasting an entire vector for the non-existing entries)
std::map< int, Vector< double > > Ref_value
Vector of reference values that are required for the specified node update operation. (Map because this node may only use the Mesh's 116th node update fct. There's no point in wasting an entire vector for the non-existing entries)
std::map< int, AlgebraicMesh * >::iterator Default_it_mesh_pt
Default iterator for mesh: This mesh performs the default update.
std::map< int, Vector< GeomObject * > >::iterator Default_it_geom_object_pt
Default iterator for vector of geom objects. These GeomObjects are involved in the default update.
std::map< int, Vector< double > >::iterator Default_it_ref_value
Default iterator for vector of ref values. These reference values are involved in the default update.
int Default_node_update_fct_id
Default node update function ID.
Static Private Attributes
static double Max_allowed_difference_between_node_update_fcts
What it says: Used in self-test to check if different node update functions produce the same result.
static int Dummy_node_update_fct_id = -100
Default (negative!) remesh fct id for nodes for which no remesh fct is defined.
static AlgebraicMesh * Dummy_mesh_pt = &AlgebraicNode::Dummy_mesh
Default dummy mesh to point to for nodes for which no remesh fct is defined.
static DummyAlgebraicMesh Dummy_mesh
Static Dummy mesh to which the pointer is addressed.
static Vector< GeomObject * > Dummy_geom_object_pt
Default dummy vector of geom objects to point to for nodes for which no remesh fct is defined.
static Vector< double > Dummy_ref_value
Default dummy vector of reference values to point to for nodes for which no remesh fct is defined.
Additional Inherited Members
Public Types inherited from oomph::Node
typedef void(* AuxNodeUpdateFctPt) (Node *)
Function pointer to auxiliary node update function.
Static Public Attributes inherited from oomph::Node
static unsigned No_independent_position = 10
Static "Magic number" used to indicate that there is no independent position in a periodic node.
Static Public Attributes inherited from oomph::Data
static long Is_pinned = -1
Static "Magic number" used in place of the equation number to indicate that the value is pinned.
static long Is_segregated_solve_pinned = -3
Static "Magic number" used in place of the equation number to indicate that the value is pinned, but only for the duration of a segregated solve.
static long Is_unclassified = -10
Static "Magic number" used in place of the equation number to denote a value that hasn't been classified as pinned or free.
static long Is_constrained = -2
Static "Magic number" used in place of the equation number to indicate that the value is constrained because it is associated with non-conforming element boundaries --- a hanging node --- (and is therefore pinned)
Protected Member Functions inherited from oomph::Node
void x_gen_range_check (const unsigned &t, const unsigned &k, const unsigned &i) const
Private function to check that the arguemnts to the position functions are in range.
double * x_position_pt (const unsigned &i)
Direct access to the pointer to the i-th stored coordinate data.
Protected Member Functions inherited from oomph::Data
virtual void reset_copied_pointers ()
Helper function that should be overloaded in derived classes that can contain copies of Data. The function must reset the internal pointers to the copied data. This is used when resizing data to ensure that all the pointers remain valid. The default implementation throws an error beacause Data cannot be a copy.
Protected Attributes inherited from oomph::Node
double ** X_position
Array of pointers to the data holding the Eulerian positions. The storage format must be the same as the internal data storage so that we can implement the functions x() in generality here without the need for virtual functions. The first index will be a flat array of position types and coordinates and the second will be the number of time history values at each position type.
TimeStepper * Position_time_stepper_pt
Pointer to the timestepper associated with the position data.
HangInfo ** Hanging_pt
C-style array of pointers to hanging node info. It's set to NULL if the node isn't hanging. The first entry (0) is the geometric hanging node data. The remaining entries correspond to the hanging data for the other values stored at the node. Usually, these entries will be the same as the geometric hanging node data represented by Hanging_pt[0], but this is not necessarily the case; e.g. the pressure in Taylor Hood has different hanging node data from the velocities.
unsigned Ndim
Eulerian dimension of the node.
unsigned Nposition_type
Number of coordinate types used in the mapping between local and global coordinates (e.g. 1 for Lagrange-type elements; 2 for 1D Hermite elements; 4 for 2D Hermite elements, etc).
bool Obsolete
Flag to indicate that the Node has become obsolete --- usually during mesh refinement process.
AuxNodeUpdateFctPt Aux_node_update_fct_pt
Pointer to auxiliary update function -- this can be used to update any nodal values following the update of the nodal position. This is needed e.g. to update the no-slip condition on moving boundaries.
Protected Attributes inherited from oomph::Data
Data ** Copy_of_data_pt
C-style array of any Data objects that contain copies of the current Data object's data values.
unsigned Ncopies
Number of Data that contain copies of this Data object's values.
Static Protected Attributes inherited from oomph::Data
static TimeStepper * Default_static_time_stepper_pt = new Steady<0>()
Default (static) timestepper used in steady problems.
Detailed Description
Algebraic nodes are nodes with an algebraic positional update function.
Definition at line 54 of file algebraic_elements.h.
Constructor & Destructor Documentation
AlgebraicNode() [1/4]
oomph::AlgebraicNode::AlgebraicNode () [inline]
Default Constructor.
Definition at line 58 of file algebraic_elements.h.
AlgebraicNode() [2/4]
oomph::AlgebraicNode::AlgebraicNode (const unsigned & n_dim, const unsigned & n_position_type, const unsigned & initial_nvalue) [inline]
Constructor for steady algebraic node of spatial dimension n_dim, with n_position_type generalised coordinates and with initial_nvalue dofs.
Definition at line 63 of file algebraic_elements.h.
References add_node_update_info(), oomph::LeakCheckNames::AlgebraicNode_build, Dummy_geom_object_pt, Dummy_mesh_pt, Dummy_node_update_fct_id, and Dummy_ref_value.
AlgebraicNode() [3/4]
oomph::AlgebraicNode::AlgebraicNode (TimeStepper * time_stepper_pt, const unsigned & n_dim, const unsigned & n_position_type, const unsigned & initial_nvalue) [inline]
Constructor for bog-standard algebraic node of spatial dimension n_dim, with n_position_type generalised coordinates, with initial_nvalue dofs and with time dependence.
Definition at line 85 of file algebraic_elements.h.
References add_node_update_info(), oomph::LeakCheckNames::AlgebraicNode_build, Dummy_geom_object_pt, Dummy_mesh_pt, Dummy_node_update_fct_id, and Dummy_ref_value.
~AlgebraicNode()
virtual oomph::AlgebraicNode::~AlgebraicNode () [inline], [virtual]
Destructor (empty)
Definition at line 105 of file algebraic_elements.h.
References oomph::LeakCheckNames::AlgebraicNode_build.
AlgebraicNode() [4/4]
oomph::AlgebraicNode::AlgebraicNode (const AlgebraicNode &) [delete]
Broken copy constructor.
Member Function Documentation
add_node_update_info() [1/2]
void oomph::AlgebraicNode::add_node_update_info (AlgebraicMesh * mesh_pt, const Vector< GeomObject * > & geom_object_pt, const Vector< double > & ref_value) [inline]
Add algebraic update information for node: Which Mesh implements the update operation? Also, pass the vector of geometric objects and the vectors of reference values that are needed for the update operation. We're assigning a default node update fct id of 0.
Definition at line 331 of file algebraic_elements.h.
References Default_it_mesh_pt, Dummy_mesh_pt, Dummy_node_update_fct_id, geom_object_pt(), Geom_object_pt, kill_node_update_info(), mesh_pt(), Mesh_pt, ref_value(), Ref_value, and set_default_node_update().
add_node_update_info() [2/2]
void oomph::AlgebraicNode::add_node_update_info (const int & id, AlgebraicMesh * mesh_pt, const Vector< GeomObject * > & geom_object_pt, const Vector< double > & ref_value, const bool & called_from_constructor = false) [inline]
Add algebraic update information for node: What's the ID of the mesh update function (typically used within the mesh) Which Mesh implements the update operation? Also, pass the vector of geometric objects and the vectors of reference values that are needed for the update operation. Negative values for ID are only allowed when called from node constructor, as indicated by the final argument which defaults to false.
Definition at line 280 of file algebraic_elements.h.
References Default_it_mesh_pt, Dummy_mesh_pt, Dummy_node_update_fct_id, geom_object_pt(), Geom_object_pt, kill_node_update_info(), mesh_pt(), Mesh_pt, ref_value(), Ref_value, and set_default_node_update().
Referenced by AlgebraicNode(), AlgebraicNode(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::update_node_update_in_lower_right_box(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::update_node_update_in_region(), and oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::update_node_update_in_upper_left_box().
all_geom_object_pt()
GeomObject ** oomph::AlgebraicNode::all_geom_object_pt () [inline], [virtual]
Return the vector of all geometric objects.
Reimplemented from oomph::Node.
Definition at line 215 of file algebraic_elements.h.
References Default_it_geom_object_pt, and ngeom_object().
geom_object_pt()
GeomObject * oomph::AlgebraicNode::geom_object_pt (const unsigned & i) [inline]
Return pointer to i-th geometric object involved in default (usually first) update function.
Definition at line 229 of file algebraic_elements.h.
References Default_it_geom_object_pt, and i.
Referenced by add_node_update_info(), add_node_update_info(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update_in_upper_left_box(), and oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update_upper_left_region().
kill_node_update_info()
void oomph::AlgebraicNode::kill_node_update_info (const int & id = 0) [inline]
Erase algebraic node update information for id-th node update function. Id defaults to 0.
Definition at line 365 of file algebraic_elements.h.
References Geom_object_pt, Mesh_pt, and Ref_value.
Referenced by add_node_update_info(), add_node_update_info(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::update_node_update_in_lower_right_box(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::update_node_update_in_region(), and oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::update_node_update_in_upper_left_box().
mesh_pt() [1/2]
AlgebraicMesh * oomph::AlgebraicNode::mesh_pt () [inline]
Default (usually first) mesh that implements update function.
Definition at line 170 of file algebraic_elements.h.
References Default_it_mesh_pt.
Referenced by add_node_update_info(), add_node_update_info(), and node_update().
mesh_pt() [2/2]
AlgebraicMesh * oomph::AlgebraicNode::mesh_pt (const int & id) [inline]
Mesh that implements the id-th node update function.
Definition at line 177 of file algebraic_elements.h.
References Mesh_pt.
ngeom_object() [1/2]
unsigned oomph::AlgebraicNode::ngeom_object () const [inline], [virtual]
Number of geometric objects involved in default (usually first) update function.
Reimplemented from oomph::Node.
Definition at line 192 of file algebraic_elements.h.
References Default_it_geom_object_pt, and oomph::FiniteElement::size().
Referenced by all_geom_object_pt().
ngeom_object() [2/2]
unsigned oomph::AlgebraicNode::ngeom_object (const int & id) [inline]
Number of geometric objects involved in id-th update function.
Definition at line 184 of file algebraic_elements.h.
References Geom_object_pt, and oomph::FiniteElement::size().
nnode_update_fcts()
unsigned oomph::AlgebraicNode::nnode_update_fcts () [inline]
Number of node update fcts.
Definition at line 136 of file algebraic_elements.h.
References Mesh_pt, and oomph::FiniteElement::size().
Referenced by node_update(), and self_test().
node_update()
void oomph::AlgebraicNode::node_update (const bool & update_all_time_levels_for_new_node = false) [virtual]
Broken assignment operator.
Excute the node update function: Update the current (and if update_all_time_levels_for_new_node==true also the previous) nodal position. Also update the current nodal values if an auxiliary update function is defined. Note: updating of previous positions is only required (and should only be performed for) newly created AlgebraicNodes i.e. when this function is called from AlgebraicElementBase::setup_algebraic_node_update(...). We create the history of its nodal positions from the time-dependent version of the specific AlgebraicMesh's algebraic_node_update(...) function.
Update the current nodal position, using the first (default) update function if there are multiple ones. If required perform the auxiliary update of nodal values. If update_all_time_levels_for_new_node==true, previous positions are also updated -- as indicated by the name of this flag, this should only be done for newly created nodes, when this function is called from AlgebraicElementBase::setup_algebraic_node_update(...) Perform auxiliary update of function values?
Reimplemented from oomph::Node.
Definition at line 231 of file algebraic_elements.cc.
References oomph::AlgebraicMesh::algebraic_node_update(), oomph::Node::Aux_node_update_fct_pt, oomph::Node::hanging_pt(), oomph::Node::is_hanging(), oomph::HangInfo::master_node_pt(), mesh_pt(), Mesh_pt, oomph::HangInfo::nmaster(), nnode_update_fcts(), node_update(), oomph::TimeStepper::nprev_values(), oomph::Node::Position_time_stepper_pt, and t.
Referenced by node_update(), and self_test().
node_update_fct_id() [1/2]
int oomph::AlgebraicNode::node_update_fct_id () [inline]
Default (usually first if there are multiple ones) node update fct id.
Definition at line 146 of file algebraic_elements.h.
References Default_node_update_fct_id.
Referenced by oomph::AlgebraicFishMesh< ELEMENT >::algebraic_node_update(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::algebraic_node_update(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::algebraic_node_update(), self_test(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::update_node_update(), and oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::update_node_update().
node_update_fct_id() [2/2]
void oomph::AlgebraicNode::node_update_fct_id (Vector< int > & id) [inline]
Return vector of node update fct ids (vector is resized to contain the correct number of entries). Somewhat costly to call as map needs to be copied into vector.
Definition at line 154 of file algebraic_elements.h.
References Mesh_pt.
nref_value() [1/2]
unsigned oomph::AlgebraicNode::nref_value () [inline]
Number of reference values involved in default (usually first) update function.
Definition at line 243 of file algebraic_elements.h.
References Default_it_ref_value, and oomph::FiniteElement::size().
nref_value() [2/2]
unsigned oomph::AlgebraicNode::nref_value (const int & id) [inline]
Number of reference values involved in id-th update function.
Definition at line 235 of file algebraic_elements.h.
References Ref_value, and oomph::FiniteElement::size().
ref_value()
double oomph::AlgebraicNode::ref_value (const unsigned & i) [inline]
Return i-th reference value involved in default (usually first) update function.
Definition at line 267 of file algebraic_elements.h.
References Default_it_ref_value, and i.
Referenced by add_node_update_info(), add_node_update_info(), and oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update_in_upper_left_box().
self_test()
unsigned oomph::AlgebraicNode::self_test ()
Perform self test: If the node has multiple node update functions, check that they all give the same result. Return 1/0 for failure/success. (Failure if max. difference between the nodal positions for different update functions exceeds AlgebraicNode::Max_allowed_difference_between_node_update_fcts.
Perform self test: If the node has multiple update functions, check that all update functions give the same result (with a tolerance of AlgebraicNode::Max_allowed_difference_between_node_update_fcts.
Definition at line 297 of file algebraic_elements.cc.
References i, Max_allowed_difference_between_node_update_fcts, oomph::Node::ndim(), nnode_update_fcts(), node_update(), node_update_fct_id(), oomph::oomph_info, oomph::Data::self_test(), set_default_node_update(), oomph::FiniteElement::size(), and oomph::Node::x().
set_default_node_update()
void oomph::AlgebraicNode::set_default_node_update (const int & id) [inline], [private]
Make id-th node update function the default.
Definition at line 384 of file algebraic_elements.h.
References Default_it_geom_object_pt, Default_it_mesh_pt, Default_it_ref_value, Default_node_update_fct_id, Geom_object_pt, Mesh_pt, and Ref_value.
Referenced by add_node_update_info(), add_node_update_info(), and self_test().
vector_geom_object_pt() [1/2]
Vector< GeomObject * > & oomph::AlgebraicNode::vector_geom_object_pt () [inline]
Return vector of geometric objects involved in default (usually first) update function.
Definition at line 208 of file algebraic_elements.h.
References Default_it_geom_object_pt.
vector_geom_object_pt() [2/2]
Vector< GeomObject * > & oomph::AlgebraicNode::vector_geom_object_pt (const int & id) [inline]
Return vector of geometric objects involved in id-th update function.
Definition at line 200 of file algebraic_elements.h.
References Geom_object_pt.
Referenced by oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update_in_central_box(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update_in_lower_right_box(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update_in_upper_left_box(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update_lower_right_region(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update_upper_left_region(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::update_node_update_in_lower_right_box(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::update_node_update_in_region(), and oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::update_node_update_in_upper_left_box().
vector_ref_value() [1/2]
Vector< double > & oomph::AlgebraicNode::vector_ref_value () [inline]
Return vector of reference values involved in default (usually first) update function.
Definition at line 251 of file algebraic_elements.h.
References Default_it_ref_value.
Referenced by oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update_in_central_box(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update_in_lower_right_box(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update_in_upper_left_box(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update_lower_right_region(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update_upper_left_region(), oomph::AlgebraicElementBase::setup_algebraic_node_update(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::update_node_update_in_lower_right_box(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::update_node_update_in_region(), and oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::update_node_update_in_upper_left_box().
vector_ref_value() [2/2]
Vector< double > & oomph::AlgebraicNode::vector_ref_value (const int & id) [inline]
Return vector of reference values involved in id-th update function.
Definition at line 259 of file algebraic_elements.h.
References Ref_value.
Member Data Documentation
Default_it_geom_object_pt
std::map<int,Vector<GeomObject*>>::iterator oomph::AlgebraicNode::Default_it_geom_object_pt [private]
Default iterator for vector of geom objects. These GeomObjects are involved in the default update.
Definition at line 460 of file algebraic_elements.h.
Referenced by all_geom_object_pt(), geom_object_pt(), ngeom_object(), set_default_node_update(), and vector_geom_object_pt().
Default_it_mesh_pt
std::map<int,AlgebraicMesh*>::iterator oomph::AlgebraicNode::Default_it_mesh_pt [private]
Default iterator for mesh: This mesh performs the default update.
Definition at line 456 of file algebraic_elements.h.
Referenced by add_node_update_info(), add_node_update_info(), mesh_pt(), and set_default_node_update().
Default_it_ref_value
std::map<int,Vector<double>>::iterator oomph::AlgebraicNode::Default_it_ref_value [private]
Default iterator for vector of ref values. These reference values are involved in the default update.
Definition at line 464 of file algebraic_elements.h.
Referenced by nref_value(), ref_value(), set_default_node_update(), and vector_ref_value().
Default_node_update_fct_id
int oomph::AlgebraicNode::Default_node_update_fct_id [private]
Default node update function ID.
Definition at line 467 of file algebraic_elements.h.
Referenced by node_update_fct_id(), and set_default_node_update().
Dummy_geom_object_pt
Vector< GeomObject * > oomph::AlgebraicNode::Dummy_geom_object_pt [static], [private]
Default dummy vector of geom objects to point to for nodes for which no remesh fct is defined.
Zero-sized default dummy vector of geom objects to point to for nodes for which no remesh fct is defined.
Definition at line 486 of file algebraic_elements.h.
Referenced by AlgebraicNode(), and AlgebraicNode().
Dummy_mesh
DummyAlgebraicMesh oomph::AlgebraicNode::Dummy_mesh [static], [private]
Static Dummy mesh to which the pointer is addressed.
Set the dummy mesh.
Definition at line 482 of file algebraic_elements.h.
Dummy_mesh_pt
AlgebraicMesh * oomph::AlgebraicNode::Dummy_mesh_pt = &AlgebraicNode::Dummy_mesh [static], [private]
Default dummy mesh to point to for nodes for which no remesh fct is defined.
Definition at line 479 of file algebraic_elements.h.
Referenced by add_node_update_info(), add_node_update_info(), AlgebraicNode(), and AlgebraicNode().
Dummy_node_update_fct_id
int oomph::AlgebraicNode::Dummy_node_update_fct_id = -100 [static], [private]
Default (negative!) remesh fct id for nodes for which no remesh fct is defined.
Definition at line 475 of file algebraic_elements.h.
Referenced by add_node_update_info(), add_node_update_info(), AlgebraicNode(), and AlgebraicNode().
Dummy_ref_value
Vector< double > oomph::AlgebraicNode::Dummy_ref_value [static], [private]
Default dummy vector of reference values to point to for nodes for which no remesh fct is defined.
Zero-sized default dummy vector of reference values to point to for nodes for which no remesh fct is defined.
Definition at line 490 of file algebraic_elements.h.
Referenced by AlgebraicNode(), and AlgebraicNode().
Geom_object_pt
std::map<int, Vector<GeomObject*> > oomph::AlgebraicNode::Geom_object_pt [private]
Vector of geometric objects that are involved in the specified node update operation. (Map because this node may only use the Mesh's 116th node update fct. There's no point in wasting an entire vector for the non-existing entries)
Definition at line 446 of file algebraic_elements.h.
Referenced by add_node_update_info(), add_node_update_info(), kill_node_update_info(), ngeom_object(), set_default_node_update(), and vector_geom_object_pt().
Max_allowed_difference_between_node_update_fcts
double oomph::AlgebraicNode::Max_allowed_difference_between_node_update_fcts [static], [private]
Initial value:
=
    1.0e-10
What it says: Used in self-test to check if different node update functions produce the same result.
Assign default value for test if different node update functions produce the same result.
Definition at line 471 of file algebraic_elements.h.
Referenced by self_test().
Mesh_pt
std::map<int, AlgebraicMesh*> oomph::AlgebraicNode::Mesh_pt [private]
Pointer to mesh that performs the specified node update operation (Map because this node may only use the Mesh's 116th node update fct. There's no point in wasting an entire vector for the non-existing entries)
Definition at line 439 of file algebraic_elements.h.
Referenced by add_node_update_info(), add_node_update_info(), kill_node_update_info(), mesh_pt(), nnode_update_fcts(), node_update(), node_update_fct_id(), and set_default_node_update().
Ref_value
std::map<int, Vector<double> > oomph::AlgebraicNode::Ref_value [private]
Vector of reference values that are required for the specified node update operation. (Map because this node may only use the Mesh's 116th node update fct. There's no point in wasting an entire vector for the non-existing entries)
Definition at line 453 of file algebraic_elements.h.
Referenced by add_node_update_info(), add_node_update_info(), kill_node_update_info(), nref_value(), set_default_node_update(), and vector_ref_value().
The documentation for this class was generated from the following files:
algebraic_elements.h
algebraic_elements.cc