oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT > Class Template Reference
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
#include <fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h>
Public Member Functions
FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement (FiniteElement *const &bulk_el_pt, const int &face_index)
Constructor, takes the pointer to the `bulk` element and the face index identifying the face to which the element is attached.
FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement (const FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement &dummy)=delete
Broken copy constructor.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Broken assignment operator.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and its Jacobian matrix.
void output (std::ostream &outfile)
Output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function: flux etc at Gauss points; n_plot is ignored.
void output (FILE *file_pt)
C-style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function.
Protected Member Functions
double shape_and_test (const Vector< double > &s, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
double shape_and_test_at_knot (const unsigned &ipt, Shape &psi, Shape &test) const
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Private Member Functions
void fill_in_generic_residual_contribution_helmholtz_flux_from_displacement (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the contribution to the Jacobian as well.
Private Attributes
unsigned Dim
The spatial dimension of the problem.
std::complex< unsigned > U_index_helmholtz_from_displacement
The index at which the unknown is stored at the nodes.
Additional Inherited Members
Detailed Description
template<class HELMHOLTZ_BULK_ELEMENT, class ELASTICITY_BULK_ELEMENT>
class oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
A class for elements that allow the imposition of an prescribed flux (determined from the normal displacements of an adjacent linearly elastic solid. Normal derivative for displacement potential is given by normal displacement of adjacent solid multiplies by FSI parameter (q = k^2 B/E). The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
Definition at line 451 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
Constructor & Destructor Documentation
FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement() [1/2]
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement (FiniteElement *const & bulk_el_pt, const int & face_index)
Constructor, takes the pointer to the `bulk` element and the face index identifying the face to which the element is attached.
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
Constructor, takes the pointer to the `bulk` element, and the face index that identifies the face of the bulk element to which this face element is to be attached.
Definition at line 652 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::FiniteElement::build_face_element(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::Dim, oomph::FaceElement::face_index(), oomph::FiniteElement::has_hanging_nodes(), oomph::FiniteElement::nodal_dimension(), oomph::ElementWithExternalElement::set_ninteraction(), oomph::Global_string_for_annotation::string(), and oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::U_index_helmholtz_from_displacement.
FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement() [2/2]
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement (const FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
void oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and its Jacobian matrix.
Reimplemented from oomph::ElementWithExternalElement.
Definition at line 490 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_generic_residual_contribution_helmholtz_flux_from_displacement(), oomph::ElementWithExternalElement::fill_in_jacobian_from_external_interaction_by_fd(), and oomph::FiniteElement::jacobian.
fill_in_contribution_to_residuals()
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
void oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Broken assignment operator.
Add the element's contribution to its residual vector
Reimplemented from oomph::GeneralisedElement.
Definition at line 479 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_generic_residual_contribution_helmholtz_flux_from_displacement().
fill_in_generic_residual_contribution_helmholtz_flux_from_displacement()
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
void oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_generic_residual_contribution_helmholtz_flux_from_displacement (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [private]
Add the element's contribution to its residual vector. flag=1(or 0): do (or don't) compute the contribution to the Jacobian as well.
Helper function to compute the element's residual vector and the Jacobian matrix.
Definition at line 740 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::Multi_domain_functions::Dim, i, s, and oomph::W.
Referenced by oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_contribution_to_residuals().
output() [1/4]
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
void oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output (FILE * file_pt) [inline], [virtual]
C-style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 562 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::CommandLineArgs::output().
output() [2/4]
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
void oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
C-style output function.
Reimplemented from oomph::FiniteElement.
Definition at line 568 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::CommandLineArgs::output().
output() [3/4]
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
void oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output (std::ostream & outfile) [inline], [virtual]
Output function.
Reimplemented from oomph::FiniteElement.
Definition at line 502 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output().
Referenced by oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output().
output() [4/4]
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
void oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function: flux etc at Gauss points; n_plot is ignored.
Reimplemented from oomph::FiniteElement.
Definition at line 510 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::Dim, oomph::ElementWithExternalElement::external_element_local_coord(), oomph::ElementWithExternalElement::external_element_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_zeta(), and oomph::FaceElement::outer_unit_normal().
shape_and_test()
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
double oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test (const Vector< double > & s, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 578 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References i, oomph::FaceElement::J_eulerian(), oomph::FiniteElement::nnode(), s, and oomph::FiniteElement::shape().
shape_and_test_at_knot()
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
double oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test_at_knot (const unsigned & ipt, Shape & psi, Shape & test) const [inline], [protected]
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates.
Definition at line 602 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
References i, oomph::FaceElement::J_eulerian_at_knot(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::shape_at_knot().
Member Data Documentation
Dim
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
unsigned oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::Dim [private]
The spatial dimension of the problem.
Definition at line 633 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
Referenced by oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement(), and oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output().
U_index_helmholtz_from_displacement
template<class HELMHOLTZ_BULK_ELEMENT , class ELASTICITY_BULK_ELEMENT >
std::complex<unsigned> oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::U_index_helmholtz_from_displacement [private]
The index at which the unknown is stored at the nodes.
Definition at line 636 of file fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h.
Referenced by oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement().
The documentation for this class was generated from the following file:
fourier_decomposed_helmholtz_time_harmonic_linear_elasticity_interaction.h