oomph::ODEElement Class Reference
Element for integrating an initial value ODE.
#include <ode_elements.h>
Public Member Functions
ODEElement ()
Default constructor: null any pointers.
ODEElement (TimeStepper *time_stepper_pt, SolutionFunctorBase *exact_solution_pt)
Constructor: Pass time stepper and a solution function pointer, then build the element.
void build (TimeStepper *time_stepper_pt, SolutionFunctorBase *exact_solution_pt)
Store pointers, create internal data.
virtual ~ODEElement ()
unsigned nvalue () const
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
Get residuals.
virtual void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the elemental contribution to the jacobian matrix. and the residuals vector. Note that this function will NOT initialise the residuals vector or the jacobian matrix. It must be called after the residuals vector and jacobian matrix have been initialised to zero. The default is to use finite differences to calculate the jacobian.
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mm)
Add the elemental contribution to the mass matrix matrix. and the residuals vector. Note that this function should NOT initialise the residuals vector or the mass matrix. It must be called after the residuals vector and jacobian matrix have been initialised to zero. The default is deliberately broken.
Vector< double > exact_solution (const double &t) const
Exact solution.
Vector< double > derivative_function (const double &t, const Vector< double > &u)
Exact solution.
Public Attributes
SolutionFunctorBase * Exact_solution_pt
bool Use_fd_jacobian
Additional Inherited Members
Detailed Description
Element for integrating an initial value ODE.
Definition at line 40 of file ode_elements.h.
Constructor & Destructor Documentation
ODEElement() [1/2]
oomph::ODEElement::ODEElement () [inline]
Default constructor: null any pointers.
Definition at line 44 of file ode_elements.h.
References Exact_solution_pt, and Use_fd_jacobian.
ODEElement() [2/2]
oomph::ODEElement::ODEElement (TimeStepper * time_stepper_pt, SolutionFunctorBase * exact_solution_pt) [inline]
Constructor: Pass time stepper and a solution function pointer, then build the element.
Definition at line 53 of file ode_elements.h.
References build().
 ODEElement()
virtual oomph::ODEElement::~ODEElement () [inline], [virtual]
Definition at line 74 of file ode_elements.h.
Member Function Documentation
build()
void oomph::ODEElement::build (TimeStepper * time_stepper_pt, SolutionFunctorBase * exact_solution_pt) [inline]
Store pointers, create internal data.
Definition at line 60 of file ode_elements.h.
References oomph::GeneralisedElement::add_internal_data(), exact_solution(), Exact_solution_pt, nvalue(), and Use_fd_jacobian.
Referenced by ODEElement().
derivative_function()
Vector< double > oomph::ODEElement::derivative_function (const double & t, const Vector< double > & u) [inline]
Exact solution.
Definition at line 166 of file ode_elements.h.
References oomph::SolutionFunctorBase::derivative(), Exact_solution_pt, and t.
Referenced by fill_in_contribution_to_residuals().
exact_solution()
Vector< double > oomph::ODEElement::exact_solution (const double & t) const [inline]
Exact solution.
Definition at line 151 of file ode_elements.h.
References Exact_solution_pt, and t.
Referenced by build().
fill_in_contribution_to_jacobian()
virtual void oomph::ODEElement::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the elemental contribution to the jacobian matrix. and the residuals vector. Note that this function will NOT initialise the residuals vector or the jacobian matrix. It must be called after the residuals vector and jacobian matrix have been initialised to zero. The default is to use finite differences to calculate the jacobian.
Reimplemented from oomph::GeneralisedElement.
Definition at line 109 of file ode_elements.h.
References Exact_solution_pt, fill_in_contribution_to_residuals(), oomph::GeneralisedElement::fill_in_jacobian_from_internal_by_fd(), oomph::SolutionFunctorBase::have_jacobian(), i, oomph::GeneralisedElement::internal_data_pt(), oomph::SolutionFunctorBase::jacobian(), nvalue(), t, oomph::TimeStepper::time(), oomph::Data::time_stepper_pt(), Use_fd_jacobian, oomph::Data::value(), and oomph::TimeStepper::weight().
fill_in_contribution_to_mass_matrix()
virtual void oomph::ODEElement::fill_in_contribution_to_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & mass_matrix) [inline], [virtual]
Add the elemental contribution to the mass matrix matrix. and the residuals vector. Note that this function should NOT initialise the residuals vector or the mass matrix. It must be called after the residuals vector and jacobian matrix have been initialised to zero. The default is deliberately broken.
Add the elemental contribution to the mass matrix and the residuals vector. Note that this function will NOT initialise the residuals vector or the mass matrix. It must be called after the residuals vector and jacobian matrix have been initialised to zero. The default is deliberately broken.
Reimplemented from oomph::GeneralisedElement.
Definition at line 140 of file ode_elements.h.
References fill_in_contribution_to_residuals(), and nvalue().
fill_in_contribution_to_residuals()
virtual void oomph::ODEElement::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Get residuals.
Reimplemented from oomph::GeneralisedElement.
Definition at line 82 of file ode_elements.h.
References derivative_function(), oomph::GeneralisedElement::internal_data_pt(), nvalue(), t, oomph::TimeStepper::time(), oomph::TimeStepper::time_derivative(), oomph::Data::time_stepper_pt(), and oomph::Data::value().
Referenced by fill_in_contribution_to_jacobian(), and fill_in_contribution_to_mass_matrix().
nvalue()
unsigned oomph::ODEElement::nvalue () const [inline]
Definition at line 76 of file ode_elements.h.
References oomph::GeneralisedElement::internal_data_pt(), and oomph::Data::nvalue().
Referenced by build(), fill_in_contribution_to_jacobian(), fill_in_contribution_to_mass_matrix(), and fill_in_contribution_to_residuals().
Member Data Documentation
Exact_solution_pt
SolutionFunctorBase* oomph::ODEElement::Exact_solution_pt
Definition at line 180 of file ode_elements.h.
Referenced by build(), derivative_function(), exact_solution(), fill_in_contribution_to_jacobian(), and ODEElement().
Use_fd_jacobian
bool oomph::ODEElement::Use_fd_jacobian
Definition at line 182 of file ode_elements.h.
Referenced by build(), fill_in_contribution_to_jacobian(), and ODEElement().
The documentation for this class was generated from the following file:
ode_elements.h