oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT > Class Template Reference
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
#include <discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h>
Public Member Functions
ProjectableTaylorHoodSpaceTimeElement ()
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Vector< std::pair< Data *, unsigned > > data_values_of_field (const unsigned &fld)
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld. In the underlying Taylor Hood elements the fld-th velocities are stored at the fld-th value of the nodes; the pressures (the dim-th field) are the dim-th values at the vertex nodes etc.
unsigned nfields_for_projection ()
Number of fields to be projected: dim+1, corresponding to velocity components and pressure.
unsigned nhistory_values_for_projection (const unsigned &fld)
Number of history values to be stored for fld-th field. Whatever the timestepper has set up for the velocity components and none for the pressure field. NOTE: The count includes the current value!
unsigned nhistory_values_for_coordinate_projection ()
Number of positional history values (Note: count includes current value!)
double jacobian_and_shape_of_field (const unsigned &fld, const Vector< double > &s, Shape &psi)
Return the Jacobian of the mapping and the shape functions of field fld at local coordinate s.
double get_field (const unsigned &t, const unsigned &fld, const Vector< double > &s)
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
unsigned nvalue_of_field (const unsigned &fld)
Return number of values in field fld.
int local_equation (const unsigned &fld, const unsigned &j)
Return local equation number of value j in field fld.
ProjectableTaylorHoodSpaceTimeElement ()
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Vector< std::pair< Data *, unsigned > > data_values_of_field (const unsigned &fld)
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld. In the underlying Taylor Hood elements the fld-th velocities are stored at the fld-th value of the nodes; the pressures (the dim-th field) are the dim-th values at the vertex nodes etc.
unsigned nfields_for_projection ()
Number of fields to be projected: dim+1, corresponding to velocity components and pressure.
unsigned nhistory_values_for_projection (const unsigned &fld)
Number of history values to be stored for fld-th field. Whatever the timestepper has set up for the velocity components and none for the pressure field. NOTE: The count includes the current value!
unsigned nhistory_values_for_coordinate_projection ()
Number of positional history values (Note: count includes current value!)
double jacobian_and_shape_of_field (const unsigned &fld, const Vector< double > &s, Shape &psi)
Return the Jacobian of the mapping and the shape functions of field fld at local coordinate s.
double get_field (const unsigned &t, const unsigned &fld, const Vector< double > &s)
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
unsigned nvalue_of_field (const unsigned &fld)
Return number of values in field fld.
int local_equation (const unsigned &fld, const unsigned &j)
Return local equation number of value j in field fld.
ProjectableTaylorHoodSpaceTimeElement ()
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Vector< std::pair< Data *, unsigned > > data_values_of_field (const unsigned &fld)
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld. In the underlying Taylor Hood elements the fld-th velocities are stored at the fld-th value of the nodes; the pressures (the dim-th field) are the dim-th values at the vertex nodes etc.
unsigned nfields_for_projection ()
Number of fields to be projected: dim+1, corresponding to velocity components and pressure.
unsigned nhistory_values_for_projection (const unsigned &fld)
Number of history values to be stored for fld-th field. Whatever the timestepper has set up for the velocity components and none for the pressure field. NOTE: The count includes the current value!
unsigned nhistory_values_for_coordinate_projection ()
Number of positional history values (Note: count includes current value!)
double jacobian_and_shape_of_field (const unsigned &fld, const Vector< double > &s, Shape &psi)
Return the Jacobian of the mapping and the shape functions of field fld at local coordinate s.
double get_field (const unsigned &t, const unsigned &fld, const Vector< double > &s)
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
unsigned nvalue_of_field (const unsigned &fld)
Return number of values in field fld.
int local_equation (const unsigned &fld, const unsigned &j)
Return local equation number of value j in field fld.
Additional Inherited Members
Detailed Description
template<class TAYLOR_HOOD_ELEMENT>
class oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
Taylor Hood upgraded to become projectable
Definition at line 2928 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
Constructor & Destructor Documentation
ProjectableTaylorHoodSpaceTimeElement() [1/3]
template<class TAYLOR_HOOD_ELEMENT >
oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::ProjectableTaylorHoodSpaceTimeElement () [inline]
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Definition at line 2934 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
ProjectableTaylorHoodSpaceTimeElement() [2/3]
template<class TAYLOR_HOOD_ELEMENT >
oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::ProjectableTaylorHoodSpaceTimeElement () [inline]
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Definition at line 2951 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
ProjectableTaylorHoodSpaceTimeElement() [3/3]
template<class TAYLOR_HOOD_ELEMENT >
oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::ProjectableTaylorHoodSpaceTimeElement () [inline]
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Definition at line 2634 of file spacetime_navier_stokes_elements.h.
Member Function Documentation
data_values_of_field() [1/3]
template<class TAYLOR_HOOD_ELEMENT >
Vector< std::pair< Data *, unsigned > > oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::data_values_of_field (const unsigned & fld) [inline], [virtual]
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld. In the underlying Taylor Hood elements the fld-th velocities are stored at the fld-th value of the nodes; the pressures (the dim-th field) are the dim-th values at the vertex nodes etc.
Implements oomph::ProjectableElementBase.
Definition at line 2943 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
data_values_of_field() [2/3]
template<class TAYLOR_HOOD_ELEMENT >
Vector< std::pair< Data *, unsigned > > oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::data_values_of_field (const unsigned & fld) [inline], [virtual]
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld. In the underlying Taylor Hood elements the fld-th velocities are stored at the fld-th value of the nodes; the pressures (the dim-th field) are the dim-th values at the vertex nodes etc.
Implements oomph::ProjectableElementBase.
Definition at line 2960 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
data_values_of_field() [3/3]
template<class TAYLOR_HOOD_ELEMENT >
Vector< std::pair< Data *, unsigned > > oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::data_values_of_field (const unsigned & fld) [inline], [virtual]
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld. In the underlying Taylor Hood elements the fld-th velocities are stored at the fld-th value of the nodes; the pressures (the dim-th field) are the dim-th values at the vertex nodes etc.
Implements oomph::ProjectableElementBase.
Definition at line 2642 of file spacetime_navier_stokes_elements.h.
get_field() [1/3]
template<class TAYLOR_HOOD_ELEMENT >
double oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::get_field (const unsigned & t, const unsigned & fld, const Vector< double > & s) [inline], [virtual]
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
Implements oomph::ProjectableElementBase.
Definition at line 3084 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References s, oomph::OneDimLagrange::shape(), and t.
get_field() [2/3]
template<class TAYLOR_HOOD_ELEMENT >
double oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::get_field (const unsigned & t, const unsigned & fld, const Vector< double > & s) [inline], [virtual]
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
Implements oomph::ProjectableElementBase.
Definition at line 3101 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References s, oomph::OneDimLagrange::shape(), and t.
get_field() [3/3]
template<class TAYLOR_HOOD_ELEMENT >
double oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::get_field (const unsigned & t, const unsigned & fld, const Vector< double > & s) [inline], [virtual]
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
Implements oomph::ProjectableElementBase.
Definition at line 2783 of file spacetime_navier_stokes_elements.h.
References s, oomph::OneDimLagrange::shape(), and t.
jacobian_and_shape_of_field() [1/3]
template<class TAYLOR_HOOD_ELEMENT >
double oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::jacobian_and_shape_of_field (const unsigned & fld, const Vector< double > & s, Shape & psi) [inline], [virtual]
Return the Jacobian of the mapping and the shape functions of field fld at local coordinate s.
Implements oomph::ProjectableElementBase.
Definition at line 3025 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
References s.
jacobian_and_shape_of_field() [2/3]
template<class TAYLOR_HOOD_ELEMENT >
double oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::jacobian_and_shape_of_field (const unsigned & fld, const Vector< double > & s, Shape & psi) [inline], [virtual]
Return the Jacobian of the mapping and the shape functions of field fld at local coordinate s.
Implements oomph::ProjectableElementBase.
Definition at line 3042 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
References s.
jacobian_and_shape_of_field() [3/3]
template<class TAYLOR_HOOD_ELEMENT >
double oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::jacobian_and_shape_of_field (const unsigned & fld, const Vector< double > & s, Shape & psi) [inline], [virtual]
Return the Jacobian of the mapping and the shape functions of field fld at local coordinate s.
Implements oomph::ProjectableElementBase.
Definition at line 2724 of file spacetime_navier_stokes_elements.h.
References s.
local_equation() [1/3]
template<class TAYLOR_HOOD_ELEMENT >
int oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::local_equation (const unsigned & fld, const unsigned & j) [inline], [virtual]
Return local equation number of value j in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 3136 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
local_equation() [2/3]
template<class TAYLOR_HOOD_ELEMENT >
int oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::local_equation (const unsigned & fld, const unsigned & j) [inline], [virtual]
Return local equation number of value j in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 3153 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
local_equation() [3/3]
template<class TAYLOR_HOOD_ELEMENT >
int oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::local_equation (const unsigned & fld, const unsigned & j) [inline], [virtual]
Return local equation number of value j in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 2835 of file spacetime_navier_stokes_elements.h.
nfields_for_projection() [1/3]
template<class TAYLOR_HOOD_ELEMENT >
unsigned oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::nfields_for_projection () [inline], [virtual]
Number of fields to be projected: dim+1, corresponding to velocity components and pressure.
Implements oomph::ProjectableElementBase.
Definition at line 2987 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
nfields_for_projection() [2/3]
template<class TAYLOR_HOOD_ELEMENT >
unsigned oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::nfields_for_projection () [inline], [virtual]
Number of fields to be projected: dim+1, corresponding to velocity components and pressure.
Implements oomph::ProjectableElementBase.
Definition at line 3004 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
nfields_for_projection() [3/3]
template<class TAYLOR_HOOD_ELEMENT >
unsigned oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::nfields_for_projection () [inline], [virtual]
Number of fields to be projected: dim+1, corresponding to velocity components and pressure.
Implements oomph::ProjectableElementBase.
Definition at line 2686 of file spacetime_navier_stokes_elements.h.
nhistory_values_for_coordinate_projection() [1/3]
template<class TAYLOR_HOOD_ELEMENT >
unsigned oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::nhistory_values_for_coordinate_projection () [inline], [virtual]
Number of positional history values (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 3016 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
nhistory_values_for_coordinate_projection() [2/3]
template<class TAYLOR_HOOD_ELEMENT >
unsigned oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::nhistory_values_for_coordinate_projection () [inline], [virtual]
Number of positional history values (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 3033 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
nhistory_values_for_coordinate_projection() [3/3]
template<class TAYLOR_HOOD_ELEMENT >
unsigned oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::nhistory_values_for_coordinate_projection () [inline], [virtual]
Number of positional history values (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 2715 of file spacetime_navier_stokes_elements.h.
nhistory_values_for_projection() [1/3]
template<class TAYLOR_HOOD_ELEMENT >
unsigned oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::nhistory_values_for_projection (const unsigned & fld) [inline], [virtual]
Number of history values to be stored for fld-th field. Whatever the timestepper has set up for the velocity components and none for the pressure field. NOTE: The count includes the current value!
Implements oomph::ProjectableElementBase.
Definition at line 2997 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
nhistory_values_for_projection() [2/3]
template<class TAYLOR_HOOD_ELEMENT >
unsigned oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::nhistory_values_for_projection (const unsigned & fld) [inline], [virtual]
Number of history values to be stored for fld-th field. Whatever the timestepper has set up for the velocity components and none for the pressure field. NOTE: The count includes the current value!
Implements oomph::ProjectableElementBase.
Definition at line 3014 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
nhistory_values_for_projection() [3/3]
template<class TAYLOR_HOOD_ELEMENT >
unsigned oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::nhistory_values_for_projection (const unsigned & fld) [inline], [virtual]
Number of history values to be stored for fld-th field. Whatever the timestepper has set up for the velocity components and none for the pressure field. NOTE: The count includes the current value!
Implements oomph::ProjectableElementBase.
Definition at line 2696 of file spacetime_navier_stokes_elements.h.
nvalue_of_field() [1/3]
template<class TAYLOR_HOOD_ELEMENT >
unsigned oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::nvalue_of_field (const unsigned & fld) [inline], [virtual]
Return number of values in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 3122 of file discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h.
nvalue_of_field() [2/3]
template<class TAYLOR_HOOD_ELEMENT >
unsigned oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::nvalue_of_field (const unsigned & fld) [inline], [virtual]
Return number of values in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 3139 of file discontinuous_galerkin_spacetime_navier_stokes_elements.h.
nvalue_of_field() [3/3]
template<class TAYLOR_HOOD_ELEMENT >
unsigned oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::nvalue_of_field (const unsigned & fld) [inline], [virtual]
Return number of values in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 2821 of file spacetime_navier_stokes_elements.h.
The documentation for this class was generated from the following files:
discontinuous_galerkin_equal_order_pressure_spacetime_navier_stokes_elements.h
discontinuous_galerkin_spacetime_navier_stokes_elements.h
spacetime_navier_stokes_elements.h