oomph::AxisymDiagHermitePVDElement Class Reference
An element that solved the AxisymmetricPVDEquations with (diagonal) Hermite interpolation for the positions -- the local and global (Lagrangian) coordinates are assumed to be aligned!
#include <axisym_solid_elements.h>
Public Member Functions
AxisymDiagHermitePVDElement ()
Constructor, there are no internal data points.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
void output (FILE *file_pt)
Overload the output function.
void output (FILE *file_pt, const unsigned &n_plot)
Output function.
Additional Inherited Members
Detailed Description
An element that solved the AxisymmetricPVDEquations with (diagonal) Hermite interpolation for the positions -- the local and global (Lagrangian) coordinates are assumed to be aligned!
Definition at line 544 of file axisym_solid_elements.h.
Constructor & Destructor Documentation
AxisymDiagHermitePVDElement()
oomph::AxisymDiagHermitePVDElement::AxisymDiagHermitePVDElement () [inline]
Constructor, there are no internal data points.
Definition at line 549 of file axisym_solid_elements.h.
Member Function Documentation
output() [1/4]
void oomph::AxisymDiagHermitePVDElement::output (FILE * file_pt) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::AxisymmetricPVDEquations.
Definition at line 596 of file axisym_solid_elements.h.
References oomph::FiniteElement::output().
output() [2/4]
void oomph::AxisymDiagHermitePVDElement::output (FILE * file_pt, const unsigned & n_plot) [inline], [virtual]
Output function.
Reimplemented from oomph::AxisymmetricPVDEquations.
Definition at line 603 of file axisym_solid_elements.h.
References i, oomph::FiniteElement::interpolated_x(), oomph::SolidFiniteElement::interpolated_xi(), and s.
output() [3/4]
void oomph::AxisymDiagHermitePVDElement::output (std::ostream & outfile) [inline], [virtual]
Overload the output function.
Reimplemented from oomph::AxisymmetricPVDEquations.
Definition at line 555 of file axisym_solid_elements.h.
References oomph::FiniteElement::output().
output() [4/4]
void oomph::AxisymDiagHermitePVDElement::output (std::ostream & outfile, const unsigned & n_plot) [inline], [virtual]
Output function.
Reimplemented from oomph::AxisymmetricPVDEquations.
Definition at line 561 of file axisym_solid_elements.h.
References i, oomph::FiniteElement::interpolated_x(), oomph::SolidFiniteElement::interpolated_xi(), and s.
The documentation for this class was generated from the following file:
axisym_solid_elements.h