oomph::PMLHelmholtzEquations< DIM > Class Template Reference
A class for all isoparametric elements that solve the Helmholtz equations with pml capabilities. This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
#include <pml_helmholtz_elements.h>
Public Types
typedef void(* PMLHelmholtzSourceFctPt) (const Vector< double > &x, std::complex< double > &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
Public Member Functions
PMLHelmholtzEquations ()
Constructor.
PMLHelmholtzEquations (const PMLHelmholtzEquations &dummy)=delete
Broken copy constructor.
virtual std::complex< unsigned > u_index_helmholtz () const
Broken assignment operator.
double *& k_squared_pt ()
Get pointer to k_squared.
double k_squared ()
Get the square of wavenumber.
const double & alpha () const
Alpha, wavenumber complex shift.
double *& alpha_pt ()
Pointer to Alpha, wavenumber complex shift.
unsigned nscalar_paraview () const
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
std::string scalar_name_paraview (const unsigned &i) const
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &n_plot)
Output FE representation of soln: x,y,u_re,u_im or x,y,z,u_re,u_im at n_plot^DIM plot points.
void output_total_real (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt incoming_wave_fct_pt, const double &phi, const unsigned &nplot)
Output function for real part of full time-dependent solution constructed by adding the scattered field u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi computed here, to the corresponding incoming wave specified via the function pointer.
void output_real (std::ostream &outfile, const double &phi, const unsigned &n_plot)
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
void output_imag (std::ostream &outfile, const double &phi, const unsigned &n_plot)
Output function for imaginary part of full time-dependent solution u = Im((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output FE representation of soln: x,y,u_re,u_im or x,y,z,u_re,u_im at n_plot^DIM plot points.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_re_exact,u_im_exact or x,y,z,u_re_exact,u_im_exact at n_plot^DIM plot points.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: (dummy time-dependent version to keep intel compiler happy)
void output_real_fct (std::ostream &outfile, const double &phi, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for real part of full time-dependent fct u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
void output_imag_fct (std::ostream &outfile, const double &phi, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for imaginary part of full time-dependent fct u = Im((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
void compute_norm (double &norm)
Compute norm of fe solution.
PMLHelmholtzSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
PMLHelmholtzSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
virtual void get_source_helmholtz (const unsigned &ipt, const Vector< double > &x, std::complex< double > &source) const
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
void values_to_be_pinned_on_outer_pml_boundary (Vector< unsigned > &values_to_pin)
Pure virtual function in which we specify the values to be pinned (and set to zero) on the outer edge of the pml layer. All of them! Vector is resized internally.
void get_flux (const Vector< double > &s, Vector< std::complex< double > > &flux) const
Get flux: flux[i] = du/dx_i for real and imag part.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Add the element's contribution to its residual vector and element Jacobian matrix (wrapper)
std::complex< double > interpolated_u_pml_helmholtz (const Vector< double > &s) const
Return FE representation of function value u_helmholtz(s) at local coordinate s.
unsigned self_test ()
Self-test: Return 0 for OK.
void compute_pml_coefficients (const unsigned &ipt, const Vector< double > &x, Vector< std::complex< double > > &pml_laplace_factor, std::complex< double > &pml_k_squared_factor)
Compute pml coefficients at position x and integration point ipt. pml_laplace_factor is used in the residual contribution from the laplace operator, similarly pml_k_squared_factor is used in the contribution from the k^2 of the Helmholtz operator.
PMLMapping *& pml_mapping_pt ()
Return a pointer to the PML Mapping object.
PMLMapping *const & pml_mapping_pt () const
Return a pointer to the PML Mapping object (const version)
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into: real and imaginary part.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Real=0; Imag=1.
Static Public Attributes
static BermudezPMLMapping Default_pml_mapping
Static so that the class doesn't need to instantiate a new default everytime it uses it.
Protected Member Functions
virtual double dshape_and_dtest_eulerian_helmholtz (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
virtual double dshape_and_dtest_eulerian_at_knot_helmholtz (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
virtual void fill_in_generic_residual_contribution_helmholtz (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Protected Attributes
double * Alpha_pt
Pointer to wavenumber complex shift.
PMLHelmholtzSourceFctPt Source_fct_pt
Pointer to source function:
double * K_squared_pt
Pointer to wave number (must be set!)
PMLMapping * Pml_mapping_pt
Pointer to class which holds the pml mapping function, also known as gamma.
Static Protected Attributes
static double Default_Physical_Constant_Value
Static default value for the physical constants (initialised to zero)
Detailed Description
template<unsigned DIM>
class oomph::PMLHelmholtzEquations< DIM >
A class for all isoparametric elements that solve the Helmholtz equations with pml capabilities. This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
Definition at line 60 of file pml_helmholtz_elements.h.
Member Typedef Documentation
PMLHelmholtzSourceFctPt
template<unsigned DIM>
typedef void(* oomph::PMLHelmholtzEquations< DIM >::PMLHelmholtzSourceFctPt) (const Vector< double > &x, std::complex< double > &f)
Function pointer to source function fct(x,f(x)) -- x is a Vector!
Definition at line 66 of file pml_helmholtz_elements.h.
Constructor & Destructor Documentation
PMLHelmholtzEquations() [1/2]
template<unsigned DIM>
oomph::PMLHelmholtzEquations< DIM >::PMLHelmholtzEquations () [inline]
Constructor.
Definition at line 70 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::Alpha_pt, oomph::PMLHelmholtzEquations< DIM >::Default_Physical_Constant_Value, oomph::PMLHelmholtzEquations< DIM >::Default_pml_mapping, and oomph::PMLHelmholtzEquations< DIM >::Pml_mapping_pt.
PMLHelmholtzEquations() [2/2]
template<unsigned DIM>
oomph::PMLHelmholtzEquations< DIM >::PMLHelmholtzEquations (const PMLHelmholtzEquations< DIM > & dummy) [delete]
Broken copy constructor.
Member Function Documentation
alpha()
template<unsigned DIM>
const double & oomph::PMLHelmholtzEquations< DIM >::alpha () const [inline]
Alpha, wavenumber complex shift.
Definition at line 119 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::Alpha_pt.
Referenced by oomph::PMLHelmholtzEquations< DIM >::compute_pml_coefficients().
alpha_pt()
template<unsigned DIM>
double *& oomph::PMLHelmholtzEquations< DIM >::alpha_pt () [inline]
Pointer to Alpha, wavenumber complex shift.
Definition at line 125 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::Alpha_pt.
Referenced by oomph::HelmholtzMGPreconditioner< DIM >::setup_mg_structures().
compute_error() [1/2]
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) [virtual]
Get error against and norm of exact solution.
Validate against exact solution.
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 728 of file pml_helmholtz_elements.cc.
References i, s, oomph::W, and oomph::x.
compute_error() [2/2]
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) [inline], [virtual]
Dummy, time dependent error checker.
Reimplemented from oomph::FiniteElement.
Definition at line 383 of file pml_helmholtz_elements.h.
compute_norm()
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::compute_norm (double & norm) [virtual]
Compute norm of fe solution.
Reimplemented from oomph::GeneralisedElement.
Definition at line 808 of file pml_helmholtz_elements.cc.
References i, s, oomph::W, and oomph::x.
compute_pml_coefficients()
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::compute_pml_coefficients (const unsigned & ipt, const Vector< double > & x, Vector< std::complex< double > > & pml_laplace_factor, std::complex< double > & pml_k_squared_factor) [inline]
Compute pml coefficients at position x and integration point ipt. pml_laplace_factor is used in the residual contribution from the laplace operator, similarly pml_k_squared_factor is used in the contribution from the k^2 of the Helmholtz operator.
Vector which points from the inner boundary to x
Vector which points from the inner boundary to the edge of the boundary
for 2D, in order: g_y/g_x, g_x/g_y for Laplace bit and g_x*g_y for Helmholtz bit for 3D, in order: g_y*g_x/g_x, g*x*g_z/g_y, g_x*g_y/g_z for Laplace bit and g_x*g_y*g_z for Helmholtz bit
The weights all default to 1.0 as if the propagation medium is the physical domain
Definition at line 546 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::alpha(), oomph::PMLMapping::gamma(), oomph::PMLHelmholtzEquations< DIM >::k_squared(), oomph::PMLElementBase< DIM >::Pml_direction_active, oomph::PMLElementBase< DIM >::Pml_inner_boundary, oomph::PMLElementBase< DIM >::Pml_is_enabled, oomph::PMLHelmholtzEquations< DIM >::Pml_mapping_pt, oomph::PMLElementBase< DIM >::Pml_outer_boundary, and oomph::x.
dshape_and_dtest_eulerian_at_knot_helmholtz()
template<unsigned DIM>
virtual double oomph::PMLHelmholtzEquations< DIM >::dshape_and_dtest_eulerian_at_knot_helmholtz (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping.
Implemented in oomph::QPMLHelmholtzElement< DIM, NNODE_1D >, oomph::QPMLHelmholtzElement< 2, NNODE_1D >, and oomph::TPMLHelmholtzElement< DIM, NNODE_1D >.
dshape_and_dtest_eulerian_helmholtz()
template<unsigned DIM>
virtual double oomph::PMLHelmholtzEquations< DIM >::dshape_and_dtest_eulerian_helmholtz (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const [protected], [pure virtual]
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping.
Implemented in oomph::QPMLHelmholtzElement< DIM, NNODE_1D >, oomph::QPMLHelmholtzElement< 2, NNODE_1D >, and oomph::TPMLHelmholtzElement< DIM, NNODE_1D >.
fill_in_contribution_to_jacobian()
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) [inline], [virtual]
Add the element's contribution to its residual vector and element Jacobian matrix (wrapper)
Reimplemented from oomph::FiniteElement.
Definition at line 495 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), and oomph::FiniteElement::jacobian.
fill_in_contribution_to_residuals()
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) [inline], [virtual]
Add the element's contribution to its residual vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
Definition at line 484 of file pml_helmholtz_elements.h.
References oomph::GeneralisedElement::Dummy_matrix, and oomph::PMLHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz().
fill_in_generic_residual_contribution_helmholtz()
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) [protected], [virtual]
Compute element residual Vector only (if flag=and/or element Jacobian matrix.
Compute element residual Vector and/or element Jacobian matrix.
flag=1: compute both flag=0: compute only residual Vector
Pure version without hanging nodes
Reimplemented in oomph::RefineablePMLHelmholtzEquations< DIM >.
Definition at line 55 of file pml_helmholtz_elements.cc.
References i, and oomph::W.
Referenced by oomph::PMLHelmholtzEquations< DIM >::fill_in_contribution_to_jacobian(), and oomph::PMLHelmholtzEquations< DIM >::fill_in_contribution_to_residuals().
get_dof_numbers_for_unknowns()
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [inline], [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) Real=0; Imag=1.
Reimplemented from oomph::GeneralisedElement.
Definition at line 650 of file pml_helmholtz_elements.h.
References oomph::GeneralisedElement::eqn_number(), oomph::GeneralisedElement::local_eqn_number(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), and oomph::PMLHelmholtzEquations< DIM >::u_index_helmholtz().
get_flux()
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::get_flux (const Vector< double > & s, Vector< std::complex< double > > & flux) const [inline]
Get flux: flux[i] = du/dx_i for real and imag part.
Definition at line 446 of file pml_helmholtz_elements.h.
References oomph::FiniteElement::dshape_eulerian(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, and oomph::PMLHelmholtzEquations< DIM >::u_index_helmholtz().
Referenced by oomph::RefineablePMLHelmholtzEquations< DIM >::get_Z2_flux(), and oomph::TPMLHelmholtzElement< DIM, NNODE_1D >::get_Z2_flux().
get_source_helmholtz()
template<unsigned DIM>
virtual void oomph::PMLHelmholtzEquations< DIM >::get_source_helmholtz (const unsigned & ipt, const Vector< double > & x, std::complex< double > & source) const [inline], [virtual]
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
Definition at line 416 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::Source_fct_pt, and oomph::x.
interpolated_u_pml_helmholtz()
template<unsigned DIM>
std::complex< double > oomph::PMLHelmholtzEquations< DIM >::interpolated_u_pml_helmholtz (const Vector< double > & s) const [inline]
Return FE representation of function value u_helmholtz(s) at local coordinate s.
Definition at line 505 of file pml_helmholtz_elements.h.
References oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and oomph::PMLHelmholtzEquations< DIM >::u_index_helmholtz().
Referenced by oomph::PMLHelmholtzEquations< DIM >::scalar_value_paraview().
k_squared()
template<unsigned DIM>
double oomph::PMLHelmholtzEquations< DIM >::k_squared () [inline]
Get the square of wavenumber.
Definition at line 104 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::K_squared_pt.
Referenced by oomph::PMLHelmholtzEquations< DIM >::compute_pml_coefficients(), and oomph::HelmholtzMGPreconditioner< DIM >::setup_mg_structures().
k_squared_pt()
template<unsigned DIM>
double *& oomph::PMLHelmholtzEquations< DIM >::k_squared_pt () [inline]
Get pointer to k_squared.
Definition at line 97 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::K_squared_pt.
ndof_types()
template<unsigned DIM>
unsigned oomph::PMLHelmholtzEquations< DIM >::ndof_types () const [inline], [virtual]
The number of `DOF types` that degrees of freedom in this element are sub-divided into: real and imaginary part.
Reimplemented from oomph::GeneralisedElement.
Definition at line 639 of file pml_helmholtz_elements.h.
nscalar_paraview()
template<unsigned DIM>
unsigned oomph::PMLHelmholtzEquations< DIM >::nscalar_paraview () const [inline], [virtual]
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
Reimplemented from oomph::FiniteElement.
Definition at line 133 of file pml_helmholtz_elements.h.
output() [1/4]
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::output (FILE * file_pt) [inline], [virtual]
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLHelmholtzElement< DIM, NNODE_1D >, oomph::QPMLHelmholtzElement< 2, NNODE_1D >, and oomph::TPMLHelmholtzElement< DIM, NNODE_1D >.
Definition at line 323 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::output().
output() [2/4]
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::output (FILE * file_pt, const unsigned & nplot) [virtual]
C-style output FE representation of soln: x,y,u_re,u_im or x,y,z,u_re,u_im at n_plot^DIM plot points.
C-style output function:
x,y,u or x,y,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLHelmholtzElement< DIM, NNODE_1D >, oomph::QPMLHelmholtzElement< 2, NNODE_1D >, and oomph::TPMLHelmholtzElement< DIM, NNODE_1D >.
Definition at line 521 of file pml_helmholtz_elements.cc.
References i, s, and oomph::u.
output() [3/4]
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::output (std::ostream & outfile) [inline], [virtual]
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLHelmholtzElement< DIM, NNODE_1D >, oomph::QPMLHelmholtzElement< 2, NNODE_1D >, and oomph::TPMLHelmholtzElement< DIM, NNODE_1D >.
Definition at line 282 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::output().
Referenced by oomph::PMLHelmholtzEquations< DIM >::output(), oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::output(), and oomph::TPMLHelmholtzElement< DIM, NNODE_1D >::output().
output() [4/4]
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::output (std::ostream & outfile, const unsigned & nplot) [virtual]
Output FE representation of soln: x,y,u_re,u_im or x,y,z,u_re,u_im at n_plot^DIM plot points.
Output function:
x,y,u_re,u_imag or x,y,z,u_re,u_imag
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLHelmholtzElement< DIM, NNODE_1D >, oomph::QPMLHelmholtzElement< 2, NNODE_1D >, and oomph::TPMLHelmholtzElement< DIM, NNODE_1D >.
Definition at line 344 of file pml_helmholtz_elements.cc.
References i, s, and oomph::u.
output_fct() [1/2]
template<unsigned DIM>
virtual void oomph::PMLHelmholtzEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) [inline], [virtual]
Output exact soln: (dummy time-dependent version to keep intel compiler happy)
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLHelmholtzElement< DIM, NNODE_1D >, oomph::QPMLHelmholtzElement< 2, NNODE_1D >, and oomph::TPMLHelmholtzElement< DIM, NNODE_1D >.
Definition at line 341 of file pml_helmholtz_elements.h.
output_fct() [2/2]
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) [virtual]
Output exact soln: x,y,u_re_exact,u_im_exact or x,y,z,u_re_exact,u_im_exact at n_plot^DIM plot points.
Output exact solution.
Solution is provided via function pointer. Plot at a given number of plot points.
x,y,u_exact or x,y,z,u_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QPMLHelmholtzElement< DIM, NNODE_1D >, oomph::QPMLHelmholtzElement< 2, NNODE_1D >, and oomph::TPMLHelmholtzElement< DIM, NNODE_1D >.
Definition at line 564 of file pml_helmholtz_elements.cc.
References i, s, and oomph::x.
Referenced by oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::output_fct(), and oomph::TPMLHelmholtzElement< DIM, NNODE_1D >::output_fct().
output_imag()
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::output_imag (std::ostream & outfile, const double & phi, const unsigned & nplot)
Output function for imaginary part of full time-dependent solution u = Im((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
Output function for imaginary part of full time-dependent solution.
u = Im((u_r +i u_i) exp(-i omega t))
at phase angle omega t = phi.
x,y,u or x,y,z,u
Output at nplot points in each coordinate direction
Definition at line 484 of file pml_helmholtz_elements.cc.
References i, s, and oomph::u.
Referenced by oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::output_imag().
output_imag_fct()
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::output_imag_fct (std::ostream & outfile, const double & phi, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for imaginary part of full time-dependent fct u = Im((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
Output function for imaginary part of full time-dependent fct.
u = Im((u_r +i u_i) exp(-i omega t))
at phase angle omega t = phi.
x,y,u or x,y,z,u
Output at nplot points in each coordinate direction
Definition at line 675 of file pml_helmholtz_elements.cc.
References i, s, and oomph::x.
Referenced by oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::output_imag_fct().
output_real()
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::output_real (std::ostream & outfile, const double & phi, const unsigned & nplot)
Output function for real part of full time-dependent solution u = Re((u_r +i u_i) exp(-i omega t)) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
Output function for real part of full time-dependent solution.
u = Re((u_r +i u_i) exp(-i omega t)
at phase angle omega t = phi.
x,y,u or x,y,z,u
Output at nplot points in each coordinate direction
Definition at line 384 of file pml_helmholtz_elements.cc.
References i, s, and oomph::u.
Referenced by oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::output_real().
output_real_fct()
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::output_real_fct (std::ostream & outfile, const double & phi, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for real part of full time-dependent fct u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi. x,y,u or x,y,z,u at n_plot plot points in each coordinate direction.
Output function for real part of full time-dependent fct.
u = Re((u_r +i u_i) exp(-i omega t)
at phase angle omega t = phi.
x,y,u or x,y,z,u
Output at nplot points in each coordinate direction
Definition at line 619 of file pml_helmholtz_elements.cc.
References i, s, and oomph::x.
Referenced by oomph::QPMLHelmholtzElement< DIM, NNODE_1D >::output_real_fct().
output_total_real()
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::output_total_real (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt incoming_wave_fct_pt, const double & phi, const unsigned & nplot)
Output function for real part of full time-dependent solution constructed by adding the scattered field u = Re((u_r +i u_i) exp(-i omega t) at phase angle omega t = phi computed here, to the corresponding incoming wave specified via the function pointer.
Output function for real part of full time-dependent solution constructed by adding the scattered field.
u = Re((u_r +i u_i) exp(-i omega t)
at phase angle omega t = phi computed here, to the corresponding incoming wave specified via the function pointer.
x,y,u or x,y,z,u
Output at nplot points in each coordinate direction
Definition at line 426 of file pml_helmholtz_elements.cc.
References i, s, oomph::u, and oomph::x.
pml_mapping_pt() [1/2]
template<unsigned DIM>
PMLMapping *& oomph::PMLHelmholtzEquations< DIM >::pml_mapping_pt () [inline]
Return a pointer to the PML Mapping object.
Definition at line 622 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::Pml_mapping_pt.
pml_mapping_pt() [2/2]
template<unsigned DIM>
PMLMapping *const & oomph::PMLHelmholtzEquations< DIM >::pml_mapping_pt () const [inline]
Return a pointer to the PML Mapping object (const version)
Definition at line 628 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::Pml_mapping_pt.
scalar_name_paraview()
template<unsigned DIM>
std::string oomph::PMLHelmholtzEquations< DIM >::scalar_name_paraview (const unsigned & i) const [inline], [virtual]
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
Reimplemented from oomph::FiniteElement.
Definition at line 250 of file pml_helmholtz_elements.h.
References i.
scalar_value_fct_paraview()
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::scalar_value_fct_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const [inline], [virtual]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
Definition at line 188 of file pml_helmholtz_elements.h.
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points_paraview(), s, and oomph::x.
scalar_value_paraview()
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const [inline], [virtual]
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
Definition at line 140 of file pml_helmholtz_elements.h.
References oomph::FiniteElement::get_s_plot(), i, oomph::PMLHelmholtzEquations< DIM >::interpolated_u_pml_helmholtz(), oomph::FiniteElement::nplot_points_paraview(), s, and oomph::u.
self_test()
template<unsigned DIM>
unsigned oomph::PMLHelmholtzEquations< DIM >::self_test [virtual]
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
Definition at line 314 of file pml_helmholtz_elements.cc.
References oomph::FiniteElement::self_test().
source_fct_pt() [1/2]
template<unsigned DIM>
PMLHelmholtzSourceFctPt & oomph::PMLHelmholtzEquations< DIM >::source_fct_pt () [inline]
Access function: Pointer to source function.
Definition at line 400 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::Source_fct_pt.
Referenced by oomph::RefineablePMLHelmholtzEquations< DIM >::further_build().
source_fct_pt() [2/2]
template<unsigned DIM>
PMLHelmholtzSourceFctPt oomph::PMLHelmholtzEquations< DIM >::source_fct_pt () const [inline]
Access function: Pointer to source function. Const version.
Definition at line 406 of file pml_helmholtz_elements.h.
References oomph::PMLHelmholtzEquations< DIM >::Source_fct_pt.
u_index_helmholtz()
template<unsigned DIM>
virtual std::complex< unsigned > oomph::PMLHelmholtzEquations< DIM >::u_index_helmholtz () const [inline], [virtual]
Broken assignment operator.
Return the index at which the unknown value is stored.
Definition at line 91 of file pml_helmholtz_elements.h.
Referenced by oomph::PMLHelmholtzEquations< DIM >::get_dof_numbers_for_unknowns(), oomph::PMLHelmholtzEquations< DIM >::get_flux(), oomph::RefineablePMLHelmholtzEquations< DIM >::get_interpolated_values(), oomph::PMLHelmholtzEquations< DIM >::interpolated_u_pml_helmholtz(), oomph::PMLHelmholtzFluxElement< ELEMENT >::PMLHelmholtzFluxElement(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::PMLHelmholtzFluxFromNormalDisplacementBCElement(), and oomph::PMLHelmholtzPowerElement< ELEMENT >::PMLHelmholtzPowerElement().
values_to_be_pinned_on_outer_pml_boundary()
template<unsigned DIM>
void oomph::PMLHelmholtzEquations< DIM >::values_to_be_pinned_on_outer_pml_boundary (Vector< unsigned > & values_to_pin) [inline], [virtual]
Pure virtual function in which we specify the values to be pinned (and set to zero) on the outer edge of the pml layer. All of them! Vector is resized internally.
Implements oomph::PMLElementBase< DIM >.
Definition at line 435 of file pml_helmholtz_elements.h.
Member Data Documentation
Alpha_pt
template<unsigned DIM>
double* oomph::PMLHelmholtzEquations< DIM >::Alpha_pt [protected]
Pointer to wavenumber complex shift.
Definition at line 724 of file pml_helmholtz_elements.h.
Referenced by oomph::PMLHelmholtzEquations< DIM >::alpha(), oomph::PMLHelmholtzEquations< DIM >::alpha_pt(), and oomph::PMLHelmholtzEquations< DIM >::PMLHelmholtzEquations().
Default_Physical_Constant_Value
template<unsigned DIM>
double oomph::PMLHelmholtzEquations< DIM >::Default_Physical_Constant_Value [static], [protected]
Initial value:
=
    0.0
Static default value for the physical constants (initialised to zero)
PML Helmholtz equations static data, so that by default we can point to a 0.
Definition at line 737 of file pml_helmholtz_elements.h.
Referenced by oomph::PMLHelmholtzEquations< DIM >::PMLHelmholtzEquations().
Default_pml_mapping
template<unsigned DIM>
BermudezPMLMapping oomph::PMLHelmholtzEquations< DIM >::Default_pml_mapping [static]
Static so that the class doesn't need to instantiate a new default everytime it uses it.
Definition at line 635 of file pml_helmholtz_elements.h.
Referenced by oomph::PMLHelmholtzEquations< DIM >::PMLHelmholtzEquations().
K_squared_pt
template<unsigned DIM>
double* oomph::PMLHelmholtzEquations< DIM >::K_squared_pt [protected]
Pointer to wave number (must be set!)
Definition at line 730 of file pml_helmholtz_elements.h.
Referenced by oomph::PMLHelmholtzEquations< DIM >::k_squared(), and oomph::PMLHelmholtzEquations< DIM >::k_squared_pt().
Pml_mapping_pt
template<unsigned DIM>
PMLMapping* oomph::PMLHelmholtzEquations< DIM >::Pml_mapping_pt [protected]
Pointer to class which holds the pml mapping function, also known as gamma.
Definition at line 734 of file pml_helmholtz_elements.h.
Referenced by oomph::PMLHelmholtzEquations< DIM >::compute_pml_coefficients(), oomph::PMLHelmholtzEquations< DIM >::pml_mapping_pt(), and oomph::PMLHelmholtzEquations< DIM >::PMLHelmholtzEquations().
Source_fct_pt
template<unsigned DIM>
PMLHelmholtzSourceFctPt oomph::PMLHelmholtzEquations< DIM >::Source_fct_pt [protected]
Pointer to source function:
Definition at line 727 of file pml_helmholtz_elements.h.
Referenced by oomph::RefineablePMLHelmholtzEquations< DIM >::further_build(), oomph::PMLHelmholtzEquations< DIM >::get_source_helmholtz(), and oomph::PMLHelmholtzEquations< DIM >::source_fct_pt().
The documentation for this class was generated from the following files:
pml_helmholtz_elements.h
pml_helmholtz_elements.cc