oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase Class Reference
A base class for elements that solve the Fourier decomposed (in cylindrical polars) equations of time-harmonic linear elasticity.
#include <time_harmonic_fourier_decomposed_linear_elasticity_elements.h>
Public Types
typedef void(* BodyForceFctPt) (const Vector< double > &x, Vector< std::complex< double > > &b)
Function pointer to function that specifies the body force as a function of the Cartesian coordinates and time FCT(x,b) -- x and b are Vectors!
Public Member Functions
virtual std::complex< unsigned > u_index_time_harmonic_fourier_decomposed_linear_elasticity (const unsigned i) const
Return the index at which the i-th (i=0: r, i=1: z; i=2: theta) real or imag unknown displacement component is stored at the nodes. The default assignment here (u_r_real, u_z_real, ..., u_theta_imag) is appropriate for single-physics problems.
void interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity (const Vector< double > &s, Vector< std::complex< double > > &disp) const
Compute vector of FE interpolated displacement u at local coordinate s.
std::complex< double > interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity (const Vector< double > &s, const unsigned &i) const
Return FE interpolated displacement u[i] (i=0: r, i=1: z; i=2: theta) at local coordinate s.
TimeHarmonicFourierDecomposedLinearElasticityEquationsBase ()
Constructor: Set null pointers for constitutive law. Set physical parameter values to default values, and set body force to zero.
const std::complex< double > & omega_sq () const
Access function for square of non-dim frequency.
std::complex< double > *& omega_sq_pt ()
Access function for square of non-dim frequency.
std::complex< double > *& youngs_modulus_pt ()
Return the pointer to Young's modulus.
std::complex< double > youngs_modulus () const
Access function to Young's modulus.
std::complex< double > & nu () const
Access function for Poisson's ratio.
std::complex< double > *& nu_pt ()
Access function for pointer to Poisson's ratio.
int & fourier_wavenumber () const
Access function for Fourier wavenumber.
int *& fourier_wavenumber_pt ()
Access function for pointer to Fourier wavenumber.
BodyForceFctPt & body_force_fct_pt ()
Access function: Pointer to body force function.
BodyForceFctPt body_force_fct_pt () const
Access function: Pointer to body force function (const version)
void body_force (const Vector< double > &x, Vector< std::complex< double > > &b) const
Evaluate body force at Eulerian coordinate x at present time (returns zero vector if no body force function pointer has been set)
unsigned ndof_types () const
The number of `DOF types` that degrees of freedom in this element are sub-divided into: for now lump them all into one DOF type. Can be adjusted later.
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Protected Attributes
std::complex< double > * Omega_sq_pt
Square of nondim frequency.
std::complex< double > * Youngs_modulus_pt
Pointer to the Young's modulus.
std::complex< double > * Nu_pt
Pointer to Poisson's ratio.
int * Fourier_wavenumber_pt
Pointer to Fourier wavenumber.
BodyForceFctPt Body_force_fct_pt
Pointer to body force function.
Static Protected Attributes
static std::complex< double > Default_omega_sq_value
Static default value for squared frequency.
static std::complex< double > Default_youngs_modulus_value
Static default value for Young's modulus (1.0 -- for natural scaling, i.e. all stresses have been non-dimensionalised by the same reference Young's modulus. Setting the `non-dimensional` Young's modulus (obtained by de-referencing Youngs_modulus_pt) to a number larger than one means that the material is stiffer than assumed in the non-dimensionalisation.
Additional Inherited Members
Detailed Description
A base class for elements that solve the Fourier decomposed (in cylindrical polars) equations of time-harmonic linear elasticity.
Definition at line 57 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
Member Typedef Documentation
BodyForceFctPt
typedef void(* oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::BodyForceFctPt) (const Vector< double > &x, Vector< std::complex< double > > &b)
Function pointer to function that specifies the body force as a function of the Cartesian coordinates and time FCT(x,b) -- x and b are Vectors!
Definition at line 143 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
Constructor & Destructor Documentation
TimeHarmonicFourierDecomposedLinearElasticityEquationsBase()
oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase () [inline]
Constructor: Set null pointers for constitutive law. Set physical parameter values to default values, and set body force to zero.
Definition at line 149 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
Member Function Documentation
body_force()
void oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::body_force (const Vector< double > & x, Vector< std::complex< double > > & b) const [inline]
Evaluate body force at Eulerian coordinate x at present time (returns zero vector if no body force function pointer has been set)
Definition at line 241 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References Body_force_fct_pt, oomph::FiniteElement::dim(), i, and oomph::x.
Referenced by oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity().
body_force_fct_pt() [1/2]
BodyForceFctPt & oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::body_force_fct_pt () [inline]
Access function: Pointer to body force function.
Definition at line 228 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References Body_force_fct_pt.
body_force_fct_pt() [2/2]
BodyForceFctPt oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::body_force_fct_pt () const [inline]
Access function: Pointer to body force function (const version)
Definition at line 234 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References Body_force_fct_pt.
fourier_wavenumber()
int & oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::fourier_wavenumber () const [inline]
Access function for Fourier wavenumber.
Definition at line 205 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References Fourier_wavenumber_pt.
Referenced by oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), and oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::get_strain().
fourier_wavenumber_pt()
int *& oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::fourier_wavenumber_pt () [inline]
Access function for pointer to Fourier wavenumber.
Definition at line 222 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References Fourier_wavenumber_pt.
get_dof_numbers_for_unknowns()
void oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const [inline], [virtual]
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the `DOF type` that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Reimplemented from oomph::GeneralisedElement.
Definition at line 274 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References oomph::GeneralisedElement::eqn_number(), i, oomph::FiniteElement::nnode(), and oomph::FiniteElement::nodal_local_eqn().
interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity() [1/2]
std::complex< double > oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity (const Vector< double > & s, const unsigned & i) const [inline]
Return FE interpolated displacement u[i] (i=0: r, i=1: z; i=2: theta) at local coordinate s.
Definition at line 107 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and u_index_time_harmonic_fourier_decomposed_linear_elasticity().
interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity() [2/2]
void oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity (const Vector< double > & s, Vector< std::complex< double > > & disp) const [inline]
Compute vector of FE interpolated displacement u at local coordinate s.
Definition at line 72 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and u_index_time_harmonic_fourier_decomposed_linear_elasticity().
Referenced by oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::compute_error(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::compute_norm(), and oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output().
ndof_types()
unsigned oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::ndof_types () const [inline], [virtual]
The number of `DOF types` that degrees of freedom in this element are sub-divided into: for now lump them all into one DOF type. Can be adjusted later.
Reimplemented from oomph::GeneralisedElement.
Definition at line 263 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
nu()
std::complex< double > & oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::nu () const [inline]
Access function for Poisson's ratio.
Definition at line 183 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References Nu_pt.
Referenced by oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity().
nu_pt()
std::complex< double > *& oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::nu_pt () [inline]
Access function for pointer to Poisson's ratio.
Definition at line 199 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References Nu_pt.
omega_sq()
const std::complex< double > & oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::omega_sq () const [inline]
Access function for square of non-dim frequency.
Definition at line 159 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References Omega_sq_pt.
Referenced by oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity().
omega_sq_pt()
std::complex< double > *& oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::omega_sq_pt () [inline]
Access function for square of non-dim frequency.
Definition at line 165 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References Omega_sq_pt.
u_index_time_harmonic_fourier_decomposed_linear_elasticity()
virtual std::complex< unsigned > oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::u_index_time_harmonic_fourier_decomposed_linear_elasticity (const unsigned i) const [inline], [virtual]
Return the index at which the i-th (i=0: r, i=1: z; i=2: theta) real or imag unknown displacement component is stored at the nodes. The default assignment here (u_r_real, u_z_real, ..., u_theta_imag) is appropriate for single-physics problems.
Definition at line 65 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References i.
Referenced by oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::get_strain(), and interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity().
youngs_modulus()
std::complex< double > oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::youngs_modulus () const [inline]
Access function to Young's modulus.
Definition at line 177 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References Youngs_modulus_pt.
Referenced by oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity().
youngs_modulus_pt()
std::complex< double > *& oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::youngs_modulus_pt () [inline]
Return the pointer to Young's modulus.
Definition at line 171 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
References Youngs_modulus_pt.
Member Data Documentation
Body_force_fct_pt
BodyForceFctPt oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::Body_force_fct_pt [protected]
Pointer to body force function.
Definition at line 326 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
Referenced by body_force(), and body_force_fct_pt().
Default_omega_sq_value
std::complex< double > oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::Default_omega_sq_value [static], [protected]
Static default value for squared frequency.
Static default value for square of angular frequency: Zero.
Definition at line 329 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
Default_youngs_modulus_value
std::complex< double > oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::Default_youngs_modulus_value [static], [protected]
Static default value for Young's modulus (1.0 -- for natural scaling, i.e. all stresses have been non-dimensionalised by the same reference Young's modulus. Setting the `non-dimensional` Young's modulus (obtained by de-referencing Youngs_modulus_pt) to a number larger than one means that the material is stiffer than assumed in the non-dimensionalisation.
Definition at line 337 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
Fourier_wavenumber_pt
int* oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::Fourier_wavenumber_pt [protected]
Pointer to Fourier wavenumber.
Definition at line 323 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
Referenced by fourier_wavenumber(), and fourier_wavenumber_pt().
Nu_pt
std::complex<double>* oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::Nu_pt [protected]
Pointer to Poisson's ratio.
Definition at line 320 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
Referenced by nu(), and nu_pt().
Omega_sq_pt
std::complex<double>* oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::Omega_sq_pt [protected]
Square of nondim frequency.
Definition at line 314 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
Referenced by omega_sq(), and omega_sq_pt().
Youngs_modulus_pt
std::complex<double>* oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::Youngs_modulus_pt [protected]
Pointer to the Young's modulus.
Definition at line 317 of file time_harmonic_fourier_decomposed_linear_elasticity_elements.h.
Referenced by youngs_modulus(), and youngs_modulus_pt().
The documentation for this class was generated from the following files:
time_harmonic_fourier_decomposed_linear_elasticity_elements.h
time_harmonic_fourier_decomposed_linear_elasticity_elements.cc