oomph::DocLinearSolverInfo Class Reference
Collection of data structures for storing information about linear solves. Currently only contains storage for the iteration counts and the linear solver time.
#include <oomph_utilities.h>
Public Member Functions
DocLinearSolverInfo ()
Constructor. Initialised the Iterations_and_times vector of vector of pairs.
void setup_new_time_step ()
Set up a new vector of pairs for a new time step.
void clear_current_time_step ()
void add_iteration_and_time (unsigned iter, double prec_setup_time, double linear_solver_time)
Add a new iteration and time pair.
unsigned current_ntime_step () const
The number of time steps.
unsigned current_nnewton_step () const
The number of Newton steps.
Vector< Vector< Vector< double > > > & iterations_and_times ()
Accessor function for the iteration and times.
Vector< Vector< Vector< double > > > iterations_and_times () const
Accessor function for the iteration and times (const version).
Private Attributes
Vector< Vector< Vector< double > > > Iterations_and_times
Storage for number of iterations during Newton steps.
Detailed Description
Collection of data structures for storing information about linear solves. Currently only contains storage for the iteration counts and the linear solver time.
Definition at line 429 of file oomph_utilities.h.
Constructor & Destructor Documentation
DocLinearSolverInfo()
oomph::DocLinearSolverInfo::DocLinearSolverInfo () [inline]
Constructor. Initialised the Iterations_and_times vector of vector of pairs.
Definition at line 434 of file oomph_utilities.h.
Member Function Documentation
add_iteration_and_time()
void oomph::DocLinearSolverInfo::add_iteration_and_time (unsigned iter, double prec_setup_time, double linear_solver_time) [inline]
Add a new iteration and time pair.
Definition at line 451 of file oomph_utilities.h.
References Iterations_and_times, and oomph::FiniteElement::size().
clear_current_time_step()
void oomph::DocLinearSolverInfo::clear_current_time_step () [inline]
Definition at line 444 of file oomph_utilities.h.
References Iterations_and_times, and setup_new_time_step().
current_nnewton_step()
unsigned oomph::DocLinearSolverInfo::current_nnewton_step () const [inline]
The number of Newton steps.
Definition at line 480 of file oomph_utilities.h.
References Iterations_and_times, and oomph::FiniteElement::size().
current_ntime_step()
unsigned oomph::DocLinearSolverInfo::current_ntime_step () const [inline]
The number of time steps.
Definition at line 474 of file oomph_utilities.h.
References Iterations_and_times, and oomph::FiniteElement::size().
iterations_and_times() [1/2]
Vector< Vector< Vector< double > > > & oomph::DocLinearSolverInfo::iterations_and_times () [inline]
Accessor function for the iteration and times.
Definition at line 486 of file oomph_utilities.h.
References Iterations_and_times.
iterations_and_times() [2/2]
Vector< Vector< Vector< double > > > oomph::DocLinearSolverInfo::iterations_and_times () const [inline]
Accessor function for the iteration and times (const version).
Definition at line 492 of file oomph_utilities.h.
References Iterations_and_times.
setup_new_time_step()
void oomph::DocLinearSolverInfo::setup_new_time_step () [inline]
Set up a new vector of pairs for a new time step.
Definition at line 437 of file oomph_utilities.h.
References Iterations_and_times.
Referenced by clear_current_time_step().
Member Data Documentation
Iterations_and_times
Vector<Vector<Vector<double> > > oomph::DocLinearSolverInfo::Iterations_and_times [private]
Storage for number of iterations during Newton steps.
Definition at line 499 of file oomph_utilities.h.
Referenced by add_iteration_and_time(), clear_current_time_step(), current_nnewton_step(), current_ntime_step(), iterations_and_times(), iterations_and_times(), and setup_new_time_step().
The documentation for this class was generated from the following file:
oomph_utilities.h