SamplePoint Class Reference
Class for containing sample points: Number of finite element in its mesh and index of sample point within that element.
#include <sample_point_container.h>
Public Member Functions
SamplePoint (const unsigned &element_index_in_mesh, const unsigned &sample_point_index_in_element)
Construct SamplePoint object from number of finite element in its mesh, and index of sample point within that element.
SamplePoint (const SamplePoint &data)
Broken copy constructor.
void operator= (const SamplePoint &)
Broken assignment operator.
unsigned element_index_in_mesh () const
Access function to the index of finite element in its mesh.
unsigned sample_point_index_in_element () const
Index of sample point within element.
Private Attributes
unsigned Element_index_in_mesh
Index of finite element in its mesh.
unsigned Sample_point_index_in_element
Index of the sample point within element.
Detailed Description
Class for containing sample points: Number of finite element in its mesh and index of sample point within that element.
Definition at line 53 of file sample_point_container.h.
Constructor & Destructor Documentation
SamplePoint() [1/2]
SamplePoint::SamplePoint (const unsigned & element_index_in_mesh, const unsigned & sample_point_index_in_element) [inline]
Construct SamplePoint object from number of finite element in its mesh, and index of sample point within that element.
Definition at line 58 of file sample_point_container.h.
SamplePoint() [2/2]
SamplePoint::SamplePoint (const SamplePoint & data) [inline]
Broken copy constructor.
Definition at line 66 of file sample_point_container.h.
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
element_index_in_mesh()
unsigned SamplePoint::element_index_in_mesh () const [inline]
Access function to the index of finite element in its mesh.
Definition at line 78 of file sample_point_container.h.
References Element_index_in_mesh.
Referenced by CGALSamplePointContainer::limited_locate_zeta(), and CGALSamplePointContainer::locate_zeta().
operator=()
void SamplePoint::operator= (const SamplePoint &) [inline]
Broken assignment operator.
Definition at line 72 of file sample_point_container.h.
References oomph::BrokenCopy::broken_assign().
sample_point_index_in_element()
unsigned SamplePoint::sample_point_index_in_element () const [inline]
Index of sample point within element.
Definition at line 84 of file sample_point_container.h.
References Sample_point_index_in_element.
Referenced by CGALSamplePointContainer::limited_locate_zeta(), and CGALSamplePointContainer::locate_zeta().
Member Data Documentation
Element_index_in_mesh
unsigned SamplePoint::Element_index_in_mesh [private]
Index of finite element in its mesh.
Definition at line 92 of file sample_point_container.h.
Referenced by element_index_in_mesh().
Sample_point_index_in_element
unsigned SamplePoint::Sample_point_index_in_element [private]
Index of the sample point within element.
Definition at line 95 of file sample_point_container.h.
Referenced by sample_point_index_in_element().
The documentation for this class was generated from the following file:
sample_point_container.h