oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT > Class Template Reference
SpaceTimeUnsteadyHeatMixedOrder upgraded to become projectable.
#include <discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h>
Public Member Functions
ProjectableUnsteadyHeatMixedOrderSpaceTimeElement ()
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Vector< std::pair< Data *, unsigned > > data_values_of_field (const unsigned &fld)
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld.
unsigned nfields_for_projection ()
Number of fields to be projected: Just one.
unsigned nhistory_values_for_projection (const unsigned &fld)
Number of history values to be stored for fld-th field. (Note: count includes current value!)
unsigned nhistory_values_for_coordinate_projection ()
Number of positional history values (Note: count includes current value!)
double jacobian_and_shape_of_field (const unsigned &fld, const Vector< double > &s, Shape &psi)
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
double get_field (const unsigned &t, const unsigned &fld, const Vector< double > &s)
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
unsigned nvalue_of_field (const unsigned &fld)
Return number of values in field fld: One per node.
int local_equation (const unsigned &fld, const unsigned &j)
Return local equation number of value j in field fld.
void output (std::ostream &outfile, const unsigned &nplot)
Output FE representation of soln: x,t,u or x,y,t,u at n_plot^(SPATIAL_DIM+1) plot points.
Additional Inherited Members
Detailed Description
template<class UNSTEADY_HEAT_ELEMENT>
class oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >
SpaceTimeUnsteadyHeatMixedOrder upgraded to become projectable.
Definition at line 1193 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
Constructor & Destructor Documentation
ProjectableUnsteadyHeatMixedOrderSpaceTimeElement()
template<class UNSTEADY_HEAT_ELEMENT >
oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement () [inline]
Constructor [this was only required explicitly from gcc 4.5.2 onwards...].
Definition at line 1199 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
Member Function Documentation
data_values_of_field()
template<class UNSTEADY_HEAT_ELEMENT >
Vector<std::pair<Data*, unsigned> > oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::data_values_of_field (const unsigned & fld) [inline], [virtual]
Specify the values associated with field fld. The information is returned in a vector of pairs which comprise the Data object and the value within it, that correspond to field fld.
Implements oomph::ProjectableElementBase.
Definition at line 1205 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
get_field()
template<class UNSTEADY_HEAT_ELEMENT >
double oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::get_field (const unsigned & t, const unsigned & fld, const Vector< double > & s) [inline], [virtual]
Return interpolated field fld at local coordinate s, at time level t (t=0: present; t>0: history values)
Implements oomph::ProjectableElementBase.
Definition at line 1339 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References interpolated_u(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), and oomph::FiniteElement::shape().
jacobian_and_shape_of_field()
template<class UNSTEADY_HEAT_ELEMENT >
double oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::jacobian_and_shape_of_field (const unsigned & fld, const Vector< double > & s, Shape & psi) [inline], [virtual]
Return Jacobian of mapping and shape functions of field fld at local coordinate s.
Implements oomph::ProjectableElementBase.
Definition at line 1289 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::FiniteElement::dim(), oomph::FiniteElement::nnode(), and s.
local_equation()
template<class UNSTEADY_HEAT_ELEMENT >
int oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::local_equation (const unsigned & fld, const unsigned & j) [inline], [virtual]
Return local equation number of value j in field fld.
Implements oomph::ProjectableElementBase.
Definition at line 1415 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::FiniteElement::nodal_local_eqn().
nfields_for_projection()
template<class UNSTEADY_HEAT_ELEMENT >
unsigned oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::nfields_for_projection () [inline], [virtual]
Number of fields to be projected: Just one.
Implements oomph::ProjectableElementBase.
Definition at line 1244 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
nhistory_values_for_coordinate_projection()
template<class UNSTEADY_HEAT_ELEMENT >
unsigned oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::nhistory_values_for_coordinate_projection () [inline], [virtual]
Number of positional history values (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 1280 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), and oomph::Node::position_time_stepper_pt().
nhistory_values_for_projection()
template<class UNSTEADY_HEAT_ELEMENT >
unsigned oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::nhistory_values_for_projection (const unsigned & fld) [inline], [virtual]
Number of history values to be stored for fld-th field. (Note: count includes current value!)
Implements oomph::ProjectableElementBase.
Definition at line 1253 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::FiniteElement::node_pt(), and oomph::Data::ntstorage().
nvalue_of_field()
template<class UNSTEADY_HEAT_ELEMENT >
unsigned oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::nvalue_of_field (const unsigned & fld) [inline], [virtual]
Return number of values in field fld: One per node.
Implements oomph::ProjectableElementBase.
Definition at line 1389 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::FiniteElement::nnode().
output()
template<class UNSTEADY_HEAT_ELEMENT >
void oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::output (std::ostream & outfile, const unsigned & nplot) [inline], [virtual]
Output FE representation of soln: x,t,u or x,y,t,u at n_plot^(SPATIAL_DIM+1) plot points.
Reimplemented from oomph::FiniteElement.
Definition at line 1445 of file discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h.
References oomph::FiniteElement::dim(), oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::nplot_points(), oomph::TimeStepper::ntstorage(), oomph::Node::position_time_stepper_pt(), s, t, oomph::FiniteElement::tecplot_zone_string(), oomph::Data::time_stepper_pt(), and oomph::FiniteElement::write_tecplot_zone_footer().
The documentation for this class was generated from the following file:
discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h