oomph::TriangleHelper Namespace Reference
Helper namespace for triangle meshes.
Functions
void clear_triangulateio (TriangulateIO &triangulate_io, const bool &clear_hole_data)
Clear TriangulateIO structure.
void initialise_triangulateio (TriangulateIO &triangle_io)
Initialise TriangulateIO structure.
TriangulateIO deep_copy_of_triangulateio_representation (TriangulateIO &triangle_io, const bool &quiet)
Make (partial) deep copy of TriangulateIO object. We only copy those items we need within oomph-lib's adaptation procedures. Warnings are issued if triangulate_io contains data that is not not copied, unless quiet=true;.
void write_triangulateio_to_polyfile (TriangulateIO &triangle_io, std::ostream &poly_file)
Write the triangulateio data to disk as a poly file, mainly used for debugging.
void create_triangulateio_from_polyfiles (const std::string &node_file_name, const std::string &element_file_name, const std::string &poly_file_name, TriangulateIO &triangle_io, bool &use_attributes)
Create a triangulateio data file from ele node and poly files. This is used if the mesh is generated by using Triangle externally. The triangulateio structure is required to dump the mesh topology for restarts.
void dump_triangulateio (TriangulateIO &triangle_io, std::ostream &dump_file)
Write all the triangulateio data to disk in a dump file that can then be used to restart simulations.
void read_triangulateio (std::istream &restart_file, TriangulateIO &triangle_io)
Read the triangulateio data from a dump file on disk, which can then be used to restart simulations.
Detailed Description
Helper namespace for triangle meshes.
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
Helper namespace for triangle meshes
Function Documentation
clear_triangulateio()
void oomph::TriangleHelper::clear_triangulateio (TriangulateIO & triangulate_io, const bool & clear_hole_data)
Clear TriangulateIO structure.
Definition at line 44 of file unstructured_two_d_mesh_geometry_base.cc.
References oomph::TriangulateIO::edgelist, oomph::TriangulateIO::edgemarkerlist, oomph::TriangulateIO::holelist, initialise_triangulateio(), oomph::TriangulateIO::neighborlist, oomph::TriangulateIO::normlist, oomph::TriangulateIO::numberofcorners, oomph::TriangulateIO::numberofedges, oomph::TriangulateIO::numberofholes, oomph::TriangulateIO::numberofpointattributes, oomph::TriangulateIO::numberofpoints, oomph::TriangulateIO::numberofregions, oomph::TriangulateIO::numberofsegments, oomph::TriangulateIO::numberoftriangleattributes, oomph::TriangulateIO::numberoftriangles, oomph::TriangulateIO::pointattributelist, oomph::TriangulateIO::pointlist, oomph::TriangulateIO::pointmarkerlist, oomph::TriangulateIO::regionlist, oomph::TriangulateIO::segmentlist, oomph::TriangulateIO::segmentmarkerlist, oomph::TriangulateIO::trianglearealist, oomph::TriangulateIO::triangleattributelist, and oomph::TriangulateIO::trianglelist.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::adapt(), oomph::TriangleMeshBase::clear_triangulateio(), oomph::QuadFromTriangleMesh< ELEMENT >::generic_constructor(), oomph::TriangleMesh< ELEMENT >::generic_constructor(), oomph::RefineableTriangleMesh< ELEMENT >::RefineableTriangleMesh(), oomph::TriangleMeshBase::remesh_from_triangulateio(), oomph::TriangleMesh< ELEMENT >::TriangleMesh(), oomph::TriangleMesh< ELEMENT >::~TriangleMesh(), and oomph::TriangleMeshBase::~TriangleMeshBase().
create_triangulateio_from_polyfiles()
void oomph::TriangleHelper::create_triangulateio_from_polyfiles (const std::string & node_file_name, const std::string & element_file_name, const std::string & poly_file_name, TriangulateIO & triangle_io, bool & use_attributes)
Create a triangulateio data file from ele node and poly files. This is used if the mesh is generated by using Triangle externally. The triangulateio structure is required to dump the mesh topology for restarts.
Definition at line 404 of file unstructured_two_d_mesh_geometry_base.cc.
References e, oomph::TriangulateIO::holelist, i, initialise_triangulateio(), oomph::TriangulateIO::numberofcorners, oomph::TriangulateIO::numberofholes, oomph::TriangulateIO::numberofpointattributes, oomph::TriangulateIO::numberofpoints, oomph::TriangulateIO::numberofregions, oomph::TriangulateIO::numberofsegments, oomph::TriangulateIO::numberoftriangleattributes, oomph::TriangulateIO::numberoftriangles, oomph::TriangulateIO::pointattributelist, oomph::TriangulateIO::pointlist, oomph::TriangulateIO::pointmarkerlist, oomph::TriangulateIO::regionlist, oomph::TriangulateIO::segmentlist, oomph::TriangulateIO::segmentmarkerlist, oomph::Global_string_for_annotation::string(), oomph::TriangulateIO::triangleattributelist, and oomph::TriangulateIO::trianglelist.
Referenced by oomph::TriangleMesh< ELEMENT >::TriangleMesh().
deep_copy_of_triangulateio_representation()
TriangulateIO oomph::TriangleHelper::deep_copy_of_triangulateio_representation (TriangulateIO & triangle_io, const bool & quiet)
Make (partial) deep copy of TriangulateIO object. We only copy those items we need within oomph-lib's adaptation procedures. Warnings are issued if triangulate_io contains data that is not not copied, unless quiet=true;.
Definition at line 134 of file unstructured_two_d_mesh_geometry_base.cc.
References oomph::TriangulateIO::edgelist, oomph::TriangulateIO::edgemarkerlist, oomph::TriangulateIO::holelist, initialise_triangulateio(), oomph::TriangulateIO::neighborlist, oomph::TriangulateIO::normlist, oomph::TriangulateIO::numberofcorners, oomph::TriangulateIO::numberofedges, oomph::TriangulateIO::numberofholes, oomph::TriangulateIO::numberofpointattributes, oomph::TriangulateIO::numberofpoints, oomph::TriangulateIO::numberofregions, oomph::TriangulateIO::numberofsegments, oomph::TriangulateIO::numberoftriangleattributes, oomph::TriangulateIO::numberoftriangles, oomph::TriangulateIO::pointattributelist, oomph::TriangulateIO::pointlist, oomph::TriangulateIO::pointmarkerlist, oomph::TriangulateIO::regionlist, oomph::TriangulateIO::segmentlist, oomph::TriangulateIO::segmentmarkerlist, oomph::TriangulateIO::trianglearealist, oomph::TriangulateIO::triangleattributelist, and oomph::TriangulateIO::trianglelist.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::adapt().
dump_triangulateio()
void oomph::TriangleHelper::dump_triangulateio (TriangulateIO & triangle_io, std::ostream & dump_file)
Write all the triangulateio data to disk in a dump file that can then be used to restart simulations.
Definition at line 709 of file unstructured_two_d_mesh_geometry_base.cc.
References e, oomph::TriangulateIO::holelist, i, oomph::TriangulateIO::numberofcorners, oomph::TriangulateIO::numberofholes, oomph::TriangulateIO::numberofpointattributes, oomph::TriangulateIO::numberofpoints, oomph::TriangulateIO::numberofregions, oomph::TriangulateIO::numberofsegments, oomph::TriangulateIO::numberoftriangleattributes, oomph::TriangulateIO::numberoftriangles, oomph::TriangulateIO::pointattributelist, oomph::TriangulateIO::pointlist, oomph::TriangulateIO::pointmarkerlist, oomph::TriangulateIO::regionlist, oomph::TriangulateIO::segmentlist, oomph::TriangulateIO::segmentmarkerlist, oomph::TriangulateIO::triangleattributelist, and oomph::TriangulateIO::trianglelist.
Referenced by oomph::TriangleMeshBase::dump_triangulateio().
initialise_triangulateio()
void oomph::TriangleHelper::initialise_triangulateio (TriangulateIO & triangle_io)
Initialise TriangulateIO structure.
Definition at line 91 of file unstructured_two_d_mesh_geometry_base.cc.
References oomph::TriangulateIO::edgelist, oomph::TriangulateIO::edgemarkerlist, oomph::TriangulateIO::holelist, oomph::TriangulateIO::neighborlist, oomph::TriangulateIO::normlist, oomph::TriangulateIO::numberofcorners, oomph::TriangulateIO::numberofedges, oomph::TriangulateIO::numberofholes, oomph::TriangulateIO::numberofpointattributes, oomph::TriangulateIO::numberofpoints, oomph::TriangulateIO::numberofregions, oomph::TriangulateIO::numberofsegments, oomph::TriangulateIO::numberoftriangleattributes, oomph::TriangulateIO::numberoftriangles, oomph::TriangulateIO::pointattributelist, oomph::TriangulateIO::pointlist, oomph::TriangulateIO::pointmarkerlist, oomph::TriangulateIO::regionlist, oomph::TriangulateIO::segmentlist, oomph::TriangulateIO::segmentmarkerlist, oomph::TriangulateIO::trianglearealist, oomph::TriangulateIO::triangleattributelist, and oomph::TriangulateIO::trianglelist.
Referenced by oomph::TriangleMesh< ELEMENT >::build_triangulateio(), oomph::UnstructuredTwoDMeshGeometryBase::build_triangulateio(), clear_triangulateio(), create_triangulateio_from_polyfiles(), deep_copy_of_triangulateio_representation(), oomph::QuadFromTriangleMesh< ELEMENT >::generic_constructor(), oomph::TriangleMesh< ELEMENT >::generic_constructor(), read_triangulateio(), oomph::RefineableTriangleMesh< ELEMENT >::refine_triangulateio(), oomph::RefineableTriangleMesh< ELEMENT >::RefineableTriangleMesh(), and oomph::TriangleMeshBase::TriangleMeshBase().
read_triangulateio()
void oomph::TriangleHelper::read_triangulateio (std::istream & restart_file, TriangulateIO & triangle_io)
Read the triangulateio data from a dump file on disk, which can then be used to restart simulations.
Definition at line 853 of file unstructured_two_d_mesh_geometry_base.cc.
References e, oomph::TriangulateIO::holelist, i, initialise_triangulateio(), oomph::TriangulateIO::numberofcorners, oomph::TriangulateIO::numberofholes, oomph::TriangulateIO::numberofpointattributes, oomph::TriangulateIO::numberofpoints, oomph::TriangulateIO::numberofregions, oomph::TriangulateIO::numberofsegments, oomph::TriangulateIO::numberoftriangleattributes, oomph::TriangulateIO::numberoftriangles, oomph::TriangulateIO::pointattributelist, oomph::TriangulateIO::pointlist, oomph::TriangulateIO::pointmarkerlist, oomph::TriangulateIO::regionlist, oomph::TriangulateIO::segmentlist, oomph::TriangulateIO::segmentmarkerlist, oomph::Global_string_for_annotation::string(), oomph::TriangulateIO::triangleattributelist, and oomph::TriangulateIO::trianglelist.
Referenced by oomph::TriangleMeshBase::remesh_from_triangulateio().
write_triangulateio_to_polyfile()
void oomph::TriangleHelper::write_triangulateio_to_polyfile (TriangulateIO & triangle_io, std::ostream & poly_file)
Write the triangulateio data to disk as a poly file, mainly used for debugging.
Definition at line 308 of file unstructured_two_d_mesh_geometry_base.cc.
References oomph::TriangulateIO::holelist, i, oomph::TriangulateIO::numberofholes, oomph::TriangulateIO::numberofpointattributes, oomph::TriangulateIO::numberofpoints, oomph::TriangulateIO::numberofregions, oomph::TriangulateIO::numberofsegments, oomph::TriangulateIO::pointattributelist, oomph::TriangulateIO::pointlist, oomph::TriangulateIO::pointmarkerlist, oomph::TriangulateIO::regionlist, oomph::TriangulateIO::segmentlist, and oomph::TriangulateIO::segmentmarkerlist.