oomph::TimingHelpers Namespace Reference
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Functions
double timer ()
returns the time in seconds after some point in past
std::string convert_secs_to_formatted_string (const double &time_in_sec)
Returns a nicely formatted string from an input time in seconds; the format depends on the size of time, e.g.: 86510 will be printed as 1d 1m:50 3710 will be printed as 1h:01:50 700 will be printed as 11m:40 59 will be printed as 59s.
Detailed Description
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Helper for recording execution time.
Function Documentation
convert_secs_to_formatted_string()
std::string oomph::TimingHelpers::convert_secs_to_formatted_string (const double & time_in_sec)
Returns a nicely formatted string from an input time in seconds; the format depends on the size of time, e.g.: 86510 will be printed as 1d 1m:50 3710 will be printed as 1h:01:50 700 will be printed as 11m:40 59 will be printed as 59s.
Returns a nicely formatted string from an input time in seconds; the format depends on the size of time, e.g.: 86510 will be printed as 1d 1m:50 3710 will be printed as 1h:01:50 700 will be printed as 11m:40 59.15 will be printed as 59.2s.
Definition at line 1316 of file oomph_utilities.cc.
Referenced by oomph::MumpsSolver::backsub(), oomph::MumpsSolver::factorise(), oomph::Problem::newton_solve(), oomph::SuperLUSolver::resolve(), oomph::MumpsSolver::resolve(), oomph::SuperLUSolver::resolve_transpose(), oomph::MumpsSolver::solve(), oomph::DenseLU::solve(), oomph::FD_LU::solve(), oomph::SuperLUSolver::solve(), and oomph::SuperLUSolver::solve_transpose().
timer()
double oomph::TimingHelpers::timer ()
returns the time in seconds after some point in past
Definition at line 1295 of file oomph_utilities.cc.
References oomph::MPI_Helpers::mpi_has_been_initialised(), and t.
Referenced by oomph::RefineableGmshTetMesh< ELEMENT >::adapt(), oomph::RefineableTetgenMesh< ELEMENT >::adapt(), oomph::RefineableTriangleMesh< ELEMENT >::adapt(), oomph::Problem::adapt(), oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::TreeBasedRefineableMesh< ELEMENT >::additional_synchronise_hanging_nodes(), oomph::Problem::assign_eqn_numbers(), oomph::Multi_domain_functions::aux_setup_multi_domain_interaction(), oomph::MumpsSolver::backsub(), oomph::ExtrudedCubeMeshFromQuadMesh< ELEMENT >::build_mesh(), CGALSamplePointContainer::CGALSamplePointContainer(), oomph::Mesh::classify_halo_and_haloed_nodes(), oomph::TreeBasedRefineableMeshBase::classify_halo_and_haloed_nodes(), oomph::ComplexDampedJacobi< MATRIX >::complex_solve_helper(), oomph::ComplexGMRES< MATRIX >::complex_solve_helper(), oomph::CRDoubleMatrixHelpers::concatenate(), oomph::RefineableTriangleMesh< ELEMENT >::create_new_shared_boundaries(), oomph::Problem::distribute(), oomph::MumpsSolver::factorise(), oomph::MGSolver< DIM >::full_setup(), oomph::HelmholtzMGPreconditioner< DIM >::full_setup(), CGALSamplePointContainer::get_sample_points(), oomph::GmshTetScaffoldMesh::GmshTetScaffoldMesh(), oomph::HypreInterface::hypre_solve(), oomph::HypreInterface::hypre_solver_setup(), oomph::RefineableTriangleMesh< ELEMENT >::load_balance(), oomph::Problem::load_balance(), oomph::MGSolver< DIM >::mg_solve(), oomph::HelmholtzMGPreconditioner< DIM >::mg_solve(), oomph::Problem::newton_solve(), oomph::Mesh::node_update(), NonRefineableBinArray::NonRefineableBinArray(), oomph::Problem::p_adapt(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::Problem::p_refine_uniformly_aux(), oomph::Problem::parallel_sparse_assemble(), oomph::BlockDiagonalPreconditioner< MATRIX >::preconditioner_solve(), oomph::HyprePreconditioner::preconditioner_solve(), oomph::TrilinosPreconditionerBase::preconditioner_solve(), oomph::PressureBasedSolidLSCPreconditioner::preconditioner_solve(), oomph::GMRESBlockPreconditioner::preconditioner_solve(), BinArray::profile_get_neighbouring_bins_helper(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project(), oomph::Problem::prune_halo_elements_and_nodes(), oomph::Mesh::prune_halo_elements_and_nodes(), oomph::VorticitySmoother< ELEMENT >::recover_vorticity(), oomph::Problem::refine_uniformly_aux(), RefineableBinArray::RefineableBinArray(), oomph::RefineableTriangleMesh< ELEMENT >::reset_halo_haloed_scheme(), oomph::Mesh::resize_halo_nodes(), oomph::SuperLUSolver::resolve(), oomph::MumpsSolver::resolve(), oomph::TrilinosAztecOOSolver::resolve(), oomph::SuperLUSolver::resolve_transpose(), oomph::MGSolver< DIM >::self_test(), oomph::BlockDiagonalPreconditioner< MATRIX >::setup(), oomph::BlockTriangularPreconditioner< MATRIX >::setup(), oomph::FSIPreconditioner::setup(), oomph::NavierStokesSchurComplementPreconditioner::setup(), oomph::PressureBasedSolidLSCPreconditioner::setup(), oomph::ExactDGPBlockPreconditioner< MATRIX >::setup(), oomph::BandedBlockTriangularPreconditioner< MATRIX >::setup(), oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::setup(), oomph::GMRESBlockPreconditioner::setup(), oomph::MatrixVectorProduct::setup(), oomph::Preconditioner::setup(), oomph::LineVisualiser::setup(), oomph::HelmholtzMGPreconditioner< DIM >::setup_coarsest_level_structures(), oomph::MGSolver< DIM >::setup_mg_hierarchy(), oomph::HelmholtzMGPreconditioner< DIM >::setup_mg_hierarchy(), oomph::MGSolver< DIM >::setup_mg_structures(), oomph::HelmholtzMGPreconditioner< DIM >::setup_mg_structures(), oomph::Mesh::setup_shared_node_scheme(), oomph::MGSolver< DIM >::setup_smoothers(), oomph::HelmholtzMGPreconditioner< DIM >::setup_smoothers(), oomph::MGSolver< DIM >::setup_transfer_matrices(), oomph::HelmholtzMGPreconditioner< DIM >::setup_transfer_matrices(), oomph::TrilinosMLPreconditioner::setup_trilinos_preconditioner(), oomph::SimpleCubicTetMesh< ELEMENT >::SimpleCubicTetMesh(), oomph::MumpsSolver::solve(), oomph::CG< MATRIX >::solve(), oomph::BiCGStab< MATRIX >::solve(), oomph::GS< MATRIX >::solve(), oomph::GS< CRDoubleMatrix >::solve(), oomph::DampedJacobi< MATRIX >::solve(), oomph::GMRES< MATRIX >::solve(), oomph::AugmentedProblemGMRES::solve(), oomph::DenseLU::solve(), oomph::SuperLUSolver::solve(), oomph::HelmholtzGMRESMG< MATRIX >::solve(), oomph::HelmholtzFGMRESMG< MATRIX >::solve(), oomph::HypreSolver::solve(), oomph::TrilinosAztecOOSolver::solve(), oomph::CG< MATRIX >::solve_helper(), oomph::BiCGStab< MATRIX >::solve_helper(), oomph::GS< MATRIX >::solve_helper(), oomph::GS< CRDoubleMatrix >::solve_helper(), oomph::DampedJacobi< MATRIX >::solve_helper(), oomph::GMRES< MATRIX >::solve_helper(), oomph::AugmentedProblemGMRES::solve_helper(), oomph::HelmholtzGMRESMG< MATRIX >::solve_helper(), oomph::HelmholtzFGMRESMG< MATRIX >::solve_helper(), oomph::SuperLUSolver::solve_transpose(), oomph::TrilinosAztecOOSolver::solver_setup(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_lists(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_maps(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_two_arrays(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_two_vectors(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_vectors_of_pairs(), oomph::Problem::synchronise_eqn_numbers(), oomph::TreeBasedRefineableMeshBase::synchronise_hanging_nodes(), oomph::TreeBasedRefineableMeshBase::synchronise_nonhanging_nodes(), oomph::Mesh::synchronise_shared_nodes(), and oomph::GMRES< MATRIX >::update().