oomph::DebugHelpers Namespace Reference
Namespace for debugging helpers. Currently only contains a function to prett-ify file name and line numbers (in red) to use when debugging. Makes it easy to identify where a std::cout statement was called.
Functions
std::string debug_string (const std::string &filename, const int &line, const bool &make_new_line)
Return the concaternation of the initials of the input file name and line number. The make_new_line flag indicates whether the string starts with a `\n`, i.e. a new line.
Detailed Description
Namespace for debugging helpers. Currently only contains a function to prett-ify file name and line numbers (in red) to use when debugging. Makes it easy to identify where a std::cout statement was called.
Function Documentation
debug_string()
std::string oomph::DebugHelpers::debug_string (const std::string & filename, const int & line, const bool & make_new_line)
Return the concaternation of the initials of the input file name and line number. The make_new_line flag indicates whether the string starts with a `\n`, i.e. a new line.
Return the concaternation of the initials of the input file name and line number. The make_new_line flag indicates whether the string starts on a new line or not.
Definition at line 92 of file oomph_utilities.cc.
References debug_string(), and oomph::Global_string_for_annotation::string().
Referenced by debug_string().