oomph::LeakCheckNames Namespace Reference
Namespace for leak check: Keep a running count of all instantiated objects -- add your own if you want to...
Functions
void reset ()
void doc ()
Variables
long QuadTree_build
long OcTree_build
long QuadTreeForest_build
long OcTreeForest_build
long RefineableQElement< 2 > _build
long MacroElement_build
long HangInfo_build
long Node_build
long GeomReference_build
long AlgebraicNode_build
long AlgebraicNodeNodeUpdateInfo_build
Detailed Description
Namespace for leak check: Keep a running count of all instantiated objects -- add your own if you want to...
Function Documentation
doc()
void oomph::LeakCheckNames::doc ()
Definition at line 1212 of file oomph_utilities.cc.
References _build, AlgebraicNode_build, GeomReference_build, HangInfo_build, MacroElement_build, Node_build, OcTree_build, OcTreeForest_build, oomph::oomph_info, QuadTree_build, and QuadTreeForest_build.
Referenced by oomph::CommandLineArgs::ArgInfo< T >::ArgInfo(), oomph::SuperLUSolver::backsub_distributed(), oomph::SuperLUSolver::backsub_serial(), oomph::SuperLUSolver::backsub_transpose_serial(), oomph::CRComplexMatrix::clean_up_memory(), oomph::CCComplexMatrix::clean_up_memory(), oomph::SuperLUSolver::clean_up_memory(), oomph::SuperLUSolver::factorise_distributed(), oomph::SuperLUSolver::factorise_serial(), oomph::CRComplexMatrix::lubksub(), oomph::CCComplexMatrix::lubksub(), oomph::CRComplexMatrix::ludecompose(), oomph::CCComplexMatrix::ludecompose(), oomph::BrickMeshBase::setup_boundary_element_info(), oomph::LineMeshBase::setup_boundary_element_info(), oomph::QuadMeshBase::setup_boundary_element_info(), oomph::TetMeshBase::setup_boundary_element_info(), oomph::TriangleMeshBase::setup_boundary_element_info(), oomph::HermiteQuadMesh< ELEMENT >::setup_boundary_element_info(), oomph::CommandLineArgs::specify_command_line_flag(), superlu(), superlu_complex(), superlu_dist_distributed_matrix(), and superlu_dist_global_matrix().
reset()
void oomph::LeakCheckNames::reset ()
Definition at line 1197 of file oomph_utilities.cc.
References _build, AlgebraicNode_build, GeomReference_build, HangInfo_build, MacroElement_build, Node_build, OcTree_build, OcTreeForest_build, QuadTree_build, and QuadTreeForest_build.
Variable Documentation
_build
long RefineableQElement< 3 > oomph::LeakCheckNames::_build
Definition at line 1189 of file oomph_utilities.cc.
Referenced by doc(), oomph::RefineableQElement< 3 >::RefineableQElement(), oomph::RefineableQElement< 1 >::RefineableQElement(), oomph::RefineableQElement< 2 >::RefineableQElement(), oomph::RefineableQSpectralElement< 3 >::RefineableQSpectralElement(), oomph::RefineableQSpectralElement< 1 >::RefineableQSpectralElement(), oomph::RefineableQSpectralElement< 2 >::RefineableQSpectralElement(), reset(), oomph::RefineableQElement< 1 >::~RefineableQElement(), oomph::RefineableQElement< 2 >::~RefineableQElement(), oomph::RefineableQSpectralElement< 3 >::~RefineableQSpectralElement(), oomph::RefineableQSpectralElement< 1 >::~RefineableQSpectralElement(), and oomph::RefineableQSpectralElement< 2 >::~RefineableQSpectralElement().
AlgebraicNode_build
long oomph::LeakCheckNames::AlgebraicNode_build
Definition at line 1195 of file oomph_utilities.cc.
Referenced by oomph::AlgebraicNode::AlgebraicNode(), doc(), reset(), and oomph::AlgebraicNode::~AlgebraicNode().
AlgebraicNodeNodeUpdateInfo_build
long oomph::LeakCheckNames::AlgebraicNodeNodeUpdateInfo_build [extern]
GeomReference_build
long oomph::LeakCheckNames::GeomReference_build
Definition at line 1194 of file oomph_utilities.cc.
Referenced by doc(), and reset().
HangInfo_build
long oomph::LeakCheckNames::HangInfo_build
Definition at line 1192 of file oomph_utilities.cc.
Referenced by doc(), oomph::HangInfo::HangInfo(), reset(), and oomph::HangInfo::~HangInfo().
MacroElement_build
long oomph::LeakCheckNames::MacroElement_build
Definition at line 1191 of file oomph_utilities.cc.
Referenced by doc(), oomph::MacroElement::MacroElement(), reset(), and oomph::MacroElement::~MacroElement().
Node_build
long oomph::LeakCheckNames::Node_build
Definition at line 1193 of file oomph_utilities.cc.
Referenced by doc(), oomph::Node::Node(), reset(), and oomph::Node::~Node().
OcTree_build
long oomph::LeakCheckNames::OcTree_build
Definition at line 1186 of file oomph_utilities.cc.
Referenced by doc(), and reset().
OcTreeForest_build
long oomph::LeakCheckNames::OcTreeForest_build
Definition at line 1188 of file oomph_utilities.cc.
Referenced by doc(), oomph::OcTreeForest::OcTreeForest(), and reset().
QuadTree_build
long oomph::LeakCheckNames::QuadTree_build
Definition at line 1185 of file oomph_utilities.cc.
Referenced by doc(), and reset().
QuadTreeForest_build
long oomph::LeakCheckNames::QuadTreeForest_build
Definition at line 1187 of file oomph_utilities.cc.
Referenced by doc(), oomph::QuadTreeForest::QuadTreeForest(), and reset().