oomph::ExactPreconditionerFactory Namespace Reference
Namespace containing functions required to create exact preconditioner.
Functions
Preconditioner * create_exact_preconditioner ()
Factory function to create suitable exact preconditioner.
Detailed Description
Namespace containing functions required to create exact preconditioner.
Function Documentation
create_exact_preconditioner()
Preconditioner * oomph::ExactPreconditionerFactory::create_exact_preconditioner ()
Factory function to create suitable exact preconditioner.
Definition at line 2819 of file linear_solver.cc.
Referenced by oomph::PreconditionerCreationFunctions::create_exact_preconditioner(), oomph::FSIPreconditioner::FSIPreconditioner(), oomph::PseudoElasticFSIPreconditioner::PseudoElasticFSIPreconditioner(), oomph::NavierStokesSchurComplementPreconditioner::set_f_exact_preconditioner(), oomph::PressureBasedSolidLSCPreconditioner::set_f_exact_preconditioner(), oomph::NavierStokesSchurComplementPreconditioner::set_p_exact_preconditioner(), oomph::PressureBasedSolidLSCPreconditioner::set_p_exact_preconditioner(), oomph::LagrangeEnforcedFlowPreconditioner::set_superlu_for_navier_stokes_preconditioner(), oomph::BiharmonicPreconditioner::setup(), oomph::ExactSubBiharmonicPreconditioner::setup(), oomph::InexactSubBiharmonicPreconditioner::setup(), oomph::SimpleFSIPreconditioner< MATRIX >::setup(), oomph::PseudoElasticPreconditioner::setup(), oomph::PseudoElasticPreconditionerOld::setup(), oomph::PseudoElasticPreconditionerSubsidiaryPreconditionerOld::setup(), oomph::LagrangeEnforcedFlowPreconditioner::setup(), oomph::NavierStokesSchurComplementPreconditioner::setup(), oomph::PressureBasedSolidLSCPreconditioner::setup(), and oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::setup().