oomph::Pseudo_Elastic_Preconditioner_Subsidiary_Operator_Helper Namespace Reference
Functions to create instances of optimal subsidiary operators for the PseudoElasticPreconditioner.
Functions
Preconditioner * get_elastic_preconditioner_hypre ()
AMG w/ GS smoothing for the augmented elastic subsidiary linear systems.
Preconditioner * get_elastic_preconditioner ()
AMG w/ GS smoothing for the augmented elastic subsidiary linear systems -- calls Hypre version to stay consistent with previous default.
Preconditioner * get_elastic_preconditioner_trilinos_ml ()
TrilinosML smoothing for the augmented elastic subsidiary linear systems.
Preconditioner * get_lagrange_multiplier_preconditioner ()
CG with diagonal preconditioner for the lagrange multiplier subsidiary linear systems.
Detailed Description
Functions to create instances of optimal subsidiary operators for the PseudoElasticPreconditioner.
Functions to create instances of optimal subsidiary operators for the PseudoElasticPreconditioner. By default we use hypre for the the elastic blocks but can use Trilinos ML too.
Function Documentation
get_elastic_preconditioner()
Preconditioner * oomph::Pseudo_Elastic_Preconditioner_Subsidiary_Operator_Helper::get_elastic_preconditioner ()
AMG w/ GS smoothing for the augmented elastic subsidiary linear systems -- calls Hypre version to stay consistent with previous default.
Definition at line 66 of file pseudo_elastic_preconditioner.cc.
References get_elastic_preconditioner_hypre().
get_elastic_preconditioner_hypre()
Preconditioner * oomph::Pseudo_Elastic_Preconditioner_Subsidiary_Operator_Helper::get_elastic_preconditioner_hypre ()
AMG w/ GS smoothing for the augmented elastic subsidiary linear systems.
Hypre AMG w/ GS smoothing for the augmented elastic subsidiary linear systems.
Definition at line 41 of file pseudo_elastic_preconditioner.cc.
References oomph::HyprePreconditioner::amg_coarsening(), oomph::HyprePreconditioner::amg_damping(), oomph::HyprePreconditioner::amg_simple_smoother(), oomph::HyprePreconditioner::amg_using_simple_smoothing(), oomph::HypreInterface::BoomerAMG, oomph::MPI_Helpers::communicator_pt(), oomph::HyprePreconditioner::hypre_method(), and oomph::HyprePreconditioner::set_amg_iterations().
Referenced by get_elastic_preconditioner().
get_elastic_preconditioner_trilinos_ml()
Preconditioner * oomph::Pseudo_Elastic_Preconditioner_Subsidiary_Operator_Helper::get_elastic_preconditioner_trilinos_ml ()
TrilinosML smoothing for the augmented elastic subsidiary linear systems.
Definition at line 77 of file pseudo_elastic_preconditioner.cc.
get_lagrange_multiplier_preconditioner()
Preconditioner * oomph::Pseudo_Elastic_Preconditioner_Subsidiary_Operator_Helper::get_lagrange_multiplier_preconditioner ()
CG with diagonal preconditioner for the lagrange multiplier subsidiary linear systems.
Definition at line 85 of file pseudo_elastic_preconditioner.cc.
References oomph::TrilinosAztecOOSolver::CG.