oomph::OneDimDiscontinuousGalerkinMixedOrderTest Namespace Reference
One dimensional shape functions and derivatives. Empty -- simply establishes the template parameters.
Functions
template<unsigned NNODE_1D>
void shape (const double &s, double *Psi)
Definition for 1D Lagrange shape functions. The value of all the shape functions at the local coordinate s are returned in the array Psi.
template<unsigned NNODE_1D>
void dshape (const double &s, double *DPsi)
Definition for derivatives of 1D Lagrange shape functions. The value of all the shape function derivatives at the local coordinate s are returned in the array DPsi.
template<unsigned NNODE_1D>
void d2shape (const double &s, double *DPsi)
Definition for second derivatives of 1D Lagrange shape functions. The value of all the shape function derivatives at the local coordinate s are returned in the array DPsi.
template<> void shape< 2 > (const double &s, double *Psi)
1D shape functions specialised to linear order (2 Nodes)
template<> void dshape< 2 > (const double &s, double *DPsi)
Derivatives of 1D shape functions specialised to linear order (2 Nodes)
template<> void d2shape< 2 > (const double &s, double *DPsi)
Second Derivatives of 1D shape functions, specialised to linear order (2 Nodes)
template<> void shape< 3 > (const double &s, double *Psi)
1D shape functions specialised to quadratic order (3 Nodes)
template<> void dshape< 3 > (const double &s, double *DPsi)
Derivatives of 1D shape functions specialised to quadratic order (3 Nodes)
template<> void d2shape< 3 > (const double &s, double *DPsi)
Second Derivatives of 1D shape functions, specialised to quadratic order (3 Nodes)
template<> void shape< 4 > (const double &s, double *Psi)
1D shape functions specialised to cubic order (4 Nodes)
template<> void dshape< 4 > (const double &s, double *DPsi)
Derivatives of 1D shape functions specialised to cubic order (4 Nodes)
template<> void d2shape< 4 > (const double &s, double *DPsi)
Second derivatives of 1D shape functions specialised to cubic order (4 nodes)
Detailed Description
One dimensional shape functions and derivatives. Empty -- simply establishes the template parameters.
Function Documentation
d2shape()
template<unsigned NNODE_1D>
void oomph::OneDimDiscontinuousGalerkinMixedOrderTest::d2shape (const double & s, double * DPsi)
Definition for second derivatives of 1D Lagrange shape functions. The value of all the shape function derivatives at the local coordinate s are returned in the array DPsi.
Definition at line 1077 of file shape.h.
d2shape< 2 >()
template<>
void oomph::OneDimDiscontinuousGalerkinMixedOrderTest::d2shape< 2 > (const double & s, double * DPsi) [inline]
Second Derivatives of 1D shape functions, specialised to linear order (2 Nodes)
Definition at line 1114 of file shape.h.
d2shape< 3 >()
template<>
void oomph::OneDimDiscontinuousGalerkinMixedOrderTest::d2shape< 3 > (const double & s, double * DPsi) [inline]
Second Derivatives of 1D shape functions, specialised to quadratic order (3 Nodes)
Definition at line 1144 of file shape.h.
d2shape< 4 >()
template<>
void oomph::OneDimDiscontinuousGalerkinMixedOrderTest::d2shape< 4 > (const double & s, double * DPsi) [inline]
Second derivatives of 1D shape functions specialised to cubic order (4 nodes)
Definition at line 1175 of file shape.h.
dshape()
template<unsigned NNODE_1D>
void oomph::OneDimDiscontinuousGalerkinMixedOrderTest::dshape (const double & s, double * DPsi)
Definition for derivatives of 1D Lagrange shape functions. The value of all the shape function derivatives at the local coordinate s are returned in the array DPsi.
Definition at line 1057 of file shape.h.
dshape< 2 >()
template<>
void oomph::OneDimDiscontinuousGalerkinMixedOrderTest::dshape< 2 > (const double & s, double * DPsi) [inline]
Derivatives of 1D shape functions specialised to linear order (2 Nodes)
Definition at line 1105 of file shape.h.
Referenced by oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::dptest_eulerian().
dshape< 3 >()
template<>
void oomph::OneDimDiscontinuousGalerkinMixedOrderTest::dshape< 3 > (const double & s, double * DPsi) [inline]
Derivatives of 1D shape functions specialised to quadratic order (3 Nodes)
Definition at line 1134 of file shape.h.
Referenced by oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::dtest_local_u_nst().
dshape< 4 >()
template<>
void oomph::OneDimDiscontinuousGalerkinMixedOrderTest::dshape< 4 > (const double & s, double * DPsi) [inline]
Derivatives of 1D shape functions specialised to cubic order (4 Nodes)
Definition at line 1164 of file shape.h.
shape()
template<unsigned NNODE_1D>
void oomph::OneDimDiscontinuousGalerkinMixedOrderTest::shape (const double & s, double * Psi)
Definition for 1D Lagrange shape functions. The value of all the shape functions at the local coordinate s are returned in the array Psi.
Definition at line 1038 of file shape.h.
shape< 2 >()
template<>
void oomph::OneDimDiscontinuousGalerkinMixedOrderTest::shape< 2 > (const double & s, double * Psi) [inline]
1D shape functions specialised to linear order (2 Nodes)
Definition at line 1097 of file shape.h.
Referenced by oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::dptest_eulerian(), and oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::ptest_nst().
shape< 3 >()
template<>
void oomph::OneDimDiscontinuousGalerkinMixedOrderTest::shape< 3 > (const double & s, double * Psi) [inline]
1D shape functions specialised to quadratic order (3 Nodes)
Definition at line 1124 of file shape.h.
Referenced by oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::dtest_local_u_nst(), and oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::shape_and_test_at_knot().
shape< 4 >()
template<>
void oomph::OneDimDiscontinuousGalerkinMixedOrderTest::shape< 4 > (const double & s, double * Psi) [inline]
1D shape functions specialised to cubic order (4 Nodes)
Definition at line 1153 of file shape.h.