oomph::OneDimHermite Namespace Reference
One Dimensional Hermite shape functions.
Functions
void shape (const double &s, double Psi[2][2])
Constructor sets the values of the shape functions at the position s.
void dshape (const double &s, double DPsi[2][2])
Derivatives of 1D Hermite shape functions.
void d2shape (const double &s, double DPsi[2][2])
Second derivatives of the Hermite shape functions.
Detailed Description
One Dimensional Hermite shape functions.
Function Documentation
d2shape()
void oomph::OneDimHermite::d2shape (const double & s, double DPsi[2][2]) [inline]
Second derivatives of the Hermite shape functions.
Definition at line 1226 of file shape.h.
References s.
Referenced by oomph::QHermiteElement< DIM - 1 >::d2shape_local().
dshape()
void oomph::OneDimHermite::dshape (const double & s, double DPsi[2][2]) [inline]
Derivatives of 1D Hermite shape functions.
Definition at line 1215 of file shape.h.
References s.
Referenced by oomph::QHermiteElement< DIM - 1 >::d2shape_local(), oomph::QHermiteElement< DIM - 1 >::dshape_local(), and oomph::DShape::operator=().
shape()
void oomph::OneDimHermite::shape (const double & s, double Psi[2][2]) [inline]
Constructor sets the values of the shape functions at the position s.
Definition at line 1203 of file shape.h.
References s.
Referenced by oomph::QHermiteElement< DIM - 1 >::d2shape_local(), oomph::QHermiteElement< DIM - 1 >::dshape_local(), oomph::Shape::operator=(), and oomph::QHermiteElement< DIM - 1 >::shape().