oomph::QElement1BulkCoordinateDerivatives Namespace Reference
Namespace for helper functions that calculate derivatives of the local coordinates in the bulk elements wrt the local coordinates in the face element.
Functions
void faces0 (const Vector< double > &s, DenseMatrix< double > &dsbulk_dsface, unsigned &interior_direction)
Function for both faces -- the bulk coordinate is fixed on both.
Detailed Description
Namespace for helper functions that calculate derivatives of the local coordinates in the bulk elements wrt the local coordinates in the face element.
Function Documentation
faces0()
void oomph::QElement1BulkCoordinateDerivatives::faces0 (const Vector< double > & s, DenseMatrix< double > & dsbulk_dsface, unsigned & interior_direction)
Function for both faces -- the bulk coordinate is fixed on both.
Definition at line 59 of file Qelement_face_coordinate_translation_schemes.cc.
Referenced by oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 1, NNODE_1D >::build_face_element(), and oomph::QElement< 1, NNODE_1D >::bulk_coordinate_derivatives_fct_pt().