oomph::BrokenCopy Namespace Reference
Functions
void broken_assign (const std::string &class_name)
Issue error message and terminate execution.
void broken_copy (const std::string &class_name)
Issue error message and terminate execution.
Detailed Description
Namespace for error messages for broken copy constructors and assignment operators
Function Documentation
broken_assign()
void oomph::BrokenCopy::broken_assign (const std::string & class_name)
Issue error message and terminate execution.
Definition at line 197 of file oomph_utilities.cc.
References oomph::Global_string_for_annotation::string().
Referenced by oomph::ErrorEstimator::operator=(), oomph::GeompackQuadScaffoldMesh::operator=(), oomph::SuperLUPreconditioner::operator=(), oomph::LineMeshBase::operator=(), oomph::MatrixBasedDiagPreconditioner::operator=(), oomph::RefineableLinearWaveEquations< DIM >::operator=(), oomph::Integral::operator=(), oomph::ComplexMatrixBase::operator=(), oomph::Preconditioner::operator=(), oomph::RefineableLineMesh< oomph::SpectralPeriodicOrbitElement< NNODE_1D > >::operator=(), SamplePoint::operator=(), oomph::EighthSphereDomain::operator=(), oomph::AnnularDomain::operator=(), oomph::QHermiteElementBase::operator=(), oomph::QuadMeshBase::operator=(), oomph::AxisymFoepplvonKarmanEquations::operator=(), oomph::MatrixVectorProduct::operator=(), oomph::MumpsSolver::operator=(), oomph::RefineablePoissonEquations< DIM >::operator=(), oomph::LinearWaveEquations< DIM >::operator=(), oomph::PeriodicOrbitTimeDiscretisation::operator=(), oomph::RefineableAdvectionDiffusionEquations< DIM >::operator=(), oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::operator=(), oomph::RefineableSphericalAdvectionDiffusionEquations::operator=(), oomph::RefineableYoungLaplaceEquations::operator=(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::operator=(), oomph::FSIFluidElement::operator=(), oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::operator=(), oomph::TriangleScaffoldMesh::operator=(), oomph::ExplicitTimeSteppableObject::operator=(), oomph::TPoissonElement< DIM, NNODE_1D >::operator=(), oomph::GeneralisedTimeStepper::operator=(), oomph::PoissonFluxElement< ELEMENT >::operator=(), oomph::QuarterPipeDomain::operator=(), oomph::RefineableBrickMesh< ELEMENT >::operator=(), oomph::ExtrudedDomain::operator=(), oomph::QuarterTubeDomain::operator=(), oomph::QuarterCircleSectorDomain::operator=(), oomph::TFoepplvonKarmanElement< NNODE_1D >::operator=(), oomph::TWomersleyElement< DIM, NNODE_1D >::operator=(), oomph::LinearWaveFluxElement< ELEMENT >::operator=(), oomph::FishDomain::operator=(), oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >::operator=(), oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >::operator=(), oomph::PoissonEquations< DIM >::operator=(), oomph::Domain::operator=(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::operator=(), oomph::ElementWithExternalElement::operator=(), oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::operator=(), oomph::AdvectionDiffusionEquations< DIM >::operator=(), oomph::SphericalAdvectionDiffusionEquations::operator=(), oomph::AdvectionDiffusionFluxElement< ELEMENT >::operator=(), oomph::Tree::operator=(), oomph::TopologicallyRectangularDomain::operator=(), oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::operator=(), oomph::YoungLaplaceEquations::operator=(), oomph::FoepplvonKarmanEquations::operator=(), oomph::Time::operator=(), oomph::SamplePointContainerParameters::operator=(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::operator=(), oomph::IterativeLinearSolver::operator=(), oomph::ExtrudedMacroElement::operator=(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::operator=(), oomph::ExactDGPBlockPreconditioner< MATRIX >::operator=(), oomph::DisplacementBasedFoepplvonKarmanEquations::operator=(), oomph::BinaryTree::operator=(), oomph::ElementWithMovingNodes::operator=(), oomph::RefineableMeshBase::operator=(), oomph::FullCircleDomain::operator=(), oomph::MacroElement::operator=(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::operator=(), oomph::LinearSolver::operator=(), oomph::ElementWithZ2ErrorEstimator::operator=(), oomph::TubeDomain::operator=(), oomph::QuadTree::operator=(), oomph::OcTree::operator=(), oomph::SolidICProblem::operator=(), oomph::MatrixBasedLumpedPreconditioner< oomph::CRDoubleMatrix >::operator=(), oomph::Matrix< double, CCMatrix< double > >::operator=(), oomph::PointIntegral::operator=(), oomph::MapMatrixMixed< unsigned, unsigned, oomph::CRDoubleMatrix * >::operator=(), oomph::PreconditionerArray::operator=(), oomph::StorableShapeElementBase::operator=(), oomph::BiharmonicFluxElement< DIM >::operator=(), oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::operator=(), oomph::QHermiteElement< DIM-1 >::operator=(), RefineableBin::operator=(), oomph::GeneralPurposeBlockPreconditioner< MATRIX >::operator=(), oomph::BiharmonicPreconditioner::operator=(), oomph::HSL_MA42::operator=(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::operator=(), oomph::ContinuationStorageScheme::operator=(), oomph::ExplicitTimeStepper::operator=(), oomph::GeomObject::operator=(), oomph::QExtrudedMacroElement< 3 >::operator=(), oomph::Euler::operator=(), oomph::RefineableQYoungLaplaceElement< NNODE_1D >::operator=(), oomph::RefineableQLinearWaveElement< DIM, NNODE_1D >::operator=(), oomph::Gauss< 1, 2 >::operator=(), oomph::RefineableElement::operator=(), oomph::RefineableQPoissonElement< DIM, NNODE_1D >::operator=(), oomph::DenseComplexMatrix::operator=(), oomph::MacroElementNodeUpdateElementBase::operator=(), oomph::LagrangeEnforcedFlowPreconditioner::operator=(), oomph::DisplacementControlElement::operator=(), oomph::WomersleyEquations< DIM >::operator=(), oomph::RungeKutta< ORDER >::operator=(), oomph::RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::operator=(), oomph::Data::operator=(), oomph::RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::operator=(), oomph::FSIWallElement::operator=(), oomph::ExactSubBiharmonicPreconditioner::operator=(), oomph::Gauss< 1, 3 >::operator=(), oomph::AddedMainNumberingLookup::operator=(), oomph::HypreInterface::operator=(), oomph::LowStorageRungeKutta< ORDER >::operator=(), SamplePointContainer::operator=(), oomph::IdentityPreconditioner::operator=(), oomph::BinaryTreeRoot::operator=(), oomph::CGALSamplePointContainerParameters::operator=(), oomph::BandedBlockTriangularPreconditioner< MATRIX >::operator=(), oomph::NewMumpsPreconditioner::operator=(), oomph::PRefineableQPoissonElement< DIM >::operator=(), oomph::PseudoBucklingRing::operator=(), oomph::CG< MATRIX >::operator=(), oomph::RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::operator=(), oomph::EBDF3::operator=(), oomph::DoubleMatrixBase::operator=(), oomph::Gauss< 1, 4 >::operator=(), oomph::ILUZeroPreconditioner< CCDoubleMatrix >::operator=(), oomph::BinArrayParameters::operator=(), oomph::TimeStepper::operator=(), oomph::GMRESBlockPreconditioner::operator=(), oomph::SumOfMatrices::operator=(), oomph::BinaryTreeForest::operator=(), oomph::QMacroElement< 2 >::operator=(), oomph::CRComplexMatrix::operator=(), oomph::TR::operator=(), oomph::TreeRoot::operator=(), oomph::ComplexDampedJacobi< MATRIX >::operator=(), oomph::Z2ErrorEstimator::operator=(), oomph::DenseLU::operator=(), oomph::Gauss< 2, 2 >::operator=(), oomph::QuadTreeRoot::operator=(), oomph::InexactSubBiharmonicPreconditioner::operator=(), oomph::WarpedCubeDomain::operator=(), oomph::TrilinosAztecOOSolver::operator=(), oomph::ILUZeroPreconditioner< CRDoubleMatrix >::operator=(), oomph::BlockDiagonalPreconditioner< MATRIX >::operator=(), oomph::RefineableQAdvectionDiffusionElement< DIM, 3 >::operator=(), oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >::operator=(), oomph::TreeBasedRefineableMeshBase::operator=(), oomph::RefineableBinArrayParameters::operator=(), oomph::MeshAsGeomObject::operator=(), oomph::StorableShapeSolidElementBase::operator=(), oomph::Gauss< 2, 3 >::operator=(), oomph::Mesh::operator=(), oomph::TreeForest::operator=(), oomph::BiCGStab< MATRIX >::operator=(), oomph::WarpedCircularDisk::operator=(), oomph::QMacroElement< 3 >::operator=(), oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::operator=(), oomph::QuadTreeForest::operator=(), oomph::QLinearWaveElement< DIM, NNODE_1D >::operator=(), oomph::CCComplexMatrix::operator=(), oomph::FD_LU::operator=(), oomph::Gauss< 2, 4 >::operator=(), BinArray::operator=(), oomph::DistributableLinearAlgebraObject::operator=(), oomph::Gauss< 3, 2 >::operator=(), oomph::QYoungLaplaceElement< NNODE_1D >::operator=(), oomph::DiagQHermiteElement< DIM >::operator=(), oomph::StraightLine::operator=(), oomph::QFoepplvonKarmanElement< NNODE_1D >::operator=(), oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >::operator=(), oomph::BlockTriangularPreconditioner< MATRIX >::operator=(), oomph::QuadFromTriangleMesh< ELEMENT >::operator=(), oomph::BlockPreconditioner< CRDoubleMatrix >::operator=(), oomph::NonRefineableBinArrayParameters::operator=(), oomph::ShapeWithDeepCopy::operator=(), oomph::SuperLUSolver::operator=(), oomph::AlgebraicElementBase::operator=(), oomph::Gauss< 3, 3 >::operator=(), oomph::SolidQHermiteElement< 2 >::operator=(), oomph::StorableShapeElement< ELEMENT >::operator=(), oomph::HypreSolver::operator=(), oomph::HijackedData::operator=(), RefineableBinArray::operator=(), oomph::MapMatrix< unsigned, oomph::CRDoubleMatrix * >::operator=(), oomph::QPoissonElement< DIM, 2 >::operator=(), oomph::ExactBlockPreconditioner< MATRIX >::operator=(), oomph::Gauss< 3, 4 >::operator=(), oomph::StorableShapeSolidElement< ELEMENT >::operator=(), oomph::PRefineableElement::operator=(), oomph::SparseMatrix< double, CCMatrix< double > >::operator=(), oomph::DummyErrorEstimator::operator=(), oomph::QAdvectionDiffusionElement< DIM, 3 >::operator=(), oomph::WarpedCircularDiskWithAnnularInternalBoundary::operator=(), oomph::SolidDiagQHermiteElement< 2 >::operator=(), oomph::GeneralisedElement::operator=(), oomph::GS< MATRIX >::operator=(), oomph::CopiedData::operator=(), oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::operator=(), oomph::Gauss_Rescaled< DIM, NPTS_1D >::operator=(), oomph::ClampedHermiteShellBoundaryConditionElement::operator=(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::operator=(), oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::operator=(), oomph::DummyBlockPreconditioner< MATRIX >::operator=(), oomph::Steady< 0 >::operator=(), oomph::OcTreeRoot::operator=(), oomph::PseudoBucklingRingElement::operator=(), oomph::QWomersleyElement< DIM, NNODE_1D >::operator=(), oomph::TetMeshBase::operator=(), oomph::TGauss< 1, 2 >::operator=(), oomph::Ellipse::operator=(), oomph::HangInfo::operator=(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::operator=(), oomph::CRMatrix< std::complex< double > >::operator=(), oomph::TGauss< 1, 3 >::operator=(), oomph::MGPreconditioner< DIM >::operator=(), oomph::TGauss< 1, 4 >::operator=(), oomph::HyprePreconditioner::operator=(), oomph::TriangleMesh< ELEMENT >::operator=(), oomph::GS< CRDoubleMatrix >::operator=(), oomph::TGauss< 1, 5 >::operator=(), NonRefineableBinArray::operator=(), oomph::TGauss< 2, 2 >::operator=(), oomph::Newmark< NSTEPS >::operator=(), oomph::CRDoubleMatrix::operator=(), oomph::ComplexGMRES< MATRIX >::operator=(), oomph::OcTreeForest::operator=(), oomph::TGauss< 2, 3 >::operator=(), oomph::Node::operator=(), oomph::TGauss< 2, 4 >::operator=(), oomph::Circle::operator=(), oomph::TGauss< 2, 13 >::operator=(), oomph::DampedJacobi< MATRIX >::operator=(), oomph::NewmarkBDF< NSTEPS >::operator=(), oomph::TGauss< 2, 9 >::operator=(), CGALSamplePointContainer::operator=(), oomph::TGauss< 2, 16 >::operator=(), oomph::EllipticalTube::operator=(), oomph::TGauss< 2, 5 >::operator=(), oomph::BDF< NSTEPS >::operator=(), oomph::TGauss< 3, 2 >::operator=(), oomph::Problem::operator=(), oomph::DenseDoubleMatrix::operator=(), oomph::TGauss< 3, 3 >::operator=(), oomph::GMRES< MATRIX >::operator=(), oomph::TGauss< 3, 5 >::operator=(), oomph::UnstructuredTwoDMeshGeometryBase::operator=(), oomph::SolidNode::operator=(), oomph::AugmentedProblemGMRES::operator=(), oomph::HelmholtzGMRESMG< MATRIX >::operator=(), oomph::VorticitySmoother< ELEMENT >::operator=(), oomph::BoundaryNodeBase::operator=(), oomph::BoundaryNode< NODE_TYPE >::operator=(), oomph::CCMatrix< std::complex< double > >::operator=(), oomph::SolidMesh::operator=(), oomph::CCDoubleMatrix::operator=(), oomph::NetFluxControlElementForWomersleyPressureControl::operator=(), oomph::HelmholtzFGMRESMG< MATRIX >::operator=(), oomph::SolidInitialCondition::operator=(), oomph::BellElement< DIM, NNODE_1D >::operator=(), oomph::SolidElementWithDiagonalMassMatrix::operator=(), oomph::NavierStokesElementWithDiagonalMassMatrices::operator=(), oomph::C1CurvedElement< 2, NNODE_1D >::operator=(), and oomph::ComplexDampedJacobi< MATRIX >::solve().
broken_copy()
void oomph::BrokenCopy::broken_copy (const std::string & class_name)
Issue error message and terminate execution.
Definition at line 214 of file oomph_utilities.cc.
References oomph::Global_string_for_annotation::string().
Referenced by oomph::AddedMainNumberingLookup::AddedMainNumberingLookup(), oomph::AdvectionDiffusionEquations< DIM >::AdvectionDiffusionEquations(), oomph::AdvectionDiffusionFluxElement< ELEMENT >::AdvectionDiffusionFluxElement(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::AdvectionDiffusionReactionEquations(), oomph::AlgebraicElement< ELEMENT >::AlgebraicElement(), oomph::AlgebraicElementBase::AlgebraicElementBase(), oomph::AlgebraicMesh::AlgebraicMesh(), oomph::AlgebraicNode::AlgebraicNode(), oomph::AnnularDomain::AnnularDomain(), oomph::AugmentedProblemGMRES::AugmentedProblemGMRES(), oomph::AxisymAdvectionDiffusionEquations::AxisymAdvectionDiffusionEquations(), oomph::AxisymFoepplvonKarmanElement< NNODE_1D >::AxisymFoepplvonKarmanElement(), oomph::AxisymFoepplvonKarmanEquations::AxisymFoepplvonKarmanEquations(), oomph::AxisymmetricTCrouzeixRaviartElement::AxisymmetricTCrouzeixRaviartElement(), oomph::AxisymmetricTTaylorHoodElement::AxisymmetricTTaylorHoodElement(), oomph::BandedBlockTriangularPreconditioner< MATRIX >::BandedBlockTriangularPreconditioner(), oomph::BDF< NSTEPS >::BDF(), oomph::BellElement< DIM, NNODE_1D >::BellElement(), oomph::BiCGStab< MATRIX >::BiCGStab(), oomph::BiharmonicFluxElement< DIM >::BiharmonicFluxElement(), oomph::BiharmonicPreconditioner::BiharmonicPreconditioner(), BinArray::BinArray(), oomph::BinArrayParameters::BinArrayParameters(), oomph::BinaryTree::BinaryTree(), oomph::BinaryTreeForest::BinaryTreeForest(), oomph::BinaryTreeRoot::BinaryTreeRoot(), oomph::BlockDiagonalPreconditioner< MATRIX >::BlockDiagonalPreconditioner(), oomph::BlockPreconditioner< CRDoubleMatrix >::BlockPreconditioner(), oomph::BlockTriangularPreconditioner< MATRIX >::BlockTriangularPreconditioner(), oomph::BoundaryNode< NODE_TYPE >::BoundaryNode(), oomph::BoundaryNodeBase::BoundaryNodeBase(), oomph::BrickMeshBase::BrickMeshBase(), oomph::C1CurvedElement< 2, NNODE_1D >::C1CurvedElement(), oomph::CCComplexMatrix::CCComplexMatrix(), oomph::CCDoubleMatrix::CCDoubleMatrix(), oomph::CG< MATRIX >::CG(), CGALSamplePointContainer::CGALSamplePointContainer(), oomph::CGALSamplePointContainerParameters::CGALSamplePointContainerParameters(), oomph::Circle::Circle(), oomph::ClampedHermiteShellBoundaryConditionElement::ClampedHermiteShellBoundaryConditionElement(), oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::ClampedSlidingHermiteBeamBoundaryConditionElement(), oomph::ComplexDampedJacobi< MATRIX >::ComplexDampedJacobi(), oomph::ComplexGMRES< MATRIX >::ComplexGMRES(), oomph::ComplexMatrixBase::ComplexMatrixBase(), oomph::ContinuationStorageScheme::ContinuationStorageScheme(), oomph::CRComplexMatrix::CRComplexMatrix(), oomph::DampedJacobi< MATRIX >::DampedJacobi(), oomph::Data::Data(), oomph::DenseComplexMatrix::DenseComplexMatrix(), oomph::DenseDoubleMatrix::DenseDoubleMatrix(), oomph::DenseLU::DenseLU(), oomph::DiagQHermiteElement< DIM >::DiagQHermiteElement(), oomph::DisplacementBasedFoepplvonKarmanEquations::DisplacementBasedFoepplvonKarmanEquations(), oomph::DisplacementControlElement::DisplacementControlElement(), oomph::DistributableLinearAlgebraObject::DistributableLinearAlgebraObject(), oomph::Domain::Domain(), oomph::DoubleMatrixBase::DoubleMatrixBase(), oomph::DShape::DShape(), oomph::DummyAlgebraicMesh::DummyAlgebraicMesh(), oomph::DummyBlockPreconditioner< MATRIX >::DummyBlockPreconditioner(), oomph::DummyBrickElement::DummyBrickElement(), oomph::DummyErrorEstimator::DummyErrorEstimator(), oomph::EBDF3::EBDF3(), oomph::EighthSphereDomain::EighthSphereDomain(), oomph::ElementWithExternalElement::ElementWithExternalElement(), oomph::ElementWithMovingNodes::ElementWithMovingNodes(), oomph::ElementWithZ2ErrorEstimator::ElementWithZ2ErrorEstimator(), oomph::Ellipse::Ellipse(), oomph::EllipticalTube::EllipticalTube(), oomph::ErrorEstimator::ErrorEstimator(), oomph::Euler::Euler(), oomph::ExactBlockPreconditioner< MATRIX >::ExactBlockPreconditioner(), oomph::ExactDGPBlockPreconditioner< MATRIX >::ExactDGPBlockPreconditioner(), oomph::ExactSubBiharmonicPreconditioner::ExactSubBiharmonicPreconditioner(), oomph::ExplicitTimeSteppableObject::ExplicitTimeSteppableObject(), oomph::ExplicitTimeStepper::ExplicitTimeStepper(), oomph::ExtrudedDomain::ExtrudedDomain(), oomph::ExtrudedMacroElement::ExtrudedMacroElement(), oomph::FaceElement::FaceElement(), oomph::FaceElementAsGeomObject< ELEMENT >::FaceElementAsGeomObject(), oomph::FD_LU::FD_LU(), oomph::FiniteElement::FiniteElement(), oomph::FishDomain::FishDomain(), oomph::FoepplvonKarmanEquations::FoepplvonKarmanEquations(), oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::FoepplvonKarmanVolumeConstraintElement(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::FourierDecomposedHelmholtzBCElementBase(), oomph::FourierDecomposedHelmholtzEquations::FourierDecomposedHelmholtzEquations(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::FourierDecomposedHelmholtzFluxElement(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement(), oomph::FSIFluidElement::FSIFluidElement(), oomph::FSIPreconditioner::FSIPreconditioner(), oomph::FSIWallElement::FSIWallElement(), oomph::FullCircleDomain::FullCircleDomain(), oomph::Gauss< 1, 2 >::Gauss(), oomph::Gauss< 1, 3 >::Gauss(), oomph::Gauss< 1, 4 >::Gauss(), oomph::Gauss< 2, 2 >::Gauss(), oomph::Gauss< 2, 3 >::Gauss(), oomph::Gauss< 2, 4 >::Gauss(), oomph::Gauss< 3, 2 >::Gauss(), oomph::Gauss< 3, 3 >::Gauss(), oomph::Gauss< 3, 4 >::Gauss(), oomph::Gauss_Rescaled< DIM, NPTS_1D >::Gauss_Rescaled(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::GeneralisedAdvectionDiffusionEquations(), oomph::GeneralisedElement::GeneralisedElement(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::GeneralisedNewtonianAxisymmetricTTaylorHoodElement(), oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::GeneralisedNewtonianTCrouzeixRaviartElement(), oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::GeneralisedNewtonianTTaylorHoodElement(), oomph::GeneralisedTimeStepper::GeneralisedTimeStepper(), oomph::GeneralPurposeBlockPreconditioner< MATRIX >::GeneralPurposeBlockPreconditioner(), oomph::GeomObject::GeomObject(), oomph::GeompackQuadScaffoldMesh::GeompackQuadScaffoldMesh(), oomph::GMRES< MATRIX >::GMRES(), oomph::GMRESBlockPreconditioner::GMRESBlockPreconditioner(), oomph::GS< MATRIX >::GS(), oomph::GS< CRDoubleMatrix >::GS(), oomph::HangInfo::HangInfo(), oomph::HelmholtzBCElementBase< ELEMENT >::HelmholtzBCElementBase(), oomph::HelmholtzEquations< DIM >::HelmholtzEquations(), oomph::HelmholtzFGMRESMG< MATRIX >::HelmholtzFGMRESMG(), oomph::HelmholtzFluxElement< ELEMENT >::HelmholtzFluxElement(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::HelmholtzFluxFromNormalDisplacementBCElement(), oomph::HelmholtzGMRESMG< MATRIX >::HelmholtzGMRESMG(), oomph::HSL_MA42::HSL_MA42(), oomph::HypreInterface::HypreInterface(), oomph::HyprePreconditioner::HyprePreconditioner(), oomph::HypreSolver::HypreSolver(), oomph::IdentityPreconditioner::IdentityPreconditioner(), oomph::ILUZeroPreconditioner< CCDoubleMatrix >::ILUZeroPreconditioner(), oomph::ILUZeroPreconditioner< CRDoubleMatrix >::ILUZeroPreconditioner(), oomph::InexactSubBiharmonicPreconditioner::InexactSubBiharmonicPreconditioner(), oomph::Integral::Integral(), oomph::IterativeLinearSolver::IterativeLinearSolver(), oomph::LagrangeEnforcedFlowPreconditioner::LagrangeEnforcedFlowPreconditioner(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::LinearisedAxisymPoroelasticBJS_FSIElement(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::LinearisedFSIAxisymmetricNStNoSlipBCElementElement(), oomph::LinearSolver::LinearSolver(), oomph::LinearWaveEquations< DIM >::LinearWaveEquations(), oomph::LinearWaveFluxElement< ELEMENT >::LinearWaveFluxElement(), oomph::LineMeshBase::LineMeshBase(), oomph::LowStorageRungeKutta< ORDER >::LowStorageRungeKutta(), oomph::MacroElement::MacroElement(), oomph::MacroElementNodeUpdateElement< ELEMENT >::MacroElementNodeUpdateElement(), oomph::MacroElementNodeUpdateElementBase::MacroElementNodeUpdateElementBase(), oomph::MacroElementNodeUpdateMesh::MacroElementNodeUpdateMesh(), oomph::MacroElementNodeUpdateNode::MacroElementNodeUpdateNode(), oomph::Matrix< double, CCMatrix< double > >::Matrix(), oomph::MatrixBasedDiagPreconditioner::MatrixBasedDiagPreconditioner(), oomph::MatrixBasedLumpedPreconditioner< oomph::CRDoubleMatrix >::MatrixBasedLumpedPreconditioner(), oomph::MatrixVectorProduct::MatrixVectorProduct(), oomph::Mesh::Mesh(), oomph::MeshAsGeomObject::MeshAsGeomObject(), oomph::MGPreconditioner< DIM >::MGPreconditioner(), oomph::MumpsSolver::MumpsSolver(), oomph::NavierStokesElementWithDiagonalMassMatrices::NavierStokesElementWithDiagonalMassMatrices(), oomph::NavierStokesExactPreconditioner< MATRIX >::NavierStokesExactPreconditioner(), oomph::NavierStokesSchurComplementPreconditioner::NavierStokesSchurComplementPreconditioner(), oomph::NetFluxControlElement::NetFluxControlElement(), oomph::NetFluxControlElementForWomersleyPressureControl::NetFluxControlElementForWomersleyPressureControl(), oomph::Newmark< NSTEPS >::Newmark(), oomph::NewmarkBDF< NSTEPS >::NewmarkBDF(), oomph::NewMumpsPreconditioner::NewMumpsPreconditioner(), oomph::Node::Node(), NonRefineableBinArray::NonRefineableBinArray(), oomph::NonRefineableBinArrayParameters::NonRefineableBinArrayParameters(), oomph::OcTree::OcTree(), oomph::OcTreeForest::OcTreeForest(), oomph::OcTreeRoot::OcTreeRoot(), oomph::OomphLibPreconditionerEpetraOperator::OomphLibPreconditionerEpetraOperator(), oomph::PeriodicOrbitEquations::PeriodicOrbitEquations(), oomph::PeriodicOrbitTimeDiscretisation::PeriodicOrbitTimeDiscretisation(), oomph::PMLFourierDecomposedHelmholtzEquations::PMLFourierDecomposedHelmholtzEquations(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::PMLFourierDecomposedHelmholtzFluxElement(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::PMLFourierDecomposedHelmholtzPowerMonitorElement(), oomph::PMLHelmholtzEquations< DIM >::PMLHelmholtzEquations(), oomph::PMLHelmholtzFluxElement< ELEMENT >::PMLHelmholtzFluxElement(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::PMLHelmholtzFluxFromNormalDisplacementBCElement(), oomph::PMLHelmholtzPowerElement< ELEMENT >::PMLHelmholtzPowerElement(), oomph::PointElement::PointElement(), oomph::PointIntegral::PointIntegral(), oomph::PoissonEquations< DIM >::PoissonEquations(), oomph::PoissonFluxElement< ELEMENT >::PoissonFluxElement(), oomph::Preconditioner::Preconditioner(), oomph::PreconditionerArray::PreconditionerArray(), oomph::PRefineableElement::PRefineableElement(), oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement(), oomph::PRefineableQCrouzeixRaviartElement< DIM >::PRefineableQCrouzeixRaviartElement(), oomph::PRefineableQLinearElasticityElement< DIM >::PRefineableQLinearElasticityElement(), oomph::PRefineableQPoissonElement< DIM >::PRefineableQPoissonElement(), oomph::PressureBasedSolidExactPreconditioner< MATRIX >::PressureBasedSolidExactPreconditioner(), oomph::PressureBasedSolidLSCPreconditioner::PressureBasedSolidLSCPreconditioner(), oomph::Problem::Problem(), oomph::PseudoBucklingRing::PseudoBucklingRing(), oomph::PseudoBucklingRingElement::PseudoBucklingRingElement(), oomph::PseudoElasticFSIPreconditioner::PseudoElasticFSIPreconditioner(), oomph::PseudoElasticPreconditioner::PseudoElasticPreconditioner(), oomph::PseudoElasticPreconditionerOld::PseudoElasticPreconditionerOld(), oomph::PseudoElasticPreconditionerScalingHelperOld::PseudoElasticPreconditionerScalingHelperOld(), oomph::PseudoElasticPreconditionerSubsidiaryBlockPreconditionerOld::PseudoElasticPreconditionerSubsidiaryBlockPreconditionerOld(), oomph::PseudoElasticPreconditionerSubsidiaryPreconditionerOld::PseudoElasticPreconditionerSubsidiaryPreconditionerOld(), oomph::QAdvectionDiffusionElement< DIM, 3 >::QAdvectionDiffusionElement(), oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::QAdvectionDiffusionReactionElement(), oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >::QAxisymAdvectionDiffusionElement(), oomph::QElement< 1, NNODE_1D >::QElement(), oomph::QElement< 2, NNODE_1D >::QElement(), oomph::QElement< 3, NNODE_1D >::QElement(), oomph::QElementBase::QElementBase(), oomph::QElementGeometricBase::QElementGeometricBase(), oomph::QExtrudedMacroElement< 3 >::QExtrudedMacroElement(), oomph::QFoepplvonKarmanElement< NNODE_1D >::QFoepplvonKarmanElement(), oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >::QFourierDecomposedHelmholtzElement(), oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::QGeneralisedAdvectionDiffusionElement(), QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::QGeneralisedAxisymAdvectionDiffusionElement(), oomph::QHelmholtzElement< DIM, NNODE_1D >::QHelmholtzElement(), oomph::QHermiteElement< DIM-1 >::QHermiteElement(), oomph::QHermiteElementBase::QHermiteElementBase(), oomph::QLinearWaveElement< DIM, NNODE_1D >::QLinearWaveElement(), oomph::QMacroElement< 2 >::QMacroElement(), oomph::QMacroElement< 3 >::QMacroElement(), oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >::QPMLFourierDecomposedHelmholtzElement(), oomph::QPMLHelmholtzElement< 2, NNODE_1D >::QPMLHelmholtzElement(), oomph::QPoissonElement< DIM, 2 >::QPoissonElement(), oomph::QScalarAdvectionElement< 2, NNODE_1D >::QScalarAdvectionElement(), oomph::QSolidElementBase::QSolidElementBase(), oomph::QSpectralEulerElement< 2, NNODE_1D >::QSpectralEulerElement(), oomph::QSpectralPoissonElement< DIM, NNODE_1D >::QSpectralPoissonElement(), oomph::QSpectralScalarAdvectionElement< 2, NNODE_1D >::QSpectralScalarAdvectionElement(), oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >::QSphericalAdvectionDiffusionElement(), oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >::QSteadyAxisymAdvectionDiffusionElement(), oomph::QuadFromTriangleMesh< ELEMENT >::QuadFromTriangleMesh(), oomph::QuadMeshBase::QuadMeshBase(), oomph::QuadTree::QuadTree(), oomph::QuadTreeForest::QuadTreeForest(), oomph::QuadTreeRoot::QuadTreeRoot(), oomph::QuarterCircleSectorDomain::QuarterCircleSectorDomain(), oomph::QuarterPipeDomain::QuarterPipeDomain(), oomph::QuarterTubeDomain::QuarterTubeDomain(), oomph::QUnsteadyHeatElement< DIM, NNODE_1D >::QUnsteadyHeatElement(), oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::QUnsteadyHeatMixedOrderSpaceTimeElement(), oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::QUnsteadyHeatSpaceTimeElement(), oomph::QWomersleyElement< DIM, NNODE_1D >::QWomersleyElement(), oomph::QYoungLaplaceElement< NNODE_1D >::QYoungLaplaceElement(), oomph::RefineableAdvectionDiffusionEquations< DIM >::RefineableAdvectionDiffusionEquations(), oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::RefineableAdvectionDiffusionReactionEquations(), oomph::RefineableAxisymAdvectionDiffusionEquations::RefineableAxisymAdvectionDiffusionEquations(), RefineableBin::RefineableBin(), RefineableBinArray::RefineableBinArray(), oomph::RefineableBinArrayParameters::RefineableBinArrayParameters(), oomph::RefineableBrickMesh< ELEMENT >::RefineableBrickMesh(), oomph::RefineableElement::RefineableElement(), oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::RefineableGeneralisedAdvectionDiffusionEquations(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::RefineableGeneralisedAxisymAdvectionDiffusionEquations(), oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::RefineableGeneralisedNewtonianQCrouzeixRaviartElement(), oomph::RefineableHelmholtzEquations< DIM >::RefineableHelmholtzEquations(), oomph::RefineableLinearWaveEquations< DIM >::RefineableLinearWaveEquations(), oomph::RefineableLineMesh< oomph::SpectralPeriodicOrbitElement< NNODE_1D > >::RefineableLineMesh(), oomph::RefineableMeshBase::RefineableMeshBase(), oomph::RefineablePMLHelmholtzEquations< DIM >::RefineablePMLHelmholtzEquations(), oomph::RefineablePoissonEquations< DIM >::RefineablePoissonEquations(), oomph::RefineableQAdvectionDiffusionElement< DIM, 3 >::RefineableQAdvectionDiffusionElement(), oomph::RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::RefineableQAdvectionDiffusionReactionElement(), oomph::RefineableQAxisymAdvectionDiffusionElement< NNODE_1D >::RefineableQAxisymAdvectionDiffusionElement(), oomph::RefineableQCrouzeixRaviartElement< DIM >::RefineableQCrouzeixRaviartElement(), oomph::RefineableQElement< 3 >::RefineableQElement(), oomph::RefineableQElement< 1 >::RefineableQElement(), oomph::RefineableQElement< 2 >::RefineableQElement(), oomph::RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >::RefineableQGeneralisedAdvectionDiffusionElement(), oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::RefineableQGeneralisedAxisymAdvectionDiffusionElement(), oomph::RefineableQHelmholtzElement< DIM, NNODE_1D >::RefineableQHelmholtzElement(), oomph::RefineableQLinearWaveElement< DIM, NNODE_1D >::RefineableQLinearWaveElement(), oomph::RefineableQPMLHelmholtzElement< 2, NNODE_1D >::RefineableQPMLHelmholtzElement(), oomph::RefineableQPoissonElement< DIM, NNODE_1D >::RefineableQPoissonElement(), oomph::RefineableQSpectralElement< 2 >::RefineableQSpectralElement(), oomph::RefineableQSpectralElement< 3 >::RefineableQSpectralElement(), oomph::RefineableQSpectralElement< 1 >::RefineableQSpectralElement(), oomph::RefineableQSpectralPoissonElement< DIM, NNODE_1D >::RefineableQSpectralPoissonElement(), oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >::RefineableQSphericalAdvectionDiffusionElement(), oomph::RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::RefineableQSUPGAdvectionDiffusionElement(), oomph::RefineableQuadMesh< ELEMENT >::RefineableQuadMesh(), oomph::RefineableQUnsteadyHeatElement< DIM, NNODE_1D >::RefineableQUnsteadyHeatElement(), oomph::RefineableQUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::RefineableQUnsteadyHeatMixedOrderSpaceTimeElement(), oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::RefineableQUnsteadyHeatSpaceTimeElement(), oomph::RefineableQYoungLaplaceElement< NNODE_1D >::RefineableQYoungLaplaceElement(), oomph::RefineableSolidQElement< 1 >::RefineableSolidQElement(), oomph::RefineableSolidQElement< 2 >::RefineableSolidQElement(), oomph::RefineableSolidQElement< 3 >::RefineableSolidQElement(), oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::RefineableSpaceTimeUnsteadyHeatEquations(), oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations(), oomph::RefineableSphericalAdvectionDiffusionEquations::RefineableSphericalAdvectionDiffusionEquations(), oomph::RefineableUnsteadyHeatEquations< DIM >::RefineableUnsteadyHeatEquations(), oomph::RefineableYoungLaplaceEquations::RefineableYoungLaplaceEquations(), oomph::RungeKutta< ORDER >::RungeKutta(), SamplePoint::SamplePoint(), SamplePointContainer::SamplePointContainer(), oomph::SamplePointContainerParameters::SamplePointContainerParameters(), oomph::Shape::Shape(), oomph::SimpleFSIPreconditioner< MATRIX >::SimpleFSIPreconditioner(), oomph::SolidDiagQHermiteElement< 2 >::SolidDiagQHermiteElement(), oomph::SolidElementWithDiagonalMassMatrix::SolidElementWithDiagonalMassMatrix(), oomph::SolidFiniteElement::SolidFiniteElement(), oomph::SolidICProblem::SolidICProblem(), oomph::SolidInitialCondition::SolidInitialCondition(), oomph::SolidMesh::SolidMesh(), oomph::SolidNode::SolidNode(), oomph::SolidQElement< 1, NNODE_1D >::SolidQElement(), oomph::SolidQElement< 2, NNODE_1D >::SolidQElement(), oomph::SolidQElement< 3, NNODE_1D >::SolidQElement(), oomph::SolidQHermiteElement< 2 >::SolidQHermiteElement(), oomph::SolidTBubbleEnrichedElement< DIM, 3 >::SolidTBubbleEnrichedElement(), oomph::SolidTElement< 1, NNODE_1D >::SolidTElement(), oomph::SolidTElement< 2, NNODE_1D >::SolidTElement(), oomph::SolidTElement< 3, NNODE_1D >::SolidTElement(), oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::SpaceTimeNavierStokesSubsidiaryPreconditioner(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::SpaceTimeUnsteadyHeatEquations(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::SpaceTimeUnsteadyHeatMixedOrderEquations(), oomph::SpectralPeriodicOrbitElement< NNODE_1D >::SpectralPeriodicOrbitElement(), oomph::SphericalAdvectionDiffusionEquations::SphericalAdvectionDiffusionEquations(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::SphericalAdvectionDiffusionFluxElement(), oomph::Steady< 0 >::Steady(), oomph::SteadyAxisymAdvectionDiffusionEquations::SteadyAxisymAdvectionDiffusionEquations(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::SteadyAxisymAdvectionDiffusionFluxElement(), oomph::StorableShapeElement< ELEMENT >::StorableShapeElement(), oomph::StorableShapeElementBase::StorableShapeElementBase(), oomph::StorableShapeSolidElement< ELEMENT >::StorableShapeSolidElement(), oomph::StorableShapeSolidElementBase::StorableShapeSolidElementBase(), oomph::StraightLine::StraightLine(), oomph::SumOfMatrices::SumOfMatrices(), oomph::SuperLUPreconditioner::SuperLUPreconditioner(), oomph::SuperLUSolver::SuperLUSolver(), oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::TAdvectionDiffusionReactionElement(), oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >::TAxisymmetricLinearElasticityElement(), oomph::TBubbleEnrichedElement< DIM, 3 >::TBubbleEnrichedElement(), oomph::TCrouzeixRaviartElement< DIM >::TCrouzeixRaviartElement(), oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::TDisplacementBasedFoepplvonKarmanElement(), oomph::TElement< 1, NNODE_1D >::TElement(), oomph::TElement< 2, NNODE_1D >::TElement(), oomph::TElement< 3, NNODE_1D >::TElement(), oomph::TElementBase::TElementBase(), oomph::TElementGeometricBase::TElementGeometricBase(), oomph::TetMeshBase::TetMeshBase(), oomph::TFoepplvonKarmanElement< NNODE_1D >::TFoepplvonKarmanElement(), oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >::TFourierDecomposedHelmholtzElement(), oomph::TGauss< 1, 2 >::TGauss(), oomph::TGauss< 1, 3 >::TGauss(), oomph::TGauss< 1, 4 >::TGauss(), oomph::TGauss< 1, 5 >::TGauss(), oomph::TGauss< 2, 2 >::TGauss(), oomph::TGauss< 2, 3 >::TGauss(), oomph::TGauss< 2, 4 >::TGauss(), oomph::TGauss< 2, 13 >::TGauss(), oomph::TGauss< 2, 9 >::TGauss(), oomph::TGauss< 2, 16 >::TGauss(), oomph::TGauss< 2, 5 >::TGauss(), oomph::TGauss< 3, 2 >::TGauss(), oomph::TGauss< 3, 3 >::TGauss(), oomph::TGauss< 3, 5 >::TGauss(), oomph::THelmholtzElement< DIM, NNODE_1D >::THelmholtzElement(), oomph::Time::Time(), oomph::TimeStepper::TimeStepper(), oomph::TLinearElasticityElement< DIM, NNODE_1D >::TLinearElasticityElement(), oomph::TopologicallyRectangularDomain::TopologicallyRectangularDomain(), oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >::TPMLFourierDecomposedHelmholtzElement(), oomph::TPMLHelmholtzElement< DIM, NNODE_1D >::TPMLHelmholtzElement(), oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >::TPMLTimeHarmonicLinearElasticityElement(), oomph::TPoissonElement< DIM, NNODE_1D >::TPoissonElement(), oomph::TPVDElementWithContinuousPressure< DIM >::TPVDElementWithContinuousPressure(), oomph::TR::TR(), oomph::Tree::Tree(), oomph::TreeBasedRefineableMesh< oomph::SpectralPeriodicOrbitElement< NNODE_1D > >::TreeBasedRefineableMesh(), oomph::TreeBasedRefineableMeshBase::TreeBasedRefineableMeshBase(), oomph::TreeForest::TreeForest(), oomph::TreeRoot::TreeRoot(), oomph::TriangleMesh< ELEMENT >::TriangleMesh(), oomph::TriangleMeshBase::TriangleMeshBase(), oomph::TriangleScaffoldMesh::TriangleScaffoldMesh(), oomph::TrilinosAztecOOSolver::TrilinosAztecOOSolver(), oomph::TrilinosIFPACKPreconditioner::TrilinosIFPACKPreconditioner(), oomph::TrilinosMLPreconditioner::TrilinosMLPreconditioner(), oomph::TrilinosPreconditionerBase::TrilinosPreconditionerBase(), oomph::TSolidElementBase::TSolidElementBase(), oomph::TTaylorHoodElement< DIM >::TTaylorHoodElement(), oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >::TTimeHarmonicLinearElasticityElement(), oomph::TubeDomain::TubeDomain(), oomph::TUnsteadyHeatElement< DIM, NNODE_1D >::TUnsteadyHeatElement(), oomph::TWomersleyElement< DIM, NNODE_1D >::TWomersleyElement(), oomph::UnsteadyHeatEquations< DIM >::UnsteadyHeatEquations(), oomph::UnsteadyHeatFluxElement< ELEMENT >::UnsteadyHeatFluxElement(), oomph::UnstructuredTwoDMeshGeometryBase::UnstructuredTwoDMeshGeometryBase(), oomph::VorticitySmoother< ELEMENT >::VorticitySmoother(), oomph::WarpedCircularDisk::WarpedCircularDisk(), oomph::WarpedCircularDiskWithAnnularInternalBoundary::WarpedCircularDiskWithAnnularInternalBoundary(), oomph::WarpedCubeDomain::WarpedCubeDomain(), oomph::WomersleyEquations< DIM >::WomersleyEquations(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::YoungLaplaceContactAngleElement(), oomph::YoungLaplaceEquations::YoungLaplaceEquations(), and oomph::Z2ErrorEstimator::Z2ErrorEstimator().