oomph::ObsoleteCode Namespace Reference
Namespace for flagging up obsolete parts of the code.
Functions
void obsolete ()
Output warning message.
void obsolete (const std::string &message)
Ouput a warning message with a string argument.
Variables
bool FlagObsoleteCode = true
Flag up obsolete parts of the code.
Detailed Description
Namespace for flagging up obsolete parts of the code.
Function Documentation
obsolete() [1/2]
void oomph::ObsoleteCode::obsolete ()
Output warning message.
Definition at line 1102 of file oomph_utilities.cc.
References FlagObsoleteCode, oomph::oomph_info, and oomph::Global_string_for_annotation::string().
Referenced by obsolete(), and oomph::MatrixBasedLumpedPreconditioner< oomph::CRDoubleMatrix >::setup().
obsolete() [2/2]
void oomph::ObsoleteCode::obsolete (const std::string & message)
Ouput a warning message with a string argument.
Definition at line 1138 of file oomph_utilities.cc.
References FlagObsoleteCode, obsolete(), and oomph::oomph_info.
Variable Documentation
FlagObsoleteCode
bool oomph::ObsoleteCode::FlagObsoleteCode = true
Flag up obsolete parts of the code.
Definition at line 1099 of file oomph_utilities.cc.
Referenced by obsolete().