oomph::QElement2FaceToBulkCoordinates Namespace Reference
Namespace for the functions that translate local face coordinates to the coordinates in the bulk element.
Functions
void face0 (const Vector< double > &s, Vector< double > &s_bulk)
The translation scheme for the west face (s0 = -1.0)
void face1 (const Vector< double > &s, Vector< double > &s_bulk)
The translation scheme for the south face (s1 = -1.0)
void face2 (const Vector< double > &s, Vector< double > &s_bulk)
The translation scheme for the east face (s0 = 1.0)
void face3 (const Vector< double > &s, Vector< double > &s_bulk)
The translation scheme for the north face (s1 = 1.0)
Detailed Description
Namespace for the functions that translate local face coordinates to the coordinates in the bulk element.
Function Documentation
face0()
void oomph::QElement2FaceToBulkCoordinates::face0 (const Vector< double > & s, Vector< double > & s_bulk)
The translation scheme for the west face (s0 = -1.0)
Definition at line 79 of file Qelement_face_coordinate_translation_schemes.cc.
References s.
Referenced by oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 2, NNODE_1D >::build_face_element(), and oomph::QElement< 2, NNODE_1D >::face_to_bulk_coordinate_fct_pt().
face1()
void oomph::QElement2FaceToBulkCoordinates::face1 (const Vector< double > & s, Vector< double > & s_bulk)
The translation scheme for the south face (s1 = -1.0)
Definition at line 86 of file Qelement_face_coordinate_translation_schemes.cc.
References s.
Referenced by oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 2, NNODE_1D >::build_face_element(), and oomph::QElement< 2, NNODE_1D >::face_to_bulk_coordinate_fct_pt().
face2()
void oomph::QElement2FaceToBulkCoordinates::face2 (const Vector< double > & s, Vector< double > & s_bulk)
The translation scheme for the east face (s0 = 1.0)
Definition at line 93 of file Qelement_face_coordinate_translation_schemes.cc.
References s.
Referenced by oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 2, NNODE_1D >::build_face_element(), oomph::BrickFromTetMesh< ELEMENT >::build_mesh(), and oomph::QElement< 2, NNODE_1D >::face_to_bulk_coordinate_fct_pt().
face3()
void oomph::QElement2FaceToBulkCoordinates::face3 (const Vector< double > & s, Vector< double > & s_bulk)
The translation scheme for the north face (s1 = 1.0)
Definition at line 100 of file Qelement_face_coordinate_translation_schemes.cc.
References s.
Referenced by oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 2, NNODE_1D >::build_face_element(), and oomph::QElement< 2, NNODE_1D >::face_to_bulk_coordinate_fct_pt().