oomph::PoroelasticityFaceElementHelper Namespace Reference
Namespace containing the zero pressure function for Darcy pressure elements.
Functions
void Zero_traction_fct (const double &time, const Vector< double > &x, const Vector< double > &N, Vector< double > &load)
Default load function (zero traction)
void Zero_pressure_fct (const double &time, const Vector< double > &x, const Vector< double > &N, double &load)
Default load function (zero pressure)
Detailed Description
Namespace containing the zero pressure function for Darcy pressure elements.
Function Documentation
Zero_pressure_fct()
void oomph::PoroelasticityFaceElementHelper::Zero_pressure_fct (const double & time, const Vector< double > & x, const Vector< double > & N, double & load)
Default load function (zero pressure)
Definition at line 67 of file poroelasticity_face_elements.h.
Referenced by oomph::PoroelasticityFaceElement< ELEMENT >::PoroelasticityFaceElement().
Zero_traction_fct()
void oomph::PoroelasticityFaceElementHelper::Zero_traction_fct (const double & time, const Vector< double > & x, const Vector< double > & N, Vector< double > & load)
Default load function (zero traction)
Definition at line 52 of file poroelasticity_face_elements.h.
References i, and oomph::FiniteElement::size().
Referenced by oomph::PoroelasticityFaceElement< ELEMENT >::PoroelasticityFaceElement().