oomph::AxisymmetricPoroelasticityTractionElementHelper Namespace Reference
Namespace containing the zero pressure function for Darcy pressure elements.
Functions
void Zero_traction_fct (const double &time, const Vector< double > &x, const Vector< double > &N, Vector< double > &load)
Default load function (zero traction)
void Zero_pressure_fct (const double &time, const Vector< double > &x, const Vector< double > &N, double &load)
Default load function (zero pressure)
Variables
bool Allow_gap_in_FSI = false
Public boolean to allow gap between poro-elastic and Navier Stokes element in FSI computations. Useful in hybrid linear/nonlinear geometry runs where this will happen.
Detailed Description
Namespace containing the zero pressure function for Darcy pressure elements.
Function Documentation
Zero_pressure_fct()
void oomph::AxisymmetricPoroelasticityTractionElementHelper::Zero_pressure_fct (const double & time, const Vector< double > & x, const Vector< double > & N, double & load)
Default load function (zero pressure)
Definition at line 68 of file axisym_poroelasticity_face_elements.h.
Referenced by oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::AxisymmetricPoroelasticityTractionElement().
Zero_traction_fct()
void oomph::AxisymmetricPoroelasticityTractionElementHelper::Zero_traction_fct (const double & time, const Vector< double > & x, const Vector< double > & N, Vector< double > & load)
Default load function (zero traction)
Definition at line 53 of file axisym_poroelasticity_face_elements.h.
References i, and oomph::FiniteElement::size().
Referenced by oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::AxisymmetricPoroelasticityTractionElement().
Variable Documentation
Allow_gap_in_FSI
bool oomph::AxisymmetricPoroelasticityTractionElementHelper::Allow_gap_in_FSI = false
Public boolean to allow gap between poro-elastic and Navier Stokes element in FSI computations. Useful in hybrid linear/nonlinear geometry runs where this will happen.
Definition at line 79 of file axisym_poroelasticity_face_elements.h.
Referenced by oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_total_porous_flux(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::get_traction(), and oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output().