superlu.c File Reference
Classes
struct factors_t
struct MemoryStatisticsStorage
Typedefs
typedef void * fptr
Functions
double get_lu_factor_memory_usage_in_bytes ()
Function to calculate the number of bytes used to store the LU factors.
double get_total_memory_usage_in_bytes ()
Function to calculate the number of bytes used in calculating and storing the LU factors.
void get_memory_usage_in_bytes (double *lu_factor_memory, double *total_memory)
int superlu (int *op_flag, int *n, int *nnz, int *nrhs, double *values, int *rowind, int *colptr, double *b, int *ldb, int *transpose, int *doc, fptr *f_factors, int *info)
Variables
struct MemoryStatisticsStorage memory_statistics_storage
Typedef Documentation
fptr
typedef void* fptr
Definition at line 23 of file superlu.c.
Function Documentation
get_lu_factor_memory_usage_in_bytes()
double get_lu_factor_memory_usage_in_bytes ()
Function to calculate the number of bytes used to store the LU factors.
Definition at line 53 of file superlu.c.
References memory_statistics_storage, MemoryStatisticsStorage::Memory_usage, and MemoryStatisticsStorage::Memory_usage_has_been_recorded.
Referenced by oomph::SuperLUSolver::get_memory_usage_for_lu_factors().
get_memory_usage_in_bytes()
void get_memory_usage_in_bytes (double * lu_factor_memory, double * total_memory)
Definition at line 85 of file superlu.c.
References memory_statistics_storage, and MemoryStatisticsStorage::Memory_usage.
Referenced by oomph::BandedBlockTriangularPreconditioner< MATRIX >::setup().
get_total_memory_usage_in_bytes()
double get_total_memory_usage_in_bytes ()
Function to calculate the number of bytes used in calculating and storing the LU factors.
Definition at line 69 of file superlu.c.
References memory_statistics_storage, MemoryStatisticsStorage::Memory_usage, and MemoryStatisticsStorage::Memory_usage_has_been_recorded.
Referenced by oomph::SuperLUSolver::get_total_needed_memory().
superlu()
int superlu (int * op_flag, int * n, int * nnz, int * nrhs, double * values, int * rowind, int * colptr, double * b, int * ldb, int * transpose, int * doc, fptr * f_factors, int * info)
Definition at line 118 of file superlu.c.
References oomph::OcTreeNames::B, oomph::LeakCheckNames::doc(), i, factors_t::L, oomph::BinaryTreeNames::L, memory_statistics_storage, MemoryStatisticsStorage::Memory_usage, MemoryStatisticsStorage::Memory_usage_has_been_recorded, n, factors_t::perm_c, factors_t::perm_r, factors_t::U, oomph::OcTreeNames::U, and values.
Variable Documentation
memory_statistics_storage
struct MemoryStatisticsStorage memory_statistics_storage
Referenced by get_lu_factor_memory_usage_in_bytes(), get_memory_usage_in_bytes(), get_total_memory_usage_in_bytes(), and superlu().