superlu_dist.c File Reference
Classes
struct superlu_dist_data
struct MemoryStatisticsStorage
Functions
double get_lu_factor_memory_usage_in_bytes_dist ()
double get_total_memory_usage_in_bytes_dist ()
void get_memory_usage_in_bytes_dist (double *lu_factor_memory, double *total_memory)
void superlu_cr_to_cc (int nrow, int ncol, int nnz, double *cr_values, int *cr_index, int *cr_start, double **cc_values, int **cc_index, int **cc_start)
void superlu_dist_distributed_matrix (int opt_flag, int allow_permutations, int n, int nnz_local, int nrow_local, int first_row, double *values, int *col_index, int *row_start, double *b, int nprow, int npcol, int doc, void **data, int *info, MPI_Comm comm)
void superlu_dist_global_matrix (int opt_flag, int allow_permutations, int n_in, int nnz_in, double *values, int *row_index, int *col_start, double *b, int nprow, int npcol, int doc, void **data, int *info, MPI_Comm comm)
Variables
struct MemoryStatisticsStorage symbolic_memory_statistics_storage
Function Documentation
get_lu_factor_memory_usage_in_bytes_dist()
double get_lu_factor_memory_usage_in_bytes_dist ()
Definition at line 77 of file superlu_dist.c.
References MemoryStatisticsStorage::Memory_usage, MemoryStatisticsStorage::Memory_usage_has_been_recorded, and symbolic_memory_statistics_storage.
get_memory_usage_in_bytes_dist()
void get_memory_usage_in_bytes_dist (double * lu_factor_memory, double * total_memory)
Definition at line 109 of file superlu_dist.c.
References MemoryStatisticsStorage::Memory_usage, and symbolic_memory_statistics_storage.
get_total_memory_usage_in_bytes_dist()
double get_total_memory_usage_in_bytes_dist ()
Definition at line 93 of file superlu_dist.c.
References MemoryStatisticsStorage::Memory_usage, MemoryStatisticsStorage::Memory_usage_has_been_recorded, and symbolic_memory_statistics_storage.
superlu_cr_to_cc()
void superlu_cr_to_cc (int nrow, int ncol, int nnz, double * cr_values, int * cr_index, int * cr_start, double ** cc_values, int ** cc_index, int ** cc_start)
Definition at line 120 of file superlu_dist.c.
superlu_dist_distributed_matrix()
void superlu_dist_distributed_matrix (int opt_flag, int allow_permutations, int n, int nnz_local, int nrow_local, int first_row, double * values, int * col_index, int * row_start, double * b, int nprow, int npcol, int doc, void ** data, int * info, MPI_Comm comm)
Definition at line 161 of file superlu_dist.c.
References superlu_dist_data::A, superlu_dist_data::anorm, oomph::OcTreeNames::B, superlu_dist_data::colequ, oomph::LeakCheckNames::doc(), superlu_dist_data::grid, i, if(), superlu_dist_data::LUstruct, MemoryStatisticsStorage::Memory_usage, superlu_dist_data::options, oomph::BinaryTreeNames::R, superlu_dist_data::rowequ, superlu_dist_data::ScalePermstruct, superlu_dist_data::SOLVEstruct, symbolic_memory_statistics_storage, and t.
superlu_dist_global_matrix()
void superlu_dist_global_matrix (int opt_flag, int allow_permutations, int n_in, int nnz_in, double * values, int * row_index, int * col_start, double * b, int nprow, int npcol, int doc, void ** data, int * info, MPI_Comm comm)
Definition at line 1236 of file superlu_dist.c.
References superlu_dist_data::A, superlu_dist_data::AC, superlu_dist_data::anorm, oomph::OcTreeNames::B, superlu_dist_data::colequ, oomph::LeakCheckNames::doc(), superlu_dist_data::grid, i, superlu_dist_data::LUstruct, MemoryStatisticsStorage::Memory_usage, superlu_dist_data::options, oomph::BinaryTreeNames::R, superlu_dist_data::rowequ, superlu_dist_data::ScalePermstruct, symbolic_memory_statistics_storage, and t.
Variable Documentation
symbolic_memory_statistics_storage
struct MemoryStatisticsStorage symbolic_memory_statistics_storage
Referenced by get_lu_factor_memory_usage_in_bytes_dist(), get_memory_usage_in_bytes_dist(), get_total_memory_usage_in_bytes_dist(), superlu_dist_distributed_matrix(), and superlu_dist_global_matrix().