the_data_structure.txt File Reference
Classes
class MultiPhysicsElement
Functions
mainpage The data structure section intro Introduction c oomph lib is big ! This document gives a bottom up overview of the library s data structure and discusses how the various objects interact In addition to the detailed discussion provided the following doxygen generated lists indices provide quick access to the documentation of c oomph lib s we usually replace the list of arguments to functions by (...)' and explain the main input and output parameters in words. The full specifications of the interfaces may be found in the individual class documentation
often abbreviated as dof b History b history values are but b not b the values at previous timesteps b Pinned c c c Mesh and c Problem subsection data Data The most elementary data structure in c oomph lib is c Data (ha!). Consider the solution of a scalar PDE(e.g. a Poisson equation) with certain boundary conditions. The numerical solution of this problem requires the computation of the function values(double precision numbers) at a finite number of spatial positions(the \c Nodes). Typically
often abbreviated as dof b History b history values are but b not b the values at previous timesteps b Pinned c c c Mesh and c Problem subsection data Data The most elementary data structure in c oomph lib is c these values fall into two and those that must be determined as part of the solution c Data stores a value a double precision number the values of the unknowns are determined by the solution of a system of algebraic equations The solution of this system usually requires a (linear) numbering of the unknowns and associated equations. Hence
often abbreviated as dof b History b history values are but b not b the values at previous timesteps b Pinned c c c Mesh and c Problem subsection data Data The most elementary data structure in c oomph lib is c these values fall into two and those that must be determined as part of the solution c Data stores a value a double precision number the values of the unknowns are determined by the solution of a system of algebraic equations The solution of this system usually requires c Data also stores a(long) integer that represents the number of the unknown in the global numbering scheme. \b Convention for in a fluids we need to store three velocity components at every node c Data allows the storage of multiple values (all of which can either be pinned or free, and all of which have their own global equation number)
c Data can also store a certain number of auxiliary (history) values used for timestepping. Finally
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt(t, i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many cases (e.g. BDF schemes) these history values are simply the values at previous timesteps
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt(t, i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE most (but not all;see below) \c Data are associated with nodal points. Conversely
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt(t, i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial(Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced we must evaluate mesh which requires the storage of the nodal position at a number of previous timesteps Storage for the positional history values is allocated by the c Node constructor A different c TimeStepper may be used to represent time derivatives of nodal so c Nodes store a separate pointer to a positional c TimeStepper[Note:By default, we allocate the same amount of storage for the history of the nodal positions as we do for the history of the nodal values;e.g. if a \c BDF< 2 > scheme is used to evaluate the time-derivatives of the fluid velocities, we assume that the same timestepping scheme is used(and the same amount of storage required) to determine the mesh velocities from the nodal positions.] For finite elements in which the global position of a point in an element is determined by interpolation from the position of the element s c Nodes (Lagrange-type elements)
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt(t, i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial(Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced we must evaluate mesh which requires the storage of the nodal position at a number of previous timesteps Storage for the positional history values is allocated by the c Node constructor A different c TimeStepper may be used to represent time derivatives of nodal so c Nodes store a separate pointer to a positional c TimeStepper[Note:By default, we allocate the same amount of storage for the history of the nodal positions as we do for the history of the nodal values;e.g. if a \c BDF< 2 > scheme is used to evaluate the time-derivatives of the fluid velocities, we assume that the same timestepping scheme is used(and the same amount of storage required) to determine the mesh velocities from the nodal positions.] For finite elements in which the global position of a point in an element is determined by interpolation from the position of the element s c we need only store the spatial position of the c Nodes In many other elements (e.g. Hermite-type elements)
the nodal coordinate of type stores the derivative of the global position w r t to the element s coordinate The member function code nodes can become hanging nodes (i.e. nodes on an element 's edge/face that are not shared by the adjacent element). The `hanging` status of a \c Node is indicated by the pointer to its \c HangInfo object. For ordinary(non-hanging) \c Nodes this pointer is NULL
the nodal coordinates represent the c Nodes fixed positions in this domain When the elastic body material points (and hence the \c Nodes) are displaced to new Eulerian positions. The \c SolidNode class is derived from \c Node and contains storage for the \c Nodes' \b fixed positions(i.e. the Lagrangian coordinates) AND their \b variable positions(i.e. the Eulerian coordinates)
the nodal coordinates represent the c Nodes fixed positions in this domain When the elastic body material which can be unknowns in the problem To avoid confusion between the the access function for the nodal code we provide a wrapper code in the case of generalised coordinates code Node::x_gen(...) \endcode always refers to the generalised Eulerian position and \code SolidNode endcode where the c MultiPhysicsElement inherits from c SinglePhysicsOneElement and c SinglePhysicsTwoElement A problem with this implementation arises when we consider where to initialise the residuals vector If the second single physics c get_residuals (...) function initialises the residuals vector
endcode The default implementation of c fill_in_contribution_to_jacobian (...) uses finite differences to calculate the Jacobian matrix. Hence
endcode The default implementation of c the simplest possible implementation of a new element requires only the specification of c fill_in_contribution_to_residuals (...). - When computing element residuals and Jacobian matrices
endcode The default implementation of c the simplest possible implementation of a new element requires only the specification of c we need to know which c Data affects the residuals (and hence the Jacobian matrix). For a \c GeneralisedElement such \c Data exists in two forms
endcode The default implementation of c the simplest possible implementation of a new element requires only the specification of c we need to know which c Data affects the accessed via in fluid (finite) elements with discontinuous pressure interpolations
endcode The default implementation of c the simplest possible implementation of a new element requires only the specification of c we need to know which c Data affects the accessed via in the pressure degrees of freedom are to each element and are stored in the element s Internal c Data c Data that is external to the element An example is a load parameter such as the external pressure that acts on a shell structure Such c Data is accessed via pointers to External c Data As discussed all c Data contains values that are either free (i.e. unknown) or pinned(i.e. prescribed by boundary conditions). Free/unknown values have a non-negative global(equation) number. When assembling an element 's local contribution to the global residual vector and the Jacobian matrix
endcode The default implementation of c the simplest possible implementation of a new element requires only the specification of c we need to know which c Data affects the accessed via in the pressure degrees of freedom are to each element and are stored in the element s Internal c Data c Data that is external to the element An example is a load parameter such as the external pressure that acts on a shell structure Such c Data is accessed via pointers to External c Data As discussed all c Data contains values that are either we refer to the unknowns by their (equation) numbers. In order to add the elemental contribution to the appropriate global degree of freedom
endcode returns the global equation number c i_global corresponding to the equation number c i_local The equation numbers of the internal and external c Data are stored in the private arrays c Internal_local_eqn and c accessed by the functions c GeneralisedElement::internal_local_eqn(...) and \c GeneralisedElement see section ref Hanging_Nodes for further details When c Nodes are created in a (templated) finite element mesh
endcode returns the global equation number c i_global corresponding to the equation number c i_local The equation numbers of the internal and external c Data are stored in the private arrays c Internal_local_eqn and c accessed by the functions c GeneralisedElement::internal_local_eqn(...) and \c GeneralisedElement see section ref Hanging_Nodes for further details When c Nodes are created in it is important that c Nodes of the correct type with the appropriate amount of storage are created For Poisson elements require c Nodes that provide storage for a single value at each c whereas Taylor Navier Stokes elements require storage for three values (two velocities and one pressure) at the corner \c Nodes
and code FiniteElement::J_eulerian(...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement< 3, 2 > is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the see ref set_commands above The most important member functions implemented at this level include Functions that evaluate the shape functions (and their derivatives) at given values of the local coordinates. - Functions that specify the position of each \c Node inside its \c FiniteElement
and code FiniteElement::J_eulerian(...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement< 3, 2 > is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the see ref set_commands above The most important member functions implemented at this level include Functions that evaluate the shape in terms of the c FiniteElement s coordinates functions that determine whether a c Node is located at a particular coordinate Output functions that allow the element shapes to be plotted we specify a pointer to a spatial integration scheme (usually a Gauss rule). The order of the integration scheme is based on the order of the interpolation in the isoparametric mapping. If this is inappropriate for an element that is derived from a given geometric element
and code FiniteElement::J_eulerian(...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement< 3, 2 > is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the see ref set_commands above The most important member functions implemented at this level include Functions that evaluate the shape in terms of the c FiniteElement s coordinates functions that determine whether a c Node is located at a particular coordinate Output functions that allow the element shapes to be plotted we specify a pointer to a spatial integration the default assignment can be over written at a higher level This is discussed in more detail in a< A HREF=`../../optimisation/html/index.html`> separate document</A > subsubsection Maths_Element we implement the equations that are represented by the specific element We implement the interpolation (s) for the unknown function(s)
and code FiniteElement::J_eulerian(...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement< 3, 2 > is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the see ref set_commands above The most important member functions implemented at this level include Functions that evaluate the shape in terms of the c FiniteElement s coordinates functions that determine whether a c Node is located at a particular coordinate Output functions that allow the element shapes to be plotted we specify a pointer to a spatial integration the default assignment can be over written at a higher level This is discussed in more detail in a< A HREF=`../../optimisation/html/index.html`> separate document</A > subsubsection Maths_Element we implement the equations that are represented by the specific element We implement the employing either the geometric shape functions that already exist on or employing additional shape functions defined at this level This allows us to write further member functions such as c interpolated_u (...)
Vector< double > s (3)
Vector< double > u (3)
fluid_element interpolated_u (s, u)
endcode (which forces us to remember that in this particular 3D fluid element, the pressure is stored as the fourth value at all nodes...)
we provide an access function c p_fluid (...) which allows us to write \code unsigned n
endcode in our standard equations the function c assign_additional_local_eqn_numbers () is not used. Finally
Variables
mainpage The data structure section intro Introduction c oomph lib is big ! This document gives a bottom up overview of the library s data structure and discusses how the various objects interact In addition to the detailed discussion provided below
mainpage The data structure section intro Introduction c oomph lib is big ! This document gives a bottom up overview of the library s data structure and discusses how the various objects interact In addition to the detailed discussion provided the following doxygen generated lists indices provide quick access to the documentation of c oomph lib s classes
mainpage The data structure section intro Introduction c oomph lib is big ! This document gives a bottom up overview of the library s data structure and discusses how the various objects interact In addition to the detailed discussion provided the following doxygen generated lists indices provide quick access to the documentation of c oomph lib s we usually replace the list of arguments to functions accessible via the links at the top of this page subsection technical_terms Technical terms Throughout this document
mainpage The data structure section intro Introduction c oomph lib is big ! This document gives a bottom up overview of the library s data structure and discusses how the various objects interact In addition to the detailed discussion provided the following doxygen generated lists indices provide quick access to the documentation of c oomph lib s we usually replace the list of arguments to functions accessible via the links at the top of this page subsection technical_terms Technical terms Throughout this certain commonly used terms have a specific technical meaning
often abbreviated as dof b History b value
often abbreviated as dof b History b history values are often
often abbreviated as dof b History b history values are but b not b always
often abbreviated as dof b History b history values are but b not b the values at previous timesteps b Pinned free
often abbreviated as dof b History b history values are but b not b the values at previous timesteps b Pinned c Node
often abbreviated as dof b History b history values are but b not b the values at previous timesteps b Pinned c c GeneralisedElement
often abbreviated as dof b History b history values are but b not b the values at previous timesteps b Pinned c c c Mesh and c Problem subsection data Data The most elementary data structure in c oomph lib is c these values fall into two categories
often abbreviated as dof b History b history values are but b not b the values at previous timesteps b Pinned c c c Mesh and c Problem subsection data Data The most elementary data structure in c oomph lib is c these values fall into two and those that must be determined as part of the solution c Data stores a value a double precision number Typically
often abbreviated as dof b History b history values are but b not b the values at previous timesteps b Pinned c c c Mesh and c Problem subsection data Data The most elementary data structure in c oomph lib is c these values fall into two and those that must be determined as part of the solution c Data stores a value a double precision number the values of the unknowns are determined by the solution of a system of algebraic equations The solution of this system usually requires c Data also stores a(long) integer that represents the number of the unknown in the global numbering scheme. \b Convention for instance
often abbreviated as dof b History b history values are but b not b the values at previous timesteps b Pinned c c c Mesh and c Problem subsection data Data The most elementary data structure in c oomph lib is c these values fall into two and those that must be determined as part of the solution c Data stores a value a double precision number the values of the unknowns are determined by the solution of a system of algebraic equations The solution of this system usually requires c Data also stores a(long) integer that represents the number of the unknown in the global numbering scheme. \b Convention for in a fluids problem
often abbreviated as dof b History b history values are but b not b the values at previous timesteps b Pinned c c c Mesh and c Problem subsection data Data The most elementary data structure in c oomph lib is c these values fall into two and those that must be determined as part of the solution c Data stores a value a double precision number the values of the unknowns are determined by the solution of a system of algebraic equations The solution of this system usually requires c Data also stores a(long) integer that represents the number of the unknown in the global numbering scheme. \b Convention for in a fluids we need to store three velocity components at every node Therefore
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives Direct
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt(t, i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE computations
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt(t, i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c Data
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt(t, i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial position
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt(t, i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial(Eulerian) coordinates. The nodal positions are accessed by the member function \code Node again
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt(t, i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial(Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced features
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt(t, i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial(Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced we must evaluate mesh velocities
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt(t, i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial(Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced we must evaluate mesh which requires the storage of the nodal position at a number of previous timesteps Storage for the positional history values is allocated by the c Node constructor A different c TimeStepper may be used to represent time derivatives of nodal so c Nodes store a separate pointer to a positional c TimeStepper[Note:By default, we allocate the same amount of storage for the history of the nodal positions as we do for the history of the nodal values;e.g. if a \c BDF< 2 > scheme is used to evaluate the time-derivatives of the fluid velocities, we assume that the same timestepping scheme is used(and the same amount of storage required) to determine the mesh velocities from the nodal positions.] For finite elements in which the global position of a point in an element is determined by interpolation from the position of the element s c we need only store the spatial position of the c Nodes In many other the interpolation of the geometry requires additional quantities
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt(t, i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial(Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced we must evaluate mesh which requires the storage of the nodal position at a number of previous timesteps Storage for the positional history values is allocated by the c Node constructor A different c TimeStepper may be used to represent time derivatives of nodal so c Nodes store a separate pointer to a positional c TimeStepper[Note:By default, we allocate the same amount of storage for the history of the nodal positions as we do for the history of the nodal values;e.g. if a \c BDF< 2 > scheme is used to evaluate the time-derivatives of the fluid velocities, we assume that the same timestepping scheme is used(and the same amount of storage required) to determine the mesh velocities from the nodal positions.] For finite elements in which the global position of a point in an element is determined by interpolation from the position of the element s c we need only store the spatial position of the c Nodes In many other the interpolation of the geometry requires additional representing
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt(t, i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial(Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced we must evaluate mesh which requires the storage of the nodal position at a number of previous timesteps Storage for the positional history values is allocated by the c Node constructor A different c TimeStepper may be used to represent time derivatives of nodal so c Nodes store a separate pointer to a positional c TimeStepper[Note:By default, we allocate the same amount of storage for the history of the nodal positions as we do for the history of the nodal values;e.g. if a \c BDF< 2 > scheme is used to evaluate the time-derivatives of the fluid velocities, we assume that the same timestepping scheme is used(and the same amount of storage required) to determine the mesh velocities from the nodal positions.] For finite elements in which the global position of a point in an element is determined by interpolation from the position of the element s c we need only store the spatial position of the c Nodes In many other the interpolation of the geometry requires additional e g the derivative of the mapping between and global coordinates we allow the storage of additional positional variables at each c so that
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt(t, i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial(Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced we must evaluate mesh which requires the storage of the nodal position at a number of previous timesteps Storage for the positional history values is allocated by the c Node constructor A different c TimeStepper may be used to represent time derivatives of nodal so c Nodes store a separate pointer to a positional c TimeStepper[Note:By default, we allocate the same amount of storage for the history of the nodal positions as we do for the history of the nodal values;e.g. if a \c BDF< 2 > scheme is used to evaluate the time-derivatives of the fluid velocities, we assume that the same timestepping scheme is used(and the same amount of storage required) to determine the mesh velocities from the nodal positions.] For finite elements in which the global position of a point in an element is determined by interpolation from the position of the element s c we need only store the spatial position of the c Nodes In many other the interpolation of the geometry requires additional e g the derivative of the mapping between and global coordinates we allow the storage of additional positional variables at each c so in general
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt(t, i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial(Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced we must evaluate mesh which requires the storage of the nodal position at a number of previous timesteps Storage for the positional history values is allocated by the c Node constructor A different c TimeStepper may be used to represent time derivatives of nodal so c Nodes store a separate pointer to a positional c TimeStepper[Note:By default, we allocate the same amount of storage for the history of the nodal positions as we do for the history of the nodal values;e.g. if a \c BDF< 2 > scheme is used to evaluate the time-derivatives of the fluid velocities, we assume that the same timestepping scheme is used(and the same amount of storage required) to determine the mesh velocities from the nodal positions.] For finite elements in which the global position of a point in an element is determined by interpolation from the position of the element s c we need only store the spatial position of the c Nodes In many other the interpolation of the geometry requires additional e g the derivative of the mapping between and global coordinates we allow the storage of additional positional variables at each c so in every c Node has a number of e generalised coordinates for each spatial coordinate direction For for nodes in Hermite elements
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt(t, i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial(Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced we must evaluate mesh which requires the storage of the nodal position at a number of previous timesteps Storage for the positional history values is allocated by the c Node constructor A different c TimeStepper may be used to represent time derivatives of nodal so c Nodes store a separate pointer to a positional c TimeStepper[Note:By default, we allocate the same amount of storage for the history of the nodal positions as we do for the history of the nodal values;e.g. if a \c BDF< 2 > scheme is used to evaluate the time-derivatives of the fluid velocities, we assume that the same timestepping scheme is used(and the same amount of storage required) to determine the mesh velocities from the nodal positions.] For finite elements in which the global position of a point in an element is determined by interpolation from the position of the element s c we need only store the spatial position of the c Nodes In many other the interpolation of the geometry requires additional e g the derivative of the mapping between and global coordinates we allow the storage of additional positional variables at each c so in every c Node has a number of e generalised coordinates for each spatial coordinate direction For for nodes in Hermite the nodal coordinate of type stores the global position at the node
the nodal coordinate of type stores the derivative of the global position w r t to the element s coordinate The member function code nodes can become hanging the default setting
see the section ref Hanging_Nodes for a more detailed discussion of hanging nodes
in particular
in the role of the member functions c Node::position() and \c Node the latter case arises if the c Node is located on edges and corners of the mesh Storage of this information facilitates the automatic determination of boundary conditions for new c Nodes that are created during mesh refinement n The majority of the c Nodes will b not be located on boundaries
in the role of the member functions c Node::position() and \c Node the latter case arises if the c Node is located on edges and corners of the mesh Storage of this information facilitates the automatic determination of boundary conditions for new c Nodes that are created during mesh refinement n The majority of the c Nodes will b not be located on however
in the role of the member functions c Node::position() and \c Node the latter case arises if the c Node is located on edges and corners of the mesh Storage of this information facilitates the automatic determination of boundary conditions for new c Nodes that are created during mesh refinement n The majority of the c Nodes will b not be located on and providing storage for the boundary information in every c Node object is rather wasteful The derived class c BoundaryNode adds the required additional storage to the c Node class and it follows that all c Nodes that could lie on boundaries must be c BoundaryNodes
see ref meshes for further details b SolidNodes
see ref meshes for further details b the governing equations are discretised in a fixed Lagrangian domain
the nodal coordinates represent the c Nodes fixed positions in this domain When the elastic body deforms
the nodal coordinates represent the c Nodes fixed positions in this domain When the elastic body material which can be unknowns in the problem To avoid confusion between the two
the nodal coordinates represent the c Nodes fixed positions in this domain When the elastic body material which can be unknowns in the problem To avoid confusion between the the access function for the nodal code we provide a wrapper code in the case of generalised coordinates code Node::x_gen(...) \endcode always refers to the generalised Eulerian position and \code SolidNode endcode where the c MultiPhysicsElement inherits from c SinglePhysicsOneElement and c SinglePhysicsTwoElement A problem with this implementation arises when we consider where to initialise the residuals vector If the second single physics c then the contribution of the first single physics element will be negated When writing a single physics element
the nodal coordinates represent the c Nodes fixed positions in this domain When the elastic body material which can be unknowns in the problem To avoid confusion between the the access function for the nodal code we provide a wrapper code in the case of generalised coordinates code Node::x_gen(...) \endcode always refers to the generalised Eulerian position and \code SolidNode endcode where the c MultiPhysicsElement inherits from c SinglePhysicsOneElement and c SinglePhysicsTwoElement A problem with this implementation arises when we consider where to initialise the residuals vector If the second single physics c then the contribution of the first single physics element will be negated When writing a single physics we cannot know whether it will ever be used as part of a multi physics element and
the nodal coordinates represent the c Nodes fixed positions in this domain When the elastic body material which can be unknowns in the problem To avoid confusion between the the access function for the nodal code we provide a wrapper code in the case of generalised coordinates code Node::x_gen(...) \endcode always refers to the generalised Eulerian position and \code SolidNode endcode where the c MultiPhysicsElement inherits from c SinglePhysicsOneElement and c SinglePhysicsTwoElement A problem with this implementation arises when we consider where to initialise the residuals vector If the second single physics c then the contribution of the first single physics element will be negated When writing a single physics we cannot know whether it will ever be used as part of a multi physics element if so
endcode The default implementation of c the simplest possible implementation of a new element requires only the specification of c we need to know which c Data affects the accessed via pointers
endcode The default implementation of c the simplest possible implementation of a new element requires only the specification of c we need to know which c Data affects the accessed via in the pressure degrees of freedom are to each element and are stored in the element s Internal c Data c Data that is external to the element An example is a load parameter such as the external pressure that acts on a shell structure Such c Data is accessed via pointers to External c Data As discussed above
GeneralisedElement el
unsigned i_global =el.eqn_number(i_local)
endcode returns the global equation number c i_global corresponding to the equation number c i_local The equation numbers of the internal and external c Data are stored in the private arrays c Internal_local_eqn and c External_local_eqn
endcode returns the global equation number c i_global corresponding to the equation number c i_local The equation numbers of the internal and external c Data are stored in the private arrays c Internal_local_eqn and c accessed by the functions c GeneralisedElement::internal_local_eqn(...) and \c GeneralisedElement see section ref Hanging_Nodes for further details When c Nodes are created in it is important that c Nodes of the correct type with the appropriate amount of storage are created For Poisson elements require c Nodes that provide storage for a single value at each c whereas Taylor Hood
endcode returns the global equation number c i_global corresponding to the equation number c i_local The equation numbers of the internal and external c Data are stored in the private arrays c Internal_local_eqn and c accessed by the functions c GeneralisedElement::internal_local_eqn(...) and \c GeneralisedElement see section ref Hanging_Nodes for further details When c Nodes are created in it is important that c Nodes of the correct type with the appropriate amount of storage are created For Poisson elements require c Nodes that provide storage for a single value at each c whereas Taylor Navier Stokes elements require storage for three but only two values(the two velocities) at all others. The member function \code FiniteElement by default the spatial dimension of the c FiniteElement s c Nodes is assumed to be the same For example
endcode returns the global equation number c i_global corresponding to the equation number c i_local The equation numbers of the internal and external c Data are stored in the private arrays c Internal_local_eqn and c accessed by the functions c GeneralisedElement::internal_local_eqn(...) and \c GeneralisedElement see section ref Hanging_Nodes for further details When c Nodes are created in it is important that c Nodes of the correct type with the appropriate amount of storage are created For Poisson elements require c Nodes that provide storage for a single value at each c whereas Taylor Navier Stokes elements require storage for three but only two values(the two velocities) at all others. The member function \code FiniteElement by default the spatial dimension of the c FiniteElement s c Nodes is assumed to be the same For code FiniteElement::set_dimension(2) \endcode sets both the spatial dimension of the element and the spatial dimension of its \c Nodes to be two. If the nodal dimension is not the same as the dimension of the element the member function \code FiniteElement code endcode returns the derivative of the shape functions with respect to the Eulerian coordinates
and code FiniteElement::J_eulerian(...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement< 3, 2 > is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the constructor
and code FiniteElement::J_eulerian(...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement< 3, 2 > is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the see ref set_commands above The most important member functions implemented at this level include Functions that evaluate the shape in terms of the c FiniteElement s coordinates conversely
and code FiniteElement::J_eulerian(...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement< 3, 2 > is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the see ref set_commands above The most important member functions implemented at this level include Functions that evaluate the shape in terms of the c FiniteElement s coordinates functions that determine whether a c Node is located at a particular coordinate Output functions that allow the element shapes to be plotted Finally
and code FiniteElement::J_eulerian(...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement< 3, 2 > is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the see ref set_commands above The most important member functions implemented at this level include Functions that evaluate the shape in terms of the c FiniteElement s coordinates functions that determine whether a c Node is located at a particular coordinate Output functions that allow the element shapes to be plotted we specify a pointer to a spatial integration the default assignment can be over written at a higher level This is discussed in more detail in a< A HREF=`../../optimisation/html/index.html`> separate document</A > subsubsection Maths_Element Level
and code FiniteElement::J_eulerian(...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement< 3, 2 > is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the see ref set_commands above The most important member functions implemented at this level include Functions that evaluate the shape in terms of the c FiniteElement s coordinates functions that determine whether a c Node is located at a particular coordinate Output functions that allow the element shapes to be plotted we specify a pointer to a spatial integration the default assignment can be over written at a higher level This is discussed in more detail in a< A HREF=`../../optimisation/html/index.html`> separate document</A > subsubsection Maths_Element we implement the equations that are represented by the specific element We implement the employing either the geometric shape functions that already exist on level
and code FiniteElement::J_eulerian(...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement< 3, 2 > is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the see ref set_commands above The most important member functions implemented at this level include Functions that evaluate the shape in terms of the c FiniteElement s coordinates functions that determine whether a c Node is located at a particular coordinate Output functions that allow the element shapes to be plotted we specify a pointer to a spatial integration the default assignment can be over written at a higher level This is discussed in more detail in a< A HREF=`../../optimisation/html/index.html`> separate document</A > subsubsection Maths_Element we implement the equations that are represented by the specific element We implement the employing either the geometric shape functions that already exist on or employing additional shape functions defined at this level This allows us to write further member functions such as c say
and code FiniteElement::J_eulerian(...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement< 3, 2 > is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the see ref set_commands above The most important member functions implemented at this level include Functions that evaluate the shape in terms of the c FiniteElement s coordinates functions that determine whether a c Node is located at a particular coordinate Output functions that allow the element shapes to be plotted we specify a pointer to a spatial integration the default assignment can be over written at a higher level This is discussed in more detail in a< A HREF=`../../optimisation/html/index.html`> separate document</A > subsubsection Maths_Element we implement the equations that are represented by the specific element We implement the employing either the geometric shape functions that already exist on or employing additional shape functions defined at this level This allows us to write further member functions such as c which compute the i th velocity component at the coordinate c s like this code SomeFluidElement fluid_element
endcode We introduce wrapper functions to access function values
endcode We introduce wrapper functions to access function so that we can formulate The Maths in generic terms Rather than referring to the pressure at node c n
double press = Node_pt[n]->value(3)
endcode When writing these wrapper functions
endcode When writing these wrapper direct access to the nodal values should be avoided to ensure that the element remains functional in the presence of hanging nodes Hence
endcode Thus
endcode in our standard equations the function c virtual the function code FiniteElement::required_nvalue(...) \endcode should be implemented to specify the number of values that are stored at each of the element 's local \c Nodes. The default number of values stored at a \c Node is zero. \subsubsection advanced_features_of_elements Advanced' features for the Maths' level this can be advantageous when the element types are very closely related
Function Documentation
a() [1/2]
often abbreviated as dof b History b history values are but b not b the values at previous timesteps b Pinned c c c Mesh and c Problem subsection data Data The most elementary data structure in c oomph lib is c these values fall into two and those that must be determined as part of the solution c Data stores a value a double precision number the values of the unknowns are determined by the solution of a system of algebraic equations The solution of this system usually requires a (linear)
Referenced by oomph::VectorHelpers::angle(), oomph::OneDLagrangianMesh< ELEMENT >::assign_undeformed_positions(), oomph::CircularCylindricalShellMesh< ELEMENT >::assign_undeformed_positions(), oomph::BellElementShape< 2 >::Bshape(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_fitting_parameters_of_cubic(), oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_fitting_parameters_of_cubic(), oomph::VectorHelpers::check_lengths_match(), oomph::CompressedMatrixCoefficient::CompressedMatrixCoefficient(), oomph::OcTree::construct_rotation_matrix(), oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), oomph::CylinderWithFlagMesh< ELEMENT >::CylinderWithFlagMesh(), oomph::BellElementShape< 2 >::d2Bshape_local(), oomph::Ellipse::d2position(), oomph::BellElementShape< 2 >::dBshape_local(), oomph::VectorHelpers::dot(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::ODEElement::fill_in_contribution_to_jacobian(), oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals_beam(), oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_residuals_shell(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::RefineableLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity(), oomph::LinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity(), oomph::RefineablePVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::PVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::TimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::PoroelasticityEquations< 2 >::fill_in_generic_residual_contribution(), oomph::AxisymmetricPoroelasticityEquations::fill_in_generic_residual_contribution(), oomph::RefineablePVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), oomph::PVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), oomph::GeompackQuadScaffoldMesh::GeompackQuadScaffoldMesh(), oomph::RefineableQElement< 3 >::get_boundaries(), oomph::KirchhoffLoveShellEquations::get_energy(), oomph::KirchhoffLoveBeamEquations::get_energy(), oomph::CRDoubleMatrix::get_matrix_transpose(), oomph::KirchhoffLoveShellEquations::get_strain_and_bend(), oomph::CRDoubleMatrix::inf_norm(), oomph::VectorHelpers::magnitude(), oomph::DGEulerFaceElement< ELEMENT >::numerical_flux(), oomph::CompressedMatrixCoefficient::operator<(), oomph::CompressedMatrixCoefficient::operator=(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::RefineableTwoDAnnularMesh< ELEMENT >::RefineableTwoDAnnularMesh(), oomph::AugmentedBlockFoldLinearSolver::resolve(), oomph::AugmentedBlockPitchForkLinearSolver::resolve(), oomph::Ellipse::set_A_ellips(), oomph::AugmentedBlockFoldLinearSolver::solve(), oomph::AugmentedBlockPitchForkLinearSolver::solve(), oomph::ANASAZI::solve_eigenproblem(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error(), superlu_dist_distributed_matrix(), superlu_dist_global_matrix(), oomph::TwoDAnnularMesh< ELEMENT >::TwoDAnnularMesh(), oomph::RefineableTriangleMesh< ELEMENT >::unrefine_boundary(), oomph::RefineableTriangleMesh< ELEMENT >::unrefine_boundary_constrained_by_target_area(), oomph::OcTree::vertex_node_to_vector(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity(), oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity(), and oomph::TwoDAnnularMesh< ELEMENT >::wrap_into_annular_shape().
a() [2/2]
endcode returns the global equation number c i_global corresponding to the equation number c i_local The equation numbers of the internal and external c Data are stored in the private arrays c Internal_local_eqn and c accessed by the functions c GeneralisedElement::internal_local_eqn (...) and \c GeneralisedElement see section ref Hanging_Nodes for further details When c Nodes are created in a (templated)
assign_additional_local_eqn_numbers()
endcode in our standard equations the function c assign_additional_local_eqn_numbers ()
Referenced by oomph::RefineablePseudoSolidNodeUpdateElement< BASIC, SOLID >::assign_additional_local_eqn_numbers().
auxiliary()
c Data can also store a certain number of auxiliary (history)
by()
mainpage The data structure section intro Introduction c oomph lib is big ! This document gives a bottom up overview of the library s data structure and discusses how the various objects interact In addition to the detailed discussion provided the following doxygen generated lists indices provide quick access to the documentation of c oomph lib s we usually replace the list of arguments to functions by (...)
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::compute_area_target().
cases()
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt (t,i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many cases (e.g. BDF schemes)
Data()
often abbreviated as dof b History b history values are but b not b the values at previous timesteps b Pinned c c c Mesh and c Problem subsection data Data The most elementary data structure in c oomph lib is c Data (ha!)
elements()
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt (t,i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial (Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced we must evaluate mesh which requires the storage of the nodal position at a number of previous timesteps Storage for the positional history values is allocated by the c Node constructor A different c TimeStepper may be used to represent time derivatives of nodal so c Nodes store a separate pointer to a positional c TimeStepper [Note: By default, we allocate the same amount of storage for the history of the nodal positions as we do for the history of the nodal values; e.g. if a \c BDF<2> scheme is used to evaluate the time-derivatives of the fluid velocities, we assume that the same timestepping scheme is used (and the same amount of storage required) to determine the mesh velocities from the nodal positions.] For finite elements in which the global position of a point in an element is determined by interpolation from the position of the element s c we need only store the spatial position of the c Nodes In many other elements (e.g. Hermite-type elements)
endcode()
endcode (which forces us to remember that in this particular 3D fluid element, the pressure is stored as the fourth value at all nodes...)
fill_in_contribution_to_jacobian()
endcode The default implementation of c fill_in_contribution_to_jacobian (...)
Referenced by oomph::PseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_contribution_to_jacobian(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::ProjectableElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::RefineablePseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_contribution_to_jacobian(), oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_contribution_to_jacobian().
fill_in_contribution_to_residuals()
endcode The default implementation of c the simplest possible implementation of a new element requires only the specification of c fill_in_contribution_to_residuals (...)
Referenced by oomph::PseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_contribution_to_residuals(), oomph::ProjectableElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::fill_in_contribution_to_residuals(), oomph::RefineablePseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_contribution_to_residuals(), oomph::PseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_shape_derivatives_by_fd(), and oomph::RefineablePseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_shape_derivatives_by_fd().
fluid()
endcode The default implementation of c the simplest possible implementation of a new element requires only the specification of c we need to know which c Data affects the accessed via in fluid (finite)
free()
endcode The default implementation of c the simplest possible implementation of a new element requires only the specification of c we need to know which c Data affects the accessed via in the pressure degrees of freedom are to each element and are stored in the element s Internal c Data c Data that is external to the element An example is a load parameter such as the external pressure that acts on a shell structure Such c Data is accessed via pointers to External c Data As discussed all c Data contains values that are either free (i.e. unknown)
functions()
and code FiniteElement::J_eulerian (...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement<3,2> is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the see ref set_commands above The most important member functions implemented at this level include Functions that evaluate the shape functions (and their derivatives)
get_residuals()
the nodal coordinates represent the c Nodes fixed positions in this domain When the elastic body material which can be unknowns in the problem To avoid confusion between the the access function for the nodal code we provide a wrapper code in the case of generalised coordinates code Node::x_gen (...) \endcode always refers to the generalised Eulerian position and \code SolidNode endcode where the c MultiPhysicsElement inherits from c SinglePhysicsOneElement and c SinglePhysicsTwoElement A problem with this implementation arises when we consider where to initialise the residuals vector If the second single physics c get_residuals (...)
Definition at line 304 of file the_data_structure.txt.
Referenced by oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >::get_residuals().
interpolated_u() [1/2]
and code FiniteElement::J_eulerian (...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement<3,2> is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the see ref set_commands above The most important member functions implemented at this level include Functions that evaluate the shape in terms of the c FiniteElement s coordinates functions that determine whether a c Node is located at a particular coordinate Output functions that allow the element shapes to be plotted we specify a pointer to a spatial integration the default assignment can be over written at a higher level This is discussed in more detail in a<A HREF=`../../optimisation/html/index.html`> separate document</A> subsubsection Maths_Element we implement the equations that are represented by the specific element We implement the employing either the geometric shape functions that already exist on or employing additional shape functions defined at this level This allows us to write further member functions such as c interpolated_u (...)
Referenced by oomph::FluxTransportEquations< DIM >::calculate_element_averages(), oomph::HelmholtzBCElementBase< ELEMENT >::compute_contribution_to_fourier_components(), oomph::ScalarAdvectionEquations< DIM >::compute_error(), oomph::EulerEquations< DIM >::compute_error(), oomph::PoroelasticityEquations< 2 >::compute_error(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::compute_gamma_contribution(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::compute_gamma_contribution(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::contact_line_vectors(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_volume_flux(), oomph::SphericalNavierStokesEquations::d_kin_energy_dt(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::d_kin_energy_dt(), oomph::NavierStokesEquations< DIM >::d_kin_energy_dt(), oomph::SpaceTimeNavierStokesEquations< DIM >::d_kin_energy_dt(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::d_kin_energy_dt(), oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::TimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::NavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution(), oomph::RefineablePolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::PolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::PoroelasticityEquations< 2 >::fill_in_generic_residual_contribution(), oomph::RefineableAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_adv_diff(), oomph::SteadyAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_adv_diff(), oomph::AdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_adv_diff(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_adv_diff_flux(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_cons_adv_diff(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_cons_adv_diff(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::FluxTransportEquations< DIM >::fill_in_generic_residual_contribution_flux_transport(), oomph::FourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz(), oomph::RefineableHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::RefineablePMLHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::HelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::PMLHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_abc(), oomph::RefineableLinearWaveEquations< DIM >::fill_in_generic_residual_contribution_lin_wave(), oomph::LinearWaveEquations< DIM >::fill_in_generic_residual_contribution_lin_wave(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::NavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::PMLFourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz(), oomph::PoissonEquations< DIM >::fill_in_generic_residual_contribution_poisson(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::SphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_spherical_adv_diff_flux(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::SphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::RefineableUnsteadyHeatEquations< DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::UnsteadyHeatEquations< DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::WomersleyEquations< DIM >::fill_in_generic_residual_contribution_womersley(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineableNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::AxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::NavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::SpaceTimeNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::get_field(), oomph::ProjectableTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectableLinearElasticityElement< LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectableAxisymLinearElasticityElement< AXISYM_LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectableFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::get_field(), oomph::ProjectablePMLTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectableHelmholtzElement< HELMHOLTZ_ELEMENT >::get_field(), oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >::get_field(), oomph::ProjectablePoissonElement< POISSON_ELEMENT >::get_field(), oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::get_field(), oomph::ProjectablePMLHelmholtzElement< HELMHOLTZ_ELEMENT >::get_field(), oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::get_field(), oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::get_field(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::get_field(), oomph::ProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::get_field(), oomph::GeneralisedNewtonianProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::get_field(), oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::get_field(), oomph::ProjectableTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::get_field(), oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::get_field(), oomph::ProjectableTaylorHoodMixedOrderSpaceTimeElement< TAYLOR_HOOD_ELEMENT >::get_field(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::get_strain(), oomph::AxisymmetricLinearElasticityEquations::get_strain(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_total_flux(), oomph::get_total_flux(), oomph::WomersleyEquations< DIM >::get_volume_flux(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::integrate_u(), oomph::SteadyAxisymAdvectionDiffusionEquations::interpolated_u_adv_diff(), oomph::AdvectionDiffusionEquations< DIM >::interpolated_u_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::interpolated_u_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::interpolated_u_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_u_axi_nst(), oomph::AxisymmetricLinearElasticityEquationsBase::interpolated_u_axisymmetric_linear_elasticity(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::interpolated_u_cons_adv_diff(), oomph::interpolated_u_cons_axisym_adv_diff(), oomph::FourierDecomposedHelmholtzEquations::interpolated_u_fourier_decomposed_helmholtz(), oomph::AxisymFoepplvonKarmanEquations::interpolated_u_fvk(), oomph::HelmholtzEquations< DIM >::interpolated_u_helmholtz(), oomph::LinearWaveEquations< DIM >::interpolated_u_lin_wave(), oomph::LinearElasticityEquationsBase< DIM >::interpolated_u_linear_elasticity(), oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_u_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations::interpolated_u_linearised_nst(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::interpolated_u_nst(), oomph::NavierStokesEquations< DIM >::interpolated_u_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >::interpolated_u_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_u_nst(), oomph::PMLFourierDecomposedHelmholtzEquations::interpolated_u_pml_fourier_decomposed_helmholtz(), oomph::PMLHelmholtzEquations< DIM >::interpolated_u_pml_helmholtz(), oomph::PolarNavierStokesEquations::interpolated_u_pnst(), oomph::PoissonEquations< DIM >::interpolated_u_poisson(), oomph::SphericalAdvectionDiffusionEquations::interpolated_u_spherical_adv_diff(), oomph::SphericalNavierStokesEquations::interpolated_u_spherical_nst(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity(), oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::interpolated_u_time_harmonic_linear_elasticity(), oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::interpolated_u_time_harmonic_linear_elasticity(), oomph::UnsteadyHeatEquations< DIM >::interpolated_u_ust_heat(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::interpolated_u_ust_heat(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::interpolated_u_ust_heat(), oomph::WomersleyEquations< DIM >::interpolated_u_womersley(), oomph::C1CurvedElementBase< NNODE_1D >::my_interpolated_u_normal(), oomph::C1CurvedElementBase< NNODE_1D >::my_interpolated_u_normal1(), oomph::C1CurvedElementBase< NNODE_1D >::my_interpolated_u_tangential(), oomph::PoroelasticityEquations< 2 >::output(), oomph::LinearisedAxisymmetricNavierStokesEquations::output_veloc(), oomph::LinearisedNavierStokesEquations::output_veloc(), oomph::PolarNavierStokesEquations::output_veloc(), oomph::SphericalNavierStokesEquations::output_veloc(), oomph::AxisymmetricNavierStokesEquations::output_veloc(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::output_veloc(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output_veloc(), oomph::NavierStokesEquations< DIM >::output_veloc(), oomph::PolarNavierStokesEquations::strain_rate(), oomph::SphericalNavierStokesEquations::strain_rate(), and oomph::PolarNavierStokesEquations::strain_rate_by_r().
interpolated_u() [2/2]
fluid_element interpolated_u (s , u)
interpolation()
and code FiniteElement::J_eulerian (...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement<3,2> is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the see ref set_commands above The most important member functions implemented at this level include Functions that evaluate the shape in terms of the c FiniteElement s coordinates functions that determine whether a c Node is located at a particular coordinate Output functions that allow the element shapes to be plotted we specify a pointer to a spatial integration the default assignment can be over written at a higher level This is discussed in more detail in a<A HREF=`../../optimisation/html/index.html`> separate document</A> subsubsection Maths_Element we implement the equations that are represented by the specific element We implement the interpolation (s)
most()
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt (t,i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE most (but not all;see below)
nodes()
the nodal coordinate of type stores the derivative of the global position w r t to the element s coordinate The member function code nodes can become hanging nodes (i.e. nodes on an element 's edge/face that are not shared by the adjacent element)
Nodes()
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt (t,i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial (Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced we must evaluate mesh which requires the storage of the nodal position at a number of previous timesteps Storage for the positional history values is allocated by the c Node constructor A different c TimeStepper may be used to represent time derivatives of nodal so c Nodes store a separate pointer to a positional c TimeStepper [Note: By default, we allocate the same amount of storage for the history of the nodal positions as we do for the history of the nodal values; e.g. if a \c BDF<2> scheme is used to evaluate the time-derivatives of the fluid velocities, we assume that the same timestepping scheme is used (and the same amount of storage required) to determine the mesh velocities from the nodal positions.] For finite elements in which the global position of a point in an element is determined by interpolation from the position of the element s c Nodes (Lagrange-type elements)
p_fluid()
we provide an access function c p_fluid (...)
Referenced by oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output().
points()
the nodal coordinates represent the c Nodes fixed positions in this domain When the elastic body material points (and hence the \c Nodes) [new]
residuals()
endcode The default implementation of c the simplest possible implementation of a new element requires only the specification of c we need to know which c Data affects the residuals (and hence the Jacobian matrix)
Referenced by oomph::SurfactantTransportInterfaceElement::add_additional_residual_contributions_interface(), oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >::add_additional_residual_contributions_interface(), oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >::add_additional_residual_contributions_interface(), oomph::DGFaceElement::add_flux_contributions(), oomph::DGElement::add_flux_contributions_to_residuals(), oomph::PeriodicOrbitTemporalMesh< oomph::SpectralPeriodicOrbitElement< NNODE_1D > >::assemble_residuals(), oomph::PeriodicOrbitTemporalMesh< oomph::SpectralPeriodicOrbitElement< NNODE_1D > >::assemble_residuals_and_jacobian(), oomph::BlackBoxFDNewtonSolver::black_box_fd_newton_solve(), oomph::PeriodicOrbitEquations::fill_in_contribution_to_integrated_jacobian(), oomph::PeriodicOrbitEquations::fill_in_contribution_to_integrated_residuals(), oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::UnsteadyHeatFluxElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::LinearWaveFluxElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::ODEElement::fill_in_contribution_to_jacobian(), oomph::AdvectionDiffusionFluxElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::HelmholtzFluxElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::PoissonFluxElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::AxisymmetricSolidTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::FluxTransportEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::PseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_contribution_to_jacobian(), oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::fill_in_contribution_to_jacobian(), oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::BiharmonicFluxElement< DIM >::fill_in_contribution_to_jacobian(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_jacobian(), LinearisedQTaylorHoodMultiDomainElement::fill_in_contribution_to_jacobian(), LinearisedAxisymmetricQTaylorHoodMultiDomainElement::fill_in_contribution_to_jacobian(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::DarcyFaceElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::SolidTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::LinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::NetFluxControlElement::fill_in_contribution_to_jacobian(), oomph::NavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::ProjectableElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::PoroelasticityFaceElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::AxisymmetricPoroelasticityTractionElement< POROELASTICITY_BULK_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), LinearisedQCrouzeixRaviartMultiDomainElement::fill_in_contribution_to_jacobian(), LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement::fill_in_contribution_to_jacobian(), oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_jacobian(), oomph::LinearWaveEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::SteadyAxisymAdvectionDiffusionEquations::fill_in_contribution_to_jacobian(), oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >::fill_in_contribution_to_jacobian(), oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_jacobian(), oomph::ImmersedRigidBodyElement::fill_in_contribution_to_jacobian(), oomph::SphericalAdvectionDiffusionEquations::fill_in_contribution_to_jacobian(), oomph::UnsteadyHeatEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::FSIWallElement::fill_in_contribution_to_jacobian(), oomph::FourierDecomposedHelmholtzEquations::fill_in_contribution_to_jacobian(), oomph::TimeHarmonicLinearElasticityEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian(), oomph::HelmholtzEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::BiharmonicFluidBoundaryElement::fill_in_contribution_to_jacobian(), oomph::RefineableNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_contribution_to_jacobian(), RefineableLinearisedQTaylorHoodMultiDomainElement::fill_in_contribution_to_jacobian(), RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement::fill_in_contribution_to_jacobian(), oomph::AxisymmetricPVDEquations::fill_in_contribution_to_jacobian(), oomph::WomersleyEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::NavierStokesFluxControlElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian(), oomph::ElementWithExternalElement::fill_in_contribution_to_jacobian(), oomph::AxisymAdvectionDiffusionEquations::fill_in_contribution_to_jacobian(), oomph::PoissonEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::AdvectionDiffusionEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::FSIHermiteBeamElement::fill_in_contribution_to_jacobian(), oomph::PMLFourierDecomposedHelmholtzEquations::fill_in_contribution_to_jacobian(), oomph::AxisymmetricLinearElasticityEquations::fill_in_contribution_to_jacobian(), oomph::PVDEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::GeneralisedElement::fill_in_contribution_to_jacobian(), oomph::PMLHelmholtzEquations< DIM >::fill_in_contribution_to_jacobian(), RefineableLinearisedQCrouzeixRaviartMultiDomainElement::fill_in_contribution_to_jacobian(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_contribution_to_jacobian(), oomph::RefineableSolidTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement::fill_in_contribution_to_jacobian(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::fill_in_contribution_to_jacobian(), oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::fill_in_contribution_to_jacobian(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_jacobian(), oomph::FSIAxisymmetricLinearElasticityTractionElement< ELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::FSIDiagHermiteShellElement::fill_in_contribution_to_jacobian(), oomph::PolarNavierStokesEquations::fill_in_contribution_to_jacobian(), oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::PMLHelmholtzFluxElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::RefineablePseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_contribution_to_jacobian(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::SphericalNavierStokesEquations::fill_in_contribution_to_jacobian(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::AxisymmetricPVDEquationsWithPressure::fill_in_contribution_to_jacobian(), oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >::fill_in_contribution_to_jacobian(), oomph::FSISolidTractionElement< ELEMENT, DIM >::fill_in_contribution_to_jacobian(), oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian(), oomph::PVDEquationsWithPressure< DIM >::fill_in_contribution_to_jacobian(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian(), oomph::RefineableFSISolidTractionElement< ELEMENT, DIM >::fill_in_contribution_to_jacobian(), oomph::ElasticPointFluidInterfaceBoundingElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian(), oomph::NavierStokesEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_contribution_to_jacobian(), oomph::FiniteElement::fill_in_contribution_to_jacobian(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::fill_in_contribution_to_jacobian(), oomph::NavierStokesWomersleyPressureControlElement::fill_in_contribution_to_jacobian(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::SolidFiniteElement::fill_in_contribution_to_jacobian(), oomph::FluxTransportEquations< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::PseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::SphericalAdvectionDiffusionEquations::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::AdvectionDiffusionEquations< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::DisplacementBasedFoepplvonKarmanEquations::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::PolarNavierStokesEquations::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::RefineablePseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::SphericalNavierStokesEquations::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::PVDEquationsWithPressure< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::NavierStokesEquations< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::ODEElement::fill_in_contribution_to_mass_matrix(), oomph::FluxTransportEquations< DIM >::fill_in_contribution_to_mass_matrix(), oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::ODEElement::fill_in_contribution_to_residuals(), oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::AxisymmetricPVDEquations::fill_in_contribution_to_residuals(), oomph::BiharmonicEquations< DIM >::fill_in_contribution_to_residuals(), oomph::UnsteadyHeatFluxElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::LinearWaveFluxElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::AdvectionDiffusionFluxElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::HelmholtzFluxElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::PoissonFluxElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::AxisymmetricSolidTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::FluxTransportEquations< DIM >::fill_in_contribution_to_residuals(), oomph::PseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_contribution_to_residuals(), oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::fill_in_contribution_to_residuals(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::fill_in_contribution_to_residuals(), oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals(), oomph::BiharmonicFluxElement< DIM >::fill_in_contribution_to_residuals(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals(), oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::DarcyFaceElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::SolidTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::LinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::NetFluxControlElement::fill_in_contribution_to_residuals(), oomph::ProjectableElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::fill_in_contribution_to_residuals(), oomph::NavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::PoroelasticityFaceElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::FluidInterfaceBoundingElement::fill_in_contribution_to_residuals(), oomph::AxisymmetricPoroelasticityTractionElement< POROELASTICITY_BULK_ELEMENT >::fill_in_contribution_to_residuals(), oomph::AxisymFoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::DisplacementControlElement::fill_in_contribution_to_residuals(), oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_residuals(), oomph::SteadyAxisymAdvectionDiffusionEquations::fill_in_contribution_to_residuals(), oomph::LinearWaveEquations< DIM >::fill_in_contribution_to_residuals(), oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals(), oomph::ImmersedRigidBodyElement::fill_in_contribution_to_residuals(), oomph::FoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::SphericalAdvectionDiffusionEquations::fill_in_contribution_to_residuals(), oomph::YoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::UnsteadyHeatEquations< DIM >::fill_in_contribution_to_residuals(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_residuals(), oomph::FourierDecomposedHelmholtzEquations::fill_in_contribution_to_residuals(), oomph::TimeHarmonicLinearElasticityEquations< DIM >::fill_in_contribution_to_residuals(), oomph::BiharmonicFluidBoundaryElement::fill_in_contribution_to_residuals(), oomph::HelmholtzEquations< DIM >::fill_in_contribution_to_residuals(), oomph::RefineableNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_contribution_to_residuals(), oomph::WomersleyEquations< DIM >::fill_in_contribution_to_residuals(), oomph::LinearElasticityEquations< DIM >::fill_in_contribution_to_residuals(), oomph::NavierStokesFluxControlElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_contribution_to_residuals(), oomph::AxisymAdvectionDiffusionEquations::fill_in_contribution_to_residuals(), oomph::AdvectionDiffusionEquations< DIM >::fill_in_contribution_to_residuals(), oomph::PoissonEquations< DIM >::fill_in_contribution_to_residuals(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::PMLFourierDecomposedHelmholtzEquations::fill_in_contribution_to_residuals(), oomph::AxisymmetricLinearElasticityEquations::fill_in_contribution_to_residuals(), oomph::PVDEquations< DIM >::fill_in_contribution_to_residuals(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::fill_in_contribution_to_residuals(), oomph::FluidInterfaceElement::fill_in_contribution_to_residuals(), oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_contribution_to_residuals(), oomph::DisplacementBasedFoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_contribution_to_residuals(), oomph::PMLHelmholtzEquations< DIM >::fill_in_contribution_to_residuals(), oomph::LinearisedNavierStokesEquations::fill_in_contribution_to_residuals(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_contribution_to_residuals(), oomph::RefineableSolidTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::fill_in_contribution_to_residuals(), oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::fill_in_contribution_to_residuals(), oomph::fill_in_contribution_to_residuals(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_residuals(), oomph::FSIAxisymmetricLinearElasticityTractionElement< ELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::fill_in_contribution_to_residuals(), oomph::PolarNavierStokesEquations::fill_in_contribution_to_residuals(), oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::PMLHelmholtzFluxElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::HeightControlElement::fill_in_contribution_to_residuals(), oomph::RefineablePseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_contribution_to_residuals(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::fill_in_contribution_to_residuals(), oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::SphericalNavierStokesEquations::fill_in_contribution_to_residuals(), oomph::ClampedHermiteShellBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_contribution_to_residuals(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::AxisymmetricPVDEquationsWithPressure::fill_in_contribution_to_residuals(), oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_residuals(), oomph::PVDEquationsWithPressure< DIM >::fill_in_contribution_to_residuals(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_contribution_to_residuals(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_residuals(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_residuals(), oomph::NavierStokesEquations< DIM >::fill_in_contribution_to_residuals(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::SpaceTimeNavierStokesEquations< DIM >::fill_in_contribution_to_residuals(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_contribution_to_residuals(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::fill_in_contribution_to_residuals(), oomph::NavierStokesWomersleyPressureControlElement::fill_in_contribution_to_residuals(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::FSIAxisymmetricLinearElasticityTractionElement< ELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::fill_in_contribution_to_residuals_axisym_fsi_traction(), oomph::AxisymmetricPoroelasticityTractionElement< POROELASTICITY_BULK_ELEMENT >::fill_in_contribution_to_residuals_axisym_poroelasticity_face(), oomph::AxisymmetricPVDEquations::fill_in_contribution_to_residuals_axisym_pvd(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals_axisymmetric_linear_elasticity_traction(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::fill_in_contribution_to_residuals_axisymmetric_nst_traction(), oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals_beam(), oomph::DarcyFaceElement< ELEMENT >::fill_in_contribution_to_residuals_darcy_face(), oomph::PoroelasticityFaceElement< ELEMENT >::fill_in_contribution_to_residuals_darcy_face(), oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals_helmholtz_traction(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals_helmholtz_traction(), oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals_helmholtz_traction(), oomph::LinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals_linear_elasticity_traction(), oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_residuals_shell(), oomph::SolidTractionElement< ELEMENT >::fill_in_contribution_to_residuals_solid_traction(), oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals_time_harmonic_fourier_decomposed_linear_elasticity_traction(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals_time_harmonic_linear_elasticity_traction(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >::fill_in_contribution_to_residuals_time_harmonic_linear_elasticity_traction(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::RefineableLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity(), oomph::LinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity(), oomph::LinearisedNavierStokesEigenfunctionNormalisationElement::fill_in_generic_contribution_to_residuals_normalisation(), oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::RefineablePVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::PVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::TimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::VolumeConstraintElement::fill_in_generic_contribution_to_residuals_volume_constraint(), oomph::SolidFiniteElement::fill_in_generic_jacobian_for_solid_ic(), oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::NavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::PolarNavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution(), oomph::RefineablePolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::DarcyEquations< 2 >::fill_in_generic_residual_contribution(), oomph::PolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::PoroelasticityEquations< 2 >::fill_in_generic_residual_contribution(), oomph::AxisymmetricPoroelasticityEquations::fill_in_generic_residual_contribution(), oomph::RefineableAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_adv_diff(), oomph::SteadyAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_adv_diff(), oomph::AdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_adv_diff(), oomph::AdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_adv_diff_flux(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_adv_diff_flux(), oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_generic_residual_contribution_adv_diff_react(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_generic_residual_contribution_adv_diff_react(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::fill_in_generic_residual_contribution_axisym_poroelastic_fsi(), oomph::AxisymmetricPVDEquationsWithPressure::fill_in_generic_residual_contribution_axisym_pvd_with_pressure(), oomph::BiharmonicEquations< DIM >::fill_in_generic_residual_contribution_biharmonic(), oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_cons_adv_diff(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_cons_adv_diff(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::NavierStokesTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction(), oomph::NavierStokesFluxControlElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::fill_in_generic_residual_contribution_fluid_traction(), oomph::NetFluxControlElement::fill_in_generic_residual_contribution_flux_control(), oomph::FluxTransportEquations< DIM >::fill_in_generic_residual_contribution_flux_transport(), oomph::DGSpectralScalarAdvectionElement< 1, NNODE_1D >::fill_in_generic_residual_contribution_flux_transport(), oomph::DGSpectralScalarAdvectionElement< 2, NNODE_1D >::fill_in_generic_residual_contribution_flux_transport(), oomph::DGSpectralEulerElement< 1, NNODE_1D >::fill_in_generic_residual_contribution_flux_transport(), oomph::DGScalarAdvectionElement< 1, NNODE_1D >::fill_in_generic_residual_contribution_flux_transport(), oomph::DGSpectralEulerElement< 2, NNODE_1D >::fill_in_generic_residual_contribution_flux_transport(), oomph::DGScalarAdvectionElement< 2, NNODE_1D >::fill_in_generic_residual_contribution_flux_transport(), oomph::FourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_DtN_bc(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_flux(), oomph::RefineableFpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc(), oomph::RefineableFpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc(), oomph::RefineableFpPressureAdvDiffRobinBCElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc(), oomph::FpPressureAdvDiffRobinBCElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc(), oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc(), oomph::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >::fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::fill_in_generic_residual_contribution_fsi_no_slip_axisym(), oomph::RefineableHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::RefineablePMLHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::HelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::PMLHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_abc(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_DtN_bc(), oomph::HelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_flux(), oomph::PMLHelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_flux(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_generic_residual_contribution_helmholtz_flux_from_displacement(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_generic_residual_contribution_helmholtz_flux_from_displacement(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::fill_in_generic_residual_contribution_helmholtz_flux_from_displacement(), oomph::FluidInterfaceElement::fill_in_generic_residual_contribution_interface(), oomph::PointFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::RefineableLinearWaveEquations< DIM >::fill_in_generic_residual_contribution_lin_wave(), oomph::LinearWaveEquations< DIM >::fill_in_generic_residual_contribution_lin_wave(), oomph::LinearWaveFluxElement< ELEMENT >::fill_in_generic_residual_contribution_lin_wave_flux(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::NavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::PeriodicOrbitEquations::fill_in_generic_residual_contribution_orbit(), oomph::PMLFourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz_flux(), oomph::RefineablePoissonEquations< DIM >::fill_in_generic_residual_contribution_poisson(), oomph::PoissonEquations< DIM >::fill_in_generic_residual_contribution_poisson(), oomph::PoissonFluxElement< ELEMENT >::fill_in_generic_residual_contribution_poisson_flux(), oomph::NavierStokesWomersleyPressureControlElement::fill_in_generic_residual_contribution_pressure_control(), oomph::RefineablePVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), oomph::PVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::SphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::fill_in_generic_residual_contribution_spherical_adv_diff_flux(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::SphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::RefineableUnsteadyHeatEquations< DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::UnsteadyHeatEquations< DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::UnsteadyHeatFluxElement< ELEMENT >::fill_in_generic_residual_contribution_ust_heat_flux(), oomph::LineVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::AxisymmetricVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::SurfaceVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::WomersleyEquations< DIM >::fill_in_generic_residual_contribution_womersley(), oomph::SolidFiniteElement::fill_in_jacobian_for_solid_ic(), oomph::GeneralisedElement::fill_in_jacobian_from_external_by_fd(), oomph::ElementWithExternalElement::fill_in_jacobian_from_external_interaction_by_fd(), oomph::ElementWithExternalElement::fill_in_jacobian_from_external_interaction_field_by_fd(), oomph::ElementWithExternalElement::fill_in_jacobian_from_external_interaction_geometric_by_fd(), oomph::ElementWithMovingNodes::fill_in_jacobian_from_geometric_data(), oomph::GeneralisedElement::fill_in_jacobian_from_internal_by_fd(), oomph::RefineableElement::fill_in_jacobian_from_nodal_by_fd(), oomph::FiniteElement::fill_in_jacobian_from_nodal_by_fd(), oomph::RefineableSolidElement::fill_in_jacobian_from_solid_position_by_fd(), oomph::SolidFiniteElement::fill_in_jacobian_from_solid_position_by_fd(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd(), oomph::NavierStokesEquations< DIM >::fill_in_pressure_advection_diffusion_jacobian(), oomph::SpaceTimeNavierStokesEquations< DIM >::fill_in_pressure_advection_diffusion_jacobian(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_pressure_advection_diffusion_jacobian(), oomph::NavierStokesEquations< DIM >::fill_in_pressure_advection_diffusion_residuals(), oomph::SpaceTimeNavierStokesEquations< DIM >::fill_in_pressure_advection_diffusion_residuals(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_pressure_advection_diffusion_residuals(), oomph::SolidFiniteElement::fill_in_residuals_for_solid_ic(), oomph::PseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_shape_derivatives_by_fd(), oomph::RefineablePseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_shape_derivatives_by_fd(), oomph::Problem::get_fd_jacobian(), oomph::Problem::get_inverse_mass_matrix_times_residuals(), oomph::AssemblyHandler::get_jacobian(), oomph::FpPreconditionerAssemblyHandler::get_jacobian(), oomph::ExplicitTimeStepHandler::get_jacobian(), oomph::RefineableSolidQElement< 1 >::get_jacobian(), oomph::RefineableSolidQElement< 2 >::get_jacobian(), oomph::RefineableSolidQElement< 3 >::get_jacobian(), oomph::ParallelResidualsHandler::get_jacobian(), oomph::ParameterDerivativeHandler::get_jacobian(), oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >::get_jacobian(), oomph::ElementWithSpecificMovingNodes< ELEMENT, MacroElementNodeUpdateNode >::get_jacobian(), oomph::FoldHandler::get_jacobian(), oomph::ImposeFluxForWomersleyElement< DIM >::get_jacobian(), oomph::PseudoBucklingRingElement::get_jacobian(), oomph::PitchForkHandler::get_jacobian(), oomph::GeneralisedElement::get_jacobian(), oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >::get_jacobian(), oomph::HopfHandler::get_jacobian(), oomph::Problem::get_jacobian(), oomph::ElementWithSpecificMovingNodes< ELEMENT, MacroElementNodeUpdateNode >::get_jacobian_and_mass_matrix(), oomph::GeneralisedElement::get_jacobian_and_mass_matrix(), oomph::GeneralisedElement::get_mass_matrix(), oomph::AssemblyHandler::get_residuals(), oomph::FpPreconditionerAssemblyHandler::get_residuals(), oomph::ExplicitTimeStepHandler::get_residuals(), oomph::ParallelResidualsHandler::get_residuals(), oomph::ParameterDerivativeHandler::get_residuals(), oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >::get_residuals(), oomph::FoldHandler::get_residuals(), oomph::ImposeFluxForWomersleyElement< DIM >::get_residuals(), oomph::PseudoBucklingRingElement::get_residuals(), oomph::PitchForkHandler::get_residuals(), oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >::get_residuals(), oomph::GeneralisedElement::get_residuals(), oomph::HopfHandler::get_residuals(), oomph::Problem::get_residuals(), oomph::SolidFiniteElement::get_residuals_for_solid_ic(), oomph::PseudoBucklingRingElement::get_residuals_generic(), oomph::ImmersedRigidBodyElement::get_residuals_rigid_body_generic(), oomph::Problem::globally_convergent_line_search(), oomph::BlackBoxFDNewtonSolver::line_search(), oomph::Problem::parallel_sparse_assemble(), oomph::RefineableSolidTractionElement< ELEMENT >::refineable_fill_in_contribution_to_residuals_solid_traction(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::RefineableNavierStokesTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::ProjectableElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::residual_for_projection(), oomph::ProjectableDarcyElement< DARCY_ELEMENT >::residual_for_projection(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::residual_for_projection(), oomph::SolidICProblem::set_newmark_initial_condition_consistently(), oomph::HelmholtzMGPreconditioner< DIM >::setup_mg_structures(), oomph::MumpsSolver::solve(), oomph::HSL_MA42::solve(), oomph::DenseLU::solve(), oomph::FD_LU::solve(), oomph::SuperLUSolver::solve(), oomph::HSL_MA42::solve_for_one_dof(), oomph::SuperLUSolver::solve_transpose(), oomph::Problem::sparse_assemble_row_or_column_compressed(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_lists(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_maps(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_two_arrays(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_two_vectors(), and oomph::Problem::sparse_assemble_row_or_column_compressed_with_vectors_of_pairs().
s()
Vector<double> s (3)
scheme()
and code FiniteElement::J_eulerian (...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement<3,2> is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the see ref set_commands above The most important member functions implemented at this level include Functions that evaluate the shape in terms of the c FiniteElement s coordinates functions that determine whether a c Node is located at a particular coordinate Output functions that allow the element shapes to be plotted we specify a pointer to a spatial integration scheme (usually a Gauss rule)
their()
endcode The default implementation of c the simplest possible implementation of a new element requires only the specification of c we need to know which c Data affects the accessed via in the pressure degrees of freedom are to each element and are stored in the element s Internal c Data c Data that is external to the element An example is a load parameter such as the external pressure that acts on a shell structure Such c Data is accessed via pointers to External c Data As discussed all c Data contains values that are either we refer to the unknowns by their (equation)
u()
Vector<double> u (3)
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::adapt(), oomph::RefineableTriangleMesh< ELEMENT >::adapt(), oomph::BlockPreconditioner< CRDoubleMatrix >::block_setup(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::compute_norm(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::compute_norm(), oomph::UnsteadyHeatEquations< DIM >::compute_norm(), oomph::PoissonEquations< DIM >::compute_norm(), oomph::NavierStokesEquations< DIM >::compute_norm(), BinArray::coords_to_bin_index(), BinArray::coords_to_vectorial_bin_index(), oomph::SolutionFunctor::derivative(), oomph::ODEElement::derivative_function(), oomph::FluxTransportEquations< DIM >::dflux_du(), oomph::ODEElement::fill_in_contribution_to_jacobian(), oomph::ODEElement::fill_in_contribution_to_residuals(), oomph::PeriodicOrbitEquations::fill_in_generic_residual_contribution_orbit(), oomph::ScalarAdvectionEquations< DIM >::flux(), oomph::EulerEquations< DIM >::flux(), RefineableBin::get_bin_boundaries(), RefineableBinArray::get_bin_boundaries(), oomph::PressureAdvectionDiffusionValidation::get_exact_u(), BinArray::get_neighbouring_bins_helper(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_solid(), oomph::BiharmonicFluidProblem< DIM >::impose_fluid_flow_on_edge(), oomph::PoroelasticityEquations< 2 >::interpolated_q(), oomph::DGFaceElement::interpolated_u(), oomph::DGEulerFaceReflectionElement< ELEMENT >::interpolated_u(), oomph::FluxTransportEquations< DIM >::interpolated_u_flux_transport(), oomph::FourierDecomposedHelmholtzEquations::output(), oomph::HelmholtzEquations< DIM >::output(), oomph::EulerEquations< DIM >::output(), oomph::PMLFourierDecomposedHelmholtzEquations::output(), oomph::PMLHelmholtzEquations< DIM >::output(), oomph::TimeHarmonicLinearElasticityEquations< DIM >::output(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output(), oomph::LinearElasticityEquations< DIM >::output(), oomph::AxisymmetricLinearElasticityEquations::output(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output(), oomph::PMLHelmholtzEquations< DIM >::output_imag(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output_imag(), oomph::FourierDecomposedHelmholtzEquations::output_real(), oomph::HelmholtzEquations< DIM >::output_real(), oomph::PMLFourierDecomposedHelmholtzEquations::output_real(), oomph::PMLHelmholtzEquations< DIM >::output_real(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output_real(), oomph::PMLHelmholtzEquations< DIM >::output_total_real(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::output_total_real(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::pin_all_non_pressure_dofs(), oomph::EulerEquations< DIM >::pressure(), oomph::HelmholtzEquations< DIM >::scalar_value_paraview(), oomph::PMLHelmholtzEquations< DIM >::scalar_value_paraview(), oomph::BiharmonicProblem< DIM >::set_dirichlet_boundary_condition(), oomph::BandedBlockTriangularPreconditioner< MATRIX >::setup(), oomph::BlockTriangularPreconditioner< MATRIX >::setup(), oomph::PseudoElasticPreconditionerSubsidiaryBlockPreconditionerOld::setup(), and oomph::RungeKutta< ORDER >::timestep().
values() [1/2]
often abbreviated as dof b History b history values are but b not b the values at previous timesteps b Pinned c c c Mesh and c Problem subsection data Data The most elementary data structure in c oomph lib is c these values fall into two and those that must be determined as part of the solution c Data stores a value a double precision number the values of the unknowns are determined by the solution of a system of algebraic equations The solution of this system usually requires c Data also stores a (long) integer that represents the number of the unknown in the global numbering scheme. \b Convention for in a fluids we need to store three velocity components at every node c Data allows the storage of multiple values (all of which can either be pinned or free, and all of which have their own global equation number)
values() [2/2]
endcode returns the global equation number c i_global corresponding to the equation number c i_local The equation numbers of the internal and external c Data are stored in the private arrays c Internal_local_eqn and c accessed by the functions c GeneralisedElement::internal_local_eqn (...) and \c GeneralisedElement see section ref Hanging_Nodes for further details When c Nodes are created in it is important that c Nodes of the correct type with the appropriate amount of storage are created For Poisson elements require c Nodes that provide storage for a single value at each c whereas Taylor Navier Stokes elements require storage for three values (two velocities and one pressure)
Variable Documentation
above
endcode The default implementation of c the simplest possible implementation of a new element requires only the specification of c we need to know which c Data affects the accessed via in the pressure degrees of freedom are to each element and are stored in the element s Internal c Data c Data that is external to the element An example is a load parameter such as the external pressure that acts on a shell structure Such c Data is accessed via pointers to External c Data As discussed above
Definition at line 370 of file the_data_structure.txt.
again
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt (t,i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial (Eulerian) coordinates. The nodal positions are accessed by the member function \code Node again
Definition at line 149 of file the_data_structure.txt.
always
often abbreviated as dof b History b history values are but b not b always
Definition at line 45 of file the_data_structure.txt.
and
and code FiniteElement::J_eulerian (...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement<3,2> is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the see ref set_commands above The most important member functions implemented at this level include Functions that evaluate the shape in terms of the c FiniteElement s coordinates and
Definition at line 304 of file the_data_structure.txt.
below
mainpage The data structure section intro Introduction c oomph lib is big ! This document gives a bottom up overview of the library s data structure and discusses how the various objects interact In addition to the detailed discussion provided below
Definition at line 7 of file the_data_structure.txt.
boundaries
in the role of the member functions c Node::position () and \c Node the latter case arises if the c Node is located on edges and corners of the mesh Storage of this information facilitates the automatic determination of boundary conditions for new c Nodes that are created during mesh refinement n The majority of the c Nodes will b not be located on boundaries
Definition at line 201 of file the_data_structure.txt.
Referenced by oomph::RefineableQElement< 3 >::build(), oomph::RefineableQElement< 2 >::build(), oomph::BackwardStepQuadMesh< ELEMENT >::build_mesh(), oomph::Missing_masters_functions::get_required_master_nodal_information_helper(), oomph::Multi_domain_functions::get_required_master_nodal_information_helper(), oomph::Missing_masters_functions::get_required_nodal_information_helper(), oomph::Multi_domain_functions::get_required_nodal_information_helper(), oomph::RefineableTriangleMesh< ELEMENT >::get_required_nodal_information_helper(), oomph::RefineableTriangleMesh< ELEMENT >::get_required_nodal_information_load_balance_helper(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::p_refine(), oomph::RefineableQSpectralElement< 2 >::rebuild_from_sons(), oomph::RefineableQSpectralElement< 3 >::rebuild_from_sons(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::rebuild_from_sons(), and oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::rebuild_from_sons().
BoundaryNodes
in the role of the member functions c Node::position () and \c Node the latter case arises if the c Node is located on edges and corners of the mesh Storage of this information facilitates the automatic determination of boundary conditions for new c Nodes that are created during mesh refinement n The majority of the c Nodes will b not be located on and providing storage for the boundary information in every c Node object is rather wasteful The derived class c BoundaryNode adds the required additional storage to the c Node class and it follows that all c Nodes that could lie on boundaries must be c BoundaryNodes
Definition at line 214 of file the_data_structure.txt.
categories
often abbreviated as dof b History b history values are but b not b the values at previous timesteps b Pinned c c c Mesh and c Problem subsection data Data The most elementary data structure in c oomph lib is c these values fall into two categories
Definition at line 65 of file the_data_structure.txt.
classes
mainpage The data structure section intro Introduction c oomph lib is big ! This document gives a bottom up overview of the library s data structure and discusses how the various objects interact In addition to the detailed discussion provided the following doxygen generated lists indices provide quick access to the documentation of c oomph lib s classes
Definition at line 25 of file the_data_structure.txt.
computations
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt (t,i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE computations
Definition at line 145 of file the_data_structure.txt.
constructor
and code FiniteElement::J_eulerian (...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement<3,2> is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the constructor
Definition at line 503 of file the_data_structure.txt.
conversely
and code FiniteElement::J_eulerian (...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement<3,2> is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the see ref set_commands above The most important member functions implemented at this level include Functions that evaluate the shape in terms of the c FiniteElement s coordinates conversely
Definition at line 540 of file the_data_structure.txt.
coordinates
endcode returns the global equation number c i_global corresponding to the equation number c i_local The equation numbers of the internal and external c Data are stored in the private arrays c Internal_local_eqn and c accessed by the functions c GeneralisedElement::internal_local_eqn (...) and \c GeneralisedElement see section ref Hanging_Nodes for further details When c Nodes are created in it is important that c Nodes of the correct type with the appropriate amount of storage are created For Poisson elements require c Nodes that provide storage for a single value at each c whereas Taylor Navier Stokes elements require storage for three but only two values (the two velocities) at all others. The member function \code FiniteElement by default the spatial dimension of the c FiniteElement s c Nodes is assumed to be the same For code FiniteElement::set_dimension (2) \endcode sets both the spatial dimension of the element and the spatial dimension of its \c Nodes to be two. If the nodal dimension is not the same as the dimension of the element the member function \code FiniteElement code endcode returns the derivative of the shape functions with respect to the Eulerian coordinates
Definition at line 502 of file the_data_structure.txt.
Data
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt (t,i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c Data
Definition at line 148 of file the_data_structure.txt.
Referenced by oomph::AxisymmetricQCrouzeixRaviartElement::AxisymmetricQCrouzeixRaviartElement(), oomph::AxisymmetricTCrouzeixRaviartElement::AxisymmetricTCrouzeixRaviartElement(), oomph::AxisymQPVDElementWithPressure::AxisymQPVDElementWithPressure(), oomph::ODEElement::build(), oomph::Circle::Circle(), oomph::DisplacementControlElement::DisplacementControlElement(), oomph::Ellipse::Ellipse(), oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::FoepplvonKarmanVolumeConstraintElement(), oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::further_build(), oomph::PRefineableQCrouzeixRaviartElement< DIM >::further_build(), oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement(), oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::GeneralisedNewtonianQCrouzeixRaviartElement(), oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::GeneralisedNewtonianTCrouzeixRaviartElement(), oomph::HeightControlElement::HeightControlElement(), oomph::ImposeFluxForWomersleyElement< DIM >::ImposeFluxForWomersleyElement(), oomph::ImmersedRigidBodyElement::initialise(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::LinearisedAxisymmetricQCrouzeixRaviartElement(), oomph::LinearisedNavierStokesEigenfunctionNormalisationElement::LinearisedNavierStokesEigenfunctionNormalisationElement(), oomph::LinearisedQCrouzeixRaviartElement::LinearisedQCrouzeixRaviartElement(), oomph::NavierStokesWomersleyPressureControlElement::NavierStokesWomersleyPressureControlElement(), oomph::NetFluxControlElement::NetFluxControlElement(), oomph::PolarCrouzeixRaviartElement::PolarCrouzeixRaviartElement(), oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement(), oomph::PRefineableQCrouzeixRaviartElement< DIM >::PRefineableQCrouzeixRaviartElement(), oomph::PseudoBucklingRing::PseudoBucklingRing(), oomph::QCrouzeixRaviartElement< DIM >::QCrouzeixRaviartElement(), oomph::QPVDElementWithPressure< DIM >::QPVDElementWithPressure(), oomph::QSphericalCrouzeixRaviartElement::QSphericalCrouzeixRaviartElement(), oomph::Spine::Spine(), oomph::StraightLine::StraightLine(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::TAxisymmetricPoroelasticityElement(), oomph::TCrouzeixRaviartElement< DIM >::TCrouzeixRaviartElement(), oomph::TPoroelasticityElement< ORDER >::TPoroelasticityElement(), oomph::TRaviartThomasDarcyElement< ORDER >::TRaviartThomasDarcyElement(), oomph::VolumeConstraintElement::VolumeConstraintElement(), and oomph::WomersleyProblem< WOMERSLEY_ELEMENT, DIM >::WomersleyProblem().
deforms
the nodal coordinates represent the c Nodes fixed positions in this domain When the elastic body deforms
Definition at line 224 of file the_data_structure.txt.
Direct
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives Direct
Definition at line 102 of file the_data_structure.txt.
document
mainpage The data structure section intro Introduction c oomph lib is big ! This document gives a bottom up overview of the library s data structure and discusses how the various objects interact In addition to the detailed discussion provided the following doxygen generated lists indices provide quick access to the documentation of c oomph lib s we usually replace the list of arguments to functions accessible via the links at the top of this page subsection technical_terms Technical terms Throughout this document
Definition at line 33 of file the_data_structure.txt.
domain
see ref meshes for further details b the governing equations are discretised in a fixed Lagrangian domain
Definition at line 223 of file the_data_structure.txt.
Referenced by oomph::Mesh::classify_halo_and_haloed_nodes(), oomph::Mesh::doc_mesh_distribution(), oomph::HermiteQuadMesh< ELEMENT >::HermiteQuadMesh(), oomph::Mesh::prune_halo_elements_and_nodes(), oomph::Problem::remove_null_pointers_from_external_halo_node_storage(), oomph::Mesh::remove_null_pointers_from_external_halo_node_storage(), and oomph::Mesh::synchronise_shared_nodes().
el
GeneralisedElement el
Definition at line 387 of file the_data_structure.txt.
element
the nodal coordinates represent the c Nodes fixed positions in this domain When the elastic body material which can be unknowns in the problem To avoid confusion between the the access function for the nodal code we provide a wrapper code in the case of generalised coordinates code Node::x_gen (...) \endcode always refers to the generalised Eulerian position and \code SolidNode endcode where the c MultiPhysicsElement inherits from c SinglePhysicsOneElement and c SinglePhysicsTwoElement A problem with this implementation arises when we consider where to initialise the residuals vector If the second single physics c then the contribution of the first single physics element will be negated When writing a single physics element
Definition at line 302 of file the_data_structure.txt.
Referenced by oomph::RefineableQElement< 3 >::get_boundaries().
elements
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt (t,i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial (Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced we must evaluate mesh which requires the storage of the nodal position at a number of previous timesteps Storage for the positional history values is allocated by the c Node constructor A different c TimeStepper may be used to represent time derivatives of nodal so c Nodes store a separate pointer to a positional c TimeStepper [Note: By default, we allocate the same amount of storage for the history of the nodal positions as we do for the history of the nodal values; e.g. if a \c BDF<2> scheme is used to evaluate the time-derivatives of the fluid velocities, we assume that the same timestepping scheme is used (and the same amount of storage required) to determine the mesh velocities from the nodal positions.] For finite elements in which the global position of a point in an element is determined by interpolation from the position of the element s c we need only store the spatial position of the c Nodes In many other the interpolation of the geometry requires additional e g the derivative of the mapping between and global coordinates we allow the storage of additional positional variables at each c so in every c Node has a number of e generalised coordinates for each spatial coordinate direction For for nodes in Hermite elements
Definition at line 188 of file the_data_structure.txt.
Referenced by oomph::Z2ErrorEstimator::get_element_errors(), and oomph::METIS::partition_mesh().
example
endcode returns the global equation number c i_global corresponding to the equation number c i_local The equation numbers of the internal and external c Data are stored in the private arrays c Internal_local_eqn and c accessed by the functions c GeneralisedElement::internal_local_eqn (...) and \c GeneralisedElement see section ref Hanging_Nodes for further details When c Nodes are created in it is important that c Nodes of the correct type with the appropriate amount of storage are created For Poisson elements require c Nodes that provide storage for a single value at each c whereas Taylor Navier Stokes elements require storage for three but only two values (the two velocities) at all others. The member function \code FiniteElement by default the spatial dimension of the c FiniteElement s c Nodes is assumed to be the same For example
Definition at line 446 of file the_data_structure.txt.
External_local_eqn
endcode returns the global equation number c i_global corresponding to the equation number c i_local The equation numbers of the internal and external c Data are stored in the private arrays c Internal_local_eqn and c External_local_eqn
Definition at line 398 of file the_data_structure.txt.
features
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt (t,i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial (Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced features
Definition at line 164 of file the_data_structure.txt.
Finally
and code FiniteElement::J_eulerian (...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement<3,2> is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the see ref set_commands above The most important member functions implemented at this level include Functions that evaluate the shape in terms of the c FiniteElement s coordinates functions that determine whether a c Node is located at a particular coordinate Output functions that allow the element shapes to be plotted Finally
Definition at line 544 of file the_data_structure.txt.
fluid_element
and code FiniteElement::J_eulerian (...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement<3,2> is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the see ref set_commands above The most important member functions implemented at this level include Functions that evaluate the shape in terms of the c FiniteElement s coordinates functions that determine whether a c Node is located at a particular coordinate Output functions that allow the element shapes to be plotted we specify a pointer to a spatial integration the default assignment can be over written at a higher level This is discussed in more detail in a<A HREF=`../../optimisation/html/index.html`> separate document</A> subsubsection Maths_Element we implement the equations that are represented by the specific element We implement the employing either the geometric shape functions that already exist on or employing additional shape functions defined at this level This allows us to write further member functions such as c which compute the i th velocity component at the coordinate c s like this code SomeFluidElement fluid_element
Definition at line 566 of file the_data_structure.txt.
free
often abbreviated as dof b History b history values are but b not b the values at previous timesteps b Pinned free
Definition at line 53 of file the_data_structure.txt.
Referenced by oomph::TriangleHelper::clear_triangulateio(), and print_stacktrace().
functions
endcode When writing these wrapper functions
Definition at line 594 of file the_data_structure.txt.
general
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt (t,i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial (Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced we must evaluate mesh which requires the storage of the nodal position at a number of previous timesteps Storage for the positional history values is allocated by the c Node constructor A different c TimeStepper may be used to represent time derivatives of nodal so c Nodes store a separate pointer to a positional c TimeStepper [Note: By default, we allocate the same amount of storage for the history of the nodal positions as we do for the history of the nodal values; e.g. if a \c BDF<2> scheme is used to evaluate the time-derivatives of the fluid velocities, we assume that the same timestepping scheme is used (and the same amount of storage required) to determine the mesh velocities from the nodal positions.] For finite elements in which the global position of a point in an element is determined by interpolation from the position of the element s c we need only store the spatial position of the c Nodes In many other the interpolation of the geometry requires additional e g the derivative of the mapping between and global coordinates we allow the storage of additional positional variables at each c so in general
Definition at line 186 of file the_data_structure.txt.
GeneralisedElement
often abbreviated as dof b History b history values are but b not b the values at previous timesteps b Pinned c c GeneralisedElement
Definition at line 54 of file the_data_structure.txt.
Hence
endcode When writing these wrapper direct access to the nodal values should be avoided to ensure that the element remains functional in the presence of hanging nodes Hence
Definition at line 597 of file the_data_structure.txt.
Hood
endcode returns the global equation number c i_global corresponding to the equation number c i_local The equation numbers of the internal and external c Data are stored in the private arrays c Internal_local_eqn and c accessed by the functions c GeneralisedElement::internal_local_eqn (...) and \c GeneralisedElement see section ref Hanging_Nodes for further details When c Nodes are created in it is important that c Nodes of the correct type with the appropriate amount of storage are created For Poisson elements require c Nodes that provide storage for a single value at each c whereas Taylor Hood
Definition at line 443 of file the_data_structure.txt.
however
the nodal coordinates represent the c Nodes fixed positions in this domain When the elastic body material which can be unknowns in the problem To avoid confusion between the the access function for the nodal code we provide a wrapper code in the case of generalised coordinates code Node::x_gen (...) \endcode always refers to the generalised Eulerian position and \code SolidNode endcode where the c MultiPhysicsElement inherits from c SinglePhysicsOneElement and c SinglePhysicsTwoElement A problem with this implementation arises when we consider where to initialise the residuals vector If the second single physics c then the contribution of the first single physics element will be negated When writing a single physics however
Definition at line 213 of file the_data_structure.txt.
i_global
unsigned i_global =el.eqn_number(i_local)
Definition at line 391 of file the_data_structure.txt.
Referenced by oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::add_element_contribution_to_aux_integral(), oomph::DoubleVectorHaloScheme::DoubleVectorHaloScheme(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_lists(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_maps(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_two_arrays(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_two_vectors(), and oomph::Problem::sparse_assemble_row_or_column_compressed_with_vectors_of_pairs().
instance
endcode returns the global equation number c i_global corresponding to the equation number c i_local The equation numbers of the internal and external c Data are stored in the private arrays c Internal_local_eqn and c accessed by the functions c GeneralisedElement::internal_local_eqn (...) and \c GeneralisedElement see section ref Hanging_Nodes for further details When c Nodes are created in it is important that c Nodes of the correct type with the appropriate amount of storage are created For instance
Definition at line 73 of file the_data_structure.txt.
Level
and code FiniteElement::J_eulerian (...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement<3,2> is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the see ref set_commands above The most important member functions implemented at this level include Functions that evaluate the shape in terms of the c FiniteElement s coordinates functions that determine whether a c Node is located at a particular coordinate Output functions that allow the element shapes to be plotted we specify a pointer to a spatial integration the default assignment can be over written at a higher level This is discussed in more detail in a<A HREF=`../../optimisation/html/index.html`> separate document</A> subsubsection Maths_Element Level
Definition at line 556 of file the_data_structure.txt.
level
and code FiniteElement::J_eulerian (...) \endcode returns the Jacobian of the mapping from Eulerian coordinates to local coordinates. - The function \c GeneralisedElement c QElement<3,2> is an node brick element with a trilinear mapping between and global coordinates The dimension and the number of c Nodes must be set by calling the appropriate c set_ functions in the see ref set_commands above The most important member functions implemented at this level include Functions that evaluate the shape in terms of the c FiniteElement s coordinates functions that determine whether a c Node is located at a particular coordinate Output functions that allow the element shapes to be plotted we specify a pointer to a spatial integration the default assignment can be over written at a higher level This is discussed in more detail in a<A HREF=`../../optimisation/html/index.html`> separate document</A> subsubsection Maths_Element we implement the equations that are represented by the specific element We implement the employing either the geometric shape functions that already exist on level
Definition at line 560 of file the_data_structure.txt.
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::adapt(), oomph::Multi_domain_functions::aux_setup_multi_domain_interaction(), oomph::HypreHelpers::euclid_settings_helper(), NonRefineableBinArray::fill_bin_by_diffusion(), oomph::Problem::get_data_to_be_sent_during_load_balancing(), oomph::TreeBasedRefineableMeshBase::get_elements_at_refinement_level(), oomph::RefineableElement::get_father_at_refinement_level(), oomph::Problem::get_flat_packed_refinement_pattern_for_load_balancing(), BinArray::get_neighbouring_bins_helper(), oomph::TreeBasedRefineableMeshBase::get_refinement_levels(), oomph::TreeBasedRefineableMeshBase::get_refinement_pattern(), oomph::HelmholtzMGPreconditioner< DIM >::interpolate_and_correct(), oomph::MGSolver< DIM >::interpolate_and_correct(), oomph::HelmholtzMGPreconditioner< DIM >::interpolation_matrix_set(), oomph::MGSolver< DIM >::interpolation_matrix_set(), oomph::MGSolver< DIM >::interpolation_self_test(), oomph::HelmholtzMGPreconditioner< DIM >::maximum_edge_width(), oomph::MGSolver< DIM >::modify_restriction_matrices(), oomph::HelmholtzMGPreconditioner< DIM >::post_smooth(), oomph::MGSolver< DIM >::post_smooth(), oomph::HelmholtzMGPreconditioner< DIM >::pre_smooth(), oomph::MGSolver< DIM >::pre_smooth(), oomph::Mesh::prune_halo_elements_and_nodes(), oomph::Problem::refine_distributed_base_mesh(), oomph::HelmholtzMGPreconditioner< DIM >::residual_norm(), oomph::MGSolver< DIM >::residual_norm(), oomph::HelmholtzMGPreconditioner< DIM >::restrict_residual(), oomph::MGSolver< DIM >::restrict_residual(), oomph::MGSolver< DIM >::restriction_self_test(), oomph::Problem::send_refinement_info_helper(), oomph::HelmholtzMGPreconditioner< DIM >::setup_interpolation_matrices(), oomph::MGSolver< DIM >::setup_interpolation_matrices(), oomph::HelmholtzMGPreconditioner< DIM >::setup_interpolation_matrices_unstructured(), oomph::MGSolver< DIM >::setup_interpolation_matrices_unstructured(), oomph::HelmholtzMGPreconditioner< DIM >::setup_mg_hierarchy(), oomph::MGSolver< DIM >::setup_mg_hierarchy(), oomph::HelmholtzMGPreconditioner< DIM >::setup_mg_structures(), oomph::RefineableBrickMesh< ELEMENT >::setup_octree_forest(), and oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest().
meaning
mainpage The data structure section intro Introduction c oomph lib is big ! This document gives a bottom up overview of the library s data structure and discusses how the various objects interact In addition to the detailed discussion provided the following doxygen generated lists indices provide quick access to the documentation of c oomph lib s we usually replace the list of arguments to functions accessible via the links at the top of this page subsection technical_terms Technical terms Throughout this certain commonly used terms have a specific technical meaning
Definition at line 40 of file the_data_structure.txt.
n
endcode We introduce wrapper functions to access function so that we can formulate The Maths in generic terms Rather than referring to the pressure at node c via code unsigned n
Definition at line 582 of file the_data_structure.txt.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::adapt(), oomph::RefineableGmshTetMesh< ELEMENT >::adapt(), oomph::RefineableTriangleMesh< ELEMENT >::adapt(), oomph::Problem::adapt(), oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >::adapt_temporal_mesh(), oomph::FaceElement::add_additional_values(), oomph::Mesh::add_boundary_node(), oomph::UnstructuredTwoDMeshGeometryBase::add_boundary_segment_node(), oomph::Problem::add_eigenvector_to_dofs(), oomph::DiskLikeGeomObjectWithBoundaries::add_region_coordinates(), oomph::TriangleMesh< ELEMENT >::add_shared_boundary_node(), oomph::BlockPreconditioner< CRDoubleMatrix >::any_mesh_distributed(), oomph::ElementWithMovingNodes::assemble_set_of_all_geometric_data(), oomph::VectorMatrix< VALUE_TYPE >::assign(), oomph::SpectralElement::assign_all_generic_local_eqn_numbers(), oomph::OneDLagrangianMesh< ELEMENT >::assign_default_element_gradients(), oomph::Problem::assign_eigenvector_to_dofs(), oomph::ElementWithExternalElement::assign_external_interaction_data_local_eqn_numbers(), oomph::RefineableElement::assign_hanging_local_eqn_numbers(), oomph::Mesh::assign_initial_values_impulsive(), oomph::GeneralisedElement::assign_local_eqn_numbers(), oomph::FiniteElement::assign_nodal_local_eqn_numbers(), oomph::RefineableSolidElement::assign_solid_hanging_local_eqn_numbers(), oomph::SolidFiniteElement::assign_solid_local_eqn_numbers(), oomph::OneDLagrangianMesh< ELEMENT >::assign_undeformed_positions(), oomph::CircularCylindricalShellMesh< ELEMENT >::assign_undeformed_positions(), oomph::Multi_domain_functions::aux_setup_multi_domain_interaction(), oomph::MumpsSolver::backsub(), oomph::DenseLU::backsub(), oomph::SuperLUSolver::backsub_serial(), oomph::SuperLUSolver::backsub_transpose_serial(), oomph::SolidICProblem::backup_original_state(), oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::BackupMeshForProjection(), oomph::BlockPreconditioner< CRDoubleMatrix >::block_setup(), oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::body_force(), oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::body_force(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::body_force(), oomph::LinearElasticityEquationsBase< DIM >::body_force(), oomph::PVDEquationsBase< DIM >::body_force(), oomph::AxisymmetricLinearElasticityEquationsBase::body_force(), oomph::Mesh::boundary_node_pt(), oomph::SolidMesh::boundary_node_pt(), oomph::TriangleMesh< ELEMENT >::boundary_segment_node_pt(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh(), oomph::RefineableQElement< 1 >::build(), oomph::RefineableSolidQElement< 2 >::build(), oomph::CRMatrix< std::complex< double > >::build(), oomph::CCMatrix< std::complex< double > >::build(), oomph::Mesh::build_face_mesh(), oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), oomph::TriangleMesh< ELEMENT >::build_from_scaffold(), oomph::AddedMainNumberingLookup::build_identity_map(), oomph::GmshTetMesh< ELEMENT >::build_it(), oomph::ExtrudedCubeMeshFromQuadMesh< ELEMENT >::build_mesh(), oomph::TetgenMesh< ELEMENT >::build_tetgenio(), oomph::TwoLayerSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::VectorMatrix< VALUE_TYPE >::build_vectors(), oomph::VectorMatrix< VALUE_TYPE >::build_vectors_and_value(), oomph::CRMatrix< std::complex< double > >::build_without_copy(), oomph::CCMatrix< std::complex< double > >::build_without_copy(), oomph::FaceElement::bulk_node_number(), oomph::Mesh::calculate_predictions(), oomph::CCMatrix< std::complex< double > >::CCMatrix(), oomph::Hankel_functions_for_helmholtz_problem::CHankel_first(), oomph::TriangleMesh< ELEMENT >::check_connections_of_polyline_nodes(), oomph::Mesh::check_halo_schemes(), oomph::RefineableQElement< 3 >::check_integrity(), oomph::Mesh::classify_halo_and_haloed_nodes(), oomph::InexactSubBiharmonicPreconditioner::clean_up_memory(), oomph::TreeForest::close_hanging_node_files(), oomph::TreeBasedRefineableMeshBase::complete_hanging_nodes(), oomph::SpineElement< FaceGeometry< ELEMENT > >::complete_setup_of_dependencies(), oomph::HelmholtzBCElementBase< ELEMENT >::compute_contribution_to_fourier_components(), oomph::HelmholtzDtNMesh< ELEMENT >::compute_fourier_components(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::compute_gamma_contribution(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::compute_gamma_contribution(), oomph::RefineableTriangleMesh< ELEMENT >::compute_global_node_names_and_shared_nodes(), oomph::RefineableTetMeshBase::compute_volume_target(), oomph::FiniteElement::construct_boundary_node(), oomph::SolidFiniteElement::construct_boundary_node(), oomph::DGElement::construct_boundary_nodes_and_faces(), oomph::FiniteElement::construct_node(), oomph::SolidFiniteElement::construct_node(), oomph::DGElement::construct_nodes_and_faces(), oomph::TriangleMesh< ELEMENT >::convex_hull(), oomph::LinearisedQCrouzeixRaviartElement::copy_efunction_to_normalisation(), oomph::Problem::copy_haloed_eqn_numbers_helper(), oomph::TwoDimensionalPMLHelper::create_bottom_left_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_bottom_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_bottom_right_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_left_pml_mesh(), oomph::GmshTetScaffoldMesh::create_mesh_from_msh_file(), oomph::RefineableTriangleMesh< ELEMENT >::create_new_shared_boundaries(), oomph::TwoDimensionalPMLHelper::create_right_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_top_left_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_top_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_top_right_pml_mesh(), oomph::CRMatrix< std::complex< double > >::CRMatrix(), oomph::CylinderWithFlagMesh< ELEMENT >::CylinderWithFlagMesh(), oomph::PoroelasticityEquations< 2 >::d2u_dt2(), oomph::AxisymmetricPoroelasticityEquations::d2u_dt2(), oomph::AxisymmetricLinearElasticityEquationsBase::d2u_dt2_axisymmetric_linear_elasticity(), oomph::LinearWaveEquations< DIM >::d2u_dt2_lin_wave(), oomph::LinearElasticityEquationsBase< DIM >::d2u_dt2_linear_elasticity(), oomph::ProjectableDarcyElement< DARCY_ELEMENT >::data_values_of_field(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::data_values_of_field(), oomph::ProjectableAxisymmetricCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::data_values_of_field(), oomph::GeneralisedNewtonianProjectableAxisymmetricCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::data_values_of_field(), oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::data_values_of_field(), oomph::ProjectableCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::data_values_of_field(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::dc_dt_adv_diff_react(), oomph::RefineableElement::deactivate_element(), oomph::TetgenMesh< ELEMENT >::deep_copy_of_tetgenio(), oomph::DenseMatrix< int * >::DenseMatrix(), oomph::SpectralElement::describe_local_dofs(), oomph::FiniteElement::describe_nodal_local_dofs(), oomph::SolidFiniteElement::describe_solid_local_dofs(), oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >::discrete_times(), oomph::Mesh::distribute(), oomph::Problem::distribute(), oomph::Orthpoly::dlegendre(), oomph::FiniteElement::dnodal_position_dt(), oomph::FiniteElement::dnodal_position_gen_dt(), oomph::DGFaceElement::dnumerical_flux_du(), oomph::Z2ErrorEstimator::doc_flux(), oomph::Mesh::doc_shared_nodes(), oomph::Mesh::does_pointer_correspond_to_mesh_data(), oomph::DoubleVector::dot(), oomph::DoubleMultiVector::dot(), oomph::DoubleVectorHaloScheme::DoubleVectorHaloScheme(), oomph::ImmersedRigidBodyElement::dposition_dt(), oomph::GeomObject::dposition_dt(), oomph::PoroelasticityEquations< 2 >::dq_edge_dt(), oomph::AxisymmetricPoroelasticityEquations::dq_edge_dt(), oomph::PoroelasticityEquations< 2 >::dq_internal_dt(), oomph::AxisymmetricPoroelasticityEquations::dq_internal_dt(), oomph::ClampedHermiteShellBoundaryConditionElement::dshape_local(), oomph::PoroelasticityEquations< 2 >::du_dt(), oomph::AxisymmetricPoroelasticityEquations::du_dt(), oomph::AdvectionDiffusionEquations< DIM >::du_dt_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::du_dt_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::du_dt_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::du_dt_axi_nst(), oomph::AxisymmetricLinearElasticityEquationsBase::du_dt_axisymmetric_linear_elasticity(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::du_dt_cons_adv_diff(), oomph::du_dt_cons_axisym_adv_diff(), oomph::FluxTransportEquations< DIM >::du_dt_flux_transport(), oomph::LinearWaveEquations< DIM >::du_dt_lin_wave(), oomph::LinearisedAxisymmetricNavierStokesEquations::du_dt_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations::du_dt_linearised_nst(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::du_dt_nst(), oomph::NavierStokesEquations< DIM >::du_dt_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >::du_dt_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::du_dt_nst(), oomph::PolarNavierStokesEquations::du_dt_pnst(), oomph::SphericalAdvectionDiffusionEquations::du_dt_spherical_adv_diff(), oomph::SphericalNavierStokesEquations::du_dt_spherical_nst(), oomph::UnsteadyHeatEquations< DIM >::du_dt_ust_heat(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::du_dt_ust_heat(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::du_dt_ust_heat(), oomph::WomersleyEquations< DIM >::du_dt_womersley(), oomph::Problem::dump(), oomph::TriangleHelper::dump_triangulateio(), oomph::TRaviartThomasDarcyElement< ORDER >::edge_flux_interpolation_point(), oomph::TRaviartThomasDarcyElement< ORDER >::edge_flux_interpolation_point_global(), oomph::TPoroelasticityElement< ORDER >::edge_gauss_point(), oomph::TPoroelasticityElement< ORDER >::edge_gauss_point_global(), oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >::ElasticUpdateFluidInterfaceElement(), oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >::element_node_index_to_pressure_node_index(), oomph::SpineMesh::element_node_pt(), oomph::SolidMesh::element_node_pt(), oomph::TRaviartThomasDarcyElement< ORDER >::face_local_coordinate_of_flux_interpolation_point(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::face_local_coordinate_of_flux_interpolation_point(), oomph::MumpsSolver::factorise(), oomph::DenseLU::factorise(), oomph::SuperLUSolver::factorise_distributed(), oomph::SuperLUSolver::factorise_serial(), RefineableBinArray::fill_bin_array(), NonRefineableBinArray::fill_bin_by_diffusion(), oomph::ODEElement::fill_in_contribution_to_jacobian(), oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals_beam(), oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_residuals_shell(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::BiharmonicEquations< DIM >::fill_in_generic_residual_contribution_biharmonic(), oomph::BiharmonicFluxElement< DIM >::fill_in_generic_residual_contribution_biharmonic_flux(), oomph::FourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::PMLFourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz(), oomph::RefineableElement::fill_in_jacobian_from_nodal_by_fd(), oomph::FiniteElement::fill_in_jacobian_from_nodal_by_fd(), oomph::SolidFiniteElement::fill_in_jacobian_from_solid_position_by_fd(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd(), oomph::PseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_shape_derivatives(), oomph::PseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_shape_derivatives_by_fd(), oomph::RefineablePseudoSolidNodeUpdateElement< BASIC, SOLID >::fill_in_shape_derivatives_by_fd(), oomph::LAPACK_QZ::find_eigenvalues(), oomph::BinaryTreeForest::find_neighbours(), oomph::QuadTreeForest::find_neighbours(), oomph::OcTreeForest::find_neighbours(), oomph::AxisymmetricPoroelasticityEquations::fluid_body_force(), oomph::FoldHandler::FoldHandler(), oomph::PoroelasticityEquations< 2 >::force_fluid(), oomph::PoroelasticityEquations< 2 >::force_solid(), oomph::RefineableSolidElement::geom_data_pt(), oomph::ElementWithMovingNodes::geometric_data_local_eqn(), oomph::GeompackQuadScaffoldMesh::GeompackQuadScaffoldMesh(), oomph::Mesh::get_all_halo_data(), oomph::RefineableQElement< 3 >::get_bcs(), oomph::RefineableQElement< 3 >::get_boundaries(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::get_dbody_force_nst_dexternal_element_data(), oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::get_dbody_force_nst_dexternal_element_data(), oomph::Problem::get_derivative_wrt_global_parameter(), oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::get_dof_numbers_for_unknowns(), oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::get_dof_numbers_for_unknowns(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::get_dof_numbers_for_unknowns(), oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::get_dof_numbers_for_unknowns(), oomph::LinearElasticityEquationsBase< DIM >::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::get_dof_numbers_for_unknowns(), oomph::AxisymmetricTCrouzeixRaviartElement::get_dof_numbers_for_unknowns(), oomph::PVDEquationsBase< DIM >::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::get_dof_numbers_for_unknowns(), oomph::TCrouzeixRaviartElement< DIM >::get_dof_numbers_for_unknowns(), oomph::AxisymmetricLinearElasticityEquationsBase::get_dof_numbers_for_unknowns(), oomph::BiharmonicEquations< DIM >::get_dof_numbers_for_unknowns(), oomph::FSIHermiteBeamElement::get_dof_numbers_for_unknowns(), oomph::FSIDiagHermiteShellElement::get_dof_numbers_for_unknowns(), oomph::PMLHelmholtzEquations< DIM >::get_dof_numbers_for_unknowns(), oomph::PMLHelmholtzFluxElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::get_dof_numbers_for_unknowns(), oomph::ClampedHermiteShellBoundaryConditionElement::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::get_dof_numbers_for_unknowns(), oomph::AxisymmetricTTaylorHoodElement::get_dof_numbers_for_unknowns(), oomph::FSISolidTractionElement< ELEMENT, DIM >::get_dof_numbers_for_unknowns(), oomph::QSphericalCrouzeixRaviartElement::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::get_dof_numbers_for_unknowns(), oomph::TTaylorHoodElement< DIM >::get_dof_numbers_for_unknowns(), oomph::PVDEquationsWithPressure< DIM >::get_dof_numbers_for_unknowns(), oomph::QSphericalTaylorHoodElement::get_dof_numbers_for_unknowns(), oomph::AxisymmetricQCrouzeixRaviartElement::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::get_dof_numbers_for_unknowns(), oomph::AxisymmetricQTaylorHoodElement::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement::get_dof_numbers_for_unknowns(), oomph::QCrouzeixRaviartElement< DIM >::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::get_dof_numbers_for_unknowns(), oomph::QTaylorHoodSpaceTimeElement< 2 >::get_dof_numbers_for_unknowns(), oomph::QTaylorHoodElement< DIM >::get_dof_numbers_for_unknowns(), oomph::SpaceTimeNavierStokesEquations< DIM >::get_du_dt(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_du_dt(), oomph::FoldHandler::get_eigenfunction(), oomph::PitchForkHandler::get_eigenfunction(), oomph::HopfHandler::get_eigenfunction(), oomph::Z2ErrorEstimator::get_element_errors(), oomph::KirchhoffLoveShellEquations::get_energy(), oomph::KirchhoffLoveBeamEquations::get_energy(), oomph::Problem::get_first_and_last_element_for_assembly(), oomph::TriangleMesh< ELEMENT >::get_halo_elements_on_all_procs(), oomph::Problem::get_hessian_vector_products(), oomph::SpectralPeriodicOrbitElement< NNODE_1D >::get_interpolated_values(), oomph::DGFaceElement::get_interpolation_data(), oomph::DGElement::get_inverse_mass_matrix_times_residuals(), oomph::DGSpectralScalarAdvectionElement< 1, NNODE_1D >::get_inverse_mass_matrix_times_residuals(), oomph::FoldHandler::get_jacobian(), oomph::PitchForkHandler::get_jacobian(), oomph::HopfHandler::get_jacobian(), oomph::PolarCrouzeixRaviartElement::get_load_data(), oomph::PolarTaylorHoodElement::get_load_data(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::get_node_at_local_coordinate(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::get_node_at_local_coordinate(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::get_node_at_local_coordinate(), oomph::FiniteElement::get_node_at_local_coordinate(), oomph::DarcyFaceElement< ELEMENT >::get_pressure(), oomph::PoroelasticityFaceElement< ELEMENT >::get_pressure(), oomph::AxisymmetricPoroelasticityTractionElement< POROELASTICITY_BULK_ELEMENT >::get_pressure(), oomph::RefineableTriangleMesh< ELEMENT >::get_required_nodal_information_load_balance_helper(), oomph::RefineableSolidQElement< 3 >::get_solid_bcs(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::get_strain(), oomph::KirchhoffLoveShellEquations::get_strain_and_bend(), oomph::AxisymmetricSolidTractionElement< ELEMENT >::get_traction(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::get_traction(), oomph::SolidTractionElement< ELEMENT >::get_traction(), oomph::LinearElasticityTractionElement< ELEMENT >::get_traction(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >::get_traction(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >::get_traction(), oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >::get_traction(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::get_traction(), oomph::NavierStokesTractionElement< ELEMENT >::get_traction(), oomph::PoroelasticityFaceElement< ELEMENT >::get_traction(), oomph::AxisymmetricPoroelasticityTractionElement< POROELASTICITY_BULK_ELEMENT >::get_traction(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::get_traction(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::get_traction(), oomph::FSISolidTractionElement< ELEMENT, DIM >::get_traction(), oomph::SpectralPeriodicOrbitElement< NNODE_1D >::get_Z2_flux(), oomph::Hankel_functions_for_helmholtz_problem::Hankel_first(), oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >::hijack_external_value(), oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >::hijack_internal_value(), oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >::hijack_nodal_position_value(), oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >::hijack_nodal_spine_value(), oomph::Hijacked< SpineElement< FaceGeometry< ELEMENT > > >::hijack_nodal_value(), oomph::HopfHandler::HopfHandler(), oomph::RefineableElement::identify_field_data_for_interactions(), oomph::FiniteElement::identify_field_data_for_interactions(), oomph::ElementWithMovingNodes::identify_geometric_data(), oomph::SolidFiniteElement::identify_geometric_data(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::identify_load_data(), oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::identify_load_data(), oomph::AxisymmetricTCrouzeixRaviartElement::identify_load_data(), oomph::TCrouzeixRaviartElement< DIM >::identify_load_data(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::identify_load_data(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::identify_load_data(), oomph::AxisymmetricTTaylorHoodElement::identify_load_data(), oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::identify_load_data(), oomph::QSphericalCrouzeixRaviartElement::identify_load_data(), oomph::TTaylorHoodElement< DIM >::identify_load_data(), oomph::RefineableQTaylorHoodElement< DIM >::identify_load_data(), oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::identify_load_data(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::identify_load_data(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::identify_load_data(), oomph::QSphericalTaylorHoodElement::identify_load_data(), oomph::RefineableQCrouzeixRaviartElement< DIM >::identify_load_data(), oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::identify_load_data(), oomph::QCrouzeixRaviartElement< DIM >::identify_load_data(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::identify_load_data(), oomph::QTaylorHoodSpaceTimeElement< 2 >::identify_load_data(), oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >::identify_load_data(), oomph::QTaylorHoodElement< DIM >::identify_load_data(), oomph::BiharmonicFluidProblem< DIM >::impose_fluid_flow_on_edge(), oomph::BiharmonicFluidProblem< DIM >::impose_solid_boundary_on_edge(), oomph::BiharmonicFluidProblem< DIM >::impose_traction_free_edge(), oomph::CRDoubleMatrix::inf_norm(), oomph::RefineablePolarTaylorHoodElement::insert_load_data(), oomph::RefineablePolarCrouzeixRaviartElement::insert_load_data(), oomph::BiharmonicEquations< DIM >::interpolated_dudx(), oomph::DGFaceElement::interpolated_u(), oomph::DGEulerFaceReflectionElement< ELEMENT >::interpolated_u(), oomph::BiharmonicEquations< DIM >::interpolated_u_biharmonic(), oomph::FluxTransportEquations< DIM >::interpolated_u_flux_transport(), oomph::RefineableQElement< 2 >::interpolated_zeta_on_edge(), oomph::RefineableElement::interpolating_node_pt(), oomph::RefineableLinearisedQTaylorHoodElement::interpolating_node_pt(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::interpolating_node_pt(), oomph::RefineablePseudoSolidNodeUpdateElement< BASIC, SOLID >::interpolating_node_pt(), oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >::is_pressure_node(), oomph::QTaylorHoodElement< DIM >::is_pressure_node(), oomph::Orthpoly::jacobi(), oomph::ProjectableDarcyElement< DARCY_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::jacobian_and_shape_of_field(), oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >::kinematic_local_eqn(), oomph::ElasticPointFluidInterfaceBoundingElement< ELEMENT >::kinematic_local_eqn(), oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >::kinematic_local_eqn(), oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >::lagrange(), oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >::lagrange_index(), oomph::SolidFiniteElement::lagrangian_position(), oomph::SolidFiniteElement::lagrangian_position_gen(), oomph::Orthpoly::legendre(), oomph::Orthpoly::legendre_vector(), oomph::MinModLimiter::limit(), oomph::BlackBoxFDNewtonSolver::line_search(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::LinearisedAxisymPoroelasticBJS_FSIElement(), oomph::Problem::load_balance(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::local_coordinate_of_node(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::local_coordinate_of_node(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::local_coordinate_of_node(), oomph::QSpectralElement< 1, NNODE_1D >::local_coordinate_of_node(), oomph::QSpectralElement< 2, NNODE_1D >::local_coordinate_of_node(), oomph::QSpectralElement< 3, NNODE_1D >::local_coordinate_of_node(), oomph::GeneralisedElement::local_eqn_number(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::local_fraction_of_node(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::local_fraction_of_node(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::local_fraction_of_node(), oomph::QSpectralElement< 1, NNODE_1D >::local_fraction_of_node(), oomph::QSpectralElement< 2, NNODE_1D >::local_fraction_of_node(), oomph::QSpectralElement< 3, NNODE_1D >::local_fraction_of_node(), RefineableBin::locate_zeta(), oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >::make_bounding_element(), oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >::make_bounding_element(), oomph::BoundaryNodeBase::make_nodes_periodic(), oomph::ComplexMatrixBase::max_residual(), oomph::HelmholtzMGPreconditioner< DIM >::maximum_edge_width(), oomph::Mesh::merge_meshes(), oomph::CRDoubleMatrix::multiply(), oomph::CRDoubleMatrix::multiply_transpose(), oomph::FaceElement::nbulk_value(), oomph::BlockPreconditioner< CRDoubleMatrix >::ndof_types(), oomph::Mesh::nexternal_halo_element(), oomph::Mesh::nexternal_halo_node(), oomph::Mesh::nexternal_haloed_element(), oomph::Mesh::nexternal_haloed_node(), oomph::RefineableSolidElement::ngeom_data(), oomph::Mesh::nhalo_node(), oomph::Mesh::nhaloed_node(), oomph::Mesh::nnon_halo_element(), oomph::FiniteElement::nodal_local_eqn(), oomph::OneDLegendreShapeParam::nodal_position(), oomph::OneDimensionalLegendreShape< NNODE_1D >::nodal_position(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_position_gen(), oomph::FiniteElement::nodal_value(), oomph::OcTree::node_number_to_vertex(), oomph::Mesh::node_pt(), oomph::AlgebraicMesh::node_pt(), oomph::SpineMesh::node_pt(), oomph::FiniteElement::node_pt(), oomph::SolidMesh::node_pt(), oomph::MacroElementNodeUpdateMesh::node_update(), oomph::Mesh::node_update(), oomph::AlgebraicMesh::node_update(), oomph::FiniteElement::node_update(), oomph::RefineableQSpectralElement< 1 >::nodes_built(), oomph::RefineableQSpectralElement< 2 >::nodes_built(), oomph::RefineableQSpectralElement< 3 >::nodes_built(), oomph::PRefineableElement::nodes_built(), oomph::DoubleVector::norm(), oomph::DoubleMultiVector::norm(), oomph::VorticityRecoveryHelpers::RecoveryHelper::npartial_derivative(), oomph::VorticitySmootherElement< ELEMENT >::npartial_derivative(), oomph::TetMeshBase::nregion_element(), oomph::Mesh::nroot_halo_element(), oomph::Mesh::nroot_haloed_element(), oomph::Mesh::nshared_node(), oomph::Mesh::null_external_halo_node(), oomph::DGScalarAdvectionFaceElement< ELEMENT >::numerical_flux(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::oc_hang_helper(), oomph::NonLinearElasticitySmoothMesh< ELEMENT >::operator()(), oomph::DenseMatrix< int * >::operator=(), oomph::RankThreeTensor< T >::operator=(), oomph::RankFourTensor< T >::operator=(), oomph::RankFiveTensor< T >::operator=(), oomph::LineVisualiser::output(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::output(), oomph::SurfactantTransportInterfaceElement::output(), oomph::TetMeshFacet::output(), oomph::TetMeshFacetedSurface::output(), oomph::DiskLikeGeomObjectWithBoundaries::output_boundaries_and_triads(), oomph::FiniteElement::output_paraview(), oomph::NavierStokesEquations< DIM >::output_pressure_advection_diffusion_robin_elements(), oomph::SpaceTimeNavierStokesEquations< DIM >::output_pressure_advection_diffusion_robin_elements(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::output_pressure_advection_diffusion_robin_elements(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::TCrouzeixRaviartElement< DIM >::p_local_eqn(), oomph::AxisymmetricTCrouzeixRaviartElement::p_local_eqn(), oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::p_local_eqn(), oomph::TRaviartThomasDarcyElement< ORDER >::p_local_eqn(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::p_local_eqn(), oomph::TPoroelasticityElement< ORDER >::p_local_eqn(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::p_local_eqn(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::p_local_eqn(), oomph::AxisymmetricTTaylorHoodElement::p_local_eqn(), oomph::LinearisedQCrouzeixRaviartElement::p_local_eqn(), oomph::PolarCrouzeixRaviartElement::p_local_eqn(), oomph::QSphericalCrouzeixRaviartElement::p_local_eqn(), oomph::TTaylorHoodElement< DIM >::p_local_eqn(), oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::p_local_eqn(), oomph::LinearisedAxisymmetricQTaylorHoodElement::p_local_eqn(), oomph::LinearisedQTaylorHoodElement::p_local_eqn(), oomph::PolarTaylorHoodElement::p_local_eqn(), oomph::QSphericalTaylorHoodElement::p_local_eqn(), oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::p_local_eqn(), oomph::AxisymmetricQCrouzeixRaviartElement::p_local_eqn(), oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::p_local_eqn(), oomph::AxisymmetricQTaylorHoodElement::p_local_eqn(), oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement::p_local_eqn(), oomph::QCrouzeixRaviartElement< DIM >::p_local_eqn(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::p_local_eqn(), oomph::QTaylorHoodSpaceTimeElement< 2 >::p_local_eqn(), oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >::p_local_eqn(), oomph::QTaylorHoodElement< DIM >::p_local_eqn(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::p_refine(), oomph::Tree::p_refine_if_required(), oomph::TRaviartThomasDarcyElement< ORDER >::p_value(), oomph::TPoroelasticityElement< ORDER >::p_value(), oomph::METIS::partition_distributed_mesh(), oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >::PeriodicOrbitAssemblyHandler(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::pin_all(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::pin_all_nodal_pressure_dofs(), oomph::AxisymmetricTTaylorHoodElement::pin_all_nodal_pressure_dofs(), oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::pin_all_nodal_pressure_dofs(), oomph::TTaylorHoodElement< DIM >::pin_all_nodal_pressure_dofs(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::pin_dofs_of_coordinate(), oomph::RefineableQSphericalTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineablePolarTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableAxisymmetricQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableLinearisedQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableQTaylorHoodElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs(), oomph::TRaviartThomasDarcyElement< ORDER >::pin_p_value(), oomph::TPoroelasticityElement< ORDER >::pin_p_value(), oomph::TPoroelasticityElement< ORDER >::pin_q_internal_value(), oomph::LinearisedQCrouzeixRaviartElement::pin_real_or_imag(), oomph::PitchForkHandler::PitchForkHandler(), oomph::Legendre_functions_helper::plgndr1(), oomph::PMLCornerQuadMesh< ELEMENT >::PMLCornerQuadMesh(), oomph::PMLQuadMesh< ELEMENT >::PMLQuadMesh(), oomph::FiniteElement::point_output(), oomph::SolidFiniteElement::position_local_eqn(), oomph::StorableShapeElementBase::pre_compute_d2shape_local_at_knots(), oomph::StorableShapeElementBase::pre_compute_dshape_local_at_knots(), oomph::StorableShapeElementBase::pre_compute_shape_at_knots(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project(), oomph::Mesh::prune_dead_nodes(), oomph::TPoroelasticityElement< ORDER >::q_edge(), oomph::TRaviartThomasDarcyElement< ORDER >::q_edge(), oomph::TPoroelasticityElement< ORDER >::q_edge_index(), oomph::TRaviartThomasDarcyElement< ORDER >::q_edge_index(), oomph::TPoroelasticityElement< ORDER >::q_edge_local_eqn(), oomph::TRaviartThomasDarcyElement< ORDER >::q_edge_local_eqn(), oomph::TPoroelasticityElement< ORDER >::q_edge_node_number(), oomph::TRaviartThomasDarcyElement< ORDER >::q_edge_node_number(), oomph::TPoroelasticityElement< ORDER >::q_internal(), oomph::TPoroelasticityElement< ORDER >::q_internal_local_eqn(), oomph::TRaviartThomasDarcyElement< ORDER >::q_internal_local_eqn(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::quad_hang_helper(), oomph::RankFiveTensor< T >::RankFiveTensor(), oomph::RankFourTensor< T >::RankFourTensor(), oomph::RankThreeTensor< T >::RankThreeTensor(), oomph::FiniteElement::raw_dnodal_position_dt(), oomph::FiniteElement::raw_dnodal_position_gen_dt(), oomph::SolidFiniteElement::raw_lagrangian_position(), oomph::SolidFiniteElement::raw_lagrangian_position_gen(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_position_gen(), oomph::FiniteElement::raw_nodal_value(), oomph::Mesh::read(), oomph::TriangleHelper::read_triangulateio(), oomph::RefineableQSpectralElement< 1 >::rebuild_from_sons(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::rebuild_from_sons(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::rebuild_from_sons(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::rebuild_from_sons(), oomph::RectangleWithHoleAndAnnularRegionMesh< ELEMENT >::RectangleWithHoleAndAnnularRegionMesh(), oomph::RectangleWithHoleMesh< ELEMENT >::RectangleWithHoleMesh(), oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh(), oomph::TetMeshBase::region_element_pt(), oomph::TriangleMesh< ELEMENT >::remesh_from_internal_triangulateio(), oomph::Mesh::remove_boundary_nodes(), oomph::Problem::remove_duplicate_data(), oomph::TPoroelasticityElement< ORDER >::required_nvalue(), oomph::TRaviartThomasDarcyElement< ORDER >::required_nvalue(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::required_nvalue(), oomph::PseudoSolidNodeUpdateElement< BASIC, SOLID >::required_nvalue(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::required_nvalue(), oomph::QLinearWaveElement< DIM, NNODE_1D >::required_nvalue(), oomph::QYoungLaplaceElement< NNODE_1D >::required_nvalue(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::required_nvalue(), oomph::RefineablePseudoSolidNodeUpdateElement< BASIC, SOLID >::required_nvalue(), oomph::LinearisedQCrouzeixRaviartElement::required_nvalue(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::required_nvalue(), oomph::AxisymmetricTTaylorHoodElement::required_nvalue(), oomph::ProjectableDarcyElement< DARCY_ELEMENT >::required_nvalue(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::required_nvalue(), oomph::PolarCrouzeixRaviartElement::required_nvalue(), oomph::TTaylorHoodElement< DIM >::required_nvalue(), oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::required_nvalue(), oomph::LinearisedAxisymmetricQTaylorHoodElement::required_nvalue(), oomph::LinearisedQTaylorHoodElement::required_nvalue(), oomph::PolarTaylorHoodElement::required_nvalue(), oomph::QSphericalTaylorHoodElement::required_nvalue(), oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >::required_nvalue(), oomph::AxisymmetricQCrouzeixRaviartElement::required_nvalue(), oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::required_nvalue(), oomph::QPVDElementWithContinuousPressure< DIM >::required_nvalue(), oomph::AxisymmetricQTaylorHoodElement::required_nvalue(), oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement::required_nvalue(), oomph::QCrouzeixRaviartElement< DIM >::required_nvalue(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::required_nvalue(), oomph::TPVDElementWithContinuousPressure< DIM >::required_nvalue(), oomph::QTaylorHoodSpaceTimeElement< 2 >::required_nvalue(), oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >::required_nvalue(), oomph::QTaylorHoodElement< DIM >::required_nvalue(), oomph::CumulativeTimings::reset(), oomph::Timer::reset(), oomph::RefineableTriangleMesh< ELEMENT >::reset_halo_haloed_scheme(), oomph::RefineableTriangleMesh< ELEMENT >::reset_halo_haloed_scheme_helper(), oomph::SolidICProblem::reset_original_state(), oomph::RefineableTriangleMesh< ELEMENT >::reset_shared_boundary_elements_and_nodes(), oomph::VectorMatrix< VALUE_TYPE >::resize(), oomph::DenseMatrix< int * >::resize(), oomph::RankThreeTensor< T >::resize(), oomph::RankFourTensor< T >::resize(), oomph::RankFiveTensor< T >::resize(), oomph::Mesh::resize_halo_nodes(), oomph::AugmentedBlockFoldLinearSolver::resolve(), oomph::BlockPitchForkLinearSolver::resolve(), oomph::AugmentedBlockPitchForkLinearSolver::resolve(), oomph::Problem::restore_dof_values(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::restore_positions(), oomph::BlockPreconditioner< CRDoubleMatrix >::return_block_vector(), oomph::YoungLaplaceEquations::scalar_product(), oomph::YoungLaplaceEquations::scalar_times_vector(), oomph::SecondInvariantHelper::second_invariant(), oomph::AlgebraicMesh::self_test(), oomph::Problem::send_refinement_info_helper(), oomph::Mesh::set_consistent_pinned_values_for_continuation(), oomph::BiharmonicProblem< DIM >::set_dirichlet_boundary_condition(), oomph::Problem::set_first_and_last_element_for_assembly(), oomph::Node::set_hanging_pt(), oomph::SolidMesh::set_lagrangian_nodal_coordinates(), oomph::FiniteElement::set_n_node(), oomph::SolidICProblem::set_newmark_initial_condition_consistently(), oomph::SolidICProblem::set_newmark_initial_condition_directly(), oomph::BlockPreconditioner< CRDoubleMatrix >::set_nmesh(), oomph::Mesh::set_nodal_time_stepper(), oomph::TRaviartThomasDarcyElement< ORDER >::set_p_value(), oomph::Problem::set_pinned_values_to_zero(), oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >::set_previous_dofs_to_current_dofs(), oomph::TRaviartThomasDarcyElement< ORDER >::set_q_edge(), oomph::VolumeConstraintBoundingElement::set_volume_constraint_element(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::setup_algebraic_node_update(), oomph::XdaTetMesh< ELEMENT >::setup_boundary_coordinates(), oomph::TetMeshBase::setup_boundary_coordinates(), oomph::LineMeshBase::setup_boundary_element_info(), oomph::BrickMeshBase::setup_boundary_element_info(), oomph::Problem::setup_element_count_per_dof(), oomph::FluidInterfaceAdditionalValues< SurfactantTransportInterfaceElement >::setup_equation_indices(), oomph::RefineableQElement< 1 >::setup_father_bounds(), oomph::RefineableQElement< 3 >::setup_father_bounds(), oomph::RefineableQElement< 2 >::setup_father_bounds(), oomph::LineVisualiser::setup_from_file(), oomph::DGFaceElement::setup_neighbour_info(), oomph::RefineableBrickMesh< ELEMENT >::setup_octree_forest(), oomph::Z2ErrorEstimator::setup_patches(), oomph::VorticitySmoother< ELEMENT >::setup_patches(), oomph::SolidICProblem::setup_problem(), oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest(), oomph::ClampedHermiteShellBoundaryConditionElement::shape(), oomph::TriangleMesh< ELEMENT >::shared_boundary_node_pt(), oomph::Mesh::shift_time_values(), oomph::TRaviartThomasDarcyElement< ORDER >::sign_edge(), oomph::TPoroelasticityElement< ORDER >::sign_edge(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::sign_edge(), oomph::RefineableTetgenMesh< ELEMENT >::snap_nodes_onto_boundary(), oomph::RefineableTriangleMesh< ELEMENT >::snap_nodes_onto_boundary(), oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), oomph::UnstructuredTwoDMeshGeometryBase::snap_nodes_onto_geometric_objects(), oomph::AxisymmetricPoroelasticityEquations::solid_body_force(), oomph::SolidMesh::SolidMesh(), oomph::AugmentedBlockFoldLinearSolver::solve(), oomph::BlockPitchForkLinearSolver::solve(), oomph::AugmentedBlockPitchForkLinearSolver::solve(), oomph::BlockHopfLinearSolver::solve(), oomph::HopfHandler::solve_complex_system(), oomph::ARPACK::solve_eigenproblem(), oomph::LAPACK_QZ::solve_eigenproblem(), oomph::ANASAZI::solve_eigenproblem(), oomph::BlockHopfLinearSolver::solve_for_two_rhs(), oomph::FoldHandler::solve_full_system(), oomph::PitchForkHandler::solve_full_system(), oomph::HopfHandler::solve_full_system(), oomph::DarcyEquations< 2 >::source(), oomph::CRDoubleMatrix::sparse_indexed_output_with_offset(), oomph::SpineElement< FaceGeometry< ELEMENT > >::spine_local_eqn(), oomph::Tree::split_if_required(), oomph::Problem::store_current_dof_values(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::store_positions(), superlu(), superlu_complex(), superlu_dist_distributed_matrix(), superlu_dist_global_matrix(), oomph::Problem::synchronise_dofs(), oomph::TreeBasedRefineableMeshBase::synchronise_hanging_nodes(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), oomph::ThinLayerBrickOnTetMesh< ELEMENT >::ThinLayerBrickOnTetMesh(), oomph::LowStorageRungeKutta< ORDER >::timestep(), oomph::RefineableTriangleMesh< ELEMENT >::try_to_add_node_pt_load_balance(), oomph::YoungLaplaceEquations::two_norm(), oomph::YoungLaplaceEquations::u(), oomph::TPoroelasticityElement< ORDER >::u_index(), oomph::PolarStressIntegralElement< ELEMENT >::u_local_eqn(), oomph::PolarNavierStokesTractionElement< ELEMENT >::u_local_eqn(), oomph::NavierStokesTractionElement< ELEMENT >::u_local_eqn(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::u_local_eqn(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::u_local_eqn(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::u_local_eqn(), oomph::YoungLaplaceEquations::u_local_eqn(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::u_local_eqn(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::u_nst(), oomph::NavierStokesEquations< DIM >::u_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >::u_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::u_nst(), oomph::PolarCrouzeixRaviartElement::u_pnst(), oomph::PolarTaylorHoodElement::u_pnst(), oomph::SphericalNavierStokesEquations::u_spherical_nst(), oomph::RefineableElement::unbuild(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::unpin_all(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::unpin_dofs_of_coordinate(), oomph::RefineableQSphericalTaylorHoodElement::unpin_elemental_pressure_dofs(), oomph::RefineablePolarTaylorHoodElement::unpin_elemental_pressure_dofs(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::unpin_elemental_pressure_dofs(), oomph::RefineableAxisymmetricQTaylorHoodElement::unpin_elemental_pressure_dofs(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::unpin_elemental_pressure_dofs(), oomph::RefineableLinearisedQTaylorHoodElement::unpin_elemental_pressure_dofs(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::unpin_elemental_pressure_dofs(), oomph::RefineableQTaylorHoodElement< DIM >::unpin_elemental_pressure_dofs(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::unpin_elemental_pressure_dofs(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::unpin_elemental_pressure_dofs(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::unpin_elemental_solid_pressure_dofs(), oomph::QPVDElementWithContinuousPressure< DIM >::unpin_elemental_solid_pressure_dofs(), oomph::TPVDElementWithContinuousPressure< DIM >::unpin_elemental_solid_pressure_dofs(), oomph::LinearisedQCrouzeixRaviartElement::unpin_real_or_imag(), oomph::RefineableTriangleMesh< ELEMENT >::unrefine_boundary(), oomph::RefineableTetgenMesh< ELEMENT >::update_faceted_surface_using_face_mesh(), oomph::YoungLaplaceEquations::vector_sum(), oomph::OcTree::vertex_node_to_vector(), oomph::TwoDAnnularMesh< ELEMENT >::wrap_into_annular_shape(), oomph::GmshTetScaffoldMesh::write_geo_file(), oomph::TriangleHelper::write_triangulateio_to_polyfile(), oomph::NavierStokesTractionElement< ELEMENT >::zeta_nodal(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::zeta_nodal(), oomph::PoissonFluxElement< ELEMENT >::zeta_nodal(), oomph::PMLHelmholtzPowerElement< ELEMENT >::zeta_nodal(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::zeta_nodal(), oomph::FaceElementAsGeomObject< ELEMENT >::zeta_nodal(), oomph::ImposeImpenetrabilityElement< ELEMENT >::zeta_nodal(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::zeta_nodal(), oomph::UnsteadyHeatFluxElement< ELEMENT >::zeta_nodal(), oomph::ImposeParallelOutflowElement< ELEMENT >::zeta_nodal(), oomph::LinearWaveFluxElement< ELEMENT >::zeta_nodal(), oomph::AdvectionDiffusionFluxElement< ELEMENT >::zeta_nodal(), oomph::HelmholtzFluxElement< ELEMENT >::zeta_nodal(), oomph::BiharmonicFluxElement< DIM >::zeta_nodal(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::zeta_nodal(), oomph::DarcyFaceElement< ELEMENT >::zeta_nodal(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::zeta_nodal(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::zeta_nodal(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::zeta_nodal(), oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >::zeta_nodal(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >::zeta_nodal(), oomph::LinearElasticityTractionElement< ELEMENT >::zeta_nodal(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >::zeta_nodal(), oomph::HelmholtzBCElementBase< ELEMENT >::zeta_nodal(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::zeta_nodal(), oomph::PoroelasticityFaceElement< ELEMENT >::zeta_nodal(), oomph::AxisymmetricPoroelasticityTractionElement< POROELASTICITY_BULK_ELEMENT >::zeta_nodal(), oomph::ElasticLineVolumeConstraintBoundingElement< ELEMENT >::zeta_nodal(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::zeta_nodal(), oomph::SpineLineVolumeConstraintBoundingElement< ELEMENT >::zeta_nodal(), oomph::DGEulerFaceElement< ELEMENT >::zeta_nodal(), oomph::ProjectableElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::zeta_nodal(), oomph::PMLHelmholtzFluxElement< ELEMENT >::zeta_nodal(), oomph::ElasticAxisymmetricVolumeConstraintBoundingElement< ELEMENT >::zeta_nodal(), oomph::SpineAxisymmetricVolumeConstraintBoundingElement< ELEMENT >::zeta_nodal(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::zeta_nodal(), oomph::DGEulerFaceReflectionElement< ELEMENT >::zeta_nodal(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::zeta_nodal(), oomph::ElasticSurfaceVolumeConstraintBoundingElement< ELEMENT >::zeta_nodal(), oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >::zeta_nodal(), oomph::SpineSurfaceVolumeConstraintBoundingElement< ELEMENT >::zeta_nodal(), oomph::ElasticPointFluidInterfaceBoundingElement< ELEMENT >::zeta_nodal(), oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >::zeta_nodal(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::zeta_nodal(), oomph::FiniteElement::zeta_nodal(), oomph::SolidFiniteElement::zeta_nodal(), oomph::SolidFaceElement::zeta_nodal(), oomph::DummyFaceElement< ELEMENT >::zeta_nodal(), oomph::FreeStandingFaceElement< ELEMENT >::zeta_nodal(), CGALSamplePointContainer::~CGALSamplePointContainer(), RefineableBin::~RefineableBin(), RefineableBinArray::~RefineableBinArray(), and oomph::WarpedCircularDisk::~WarpedCircularDisk().
Node
endcode returns the global equation number c i_global corresponding to the equation number c i_local The equation numbers of the internal and external c Data are stored in the private arrays c Internal_local_eqn and c accessed by the functions c GeneralisedElement::internal_local_eqn (...) and \c GeneralisedElement see section ref Hanging_Nodes for further details When c Nodes are created in it is important that c Nodes of the correct type with the appropriate amount of storage are created For Poisson elements require c Nodes that provide storage for a single value at each c Node
Definition at line 53 of file the_data_structure.txt.
Referenced by oomph::QuadFromTriangleMesh< ELEMENT >::build_from_scaffold(), oomph::Missing_masters_functions::construct_new_external_halo_master_node_helper(), oomph::Multi_domain_functions::construct_new_external_halo_master_node_helper(), oomph::FiniteElement::construct_node(), and oomph::SimpleCubicScaffoldTetMesh::SimpleCubicScaffoldTetMesh().
node
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt (t,i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial (Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced we must evaluate mesh which requires the storage of the nodal position at a number of previous timesteps Storage for the positional history values is allocated by the c Node constructor A different c TimeStepper may be used to represent time derivatives of nodal so c Nodes store a separate pointer to a positional c TimeStepper [Note: By default, we allocate the same amount of storage for the history of the nodal positions as we do for the history of the nodal values; e.g. if a \c BDF<2> scheme is used to evaluate the time-derivatives of the fluid velocities, we assume that the same timestepping scheme is used (and the same amount of storage required) to determine the mesh velocities from the nodal positions.] For finite elements in which the global position of a point in an element is determined by interpolation from the position of the element s c we need only store the spatial position of the c Nodes In many other the interpolation of the geometry requires additional e g the derivative of the mapping between and global coordinates we allow the storage of additional positional variables at each c so in every c Node has a number of e generalised coordinates for each spatial coordinate direction For for nodes in Hermite the nodal coordinate of type stores the global position at the node
Definition at line 190 of file the_data_structure.txt.
Referenced by oomph::RefineableQElement< 3 >::get_boundaries(), and oomph::RefineableQElement< 3 >::interpolated_zeta_on_face().
nodes
see the section ref Hanging_Nodes for a more detailed discussion of hanging nodes
Definition at line 200 of file the_data_structure.txt.
Referenced by oomph::TFace::TFace().
often
often abbreviated as dof b History b history values are often
Definition at line 44 of file the_data_structure.txt.
particular
in particular
Definition at line 200 of file the_data_structure.txt.
pointers
endcode The default implementation of c the simplest possible implementation of a new element requires only the specification of c we need to know which c Data affects the accessed via pointers
Definition at line 362 of file the_data_structure.txt.
position
the nodal coordinates represent the c Nodes fixed positions in this domain When the elastic body material which can be unknowns in the problem To avoid confusion between the the access function for the nodal position
Definition at line 148 of file the_data_structure.txt.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::BellElementShape< 2 >::Bshape(), oomph::BellElementShape< 2 >::d2Bshape_local(), oomph::GeometricTElement< 2 >::d2Lshape_local(), oomph::BellElementShape< 2 >::dBshape_local(), oomph::Mesh::delete_all_external_storage(), oomph::GeometricTElement< 2 >::dLshape_local(), oomph::Problem::get_data_to_be_sent_during_load_balancing(), oomph::GeometricTElement< 2 >::Lshape(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), and oomph::ChannelSpineMesh< ELEMENT >::spine_node_update().
press
double press = Node_pt[n]->value(3)
Definition at line 585 of file the_data_structure.txt.
Referenced by oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::further_build(), oomph::RefineableLinearisedQCrouzeixRaviartElement::further_build(), oomph::RefineableQPVDElementWithPressure< DIM >::further_build(), oomph::RefineableQSphericalCrouzeixRaviartElement::further_build(), oomph::RefineablePolarCrouzeixRaviartElement::further_build(), oomph::RefineableAxisymmetricQCrouzeixRaviartElement::further_build(), oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::further_build(), oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::further_build(), oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::further_build(), oomph::PRefineableQCrouzeixRaviartElement< DIM >::further_build(), oomph::RefineableQCrouzeixRaviartElement< DIM >::further_build(), oomph::PolarNavierStokesEquations::get_traction(), oomph::SphericalNavierStokesEquations::get_traction(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::get_traction(), oomph::NavierStokesEquations< DIM >::get_traction(), oomph::SpaceTimeNavierStokesEquations< DIM >::get_traction(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_traction(), oomph::PolarNavierStokesEquations::pressure_integral(), oomph::SphericalNavierStokesEquations::pressure_integral(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::pressure_integral(), oomph::AxisymmetricNavierStokesEquations::pressure_integral(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::pressure_integral(), oomph::NavierStokesEquations< DIM >::pressure_integral(), oomph::SpaceTimeNavierStokesEquations< DIM >::pressure_integral(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::pressure_integral(), oomph::AxisymmetricNavierStokesEquations::traction(), and oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::traction().
problem
often abbreviated as dof b History b history values are but b not b the values at previous timesteps b Pinned c c c Mesh and c Problem subsection data Data The most elementary data structure in c oomph lib is c these values fall into two and those that must be determined as part of the solution c Data stores a value a double precision number the values of the unknowns are determined by the solution of a system of algebraic equations The solution of this system usually requires c Data also stores a (long) integer that represents the number of the unknown in the global numbering scheme. \b Convention for in a fluids problem
Definition at line 92 of file the_data_structure.txt.
Referenced by oomph::SolidICProblem::set_newmark_initial_condition_consistently().
quantities
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt (t,i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial (Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced we must evaluate mesh which requires the storage of the nodal position at a number of previous timesteps Storage for the positional history values is allocated by the c Node constructor A different c TimeStepper may be used to represent time derivatives of nodal so c Nodes store a separate pointer to a positional c TimeStepper [Note: By default, we allocate the same amount of storage for the history of the nodal positions as we do for the history of the nodal values; e.g. if a \c BDF<2> scheme is used to evaluate the time-derivatives of the fluid velocities, we assume that the same timestepping scheme is used (and the same amount of storage required) to determine the mesh velocities from the nodal positions.] For finite elements in which the global position of a point in an element is determined by interpolation from the position of the element s c we need only store the spatial position of the c Nodes In many other the interpolation of the geometry requires additional quantities
Definition at line 183 of file the_data_structure.txt.
related
endcode in our standard equations the function c virtual the function code FiniteElement::required_nvalue (...) \endcode should be implemented to specify the number of values that are stored at each of the element's local \c Nodes. The default number of values stored at a \c Node is zero. \subsubsection advanced_features_of_elements Advanced' features for the Maths' level this can be advantageous when the element types are very closely related
Definition at line 640 of file the_data_structure.txt.
representing
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt (t,i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial (Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced we must evaluate mesh which requires the storage of the nodal position at a number of previous timesteps Storage for the positional history values is allocated by the c Node constructor A different c TimeStepper may be used to represent time derivatives of nodal so c Nodes store a separate pointer to a positional c TimeStepper [Note: By default, we allocate the same amount of storage for the history of the nodal positions as we do for the history of the nodal values; e.g. if a \c BDF<2> scheme is used to evaluate the time-derivatives of the fluid velocities, we assume that the same timestepping scheme is used (and the same amount of storage required) to determine the mesh velocities from the nodal positions.] For finite elements in which the global position of a point in an element is determined by interpolation from the position of the element s c we need only store the spatial position of the c Nodes In many other the interpolation of the geometry requires additional representing
Definition at line 183 of file the_data_structure.txt.
say
say
Definition at line 562 of file the_data_structure.txt.
setting
the nodal coordinate of type stores the derivative of the global position w r t to the element s coordinate The member function code nodes can become hanging the default setting
Definition at line 199 of file the_data_structure.txt.
so
the nodal coordinates represent the c Nodes fixed positions in this domain When the elastic body material which can be unknowns in the problem To avoid confusion between the the access function for the nodal code we provide a wrapper code in the case of generalised coordinates code Node::x_gen (...) \endcode always refers to the generalised Eulerian position and \code SolidNode endcode where the c MultiPhysicsElement inherits from c SinglePhysicsOneElement and c SinglePhysicsTwoElement A problem with this implementation arises when we consider where to initialise the residuals vector If the second single physics c then the contribution of the first single physics element will be negated When writing a single physics we cannot know whether it will ever be used as part of a multi physics element if so
Definition at line 304 of file the_data_structure.txt.
SolidNodes
see ref meshes for further details b SolidNodes
Definition at line 222 of file the_data_structure.txt.
that
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt (t,i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial (Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced we must evaluate mesh which requires the storage of the nodal position at a number of previous timesteps Storage for the positional history values is allocated by the c Node constructor A different c TimeStepper may be used to represent time derivatives of nodal so c Nodes store a separate pointer to a positional c TimeStepper [Note: By default, we allocate the same amount of storage for the history of the nodal positions as we do for the history of the nodal values; e.g. if a \c BDF<2> scheme is used to evaluate the time-derivatives of the fluid velocities, we assume that the same timestepping scheme is used (and the same amount of storage required) to determine the mesh velocities from the nodal positions.] For finite elements in which the global position of a point in an element is determined by interpolation from the position of the element s c we need only store the spatial position of the c Nodes In many other the interpolation of the geometry requires additional e g the derivative of the mapping between and global coordinates we allow the storage of additional positional variables at each c so that
Definition at line 186 of file the_data_structure.txt.
Referenced by oomph::SolutionFunctor::operator=(), and oomph::SolutionFunctor::SolutionFunctor().
Therefore
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt (t,i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial (Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced we must evaluate mesh which requires the storage of the nodal position at a number of previous timesteps Storage for the positional history values is allocated by the c Node constructor A different c TimeStepper may be used to represent time derivatives of nodal so c Nodes store a separate pointer to a positional c TimeStepper [Note: By default, we allocate the same amount of storage for the history of the nodal positions as we do for the history of the nodal values; e.g. if a \c BDF<2> scheme is used to evaluate the time-derivatives of the fluid velocities, we assume that the same timestepping scheme is used (and the same amount of storage required) to determine the mesh velocities from the nodal positions.] For finite elements in which the global position of a point in an element is determined by interpolation from the position of the element s c we need only store the spatial position of the c Nodes In many other the interpolation of the geometry requires additional e g the derivative of the mapping between and global coordinates Therefore
Definition at line 95 of file the_data_structure.txt.
Thus
endcode Thus
Definition at line 636 of file the_data_structure.txt.
two
the nodal coordinates represent the c Nodes fixed positions in this domain When the elastic body material which can be unknowns in the problem To avoid confusion between the two
Definition at line 232 of file the_data_structure.txt.
Typically
often abbreviated as dof b History b history values are but b not b the values at previous timesteps b Pinned c c c Mesh and c Problem subsection data Data The most elementary data structure in c oomph lib is c these values fall into two and those that must be determined as part of the solution c Data stores a value a double precision number Typically
Definition at line 69 of file the_data_structure.txt.
value
often abbreviated as dof b History b value
Definition at line 44 of file the_data_structure.txt.
Referenced by oomph::HelmholtzMGPreconditioner< DIM >::block_preconditioner_self_test(), oomph::CRMatrix< std::complex< double > >::build(), oomph::CCMatrix< std::complex< double > >::build(), oomph::CRMatrix< std::complex< double > >::build_without_copy(), oomph::CCMatrix< std::complex< double > >::build_without_copy(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_matrix(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_matrix_for_aztecoo(), oomph::SuperLUSolver::factorise_serial(), oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::further_build(), oomph::RefineableLinearisedQCrouzeixRaviartElement::further_build(), oomph::RefineableQSphericalCrouzeixRaviartElement::further_build(), oomph::CRDoubleMatrixHelpers::gershgorin_eigenvalue_estimate(), oomph::Problem::get_eigenproblem_matrices(), oomph::SpectralPeriodicOrbitElement< NNODE_1D >::get_interpolated_values(), oomph::Problem::get_jacobian(), oomph::C1CurvedElementBase< NNODE_1D >::get_nodal_value_curve1(), oomph::Problem::get_residuals(), oomph::CRDoubleMatrixHelpers::inf_norm(), oomph::HelmholtzMGPreconditioner< DIM >::interpolation_matrix_set(), oomph::MGSolver< DIM >::interpolation_matrix_set(), oomph::MinModLimiter::limit(), oomph::TrilinosEpetraHelpers::multiply(), oomph::C1CurvedElementBase< NNODE_1D >::my_interpolated_u_normal(), oomph::VorticityRecoveryHelpers::RecoveryHelper::npartial_derivative(), oomph::Problem::parallel_sparse_assemble(), oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >::PeriodicOrbitAssemblyHandler(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::pin_q_edge_value(), oomph::TRaviartThomasDarcyElement< ORDER >::set_p_value(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::set_p_value(), oomph::TRaviartThomasDarcyElement< ORDER >::set_q_edge(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::set_q_edge(), oomph::TRaviartThomasDarcyElement< ORDER >::set_q_internal(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::set_q_internal(), oomph::GeneralElasticityTensor::set_value(), oomph::ILUZeroPreconditioner< CCDoubleMatrix >::setup(), oomph::ILUZeroPreconditioner< CRDoubleMatrix >::setup(), oomph::HelmholtzMGPreconditioner< DIM >::setup_coarsest_level_structures(), oomph::HelmholtzMGPreconditioner< DIM >::setup_interpolation_matrices(), oomph::MGSolver< DIM >::setup_interpolation_matrices(), oomph::HelmholtzMGPreconditioner< DIM >::setup_interpolation_matrices_unstructured(), oomph::MGSolver< DIM >::setup_interpolation_matrices_unstructured(), oomph::Problem::sparse_assemble_row_or_column_compressed(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_lists(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_maps(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_two_arrays(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_two_vectors(), and oomph::Problem::sparse_assemble_row_or_column_compressed_with_vectors_of_pairs().
values
endcode We introduce wrapper functions to access function values
Definition at line 580 of file the_data_structure.txt.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::RefineableQElement< 3 >::check_integrity(), oomph::RefineableQElement< 2 >::check_integrity(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::check_integrity(), oomph::BoundaryNode< NODE_TYPE >::clear_copied_pointers(), oomph::HypreHelpers::create_HYPRE_Vector(), oomph::CRDoubleMatrixHelpers::create_uniformly_distributed_matrix(), oomph::Mesh::delete_all_external_storage(), oomph::SumOfMatrices::get_as_indices(), oomph::Problem::get_data_to_be_sent_during_load_balancing(), oomph::RefineableLinearElasticityEquations< DIM >::get_interpolated_values(), oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::get_interpolated_values(), oomph::RefineablePVDEquations< DIM >::get_interpolated_values(), oomph::RefineableLinearWaveEquations< DIM >::get_interpolated_values(), oomph::RefineableAdvectionDiffusionEquations< DIM >::get_interpolated_values(), oomph::RefineableSphericalAdvectionDiffusionEquations::get_interpolated_values(), oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_interpolated_values(), oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::get_interpolated_values(), oomph::RefineableYoungLaplaceEquations::get_interpolated_values(), oomph::RefineablePoissonEquations< DIM >::get_interpolated_values(), oomph::RefineableAxisymAdvectionDiffusionEquations::get_interpolated_values(), oomph::RefineableUnsteadyHeatEquations< DIM >::get_interpolated_values(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::get_interpolated_values(), oomph::RefineableHelmholtzEquations< DIM >::get_interpolated_values(), oomph::RefineablePMLHelmholtzEquations< DIM >::get_interpolated_values(), oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_interpolated_values(), oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_interpolated_values(), oomph::RefineablePVDEquationsWithPressure< DIM >::get_interpolated_values(), oomph::RefineableQSphericalTaylorHoodElement::get_interpolated_values(), oomph::RefineablePolarTaylorHoodElement::get_interpolated_values(), oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableLinearisedQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableElement::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::get_interpolated_values(), oomph::RefineableAxisymmetricQTaylorHoodElement::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::get_interpolated_values(), oomph::RefineableQSphericalCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableLinearisedQTaylorHoodElement::get_interpolated_values(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::get_interpolated_values(), oomph::RefineablePolarCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableQTaylorHoodElement< DIM >::get_interpolated_values(), oomph::VorticitySmootherElement< ELEMENT >::get_interpolated_values(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::get_interpolated_values(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolated_values(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::get_interpolated_values(), oomph::RefineableAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::get_interpolated_values(), oomph::RefineablePseudoSolidNodeUpdateElement< BASIC, SOLID >::get_interpolated_values(), oomph::RefineableQCrouzeixRaviartElement< DIM >::get_interpolated_values(), oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::get_interpolated_values(), oomph::PRefineableQCrouzeixRaviartElement< DIM >::get_interpolated_values(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::Problem::parallel_sparse_assemble(), oomph::Data::resize(), oomph::Data::set_time_stepper(), superlu(), superlu_complex(), superlu_dist_distributed_matrix(), superlu_dist_global_matrix(), oomph::Data::value(), and oomph::Node::value().
velocities
c Data can also store a certain number of c Data stores a pointer to a c TimeStepper whose member functions relate the history values to the values time derivatives pointer based read write access to the c Data values is provided by the functions code and by code Data::value_pt (t,i) \endcode which returns a pointer to the \c t -th history value associated with value \c i. Read-only access is also provided by the functions \code Data and its time dependent counterpart code whereas the values associated with t correspond to history values In many but this is not guaranteed See the section ref timestepping for further details subsection nodes Nodes In FE all c Nodes in a finite element mesh have c Data associated with them c Nodes are therefore derived from c but also store a spatial specified by a certain number of spatial (Eulerian) coordinates. The nodal positions are accessed by the member function \code Node note that the history values are not necessarily positions at previous timesteps subsubsection advanced_features_of_nodes Advanced we must evaluate mesh velocities
Definition at line 164 of file the_data_structure.txt.