/**

\mainpage Demo problem: Fluid Mechanics on unstructured meshes

This tutorial provides another quick demonstration of how to use
unstructured meshes for the solution of fluid flow problems.
(The <A HREF="http://en.wikipedia.org/wiki/Xfig">xfig </a>/
<A HREF="http://www.cs.cmu.edu/~quake/triangle.html">\c Triangle
</A> <a href="../../../meshes/mesh_from_xfig/html/index.html">
tutorial</a> already contains 2D and 3D unstructured fluid examples.)

The specific problem considered here serves as a "warm-up problem" for the
<a href="../../../interaction/unstructured_fsi/html/index.html">corresponding 
fluid-structure interaction problem</a> in which the part of the
domain boundary is replaced by an elastic object.
 
<HR>
<HR>

\section problem The problem 
Here is a sketch of the problem: Flow is driven through a 2D channel 
that is partly obstructed by an odd-shaped obstacle. The flow
is driven by the imposed Poiseuille flow at the upstream end of
the channel. 

\image html fluid_sketch.gif "Sketch of the problem. " 
\image latex fluid_sketch.eps "Sketch of the problem. " width=0.75\textwidth


<HR>
<HR> 

\section mesh Mesh generation
We use the combination of <A HREF="http://en.wikipedia.org/wiki/Xfig">xfig</A>,
\c oomph-lib's conversion code 
<a href="../../../meshes/mesh_from_xfig/html/index.html">
\c fig2poly </a>, and the unstructured
mesh generator 
<A HREF="http://www.cs.cmu.edu/~quake/triangle.html">\c Triangle
</A> to generate the mesh, using the procedure discussed in 
<a href="../../../meshes/mesh_from_xfig/html/index.html">
another tutorial.</a>

We start by drawing the outline of the fluid domain as a polyline in
<A HREF="http://en.wikipedia.org/wiki/Xfig">xfig</A>:

\image html xfig_screenshot.gif "xfig drawing of the fluid body. " 
\image latex xfig_screenshot.eps "xfig drawing of the fluid body. " width=0.75\textwidth
 
(Note that we draw the domain upside-down because of the way 
<A HREF="http://en.wikipedia.org/wiki/Xfig">xfig</A> orients its coordinate axes.)

We save the figure as a *.fig file and convert it to a *.poly file
using \c oomph-lib's conversion code 
<a href="../../../meshes/mesh_from_xfig/html/index.html">
\c fig2poly </a> (a copy of which is
located in \c oomph-lib's \c bin directory): 

\code
fig2poly fluid.fig 
\endcode

This creates a file called \c fluid.fig.poly that can be processed
using Triangle. For instance, to create a quality mesh with a maximum
element size of 0.03 we use
\code
triangle -q -a0.03 fluid.fig.poly
\endcode

Here is a plot of the mesh, generated by \c showme 
distributed with 
<A HREF="http://www.cs.cmu.edu/~quake/triangle.html">\c Triangle
</A>:

\image html showme_screenshot.gif "Visualisation of the mesh with showme. " 
\image latex showme_screenshot.eps "Visualisation of the mesh with showme. " width=0.75\textwidth

The <CODE> *.poly, *.ele </CODE> and <CODE> *.node </CODE>
files generated by 
<A HREF="http://www.cs.cmu.edu/~quake/triangle.html">\c Triangle
</A> can now be used as input to \c oomph-lib's 
\c TriangleMesh class.
 
<HR>
<HR> 



\section results Results
The animation shown below illustrates the flow field (streamlines and
pressure contours) for Reynolds numbers of \f$ Re=0, 5, 10, ... \f$
An increase in Reynolds number increases the length
of the recirculation region behind the obstacle; furthermore,
the sharp corner at the "leading edge" of the obstacle creates
very low pressures just downstream of the corner. 

\image html stream.gif "Flowfield (streamlines and pressure contours) at various Reynolds numbers. " 
\image latex stream.eps "Flowfield (streamlines and pressure contours) at various Reynolds numbers. " width=0.75\textwidth


<HR>
<HR>

\section mesh_code Creating the mesh

In anticipation of the mesh's use in a fluid-structure interaction
problem, we create the mesh by multiple inheritance from \c oomph-lib's 
\c TriangleMesh and the \c SolidMesh base class. This will allow
us to use pseudo-solid node-update techniques to update the position
of the fluid nodes in response to changes in the domain boundary. 
In the present problem, the "elasticity" of the fluid elements
plays no useful role; see \ref comm_ex for instructions on how to 
remove the pseudo-elasticity from the problem.

\dontinclude unstructured_two_d_fluid.cc
\skipline start_mesh
\until { 

The constructor calls the constructor of the underlying 
\c TriangleMesh, and, as usual, sets the Lagrangian coordinates
to the current nodal positions, making the current configuration
stress-free.

\until }

The \c TriangleMesh constructor associates each polyline in the
\c xfig drawing with a distinct \c oomph-lib mesh boundary. Hence
the boundary nodes are initially located on the same, single boundary.
The boundary conditions can be more easily applied if the boundary is
divided into three boundaries, which is the task of the function
\c TriangleMesh::identify_boundaries().

We first allocate storage for three boundaries:

\until set_nboundary

We loop over all nodes in the mesh and identify nodes on the left
(inflow) boundary by their x-coordinate. We remove the node
from the boundary 0 and re-allocate it to the new boundary 1:

\until }

Similarly, we identify all nodes on the right (outflow) boundary and
re-assign them to boundary 2, before re-generating the various boundary
lookup schemes that identify which elements are located next
to the various mesh boundaries:

\until };

<HR>
<HR>

\section namespace Problem Parameters
As usual we define the various problem parameters in a 
global namespace. We define the Reynolds number and 
prepare a pointer to a constitutive equation (for the pseudo-elastic
elements).

\skipline start_namespace
\until end_of_namespace

<HR>
<HR>

\section main The driver code

We specify an output directory and instantiate a constitutive 
equation for the pseudo-elasticity, specifying the Poisson ratio.

\dontinclude unstructured_two_d_fluid.cc
\skipline start_of_main
\until Nu);

We create the \c Problem object and output the domain boundaries
and the initial guess for the flow field.
\skipline Build
\until ()++

Finally, we perform a straightforward parameter study by
slowly increasing the Reynolds number of the flow from zero.

\until end_of_parameter_study


<HR>
<HR>

\section class The Problem class
The \c Problem class has the usual member functions and provides
explicit storage for the fluid mesh. [This is again slight overkill
for the problem at hand, and is done mainly in anticipation of 
the "upgrade" of this driver code to 
<a href="../../../interaction/unstructured_fsi/html/index.html">
the FSI problem</a> with its 
multiple meshes; in the present problem we could, of course, store the 
pointer to the problem's one-and-only mesh directly in 
\c Problem::mesh_pt(). ] 

\dontinclude unstructured_two_d_fluid.cc
\skipline start_of_problem_class
\until };

<HR>
<HR>

\section constructor The Problem constructor

We start by building the fluid mesh, using the files created
by <A HREF="http://www.cs.cmu.edu/~quake/triangle.html">\c Triangle
</A>.

\skipline start_constructor
\until fluid_poly_file_name);
 
Next, we apply the boundary conditions for the fluid and the 
pseudo-solid equations using the function \c
set_boundary_conditions(), which also completes the build of the
elements by setting the appropriate pointers to the physical
variables.

\until set_boundary_conditions()

We add the fluid mesh as a single sub-mesh to the \c Problem and build
the global mesh (see the comment in \ref class .)

\until build_global

Finally, we assign the equation numbers

\until end_of_constructor

<HR>
<HR>

\section bound Setting the boundary conditions


We pin the pseudo-solid nodes along
all domain boundaries, apply a no-slip condition for the fluid velocity 
along the solid boundary  (boundary 0), pin the velocity at the inflow
(boundary 1, where we will impose a Poiseuille flow profile), and impose
parallel outflow at the downstream end (boundary 2). 
Given that the manual identification of
mesh boundaries in unstructured meshes that are generated by
third-party mesh generators is a relatively error-prone process, we
document the boundary conditions in three separate files to allow 
an external sanity check; see
<a href="../../../solid/unstructured_solid/html/index.html#comm_ex">
the comments in the corresponding solid mechanics tutorial.</a>
The \ref comm_ex section of the present tutorial also has a sub-section 
that illustrates what can go wrong. 

\until solid_bc_file.close();

We complete the build of the elements by specifying
the Reynolds number and the constitutive equation for the pseudo-solid
equations. 

\until }

Finally, we impose a Poiseuille profile at the inflow boundary (boundary
1).

\until end_of_set_boundary_conditions


<HR>
<HR>

\section doc Post-processing

The post-processing routine outputs the flow field.

\until end_of_doc


<HR>
<HR>

\section comm_ex Comments and Exercises



<HR> 
 
 
\subsection reynolds What is the Reynolds number?
 
The problem considered here is  a "toy"-problem, devised
to illustrate the use of unstructured meshes in fluids problems.
The specific non-dimensionalisation and parameter values are therefore
of secondary importance. However, since \c oomph-lib's implementation
of the Navier-Stokes equations is based on their non-dimensional form
it is important to clarify the meaning of the Reynolds number 
in the present problem. 

<a href="../../driven_cavity/html/index.html#equation">Recall</a> 
that the Reynolds number is defined as 
\f[
Re = \frac{\rho {\cal U} {\cal L}}{\mu}
\f]
where \f$ \rho \f$ and \f$ \mu \f$ are the fluid density and viscosity,
respectively.  \f$ {\cal L} \f$ is the reference length chosen for the
non-dimensionalisation of the coordinates. In the present problem,
where the domain boundaries were simply drawn in 
<A HREF="http://en.wikipedia.org/wiki/Xfig">xfig </a>, no specific reference
length was identified, but inspection of the maximum and minimum 
y-coordinates of the inflow boundary in the mesh plot 
shows that the inflow boundary has a (dimensional) length 
of \f$ (4.0875 - 0.1125) {\cal L} = 3.975 {\cal L}. \f$
In the non-dimensional version of the Navier-Stokes equations, all 
velocities are non-dimensionalised with a reference velocity
\f$ {\cal U} \f$. When we applied the inflow boundary conditions,
we chose the (dimensionless) inflow profile such that its 
integral over the inflow boundary yields a value of 1. The velocity 
scale \f$ {\cal U} \f$ may therefore be interpreted as 
a (dimensional) average inflow velocity through the channel, i.e. the
volume flux divided by the reference length scale.

<HR>

\subsection bound Identification/assignment of mesh boundaries
We wish to re-iterate the comments made in the 
<a href="../../../solid/unstructured_solid/html/index.html#comm_ex">
corresponding solid mechanics tutorial</a> that the manual 
identification of nodes on domain boundaries is tedious and 
therefore error prone. It pays off to <B>be  as a paranoid 
as possible</B>, by always documenting the domain boundaries and the
applied boundary conditions. 

 Here is the plot of boundary conditions applied in the present
problem. Hollow blue markers indicate (pseudo-)solid boundary conditions
(both displacements are pinned); small red markers identify nodes
where the vertical fluid velocity is pinned; hollow green markers (filling
the space between the blue and red lines markers) identify nodes at
which the horizontal fluid velocity is pinned. 

\image html bcs.gif "Plot of the correct boundary conditions. " 
\image latex bcs.eps "Plot of the correct boundary conditions. " width=0.75\textwidth

Here is another plot, obtained with the initial version of 
our driver code -- can you spot what's wrong and can you
identify the lines were added to the mesh constructor to 
fix the problem? 

\image html bcs_wrong.gif "Plot of the wrong boundary conditions. " 
\image latex bcs_wrong.eps "Plot of the wrong boundary conditions. " width=0.75\textwidth



<HR>

\subsection pseudo_elast Pseudo-elasticity

As mentioned above, the elements' pseudo-elasticity plays no useful
role in the present problem, as the domain boundaries remain
at fixed positions and no mesh movement is required. 

- As an exercise, remove all functionality related to the 
  pseudo-elasticity by changing the element type from
  \code
  PseudoSolidNodeUpdateElement<TTaylorHoodElement<2>,TPVDElement<2,3> >
  \endcode
  to
  \code
  TTaylorHoodElement<2>
  \endcode
  Adjust the code as required (e.g. remove mesh's inheritance from the
  \c SolidMesh base class; remove the application of boundary conditions
  for the nodal positions; etc) and confirm that the results
  for the flow field remain unchanged.
  \n\n
- Alternatively, the pseudo-elasticity can can be suppressed by 
  pinning all nodal positions, drastically reducing the number
  of degrees of freedom in the problem without the need to 
  rewrite the rest of the code. (Note that this is also a useful
  test for the development of FSI codes.)
  \n\n
- However, if the pseudo-elastic capabilities are retained
  the fluid mesh can indeed deform as an elastic
  body; for example, by specifying a (solid mechanics) body force. 
  Simply follow the steps used in 
  <a href="../../../solid/unstructured_solid/html/index.html">
  the corresponding solid mechanics problem.</a> Define the body
  force in the namespace \c Global_Physical_Variables
  and pass a (function-)pointer to it 
  to the elements. N.B. 
  The body force for the (pseudo-)solid equations must be specified explicitly
  because  the Navier-Stokes equations have their own body force
  pointer! The compiler will complain about ambiguities in the following code: 
  \n
  \code
  [...]

   //Set the body force
   el_pt->body_force_fct_pt() = Global_Physical_Variables::gravity;

  [...]  
  \endcode
  Instead, we must be more specific by writing
  \n
  \code
  [...]

   //Set the body force
   el_pt->PVDEquationsBase<2>::body_force_fct_pt() = 
    Global_Physical_Variables::gravity;
  
  [...]   
  \endcode
   indicating that it is the body force defined in the
  2D solid mechanics equations that is being specified.
.

<HR>
<HR>

\section sources Source files for this tutorial
- The source files for this tutorial are located in the directory:\n\n
<CENTER>
<A HREF="../../../../demo_drivers/navier_stokes/unstructured_fluid/">
demo_drivers/navier_stokes/unstructured_fluid/
</A>
</CENTER>\n
- The driver code is: \n\n
<CENTER>
<A HREF="../../../../demo_drivers/navier_stokes/unstructured_fluid/unstructured_two_d_fluid.cc">
demo_drivers/navier_stokes/unstructured_fluid/unstructured_two_d_fluid.cc
</A>
</CENTER>
.











<hr>
<hr>
\section pdf PDF file
A <a href="../latex/refman.pdf">pdf version</a> of this document is available.
**/

