ElasticFishProblem< ELEMENT > Class Template Reference
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Public Member Functions
ElasticFishProblem ()
Constructor:
void run ()
Run simulation.
ElasticFishMesh< ELEMENT > * mesh_pt ()
Access function for the mesh.
void doc_solution (DocInfo &doc_info)
Doc the solution.
void actions_after_newton_solve ()
Update function (empty)
void actions_before_newton_solve ()
Update before solve: We're dealing with a static problem so the nodal positions before the next solve merely serve as initial conditions. For meshes that are very strongly refined near the boundary, the update of the displacement boundary conditions (which only moves the SolidNodes on the boundary), can lead to strongly distorted meshes. This can cause the Newton method to fail --> the overall method is actually more robust if we use the nodal positions as determined by the Domain/MacroElement- based mesh update as initial guesses.
void actions_after_adapt ()
Update after adapt: Pin all redundant pressure nodes (if required)
Private Attributes
Circle * Fish_back_pt
Detailed Description
template<class ELEMENT>
class ElasticFishProblem< ELEMENT >
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Boundary-driven elastic deformation of fish-shaped domain.
Definition at line 181 of file static_fish.cc.
Constructor & Destructor Documentation
ElasticFishProblem()
template<class ELEMENT >
ElasticFishProblem< ELEMENT >::ElasticFishProblem
Constructor:
Definition at line 237 of file static_fish.cc.
References Global_Physical_Variables::body_force(), and Global_Physical_Variables::Constitutive_law_pt.
Member Function Documentation
actions_after_adapt()
template<class ELEMENT >
void ElasticFishProblem< ELEMENT >::actions_after_adapt () [inline]
Update after adapt: Pin all redundant pressure nodes (if required)
Definition at line 218 of file static_fish.cc.
References ElasticFishProblem< ELEMENT >::mesh_pt().
actions_after_newton_solve()
template<class ELEMENT >
void ElasticFishProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update function (empty)
Definition at line 200 of file static_fish.cc.
actions_before_newton_solve()
template<class ELEMENT >
void ElasticFishProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update before solve: We're dealing with a static problem so the nodal positions before the next solve merely serve as initial conditions. For meshes that are very strongly refined near the boundary, the update of the displacement boundary conditions (which only moves the SolidNodes on the boundary), can lead to strongly distorted meshes. This can cause the Newton method to fail --> the overall method is actually more robust if we use the nodal positions as determined by the Domain/MacroElement- based mesh update as initial guesses.
Definition at line 211 of file static_fish.cc.
References ElasticFishProblem< ELEMENT >::mesh_pt().
doc_solution()
template<class ELEMENT >
void ElasticFishProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 327 of file static_fish.cc.
mesh_pt()
template<class ELEMENT >
ElasticFishMesh< ELEMENT > * ElasticFishProblem< ELEMENT >::mesh_pt () [inline]
Access function for the mesh.
Definition at line 193 of file static_fish.cc.
Referenced by ElasticFishProblem< ELEMENT >::actions_after_adapt(), and ElasticFishProblem< ELEMENT >::actions_before_newton_solve().
run()
template<class ELEMENT >
void ElasticFishProblem< ELEMENT >::run
Run simulation.
Run the problem.
Definition at line 354 of file static_fish.cc.
References Global_Physical_Variables::Gravity.
Referenced by main().
Member Data Documentation
Fish_back_pt
template<class ELEMENT >
Circle* ElasticFishProblem< ELEMENT >::Fish_back_pt [private]
Definition at line 229 of file static_fish.cc.
The documentation for this class was generated from the following file:
static_fish.cc