UnstructuredPoissonProblem< ELEMENT > Class Template Reference
//////////////////////////////////////////////////////// ////////////////////////////////////////////////////////
Public Member Functions
UnstructuredPoissonProblem ()
Constructor.
~UnstructuredPoissonProblem ()
Destructor.
void actions_before_adapt ()
Actions before adapt. Empty.
void actions_after_adapt ()
Actions after adapt: Setup the problem again -- remember that the mesh has been completely rebuilt and its element's don't have any pointers to source fcts etc. yet.
void actions_after_newton_solve ()
Update after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve: Re-apply boundary conditons.
void doc_solution (const std::string &comment=``)
Doc the solution.
UnstructuredPoissonProblem ()
Constructor.
~UnstructuredPoissonProblem ()
Destructor.
void actions_after_newton_solve ()
Update after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve: Re-apply boundary conditons.
void doc_solution (const std::string &comment=``)
Doc the solution.
Private Member Functions
void apply_boundary_conditions ()
Helper function to apply boundary conditions.
void complete_problem_setup ()
Helper function to (re-)set boundary condition and complete the build of all elements.
void apply_boundary_conditions ()
Helper function to apply boundary conditions.
void complete_problem_setup ()
Helper function to (re-)set boundary condition and complete the build of all elements.
Private Attributes
DocInfo Doc_info
Doc info object for labeling output.
RefineableTriangleMesh< ELEMENT > * My_mesh_pt
Pointers to specific mesh.
ofstream Trace_file
Trace file to document norm of solution.
TriangleMesh< ELEMENT > * My_mesh_pt
Pointers to specific mesh.
Detailed Description
template<class ELEMENT>
class UnstructuredPoissonProblem< ELEMENT >
//////////////////////////////////////////////////////// ////////////////////////////////////////////////////////
Class definition
Definition at line 90 of file mesh_from_inline_triangle.cc.
Constructor & Destructor Documentation
UnstructuredPoissonProblem() [1/2]
template<class ELEMENT >
UnstructuredPoissonProblem< ELEMENT >::UnstructuredPoissonProblem
Constructor.
Definition at line 154 of file mesh_from_inline_triangle.cc.
 UnstructuredPoissonProblem() [1/2]
template<class ELEMENT >
UnstructuredPoissonProblem< ELEMENT >::~UnstructuredPoissonProblem () [inline]
Destructor.
Definition at line 99 of file mesh_from_inline_triangle.cc.
UnstructuredPoissonProblem() [2/2]
template<class ELEMENT >
UnstructuredPoissonProblem< ELEMENT >::UnstructuredPoissonProblem ()
Constructor.
 UnstructuredPoissonProblem() [2/2]
template<class ELEMENT >
UnstructuredPoissonProblem< ELEMENT >::~UnstructuredPoissonProblem () [inline]
Destructor.
Definition at line 99 of file mesh_from_inline_triangle_no_adapt.cc.
Member Function Documentation
actions_after_adapt()
template<class ELEMENT >
void UnstructuredPoissonProblem< ELEMENT >::actions_after_adapt () [inline]
Actions after adapt: Setup the problem again -- remember that the mesh has been completely rebuilt and its element's don't have any pointers to source fcts etc. yet.
Definition at line 108 of file mesh_from_inline_triangle.cc.
References UnstructuredPoissonProblem< ELEMENT >::complete_problem_setup().
actions_after_newton_solve() [1/2]
template<class ELEMENT >
void UnstructuredPoissonProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update after solve (empty)
Definition at line 114 of file mesh_from_inline_triangle.cc.
actions_after_newton_solve() [2/2]
template<class ELEMENT >
void UnstructuredPoissonProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update after solve (empty)
Definition at line 102 of file mesh_from_inline_triangle_no_adapt.cc.
actions_before_adapt()
template<class ELEMENT >
void UnstructuredPoissonProblem< ELEMENT >::actions_before_adapt () [inline]
Actions before adapt. Empty.
Definition at line 102 of file mesh_from_inline_triangle.cc.
actions_before_newton_solve() [1/2]
template<class ELEMENT >
void UnstructuredPoissonProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve: Re-apply boundary conditons.
Definition at line 117 of file mesh_from_inline_triangle.cc.
References UnstructuredPoissonProblem< ELEMENT >::apply_boundary_conditions().
actions_before_newton_solve() [2/2]
template<class ELEMENT >
void UnstructuredPoissonProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve: Re-apply boundary conditons.
Definition at line 105 of file mesh_from_inline_triangle_no_adapt.cc.
References UnstructuredPoissonProblem< ELEMENT >::apply_boundary_conditions().
apply_boundary_conditions() [1/2]
template<class ELEMENT >
void UnstructuredPoissonProblem< ELEMENT >::apply_boundary_conditions [private]
Helper function to apply boundary conditions.
Definition at line 502 of file mesh_from_inline_triangle.cc.
References TanhSolnForPoisson::get_exact_u().
Referenced by UnstructuredPoissonProblem< ELEMENT >::actions_before_newton_solve().
apply_boundary_conditions() [2/2]
template<class ELEMENT >
void UnstructuredPoissonProblem< ELEMENT >::apply_boundary_conditions () [private]
Helper function to apply boundary conditions.
complete_problem_setup() [1/2]
template<class ELEMENT >
void UnstructuredPoissonProblem< ELEMENT >::complete_problem_setup [private]
Helper function to (re-)set boundary condition and complete the build of all elements.
Set boundary condition exactly, and complete the build of all elements.
Definition at line 458 of file mesh_from_inline_triangle.cc.
References TanhSolnForPoisson::get_source().
Referenced by UnstructuredPoissonProblem< ELEMENT >::actions_after_adapt().
complete_problem_setup() [2/2]
template<class ELEMENT >
void UnstructuredPoissonProblem< ELEMENT >::complete_problem_setup () [private]
Helper function to (re-)set boundary condition and complete the build of all elements.
doc_solution() [1/2]
template<class ELEMENT >
void UnstructuredPoissonProblem< ELEMENT >::doc_solution (const std::string & comment = ``)
Doc the solution.
Definition at line 536 of file mesh_from_inline_triangle.cc.
References TanhSolnForPoisson::get_exact_u(), and TanhSolnForPoisson::zero().
Referenced by main().
doc_solution() [2/2]
template<class ELEMENT >
void UnstructuredPoissonProblem< ELEMENT >::doc_solution (const std::string & comment = ``)
Doc the solution.
Member Data Documentation
Doc_info
template<class ELEMENT >
DocInfo UnstructuredPoissonProblem< ELEMENT >::Doc_info [private]
Doc info object for labeling output.
Definition at line 129 of file mesh_from_inline_triangle.cc.
My_mesh_pt [1/2]
template<class ELEMENT >
RefineableTriangleMesh<ELEMENT>* UnstructuredPoissonProblem< ELEMENT >::My_mesh_pt [private]
Pointers to specific mesh.
Definition at line 139 of file mesh_from_inline_triangle.cc.
My_mesh_pt [2/2]
template<class ELEMENT >
TriangleMesh<ELEMENT>* UnstructuredPoissonProblem< ELEMENT >::My_mesh_pt [private]
Pointers to specific mesh.
Definition at line 127 of file mesh_from_inline_triangle_no_adapt.cc.
Trace_file
template<class ELEMENT >
ofstream UnstructuredPoissonProblem< ELEMENT >::Trace_file [private]
Trace file to document norm of solution.
Definition at line 142 of file mesh_from_inline_triangle.cc.
The documentation for this class was generated from the following files:
mesh_from_inline_triangle.cc
mesh_from_inline_triangle_no_adapt.cc