SimpleRefineableFishPoissonProblem< ELEMENT > Class Template Reference
Poisson problem in fish-shaped domain. Template parameter identifies the element type.
Public Member Functions
SimpleRefineableFishPoissonProblem ()
Constructor.
virtual ~SimpleRefineableFishPoissonProblem ()
Destructor: Empty.
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
SimpleRefineableFishMesh< ELEMENT > * mesh_pt ()
Overloaded version of the problem's access function to the mesh. Recasts the pointer to the base Mesh object to the actual mesh type.
void doc_solution (DocInfo &doc_info)
Doc the solution. Output directory and labels are specified by DocInfo object.
Detailed Description
template<class ELEMENT>
class SimpleRefineableFishPoissonProblem< ELEMENT >
Poisson problem in fish-shaped domain. Template parameter identifies the element type.
Definition at line 110 of file fish_poisson_simple_adapt.cc.
Constructor & Destructor Documentation
SimpleRefineableFishPoissonProblem()
template<class ELEMENT >
SimpleRefineableFishPoissonProblem< ELEMENT >::SimpleRefineableFishPoissonProblem
Constructor.
Constructor for adaptive Poisson problem in fish-shaped domain.
Definition at line 150 of file fish_poisson_simple_adapt.cc.
References ConstSourceForPoisson::get_source().
 SimpleRefineableFishPoissonProblem()
template<class ELEMENT >
virtual SimpleRefineableFishPoissonProblem< ELEMENT >::~SimpleRefineableFishPoissonProblem () [inline], [virtual]
Destructor: Empty.
Definition at line 119 of file fish_poisson_simple_adapt.cc.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT >
void SimpleRefineableFishPoissonProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem specs after solve (empty)
Definition at line 122 of file fish_poisson_simple_adapt.cc.
actions_before_newton_solve()
template<class ELEMENT >
void SimpleRefineableFishPoissonProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve (empty)
Definition at line 125 of file fish_poisson_simple_adapt.cc.
doc_solution()
template<class ELEMENT >
void SimpleRefineableFishPoissonProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution. Output directory and labels are specified by DocInfo object.
Doc the solution in tecplot format.
Definition at line 202 of file fish_poisson_simple_adapt.cc.
Referenced by main().
mesh_pt()
template<class ELEMENT >
SimpleRefineableFishMesh< ELEMENT > * SimpleRefineableFishPoissonProblem< ELEMENT >::mesh_pt () [inline]
Overloaded version of the problem's access function to the mesh. Recasts the pointer to the base Mesh object to the actual mesh type.
Definition at line 130 of file fish_poisson_simple_adapt.cc.
Referenced by main().
The documentation for this class was generated from the following file:
fish_poisson_simple_adapt.cc