ElasticBeamProblem Class Reference
Beam problem object.
Public Member Functions
ElasticBeamProblem (const unsigned &n_elem, const double &length)
Constructor: The arguments are the number of elements, the length of domain.
void parameter_study ()
Conduct a parameter study.
OneDLagrangianMesh< HermiteBeamElement > * mesh_pt ()
Return pointer to the mesh.
void actions_after_newton_solve ()
No actions need to be performed after a solve.
void actions_before_newton_solve ()
No actions need to be performed before a solve.
Private Attributes
Node * Doc_node_pt
Pointer to the node whose displacement is documented.
double Length
Length of domain (in terms of the Lagrangian coordinates)
GeomObject * Undef_beam_pt
Pointer to geometric object that represents the beam's undeformed shape.
Detailed Description
Beam problem object.
Definition at line 63 of file tensioned_string.cc.
Constructor & Destructor Documentation
ElasticBeamProblem()
ElasticBeamProblem::ElasticBeamProblem (const unsigned & n_elem, const double & length)
Constructor: The arguments are the number of elements, the length of domain.
Constructor for elastic beam problem.
Definition at line 102 of file tensioned_string.cc.
References Doc_node_pt, Global_Physical_Variables::H, Global_Physical_Variables::load(), mesh_pt(), Global_Physical_Variables::Sigma0, and Undef_beam_pt.
Member Function Documentation
actions_after_newton_solve()
void ElasticBeamProblem::actions_after_newton_solve () [inline]
No actions need to be performed after a solve.
Definition at line 80 of file tensioned_string.cc.
actions_before_newton_solve()
void ElasticBeamProblem::actions_before_newton_solve () [inline]
No actions need to be performed before a solve.
Definition at line 83 of file tensioned_string.cc.
mesh_pt()
OneDLagrangianMesh<HermiteBeamElement>* ElasticBeamProblem::mesh_pt () [inline]
Return pointer to the mesh.
Definition at line 75 of file tensioned_string.cc.
Referenced by ElasticBeamProblem(), and parameter_study().
parameter_study()
void ElasticBeamProblem::parameter_study ()
Conduct a parameter study.
Solver loop to perform parameter study.
Definition at line 172 of file tensioned_string.cc.
References Doc_node_pt, Global_Physical_Variables::H, Length, mesh_pt(), Global_Physical_Variables::P_ext, and Global_Physical_Variables::Sigma0.
Referenced by main().
Member Data Documentation
Doc_node_pt
Node* ElasticBeamProblem::Doc_node_pt [private]
Pointer to the node whose displacement is documented.
Definition at line 88 of file tensioned_string.cc.
Referenced by ElasticBeamProblem(), and parameter_study().
Length
double ElasticBeamProblem::Length [private]
Length of domain (in terms of the Lagrangian coordinates)
Definition at line 91 of file tensioned_string.cc.
Referenced by parameter_study().
Undef_beam_pt
GeomObject* ElasticBeamProblem::Undef_beam_pt [private]
Pointer to geometric object that represents the beam's undeformed shape.
Definition at line 94 of file tensioned_string.cc.
Referenced by ElasticBeamProblem().
The documentation for this class was generated from the following file:
tensioned_string.cc