oomph::RefineableFishMesh< ELEMENT > Class Template Reference
Refineable fish shaped mesh. The geometry is defined by the Domain object FishDomain.
#include <fish_mesh.h>
Public Member Functions
RefineableFishMesh (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass pointer to timestepper -- defaults to (Steady) default timestepper defined in the Mesh base class.
RefineableFishMesh (GeomObject *back_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass pointer GeomObject that defines the fish's back and pointer to timestepper (defaults to (Steady) default timestepper defined in Mesh)
virtual ~RefineableFishMesh ()
Destructor: Empty -- all cleanup gets handled in the base classes.
Public Member Functions inherited from oomph::FishMesh< ELEMENT >
FishMesh (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass pointer to timestepper (defaults to the (Steady) default timestepper defined in Mesh)
FishMesh (GeomObject *back_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass pointer GeomObject that defines the fish's back and pointer to timestepper (defaults to the (Steady) default timestepper defined in Mesh)
virtual ~FishMesh ()
Destructor: Kill the geom object that represents the fish's back (if necessary)
GeomObject *& fish_back_pt ()
Access function to geom object that represents the fish's back.
FishDomain *& domain_pt ()
Access function to FishDomain.
Protected Member Functions
void setup_adaptivity ()
Setup all the information that's required for spatial adaptivity: Set pointers to macro elements and build quadtree forest. (contained in separate function as this functionality is common to both constructors),.
Protected Member Functions inherited from oomph::FishMesh< ELEMENT >
void build_mesh (TimeStepper *time_stepper_pt)
Build the mesh, using the geometric object identified by Back_pt.
Additional Inherited Members
Protected Types inherited from oomph::FishMesh< ELEMENT >
enum { Lower_body
, Upper_body
, Lower_fin
, Upper_fin
 }
Remesh function ids.
Protected Attributes inherited from oomph::FishMesh< ELEMENT >
GeomObject * Back_pt
Pointer to fish back.
FishDomain * Domain_pt
Pointer to domain.
bool Must_kill_fish_back
Do I need to kill the fish back geom object?
Detailed Description
template<class ELEMENT>
class oomph::RefineableFishMesh< ELEMENT >
Refineable fish shaped mesh. The geometry is defined by the Domain object FishDomain.
Definition at line 124 of file fish_mesh.h.
Constructor & Destructor Documentation
RefineableFishMesh() [1/2]
template<class ELEMENT >
oomph::RefineableFishMesh< ELEMENT >::RefineableFishMesh (TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass pointer to timestepper -- defaults to (Steady) default timestepper defined in the Mesh base class.
Definition at line 130 of file fish_mesh.h.
References oomph::RefineableFishMesh< ELEMENT >::setup_adaptivity().
RefineableFishMesh() [2/2]
template<class ELEMENT >
oomph::RefineableFishMesh< ELEMENT >::RefineableFishMesh (GeomObject * back_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass pointer GeomObject that defines the fish's back and pointer to timestepper (defaults to (Steady) default timestepper defined in Mesh)
Definition at line 146 of file fish_mesh.h.
References oomph::RefineableFishMesh< ELEMENT >::setup_adaptivity().
~RefineableFishMesh()
template<class ELEMENT >
virtual oomph::RefineableFishMesh< ELEMENT >::~RefineableFishMesh () [inline], [virtual]
Destructor: Empty -- all cleanup gets handled in the base classes.
Definition at line 160 of file fish_mesh.h.
Member Function Documentation
setup_adaptivity()
template<class ELEMENT >
void oomph::RefineableFishMesh< ELEMENT >::setup_adaptivity () [protected]
Setup all the information that's required for spatial adaptivity: Set pointers to macro elements and build quadtree forest. (contained in separate function as this functionality is common to both constructors),.
Setup all the information that's required for spatial adaptivity: Build quadtree forest.
Definition at line 641 of file fish_mesh.template.cc.
References oomph::TetgenMesh< ELEMENT >::TetgenMesh().
Referenced by oomph::RefineableFishMesh< ELEMENT >::RefineableFishMesh(), and oomph::RefineableFishMesh< ELEMENT >::RefineableFishMesh().
The documentation for this class was generated from the following files:
fish_mesh.h
fish_mesh.template.cc