oomph::ElasticRectangularQuadMesh< ELEMENT > Class Template Reference
#include <rectangular_quadmesh.template.h>
Public Member Functions
ElasticRectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly, const Vector< double > &origin, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Build mesh and copy Eulerian coords to Lagrangian ones so that the initial configuration is the stress-free one and assign boundary coordinates. Origin specifies an additional rigid-body displacement.
ElasticRectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Build mesh and copy Eulerian coords to Lagrangian ones so that the initial configuration is the stress-free one and assign boundary coordinates.
ElasticRectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly, const bool &periodic_in_x, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Build mesh and copy Eulerian coords to Lagrangian ones so that the initial configuration is the stress-free one and assign boundary coordinates. This includes a boolean flag to specify if the mesh is periodic in the x-direction.
Private Member Functions
void set_boundary_coordinates (const Vector< double > &origin)
Setup the boundary coordinates. Vector origin specifies the coordinates of the lower left corner of the mesh.
Additional Inherited Members
Detailed Description
template<class ELEMENT>
class oomph::ElasticRectangularQuadMesh< ELEMENT >
Elastic quad mesh with functionality to attach traction elements to the specified boundaries. We `upgrade` the RectangularQuadMesh to become an SolidMesh and equate the Eulerian and Lagrangian coordinates, thus making the domain represented by the mesh the stress-free configuration.
Definition at line 420 of file rectangular_quadmesh.template.h.
Constructor & Destructor Documentation
ElasticRectangularQuadMesh() [1/3]
template<class ELEMENT >
oomph::ElasticRectangularQuadMesh< ELEMENT >::ElasticRectangularQuadMesh (const unsigned & nx, const unsigned & ny, const double & lx, const double & ly, const Vector< double > & origin, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Build mesh and copy Eulerian coords to Lagrangian ones so that the initial configuration is the stress-free one and assign boundary coordinates. Origin specifies an additional rigid-body displacement.
Make the current configuration the undeformed one by setting the nodal Lagrangian coordinates to their current Eulerian ones
Definition at line 429 of file rectangular_quadmesh.template.h.
References oomph::ElasticRectangularQuadMesh< ELEMENT >::set_boundary_coordinates().
ElasticRectangularQuadMesh() [2/3]
template<class ELEMENT >
oomph::ElasticRectangularQuadMesh< ELEMENT >::ElasticRectangularQuadMesh (const unsigned & nx, const unsigned & ny, const double & lx, const double & ly, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Build mesh and copy Eulerian coords to Lagrangian ones so that the initial configuration is the stress-free one and assign boundary coordinates.
Make the current configuration the undeformed one by setting the nodal Lagrangian coordinates to their current Eulerian ones
Definition at line 459 of file rectangular_quadmesh.template.h.
References oomph::ElasticRectangularQuadMesh< ELEMENT >::set_boundary_coordinates().
ElasticRectangularQuadMesh() [3/3]
template<class ELEMENT >
oomph::ElasticRectangularQuadMesh< ELEMENT >::ElasticRectangularQuadMesh (const unsigned & nx, const unsigned & ny, const double & lx, const double & ly, const bool & periodic_in_x, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Build mesh and copy Eulerian coords to Lagrangian ones so that the initial configuration is the stress-free one and assign boundary coordinates. This includes a boolean flag to specify if the mesh is periodic in the x-direction.
Make the current configuration the undeformed one by setting the nodal Lagrangian coordinates to their current Eulerian ones
Definition at line 484 of file rectangular_quadmesh.template.h.
References oomph::ElasticRectangularQuadMesh< ELEMENT >::set_boundary_coordinates().
Member Function Documentation
set_boundary_coordinates()
template<class ELEMENT >
void oomph::ElasticRectangularQuadMesh< ELEMENT >::set_boundary_coordinates (const Vector< double > & origin) [inline], [private]
Setup the boundary coordinates. Vector origin specifies the coordinates of the lower left corner of the mesh.
Definition at line 510 of file rectangular_quadmesh.template.h.
References oomph::RectangularQuadMesh< ELEMENT >::Ymax, and oomph::RectangularQuadMesh< ELEMENT >::Ymin.
Referenced by oomph::ElasticRectangularQuadMesh< ELEMENT >::ElasticRectangularQuadMesh().
The documentation for this class was generated from the following file:
rectangular_quadmesh.template.h