NavierStokesProblem< ELEMENT > Class Template Reference
Entry flow problem in quarter tube domain.
Public Member Functions
NavierStokesProblem (DocInfo &doc_info, const string &node_file_name, const string &element_file_name, const string &face_file_name)
Constructor: Pass DocInfo object and file names.
~NavierStokesProblem ()
Destructor (empty)
void actions_after_newton_solve ()
Doc the solution after solve.
void actions_before_newton_solve ()
Update the problem specs before solve.
void doc_solution ()
Doc the solution.
TetgenMesh< ELEMENT > * mesh_pt ()
Private Attributes
DocInfo Doc_info
Doc info object.
Detailed Description
template<class ELEMENT>
class NavierStokesProblem< ELEMENT >
Entry flow problem in quarter tube domain.
Definition at line 55 of file mesh_from_tetgen_navier_stokes.cc.
Constructor & Destructor Documentation
NavierStokesProblem()
template<class ELEMENT >
NavierStokesProblem< ELEMENT >::NavierStokesProblem (DocInfo & doc_info, const string & node_file_name, const string & element_file_name, const string & face_file_name)
Constructor: Pass DocInfo object and file names.
Constructor: Pass DocInfo object mesh files.
Definition at line 107 of file mesh_from_tetgen_navier_stokes.cc.
References NavierStokesProblem< ELEMENT >::mesh_pt(), and Global_Physical_Variables::Re.
~NavierStokesProblem()
template<class ELEMENT >
NavierStokesProblem< ELEMENT >::~NavierStokesProblem () [inline]
Destructor (empty)
Definition at line 67 of file mesh_from_tetgen_navier_stokes.cc.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT >
void NavierStokesProblem< ELEMENT >::actions_after_newton_solve () [inline]
Doc the solution after solve.
Definition at line 70 of file mesh_from_tetgen_navier_stokes.cc.
References NavierStokesProblem< ELEMENT >::Doc_info, and NavierStokesProblem< ELEMENT >::doc_solution().
actions_before_newton_solve()
template<class ELEMENT >
void NavierStokesProblem< ELEMENT >::actions_before_newton_solve ()
Update the problem specs before solve.
Set the inflow boundary conditions.
Definition at line 185 of file mesh_from_tetgen_navier_stokes.cc.
References oomph::TetgenMesh< ELEMENT >::TetgenMesh().
doc_solution()
template<class ELEMENT >
void NavierStokesProblem< ELEMENT >::doc_solution ()
Doc the solution.
Definition at line 205 of file mesh_from_tetgen_navier_stokes.cc.
References oomph::TetgenMesh< ELEMENT >::TetgenMesh().
Referenced by NavierStokesProblem< ELEMENT >::actions_after_newton_solve().
mesh_pt()
template<class ELEMENT >
TetgenMesh< ELEMENT > * NavierStokesProblem< ELEMENT >::mesh_pt () [inline]
Definition at line 86 of file mesh_from_tetgen_navier_stokes.cc.
Referenced by NavierStokesProblem< ELEMENT >::NavierStokesProblem().
Member Data Documentation
Doc_info
template<class ELEMENT >
DocInfo NavierStokesProblem< ELEMENT >::Doc_info [private]
Doc info object.
Definition at line 96 of file mesh_from_tetgen_navier_stokes.cc.
Referenced by NavierStokesProblem< ELEMENT >::actions_after_newton_solve().
The documentation for this class was generated from the following file:
mesh_from_tetgen_navier_stokes.cc