two_d_adv_diff_adapt2.cc File Reference
Classes
class RefineableAdvectionDiffusionProblem< ELEMENT >
2D AdvectionDiffusion problem on rectangular domain, discretised with refineable 2D QAdvectionDiffusion elements. The specific type of element is specified via the template parameter.
Namespaces
namespace TanhSolnForAdvectionDiffusion
Namespace for exact solution for AdvectionDiffusion equation with "sharp" step.
Functions
void TanhSolnForAdvectionDiffusion::tanh_profile (const Vector< double > &x, Vector< double > &u)
Tanh profile for assignment of boundary conditons as a Vector.
void TanhSolnForAdvectionDiffusion::tanh_profile (const Vector< double > &x, double &u)
Tanh profile for assignment of boundary conditons as a Vector.
void TanhSolnForAdvectionDiffusion::source_function (const Vector< double > &x_vect, double &source)
Source function required to make the solution above an exact solution.
void TanhSolnForAdvectionDiffusion::wind_function (const Vector< double > &x, Vector< double > &wind)
Wind.
int main ()
Driver code for 2D AdvectionDiffusion problem.
Function Documentation
main()
int main ()
Driver code for 2D AdvectionDiffusion problem.
Definition at line 277 of file two_d_adv_diff_adapt2.cc.
References TanhSolnForAdvectionDiffusion::Alpha, RefineableAdvectionDiffusionProblem< ELEMENT >::doc_solution(), RefineableAdvectionDiffusionProblem< ELEMENT >::mesh_pt(), TanhSolnForAdvectionDiffusion::source_function(), TanhSolnForAdvectionDiffusion::TanPhi, and TanhSolnForAdvectionDiffusion::wind_function().