oomph::PicardConvergenceData Class Reference
Object that collates convergence data of Picard iteration.
#include <segregated_fsi_solver.h>
Public Member Functions
PicardConvergenceData ()
Constructor initialises all data.
~PicardConvergenceData ()
Empty destructor.
unsigned & niter ()
Number of iterations performed.
double & cpu_total ()
Total CPU time for segregated solve.
double & essential_cpu_total ()
Total essential CPU time for segregated solve (excluding any actions that merely doc the progress of the iteration, etc.)
double & cpu_for_global_residual ()
CPU time for computation of global residual vectors Note: This time is contained in Total_CPU and is only used if convergence is based on the residual of the fully coupled system.
double & tol_achieved ()
Final tolerance achieved by the iteration.
bool has_converged () const
Flag to indicate if the solver has converged.
void set_solver_converged ()
Set the flag to indicate that the solver has converged.
void set_solver_not_converged ()
Set the flag to indicate that the solver has not converged.
Private Attributes
unsigned Niter
Number of iterations performed.
double CPU_total
Total CPU time for segregated solve.
double Essential_cpu_total
Total essential CPU time for segregated solve (excluding any actions that merely doc the progress of the iteration, etc.)
double CPU_for_global_residual
CPU time for computation of global residual vectors Note: This time is contained in Total_CPU and is only used if convergence is based on the residual of the fully coupled system.
double Tol_achieved
Final tolerance achieved by the iteration.
bool Has_converged
Flag to indicate if the solver has converged.
Detailed Description
Object that collates convergence data of Picard iteration.
Definition at line 39 of file segregated_fsi_solver.h.
Constructor & Destructor Documentation
PicardConvergenceData()
oomph::PicardConvergenceData::PicardConvergenceData () [inline]
Constructor initialises all data.
Definition at line 43 of file segregated_fsi_solver.h.
 PicardConvergenceData()
oomph::PicardConvergenceData::~PicardConvergenceData () [inline]
Empty destructor.
Definition at line 54 of file segregated_fsi_solver.h.
Member Function Documentation
cpu_for_global_residual()
double & oomph::PicardConvergenceData::cpu_for_global_residual () [inline]
CPU time for computation of global residual vectors Note: This time is contained in Total_CPU and is only used if convergence is based on the residual of the fully coupled system.
Definition at line 80 of file segregated_fsi_solver.h.
References CPU_for_global_residual.
Referenced by oomph::SegregatableFSIProblem::segregated_solve().
cpu_total()
double & oomph::PicardConvergenceData::cpu_total () [inline]
Total CPU time for segregated solve.
Definition at line 63 of file segregated_fsi_solver.h.
References CPU_total.
Referenced by oomph::SegregatableFSIProblem::segregated_solve().
essential_cpu_total()
double & oomph::PicardConvergenceData::essential_cpu_total () [inline]
Total essential CPU time for segregated solve (excluding any actions that merely doc the progress of the iteration, etc.)
Definition at line 71 of file segregated_fsi_solver.h.
References Essential_cpu_total.
Referenced by oomph::SegregatableFSIProblem::segregated_solve().
has_converged()
bool oomph::PicardConvergenceData::has_converged () const [inline]
Flag to indicate if the solver has converged.
Definition at line 92 of file segregated_fsi_solver.h.
References Has_converged.
niter()
unsigned & oomph::PicardConvergenceData::niter () [inline]
Number of iterations performed.
Definition at line 57 of file segregated_fsi_solver.h.
References Niter.
Referenced by oomph::SegregatableFSIProblem::segregated_solve().
set_solver_converged()
void oomph::PicardConvergenceData::set_solver_converged () [inline]
Set the flag to indicate that the solver has converged.
Definition at line 98 of file segregated_fsi_solver.h.
References Has_converged.
Referenced by oomph::SegregatableFSIProblem::segregated_solve().
set_solver_not_converged()
void oomph::PicardConvergenceData::set_solver_not_converged () [inline]
Set the flag to indicate that the solver has not converged.
Definition at line 104 of file segregated_fsi_solver.h.
References Has_converged.
tol_achieved()
double & oomph::PicardConvergenceData::tol_achieved () [inline]
Final tolerance achieved by the iteration.
Definition at line 86 of file segregated_fsi_solver.h.
References Tol_achieved.
Referenced by oomph::SegregatableFSIProblem::segregated_solve().
Member Data Documentation
CPU_for_global_residual
double oomph::PicardConvergenceData::CPU_for_global_residual [private]
CPU time for computation of global residual vectors Note: This time is contained in Total_CPU and is only used if convergence is based on the residual of the fully coupled system.
Definition at line 125 of file segregated_fsi_solver.h.
Referenced by cpu_for_global_residual().
CPU_total
double oomph::PicardConvergenceData::CPU_total [private]
Total CPU time for segregated solve.
Definition at line 114 of file segregated_fsi_solver.h.
Referenced by cpu_total().
Essential_cpu_total
double oomph::PicardConvergenceData::Essential_cpu_total [private]
Total essential CPU time for segregated solve (excluding any actions that merely doc the progress of the iteration, etc.)
Definition at line 119 of file segregated_fsi_solver.h.
Referenced by essential_cpu_total().
Has_converged
bool oomph::PicardConvergenceData::Has_converged [private]
Flag to indicate if the solver has converged.
Definition at line 131 of file segregated_fsi_solver.h.
Referenced by has_converged(), set_solver_converged(), and set_solver_not_converged().
Niter
unsigned oomph::PicardConvergenceData::Niter [private]
Number of iterations performed.
Definition at line 111 of file segregated_fsi_solver.h.
Referenced by niter().
Tol_achieved
double oomph::PicardConvergenceData::Tol_achieved [private]
Final tolerance achieved by the iteration.
Definition at line 128 of file segregated_fsi_solver.h.
Referenced by tol_achieved().
The documentation for this class was generated from the following file:
segregated_fsi_solver.h