ConvectionProblem< ELEMENT > Class Template Reference
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
Public Member Functions
ConvectionProblem ()
Constructor.
~ConvectionProblem ()
Destructor. Empty.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_adapt ()
Actions before adapt:(empty)
void actions_before_implicit_timestep ()
Actions before the timestep (update the the time-dependent boundary conditions)
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void doc_solution ()
Doc the solution.
void set_boundary_conditions (const double &time)
Set the boundary conditions.
RectangularQuadMesh< ELEMENT > * mesh_pt ()
Overloaded version of the problem's access function to the mesh. Recasts the pointer to the base Mesh object to the actual mesh type.
ConvectionProblem ()
Constructor.
~ConvectionProblem ()
Destructor. Empty.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem after solve (empty)
void actions_before_adapt ()
Actions before adapt:(empty)
void actions_before_implicit_timestep ()
Actions before the timestep (update the the time-dependent boundary conditions)
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void doc_solution ()
Doc the solution.
void set_boundary_conditions (const double &time)
Set the boundary conditions.
RectangularQuadMesh< NST_ELEMENT > * nst_mesh_pt ()
Access function to the Navier-Stokes mesh.
RectangularQuadMesh< AD_ELEMENT > * adv_diff_mesh_pt ()
Access function to the Advection-Diffusion mesh.
Protected Attributes
RectangularQuadMesh< NST_ELEMENT > * Nst_mesh_pt
Mesh of Navier Stokes elements.
RectangularQuadMesh< AD_ELEMENT > * Adv_diff_mesh_pt
Mesh of advection diffusion elements.
Private Attributes
DocInfo Doc_info
DocInfo object.
Detailed Description
template<class ELEMENT>
class ConvectionProblem< ELEMENT >
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
2D Convection problem on rectangular domain, discretised with refineable elements. The specific type of element is specified via the template parameter.
2D Convection problem on two rectangular domains, discretised with Navier-Stokes and Advection-Diffusion elements. The specific type of elements is specified via the template parameters.
Definition at line 75 of file boussinesq_convection.cc.
Constructor & Destructor Documentation
ConvectionProblem() [1/2]
template<class NST_ELEMENT , class AD_ELEMENT >
ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::ConvectionProblem
Constructor.
Constructor for convection problem.
Definition at line 137 of file boussinesq_convection.cc.
References Global_Physical_Variables::Direction_of_gravity(), Global_Physical_Variables::Inverse_Prandtl, Global_Physical_Variables::Peclet, and Global_Physical_Variables::Rayleigh.
 ConvectionProblem() [1/2]
template<class ELEMENT >
ConvectionProblem< ELEMENT >::~ConvectionProblem () [inline]
Destructor. Empty.
Definition at line 84 of file boussinesq_convection.cc.
ConvectionProblem() [2/2]
template<class ELEMENT >
ConvectionProblem< ELEMENT >::ConvectionProblem ()
Constructor.
 ConvectionProblem() [2/2]
template<class ELEMENT >
ConvectionProblem< ELEMENT >::~ConvectionProblem () [inline]
Destructor. Empty.
Definition at line 84 of file multi_domain_boussinesq_convection.cc.
Member Function Documentation
actions_after_newton_solve() [1/2]
template<class ELEMENT >
void ConvectionProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem after solve (empty)
Definition at line 90 of file boussinesq_convection.cc.
actions_after_newton_solve() [2/2]
template<class ELEMENT >
void ConvectionProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem after solve (empty)
Definition at line 90 of file multi_domain_boussinesq_convection.cc.
actions_before_adapt() [1/2]
template<class ELEMENT >
void ConvectionProblem< ELEMENT >::actions_before_adapt () [inline]
Actions before adapt:(empty)
Definition at line 93 of file boussinesq_convection.cc.
actions_before_adapt() [2/2]
template<class ELEMENT >
void ConvectionProblem< ELEMENT >::actions_before_adapt () [inline]
Actions before adapt:(empty)
Definition at line 93 of file multi_domain_boussinesq_convection.cc.
actions_before_implicit_timestep() [1/2]
template<class ELEMENT >
void ConvectionProblem< ELEMENT >::actions_before_implicit_timestep () [inline]
Actions before the timestep (update the the time-dependent boundary conditions)
Definition at line 97 of file boussinesq_convection.cc.
actions_before_implicit_timestep() [2/2]
template<class ELEMENT >
void ConvectionProblem< ELEMENT >::actions_before_implicit_timestep () [inline]
Actions before the timestep (update the the time-dependent boundary conditions)
Definition at line 97 of file multi_domain_boussinesq_convection.cc.
actions_before_newton_solve() [1/2]
template<class ELEMENT >
void ConvectionProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve (empty)
Definition at line 87 of file boussinesq_convection.cc.
actions_before_newton_solve() [2/2]
template<class ELEMENT >
void ConvectionProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve (empty)
Definition at line 87 of file multi_domain_boussinesq_convection.cc.
adv_diff_mesh_pt()
template<class ELEMENT >
RectangularQuadMesh<AD_ELEMENT>* ConvectionProblem< ELEMENT >::adv_diff_mesh_pt () [inline]
Access function to the Advection-Diffusion mesh.
Definition at line 124 of file multi_domain_boussinesq_convection.cc.
doc_solution() [1/2]
template<class NST_ELEMENT , class AD_ELEMENT >
void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::doc_solution
Doc the solution.
Definition at line 290 of file boussinesq_convection.cc.
Referenced by main().
doc_solution() [2/2]
template<class ELEMENT >
void ConvectionProblem< ELEMENT >::doc_solution ()
Doc the solution.
fix_pressure() [1/2]
template<class ELEMENT >
void ConvectionProblem< ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) [inline]
Fix pressure in element e at pressure dof pdof and set to pvalue.
Definition at line 103 of file boussinesq_convection.cc.
fix_pressure() [2/2]
template<class ELEMENT >
void ConvectionProblem< ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) [inline]
Fix pressure in element e at pressure dof pdof and set to pvalue.
Definition at line 103 of file multi_domain_boussinesq_convection.cc.
mesh_pt()
template<class ELEMENT >
RectangularQuadMesh<ELEMENT>* ConvectionProblem< ELEMENT >::mesh_pt () [inline]
Overloaded version of the problem's access function to the mesh. Recasts the pointer to the base Mesh object to the actual mesh type.
Definition at line 120 of file boussinesq_convection.cc.
nst_mesh_pt()
template<class ELEMENT >
RectangularQuadMesh<NST_ELEMENT>* ConvectionProblem< ELEMENT >::nst_mesh_pt () [inline]
Access function to the Navier-Stokes mesh.
Definition at line 118 of file multi_domain_boussinesq_convection.cc.
set_boundary_conditions() [1/2]
template<class NST_ELEMENT , class AD_ELEMENT >
void ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::set_boundary_conditions (const double & time)
Set the boundary conditions.
Set the boundary conditions as a function of continuous time.
Definition at line 237 of file boussinesq_convection.cc.
Referenced by main().
set_boundary_conditions() [2/2]
template<class ELEMENT >
void ConvectionProblem< ELEMENT >::set_boundary_conditions (const double & time)
Set the boundary conditions.
Member Data Documentation
Adv_diff_mesh_pt
template<class ELEMENT >
RectangularQuadMesh<AD_ELEMENT>* ConvectionProblem< ELEMENT >::Adv_diff_mesh_pt [protected]
Mesh of advection diffusion elements.
Definition at line 140 of file multi_domain_boussinesq_convection.cc.
Doc_info
template<class ELEMENT >
DocInfo ConvectionProblem< ELEMENT >::Doc_info [private]
DocInfo object.
Definition at line 129 of file boussinesq_convection.cc.
Nst_mesh_pt
template<class ELEMENT >
RectangularQuadMesh<NST_ELEMENT>* ConvectionProblem< ELEMENT >::Nst_mesh_pt [protected]
Mesh of Navier Stokes elements.
Definition at line 137 of file multi_domain_boussinesq_convection.cc.
The documentation for this class was generated from the following files:
boussinesq_convection.cc
multi_domain_boussinesq_convection.cc