#!MC 1000

$!EXPORTSETUP
  EXPORTFORMAT = AVI
  USESUPERSAMPLEANTIALIASING = NO
  EXPORTFNAME = "anim.avi"
$!EXPORTSETUP IMAGEWIDTH = 829

$!FRAMELAYOUT SHOWHEADER = NO
$!FRAMELAYOUT SHOWBORDER = NO
$!FRAMECONTROL FITALLTOPAPER

$!EXPORTSTART
$!PROMPTFORTEXTSTRING |NFILES|
  INSTRUCTIONS = "Enter the number of timesteps"

$!LOOP |NFILES|
$!READDATASET "RESLT/soln|LOOP|.dat"
$!FIELDLAYERS SHOWMESH = YES
$!FIELDLAYERS SHOWBOUNDARY = YES
$!FIELDLAYERS SHOWSHADE = YES
$!FIELDLAYERS SHOWCONTOUR = NO

$!FRAMELAYOUT SHOWHEADER = NO
$!FRAMELAYOUT SHOWBORDER = NO
$!FRAMECONTROL FITALLTOPAPER

####################################################
# SCALING FACTOR FOR VELOCITY
####################################################
$!VARSET |VELOC_FACTOR|=0.5

####################################################
# NUMBER OF SLICES
####################################################
$!VARSET |NSLICE|=6

$!LOOP |NSLICE|

$!VARSET |ZSLICE|=|LOOP|
$!VARSET |ZSLICE|-=0.99


$!GLOBALTHREED 
  SLICE
  {
    ORIGIN{Z =|ZSLICE| }
    NORMAL
    {
      X=0
      Y=0
      Z=1
    }
  }
$!CREATESLICEZONEFROMPLANE 
  SLICESOURCE = VOLUMEZONES
  FORCEEXTRACTIONTOSINGLEZONE = YES

$!ENDLOOP




$!VARSET |ZONEMAX| = (|NUMZONES|-|NSLICE|)
$!ACTIVEFIELDZONES-=[1-|ZONEMAX|]
$!VARSET |ZONEMAX|+=1
$!ACTIVEFIELDZONES+=[|ZONEMAX|-|NUMZONES|]
$!ALTERDATA 
  EQUATION = 'V6=V3+|VELOC_FACTOR|*V6' 
$!FIELD 
  SHADE
  {
    SHOW = YES
  }
$!FIELD
  MESH
  {
    SHOW = NO    
    COLOR = BLACK
  }
$!FIELD
  BOUNDARY
  {
    SHOW = YES
    COLOR = BLACK
  }
$!THREEDAXIS
  ZDETAIL
  {
    VARNUM = 6
  }


$!THREEDVIEW VIEWERPOSITION{X = 16.457195465}
$!THREEDVIEW VIEWERPOSITION{Y = 21.3462401861}
$!THREEDVIEW VIEWERPOSITION{Z = 16.805042511}
$!THREEDVIEW PSIANGLE = 62
$!THREEDVIEW VIEWERPOSITION{X = 16.4815564968}
$!THREEDVIEW VIEWERPOSITION{Y = 21.3275699242}
$!THREEDVIEW THETAANGLE = -142.5
$!THREEDVIEW ALPHAANGLE = -109.1


$!FIELD [1-|NUMZONES|]  BOUNDARY{LINETHICKNESS = 0.1}
$!THREEDAXIS FRAMEAXIS{XYPOS{X = 83.999724254}}
$!THREEDAXIS FRAMEAXIS{XYPOS{Y = 72.014117553}}

$!VIEW FIT
$!REDRAW
$!EXPORTNEXTFRAME
$!ENDLOOP
$!EXPORTFINISH

