GeomObjectAsGeneralisedElementProblem Class Reference
Problem to demonstrate the use of a GeomObject as a GeneralisedElement: A geometric object (a Circle) is "upgraded" to a GeneralisedElement. The position of the Circle is determined by a balance of forces, assuming that the Circle is mounted on an elastic spring of specified stiffness and loaded by a vertical "load".
Public Member Functions
GeomObjectAsGeneralisedElementProblem ()
Constructor.
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void doc_solution ()
Doc the solution.
double & load ()
Return value of the "load" on the elastically supported ring.
DocInfo & doc_info ()
Access to DocInfo object.
Private Attributes
ofstream Trace_file
Trace file.
Data * Load_pt
Pointer to data item that stores the "load" on the ring.
DocInfo Doc_info
Doc info object.
Detailed Description
Problem to demonstrate the use of a GeomObject as a GeneralisedElement: A geometric object (a Circle) is "upgraded" to a GeneralisedElement. The position of the Circle is determined by a balance of forces, assuming that the Circle is mounted on an elastic spring of specified stiffness and loaded by a vertical "load".
Definition at line 52 of file geom_object_element.cc.
Constructor & Destructor Documentation
GeomObjectAsGeneralisedElementProblem()
GeomObjectAsGeneralisedElementProblem::GeomObjectAsGeneralisedElementProblem ()
Constructor.
Definition at line 98 of file geom_object_element.cc.
References demo_fish_poisson(), Doc_info, Load_pt, and Trace_file.
Member Function Documentation
actions_after_newton_solve()
void GeomObjectAsGeneralisedElementProblem::actions_after_newton_solve () [inline]
Update the problem specs after solve (empty)
Definition at line 61 of file geom_object_element.cc.
actions_before_newton_solve()
void GeomObjectAsGeneralisedElementProblem::actions_before_newton_solve () [inline]
Update the problem specs before solve (empty)
Definition at line 64 of file geom_object_element.cc.
doc_info()
DocInfo & GeomObjectAsGeneralisedElementProblem::doc_info () [inline]
Access to DocInfo object.
Definition at line 76 of file geom_object_element.cc.
References Doc_info.
doc_solution()
void GeomObjectAsGeneralisedElementProblem::doc_solution ()
Doc the solution.
Doc the solution in tecplot format.
Definition at line 151 of file geom_object_element.cc.
References demo_fish_poisson(), Doc_info, load(), and Trace_file.
load()
double & GeomObjectAsGeneralisedElementProblem::load () [inline]
Return value of the "load" on the elastically supported ring.
Definition at line 70 of file geom_object_element.cc.
References Load_pt.
Referenced by doc_solution(), and main().
Member Data Documentation
Doc_info
DocInfo GeomObjectAsGeneralisedElementProblem::Doc_info [private]
Doc info object.
Definition at line 87 of file geom_object_element.cc.
Referenced by doc_info(), doc_solution(), and GeomObjectAsGeneralisedElementProblem().
Load_pt
Data* GeomObjectAsGeneralisedElementProblem::Load_pt [private]
Pointer to data item that stores the "load" on the ring.
Definition at line 84 of file geom_object_element.cc.
Referenced by GeomObjectAsGeneralisedElementProblem(), and load().
Trace_file
ofstream GeomObjectAsGeneralisedElementProblem::Trace_file [private]
Trace file.
Definition at line 81 of file geom_object_element.cc.
Referenced by doc_solution(), and GeomObjectAsGeneralisedElementProblem().
The documentation for this class was generated from the following file:
geom_object_element.cc