FreeBoundaryPoissonProblem< ELEMENT > Class Template Reference
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Public Member Functions
FreeBoundaryPoissonProblem ()
Constructor.
virtual ~FreeBoundaryPoissonProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
MyMacroElementNodeUpdateRefineableFishMesh< ELEMENT > * fish_mesh_pt ()
Access function for the fish mesh.
void doc_solution ()
Doc the solution.
void actions_before_newton_convergence_check ()
Before checking the new residuals in Newton's method we have to update nodal positions in response to possible changes in the position of the domain boundary.
FreeBoundaryPoissonProblem ()
Constructor.
virtual ~FreeBoundaryPoissonProblem ()
Destructor (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
MyMacroElementNodeUpdateFishMesh< ELEMENT > * fish_mesh_pt ()
Access function for the fish mesh.
void doc_solution ()
Doc the solution.
void actions_before_newton_convergence_check ()
Before checking the new residuals in Newton's method we have to update nodal positions in response to possible changes in the position of the domain boundary.
Private Attributes
MyMacroElementNodeUpdateRefineableFishMesh< ELEMENT > * Fish_mesh_pt
Pointer to fish mesh.
Mesh * Fish_back_mesh_pt
Pointer to single-element mesh that stores the GeneralisedElement that represents the fish's back.
MyMacroElementNodeUpdateFishMesh< ELEMENT > * Fish_mesh_pt
Pointer to fish mesh.
Detailed Description
template<class ELEMENT>
class FreeBoundaryPoissonProblem< ELEMENT >
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Refineable `free-boundary` Poisson problem in deformable fish-shaped domain. Template parameter identifies the element.
Non-refineable `free-boundary` Poisson problem in deformable fish-shaped domain. Template parameter identifies the element.
Definition at line 146 of file macro_element_free_boundary_poisson.cc.
Constructor & Destructor Documentation
FreeBoundaryPoissonProblem() [1/2]
template<class ELEMENT >
FreeBoundaryPoissonProblem< ELEMENT >::FreeBoundaryPoissonProblem
Constructor.
Constructor for adaptive free-boundary Poisson problem in deformable fish-shaped domain. Loop over elements and set pointers to source function
Definition at line 199 of file macro_element_free_boundary_poisson.cc.
References ConstSourceForPoisson::get_source().
 FreeBoundaryPoissonProblem() [1/2]
template<class ELEMENT >
virtual FreeBoundaryPoissonProblem< ELEMENT >::~FreeBoundaryPoissonProblem () [inline], [virtual]
Destructor (empty)
Definition at line 155 of file macro_element_free_boundary_poisson.cc.
FreeBoundaryPoissonProblem() [2/2]
template<class ELEMENT >
FreeBoundaryPoissonProblem< ELEMENT >::FreeBoundaryPoissonProblem ()
Constructor.
 FreeBoundaryPoissonProblem() [2/2]
template<class ELEMENT >
virtual FreeBoundaryPoissonProblem< ELEMENT >::~FreeBoundaryPoissonProblem () [inline], [virtual]
Destructor (empty)
Definition at line 151 of file macro_element_free_boundary_poisson_non_ref.cc.
Member Function Documentation
actions_after_newton_solve() [1/2]
template<class ELEMENT >
void FreeBoundaryPoissonProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem specs after solve (empty)
Definition at line 161 of file macro_element_free_boundary_poisson.cc.
actions_after_newton_solve() [2/2]
template<class ELEMENT >
void FreeBoundaryPoissonProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem specs after solve (empty)
Definition at line 157 of file macro_element_free_boundary_poisson_non_ref.cc.
actions_before_newton_convergence_check() [1/2]
template<class ELEMENT >
void FreeBoundaryPoissonProblem< ELEMENT >::actions_before_newton_convergence_check () [inline]
Before checking the new residuals in Newton's method we have to update nodal positions in response to possible changes in the position of the domain boundary.
Definition at line 175 of file macro_element_free_boundary_poisson.cc.
References FreeBoundaryPoissonProblem< ELEMENT >::fish_mesh_pt().
actions_before_newton_convergence_check() [2/2]
template<class ELEMENT >
void FreeBoundaryPoissonProblem< ELEMENT >::actions_before_newton_convergence_check () [inline]
Before checking the new residuals in Newton's method we have to update nodal positions in response to possible changes in the position of the domain boundary.
Definition at line 171 of file macro_element_free_boundary_poisson_non_ref.cc.
References FreeBoundaryPoissonProblem< ELEMENT >::fish_mesh_pt().
actions_before_newton_solve() [1/2]
template<class ELEMENT >
void FreeBoundaryPoissonProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve (empty)
Definition at line 158 of file macro_element_free_boundary_poisson.cc.
actions_before_newton_solve() [2/2]
template<class ELEMENT >
void FreeBoundaryPoissonProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve (empty)
Definition at line 154 of file macro_element_free_boundary_poisson_non_ref.cc.
doc_solution() [1/2]
template<class ELEMENT >
void FreeBoundaryPoissonProblem< ELEMENT >::doc_solution
Doc the solution.
Doc the solution in tecplot format.
Definition at line 288 of file macro_element_free_boundary_poisson.cc.
Referenced by main().
doc_solution() [2/2]
template<class ELEMENT >
void FreeBoundaryPoissonProblem< ELEMENT >::doc_solution ()
Doc the solution.
fish_mesh_pt() [1/2]
template<class ELEMENT >
MyMacroElementNodeUpdateRefineableFishMesh< ELEMENT > * FreeBoundaryPoissonProblem< ELEMENT >::fish_mesh_pt () [inline]
Access function for the fish mesh.
Definition at line 164 of file macro_element_free_boundary_poisson.cc.
References FreeBoundaryPoissonProblem< ELEMENT >::Fish_mesh_pt.
Referenced by FreeBoundaryPoissonProblem< ELEMENT >::actions_before_newton_convergence_check().
fish_mesh_pt() [2/2]
template<class ELEMENT >
MyMacroElementNodeUpdateFishMesh< ELEMENT > * FreeBoundaryPoissonProblem< ELEMENT >::fish_mesh_pt () [inline]
Access function for the fish mesh.
Definition at line 160 of file macro_element_free_boundary_poisson_non_ref.cc.
References FreeBoundaryPoissonProblem< ELEMENT >::Fish_mesh_pt.
Member Data Documentation
Fish_back_mesh_pt
template<class ELEMENT >
Mesh * FreeBoundaryPoissonProblem< ELEMENT >::Fish_back_mesh_pt [private]
Pointer to single-element mesh that stores the GeneralisedElement that represents the fish's back.
Definition at line 187 of file macro_element_free_boundary_poisson.cc.
Fish_mesh_pt [1/2]
template<class ELEMENT >
MyMacroElementNodeUpdateRefineableFishMesh<ELEMENT>* FreeBoundaryPoissonProblem< ELEMENT >::Fish_mesh_pt [private]
Pointer to fish mesh.
Definition at line 183 of file macro_element_free_boundary_poisson.cc.
Referenced by FreeBoundaryPoissonProblem< ELEMENT >::fish_mesh_pt().
Fish_mesh_pt [2/2]
template<class ELEMENT >
MyMacroElementNodeUpdateFishMesh<ELEMENT>* FreeBoundaryPoissonProblem< ELEMENT >::Fish_mesh_pt [private]
Pointer to fish mesh.
Definition at line 179 of file macro_element_free_boundary_poisson_non_ref.cc.
The documentation for this class was generated from the following files:
macro_element_free_boundary_poisson.cc
macro_element_free_boundary_poisson_non_ref.cc