old_for_doc.cc File Reference
Classes
class RefineableFishPoissonProblem< ELEMENT >
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Namespaces
 ConstSourceForPoisson
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Functions
void ConstSourceForPoisson::get_source (const Vector< double > &x, double &source)
Const source function.
template<class ELEMENT >
void demo_fish_poisson (const string &directory_name)
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
template<class ELEMENT >
void demo_elastic_fish_poisson (const string &directory_name)
Demonstrate how to solve coupled `elastic` 2D Poisson problem in deformable fish-shaped domain with mesh adaptation.
int main (int argc, char *argv[])
Driver for `elastic` fish poisson solver with adaptation. If there are any command line arguments, we regard this as a validation run and reduce the targets for the mesh adaptation.
Function Documentation
demo_elastic_fish_poisson()
template<class ELEMENT >
void demo_elastic_fish_poisson (const string & directory_name)
Demonstrate how to solve coupled `elastic` 2D Poisson problem in deformable fish-shaped domain with mesh adaptation.
Definition at line 446 of file old_for_doc.cc.
References RefineableFishPoissonProblem< ELEMENT >::doc_solution(), RefineableFishPoissonProblem< ELEMENT >::fish_mesh_pt(), and RefineableFishPoissonProblem< ELEMENT >::load().
demo_fish_poisson()
template<class ELEMENT >
void demo_fish_poisson (const string & directory_name)
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Demonstrate how to solve 2D Poisson problem in deformable fish-shaped domain with mesh adaptation.
Definition at line 383 of file old_for_doc.cc.
References RefineableFishPoissonProblem< ELEMENT >::doc_info(), RefineableFishPoissonProblem< ELEMENT >::doc_solution(), RefineableFishPoissonProblem< ELEMENT >::fish_mesh_pt(), and RefineableFishPoissonProblem< ELEMENT >::y_c().
main()
int main (int argc, char * argv[])
Driver for `elastic` fish poisson solver with adaptation. If there are any command line arguments, we regard this as a validation run and reduce the targets for the mesh adaptation.
Definition at line 485 of file old_for_doc.cc.