airy_cantilever.txt File Reference
Functions
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E *f and Poisson s ratio f nu f Here is a e g H Eschenauer &W Schnell Elastizitaetstheorie BI< HR >< HR > section results Results The following figure shows an animation of beam s deformation in response to an increase in the uniform f P at zero f f and the approximate analytical solution (in red). @I w 0.75\textwidth stress_comparison `Comparison of the computed distribution of the horizontal' stress (in green) against the approximate analytical solution (in red). ` The agreement between the two solutions is excellent over most of the domain
< HR >< HR > section constructor The problem constructor The constructor builds the bulk mesh (the standard \c RefineableRectangularQuadMesh that we already used in many previous examples, upgraded to a \c SolidMesh, via the procedure discussed in the document< A HREF=`../../solid_theory/html/index.html#solid_mesh`> Solid mechanics:Theory and implementation</A >)
We employ the c Z2ErrorEstimator to assess the accuracy of the computed solution and to control the adaptive mesh refinement When used with the c the c Z2ErrorEstimator uses the components of Green s strain tensor as fluxes in its flux recovery procedure skipline Set error until Z2 we pass the constitutive equations and the gravitational body force to the select a control and perform one uniform mesh refinement until refine_uniformly ()
We pin the position of all nodes on the left boundary(boundary 3) of the bulk mesh. The subsequent call to \c PVDEquationsBase< 2 > Next we output the approximate St Venant solution at the same plot points and write the load displacement characteristics to the trace file until end doc< HR >< HR > section exercises Comments and exercises subsection ex Exercises gravity rather than a pressure load Consult the document< A HREF=`../../solid_theory/html/index.html`> Solid the macroscopic deformation due to a gravitational load is identical to that induced by an equivalent pressure equivalent meaning that the total force on the beam is the same for both cases n n and c RefineableQPVDElementWithContinuousPressure< 2 > and compare the results Both of these two elements are based on a pressure displacement the former employing a discontinuous pressure representation (as in Crouzeix-Raviart Navier-Stokes elements)
We pin the position of all nodes on the left boundary(boundary 3) of the bulk mesh. The subsequent call to \c PVDEquationsBase< 2 > Next we output the approximate St Venant solution at the same plot points and write the load displacement characteristics to the trace file until end doc< HR >< HR > section exercises Comments and exercises subsection ex Exercises gravity rather than a pressure load Consult the document< A HREF=`../../solid_theory/html/index.html`> Solid the macroscopic deformation due to a gravitational load is identical to that induced by an equivalent pressure equivalent meaning that the total force on the beam is the same for both cases n n and c RefineableQPVDElementWithContinuousPressure< 2 > and compare the results Both of these two elements are based on a pressure displacement the former employing a discontinuous pressure the latter employing a continuous pressure representation(as in Taylor-Hood elements). Confirm that calls to \c PVDEquationsBase< 2 >[\b Note:Since this element is only defined and used in a 2D drivercode, there is little point in implementing the output for 1D or 3D elements. However, paranoid as we are, we check thedimension of the element and throw an error if it is wrong.] Finally we declare that the c FaceGeometry of the wrapped element is the same as that of the underlying element This step is required to allow the automatic construction of c SolidTractionElements in c create_traction_elements (). \dontinclude airy_cantilever.cc \skipline start_face_geometry \until }
Variables
mainpage Demo problem
mainpage Demo the bending of a cantilever beam
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E *f and Poisson s ratio f nu f Here is a sketch
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E *f and Poisson s ratio f nu f Here is a e g H Eschenauer &W Schnell Elastizitaetstheorie I
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E *f and Poisson s ratio f nu f Here is a e g H Eschenauer &W Schnell Elastizitaetstheorie BI Wissenschaftsverlag
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E *f and Poisson s ratio f nu f Here is a e g H Eschenauer &W Schnell Elastizitaetstheorie BI edition
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E *f and Poisson s ratio f nu f Here is a e g H Eschenauer &W Schnell Elastizitaetstheorie BI< HR >< HR > section results Results The following figure shows an animation of beam s deformation in response to an increase in the uniform pressure
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E *f and Poisson s ratio f nu f Here is a e g H Eschenauer &W Schnell Elastizitaetstheorie BI< HR >< HR > section results Results The following figure shows an animation of beam s deformation in response to an increase in the uniform f P f
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E *f and Poisson s ratio f nu f Here is a e g H Eschenauer &W Schnell Elastizitaetstheorie BI< HR >< HR > section results Results The following figure shows an animation of beam s deformation in response to an increase in the uniform f P at zero gravity
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E *f and Poisson s ratio f nu f Here is a e g H Eschenauer &W Schnell Elastizitaetstheorie BI< HR >< HR > section results Results The following figure shows an animation of beam s deformation in response to an increase in the uniform f P at zero f g
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E *f and Poisson s ratio f nu f Here is a e g H Eschenauer &W Schnell Elastizitaetstheorie BI< HR >< HR > section results Results The following figure shows an animation of beam s deformation in response to an increase in the uniform f P at zero f f sigma_
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E *f and Poisson s ratio f nu f Here is a e g H Eschenauer &W Schnell Elastizitaetstheorie BI< HR >< HR > section results Results The following figure shows an animation of beam s deformation in response to an increase in the uniform f P at zero f f and the approximate analytical apart from two small regions near the left end of the beam where stress singularities develop at the vertices of the domain The singularities arise because the zero tangential stress boundary condition on the top and bottom faces is inconsistent with the zero displacement boundary condition on the left face The singularities are not captured by the approximate analytical solution c oomph lib s automatic mesh adaptation refines the mesh in an attempt to capture the rapid variations of the stresses in these regions< HR >< HR > section global Global parameters and functions As usual
We employ the c Z2ErrorEstimator to assess the accuracy of the computed solution and to control the adaptive mesh refinement When used with the c RefineableQPVDElements
We employ the c Z2ErrorEstimator to assess the accuracy of the computed solution and to control the adaptive mesh refinement When used with the c the c Z2ErrorEstimator uses the components of Green s strain tensor as fluxes in its flux recovery procedure skipline Set error until Z2 Next
We employ the c Z2ErrorEstimator to assess the accuracy of the computed solution and to control the adaptive mesh refinement When used with the c the c Z2ErrorEstimator uses the components of Green s strain tensor as fluxes in its flux recovery procedure skipline Set error until Z2 we pass the constitutive equations and the gravitational body force to the elements
We employ the c Z2ErrorEstimator to assess the accuracy of the computed solution and to control the adaptive mesh refinement When used with the c the c Z2ErrorEstimator uses the components of Green s strain tensor as fluxes in its flux recovery procedure skipline Set error until Z2 we pass the constitutive equations and the gravitational body force to the select a control node
We pin the position of all nodes on the left boundary(boundary 3) of the bulk mesh. The subsequent call to \c PVDEquationsBase< 2 > Next we output the approximate St Venant solution at the same plot points and write the load displacement characteristics to the trace file until end doc< HR >< HR > section exercises Comments and exercises subsection ex Exercises gravity rather than a pressure load Consult the document< A HREF=`../../solid_theory/html/index.html`> Solid mechanics
We pin the position of all nodes on the left boundary(boundary 3) of the bulk mesh. The subsequent call to \c PVDEquationsBase< 2 > Next we output the approximate St Venant solution at the same plot points and write the load displacement characteristics to the trace file until end doc< HR >< HR > section exercises Comments and exercises subsection ex Exercises gravity rather than a pressure load Consult the document< A HREF=`../../solid_theory/html/index.html`> Solid the macroscopic deformation due to a gravitational load is identical to that induced by an equivalent pressure load
We pin the position of all nodes on the left boundary(boundary 3) of the bulk mesh. The subsequent call to \c PVDEquationsBase< 2 > Next we output the approximate St Venant solution at the same plot points and write the load displacement characteristics to the trace file until end doc< HR >< HR > section exercises Comments and exercises subsection ex Exercises gravity rather than a pressure load Consult the document< A HREF=`../../solid_theory/html/index.html`> Solid the macroscopic deformation due to a gravitational load is identical to that induced by an equivalent pressure equivalent meaning that the total force on the beam is the same for both cases n n and c RefineableQPVDElementWithContinuousPressure< 2 > and compare the results Both of these two elements are based on a pressure displacement formulation
Function Documentation
create_traction_elements()
We pin the position of all nodes on the left boundary (boundary 3) of the bulk mesh. The subsequent call to \c PVDEquationsBase<2> Next we output the approximate St Venant solution at the same plot points and write the load displacement characteristics to the trace file until end doc<HR><HR> section exercises Comments and exercises subsection ex Exercises gravity rather than a pressure load Consult the document<A HREF=`../../solid_theory/html/index.html`> Solid the macroscopic deformation due to a gravitational load is identical to that induced by an equivalent pressure equivalent meaning that the total force on the beam is the same for both cases n n and c RefineableQPVDElementWithContinuousPressure<2> and compare the results Both of these two elements are based on a pressure displacement the former employing a discontinuous pressure the latter employing a continuous pressure representation (as in Taylor-Hood elements). Confirm that calls to \c PVDEquationsBase<2>[\b Note: Since this element is only defined and used in a 2D drivercode, there is little point in implementing the output for 1D or 3D elements. However, paranoid as we are, we check thedimension of the element and throw an error if it is wrong.] Finally we declare that the c FaceGeometry of the wrapped element is the same as that of the underlying element This step is required to allow the automatic construction of c SolidTractionElements in c create_traction_elements ()
Referenced by CantileverProblem< ELEMENT >::actions_after_adapt(), and CantileverProblem< ELEMENT >::CantileverProblem().
mesh()
<HR><HR> section constructor The problem constructor The constructor builds the bulk mesh (the standard \c RefineableRectangularQuadMesh that we already used in many previous examples, upgraded to a \c SolidMesh, via the procedure discussed in the document< A HREF=`../../solid_theory/html/index.html#solid_mesh`> Solid mechanics:Theory and implementation</A >)
refine_uniformly()
We employ the c Z2ErrorEstimator to assess the accuracy of the computed solution and to control the adaptive mesh refinement When used with the c the c Z2ErrorEstimator uses the components of Green s strain tensor as fluxes in its flux recovery procedure skipline Set error until Z2 we pass the constitutive equations and the gravitational body force to the select a control and perform one uniform mesh refinement until refine_uniformly ()
Referenced by CantileverProblem< ELEMENT >::CantileverProblem().
representation()
We pin the position of all nodes on the left boundary (boundary 3) of the bulk mesh. The subsequent call to \c PVDEquationsBase<2> Next we output the approximate St Venant solution at the same plot points and write the load displacement characteristics to the trace file until end doc<HR><HR> section exercises Comments and exercises subsection ex Exercises gravity rather than a pressure load Consult the document<A HREF=`../../solid_theory/html/index.html`> Solid the macroscopic deformation due to a gravitational load is identical to that induced by an equivalent pressure equivalent meaning that the total force on the beam is the same for both cases n n and c RefineableQPVDElementWithContinuousPressure<2> and compare the results Both of these two elements are based on a pressure displacement the former employing a discontinuous pressure representation (as in Crouzeix-Raviart Navier-Stokes elements)
solution()
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E* f and Poisson s ratio f nu f Here is a e g H Eschenauer& W Schnell Elastizitaetstheorie BI<HR><HR> section results Results The following figure shows an animation of beam s deformation in response to an increase in the uniform f P at zero f f and the approximate analytical solution (in red)
Variable Documentation
beam
mainpage Demo the bending of a cantilever beam
Definition at line 4 of file airy_cantilever.txt.
edition
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E* f and Poisson s ratio f nu f Here is a e g H Eschenauer& W Schnell Elastizitaetstheorie BI edition
Definition at line 16 of file airy_cantilever.txt.
elements
We employ the c Z2ErrorEstimator to assess the accuracy of the computed solution and to control the adaptive mesh refinement When used with the c the c Z2ErrorEstimator uses the components of Green s strain tensor as fluxes in its flux recovery procedure skipline Set error until Z2 we pass the constitutive equations and the gravitational body force to the elements
Definition at line 178 of file airy_cantilever.txt.
f
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E* f and Poisson s ratio f nu f Here is a e g H Eschenauer& W Schnell Elastizitaetstheorie BI<HR><HR> section results Results The following figure shows an animation of beam s deformation in response to an increase in the uniform f P f
Definition at line 26 of file airy_cantilever.txt.
formulation
We pin the position of all nodes on the left boundary (boundary 3) of the bulk mesh. The subsequent call to \c PVDEquationsBase<2> Next we output the approximate St Venant solution at the same plot points and write the load displacement characteristics to the trace file until end doc<HR><HR> section exercises Comments and exercises subsection ex Exercises gravity rather than a pressure load Consult the document<A HREF=`../../solid_theory/html/index.html`> Solid the macroscopic deformation due to a gravitational load is identical to that induced by an equivalent pressure equivalent meaning that the total force on the beam is the same for both cases n n and c RefineableQPVDElementWithContinuousPressure<2> and compare the results Both of these two elements are based on a pressure displacement formulation
Definition at line 325 of file airy_cantilever.txt.
g
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E* f and Poisson s ratio f nu f Here is a e g H Eschenauer& W Schnell Elastizitaetstheorie BI<HR><HR> section results Results The following figure shows an animation of beam s deformation in response to an increase in the uniform f P at zero f g
Initial value:
=0 \f$. The colour contours represent the magnitude of
the "horizontal" component of the 2nd Piola-Kirchhoff stress tensor
Definition at line 27 of file airy_cantilever.txt.
gravity
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E* f and Poisson s ratio f nu f Here is a e g H Eschenauer& W Schnell Elastizitaetstheorie BI<HR><HR> section results Results The following figure shows an animation of beam s deformation in response to an increase in the uniform f P at zero gravity
Definition at line 27 of file airy_cantilever.txt.
I
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E* f and Poisson s ratio f nu f Here is a e g H Eschenauer& W Schnell Elastizitaetstheorie I
Definition at line 15 of file airy_cantilever.txt.
load
We pin the position of all nodes on the left boundary (boundary 3) of the bulk mesh. The subsequent call to \c PVDEquationsBase<2> Next we output the approximate St Venant solution at the same plot points and write the load displacement characteristics to the trace file until end doc<HR><HR> section exercises Comments and exercises subsection ex Exercises gravity rather than a pressure load Consult the document<A HREF=`../../solid_theory/html/index.html`> Solid the macroscopic deformation due to a gravitational load is identical to that induced by an equivalent pressure load
Definition at line 319 of file airy_cantilever.txt.
mechanics
We pin the position of all nodes on the left boundary (boundary 3) of the bulk mesh. The subsequent call to \c PVDEquationsBase<2> Next we output the approximate St Venant solution at the same plot points and write the load displacement characteristics to the trace file until end doc<HR><HR> section exercises Comments and exercises subsection ex Exercises gravity rather than a pressure load Consult the document<A HREF=`../../solid_theory/html/index.html`> Solid mechanics
Definition at line 190 of file airy_cantilever.txt.
Next
We employ the c Z2ErrorEstimator to assess the accuracy of the computed solution and to control the adaptive mesh refinement When used with the c the c Z2ErrorEstimator uses the components of Green s strain tensor as fluxes in its flux recovery procedure skipline Set error until Z2 Next
Definition at line 177 of file airy_cantilever.txt.
node
We employ the c Z2ErrorEstimator to assess the accuracy of the computed solution and to control the adaptive mesh refinement When used with the c the c Z2ErrorEstimator uses the components of Green s strain tensor as fluxes in its flux recovery procedure skipline Set error until Z2 we pass the constitutive equations and the gravitational body force to the select a control node
Definition at line 178 of file airy_cantilever.txt.
pressure
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E* f and Poisson s ratio f nu f Here is a e g H Eschenauer& W Schnell Elastizitaetstheorie BI<HR><HR> section results Results The following figure shows an animation of beam s deformation in response to an increase in the uniform pressure
Definition at line 26 of file airy_cantilever.txt.
problem
mainpage Demo problem
Definition at line 3 of file airy_cantilever.txt.
Referenced by main().
RefineableQPVDElements
We employ the c Z2ErrorEstimator to assess the accuracy of the computed solution and to control the adaptive mesh refinement When used with the c RefineableQPVDElements
Definition at line 170 of file airy_cantilever.txt.
sigma_
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E* f and Poisson s ratio f nu f Here is a e g H Eschenauer& W Schnell Elastizitaetstheorie BI<HR><HR> section results Results The following figure shows an animation of beam s deformation in response to an increase in the uniform f P at zero f f sigma_
Initial value:
{11} \f$ . Its approximately linear variation across the beam's
thickness indicates a bending-type stress distribution with the
stress being positive (tensile) at the top and negative
(compressive) at the bottom.
@I w 0.75\textwidth beam_animation "Animation of the beam's deformation with contours of its `horizontal' stress component. "
The next figure shows a comparison of the computational predictions for
\f$ \sigma_{11} \f$ (in green)
Definition at line 29 of file airy_cantilever.txt.
sketch
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E* f and Poisson s ratio f nu f Here is a sketch
Definition at line 14 of file airy_cantilever.txt.
usual
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E* f and Poisson s ratio f nu f Here is a e g H Eschenauer& W Schnell Elastizitaetstheorie BI<HR><HR> section results Results The following figure shows an animation of beam s deformation in response to an increase in the uniform f P at zero f f and the approximate analytical apart from two small regions near the left end of the beam where stress singularities develop at the vertices of the domain The singularities arise because the zero tangential stress boundary condition on the top and bottom faces is inconsistent with the zero displacement boundary condition on the left face The singularities are not captured by the approximate analytical solution c oomph lib s automatic mesh adaptation refines the mesh in an attempt to capture the rapid variations of the stresses in these regions<HR><HR> section global Global parameters and functions As usual
Definition at line 59 of file airy_cantilever.txt.
Wissenschaftsverlag
mainpage Demo the bending of a cantilever subject to a pressure loading on its upper face and or gravity We assume that the material behaves like a generalised Hookean solid with elastic modulus f E* f and Poisson s ratio f nu f Here is a e g H Eschenauer& W Schnell Elastizitaetstheorie BI Wissenschaftsverlag
Definition at line 16 of file airy_cantilever.txt.