boussinesq_convection.cc File Reference
Classes
class ConvectionProblem< ELEMENT >
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
Namespaces
namespace Global_Physical_Variables
Namespace for the physical parameters in the problem.
Functions
Vector< double > Global_Physical_Variables::Direction_of_gravity (2)
Gravity vector.
int main (int argc, char **argv)
Driver code for 2D Boussinesq convection problem.
Variables
double Global_Physical_Variables::Peclet =1.0
Peclet number (identically one from our non-dimensionalisation)
double Global_Physical_Variables::Inverse_Prandtl =1.0
1/Prandtl number
double Global_Physical_Variables::Rayleigh = 1800.0
Rayleigh number, set to be greater than the threshold for linear instability.
Function Documentation
main()
int main (int argc, char ** argv)
Driver code for 2D Boussinesq convection problem.
Definition at line 314 of file boussinesq_convection.cc.
References Global_Physical_Variables::Direction_of_gravity(), ConvectionProblem< ELEMENT >::doc_solution(), and ConvectionProblem< ELEMENT >::set_boundary_conditions().