refine_b_convect.txt File Reference
Typedefs
using href = `../../b_convection/html/index.html`>non-refineable version of the problem</a > we create the refineable element \c RefineableBuoyantQCrouzeixRaviartElement by multiple inheritance from the \c RefineableQCrouzeixRaviartElement and \c RefineableQAdvectionDiffusionElement:\dontinclude boussinesq_elements.h \skipline start_element_class \until { Many of the additional member functions required in the combined multi-physics element are identical to those in the non-refineable version:- the access function to(the pointer to the) Rayleigh number, \c ra_pt(), - the output functions, \c output(...), - the function \c required_n_value(...) which specifies the number of values required at each node, - the function \c u_index_adv_diff(...) which specifies the index at which the temperature is stored within the elements' \c Nodes, - the function \c get_wind_adv_diff(...) which specifies the `wind` in the advection diffusion equations in terms of the Navier-Stokes velocities, - the function \c get_body_force_nst(...) which specifies the body force in the Navier-Stokes equations in terms of the temperature. - the two `fill in` function are implemented as in the non-refineable element. The function \c fill_in_contribution_to_residuals(...) concatenates the contributions from the two underlying elements
Functions
As discussed in the< a href=`../../b_convection/html/index.html`> previous</a > a small perturbation is required to force the solution from the trivial steady state of zero velocity and linear temperature variation we add a small perturbation to the vertical velocity on the upper wall before solving the steady allowing for up to two levels of adaptive mesh refinement until doc_solution Having forced the solution into a non trivial symmetry broken we switch off the perturbation and re solve the allowing for another two levels of adaptive refinement The Newton solver now converges to the unperturbed but symmetry broken solution shown above until end of main< HR >< HR > section problem The problem class The problem class contains the constructor and (empty) destructor
As discussed in the< a href=`../../b_convection/html/index.html`> previous</a > a small perturbation is required to force the solution from the trivial steady state of zero velocity and linear temperature variation we add a small perturbation to the vertical velocity on the upper wall before solving the steady allowing for up to two levels of adaptive mesh refinement until doc_solution Having forced the solution into a non trivial symmetry broken we switch off the perturbation and re solve the allowing for another two levels of adaptive refinement The Newton solver now converges to the unperturbed but symmetry broken solution shown above until end of main< HR >< HR > section problem The problem class The problem class contains the constructor the usual action and an access function to the specific mesh used in this problem dontinclude refineable_b_convection cc skipline start_of_problem_class until end of access No specific action is required before the adaptation but following the mesh adaptation exactly one pressure degree of freedom must be pinned in the problem (Since the domain is enclosed the pressure is only determined up to an arbitrary constant.) The pressure degree of freedom that was pinned before the adaptation may have disappeared during the adaptation
the function c fill_in_contribution_to_jacobian (...) computes the coupled elemental Jacobian matrix by finite-differencing. . We shall only discuss those additional functions that are required in the refineable version of the combined multi-physics element. Both const ituent elements are derived from the \c ElementWithZ2ErrorEstimator base class and each element provides its own definition of the `Z2-flux` that is used by the Z2 error estimator to compute elemental error estimates. We must decide on a single error estimator for the combined element. We could base the error estimation entirely on the fluid flow
a choice that would be appropriate for problems with thin thermal boundary layers The different error estimates can all be specified by user defined functions that combine the vector of compound flux error estimates into a single number For the function code double navier_stokes_flux_error (const Vector< double > &errors)
Variables
mainpage Refineable Boussinesq Convection
nard problem The lower wall is maintained at a temperature f theta_
As discussed in the< a href=`../../b_convection/html/index.html`> previous example
As discussed in the< a href=`../../b_convection/html/index.html`> previous</a > a small perturbation is required to force the solution from the trivial steady state of zero velocity and linear temperature variation Therefore
As discussed in the< a href=`../../b_convection/html/index.html`> previous</a > a small perturbation is required to force the solution from the trivial steady state of zero velocity and linear temperature variation we add a small perturbation to the vertical velocity on the upper wall before solving the steady problem
As discussed in the< a href=`../../b_convection/html/index.html`> previous</a > a small perturbation is required to force the solution from the trivial steady state of zero velocity and linear temperature variation we add a small perturbation to the vertical velocity on the upper wall before solving the steady allowing for up to two levels of adaptive mesh refinement until doc_solution Having forced the solution into a non trivial symmetry broken state
As discussed in the< a href=`../../b_convection/html/index.html`> previous</a > a small perturbation is required to force the solution from the trivial steady state of zero velocity and linear temperature variation we add a small perturbation to the vertical velocity on the upper wall before solving the steady allowing for up to two levels of adaptive mesh refinement until doc_solution Having forced the solution into a non trivial symmetry broken we switch off the perturbation and re solve the allowing for another two levels of adaptive refinement The Newton solver now converges to the unperturbed but symmetry broken solution shown above until end of main< HR >< HR > section problem The problem class The problem class contains the constructor the usual action functions
As discussed in the< a href=`../../b_convection/html/index.html`> previous</a > a small perturbation is required to force the solution from the trivial steady state of zero velocity and linear temperature variation we add a small perturbation to the vertical velocity on the upper wall before solving the steady allowing for up to two levels of adaptive mesh refinement until doc_solution Having forced the solution into a non trivial symmetry broken we switch off the perturbation and re solve the allowing for another two levels of adaptive refinement The Newton solver now converges to the unperturbed but symmetry broken solution shown above until end of main< HR >< HR > section problem The problem class The problem class contains the constructor the usual action and an access function to the specific mesh used in this problem dontinclude refineable_b_convection cc skipline start_of_problem_class until end of access No specific action is required before the adaptation but following the mesh adaptation exactly one pressure degree of freedom must be pinned in the therefore the constraint must be re applied However
As discussed in the< a href=`../../b_convection/html/index.html`> previous</a > a small perturbation is required to force the solution from the trivial steady state of zero velocity and linear temperature variation we add a small perturbation to the vertical velocity on the upper wall before solving the steady allowing for up to two levels of adaptive mesh refinement until doc_solution Having forced the solution into a non trivial symmetry broken we switch off the perturbation and re solve the allowing for another two levels of adaptive refinement The Newton solver now converges to the unperturbed but symmetry broken solution shown above until end of main< HR >< HR > section problem The problem class The problem class contains the constructor the usual action and an access function to the specific mesh used in this problem dontinclude refineable_b_convection cc skipline start_of_problem_class until end of access No specific action is required before the adaptation but following the mesh adaptation exactly one pressure degree of freedom must be pinned in the therefore the constraint must be re applied we unpin all pressure degrees of freedom first to ensure that we do not accidentally pin two pressure degrees of freedom until end_of_fix The remaining member functions provide access to the boolean flag that controls the application of the imperfection
As discussed in the< a href=`../../b_convection/html/index.html`> previous</a > a small perturbation is required to force the solution from the trivial steady state of zero velocity and linear temperature variation we add a small perturbation to the vertical velocity on the upper wall before solving the steady allowing for up to two levels of adaptive mesh refinement until doc_solution Having forced the solution into a non trivial symmetry broken we switch off the perturbation and re solve the allowing for another two levels of adaptive refinement The Newton solver now converges to the unperturbed but symmetry broken solution shown above until end of main< HR >< HR > section problem The problem class The problem class contains the constructor the usual action and an access function to the specific mesh used in this problem dontinclude refineable_b_convection cc skipline start_of_problem_class until end of access No specific action is required before the adaptation but following the mesh adaptation exactly one pressure degree of freedom must be pinned in the therefore the constraint must be re applied we unpin all pressure degrees of freedom first to ensure that we do not accidentally pin two pressure degrees of freedom until end_of_fix The remaining member functions provide access to the boolean flag that controls the application of the and document the solution
As discussed in the< a href=`../../b_convection/html/index.html`> previous</a > a small perturbation is required to force the solution from the trivial steady state of zero velocity and linear temperature variation we add a small perturbation to the vertical velocity on the upper wall before solving the steady allowing for up to two levels of adaptive mesh refinement until doc_solution Having forced the solution into a non trivial symmetry broken we switch off the perturbation and re solve the allowing for another two levels of adaptive refinement The Newton solver now converges to the unperturbed but symmetry broken solution shown above until end of main< HR >< HR > section problem The problem class The problem class contains the constructor the usual action and an access function to the specific mesh used in this problem dontinclude refineable_b_convection cc skipline start_of_problem_class until end of access No specific action is required before the adaptation but following the mesh adaptation exactly one pressure degree of freedom must be pinned in the therefore the constraint must be re applied we unpin all pressure degrees of freedom first to ensure that we do not accidentally pin two pressure degrees of freedom until end_of_fix The remaining member functions provide access to the boolean flag that controls the application of the and document the which has no arguments The constructor builds a coarse initial c RefineableRectangularQuadMesh
the function c or the temperature field
the function c or the temperature but instead we shall choose our single error estimate to be the maximum of the fluid and temperature error estimates The functions required by the c Z2ErrorEstimator are overloaded to return all the flux terms associated with both the velocity and temperature fields
the function c or the temperature but instead we shall choose our single error estimate to be the maximum of the fluid and temperature error estimates The functions required by the c Z2ErrorEstimator are overloaded to return all the flux terms associated with both the velocity and temperature with the velocity field terms stored first dontinclude boussinesq_elements h skipline The recovery order is that of until end of get_Z2_flux The default behaviour of the Z2 error estimator is to combine all components of the flux vector into a single compound flux In the present multi physics element
the function c or the temperature but instead we shall choose our single error estimate to be the maximum of the fluid and temperature error estimates The functions required by the c Z2ErrorEstimator are overloaded to return all the flux terms associated with both the velocity and temperature with the velocity field terms stored first dontinclude boussinesq_elements h skipline The recovery order is that of until end of get_Z2_flux The default behaviour of the Z2 error estimator is to combine all components of the flux vector into a single compound flux In the present multi physics we instead define two compound fluxes
the function c or the temperature but instead we shall choose our single error estimate to be the maximum of the fluid and temperature error estimates The functions required by the c Z2ErrorEstimator are overloaded to return all the flux terms associated with both the velocity and temperature with the velocity field terms stored first dontinclude boussinesq_elements h skipline The recovery order is that of until end of get_Z2_flux The default behaviour of the Z2 error estimator is to combine all components of the flux vector into a single compound flux In the present multi physics we instead define two compound containing the index of the compound flux to which the flux component contributes dontinclude boussinesq_elements h skipline The number of compound fluxes until end of get_Z2_compound_flux_indices The c Z2ErrorEstimator calculates the error estimates for each compound flux The individual error estimates are then combined to a single error estimate by the function c Z2ErrorEstimator::get_combined_error_estimate(). By default the single error estimate is chosen to be the maximum of all calculated error estimates. Alternative user-defined functions can be specified via the function pointer \c Z2ErrorEstimator an appropriate choice for problems in which the variations in the velocity field are expected to be much more rapid than those in the temperature field Alternatively
endcode specifies that the combined error estimate is the first of the compound error estimates the error estimate for the Navier Stokes equations n n In the current example both fields vary very smoothly
endcode specifies that the combined error estimate is the first of the compound error estimates the error estimate for the Navier Stokes equations n n In the current example both fields vary very and as a result spatial adaptivity is not really required in this problem This is why we set a very narrow range of target errors if the default targets are used
endcode specifies that the combined error estimate is the first of the compound error estimates the error estimate for the Navier Stokes equations n n In the current example both fields vary very and as a result spatial adaptivity is not really required in this problem This is why we set a very narrow range of target errors if the default targets are c oomph lib refines the mesh uniformly subsection exercises Exercises is stable
Typedef Documentation
href
using href = `../../b_convection/html/index.html`>non-refineable version of the problem</a> we create the refineable element \c RefineableBuoyantQCrouzeixRaviartElement by multiple inheritance from the \c RefineableQCrouzeixRaviartElement and \c RefineableQAdvectionDiffusionElement: \dontinclude boussinesq_elements.h \skipline start_element_class \until { Many of the additional member functions required in the combined multi-physics element are identical to those in the non-refineable version: - the access function to (the pointer to the) Rayleigh number, \c ra_pt(), - the output functions, \c output(...), - the function \c required_n_value(...) which specifies the number of values required at each node, - the function \c u_index_adv_diff(...) which specifies the index at which the temperature is stored within the elements' \c Nodes, - the function \c get_wind_adv_diff(...) which specifies the `wind` in the advection diffusion equations in terms of the Navier-Stokes velocities, - the function \c get_body_force_nst(...) which specifies the body force in the Navier-Stokes equations in terms of the temperature. - the two `fill in` function are implemented as in the non-refineable element. The function \c fill_in_contribution_to_residuals(...) concatenates the contributions from the two underlying elements
Definition at line 180 of file refine_b_convect.txt.
Function Documentation
and()
As discussed in the<a href=`../../b_convection/html/index.html`> previous</a> a small perturbation is required to force the solution from the trivial steady state of zero velocity and linear temperature variation we add a small perturbation to the vertical velocity on the upper wall before solving the steady allowing for up to two levels of adaptive mesh refinement until doc_solution Having forced the solution into a non trivial symmetry broken we switch off the perturbation and re solve the allowing for another two levels of adaptive refinement The Newton solver now converges to the unperturbed but symmetry broken solution shown above until end of main<HR><HR> section problem The problem class The problem class contains the constructor and (empty)
fill_in_contribution_to_jacobian()
the function c fill_in_contribution_to_jacobian (...) const
Referenced by oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_contribution_to_jacobian(), oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian().
navier_stokes_flux_error()
a choice that would be appropriate for problems with thin thermal boundary layers The different error estimates can all be specified by user defined functions that combine the vector of compound flux error estimates into a single number For the function code double navier_stokes_flux_error (const Vector< double > & errors)
Definition at line 303 of file refine_b_convect.txt.
problem()
As discussed in the<a href=`../../b_convection/html/index.html`> previous</a> a small perturbation is required to force the solution from the trivial steady state of zero velocity and linear temperature variation we add a small perturbation to the vertical velocity on the upper wall before solving the steady allowing for up to two levels of adaptive mesh refinement until doc_solution Having forced the solution into a non trivial symmetry broken we switch off the perturbation and re solve the allowing for another two levels of adaptive refinement The Newton solver now converges to the unperturbed but symmetry broken solution shown above until end of main<HR><HR> section problem The problem class The problem class contains the constructor the usual action and an access function to the specific mesh used in this problem dontinclude refineable_b_convection cc skipline start_of_problem_class until end of access No specific action is required before the adaptation but following the mesh adaptation exactly one pressure degree of freedom must be pinned in the problem (Since the domain is enclosed the pressure is only determined up to an arbitrary constant.)
Variable Documentation
Alternatively
the function c or the temperature but instead we shall choose our single error estimate to be the maximum of the fluid and temperature error estimates The functions required by the c Z2ErrorEstimator are overloaded to return all the flux terms associated with both the velocity and temperature with the velocity field terms stored first dontinclude boussinesq_elements h skipline The recovery order is that of until end of get_Z2_flux The default behaviour of the Z2 error estimator is to combine all components of the flux vector into a single compound flux In the present multi physics we instead define two compound containing the index of the compound flux to which the flux component contributes dontinclude boussinesq_elements h skipline The number of compound fluxes until end of get_Z2_compound_flux_indices The c Z2ErrorEstimator calculates the error estimates for each compound flux The individual error estimates are then combined to a single error estimate by the function c Z2ErrorEstimator::get_combined_error_estimate (). By default the single error estimate is chosen to be the maximum of all calculated error estimates. Alternative user-defined functions can be specified via the function pointer \c Z2ErrorEstimator an appropriate choice for problems in which the variations in the velocity field are expected to be much more rapid than those in the temperature field Alternatively
Definition at line 222 of file refine_b_convect.txt.
Convection
mainpage Refineable Boussinesq Convection
Definition at line 8 of file refine_b_convect.txt.
element
the function c or the temperature but instead we shall choose our single error estimate to be the maximum of the fluid and temperature error estimates The functions required by the c Z2ErrorEstimator are overloaded to return all the flux terms associated with both the velocity and temperature with the velocity field terms stored first dontinclude boussinesq_elements h skipline The recovery order is that of until end of get_Z2_flux The default behaviour of the Z2 error estimator is to combine all components of the flux vector into a single compound flux In the present multi physics element
Definition at line 206 of file refine_b_convect.txt.
example
a choice that would be appropriate for problems with thin thermal boundary layers The different error estimates can all be specified by user defined functions that combine the vector of compound flux error estimates into a single number For example
Definition at line 36 of file refine_b_convect.txt.
field
the function c or the temperature but instead we shall choose our single error estimate to be the maximum of the fluid and temperature error estimates The functions required by the c Z2ErrorEstimator are overloaded to return all the flux terms associated with both the velocity and temperature with the velocity field terms stored first dontinclude boussinesq_elements h skipline The recovery order is that of until end of get_Z2_flux The default behaviour of the Z2 error estimator is to combine all components of the flux vector into a single compound flux In the present multi physics we instead define two compound containing the index of the compound flux to which the flux component contributes dontinclude boussinesq_elements h skipline The number of compound fluxes until end of get_Z2_compound_flux_indices The c Z2ErrorEstimator calculates the error estimates for each compound flux The individual error estimates are then combined to a single error estimate by the function c Z2ErrorEstimator::get_combined_error_estimate (). By default the single error estimate is chosen to be the maximum of all calculated error estimates. Alternative user-defined functions can be specified via the function pointer \c Z2ErrorEstimator an appropriate choice for problems in which the variations in the velocity field are expected to be much more rapid than those in the temperature field the error estimation could be based exclusively on the temperature field
Definition at line 193 of file refine_b_convect.txt.
fields
the function c or the temperature but instead we shall choose our single error estimate to be the maximum of the fluid and temperature error estimates The functions required by the c Z2ErrorEstimator are overloaded to return all the flux terms associated with both the velocity and temperature fields
Definition at line 198 of file refine_b_convect.txt.
fluxes
the function c or the temperature but instead we shall choose our single error estimate to be the maximum of the fluid and temperature error estimates The functions required by the c Z2ErrorEstimator are overloaded to return all the flux terms associated with both the velocity and temperature with the velocity field terms stored first dontinclude boussinesq_elements h skipline The recovery order is that of until end of get_Z2_flux The default behaviour of the Z2 error estimator is to combine all components of the flux vector into a single compound flux In the present multi physics we instead define two compound fluxes
Definition at line 212 of file refine_b_convect.txt.
functions
As discussed in the<a href=`../../b_convection/html/index.html`> previous</a> a small perturbation is required to force the solution from the trivial steady state of zero velocity and linear temperature variation we add a small perturbation to the vertical velocity on the upper wall before solving the steady allowing for up to two levels of adaptive mesh refinement until doc_solution Having forced the solution into a non trivial symmetry broken we switch off the perturbation and re solve the allowing for another two levels of adaptive refinement The Newton solver now converges to the unperturbed but symmetry broken solution shown above until end of main<HR><HR> section problem The problem class The problem class contains the constructor the usual action functions
Definition at line 58 of file refine_b_convect.txt.
However
As discussed in the<a href=`../../b_convection/html/index.html`> previous</a> a small perturbation is required to force the solution from the trivial steady state of zero velocity and linear temperature variation we add a small perturbation to the vertical velocity on the upper wall before solving the steady allowing for up to two levels of adaptive mesh refinement until doc_solution Having forced the solution into a non trivial symmetry broken we switch off the perturbation and re solve the allowing for another two levels of adaptive refinement The Newton solver now converges to the unperturbed but symmetry broken solution shown above until end of main<HR><HR> section problem The problem class The problem class contains the constructor the usual action and an access function to the specific mesh used in this problem dontinclude refineable_b_convection cc skipline start_of_problem_class until end of access No specific action is required before the adaptation but following the mesh adaptation exactly one pressure degree of freedom must be pinned in the therefore the constraint must be re applied However
Definition at line 71 of file refine_b_convect.txt.
imperfection
As discussed in the<a href=`../../b_convection/html/index.html`> previous</a> a small perturbation is required to force the solution from the trivial steady state of zero velocity and linear temperature variation we add a small perturbation to the vertical velocity on the upper wall before solving the steady allowing for up to two levels of adaptive mesh refinement until doc_solution Having forced the solution into a non trivial symmetry broken we switch off the perturbation and re solve the allowing for another two levels of adaptive refinement The Newton solver now converges to the unperturbed but symmetry broken solution shown above until end of main<HR><HR> section problem The problem class The problem class contains the constructor the usual action and an access function to the specific mesh used in this problem dontinclude refineable_b_convection cc skipline start_of_problem_class until end of access No specific action is required before the adaptation but following the mesh adaptation exactly one pressure degree of freedom must be pinned in the therefore the constraint must be re applied we unpin all pressure degrees of freedom first to ensure that we do not accidentally pin two pressure degrees of freedom until end_of_fix The remaining member functions provide access to the boolean flag that controls the application of the imperfection
Definition at line 78 of file refine_b_convect.txt.
problem
As discussed in the< a href=`../../b_convection/html/index.html`> previous</a > a small perturbation is required to force the solution from the trivial steady state of zero velocity and linear temperature variation we add a small perturbation to the vertical velocity on the upper wall before solving the steady allowing for up to two levels of adaptive mesh refinement until doc_solution Having forced the solution into a non trivial symmetry broken we switch off the perturbation and re solve the problem
Definition at line 40 of file refine_b_convect.txt.
Referenced by main().
RefineableRectangularQuadMesh
As discussed in the<a href=`../../b_convection/html/index.html`> previous</a> a small perturbation is required to force the solution from the trivial steady state of zero velocity and linear temperature variation we add a small perturbation to the vertical velocity on the upper wall before solving the steady allowing for up to two levels of adaptive mesh refinement until doc_solution Having forced the solution into a non trivial symmetry broken we switch off the perturbation and re solve the allowing for another two levels of adaptive refinement The Newton solver now converges to the unperturbed but symmetry broken solution shown above until end of main<HR><HR> section problem The problem class The problem class contains the constructor the usual action and an access function to the specific mesh used in this problem dontinclude refineable_b_convection cc skipline start_of_problem_class until end of access No specific action is required before the adaptation but following the mesh adaptation exactly one pressure degree of freedom must be pinned in the therefore the constraint must be re applied we unpin all pressure degrees of freedom first to ensure that we do not accidentally pin two pressure degrees of freedom until end_of_fix The remaining member functions provide access to the boolean flag that controls the application of the and document the which has no arguments The constructor builds a coarse initial c RefineableRectangularQuadMesh
Definition at line 90 of file refine_b_convect.txt.
smoothly
endcode specifies that the combined error estimate is the first of the compound error estimates the error estimate for the Navier Stokes equations n n In the current example both fields vary very smoothly
Definition at line 310 of file refine_b_convect.txt.
solution
As discussed in the<a href=`../../b_convection/html/index.html`> previous</a> a small perturbation is required to force the solution from the trivial steady state of zero velocity and linear temperature variation we add a small perturbation to the vertical velocity on the upper wall before solving the steady allowing for up to two levels of adaptive mesh refinement until doc_solution Having forced the solution into a non trivial symmetry broken we switch off the perturbation and re solve the allowing for another two levels of adaptive refinement The Newton solver now converges to the unperturbed but symmetry broken solution shown above until end of main<HR><HR> section problem The problem class The problem class contains the constructor the usual action and an access function to the specific mesh used in this problem dontinclude refineable_b_convection cc skipline start_of_problem_class until end of access No specific action is required before the adaptation but following the mesh adaptation exactly one pressure degree of freedom must be pinned in the therefore the constraint must be re applied we unpin all pressure degrees of freedom first to ensure that we do not accidentally pin two pressure degrees of freedom until end_of_fix The remaining member functions provide access to the boolean flag that controls the application of the and document the solution
Definition at line 89 of file refine_b_convect.txt.
stable
endcode specifies that the combined error estimate is the first of the compound error estimates the error estimate for the Navier Stokes equations n n In the current example both fields vary very and as a result spatial adaptivity is not really required in this problem This is why we set a very narrow range of target errors if the default targets are c oomph lib refines the mesh uniformly subsection exercises Exercises is stable
Definition at line 317 of file refine_b_convect.txt.
state
endcode specifies that the combined error estimate is the first of the compound error estimates the error estimate for the Navier Stokes equations n n In the current example both fields vary very and as a result spatial adaptivity is not really required in this problem This is why we set a very narrow range of target errors if the default targets are c oomph lib refines the mesh uniformly subsection exercises Exercises is i e it returns to the trivial state
Definition at line 45 of file refine_b_convect.txt.
Therefore
As discussed in the<a href=`../../b_convection/html/index.html`> previous</a> a small perturbation is required to force the solution from the trivial steady state of zero velocity and linear temperature variation Therefore
Definition at line 38 of file refine_b_convect.txt.
theta_
nard problem The lower wall is maintained at a temperature f where f theta_
Initial value:
{bottom} \f$ and the upper wall is maintained at
 a temperature \f$ \theta_{top} \f$
Definition at line 9 of file refine_b_convect.txt.
used
endcode specifies that the combined error estimate is the first of the compound error estimates the error estimate for the Navier Stokes equations n n In the current example both fields vary very and as a result spatial adaptivity is not really required in this problem This is why we set a very narrow range of target errors if the default targets are used
Definition at line 313 of file refine_b_convect.txt.