AnnularQuadMesh< ELEMENT > Class Template Reference
Public Member Functions
AnnularQuadMesh (const unsigned &n_r, const unsigned &n_phi, const double &r_min, const double &r_max, const double &phi_min, const double &phi_max)
Detailed Description
template<class ELEMENT>
class AnnularQuadMesh< ELEMENT >
Definition at line 55 of file sphere_scattering.cc.
Constructor & Destructor Documentation
AnnularQuadMesh()
template<class ELEMENT >
AnnularQuadMesh< ELEMENT >::AnnularQuadMesh (const unsigned & n_r, const unsigned & n_phi, const double & r_min, const double & r_max, const double & phi_min, const double & phi_max) [inline]
Definition at line 65 of file sphere_scattering.cc.
Referenced by FourierDecomposedHelmholtzProblem< ELEMENT >::actions_after_adapt(), FourierDecomposedHelmholtzProblem< ELEMENT >::actions_before_adapt(), FourierDecomposedHelmholtzProblem< ELEMENT >::actions_before_newton_convergence_check(), and main().
The documentation for this class was generated from the following file:
sphere_scattering.cc