oomph::SurfaceVolumeConstraintBoundingElement Class Reference
Two-dimensional interface elements that allow the application of a volume constraint on the region bounded by these elements. The volume is computed by integrating x.n around the boundary of the domain and then dividing by three. The sign is chosen so that the volume will be positive when the elements surround a fluid domain.
#include <constrained_volume_elements.h>
Public Member Functions
SurfaceVolumeConstraintBoundingElement ()
Empty Contructor.
~SurfaceVolumeConstraintBoundingElement ()
Empty Desctructor.
Public Member Functions inherited from oomph::VolumeConstraintBoundingElement
VolumeConstraintBoundingElement ()
Constructor initialise the boolean flag We expect the traded pressure data to be stored externally.
~VolumeConstraintBoundingElement ()
Empty Destructor.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in contribution to residuals and Jacobian.
void set_volume_constraint_element (VolumeConstraintElement *const &vol_constraint_el_pt, const bool &check_nodal_data=true)
Set the "master" volume constraint element The setup here is a bit more complicated than one might expect because if an internal pressure on a boundary is hijacked in TaylorHood elements then that the "traded" value may already be stored as nodal data in this element. This causes no problems apart from when running with PARANOID in which case the resulting repeated local equation numbers are spotted and an error is thrown. The check is a finite amount of work and so can be avoided if the boolean flag check_nodal_data is set to false.
Protected Member Functions
void fill_in_generic_residual_contribution_volume_constraint (Vector< double > &residuals)
Helper function to fill in contributions to residuals (remember that part of the residual is added by the the associated VolumeConstraintElement). This is specific for 2D surface elements that bound 3D cartesian fluid elements.
Protected Member Functions inherited from oomph::VolumeConstraintBoundingElement
int ptraded_local_eqn ()
The local eqn number for the traded pressure.
Additional Inherited Members
Protected Attributes inherited from oomph::VolumeConstraintBoundingElement
unsigned Data_number_of_traded_pressure
The Data that contains the traded pressure is usually stored as external Data for this element, but may also be nodal Data Which Data item is it?
unsigned Index_of_traded_pressure_value
Index of the value in traded pressure data that corresponds to the traded pressure.
bool Traded_pressure_stored_at_node
Boolean to indicate whether the traded pressure is stored externally or at a node (this can happen in Taylor-Hood elements)
Detailed Description
Two-dimensional interface elements that allow the application of a volume constraint on the region bounded by these elements. The volume is computed by integrating x.n around the boundary of the domain and then dividing by three. The sign is chosen so that the volume will be positive when the elements surround a fluid domain.
These elements must be used together with the associated VolumeConstraintElement, which stores the value of the target volume.
Definition at line 715 of file constrained_volume_elements.h.
Constructor & Destructor Documentation
SurfaceVolumeConstraintBoundingElement()
oomph::SurfaceVolumeConstraintBoundingElement::SurfaceVolumeConstraintBoundingElement () [inline]
Empty Contructor.
Definition at line 728 of file constrained_volume_elements.h.
~SurfaceVolumeConstraintBoundingElement()
oomph::SurfaceVolumeConstraintBoundingElement::~SurfaceVolumeConstraintBoundingElement () [inline]
Empty Desctructor.
Definition at line 733 of file constrained_volume_elements.h.
Member Function Documentation
fill_in_generic_residual_contribution_volume_constraint()
void oomph::SurfaceVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint (Vector< double > & residuals) [protected], [virtual]
Helper function to fill in contributions to residuals (remember that part of the residual is added by the the associated VolumeConstraintElement). This is specific for 2D surface elements that bound 3D cartesian fluid elements.
Implements oomph::VolumeConstraintBoundingElement.
Definition at line 434 of file constrained_volume_elements.cc.
References oomph::VolumeConstraintBoundingElement::ptraded_local_eqn().
Referenced by oomph::ElasticSurfaceVolumeConstraintBoundingElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::SpineSurfaceVolumeConstraintBoundingElement< ELEMENT >::fill_in_contribution_to_jacobian().
The documentation for this class was generated from the following files:
constrained_volume_elements.h
constrained_volume_elements.cc