Flag_definition::TopOfFlag Class Reference
GeomObject that defines the upper boundary of the flag.
Public Member Functions
TopOfFlag ()
Constructor: It's a 1D object in 2D space.
~TopOfFlag ()
Destructor (empty)
void position (const unsigned &t, const Vector< double > &xi, Vector< double > &r) const
Return the position along the top of the flag (xi[0] varies between 0 and Lx)
void position (const Vector< double > &xi, Vector< double > &r) const
Current position.
unsigned ngeom_data () const
Number of geometric Data in GeomObject: None.
Detailed Description
GeomObject that defines the upper boundary of the flag.
Definition at line 126 of file turek_flag_non_fsi.cc.
Constructor & Destructor Documentation
TopOfFlag()
Flag_definition::TopOfFlag::TopOfFlag () [inline]
Constructor: It's a 1D object in 2D space.
Definition at line 132 of file turek_flag_non_fsi.cc.
 TopOfFlag()
Flag_definition::TopOfFlag::~TopOfFlag () [inline]
Destructor (empty)
Definition at line 135 of file turek_flag_non_fsi.cc.
Member Function Documentation
ngeom_data()
unsigned Flag_definition::TopOfFlag::ngeom_data () const [inline]
Number of geometric Data in GeomObject: None.
Definition at line 167 of file turek_flag_non_fsi.cc.
position() [1/2]
void Flag_definition::TopOfFlag::position (const unsigned & t, const Vector< double > & xi, Vector< double > & r) const [inline]
Return the position along the top of the flag (xi[0] varies between 0 and Lx)
Definition at line 139 of file turek_flag_non_fsi.cc.
References Flag_definition::Centre_x, Flag_definition::Centre_y, Flag_definition::H, Flag_definition::L, Flag_definition::Period, Flag_definition::Radius, Flag_definition::Time_pt, and Flag_definition::upper_tip().
Referenced by position().
position() [2/2]
void Flag_definition::TopOfFlag::position (const Vector< double > & xi, Vector< double > & r) const [inline]
Current position.
Definition at line 161 of file turek_flag_non_fsi.cc.
References position().
The documentation for this class was generated from the following file:
turek_flag_non_fsi.cc