prescribed_displ_lagr_mult.txt File Reference
Typedefs
using prescr = \big(\xi^1_{\partial D_{prescr}}(\zeta), \xi^2_{\partial D_{prescr}}(\zeta) \big) \f] which allows us to write the displacement constraint as \f[{\bf R}(\xi^1_{\partial D_{prescr}}(\zeta),\xi^2_{\partial D_{prescr}}(\zeta))={\bf R}_{prescr}(\zeta). \f] We enforce this constraint by augmenting the principle of virtual displacements, discussed in< a href=`../../solid_theory/html/index.html#equilibrium`> the solid mechanics theory tutorial</a >, by a Lagrange multiplier term so that it becomes \f[\int \left\{ \sigma^{ij} \ \delta \gamma_{ij} - \left({\bf f} - \Lambda^2 \frac{\partial^2 {\bf R}}{\partial t^2} \right) \cdot \delta {\bf R} \right\} \ dv - \oint_{A_{tract}} {\bf T} \cdot \delta {\bf R} \ dA \+\ \delta \Pi_{constraint}=0 \ \ \ \ \ \ \ \ @E[continuous_pdv]@ \f] where \f[\Pi_{constraint}=\int_{\partial D} \bigg({\bf R}(\xi^1(\zeta),\xi^2(\zeta)) - {\bf R}_{prescr}(\zeta) \bigg) \cdot {\bf \Lambda} \ dS. \f] Here \f[dS=\left|\frac{d {\bf R}(\xi^1(\zeta),\xi^2(\zeta))}{d \zeta} \right|d\zeta \f] is the differential of the arclength along the domain boundary and the vector \f$ {\bf \Lambda} \f$(not to be confused with the scalar \f$ \Lambda^2 \f$ which represents the non-dimensional density in(@R[continuous_pdv]@)!) is the Lagrange multiplier -- the surface traction to be applied to \f$ \partial D_{prescr} \f$ to deform the boundary into the required shape. We discretise this constraint by attaching \c FaceElements to the boundaries of the `bulk` solid elements that are adjacent to \f$ \partial D_{prescr} \f$. We denote the number of nodes in these \c FaceElements by \f$ N \f$ and write the \f$ i \f$-th component of the discrete Lagrange multiplier stored at node \f$ j \f$ as \f$ L_{ij} \f$. Thus the \f$ i \f$ -th component of the Lagrange multiplier at local coordinate \f$ s \f$ in the element is given by \f[\Lambda_i=\sum_{j=1}^{N} L_{ij} \psi_j(s) \f] where \f$ \psi_j(s) \f$ is the shape function associated with node \f$ j \f$. Upon taking the variations of the discretised constraint with respect to the unknown nodal positions and the discrete Lagrange multipliers we obtain< b >(i)</b > additional contributions to the residuals of the `bulk` solid mechanics equations(these may be interpreted as the virtual work done by the boundary tractions required to impose the prescribed boundary displacement) and< b >(ii)</b > the equations that impose the displacement constraints in weak form. The actual implementation of this approach in \c oomph-lib is best thought of as a generalisation of the \c SolidTractionElements that are used to impose a prescribed traction to the boundary of a solid domain. The main difference is that in the \c ImposeDisplacementByLagrangeMultiplierElement, the imposed traction is one of the unknowns in the problem and must be determined via the displacement constraint, using the approach described above. The element introduces additional unknowns(the nodal values of the Lagrange multiplier) into the problem, therefore the \c ImposeDisplacementByLagrangeMultiplierElement resizes(increases) the number of values stored at the node from the value that was originally assigned by the `bulk` solid element it is attached to.(If the elements are used in a single-physics solid mechanics problem the discrete Lagrange multipliers are the only nodal values in the problem since the unknown nodal positions are stored in a separate \c Data item
Functions
cf< A HREF=`../../solid_theory/html/index.html#solid_node`> Solid the boundary is pulled upwards into a sinusoidal shape while simultaneously being pushed to the right The vectors in the animation represent the Lagrange multipliers (i.e. the physical surface tractions) required to deform the domain into the required shape. Note how the automatic mesh adaptation refines the mesh in regions where the solid is strongly deformed. @I w 0.75\textwidth lagr_distort `Domain deformation in response to the prescribed boundary displacement. `< HR >< HR > \section prescribed_boundary Describing the prescribed boundary motion with a GeomObject Here is the implementation of the prescribed boundary shape as the \c WarpedLine
namespace Global parameters As usual we define the problem parameters in a global namespace We provide an instantiation of the c GeomObject that defines the deformed boundary shape (setting its initial displacement amplitude to zero)
namespace Global parameters As usual we define the problem parameters in a global namespace We provide an instantiation of the c GeomObject that defines the deformed boundary and create an instance of c oomph lib s generalised Hookean constitutive equation with a Poisson ratio of (recall that the use of the single-argument constructor for this constitutive equation implies that all stresses are non-dimensionalised on Young 's modulus \f$ E \f$;see< a href=`../../solid_theory/html/index.html#non-dim_solid`> the solid mechanics theory tutorial</a > for details). \dontinclude prescribed_displ_lagr_mult.cc \skipline start_namespace \until end namespace< HR >< HR > \section driver The driver code We build an instantiation of the \c Problem class(described below)
We now create a new c SolidMesh in which we store the elements that apply the displacement constraint These elements are built (and added to the newly created \c SolidMesh) in the helper function \c create_lagrange_multiplier_elements(). Both meshes are then combined to the \c Problem 's global mesh. \until build_global_mesh()
We pin the position of the nodes on all domain boundaries apart from the top boundary (boundary 2) and pin any redundant pressure degrees of freedom.(This is not strictly necessary in the present driver code since the displacement-based \c RefineableQPVDElements do not have any pressure degrees of freedom. However
We pin the position of the nodes on all domain boundaries apart from the top it is good practice to do this anyway to guard against unpleasant surprises when the element type is changed at some point until solid_mesh_pt () -> element_pt())
we assign the equation numbers and specify the output directory until end of constructor< HR >< HR > section actions_before_adapt Actions before mesh adaptation As we remove the c FaceElements that apply the displacement constraints before the bulk mesh is adapted dontinclude prescribed_displ_lagr_mult cc skipline start_of_actions_before_adapt until end of actions_before_adapt< HR >< HR > section actions_after_adapt Actions after mesh adaptation We re attach the c FaceElements that apply the displacement constraints once the bulk mesh has been adapted Since the hanging status of nodes in the bulk mesh can change during the mesh adaptation it is again good practice to pin any nodal solid pressure values that may have become redundant dontinclude prescribed_displ_lagr_mult cc skipline start_of_actions_after_adapt until end of actions_after_adapt< HR >< HR > section lagr_elements Creating the Lagrange multiplier elements that impose the displacement constraint The creation of the Lagrange multiplier elements that impose the displacement constraint follows the usual pattern We loop over the bulk solid elements that are adjacent to mesh boundary and attach c ImposeDisplacementByLagrangeMultiplierElements to the appropriate faces dontinclude prescribed_displ_lagr_mult cc skipline start_of_create_lagrange_multiplier_elements until Next we loop over the newly created c ImposeDisplacementByLagrangeMultiplierElements and specify the c GeomObject that defines the imposed boundary displacements We also specify which boundary of the bulk mesh the c ImposeDisplacementByLagrangeMultiplierElements are located on This is required to enable the c ImposeDisplacementByLagrangeMultiplierElements to extract the appropriate boundary coordinate from its constituent nodes(We discussed< a href=`../../../poisson/fish_poisson2/html/index.html#boundary_coords`> elsewhere</a > that boundary coordinates are usually defined(and passed to the nodes) when the nodes are first created, typically during the construction of the bulk mesh. Since nodes can be located on multiple domain boundaries, each boundary coordinate is associated with a particular boundary number. Passing this number to the \c ImposeDisplacementByLagrangeMultiplierElements allows them to obtain the correct boundary coordinate from the node.) \until &Global_Physical_Variables we impose boundary conditions for the Lagrange multipliers Their values must be pinned (and set to zero) at the left and right ends of the upper mesh boundary(boundary 2)
we assign the equation numbers and specify the output directory until end of constructor< HR >< HR > section actions_before_adapt Actions before mesh adaptation As we remove the c FaceElements that apply the displacement constraints before the bulk mesh is adapted dontinclude prescribed_displ_lagr_mult cc skipline start_of_actions_before_adapt until end of actions_before_adapt< HR >< HR > section actions_after_adapt Actions after mesh adaptation We re attach the c FaceElements that apply the displacement constraints once the bulk mesh has been adapted Since the hanging status of nodes in the bulk mesh can change during the mesh adaptation it is again good practice to pin any nodal solid pressure values that may have become redundant dontinclude prescribed_displ_lagr_mult cc skipline start_of_actions_after_adapt until end of actions_after_adapt< HR >< HR > section lagr_elements Creating the Lagrange multiplier elements that impose the displacement constraint The creation of the Lagrange multiplier elements that impose the displacement constraint follows the usual pattern We loop over the bulk solid elements that are adjacent to mesh boundary and attach c ImposeDisplacementByLagrangeMultiplierElements to the appropriate faces dontinclude prescribed_displ_lagr_mult cc skipline start_of_create_lagrange_multiplier_elements until Next we loop over the newly created c ImposeDisplacementByLagrangeMultiplierElements and specify the c GeomObject that defines the imposed boundary displacements We also specify which boundary of the bulk mesh the c ImposeDisplacementByLagrangeMultiplierElements are located on This is required to enable the c ImposeDisplacementByLagrangeMultiplierElements to extract the appropriate boundary coordinate from its constituent nodes(We discussed< a href=`../../../poisson/fish_poisson2/html/index.html#boundary_coords`> elsewhere</a > that boundary coordinates are usually defined(and passed to the nodes) when the nodes are first created, typically during the construction of the bulk mesh. Since nodes can be located on multiple domain boundaries, each boundary coordinate is associated with a particular boundary number. Passing this number to the \c ImposeDisplacementByLagrangeMultiplierElements allows them to obtain the correct boundary coordinate from the node.) \until &Global_Physical_Variables we impose boundary conditions for the Lagrange multipliers Their values must be since the displacement of the nodes at these points is already enforced by the boundary conditions imposed at the left and right vertical boundaries (boundaries 1 and 3).< a name
Variables
mainpage Demo problem
cf< A HREF=`../../solid_theory/html/index.html#solid_node`> Solid mechanics
cf< A HREF=`../../solid_theory/html/index.html#solid_node`> Solid the boundary is pulled upwards into a sinusoidal shape while simultaneously being pushed to the right The vectors in the animation represent the Lagrange a two dimensional c GeomObject whose shape is parametrised by a single intrinsic coordinate dontinclude prescribed_displ_lagr_mult cc skipline Start_of_warped_line until
< HR >< HR > section constructor The Problem constructor We start by creating the bulk mesh
< HR >< HR > section constructor The Problem constructor We start by creating the bulk discretising the domain with elements of the type specified by the class s template argument dontinclude prescribed_displ_lagr_mult cc skipline start_of_constructor until l_x
< HR >< HR > section constructor The Problem constructor We start by creating the bulk discretising the domain with elements of the type specified by the class s template argument dontinclude prescribed_displ_lagr_mult cc skipline start_of_constructor until l_y
Next we specify the error estimator
Next we specify the error pass the pointer to the constitutive equation to the elements and perform one uniform mesh refinement
Finally
we assign the equation numbers and specify the output directory until end of constructor< HR >< HR > section actions_before_adapt Actions before mesh adaptation As usual
we assign the equation numbers and specify the output directory until end of constructor< HR >< HR > section actions_before_adapt Actions before mesh adaptation As we remove the c FaceElements that apply the displacement constraints before the bulk mesh is adapted dontinclude prescribed_displ_lagr_mult cc skipline start_of_actions_before_adapt until end of actions_before_adapt< HR >< HR > section actions_after_adapt Actions after mesh adaptation We re attach the c FaceElements that apply the displacement constraints once the bulk mesh has been adapted Since the hanging status of nodes in the bulk mesh can change during the mesh adaptation it is again good practice to pin any nodal solid pressure values that may have become redundant dontinclude prescribed_displ_lagr_mult cc skipline start_of_actions_after_adapt until end of actions_after_adapt< HR >< HR > section lagr_elements Creating the Lagrange multiplier elements that impose the displacement constraint The creation of the Lagrange multiplier elements that impose the displacement constraint follows the usual pattern We loop over the bulk solid elements that are adjacent to mesh boundary and attach c ImposeDisplacementByLagrangeMultiplierElements to the appropriate faces dontinclude prescribed_displ_lagr_mult cc skipline start_of_create_lagrange_multiplier_elements until Next we loop over the newly created c ImposeDisplacementByLagrangeMultiplierElements and specify the c GeomObject that defines the imposed boundary displacements We also specify which boundary of the bulk mesh the c ImposeDisplacementByLagrangeMultiplierElements are located on This is required to enable the c ImposeDisplacementByLagrangeMultiplierElements to extract the appropriate boundary coordinate from its constituent nodes(We discussed< a href=`../../../poisson/fish_poisson2/html/index.html#boundary_coords`> elsewhere</a > that boundary coordinates are usually defined(and passed to the nodes) when the nodes are first created, typically during the construction of the bulk mesh. Since nodes can be located on multiple domain boundaries, each boundary coordinate is associated with a particular boundary number. Passing this number to the \c ImposeDisplacementByLagrangeMultiplierElements allows them to obtain the correct boundary coordinate from the node.) \until &Global_Physical_Variables we impose boundary conditions for the Lagrange multipliers Their values must be since the displacement of the nodes at these points is already enforced by the boundary conditions imposed at the left and right vertical used here
Typedef Documentation
prescr
using prescr = \big(\xi^1_{\partial D_{prescr}}(\zeta), \xi^2_{\partial D_{prescr}}(\zeta) \big) \f] which allows us to write the displacement constraint as \f[ {\bf R}(\xi^1_{\partial D_{prescr}}(\zeta),\xi^2_{\partial D_{prescr}}(\zeta)) = {\bf R}_{prescr}(\zeta). \f] We enforce this constraint by augmenting the principle of virtual displacements, discussed in <a href=`../../solid_theory/html/index.html#equilibrium`> the solid mechanics theory tutorial</a>, by a Lagrange multiplier term so that it becomes \f[ \int \left\{ \sigma^{ij} \ \delta \gamma_{ij} - \left({\bf f} - \Lambda^2 \frac{\partial^2 {\bf R}}{\partial t^2} \right) \cdot \delta {\bf R} \right\} \ dv - \oint_{A_{tract}} {\bf T} \cdot \delta {\bf R} \ dA \ + \ \delta \Pi_{constraint} = 0 \ \ \ \ \ \ \ \ @E[continuous_pdv]@ \f] where \f[ \Pi_{constraint} = \int_{\partial D} \bigg({\bf R}(\xi^1(\zeta),\xi^2(\zeta)) - {\bf R}_{prescr}(\zeta) \bigg) \cdot {\bf \Lambda} \ dS. \f] Here \f[ dS = \left| \frac{d {\bf R}(\xi^1(\zeta),\xi^2(\zeta))}{d \zeta} \right| d\zeta \f] is the differential of the arclength along the domain boundary and the vector \f$ {\bf \Lambda} \f$ (not to be confused with the scalar \f$ \Lambda^2 \f$ which represents the non-dimensional density in (@R[continuous_pdv]@)!) is the Lagrange multiplier -- the surface traction to be applied to \f$ \partial D_{prescr} \f$ to deform the boundary into the required shape. We discretise this constraint by attaching \c FaceElements to the boundaries of the `bulk` solid elements that are adjacent to \f$ \partial D_{prescr} \f$. We denote the number of nodes in these \c FaceElements by \f$ N \f$ and write the \f$ i \f$-th component of the discrete Lagrange multiplier stored at node \f$ j \f$ as \f$ L_{ij} \f$. Thus the \f$ i \f$ -th component of the Lagrange multiplier at local coordinate \f$ s \f$ in the element is given by \f[ \Lambda_i = \sum_{j=1}^{N} L_{ij} \psi_j(s) \f] where \f$ \psi_j(s) \f$ is the shape function associated with node \f$ j \f$. Upon taking the variations of the discretised constraint with respect to the unknown nodal positions and the discrete Lagrange multipliers we obtain <b>(i)</b> additional contributions to the residuals of the `bulk` solid mechanics equations (these may be interpreted as the virtual work done by the boundary tractions required to impose the prescribed boundary displacement) and <b>(ii)</b> the equations that impose the displacement constraints in weak form. The actual implementation of this approach in \c oomph-lib is best thought of as a generalisation of the \c SolidTractionElements that are used to impose a prescribed traction to the boundary of a solid domain. The main difference is that in the \c ImposeDisplacementByLagrangeMultiplierElement, the imposed traction is one of the unknowns in the problem and must be determined via the displacement constraint, using the approach described above. The element introduces additional unknowns (the nodal values of the Lagrange multiplier) into the problem, therefore the \c ImposeDisplacementByLagrangeMultiplierElement resizes (increases) the number of values stored at the node from the value that was originally assigned by the `bulk` solid element it is attached to. (If the elements are used in a single-physics solid mechanics problem the discrete Lagrange multipliers are the only nodal values in the problem since the unknown nodal positions are stored in a separate \c Data item
Definition at line 111 of file prescribed_displ_lagr_mult.txt.
Function Documentation
boundaries()
we assign the equation numbers and specify the output directory until end of constructor<HR><HR> section actions_before_adapt Actions before mesh adaptation As we remove the c FaceElements that apply the displacement constraints before the bulk mesh is adapted dontinclude prescribed_displ_lagr_mult cc skipline start_of_actions_before_adapt until end of actions_before_adapt<HR><HR> section actions_after_adapt Actions after mesh adaptation We re attach the c FaceElements that apply the displacement constraints once the bulk mesh has been adapted Since the hanging status of nodes in the bulk mesh can change during the mesh adaptation it is again good practice to pin any nodal solid pressure values that may have become redundant dontinclude prescribed_displ_lagr_mult cc skipline start_of_actions_after_adapt until end of actions_after_adapt<HR><HR> section lagr_elements Creating the Lagrange multiplier elements that impose the displacement constraint The creation of the Lagrange multiplier elements that impose the displacement constraint follows the usual pattern We loop over the bulk solid elements that are adjacent to mesh boundary and attach c ImposeDisplacementByLagrangeMultiplierElements to the appropriate faces dontinclude prescribed_displ_lagr_mult cc skipline start_of_create_lagrange_multiplier_elements until Next we loop over the newly created c ImposeDisplacementByLagrangeMultiplierElements and specify the c GeomObject that defines the imposed boundary displacements We also specify which boundary of the bulk mesh the c ImposeDisplacementByLagrangeMultiplierElements are located on This is required to enable the c ImposeDisplacementByLagrangeMultiplierElements to extract the appropriate boundary coordinate from its constituent nodes (We discussed <a href=`../../../poisson/fish_poisson2/html/index.html#boundary_coords`> elsewhere</a> that boundary coordinates are usually defined (and passed to the nodes) when the nodes are first created, typically during the construction of the bulk mesh. Since nodes can be located on multiple domain boundaries, each boundary coordinate is associated with a particular boundary number. Passing this number to the \c ImposeDisplacementByLagrangeMultiplierElements allows them to obtain the correct boundary coordinate from the node.) \until &Global_Physical_Variables we impose boundary conditions for the Lagrange multipliers Their values must be since the displacement of the nodes at these points is already enforced by the boundary conditions imposed at the left and right vertical boundaries (boundaries 1 and 3)
boundary()
We pin the position of the nodes on all domain boundaries apart from the top boundary (boundary 2)
built()
We now create a new c SolidMesh in which we store the elements that apply the displacement constraint These elements are built (and added to the newly created \c SolidMesh)
multipliers()
cf<A HREF=`../../solid_theory/html/index.html#solid_node`> Solid the boundary is pulled upwards into a sinusoidal shape while simultaneously being pushed to the right The vectors in the animation represent the Lagrange multipliers (i.e. the physical surface tractions)
of()
namespace Global parameters As usual we define the problem parameters in a global namespace We provide an instantiation of the c GeomObject that defines the deformed boundary and create an instance of c oomph lib s generalised Hookean constitutive equation with a Poisson ratio of (recall that the use of the single-argument constructor for this constitutive equation implies that all stresses are non-dimensionalised on Young 's modulus \f$ E \f$;see< a href=`../../solid_theory/html/index.html#non-dim_solid`> the solid mechanics theory tutorial</a > for details)
pinned()
we assign the equation numbers and specify the output directory until end of constructor<HR><HR> section actions_before_adapt Actions before mesh adaptation As we remove the c FaceElements that apply the displacement constraints before the bulk mesh is adapted dontinclude prescribed_displ_lagr_mult cc skipline start_of_actions_before_adapt until end of actions_before_adapt<HR><HR> section actions_after_adapt Actions after mesh adaptation We re attach the c FaceElements that apply the displacement constraints once the bulk mesh has been adapted Since the hanging status of nodes in the bulk mesh can change during the mesh adaptation it is again good practice to pin any nodal solid pressure values that may have become redundant dontinclude prescribed_displ_lagr_mult cc skipline start_of_actions_after_adapt until end of actions_after_adapt<HR><HR> section lagr_elements Creating the Lagrange multiplier elements that impose the displacement constraint The creation of the Lagrange multiplier elements that impose the displacement constraint follows the usual pattern We loop over the bulk solid elements that are adjacent to mesh boundary and attach c ImposeDisplacementByLagrangeMultiplierElements to the appropriate faces dontinclude prescribed_displ_lagr_mult cc skipline start_of_create_lagrange_multiplier_elements until Next we loop over the newly created c ImposeDisplacementByLagrangeMultiplierElements and specify the c GeomObject that defines the imposed boundary displacements We also specify which boundary of the bulk mesh the c ImposeDisplacementByLagrangeMultiplierElements are located on This is required to enable the c ImposeDisplacementByLagrangeMultiplierElements to extract the appropriate boundary coordinate from its constituent nodes (We discussed <a href=`../../../poisson/fish_poisson2/html/index.html#boundary_coords`> elsewhere</a> that boundary coordinates are usually defined (and passed to the nodes) when the nodes are first created, typically during the construction of the bulk mesh. Since nodes can be located on multiple domain boundaries, each boundary coordinate is associated with a particular boundary number. Passing this number to the \c ImposeDisplacementByLagrangeMultiplierElements allows them to obtain the correct boundary coordinate from the node.) \until &Global_Physical_Variables we impose boundary conditions for the Lagrange multipliers Their values must be pinned (and set to zero)
shape()
namespace Global parameters As usual we define the problem parameters in a global namespace We provide an instantiation of the c GeomObject that defines the deformed boundary shape (setting its initial displacement amplitude to zero)
solid_mesh_pt()
We pin the position of the nodes on all domain boundaries apart from the top it is good practice to do this anyway to guard against unpleasant surprises when the element type is changed at some point until solid_mesh_pt () -> element_pt())
Referenced by PrescribedBoundaryDisplacementProblem< ELEMENT >::actions_after_adapt(), PrescribedBoundaryDisplacementProblem< ELEMENT >::actions_before_newton_solve(), PrescribedBoundaryDisplacementProblem< ELEMENT >::create_lagrange_multiplier_elements(), PrescribedBoundaryDisplacementProblem< ELEMENT >::doc_solution(), and PrescribedBoundaryDisplacementProblem< ELEMENT >::PrescribedBoundaryDisplacementProblem().
Variable Documentation
estimator
Next we specify the error estimator
Definition at line 261 of file prescribed_displ_lagr_mult.txt.
Finally
we assign the equation numbers and specify the output directory until end of constructor<HR><HR> section actions_before_adapt Actions before mesh adaptation As we remove the c FaceElements that apply the displacement constraints before the bulk mesh is adapted dontinclude prescribed_displ_lagr_mult cc skipline start_of_actions_before_adapt until end of actions_before_adapt<HR><HR> section actions_after_adapt Actions after mesh adaptation We re attach the c FaceElements that apply the displacement constraints once the bulk mesh has been adapted Since the hanging status of nodes in the bulk mesh can change during the mesh adaptation it is again good practice to pin any nodal solid pressure values that may have become redundant dontinclude prescribed_displ_lagr_mult cc skipline start_of_actions_after_adapt until end of actions_after_adapt<HR><HR> section lagr_elements Creating the Lagrange multiplier elements that impose the displacement constraint The creation of the Lagrange multiplier elements that impose the displacement constraint follows the usual pattern We loop over the bulk solid elements that are adjacent to mesh boundary and attach c ImposeDisplacementByLagrangeMultiplierElements to the appropriate faces dontinclude prescribed_displ_lagr_mult cc skipline start_of_create_lagrange_multiplier_elements until Next we loop over the newly created c ImposeDisplacementByLagrangeMultiplierElements and specify the c GeomObject that defines the imposed boundary displacements We also specify which boundary of the bulk mesh the c ImposeDisplacementByLagrangeMultiplierElements are located on This is required to enable the c ImposeDisplacementByLagrangeMultiplierElements to extract the appropriate boundary coordinate from its constituent nodes (We discussed <a href=`../../../poisson/fish_poisson2/html/index.html#boundary_coords`> elsewhere</a> that boundary coordinates are usually defined (and passed to the nodes) when the nodes are first created, typically during the construction of the bulk mesh. Since nodes can be located on multiple domain boundaries, each boundary coordinate is associated with a particular boundary number. Passing this number to the \c ImposeDisplacementByLagrangeMultiplierElements allows them to obtain the correct boundary coordinate from the node.) \until &Global_Physical_Variables Finally
Definition at line 284 of file prescribed_displ_lagr_mult.txt.
here
we assign the equation numbers and specify the output directory until end of constructor<HR><HR> section actions_before_adapt Actions before mesh adaptation As we remove the c FaceElements that apply the displacement constraints before the bulk mesh is adapted dontinclude prescribed_displ_lagr_mult cc skipline start_of_actions_before_adapt until end of actions_before_adapt<HR><HR> section actions_after_adapt Actions after mesh adaptation We re attach the c FaceElements that apply the displacement constraints once the bulk mesh has been adapted Since the hanging status of nodes in the bulk mesh can change during the mesh adaptation it is again good practice to pin any nodal solid pressure values that may have become redundant dontinclude prescribed_displ_lagr_mult cc skipline start_of_actions_after_adapt until end of actions_after_adapt<HR><HR> section lagr_elements Creating the Lagrange multiplier elements that impose the displacement constraint The creation of the Lagrange multiplier elements that impose the displacement constraint follows the usual pattern We loop over the bulk solid elements that are adjacent to mesh boundary and attach c ImposeDisplacementByLagrangeMultiplierElements to the appropriate faces dontinclude prescribed_displ_lagr_mult cc skipline start_of_create_lagrange_multiplier_elements until Next we loop over the newly created c ImposeDisplacementByLagrangeMultiplierElements and specify the c GeomObject that defines the imposed boundary displacements We also specify which boundary of the bulk mesh the c ImposeDisplacementByLagrangeMultiplierElements are located on This is required to enable the c ImposeDisplacementByLagrangeMultiplierElements to extract the appropriate boundary coordinate from its constituent nodes (We discussed <a href=`../../../poisson/fish_poisson2/html/index.html#boundary_coords`> elsewhere</a> that boundary coordinates are usually defined (and passed to the nodes) when the nodes are first created, typically during the construction of the bulk mesh. Since nodes can be located on multiple domain boundaries, each boundary coordinate is associated with a particular boundary number. Passing this number to the \c ImposeDisplacementByLagrangeMultiplierElements allows them to obtain the correct boundary coordinate from the node.) \until &Global_Physical_Variables we impose boundary conditions for the Lagrange multipliers Their values must be since the displacement of the nodes at these points is already enforced by the boundary conditions imposed at the left and right vertical used here
Definition at line 432 of file prescribed_displ_lagr_mult.txt.
l_x
<HR><HR> section constructor The Problem constructor We start by creating the bulk discretising the domain with elements of the type specified by the class s template argument dontinclude prescribed_displ_lagr_mult cc skipline start_of_constructor until l_x
Definition at line 259 of file prescribed_displ_lagr_mult.txt.
Referenced by PrescribedBoundaryDisplacementProblem< ELEMENT >::PrescribedBoundaryDisplacementProblem().
l_y
<HR><HR> section constructor The Problem constructor We start by creating the bulk discretising the domain with elements of the type specified by the class s template argument dontinclude prescribed_displ_lagr_mult cc skipline start_of_constructor until l_y
Definition at line 259 of file prescribed_displ_lagr_mult.txt.
Referenced by PrescribedBoundaryDisplacementProblem< ELEMENT >::PrescribedBoundaryDisplacementProblem().
mechanics
cf<A HREF=`../../solid_theory/html/index.html#solid_node`> Solid mechanics
Definition at line 144 of file prescribed_displ_lagr_mult.txt.
mesh
<HR><HR> section constructor The Problem constructor We start by creating the bulk mesh
Definition at line 254 of file prescribed_displ_lagr_mult.txt.
problem
mainpage Demo problem
Definition at line 5 of file prescribed_displ_lagr_mult.txt.
Referenced by main().
refinement
Next we specify the error pass the pointer to the constitutive equation to the elements and perform one uniform mesh refinement
Definition at line 264 of file prescribed_displ_lagr_mult.txt.
until
cf<A HREF=`../../solid_theory/html/index.html#solid_node`> Solid the boundary is pulled upwards into a sinusoidal shape while simultaneously being pushed to the right The vectors in the animation represent the Lagrange a two dimensional c GeomObject whose shape is parametrised by a single intrinsic coordinate dontinclude prescribed_displ_lagr_mult cc skipline Start_of_warped_line until
Definition at line 168 of file prescribed_displ_lagr_mult.txt.
usual
we assign the equation numbers and specify the output directory until end of constructor<HR><HR> section actions_before_adapt Actions before mesh adaptation As usual
Definition at line 295 of file prescribed_displ_lagr_mult.txt.