prescribed_displ_lagr_mult2.cc File Reference
Classes
class WarpedLine
Warped line in 2D space.
class PrescribedBoundaryDisplacementProblem< ELEMENT >
Problem class for deformation of elastic block by prescribed boundary motion.
Namespaces
namespace Global_Physical_Variables
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Functions
int main ()
Driver code.
Variables
WarpedLine Global_Physical_Variables::Boundary_geom_object (0.0)
GeomObject specifying the shape of the boundary: Initially it's flat.
Function Documentation
main()
int main ()
Driver code.
Definition at line 300 of file prescribed_displ_lagr_mult2.cc.
References WarpedLine::ampl(), Global_Physical_Variables::Boundary_geom_object, PrescribedBoundaryDisplacementProblem< ELEMENT >::doc_solution(), and PrescribedBoundaryDisplacementProblem< ELEMENT >::solid_mesh_pt().