EighthSpherePoissonProblem< ELEMENT > Class Template Reference
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Public Member Functions
EighthSpherePoissonProblem (PoissonEquations< 3 >::PoissonSourceFctPt source_fct_pt)
Constructor: Pass pointer to source function.
~EighthSpherePoissonProblem ()
Destructor: Empty.
RefineableEighthSphereMesh< ELEMENT > * mesh_pt ()
Overload generic access function by one that returns a pointer to the specific mesh.
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve: Set Dirchlet boundary conditions from exact solution.
void doc_solution (DocInfo &doc_info)
Doc the solution.
Private Attributes
PoissonEquations< 3 >::PoissonSourceFctPt Source_fct_pt
Pointer to source function.
Detailed Description
template<class ELEMENT>
class EighthSpherePoissonProblem< ELEMENT >
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Poisson problem in refineable eighth of a sphere mesh.
Definition at line 131 of file eighth_sphere_poisson.cc.
Constructor & Destructor Documentation
EighthSpherePoissonProblem()
template<class ELEMENT >
EighthSpherePoissonProblem< ELEMENT >::EighthSpherePoissonProblem (PoissonEquations< 3 >::PoissonSourceFctPt source_fct_pt)
Constructor: Pass pointer to source function.
Constructor for Poisson problem on eighth of a sphere mesh. Create mesh for sphere of radius 5
Definition at line 195 of file eighth_sphere_poisson.cc.
References TanhSolnForPoisson::Alpha, EighthSpherePoissonProblem< ELEMENT >::mesh_pt(), and EighthSpherePoissonProblem< ELEMENT >::Source_fct_pt.
 EighthSpherePoissonProblem()
template<class ELEMENT >
EighthSpherePoissonProblem< ELEMENT >::~EighthSpherePoissonProblem () [inline]
Destructor: Empty.
Definition at line 141 of file eighth_sphere_poisson.cc.
Member Function Documentation
actions_after_newton_solve()
template<class ELEMENT >
void EighthSpherePoissonProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the problem specs after solve (empty)
Definition at line 151 of file eighth_sphere_poisson.cc.
actions_before_newton_solve()
template<class ELEMENT >
void EighthSpherePoissonProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve: Set Dirchlet boundary conditions from exact solution.
Definition at line 155 of file eighth_sphere_poisson.cc.
References TanhSolnForPoisson::get_exact_u().
doc_solution()
template<class ELEMENT >
void EighthSpherePoissonProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 271 of file eighth_sphere_poisson.cc.
References TanhSolnForPoisson::get_exact_u().
Referenced by main().
mesh_pt()
template<class ELEMENT >
RefineableEighthSphereMesh<ELEMENT>* EighthSpherePoissonProblem< ELEMENT >::mesh_pt () [inline]
Overload generic access function by one that returns a pointer to the specific mesh.
Definition at line 145 of file eighth_sphere_poisson.cc.
Referenced by EighthSpherePoissonProblem< ELEMENT >::EighthSpherePoissonProblem(), and main().
Member Data Documentation
Source_fct_pt
template<class ELEMENT >
PoissonEquations<3>::PoissonSourceFctPt EighthSpherePoissonProblem< ELEMENT >::Source_fct_pt [private]
Pointer to source function.
Definition at line 183 of file eighth_sphere_poisson.cc.
Referenced by EighthSpherePoissonProblem< ELEMENT >::EighthSpherePoissonProblem().
The documentation for this class was generated from the following file:
eighth_sphere_poisson.cc