Global_Parameters Namespace Reference
Namespace for global parameters.
Functions
void boundary_traction (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &result)
The traction function at r=Rmin: (t_r, t_z, t_theta)
void body_force (const double &time, const Vector< double > &x, Vector< double > &result)
The body force function; returns vector of doubles in the order (b_r, b_z, b_theta)
void exact_solution_th (const Vector< double > &x, Vector< double > &u)
Helper function - spatial components of the exact solution in a vector. This is necessary because we need to multiply this by different things to obtain the velocity and acceleration 0: u_r, 1: u_z, 2: u_theta.
double u_r (const double &time, const Vector< double > &x)
Calculate the time dependent form of the r-component of displacement.
double u_z (const double &time, const Vector< double > &x)
Calculate the time dependent form of the z-component of displacement.
double u_theta (const double &time, const Vector< double > &x)
Calculate the time dependent form of the theta-component of displacement.
double d_u_r_dt (const double &time, const Vector< double > &x)
Calculate the time dependent form of the r-component of velocity.
double d_u_z_dt (const double &time, const Vector< double > &x)
Calculate the time dependent form of the z-component of velocity.
double d_u_theta_dt (const double &time, const Vector< double > &x)
Calculate the time dependent form of the theta-component of velocity.
double d2_u_r_dt2 (const double &time, const Vector< double > &x)
Calculate the time dependent form of the r-component of acceleration.
double d2_u_z_dt2 (const double &time, const Vector< double > &x)
Calculate the time dependent form of the z-component of acceleration.
double d2_u_theta_dt2 (const double &time, const Vector< double > &x)
Calculate the time dependent form of the theta-component of acceleration.
void exact_solution (const double &time, const Vector< double > &x, Vector< double > &u)
The exact solution in a vector: 0: u_r, 1: u_z, 2: u_theta and their 1st and 2nd derivs.
Variables
double Nu = 0.3
Define Poisson's ratio Nu.
double E = 1.0
Define the non-dimensional Young's modulus.
double Lambda = E*Nu/(1.0+Nu)/(1.0-2.0*Nu)
Lame parameters.
double Mu = E/2.0/(1.0+Nu)
double Omega_sq = 0.5
Square of the frequency of the time dependence.
unsigned Nr = 5
Number of elements in r-direction.
unsigned Nz = 10
Number of elements in z-direction.
double Lr = 1.0
Length of domain in r direction.
double Lz = 2.0
Length of domain in z-direction.
double Rmin = 0.1
Set up min r coordinate.
double Zmin = 0.3
Set up min z coordinate.
double Rmax = Rmin+Lr
Set up max r coordinate.
double Zmax = Zmin+Lz
Set up max z coordinate.
Detailed Description
Namespace for global parameters.
Function Documentation
body_force()
void Global_Parameters::body_force (const double & time, const Vector< double > & x, Vector< double > & result)
The body force function; returns vector of doubles in the order (b_r, b_z, b_theta)
Definition at line 96 of file cylinder.cc.
References Lambda, Mu, and Omega_sq.
Referenced by AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::AxisymmetricLinearElasticityProblem().
boundary_traction()
void Global_Parameters::boundary_traction (const double & time, const Vector< double > & x, const Vector< double > & n, Vector< double > & result)
The traction function at r=Rmin: (t_r, t_z, t_theta)
Definition at line 83 of file cylinder.cc.
References Lambda, and Mu.
Referenced by AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::AxisymmetricLinearElasticityProblem().
d2_u_r_dt2()
double Global_Parameters::d2_u_r_dt2 (const double & time, const Vector< double > & x)
Calculate the time dependent form of the r-component of acceleration.
Definition at line 178 of file cylinder.cc.
References exact_solution_th().
Referenced by exact_solution(), AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions(), and AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_initial_conditions().
d2_u_theta_dt2()
double Global_Parameters::d2_u_theta_dt2 (const double & time, const Vector< double > & x)
Calculate the time dependent form of the theta-component of acceleration.
Definition at line 194 of file cylinder.cc.
References exact_solution_th().
Referenced by exact_solution(), AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions(), and AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_initial_conditions().
d2_u_z_dt2()
double Global_Parameters::d2_u_z_dt2 (const double & time, const Vector< double > & x)
Calculate the time dependent form of the z-component of acceleration.
Definition at line 186 of file cylinder.cc.
References exact_solution_th().
Referenced by exact_solution(), AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions(), and AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_initial_conditions().
d_u_r_dt()
double Global_Parameters::d_u_r_dt (const double & time, const Vector< double > & x)
Calculate the time dependent form of the r-component of velocity.
Definition at line 154 of file cylinder.cc.
References exact_solution_th().
Referenced by exact_solution(), AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions(), and AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_initial_conditions().
d_u_theta_dt()
double Global_Parameters::d_u_theta_dt (const double & time, const Vector< double > & x)
Calculate the time dependent form of the theta-component of velocity.
Definition at line 170 of file cylinder.cc.
References exact_solution_th().
Referenced by exact_solution(), AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions(), and AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_initial_conditions().
d_u_z_dt()
double Global_Parameters::d_u_z_dt (const double & time, const Vector< double > & x)
Calculate the time dependent form of the z-component of velocity.
Definition at line 162 of file cylinder.cc.
References exact_solution_th().
Referenced by exact_solution(), AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions(), and AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_initial_conditions().
exact_solution()
void Global_Parameters::exact_solution (const double & time, const Vector< double > & x, Vector< double > & u)
The exact solution in a vector: 0: u_r, 1: u_z, 2: u_theta and their 1st and 2nd derivs.
Definition at line 203 of file cylinder.cc.
References d2_u_r_dt2(), d2_u_theta_dt2(), d2_u_z_dt2(), d_u_r_dt(), d_u_theta_dt(), d_u_z_dt(), u_r(), u_theta(), and u_z().
Referenced by AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::doc_solution(), and AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions().
exact_solution_th()
void Global_Parameters::exact_solution_th (const Vector< double > & x, Vector< double > & u)
Helper function - spatial components of the exact solution in a vector. This is necessary because we need to multiply this by different things to obtain the velocity and acceleration 0: u_r, 1: u_z, 2: u_theta.
Definition at line 116 of file cylinder.cc.
Referenced by d2_u_r_dt2(), d2_u_theta_dt2(), d2_u_z_dt2(), d_u_r_dt(), d_u_theta_dt(), d_u_z_dt(), u_r(), u_theta(), and u_z().
u_r()
double Global_Parameters::u_r (const double & time, const Vector< double > & x)
Calculate the time dependent form of the r-component of displacement.
Definition at line 130 of file cylinder.cc.
References exact_solution_th().
Referenced by exact_solution(), AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions(), and AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_initial_conditions().
u_theta()
double Global_Parameters::u_theta (const double & time, const Vector< double > & x)
Calculate the time dependent form of the theta-component of displacement.
Definition at line 146 of file cylinder.cc.
References exact_solution_th().
Referenced by exact_solution(), AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions(), and AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_initial_conditions().
u_z()
double Global_Parameters::u_z (const double & time, const Vector< double > & x)
Calculate the time dependent form of the z-component of displacement.
Definition at line 138 of file cylinder.cc.
References exact_solution_th().
Referenced by exact_solution(), AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions(), and AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::set_initial_conditions().
Variable Documentation
E
double Global_Parameters::E = 1.0
Define the non-dimensional Young's modulus.
Definition at line 49 of file cylinder.cc.
Referenced by AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::AxisymmetricLinearElasticityProblem().
Lambda
double Global_Parameters::Lambda = E*Nu/(1.0+Nu)/(1.0-2.0*Nu)
Lame parameters.
Definition at line 52 of file cylinder.cc.
Referenced by body_force(), and boundary_traction().
Lr
double Global_Parameters::Lr = 1.0
Length of domain in r direction.
Definition at line 65 of file cylinder.cc.
Lz
double Global_Parameters::Lz = 2.0
Length of domain in z-direction.
Definition at line 68 of file cylinder.cc.
Mu
double Global_Parameters::Mu = E/2.0/(1.0+Nu)
Definition at line 53 of file cylinder.cc.
Referenced by body_force(), and boundary_traction().
Nr
unsigned Global_Parameters::Nr = 5
Number of elements in r-direction.
Definition at line 59 of file cylinder.cc.
Referenced by AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::AxisymmetricLinearElasticityProblem().
Nu
double Global_Parameters::Nu = 0.3
Define Poisson's ratio Nu.
Definition at line 46 of file cylinder.cc.
Referenced by AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::AxisymmetricLinearElasticityProblem().
Nz
unsigned Global_Parameters::Nz = 10
Number of elements in z-direction.
Definition at line 62 of file cylinder.cc.
Referenced by AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::AxisymmetricLinearElasticityProblem().
Omega_sq
double Global_Parameters::Omega_sq = 0.5
Square of the frequency of the time dependence.
Definition at line 56 of file cylinder.cc.
Referenced by AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::AxisymmetricLinearElasticityProblem(), and body_force().
Rmax
double Global_Parameters::Rmax = Rmin+Lr
Set up max r coordinate.
Definition at line 77 of file cylinder.cc.
Referenced by AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::AxisymmetricLinearElasticityProblem().
Rmin
double Global_Parameters::Rmin = 0.1
Set up min r coordinate.
Definition at line 71 of file cylinder.cc.
Referenced by AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::AxisymmetricLinearElasticityProblem().
Zmax
double Global_Parameters::Zmax = Zmin+Lz
Set up max z coordinate.
Definition at line 80 of file cylinder.cc.
Referenced by AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::AxisymmetricLinearElasticityProblem().
Zmin
double Global_Parameters::Zmin = 0.3
Set up min z coordinate.
Definition at line 74 of file cylinder.cc.
Referenced by AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::AxisymmetricLinearElasticityProblem().