GlobalPhysicalParameters Namespace Reference
Namespace for global parameters: Unforced problem with boundary values corresponding to a steep tanh step profile oriented at 45 degrees across the domain.
Functions
void get_boundary_values (const Vector< double > &x, Vector< double > &u)
Some `solution` for assignment of boundary values.
void source_function (const Vector< double > &x_vect, double &source)
Zero source function.
void wind_function (const Vector< double > &x, Vector< double > &wind)
Wind.
Variables
double Peclet =200.0
Peclet number.
double Alpha =50.0
Parameter for steepness of step in boundary values.
double TanPhi =1.0
Parameter for angle of step in boundary values: 45 degrees.
Detailed Description
Namespace for global parameters: Unforced problem with boundary values corresponding to a steep tanh step profile oriented at 45 degrees across the domain.
Function Documentation
get_boundary_values()
void GlobalPhysicalParameters::get_boundary_values (const Vector< double > & x, Vector< double > & u)
Some `solution` for assignment of boundary values.
Definition at line 61 of file two_d_adv_diff_SUPG.cc.
References Alpha, and TanPhi.
Referenced by SUPGAdvectionDiffusionProblem< ELEMENT >::actions_before_newton_solve().
source_function()
void GlobalPhysicalParameters::source_function (const Vector< double > & x_vect, double & source)
Zero source function.
Definition at line 67 of file two_d_adv_diff_SUPG.cc.
Referenced by main().
wind_function()
void GlobalPhysicalParameters::wind_function (const Vector< double > & x, Vector< double > & wind)
Wind.
Definition at line 73 of file two_d_adv_diff_SUPG.cc.
Referenced by main().
Variable Documentation
Alpha
double GlobalPhysicalParameters::Alpha =50.0
Parameter for steepness of step in boundary values.
Definition at line 55 of file two_d_adv_diff_SUPG.cc.
Referenced by get_boundary_values().
Peclet
double GlobalPhysicalParameters::Peclet =200.0
Peclet number.
Definition at line 52 of file two_d_adv_diff_SUPG.cc.
Referenced by SUPGAdvectionDiffusionProblem< ELEMENT >::SUPGAdvectionDiffusionProblem().
TanPhi
double GlobalPhysicalParameters::TanPhi =1.0
Parameter for angle of step in boundary values: 45 degrees.
Definition at line 58 of file two_d_adv_diff_SUPG.cc.
Referenced by get_boundary_values().