two_d_adv_diff_SUPG.cc File Reference
Classes
class SUPGAdvectionDiffusionProblem< ELEMENT >
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
Namespaces
 GlobalPhysicalParameters
Namespace for global parameters: Unforced problem with boundary values corresponding to a steep tanh step profile oriented at 45 degrees across the domain.
Functions
void GlobalPhysicalParameters::get_boundary_values (const Vector< double > &x, Vector< double > &u)
Some `solution` for assignment of boundary values.
void GlobalPhysicalParameters::source_function (const Vector< double > &x_vect, double &source)
Zero source function.
void GlobalPhysicalParameters::wind_function (const Vector< double > &x, Vector< double > &wind)
Wind.
int main ()
Driver code for 2D AdvectionDiffusion problem.
Variables
double GlobalPhysicalParameters::Peclet =200.0
Peclet number.
double GlobalPhysicalParameters::Alpha =50.0
Parameter for steepness of step in boundary values.
double GlobalPhysicalParameters::TanPhi =1.0
Parameter for angle of step in boundary values: 45 degrees.
Function Documentation
main()
int main ()
Driver code for 2D AdvectionDiffusion problem.
Definition at line 317 of file two_d_adv_diff_SUPG.cc.
References SUPGAdvectionDiffusionProblem< ELEMENT >::doc_solution(), GlobalPhysicalParameters::source_function(), and GlobalPhysicalParameters::wind_function().