ChannelSpineFlowProblem< ELEMENT > Class Template Reference
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Public Member Functions
ChannelSpineFlowProblem ()
Constructor.
~ChannelSpineFlowProblem ()
Destructor: (empty)
void actions_before_newton_solve ()
Update the problem specs before solve. Update the nodal positions.
void actions_after_newton_solve ()
Update the after solve (empty)
void doc_solution (DocInfo &doc_info)
Doc the solution.
SimpleSpineMesh< ELEMENT > * mesh_pt ()
Overload access to mesh.
ChannelSpineFlowProblem ()
Constructor.
~ChannelSpineFlowProblem ()
Destructor: (empty)
void actions_before_newton_solve ()
Update the problem specs before solve. Set velocity boundary conditions just to be on the safe side...
void actions_after_newton_solve ()
Update the after solve (empty)
void doc_solution (DocInfo &doc_info)
Doc the solution.
Private Attributes
double Ly
Width of channel.
Detailed Description
template<class ELEMENT>
class ChannelSpineFlowProblem< ELEMENT >
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////
Channel flow through a non-uniform channel whose geometry is defined by a spine mesh.
//////////////////////////////////////////////////////////////////// Geometric object representing a sinusoidal wall, parametrised by
 x = \zeta 
 //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Channel flow through a non-uniform channel whose geometry is defined by a spine mesh.
Definition at line 458 of file simple_spine_channel.cc.
Constructor & Destructor Documentation
ChannelSpineFlowProblem() [1/2]
template<class ELEMENT >
ChannelSpineFlowProblem< ELEMENT >::ChannelSpineFlowProblem
Constructor.
Constructor for ChannelSpineFlow problem.
Definition at line 505 of file simple_spine_channel.cc.
References Global_Physical_Variables::H, Global_Physical_Variables::height(), Global_Physical_Variables::L_total, and Global_Physical_Variables::Re.
 ChannelSpineFlowProblem() [1/2]
template<class ELEMENT >
ChannelSpineFlowProblem< ELEMENT >::~ChannelSpineFlowProblem () [inline]
Destructor: (empty)
Definition at line 467 of file simple_spine_channel.cc.
ChannelSpineFlowProblem() [2/2]
template<class ELEMENT >
ChannelSpineFlowProblem< ELEMENT >::ChannelSpineFlowProblem ()
Constructor.
 ChannelSpineFlowProblem() [2/2]
template<class ELEMENT >
ChannelSpineFlowProblem< ELEMENT >::~ChannelSpineFlowProblem () [inline]
Destructor: (empty)
Definition at line 322 of file spine_channel.cc.
Member Function Documentation
actions_after_newton_solve() [1/2]
template<class ELEMENT >
void ChannelSpineFlowProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the after solve (empty)
Definition at line 479 of file simple_spine_channel.cc.
actions_after_newton_solve() [2/2]
template<class ELEMENT >
void ChannelSpineFlowProblem< ELEMENT >::actions_after_newton_solve () [inline]
Update the after solve (empty)
Definition at line 335 of file spine_channel.cc.
actions_before_newton_solve() [1/2]
template<class ELEMENT >
void ChannelSpineFlowProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve. Update the nodal positions.
Definition at line 471 of file simple_spine_channel.cc.
References ChannelSpineFlowProblem< ELEMENT >::mesh_pt().
actions_before_newton_solve() [2/2]
template<class ELEMENT >
void ChannelSpineFlowProblem< ELEMENT >::actions_before_newton_solve () [inline]
Update the problem specs before solve. Set velocity boundary conditions just to be on the safe side...
Definition at line 326 of file spine_channel.cc.
References ChannelSpineFlowProblem< ELEMENT >::mesh_pt().
doc_solution() [1/2]
template<class ELEMENT >
void ChannelSpineFlowProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 631 of file simple_spine_channel.cc.
Referenced by main().
doc_solution() [2/2]
template<class ELEMENT >
void ChannelSpineFlowProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
mesh_pt()
template<class ELEMENT >
SimpleSpineMesh< ELEMENT > * ChannelSpineFlowProblem< ELEMENT >::mesh_pt () [inline]
Overload access to mesh.
Definition at line 485 of file simple_spine_channel.cc.
Referenced by ChannelSpineFlowProblem< ELEMENT >::actions_before_newton_solve().
Member Data Documentation
Ly
template<class ELEMENT >
double ChannelSpineFlowProblem< ELEMENT >::Ly [private]
Width of channel.
Definition at line 494 of file simple_spine_channel.cc.
The documentation for this class was generated from the following files:
simple_spine_channel.cc
spine_channel.cc