ElasticRefineableTwoLayerMesh< ELEMENT > Class Template Reference
Two layer mesh which employs a pseudo-solid node-update strategy. This class is essentially a wrapper to an ElasticRefineableRectangularQuadMesh, with an additional boundary to represent the interface between the two fluid layers.
Public Member Functions
ElasticRefineableTwoLayerMesh (const unsigned &nx, const unsigned &ny1, const unsigned &ny2, const double &lx, const double &h1, const double &h2, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass number of elements in x-direction, number of elements in y-direction in bottom and top layer, respectively, axial length and height of top and bottom layers, and pointer to timestepper (defaults to Steady timestepper)
Detailed Description
template<class ELEMENT>
class ElasticRefineableTwoLayerMesh< ELEMENT >
Two layer mesh which employs a pseudo-solid node-update strategy. This class is essentially a wrapper to an ElasticRefineableRectangularQuadMesh, with an additional boundary to represent the interface between the two fluid layers.
Definition at line 106 of file elastic_two_layer_interface_axisym.cc.
Constructor & Destructor Documentation
ElasticRefineableTwoLayerMesh()
template<class ELEMENT >
ElasticRefineableTwoLayerMesh< ELEMENT >::ElasticRefineableTwoLayerMesh (const unsigned & nx, const unsigned & ny1, const unsigned & ny2, const double & lx, const double & h1, const double & h2, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Pass number of elements in x-direction, number of elements in y-direction in bottom and top layer, respectively, axial length and height of top and bottom layers, and pointer to timestepper (defaults to Steady timestepper)
Definition at line 116 of file elastic_two_layer_interface_axisym.cc.
Referenced by InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_after_adapt(), InterfaceProblem< ELEMENT, TIMESTEPPER >::deform_free_surface(), InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem(), and main().
The documentation for this class was generated from the following file:
elastic_two_layer_interface_axisym.cc