WarpedLine Class Reference
Warped line in 2D space.
Public Member Functions
WarpedLine (const double &ampl)
Constructor: Specify amplitude of deflection from straight horizontal line.
WarpedLine (const WarpedLine &dummy)
Broken copy constructor.
void operator= (const WarpedLine &)
Broken assignment operator.
~WarpedLine ()
Empty Destructor.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Forward to steady version.
double & ampl ()
Access to amplitude.
unsigned ngeom_data () const
How many items of Data does the shape of the object depend on? None.
WarpedLine (const double &ampl)
Constructor: Specify amplitude of deflection from straight horizontal line.
WarpedLine (const WarpedLine &dummy)
Broken copy constructor.
void operator= (const WarpedLine &)
Broken assignment operator.
~WarpedLine ()
Empty Destructor.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Forward to steady version.
double & ampl ()
Access to amplitude.
WarpedLine (const double &ampl)
Constructor: Specify amplitude of deflection from straight horizontal line.
WarpedLine (const WarpedLine &dummy)
Broken copy constructor.
void operator= (const WarpedLine &)
Broken assignment operator.
~WarpedLine ()
Empty Destructor.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Forward to steady version.
double & ampl ()
Access to amplitude.
unsigned ngeom_data () const
How many items of Data does the shape of the object depend on? None.
Private Attributes
double Ampl
Amplitude of perturbation.
Detailed Description
Warped line in 2D space.
Definition at line 66 of file prescribed_displ_lagr_mult.cc.
Constructor & Destructor Documentation
WarpedLine() [1/6]
WarpedLine::WarpedLine (const double & ampl) [inline]
Constructor: Specify amplitude of deflection from straight horizontal line.
Definition at line 72 of file prescribed_displ_lagr_mult.cc.
References ampl(), and Ampl.
WarpedLine() [2/6]
WarpedLine::WarpedLine (const WarpedLine & dummy) [inline]
Broken copy constructor.
Definition at line 78 of file prescribed_displ_lagr_mult.cc.
 WarpedLine() [1/3]
WarpedLine::~WarpedLine () [inline]
Empty Destructor.
Definition at line 91 of file prescribed_displ_lagr_mult.cc.
WarpedLine() [3/6]
WarpedLine::WarpedLine (const double & ampl) [inline]
Constructor: Specify amplitude of deflection from straight horizontal line.
Definition at line 51 of file prescribed_displ_lagr_mult2.cc.
References ampl(), and Ampl.
WarpedLine() [4/6]
WarpedLine::WarpedLine (const WarpedLine & dummy) [inline]
Broken copy constructor.
Definition at line 57 of file prescribed_displ_lagr_mult2.cc.
 WarpedLine() [2/3]
WarpedLine::~WarpedLine () [inline]
Empty Destructor.
Definition at line 70 of file prescribed_displ_lagr_mult2.cc.
WarpedLine() [5/6]
WarpedLine::WarpedLine (const double & ampl) [inline]
Constructor: Specify amplitude of deflection from straight horizontal line.
Definition at line 219 of file prescribed_displ_lagr_mult_precond.cc.
References ampl(), and Ampl.
WarpedLine() [6/6]
WarpedLine::WarpedLine (const WarpedLine & dummy) [inline]
Broken copy constructor.
Definition at line 225 of file prescribed_displ_lagr_mult_precond.cc.
 WarpedLine() [3/3]
WarpedLine::~WarpedLine () [inline]
Empty Destructor.
Definition at line 238 of file prescribed_displ_lagr_mult_precond.cc.
Member Function Documentation
ampl() [1/3]
double & WarpedLine::ampl () [inline]
Access to amplitude.
Definition at line 111 of file prescribed_displ_lagr_mult.cc.
References Ampl.
Referenced by main(), and WarpedLine().
ampl() [2/3]
double & WarpedLine::ampl () [inline]
Access to amplitude.
Definition at line 90 of file prescribed_displ_lagr_mult2.cc.
References Ampl.
ampl() [3/3]
double & WarpedLine::ampl () [inline]
Access to amplitude.
Definition at line 258 of file prescribed_displ_lagr_mult_precond.cc.
References Ampl.
ngeom_data() [1/2]
unsigned WarpedLine::ngeom_data () const [inline]
How many items of Data does the shape of the object depend on? None.
Definition at line 115 of file prescribed_displ_lagr_mult.cc.
ngeom_data() [2/2]
unsigned WarpedLine::ngeom_data () const [inline]
How many items of Data does the shape of the object depend on? None.
Definition at line 262 of file prescribed_displ_lagr_mult_precond.cc.
operator=() [1/3]
void WarpedLine::operator= (const WarpedLine &) [inline]
Broken assignment operator.
Definition at line 84 of file prescribed_displ_lagr_mult.cc.
operator=() [2/3]
void WarpedLine::operator= (const WarpedLine &) [inline]
Broken assignment operator.
Definition at line 63 of file prescribed_displ_lagr_mult2.cc.
operator=() [3/3]
void WarpedLine::operator= (const WarpedLine &) [inline]
Broken assignment operator.
Definition at line 231 of file prescribed_displ_lagr_mult_precond.cc.
position() [1/6]
void WarpedLine::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const [inline]
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Forward to steady version.
Definition at line 104 of file prescribed_displ_lagr_mult.cc.
References position().
position() [2/6]
void WarpedLine::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const [inline]
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Forward to steady version.
Definition at line 83 of file prescribed_displ_lagr_mult2.cc.
References position().
position() [3/6]
void WarpedLine::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const [inline]
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Forward to steady version.
Definition at line 251 of file prescribed_displ_lagr_mult_precond.cc.
References position().
position() [4/6]
void WarpedLine::position (const Vector< double > & zeta, Vector< double > & r) const [inline]
Position vector at Lagrangian coordinate zeta.
Definition at line 94 of file prescribed_displ_lagr_mult.cc.
References Ampl.
Referenced by PrescribedBoundaryDisplacementProblem< ELEMENT >::actions_before_newton_solve(), and position().
position() [5/6]
void WarpedLine::position (const Vector< double > & zeta, Vector< double > & r) const [inline]
Position vector at Lagrangian coordinate zeta.
Definition at line 73 of file prescribed_displ_lagr_mult2.cc.
References Ampl.
position() [6/6]
void WarpedLine::position (const Vector< double > & zeta, Vector< double > & r) const [inline]
Position vector at Lagrangian coordinate zeta.
Definition at line 241 of file prescribed_displ_lagr_mult_precond.cc.
References Ampl.
Member Data Documentation
Ampl
double WarpedLine::Ampl [private]
Amplitude of perturbation.
Definition at line 123 of file prescribed_displ_lagr_mult.cc.
Referenced by ampl(), position(), and WarpedLine().
The documentation for this class was generated from the following files:
prescribed_displ_lagr_mult.cc
prescribed_displ_lagr_mult2.cc
prescribed_displ_lagr_mult_precond.cc