prescribed_displ_lagr_mult.cc File Reference
Classes
class FiniteElementComp
Function-type-object to compare finite elements based on their x coordinate.
class WarpedLine
Warped line in 2D space.
class PrescribedBoundaryDisplacementProblem< ELEMENT >
Problem class for deformation of elastic block by prescribed boundary motion.
Namespaces
 Global_Physical_Variables
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Functions
int main ()
Driver code.
Variables
WarpedLine Global_Physical_Variables::Boundary_geom_object (0.0)
GeomObject specifying the shape of the boundary: Initially it's flat.
double Global_Physical_Variables::Nu =0.3
Poisson's ratio.
Function Documentation
main()
int main ()
Driver code.
Definition at line 484 of file prescribed_displ_lagr_mult.cc.
References WarpedLine::ampl(), Global_Physical_Variables::Boundary_geom_object, PrescribedBoundaryDisplacementProblem< ELEMENT >::doc_solution(), and PrescribedBoundaryDisplacementProblem< ELEMENT >::solid_mesh_pt().