unstructured_2d_biharmonic_curvedelement.cc File Reference
#include `generic.h`
#include `meshes/one_d_mesh.h`
#include `meshes/simple_rectangular_tri_mesh.h`
#include `meshes/simple_rectangular_quadmesh.h`
#include `generic/geom_objects.h`
#include `meshes/triangle_mesh.h`
Classes
class oomph::MyBiharmonicEquations< DIM, NNODE_1D >
class oomph::BiharmonicCurvedElement< DIM, NNODE_1D >
class oomph::FaceGeometry< BiharmonicCurvedElement< DIM, NNODE_1D > >
class MyBiharmonicProblem< ELEMENT, DIM, NNODE_1D >
2D Biharmonic problem.
Namespaces
 oomph
 Physical_Variables
Namespace for the solution of 2D Biharmonic equation.
Macros
#define OOMPH_BIHARMONIC_CURVED_ELEMENTS_HEADER
Functions
void Physical_Variables::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void Physical_Variables::source_function (const Vector< double > &x, double &source)
Source function required to make the above exact solution.
int main (int argc, char *argv[])
Driver for 2D Biharmonic problem.
Macro Definition Documentation
OOMPH_BIHARMONIC_CURVED_ELEMENTS_HEADER
#define OOMPH_BIHARMONIC_CURVED_ELEMENTS_HEADER
Definition at line 50 of file unstructured_2d_biharmonic_curvedelement.cc.
Function Documentation
main()
int main (int argc, char * argv[])
Driver for 2D Biharmonic problem.
Definition at line 1587 of file unstructured_2d_biharmonic_curvedelement.cc.
References MyBiharmonicProblem< ELEMENT, DIM, NNODE_1D >::doc_solution(), Physical_Variables::get_exact_u(), and Physical_Variables::source_function().