elastic_poisson.cc File Reference
Classes
class ElasticFishBackElement
Fish back as a GeneralisedElement: Circular ring whose position is given by.
class RefineableFishPoissonProblem< ELEMENT >
Refineable Poisson problem in deformable fish-shaped domain. Template parameter identify the elements.
Namespaces
namespace ConstSourceForPoisson
Namespace for const source term in Poisson equation.
Functions
void ConstSourceForPoisson::get_source (const Vector< double > &x, double &source)
Const source function.
template<class ELEMENT >
void demo_fish_poisson (const string &directory_name)
Demonstrate how to solve 2D Poisson problem in deformable fish-shaped domain with mesh adaptation.
template<class ELEMENT >
void demo_elastic_fish_poisson (const string &directory_name)
Demonstrate how to solve "elastic" 2D Poisson problem in deformable fish-shaped domain with mesh adaptation.
int main (int argc, char *argv[])
Driver for "elastic" fish poisson solver with adaptation. If there are any command line arguments, we regard this as a validation run and perform only a single step.
Variables
double ConstSourceForPoisson::Strength =1.0
Strength of source function: default value 1.0.
Function Documentation
demo_elastic_fish_poisson()
template<class ELEMENT >
void demo_elastic_fish_poisson (const string & directory_name)
Demonstrate how to solve "elastic" 2D Poisson problem in deformable fish-shaped domain with mesh adaptation.
Definition at line 576 of file elastic_poisson.cc.
References RefineableFishPoissonProblem< ELEMENT >::doc_solution(), RefineableFishPoissonProblem< ELEMENT >::fish_mesh_pt(), and RefineableFishPoissonProblem< ELEMENT >::load().
demo_fish_poisson()
template<class ELEMENT >
void demo_fish_poisson (const string & directory_name)
Demonstrate how to solve 2D Poisson problem in deformable fish-shaped domain with mesh adaptation.
Definition at line 527 of file elastic_poisson.cc.
References RefineableFishPoissonProblem< ELEMENT >::doc_info(), RefineableFishPoissonProblem< ELEMENT >::doc_solution(), RefineableFishPoissonProblem< ELEMENT >::fish_mesh_pt(), and RefineableFishPoissonProblem< ELEMENT >::load().
Referenced by main().
main()
int main (int argc, char * argv[])
Driver for "elastic" fish poisson solver with adaptation. If there are any command line arguments, we regard this as a validation run and perform only a single step.
Definition at line 611 of file elastic_poisson.cc.
References demo_fish_poisson().