ElasticCollapsibleChannelMesh< ELEMENT > Class Template Reference
Upgrade mesh to solid mesh.
Public Member Functions
ElasticCollapsibleChannelMesh (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly, GeomObject *wall_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Build mesh and copy Eulerian coords to Lagrangian ones so that the initial configuration is the stress-free one.
Detailed Description
template<class ELEMENT>
class ElasticCollapsibleChannelMesh< ELEMENT >
Upgrade mesh to solid mesh.
Definition at line 49 of file fsi_pseudo_solid_collapsible_channel.cc.
Constructor & Destructor Documentation
ElasticCollapsibleChannelMesh()
template<class ELEMENT >
ElasticCollapsibleChannelMesh< ELEMENT >::ElasticCollapsibleChannelMesh (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly, GeomObject * wall_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) [inline]
Constructor: Build mesh and copy Eulerian coords to Lagrangian ones so that the initial configuration is the stress-free one.
Make the current configuration the undeformed one by setting the nodal Lagrangian coordinates to their current Eulerian ones
Definition at line 1017 of file fsi_pseudo_solid_collapsible_channel.cc.
References ElasticCollapsibleChannelMesh< ELEMENT >::ElasticCollapsibleChannelMesh(), Global_Physical_Variables::P_ext, and Global_Physical_Variables::P_up.
Referenced by FSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_convergence_check(), ElasticCollapsibleChannelMesh< ELEMENT >::ElasticCollapsibleChannelMesh(), and ElasticRefineableCollapsibleChannelMesh< ELEMENT >::ElasticRefineableCollapsibleChannelMesh().
The documentation for this class was generated from the following file:
fsi_pseudo_solid_collapsible_channel.cc