elastic_annulus.txt File Reference
Typedefs
using T = \frac{1}{\omega} \f$, and use Young 's modulus to non-dimensionalise the body force and the stress tensor:< CENTER > \f[\pmb{\tau}^ *=E \, \pmb{\tau}, \qquad x_{i}^ *={\cal L}\, x_{i} \f] \f[\mathbf{u}^ *={\cal L}\, \mathbf{u}, \qquad \mathbf{F}^ *=\frac{E}{\rho \cal L} \, \mathbf{F}, \qquad t^ *={\cal T}\, t. \f]</CENTER > The non-dimensional form of the equations is then given by< CENTER > \f[\pmb{\nabla}\cdot\pmb{\tau}+\mathbf{F}=-\Omega^2\mathbf{u}, \ \ \ \ \ \ \ \ \ \ @E[nondimeqn]@ \f]</CENTER > with the non-dimensional constitutive relation,< CENTER > \f[\pmb{\tau}=\frac{1}{1+\nu}\left(\frac{\nu}{1-2\nu}(\pmb{\nabla}\cdot\mathbf{u})\textbf{I}+\frac{1}{2}(\pmb{\nabla}\mathbf{u}+\pmb{\nabla}\mathbf{u}^{{\rm T}})\right). \ \ \ \ \ \ \ \ \ \ @E[nondimconstitutive]@ \f]</CENTER > The non-dimensional parameter< CENTER > \f[\Omega={\cal L}\omega \sqrt{\frac{\rho}{E}} \f]</CENTER > is the ratio of the elastic body 's intrinsic timescale, \f$\displaystyle {\cal L} \sqrt{\frac{\rho}{E}}\f$, to the problem-specific timescale,\f$ \displaystyle {\cal T}=\frac{1}{\omega} \f$, that we used to non-dimensionalise time. \f$ \Omega \f$ can be interpreted as a non-dimensional version of the excitation frequency
using Omega = 10 \f$, \f$ \nu=0.3 \f$, \f$ P_0=0.3 \f$, \f$ r_{\rm min}=1\f$ and \f$ r_{\rm max}=1.5 \f$. @I w 0.8\textwidth re_ux `Real part of the horizontal displacement. Green: exact
Functions
alternatively equivalently f Omega f may be interpreted as a non dimensional density The boundary conditions are< CENTER > f[\mathbf{u}=\mathbf{\hat{u}}\,\,\textrm{on $\partial D_d $ },\quad\pmb{\tau} \cdot {\mathbf{n}}=\pmb{\hat{\tau}}\,\,\textrm{on $\partial D_n $ }.\f]</CENTER >< HR >< HR > section element_types Implementation Within c oomph the non dimensional version of equations (@R[nondimeqn]@) with the const itutive equations(@R[nondimconstitutive]@) are implemented in the \c TimeHarmonicLinearElasticityEquations< DIM > equations class
alternatively equivalently f Omega f may be interpreted as a non dimensional density The boundary conditions are< CENTER > f[\mathbf{u}=\mathbf{\hat{u}}\,\,\textrm{on $\partial D_d $ },\quad\pmb{\tau} \cdot {\mathbf{n}}=\pmb{\hat{\tau}}\,\,\textrm{on $\partial D_n $ }.\f]</CENTER >< HR >< HR > section element_types Implementation Within c oomph the non dimensional version of where the template parameter c DIM indicates the spatial dimension Following our usual discussed in the< A HREF=`../../../quick_guide/html/index.html`> (Not-So-) Quick Guide
alternatively equivalently f Omega f may be interpreted as a non dimensional density The boundary conditions are< CENTER > f[\mathbf{u}=\mathbf{\hat{u}}\,\,\textrm{on $\partial D_d $ },\quad\pmb{\tau} \cdot {\mathbf{n}}=\pmb{\hat{\tau}}\,\,\textrm{on $\partial D_n $ }.\f]</CENTER >< HR >< HR > section element_types Implementation Within c oomph the non dimensional version of where the template parameter c DIM indicates the spatial dimension Following our usual discussed in</A > this equation class is then combined with a geometric finite element to form a fully functional finite element For instance the combination of the c TimeHarmonicLinearElasticityEquations< 2 > class with the geometric finite element c QElement< 2, 3 > yields a nine node quadrilateral element As usual the mapping between local and global (Eulerian) coordinates within an element is given by
red here is a plot of the real part of the radial f (Re(u_1)^2+Re(u_2)^2)^
namespace Global parameters and functions As usual we define all non dimensional parameters in a namespace where we also define the displacement to be applied on the inner boundary the traction (pressure) to be applied on the outer boundary
namespace Global parameters and functions As usual we define all non dimensional parameters in a namespace where we also define the displacement to be applied on the inner boundary the and the exact solution (which we don 't list here because it is very lengthy). \dontinclude time_harmonic_elastic_annulus.cc \skipline start_namespace \until end_of_pressure_load We also define the output directory and the number of elements in the mesh. \skipline Output \until Nr< HR >< HR > \section main The driver code We start by defining command line arguments which specify the number of elements in the mesh and indicate the presence or absence of the `gap` in the coating. \dontinclude time_harmonic_elastic_annulus.cc \skipline start_of_main \until have_gap The code performs a parameter study in which we compute the solution for a range of pressures. We specify the pressure increment and the number of steps to be performed
namespace Global parameters and functions As usual we define all non dimensional parameters in a namespace where we also define the displacement to be applied on the inner boundary the and the exact parse the command line arguments and document them skipline P increment until doc_specified we create the problem (discretising the domain with nine-noded quadrilateral elements)
skipline Doc solution until end of main< HR >< HR > section problem The problem class The c Problem class is very simple As in other problems with Neumann boundary conditions we provide separate meshes for the bulk elements and the face elements that apply the traction boundary conditions The latter are attached to the relevant faces of the bulk elements by the function c create_traction_elements (). \dontinclude time_harmonic_elastic_annulus.cc \skipline begin_problem \until actions_before_newton_solve() \skipline Doc the solution \until delete_traction \skipline Pointer to solid mesh \until Solid_mesh_pt \skipline Pointer to mesh of traction \until }
< HR >< HR > section constructor The problem constructor We begin by building the bulk solid specifying the presence of the gap (and its width) if necessary. If there is no gap
Variables
mainpage The equations of time harmonic linear elasticity The aim of this tutorial is to demonstrate the solution of the time harmonic equations of linear elasticity in cartesian coordinates These equations are useful to describe forced
mainpage The equations of time harmonic linear elasticity The aim of this tutorial is to demonstrate the solution of the time harmonic equations of linear elasticity in cartesian coordinates These equations are useful to describe time harmonic oscillations of elastic bodies< CENTER >< TABLE BORDER=1, WIDTH=500px >< TR >< TD bgcolor=`cornsilk`>< CENTER >< B > Acknowledgement
mainpage The equations of time harmonic linear elasticity The aim of this tutorial is to demonstrate the solution of the time harmonic equations of linear elasticity in cartesian coordinates These equations are useful to describe time harmonic oscillations of elastic bodies< CENTER >< TABLE BORDER=1, WIDTH=500px >< TR >< TD bgcolor=`cornsilk`>< CENTER >< B > Young s modulus f E f and Poisson s ratio f nu f
mainpage The equations of time harmonic linear elasticity The aim of this tutorial is to demonstrate the solution of the time harmonic equations of linear elasticity in cartesian coordinates These equations are useful to describe time harmonic oscillations of elastic bodies< CENTER >< TABLE BORDER=1, WIDTH=500px >< TR >< TD bgcolor=`cornsilk`>< CENTER >< B > Young s modulus f E f and Poisson s ratio f nu occupying the region f D f whose boundary is f partial D f Assuming that the body performs time harmonic oscillations of frequency of f omega f its motion is governed by the equations of time harmonic linear elasticity< CENTER > f[\pmb{\nabla}^ *\cdot\pmb{\tau}^ *+\rho \mathbf{F}^ *=-\rho\omega^2 \mathbf{u}^ *,\f]</CENTER > where the f x_ {i}^* \f$ are the cartesian coordinates
mainpage The equations of time harmonic linear elasticity The aim of this tutorial is to demonstrate the solution of the time harmonic equations of linear elasticity in cartesian coordinates These equations are useful to describe time harmonic oscillations of elastic bodies< CENTER >< TABLE BORDER=1, WIDTH=500px >< TR >< TD bgcolor=`cornsilk`>< CENTER >< B > Young s modulus f E f and Poisson s ratio f nu occupying the region f D f whose boundary is f partial D f Assuming that the body performs time harmonic oscillations of frequency of f omega f its motion is governed by the equations of time harmonic linear elasticity< CENTER > f[\pmb{\nabla}^ *\cdot\pmb{\tau}^ *+\rho \mathbf{F}^ *=-\rho\omega^2 \mathbf{u}^ *,\f]</CENTER > where the f and the time periodic stresses
mainpage The equations of time harmonic linear elasticity The aim of this tutorial is to demonstrate the solution of the time harmonic equations of linear elasticity in cartesian coordinates These equations are useful to describe time harmonic oscillations of elastic bodies< CENTER >< TABLE BORDER=1, WIDTH=500px >< TR >< TD bgcolor=`cornsilk`>< CENTER >< B > Young s modulus f E f and Poisson s ratio f nu occupying the region f D f whose boundary is f partial D f Assuming that the body performs time harmonic oscillations of frequency of f omega f its motion is governed by the equations of time harmonic linear elasticity< CENTER > f[\pmb{\nabla}^ *\cdot\pmb{\tau}^ *+\rho \mathbf{F}^ *=-\rho\omega^2 \mathbf{u}^ *,\f]</CENTER > where the f and the time periodic body force and displacements are given by as usual
alternatively equivalently f Omega f may be interpreted as a non dimensional density The boundary conditions are< CENTER > f[\mathbf{u}=\mathbf{\hat{u}}\,\,\textrm{on $\partial D_d $ },\quad\pmb{\tau} \cdot {\mathbf{n}}=\pmb{\hat{\tau}}\,\,\textrm{on $\partial D_n $ }.\f]</CENTER >< HR >< HR > section element_types Implementation Within c oomph lib
alternatively equivalently f Omega f may be interpreted as a non dimensional density The boundary conditions are< CENTER > f[\mathbf{u}=\mathbf{\hat{u}}\,\,\textrm{on $\partial D_d $ },\quad\pmb{\tau} \cdot {\mathbf{n}}=\pmb{\hat{\tau}}\,\,\textrm{on $\partial D_n $ }.\f]</CENTER >< HR >< HR > section element_types Implementation Within c oomph the non dimensional version of where the template parameter c DIM indicates the spatial dimension Following our usual approach
alternatively equivalently f Omega f may be interpreted as a non dimensional density The boundary conditions are< CENTER > f[\mathbf{u}=\mathbf{\hat{u}}\,\,\textrm{on $\partial D_d $ },\quad\pmb{\tau} \cdot {\mathbf{n}}=\pmb{\hat{\tau}}\,\,\textrm{on $\partial D_n $ }.\f]</CENTER >< HR >< HR > section element_types Implementation Within c oomph the non dimensional version of where the template parameter c DIM indicates the spatial dimension Following our usual discussed in</A > this equation class is then combined with a geometric finite element to form a fully functional finite element For instance the combination of the c TimeHarmonicLinearElasticityEquations< 2 > class with the geometric finite element c QElement< 2, 3 > yields a nine node quadrilateral element As usual the mapping between local and< CENTER > f[x_i=\sum_{j=1}^{N^{(E)}} X^{(E)}_{ij} \, \psi_j, \qquadi=1, 2,\f]</CENTER > where f N {(E)} \f$ is the number of nodes in the element
alternatively equivalently f Omega f may be interpreted as a non dimensional density The boundary conditions are< CENTER > f[\mathbf{u}=\mathbf{\hat{u}}\,\,\textrm{on $\partial D_d $ },\quad\pmb{\tau} \cdot {\mathbf{n}}=\pmb{\hat{\tau}}\,\,\textrm{on $\partial D_n $ }.\f]</CENTER >< HR >< HR > section element_types Implementation Within c oomph the non dimensional version of where the template parameter c DIM indicates the spatial dimension Following our usual discussed in</A > this equation class is then combined with a geometric finite element to form a fully functional finite element For instance the combination of the c TimeHarmonicLinearElasticityEquations< 2 > class with the geometric finite element c QElement< 2, 3 > yields a nine node quadrilateral element As usual the mapping between local and< CENTER > f[x_i=\sum_{j=1}^{N^{(E)}} X^{(E)}_{ij} \, \psi_j, \qquadi=1, 2,\f]</CENTER > where f f X
alternatively equivalently f Omega f may be interpreted as a non dimensional density The boundary conditions are< CENTER > f[\mathbf{u}=\mathbf{\hat{u}}\,\,\textrm{on $\partial D_d $ },\quad\pmb{\tau} \cdot {\mathbf{n}}=\pmb{\hat{\tau}}\,\,\textrm{on $\partial D_n $ }.\f]</CENTER >< HR >< HR > section element_types Implementation Within c oomph the non dimensional version of where the template parameter c DIM indicates the spatial dimension Following our usual discussed in</A > this equation class is then combined with a geometric finite element to form a fully functional finite element For instance the combination of the c TimeHarmonicLinearElasticityEquations< 2 > class with the geometric finite element c QElement< 2, 3 > yields a nine node quadrilateral element As usual the mapping between local and< CENTER > f[x_i=\sum_{j=1}^{N^{(E)}} X^{(E)}_{ij} \, \psi_j, \qquadi=1, 2,\f]</CENTER > where f f and the f psi_j f are the element s shape functions
red __pad0__
red __pad1__
red here is a plot of the real part of the radial displacement
f I w textwidth re_ur Real part of the radial displacement Green
red __pad2__
red here is a plot of the real part of the horizontal displacement for the case when there is a gap in the annular region The presence of the gap clearly breaks the axisymmetry of the solution and creates waves that propagate in all directions
namespace Global parameters and functions As usual we define all non dimensional parameters in a namespace where we also define the displacement to be applied on the inner boundary the and the exact parse the command line arguments and document them skipline P increment until doc_specified Next
namespace Global parameters and functions As usual we define all non dimensional parameters in a namespace where we also define the displacement to be applied on the inner boundary the and the exact parse the command line arguments and document them skipline P increment until doc_specified we create the skipline Set up the problem until AnnularDisk and perform the parameter study
< HR >< HR > section constructor The problem constructor We begin by building the bulk solid mesh
< HR >< HR > section constructor The problem constructor We begin by building the bulk solid specifying the presence of the the mesh is periodic
see ref comments for a more detailed discussion of how the mesh for this problem is constructed dontinclude time_harmonic_elastic_annulus cc skipline start_of_constructor until skipline Build solid mesh until H_annulus It is always a good idea to have a look at the mesh and its boundary enumeration
see ref comments for a more detailed discussion of how the mesh for this problem is constructed dontinclude time_harmonic_elastic_annulus cc skipline start_of_constructor until skipline Build solid mesh until H_annulus It is always a good idea to have a look at the mesh and its boundary until Next we create the mesh that contains the FaceElements that apply the traction boundary conditions
Typedef Documentation
Omega
using Omega = 10 \f$, \f$ \nu=0.3 \f$, \f$ P_0 = 0.3 \f$, \f$ r_{\rm min}=1\f$ and \f$ r_{\rm max}=1.5 \f$. @I w 0.8\textwidth re_ux `Real part of the horizontal displacement. Green: exact
Definition at line 261 of file elastic_annulus.txt.
T
using T = \frac{1}{\omega} \f$, and use Young's modulus to non-dimensionalise the body force and the stress tensor: <CENTER> \f[ \pmb{\tau}^* = E \, \pmb{\tau}, \qquad x_{i}^* = {\cal L}\, x_{i} \f] \f[ \mathbf{u}^* = {\cal L}\, \mathbf{u}, \qquad \mathbf{F}^* = \frac{E}{\rho \cal L} \, \mathbf{F}, \qquad t^* = {\cal T}\, t. \f] </CENTER> The non-dimensional form of the equations is then given by <CENTER> \f[ \pmb{\nabla}\cdot\pmb{\tau}+\mathbf{F}=-\Omega^2\mathbf{u}, \ \ \ \ \ \ \ \ \ \ @E[nondimeqn]@ \f] </CENTER> with the non-dimensional constitutive relation, <CENTER> \f[ \pmb{\tau}=\frac{1}{1+\nu}\left(\frac{\nu}{1-2\nu}(\pmb{\nabla}\cdot\mathbf{u})\textbf{I}+ \frac{1}{2}(\pmb{\nabla}\mathbf{u}+\pmb{\nabla}\mathbf{u}^{{\rm T}})\right). \ \ \ \ \ \ \ \ \ \ @E[nondimconstitutive]@ \f] </CENTER> The non-dimensional parameter <CENTER> \f[ \Omega = {\cal L}\omega \sqrt{\frac{\rho}{E}} \f] </CENTER> is the ratio of the elastic body's intrinsic timescale, \f$\displaystyle {\cal L} \sqrt{\frac{\rho}{E}}\f$, to the problem-specific timescale,\f$ \displaystyle {\cal T}=\frac{1}{\omega} \f$, that we used to non-dimensionalise time. \f$ \Omega \f$ can be interpreted as a non-dimensional version of the excitation frequency
Definition at line 124 of file elastic_annulus.txt.
Function Documentation
create_traction_elements()
skipline Doc solution until end of main<HR><HR> section problem The problem class The c Problem class is very simple As in other problems with Neumann boundary conditions we provide separate meshes for the bulk elements and the face elements that apply the traction boundary conditions The latter are attached to the relevant faces of the bulk elements by the function c create_traction_elements ()
Referenced by RingWithTRibProblem< ELASTICITY_ELEMENT >::actions_after_adapt(), AnnularDiskProblem< ELASTICITY_ELEMENT >::actions_after_adapt(), AnnularDiskProblem< ELASTICITY_ELEMENT >::AnnularDiskProblem(), and RingWithTRibProblem< ELASTICITY_ELEMENT >::RingWithTRibProblem().
equations()
alternatively equivalently f Omega f may be interpreted as a non dimensional density The boundary conditions are<CENTER> f [\mathbf{u}=\mathbf{\hat{u}}\,\,\textrm{on $\partial D_d $ },\quad\pmb{\tau} \cdot {\mathbf{n}}=\pmb{\hat{\tau}}\,\,\textrm{on $\partial D_n $ }.\f]</CENTER><HR><HR> section element_types Implementation Within c oomph the non dimensional version of equations (@R@ [nondimeqn]) const
f()
red here is a plot of the real part of the radial f (Re(u_1)^2+Re(u_2)^ 2)
Definition at line 268 of file elastic_annulus.txt.
gap()
<HR><HR> section constructor The problem constructor We begin by building the bulk solid specifying the presence of the gap (and its width)
global()
alternatively equivalently f Omega f may be interpreted as a non dimensional density The boundary conditions are<CENTER> f [\mathbf{u}=\mathbf{\hat{u}}\,\,\textrm{on $\partial D_d $ },\quad\pmb{\tau} \cdot {\mathbf{n}}=\pmb{\hat{\tau}}\,\,\textrm{on $\partial D_n $ }.\f]</CENTER><HR><HR> section element_types Implementation Within c oomph the non dimensional version of where the template parameter c DIM indicates the spatial dimension Following our usual discussed in</A> this equation class is then combined with a geometric finite element to form a fully functional finite element For instance the combination of the c TimeHarmonicLinearElasticityEquations<2> class with the geometric finite element c QElement<2,3> yields a nine node quadrilateral element As usual the mapping between local and global (Eulerian)
problem()
namespace Global parameters and functions As usual we define all non dimensional parameters in a namespace where we also define the displacement to be applied on the inner boundary the and the exact parse the command line arguments and document them skipline P increment until doc_specified we create the problem (discretising the domain with nine-noded quadrilateral elements)
Referenced by main().
solution()
namespace Global parameters and functions As usual we define all non dimensional parameters in a namespace where we also define the displacement to be applied on the inner boundary the and the exact solution (which we don 't list here because it is very lengthy)
the< A HREF="../../../quick_guide/html/index.html">()
alternatively equivalently f Omega f may be interpreted as a non dimensional density The boundary conditions are<CENTER> f [\mathbf{u}=\mathbf{\hat{u}}\,\,\textrm{on $\partial D_d $ },\quad\pmb{\tau} \cdot {\mathbf{n}}=\pmb{\hat{\tau}}\,\,\textrm{on $\partial D_n $ }.\f]</CENTER><HR><HR> section element_types Implementation Within c oomph the non dimensional version of where the template parameter c DIM indicates the spatial dimension Following our usual discussed in the< A HREF=`../../../quick_guide/html/index.html`> (Not-So-)
traction()
namespace Global parameters and functions As usual we define all non dimensional parameters in a namespace where we also define the displacement to be applied on the inner boundary the traction (pressure)
Referenced by Global_Parameters::constant_pressure(), and Global_Parameters::pressure_load().
Variable Documentation
__pad0__
red __pad0__
Definition at line 263 of file elastic_annulus.txt.
__pad1__
red __pad1__
Definition at line 267 of file elastic_annulus.txt.
__pad2__
red __pad2__
Definition at line 272 of file elastic_annulus.txt.
Acknowledgement
mainpage The equations of time harmonic linear elasticity The aim of this tutorial is to demonstrate the solution of the time harmonic equations of linear elasticity in cartesian coordinates These equations are useful to describe time harmonic oscillations of elastic bodies<CENTER><TABLE BORDER=1, WIDTH=500px><TR><TD bgcolor=`cornsilk`><CENTER><B> Acknowledgement
Definition at line 29 of file elastic_annulus.txt.
approach
alternatively equivalently f Omega f may be interpreted as a non dimensional density The boundary conditions are<CENTER> f [\mathbf{u}=\mathbf{\hat{u}}\,\,\textrm{on $\partial D_d $ },\quad\pmb{\tau} \cdot {\mathbf{n}}=\pmb{\hat{\tau}}\,\,\textrm{on $\partial D_n $ }.\f]</CENTER><HR><HR> section element_types Implementation Within c oomph the non dimensional version of where the template parameter c DIM indicates the spatial dimension Following our usual approach
Definition at line 149 of file elastic_annulus.txt.
conditions
see ref comments for a more detailed discussion of how the mesh for this problem is constructed dontinclude time_harmonic_elastic_annulus cc skipline start_of_constructor until skipline Build solid mesh until H_annulus It is always a good idea to have a look at the mesh and its boundary until Next we create the mesh that contains the FaceElements that apply the traction boundary conditions
Definition at line 394 of file elastic_annulus.txt.
directions
red here is a plot of the real part of the horizontal displacement for the case when there is a gap in the annular region The presence of the gap clearly breaks the axisymmetry of the solution and creates waves that propagate in all directions
Definition at line 279 of file elastic_annulus.txt.
displacement
red here is a plot of the real part of the radial displacement
Definition at line 268 of file elastic_annulus.txt.
enumeration
see ref comments for a more detailed discussion of how the mesh for this problem is constructed dontinclude time_harmonic_elastic_annulus cc skipline start_of_constructor until skipline Build solid mesh until H_annulus It is always a good idea to have a look at the mesh and its boundary enumeration
Definition at line 390 of file elastic_annulus.txt.
f
alternatively equivalently f Omega f may be interpreted as a non dimensional density The boundary conditions are< CENTER > f
Initial value:
{\rm Re}\{\pmb{\tau^*}(x_{i}^*){\rm e}^{-{\rm i}\omega
t^*}\} \f$
Definition at line 30 of file elastic_annulus.txt.
forced
mainpage The equations of time harmonic linear elasticity The aim of this tutorial is to demonstrate the solution of the time harmonic equations of linear elasticity in cartesian coordinates These equations are useful to describe forced
Definition at line 5 of file elastic_annulus.txt.
functions
alternatively equivalently f Omega f may be interpreted as a non dimensional density The boundary conditions are<CENTER> f [\mathbf{u}=\mathbf{\hat{u}}\,\,\textrm{on $\partial D_d $ },\quad\pmb{\tau} \cdot {\mathbf{n}}=\pmb{\hat{\tau}}\,\,\textrm{on $\partial D_n $ }.\f]</CENTER><HR><HR> section element_types Implementation Within c oomph the non dimensional version of where the template parameter c DIM indicates the spatial dimension Following our usual discussed in</A> this equation class is then combined with a geometric finite element to form a fully functional finite element For instance the combination of the c TimeHarmonicLinearElasticityEquations<2> class with the geometric finite element c QElement<2,3> yields a nine node quadrilateral element As usual the mapping between local and<CENTER> f [x_i = \sum_{j=1}^{N^{(E)}} X^{(E)}_{ij} \, \psi_j, \qquadi=1,2,\f]</CENTER> where f f and the f psi_j f are the element s shape functions
Definition at line 168 of file elastic_annulus.txt.
Green
f I w textwidth re_ur Real part of the radial displacement Green
Definition at line 270 of file elastic_annulus.txt.
lib
alternatively equivalently f Omega f may be interpreted as a non dimensional density The boundary conditions are<CENTER> f [\mathbf{u}=\mathbf{\hat{u}}\,\,\textrm{on $\partial D_d $ },\quad\pmb{\tau} \cdot {\mathbf{n}}=\pmb{\hat{\tau}}\,\,\textrm{on $\partial D_n $ }.\f]</CENTER><HR><HR> section element_types Implementation Within c oomph lib
Definition at line 144 of file elastic_annulus.txt.
mesh
see ref comments for a more detailed discussion of how the mesh for this problem is constructed dontinclude time_harmonic_elastic_annulus cc skipline start_of_constructor until skipline Build solid mesh until H_annulus It is always a good idea to have a look at the mesh and its boundary until Next we create the mesh that contains the FaceElements that apply the traction boundary and combine all meshes into a global mesh
Definition at line 370 of file elastic_annulus.txt.
N
alternatively equivalently f Omega f may be interpreted as a non dimensional density The boundary conditions are<CENTER> f [\mathbf{u}=\mathbf{\hat{u}}\,\,\textrm{on $\partial D_d $ },\quad\pmb{\tau} \cdot {\mathbf{n}}=\pmb{\hat{\tau}}\,\,\textrm{on $\partial D_n $ }.\f]</CENTER><HR><HR> section element_types Implementation Within c oomph the non dimensional version of where the template parameter c DIM indicates the spatial dimension Following our usual discussed in</A> this equation class is then combined with a geometric finite element to form a fully functional finite element For instance the combination of the c TimeHarmonicLinearElasticityEquations<2> class with the geometric finite element c QElement<2,3> yields a nine node quadrilateral element As usual the mapping between local and<CENTER> f [x_i = \sum_{j=1}^{N^{(E)}} X^{(E)}_{ij} \, \psi_j, \qquadi=1,2,\f]</CENTER> where f N {(E)} \f$ is the number of nodes in the element
Definition at line 164 of file elastic_annulus.txt.
Next
namespace Global parameters and functions As usual we define all non dimensional parameters in a namespace where we also define the displacement to be applied on the inner boundary the and the exact parse the command line arguments and document them skipline P increment until doc_specified Next
Definition at line 325 of file elastic_annulus.txt.
periodic
<HR><HR> section constructor The problem constructor We begin by building the bulk solid specifying the presence of the the mesh is periodic
Definition at line 372 of file elastic_annulus.txt.
Referenced by AnnularDiskProblem< ELASTICITY_ELEMENT >::AnnularDiskProblem().
stresses
mainpage The equations of time harmonic linear elasticity The aim of this tutorial is to demonstrate the solution of the time harmonic equations of linear elasticity in cartesian coordinates These equations are useful to describe time harmonic oscillations of elastic bodies<CENTER><TABLE BORDER=1, WIDTH=500px><TR><TD bgcolor=`cornsilk`><CENTER><B> Young s modulus f E f and Poisson s ratio f nu occupying the region f D f whose boundary is f partial D f Assuming that the body performs time harmonic oscillations of frequency of f omega f its motion is governed by the equations of time harmonic linear elasticity<CENTER> f [\pmb{\nabla}^*\cdot\pmb{\tau}^*+\rho \mathbf{F}^*=-\rho\omega^2 \mathbf{u}^*,\f]</CENTER> where the f and the time periodic stresses
Definition at line 43 of file elastic_annulus.txt.
study
namespace Global parameters and functions As usual we define all non dimensional parameters in a namespace where we also define the displacement to be applied on the inner boundary the and the exact parse the command line arguments and document them skipline P increment until doc_specified we create the skipline Set up the problem until AnnularDisk and perform the parameter study
Definition at line 336 of file elastic_annulus.txt.
usual
mainpage The equations of time harmonic linear elasticity The aim of this tutorial is to demonstrate the solution of the time harmonic equations of linear elasticity in cartesian coordinates These equations are useful to describe time harmonic oscillations of elastic bodies<CENTER><TABLE BORDER=1, WIDTH=500px><TR><TD bgcolor=`cornsilk`><CENTER><B> Young s modulus f E f and Poisson s ratio f nu occupying the region f D f whose boundary is f partial D f Assuming that the body performs time harmonic oscillations of frequency of f omega f its motion is governed by the equations of time harmonic linear elasticity<CENTER> f [\pmb{\nabla}^*\cdot\pmb{\tau}^*+\rho \mathbf{F}^*=-\rho\omega^2 \mathbf{u}^*,\f]</CENTER> where the f and the time periodic body force and displacements are given by as usual
Definition at line 48 of file elastic_annulus.txt.
X
alternatively equivalently f Omega f may be interpreted as a non dimensional density The boundary conditions are<CENTER> f [\mathbf{u}=\mathbf{\hat{u}}\,\,\textrm{on $\partial D_d $ },\quad\pmb{\tau} \cdot {\mathbf{n}}=\pmb{\hat{\tau}}\,\,\textrm{on $\partial D_n $ }.\f]</CENTER><HR><HR> section element_types Implementation Within c oomph the non dimensional version of where the template parameter c DIM indicates the spatial dimension Following our usual discussed in</A> this equation class is then combined with a geometric finite element to form a fully functional finite element For instance the combination of the c TimeHarmonicLinearElasticityEquations<2> class with the geometric finite element c QElement<2,3> yields a nine node quadrilateral element As usual the mapping between local and<CENTER> f [x_i = \sum_{j=1}^{N^{(E)}} X^{(E)}_{ij} \, \psi_j, \qquadi=1,2,\f]</CENTER> where f f X
Initial value:
{(E)}_{ij}
\f$ is the \f$ i \f$-th global (Eulerian) coordinate of
the \f$ j \f$-th \c Node
in the element
Definition at line 164 of file elastic_annulus.txt.
x_
mainpage The equations of time harmonic linear elasticity The aim of this tutorial is to demonstrate the solution of the time harmonic equations of linear elasticity in cartesian coordinates These equations are useful to describe time harmonic oscillations of elastic bodies<CENTER><TABLE BORDER=1, WIDTH=500px><TR><TD bgcolor=`cornsilk`><CENTER><B> Young s modulus f E f and Poisson s ratio f nu occupying the region f D f whose boundary is f partial D f Assuming that the body performs time harmonic oscillations of frequency of f omega f its motion is governed by the equations of time harmonic linear elasticity<CENTER> f [\pmb{\nabla}^*\cdot\pmb{\tau}^*+\rho \mathbf{F}^*=-\rho\omega^2 \mathbf{u}^*,\f]</CENTER> where the f x_ {i}^* \f$ are the cartesian coordinates
Definition at line 42 of file elastic_annulus.txt.