SpineInclinedPlaneProblem< ELEMENT, TIMESTEPPER > Class Template Reference
Public Member Functions
SpineInclinedPlaneProblem (const unsigned &nx, const unsigned &ny, const double &length)
void actions_before_newton_convergence_check ()
Spine heights/lengths are unknowns in the problem so their values get corrected during each Newton step. However, changing their value does not automatically change the nodal positions, so we need to update all of them.
Public Member Functions inherited from InclinedPlaneProblem< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > >
InclinedPlaneProblem (const unsigned &nx, const unsigned &ny, const double &length)
Generic Constructor (empty)
void solve_steady ()
Solve the steady problem.
void timestep (const double &dt, const unsigned &n_tsteps)
Take n_tsteps timesteps of size dt.
void actions_before_implicit_timestep ()
Actions before the timestep (update the time-dependent boundary conditions)
void make_traction_elements ()
Function to add the traction boundary elements to boundaries 3(inlet) and 1(outlet) of the mesh.
void make_free_surface_elements ()
void complete_build ()
Complete the build of the problem setting all standard parameters and boundary conditions.
~InclinedPlaneProblem ()
Generic desructor to clean up the memory allocated in the problem.
Additional Inherited Members
Protected Attributes inherited from InclinedPlaneProblem< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > >
Mesh * Bulk_mesh_pt
Bulk fluid mesh.
Mesh * Traction_mesh_pt
Mesh for the traction elements that are added at inlet and outlet.
Mesh * Surface_mesh_pt
Mesh for the free surface elements.
Mesh * Point_mesh_pt
Mesh for the point elements at each end of the free surface.
std::string Output_prefix
Prefix for output files.
Detailed Description
template<class ELEMENT, class TIMESTEPPER>
class SpineInclinedPlaneProblem< ELEMENT, TIMESTEPPER >
Definition at line 607 of file inclined_plane.cc.
Constructor & Destructor Documentation
SpineInclinedPlaneProblem()
template<class ELEMENT , class TIMESTEPPER >
SpineInclinedPlaneProblem< ELEMENT, TIMESTEPPER >::SpineInclinedPlaneProblem (const unsigned & nx, const unsigned & ny, const double & length) [inline]
Definition at line 613 of file inclined_plane.cc.
References InclinedPlaneProblem< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > >::Bulk_mesh_pt, InclinedPlaneProblem< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > >::complete_build(), InclinedPlaneProblem< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > >::make_free_surface_elements(), InclinedPlaneProblem< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > >::make_traction_elements(), InclinedPlaneProblem< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > >::Output_prefix, InclinedPlaneProblem< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > >::Point_mesh_pt, InclinedPlaneProblem< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > >::Surface_mesh_pt, and InclinedPlaneProblem< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > >::Traction_mesh_pt.
Member Function Documentation
actions_before_newton_convergence_check()
template<class ELEMENT , class TIMESTEPPER >
void SpineInclinedPlaneProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_convergence_check () [inline]
Spine heights/lengths are unknowns in the problem so their values get corrected during each Newton step. However, changing their value does not automatically change the nodal positions, so we need to update all of them.
Definition at line 649 of file inclined_plane.cc.
References InclinedPlaneProblem< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > >::Bulk_mesh_pt.
The documentation for this class was generated from the following file:
inclined_plane.cc