inclined_plane.cc File Reference
Classes
class InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >
Generic problem class that will form the base class for both spine and elastic mesh-updates of the problem. Templated by the bulk element and interface element types.
class SpineInclinedPlaneMesh< ELEMENT >
Create a spine mesh for the problem.
class SpineInclinedPlaneProblem< ELEMENT, TIMESTEPPER >
class ElasticInclinedPlaneMesh< ELEMENT >
Create an Elastic mesh for the problem.
class ElasticInclinedPlaneProblem< ELEMENT, TIMESTEPPER >
Namespaces
 Global_Physical_Variables
Functions
Vector< double > Global_Physical_Variables::G (2, 0.0)
The Vector direction of gravity, set in main()
void Global_Physical_Variables::wall_unit_normal_inlet_fct (const Vector< double > &x, Vector< double > &normal)
Function that specifies the wall unit normal at the inlet.
void Global_Physical_Variables::wall_unit_normal_outlet_fct (const Vector< double > &x, Vector< double > &normal)
Function that specified the wall unit normal at the outlet.
void Global_Physical_Variables::hydrostatic_pressure_outlet (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction)
Function that prescribes the hydrostatic pressure field at the outlet.
void Global_Physical_Variables::hydrostatic_pressure_inlet (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction)
Function that prescribes hydrostatic pressure field at the inlet.
int main (int argc, char **argv)
Variables
double Global_Physical_Variables::Re =0.0
Reynolds number, based on the average velocity within the fluid film.
double Global_Physical_Variables::ReInvFr =2.0
The product of Reynolds number and inverse Froude number is set to two in this problem, which gives the free surface velocity to be sin(alpha). [Set to three in order to get the same scale as used by Yih, Benjamin, etc].
double Global_Physical_Variables::Alpha = 1.0*atan(1.0)
Angle of incline of the slope (45 degrees)
double Global_Physical_Variables::Ca = 1.0
The Capillary number.
double Global_Physical_Variables::K = 0.1
Set the wavenumber.
double Global_Physical_Variables::N_wave = 3
Set the number of waves desired in the domain.
double Global_Physical_Variables::Length = 2*N_wave*4.0*atan(1.0)/K
The length of the domain to fit the desired number of waves.
Vector< double > Global_Physical_Variables::Wall_normal
Direction of the wall normal vector (at the inlet)
double Global_Physical_Variables::Inlet_Angle = 2.0*atan(1.0)
The contact angle that is imposed at the inlet (pi)
ConstitutiveLaw * Global_Physical_Variables::Constitutive_law_pt
Constitutive law used to determine the mesh deformation.
double Global_Physical_Variables::Nu =0.1
Pseudo-solid Poisson ratio.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 756 of file inclined_plane.cc.
References Global_Physical_Variables::Alpha, Global_Physical_Variables::Constitutive_law_pt, Global_Physical_Variables::G(), Global_Physical_Variables::Length, Global_Physical_Variables::Nu, Global_Physical_Variables::Re, InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::solve_steady(), InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::timestep(), and Global_Physical_Variables::Wall_normal.