Global_Physical_Variables Namespace Reference
Functions
Vector< double > G (2, 0.0)
The Vector direction of gravity, set in main()
void wall_unit_normal_inlet_fct (const Vector< double > &x, Vector< double > &normal)
Function that specifies the wall unit normal at the inlet.
void wall_unit_normal_outlet_fct (const Vector< double > &x, Vector< double > &normal)
Function that specified the wall unit normal at the outlet.
void hydrostatic_pressure_outlet (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction)
Function that prescribes the hydrostatic pressure field at the outlet.
void hydrostatic_pressure_inlet (const double &time, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction)
Function that prescribes hydrostatic pressure field at the inlet.
Variables
double Re =0.0
Reynolds number, based on the average velocity within the fluid film.
double ReInvFr =2.0
The product of Reynolds number and inverse Froude number is set to two in this problem, which gives the free surface velocity to be sin(alpha). [Set to three in order to get the same scale as used by Yih, Benjamin, etc].
double Alpha = 1.0*atan(1.0)
Angle of incline of the slope (45 degrees)
double Ca = 1.0
The Capillary number.
double K = 0.1
Set the wavenumber.
double N_wave = 3
Set the number of waves desired in the domain.
double Length = 2*N_wave*4.0*atan(1.0)/K
The length of the domain to fit the desired number of waves.
Vector< double > Wall_normal
Direction of the wall normal vector (at the inlet)
double Inlet_Angle = 2.0*atan(1.0)
The contact angle that is imposed at the inlet (pi)
ConstitutiveLaw * Constitutive_law_pt
Constitutive law used to determine the mesh deformation.
double Nu =0.1
Pseudo-solid Poisson ratio.
Function Documentation
G()
Vector<double> Global_Physical_Variables::G (2 , 0. 0)
The Vector direction of gravity, set in main()
Referenced by InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::complete_build(), hydrostatic_pressure_inlet(), hydrostatic_pressure_outlet(), and main().
hydrostatic_pressure_inlet()
void Global_Physical_Variables::hydrostatic_pressure_inlet (const double & time, const Vector< double > & x, const Vector< double > & n, Vector< double > & traction)
Function that prescribes hydrostatic pressure field at the inlet.
Definition at line 115 of file inclined_plane.cc.
References G(), and ReInvFr.
Referenced by InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::make_traction_elements().
hydrostatic_pressure_outlet()
void Global_Physical_Variables::hydrostatic_pressure_outlet (const double & time, const Vector< double > & x, const Vector< double > & n, Vector< double > & traction)
Function that prescribes the hydrostatic pressure field at the outlet.
Definition at line 106 of file inclined_plane.cc.
References G(), and ReInvFr.
Referenced by InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::make_traction_elements().
wall_unit_normal_inlet_fct()
void Global_Physical_Variables::wall_unit_normal_inlet_fct (const Vector< double > & x, Vector< double > & normal)
Function that specifies the wall unit normal at the inlet.
Definition at line 84 of file inclined_plane.cc.
References Wall_normal.
Referenced by InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::make_free_surface_elements().
wall_unit_normal_outlet_fct()
void Global_Physical_Variables::wall_unit_normal_outlet_fct (const Vector< double > & x, Vector< double > & normal)
Function that specified the wall unit normal at the outlet.
Definition at line 91 of file inclined_plane.cc.
References Wall_normal.
Referenced by InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::make_free_surface_elements().
Variable Documentation
Alpha
double Global_Physical_Variables::Alpha = 1.0*atan(1.0)
Angle of incline of the slope (45 degrees)
Definition at line 63 of file inclined_plane.cc.
Referenced by main(), and InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::solve_steady().
Ca
double Global_Physical_Variables::Ca = 1.0
The Capillary number.
Definition at line 69 of file inclined_plane.cc.
Referenced by InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::make_free_surface_elements().
Constitutive_law_pt
ConstitutiveLaw* Global_Physical_Variables::Constitutive_law_pt
Constitutive law used to determine the mesh deformation.
Definition at line 125 of file inclined_plane.cc.
Referenced by ElasticInclinedPlaneProblem< ELEMENT, TIMESTEPPER >::ElasticInclinedPlaneProblem(), and main().
Inlet_Angle
double Global_Physical_Variables::Inlet_Angle = 2.0*atan(1.0)
The contact angle that is imposed at the inlet (pi)
Definition at line 102 of file inclined_plane.cc.
Referenced by InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::make_free_surface_elements().
K
double Global_Physical_Variables::K = 0.1
Set the wavenumber.
Definition at line 72 of file inclined_plane.cc.
Referenced by InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::actions_before_implicit_timestep().
Length
double Global_Physical_Variables::Length = 2*N_wave*4.0*atan(1.0)/K
The length of the domain to fit the desired number of waves.
Definition at line 78 of file inclined_plane.cc.
Referenced by main().
N_wave
double Global_Physical_Variables::N_wave = 3
Set the number of waves desired in the domain.
Definition at line 75 of file inclined_plane.cc.
Nu
double Global_Physical_Variables::Nu =0.1
Pseudo-solid Poisson ratio.
Definition at line 128 of file inclined_plane.cc.
Referenced by main().
Re
double Global_Physical_Variables::Re =0.0
Reynolds number, based on the average velocity within the fluid film.
Definition at line 54 of file inclined_plane.cc.
Referenced by InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::complete_build(), main(), and InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::timestep().
ReInvFr
double Global_Physical_Variables::ReInvFr =2.0
The product of Reynolds number and inverse Froude number is set to two in this problem, which gives the free surface velocity to be sin(alpha). [Set to three in order to get the same scale as used by Yih, Benjamin, etc].
Definition at line 60 of file inclined_plane.cc.
Referenced by InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::complete_build(), hydrostatic_pressure_inlet(), hydrostatic_pressure_outlet(), and InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::solve_steady().
Wall_normal
Vector<double> Global_Physical_Variables::Wall_normal
Direction of the wall normal vector (at the inlet)
Definition at line 81 of file inclined_plane.cc.
Referenced by main(), wall_unit_normal_inlet_fct(), and wall_unit_normal_outlet_fct().