algebraic_free_boundary_poisson.cc File Reference
Classes
class RefineableFishPoissonProblem< ELEMENT >
Refineable Poisson problem in deformable fish-shaped domain. Template parameter identify the elements.
Namespaces
namespace ConstSourceForPoisson
Namespace for const source term in Poisson equation.
Functions
void ConstSourceForPoisson::get_source (const Vector< double > &x, double &source)
Const source function.
template<class ELEMENT >
void demo_fish_poisson (const string &directory_name)
Demonstrate how to solve 2D Poisson problem in deformable fish-shaped domain with mesh adaptation.
template<class ELEMENT >
void demo_elastic_fish_poisson (const string &directory_name)
Demonstrate how to solve "elastic" 2D Poisson problem in deformable fish-shaped domain with mesh adaptation.
int main (int argc, char *argv[])
Driver for "elastic" fish poisson solver with adaptation. If there are any command line arguments, we regard this as a validation run and perform only a single step.
Variables
double ConstSourceForPoisson::Strength =1.0
Strength of source function: default value 1.0.
Function Documentation
demo_elastic_fish_poisson()
template<class ELEMENT >
void demo_elastic_fish_poisson (const string & directory_name)
Demonstrate how to solve "elastic" 2D Poisson problem in deformable fish-shaped domain with mesh adaptation.
Definition at line 511 of file algebraic_free_boundary_poisson.cc.
References RefineableFishPoissonProblem< ELEMENT >::doc_solution(), RefineableFishPoissonProblem< ELEMENT >::fish_mesh_pt(), and RefineableFishPoissonProblem< ELEMENT >::load().
demo_fish_poisson()
template<class ELEMENT >
void demo_fish_poisson (const string & directory_name)
Demonstrate how to solve 2D Poisson problem in deformable fish-shaped domain with mesh adaptation.
Definition at line 460 of file algebraic_free_boundary_poisson.cc.
References RefineableFishPoissonProblem< ELEMENT >::doc_info(), RefineableFishPoissonProblem< ELEMENT >::doc_solution(), RefineableFishPoissonProblem< ELEMENT >::fish_mesh_pt(), and RefineableFishPoissonProblem< ELEMENT >::y_c().
Referenced by DeformableFishPoissonProblem< ELEMENT >::actions_after_adapt(), DeformableFishPoissonProblem< ELEMENT >::actions_before_newton_solve(), DeformableFishPoissonProblem< ELEMENT >::DeformableFishPoissonProblem(), GeomObjectAsGeneralisedElementProblem::doc_solution(), FreeBoundaryPoissonProblem< ELEMENT >::doc_solution(), DeformableFishPoissonProblem< ELEMENT >::doc_solution(), oomph::ElasticallySupportedRingElement::ElasticallySupportedRingElement(), ElasticFishMesh< ELEMENT >::ElasticFishMesh(), oomph::ElasticallySupportedRingElement::fill_in_generic_residual_contribution(), FreeBoundaryPoissonProblem< ELEMENT >::FreeBoundaryPoissonProblem(), oomph::GeneralCircle::GeneralCircle(), oomph::GeneralCircle::GeneralCircle(), oomph::GeneralCircle::geom_data_pt(), GeomObjectAsGeneralisedElementProblem::GeomObjectAsGeneralisedElementProblem(), oomph::ElasticallySupportedRingElement::get_jacobian(), oomph::ElasticallySupportedRingElement::get_residuals(), oomph::ElasticallySupportedRingElement::load(), main(), main(), MyMacroElementNodeUpdateFishMesh< ELEMENT >::MyMacroElementNodeUpdateFishMesh(), MyMacroElementNodeUpdateRefineableFishMesh< ELEMENT >::MyMacroElementNodeUpdateRefineableFishMesh(), oomph::ElasticallySupportedRingElement::pin_yc(), oomph::SimpleCircle::position(), oomph::GeneralCircle::position(), oomph::SimpleCircle::position(), oomph::GeneralCircle::position(), DeformableFishPoissonProblem< ELEMENT >::run(), oomph::ElasticallySupportedRingElement::set_load_pt(), oomph::ElasticallySupportedRingElement::unpin_yc(), and oomph::GeneralCircle::~GeneralCircle().
main()
int main (int argc, char * argv[])
Driver for "elastic" fish poisson solver with adaptation. If there are any command line arguments, we regard this as a validation run and perform only a single step.
Definition at line 558 of file algebraic_free_boundary_poisson.cc.
References demo_fish_poisson().