oomph::GeneralCircle Class Reference
GeneralCircle in 2D space.
#include <circle.h>
Public Member Functions
GeneralCircle (const double &x_c, const double &y_c, const double &r)
Constructor: Pass x and y-coords of centre and radius (all pinned)
GeneralCircle (Data *geom_data_pt)
Alternative constructor: Pass x and y-coords of centre and radius (all as part of Data)
virtual ~GeneralCircle ()
Destructor: Clean up if necessary.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position Vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
Position Vector at Lagrangian coordinate zeta at time level t (t=0: present; t>0: previous level). Steady object, so we simply forward the call to the steady version.
double & x_c ()
Access function to x-coordinate of centre of circle.
double & y_c ()
Access function to y-coordinate of centre of circle.
double & R ()
Access function to radius of circle.
unsigned ngeom_data () const
How many items of Data does the shape of the object depend on?
Data * geom_data_pt (const unsigned &j)
Return pointer to the j-th Data item that the object's shape depends on.
Protected Attributes
Vector< Data * > Geom_data_pt
Vector of pointers to Data items that affects the object's shape.
bool Must_clean_up
Do I need to clean up?
Detailed Description
GeneralCircle in 2D space.
 x = X_c + R \cos(\zeta)  
 y = Y_c + R \sin(\zeta)  
 The three parameters $ X_c, Y_c $ and $ R $ are represented by Data and can therefore be unknowns in the problem.
Definition at line 95 of file circle.h.
Constructor & Destructor Documentation
GeneralCircle() [1/2]
oomph::GeneralCircle::GeneralCircle (const double & x_c, const double & y_c, const double & r) [inline]
Constructor: Pass x and y-coords of centre and radius (all pinned)
Definition at line 101 of file circle.h.
References demo_fish_poisson(), Geom_data_pt, Must_clean_up, x_c(), and y_c().
GeneralCircle() [2/2]
oomph::GeneralCircle::GeneralCircle (Data * geom_data_pt) [inline]
Alternative constructor: Pass x and y-coords of centre and radius (all as part of Data)
Geom_data_pt[0]->value(0) = X_c;
Geom_data_pt[0]->value(1) = Y_c;
Geom_data_pt[0]->value(2) = R;
Definition at line 143 of file circle.h.
References demo_fish_poisson(), geom_data_pt(), Geom_data_pt, and Must_clean_up.
~GeneralCircle()
virtual oomph::GeneralCircle::~GeneralCircle () [inline], [virtual]
Destructor: Clean up if necessary.
Definition at line 167 of file circle.h.
References demo_fish_poisson(), Geom_data_pt, Must_clean_up, and ngeom_data().
Member Function Documentation
geom_data_pt()
Data * oomph::GeneralCircle::geom_data_pt (const unsigned & j) [inline]
Return pointer to the j-th Data item that the object's shape depends on.
Definition at line 218 of file circle.h.
References demo_fish_poisson(), and Geom_data_pt.
Referenced by GeneralCircle().
ngeom_data()
unsigned oomph::GeneralCircle::ngeom_data () const [inline]
How many items of Data does the shape of the object depend on?
Definition at line 214 of file circle.h.
References Geom_data_pt.
Referenced by ~GeneralCircle().
position() [1/2]
void oomph::GeneralCircle::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const [inline]
Position Vector at Lagrangian coordinate zeta at time level t (t=0: present; t>0: previous level). Steady object, so we simply forward the call to the steady version.
Definition at line 200 of file circle.h.
References demo_fish_poisson(), and position().
position() [2/2]
void oomph::GeneralCircle::position (const Vector< double > & zeta, Vector< double > & r) const [inline]
Position Vector at Lagrangian coordinate zeta.
Definition at line 183 of file circle.h.
References demo_fish_poisson(), Geom_data_pt, and R().
Referenced by position().
R()
double & oomph::GeneralCircle::R () [inline]
Access function to radius of circle.
Definition at line 211 of file circle.h.
References Geom_data_pt.
Referenced by position().
x_c()
double & oomph::GeneralCircle::x_c () [inline]
Access function to x-coordinate of centre of circle.
Definition at line 205 of file circle.h.
References Geom_data_pt.
Referenced by GeneralCircle().
y_c()
double & oomph::GeneralCircle::y_c () [inline]
Access function to y-coordinate of centre of circle.
Definition at line 208 of file circle.h.
References Geom_data_pt.
Referenced by oomph::ElasticallySupportedRingElement::fill_in_generic_residual_contribution(), GeneralCircle(), and main().
Member Data Documentation
Geom_data_pt
Vector<Data*> oomph::GeneralCircle::Geom_data_pt [protected]
Vector of pointers to Data items that affects the object's shape.
Definition at line 224 of file circle.h.
Referenced by oomph::ElasticallySupportedRingElement::ElasticallySupportedRingElement(), GeneralCircle(), GeneralCircle(), geom_data_pt(), ngeom_data(), position(), R(), x_c(), y_c(), and ~GeneralCircle().
Must_clean_up
bool oomph::GeneralCircle::Must_clean_up [protected]
Do I need to clean up?
Definition at line 227 of file circle.h.
Referenced by oomph::ElasticallySupportedRingElement::ElasticallySupportedRingElement(), GeneralCircle(), GeneralCircle(), and ~GeneralCircle().
The documentation for this class was generated from the following file:
circle.h