geom_object_element.cc File Reference
Classes
class GeomObjectAsGeneralisedElementProblem
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Functions
int main ()
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Function Documentation
main()
int main ()
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Driver
Definition at line 208 of file geom_object_element.cc.
References GeomObjectAsGeneralisedElementProblem::doc_info(), GeomObjectAsGeneralisedElementProblem::doc_solution(), and GeomObjectAsGeneralisedElementProblem::load().