oomph::GmshParameters Class Reference
Class to collate parameters for Gmsh mesh generation.
#include <gmsh_tet_mesh.template.h>
Public Member Functions
GmshParameters (TetMeshFacetedClosedSurface *const &outer_boundary_pt, const std::string &gmsh_command_line_invocation)
Specify outer boundary of domain to be meshed. Other parameters get default values and can be set via member functions.
TetMeshFacetedClosedSurface *& outer_boundary_pt ()
Outer boundary.
Vector< TetMeshFacetedSurface * > & internal_surface_pt ()
Internal boundaries.
double & element_volume ()
Uniform target element volume.
std::string & target_size_file_name ()
Filename for target volumes (for system-call based transfer to gmsh during mesh adaptation). Default: .gmsh_target_size_for_adaptation.dat.
std::string & gmsh_command_line_invocation ()
String to be issued via system command to activate gmsh.
std::string & geo_and_msh_file_stem ()
Stem for geo and msh files (input/output to command-line gmsh invocation)
double & max_element_size ()
Max. element size during refinement.
double & min_element_size ()
Min. element size during refinement.
double & max_permitted_edge_ratio ()
Max. permitted edge ratio.
double & dx_for_target_size_transfer ()
(Isotropic) grid spacing for target size transfer
unsigned & max_sample_points_for_limited_locate_zeta_during_target_size_transfer ()
Target size is transferred onto regular grid (for gmsh) by locate zeta. We try to find the exact point in the existing mesh but if we fail to converge from the nearest specified number of sample points we use the nearest of those.
std::string & stem_for_filename_gmsh_size_transfer ()
Stem for filename used to doc target element sizes on gmsh grid. No doc if stem is equal to empty string (or counter is negative)
int & counter_for_filename_gmsh_size_transfer ()
Counter for filename used to doc target element sizes on gmsh grid. No doc if stem is equal to empty string (or counter is negative)
bool projection_is_disabled ()
Is projection of old solution onto new mesh disabled?
void disable_projection ()
Disable projection of old solution onto new mesh.
void enable_projection ()
Disable projection of old solution onto new mesh.
std::string & gmsh_onscreen_output_file_name ()
Output filename for gmsh on-screen output.
unsigned & gmsh_onscreen_output_counter ()
Counter for marker that indicates where we are in gmsh on-screen output.
Private Attributes
TetMeshFacetedClosedSurface * Outer_boundary_pt
Pointer to outer boundary.
Vector< TetMeshFacetedSurface * > Internal_surface_pt
Internal boundaries.
double Element_volume
Uniform element volume.
std::string Target_size_file_name
Filename for target volume (for system-call based transfer to gmsh during mesh adaptation)
std::string Geo_and_msh_file_stem
Stem for geo and msh files (input/output to command-line gmsh invocation)
std::string Gmsh_command_line_invocation
Gmsh command line invocation string.
double Max_element_size
Max. element size during refinement.
double Min_element_size
Min. element size during refinement.
double Max_permitted_edge_ratio
Max edge ratio before remesh gets triggered.
double Dx_for_target_size_transfer
(Isotropic) grid spacing for target size transfer
unsigned Max_sample_points_for_limited_locate_zeta_during_target_size_transfer
Target size is transferred onto regular grid (for gmsh) by locate zeta. We try to find the exact point in the existing mesh but if we fail to converge from the nearest specified number of sample points we use the nearest of those.
std::string Stem_for_filename_gmsh_size_transfer
Stem for filename used to doc target element sizes on gmsh grid. No doc if stem is equal to empty string (or counter is negative)
int Counter_for_filename_gmsh_size_transfer
Counter for filename used to doc target element sizes on gmsh grid. No doc if stem is equal to empty string (or counter is negative)
bool Projection_is_disabled
Is projection of old solution onto new mesh disabled?
std::string Gmsh_onscreen_output_file_name
Output filename for gmsh on-screen output.
unsigned Gmsh_onscreen_output_counter
Counter for marker that indicates where we are in gmsh on-screen output.
Detailed Description
Class to collate parameters for Gmsh mesh generation.
Definition at line 49 of file gmsh_tet_mesh.template.h.
Constructor & Destructor Documentation
GmshParameters()
oomph::GmshParameters::GmshParameters (TetMeshFacetedClosedSurface *const & outer_boundary_pt, const std::string & gmsh_command_line_invocation) [inline]
Specify outer boundary of domain to be meshed. Other parameters get default values and can be set via member functions.
Definition at line 55 of file gmsh_tet_mesh.template.h.
Member Function Documentation
counter_for_filename_gmsh_size_transfer()
int & oomph::GmshParameters::counter_for_filename_gmsh_size_transfer () [inline]
Counter for filename used to doc target element sizes on gmsh grid. No doc if stem is equal to empty string (or counter is negative)
Definition at line 160 of file gmsh_tet_mesh.template.h.
References Counter_for_filename_gmsh_size_transfer.
disable_projection()
void oomph::GmshParameters::disable_projection () [inline]
Disable projection of old solution onto new mesh.
Definition at line 172 of file gmsh_tet_mesh.template.h.
References Projection_is_disabled.
dx_for_target_size_transfer()
double & oomph::GmshParameters::dx_for_target_size_transfer () [inline]
(Isotropic) grid spacing for target size transfer
Definition at line 135 of file gmsh_tet_mesh.template.h.
References Dx_for_target_size_transfer.
element_volume()
double & oomph::GmshParameters::element_volume () [inline]
Uniform target element volume.
Definition at line 89 of file gmsh_tet_mesh.template.h.
References Element_volume.
Referenced by oomph::GmshTetScaffoldMesh::write_geo_file().
enable_projection()
void oomph::GmshParameters::enable_projection () [inline]
Disable projection of old solution onto new mesh.
Definition at line 178 of file gmsh_tet_mesh.template.h.
References Projection_is_disabled.
geo_and_msh_file_stem()
std::string & oomph::GmshParameters::geo_and_msh_file_stem () [inline]
Stem for geo and msh files (input/output to command-line gmsh invocation)
Definition at line 110 of file gmsh_tet_mesh.template.h.
References Geo_and_msh_file_stem.
Referenced by oomph::GmshTetScaffoldMesh::create_mesh_from_msh_file(), oomph::GmshTetScaffoldMesh::GmshTetScaffoldMesh(), and oomph::GmshTetScaffoldMesh::write_geo_file().
gmsh_command_line_invocation()
std::string & oomph::GmshParameters::gmsh_command_line_invocation () [inline]
String to be issued via system command to activate gmsh.
Definition at line 103 of file gmsh_tet_mesh.template.h.
References Gmsh_command_line_invocation.
Referenced by oomph::GmshTetScaffoldMesh::GmshTetScaffoldMesh().
gmsh_onscreen_output_counter()
unsigned & oomph::GmshParameters::gmsh_onscreen_output_counter () [inline]
Counter for marker that indicates where we are in gmsh on-screen output.
Definition at line 191 of file gmsh_tet_mesh.template.h.
References Gmsh_onscreen_output_counter.
Referenced by oomph::GmshTetScaffoldMesh::GmshTetScaffoldMesh().
gmsh_onscreen_output_file_name()
std::string & oomph::GmshParameters::gmsh_onscreen_output_file_name () [inline]
Output filename for gmsh on-screen output.
Definition at line 184 of file gmsh_tet_mesh.template.h.
References Gmsh_onscreen_output_file_name.
Referenced by oomph::GmshTetScaffoldMesh::GmshTetScaffoldMesh().
internal_surface_pt()
Vector< TetMeshFacetedSurface * > & oomph::GmshParameters::internal_surface_pt () [inline]
Internal boundaries.
Definition at line 83 of file gmsh_tet_mesh.template.h.
References Internal_surface_pt.
Referenced by oomph::GmshTetMesh< ELEMENT >::build_it(), and oomph::GmshTetScaffoldMesh::write_geo_file().
max_element_size()
double & oomph::GmshParameters::max_element_size () [inline]
Max. element size during refinement.
Definition at line 117 of file gmsh_tet_mesh.template.h.
References Max_element_size.
Referenced by oomph::RefineableGmshTetMesh< ELEMENT >::initialise_adaptation_data().
max_permitted_edge_ratio()
double & oomph::GmshParameters::max_permitted_edge_ratio () [inline]
Max. permitted edge ratio.
Definition at line 129 of file gmsh_tet_mesh.template.h.
References Max_permitted_edge_ratio.
Referenced by oomph::RefineableGmshTetMesh< ELEMENT >::initialise_adaptation_data().
max_sample_points_for_limited_locate_zeta_during_target_size_transfer()
unsigned & oomph::GmshParameters::max_sample_points_for_limited_locate_zeta_during_target_size_transfer () [inline]
Target size is transferred onto regular grid (for gmsh) by locate zeta. We try to find the exact point in the existing mesh but if we fail to converge from the nearest specified number of sample points we use the nearest of those.
Definition at line 144 of file gmsh_tet_mesh.template.h.
References Max_sample_points_for_limited_locate_zeta_during_target_size_transfer.
min_element_size()
double & oomph::GmshParameters::min_element_size () [inline]
Min. element size during refinement.
Definition at line 123 of file gmsh_tet_mesh.template.h.
References Min_element_size.
Referenced by oomph::RefineableGmshTetMesh< ELEMENT >::initialise_adaptation_data().
outer_boundary_pt()
TetMeshFacetedClosedSurface *& oomph::GmshParameters::outer_boundary_pt () [inline]
Outer boundary.
Definition at line 77 of file gmsh_tet_mesh.template.h.
References Outer_boundary_pt.
Referenced by oomph::GmshTetMesh< ELEMENT >::build_it(), and oomph::GmshTetScaffoldMesh::write_geo_file().
projection_is_disabled()
bool oomph::GmshParameters::projection_is_disabled () [inline]
Is projection of old solution onto new mesh disabled?
Definition at line 166 of file gmsh_tet_mesh.template.h.
References Projection_is_disabled.
stem_for_filename_gmsh_size_transfer()
std::string & oomph::GmshParameters::stem_for_filename_gmsh_size_transfer () [inline]
Stem for filename used to doc target element sizes on gmsh grid. No doc if stem is equal to empty string (or counter is negative)
Definition at line 152 of file gmsh_tet_mesh.template.h.
References Stem_for_filename_gmsh_size_transfer.
target_size_file_name()
std::string & oomph::GmshParameters::target_size_file_name () [inline]
Filename for target volumes (for system-call based transfer to gmsh during mesh adaptation). Default: .gmsh_target_size_for_adaptation.dat.
Definition at line 97 of file gmsh_tet_mesh.template.h.
References Target_size_file_name.
Referenced by oomph::GmshTetScaffoldMesh::write_geo_file().
Member Data Documentation
Counter_for_filename_gmsh_size_transfer
int oomph::GmshParameters::Counter_for_filename_gmsh_size_transfer [private]
Counter for filename used to doc target element sizes on gmsh grid. No doc if stem is equal to empty string (or counter is negative)
Definition at line 244 of file gmsh_tet_mesh.template.h.
Referenced by counter_for_filename_gmsh_size_transfer().
Dx_for_target_size_transfer
double oomph::GmshParameters::Dx_for_target_size_transfer [private]
(Isotropic) grid spacing for target size transfer
Definition at line 227 of file gmsh_tet_mesh.template.h.
Referenced by dx_for_target_size_transfer().
Element_volume
double oomph::GmshParameters::Element_volume [private]
Uniform element volume.
Definition at line 204 of file gmsh_tet_mesh.template.h.
Referenced by element_volume().
Geo_and_msh_file_stem
std::string oomph::GmshParameters::Geo_and_msh_file_stem [private]
Stem for geo and msh files (input/output to command-line gmsh invocation)
Definition at line 212 of file gmsh_tet_mesh.template.h.
Referenced by geo_and_msh_file_stem().
Gmsh_command_line_invocation
std::string oomph::GmshParameters::Gmsh_command_line_invocation [private]
Gmsh command line invocation string.
Definition at line 215 of file gmsh_tet_mesh.template.h.
Referenced by gmsh_command_line_invocation().
Gmsh_onscreen_output_counter
unsigned oomph::GmshParameters::Gmsh_onscreen_output_counter [private]
Counter for marker that indicates where we are in gmsh on-screen output.
Definition at line 254 of file gmsh_tet_mesh.template.h.
Referenced by gmsh_onscreen_output_counter().
Gmsh_onscreen_output_file_name
std::string oomph::GmshParameters::Gmsh_onscreen_output_file_name [private]
Output filename for gmsh on-screen output.
Definition at line 250 of file gmsh_tet_mesh.template.h.
Referenced by gmsh_onscreen_output_file_name().
Internal_surface_pt
Vector<TetMeshFacetedSurface*> oomph::GmshParameters::Internal_surface_pt [private]
Internal boundaries.
Definition at line 201 of file gmsh_tet_mesh.template.h.
Referenced by internal_surface_pt().
Max_element_size
double oomph::GmshParameters::Max_element_size [private]
Max. element size during refinement.
Definition at line 218 of file gmsh_tet_mesh.template.h.
Referenced by max_element_size().
Max_permitted_edge_ratio
double oomph::GmshParameters::Max_permitted_edge_ratio [private]
Max edge ratio before remesh gets triggered.
Definition at line 224 of file gmsh_tet_mesh.template.h.
Referenced by max_permitted_edge_ratio().
Max_sample_points_for_limited_locate_zeta_during_target_size_transfer
unsigned oomph::GmshParameters::Max_sample_points_for_limited_locate_zeta_during_target_size_transfer [private]
Target size is transferred onto regular grid (for gmsh) by locate zeta. We try to find the exact point in the existing mesh but if we fail to converge from the nearest specified number of sample points we use the nearest of those.
Definition at line 234 of file gmsh_tet_mesh.template.h.
Referenced by max_sample_points_for_limited_locate_zeta_during_target_size_transfer().
Min_element_size
double oomph::GmshParameters::Min_element_size [private]
Min. element size during refinement.
Definition at line 221 of file gmsh_tet_mesh.template.h.
Referenced by min_element_size().
Outer_boundary_pt
TetMeshFacetedClosedSurface* oomph::GmshParameters::Outer_boundary_pt [private]
Pointer to outer boundary.
Definition at line 198 of file gmsh_tet_mesh.template.h.
Referenced by outer_boundary_pt().
Projection_is_disabled
bool oomph::GmshParameters::Projection_is_disabled [private]
Is projection of old solution onto new mesh disabled?
Definition at line 247 of file gmsh_tet_mesh.template.h.
Referenced by disable_projection(), enable_projection(), and projection_is_disabled().
Stem_for_filename_gmsh_size_transfer
std::string oomph::GmshParameters::Stem_for_filename_gmsh_size_transfer [private]
Stem for filename used to doc target element sizes on gmsh grid. No doc if stem is equal to empty string (or counter is negative)
Definition at line 239 of file gmsh_tet_mesh.template.h.
Referenced by stem_for_filename_gmsh_size_transfer().
Target_size_file_name
std::string oomph::GmshParameters::Target_size_file_name [private]
Filename for target volume (for system-call based transfer to gmsh during mesh adaptation)
Definition at line 208 of file gmsh_tet_mesh.template.h.
Referenced by target_size_file_name().
The documentation for this class was generated from the following file:
gmsh_tet_mesh.template.h