oomph::QuarterTubeMesh< ELEMENT > Class Template Reference
3D quarter tube mesh class. The domain is specified by the GeomObject that identifies boundary 3. Non-refineable base version!
#include <quarter_tube_mesh.template.h>
Public Member Functions
QuarterTubeMesh (GeomObject *wall_pt, const Vector< double > &xi_lo, const double &fract_mid, const Vector< double > &xi_hi, const unsigned &nlayer, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Pass pointer to geometric object that specifies the wall, start and end coordinates on the geometric object, and the fraction along which the dividing line is to be placed, and the timestepper. Timestepper defaults to Steady dummy timestepper.
virtual ~QuarterTubeMesh ()
Destructor: empty.
GeomObject *& wall_pt ()
Access function to GeomObject representing wall.
QuarterTubeDomain * domain_pt ()
Access function to domain.
QuarterTubeDomain::BLSquashFctPt & bl_squash_fct_pt ()
Function pointer for function that squashes the outer macro elements towards the wall by mapping the input value of the `radial` macro element coordinate to the return value (defined in the underlying Domain object)
virtual QuarterTubeDomain::AxialSpacingFctPt & axial_spacing_fct_pt ()
Function pointer for function for axial spacing.
QuarterTubeDomain * domain_pt () const
Access function to underlying domain.
Protected Attributes
QuarterTubeDomain * Domain_pt
Pointer to domain.
GeomObject * Wall_pt
Pointer to the geometric object that represents the curved wall.
Vector< double > Xi_lo
Lower limits for the coordinates along the wall.
double Fract_mid
Fraction along wall where outer ring is to be divided.
Vector< double > Xi_hi
Upper limits for the coordinates along the wall.
Detailed Description
template<class ELEMENT>
class oomph::QuarterTubeMesh< ELEMENT >
3D quarter tube mesh class. The domain is specified by the GeomObject that identifies boundary 3. Non-refineable base version!
The mesh boundaries are numbered as follows:
Boundary 0: `Inflow` cross section; located along the line parametrised by $ \xi_0 = \xi_0^{lo} $ on the geometric object that specifies the wall.
Boundary 1: Plane x=0
Boundary 2: Plane y=0
Boundary 3: The curved wall
Boundary 4: `Outflow` cross section; located along the line parametrised by $ \xi_0 = \xi_0^{hi} $ on the geometric object that specifies the wall.
IMPORTANT NOTE: The interface looks more general than it should. The toplogy must remain that of a quarter tube, or the mesh generation will break.
Definition at line 64 of file quarter_tube_mesh.template.h.
Constructor & Destructor Documentation
QuarterTubeMesh()
template<class ELEMENT >
oomph::QuarterTubeMesh< ELEMENT >::QuarterTubeMesh (GeomObject * wall_pt, const Vector< double > & xi_lo, const double & fract_mid, const Vector< double > & xi_hi, const unsigned & nlayer, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass pointer to geometric object that specifies the wall, start and end coordinates on the geometric object, and the fraction along which the dividing line is to be placed, and the timestepper. Timestepper defaults to Steady dummy timestepper.
Constructor for deformable quarter tube mesh class. The domain is specified by the GeomObject that identifies boundary 3. Pass pointer to geometric object that specifies the wall, start and end coordinates on the geometric object, and the fraction along which the dividing line is to be placed, and the timestepper. Timestepper defaults to Static dummy timestepper.
Definition at line 44 of file quarter_tube_mesh.template.cc.
References oomph::QuarterTubeMesh< ELEMENT >::Domain_pt, oomph::QuarterTubeMesh< ELEMENT >::wall_pt(), oomph::QuarterTubeMesh< ELEMENT >::Xi_hi, and oomph::QuarterTubeMesh< ELEMENT >::Xi_lo.
 QuarterTubeMesh()
template<class ELEMENT >
virtual oomph::QuarterTubeMesh< ELEMENT >::~QuarterTubeMesh () [inline], [virtual]
Destructor: empty.
Definition at line 80 of file quarter_tube_mesh.template.h.
References oomph::QuarterTubeMesh< ELEMENT >::Domain_pt.
Member Function Documentation
axial_spacing_fct_pt()
template<class ELEMENT >
virtual QuarterTubeDomain::AxialSpacingFctPt & oomph::QuarterTubeMesh< ELEMENT >::axial_spacing_fct_pt () [inline], [virtual]
Function pointer for function for axial spacing.
Reimplemented in oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >.
Definition at line 108 of file quarter_tube_mesh.template.h.
References oomph::QuarterTubeDomain::axial_spacing_fct_pt(), and oomph::QuarterTubeMesh< ELEMENT >::Domain_pt.
bl_squash_fct_pt()
template<class ELEMENT >
QuarterTubeDomain::BLSquashFctPt & oomph::QuarterTubeMesh< ELEMENT >::bl_squash_fct_pt () [inline]
Function pointer for function that squashes the outer macro elements towards the wall by mapping the input value of the `radial` macro element coordinate to the return value (defined in the underlying Domain object)
Definition at line 101 of file quarter_tube_mesh.template.h.
References oomph::QuarterTubeDomain::bl_squash_fct_pt(), and oomph::QuarterTubeMesh< ELEMENT >::Domain_pt.
domain_pt() [1/2]
template<class ELEMENT >
QuarterTubeDomain * oomph::QuarterTubeMesh< ELEMENT >::domain_pt () [inline]
Access function to domain.
Definition at line 92 of file quarter_tube_mesh.template.h.
References oomph::QuarterTubeMesh< ELEMENT >::Domain_pt.
Referenced by oomph::MacroElementNodeUpdateRefineableQuarterTubeMesh< ELEMENT >::setup_macro_element_node_update().
domain_pt() [2/2]
template<class ELEMENT >
QuarterTubeDomain * oomph::QuarterTubeMesh< ELEMENT >::domain_pt () const [inline]
Access function to underlying domain.
Definition at line 114 of file quarter_tube_mesh.template.h.
References oomph::QuarterTubeMesh< ELEMENT >::Domain_pt.
wall_pt()
template<class ELEMENT >
GeomObject *& oomph::QuarterTubeMesh< ELEMENT >::wall_pt () [inline]
Access function to GeomObject representing wall.
Definition at line 86 of file quarter_tube_mesh.template.h.
References oomph::QuarterTubeMesh< ELEMENT >::Wall_pt.
Referenced by oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::AlgebraicRefineableQuarterTubeMesh(), and oomph::QuarterTubeMesh< ELEMENT >::QuarterTubeMesh().
Member Data Documentation
Domain_pt
template<class ELEMENT >
QuarterTubeDomain* oomph::QuarterTubeMesh< ELEMENT >::Domain_pt [protected]
Pointer to domain.
Definition at line 121 of file quarter_tube_mesh.template.h.
Referenced by oomph::QuarterTubeMesh< ELEMENT >::axial_spacing_fct_pt(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::axial_spacing_fct_pt(), oomph::QuarterTubeMesh< ELEMENT >::bl_squash_fct_pt(), oomph::QuarterTubeMesh< ELEMENT >::domain_pt(), oomph::QuarterTubeMesh< ELEMENT >::QuarterTubeMesh(), oomph::RefineableQuarterTubeMesh< ELEMENT >::RefineableQuarterTubeMesh(), and oomph::QuarterTubeMesh< ELEMENT >::~QuarterTubeMesh().
Fract_mid
template<class ELEMENT >
double oomph::QuarterTubeMesh< ELEMENT >::Fract_mid [protected]
Fraction along wall where outer ring is to be divided.
Definition at line 130 of file quarter_tube_mesh.template.h.
Wall_pt
template<class ELEMENT >
GeomObject* oomph::QuarterTubeMesh< ELEMENT >::Wall_pt [protected]
Pointer to the geometric object that represents the curved wall.
Definition at line 124 of file quarter_tube_mesh.template.h.
Referenced by oomph::MacroElementNodeUpdateRefineableQuarterTubeMesh< ELEMENT >::setup_macro_element_node_update(), and oomph::QuarterTubeMesh< ELEMENT >::wall_pt().
Xi_hi
template<class ELEMENT >
Vector<double> oomph::QuarterTubeMesh< ELEMENT >::Xi_hi [protected]
Upper limits for the coordinates along the wall.
Definition at line 133 of file quarter_tube_mesh.template.h.
Referenced by oomph::QuarterTubeMesh< ELEMENT >::QuarterTubeMesh().
Xi_lo
template<class ELEMENT >
Vector<double> oomph::QuarterTubeMesh< ELEMENT >::Xi_lo [protected]
Lower limits for the coordinates along the wall.
Definition at line 127 of file quarter_tube_mesh.template.h.
Referenced by oomph::QuarterTubeMesh< ELEMENT >::QuarterTubeMesh().
The documentation for this class was generated from the following files:
quarter_tube_mesh.template.h
quarter_tube_mesh.template.cc