oomph Namespace Reference
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
Namespaces
 MeshExtrusionHelpers
Classes
class AnnularDomain
Annular domain.
class TwoDAnnularMesh
2D annular mesh with a unit circle in the middle and a layer of thickness h surrounding it.
class RefineableTwoDAnnularMesh
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
class BackwardStepQuadMesh
Backward step mesh.
class RefineableBackwardStepQuadMesh
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
class BrethertonSpineMesh
Mesh for 2D Bretherton problem -- based on single layer mesh. Templated by spine-ified Navier-Stokes element type (e.g. SpineElement<QCrouzeixRaviartElement<2> > and the corresponding interface element (e.g. SpineLineFluidInterfaceElement<SpineElement<QCrouzeixRaviartElement<2> > >
class BrickFromTetMesh
Brick mesh built by brickifying an existing tet mesh -- each tet gets split into four bricks. Can only be built with quadratic (27 node) elements.
class SolidBrickFromTetMesh
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
class RefineableBrickFromTetMesh
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
class RefineableSolidBrickFromTetMesh
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
class ChannelSpineMesh
Spine mesh class derived from standard 2D mesh. The mesh contains a StraightLine GeomObject which defines the height of the left and right regions (0,2) and another GeomObject is passed to the constructor to define the height in the central region.
class ChannelWithLeafletDomain
Rectangular domain with a leaflet blocking the lower half.
class ChannelWithLeafletMesh
Channel with leaflet mesh.
class RefineableChannelWithLeafletMesh
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
class MacroElementNodeUpdateChannelWithLeafletMesh
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
class MacroElementNodeUpdateRefineableChannelWithLeafletMesh
///////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////
class AlgebraicChannelWithLeafletMesh
//////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
class RefineableAlgebraicChannelWithLeafletMesh
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
class PseudoElasticChannelWithLeafletMesh
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
class CircularCylindricalShellMesh
A 2D solid mesh for (topologically) circular cylindrical shells. The shell is represented by two Lagrangian coordinates that correspond to z and theta in cylindrical polars. The required mesh is therefore a 2D mesh and is therefore inherited from the generic RectangularQuadMesh.
class CollapsibleChannelDomain
Collapsible channel domain.
class CollapsibleChannelMesh
Basic collapsible channel mesh. The mesh is derived from the SimpleRectangularQuadMesh so it's node and element numbering scheme is the same as in that mesh. Only the boundaries are numbered differently to allow the easy identification of the `collapsible` segment. Boundary coordinates are set up for all nodes located on boundary 3 (the collapsible segment). The curvilinear (`collapsible`) segment is defined by a GeomObject.
class RefineableCollapsibleChannelMesh
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
class MacroElementNodeUpdateCollapsibleChannelMesh
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
class MacroElementNodeUpdateRefineableCollapsibleChannelMesh
///////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////
class AlgebraicCollapsibleChannelMesh
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
class RefineableAlgebraicCollapsibleChannelMesh
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
class CylinderWithFlagDomain
Domain for cylinder with flag as in Turek benchmark.
class CylinderWithFlagMesh
Domain-based mesh for cylinder with flag as in Turek benchmark.
class RefineableCylinderWithFlagMesh
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
class AlgebraicCylinderWithFlagMesh
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
class RefineableAlgebraicCylinderWithFlagMesh
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
class EighthSphereDomain
Eighth sphere as domain. Domain is parametrised by four macro elements.
class EighthSphereMesh
Eight of a sphere brick mesh, based on the EightSphereDomain Non-refineable version with four brick elements. The eighth-sphere is located in the positive octant, centred at the origin. The mesh boundaries are numbered as follows:
class RefineableEighthSphereMesh
Refineable version of the eight of a sphere brick mesh. The eighth-sphere is located in the positive octant, centred at the origin. The mesh boundaries are numbered as follows:
class ExtrudedCubeMeshFromQuadMesh
Mesh class that takes a 2D mesh consisting of quadrilateral elements and `extrudes` it in the z-direction.
class RefineableExtrudedCubeMeshFromQuadMesh
///////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////
class FishDomain
Fish shaped domain, represented by four MacroElements. Shape is parametrised by GeomObject that represents the fish's back.
class FishMesh
Fish shaped mesh. The geometry is defined by the Domain object FishDomain.
class RefineableFishMesh
////////////////////////////////////////////////////////////////////
class MacroElementNodeUpdateRefineableFishMesh
Refineable fish shaped mesh with MacroElement-based node update. The fish's back is represented by a specified geometric object. Some or all of the geometric Data in that geometric object may contain unknowns in the global Problem. The dependency on these unknowns is taken into account when setting up the Jacobian matrix of the elements. For this purpose, the element (whose type is specified by the template parameter) must inherit from MacroElementNodeUpdateElementBase.
class AlgebraicFishMesh
////////////////////////////////////////////////////////////////////
class AlgebraicRefineableFishMesh
////////////////////////////////////////////////////////////////////
class FSIDrivenCavityMesh
Mesh for W. Wall's FSI driven cavity problem. The mesh is derived from the SimpleRectangularQuadMesh so it's node and element numbering scheme is the same as in that mesh. Only the boundaries are numbered differently to allow the easy identification of the `collapsible` segment. Boundary coordinates are set up for all nodes located on boundary 3 (the collapsible segment). The curvilinear (`collapsible`) segment is defined by a GeomObject.
class RefineableFSIDrivenCavityMesh
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
class AlgebraicFSIDrivenCavityMesh
/ Alebraic node update version of FSIDrivenCavityMesh
class RefineableAlgebraicFSIDrivenCavityMesh
//////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
class FullCircleDomain
Topologically circular domain, e.g. a tube cross section. The entire domain must be defined by a GeomObject with the following convention: zeta[0] is the radial coordinate and zeta[1] is the theta coordinate around the cross-sectin. The outer boundary must lie at zeta[0] = 1.
class FullCircleMesh
Full circle mesh class. The domain is specified by the GeomObject that identifies the entire area. Non-refineable base version!
class RefineableFullCircleMesh
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
class GeompackQuadMesh
Quadrilateral mesh generator; Uses input from Geompack++. See: http://members.shaw.ca/bjoe/ Currently only for four-noded quads -- extension to higher-order quads should be trivial (see the corresponding classes for triangular meshes).
class GmshParameters
Class to collate parameters for Gmsh mesh generation.
class TetEdge
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
class GmshTetMesh
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
class GmshTetScaffoldMesh
class RefineableGmshTetMesh
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
class HermiteQuadMesh
A two dimensional Hermite bicubic element quadrilateral mesh for a topologically rectangular domain. The geometry of the problem must be prescribed using the TopologicallyRectangularDomain. Non uniform node spacing can be prescribed using a function pointer.
class HorizontalSingleLayerSpineMesh
Horizontal Single-layer spine mesh class derived from standard 2D mesh. The mesh contains a layer of spinified fluid elements (of type ELEMENT; e.g SpineElement<QCrouzeixRaviartElement<2>) and the information required to update their position. Additional equations must be specified in order to determine how the spines move.
class OneDLagrangianMesh
1D mesh parametrised in terms of a 1D Lagrangian coordinate. The Eulerian positions of the nodes are determined by the GeomObject.
class OneDMesh
1D mesh consisting of N one-dimensional elements from the QElement family.
class RefineableOneDMesh
Refineable version of the OneDMesh.
class QuadFromTriangleMesh
Quad mesh built on top of triangle scaffold mesh coming from the triangle mesh generator Triangle. http://www.cs.cmu.edu/~quake/triangle.html.
class RefineableQuadFromTriangleMesh
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
class SolidQuadFromTriangleMesh
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
class RefineableSolidQuadFromTriangleMesh
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
class QuarterCircleSectorDomain
Circular sector as domain. Domain is bounded by curved boundary which is represented by a GeomObject. Domain is parametrised by three macro elements.
class QuarterCircleSectorMesh
2D quarter ring mesh class. The domain is specified by the GeomObject that identifies boundary 1.
class RefineableQuarterCircleSectorMesh
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
class MacroElementNodeUpdateRefineableQuarterCircleSectorMesh
MacroElementNodeUpdate version of RefineableQuarterCircleSectorMesh.
class AlgebraicRefineableQuarterCircleSectorMesh
Algebraic version of RefineableQuarterCircleSectorMesh.
class QuarterPipeDomain
Domain representing a quarter pipe.
class QuarterPipeMesh
Non refineable quarter pipe mesh class Deform a simple cubic mesh into a quarter pipe r: radial direction theta: azimuthal direction z: axis direction.
class RefineableQuarterPipeMesh
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
class ElasticQuarterPipeMesh
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
class ElasticRefineableQuarterPipeMesh
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
class QuarterTubeDomain
Quarter tube as domain. Domain is bounded by curved boundary which is represented by a GeomObject. Domain is parametrised by three macro elements in each of the nlayer slices.
class QuarterTubeMesh
3D quarter tube mesh class. The domain is specified by the GeomObject that identifies boundary 3. Non-refineable base version!
class RefineableQuarterTubeMesh
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
class MacroElementNodeUpdateRefineableQuarterTubeMesh
MacroElementNodeUpdate version of RefineableQuarterTubeMesh.
class AlgebraicRefineableQuarterTubeMesh
AlgebraicMesh version of RefineableQuarterTubeMesh.
class RectangleWithHoleDomain
Rectangular domain with circular whole.
class RectangleWithHoleMesh
Domain-based mesh for rectangular mesh with circular hole.
class RefineableRectangleWithHoleMesh
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
class RectangleWithHoleAndAnnularRegionDomain
Rectangular domain with circular whole DRAIG: This looks like a redefinition of the RectangleWithHoleAndAnnularRegionDomain in src/meshes but it creates 8 macro-elements instead of 4 macro-elements and creates an annular region around the cylinder. It's probably a good idea to rename this class to avoid ambiguity and a name clash...
class RectangleWithHoleAndAnnularRegionMesh
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
class RefineableRectangleWithHoleAndAnnularRegionMesh
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
class RefineableQuadMeshWithMovingCylinder
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
class RectangularQuadMesh
RectangularQuadMesh is a two-dimensional mesh of Quad elements with Nx elements in the `x` (horizonal) direction and Ny elements in the `y` (vertical) direction. Two Constructors are provided. The basic constructor assumes that the lower-left-hand corner of the mesh is (0,0) and takes only the arguments, Nx, Ny, Xmax and Ymax. The more complex constructor takes the additional arguments Xmin and Ymin.
class RefineableRectangularQuadMesh
Refineable version of the RectangularQuadMesh: A two-dimensional mesh of Quad elements with Nx elements in the `x` (horizonal) direction and Ny elements in the `y` (vertical) direction. Two Constructors are provided. The basic constructor assumes that the lower-left-hand corner of the mesh is (0,0) and takes only the arguments, Nx, Ny, Xmax and Ymax. The more complex constructor takes the additional arguments Xmin and Ymin.
class ElasticRectangularQuadMesh
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
class ElasticRefineableRectangularQuadMesh
/////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
class RefineableTetgenMesh
class RefineableSolidTetgenMesh
////////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////////
class SimpleCubicMesh
Simple cubic 3D Brick mesh class.
class RefineableSimpleCubicMesh
///////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////
class SimpleCubicTetMesh
MySimple 3D tet mesh for TElements.
class SimpleRectangularQuadMesh
Simple rectangular 2D Quad mesh class. Nx : number of elements in the x direction.
class SimpleRectangularTriMesh
Simple 2D triangular mesh for TElements.
class SingleLayerCubicSpineMesh
Spine mesh class derived from standard cubic 3D mesh. The mesh contains a layer of spinified fluid elements (of type ELEMENT; e.g SpineElement<QCrouzeixRaviartElement<3>) for 3D problems, in which the interface's vertical position can vary.
class SingleLayerSpineMesh
Single-layer spine mesh class derived from standard 2D mesh. The mesh contains a layer of spinified fluid elements (of type ELEMENT; e.g SpineElement<QCrouzeixRaviartElement<2>). It constructs the spines and contains the information on how to update the nodal positions within the mesh as a function of the spine lengths. Equations that determine the spine heights (even if they are pinned) must be specified externally or else there will be problems.
class TetgenMesh
Unstructured tet mesh based on output from Tetgen: http://wias-berlin.de/software/tetgen/.
class SolidTetgenMesh
/////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////
class ThinLayerBrickOnTetMesh
Brick mesh layer built on top of a given tet mesh. Typically used in FSI problems where the tet mesh is the fluid mesh and this mesh acts as the solid mesh that surrounds the FSI interface.
class RefineableThinLayerBrickOnTetMesh
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
class SolidThinLayerBrickOnTetMesh
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
class RefineableSolidThinLayerBrickOnTetMesh
//////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
class TopologicallyRectangularDomain
Topologically Rectangular Domain - a domain dexcribing a topologically rectangular problem - primarily contains functions to access the position of the global boundary relative to the macro element boundary, as well as first and second derivates of the global boundary wrt the macro element boundary NOTE : suitable for HermiteElementQuadMesh.
struct classcomp
class TriangleMeshParameters
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
class TriangleMesh
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
class RefineableTriangleMesh
/////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
class SolidTriangleMesh
////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
class RefineableSolidTriangleMesh
///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
class TubeDomain
Tube as a domain. The entire domain must be defined by a GeomObject with the following convention: zeta[0] is the coordinate along the centreline, zeta[1] is the theta coordinate around the tube wall and zeta[2] is the radial coordinate. The outer boundary must lie at zeta[2] = 1.
class TubeMesh
3D tube mesh class. The domain is specified by the GeomObject that identifies the entire volume. Non-refineable base version!
class RefineableTubeMesh
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
class TwoLayerSpineMesh
Two-layer spine mesh class derived from standard 2D mesh. The mesh contains two layers of spinified fluid elements (of type ELEMENT; e.g SpineElement<QCrouzeixRaviartElement<2>).
class XdaTetMesh
Tet mesh made of quadratic (ten node) tets built from xda input file.
class SolidXdaTetMesh
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
Functions
void triangulate (char *triswitches, struct oomph::TriangulateIO *in, struct oomph::TriangulateIO *out, struct oomph::TriangulateIO *vorout)
Variables
struct oomph::classcomp Bottom_left_sorter
Detailed Description
////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
Function Documentation
triangulate()
void oomph::triangulate (char * triswitches, struct oomph::TriangulateIO * in, struct oomph::TriangulateIO * out, struct oomph::TriangulateIO * vorout)
Referenced by oomph::QuadFromTriangleMesh< ELEMENT >::generic_constructor(), oomph::TriangleMesh< ELEMENT >::generic_constructor(), oomph::RefineableTriangleMesh< ELEMENT >::RefineableTriangleMesh(), and oomph::TriangleMesh< ELEMENT >::TriangleMesh().
Variable Documentation
Bottom_left_sorter
struct oomph::classcomp oomph::Bottom_left_sorter
Referenced by oomph::RefineableTriangleMesh< ELEMENT >::sort_nodes_on_shared_boundaries().