PseudoSolidCapProblem< ELEMENT > Class Template Reference
A class that solves the Navier--Stokes equations to compute the shape of a static interface in a rectangular container with imposed contact angle at the boundary.
Public Member Functions
PseudoSolidCapProblem (const bool &hijack_internal)
Constructor: Boolean flag indicates if volume constraint is applied by hijacking internal or external pressure.
~PseudoSolidCapProblem ()
Destructor: clean up memory allocated by the object.
void parameter_study (const string &dir_name)
Peform a parameter study: Solve problem for a range of contact angles Pass name of output directory as a string.
void doc_solution (DocInfo &doc_info)
Doc the solution.
Private Member Functions
void create_free_surface_elements ()
Create the free surface elements.
void create_volume_constraint_elements ()
Create the volume constraint elements.
void create_contact_angle_element ()
Create the contact angle element.
Private Attributes
double Ca
The Capillary number.
double Volume
The prescribed volume of the fluid.
double Pext
The external pressure.
double Angle
The contact angle.
ConstitutiveLaw * Constitutive_law_pt
Constitutive law used to determine the mesh deformation.
Data * External_pressure_data_pt
Data object whose single value stores the external pressure.
Data * Traded_pressure_data_pt
ofstream Trace_file
Trace file.
Mesh * Bulk_mesh_pt
Storage for the bulk mesh.
Mesh * Free_surface_mesh_pt
Storage for the free surface mesh.
Mesh * Free_surface_bounding_mesh_pt
Storage for the element bounding the free surface.
Mesh * Volume_computation_mesh_pt
Storage for the elements that compute the enclosed volume.
Mesh * Volume_constraint_mesh_pt
Storage for the volume constraint.
Detailed Description
template<class ELEMENT>
class PseudoSolidCapProblem< ELEMENT >
A class that solves the Navier--Stokes equations to compute the shape of a static interface in a rectangular container with imposed contact angle at the boundary.
Definition at line 512 of file axi_static_cap.cc.
Constructor & Destructor Documentation
PseudoSolidCapProblem()
template<class ELEMENT >
PseudoSolidCapProblem< ELEMENT >::PseudoSolidCapProblem (const bool & hijack_internal)
Constructor: Boolean flag indicates if volume constraint is applied by hijacking internal or external pressure.
Constructor: Pass boolean flag to indicate if the volume constraint is applied by hijacking an internal pressure or the external pressure.
Definition at line 592 of file axi_static_cap.cc.
References PseudoSolidCapProblem< ELEMENT >::Bulk_mesh_pt, PseudoSolidCapProblem< ELEMENT >::Constitutive_law_pt, PseudoSolidCapProblem< ELEMENT >::create_contact_angle_element(), PseudoSolidCapProblem< ELEMENT >::create_free_surface_elements(), PseudoSolidCapProblem< ELEMENT >::create_volume_constraint_elements(), PseudoSolidCapProblem< ELEMENT >::External_pressure_data_pt, PseudoSolidCapProblem< ELEMENT >::Free_surface_bounding_mesh_pt, PseudoSolidCapProblem< ELEMENT >::Free_surface_mesh_pt, Global_Physical_Variables::Nu, PseudoSolidCapProblem< ELEMENT >::Pext, PseudoSolidCapProblem< ELEMENT >::Traded_pressure_data_pt, PseudoSolidCapProblem< ELEMENT >::Volume_computation_mesh_pt, PseudoSolidCapProblem< ELEMENT >::Volume_constraint_mesh_pt, and Global_Physical_Variables::Wall_normal.
 PseudoSolidCapProblem()
template<class ELEMENT >
PseudoSolidCapProblem< ELEMENT >::~PseudoSolidCapProblem
Destructor: clean up memory allocated by the object.
Destructor. Make sure to clean up all allocated memory, so that multiple instances of the problem don't lead to excessive memory usage.
Definition at line 764 of file axi_static_cap.cc.
Member Function Documentation
create_contact_angle_element()
template<class ELEMENT >
void PseudoSolidCapProblem< ELEMENT >::create_contact_angle_element [private]
Create the contact angle element.
Definition at line 898 of file axi_static_cap.cc.
References Global_Physical_Variables::wall_unit_normal_fct().
Referenced by PseudoSolidCapProblem< ELEMENT >::PseudoSolidCapProblem().
create_free_surface_elements()
template<class ELEMENT >
void PseudoSolidCapProblem< ELEMENT >::create_free_surface_elements [private]
Create the free surface elements.
Definition at line 805 of file axi_static_cap.cc.
Referenced by PseudoSolidCapProblem< ELEMENT >::PseudoSolidCapProblem().
create_volume_constraint_elements()
template<class ELEMENT >
void PseudoSolidCapProblem< ELEMENT >::create_volume_constraint_elements [private]
Create the volume constraint elements.
Definition at line 852 of file axi_static_cap.cc.
Referenced by PseudoSolidCapProblem< ELEMENT >::PseudoSolidCapProblem().
doc_solution()
template<class ELEMENT >
void PseudoSolidCapProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
Definition at line 977 of file axi_static_cap.cc.
parameter_study()
template<class ELEMENT >
void PseudoSolidCapProblem< ELEMENT >::parameter_study (const string & dir_name)
Peform a parameter study: Solve problem for a range of contact angles Pass name of output directory as a string.
Perform a parameter study. Pass name of output directory as a string.
Definition at line 935 of file axi_static_cap.cc.
Member Data Documentation
Angle
template<class ELEMENT >
double PseudoSolidCapProblem< ELEMENT >::Angle [private]
The contact angle.
Definition at line 551 of file axi_static_cap.cc.
Bulk_mesh_pt
template<class ELEMENT >
Mesh* PseudoSolidCapProblem< ELEMENT >::Bulk_mesh_pt [private]
Storage for the bulk mesh.
Definition at line 568 of file axi_static_cap.cc.
Referenced by PseudoSolidCapProblem< ELEMENT >::PseudoSolidCapProblem().
Ca
template<class ELEMENT >
double PseudoSolidCapProblem< ELEMENT >::Ca [private]
The Capillary number.
Definition at line 542 of file axi_static_cap.cc.
Constitutive_law_pt
template<class ELEMENT >
ConstitutiveLaw* PseudoSolidCapProblem< ELEMENT >::Constitutive_law_pt [private]
Constitutive law used to determine the mesh deformation.
Definition at line 554 of file axi_static_cap.cc.
Referenced by PseudoSolidCapProblem< ELEMENT >::PseudoSolidCapProblem().
External_pressure_data_pt
template<class ELEMENT >
Data* PseudoSolidCapProblem< ELEMENT >::External_pressure_data_pt [private]
Data object whose single value stores the external pressure.
Definition at line 557 of file axi_static_cap.cc.
Referenced by PseudoSolidCapProblem< ELEMENT >::PseudoSolidCapProblem().
Free_surface_bounding_mesh_pt
template<class ELEMENT >
Mesh* PseudoSolidCapProblem< ELEMENT >::Free_surface_bounding_mesh_pt [private]
Storage for the element bounding the free surface.
Definition at line 574 of file axi_static_cap.cc.
Referenced by PseudoSolidCapProblem< ELEMENT >::PseudoSolidCapProblem().
Free_surface_mesh_pt
template<class ELEMENT >
Mesh* PseudoSolidCapProblem< ELEMENT >::Free_surface_mesh_pt [private]
Storage for the free surface mesh.
Definition at line 571 of file axi_static_cap.cc.
Referenced by PseudoSolidCapProblem< ELEMENT >::PseudoSolidCapProblem().
Pext
template<class ELEMENT >
double PseudoSolidCapProblem< ELEMENT >::Pext [private]
The external pressure.
Definition at line 548 of file axi_static_cap.cc.
Referenced by PseudoSolidCapProblem< ELEMENT >::PseudoSolidCapProblem().
Trace_file
template<class ELEMENT >
ofstream PseudoSolidCapProblem< ELEMENT >::Trace_file [private]
Trace file.
Definition at line 565 of file axi_static_cap.cc.
Traded_pressure_data_pt
template<class ELEMENT >
Data* PseudoSolidCapProblem< ELEMENT >::Traded_pressure_data_pt [private]
Definition at line 562 of file axi_static_cap.cc.
Referenced by PseudoSolidCapProblem< ELEMENT >::PseudoSolidCapProblem().
Volume
template<class ELEMENT >
double PseudoSolidCapProblem< ELEMENT >::Volume [private]
The prescribed volume of the fluid.
Definition at line 545 of file axi_static_cap.cc.
Volume_computation_mesh_pt
template<class ELEMENT >
Mesh* PseudoSolidCapProblem< ELEMENT >::Volume_computation_mesh_pt [private]
Storage for the elements that compute the enclosed volume.
Definition at line 577 of file axi_static_cap.cc.
Referenced by PseudoSolidCapProblem< ELEMENT >::PseudoSolidCapProblem().
Volume_constraint_mesh_pt
template<class ELEMENT >
Mesh* PseudoSolidCapProblem< ELEMENT >::Volume_constraint_mesh_pt [private]
Storage for the volume constraint.
Definition at line 580 of file axi_static_cap.cc.
Referenced by PseudoSolidCapProblem< ELEMENT >::PseudoSolidCapProblem().
The documentation for this class was generated from the following file:
axi_static_cap.cc